### PR TITLE
Improved Configuration and ModuleManagerBuilder performances

### PR DESCRIPTION
**Pull request by jocel1**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Try to improve performances |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Run tests |

### CODE REVIEW

**Comment by jocel1** [comment]
With the latest push : https://blackfire.io/profiles/compare/2ef4e603-7428-455a-adac-a0237595da50/graph

**Comment by mickaelandrieu** [comment]
@jocel1 build relaunched, thank you :)

**Comment by mickaelandrieu** [comment]
@jocel1 would you mind to provide a blackfire report ? :)

**Comment by jocel1** [comment]
@mickaelandrieu it seems the comment with the link has been deleted, so adding it again ;)
https://blackfire.io/profiles/compare/2ef4e603-7428-455a-adac-a0237595da50/graph

**Comment by mickaelandrieu** [comment]
LGTM.

Thank you @jocel1

**Pull request merged**
