### PR TITLE
Fix shipping cost becoming free if more than a half or available quantity ordered

### LINKED ISSUE #9694: [BOOM-5163] Shipping costs become free when the product qty is beeing changed in BO order
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5163).

- _**Reporter:**_ Connie
- _**Created at:**_ Thu, 22 Mar 2018 17:55:10 +0100

<p>This bug can be reproduces on clean install with demo goods.</p>

<p>Let we have some goods with total quantity 50 and simple carrier with some shipping cost.</p>

<p>The buyer creates an order and the shop calculates the shipping costs. For example he buys 20 qty. So in the BO one can see that in order qty 20 and 30 is available for the other buyers.</p>

<p>After that the buyer lets know that he wants to change quantyty and the new quantyty should be 30. Actually it could be any that would be equal or greater than quantity left.</p>

<p>The seller changes the quantuty to 30 and after that the shipping becomes free.</p>

<p>The problem is in the class Order method refreshShippingCost() line 2501. </p>

<p>First in lines 2521-2524 fake cart gets zero quantyty and after that in lines 2526-2529 cart is sets with real quantity that the admin set.</p>

<p>If you have a look at the methor updateQty in the class Cart you can see that this method is invoked with default parametn operator = 'up'  so we get to the next if in the class Cart, line 1283 where the new quantity is been checked as the addon, not the new quantity. <br/>
Since new quantity in not less that the quantity available for order the method updateQty returns false.</p>

<p>But this false result is not processed, see the class Order line 2528.</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by LedCloud**
If more than a half specifiend in BO the shipping cost becomes free.

To fix that we should pass skipAvailabilityCheckOutOfStock  set to true to updateQty in class Cart
(classes/Cart.php)

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | If the order is beeing edited in BO and the quantity changed to more than a half of available qty the shipping cost gets free.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9694.
| How to test?  | Create an order in BO or FO with qty less than a half of availble. Correct qty in BO so the new qty would be more than a haft, it leads to shipping become free.

Issue link - https://github.com/PrestaShop/PrestaShop/issues/9694

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12711)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @LedCloud,

As reported by Travis, you Travis does not pass all the tests.

```
SYNTAX TESTS FAILED
Run PHP CS Fixer from your PrestaShop folder to fix the lint issues:
- Linux: "php ./vendor/bin/php-cs-fixer fix"
- Windows: "vendor\bin\php-cs-fixer fix"
```

**Comment by LedCloud** [comment]
I did. Hope that helps.

**Comment by Quetzacoalt91** [comment]
It did, thanks!

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @LedCloud

**Pull request merged**
