### PR TITLE
Merge 8.1.x into develop

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI / tests UI are green
| Fixed issue or discussion?     | -
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
There's a git conflict 😢

**Comment by M0rgan01** [comment]
Tests ui: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6147154778

**Comment by matks** [comment]
The PR is still in draft @M0rgan01 is it on purpose?

**Comment by M0rgan01** [comment]
@matks yes, pending the resolution of conflicts. PR is not ready

**Comment by nesrineabdmouleh** [comment]
UI tests => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/6147212572

**Review by boherm — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @M0rgan01 !

**Pull request merged**
