### PR TITLE
Merge 177x into develop 08/09/2020

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Merge 1.7.7.x into develop
| Type?         | improvement
| Category?     | ME
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20939)

### CODE REVIEW

**Comment by jolelievre** [comment]
Same problem as in https://github.com/PrestaShop/PrestaShop/pull/20898 so I close this one (actually build instance are shared between the two PRs)

**Review by matks — APPROVED** [review]

**Review by Sinepel — APPROVED** [review]

**Comment by PierreRambaud** [comment]
I'm afraid about this commit 7fcf6b7f45b11ec56a05d08995832b44c021d6dd which is fixing something that happened only in PHP7.2 :( 
We are trying to hide something that will pop in our face the future :(

**Comment by matks** [comment]
> I'm afraid about this commit [7fcf6b7](https://github.com/PrestaShop/PrestaShop/commit/7fcf6b7f45b11ec56a05d08995832b44c021d6dd) which is fixing something that happened only in PHP7.2 :(
> We are trying to hide something that will pop in our face the future :(

Yes but blocking this PR from being merged means `develop` grows more and more distant from `1.7.7.x` :/

Can we merge this PR **but** create a issue for 178 "critical" ?

**Comment by PierreRambaud** [comment]
> > I'm afraid about this commit [7fcf6b7](https://github.com/PrestaShop/PrestaShop/commit/7fcf6b7f45b11ec56a05d08995832b44c021d6dd) which is fixing something that happened only in PHP7.2 :(
> > We are trying to hide something that will pop in our face the future :(
> 
> Yes but blocking this PR from being merged means `develop` grows more and more distant from `1.7.7.x` :/
> 
> Can we merge this PR **but** create a issue for 178 "critical" ?

What will we have to add in the issue? we must be able to reproduce it :sweat_smile:

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
Thank you @jolelievre

**Comment by matks** [comment]
> 7fcf6b7

The issue wi

> > > I'm afraid about this commit [7fcf6b7](https://github.com/PrestaShop/PrestaShop/commit/7fcf6b7f45b11ec56a05d08995832b44c021d6dd) which is fixing something that happened only in PHP7.2 :(
> > > We are trying to hide something that will pop in our face the future :(
> > 
> > 
> > Yes but blocking this PR from being merged means `develop` grows more and more distant from `1.7.7.x` :/
> > Can we merge this PR **but** create a issue for 178 "critical" ?
> 
> What will we have to add in the issue? we must be able to reproduce it 😅

See https://github.com/PrestaShop/PrestaShop/issues/20954 and https://github.com/PrestaShop/PrestaShop/pull/20953

**Pull request merged**
