### PR TITLE
Merge `1.7.8.x` into `8.0.x`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Merge `1.7.8.x` into `8.0.x`
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A

For @PrestaShop/prestashop-maintainers

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
Thank you @Progi1984 . It's a quite simple merge I think it does not need QA, wdyt @PrestaShop/qa-team ?

**Comment by HanaRebaiQA** [comment]
Hello @matks,

We think that we should test this PR and run the automated tests on it.

Thanks!

**Review by matks — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Comment by boubkerbribri** [comment]
FYI : We will only run automated tests for this pull request to validate it

**Review by boubkerbribri — APPROVED** [review]
Automated tests are OK :heavy_check_mark:

**Comment by matks** [comment]
Thank you @Progi1984

**Pull request merged**
