### PR TITLE
IN : Added US military base codes

### PR DESCRIPTION
**Pull request by Dh42**
| Questions | Answers |
| --- | --- |
| Branch? | Develop |
| Description? | Added US military base addresses |
| Type? | Improvement |
| Category? | IN |
| BC breaks? | No |
| Deprecations? | No |
| Fixed ticket? |  |
| How to test? | Try to ship a package to the military |

For usage see
http://www.columbia.edu/~fdc/postal/#usa

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by AlexEven** [comment]
@Dh42 Thanks for this!

Would it be possible to complete your PR by providing the full names of the bases?
I'm not sure everyone will know what it is about when looking at the states list:
image

Thank you!
Best,

**Comment by Dh42** [comment]
These are not bases names, from everything I know they don't use the full names they just use the 2 letter iso codes.

**Comment by xBorderie** [comment]
I suggest the following names:

* AA: "U.S. Armed Forces – Americas"
* AE: "U.S. Armed Forces – Europe"
* AP: "U.S. Armed Forces – Pacific"

**Comment by inetbiz** [comment]
@AlexEven https://support.shippingeasy.com/hc/en-us/articles/203085299-How-to-Format-Military-mail-addresses And the confusion right now is which 3 letter designation should be used for which GEO location. For example: "Does AE ( Europe ) use Fleet shipping or Air?"

**Comment by xBorderie** [comment]
Dunno what Frenchness has to do with it, I'm just trying to make a suggestion here, so that this data can be readable to everyone. I simply copy-pasted what I found in https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations (green lines in the long table).

Now, as far as I know, those codes are not used on parcel addresses, but are used to configure carrier using ISO codes -- and AA/AE/AP are USPS codes, not ISO ones (according to the Wikipedia page above, there are no ISO codes for US military bases). I don't know how the system works in order to build the final parcel address. I need to test this.

**Comment by firstred** [comment]
I think that they (USPS?) literally need the abbreviations on the printed address. By avoiding the full names there's no need to convert these later on, e.g. when printing the shipment label or when exporting the order data.

**Comment by xBorderie** [comment]
According to @inetbiz 's link, USPS need some other codes that only AA/AE/AP. Am I right?

**Comment by Dh42** [comment]
@xavier It was not meant as an insult, I just meant that the way you were suggesting is not how it is used in practice. If you scroll down to close to the bottom on the USPS site here, https://www.usps.com/ship/apo-fpo-dpo.htm  you can see how it needs to appear on the label. 

As for the other code you are correct, but that needs to be added in the city field manually.

**Pull request merged**
