### PR TITLE
Fix saving status code 410 on the product page v1

### LINKED ISSUE #29945: The 410 redirection is not saved on product page V1
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The 410 Gone was made onto the product page v2.

But the product page v1 show the help text and the option to choose the 410 as redirection.
It's seems not handled/saved.

### Expected behavior

_No response_

### Steps to reproduce

1. Go to product settings
2. Change the redirection to 410

See that it's not handled in Front Office and that on refresh is 301.

### PrestaShop version(s) where the bug happened

8.0.0-beta.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | This PR fixes saving the product page v1, another PR will fix not working behavior in the front office
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29945
| Related PRs       | https://github.com/PrestaShop/classic-theme/pull/62
| How to test?      | follow the issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by kpodemski** [comment]
@jolelievre I've just rebased on RC branch :)

**Review by ghost — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @kpodemski 

Thank you for your PR, I tested it and it works, as we can see here :

[Untitled_ Oct 17, 2022 2_39 PM.webm](https://user-images.githubusercontent.com/100699445/196211309-f7941cc4-4646-4f15-824e-dca903a23baf.webm)

It's a QA :heavy_check_mark: but I don't know if it's the good wording 

Thank you

**Review by jolelievre — CHANGES_REQUESTED** [review]
I believe this PR requires updating the classic theme

**Comment by jolelievre** [comment]
Blocked by https://github.com/PrestaShop/PrestaShop/pull/30005

**Review by jolelievre — APPROVED** [review]
Unblocked!

**Comment by Robin-Fischer-PS** [comment]
Hi @jolelievre !

Since the PR was tested and QA Approved previously, do we need to test it again ? If so, what should we check (what could have been chnaged between the previous QA approved and now) ?

Thanks :)

**Comment by kpodemski** [comment]
@Robin-Fischer-PS IMHO it would be good to re-test it, just to make sure

two scenarios:

1. new product page 410
2. old product page 410

**Comment by AureRita** [comment]
Hi @kpodemski 

Thank you for your PR and for this information I tested these two scenario and it works, as we can see here :

[Untitled_ Oct 24, 2022 11_58 AM.webm](https://user-images.githubusercontent.com/100699445/197501474-20442ffa-2be1-43d5-aad6-5c68e7fb2cb9.webm)

It's QA approved :heavy_check_mark: 

Thanks

**Comment by jolelievre** [comment]
Thanks @AureRita and @kpodemski

**Pull request merged**
