### PR TITLE
Enable hook 'displayAfterProductThumbs' to access product - thanks @elburgl69

### LINKED ISSUE #19940: Hook displayAfterProductThumbs should give $product in the context
#### hook displayAfterProductThumbs has no product context

When I try to use the displayAfterProductThumbs hook in my module, I get no context of the product I am working with.

#### product-cover-thumbnails.tpl should add the product. 

The displayAfterProductThumbs hook should call the hook in product-cover-thumbnails.tpl like (last line):

```
{hook h='displayAfterProductThumbs' product=$product}
```
#### Alternatives you've considered

None

#### Additional context

None

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Enable hook 'displayAfterProductThumbs' to access product for better customization capabilities
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/19940
| How to test?  | I will provide a test module when review is ☑️ 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20132)

### CODE REVIEW

**Comment by Progi1984** [comment]
@matks Please look at the @PierreRambaud module. It would be a perfect sample.

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
> @matks Please look at the @PierreRambaud module. It would be a perfect sample.

If it's ready for this PR, indeed it will be a good test ! 😄

**Comment by PierreRambaud** [comment]
> > @matks Please look at the @PierreRambaud module. It would be a perfect sample.
> 
> If it's ready for this PR, indeed it will be a good test !

Not yet, but on Monday you will be able to test a template file :D 
(Only working with PHP right now)

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]
The module ps_qualityassurance is ready :) You only need to add a content of the hook you wanted to test.

**Comment by khouloudbelguith** [comment]
Hi @matks,

It is ok :heavy_check_mark: 
I used this module
[mymod.zip](https://github.com/PrestaShop/PrestaShop/files/4919180/mymod.zip)

Thanks!

**Comment by matks** [comment]
Thank you everybody for participating, and special thanks to @elburgl69 for the suggestion

**Comment by Progi1984** [comment]
@matks Don't forget to update docs ;)

**Comment by matks** [comment]
> @matks Don't forget to update docs ;)

What should I update 🤔  ? AFAIK devdocs does not mention hook arguments

**Comment by Progi1984** [comment]
@matks Sorry, I believed that [Core Changes](https://devdocs.prestashop.com/1.7/modules/core-updates/) had this info.

**Pull request merged**
