### PR TITLE
Removed deprecated in Adapter namespace

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed deprecated in Adapter namespace
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4576294464
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks
* Removed method `handleProductsUpdate` in class `PrestaShop\PrestaShop\Adapter\Category\CommandHandler\AbstractDeleteCategoryHandler`
* Removed default value for parameter `$imageTagSourceParser` for the constructor of the class `PrestaShop\PrestaShop\Adapter\Profile\QueryHandler\GetProfileForEditingHandler`
* Removed class `PrestaShop\PrestaShop\Adapter\Shop\Url\ProductImageFolderProvider`
* Removed abstract class `PrestaShop\PrestaShop\Adapter\SpecificPrice\AbstractSpecificPriceHandler`
* Removed class `PrestaShop\PrestaShop\Adapter\SpecificPrice\CommandHandler\AddSpecificPriceHandler`
* Removed class `PrestaShop\PrestaShop\Adapter\SpecificPrice\CommandHandler\DeleteSpecificPriceByCartProductHandler`
* Removed class `PrestaShop\PrestaShop\Adapter\Twig\LocaleExtension`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\Command\AddSpecificPriceCommand`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\Command\DeleteSpecificPriceByCartProductCommand`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\CommandHandler\AddSpecificPriceHandlerInterface`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\CommandHandler\DeleteSpecificPriceByCartProductHandlerInterface`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\Exception\CannotSetSpecificPricePrioritiesException`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\Exception\SpecificPriceConstraintException`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\Exception\SpecificPriceException`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\Exception\SpecificPriceNotFoundException`
* Removed class `PrestaShop\PrestaShop\Core\Domain\SpecificPrice\ValueObject\SpecificPriceId`
* Removed service `prestashop.adapter.specific_price.command_handler.add_specific_price`
* Removed service `prestashop.adapter.specific_price.command_handler.delete_specific_price_by_cart_product`

### CODE REVIEW

**Review by FabienPapet — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/committers /@PrestaShop/prestashop-maintainers Open to review

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team let me know if we can merge it without manual tests

**Comment by Progi1984** [comment]
Oh :hankey: : My auto tests were :green_circle: but I recreated my repository and that was removed.

Do you want that I restart them ?

**Comment by kpodemski** [comment]
@Progi1984 please do, unless QA wants to run them :-))

**Comment by Progi1984** [comment]
:heavy_check_mark: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4576294464

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

It's OK for us!

**Comment by kpodemski** [comment]
@Progi1984 auto tests are not green

**Comment by Progi1984** [comment]
UI tests are fixed here :#32012

**Pull request merged**
