### PR TITLE
Merge 8.0.x into 8.1.x

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Merge 8.0.x into 8.1.x
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is green. tests: https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5575300122
| Fixed ticket?     | -
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by M0rgan01 — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Please update the PR with last commit of the `8.0.x` branch

**Review by Progi1984 — APPROVED** [review]
OK for UI tests

**Review by boherm — APPROVED** [review]

**Comment by boherm** [comment]
https://github.com/boherm/ga.tests.ui.pr/actions/runs/5584745876

**Review by M0rgan01 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/ui-tests-maintainers It's ok for approval. Please approve.

**Review by boubkerbribri — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @mflasquin

**Pull request merged**
