### PR TITLE
Combination images now use the legend if any

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | It's useful for the user to see the legend instead of the filepath on the roll over of the image
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3544
| How to test?  | Complete le legend field of a combination image and then try to edit a combination in back office. On the Combination form, in the bottom of page you'll find the "Images" section.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8499)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Can you please rebase @mickaelandrieu?

**Comment by tomlev** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8499#-:-Kz971kIoxpRaCj1bwaE:bnfp4nl)*

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 done!
@tomlev thanks for review

**Comment by Quetzacoalt91** [comment]
Have you checked potential calls to this function?

https://github.com/PrestaShop/PrestaShop/blob/90d396fc446f7d066c5c240398de54f9b7b2e6f0/src/PrestaShopBundle/Controller/Admin/ProductImageController.php#L129

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 nice catch :+1:  fixed

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8499#-:-KzXk_x-H-8DuTqaUbMX:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Nice one

**Comment by marionf** [comment]
@mickaelandrieu I have a 500 when I click on an image and the image form isn't here

capture du 2017-11-24 14-09-56

**Comment by mickaelandrieu** [comment]
@marionf the feature need much more work than I expected, because the Upload/Image block don't rely at all on locale change introduced by the language selector.

@eternoendless as it's not a bug fix, can we plan to delay this issue? We need to introduce a state in Product page to get some data like the selected locale, langage and make the change everywhere, I don't want to introduce one more quircks here. I'm faced the same issue than @aleeks (https://github.com/PrestaShop/PrestaShop/pull/8200) for the same reasons: the language/locale are inconsistents in the application, and so on we need to fix the state before use locale/language.

**Pull request closed without merging**
