### PR TITLE
Logo is saved with wrong MIME type

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | https://github.com/PrestaShop/PrestaShop/issues/15066
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/15066
| How to test?  | https://github.com/PrestaShop/PrestaShop/issues/15066

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15067)

### CODE REVIEW

**Comment by MathiasReker** [comment]
@eternoendless I think this should target 1.7.6.1 because wrong MIME type can be critical.

**Comment by matks** [comment]
Hi @MathiasReker thanks for the PR !

I have a question 🤔here you modify the extension in the name, so if in the BO "png" has been configured for config `PS_IMAGE_QUALITY`, then the logo filename will be `mylogo.png` instead of `mylogo.jpg` => this is what your PR does.

But this is only the filename. The image is either a JPG or a PNG. What happens if someone 1) configures the BO to PNG but 2) uploads a JPG ? Will it save it with `.png` even the file is a JPG ?

**Comment by mickaelandrieu** [comment]
Hello @matks & @MathiasReker,

I guess this can be linked to this issue: https://github.com/PrestaShop/PrestaShop/issues/14693

I have the feeling that the core "service/class" used to manage the upload is buggy. This is not a regression from 1.7.5 afaik, so on I'm not that sure this should be "quick-fixed" in 1.7.6.1.

Cheers

**Comment by MathiasReker** [comment]
@matks you are right! What I am doing is not going to work in any case. I assumed that users uploade the file with same extension as selected in `Configuration::get('PS_IMAGE_QUALITY')`.
But that might not be the case. What I want to do is to get the extension of the uploaded image.

**Comment by MathiasReker** [comment]
@mickaelandrieu Please check this URL with IE11: https://iqit-commerce.com/ps17/demo5/en/
image

The logo is not displayed in some browsers. I think that is critical. Therefor I attempted to fix it for 1.7.6.1 :-)

**Comment by MathiasReker** [comment]
See this screenshot. A `JPG` image with transparent background. :trollface: 

jpg

As it is in 1.7.6.0 all logo files is forced with `JPG` even if they are `PNG`. In some cases the browser cannot decode the image because of wrong MIME type.

**Comment by matks** [comment]
> As it is in 1.7.6.0 all logo files is forced with `JPG` even if they are `PNG`. In some cases the browser cannot decode the image because of wrong MIME type.

That's what I was afraid of 😱
So the issue is even worse: the filename has wrong extension AND the filename extension is unrelated to the **real** extension

I think we need a better (meaning: more complex) management of the topic

**Comment by matks** [comment]
I think we need to do the following:
- only accept valid image formats to be uploaded, other formats must be rejected (need to define what is valid 😬)
- save the uploaded files with the right extension

**Comment by MathiasReker** [comment]
> 
> 
> I think we need to do the following:
> 
>     * only accept valid image formats to be uploaded, other formats must be rejected (need to define what is valid 😬)
> 
>     * save the uploaded files with the right extension

Yes, agree on that. I am not the right person do that, so I don't update my PR. Should I close this PR or should I let it stay open until a new one is created?

**Comment by eternoendless** [comment]
It's best to close it for now. Thanks @MathiasReker for pointing out the problem.

**Pull request closed without merging**
