### PR TITLE
Fixed modal content when bulk delete combinations

### LINKED ISSUE #25901: BO - Warning is empty when we try to delete all combinations
#### Describe the bug

In the BO > Catalog > Products > Product details page combinations Tab, when we try to delete all combinations => the warning is empty
image

#### Expected behavior

It should be
image

#### Steps to Reproduce

1. Go to BO > Catalog > Products page
2. Edit a product with combinations
3. In the combinations Tab > select all combinations and click on `Delete combinations`
4. See an error

#### Additional information

* PrestaShop version: 1.7.8.0rc1build4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed modal content when bulk delete combinations
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25901
| How to test?      | Cf. #25901
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25904)

### CODE REVIEW

**Comment by Julievrz** [comment]
I think it would be more relevant to have "Delete %number_of_selected_combinations% combinations"? for the title. I don't think a body is needed here, as there's nothing relevant to add. See the [Content style guide](https://zeroheight.com/80a6c5a61/v/latest/p/510e8a-components/b/253853).
image

**Comment by Progi1984** [comment]
@Julievrz ; It's a patch version : we can't add new wordings. But it can be done in 8.0.0 version.

**Comment by Julievrz** [comment]
> @Julievrz ; It's a patch version : we can't add new wordings. But it can be done in 8.0.0 version.

Oops, my bad! You're right. Then it's ok :-)

**Review by Julievrz — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

Thanks for the PR, works great !

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
