### PR TITLE
Merge 177x into develop 22/09/2020

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Merge 1.7.7.x into develop
| Type?         | improvement
| Category?     | ME
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21096)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Do not update tests/Integration/Behaviour/bootstrap.php, but use tests/Integration/bootstrap.php, it should work.

**Review by jolelievre — DISMISSED** [review]

**Comment by jolelievre** [comment]
@PierreRambaud I don't think so:
- the Integration boostrap defines more consts, require the autoload manually
- the behat one loads the kernel

They don't do the same thing 🤷‍♂️

**Comment by PierreRambaud** [comment]
> @PierreRambaud I don't think so:
> 
> * the Integration boostrap defines more consts, require the autoload manually
> * the behat one loads the kernel
> 
> They don't do the same thing

One is not used and must be removed :)

**Comment by sowbiba** [comment]
@PierreRambaud The behat one is loaded in https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php#L56

And the integration one in https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/phpunit.xml#L1

**Comment by PierreRambaud** [comment]
> @PierreRambaud The behat one is loaded in https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Behaviour/Features/Context/CommonFeatureContext.php#L56
> 
> And the integration one in https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/phpunit.xml#L1

:scream: I miss that suite sorry :sob:

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sowbiba

**Pull request merged**
