### PR TITLE
Prevent wrong redirect with ssl

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If we're under https connection we don't want to be redirect on http when we are redirecting to another page.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Navigate in BO with with https, loose the session (remove cookie, logout in other tab) and wait for the redirection, without the fix you're redirecting in http. Url Example: https://ps-develop.localhost/admin-dev/index.php?controller=AdminOrders

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9232)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
@fatmaBouchekoua Do you know why e2e tests are failing? :)

**Comment by Quetzacoalt91** [comment]
Tested on my shop, running without virtual host and in a subfolder. It works. :+1: 

@PierreRambaud can you rebase your PR? Now that you updated `develop` with the `1.7.4.x` changes.

**Comment by PierreRambaud** [comment]
I rebased, but still don't understand why E2E tests are failing -_-' Any idea @fatmaBouchekoua @Quetzacoalt91  ?

**Comment by Quetzacoalt91** [comment]
The only reason I see is a error 500, or an issue ... with a generated link? :stuck_out_tongue:

**Comment by Quetzacoalt91** [comment]
When I'm on your PR, the product list in the cart is empty when I try to change its quantity. Weird.

**Comment by Quetzacoalt91** [comment]
Also even if I haven't enabled SSL some link are now using thie HTTPS protocol, for instance on the cart.

**Comment by PierreRambaud** [comment]
Weird, but after investigation, it look like it's the desired behavior. I closed this PR, we need to investigate to have a better way to ssl =)

**Pull request closed without merging**
