### PR TITLE
Add recommended length counters to SEO fields in CMS Pages Add/Edit and SEO Add/Edit URLs

### LINKED ISSUE #14266: Add recommended length counters to SEO fields in CMS Pages Add/Edit and SEO Add/Edit URLs
Suggestion from @CreaNico
We have added a character length counter to SEO fields for Categories:
Capture d’écran 2019-06-17 à 11 56 29

We should do the same for other SEO fields:
- [x] meta title and meta description for CMS Pages
- [x] title and meta description for URLs (in trafic & SEO page)

Recommended lengths for SEO: 70 for titles, 160 for descriptions (edited)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add recommended length counters to SEO fields in CMS Pages Add/Edit and SEO Add/Edit URLs
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #14266
| How to test?      | Go to Trafic & SEO page and to the "Add/Edit an URL" form, the fields "page title" and "meta description" have a working SEO chars counter (70c for title & 160 for description). <br />Go to CMS Page and to the "Add/Edit" form, the fields "meta title" and "meta description" have a working SEO chars counter (70c for title & 160 for description).

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm 👍

**Review by Hlavtox — APPROVED** [review]
Good!!!

**Review by sLorenzini — APPROVED** [review]
hi @Progi1984,

Thank you for this PR.
Tested on develop branch with PHP 7.3.

Tested on SEO & traffic page and CMS pages, multistore activated & deactivated:

Successful creation alert is displayed when:

1. new page with title and meta description longer than recommended characters
2. new page with title and meta description shorter than recommended characters
3. new page with title longer and meta description shorter than recommended characters
4. new page with title shorter and meta description longer than recommended characters

---------------------------

Successful update alert is displayed

1. edit page with already existing page in the default shop with title and meta description longer than recommended characters
2. edit page with already existing page in the default shop with title and meta description shorter than recommended characters
3. edit page with already existing page in the default shop with title longer and meta description shorter than recommended characters
4. edit page with already existing page in the default shop with title shorter and meta description longer than recommended characters
5. edit page with newly created page in shop with title and meta description longer than recommended characters
6. edit page with newly created page in shop with title and meta description shorter than recommended characters
7. edit page with newly created page in shop with title longer and meta description shorter than recommended characters
8. edit page with newly created page in shop with title shorter and meta description longer than recommended characters

---------------------------------

Error on fields concerned

1. new page with title and meta description with invalid characters longer or shorter than recommended characters
2. edit page with already existing page on the default shop with invalid characters longer or shorter than recommended characters
3. edit page with newly created page in shop with invalid characters longer or shorter than recommended characters

QA approved ✅ 

Thanks

**Review by matks — APPROVED** [review]
I'm happy to see the work I started in https://github.com/PrestaShop/PrestaShop/pull/14469/ getting delivered

Thank you @Progi1984

**Pull request merged**
