### PR TITLE
Avoid clear ranges when click on "Free shipping"

### LINKED ISSUE #15214: After Enabling "Free shipping" in the carriers page => the ranges shouldn't be emptied
**Is your feature request related to a problem? Please describe.**
In the BO => Shipping => Carriers page => after adding some Ranges to a specific carrier => when we enable the Free Shipping option, Ranges shouldn't be emptied
1. 
carrier1
2. Enable Free shipping
image021

It could be fixed with this
https://github.com/PrestaShop/PrestaShop/issues/10586

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix #15214
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #15214
| Related PRs       | [#30886](https://github.com/PrestaShop/PrestaShop/pull/30886)
| How to test?      | Follow the issue 😊
| Possible impacts? | ~

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hi @marsaldev,

I followed this speck https://github.com/PrestaShop/PrestaShop/issues/15214#issuecomment-529529976
I found some issues:

**First issue**
_When enabling "Free Shipping", the content of the table should not be **visible**_

1. Go to BO > Shipping > Add new carrier
2. Set a name and a Transit time > click on Next
3. Free shipping is disabled
4. Select a Billing
5. Add some ranges for all countries for example
image
6. Enable Free shipping
7. See error > All ranges are visible
image

**Second issue**
_When enabling "Free Shipping", the content of the table should not be visible or **editable**_

1. Go to BO > Shipping > Add new carrier
2. Set a name and a Transit time > click on Next
3. Free shipping is disabled
4. Select a Billing
5. Add some ranges for all countries for example
image
1. Enable Free shipping
2. Click on All twice to unselect and select it again 
3. Set a number and click outside 
4. See error => we can edit all ranges

I attached a screen record

https://user-images.githubusercontent.com/16067358/174815178-f572396c-60ee-41c4-9bde-8f8cfbb9e6c2.mp4

Also, I have some blocked issues: https://github.com/PrestaShop/PrestaShop/issues/28588, https://github.com/PrestaShop/PrestaShop/issues/28810

I can test the free shipping case

Thanks!

**Comment by marsaldev** [comment]
Hi @khouloudbelguith ! Thanks for your time!

**First issue**:
I don't think if it is a real issue 😊, also if you disable the single zone, the value/s is/are still visible 🤔

**Second issue**:
Totally right, I was able to reproduce it, I'm going to work on it 😉

**Review by kpodemski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @MatShir 

According to spec  the content table **should not be visible or editable** . https://github.com/PrestaShop/PrestaShop/issues/15214#issuecomment-529529976

The existing case of this pr is : the content table is **still visible** but **not editable** ! you can see the screen record

[Untitled_ Nov 10, 2022 8_53 AM.webm](https://user-images.githubusercontent.com/31663369/201045456-cb7ace90-8ddd-4e73-a464-549ea13f29b0.webm)


WDT ?

Thanks !

**Comment by MatShir** [comment]
Looks good, the checkboxes are still editable. Disabling the checkbox would have been better, but I think we ca go with that ! Thanks for the work @marsaldev

**Review by matks — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @marsaldev, 

I just tested the PR and I report a lot of problem.

1. If I enable Free Shipping, all the boxes are grayed out, I can no longer see the values entered.
2. If I disable Free Shipping afterwards, all the values entered before have disappeared
3. If I create additional ranges, I enable Free Shipping, click on "Finish", and return to my carrier edition, the additional ranges have disappeared.
4. This PR fails auto-test.


https://watch.screencastify.com/v/jlXpxQGGmEJ7DkieDxmv

**Comment by marsaldev** [comment]
Hi @paulnoelcholot, it's strange that you report a completely different feedback than @sallemiines.
Have you cleaned the browser cache? Can you do a pair check with her?

**Comment by marsaldev** [comment]
@paulnoelcholot @sallemiines gently reminder 😊

**Review by florine2623 — COMMENTED** [review]
Hello @marsaldev ,

Link to automated tests :x: : https://github.com/florine2623/testing_pr/actions/runs/3928574366
Could you check this issue please ?

I have found an issue while testing your PR. I think it is out-of-scope to fix it in this PR.
It is the same as : https://github.com/PrestaShop/PrestaShop/issues/16521

I have found a work around by enabling Free shipping directly on the list of carriers :

https://user-images.githubusercontent.com/16019289/212649777-d400753e-7b81-4966-8244-8e1043bdde97.mov

@khouloudbelguith 's second issue can't be reproduced
@sallemiines 's issue has been seen with @MatShir 
@paulnoelcholot 's 3rd issue is normal behavior as this feature is only available while editing the carrier on step 2  and not after the Saving process.

Followed https://github.com/PrestaShop/PrestaShop/issues/15214#issuecomment-529529976 & https://github.com/PrestaShop/PrestaShop/pull/28720#issuecomment-1312836059 ✅ 

Functional tests are OK, only automated test are broken.
@PrestaShop/qa-automation could you check this one please ? 

Thanks!

**Comment by florine2623** [comment]
As discussed with @nesrineabdmouleh , this PR is validated.
It needs to wait @nesrineabdmouleh PR for automated tests before being merged.

=> https://github.com/PrestaShop/PrestaShop/pull/30886

Thanks!

**Comment by kpodemski** [comment]
Thank you @marsaldev

**Pull request merged**
