### PR TITLE
Delete shopping carts

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This scenario tests the deletion of a not ordered shopping cart and a shopping cart related to an order
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | run the script: path=full/01_orders/5_delete_shopping_carts.js npm run specific-test -- --URL=URLFrontOffice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8977)

### CODE REVIEW

**Review by marionf — DISMISSED** [review]
It's ok for the functional scenario

**Review by mbadrani — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
need rebase

**Comment by fatmaBouchekoua** [comment]
Done !

**Review by mbadrani — APPROVED** [review]

**Comment by mbadrani** [comment]
@eternoendless can you merge it please, because of codacy we cannot proceed

**Comment by PierreRambaud** [comment]
Thanks @fatmaBouchekoua

**Pull request merged**
