### PR TITLE
Show list bullets on product page and align it

### LINKED ISSUE #15498: Wrong text formatting <li>
Hello!
When I format text in the BO like List it looks like Ok
image
 But in the FO the indent is lost

image

PS 1.7.5.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Bullets where hidden on product page when PO team thinks if people use it in BO they wants to see these on the page
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15498
| How to test?  | Put a list with items on a product description and see if bullets are on the product page description. Please rebuild assets.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16856)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG the indent is missing 
Capture d’écran 2019-12-19 à 12 51 19

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
Conflict on assets
- for QA team: please rebuild assets 😄
- after QA ✅we need to rebase and rebuild

**Comment by matks** [comment]
@NeOMakinG one rebase to get rid of the git conflict, and we can merge 😄

**Comment by NeOMakinG** [comment]
Should be fine now, thanks @sarahdib @matks

**Review by matks — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Review by photinia73 — COMMENTED** [review]
Hello!
Unfortunately thees changes didn't help. The list has the same look. 
image
I made the changes in the my Theme but nothing happend...

**Comment by NeOMakinG** [comment]
@photinia73 unfortunately it should be related to your theme

**Comment by matks** [comment]
@photinia73 can we see your theme online ? is it inspired / a child of classic theme ?

**Comment by photinia73** [comment]
https://te.com.ua/uk/stereo-pidsilyuvachi-integralni/2635-marantz-pm7000n.html
If you need access to ftp to see the Theme code give me please your e-mail. This is the Theme by HiddenTechies

**Comment by photinia73** [comment]
At last it work! But in the such way
 .product-description  ul {
      list-style: inherit;
      list-style-position: inside;
      padding-left: 1.75rem;
    }
and only from file themes/pixtronpro/assets/css/custom.css
from this file themes/classic/_dev/css/components/products.scss no effect....

**Comment by matks** [comment]
> At last it work! But in the such way
> .product-description ul {
> list-style: inherit;
> list-style-position: inside;
> padding-left: 1.75rem;
> }
> and only from file themes/pixtronpro/assets/css/custom.css
> from this file themes/classic/_dev/css/components/products.scss no effect....

SCSS files are actually source code that needs to be compiled 😉see [SASS](https://sass-lang.com/guide) and [PrestaShop assets compilation](https://devdocs.prestashop.com/1.7/development/compile-assets/)

**Comment by matks** [comment]
Thank you @NeOMakinG

**Comment by photinia73** [comment]
WOW, so many interesting news, will learn! Thank you very much!

**Pull request merged**
