### PR TITLE
Build assets on 1.7.7.x 

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Build assets before 1.7.7.6 release
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | none
| How to test?      | none
| Possible impacts? |

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25449)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matks — COMMENTED** [review]
`themes/classic/assets/js/theme.js ` is completely deleted, is that expected?

**Comment by atomiix** [comment]
@matks it's not completely deleted, it has been minified!
Capture d’écran 2021-07-28 à 16 35 19

**Comment by matks** [comment]
> @matks it's not completely deleted, it has been minified!
> Capture d’écran 2021-07-28 à 16 35 19

Nice find

**Comment by matks** [comment]
Thank you @matthieu-rolland

**Pull request merged**
