### PR TITLE
Properly set the test database by taking into account the environment  with console commands

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fix tests
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Run tests with another db name than prestashop

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8886)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @jocel1 this was a hack I wasn't proud for :/

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
This is not something that can be validated by QA.

Can someone approve this contribution ? /c @eternoendless maybe?

**Review by mickaelandrieu — APPROVED** [review]

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8886#-:-L8ffBWmAKd-vVvxJSIv:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Thank you @jocel1 :heart:

**Pull request merged**
