### PR TITLE
Remove obsolete P3P policy

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | P3P header is obsolete: https://en.wikipedia.org/wiki/P3P
| Type?         | improvement
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | / 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12748)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Closing / reopening in order to trigger Travis

**Comment by Quetzacoalt91** [comment]
Hi @MathiasReker,

Looks like Travis does not want to test your PR. Can you please do a `git commit --amend` followed by a `git push -f` please? Updating the sha1 should refresh Travis.

**Comment by MathiasReker** [comment]
@Quetzacoalt91 sure :)

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @MathiasReker

**Pull request merged**
