### PR TITLE
Fix line endings in theme's JS files

### PR DESCRIPTION
**Pull request by mcdado**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Fix line endings in JavaScript theme files.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Check out the files and verify the line endings, they should be LF instead of CRLF.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks! Are you sure your indentation is correct? 'cos I need to point to https://github.com/PrestaShop/PrestaShop/pull/7607/files?w=1 :)

**Comment by mcdado** [comment]
Well… I didn't want to put too many style corrections into this PR. All `.js` theme files are tab indented, I just followed that, and I don't think I made indentation mistakes, right? Otherwise let me know where exactly and I'll correct it, as usual.

That said, I had to correct the line endings because I have a big heart! ❤️  😉

**Comment by mcdado** [comment]
I would gladly make a PR with an `eslint` run of all js files in the theme directory. Let me know! if that's be okay.

**Comment by Quetzacoalt91** [comment]
Hello @mcdado,

What error are you trying to fix ? I tried to reproduce the initial problem but unfortunately nothing is reported in the console on this page.

capture d ecran 2017-03-06 a 09 29 18

**Comment by mcdado** [comment]
screen shot 2017-03-06 at 09 55 21

Line 410 of `global.js` is as follows in my current theme:
`$.totalStorage('display', 'list');`

Actually, now that I think of it, I didn't test it against current default theme, since we have a theme that is based on it, I thought it couldn't be too different since we generally pull upstream patches. Can you try to force running `bindGrid()` from `global.js` and see if that causes errors to you?

**Comment by Quetzacoalt91** [comment]
Hello,

The function bindGrid() handles properly the non-existing storage and returns before executing anything related to the view:

```js
function bindGrid()
{
    console.log('bindGrid() called');
	var storage = false;
	if (typeof(getStorageAvailable) !== 'undefined') {
		storage = getStorageAvailable();
	}
	if (!storage) {
		return; // <- returns here
	}
``` 

Console output:
capture d ecran 2017-03-06 a 11 18 46

**Comment by mcdado** [comment]
That's right, it was already implemented… 6528fe99ff2adb38233f9d347af3e95236e5267d

Well, then let me amend my commits and do just the line ending fixes

**Comment by mcdado** [comment]
Okay I deleted the extra change, now it's only linde endings.

**Review by Quetzacoalt91 — APPROVED** [review]
All right, this PR can now be merged.

**Comment by mcdado** [comment]
Rebased on top of `1.6.1.x`.

**Comment by xBorderie** [comment]
Cheers David! 🎉

**Comment by maximebiloe** [comment]
Thank you @mcdado

**Pull request merged**
