### PR TITLE
Execute displayAdminLogin hook without shop context

### LINKED ISSUE #13962: Error with hook displayAdminLogin
### BUG 1
**Describe the bug**
Hook `displayAdminLogin` is not in table `ps_hook`, so a module can not be hooked manually in this position unless you call `registerHook` function.

**To Reproduce**
1. Install module dummymodule_v1.zip
[dummymodule_v1.zip](https://github.com/PrestaShop/PrestaShop/files/3216911/dummymodule_v1.zip)
2. Go to "Design -> Positions -> Insert a module"
3. Can't be hooked to 'displayAdminLogin` because this position doesn't appear
4. Uninstall and remove module
5. Install module dummymodule_v2.zip
[dummymodule_v2.zip](https://github.com/PrestaShop/PrestaShop/files/3216910/dummymodule_v2.zip)
6. Go to "Design -> Positions"
7. Module is hooked to `displayAdminLogin`. You can unhook and hook module because now position is at `ps_hook` table.

**Hook `displayAdminLogin` should be inserted in `ps_hook` table in installation.**

**Additinnal information**
PrestaShop version: 1.7.6

### BUG 2
**Describe the bug**
Hook is linked with "multishop" and it shouldn't. It should be executed always, doesn't matter the shop context.

**To Reproduce**
1. Create a multishop with 2 stores
2. Go to "Modules -> Catalog manager"
3. Select the store with ID 2 in the store selector
4. Install module dummymodule_v2.zip
[dummymodule_v2.zip](https://github.com/PrestaShop/PrestaShop/files/3216910/dummymodule_v2.zip)
5. Open BO login page in an Incognito tab
6. Hook `displayAdminLogin` is not executed
8. Uninstall module
9. Select the store with ID 1 in the store selector
10. Install module dummymodule_v2.zip
11. Reload the previous BO login page opened
12. Hook `displayAdminLogin` is executed (appears a string `Dummy module` under the login box)

Hook is only executed if you install module in "All shops" context or in Multistore ID 1, while in BO login page there is not a shop context yet. Query that retrieves module hooks for hook `displayAdminLogin` should not take into consideration shop context.

**Additional information**
PrestaShop version: 1.7.6

### PR DESCRIPTION
**Pull request by idnovate**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Hook is not executed if module is not hooked to displayAdminLogin in store ID 1
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13962
| How to test?  | Please see [issue](https://github.com/PrestaShop/PrestaShop/issues/13962)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13980)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Since it's the legacy behavior I approve this PR.

**Comment by sarahdib** [comment]
Hello @idnovate 

Thank you for your contribution. 

I found an error when I clic on transplant a module 

image

**Comment by idnovate** [comment]
@sarahdib I couldn't reproduce the issue in a fresh PS 1.7.6.0 install with the patch applied. Could you give me more information? If you undo the patch the issue is fixed? Are you testing in a multistore?

image

**Comment by sarahdib** [comment]
@idnovate ok I don't understand what's happen before. I can't reproduce the error.

I test again and it's OK.

Thank you

**Comment by matks** [comment]
We need to re-run PrettyCI, build got lost I think

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @idnovate

**Comment by PierreRambaud** [comment]
Thanks @idnovate

**Pull request merged**
