### PR TITLE
Make the menu scrollable

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Make the menu scrollable
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3502
| How to test?  |

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]
Code looks good

**Comment by marionf** [comment]
Hello @maximebiloe 
When hovering, the submenus no longer appear. I have to click on the main menu to see them appear.

**Comment by TristanGie** [comment]
Just so you know, issue came back with PS 1.7.3.

**Comment by eternoendless** [comment]
Yeah, the menu is being completely redone in 1.7.4: https://github.com/PrestaShop/PrestaShop/pull/8637

**Pull request closed without merging**
