### PR TITLE
Replace getsupplierlink with getSupplierLink

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix case typo to standardize. I didn't see that there was the same problem as on #25187 before, sorry!
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Just check if the links to each supplier's page are OK in the list of suppliers

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25267)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Sinepel** [comment]
Hi @Progi1984 @matthieu-rolland 
Can you see why merge checks do not work? 
If necessary, please tell me how to fix it?
Thank you for your help!

**Comment by kpodemski** [comment]
@Sinepel I think that everything should be all right once you rebase your PR once again 👍

**Comment by Sinepel** [comment]
@kpodemski Hi ! It's done :)

**Review by kpodemski — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @Sinepel

**Pull request merged**
