### PR TITLE
Test with PHP 8.0 version

### LINKED ISSUE #18547: PrestaShop must be compatible with PHP 8.0
PHP 8.0 is out and PrestaShop must be compatible

**Related issues:**
- [x] https://github.com/PrestaShop/PrestaShop/issues/17300
- [x] https://github.com/PrestaShop/PrestaShop/issues/20739
- [x] https://github.com/PrestaShop/PrestaShop/issues/17351
- [x] #25921
- [x] #25922

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Test with PHP 8.0 version
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | fixes #18547
| How to test?  | CI needs to pass before merge

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20703)

### CODE REVIEW

**Comment by mvorisek** [comment]
how to debug the error?
```
https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/377609629#L491
```

**Comment by mvorisek** [comment]
```
ParseError: syntax error, unexpected token "match", expecting variable
```
@PierreRambaud do you know what is causing these errors and how to fix it?

**Comment by PierreRambaud** [comment]
> ```
> ParseError: syntax error, unexpected token "match", expecting variable
> ```
> 
> @PierreRambaud do you know what is causing these errors and how to fix it?

I don't know why. But imho, you're doing it for nothing, we don't plan to make PrestaShop compatible with PHP8.0 yet.
PHP8.0 is also only in beta, everything you're doing right know will maybe be removed in few days.

**Comment by mvorisek** [comment]
> But imho, you're doing it for nothing, we don't plan to make PrestaShop compatible with PHP8.0 yet.

in our system, we include some libs from PrestaShop in our internal system which we develop using the latest technologies

even if PHP 8 is not officially supported, there should nothing stop us to merge fixes sooner ;-) (of course, fixes that are clean, not hacked deps)

**Comment by PierreRambaud** [comment]
> > But imho, you're doing it for nothing, we don't plan to make PrestaShop compatible with PHP8.0 yet.
> 
> in our system, we include some libs from PrestaShop in our internal system which we develop using the latest technologies
> 
> even if PHP 8 is not officially supported, there should nothing stop us to merge fixes sooner ;-) (of course, fixes that are clean, not hacked deps)

Little fixes yes, but it's not planned yet to integrate PHP8.0 since it is still in beta. 
If you want to continue playing with the nightly Travis image, you should do it on your own repository to don't block Travis queue.
I'm closing this pull request since it will generate more noise for us (review, Travis queue) and dependencies are not compatible with PHP8.0 (we will not approve sed in travis.yml file :sweat_smile: ).
Feel free to create little pull requests when you think it's relevant.
Kind regards

**Comment by mvorisek** [comment]
what is wrong with sed in travis.yml for nightly build?

I belive we should have one nightly even without locked deps to detect issues early

**Comment by PierreRambaud** [comment]
> what is wrong with sed in travis.yml for nightly build?
> 
> I belive we should have one nightly even without locked deps to detect issues early

It's consuming useless travis jobs since we don't want to integrate a beta version of PHP8 and we are limited in concurrencies jobs :/

**Pull request closed without merging**
