### PR TITLE
Fix open new tab when target _blank exist for new product page link

### LINKED ISSUE #30200: BO - "Add new product" V2 with quick access is always opened in the same page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Reported here https://github.com/PrestaShop/PrestaShop/pull/30065#pullrequestreview-1160322870 previously
In the quick access management, we can open the page in a new window, "Add new product" V2 with quick access is always opened in the same page

image

PS: product page V1 => ok
### Expected behavior

It should be opened on another page

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Single store
2. Click on the "Quick access" > Manage your quick access
3. Enable "New window" for the "New product" 
image
4. Click on "Quick access" > Add a new product
5. Click on "Add new product" button => the add new product page is displayed in the same page

https://user-images.githubusercontent.com/16067358/198686293-9c9cacc5-cff7-4500-a754-303fc7453b4d.mp4

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix open new tab when target _blank exist for new product page link
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #30200 
| Fixed ticket?     | Fixes #30200 
| Sponsor company   | https://github.com/PrestaShopCorp

### CODE REVIEW

**Review by kpodemski — COMMENTED** [review]
If it's part of the new product page, I think it should be fixed on the 8.1.x branch.

**Comment by MatShir** [comment]
> If it's part of the new product page, I think it should be fixed on the 8.1.x branch.
Yes it would be perfect :)

**Review by kpodemski — CHANGES_REQUESTED** [review]
@mflasquin in that case, please rebase on 8.1.x :)

**Comment by mflasquin** [comment]
Hi @kpodemski done :smile:

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hi @mflasquin 

I have tested your PR and the bug is still here for product V2 enabled

**Comment by paulnoelcholot** [comment]
@mflasquin,

My apologies, forgot to clear the cache...

It's good for me now :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by mflasquin** [comment]
thanks @paulnoelcholot

**Pull request merged**
