### PR TITLE
Fixes the import configuration save on BO

### LINKED ISSUE #19746: Wrong payload sent when saving import configuration
#### Describe the bug

When saving the import configuration, everything seems to be fine but when you're back on this screen later, you will see an "undefined" choice in the select instead the name of your saved configuration.
And when you load it, each fields will be set to `undefined`.

If you look at the network tab and more precisely on the payload sent when you save the configuration, you will see this:

```
ajax	"1"
action	"saveImportMatchs"
tab	"AdminImport"
token	"ee20d0f98a45013400a34a36bd0e4ea6"
skip	"1"
newImportMatchs	"undefined"
type_value[0]	"undefined"
type_value[1]	"undefined"
type_value[2]	"undefined"
type_value[3]	"undefined"
type_value[4]	"undefined"
type_value[5]	"undefined"
type_value[6]	"undefined"
type_value[7]	"undefined"
type_value[8]	"undefined"
type_value[9]	"undefined"
type_value[10]	"undefined"
type_value[11]	"undefined"
type_value[12]	"undefined"
type_value[13]	"undefined"
type_value[14]	"undefined"
type_value[15]	"undefined"
type_value[16]	"undefined"
type_value[17]	"undefined"
type_value[18]	"undefined"
type_value[19]	"undefined"
type_value[20]	"undefined"
type_value[21]	"undefined"
type_value[22]	"undefined"
type_value[23]	"undefined"
type_value[24]	"undefined"
type_value[25]	"undefined"
type_value[26]	"undefined"
type_value[27]	"undefined"
type_value[28]	"undefined"
type_value[29]	"undefined"
type_value[30]	"undefined"
type_value[31]	"undefined"
type_value[32]	"undefined"
type_value[33]	"undefined"
type_value[34]	"undefined"
type_value[35]	"undefined"
type_value[36]	"undefined"
type_value[37]	"undefined"
type_value[38]	"undefined"
type_value[39]	"undefined"
type_value[40]	"undefined"
type_value[41]	"undefined"
type_value[42]	"undefined"
type_value[43]	"undefined"
type_value[44]	"undefined"
type_value[45]	"undefined"
type_value[46]	"undefined"
type_value[47]	"undefined"
type_value[48]	"undefined"
type_value[49]	"undefined"
type_value[50]	"undefined"
type_value[51]	"undefined"
type_value[52]	"undefined"
type_value[53]	"undefined"
type_value[54]	"undefined"
type_value[55]	"undefined"
type_value[56]	"undefined"
type_value[57]	"undefined"
type_value[58]	"undefined"
type_value[59]	"undefined"
type_value[60]	"undefined"
type_value[61]	"undefined"
type_value[62]	"undefined"
type_value[63]	"undefined"
type_value[64]	"undefined"
type_value[65]	"undefined"
```

#### Expected behavior

Once the import configuration is saved, I'd like to load it later :)

#### Steps to Reproduce

1. Go to 'Avanced Settings > Import > Fill the form and upload a file to import (Products in my case)'
2. Click on 'Next Step'
3. Give a name to the field : Save your data matching configuration
4. Once you're on the match fields table, Save the import configuration
5. Look at the payload sent or try to refresh an load your previous saved configuration

**Screenshots**

When you name it and save it:

image

And when you try to load it:
image

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: 7.2.30 (PrestaShop Docker default config)

### PR DESCRIPTION
**Pull request by joemugen**
`$(this).attr('value')` was returning `undefined`
Replacing it by `$(this).val()` is doing the job

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | I'm using PrestaShop 1.7.7 with Firefox 77 but the problem seems to exist on any 1.7.x version. See below for more details.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? |  Fixes #19746
| How to test?  | Please, have a look at "How to test?" below.

## Problem description
While using the "save import configuration" on Firefox 77, I couldn't load the configuration again.
Once the network tab inspected, I realized that values were undefined.
In the `js/admin/import.js` values were called with `.attr('value')` function. I'm not sure but I think it's more `.val()` function we need to use to get a value of an input with jQuery.
Once all `.attr('value')` replaced by `.val()` everything is working smoothly. 
Just a quick fix but we can now save our import configuration and use it again :)

## How to test?
Pretty simple to test, try to save a import configuration and check the payload sent, you should see something like this:

```
ajax	"1"
action	"saveImportMatchs"
tab	"AdminImport"
token	"ee20d0f98a45013400a34a36bd0e4ea6"
skip	"1"
newImportMatchs	"undefined"
type_value[0]	"undefined"
type_value[1]	"undefined"
type_value[2]	"undefined"
type_value[3]	"undefined"
// ...
```

Once you apply the fix it should become:
```
ajax	"1"
action	"saveImportMatchs"
tab	"AdminImport"
token	"ee20d0f98a45013400a34a36bd0e4ea6"
skip	"1"
newImportMatchs	"default-product-import-configuration"
type_value[0]	"id"
type_value[1]	"active"
type_value[2]	"name"
type_value[3]	"category"
// ...
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19738)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@joemugen  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

**Review by PierreRambaud — DISMISSED** [review]

**Comment by joemugen** [comment]
> @joemugen Thank you for your contribution. hugs
> 
> Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
> 
> Thanks +1

PR updated and issue #19746 has been created

**Comment by Progi1984** [comment]
@joemugen Thanks. We send your PR to QA Team ;)

**Comment by colinegin** [comment]
ping @Progi1984 the PR should be targetting 1.7.7.x branch right ?

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@colinegin After validation, we can cherry pick this commit to 177x.

**Comment by Robin-Fischer-PS** [comment]
Hi @joemugen ! With your PR, the payload is now OK.

pr19738 payload ok


Thanks for the fix !

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @joemugen

**Pull request merged**
