### PR TITLE
[-] PDF: Update invoice.addresses-tab.tpl

### PR DESCRIPTION
**Pull request by Nobodaddy**
Seriously, show me the merchant who needs the shop address in this place. This is the perfect place for the delivery address, followed  - if necessary  - by the invoice address.

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi @Nobodaddy ,

We could delete the shop address from the main address tab, you put it from left from right.
In the example below, I just deleted the shop address from invoice.addresses-tab.tpl and as it remains in the bottom of the shop, it must be enough. What do you think ?

[IN000001(1).pdf](https://github.com/PrestaShop/PrestaShop/files/167143/IN000001.1.pdf)

**Comment by Nobodaddy** [comment]
Hi @vincentbz 
looks much better.  :)

And as next step ... input fields for margin and page setting in the back office. :dancers: 
In 1.5 it was quite easy to change the default margins in *fpdf.php*. And different linear measurements were supported. But now ...
You need to change several *style-tab.tpl*, which is no real improvement.

**Comment by vincentbz** [comment]
Hi @Nobodaddy ,

Do you think you could update your PR with the removal of the address on the top of the invoice, so that we can merge it ?
Thanks ! :)

**Comment by aleeks** [comment]
Hello @vincentbz 
What do you expect from this PR ?

**Comment by aleeks** [comment]
Hello @Nobodaddy 
Your commit has been rebased here: https://github.com/PrestaShop/PrestaShop/pull/7462

Thank you.

**Pull request closed without merging**
