### PR TITLE
Fix store hours migration

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | hours are not properly migrated due to problem with " " 
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 
| Sponsor company  | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8556)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @kpodemski

**Comment by kpodemski** [comment]
Hey @Quetzacoalt91 why it is not a part of 1.7.3.1 or something? Why we need to wait to much time for a fix related to data migration?

**Comment by Quetzacoalt91** [comment]
At the moment we merged this PR, the `develop` branch was already for the version 1.7.4.x.

Making it available for 1.7.3.x requires to cherry-pick on the previous branch, as I just did on https://github.com/PrestaShop/PrestaShop/pull/8670

**Comment by kpodemski** [comment]
Great, thank you

**Comment by DaleyKD** [comment]
Is it just me, and I'm not a PHP developer by day (C#), but during my upgrade, the error [ERROR] PHP 1.7.0.0 /* PHP:ps1700_stores(); */ is shown.  Since I have ZERO items in the stores table, it's returning false.  Wouldn't that be the cause?  Shouldn't we want to return true by default?

**Comment by Quetzacoalt91** [comment]
You're right @DaleyKD. Another pull-request has been created for that point: #10218

**Pull request merged**
