### PR TITLE
[*] FO : fixed shipping cost not correctly updated on checkout

### PR DESCRIPTION
**Pull request by kelu95**
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/4437)

### CODE REVIEW

**Comment by xBorderie** [comment]
Rework of #3031. Thanks @kelu95 !

**Comment by vTerenti** [comment]
QA OK

**Comment by xBorderie** [comment]
:+1:

**Comment by kpodemski** [comment]
@mickaelandrieu just close it, it's too late for that, breaking change for themes and modules...

**Comment by mickaelandrieu** [comment]
@kpodemski duly noted :cry:

**Pull request closed without merging**
