### PR TITLE
Install `rector/rector` and apply basic rules

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below
| Type?             | refacto
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | No functional changes, only re-written code, CI and automated tests should be sufficient.

Rector is a tool that helps us modernize the code we are using, it can automatically use new functions (see the example in the PR) used with Symfony, it can help us refactoring many services in a few minutes.

https://getrector.com/documentation

You can run rector by run `php vendor/bin/rector` and its config file is at the root named `rector.php`

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
Seems like a good idea, could you please detail a bit more in the description how to run it it? (simple CLI example). Also maybe indicate one or to links related to interesting rules to add in the future?

And if this usage is accepted it's worth adding a CI in this PR from the starts, that only executes with a dry-run (blocking if failed) and an error message indicating the CLI command to execute to fix the code.

**Comment by mflasquin** [comment]
Nice idea ! I'm agree with @jolelievre about adding step in CI to run the tool, maybe not blocking if failed for the moment, what do you think @jolelievre ?

**Comment by jolelievre** [comment]
@mflasquin If we're not confident enough for starters, I guess yes we can leave it as not required and see how it goes
It's just about delaying the settings for branch protection to a bit later so no problem

**Comment by FabienPapet** [comment]
Putting rector into the CI requires some extra work as this tool is not built for this (there's no return code for the process other than 0 AFAIK), but only for code modernization. 

The only thing I could go is adding a comment with the diff, but not in the test suite. I'm not sure this is is a great idea, as our CI is already slow enough. 

I'd go to merge this, and  run this for time to time before release, or when someone wants to.

WDYT ?

**Comment by FabienPapet** [comment]
> Also maybe indicate one or to links related to interesting rules to add in the future?

@jolelievre There are already plenty of rules that are commented inside the rector file, all these rules are included in the set PHP8.1, which is the default one. I ignored them because it would make the PR way too big, maybe 40k deleted lines 😂 

Also, I would stay with the default rules included in the set list, they are basic, and make  the configuration simple.

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
@FabienPapet ok it makes sense, let's keep it as an occasional tool to run from time to time, although by doing this I'm afraid we'll quickly forget it but let's try it this way for now

**Review by mflasquin — APPROVED** [review]

**Comment by mflasquin** [comment]
After discussion with @FabienPapet It's a good idea maybe to add rector acting like a dependabot each week for example

**Comment by mflasquin** [comment]
Tests: https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5321746183

**Comment by jolelievre** [comment]
@mflasquin @FabienPapet yeah once a week seems like a good idea, but we should add an automatic workflow that creates a PR then right? Probably to be done in a second PR then

**Comment by mflasquin** [comment]
All tests are green, thanks @FabienPapet

**Comment by GeniJaho** [comment]
I don't use PrestaShop but it's great that it's including Rector ✌️. It can be cached in the pipelines, so it takes about 1 min per PR if cached https://getrector.com/documentation/cache-in-ci. Have a good day.

**Comment by matks** [comment]
Dont forget milestone ;) @mflasquin

**Pull request merged**
