### PR TITLE
Merge branch 1.7.8.x into develop [merge]

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge branch 1.7.8.x into develop
| Type?             | bug fix
| Category?         | ME 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | CI is green
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27992)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
Integration tests fail during webpack build on BO new-theme

> new-theme@1.0.0 build /home/runner/work/PrestaShop/PrestaShop/admin-dev/themes/new-theme
> webpack --progress --mode=production
```
1020 modules
1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

ERROR in js/app/pages/stock/components/overview/spinner.vue:86:11
TS2322: Type '""' is not assignable to type 'number | null'.
    84 |         if (!this.product.qty) {
    85 |           this.isEnabled = false;
  > 86 |           this.value = '';
       |           ^^^^^^^^^^
    87 |         }
    88 |         return Math.round(<number> this.value);
    89 |       },

ERROR in js/app/widgets/ps-number.vue:90:32
TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.
    88 |       },
    89 |       increment() {
  > 90 |         const value = parseInt(this.value === '' || isNaN(this.value) ? 0 : this.value, 10);
       |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    91 |         this.$emit('change', Number.isNaN(value) ? 0 : value + 1);
    92 |       },
    93 |       decrement(): void {
```

**Comment by matks** [comment]
In order to not have CI rejecting PR because of Block Merge Commits PR Validator
you might need to add `[merge]` to your PR title (example https://github.com/PrestaShop/PrestaShop/pull/27609)

**Comment by atomiix** [comment]
@PrestaShop/qa-functional maybe this one should checked to see if #27736 is still fixed

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by khouloudbelguith — DISMISSED** [review]
Hi @atomiix,

I checked the automatic tests => OK :heavy_check_mark: 
But I found those issues manually:
- https://github.com/PrestaShop/PrestaShop/pull/27814 => NOK, I still reproduce this issue: https://github.com/PrestaShop/PrestaShop/issues/27725 with this PR 
image
, I checked 1785 => ok 
image

- https://github.com/PrestaShop/PrestaShop/pull/27776, we have an exception only with this PR:
Go to BO > Catalog > Stocks page
Try to increase the quantity with the arrow => NOK
Stock • PrestaShop
I checked develop without PR, 1785, 178x => OK
Stock • PrestaShop (1)

https://github.com/PrestaShop/PrestaShop/pull/27763 => ok
https://github.com/PrestaShop/PrestaShop/pull/27843 => ok
https://github.com/PrestaShop/PrestaShop/pull/27874 => ok

Thanks!

**Comment by atomiix** [comment]
@khouloudbelguith for #27814, the fix is now on the https://github.com/PrestaShop/classic-theme repo so I think you need to update your package with `composer update prestashop/classic`.

for #27776, this should be fixed now.

**Review by matks — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hi @atomiix,

It is ok :heavy_check_mark: 
I checked all automatic tests => ok :heavy_check_mark: 
About the issue https://github.com/PrestaShop/PrestaShop/issues/27725 as discussed with @atomiix, I just re-opened a new issue: https://github.com/PrestaShop/PrestaShop/issues/28151

#27736 => ok
#27761 => ok
#27835 => ok
#27854 => ok
#27385 => ok
#27684 => ok
#27690 => ok
#27774 => ok

Thanks!

**Comment by matks** [comment]
Thank you @atomiix

**Pull request merged**
