### PR TITLE
Unlink cart products from current address.

### LINKED ISSUE #30350: No carriers proposed after deletion of address
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When products are added to a cart, the system sets ps_cart_product.id_address_delivery to current address of the cart. Later during the checkout process, function Carrier::getAvailableCarrierList uses this address to determine validity of carriers for this product (through function Address::isCountryActiveById). So if the address in question is deleted while the cart is still pending, then Carrier::getAvailableCarrierList returns empty list, therefore no carriers can be found for the cart, and the user has no other option than removing all his products from the cart and adding them again.

### Expected behavior

System should not fail to propose carriers when address is deleted while the cart is still pending.

### Steps to reproduce

1. Add a product to the cart from FO.
Note: the current default address of the cart should be not used in previous orders (so it can be deleted after)
2. Do not proceed to finish the order yet.
3. Check the id_address_delivery field of the newly created ps_cart_product record.
4. Delete this address from BO.
5. Go back to FO and try to finish the order.
6. At the step for choosing the carrier there will be an error that no carriers are available.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by stoycho**
Otherwise, if the address is deleted,
the system cannot find delivery options for the pending carts.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | PrestaShop v1.7.8.7. When products are added to a cart, the system sets ps_cart_product.id_address_delivery to current address of the cart. Later during the checkout process, function Carrier::getAvailableCarrierList uses this address to determine validity of carriers for this product (through function Address::isCountryActiveById). So if the address in question is deleted while the cart is still pending, then Carrier::getAvailableCarrierList returns empty list, therefore no carriers can be found for the cart, and the user has no other option than removing all his products from the cart and adding them again.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #30350.
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Reproduce the bug: Add a product to the cart from FO. Note: the current default address of the cart should be not used in previous orders (so it can be deleted after). Do not proceed to finish the order yet. Check the id_address_delivery field of the newly created ps_cart_product record. Delete this address from BO. Go back to FO and try to finish the order. At the step for choosing the carrier there will be an error that no carriers are available. When the fix in current pull request is applyed, there will be no such error and the system will correctly propose available carriers.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]
LGTM

**Comment by stoycho** [comment]
I made a mistake in the initial comment and did not specify an answer to "BC breaks" question. So now the PR has label "BC break", but the corrections do not introduce backwards incompatible changes. Is it possible to remove this label somehow?

**Comment by matks** [comment]
> I made a mistake in the initial comment and did not specify an answer to "BC breaks" question. So now the PR has label "BC break", but the corrections do not introduce backwards incompatible changes. Is it possible to remove this label somehow?

Yes, just ask 😄 I did it

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Good catch @stoycho!

I think we should also reset this value in `ps_customization` table, because `id_address_delivery` is also used there.

```sql
$sql = 'UPDATE ' . _DB_PREFIX_ . 'customization
SET id_address_delivery = 0 WHERE id_address_delivery = ' . $this->id;
Db::getInstance()->execute($sql);
```

**Comment by stoycho** [comment]
> > I made a mistake in the initial comment and did not specify an answer to "BC breaks" question. So now the PR has label "BC break", but the corrections do not introduce backwards incompatible changes. Is it possible to remove this label somehow?
> 
> Yes, just ask 😄 I did it

Thank you so much! :-)

**Comment by stoycho** [comment]
> Good catch @stoycho!
> 
> I think we should also reset this value in `ps_customization` table, because `id_address_delivery` is also used there.
> 
> ```sql
> $sql = 'UPDATE ' . _DB_PREFIX_ . 'customization
> SET id_address_delivery = 0 WHERE id_address_delivery = ' . $this->id;
> Db::getInstance()->execute($sql);
> ```

Thanks for the suggestion, I will look into it.

**Comment by stoycho** [comment]
@Hlavtox I added the suggested reset of `id_address_delivery` in `ps_customization`.

**Comment by abramofranchetti** [comment]
Please, notice the this simple solution, which I also thought about, is incorrect.
The code 
`$sql = 'UPDATE ' . _DB_PREFIX_ . 'customization
                    SET id_address_delivery = 0
                    WHERE id_address_delivery = ' . $this->id;`

does not consider that the field "**id_address_delivery" is part of the primary key of the table cart_product** and setting it to zero can cause a "**duplicate key**" if there are two or more rows with the other key fields with the same value (id_cart,id_product,id_product_attribute,id_customization). 

furthermore the f**ix does not work if the address is already used in an order**. In that case in fact the address is not really deleted from the table but only flagged as deleted, and the method "deleteCartAddress" (that @stoycho have fixed) is not called. In fact the function "deleteCartAddress" is only called when the address in "new" and never used in other orders.

The correct way to proceed to the solution is already been found by prestashop team (in particular developers of ps_checkout module) and it is calling the "s**etProductAddressDelivery**" function that take care of not generating potential "duplicate key" error and fixing also the customization table.

**Comment by stoycho** [comment]
@abramofranchetti 
You are right, it is good to take care about the unique index, I wll look into it.
About your second remark, I think in case when the address is not really phisically deleted but just archived, then this problem does not occur, because the system manages to reset addresses correctly afterwards.

**Comment by abramofranchetti** [comment]
> @abramofranchetti About your second remark, I think in case when the address is not really phisically deleted but just archived, then this problem does not occur, because the system manages to reset addresses correctly afterwards.

Nope, i've tried and also if the address is flagged as deleted the error occurs. Take a look at the "setProductAddressDelivery" function for a correct management.

**Comment by stoycho** [comment]
@abramofranchetti Ok, so seems there are more bugs to be fixed here. Seems the system resets correctly the address of the cart, but not the address of the cart_product.
The question is not only how to set the address, but at which point of the deletion of the old address to set it and to which new address to set it.

**Comment by abramofranchetti** [comment]
> @abramofranchetti Ok, so seems there are more bugs to be fixed here. Seems the system resets correctly the address of the cart, but not the address of the cart_product. The question is not only how to set the address, but at which point of the deletion of the old address to set it and to which new address to set it.

yes, i've had to fix this bug in production for a customer so i had to dig deep into the problem and i think i've found a way to fix. i've the code already written and tested' as soon as I have a moment I'll put it on github and tag you so we can talk about if you want.

**Comment by stoycho** [comment]
@abramofranchetti Yes, sure.

**Comment by stoycho** [comment]
@abramofranchetti , @Hlavtox 
Ok, seems the magic of resetting the cart address to 0 happens in Cart function `checkAndUpdateAddresses`.

So I think now the options are:

- a) To adapt `checkAndUpdateAddresses` of class `Cart` to take care about `id_address_delivery` also in `cart_product` and `customization` (using `setProductAddressDelivery`).
- b) To adapt `deleteCartAddress` of class `Address` to take care about `id_address_delivery` also in `cart_product` and `customization` (using `setProductAddressDelivery`), and to execute it in all the cases during `delete` of the address, not only for new addresses, like now.
- c) The both of a) and b)

What do you think?

**Comment by stoycho** [comment]
Just pushed changes which adapt `deleteCartAddress` of class `Address` to take care about `id_address_delivery` also in `cart_product` and `customization` (using idea of `setProductAddressDelivery` from class `Cart`), and executing it when deleting addresses regardless of their usage beforehand, not only for new addresses. (option `b)` from the list above)

**Comment by Hlavtox** [comment]
@stoycho Hi, I think the correct solution is to take care of this in both methods. :-)
- Reset it everywhere in `deleteCartAddress`.
- Validate and reset everything if needed in `checkAndUpdateAddresses`.

**Comment by stoycho** [comment]
@Hlavtox 
Pushed the changes in `checkAndUpdateAddresses`.
I am afraid it's going to need a little bit more of shotgun surgery. There are a few places where the system, after the `checkAndUpdateAddresses`, sets automatically the cart delivery address to a new appropriate one, but seems it do not set the addresses in cart_product and customization. I will look into it.

**Comment by Hlavtox** [comment]
Yeah it's a total mess dude. 😄 There should be ONE PLACE when initializing the cart, where every checks and adjustments are done...
- Cart rule validity and removal.
- Adress validity and reset to another adress or to zero.
- Customer and id_guest validity and reset.
- Carrier and delivery option validity and reset to default.
- ID lang check and reset to default.

**Comment by stoycho** [comment]
@Hlavtox , @abramofranchetti 
Should be ok now.
It now sets also the delivery address of cart products and customizations while setting delivery address of the cart in FrontController.

**Comment by stoycho** [comment]
I see that behaviour tests are failing, but I do not know where exactly is the problem and how to fix. Neither I know how to run those tests locally in my clone of the repo. Can somebody guide me through this endeavour?

**Comment by stoycho** [comment]
Found the problem for behaviour tests and fixed it.

**Comment by stoycho** [comment]
The integration-behaviour-test passes Ok now.

**Comment by stoycho** [comment]
@Hlavtox This is my first PR, so I am not sure, do I have to do something more at this point, or it is all in the hands of maintainers/reviewers from now on?

**Comment by kpodemski** [comment]
Reopening to trigger the tests again.

**Comment by Hlavtox** [comment]
@stoycho @kpodemski We will need to properly analyze the PR again, I find the new functions like `setProductAnyAddressDelivery` very confusing for just a simple address reset. 🤷‍♂️ 

We should really now think of having one place to validate and do everything, instead of introducing more and more spaghetti code that nobody understands.

**Comment by stoycho** [comment]
@Hlavtox 

`setProductAnyAddressDelivery` is not really a new function, it is a piece extracted out of `setProductAddressDelivery`. As @abramofranchetti mentioned, the `setProductAddressDelivery` seems to be the correct way to do the address setting. In this way the main functionality of setting the address can be used from different places, with or without validating the link between the adress and the customer. `setProductAnyAddressDelivery` is a private function, and in fact it exists exactly for that - to have same functionality accessible from many different places.

**Comment by abramofranchetti** [comment]
> @Hlavtox @stoycho yes the question is very tricky. The solution proposed by @stoycho is correct. In fact is mandatory to keep coherent the link in between address and ps_cart_product.id_address_delivery because , if there is some rows in ps_cart_product that have some id_address_delivery that does not exist anymore, there will be problems during the checkout.

**Comment by Hlavtox** [comment]
A lot of things won't be needed after https://github.com/PrestaShop/PrestaShop/pull/33264 is merged, it will be much simplier. Let's push this PR to finish afterwards if there are some things buggy remaining. :-)

**Comment by Hlavtox** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/35017

**Pull request closed without merging**
