### PR TITLE
[*] Core : Use more modern hashing methods (PSCFV-11357)

### PR DESCRIPTION
**Pull request by tiennou**
[PSCFV-11357](http://forge.prestashop.com/browse/PSCFV-11357)

This is my take on #3183 (kudos to @sfroment42 for the initial implementation). This changes the authentication methods to PHP's `password_hash` group of functions to bring Prestashop's security to 2015.

Added but not "discussed" on Forge is the ability to register compatibility hashing algorithms (the old md5 method being one of those, but I need phpass support as well for an upcoming migration). So, I've build this [hashingtest](https://gist.github.com/tiennou/bde3e16d260507b491c2) module to check that it can be done.

### CODE REVIEW

**Comment by tiennou** [comment]
@julienbourdeau Some comments would be really welcome ;-).

From the top of my head, I'll recap the points I've made on the forge ticket that this PR tries to fix :
- I don't find the current API easy-to-use/well-named but that's a minor point (e.g. hardcodes a parameter for `COOKIE_KEY`, `isFirstHash` check).
- It doesn't handle transparent password upgrades.
- It doesn't take care of employee passwords, which are more critical.

If you have concerns about the extendability of it (which is admittedly the only part I'm concerned with), I can split this one in 2 parts : the changes that improve on PSCFV-11357 and the extendability part.

**Comment by sfroment42** [comment]
Hello,

Nice PR :+1: . Would be nice to get it reviewed by the PS team =).
I'm sorry to have forgotten the employee password.

b58

**Comment by tiennou** [comment]
Freshly rebased against develop.

**Comment by tiennou** [comment]
Re-rebased against `develop`.

**Comment by tiennou** [comment]
Just noticed that the installer still generates old-style employee passwords, but they get upgraded on first login.

I'd really appreciate some comments on this, as it's been open since 2 months now...

**Comment by aleeks** [comment]
Hello,
So @Quetzacoalt91 we have to close it isn't ?

**Comment by aleeks** [comment]
As @Quetzacoalt91 said, an other has been done related to hashing method.
I'm closing this PR, If it has to be reopened, it will be.

Regards

**Pull request closed without merging**
