### PR TITLE
Register translation wordings for Feature Flag

### LINKED ISSUE #24000: [Add support for experimental features] Make sure Handle Product Page V2 flag is translatable
This issue is an item in the [Add support for experimental features](https://github.com/PrestaShop/PrestaShop/issues/23235) project

You can read about the project [here](https://github.com/PrestaShop/PrestaShop/issues/23235).

The Product Page flag will be loaded after https://github.com/PrestaShop/PrestaShop/issues/23999 is implemented.

**We need to make sure we can translate this flag name (a.k.a wording) and help text** so that, when a user opens the Experimental Features BO page in English, Spanish, Greek or Turkish he sees the name in a correct language.

## TODO

1. We need to make sure the wording and help text **translation messages** are correctly acknowledged by the Translation Tools of PrestaShop. This means that _when we expect Translation Catalog for 1.7.8_ the wording and help text messages will be exported. This will allow translators on https://crowdin.com/project/prestashop-official to translate it.

2. Merchants / shop administrators be able to translate these wording and help text in the Back Office interface

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Register the wordings for Feature Flag.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24000
| How to test?      | See below
| Possible impacts? | ~

## How to test

1. Install PS using this branch with FRENCH language
2. Run the following SQL script to load the feature flag data
```
INSERT INTO `ps_feature_flag` (`name`, `state`, `label_wording`, `label_domain`, `description_wording`, `description_domain`)
VALUES
   ('product_page_v2', 0, 'Experimental product page', 'Admin.Advparameters.Feature', 'This page is a work in progress. It includes new combination management features and other features under development (virtual products, packs, etc.)', 'Admin.Advparameters.Help');
```
3. Open the Back Office using FRENCH language
4. Open Configure > Adv Parameters > Experimental Feature: wordings are not translated

Capture d’écran 2021-04-14 à 15 40 21

5. Open International > Translations Page and follow "Translate Back Office wordings" menu
6. You can find the 2 wordings for Feature flag in
- Admin > AdvParameter > Feature for the flag name `Experimental product page`
- Admin > AdvParameter > Help for the help message `This page is a work in progress. It includes new combination management features and other features under development (virtual products, packs, etc.)`
7. Using the translation interface you can translate the 2 wordings

Capture d’écran 2021-04-14 à 15 46 31

8. Save your translations, go back to Configure > Adv Parameters > Experimental Feature and see translated wordings

Capture d’écran 2021-04-14 à 15 45 09

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24045)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
IMO this doesn't require QA because there is no functional change

**Comment by Progi1984** [comment]
Ping @PrestaShop/qa-functional for validation.

**Comment by sarahdib** [comment]
@Progi1984 this can be tested by a QA functional :) @Robin-Fischer-PS is already on it

**Comment by Robin-Fischer-PS** [comment]
Hi @matks 

Translation is OK on the new page : 

pr 24045 - translation OK


Thanks !

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
