### PR TITLE
CACHEDIR.TAG - saving resources and disk space

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Creating empty file "CACHEDIR.TAG" will tell to a lot of  backup software (or webhosting companies as well) not to backup this folder content (not necessary), waste of time and resources. Our hosting don't backup this folders X years, because they are useless to have them in backups everyday...  Some customers have big folder /var/cache/ (X GB). Helping saving resources and space. And there is other benefit, if a customer has a problem and restores a backup (from webhosting), he immediately has it clean without a cache that will be created again, and it is another benefit that there could be a defect even at a moment it could be with the cache. No negative impact, because folders will be recreated again.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       |
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Review by Hlavtox — COMMENTED** [review]
Googled it, legit, approving :-)

**Review by Hlavtox — APPROVED** [review]

**Review by LouisAUTHIE — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by jf-viguier** [comment]
Please add signature !
cf https://bford.info/cachedir/

> This file must be an ordinary file, not for example a symbolic link. Additionally, the first 43 octets of this file must consist of the following ASCII header string:
> 
> Signature: 8a477f597d28d172789f06886806bc55

It's required for gnu tar by example.

**Comment by Hlavtox** [comment]
@ShaiMagal Bro, please open another PR adding the signature, it's good point. :-)

**Comment by ShaiMagal** [comment]
@jf-viguier @Hlavtox OK, will make another PR :)
Our software don't care about signature, detecting only file name, but if any software handling signature as well, it's good point of course.

**Comment by paulc010** [comment]
After upgrade (clean) 8.1.4 to 8.1.5 var/cache/CACHEDIR.TAG is listed under missing files....

**Comment by SharakPL** [comment]
It's the same after each cache clean because this file gets deleted right away. Isn't there a better way to use it?

**Comment by paulc010** [comment]
It's not really a core function in my humble opinion and errors or warnings in the back office just cause alarm. It seems to me it's a deployment thing. Its creation could be triggered by an environment setting that's picked up by the installer.

**Pull request merged**
