### PR TITLE
Improve SEO - Hn tags in Classic Theme

### PR DESCRIPTION
**Pull request by sLorenzini**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve SEO Hn tags on Classic Theme (template files + override module files)
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/FF-158
| How to test?  | The changes are on Hn tags. Can see changes on .tpl files or source code on browser

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8741)

### CODE REVIEW

**Comment by alegout** [comment]
Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8741)*

**Review by alegout — APPROVED** [review]
Thank you!

**Comment by eternoendless** [comment]
Thank you @sLorenzini

**Comment by dbucci24** [comment]
@eternoendless 
I would like to contribute to the translation into Spanish, does this project need?

**Comment by marionf** [comment]
@sLorenzini & @eternoendless 
I just find a regression on develop, I think it's following this PR
The search no longer displays the products
pr8741

**Pull request merged**
