### PR TITLE
[WIP] Available carriers in product page - differenciate between enabled and disabled carriers and add ability to enable/disable

### LINKED ISSUE #24497: List of available carriers in product edit page contain disabled carriers - product v1 and v2
#### Describe the bug
Disabled carriers appear in list of available carriers in product edit page v1 and v2.

#### Expected behavior
Disabled carriers shouldn't appear in list, or should appear as "greyed".

#### Steps to Reproduce the behavior:

0. Have a fresh install on develop
1. Go to Shipping > Carriers, see 2 active carriers and 2 disabled carriers
2. Go to Catalog> Products> Choose a product and go to product Edit page (non virtual product)> Shipping
3. See the 4 carriers in available carriers, all of them ready to receive check/uncheck actions.

#### Additional information

* PrestaShop version: 1.7.6.7 & 1.7.7.4 & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by arouiadib**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See paragraph below.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24497
| How to test?      | See paragraph below.
| Possible impacts? | I don't see any

**Description:**

In product page, v1 and v2, all available carriers are shown to the merchant, even disabled ones. This will allow him to check a disabled carrier (by mistake), and thus add an unnecessary record in join table in database. Such a record can lead to data inconsistency on retrieval.

A good solution is to show disabled carriers but disable checking them with a grey checkbox. However this need some advanced knowledge in Symfony form types and/or need extra logic.

For the moment, I create this PR to fix the issue by not showing disabled carriers at all.

**How to test:**
Have a fresh install on develop
Go to Shipping > Carriers, see 2 active carriers and 2 disabled carriers
Go to Catalog> Products> Choose a product and go to product Edit page (non virtual product)> Shipping
See the 2 active carriers in available carriers, not the 4 available carriers.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25161)

### CODE REVIEW

**Comment by Hlavtox** [comment]
@arouiadib I think it's good to enable checking the disabled carrier. 😉 Imagine these situations:
- You create a new carrier, keep it disabled, you want to assign it to products before you activate it.
- You disable carrier for a week for some reason (problem with a carrier or whatever), you go working on some products and it will remove this carrier from your products, because it won't be checked when saving the products.

**Comment by arouiadib** [comment]
Great points here @Hlavtox , thanks a lot

Finally I think we should show all carriers, enabled ones and disabled ones, but with some indication on the difference.
And to improve it more, add the ability to disable/enable a carrier on product page, without going to shipping page.

It would be nice if I have more info product-wise [in ticket page.](https://github.com/PrestaShop/PrestaShop/issues/24497)
I mark this as [WIP] in hope I do better in the future.

**Comment by PierreRambaud** [comment]
Hey @arouiadib 
Is it still in WIP? Is there something we can do to help you?

**Comment by PierreRambaud** [comment]
Hi @arouiadib ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
