### PR TITLE
Display fixed index in profiling for easier navigation

### LINKED ISSUE #26896: Profiling navigation can be made easier with a fixed index
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Navigating the profiling results can be difficult, because you have to scroll up to the index each time you want to navigate to a different section.
2021-12-06 at 5 17 PM

### Describe the solution you'd like

Make the index fixed on top of the page (i'll submit a PR for this)

2021-12-06 at 5 18 PM

### Alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Display the profiling sections in a fixed container for easier navigation
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26896 
| How to test?      | Enable profiling then check the index in the top right corner of the page
| Possible impacts? | NA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26898)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
that looks like a nice improvement 👍 

lgtm codewise, I'm not sure if PMs are supposed to validate this since it is mostly for developers ? @PrestaShop/product-team wdyt ?

**Review by PierreRambaud — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
Can we agree that things related to the developer tools are going to the developer Validation and QA? :-)

**Comment by PierreRambaud** [comment]
> Can we agree that things related to the developer tools are going to the developer Validation and QA? :-)

Yep

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
Hi @unlocomqx it's a really cool feature but when I try it I can see some issues. On FO we have headers at the top that hide the index, now:

### When it's not hidden it looks good

Capture d’écran 2021-12-20 à 15 36 27

### But if you go at the top, it's hidden behind top navbar

Capture d’écran 2021-12-20 à 15 36 34

### On BO it's worse because top navbar is sticky

Capture d’écran 2021-12-20 à 15 37 11

**Comment by unlocomqx** [comment]
I improved it a bit using some css. It's probably simpler to just move it to the bottom though.
If so, tell me and I will simplify it.

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by kpodemski** [comment]
Hello @unlocomqx 

I've tested your PR, it's a very nice improvement, but I had a hard time finding this new element with the links. Maybe we could improve it, make it bigger + with a more visible color? Another option would be to stick it to the bottom of the page and make it full width, similar to Symfony's toolbar, but... this might not be good for BO. What do you think?

image

Edit: nevermind :D we can improve it some other time :D

**Comment by matks** [comment]
@unlocomqx I LOVE it ❤️ 
Capture d’écran 2021-12-22 à 22 27 49

Capture d’écran 2021-12-22 à 22 27 53

I think it's a very good improvement. Maybe some people will have some issues in some usecases, but then we can improve the code until 8.0.0 release. So for me this is a good improvement and it can be merged.

**Comment by matks** [comment]
Hoho @kpodemski we answered almost at the very same time 😅

**Comment by unlocomqx** [comment]
Thank you for merging. 

If people complain about visibility, i'll give it a border, it will make it stand out more

Cheers 🎉

**Pull request merged**
