### PR TITLE
Bug in upgrade queries: adjust column size and index name.

### LINKED ISSUE #24943: Error in upgrade queries PS 1.7.8.0 beta.1
#### Describe the bug

The table definition of `PREFIX_feature_flag` does not fit the data inserted.

#### Expected behavior

I expect the queries to run without error.

#### Steps to Reproduce

1. Following `https://devdocs.prestashop.com/1.7/basics/keeping-up-to-date/upgrade/`run `http://<shop_domain>/install/upgrade/upgrade.php`. Run the script `install-dev/upgrade/sql/1.7.8.0.sql` manually (because of #24886 `/install-dev/upgrade/upgrade.php` won't run)
2. Run the second last query.
3. run the last query
You get error 
> Error 1406 - Data too long for column 'description_wording' at row 1

#### Additional information

```
CREATE TABLE IF NOT EXISTS `PREFIX_feature_flag` (
  `id_feature_flag` INT(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL,
  `state` TINYINT(1) NOT NULL DEFAULT '0',
  `label_wording` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `label_domain` VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `description_wording` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  `description_domain` VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id_feature_flag`),
  UNIQUE KEY `UNIQ_91700F175E237E06` (`name`)
) ENGINE=ENGINE_TYPE DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `PREFIX_feature_flag` (`name`, `state`, `label_wording`, `label_domain`, `description_wording`, `description_domain`)
VALUES
	('product_page_v2', 0, 'Experimental product page', 'Admin.Advparameters.Feature', 'This page benefits from increased performance and includes new features such as a new combination management system. Please note this is a work in progress and some features are not available yet.', 'Admin.Advparameters.Help');
```
`label_wording` and `description_wording` are `varchar(191)`, while the inserted text has 196 chars. The size of the columns should probably be 255.
Additionally, the unique key should not have an automatic name 

      UNIQUE KEY `name` (`name`)

would probably be a better choice.

* PrestaShop version: 1.7.8.0 beta.1
* PHP version: N/A

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixes an issue in the sql upgrade script for 1.7.8.0 beta.1. Adjust column size and index name of the new table `PREFIX_feature_flag`.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24943.
| How to test?      | Run the two last sql queries in the script
| Possible impacts? | A step closer to a working upgrade.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24949)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
The value can't be 255 when using utf8mb4 and index. It will result on an error an old MySQL configuration

**Comment by lmeyer1** [comment]
@PierreRambaud 
> The value can't be 255 when using utf8mb4 and index. It will result on an error an old MySQL configuration

I'm using Mysql server 5.7.34, and I don't have this limit.

**Comment by PierreRambaud** [comment]
> @PierreRambaud
> 
> > The value can't be 255 when using utf8mb4 and index. It will result on an error an old MySQL configuration
> 
> I'm using Mysql server 5.7.34, and I don't have this limit.


The problem is on MySQL 5.6 :sweat_smile:

**Comment by lmeyer1** [comment]
I'm closing this, because this solution is going in the wrong direction. The issue #24943 remains open, because the text in `install-dev/upgrade/sql/1.7.8.0.sql` in branch `1.7.8.x` still has a text that is too long. Thus the upgrade script still fails.

**Pull request closed without merging**
