### PR TITLE
Allow to print order messages

### LINKED ISSUE #26376: Allow to print order messages
## Is your feature request related to a problem?

Add order message in print.

## Describe the solution you'd like

Allow print order messages

## Additional context

- Go to order page in BO
- Add order message
- click on **print order**
- See is missing the message block

image

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allow print order messages
| Type?             | improvement 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26376
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/26376
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26377)

### CODE REVIEW

**Comment by Progi1984** [comment]
@PrestaShop/product-team Check question on issue #26376#issuecomment-949664055

**Review by matthieu-rolland — COMMENTED** [review]
thanx @PululuK 

lgtm code wise but I wait for PM's feedback before approving 👍

**Comment by MatShir** [comment]
@PululuK Maybe you could share the output so the @PrestaShop/ux-team can have a look :)

**Comment by MatShir** [comment]
@PululuK could you provide a screenshot so the @PrestaShop/ux-team can have a look ;)
It will help a lot on the process review 🤗 
Thanks in advance! :)

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
Hi @PululuK ,

Since we had no news from you for almost 2 months, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Naturally if you want to continue this PR, you can reopen 😉  .

Thanks!

**Comment by PululuK** [comment]
Hi @MatShir  See [Order #5 KHWLILZLL.pdf](https://github.com/PrestaShop/PrestaShop/files/8373495/Order.5.KHWLILZLL.pdf)

**Review by atomiix — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by Progi1984** [comment]
I remove the "Waiting for UX" label because the issue has been "UX :heavy_check_mark:".

**Review by AureRita — COMMENTED** [review]
Hi @PululuK ,

Thank you for your PR, I tested it and it works as we can see here :

Summary of messages
image

We can maybe Ping @Julievrz 
For the message, the expeditor should be "Me" or the name of the shop where the order is passed ?

**Comment by PululuK** [comment]
> We can maybe Ping @Julievrz For the message, the expeditor should be "Me" or the name of the shop where the order is passed ?

Hi @AureRita 

About wording, is not related to this PR, so you can open an issue.

**Review by AureRita — APPROVED** [review]

**Comment by MatShir** [comment]
It is using the wording of the order message system, all good @AureRita !

**Comment by Progi1984** [comment]
Thanks @PululuK & @AureRita & @MatShir

**Comment by matks** [comment]
An old PR finally becoming live 😄 congratulations @PululuK

**Pull request merged**
