### PR TITLE
[-] FO : small layout fixes

### PR DESCRIPTION
**Pull request by martinfojtik**

### CODE REVIEW

**Comment by prestarocket** [comment]
For product page, you should add button type submit with bs classes (btn btn primary) instead input type submit

**Comment by prestarocket** [comment]
In header-nav, i m not sur that row before container is correct

**Comment by xBorderie** [comment]
The default theme is a fast-moving project at the moment, which makes that your PR already cannot be merged because of conflicts. Sorry! :/ You'll have to rebase/upgrade your code in order for the PR to be mergable again.
It might be best for you to join [the Gitter channel](https://gitter.im/PrestaShop/StarterTheme), and talk with @nihco2 and the rest of the team about this :)

**Comment by nihco2** [comment]
I currently work on product page, I will include these improvements  in my next PR.

**Comment by maximebiloe** [comment]
@nihco2 Could you close this PR when you'll commit the changes, please ?

Thanks again @fojtCz

**Comment by nihco2** [comment]
@maximebiloe yep

**Comment by fojtCz** [comment]
Thanks  #4980

**Pull request closed without merging**
