### PR TITLE
Add class on light display layout and remove padding top

### LINKED ISSUE #27266: BO - Bad display In some modals
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO, we have a bad display of some modals
image
**1782** => ok
image

I found this issue in different pages
1. Go to BO > Orders > Add new Order 
2. Click Add new customer
3. See error

----------------------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Details for Carts & Orders
image

---------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Add new customer

-------------------------
1. Go to BO > Orders > View an old order
2. EDit the shipping address & the invoice address
3. See error
 

### Expected behavior

_No response_

### Steps to reproduce

I found this issue in different pages
1. Go to BO > Orders > Add new Order 
2. Click Add new customer
3. See error

----------------------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Details for Carts & Orders
image

---------------------------
1. Go to BO > Orders > Add new order
2. choose a customer
3. Click on Add new customer

-------------------------
1. Go to BO > Orders > View an old order
2. EDit the shipping address & the invoice address
3. See error
 

### PrestaShop version(s) where the bug happened

1.7.8.3build1

### PHP version(s) where the bug happened
7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Due to the remove of the header calculation, there is a padding top inside modales
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27266
| How to test?      | See issue
| Possible impacts? | Light layout

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27296)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by hibatallahAouadni — CHANGES_REQUESTED** [review]
Hello @NeOMakinG 

I think it will be better to change the `padding-top` from `0` to `10px` or at least `5px` (as you & @prestascott like) :sweat_smile: 
Cause with `padding-top:0;` it's a bit ugly:

image

---
image

If you check right in the end of modal, there's `margin-bottom=10px` :+1: (pretty :wink: )

image

Well, I attached below a screenshot of the modal if we add `padding-top:10px;`

image

Please check and feedback.
Thanks!

**Comment by NeOMakinG** [comment]
@hibatallahAouadni did it

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @NeOMakinG 

LGTM, QA :heavy_check_mark: 

image

Thanks!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
WAIT FOR 1783 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @hibatallahAouadni

**Comment by prestascott** [comment]
Hello everyone,

Thanks for your request @NeOMakinG!

I agree with @hibatallahAouadni, `padding-top:0;` looks awful. I suggest going for a `padding-top:8;`. 

Now that I see, can't we add a `padding: 8;` to make it consistent because the containers on the left touch the edges.

Wdyt?

**Comment by hibatallahAouadni** [comment]
@NeOMakinG wdyt? should I reopen the issue or create new feature to change the `padding-top` from `10px` to `8px`? :sweat_smile:

**Pull request merged**
