### PR TITLE
Add itemprop properties from schema.org

### LINKED ISSUE #15554: Errors with latest changes on itemList for products listing
Hi
I report here some infos to help to find a better solution to this pull request
https://github.com/PrestaShop/PrestaShop/pull/14558

I think some data is missing from those fixes:
look here
https://developers.google.com/search/docs/data-types/carousel

I think for the "item" attribute should be necessary to add more infos like: name, url, image, aggregateRating ...

bye

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0

### PR DESCRIPTION
**Pull request by Peter-Liska**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  Fixing some of the Google Search Console warnings for products listing pages.
| Type?         |  Bug
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #15554 and some of the #15764
| How to test?  | Go to product warnings in Google Search Console. Then push button VALIDATE FIX for corresponding warning (in product listing look for missing field image and in offers look for missing url or availability). After Google crawl your pages, these warnings will disappear.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21786)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
Looks fine to me @Peter-Liska , thanks for this contribution.

Could you create an issue in order to list this in next changelog ?

**Comment by Peter-Liska** [comment]
It looks like, that this fix issue
https://github.com/PrestaShop/PrestaShop/issues/15554
and some of these
https://github.com/PrestaShop/PrestaShop/issues/15764

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
Hi @Peter-Liska 
I still have the "warnings" with your PR and the suggested tools in #15764 seems to be deprecated
**With the deprecated tool**
image
 **With the new tool**
image

Can you check this please ?

**Comment by Peter-Liska** [comment]
> Hi @Peter-Liska
> I still have the "warnings" with your PR and the suggested tools in #15764 seems to be deprecated
> Can you check this please ?

This fix only some issues from #15764 ... as I have written  before.

**Comment by SD1982** [comment]
Hi @Peter-Liska  with your PR i still have **"all"** the warning described in #15764

**In #15764**
image

**With your PR applied**
image

**Comment by Peter-Liska** [comment]
I can take a closer look at this when I have free time again.

**Comment by alfonsolr09** [comment]
"Indicates Nested Offer or AggregateOffer values to sell the product. Add the required and recommended properties of Offer or AggregateOffer, depending on what corresponds to your content. ****In order to take advantage of the appearance of price drops, add Offer, not AggregateOffer.**** "


Is there a way to use both depending on whether the product is on sale or not?

**Comment by sarahdib** [comment]
Hello

Since we had no news from you for more than 30 days, I'll close this PR. Feel free to ask us to re-open  if you can fix the issue.

Thank you!

**Pull request closed without merging**
