### PR TITLE
Remove Activity Shop from Installer & Config

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove Activity Shop from Installer & Config (Only used by Addons)
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A
| Possible impacts? | N/A

**:notebook: BC Breaks :**
* Removed configuration `PS_SHOP_ACTIVITY`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26850)

### CODE REVIEW

**Review by sowbiba — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Code looks OK but I think we need to provide a way for ps_mbo to reintroduce this, if needed.

@PierreRambaud introduced some overridable templates to make sure ps_mbo can reinject the views removed from the Core. How can ps_mbo reinject this behavior ?

**Comment by Progi1984** [comment]
@matks It is not the scope of the PR.If @intraordinaire has some needs, we will help us to add its needs to Core.

**Review by PierreRambaud — DISMISSED** [review]
The code is maybe used by addons but maybe not only. This part is maybe useful for something or someone, no need to remove it as there is nothing here related to addons :thinking:

**Review by kpodemski — APPROVED** [review]
1. If needed, `ps_mbo` can use hooks to add this option to the configuration form, and they can provide their version of the installer (from what I know)
2. I've never seen anything that would use this field.

**Comment by PierreRambaud** [comment]
> 1. If needed, `ps_mbo` can use hooks to add this option to the configuration form, and they can provide their version of the installer (from what I know)
> 2. I've never seen anything that would use this field.

Hooks are not usable in the installer :eyes: 

Also, it's not because you saw something that it's not needed :sweat_smile:

**Comment by kpodemski** [comment]
@PierreRambaud 

> Also, it's not because you saw something that it's not needed 😅

This information might only be needed by third parties that have to map the store owner to some group of merchants. Nothing else is coming to my mind.

> Hooks are not usable in the installer 👀

You can add **additional fields to the configuration of the store** using hooks, and the team can implement `select` via a modified installer.

Everything that @Progi1984 just removed is possible to recreate using a combination of hooks and a custom installer.

**Comment by PierreRambaud** [comment]
> This information might only be needed by third parties that have to map the store owner to some group of merchants. Nothing else is coming to my mind.

You can provide different fixtures depending on the activity you choose (also work with images).

**Comment by Progi1984** [comment]
@PierreRambaud In this case, it's on the side of the module that the developer allow the merchant to define its activity.

**Comment by Progi1984** [comment]
@PierreRambaud Is modok be able to return modules with use of a configuration key ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud Is modok be able to return modules with use of a configuration key ?

Nope, it's only related to module.

**Comment by PierreRambaud** [comment]
@PrestaShop/product-team I let you decide

**Review by matthieu-rolland — COMMENTED** [review]
LGTM codewise, waiting for PM

**Review by matthieu-rolland — APPROVED** [review]

**Comment by MatShir** [comment]
I agree with @PierreRambaud, here the field is used by Addons but can be used by any third party. It shares an information of the shop. 
The work of separation between the project and PrestaShop SA is to remove all dependencies and make the solution neutral. Here, I see no link with Addons but just a data used by Addons. 
If they are no real reason to remove it (feature/improvement, bug, dependency issue, refacto...), I don't see why we should remove it.

**Comment by MatShir** [comment]
Feel free to reopen/comment it if you think there is missing information on the decision of the closure of the PR, thank you for your understanding

**Pull request closed without merging**
