### PR TITLE
Add missing MPN column into products CSV example

### LINKED ISSUE #29254: MPN field is missing in sample product CSV
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

MPN field is missing in sample product CSV
[screencast-nimbus-capture-2022.08.04-19_51_20.webm](https://user-images.githubusercontent.com/42021740/182871289-3433223a-8674-4760-aa76-9378409d4947.webm)

### Expected behavior

_No response_

### Steps to reproduce

1. Go to the Advanced parameter->import section
2. Download sample product CSV file
3. Upload it as an import file
4.  Due to missing column MPN all fields orders displaying wrong 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #32413: The MPN column is missing in products' import file
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The MPN column is missing, so the file could not be used as wanted without changing the fields related to each column.

### Expected behavior

_No response_

### Steps to reproduce

1. Go to Import page
2. Download the example about products
3. Use it inside the import
4. See that after EAN/UPC, there is a no match.

### PrestaShop version(s) where the bug happened

8.0.4

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@Wepika

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing MPN field into example.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/32413
| Fixed ticket?      | Fixes #32413, Fixes #29254
| Related PRs       | Use this newer file on the products import and see that every fields match the needed column.

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Review by 0x346e3730 — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Comment by AchrafKchaou1991** [comment]
Hello @PrestaEdit  ,
I have checked your PR , the MPN column is well added but  the dropdown menu is incoherent with the title of the colomun as you can see below:

WITHOUT PR :

[without PR 32411.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/049ab717-f95e-4038-abc4-6ae9feb80384)



WITH PR :

[with PR 32411.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/0a742fb4-2d5e-49bf-9300-9cd992fc7823)



Can you check it  please ?
 
Thank you

**Comment by PrestaEdit** [comment]
I'm not able to see how you make your import, the fact that you have a lot of 'Ignored this column' is not something attending there and seems not related to the PR itself.

**Comment by kpodemski** [comment]
Hello @AchrafKchaou1991 

You have to choose which column is what. This is manual mapping.

**Comment by AureRita** [comment]
Hi @PrestaEdit 

Thank you for your PR, I tested it and it works ! as you can see here : 

[Untitled_ May 17, 2023 12_38 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/d381a0d2-61b0-444c-8075-31788954528f)

Thank you

**Review by AureRita — DISMISSED** [review]

**Comment by AureRita** [comment]
After the validation I see that the auto test failed, 
@nesrineabdmouleh 'll validate it

**Comment by nesrineabdmouleh** [comment]
Thank you @AureRita,
I fixed UI tests, please restart the failed job :)

**Review by AureRita — APPROVED** [review]
Auto-test are :green_circle: 
So it's a QA Approved :heavy_check_mark:

**Review by boubkerbribri — APPROVED** [review]
LGTM for `tests/UI`

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @PrestaEdit !

**Pull request merged**
