### PR TITLE
Remove Tools::array_replace(), deprecated since 1.7.4.0

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Remove an old version, listed as deprecated since 1.7.4.0, 3 years ago
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | The function was already no longer used in the core
| Possible impacts? | Possibly old modules can call it

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24275)

### CODE REVIEW

**Comment by kpodemski** [comment]
There is a lot of methods like this but I'm afraid that we don't know if we can remove it on `develop` just yet.

**Comment by Sinepel** [comment]
> There is a lot of methods like this but I'm afraid that we don't know if we can remove it on `develop` just yet.

Yes, I understand. Even for the 1.7.9.0?

**Review by Progi1984 — CHANGES_REQUESTED** [review]
We only can merge it, if `develop` was a major version. But `develop` is in 1.7.9.0 so we can't remove it for avoiding BC Breaks.

**Comment by Sinepel** [comment]
> We only can merge it, if `develop` was a major version. But `develop` is in 1.7.9.0 so we can't remove it for avoiding BC Breaks.

Hi @Progi1984, how can we do this? 
Should I put it on another branch or close it and see later?

**Comment by PierreRambaud** [comment]
> > We only can merge it, if `develop` was a major version. But `develop` is in 1.7.9.0 so we can't remove it for avoiding BC Breaks.
> 
> Hi @Progi1984, how can we do this?
> Should I put it on another branch or close it and see later?

I recommend you to close it, and we will remove all deprecated elements in the next major version :)

**Pull request closed without merging**
