### PR TITLE
Raise minimal PHP version to PHP 7.2.5

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Raise minimal PHP version to PHP 7.2.5 for the upcoming 1.7.9 release. Needed for https://github.com/PrestaShop/PrestaShop/pull/23896
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | CI must pass
| Possible impacts? | PHP 7.1 support is dropped

Regex used to find places to replace minimal version:
```
(php.*(7\.0?1(?!\w)|(?<!\d)701))|((7\.0?1(?!\w)|(?<!\d)701).*php)
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24476)

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I see no reason to merge it right now as we don't update our dependencies yet in order to be compatible with PHP8 or Symfony 4.4

**Comment by mvorisek** [comment]
@PierreRambaud see https://github.com/PrestaShop/PrestaShop/issues/20739#issuecomment-822462017 , we can merge right now :)

**Comment by PierreRambaud** [comment]
> @PierreRambaud see [#20739 (comment)](https://github.com/PrestaShop/PrestaShop/issues/20739#issuecomment-822462017) , we can merge right now :)

This is just a state comment, maybe not the final situation

**Comment by matks** [comment]
Hello @mvorisek although it is expected that we will need to indeed drop php7.1 (as written in https://github.com/PrestaShop/PrestaShop/issues/20739#issuecomment-822462017) it's not 100% sure.

The compatibility with php8 raises very complex questions 😞 and we are not sure yet how to handle it. Multiple options are being discussed, nothing decided totally.

So indeed we cannot approve this pull request yet.

**Comment by PierreRambaud** [comment]
Closed in favor of #24609

**Comment by mvorisek** [comment]
@PierreRambaud @matks why very clean isolated PR is rejecter in favor of another PR, that does not even contain all changes from this PR?

**Pull request closed without merging**
