### PR TITLE
[-] BO: Fix bug wrong Context mode name

### PR DESCRIPTION
**Pull request by kpodemski**
Critical bug, fatal error after sign in to addons account to back-office.
Fatal error: Undefined class constant 'MODE_CONTRIB' in classes\controller\AdminController.php on line 405

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by DogSports** [comment]
Delete Cookies, and connect back to your BO.

**Comment by kpodemski** [comment]
It's not the point, there is no static MODE_CONTRIB...

image

**Comment by julienbourdeau** [comment]
Hi kpodemski,

Thanks for your contribution to PrestaShop. It should only appear when you are a contributor on Addons, I hope they will be able to fix it until the next release.

Thanks again,

Julien

**Comment by SirDev** [comment]
I just ran into this same issue. White admin page after logging in (yes I have a contributor account).

**Comment by julienbourdeau** [comment]
Hi,

This is fixed on the development version and we will release a new version soon. We usually dont edit the zip after releasing it.

Best regards,

**Comment by SirDev** [comment]
All right. It might be a good reason to exempt from that rule as people are expecting to receive a stable build from the stable channel :)

Verzonden met mijn Windows Phone

-----Original Message-----

**Pull request merged**
