### PR TITLE
Fix edit price modal showed when adding same product in multi-invoices

### LINKED ISSUE #24691: [Multi-invoices] BO - Orders - A modal should'nt be displayed when we add the same product to a specific invoice with updating price
#### Describe the bug

Reported [here](https://github.com/PrestaShop/PrestaShop/pull/24253#issuecomment-849614195)
This issue occurs when we have multi-invoice (more than 2 invoices created).
When we try to add the same product to a specific invoice, a modal is displayed.
It shouldn't, we need to have only alert `Error! This product is already in the invoice #IN00000x, please edit the quantity instead.`

#### Steps to Reproduce

1. Create an order
2. Go to BO > Orders > View last order created with `Product1`
3. Generate an invoice
4. Add the same product `Product1` with creating a new invoice
5. Add the same product to any invoice with changing the product price 
6. See error: a modal `Edit the price` is displayed => it shouldn't, we should have `Error! This product is already in the invoice #IN00000x, please edit the quantity instead.`

**Another case**

1. Create an order
2. Go to BO > Orders > View last order created with `Product1`
3. Generate an invoice
4. Add the same product `Product1` with creating a new invoice
5. Edit the product price and confirm the update
5. Add the same product to any invoice without changing the product price 
6. See error: a modal `Edit the price` is displayed => it shouldn't, we should have `Error! This product is already in the invoice #IN00000x, please edit the quantity instead.`

image

With PS176 => we can add the same product without any alert

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Because of a bad condition, under certain circumstances, the "edit price" modal was showed when it shouldn't. This PR fixes it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24691
| How to test?      | Please see #24691
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24765)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@atomiix Could you rebase your PR ?

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @atomiix !

**Review by Progi1984 — CHANGES_REQUESTED** [review]
## WAIT FOR 1775 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @atomiix & @florine2623

**Pull request merged**
