### PR TITLE
Add font awesome in new theme & upgrade in default

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add font awesome in new theme & upgrade in default
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1805
| How to test?  | check icon

See: https://github.com/PrestaShop/PrestaShop/pull/7072

### CODE REVIEW

**Comment by kpodemski** [comment]
Nice!

**Comment by aleeks** [comment]
I would have preferred to include original font-awesome .. but we included it in the theme with the prefix 'icon' so it's not very good .. So we have to include file manualy :/

**Comment by kpodemski** [comment]
@aleeks hmm, am i missing something? i don't see anything added to `classic` theme, only to admin

**Comment by maximebiloe** [comment]
@kpodemski We don't want to add font awesome on the front office, we want to use Material instead. This is a graphical choice.
Any theme developer is free to implement its own icon pack.

**Comment by kpodemski** [comment]
@maximebiloe so you can close this forge ticket as "not resolved" because i wasn't writing about back-office

the point of this ticket was to prevent loading of dozen of Font Awesome instances by separated modules

**Comment by maximebiloe** [comment]
@kpodemski even if we include Font Awesome in Classic, what will guarantee you that all theme developers will do the same? Anyway, you should embed what you want to use, there is no miracle solution here.

**Comment by aleeks** [comment]
:(

**Comment by kpodemski** [comment]
@maximebiloe because it's most popular font icon library in the world, used by many very popular PrestaShop modules where you can choose an icon displayed within a menu item etc. it was normal to have font-awesome available in 1.6 so most modules used FA, now in 1.7 they need to load FontAwesome by themselves which will cause having few instances of FontAwesome in store.

**Comment by kpodemski** [comment]
Yet another pointless discussion when you guys think that you're right, but you have no idea how PrestaShop modules/themes market works.

What a shame.

**Comment by firstred** [comment]
What is this strange decision, to just close the PR?

PrestaShop is an eCommerce framework and should do its frameworky thing, such as providing modules with the right tools. You guys should be grateful that projects such as FontAwesome exist!

With every new version more and more features are removed, making it harder to create quality modules. The fact that many modules need to use overrides and almost always have to include their own framework says enough about how bad PrestaShop's module API actually is. You should be focusing on introducing standards (FontAwesome could have helped here!), more powerful hooks and global events to which modules can listen.

**Comment by Simonchik** [comment]
Totally agree with @kpodemski. Classic theme should have Font-Awesome by default.
@maximebiloe just imagine that I have 20 modules where I will load the same library.

**Comment by aleeks** [comment]
Hello @firstred 
I just close this PR because i didn't add FA in classic theme :/ it was in BO.
If we take the decision to include FA, it will be in another PR.
PR was closed but discussion is open

**Comment by firstred** [comment]
@aleeks Makes sense. I was actually more referring to the strange decision not to include FA.

**Comment by aleeks** [comment]
I have an idea. wait 20 minutes.

**Comment by xBorderie** [comment]
10 minutes left!

**Comment by aleeks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/7076 :whale:

**Comment by xBorderie** [comment]
Right on time! 👏

**Pull request closed without merging**
