### PR TITLE
[-] CORE : Fixed bug while updating ObjectModel::update() for all shops context

### PR DESCRIPTION
**Pull request by ghost**
When saving changes in all shops context, and have no checkbox checked, it replaces all values in all shops.
This fix this bug.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/5044)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commit's name to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog?
To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this must be done via the command line: just changing the title of the pull-request from the GitHub interface is not the same!_ :)

Thank you!

**Comment by Planetediscount** [comment]
Hello,

I had on my Prestashop 1.6.1.4 when update in context all shop the field "activated" then the price was changing on all shop, that was really poor. It's look your code is working for that also. (as for me not all field was changed, just price)

**Comment by xBorderie** [comment]
@Planetediscount Have you applied the changes from this PR? Does it solve your issue? Let us know!

@creaweb06 Thank you for your updates!
Sadly, you now have malformed commits instead of just one commit:
* the initial commit, which does not follow the [PS naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message),
* one commit which does follow the naming convention,
* one merge commit -- which if merged can break the repository's history!

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by Shudrum** [comment]
Are you sure that on some forms, if the field is not sent, then it was not simply removed?

**Comment by Planetediscount** [comment]
Hello @xBorderie yes i have done this PR also with ( https://github.com/PrestaShop/PrestaShop/pull/4601/files). for price it is ok but now on all shop context we can't change the reference of product, we are oblige to select one shop to change it.

**Comment by xBorderie** [comment]
@Planetediscount Thank you for your feedback, but I'm not sure I understand.
As far as I can tell, what you did is:

* apply the changes from the #4601 PR by @mickaelandrieu, but it did not solve all issues -- or rather, it created another problem.
* apply the changes from this PR (#5044), and this one solved your issues.

Am I correct?

**Comment by Planetediscount** [comment]
@xBorderie what i did is apply the two PR in same time, so now when activate a product in context all shop price don't change anymore on all shop. this OK
But we find that now we can't change on context all shop the reference of product, when we save, it keep old reference.
So what we have to do is select one shop and change reference in this shop.

For #4601 i find that there is a comment with a nother change, maybe this can solve, as i don't know if the new issues is because of this PR #5044 or from #4601

**Comment by xBorderie** [comment]
Thank you @Planetediscount.
Please note that #5044 was written with PS 1.7 in mind, while #4601 was written for PS 1.6. The two might therefore not be compatible with each other.

**Comment by Planetediscount** [comment]
Ok so i must take of this PR #5044

Also i note that all field where there is no case to check on context all shop (like EAN, reference..) then it won't take change on save, same we are oblige to go in one shop for change those fields.

**Comment by Planetediscount** [comment]
I have reverse PR #5044 to keep only change from PR #4601, the problem is still here, impossible to change any field that don't have an checkbox in context all shop.

**Comment by Planetediscount** [comment]
Hello, Why on a commit like #4601 where i say that apply this commit make price to don't change OK but make impossible to change other field where there is no case to check (multistore). We don't have any answer ? Does it is better to make an commit that put an other bug without trying to resolve it ?

I feel when i see every version of Prestashop coming out with full bug that for you it is normal ?

**Comment by xBorderie** [comment]
#4601 has been closed, as its developer, @mickaelandrieu , felt it was too risky.

**Comment by mickaelandrieu** [comment]
Hello,

the situation didn't changed, I don't think we can make any change without adding a lot of tests **first**.

So it won't be fixed in `1.6.1.x` as we are now focused on PrestaShop 1.7.

Thanks for your understanding.

**Pull request closed without merging**
