### PR TITLE
[-] BO: Export to SQL Manager should only be enabled in dev_mode

### PR DESCRIPTION
**Pull request by guestisp**
Show SQL Query is enabled only in dev mode.
In the same way, export to SQL manager should be enabled only in dev mode for security reasons.

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, 

Thank you for your PR, in your opinion merchant may no export listing to sql manager ?
I understand you may not show irrelevant data into BO if you are not in dev mode, but the export...

Best regards.

**Comment by guestisp** [comment]
As you are showing SQL query only in dev mode, why export to sql manager (that also show the query) should be always available? 

Actually is impossible to hide some parts of PS from being displayed, if you like, I can change this PR to disable "export to sql manager" and "show sql" only if `_PS_ENABLE_SQL_` is enabled (or something similiar)

This because we would like to hide some parts of PS for security reasons and, actually, is impossible.

Keep in mind that I'm disabling just the *SQL export*, not the *data export* to CSV

**Comment by jeromenadaud** [comment]
Hi, 

If you want to hide it for security reason, it will be better to hide/show it with ACL restrictions.
But at this moment it's not our priority. We will keep it in mind.

Best regards.

**Comment by guestisp** [comment]
Ok, but why sql query is only shown in dev mode and export to sql (that also does the same like show sql query) is always available. It's nonsense.

You are hiding sql query but still show it with the button on the right.

**Comment by jeromenadaud** [comment]
Hi, because SQL query are always shown in SQL manager. If you want to hide for security reason we must make it better with ACL restrictions.
We keep it in mind.

Best regards.

**Pull request closed without merging**
