### PR TITLE
New post code standard for Argentina LNNNNLLL

### PR DESCRIPTION
**Pull request by therampagerado**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | There's a "new" Postal Code standard in Argentina from few years (LNNNNLLL). The customers from there willing to use it can't. The shop owner should edit сш manually. To be picked in develop. https://en.wikipedia.org/wiki/Postal_codes_in_Argentina |
| Type? | improvement |
| Category? | IN |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

My First PR so be nice! :D

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi,

Thanks for your PR :)
Is this new standard the only one used or are the new and old used in the same time ?

**Comment by therampagerado** [comment]
The wiki says the new one is in force for all of Argentina but the old should be delivered as well with no problems. As far as I see it we need to use the latest standard regarding post codes.

**Comment by vincentbz** [comment]
OK thank you :)
We'll put it in the next version

**Comment by xBorderie** [comment]
Thank you for your contribution!

Sadly, you now have malformed commits instead of just one commit, and all your commit do not follow the [PS naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message).

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by therampagerado** [comment]
@xBorderie , I don't know what you're talking about but I'll try to delve into git tomorrow, is that OK? Hopefully I'll be able to fix my PR. ;)

**Comment by xBorderie** [comment]
Thank you for your willingness to try!
Just a note: don't change the title of the PR, change the name of the final commit :)
Good luck!

**Comment by therampagerado** [comment]
@xBorderie  - hope it's ok now! :)

**Comment by xBorderie** [comment]
Seems good to me, thank you!

**Pull request merged**
