### PR TITLE
Add WebP and Avif to mod_expires

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | We forgot to add WebP and Avif to .htaccess. I had to force .webp to be recognized thus AddType.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | You can use Page Speed Insights/Lighthouse or even devtools. It should be tested by a developer.
| Fixed ticket?     | n/a
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company | impSolutions

### CODE REVIEW

**Review by matks — APPROVED** [review]
Makes sense

I think that webp and avif might work even without these directives for some browsers / configurations 👍 but this PR will expand the usage to more users

**Review by matthieu-rolland — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by Hlavtox** [comment]
@matks It will work fine, but browser caching would be a freestyle.

**Comment by Hlavtox** [comment]
Nothing to test here, MIME types are valid - https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types.

**Review by LouisAUTHIE — APPROVED** [review]

**Review by matks — APPROVED** [review]
These changes are valid from a developer POV 👍

**Pull request merged**
