### PR TITLE
Building all assets goes 🏎️

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Paralellizes building assets to make it faster to build all assets
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | `make` =>  🏎️
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop SA

Before 🐌
image

After 🏎️
image

NB: The screenshots are results from Docker on Mac, so the performance improvement may vary based on the developers' setup

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
I made a little test:

43 seconds on develop
28 seconds with your branch

Not bad: :+1:

**Review by jolelievre — APPROVED** [review]
Thanks @0x346e3730

**Review by AureRita — APPROVED** [review]
Hi @0x346e3730 

Thank you for your PR ! I tested your PR and without your PR : 

WIth your PR, I've only 47'30 seconds 
Without your PR , I've 59'88 seconds 

Thank you !

**Comment by nicosomb** [comment]
Thank you @0x346e3730 !

**Pull request merged**
