### PR TITLE
Fix download product mail template

### LINKED ISSUE #10915: Display issue in virtual product email
**Describe the bug**
Some html tags are displayed in email when you order virutal product

**To Reproduce**
1. Go to advanced parameters > Email and choose Send email in text format
2. Make sure you receive email (test it)
3. Go to Catalog > Product
4. Create a new virual product with a file
4. Order this product
5. Put the order in "payment accepted" status
6. See the txt email sent 

**Screenshots**

46542475-cb99dd00-c8be-11e8-932e-13fb208dacc0

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by dennybiasiolli**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixing download product mail template
| Type?         | bug fix
| Category?     | LO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10915 
| How to test?  | Check html and txt mail after buying one or more virtual products

@marionf  I'm not very familiar with this templating system, but I suppose it will work. Can you give it a try? Now it should send a mail displaying a list of virtualProducts both in html and in txt mode

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10897)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by marionf** [comment]
Hello @dennybiasiolli 

Without your PR I have this: 
capture d ecran_749

With yout PR I have this:
capture d ecran_750

**Comment by PierreRambaud** [comment]
@dennybiasiolli Any news?

**Comment by dennybiasiolli** [comment]
Hi @PierreRambaud , no news for now, sorry but I'm working on other things right now 😥

**Comment by marionf** [comment]
@dennybiasiolli 

Thank you for your PR, the issue has been fixed by #16014
So, I close your PR

**Pull request closed without merging**
