### PR TITLE
Fixed redirect after canceling the edition of an address from the customer detail page

### LINKED ISSUE #27898: BO - Customers / Wrong redirection after canceling the edition of an address from the customer detail page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After canceling the edition of a new address from the customer detail page we are redirected to the addresses list instead of the customer detail page.

### Expected behavior

We should be redirected to the customer detail page.

### Steps to reproduce

1. Go to Customers => Customers
2. Select any customer and go to the customer detail page
3. Scroll down to the bottom of the page and in the address block click on the "edit" icon to edit an existing address (if your customer doesn't have any address, you'll need to create one first)
4. Click on Cancel button
5. See Error => redirected to the addresses list page instead of the customer detail page

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4.28

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed redirect after canceling the edition of an address from the customer detail page
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27898
| How to test?      | Cf.  #27898

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Seems legit

**Review by matthieu-rolland — APPROVED** [review]
legit it seems

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Tested multiples cases :
- Cancel from Customers > Customers > Customer details page
- After creating an address from Customer Details page
- After deleting the address, the right error message is displayed : The object cannot be loaded (or found)
- Cancel from Customers > Addresses > Add new address form

It is QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
