### PR TITLE
Update colombian tax rate

### PR DESCRIPTION
**Pull request by jorgevrgs**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update standard tax rate for Colombia
| Type?         | improvement
| Category?     | LO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Install Colombia localization pack

#### Important guidelines

* Colombia iso code for language package is CO but PrestaShop uses cb, that is wrong, some day it's neccessary to fix that.

### CODE REVIEW

**Comment by aleeks** [comment]
Thank you @jorgevrgs !
ping @AlexEven

**Comment by AlexEven** [comment]
Hello @jorgevrgs 
Thanks for this PR!
Yes we have an odd code language but unfortunately we can't change it like this, it will get too messy.
I tried your file and the Spanish, Colombian didn't installed. Did you try it? Was it all ok?
Thanks!

**Comment by AlexEven** [comment]
To be cherry-picked in 1.6

**Comment by jorgevrgs** [comment]
Use same as:

https://github.com/jorgevrgs/PrestaShop/blob/cbb8597009ef2144a07a434134dd1606dced761f/localization/ar.xml

But for tax id I see only works for first installation in all localization files.

**Comment by aleeks** [comment]
Thank you @jorgevrgs & @AlexEven

**Pull request merged**
