### PR TITLE
Fix scrollbar on order page when adding product

### LINKED ISSUE #19488: The list of products researched is hidden when adding a product
#### Describe the bug

In the tablet view, the list of products researched is hidden when adding a product by the order totals.
image

#### Expected behavior

To be displayed on the top of the order totals.
image

#### Steps to Reproduce

1. Reduce the window size on the order view
2. Add a new product

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

### PR DESCRIPTION
**Pull request by antoinedamiron**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In the tablet view, the list of products researched is hidden when adding a product by the order totals.
| Type?         | bug fix
| Category?     | BO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19488.
| How to test?  | go to order page, click on add product , type product title and verify that the dropdown doesn't make append scrollbar on the table on deskop and tablet view.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19546)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@antoinedamiron Before sending your PR to QA, could you build assets and commit them ? Thanks

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
I restarted the failing test, just in case

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @antoinedamiron !

With your PR, I still have the scrollbar in tablet view : 
pr19546 still ko

Could you fix that ? Thanks ;)

**Comment by antoinedamiron** [comment]
Hello @Robin-Fischer-PS 

I just try again the tablet view on Chrome and firefox and can't notice the scrollbar on products list.
The dropdown menu also look like to be well displayed on top of order totals.

Please find bellow the render i got.

test-scrollbar

**Comment by Robin-Fischer-PS** [comment]
Hi @antoinedamiron ! My mistake, my setup was probably to blame, @sarahdib  and I retested this morning, it's fine!

https://drive.google.com/file/d/19w3kdc5e4oSQ5f8m2z-WSGSPpxLKNNlY/view

Thanks for your contribution :)

**Comment by Progi1984** [comment]
Thanks @antoinedamiron

**Pull request merged**
