### PR TITLE
[*] CORE : Update SwiftMailer

### PR DESCRIPTION
**Pull request by firstred**
## Description

Same as #5214, but for PrestaShop 1.7
### What has changed?
- Update `SwiftMailerBundle` to `2.3.11`
- Add `swiftmailer/swiftmailer` to `composer.json`, version is `5.4.1`
- Removed `swift` folder from `/tools`
- Update `Mail.php` to work with the newer `SwiftMailer`

I haven't found an isolated mailer for the installer, like `1.6` has. Has that been removed with `1.7`?
## Steps to Test this Fix
- Send test emails
- Order something in the store.
- Try with sendmail and with a direct SMTP connection.
- Gmail, Outlook, etc. (STARTTLS) are supported with this update. It should be possible to relay emails to these email providers.

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi again @firstred !

Thanks for this PR ! I will review it ASAP.

To answer your question, yes, isolated mailer for installer has been removed in the 1.7. So don't worry about it.

Best regards,

**Comment by xBorderie** [comment]
giphy

**Comment by mickaelandrieu** [comment]
:+1:  sounds good to me, time to QA :cat:

**Comment by vincentbz** [comment]
Tested and OK, thanks !

**Comment by tchauviere** [comment]
Hi @firstred,

Again, thanks a lot for this huge contribution. Your PR is now merged and we are up to date with SwiftMailer thanks to you !

So Much Win

**Comment by firstred** [comment]
Nice! We've finally addressed a rather big issue, haven't we? :)

**Comment by xBorderie** [comment]
I'd say! Cup of tea, everyone!

giphy

**Comment by vincentbz** [comment]
gif minions

**Pull request merged**
