### PR TITLE
Fix the lowest composer dependencies

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Make sure the lowest allowed deps are fully compatible when deps are installed with `--prefer-lowest` composer option.
| Type?             | improvement 
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | GH tests must pass
| Possible impacts? | no, `composer.lock` versions are already the same or higher

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23981)

### CODE REVIEW

**Comment by mvorisek** [comment]
This is for you PS guys, @PierreRambaud, @Progi1984, @eternoendless, please fix the deps as required.

**Comment by mvorisek** [comment]
@PierreRambaud please review

**Comment by eternoendless** [comment]
Why would you install using `--prefer-lowest` when the project is distributed with composer.lock?

**Comment by mvorisek** [comment]
For development purposes to catch bugs early :)

**Comment by eternoendless** [comment]
I still don't understand why would you ignore composer.lock

**Comment by mvorisek** [comment]
> 
> 
> I still don't understand why would you ignore composer.lock

It is honored. But for CI/testing purposes, we test extra if deps defined in `composer.json` are fully compatible, if not, something should be sooner or later fixed. And this detect the issues early so `composer update` can be run safely any time :)

**Comment by eternoendless** [comment]
If I understood that right, that would happen only when updating a library A makes composer downgrade the version of library B that is currently used in composer.lock, AND that library falls below the actual minimum requirement. What are the chances of that happening?

**Comment by mvorisek** [comment]
> 
> 
> If I understood that right, that would happen only when updating a library A makes composer downgrade the version of library B that is currently used in composer.lock, AND that library falls below the actual minimum requirement. What are the chances of that happening?

Not only. Also, if some new/updated code depends on a newer locked version, that is however not required (=prohibited) by the deps.

As you can see, I also added a testing for "latest", which detect new incompatibilities early.

**Comment by mvorisek** [comment]
@eternoendless ok with to test this in CI? If not, I will adjust and we can merge the fixed deps at least.

Another way will be to run these extra checks on daily basis in cron which looks like a good compromise to me as it will not slow the regular testing.

**Review by matks — COMMENTED** [review]
Hi,

I understand this GH can be useful for a library that aims to provide a compatibility range with other dependencies and is expected to be used in different Composer usecases.

But PrestaShop is an application, it is not intended to work with a large compatibility range of libraries. It is expected to work with an accurate set of dependencies, defined in `composer.lock`.

I dont think the information provided by this GitHub Actions is useful and I dont think we should block some PRs because of these. The composer.lock is the only configuration we should test?

**Comment by mvorisek** [comment]
@matks I have reverted the CI testing, but let's merge the discovered dependency fixes. Title/desc adjusted.

**Comment by mvorisek** [comment]
PR rebased onto the latest composer.json, can you guys get onto it?

**Comment by matks** [comment]
Hi everyone

Like I just wrote in PR https://github.com/PrestaShop/PrestaShop/pull/22823#issuecomment-870394578, I'm afraid here we are in a situation where we don't want to merge this PR. It has not been moved since May and I think if nobody from maintainer team joins in the discussion it means nobody from maintainer team is willing to join.

There is a lot of things to do for the PrestaShop project and our time is limited. Maintainers have to pick carefully what topics they allow to go forward by reviewing and approving Pull Requests, so they choose what PRs and/or topics they invest their time in. If this PR has not moved for a long time I think it's because maintainers do not see a very valid reason to continue.

@eternoendless mentioned that we think this is not needed as we have the composer.lock . We see no huge reason to change how we use composer.json and composer.lock .

Thank you for your contribution, I close this Pull Request because I don't think it will be merged.

If 2 other maintainers of the project disagree with me they are free to re-open the Pull Request and continue this journey. For me, it's better to halt it here.

**Comment by mvorisek** [comment]
@matks seriously? The minimal deps are wrong, this is definitely wrong decision!

**Comment by mvorisek** [comment]
> @eternoendless mentioned that we think this is not needed as we have the composer.lock . We see no huge reason to change how we use composer.json and composer.lock .

@eternoendless I belive you need to speak with @matks, fixing deps to make sure lock file is newer wrong is definitely legit

**Pull request closed without merging**
