### PR TITLE
Fix get attributes in order presenter

### PR DESCRIPTION
**Pull request by manfield**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | it's an issue in the OrderPresenter core class. Product attributes stored in the products array are always the same. This is caused by a comparison on a wrong variable value (id_product, instead of id_product_attribute)
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | I noticed it developing a theme that use more informations on the order history page. You may add a {debug} in customer/history.tpl and see that product attributes are the same for each product in the order.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, @manfield ! A Core dev will soon have a look at it.

**Comment by manfield** [comment]
Just to speed up the merging.
This is what happens without modification:
02-wrong

This is the right behavior:
01-right

**Comment by maximebiloe** [comment]
Hello @manfield,

Thanks for your contribution.
As you had merge commits, we couldn't merge your PR, so I cherry picked your commit and open a new one here #8103 

In the future, don't merge, just rebase your branch 😉 

Regards

**Comment by manfield** [comment]
Yep! you're right. Probably if it is even better if I do my contribution (fix or dev) in a different branch.

**Comment by xBorderie** [comment]
Thanks @maximebiloe !

**Pull request closed without merging**
