### PR TITLE
Migrate customer view cart and order tables to grid

### LINKED ISSUE #15444: Reduce client view in Customer Page 1/2
**Is your feature request related to a problem? Please describe.**
Yes, it is. When I look a customer profile, which is a very old and very good customer, my page is really high !!
If we have this important list + some modules, this page become very very slow.
=> I have many customers in this case

**Describe the solution you'd like**
If it's possible to reduce all these informations such as see only 20 last carts, 20 last orders. Same for Products bought by the customer : Top 20 products more bought by the customer.
Every time we want to have more than 20, you have "See more" to display 20 others carts, orders or products.

**Describe alternatives you've considered**
None actually

**Additional context**
Screenshots about only one page/customer : [https://drive.google.com/drive/folders/13TPktWYVdz1Va985wvQH0g0qBHJngt_Z?usp=sharing](https://drive.google.com/drive/folders/13TPktWYVdz1Va985wvQH0g0qBHJngt_Z?usp=sharing)

### LINKED ISSUE #25683: Customers Query slow with many orders
#### Describe the bug

Hello there,

When trying to view or edit the password of a customer with many orders, this generates slowness in seeing customer as edit (Change Password).

You should not delay in the edit client option (Change Password) since in this option there is only basic information, there is no detailed information about the client.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to 'Clients'
2. Click on 'Clients'
3. Find a customer who has thousands of orders

**Screenshots**

image

https://drive.google.com/file/d/1-yz5mDkFm9_yc-In4JJaxuVBc9qUsXOV/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | see below
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Check the page and see that it works the same, but limits the amount of shown orders and carts to 10. The main difference will be visible when viewing a customer with many orders and carts (50+).
| Fixed ticket?     | Fixes #25683, Fixes #15444
| Related PRs       | 
| Sponsor company   | [AGRO-LA]( https://eshop.agrola.cz/)

### Details
- Right now, the cart and order listing on customer detail is a simple manually rendered table. When customer has more oders, let's say more than 20, it's incredibly slow because of all the carts loading and computing their data.
- You can see how it looks with 70 orders - https://user-images.githubusercontent.com/6097524/219952122-995c4f22-26dd-4e5b-acd0-de4124d8e59f.png, and I cropped about a kilometer of bought products. 😄
 - So, I changed the implementation of these two tables to grids. 
 - This fixes the insanely slow page load time, makes the page readable and allows the use of standard hooks. I followed address grid as an example.
 - For orders, there were originally two grids for valid and invalid orders. I unified orders to a single grid and marked the valid/invalid thing with a green/red badge. I think it simplifies things and looks quite good. PM validated.
 - When this is approved, I can continue with the list of bought products, which can be also pretty long.

### Screenshot
localhost_dev_admin-dev_index php_sell_customers_2_view__token=Kzw8BCzesvbRA4l1fN_MoC74wv0Dq5WUYVCa433F5FA customer_order%5BorderBy%5D=id_order customer_order%5BsortOrder%5D=asc

### CODE REVIEW

**Comment by MatShir** [comment]
LGTM 👍

**Review by zuk3975 — APPROVED** [review]
cool

**Review by matks — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by Hlavtox** [comment]
AAAAAAYY Thank you @MhiriFaten!

**Comment by ChineseNorris** [comment]
Hi,

I've checked the PR and improves a little bit the performance but not quite enough, it still loads very slow compared to PS 1.6

What is really the cause of this?

**Pull request merged**
