### PR TITLE
Added $result (from facet) in hook filterProductSearch

### PR DESCRIPTION
**Pull request by Tanguy-SALMON**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | $result from facet has some interesting informations and this commit allows to use it in modules via a hook. Now for me, it's useful to display current Manufacturer present on the category page. And it's possible to display on the category page, present features or attributes and adding a nice presentation with icons, etc...
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Just use the hook `filterProductSearch` or `actionProductSearchAfter` and use the variable available.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9079)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Thanks @Lathanao :)

Do you think you can provide a minimal module sample? You can drop it in a comment.

Our QA team are not developers so they can't create modules.

For instance, a simple module called toto with a `print_r($searchVariables);die;` for hook "filterProductSearch" is totally fine.

So the test for them could be: "Before: no "results" in "searchVariables" and after a new "results" entry in "searchVariables".

Again, thanks for your time !

**Review by mickaelandrieu — APPROVED** [review]

**Comment by Tanguy-SALMON** [comment]
[ao_commit_hook.zip](https://github.com/PrestaShop/PrestaShop/files/2009056/ao_commit_hook.zip)

Hi,

Here is the module.
Works on basic template, with basic products.

I put 2 print_r():
The first display $searchVariables. But there is to much code, including HTML code!
The second display only Manufacturer Id.

Regards.

**Comment by mickaelandrieu** [comment]
@Lathanao with @marionf we have reviewed the module and the contribution you did works but... there is one error that could be annoying for your need: the function `getFilters` may be unavailable.

This is probably a minor issue from your module, but can you confirm it before we merge?

**Comment by Tanguy-SALMON** [comment]
@mickaelandrieu 

I didn't get any issue for now cause all products get brand.

I test some cases. And you're right, method could be missing if:
- Facet module isn't right configured (category is not selected in Facet config).
- there is no active brand in the category displayed.

I get it.
That could be a way to change the behavior in case of no brand detected.

Thx for having report me that.

Regards,

**Comment by mickaelandrieu** [comment]
@Lathanao but we agree that the bug we meet have nothing to do with the change you have introduced so we can merge?

**Comment by Tanguy-SALMON** [comment]
@mickaelandrieu

The bug have nothing to do with the change I have introduced so you can merge.

**Comment by mickaelandrieu** [comment]
Thanks and welcome here :)

**Pull request merged**
