### PR TITLE
Revert php errors twigs component

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Revert php errors twigs component PR since it's useless from starting using symfony layout. The php errors will be display in the symfony debug bar.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto tests 🟢 
| Fixed ticket?     | 
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/33167
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/5681046431

**Comment by lartist** [comment]
Sorry @djoelleuch this PR doesn't need QA. The code is behind a feature flag. It means it's not activate as things stand. When the epic is finished a whole campaign on the admin layout will be asked.

**Review by boherm — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @lartist  , 

Automated tests are OK :heavy_check_mark:  (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/5681179533) 
LGTM , it's QA :heavy_check_mark: 
thank you

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/5710426048

**Pull request merged**
