### PR TITLE
[-] BO : Add $id_cart to Message in PaymentModule::validateOrder()

### PR DESCRIPTION
**Pull request by simondaigre**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Best regards

**Comment by PrestanceDesign** [comment]
Hi @Elitius !
Why these commits is useful ? I have some clients who recently updated their shop and they don't want see these entries in their customers threads.

Can I just remove these lines in `validateOrder` overrided method without create collateral damage ? 

image

**Comment by Elitius** [comment]
Hi @PrestanceDesign,

I've done this PR because without $id_cart, the thread is not created. I know this is boring, because some payment modules are adding this kind of message, but without this commit, it also get rid of customer's order message (the message bloc in carrier order step).

The check is done after the message is created:
// Specify order id for message
`
$old_message = Message::getMessageByCartId((int)$this->context->cart->id);
`

And the message is copied a second time in a CustomerMessage instance :

`
if ($old_message)
{
						$update_message = new Message((int)$old_message['id_message']);
						$update_message->id_order = (int)$order->id;
						$update_message->update();
						// Add this message in the customer thread
						$customer_thread = new CustomerThread();
						$customer_thread->id_contact = 0;
						$customer_thread->id_customer = (int)$order->id_customer;
						$customer_thread->id_shop = (int)$this->context->shop->id;
						$customer_thread->id_order = (int)$order->id;
						$customer_thread->id_lang = (int)$this->context->language->id;
						$customer_thread->email = $this->context->customer->email;
						$customer_thread->status = 'open';
						$customer_thread->token = Tools::passwdGen(12);
						$customer_thread->add();
						$customer_message = new CustomerMessage();
						$customer_message->id_customer_thread = $customer_thread->id;
						$customer_message->id_employee = 0;
						$customer_message->message = $update_message->message;
						$customer_message->private = 0;
						if (!$customer_message->add())
							$this->errors[] = Tools::displayError('An error occurred while saving message');
					}
`

So if you don't add $id_cart in Message, you only see it on order page, and no thread will be created.

**Comment by PrestanceDesign** [comment]
Hello @Elitius 

OK nice, thx for your explanation.
I'll see what I can do.

Best regards.

**Pull request merged**
