### PR TITLE
[+] MO: Use positions with HelperList

### PR DESCRIPTION
**Pull request by PrestaEdit**
Use:

```
function getContent()
{
  $helper = new HelperList();
  $helper->table_id = 'module-'.$this->name;
  [...]
}
```

### CODE REVIEW

**Comment by PrestaEdit** [comment]
A module example with this: https://github.com/PrestaEdit/PrestaShop-Canvas/tree/master/PrestaShop%201.6/Modules/helperlist_positions

**Comment by prestarocket** [comment]
It should be :
  $helper->table_id = 'table-module-'.$this->name;

**Comment by PrestaEdit** [comment]
No, @prestarocket ; "table-" is added by default when you have "table_id" defined. [https://github.com/PrestaShop/PrestaShop/blob/1.6/admin-dev/themes/default/template/helpers/list/list_header.tpl#L243]

**Comment by prestarocket** [comment]
so you have to change your js because : table in id is removed on drop https://github.com/PrestaEdit/PrestaShop/blob/helperlist_options-modules/js/admin/dnd.js#L61

					module = table.id.replace('module-', '');

**Comment by PrestaEdit** [comment]
Yes, @prestarocket ! My commit was not done ! Do it right now !

**Comment by PrestaEdit** [comment]
Done, :+1:

**Comment by jeromenadaud** [comment]
Hi guys,

Thank you for your contribution, nice jobs.

Best regards.

**Comment by prestarocket** [comment]
:+1:

**Pull request merged**
