### PR TITLE
Fix ordering by product name + add ordering by product id (movements page)

### LINKED ISSUE #28895: BO - Mouvements page - Sorting by product name is NOK
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Catalog > Mouvements > When we try to sort by product name > The sort is NOK
image

With PS1786 => we have this
image

Seems related: https://github.com/PrestaShop/PrestaShop/pull/28140

### Expected behavior

The product name should be replaced by Product ID 

### Steps to reproduce

1. Create some products with aaaa / bbbb / ccccc & edit the quantity for each product
2. Go to BO > Catalog > Stocks page > Mouvements tab
3. Try to sort by `Product name`
4. See error: The sort is not working with product name, but with the product ID

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fix the trivial regression mentioned here: https://github.com/PrestaShop/PrestaShop/issues/26427
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28895
| Related PRs       | ~
| How to test?      | Follow the issue
| Possible impacts? | ~

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by ghost — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
Hi @marsaldev

I don't know if you saw this issue https://github.com/PrestaShop/PrestaShop/issues/28894 which seems very similar, maybe it's not too much work to fix both bugs at the same time?

Maybe even your PR already fixes the issue

**Comment by marsaldev** [comment]
> Hi @marsaldev
> 
> I don't know if you saw this issue #28894 which seems very similar, maybe it's not too much work to fix both bugs at the same time?
> 
> Maybe even your PR already fixes the issue

Hi @jolelievre, unfortunately I haven't seen it :) 
I can work on it 😉, but I think needs a different PR, this one acts on the grid (simply ordering) while that issue is on the filters, wdyt?

Just checked, mine PR doesn't fix the issue (#28894) :(

**Review by marwachelly — COMMENTED** [review]
Hello @marsaldev,

PR will be tested as soon as issue will be fixed.

Many thanks,

**Comment by marsaldev** [comment]
> Hello @marsaldev,
> 
> PR will be tested as soon as issue will be fixed.
> 
> Many thanks,

Hi @marwachelly, I think there is a misunderstanding, this PR #29047, solve the issue #28895 😊
I was referring the other issue mentioned by @jolelievre https://github.com/PrestaShop/PrestaShop/issues/28894

**Comment by jolelievre** [comment]
My bad @marsaldev you're right it's a different issue that should be fixed separately.

And sorry @marwachelly my comments maybe was confusing but this PR is perfectly testable for the issue it's assigned to which is https://github.com/PrestaShop/PrestaShop/issues/28895

**Review by jolelievre — DISMISSED** [review]

**Comment by marsaldev** [comment]
No worries @jolelievre!! 😉

**Comment by marsaldev** [comment]
gently reminder @PrestaShop/qa-team 😊

**Review by NeOMakinG — DISMISSED** [review]

**Review by marwachelly — COMMENTED** [review]
Hello @marsaldev,

Thank you for your PR. I tested it but I noticed an error in the sort following the steps bellow:

1. add 3 products with the names yyyyy, aaaaa, zzzzz
2. edit the quantity of the 3 new added product
3. Go to catalog>Stock and check  the "Bulk edit quantity"
4. Increase the quantity to 3 (for example)
5. Click on Apply new quantity (for all products)
6. Go to tab movements and sort by name in ascending order (from a to z)
7. go to the next page from the list => the sort is not correct in the page number 2 
8. When trying to apply the sort in the page 2. At the first click on the sort, it is not working.



https://user-images.githubusercontent.com/89604350/181036457-d61d1378-7cda-40aa-b78e-1e285ad3a5f0.mp4

Could you please check?

Many thanks,

**Comment by matks** [comment]
@marsaldev Friendly reminder

**Comment by marsaldev** [comment]
@matks I'm on it 😊

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by sLorenzini — APPROVED** [review]
hello @marsaldev,

Thank you for your PR and sorry for the delay.
Tested on 8.0.x with PHP 7.3

Product on stock pages are well sorted by name:

[Stock • PS 8.0.webm](https://user-images.githubusercontent.com/2854834/194591179-e8737390-8d61-4096-b913-7595d5c07fce.webm)


QA approved ✅ 

Thanks

**Comment by matks** [comment]
Thank you @marsaldev

**Pull request merged**
