### PR TITLE
Carrier field in invoice must not be displayed if order is virtual

### LINKED ISSUE #26977: BO - Orders - Carrier field in invoice must be empty if order contains only virtuals products
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After updating an order from BO and adding only virtual products to this order.
In the invoice > The carrier field is not empty
image

In the Carrier tab => ok
image

This issue is reported by @nesrineabdmouleh 

### Expected behavior

image

### Steps to reproduce

1. Create an order with a simple standard product
2. Go to BO > Orders > View last order created and change status to payment accepted
3. Remove the product from the order
4. Add a virtual product to the same order
5. Download the invoice
6. See error in the carrier tab

### PrestaShop version(s) where the bug happened

1.7.7.8, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The Carrier field in the invoice must not be displayed if an order is virtual i.e if all products of an order are virtual.
| Type?             | bug fix
| Category?         | BO 
| Fixed ticket?     | Fixes #26977
| How to test?      | Go to the front end and add one or more than one virtual product to the cart. Make a successful order. Now go to the back office and download the invoice for that order. Since the order contains all virtual products that mean no shipping is required but the string is appearing https://prnt.sc/u1sfdh that is incorrect.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27001)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
thank you for your contribution 👍

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Amit-Kumar-Tiwari-Webkul,

I have two issues.

**First issue**
1. Create an order with a simple product
2. Go to BO > Orders > Last order created
3. Generate an invoice 
4. See error 

image

**Second issue**
1. Create an order with a simple product
2. Go to BO > Orders > Last order created
3. Generate an invoice 
4. Try to add a vector product to the same order with creating a new invoice
5. Download the invoice
6. See error 
image

Thanks!

**Comment by mikirimiki** [comment]
The shipping section for a virtual product appears on the checkout as well.
Should I open a new Issue?

**Comment by Progi1984** [comment]
Hi @Amit-Kumar-Tiwari-Webkul,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

**Pull request closed without merging**
