### PR TITLE
Fix tinymce RTL text direction

### PR DESCRIPTION
**Pull request by Danoosh**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix text direction bug in tinymce editor for RTL languages
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Editor text direction is LTR now. You can see admin product add/edit page in both RTL and LTR languages.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8838)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8838#-:-LAvay96-UbcCNjwtfmp:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Thank you @Danoosh

**Comment by marionf** [comment]
@eternoendless 1.7.4.0 ?

**Comment by eternoendless** [comment]
Thank you @Danoosh

**Pull request merged**
