### PR TITLE
Translation app URL, refresh and selection issues

### LINKED ISSUE #31115: Translation app URL, refresh and selection issues
### Describe the bug and add attachments

There are multiple issues with translations I found.

### Steps to reproduce

1. Get develop.
2. Go to BO > International > Translations.
3. Select `Front office translations` > `Core` > `Any language`.
4. Click modify.
5. See that the URL is weird - `http://localhost/dev/admin-dev/translations/dev/admin-dev/index.php/improve/international/translations/?lang=cs&type=themes&locale=cs-CZ&selected=0&_token=J5NKtedIAAf0GJu46m40uWTY6OTcB_yZsn-rlnzPnDA` - **Issue 1**
6. Hit refresh or F5 - error 404 - **Issue 2**
7. Go back in your browser, see that `Front office translations` are still selected, but not the second selectbox. - **Issue 3**
8. Click modify. Translation app loads and red `undefined` toast is shown in right top corner - **Issue 4**

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | This PR fix translation app router to avoid url problem, and fix also translation settings form on page load.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31115 
| Fixed ticket?     | Fixes #31115 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
🎸🎉

**Review by FabienPapet — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @boherm 

I have checked this PR. The issue is fixed.
-Check with multistore : OK
-Check with different languages : OK
-Check with different PHP versions : OK
-Check with different browsers : OK
-Check with different options of Translations : OK

But, there are failures on automatic tests on Design and Classic https://github.com/HanaRebaiQA/testing_pr/actions/runs/4832142107/jobs/8661899538
**Nightly** : is all green https://github.com/PrestaShop/PrestaShop/actions/runs/4856676829

ping @PrestaShop/qa-automation What do you think ? Is it related to this PR ?

Thank You!

**Comment by nesrineabdmouleh** [comment]
Hello @HanaRebaiQA 

Thank you for your tests! 
Please rebase your branch and restart UI tests

**Comment by boherm** [comment]
Hello @nesrineabdmouleh @HanaRebaiQA!
I just rebased my branch :-)

**Comment by nesrineabdmouleh** [comment]
Hello @boherm,

Thank you! 
Maybe I didn't explain it well, it's about the main branch of https://github.com/HanaRebaiQA/testing_pr
Some updates are missing in the branch of @HanaRebaiQA please synchronise your fork and create a new run :)

**Comment by HanaRebaiQA** [comment]
Hello @nesrineabdmouleh 

Thank you for your feedback!
@boherm I think that we have to re-test the PR again following the new rebase. What do you think ?

**Comment by boherm** [comment]
@HanaRebaiQA in theory it will be ok, but why not!

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @boherm 

I have checked again this PR after the new rebase. 

Check the automatic tests: OK https://github.com/HanaRebaiQA/testing_pr/actions/runs/4883625190/jobs/8715230833 
But I found these issues : 

**Issue 1 :** which is the same one mentioned in the original issue (Issue 3) : **NOK** :x: 

1. Go to Translations > Front office translations > Core > Any language.
2. Click on Modify
3. refresh / without refreshing the page
4. Come back to the Translations page
5. See error >> The field `Select your theme` is not displayed!

image

https://user-images.githubusercontent.com/92912932/236258139-a40b76a1-457a-481a-9091-6ea9db4385f1.mp4


**Issue 2 :** An invalid form control error is displayed when clicking on modify and the Select your theme field is not displayed

1. Go to Translations > Front office translations > Core > Any language.
2. Click on Modify
3. refresh / without refreshing the page
4. Come back to the Translations page
5. See issue 1 
6. Click on Modify
7. See console with `F12` >>  An invalid form control error is displayed!

image

https://user-images.githubusercontent.com/92912932/236258264-747be2b8-88b0-410a-83b3-d8715a5f1691.mp4



Could you please check it again ?

Thank You!

**Comment by boherm** [comment]
Hum, it's weird. 🤔
After testing on my side, I can't reproduce.
Have you do a `make admin-new-theme` ?

**Review by AchrafKchaou1991 — APPROVED** [review]
Hello @boherm 
I have checked the Pr using differents :

- Langages
- Versions of PHP
- Browsers

The issue is well fixed,
[Untitled_ May 15, 2023 3_24 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/174e64bc-9eb1-45f9-82c4-8fdd9612f9cc)

The automated tests is  OK

LGTM QA :heavy_check_mark: 
 
Thank you!

**Pull request merged**
