### PR TITLE
Merge/1.7.8.x to 8.0.x

### PR DESCRIPTION
**Pull request by MeKeyCool**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Sync 8.0.x with 1.7.8.x
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Na.
| Related PRs       | Na.
| How to test?      | Na.
| Possible impacts? | Na.

### CODE REVIEW

**Comment by MeKeyCool** [comment]
@NeOMakinG , I would be interested that you double check the merge commit (due to some js/ts change. I prefer you to confirm that my merge is Ok)

**Review by matks — DISMISSED** [review]
Seems OK for PHP part

**Review by jolelievre — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Once it's OK for QA : It will only need au automation pass :)

**Review by NeOMakinG — DISMISSED** [review]
Couldn't detect something strange inside the merge commit, I hope we don't miss anything

**Comment by matks** [comment]
@MeKeyCool https://github.com/PrestaShop/PrestaShop/issues/29688 is fixed but you need to rebase

**Comment by atomiix** [comment]
@matks just a close/reopen should be enough ;)

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @MeKeyCool 

Thank your for this PR,I retry to do this PR : 
#29471 :white_check_mark: 
#29551 :white_check_mark:
#29635 :white_check_mark:

I do an automated test and all of this seems to be ok :white_check_mark:, 

test it and it's QA approved :heavy_check_mark: 

Thanks

**Review by AureRita — APPROVED** [review]

**Comment by matks** [comment]
Thank you @MeKeyCool and @AureRita

**Pull request merged**
