### PR TITLE
Replaces non-existent route by the correct one in geolocation controller

### LINKED ISSUE #29119: BO - Geolocation by IP address throws exception for read-only employee
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I have an exception when I try to save Geolocation by IP address option as an employee with only View Permission.

Screenshot 2022-07-20 at 11 52 03

In PS 1.7.7.8, it was not working either. There was an error 500:
Screenshot 2022-07-20 at 11 56 03

In PS 1.7.8.x, there was also an exception, but the error is more explicit:
Screenshot 2022-07-20 at 12 06 33

It's a semi regression.

### Expected behavior

I should have a warning: "You do not have permission to edit this."

Screenshot 2022-07-20 at 12 04 12

### Steps to reproduce

1. Go to BO > Team > Profile
2. Create a new profile "stagiaire"
3. Go to Permissions > Choose "stagiaire" > click on "View" for everything
4. Go to Employees > Create new employee with profile "stagiaire"
5. Log out from your current account and Log Into your "stagiaire" account
6. Go to BO > International > Localization > Geolocation tab
7. Try to click on any Save button of this page
8. See exception

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.x, 8.0.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | A non existent route was used. I replaced it with the correct one. 
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29119
| Related PRs       | 
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/29119
| Possible impacts? |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by PrestaEdit** [comment]
Not going into `8.0.x` ? 🤔

**Comment by nicosomb** [comment]
> Not going into `8.0.x` ? 🤔

@PrestaEdit as the issue affects 1.7.7.8, 1.7.8.x & 8.0.x, we told me to target `develop`.

**Review by MhiriFaten — APPROVED** [review]
Hello @nicosomb ,

Thank you for your PR, I have checked it. The issue is well fixed.
Here is the checked list :

Check the automated tests : OK
Check with different languages (RTL and no RTL) : OK
Check Check with different browsers (Chrome & Firefox) : OK
Check with multistore: OK

https://user-images.githubusercontent.com/111756615/189626827-3d883647-9650-4fe0-835a-1e9873dd7c2e.mp4

Thank you :smile:

**Comment by matthieu-rolland** [comment]
thank you @nicosomb and @MhiriFaten !

**Comment by PrestaEdit** [comment]
I really don't understand why this is not added to the 8.0.x, at least.

**Pull request merged**
