### PR TITLE
Solved problem with a category thumbnails

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | We can't use thumbnail without using category banner at this moment, i think this is mistake |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | no |
| How to test? | Try to add thumbnail before and after this change without using category banner |

### CODE REVIEW

**Comment by firstred** [comment]
Status: Code reviewed

**Comment by vincentbz** [comment]
Oh great ! I test it right now :)

**Comment by vincentbz** [comment]
there is a big decline on that category part in the 1.7 BO, so I cannot test your PR right now. I'll see with someone tomorrow.

Did you manage to make a thumbnail appear somewhere or even upload a thumbnail different from the category cover image ? It seems it doesn't work at all.

category thumbnail

**Comment by kpodemski** [comment]
So probably someone broke this feature in 1.7, i'll take a look into this, for sure it is ready to go on 1.6 branch

**Comment by kpodemski** [comment]
Yep, i can confirm that this doesn't work at all in 1.7, we have two options:

1. delete those fields for category thumbnail and "thumbnails" for blocktopmenu as they are not in use anymore in classic theme
2. re-work this feature for classic theme

**Comment by mickaelandrieu** [comment]
So ... @vincentbz ... what do we do here ?

**Comment by kpodemski** [comment]
@mickaelandrieu from what I saw in different PR this feature was fixed, i'm trying to find proper PR

**Comment by kpodemski** [comment]
Found it: https://github.com/PrestaShop/PrestaShop/pull/6046

so... this PR should be relevant now

**Comment by vincentbz** [comment]
hi,

Yes we needed to fix it deeper than your PR as it was not integrated into the starter theme, and I think it has also fixed what your PR does, we can use a thumbnail without cover

**Pull request closed without merging**
