### PR TITLE
CI : Added support to branch 8.1.x (and removed support to branch 1.7.8.x)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | CI : Added support to branch 8.1.x (and removed support to branch 1.7.8.x)
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | N/A
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

### CODE REVIEW

**Comment by kpodemski** [comment]
I think we have to change the rules for protected branches because action fails if the branch has something.something.x in the name. https://github.com/PrestaShop/PrestaShop/actions/workflows/cron_php_update_modules.yml 🤔

**Comment by Progi1984** [comment]
@kpodemski I think so. But it's not linked to this PR. :smile_cat:

**Review by nicosomb — APPROVED** [review]
:tada:

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/committers No need QA

**Comment by nicosomb** [comment]
Thank you @Progi1984 !

**Pull request merged**
