### PR TITLE
Fixed image of module on Payment page

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed module image display on Payment page
| Type?         | bug fix
| Category?  | BO
| Issue?        | Yes => [http://forge.prestashop.com/browse/BOOM-1791](http://forge.prestashop.com/browse/BOOM-1791)

### CODE REVIEW

**Comment by aleeks** [comment]
Could you rebase please @mickaelandrieu, for tests :/

**Comment by mickaelandrieu** [comment]
@aleeks done and I've added another fixed for prefered modules action

**Comment by aleeks** [comment]
thank you!

**Comment by aleeks** [comment]
Thank you @mickaelandrieu

**Pull request merged**
