### PR TITLE
Fix wiping module cache

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Improves loading performance by avoiding wiping module cache in some cases. Details below.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test page load in FO with profiler. You will see fewer SQL requests.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/10685330569
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### Details
Check profiler on any shop and you will see that there will be this query several times.

```sql
SELECT m.`id_module`, m.`name`, ms.`id_module`as `mshop`
                FROM `ps_module` m
                LEFT JOIN `ps_module_shop` ms
                ON m.`id_module` = ms.`id_module`
                AND ms.`id_shop` = XX
```

This query is coming from constructor in Module class. It's purpose is to load module ID and if it's active from database and store it into `static::$modules_cache`, so it can be later assigned from this cache to the module instance, on it's creation.
 https://github.com/PrestaShop/PrestaShop/blob/c10bd6317b22f45742cbae3b1017b4b505b310cf/classes/module/Module.php#L338

However, in the beginning of page load, until controller is initialized, this cache is wiped several times (5 in my case), because of this line. 

https://github.com/PrestaShop/PrestaShop/blob/c10bd6317b22f45742cbae3b1017b4b505b310cf/classes/module/Module.php#L362

This line was introduced in https://github.com/PrestaShop/PrestaShop/pull/3485, because in the beginning of the request process, when there is no `$this->context->shop->id` initialized yet, the cache could be retrieved for a default shop ID, instead of the one we are using.

https://github.com/PrestaShop/PrestaShop/blob/c10bd6317b22f45742cbae3b1017b4b505b310cf/classes/module/Module.php#L334

This may have worked, but it creates duplicate queries and is kinda a hackjob. `!$this->context->controller instanceof Controller` doesn't really mean the shop_id is ready.

### So, what I did to improve this and keep it working like it should
What I did was to change the query a bit so it loads the active statuses for all shops.

```
SELECT m.`id_module`, m.`name`, ms.`id_shop` as `id_shop`
FROM `ps_module` m
LEFT JOIN `ps_module_shop` ms ON m.`id_module` = ms.`id_module`
```

Then I store the active properties into the cache for all shops.

So, then whatever shop ID is used when constructing the module, it won't need to run this query again.

### Real world performance
On https://eshop-franke.cz/, I got down from 110 to 105 queries and few ms saved. Small piece in a puzzle.

Snímek obrazovky 2024-05-23 143707

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]
Since it is a micro-optimization I think we should move it to the develop branch 👍🏻

**Review by tleon — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]
I tested this PR.
Before PR: 127 queries, 8.7M memory
After PR: 120 queries, 8.1M memory

**It's small improvement, but important..** More small improvements = one big improvement. 

good find bro :)

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

I'm not sure I'm testing it right.

Fresh install `develop` branch :
Screenshot 2024-09-04 at 14 45 08

Fresh install `develop` branch with this PR :
Screenshot 2024-09-04 at 14 45 03

The number of queries is the same on the loading page of the FO.
Am I missing something ? :) 
Waiting for your feedback ! Thanks!

**Comment by Hlavtox** [comment]
@florine2623 I have no idea why you see simmilar results. :(
@kpodemski Could you test this also?

**Comment by florine2623** [comment]
I'll let a dev test it and validate it ^^

**Comment by pvujic** [comment]
@Hlavtox Why was this PR closed?
Just did some tests locally and the issue persists. 
When a module injects via hookModuleRoutes the controller is not yet set, and it wipes the cache, e.g. we have 10 modules with hookModuleRoutes it does this query 10 times for each hookModuleRoutes + 1 time when the controller is set and modules construct.

**Pull request closed without merging**
