### PR TITLE
Merge pull request #1 from PrestaShop/1.6

### PR DESCRIPTION
**Pull request by blackmode**
Update

### CODE REVIEW

**Comment by blackmode** [comment]
w

**Comment by blackmode** [comment]
w2

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR, but watch out it is empty, only a commit merge in it.

Regards

**Comment by jeromenadaud** [comment]
Hi, I close this PR

**Comment by blackmode** [comment]
Hi, yes - just testing forked repo, sry for PR

**Pull request closed without merging**
