### PR TITLE
Fixed category tree arrows behavior

### PR DESCRIPTION
**Pull request by LittleBigDev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | In category trees, arrows should be usable to expand / collapse items but right now, click does nothing.This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [BOOM-4123](http://forge.prestashop.com/browse/BOOM-4123)
| How to test?  | Apply the fix and check if click on these arrows expands / collapses the tree.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8496)

### CODE REVIEW

**Review by toutantic — DISMISSED** [review]
Works for me

**Comment by eternoendless** [comment]
Missing built assets :wink: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8496#-:-Kz4I5Pc4SCqXZjLE_XZ:bgb1tw3)*

**Review by eternoendless — CHANGES_REQUESTED** [review]
Missing built assets

**Comment by LittleBigDev** [comment]
Assets built.

**Comment by eternoendless** [comment]
Looks like something broke down

**Comment by LittleBigDev** [comment]
What do you mean ?

**Comment by eternoendless** [comment]
The travis build failed

**Comment by LittleBigDev** [comment]
Travis is green now

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8496#-:-KzONBmjZcT75iZQmz5i:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @LittleBigDev

**Pull request merged**
