### PR TITLE
Update licenses and clean routing controllers

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Update licenses in all core files that needed it using the `prestashop:licenses:update` And clean routng controllers using `prestashop:linter:naming-convention` Also added an exception for licenses in test files, and improve the linter command to detect invalid controller convetions and controllers not founs
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
@jolelievre CI is red


PHP CS Fixer wants to change a few things and integration tests fail
```
1) Tests\Integration\Core\Addon\Module\ModuleManagerBuilderTest::testInstall
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Cache\Adapter\FilesystemAdapter in /home/runner/work/PrestaShop/PrestaShop/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php:179
Stack trace:
#0 [internal function]: Symfony\Component\Cache\Adapter\FilesystemAdapter->__sleep()
#1 Standard input code(571): serialize(Array)
#2 Standard input code(1280): __phpunit_run_isolated_test()
#3 {main}
  thrown in /home/runner/work/PrestaShop/PrestaShop/vendor/symfony/symfony/src/Symfony/Component/Cache/Traits/FilesystemCommonTrait.php on line 179
```

**Comment by jolelievre** [comment]
@matks yeah I know but the main problem on this PR is about the failing tests, though I got "distracted" on other more urgent matters

**Review by FabienPapet — DISMISSED** [review]

**Review by atomiix — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
This PR impacts only tooling and license headers: there should be no regression in behavior

**Comment by matks** [comment]
Thank you @jolelievre

**Comment by matks** [comment]
@jolelievre Little warning: this PR introduced [a bug](https://github.com/PrestaShop/PrestaShop/issues/29667)

The file `install-dev/theme/js/sprintf.min.js` was modified by the license header updator. The behavior of the file was not modified BUT as the file changed, the integrity check now fails, causing an error when attempting to load it inside the Installer "Informations" step (see screenshot below).

Capture d’écran 2022-09-16 à 20 48 51

There is maybe more files with an identical problem, and we need to make sure the license updator tool does not do this again.

**Pull request merged**
