### PR TITLE
CLDR number formatter

### PR DESCRIPTION
**Pull request by LittleBigDev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Adapt formatter to use new specification entities. Please do not review this PR before PR #8581 is merged
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [FF-138](http://forge.prestashop.com/browse/FF-138)
| How to test?  |

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8597)

### CODE REVIEW

**Comment by eternoendless** [comment]
Reviewed 1 of 7 files at r1, 15 of 15 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 37 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LHMP-sGi8dece8l8K:-L2LHMP-sGi8dece8l8L:bk02fi5) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L37)):*
> ```PHP
> use PrestaShopBundle\Localization\Specification\Price as PriceSpecification;
> 
> class Formatter
> ```

Missing description

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 44 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LHQMTUCK3Y2Ud3WIB:-L2LHQMTUCK3Y2Ud3WIC:bp3z9bq) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L44)):*
> ```PHP
>     const MINUS_SIGN_PLACEHOLDER        = '-';
>     const PERCENT_SYMBOL_PLACEHOLDER    = '%';
>     const PLUS_SIGN_PLACEHOLDER         = '+';
> ```

What are these for?

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 70 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LHxZs4eXF70pFZQ0g:-L2LHxZs4eXF70pFZQ0h:b-ov8yho) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L70)):*
> ```PHP
>      *
>      * @param int $roundingMode
>      *   The wanted rounding mode when formatting numbers
> ```

If these are values from `Decimal\Rounding`, it should be specified in the doc, otherwise we can't know which values are valid

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 73 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIJbnCItR3Wrqek3i:-L2LIJboMtf98nUEHUGH:b-gp7sqi) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L73)):*
> ```PHP
>      *
>      * @param string $numberingSystem
>      *   Numbering system to use when formatting numbers
> ```

Should specify what a numbering system is or where I can find them

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 82 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIR1ez2S_iaMbLuyU:-L2LIR1ez2S_iaMbLuyV:b-jbu0u9) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L82)):*
> ```PHP
>     }
> 
>     public function format($number)
> ```

Missing Phpdoc

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LLRgxE1ba-mkKpkwP:-L2LLRgxE1ba-mkKpkwQ:bq0pfsf) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L87)):*
> ```PHP
>             $decimalNumber = $this->prepareNumber($number);
>         } catch (SPLInvalidArgumentException $e) {
>             throw new LocalizationException('Invalid $number parameter : ' . $e->getMessage());
> ```

You should always include the previous exception when retrowing an exception. It's the 3rd parameter of `Exception()`

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 130 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIar9MLiVSgaWGOG8:-L2LIar9MLiVSgaWGOG9:b7pahg9) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L130)):*
> ```PHP
>         $decimalNumber = new DecimalNumber((string)$number);
>         $precision     = $this->numberSpecification->getMaxFractionDigits();
>         $roundingMode  = RoundingMapper::mapRounding($this->roundingMode);
> ```

Parameter verification should be done as early as possible (this case: in the constructor), otherwise you can have an invalid instance of Formatter.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 130 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LJbrI1tA3hudsJivZ:-L2LJbrI1tA3hudsJiv_:bv3js5o) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L130)):*
> ```PHP
>         $decimalNumber = new DecimalNumber((string)$number);
>         $precision     = $this->numberSpecification->getMaxFractionDigits();
>         $roundingMode  = RoundingMapper::mapRounding($this->roundingMode);
> ```

I don't think this class should be aware of PrestaShop's "configuration" rounding modes, it would be better if it received Decimal's rounding modes directly. Mapping should be done in another class (suggestion: do it in the class that fetches the configuration)

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 132 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LJpGSiDskkZXqZwcR:-L2LJpGSiDskkZXqZwcS:b-3wvbef) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L132)):*
> ```PHP
>         $roundingMode  = RoundingMapper::mapRounding($this->roundingMode);
> 
>         $roundedNumber = (new Rounding())->compute(
> ```

You should use `$decimalNumber->toPrecision(...)` or `$decimalNumber->round(...)` depending on whether you want to keep trailing zeroes or not.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 169 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LKZLk_4ih7fIIBcPb:-L2LKZLk_4ih7fIIBcPc:b-9jxm03) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L169)):*
> ```PHP
>      * @return string
>      */
>     protected function splitMajorGroups($majorDigits)
> ```

Incomplete Phpdoc

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 192 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LK_rdY_fERPUjg08E:-L2LK_rdY_fERPUjg08F:b-jbu0u9) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L192)):*
> ```PHP
>     }
> 
>     protected function adjustMinorDigitsZeroes($minorDigits)
> ```

Missing Phpdoc

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 230 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LKhngTlHP9u4MwTRy:-L2LKhngTlHP9u4MwTRz:b-9jxm03) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L230)):*
> ```PHP
>      * @return mixed
>      */
>     protected function localizeNumber($formattedNumber)
> ```

Incomplete Phpdoc

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolListInterface.php, line 35 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LOQSf2YE7A9dXBw_X:-L2LOQSgShWFBXIbR2dE:bz49fo4) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Specification/NumberSymbolListInterface.php#L35)):*
> ```PHP
>  * (decimal separator, thousands separator, etc.).*
>  */
> interface NumberSymbolListInterface
> ```

Is this really necessary?

---

*[src/PrestaShopBundle/Localization/Specification/Price.php, line 156 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LOiW-EU4Nxfb0fJS0:-L2LOiW0pC9m09tjtDfD:b-mcuant) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Specification/Price.php#L156)):*
> ```PHP
>     public function getCurrencyCode()
>     {
>         return $this->currencyCode;
> ```

And how is this set?

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 147 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LP1Dbqhv0tkkixjWV:-L2LP1Dbqhv0tkkixjWW:b85qe95) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L147)):*
> ```PHP
>         $mocked->method('getInfinity')
>             ->willReturn($infinity);
>         $mocked->method('getNan')
> ```

Why don't you just use an actual `NumberSymbolList` instance?

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 209 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPMb7QFkXUPCf-xOg:-L2LPMb7QFkXUPCf-xOh:b-vs6r7e) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L209)):*
> ```PHP
>         }
> 
>         return $mocked;
> ```

You should have created actual instances. You would have noticed there's no way of setting the currency symbol

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 216 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPdsITYQnPHJPh3xu:-L2LPdsITYQnPHJPh3xv:b-k7bwaq) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L216)):*
> ```PHP
>         return [
>             'French positive number'           => [
>                 'specs'    => [
> ```

I think it will be easier to create test cases if you provide actual specification instances here instead of a complex schema

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8597)*

**Comment by LittleBigDev** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 37 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LHMP-sGi8dece8l8K:-L2LV6lCZs9YDJVqo0Aq:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L37)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing description
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 44 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LHQMTUCK3Y2Ud3WIB:-L2LV7_wkVCB47lwBRY9:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L44)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

What are these for?
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 70 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LHxZs4eXF70pFZQ0g:-L2LVTXNlXKtRnRpUSar:bb6un1j) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L70)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

If these are values from `Decimal\Rounding`, it should be specified in the doc, otherwise we can't know which values are valid
</blockquote></details>

Done

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 73 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIJbnCItR3Wrqek3i:-L2Lbhr1w7G0iQCbU0RF:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L73)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Should specify what a numbering system is or where I can find them
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 82 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIR1ez2S_iaMbLuyU:-L2LbjmyuhyQ8yWMBiXy:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L82)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing Phpdoc
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LLRgxE1ba-mkKpkwP:-L2LbpFSvLc3jvqC5QiN:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L87)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should always include the previous exception when retrowing an exception. It's the 3rd parameter of `Exception()`
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 130 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LJbrI1tA3hudsJivZ:-L2Lci0l_X7FvjZ_oUX8:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L130)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I don't think this class should be aware of PrestaShop's "configuration" rounding modes, it would be better if it received Decimal's rounding modes directly. Mapping should be done in another class (suggestion: do it in the class that fetches the configuration)
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 130 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIar9MLiVSgaWGOG8:-L2LclnFyA_nY0swfL04:bbyp51r) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L130)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Parameter verification should be done as early as possible (this case: in the constructor), otherwise you can have an invalid instance of Formatter.
</blockquote></details>

Should I make the `DecimalNumber`'s constructor verification redundant ? It already throws an exception for invalid numbers.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 132 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LJpGSiDskkZXqZwcR:-L2Ldd3u_uZqdjOojGKv:b-kqo3oe) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L132)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should use `$decimalNumber->toPrecision(...)` or `$decimalNumber->round(...)` depending on whether you want to keep trailing zeroes or not.
</blockquote></details>

After talking about it, I preferred using `Rounding::compute()` because it returns a decimal number instance. Decimal number's rounding method are returning strings.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 169 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LKZLk_4ih7fIIBcPb:-L2LenNTcT5ktxbO5xOt:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L169)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Incomplete Phpdoc
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 192 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LK_rdY_fERPUjg08E:-L2LgIrZzBeVbvVgCv5B:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L192)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Missing Phpdoc
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 230 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LKhngTlHP9u4MwTRy:-L2LhQCUHaUbEplqPhZ2:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L230)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Incomplete Phpdoc
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/NumberSymbolListInterface.php, line 35 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LOQSf2YE7A9dXBw_X:-L2LiUNZG0JXZIe96z6r:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Specification/NumberSymbolListInterface.php#L35)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Is this really necessary?
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Localization/Specification/Price.php, line 156 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LOiW-EU4Nxfb0fJS0:-L2Licxs91uevB4VYyel:bmp7f12) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Specification/Price.php#L156)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

And how is this set?
</blockquote></details>

Forgot to add it in the constructor :)

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 147 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LP1Dbqhv0tkkixjWV:-L2LjG0enNV73vZdULec:bm1939n) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L147)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why don't you just use an actual `NumberSymbolList` instance?
</blockquote></details>

Because I'm unit testing the formatter, and don't want to depend on `NumberSymbolList` implementation.

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 209 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPMb7QFkXUPCf-xOg:-L2LjZXn-NC3R406vCAk:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L209)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should have created actual instances. You would have noticed there's no way of setting the currency symbol
</blockquote></details>

Done.

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 216 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPdsITYQnPHJPh3xu:-L2LjbwT2um_bpbX5Tp7:b37vpxs) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L216)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I think it will be easier to create test cases if you provide actual specification instances here instead of a complex schema
</blockquote></details>

I don't want to depend on other real classes implementation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8597)*

**Comment by eternoendless** [comment]
Reviewed 2 of 15 files at r2, 8 of 8 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 130 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LIar9MLiVSgaWGOG8:-L2PPX-NrA_kx5j4pILi:b-nnq8v8) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/src/PrestaShopBundle/Localization/Number/Formatter.php#L130)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Should I make the `DecimalNumber`'s constructor verification redundant ? It already throws an exception for invalid numbers.
</blockquote></details>

No, I was talking about roundingMode

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 216 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2PQML4K2soDRCUdSPO:-L2PQML4K2soDRCUdSPP:b-qr1fv8) ([raw file](https://github.com/prestashop/prestashop/blob/cfe23fa641c371ec4013b52bc5d46f15cba0b4ef/src/PrestaShopBundle/Localization/Number/Formatter.php#L216)):*
> ```PHP
>         }
> 
>         return $majorDigits;
> ```

The Phpdoc for this method says that some transformation should be applied here, but nothing is done. Why?

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 244 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2PQv2gr_wxnldqAhdD:-L2PQv2hyp0x6hY-PMXT:b-m5rs7s) ([raw file](https://github.com/prestashop/prestashop/blob/cfe23fa641c371ec4013b52bc5d46f15cba0b4ef/src/PrestaShopBundle/Localization/Number/Formatter.php#L244)):*
> ```PHP
>         }
> 
>         return $minorDigits;
> ```

Not blocking, but this logic already exists in Decimal

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 147 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LP1Dbqhv0tkkixjWV:-L2PRZOPLkMgUgDzjNYu:b-wa3jxw) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L147)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Because I'm unit testing the formatter, and don't want to depend on `NumberSymbolList` implementation.
</blockquote></details>

IMO it's overkill to do it that way as you're mocking a data bag. You are stubbing the whole behavior of this class and replacing it with the same logic, essentially doing the job twice.

I think in those cases it's better  better to make your test a little more "integration-y" instead of going unitary-nazi "STUB ALL THE DEPENDENCIES". Stub only what you need.

This way has its advantages:
- Less work
- You are testing the actual dependency too (changing it will break the "interface" contract on which the Formatter relies)

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 209 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPMb7QFkXUPCf-xOg:-L2PU4TxDYtQhcdQ2Wef:b-6pccms) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L209)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still an issue for me

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 216 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPdsITYQnPHJPh3xu:-L2PTq4k--by9SNqFV71:b8b25vt) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L216)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I don't want to depend on other real classes implementation
</blockquote></details>

Why not?

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 239 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2PTwlsSqjKgYebkK5K:-L2PTwlsSqjKgYebkK5L:b-slooin) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L239)):*
> ```PHP
>                         'secondaryGroupSize' => 3,
>                     ],
>                     'rounding'            => 2,      // Half Up (PS_ROUND_HALF_UP)
> ```

You can use the actual constant (that what they are for)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8597)*

**Comment by eternoendless** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 216 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2PQML4K2soDRCUdSPO:-L2PZ9rT-gXags_-pa10:b-mcm2bq) ([raw file](https://github.com/prestashop/prestashop/blob/cfe23fa641c371ec4013b52bc5d46f15cba0b4ef/src/PrestaShopBundle/Localization/Number/Formatter.php#L216)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

The Phpdoc for this method says that some transformation should be applied here, but nothing is done. Why?
</blockquote></details>

My mistake, sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8597)*

**Comment by LittleBigDev** [comment]
Review status: 12 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/PrestaShopBundle/Localization/Number/Formatter.php, line 244 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2PQv2gr_wxnldqAhdD:-L2Pqb_OgDInTXDxsQXD:b-po39sv) ([raw file](https://github.com/prestashop/prestashop/blob/cfe23fa641c371ec4013b52bc5d46f15cba0b4ef/src/PrestaShopBundle/Localization/Number/Formatter.php#L244)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Not blocking, but this logic already exists in Decimal
</blockquote></details>

Indeed, but it is not compatible with major digits grouping (or maybe it is, but this is not obvious).
`Decimal/Number` is able to render a string with the correct amount of zeroes but this is a "final" result. However, this result needs more processing (major digits grouping) and I need a `Decimal/Number` for that. And `Decimal/Number` doesn't keep track of the precision I want.
I can't find a clean way to take advantage of `Decimal/Number` for data extraction AND `toPrecision()` at the same time.

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 209 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPMb7QFkXUPCf-xOg:-L2Q10lXm6Zd7F9YwHHy:bt2vr1b) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L209)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Still an issue for me
</blockquote></details>

Fixed.

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 216 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2LPdsITYQnPHJPh3xu:-L2Q13gXgaf-0PiMOZJ5:bt2vr1b) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L216)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why not?
</blockquote></details>

Fixed.

---

*[tests/PrestaShopBundle/Localization/Number/FormatterTest.php, line 239 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-L2PTwlsSqjKgYebkK5K:-L2Q0zDt39UYyvWo-RMb:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/bfbbda39db6ca159459a99a6e0826051cabae3c9/tests/PrestaShopBundle/Localization/Number/FormatterTest.php#L239)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You can use the actual constant (that what they are for)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8597)*

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8597#-:-L2Q9XLh-kFplymFHc_c:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Pull request merged**
