### PR TITLE
fix error while adding product to cart in quantity check

### LINKED ISSUE #27505: Cart check quantity when stock disabled
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error occured while adding product to cart (after clicking "add to cart" button and no entry for given product in ps_stock_available table.

### Expected behavior

Product should be added to cart without error...

### Steps to reproduce

- Disable Stock management
- remove entries from ps_stock_available table
- add to cart product 

### PrestaShop version(s) where the bug happened

1.7.8.0-1.7.8.3

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by vladikk007**
if no entry for given product in ps_stock_available table, variable $result2 has value false, so it should be checke before Product::isAvailableWhenOutOfStock is called

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | An error occured while adding product to cart (after clicking "add to cart" button and no entry for given product in ps_stock_available table.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27505.
| How to test?      | Disable Stock management, remove entries from ps_stock_available table, add to cart product
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27568)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
This makes sense 👍

**Review by saulaski — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Hello @vladikk007 

Your PR should target `1.7.8.x` branch because it's a regression. Could you rebase your PR? If it's easier for you, you can close this PR and create a new one targeting a valid branch.

**Review by kpodemski — CHANGES_REQUESTED** [review]
Needs rebase to `1.7.8.x`

**Comment by vladikk007** [comment]
Needs rebase to 1.7.8.x

**Pull request closed without merging**
