### PR TITLE
If price is not shown hide add to cart too. Fixes #37532

### LINKED ISSUE #37532: On product listing "add to cart" is shown even if prices are not.
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Initially found with hummingbird, but this affects all themes that show add to cart functionality in product listings. The initial issue has been closed in hummingbird repo for that reason: https://github.com/PrestaShop/hummingbird/issues/661

If customer group has the settting "Show prices: no" they will not see any prices and thus cannot buy the product. This works with the current default theme as it does not show add to cart button in product listing BUT hummingbird (and probably other themes) do show add to cart in the listing. The product quick preview works and product page work as expected.

Image

### Expected behavior

If customer group does not see prices for products the add to cart buttons should also be hidden from product listing

### Steps to reproduce

1. Install humminbird theme from: https://github.com/PrestaShop/hummingbird/releases/tag/v0.2.0 (or some other theme that shows add to cart buttons in product listing)
2. set "guest" and "visitor" customer groups to "show prices: no"
3. check the shop frontpage, prices are hidden but add to cart is still shown (of course it does not work)

### PrestaShop version(s) where the bug happened

8.2.0 branch

### PHP version(s) where the bug happened

8.1 (using the docker-compose.yml from the 8.2.0 branch)

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Hide add to cart if price is hidden
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install theme that shows "add to cart" on the product listings. Mark guest and visitor groups as "show prices: no". Check the prices and add to cart are hidden. Login with user that is in a group that does show prices. Check that prices and add to cart is shown in the product listing.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/12279464980 ✅ 
| Fixed issue or discussion?     | #37532
| Related PRs       | https://github.com/PrestaShop/hummingbird/pull/662#pullrequestreview-2464836989
| Sponsor company   | 

All thanks go to @Hlavtox for comment in the original PR to hummingbird theme:  https://github.com/PrestaShop/hummingbird/pull/662#pullrequestreview-2464836989

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `description` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#description))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — DISMISSED** [review]

**Review by ShaiMagal — DISMISSED** [review]
LGTM

**Comment by tswfi** [comment]
no idea how long this will take: https://github.com/tswfi/ga.tests.ui.pr/actions/runs/12088357135

**Comment by Touxten** [comment]
Hello @tswfi 

For me it never works, you have to choose to test a PR without Cache

I'm going to make a PR in this sense in the repo https://github.com/PrestaShop/ga.tests.ui.pr

**Review by Touxten — APPROVED** [review]

**Comment by Touxten** [comment]
As you can see, QA does the same thing 
Screenshot (17)

**Review by PululuK — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @tswfi ,

Some checks were not successful, could you check ?

Thanks!

**Comment by florine2623** [comment]
I have launched the tests here : https://github.com/florine2623/testing_pr/actions/runs/12121807599

**Comment by Hlavtox** [comment]
@tswfi The integration tests are failing, I think you need to modify the test expected data in `tests\Integration\Adapter\Presenter\Product\ProductLazyArrayTest.php`.

Because we return false from `shouldEnableAddToCartButton` in more cases, `getDeliveryInformation` will now return `null` instead of `PS_LABEL_DELIVERY_TIME_OOSBOA`.

**Comment by tswfi** [comment]
Yup, I noticed.. just busy elsewhere atm..

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @tswfi ,

Thanks for the PR !
It works as expected :

https://github.com/user-attachments/assets/15cc39ee-acfe-4ca4-b1b7-a772b8826ba6

It is QA ✅

**Pull request merged**
