### PR TITLE
Remove fakepath

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove fakepath
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2441 http://forge.prestashop.com/browse/BOOM-623
| How to test?  | Create a product with a file customization and then try to add the file on the front. You should not see the fakepath.

### CODE REVIEW

**Comment by basma-yangui-prestashop** [comment]
Hello @antoin-m,

Your fix did solve the ticket [623](http://forge.prestashop.com/browse/BOOM-623) but not the ticket [2441](http://forge.prestashop.com/browse/BOOM-2441). Isn't it?

**Comment by antoin-m** [comment]
@basma-yangui-prestashop My bad! [2441](http://forge.prestashop.com/browse/BOOM-2441) should be fixed now.

**Comment by aleeks** [comment]
Thank you @antoin-m

**Comment by afoucher** [comment]
Same problem on PS 1.6.1.4, from the BO in combinations options, can i use the same files ?

**Pull request merged**
