### PR TITLE
Restore legacy controller and template files deleted late in beta

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | We removed legacy template and controllers file late in beta period for 1.7.6.0. The pages were migrated so these files are supposed to be useless now however we have detected several regressions both from manual QA testing and automated E2E testing. Considering how close the release date is, we choose to restore these files with a deprecation notice and perform the removal in the early phase of v1.7.7 development.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | yes, it deprecates some legacy template and controller files
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/13935
| How to test?  | Please check that recent regressions are fixed thanks to this, including (but not only) https://github.com/PrestaShop/PrestaShop/issues/13935

This PR reverts:
- https://github.com/PrestaShop/PrestaShop/pull/13910
- https://github.com/PrestaShop/PrestaShop/pull/13852
- https://github.com/PrestaShop/PrestaShop/pull/13850
- https://github.com/PrestaShop/PrestaShop/pull/13849
- https://github.com/PrestaShop/PrestaShop/pull/13847

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13956)

### CODE REVIEW

**Comment by matks** [comment]
For deprecations:
- in .tpl files I added a smarty comment notice tag
- in controller files I added a phpDoc notice tag and a trigger_error in the `__construct()`
Example:
```
    /**
     * @deprecated since 1.7.6, to be removed in the next minor
     */
    public function __construct()
    {
        @trigger_error(
            'The AdminPreferencesController is deprecated and will be removed in the next minor',
            E_USER_DEPRECATED
        );
    ...
    }
```

**Review by eternoendless — APPROVED** [review]
:cry:

**Comment by zuk3975** [comment]
:cry:

**Comment by sarahdib** [comment]
@matks When i click on transplant a module in position page there is an error.

Capture d’écran 2019-05-24 à 14 58 34

**Comment by matks** [comment]
> @matks When i click on transplant a module in position page there is an error.
> 
> Capture d’écran 2019-05-24 à 14 58 34

I cannot reproduce this. Did you perform a full reinstall ? Cache and cookies cleared ?

Can you retry to check it was not a random error ?

**Comment by matks** [comment]
Thank you for review & QA

**Pull request merged**
