### PR TITLE
[*] FO : Fix PSCSX-5778 Default Bootstrap blocksearch schema search action

### PR DESCRIPTION
**Pull request by inetbiz**
Link Reference: https://developers.google.com/structured-data/slsb-overview

### CODE REVIEW

**Comment by inetbiz** [comment]
I tested this for a live site. https://developers.google.com/structured-data/testing-tool?url=https%253A%252F%252Fwww.holylandshopping.com%252F

**Comment by gskema** [comment]
:+1: for this PR.

However, I think the search actionURL needs to be updated to use `getPageLink`. Currently it looks like a mix of both friendly and unfriendly URL.

Also, wrapping the block with `WebSite` tags limits it's use elsewhere, because there (should) only be one tag in the page describing the same item

**Comment by inetbiz** [comment]
@gskema I didn't see anywhere else that linked to website schema. That's what Google wants for navigational type queries (website name), I think?

Gladly will edit my PR if you gave me an example I should have used getPageLink?  ;-)

**Comment by gskema** [comment]
`{$link->getPageLink('search', null, null, ['search_query' => '{search_query}'])|replace:'%7B':{ldelim}|replace:'%7D':{rdelim}}` would be a better solution, but still I think we hould wait for some other opinions.

**Comment by inetbiz** [comment]
:thumbsup: @gskema

**Pull request closed without merging**
