### PR TITLE
Update Symfony to latest patch

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Update dependencies for security
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | CI green, maybe check that install is ok
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24690)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]
Ok but it will conflict with #24681

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Does it need some QA ?

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 !

We will test the PR, thanks for the ping !

**Review by matks — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
Tests with some UI tests (Randomly chosen) on Symfony page.
It's QA :heavy_check_mark:

**Comment by atomiix** [comment]
Thanks @jolelievre & @boubkerbribri !

**Pull request merged**
