### PR TITLE
[-] FO: Searching by postcode in store locator

### PR DESCRIPTION
**Pull request by kpodemski**
This PR prevents problem with searching for store with specific postcode, for example 33181 can be in Germany, Ukraine and USA, this change prevents all the problems with this kind of situation.

How to reproduce this bug? Search for eg. 33181 in store locator, results array from Geocoder has few elements but currently in script we had results[0].

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hi @kpodemski,

I just tested your fix and I see the problem but it's still here even with your changes. Indeed, `Geocoder` return only one result even if there is more than one possibility.
Also, the stores are still not found.

Maybe I've missed something and let me know if I'm wrong.

Best regards

**Comment by kpodemski** [comment]
Hi @maximebiloe 

To be honest I forgot about this case, I tested it on default installation with few stores in USA from what I remember but I also notice few other issues like doesn't taking into account that shop can have local stores in USA and other countries, problem is related to default country set up in store.

I think this mechanism should be rewritten from scratch but I do not have time now :(

**Comment by kpodemski** [comment]
@maximebiloe one more thing, `Geocoder` returns more results but in code you had `results[0]` that's why I use loop here

**Comment by maximebiloe** [comment]
I checked what's inside `result` [here](https://github.com/PrestaShop/PrestaShop/pull/4251/files#diff-c0efb9cb04a3cb4db17c6ed100585655R94) and I didn't find a case where there is more than one result. Even with the postcode 33181.

We're aware that there is some bugs with the current Store Locator and it needs to be rewritten.

So, I close this PR, but if you eventually have time to look at it don't hesitate.

Regards

**Comment by kpodemski** [comment]
@maximebiloe what is your store country? Could you change it to USA? As I wrote, it is related to default PrestaShop country from BO because it's used here:
https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/controllers/front/StoresController.php#L289

**Comment by maximebiloe** [comment]
I've changed it to USA but still have only one result from Geocoder

**Comment by kpodemski** [comment]
@maximebiloe use `console.log(results);` in `searchLocations()` and type postcode: 33100

**Comment by maximebiloe** [comment]
Ok, with the postcode 33100 I have 5 results. I was trying with the postcode you gave initially 33181.
But it does not seem to correct the initial issue. The stores are still not displayed.

**Pull request closed without merging**
