### PR TITLE
Updated query to remove subquery

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | See bug 4 here https://github.com/PrestaShop/PrestaShop/issues/35591 
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no 
| How to test?      | See bug 4 here:  https://github.com/PrestaShop/PrestaShop/issues/35591
| UI Tests          |  https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/8551008706
| Fixed issue or discussion?     | See #35591 
| Related PRs       | #35270 
| Sponsor company   | PrestaShop SA

The subquery was OK, but the native PrestaShop SQL manager seems to be buggy. As we can't fix it (it's a 3rd dependency), it's better to change the query on our side

The new query looks like: 

```
SELECT DISTINCT ag.id_attribute_group, agl.name, ag.position, COUNT(a.id_attribute) as `values` 
FROM ps_attribute a
LEFT JOIN ps_attribute_group ag ON a.id_attribute_group = ag.id_attribute_group 
LEFT JOIN ps_attribute_group_lang agl ON agl.id_attribute_group = ag.id_attribute_group AND agl.id_lang = 1 
LEFT JOIN ps_attribute_group_shop ags ON ag.id_attribute_group = ags.id_attribute_group 
WHERE ags.id_shop IN ('1') 
GROUP BY ag.id_attribute_group 
ORDER BY position desc LIMIT 50
``` 

instead of : 

```
SELECT DISTINCT ag.id_attribute_group, agl.name, ag.position, acount.values 
FROM ps_attribute_group ag 
LEFT JOIN (SELECT COUNT(DISTINCT a.id_attribute) AS `values`, a.id_attribute_group FROM ps_attribute a LEFT JOIN ps_attribute_shop attrShop ON a.id_attribute = attrShop.id_attribute WHERE attrShop.id_shop IN ('1') GROUP BY a.id_attribute_group) acount ON acount.id_attribute_group = ag.id_attribute_group 
LEFT JOIN ps_attribute_group_lang agl ON agl.id_attribute_group = ag.id_attribute_group AND agl.id_lang = 1 
LEFT JOIN ps_attribute_group_shop ags ON ag.id_attribute_group = ags.id_attribute_group 
WHERE ags.id_shop IN ('1') 
ORDER BY position desc LIMIT 50 
```

### CODE REVIEW

**Comment by jolelievre** [comment]
Be careful the initial query was complex for a good reason, to handle the multishop count properly It doesn't mean there's no room for improvement but we must take into account this use case https://github.com/PrestaShop/PrestaShop/pull/14040#issuecomment-537043021 and make sure the count is correct in every type of shop context

So this should be thoroughly tested by both you @nicosomb and the QA after

**Comment by nicosomb** [comment]
@jolelievre you're right, there was an issue in multishop context. I fixed it with the last commit.

**Review by jolelievre — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @nicosomb ,

While testing this PR, I wanted to add specific Attributes for a specific shop, but I'm encountering the exception mentioned [here](https://github.com/PrestaShop/PrestaShop/pull/35270#pullrequestreview-1973064113).


I tested the SQL query, I have no more error/alert.

But The query doesn't retrieve the same info as before the migration ✅ 

Before, there were more columns displayed :
Screenshot 2024-04-02 at 14 38 56

After :
Screenshot 2024-04-02 at 14 39 00

Could you check ? 
Thanks :)

**Comment by nicosomb** [comment]
:( I don't have these columns locally. I will try on a fresh fork (as the other PR) :(

**Comment by nicosomb** [comment]
@florine2623 thank you for your review. 

I added the other columns, which are displayed in the export sql section. 
I have the "values" column now, is that annoying? 

Capture d’écran 2024-04-02 à 15 00 36

**Review by florine2623 — APPROVED** [review]
Hello @nicosomb ,

LGTM ✅
 
Screenshot 2024-04-02 at 15 45 56


Thanks !

**Review by boherm — APPROVED** [review]

**Comment by nicosomb** [comment]
UI tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/8551008706

**Review by tleon — APPROVED** [review]

**Pull request merged**
