### PR TITLE
Merge 8.0.x into 8.1.x

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Merge 8.0.x into 8.1.x
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI Green ✅ & [auto tests](https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4934699943) green ✅
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop

### CODE REVIEW

**Comment by 0x346e3730** [comment]
Tests running : https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4934699943

**Review by boherm — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]
In case you need one more approval

**Review by kpodemski — DISMISSED** [review]
Sorry for such a late review.

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional I think you can merge this one-liner?

**Comment by 0x346e3730** [comment]
> @PrestaShop/qa-functional I think you can merge this one-liner?

It breaks an auto test and there's an ongoing discussion as to what to do

**Review by boherm — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Pull request merged**
