### PR TITLE
Fix 'New' Translation domain

### LINKED ISSUE #32212: Product condition 'new' is missing in FO
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,

According to the case #30916, fixed by the case #31148, there is a misunderstanding I guess.

'new' has different meanings in other countries, as a product 'just added' or 'now available' vs. new as a condition.

It has been decided to move 'new' from `Shop.Theme.Catalog` to `Admin.Global` to make it appears correctly in BO.

Now if 'new' is selected in BO, how to make it appears in FO ?

In 8.0.3 version, the condition 'new' in FO is showing what appears on the flag, 'new' as a new product 'just added' (=Nouveau).
Therefore, it shows 'Nouveau' as a condition and that's wrong.

The expected condition is 'Neuf', accordingly the selected condition in BO ('Neuf')
image

Thank you in advance to fix this please.
Best regards

### Expected behavior
Product page, back office :

'New' in Admin.Catalog.Feature
'Used' in Admin.Catalog.Feature
'Refurbished' in Admin.Catalog.Feature

New label in the product listing, front office:
'New' in Shop.Theme.Global

New in the product page, front office (condition):

'New' in Shop.Theme.Catalog
'Used' in Shop.Theme.Catalog
'Refurbished' in Shop.Theme.Catalog

### Steps to reproduce

1. Goto BO -> Catalog -> Product -> demo_21 (or any) -> options -> condition
2. Active the condition case to be shown in FO -> select 'new' in french (=Neuf)
3. See the condition of the product in FO (=Nouveau) and not (=Neuf)

### PrestaShop version(s) where the bug happened

8.0.3

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Fix 'New' Translation domain
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see #32212 
| Fixed ticket?     | Fixes #32212 
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by tleon — DISMISSED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by lartist — DISMISSED** [review]

**Review by aniszr — COMMENTED** [review]
Hello @mflasquin 

Thanks for your PR, I tested it and found that problems still persist.
See attached screenshot:
image

Auto Test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5389841122 :heavy_check_mark: 

Thanks!

**Comment by MatShir** [comment]
@aniszr It is missing for the top of the screenshot, to be sure :)

**Comment by mflasquin** [comment]
@aniszr I think the error is from translations files :

image

ping @l-delin

**Review by boherm — APPROVED** [review]

**Comment by l-delin** [comment]
> @aniszr updated, the translation have to be added in crowdin

@WahbiPS @jolelievre 

> @aniszr I think the error is from translations files :
> 
> image
> 
> ping @l-delin

Hello, that's the issue.

**Comment by l-delin** [comment]
Hello @mflasquin, you're right -- that's just been corrected on Crowdin. However, the [string domain issue](https://github.com/PrestaShop/PrestaShop/issues/32212#issuecomment-1516072538) still persists 😄

**Comment by mflasquin** [comment]
Yes but with the PR it will be ok for the domain issue, no ? @l-delin

**Comment by l-delin** [comment]
@mflasquin yep 👍

**Review by FabienPapet — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @mflasquin 

I tested your PR, ALGTM :heavy_check_mark: 



See attached screenrecord :

https://github.com/PrestaShop/PrestaShop/assets/92626242/b7525006-7b1d-441f-8d6e-35344ddc6dd4

Auto Test : https://github.com/MhiriFaten/testing_pr/actions/runs/5552460657  :heavy_check_mark: 
Thanks!

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @mflasquin !

**Pull request merged**
