### PR TITLE
Better visibility for reference

### PR DESCRIPTION
**Pull request by PhpMadman**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Longer display box for product reference |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | no |

Let me know if anything else is needed, this is my first PR for 1.7

### CODE REVIEW

**Comment by xBorderie** [comment]
ping @vincentbz What do you think?

**Comment by vincentbz** [comment]
Hi,

I check with our designer to validate it, thanks :)

**Comment by vincentbz** [comment]
Seen with Léa, this PR is relevant.
So it can be merged, thanks @PhpMadman  !

**Comment by xBorderie** [comment]
Sadly, it cannot be automatically merged anymore since ##6161 was merged in the meantime (ping @maximebiloe and @nihco2).

@PhpMadman, could you rebase your PR? Thank you!

**Comment by PhpMadman** [comment]
It's updated. Now uses the css class that it was changed to in #6161

**Comment by PhpMadman** [comment]
Also corrected spelling in PR.  it's visibility not visability

**Comment by julienbourdeau** [comment]
Thank you @PhpMadman !

**Pull request merged**
