### PR TITLE
Remove deprecated methods in Language

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Language
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `Language::recurseDeleteDir()`
* Removed method : `Language::_copyNoneFlag()`
* Removed method : `Language::installEmailsLanguagePack()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26309)

### CODE REVIEW

**Review by tegbessou — APPROVED** [review]
PR is valid IMO

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaEdit Could you remove the use in https://github.com/PrestaShop/autoupgrade/blob/dev/classes/UpgradeTools/CoreUpgrader/CoreUpgrader17.php#L90 before accepting and merging this PR ?

**Comment by PrestaEdit** [comment]
Hi @Progi1984 ,

It's now done here https://github.com/PrestaShop/autoupgrade/pull/428

**Comment by Progi1984** [comment]
Thanks @PrestaEdit 

@PrestaShop/qa-functional Checked and no use founds except in PrestaShop/autoupgrade#428

**Pull request merged**
