### PR TITLE
Merge 8.1.x into develop

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4617111255
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @0x346e3730

**Review by boubkerbribri — DISMISSED** [review]
LGTM for UI tests

**Comment by nesrineabdmouleh** [comment]
Hello @0x346e3730 

UI tests are KO, please check the screenshot 
Capture d’écran de 2023-04-03 14-24-06

I think the problem is here => https://github.com/PrestaShop/PrestaShop/pull/32017/files#diff-113afe4a27ab97edd8acf092babfa5d5c64f43dc8af0bd85e0f738a7ceca658fL75

Thank you!

**Comment by 0x346e3730** [comment]
> Hello @0x346e3730
> 
> UI tests are KO, please check the screenshot Capture d’écran de 2023-04-03 14-24-06
> 
> I think the problem is here => https://github.com/PrestaShop/PrestaShop/pull/32017/files#diff-113afe4a27ab97edd8acf092babfa5d5c64f43dc8af0bd85e0f738a7ceca658fL75
> 
> Thank you!

You were right, badly handled conflict. Re-ran tests with the new changes.

**Comment by 0x346e3730** [comment]
Ping @boubkerbribri @nesrineabdmouleh can you check the UI tests that are failing and telling me if it's because of the PR or not please ?

**Comment by nesrineabdmouleh** [comment]
Hello @0x346e3730,

UI tests are fixed, please restart the failed jobs :)
Thank you!

**Comment by 0x346e3730** [comment]
👋  @nesrineabdmouleh, there is one error left : `Missing script: "test:functional:FO:08-12"`

https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4607833674/jobs/8162421700#step:27:33

**Review by zuk3975 — APPROVED** [review]

**Comment by djoelleuch** [comment]
Hello 
This PR should be approved by at least two @PrestaShop/prestashop-maintainers.
 I will remove the 'waiting for QA' label.
Thanks!

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4665412639

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]
Ok for UI tests

**Comment by jolelievre** [comment]
@Progi1984 as we discusses the third campaign for International is no green the remaining red ones should be fixed in the next PR that will contain the fix for the CI So I merge this one in the mean time to allow the next PR to be done quickly

**Pull request merged**
