### PR TITLE
MPN field is missing in sample product CSV

### LINKED ISSUE #29254: MPN field is missing in sample product CSV
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

MPN field is missing in sample product CSV
[screencast-nimbus-capture-2022.08.04-19_51_20.webm](https://user-images.githubusercontent.com/42021740/182871289-3433223a-8674-4760-aa76-9378409d4947.webm)

### Expected behavior

_No response_

### Steps to reproduce

1. Go to the Advanced parameter->import section
2. Download sample product CSV file
3. Upload it as an import file
4.  Due to missing column MPN all fields orders displaying wrong 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | MPN field is missing in sample product CSV [screencast-nimbus-capture-2022.08.04-19_51_20.webm](https://user-images.githubusercontent.com/42021740/182872564-f247ff9d-fd5e-455d-910f-838ad0d762b8.webm)
| Type?             | bug fix 
| Category?         |  BO 
| Fixed ticket?     | Fixes #29254 .
| How to test?      | Go to the Advanced parameter->import section<br>Download sample product CSV file<br>Upload it as an import file<br>Due to missing column MPN all fields orders display wrong

| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by zuk3975 — DISMISSED** [review]

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
HI,
Any status on this PR
Thanks

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
HI,
Is there any update on this PR?
Thanks

**Comment by kpodemski** [comment]
Hi @Amit-Kumar-Tiwari-Webkul 

Sorry for the late reply. Could you change the branch you targeting to `develop`? It is not a regression, and we cannot accept it on 1.7.8.x

**Review by FabienPapet — DISMISSED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
Needs to target `develop`

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
HI,
Base branch is changed,
Is there still any issue on this PR?

**Comment by zuk3975** [comment]
> HI, Base branch is changed, Is there still any issue on this PR?

merge commits are not allowed, you should rebase yor branch instead.

**Comment by kpodemski** [comment]
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find and motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
