### PR TITLE
Fix module upgrades, cleanup a bit

### LINKED ISSUE #34728: Module updates broken on develop
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Module updates are broken on develop branch in some cases. See steps to reproduce and the go back here.

### Workflow
- `C:\xampp\htdocs\dev\src\Core\Module\ModuleManager.php::upgradeMigration` calls `Module::initUpgradeModule` which tells it if there is a module upgrade available and loads upgrade data. 
- So let's go inside `Module::initUpgradeModule` method. It preloads `static::$modules_cache[$module->name]['upgrade']` with empty data, including `number_upgraded` counter. 
- Right after that, it calls `Module::needUpgrade` ➡️  `Module::getInstanceByName($module->name)` ➡️ `Module::coreLoadModule($module_name);` and by calling `ServiceLocator::get($module_name);`, it wipes the static data for some reason.
- So `static::$modules_cache[$module->name]['upgrade']['upgraded_from'] = $module->database_version;` set in `Module::needUpgrade` is maybe useless.
- Then, it loads this list partially back in `$module->loadUpgradeVersionList`, but without those default empty keys.
- Now, back to ModuleManager and runUpgradeModule call - we don't have `number_upgraded` in that data.

### Expected behavior

_No response_

### Steps to reproduce

1. Get develop
2. Install https://github.com/PrestaShop/gsitemap/releases/tag/v4.3.0
3. Clone following branch https://github.com/ShaiMagal/gsitemap/tree/dev
4. Go to backoffice and try to update the module.
5. 🔴 See error `Cannot update module gsitemap. Warning: Undefined array key "number_upgraded"`

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes some of the magic with module upgrades. It could be rewritten some day, but now it at least works. Removed some unused things when I was digging through it.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests green.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7045684274
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34728
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by ShaiMagal — DISMISSED** [review]

**Comment by Hlavtox** [comment]
Test run - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7035634732

**Review by ShaiMagal — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Comment by Hlavtox** [comment]
Ping @PrestaShop/qa-automation to check that test failure is not related. :-)

**Comment by nesrineabdmouleh** [comment]
Hello @Hlavtox 
Yes, the failure is not related to the PR :)

**Comment by Hlavtox** [comment]
I reverted deletion of one method, it's used by autoupgrade module ONLY. Added some comments so the next person has easier digging through it. :-)

New run - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7045684274

**Review by ShaiMagal — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(1).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/883663cb-2ddc-4bde-a46c-4e246314fef8)

Link to the auto test : https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7045684274

Because the auto test is :green_circle: (as @nesrine said, the failed job isn't your pr fault) and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by SharakPL** [comment]
On 8.1 and previous versions (even 1.7) you sometimes get an error like "can't upgrade the module undefined". Especially if you use the `Update All` button. Like the module data gets lost in the process. Seems random as the next try on the same modules (not upgraded with first try) is usually successful.

**Pull request merged**
