### PR TITLE
Uniformise and improve cart stock protection

### LINKED ISSUE #33947: FO - Cart - Alert message is not correct in cart when the stock is low
### Describe the bug and add attachments

There are two issues on cart page.
- When product is no longer available, the error you get is different:
  - If you refresh the page cleanly
  - If you change amounts in arrows.
- When there is an error and you change quantity of another product that is in stock, the error disappears and you can continue checkout. It will redirect you back, but it's wrong.

### Expected behavior

- The error must be always the same. It should probably only be `Mug Today is a good day is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted.`
- If there is an error, it can't be cleared after doing a valid action.

### Videos 

https://github.com/PrestaShop/PrestaShop/assets/6097524/67dda64b-0c56-45d0-b0c4-8152fec8c383

https://github.com/PrestaShop/PrestaShop/assets/16019289/4d74199b-7f4b-4dd9-a3bf-dc7a3d1f485c

### Steps to reproduce

1. Create 2 products. Product A will have quantity 1 and disabled backorders. Product B will have quantity 300 and enabled backorders.
2. Add both products to cart. Go to cart.
3. Change quantity of Product A to 2. See one error.
4. Refresh page, see different error. 🔴 <- You should get the same one?
5. Change quantity of Product B. See that the error disappears and you can apparently continue checkout. 🔴

You can reproduce the issue with those easier steps :
1. Add 2 products "Mug Today is a good day" to you cart
2. Go to BO > Catalog > Products > Edit "Mug Today is a good day"
3. Edit quantity to 1 > Save
4. Edit Minimum quantity for sale : 2 > Save
5. Go to FO > Cart
6. Edit quantity
7. See alert message is incorrect :x:
8. You can still click on proceed to checkout even thought the product is not available anymore :x:

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Uniformize the error message when a product in cart has a quantity higher than the available one. Also perform a check on each product after each update to make sure there is not another product that wouldn't be available.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See issue also CI should be green along with UI tests
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6248510732 (Probably one test is gonna fail because the wording needs to be updated, but waiting for the final wording approval first)
| Fixed issue or discussion?     | Fixes #33947
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]

**Comment by Julievrz** [comment]
Hi @jolelievre and @MatShir
As we discussed, here's a suggestion of error message that could be used:

"There are only %nb_of_products_left% "%product_name%" left. Adjust the quantity in your cart to continue."

For example : They are only 3 “Mug The Adventure Begins” left in stock. Adjust the quantity in your cart to continue."

**Comment by Hlavtox** [comment]
@Julievrz That doesn't work in English nor other languages.

There are only 1 “Mug The Adventure Begins” left in stock. Adjust the quantity in your cart to continue.

There are technical limitations which I would like to solve so much, but we need to work with what we have... all this bad grammar just gives an impression of a scam shop with bad translations.

**Comment by Julievrz** [comment]
> @Julievrz That doesn't work in English nor other languages.
> 
> There are only 1 “Mug The Adventure Begins” left in stock. Adjust the quantity in your cart to continue.
> 
> There are technical limitations which I would like to solve so much, but we need to work with what we have... all this bad grammar just gives an impression of a scam shop with bad translations.

You're right, there are many things that should be improved regarding the way we manage plural. :(

We could either create a singular string and a plural string (but I'm not sure this works in all languages). 

Or maybe a quick win could be:

"You can only buy 3 "product_name". Please adjust the quantity in your cart to continue."
or
"The quantity of "product_name" in your cart must be less than or equal to 3." even if it sounds a bit technical.

**Comment by Hlavtox** [comment]
@Julievrz Yes, some wording that avoids having to use different grammar cases. I think the current wording is OK no?

`Available quantity of product "product_name" is 3. Please adjust the quantity in your cart to continue.`

➡️ I would avoid `less than or equal to 3` because there can be minimal quantity of 3. ;-)

**Comment by MatShir** [comment]
@jolelievre let's go with "You can only buy 3 "product_name". Please adjust the quantity in your cart to continue." then thanks everyone 🤗

**Comment by jolelievre** [comment]
Thanks everyone, that's much clearer and shorter now!!

**Review by M0rgan01 — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @jolelievre 

I tested your PR, and all the mentioned improvements are verified :heavy_check_mark: 

- Same Error message is displayed in the card :heavy_check_mark: 
- The error message still displayed even after a valid action in cart :heavy_check_mark: 

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/5fe75cce-fd80-4878-8025-e21923147dd1

Auto Test :  https://github.com/aniszr/ga.tests.ui.pr/actions/runs/6246848890 :heavy_check_mark: 

QA :heavy_check_mark: 

Thanks!

**Comment by Hlavtox** [comment]
Thank you @jolelievre!

**Pull request merged**
