### PR TITLE
Fix module updates

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Reverting one change from https://github.com/PrestaShop/PrestaShop/pull/34731. I burned myself and broke module upgrades. I added a comment so another person doesn't make the same mistake.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests green.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7489430664
| Fixed issue or discussion?     | It's passing an empty current version number into the method that loads upgrade files. Thus executing ALL of the upgrade files it found. Which results in an error when doing some database changes for example.
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by boherm — APPROVED** [review]

**Review by metacreo — APPROVED** [review]
Nice. Already in 8.1

**Review by tleon — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Hlavtox ,

I have an issue installing your PR 😓 
Screenshot 2024-01-22 at 10 33 24

I have that error :
```
Unknown error on line 351 in file /Users/fHea/Desktop/develop/classes/Tab.php
[8192] strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

Unknown error on line 951 in file /Users/fHea/Desktop/develop/classes/Dispatcher.php
[8192] trim(): Passing null to parameter #1 ($string) of type string is deprecated
```

And during installing here's what I have :
Screenshot 2024-01-22 at 10 34 49

Could you check ? 
Thanks :)

**Comment by Hlavtox** [comment]
@florine2623 Can't be caused by my PR. :-)

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Tested the upgrades of modules. LGTM :) QA ✅ 

https://github.com/PrestaShop/PrestaShop/assets/16019289/691f265e-1ef3-4353-9b62-df88ffee5018

Thanks!

**Comment by Hlavtox** [comment]
Thank you @florine2623! :-)

**Pull request merged**
