### PR TITLE
Multistore - Orders > Credit Slips - Add checkboxes

### LINKED ISSUE #19382: Multistore - Orders > Credit Slips - Add checkboxes
As a merchant, I want to be able to select one or many fields / toggles when I am in a specific shop context or in a group context, so I can apply a different configuration for the selected store or group and see which parameters have different value(s) for the selected store or group.

[Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

### LINKED ISSUE #19383: Multistore - Orders > Delivery Slips - Add checkboxes
As a merchant, I want to be able to select one or many fields / toggles when I am in a specific shop context or in a group context, so I can apply a different configuration for the selected store or group and see which parameters have different value(s) for the selected store or group.

[Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

### PR DESCRIPTION
**Pull request by nenes25**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | new feature 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19382.
| How to test?      | Multistore - Checkbox should be visible on field slip_prefix on page Orders > Credit Slips
| Possible impacts? | Change the way the data are saved with multistore

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25793)

### CODE REVIEW

**Comment by nenes25** [comment]
Sorry this PR is in fact for #19382 i've been confused between order delivery and order slips ...

**Comment by PierreRambaud** [comment]
Hi @nenes25 
Are you planning to continue the work on this PR, or should I close it?

**Comment by nenes25** [comment]
@PierreRambaud yes i'll finish it ;)

**Comment by matks** [comment]
@nenes25 friendly reminder 😄

**Comment by nenes25** [comment]
@matks  in fact i'm  stuck on this :/ 
I've retry last week and i still have an issue with the patch submission on the form which is not working.
I have done a workaround to force in post and it works, but not in a clear way according to initial @matthieu-rolland documentation

**Comment by matks** [comment]
Dear @nenes25  unfortunately this PR seems stale since more than 1 month. I close it, but as you know we can reopen 😄 . Please ping me if you wish to reopen this PR.

**Pull request closed without merging**
