### PR TITLE
Add Uzbek language in the installer

### LINKED ISSUE #16239: Add Uzbek to the installer
**Is your feature request related to a problem?**
It is not a bug, but a default parameter to update.

**Describe the solution you'd like**
For the 1.7.7 version, following recent activity on Crowdin, it would be nice to add Uzbek to the PrestaShop installer.

**Why?**
Since the installer helps you installing PrestaShop, it must be accessible to as many people as possible. And this is why it is available in many languages. If a language has a high level of translation on Crowdin, which is the case for the Uzbek project, without being available in the installer, we should consider adding it.

**How?**
Here, a pull request must be created to add a new folder in install-dev/langs, named with the code of the language we want to add.

### PR DESCRIPTION
**Pull request by LouiseBonnard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add Uzbek language in the installer
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16239
| How to test?  | Install PrestaShop in UZ

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10107)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by marionf** [comment]
@ntiepresta Why this is in waiting for author ? Is there an issue ?

**Comment by LouiseBonnard** [comment]
@marionf, we're actually waiting for @eternoendless to update the two JSON files ("legacy to standard locales" + "all languages") with the right data. It seems that the merging is blocked here because it is not set as a supported language yet.

**Comment by ntiepresta** [comment]
Hi, @marionf
Yes, the Uzbek language doesn’t applied in the installer
Best regards, Reddy Ntie

**Comment by PierreRambaud** [comment]
Uzbek language is not available yet, we need to wait until CLDR.

**Comment by LouiseBonnard** [comment]
Yep, it must be added to the software as a supported language... @eternoendless and the data team are on it. :-)

**Comment by eternoendless** [comment]
@LouiseBonnard, I think @PierreRambaud means that the current implementation of CLDR does not support Uzbek, which means that we can't install that language.

**Comment by PierreRambaud** [comment]
I move this PR to 1.7.6.0.

**Comment by eternoendless** [comment]
It's too late to merge this in 1.7.6, bumping it to 1.7.7

**Comment by marionf** [comment]
Guys, can we hope to have this one merged for 1.7.7 ?

**Comment by Progi1984** [comment]
New PR : #16374

**Pull request closed without merging**
