### PR TITLE
IN : Brings urls and pages in line with natural english

### PR DESCRIPTION
**Pull request by Dh42**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Page names are not natural english |
| Type? | bug fix / improvement / new feature |
| Category? | IN / FO |
| BC breaks? | yes, urls will be changed on upgrade possibly |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | self expanitory |

### CODE REVIEW

**Comment by xBorderie** [comment]
16k6qi

**Comment by Dh42** [comment]
lol totally

**Comment by kpodemski** [comment]
i know something about that, right pink @xBorderie ? :laughing:

**Comment by vincentbz** [comment]
Hi @Dh42 ,

If I create a shop with your modification, the two links "prices drop" and "best sales" disappear in the footer. Maybe your PR should rewrite the two urls too ? 

Thanks :)

image

**Comment by kpodemski** [comment]
It is because this change is related to ps_linklist and few other places
01.07.2016 14:41 "vincentbz" <notifications@github.com> napisał(a):

**Comment by julienbourdeau** [comment]
I would love to merge this but there will become consistency issue.
Are you sure it will find the correct controller if the class name and the `$this->php_self` are different from the meta name ? Like here: https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/BestSalesController.php#L30-L32

I would also love to fix it the template, since this is what is displayed to the customer:
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/best-sales.tpl#L6

**Comment by julienbourdeau** [comment]
@Dh42 If you want to change the display, you can change the translation in this file: https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/en/data/meta.xml#L11

Then we keep the 'technical' therm and display a better english title.

**Comment by aleeks** [comment]
@julienbourdeau  commented the PR, indeed, it is dangerous to touch directly to the technical name. The translation solution is currently favorable.
Thank you for your PR.

Regards

**Pull request closed without merging**
