### PR TITLE
Product flags: Fixed spacing with multiples flags on frontoffice

### LINKED ISSUE #25272: FO - the product-flags must be on the same row but with spaces
#### Describe the bug

The product-flags are displayed in the same row with no space

#### Expected behavior

The product-flags must be on the same row but with spaces

@prestascott notes:

- the out of stock label will be changed, so it won't be like that anymore
- the spacing between the 2 labels is 8 px

#### Steps to Reproduce

1. **BO** > **SELL** > **Catalog** > **Products**
2. Create a new product with a **specific price** (discount of 10% starting at 1 unit) and **qty**=0
3. **Save** and click on **preview** button
4. See error > the product-flags are displayed in the same row without spaces between them

**Screenshots**

### 1.7.8.x

image

image

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Product flags: Fixed spacing with multiples flags on frontoffice
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25272
| How to test?      | Cf #25272

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25387)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

All good to me !
Thanks !

**Comment by Progi1984** [comment]
## WAIT FOR 1780 RELEASE

**Review by jolelievre — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@Progi1984 I remember something about this, flags needed to be on the same row (as specified in the ticket), but with spaces, not on the same column, but @prestascott needs to validate it

**Review by sowbiba — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hi all,

Tested again, and it works like a charm.

Thanks for the PR!

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
