### PR TITLE
Fix top buttons on order view on mobile

### LINKED ISSUE #24732: [BO - Mobile] some Frontend regressions in View Order Page
#### Describe the bug

some Frontend regressions in Order Page

#### Expected behavior

nice and neat responsive display

#### Steps to Reproduce

1. Go to Orders > Orders
2. Click on **View** Order
3. See error > Update order status select & button is not well fit (see screenshot n°1)
4. Change the status to payment accepted
5. See error > all buttons are not well fit (see screenshot n°2)
6. Scroll down to **Products** bloc (add a cart rule to the order)
5. See error (see the screenshot n°3, the cart rule table is misplaced even with 1.7.7.4)

**Screenshot n°1**

image

**Screenshot n°2**

image

**Screenshot n°3**

image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Top buttons on mobile on order view page were completely broken
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24732.
| How to test?      | Go on order view page, set width to 320px and check top buttons
| Possible impacts? | Order view page top buttons

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24890)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Thanks for your PR!
So, I found some issues that has not been fixed within your PR:

**Desktop:**

- there's no espace between these buttons **Add a Product** and **Add a dsicount** and the block **total** below:

image


Tablet / medium screen (max:1299px)

- In the Block Documents (nav-tabs), when there's no document, the table is misplaced:

image

- Screen size between 768px and 1252, the nav-abs are not well displayed:

image

**Mobile:**

- mobile size between 375px and 401px (ex: iPhoneX):

image

- there's no space between the label **Items per page** and its select:

image

Well, I made a sreen record about all these issues (I hope I didn't forget anything :sweat_smile: ):
https://drive.google.com/file/d/1HUBRU1BCUvT2-0sSq2ORn2NhzHSqzu1m/view

Please check and feedback.

Thanks!

**Comment by NeOMakinG** [comment]
@hibatallahAouadni should be fine now

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Everything is perfect just this :sweat_smile: 

image

And to fix that, we need to change: 
```
#order-view-page .product-row .nav-tabs {
   overflow: auto;
}
```
by 
```
#order-view-page .product-row .nav-tabs {
   overflow-x: auto;
   overflow-y: hidden;
}
```

Thanks!

**Comment by NeOMakinG** [comment]
Good @hibatallahAouadni

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

You miss this issue:

image

You need to add `height: auto;` to `#order-view-page #view_order_payments_block #order_payment_id_currency`
Then, all LGTM

**Review by jolelievre — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
LGTM, QA :heavy_check_mark:

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG and @hibatallahAouadni

**Pull request merged**
