### PR TITLE
Callback on HelperList should have highest priority

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Callback result in HelperList should have highest priority to prevents error like this one
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | check before/after images below
| Sponsor company | impSolutions

BEFORE:
image

AFTER:
image

### CODE REVIEW

**Comment by kpodemski** [comment]
btw. i'll cherry pick this into 1.6 after merge here

**Comment by Shudrum** [comment]
Hey!

Thank you @kpodemski! Instant merge!

👍

**Comment by aleeks** [comment]
Strange, to me, it was working on develop before this..

Real problem was here: https://github.com/PrestaShop/PrestaShop/pull/7379/files

**Comment by kpodemski** [comment]
@aleeks it needs to be type=bool, that was not a problem, with your change you cannot filter on this field i don't know if you've noticed :)

**Comment by aleeks** [comment]
OMG, yes!
https://github.com/PrestaShop/PrestaShop/pull/7559 

Thank you!!!

**Pull request merged**
