### PR TITLE
Enhanced sav

### PR DESCRIPTION
**Pull request by djbuch**
Added IMAP attachements syncing (attachements are added if they are contained in the mail).
Added BO multiple attachements.

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by djbuch** [comment]
Hi,

ok I'll try to have a look at my PR and reply to it according your article.

Regards,
David

2015-11-05 17:41 GMT+01:00 Vincent Terenti <notifications@github.com>:

**Comment by vTerenti** [comment]
Ok thank you @djbuch !

Best regards

**Comment by djbuch** [comment]
Hi, is there a way to see what the conflict is ? Do I need to rewrite the PR ? I'm not very easy with Github. 

Regards,

**Comment by xBorderie** [comment]
Hey @djbuch !

A few things:
* Firstly, Git will display conflicts if you try to commit the very same code to the latest version of the PS code. Just use Git's tools to work through them, or rewrite the commit step by step.
* Secondly, this PR was made on the `1.6` branch, which is not used anymore. So yeah, you'll definitively have to create another PR on the correct branch.
* Thirdly, this is not a bugfix but new options (for an existing feature), so this new PR should be made in the `develop` branch.
* Finally, and before you do any more rewrite (and spend time on this), I want to make sure that what you are implementing is accepted. Could you give us a lot more details about your intentions with this PR? This way, our Product team will be able to make a decision about that idea. 

This is a long work that you have put into this, I want to make sure we are on the same point.

Thank you very much!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
