### PR TITLE
Change 9.0 to 9.1 to describe the develop branch

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | title says it all
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 🤷🏻‍♂️ 
| UI Tests          | ❌ 
| Fixed issue or discussion?     | ❌
| Related PRs       | ❌
| Sponsor company   | Krystian Podemski

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by Progi1984** [comment]
:warning: It's always 9.0.0 : https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Version.php#L35

**Comment by boherm** [comment]
Yes @Progi1984, isn't possible for now to do this because of distribution api. (https://github.com/PrestaShop/PrestaShop/pull/37516)
Anyway, I'm currently on it!

**Comment by Progi1984** [comment]
@boherm Time to fix Distribution API :+1:

**Comment by jolelievre** [comment]
Yep guys please be patient @boherm closed his PR https://github.com/PrestaShop/PrestaShop/pull/37516 on purpose because this is blocked for now because the distribution API doesn't handle a version under development so far ahead

So he's seeing if we can anticipate this even without the 9.0 released, if not we'll have to wait for the official release Give him some time ^^

**Comment by kpodemski** [comment]
@jolelievre @Progi1984 

That doesn't change the fact that `develop` points to 9.1 and we should merge this PR :))

**Comment by jolelievre** [comment]
Yeah, sorry I only looked at the title I thought you were doing the version bump again

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
