### PR TITLE
Merge branch 8.1.x into develop

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge branch 8.1.x into develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Ci is green. Tests : https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5588876840
| Fixed ticket?     | -
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @mflasquin ,

I have an error while testing the PR, during installation :
Screenshot 2023-07-19 at 11 50 28

I also had to rebase the PR :
Screenshot 2023-07-19 at 11 51 53

Could you check please ?
Thanks!

**Comment by mflasquin** [comment]
Hi @florine2623 I just try to reproduce without success (do you have made clear cache and composer install ?)

**Comment by M0rgan01** [comment]
I don't reproduce either. The pull request is not related to the error

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
Hello @mflasquin,

Can you restart the 2 campaigns [BO:design](https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5588876840/job/15236745075) and [BO:shop-parameters](https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5588876840/job/15236746492) plz ?

**Comment by sallemiines** [comment]
Hello @mflasquin 

I didn't manage to install the PR ! 

image


image


Tests auto are failed : https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5642992420

could you please check and feedback ! 

Thank you !

**Comment by mflasquin** [comment]
@sallemiines  as said by @boubkerbribri can you test with other alias (prcm) because It's the right way to test a merge PR I think

**Review by florine2623 — APPROVED** [review]
Hello @mflasquin ,

The PR is well installed with the `prcm` command.

Tested the following :

- Upload a theme, check the FO :x: error from nightly : https://nightly.prestashop-project.org/report/7216
- Upload a module, check the configure page
- Test the purchase of a product with a fake payment method and a fake delivery method in the default theme
- Login in the BO then open the product list
- Creation of a product

Functional part is OK for me ✅ 

Automated tests have been relaunched but are still broken : https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5588876840

@nesrineabdmouleh could you check ?

Waiting for @nesrineabdmouleh's approval before merging please.

**Comment by nesrineabdmouleh** [comment]
Hello @florine2623,

Thank you for your report!
The errors are not related to the PR (random) i'm working on it right now to fix them.
It's ok for me :heavy_check_mark:

**Review by nesrineabdmouleh — APPROVED** [review]

**Pull request merged**
