### PR TITLE
Improve display of gift message on order view

### LINKED ISSUE #32104: Improve the display of gift message in BO
### Discussed in https://github.com/PrestaShop/PrestaShop/discussions/32057

<div type='discussions-op-text'>

<sup>Originally posted by **Prestaworks** April  5, 2023</sup>
### The problem

Prestashop offers the customers the option to get the order gift wrapped and to add a message to the gift wrapping.

This message is displayed in not that great way today.
current gift message
it is hidden without styling in the shipping tab.

### The solution

I suggest that maybe it can be moved to below the labels and get some styling?

betterdisplaymaybe

and adding the label on the top of the order page 

image

### Alternatives

_No response_

### Additional context

_No response_

### Do you plan to work on this subject?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.</div>

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Improves the display of Gift message and gift wrapping icon in BO on order view.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Place an order with gift wrapping and gift message. View the order in BO
| Fixed ticket?     | Fixes #32104 
| Related PRs       | 
| Sponsor company   | Prestaworks AB

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Prestaworks 

I checked your PR. The feature is well-added.

- Check the automatic tests : OK
- Check with multistore : OK
- Check with different languages: OK 
- Check when creating an order from BO : OK
- Check when creating an order from FO : OK
image


But I found this issue : 

The size of the `Gift wrapping` on the top of the order is too big compared to the specifications.

**With PR :** 
image

**Specs :** 
image

@MatShir What do you think about this issue ?

Waiting for your feedback!

Thank You!

**Comment by MatShir** [comment]
Perfecto ! Thansk @HanaRebaiQA

**Comment by MatShir** [comment]
Can we consider QA ✅ ? @HanaRebaiQA

**Review by HanaRebaiQA — APPROVED** [review]
Yes @MatShir It's QA :heavy_check_mark: 

Thanks!

**Comment by nicosomb** [comment]
Thank you @Prestaworks

**Pull request merged**
