### PR TITLE
Improve GroupReduction

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Use `array_column` (faster / simpler) <br> `Db::execute()` already returns bool <br> Avoid nested and deep control structures.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No need. By dev.
| Fixed ticket?     | no
| Related PRs       | no
| Sponsor company   | -

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
thank you, it does make the code more readable 👍

**Review by boherm — APPROVED** [review]
LGTM @davidglezz!
Thanks!

**Review by M0rgan01 — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by FabienPapet** [comment]
Tests: https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/5280370799

**Comment by davidglezz** [comment]
I think the `Waiting for dev` tag was added by mistake

**Comment by M0rgan01** [comment]
QA by dev -> Ok for me

**Comment by mflasquin** [comment]
Thanks @davidglezz @M0rgan01

**Pull request merged**
