### PR TITLE
[*] FO : Add some data-* attributes to the <article>

### PR DESCRIPTION
**Pull request by prestamodule**
## Description

Allow us to add special actions or even CSS on a specific product into any list

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Maybe we should even do something like `data-product="{$product|json_encode}"`. What do you think ?
@ping @mickaelandrieu @djfm @maximebiloe

**Comment by kpodemski** [comment]
@julienbourdeau in that case we can also use Media::addJsDef and add some `product_datas` variable in Controller

**Comment by prestamodule** [comment]
@julienbourdeau I agree with @kpodemski, this should not go here i guess but use Media class. It will generate too much data into the page (slowing rendering ?) + showing sensible data ?
@kpodemski If we want to mark a product has "important" using some CSS rules, we can do it with this PR. Also, if we want to add some JS events on specific product, we can also do so.

**Comment by julienbourdeau** [comment]
I realized I used these for the quickview #5239 I'll see if I can adapt it.

**Pull request merged**
