### PR TITLE
Clean Back-office templates, part 4 - catalog

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | This PR should be considered as a BC because of lot of HTML structure changes and they might be used by a module or anything else, but it's acceptable. The optimizations are only within the files itself, so it does not matter if anyone uses the old version in any form in their modules.
| Deprecations?     | no
| How to test?      | Go through Catalog section BO and see if nothing is broken by this PR. There should be no visible change.
| Possible impacts? | No bad impacts. :-)

### Description
- I went through all templates and removed 99% of unneeded boostrap code like `<div class="row"><div class="col">XXX</div></div>`. It will reduce render depth and complexity by several layers - easier to navigate, debug CSS, maybe faster to render on slower PCs.
- I fixed all places where somebody used single quotations or no quotations at all.
- I fixed all places where somebody combined row and column in same element, this is not allowed.
- I fixed all places where somebody used syntax line col-sm-12 col-md-12 or col-md-12 col-lg-6. The first one is not needed.
- Small fixes here and there - removed some container classes, fixed module position page responsivity a bit, fixed virtual product block responsivity etc...
It should produce no BC breaks, unless some 3rd party module was targetting some classes they shouldn't have OR they targeted it by child or parent.

### Templates concerned
Product/CatalogPage
Product/ProductPage
Product/ProductPage/Panels
Sell/Catalog/Attachment
Sell/Catalog/Attribute
Sell/Catalog/AttributeGroup
Sell/Catalog/CartRule
Sell/Catalog/CatalogPriceRule
Sell/Catalog/Categories
Sell/Catalog/Features
Sell/Catalog/Manufacturer
Sell/Catalog/Manufacturer/Address
Sell/Catalog/Monitoring
Sell/Catalog/Product/Combination
Sell/Catalog/Product
Sell/Catalog/Suppliers
Stock
ProductImage

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26063)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
@Julievrz no wording changes

**Review by jolelievre — DISMISSED** [review]
Thank you @Hlavtox 
I'm not sure it was necessary to clean the legacy product page layouts, but since it's already done... nice work!! 😉

**Comment by Hlavtox** [comment]
@jolelievre Once I start, there is no stopping me :trollface:

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@hibatallahAouadni rebased

**Review by jolelievre — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

I encountred an issue wit auto test in Brands page:

image

We need to change the selector by removing the `.row`:

image

@PrestaShop/qa-automation could you please check it in this [file](https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/campaigns/functional/BO/03_catalog/05_brandsAndSuppliers/brands/01_CRUDBrandAndAddress.js) :wink: 
Otherwise LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by boubkerbribri** [comment]
Thanks @Hlavtox and @hibatallahAouadni,
We did add a fix on UI tests, it's all good for functional/catalog tests (we did rerun all).
We will wait for maintainers reviews before adding the QA :heavy_check_mark: .

**Comment by Hlavtox** [comment]
@boubkerbribri Thank you man!!! 🚀🚀🚀

**Comment by Hlavtox** [comment]
@boubkerbribri And have a look on these, if you are on it ;-)
https://github.com/PrestaShop/PrestaShop/blob/0da6d3bc9abeebe9fdb7db146a540f63564f49bf/tests/UI/pages/FO/FObasePage.js#L22
https://github.com/PrestaShop/PrestaShop/blob/0da6d3bc9abeebe9fdb7db146a540f63564f49bf/tests/UI/pages/FO/FObasePage.js#L65
https://github.com/PrestaShop/PrestaShop/blob/0da6d3bc9abeebe9fdb7db146a540f63564f49bf/tests/UI/pages/BO/catalog/suppliers/view.js#L19

**Comment by boubkerbribri** [comment]
> https://github.com/PrestaShop/PrestaShop/blob/0da6d3bc9abeebe9fdb7db146a540f63564f49bf/tests/UI/pages/FO/FObasePage.js#L22

What's the problem with this one?

I know that the others should be updated/deleted, however, it can be done on another one.

**Comment by Hlavtox** [comment]
@boubkerbribri Nothing now, but it would be universal if it was without the span. Now when making theme-refacto, we break it if we change span to div. :-)

**Comment by boubkerbribri** [comment]
> @boubkerbribri Nothing now, but it would be universal if it was without the span. Now when making theme-refacto, we break it if we change span to div. :-)

Thanks for pointing this out.  https://github.com/PrestaShop/PrestaShop/pull/26688

**Review by jolelievre — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
@boubkerbribri Could you please check these failing tests, thanks in advance :relaxed: 

image

**Comment by boubkerbribri** [comment]
It was a composer problem linked to GA. All tests passed after a restart.

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @Hlavtox

**Pull request merged**
