### PR TITLE
[-] BO: open "My Shop" link on new page

### PR DESCRIPTION
**Pull request by prestamodule**
## Description

With this, the click on the link "My Shop" (name of the shop) in the Back Office will be open in a new page.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @vTerenti is that intended ? What do you think ? 

@prestamodule would you mind to rebase it against develop ?

**Comment by vTerenti** [comment]
@mickaelandrieu Yes, it's good for me! :)

**Comment by mickaelandrieu** [comment]
Thank you @prestamodule

**Comment by vTerenti** [comment]
QA OK

**Pull request merged**
