### PR TITLE
Fix PHP Cs fixer

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Because an old pull request has been merge without taking in consideration the new php-cs-fixer configuration.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Travis and tests must be green. No need QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17435)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by matks** [comment]
Closing and reopening to wake up Travis who's drunk

**Comment by matks** [comment]
Capture d’écran 2020-01-30 à 17 33 13

**Comment by PierreRambaud** [comment]
Closed in favour of #17446

**Pull request closed without merging**
