### PR TITLE
[WIP] Improve code

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11658)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Commit: `Optimize order of PHP docs` should have name: `Use strict_param and fix a few more phpdoc orders`
And commit: `Use strict_param and fix a few more phpdoc orders` should have name: `Optimize order of PHP docs`

**Comment by MathiasReker** [comment]
Maybe I removed some not useless else statements..

**Comment by MathiasReker** [comment]
Should I finish the work, or is this PR too big to ever be merged?

**Comment by MathiasReker** [comment]
I close this PR and split it up.

**Comment by PierreRambaud** [comment]
It will be very hard to review. Not sure we can accept this kind of pull request, and because it's not in our cs fixer configuration.
WDYT @mickaelandrieu @matks ?

**Pull request closed without merging**
