### PR TITLE
Error in cache id naming

### LINKED ISSUE #32837: error in cache key name
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In Hook.php, method getAllHookIds, the `$cacheId` is wrong for `with aliases`. It is `'hook_idsbynamehook_idsbyname_withalias'` instead of `'hook_idsbyname_withalias'`.
https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L1223

The correct cache ids are 'hook_idsbyname' without aliases and 'hook_idsbyname_withalias' with, as ussed elsewhere, see https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L126

### Expected behavior

 The correct name is `'hook_idsbyname_withalias'`.

### Steps to reproduce

Look at the two lines. The error is obvious. https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L1223
https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L126

### PrestaShop version(s) where the bug happened

1.7.7 - develop

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix incorrect cache id
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | `echo $cacheId;` @ https://github.com/PrestaShop/PrestaShop/blob/32b958d86912b5ece2087e307dfc6aca9c7ba385/classes/Hook.php#L1225
| Fixed ticket?     | Fixes #32837
| Related PRs       | None
| Sponsor company   | Société Biblique de Genève

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]
Thanks @lmeyer1

**Review by M0rgan01 — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto-tests:
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5201297595

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional FYI, all auto tests ok, change is just a cache id, no impact on the functional side visible

**Comment by kpodemski** [comment]
thanks @lmeyer1 

happy to see so much activity from you again! ❤️

**Pull request merged**
