### PR TITLE
[*] CORE : Default shop object link generation PSCSX-7540

### PR DESCRIPTION
**Pull request by merguezzz**
http://forge.prestashop.com/browse/PSCSX-7540

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/4662)

### CODE REVIEW

**Comment by merguezzz** [comment]
Seems to be internal test environment errors ?

**Comment by merguezzz** [comment]
Second commit done. Any hint on what failed ?

**Comment by merguezzz** [comment]
Error "Exception: The method deleteProduct in the class Cart is already overridden by the module pscsx3241".

**Comment by mickaelandrieu** [comment]
Hello @merguezzz,

sorry for the delay, the pull request is not active since 2 years, so I'm gonna close it.

Fee free to re open a pull request if you still need it.

Thanks!

**Pull request closed without merging**
