### PR TITLE
make postcode field optional in BO

### LINKED ISSUE #29625: Postcode is a required field in admin address form, but is not checked in country settings.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

If I try to add a new address for a customer (existing or new), the form ask me for a Zip/Postal code, but the country have this option unchecked. This was the previous behavior after upgrade from 1.7.7.1 to 1.7.8.7

Form with Zip/postal code required.
screencshot of BO's form
image

Country has unchecked this option.
image

### Expected behavior

Form should allow leave postcode empty.

### Steps to reproduce

1. Uncheck Zip/Postal Code from country
2. Try to add a new address for a customer.
3. Fill form without postcode in the Back Office.
4. Submit the form
5. Postcode is required.

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by panariga**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | make postcode field optional in BO
| Type?             | bug fix 
| Category?         |BO
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #29625
| Related PRs       |
| How to test?      | Try to edit customer Address in BO, postcode should not be required anymore
| Possible impacts? |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
Probably best would be to check if the country needs postcode before saving the form, but it was not the case before (<1.7.8) thus I think we can accept it

**Review by kpodemski — CHANGES_REQUESTED** [review]
Sorry, I've noticed that you target wrong branch. It should go to 1.7.8.x

**Comment by kpodemski** [comment]
Hi @panariga 

Something went wrong during rebase. You probably tried to do it from GitHub UI, right? It won't work this way :(

Maybe it would be easier to open a new PR with your change so we can merge it to 1.7.8.8? :)

**Review by yanmakouf — COMMENTED** [review]
Your commit is fine to me. Just need to fix the branch commit history or open a new PR as @kpodemski said :)

**Comment by ghost** [comment]
@yanmakouf && @panariga i think we can use this https://github.com/PrestaShop/PrestaShop/pull/29114/files

**Comment by kpodemski** [comment]
@okom3pom I think it won't work 100% because this field would need to by dynamic, right? some countries require postcodes, and some don't.

**Comment by panariga** [comment]
> 
In admin interface it should be optional.
In real world I don`t know users postcode. I need to search this info.
And I can`t save changes to address without this info.
So if I need to change something quickly, i just can`t. Or I can use a dummy postcode. Bad option either

**Comment by ghost** [comment]
PrestaShop should use the country data and the required field data. 

This is not the case.

Your PR solves your problem but adds to others. 

I will check the code to use the country datas first and after required flieds to fix the problem for all.

**Pull request closed without merging**
