### PR TITLE
[ WIP ] Do not display any shipping method in the summary of virtual cart

### LINKED ISSUE #19963: Do not display any shipping method in the summary when ordering virtual products only
#### Describe the bug

The first (in terms or order) shipping method is chosen for an order with one virtual product and shown in the order summary.

#### Expected behavior

Not showing the shipping method in order summary when only virtual products in order

#### Steps to Reproduce

1. Go to BO > Shop Preferences > Order Preference 
2. Activate order summary
3. Save
4. In BO :  Create a virtual product
5. As a customer  add the virtual product to your cart
6. Checkout , create account, put address and view product summary

image (10)

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: the one used in https://demo.prestashop.com/

### PR DESCRIPTION
**Pull request by arouiadib**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In FO, order summary for virutal cart shoudn't contain shipping method. This PR adds only an if statement (2 lines ) and all the other modifications are caused by trying to indent. 
| Type?         | bug fix
| Category?     | FO 
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes #19963 
| How to test?  | Steps to reproduce the behavior:<br><br>- Go to BO > Shop Preferences > Order Preference<br>- Activate order summary<br>- Save<br>- In BO : Create a virtual product<br>- As a customer add the virtual product to your cart<br>- Checkout , create account, put address and view summary without shipping method

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20190)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matks — COMMENTED** [review]
I am not sure about this 🤔 

Maybe a shop could deliver virtual goods in different ways: some are downloadable files, other are subscribe-only goods, other are sent by email later.

Moreover I dont think this is the responsibility of the theme (= the view) to decide what should be displayed or not. I would prefer that we have a boolean `{if $display_shipping_infos}` instead of `{if !$cart.is_virtual}` and this `$display_shipping_infos` would be constructed inside the Controller. This would grant modules the ability to modify it without having to override the template or having to modify the product type.

**Comment by arouiadib** [comment]
@matks Thank you very much for sharing this info.
It is way better than what I did. I will try your approach

**Comment by matks** [comment]
Hi @arouiadib it looks like you could not find the time to work on this PR. Do I close it (and we can reopen later) or do you think you can do something in next weeks? 😄

**Comment by marionf** [comment]
Hello @arouiadib,

I close your PR because the issue https://github.com/PrestaShop/PrestaShop/issues/19963 has been fixed by https://github.com/PrestaShop/PrestaShop/pull/8738

Thank you for your PR :)

**Comment by arouiadib** [comment]
Sorry for delay guys, I just saw the messages. Perfect.

Special thanks to @marionf who posted the solution

**Pull request closed without merging**
