### PR TITLE
Product image adding, and products image regenerating :more performances

### PR DESCRIPTION
**Pull request by 123monsite-regis**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Product image adding, and products image regenerating :more performances : avoid loading image in memory several times, instead of this, load it once, and generate all wanted sizes |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | - |
| How to test? | 2 tests are needeed : 1/ adding pictures on products/combinations, 2/ regenerating pictures (one size and all sizes) from AdminImageController |

Whith this commit, you gain about 15% of time during pictures generations (gain may depend on your host).

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @123monsite-regis Your PR is about `develop` or `1.6.1.x` ?

**Comment by 123monsite-regis** [comment]
Hello ,
I made this code for 1.6.1.x, for 1.7 developp branch, it need to be adapted.

**Comment by aleeks** [comment]
Hello,
So I let you make a PR for `develop` branch.
I'm sorry :confused: but we won't merge improvement on another branch than develop. It's only for bug fix.

**Comment by 123monsite-regis** [comment]
ok :(

**Pull request closed without merging**
