### PR TITLE
Number specification Repository, Locale Repository

### PR DESCRIPTION
**Pull request by LittleBigDev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | **As a Locale, I need a repository to load Number Specifications**<br>
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [FF-147](http://forge.prestashop.com/browse/FF-147)
| How to test?  | See test suite !

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8693)

### CODE REVIEW

**Comment by tomlev** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Core/Localization/Locale/Repository.php, line 102 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8693#-L3gEVwHKSUHVPqb54Ii:-L3gEVwIm_yi2Pu6qwud:bn4w0wt) ([raw file](https://github.com/prestashop/prestashop/blob/9c357ece7f9855a34b0e88a4f4022a6b598bc85d/src/Core/Localization/Locale/Repository.php#L102)):*
> ```PHP
>         CurrencyRepository $currencyRepository,
>         $roundingMode = Rounding::ROUND_HALF_UP,
>         $numberingSystem = 'latn',
> ```

is there a way to get consts instead of magic strings here ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8693#-:-L3gI8I_XGsrSx9i27aX:bnfp4nl)*

**Comment by LittleBigDev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Core/Localization/Locale/Repository.php, line 102 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8693#-L3gEVwHKSUHVPqb54Ii:-L3gImHNloJRUGSPsLuU:bn5oer8) ([raw file](https://github.com/prestashop/prestashop/blob/9c357ece7f9855a34b0e88a4f4022a6b598bc85d/src/Core/Localization/Locale/Repository.php#L102)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

is there a way to get consts instead of magic strings here ?
</blockquote></details>

Yes it should. Not stated where yet, though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8693)*

**Comment by LittleBigDev** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Core/Localization/Locale/Repository.php, line 102 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8693#-L3gEVwHKSUHVPqb54Ii:-L3gNgPBAFXL4MRDNzhE:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/9c357ece7f9855a34b0e88a4f4022a6b598bc85d/src/Core/Localization/Locale/Repository.php#L102)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Yes it should. Not stated where yet, though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8693)*

**Comment by tomlev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Core/Localization/Locale/Repository.php, line 102 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8693#-L3gEVwHKSUHVPqb54Ii:-L3gTZmXyKtRYHtc12Dc:bwfgpi4) ([raw file](https://github.com/prestashop/prestashop/blob/9c357ece7f9855a34b0e88a4f4022a6b598bc85d/src/Core/Localization/Locale/Repository.php#L102)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

much better, thx ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8693#-:-L3gTcrMoCLknndv16JJ:bnfp4nl)*

**Review by tomlev — APPROVED** [review]

**Pull request merged**
