### PR TITLE
[-] CORE : Bugfix Hook.php country restrictions

### PR DESCRIPTION
**Pull request by Nobodaddy**
It really makes no sense to be forced to do the same bugfix because a developer ingnore the merges for the new release. 
Though 1.6.1.5 has flopped because of the many new bugs, this must not happen: https://github.com/PrestaShop/PrestaShop/commit/0993bed0683a7f4a5eb7e44c5c5432471985268e

### CODE REVIEW

**Comment by xBorderie** [comment]
Confirmed as an oversight.

**Comment by mickaelandrieu** [comment]
> It really makes no sense to be forced to do the same bugfix because a developer ignore the merges for the new release. 

After review of https://github.com/PrestaShop/PrestaShop/pull/4739 I didn't saw any information regarding a possible cherry-pick in ``1.6.1.x``. It could be nice to inform us next time, as we are realy focused and 1.7 for now.

Mickaël

**Comment by firstred** [comment]
There's something weird going on with the hooks anyway. The 1.7 should also keep an eye on the hook `paymentOptions`, but that has still not been added to `Hooks.php` on the `develop` branch. 
I hope that it will be added before the release of 1.7. This bug has been around for too long.

**Comment by mickaelandrieu** [comment]
@firstred I don't know what are you talking about :D 

If you can help on this point, don"t hesitate to make a report on the forge, it's very important for us.

**Comment by firstred** [comment]
These PRs:
https://github.com/PrestaShop/PrestaShop/pull/5240
https://github.com/PrestaShop/PrestaShop/pull/5243

If I take a look at #5240, I see that it is almost the same as this PR, but it prevents storing and caching info the cache as well.
If you want a Forge ticket, then that can be arranged, but the problem is simple: without these PRs the currency, group and country restrictions cannot be applied to payment modules which hook onto `displayPaymentEU` and `paymentOptions`.

**Comment by firstred** [comment]
http://forge.prestashop.com/browse/PSCSX-7946
http://forge.prestashop.com/browse/BOOM-629

**Comment by Shudrum** [comment]
I close this pull request, as another one have done the same modifications.

**Comment by xBorderie** [comment]
Namely, #5240.

**Pull request closed without merging**
