### PR TITLE
Update new-theme bootstrap and remove unused dependencies

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Some dependencies looked not used and Bootstrap was out of date
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Mainly on migrated pages, the update bootstrap could change a lot of styles (but the UIKit is using the updated version, so it should work as usual...), also some dependencies got removed so it may change some pages behavior if I did it wrong... Sorry but I can't precise more :(
| Possible impacts? | Whole migrated pages

# BC Break
Some dependencies were available globally, so modules may rely on this and will need to add the dependency inside their own assets

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25917)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Sounds good but maybe we should create a dedicated issue to list the dependencies removed/updated and help people track progress for 8.0.0 ? 😉

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Can you please check the Conflicting files?

Thanks!

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by HanaRebaiQA** [comment]
Hello,

I verified this PR. The issue is well fixed.
I tested the behavior in different pages which contains the date with : 
different languages (English, Français, Arabe), different format of dates (`, ; : - _ /`) , different browsers (Chrome, Safari, Firefox in different devices (Android, IOS)

LGTM, QA :heavy_check_mark: 
See screen-record (which contains one example) : 
https://www.awesomescreenshot.com/video/6035556?key=936182a6f1bc5a07de2bc5dab2b29460

Thanks,

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
New dependencies have a MIT License.

**Comment by NeOMakinG** [comment]
@Progi1984 which new dependency? I just removed babel one because we're now using esbuild-loader

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Could you rebase your PR, please ?

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is OK :heavy_check_mark: 
Automatic tests are ok, validated by @boubkerbribri, thanks!

In my case, I checked the whole migrated page => ok

Thank you!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @khouloudbelguith & @boubkerbribri

**Pull request merged**
