### PR TITLE
Show profile icon on mobile and hide see my shop text

### LINKED ISSUE #20522: [Profile Edit][Responsive] unreachable on migrated pages from size 1023x1037
#### Describe the bug

Depending on the size of my screen on migrated pages, I am not able to see the profile edit icon

#### Expected behavior

Being able to see the edit profile on various devices with screen size from 1023*1037 and less on migrated pages

#### Steps to Reproduce

1. Open a migrated page and set your screen size to 1023*1037 or less
2. See the profile edit icon isnt appearing 

**Screenshots**
Capture d’écran 2020-08-10 à 15 39 42

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Profile icon was not visible on mobile so you couldn't access you'r profile on migrated pages
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20522.
| How to test?  | Go on the BO, resize to low screen as in the issue, and see if you can see the profile icon, click on it and everything should work pretty well

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20688)

image

@PrestaShop/prestashop-product-team I've been forced to hide the "See my shop" sentence on mobile as we don't have any space anymore

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @NeOMakinG 

I was able to reproduce the issue:
https://drive.google.com/file/d/1A4XEq0anMx-3cpiNHgpiqy49vutMqYnO/view

As you can see, the edit icon appears 1/4 second then disappear: If it's not the wanted behavior, I don't think it should popup and disappear? It should just not be seen? 
Can you confirm @marionf ?
Also, I cannot see the edit profile page in menu if I switch to orders page for instance. 
As you can see in the video, part of the menu is split.

Thank you

**Comment by marionf** [comment]
Yes, there is an issue here, the profile isn't displayed in the menu on symfony pages
Depending on your screen size, the profile should be displayed at the top right or in the menu
But it shouldn't appear and disappear

**Comment by ngodefroy** [comment]
TEST OK, thank you @NeOMakinG 
https://drive.google.com/file/d/1-5TWhNEu_cZEVi_e4-QaT7Zcj_UqVY1b/view

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

**Pull request merged**
