### PR TITLE
Prevent including jQuery in the new theme

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | It shouldn't be possible to add jQuery to the new theme, because it's already included in the UI kit. This PR works better with this modification in gamification: https://github.com/PrestaShop/gamification/pull/62
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | maybe? - It's no longer possible to include jQuery twice
| Deprecations? | yes
| Fixed ticket? | n/a
| How to test?  | Using current gamification, it shouldn't work. Using the provided change it should. In any case, you should no longer have jQuery 1.x loaded in the new theme.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12716)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thanks @eternoendless

**Comment by damianobertuna** [comment]
Hi,
if addJquery is no longer supported, how can I be sure that a custom js file in a module I am developing is loaded after jQuery framework?
Can you help me?

**Comment by eternoendless** [comment]
@damiandominella Unless you're writing jQuery plugins, why would the order matter?

In any case, if scripts are being added to the page _before_ jQuery, that would be a bug.

**Comment by damianobertuna** [comment]
> @damiandominella Unless you're writing jQuery plugins, why would the order matter?
> 
> In any case, if scripts are being added to the page _before_ jQuery, that would be a bug.

Hi, in my javascritp code I use jQuery, so the loading order in important.

My module works well in PrestaShop version before 1.7.6 because I can use the method addJquery, but in the last PrestaShop version 1.7.6 addJquery is no longer allowed, so it's not clear how to load a custom javascript file after jQuery framework is loaded.

I repeat, it's a problem present only with PrestaShop 1.7.6.

**Comment by eternoendless** [comment]
Please open a new issue and ping me there.

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

Issue created by @damianobertuna: https://github.com/PrestaShop/PrestaShop/issues/16944

Thanks!

**Pull request merged**
