### PR TITLE
#11379 Prepend carrier ID, otherwise carrier would be overwritten

### LINKED ISSUE #11379: Multiple carriers with same name & delay key will not be display
**Describe the bug**
If two carriers with the same name and transit time (delay) then only one carrier display when we edit product for assign carrier, This is because we are creating the key with name and delay which can be same for multiple carriers. See this code

Code: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L71

Some shipping providers will create the same name and delay time carrier like DHL and other. they maintain with the service code of carriers in the different zone.

**To Reproduce**
1. Go to 'Shipping -> Carriers'
2. Click on 'Add Carriers'
3. and add two carriers with the same name & delay (Transit time)
4. Edit any product and see only one carrier display

**Screenshots**
download 2
download 3

**Additionnal information**
PrestaShop version: 1.7.4.4 & 1.7.5.0 beta also
PHP version: 5.6

### PR DESCRIPTION
**Pull request by manfield**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | When more carriers have the same name and delay, disappear on the carrier list on the product details' shipping tab carrier's list - because of elements of the associative array ($carriers) are rewritten. There're no other clean ways at the moment to solve this issue. But this is a valid fix, moreover it helps the user to identify easily the carrier, if the same name/delay is assigned.
| Type?         | bug fix 
| Category?     |  BO 
| BC breaks?    |no
| Deprecations? | no
| Fixed ticket? | Fixes #11379
| How to test?  | Follow issue instructions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13077)

### CODE REVIEW

**Comment by manfield** [comment]
I attach an image that shows the fix

Product • GR1PS 2019-03-31 12-16-36

**Comment by manfield** [comment]
I attach two images that show how the fix works:

**BEFORE**
(you may see only 5 carriers available)

before

**AFTER**
(all carriers are shown)

after

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Hi @manfield ,

I remember having another pull-request, which I just found: https://github.com/PrestaShop/PrestaShop/pull/12379

Thanks for creating this one which behaves like a reminder for me, but I'd like avoiding duplicates. I'm closing yours which was created later and will update the other one.

**Comment by manfield** [comment]
No prob at all

**Pull request closed without merging**
