### PR TITLE
Assign ID to password forgotten form

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | `develop` |
| Description? | Assign ID to password forgotten form |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @firstred 
Why do you need this id ? I just ask because it's not used after

**Comment by firstred** [comment]
To access the form with ease.

**Comment by xBorderie** [comment]
@aleeks It is not used by default, but it might be useful for a module wanted to customize the form, mightn't it?

**Comment by aleeks** [comment]
@xBorderie Yes, but some people may think it is usable in all themes and build a module from this ID, and this is not the case. 
This is what we had said @maximebiloe  ?!

**Comment by maximebiloe** [comment]
Yes, we can't impose the theme developers to use the same ids. If you want to add an easier way to access to the form, you can add a class prefixed by `js-`. If you do, you need to make the same on StarterTheme.

Thanks.

**Pull request closed without merging**
