### PR TITLE
Allow changing the position of products in a category in the catalog > product page

### LINKED ISSUE #14616: It is impossible to change position of products into a category in the catalog > product page (only the first time is OK)
**Describe the bug**
It is impossible to change the position of products into the catalog => product page.
After Drag & drop => Click on "Save & Refresh" button => The green alert "Products successfully sorted." is not displayed.
The new positions of products are not saved.
Only the first time is ok, but after some tests, this action is not possible
Checked with FireFox & Google Chrome.

Issue reported here: https://github.com/PrestaShop/PrestaShop/issues/11152#issuecomment-510818944

**To Reproduce**
1. Go to Catalog > Products
2. Click on Filter by categories and select a category ( Art category)
3. Click on Reorder button
4. Drag & drop some products
5. Click on "Save & Refresh" button
6. "Products successfully sorted." is not displayed & The new positions of products are not saved.

**Screenshots**
PS1.7.5.2: https://drive.google.com/file/d/1MD1EIi0yltRedcHbSEAL2ex2oC9Bb5ik/view
PS1.7.6.0: https://drive.google.com/file/d/1pbnjkFSTE7ebh6qX3Z2sEuZROAvkwEhL/view

**Additional information**
PrestaShop version: 1.7.5.2 / 1.7.6.0
PHP version: 7.0

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Use a different way to sort product in categories
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14616 
| How to test?  | Follow ticket instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14879)

### CODE REVIEW

**Comment by ABarailler** [comment]
Hello,
I have tested the commit e199ed4 on two projects and this is not working.
But I have tried to modify the SQL request and I found a way where the product's position updates well




		$firstPosition = min($positionsMatcher);
		$productsIds = implode(',', array_map('intval', array_keys($productList)));
                $updatePositions = 'UPDATE `' . _DB_PREFIX_ . 'category_product` cp
			INNER JOIN `' . _DB_PREFIX_ . 'product` p ON (cp.`id_product` = p.`id_product`)
			' . Shop::addSqlAssociation('product', 'p') . '
			INNER JOIN (
				SELECT id_product
				FROM `' . _DB_PREFIX_ . 'category_product` cp
				WHERE cp.`id_category` = ' . (int) $categoryId . ' AND cp.`id_product` IN (' . $productsIds . ')
				ORDER BY FIELD(cp.`id_product`, ' . $productsIds . ')
			)
			AS cp2 ON cp2.id_product = p.id_product
			SET cp.`position` = (SELECT @i := @i + 1),
				p.`date_upd` = "' . date('Y-m-d H:i:s') . '",
				product_shop.`date_upd` = "' . date('Y-m-d H:i:s') . '"
			WHERE cp.`id_category` = ' . (int) $categoryId . ' AND cp.`id_product` IN (' . $productsIds . ')';

		Db::getInstance()->query('SET @i := ' . (((int) $firstPosition) - 1));
		Db::getInstance()->query($updatePositions);`

It's not perfect but that works

**Comment by PierreRambaud** [comment]
@ABarailler Can you tell me what was the error?
You do
```sql
SELECT id_product
FROM `' . _DB_PREFIX_ . 'category_product` cp
WHERE cp.`id_category` = ' . (int) $categoryId . ' AND cp.`id_product` IN (' . $productsIds . ')
ORDER BY FIELD(cp.`id_product`, ' . $productsIds . ')
```

Which is already done by the:

```php
'INNER JOIN `' . _DB_PREFIX_ . 'product` p ON (cp.`id_product` = p.`id_product`) ' .
" . Shop::addSqlAssociation('product', 'p') . ' ' .
// AND
'ORDER BY FIELD(cp.`id_product`, ' . $productsIds . ')';

```

Same for 
```sql
AS cp2 ON cp2.id_product = p.id_product
```
Which is 
```php
'INNER JOIN `' . _DB_PREFIX_ . 'product` p ON (cp.`id_product` = p.`id_product`) ' .
```

**Comment by ABarailler** [comment]
No problem @PierreRambaud,
The initial problem is on ORDER BY, on SQL we can't add ORDER BY on multi table UPDATE.
The only solution I found is to replace the "order by" by a "inner join" that works the same way

It's probably not the best solution, but I can't find a better way right now.

**Comment by PierreRambaud** [comment]
@ABarailler Thanks for explanation. Your solution isn't working for me :sweat_smile: 
Are you able to test this one?
On request for postion, and one for multiple table (we don't care for order here).

**Comment by ABarailler** [comment]
OK on one project I found a case that my SQL doesn't work.
But I test your script on two projects and it works

Thanks for the fix @PierreRambaud

**Comment by PierreRambaud** [comment]
@ABarailler Thanks to you for helping us to make this project better :smile_cat:

**Review by matks — DISMISSED** [review]

**Comment by sarahdib** [comment]
@PierreRambaud  it's not working 
https://drive.google.com/file/d/1M6-uNKimxOfYqZ1Xl_xkmZ71wt-vF5NU/view

**Comment by sarahdib** [comment]
@PierreRambaud The problem is fixed if we use the icon in position column. The product is selected and we can change the position and saved and all changes is validated.

Since this PR correct the problem it's OK a New issue was created for the second issue : #15291

**Review by matks — APPROVED** [review]

**Comment by marlon8511** [comment]
Hello 
I still have the issue. The order by position in the parent category of the BO doesn't work in FO when "Show products from subcategories" is activated

I use the AdminProductDataUpdater.php file found here and doesn't work for me

PS:1.7.6.3
Faceted Search: 3.4.1

**Comment by marionf** [comment]
@marlon8511 
As you can see with the milestone, this issue has been fixed for the 1.7.7, so it's normal if it's not fixed in 1.7.6.3

Furthermore, there is still an issue about this not fixed: https://github.com/PrestaShop/PrestaShop/issues/14616#issuecomment-525757062
https://github.com/PrestaShop/PrestaShop/issues/15291

**Pull request merged**
