### PR TITLE
combine consecutive issets

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add combine_consecutive_issets to php-cs-fixer conf
| Type?         | new feature
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13992)

### CODE REVIEW

**Comment by MathiasReker** [comment]
@Quetzacoalt91 I have problems with all my PR's. Travis do not start. I just deleted my old repository and made a new clone of PrestaShop before I made this PR. I still face the same issue. I remember that you cloned some of my old PR's to fix this issue for the specific PR, but how do I solve this problem for the future? I changed my GitHub name from Mreker to MathiasReker a while ago. Could that be a reason for this weird issue?

**Comment by Quetzacoalt91** [comment]
I'll send a mail to the Travis support, you can't stay in this situation forever. :)

**Comment by MathiasReker** [comment]
> 
> 
> I'll send a mail to the Travis support, you can't stay in this situation forever. :)

Thank you :)

**Comment by Quetzacoalt91** [comment]
I got an update from Travis 

```
Thanks for reaching out and I'm sorry for the troubles.

Looking at this account (i.e.MathiasReker), it seems that it has never logged into Travis CI and this is why we are currently blocking their requests. Sorry for the inconvenience.

To confirm, do you think you could try to log into Travis CI at least once at https://travis-ci.org/ and push a new commit?

Please let us know the result and we would be happy to have another look if it's still not working.

Thanks in advance and have a great day!

-- Dominic.
```

**Comment by PierreRambaud** [comment]
Hey, I approve this change. But need the feedback from the rest of the team, and of course can you do a pull request on our php coding standard repository? (https://github.com/PrestaShop/php-coding-standards)
Thanks

**Review by PierreRambaud — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Hi @MathiasReker,

Because your fork was deleted, maintaining your PR will be now more difficult, and even impossible.
I created another PR from your changes in order to trigger Travis: https://github.com/PrestaShop/PrestaShop/pull/14134

**Comment by MathiasReker** [comment]
@Quetzacoalt91 Thank you. Everything with travis is fixed now. :)

**Comment by Quetzacoalt91** [comment]
Wohoo! I'm glad to hear that.

**Pull request closed without merging**
