### PR TITLE
Fix a problem when a voucher is added on checkout

### PR DESCRIPTION
**Pull request by AntoineMille**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix a problem when a voucher is added on checkout
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2364
| How to test?  | Add voucher on checkout

### CODE REVIEW

**Review by maximebiloe — APPROVED** [review]

**Comment by vincentbz** [comment]
Hi,

When I add the voucher into the order process, the discount amount is not shown

image



And when I add it before the order process but I remove it within, then the discount remains displayed, see "remise" under the price, whereas it's not applied

image


Thanks !

**Comment by AntoineMille** [comment]
Hi @vincentbz,

I think is an other problem and a new ticket no ?

Regards

**Comment by vincentbz** [comment]
ok !

**Comment by aleeks** [comment]
Thank you @AntoineMille

**Pull request merged**
