### PR TITLE
Remove deprecated UpdateProductStatusCommand (& Handler & Interface & service)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated UpdateProductStatusCommand (& Handler & Interface & service)
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5152967183
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks
* Removed class `PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductStatusHandler`
* Removed class `PrestaShop\PrestaShop\Core\Domain\Product\Command\UpdateProductStatusCommand`
* Removed class `PrestaShop\PrestaShop\Core\Domain\Product\CommandHandler\UpdateProductStatusHandlerInterface`
* Removed service `PrestaShop\PrestaShop\Adapter\Product\CommandHandler\UpdateProductStatusHandler`

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by boherm** [comment]
@Progi1984, no need QA on this I think with CI / Autotests green, so are you agree to merge now?

**Comment by Progi1984** [comment]
Ping @PrestaShop/qa-functional

**Comment by florine2623** [comment]
OK to merge this @Progi1984 and @boherm 
Thanks !

**Comment by Progi1984** [comment]
Thanks @florine2623 

Ping @PrestaShop/committers

**Pull request merged**
