### PR TITLE
[-] Security : Fixes PSCSX-4841 Usage of ECB mode

### PR DESCRIPTION
**Pull request by SDF-of-BC**
Use CBC mode on cookies instead for added security.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, @SDF-of-BC ! Our devteam will review it as soon as possible.

Team, the Forge ticket is here: http://forge.prestashop.com/browse/PSCSX-4841
The gist of it, [from Wikipedia](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_Codebook_.28ECB.29) (my emphasis): "The disadvantage of this method is that **identical plaintext blocks are encrypted into identical ciphertext blocks**; thus, it does not hide data patterns well. In some senses, it doesn't provide serious message confidentiality, and **it is not recommended for use in cryptographic protocols at all**".

The ticket's reporter points to [defuse's article](https://defuse.ca/secure-php-encryption.htm).

**Comment by SDF-of-BC** [comment]
My grasp on it. In ECB mode each block of data is encrypted separately, so it's possible to swap around the blocks to mess around with the cookie data, PS wouldn't know this had happened as the data would decrypt successfully.
With CBC the blocks are cryptographically chained together meaning that if they were re-ordered then decryption of the cookie would fail.

**Comment by jvoisin** [comment]
Encryption doesn't mean authentication : maybe this is the good time to check if the implementation doesn't expose malleability issues ;)

**Comment by xBorderie** [comment]
Reviewed by @rGaillard (thanks!)

Dev team: please cherry-pick this one on the `develop` branch!

**Comment by Shudrum** [comment]
:+1:

**Comment by xBorderie** [comment]
Cool!

**Pull request merged**
