### PR TITLE
Cleanup /tests directory

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | It moves tests (except for Selenium and E2E) to `tests-legacy` directory.
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/10733
| How to test?  | Travis should be green.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11464)

### CODE REVIEW

**Comment by sarjon** [comment]
@matks here's PR. :)

@mickaelandrieu @PierreRambaud your reviews would be nice as well.

Things left to do:
- [ ] Maybe update legacy tests namespace to `Tests` => `LegacyTests`?
- [ ] should `check_e2e.sh` be left under original `tests/` dir?
- [ ] Move valid Unit tests back to `tests` dir or do it in separate PR?

**Comment by LouiseBonnard** [comment]
Hi there, can I remove the 'Waiting for Wording' label?

**Comment by PierreRambaud** [comment]
@LouiseBonnard Yes you can.

**Comment by sarjon** [comment]
seems that unit tests are okay, but e2e are not. :/ any ideas?

**Comment by matks** [comment]
@sarjon I think `check_e2e` should stay with E2E tests. It's not perfect but we can deal with 1 file "not in the right place" 😄 

E2E tests error seem to happen at `The blocktopmenu 1) should be shown on the home page` so maybe it's because some test fixtures modules was moved and is now not installed anymore on e2e folder. I'm gonna have a look.

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thanks @sarjon this is a great step for Prestashop automatic testing 😄

**Pull request merged**
