### PR TITLE
Fixed save in Symfony Form Merchandise Return Options

### LINKED ISSUE #23606: BO - Merchandise Returns - Cannot save Merchandise return (RMA) options
#### Describe the bug

In the BO > Merchandise Returns migrated page, In the `Merchandise return (RMA) options`, we cannot save any option, it is not possible to enable Merchandise return and we can't change the `Time limit of validity` and `Return prefix` values

#### Steps to Reproduce

1. Go to BO > admin-dev/index.php/sell/customer-service/merchandise-return/ page
2. In the `Merchandise return (RMA) options` section
3. Try to enable returns
4. Set the `Time limit of validity` and `Return prefix` values
5. Save
6. A green alert is well displayed
7. Go to BO > admin-dev/index.php/sell/customer-service/merchandise-return/ page 
8. See error: No option is saved
https://drive.google.com/file/d/1WnWmDEi8HBU7lcgr_7Vo_qDaXRr10rcB/view?usp=sharing

It is ok with the PS1772 migrated page

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed save in Symfony Form Merchandise Return Options
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23606
| How to test?      | Cf. #23606

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25558)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
Do you think we can have a behat test on this ?

**Review by matks — DISMISSED** [review]

**Comment by Progi1984** [comment]
@matthieu-rolland It's a FormHandler, so I add a unit test on it.

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Should it be backported on the 1.7.8.x too?

**Comment by matks** [comment]
> Should it be backported on the 1.7.8.x too?

This Symfony page is hidden in 1.7.8 I believe, so no need to backport

**Review by sowbiba — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1zOh9bqcFR049OVgWYz2H1wxGxxTaJ3aJ/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith

**Pull request merged**
