### PR TITLE
[*] Update AdminCategoriesController.php

### PR DESCRIPTION
**Pull request by Nobodaddy**
Dropped type "textarea". I'd suggest that size limit for meta name and meta desciption should be the same like for products.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

This would revert https://github.com/PrestaShop/PrestaShop/pull/2038

Regards

**Comment by Nobodaddy** [comment]
Yep, because #2038 makes no sense.

**Comment by gRoussac** [comment]
Hi,

Welle sorry but this makes sense someway.

I opened a PR follow up yours so.

https://github.com/PrestaShop/PrestaShop/pull/3530/files

Reagrds

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
Closing this one since #4426 changes the behavior of this block of code, and it seems to work pretty well this way. Thank you for your contribution!

**Pull request closed without merging**
