### PR TITLE
[-] BO: Fix filter by category change not working after other actions. #PSCSX-5813

### PR DESCRIPTION
**Pull request by xGouley**
// Remake of the PR https://github.com/PrestaShop/PrestaShop/pull/3367 on develop.

### CODE REVIEW

**Comment by xGouley** [comment]
To be tested on develop before to merge.

**Comment by xBorderie** [comment]
@vincentbz Could please give your opinion about this. Forge ticket is http://forge.prestashop.com/browse/PSCSX-5813 Thanks!

**Comment by xBorderie** [comment]
Tested by @vTerenti (see internal log): ok.

**Comment by vincentbz** [comment]
A intégrer dans la 1.6.1.5, merci !

**Pull request merged**
