### PR TITLE
Adding a test for unsigned integer values

### PR DESCRIPTION
**Pull request by ghost**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | There is an issue where the isUnsignedInt function of the Validate class is not returning true when it should, for all numbers between 2147483647 and 4294967295 |
| Type? | bug fix |
| Category? | TE |
| BC breaks? | no |
| Deprecations? | yes |
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL. |
| How to test? | Testing the Validate::isUnsignedInt function for a value of 4294967290 will return false when it should return true |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello,

You made your PR on `develop` branch but you filled `1.6.1.x` in the table. So, where did you want to make the PR?

Regards

**Comment by yosskom** [comment]
@maximebiloe My apologies. As far as I can tell, this applies to at least 1.6.1.x and up.

**Comment by maximebiloe** [comment]
No problem.
Would you mind remake your PR for `1.6.1.x`, so? 
I can't just change the targeted branch because there will be thousands of commit

**Comment by yosskom** [comment]
I'm going to remake it into 1.6.1.x

**Pull request closed without merging**
