### PR TITLE
[-] Class: Category / Add moved_category as hook params when update p…

### PR DESCRIPTION
**Pull request by prestamodule**
…ositions

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

thank you for your contribution, please use develop branch for minor improvement.

Best regards

**Comment by gRoussac** [comment]
Hi,

Sorry but everywhere else it is category, why is it here specific ?

Regards

**Comment by gRoussac** [comment]
:up: ?

**Comment by gRoussac** [comment]
Please ?

**Comment by gRoussac** [comment]
https://github.com/PrestaShop/PrestaShop/pull/4111

**Pull request closed without merging**
