### PR TITLE
Fix 11130: Problems in the Back-Office on the bottom toolbar of product page.

### LINKED ISSUE #11130: Problems in the admin side on the bottom toolbar of product pages under 1039px
Hi
if you go in a product page in the back office
try to resize the borwser's width under 1039px you will see the the bottom toolbar will not be full size
it should have ad width of 100% because the lateral menu is not visible

**Screenshots**

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7

bye

### PR DESCRIPTION
**Pull request by dineshbadrukhiya**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Problems in the Back-Office on the bottom toolbar of product page.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |  Fixes #11130
| How to test?  |

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11138)

### CODE REVIEW

**Comment by dineshbadrukhiya** [comment]
@Quetzacoalt91 wdyt?

**Comment by Quetzacoalt91** [comment]
Unfortunately, your changes will be lost as soon as the assets will be regenerated.

`admin-dev/themes/new-theme/public/theme.css` is the compiled file of the folder ` admin-dev/themes/new-theme/scss/*`. You must update the equivalent rule in the non-compiled file in order to keep it in the long time.

And what about the file `install-dev/fixtures/fashion/langs/bn/data/product.xml`, is it related to the fix?

**Comment by dineshbadrukhiya** [comment]
Hello @Quetzacoalt91 
I have updated non-compiled file of the folder `admin-dev/themes/new-theme/scss/`.

And `install-dev/fixtures/fashion/langs/bn/data/product.xml`, is not related to the fix. That commit is for my another pull request, But by mistake it's showing here and I don't know how to remove it from here. Can you please look on it?

**Comment by dbadrukhiya** [comment]
Wdyt? @Quetzacoalt91

**Comment by dineshbadrukhiya** [comment]
@Quetzacoalt91 is it ok?

**Comment by Quetzacoalt91** [comment]
Let's ask a review from @eternoendless first, who is the most adequate person on this topic. :)

**Comment by dineshbadrukhiya** [comment]
@eternoendless  wdyt?

**Comment by dineshbadrukhiya** [comment]
@eternoendless wdyt?

**Comment by PierreRambaud** [comment]
ping @eternoendless

**Comment by Quetzacoalt91** [comment]
Hi @dineshbadrukhiya,

By compiling the assets for you in order to go on the process, it appears the issue is not fixed and the footer still does not use the whole space. Can you please check again?

**Comment by dineshbadrukhiya** [comment]
> Hi @dineshbadrukhiya,
> 
> By compiling the assets for you in order to go on the process, it appears the issue is not fixed and the footer still does not use the whole space. Can you please check again?

I have opened new PR #12904 so can you please check. I think there is something going wrong while compiling assets.

**Comment by Quetzacoalt91** [comment]
Hi there,

In order to avoid duplicates, I close this one and will update #12931

**Pull request closed without merging**
