### PR TITLE
Remove Support for 1.7.7.x

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove Support for 1.7.7.x
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26631)

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Shouldn't be done on the develop branch only as it concerns `.github` directory :thinking:

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984

**Review by tegbessou — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PierreRambaud It will be merged in develop next week.

**Comment by PierreRambaud** [comment]
> @PierreRambaud It will be merged in develop next week.

What I mean is, there is no reason to update this branch as GitHub uses the main branch only. The fix needs to be done only on the develop branch.

**Comment by Progi1984** [comment]
@PierreRambaud It's done (Ping @jolelievre & @tegbessou)

**Review by atomiix — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @Progi1984

**Pull request merged**
