### PR TITLE
Fix fixed height of TinyMce fields

### LINKED ISSUE #10825: Height of wysiwyg editor on product page
**Describe the bug**
Edit a product and enter a long description

**To Reproduce**
1. Go to Catalog > Products > Edit a product
2. Enter a long description & save
3. Refresh the page
4. You don't see all your text

**Screenshots**

capture d ecran_373

It was good on 1.7.4.2

capture d ecran_374

**Additionnal information**
PrestaShop version: 1.7.5.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Partially reverts #10170 (ping @CaptainYouz ). Fixes the fixed height of the different text area on the product page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | Fixes #10825
| How to test?  | See issue, you need to write a lot of content in a product description.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10861)

### CODE REVIEW

**Comment by CaptainYouz** [comment]
Hi @Quetzacoalt91 
Does this change reproduce the precedent behavior describe here https://github.com/PrestaShop/PrestaShop/pull/10170 ? If yes, better to set `min-height` value instead of getting rid of the height.

**Comment by Quetzacoalt91** [comment]
Which one are you thinking about?  The only one related to this input is 

```
    Increase dimensions of the text editor.
```

**Comment by CaptainYouz** [comment]
@Quetzacoalt91 yep this one :)

**Comment by Quetzacoalt91** [comment]
Well, the issue I'm trying to fix is this input being too small, I'm following the changes requested.

**Comment by Quetzacoalt91** [comment]
PR updated, we now use `min-height` instead of `height !important`

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Rebased

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
