### PR TITLE
[standby] Filters in catalog page

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This script tests the sort and filters in the catalog page
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | To test this scenario, you have to run this script: TEST_PATH=full/02_product/08_sort_product.js npm run specific-test -- --URL=URLFrontOffice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9249)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
```
$ path=full/02_product/08_sort_product.js npm run specific-test -- --URL=localhost/PrestaShop

> END2END@1.0.0 specific-test /home/thomas/Documents/github/PrestaShop/tests/E2E
> node_modules/mocha/bin/mocha test/campaigns/$TEST_PATH "--URL=localhost/PrestaShop"


  0 passing (1ms)
```

Did I miss something?

**Comment by fatmaBouchekoua** [comment]
Hello @Quetzacoalt91 ,
We don't use `path` anymore, that was replaced by `TEST_PATH`. 
I will edit all the descriptions. 
Thank you for reporting!

**Comment by mbadrani** [comment]
@fatmaBouchekoua @fouratachour This PR need to be rebased

**Comment by fatmaBouchekoua** [comment]
@mbadrani this PR is in standby because I can't validate the scenario (there's is a bug). I will rebase it when this issue https://github.com/PrestaShop/PrestaShop/issues/10168 will be resolved.

**Pull request closed without merging**
