### PR TITLE
Removed dead code relative to Addons

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed dead code relative to Addons
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Relative to #24639
| How to test?      | * In Carriers & Payments list, removed links to Addons Prestashop 

**BC Breaks:**
* Removed template `admin-dev/themes/default/template/controllers/carriers/helpers/list/list_footer.tpl`
* Removed template `admin-dev/themes/default/template/helpers/modules_list/list.tpl`
* Removed template `admin-dev/themes/default/template/helpers/modules_list/modal.tpl`
* Removed template `src/PrestaShopBundle/Resources/views/Admin/Common/recommendedModules.html.twig`
* Removed method `renderModulesList` in `AdminController`
* Removed method `renderModulesList` in `Helper`
* Removed method `recommendedModulesAction` in `\PrestaShopBundle\Controller\Admin\CommonController`
* Removed class `\PrestaShopBundle\Service\DataProvider\Admin\RecommendedModules`
* Removed route `admin_common_recommended_modules`
* Removed service `prestashop.data_provider.modules.recommended`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27710)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
Remove `/home/flefevre/projects/prestashop/src/PrestaShopBundle/Service/DataProvider/Admin/RecommendedModules.php`

**Comment by Progi1984** [comment]
@PierreRambaud & @atomiix Removed some another dead code (in CommonController and the tree of dependencies).

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Thanks for the PR !
LGTM. I haven't found anything wrong in Carrier and Payment. I also ran the auto tests for Carriers without any error.
QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
