### PR TITLE
Add rtl_suffix in stylesheet link

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing rtl_suffix into stylesheets links added with template.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | n/d
| Sponsor company   | @Wepika

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Hello @PrestaEdit can you confirm that without this `rtl_suffix` part, then the following scenario does happen:

1. Open BO
2. Download an Arabic language (or any other RTL language)
3. Set your BO profile settings: use this RTL language
4. All the BO web interface is transformed to RTL
5. But on the Product Page V2, the RTL behavior is not applied

?

**Review by matthieu-rolland — APPROVED** [review]
lgtm, but removing the qa label until @matks's question is answered

**Comment by PrestaEdit** [comment]
Hi,

To be honest, it's not changing something there, but it could if needed sometimes.

**Comment by kpodemski** [comment]
@PrestaEdit so this PR doesn't change anything? :D

**Comment by PrestaEdit** [comment]
It's prevent any potential issues but... surely.

Close it.

**Comment by kpodemski** [comment]
@PrestaEdit 

Help me understand it. If we have RTL language, does it add rtl suffix? will it try to load `product_rtl`?

**Comment by matks** [comment]
Hello guys I might be wrong but I think thanks to @NeOMakinG work, the backoffice theme is now RTL-compliant natively: the CSS automatically handles RTL displays. The CSS file with `rtl_suffix` and the system that generates/enables/disables it was left for backward compatibility.

The CSS file with `rtl_suffix` and the system - once again if I am not wrong, I'm saying this from memories - were left to make sure that, if somebody created his own backoffice theme that did rely on this system well it was still available.

**Pull request closed without merging**
