### PR TITLE
Add default config value for backorder status

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Default configuration value for https://github.com/PrestaShop/PrestaShop/pull/29753. Does not need QA.
| Type?             | new feature
| Category?         | CO
| BC breaks?        | -
| Deprecations?     | -
| Fixed ticket?     | -
| Related PRs       | -
| How to test?      | To test : install a new shop and check the value in configuration table, also check if the switch button is to off in Shop Parameters > Order settings.
| Possible impacts? | -

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]
👍

**Comment by nicosomb** [comment]
@PrestaShop/qa-team I leave you the choice to test or not this PR

**Comment by florine2623** [comment]
As discussed with @boubkerbribri ,

I think there is some ways to test this that can be added to the `how to test` :
- Try CLI install without adding `PS_ENABLE_BACKORDER_STATUS` (see that default Param is true)
- Try Docker install too (With PS_Install_auto = true) even if it uses also CLI
- Try the others ways too (adding param on docker and CLI)

@Hlavtox what do you think ? Could you update your description ? ^^

**Comment by Hlavtox** [comment]
Default value changed to false as per discussion on slack with @MatShir.

Needs reapproval please 👍 @matks @nicosomb 

@florine2623 I don't use CLI or docker sorry, I would just test a simple install if you want to test anything. I don't want to spend more time on one configuration value... 😉

**Review by nicosomb — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
To test : install a new shop and check the value in `configuration` table, also check if the switch button is to off in Shop Parameters > Order settings.

**Review by sallemiines — COMMENTED** [review]
Hello @Hlavtox 

Thanks for the PR ! it's LGTM QA :heavy_check_mark: , you can see the attached screenShots 

Order-settings-•-developpr


Orders-Order-YPMCKFGVZ-from-John-DOE-•-developpr

Thank you ! :rocket:

**Comment by ghost** [comment]
@PrestaShop/prestashop-core-developers need one approve from maintener

**Review by atomiix — APPROVED** [review]
LGTM. Just wondering if we should add the default value in the DB when upgrading from a previous version?

**Comment by Hlavtox** [comment]
@atomiix ✅ https://github.com/PrestaShop/autoupgrade/pull/526

**Comment by ghost** [comment]
Thank @sallemiines && @Hlavtox

**Pull request merged**
