### PR TITLE
Fix error while compiling theme assets

### LINKED ISSUE #26248: PS 1.7.8.0 Error compiling classic theme assets with Windows 10
#### Describe the bug
When I try to compile the assets of the "classic" theme, the system gives an error.

If I run the command: 
**npm run build**

I get the following error:
**"NODE_ENV" non è riconosciuto come comando interno o esterno**
I solved it by replacing in the package.json file
`"build": "NODE_ENV=production webpack --progress --colors --debug --display-chunks",`
with
`"build": "webpack --progress --colors --debug --display-chunks --mode=production",`

But I still have problems, in fact executing the command:
**npm run build**
I get the following error:
**Can't resolve '. \ Tether.js' ...**

I attach the screenshot with the complete error

P.S.
I tried with ubuntu and it works

**Screenshots**
Screenshot

#### Additional information
* PrestaShop version: 1.7.8.0
* PHP: all
* SO: Windows 10

### PR DESCRIPTION
**Pull request by templatin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Error compiling theme assets in PS 1.7.8.0.
| Type?             | bug fix 
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26248
| How to test?      | Please check above ticket.
| Possible impacts? | Theme assets compiling.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26297)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/product-team Hi, can we add this fix to `1.7.8.x` or do you prefer to add it to the `develop` branch ?

**Comment by NeOMakinG** [comment]
> @PrestaShop/product-team Hi, can we add this fix to `1.7.8.x` or do you prefer to add it to the `develop` branch ?

It's blocking building assets on windows on this version, we should add it to the version patch (from my point of view)

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
> > @PrestaShop/product-team Hi, can we add this fix to `1.7.8.x` or do you prefer to add it to the `develop` branch ?
> 
> It's blocking building assets on windows on this version, we should add it to the version patch (from my point of view)

It's not necessary as it targets only the development process and not the production environement.

**Comment by marionf** [comment]
It's not a regression so I would say develop, unless if it's blocking some of you for developments on 1.7.8.x

**Review by matthieu-rolland — CHANGES_REQUESTED** [review]
thank you for your contribution @templatin !  

as stated by @marionf this PR must be based on develop and not 1.7.8.x ;)

**Comment by templatin** [comment]
Okay, I got that but don't know how to target this PR to "develop" branch :(
I can do it by submitting a new PR based on "develop" and then targeting it.

But I'm interested in knowing how to do in this PR itself.
Since my "templatin-webpack-1" branch is based on "1.7.8.x" so I think clicking the "Edit" button (near PR title) and changing the base won't be a proper method (or might not work even).

**Comment by NeOMakinG** [comment]
> Okay, I got that but don't know how to target this PR to "develop" branch :( I can do it by submitting a new PR based on "develop" and then targeting it.
> 
> But I'm interested in knowing how to do in this PR itself. Since my "templatin-webpack-1" branch is based on "1.7.8.x" so I think clicking the "Edit" button (near PR title) and changing the base won't be a proper method (or might not work even).

You've 2 way =>

```
git remote add upstream git@github.com:PrestaShop/PrestaShop.git
git checkout develop
git pull upstream develop
git checkout templatin-webpack 1
git rebase develop
```

This can be hard regarding the difference between 1.7.8.x and develop, it may lead to a to difficult task.

The other way (to me), is to reset the current branch and redo the change

```
git reset --hard develop
redo changes, redo commit
```

and then push

This works on a PR without a lot of changes, but you could also cherry-pick your commits so you don't have to redo changes

**Pull request closed without merging**
