### PR TITLE
Cast properties of specific price to number

### PR DESCRIPTION
**Pull request by maidmaid**
cf #5017 

Hi !

In some commercial template, there is a round on specific price in js, like : 

``` js
combination.specific_price.price.toFixed(2)
```

but `price` property is currently a string and schould be casted to float. This thrown a fatal js error and next it's not possible to change correclty prices by combination.

image

To fix it, I propose to cast `price` and other properties of specific price to number.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/5023)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for remaking your PR on the `1.6.1.x` branch, @maidmaid !
The Core devs will soon review it.

**Comment by maidmaid** [comment]
Any news?

**Comment by mickaelandrieu** [comment]
Hello @maidmaid,

as `1.6.1.x` branch is close to end of maintenance period I encourage you to migrate to PrestaShop 1.7.

For now, all our efforts are on `1.7.3.2` and `1.7.4.0`, thanks for your understanding.

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
