### PR TITLE
Boom 468 combinations improvements

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Make the selection of  default combination of a product easier and see the impact on price by combination directly by adding the final price in related forms. |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-468 |
| How to test? | combinations_part |
### How to test  ?

In the combinations section of a product, you can now select the default combination using a radio button in the last column of the table (with the edition an deletion features)

The impact on weight has been removed, in favor of the final price, dynamicaly impacted by the impact on price - now editable - for each combination.

### CODE REVIEW

**Comment by vTerenti** [comment]
QA NOK

Taille de L'input impact one price trop réduite, on ne voit pas ce que l'on écrit dans le champs.
+ 
On peut sélectionner tous les boutons radio et on ne peut les sélectionner...

**Comment by mickaelandrieu** [comment]
Hi @vTerenti,

your comments have been adressed, thank you for report :)

Mickaël

**Comment by vTerenti** [comment]
Thanks Mickael!

Seems to be good for me!

QA OK!

**Comment by Shudrum** [comment]
Merged as the tests are not linked to your modifications.

**Pull request merged**
