### PR TITLE
Fix admin email translations

### PR DESCRIPTION
**Pull request by gskema**
This is a major bug, I don't why anyone hasn't fixed this yet.

What doesn't work:
- `cleanMailContent` butchers the HTML before outputting it to admin forms: only the contents of the `<body>` is left;
- TinyMCE doesn't allow full HTML, it would butcher the full HTML too.
- Submitted translations are butchered, we lost `<head>` tag (which contains `<style>` block) and the `<body style="*"` attribute, which contains email width.
- When we are processing the email, we wrap the email with HTML document tags again by calling `getMailPattern`.
- Just before putting the HTML to file, the HTML is butchered again by `Tools::purifyHTML`.

Same description can be found here:
- https://gist.github.com/gskema/d3f62431965dbb5c8cdb04da97c9dc77

What this PR fixes:
- HTML isn't butchered anymore before outputting it to admin form. Removed functions in `cleanMailContent`.
- TinyMCE doesn't butcher the full HTML that we managed to output because it now includes `fullpage` plugin.
- When we process the submitted HTML (now full HTML document), we no longer need `getMailPattern` (deprecated).
- We only need to insert the `title` text since it's entered using a separate field. Tip: you could edit these fields by adding `fullpage` plugin to TinyMCE toolbar!
- When we are ready to save with `file_put_contents`, we don't use `Tools::purifyHTML` -> our HTML doesn't get butchered. But you will say that we need to escape the input! Well, we already check if the HTML is secure with `Validate::isCleanHTML`.

**Does this affect 1.7** ? Yes

**Should you include this to 1.7 and 1.6.1.5** ? Yes, absolutely definitely please

Someone didn't believe that full HTML was possible with TinyMCE, see the highlighted line:

https://github.com/PrestaShop/PrestaShop/pull/5333/files#diff-b06d30a34002e19b65a408bbb0d4d82bL2482

### CODE REVIEW

**Comment by Shudrum** [comment]
Sorry, we cannot merge all the pull request on a single patch version. It is the best way to make the 1.6 less stable.

**Comment by gskema** [comment]
I'm just frustrated that is such an obvious bug, which makes admin email translations unusable (it has been like this for years now?). I'd rather have something working with bugs than having something unusable at all. I'm hoping that you will at least merge this into 1.7.

**Comment by maximebiloe** [comment]
Thank you @gskema!

**Comment by aleeks** [comment]
Hello @gskema , this PR weren't meant to be merged ?!!

**Comment by gskema** [comment]
@aleeks It's all good. Enjoy your email templates (finally)!

**Comment by xBorderie** [comment]
Thank you for this PR, Gytis!

**Comment by kpodemski** [comment]
Only 6+ months, good job, i can feel this open source spirit in the air :)

**Comment by xBorderie** [comment]
We try our best!

**Pull request merged**
