### PR TITLE
Add some hooks to allow invoice customizations

### PR DESCRIPTION
**Pull request by guestisp**
These hooks allows a better invoice customizations without using php overrides.
`actionSetInvoice` is called when setting a new invoice for an order. Modules would be able to replace the `invoice_number` bound to an order and take some actions (for example, by replacing the invoice progressive number based on some criteria, like new year reset and so on)
`actionInvoiceNumberFormatted` is called when displaying the invoice number. With this hook will be possible to customize the formatted number. (in example: `INVOICE-0000123/2015`)

### CODE REVIEW

**Comment by PhpMadman** [comment]
That's awesome!
However, is_numeric is not ideal to use. Some people may wish to use the order reference as the invoice number. Maybe a `is_string() || is_numeric()` is better?

And also if statements with just one line, don't use {} in prestashop's norms.

**Comment by guestisp** [comment]
Thank you for your advice, i'll fix asap.

Just to clarify: i'm using `is_numeric` because `Hook::exec` returns an empty string when there isn't any output coming from the module.
Just checking for `is_string` will also skip default invoice generation even if there isn't active module.

For example, something like this, in a module, will return an empty string as output:
`
function hookActionSetInvoice($params) {
}
`

**Comment by guestisp** [comment]
Additionally, `invoice_number` in an `INT(10)` in DB, I can't accept a string coming from module.

**Comment by PhpMadman** [comment]
ah, yes. completely forgot about the database.

**Comment by guestisp** [comment]
I've removed the unneeded brackets

**Comment by guestisp** [comment]
Any chance to get this merged? I'll continue adding more hooks to allow better modules development.

How can I push a db change to be included? I would like to add support for zip codes bound to shipping zones.

**Comment by PhpMadman** [comment]
Here is an example. https://github.com/PrestaShop/PrestaShop/pull/2096/files

You need to alter the installer install-dev/data/db_structure.sql
And also add support for it in upgrade, browse the install-dev/upgrade/sql and pick the highest number on the sql file.
In my example install-dev/upgrade/sql/1.6.0.11.sql

And in addition it might be required to change a xml file.
I had to alter the install-dev/data/xml/order_state.xml to add support for the install for my two new checkboxes.

Hope this helps to get an idea to what is required

**Comment by guestisp** [comment]
Thank you so much. So I have to create (or append) to the next version sql file, (actually, 1.6.0.13.sql)

**Comment by guestisp** [comment]
Can you merge this? We have to create an invoice module and without these hooks the only way is to override PHP

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Regards

**Comment by guestisp** [comment]
Thank you. you made happy all italian customers.  
No more overrides for sequential numbering with reset each year.

**Pull request closed without merging**
