### PR TITLE
Display transporter block in RTL

### PR DESCRIPTION
**Pull request by molka**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | rtl
| Description?  | The general settings block on transporter page is missing
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Go to transporter page, you can see that the general settings block is displayed

### CODE REVIEW

**Review by maximebiloe — DISMISSED** [review]

**Comment by maximebiloe** [comment]
Hello @molka,

Thanks for this.
Could you rebase it to solve the conflicts, please?
@marionf could you have a look, please?

Regards

**Comment by molka** [comment]
Hello @maximebiloe ,

Sorry for the late answer.
Still need rebase?

Regards

**Comment by maximebiloe** [comment]
Hello @molka,

No problem.
Yes it would be great if you can rebase.

Regards

**Comment by molka** [comment]
Hello @maximebiloe,

Done.

Thanks,
Molka

**Review by maximebiloe — APPROVED** [review]

**Comment by maximebiloe** [comment]
Thank you @molka

**Pull request merged**
