### PR TITLE
[*] Project : Full PHPDoc comments for AdminController class

### PR DESCRIPTION
**Pull request by gskema**
Fully filled in PHPDoc comments for class members and methods. The benefit of this is fully working code autocomplete in IDEs and type suggestions. Most notable change: specifing $this->object as ObjectModel, IDEs will understand $this->object->save() and etc.

Downsides: some member variables were grouped together for better visibility/readability, now they are not.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Regards

**Comment by gskema** [comment]
Hello, is this PHPDoc refactoring acceptable to PS team? I would like to do some other classes as well.

**Comment by gRoussac** [comment]
Hi,

@Shudrum has issues with "-" in params, he will answer you about it asap.

Regards

**Comment by Shudrum** [comment]
Hi gskema,

Thank your for your contribution, great initiative ! :+1: 

I've just pushed some corrections: https://github.com/PrestaShop/PrestaShop/commit/eef330478448181a88970b76237367e16248b947 and this is why:

- phpDocumentor have no separator, so every '-' you have used are visible on titles.

For example:

instead of :


- For methods or variables with description, it is better to enter the title on the first line, use two line returns and enter the description, like this var:

```php
    /**
     * Actions to execute on multiple selections.
     *
	 * Usage:
	 *
	 * array(
	 * 		'actionName' => array(
	 * 			'text' => $this->l('Message displayed on the submit button (mandatory)'),
	 * 			'confirm' => $this->l('If set, this confirmation message will pop-up (optional)')),
	 * 		'anotherAction' => array(...)
	 * );
	 *
	 * If your action is named 'actionName', you need to have a method named bulkactionName() that will be executed when the button is clicked.
	 *
	 * @var array
	 */
	protected $bulk_actions;
```

Thank you again !

**Comment by gskema** [comment]
@Shudrum 

Hello, I do understand the issue of "-", I will try to omit them in the commits (I used them because the docs were more readable in IDEs, but I won't add them anymore).

About the second issue, there are many one line PHPDocs for class members like `/** @var $table Associated table name*/` - shall we just keep it like that? Using multiple line would add a lot of line to the code.

**Comment by Shudrum** [comment]
Of course you can keep it like that !

My example is just for readability of vars with title **and** description. Just one on this controller. All others stay on one line as you've done .

**Comment by Shudrum** [comment]
And if you want to do some other classes, do not hesitate !

Thank you !

**Comment by gskema** [comment]
Sure, I was thinking of doing Controller or FrontController next. It took me 1-2 hours yesterday to fill in AdminController.

**Comment by gRoussac** [comment]
:+1:

**Comment by Shudrum** [comment]
:+1:

**Comment by kpodemski** [comment]
kudos @gskema :+1:

**Pull request merged**
