### PR TITLE
Fix BO Product attributes MultiShop issue

### LINKED ISSUE #19999: BO Product attributes MultiShop issue
#### Describe the bug

Product attributes MultiShop issue

#### Expected behavior

The attributes should only be displayed in the correct shop

#### Steps to Reproduce

1. Make sure you are using multiShop
2. Create two attributes : Attribute1 associated to shop1 and Attribute2 associated to shop2
3. Go Shop1 > BO > Product > (Select a product with combinations)
4. See error ... You have Attribute2 in Shop1

**Screenshots**
image

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: develop
* PHP version: N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Product attributes MultiShop issue. The attributes should only be displayed in the correct shop
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19999.
| How to test?  | See #19999

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20000)

### CODE REVIEW

**Comment by Progi1984** [comment]
:tada: Congrats : You have the #20000 :tada:

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
@PululuK as said in the issue, we're waiting for pm feedback before approving this PR

**Comment by marionf** [comment]
Hello @PululuK 

This is the behavior to fix the issue:
1.When you edit a product and select shop1 as context, you should see only the attributes associated to shop1 in the right column
2.When you edit a product and select shop2 as context, you should see only the attributes associated to shop2 in the right column
3.When you edit a product and select all shops as context, you should see the attributes associated to shop1 and shop2 in the right column

I just tested your PR, point 1 and 2 are ok :heavy_check_mark:
However point 3 seems not ok: I see only the attributes of shop1 in all shops context

Could you fix that ?

By the way, it seems we have two other PR candidating to fix this issue:
https://github.com/PrestaShop/PrestaShop/pull/13217
https://github.com/PrestaShop/PrestaShop/pull/19969

**Comment by matks** [comment]
Hi @PululuK ,

It looks like this PR is not moving anymore. As mentioned in our [Maintainer Guide](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests), "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

I close this pull request as it seems stale and you might dont want to continue on it. If however you want to continue it, you can re-open 😉 .

Thank you!

**Pull request closed without merging**
