### PR TITLE
Allow product_option_values image

### PR DESCRIPTION
**Pull request by FrancMunoz**
Allow CRUD operations over product_option_values images.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow CRUD operations over product_option_values images.
| Type?         | new feature
| Category?     | WS
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | http://site.com/api/images/product_option_values

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8303)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for remaking your PR!

**Comment by FrancMunoz** [comment]
I guess I did it right this time! Thank you!

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[classes/webservice/WebserviceSpecificManagementImages.php, line 634 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8303#-KyKTknYj7Ry_k8PmGv0:-KyKTknYj7Ry_k8PmGv1:bcua5zx) ([raw file](https://github.com/prestashop/prestashop/blob/7a49d0ec0f354f4a597599963c0387fe00c681a3/classes/webservice/WebserviceSpecificManagementImages.php#L634)):*
> ```PHP
>     {
>         // Get available image sizes for the current image type
>         if ($this->imageType=='product_option_values') {      	
> ```

- Please add spaces around comparison operators.
- Please use strict comparison (`===`) unless you have a good reason not to use it.
- Care about trailing white spaces (or tabulations). You can configure your IDE to automatically strip them (including for blank lines).

---

*[classes/webservice/WebserviceSpecificManagementImages.php, line 635 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8303#-KyKUYHiGz4Nlz1LnBtx:-KyKUYHjX_6NIwXj2OGR:b92jddc) ([raw file](https://github.com/prestashop/prestashop/blob/7a49d0ec0f354f4a597599963c0387fe00c681a3/classes/webservice/WebserviceSpecificManagementImages.php#L635)):*
> ```PHP
>         // Get available image sizes for the current image type
>         if ($this->imageType=='product_option_values') {      	
>             $normal_image_sizes = array();
> ```

When creating a new variable, please name it using the camelCase style (`$normalImageSizes`).

---

*[classes/webservice/WebserviceSpecificManagementImages.php, line 636 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8303#-KyKU8VSyTC1uRpR-Tct:-KyKU8VSyTC1uRpR-Tcu:b-6hohx5) ([raw file](https://github.com/prestashop/prestashop/blob/7a49d0ec0f354f4a597599963c0387fe00c681a3/classes/webservice/WebserviceSpecificManagementImages.php#L636)):*
> ```PHP
>         if ($this->imageType=='product_option_values') {      	
>             $normal_image_sizes = array();
>         } else {
> ```

To avoid the `else` part, I suggest initializing `$normal_image_sizes` as an empty array, then fill it if image type is not 'product_option_values'.

---

*[classes/webservice/WebserviceSpecificManagementImages.php, line 638 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8303#-KyKT4YcUvbq8Ev_NV-e:-KyKT4YcUvbq8Ev_NV-f:b-s4e51z) ([raw file](https://github.com/prestashop/prestashop/blob/7a49d0ec0f354f4a597599963c0387fe00c681a3/classes/webservice/WebserviceSpecificManagementImages.php#L638)):*
> ```PHP
>         } else {
>             $normal_image_sizes = ImageType::getImagesTypes($this->imageType);
>         }        
> ```

Care about trailing white spaces.
You can configure your IDE to automatically strip them (including for blank lines).

---

*[classes/webservice/WebserviceSpecificManagementImages.php, line 808 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8303#-KyKSzfgaOpjLFc54kFA:-KyKSzfgaOpjLFc54kFB:b-8g0uth) ([raw file](https://github.com/prestashop/prestashop/blob/7a49d0ec0f354f4a597599963c0387fe00c681a3/classes/webservice/WebserviceSpecificManagementImages.php#L808)):*
> ```PHP
>                     return $image->delete();
>                 } elseif ($filename_exists) {
>                     if (in_array($this->imageType, array('categories', 'manufacturers', 'suppliers', 'stores', 'product_option_values'))) {
> ```

Line is too long. Please break it in multiple lines, following PSR standards (focus only on the lines you edited, ignore the others).

---

*[classes/webservice/WebserviceSpecificManagementImages.php, line 1128 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8303#-KyKT_KancZDtvhDw497:-KyKT_KancZDtvhDw498:b-1upgnu) ([raw file](https://github.com/prestashop/prestashop/blob/7a49d0ec0f354f4a597599963c0387fe00c681a3/classes/webservice/WebserviceSpecificManagementImages.php#L1128)):*
> ```PHP
>                             throw new WebserviceException('An error occurred while copying image', array(76, 400));
>                         }
>                         if ($this->imageType!='product_option_values') {
> ```

Please add spaces around comparison operators.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8303)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Hello @FrancMunoz, thanks for this PR !
I identified some code style and formatting issues.
I suggest using php codesniffer and/or php cs fixer to avoid this in the future. Modern IDE often have extensions to use it and get warnings and/or fixes directly into the code you are editing (e.g phpStorm includes them by default, but not activated)

**Comment by matks** [comment]
Hi, [following our review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

Since we did not get answer from author I close this PR.

Please note this does not mean it's a final "won't merge" 😉 if you come back we can reopen it

Thank you for the contribution

**Pull request closed without merging**
