### PR TITLE
// AddonsDataProvider curl fallback

### PR DESCRIPTION
**Pull request by rGaillard**
This PR follow #5014 and must be merged after the first one on the develop branch.

### CODE REVIEW

**Comment by xBorderie** [comment]
Hey @Shudrum, now that #5014 has been merged, maybe it's time to merge this one too?

**Comment by Shudrum** [comment]
What is the relation between the #5014 and this one?

**Comment by xBorderie** [comment]
This PR makes `Tools::file_get_contents()` use one parameter (the last one, `fallback`) that was added in #5014.

Before #5014:

`public static function file_get_contents($url, $use_include_path = false, $stream_context = null, $curl_timeout = 5)`

After #5014:

`public static function file_get_contents($url, $use_include_path = false, $stream_context = null, $curl_timeout = 5, $fallback = false)`

**Comment by aleeks** [comment]
Hello @rGaillard 
Thank you, as seen with you, we did differently

Thank you!!

**Pull request closed without merging**
