### PR TITLE
Add pre-release information

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | This PR aims to add the prerelease information of the version available. This way, developers can choose to use the full version (8.0.0-beta.1) or only the "main" part (8.0.0) by using the method `PrestaShop\PrestaShop\Core\Foundation\Version::getVersion($full = false)`
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | Create a release with this PR and try to install it. Everything should work but know you should have `8.0.0-beta.1` instead of `8.0.0` in the login screen and on the top bar of the BO.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by paulnoelcholot** [comment]
Hi @atomiix 

I tested this PR and saw a design bug. There is an overflow on the "Quick Access" drop-down menu. You can see this on the screenshot.

image

**Review by boubkerbribri — CHANGES_REQUESTED** [review]
Hello @atomiix 
Install on CLI seems to be broken. I got this error 
image

Script used : 
```sh
php /var/www/html/ps_80x/install-dev/index_cli.php --domain="localhost" --base_uri="/ps_80x" --db_server="127.0.0.1:3306" --db_name="ps_80x" --db_user="*****" --db_password="*****" --prefix="tst_" --firstname="Marc" --lastname="Beier" --email="demo@prestashop.com" --language="en" --country="fr" --create-db="1"
```

**Comment by matks** [comment]
Friendly reminder @atomiix

**Comment by kpodemski** [comment]
Hi @atomiix 

Another reminder, if you want to see it in PrestaShop 8.1, it's the last call to have it finished :)

**Pull request closed without merging**
