### PR TITLE
Merge 1.7.8.x into 8.0.x

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Merge 1.7.8.x into 8.0.x
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Comment by nicosomb** [comment]
Tests launched here: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/3731465667

**Review by jolelievre — APPROVED** [review]
Thanks @nicosomb

**Review by jolelievre — DISMISSED** [review]
Actually many CI is failing, probably related to the composer.lock which updates many of our dependencies to versions even higher than on develop (8.1 version)

**Review by atomiix — DISMISSED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by nicosomb** [comment]
Tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/3739336717

**Comment by nicosomb** [comment]
List of updated dependencies in composer.lock: 

composer/ca-bundle
doctrine/collections
doctrine/event-manager  
incenteev/composer-parameter-handler
matthiasmullie/minify  
mobiledetect/mobiledetectlib
monolog/monolog
nikic/php-parser  
prestashop/ps_categorytree 
tijsverkoyen/css-to-inline-styles
mikey179/vfsstream    
sebastian/comparator 
sebastian/exporter

Due to conflicts with other dependencies, I set doctrine/deprecations to v0.5.3

**Comment by MhiriFaten** [comment]
Hello @nicosomb ,

We are waiting to test it, can you add the **`waiting for QA`** label ?

Thank you.

**Review by florine2623 — APPROVED** [review]
Hello @nicosomb ,

Thanks for the launch of the automated tests!
After a quick exploratory session for (on BO and FO), I haven't found anything major.
Checked:
- PPV2
- Order page
- Customer account
- Order confirmation

So this is QA ✅ !

Thanks!

**Comment by matks** [comment]
Thank you QA team and @nicosomb !

**Pull request merged**
