### PR TITLE
Display discounts by quantity table when applied to combination

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Display discounts by quantity table when applied to combination |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1218 |
| How to test? | Add a specific rule on a specific combination with a price fixed if you buy - lets say - 3 products. You should see the table of discounts displayed. |

capt

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by mickaelandrieu** [comment]
Thanks !

**Comment by jkfoong** [comment]
I am having this issue even with fixed product-discounts.tpl. Can you please help me?
new
new2

Same happens to the quick view when adding product discount block in quick view. It doesn't update automatically.

**Comment by khouloudbelguith** [comment]
Hi jkfoong,

In the Shop Parameters / Product Settings page, the Quantity discounts should be based on combinations.
image

Best regards, Khouloud

**Comment by jkfoong** [comment]
It is already based on Combinations. But still the problem exists.

**Comment by khouloudbelguith** [comment]
Hi jkfoong,

This issue is added to our bug roadmap: http://forge.prestashop.com/browse/BOOM-3976.
It is not fixed yet.
Please follow BOOM-3976.

Best regards, Khouloud

**Comment by jkfoong** [comment]
Okay thank you! Does that mean that it will only be fixed in 1.7.5?

**Pull request merged**
