### PR TITLE
Change classic selectors to js prefixed selectors

### LINKED ISSUE #14346: CSS classes / element attributes called by core.js have to be marked
It would be very, very helpful for anyone designing / updating a theme if all classes, ids, data-attributes or anything else required by the core could be prefixed in the starter & classic theme as such.

Ideally it would be something like class="js-core-xyz"

I remember reading this was an aim on the developer.prestashop.com docs before they got migrated to devdocs.prestashop.com but I can't find anything on it now.

I just spent a good part of day debugging why the product page theme wasn't working after updating to the newest version of PS. I had to debug the core itself line by line only to find it was because I didn't have a div class="product-actions" in my theme, which the core requires to update thumbnails. If mandatory element attributes were easily signposted in the classic theme I could just compare my template file like for like and spot any missed element attributes.

I am aware this might break a lot of themes in the short run but it seems good coding practice for the long run.  You could either check for both attributes for backward comparability while you deprecate.

I know not a big one but would make things feel more dev friendly and probably save a bunch of hidden wasted hours in the long run.

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | It's easier for theme developers and bc breaks if selectors are named prefixed with js-, actually it should be a nightmare to template something with these selectors
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #14346.
| How to test?      | You should browse the classic theme looking for features with JavaScript like checkout, product page (with multiple images for example, combinations) and see if it works as expected
| Possible impacts? | The whole FO

PS: Some selectors are not changed or approx, because it would add BC break or would break something

I kept past selectors in order to avoid BC Breaks, but they needs to be removed in the next major

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23056)

### CODE REVIEW

**Comment by Hlavtox** [comment]
THIS!!!! ❤️

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I found this issue in the FO > Product list page > Filter by section:

If you click in the checkbox => nothing happens
image
I attached a screen record
https://drive.google.com/file/d/1VoYg2uM3dYBvqQstb5edmGk9AKusdMM3/view?usp=sharing

**Without PR**
=> ok
https://drive.google.com/file/d/1_coQAAnMuE4y86CyfYv0pHcI3QHjKtGv/view?usp=sharing

Thank you!

**Comment by NeOMakinG** [comment]
Should be fine @khouloudbelguith now, is it the only one regression you detected ?

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Yesterday, I made those tests and they are ok.
1. FO quick view and product details page
1.1 minimal quantity
1.2 Stock available (when in stock & out of stock)
1.3 label when in stock
1.4 label when out of stock with allowed order
1.5 change combinations
1.6 images
1.7 specific price applied to all combinations or applied to a specific combination
1.8 Specific price on quantity > 1
1.9 rating (product comment transplant to the hook Dislayproductadditionalinfo)
1.10 Add to cart
1.11 A product with an attachment
1.12 check a product when in stock / no stock with denying order / no stock with allowed order
1.13 Customized product ( text / file)
1.14 Flags

2. checkout
2.1 try with a guest
2.2 Try with a new customer
2.3 Sign in with Old customer
2.4 Add new address
2.5 edit address
2.6 select carrier
2.7 select a gift
2.8 select a Wrapping
2.9 display the alert No shipping displayed for a specific country
2.10 display No payment alert method
2.11 select payment
2.12 select terms & service

3. Cart rule in the checkout page
3.1 cart with no code
3.2 cart rule with code not displayed
3.3 cart with code displayed

I will make a new test when this PR is ready:slightly_smiling_face:  

Thank you!

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I found a new issue following these steps:

1. Create a cart rule with a code (`Highlight` is enabled or not)
2. Go to FO > Log in > Add a product to the cart
3. Continue checkout 
4. In the checkout page > Add the promo code 
image
5. See the error 
image
6. Refresh the page => ok
7. Delete the voucher
image
8. See the error 
image

I tried with fresh develop branch without PR, it was partially ok (there is an old issue reported here: https://github.com/PrestaShop/PrestaShop/issues/21961)
I attached a screen record https://drive.google.com/file/d/1tTiXNhY7cSTxvDlq8Dg4MXurjeV0kAzd/view?usp=sharing

Thank you!

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/151EvKCYIxnPTW_Uan1ByeUs8d9cD2uDv/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @khouloudbelguith

**Pull request merged**
