### PR TITLE
// hide deprecated msg for Module::isInstalled

### PR DESCRIPTION
**Pull request by julienbourdeau**
As of today this method is still used a lot. it's a bit soon to display the deprecated message.

http://forge.prestashop.com/browse/BOOM-434

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
ping @Shudrum.

Shall we make `disableByName` and `enableByName` deprecation notice silent too ?

b49fbd6541e373303ae7debfb0ff843b

**Comment by julienbourdeau** [comment]
done

**Comment by Quetzacoalt91** [comment]
Thanks @julienbourdoge

**Comment by julienbourdeau** [comment]
Because as of today there is too many use of this method, we'll put the deprecation message back during the beta process. We need to clean some of our code before that.

**Pull request merged**
