### PR TITLE
[*]WS: Adding Message to the API

### PR DESCRIPTION
**Pull request by gleseur**
Hi,

This is very useful when creating orders or updating orders with the API and needing to leave a note.

Thanks

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi!

Sorry for the long time…

And thank you!

**Comment by Shudrum** [comment]
(Tests have passed locally)

**Comment by gleseur** [comment]
Thanks @Shudrum. Glad this ends up being merged

**Comment by Shudrum** [comment]
Yep, I am working to reduce the develop branch PR count, it is a huge work, but PrestaShop really need this!

**Pull request merged**
