### PR TITLE
Add admin breadcrumb hook

### PR DESCRIPTION
**Pull request by cvng**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Hooks: Allow customizing the admin breadcrumb for user navigation
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | You can test it using ps_qualityassurance module, all the details available below
| Fixed ticket?     | N/A
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/580
| Sponsor company   | 

Using the ps_qualityassurance module

Register the `actionAdminBreadcrumbModifier` hook and assign the `breadcrumb` param:

```php
public function hookActionAdminBreadcrumbModifier(array &$params): void
{
    $params['breadcrumb']['container']['name'] = 'HELLO';
}
```

In the back-office, you should see the updated breadcrumb with the HELLO text.

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]
Seems a good idea, but why do you add 'tabs' in the hook ?

**Comment by cvng** [comment]
> Seems a good idea, but why do you add 'tabs' in the hook ?

Hi @mflasquin, thanks for the quick feedback :) To be fair the original changeset was:

```php
// classes/controller/AdminController.php#L676

$breadcrumbs2 = [];

foreach (array_filter($tabs) as $tab) {
    array_unshift($breadcrumbs2, ['name' => $tab['name'], 'href' => $this->context->link->getTabLink($tab)]);
}
```

But since this is a breaking change, we need a way to expose `$tabs` in user-space to implement the same behavior

**Review by boherm — APPROVED** [review]
Seems good for me, and a good idea too.
Thanks for your contribution!

**Comment by Hlavtox** [comment]
Hi @cvng, you can do this using already existing hook `actionAdminControllerInitAfter`, is it worth it to add another one?

```
$breadcrumbs2 = $this->context->smarty->tpl_vars['breadcrumbs2']->value;
$breadcrumbs2['container']['name'] = 'HELLO';
$this->context->smarty->assign(['breadcrumbs2' => $breadcrumbs2]);
```

**Comment by kpodemski** [comment]
@Hlavtox, having an extra hook is much cleaner 👍🏻

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@kpodemski I friendly disagree, one more hook to add to fixtures, to documentation, when upgrading. But OK if I am over-voted. :D

**Comment by matks** [comment]
> @kpodemski I friendly disagree, one more hook to add to fixtures, to documentation, when upgrading. But OK if I am over-voted. :D

Interesting question

The bigger question behind is: "is it easier to have a lot of hooks, in a lot of different places, each of them specialized to allow one customisation and do it well or is it easier to have highly generic hooks that cover most of possible usecases"

I prefer @kpodemski approach because smaller and more specific hooks make it easier to modify the software.

Here is my reasoning: a hook like `actionAdminControllerInitAfter` might be used for 20 or 30 different usages. So we might have hundred of modules, some use it to alter a controller rendering, some use it to expand a controller capabilities, some use it to sync data to another software...
If we decide one day to modify / move this hook it'll have a very big impact on these hundred modules.

On the other hand, a hook like `actionAdminBreadcrumbModifier` will only be used (I think) to modify crumbs, nothing else. So if in the future we move / refactor this hook the impact will be limited to modules that aim to modify the crumbs in the software.

So I approve this PR

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @cvng 

I have checked your PR. 

I used the `qualityassurance` module and used the same steps that you have mentioned. But, I did not found the HELLO for the updated breadcrumb. However, the hook is well present in the DB 

image

https://user-images.githubusercontent.com/92912932/233369973-e5468752-8fcf-4b6a-8a28-726a8995def8.mp4

Did I miss something ? 

Thank You!

**Comment by kpodemski** [comment]
@HanaRebaiQA Hana, you shouldn't put the entire function in the quality assurance module, only the content of the function. Only this part of the code:

`$params['breadcrumb']['container']['name'] = 'HELLO';`

**Comment by HanaRebaiQA** [comment]
@kpodemski Yes! I did it also even with dump and die 


https://user-images.githubusercontent.com/92912932/233382590-4a697fbd-9481-4bbb-bab1-d2cf0f224e55.mp4

**Comment by kpodemski** [comment]
@cvng could you help QA test the hook?

**Comment by cvng** [comment]
> @kpodemski Yes! I did it also even with dump and die
> 
>  32060_new.mp4

Hi @HanaRebaiQA Hana, thanks for the feedback! How can I help you test it? This is what I have on a fresh install:

Capture d’écran 2023-04-24 à 12 54 37

The full code is:

```php
// classes/controller/AdminController.php#L676

Hook::exec('actionAdminBreadcrumbModifier', ['tabs' => $tabs, 'breadcrumb' => &$breadcrumbs2], null, true);

// modules/module.php

public function hookActionAdminBreadcrumbModifier(array $params): void
{
    // dd($params);
    $params['breadcrumb']['container']['name'] = 'HELLO';
}
```

cc @kpodemski

**Comment by kpodemski** [comment]
@cvng as you can see on the video, breadcrumbs didn't change at all

**Comment by kpodemski** [comment]
Hello @HanaRebaiQA 

Everything works for me. Here are some screenshots:

1. I registered the hook: https://capture.dropbox.com/XaJXfZmNKMmcSCdV
2. This is its content: https://capture.dropbox.com/26yXX0CgaFHBHlF7
3. And when I visit the Dashboard, I have this: https://capture.dropbox.com/rdEAFdHYcB2gV7uY
4. It works also for migrated pages: https://capture.dropbox.com/dIkbeTwrC4pvWsg0

So to me it is QA ✅

**Comment by kpodemski** [comment]
cc @HanaRebaiQA @Robin-Fischer-PS what about this PR? can it be treated as validated after my tests?

**Comment by kpodemski** [comment]
@cvng we're going to need this hook added in `autoupgrade` module as well 👍🏻 You can use this helper while modifying 8.1.0.sql:

`/* PHP:add_hook('actionAdminBreadcrumbModifier', 'Modify back office breadcrumb', 'This hook allows modifying back office breadcrumb'); */;`

**Comment by cvng** [comment]
> @cvng we're going to need this hook added in `autoupgrade` module as well 👍🏻 You can use this helper while modifying 8.1.0.sql:
> 
> `/* PHP:add_hook('actionAdminBreadcrumbModifier', 'Modify back office breadcrumb', 'This hook allows modifying back office breadcrumb'); */;`

@kpodemski Thanks for the review :) <s>I will do</s> I added the PR https://github.com/PrestaShop/autoupgrade/pull/580

**Comment by Robin-Fischer-PS** [comment]
Hi there ! @kpodemski If your test is OK, the PR can be validated and merged yes :)

Thanks ! And thanks @cvng for the PR.

**Comment by kpodemski** [comment]
thank you @cvng

**Comment by jolelievre** [comment]
Associated Autoupgrade PR https://github.com/PrestaShop/autoupgrade/pull/580

**Pull request merged**
