### PR TITLE
[-] BO : Pipes in product names in autocomplete

### PR DESCRIPTION
**Pull request by axometeam**
Convert pipe characters with their html entity for product name compatibility with autocomplete.js

How to reproduce bug : 
- Add a pipe in a product name
- Try to add this product as an accessory for an other product
- Autocomplete fails to load this product because of the pipe present in the name

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi and thank you!

Why not just use `htmlentities()` is this case? Maybe names can contains other characters failling the autocomplete?

**Comment by nsorosac** [comment]
Hi @Shudrum,

Because autocomplete.js uses the pipe character to split the ajax result rows:

`row = row.split("|");`
*(in jquery.autocomplete.js method $.Autocompleter.parse)*

If I'm right, `htmlentities` doesn't convert pipes, urlencode would be the best choice here, but we would need to urldecode the data wherever the ajax_products_list is used.

Can't we migrate each call to this file with a JSON response instead of an old fashioned "multi-vars-split-string"? Is there a reason why all autocomplete calls use a JSON response but not this one?

**Comment by Shudrum** [comment]
My bad, I haven't see that…

Ok, perfect! Thank you!

:+1:

**Comment by Shudrum** [comment]
And for your question, I do not really now why… I think we can do it, but we do not have the time right now, sorry.

**Comment by Shudrum** [comment]
Hi @axometeam, we have tried a feature for the Travis tests and we cannot merge your PR… Can you please try the auto update button or recreate a PR?

Thank you!

_And yep, we have removed this feature._

**Comment by Shudrum** [comment]
:+1:

**Pull request merged**
