### PR TITLE
Fix stock design

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | devolop
| Description?  | Fix page display on desktop
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3939
| How to test?  | Test stock on desktop

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8326)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]
Okay for me!

**Comment by Quetzacoalt91** [comment]
I think you would be interested in this issue. On firefox, the input fields have their arrows displayed:

capture du 2017-09-19 09-36-29
On Google Chrome, everything seems good.

**Comment by nihco2** [comment]
Thx for this FF test @Quetzacoalt91

**Comment by Quetzacoalt91** [comment]
Okay for me!
However, I need you to keep only one commit "BO: compiled assets". It could create conflicts to resolve several times for the other developers, once your PR would be merged.

**Review by eternoendless — DISMISSED** [review]

**Comment by marionf** [comment]
Little thing :
On Firefox, the text is stuck against the border
capture du 2017-10-04 18-27-17

On Chrome it's better, there is more place
capture du 2017-10-04 18-29-02

**Comment by eternoendless** [comment]
I fixed a lot of small things. It should be OK now!

**Comment by Quetzacoalt91** [comment]
@marionf, could you have a look again please?

**Review by nihco2 — COMMENTED** [review]
:thumbsup:

**Comment by marionf** [comment]
There are still some regression listed here: http://forge.prestashop.com/browse/BOOM-3939
But I don't know if it will be solved on this PR or another ?

**Comment by nihco2** [comment]
@eternoendless to fix the regression, I think here: https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/app/widgets/ps-number.vue#L62
this.value should be a Number instead of a string

**Comment by LittleBigDev** [comment]
Reviewed 2 of 8 files at r1, 3 of 3 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/low-filter.vue, line 35 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8326#-Kwj_ICbWQc71dtC-vS3:-Kwj_ICbWQc71dtC-vS4:b-cl4tsd) ([raw file](https://github.com/prestashop/prestashop/blob/d4e31d9460a77387497e18378d8930b5fd292bef/admin-dev/themes/new-theme/js/app/pages/stock/components/header/filters/low-filter.vue#L35)):*
> ```Vue
>       <a class="float-sm-right ml-2" :href="stockImportUrl" target="_blank">
> 				<span data-toggle="pstooltip" :title="stockImportTitle" data-html="true" data-placement="top">
> 					<i class="material-icons">cloud_download</i>
> ```

Care about tabs instead of spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8326)*

**Comment by eternoendless** [comment]
@nihco2, I can't push into your branch anymore 😢 

Could you please check the option "Allow edits from maintainers" on your PR?

You can find it at the bottom of the right column:

image

Thanks!

**Comment by nihco2** [comment]
@eternoendless done !

**Comment by eternoendless** [comment]
Thanks!

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8326#-:-KwobZ4ahN6DHdNe6H2J:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @nihco2

**Pull request merged**
