### PR TITLE
[-] FO : Invalid combination price in case of ecotax

### PR DESCRIPTION
**Pull request by erouvier29**

### CODE REVIEW

**Comment by eric-rouvier** [comment]
There is still some strange stuff about ecotax in /themes/default-bootstrap/js/product.js (confusion between tax ecluded and included). I didn't see any impact at the moment, but I did very simple tests. To be continued...

**Comment by kpodemski** [comment]
inline math is IMO very bad practice, there's should be method in Product class to work on ecotax...

**Comment by eric-rouvier** [comment]
@kpodemski: fully agree, especially when in theme related files. This is just a fix waiting for refactoring.

**Comment by eric-rouvier** [comment]
Moved as #3471

**Pull request closed without merging**
