### PR TITLE
Merge 1.7.7.x into develop - 18/02/2020

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Merge last changes from 1.7.7.x into develop
| Type?         | improvement
| Category?     | ME
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |  No QA needed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17718)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by matks** [comment]
Thanks for review

**Comment by matks** [comment]
Trolled by Travis
Capture d’écran 2020-02-18 à 17 42 20
Capture d’écran 2020-02-18 à 17 42 37

**Comment by matks** [comment]
> Trolled by Travis

Should be fixed by https://github.com/PrestaShop/PrestaShop/pull/17718/commits/ee106d34721d0ffcd2efa8f764f4d0a5c989823e

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @matks

**Pull request merged**
