### PR TITLE
Introduce hook to override layout file

### PR DESCRIPTION
**Pull request by julienbourdeau**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Introduce hook to override layout file. Since 1.7 consider layout and template as 2 different things, we need a hook to build amazing things :D |
| Type? | new feature |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Create a module that register this hook and create "hookOverrideLayoutTemplate($params)" method |

**Note**: New naming convention for hook name, this one start with `get`. Since it's neither an action nor a display hook, it made sense to me. What do you think?

### CODE REVIEW

**Comment by kpodemski** [comment]
@julienbourdeau hmm, i've had the same problem with naming here:
https://github.com/PrestaShop/PrestaShop/pull/5924

and finally it ends up with `overrideMinimalPurchasePrice`, should i change this hook name or we keep naming it as for example `overrideLayoutFile`, `overrideSomethingElse` etc?

**Comment by julienbourdeau** [comment]
I like `overrideXX` I'll change it

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
How can we test it?

**Comment by maximebiloe** [comment]
Thank you!

**Comment by julienbourdeau** [comment]
@mickaelandrieu I updated the PR description

**Pull request merged**
