### PR TITLE
Correct stylelint browsers on new-theme

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | We need to correct some things in order to get no-unsupported-browsers-features in our eslint configuration
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | It's globally touching new-theme (migrated pages) style, but nothing really risky, QA should at least look the theme page, modules cards

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20375)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @PierreRambaud @Progi1984 
On safari browser, I have two 404 in console while navigation on website (no specifically related to module or themes) 
I had this errors on others version but Im not sure if this correction should get rid of it?
Capture d’écran 2020-08-13 à 11 55 09

Thank you

**Comment by ngodefroy** [comment]
I found issues in the console while testing this version, not reproductible on the 177.
Test case:
BO>Design>Theme catalog 
Capture d’écran 2020-08-13 à 14 25 31

**Comment by ngodefroy** [comment]
Hello,

I found some issues in the console on the theme Catalog page, not reproduced in the 177 v.
Scenario:
BO>Design>Theme Catalog>see console

Capture d’écran 2020-08-13 à 15 31 33

**Comment by PierreRambaud** [comment]
> Hello,
> 
> I found some issues in the console on the theme Catalog page, not reproduced in the 177 v.
> Scenario:
> BO>Design>Theme Catalog>see console
> 
> Capture d’écran 2020-08-13 à 15 31 33

These errors are not related to the PrestaShop software itself, I will contact the addons team :wink:

**Comment by NeOMakinG** [comment]
Hello,

This is not related to the PR

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

**Pull request merged**
