### PR TITLE
Add id shop parameter to module link with route

### PR DESCRIPTION
**Pull request by nprokopenko202**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In multishop for modules with routes links are generated not correctly.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | See below

1) Create two shops. In my example there will be:
```
https://test-prestashop.fr/
https://test-prestashop.de/	
```										
2) For tests we can use module RGPD Officiel. In BO "SEO & URL" for every shop add meta page for controller "psgdpr-gdpr" with url rewrite "gdpr" for example;	
3) In any front template add links to gdpr page with specific shop id like:
```
<div>{url entity="module" name="psgdpr" controller="gdpr" id_shop="1"}</div>
<div>{url entity="module" name="psgdpr" controller="gdpr" id_shop="2"}</div>
```
4) Refresh page that uses template from step 3. As a result we have same links for every shop:
```
https://test-prestashop.fr/pdpr
https://test-prestashop.fr/pdpr
```	

Result expected:
```
https://test-prestashop.fr/pdpr
https://test-prestashop.de/pdpr
```	

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20322)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by nprokopenko202** [comment]
Hello, @Progi1984 
Could you please say when this PR will be merged? 
Thanks

**Comment by PierreRambaud** [comment]
> Hello, @Progi1984
> Could you please say when this PR will be merged?
> Thanks

When it will validate by the QA team :wink:

**Comment by SD1982** [comment]
Hi @nprokopenko202  can you provide us a test scenario please ?

**Comment by nprokopenko202** [comment]
Hello, @SD1982 !
In multi shop try to generate a link for module that uses friendly URL (with Link::getModuleLink) for navigating in front office from one shop to another. It will be the link to the current shop and not to the one we indicated.

**Comment by Progi1984** [comment]
Ping @SD1982

**Comment by SimonGrn** [comment]
Hello @nprokopenko202 

could it be possible to have a **detailed** process with all the steps to reproduce, please ? I'm sorry but this is not very clear right now (what are you referring to with "module link" ?)

Thank you !

**Comment by nprokopenko202** [comment]
Hello, @SimonGrn !

1) Create two shops. In my example there will be:
```
https://test-prestashop.fr/
https://test-prestashop.de/	
```										
2) For tests we can use module RGPD Officiel. In BO "SEO & URL" for every shop add meta page for controller "psgdpr-gdpr" with url rewrite "gdpr" for example;	
3) In any front template add links to gdpr page with specific shop id like:
```
<div>{url entity="module" name="psgdpr" controller="gdpr" id_shop="1"}</div>
<div>{url entity="module" name="psgdpr" controller="gdpr" id_shop="2"}</div>
```
4) Refresh page that uses template from step 3. As a result we have same links for every shop:
```
https://test-prestashop.fr/pdpr
https://test-prestashop.fr/pdpr
```	

Result expected:
```
https://test-prestashop.fr/pdpr
https://test-prestashop.de/pdpr
```

**Comment by SimonGrn** [comment]
Thank you @nprokopenko202 ! I took the liberty to edit the issue body to add these steps.

@SD1982 Is this enough for you ?

**Comment by SD1982** [comment]
@SimonGrn Yes it's more clear now i will try this scénario !
Thanks  @nprokopenko202 !

**Comment by SD1982** [comment]
Hi @nprokopenko202 i can't test for now with your scénario because of this issue : #20863 
I will test your PR again when it's fixed !

**Comment by SD1982** [comment]
Hi @nprokopenko202 I don't reproduce the behaviour you described without the PR applied
I proceeded this way:

1 - Enable multistore
2 - create two additional stores in the default group => so i have "default shop = id 1" , "shopA = id 2", "shopB = id 3"
image
3 - in "all shops" context In BO "SEO & URL" add meta page for controller "psgdpr-gdpr" with url rewrite "gdpr" 
4 - in the index.tpl template i added links to gdpr page with specific shop id like this:
image
In my FO i have the 3 links correctly displayed
image

If i check the links i have this results:
`Default link => http://localhost:8071/develop/fr/gdpr`
`ShopA link => http://localhost:8071/develop/shopA/fr/module/psgdpr/gdpr`
`ShopB link => http://localhost:8071/develop/shopB/fr/module/psgdpr/gdpr`

So for me it's seems that the links are correct no ?
Did i miss something while tryng to reproduce the behaviour ?
Is it the fact that I am testing in localhost that can generate behavior different from the one you describe?
Or maybe the issue is already fixed by another PR ?

**Comment by nprokopenko202** [comment]
Hi @SD1982 !
As I can see the links for two other shops don't use url rewrite cause we shouldn't have 'module/psgdpr/gdpr' but only 'gdpr' in link.
That's why it works. Link rewrite should be generated for every shop to reproduce this bug

**Comment by SD1982** [comment]
Hi @nprokopenko202 it's me again !!
So i just tested to disable thefriendly option and i have the following results:

**Without PR - friendly url disabled**
`default link => http://localhost:8071/develop/index.php?fc=module&module=psgdpr&controller=gdpr&id_lang=2`
`shop A link => http://localhost:8071/develop/shopA/index.php?fc=module&module=psgdpr&controller=gdpr&id_lang=2`
`shop B link => http://localhost:8071/develop/shopB/index.php?fc=module&module=psgdpr&controller=gdpr&id_lang=2`

**Without PR - friendly url enabled**
`default link => http://localhost:8071/develop/fr/gdpr`
`shop A link => http://localhost:8071/develop/shopA/fr/module/psgdpr/gdpr`
`shop B link => http://localhost:8071/develop/shopB/fr/module/psgdpr/gdpr`

**With PR - friendly url disabled**
`default link => http://localhost:8071/developPR1/index.php?fc=module&module=psgdpr&controller=gdpr&id_lang=2`
`shop A link => http://localhost:8071/developPR1/shopA/index.php?fc=module&module=psgdpr&controller=gdpr&id_lang=2`
`shop B link => http://localhost:8071/developPR1/shopB/index.php?fc=module&module=psgdpr&controller=gdpr&id_lang=2`

**WithPR - friendly url enabled**
`default link => http://localhost:8071/developPR1/fr/gdpr`
`shop A link => http://localhost:8071/developPR1/shopA/fr/module/psgdpr/gdpr`
`shop A link => http://localhost:8071/developPR1/shopB/fr/module/psgdpr/gdpr`

I have the same results with 1.7.7.x

And for this part
image
I think it's because of this parameter
image
but i have no idea why it's only applied for shop A and B but not for the default shop !

**Comment by nprokopenko202** [comment]
Hi, @SD1982 !

To reproduce this bug you have to add link rewrite for this module here (buy click on 'Add a new page' that is on your screen) : 

linkrewrite

**Comment by SD1982** [comment]
> Hi, @SD1982 !
> 
> To reproduce this bug you have to add link rewrite for this module here (buy click on 'Add a new page' that is on your screen) :
> 
> linkrewrite

Hi @nprokopenko202 Yes I do that part too
This is a screenrecord of all the process i followed ( The PR is not applied )
Maybe it will help you see if I miss a step
https://drive.google.com/file/d/1yMClW43MUKBn9Gw6Of5vAlAL5v7XQwZV/view?usp=sharing
I also tested to switch my FO in english and the links are correct too
`default link => http://localhost:8071/develop/en/gdpr`
`shop A link => http://localhost:8071/develop/shopA/en/module/psgdpr/gdpr`
`shop B link => http://localhost:8071/develop/shopB/en/module/psgdpr/gdpr`

Maybe another @PrestaShop/qa-functional member can watch from his side

**Comment by khouloudbelguith** [comment]
Hi @nprokopenko202,

I did not manage to reproduce the issue with the develop branch (without PR)

In shop1, I have
```
https://prestashop.tn/PrestaShop/fr/gdpr
//0.0.0.0:8090/PrestaShop/shop2/fr/module/psgdpr/gdpr 
```
image

In the shop2, I have
```
//prestashop.tn/PrestaShop/en/module/psgdpr/gdpr
https://0.0.0.0:8090/PrestaShop/shop2/en/gdpr
```

Thank you!

**Comment by nprokopenko202** [comment]
@khouloudbelguith Hi ! Thanks for tests :) 
As you can see the type of the links for two shops is not the same. In FO link rewrite is taken into account only for shop in current context and not for others. 

If we are in shop 1 the link for this shop ends with **/gdpr** and for the same shop but in shop 2 we have **/module/psgdpr/gdpr**
It's just weird. The routes are loaded only for shop in current context in FO. 

No matter in which shop we are links are expected to be like:
```
https://prestashop.tn/PrestaShop/fr/gdpr
https://prestashop.tn/PrestaShop/shop2/fr/gdpr
```

Actually I've found the similar PR https://github.com/PrestaShop/PrestaShop/pull/8025 that was added for 1.6 and was removed from 1.7

But in this condition in IF case we pass only for current shop, cause for others routes are not loaded:
moduleLink

Maybe I have to make another PR and close this one? What do you think?

**Comment by khouloudbelguith** [comment]
Hi @nprokopenko202,

Thanks for these clarifications.
Ping @PrestaShop/prestashop-core-developers what do you think?

Thanks!

**Review by matthieu-rolland — COMMENTED** [review]
@nprokopenko202 hello ! 

You should probably create an issue, explaining the bug, and giving a definitive test scenario, with all the additional details you put in this PR, it must be very precise, seems it seems to be tricky to reproduce. Then you can link the issue in the PR description.

Once the bug is validated, we can use this PR. This will help QA team, but also the product team, they need these issues to track what is happening on the project.

Thanx !

**Comment by PierreRambaud** [comment]
Hi @nprokopenko202 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
