### PR TITLE
[*] BO : Pass the object we're displaying to the action{$controller}Form...

### PR DESCRIPTION
**Pull request by tiennou**
...Modifier hook

This allows modules to register a hook instead of overriding the whole controller to add a new section to "display" templates

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by tiennou** [comment]
This one still holds. Maybe there's a better Core-sanctioned way of doing it, but this seemed the cleanest way to go...

**Comment by xBorderie** [comment]
Thank you for your feedback @tiennou !

Since this PR was made on the '1.6' branch, could you make it again on the '1.6.1.x' branch so that you get full credit once we merge it? Even better if you do it on the 'develop' branch, so that it lands in PS 1.7 :)

Thank you very much!

**Comment by tiennou** [comment]
Here comes a PR against `develop` then ;-).

**Comment by xBorderie** [comment]
Great, thank you very much Étienne!

**Pull request closed without merging**
