### PR TITLE
Fix updating empty combination reference from list

### LINKED ISSUE #29269: BO - Products V2 - Cannot remove the combination reference from the combination's list
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Products > Product V2 > Combinations tab, when we try to remove a combination's reference, the modification is not saved.

https://user-images.githubusercontent.com/16067358/183115014-77de5818-edb9-45c9-9c15-e1eb635d1504.mp4

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features page & Enable New product page - Single store
2. Go to BO > Catalog > Products V2
3. Create a product with combinations
4. Generate a combination & set a reference for this one
5. try to remove the reference from the combination list & save
6. See error > the modification is not saved

PS: we can remove the combination reference from the edit page or with bulk action

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | bug fix #29269
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Closes #29269
| Related PRs       | 
| How to test?      | refer to #29269
| Possible impacts? |

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

**Review by jolelievre — COMMENTED** [review]
@zuk3975 Did you test if it works with bulk edition as well just in case?

**Comment by zuk3975** [comment]
> @zuk3975 Did you test if it works with bulk edition as well just in case?

yes it works, we have a disabling toggle exactly for that case (so we are not checking against empty value, but against the disabling toggle option when bulk updating).

**Comment by hibatallahAouadni** [comment]
Hello @zuk3975 

Thanks for your PR :rocket: and your patience :pray: 
LGTM, QA :heavy_check_mark: 

- Setting a reference for each combination :heavy_check_mark:
- Modifying a reference for each combination :heavy_check_mark: 
- Deleting a reference for each combination :heavy_check_mark: 

All works in Single Store / Multistore / Product V1 / Product V2 :raised_hands: :clap: 

Thanks!

**Review by hibatallahAouadni — APPROVED** [review]
Hello @zuk3975 

Thanks for your PR :rocket: and your patience :pray: 
LGTM, QA :heavy_check_mark: 

- Setting a reference for each combination :heavy_check_mark:
- Modifying a reference for each combination :heavy_check_mark: 
- Deleting a reference for each combination :heavy_check_mark: 

All works in Single Store / Multistore / Product V1 / Product V2 :raised_hands: :clap: 

Thanks!

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
