### PR TITLE
Remove deprecated $bo_show_screencast property

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Remove deprecated property, set as deprecated in 1.6.0 version (See 06a178b8fe1fb8a4982ca5421bdead268af01745).
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no

📓 BC Breaks

    Removed property : Employee::bo_show_screencast

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28190)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @PrestaEdit

**Review by atomiix — APPROVED** [review]

**Comment by atomiix** [comment]
@PrestaShop/qa-functional I think this one doesn't need QA, ok for you?

**Comment by Robin-Fischer-PS** [comment]
We would like to run the automated test on the "Remove deprecated" PRs so it will go through QA (maybe with several PR merged into only one, in order to save some time).

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I think we should use automated tests.

**Review by HanaRebaiQA — APPROVED** [review]
Hello @PrestaEdit 

I just ran the automated tests, they are OK :heavy_check_mark: 

So, it's QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @PrestaEdit & @HanaRebaiQA

**Pull request merged**
