### PR TITLE
Add missing apostrophes to database queries

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing apostrophes to database queries
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          |
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Comment by SharakPL** [comment]
Why do you think it's missing?

**Comment by Hlavtox** [comment]
@ShaiMagal I think it's no problem to approve, but do you have any specific scenario when this doesn't work? I usually don't use any backticks and my queries work fine..

**Comment by ShaiMagal** [comment]
@SharakPL @Hlavtox because ALL other queries using it...
And its best practices to use this.
Check other files and queries.

Its not about "if worrking". Its about "semantic" only. Its best practices to use apostrophes and other our files using this.

So we should use it everywhere ;)

**Review by kpodemski — APPROVED** [review]
I don't see too much value in this PR, but the fact is that I also don't see any downsides in having it unified 🤷🏻‍♂️

**Review by Hlavtox — APPROVED** [review]

**Comment by kpodemski** [comment]
@ShaiMagal Please run UI tests, they, I think, will be enough for the validation of the PR.

**Comment by Hlavtox** [comment]
https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11775916222

**Comment by florine2623** [comment]
@Hlavtox , could you re-run the failed tests ? ^^

**Review by florine2623 — APPROVED** [review]
Tests are green : https://github.com/florine2623/testing_pr/actions/runs/11813857459

It can be merged ^^

Thanks!

**Comment by kpodemski** [comment]
thanks @ShaiMagal

**Pull request merged**
