### PR TITLE
Refacto product front controller

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Simplification and cleaning of product front controller. No changes in logic or BC breaks, just made it cleaner and easier to modify/extend/improve.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | -
| How to test?      | Check that everything works correctly
| Possible impacts? | no

### Changes
- Two new attributes saving ID of product and ID of combination.
- Removed two huge if blocks.
- Save `isPreview` to attribute the same way as `isQuickview`, so we don't have to check for it everytime.
- Put viewing checks to separate function `checkPermissionsToViewProduct()`. We want to improve it further by allowing users to view disabled products for SEO. This will make the QA easier.
- Put category assignment to separate function `initializeCategory()`. It will be easier for QA when we add some customization like "Always show full path in breadcrumb".
- Renamed `isAssociatedToProduct` to `isAdminWithToken` - easier to understand.
- Do not check if default category module is enabled to save id category to cookie - just save it. Other modules can benefit from it also. And we will get some performance gain.
- Put customization processing to `postProcess`, where it belongs.
- Remove `isQuickview` and `isPreview` from `displayAjaxQuickview` - already resolved in `init`.

### CODE REVIEW

**Review by Julievrz — APPROVED** [review]
Wording ok ✔️

**Review by matks — COMMENTED** [review]
> No changes in logic

I disagree a little 😛 you changed the behavior, you even described what you changed 😄

**Review by matks — APPROVED** [review]
@Hlavtox it was not easy to review 😛 I had to check every block you moved to make sure you rewrote it properly at another place

But it seems OK 👍 and tests will confirm it

Hint: when you do such refactoring it can be useful to move 1 block, then commit, then move 1 block, then commit so reviewers can review commit by commit and each commit is easy to review

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Automatic tests are OK. No error in console.

Checked FO product page:
- display images, description, title, details, summary, price...
- add to cart button
- wishlist button
- combinations
- customization
- pack product
- quantity
- tags on product
- breadcrumbs
- options

It is looking good ✅ 
Thanks!

**Pull request merged**
