### PR TITLE
Fix issue where field updates by api when they are not supposed to

### LINKED ISSUE #9819: [BOOM-4234] CLONE - [webservice] Data deleted
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4234).

- _**Reporter:**_ salma.moakhar
- _**Created at:**_ Fri, 3 Nov 2017 17:30:38 +0100

<p>Hi,</p>

<p>Throw webservice, update a customer.<br/>
Unset date_add and secure_key, resend xml to webservice in order to update customer.</p>

<p>date_add is updated<br/>
secure_key are deleted.</p>

<p>PS Webservice shouldn't delete these data.<br/>
secure_key is a readonly field !<br/>
It mustn't be updated.</p>

<p>Best regards,</p>

### PR DESCRIPTION
**Pull request by Prestaworks**
Fix for issue 9819 where last_passwd_get and secure_key are possible to update by api. also fix the same issue for employee.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | setter can not be null, it should be set to false to prevent saving data using API.
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9819.
| Related PRs       | 
| How to test?      | Follow instructions in issue, Use Postman to post changes to customer using api with and without mentioned fields in the data. Check result in DB and response from PS API
| Possible impacts? | Older integrations that update these fields or add these fields to the data will stop working until data sent to PS API is corrected.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@Prestaworks makes sense! thank you Daniel

**Review by matks — APPROVED** [review]
My apologies for delay 😞 we've been really busy with PrestaShop 8.0.0 and could not keep up with review

**Comment by boubkerbribri** [comment]
I think this can be tested by a developer .

**Review by matks — APPROVED** [review]
I was finally able to get to this PR that was waiting in my todo-list for a long time 😅 

Tested and approved ✅ thank you

**Comment by matks** [comment]
For the record:

In PrestaShop 8 if you send a XML input to update a customer and it contains the file secure_key or the file last_passwd_gen it will be accepted by PrestaShop.

By modifying the WS configuration for Customer and Employees, developers who send XML payloads containing these fields will now get a response message `parameter "secure_key" not writable`
`

**Pull request merged**
