### PR TITLE
Introduce alternative search panels same page links

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Alternative search panels links always have target="_blank" but what if we want to have internal page link? This PR adds a property to allow opening the link in the same page
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | An easy way is to use MBO which adds one alternative search panel (https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.5.2). The hard but independent is to have an example module adding alternative search panels
| Fixed issue or discussion?     | Fixes [https://github.com/PrestaShop/PrestaShop/discussions/33744](https://github.com/PrestaShop/PrestaShop/discussions/33744)
| Related PRs       | -
| Sponsor company   | PrestaShop

### CODE REVIEW

**Comment by sowbiba** [comment]
Check https://github.com/PrestaShop/PrestaShop/discussions/33744

**Comment by nicosomb** [comment]
Why not. 

Because you're working on this "feature", I think that `_blank` which is not clearly announced to the user is not a good thing. A good accessibility practice is to show to the user that a new tab / window will be opened (with icon like that for example https://thenounproject.com/browse/icons/term/new-window/)

We could take advantage of this PR to enhance "new tab" display. WDYT?

**Comment by sowbiba** [comment]
> Why not.
> 
> Because you're working on this "feature", I think that `_blank` which is not clearly announced to the user is not a good thing. A good accessibility practice is to show to the user that a new tab / window will be opened (with icon like that for example https://thenounproject.com/browse/icons/term/new-window/)
> 
> We could take advantage of this PR to enhance "new tab" display. WDYT?

Hello @nicosomb 
Thanks for the feedback

Please look at https://github.com/PrestaShop/PrestaShop/pull/33745/commits/adf69653562db522c3882c2f33c3d834f8516cdf

Capture d’écran du 2023-08-29 12-41-54

**Review by nicosomb — APPROVED** [review]
it looks nice, thank you @sowbiba !

**Review by matthieu-rolland — APPROVED** [review]

**Review by aniszr — COMMENTED** [review]
Hello @sowbiba 

I tested your PR and I found two different behaviors to check!

After submitting a search in BO :

- The First button redirect the user to another page
- The second button keep the user in the same page
- New customized button well displayed :heavy_check_mark: 

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/aeac6ba5-53bf-4517-bc55-1ff471da44e1



Auto Test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/6046703343 :heavy_check_mark: 

Could you please provide more details about expected behavior or correct me if I was wrong in some steps!

Thank you !

**Comment by kpodemski** [comment]
cc @sowbiba

**Comment by MatShir** [comment]
Not sure what is missing in this PR, both links redirect the another the page, both have the right icon. @kpodemski ?

**Comment by sowbiba** [comment]
Maybe an approval from me for the QA process. It's ok for me @aniszr 
You did the right tests. 
If you see nothing wrong, you can QA approve

**Review by paulnoelcholot — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @sowbiba

**Pull request merged**
