### PR TITLE
// added delete buttons for brand & related products options

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | updated_capture |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | Does it break backward compatibility? no |
| Deprecations? | Does it deprecate an existing feature? no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-371 |
| How to test? | Delete Manufacturer and related products, save and enjoy |

### CODE REVIEW

**Comment by maximebiloe** [comment]
Can you use this button `<button type="button" class="btn btn-invisible btn-block delete p-l-0 p-r-0"><i class="material-icons">delete</i></button>` for the delete one? So, it will respect the mockup 😄

**Comment by mickaelandrieu** [comment]
unmergeable from my point of view, regarding the multiple editions of the same files...

**Comment by vTerenti** [comment]
QA OK

But a detail has to be fixed, i wrote you the description on the ticket ;)

Best regards

**Comment by vTerenti** [comment]
Détail  fixed here :)

https://github.com/PrestaShop/PrestaShop/pull/5536

Good for me!

**Pull request merged**
