### PR TITLE
Add an instruction in htaccess to prevent directory listings

### LINKED ISSUE #33699: Prevent directory listings in the htaccess for Apache
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Some hosting providers, by default, do not prevent directory listings. We frequently encounter merchants whose directories can be viewed because of the absence of an `index.php` file, particularly when their hosting hasn't been configured correctly to restrict directory listings. Consequently, when these directories are accessed online, a list of files becomes visible. This poses a security risk, especially in cases where custom directories contain configuration files or other resources that shouldn't be publicly accessible.

### Expected behavior

The directly listing should be prevented in the htaccess.

### Steps to reproduce

To reproduce the issue, the Apache server should not enforce the Indexes.
The accessing to a directory (https://example.test/directory_notprotected) will [display the list of files](https://ibb.co/xDp4CnY).

### PrestaShop version(s) where the bug happened

All versions

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Profileo

### PR DESCRIPTION
**Pull request by maxime-morel**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix #33699 to prevent directory listings in the htaccess for Apache
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #33699
| Fixed issue or discussion?     | Fixes #33699
| Related PRs       | 
| Sponsor company   | Profileo

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Comment by MatShir** [comment]
You are targeting develop, it would be nice to have your feature on the 8.1 patch. What do you think ?

**Review by matthieu-rolland — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @maxime-profileo 

Thanks for your PR :rocket: 
The issue related is waiting for Dev to reproduce and validate it! 

Thanks!

**Review by jolelievre — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
I tested this PR, it's all god, QA dev ok 👍

**Review by matthieu-rolland — COMMENTED** [review]
I tested this PR, it's all god, QA dev ok 👍

**Pull request merged**
