### PR TITLE
Better performance in order template

### PR DESCRIPTION
**Pull request by jkfran**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove redundant code.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Compare times when loading an order.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8547)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]
To be confirmed with a Blackfire dump.

**Comment by Quetzacoalt91** [comment]
capture d ecran de 2017-11-28 15-17-12

**Comment by jkfran** [comment]
@Quetzacoalt91 So, it can be merged?  :smile:

**Comment by Quetzacoalt91** [comment]
Indeed. thank you @jkfran

**Pull request merged**
