### PR TITLE
FO: [BOOM-3916] Image slider showing enlarged images

### LINKED ISSUE #9882: [BOOM-3916] Image slider showing enlarged images
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3916).

- _**Reporter:**_ ankur112
- _**Created at:**_ Sat, 30 Sep 2017 13:30:33 +0200

<p>Images get zoomed in the image slider</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by rdy4ever**
Fix/imporvment for #9882

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix/improvement for #9882 + some responsive optimization if module is enabled for mobile
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9882
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10492)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @rdy4ever,

this needs to be rebased and I think @TristanLDD should review this.

Would you mind to add screenshots, please?

Mickaël

**Comment by mickaelandrieu** [comment]
Hello @rdy4ever,

would you mind to add some screenshot so @TristanLDD can review and validate this?

Thanks for your help

**Comment by rdy4ever** [comment]
Hi. Unfortunately I had to delete that repository and installation, so I can no longer provide screenshots or push commits.

**Comment by jolelievre** [comment]
Close this PR for lack of source branch. The modification was ported in this PR https://github.com/PrestaShop/PrestaShop/pull/13072

**Pull request closed without merging**
