### PR TITLE
Removed `pear/archive_tar` dependency

### LINKED ISSUE #24715: Replace `pear/archive_tar` with Phardata
#### Is your feature request related to a problem?

As of PHP 5.3 not needed, see https://stackoverflow.com/questions/9416508/php-untar-gz-without-exec

#### Describe the solution you'd like
...

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed `pear/archive_tar` dependency
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #24715
| How to test?      | Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4374844555
| Possible impacts? | Check that download of language pack always runs well

**:notebook: BC Breaks :**
* Removed method `getLanguagePackListContent` in class `Language`
* Removed `pear/archive_tar` dependency
* Removed method `submitExportLang` in controller `AdminTranslationsController`
* Removed method `submitImportLang` in controller `AdminTranslationsController`
* Removed static method `filterTranslationFiles` in controller `AdminTranslationsController`
* Removed static method `filesListToPaths` in controller `AdminTranslationsController`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28102)

### CODE REVIEW

**Comment by Progi1984** [comment]
**Blocked** : Needs to have the #27912 merged.

**Review by matthieu-rolland — APPROVED** [review]

**Review by matthieu-rolland — DISMISSED** [review]
I "block" the PR until it could be merged

**Comment by matks** [comment]
I'm afraid if we wait for https://github.com/PrestaShop/PrestaShop/pull/27912 to be merged, this is going to take very long

**Comment by Progi1984** [comment]
Finally open to review @PrestaShop/committers and @PrestaShop/prestashop-maintainers

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
Need QA by dev.

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Ok for a QA by dev ?

**Comment by Robin-Fischer-PS** [comment]
OK for QA by dev, thanks for the ping @Progi1984 :)

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-maintainers / @PrestaShop/committers

**Review by FabienPapet — APPROVED** [review]

**Comment by Progi1984** [comment]
Ping @PrestaShop/prestashop-core-developers for QA Dev :)

**Comment by Progi1984** [comment]
Ping @nicosomb ;)

**Comment by Progi1984** [comment]
Go for merge @PrestaShop/committers . The nightly is 🟢

**Comment by jolelievre** [comment]
Thanks @Progi1984

**Pull request merged**
