### PR TITLE
Fix search bar on header when it moves from hook and improve header structure #2

### PR DESCRIPTION
**Pull request by sLorenzini**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Search bar was broken when we add it on displayNavX. Structure of header have been improved to be more flexible
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4306
| How to test?  | Add search bar on displayNav1 and/or displayNav2 hook

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8845)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-:-L7Z039BVn2TqY_Lfy75:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]
Thank you @sLorenzini

**Comment by LittleBigDev** [comment]
:lgtm_cancel: 
See comments

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[themes/classic/_dev/css/theme.scss, line 123 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-L7Z8oluCIBxcQGLALn8:-L7Z8oluCIBxcQGLALn9:b8ikab8) ([raw file](https://github.com/prestashop/prestashop/blob/735972e321ac29c0196897810f7c8005ab217a0f/themes/classic/_dev/css/theme.scss#L123)):*
> ```SCSS
>     }
>     .search-widget {
>       margin-top: 3px;
> ```

Please use `rem` unit to keep consistent with Bootstrap

---

*[themes/classic/_dev/css/theme.scss, line 241 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-L7Z8v25gXpu4WOGUv9i:-L7Z8v25gXpu4WOGUv9j:b8ikab8) ([raw file](https://github.com/prestashop/prestashop/blob/735972e321ac29c0196897810f7c8005ab217a0f/themes/classic/_dev/css/theme.scss#L241)):*
> ```SCSS
>       .search-widget {
>        float: none;
>        width: 250px;
> ```

Please use `rem` unit to keep consistent with Bootstrap

---

*[themes/classic/_dev/css/theme.scss, line 271 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-L7Z8xVlwscI2zadkpu9:-L7Z8xVlwscI2zadkpuA:b8ikab8) ([raw file](https://github.com/prestashop/prestashop/blob/735972e321ac29c0196897810f7c8005ab217a0f/themes/classic/_dev/css/theme.scss#L271)):*
> ```SCSS
>     width: 100%;
>     display: block;
>     max-width: 250px;
> ```

Please use `rem` unit to keep consistent with Bootstrap

---

*[themes/classic/_dev/css/components/search-widget.scss, line 54 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-L7Z8zpmaypRFDA9B2pn:-L7Z8zpmaypRFDA9B2po:b8ikab8) ([raw file](https://github.com/prestashop/prestashop/blob/735972e321ac29c0196897810f7c8005ab217a0f/themes/classic/_dev/css/components/search-widget.scss#L54)):*
> ```SCSS
> @include media-breakpoint-up(md) {
>   .search-widget {
>     min-width: 250px;
> ```

Please use `rem` unit to keep consistent with Bootstrap

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-:-L7Z8g2Z1n1zvz9iPdq9:buvihh1)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
`px` unit should be avoided. Please stay consistent with Bootstrap, using `rem` unit.

**Comment by sLorenzini** [comment]
@LittleBigDev, changes done. Thanks

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8845#-:-L7_CFJ_OgDMIvrtMY-9:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]
Thank you @sLorenzini

**Comment by LittleBigDev** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8845)*

**Review by LittleBigDev — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @sLorenzini

**Pull request merged**
