### PR TITLE
Remove modules catalog controller

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR removes the controller Improve > Modules > Modules catalog
| Type?         | refacto
| Category?     | BO
| BC breaks?    | Controller removed
| Deprecations? | /
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/projects/1#card-10474333 / http://forge.prestashop.com/browse/FF-176
| How to test?  | Install or upgrade your shop, the addons catalog does not exist anymore

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9253)

### CODE REVIEW

**Review by mickaelandrieu — COMMENTED** [review]
Can we do that ? this is a BC :/

**Comment by PierreRambaud** [comment]
Yes, it's on develop, and it's like migrating to Symfony, we always remove the old one. :)

Is it for the MBO @Quetzacoalt91?

**Comment by Quetzacoalt91** [comment]
Yep, the module catalog will be handled by the MBO module.

**Comment by mickaelandrieu** [comment]
Ok but the MBO module must use Symfony, not 1.6 controllers: to be clear on my position, I won't migrate this page again :)

**Review by mickaelandrieu — APPROVED** [review]

**Review by mickaelandrieu — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @Quetzacoalt91

**Pull request merged**
