### PR TITLE
Bump version to 8.1.0

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Bump version to 8.1.0
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A

### CODE REVIEW

**Comment by Progi1984** [comment]
Failed because https://i18n.prestashop-project.org/translations/8.1.0/fr-FR/fr-FR.zip is not available.

@matthieu-rolland Are you always the referent developer on Translations subject ?

**Comment by matks** [comment]
@Progi1984 We're working on making translations available for 8.0

**Comment by matks** [comment]
@Progi1984 I think https://i18n.prestashop-project.org/translations/8.1.0/fr-FR/fr-FR.zip will not be ready before multiple months as our focus is 8.0.0 and not 8.1.0

**Comment by Progi1984** [comment]
@matks No problem. I'm waiting for.

**Comment by Progi1984** [comment]
Moved to #30087

**Pull request closed without merging**
