### PR TITLE
[-] Core: fix ambiguous column name

### PR DESCRIPTION
**Pull request by guestisp**

### CODE REVIEW

**Comment by guestisp** [comment]
There are tons of ambiguous column name, why these erorrs ? Did you change something recently ?
These errors make prestashop unusable

**Comment by jocel1** [comment]
Hi @guestisp ,

An id_product field has been added to product_attribute_shop and image_shop table.
I'll double check all the place where ambiguous column could appear.

Thanks and regards,

**Comment by guestisp** [comment]
@jocel1  Thank you.

**Comment by kpodemski** [comment]
Of course you're right @guestisp

**Comment by jocel1** [comment]
@guestisp I've just pushed a fix.

**Comment by jeromenadaud** [comment]
Hi @guestisp,

Is it ok for you now ?

Best regards.

**Comment by guestisp** [comment]
I'm out of office now, i'll try tomorrow but if you pushed my aliases, should be ok.

**Comment by guestisp** [comment]
@jeromenadaud Your fix is working. Thank you.

**Pull request closed without merging**
