### PR TITLE
Seo preview on category & cms pages

### LINKED ISSUE #13259: Missing SEO previews on migrated pages
**Describe the bug**
Add SEO preview to migrated pages: 
- [x] Catalog > Categories > Add new / edit category https://github.com/PrestaShop/PrestaShop/pull/13132
- [x] Design > Pages > Add new / edit page https://github.com/PrestaShop/PrestaShop/pull/13132

Check what has been done for https://github.com/PrestaShop/PrestaShop/pull/9444

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | See #13259.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13259
| How to test?  | SEO preview is available on category page & cms pages. The behavior must be the same as Product page, and of course the seo component on Product page must work as expected.<br>Assets need to be build

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13714)

### CODE REVIEW

**Comment by matks** [comment]
@PierreRambaud Is it still in WIP ?

**Comment by PierreRambaud** [comment]
@matks Yes

**Comment by PierreRambaud** [comment]
@matks Not WIP anymore, assets not compiled.
Waiting for your feedback

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
> @matks Not WIP anymore, assets not compiled.
> Waiting for your feedback

It's a ✅ !

**Comment by marionf** [comment]
@PierreRambaud 

When I create/edit a category or a cms page, I complete/change the name and the friendly url is automatically completed/changed according to the name. But the URL ins't completed/changed in the SEO preview.

capture d'écran_1512

**Comment by PierreRambaud** [comment]
Nice catch @marionf Should be ok now :)

**Review by jolelievre — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by jolelievre** [comment]
Thank you @PierreRambaud

**Pull request merged**
