### PR TITLE
Lossless compression of all images

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Lossless conpression of all images.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11417)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Saved about 2 MB

**Comment by MathiasReker** [comment]
I tried to fix the conflicts, but I have some troubles with it. Are those images generated? I can't see the conflict.

**Comment by PierreRambaud** [comment]
I like the idea :)
What kind of command do you use to compress file? 
@TristanLDD Can you have a check on these files?

**Comment by MathiasReker** [comment]
@PierreRambaud I use https://nikkhokkho.sourceforge.io/static.php?page=FileOptimizer :)

**Comment by PierreRambaud** [comment]
Good to know :D Waiting for UX designers to have a check if everything is ok. But I totally approve the change!
For public/* images, I don't know if they are generated or not :(

**Comment by MathiasReker** [comment]
It took me 5 hours and 15 min. to scan all files and compress the images. Fileoptimizer uses several image optimization scripts on each file. You can see the list of used scripts in the link just I sent.

**Review by PierreRambaud — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
You should probably avoid committing the files in `admin-dev/themes/new-theme/public/` as they will be replaced with the next assets generation . :)

**Comment by MathiasReker** [comment]
Can they stay for now and just get overrided?

**Comment by Quetzacoalt91** [comment]
As you wish, but you need anyway to solve the conflicts. :)

**Comment by TristanLDD** [comment]
Everything is ok for me !

**Comment by MathiasReker** [comment]
I need help to resolve the conflicts. From my commits, you can see I tried to revert the images caused the conflict, but I had some troubles with it. I can't click the "Resolve conflicts" button. because: "These conflicts are too complex to resolve in the web editor"

**Comment by mickaelandrieu** [comment]
Hello @MathiasReker,

let's do it the easy way, revert changes done in `admin-dev/themes/new-theme/public/` folder, imho the optimizations should be done on this folder using webpack.

Regards,

**Comment by Quetzacoalt91** [comment]
I updated the pull-request to remove the conflicted files and trigger a Travis build. :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by MathiasReker** [comment]
Thanks @Quetzacoalt91 =)

**Comment by Quetzacoalt91** [comment]
Thank you @MathiasReker

**Pull request merged**
