### PR TITLE
Update nginx.conf.dist bug fix 404 error

### PR DESCRIPTION
**Pull request by Giean**
| Questions   |	Answers
|-------------|-----------
| Branch? | 	develop
| Description? |	**Fix problem of URL writing is redirect http to 404 error page**
| Type?  |	Bug Fix
| Category ? |	WS
| BC breaks ? | 	no
| Deprecations | 	no
| Fixed ticket ? |	n/a
| How to test ?| Hi, without this option if we enabled the url writing on the BO. All link of website redirect to 404 error page. I tryed purge cache before modify my nginx vhost this not working. For fix this prob, please add the line on your vhost.  Inside the block server try_files $uri $uri/ /index.php$is_args$args;

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14217)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi,
Can you tell us more where you have the 301 => 404 errors pages?
Please, can you complete the description as @prestonBot ask you? :)
Regards

**Comment by Giean** [comment]
Hi Pierre,

I've complete the decription with contribution table it's ok ?

Kind regards,

**Comment by PierreRambaud** [comment]
By copy paste the example configuration, I'm not able to reproduce.
More the try_files is already present for php files:
https://github.com/PrestaShop/PrestaShop/blob/bb588bc5bd8c034395c720686133e17b04b4c623/docs/server_config/nginx.conf.dist#L168

**Comment by Giean** [comment]
Yes the try_files is already present in the php block, but the function url rewriting it's not working. 
When you click on the all links in the website you are redirect to 404 fatal error page. 

So I added this line **try_files $uri $uri/ /index.php$is_args$args;** in the block server, for it to work.

**Comment by PierreRambaud** [comment]
I tried all link, and everything's working fine. Can you send us your nginx configuration? (even for mods & sites)

**Comment by Giean** [comment]
It's strange, of course !
Here are my configuration files :

- **/etc/nginx/nginx.conf** : https://pastebin.com/fR9SiJ2X
- **/etc/nginx/conf.d/default.conf** : https://pastebin.com/rxJCAqtq
- **/etc/nginx/sites-enabled/defaut.conf** : https://pastebin.com/6xx8B25T

**Comment by PierreRambaud** [comment]
it's because of 
```
server {
    if ($host = www.monndd.fr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
 
 
    if ($host = monndd.fr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
 
 
    listen 80;
    server_name server_name monndd.fr www.monndd.fr;
    return 404; # managed by Certbot
 
}
```
This is where your configuration failed

**Comment by Giean** [comment]
Hi Pierre,
Thank you for your time, I just installed letencrypt. I do not think the problem comes from SSL. Before installing SSL, the problem is already there.

Nginx configuration seems good, I have no errors in the journalctl.

**Comment by PierreRambaud** [comment]
You have a 404 because of this part of code :) it's not related to SSL. 
You say: all http request on port 80 are a 301 to the 404 because of
`server_name server_name monndd.fr www.monndd.fr;`

**Comment by Giean** [comment]
I have try some different tests. Look here :
 
```

server {
     if ($host = www.monsite.fr) {
        return 301 https://$host$request_uri;
     } # managed by Certbot
 
     if ($host = monsite.fr) {
         return 301 https://$host$request_uri;
     } # managed by Certbot
 
     listen 80;
     server_name server_name  monsite.fr www.monsite.fr;
}
```

This not changer, my website is working. So i continued without the 301 redirect to 404 by certbot. I comment my 'fix' try_files $uri $uri/ /index.php$is_args$args;
And the rewriting url it's notworking :( If i uncomment my fix it's working.

**Comment by PierreRambaud** [comment]
I fond what's wrong (I think)
Your `/etc/nginx/conf.d/default.conf just` `include /etc/nginx/sites-enabled/*` which is already done in `/etc/nginx/nginx.conf`. Your configuration look weird :thinking:

**Comment by Giean** [comment]
i desactivated /etc/nginx/conf.d/default.conf
No change..
It's really strange, if I do not add my try_file, it does not work. no matter what configuration is adopted

**Comment by PierreRambaud** [comment]
I think it's specific to your configuration :disappointed:

**Comment by Giean** [comment]
Maybe.. It is possible that you can send me your Nginx configuration (nginx.conf & prestashop.conf) so that I compare my files.

Thank it's for de the science :)

**Comment by PierreRambaud** [comment]
my nginx.conf
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
}

http {

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	gzip on;

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}
```

vhost configuration:
```
server {
	listen 80;
	listen [::]:80;

    server_name ps.localhost;

    root /home/nginx/prestashop/source;

    index index.php;

    # Redirect 404 errors to prestashop
    error_page 404 /index.php?controller=404;

    # Gzip Settings, convert all types.
    gzip on;
    gzip_vary on;
    gzip_proxied any;

    # Can be enhance to 5, but it can slow you server
    # gzip_comp_level    5;
    # gzip_min_length    256;

    gzip_types
        application/atom+xml
        application/javascript
        application/json
        application/ld+json
        application/manifest+json
        application/rss+xml
        application/vnd.geo+json
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/x-web-app-manifest+json
        application/xhtml+xml
        application/xml
        font/opentype
        image/bmp
        image/svg+xml
        image/x-icon
        text/cache-manifest
        text/css
        text/plain
        text/vcard
        text/vnd.rim.location.xloc
        text/vtt
        text/x-component
        text/x-cross-domain-policy;

    gzip_disable "MSIE [1-6]\.(?!.*SV1)";

    # HSTS (Force clients to interact with your website using HTTPS only)
    # For enhanced security, register your site here: https://hstspreload.org/
    # WARNING: Don't use this if your site is not fully on HTTPS!
    # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" preload; always;

    # Cloudflare / Max CDN fix
    location ~* \.(eot|otf|ttf|woff(?:2)?)$ {
        add_header Access-Control-Allow-Origin *;
    }

    # Do not save logs for these
    location = /favicon.ico {
        auth_basic off;
        allow all;
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        auth_basic off;
        allow all;
        log_not_found off;
        access_log off;
    }

    # [REQUIRED EDIT IF MULTILANG]
    # rewrite ^/fr$ /fr/ redirect;
    # rewrite ^/fr/(.*) /$1;

    # Images
    rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
    rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
    rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
    rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
    rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;

    # AlphaImageLoader for IE and fancybox
    rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

    # Web service API
    rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

    # Installation sandbox
    rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;

    # FIX PROBLEM OF URL REWRITING
    try_files $uri $uri/ /index.php$is_args$args;

    # [REQUIRED EDIT] Change this block to your admin folder
    location /admin-dev/ {
        if (!-e $request_filename) {
            rewrite ^/.*$ /admin-dev/index.php last;
        }
    }


    # File security
    # .htaccess .DS_Store .htpasswd etc
    location ~ /\. {
        deny all;
    }
    # Source code directories
    location ~ ^/(app|bin|cache|classes|config|controllers|docs|localization|override|src|tests|tools|translations|travis-scripts|vendor|var)/ {
        deny all;
    }
    # Prevent exposing other sensitive files
    location ~ \.(yml|log|tpl|twig|sass)$ {
        deny all;
    }

    # Prevent injection of php files
    location /upload {
        location ~ \.php$ {
            deny all;
        }
    }
    location /img {
        location ~ \.php$ {
            deny all;
        }
    }

    # PHP FPM part
    location ~ \.php$ {
        # Verify that the file exists, redirect to index if not
        try_files $fastcgi_script_name /index.php$uri&$args =404;

        fastcgi_index  index.php;

        # Environment variables for PHP
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        include       fastcgi_params;

        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_pass unix:/run/php/php7.3-fpm.sock;

        fastcgi_keep_conn on;
        fastcgi_read_timeout 30s;
        fastcgi_send_timeout 30s;

        # In case of long loading or 502 / 504 errors
        # fastcgi_buffer_size 256k;
        # fastcgi_buffers 256 16k;
        # fastcgi_busy_buffers_size 256k;
        client_max_body_size 10M;
    }
}

```

**Comment by PierreRambaud** [comment]
Any news?

**Comment by PierreRambaud** [comment]
No news since one month, I'm closing this PR. 
Hope you find a better way to fix your issue :wink:

**Pull request closed without merging**
