### PR TITLE
Fix a case where shipping cost is always free

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Solves an issue where the shipping was always free. For some reason the sum of shipping remained 0.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/pull/12710
| How to test?  | https://github.com/PrestaShop/PrestaShop/pull/12710

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14626)

### CODE REVIEW

**Comment by MathiasReker** [comment]
I rebased https://github.com/PrestaShop/PrestaShop/pull/12710 and fixed lint issues.

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @MathiasReker 

Can you list the steps to reproduce ?

I didn't reproduce the shipping free 

Thank you for your contribution :)

**Comment by MathiasReker** [comment]
@sarahdib I just rebased this PR: https://github.com/PrestaShop/PrestaShop/pull/12710 I did not test it.

**Comment by sarahdib** [comment]
@MathiasReker oh ok thank you I ask in the other PR :)

**Comment by sarahdib** [comment]
Hello @henkkelder

Since we have not had answer for more than 30 days, I close this PR.
Please before submitting a PR, open an issue to describe the issue and how to reproduce it.

**Pull request closed without merging**
