### PR TITLE
Remove autoload

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated features on v9
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no

### CODE REVIEW

**Comment by nicosomb** [comment]
@FabienPapet I think that you should change the status of this PR, to put it in draft mode. This PR can be merged only after 8.1 release. I know that you set `9.0` for the milestone, but a misclick can happen so fast... 😉

**Comment by FabienPapet** [comment]
tests: https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4084780395

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by FabienPapet** [comment]
Test auto failures unrelated I think. TO be confirmed by QA

**Review by AureRita — APPROVED** [review]
Hi @FabienPapet 

Thank you for this PR, I tested all the test fail on the auto test and it seems to be OK.

**Pull request merged**
