### PR TITLE
CO: CustomerAddressFormCore validation was not working fine with hooks provided by modules

### PR DESCRIPTION
**Pull request by yuxblank**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | CustomerAddressFormCore validation was not working fine with hooks provided by modules for custom validation.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a module with ActionValidateCustomerAddressForm hook that validate one of the form fields. at the submit will be possible to proceed to addresses page which shows the error message set in context-controller.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for your contribution!

Sadly, you now have malformed commits instead of just one commit.

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by Quetzacoalt91** [comment]
Hello @yuxblank,

May I suggest another fix?
When trying your reported bug, I succeeded to reproduce it.
However, I think these changes are not the best way to handle it. Basically, I do not see how changing the order of the validation may impact the final result.

If any of the step is `false`, the result will be `false`. And both `parent::validate()` and `Hook::exec()` will be executed whatever happens in the context. Running in first or last step brings the same result.

I suggest in #8230 to return the hook result as an array, and handle each element as a boolean. Then, we use the operand `&` between each module response to get the global hook result.

**Comment by yuxblank** [comment]
@xBorderie i tried to squash but following the guide you posted but i wasn't able to produce the result expected. Can you kindly give support? (i'm a newbie with git)

@Quetzacoalt91 
I'm not a big fan of function returning different types of values (and php 7.0 return type will not work that way) .
It's not about change the order of execution, but using AbstractForm::validate method to provide validation for each form.
in that way the validation of the form is done after hook, so if any hook invalidate the form the result will be false.
But maybe i just don't get your point. Please let me know

In this way we can handle validation from hooks in this way:

```php    public function hookActionValidateCustomerAddressForm($params)
    {
        /** @var CustomerAddressForm $form */
        $form = $params['form'];
        $field= $form->getField("fieldname") ? $form->getField('fieldname')->getValue() : null;
        if (!$this->validateModuleHookFunction($field)) {
            $form->getField('fieldname')->addError($this->l('Invalid field label'));
        }
    }
```
So we can handle field validation on the actual form object, instead of [#8230](https://github.com/PrestaShop/PrestaShop/pull/8230) where you return just a boolean from the hook.
So "Core" classes can always been specialized with additional validators agents thus reflecting to all modules.

**Comment by yuxblank** [comment]
Im closing the pull. I will open another one but well formed.

**Pull request closed without merging**
