### PR TITLE
Fix bullets of bulleted lists being removed by default

### LINKED ISSUE #16333: Bullets of bulleted lists are removed by default
By default, PrestaShop changes the behaviour of bulleted lists by removing the bullets:
https://github.com/PrestaShop/PrestaShop/blob/4f5d70f1ae3a9ceb5251a850551e79d8ff62a0d7/themes/classic/_dev/css/partials/_commons.scss#L14-L17

So, every time I make a bulleted list, I don't have the bullets, and that's quite annoying. Would it be possible to remove this piece of code from the default theme?

If we want a list of "unbulleted" items, we could use multiple `<div>` or add a class like `list-unstyled` to the `<ul>`.

### PR DESCRIPTION
**Pull request by rdy4ever**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As per #16333, bullets for lists are removed by default globally. But they are actually needed in cms pages.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16333
| How to test?  | **How to test ?**<br>* Add a bulleted list to a cms page.<br>**Result :**<br>This is before:<br>image<br>This is after:<br>image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16340)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@rdy4ever Thank you for your contribution. Could you give a test scenario and/or a screen before ?

**Comment by rdy4ever** [comment]
> @rdy4ever Thank you for your contribution. Could you give a test scenario and/or a screen before ?

Hi @Progi1984 
Sure. Add a bulleted list to a cms page.
This is before:
image
This is after:
image

**Comment by Progi1984** [comment]
@rdy4ever Thanks. I send it to QA Team for testing.

**Review by PierreRambaud — APPROVED** [review]
Approved, but I add a `Waiting for UX` to be sure @TristanLDD is ok :)

**Comment by yannicka** [comment]
Would it be possible to have bulleted lists on the pages too?

See my comment: https://github.com/PrestaShop/PrestaShop/issues/16333#issuecomment-552094913

**Comment by TristanLDD** [comment]
Good for me!

**Comment by Progi1984** [comment]
Thanks @rdy4ever

**Pull request merged**
