### PR TITLE
Type hint front controllers

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Adds type hints for some front controller functions.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI 🟢 and automatic tests 🟢 no more tests required
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by boherm — DISMISSED** [review]
LGTM, thanks @Hlavtox!
No really need a QA on this I think, but only autotests?

**Comment by hibatallahAouadni** [comment]
Ping @Hlavtox could you please provide the "how to test" 🙏 
Thanks in advance!

**Comment by kpodemski** [comment]
@hibatallahAouadni auto tests should be more than enough

**Comment by kpodemski** [comment]
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5308947964

**Comment by hibatallahAouadni** [comment]
@kpodemski Ok that's great! But it seems there's some failed auto tests 😞 on BO, did you update your test repo? And when you launch the auto test, did you choose rebase or pull?

**Review by kpodemski — CHANGES_REQUESTED** [review]
some conflicts happened

**Comment by Hlavtox** [comment]
@kpodemski Done, can you relaunch the auto tests please? :-)

**Review by boherm — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5375893372

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

The auto tests are still failing : https://github.com/florine2623/testing_pr/actions/runs/5378376962

I have the same result as @kpodemski .

Could you check ?
Thanks!

**Comment by kpodemski** [comment]
@Hlavtox could you rebase?

**Comment by jolelievre** [comment]
One question about this modification @Hlavtox 

It means that ALL the modules will have to update their front controller so that the modified functions match the same prototype right? Meaning that their module once modified won't be compatible with previous PrestaShop versions and so they will have to handle two versions of their module depending on the PrestaShop version?

I'm not against it but in many changes we made on the BO side we tried to limit the impact so that modules can remain as compatible as possible across versions. But if we start doing this kind of change our effort are useless on the BO side and we could start doing more in-depth modifications I guess 😅

**Comment by kpodemski** [comment]
@jolelievre we recently removed `Tools::displayPrice` and a bunch of other crucial things, there will be a new theme for PrestaShop 9, PHP 8.2 compat required, etc., etc. 

Also, the impact is limited there. ModuleFrontController will have to adapt to the new `canonicalRedirection`, and there will be an impact for overrides.

**Comment by kpodemski** [comment]
What I'm trying to say is that we need to agree on whether we improve what we can, or we are limiting the scope of the version to have less painful upgrades.

**Comment by Hlavtox** [comment]
@jolelievre @kpodemski Following some DMs and testing, this is the situation about BC breaks. I think it should be OK.

- Given `FrontController::protected function canonicalRedirection(string $canonical_url = '')`
- If module front controller is untyped `public function canonicalRedirection($canonicalURL = '')`, it works fine.
- If it is typed differently, it results in `Fatal error: Declaration of YourModuleTestModuleFrontController::canonicalRedirection(array $canonicalURL) must be compatible with FrontControllerCore::canonicalRedirection(string $canonical_url = '')`
- If some module called some front controller method via $context->controller or by creating an instance of it with a wrong type, it will only stop the error sooner.

**Comment by jolelievre** [comment]
Ok great then the impact is minimum as the module don't need to change anything and they can remain compatible with all versions

**Comment by kpodemski** [comment]
Auto tests:
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5490359388

**Review by MhiriFaten — COMMENTED** [review]
Hello @Hlavtox ,

The auto tests always fail 
**link :** https://github.com/MhiriFaten/testing_pr/actions/runs/5506178938
same result as @kpodemski  in his last auto test 3 days ago https://github.com/PrestaShop/PrestaShop/pull/32846#issuecomment-1626058315

Could you rechecked it please ?

**Comment by kpodemski** [comment]
@Hlavtox I guess you need to rebase your PR 🤷🏻

**Comment by Hlavtox** [comment]
@kpodemski Rebased 👍

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
Auto-tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5507443110

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
New auto-tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5507590138

**Review by kpodemski — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @Hlavtox 
[Auto Tests](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5517036150) are not OK

image

Please check and feedback ! 

Thank you  !

**Comment by kpodemski** [comment]
@sallemiines it's ok on my tests:
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5507590138

**Pull request merged**
