### PR TITLE
Make cURL a requirement

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | `develop` |
| Description? | Make `cURL` a requirement, since it is needed by core libraries. |
| Type? | bug fix |
| Category? | IN |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Can you point the library that requires curl?

**Comment by kpodemski** [comment]
Guzzle?

**Comment by kpodemski** [comment]
Oh, ok, no longer needed

**Comment by firstred** [comment]
I thought that it was necessary to update Guzzle to a version that supports 5.4 - 7.1 and this one required cURL.

But it looks like it is only a dev requirement: https://packagist.org/packages/guzzlehttp/guzzle

**Pull request closed without merging**
