### PR TITLE
Prestashop 1.7.4.1 PHP 7.2 compatibility for GamificationTools.php

### PR DESCRIPTION
**Pull request by Pharaoh2k**
To avoid errors in admin, the following code must be changed for php 7.2 compatibility, as it throws deprecated notices for create_function:
```
        $content = preg_replace_callback('#\{config\}([a-zA-Z0-9_-]*)\{/config\}#', create_function('$matches', 'return Configuration::get($matches[1]);'), $content);
        $content = preg_replace_callback('#\{link\}(.*)\{/link\}#', create_function('$matches', 'return Context::getContext()->link->getAdminLink($matches[1]);'), $content);
        $content = preg_replace_callback('#\{employee\}(.*)\{/employee\}#', create_function('$matches', 'return Context::getContext()->employee->$matches[1];'), $content);
        $content = preg_replace_callback('#\{language\}(.*)\{/language\}#', create_function('$matches', 'return Context::getContext()->language->$matches[1];'), $content);
        $content = preg_replace_callback('#\{country\}(.*)\{/country\}#', create_function('$matches', 'return Context::getContext()->country->$matches[1];'), $content);
```

To:
```
        $content = preg_replace_callback('#\{config\}([a-zA-Z0-9_-]*)\{/config\}#', function($matches) { return Configuration::get($matches[1]); }, $content);
        $content = preg_replace_callback('#\{link\}(.*)\{/link\}#', function($matches) { return Context::getContext()->link->getAdminLink($matches[1]); }, $content);
        $content = preg_replace_callback('#\{employee\}(.*)\{/employee\}#', function($matches) { return Context::getContext()->employee->$matches[1]; }, $content);
        $content = preg_replace_callback('#\{language\}(.*)\{/language\}#', function($matches) { return Context::getContext()->language->$matches[1]; }, $content);
        $content = preg_replace_callback('#\{country\}(.*)\{/country\}#', function($matches) { return Context::getContext()->country->$matches[1]; }, $content);
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9363)

### CODE REVIEW

**Comment by Pharaoh2k** [comment]
Kindly look at my pull request. It is already very clear.
Thanks

On 23/07/2018 02:10, Preston wrote:

Hi!

Your pull request description seems to be incomplete or malformed:

  *   The description shouldn't be empty.
  *   The type should be one of: new feature, improvement, bug fix, refacto or critical.
  *   The category should be one of: FO, BO, CO, IN, TE, WS, LO

Would you mind completing the contribution table ? This would help us understand how interesting your contribution is.

Thank you!

(note: this is an automated message, but answering it will reach a real human )

**Comment by PierreRambaud** [comment]
Hi,

When you create a Pull Request, there's a markdown table you must complete. That's why preston is disturbing :P

More  in your PR, there's no commit from you because you target the wrong branches `wants to merge 86 commits into develop from 1.7.4.x`, you must use your fork's branch and follow this:

```
Use the "develop" branch if you target the next major version of PrestaShop 1.7, "1.7.4.x" for 1.7 bug fixes, and "1.6.1.x" for PrestaShop 1.6 (bugfixes only).
```

Regards

**Comment by doclucas** [comment]
Pierre, I really have no idea about how github pulls work and no time to learn now. Thanks for the info tho.
The corrections are still valid and required, if you want your code to be php 7.2 as PS claims it is.
Thus, please feel free to post these where and the way they should be posted on my behalf. Feel free to take credit for them as well, no problem, I just want to help improve the code. :)

Thanks

**Comment by PierreRambaud** [comment]
We will fix everything about create_function in the next release, I close this one ;)

Thanks for the feedback.

**Pull request closed without merging**
