### PR TITLE
Add dd() function

### LINKED ISSUE #25585: Please provide a dd() (“dump and die”) helper function
#### Is your feature request related to a problem?
NO

#### Describe the solution you'd like

Thanks to symfony we already can use `dump()` helper function in prestashop. 
But symfony VarDumper component provides dd() helper function as well, which is very handy.
Why not to add it to prestashop?

### PR DESCRIPTION
**Pull request by andreapozza**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | Add Symfony's dd function, alias of dump and die.
| Type?             | new feature 
| Category?         | CO / Developer feature
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Just try to use instead of `dump($foo); exit;`
| UI Tests          |  -
| Fixed issue or discussion?     | Fixes #25585
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello @andreapozza 

I've checked on the develop branch and `dd` function is available and you can use it. There is no need to add it to the `alias.php` file.

**Comment by andreapozza** [comment]
Hi @kpodemski 

I read that it is available in develop branch, but usually when debugging issues I need that function in production releases as well. In `config/alias.php` it is already present a dump function declaration and I supposed that dd could be useful.

**Comment by kpodemski** [comment]
@andreapozza it is on the `develop` branch meaning that in the next version (v9) is available in both, production and developer environment

**Comment by andreapozza** [comment]
Oh super! Sorry for the loss of time

**Comment by kpodemski** [comment]
@andreapozza, no worries!!! thanks for contributing! 💪🏻

**Pull request closed without merging**
