### PR TITLE
Adjust notifications pan on mobile

### LINKED ISSUE #22514: [RESPONSIVE - BO] Notification window modal can't be closed on migrated pages
#### Describe the bug

When you open notification modal, you see this :

image

#### Expected behavior

I would suggest as a quickwin to just add a small margin like this :

image

#### Steps to Reproduce

1. Go to Orders page
2. Click on Notification icon on the left on mobile

#### Additional information

* PrestaShop version: develop

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Notification pan was unusable on mobile, We adjusted font size, colors, width and height
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22514.
| How to test?      | Check issue, some differences can happen because of the existing, don't worry

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22519)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !!
Tested on browserstack with chrome
**before**
image
**after**
image
And on firefox (not with browserstack)
**before**
image
**after**
image

Thanks @NeOMakinG

**Comment by atomiix** [comment]
Thanks @NeOMakinG & @SD1982

**Comment by prestascott** [comment]
Hello everyone,

I just tested the PR and there is still a tiny little bug.

On legacy pages:
• The indicator under the notification icon is still displayed when the profile is selected.
Capture d’écran 2021-02-25 à 17 27 57

Also, I found out that the wording used was different between legacy pages and migrated ones. 
Wording on legacy pages:
Capture d’écran 2021-02-25 à 17 28 01

Wording on migrated pages:
Capture d’écran 2021-02-25 à 17 27 52

Which wording should we keep? @Julievrz

**Comment by Julievrz** [comment]
Hi @prestascott 
Following your comment, I discovered something weird with this wording: it is always changing! I don't know if it is the desired behavior. I noticed that I had a different wording on my store. I tried to log out and log in again and the wording was again different. When you browse the BO, the wording changes too depending on which page you are on. 

image
image

**Comment by NeOMakinG** [comment]
@Julievrz I think it's only because of the context : on legacy pages, it's an old wording, on migrated pages it's another wording, isn't it ?

**Comment by Julievrz** [comment]
@NeOMakinG Well, I don't know because when I log out and log in again, I'm on the same page and the wording changes anyway.

**Comment by NeOMakinG** [comment]
What a strange behavior then, but we can harmonize all these wordings

**Comment by prestascott** [comment]
@Julievrz I can see that the wording is clearly different depending on what page users are. This is an unwanted behavior because notifications pan's content should be the same with the same wording. Otherwise it's confusing... I agree with @NeOMakinG, we really need to harmonize all these wordings by keeping it simple without the word "new":
- Orders
- Customers
- Messages

And use "No new order for now :( Have you checked your **abandoned carts**? Your next order could be hiding there!" because we're helping merchants to find where they might missed something. It's important to redirect users to a potential solution rather than just text. At least, they know where they can possibly fix the issue.

Wdyt?

**Comment by Julievrz** [comment]
Hi @prestascott @NeOMakinG 
I agree that the wording should be harmonized. Should we open a new issue for that?

**Comment by NeOMakinG** [comment]
@Julievrz if possible yes, including @prestascott feedbacks

**Pull request merged**
