### PR TITLE
[*] CORE : readability improvement

### PR DESCRIPTION
**Pull request by webmake**
Promised changes of improvement in readability, by inverting conditions and exiting early

### CODE REVIEW

**Comment by gskema** [comment]
Did you check the changes against PSR-2 standard?

**Comment by webmake** [comment]
@gskema which one rule was violated against psr standards? I thought left better code that I found it before :) Also my IDE is configured to use psr1/psr2 standards.
I didn't started to refactor more, because it doesn't give more valuable worth, that it coud give now for readability, without any logic break. ["200lines per class (including docblocks), 10methods per class, 15classes per namespace (folder)" (49th slide)] (http://www.slideshare.net/chadwick0678/getting-your-code-into-shape-with-object)

**Comment by mickaelandrieu** [comment]
Hi @webmake,
the best tool to check if your code is PSR-2 compliant is [PHP-CS-Fixer] (http://cs.sensiolabs.org/).

After installation you can do:

```bash
php-cs-fixer fix controllers/admin/AdminModulesController.php
```

Mickaël

**Comment by xBorderie** [comment]
Hi @webmake !
Great PR! Sadly, the AdminModuleManager has been heavily reworked these past days, and most of your changes are not applicable anymore.
Since that work on your side is still ongoing, and because your PR cannot merge anymore because of the conflicts, I have to close your PR. Sorry for this!
if you wish, I can let you know once the work on AdminModuleManager is done, so that you can explore it again with your ideas from this PR? Let me know: xavier@prestashop.com
Again, sorry to close this PR, but we don't really have a choice.
Thank you for contributing!

**Pull request closed without merging**
