### PR TITLE
Refactored $form declare

### PR DESCRIPTION
**Pull request by nicolas-wallerand**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Use the "develop" branch if you target PrestaShop 1.7; use the "1.6.1.x" branch if you target PrestaShop 1.6 (bugfixes only).
| Description?  |refactor variable
| Type?         | refactor
| Category?     | BO 
| BC breaks?    | no
| Deprecations? |no 
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
> Note: this must be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface! :)

**Comment by nicolas-wallerand** [comment]
Yes but I did the modification from the github interface

**Comment by mickaelandrieu** [comment]
@nicolas-wallerand sadly, as we said you can't update a commit label from GitHub interface.

capture

2 choices:

* use git from a command line interface
* re-create a pull request with a valid commit label

Mickaël

**Comment by maximebiloe** [comment]
Hello @nicolas-wallerand,

Without an answer from you, I close this PR.
Feel free to open a new one respecting our standards.

Regards

**Pull request closed without merging**
