### PR TITLE
Remove deprecated OrderDiscount model

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated OrderDiscount model
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed class : `OrderDiscount`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28193)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @PrestaEdit

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I think executing the automated full suite could be a good idea.

**Review by HanaRebaiQA — APPROVED** [review]
Hello @PrestaEdit 

I just runned the automated tests, they are OK :heavy_check_mark: 

So, it's QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @PrestaEdit & @HanaRebaiQA

**Comment by matks** [comment]
@Progi1984 If there is a BC break, don't forget to add the "Needs documentation" label 😉

**Pull request merged**
