### PR TITLE
[*] Controller: Cart / hook "actionAfterDeleteProductInCart"

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by SebSept** [comment]
I think the hookname is not correct.

Most of hook name are <action|display><Object><Action|State>[<After>]

So this should should better be named `actionCartProductRemovedAfter` (or something close to that).

**Comment by gskema** [comment]
I think `actionCartProductRemoveAfter` would be the best.

**Comment by SebSept** [comment]
:+1: @gskema

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution.

Best regards.

**Pull request merged**
