### PR TITLE
[-] CORE: Fix redirect headers. RFC2616#sec10.3.2

### PR DESCRIPTION
**Pull request by guestisp**
Fix redirect headers following RFC2616#sec10.3.2

### CODE REVIEW

**Comment by guestisp** [comment]
There is also another bug. This force a redirect to an `http` resource. What if shop is running in `https` ?

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. You are taking the value for ssl enabled but you do not know the shop protocol and you do not know if ssl is enabled on all pages.

Just add in your PR the RFC compliancey please. Redirection to https is handled afterward.

Regards

**Comment by guestisp** [comment]
Revert done.

**Comment by gRoussac** [comment]
Thank you.

Regards

**Pull request closed without merging**
