### PR TITLE
Fix product page blocks spacing

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix spacings
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Check with design team

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]
:ok_hand: for me

**Comment by Quetzacoalt91** [comment]
@TristanLDD, I suppose your also review is requested on this one? Or this is only for @vincentbz?

**Comment by TristanLDD** [comment]
@Quetzacoalt91 I've checked the changes with Nico so it's ok for me !

**Comment by Quetzacoalt91** [comment]
Perfect, thank you

**Comment by vincentbz** [comment]
Two tabs were missing : combinations details and quantities.

**Pull request merged**
