### PR TITLE
[-] CORE : #PSCSX-6814 fixed a bad written SQL query

### PR DESCRIPTION
**Pull request by bertuz**
(it can generate an error when importing a new language and updating the _lang tables)

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.

Error execpted you forgot an backquote in the begining of $fields, it produces on my test an SQL statement like for instance 

```
INSERT IGNORE INTO `ps_advice_lang` (id_advice`, id_lang`, html`) (SELECT 
```

then you are using retrim with '`, ', wich can lead to troubles as this will not replace the expression "'`, '" but it will search every caracters here, not the expression. Here it is fine but this may lead to troubles in PHP and I see no change with $fields = rtrim($fields, ', ');

Last little thing your seem to hav a issue with indentation on line 453. 

I believe you just wanted to commit 

```
 $fields .= '`'.$column['Field'].'`, ';
```

Best regards

**Comment by gRoussac** [comment]
I made a PR, no need to report on develop this will be merged later so please close https://github.com/PrestaShop/PrestaShop/pull/3978

https://github.com/PrestaShop/PrestaShop/pull/3987/files

Best regards

**Comment by bertuz** [comment]
I guess your PR #3978 will be more than enough, so we should close this one as well then. Let me know if you want me to close.

Bests

**Comment by gRoussac** [comment]
Thank you for your help.

**Pull request closed without merging**
