### PR TITLE
[-] FO VAT field is show when change country

### PR DESCRIPTION
**Pull request by prestarocket**
Step to reporduce the bug
if you have 2 addresses : one with vat applicable and one with vat not applicable (ex : France and USA) :
- leave blank company input
- choose country with vat applicable
- choose country with vat not applicable
- choose country with vat applicable => vat input is shown

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, what append if company field is filled after country change ?
We will ask our @PrestaShop/prestashop-product-managers  about this change.

Best regards

**Comment by prestarocket** [comment]
if company field is filled after country change, no bug, it's managed by vatManagement.js.

**Comment by jeromenadaud** [comment]
Oh yes you are right.
Thank you. Merged !

**Comment by prestarocket** [comment]
you are welcome ! ;)

**Pull request merged**
