### PR TITLE
Minor Module performance fixes

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR contains minor performances on modules.
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?     | This PR improves performance when loading the modules list in back-office page Module Manager. The list should work as expected however `getModule`function should be a little faster than usual

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

Only the `How to test` section is missing in the description, how do you suggest this should be tested/validated? Should we run the full automatic campaign? Test some module installation, module update?

Does this impact the module actions (install/enable/...) or the hole module execution?

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Ping @FabienPapet - QA team or dev QA could use some "How to test"

**Comment by FabienPapet** [comment]
Updated how to test

**Comment by sLorenzini** [comment]
hello @FabienPapet,

Thank you for this PR.
There is no fixed ticket linked to this PR and "How to test" section is too small to test correctly this one.
Could you link an issue or at least describe with more detail in "How to test" section please 🙏?  

Waiting for your feedbacks 😉 

Thanks

**Comment by matks** [comment]
@FabienPapet I think this "How to test" is too light ^^ 

I suggest to go a bit farther:
> How to test?
> This PR improves performance when loading the modules list in back-office page Module Manager. The list should work as expected however {...} should be a little faster than usual

I need you to complete the `{...}` 😉 

Even if between QA people and developer people we quite know each other, remember that in theory Pull Requests should be readable by anybody for transparency. Accurate description of changes and how to test help someone else to test your branch, suggest improvements and look for issues.

**Comment by FabienPapet** [comment]
This is a performance pull request, the edited function is getModule which is called on the module list. There is nothing more to say... Perhaps should've written "test the whole module system and see if it breaks ... ".

Unit tests should be sufficient on this one

**Comment by kpodemski** [comment]
Seems good to me, and tests have already handled some of the changes.

**Comment by kpodemski** [comment]
Thanks @FabienPapet

**Pull request merged**
