### PR TITLE
Speed up search queries

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | speed up search queries
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Execute search with a lot of products

### CODE REVIEW

**Comment by jocel1** [comment]
Test on a real DB, with a lot of matching products:

```sql
SELECT p.*, product_shop.*, stock.out_of_stock, IFNULL(stock.quantity, 0) as quantity, pl.`description_short`, pl.`available_now`, pl.`available_later`, pl.`link_rewrite`, pl.`name`,  image_shop.`id_image` id_image, il.`legend`, m.`name` manufacturer_name ,( SELECT SUM(weight) FROM ps_search_word sw LEFT JOIN test.ps_search_index si ON sw.id_word = si.id_word WHERE sw.id_lang = 2 AND sw.id_shop = 1 AND si.id_product = p.id_product AND (sw.word LIKE '%han%') ) position, DATEDIFF( p.`date_add`, DATE_SUB( "2017-07-21 00:00:00", INTERVAL 30 DAY ) ) > 0 new, product_attribute_shop.minimal_quantity AS product_attribute_minimal_quantity, IFNULL(product_attribute_shop.`id_product_attribute`,0) id_product_attribute FROM ps_product p  INNER JOIN ps_product_shop product_shop ON (product_shop.id_product = p.id_product AND product_shop.id_shop = 1) INNER JOIN `ps_product_lang` pl ON ( p.`id_product` = pl.`id_product` AND pl.`id_lang` = 2 AND pl.id_shop = 1  ) LEFT JOIN `ps_product_attribute_shop` product_attribute_shop ON (p.`id_product` = product_attribute_shop.`id_product` AND product_attribute_shop.`default_on` = 1 AND product_attribute_shop.id_shop=1)  LEFT JOIN ps_stock_available stock ON (stock.id_product = p.id_product AND stock.id_product_attribute = 0 AND stock.id_shop_group = 1  AND stock.id_shop = 0  ) LEFT JOIN `ps_manufacturer` m ON m.`id_manufacturer` = p.`id_manufacturer` LEFT JOIN `ps_image_shop` image_shop ON (image_shop.`id_product` = p.`id_product` AND image_shop.cover=1 AND image_shop.id_shop=1) LEFT JOIN `ps_image_lang` il ON (image_shop.`id_image` = il.`id_image` AND il.`id_lang` = 2) WHERE p.`id_product`  IN ([lots of ids])  GROUP BY product_shop.id_product ORDER BY  position desc LIMIT 0, 10;
```

Before the fix:
10 rows in set (2 min 1.31 sec)
After the fix:
10 rows in set (20.38 sec)

**Comment by xBorderie** [comment]
tumblr_newoyhbf7q1sr0pqfo1_500

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by maximebiloe** [comment]
Hi @jocel1,

Can you squash your two commits, please?

Thanks

**Comment by jocel1** [comment]
@maximebiloe Why not using the squash & merge feature of github ?

**Comment by maximebiloe** [comment]
Because we lose the merge commit with this feature. It will commit directly to the branch.

**Comment by jocel1** [comment]
ah good to know, I'll do the squash then

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @jocel1

**Comment by hakeryk2** [comment]
So easy, yet so effective.

**Pull request merged**
