### PR TITLE
Add the Bug Bounty Program in SECURITY.md

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve Security.md file.
| Type?         | improvement
| Category?     | PM
| BC breaks?    | no
| Deprecations? | no
| How to test?  | No need QA.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20291)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by PululuK** [comment]
Guys, It's not enough to get rich I think  😅 I am very discouraged 😪
image

Could you specify here https://yeswehack.com/programs/prestashop under which criteria they are classified as a : `LOW`, `MEDIUM`, `HIGHT` or `CRITICAL` ?

**Comment by matks** [comment]
> https://yeswehack.com/programs/prestashop

I think it's CVSS3 scores https://www.first.org/cvss/specification-document

**Comment by matks** [comment]
Thank you @PierreRambaud

**Comment by PierreRambaud** [comment]
> Guys, It's not enough to get rich I think  I am very discouraged 
> image
> 
> Could you specify here https://yeswehack.com/programs/prestashop under which criteria they are classified as a : `LOW`, `MEDIUM`, `HIGHT` or `CRITICAL` ?

I confirm it depends on the CVS score :wink:

**Pull request merged**
