### PR TITLE
[WIP] UI tests for stock counter - create order page BO 

### PR DESCRIPTION
**Pull request by arouiadib**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | Create UI tests for the stock counter in "Create order page" in BO. https://github.com/PrestaShop/PrestaShop/pull/18510
| Type?         | TE 
| Category?     |  TE 
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | 
| How to test?  | TEST_PATH="sanity/03_ordersBO/03_createOrder.js" URL_FO="http://localhost/prestashop/" npm run specific-test

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19433)

### CODE REVIEW

**Comment by SimonGrn** [comment]
Hey, that's a good template you got there :)
We're very happy to see you taking interest in UI tests. Don't hesitate to ping the qa automation team @boubkerbribri @nesrineabdmouleh and myself) if you need info or help !

**Comment by matks** [comment]
@arouiadib Impressive !

**Comment by PierreRambaud** [comment]
Hi @arouiadib 
Are you still working on it? (we are sorry for the delay, thought people already reviewed it :( )

**Comment by arouiadib** [comment]
@PierreRambaud Yes.
This time I should finalize it to detect future regressions using tests instead of manual testing.

Thanks for your time @PierreRambaud

**Comment by arouiadib** [comment]
I don't feel it is good to continue on 1.7.7.x
Also, moving to 1.7.8.x gives a lot of conflicts (also develop).

I close this to make a new one on 1.7.8.x.

Thanks.

**Comment by PierreRambaud** [comment]
> I don't feel it is good to continue on 1.7.7.x
> Also, moving to 1.7.8.x gives a lot of conflicts (also develop).
> 
> I close this to make a new one on 1.7.8.x.
> 
> Thanks.

I recommend you to do it on the develop branch instead :+1:

**Pull request closed without merging**
