### PR TITLE
Remove unused parameters from Tools::addonsRequest()

### LINKED ISSUE #24740: Remove Tools::addonsRequest('partner') calls
#### Is your feature request related to a problem?

Remove all calls related to `Tools::addonsRequest('partner')` 

#### Describe the solution you'd like

Remove all calls, and if needed backports changes into ps_mbo module

### LINKED ISSUE #24741: Remove Tools::addonsRequest('service') calls
#### Is your feature request related to a problem?

Remove all calls related to `Tools::addonsRequest('service')` 

#### Describe the solution you'd like

Remove all calls, and if needed backports changes into ps_mbo module

### LINKED ISSUE #24744: Remove Tools::addonsRequest('must-have-themes') calls
#### Is your feature request related to a problem?

Remove all calls related to `Tools::addonsRequest('must-have-themes')` 

#### Describe the solution you'd like

Remove all calls, and if needed backports changes into ps_mbo module

### LINKED ISSUE #24747: Remove Tools::addonsRequest('customer_themes') calls
#### Is your feature request related to a problem?

Remove all calls related to `Tools::addonsRequest('customer_themes')` 

#### Describe the solution you'd like

Remove all calls, and if needed backports changes into ps_mbo module

### LINKED ISSUE #24751: Remove Tools::addonsRequest('hosted_module') calls
#### Is your feature request related to a problem?

Remove all calls related to `Tools::addonsRequest('hosted_module')` 

#### Describe the solution you'd like

Remove all calls, and if needed backports changes into ps_mbo module

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed unused requests from `Tools::addonsRequest()`
| Type?             | new feature
| Category?         | CO
| BC breaks?        | yes - The option is no longer available
| Deprecations?     | no
| Fixed ticket?     | Fixes #24740, fixes #24741, fixes #24744, fixes #24747, fixes #24751
| How to test?      | Nothing to test
| Possible impacts? | Calls to `Tools::addonsRequest()` using any of the removed values listed above will return `false`.

I wasn't able to find any calls to the following requests in the Core, MBO or any of the native modules:

- Tools::addonsRequest('partner')
- Tools::addonsRequest('service')
- Tools::addonsRequest('hosted_module')
- Tools::addonsRequest('must-have-themes')
- Tools::addonsRequest('customer_themes')
- Tools::addonsRequest('native_all')

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25714)

### CODE REVIEW

**Comment by Progi1984** [comment]
@eternoendless Look for `'partner'` ;)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by eternoendless** [comment]
FYI even if the keys can be found they are unrelated, because I made sure that there were no dynamic method calls to addonsRequest first.

The only call to `addonsRequest($` is the method definition, so we can rule off cases of `addonsRequest($theRequest)`

Screenshot 2021-08-26 at 17 29 01

There can't be any dynamic method calls to addonsRequest (e.g. using `call_user_func()`) because no string starting with it exists in the codebase:

Screenshot 2021-08-26 at 17 30 04

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by eternoendless** [comment]
Tests are green - this is good for merge, right?

**Comment by Progi1984** [comment]
@eternoendless Have you moved the removed code to MBO ?

**Comment by PierreRambaud** [comment]
> @eternoendless Have you moved the removed code to MBO ?

I'll do it, a lot of refactoring has to be done (and in progress) for MBO.

**Comment by PierreRambaud** [comment]
Thank you @eternoendless

**Pull request merged**
