### PR TITLE
Upgraded symfony packages

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Upgrades to symfony 4.4.50
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See tests launched below
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | PrestaShop

### CODE REVIEW

**Comment by nicosomb** [comment]
Tests launched here: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4068453690

**Comment by nesrineabdmouleh** [comment]
> Tests launched here: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4068453690

Thank you @nicosomb for the PR and for the launch of UI tests !

I confirm that the red tests are not related to the PR :)

**Review by lartist — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @nicosomb

**Review by jolelievre — CHANGES_REQUESTED** [review]
Seems like just changin the branch was not enough, you are incorporating changes from develop into the 8.1.x branch with this PR

You need to rebase your branch, or create a new one based on 8.1.x

**Pull request closed without merging**
