### PR TITLE
[-] FO : Fix #PSCSX-5573, could not change HOOK_SHOPPING_CART_EXTRA

### PR DESCRIPTION
**Pull request by Shagshag**
better approach than da33b69fee31aefaf2d934626c280b48bb120b99

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you, I think it is pretty much the same. @jeromenadaud will merge yours if you want, no problem.

Best regards

**Comment by Shagshag** [comment]
Hi,

it the same, just a different approach, <div id="HOOK_SHOPPING_CART_EXTRA"> need to exist whatever $HOOK_SHOPPING_CART_EXTRA is, so the test should not include the div.

Regards

**Comment by gRoussac** [comment]
No problem as soon as the isset test is kept.

Thank you. Regards

**Comment by gRoussac** [comment]
@Eolia, I assure you you are missing the point here. Please read the corresponding bug track.

This is a small change, no use to start a battle on that.

Regards

**Comment by jeromenadaud** [comment]
Hi, 

Thank you for your contribution.

Best regards.

**Pull request merged**
