### PR TITLE
Fix typo in download_product.txt

### LINKED ISSUE #9785: [BOOM-4488] Downloadable product email: Typos in template variables
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4488).

- _**Reporter:**_ ckubitza
- _**Created at:**_ Fri, 15 Dec 2017 10:08:38 +0100

<p>In mails/en/download_product.txt, wrong template variables are used so especially the download link does not appear.</p>

<p>It has to be "{nbProducts}" instead of "{nbproducts}" and "{virtualProducts}" instead of "{virtualproducts}"</p>

<p> </p>
        
* How to reproduce the issue ?

Place an order with a virtual product, an email is sent with the download link, view it in pure text mode. The strings &quot;{nbproducts}&quot; and &quot;{virtualproducts}&quot; are visible and were not replaced by smarty.

### PR DESCRIPTION
**Pull request by antonellamarengo**
Ref. #9785

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Downloadable product email: Typos in template variables
| Type?         | bug fix
| Category?     | LO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #9785

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10843)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Nice catch :)

**Comment by marionf** [comment]
When we will merge this one, we need to think to do what is necessary to have this fix in other languages
@eternoendless

**Comment by marionf** [comment]
Hello @antonellamarengo 

Some html tags are displayed, can you fix it ?

capture d ecran_394

**Comment by dennybiasiolli** [comment]
> Some html tags are displayed, can you fix it ?

Hi @marionf, I think the problem is in the way [`OrderHistory.php`](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/OrderHistory.php#L156) receives the `{virtualProducts}` parameter.

It's created as HTML string in the [following lines](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/OrderHistory.php#L137-L149)

```
$links = '<ul>';
foreach ($assign as $product) {
    $links .= '<li>';
    $links .= '<a href="' . $product['link'] . '">' . Tools::htmlentitiesUTF8($product['name']) . '</a>';
    if (isset($product['deadline'])) {
        $links .= '&nbsp;' . $this->trans('expires on %s.', array($product['deadline']), 'Admin.Orderscustomers.Notification');
    }
    if (isset($product['downloadable'])) {
        $links .= '&nbsp;' . $this->trans('downloadable %d time(s)', array((int) $product['downloadable']), 'Admin.Orderscustomers.Notification');
    }
    $links .= '</li>';
}
$links .= '</ul>';
```

It's passed to the `Mail::Send` function as element of `$data` array

```
'{virtualProducts}' => $links,
```

Later on, `Mail.php` receives the data in `$templateVars` parameter and in case of txt mail it's not converted back to plain text.

How do you suggest to fix this?
I think the best way it's to change the way `virtualProducts` are passed to the template, and in `download_product.txt` and `download_product.html` template loop through the values and display them in the right way.
What do you think? Does this approach breaks the other localized mail templates?

**Comment by marionf** [comment]
Thanks for diving into this @dennybiasiolli 

Would you be willing to make a pull request with your code suggestion?
https://github.com/PrestaShop/PrestaShop/tree/develop

Thank you!

**Comment by PierreRambaud** [comment]
Thanks @antonellamarengo

**Pull request merged**
