### PR TITLE
Update HTML Purifier

### PR DESCRIPTION
**Pull request by PeterStudioWeb**
Update HTML Purifier from version 4.6 (in distribution) to version 4.10.0.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update HTML Purifier to version 4.10.0
| Type?         | improvement
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9393)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @PeterStudioWeb,

would you mind to point me what did you change, or what do you want to change?

Because afaik there is no commits from you here...

**Comment by PierreRambaud** [comment]
@mickaelandrieu Look like he wants to ask us for updating HTML Purifier.
`into 1.7.4.x from develop` no fork used, and don't have rights to push a new branch here :P

**Comment by mickaelandrieu** [comment]
Ok, feature requests need to be done in our forge => http://forge.prestashop.com/secure/Dashboard.jspa

I close, thanks for your proposal @PeterStudioWeb !

**Comment by PeterStudioWeb** [comment]
Yes, updating HTML Purifier to 4.10.0
Thank You.

**Pull request closed without merging**
