### PR TITLE
BO :  Wording  readmore-header.tpl

### PR DESCRIPTION
**Pull request by Nobodaddy**
Just for the record: It makes no sense to specify expressions or single characters that must not be translated as translation variables.

### CODE REVIEW

**Comment by Shagshag** [comment]
Hi, do not forget non latin alphabets.
in thaï language "version" is said "รุ่น" so "v" can be translated by "รุ่น" or maybe "รุ่".

**Comment by julienbourdeau** [comment]
There is issue with non-latin languages like Shagshag said, but also RTL languages. Regarding the new translation system, I believe the best way would be changing it to something like this.

```
<small class="text-muted">
  {l s='v%version_number% - by %author%' sprintf=['%version%' => $version, '%author%' => $author] d='domain_to_be_determined'}
</small>
```

Also, are you sure this template is still used in PrestaShop 1.7 ? I doubt it :(

**Comment by Nobodaddy** [comment]
Well, if you doubt it then you should remove it because otherwise one more waste translation item is presented at Crowdin. There are already dozens, if not hundreds of waste translations items gathered there.

**Comment by julienbourdeau** [comment]
Have you noticed we removed about ~4000 strings with the new translation system ?

I'll ask @Quetzacoalt91 if this template can be removed or not. But still, the point I'm making is that is should be a certain way to add all variables with a clear name inside the string. It's easier for translator to understand what the `v` means in `v%version_number%` than when it's on its own.

**Comment by Nobodaddy** [comment]
@julienbourdeau 
_'Have you noticed we removed about ~4000 strings with the new translation system ?'_

Ha, ha, good point!
However, from my view as German proofreader I just noticed that a lot of fully translated items vanished and several hundreds of new items are now waiting for a translator. 1.6 is 100% completed, 1.7 is far way from this goal.

**Comment by julienbourdeau** [comment]
We imported all translations from crowdin that were matching 100%, it think it was about 80%. I know there still a lot of work to translate the rest, but we tried our best to make it as easy as possible.

We're also changing processes so there is no string updates in patch version (at least) so there won't be any breaking translation in any 1.7.0.x version.
It also means that if prestashop was only 80% translated when you installed your store, you can update your translation with one click without anything breaking.

**Comment by Nobodaddy** [comment]
I'm quite familiar with Crowdin. Trust me, in many cases your match didn't work.

**Pull request closed without merging**
