### PR TITLE
Recreate #2779 "Fix redirects on HTTPS" on the '1.6.1.x' branch.

### PR DESCRIPTION
**Pull request by xBorderie**
Original commit by @ZiZuu-store in #2779.

### CODE REVIEW

**Comment by doekia** [comment]
I don't understand the boring campaign late 2015 regarding all pending PR, just to re-postpone them again 3 months later to the exact same dead-end to-do (or not) list.

**Comment by mickaelandrieu** [comment]
:+1:

**Comment by xBorderie** [comment]
@doekia The ["Let's review pull requests" campaign](http://build.prestashop.com/news/review-your-pull-requests/) started in late 2015 is an honest call for help to the community, in order to find our way through the heap of PRs waiting. A few contributor did update their PR in order to fit into the `1.6.1.x` or `develop` branches, but a majority were left as-is by their authors, sadly.

In the meantime, 1.7 is being developed, so the priority right now is to make sure that we can present a great beta version soon. All hands are therefore deep into the 1.7 project, and managing PRs had to take a step back for now. We plan on diving back into PRs once the 1.7 is stable enough. It's just a very pragmatic question of developer time and wanting to deliver the project.

**Comment by therampagerado** [comment]
After applying this fix it still redirect to http and then to https...

What can be the problem?

http://tools.pingdom.com/fpt/#!/dT1AOm/https://www.rampagesport.eu/

**Comment by maximebiloe** [comment]
Hello,

Nice catch but why creating a function `getProto()` instead of using `Tools::getShopProtocol()` ?

Regards

**Comment by ZiZuu-store** [comment]
@maximebiloe because it checks PS_SSL_ENABLED_EVERYWHERE too .. which is ignored by the Tools method

**Pull request closed without merging**
