### PR TITLE
Prevent email enumeration

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | On the BO login page, it is possible to find out if the email of an employee is registered. It can be done by looking at the response time of the POST request.<br/>On my end I got the following result:<br/>Average time if email does not exist: ~0.31<br/>Average time if email exists: ~0.36
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | What this PR must achieve is that it must take the same time to execute the request with correct email as well as incorrect email.<br/>Please test that trying to login on BO with an email that belongs to a registered employee and with an email that does not exist is almost the same. The average time difference must about the same.<br/>You can check the response time by this command: `curl -w %{time_total} -s -X POST http://localhost/prestashop/admin-dev/index.php -d 'ajax=1&token=&controller=AdminLogin&submitLogin=1&passwd=demodemo&email=demo%40demo.com' -o /dev/null`
| Fixed ticket?     | ~
| Related PRs       | 
| Sponsor company   | ~

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Good for me 👍 thank you @MathiasReker !

**Review by nicosomb — APPROVED** [review]
OK for me. 
@MathiasReker we had an issue on CI, which is now fixed. Could you please rebase your branch to launch all the testsuite?

**Comment by MathiasReker** [comment]
> OK for me. @MathiasReker we had an issue on CI, which is now fixed. Could you please rebase your branch to launch all the testsuite?

Sure

**Review by nicosomb — DISMISSED** [review]

**Comment by nicosomb** [comment]
hum, you didn't rebase it, you merged 8.0.x in your one.

**Comment by MathiasReker** [comment]
> hum, you didn't rebase it, you merged 8.0.x in your one.

Now it is rebased :)

**Comment by matks** [comment]
> [@MathiasReker ](/MathiasReker)
> ` [Merge branch '8.0.x' into prevent-email-enumeration](/PrestaShop/PrestaShop/pull/31647/commits/dfd2c177ff3a5d5723ff0a9bdd6e46a577f08097)`

I'm afraid git does not agree with you 😅 : see commit https://github.com/PrestaShop/PrestaShop/pull/31647/commits/dfd2c177ff3a5d5723ff0a9bdd6e46a577f08097 it says "[Merge branch '8.0.x' into prevent-email-enumeration](https://github.com/PrestaShop/PrestaShop/pull/31647/commits/dfd2c177ff3a5d5723ff0a9bdd6e46a577f08097)"

**Comment by MathiasReker** [comment]
> > [@MathiasReker ](/MathiasReker)
> > ` [Merge branch '8.0.x' into prevent-email-enumeration](/PrestaShop/PrestaShop/pull/31647/commits/dfd2c177ff3a5d5723ff0a9bdd6e46a577f08097)`
> 
> I'm afraid git does not agree with you 😅 : see commit [dfd2c17](https://github.com/PrestaShop/PrestaShop/commit/dfd2c177ff3a5d5723ff0a9bdd6e46a577f08097) it says "[Merge branch '8.0.x' into prevent-email-enumeration](https://github.com/PrestaShop/PrestaShop/pull/31647/commits/dfd2c177ff3a5d5723ff0a9bdd6e46a577f08097)"

I think it is rebased now 😅

**Review by matks — APPROVED** [review]
@MathiasReker Yes! 😄 GitHub agrees with you

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @MathiasReker ,

I don't find the same result as you, maybe I'm doing something wrong.

I tested with right/wrong password for existing employee accounts, tested the same thing with non-existing account.
I also tested multiple times with the same data, but the result is different each time

Here's what I have :
Screenshot 2023-03-14 at 09 39 32

Am I missing something ?
Thanks!

**Comment by kpodemski** [comment]
Hi @florine2623 

This is completely normal that script execution time is different on your machine.

This PR should make the difference between requesting existing users vs non-existing users smaller.

**Review by florine2623 — APPROVED** [review]
Hello @MathiasReker @kpodemski ,

Using the command and changing the login data :

`curl -w %{time_total} -s -X POST http://localhost/prestashop/admin-dev/index.php -d 'ajax=1&token=&controller=AdminLogin&submitLogin=1&passwd=demodemo&email=demo%40demo.com' -o /dev/null`

I have these results : 
Average time if email does not exist: ~0.005227
Average time if email exists: ~0.005170

Tested with existing and non-existing employees account directly from BO. For me it is QA ✅ 

I let @kpodemski add his review ^^
Thanks!

**Review by kpodemski — APPROVED** [review]
All good, thanks @MathiasReker

**Comment by matks** [comment]
Thank you @MathiasReker 😉 great!

**Pull request merged**
