### PR TITLE
Document Category class + cleanup

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | `develop` |
| Description? | Upgrading the PHPDoc comments of this class, using the latest PS standards and also applying the PS standards to some of the code. Also getting the Franglais out of the comments, getting rid of things the Symfony code sniffer nags about, etc. It might have some additional `todo` tags, depending on whether the code was comprehensible or not. |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | N/A |
| How to test? | N/A |

Warning: this PR also has a code cleanup. Please check this first before merging!

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
> 985 additions, 586 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

:(

**Comment by firstred** [comment]
`gitk` to the rescue :smile:

**Comment by firstred** [comment]
But I indeed have changed a lot. This is basically what I would like to see with every class/controller file before 1.7 gets released.

Having good documentation, add `@deprecate` tags to unncessary stuff and fully up to date with Symfony style. This should eventually save a lot of people a lot of time.

**Comment by mickaelandrieu** [comment]
:+1: ok to me !

**Comment by firstred** [comment]
Damn you did a lot of work in a short amount of time.

Great job! :tada:

**Comment by mickaelandrieu** [comment]
I've rode only "your" file, not the diff :p

**Comment by firstred** [comment]
Nice. The rest should be easier (I hope) as those classes are smaller.

**Comment by mickaelandrieu** [comment]
And obviously, this huge PR broke something :(

**Comment by firstred** [comment]
Good to know. I'll go check it.

**Comment by mickaelandrieu** [comment]
https://github.com/PrestaShop/PrestaShop/pull/6212 :)

**Pull request merged**
