### PR TITLE
Do not allow 0 as number of products per page

### LINKED ISSUE #28367: Error when pagination (products per page) on category page set to 0
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Previously reported here: https://github.com/PrestaShop/PrestaShop/pull/27892#pullrequestreview-951989134

When we set to 0, "Products per page" fiels in product settings page, errors are displayed on category page:

On top of the category page:

165108496-3ae09b70-c16b-4a9f-846a-87ccfb769214

On bottom of the page:

165108699-019653c6-61c5-48d6-8cca-9f44e6b5e1d2

### Expected behavior

- The input can't validate if the value is equals to 0. The value allowed are strictly superior to 0.
- Wording: define an error message for value equals and inferior to 0.
- Change tooltips wording: 10 to 12 products
- Check placeholder 

**Wording:** 

'The field is invalid. Please enter a positive integer.' in Admin.Notifications.Error

+ update the tooltip: 'Number of products displayed per page. Default is 12' Admin.Shopparameters.Help

### Steps to reproduce

Go to BO > Shop parameters > Product settings page > Pagination Block
Set to 0 the "Products per page" field in product settings page
Go to FO > Home category
See errors > on top & bottom of the page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2.21

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | A wrong check was made to validate the data of the form responsible of the number of product per page. This PR fixes it by checking that the number is strictly positive.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28367
| Related PRs       | 
| How to test?      | Please see #28367
| Possible impacts? |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Comment by atomiix** [comment]
@Julievrz I only updated the tooltip message but not the error one because I think that mentioning the field that is responsible for the error is better than saying "the field is invalid" in that case because the error messages are displayed at the top of the page, not under every form field.
Don't hesitate to correct me if I'm wrong though!

**Comment by Julievrz** [comment]
> @Julievrz I only updated the tooltip message but not the error one because I think that mentioning the field that is responsible for the error is better than saying "the field is invalid" in that case because the error messages are displayed at the top of the page, not under every form field. Don't hesitate to correct me if I'm wrong though!

Do you mean we need to update the error message of the issue to specify the field? We could do that, yes!

**Review by matthieu-rolland — DISMISSED** [review]
waiting for wording validation before sending to QA

**Comment by atomiix** [comment]
@Julievrz I updated the wording ;)

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]
Code is valid

Waiting for @Julievrz to add "Wording ✔️ " label

**Review by florine2623 — APPROVED** [review]
Hello @atomiix ,

**Without PR :**
Screenshot 2022-07-07 at 11 13 39

**With PR :**
No error displayed in FO.
New error message :
Screenshot 2022-07-07 at 11 16 21

New info displayed :
Screenshot 2022-07-07 at 11 16 08

Can only save positive integer. Tested with minus and plus signs, letter, special characters.

It is QA ✅ 
Thanks!

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
