### PR TITLE
Update SHOP_LOGO_* configuration when changing shop logo

### LINKED ISSUE #23733: Shop logo width and height are not updated
#### Describe the bug

SHOP_LOGO_WIDTH and SHOP_LOGO_HEIGHT configuration vars are set in prestashop install, in web service logo update but not in SF Theme controller.
It was there in AdminThemeController before SF migration.
#### Steps to Reproduce

1. Note SHOP_LOGO_WIDTH  and SHOP_LOGO_HEIGHT in configuration table
2. Go to theme configuration
3. Change shop logo
4. See in base that  SHOP_LOGO_WIDTH  and SHOP_LOGO_HEIGHT are not changed

#### Additional information

* PrestaShop version: 1.7.8 (develop)
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | When uploading a logo in `Theme & Logo > Theme`, the associated `SHOP_LOGO_HEIGHT` & `SHOP_LOGO_WIDTH` configuration keys were not updated. This PR fixes it.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23733
| How to test?      | Please see #23733
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24017)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Could you add some tests, please ?

**Comment by atomiix** [comment]
@Progi1984 Kinda hard to test without rewriting a part of `LogoUpdater`. I think a Behat test would be appropriate but the upload function uses `move_uploaded_file` that is not really mockable (and doesn't work in a CLI environment) and rewriting the way files are uploaded is out of the scope of this PR IMO...

**Comment by Progi1984** [comment]
@atomiix You can override `move_uploaded_file`. Check this test on `develop` branch by @PierreRambaud  : https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Core/File/FileUploaderTest.php#L34

**Review by Progi1984 — APPROVED** [review]
Thanks @atomiix :heart_eyes:

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @atomiix,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1czP9X_t21398sVEEkz3Lw-rQ1h4NXjLD/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith & @atomiix

**Pull request merged**
