### PR TITLE
PPV2 Fix virtual file validation

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/31370. Additionally I added some js so it fills up file name from uploaded file automatically (as it was in previous page version).
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/31370
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/31370
| Related PRs       | 
| Sponsor company   | 

Screenshot from 2023-02-20 20-04-48
Screenshot from 2023-02-20 20-04-29

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
LGTM

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

**Review by djoelleuch — APPROVED** [review]
Hello @zuk3975 , 

https://user-images.githubusercontent.com/115152460/220961947-a118a1a9-18f2-4bc4-8231-22464ed1461d.mp4


LGTM ,IT'S QA :heavy_check_mark: 
 Thank you !

**Comment by nicosomb** [comment]
Thank you @zuk3975 and @djoelleuch !

**Pull request merged**
