### PR TITLE
Fix profile class regex

### PR DESCRIPTION
**Pull request by gploteau**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | When a tab is installed with an invalid parent id, the suffix _MTR is added by ModuleTabRegister::duplicateParentIfAlone, but the regex in Profile::generateAccessesArrayFromPermissions does not take account of this addition of _MTR.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | None
| How to test?      | None
| Possible impacts? | None

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25832)

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hello and thank you for the contribution!

I see you modified a little bit profile and fixtures data. I don't understand how the two are connected.

Could you describe a bit more what you PR does and why ? What was wrong, how did you fix it? The best would be to submit a bug report with the PR so we can track it.

See https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/pull-requests/

> Describing your change and the reasoning behind it is extremely important for it to be reviewed and approved. Explain, in as much detail as you can, what did you change and why.

> If you need space, just write a short summary about your change in the table, then describe in more detail below it. You are also encouraged to add links, files, screenshots… anything that can help reviewers understand why the change is needed, and why it’s valid.

**Comment by gploteau** [comment]
Ok i've updated the description.
When a tab is installed with an invalid parent id, the suffix _MTR is added by ModuleTabRegister::duplicateParentIfAlone, but the regex in Profile::generateAccessesArrayFromPermissions does not take account of this addition of _MTR.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I'm sorry but I don't get it, can you please create an issue in order to make sure we are able to reproduce your issue?

**Comment by PierreRambaud** [comment]
Hi @gploteau ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
