### PR TITLE
Fix theme export

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix theme export
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1727
| How to test?  |

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by aleeks** [comment]
Add a commit for windows hihi !
sans titre

**Comment by aleeks** [comment]
ping @PrestaShop/prestashop-core-dev  to test linux/windows/mac/etc ;alien:

**Comment by aleeks** [comment]
Need this by the way : https://github.com/PrestaShop/TranslationToolsBundle/pull/23

**Comment by mickaelandrieu** [comment]
Thank you guys, good job !

**Pull request merged**
