### PR TITLE
Update install with trans from crowdin

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update install with trans from crowdin
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | @AlexEven  @maximebiloe 

To test this PR, you need to have new lang pack!

### CODE REVIEW

**Comment by Nobodaddy** [comment]
Lol, great!
You may not have realized it, but as far as I know **none** of these items are part of the Crowdin translation files. You cannot automatically update what doesn't exist. Currently the closing of all PRs just means a lot of untranslated - English - expressions.

**Comment by AlexEven** [comment]
Hello @Nobodaddy! Thanks for your concern :)
The whole point of these modifications is to upload the install files to Crowdin in the end. It's still work in progress, and we'll add the files in the coming weeks, together with the current translations from the XML files. 
It will be much easier to translate and to maintain.
Thanks!

**Review by Nobodaddy — COMMENTED** [review]
Seems to me the only halfway correct files are Farsi und French.
Pars pro toto lang DE: Chapeau!
Wrong language, in parts outdated items.
I really wonder where you found these old files. And what is it good for? :)

**Comment by maximebiloe** [comment]
Thank you @aleeks

**Pull request merged**
