### PR TITLE
Fix "weird behaviour when filling the quantity field with letters of symbols"

### LINKED ISSUE #18031: Weird behaviour when filling the quantity field with letters of symbols
On order page > Add a product, when performing this action, you can still save it and this will add a fake product with zero quantity. It will removed when reloading the page.

### PR DESCRIPTION
**Pull request by arouiadib**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |1.7.7.x
| Description?  | This PR contains a front-end validation for the quantity input when adding/edditing product in order view page (migrated).
| Type?         | bug fix 
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18031
| How to test?  | In order view page (`sell/orders/orders/6/view`), add product to order , then fill the quantity field with a negative number or characters other than numerical characters, you will see the add button disabled. And so, it makes avoiding the creation of fake product.

PS:<del> I am also trying to find a good way to make a server-side validation also. Any feedback regarding this part is highly appreciated.</del>. I think server-side validation is already done by @jolelievre in his PR (just discovered this fact).

⚠️ Note: this PR https://github.com/PrestaShop/PrestaShop/pull/18168 (server side validation) should be tested and merged before this front validation, or it won't be possible to validate the server side easily any more. ✓

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18200)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by jolelievre** [comment]
Hello @arouiadib,

I think this PR is redundant with this one https://github.com/PrestaShop/PrestaShop/pull/18168 that manages all the validation on server side, this provides more robust behavior as these actions might be used in another context in the future (for an API for example).

The controller returns an error message via json so the js displays a notification error message:
Capture d’écran 2020-03-19 à 11 26 05

Do you think it requires an additional front validation?

**Comment by jolelievre** [comment]
After reflexion I guess it's always interesting to validate on front side and avoid a request to the server. But the server side validation is still important, so I guess we should test and validate it before merging this PR or it will be complicated to test for QA team.

**Comment by arouiadib** [comment]
@jolelievre , totally agree with you in all what you mentionned :+1:  Thank you very much for these important points.
Thank you for your time reviewing  @NeOMakinG @Progi1984 .

**Comment by NeOMakinG** [comment]
> After reflexion I guess it's always interesting to validate on front side and avoid a request to the server. But the server side validation is still important, so I guess we should test and validate it before merging this PR or it will be complicated to test for QA team.

I agree, for me, validating in front AND back should be a best practice

**Comment by jolelievre** [comment]
The related PR #18168 has been merged, so this one can now be tested safely

**Comment by SD1982** [comment]
Hello @arouiadib and @jolelievre I discovered by testing this PR that it was possible to add a quantity greater than the quantity in stock :

https://drive.google.com/file/d/1LYOxmyQFNTTgzAzWugUGTOTAZhp7wKA2/view?usp=sharing

I hadn't thought to test this case during the test of PR #18168 made by @jolelievre 

I think it would be more logical to make the correction on the server side before validating this PR in this way @arouiadib  can adapt this PR to this new modification.

@jolelievre  Is it better that I create a new issue for this behavoiur or it is better to reopen the old ones and edit them

**Comment by SD1982** [comment]
@arouiadib , @jolelievre, @khouloudbelguith  I have created a new issue (#18238) for the behaviour that I mentioned in my last comment . Once the issue is confirmed by @khouloudbelguith and fixed by a PR @arouiadib could you adapt this one to ?

**Comment by jolelievre** [comment]
@arouiadib I'll deal with the server side part for this issue https://github.com/PrestaShop/PrestaShop/issues/18238

For front side I think we should just disable the save/add buttons when the stock is negative, besides it's already displayed in red so I guess the detection part is already implemented somewhere

**Comment by arouiadib** [comment]
Thank you very much @SD1982  for this important point, and all of you guys for review and remarks.
Entendu! I will modify this PR so that add/edit button is disabled when stock < quantity.

**Comment by jolelievre** [comment]
@arouiadib @SD1982 After some research and as I explained in this comment https://github.com/PrestaShop/PrestaShop/issues/18238#issuecomment-601737241

The behaviour is actually not a bug. It is allowed on some product that can be ordered out of stock (it's configurable), and the "vector graphics" are one of them

**Comment by jolelievre** [comment]
So this PR can be tested and validated it's all ok!

**Comment by SD1982** [comment]
hi @arouiadib  

There is still one case where the "add" button is not disabled. It's when you first enter a number in the field and you add some letters :


But if "add" button is clicked the product is added and only the numbers are retained : 


It's not really a big deal but it can be confusing for users

**Comment by arouiadib** [comment]
Hello @SD1982 , I will take it into account , thank you for your observation and time :)

**Comment by arouiadib** [comment]
Hello @SD1982, 

While working on your remark, I have a question to the community: is there a specific reason behind using a text input for quantity and not the HTML5 numeric input:
image

The good thing about this input type : it makes server-side validation work out of the box for cases like `123abc`:
image

You can test a [PR with only this feature (separated from the frontend validation added by this current PR)](https://github.com/PrestaShop/PrestaShop/pull/18254). 

A second good point about numeric input, it fixes also front end validation in this current PR for the point you mentioned :smile:  (to be tested in this current PR).

So I think the HTML5 input will make both server-side and client-side validation better. What do you think?


PS: There is also the `dev` advantage of not adding lines of code in JavaScript files just to treat cases like `123abc`. In fact the current code uses `parseInt` which is not enough to make the button disabled when it should be. I think adding one other line for testing against `NaN`  is reasonable but more checks will require more code and probably, a thinking about the architecture ( To be honest, I still can't find the better place to add validation function code in front-end:  whether in same file or in a new file==> needs expert js advise).

**Review by Arman-Hosseini — DISMISSED** [review]

**Comment by jolelievre** [comment]
@arouiadib Yes I think it's a good idea to use a number input, you should integrate this modification in this PR and close the other one

**Comment by arouiadib** [comment]
Hello @jolelievre ,

> ... number input, you should integrate this modification in this PR and close the other onei

Thank you very much for the guidance.  I have closed that PR , but now I need to find why we need  declare `numberType` in both FormBuilder and in template?! 
Do you have an idea?

**Comment by arouiadib** [comment]
Hello @PierreRambaud @jolelievre ,

It seems the numberType in SF 3.4 is not behaving correctly and that there are other people using the same trick like in Prestashop ([look at the answer here](https://stackoverflow.com/questions/44696981/symfonys-numbertype-as-html5-input-field-and-a-custom-locale-setting) ).

The trick is to use TextType and use`{'type':'number'}` in template. Wdyt?
Thank you very much.

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
Assets need to be build in 1.7.7.x :thinking:

**Comment by Progi1984** [comment]
@arouiadib Could you rebase your PR from `1.7.7.x` branch and build assets ? Thanks

After that, we cand send your PR in QA. ;)

**Comment by arouiadib** [comment]
@PierreRambaud , @Progi1984 , done. 
Thank you for your usual guidance.

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
Hello @arouiadib I don't know if it's because there is a conflicting file but the page seems to be a little bit "broken" 
- Some "comments" are visible on the page
- The page not using the full width . 
Can you please check ?
capture d'écran_29

**Comment by arouiadib** [comment]
Hello @SD1982 , 
Thank you for all the time testing this PR.
could you please check if it is working as expected right now?

**Comment by Progi1984** [comment]
@arouiadib The @PrestaShop/prestashop-core-developers need to review before sending the PR to the @PrestaShop/prestashop-qa team :)

Please fix Travis CI before review :) Thanks :smiley:

**Comment by arouiadib** [comment]
@Progi1984 , thank you for your usual explanations.
I don't know what happened to the Travis CI error, it suddenly disappeared :D.
Althought I did nothing to the PR  to create an error yesterday;  I confirm there was an error related to timeout exceeded . I have seen it. 
Regards

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
Hello @arouiadib sorry to ask you again but can you please resolve the conflict ?

**Comment by SD1982** [comment]
Hello @arouiadib  sorry to ask you again but can you please resolve the conflict ? I still have the "comments" visible on the page.

**Comment by jolelievre** [comment]
Hello @arouiadib 
I took the liberty to resolve conflicts and rebuild the assets, so that the PR can be validated quickly
I hope you don't mind

@SD1982 it should be fine now!

**Comment by arouiadib** [comment]
@jolelievre  thank you very much, I really appreciate your effort. 
@SD1982 thank you for your time testing and feedbacking.

**Review by jolelievre — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @arouiadib !

**Comment by Progi1984** [comment]
@arouiadib Congratulations :tada: ! Your PR has been validated by the QA Team. Could you rebase and rebuild your assets before merging ? Thanks :)

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
@arouiadib I just rebased the PR to avoid it to become conflicted again
@Progi1984 just need to approve and merge once the tests are green

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @arouiadib & @jolelievre

**Comment by arouiadib** [comment]
Big thanks @jolelievre @Progi1984 @SD1982 :heart:

**Pull request merged**
