### PR TITLE
invoice fix to better group items.

### PR DESCRIPTION
**Pull request by DavidEschmeyer**
makes picking products easier when the same product is added in a different size.
example, 1) add ipod to cart, add mackbook, add different ipod. Invoice shows ipod, macbook, ipod. With this change it shows ipod, ipod, macbook so the fulfillment department can pull products more efficiently.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Can you please close this one and make it again on 1.6.1.x branch ?

Thank you.

**Comment by dave-lp** [comment]
makes picking products easier when the same product is added in a different size.
example, 1) add ipod to cart, add mackbook, add different ipod. Invoice shows ipod, macbook, ipod. With this change it shows ipod, ipod, macbook so the fulfillment department can pull products more efficiently.

**Comment by gRoussac** [comment]
Hi @dave-lp,

Do you want me to do it on 1.6.1.x branch ?

Regards

**Comment by dave-lp** [comment]
sure, and any future rev's

Best regards,
Dave

**Comment by dave-lp** [comment]
actually i made it again on 1.6.1.x already.  you should see the pull req
there.

**Comment by dave-lp** [comment]
here, this is 1.6.1.x proper
https://github.com/PrestaShop/PrestaShop/pull/3991

**Pull request closed without merging**
