### PR TITLE
Fix missing permission roles

### LINKED ISSUE #11547: Can't enable or disable some modules permissions
**Describe the bug**
Can't enable or disable some modules permissions

**To Reproduce**
1. Go to Advanced parameters > Team > Permissions
2. Try to enable/disable checkboxes below

capture d ecran_680

3. See the error

capture d ecran_681

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

### PR DESCRIPTION
**Pull request by 202-ecommerce**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Impossible to customize permissions on 3 employee's permissions level.<br>Please note older 1.7.x need add suggested requests to fix the bug.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11547
| How to test?  | Please refer to the issue #11547

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14101)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
But, it should target the 1.7.6 branch :thinking:

**Comment by 202-ecommerce** [comment]
> But, it should target the 1.7.6 branch thinking

yep, PR for an upgrade with @matks agreements during PSD because we cannot add an upgrade file for 1.7.7 at this step...

**Comment by matks** [comment]
As discussed with @202-ecommerce during PSD,
- this issue has been there in 1.7 for a long time
- putting this script in 1.7.6 SQL upgrade will repair shops which upgrade to 1.7.6
- for shops which do not upgrade, we could provide an "Auto-repair" module that people could install and trigger from there some repair scripts, including the SQL requests from this PR

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by 202-ecommerce** [comment]
Thank you for the merge.

**Pull request merged**
