### PR TITLE
Force AbstractColumn::name to never be null

### LINKED ISSUE #30302: A HTTP 500 internal server error in BO > Orders > Credit slips page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An exception is displayed in BO > Orders > Credit slips page
Capture d’écran de 2022-11-16 10-51-25

### Expected behavior

The page BO > Orders > Credit slips page should be displayed correctly

### Steps to reproduce

1. Go to BO and login
2. Go to Orders > Credit slips page
=> See the exception

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | AbstractColumn can be instantiated with `$name` empty (null), which is against the `ColumnInterface` since `getName` must always return a string type. So we initialize it with the same value as ID, this way in case `setName` is not used on the column it will still have a value for name
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30302 and [#30358](https://github.com/PrestaShop/PrestaShop/issues/30358)
| Related PRs       | ~
| How to test?      | See issue, access to credit slip page you should have no exception anymore
| Possible impacts? | ~

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by FabienPapet — CHANGES_REQUESTED** [review]
Can you add one unit test on this to avoid future regression ?

**Review by MhiriFaten — COMMENTED** [review]
Hello @jolelievre ,

I checked the PR, and I noticed that there is **bulk** added in the migrated pages which contain the **'grid listing'**, and it caused a disruption in the **automated tests**.

Here is the list of pages where the **bulk** is added :

>     - Orders list page
>     - Product list page V2
>     - Categories list page
>     - Brands & Suppliers
>     - Files
>     - Customers
>     - Addresses
>     - Order Messages
>     - Pages
>     - Locations
>     - Taxes
>     - Contacts
>     - Traffic & URLs
>     - E-mail
>     - Team
>     - Security
> 
> 

Here are some  examples of bulk added because of this PR

**Customers Page**
image

**Brands & Suppliers Page**
image

:warning: **Automated tests**
https://github.com/HanaRebaiQA/testing_pr/actions/runs/3513019090/jobs/5885359541

Could you check it please? :pray:
Waiting for your feedback .

Thank you !

**Review by nicosomb — DISMISSED** [review]

**Comment by jolelievre** [comment]
Hi @FabienPapet 

actually, the initial fix had unexpected side effects, I just changed it to at least make sure the `$name` field is initialized with an empty string. Also, I'm not sure it's worth unit testing an abstract column The final implementation actually depends on the class that extends it, and adding a basic class in unit test just to assert this minimalist abstract class doesn't bring much value to the test.

The automatic tests actually already validate this behavior indirectly since it's used for all the existing grids.

**Comment by FabienPapet** [comment]
I disagree, as there was a type error, you need a test to cover it, even if it is basic usage. If we don't test what we are doing, we can expect more and more little bugs like this one.

A basic test of the default value after the construct method would be great

**Comment by jolelievre** [comment]
@FabienPapet I added unit tests as it was the related column in the related issue, but I won't add unit tests for all the existing columns relying on this abstract as they're not related to this PR. If they need to be added then it should be in a dedicated PR. But this bugfix should focus on its related issue.

**Review by FabienPapet — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @jolelievre , 

Thanx for the PR . it's LGTM ! QA :heavy_check_mark: 

- Tests auto : **OK**, you can see the tests execution here : [TESTS-REPORT](https://github.com/sallemiines/testing_pr/actions/runs/3530688898)

- The issues [#30302]( https://github.com/PrestaShop/PrestaShop/issues/30302) and #[30358](https://github.com/PrestaShop/PrestaShop/issues/30358) are fixed, you can see the attached screen record 

[Untitled_ Nov 23, 2022 1_12 PM.webm](https://user-images.githubusercontent.com/31663369/203548731-04fe1431-5ccc-4d42-8593-0a250e9cb378.webm)


Thank you ! :rocket:

**Comment by nicosomb** [comment]
Thank you @jolelievre!

**Pull request merged**
