### PR TITLE
Save before generate combinations

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | If you generate combinations without saving before, the data can be lost. This PR launch the save button before combination generation.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3284
| How to test?  | Create a product, don't put a name, generate combinations, put price and quantities. Refresh, everything has disappeared except the combinations

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi @fatmaBouchekoua ,

Could you move this PR to 1.7.2.x branch please ? So that it can be taken in 1.7.2.1

Thanks !

**Review by eternoendless — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Are all the commits expected in this PR ? It seems a rebase went wrong.

**Comment by eternoendless** [comment]
You mean this one? https://github.com/PrestaShop/PrestaShop/pull/8057/commits/52f4e80e2645ff042aeeeebcbf75be989482b242

It does look unrelated but I don't think it hurts.

**Comment by eternoendless** [comment]
@fatmaBouchekoua Could you please confirm if that commit belongs to another PR? If that's the case, please rebase it out from this one.

**Comment by fatmaBouchekoua** [comment]
Hello @eternoendless & @Quetzacoalt91 , 
I've removed this commit from 3 other PRs (I don't know how it got into my PRs).
I will remove it

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @fatmaBouchekoua

**Pull request merged**
