### PR TITLE
Fix "can not" spelling

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | see title
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | CI must be 🟢 
| Possible impacts? | None if wrong texts are not expected somewhere.

see https://www.grammarly.com/blog/cannot-or-can-not/ grammar

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26069)

### CODE REVIEW

**Comment by Hlavtox** [comment]
**Can not** is perfectly gramatically correct and formal spelling.

**Comment by mvorisek** [comment]
> 
> 
> **Can not** is perfectly gramatically correct and formal spelling.

It is and hi to the Czech Republic! Only "can not" is usually used for something totaly else 😆, citing summary from the grammar page:

> - In formal writing and where contractions are frowned upon, use cannot.
> - It is possible to write can not, but you generally find it only as part of some other construction, such as “not only . . . but also.”

**Comment by MatShir** [comment]
We need to ask @Julievrz (she is our content manager in PrestaShop :) )
Do you have any recommendations? We need to stay consistent in the software

**Comment by mvorisek** [comment]
https://github.com/PrestaShop/PrestaShop/search?q=cannot to be consistent...

**Comment by Julievrz** [comment]
Hi everyone, 

Here's a great [article ](https://www.grammarly.com/blog/cannot-or-can-not/) to understand the difference between "cannot", "can not" and "can't".

On the software, there are some inconsistencies. Both "cannot" and "can't" are used. 

So, when working on the Content style guide, the question of contractions was raised.

You can read about it [here](https://zeroheight.com/80a6c5a61/v/latest/p/91e0b7-mechanics/b/06e117). 

=> Following the new guidelines and with the aim of making the wording on PrestaShop software sound more human and casual, it is preferable to use "Can't". 

However, we should take the opportunity to improve/optimize the error messages instead of only replacing "Cannot" with "Can't". Starting a sentence with "Can't" or even "Cannot" is a bit weird and sounds negative. I invite you to read the section of the Content style guide that deals with error messages, [here](https://zeroheight.com/80a6c5a61/v/latest/p/510e8a-components/b/2943bd.). ☺️

**Comment by PierreRambaud** [comment]
Could you please create an issue to define what we should do @Julievrz

**Comment by Julievrz** [comment]
> Could you please create an issue to define what we should do @Julievrz

In my opinion, the wording of this PR is not easy to review/improve because the error messages are taken out of their context. 

I think it would be easier to improve the wording page per page. The Content style guide will help, and issues will be created as we go along. ☺️

**Comment by PierreRambaud** [comment]
> > Could you please create an issue to define what we should do @Julievrz
> 
> In my opinion, the wording of this PR is not easy to review/improve because the error messages are taken out of their context.
> 
> I think it would be easier to improve the wording page per page. The Content style guide will help, and issues will be created as we go along. relaxed

Thanks @Julievrz .
I'm closing this pull request. As defined by @Julievrz we will update wording when it will be needed depending on the context :)

**Comment by mvorisek** [comment]
the contexts in this PR are exactly the one that needs to be updated to fix the English grammar, therefore please reopen

**Comment by PierreRambaud** [comment]
As it was said by @Julievrz it will be easier to improve wording page per page, not editing all wordings in a single PR.

**Comment by Julievrz** [comment]
> the contexts in this PR are exactly the one that needs to be updated to fix the English grammar, therefore please reopen

I don't think we should only correct grammar here. I'll explain why:

Replacing "Can not" with "Cannot" in all these strings will create new strings. These new strings will have to be translated by the community of translators again. For this reason, we should make sure that the new strings we are creating are optimal so that we don't need to modify them again later (otherwise, translators will have to translate similar strings again and again). 

And it will be easier to improve the strings in their context. 

Please know that the wording will be improved as we go along with the Content style guide.

**Comment by mvorisek** [comment]
ah, so you want to correct the EN translations only to match not the source strings

This makes sense, however, I think the source strings should be updated together then and all keys for mapping to the languages as well

**Pull request closed without merging**
