### PR TITLE
Display "Free shipping" cart rule correctly

### PR DESCRIPTION
**Pull request by idnovate**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Display "Free shipping" cart rule correctly image
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | Fixes issue #9702 and #13644 (duplicate)
| How to test?  | Create "Free shipping" cart rule and check order summary image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13645)

### CODE REVIEW

**Review by jolelievre — COMMENTED** [review]
This seems legit to me, @tomlev since you've been working on free shipping lately (even though it's in the calculator). Do you have any remark?

**Comment by tomlev** [comment]
@idnovate did you test with a not null cart rule offering free shipping (eg 5€ discount, AND free shipping) ?

**Comment by idnovate** [comment]
@tomlev Oh you are right, won't work, discount would not be aggregated.

If discount is an amount would be simple, for example:
 
```
if (isset($cartVoucher['reduction_amount']) && $cartVoucher['reduction_amount'] > 0) {
    if (isset($cartVoucher['free_shipping']) && $cartVoucher['free_shipping']) {
        $cartVoucher['reduction_amount'] += $cart->getTotalShippingCost(null, $this->includeTaxes());
    }
    $cartVoucher['reduction_formatted'] = $this->priceFormatter->convertAndFormat($cartVoucher['reduction_amount']);
}
```

But what to do with a percentage discount?

**Comment by jolelievre** [comment]
I guess you would need to compute it? @tomlev wdyt?

**Comment by tomlev** [comment]
@colinegin what should be displayed in case of discount offering free shipping AND percentage discount ?

**Comment by colinegin** [comment]
Hello @tomlev ,

you mean what should be the discount displayed (XX%) ? 
If so, then i guess it should sum up the discount price (let's say 5€) + the cart discount (if 20% on a cart with 100€ value then 20€ discount) = 25€. 

Then it should either show :
Discount -25€
or 
Discount -23,80% (i'm actually wondering if we should consider the cart value only or the cart + shipping value).

Wdyt @tomlev and @marionf ?

**Comment by marionf** [comment]
The "discount" line is always in amount
The "cart rule" line is also displayed in amount if you have a percent discount and a free gift 
We can do the same for a percent discount and free shipping.
I think it's more clear to have the same thing displayed for both lines

**Comment by colinegin** [comment]
Alright I'm ok with this option.
But then isn't it weird that we display it in % if this is only a %age discount ?

**Comment by marionf** [comment]
You mean display the amount below if it's only a percent discount ?

capture d'écran_1646

**Comment by colinegin** [comment]
Yes exactly. Shouldn't we display an amount value in every cases for more consistency ?

**Comment by marionf** [comment]
Yes, it could be good :)

**Review by jolelievre — APPROVED** [review]
Thank you @idnovate

**Comment by idnovate** [comment]
@jolelievre Be careful, there were bugs

**Comment by jolelievre** [comment]
> @jolelievre Be careful, there were bugs

Really? I tested it out quickly it seemed to work. Which bugs did you notice then?

**Comment by idnovate** [comment]
> > @jolelievre Be careful, there were bugs
> 
> Really? I tested it out quickly it seemed to work. Which bugs did you notice then?

This case: https://github.com/PrestaShop/PrestaShop/pull/13645#issuecomment-489590593

**Comment by jolelievre** [comment]
> This case: [#13645 (comment)](https://github.com/PrestaShop/PrestaShop/pull/13645#issuecomment-489590593)

Ok thank you Then do you think you have time to fix this issue? It's not urgent of course.
Or would like me to continue your PR and fix this second issue?

**Comment by idnovate** [comment]
I would like you to wait :)

**Comment by jolelievre** [comment]
> I would like you to wait :)

Sure, no problem ;)

**Comment by marionf** [comment]
Hello @idnovate 

Will you have time to look at this soon ?

**Comment by idnovate** [comment]
@jolelievre @marionf 

You can continue the PR if you can :raised_hands::raised_hands:

**Comment by marionf** [comment]
Hello @idnovate 

Thank you for your contribution, the issue #9702 has been fixed by #16235
So, I close your PR

**Pull request closed without merging**
