### PR TITLE
[-] BO : Fix bug #PSCSX-5364 - Missing retina option

### PR DESCRIPTION
**Pull request by jnadaud**

### CODE REVIEW

**Comment by gRoussac** [comment]
:x :point_up_2:

**Comment by tchauviere** [comment]
:+1:

**Review by MockoB — COMMENTED** [review]
Hi. Did any one actually tested retina images on real device? I think that all images should be "@2x" instead "2x". I changed it in all php files I found it and regenerated images but when I open the shop with ipad or Iphone it doesn't call the @2x images? Please advice me what to do to get real retina images on high density pixel devices?

**Comment by kpodemski** [comment]
@MockoB you have code behind that in your global.js, from what i remember it was indeed `2x` instead of `@2x`

yep, https://github.com/PrestaShop/PrestaShop/blob/1.6.1.x/themes/default-bootstrap/js/global.js#L114

**Comment by MockoB** [comment]
Thanks @kpodemski I changed the 2x with @2x on line 125 cleared cache with recompile, regenerated images but still the ipad is calling the non @2x image. Actually I saw that the code posted above is different than 1.6.1.11 files at least there isn't any @2x files in the admincategoriescontroller.php. So just to mention that there are already @3x images that must be generates within @2x. Any advice is welcome!

**Comment by MockoB** [comment]
Or maybe it is not @2x issue it could be media query missing ? Because after all the @2x images are generated no matter if they are 2x or @2x, but they just don't display! I am not a programmer but I desperately need HQ images on my shop so if there is any one knowledgeable please help.

**Pull request merged**
