### PR TITLE
Fix search results if shop has non-default 'visitor' group and categories that are only accessible for the non-default visitor group

### PR DESCRIPTION
**Pull request by fgschaefer**
in getCurrentCustomerGroups function, if user is not logged in (no customer present), return default value instead of empty list.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fixes search results if shop has non-default 'visitor' group and categories that are only accessible for the non-default visitor group.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | PSCSX-8515 http://forge.prestashop.com/browse/PSCSX-8515?jql=labels%20%3D%20search
| How to test?  | set visitor group to different group than the default (id 1) and configure one ore more categories so that the default visitor group (id 1) does not have access to this category, but the configured non-default visitor group has. before this bug fix, products of this category can not be found by the search. after this PR is applied, those products do correctly appear in search results.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13073)

### CODE REVIEW

**Comment by Eolia** [comment]
No, it's a bad idea.
look in the classes where this function is called. If the array exists an implode () is thrown each time while the default value is 1.
In terms of performance so it's not ideal to create a array to convert it into a string in the end

**Comment by fgschaefer** [comment]
Ok, so would it be better to replace the hardcoded default of "1" with something like `(int) Group::getCurrent()->id` at all places where the function is called? Like it was already done in [Category.php on line 898](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Category.php#L898)?

**Comment by Eolia** [comment]
In terms of performance, the best is 1 (this group ID can never be modified)
Why call a static and run code that will return 1 in the end?
Sometimes I have trouble understanding the reasoning ...

**Comment by Matt75** [comment]
With multishop, the default group can be another ID of 1

**Comment by Eolia** [comment]
Oh @Matt75 ...
The 1 is not the defaultgroup but the unidentified group ID^^
=> Configuration::get('PS_UNIDENTIFIED_GROUP')

**Comment by Matt75** [comment]
Configure > Shop Parameters > Customers > Groups

I create 3 shops, for Shop 2 & 3, I create new group and assign it to be new Visitor Group in `DEFAULT GROUPS OPTIONS` below the groups list

So in the database , I have this now

id_configuration | id_shop_group | id_shop | name | value
------------ | ------------- | ------------- | ------------- | -------------
160 | NULL | NULL | PS_UNIDENTIFIED_GROUP | 1
742 | 1 | 2 | PS_UNIDENTIFIED_GROUP | 4
743 | 1 | 3 | PS_UNIDENTIFIED_GROUP | 5


id_group | id_shop | name
-- | -- | --
1 | 1 | Visitor
4 | 2 | Visitor shop 2
5 | 3 | Visitor shop 3

So the default group (visitor aka PS_UNIDENTIFIED_GROUP) can be modified

**Comment by Eolia** [comment]
Yes, so replace 1 by  (int)Configuration::get('PS_UNIDENTIFIED_GROUP')

**Comment by Matt75** [comment]
# CategoryCore
is already patched by `(int) Group::getCurrent()->id` https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Category.php#L898

--------------------

# ManufacturerCore
has to be patched here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Manufacturer.php#L216
and to be patched here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Manufacturer.php#L407

--------------------

# ProductCore
is already patched by `(int) Configuration::get('PS_UNIDENTIFIED_GROUP')`
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Product.php#L2596
and not here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Product.php#L2652
and not here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Product.php#L2741
and not here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Product.php#L2866


# ProductSaleCore
has to be patched here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/ProductSale.php#L141
and here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/ProductSale.php#L218

--------------------

# SearchCore
has to be patched here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Search.php#L274
and here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Search.php#L864

--------------------

# SupplierCore
has to be patched here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Supplier.php#L147
and here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Supplier.php#L311

--------------------

# TagCore
has to be patched here
https://github.com/PrestaShop/PrestaShop/blob/84c2b03ad7c78de0e1ffb1b7cf454988a4efaa0f/classes/Tag.php#L201

--------------------

@PrestaShop/prestashop-core-developers 
Should we use `(int) Group::getCurrent()->id` OR ``(int) Configuration::get('PS_UNIDENTIFIED_GROUP')``

**Comment by Eolia** [comment]
(int) Configuration::get('PS_UNIDENTIFIED_GROUP') because it already loaded on memory on each page as a static value :)

**Comment by Matt75** [comment]
Same for Group::getCurrent()->id there is a static cache

I ask Core Team, you have already give your opinion thanks.

**Comment by Eolia** [comment]
As you want.
I like when the names are explicit.

**Comment by Matt75** [comment]
I looked into test suite, `Group::clearCachedValues()` is called one time in `LegacyTests\Integration\classes\CartGetOrderTotalTest::setUp()` but Configuration was reloaded too and `Group::getCurrent()` is initialized with  `Configuration::get('PS_UNIDENTIFIED_GROUP')`.

I think we can use `Configuration::get('PS_UNIDENTIFIED_GROUP')` instead of `Group::getCurrent()->id` without risk for test suite and it will be more efficient as @Eolia said.

@fgschaefer Could you update your Pull Request ?
In fact, no need to change  `FrontControllerCore::getCurrentCustomerGroups()` but you can replace `1` with `(int) Configuration::get('PS_UNIDENTIFIED_GROUP')` in every place I listed in https://github.com/PrestaShop/PrestaShop/pull/13201#issuecomment-479995615
In order to uniformize code, please update `CategoryCore` too.

Thanks for your contribution :)

**Comment by fgschaefer** [comment]
OK @Matt75  i changed this as you suggested.
I don't use php that much so i don't know what performance implications an implode for an array with just one element has. On the other side it seemed clean to let `FrontControllerCore::getCurrentCustomerGroups` return just what it says and don't have to have a special case everywhere it is used. The current situation looks like that this leads to some inconsistencies, because everyone that uses this function has to know some more details, e.g. that the visitor group can be configured to another value than 1, and how to retreive this value in a standard manner.

**Comment by Matt75** [comment]
True, this apply in general to all legacy classes. Misnamed method, undocumented method or obsolete phpdoc, inconsistency of returns and behavior etc
That’s why (and more others reasons) core team migrate step by step to another architecture as you can see in src folder.

In fact developers should not use directly legacy classes if they can, that’s why there are adapter and core folder in src.

That’s a huge work and its still in progress.
In legacy classes we only patch code and improvement are mostly done in src folder.

You can read more on http://build.prestashop.com/news/prestashop-in-2019-and-beyond-part-1-current-architecture/

Let’s core team take the final decision for this pull request ;)

Thanks for your work

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
