### PR TITLE
Merge `8.1.x` into `develop`

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge `8.1.x` into `develop`
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 & [Autotests](https://github.com/boherm/ga.tests.ui.pr/actions/runs/5657192861) 🟢
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by boubkerbribri — DISMISSED** [review]
LGTM for UI tests

**Review by mflasquin — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @boherm ,

Thanks for the auto tests.

Tested the following :

- Creation of products
- Checkout process
- Intallation modules
- Creation of customer

LGTM ✅

**Review by boubkerbribri — APPROVED** [review]

**Comment by matks** [comment]
@boherm Don't forget the milestone ;)

**Comment by boherm** [comment]
Oupsii 😅

**Pull request merged**
