### PR TITLE
[-] Core : Fix SpecificPrice when there are more that $threshold of them

### PR DESCRIPTION
**Pull request by tiennou**
This fixes an issue where if you have more that 1000 Specific Price in the database, none of them are applied.

### CODE REVIEW

**Comment by xBorderie** [comment]
Hi @tiennou! We had our QA team take a lot at the issue of SpPrices not being applied if there were a thousand of them, and it doesn't seem to change anything.
Could you give us a step-by-step process to reproduce this everytime?
Thank you!

**Comment by tiennou** [comment]
I'm sorry, I don't understand the context you're in. Do you mean that applying that PR "doesn't seem to change anything", implying that there is no issue on your side ?

I'm not sure about the reproduction steps, as I'm no longer trying to use Prestashop for our shop. IIRC I was working on adding support for applying specific prices to a category and all its subcategories (in contrast to the current "only products in that category are affected"), and hit the bug because I had like 2700 products in the database, so it made (expectedly) 2700 specific prices, but there were ignored as there were more than 1000 — the threshold.

Reading the [code](https://github.com/PrestaShop/PrestaShop/blob/7e25cddd7dc1e8c227cb621460b2683d16149446/classes/SpecificPrice.php) in `master` again I'm pretty sure it still happens :
- filterOutField is called with arguments 'id_products', and some product ID.
- L214 `$query_extra` is initialized to be `AND 'id_product' = 0`
- L220 there's no cache for that field yet so the branch is taken
- L221 we count the prices in the table by doing a `id_product` != 0. Since there are 2700 prices in there, each applying to a different product, this count is returned by the DB (the DISTINCT doesn't do anything).
- L228 there are more than $threshold prices in the table so the if-branch doesn't execute
- L235 we store an incorrect, empty list in cache.
- L244 we return the default `$query_extra`, and no specific prices are applied.

**Comment by jocel1** [comment]
Hi @tiennou ,

I think the issue you are referring is fixed by https://github.com/PrestaShop/PrestaShop/pull/4412/files which is already integrated.

**Comment by tiennou** [comment]
Yep, looks like it is then. Since I can't really reproduce it, I'm gonna close this one.

**Comment by xBorderie** [comment]
Thank you for your contribution!

**Pull request closed without merging**
