### PR TITLE
Added values and amounts with and without taxes #27652

### LINKED ISSUE #27652: Subtotal of Shipping and Products in order-confirmation-table.tpl with and without tax
Hi there,

today i inspected the variables of the template file `order-confirmation-table.tpl` from classic theme. 

The file is included twice:
1. From the payment step at the order page 
2. From the order-confirmation page after purchase

it gets the variables added for totals, subtotals and products but the variables differ from inside out. The Products Object is completely differtent and the keys are named differently (exept for those, classic theme uses default).

to get these prices side by side some simple adoptions would make them accessible.

is there a specific reason why not both values are available as variables for subtotals? including and excluding taxes?

Order-Page Payment Step:
**Current solution**
```
{if $subtotal.type === 'shipping'}
    {assign var='subtotal_value_exc' value=Context::getContext()->cart->getOrderTotal(false, Cart::ONLY_SHIPPING) }
{elseif $subtotal.type === 'products'}
    {assign var='subtotal_value_exc' value=Context::getContext()->cart->getOrderTotal(false, Cart::ONLY_PRODUCTS) }
{/if}
```

Order-Confirmation Page:
It would be a two-liner at https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Order/OrderSubtotalLazyArray.php#L140

to add these values
```return [
                // is allready there
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),

                // is missing
                'amount_excl_tax' => $this->order->total_shipping_tax_excl,
                'amount_incl_tax' => $this->order->total_shipping_tax_incl,
            ];
```

Then it would be possible to write in [order-confirmation-table.tpl](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/checkout/_partials/order-confirmation-table.tpl#L110):
```
{assign var='subtotal_value_exc_format' value=Context::getContext()->currentLocale->formatPrice($subtotal.amount_excl_tax, Context::getContext()->currency->iso_code) }
{$subtotal_value_exc_format}
```
This also applies to products!

But it looks like impossible to get that variable out of the system. How can i override that file? is that possible for "/scr/Adapter" paths? (I tried allready but does not activate somehow)

Also i could imagine to get the variables like so:
```return [
                // is allready there
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),

                // handy variables for theme developers:
                'amount_excl_tax' => $this->order->total_shipping_tax_excl,
                'amount_incl_tax' => $this->order->total_shipping_tax_incl,
                'value_excl_tax' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $this->order->total_shipping_tax_excl,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
                'value_incl_tax' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $this->order->total_shipping_tax_incl,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                )
                    : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
            ];
```

you also can comment my latest workaround:
```
            {if $subtotal.type === 'shipping'}
              {assign var='shipping_data' value=$order.details->getShipping() }
              {assign var='subtotal_value_exc' value=$shipping_data[0].shipping_cost_tax_excl }
            {/if}
```
now only the products subtotals are missing...

// some times later...
**Finaly i ended up overwriting** the original file it self so i can use that values.

_Originally posted by @netzgestaltung in https://github.com/PrestaShop/PrestaShop/issues/12743#issuecomment-1036408651_

### PR DESCRIPTION
**Pull request by netzgestaltung**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | To freely display all price values with or without taxes these ones are missing. <br> Seems to be common in other classes like Cart, Product and so on.
| Type?             | improvement / consistency
| Category?         | FO
| BC breaks?        | ?
| Deprecations?     | no
| Fixed ticket?     | Fixes #27652.
| How to test?      | In Classic Theme find `/templates/checkout/_partials/order-confirmation-table.tpl`. Inside the file find `{foreach $subtotals as $subtotal}`. Add `{$subtotal.amount_excl_tax\|var_dump}`, `{$subtotal.value_excl_tax\|var_dump}`, `{$subtotal.value_incl_tax\|var_dump}`, `{$subtotal.value_incl_tax\|var_dump}`. Purchase and see the Order Confirmation Table afterwards.
| Possible impacts? | There may be necessary adoptions to the variables at the Order Page because it includes the same tpl file with differing variables.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27653)

### CODE REVIEW

**Comment by Hlavtox** [comment]
Hi @netzgestaltung, very good idea, this could be a very nice addition. I want to add all with/without totals to everywhere in backoffice, this would be a huge part of the work. :-)

I have 2 requests for you:

### 1 - I think we should follow the schema that is already used in totals
Both in cart - https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Cart/CartPresenter.php#L396
And in order - https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Order/OrderLazyArray.php#L240

So, can you implement it, so the final presented array looks like this? For products, shipping, discounts and gift wrapping?
```
            'products' => [
                'type' => 'products',
                'label' => $this->translator->trans('Subtotal', [], 'Shop.Theme.Checkout'),
                'amount' => $this->includeTaxes() ? $total_including_tax : $total_excluding_tax,
                'value' => $this->priceFormatter->format(
                    $this->includeTaxes() ? $total_including_tax : $total_excluding_tax
                ),
            ],
            'products_including_tax' => [
                'type' => 'products',
                'label' => $this->translator->trans('Subtotal (tax incl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $this->order->total_products,
                'value' => $this->priceFormatter->format($total_including_tax),
            ],
            'products_excluding_tax' => [
                'type' => 'products',
                'label' => $this->translator->trans('Subtotal (tax excl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $this->order->total_products_wt,
                'value' => $this->priceFormatter->format($total_excluding_tax),
            ],
```

### 2 - Can you also add the same to cart presenter, so we can use it in front office also?
It would be good if we could also use the same scheme for cart - products, shipping, discounts. Both with and without tax. :-)

https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Cart/CartPresenter.php#L338

**Comment by netzgestaltung** [comment]
Hi @Hlavtox ,

thank you for the warm welcome.

At the Order-Page i currently implemented only a template basis workaround:
```
{if $subtotal.type === 'shipping'}
    {assign var='subtotal_value_exc' value=Context::getContext()->cart->getOrderTotal(false, Cart::ONLY_SHIPPING) }
{elseif $subtotal.type === 'products'}
    {assign var='subtotal_value_exc' value=Context::getContext()->cart->getOrderTotal(false, Cart::ONLY_PRODUCTS) }
{/if}
```
so there is already a `Cart->getOrderTotal()` Method but it works completely different than the comparing Methods for Orders.

I think it would be good to implement that getOrderTotal into Orders if Possible and then add these values in a unified way.

On next workday i will look into it. Followind schemas is fine for me if i can interpret them.

Best
Tom

**Comment by netzgestaltung** [comment]
Hi,

~~i think you missed the topic slightly. Its not about the totals but the sub-totals.~~
Ah i see you want it that way. I am not sure if that's possible without breaking existing themes (classic). But i will consider it.

So i believe i allready follow that schema: 
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Cart/CartPresenter.php#L338

The order subtotals are not created in `OrderLazyArray.php` but in `OrderSubtotalLazyArray.php` which i made the first commit. 
You see the method call here: https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Presenter/Order/OrderLazyArray.php#L88

kind regards
tom

**Comment by netzgestaltung** [comment]
Please note that there are also other naming conventions present as well. you find in 
OrderLazyArray.php
```php
        ['total_excluding_tax'] = [
            'type' => 'total_excluding_tax',
            'label' => $this->translator->trans('Total (tax excl.)', [], 'Shop.Theme.Checkout'),
            'amount' => $order->total_paid_tax_excl,
            'value' => $this->priceFormatter->format(
                $order->total_paid_tax_excl,
                Currency::getCurrencyInstance((int) $order->id_currency)
            ),
        ];
```
and in CartPresenter.php:
```php
            'total_including_tax' => [
                'type' => 'total',
                'label' => $this->translator->trans('Total (tax incl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $total_including_tax,
                'value' => $this->priceFormatter->format($total_including_tax),
            ],
            'total_excluding_tax' => [
                'type' => 'total',
                'label' => $this->translator->trans('Total (tax excl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $total_excluding_tax,
                'value' => $this->priceFormatter->format($total_excluding_tax),
            ],
```
See the difference in the `type` value. I choose the more specific one because in iterations you already can check the "more global" type in the parent array.

Also there was a bit of a mess with variable names which i tidy in the process.

Now i edited both arrays the same way:

CartPresenter.php
```php
        $subtotals['products'] = [
            'type' => 'products',
            'label' => $this->translator->trans('Subtotal', [], 'Shop.Theme.Checkout'),
            'amount' => $products_total_amount,
            'value' => $this->priceFormatter->format($products_total_amount),
            'subtotal_including_tax' => array(
                'type' => 'products_including_tax',
                'label' => $this->translator->trans('Subtotal (tax incl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $products_total_including_tax,
                'value' => $this->priceFormatter->format($products_total_including_tax),
            ),
            'subtotal_excluding_tax' => array(
                'type' => 'products_excluding_tax',
                'label' => $this->translator->trans('Subtotal (tax excl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $products_total_excluding_tax,
                'value' => $this->priceFormatter->format($products_total_excluding_tax),
            ),
        ];
        // ...        
        $subtotals['shipping'] = [
            'type' => 'shipping',
            'label' => $this->translator->trans('Shipping', [], 'Shop.Theme.Checkout'),
            'amount' => $shippingCost,
            'value' => $this->getShippingDisplayValue($cart, $shippingCost),
            'subtotal_including_tax' => array(
                'type' => 'shipping_including_tax',
                'label' => $this->translator->trans('Shipping and handling (tax incl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $shipping_total_including_tax,
                'value' => $this->priceFormatter->format($shipping_total_including_tax),
            ),
            'subtotal_excluding_tax' => array(
                'type' => 'shipping_excluding_tax',
                'label' => $this->translator->trans('Shipping and handling (tax excl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $shipping_total_excluding_tax,
                'value' => $this->priceFormatter->format($shipping_total_excluding_tax),
            ),
        ];
```
OrderSubtotalLazyArray.php:
```php
        return [
            'type' => 'products',
            'label' => $this->translator->trans('Subtotal', [], 'Shop.Theme.Checkout'),
            'amount' => $totalProducts,
            'value' => $this->priceFormatter->format(
                $totalProducts,
                Currency::getCurrencyInstance((int) $this->order->id_currency)
            ),
            'subtotal_including_tax' => array(
                'type' => 'products_including_tax',
                'label' => $this->translator->trans('Subtotal (tax incl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $this->order->total_products_wt,
                'value' => $this->priceFormatter->format(
                    $this->order->total_products_wt,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                ),
            ),
            'subtotal_excluding_tax' => array(
                'type' => 'products_excluding_tax',
                'label' => $this->translator->trans('Subtotal (tax excl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $this->order->total_products,
                'value' => $this->priceFormatter->format(
                    $this->order->total_products,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                ),
            ),
        ];
        // ...
            return [
                'type' => 'shipping',
                'label' => $this->translator->trans('Shipping and handling', [], 'Shop.Theme.Checkout'),
                'amount' => $shippingCost,
                'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                    $shippingCost,
                    Currency::getCurrencyInstance((int) $this->order->id_currency)
                ) : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
                'subtotal_including_tax' => array(
                    'type' => 'shipping_including_tax',
                    'label' => $this->translator->trans('Shipping and handling (tax incl.)', [], 'Shop.Theme.Checkout'),
                    'amount' => $this->order->total_shipping_tax_incl,
                    'value' => $this->priceFormatter->format(
                        $this->order->total_products_wt,
                        Currency::getCurrencyInstance((int) $this->order->id_currency)
                    ),
                ),
                'subtotal_excluding_tax' => array(
                    'type' => 'shipping_excluding_tax',
                    'label' => $this->translator->trans('Shipping and handling (tax excl.)', [], 'Shop.Theme.Checkout'),
                    'amount' => $this->order->total_shipping_tax_excl,
                    'value' => $shippingCost != 0 ? $this->priceFormatter->format(
                        $this->order->total_shipping_tax_excl,
                        Currency::getCurrencyInstance((int) $this->order->id_currency)
                    ) : $this->translator->trans('Free', [], 'Shop.Theme.Checkout'),
                ),
            ];
            
```

so please check again.

**Comment by Hlavtox** [comment]
Hi, it seems you copied your whole **CartPresenter.php** with some unwanted changes, can you check?

Looks better, but still does not follow the structure we have in totals.

Instead of:
```
        $subtotals['products'] = [
            'type' => 'products',
            'label' => $this->translator->trans('Subtotal', [], 'Shop.Theme.Checkout'),
            'amount' => $products_total_amount,
            'value' => $this->priceFormatter->format($products_total_amount),
            'subtotal_including_tax' => array(
                'type' => 'products_including_tax',
                'label' => $this->translator->trans('Subtotal (tax incl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $products_total_including_tax,
                'value' => $this->priceFormatter->format($products_total_including_tax),
            ),
            'subtotal_excluding_tax' => array(
                'type' => 'products_excluding_tax',
                'label' => $this->translator->trans('Subtotal (tax excl.)', [], 'Shop.Theme.Checkout'),
                'amount' => $products_total_excluding_tax,
                'value' => $this->priceFormatter->format($products_total_excluding_tax),
            ),
        ];
```

Do:
```
          $subtotals['products'] = [
            'type' => 'products',
            'label' => $this->translator->trans('Subtotal', [], 'Shop.Theme.Checkout'),
            'amount' => $products_total_amount,
            'value' => $this->priceFormatter->format($products_total_amount),
          ];
          $subtotals['subtotal_including_tax'] =  [
            'type' => 'products_including_tax',
            'label' => $this->translator->trans('Subtotal (tax incl.)', [], 'Shop.Theme.Checkout'),
            'amount' => $products_total_including_tax,
            'value' => $this->priceFormatter->format($products_total_including_tax),
          ];
          $subtotals['subtotal_excluding_tax'] =  [
            'type' => 'products_excluding_tax',
            'label' => $this->translator->trans('Subtotal (tax excl.)', [], 'Shop.Theme.Checkout'),
            'amount' => $products_total_excluding_tax,
            'value' => $this->priceFormatter->format($products_total_excluding_tax),
          ];
```

**Comment by Hlavtox** [comment]
In case of the OrderSubtotalLazyArray, just create new functions
`public function getShippingIncludingTax()`
`public function getShippingExcludingTax()`
etc. 👍

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@netzgestaltung Thank you for your contribution. Could you fix firstly the CI ? Thanks

**Comment by netzgestaltung** [comment]
Hi, 
i was in heavy crunchy work-load to publish the shop i was working on. Currently i have a few days break an will come back on that topic in the next week. Stay tuned.

**Comment by matks** [comment]
Hello,

It looks like this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

@netzgestaltung don't worry we can reopen the PR when you have some time and motivation 😉 just ping me

Thank you

**Pull request closed without merging**
