### PR TITLE
"Pay What You Want" (french "prix libre") implementation.

### PR DESCRIPTION
**Pull request by drzraf**
Hi,
in this pull request is implemented a feature known as "Pay What You Want" (in french "prix libre").
When set for a product, its price becomes an `<input>` where the customer can freely choose how much he wants to put/spend/contribute/....
There are so many use cases that I won't enumerate.

Since it requires core-database columns additions and core function modifications, making this a module was out of scope (as an example "gift" functionality is in the core). But please note that no module is modified nor _should_ require modification. And it should be safe for the PoV of hook-consumers (but that's not a 100% sure statement)

From a diff --stat PoV the patch seems intrusive (it is), but if you look at it, and with exception of DB structure changes,, most "Pay What You Want"-related lines are encapsulated in a condition either about product support for the feature or about a consumer-provided price has been provided in the frontend. So I would say that it's safe.

Let me just elaborate technically (see the below commit message for additional information) :
I worked against 1.6.0.14 (since we lacks development space and have fixes there which are waiting to be pushed [see PHP::Memcached and others]).
Today I tried the merge against 1.6 but there were a lot of trivial **but still painful** conflicts (Cart.php, Product.php, ajax-cart.js, ...)
I resolved the merge for the sake of this pull-request **but** since I'll not develop against 1.6, I'd would rather appreciate (very deeply) that a maximum of comments about the pull-request could be done now so that it doesn't require me to do painful and redundant merges against 1.6

Please tell me how you feel about the implementation, if there missing bits, ....
For sure the UI side on product.tpl is far from perfect. PS savvy UI/developers may think of a best UI for quantity and price in the context of Pay-What-You-Want products.

Please note that this work is intended for a NGO, thus:
0) I tried to get this initial patch realistically stable and mergeable
1) we don't have the capacity to spend months reshaping the patch too many times
2) the quicker it's accepted, the better since we just can't afford to maintain such a patch applied on our shop during a large period of time.

Follows the commit's text:

The patch would benefit from some API changes
(the backend is not well adapted for cart modifications other than quantities)
- Product::getPriceStatic() support for free-price (after defining how to pass the value)
- The CartController processChangeProductInCart() is difficult to adapt when modifications
  other values than the quantity happen (it postulates that changing a product in the cart is always
  inc/dec the quantity of said product).

Some work is left:
- total w/wo shipping & co calculations may need some love (pwyw should be assumed tax-included)
- initial pwyw price setting which is a bit confusing because highly bound
  to quantity updates handlers. UI modification may be needed.
- Attributes and multiples delivery addresses _should_ be handled but haven't been tested
  so far. Customizations have been ignored/skipped when possible: multiples pwyw-enabled
  products differing only by there customization id will all get the same newest pwyw-price
  (if this situation is even possible)

Conflicts:
    admin-dev/themes/default/template/controllers/orders/_product_line.tpl
    classes/Cart.php
    classes/Product.php
    pdf/invoice.tpl
    themes/default-bootstrap/js/modules/blockcart/ajax-cart.js
    themes/default-bootstrap/product.tpl

### CODE REVIEW

**Comment by djfm** [comment]
Hi @drzraf, this sounds interesting, thank you, but we think this type of feature should rather be implemented as a module than in the core. If, however, the core lacks feature that would make such a module possible, feel free to PR the minimal changes needed for the module to work.

Kind regards,
François-Marie

**Comment by drzraf** [comment]
Hi,
thank you for the analysis.

I've a couple of doubts about the modularisation of this feature I would
really love to see clarified before putting an end to this PR:
$ git show --stat
```
.../template/controllers/orders/_product_line.tpl  |   1 +
.../template/controllers/products/prices.tpl       |  11 ++
classes/Cart.php                                   | 120 +++++++++++++++++--
classes/Product.php                                |   4 +
classes/order/OrderDetail.php                      |   6 +
controllers/admin/AdminProductsController.php      |   6 +-
controllers/front/CartController.php               |  81 ++++++++++---
controllers/front/ProductController.php            |   2 +
install-dev/data/db_structure.sql                  |   4 +
install-dev/upgrade/sql/1.6.0.15.sql               |   4 +
modules/blocklayered                               |   2 +-
pdf/invoice.tpl                                    |   2 +-
themes/default-bootstrap/css/product.css           |   8 +-
themes/default-bootstrap/js/cart-summary.js        | 132 +++++++++++++++++++--
.../js/modules/blockcart/ajax-cart.js              |   9 +-
themes/default-bootstrap/js/product.js             |  13 ++
themes/default-bootstrap/product-list.tpl          |   5 +-
themes/default-bootstrap/product.tpl               |  39 +++++-
.../shopping-cart-product-line.tpl                 |  23 ++++
```

1. Templates
* admin-dev/themes/default/template/controllers/*
* themes/default-bootstrap/product-list.tpl
* themes/default-bootstrap/product.tpl
* themes/default-bootstrap/shopping-cart-product-line.tpl
* pdf/invoice.tpl

I can not see how to "hook" into these templates without having to
copy/paste/override/maintain upstream templates.

2. Core classe
* classes/Cart.php
* class/Product.php
* classes/order/OrderDetail.php

Pay What You Want affects price calculation at the deepest level (tax
calculations, ...), see the patch hunk related to the CartCore.

I may have missed a point, but how could such changes be implemented
properly as a module?

3. Please note that the ecotax stuff does not seems so intrusive (price
calculation, UI, ...) is implemented in core.

4. DB structure. "Pay What You Want", even if implemented in a
declinaison-compliant way, is about the Product Object Model
(ProductCore). See install-dev/data/db_structure.sql
How could a new attribute appears in Product.php without a core patch?
(cf issue n°2 above)

5. assets
* css maybe be easily overrided
* $(.cart_pwyw_price_change).change() could be implemented in an external javascript
* updatePWYW() too
* hunk about themes/default-bootstrap/js/product.js too
Thus cart-summary.js is not an issue... but ajax-cart.js is.
The same way the CartCore has to be changed, the ajaxCart javscript
needs patching (to handle *properly* the PWYW product addition).
If not, any hint about how it could be extended would be really
appreciated?

6. The PS core/module relation is a bit unclear since, for example the blockcart
appears in many way very "core-related". See the references to blockcart
concept inside the theoretically module-agnostic themes/default-bootstrap/js/cart-summary.js.
[or even the presence of themes/default-bootstrap/js/modules/ which is a
bunch of module-specific things bundled in the core default theme]
How would I, myself, do a better work than pro upstream in this regard?

Any advise on these questions would be greatly appreciated!

**Comment by drzraf** [comment]
Any hope to get some hints about the above?
Eg: since this feature alters the back-office UI. But  there is no way that I know to override admin' templates.
I can implement some parts using of module/override, but it's less than ideal when it comes to "large" functions (or when other module may need the privilege of overriding base classes).

**Comment by drzraf** [comment]
I was able to override an admin template at the price of overriding classes/controller/AdminController.php  !!
```php
<?php

class AdminController extends AdminControllerCore
{
  public function addAdminTemplateOverride() {
    if(! in_array(_PS_MODULE_DIR_ . 'paywhatyouwant/override/controllers/admin/templates/', $this->context->smarty->getTemplateDir()))
      $this->context->smarty->addTemplateDir(_PS_MODULE_DIR_ . 'paywhatyouwant/override/controllers/admin/templates/');
  }

  public function createTemplate($tpl_name)
  {
    // Use override tpl if it exists
    // If view access is denied, we want to use the default template that will be used to display an error
    if ($this->viewAccess() && $this->override_folder) {
      if (!Configuration::get('PS_DISABLE_OVERRIDES') && file_exists($this->context->smarty->getTemplateDir(1).DIRECTORY_SEPARATOR.$this->override_folder.$tpl_name)) {
        return $this->context->smarty->createTemplate($this->override_folder.$tpl_name, $this->context->smarty);
      } else {
        $this->addAdminTemplateOverride();
        foreach(array_reverse($this->context->smarty->getTemplateDir()) as $tpl_dir) {
          if(file_exists($tpl_dir . 'controllers'.DIRECTORY_SEPARATOR.$this->override_folder.$tpl_name))
            return $this->context->smarty->createTemplate('controllers'.DIRECTORY_SEPARATOR.$this->override_folder.$tpl_name, $this->context->smarty);
        }
      }
    }

    return $this->context->smarty->createTemplate($this->context->smarty->getTemplateDir(0).$tpl_name, $this->context->smarty);
  }
}
```

We this I can ... add a simple checkbox to the information tab of the AdminProductsController
(these per-tabs template do not use the FormModifier which may have been smoother).

Anyway, when it comes to overriding theme's component it's just impossible.
Obviously, the ```displayProduct*``` hook are never placed where one would like.
Moreover the ```{include}``` smarty statement, as currently used, does not give way for path override.
Eg: category.tpl:
contains
```{include file="./product-list.tpl" products=$products}```
but I didn't find anyway to give priority to mymodule/tpl/override/product-list.tpl

thank you in advance for your support

**Comment by drzraf** [comment]
Is there any point for me to continue here ??
cart-summary.js updateCartSummary() needs a hook system where module can define javascripts to be run by the said function.
The interesting part if the ```for (i in product_list)  ``` loop.
where ```$('#total_product_price_...)``` is given a ```val()```

Eg, just after ```key_for_blockcart_nocustom```
call a function which grabs all defined hook for this step and pass the parameters.

Another painful diff part is that of ajax-cart.js, most of the changes are useless: they manually grab new "data" attributes (introduced by the templates) and pass them all along the function stack in order to only add them to the function add(), ajaxCart struct/ajax call.
Would be more generic that this function grab *all* data attributes found, serialize and send them.

If these javascript issues could be resolved, most of the problem would be concentrated in the template/theme + the need to override classes since no hook help here.
Side note: to add a complementary javscript to cart-summary.js, I add to override the setMedia() of override/controllers/front/ParentOrderController.php. It seems overkill.

**Comment by drzraf** [comment]
@djfm I spent another whole day on this (I already spent twice the time on the possibility of the module than on the core patch). It's near than impossible to implement this as a module.
1) hooks provided are not useful in this case
2) override do not makes a module, there are painful and bug-prone to deploy and keep one to use other modules using the same override. But as soon as an ObjectModel changes, override seems like the only possibility.
3) a part of the javascript could indeed be implemented in a module, but others can't: thus javascript files inside a theme has to be heavily changed.
4) templates are a pain to override and this is almost impossible in a module (unless you end-up copying and bundle a bunch of them)

Could you please reconsider you decision about core-patch functionality merge, or otherwise give me hope that PrestaShop is going to be more extensible in the next versions so that implementing the feature as a module becomes a **real** option?
thank you

**Comment by drzraf** [comment]
I started thinking about a minimal hook system on the javascript side.
Please have a look at #3646.
Many other hooks like this may need to be defined in various places before the javascript-part could be stated as "modularized".

**Comment by drzraf** [comment]
ping?

**Comment by drzraf** [comment]
@djfm ping ?

**Comment by Jolg42** [comment]
:+1:

**Comment by drzraf** [comment]
@jnadaud  does PSP 1.7 offers the hooks that would make that functionality possible?

**Comment by chefdeprojetrc** [comment]
@Shudrum can you respond ?
Thanks

**Comment by drzraf** [comment]
given:
- the original diff
- the above (misformated) diff-stat
- the precise explanation of what would need to change in order to have the feature implemented as a plugin
- attempts like PR #3646
- and given that the whole theme system has been rewritten
may I keep asking about PS 1.7 ability to support this feature (and thus ping-in this issue?)

More specifically:
* Does the new front-office theme-system resolve the issue of the  javascript/AJAX-embedded price logic which can't easily be overridden?
* Did back-office customizations became possible? (eg: additional checkbox in product page)
* Is price calculation now hookable?
* ...

**Comment by drzraf** [comment]
ping?

**Comment by drzraf** [comment]
ping?

**Pull request closed without merging**
