### PR TITLE
Fix Address form not work properly in customer account area

### LINKED ISSUE #34080: Address form not work properly in customer account area
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Tested on demo.prestashop.com
If you go to "account" and click update address (France) you need to enter states.
For some this bug exist only on Firefox or only on Chrome. On one my server with fresh PS install, bug seen in both browsers.
Reopen #33991.
On click Update on address in my-account area, form requesting enter state, even if country without states, Self-fixing only after manipulation with country change.

public function fillWith(array $params = []) called twice. Second call destroys country->id

### Expected behavior

No need enter states by default for France or other country with no states.

### Steps to reproduce
Clean browser cache before.
Go to demo.prestashop.com with 8.1.x version.
PS browser detection must be enabled.
PS must have enabled US country with states.
PS need to default US country (optional).
Ensure that your browser have default eu_US locale.
login as new customer and create address not US, all other without states.
Save address.
Click Update address.
Click Save.
 
https://github.com/PrestaShop/PrestaShop/assets/543458/a57f199d-05ec-4a6e-a859-14b1d1a78a2d

### PrestaShop version(s) where the bug happened

8.1.1 8.1.2

### PHP version(s) where the bug happened

8.2.10

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed issue or discussion?     | Fixes #34080, #35013

### CODE REVIEW

**Comment by Hlavtox** [comment]
@Codencode Bro, try not to open new and new and new PRs, please! :D It makes things not clear, we loose the comments for example. If you mess up the branch, I will help you fix it. :-)

**Comment by Codencode** [comment]
> @Codencode Bro, try not to open new and new and new PRs, please! :D It makes things not clear, we loose the comments for example. If you mess up the branch, I will help you fix it. :-)

@Hlavtox,
sorry, you're right, I was editing the previous pull request and had problems so I had to recreate a new one.

I was just specifying this in the old pull request

**Comment by metacreo** [comment]
duplicate of #34152

**Comment by Hlavtox** [comment]
Duplicate

**Pull request closed without merging**
