### PR TITLE
Add Malagasy language

### PR DESCRIPTION
**Pull request by OneDotIT**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Develop
| Description?  | Add the support for Malagasy language.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | #14074 #15435
| How to test?  | Through the localization option, create a new language with costume ISO code.

Hello, 
This pull request update the language files to include Malagasy.
Out of #14185, #14349, #14074, and this, I believe this should be documented. I will try to put some effort on that.
Regards,

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15063)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Hello @OneDotIT, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by OneDotIT** [comment]
> Hello @OneDotIT, thanks for your contribution, would you mind to rebase your pull request? Thanks

Hello,
Sorry, changing the base introduced some conflict. I will re-pull

**Comment by Progi1984** [comment]
Thank you @OneDotIT

**Comment by Progi1984** [comment]
@OneDotIT Hi, have you had some times for updating your PR ? Thanks :)

**Comment by OneDotIT** [comment]
Yes, Please pardon me.

I do understand being free and open doesn't mean commitment free, my reason for being late is that I'm bulked with papers.

I will push it soon

Regards,



---- On Mon, 09 Sep 2019 11:04:52 +0300 Progi1984 <mailto:notifications@github.com> wrote ----



https://github.com/OneDotIT Hi, have you had some times for updating your PR ? Thanks :)

**Comment by Progi1984** [comment]
Thank you @OneDotIT

**Comment by OneDotIT** [comment]
Hello @Progi1984,
This should be right : #15482.

I will close this pull request.

**Pull request closed without merging**
