### PR TITLE
Fix CS in more code directories

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Normalize CS fix in more code directories.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23918)

### CODE REVIEW

**Comment by mvorisek** [comment]
Please help with fixing `LegacyTests\Integration\classes\module\ModuleOverrideInstallUninstallTest::testDiffOverrideAndUninstall` test

**Comment by PierreRambaud** [comment]
> Please help with fixing `LegacyTests\Integration\classes\module\ModuleOverrideInstallUninstallTest::testDiffOverrideAndUninstall` test

This is the reason why we don't want to execute cs fixer on old files and static dependencies like filemanager, it's not up to us to change the code of these files.

**Comment by mvorisek** [comment]
@PierreRambaud here is GitHub analysis:

image

It can be used for commercial purposes. If the library code itself is not modified, what is the exact reason we can not use it?

**Comment by mvorisek** [comment]
95% of the files are PrestaShop files.

`admin-dev/filemanager` can be excluded from fixes. Is these something else to exclude?

**Comment by mvorisek** [comment]
I have excluded `filemanager`, all other fixes seems to fix PrestaShop code.

**Comment by mvorisek** [comment]
@matks can you review this one? Slightly related with https://github.com/PrestaShop/PrestaShop/issues/15545 , I will then update to PSR-12 everything.

Changes can be checked by reruning fixer on the original data.

**Comment by mvorisek** [comment]
can you submit a constructive feedback to move this forward?

**Comment by matks** [comment]
Hi everyone,

Like I just wrote in PR https://github.com/PrestaShop/PrestaShop/pull/22823#issuecomment-870394578, I'm afraid here we are in a situation where we don't want to merge this PR. It has not been moved since April and I think if nobody from maintainer team joins in the discussion it means nobody from maintainer team is willing to join.

There is a lot of things to do for the PrestaShop project and our time is limited. Maintainers have to pick carefully what topics they allow to go forward by reviewing and approving Pull Requests, so they choose what PRs and/or topics they invest their time in. If this PR has not moved for a long time I think it's because maintainers do not see a very valid reason to continue.

By opening this PR you suggested to go through one path, but it seems we don't want the project to go through this path in this direction, at least today. Maybe in the future.

Codestyle is a good thing but we don't want to apply it to these area of the code, at least not today. And applying it would modify a huge amount of code introducing big git history changes and git conflicts for other PRs.

It's a good idea but we do not wish for it to happen now.

Thank you for your contribution, I close this Pull Request because I don't think it will be merged.

If 2 other maintainers of the project disagree with me they are free to re-open the Pull Request and continue this journey. For me, it's better to halt it here.

**Comment by mvorisek** [comment]
@matks this PR moves code quality forward, explain, why this change is not wanted when the project is moving towards this

**Pull request closed without merging**
