### PR TITLE
ProductId should throw a ProductException instead of an OrderException

### LINKED ISSUE #14520: ProductId throw an OrderException instead of ProductException
**Describe the bug**
I need to use a [ProductId](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Product/ValueObject/ProductId.php) for a module (1.7.6.+) but it throw an OrderException instead of ProductException

**To Reproduce**
1. Go to https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Domain/Product/ValueObject/ProductId.php
2. Look on assertIntegerIsGreaterThanZero function
3. See Exception thrown is not a ProductException

**Additionnal information**
PrestaShop version: develop
PHP version: PHP 7.2

### PR DESCRIPTION
**Pull request by Matt75**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | ProductId should throw a ProductException instead of an OrderException
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14520
| How to test?  | Run Unit Tests

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14564)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
While I agree with the fix, this is a BC break :'(

We had to merge that before the 1.7.6.0, I don't think this is worth to update it before the 1.8.x...

wdyt @matks ?

**Comment by matks** [comment]
> While I agree with the fix, this is a BC break :'(

I disagree.
We do not modify a function signature nor its return, we only modify the Exception being thrown. If you're worried that some external code relies on that, we can mention it in the 1.7.7 release note as [it has been done for the 1.7.6 release note](http://build.prestashop.com/news/prestashop-1-7-6-0-available/) in a "breaking or risky changes" section.

Also, it's an obvious mistake. Patch versions are allowed to break _behavior_ (not signature) if it's a bugfix to me. If a security vulnerability allows someone to go through a bad check, fixing the check is not considered a breaking change although some external code could rely on it ?

**Comment by Matt75** [comment]
So what's the status on this issue ?

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Can you please rebase your branch?
@matks Can you please approve this change.

**Comment by Matt75** [comment]
Should be ok now

**Review by PierreRambaud — APPROVED** [review]

**Comment by Matt75** [comment]
Oh wait, looks like it was already replaced by ProductConstraintException so this PR is useless

**Comment by PierreRambaud** [comment]
Haha sorry @Matt75 ^^'
Really sorry for the delay, I'm closing your PR.

**Pull request closed without merging**
