### PR TITLE
Sending rating event on product refresh to avoid empty rating stars

### LINKED ISSUE #15184: Reviews are not displayed after changing the quantity
**Describe the bug**
If we change the quantity on the product page, the reviews are not displayed any more.

**To Reproduce**
1. Go to a product with some reviews approved
image

2. Change the quantity
3. See error

image

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.2
productcomments v4.0.0

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Stars were disappearing when review module was on right column hook of product and you change quantity/combinations
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15184 but https://github.com/PrestaShop/productcomments/pull/48 needs to be merged before
| How to test?  | Set productcomments to right column of product, go on product page with reviews and change quantity, stars should stay on the page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17020)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Please remove assets

**Review by Progi1984 — CHANGES_REQUESTED** [review]
It's for the `develop` branch : please remove assets.

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
The pull request correctly fix the issue. Thanks @NeOMakinG

**Comment by matks** [comment]
Thank you @NeOMakinG

**Pull request merged**
