### PR TITLE
Change URLs to prestashop-project.org

### PR DESCRIPTION
**Pull request by Hlavtox**
Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR removes some of the branding, changes links to prestashop-project.org. First commit is only `devdocs.prestashop-project.org` change on 7000 files, no need to check manually. The second one can be checked manually and contains all other changes, https prefix here and there etc.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Comment by NeOMakinG** [comment]
This PR is going to get a lot of conflicts really often :(

**Comment by nicosomb** [comment]
As I already said in an other PR, I can approve this PR but I really think that the license block should only be in LICENSE file and the codesource files should link to the LICENSE file. 
When we'll have some changes to do, we'll just have a single file to edit. 

@PrestaShop/prestashop-core-developers what is your opinion?

**Comment by matks** [comment]
@Hlavtox we will be obliged to somehow review each line of the PR. what if an attacker stole your github account and one of this line injects a backdoor inside prestashop? we need a way to validate there is nothing bad in this big PR

**Comment by nicosomb** [comment]
@Hlavtox your huge PR has conflicts. 

@PrestaShop/prestashop-core-developers I think that we need to take quickly a decision on this PR. This PR will always have conflicts.

**Comment by 0x346e3730** [comment]
@Hlavtox how did you implemented those changes ? Did you used grep, a bash script, a find & replace from an IDE ?

**Comment by Hlavtox** [comment]
@0x346e3730 

https://github.com/PrestaShop/PrestaShop/pull/30195/commits/1097b695199b6e1d4d7c3d32a98420be06324195
Here, I have replaced the whole sentence in VS code in all files.

https://github.com/PrestaShop/PrestaShop/pull/30195/commits/1eb8869c9387247ae8d69704803f233f4c754390
These are all manual changes.

**Comment by kpodemski** [comment]
Hi @Hlavtox 

I'm closing this PR. We need to change it and merge it quickly. We will do it with a CLI tool and proceed with a license a bit differently, as explained here: https://github.com/PrestaShop/PrestaShop/issues/30213

**Pull request closed without merging**
