### PR TITLE
Generate a PDF by date / Generate a PDF by order status

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | check a Generated PDF by date and by order status.
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | TEST_PATH=full/01_orders/8_generate_pdf_by_date  npm run specific-test -- --URL=UrlFrontOffice --DIR=DownloadDirectory

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9448)

### CODE REVIEW

**Review by fatmaBouchekoua — APPROVED** [review]

**Comment by marionf** [comment]
Hello @fouratachour 

I can't launch your test, maybe I forgot something ?

capture d ecran_546

The shop is already installed in English and all parameters are ok:
--URL=localhost/prestashop/ --ADMIN_EMAIL=marion.francois@prestashop.com --ADMIN_PASSWORD=prestashop --DIR=/home/mfrancois/Téléchargements

**Comment by fatmaBouchekoua** [comment]
Hello @marionf ,
There's a typo in the command, can you try this one please?
TEST_PATH=full/01_orders/08_generate_pdf_by_date npm run specific-test -- --URL=localhost/prestashop/ --ADMIN_EMAIL=marion.francois@prestashop.com --ADMIN_PASSWORD=prestashop --DIR=/home/mfrancois/Téléchargements/

**Comment by marionf** [comment]
Thank you @fatmaBouchekoua it's better like this :+1: 

@fouratachour it's ok for the scenario Generate a PDF by date but I don't see tests described in the scenario Generate a PDF by order status
Can you add this test ?

**Comment by fatmaBouchekoua** [comment]
@marionf the scenario Generate a PDF by order status will be in another PR

**Comment by fatmaBouchekoua** [comment]
@marionf you can run this command to test the second scenario:
TEST_PATH=full/01_orders/09_generate_pdf_by_status npm run specific-test -- --URL=localhost/prestashop/ --ADMIN_EMAIL=marion.francois@prestashop.com --ADMIN_PASSWORD=prestashop --DIR=/home/mfrancois/Téléchargements/

**Comment by marionf** [comment]
Thank you @fatmaBouchekoua 

@fouratachour Why are you changing the price display method to tax excluded ?

**Comment by ansar21mallouli** [comment]
Hello @marionf,

@fouratachour change  the price display method  from tax included to tax excluded, because when tax included is selected, in the order details, the field taxes is not displayed.
taxexludedmodifed
=> Tax excluded
taxincluded => Tax included
Thanks

**Pull request closed without merging**
