### PR TITLE
[*] FO : Added option to display lowest available price, based on product...

### PR DESCRIPTION
**Pull request by PhpMadman**
... quantity discounts

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by PhpMadman** [comment]
Still a good idea to implement, needs to be rewritten to PSR-2.
Will do when I get the time.

**Comment by xBorderie** [comment]
Quite a bit of work here too!

And, indeed, it needs to use PSR-2 and be on the `develop` branch. If you are up to the challenge, that would be great!

Thank you!

**Comment by PhpMadman** [comment]
Remade in #4430

**Comment by xBorderie** [comment]
Thank you @PhpMadman !

**Pull request closed without merging**
