### PR TITLE
Remove menu thumbnails

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes category menu thumbnails functionality. Complicates our lives and menu modules should handle this on their own.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | Check that other category images work fine.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

### Removed methods
- src/Adapter/Category/QueryHandler/GetCategoryForEditingHandler::getMenuThumbnailImages
- src/Core/Domain/Category/Command/AddCategoryCommand::getMenuThumbnailImages
- src/Core/Domain/Category/Command/AddCategoryCommand::setMenuThumbnailImages
- src/Core/Domain/Category/Command/AddRootCategoryCommand::getMenuThumbnailImages
- src/Core/Domain/Category/Command/AddRootCategoryCommand::setMenuThumbnailImages
- src/Core/Domain/Category/Command/EditCategoryCommand::getMenuThumbnailImages
- src/Core/Domain/Category/Command/EditCategoryCommand::setMenuThumbnailImages
- src/Core/Domain/Category/Command/EditRootCategoryCommand::getMenuThumbnailImages
- src/Core/Domain/Category/Command/EditRootCategoryCommand::setMenuThumbnailImages
- src/Core/Domain/Category/QueryResult/EditableCategory::getMenuThumbnailImages
- src/Core/Domain/Category/QueryResult/EditableCategory::canContainMoreMenuThumbnails
- src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController::deleteMenuThumbnailAction
- src/PrestaShopBundle/Form/Admin/Catalog/Category/AbstractCategoryType::configureOptions

### Removed services
- admin_categories_delete_menu_thumbnail
- prestashop.adapter.category.command_handler.delete_category_menu_thumbnail_image_handler
- prestashop.adapter.image.uploader.category_menu_thumbnail_image_uploader
- PrestaShop\PrestaShop\Core\Category\Provider\MenuThumbnailAvailableKeyProvider

### Removed files
- src/Adapter/Category/CommandHandler/DeleteCategoryMenuThumbnailImageHandler
- src/Adapter/Image/Uploader/CategoryMenuThumbnailUploader
- src/Core/Category/Provider/CategoryImageFinder
- src/Core/Category/Provider/MenuThumbnailAvailableKeyProvider
- src/Core/Domain/Category/Command/DeleteCategoryMenuThumbnailImageCommand
- src/Core/Domain/Category/CommandHandler/DeleteCategoryMenuThumbnailImageHandlerInterface
- src/Core/Domain/Category/Exception/MenuThumbnailsLimitException
- src/Core/Domain/Category/ValueObject/MenuThumbnailId

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
Finally, I agree with the change. The usefulness of this is minor, and it is possible to re-implement this feature from the module.

I would like other @PrestaShop/prestashop-maintainers to speak up, because we didn't deprecate the code in the previous version (we can still do it, tho).

**Review by kpodemski — DISMISSED** [review]
Finally, I agree with the change. The usefulness of this is minor, and it is possible to re-implement this feature from the module.

I would like other @PrestaShop/prestashop-maintainers to speak up, because we didn't deprecate the code in the previous version (we can still do it, tho).

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
@nesrineabdmouleh @Progi1984 

some extra checks appear and the code for auto tests fails, could you take a look? :)

**Comment by Progi1984** [comment]
@Hlavtox You can run `npm run check:typescript` in the `tests/UI` directory.

Errors are explained here : 
```
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(37,5): error TS2345: Argument of type '{ coverImage: string; thumbnailImage: string; metaImage: string; }' is not assignable to parameter of type 'CategoryCreator'.
  Object literal may only specify known properties, and 'metaImage' does not exist in type 'CategoryCreator'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(42,5): error TS2345: Argument of type '{ coverImage: string; thumbnailImage: string; metaImage: string; }' is not assignable to parameter of type 'CategoryCreator'.
  Object literal may only specify known properties, and 'metaImage' does not exist in type 'CategoryCreator'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(47,5): error TS2345: Argument of type '{ coverImage: string; thumbnailImage: string; metaImage: string; }' is not assignable to parameter of type 'CategoryCreator'.
  Object literal may only specify known properties, and 'metaImage' does not exist in type 'CategoryCreator'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(61,23): error TS2339: Property 'metaImage' does not exist on type 'CategoryData'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(64,23): error TS2339: Property 'metaImage' does not exist on type 'CategoryData'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(67,24): error TS2339: Property 'metaImage' does not exist on type 'CategoryData'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(81,23): error TS2339: Property 'metaImage' does not exist on type 'CategoryData'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(84,23): error TS2339: Property 'metaImage' does not exist on type 'CategoryData'.
Error: campaigns/functional/BO/08_design/06_imageSettings/14_checkCategoryImageFormat.ts(87,24): error TS2339: Property 'metaImage' does not exist on type 'CategoryData'.

```

**Comment by kpodemski** [comment]
@Progi1984 Daniel didn't create these tests. It'd be great to have your or @nesrineabdmouleh help with them.

**Comment by Progi1984** [comment]
@kpodemski I can help him, yes :) But it's like Unit or Integrations tests, we can help contributors but not make to theirs places

**Comment by Hlavtox** [comment]
@kpodemski @Progi1984 Ready for review

**Comment by Progi1984** [comment]
@Hlavtox Can you execute UI tests on this PR ?

**Comment by Hlavtox** [comment]
@Progi1984 🔬 https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/5609925035

**Review by matks — COMMENTED** [review]
@Hlavtox We need to write the list of removed files and methods 😄 this will be a great help for @thomasnares and @kpodemski to document 9.0.0 important changes.

Also some UI tests are failing :/

**Comment by Hlavtox** [comment]
@Progi1984 Can you check the UI tests run please? The failed ones seem unrelated. 👍

**Comment by boubkerbribri** [comment]
> @Progi1984 Can you check the UI tests run please? The failed ones seem unrelated. +1

yes, It's unrelated, almost the same errors are on the nightly (the one on emails must be fixed on our side)

**Comment by Hlavtox** [comment]
@matks @kpodemski Ready to review, I rebased it and created a list of deleted methods, files and services for @thomasnares.

**Review by M0rgan01 — APPROVED** [review]
I think it makes the category images a bit clearer

**Review by boherm — APPROVED** [review]
I think I agree with that too. 
Let's simplify this system that I think isn't really used by themes.

**Review by MhiriFaten — APPROVED** [review]
Hello @Hlavtox ,

LGTM, and automated tests are OK
https://github.com/MhiriFaten/testing_pr/actions/runs/6123589792

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-automation we need your approval

**Comment by Hlavtox** [comment]
@kpodemski All tests are green and it's QA, what approval do we need?

**Review by Progi1984 — APPROVED** [review]
UI Tests : 
* Updated Scenario : https://forge.prestashop.com/browse/TEST-6018 & https://forge.prestashop.com/browse/TEST-5513 (FYI @PrestaShop/qa-functional)
* Updated Acceptance Test : https://github.com/PrestaShop/PrestaShop/issues/32404 (FYI @PrestaShop/qa-automation)

**Comment by kpodemski** [comment]
cc @boubkerbribri @nesrineabdmouleh

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @Hlavtox @nesrineabdmouleh @Progi1984 !

**Comment by web-burn** [comment]
I believe this was a very harmful removal. I actively used menu thumbnails display in the default Main Menu of my themes. Who were these thumbnails bothering? Many of my clients relied on this functionality. Why remove functionality when it is possible simply display the menu thumbnails in ps_mainmenu.tpl? It only takes a small snippet of code to enable this feature: 
image

**Comment by nicosomb** [comment]
@web-burn as this pull request is merged and closed, please open a new issue if it's necessary. It will be easier to discuss about it.

**Pull request merged**
