### PR TITLE
Removed inline-style color in demo product description

### LINKED ISSUE #11211: Font color should be consistence and visible in description tab of "Hummingbird_printed_t-shirt" in demo data.
**Describe the bug**

**To Reproduce**
1. Go to '[Hummingbird_printed_t-shirt](http://fo.demo.prestashop.com/en/men/1-1-hummingbird-printed-t-shirt.html#/1-size-s/8-color-white)'
2. See the description tab.

**Screenshots**
hummingbird

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: 7.1

### PR DESCRIPTION
**Pull request by dineshbadrukhiya**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Removed inline-style of color in demo product desciption of "Hummingbird_printed_t-shirt" for design improvement.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11211 
| How to test?  | Go to: http://demo.prestashop.com/en/?view=front ,Where on product page of "Hummingbird_printed_t-shirt" font color should be consistence in description tab.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11133)

### CODE REVIEW

**Comment by dineshbadrukhiya** [comment]
@Quetzacoalt91 wdyt?

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Yep, it needs to be updated. I also found out that all languages have this issue. cc @LouiseBonnard

**Comment by dineshbadrukhiya** [comment]
Hello @Quetzacoalt91 
I think it should be updated for 1.7.5.0 also.

**Comment by MathiasReker** [comment]
How about remove all the inline style? For some time ago I removed the font from the inline style (https://github.com/PrestaShop/PrestaShop/pull/10867/files) I think that it is better to remove all the inline style at once.

**Comment by dineshbadrukhiya** [comment]
Hello @Quetzacoalt91 

Does I need to remove this inline-style for all other languages?

**Comment by MathiasReker** [comment]
@dbadrukhiya you can see what I mean here: https://github.com/PrestaShop/PrestaShop/pull/11212

**Comment by Quetzacoalt91** [comment]
Well, if you don't mind @dbadrukhiya I'd appreciate. :)
Let's stick to the `develop` branch for this PR.

**Comment by dineshbadrukhiya** [comment]
Np @Quetzacoalt91 , I will remove it for othe languages also.

**Comment by Quetzacoalt91** [comment]
I missed it the first time, but it seems @MathiasReker already made a PR about this.

**Comment by dineshbadrukhiya** [comment]
That’s great! @Quetzacoalt91 . Is it good decision to remove all inline styles? Wdyt?

**Comment by Quetzacoalt91** [comment]
Well, as I said in https://github.com/PrestaShop/PrestaShop/pull/11212#issuecomment-434711780, I'm unsure about removing everything, as these field will end anyway with inline style as soon as they are updated. I'd like to start first with the color.

**Comment by dineshbadrukhiya** [comment]
I’m also unsure with removing all. Can I start with color @Quetzacoalt91 ?

**Comment by Quetzacoalt91** [comment]
I let you decide. Just avoid doing the same work 2 times with @MathiasReker . :wink:

**Comment by dineshbadrukhiya** [comment]
Hello @Quetzacoalt91 
I have opened new PR #11215 to start first with inline-style of color.

**Pull request merged**
