### PR TITLE
Fix getting products count on category list

### LINKED ISSUE #24964: BO - Categories - A new category created is not displayed in the list
#### Describe the bug

In the BO > Catalog > Categories page, when we create a new category, it is not displayed in the list

#### Steps to Reproduce

1. Go to BO > Catalog > Categories page
2. Create a new category
3. Set required fields and save
4. See the error, the number of categories is NOK, and the new category created is not displayed in the list

This regression is detected by [nightly](https://nightly.prestashop.com/report/1692)

**Screenshots**
In the list of categories, we have only demo categories
image
But we have all these categories
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | `category_product` might be empty, we need to use `leftJoin`
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24964.
| How to test?      | Try to add a new category, it should be displayed properly on the list
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24982)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thanks for the PR.
But I still have the issue :
Screenshot 2021-06-16 at 16 34 08
Screenshot 2021-06-16 at 17 02 15


Could you check and feedback please ?
Thanks !

**Comment by kpodemski** [comment]
Thank you @florine2623 

You're right, I didn't notice this error before :/

**Review by PululuK — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thanks for the update, but there's still a little issue.

_In PS 1.7.7.x :_
Screenshot 2021-06-17 at 13 52 09
_In develop :_
Screenshot 2021-06-17 at 14 03 06


Could you check again please ?
Thanks !

**Comment by kpodemski** [comment]
Hello @florine2623 

Sorry again, you're right, fixed

**Review by PululuK — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by boubkerbribri** [comment]
Hi @kpodemski ,
We still have the issue, 
When you add 2 categories (or more), only one is displayed, the others are hidden. Then when you delete the last one, the next one displayed.


image


I don't know but it seems that it's limited to 3 (demo categories) + 1 (created category). If you filter to have only the created categories, you will have only one displayed.

image

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
Tested and approved with UI tests.
Thanks @kpodemski

**Comment by PululuK** [comment]
Thanks @kpodemski & @boubkerbribri

**Pull request merged**
