### PR TITLE
Fix notices thrown during SQL upgrade from 1.7.3.x

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes a syntax error on CREATE TABLE and undefined variable notice
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5289
| How to test?  | Make a SQL upgrade from 1.7.3.x to 1.7.4.0

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8978)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
@LittleBigDev, this one's for you.
I'd like you to confirm only one lang will be registered for each currency during the upgrade.

**Comment by LittleBigDev** [comment]
Yes I confirm, I forgot the case where multiple langs are already installed. I was working for "install" context only... This needs to be enhanced.

**Comment by LittleBigDev** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8978)*

**Comment by Quetzacoalt91** [comment]
Changes have been removed from `develop`, closing.

**Pull request closed without merging**
