### PR TITLE
Add CMS page listing position update functionality

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | adds usage of new PositionColumn functionality in the list. Also fixes filtering problem.
| Type?         |  improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | npm run dev or npm run build and start dragging the position column in the second list located in **admin-dev/index.php/improve/design/cms-pages/**

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13125)

### CODE REVIEW

**Comment by tomas862** [comment]
status: blocked by https://github.com/PrestaShop/PrestaShop/pull/12974

**Comment by tomas862** [comment]
todo: test inner list position filtering after #12974 is merged

**Comment by tomas862** [comment]
ready for review :)

**Comment by matks** [comment]
Does this fix https://github.com/PrestaShop/PrestaShop/pull/10877#issuecomment-440275907 ?

**Comment by tomas862** [comment]
Yes :)

**Review by matks — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @tomas862

**Pull request merged**
