### PR TITLE
Redesign SEO preview

### LINKED ISSUE #27310: Update SEO preview in the style currently used by search engines
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

The current SEO preview is kinda old and is only used by **Bing**:

### Describe the solution you'd like

Update to a new style used by **Google**, **Yahoo** and **DuckDuckGo**:

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Redesign SEO preview in the style currently used by search engines.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27310
| How to test?      | Go to BO > Catalog > Product > Edit a product <br/> Go to BO > Catalog > Categories > Edit a category <br/> Go to BO > Design > Pages > Edit a page
| Possible impacts? | SEO preview UI in Product, Category and CMS page

**LTR:**

**RTL:**

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27346)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Looks fine to me except one thinkg @mparvazi, could we use some variables inside SCSS? You can temporary use the import of the `_variable` partial, add some vars related to `serp` component if needed

This component definitely deserve to be switched to the UIKit but well it's not the scope of the PR

**Comment by mparvazi** [comment]
@NeOMakinG 

It's possible to define variables inside vue files, but if we define scope variables for all vue components inside _settings.scss, it would be easier to change their values.

admin-dev/themes/new-theme/scss/config/_settings.scss

```
// Config
$enable-shadows: true;

// Colors
.
.
.
$widget-border-color: #e7e7e7;


// Serp
$serp-url-light-color: #5f6368;
$serp-url-dark-color: #202124;
$serp-title-color: #1a0dab;
$serp-description-color: #4d5156;
```


I think it's better also define bootstarp config variables for controlling mixin functions (e.g. $enable-shadows).
It can be used for dark theming.

For box-shadow we can use:
```
@include box-shadow(0 0 0.375rem 0 rgba($black, 0.1));
```
If theme is dark:
```
$enable-shadows: false;
```
Then bootstrap mixin (box-shadow() function) doesn't add box-shadow attribute.

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> It's possible to define variables inside vue files, but if we define scope variables for all vue components inside _settings.scss, it would be easier to change their values.
> 
> admin-dev/themes/new-theme/scss/config/_settings.scss
> 
> ```
> // Config
> $enable-shadows: true;
> 
> // Colors
> .
> .
> .
> $widget-border-color: #e7e7e7;
> 
> 
> // Serp
> $serp-url-light-color: #5f6368;
> $serp-url-dark-color: #202124;
> $serp-title-color: #1a0dab;
> $serp-description-color: #4d5156;
> ```
> 
> I think it's better also define bootstarp config variables for controlling mixin functions (e.g. $enable-shadows). It can be used for dark theming.
> 
> For box-shadow we can use:
> 
> ```
> @include box-shadow(0 0 0.375rem 0 rgba($black, 0.1));
> ```
> 
> If theme is dark:
> 
> ```
> $enable-shadows: false;
> ```
> 
> Then bootstrap mixin (box-shadow() function) doesn't add box-shadow attribute.

This is what I said yes, we can use the _settings variables from the SCSS folder of the core

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @mparvazi ,

Thanks for the PR!

I have some feedbacks.

**Go to BO > Catalog > Product > Edit a product** 
The URL is not updated :
Screenshot 2022-01-19 at 15 28 47
It should be :
Screenshot 2022-01-19 at 15 30 44

**Go to BO > Catalog > Categories > Edit a category**
The initial description is not on the SEO preview, only the meta-description is taken into account
Screenshot 2022-01-19 at 15 31 55
I should have :
Screenshot 2022-01-19 at 15 32 03

The SEO Preview is shifted to the left when 62 characters are used :
Screenshot 2022-01-19 at 15 37 06

**Go to BO > Design > Pages > Edit a page**
When the meta-description is too long, the block is shifted to the left :

Screenshot 2022-01-19 at 15 40 38

Could you check ?
Thanks!

**Comment by mparvazi** [comment]
Hello @florine2623 

These problems aren't related to this PR, you can check without PR.
This PR only focus on UI and I didn't want to change current functionality.
But I'll check again to fix them.

**Comment by mparvazi** [comment]
@jolelievre  @NeOMakinG 

Due to proplems found by @florine2623 .

Should I work in current script to fix them? because this PR approved for changing UI.

Most of those problems  must be fixed here:
`admin-dev/themes/new-theme/js/app/utils/serp/index.js`

**Comment by florine2623** [comment]
@mparvazi ,

Indeed, I reproduced the bugs mentioned in develop without PR ^^
Let's wait for @jolelievre and @NeOMakinG to see if this needs to be fixed in another PR

**Review by jolelievre — APPROVED** [review]
Hi @mparvazi and @florine2623 

I agree that most of these bugs are not related with the scope of this PR. Besides I already saw some of them which, I believe, are fixed in the new experimental product page which will replace the current one in v8.0. So I would suggest that we merge the new design as is, but it's important not to forget about these potential bugs.

So ideally @florine2623 could you check on new product page if they are all still present? For example, I believe that the automatic syncing of title, description and URL is supposed to have been fixed. For the block which is shifted I don't know, since it's a new page and new integration maybe the bug won't be present either.

If some bugs remain we can open an issue to fix them, but only in product page v2. We have no interest of keeping maintaining the old page since it's gonna be removed.

**Comment by florine2623** [comment]
Hello @jolelievre ,

Thanks for the update !

In product page V2, there are no bugs found ! ✅ 

The only bugs are about :
**Go to BO > Catalog > Categories > Edit a category
Go to BO > Design > Pages > Edit a page**

I created this issue for the those mentioned above : https://github.com/PrestaShop/PrestaShop/issues/27414

For me, it is QA ✅ 
Thanks @mparvazi !

**Comment by Progi1984** [comment]
Thanks @mparvazi & @florine2623

**Pull request merged**
