### PR TITLE
Correction with assignment of order reference

### LINKED ISSUE #21584: Correction with assignment of order reference
#### Describe the bug

Faced the problem that at some point the code between the creation of the order reference and the creation of the order itself took a long time, which is why two customers received two identical order references

#### Steps to Reproduce

1. Create delay 20 seconds between the creation of the order reference and the creation of the order in PaymentModule class
2. Create first order, while there is a delay, create a second order at this time

**Screenshots**
https://prnt.sc/v57wll

#### Additional information

* PrestaShop version: 1.7.4.4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by fest73**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Faced the problem that at some point the code between the creation of the order reference and the creation of the order itself took a long time, which is why two customers received two identical order references. So I generate order reference _just before I create the order_
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21584
| How to test?  | 1. Create delay 20 seconds between the creation of the order reference and the creation of the order in PaymentModule class<br>2. Create first order, while there is a delay, create a second order at this time

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21585)

### CODE REVIEW

**Comment by matks** [comment]
Hi ! So if I get it correctly, you generate order reference just before you create the order to avoid the bug you mention.

Even if this improves the situation indeed, the "2 identical order references" could happen if you have 2 users that are placing an order simultaneously 🤔 .

I think the issue is not in the delay. The delay is indeed something improvable but the real issue is that the references generation is supposed to be random and consequently unique. I know nothing is unique in software world but unless you have thousand of customers placing orders every minute 😄 you should not get 2 identical order references.

IMO `Order::generateReference();` is not "random enough", that is the key issue to solve.

**Comment by matks** [comment]
@dariusakafest Actually I read it again, and you are saying that if we follow the scenario

```
1. Create delay 20 seconds between the creation of the order reference and the creation of the order in PaymentModule class
2. Create first order, while there is a delay, create a second order at this time
```

We get identical order references ... every time 🤯 ?

**Comment by fest73** [comment]
@matks The fact is that not all stores use random codes, but on the contrary, for convenience, this type of order:
B0001/20, B0002/20, B0003/20
Thus, the identifiers could match

**Comment by fest73** [comment]
@matks  A popular solution has often been similar to this:
    
public static function generateReference()
    {
        $last_order_id = self::getLastOrderId();
        return self::formatOrderId($last_order_id);
    }

    public static function formatOrderId($id_order) {
        //return 'B'.sprintf('%06d', $id_order).'/'.date('y');
        return 'B'.$id_order.'/'.date('y');
    }

    public static function getLastOrderId()
    {
        $id_order = (int)Db::getInstance()->getValue(
            'SELECT MAX(id_order)
            FROM '._DB_PREFIX_.'orders'
        );
        return ($id_order + 1);
    }

**Comment by matks** [comment]
@dariusakafest so you mean that [current Core implementation](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/order/Order.php#L1787) is fine but this popular replacement is not ?

And people, to use this replacement, use an Override ?

**Comment by fest73** [comment]
@matks yes. Current implementation is good in terms of stability but not usability

**Comment by fest73** [comment]
@matks Can you help me to solve problem with validation?
image

**Comment by matks** [comment]
@dariusakafest OK I get it.

I understand random strings are not user-friendly. Hard to copy-paste, hard to remember, hard to use it if you are talking about the order on the phone. But as you said, references as random strings are good for stability.

Moreover, if your references become predictable, this can be used as an attack vector by a hacker against your shop. For example using `B0001/20, B0002/20, B0003/20` I can guess some future order references and use them against your payment provider for fraud.

May I suggest another way ?

I suggest using 2 different references:
- keep current order reference for what it is meant for: identifying a unique transaction between PS and other systems (ERP, payment provider ...) where it is important it is random and cannot be guessed
- create a new reference, that I would call a `order friendly reference` using the pattern you mentioned, that you can show inside the BO and FO and use it to communicate with user. 

> Current implementation is good in terms of stability but not usability

We dont want to choose between the 2 😄 so let's not choose. It is impossible to have a single ref provide both benefits, so better use 2 references.

It's not unusual, I have seen it done before. 2 references, "one for the humans, one for the machine".

You could even create a module that does it and sell it 😉 

And a very simplistic implementation (but it's not secure) would be simply to use SQL ID appended to a string.

**Comment by matks** [comment]
Hi @dariusakafest will you be able to continue? else we can close (and reopen later)

**Comment by matks** [comment]
Well it looks like this PR is not moving anymore. As mentioned in our [Maintainer Guide](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests), "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

I close this pull request as it seems stale. If however someone wants to get involved to continue it, you can re-open a new PR 😉 .

Thank you!

**Pull request closed without merging**
