### PR TITLE
Remove useless space

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove useless space in `elseif`
| Type?         | improvement
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | no
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11607)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by MathiasReker** [comment]
After reading this: https://github.com/PrestaShop/PrestaShop/pull/11605 I scanned every .*tpl file for this issue.

**Comment by Quetzacoalt91** [comment]
No need of QA on this one.

**Comment by MathiasReker** [comment]
Same issue for this path, but it should be fixed in the module:

```
modules\ps_themecusto\views\templates\admin\controllers\configuration\elem\module_actions.tpl
Line 64.
```

**Comment by MathiasReker** [comment]
Nice catch @SebBareyre (https://github.com/PrestaShop/PrestaShop/pull/11605)

**Comment by Quetzacoalt91** [comment]
Thank you @MathiasReker

**Pull request merged**
