### PR TITLE
Enable grid search button by default

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | `FiltersSubmitButtonEnablerExtension` should provide functionality to enable/disable the button depending on inputs, but the button by default should be enabled. Currently the button by default was disabled and without extension the list was not searchable at all. This PR enables the button by default on page load, and then the above mentioned extension decides if button needs to be shown or hidden, this way extension is optional and not forced to use.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Go to any list in migrated pages, for example brands (Sell > Catalog > Brands & Suppliers). You should see search button turns from enabled (blue) to disabled (grey), and is unusable until any of inputs are filled. Once any input is filled, the search button is enabled and the reset button appears bellow.

 :warning: This change brings another issue - on page load search button noticeably flickers from enabled to disabled as it takes up to one second for page to load. This behavior might look strange from UX perspective.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13571)

### CODE REVIEW

**Comment by zuk3975** [comment]
@matks ready.
Just before merging consider this ( maybe need to ping UX team ) : - on page load search button noticeably flickers from enabled to disabled as it takes up to one second for page to load. This behavior might look strange from UX perspective.

**Comment by matks** [comment]
@zuk3975 It was you call, I summon @TristanLDD 😄

**Review by matks — APPROVED** [review]

**Comment by TristanLDD** [comment]
Hi @zuk3975, 

Indeed, the flickering of the search button from enabled to disabled on page load is not the best behavior, but in the same time doesn't really alter user experience as long as the button enables when one of the inputs is filled. 

Considering that this case is preferable to the case when list is not searchable at all, I'll say let's merge.

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
