### PR TITLE
Update required inputs on carrier page

### LINKED ISSUE #37004: It's possible to create new carrier without ranges and prices
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

It's possible to create new carrier without ranges and prices. This should not be possible because this field is mandatory.

image

### Expected behavior

This should not be possible because this field is mandatory.

### Steps to reproduce

1. Go to BO > Shipping > Carriers > Add new carrier
2. Fill the page General settings
3. Add  a zone and tax
4. Save
5. Carrier is created without ranges and prices

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Poulinhoo**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove required inputs on carrier form
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| UI Tests | https://github.com/florine2623/testing_pr/actions/runs/11176257922/job/31083144573 ✅ 
| Deprecations?     | no
| How to test?      | Follow the issue [#37004](https://github.com/PrestaShop/PrestaShop/issues/37004)
| Fixed issue or discussion?     | Fixes #37004

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by jolelievre — COMMENTED** [review]
@PoulainMaxime all good for the modifications, however can you please rebase your PR the CI has changed this week so you need a rebase to have it validated completely

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Shipping.Feature`
    - [ ] `Tax`
    - [ ] `Handling costs`
    - [ ] `[1]Manage handling costs[/1]`
    - [ ] `Set ranges and prices`
- `Admin.Shipping.Help`
    - [ ] `Does the carrier have additional fees`

(Note: this is an automated message, but answering it will reach a real human)

**Review by jolelievre — APPROVED** [review]
Thanks @PoulainMaxime

**Review by tleon — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @PoulainMaxime ,

LGTM ^^

Field is not longer required ✅ I can save my carrier without adding a range in the field.

Although the automated test are broken. @PrestaShop/qa-automation WDYT ?

I have relaunched them multiple times here : :x:
https://github.com/florine2623/testing_pr/actions/runs/11144625694

**Review by florine2623 — APPROVED** [review]
Tests are green ✅ 
It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
thank you @PoulainMaxime @florine2623

**Pull request merged**
