### PR TITLE
[*] FO : Added option to display lowest available price, based on …

### PR DESCRIPTION
**Pull request by PhpMadman**
…product quantity discounts

### CODE REVIEW

**Comment by PhpMadman** [comment]
New PR for #1280
Think everything is PSR-2.
It was made half automated. I copied the code, removed the +, and my editor made the PSR-2 spaces.

It's untested on 1.7, since I'm still uploading the latest 1.7 to my server.

**Comment by xBorderie** [comment]
Thank you for rebasing your PR to the `develop` branch and to PSR-2!
A PS developer will review this new PR.
Cheers!

**Comment by maximebiloe** [comment]
Hello,

Thanks for your contribution.

I think it could be a nice thing to have, but while we was rewriting the front office, we have dropped the `default-bootstrap` and reworked the front controllers.
Could you please, modify your PR, to improve the `ProductPresenter` to make available the reduced price in it ?

Thanks in advance,
Regards

**Comment by xBorderie** [comment]
Hi @PhpMadman !
Between your PR not being mergeable anymore because of conflicts, and the fact that you target a theme that is not available anymore in `develop`, I am closing this PR for now.
Don't hesitate to re-open it if you can update your code to follow @maximebiloe advices.

Note: don't re-open it on the `1.6.1.x` branch (where the default-bootstrap them is still used), because that branch does not accept enhancements anymore, only bugfixes. Thank you!

**Comment by PhpMadman** [comment]
I completely forgot about this PR.
I'll  look in to it, and make a new PR.

**Comment by xBorderie** [comment]
If you're thinking about adding a "display lowest available price" to the new 1.7 theme, then that could be nice! What do you think, @vincentbz ?

**Pull request closed without merging**
