### PR TITLE
Fixed display of attributes in cart on Frontoffice

### LINKED ISSUE #25942: FO - Shopping cart page - An exception is displayed when a product added to cart transformed from simple product to a product with combinations
#### Describe the bug

In the FO > We add a simple product to the cart
In the BO > We transform this product from a simple product to a product with combinations
When we add this product again to the cart => an exception is displayed, only when debug mode enabled

#### Steps to Reproduce

1. Enable debug mode
1. Go to BO > Catalog > Products page > create standard simple product with quantity
2. Go to FO > add it to cart
3. Go to BO > Catalog > Products page  > Edit the last product and generate a combination with a quantity
4. Go to FO add this product to the cart again
5. Go to the shopping cart page => exception image

If debug mode disabled
image

PS: in PS1778 => ok
https://drive.google.com/file/d/1EuqalL7nkSU4iolYSlx4H0yrxruNFSmi/view?usp=sharing

#### Additional information

* PrestaShop version: 1780rc1build5
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed display of attributes in cart on Frontoffice
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25942
| How to test?      | Cf. #25942

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25961)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by matks — COMMENTED** [review]
What a weird scenario 😅  transform a product already in cart from a simple product to a product with combinations.

I understand in this PR you're trying to exclude this case to avoid the exception.

So basically your code is "if it is an array, skip it, else display it".

Shall we go a bit further ? Rather than saying 'it is either an array (invalid) or the data is valid' we could say

"If my data is correct, I display it, else I skip it". So we would assert that $attribute and $array have expected types instead of just looking for arrays.

But such checks... shouldn't they happen in the controller ? Our view should contain no data logic, just rendering logic. [It should be just a view](https://flylib.com/books/en/1.315.1.55/1/).

**Comment by kpodemski** [comment]
This fixes a bug, but I think we need to know where is this bug coming from, right? Attributes should not return any array in this place. It was never a case.

We have yet another change in the core theme that the developer needs to implement while updating the PrestaShop by fixing this in such a manner. We should do our best to prevent such changes.

**Comment by matthieu-rolland** [comment]
@Progi1984 do you know why sometimes the attribute's value is an array ?

**Review by matks — APPROVED** [review]
So the changes have switched completely to a new technical behavior 👍

**Review by sowbiba — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @Progi1984 ,

Thanks for the PR, works like a charm !

**Pull request merged**
