### PR TITLE
Product: allow up to 14 chars in EAN field

### PR DESCRIPTION
**Pull request by rmilecki**
```
EAN-14 (GTIN-14) is in use for few years now so adjust PrestaShop's EAN
field to allow storing it.
```

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | EAN-14 is a superset of EAN-13, PrestaShop should allow up to 14 characters to allow storing this format as well
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [Provide means to store 14-digit GTIN identifiers](http://forge.prestashop.com/browse/PSCFV-9309)<br>[EAN Code lengte](https://www.prestashop.com/forums/topic/620923-ean-code-lengte/)<br>[Change Size Ean-13 And Upc With Special Caractères](https://www.prestashop.com/forums/topic/229684-change-size-ean-13-and-upc-with-special-caract%C3%A8res/?tab=comments#comment-2587529)<br>[Disable the EAN control function](https://www.prestashop.com/forums/topic/981203-disable-the-ean-control-function/?tab=comments#comment-3114148)
| How to test?  | Edit product in BO and set 14 characters long EAN

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17362)

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
You must add a new ean14 field.

**Comment by matthieu-rolland** [comment]
We should probably also confirm with the product team that the feature is actually wanted: @colinegin , @marionf  ?

Here are some informations about ean14 (it's just another barcode format):

https://www.normapremier.com/code-barre/

**Comment by colinegin** [comment]
@marionf @MatShir do you think this PR should be handled before the migration of the product page ?

**Comment by marionf** [comment]
Yes, we can do it before the migration but the changes request should be integrated 
@rmilecki could you apply the changes requested by @PierreRambaud ?
We should also edit the translation and change it while editing a combination, not only in the options tab

capture d'écran_2295

**Comment by PierreRambaud** [comment]
Hi @rmilecki ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
