### PR TITLE
Change module translation domains, make sure it's discoverable by the…

### LINKED ISSUE #34568: Wording conflict after changing modules from Upgrade to Update
### Describe the bug and add attachments

After wording of module actions was changed from Upgrade to Update on develop, it created conflict at least in Czech language.

Snímek obrazovky 2023-11-14 220317

Now when you open Module Manager, you see word `Upravit`, which means to modify something (a text, a piece of wood, a car), not to update a module. For update, it should be `Aktualizovat`.

### Expected behavior

We must start using proper wording domains to avoid conflicts like this. The same story goes with neverending New for new products and new product condition.

If we are not using technical names for source strings, we should at least use specific domains.

### Steps to reproduce

Don't waste time by installing czech prestashop on develop, just check the screenshot. :-)

### PrestaShop version(s) where the bug happened

develop

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes unused code, simplifies retrieving of the labels and removes some twig magic, removes some extra properties, changes the domain of the actions to fix a conflict.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Tests green. There is no visual change in the module manager.
| UI Tests          | https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6905211594
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34568
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by tleon — DISMISSED** [review]

**Comment by M0rgan01** [comment]
@Hlavtox thanks for the PR :) Some conflict remains

**Review by matthieu-rolland — COMMENTED** [review]
LGTM once condlict is solved 👍

**Comment by Hlavtox** [comment]
@tleon @M0rgan01 @matthieu-rolland ready ;-)

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

When I install my shop in Czech, the buttons in modules are in English.

I have updated my Czech language, but the issue remains :
Screenshot 2023-11-20 at 10 50 02

Could you check ?

**Comment by Hlavtox** [comment]
@florine2623 Yes, because translations have changed domain, that's normal. It will be czech before releasing 9.0, after we translate it in Crowdin. :-)

**Comment by florine2623** [comment]
Thanks @Hlavtox ^^

**Pull request merged**
