### PR TITLE
Use softDelete method

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Tiny improvement to avoid repetition.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

Test: https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6156323655

### CODE REVIEW

**Review by matks — APPROVED** [review]
Nice refactoring

For other reviewers see https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ObjectModel.php#L964

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
@Hlavtox Could you please run UI Tests? As this refactoring changes theoretically nothing, I guess UI Tests will tell us if a mistake did introduce a regression

**Comment by Hlavtox** [comment]
@matks Done

**Comment by kpodemski** [comment]
thanks @Hlavtox

**Comment by kpodemski** [comment]
the next step could be to use `setFieldsToUpdate` inside `softDelete` method @Hlavtox :)

**Pull request merged**
