### PR TITLE
[-] FO: #PSCSX-5582 fix wrong displayed specific price on product detail

### PR DESCRIPTION
**Pull request by kelu95**

### CODE REVIEW

**Comment by vTerenti** [comment]
QA OK

**Comment by dSkrbic** [comment]
Hello, 
tested this morning, and all lines displayed correctely
* Tested on 1614
* See third screenshot
* Remark: "-8% discount" which should appear near the price is missing (but it's another bug)

{color:red}*EDIT*{color}
Tested with combinations, and, indeed, only the first specific price appears!

Note for developpers:
to reproduce the bug, you need a product with three combination where:
* default doens't have any specific price
* second and third combination have two specific prices.
In this case: is proposed only the first created specific price whichever combination selected!

(passez me voir, j'ai un shop avec le bug...
z5-screenshot_dsk_2016 03 14_15h46m42s_006_
z4-screenshot_dsk_2016 03 14_15h45m43s_004_
z3-screenshot_dsk_2016 03 14_15h18m41s_002_

**Comment by vincentbz** [comment]
Hi,

For me it's not good too, but not for the same point. 
4 rules : 
Color : blue  / Qty : 1 => -20€
Color : blue / Qty : 2 => -1€
Color : orange / Qty : 1 => -10€
Color : orange / Qty : 2 => -2€

each rule works individually. But : 
Going from blue <--> orange with qty = 1 is OK
Going from blue <--> orange with qty = 2 is KO ==> Because filter is not refresh, if I go to qty = 3 yeah it's working, it remembers there is a rule for >=2. 
I think when we change combination, it doesn't take account there is a quantity to take.

**Comment by vincentbz** [comment]
@nicoxygen could you try the last commit by Nihco2 please ? i've just tested and I don't have any JS problem anymore when I have specific prices w/ product numbers

**Comment by nicoxygen** [comment]
commit of Nihco2 don't work on theme, i have tested on theme defaut and is the same problem,
it's for one declination not for all declination option

specific price

specific-price2

specific-price3

**Comment by vincentbz** [comment]
Hi,
Your theme for : https://www.leparadisdujardin.fr/ is not the default one
And the images you just added belongs to this theme, which has its own JS developments.

**Comment by bellini13** [comment]
Are we really going to release this "fix" that changes 1900 files, mostly due to copyright date changes?

**Comment by Shudrum** [comment]
Hi @bellini13!

This is why we added the tag `Need refacto`, this pull request contain come unwanted commits.

**Comment by bellini13** [comment]
It might be good to add some comments so that @kelu95 knows what he is being asked to refactor.  It would not be clear to me that the 1900 files that change the copyright need to be removed

**Comment by Shudrum** [comment]
The problem is that @kelu95 no longer works for us, and do not have the time to do it 😔

**Comment by bellini13** [comment]
So does that mean the 1.6.1.6 milestone should be removed, so this does not accidentally get released?  It currently shows as included, and it would be a real shame if this gets released

**Comment by Shudrum** [comment]
This is why we add the milestone and we do not merge.

We have and we will rework this pull request. The 1.6.1.6 means we really hope for this version.

**Comment by Shudrum** [comment]
Manually merged!

https://github.com/PrestaShop/PrestaShop/commit/cb7348f9b596124561513dfd209f8fa954804ccb
https://github.com/PrestaShop/PrestaShop/commit/42d884731abb538f37455e1e0d6447c2433fe57e

**Pull request closed without merging**
