### PR TITLE
Fix for product images in multishop BO

### PR DESCRIPTION
**Pull request by PrestaworksJonas**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix for product images in backoffice for multishop and give option for getting images by shop id
| Type?         | bug fix 
| Category?     | BO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes issue [#12061](https://github.com/PrestaShop/PrestaShop/issues/12061)
| How to test?  |  **1.** Go to a product in BO  **2**.  Select one of your multishops in the context. **3.** Upload a new image **4.** This image will only be shown on the selected shop that it was uploaded on (this is the expected behavior, before this PR it does not work, see ticket)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15909)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@PrestaworksJonas Could you please rebase your PR on `develop` ? This should fix Travis failing build

**Comment by Robin-Fischer-PS** [comment]
Thanks for the PR @PrestaworksJonas :smile:

**Comment by Progi1984** [comment]
@matks 
> @PrestaworksJonas Could you please rebase your PR on `develop` ? This should fix Travis failing build

Done ;)

**Comment by Progi1984** [comment]
Reopened for relaunching PrettyCI

**Comment by matks** [comment]
Looks like PrettyCI has been lost in the abyss

**Comment by matks** [comment]
PrettyCI is gone for good now

**Comment by matks** [comment]
PR rebased on develop in an attempt to reset PrettyCI

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
It worked 😄 thanks @PrestaworksJonas

**Pull request merged**
