### PR TITLE
Order modules on translation page alphabetically

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Modules on translation page (translation on the top and export section on the bottom), are ordered randomly, in the export section, with no search. This orders them alphabetically.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/10628550883 ✅ 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### Before
before

### After
after

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by kpodemski — DISMISSED** [review]

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by matks** [comment]
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

**Review by matks — APPROVED** [review]
Nice idea 👍

**Review by kpodemski — APPROVED** [review]

**Comment by ShaiMagal** [comment]
Finally, good @Hlavtox  :)

**Review by ShaiMagal — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

LGTM ✅ 

Before:
Screenshot 2024-08-30 at 09 26 32

After:
Screenshot 2024-08-30 at 09 52 07


Thanks :)

**Pull request merged**
