### PR TITLE
[+] FO : Add New hook display after opened body tag (usefull for GTM)

### PR DESCRIPTION
**Pull request by prestarocket**
Add new hook displayAfterBody after body tag: usefull for add tag like google tag manager

### CODE REVIEW

**Comment by prestarocket** [comment]
fix pull request subject

**Comment by xBorderie** [comment]
Hello @prestarocket! Thank you for this PR!

Could you [update your commit's name](https://help.github.com/articles/changing-a-commit-message/) so that it follows [the guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)?

Thank you!

**Comment by prestarocket** [comment]
Hello @xBorderie , it s done thx

**Comment by xBorderie** [comment]
Well yes, you did change the PR's title, but the important part is the commit's name, since that is the one that will be used by our changelog tool :)
This page should give you all the information you need: https://help.github.com/articles/changing-a-commit-message/
Thank you!

**Comment by prestarocket** [comment]
what do you think now ? ([+] Add New hook display after opened body tag (usefull for GTM))

**Comment by kpodemski** [comment]
No, you need to do like this:
[+] FO : New hook after opened body tag

you need to mark Front-Office, Back-Office, Project, Modules etc.

**Comment by prestarocket** [comment]
sorry, i'm a "boulet"

**Comment by xBorderie** [comment]
And you're still change the Pull-Request's title through the GitHub interface :)
To change a commit's name, you need to use the Git command itself, not GitHub interface -- you can't do that through GitHub, you have to use the command line on your desktop computer.
Use the documentation link I gave you.
And yes, changing "add New hook after body" into "[+] FO : New hook after opened body tag" is the right way to go -- but as a commit name, not as a PR title :)
You can do it! I trust you! :)

**Comment by prestarocket** [comment]
aaahhhhh

**Pull request closed without merging**
