### PR TITLE
Do not show price when catalog mode is enabled

### LINKED ISSUE #9937: [BOOM-3522] Native Catalog Mode Displays Product Prices
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3522).

- _**Reporter:**_ elpatron
- _**Created at:**_ Sat, 22 Jul 2017 20:02:26 +0200

<p>Hi ps team.  All previous versions of PrestaShop,  when native catalog mode enabled.  Would hide prices.</p>

<p>We noticed that 1.7 displays prices.  We suggest either hiding prices or better yet in conjunction with catalog mode have option to display or not display prices.</p>

<p>Loving 1.7, lots of new dev I could never do in previous versions, having template inheritance is a 'big deal'...hugs el</p>
        
* How to reproduce the issue ?

enable native prestashop catalog mode...see fo to see prices

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes #9937 
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9937 
| How to test?  | Enable catalog mode before this change, prices are shown, enable catalog mode after this change, prices are properly hidden

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12546)

### CODE REVIEW

**Comment by kpodemski** [comment]
oh, nevermind, i just noticed that there's completely different idea for this one 👎 #11742

**Comment by mickaelandrieu** [comment]
> oh, nevermind, i just noticed that there's completely different idea for this one 

do we have to merge your pull request or not then? I'm a little bit lost here :thinking: ...

**Review by mickaelandrieu — APPROVED** [review]

**Comment by marionf** [comment]
@kpodemski 

We would like to let the merchant choose if he/she wants to display prices when he/she activates catalog mode
And there is already a PR in progress for that: #11688

**Comment by Quetzacoalt91** [comment]
Hi @kpodemski, 

As said by @marionf, another pull-request is in progress by @jolelievre and should be merged this week in order to be part of the improvements on PrestaShop 1.7.6.0.
I'm closing yours as it duplicates the changes and could create conflicts on merge.

**Pull request closed without merging**
