### PR TITLE
[+] StarterTheme: add body classes

### PR DESCRIPTION
**Pull request by julienbourdeau**
Now we'll add many classes to the HTML body. 2 of them are available on every pages:
- layout name
- page name

Then some pages have extra classes. I only worked on Product, CMS and Category page. We'll see if more page need this kind of variants ([following RSCSS](http://rscss.io/variants.html)).
### Product

``` html
<body id="product" class="layout-full-width page-product -id-3 -robe-imprimee -id-category-9 -id-manufacturer-1 -id-supplier-1 -on-sale -available-for-order -customizable">
```
### Category

``` html
<body id="category" class="layout-full-width page-category -id-8 -robes -id-parent-3 -depth-level-3">
```
### CMS

``` html
<body id="cms" class="layout-full-width page-cms -id-8">
```

### CODE REVIEW

**Comment by maximebiloe** [comment]
:+1:

**Comment by kpodemski** [comment]
It will be a nice addition to have possibility to add custom classes for Category or CMS or other Controller via Module

**Comment by julienbourdeau** [comment]
Do you have a use case in mind ? Do you want to add classes to prefix your module css or trigger some css like modernizr (sort of) ?

**Comment by kpodemski** [comment]
Sure, let's assume that I'd like to target styling of I don't know... `#header` of the page based on `id_post` in my module so I'd like to have additional `class` based on `Tools::getValue('id_post`')`, or i'd like to add addiitonal class to body if some things are `true` in my module :) 

We can do this via ModuleController or we can do this similar to `{addJsDef}`, yet I was using js for this

**Comment by kpodemski** [comment]
Hi @julienbourdeau 

From what I see it should be good enough to use `getTemplateVarPage()` in our ModuleController?

**Pull request merged**
