### PR TITLE
Bump some module versions

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Bump some module versions
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto tests 🟢  https://github.com/lartist/ga.tests.ui.pr/actions/runs/4530711633
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by FabienPapet — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
CLDR fails

cc @PrestaShop/qa-functional

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

ping @PrestaShop/qa-automation What do you think about the CLDR fails?

**Comment by boubkerbribri** [comment]
@lartist Sometimes PrestaShop fails to create multiple currencies (some cache problem maybe), if you could restart that fail one please.

**Comment by lartist** [comment]
> @lartist Sometimes PrestaShop fails to create multiple currencies (some cache problem maybe), if you could restart that fail one please.

Done ✅

**Review by jolelievre — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @lartist 

Following the automatic tests launched and which are green https://github.com/lartist/ga.tests.ui.pr/actions/runs/4530711633

It's QA :heavy_check_mark: 

Thank You!

**Comment by jolelievre** [comment]
Thanks @lartist and @HanaRebaiQA

**Pull request merged**
