### PR TITLE
Fix total total_price_tax_excl

### PR DESCRIPTION
**Pull request by maniT4c**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | "total_price_tax_excl"value is wrong for "The_adventure_begins_Framed_poster" in "order_detail_3" should be 158 and not 79 because quantity of this product is set to 2
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | -
| Related PRs       | -
| How to test?      | -
| Possible impacts? | -

### CODE REVIEW

**Review by zuk3975 — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
I think we can merge without QA, it's only fixtures and the change is legit.

**Review by FabienPapet — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
I just launched the automatic campaigns for this PR https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3730085724 it should be enough for tests, not sure functional QA is really needed on this one

**Review by boubkerbribri — APPROVED** [review]
I saw the automatic campaign run, fails are false flags , it should be all good.

**Comment by Hlavtox** [comment]
Thanks guys!

**Pull request merged**
