### PR TITLE
Replace legacy cart rule creation methods in behats with new CQRS steps

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Following PR https://github.com/PrestaShop/PrestaShop/pull/32483, this one replaces all legacy cart rule creation steps with new ones and removes unused methods. There is still some things to refactor, but should be done in yet additional dedicated PR.
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Nothing to test manually.
| Fixed ticket?     | 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by mflasquin — COMMENTED** [review]
Tests are red :/

**Review by matthieu-rolland — APPROVED** [review]

**Review by boherm — APPROVED** [review]
LGTM @zuk3975 :)

**Review by florine2623 — APPROVED** [review]
Hello @zuk3975 ,

Auto tests are green : https://github.com/florine2623/testing_pr/actions/runs/5375853551

Thanks @zuk3975 !

**Comment by nicosomb** [comment]
Thank you @zuk3975 !

**Pull request merged**
