### PR TITLE
Added missing Rewrite base on Api rule

### PR DESCRIPTION
**Pull request by 123monsite-regis**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | missing Rewrite base on Api rule : on server configuration whith customs rewrite base, [shop Url]/api does not target correctly [shop Url]/api/ as the rule should do. 
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | enable rewriting and web service, then go on [shop Url]/api

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9034)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Maybe we can change both lines by:

```
RewriteRule ^api(?:/(.*))?$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]
```

**Comment by 123monsite-regis** [comment]
@PierreRambaud , i modified my commit whith your proposition.
thanks

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Really sorry for the delay :/ Can you rebase your branch?

**Comment by 123monsite-regis** [comment]
mm, i tried to rebase,
sorry i'm not a really good expert on rebasing a quick patch done with github interface.
if rebase is not ok, tell me and i will close this pull and open an other.

**Comment by PierreRambaud** [comment]
It looks ok for Github, so it's ok for us :D

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @123monsite-regis

**Pull request merged**
