### PR TITLE
Improving Clarity: Refactor Image Link Handling in Link.php

### PR DESCRIPTION
**Pull request by dali-rajab**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Refactoring image link generation in `classes/Link.php`. This PR aims to standardize and improve the readability of image link generation code within the mentioned file.
| Type?             | refacto
| BC breaks?        | no
| Category          | CO
| Deprecations?    | No
| Fixed ticket?        | N/A
| How to tests       | This is only a refactoring, no behavior is changed. Running UI tests https://github.com/matks/ga.tests.ui.pr/actions/runs/7475467153 ✅

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
Hello @dali-rajab can you please complete the PR table and provide a better PR title?

**Review by Hlavtox — APPROVED** [review]

**Comment by dali-rajab** [comment]
@matks ok it's done !

**Review by 0x346e3730 — APPROVED** [review]

**Review by matks — APPROVED** [review]
Thank you 👍 much better

**Comment by matks** [comment]
Running UI Tests https://github.com/matks/ga.tests.ui.pr/actions/runs/7475467153

**Pull request merged**
