### PR TITLE
[-] FO, obey SSL settings

### PR DESCRIPTION
**Pull request by doekia**
[-] FO, obey SSL settings

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by doekia** [comment]
Yes the patch is still valid and should be applied.

No I will not make yet another PR for such when it concern a single easy line of code to change.
The PR was just fine 6month ago and applied to the accurate branch at that time .

If you see any conflict not my fault

**Comment by xBorderie** [comment]
Hey @doekia , thank you for your feedback!

Sadly, since this PR was made on the `1.6` branch (which is not used anymore), could you make it again on the `1.6.1.x` branch so that you get full credit once we merge it? Even better if you do it on the `develop` branch, so that it lands in PS 1.7 :)

Thank you very much!

**Comment by maximebiloe** [comment]
Hello,

Thanks but in front office, you should use `Tools::getShopProtocol()` to know if HTTPS is available.
That's what we've made on the 1.7 front office.

Regards

**Comment by doekia** [comment]
Yet again card shuffling rather than rethink and fix once for ever the issue.
There is no per shop ssl settings - a miss yes but you do not even noticed it ! The SSL_EVERYWHERE is everywhere forgotten !! Tools::getShopProtocol() does not obey SSL settings in 1.7 !!

- Tools::getProtocol()
- Tools::getHttpHost()
- Tools::getShopDomain()
- Tools::getShopDomainSsl()
- _PS_BASE_URL_SSL_ _PS_BASE_URL_
- $base_dir, $base_dir_ssl
- Shop::getProto()  <-- PR marked as future implementation 1.7
- Tools::getCurrentUrlProtocolPrefix()
- $protocol_link = (Tools::usingSecureMode() && Configuration::get('PS_SSL_ENABLED')) ? 'https://' : 'http://'
- Configuration::get('PS_SSL_ENABLED') && Configuration::get('PS_SSL_ENABLED_EVERYWHERE')
- $use_ssl
- $force_ssl
-  preg_replace('#^https?://[^/]+/#', '/', $smarty.server.HTTP_REFERER) != $request_uri}

**Comment by julienbourdeau** [comment]
Hi doekia,

We know there is multiple way to get the SSL base url.

I'm thinking out loud here:

* Use `$shop->getUrl()` that will return "http://www.myshop.com/basedir" or "https://www.myshop.com/basedir" if you have SSL
* Use `$shop->domain`, `$shop->physical_uri`, `$shop->virtual_uri`, `$shop->use_ssl` for chunk of URL (if you need it)
* Remove `PS_SSL_ENABLED_EVERYWHERE` option, once you enable ssl (`PS_SSL_ENABLED` option), we redirect all traffic to https, the whole site isn't accessible without SSL. Google consider SSL in it's ranking, if you have a valid certificate there is absolutely no reason to not use SSL.
* Deprecate every other method (all of them!)

What do you think ?

**Comment by doekia** [comment]
Yet again, an interpretation of the need. Google behaviour interpretation does not make sense. 

SSL_ENABLED (only checkout/account) and SSL_ENABLED_EVERYWHERE cover all possible scenarii from now and any future - whatever this future be. Stick to that, make it per shop tunable and we are set. Choose only one of the method ** document it ** if behaviour complies or make a new one  - ** document it ** - end of the story.

I have at least 2 cases where EVERYWHERE is not possible 
One is a site that should provide this in iframe http://www.easysysteme.fr/vues/index.php
Your scenario kills it all

As a general rule:
- providing options - I am against preselection but even - is fine.
- Making hidden technical/system choice is not only bad it is out of the scope of a CMS

**Pull request closed without merging**
