### PR TITLE
Remove short_description field from the Suppliers importer

### LINKED ISSUE #20834: Suppliers import missing [short_description] field issues
Advanced Parameters -> Import

When you select Suppliers for import, the right side prompts for available fields:

ID
Active (0/1)
Name
Description
Short description
Meta title
Meta keywords
Meta description
Image URL
ID / Name of group shop
However, ps_supplier_lang does not contain short_description field.

Request the PrestaShop official to add the short_description field.

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Suppliers never had, and probably should not need `short_description`, most of the time, they are hidden in the stores and used for internal logistics in the store, thus I decided to remove this field from import instead of adding a field to Supplier entity
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #20834.
| Related PRs       | n/a
| How to test?      | Try to import Supplier and make sure there is no `short_description` field anymore, and you can still import supplier
| Possible impacts? | n/a
| Sponsor company | impSolutions

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by marsaldev — DISMISSED** [review]

**Comment by marsaldev** [comment]
~~will the field be removed from the DB?~~
~~(or has it already been removed?)~~
There is no a short_description field in the DB ^^"

**Review by florine2623 — COMMENTED** [review]
Hello @kpodemski ,

Works like a charm. I just noticed there's a missing `<p>` tag at the end the "Description" column of the example import file for Suppliers.
Could you add it ? It was already like that in previous version. There's no negative effect on the BO nor the import part, but it can't hurt to add it ^^

https://user-images.githubusercontent.com/16019289/196702537-e0bff649-d170-4cdb-ad58-2fc0b08366de.mov

Import is OK ✅ 

Thanks :)

**Review by jolelievre — DISMISSED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
LGTM !

It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
Thanks @florine2623 :)

**Pull request merged**
