### PR TITLE
Delete legacy AdminPreferences controller

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Deleted legacy AdminPreferences controller, as corresponding page is migrated.
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No changes in user interface

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13847)

### CODE REVIEW

**Comment by matks** [comment]
@zuk3975 Travis might have found an usage for this legacy controller
```
1) LegacyTests\PrestaShopBundle\Controller\ControllerTest::itShouldRunTheTestedController with data set #30 ('AdminStatsController')
PHPUnit_Framework_Exception: Fatal error: Class 'AdminPreferencesControllerCore' not found in /home/travis/build/PrestaShop/PrestaShop/controllers/admin/AdminStatsTabController.php on line 27
```
Can you check ?
https://travis-ci.org/PrestaShop/PrestaShop/jobs/534166485

**Comment by zuk3975** [comment]
> @zuk3975 Travis might have found an usage for this legacy controller
> 
> ```
> 1) LegacyTests\PrestaShopBundle\Controller\ControllerTest::itShouldRunTheTestedController with data set #30 ('AdminStatsController')
> PHPUnit_Framework_Exception: Fatal error: Class 'AdminPreferencesControllerCore' not found in /home/travis/build/PrestaShop/PrestaShop/controllers/admin/AdminStatsTabController.php on line 27
> ```
> 
> Can you check ?
> https://travis-ci.org/PrestaShop/PrestaShop/jobs/534166485

@matks, yep i missed that. AdminStatsTabController is extending it, and that one isn't migrated, so we can close this.

**Comment by matks** [comment]
Can we try to remove the public functions from AdminPreferences that are not used anymore ?
At least let's remove the dead code 😉

**Comment by zuk3975** [comment]
> Can we try to remove the public functions from AdminPreferences that are not used anymore ?
> At least let's remove the dead code

ok, ill create new PR once i can rely on tests, because currently they are failing on 1.7.6.x so i cannot test if my code doesn't ruin anything.

**Pull request closed without merging**
