### PR TITLE
// BYE BYE PRESTASHOP

### PR DESCRIPTION
**Pull request by kelu95**
Don't merge this...

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
Tests Ok, merged.

Thank you @kelu95

**Comment by tchauviere** [comment]
ByeBye

**Comment by xGouley** [comment]
:'(

**Comment by julienbourdeau** [comment]
:(

**Comment by kpodemski** [comment]
http://i.imgur.com/0UIwFbR.gif

**Comment by Quetzacoalt91** [comment]
Bye bye !

**Comment by xBorderie** [comment]
tumblr_m55qpoqgfg1rxevt4o1_400

**Comment by AlexEven** [comment]
If you want to open a new PR, the official spelling is "PrestaCrew", not "prestacrew" :smirk:

See you! :)

**Pull request closed without merging**
