### PR TITLE
Improve pop up information on Category deletion

### LINKED ISSUE #15567: Improve pop up information on Category deletion
The information displayed in the pop-up when removing a category is not clear, we should improve the content to make it more understandable. 
image

For instance, there is no information about what is happening for products which belong to 2 different categories when one of them is deleted.

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve pop up information on Category deletion
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15567
| How to test?  | Go in BO > Sell > Catalog > Categories <br>Select a category<br/>Try to remove it<br/>Wording must be changed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15886)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by LouiseBonnard** [comment]
Hi @Progi1984, could you please keep the recommended option at the second place like it was in the issue? It looks much more logic when it is read secondly since it refers to the first option.

Also, the note at the end was meant to be displayed. Can you add it? You can keep the same domain. ;-)

**Comment by Progi1984** [comment]
@LouiseBonnard A note like that ?
image

Poke @TristanLDD @colinegin

**Comment by TristanLDD** [comment]
Hi @Progi1984, I have a few design comments about that popup:

- Use Google material icons for radio buttons
- Use the color #7A8A8F instead of red for the radio buttons checked and unchecked states
- Add 10px of vertical spacing between each options, and 10px of horizontal spacing between radio buttons and option's first letter. 
- Change the wording of the button for "Supprimer la catégorie" so the action is clear (otherwise it's can be unclear if we're talking about deleting products or category)

Thx ! :)

**Comment by Progi1984** [comment]
Hi @TristanLDD, it's totally out of the scope of the initial issue. In addition to that, I think that a CSS modification like you want impact all modals and not just this one. Could you create an issue for that ?

Initially, I pinged you and @colinegin for the style of the note.

**Comment by PierreRambaud** [comment]
@Progi1984 I confirm that if it's something more than just wording, we should create a new issue and be sure it's for all modal or only this one :)

**Comment by TristanLDD** [comment]
@Progi1984 
I thought we were talking about the popup here, my bad. About the note itself, I'm ok with it.

**Comment by Progi1984** [comment]
Just waiting for @LouiseBonnard before review

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
