### PR TITLE
FIX - make force ssl work on all links

### PR DESCRIPTION
**Pull request by humpfreybogart**
using SSL and forcing SSL I had issues with some links that still was http://
This was the best way to fix it.
Please let me know if there is a better fix
www.dyrefoder.dk

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Can you please detail wich links ?

Thank you. Regards

**Comment by michaelhjulskov** [comment]
Hi,
Yes example is use of {$base_dir}
inside header.tpl and other places.

**Comment by kpodemski** [comment]
This is old discussion, PrestaShop don't want to force ssl on $base_dir, you can use $base_dir_ssl instead

**Comment by michaelhjulskov** [comment]
Maybe thats your opinion, but not mine, as force  its not working so this is a fix. 
Base dir is used in default theme so...

**Comment by kpodemski** [comment]
That was already commented by @gRoussac in other PR

**Comment by michaelhjulskov** [comment]
Ok :-)
Do whatever u like 
This is my preferred way to fix/solve 
Chario

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, please use "Enable SSL on all pages" if you want to force ssl and use base_dir_ssl variable in your custom template.

Best regards.

**Comment by michaelhjulskov** [comment]
>please use "Enable SSL on all pages" if you want to force ssl 
I AM using "Enable SSL on all pages"
but let me repeat my self
it doesnt work on base_dir
AND base_dir is used several places, also by defalt theme
so do whatever, but dont tell me Im wrong, please, cause Im not

**Comment by jeromenadaud** [comment]
Please check this PR #3597, changes will be available in next release.

Best regards

**Comment by michaelhjulskov** [comment]
Or leave it up to shop manager whether or not to force https on base_dir
So add one more option to the configuration/settings in BO
FORCE_SSL_ON_BASE_DIR

**Pull request closed without merging**
