### PR TITLE
Show the attributes list in combinations tabs

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If you add more languages and delete the first one, you will have no attributes set to Language ID 1. While you check the combinations tab, no attributes will be show due of this process.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Add one more language. Delete the first one. Add some attributes. Check the combinations tab of product form.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8703)

### CODE REVIEW

**Review by PrestaEdit — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Sorry, but that issue is already in progress in https://github.com/PrestaShop/PrestaShop/pull/8341.
That'd be great if you take some to review the other one. :)

**Comment by Quetzacoalt91** [comment]
Closed to avoid duplicates. Thanks!

**Comment by PrestaEdit** [comment]
J’approuve ta désapprobation.

**Comment by PrestaEdit** [comment]
This PR is born the 25 january. It was closed few days later, about another PR. The #8341 and... guess what ?

**Pull request closed without merging**
