### PR TITLE
Fix prestashop gifts and cart calculation when gift separation is enabled

### LINKED ISSUE #9757: [BOOM-4701] Free GIFT is not displayed correctly on cart
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4701).

- _**Reporter:**_ tantan199
- _**Created at:**_ Fri, 26 Jan 2018 10:50:03 +0100

I added a gift to all products on my store, the problem is that the price of the gift is displayed on the shopping cart page, another problem is that the quantity of the gift is adjustable. See attached pictures.

Because the cart variable from the `controller/front/CartController.php` filed gets override by another cart variable from the assignGeneralPurposeVariables function in the `/classes/controller/ProductListingFrontController.php`

**Temporary solution is change this code**
`'cart' => $this->cart_presenter->present($this->context->cart),`

in the assignGeneralPurposeVariables function to 

`cart' => $this->cart_presenter->present($this->context->cart, $shouldSeparateGifts = true),`

The same problem also exist in the Shopping cart module.

---
When I apply a cart rule that offers an item, it should behave the same as in 1.6

- when adding a product that meets the conditions of a cart rule in the cart, do not take into account the gift price calculations. Currently, we add the product with its price and then apply a reduction of this amount.
- **The recycle bin to delete a gift does not work** (see #24831)
- display the product as a gift, remove the possibility of modifying the quantity and no longer display the price either in the basket and at the time of payment.

Capture du 2018-02-20 11-25-39

- If my cart rule offers an item & a reduction (in amount or %), a "Discount" field appears in the cart.
- This field must not include the amount of the product offered but only the reduction -> OK.
- Same for the orange line with the promo, it must not include the amount of the product offered but only the reduction -> NOK

Capture du 2018-04-17 15-48-03

Capture du 2018-04-17 15-47-50

- In the case that I buy a product that is offered, 2 lines must appear in the cart.
- The discount field should not include the amount of the product offered but only the discount -> NOK.
- Same for the orange line with the promo, it must not include the amount of the product offered but only the reduction -> NOK

Capture du 2018-04-17 16-12-58

Capture du 2018-04-17 15-55-47

We should also replace "Discount" by "Total vouchers" as in 1.6, it was clearer like this

### LINKED ISSUE #16486: Cart presenter totals wrong when shouldSeparateGifts is true
**Describe the bug**
In order to display cart gifts correctly, CartPresenter->present must be called with shouldSeparateGifts as true. This was proposed in this PR: #8706.

**To test, change bold to true:**
classes/controller/FrontController.php - Line 490 - 'cart' => $this->cart_presenter->present($this->context->cart, **true**),

Now, this works until you put another pieces of the _product you got as a gift_ to cart.

**1 - WRONG TOTALS**
From then, cart totals are wrong, because the totals are calculated from wrong quantity variable.

**Example**
Product ABC with price 100.
You add 5 to cart manually.
You get 1 free because you got over XXX amount or applied a voucher.
Total products should be 600, but it is 1200. 

**2 - WRONG DISCOUNTS**
Another bug - product gets discounted twice.

**Additional information**
PrestaShop version: 1.7.6.0.

### PR DESCRIPTION
**Pull request by Hlavtox**
THIS IS REPLACEMENT PR. I closed the old one because I messed it up with my amazing git skills. - #16573

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR fixes display of gift products in cart and allows them to be displayed separately. The UI was provided, but it was disabled probably due to wrong calculations, which this PR fixes.
| Type?         | bug fix / improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16486 & Fixes #9757
| How to test?  | Enable some gift rules, enable some discount rules, add everything to cart, all calculations will be correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16573)

### CODE REVIEW

**Comment by jf-viguier** [comment]
Good luck for git stuff, it's sometime easier to make an new pr than this rebasing nightmare. 
I'm happy to see that I'm not the only one. Ping @matks

**Comment by Hlavtox** [comment]
@eternoendless Regarding this:
> How do you feel about adding a new test case here that validates this bug fix? It should fail without your change and succeed with it. Adding automated tests help us verify that your change does what it's supposed to do, and keeps doing it afterwards.

To be honest, I see the tests the first time in my life, so, maybe someone can help? 🙄 

@jf-viguier I clicked revert commit and I had more file changes than before. I thought that it will just put the branch to the state it was before, but... 😄

**Comment by Progi1984** [comment]
Hello @Hlavtox, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by Hlavtox** [comment]
@Progi1984 Can I kindly ask for you to rebase it, if possible? ❤️ 😄 I don't want to mess it up.

**Comment by Progi1984** [comment]
@Hlavtox Sorry, but I don't arrive to rebase this PR :( (It created in february and a lot have been done since).

Could you update your branch `develop` in your repository, before creating a new branch based on this ?

**Comment by jf-viguier** [comment]
@Progi1984 @Hlavtox we need this fix, it's a nice one. Can we expect this in prestashop one day or another ?

**Comment by Hlavtox** [comment]
@jf-viguier @Progi1984 I think I successfully managed to update my develop branch and the patch-7 this PR comes from!!! 🚀 😄

**Comment by Progi1984** [comment]
@Hlavtox Your PR broke a behat test : https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/316764900#L5007

**Comment by Azeus1980** [comment]
hi @Hlavtox,
We are in 1.7.6.1 and when i activate your patch with your 3 commit i sometimes have a bug.
Between 1 and 2% of orders arrive without order status and the script doesn't execute the end of the recording of the order. I don't find any common point in these orders, carrier, product, customer. Even the discounts they contain are of all types.
The other commands have no problem and I have not succeeded in reproducing the bug.
Am I the only one with this problem?

**Comment by Hlavtox** [comment]
@Progi1984 I will have a look into it.

@Azeus1980 Hm hm, that's weird. I am running this fix for 4 months and several thousands of orders and everything is fine. Are you sure it's not caused by some module? What's hooked to your validateOrder hook?

**Comment by Azeus1980** [comment]
@Hlavtox thanks for your reply

actionValidateOrder 12 Modules
1 Advanced Pack	Advanced Pack  - v5.2.11	
2 Darique	Darique  - v2.4.43
3 Expertise PrestaShop	Expertise PrestaShop  - v2.3.1	
4 DPD France	DPD France  - v5.3.1
5 Chronopost	Chronopost  - v4.7.0	
6 Avis Vérifiés	Avis Vérifiés  - v7.8.1	
7 Colissimo - Officiel : Gérer vos expéditions avec Colissimo.	Colissimo - Officiel : Gérer vos expéditions avec Colissimo.  - v9.9.9
8 Notes et Avis Client Pro + Google Rich Snippets	Notes et Avis Client Pro + Google Rich Snippets  - v4.4.0
9 EMARSYS Email Data Base	EMARSYS Email Data Base  - v1
10 Google Analytics Pro	Google Analytics Pro  - v1.1.4
11 Alertes par e-mail	Alertes par e-mail  - v2.1.1	
12 Récompenses : Fidélité, Parrainage multi niveaux, Affiliation, Facebook...	Récompenses : Fidélité, Parrainage multi niveaux, Affiliation, Facebook...  - v4.1.5

The first module should change some product in the cart and he is not executed. I don't have any error in the log. Maybe the script enter in a infinite loop before the execution of this Hook.
We have around 400-600 order by days. When i remove the correction on the CartRuleCalculator.php we don't have the bug in the orders.

Thanks

**Comment by LouiseBonnard** [comment]
@Hlavtox, what's the status of this PR? Thanks!

**Comment by Hlavtox** [comment]
@LouiseBonnard Sorry for not answering, I will close this, I don't have time and skills to finish it.

**Pull request closed without merging**
