### PR TITLE
Refacto of htaccess

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | A lot of work is done. Please check diff.
| Type?         | refacto
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/13226, https://www.sunnytoo.com/40385
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14125)

Example of new output:

```
# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_rewrite.c>
    RewriteEngine on
    <IfModule mod_env.c>
        SetEnv HTTP_MOD_REWRITE On
    </IfModule>

    # Domain: localhost

    # ENV
    RewriteRule . - [E=REWRITEBASE:/]

    # API
    RewriteRule ^api$ api/ [L]
    RewriteRule ^api/(.*)$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

    # Product URL
    RewriteRule ^([0-9])([0-9]*(?:\-[_a-z0-9-]*)?(?:-[0-9]+)?)\/(.+)\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp)(?:\/img\/p\/((?:[0-9]\/)+)(.*))?$ $2/$3.$4/img/p/$5$1/$6$1 [NC,N,L]
    RewriteRule ^(?:\-[_a-z0-9-]*)?(?:-[0-9]+)?\/.+\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp)\/(img\/p\/([0-9]\/)+.*)$ %{ENV:REWRITEBASE}$2.$1 [NC,L]

    # Category URL
    RewriteRule ^c\/([a-z_-]+|[0-9]+-[\.*_a-z0-9-]*(?:-[0-9]+)?)\/.+\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp)$ %{ENV:REWRITEBASE}img/c/$1.$2 [NC,L]

    # AlphaImageLoader for IE and fancybox
    ReWriteRule ^images_ie\/?([^\/]+)\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp)$ %{ENV:REWRITEBASE}js/jquery/plugins/fancybox/images/$1.$2 [NC,L]

    # Dispatcher
    RewriteCond %{REQUEST_FILENAME} -s [OR]
    RewriteCond %{REQUEST_FILENAME} -l [OR]
    RewriteCond %{REQUEST_FILENAME} -d
    RewriteRule ^.*$ - [NC,L]

    # Index
    RewriteRule ^.*$ %{ENV:REWRITEBASE}index.php [NC,L]
</IfModule>

<IfModule mod_mime.c>
    AddType application/atom+xml atom
    AddType application/json json map topojson
    AddType application/ld+json jsonld
    AddType application/rss+xml rss
    AddType application/geo+json geojson
    AddType application/rdf+xml rdf
    AddType application/xml xml
    AddType text/javascript js mjs
    AddType application/manifest+json webmanifest
    AddType application/x-web-app-manifest+json webapp
    AddType text/cache-manifest appcache
    AddType audio/mp4 f4a f4b m4a
    AddType audio/ogg oga ogg opus
    AddType image/bmp bmp
    AddType image/svg+xml svg svgz
    AddType image/webp webp
    AddType video/mp4 f4v f4p m4v mp4
    AddType video/ogg ogv
    AddType video/webm webm
    AddType video/x-flv flv
    AddType image/x-icon cur ico
    AddType application/wasm wasm
    AddType font/woff woff
    AddType font/woff2 woff2
    AddType application/vnd.ms-fontobject eot
    AddType font/ttf ttf
    AddType font/collection ttc
    AddType font/otf otf
    AddType application/octet-stream safariextz
    AddType application/x-bb-appworld bbaw
    AddType application/x-chrome-extension crx
    AddType application/x-opera-extension oex
    AddType application/x-xpinstall xpi
    AddType text/calendar ics
    AddType text/markdown markdown md
    AddType text/vcard vcard vcf
    AddType text/vnd.rim.location.xloc xloc
    AddType text/vtt vtt
    AddType text/x-component htc
</IfModule>

<IfModule mod_setenvif.c>
    <IfModule mod_headers.c>
        <FilesMatch "\.(bmp|cur|gif|ico|jpe?g|png|svgz?|webp)$">
            SetEnvIf Origin ":" IS_CORS
            Header set Access-Control-Allow-Origin "*" env=IS_CORS
        </FilesMatch>
    </IfModule>
</IfModule>

<IfModule mod_headers.c>
    <FilesMatch "\.(eot|otf|tt[cf]|woff2?)$">
        Header set Access-Control-Allow-Origin "*"
    </FilesMatch>
</IfModule>

<IfModule mod_filter.c>
    AddOutputFilterByType DEFLATE "application/atom+xml" \
                                  "application/javascript" \
                                  "application/json" \
                                  "application/ld+json" \
                                  "application/manifest+json" \
                                  "application/rdf+xml" \
                                  "application/rss+xml" \
                                  "application/schema+json" \
                                  "application/geo+json" \
                                  "application/vnd.ms-fontobject" \
                                  "application/wasm" \
                                  "application/x-font-ttf" \
                                  "application/x-javascript" \
                                  "application/x-web-app-manifest+json" \
                                  "application/xhtml+xml" \
                                  "application/xml" \
                                  "font/eot" \
                                  "font/opentype" \
                                  "font/otf" \
                                  "image/bmp" \
                                  "image/svg+xml" \
                                  "image/vnd.microsoft.icon" \
                                  "text/cache-manifest" \
                                  "text/calendar" \
                                  "text/css" \
                                  "text/html" \
                                  "text/plain" \
                                  "text/markdown" \
                                  "text/vcard" \
                                  "text/vnd.rim.location.xloc" \
                                  "text/vtt" \
                                  "text/x-component" \
                                  "text/x-cross-domain-policy" \
                                  "text/xml"
</IfModule>

<IfModule mod_mime.c>
    AddEncoding gzip svgz
</IfModule>

<IfModule mod_headers.c>
    Header unset ETag
</IfModule>

FileETag None

<IfModule mod_expires.c>
    ExpiresActive on
    ExpiresDefault "access plus 1 month"
    ExpiresByType text/css "access plus 1 year"
    ExpiresByType application/atom+xml "access plus 1 hour"
    ExpiresByType application/rdf+xml "access plus 1 hour"
    ExpiresByType application/rss+xml "access plus 1 hour"
    ExpiresByType application/json "access plus 0 seconds"
    ExpiresByType application/ld+json "access plus 0 seconds"
    ExpiresByType application/schema+json "access plus 0 seconds"
    ExpiresByType application/geo+json "access plus 0 seconds"
    ExpiresByType application/xml "access plus 0 seconds"
    ExpiresByType text/calendar "access plus 0 seconds"
    ExpiresByType text/xml "access plus 0 seconds"
    ExpiresByType image/vnd.microsoft.icon "access plus 1 week"
    ExpiresByType image/x-icon "access plus 1 week"
    ExpiresByType text/html "access plus 0 seconds"
    ExpiresByType application/javascript "access plus 1 year"
    ExpiresByType application/x-javascript "access plus 1 year"
    ExpiresByType text/javascript "access plus 1 year"
    ExpiresByType application/manifest+json "access plus 1 week"
    ExpiresByType application/x-web-app-manifest+json "access plus 0 seconds"
    ExpiresByType text/cache-manifest "access plus 0 seconds"
    ExpiresByType text/markdown "access plus 0 seconds"
    ExpiresByType audio/ogg "access plus 1 month"
    ExpiresByType image/bmp "access plus 1 month"
    ExpiresByType image/gif "access plus 1 month"
    ExpiresByType image/jpeg "access plus 1 month"
    ExpiresByType image/png "access plus 1 month"
    ExpiresByType image/svg+xml "access plus 1 month"
    ExpiresByType image/webp "access plus 1 month"
    ExpiresByType video/mp4 "access plus 1 month"
    ExpiresByType video/ogg "access plus 1 month"
    ExpiresByType video/webm "access plus 1 month"
    ExpiresByType application/wasm "access plus 1 year"
    ExpiresByType font/collection "access plus 1 month"
    ExpiresByType application/vnd.ms-fontobject "access plus 1 month"
    ExpiresByType font/eot "access plus 1 month"
    ExpiresByType font/opentype "access plus 1 month"
    ExpiresByType font/otf "access plus 1 month"
    ExpiresByType application/x-font-ttf "access plus 1 month"
    ExpiresByType font/ttf "access plus 1 month"
    ExpiresByType application/font-woff "access plus 1 month"
    ExpiresByType application/x-font-woff "access plus 1 month"
    ExpiresByType font/woff "access plus 1 month"
    ExpiresByType application/font-woff2 "access plus 1 month"
    ExpiresByType font/woff2 "access plus 1 month"
    ExpiresByType text/x-cross-domain-policy "access plus 1 week"
</IfModule>

<IfModule mod_deflate.c>
    <IfModule mod_setenvif.c>
        SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
        RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
    </IfModule>
</IfModule>

# If rewrite_mod isn't enabled
ErrorDocument 404 /index.php?controller=404

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
```

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
The main advantage of using `fwrite` is to prevent storing data in a variable. As we deal with a stream, we can directly send the data to write in the file and prevent memory to be filled with all the content.

What are the reasons to use an array in this PR?

**Comment by MathiasReker** [comment]
> 
> 
> The main advantage of using `fwrite` is to prevent storing data in a variable. As we deal with a stream, we can directly send the data to write in the file and prevent memory to be filled with all the content.
> 
> What are the reasons to use an array in this PR?

Mainly to make the code more readable.

**Comment by PierreRambaud** [comment]
@MathiasReker I think `fwrite` is also readable.

**Comment by MathiasReker** [comment]
@Quetzacoalt91 @PierreRambaud I agree, I can change it to `fwrite`. I think this change is a "minor" thing is this PR. If everything else is OK, I can made the change, but I think the new structure and new rules should be focused. Also I am not sure all those changes should be made in one PR. Maybe this PR should be used as inspiration to a better solution.

**Comment by PierreRambaud** [comment]
Make the change, and I will review it again on Monday. :)

**Comment by MathiasReker** [comment]
I will make the change in this week. :)

**Comment by matks** [comment]
It was a really long week 😛

**Comment by PierreRambaud** [comment]
Hi @MathiasReker ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
