### PR TITLE
Add  contributors to copyright in LICENSE.md

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | add  contributors to LICENSE.md
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28105)

### CODE REVIEW

**Comment by kpodemski** [comment]
Seems ok, it's the same in the license headers inside the core.

**Review by PululuK — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]
Content is OK 👍  but I wonder if we can change a LICENSE file just like this or if we need to do some additional steps.

@ttoine is this OK to make this change, given that indeed all the license headers have the target pattern?

**Comment by ttoine** [comment]
Yes, sure. This was just something we forgot to update at the time we improved file headers.

**Review by ttoine — APPROVED** [review]

**Comment by matks** [comment]
🎉

**Comment by jf-viguier** [comment]
🚀

**Pull request merged**
