### PR TITLE
Corrects some CORE wordings

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Correction of wordings
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No tests needed it's just wording
| Fixed ticket?     | 
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/31517/files/de0486303a8e64d1733187e63ad50ee5cf61a1d5#diff-8913750e531401bc4e6a272b2dbd244181f7e5770ef0828979b8859dca512e26
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-automation I think we could run auto-tests to see if any changes are required. What do you think?

**Comment by nesrineabdmouleh** [comment]
> @PrestaShop/qa-automation I think we could run auto-tests to see if any changes are required. What do you think?

Hello @kpodemski
Yes definitely, we also test messages on our UI tests.
Thank you

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4375777601

**Comment by kpodemski** [comment]
@nesrineabdmouleh one red test, but it doesn't look like it's related, could you confirm?

**Comment by nesrineabdmouleh** [comment]
Hello @kpodemski, yes it's not related to the PR (Same errors in nightly)
UI tests are :heavy_check_mark:

**Comment by kpodemski** [comment]
Thank you @lartist

**Pull request merged**
