### PR TITLE
Add hook to display the extra field added on the customer address form in the address block

### PR DESCRIPTION
**Pull request by PeeyushAgrawal**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR ie related to already merged PR - https://github.com/PrestaShop/PrestaShop/pull/9132. <br> In PR 9132 we have added a hook on customer address form to add extra address fields. To display these fields record in the address block on address front controller we need to add a hook in block-address.tpl file, which will help to display the extra added fields values.
| Type?         | new feature
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | By using the hook (as in commit) we can display the value of the field. This PR is related to https://github.com/PrestaShop/PrestaShop/pull/9132, please check.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12033)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
In the PR you linked, these fields are returned as an array. This hook could actually be reused by the theme to display them as it feels.

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 ,

Yes, in the linked PR we have added a hook to add the fields on the customer address form which returns an array of fields. 

But right now there is no way to display those field values in the address block of the addreses page. 
This PR is the solution for this problem.
By using this hook (added in this PR) we can display those fields value in the address block of the addresses page. This hook will return the html with the values of the fields which was added through the extra field hook(linked PR hook).

Thanks

**Comment by Quetzacoalt91** [comment]
I understand your point, but adding one more hook would mean for the module developers to register to it, then implement a new method to prepare the data to display.

On the other hand, reusing the same hook means we reuse directly the same data, and we let the theme handle it by itself. The only change would be adding a template for displaying this data.

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 

Please do not relate this #9132 PR for this hook requirement directly, you can ignore #9132 PR for now. My requirement is to display more data on address details card by some module by this hook 'displayAdditionalCustomerAddressFields'. Please see the screenshot. I think if PrestaShop adds this standard hook here, the other theme would also use this hook by default.
addresses

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 ,

Is there any update for my last reply? As I understand this hook should be there in PrestaShop core.

Thanks,

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 

Please check this and if anything is remaining from my end then please let me know.

Thanks

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 

There is no way to display the extra address details in the address block.
By adding this hook, 
the module developer can display the address extra details which are added by using "additionalCustomerAddressFields" hook.

Thanks.

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 
@PierreRambaud 
Please merge this PR. 

Thanks.

**Comment by PierreRambaud** [comment]
@PeeyushAgrawalWebkul We are waiting for QA feedback, to be sure everything is working as expected :)

**Pull request merged**
