### PR TITLE
[-] BO, SQL crash on search abandoned cart

### PR DESCRIPTION
**Pull request by doekia**
[-] BO, SQL crash on search abandoned cart

### CODE REVIEW

**Comment by PrestaEdit** [comment]
:+1:

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution.

Best regards

**Comment by jeromenadaud** [comment]
Modified my this : #3197

**Comment by doekia** [comment]
date_add vs date_upd? 
filter by date_sub(now(), interval 1 day)
performances!

**Comment by jeromenadaud** [comment]
Depending server configuration, SQL function now() is not the same as date('Y-m-d H:i:00', time())

**Pull request merged**
