### PR TITLE
Sample products in FA

### PR DESCRIPTION
**Pull request by mehrshadz**
Sample products translations in Persian language

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Persian translation for PrestaShop 1.7.3 sample products.
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Check it while a new installation.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8806)

### CODE REVIEW

**Comment by mehrshadz** [comment]
Please merge this PR before 1.7.3.0 stable version is released

Thanks

**Comment by mickaelandrieu** [comment]
Thanks for your contribution @mehrshadz!

Afaik, translations need to be done on [Crowdin](https://crowdin.com/project/prestashop-official): am I right @toutantic?

Regards,

**Comment by mehrshadz** [comment]
@mickaelandrieu
Thanks for your response. Unfortunately sample products and categories are not available inside Crowdin since Persian translation is 100% complete on Crowdin.

Regards,

**Review by toutantic — APPROVED** [review]
Demo product texts are directly translated in those files and not on crowdin.

**Pull request merged**
