### PR TITLE
Introduce module self configurator feature

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
- [x] Requires #7778 to be merged in order to link the feature with the command

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In order to make the global deployment process of PrestaShop easier, we allow server maintainers to execute configuration files for modules. See https://docs.google.com/document/d/1VADVkZiYM5dQsjxsFiJT4stj3EjCPqAPLBThuVLJMkA/edit?usp=sharing for more details.
| Type?         | new feature
| Category?     | CO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | You can test the feature with `app/console prestashop:module configure <module name>`, with the example files in https://github.com/PrestaShop/PrestaShop/pull/7889#issuecomment-302049872

### YAML config file example

```yml
# This file is an example of data configuration which can be applied to a module
# Paths are relative to the config file!

# Data to be updated in Configuration table
configuration:
    update:
        # Option 1: having a pair key/value
        PAYPAL_SANDBOX: 1
        PAYPAL_API_CARD: 0
        # Option 2: use "value" subkey. Will allow to use addtionnal keys later
        PAYPAL_SANDBOX_2:
            value: 1
            multilang: false
        # Question: how to handle multi lang values ?
    delete:
        - "PAYPAL_ONBOARDING"

# SQL files to execute 
sql:
    - file: "path/to/file1.sql"
    # But key is optionnal
    - "path/to/file2.sql"
    - "sql/default-config.sql"

# File to copy from local disk or website
files:
    - source: "../source/file.txt"
      dest: "docs/file.txt"
      
    - source: "https://www.prestashop.com"
      dest: "webpage.html"

# Fox complex configuration data, allow PHP code to be executed
php:
    - file: "path/to/file.php"
      # Must have a class which implements interface PrestaShop\PrestaShop\Adapter\Module\Configuration\ModuleComplexConfigurationInterface
      params:
        - myParam1: 1
        - oneArrayParam:
            - "value1"
            - "value2"
            - withSpecificKey: "value3"
```

### CODE REVIEW

**Comment by kpodemski** [comment]
Interesting!!! 👍

**Comment by Quetzacoalt91** [comment]
If you want to test the pull-request, you can use the following files:

### self_config.yml
This is the default name of the file. You can store it in the module you want to configure.

```yml
configuration:
    update:
        PAYPAL_SANDBOX_DOGE: 1
        PAYPAL_API_CARD_DOGE: 2
        PAYPAL_SANDBOX_2_DOGE: trololo
    delete:
        - "PAYPAL_ONBOARDING_DOGE"

sql:
    - file: "sample_doge.sql"

files:
    - source: "https://www.prestashop.com"
      dest: "webpage.html"

php:
    - file: "MyComplexModuleConfiguration.php"
      params:
        - myParam1: 1
        - oneArrayParam:
            - "value1"
            - "value2"
            - withSpecificKey: "value3"
    - file: "MyComplexModuleConfiguration.php"
```

### sample_doge.sql
To store in the same folder

```sql
INSERT 
INTO PREFIX_alias (`alias`, `search`, `active`) 
VALUES ("dog", "doge", 1)
```

### MyComplexModuleConfiguration.php
To store in the same folder

```php
use PrestaShop\PrestaShop\Adapter\Module\Module;
use PrestaShop\PrestaShop\Adapter\Module\Configuration\ModuleComplexConfigurationInterface;

class MyComplexModuleConfiguration implements ModuleComplexConfigurationInterface
{
    public function run(Module $module, array $params)
    {
        dump($module, $params);
    }
}
```

**Comment by 123monsite-regis** [comment]
nice :)
but, maybe hooks could be also declared on this file ?

**Comment by Quetzacoalt91** [comment]
Hello @123monsite-regis,

Do you think this is a relevant feature ? The module self configurator should run only on a installed module, and hooks are supposed to be registered as the same time as the module is installed.

I do not usually see modules registering more hooks once they are configured.

**Comment by 123monsite-regis** [comment]
we have some troubles with hooks and themes, now during 1.7 migrations, modules hooked to some places not declared on theme/yaml configuration does sometime unhook them.

**Comment by Quetzacoalt91** [comment]
For the moment, I would prefer to see if we can find a potential fix for your issue directly in the theme manager. If there is actually a bug, we should fix it instead of implementing a workaround here.

Anyway, if you really need to register hooks with this PR, you can already do it via the PHP files.

**Comment by maximebiloe** [comment]
Thank you @Quetzacoalt91 🐕

**Pull request merged**
