### PR TITLE
Fixed save of translation message

### LINKED ISSUE #23437: Trouble to translate multiple occurence of the same string in the same domain
#### Describe the bug

Translation is said to be validated. You've got the green popup right up the screen. But if you leave and come back or if you try to see the result you see translation has not changed.

#### Expected behavior

I don't know. Translation to be dealt or one unique field if ever the same string is twice in the domain.

#### Steps to Reproduce

1. Go to Translation and select backoffice
2. Search for "first name"
3. Select Admin > Global domain
4. You'll see the exact same string twice.
5. Try to change one and save
6. Leave translation
7. Redo 1-6 but change the other one
8. Redo 1-4 : you should notice just one of the two get changed

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by agostinofiscale**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Before the changes that i've done, the select query uses the **equal** comparison operator to find the row, i changed it with the **like** one. The equal comparison returns the values without checking the space after the last character so if you have a key named "first name " (notice the space after "name") and it searchs for "first name", it updates "first name".
| Type?             | bug fix
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23437.
| How to test?      | In the issue there are the instructions.
| Possible impacts? | Nope.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23443)

### CODE REVIEW

**Comment by agostinofiscale** [comment]
Am i wrong or the unit test failed not because of my code but because it cannot download a ".zip"?

**Comment by matks** [comment]
> Am i wrong or the unit test failed not because of my code but because it cannot download a ".zip"?

You are not wrong 😅  .

Network latencies can make integration tests fail, I relaunch the suite.

**Comment by agostinofiscale** [comment]
> > Am i wrong or the unit test failed not because of my code but because it cannot download a ".zip"?
> 
> 
> 
> You are not wrong 😅  .
> 
> 
> 
> Network latencies can make integration tests fail, I relaunch the suite.

@matks Thank you,seems like all is pass now :)

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
@agostinofiscale but is there a risk using this `LIKE` ?

If I have the following translations keys:
- "ABC number"
- "ABC number extra"

If I search "ABC number", I might be returned "ABC number extra" although I did not wanted this?

If the issue you try to solve is "when I leave an extra blank space at the end of the string, it does not ignore it", maybe a `trim()` would do the job?

**Comment by agostinofiscale** [comment]
> @agostinofiscale but is there a risk using this `LIKE` ?
> 
> If I have the following translations keys:
> 
> * "ABC number"
> * "ABC number extra"
> 
> If I search "ABC number", I might be returned "ABC number extra" although I did not wanted this?
> 
> If the issue you try to solve is "when I leave an extra blank space at the end of the string, it does not ignore it", maybe a `trim()` would do the job?

Hi @matks, thank you for your response.

The issue I try to resolve is not that. In fact the issue is that it already ignores the space. 

If I have a key named "first name" and i'm looking for "first name " (notice the space) the **equal** comparison will return "first name" instead the **like** operator will return 0 row.

It should not return any other result because there is no jolly character, maybe would be a good idea to escape them, what do you think?

I hope I explained well my point, but if i'm wrong please tell me :)

**Review by matthieu-rolland — APPROVED** [review]
@matks I think @agostinofiscale 's fix is right, he uses LIKE without any wildcard. And LIKE is actually more precise than equals, it does a character-by-character comparison, so it fixes the trailing space issue. 

What do you think ?

**Comment by matks** [comment]
> @matks I think @agostinofiscale 's fix is right, he uses LIKE without any wildcard. And LIKE is actually more precise than equals, it does a character-by-character comparison, so it fixes the trailing space issue.
> 
> What do you think ?

It's the first time I encounter a LIKE without wildcard 😄  so today I learn something! Thanks!

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @agostinofiscale,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/16s7ckm_3God0-jAEeemRbyAENfjDsMI9/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @agostinofiscale & @khouloudbelguith

**Comment by agostinofiscale** [comment]
You're welcome 👍🏻

**Comment by bogdanbeniaminb** [comment]
Hello, @matks @agostinofiscale @Progi1984 .

Sorry I have to comment on this, but it actually breaks the translator if you have texts that include "%" in the translation key. For example `%count% products` now also matches `%product_count% products`. Given the fact that Prestashop developer docs actually use such examples of "named parameters" that contain `%`, this is a big issue. `%` will have meaning for the "LIKE" operator.

I'm reporting this because it actually creates production problems for our websites.

**Pull request merged**
