### PR TITLE
CO allow merchant and customer to add < } in a message

### LINKED ISSUE #24901: FO | BO - customer message  with invalid data
#### Describe the bug

In the BO > Orders > Order details page > when we add a customer  message with invalid data, an Update successful alert is displayed but the message is empty.

In the FO Order History > when a customer add `{` `<` an error is display

#### Expected behavior

The user should be able to save any value. (expect html tags)

#### Steps to Reproduce

1. BO ->Go to an order add a message with `<`
2. FO -> Go to an order history add a message with `<`

#### Additional information

* PrestaShop version: 178
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In the BO > Orders > Order details page > when we add a customer message with invalid data, an Update successful alert is displayed but the message is empty. In the FO Order History > when a customer add { < an error is display
| Type?             | bug fix
| Category?         | CO 
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24901
| How to test?      | see issue

Capture d’écran de 2021-06-10 17-57-04
Capture d’écran de 2021-06-10 17-57-19

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24910)

### CODE REVIEW

**Comment by ghost** [comment]
Hello @prestonBot  it's BO and FO :p

**Comment by MatShir** [comment]
@matthieu-rolland well, well doesn't it remind you of something #24867 😄

**Comment by PierreRambaud** [comment]
> Hello @prestonBot it's BO and FO :p

When it's both, it's CO as Core.
Could you please add a better title? I'm afraid I don't understand what it fixes and why when reading it.

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland well, well doesn't it remind you of something #24867 😄

haha yes, seems like we had the same bug everywhere, the fix is the same too :D
LGTM

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @okom3pom !

**Comment by Progi1984** [comment]
Thanks @okom3pom & @florine2623

**Pull request merged**
