### PR TITLE
Do not use hook alias - follow-up

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Follow-up of https://github.com/PrestaShop/ps_mainmenu/pull/56 and https://github.com/PrestaShop/ps_featuredproducts/pull/40
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | - 
| How to test?      | No need QA
| Possible impacts? | PrestaShop/ps_featuredproducts

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26601)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]
Thank you for your PR!

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@SharakPL Hi Could you give a test scenario for checking the behaviro ? May be could you use the `ps_qualityassurance` module ?

**Comment by SharakPL** [comment]
@Progi1984 I'm afraid I couldn't. Never done tests before 😓

**Comment by atomiix** [comment]
@Progi1984 I don't think QA is needed here, however, you should probably add a migration script to unregister the wrong hook and register the good one [like this](https://github.com/PrestaShop/ps_mainmenu/pull/56/files#diff-c580f61b77185794ef129c74ac78f853b5a80f5b35b55b8f602cf6d1c7f40cb6R24-R30).

**Comment by SharakPL** [comment]
@atomiix migration script is in https://github.com/PrestaShop/ps_featuredproducts/pull/40. I don't see any other modules hooked into `categoryUpdate` by default.

**Review by atomiix — APPROVED** [review]

**Comment by atomiix** [comment]
Thanks @SharakPL!

**Pull request merged**
