### PR TITLE
Improve security by randomizing prefix

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Changes to PR 37079, after som consideration, capital letters should not be used.
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install Prestashop
| Sponsor company   | Prestaworks AB

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Comment by matks** [comment]
Hi @Prestaworks your PR title will appear here https://github.com/PrestaShop/PrestaShop/blob/develop/docs/CHANGELOG.txt so could you improve it a little, so it's more easy to guess what it is? 😉

**Comment by matks** [comment]
Thanks!

**Review by kpodemski — APPROVED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello @Prestaworks 

@Hlavtox was right, installation failed on my env.

In your PR there is a merge commit that has to be deleted.

**Comment by Prestaworks** [comment]
> Hello @Prestaworks
> 
> @Hlavtox was right, installation failed on my env.
> 
> In your PR there is a merge commit that has to be deleted.

it should be gone now I think :)

**Comment by kpodemski** [comment]
@Prestaworks there's still a conflict it seems that you have to rebase your PR

**Comment by Prestaworks** [comment]
> @Prestaworks there's still a conflict it seems that you have to rebase your PR

I think it's ok now?

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by florine2623 — DISMISSED** [review]
Hello @Prestaworks ,

The PR works as expected :

Screenshot 2024-10-18 at 10 28 56

Tested multiple times, the randomization of the prefix is correct.

Tests auto are not validated. But I don't think they are related to the PR.
https://github.com/florine2623/testing_pr/actions/runs/11399578750

ping @PrestaShop/qa-automation could you confirm ?

If yes, you can add the label QA ✅ functional testing is validated.
Thanks!

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello @Prestaworks 

I'm sorry, but you will have to change the branch to `9.0.x` to make sure this change is part of version 9.0. 

We created branch 9.0.x this morning and your change should be part of version 9 :)

**Comment by Prestaworks** [comment]
> Hello @Prestaworks
> 
> I'm sorry, but you will have to change the branch to `9.0.x` to make sure this change is part of version 9.0.
> 
> We created branch 9.0.x this morning and your change should be part of version 9 :)

np, I think it should be all good now.

**Comment by Progi1984** [comment]
> Tests auto are not validated. But I don't think they are related to the PR. https://github.com/florine2623/testing_pr/actions/runs/11399578750
> 
> ping @PrestaShop/qa-automation could you confirm ?
> 
> If yes, you can add the label QA ✅ functional testing is validated. Thanks!

@florine2623 It's a QA :heavy_check_mark:

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you @Prestaworks

**Pull request merged**
