### PR TITLE
New Hook after Login form

### PR DESCRIPTION
**Pull request by paeddl**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Adds a new hook below the login form. This is a place where different login-methods (like login by Facebook, login with Amazon etc) can be placed. |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Create a module, register the hook displayAfterLoginForm and create a method hookDisplayAfterLoginForm() to return some test-value |

### CODE REVIEW

**Comment by superGB** [comment]
ping @julienbourdeau

**Comment by julienbourdeau** [comment]
Hi Patrick,

I'll merge this hook but there is a few thing I'd like you to complete:

1. I know there no consistency at all in hook names but we're trying to suffix hook names with after/before. Can you call it something like `displayCustomerLoginFormAfter` instead ?
1. Please add the hook to this file https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/data/xml/hook.xml so it's displayed in the admin module position page. Unless you advise otherwise.
If you choose to do it, you also need to add the upgrade SQL statement https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.0.0.sql
1. Report your change to the startertheme (this is the most important one 😄 ) https://github.com/PrestaShop/StarterTheme/blob/master/templates/customer/authentication.tpl

Thank you!

**Comment by paeddl** [comment]
@julienbourdeau 
Thanks for your comments. I updated this PR with a new commit.
Also please look at the PR for the StarterTheme: https://github.com/PrestaShop/StarterTheme/pull/95

**Comment by firstred** [comment]
Status: Code reviewed

Thank you for your edits. If you'd like you can simply squash the commits into one, just follow this procedure:
- `git rebase -i HEAD~2`
- Edit it in such a way that you have `pick` for the current commit and `squash` for the previous one
- Edit the commit message
- Exit the editor
- Force push: `git push -f`

**Comment by paeddl** [comment]
@firstred Hi could you still merge it as I won't have the possibility to rebase until beginning of September I think as I'm out of the office? Thanks a lot!!

**Comment by firstred** [comment]
Hi @paeddl 
I'm not a PrestaShop employee, I've just sent the status code, trying to abuse @prestonBot haha, but it didn't work

If you'd like, I can change the pull request for you, but I will need you to make me a contributor of your PrestaShop fork.

**Comment by mickaelandrieu** [comment]
> Status: Code reviewed

Will never work :p we'd like to keep some actions with Preston discrete for some weeks ^^

**Comment by Shudrum** [comment]
Thank you!

**Pull request merged**
