### PR TITLE
Optimise shipping cost computation

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | optimize shipping cost computation by skipping useless queries
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | run tests

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8403)

### CODE REVIEW

**Review by tomlev — DISMISSED** [review]

**Comment by tomlev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8403)*

**Comment by eternoendless** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[classes/Cart.php, line 589 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8403#-KwozUcujxhRGoXERbLZ:-KwozUcujxhRGoXERbL_:b-rrn6ap) ([raw file](https://github.com/prestashop/prestashop/blob/46e7a7614febd9a96b0b90d772e9f76baa73af20/classes/Cart.php#L589)):*
> ```PHP
>      * @result array Products
>      */
>     public function getProducts($refresh = false, $id_product = false, $id_country = null, $fullInfos = true)
> ```

Missing Phpdoc for this parameter

---

*[classes/Cart.php, line 1621 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8403#-Kwoz_ewtSVFi9AHWvjQ:-Kwoz_ewtSVFi9AHWvjR:bazdzzr) ([raw file](https://github.com/prestashop/prestashop/blob/46e7a7614febd9a96b0b90d772e9f76baa73af20/classes/Cart.php#L1621)):*
> ```PHP
>         foreach ($gifts as $gift) {
>             if (
>                 (int) $gift['id_product_attribute'] === $id_product_attribute &&
> ```

When breaking conditions into multiple lines, please put the boolean operator at the **start** of the line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8403)*

**Comment by mickaelandrieu** [comment]
Hello @jocel1, would you mind to fix last comments from @eternoendless so I can merge before freeze :+1:

**Comment by jocel1** [comment]
done!

**Review by Quetzacoalt91 — APPROVED** [review]
Let's go for merge. Thank you @jocel1

**Pull request merged**
