### PR TITLE
Add return to Tools::deleteFile() method

### PR DESCRIPTION
**Pull request by Arman-Hosseini**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Adds the return statement in Tools::deleteFile() method.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18098)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matks** [comment]
I think this would be considered a BC break. Can you confirm @eternoendless ?

**Comment by Arman-Hosseini** [comment]
@matks It returns no value and is void. As a result, it does not break backward compatibility.

**Comment by matks** [comment]
> @matks It returns no value and is void. As a result, it does not break backward compatibility.

## Before

```
$result = Tools::deleteFile($file);
// $result is null
```

## After

```
$result = Tools::deleteFile($file);
// $result is false or true
```

If someone's code rely on the void result* it will break his code.

*Example

```
$result = Tools::deleteFile($file);

id (null !== $result) {
    // do something
}
```
The code above works based on a mistake (= developer thinks `Tools::deleteFile()` returns something) but works.

If we follow SemVer this is a BC break, even though it's a code improvement.

As OSS maintainers, "we have to live with our mistakes until the major" 😢

## How to avoid breaking SemVer

### Use flag

Use flag to return bool, so only people with knowledge of the flag can use it

```
public static function deleteFile($file, $exclude_files = [], $returnResultAsBool = false)
```

### Create new, better function

```
public static function deleteFileV2($file, $exclude_files = []) : bool
```

**Comment by Arman-Hosseini** [comment]
Why should a developer check it with a null/non-null value? When its value is always null.
Whenever I want to use a method, I first refer to its documentation. Any developer should check the documentation, even if it's a novice.
When you don't know how a method works and what kind of data it returns, then how do you want to use it?

**Comment by matthieu-rolland** [comment]
> Why should a developer check it with a null/non-null value? When its value is always null.
> Whenever I want to use a method, I first refer to its documentation. Any developer should check the documentation, even if it's a novice.
> When you don't know how a method works and what kind of data it returns, then how do you want to use it?

Yes we know it's bad...  Your modification is cleaner but we can't implement it:

@matks is right, changing what a function returns in a given circumstance is a breaking change. For example if a module expects this method to return nothing/null all the time, then it will stop working when the function will return true.  

We can only do breaking changes on major versions, this is not a new major version.

**Comment by PierreRambaud** [comment]
It's more a bug than a BC, otherwise all changes are BC because the behavior isn't the same :thinking: 

And here @matks you're wrong it's an improvement :sweat_smile:

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
No need QA. @eternoendless confirmed us, it's not a BC because the return was void :)
Thanks @Arman-Hosseini

**Comment by matks** [comment]
> No need QA. @eternoendless confirmed us, it's not a BC because the return was void :)

I learned something today 😊thanks !

Sorry for confusion @Arman-Hosseini 🙏

**Pull request merged**
