### PR TITLE
Bump version to 8.1.0 & Github Actions : Removed Skip Conditions

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Bump version to 8.1.0
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A

### CODE REVIEW

**Comment by Progi1984** [comment]
@jolelievre You have right. It works now.

**Comment by kpodemski** [comment]
@Progi1984 are you sure about these changes from .yml files? this will cause problems with dependabot again

**Comment by Progi1984** [comment]
@kpodemski Yes i'm sure. It locks PR because it skips actions which are required. I will work on it to find a better solution.

**Comment by kpodemski** [comment]
@Progi1984 but you could just use a different title, right?

**Comment by Progi1984** [comment]
@kpodemski Fixed.

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @Progi1984

**Pull request merged**
