### PR TITLE
Fix child theme download

### LINKED ISSUE #30134: BO - Cannot download the child_classic theme from the Advanced customization page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error is displayed when downloading the child_classic.zip theme
Related to https://github.com/PrestaShop/PrestaShop/pull/29382

### Expected behavior

the theme child_classic.zip is well downloaded

### Steps to reproduce

1. Go to BO > Design > Theme & Logo page > Advanced Customization tab
2. Click on "Download theme"
3. See error => redirection to this link `shop.com/PrestaShop//themes/child_classic.zip` 

image

It is detected by automatic tests also https://github.com/khouloudbelguith/testing_pr/actions/runs/3336075707/jobs/5521872535

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1, 8.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix child theme download
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30134
| Related PRs       | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @khouloudbelguith

**Review by PrestaEdit — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]
LGTM

**Review by lartist — APPROVED** [review]

**Comment by MatShir** [comment]
It looks like a regression. I think you can target 8.0.x

**Comment by PrestaEdit** [comment]
No ; it's due a change make this morning : https://github.com/PrestaShop/PrestaShop/pull/29382

**Review by FabienPapet — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @Hlavtox ! 

The issue is solved :+1: 

- I run the automated tests > **OK**

- I checked those steps: 

1. Go to BO > Design > Theme & Logo page > Advanced Customization tab
2. Click on "Download theme"
3. The child_classic.zip file is well downloaded.


image

Thank you ! :rocket:

**Comment by kpodemski** [comment]
Thanks @Hlavtox

**Comment by dzhigit** [comment]
Access to the folder themes is needed. 666

**Pull request merged**
