### PR TITLE
Update symfony-property-access to 6.3.0

### LINKED ISSUE #32648: symfony/property-access
As a developer I want to have framework up2date so : 
- I have a secure plateform
- New features 
- more performant prlateform in some case

## Description 

Upgrade [symfony/property-access](https://packagist.org/packages/symfony/property-access) to,  at least, 6.2.8 version.

See also : 
[frameworks - PHP dependancies](https://www.notion.so/prestashopcorp/Les-cons-quence-en-fonction-des-versions-de-PHP-support-es-5fa9b7e6654a495cbcbbf86cb82fee91)
and 
[dependencies](https://miro.com/app/board/uXjVMMFa4_Y=/?share_link_id=447161604159)

## AT

PS should work (ISO) with the 6.2.8 version of symfony/property-access

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update symfony-property-access to 6.3.0
| Type?             | improvement
| Category?         |CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green and auto-tests https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5219575827 green
| Fixed ticket?     | Fixes #32648
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Comment by M0rgan01** [comment]
Tests: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5219575827

**Review by nicosomb — DISMISSED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
LGTM but autom tests are failing, not sure it's related to your PR though :thinking:

**Comment by lartist** [comment]
Sorry @M0rgan01, I wasn't clear enough when we discussed about upgrading librairies. This library should evolve at the same rythme than the other symfony libraries (currently 5.4).
We can close it.

**Review by FabienPapet — CHANGES_REQUESTED** [review]
Agree with @lartist here

**Pull request closed without merging**
