### PR TITLE
Fix PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined

### PR DESCRIPTION
**Pull request by mervick**

### CODE REVIEW

**Comment by nicosomb** [comment]
@mervick Thank you for your pull request. Could you please edit it to fill the template?

**Comment by Hlavtox** [comment]
This is weird... This constant should probably avoid loading configuration in install process. So it should not be defined and shoudn't throw this error in the first place.

If this warning is thrown during every install ➡️ This call is not working this whole time ➡️ We can just remove this constant.

Ping @kpodemski @ShaiMagal

**Comment by ShaiMagal** [comment]
@Hlavtox I never had this error before... I don't know. Maybe author (@mervick) should give us more informations...? :)

**Comment by mervick** [comment]
I have this error always in logs on installation process

**Comment by mervick** [comment]
Screenshot from 2023-11-07 09-47-41

**Comment by nicosomb** [comment]
Which PHP version?

**Comment by mervick** [comment]
```
PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.14, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by ShaiMagal** [comment]
@mervick This isn't error, this is warning. Only to be clear, but of course, nothing changed! :)

I confirm this, I have same warnings in php log after installation, but i never checked logs while installing PS.... So I never noticed this before.

[07-Nov-2023 11:18:19 Europe/Prague] PHP Warning:  Constant _PS_DO_NOT_LOAD_CONFIGURATION_ already defined in /XXX/install/controllers/http/smarty_compile.php on line 26

_PS_DO_NOT_LOAD_CONFIGURATION_ is defined in defines.inc.php
```
if (!defined('_PS_DO_NOT_LOAD_CONFIGURATION_')) {
    define('_PS_DO_NOT_LOAD_CONFIGURATION_', false);
}

```

This commit looks legit, but to be clear:
**I don't know what the hell is real example of usage "_PS_DO_NOT_LOAD_CONFIGURATION_"? Anyone knows?**

**Comment by matks** [comment]
I have no idea why it was implemented and why it's there. I would suggest we remove it 😄 if everybody here agrees.

@PululuK by any chance do you know what someone would want `Configuration::get()` to always return `false` ? You refactored a bit this part so maybe you came accross it?

**Review by tleon — COMMENTED** [review]
I agree that if it does not seemed to be used, we should remove it. Better get rid of it than keeping some dead constant. CI will tell us if this removal is a problem I guess.

**Comment by ShaiMagal** [comment]
Yep, remove it completely, I think, it's something obsolete...

**Review by Hlavtox — DISMISSED** [review]

**Comment by ShaiMagal** [comment]
Author isn't responding longer time...
I edited code to make CS Fixer happy.

**Comment by ShaiMagal** [comment]
UI tests are failing. I don't know why. Can anyone identify why? I am not familiar with UI tests.

**Comment by M0rgan01** [comment]
@ShaiMagal All PRs have a problem with sanity. We try to understand why

**Review by matthieu-rolland — COMMENTED** [review]
I restarted failed ui tests from the CI

**Review by M0rgan01 — COMMENTED** [review]
We need to rebase. After the tests will be green

**Comment by Hlavtox** [comment]
@M0rgan01 Morgan, can you rebase and squash the commits?

**Comment by Hlavtox** [comment]
Constant has been removed. :-)

**Pull request closed without merging**
