### PR TITLE
Added support for PostgreSQL

### LINKED ISSUE #13512: Please add support for PostgreSQL
I would like to use PostgreSQL instead of MySQL
PostgreSQL seems to behave better on heavy load.

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Added support for PostgreSQL
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle:  & Nightly is :green_circle: 
| Fixed ticket?     | Fixes #13512
| Related PRs       | N/A
| Sponsor company   | lefevre.dev

### CODE REVIEW

**Comment by Progi1984** [comment]
Sorry. I will contribute only on UI tests now.

**Comment by EdwinBetanc0urt** [comment]
This was a good start, so why was it shut down? I understand that this proposal did not provide complete support, but it was a start.

**Comment by Progi1984** [comment]
@EdwinBetanc0urt Funding, like often

**Comment by EdwinBetanc0urt** [comment]
Hi @Progi1984 it would be good to mix or integrate these types of changes. Although they do not provide full support, the community can provide partial support for Postgres and include a disclaimer indicating that support is partial and not recommended for production until it is stable.

**Pull request closed without merging**
