### PR TITLE
The date field can also be required in HTML

### PR DESCRIPTION
**Pull request by juliendombret**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The date field can also be required in HTML.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19545)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
Hi @juliendombret and thanks for your contribution.
Could you please next time provide us a title, description and tell us how to test :)

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
I restarted failing travis ci tests

**Review by NeOMakinG — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Unfortunately, I don't know how to test it and @juliendombret don't provide us a way to test it :)

**Comment by Progi1984** [comment]
@juliendombret  Thank you for your contribution. :hugs: 

Could you give us a scenario which permits to test the bug before and after this PR ? That permits to send your PR in QA.

Thanks :+1:

**Comment by PierreRambaud** [comment]
Hi @juliendombret  ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
