### PR TITLE
Orders amount currency fixed

### PR DESCRIPTION
**Pull request by Casper-O**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | If a shop is multi-currency and customer pays in an other than the default, the valid orders amount is displaying the amount with default currency ISO code. |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7738 |
| How to test? | Customer pays 100 EURO, default store currency is DKK = displaying customers valid order is worth 100 DKK, instead of 100 EURO - since stores can have many currencies i figured out it was best to convert the orders back to the default currency instead of guessing the most valid currency for each customer |

### CODE REVIEW

**Comment by Casper-O** [comment]
@xBorderie sorry to ask, but what do Estimate: S means?

**Comment by Casper-O** [comment]
Okay thanks for the explanation, it makes good sense :)

**Comment by Casper-O** [comment]
@Shudrum can i ask why the title was changed? As far i know the Title followed the guidelines?

Also was it you that added the QA table? This relates to the BO not to FO

**Comment by Casper-O** [comment]
Btw - this issue also related to 1.6.1.X - should also make a PR to that branch?

**Comment by maximebiloe** [comment]
Thank you @Casper-O 
It has been merged in 1.6, so let's merge this one too

**Pull request merged**
