### PR TITLE
[*] CORE : Use always the correct class_index.php file and cache directory

### PR DESCRIPTION
**Pull request by dkarvounaris**
Ensures to create the class_index.php always in _PHP_CACHE_DIR_ and hides internals by offering the method getClassIndexFilepath() to receive the full path and filename from outside the class.
Deprecates constant INDEX_FILE. Backwards compatibility for INDEX_FILE.

### CODE REVIEW

**Comment by dkarvounaris** [comment]
This is a replacement for https://github.com/PrestaShop/PrestaShop/pull/2699

**Comment by jeromenadaud** [comment]
Hi,

do you think it's very necessary to make getClassIndexFilepath static ?
It's very difficult for use to change static variable in unit test case, and this function is called one time at start and only if you regenerate a class_index.

Also, can you explain all the code between lines 172 and 179 ?

Best regards

**Comment by dkarvounaris** [comment]
Ok, the problem the 172-179 solves is regarded to what you asked, keeping INDEX_FILE as deprecated instead of removing it and asking other code to be updated. Nothing in the CORE and standard modules afaik depends on it, I don't know about 3rd party modules. But if some other code is still using INDEX_FILE, it will try to access a file that isn't getting updated on changes if it existed before _PS_CACHE_DIR_ was copied to a new location or that might even not exist. So this updates once this location too, in case some other code depends on INDEX_FILE. However it seems unlikely to me and I would rather opt to remove INDEX_FILE and 172-179 and ask that one module that might use it to be updated. But if INDEX_FILE should be just deprecated, a compatibility code should be kept until removal of INDEX_FILE to not break some 3rd party module and this is 172-179 for.

**Comment by dkarvounaris** [comment]
About the static: My thought was, that INDEX_FILE has been public and you thought that some module might use it. In that case, getClassIndexFilepath should be also public. As that, it makes sense to have it accessible without initiating an instance, same as INDEX_FILE was before too, as it's not depending on an instance either. Does this method really need a test, I don't see how it could fail on itself. As a test should test one thing, this seems to me a candidate for the "what not to test" category? 
I guess it could be changed though, as PrestashopAutoload is already initiated extremely early, it shouldn't have any sideeffect on anything that might call it in this case.

**Comment by dkarvounaris** [comment]
Or I had rather make it a private method and disallow any external module to depend on that value alltogether. It exposes internals of the implementation as INDEX_FILE already did and makes any changes difficult. Would solve two problems.

**Pull request closed without merging**
