### PR TITLE
[-] FO: Fix minifyCSS() for Quoted URLs in Media.php and replaceByAbsoluteURL() in Tools.php

### PR DESCRIPTION
**Pull request by Xperos**
Fixes the URL matching in minifyCSS() and only calls replaceByAbsoluteURL() if protocol is not data:, http: or https:

replaceByAbsoluteURL() fixed to handle absolute addressing, i.e. beginning with /

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Can you please give an example of the failing case with current code ?

I tried with ```background: url(//www.google.fr/images/nav_logo195.png) ``` but could nto reproduce the issue.

Thank you. Regards

**Comment by Xperos** [comment]
Hi,

The particular use case I'm am looking at is the use of quotes i.e. your
example changed to:

background: url("//www.google.fr/images/nav_logo195.png")

with Smart cache for CSS and Media Servers enabled.

background: url("//www.google.fr/images/nav_logo195.png") fails. Looking at
the compresses css file (you may need to wget the file and search in a text
editor) you find the following:

background:url("
http://ms1.example.com/themes/realty/css///www.google.fr/images/nav_logo195.png
")

http://ms1.example.com being the media server.


With media servers switched off but CSS compression still enabled it also
fails and you get:

background:url("
http://realty.example.com/themes/realty/css///www.google.fr/images/nav_logo195.png
")

http://realty.example.com is the domain

Without caching enabled it does work and you get:

background: url("//www.google.fr/images/nav_logo195.png")


The current regex does work but is inefficient and makes unnecessary calls
to replaceByAbsoluteURL().

My regex is more efficient and does not make unnecessary calls
to replaceByAbsoluteURL()

HOWEVER I was not aware that // was valid syntax, I thought that it should
include the protocol i.e. http:// or https:// but it seams to work fine
without the protocol specified, I assume it defaults to http://

You are never too old to learn something new every day.

With my new knowledge learnt today my regex needs to be modified to allow
for //

Therefor the new fix for Media.php line 180 should be:

$css_content =
preg_replace_callback('#(url\((?![\'"]?(?:data:|//|https?:))(?:\'|")?)([^\)\'"]*)(?=[\'"]?\))#s',
array('Tools', 'replaceByAbsoluteURL'), $css_content, $limit);


Unfortunately I'm no expert at GitHub and have no idea how to update the
pull request, is it necessary to create a new request?

I hope you agree with my findings and can apply the above change to the
pull request before committing.

Kind regards

**Comment by gRoussac** [comment]
Hi,

Thank you for your answer however i will need further tets because 

url("//www.google.fr/images/nav_logo195.png") is working in my test and in the compressed output file. Are you sure to test on a up to date git version ?

Regards

**Comment by gRoussac** [comment]
Hi,

// will default to current page protocol i believe.

Ok I will test further with all CCC options.

You just need to commit on the same branch to fix your PR.

However on replaceByAbsoluteURL I will change it to ``	$tmp = dirname($current_css_file).$sep.ltrim($matches[2], $sep); ``` becasue I do not really agree on checking first letter of matches[2]

Regards

**Comment by Xperos** [comment]
Hi

I don't believe that $tmp = dirname($current_css_file).$sep.ltrim($matches[2], $sep); will work.

My coding is ONLY applying dirname($current_css_file) IF the url does not start with /

It is not a case of just stripping the leading /

This is to handle cases where the coder has used an absolute site address i.e:

url("/img/logo_stores.gif")

If you prefix the dirname($current_css_file) the url will be corrupted.

Regards

**Comment by gRoussac** [comment]
Hi,

I mixed things with url("./img/logo_stores.gif").

Thank you for your explanation and help.

https://github.com/PrestaShop/PrestaShop/commit/c0052ceca7979c3f6fedb45a27a323e91d2ebf7d

Tell me if this is ok for you.

Regards

**Comment by gRoussac** [comment]
Hi agian,

I started to implement a test on minifyCSS. I will fullfill it with others rules of the method asap.

https://github.com/PrestaShop/PrestaShop/pull/2899/files

tell me if I forgot a case in isCssInputsProvider.

Thank you again.

Regards

**Comment by Xperos** [comment]
Hi

For completeness you may choose to add tests for all cases enclosed in single and double quotes. i.e. expand data and https tests as well as dot, dot dot and /

Certainly you do not appear to have a test case for relative and absolute own domain addressing enclosed in quotes.

Regards

**Comment by gRoussac** [comment]
Ok thank you for your feedback.

Regards

**Pull request closed without merging**
