### PR TITLE
Merge 8.0.x into 8.1.x

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x 
| Description?      | Merge 8.0.x into 8.1.x
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and auto tests 🟢 
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by nicosomb** [comment]
@matks php cs is failing 🤔

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/pull/31575 merged too quickly i don't the way ? A new PR ?

**Comment by nicosomb** [comment]
no new PR needed, it seems to be already fixed

@matks you need to rebase your 8.0 branch

**Comment by matks** [comment]
> no new PR needed, it seems to be already fixed
> 
> @matks you need to rebase your 8.0 branch

Merge PRs cannot be rebased 😭 that's the sad stuff

Merge PRs need to be re-built from the beginning (as far as I know) so I close this one

**Pull request closed without merging**
