### PR TITLE
Fix special prices for product

### PR DESCRIPTION
**Pull request by MounirBoukhris**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Product Price with Specific is wrong
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8919 & http://forge.prestashop.com/browse/PSCSX-9102 & http://forge.prestashop.com/browse/PSCSX-9095 & http://forge.prestashop.com/browse/PSCSX-8756
| How to test?  | Add different specific prices for a product, some with fixed price, some with amount reduction or percent reduction, and with different quantities.

### CODE REVIEW

**Comment by sooroos** [comment]
Hi @MounirBoukhris  . i have just tested #8099 on P.S. 1.6.1.14  and it is still wrong.
It updates the base price accordingly but i apply no discount (i change only the base price affter a certain qty) and still on the product page i got displayed a reduction with "0,00€" and the previous price (which is also wrong while it is the new price)

Moreover in the "Volume discounts" table i have displayed only the qty from which the new price is changed and there is no info about the new base price, only reduction, again with 0.00€

Regards

**Comment by MounirBoukhris** [comment]
Hi @sooroos,
Thanks for reporting the issue.
I added the necessary modifications to correct this problem.
Best regards,
Mounir

**Comment by marionf** [comment]
Hello @MounirBoukhris 

The price displayed in the table doesn't look good
pr8099-3
pr8099-2

**Comment by MounirBoukhris** [comment]
Hello @marionf 
Thanks for your feedback.
I will see how to fix it.

Best regards,
Mounir

**Comment by MounirBoukhris** [comment]
Hello @marionf
could you please test again.

Best regards,
Mounir

**Comment by marionf** [comment]
Hello @MounirBoukhris 

I tested and the prices in the table are not good.
pr8099

pr8099 2

**Comment by MounirBoukhris** [comment]
Hello @marionf 
The last column in the "Volume discounts" table displays the product prices without discount to indicate to the customer that the base price or the fixed price is used for each quantity

Best regards,
Mounir

**Comment by marionf** [comment]
Hello @MounirBoukhris 

Can you move the column price in 2nd position in your tab ?
Can you find also a string instead of "price" like "base price" to be more clear ?

Thanks !

**Comment by MounirBoukhris** [comment]
Hello @marionf 
I added in this PR the necessary modifications.
Can you please check them.

Best regards,
Mounir

**Comment by aleeks** [comment]
@maximebiloe this PR can be done in 1.6.1.x ? because of theme changes ?

**Comment by maximebiloe** [comment]
Yes @aleeks, too much in the theme. It will break the retrocompatibility 😕

**Comment by aleeks** [comment]
@maximebiloe  yes or no ? :smiley_cat:

**Comment by maximebiloe** [comment]
As there are too much changes in the theme, we can't merge this to prevent breaking other themes. I close this PR, but the fix remains valid if someone wants to apply it manually.

Regards

**Comment by variamus** [comment]
Hello @MounirBoukhris , I'm new to all of this and I don't seem to succeed to apply your fix. As soon as I modify the product.php by removing the red lines and adding green lines from your changed files tab I break all the products.
Would you mind kindly helping me ?

**Comment by DavidEschmeyer** [comment]
this fix is not working if you hit shift-f5 to force the js fetch, the page shows NaN for price

**Pull request closed without merging**
