### PR TITLE
Display an error while the file format does not match the allowed formats

### LINKED ISSUE #28875: BO - Products V1 - Error 500 when we add ad invalid image to a product
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error 500  is displayed when adding an invalid image to a product
image

### Expected behavior

We should have an alert
image

### Steps to reproduce

1. Go to BO > Catalog > Products V1
2. Edit a product > Add an invalid image for example .svg, .ico
3. See error: error 500 in the console

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Regarding the related issue, the error is not shown. With this, if your upload a .svg file (as example) you will see an error.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28875.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by sLorenzini — COMMENTED** [review]
hello @PrestaEdit,

Thank you for this PR.

Tested on 8.0.X with PHP 7.3 & 8.1 version

Tested with two types of image:

1. .svg 
- on new product, the error message is well displayed ✅

https://user-images.githubusercontent.com/2854834/179548655-eccdef2e-1d6d-48e7-ad10-a78d024d3d45.mp4

- by editing a product, the error message is well displayed ✅

https://user-images.githubusercontent.com/2854834/179548680-11d2312c-64d2-4f63-bb09-a1bac90f8aa2.mp4

2. .ico 
- on new product and by editing product, the error message is not displayed and we can save the product. Error 500 on the console. The image can't be shown on FO ❌ 

https://user-images.githubusercontent.com/2854834/179548724-753c5c50-3518-4530-820b-ec7b3602b6df.mp4

In the PHP file, the .ico images are not authorized.

Could you check please 🙏?

Thanks

**Comment by PrestaEdit** [comment]
This is what I have with a .ico : 
Capture d’écran 2022-07-18 à 18 44 35

Can I ask you to provide the used file there ?

**Review by sLorenzini — APPROVED** [review]
Hello @PrestaEdit,

I can't sent you the .ico (Github not allows this file type 😄). It was the .ico from PrestaShop website.
This morning, I retried with another .ico (an image generated to .ico) and I've got the same message as you:

Capture d’écran 2022-07-19 à 10 59 45

That's ok for me.

QA approved ✅ 

Thank you

**Comment by PrestaEdit** [comment]
I've take it to make a test and it's what I was suppose is it : the favicon.ico was a favicon.png image rename and use as it.
It's not a real .ico file and so the mimetype is image/png (and no error will be thrown).

There is surely an extra check to manage the extension of the file, here. :-/

**Comment by kpodemski** [comment]
@Julievrz could you take a look at the wording? :)

**Comment by kpodemski** [comment]
Thanks @PrestaEdit @sLorenzini

**Pull request merged**
