### PR TITLE
Cast id_cart to int to keep it in the SQL query

### PR DESCRIPTION
**Pull request by roja45**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Added cast to int for id_cart as with id_customer.  When function is called with id_cart null, id_cart is dropped from the query and it returns all specific prices assigned to carts.  These can be seen in the BO in the plist of products. Previously, and as with id_customer, the minimum was to have 'AND id_cart IN (0, 0')' in hte final query. |
| Type? | bug fix |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7849 |
| How to test? | Create a new specific price, assigned to a specific id_cart, you will be able to see it in the back office as the final price for that product. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

…ys being included in query and preventing specific prices assigned to carts being returned when calling method with id_cart of null: http://forge.prestashop.com/browse/PSCSX-7849

### CODE REVIEW

**Comment by roja45** [comment]
This PR replaces one created erroneously against develop branch, and changes the fix.  Result is the same. (#5545 on develop branch)

**Comment by Shudrum** [comment]
Thank you 👍

**Comment by erouvier29** [comment]
@roja45 +1
I found the same issue, and was about to PR the same fix.

**Comment by roja45** [comment]
Will this fix ever be included in a 1.6 point release, approaching 12 months since I first encountered this bug?

**Comment by xBorderie** [comment]
Thank you for updating your code, @roja45 !

**Comment by erouvier29** [comment]
Is this actually the reason why the merge was blocked ???

**Comment by xBorderie** [comment]
@erouvier29 I think it was more forgotten than blocked, sadly :/

**Comment by maximebiloe** [comment]
Thank you @roja45

**Pull request merged**
