### PR TITLE
Replace Noto Sans font with Vazir font for Farsi in Classic theme

### PR DESCRIPTION
**Pull request by mehrshadz**
Replace the Noto Sans font with Vazir font (v18.0.0) which is a better choice for Farsi typeface + copyright (Apache v2)

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Replace the Noto Sans font with Vazir font (v18.0.0) which is a better choice for Farsi typeface + copyright (Apache v2)
| Type?         | improvement
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://trello.com/c/FI0ri5Ev/1-fonts
| How to test?  | Generate RTL stylesheet from Design -> Theme & Logo menu. Please remove "theme_rtl.css" file from "themes/classic/assets/css" path if existing before generating new RTL stylesheet.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8835)

### CODE REVIEW

**Review by eternoendless — CHANGES_REQUESTED** [review]
Same comments as https://github.com/PrestaShop/PrestaShop/pull/8837#pullrequestreview-103435605

**Review by mehrshadz — COMMENTED** [review]
CDN urls changed and copyrights removed

**Review by eternoendless — APPROVED** [review]

**Comment by mehrshadz** [comment]
@eternoendless 
Hi Pablo,

How long does it take to pass the "report on StarterTheme" level? Will it be merged before 1.7.3.2 is released?

Thanks

**Comment by mickaelandrieu** [comment]
> How long does it take to pass the "report on StarterTheme" level?

This means someone needs to report the modification on the Starter Theme: if you can do it, it will help a lot :)

Mickaël

**Comment by mehrshadz** [comment]
@eternoendless 

Thanks @mickaelandrieu 
But actually this PR is not really related to StarterTheme since it's generated after installation. If it's necessary I can make a copy of .rtlfix file inside the StarterTheme too.

Also this PR is a temporary solution for fixing the font issue. I've sent our final solution to Pablo and waiting for his review on that so we can replace that method with this temporary one for the next releases.

Regards,

**Comment by mickaelandrieu** [comment]
Hi @mehrshadz, thanks for the information :)

As @eternoendless validated this contribution and as it's QA-approved, I don't see why this shouldn't be merged.

LGTM,

thanks again @mehrshadz and sorry for the delay :)

**Pull request merged**
