### PR TITLE
Happy new year 2018

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Updated licenses with `php bin/console prestashop:licenses:update`
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | Nothing to test, only file comments should be updated.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8649)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 How about just remove 2017 and put "2007-present" instead?

**Comment by Quetzacoalt91** [comment]
I don't know, I also saw this suggestion on Symfony, but it seems it was reverted. https://github.com/symfony/symfony/commit/07a7f560cdfb7d0b6984b03231b1280f8420d41e#diff-9879d6db96fd29134fc802214163b95a :)

**Comment by mickaelandrieu** [comment]
It's not because @fabpot did something wrong that we have to do the same :) => https://github.com/symfony/symfony/pull/25646

I see no reason to update these files every year, let's update them the day we will stop to maintain it instead :)

**Comment by Quetzacoalt91** [comment]
Even if this done by someone else (using another license btw), I can't confirm if the header is still valid with that suggestion. :/

**Comment by eternoendless** [comment]
Internet people [suggest keeping the year updated](https://opensource.stackexchange.com/questions/4885/copyright-unitl-the-present-year-in-bsd-license), so I think we should keep doing that to be safe.

**Comment by fabpot** [comment]
@mickaelandrieu Thanks for being wrong. I did some research before settling on what we are doing. Apparently, you didn't. Too bad.

**Comment by mickaelandrieu** [comment]
@fabpot except if you assume I'm in your head, you never have explained your reasons. Doing this update every year have *no gain* from both maintenance or legal point of views: period. Feel free to enlight my brain with your conclusions at any time !

**Pull request closed without merging**
