### PR TITLE
Fix language dropdown when resizing window  in attribute creation page

### LINKED ISSUE #26252: BO - the language dropdown is not well displayed when resizing the window
#### Describe the bug

when we resize the window the language dropdown is not well displayed

#### Expected behavior

resize the window the language dropdown should be well displayed

#### Steps to Reproduce

1. Go to catalog >Attributes & Features > Add new attribute > resize window (the language dropdown is not ok)
2. Go to shop parameters> customer settibngs> Titles> add new social title

**Screenshots**
image
image

The issue is not present in 1.7.8.0

#### Additional information

* PrestaShop version: develop/1.7.8.x
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by marwachelly**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | when we resize the window the language dropdown is not well displayed
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26252
| How to test?      | resize the window the language dropdown should be well displayed
| Possible impacts? | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26328)

### CODE REVIEW

**Review by sowbiba — APPROVED** [review]
Thanks @marwachelly 🚀

**Review by matthieu-rolland — COMMENTED** [review]
LGTM ! 
Let's wait for the CI to finish before sending in QA

**Review by NeOMakinG — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @marwachelly,

It is ok :heavy_check_mark: 
I checked the language dropdown on those pages:
1. Add a new attribute / Add new value
3. Add a new feature / Add new value
4. Customer Service page
5. Marchandise return page
6. Add a new carrier page
7. Add new Group customer
8. Add a new title
9. Search page

**Without PR** 
image

**With PR**
image


Thanks!


Thanks!

**Comment by matks** [comment]
Congratulations @marwachelly for this first Pull Request merged!

No need to add `Hacktoberfest` label I think 😉  the repository has enabled hacktoberfest globally

EDIT: this is not your 1st PR, my bad. It's just prestonbot who said that.

**Pull request merged**
