### PR TITLE
Filter empty values for modulesFromHooks

### LINKED ISSUE #31274: Issues when upgrading a module used as external source
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we try to update a module implementing the hook `actionListModules`, if there is any change in the service defintions, the upgrade fails

For example, ps_mbo is an external source module, it registers `actionListModules`. That hook returns the fresh data about modules from external APIs
During the upgrade process, we are call ```$this->moduleRepository->getModule($name);```
This call will request external sources to get fresh data.
In the case it's the module MBO itself which is updating, any changes on service definitions of the new version will lead to a failure

Another issue during module upgrade happens when the module listens to event `ModuleManagementEvent::UPGRADE`. The listeners and subcribers are stored on Sf Container build as Closure (see RegisterListenerPass) and until the process ends. So whatever is done in the upgrade process (cache clean, ...) the subscriber will remain the same. If we use some module services in that subscriber and they have changed, ClassLoader will yell because service definitons changed.<br>To help module developpers to avoid this case, we add a "JS hook" to help modules to execute tasks after a module import

### Expected behavior

_No response_

### Steps to reproduce

1 - Install mbo 4.0.1
2 - Try to upgrade to 4.3.0 using the button "Install a module"
3 - You'll have an error saying that service `AddonsUser` changed defintion

OR

1 - Install v1.0.0 of the example module using the button "Install a module" [prestashopexamplemodule_1.0.0.zip](https://github.com/PrestaShop/PrestaShop/files/10814931/prestashopexamplemodule_1.0.0.zip)
2 - Install v1.0.1 of the example module using the button "Install a module" [prestashopexamplemodule_1.0.1.zip](https://github.com/PrestaShop/PrestaShop/files/10814943/prestashopexamplemodule_1.0.1.zip) => this will perform an upgrade 

==> You'll have an erreur about array_merge with a value that is not an array

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Filter empty values of modules infos retrieved by external sources
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | -
| Fixed ticket?     | Partially Fixes #31274

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
@sowbiba and @PrestaShop/qa-team , how should we proceed here ?

**Comment by sowbiba** [comment]
I just added a 2nd scenario to the issue with an example module 😉

**Comment by paulnoelcholot** [comment]
Hello @sowbiba 

I have tested your PR and it's OK for me :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @sowbiba and @paulnoelcholot !

**Pull request merged**
