### PR TITLE
Use service discovery for form types

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Use service discovery instead of adding every form type by hand.
| Type?             |  improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢  and automated tests

### CODE REVIEW

**Review by M0rgan01 — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]
LGTM, thanks @FabienPapet, it seems pretty! 😍

**Review by M0rgan01 — DISMISSED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
Do we need some documentation about this or not?

**Comment by FabienPapet** [comment]
I think no because it is only internal feature

**Comment by nicosomb** [comment]
sure, but for developers?

**Comment by FabienPapet** [comment]
As discussed with @nicosomb nothing to document, here as it just syntax, but there have been some new reusables form types that may need documentation.

- GroupType
- GenderType
- CurrencyChoiceType

I will put the label on those.

**Review by boherm — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @FabienPapet 

Tests auto is :heavy_check_mark: and CI is :green_circle: 
https://github.com/hibatallahAouadni/testing_pr/actions/runs/5153573045/jobs/9282278345
(the only failed test is BO:header cause it's a regression on develop branch).
LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by nicosomb** [comment]
Thank you @FabienPapet !

**Pull request merged**
