### PR TITLE
Bump `prestashop/ps_cashondelivery` to 2.0.1

### LINKED ISSUE #27375: FO - Order confirmation page - ps_cashondelivery is NOK
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The ps_cashondelivery module is NOK with the develop branch
image

https://watch.screencastify.com/v/lmgJAl2A4YmcewAyTMGK

### Expected behavior

_No response_

### Steps to reproduce

1. Go to FO > create an order using ps_cashondelivery payment
2. see error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

ps_cashondelivery

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Bump `prestashop/ps_cashondelivery` to 2.0.1
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27375
| How to test?      | N/A

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by matks — DISMISSED** [review]
Re-run CI

**Comment by Progi1984** [comment]
This PR is blocked by PrestaShop/ps_cashondelivery#45

**Comment by MatShir** [comment]
Thanks for the fix. The PR fixes a regression from the 8.0.X. Could you change the PR of branch ? 
The develop is now for the 8.1 version ;)

**Comment by Progi1984** [comment]
@MatShir :heavy_check_mark: for `8.0.x`.

**Review by ghost — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team do you want to run automated tests on this one?

**Comment by AureRita** [comment]
Hi @Progi1984 

Thank you for your PR, Strangely, when I Tested your PR, it change something with the password policy when a customers want to change his password, as you can see : 

https://user-images.githubusercontent.com/100699445/182152800-0c8d9490-7b50-45bd-ba97-8a1e59b48e31.mp4

FYI : the first one is with your PR and the second is with version 8.0.x

**Comment by ghost** [comment]
Hello @AureRita 

The how to test is not filled here

You have to check if the version of the module changes.

The other bugs are not from the PR

**Comment by AureRita** [comment]
Hi @okom3pom ,

Currently, I tested this issue with and without this PR, I only have this issue with this PR, I have to check if this PR will not make issue like this one. Moreover, this issue has been detected by the automated test so I have to mention it. Except this issue, the PR change the version of cashondelivery as we can see on this photo : 
image

**Review by AureRita — APPROVED** [review]
After checking with the nightly reporting, I see that this problem was recently add on 8.0.0, so without this issue, your PR works as we want, so QA heavy_check_mark

**Review by matthieu-rolland — COMMENTED** [review]
thank you @Progi1984 and @AureRita !

**Pull request merged**
