### PR TITLE
// small fix and documentation of a ambiguity around 'price display m…

### PR DESCRIPTION
**Pull request by zapalm**
…ethod' functions

### CODE REVIEW

**Comment by zapalm** [comment]
it is not serious for waiting a review about 6 month for this small enhancement.

**Comment by Shudrum** [comment]
Hi @zapalm!

Yep, I agree, and we are on the way to change it.
So I review your pull request and it cannot work.

You have changed

```php
if ($id_customer) {
```
to
```php
if ($id_customer !== null) {
```

But $id_customer can be 0 and this should not be validated.
You can see this error just by refreshing the front page if not logged.

Thank you.

**Comment by zapalm** [comment]
hello

oops. i fixed this and add another one mistake.

**Comment by Shudrum** [comment]
Hi!

Thank you for your modifications.

Just cast the integer before the test (`(int)`), squash your commits and I merge!

**Comment by zapalm** [comment]
done

**Comment by aleeks** [comment]
Hello @zapalm 
Your commit has been squashed here: https://github.com/PrestaShop/PrestaShop/pull/7480

Thank you!

**Pull request closed without merging**
