### PR TITLE
Set php-cs-fixer to version 2.14.2

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | PrettyCI has been updated and use an incompatible version of php-cs-fixer with 1.7.6.x branch. This PR set the right version of php-cs-fixer for this branch.
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | No test needed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17721)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Look like PrettyCi is not happy.. :thinking:

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
PrettyCi dislike this PrettyCi change :trollface:

**Comment by Progi1984** [comment]
Hello @atomiix, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by PierreRambaud** [comment]
PrettyCi is dead, this pull request is no longer required.
https://prettyci.com/goodbye

**Pull request closed without merging**
