### PR TITLE
Add some comments to Product class

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Adds some comments and simplifies one line of code.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Nothing to test, dev can QA it.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]
Nice job :+1:

**Review by boherm — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,
Auto tests are failing : https://github.com/florine2623/testing_pr/actions/runs/5691772881/job/15428897061
I already relaunched it multiple times.
Could you check ?

@PrestaShop/qa-automation 
Are the errors caused by the PR ?

**Comment by nesrineabdmouleh** [comment]
Hello @florine2623,

Thank you for your report!
The failed test is also failed in the nightly => https://github.com/PrestaShop/PrestaShop/actions/runs/5687189349

You can approve ;)

**Comment by boherm** [comment]
Thanks @Hlavtox!

**Pull request merged**
