### PR TITLE
Save old address id before delete

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Save old address id before delete.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Make sure you have the old address Id in the new address generated after delete
| UI Tests          | N/A.
| Fixed issue or discussion?     | N/A
| Related PRs       | N/A
| Sponsor company   | Evolutive

### CODE REVIEW

**Comment by PululuK** [comment]
TODO : upgrade script

**Comment by Hlavtox** [comment]
@PululuK What is the purpose of keeping the ID if we don't use it anywhere? 🤔

**Comment by PululuK** [comment]
> @PululuK What is the purpose of keeping the ID if we don't use it anywhere? 🤔

For example, this allows you to know which information has been modified compared to the initial address.

**Review by ShaiMagal — CHANGES_REQUESTED** [review]
unfortunately I don't see a single practical reason to use it :(

**Comment by kpodemski** [comment]
I'm closing this PR because I think it's easily achievable via a module, and the use case is so specific that, IMHO, it's not worth adding to the core.

**Pull request closed without merging**
