### PR TITLE
Fix undefined currency if cart is updated before currency is assigned to the context

### LINKED ISSUE #33953: Undefined context currency in actionCartSave
### Describe the bug and add attachments

There is a fatal error if there is a module hooked to `actionCartSave` that is doing something with currency (for example ps_googleanalytics) and the cart needs to be updated on these two places.

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L361

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L379

### Stack trace
```
PHP Fatal error: Uncaught PrestaShop\\PrestaShop\\Core\\Localization\\Exception\\LocalizationException: Price specification not found for currency: ""
in /var/www/vhosts/domain.cz/httpdocs/src/Core/Localization/Locale.php:171

Stack trace:
#0 /var/www/vhosts/domain.cz/httpdocs/src/Core/Localization/Locale.php(155): PrestaShop\\PrestaShop\\Core\\Localization\\Locale->getPriceSpecification('')
#1 /var/www/vhosts/domain.cz/httpdocs/classes/Tools.php(776): PrestaShop\\PrestaShop\\Core\\Localization\\Locale->formatPrice(52.231405, NULL)
#2 /var/www/vhosts/domain.cz/httpdocs/classes/Product.php(5567): ToolsCore::displayPrice(52.231405, NULL)
#3 /var/www/vhosts/domain.cz/httpdocs/modules/ps_googleanalytics/classes/Hook/HookActionCartSave.php(96): ProductCore::getProductProperties(1, Array)
#4 /var/www/vhosts/domain.cz/httpdocs/modules/ps_googleanalytics/ps_googleanalytics.php(203): PrestaShop\\Module\\Ps_Googleanalytics\\Hooks\\HookActionCartSave->run()
#5 /var/www/vhosts/kidspara...', referer: https://domain.cz/kosik?action=show
```

### Cause
The issue is caused by currency being initialized at the right place here:

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L318

But assigned to the context all the way on the bottom:

https://github.com/PrestaShop/PrestaShop/blob/5314c7dbc7a745f5d8aed42c681a7b88c6ff1e15/classes/controller/FrontController.php#L430

### Solution
Assign currency to the context right away.
PR to fix this: https://github.com/PrestaShop/PrestaShop/pull/33954

### Expected behavior

No error should be thrown

### Steps to reproduce

1. Make sure [tox_carttest.zip](https://github.com/PrestaShop/PrestaShop/files/12718116/tox_carttest.zip) is installed.
2. Go to FO, add two products to cart.
3. Go to cart page.
4. Change language with switcher in header.
5. Error.
6. Apply my PR, it will work fine.

### PrestaShop version(s) where the bug happened

1.7.6.0, 8.1.x, develop

### PHP version(s) where the bug happened

7.3, 8.1

### If your bug is related to a module, specify its name and its version

ps_googleanalytics

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixes context currency usage for modules that are hooked to `actionCartSave`. The fix is moving one line `$this->context->currency = $currency;`. If you look on it, you will see that `$currency` is only read. I also added some comments so it's easier to understand what is happening.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Follow steps to reproduce in https://github.com/PrestaShop/PrestaShop/issues/33953.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6214848736
| Fixed issue or discussion?     | Fixes #33953
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by boherm — DISMISSED** [review]
LGTM, thanks @Hlavtox!

**Review by boherm — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Waiting for author to validate the issue :pray:

**Comment by Hlavtox** [comment]
@hibatallahAouadni I have improved the steps to reproduce. You can start testing when you have time. :-)

**Review by hibatallahAouadni — COMMENTED** [review]
Please check my comment in the related issue :pray: 
https://github.com/PrestaShop/PrestaShop/issues/33953#issuecomment-1736007223

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
Auto-tests are :green_circle: https://github.com/hibatallahAouadni/testing_pr/actions/runs/6315904855
LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by matks** [comment]
@Hlavtox Don't forget the milestoooooone 🎶 😉

**Pull request merged**
