### PR TITLE
Remove box-shadow around contact form in classic

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The contact form shouldn't have 2 shadows
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1662
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
Screenshot :nail_care:

**Comment by antoin-m** [comment]
Before :
contactus-before

After :
contactus-after

**Review by mickaelandrieu — APPROVED** [review]

**Comment by maximebiloe** [comment]
Need a little rebase here 💅🏼

**Comment by maximebiloe** [comment]
Thank you @antoin-m!

**Pull request merged**
