### PR TITLE
Add new Hook for GetHookExecList

### PR DESCRIPTION
**Pull request by ludoviccardinale**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch           | develop
| Description      | We created this hook to avoid certain overrides on widely used modules; it will primarily allow for better management of cookie consent.
| Type             | improvement
| Category         | CO
| BC breaks        | no
| Deprecations     | no
| How to test      | 
| UI Tests          | 
| Fixed issue or discussion     | 
| Related PRs       | [Related PR autoupgrade](https://github.com/PrestaShop/autoupgrade/pull/811)
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hello @ludoviccardinale!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by Hlavtox — COMMENTED** [review]
I think we tried this with @ShaiMagal and it lead to an endless loop no?

Core will call `actionGetHookExecListAfter`, which will call `getHookModuleExecList`, which will call `actionGetHookExecListAfter` etc.

**Comment by kpodemski** [comment]
Hi @ludoviccardinale 

Have you tested it? This should be done differently outside of the Hooks mechanism. One idea could be using the Symfony service, where module registers list to block certain modules. They would return an array. In this method, all you do is compare the list coming from modules and `$modules_to_invoke`.

**Comment by matthieu-rolland** [comment]
> Hi @ludoviccardinale
> 
> Have you tested it? This should be done differently outside of the Hooks mechanism. One idea could be using the Symfony service, where module registers list to block certain modules. They would return an array. In this method, all you do is compare the list coming from modules and `$modules_to_invoke`.

hi @kpodemski ! 

are you referring to the hook dispatcher, which is defined as a service ?

**Review by matks — CHANGES_REQUESTED** [review]
The Behat tests fail it seems indeed there is an issue with this hook.

**Comment by kpodemski** [comment]
> > Hi @ludoviccardinale
> 
> > 
> 
> > Have you tested it? This should be done differently outside of the Hooks mechanism. One idea could be using the Symfony service, where module registers list to block certain modules. They would return an array. In this method, all you do is compare the list coming from modules and `$modules_to_invoke`.
> 
> 
> 
> hi @kpodemski ! 
> 
> 
> 
> are you referring to the hook dispatcher, which is defined as a service ?

No, it would've been the same problem, it has to be something completely different which does not work base on hooks

**Comment by Hlavtox** [comment]
And regarding the usecase, it would be better to implement a consent system to handle this usecase.

It wouldn't be difficult either.
New consent property array on context, that would be updated by cookie bar modules and read by marketing modules.
Then some standardized JS event so marketing modules can start measuring without page reload.

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Cant be done like this, you need to prevent execution differently for each customer. :-)

**Comment by kpodemski** [comment]
> Cant be done like this, you need to prevent execution differently for each customer. :-)

I think it is possible to use Configuration::set which could help for this, but this should be consulted with somebody from Linea Graphica or @prestamodule

**Review by kpodemski — CHANGES_REQUESTED** [review]
Before submitting changes to this PR, please [open the discussion](https://github.com/PrestaShop/PrestaShop/discussions/categories/ideas) to consult the best way to implement this feature.

**Comment by kpodemski** [comment]
Closing because a different solution is in the works.

**Pull request closed without merging**
