### PR TITLE
Fix translation on account creation email error

### PR DESCRIPTION
**Pull request by SebBareyre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix translation if email is already registered on account creation
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Try to create an account with an already registered email

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12344)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @SebBareyre

**Comment by marionf** [comment]
@SebBareyre it was removed by @MathiasReker in this commit: https://github.com/PrestaShop/PrestaShop/commit/5d31dfbff377bad9ba9ac271b8ab74b61cb54288#diff-fb40c58222cc1693e8a461a4de4956df

If email is too long, it brokes the display:

capture d ecran_951

**Comment by MathiasReker** [comment]
This PR can break the design. Test your change with "test@testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest.com"

**Comment by MathiasReker** [comment]
Also the email is already displayed in the field. Why would you want to add it into the error msg?

**Pull request merged**
