### PR TITLE
Merge 1.7.8.x into develop [merge]

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 1.7.8.x into develop
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI should be green
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27103)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]
Thank you @atomiix :pray:

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@atomiix It seems that CI is broken.

**Comment by PierreRambaud** [comment]
@Progi1984 @atomiix 's not available this week, I did it for him, I hope everything is ok right now. Waiting for the CI

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @atomiix

**Pull request merged**
