### PR TITLE
WS: Allow product_option_values image

### PR DESCRIPTION
**Pull request by FrancMunoz**
Allow CRUD operations over product_option_values images.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow CRUD operations over product_option_values images.
| Type?         | new feature
| Category?     | WS
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | http://site.com/api/images/product_option_values

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR! The Core team will soon have  look at it.
In the meantime, could you squash your commits into one (with the proper naming convention)? Thanks!

**Comment by xBorderie** [comment]
[Here's how to squash commits](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request). [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by FrancMunoz** [comment]
Hi xBorderie! I'm sorry I'm unable to squash , it shows me merge conflicts. Is there any alternative... if I have to start again I will...

**Comment by xBorderie** [comment]
The easiest way here might indeed be to start over, with a recent codebase :)

**Pull request closed without merging**
