### PR TITLE
Adding country Tanzania

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Adding Tanzania to the list of supported countries.
| Type?         | new feature
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | na
| How to test?  | You should be able to create a shop located in Tanzania.

When Swahili language is available, should be added to the XML file.
FYI the 0% tax rule is for exportation (all countries expect Tanzania), I don't know how it should be configured in the XML (or in PrestaShop, for that matter).

### CODE REVIEW

**Comment by AlexEven** [comment]
Well, we should update the documentation to which we're redirecting to in that case -_-

That's where you go when you click on the provided link when you create a PR:
http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message
(Oh! LO!)

Ping @xBorderie

**Comment by mickaelandrieu** [comment]
Sorry for that, @prestonBot wasn't aware of this category (shame on me!) this will be fixed as soon as the tests pass :)

**Comment by AlexEven** [comment]
Thanks @mickaelandrieu - and apologies to @xBorderie, the doc was ok it seems! ^^;

**Comment by aleeks** [comment]
Thank you @AlexEven :alien:

**Pull request merged**
