### PR TITLE
Add actionEmailSendBefore hook

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add actionEmailSendBefore hook
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

See https://github.com/PrestaShop/PrestaShop/pull/4194

@aleeks didn't have the time to test before leaving because I can't reinstall my shop (??) but I'm pretty confident :smile:

### CODE REVIEW

**Comment by aleeks** [comment]
@antoin-m , I don't care about your confident ahahah, I want you show me !!!!!!!

**Comment by antoin-m** [comment]
@aleeks add this to a module's installation method :
`            $this->registerHook('actionEmailSendBefore')
`

And 

`
    public function hookActionEmailSendBefore($params) {
        return true;
    }
`

If you buy something you should receive an email.
Then change the function so that it returns false. You shouldn't receive emails then.

**Comment by aleeks** [comment]
Tested & ok. To be merged.

**Comment by aleeks** [comment]
Thank you @antoin-m

**Pull request merged**
