### PR TITLE
BO - Save button design change if an error message is displayed

### LINKED ISSUE #19005: BO - Save button design change if an error message is displayed
#### Describe the bug

In cart rule page if an error message is displayed the "save" button design change (see screenshot)

#### Expected behavior

The design should never change

#### Steps to Reproduce

1. Go to BO => catalog => discount => cart rules
2. Click on "add new cart rule"
3. Check the design off the "save" button
4. Don't fill any field and click on "save" button
5. The error message is displayed
6. Check again the "save" button ( the design is not the same )

**Screenshots**

**Without the error message**
capture d'écran_48

**With the error message**
capture d'écran_49

#### Additional information

* PrestaShop version: 1.7.7 and 1.7.6
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In cart rule page if an error message is displayed the "save" button design change.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    |no
| Deprecations? | no
| Fixed ticket? | Fixes #19005.
| How to test?  | See ##19005 by @SD1982 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19021)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SimonGrn** [comment]
Hello, it seems the issue fixed by this PR is from the 1.7.7 branch (from the 1.7.7 beta test campaign). 
Why is this PR on the `develop` branch ?

**Comment by Progi1984** [comment]
@SimonGrn The issue has not been added to the 177x Kanban so it must be fixed on `develop` branch.

**Comment by SD1982** [comment]
LGTM Thanks @PululuK !

**Comment by Progi1984** [comment]
Thanks @PululuK

**Pull request merged**
