### PR TITLE
[-] BO : Fix #PSCSX-6087 "Maintenance Mode" disappears in Modules page

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Thanks @PrestaEdit  for your contribution, it also disappear in multistore... @Shudrum is looking at it.

Best regards

**Comment by Shudrum** [comment]
:+1:

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, can you report your PR on branch 1.6.1.x ?

Best regards.

**Comment by PrestaEdit** [comment]
Do we have to do PR on branch 1.6.1.x each time or ? What th epoint to do it on this branch ?

**Comment by julienbourdeau** [comment]
We will explain everything on build.prestashop.com soon. You will have to choose the right branch for your PR now.
Bug fixes go to `1.6.1.x`
New minor features go to `1.6.2.x`
New major features go to `develop`

**Comment by PrestaEdit** [comment]
All right ;-) Good, :)

**Comment by panploenes** [comment]
Great!! Means you LTS is not far :)

**Pull request closed without merging**
