### PR TITLE
Fixes free product cart rule not being added

### LINKED ISSUE #15751: 'Total available for each user' in cart rule not considered
**Describe the bug**
When you offer a product with price 0 as a free gift any record is inserted at table `ps_order_cart_rule`, so the customer can use it another time

**To Reproduce**

1. Set a product with price 0
image
1. Create a cart rule limited to 1 use per customer and offer this product as free gift:
image
image

1. Create an order. Cart rule is added correctly.
1. Create a second order. **Cart rule is added but it shouldn't**.

**Additional information**
PrestaShop version: 1.7.6.1

### PR DESCRIPTION
**Pull request by gennaris**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Customers were able to reuse a cart rule intended for a one-time free gift because the entry in ps_order_cart_rule wasn't recorded when the cart total had a zero price. This PR introduces a check to ensure that cart rules of the “gift product” type are correctly accounted for, regardless of the cart total.
| Type?             | bug fix 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check #15751 steps to reproduce before / after this patch
| UI Tests          |  N/A
| Fixed issue or discussion?     | Fixes #15751 
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ha, I reported this some time ago - https://github.com/PrestaShop/PrestaShop/issues/35921, cool!

What if we just delete this piece of code completely?

```
// If the reduction is not applicable to this order, then continue with the next one
            if (!$values['tax_excl']) {
                continue;
            }
```

**Review by Hlavtox — APPROVED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Please target 9.0.x

**Comment by gennaris** [comment]
I think that check was added to avoid saving other lower-priority cart rules compatible with that cart in **ps_order_cart_rule**, but the codebase would need to be explored further. 
I just focused on fixing this specific issue since it relates to some of my activities.

**Comment by kpodemski** [comment]
Hi @gennaris 

If that's the case then maybe we should convert your PR to Draft?

**Comment by Hlavtox** [comment]
@kpodemski The solution works, I just suggested if we can explore that original of those lines. And just wipe them completely.

**Comment by kpodemski** [comment]
@Hlavtox I ignored your comment 😅 all clear

@gennaris you will have to rebase your branch after changing to v9.0.x, or create a new PR :)

**Comment by gennaris** [comment]
@Hlavtox  @kpodemski  
Thanks - I am closing this one and create a new PR with v9.0.x target

**Pull request closed without merging**
