### PR TITLE
Wrong visitor group assumed on multistore

### LINKED ISSUE #10849: Wrong visitor group assumed on multistore
**Describe the bug**

Every time the `FrontController::getCurrentCustomerGroups()` method is called and returns an empty array, the customer group is assumed to be `1` by default. But In Group admin page, you've got the choice to define visitor group to a different id than `1`.

We should be using `Group::getCurrent()->id` instead.

**To Reproduce**

* Create a new group and define it as the visitor group.
* Create a category only visible by that group.
* Link a product to this category.
* Make a search call on this product name in frontend.
* The product will not show.

**Additionnal information**
PrestaShop version: all versions
PHP version: all versions

### PR DESCRIPTION
**Pull request by Flowster**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Default group should not be id `1` but the visitor group set by the shop owner.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10849 
| How to test?  | Follow steps in above ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10851)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Hello @Flowster,

thanks for your contribution, would you mind to rebase your pull request?

Thanks

**Review by jolelievre — CHANGES_REQUESTED** [review]
Hello @Flowster 
Thank you for the fix ;) It's all good to me, however since the develop branch changed since you created your PR you have several conflicts. Can you rebase your PR with the up to date `develop` branch please?

**Comment by Flowster** [comment]
Hello @jolelievre
Unfortunately I'm traveling aboard for a few months without stable internet connection. If someone wants to do it for me I'm good with it ;).

**Comment by Progi1984** [comment]
I close this PR because it was implemented by @matthieu-rolland in #14702. Thank you @Flowster for your contribution.

**Pull request closed without merging**
