### PR TITLE
Wording corrections before RC

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR fixes a few new wordings The incorrect ones have been removed from the XLF files because they were new in 178 anyway, so no need to keep useless wordings in the catalogs
| Type?             | bug fix
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24902)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
PR content seems OK. Need Wording OK too

**Review by Progi1984 — DISMISSED** [review]

**Comment by Julievrz** [comment]
Hi @jolelievre, thanks for the PR! Could you please change the domain of the following string:

'Note that this page is available in a single shop context only. Switch context to work on it.' in Admin.Payment.Notification

The right domain is Admin.Notifications.Info 

Plus, it will allow Matthieu to use it in #24471 without delaying the catalog push. :)

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by Julievrz** [comment]
The wording is ok but please **wait until Tuesday, June 22 before merging the PR**. We will wait until then in case new corrections should be done before the RC.

**Comment by jolelievre** [comment]
**Kindly reminder** this PR is NOT mergeable in its current state Only the modifications on the wording have been made but they remain useless until we re-exported the XLF catalog to include new wordings into them Don't rush at merging this one before the catalog are re-exported

I planned to do it (in time) I'm just waiting the last moment in case we have other wordings to add, besides because of the recent troubles with our CI I think we still have a few days before the next build

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Pull request merged**
