### PR TITLE
Removed theme and admin menu orientation fields

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Remove theme and admin menu orientation fields from `Edit employee` form |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1384 |
| How to test? | Open `Edit employee` form and check theme and admin orientation fields availability |

### CODE REVIEW

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by maximebiloe** [comment]
Shouldn't we remove the columns into employee tab into database too?

**Comment by maximebiloe** [comment]
Thanks!

**Comment by PrestaEdit** [comment]
Mmmmmmh. A (good) reason to remove this ? 

(N.B.: I think that, when it's not a bugifx PR, you can avoid merge a PR in only 3hours, to let community talk about it, maybe... :))

**Comment by vincentbz** [comment]
Hi,

The reason to remove/hide this option is that it's not working and we need too much time to make it correctly work with the new navigation. 
So the decision was taken to hide it until we fix it

**Comment by PrestaEdit** [comment]
We have time, no ? Or, maybe, you plan to have a first release in the next few days ?!

**Comment by PrestaEdit** [comment]
(by the way, it's not hidden but deleted. Hidden need to have commented code, instead of code deletion, too ;-))

**Comment by thierrymarianne** [comment]
@PrestaEdit Only the view has been impacted (fields hidden to merchants), not the model. VCS history will help restoring the code whenever needed.

**Comment by PrestaEdit** [comment]
Mmmmh. I'm really not satisfied by your reply, and you know it. Not satisfied because I don't see why hidden this, and not solve it (or, as I say and you don't answer to, you want to make a first release in a realy next few days ...).

Really hope this options will come back, and not in a 1.8 version, :)

**Comment by vincentbz** [comment]
This is a question of time vs resources we have vs priorization with the other topics.
You've noticed we have changed the navigation, the menu. So we need to recreate it for top menu too, and it takes time to do it correctly.

**Comment by PrestaEdit** [comment]
Don't worry, I can understand it. I just hope it will come back again, :)

**Pull request merged**
