### PR TITLE
[*] FO : Improve performances

### PR DESCRIPTION
**Pull request by jocel1**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | improve 1.7 performances |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Run tests |
- Make sure to create empty translation file to make file_exists cacheable
- Properly create theme/cache dir
- Properly create rijndael setting during install to enable mcrypt native functions instead of slow blowfish class

### CODE REVIEW

**Comment by jocel1** [comment]
According to my benchmarks on a real shop, with those optimisations combined with the ones already pushed, 1.7 is now faster (up to almost 20% @8 concurrent connection) than the 1.6.1.4 release ! \o/

https://www.dropbox.com/s/q0tv40cfqmldg75/1.7-opti-latest.png?dl=0

**Comment by Shudrum** [comment]
Wow!

Thank you!

**Comment by xBorderie** [comment]
:chart_with_upwards_trend:

**Comment by shyandsy** [comment]
@jocel1 
my back office of version 1.6.1.7 is very slow.
product list page            10 -12s
add product operation    8-10s

running on linode 2GB, 1 core machine
just wanna confirm is this normal?

**Comment by xBorderie** [comment]
Hi @shyandsy !
This PR impacts the future version 1.7.0.0, not v1.6.

Could you create an issue ticket on the Forge with as many details as possible?
http://forge.prestashop.com/secure/Dashboard.jspa
Thank you!

**Comment by shyandsy** [comment]
@xBorderie  
ok

**Pull request merged**
