### PR TITLE
Fix button show password height on Safari

### PR DESCRIPTION
**Pull request by sLorenzini**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Button show password height was too small on Safari. Add an height on ti (the same as field height)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4484
| How to test?  | Go to sign in page to see the button (on Safari)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8848)

### CODE REVIEW

**Comment by eternoendless** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[themes/classic/_dev/css/partials/_commons.scss, line 149 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8848#-L7Z7hEHEvzX4FdNRKrg:-L7Z7hEHEvzX4FdNRKrh:b-13erx7) ([raw file](https://github.com/prestashop/prestashop/blob/8d1dc70fb53b8894e9c91fc557aba07b0b1b9cd0/themes/classic/_dev/css/partials/_commons.scss#L149)):*
> ```SCSS
>       &[data-action="show-password"]{
>         background: $gray;
>         height: 38px;
> ```

I think you can simply remove the "height" property altogether, it doesn't seem to be needed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8848)*

**Comment by sLorenzini** [comment]
@eternoendless, changes done.

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8848#-:-L7d32wvAFWsIyDRo2yc:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
~~@sLorenzini would you mind rebasing your pull request?~~ nope, let's wait after 1.7.3.1 release :)

**Comment by eternoendless** [comment]
Replaced by https://github.com/PrestaShop/PrestaShop/pull/8946

**Pull request closed without merging**
