### PR TITLE
Migrate cookie constants usages to PSR4

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | This will remove constants usages of the `Cookie` class into a new CookieOptions class. That's less legacy to maintain, and this also removes legacy usages from the `PrestaShopBundle` and `Adapter` namespaces.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | CI 🟢 & automated tests should be sufficient. Tests classes that handle cookie, in both front and back office.

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
LGTM 👍

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
Auto tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/4233005127

**Comment by nicosomb** [comment]
@kpodemski I think that auto tests and CI are enough for this PR. No need to wait for QA and dev 😉  if all is green, you can merge (maybe we can ask QA team before, but from dev side, we have nothing to test).

**Comment by kpodemski** [comment]
@nicosomb waiting for qa + waiting for dev means that we make sure to validate it, this time we validate it using automated tests 👍🏻 so, yes, there's nothing for us to test, but we need to see if auto tests are green, thus "waiting to dev"

**Comment by FabienPapet** [comment]
Tests : https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4372668414

**Review by matthieu-rolland — COMMENTED** [review]
It seems like many automated tests are broken here, it could be related to the PR (but you can confirm with the automation team if you think it could be unrelated :+1: )

Maybe it's worth restarting the tests because many things have been fixed on automation in the last two weeks

**Comment by FabienPapet** [comment]
~Tests re-run in [FabienPapet/ga.tests.ui.pr/actions/runs/4372668414](https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4372668414)~

**Comment by FabienPapet** [comment]
~https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4531391094~

**Comment by kpodemski** [comment]
@FabienPapet you have an outdated `ga.tests.ui.pr` repo

**Comment by FabienPapet** [comment]
Fixed it 

New running campaign : https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4532240027

**Comment by lartist** [comment]
New trial https://github.com/lartist/ga.tests.ui.pr/actions/workflows/pr_test.yml

**Review by mflasquin — APPROVED** [review]

**Comment by 0x346e3730** [comment]
CI and Tests are green, merging, thank you @FabienPapet

**Review by 0x346e3730 — APPROVED** [review]

**Pull request merged**
