### PR TITLE
Removed free shipping from cumulative reduction

### LINKED ISSUE #24635: FO - Discounts - The discount detail is NOK
#### Describe the bug

In the FO > Shopping cart page and checkout page, when we apply two cart rule "Free shipping" + percent discount, the discount line s NOK, the discount = total product + shipping

#### Steps to Reproduce

1. Go to BO > Catalog >  Cart rules page
2. Create a cart rule Free shipping
3. Create another cart rule 10%
3. Go to FO, add a product to the cart
4. In the shipping method, you need to select **not a free shipping**
5. Apply discounts
image

In the BO > Orders > Order details => ok
image

With PS1769, we have this:
image

#### Additional information

* PrestaShop version: 177x, 178x
* PHP version: 7.2, 7.4

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Removed free shipping from cumulative reduction
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24635
| How to test?      | Cf #24635
| Possible impacts? | Cart Rule & Free Shipping

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24754)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @Progi1984 
Following the step described by @khouloudbelguith  in #24635 I'm still able to reproduce the issue
It's ok in BO 
image
But not in FO
https://drive.google.com/file/d/1qqiYGYfaCAMjwjFDPEvQthcV6bCWSYLM/view?usp=sharing

**Comment by Progi1984** [comment]
@SD1982 Sorry : i just tested the PR 

image

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM thanks @Progi1984 !!

**Comment by Progi1984** [comment]
Thanks @SD1982

**Pull request merged**
