### PR TITLE
Delete obsoleted /images.inc.php file

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Obsoleted in v1.5, let's delete it now.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | GH CI tests must pass
| Possible impacts? | no, obsoleted years ago in v1.5

There is no use/mention in the current repo, checked by regex:
```
(?<!\w|::|->)(cacheImage|checkImage|checkImageUploadError|isPicture|checkIco|imageResize|imageCut|createSrcImage|createDestImage|returnDestImage|deleteImage) *\(
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23992)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@mvorisek We can't remove this file as functions can be used by external modules. So these functions are our public API. They can be removed in 8.0, when we will be able to do some BC Breaks.

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek We can't remove this file as functions can be used by external modules. So these functions are our public API. They can be removed in 8.0, when we will be able to do some BC Breaks.

I know, but as deprecated in `v1.5`, I think this is more than than safe to be removed now

**Comment by Progi1984** [comment]
> > @mvorisek We can't remove this file as functions can be used by external modules. So these functions are our public API. They can be removed in 8.0, when we will be able to do some BC Breaks.
> 
> I know, but as deprecated in `v1.5`, I think this is more than than safe to be removed now

No, it will be removed in `8.0`. We can't remove it in minor versions.

**Comment by mvorisek** [comment]
What do you mean by `8.0`? If it should be for the next major version, please reopen and add a milestone instead.

**Comment by Progi1984** [comment]
The next minor version will be `1.7.8.x`, followed by `1.7.9.x`. The next major will be `8.x`.

**Comment by mvorisek** [comment]
Please add `8.0` milestone then :)

**Comment by Progi1984** [comment]
We will add it when we will have define the roadmap.

**Comment by mvorisek** [comment]
I see there is `Next`, please reopen and add it there. This PR is not to be closed, only the merge should be postponed.

**Comment by PierreRambaud** [comment]
Don't worry, we will refactor the whole project architecture during the next major.

**Comment by PrestaEdit** [comment]
You know... Already the case in 2015, we will have to wait to purge some deprecateds files, as you see (https://github.com/PrestaShop/PrestaShop/pull/1081)

**Comment by mvorisek** [comment]
Yes, marked to be deprecated in v1.5, thus fine to remove in v1.6, super fine in v1.7.

**Comment by PierreRambaud** [comment]
> Yes, marked to be deprecated in v1.5, thus fine to remove in v1.6, super fine in v1.7.

You know, a lot of things are deprecated for a long time but still used by the community because of lack of communication.
Since we don't communicate about removing it in the next version, we can't do it right now. 
But as I said above, we will do it on the next major.

**Comment by mvorisek** [comment]
Reopening and labeling with `Next` will be a good colab response.

**Comment by matks** [comment]
> Reopening and labeling with `Next` will be a good colab response.

No need.

When we start working on PrestaShop 8.0.0 we'll simply go through all `deprecated` tags in the code and remove it all 😄

**Pull request closed without merging**
