### PR TITLE
[-] CORE : Check displayPaymentEU to fix advanced checkout restrictions

### PR DESCRIPTION
**Pull request by firstred**
## Description

Same as #5240, but for PS 1.7

Applies remaining fixes for #4739 
## Forge ticket

http://forge.prestashop.com/browse/BOOM-629

### CODE REVIEW

**Comment by maximebiloe** [comment]
@tchauviere can you look at it, please?

**Comment by tchauviere** [comment]
Everything looks good to me, waiting for PM feedback

Ping @superGB or @vincentbz.

**Comment by tchauviere** [comment]
I added "Waiting for tests to pass" since there were failing.

I forced travis to retry them.

**Comment by firstred** [comment]
Strange isn't it?

It's the same as for 1.6, only with `paymentOptions` aa extra hook and it fails...

**Comment by Shudrum** [comment]
Hi!

Sorry but the `displayPaymentEU` should not exists anymore on this branch.

**Pull request closed without merging**
