### PR TITLE
Change old links to newer method

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Migrates some of the old links to use getPageLink method.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~Tests green.~ (@matks disagrees)
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7812740104
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by kpodemski — DISMISSED** [review]
Improvement -> Develop :D

**Comment by Hlavtox** [comment]
@kpodemski Done

**Comment by Hlavtox** [comment]
Test run - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7725519079
I also manually verified one link with encoding, just to be sure. :-)
`https://upgradetest.trendo.cz/pokladna?submitAddDiscount=1&discount_name=DSAD+SDASD%3F`

**Review by boherm — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]
Nice improvement 👍

**Review by matks — COMMENTED** [review]
@Hlavtox I think this PR needs to be tested by a QA analyst. UI Tests are not enough unless you tell me you have yourself verified that for each of the links modified, there is a UI test using it.

**Comment by Hlavtox** [comment]
@matks QA can test it, no worries.

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

I tested the following pages :
- payment module page in BO
- customer address
- FO address form in customer account
- Order confirmation
- Order detail
- Order follow
- Password forgot 
- pdf invoice
- pdf return invoice
- pdf order slip

LGTM ✅

**Comment by kpodemski** [comment]
thank you @Hlavtox @florine2623

**Pull request merged**
