### PR TITLE
[-] BO: Sync stock reference, EAN13, UPC codes when updating product and attributes

### PR DESCRIPTION
**Pull request by guestisp**

### CODE REVIEW

**Comment by sfroment42** [comment]
Hello,

Could you please tell why you want to do it? Cause if you don't have the advanced stock active you don't need to use the ps_stock table. Here you actually force a useless insertion for people who don't use this feature...

Best regards.

**Comment by guestisp** [comment]
I'm not forcing an insert, i'm just updating.

**Comment by sfroment42** [comment]
Yes but your running a useless query if the advanced stock isn't activate.
You should add some check to verify if the advanced stock is activate and if the product use it.
Like this:
```php
if (Configuration::get('PS_ADVANCED_STOCK_MANAGEMENT') && StockAvailable::dependsOnStock($this->id, Context::getContext()->shop->id))
```

Thanks.

**Comment by guestisp** [comment]
I did the change as your suggestion, but now is even worse. 
Previously I was executing a single query in all conditions, now, with your suggestion, there are 2 query: one for `StockAvailable::dependsOnStock`  and one for the update.

**Comment by sfroment42** [comment]
No cause the 2 queries made in the if are often used when you update a product so they will be cached.
Another thing: 
```php
'id_product_attribute = '.(int)$id_product_attribute, 1);
```
Instead of the limit 1 I think this would be more appropriate 
```php
'id_product = '.$this->id.' AND id_product_attribute = '.(int)$id_product_attribute);
```

**Comment by guestisp** [comment]
Fixed

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR.

Best regards.

**Pull request merged**
