### PR TITLE
Integrate ContextStateManager into refund handlers

### LINKED ISSUE #21990: [Multistore] - BO - Order page - All shops selected - cannot return products
#### Describe the bug

"All shops" is selected, in the BO > Orders > Order page > when we try to return products => An exception is displayed
image

#### Steps to Reproduce

Enable Multishop Context.
Create a new shop `ShopA` related to the `Default` Group
Create an Order from the FO in any shop 
Go to BO > Customer Service > Merchandise Returns > Enable returns in all shops
Go Back to the Order => last order created => All shops selected
Change the status of the Order to Shipped 
Click on "Return Products"
Select Products
Click on Return products
See error
image

PS: 1768 => ok
https://drive.google.com/file/d/1Fy1srxxiYJ1ucIh9hGPlRSXuxtVfsfR_/view?usp=sharing

#### Additional information

* PrestaShop version: 177x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | The ContextStateManager was not used in all handlers related to refund, it's now added which prevents this action from bugging when the BO is in All shops mode
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21990
| How to test?  | See the issue, it only mentions return product, but partial and standard products were also buggy

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22246)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !! Thanks @jolelievre !!

**Comment by PierreRambaud** [comment]
Thank you @jolelievre

**Comment by PierreRambaud** [comment]
Thank you @jolelievre

**Pull request merged**
