### PR TITLE
Add order table empty state

### LINKED ISSUE #17597: Remove search fields when listing are empty
**Describe the bug**
Remove search fields, search button, labels and bulk checkbox when listing are empty

Already migrated pages:
- [x] Catalog > categories
- [x] Catalog > monitoring
- [x] Catalog > brands
- [x] Catalog > suppliers
- [x] Catalog > files
- [x] Customers > customers
- [x] Customers > addresses
- [x] Customer service > order messages
- [x] Design > pages (categories & pages)
- [x] International > localization > Languages
- [x] International > localization > Currencies
- [x] International > taxes > taxes
- [x] Shop parameters > order settings > statuses
- [x] Shop parameters > customer settings > groups
- [x] Shop parameters > contact > contacts
- [x] Shop parameters > traffic & SEO > SEO & URLs
- [x] Advanced parameters > E-mail 
- [x] Advanced parameters > Team > Employees 
- [x] Advanced parameters > Team > Profiles 
- [x] Advanced parameters > Database > SQL manager 
- [x] Advanced parameters > Database > DB backup
- [x] Advanced parameters > Logs
- [x] Advanced parameters > Webservice

Not yet migrated pages:
- [ ] Catalog > products
- [ ] Catalog > attributes
- [ ] Catalog > features
- [ ] Catalog > cart rules
- [ ] Catalog > catalog price rules
- [ ] Customer service > customer service
- [ ] Customer service > merchandise returns
- [ ] Design > image settings
- [ ] Shipping > carriers
- [ ] International > locations > Zones
- [ ] International > locations > Countries
- [ ] International > locations > States
- [ ] International > taxes > taxes rules
- [ ] Shop parameters > customer settings > titles
- [ ] Shop parameters > contact > stores
- [ ] Shop parameters > traffic & SEO > Search engines
- [ ] Shop parameters > traffic & SEO > Referrers
- [ ] Shop parameters > Search > Search
- [ ] Shop parameters > Search > Tags
- [ ] Advanced parameters > Multistore > Admin shop group
- [ ] Advanced parameters > Multistore > Admin shop
- [ ] Advanced parameters > Multistore > Admin shop url

**Screenshots**
Pages without empty state
capture d'écran_2306

Pages with empty state
capture d'écran_2305

### LINKED ISSUE #18526: Empty state order list page
**SPEC**

Add an empty state on the order list page

**WHY**
Empty states are a way to improve the user experience of your product, from onboarding to encouraging users to interact with PrestaShop.

**DESIGN**
https://invis.io/5FRLCBENAS4#/419281734_Order

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | The empty state of the order page was missing, this PR adds it.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18526 & partially #17597
| How to test?  | Install PrestaShop **without** demo data and go to the orders pages. You should see the empty state content as shown here : [https://invis.io/5FRLCBENAS4#/419281734_Order](https://invis.io/5FRLCBENAS4#/419281734_Order) and no search form should be displayed<br><br>None of the search form listed in the issue #17597 should be showed except in `Catalog > Category` & `Design > Pages`. Those 2 pages will be done in a separate PR.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19597)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

The display of the empty state is on 4 lines, it's not very readable. Could you display it on 3 lines (as shown on Invision) ?

Thanks

pr19597 affichage moche

**Review by jolelievre — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @atomiix !

It's OK for the empty state. For the search not displayed when there is no data, I still have the search bar on Catalog > Categories and Design > Pages.

Please note that this might be linked to the fact that there is a "Home" category, which cannot be deleted, so maybe the search bar is displayed because the table is not empty (just like the search bar is displayed when a filter is applied with no result).

pr19597 search on pages

pr19597 search on categories

Please tell me if this can be fixed or not :)

Thanks

**Comment by atomiix** [comment]
@Robin-Fischer-PS You got it all right ;) because of that Home category, there's a "default" filter and that prevents the form to be hidden.

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Progi1984** [comment]
@atomiix Could you fix that ?

**Comment by atomiix** [comment]
@Progi1984 Maybe we should fix this in another PR milestoned for 1.7.8 as it was in the first place? WDYT?

**Comment by Progi1984** [comment]
@atomiix I don't approve. The job is nearly done. It's a small step to fix bugs rather than create a new PR.

**Comment by Progi1984** [comment]
@atomiix Could you rebase your PR for merging ? Thanks ;)

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @atomiix & @Robin-Fischer-PS

**Pull request merged**
