### PR TITLE
Fixed adminorders concat statement not selecting customer firstname

### PR DESCRIPTION
**Pull request by Rho-bur**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | In 1.6.1.13 BO Orders, the customers firstname and name were missing;<br/> That is because in the AdminOrders constructor the new CONCAT option of the _select statement doesn't produce the desired output. <br/> Changed it to CONCAT_WS.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | That happened on a 1.6.1.3 upgraded to 1.6.1.13 using the default theme

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7928)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for your contribution!

Sadly, you now have malformed commits instead of just one commit:
* the initial commit, which does not follow the [PS naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message),
* one commit which does follow the naming convention,
* one merge commit -- which if merged can break the repository's history!

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by eternoendless** [comment]
From what I see, the previous code produces a customer name like "J. DOE" and the proposed code changes it to "John DOE"

I don't believe this can be considered a bug fix really, and to my understanding it's unrelated to the usage of CONCAT or CONTACT_WS.

@vincentbz What do you think?

**Comment by Rho-bur** [comment]
It may not appear as a big difference but this was solving a specific issue when the customers first and last name were missing despite the records existing in the tables.
Nothing else worked.

**Comment by colinegin** [comment]
@sarahdib and @marionf what do you think about this PR ? Do we still have the issue in 1.7 ?

**Comment by marionf** [comment]
In 1.7, customer lastname is completely displayed while only the first letter of the firstname is displayed

capture d'écran_1763

**Comment by colinegin** [comment]
@eternoendless @PrestaShop/prestashop-core-developers can you tell us if this PR is still needed for 1.7 ?
Thanks !

**Comment by PierreRambaud** [comment]
The problem is how the search is doing the request. But the problem still occur on 1.7.

**Pull request closed without merging**
