### PR TITLE
Fix totals excluding tax in confirmation email

### LINKED ISSUE #17764: Mail with prices with taxes/no taxes mixed
**Describe the bug**
'order_conf' mail template displays the order summary, and prices tax are mixed.

**To Reproduce**
1. Configure a customer group with "No taxes"
image

2. Create a coupon code with 1€ "No taxes"
image

3. All prices in checkout are displayed with "No taxes"
image
image

4. Finish order and check email. There are prices with "No taxes" and prices "With taxes".
image

**Additional information**
PrestaShop version: 1.7.6.3

### PR DESCRIPTION
**Pull request by Seb33300**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | In confirmation email, all totals should be displayed without taxes if the shop is configured to display prices without taxes.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #17764
| Related PRs       | 
| How to test?      | Follow steps described in https://github.com/PrestaShop/PrestaShop/issues/28230
| Possible impacts? | 

I applied the same condition as here:
https://github.com/PrestaShop/PrestaShop/blob/ae6600f44d32ab5982ea2a219df7d121c6c35f1e/src/Adapter/Cart/QueryHandler/GetCartForViewingHandler.php#L106-L118

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28231)

### CODE REVIEW

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@Seb33300 Could you target the `develop` branch ? As the bug is present since the `1.7.5.2`, it will not be fixed in `1.7.8.x`.

**Comment by Seb33300** [comment]
@Progi1984 done

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Closed & Reopened for restarting the CI.

**Review by atomiix — DISMISSED** [review]

**Review by szavadskiy — COMMENTED** [review]
Hello @Seb33300 

Thank you for your PR :rocket: 
I checked it and see that one of the line still displaying with taxes
photo_2022-04-22_16-41-42

Please check it and feedback 
Thanks

**Comment by Seb33300** [comment]
@szavadskiy how did you get this line?

**Comment by szavadskiy** [comment]
@Seb33300  "no tax" it's a name of "Cart Rules"

**Comment by Seb33300** [comment]
@szavadskiy I pushed an additional fix for this line. Can you please try again?

**Comment by hibatallahAouadni** [comment]
@Seb33300 Yes after validating the code by Dev Team :wink:

**Review by matks — COMMENTED** [review]
Hi @Seb33300 the logic is good but ... could we split this very long line into something smaller ? 😅  it would help to read it and help to maintain it

**Review by Progi1984 — DISMISSED** [review]

**Comment by Seb33300** [comment]
I can split it but we will have 2 long lines after that 😅

**Comment by matks** [comment]
> I can split it but we will have 2 long lines after that 😅

The two lines will be smaller than the single very big line we have now 😄

**Comment by Seb33300** [comment]
@matks Done

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]
It's a lot better 👍 thanks

**Comment by Seb33300** [comment]
Hello, @szavadskiy @hibatallahAouadni 
This PR has 2 accepted reviews.

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Seb33300 

Thanks for your PR and your patience :pray: 
LGTM, I tested on divers cases and with multistore enabled, it works like charm :tada: 
QA :heavy_check_mark: 

image

Thanks!

**Comment by Progi1984** [comment]
Thanks @Seb33300 & @hibatallahAouadni

**Pull request merged**
