### PR TITLE
Update CategoryController.php to display the root category in the categories/subcategories breadcrumbs for better user experience.

### PR DESCRIPTION
**Pull request by greatdesign**
| Questions      | Answers
| -----------------  | -------------------------------------------------------
| Branch?         | develop 
| Description?  | Display the root category in the categories/subcategories breadcrumbs for better user experience.
| Type ?            | Improvement / New feature
| Category?      | FO

### CODE REVIEW

**Comment by Hlavtox** [comment]
@greatdesign Nice PR!

I have thought about this in the past, that the `Root` category (or whatever it is named) is missing from the breadcrumbs, but it will make the breadcrumbs very long on some shops or on product page. 🤔 But, if we make it configurable, it could be good addition. What do you think? :-)

root

Also, the root category doesn't have any breadcrumbs at all:

root2

### My proposal
- We should fix the breadcrumbs in the root category in the fist place. So, the breadcrumbs on `/2-rootcategoryname` look like `Home > RootCategoryName`.
- Add a configuration switch, if user wants to include the root category in subcategory breadcrumbs or not. It's few lines of code - check my other PR on how to do it - https://github.com/PrestaShop/PrestaShop/pull/29753
  - Switch name - `Show home category in breadcrumbs`, configuration key name `PS_BREADCRUMBS_HOME_CATEGORY`, helptext `If enabled, all category breadcrumbs will include a link to Home category of your shop.`

**Review by matks — COMMENTED** [review]
Hello @greatdesign as mentioned by prestonbot please fill the full PR table. These informations will be very useful for people to review your contribution 😉

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello @greatdesign 

Could you please create an issue + fix the errors reported by PHPtan?

**Comment by kpodemski** [comment]
Hello @greatdesign 

Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find and motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
