### PR TITLE
Update Employee.php

### PR DESCRIPTION
**Pull request by ghost**
No text information on personal data collection for employees

On install why not but for employees it's a joke !

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

thank you for your contribution, can you please explain why do you want to remove PrestaShop newsletter subscription ?

Best regards.

**Comment by julienbourdeau** [comment]
Hi,
You can uncheck this option so your new employee won't be subscribed. We will change the wording to replace "Connect to PrestaShop". This should be available soon.

**Comment by okom3pom** [comment]
Because we can't uncheck this option.
Tell me what you are going to serve the employees' email .
This is really a joke ...

where

**Comment by Eolia** [comment]
There is a big difference between "log on" and "opt-in" Here, you force to be registered on a newsletter list ...

**Comment by okom3pom** [comment]
I did not find method to unsucribe it's a fake uncheck
			
$language = new Language($this->id_lang);
			$params = http_build_query(array(
				'email' => $this->email,
				'method' => 'addMemberToNewsletter',
				'language' => $language->iso_code,
				'visitorType' => 1,
				'source' => 'backoffice'
			));
			Tools::file_get_contents('http://www.prestashop.com/ajax/controller.php?'.$params);

I tested a lot of combinations and not functioned. ( removeMemberToNewsletter delMemberToNewsletter deleteMemberToNewsletter  .... )
The code does not even exsite in www.prestashop.com/controller/ajax.php

Do not take me for a stroumph

**Pull request closed without merging**
