### PR TITLE
Cart rule modification

### PR DESCRIPTION
**Pull request by djbuch**
A response for : http://forge.prestashop.com/browse/PSCFV-8345
It is only added for percentage cart rules.

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by djbuch** [comment]
Hi,

ok I'll try to have a look at my PR and reply to it according your article.

Regards,
David

2015-11-05 17:44 GMT+01:00 Vincent Terenti <notifications@github.com>:

**Comment by vTerenti** [comment]
Ok thank you @djbuch !

Best regards

**Comment by kpodemski** [comment]
@djbuch :+1: for this PR, this is very wanted feature

**Comment by giorgiomancuso** [comment]
Thank you for your work. I have done two little modification to allow use of this code with a fixed amount discount and also not to consider the costs of specials products in the calculation of the minimum amount. If you want I can send you the sources

**Comment by djbuch** [comment]
Yes you could do so, I'll review it and create the new PR.

Regards

2015-11-12 15:05 GMT+01:00 giorgiomancuso <notifications@github.com>:

**Comment by giorgiomancuso** [comment]
Il 12/11/2015 15:08, David-Julian BUCH ha scritto:
> Yes you could do so, I'll review it and create the new PR.
>
> Regards
>
> 2015-11-12 15:05 GMT+01:00 giorgiomancuso <notifications@github.com>:
>
> > Thank you for your work. I have done two little modification to 
> allow use
> > of this code with a fixed amount discount and also not to consider the
> > costs of specials products in the calculation of the minimum amount. 
> If you
> > want I can send you the sources
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/PrestaShop/PrestaShop/pull/2060#issuecomment-156110249>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PrestaShop/PrestaShop/pull/2060#issuecomment-156110734>.
>
The modification of CartRule is around line 578

-- 
Giorgio Mancuso

Responsabile Tecnico ITACAD s.r.l.

Tel:     +39 011 7724858
Fax:     +39 011 7731722
Cell:    +39 335 6695959
www.itacad.it - www.caddy.it
email:   g.mancuso@itacad.it
Skype:   hotline_itacad

**Comment by xBorderie** [comment]
Hey @giorgiomancuso and @djbuch, glad to see you both collaborating on this!

**Comment by xBorderie** [comment]
Hey @djbuch! Did you find the time to upgrade your code? If so, could you make the PR on branch `1.6.1.x`?

Also, could you please follow these title guidelines? http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Thank you!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
