### PR TITLE
The t must be capital in namespace

### PR DESCRIPTION
**Pull request by chellem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The `t` must be capital
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by xBorderie** [comment]
I fixed the description for you.
Is there a way you could amend your commit's name?
Thank you!

**Comment by aleeks** [comment]
@xBorderie done

**Comment by chellem** [comment]
@xBorderie Thank you 👍

**Comment by aleeks** [comment]
just done for all files..

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thanks @chellem & @aleeks

**Pull request merged**
