### PR TITLE
Fix bug alignment sidebar menuCollapse Admin theme

### PR DESCRIPTION
**Pull request by vincent8balls**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Alignment of the sidebar menuCollapse in the Admin Theme. (not in the middle)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Check admin sidebar of PrestaShop

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8529)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by marionf** [comment]
Hello @vincent8balls 
Can you add a screenshot with the issue to explain what do you solve ?
It will help me to test your PR.
Thanks !

**Review by Quetzacoalt91 — APPROVED** [review]
@alegout, this PR could go with yours (#8637)

**Comment by Quetzacoalt91** [comment]
@marionf 

Here are the changes (tested with the new menu from @alegout):

### Without PR
capture du 2018-01-08 11-06-30

### With PR
capture du 2018-01-08 11-06-50

Seeing the changes is difficult, but on the second screenshot, the collapse icon has been moved slightly on the left.

**Comment by mickaelandrieu** [comment]
Thanks @vincent8balls !

**Pull request merged**
