### PR TITLE
[*] CORE : You can now search with filter by category

### PR DESCRIPTION
**Pull request by wellic**
Added ability to filter products by category into the method Search::Find. This allows to make the search more flexible using the id_category the same as in Products::getProducts.

Fixed after commetns in pull request #4364.

### CODE REVIEW

**Comment by wellic** [comment]
Is it necessary to prepare some pull-requests for the branch 1.6, 1.6.1?

**Comment by wellic** [comment]
I've added posibility filter by list ids' categories.

**Comment by wellic** [comment]
Ping. 
I think it is useful feature.
It extends the search functionality significantly because the search returns too many not needed results.
Plus the old search behavior stays the same and it is compatible with earlier versions.

**Comment by Mooty13** [comment]
Searching by ID ?
I don't think this is relevant actually. You modify behavious of Find function. After chatting with Prestashop Team last week they don't want to modify such things, as it's (in continuous integration perspective) a way to create bugs.

NB : I'm not a PS team member, this comment is my only opinion.

**Comment by wellic** [comment]
Id uses as a additional filter.

**Comment by aleeks** [comment]
Hello @wellic 
I'm closing this PR after discussion with the team.
If we accept this PR, we can do the same for brand, supplier, etc, etc.
Moreover, searching by ID (category, brand or other) isn't the best way to find a product (find like research engine) with words.

Regards

**Pull request closed without merging**
