### PR TITLE
ShopConstraint parameter is deprecated since version 1.7.8.0 

### PR DESCRIPTION
**Pull request by Pierpaolo-Amarante**
description: Hi and my first pull request, forgive me if I do something wrong. I have prestashop 1.7.8.7 in which I have the logs file full of the optional deprecated ShopConstraint parameter is obsolete from version 1.7.8.0 public_html / src / Adapter / Configuration.php: 418.
How can I solve?
My environment
PS 1.7.8.7
Apache Version 2.4.54
PHP Version 7.4.30
extension = php_mysql.dll
extension = php_gd2.dll
allow_url_fopen = On
allow_url_include = Off
realpath_cache_size = 4096k
realpath_cache_ttl = 600
short_open_tag = off
display_errors = Off
max_execution_time = 300
max_input_time = 300
max_input_vars = 20000
memory_limit = 512M
post_max_size = 128M
session.gc_maxlifetime = 1440
session.save_path = "/ var / cpanel / php / sessions / ea-php74"
upload_max_filesize = 128M
zlib.output_compression = Off

type:
category: BO

### CODE REVIEW

**Review by yanmakouf — COMMENTED** [review]
Hello @Pierpaolo-Amarante and thank you for using Prestashop :-) I think there's a confusion on how to report your problem. As I can understand, what bother you is a warning on ShopConstraint in your logs. You should create an issue. A pull request fixes an issue. Here you just ask to fix a problem :) You can check the guidelines here : https://devdocs.prestashop-project.org/1.7/contribute/contribute-reporting-issues/

**Comment by Pierpaolo-Amarante** [comment]
hi @yanmakouf,
thanks for your reply.
Forgive my inexperience and the first time for me. Read the guide you sent me, do you think you need to open a request or are they normal logs?

**Comment by matthieu-rolland** [comment]
I think the trigger_error should be a trigger_deprecated...

**Comment by yanmakouf** [comment]
Hello @Pierpaolo-Amarante,

No worries ;) 

Several things. 

If you notice a bug/problem you can either contact the community through forums, slack, or on github (through an issue as described in the documentation I shared with you).
So we will close this pull request.

This log is normal a deprecation notice, meaning that in the next major Prestashop with no longer support calling buildShopConstraintFromContext() function without the ShopConstraint parameter. The same thing actually exist in version 8, so this will be removed in version 9.
Although as @matthieu-rolland said the log level is wrong and it shoulf be logged as a warning and not an error. So ultimately you could try to open an issue to change that. 

Anyway it is normal and you keep having this log for a while (unless you decide to remove it in your own prestashop application)

**Comment by atomiix** [comment]
@Pierpaolo-Amarante even though they are just deprecation logs, I think we should try to get rid of them as much as possible. You can open an issue ;)

**Comment by Pierpaolo-Amarante** [comment]
Hi @atomiix, ok I'll open the problem today

**Comment by atomiix** [comment]
Closing this PR then ;)

**Pull request closed without merging**
