### PR TITLE
Add IE11 support to FO webpack

### LINKED ISSUE #26988: PrestaShop 1.7.8 is no longer compatible with the IE browser
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello,

PrestaShop 1.7.7 working correctly in the IE browser and console is clear:
https://i.imgur.com/j6CFZxA.png

but in PrestaShop 1.7.8 the quick view doesn't work, I also can't add product to the cart and other thing related to .js code doesn't work.
In the console I see these js errors:
https://i.imgur.com/R6GQw23.png

Probably something is broken in the core.js file.

### Expected behavior

_No response_

### Steps to reproduce

1.Open PrestaShop 1.7.7 in the IE browser to see that everything is ok.
2.Open PrestaShop 1.7.8 in the IE browser to see .js errors in the console and not working elements in the default frontoffice theme.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Babel wasn't supporting IE11
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26988.
| How to test?      | Try to use classic with IE11 (this pr aim only javascript, don't care about CSS problems)
| Possible impacts? | IE11 use of classic

⚠️ I had a problem with the add to cart action, please take care of it when testing @PrestaShop/qa-team 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26995)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG You have 2 approvals but we can't send it to QA without all the CI is green

**Comment by NeOMakinG** [comment]
> Details

Yeah but CI fails because of addons 😆

**Review by matthieu-rolland — APPROVED** [review]

**Comment by jf-viguier** [comment]
IE11 will be supported by prestashop ? It's not in this list https://devdocs.prestashop.com/1.7/themes/getting-started/guidelines/#html--css--javascript

**Comment by NeOMakinG** [comment]
> IE11 will be supported by prestashop ? It's not in this list https://devdocs.prestashop.com/1.7/themes/getting-started/guidelines/#html--css--javascript

It's not really supported, I think we gave up some months ago, but as classic and the BO is using bootstrap 4, it's indirectly supported

I did in the issue that I was making an effort for this 😆

**Comment by NeOMakinG** [comment]
But passing june 2022, I won't care anymore

**Comment by HanaRebaiQA** [comment]
Hello @NeOMakinG 

I have tested this PR. The issue is fixed.
I verified in different pages of products in FO also with multistore.

See screen-record below : 
https://watch.screencastify.com/v/DHtA9Tt6OXHyMUpLu6Cz

So, QA :heavy_check_mark: 

**PS** : A lot of issues / regressions has been detected related to IE11 but not related to this PR.

Thanks!

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Comment by NeOMakinG** [comment]
> Hello @NeOMakinG
> 
> I have tested this PR. The issue is fixed. I verified in different pages of products in FO also with multistore.
> 
> See screen-record below : https://watch.screencastify.com/v/DHtA9Tt6OXHyMUpLu6Cz
> 
> So, QA ✔️
> 
> **PS** : A lot of issues / regressions has been detected related to IE11 but not related to this PR.
> 
> Thanks!

We shouldn't mind too much about IE11 honestly, too much efforts for something out of support in 5 months

**Pull request merged**
