### PR TITLE
FIX Exception when adding a new discount with invalid amount - invalid discount

### LINKED ISSUE #17747: Exception when adding a new discount with invalid amount - invalid discount
**Describe the bug**
In the BO => Orders => new migrated Order details page or legacy page when we add a new discount with an invalid amount for example `-10` => an exception is displayed

**To Reproduce**
1. Go to BO => Orders => new migrated Order details page `admin-dev/index.php/sell/orders/orders/5/view` or the legacy page
2. Click on "Add a new discount" button
2.1. Type = Amount
2.2. Value = -10
3. Click Add
image
image

**Additional information**
PrestaShop version: 1.7.7.x, 1.7.6.3, 1.7.5.2
PHP version: 7.1

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | An exception was thrown when adding a negative amount/percentage in an order view. This PR fixes it by showing an error message.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17747 for PS1.7.6.3 and PS1.7.5.2
| How to test?  | In BO on the legacy order page `/index.php?controller=AdminOrders&vieworder&token=xxx&id_order=xxx` dd a new discount with an invalid amount for example -10 => an exception is displayed

The idea of ​​my PR is to keep the same behavior present on AdminCartRules (with the same error messages and validation conditions) see  : 

-  https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/controllers/admin/AdminCartRulesController.php#L217 
- https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/controllers/admin/AdminCartRulesController.php#L220

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17874)

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
Hi @PululuK , thank you for your contribution 👍 

Is this PR for the 1.7.6.x branch ? It seems like you are basing it on develop.

**Comment by PululuK** [comment]
> Hi @PululuK , thank you for your contribution +1
> 
> Is this PR for the 1.7.6.x branch ? It seems like you are basing it on develop.

Hi @matthieu-rolland thank you ... in fact, this PR is for PS1.7.6.3 and PS1.7.5.2. In this case i'm not sure where to do my PR. Can you help please ? I'm too old for that ...

**Comment by LouiseBonnard** [comment]
Hi @PululuK, thanks a lot for your contribution here! We have already suggested a fix with PR #17852. Can you please check it and confirm that it is the same so that I can close this one? :-)

**Comment by PululuK** [comment]
> Hi @PululuK, thanks a lot for your contribution here! We have already suggested a fix with PR #17852. Can you please check it and confirm that it is the same so that I can close this one? :-)

Hi @LouiseBonnard ... Thank you !
The patch proposed by @atomiix  only concerns PS 1.7.7.X. My PR fixes #17747 for PS1.7.6.3 and PS1.7.5.2

Can you check please ?

**Comment by LouiseBonnard** [comment]
Right, thanks @PululuK! We've just released [PrestaShop 1.7.6.4](https://build.prestashop.com/news/prestashop-1-7-6-4-maintenance-release), and this fix is planned for forthcoming version 1.7.7, so I'm afraid we might not merge it for now. But, that said, we keep it in mind and will merge it if we plan to release a new 1.7.6.x patch.

**Comment by PululuK** [comment]
> Right, thanks @PululuK! We've just released [PrestaShop 1.7.6.4](https://build.prestashop.com/news/prestashop-1-7-6-4-maintenance-release), and this fix is planned for forthcoming version 1.7.7, so I'm afraid we might not merge it for now. But, that said, we keep it in mind and will merge it if we plan to release a new 1.7.6.x patch.

OK, thanks ! On the other hand I have just updated my username git, could you also update this article https://build.prestashop.com/news/prestashop-1-7-6-4-maintenance-release/ and this file https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/CONTRIBUTORS.md please? **PululuK** instead of **PK André**

**Comment by LouiseBonnard** [comment]
Hi @PululuK, just to keep you posted, the decision has been made not to add this fix to the next 1.7.6.x patch version since it will be part of PrestaShop 1.7.7. In short, here is why:

1. a patch version should **only correct critical bugs and security issues** and this fix is neither a regression nor a critical bug

2. this fix will be made **available in the future minor version** of PrestaShop, users will be able to benefit from this correction so we consider it fixed

I'm sorry we cannot merge your contribution this time, thank you anyway. I add the _No change required_ label and close it. :-)

**Comment by PululuK** [comment]
> Hi @PululuK, just to keep you posted, the decision has been made not to add this fix to the next 1.7.6.x patch version since it will be part of PrestaShop 1.7.7. In short, here is why:
> 
>     1. a patch version should **only correct critical bugs and security issues** and this fix is neither a regression nor a critical bug
> 
>     2. this fix will be made **available in the future minor version** of PrestaShop, users will be able to benefit from this correction so we consider it fixed
> 
> 
> I'm sorry we cannot merge your contribution this time, thank you anyway. I add the _No change required_ label and close it. :-)

Hi @LouiseBonnard 

I understand perfectly !

Thanks you

**Pull request closed without merging**
