### PR TITLE
Fix notifications color contrast on module manager page

### LINKED ISSUE #28053: Low contrast in notification-counter
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Is your feature request related to a problem?

`.notification-counter` in files `admin\themes\new-theme\public\main.css` and `admin\themes\new-theme\public\theme.css` uses background `#f1b746` with white font color. This produces low conrast.

Darker color, e.g. orangered for background or black for text should be used to enhance readability.

See attached image with original bg and orangered as bg
nimetön

Original bg with black text gives even better contrast.

### Describe the solution you'd like

Contrast should be better for readability.
In `admin\themes\new-theme\public\main.css`, search for
```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem
}
```

1. Change to:

```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem; 
   color:black;
}
```
2. Or to:

```
.notification-counter{
   position:absolute;
   top:0.25rem;
   right:0;
   display:inline-block;
   padding:0 0.1875rem;
   font-size:0.625rem;
   line-height:0.75rem;
   color:#fff;
   background:#f1b746;
   border:0.125rem solid #fff;
   border-radius:1rem;
   top:-1.75rem;
   right:-0.9375rem; 
   color:black;
   font-weight:bold;
}
```

3. or some other bg / color combination that produces good contrast.

### Do you plan to work on this feature?

- [] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Numbers were unreadable on the module manager page because of a contrast issue
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28053.
| How to test?      | See issue
| Possible impacts? | Nothing except readability of notifications number on module manager

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28226)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by MeKeyCool — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @NeOMakinG ,

Thanks for the PR.

I have 2 different colours on the BO : 
- On non-migrated page I still have the yellow notification on the top-right bell icon 🚫 
- On migrated page, it is OK.

https://user-images.githubusercontent.com/16019289/164206066-1de5d783-5650-43ff-a826-2e1f93a5c5ac.mov

Could you check ?
Thanks!

**Review by matks — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by MeKeyCool — DISMISSED** [review]

**Comment by TristanLDD** [comment]
Hi, the new notification color expected is #f44336 to match the UI kit guidelines. Thank you!

**Review by florine2623 — COMMENTED** [review]
Hello @NeOMakinG ,

On migrated pages I have : #f54c3e
Screenshot 2022-04-29 at 10 35 49

On old pages I have : #e08f95
Screenshot 2022-04-29 at 10 35 04

It should be :  #f44336


Could you check ?

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
@NeOMakinG ,

Looking good ! It is QA ✅

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @florine2623

**Pull request merged**
