### PR TITLE
Update twig dependency

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Update twig dependency
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Comment by jolelievre** [comment]
Automatic campaigns are run here:
- PHP 7.3 Node 14 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3322808613
- PHP 7.4 Node 14 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3322798353
- PHP 8.0 Node 16 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3322812823

**Review by yanmakouf — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
I add documentation label to mark this in developer doc

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
It's all good for me. the workflow is not working with php7.3, but that is a problem with the workflow.
So QA :heavy_check_mark:

**Comment by matthieu-rolland** [comment]
thanks @jolelievre and @boubkerbribri !

**Comment by thomasnares** [comment]
You can remove label "needs-documentation" @matks

**Pull request merged**
