### PR TITLE
Show discount to cart summary

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.5
| Description?  | Show discount to cart summary
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2135
| How to test?  | create discount, add product & see your cart 

cart

### CODE REVIEW

**Review by maximebiloe — APPROVED** [review]

**Comment by aleeks** [comment]
See: https://github.com/PrestaShop/StarterTheme/pull/162

**Comment by aleeks** [comment]
ping  @fatmaBouchekoua

**Comment by dSkrbic** [comment]
Hello, Q&A test NOK:
1-When adding a product in cart, discount is still not visible
2-When adding again the same product, the cart is broken (see attached animation)

**Comment by AntoineMille** [comment]
@aleeks, please need to rebase

**Comment by aleeks** [comment]
@AntoineMille WIP, @fatmaBouchekoua is on this problem.

**Comment by Pixomaniak** [comment]
This bug is still there on 1.7.0.5, why this pull request has not been integrated ?

**Comment by aleeks** [comment]
Hello, it's not complete yet.. 😥

**Pull request closed without merging**
