### PR TITLE
Delete parameters.yml.travis

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Duplicate of `.github/workflows/phpunit/parameters.yml`, the Travis conf is no longer used.
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | GH CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22967)

### CODE REVIEW

**Comment by matks** [comment]
As indicated by CI report, this file was still being used although the name is indeed outdated. We might update the naming/location of the file? 😉

**Comment by mvorisek** [comment]
> 
> 
> As indicated by CI report, this file was still being used although the name is indeed outdated. We might update the naming/location of the file? 😉

Now fixed, there was one usafe of the old Travis conf for static phpunit tests.

**Review by matks — APPROVED** [review]
Great idea !

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @mvorisek

**Pull request merged**
