### PR TITLE
Allow 255 char to company field in Adress

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Company field in Address doesn't allow more than 64 char.
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8949
| How to test?  | Reinstall your shop and try to add new Address with a long name of company

### CODE REVIEW

**Review by aleeks — CHANGES_REQUESTED** [review]
Hello @fatmaBouchekoua 
Create a file upgrade 1.6.1.13.sql please & make your request !

**Comment by fatmaBouchekoua** [comment]
Done. Thanks !

**Comment by kpodemski** [comment]
I'm ok with this change but are we sure that it can be part of path version? @xBorderie

**Review by aleeks — APPROVED** [review]

**Comment by aleeks** [comment]
When it will be merged, please, : 

- add your sql script to 1.7.0.x
- change db structure on `develop` branch

**Comment by maximebiloe** [comment]
@kpodemski we know it shouldn't be embedded in a patch version, but it's a really minor change, so we'll make an exception for this one.

Thank you @fatmaBouchekoua

**Comment by Mreker** [comment]
I want to apply this fix for my website without upgrading Prestashop to newest version. Do I just run this code in SQL on my database?
```
SET NAMES 'utf8';

ALTER TABLE `PREFIX_address` CHANGE `company` `company` VARCHAR(255) DEFAULT NULL;
```
and replace code in classes/Address.php?

I am not familiar with SQL, therefor I ask, so I don't mess something up.

**Comment by aleeks** [comment]
Hello @Mreker 
Yes, you have to, just replace `PREFIX_` with your prefix database :)
It should be work

Regards

**Comment by aleeks** [comment]
@fatmaBouchekoua 

Can you please : 
- add your sql script to develop branc
- change db structure on develop branch

**Pull request merged**
