### PR TITLE
Fixed free gifts not displaying correctly on cart

### PR DESCRIPTION
**Pull request by tantan199**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  |  Free gifts are not displayed correctly on cart, their prices show out, their quantities are adjustable. The "cart" variable from the initContent function in the controller/front/CartController.php always get overridden by another "cart" variable from the assignGeneralPurposeVariables function in the /classes/controller/ProductListingFrontController.php, the first "cart" variable contains information of free gifts, but the second one doesn't. It's also not cool to assign the same "cart" variable twice on the shopping cart page. BTW the "cart" variable in the "Shopping cart" module also doesn't have information of free gifts. The fix is a temporary one, hope someone could find a better one.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4701
| How to test?  | Create a cart rule to add a free gift to all products, and then go to FO to add a product to cart to see the bug.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8706)

### CODE REVIEW

**Review by LittleBigDev — DISMISSED** [review]
LGTM

Thank you @tantan199

**Comment by marionf** [comment]
Hello @tantan199 

We can improve the behaviour:
- by removing the trash next to the promo code that doesn't work
- by not adding the amount of the gift product in the cart
- by removing the amount of the gift product

capture du 2018-02-20 11-25-39

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Rebased on `develop`.

@marionf, although the requested improvement won't be done here, does this PR fixes an issues which makes it mergeable?

**Comment by marionf** [comment]
@tantan199 

I should see the gift in the cart, but I don't

capture d ecran_244

**Comment by marionf** [comment]
Hello @tantan199 

Since we have not had answer for more than 30 days and this PR doesn't fix the issue as expected, I close it
Feel free to open a new one if needed

**Pull request closed without merging**
