### PR TITLE
Wrong discount subtotal when customergroup is set to use ex taxes

### LINKED ISSUE #13658: Regression on price calculation in FO
**Describe the bug**
Regression on price calculation in FO when you have cart rules and specific display price in customer group

**To Reproduce**
Scénario 1:
1. Set your customer group to display price tax excl
2. Create a cart rule of 10%
3. Create a product of 10€ tax excl, 20% TVA
4. Total tax excl is 8.80 instead of 9
5. Amount of tax incl is 2 instead of 1.80€

Scénario 2:
1. Set your customer group to display price tax incl (by default)
2. Create a cart rule of 1€ tax incl
3. Create a product of 10€ tax excl, 20% TVA
4. Total tax incl is 12 instead of 11
5. Amount of tax incl is 2 instead of 1.83€

Scénario 3:
1. Set your customer group to display price tax incl (by default)
2. Create a cart rule of 10%
3. Create a product of 10€ tax excl, 20% TVA
4. Amount of tax incl is 2 instead of 1.80€

**Screenshots**
https://docs.google.com/spreadsheets/d/1y-4p2cIDeIF9SIxVPUtZ604OJutLDHVu9uPpoE1QirE/edit#gid=0

**Additionnal information**
PrestaShop version: 1.7.6.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | from https://github.com/PrestaShop/PrestaShop/pull/13632 : Wrong discount subtotal when customergroup is exc taxes
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13658 #11360 #9856
| How to test?  | Set in customergroup price without taxes the discount subtotal in the cart is always displayed including taxes as seen in the previous code. Now the variable inc or ex taxes is passed to getDiscountSubtotalWithoutGifts resulting in correctly displaying the discount subtotal in the shopping cart

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13684)

### CODE REVIEW

**Comment by tomlev** [comment]
previous PR: https://github.com/PrestaShop/PrestaShop/pull/13632
this branch was created after a wrong rebase on 1.7.6.x

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @tomlev

**Comment by tomlev** [comment]
thanks @venditdevs ;)

**Comment by venditdevs** [comment]
@tomlev , sorry;) We had some 1.6 to 1.7 migration issues with a customer of ours that needed our dedicated attention. Thanks for merging the fixes!

**Comment by idnovate** [comment]
@tomlev I think there's still a wrong case:

image

image

image

The problem is in function `getTemplateVarVouchers` from `CartPresenter`:

```
// Voucher reduction depending of the cart tax rule
// if $cartHasTax & voucher is tax excluded, set amount voucher to tax included
if ($cartHasTax && $cartVoucher['reduction_tax'] == '0') {
    $cartVoucher['reduction_amount'] = $cartVoucher['reduction_amount'] * (1 + $cartHasTax / 100);
}
```
This `if` is evaluated as false, but `$cartVoucher['reduction_amount']` is 1€ (in my example). Taxes should be removed.

**Comment by idnovate** [comment]
And also this one:

image

image

image

**Comment by venditdevs** [comment]
Will try to look at it in the coming weeks.

**Comment by marionf** [comment]
@venditdevs [the issue posted by idnovate](https://github.com/PrestaShop/PrestaShop/issues/13748) is already fixed by https://github.com/PrestaShop/PrestaShop/pull/13780

**Pull request merged**
