### PR TITLE
Add order status info in exception message

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add order status info in exception message.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | N/A
| Fixed ticket?     | N/A
| Related PRs       | N/A.
| Sponsor company   | PululuK.

### CODE REVIEW

**Review by lartist — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by mflasquin** [comment]
Hello @PululuK maybe you can add a "how to test" section to help QA ? :smile:

**Comment by FabienPapet** [comment]
Maybe this needs a wording update ? ping @l-delin

**Comment by l-delin** [comment]
Hello, could I get more info? I'm not sure what's going on here @PululuK

**Comment by kpodemski** [comment]
Since we have had no news from you for over 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
