### PR TITLE
Adding review page check

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  This PR allows to check the created page Preview
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run the script path=full/15_design/2_pages/* npm run specific-test -- --URL=BackOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9148)

### CODE REVIEW

**Comment by fouratachour** [comment]
Hello @marionf 
This PR has been rebased
Best regard,

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
This PR need to be rebased again :)

**Comment by fouratachour** [comment]
@PierreRambaud 
Done .

**Review by fatmaBouchekoua — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @fouratachour

**Pull request merged**
