### PR TITLE
For a shop with 10K products, search index will stop working correct.

### PR DESCRIPTION
**Pull request by astterx**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | For a shop with 10K products, search index will stop working correct. Unsigned INT max value will be reached.
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Install a new instance of Prestashop.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9240)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @jocel1, wdyt? is it worth?

**Comment by jocel1** [comment]
I think it needs to be investigated more thoroughly. There're not so many existing id_word, so perhaps the autoincrement counter needs to be reset using ```ALTER TABLE PREFIX_search_word auto_increment=1``` after the ```TRUNCATE '._DB_PREFIX_.'search_word'``` in Search.php during the full reindex process. (innodb doesn't always reset autoincrement after a TRUNCATE)
@astterx could you try with this method?

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Still waiting for investigation.

**Comment by matks** [comment]
Hi, [following our review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

Since we did not get answer from author I close this PR.

Please note this does not mean it's a final "won't merge" 😉 if you come back we can reopen it

Thank you for the contribution

**Pull request closed without merging**
