### PR TITLE
Fixed Sort by price in FO with specific price

### LINKED ISSUE #17212: Wrong sort price and/or product limit/offset on listing page
**Describe the bug**
On category page (without ps_facetedsearch), search page, manufacturer page, supplier page, new products page, prices drop page:
When sort by low price, a product of second page (without its reduction) should be on the first page (with its reduction)
>Edit by Khouloud

Steps to reproduce the issue:
1. Disable ps_facetedsearch module
2. Edit the Product "Hummingbird printed sweater" => specific price = 50%
image

3. Go to the FO => Home page
4. sort by price from low to high 
5. Go to the next page
6. See error

https://drive.google.com/file/d/1uVy8vx_z1HrEqELEBx-GMKy3odytXClU/view
**To Reproduce**
1. Add a specific price on a product.
2. Sort any listing page except bestsellers page by price.
3. Use pagination.
4. See error: wrong order

### PR DESCRIPTION
**Pull request by soulardromain**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Search page: fix sort price using Tools::orderbyPrice function and array_slice for pagination. Category page, manufacturer page, supplier page, new products page, prices drop page: fix sort price using array_slice for pagination. I based on the best sales page.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17212
| How to test?  | Add a specific price on a product and sort any listing page except best sales page and use pagination.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16698)

### CODE REVIEW

**Comment by matks** [comment]
Hi @soulardromain 

First of all, thanks for modifying these nasty SQL queries 😅must not have been fun

However I'm worried that it could not scale. In your PR you perform the pagination yourself, you replace the `LIMIT` SQL statement by a PHP processing. This means all data, and there can be a lot of categories / products ina shop, is put inside php memory.

I dont think this can be done this way 🤔.

**Review by Progi1984 — DISMISSED** [review]

**Comment by 23Stephan23** [comment]
Hello,

Tested on PS 1.7.6.4

Pagination work better but products are sorted by original prices and not by discounted prices :(

orderbyprices

**Comment by Progi1984** [comment]
@soulardromain Have you seen the @23Stephan23 feedback ?

**Comment by LouiseBonnard** [comment]
Hi @soulardromain, any news on this?

**Comment by soulardromain** [comment]
Hi

I'm sorry I didn't have time to watch.
Maybe this month.

Le mer. 7 oct. 2020 à 15:28, LouiseBonnard <notifications@github.com> a
écrit :

**Comment by soulardromain** [comment]
Hello @23Stephan23,
I tested on 1.7.6.4 and it works fine for me.
What type of page have you tested? has the faceted search module been uninstalled?

**Comment by soulardromain** [comment]
Hello @23Stephan23,
I tested on 1.7.6.4 and it works fine for me.
What type of page have you tested? has the faceted search module been uninstalled?

**Comment by Progi1984** [comment]
@soulardromain Could you allow edit for maintainers, please ?

image

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Roomsmaniia** [comment]
LGTM,

Thanks @soulardromain

**Comment by Progi1984** [comment]
Thanks to 2 Romain : @soulardromain & @RomainBocheux

**Pull request merged**
