### PR TITLE
Fix init method not existing in module_card

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | There was an error when you click on "Recommended module" on the top right caused by one file and blocking a PR of ps_mbo module
| Type?         | bug fix
| Category?     | BO
| BC breaks?    |  no
| Deprecations? | no
| How to test?  | Go on a legacy page, click "Recommended module" on top right. Everything should works fine

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18554)

### CODE REVIEW

**Comment by Matt75** [comment]
Great 🥳
Resolve https://github.com/PrestaShop/ps_mbo/pull/89#issuecomment-579801566
Will be backported on MBO

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

In the BO => International => Locations => Countries Tab => When I click on the "Recommended Modules" => it is loading without any result and I have an exception in the console.
I tried to delete the cache => same issue.
image

Thanks!

**Comment by NeOMakinG** [comment]
@Matt75 an idea about this ? Looks not related to this PR

**Comment by Matt75** [comment]
@khouloudbelguith This is not related to this Pull Request, error is in MBO module.
Will be fixed with v2.0.0 soon.

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is OK :heavy_check_mark: 

@Matt75, for your information, same exception in those pages:
1. Countries list page
2. Add new country page
3. Taxes rule list page
4. Add new tax rule page
5. Tags list page
6. Add new tag page

Thanks!

**Comment by Matt75** [comment]
@khouloudbelguith Yes, alls fixed with v2.0.0, thanks for report 👍

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

**Pull request merged**
