### PR TITLE
Fix manufacturers grid logo to not depend from shop context

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Changed source path of list logo image (this image is still taken from `img/tmp`, however  now it doesn't depend from shop id). Example of previously taken image path: `img/tmp/manufacturer_1_2.jpg` (first number stands for manufacturerId, second was the shopId), changed to: `img/tmp/manufacturer_1.jpg` (only the id). This Pr intends only fixing the bug. The code should be optimized in following versions by joining some common image parsing/uploading methods.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | Changed cached image name which is used to render image in grid, but it shouldn't be a problem.
| Fixed ticket? | #14299
| How to test?  | Overall manufacturers page shouldn't change, images should be rendered as before. Some behavior regarding multishop should be fixed. Refer the issue #14299 for more info. 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14307)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by zuk3975** [comment]
Could someone please rerun travis? :pray:  It doesn't look like PR has anything to do with its failing.

**Comment by PierreRambaud** [comment]
@zuk3975 In progress! 🤞

**Comment by matks** [comment]
@zuk3975 Can you target `develop` ?

**Comment by PierreRambaud** [comment]
Thanks @zuk3975

**Pull request merged**
