### PR TITLE
Disable legacy_feature_flag for migrated feature page

### LINKED ISSUE #31821: Attributes & Features > Features list actions not working
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments
image

Features list is migrated horizontally and is not compatable with recently merged legacy_feature_flag, so when you enable experimental migrated feature page the list actions aren't working. 
There is also one related error - Even when "new features page" is disabled, when you go to features list and open up edit action from list, you can see that it opens up the new migrated edit page. (it should open old one). To differentiate legacy and new pages you can just see that in new page there is a symfony debug toolbar at the bottom of the screen (as well as the link is different new being `/sell/catalog/features`, old something like `/index.php?controller=AdminFeatures`...)

### Expected behavior

As horizontal migration approach was cancelled as inefective and there is already PR to merge list vertically, it would be wise just to disable the feature in 8.1 and wait to be fixed in develop branch. So from UX point of view, merchant should not have the option to enable new "features" page and always see a working legacy features page.

### Steps to reproduce

issue1:
1. Go to BO new & experimental features and enable "Features" toggle.
2. Go to Sell > Catalog  > Attributes & Features > Features
3. Check that list actions are not working. (clicking view/edit or delete juts redirects back)

issue2:
1. Go to BO new & experimental features and disable "Features" toggle.
2.  Go to Sell > Catalog  > Attributes & Features > Features
3. Click on edit action and see that it opens up a new features page, while it should open legacy one. (explained how to differentiate between new and legacy page in description above)

### PrestaShop version(s) where the bug happened

8.1.x, develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/31821. No bc breaks and upgrade is not needed because this feature_flag for feature page was introduced just recently in 8.1.x and wasn't yet released.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Requires reinstalling your shop locally (because feature flags are saved in database during install.) For how to test refer to https://github.com/PrestaShop/PrestaShop/issues/31821
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/31821
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
LGTM. Does it require autoupgrade PR?

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

**Comment by zuk3975** [comment]
> LGTM. Does it require autoupgrade PR?

I don't think so, it wasn't yet released

**Comment by jolelievre** [comment]
@kpodemski indeed, I think many feature flags haven't been integrated in autoupgrade yet, we'll need to check the whole list once this one is merged to make sure they are all correctly added

The ones related to new features (PPV2, API, Images) should already be there, but not the ones we added that are related to migration in progress

**Review by djoelleuch — APPROVED** [review]
Hello @zuk3975 ,
I have checked this PR , it LGTM .
Automated tests --> OK 


[Untitled_ Mar 21, 2023 3_38 PM.webm](https://user-images.githubusercontent.com/115152460/226642100-2f0b0bf5-29ce-4033-8465-b5d32ef198a0.webm)



[Untitled_ Mar 21, 2023 3_39 PM.webm](https://user-images.githubusercontent.com/115152460/226642142-f22d7f41-1953-410f-8abc-141054136230.webm)



The issue is well fixed . :rocket: 
Thank you !

**Comment by nicosomb** [comment]
Thank you @zuk3975

**Pull request merged**
