### PR TITLE
Removed deprecated in Carrier class

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | 
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Relative to #26293
| How to test?      | Nothing to test.
| Possible impacts? | BC break : remove usage of SHIPPING_METHOD_DEFAULT

### CODE REVIEW

**Review by matks — APPROVED** [review]
Some code that was there since 1.5 😄  ? Let's get rid of that 👍

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Waiting for automated tests from QA. Thanks @jf-viguier

**Review by AureRita — APPROVED** [review]
Hi @jf-viguier ,

Thank for your PR, I launched an automated regression tests and it seems good

**Comment by Progi1984** [comment]
Thanks @jf-viguier & @AureRita

**Pull request merged**
