### PR TITLE
Use 'npm ci' instead of 'npm i'

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Use `npm ci` instead of `npm i` in CI processes and update README's to use it also. See: https://docs.npmjs.com/cli/v9/commands/npm-ci
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check that CI goes green
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

As a side note I think all of the `Setup NPM` steps can be omitted as `actions/setup-node@v3` already sets up npm (I think)

And the node version should really come from one single source of truth for future, but lets keep this iterative :)

### CODE REVIEW

**Review by boubkerbribri — APPROVED** [review]
LGTM for me.
But something is wrong with the CI if someone can check it.

**Review by FabienPapet — APPROVED** [review]

**Comment by tswfi** [comment]
> LGTM for me. But something is wrong with the CI if someone can check it.

Either someone did something or the CI fixed itself.

I can take a look at the `npm install` step if this gets merged.

**Comment by boubkerbribri** [comment]
The only test that can be done is to run `make install` to see if the theme is working but it's already done on the CI, @PrestaShop/qa-functional we can merge it.

**Comment by boubkerbribri** [comment]
Thanks @tswfi

**Pull request merged**
