### PR TITLE
[*] Project : Re-design Order View

### PR DESCRIPTION
**Pull request by PhpMadman**
This is the first draft on the order view based on #3296 

There are still some issues, I havent found a soultion to.

It was also suggested to move the status to it's own panel. I did to that, but tweeked it a bit.
See screenshoot in next comment.

**Known Issues**
~~Product tab is blank at load, switching tab loads it.~~
~~Products kpi linkd does not work if not on product tab. ?JS to switch tab?~~ Room for code improvment?
~~Status select does not get proper width~~
~~Message select does not get proper width~~ - Code improvment?
~~Hooks are badly placed~~
~~Linked orders tab is always shown~~
~~Responsive design does not work correctly~~
Customer Private note textarea is only one line high - Beacuse it's hidden, it gets 0. V1 of autosize dosent seem to have and update featureas v2 does.
~~x = delivery_map.getZoom(); Causes an TypeError: delivery_map is undefined when switching between invoice / delivery address tabs.~~

**Ideas**
~~Move payment to it's own tab~~
~~Move Print order / View Invoice / Delivery etc buttons to above the tabs, sho they always show.~~
~~Move Status above tab panel, under kpi~~
~~displayAdminOrder should be moved to it own "Extra" tab~~
~~displayAdminOrderLeft/Right could get own tabs or a own panel beneth the tabView~~
Add a new 2-part hook system like displayAdminOrderTabOrder to add tab and content to tabView
~~Add #3591~~

### CODE REVIEW

**Comment by PhpMadman** [comment]
taborderview-2

**Comment by PhpMadman** [comment]
taborderview-3

**Comment by PhpMadman** [comment]
KPI link fixed.
minor design fix on products content.

**Comment by PhpMadman** [comment]
Tabs now also have icons

**Comment by PhpMadman** [comment]
Added #3442
Fixed hooks
Fixed msg select with - Find a better way to do it?

**Comment by PhpMadman** [comment]
Rebased to get up to date.

I need some help. I need to fix the responsive parts now. But I have no idea where to start.
Any pointers / tips / ideas?

**Comment by PhpMadman** [comment]
Figuerd out how to work sass and compile.
Added view fixes for screen-phone.
Then it's only $screen-tablet left, or is it nessary to add for screen- lg / tiny / small / xs / sm ?

**Comment by PhpMadman** [comment]
tablets don't need any fixes.

This thing is finally ready to be merged / tested

@syswarren @jeromenadaud

**Comment by PhpMadman** [comment]
Is this being reviewed yet? Want to know since you said you definitely was interested in this design.

**Comment by PhpMadman** [comment]
And yet another rebase, followed by some crappy commit msg to fix conflicts...

**Comment by kpodemski** [comment]
I think as 1.7 will be on twig this commit is dead...

**Comment by PhpMadman** [comment]
Well, this was supossed to be a 'qucik fix' for the order view in 1.6.
But let's see what's the team say.
And i'll read up on this twig thing...

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by PhpMadman** [comment]
Still needed, and still up to date.

**Comment by xBorderie** [comment]
Thank you for your feedback and hard work @PhpMadman ! This seems like a lot of work! I created a ticket in order to have a developer take a look at your code. Thanks a lot for your patience and dedication!

**Comment by vincentbz** [comment]
Hi,

Your PR is not forgotten, we appreciate this big big contribution :)
I'm on it, i make a feedback very soon :)

Thanks again

**Comment by PhpMadman** [comment]
Anyway to get Travis re-check this? and show what the conflicts are? What I can see, it should be up to date

**Comment by xBorderie** [comment]
Thank you for staying the course with this!
If you want to trigger Travis again, just make a dummy commit to the PR.
But please be aware that GitHub itself is saying that the branch has conflicts, which means that some of the target files have changed since your initial commits. Are you sure your local branch is up-to-date?

**Comment by PhpMadman** [comment]
Hmm, I might have forgotten to fetch the latest.
I'll give that a go, see if I can get this fixed.

**Comment by PhpMadman** [comment]
Yeah, forgot to fetch before the rebase, it is now up to date again.
But I screwed up the view.tpl so had to get the original, and re-apply my changes again.
But everything seems to be working

**Comment by vincentbz** [comment]
Hi,

First, apologizes from our team for not having been more proactive with you on this PR.
On "develop" branch, this is something we cannot merge for several reasons : 
 - when we revamp a page, we "upgrade" it on symfony and this page is on our roadmap for being revamped in the next versions
 - Now we work with an UX designer on these problematics to fit with the needs of merchants, with user tests, prototypes, iterations. As this is a very important page for merchants, we would like to be the most efficient on this topic.
 
But would you be interested to work on this topic with our PM, dev and UX when we launch this subject ? It will be on Symfony.

Thanks again

**Comment by PhpMadman** [comment]
Hi.

Yes, I can work with the dev team.
I think making this a tabbed interface is a good idea, it is easier to handle.

And also if we rewrite the order files, in theory it should be work to only load tabs and displayed content, and then use ajax to load the other tabs behind the secne, and that should give the feel of a faster order page.

And this is something I would like to do on the incoive page as-well.

**Comment by xBorderie** [comment]
Thank you for being so understanding about this, Björn!
As you surely understand, this project may only be restarted once 1.7.0.0 is stable and released, so that team members can be available again to work with you on this.
Thank you for being patient, and in the meantime I advise to keep watching the changes to the codebase, and come discuss with is on Gitter!
Cheers!

**Pull request closed without merging**
