### PR TITLE
Add some missing elements ids

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR adds an Id to some elements in order to use them in the automated tests
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8961)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[admin-dev/themes/new-theme/template/page_header_toolbar.tpl, line 98 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8961#-LAS4FCK0nUN80oVNqOg:-LAS4FCK0nUN80oVNqOh:bu96rxh) ([raw file](https://github.com/prestashop/prestashop/blob/e0884f71bca91f302ad4cac36ecd334f4a5c5fce/admin-dev/themes/new-theme/template/page_header_toolbar.tpl#L98)):*
> ```Smarty
>   {/if}
>   {if $current_tab_level == 3}
>     <div class="page-head-tabs" id="head_tabs">
> ```

Are you sure about underscores ? Shouldn't it be consistent with classes ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8961)*

**Comment by fatmaBouchekoua** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[admin-dev/themes/new-theme/template/page_header_toolbar.tpl, line 98 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8961#-LAS4FCK0nUN80oVNqOg:-LASIwph7UHnAitMXBaa:b-1zos4u) ([raw file](https://github.com/prestashop/prestashop/blob/e0884f71bca91f302ad4cac36ecd334f4a5c5fce/admin-dev/themes/new-theme/template/page_header_toolbar.tpl#L98)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Are you sure about underscores ? Shouldn't it be consistent with classes ?
</blockquote></details>

I've used the old one (before the migration to Symfony)
There are ids everywhere with underscores and others with a hyphen.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8961)*

**Comment by LittleBigDev** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[admin-dev/themes/new-theme/template/page_header_toolbar.tpl, line 98 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8961#-LAS4FCK0nUN80oVNqOg:-LASKO9U-jaiynuazOJ4:bgg2dg3) ([raw file](https://github.com/prestashop/prestashop/blob/e0884f71bca91f302ad4cac36ecd334f4a5c5fce/admin-dev/themes/new-theme/template/page_header_toolbar.tpl#L98)):*
<details><summary><i>Previously, fatmaBouchekoua (Fatma Bouchekoua) wrote…</i></summary><blockquote>

I've used the old one (before the migration to Symfony)
There are ids everywhere with underscores and others with a hyphen.
</blockquote></details>

ok then :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8961#-:-LASKQvl6NtBv7Bx5KYL:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Thanks @fatmaBouchekoua

**Pull request merged**
