### PR TITLE
Bug fix for 12588

### LINKED ISSUE #12588: Order payment duplicated depending on order state configuration
**Describe the bug**
If a state has these 3 options enabled, when you call validateOrder with this state the order payment is duplicated:

- Consider the associated order as validated.
- Set the order as paid.
- Show delivery PDF.

**To Reproduce**
1. Configure "Awaiting bank wire payment" order state with the 3 options enabled.
2. Create an order paid with bankwire
3. Check order payments

It doesn't happen when you change an order into an state with these 3 options, it only happens when it's called from ValdiateOrder.

**Screenshots**
image
image

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: N/A

### PR DESCRIPTION
**Pull request by Prestaworks**
Only add a new payment if it is a real invoice and missing payment info.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Bug fix for #12588
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |Fixes #12588
| How to test?  | See details under the ticket.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15322)

### CODE REVIEW

**Comment by Progi1984** [comment]
Hello @Prestaworks, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by Prestaworks** [comment]
Hi Progi, can you explain what you mean by rebase the request? what the issue is?

**Comment by Progi1984** [comment]
@Prestaworks A technical article is better than a long speech so : http://build.prestashop.com/howtos/misc/rebasing-your-git-branch/ & https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase.
That will permit to avoid conflict files and merge commits. Thanks in advance.

**Comment by Prestaworks** [comment]
It was not possible to rebase, too many delta conflicts or some error like that, horribly that it should be this hard to just change a simple file in Prestashop.. I have made some changes here on github directly does it work to merge it now? or should I just close this and redo everything in a new branch? will you have time to check it in that case before there are to many conflicts again?

**Comment by Progi1984** [comment]
@Prestaworks Hi, no problem. Close this PR et create a new one from the head of develop. I will check it asap ;) Thank you for your help.

**Comment by Prestaworks** [comment]
Here is the new one https://github.com/PrestaShop/PrestaShop/pull/15417

**Comment by PierreRambaud** [comment]
Closed in favor of #15417

**Pull request closed without merging**
