### PR TITLE
fixes needed for upgrade : avoid fail of foreign keys introduction

### PR DESCRIPTION
**Pull request by 123monsite-regis**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fixes needed for upgrade : avoid fail of foreign keys introduction
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | You must upgrade a shop form a version previous of 1.7.1.0, having rows on PREFIX_tab_lang , not matching one entry of PREFIX_tab

foreign keys are introduce to PREFIX_tab_lang here : https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Entity/TabLang.php#L51
At the end of the autopgrage, there is a doctrine:schema:update , so if datas are not ready to be constraint, it fail :)

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @123monsite-regis 
Did you had this problem when trying an upgrade ?
Can you do this PR changing sql file to `1.7.2.0.sql` please ?

**Comment by 123monsite-regis** [comment]
Did you had this problem when trying an upgrade > yes, due to external modules, not core, tabs where deleted on uninstall, but not tab_lang

**Comment by aleeks** [comment]
I've just edited my last message :smile: 
If you had problem so, `1.7.1.1.sql` :/

**Comment by 123monsite-regis** [comment]
i have tried to review my commit annd adding 1.7.1.1.sql , why the rebase has included a lot of commits ?

**Comment by aleeks** [comment]
You have to rebase from 1.7.1.x not from develop :p

**Comment by maximebiloe** [comment]
Hello @123monsite-regis,

Thanks for your contribution, but this PR is no longer needed since the following one has been merged: https://github.com/PrestaShop/PrestaShop/pull/7746
So, I close this one.

Regards

**Pull request closed without merging**
