### PR TITLE
Fix: If Ask for birth date option is disabled, an exception is displayed in the FO

### LINKED ISSUE #13976: PS1.7.6 beta - If Ask for birth date option is disabled, an exception is displayed in the FO
PS 1.7.6.0 clean install after 1.7.5
```
(1/1) FatalThrowableError
Call to a member function getValue() on null
in CustomerForm.php line 120
at CustomerFormCore->validate()
in CustomerForm.php line 188
at CustomerFormCore->submit()
in CheckoutPersonalInformationStep.php line 62
at CheckoutPersonalInformationStepCore->handleRequest(array('id_customer' => '', 'id_gender' => '1', 'firstname' => 'MyName', 'lastname' => 'MyName', 'email' => 'email', 'password' => '', 'submitCreate' => '1', 'continue' => '1', 'isolang' => 'en', 'id_lang' => 1, 'controller' => 'order'))
in CheckoutProcess.php line 59
at CheckoutProcessCore->handleRequest(array('id_customer' => '', 'id_gender' => '1', 'firstname' => 'MyName', 'lastname' => 'MyName', 'email' => 'email', 'password' => '', 'submitCreate' => '1', 'continue' => '1', 'isolang' => 'en', 'id_lang' => 1, 'controller' => 'order'))
in OrderController.php line 264
at OrderControllerCore->initContent()
in Controller.php line 291
at ControllerCore->run()
in Dispatcher.php line 515
at DispatcherCore->dispatch()
in index.php line 28
```

Order as a guest -> click Continue
**Steps to reproduce the issue:**
1. In the BO => Shop Parameters => Customer settings => Disable `Ask for birth` date option

2. In the FO, when you try to create a new account from the new account page, or the checkout page(a guest or a customer) => an exception is displayed

Reported by user @PeterStudioWeb

### PR DESCRIPTION
**Pull request by OneDotIT**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Disabling the Ask for birthdate option in BO prevents account creation from FO and guest ordering.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13976
| How to test?  | Disable the option 'Ask for birth date' from BO, then do a new order as a guest from FO

The variable birthdayField could be a form array, empty variable , or null.
The previous commit only introduced the check-up for the form array, at which a fatal error will occur if getValue() was introduced with a  null value, such this bug: https://github.com/PrestaShop/PrestaShop/issues/13976.
The first if statement in this commit, is mainly a check for null case.
Also to keep in mind, customer birthdate is optional if enabled, which is why we need to check for empty array value. 

Mathieu's (@matks) have suggested to check the current configuration and then do a decision:

`$isBirthDateOptional = (bool) Configuration::get('PS_CUSTOMER_BIRTHDATE');`

This suggestion would be great, if we eliminated all the view checking (reduce all to a single if statement), but we are already doing a nested check for all the reasonable value's, and as I see it, this will introduce more redundancy.

So, a lot could be done to improve this code, but currently we have a bug #13976 that prevent an essential usecase, and the added modification actually replicate what was done in 1.7.5.x, which seems to work.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14075)

### CODE REVIEW

**Comment by Matt75** [comment]
Instead of add another if you can do
```php
            if (!empty($birthdayField)
                && !empty($birthdayField->getValue())
                && Validate::isBirthDate($birthdayField->getValue(), Context::getContext()->language->date_format_lite)
            ) {
                $dateBuilt = DateTime::createFromFormat(
                    Context::getContext()->language->date_format_lite,
                    $birthdayField->getValue()
                );
                $birthdayField->setValue($dateBuilt->format('Y-m-d'));
            }
```

**Comment by OneDotIT** [comment]
I don't know, must the condition be in the right order or we run the possibility of an error ?

we could do even more, as Validate suppose to not validate empty value's:

```
if (!empty($birthdayField)
    && Validate::isBirthDate($birthdayField->getValue(), Context::getContext()->language->date_format_lite)
) {
        $dateBuilt = DateTime::createFromFormat(
            Context::getContext()->language->date_format_lite,
            $birthdayField->getValue()
    );
    $birthdayField->setValue($dateBuilt->format('Y-m-d'));
}
```

**Comment by OneDotIT** [comment]
trimmed and added a head's up comment.

**Comment by OneDotIT** [comment]
Ok, validate isn't good at not validating empty values. As Travis, validate and "" result to a rendering problem.

**Comment by OneDotIT** [comment]
The last 4 commits are the same.
Only the last one passed (Travis issue was related to system execution for the 3 before).

Please review.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @OneDotIT

**Pull request merged**
