### PR TITLE
Fix: BO - Import/Export - Can't import Store contact

### LINKED ISSUE #35009: BO - Import/Export - Can't import Store contact
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to Import a store contact, I have red notification that they can do it as you can see : 

[recording(46).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/a2a72059-3dd5-4a3b-b200-7aa2ca367ccb)

FYI I use the store contact files template 

Issue find thank to https://github.com/PrestaShop/PrestaShop/issues/34974

### Expected behavior

I wish I could import some store contact

### Steps to reproduce

1. Go to BO 
2. Go to Advenced Parameters > Import
3. Download the "Sample Store Contacts files" (the template for the store Contact import) 
4. On "What do you want to Import?" set "Store Contact
5. Select the file that you just download in the "Select a file to import"
6. Click on Next step 
7. Clic on Import 
8. :tada: Red Alert :tada: 

### PrestaShop version(s) where the bug happened

8.1.x - develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

PS

### PR DESCRIPTION
**Pull request by Codencode**
The problem depends on the fact that when importing store contacts, the 
```
PrestaShopLogger->object_type property
```
 is set with "Store contacts" which does not pass the validation of the **Validate::isValidObjectClassName()** method. So in this case I thought of valorising the **$import_type** variable with **StoreContacts** which passes the validation and the error no longer occurs.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| UI    | https://github.com/florine2623/testing_pr/actions/runs/8049269672 ✅ 
| Fixed issue or discussion?     | Fixes #35009
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by Hlavtox** [comment]
This is weird, how come the translated string works for all other types? 

Oh, so isValidObjectClassName doesn't accept spaces? And all the other types that are translated work by accident? What if some language translates it with some nonsupporter character, then it also won't work.

Snímek obrazovky 2024-01-11 114555

**Comment by Codencode** [comment]
> This is weird, how come the translated string works for all other types?

I tried in PS 8.1.2 where the strings are all single words, except 'Store contacts' which is the only one that generates the error, because there is a space between the 2 words.

Screenshot

What version of PS does your screenshot refer to?
I understand to check 'Supply Orders' and 'Supply Order Details' you need to activate 'PS_ADVANCED_STOCK_MANAGEMENT'.

Yes, you are right, in case of translation with spaces it would give an error.
Perhaps it would be better to set the "$import_type" variable manually.

**Review by tleon — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Codencode ,

This issue is not fixed : https://github.com/PrestaShop/PrestaShop/issues/35009 

I can properly import my sample store contacts once but it is added to the Categories section instead of the Store section instead of the Store - Contact section :

Screenshot 2024-02-26 at 14 56 57

When I try to import it a second time, I have the initial error :

Screenshot 2024-02-26 at 15 15 33

For this issue, https://github.com/PrestaShop/PrestaShop/issues/34974, I still can't reproduce it.

https://github.com/PrestaShop/PrestaShop/assets/16019289/15aaa94b-351c-4303-9bc6-d2921380b1f8

Could you check ?

**Comment by Codencode** [comment]
> When I try to import it a second time, I have the initial error :

Hi @florine2623,
when you import the file check if the URL in the "image" field exists, otherwise you must skip that field because this generates an error as the URL does not exist.
However, now I make a change to avoid this error too.

**Comment by Codencode** [comment]
I uploaded a new edit to check if the store image to import actually exists.

@florine2623 can you check if you still have the error?

**Review by florine2623 — DISMISSED** [review]
Hello @Codencode ,

Thanks for the update ^^

For the issue https://github.com/PrestaShop/PrestaShop/issues/35009 , it is fixed ✅ 
Tested with/without images.

https://github.com/PrestaShop/PrestaShop/assets/16019289/5d9cf141-79d9-45f3-8ec2-32a7ba15bbb2

2nd attempt, OK :

https://github.com/PrestaShop/PrestaShop/assets/16019289/9206498d-69e2-4b50-9ee4-3acdd692af60

But for the issue https://github.com/PrestaShop/PrestaShop/issues/34974 , there's still an error and it can be tested entirely :

https://github.com/PrestaShop/PrestaShop/assets/16019289/35674ccb-9798-4172-935b-178d9432c77d

For me it is QA ✅ 
But the PR https://github.com/PrestaShop/PrestaShop/issues/34974 will need another PR to test/fix the issue.

**Comment by Codencode** [comment]
> Hello @Codencode ,
> 
> Thanks for the update ^^
> 
> For the issue #35009 , it is fixed ✅ Tested with/without images.
> 
>  Screen.Recording.2024-02-27.at.16.18.04.mov 
> 2nd attempt, OK :
> 
>  Screen.Recording.2024-02-27.at.16.23.46.mov 
> But for the issue #34974 , there's still an error and it can be tested entirely :
> 
>  Screen.Recording.2024-02-27.at.16.19.52.mov 
> For me it is QA ✅ But the PR #34974 will need another PR to test/fix the issue.

Ok, 
I removed the reference to the ISSUE in the description.

Thanks!

**Comment by mflasquin** [comment]
Hi @Codencode, can you fix the CI before we can merge the PR ?

**Comment by Codencode** [comment]
Hi @mflasquin,
I fixed.

Thanks!

**Comment by mflasquin** [comment]
thanks @Codencode

**Review by mflasquin — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Pull request merged**
