### PR TITLE
Fix deprecated jquery shortcut function 'load'

### PR DESCRIPTION
**Pull request by Fabuloops**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The "load" shortcut function in jQuery > 3.X should not be used anymore https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Use JQuery > 3.X => compile your assets with webpack and look at your console. It's will tel you something like 'url.indexOf is not a function'

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11608)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Hi @Fabuloops,

Can you please commit the generated assets for the QA review?


Note to the QA team: the address step of the checkout works as before.

**Comment by Fabuloops** [comment]
Hi @Quetzacoalt91,

I don't understand what you look for by "generated assets"

**Comment by Quetzacoalt91** [comment]
I meant "compiling your assets with webpack" :)

**Comment by Fabuloops** [comment]
The core.js ?

**Comment by Quetzacoalt91** [comment]
This one exactly. :)

**Comment by MathiasReker** [comment]
Builds assests in FO Core:

```
cd themes/
npm install
npm run build
```

**Comment by Fabuloops** [comment]
Hi @MathiasReker,

I have run "npm run watch" do you need the production compilation ?
This branch is under jQuery 2.2.4 where function load is not deprecated

**Comment by Quetzacoalt91** [comment]
I'd like to have the production version indeed, as these files are published in the release package. Thanks.

However, no need to commit the package-lock.json. :)

**Comment by Quetzacoalt91** [comment]
PR rebased.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Rebased, ready for merge

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @Fabuloops

**Pull request merged**
