### PR TITLE
Fix the style of forgotten password page

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Forgotten password page doesn't display properly on mobile/tablet.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2957
| How to test?  | Go to FO > forgotten password page and check with different mobile view (different resolution) if it displayed well.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @Azouz-Jribi, can you please add the changes of the file `themes/classic/assets/css/theme.css` in a dedicated commit like "FO: Generate assets"?
In case of cherry-pick / merge later, it will be easier for us to manage the potential conflicts.

**Comment by Quetzacoalt91** [comment]
For reviewers, I asked the review of Tristan on the forge issue.

**Comment by Azouz-Jribi** [comment]
Hi @Quetzacoalt91 
done ;)

Regards

**Comment by Quetzacoalt91** [comment]
Thanks, I'm now waiting for Tristan's review

**Review by toutantic — DISMISSED** [review]

**Comment by maximebiloe** [comment]
Hello @Azouz-Jribi,

It breaks the behavior on large screen.
@leadesign will add recommendations on the forge ticket.

Regards

**Comment by Azouz-Jribi** [comment]
Hi @maximebiloe 
I will apply the new changes requested by @Leadesign

Thanks

**Comment by Azouz-Jribi** [comment]
@maximebiloe 
Can you please check with @Leadesign the new changes.

Thanks

**Comment by maximebiloe** [comment]
It's fine for me!
Thanks @Azouz-Jribi

**Comment by aleeks** [comment]
Thank you @Azouz-Jribi

**Review by aleeks — APPROVED** [review]

**Pull request merged**
