### PR TITLE
Do not enable add to cart button if catalog mode is enabled

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Add to cart button did not take catalog mode into consideration. Given we want to maybe ship hummingbird optionally with 8.1 and it has add to cart feature from product lists, this should be handled on the core side. @nizelg made a [PR for the theme](https://github.com/PrestaShop/hummingbird/pull/471), but it should not be theme's responsibility.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install hummingbird, enable catalog mode, add to cart buttons will disappear from product lists. Clear cache if they don't disappear from modules on homepage. You don't have to test anything other than product miniature and product page in front office. And focus only on product add to cart button and displaying of delivery time.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/455
| Related PRs       | 
| Sponsor company   | 

For reviewers - `$this->shouldShowAddToCartButton($product)` just returns `$product['available_for_order']`. It's A) a bad name for such a function and B) why the hell it should call a function to return one value.

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Comment by nicosomb** [comment]
The two PR are ok for me :+1:

**Comment by nizelg** [comment]
I laughed a lot at B). Indeeed it's on core responsibility to decide such things. Thank you for handling this!

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Checked on hummingbird theme and classic theme: FO, product page, quickview, switch back and forth catalog mode.

LGTM
QA ✅

**Comment by kpodemski** [comment]
thanks @Hlavtox 🤖

**Pull request merged**
