### PR TITLE
Undefined index base_price

### PR DESCRIPTION
**Pull request by Flowster**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | initialize base_price for quantity_discount before passing it to formatQuantityDiscounts
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a product without attribute and with quantity discount. On the product page a notice will show with an undefined index base_price

### CODE REVIEW

**Comment by Flowster** [comment]
I've made this new pull request based on the comments on the previous one https://github.com/PrestaShop/PrestaShop/pull/7851

**Comment by xBorderie** [comment]
Thanks Florian!

**Comment by Flowster** [comment]
Hi @xBorderie does something needs to be added to this pull request to be accepted or does it has simply been forgotten? ;)

**Comment by maximebiloe** [comment]
Thank you @Flowster

**Comment by SharakPL** [comment]
And why exactly is `$quantity_discount['base_price'] = 0`? It should be base price of the product. Now quantity discounts make product price all wrong i.e. if base price is 10€ and there's 2€ discount from 5 amount, when I set amount to 5 then product price doesn't change to `8€` (10 - 2) but to `-2€` (0 - 2).

**Pull request merged**
