### PR TITLE
Added prestashop version to exceptions

### PR DESCRIPTION
**Pull request by aleeks**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Added prestashop version on exceptions |
| Type? | bug fix |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1645 |
| How to test? | No idea |

Use : https://github.com/PrestaShop/PrestaShop/pull/4040

### CODE REVIEW

**Comment by aleeks** [comment]
?w=1 needed :/

**Comment by aleeks** [comment]
`{'error': v + ' || {"version": "' + ps_version + '"}'}` strange but ok with @ishcherbakov

**Comment by Quetzacoalt91** [comment]
Is the file install-dev/.jpg expected ?

**Comment by aleeks** [comment]
This girl come in from nowhere!

**Comment by mickaelandrieu** [comment]
Thank you @aleeks

**Pull request merged**
