### PR TITLE
Get stores ordered by names

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add an order by name in Store::getStore to avoid a random sorted list in front.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | List stores and check the order on front
| Possible impacts? | none
| Sponsor company   | Creabilis.com

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]
I approve, but it's not a definitive solution tbh 😊
we should add a position field at least

**Review by kpodemski — APPROVED** [review]
Good for a start.

**Review by sallemiines — COMMENTED** [review]
Hello @jf-viguier 
Thanx for the PR ! it's LGTM QA :heavy_check_mark: 
Thank you

**Comment by nicosomb** [comment]
Thank you @jf-viguier !

**Pull request merged**
