### PR TITLE
Add composer.json CS normalizer to CI

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add composer.json CS normalizer. Even `composer.json` is configured to have deps sorted, it does not. Thus enforce clean composer.json format and reduces possible merge conflicts.
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23886)

### CODE REVIEW

**Comment by mvorisek** [comment]
@Progi1984 can we merge this?

**Comment by mvorisek** [comment]
@eternoendless @matks please merge

**Comment by mvorisek** [comment]
@eternoendless @matks please review, it helps to keep the composer.json ordered (now `require-dev` deps are out of orded) and prevents merge conflicts

**Comment by mvorisek** [comment]
@eternoendless @matks @PierreRambaud please review, it helps to keep the composer.json ordered (now `require-dev` deps are out of orded) and prevents merge conflicts

**Review by matks — COMMENTED** [review]
Well it sounds good :)

Included dependencies use MIT and BSD which are compatible

**Comment by mvorisek** [comment]
@NeOMakinG @PierreRambaud can you please approve and merge?

**Review by atomiix — DISMISSED** [review]

**Comment by mvorisek** [comment]
@Progi1984 can you please approve and merge as well? I need to make another PRs on top of this one.

**Comment by eternoendless** [comment]
@mvorisek we appreciate your recent activity and contributions to the project. However, please be aware that repeatedly pinging people and asking them to do things might come across as rude.

**Comment by mvorisek** [comment]
@eternoendless Yes, please review faster - I need to iterate quickly and need feedback asap so I can implement it before I need to move 😄

Who is the best one to ping for PHP/CI changes?

**Comment by eternoendless** [comment]
Let me remind you that while you have your priorities, we have our own as well. There's no need to ping anyone – your PRs will be reviewed in due time. Being pushy about it will achieve the opposite of what you want.

**Comment by mvorisek** [comment]
> 
> 
> Let me remind you that while you have your priorities, we have our own as well. There's no need to ping anyone – your PRs will be reviewed in due time. Being pushy about it will achieve the opposite of what you want.

I understand you, but please also understand my point - some PRs can be merged faster. Especially CS fixes PRs, I had to rebase this twice already.

**Review by atomiix — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
noice

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @mvorisek

**Pull request merged**
