### PR TITLE
Change prestashop.com to prestashop-project.org in .htaccess

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | change prestashop.com to prestashop-project.org in .htaccess
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | just a text
| UI Tests          | no
| Fixed issue or discussion?     | no
| Sponsor company   | Creabilis

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
To be merged after the tests.

**Review by matks — COMMENTED** [review]
Hi @jf-viguier I think you can also modify lines 2110 and 2370 to make this change relevant 😉 let's change it uniformly

**Comment by nicosomb** [comment]
>  I think you can also modify lines 2110 and 2370 to make this change relevant 😉 let's change it uniformly

Or you can open 2 other PR for Hacktoberfest :trollface: 😅😘

**Comment by jf-viguier** [comment]
@matks 2370 changed, nice catch.
For line 2110 no, it's for retrocompatibility before ~~start~~ stuff.

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by matks** [comment]
@jf-viguier Can you please describe more how to test? 😉

**Comment by jf-viguier** [comment]
@matks it's just a text comment, nothing to test. I don't understand.
The replace stuff before the start is for an unsupported prestashop version I guess : 1.5 ou 1.6 ? I don't know

**Comment by paulnoelcholot** [comment]
Hello @jf-viguier,

I tested your PR and it's GOOD for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by boherm** [comment]
Thanks @jf-viguier!

**Comment by matks** [comment]
@boherm Don't forget the milestone 😉

**Comment by boherm** [comment]
Oopsi! @matks nice catch 😅

**Pull request merged**
