### PR TITLE
[-] FO : Fix ajax register

### PR DESCRIPTION
**Pull request by monsty**
Fixed bug while creating customer account without address by ajax.

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi !

Thank you for your contribution !

Next time, please follow our commit messages convention here : http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Best regards.

**Comment by Shudrum** [comment]
Hi again !

I've reverted the merge because there is an else statement after this test. Can you explain us what is your error and explain us why do you do this ?

Thank you.

Best regards.

**Comment by monsty** [comment]
Hi,

Actually, it's impossible to create an account without the customer address, because it always go in the else statement (supposed to be used for the one step registration). 

So I checked the code, and I saw that it never enters in the if condition because of the ajax check. Moreover, there is a dead code inside : 

```php
[line 434] if (... !$this->ajax ...) {
 ...
[line 465] if ($this->ajax) {...}
...
}
```

**Comment by Shudrum** [comment]
Hi !

This one of the reason for the revert : there is some unreachable code, so the test was locked for $this->ajax afterwards … I prefer to double check before "revert" an old modification like this one.

The other reason is because you should pass through the one step registration in ajax …

So, if I understand, you want to register an account, from an ajax, but you can't because you have no address ?

Thank you !

**Comment by monsty** [comment]
I don't get it, why do you keep unreachable code inside then ?
The "ajaxDie" inside is supposed to return a json response, but it can't because of the first check.

So, it's impossible to create a customer account without address ?

**Comment by Shudrum** [comment]
The unreachable code will be removed, there is a lot of forgotten lines ... we can't find them all ...

So : Creating a customer account without address is the problem, but, in PrestaShop a user WILL have an address.

Maybe you should override this method in your project if you really wan't the possibility of creating users without address ...

Best Regards.

**Comment by monsty** [comment]
Oh ok I see, thanks ! 
I'll tell you if I find some dead code again :) 

Have a good day !

**Comment by Shudrum** [comment]
My bad ... After many discussions, another team member explained us that we can create a user without address ... but not in ajax ^^'

So finally, we will merge your PR :+1: 

Sorry for the wrong information, and thank you again !

**Comment by kermes** [comment]
Hi, this is not the solution for this problem. you created another one by removing that check.
After this modification, when you have PS_REGISTRATION_PROCESS_TYPE set to 0 (that means you dont want addresses to be mandatory for registration) you can create an account and no address is needed unless you are in onepagecheckout. In that situation even though you have that kind of registration in checkout customers are asked to enter an address (ther are checking out, at this point an address IS mandatory) but now it never reaches the "}else{" part because you removed the !$this->ajax that made it create the account properly, so the result right now is that if you try to create an account from the onepage checkout page, after filling all the form with your address datas, you are redirected to create an address (because none where created).

**Comment by kermes** [comment]
I can't find a place in prestashop where an account in one step is created by ajax, I suposse you need it for a module, maybe in your module you need to create an override, but i dont think this is a bug (well it is now, because it used to work and now it doesn't)
AuthController creates the accounts without ajax The only place where account is created in ajax is in the checkout, and in that point regardless of what you chose the registration process to be in 1 or 2 steps, an addreess is needed. That is why that check used to have '!$this->ajax' in it to force 2 steps when in checkout process.

**Comment by gRoussac** [comment]
Hi,

This is right we will revert it. Thank you for your dedication.

Regards

**Pull request merged**
