### PR TITLE
Fix load JqueryUI on FrontController : load only requested components

### LINKED ISSUE #33558: addJqueryUI load all JqueryUI, not just a component
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On the frontController, calling the `addJqueryUI` function automatically adds the whole jQuery UI library.

### Expected behavior

The function should only add the necessary components. (The jQuery library being quite heavy, it is interesting for web performance (webperf) to load only the necessary components)

We can also see that in the Controller `classes/controller/Controller.php` does it very well for the administration.

Example we execute:
`$this->context->controller->addJqueryUi('ui.autocomplete');`

The jQuery UI library is fully loaded:
     - `/js/jquery/ui/jquery-ui.min.js`
     - `/js/jquery/ui/themes/base/minified/jquery.ui.theme.min.css`
     - `/js/jquery/ui/themes/base/minified/jquery-ui.min.css`
Instead of just charging:

- `js/jquery/ui/jquery.ui.core.min.js`
- `js/jquery/ui/jquery.ui.widget.min.js`
- `js/jquery/ui/jquery.ui.position.min.js`
- `js/jquery/ui/jquery.ui.menu.min.js`
- `js/jquery/ui/jquery.ui.autocomplete.min.js`

- `/js/jquery/ui/themes/base/jquery.ui.core.css`
- `/js/jquery/ui/themes/base/jquery.ui.widget.css`
- `/js/jquery/ui/themes/base/jquery.ui.position.css`
- `/js/jquery/ui/themes/base/jquery.ui.menu.css`
- `/js/jquery/ui/themes/base/jquery.ui.autocomplete.css`

### Steps to reproduce

1. Add search bar module (ps_searchbar)
2. Check on the Front side, the list of assets loaded in the network console of the web browser

### PrestaShop version(s) where the bug happened

All

### PHP version(s) where the bug happened

All

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Damien TUPINIER & Lord of Web

### PR DESCRIPTION
**Pull request by tups**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | On the frontController, calling the addJqueryUI function automatically adds the whole jQuery UI library. <br>The function should only add the necessary components. (The jQuery library being quite heavy, it is interesting for web performance (webperf) to load only the necessary components)<br>We can also see that in the Controller classes/controller/Controller.php does it very well for the administration.<br>I adapted the function to match the loading of assets for the Front, loading only the requested components
| Type?             | bug fix 
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | <ol><li>Add search bar module (ps_searchbar). The module calls the function `$this->context->controller->addJqueryUI('ui.autocomplete');`</li><li>Check on the Front side, the list of assets loaded in the network console of the web browser</li></ol><p>If the jQuery UI library is fully loaded, we must have the following list of assets:</p><ul> <li>/js/jquery/ui/jquery-ui.min.js</li> <li>/js/jquery/ui/themes/base/minified/jquery.ui.theme.min.css</li> <li>/js/jquery/ui/themes/base/minified/jquery-ui.min.css</li></ul><p>If we only load the called jQuery components, we should have the following list:</p><ul> <li>/js/jquery/ui/jquery.ui.core.min.js</li> <li>/js/jquery/ui/jquery.ui.widget.min.js</li> <li>/js/jquery/ui/jquery.ui.position.min.js</li> <li>/js/jquery/ui/jquery.ui.menu.min.js</li> <li>/js/jquery/ui/jquery.ui.autocomplete.min.js</li> <li>/js/jquery/ui/themes/base/jquery.ui.core.css</li> <li>/js/jquery/ui/themes/base/jquery.ui.widget.css</li> <li>/js/jquery/ui/themes/base/jquery.ui.position.css</li> <li>/js/jquery/ui/themes/base/jquery.ui.menu.css</li> <li>/js/jquery/ui/themes/base/jquery.ui.autocomplete.css</li> </ul>
| Fixed ticket?     | Fixes #33558 
| Related PRs       | https://github.com/PrestaShop/ps_facetedsearch/pull/895
| Sponsor company   | Damien TUPINIER & Lord of Web

### CODE REVIEW

**Review by Hlavtox — COMMENTED** [review]
- Looks legit, just a small comment in https://github.com/PrestaShop/ps_facetedsearch/pull/895#issuecomment-1669266476.
- Only disadvantage is that more files are loaded, but if CCC is enabled, this is no issue.
- It would be also good to update the package, [because it throws lightouse errors](https://github.com/PrestaShop/PrestaShop/issues/27186), but I don't know if it's possible to build the library per-component. 

@tups Do you think you could provide the compliled asset sizes before & after?

**Comment by tups** [comment]
@Hlavtox indeed, it will load more files, but we gain a lot of weight

We will take for example a Prestashop, with the "classic" theme, if I'm not mistaken there is the module `ps_searchbar` (load ui.autocomplete ) and `ps_facetedsearch` (load ui.slider) by default.
 
Here is the recap of the weight with the two components `ui.autocomplete` and `ui.slider`:

Only components JS:
- /js/jquery/ui/jquery.ui.core.min.js 4,18 ko
- /js/jquery/ui/jquery.ui.widget.min.js 6,33 Ko
- /js/jquery/ui/jquery.ui.position.min.js 6,12 Ko
- /js/jquery/ui/jquery.ui.menu.min.js 9,18 Ko
- /js/jquery/ui/jquery.ui.autocomplete.min.js 7,54 Ko
- /js/jquery/ui/jquery.ui.mouse.min.js 2,77 Ko
- /js/jquery/ui/jquery.ui.slider.min.js 9,96 Ko
**Total : 46,08 Ko**

All jQuery UI JS:
- /js/jquery/ui/jquery-ui.min.js 222 Ko
**Total : 222 Ko**

**Gain JS : 175,92 Ko**

Only components CSS :
- /js/jquery/ui/themes/base/jquery.ui.core.css 1,43 Ko
- /js/jquery/ui/themes/base/jquery.ui.menu.css 1,41 Ko
- /js/jquery/ui/themes/base/jquery.ui.autocomplete.css 0,322 Ko
- /js/jquery/ui/themes/base/jquery.ui.slider.css 1,28 Ko
**Total : 4,44 Ko**

All jQuery UI CSS:
- /js/jquery/ui/themes/base/minified/jquery.ui.theme.min.css 14 Ko
- /js/jquery/ui/themes/base/minified/jquery-ui.min.css 25,1 Ko
**Total : 39,1 Ko** 

**Gain CSS : 34,66 Ko**

**Review by Hlavtox — APPROVED** [review]
@tups Cool numbers, +- the same gains I got. ;-) Good job brother.

**Review by LouisAUTHIE — DISMISSED** [review]
Great job, nice optimization ! Thanks

**Comment by Hlavtox** [comment]
@PrestaShop/tech-council Guys, can we target 8.1 here or it's dangerous? The jquery UI component parameter was required before. It would be a BC break only if somebody was doing something like `addJqueryUI('blablabla');`

**Review by aniszr — COMMENTED** [review]
Hello @tups 

I testes your PR related to [PR #895](https://github.com/PrestaShop/ps_facetedsearch/pull/895), unfortunately I couldn't get the expected result mentioned in the PR description!
In console Network
- **CSS loaded files are :**
theme.css
front.css
ps_socialfollow.css
ps_searchbar.css
productcomments.css
wishlist.css
homeslider.css

- **JS loaded files are :**
core.js
theme.js
front.js
ps_emailsubscription.js
mailalerts.js
jquery.rating.plugin.js
productListingComments.js
product.bundle.js
ps_shoppingcart.js
ps_searchbar.js
responsiveslides.min.js
homeslider.js
graphql.js
vendors.js

See attached screenrecord :

https://github.com/PrestaShop/PrestaShop/assets/92626242/c7362d46-8aae-47b5-864b-fb4cd904a3ee

Could you please check and feed-back 

thanks!

**Comment by Hlavtox** [comment]
@aniszr You must test it on category page, faceted search does not register the library on homepage

**Comment by tups** [comment]
I just did a fresh install locally to check, I confirm that it works so I don't really understand:
image

You don't even have jQuery UI, it's quite strange

**Review by Hlavtox — CHANGES_REQUESTED** [review]
So, I tested it manually, few things. After discussion with @kpodemski, we could target 8.1.x, if you put following fallback to the beginning of the method. I would like you to do it anyway, please.

```php
// If the component does not start with ui. prefix, we need to add it
        if (substr($component, 0, 3) !== 'ui.') {
            $component = 'ui.' . $component;
        }
```

Now, the PR really doesn't work as it should. Why it doesn't work. Because `registerJavascript` and `registerStylesheet` need a PATH not a URL. So, the PR works only for shops that are not in subfolders.

Original function was including the PATH to files.
`/js/jquery/ui/themes/base/minified/jquery-ui.min.css`

But `Media::getJqueryUIPath` we started to use return the URL.
`/81x/js/jquery/ui/themes/base/jquery.ui.slider.css`
(Yeah, quite confusing name of the function. Looking inside that method, to add some more confusion - _PS_JS_DIR_ is not a DIR, but a URL.)

If you fix it, the gains are there. 
- Before: 1248 kB of JS, 365 kB of CSS
- After: 1067 kB of JS, 306 kB of CSS

**Comment by tups** [comment]
I get it, that's a good idea.
I just made the change on the commit

So you found another bug along the way 🤕

**Comment by Hlavtox** [comment]
@tups No, it works fine with the original code. 

It's broken only with this PR, do you think you could find a way to fix it?

**Comment by tups** [comment]
Indeed, it is a pretty knot bag.

_PS_JS_DIR_ is declared with the physical_uri, but Media::getMediaPath is intended to have URLs from the root of the project.

So I propose to clean the _PS_JS_DIR_ folder without the __PS_BASE_URI__. This fixes the bug when we have a physical URI that is configured

I made the commit

**Comment by Hlavtox** [comment]
@tups Do it like this, and delete the change in Media.php. ;-) It's not the prettiest solution, but `addJqueryPlugin` does the same thing.

```php
    public function addJqueryUI($component, $theme = 'base', $check_dependencies = true)
    {
        // If the component does not start with ui. prefix, we need to add it
        if (substr($component, 0, 3) !== 'ui.') {
            $component = 'ui.' . $component;
        }

        if (!is_array($component)) {
            $component = [$component];
        }

        foreach ($component as $ui) {
            $ui_path = Media::getJqueryUIPath($ui, $theme, $check_dependencies);
            foreach ($ui_path['css'] as $uiPathCss => $uiMediaCss) {
                $this->registerStylesheet(
                    str_replace(_PS_JS_DIR_ . 'jquery/ui/themes/' . $theme . '/', '', $uiPathCss),
                    str_replace(_PS_JS_DIR_, '/js/', $uiPathCss),
                    ['media' => $uiMediaCss, 'priority' => 95]
                );
            }
            foreach ($ui_path['js'] as $uiPathJs) {
                $this->registerJavascript(
                    str_replace(_PS_JS_DIR_ . 'jquery/ui/', '', $uiPathJs),
                    str_replace(_PS_JS_DIR_, '/js/', $uiPathJs),
                    ['position' => 'bottom', 'priority' => 49]
                );
            }
        }
    }
```

**Comment by tups** [comment]
Ok it's done

**Review by Hlavtox — APPROVED** [review]
Ready to go

**Review by boherm — APPROVED** [review]
Nice, it looks very good! Thanks for your contribution @tups!

**Review by aniszr — APPROVED** [review]
Hello @tups 

I tested your PR, LGTM:heavy_check_mark: 

See attached screenshot:
image

Auto Test :https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5830278866 :heavy_check_mark: 

QA:heavy_check_mark: 
Thanks!

**Comment by boherm** [comment]
It's merged, thanks @tups!

**Comment by tups** [comment]
With pleasure 🙂

**Pull request merged**
