### PR TITLE
Fix show sql action in logs page

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes show action action in Logs page.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Access logs page which is hidden under http://your-prestashop.local/admin-dev/index.php/configure/advanced/logs Grid action (https://prnt.sc/k1k4y5) "Show SQL query" should show modal with SQL.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9243)

### CODE REVIEW

**Comment by sarjon** [comment]
ping @mickaelandrieu

**Comment by mickaelandrieu** [comment]
Thank you, I'll review it in the morning :)

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Hello @sarjon , would you mind to explain to the QA team how to access to the Logs page and what needs to be checked please?

**Comment by sarjon** [comment]
this PR does not recompile assets, but should it?

**Comment by mickaelandrieu** [comment]
@sarjon yes please :)

**Comment by sarjon** [comment]
done

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Hello @marionf, I need this for my own pull request (or this will create conflicts :( ).

**Comment by mickaelandrieu** [comment]
Thanks for the review @marionf :)

Good job @sarjon

**Pull request merged**
