### PR TITLE
Code issues : Avoid code duplicate in EmployeeGridDefinitionFactory

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | This change fixes minor code issues I found while working on another bug.
| Type?         | refacto 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A.
| How to test?  | Make sure `BO > Advanced params > teams` filter by active/disabled work !

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19873)

### CODE REVIEW

**Comment by PululuK** [comment]
ping @atomiix @matks @PierreRambaud

**Review by matks — APPROVED** [review]
Nice catch !

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

The filter in the BO => Advanced Parameters => Team => Employees do not work **With/Without PR** as reported here: https://github.com/PrestaShop/PrestaShop/issues/19812 which fixed by this PR: https://github.com/PrestaShop/PrestaShop/pull/19828 1.7.7.x.
Waiting for Merge 177 into develop to test this PR as it is blocked.

Thanks!

**Comment by PululuK** [comment]
> Hi @PululuK,
> 
> The filter in the BO => Advanced Parameters => Team => Employees do not work **With/Without PR** as reported here: #19812 which fixed by this PR: #19828 1.7.7.x.
> Waiting for Merge 177 into develop to test this PR as it is blocked.
> 
> Thanks!

Hi @khouloudbelguith  !!!!
How are you ? It's great to see you again ! 👶🏻
Okay! Please keep me posted.

**Comment by khouloudbelguith** [comment]
Hi @PululuK,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1tndqs2qeTj47f41q17gfMWypJxJVTQa8/view?usp=sharing
Thanks!

**Comment by Progi1984** [comment]
Thanks @PululuK & @khouloudbelguith

**Pull request merged**
