### PR TITLE
// Updated Romanian tax rate where necessary

### PR DESCRIPTION
**Pull request by Nobodaddy**
main tax rate decreased in 2016 from 24% to 20%

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

Thank you for this PR. Can you give me write access on your repository so I can squash all your commits. This PR will be backported to PrestaShop 1.6 (and it's very annoying to cherry-pick 26 commits).
I'll merge this as soon as possible.

Best regards,

**Comment by Nobodaddy** [comment]
Hi,
as a Github dummy I really don't know how to give you write access.
So please lend me a helpful hand. ;)

**Comment by julienbourdeau** [comment]
I made a little animated gif, it should be easy :smiley: 

give-me-write-access-please

**Comment by Nobodaddy** [comment]
Perfect! Done.

Best wishes

**Comment by julienbourdeau** [comment]
I'll update your develop branch at the same time. Thank you for your contribution !

Note to the PrestaShop team, this commit need to be cherry-picked on `1.6.1.x`: cdc16e5f0d48b40894e36e9540e2c2d5b0a9cacc

**Pull request merged**
