### PR TITLE
[~] BO : Remove open graph title/description

### PR DESCRIPTION
**Pull request by kelu95**
Also, this features already exists on seo expert module

### CODE REVIEW

**Comment by inetbiz** [comment]
I am against removing OGP tags from core and native social share module.

**Comment by vincentbz** [comment]
Hi,

We removed it because it has no sense to leave it in the core while it's not something essential for most of the users and there are many modules doing it.

**Comment by inetbiz** [comment]
socialsharing is a native module. OGP must remain in that module and outputted title and description for facebook shares and pinterest to work!

**Comment by vincentbz** [comment]
We don't modify at all the native module. We planned to add something that would be a duplicate of SEO expert module or other module. And we removed it

**Pull request merged**
