### PR TITLE
OPC : login or register

### PR DESCRIPTION
**Pull request by julienbourdeau**
commande_-_prestashop
### Todos
- [ ] Make http://prestashop.ps/fr/adresse private again (see https://github.com/PrestaShop/PrestaShop/pull/4156/files#diff-540b24198b84a4ae4ca03dbe21a6d014R29 )

### CODE REVIEW

**Comment by djfm** [comment]
Looks good to me, and I really like the fact that we're creating the account and address in one step! But we'll probably need to do some real user testing to be safe.

I've found a few subtle bugs though, here are the test scenarios I have tried:

Background:
- OPC is enabled
- guest checkout is enabled
- I have already added a product to the cart

Scenarios:

- As a customer who is **not logged in** and **doesn't have an account** I want to place an order. I write my address, save it and proceed with the order **without making any mistakes**. **I do not create an account**.
- As a customer who is **not logged in** and **doesn't have an account** I want to place an order. I write my address, save it and proceed with the order **without making any mistakes**. **I do create an account**.
- As a customer who is **not logged in** and **doesn't have an account** I want to place an order. I write my address, save it and proceed with the order **but before paying I realize that I made a mistake in my delivery address and I correct it**. **I do create an account**. You should find an issue here :)
- As a customer who is **not logged in** and **doesn't have an account** I want to place an order. I write my address, but I forget to add a phone number. You should find an issue here :)

**Comment by snrTerco** [comment]
Yes, and another one, provably not for OPC only:
You'd like self-delivery, but imagine enetering your address/billing information even if you're typing just 'sdfsdf' and '00000'. -_o

**Comment by julienbourdeau** [comment]
@snrTerco It seems like this is a special use case. I think we'll let module and theme makers add this feature :)

**Comment by drzraf** [comment]
referencing http://forge.prestashop.com/browse/PSCSX-7434 here
since forge seems abandoned.

**Pull request merged**
