### PR TITLE
Update keyboard shortcuts in product page

### PR DESCRIPTION
**Pull request by AntoineMille**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | BO: Update keyboard shortcuts in product page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by aleeks** [comment]
ping @vincentbz

**Comment by Quetzacoalt91** [comment]
I think @dave-ps would appreciate to see a new pull-request about that. :)

**Comment by xBorderie** [comment]
So we're changing all the letters? :)

Alt-Q: Save
Alt-R: Save & Duplicate
Alt-Y: Save current & create new
Alt-W: Save & go to catalog
Alt-C: Save & open preview
Alt-N: Save & toggle enable/disable

I really think those are not the best choices. To me, those letters are mentally attached to:

Q: Quit
R: Reload
Y: Undo Ctrl-Z (Undo the undo, yay!)
W: Close window
C: Copy
N: New

Q, R and W are particularly dangerous, since a user could press Ctrl-key instead of Alt-key by mistake -- and lose the unsaved content.
Moreover, Alt is alse used by the Windows applications, as shortcuts to menu items. Shouldn't we use Alt-Shift?

After a quick look around, I propose these:

Alt-Shift-S: Save
Alt-Shift-D: Save & Duplicate
Alt-Shift-A: Save current & create new
Alt-Shift-G: Save & go to catalog
Alt-Shift-P: Save & open preview
Alt-Shift-T: Save & toggle enable/disable

What do you guys think?

**Comment by julienbourdeau** [comment]
I like your shortcuts @xBorderie 👍

**Comment by AntoineMille** [comment]
Hello @xBorderie,
Thanks for your help.
I have just done a commit =).

Regards,

**Comment by xBorderie** [comment]
Thanks a lot! Can't wait to see it land in the next version :)
(which will be 1.7.1.0 I guess, because of "no string change in patch versions")

**Comment by vincentbz** [comment]
Hi guys,

I would keep the current letters and change the CTRL by ALT+SHIFT as proposed by Xavier

Alt-Shift-S: Save
Alt-Shift-D: Save & Duplicate
Alt-Shift-P: Save current & create new
Alt-Shift-Q: Save & go to catalog
Alt-Shift-V: Save & open preview
Alt-Shift-O: Save & toggle enable/disable

Thanks

**Comment by aleeks** [comment]
Thank you @AntoineMille  @maximebiloe

**Comment by xBorderie** [comment]
@vincentbz Now you need to put this in the documentation :)

**Comment by dave-ps** [comment]
excellent!

**Comment by Nobodaddy** [comment]
Excellent? No!
Forget it, guys!
Only nerds or fossils like me love shortcuts. Come back to the real world: The average user prefers mouse clicks and doesn't give a damn that this is more lengthy. But a roundabout way with 3 keys pressed simultaneously overstrains the normal Prestashop user.
And btw you didn't consider the keyboard language. ALT+SHIFT+D for example on a German Windows keyboard behaves like ALT+D(atei) and opens the browser menu. 
It's not easy to write a software for foreign languages ... :D

**Review by Nobodaddy — COMMENTED** [review]
cancelled

**Comment by haveyougotanypets** [comment]
Hi

I can see people are keen on the idea of shortcuts however I really feel I have to agree with Nobodaddy on this one.

Adding keyboard shortcuts is always going to cause problems, especially if you overload standard design patterns. The fact that they are default with no way to turn off doubly so. 

In the real world the average users of this plaftorm are going to be office admin assistants. From (painful) experience it is hard enough to teach this kind of user the standard ctrl-z,x,c,v for their daily grind with spreadsheets / word. The last thing you want to do is drop in a load of platform specific accelerators and confuse the hell out of them, sending them back to the old right click menu safe place.

If you are lucky enough to get a user that is comfortable with keyboard shortcuts, it is very likely they are going to be copying and pasting the data from a product spreadsheet into the system. You don't want a system that rewards users for understanding keyboard shortcuts allowing them to create new products, e.t.c but at the same time punish them for not being able to use the word wide standard shortcuts inside the actual forms on these pages.

I do like the idea of these keys for power users. But I would very strongly suggest the are disabled as default and power users can turn them on ideally with their ability to provide their own mappings if they wish, as per Nobodaddy's comment about German systems, it is going to be very hard to standardise for internationalised users.

If people are really set I would agree with xBorderie and map them to a 3 key mapping so that only the very keen can use.

**Comment by Nobodaddy** [comment]
👍

**Comment by xBorderie** [comment]
@haveyougotanypets 
> If people are really set I would agree with xBorderie and map them to a 3 key mapping so that only the very keen can use.

[As you can see](https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/js/bundle/product/form.js#L982-L1025), this is what we went with.

**Pull request merged**
