### PR TITLE
Fix var_export() with missing 2nd return=true arg

### PR DESCRIPTION
**Pull request by staabm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Fixing a typo / fix wrong exception messages. This code is tested by behat.
| Type?             | bug fix 
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Behat tests should run correctly
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/9936425423
| Fixed issue or discussion?     | 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

A new feature I have implemented recently in PHPStan detected this typo errors

https://github.com/phpstan/phpstan-src/pull/3225

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by matks — COMMENTED** [review]
Hello @staabm and thank you for the PR. Could you please fill in the PR description ;) ?

**Comment by staabm** [comment]
Thanks for getting back to me. Does it work like that?

**Review by matks — APPROVED** [review]
Still a few items left ;) but I fixed it for you

One question though: I am not sure to understand the connection between your phpstan PR and these changes. In this PR you add a 2nd arg to var_export.

Aaaah I get it : without this `true` there is no return value 😄 . I approve the PR then

**Review by boherm — APPROVED** [review]

**Comment by staabm** [comment]
> Still a few items left ;) but I fixed it for you

thanks

> One question though: I am not sure to understand the connection between your phpstan PR and these changes. In this PR you add a 2nd arg to var_export.
> 
> Aaaah I get it : without this `true` there is no return value 😄 . I approve the PR then

right, sorry for beeing not precise enough. I tweeted about the new PHPStan rule here: https://x.com/markusstaab/status/1811764512841695238

**Review by florine2623 — APPROVED** [review]
CI green, no need for manual testing

**Comment by kpodemski** [comment]
thank you @staabm !

**Pull request merged**
