### PR TITLE
Add Malagasy language.

### PR DESCRIPTION
**Pull request by OneDotIT**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Adding the language details, completes #14185 
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Related to #14074, completes #14185
| How to test?  | By Adding the Malagasy language.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14349)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @OneDotIT 

When I try to translate I found this error 
image

**Comment by OneDotIT** [comment]
@sarahdib, this error has been fixed @ #14185. 
I made the initial clarification in this comment: https://github.com/PrestaShop/PrestaShop/issues/14074#issuecomment-500508124

and this comment: https://github.com/PrestaShop/PrestaShop/issues/14074#issuecomment-505332891

And yes, my description for this pull request might be is missing little details.

So just to point out (no need to go through the previous links), to add a new language in the system, we need modify two separate files,  **/app/Resources/legacy-to-standard-locales.json** and **/app/Resources/all_languages.json**, the first one identify the ISO codes, and the second represent the drop menu -my suspicion-. These would be the pull request #14185 and #14349(this one)

**Comment by PierreRambaud** [comment]
Please combine both PR into one :smile: If one can't work without another it's not a good idea :/

**Comment by PierreRambaud** [comment]
Closed in favor of #15063

**Pull request closed without merging**
