### PR TITLE
Add `theme_dir` smarty global var in front contoller

### PR DESCRIPTION
**Pull request by hendaghanmi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Add `theme_dir` smarty global var in front contoller
| Type?             | improvement
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | You can access any where in the tpl `{$urls.theme_dir}`
| Possible impacts? |  N/A

### CODE REVIEW

**Review by PululuK — APPROVED** [review]
Thanks @hendaghanmi

**Review by lartist — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello @hendaghanmi ,

Thank you for your PR, but some checks were not successful!

image

Ping @PrestaShop/prestashop-maintainers  could you check it please?

Many thanks !

**Comment by nicosomb** [comment]
@MhiriFaten it seems that sanity tests are KO everywhere, see https://github.com/PrestaShop/PrestaShop/pull/30387 (same error).

**Comment by PululuK** [comment]
Hi @MhiriFaten @nicosomb 
All sanity setups failing, is not related to the PR.

**Review by MhiriFaten — COMMENTED** [review]
Thank you @PululuK for your feedback,
But we can not test it until the sanity setups will be repaired.

**Comment by kpodemski** [comment]
@MhiriFaten maybe it would be better to keep "Waiting for QA" but with "Blocked" label? otherwise it will be hard to track

**Review by nicosomb — APPROVED** [review]

**Comment by PululuK** [comment]
Hi @MhiriFaten it is good now :)

**Review by FabienPapet — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @hendaghanmi 

Thank you for your PR, I tested it and it works, as we can see here :

[Untitled_ Nov 29, 2022 3_20 PM.webm](https://user-images.githubusercontent.com/100699445/204554082-74acaa25-f088-401a-9f41-2b8bad2df30e.webm)

Nice first PR ! 

Thanks !

**Comment by PululuK** [comment]
Thanks @hendaghanmi @AureRita

**Comment by hendaghanmi** [comment]
Thanks @PululuK

**Pull request merged**
