### PR TITLE
Fix auto-remove carrier-specific voucher when changing carrier

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Fix auto-remove carrier-specific voucher when changing carrier
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3307 http://forge.prestashop.com/browse/BOOM-5218 http://forge.prestashop.com/browse/BOOM-5219
| How to test?  | Add a carrier-specific voucher. Check voucher is automatically removed when changing carrier. Test the same behavior with empty-code voucher

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9172)

### CODE REVIEW

**Comment by tomlev** [comment]
same as https://github.com/PrestaShop/PrestaShop/pull/9142

**Comment by PierreRambaud** [comment]
Your PR #9142 doesn't include smarty fix, is it normal to have this one in this PR?

**Comment by tomlev** [comment]
smarty fix was required by QA to test this PR, and is already merged in develop

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
So I approve it again! :)

**Comment by PierreRambaud** [comment]
Thansk @tomlev

**Pull request merged**
