### PR TITLE
[-] Project : Fix undefined encoding variable which caused never reached condition for iso-8859-1 encoding

### PR DESCRIPTION
**Pull request by webmake**
Fix undefined encoding variable which caused never reached condition for iso-8859-1 encoding.

### CODE REVIEW

**Comment by webmake** [comment]
Can't remember how this was initiated or noticed, but according current code state such stack is possible:
blockrss.php:125 hookLeftColumn()
blockrss.php:147 getEnclosure()
AtomElement.php:202 getText()
Atom.php:236 parseTextConstruct()
Atom.php:278 traverseNode()
Type.php:378 processEntitiesForNodeValue()
Type.php:339 -> $current_encoding undefined

**Comment by julienbourdeau** [comment]
Hi,

How can we test this please?

**Comment by webmake** [comment]
Well, first of all $current_encoding is undefined, so `elseif ($current_encoding == 'iso-8859-1')` this condition is always false and never ever fullfiled. In connection with such situation, there is variable assignment, that makes sense to have common for both conditions, either that elseif is completely unnecessary. 
Also now I've noticed https://github.com/pear/XML_Feed_Parser/blob/master/XML/Feed/Parser/Type.php#L351 similar realization.

**Comment by aleeks** [comment]
Hello @webmake,
This file is not longer used on `develop`, feel free to add your fix on `1.6.1.x` branch!
Thank you for your contribution!

**Pull request closed without merging**
