### PR TITLE
Fix products not centered on home and search pages with classic theme

### LINKED ISSUE #23372: Products not centered in home with default theme
#### Describe the bug

Products are not centered correctly in the home container

#### Steps to Reproduce

1. Install PS
2. Check home product block

image

#### Additional information

* PrestaShop version: PS 1.7.7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Home and Search product list has wrong width and aligns
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23372.
| How to test?      | Build assets, go on home or search page and see issue to get the problem!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23388)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
Hi @NeOMakinG I still have the initial issue with your PR (confirmed by @khouloudbelguith )
image
@khouloudbelguith also have an error in terminal when running the `npm run build` command
The error:
`ERROR in ./js/theme.js
Module build failed: Error: EISDIR: illegal operation on a directory, read`

**Comment by NeOMakinG** [comment]
@SD1982 I think it's due to your error, let me test it again right now

**Comment by SD1982** [comment]
After a new test and some help (thanks @NeOMakinG :+1: ) it looks ok now 
**home page before**
image
**home page after**
image
**search page before**
image
**search page after**
image

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @SD1982

**Pull request merged**
