### PR TITLE
Merge 8.1.x into develop 2303

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop 2303
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |  https://github.com/lartist/ga.tests.ui.pr/actions/runs/4540484314
| Fixed ticket?     |
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @matthieu-rolland

**Review by SharakPL — DISMISSED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @matthieu-rolland 

I have launched the automated tests on this PR and here is the result of the tests run: https://github.com/HanaRebaiQA/testing_pr/actions/runs/4509131234 

Thank You @nesrineabdmouleh for your investigation on it :)

**Comment by nesrineabdmouleh** [comment]
Hello @matthieu-rolland,

After investigation, the problems of UI tests are about a missing selectors in the PR.
Please check these lines of code => 
https://github.com/PrestaShop/PrestaShop/pull/31887/commits/fbbe83a7adfc1cbee4a07012198db9b8af619922#diff-ac3e622de67a454fa956473ea9a617ea03eb617bb8ce13697669034414904873L34-L43

Thank you @matthieu-rolland  and @HanaRebaiQA :)

**Review by boubkerbribri — DISMISSED** [review]
LGTM for UI tests

**Review by boubkerbribri — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by jolelievre** [comment]
Just re-ran the campaign with latest changes https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4533272957

**Comment by Progi1984** [comment]
@jolelievre I'm on it (since this morning) : https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/4501986004

**Review by boubkerbribri — DISMISSED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/committers It's now all :green_circle:  : https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/4501986004

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @matthieu-rolland 

I have launched the automatic tests. They are OK https://github.com/HanaRebaiQA/testing_pr/actions/runs/4533408727 

So, it's QA :heavy_check_mark: 

Thank You!

**Pull request merged**
