### PR TITLE
LC_CTYPE turkish

### LINKED ISSUE #16745: LC_CTYPE & Turkish Language
**Describe the bug**
If setlocale is set to LC_CTYPE variable tr_TR, some of the Turkish characters are different from the en_US definition of PHP's strtolower or strtoupper method.

This character change affects the autoloader configuration of some vendor packages. Smarty for example.

This definition causes Smarty-like Vendor packages to fail to find the classes the autoloaders want to load.

en_US -> Smarty_Internal_Undefined -> smarty_internal_undefined.php
tr_TR -> Smarty_Internal_Undefined -> smarty_ınternal_undefined.php

**To Reproduce**
We need to change the locale in Debian with tr_TR.UTF-8 to reproduce the issue ([tuto](https://www.youtube.com/watch?v=5HRpkjzJUGY) followed)
1. Try a new PrestaShop installation in Turkish language OR Try to Product Import/Export in Turkish Language

**Additional information**
PrestaShop version: 1.7.6.2
PHP version: 7.2.x

**Solution**
https://github.com/PrestaShop/PrestaShop/pull/15991

### PR DESCRIPTION
**Pull request by metineren**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If setlocale is set to LC_CTYPE variable tr_TR, some of the Turkish characters are different from the en_US definition of PHP's strtolower method.<br><br>**For example:**<br>echo strtolower ('Instance'); // en_US: **i**nstance,<br>echo strtolower ('Instance'); // tr_TR: **ı**nstance<br><br>This character change affects the autoloader configuration of some vendor packages. Smarty for example.<br><br>This definition causes Smarty-like Vendor packages to fail to find the classes the autoloaders want to load.<br><br>en_US -> Smarty_Internal_Undefined -> smarty_**i**nternal_undefined.php<br>tr_TR -> Smarty_Internal_Undefined -> smarty_**ı**nternal_undefined.php
| Type?         | bug fix
| Category?     |  CO
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes #16745
| How to test?  | You can try installation in Turkish language, you can try csv product import in Turkish language or you can try Upgrade via One Click Upgrade module in Turkish language.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15991)

### CODE REVIEW

**Comment by metineren** [comment]
My choice of category is correct. This fix covers all selected categories.

**Comment by Progi1984** [comment]
@metineren Thank you for your contribution. :hugs: 

Could you explain in an issue your initial bug for this PR (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Comment by metineren** [comment]
@Progi1984 Thank you for your reply.

For catch debug errors;

You can try installation in Turkish language, you can try csv product import in Turkish language or you can try Upgrade via One Click Upgrade module in Turkish language.

**Comment by Progi1984** [comment]
@metineren Thanks for the scenario test. Could you create an issue for linking to this PR ? Our PO team can prioritize this issue. Thanks :)

**Comment by metineren** [comment]
https://github.com/PrestaShop/PrestaShop/issues/16745 issue created.
I apologize for the delay.

**Comment by metineren** [comment]
Hello again @Progi1984,

In the issue I reported (https://github.com/PrestaShop/PrestaShop/issues/16745), @khouloudbelguith and I together confirmed the existence and cause of the problem.

I would like you to process my pull request.

Best regards

**Comment by Progi1984** [comment]
@metineren Hi, Best wishes for this new year. The problem that I have with this PR is side effect. Because changing locale may have some effects on another libraries. 

What do you think about that @PrestaShop/prestashop-core-developers ?

**Comment by metineren** [comment]
Hi @Progi1984,

Best wishes for this new year you too.

The solution actually not side effect. Because too many servers preventing setlocale LC_CTYPE method. Too many servers keeps LC_CTYPE to "C" value. C Language standars same as to EN language.

Servers outside the majority do not prevent the LC_CTYPE value from being changed in php' s setlocale function.

In this case, issue #16745 occurs for languages in the latin extended language group, such as Turkish. 

LC_CTYPE affects strtolower & strtoupper (Case Conversions) functions.

This error results in a fatal error for the Turkish language at the time of installation and installation cannot be completed.

Many potential Turkish users who do not know the coding, give up installing PrestaShop because of an error they cannot solve on installation process. We're talking about a country where 80 million people live.

I guarantee that there will be no errors when you perform the merge.

>  What do you think about that [@PrestaShop/prestashop-core-developers (https://github.com/orgs/PrestaShop/teams/prestashop-core-developers) ?"

I don't understand this part. Is this a job offer? Can you explain this part a little?

**Comment by PierreRambaud** [comment]
I'm more in favor of deleting everything in about `setlocale` in the source code because we are using CLDR and a custom translate system :thinking:

**Comment by Progi1984** [comment]
+1 @PierreRambaud The advantage is the config system will not be overridden.

**Comment by metineren** [comment]
Hi guys, @Progi1984, @PierreRambaud,

If you can see https://github.com/PrestaShop/PrestaShop/blob/develop/config/config.inc.php [line 155](https://github.com/PrestaShop/PrestaShop/blob/develop/config/config.inc.php#L155) showing a important comment, LC_ALL and LC_CTYPE same effect on php's case convertion functions.

Also, I would like you to carefully look at the https://github.com/PrestaShop/PrestaShop/issues/16745 before making a decision.

Because me and @khouloudbelguith simulate this issue and tested it

Best regards

**Comment by Progi1984** [comment]
Hi @mehdi-ghezal, thank you for your feedback.

We agree with you. We (me and @PierreRambaud) think that the locale configuration must not be done at the PHP level but must be managed by the server configuration. So it's why we are in favor of deleting everything in about `setlocale` in the source code.

**Comment by matks** [comment]
Hi @Progi1984 @PierreRambaud I'm confused about the state of this PR

**Comment by Progi1984** [comment]
@mehdi-ghezal : Could you continue this PR ?

**Comment by PierreRambaud** [comment]
Hi @metineren ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
