### PR TITLE
[<3] Core: Thank you to all our community! I love you <3! Meow! Meow! Meow!

### PR DESCRIPTION
**Pull request by PuffDaddyCat**
Meow! I am the PrestaShop's cat.
I really want to thank all our developer community. Thank you for your help, your dedication and your pull requests! 

I invite all of you to the PrestaShop Day! Just enter the code BDB0GF  on http://www.prestashopday.com/

Meow! Meow! Meow!
Meow!
Meow!
Meow! Meow! Meow!

### CODE REVIEW

**Comment by DamienMetzger** [comment]
Thank you, Cat!

**Comment by Shudrum** [comment]
:smiling_imp:

**Comment by Quetzacoalt91** [comment]
image_1-cart_default

**Comment by Shudrum** [comment]
:cat:

**Comment by Quetzacoalt91** [comment]
image_1-cart_default

**Comment by Quetzacoalt91** [comment]
image_1-cart_default

**Comment by Quetzacoalt91** [comment]
Lol, très bon

**Comment by sfroment42** [comment]
XQ48QK

**Pull request closed without merging**
