### PR TITLE
Fix country change in checkout form

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | This PR use #7595 as base. It will fix the bug after a country change in checkout form, and an issue with the cancel button
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2227
| How to test?  | Follow steps in BOOM-2227

### CODE REVIEW

**Comment by vincentbz** [comment]
And it works^^ 


bradpitt

**Comment by vincentbz** [comment]
By the way, is it possible to have it on the 1.7.1.x branch please ? So that it can be merged in the 1.7.1.1 version . Thanks !

**Comment by Quetzacoalt91** [comment]
PR moved to the branch 1.7.1.x

**Comment by vincentbz** [comment]
Danke !

**Comment by martinfojtik** [comment]
Hi @Quetzacoalt91, good job.

**Comment by maximebiloe** [comment]
Thank you @Quetzacoalt91

**Comment by kingreym** [comment]
It still not working.

**Comment by kingreym** [comment]
Never ever again gonna use prestashop. Trash of trashes.

**Comment by kamilko** [comment]
@kingreym You probably using not default theme or you didn't update correctly. I had similar issue but it's resolvable if you modify manually own theme as you can find in here pressing: [Files changed](https://github.com/PrestaShop/PrestaShop/pull/7710/files) (last two tpl files).

**Comment by kingreym** [comment]
@kamilko thx for your response, but I'm done with open-sources.

**Pull request merged**
