### PR TITLE
Create, edit, delete, view, sort, filter a file

### PR DESCRIPTION
**Pull request by hadrich-hatem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allow to : Create file in the Back Office. Edit file in the Back Office. Check file in the Back Office. Delete file in the Back Office. Delete file with bulk action in the Back Office. Check the created and edited file in the Front Office. View file in the Back Office. Sort files in the Back Office. Filter files in the Back Office
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run this script path=full/16_file/* npm run specific-test -- --URL=BackOfficeURL --DIR=DownloadDirectory

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8887)

### CODE REVIEW

**Comment by hadrich-hatem** [comment]
Hello @mickaelandrieu,
The rebase of this PR done.
Thanks :)

**Comment by mickaelandrieu** [comment]
@fatmaBouchekoua wdyt? I'm not the best to review this contribution :)

**Review by fatmaBouchekoua — DISMISSED** [review]
It seems good for me

**Comment by marionf** [comment]
I will check it after the code review of @fatmaBouchekoua

**Review by fatmaBouchekoua — APPROVED** [review]

**Pull request merged**
