### PR TITLE
[-] Class: Address / Use getValue() instead of getRow() in isUsed() m…

### PR DESCRIPTION
**Pull request by PrestaEdit**
…ethod.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi @PrestaEdit,

Thnak you for your PR. You are changing return type from int / false to true/ false here don't you think some moduel samy rely on that ?

Regards

**Comment by PrestaEdit** [comment]
Hi @gRoussac ,

You maybe right on this. Even if I think that it will be not a real problem, but I will agree with you ;-)

**Comment by PrestaEdit** [comment]
See this one #4158 : it's the same, but with correction.

**Comment by prestamodule** [comment]
#4159 ; on the right branch.

**Pull request closed without merging**
