### PR TITLE
[*] Fixed bug in download_product.txt

### PR DESCRIPTION
**Pull request by Nobodaddy**
Misspelled variable

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Thank you :)

Maybe we should think about making this case insensitive. What do you think ?

**Comment by Nobodaddy** [comment]
I'm all ears! How (and where) would you like to make this case insensitivity work? In this place it wouldn't make sense. And I doubt that it would make sense in the array of __OrderHistory.php__ either:
>                $data = array(
>                    '{lastname}' => $customer->lastname,
>                    '{firstname}' => $customer->firstname,
>                    '{id_order}' => (int)$order->id,
>                    '{order_name}' => $order->getUniqReference(),
>                    '{nbProducts}' => count($virtual_products),
>                   ** '{virtualProducts}' => $links**
>                );

**Comment by julienbourdeau** [comment]
I was just thinking out loud. Because the var has is surrounded with curly brackets I forgot it was a smarty variables. I thought it was some sort of `preg_replace` :(
My bad ^^

**Comment by jnadaud** [comment]
:+1:

**Pull request merged**
