### PR TITLE
Update keyboard shortcut in product page for preview

### PR DESCRIPTION
**Pull request by AntoineMille**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | BO: Update keyboard shortcut in product page for preview
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1755
| How to test?  | Go to the product page in the BO and test CTRL+E

### CODE REVIEW

**Comment by aleeks** [comment]
Thank you @AntoineMille

**Comment by Dylan-Chapman** [comment]
I don't understand. Why are we overriding default browser shortcuts like this? Browser shortcuts commonly bind to Ctrl+letter. Why don't we set these shortcuts to Alt+letter instead? This way we don't block the browser's native print, bookmark, etc.

**Comment by vincentbz** [comment]
Hi @Dylan-Chapman 

We are working on a better way to use shortcuts, according to people's returns and best practices

**Comment by dave-ps** [comment]
way to break standards

**Comment by AntoineMille** [comment]
Hi,
Pending a decision, please see : https://github.com/PrestaShop/PrestaShop/pull/7449

Regards,

**Pull request merged**
