### PR TITLE
Add possiblity to customize the installer based on template from a module

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add possiblity to customize the installer based on template from a module
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/10503902428
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### How to test

1. Clone this PR
2. Download this theme [install_theme.zip](https://github.com/user-attachments/files/16662446/install_theme.zip)
3. Unzip the module and place it in the `modules` folder
4. Go to the installation page `/install-dev`
5. The footer should contain an extra paragraph with a text for the help center

Capture d’écran 2024-08-19 à 17 38 28

### How to implement in the modules

The install templates are now overridable by a module, the core loops through all the module folders and search for a `install-theme/{template}.php` file, if it exists it is included in place of the core one. Example to override the footer you need a `install-theme/footer.php` file

```php
<?php
    /** Keep the initial footer content we just need to add an extra paragraph */
    include_once _PS_INSTALL_PATH_ . '/theme/views/footer.php';
?>
<p>
My extra content
</p>
```

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Hlavtox** [comment]
@jolelievre Just a suggestion - I guess the usecase is to customize the installer for Prestashop SA distribution right?

Can't you just modify the installer directly? Once installed, the folder is deleted anyway, so the core will be the same as the opensource distro.

**Review by kpodemski — APPROVED** [review]
Simple and effective 👍🏻

**Comment by jolelievre** [comment]
> @jolelievre Just a suggestion - I guess the usecase is to customize the installer for Prestashop SA distribution right?
> 
> Can't you just modify the installer directly? Once installed, the folder is deleted anyway, so the core will be the same as the opensource distro.

Hi @Hlavtox I can't change the installer directly because the content that needs to be added for the PrestaShop SA edition is a bit commercial, in order to prevent adding commercial content in the open source project I think it's better to improve it and allow some additional ways to customize it

The installer had no such need before, the modification is quite small and won't have any impact for the OS release thus it won't be affected by this change but it allows us to integrate commercial content cleanly without polluting the OS core

**Comment by Hlavtox** [comment]
@jolelievre Hey, what I meant was to change it, when you build the PrestaShop SA edition, in your build script. :-)

If we install OS release and SA release, we both delete the install folder after the install, and we both end up with the same core, right? So, does it matter that the installer is different?

**Review by Hlavtox — APPROVED** [review]
All good, but I think Prestashop SA edition could just hardcode it, comment above. 👍

**Comment by jolelievre** [comment]
> @jolelievre Hey, what I meant was to change it, when you build the PrestaShop SA edition, in your build script. :-)
> 
> If we install OS release and SA release, we both delete the install folder after the install, and we both end up with the same core, right? So, does it matter that the installer is different?

Yep I also thought about this possibility, but I don't think the builder should be responsible for this There is a module in the PrestaShop SA edition that brings all the modification needed to the core (new homepage, new menu, previously also the reskin of the BO), so it should be this module's responsibility to bring any modification in the installer as well

This way if other customization is needed they would be done in the module not in the builder. It seems cleaner to me to separate the responsibilities this way

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional I guess this is something that can be tested by a developer?

**Comment by Robin-Fischer-PS** [comment]
Indeed @kpodemski , it can be tested by a dev. Thanks for the ping :)

**Review by matks — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
@jolelievre  Seems to be working:

Capture d’écran 2024-08-21 à 19 33 47

I tested this by making an override of the footer, in an already installed module, and then visited the install page.

LGTM, can it be merged ? I think you wanted some confirmation from other people at PS ?

**Comment by matthieu-rolland** [comment]
we can merge when ui tets are green 👍 there's still an error, should be fixed by restarting failed test

**Comment by matthieu-rolland** [comment]
thank you @jolelievre !

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by PululuK** [comment]
👀

**Pull request merged**
