### PR TITLE
Avoid global markup duplicate in checkout.tpl

### LINKED ISSUE #21719: Avoid global markup duplicate in checkout.tpl
#### Is your feature request related to a problem?

In classic theme, `templates/checkout/checkout.tpl` file redefine global markup (`<html><head>...</head><body>....</body></html>`) instead of use Smarty template inheritance.

#### Describe the solution you'd like

Use Smarty template inheritance to avoid duplicate of global markup. I'll make a PR soon.

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Use Smarty template inheritance to avoid duplicate of global markup
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21719
| How to test?  | Check if page layout isn't broken
| Sponsor company | @Creabilis

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21725)

### CODE REVIEW

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Hey @micka-fdz 

Thanks for your contribution.

Can you explain a bit further what you did ? It looks like you're removing some hooks that I can't manage to find anywhere, else like `displayWrapperBottom`, maybe this is right, but removing them can introduce some BC, this looks touchy.

Hope you understand that I just ask some explains about your changes before going further!

I think they're inside the layout or something like this, but let's reassure us for the review :)

If the final markup is the same, that should be ok, overwhise we may need to tag is as a BC

**Comment by micka-fdz** [comment]
Hello @NeOMakinG and thanks for your return.

Indeed, `displayWrapperTop` and `displayWrapperBottom` hooks are already in main layout file : `templates/layouts/layout-both-columns.tpl`. I just redefined necessary Smarty blocks : `header`, `footer` and `content`.

Moreover, I compared the markup of the before/after page and there is no difference.

**Comment by PrestaSafe** [comment]
Very good improvement, i do that for every project !

**Review by NeOMakinG — DISMISSED** [review]
Looks fine to me, thanks @micka-fdz

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@micka-fdz It seems that all sanity are broken : https://travis-ci.com/github/PrestaShop/PrestaShop/builds/197674268 

Could you fix it ? Thanks

**Comment by jf-viguier** [comment]
@Progi1984 it's seem that there is a timeout issue only on checkout test, can you help ?

**Comment by jf-viguier** [comment]
@Progi1984 how to restart the check ? It's a timeout not related to this pr I guess

**Comment by Progi1984** [comment]
@jf-viguier Sorry, I was disconnected this week end. I retry all failed job on Travis. 

@micka-fdz Have you tried sanity tests in local ?

**Comment by micka-fdz** [comment]
Hi @Progi1984, no I didn't tried sanity tests in local.

The error seems to be on :

> should proceed to checkout and check Step Address

I tried and I've no problem with checkout steps. What should I do?

**Comment by NeOMakinG** [comment]
@boubkerbribri wdyt of these broken sanity tests ?

**Comment by boubkerbribri** [comment]
@NeOMakinG I got this error when truing to access the checkout page 
image


To see what's happening, you can run this command 
```
cd tests/UI/
npm i 
HEADLESS=false TEST_PATH="sanity/06_checkoutFO/01_orderProduct.js" URL_FO=shopUrlFO/ npm run specific-test
```

**Comment by micka-fdz** [comment]
Ok I got it !

It seems there was duplicate with Smarty blocks `{block name='header'}` and `{block name='footer'}`.
I removed theses useless blocks from `checkout/_partials/header.tpl` and `checkout/_partials/footer.tpl`.

Thanks @Progi1984, @NeOMakinG and @boubkerbribri !

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1NMCsk7nchxr1TKKeynThyPXgnoUweQWY/view?usp=sharing

Thanks!

**Comment by PierreRambaud** [comment]
Thanks @micka-fdz

**Pull request merged**
