### PR TITLE
Use json_encode instead of serialize

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Use json_encode() instead of serialize(). Many thanks to ROBIN PERAGLIE from RIPS TECHNOLOGIES
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4804
| How to test?  | test if there is no regression: change of delivery option on cart / filter (especialy date one) still works on AdminOrders

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8761)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by prestamodule** [comment]
http://forge.prestashop.com/browse/BOOM-4804 goes to 404, what is the right link?

**Comment by Quetzacoalt91** [comment]
This is the right link. You cannot access it because specific rights have been set. :)

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
@tomlev Could you please create a copy of this PR based on `1.7.2.x`? Thanks!

**Comment by eternoendless** [comment]
Thank you @tomlev

**Pull request merged**
