### PR TITLE
Remove not needed concatenation in meta title

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | PR #5796 was merged before I can comment on this line. It's remove a concatenation not needed |
| Type? | code |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | No need to test. |

### CODE REVIEW

**Comment by maximebiloe** [comment]
Thank you!

**Comment by xBorderie** [comment]
Keen eye!

**Comment by inetbiz** [comment]
Why is site name added back into the title. There is no need for this anymore with google rankbrain and bing's use of schema.org for organization schema. We need the character count available to put better SEO titles.

**Comment by xBorderie** [comment]
This PR is not adding the title back, it is removing three characters: `.''`, which are indeed useless :)

**Comment by inetbiz** [comment]
AH! =)

**Pull request merged**
