### PR TITLE
Allow to import product with quantity set to 0

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This change allow to import qty change for a product to set qty to 0 |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | no |
| How to test? | Try to import .csv with 2 columns, id;qty, try to set qty 0 from import file, now you can't, after this change you can |
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @kpodemski,

Why are you removing all casting to integer?
I understand this modification (https://github.com/PrestaShop/PrestaShop/pull/6434/files#diff-7bdf6b540c21355166c0d726ffb9bf81R2214) but I don't get why you're removing the cast.

Regards

**Comment by aleeks** [comment]
Hello

@maximebiloe For `StockAvailable::setQuantity()`, it's cast in the function : `$stock_available->quantity = (int)$quantity;`

@kpodemski But for `$stock_manager->addProduct()` I think it's needed because, it's not cast in this function. What do you think ?

**Comment by kpodemski** [comment]
@aleeks @maximebiloe  you're right guys, changed

**Comment by aleeks** [comment]
Hello @kpodemski you remove your other changes ?! o_O

**Review by maximebiloe — APPROVED** [review]

**Comment by kpodemski** [comment]
@aleeks yeah, there were not really needed, for some reason i assumed that 0 cannot be integer, lololol :skull:

**Comment by aleeks** [comment]
@kpodemski okeeeeeey, test & merge ! nice!

**Comment by kpodemski** [comment]
@aleeks travis not really likes me i guess...

**Comment by aleeks** [comment]
Thank you!

**Pull request merged**
