### PR TITLE
CCC should be enabled by default after PS installation

### LINKED ISSUE #37145: CCC should be enabled by default after PS installation
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After clean PS installation we enabled by default filesystem cache, but not CCC for JS/CSS/Apache. I don't see any reason for that, I think, this should be enabled everytime.
Untitled

### Expected behavior

CCC should be enabled by default. (CSS, JS, Apache)

### Steps to reproduce

1. Install PS9
2. Go to "Advanced Parameters" -> "Performance"
3. scroll down to "CCC (Combine, Compress and Cache)"

### PrestaShop version(s) where the bug happened

9.0.0

### PHP version(s) where the bug happened

8.3

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

https://www.openservis.cz/

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Already discussed here: #37145
| Type?             | improvement
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | install prestashop and you will see this 3 options in performance section will be enabled
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/11570386280
| Fixed issue or discussion?     | Fixes #37145
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I removed "Needs autoupgrade PR" because the new behavior should be only for the new installations.

**Review by florine2623 — APPROVED** [review]
Hello @ShaiMagal ,

Before:
Screenshot 2024-10-29 at 14 32 31

After:

Screenshot 2024-10-29 at 14 39 31

Works as expected, it is QA ✅ 
Thanks!

**Comment by Hlavtox** [comment]
Thank you @florine2623 :-)

**Pull request merged**
