### PR TITLE
Fix quick view in safari browser

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | Error when clicking on Quick View button.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1955
| How to test?  | Go to home page and click on Quick View button on product

### CODE REVIEW

**Comment by xBorderie** [comment]
You'll need to rebase, I think :)

**Comment by Quetzacoalt91** [comment]
Done :)

**Comment by aleeks** [comment]
Is there the same problem there?https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/cart.js#L223

**Comment by dSkrbic** [comment]
Hello,

Result in Q&A tests are dubious:
1- No error when clicking on QuickViewButton, but
2- Integration is awful, see screesnhot:

image

**Comment by xBorderie** [comment]
The image overflow looks a lot like this issue: http://forge.prestashop.com/browse/BOOM-2016

**Comment by fatmaBouchekoua** [comment]
Hello @dSkrbic ,
The integration bugs where already present before correcting this bug.

**Comment by maximebiloe** [comment]
Thank you @fatmaBouchekoua!

**Pull request merged**
