### PR TITLE
Moved the misplaced facets override file for ps_facetedsearch module

### LINKED ISSUE #24432: theme/XXX/templates/catalog/_partials/facets.tpl is not used
#### Describe the bug

Read this https://github.com/PrestaShop/PrestaShop/issues/23104

Hovewer, if i a place this file in the `themes/XXXX/modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl` the override works !

#### Expected behavior

When i edit the templates/catalog/_partials/facets.tpl  file, it should override the default tpl.

#### Steps to Reproduce

1. Create a theme
2. Change facets.tpl content !
3. Look, no effect.

#### Possible solution

Move the file to the `themes/XXX/modules/ps_facetedsearch/views/templates/front/catalog/facets.tpl` to avoid confusion.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by henri9813**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The facet override file is misplaced, not interpreted in the current path
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/24432
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | No impact

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24433)

### CODE REVIEW

**Comment by henri9813** [comment]
Your bot  should stop drinking alcool on monday ! :D

**Comment by PierreRambaud** [comment]
> Your bot should stop drinking alcool on monday ! :D

It's because you don't specify the `Fixes #` which is how GitHub work.
You also don't provide any description or a way to test it and the branch is not the same as the one you target.

If we have to read everything from the issue and do a reverse engineering to understand what you are trying to do, it will be a waste of time for us as you already did the job. This is the reason why we are waiting for contributor to help us and provide us a good description explaining why and how they did it :)

**Comment by henri9813** [comment]
Hello, 

Updated @PierreRambaud .

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
What about this file, I'm afraid you rename the wrong file :thinking: 
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/ProductListingFrontController.php#L157

**Comment by henri9813** [comment]
@PierreRambaud  i don't know, but this currently doesn't work. 

I don't know if it's normal, i didn't look in the controller to be honest.

I integrate the solution of https://www.prestashop.com/forums/topic/1016423-modifier-apparence-de-la-navigation-%C3%A0-facettes/ which also works for me

**Comment by PierreRambaud** [comment]
> @PierreRambaud i don't know, but this currently doesn't work.
> 
> I don't know if it's normal, i didn't look in the controller to be honest.
> 
> I integrate the solution of https://www.prestashop.com/forums/topic/1016423-modifier-apparence-de-la-navigation-%C3%A0-facettes/ which also works for me

The file you change is related to the Core whereas you are trying to change the file in ps_facetedsearch :thinking:

**Comment by henri9813** [comment]
I do not understand at all. :/  

I am available on the prestashop slack if you want.

**Comment by PierreRambaud** [comment]
You are looking for this file:
https://github.com/PrestaShop/ps_facetedsearch/blob/d8d369419a2e68180748f865bc81d50eef86025c/src/Product/SearchProvider.php#L236
and not this one: https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/ProductListingFrontController.php#L157

Both are used but in a different context.

**Comment by henri9813** [comment]
Warning !!!!

The facets.tpl delivered by the classic theme is outdated ! Keep warning, i try to find the updated facets.tpl.

In this case, how should i make an override  of the tpl file ?

**Comment by henri9813** [comment]
Okay, i'm totally lost.

So, what is the _partials/facets.tpl which is it outdated against the module template ?

**Comment by henri9813** [comment]
In the Classic theme facets.tpl, the slider doesn't exist and it's replaced by a radio button.

**Comment by PierreRambaud** [comment]
`_partials/facets.tpl` is used as default behaviour for some modules that are using the facet system https://devdocs.prestashop.com/1.7/development/components/faceted-search/

**Comment by henri9813** [comment]
Hmmm, so, what should be the good files to be renamed / moved to make this file usefull ?

**Comment by PierreRambaud** [comment]
> Hmmm, so, what should be the good files to be renamed / moved to make this file usefull ?

No one has to be renamed regarding what you tried to do :thinking:

**Comment by henri9813** [comment]
I never make this file used, how should i make it usable ? 

What put this file in this directory make the template used ? :/

**Comment by PierreRambaud** [comment]
> I never make this file used, how should i make it usable ?
> 
> What put this file in this directory make the template used ? :/


When you use the faceted search system as I linked above.
https://github.com/PrestaShop/PrestaShop/pull/24433#issuecomment-839770606

I'm closing this PR as it makes no sense to merge it.

**Pull request closed without merging**
