### PR TITLE
Increase carrier delay length

### PR DESCRIPTION
**Pull request by enumag**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Increase carrier delay length
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  |

### CODE REVIEW

**Comment by xBorderie** [comment]
Could you tell us why you feel this change is necessary? Thank you!

**Comment by enumag** [comment]
@xBorderie Well obviously because 128 characters it too little for my texts here and I don't like to hack Prestashop if I can help it. How much it should be increased can be discussed (I need a little over 200 at the moment).

**Review by aleeks — APPROVED** [review]
Code looks ok

**Comment by enumag** [comment]
@aleeks I have to move the SQL ALTER TABLE to different file here. Should I put it into 1.6.1.14.sql or 1.6.1.15.sql? (I would prefer this to appear in 1.6.1.14 of course.)

**Comment by maximebiloe** [comment]
Hello @enumag,

I plan to include your pull request into 1.6.1.14. 
Could you move the sql update into 1.6.1.14.sql please?

Regards

**Comment by enumag** [comment]
@maximebiloe Done.

**Comment by aleeks** [comment]
Ooooops @enumag 
The change on db_structure is missing isn't ?

**Comment by enumag** [comment]
@maximebiloe 

> The change on db_structure is missing isn't ? Can you change it please ?

What? I don't know what you're talking about...

**Comment by enumag** [comment]
@maximebiloe Oh you mean the db_structure.sql file, right? Sorry. I didn't know this file existed. Should be ok now.

**Comment by aleeks** [comment]
Niceeeee, thank you for your reactivity! Merged right now!

**Comment by enumag** [comment]
@aleeks Thank you! Any ETA on the new release? I need to finish an upgrade of one eshop this weekend and it would be nice to do it with the new version - it contains some important fixes.

**Comment by aleeks** [comment]
pnig @maximebiloe  

07b70cbbdec2e1e7544543cb516dadf9a69c3346d96c319fdb2d331b6fcf1ba0

**Comment by enumag** [comment]
@maximebiloe It would help me a lot to have 1.6.1.14 released today. I'll be doing the upgrade tomorrow.

**Comment by Quetzacoalt91** [comment]
Sorry @enumag, the new release won't happen before next week. Publishing a new version on a Friday is never a good idea. :)

**Comment by enumag** [comment]
@Quetzacoalt91 Understood, thanks for letting me know. I'll try to somehow use the latest commit from 1.6.1.x branch.

**Comment by xBorderie** [comment]
@enumag Just so you know, [1.6.1.14 was released last Monday](http://build.prestashop.com/news/prestashop-1-6-1-14-maintenance-release/)! :)

**Comment by enumag** [comment]
@xBorderie A bit too late for me since I made the upgrade over the weekend - I manually copied some of the fixes. Thanks for the notice though.

**Pull request merged**
