### PR TITLE
Downgrade playwright to version 1.0.2

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Downgrade playwright to version 1.0.2 (it will maybe fix random fails in nightly)
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | No tests needed (Nightly should be green tomorrow)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21097)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Why not

**Review by Progi1984 — APPROVED** [review]
Nice try

**Comment by matks** [comment]
@boubkerbribri I think we might be able to check the results without having to wait for the night.

If the nigthly campaign is being run on GCP following a trigger from Travis, then we should be able to run it at will

ping @PierreRambaud

**Comment by PierreRambaud** [comment]
> @boubkerbribri I think we might be able to check the results without having to wait for the night.
> 
> If the nigthly campaign is being run on GCP following a trigger from Travis, then we should be able to run it at will
> 
> ping @PierreRambaud

Everything is here: https://travis-ci.com/github/PrestaShop/PrestaShop/settings 
and documented here: http://doc.prestashop.com/display/PSRD/PrestaShop+Nightlies

**Comment by boubkerbribri** [comment]
Thanks all, I'm waiting for travis to merge and trigger a new nightly build

**Pull request merged**
