### PR TITLE
Improve front-end accessibility

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve shop accessibility. There are many of problems with accessibility in website, this will fix at least the major ones in header, front page and product page.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Use only keyboard on webpage.

NOTE: There is bug in Bootstrap Carousel, which i can't fix. (https://github.com/twbs/bootstrap/issues/19972)

### CODE REVIEW

**Comment by xBorderie** [comment]
I am 100% for a more accessible default theme! Thank you Martin!

**Comment by maximebiloe** [comment]
Hello @martinfojtik,

Thanks for this contribution and sorry for the very late reply.
We're interested in your accessibility improvement but could your remove the CSS part, please?
We've worked with @TristanLDD (the Classic UI designer) to improve the readability on low contrast screen in #7681.

Regards

**Comment by martinfojtik** [comment]
Hi @maximebiloe , I rebased the PR. What do you want to remove from the CSS part? There is one new class `.btn-unstyle` which is used in drop down buttons. And I added a border for focused radio inputs and checkboxes.

**Comment by maximebiloe** [comment]
Sorry for the lack of precision ^^
I meant the `.btn-unstyle` part. I checked it with our UI/UX and we prefer without it.

Thanks in advance

**Comment by martinfojtik** [comment]
without this class, buttons will look ugly 😄 as you can see on the image. 
prestashop-dropdown-button
Do you have any suggestion how to style this buttons?

**Comment by maximebiloe** [comment]
I guess you don't have the latest compiled style.
Here is what is looking for right now: 

capture d ecran 2017-04-19 a 10 15 34

**Comment by martinfojtik** [comment]
I have latest styles. But in this PR I changed tag `<a>` to  `<button>`. Without `btn-unstyle` class, buttons look as you saw on the image.

**Comment by maximebiloe** [comment]
My bad, I didn't recompile the assets when I tried your PR.
So, it's ok for me the `.btn-unstyle` class.
But, can you add the pseuo-class `:focus` with an `outline` set to 0, please?
It will avoid this:
capture d ecran 2017-04-19 a 10 32 25

Then, we'll be able to merge 😉

**Comment by martinfojtik** [comment]
Sure I can remove the outline but I don't recommend to do that. Because for a keyboard user is important to see some kind of outline/border, to be able distinct which element is focused. Other focusable elements in the header don't have `outline: 0`. 

Sorry for my English.

**Comment by maximebiloe** [comment]
Yes, without the outline, we don't see when we have the focus on it. 
We tried some solutions and we found one which seems to be the less bad.
```css
.btn-unstyle {
  background-color: transparent;
  border: none;
  padding: 0;
  text-align: inherit;
  &:focus {
    outline: 0;
    .expand-more{
      color: $brand-primary;
    }
  }
}
```
It will look like
capture d ecran 2017-04-19 a 13 53 17

**Comment by martinfojtik** [comment]
ok, I added your code, it's better

**Comment by maximebiloe** [comment]
Thank you @martinfojtik for your work!

Regards

**Comment by AlexEven** [comment]
Hello, 

Can one of you tell me where the strings "Carousel buttons", "Language selector" and "Currency selector" are supposed to appear?
Didn't find it in the respective modules.
I'm trying to understand the purpose of "Carousel buttons" for translation purposes.

Thanks!

**Pull request merged**
