### PR TITLE
Respect country setting "Display tax label (e.g. "Tax incl.")" in cart and order confirmation page

### LINKED ISSUE #21484: FO - "No tax" label is displayed in the FO despite of disabling the "Display tax label" in the Countries page
#### Describe the bug

I disable all taxes but in the product page display Without Taxes

#### Expected behavior

If disable the taxes, we expected don't show anything in product page

#### Steps to Reproduce

1. Go to 'International'
2. Click on 'taxes'
3. Scroll down to 'active taxes' -> Set no
4. Clean cache
5. Clean Cache from /var/cache

How you see in the attachment screenshots I disable the taxes from everywhere that appears, but this appears in the same ways

**Screenshots**

image
image
image

#### Additional information

o_outline Información del servidor

Información del servidor Linux #1 SMP Thu Sep 17 06:10:33 EDT 2020 x86_64

Versión del software del servidor: Apache

Versión PHP: 7.2.33

Límite de memoria: 512M

Tiempo máx. de ejecución: 300

Tamaño máx. para la subida de archivos: 20M
info_outline Información de la base de datos

Versión de MySQL: 10.2.33-MariaDB-log-cll-lve

Servidor MySQL: 127.0.0.1

Nombre MySQL: albarico_test

Usuario MySQL: albarico_simchgab

Prefijo de las tablas: ps_

Motor MySQL: InnoDB

Controlador MySQL: DbPDO

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Carrier price and cart summary total do not follow the country "show tax label" setting
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Partially Fixes #21484
| How to test?      | Mark at least one country as "Display tax label (e.g. "Tax incl.")" no in country settings. Add product to basket. Use the country with label no setting as the address. Check that "tax incl" text is not shown for carrier price on delivery step and cart summary total line on the right side of the process and on the total line on order confirmation page.
| Possible impacts? | Cart functionality and showing the label in different places of the process.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25882)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi @tswfi and thanks for the contribution.

Code seems valid and logic seems valid 👍  .

There's only 1 thing that worries me: I have searched `country->display_tax_label` in PrestaShop codebase and found this usage in FrontController 
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/FrontController.php#L1578

```
protected function getDisplayTaxesLabel()
    {
        return (Module::isEnabled('ps_legalcompliance') && (bool) Configuration::get('AEUC_LABEL_TAX_INC_EXC')) || $this->context->country->display_tax_label;
    }
```

In your pull request, `$display_taxes_label` becomes true if
- tax usage is enabled
- show tax label is true at country level
- AEUC_LABEL_TAX_INC_EXC option is turned off

It's a AND logic condition: all three items must be true.

But the usage I found is a OR logic.

So I'm wondering if there's an issue about conditional logic here

**Comment by tswfi** [comment]
Module `ps_legalcompliance` is deprecated (https://github.com/PrestaShop/ps_legalcompliance) and is not installed by default (thus there is also no configuration value `AEUC_LABEL_TAX_INC_EXC` by default) The first `Module::isEnabled('ps_legalcompliance')` already returns false so the `|| country` is the only one that does something in the logic (php parses `(false && true || true)` as `((false && true) || true)`. (probably all mentions of the `ps_legalcompliance` module should be removed?)

The whole logic should probably be refactored completely to get rid of all old strangeness and have "single point of truth" for this. And for carriers the $carrier->price should only return the price (float) and leave the extra texts for the template to figure out.. but all of that is quite a bit of work and bit out of scope for this pr :)

**Review by matks — APPROVED** [review]
> The whole logic should probably be refactored completely to get rid of all old strangeness and have "single point of truth" for this [...] but all of that is quite a bit of work and bit out of scope for this pr :)

Agreed :) I approve this contribution.

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,
The problem is still not fixed when I follow the steps bellow : 
- BO>Locations>Countries>Edit countries
- Display tax label (e.g. "Tax incl.") > No
- FO>product page>Add to the cart
- The label tax incl is still shown in the attached screenshot:

image

image

Could you please check if your PR can fix the issue.

**Comment by tswfi** [comment]
@marwachelly Did a quick check and the modal comes from module ps_shoppingcart so it needs its own pr in that module repo (https://github.com/PrestaShop/ps_shoppingcart). The payment by check comes from ps_checkpayment (https://github.com/PrestaShop/ps_checkpayment) and it needs its own pr in that module repo.

Or have I misunderstood how the module repos work?

**Comment by marwachelly** [comment]
> @marwachelly Did a quick check and the modal comes from module ps_shoppingcart so it needs its own pr in that module repo (https://github.com/PrestaShop/ps_shoppingcart). The payment by check comes from ps_checkpayment (https://github.com/PrestaShop/ps_checkpayment) and it needs its own pr in that module repo.
> 
> Or have I misunderstood how the module repos work?

Hello @tswfi,
You are right those two pages belongs to the modules ps_shoppingcart and ps_checkpayment. So the issue should be fixed in each module. And regarding your PR I checked that the label (tax incl) is not present when "Display tax label" is disabled in the following pages:
-Delivery step
-Cart summary
-Confirmation page
-Checkout summary
-Final summary
https://www.awesomescreenshot.com/video/5612708?key=2f2af8aebac4b2ce5bf2a23e8478c0cb
=>issue is partially resolved => PR can be merged 
Many thanks,

**Comment by tswfi** [comment]
I will create two new issues for the modules.

**Comment by Progi1984** [comment]
Thanks @tswfi & @marwachelly

**Comment by TecnoHands** [comment]
I found the same bug in prestashop 1.7.8.7
Other user found this bug is in the classic theme -> product-prices.tpl in lines:

`{if !$configuration.taxes_enabled}
        {l s='No tax' d='Shop.Theme.Catalog'}
{elseif $configuration.display_taxes_label}
        {$product.labels.tax_long}
{/if}`

I can solve the problem (don't know if the best manner) but I think the bug is really a problem with the variable: 
"display_prices_tax_incl" => true
This value don't change anywhere I try to change it, (Specific product select without taxes, in taxes section or country config)
My code to solve this is this:

`{if $configuration.taxes_enabled && $configuration.display_taxes_label} {if $configuration.display_prices_tax_incl} {$product.labels.tax_long} {else} {l s='No tax' d='Shop.Theme.Catalog'} {/if} {/if}`

Now it's work show or unshow tax included or don't show taxes. And I think works fine too if the problem are the unchanged variable "display_prices_tax_incl" => true.

This code works fine in modal quick view too and I thested in Warehouse theme too
Images in [https://github.com/PrestaShop/PrestaShop/issues/21484](url)

**Pull request merged**
