### PR TITLE
Add manufacturer and supplier body classes

### LINKED ISSUE #29263: Add identifying classes to manufacturer and supplier
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

ProductController, CategoryController, CmsController and others provide additional identifying classes in the html `<body>` tag, like `category-id-XXX` or `category-xxxxx`. 

It would be good if we standardize it and manufacturer+supplier controllers also provide it.

### Describe the solution you'd like

Add missing classes to manufacturer and supplier controller.

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add manufacturer and supplier body classes
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29263
| How to test?      | Visit any manufacturer page and check source code `<body>` tag, see new classes.
| Possible impacts? | No

manufacturer

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hello,

Ping @PrestaShop/product-team, the issue https://github.com/PrestaShop/PrestaShop/issues/29263 is not yet validated.
Can you please check it?

Thanks!

**Comment by Hlavtox** [comment]
@PrestaShop/qa-team Related issue validated, can you put it to QA stage? Thanks!

**Comment by Hlavtox** [comment]
@kpodemski Can this be QA by a dev?

**Comment by Robin-Fischer-PS** [comment]
Hi @Hlavtox ! OK for QA by Dev :)

**Comment by NeOMakinG** [comment]
image

Same for supplier, it's QA ✅

**Pull request merged**
