### PR TITLE
Remove overwritten property: context

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | All `context: document.body` are overwritten by `context: this`.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | It is not necessary

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20472)

### CODE REVIEW

**Comment by matks** [comment]
Waho 😮  indeed
```
                        context: document.body,
			dataType: 'json',
			context: this,
```
And the latest property is the one who is kept ?

**Comment by davidglezz** [comment]
Yes.

in console:
```js
{a: 1, b: 2, a: 3}
=> {a: 3, b: 2}
```

**Review by matks — APPROVED** [review]
Approved 👍

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
Thank you @davidglezz for this PR and all of the other ones you are submitting 😃  what an awesome work ! 🎉

**Pull request merged**
