### PR TITLE
BO - Import CSV - sample for manufacturer not OK

### LINKED ISSUE #10027: [BOOM-1341] BO - Import CSV - sample for manufacturer not OK
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-1341).

- _**Reporter:**_ dragan.skrbic
- _**Created at:**_ Mon, 5 Sep 2016 17:19:19 +0200

<p>Hello,</p>

<p>le CSV d'import d'exemples de fabricant est mal mis en page. Il faut le remplacer "brands_imports" attaché dans ce ticket</p>

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | BO - Import CSV - sample for manufacturer not OK. See https://github.com/PrestaShop/PrestaShop/issues/10027 for more information.
| Type?         | bug fix
| Category?     | BO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/10027.
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/10027 please.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21351)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Many things are missing in this pull request.
The file manufacturers_import.csv is still here, and many parts are still talking about "Manufacturer" :thinking:

**Comment by PululuK** [comment]
> Many things are missing in this pull request.
> The file manufacturers_import.csv is still here, and many parts are still talking about "Manufacturer" thinking


@PierreRambaud 
I did not delete it to avoid BCs ... I don't know if there are any modules that use it .

**Comment by PululuK** [comment]
@marionf @LouiseBonnard I can't access http://forge.prestashop.com/browse/BOOM-1341
Could you download the csv file attached to this ticket please?

See https://github.com/PrestaShop/PrestaShop/issues/10027#issue-353180480

**Comment by LouiseBonnard** [comment]
Sure, @PululuK, here are the two CSV files mentioned in the Forge ticket: https://we.tl/t-k3FqQS7zLV. I hope it can help!

**Comment by PululuK** [comment]
> Sure, @PululuK, here are the two CSV files mentioned in the Forge ticket: https://we.tl/t-k3FqQS7zLV. I hope it can help!

Merci beaucoup @LouiseBonnard !

**Comment by PululuK** [comment]
@PierreRambaud  @Progi1984 

- the file name has been changed : `manufacturers_import.csv`  to `brands_import.csv`
- the old file (manufacturers_import.csv) must not be deleted to avoid BCs
- the contents of both files have been fixed

**Comment by PierreRambaud** [comment]
The `manufacturers_import.csv` can be removed, it's not used in the Core, and it's here as an example.

**Comment by PululuK** [comment]
> The `manufacturers_import.csv` can be removed, it's not used in the Core, and it's here as an example.

@PierreRambaud  If a module use it ?

**Comment by PierreRambaud** [comment]
> > The `manufacturers_import.csv` can be removed, it's not used in the Core, and it's here as an example.
> 
> @PierreRambaud If a module use it ?

It's related to how PrestaShop handle these files, we should be able to change our example.
I don't see any reason to copy what the downloadSampleAction doing with this static file :thinking:

**Comment by PululuK** [comment]
> > > The `manufacturers_import.csv` can be removed, it's not used in the Core, and it's here as an example.
> > 
> > 
> > @PierreRambaud If a module use it ?
> 
> It's related to how PrestaShop handle these files, we should be able to change our example.
> I don't see any reason to copy what the downloadSampleAction doing with this static file thinking

imagine you have an export module and it uses this file as an example too?

**Comment by PululuK** [comment]
@PierreRambaud done !

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @PululuK 

- the file name has been changed : manufacturers_import.csv to brands_import.csv
Capture d’écran 2020-10-16 à 11 11 56


- the old file (manufacturers_import.csv) has been deleted

=> Test OK

Thank you 💯

**Comment by atomiix** [comment]
Thanks @PululuK & @ngodefroy !

**Comment by PululuK** [comment]
> Thanks @PululuK & @ngodefroy !

thank you @atomiix

**Pull request merged**
