### PR TITLE
Import source files of the UIKit instead of dist files to use prestakit variables

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | We wants to use variables comming from the UIKit, so I now imported sources instead of dist files and removed some vars related to the UIKit
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Build assets on every page, and nothing should change... that's pretty hard to tell what could even change, colors, font-weight, borders... but you can compare with develop and this PR :/

⚠️ https://github.com/PrestaShop/prestashop-ui-kit/pull/123 should be merged before, also the UIKit should be updated on npm with this PR inside, we can't merge before the next UIKit version on npm, but it is testable (change "prestakit" path inside your `/admin-dev/themes/new-theme/package.json` to `NeOMakinG/prestashop-ui-kit#import-source` and then npm install npm run build, you'r uikit repo should be on develop. ⚠️ 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18396)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Tests are red because the UIKit is not udpated yet with this PR inside : https://github.com/PrestaShop/prestashop-ui-kit/pull/92

**Comment by PierreRambaud** [comment]
@NeOMakinG I add the WIP label waiting for your PR to be merge and this one rebased :wink:

**Comment by Progi1984** [comment]
@NeOMakinG PrestaShop/prestashop-ui-kit#92 is merged.

**Review by atomiix — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
@Progi1984 it can go ahead as the new uikit version is not on npm yet, it needs to wait a bit

**Comment by Progi1984** [comment]
@NeOMakinG

**Comment by NeOMakinG** [comment]
@Progi1984 it's in wip, it's broken for the moment due to a dependency problem :)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-maintainers it's now reviewable!

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG the round border is not apply anymore. 
Capture d’écran 2021-02-10 à 19 13 42
Capture d’écran 2021-02-10 à 19 13 58

Round on the input too (same with dropdown)
Capture d’écran 2021-02-10 à 19 30 59

**Comment by NeOMakinG** [comment]
@sarahdib there was a border radius 0 var, probably a miss from the rebase, that should be fine now

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Lint is :red_circle:

**Comment by NeOMakinG** [comment]
@Progi1984 should be fine now, it needed a rebase

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Sanity is broken :(

**Review by matthieu-rolland — COMMENTED** [review]
Seems like behat tests are failing on several PRs

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
Well, I need to look at it, idk why sanity fails on this one, putting this as a WIP

**Review by PierreRambaud — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Finally!! Tests are green 😆

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG Always in WIP ? or Go to QA ?

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sarahdib

**Pull request merged**
