### PR TITLE
Merge 8.0.x into develop 26 01 2023

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.0.x into develop the 26/01/2023
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Comment by nicosomb** [comment]
Tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4013327987

**Comment by lartist** [comment]
> Tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4013327987

I was doing it, but you did it first. Thanks @nicosomb

**Review by nicosomb — APPROVED** [review]
All is green, let's go!

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @lartist

**Pull request merged**
