### PR TITLE
Sort modules authors alphabetically

### PR DESCRIPTION
**Pull request by fgaroby**
| Questions | Answers |
| --- | --- |
| Branch | develop |
| Description | In the "Modules and Services" menu, sort modules authors list alphabetically |
| Type | improvement |
| Category | BO |
| BC breaks | no |
| Deprecations | no |
| Fixed ticket |  |
| How to  #test | In BO, go to "Modules and Services" menu. Check the "Authors" list |

### CODE REVIEW

**Comment by aleeks** [comment]
@vincentbz agree with this sort ?

**Comment by Quetzacoalt91** [comment]
Hmm, on which page can we see the result ? You ar not supposed to go to the old module page anymore.

Or did you want to create the pull-request on the 1.6.1.x branch ?

**Comment by aleeks** [comment]
It's only my opinion, but tomorrow, i create an account named Aaaaaaaalex & I make modules.
I can take all visibility than other module, (which can be better by the way..)

**Comment by maximebiloe** [comment]
Hello @windu2b,

I just saw with @superGB and we prefer to not add this possibility. It will complicate the interface without bringing so much. We already are able to search by the author name. Moreover, you were modifying the old 1.6 controller which is not used anymore.

Regards

**Pull request closed without merging**
