### PR TITLE
Merge 8.1.x into develop 02/04/2024

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green and UI tests green
| UI Tests          | 
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by SharakPL — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by matks** [comment]
Running UI Tests https://github.com/matks/ga.tests.ui.pr/actions/runs/8523833259

**Comment by matks** [comment]
I have multiple issues in UI Tests, but not related to code content :/

issues with starting mysql

**Comment by jolelievre** [comment]
> I have multiple issues in UI Tests, but not related to code content :/
> 
> issues with starting mysql

Hmm maybe try a few restarts and it will be fine
Just in case I launched another run https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/8526680275

**Comment by matks** [comment]
@jolelievre you have the "mysql cannot start" errors too

**Comment by SharakPL** [comment]
Please ping me when it's merged so I could rebase #35644

**Comment by matks** [comment]
Re-running https://github.com/matks/ga.tests.ui.pr/actions/runs/8523833259

I have a mix of docker compose issues and bugs about the Stocks page

**Comment by matks** [comment]
Last week multiple CI issues prevented the merge of this PR. It's been too long now, a new PR is needed

**Pull request closed without merging**
