### PR TITLE
Debug of Tools::strReplaceFirst that do not correctly compare the return of strpos + PhpDoc

### PR DESCRIPTION
**Pull request by ghost**
1. Fix issue in `Tools::strReplaceFirst` that do not correctly compare the return of `strpos`.
In fact, `strpos` may return Boolean FALSE, but may also return a non-Boolean value which evaluates to FALSE. (Like cursor equals to `0`). The comparison was incorrect and must use strictly equals to false.
2. Add PhpDoc to the `strReplaceFirst` function.
3. Optimise the usage of `strpos` that was used twice in the return string. Replaced by variable `$strPos`

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Fix the usage of `strpos` in `Tools::strReplaceFirst` and add documentation
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | See the result of `Tools::strReplaceFirst('t', 'm', 'toto');`. The replacement will be ignored when the string starts with the search character.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8708)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Review by Quetzacoalt91 — COMMENTED** [review]
For this PR we can add tests easily.To be done before merge. :)

**Comment by ghost** [comment]
@Quetzacoalt91 Is there any action required on my hand to add the tests ?

**Comment by Quetzacoalt91** [comment]
If you're motivated, you can add the related test in a new method inside tests/Unit/Classes/ToolsCoreTest.php

**Comment by ghost** [comment]
@Quetzacoalt91 It's done and the test passed.

**Review by Quetzacoalt91 — DISMISSED** [review]
That's awesome. Thank you

**Review by eternoendless — DISMISSED** [review]

**Review by eternoendless — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @infiniweb

**Pull request merged**
