### PR TITLE
Clean behat scenarios with new carrier steps

### LINKED ISSUE #36556: Refacto behat tests: replace old steps relying on legacy ObjectModel with new steps based on the CQRS commands everywhere

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Clean behat scenarios with new carrier steps
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI tests green
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/10509758184
| Fixed issue or discussion?     | Fixes #36556
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @tleon

**Review by matks — DISMISSED** [review]
Nice refacto on the behat part, using backgrounds

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
All good, except `getGroupIds`. :-)

There already is `getAllGroupIds` that does the exact same thing.
Or `getGroups`.

**Comment by jolelievre** [comment]
@Hlavtox nice catch, thanks

**Review by jolelievre — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Pull request merged**
