### PR TITLE
Added hook on manufacturer edit form

### PR DESCRIPTION
**Pull request by SebBareyre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add hook on manufacturer edit form
| Type?         |  feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8989)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @SebBareyre,

I'm not opposed to new hooks, can you tell me what are/is your-s need-s?

Mickaël

**Review by mickaelandrieu — APPROVED** [review]

**Comment by SebBareyre** [comment]
Hi @mickaelandrieu 

I need to add some fields in the manufacturer admin page..

thanks

Seb

**Comment by mickaelandrieu** [comment]
Don't we have already some specific hooks for forms?

**Comment by kpodemski** [comment]
@mickaelandrieu yes we do @SebBareyre 

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/AdminController.php#L2514

**Comment by SebBareyre** [comment]
@mickaelandrieu My bad, I just saw that.. I close this.

**Pull request closed without merging**
