### PR TITLE
Allow HTML in customization when it's displayed by a module

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow modules to display html in customizations (in the cart module)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Having a module which is hooked to "displayCustomization", the returned html output will be displayed as text in the cart module

### CODE REVIEW

**Comment by antoin-m** [comment]
Ping @julienbourdeau what do you think?

How about just adding nofilter (without the if/else) since the customization's input is already sanitized?

**Comment by unlocomqx** [comment]
I can amend my commit, no problem. Just tell me what you guys decide :)
Thank you

**Comment by julienbourdeau** [comment]
It should be sanitized after being retrieved from the DB and before being passed to the template, then the nofilter is ok.
And I agree, we can keep only the _nofilter_ one. 👍

**Comment by antoin-m** [comment]
Okay! So could you amend your commit to remove the if/else @unlocomqx ?

I'll merge it as soon as the tests are green! :green_apple:

**Comment by unlocomqx** [comment]
Yes, right away :)

**Comment by aleeks** [comment]
Thank you @unlocomqx

**Comment by antoin-m** [comment]
Thief! :cry:

**Comment by aleeks** [comment]
Ahahah

**Pull request merged**
