### PR TITLE
travis: use it's own composer

### PR DESCRIPTION
**Pull request by TomasVotruba**
There is no need to download/install new composer. Travis already has one.

### CODE REVIEW

**Comment by djfm** [comment]
Hi, thanks for the suggestion, but I prefer to download composer each time to be sure to have the latest version.

Travis does indeed have one, but [as you can see](https://travis-ci.org/PrestaShop/PrestaShop/jobs/56924799) it is rather old:

```bash
$ composer --version
Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/home/travis/.phpenv/versions/5.3/bin/composer self-update" to get the latest version.
```

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, I totally agree with @djfm.
Please keep contributing.

Best regards.

**Comment by TomasVotruba** [comment]
Hi guys,

I'm confused what to do now.
Do you want to close this, or add `composer self-update` or sth else?

**Comment by djfm** [comment]
To be honest I don't really care that much :) I'm fine with the composer self-update approach if you want to make another PR.

**Comment by TomasVotruba** [comment]
Ok. The usual git workflow is to comment and update single PR, that's why I'm confused.

I'll make a new one then.

**Pull request closed without merging**
