### PR TITLE
Reusable CustomMoneyType and ResizableTextType

### LINKED ISSUE #19544: CustomMoneyType and ResizableTextType looks unused and throw an error when used
#### Describe the bug

When we try to use CustomMoneyType or ResizableTextType, we have an error : 

Could not load type "PrestaShopBundle\Form\Admin\Type\CustomMoneyType": class does not implement "Symfony\Component\Form\FormTypeInterface".

#### Expected behavior

This Form Type sould probably be removed because I don't find 

<pre>
./src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php:32:class CustomMoneyType extends AbstractTypeExtension
./src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml:6:        class: 'PrestaShopBundle\Form\Admin\Type\CustomMoneyType'
</pre>

Please note: Service _form.type.extension.money_ is not used too.

Edit: same bug with ResizableTextType

1. Enable debug mode
1. Install PS 1.7.7 and install this module 
[checkboform_with_buggy_types.zip](https://github.com/PrestaShop/PrestaShop/files/8451434/checkboform_with_buggy_types.zip)
2. Click on configure
3. See error

1. Install PS 1.7.7 and [sample module](https://github.com/202ecommerce/checkboform) 

2. Uncomment CustomMoneyType on file Checkboform\Form\Type\SettingsType::buildForm

See the error 
image

#### Additional information

* PrestaShop version: 1.7.6 / 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by clotairer**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove unused code.<br>This is a radical approached to remove unused classes instead of trying to fix it. This issue is sleepy without answer for 2 years, so I propose and tell me what's your opinion.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19544
| How to test?      | Check all backoffice pages. If pages load without fatal error, files removed are in fact unecessary.
| Possible impacts? | None. Even if a module want use this types, It didn't work.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28152)

### CODE REVIEW

**Comment by clotairer** [comment]
I worked on this issue. Removing is not a good way (Unit test KO). I found ResizableTextType is used on Profil Grid in the head of the table.

I look for a solution to let ResizableTextType an CustomMoneyType reusable on a module context...

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@clotairer It seems that Integrations Tests are broken.

**Comment by clotairer** [comment]
Yes I’ve seen and It show me these Types are in fact useful !

I need to show if these Types are reusable in a module context, but à Little tricky to understand.

**Comment by clotairer** [comment]
I closed this PR and the issue associated. I've no time to work on this to propose a better way to reuse CustomManeyType and ResizableTextType.
It probably a bad uses of these object instead of real bug.
Don't waste time with this.

**Pull request closed without merging**
