### PR TITLE
[-] CORE: Replace LIKE with "=" in some SQL Queries

### PR DESCRIPTION
**Pull request by guestisp**
By replacing unneeded LIKE with "=" in some SQL query we improve performance by using `const` tables.
See http://dev.mysql.com/doc/refman/5.0/en/explain-output.html#jointype_const

More replace could be done, for example in `Category::searchByName` what do you think ?

### CODE REVIEW

**Comment by jocel1** [comment]
I agree, I will integrate this kind of optimizations in my sql optimizations PR.

**Comment by jocel1** [comment]
Integrated in PR #2421

**Comment by guestisp** [comment]
are you able to post any benchmark results before and after these changes?

**Comment by jeromenadaud** [comment]
Hi,

Thank you @jocel1. I will close this PR and continue code review on PR #2421 

Best regards.

**Pull request closed without merging**
