### PR TITLE
Wait for combinations to load before enabling save and generate

### LINKED ISSUE #14910: Error when save an existing product before it is fully loaded
**Describe the bug**
I get an error message 'Unable to update settings' if i try to save an existing product before the product has been fully loaded. I would expect the 'Save' button to be disabled before the product is fully loaded.

**To Reproduce**
1. Go to 'Catalog / Products'
2. Click on an existing product with combinations
3. Click on 'Save' before the combinations is loaded
4. See error 'Unable to update settings'

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0.33

### PR DESCRIPTION
**Pull request by R-Larsson**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR disables the save and generate button when edit a product with combinations until the combinations has been fully loaded.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14910 
| How to test?  | Go to 'Catalog / Products'. Click on an existing product with combinations. Click on 'Save' as soon as the button is available. The product should successfully save.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15034)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
This looks fine to me but not sure what to do since an EPIC issue is opened on the product page ?

**Comment by marionf** [comment]
@NeOMakinG This can go through QA if it's ok for the code review :)

**Comment by NeOMakinG** [comment]
@R-Larsson could you please rebuild the bundle before we change the tag to waiting for QA ?

Thanks for your contribution :)

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Hello @R-Larsson, thanks for your contribution, would you mind to rebase your pull request and don't commit assets files on `develop` branch ? Thanks

**Comment by colinegin** [comment]
Since we did not get any news in the last month, we have to close this PR.
Feel free to reopen it if you are able to keep working on this PR !

Thanks anyway for your contribution :)

**Pull request closed without merging**
