### PR TITLE
Change stock alert z index to be on top of header

### LINKED ISSUE #12387: There is no alert after editing quantity in the Stocks page - BO
**Describe the bug**
In the BO => Catalog => Stocks page => we try to "Edit quantity" with the arrow icons, then when we click on "Apply new quantity" or with the "Check" button=> There is no successful green alert displayed, it should be displayed a success message: `stock successfully updated`

**To Reproduce**
1. Go to BO => SELL => Catalog => Stocks => Stock Tab
2. Edit the quantity for a product
3. Click on the "Check" button / or Click on "Apply new quantity" button
4. There is no message added

**Screenshots**
1.7.5.0
image

1.7.4.4
image

**Additionnal information**
PrestaShop version: 1.7.5.0
PHP version: 7.1

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Stock alert box was invisible because it was hidden under the menu header.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12387
| How to test?  | Go to `Catalog -> Stocks` update a product quantity, the green alert must be visible after request is done.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12395)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
It is really good to see that you are not recompile the world when you change just one line :trollface:

**Comment by jolelievre** [comment]
I was actually surprised myself!!! 😅

**Comment by matks** [comment]
Thanks @jolelievre

**Comment by PierreRambaud** [comment]
@jolelievre This is because of the new webpack implementation 😄

**Comment by jolelievre** [comment]
@PierreRambaud it's on the 175 branch so I doubt it! 😛
But nice try!

**Pull request merged**
