### PR TITLE
admin/threads : improve list sql query

### PR DESCRIPTION
**Pull request by ebuildy**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | To get employee name, use LEFT JOIN instead of inefficient sub query in select clause (I could use windowed function for mysql 8 ?) 
| Type?             | improvement
| Category?         | BO 
| Benchmark?             | 20s --> 1,3s
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Open admin "SAV" listing page, on a very big shop with ton of messages
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Comment by kpodemski** [comment]
Hello @ebuildy 

Thank you for this pull request. You have some error inside the code, which has been reported by our automatic tests.

**Review by kpodemski — CHANGES_REQUESTED** [review]
CI is 🔴

**Comment by kpodemski** [comment]
@jolelievre @MatShir do we plan to enable the new Customer Threads page in v9?

**Comment by ebuildy** [comment]
Oups wrong copy/paste :-) 

Actually I need this query for a big customer running PS 1.7.8 , what is the new Threads page please ?

**Comment by Hlavtox** [comment]
@kpodemski CI green

@ebuildy The page is being migrated to symfony on the 8.1.x, develop branch, currently hidden in experimental features section.

**Comment by ebuildy** [comment]
Thanks @Hlavtox , so I could PR against 1.7.X branches instead? ( I really want to become a contributor ^^ since I have a ton of small optimisations like to give).

**Comment by Hlavtox** [comment]
@ebuildy No, 1.7 doesn't accept any patches anymore.

If you have a bug that is easy to fix, has a nice scope, easy to test, and we all agree it's safe, it can go to 8.1.x branch.
For all other optimizations, please target develop, which will become 9.0. ;-)

Let's go!

**Pull request closed without merging**
