### PR TITLE
Old products.js fixes

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Some bugfixes and code improvements. Is this file still used?
feel free to close the PR.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | As seen with @Robin-Fischer-PS, test with automated tests
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24933)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Hey @davidglezz, you're PR miss some information, we need a way to test (at least a way to test that behavior is normal)

I doubt this file is used somewhere, and I think it's time to clear that js/ folder

**Review by Progi1984 — APPROVED** [review]

**Comment by davidglezz** [comment]
@NeOMakinG almost all modifications do not alter the logic: Remove unused variables, declare variables with var ...these things cannot be tested.

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Let's wait for one more approve, and another maintainer advice in case we miss something

**Review by PierreRambaud — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@davidglezz I spoke with the @PrestaShop/qa-team , they wants to run automated tests on it, so I still add the QA label

**Review by SD1982 — APPROVED** [review]
Tests auto are :+1:

**Comment by NeOMakinG** [comment]
Thanks @davidglezz

**Pull request merged**
