### PR TITLE
Click on read more

### PR DESCRIPTION
**Pull request by hadrich-hatem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows to : Check the click on "Read more" button, Check that the modal is well opened, Check that the content of all tabs is not empty, Install MBO module if it's not installed, Uninstall MBO module if it's installed.
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4951
| How to test?  | Run the script TEST_PATH=full/10_module/8_read_more_module.js npm run specific-test -- --URL=FrontOfficeURL --MODULE=mailchimpintegration

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8941)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @hadrich-hatem, would you mind to rebase your pull request?

Thank you

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by marionf** [comment]
@hadrich-hatem 
We need to check each tab of the modal after clicking on "read more" link: Overview, additional information, benefits, features

**Comment by hadrich-hatem** [comment]
@marionf,
Alright, i will add the missing check ASAP.
Thank you,

**Comment by hadrich-hatem** [comment]
Hello,
I'm waiting for the merge of this PR [9215](https://github.com/PrestaShop/PrestaShop/pull/9215) to be able to continue the dev of the script.
Best regards,

**Review by fatmaBouchekoua — APPROVED** [review]

**Comment by fatmaBouchekoua** [comment]
@mbadrani this PR is ready to be merged

**Pull request merged**
