### PR TITLE
Add keycloack module as a dev dependency

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Add keycloack module as a dev dependency 
| Type?             |  improvement 
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | PrestaShop SA 

As discussed with @Progi1984 and @matks, we add this module as a dev dependency to simplify tests. 

@Progi1984 Do we need to update something in the UI tests?

### CODE REVIEW

**Comment by nicosomb** [comment]
UI tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5657687409

**Review by matks — DISMISSED** [review]
Good for me I think now the config is a lot more relevant ;)

**Review by matthieu-rolland — COMMENTED** [review]
there's an api platform integration test broken, not sure if it's the PR, I'm restarting it just in case

**Comment by nicosomb** [comment]
We need to merge https://github.com/PrestaShop/keycloak_connector_demo/pull/10 before this PR.

**Comment by nicosomb** [comment]
tests UI https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/5681478755

**Review by boherm — DISMISSED** [review]

**Pull request closed without merging**
