### PR TITLE
Use datetime format in product specific price form.

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Use datetime format in product specific price form.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes  (part of https://github.com/PrestaShop/PrestaShop/issues/11329)
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/11329
| Possible impacts? | N/A

## BEFORE

image

## AFTER

image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27642)

### CODE REVIEW

**Comment by ghost** [comment]
@PululuK You're the best; I warned about this at in 2017

https://github.com/PrestaShop/PrestaShop/pull/8571 

All my shops have this fixes

**Review by kpodemski — APPROVED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Please support locale for dates. 

Relative to #9591

**Comment by kpodemski** [comment]
ping @PululuK do you plan to work on this PR?

**Comment by matks** [comment]
Hi @PululuK,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant 😉 

Thanks!

**Comment by az-vm** [comment]
Hello @PululuK 
Thank you for this post.
I´m trying to update the files, but dont see any change on it (the time do not show) i´m in version 1.7.8.6, any idea ?

Regard´s

**Comment by ghost** [comment]
Hello, @az-vm,

You have to : https://devdocs.prestashop.com/1.7/development/compile-assets/#requirements

**Comment by az-vm** [comment]
Hello @okom3pom,

Thank you for your message, i need to recompile all the assets in the backend side, correct ?

**Comment by jf-viguier** [comment]
Tested OK, Good for me.

**Pull request closed without merging**
