### PR TITLE
Mobile Cart - Carriers Improperly integrated

### PR DESCRIPTION
**Pull request by hibatallahAouadni**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fix the problem that appears only with the first proposed carrier (integration).
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2179
| How to test?  | order a product and choose a shipping method

- iPad: 
ipad

- iPhone6:
iphone6

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7361)

### CODE REVIEW

**Comment by antoin-m** [comment]
Hey @hibatallahAouadni , thank you for your contribution :smile: 

Could you please change the target branch to `develop` and add some screenshots of the results?

Thanks! :smiley:

**Comment by hibatallahAouadni** [comment]
hey @antoin-m done ;)

**Comment by hibatallahAouadni** [comment]
Hello @maximebiloe
do you have to rebase this one too?

**Comment by maximebiloe** [comment]
No, it's okay for this one

**Comment by antoin-m** [comment]
Hey @hibatallahAouadni 

Could you check why the tests are red?

**Comment by hibatallahAouadni** [comment]
hey @antoin-m ,
the file travis.yml causes these problems and thanks to @basma-yangui-prestashop help I could find out, so I just rebase the branch against the develop branch and re-push it.

**Comment by antoin-m** [comment]
Thank you @hibatallahAouadni ! :+1:

**Pull request merged**
