### PR TITLE
Remove Adapter\Tools::link_rewrite

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove Adapter\Tools::link_rewrite
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes  - Remove Adapter\Tools::link_rewrite
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293
| How to test?      | Tests are green.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27960)

### CODE REVIEW

**Review by saulaski — COMMENTED** [review]
Possible impact ?
https://github.com/PrestaShop/PrestaShop/blob/10e33c06b3da86f79dcaaef4e91f3ab6f1840c6c/src/PrestaShopBundle/Model/Product/AdminModelAdapter.php#L376

**Comment by PierreRambaud** [comment]
Nope as I already changed it :)

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Hi Thank you for your contribution. Could you add a linked PR on the devdocs : https://devdocs.prestashop.com/8/modules/core-updates/8.0/#removals ?

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PierreRambaud

**Pull request merged**
