### PR TITLE
Fix order and remove duplicates from smarty.config.inc.php

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed for 8.1.x in #33555, but it appears #33582 didn't go as planned - no order and duplicates again
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | -
| UI Tests          | https://github.com/SharakPL/ga.tests.ui.pr/actions/runs/8278518875
| Fixed issue or discussion?     | -
| Related PRs       | #33555
| Sponsor company   | -

### CODE REVIEW

**Review by boherm — DISMISSED** [review]

**Comment by SharakPL** [comment]
Additional fix to avoid deprecation warning from ps_mbo.
https://github.com/PrestaShopCorp/ps_mbo/blob/71769b2a54e0b9679ab29ccce23f7aa25b2a9eff/views/templates/hook/dashboard-zone-one.tpl#L43

**Review by M0rgan01 — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Comment by SharakPL** [comment]
Guys, sorry for another dismissing of your reviews 😳
Replicating #35705

**Review by boherm — DISMISSED** [review]

**Comment by SharakPL** [comment]
I've just noticed a bugged extension in my editor added unwanted spaces on save: `empty ()`. Sorry about this 😔

**Review by boherm — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Comment by SharakPL** [comment]
Can it be merged without QA?

**Comment by Hlavtox** [comment]
Ping @florine2623, it's just a cosmetic change ;-)

**Comment by tleon** [comment]
Hello, this has been labeled as QA by dev. I wannted to test this in order to merge it but I have now Idea how can I do that. Could you give me a way to test this ? 

Thanks in advance. 

Also you have a conflict.

BR.

**Comment by SharakPL** [comment]
@tleon conflicts resolved.
No need to test anything really. It's just about applying #33555 properly since merging 8.1.x into develop didn't go as planned in this case. Please make sure everything is in order, there's no duplicates and none of the functions were removed.

**Review by nicosomb — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
