### PR TITLE
CI: Skip Travis CI check in some cases

### LINKED ISSUE #21212: CI: Skip Travis CI check in some cases
#### Is your feature request related to a problem?

In some cases it is unnecessary to run the Travis CI checks. For example if you just modify the Contributors file, there is no need to run the Travis CI.

Examples : 

- https://github.com/PrestaShop/PrestaShop/pull/21211
- https://github.com/PrestaShop/PrestaShop/pull/21208
- etc

#### Describe the solution you'd like

Do not perform travis when the PR modifies only the following files :  

- `.gitignore`
- `.md`
- `.png`
- `.jpg`
- `.gif`

#### Alternatives you've considered

Use @prestonBot  to edit the title of PR when it only contains files with the some extentions (`.png`, `.jpg`, `.gif`, `.md`, `.gitignore`)

See [Travis CI how to skip a build](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build)

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | In some cases it is unnecessary to run the Travis CI checks. For example if you just modify the Contributors file, there is no need to run the Travis CI.
| Type?         | new feature
| Category?     | TE
| BC breaks?    | yes
| Deprecations? | yes
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21212.
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/21212.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21213)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi @PululuK thank you for the contribution but... I am not sure this is something we would like to happen 🤔 

I think it's better to run Travis too many times rather than mistakenly avoid to run it for some PRs

Also modifying `.tpl` and `.twig` files can break the view and introduce bugs, it should not be in the "dont run travis" scope

**Comment by PululuK** [comment]
> Hi @PululuK thank you for the contribution but... I am not sure this is something we would like to happen thinking
> 
> I think it's better to run Travis too many times rather than mistakenly avoid to run it for some PRs

See this case for example 🤔 ? https://github.com/PrestaShop/PrestaShop/pull/21211

> Also modifying `.tpl` and `.twig` files can break the view and introduce bugs, it should not be in the "dont run travis" scope

I totally agree with you !

**Comment by matks** [comment]
> > Hi @PululuK thank you for the contribution but... I am not sure this is something we would like to happen thinking
> > I think it's better to run Travis too many times rather than mistakenly avoid to run it for some PRs
> 
> See this case for example 🤔 ? #21211
> 
> > Also modifying `.tpl` and `.twig` files can break the view and introduce bugs, it should not be in the "dont run travis" scope

The idea "let's not run Travis when it's not needed" is good. However "when it's not needed" is quite hard to exactly identify. The criterion you have selected for "when it's not needed" is "there's only gitignore / pdf / markdown" files.

But in the future we could have some configuration settings written in Markdown and, the day we do introduce/modify them, Travis will not run on these PRs 😅 . That is what worries me: it's very hard to define a very accurate criterion that says "this PR does not need to run Travis".

Some projects rather use a keyword inside commit message and let the maintainer choose when and when not to run Travis. If they commit a PR with inside the commit message "[Skip CI]", the CI does skip the PR.

**Comment by PululuK** [comment]
> Some projects rather use a keyword inside commit message and let the maintainer choose when and when not to run Travis. If they commit a PR with inside the commit message "[Skip CI]", the CI does skip the PR.

@matks  looks at the alternative that I have proposed here #21212.

**Pull request closed without merging**
