### PR TITLE
Delete ACKNOWLEDGEMENTS.md

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | less uneeded files in the root directory, also, this file is outdated a lot
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | no functional change
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23991)

### CODE REVIEW

**Comment by eternoendless** [comment]
Sorry @mvorisek but we're keeping this file

**Comment by mvorisek** [comment]
@eternoendless how is that file helpful?

**Comment by matks** [comment]
@mvorisek you can find the origins of this file in the PR https://github.com/PrestaShop/PrestaShop/pull/20854

**Comment by mvorisek** [comment]
I did! I found this file outdated thus I think it is ok to remove. If not, I think it can be moved somewhere else (probably to some other existing Markdown file), so the root directory is uncluttered.

**Comment by matks** [comment]
If it's outdated we can fix it 🤔  why do you consider it outdated? It's not the same as https://github.com/PrestaShop/PrestaShop/blob/develop/CONTRIBUTORS.md

**Comment by mvorisek** [comment]
Travis will be dropped soon (already not used for testing), BrowserStack is not used, at least in CI as we use Github CI solely. Then when one line is remaining, I propose to drop it entirely.

**Comment by matks** [comment]
BrowserStack is used a tool by the people who make PrestaShop :) and Travis is still being used in multiple repositories in the PrestaShop organization and on old branches :) .

Things take time to move on such a big org 😄

**Comment by eternoendless** [comment]
We need to add https://coveralls.io/

And there are probably other services we have forgotten

**Pull request closed without merging**
