### PR TITLE
[FO] Fix cart value amount

### LINKED ISSUE #37148: Incorrect cart rule value in a product with specific price
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you call the method `getCartRules` from the class `CartRule`, if there is a product with a specific price, and the cart rule only applies to it, the discount amount computed is not correct.

### Expected behavior

_No response_

### Steps to reproduce

1. Create a specific price to a product
image

2. Create a cart rule that applies a percentage discount to a specific product
image
image

3. Add this product to the cart and go to the checkout

4. If you add a trace in these lines you get a different value:
https://github.com/PrestaShop/PrestaShop/blob/8b1ee442cd5f57ad77d443c33e878c915b313505/classes/CartRule.php#L1415

```
dump('Amount from CartRule with use_tax ' . (int)$use_tax . ': ' . $price);
```

https://github.com/PrestaShop/PrestaShop/blob/8b1ee442cd5f57ad77d443c33e878c915b313505/src/Core/Cart/CartRow.php#L484

```
dump('Amount from CartRow with use_tax 1: ' . $this->finalTotalPrice->getTaxIncluded());
dump('Amount from CartRow with use_tax 0: ' . $this->finalTotalPrice->getTaxExcluded());
```

5. Result:
```
"Amount from CartRule with use_tax 1: 15"
"Amount from CartRule with use_tax 0: 10.53719"
"Amount from CartRow with use_tax 1: 12.75"
"Amount from CartRow with use_tax 0: 10.54"
```

Error when `use_tax` is `true`

### PrestaShop version(s) where the bug happened

8.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

idnovate.com

### PR DESCRIPTION
**Pull request by idnovate**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The amount is not computed correctly when you call `getCartRules` from a module. The bug doesn't appear in the checkout because it uses `CartPresenter` and it's computed in another place.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | #37148 
| Fixed issue or discussion?     | Fixes #37148
| Sponsor company   | idnovate.com

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello

We recently introduced the 9.0.x branch, which will be the base for PrestaShop 9.0. If you want to see your change in this version, please rebase your PR onto 9.0.x. The `develop` will be used for PrestaShop 9.1, so you need to decide what to do.

Please rebase onto `9.0.x` or let me know your decision if you don't need to have it there so I can unblock the pull request.

**Comment by idnovate** [comment]
It's OK for 9.1 👍

**Comment by kpodemski** [comment]
Hello @idnovate 

Since this issue has been marked as a "Major", maybe you could consider changing the branch to `8.2.x`?

**Review by idnovate — COMMENTED** [review]
Branch change

**Comment by idnovate** [comment]
#37267

**Pull request closed without merging**
