### PR TITLE
Prevent short description limit to be set at 0

### LINKED ISSUE #11164: Max size of short description is equal to 0
**Describe the bug**
When you set the Max size of the short description as 0 in BO => CONFIGURE => Shop Parameters => Product Settings, and try to save the product with (short description size > 800), an error message appears "This value is too long. It should have 800 characters or less."
In the manual is written: http://doc.prestashop.com/display/PS17/Product+Settings
" The short description, which appears in search engines and in the category description for your product, is limited to 400 characters by default, but this option enables you to change that limit. 0 means that there is no limit."

**To Reproduce**
1. Go to BO => CONFIGURE => Shop Parameters => Product Settings
2. Set the "Max size of short description" to 0 & SAVE
3. Go to the BO => Catalog => Product page => create a new product 
4. In the Summary, only 800 characters are allowed. => NOK
5. try to save the product with (short description size > 800), an error message appears.

PS: In the last version 1.7.4.3 is not allowed to set 0 in the Max size of the short description
**Screenshots**
https://drive.google.com/file/d/12OiTDVRxzCutPGrCaZzh6Fj3AaP1WXly/view

**Additionnal information**
PrestaShop version: 1.7.5.0 build1 beta2
PHP version: 7.1

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Prevent short description limit to be set at 0
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11164
| How to test?  | See ticket bug description

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11312)

### CODE REVIEW

**Comment by arouiadib** [comment]
thanks @jolelievre.
~~I suggest changes to be equally done for the validation in `Catalog > Product > New Product` and `Catalog > Product > Product Edit` , by editing `src/PrestaShopBundle/Form/Admin/Product/ProductInformation.php`, Lines 194 and 198.~~

~~Additionnaly, values greater than 800 should be considered as equal to 800. Then, a comparison with 800 should be added.~~

~~And '800' should be declared as a constant , e.g, on the top of class attributes.~~

**Comment by jolelievre** [comment]
hello @arouiadib
I'm not sure I understand the modification you suggest, the validation for edition and creation is already present in `ProductInformation` at the lines you suggested, so there is no validation to add
I just tested it and it works fine, even when you change the value (for example 10) you have the appropriate error message when you try to save

Besides I don't think we should crop the text when it's over 800 as you suggested because it hides the modification to the user who will not understand why his modification was not fully applied. It is a better practice to inform the user about the error and let him fix it himself.

Finally about the 800 constant, do you mean we should define a constant for the default value which would be common between `ProductInformation` and `ProductPreferencesFormDataProvider` ? Only for the default value then because we need to keep this value configurable. That's a good idea, I'll have to look for other places where this value is used then.

**Comment by arouiadib** [comment]
Thanks @jolelievre.

You are right about the first point. I thought it should become strictly less than zero instead of "<=". I am sorry.

I didn't suggest to crop the user text. I think the aim of "max" in "constraints" is to notify the user when he exceeds the config value. 

But I still believe:"it doesn't make sense to allow infinite length for a short description even though it is allowed in the database". 

In current situation, if config value is set to 10000, the user will be notified to do not exceed 10000. While the good thing IMHO is to do not allow exceeding 800 in all cases.

If I am correct, then the code in `ProductPreferencesFormDataProvider` looks like:
 
```
 if (!is_numeric($shortDescriptionLimit) || 0 >= $shortDescriptionLimit  || 800 <= $shortDescriptionLimit) {
            $invalidFields[] = ...
        }

```
and in `ProductInformation`:

```
$configValue = (int)$this->configuration->get('PS_PRODUCT_SHORT_DESC_LIMIT');

'counter' =>  ( $configValue <= 0 || $configValue > 800) ? 800 : $configValue

'max' => ( $configValue <= 0 || $configValue > 800) ? 800 : $configValue
```

**Comment by arouiadib** [comment]
@jolelievre  You are right. I am sorry. 
Thanks.

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
