### PR TITLE
Use attribute public names instead of private when appending combination attributes to URL

### LINKED ISSUE #35976: Combinations display private attribute names instead of public in the URL
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

On a product page with combinations, when an attribute value is selected, the attribute name+value groups are appended to the URL e.g.:
122-3154-product.html#/10-attr1_value1/11-attr2_value2

Currently we show the attributes' private names. Since this information is visible publicly, we should show the public names instead.

### Expected behavior

Public attribute names are appended to URL

### Steps to reproduce

1. Go on a product page with combinations
2. Select any attribute value
3. Check the attribute-value permutations added to the URL after #/

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by maxldn5**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The query in getAttributeParams() currently fetches al.name, which contains attribute private names. Since this is publicly visible to the user in the URL, we should fetch the public_name instead. This can be considered a bug since private fields are not expected to be made visible publicly.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | View a product page with combinations, change the value of one of the attribute and check what's appended to the URL in the address bar. A pass would show the attribute's public name being appended.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #35976
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
thank you for your contribution @maxldn5 👍 

the change looks good to me, the issue still needs to be validated by qa/pm though

**Review by Hlavtox — CHANGES_REQUESTED** [review]
I think you should select both columns and change the logic in the method that constructs the URL. This could bring unexpected results.

**Comment by maxldn5** [comment]
@Hlavtox I have made the changes as suggested, I re-added agl.name, added agl.public_name as public_group, and getAnchor now references public_group.

**Comment by kpodemski** [comment]
Hello @maxldn5 

Since this problem is on recent PrestaShop 8.1.5, and the change seems safe, you may want to send your PR against the `8.1.x` branch instead of `develop` :)

**Comment by maxldn5** [comment]
Will re-submit a PR from a clean branch for 8.1.x

**Pull request closed without merging**
