### PR TITLE
Normalize white-characters all text files

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove trailing white-characters (except NL) in all text files
| Type?         | refacto
| Category?     | all
| BC breaks?    | no
| Deprecations? | no
| How to test?  | All existing tests MUST pass.

Refactor to make versioning easier.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16517)

### CODE REVIEW

**Comment by matks** [comment]
Hi @mvorisek thanks for this PR 😉can you tell us what tool you used to remove all trailing spaces ?

I must warn you that I dont know if we can merge this PR like that. Indeed as it impacts a very huge number of files, if we merge we're going to create potential git conflicts with dozen of other PRs. That's why I'm asking about the tool: in order to ease the merge we might do use an alternative strategy.

2 strategies I can think of:
- merge PR bit by bit, folder per folder, to minimize impact
- merge it at christmas 😬when nobody's doing PRs around so we dont mess with existing PR 😆

**Comment by mvorisek** [comment]
@matks Thanks. We have some internal content aware tool and I will commit it soon.

Tasks:
- [ ] commit transformation tool
- [ ] integrate with CI, so all new code with not normalized text will fail
- [ ] apply on top of the `develop` branch

- [ ] apply on every PR<br>
  @TBD amend the last commit or commit one extra if needed?

- [ ] apply on other branches<br>
  @TBD how?

- [ ] strictly normalize other text like tabs<br>
  @TBD is this welcomed too?

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-core-developers Ping here

**Comment by mvorisek** [comment]
Whitespaces are now more or less managed by CS fixers/linters.

**Pull request closed without merging**
