### PR TITLE
fix(BO): assign the theme chosen by the employee on the backoffice

### LINKED ISSUE #13020: change the backoffice theme to my own theme
**Describe the bug**
when changing the backoffice theme from default to my own theme, it does not show.

I want to use my own theme because I don't like to use template overrides for the backoffice, for instance when adding my custom hooks

**To Reproduce**
1. in the source, go to admin-dev/themes
1. duplicate the backoffice default theme with the name 'mytheme'
2. open the file admin-dev/theme/mytheme/template/controllers/dashboard/helpers/view/view.tpl
3. on line 39 add the line 
`<div class="alert alert-warning">This in mytheme</div>`
4. open the database table ps_employee and change the field bo_theme for the current employee to 'mytheme' (unfortunetly we cannot change themes in the backoffice itself)
5. login into the backoffice as the current employee

**Expected behaviour:** 
on the dashboard we should see an error message 'This is mytheme'

**Real behaviour:**
no error message

**Solution:**
in the file classes/controllers/AdminController.php on line 429 change this line to:
`
$this->bo_theme = ((Validate::isLoadedObject($this->context->employee)
                && $this->context->employee->bo_theme) ? $this->context->employee->bo_theme : $default_theme_name);
`

**Additional information**
PrestaShop version: 7.5.1
PHP version: 7.1.20

### PR DESCRIPTION
**Pull request by jbalieux**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing assignment logic on bo_theme variable
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #13020
| Related PRs       | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Comment by yanmakouf** [comment]
Hello @jbalieux and thank you very much for your contribution ! Code seems legit to me, just wondering if it could be tested 🤔 Also CI Sanity tests failling. Otherwise good for me 👍

**Review by yanmakouf — APPROVED** [review]

**Comment by PrestaEdit** [comment]
Hi,

As the theme and colore scheme was removed from the Employee form, and even if not writed inside the code, I think that this part is deprecated.

**Review by nicosomb — APPROVED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
UI tests are failing : can you please check why? This might be a warning that this PR is breaking something

**Comment by kpodemski** [comment]
Hello @jbalieux 

I agree with @PrestaEdit . This part is no longer used. Maybe, if somebody is motivated enough, we could have a BO theme selector in the future. As for now, it's not the case.

**Pull request closed without merging**
