### PR TITLE
Move Logs page JS to appropriate location

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Seems that `new-theme/js/app` contains only Vue related code. This PR moves Logs page js to `new-theme/js/pages` where all other page specific js code lives.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Logs page works the same

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10265)

### CODE REVIEW

**Comment by LouiseBonnard** [comment]
@sarjon, is there any translation key to check here? I can't find any.

**Comment by sarjon** [comment]
@LouiseBonnard there arent any, @prestonBot is lying.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
I wonder if the vuejs pages should not be merged with the other pages, I was lost when I try to find my way in these folders.

Anyway, can you please rebase? :)

**Comment by sarjon** [comment]
@Quetzacoalt91 rebased. :+1:

**Comment by Quetzacoalt91** [comment]
Are you sure? I still see a conflicted file. :)

**Comment by sarjon** [comment]
oh god, those assets are so annoying. :expressionless:

**Comment by sarjon** [comment]
rebased (for now). :+1:

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @sarjon

**Pull request merged**
