### PR TITLE
Update Mexico unit settings

### LINKED ISSUE #23848: Mexico units
#### Describe the bug

There is a file called `localization/mx.xml` with Mexico's settings. I updated the units with PR #23830, since we use metric system.

#### Expected behavior

We expect to see  short distance = cm, base distance = m and long distance = km

#### Steps to Reproduce

1. Go to '`localization/mx.xml`'
2. Scroll down to bottom
3. See error
4. See corrected units in PR #23830

**Screenshots**

Not applicable.

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: N/A

### PR DESCRIPTION
**Pull request by rickygzz**
Updated short, base and long distance to metric units

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There is a file called `localization/mx.xml` with Mexico's settings. I updated the units, since we use metric system.
| Type?             | improvement
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23848
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | I dont think there is any impacts.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23830)

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hi @rickygzz and thank you for the PR!

As mentioned by the bot, would it be possible to open a github issue explaining us the topic? I'm afraid we are no Mexico experts so we have no way to validate if your change is good. Is there a way we could validate this, some authority or some material?

So a github issue would help us trigger a discussion about the best implementation path for this 😉

**Comment by rickygzz** [comment]
> ed by the bot, would it be possible to open a github issue explaining us the topic? I'm afraid we are no Mexico experts so we have no way to validate if your change is good. Is there a way we could validate this, some authority or some material?

Ok. I created a ticket #23848 to describe the error. Also, I can tell you that the metric system was officialy accepted in Mexico since 1852, 53 years after it was introduced in France.

I am pretty sure of this information because I am from Mexico, it is mandatory that we have to use the international system (sistema international) as it is stated in our Federal Laws about Metrology and Normalization:

Ley Federal sobre Metrología y normalización, article 5
http://www.diputados.gob.mx/LeyesBiblio/abro/lfmn/LFMN_abro.pdf

> "ARTÍCULO 5o.- En los Estados Unidos Mexicanos el Sistema General de Unidades de Medida es el
> único legal y de uso obligatorio.
> El Sistema General de Unidades de Medida se integra, entre otras, con las unidades básicas del
> Sistema Internacional de Unidades: **de longitud, el metro; de masa, el kilogramo; de tiempo, el segundo;
> de temperatura termodinámica, el kelvin**; de intensidad de corriente eléctrica, el ampere; de intensidad
> luminosa, la candela; y de cantidad de sustancia, el mol, así como con las suplementarias, las derivadas
> de las unidades base y los múltiplos y submúltiplos de todas ellas, que apruebe la Conferencia General
> de Pesas y Medidas y se prevean en normas oficiales mexicanas. También se integra con las no
> comprendidas en el **sistema internacional** que acepte el mencionado organismo y se incluyan en dichos
> ordenamientos"

http://www.diputados.gob.mx/LeyesBiblio/abro/lfmn/LFMN_abro.pdf

Source:
http://chartsbin.com/view/d12
https://www.quora.com/Which-countries-do-not-use-the-metric-system

**Comment by matks** [comment]
Close and reopen to reset the CI

**Comment by matks** [comment]
@rickygzz The issue https://github.com/PrestaShop/PrestaShop/issues/23848 is not validated yet, I have pinged some people to make it go forward 😊

**Comment by hibatallahAouadni** [comment]
@matks it's validated now :tada:

**Comment by matks** [comment]
Hi @rickygzz can you please submit your PR against https://github.com/PrestaShop/LocalizationFiles/blob/master/mx.xml ?

This file here is actually a copy of https://github.com/PrestaShop/LocalizationFiles/blob/master/mx.xml . https://github.com/PrestaShop/LocalizationFiles/blob/master/mx.xml is the reference and we keep a copy inside the software so that, upon install, user does not need to download all files from https://github.com/PrestaShop/LocalizationFiles/

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@rickygzz Could you look at @matks message ?

**Comment by PierreRambaud** [comment]
Hi @rickygzz ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
