### PR TITLE
Replace `Tools::link_rewrite` usages by `Tools::str2url`, deprecate `Tools::link_rewrite`

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Duplicate function, one already calls the other one, this PR keeps only the used function and deprecates the old one
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | Tests should be sufficient as this is widely used function.

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm (not merging yet, tests still running...)

**Review by boubkerbribri — DISMISSED** [review]
@FabienPapet 
This pull request needs to be tested, There some main files that are updated.
But Since There is no issue and no How to test. I'm sending it back to you

**Comment by kpodemski** [comment]
@boubkerbribri no, there's no need for tests on this one

`Tools::link_rewrite` points to `Tools::str2url`

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @FabienPapet - automated tests didn't show anything suspicious that could be related to this change, it's QA ✅

**Pull request merged**
