### PR TITLE
Merge 8.1.x into develop

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ui tests should be enough
| UI Tests          | https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/7502739448
| Fixed issue or discussion?     | none
| Related PRs       | none
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by M0rgan01 — COMMENTED** [review]
The PR https://github.com/PrestaShop/PrestaShop/pull/35014 will become useless following the merge, or merge before and rebase

**Review by boherm — DISMISSED** [review]

**Comment by nicosomb** [comment]
I think that UI tests will fail (like in https://github.com/PrestaShop/PrestaShop/pull/35014).

**Comment by matthieu-rolland** [comment]
UI tests did not pass because of a bug on ps_email_subscription, it was because of a problem on composer.lock, I rebased and pushed, so review is needed again...

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
As seen with QA, UI tests are enough 👍

**Review by M0rgan01 — APPROVED** [review]

**Pull request merged**
