### PR TITLE
B2B with internationalization

### PR DESCRIPTION
**Pull request by jorgevrgs**
| Questions | Answers |
| --- | --- |
| Branch? | 1.7 |
| Description? | B2B have a feature without internationalization. <br/> Allow international customer to use B2B feature by implementing an abstract Validation method for Siret and Ape fields. |
| Type? | improvement |
| Category? | CO |
| BC breaks? | yes |
| Deprecations? | no |
| Fixed ticket? | PSCsX-7835 |
| How to test? | create a customer in B2B mode in countries with any Siret and Ape code |

SIRET and APE is not a feature with international use, then must be and abstract method to allow all countries to use it only by overriding this class.

### CODE REVIEW

**Comment by kpodemski** [comment]
It's not a solution, if someone wants to create B2B in your country he can just extend Validation class and change behavior of this methods, B2B is not international and this change doesn't help with it at all, this mechanism and feature needs refactoring ,not skipping validation. Sorry.

**Comment by jorgevrgs** [comment]
For Cloud users is most important to be able to use B2B that override method. It is important, you need to refactoring this feature for internationalization purposes.

**Comment by vincentbz** [comment]
Hi,

Thanks for your contribution :)
Right now, we cannot accept this change because the problem would almost still be the same. The fields "SIRET / APE", even without checks, are for french companies and I don't think your other customers would understand they have to enter their international company number.
Another problem is that a company is not linked to a country, so we cannot contextualize this field according to the country.

It's better to modify this process deeper than a small fix like this, but we cannot apply a local check for an international field.
So we have to think about a better solution that would not block people from some countries, but that keep the same goal : collecting the company data.

**Comment by julienbourdeau** [comment]
We all agree this feature needs refactoring! I hope we get to that soon.
Although , like Vincent said, we can't do it this way right now.

**Pull request closed without merging**
