### PR TITLE
HookDispatcher dispatchMultiple doesn't exists anymore

### LINKED ISSUE #10231: Cannot change the status of a product in the list product page - BO
> **Reminder**
> 
> DO NOT disclose security issues here, contact security@prestashop.com instead!

**Describe the bug**
In the BO / Product list page, we cannot change the status of a product with the icon status.
An exception occurred.
image

**To Reproduce**
1. Go to BO => Product page
2. Click on icon status to disable a product
3. See error

**Additionnal information**
PrestaShop version: develop
PHP version: 7.1

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Cannot change the status of a product in the list product page. This is due to a missing change. dispatchMultple doesn't exists anymore.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #10231
| How to test?  | Follow issue instructions.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10233)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by marionf** [comment]
@PierreRambaud 
The progress bar and words seems pixelated with Chrome

capture d ecran_223

With firefox I don't have this problem

**Comment by PierreRambaud** [comment]
@marionf Not an issue due to this PR, I just fixed hooks :/

**Comment by marionf** [comment]
Fixes #10217

**Comment by marionf** [comment]
Fixes #10224

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @PierreRambaud and @marionf for the review!

**Pull request merged**
