### PR TITLE
[-] BO : Change only active state on bulk status change

### PR DESCRIPTION
**Pull request by erouvier29**
In particular, avoid unit price ratio to be reset in database when disabling a set of products

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by erouvier29** [comment]
Reviewing my PR, this one is still valid on 1.6.1.4:

1. Edit a product and set a unit price
2. Select the product and perform the bulk action "Disable selection"
=> The unit price has been reset to 0
3. Enable the product again
=> The unit price is still 0

**Comment by erouvier29** [comment]
Reviewing my PR, this one is still valid on 1.6.1.4.
Renewed as #4767 on branch 1.6.1.X

**Comment by xBorderie** [comment]
Again, thank you for these reviews Éric!

**Pull request closed without merging**
