### PR TITLE
Enable symfony layout feature flag by default

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | 
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Ci green and UI tests green<br>Symfony layout: https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7670270819<br>Legacy layout: https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7670297902
| UI Tests          | 
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
There are some tiny issues:

Language code is encoded:
```
var full_language_code = 'en\u002Dus';
var full_cldr_language_code = 'en\u002Dus';
```

`changeFormLanguageUrl` missing, is it needed?

**Comment by jolelievre** [comment]
I just checked `changeFormLanguageUrl` is correctly injected in legacy pages (even with symfony layout) thanks to the `setMedia` that adds it I'm gonna remove the forced escape on the manual variables though

By the way `changeFormLanguageUrl` seems to be used only when `PS_BO_ALLOW_EMPLOYEE_FORM_LANG` is enabled in configuration, this configuration is not even the the default data anymore and it can't be edited either from the BO Seems like an old feature, only used on legacy pages

**Comment by Hlavtox** [comment]
@jolelievre I digged in and the feature is used. If you go to Advanced parameters >Employees and enable "Memorize the language used in Admin panel forms", it will enable `PS_BO_ALLOW_EMPLOYEE_FORM_LANG`. Anyway, good then.

So we fix the encoding and then it's ready. :-)

**Review by Hlavtox — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by jolelievre** [comment]
No QA for this one even though it enables the new symfony layout on the branch This will allow us to getearly feedback And a full manual QA is planned after we finish upgrading the remaining dependencies (removal of sensio framework extra bundle and upgrade of ApiPlatform)

**Pull request merged**
