### PR TITLE
Display multishop header for translations page and lock it to all shops context

### LINKED ISSUE #23901: No Multistore header in the translation BO component
This bug seems to be related to [Refactoring of Translation storage component](https://github.com/PrestaShop/PrestaShop/issues/19242) project and [Multishop 1.7.8](https://github.com/PrestaShop/PrestaShop/issues/19304) project

## Issue description by @Robin-Fischer-PS https://github.com/PrestaShop/PrestaShop/pull/23696#issuecomment-812523672

In Multistore, I have no header in the translation component (no Legacy or Migrated header).

image

Furthermore, in 1.7.7 (and in 1.7.8 with and without this PR), the context the user is seems to have no impact : When I edit a translation in Context 1, if I switch to Context 2, the translation will also be modified.

Maybe this page should be forced in All Shops context ?

**Answer from @marionf **: Yes, it will be better to force the context to "all shops" :)

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Display multishop header for translations page and lock it to all shops context in Translations and Settings pages
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23901 
| How to test?      | Go to International > Translations, you will see the multishop header with no other context possible but "All shops". In "Modify translations" panel, select a category and a language and validate. In the settings page, you will see the same multishop header
| Possible impacts? | -

@PrestaShop/product-team In the breadcrumb, we had before **International** > **Translations** with a link for both items. That's because the breadcrumb was overriden by the Vue app made for translations. This override causes some problems with Multishop header, so I remove it. But, there is a difference : we still have the link for **Translations** item but not for **International**
I really hope this won't be an issue for you 🤞🏾

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23927)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
TranslationHeader has been removed, but still used. Not sure it has correctly been tested, the make assets is failling :sweat_smile:

**Comment by NeOMakinG** [comment]
You also forgot to kick it from there : https://github.com/PrestaShop/PrestaShop/pull/23927/files#diff-855dbfc11dbc513b5a9a859b15efd4b35bed67e87991561eb48c8f312527f16dR62

**Review by NeOMakinG — COMMENTED** [review]
And you forgot to kick it from the component attribute!

**Comment by Progi1984** [comment]
A PM answer has been waiting for the breadcrumb

**Comment by marionf** [comment]
> @PrestaShop/product-team In the breadcrumb, we had before International > Translations with a link for both items. That's because the breadcrumb was overriden by the Vue app made for translations. This override causes some problems with Multishop header, so I remove it. But, there is a difference : we still have the link for Translations item but not for International
I really hope this won't be an issue for you 🤞🏾

@sowbiba I don't think it will be a problem, the users can still click in the menu if they want to go to International

**Review by matthieu-rolland — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]
LGTM

**Review by NeOMakinG — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hello @sowbiba ,

Translations pages (and Design > Email Theme / Design > Email Theme > Translation) have the Multistore header : OK.

The header is switched and blocked in All Shops context on International > Translations pages : OK

Every "Modify Translation" pages (from International > Translations and Design > Email Theme) are switched and blocked in All Shops context : OK

Edit a translation : The edit is done on all shops : OK

pr 23927 translation OK

It's QA :heavy_check_mark: , thanks !

**Comment by sowbiba** [comment]
Thanks @Robin-Fischer-PS @PrestaShop/prestashop-maintainers

**Comment by atomiix** [comment]
Thanks @sowbiba & @Robin-Fischer-PS!

**Pull request merged**
