### PR TITLE
Display display_name instead of name in theme card and add author.url

### LINKED ISSUE #16054: PS admin panel - Theme & Logo - does not display theme name properly
PS 1.7.4.0 - 1.7.6.1
In the config/theme.yml there is two options, theme name (folder) and display theme name
Example:
name: pcstore
display_name: PC Store
version: 1.0.0

In the PS admin panel - Theme & Logo - under themes options, should display the "Display name", instead is the "name" displayed.
Those are descried in the PS dev documentation - https://devdocs.prestashop.com/1.7/themes/getting-started/theme-yml/

Screenshot https://ibb.co/L1LqcLH

Additionally - Author URL is not displayed anywhere
  author:
    name: "John Doe"
    email: "pub@prestashop.com"
    url: "https://www.prestashop.com"

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Changing the name of theme cards in theme options to display name
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16054
| How to test?  | Go to the Appearance->Theme and logo pannel and watch the theme name<br> and then check the author url on the Designed by line

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16461)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Congrats for the 1st PR @NeOMakinG 😉

**Review by PierreRambaud — APPROVED** [review]

**Comment by shahbazelahi** [comment]
Is bug fixed yet ?

**Comment by PierreRambaud** [comment]
> It bug fixed yet ?

When this pull request will be merged and the 1.7.7.0 will be released :)

**Comment by Progi1984** [comment]
Thanks @NeOMakinG

**Pull request merged**
