### PR TITLE
Fixed Microdata ItemList position : index starts to 1 and not 0

### LINKED ISSUE #27725: SEO error ItemList position product list
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Prestashop template file themes/classic/templates/_partials/microdata/product-list-jsonld.tpl the position is wrong. Position should always start with 1 not 0.

### Expected behavior

First item should have position 1.

### Steps to reproduce

1. Go to FO to a category page with products.
2. Show the source code
3. Search for @type": "ItemList
4. First item will have the "position": 0,

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

classic theme

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed Microdata ItemList position : index starts to 1 and not 0
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27725
| How to test?      |  Cf. #27725

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27814)

### CODE REVIEW

**Review by tegbessou — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

The issue is updated
https://github.com/PrestaShop/PrestaShop/issues/27725#issuecomment-1057903909
It is a regression from PS1780.
I think we need to change the base from develop to 1.7.8.x

Thank you!

**Comment by Progi1984** [comment]
Rebased to `1.7.8.x` branch.

**Review by saulaski — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @Progi1984,

It is ok :heavy_check_mark: 
In the FO, I checked those lists:
1. FO > Category list page with a filter & changing the order => ok 
image
2. FO > Search list
3. FO > Price drop list
4. FO > New products list
5. FO > Best sales list
6. Second shop > OK

https://user-images.githubusercontent.com/16067358/158154408-3664d178-104e-4a90-b6c9-92106d37bae6.mp4

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith

**Pull request merged**
