### PR TITLE
Fix ecotax value and label displayed in Admin Product form

### PR DESCRIPTION
**Pull request by didpoule**
| Questions | Answers
| -- | --
| Branch? | 1.7.6.x
| Description? | Fix ecotax displaying in admin product.
| Type? | bug fix
| Category? | BO
| BC breaks? | no (I think)
| Deprecations? | no
| Fixed ticket? | Partially, #9855
| How to test? | Save a product after editing ecotax and refresh the page. The ecotax value should be displayed tax included and the product price tax included should be correctly computed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21015)

### CODE REVIEW

**Comment by matks** [comment]
EDIT: mistake, my bad

**Comment by Progi1984** [comment]
@didpoule Hi, could you target the `develop` branch ? Thanks

**Comment by didpoule** [comment]
> @didpoule Hi, could you target the `develop` branch ? Thanks

Hi, i changed the target ;)

**Comment by Progi1984** [comment]
@didpoule Perfect. Could you rebase your PR for fixing conflicting files ? Thanks

**Comment by didpoule** [comment]
> @didpoule Perfect. Could you rebase your PR for fixing conflicting files ? Thanks

Hi, i'm checking this file : src/PrestaShopBundle/Model/Product/AdminModelAdapter.php
I see my PR is now obsolete cause an equivalent fix has been applied L538-541.
The comment explains the issue that i was fixing.
 
 Therefore I can close this one :).
 
 Regards,
 Jordan

**Comment by Progi1984** [comment]
Thank you for your contribution... :heart_eyes_cat:

**Pull request closed without merging**
