### PR TITLE
Change translation key when duplicate product

### LINKED ISSUE #31778: BO - Multistore - PPV2 -  Some issues when duplicating a product for all stores by Build actions
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments & expected behavior

the wording :ok: 
the product should be duplicated to all the stores . 

### Steps to reproduce

1. Go to BO > Shop parameters > General > Enable multistore
2. Go to BO > Advanced parameters > Multistore > Add two  new shops (shop1) , (shop2)
3. go to catalog >products>shop1 >create a new product .
4. go to products ALL SHOPS > select the product created , click on Duplicate selection for all stores on BUILD ACTIONS > see the first issue : _name store have only the parent shop name_ :x:
5. go to shop2 > see the second issue : _there is not a copy of the product created_ :x:

[Untitled_ Mar 14, 2023 10_23 AM.webm](https://user-images.githubusercontent.com/115152460/224960471-12792368-586f-4e13-a38f-c9e0fc39e15e.webm)

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Change translation key when duplicate product
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31778 
| Fixed ticket?     | Fixes #31778 
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by boherm — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @mflasquin 

I tested your PR, the wording is ok but the other issues still not fixed:

Auto Test : https://github.com/florine2623/testing_pr/actions/runs/5379873584 :heavy_check_mark: 
- The wording issue is fixed :heavy_check_mark: 
See attached screenshot:
image

-  The product duplicated in associated stores is assigned for all shops :x:
See attached screenshot:
image

- In Store(s) section, the duplicated product have both : the parent and child shop displayed :x:
See attached sceenshot:
image

Do not close the issue, it's partially fixed!

Thanks!

**Comment by florine2623** [comment]
Please do not close the linked issue as it is only partially fixed.

**Comment by nicosomb** [comment]
Thank you @mflasquin !

**Comment by MatShir** [comment]
@mflasquin you forgot the other wording 

https://github.com/PrestaShop/PrestaShop/issues/31778#issue-1623102017

> Change the wording:
> from: Activate selection for all stores
> to: Activate selection for associated stores
> 
> from: Deactivate selection for all stores
> to: Deactivate selection for associated stores
> 
> from: Duplicate selection for all stores
> to: Duplicate selection for associated stores
> 
> from: Delete selection for all stores
> to: Delete selection for associated stores

**Comment by MatShir** [comment]
@mflasquin Could you make a quick PR for the other wording ? So we can close the issue for good :)

**Pull request merged**
