### PR TITLE
Update native module versions

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Updated native module versions on composer.json
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | No tests needed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9167)

### CODE REVIEW

**Comment by eternoendless** [comment]
To be merged once tests are green

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Maybe you can merge PR on https://github.com/PrestaShop/welcome and update its too? :)

**Comment by eternoendless** [comment]
@PierreRambaud I can't, you need to wait for QA to validate it before :)

**Comment by eternoendless** [comment]
Regardless, beta won't have MBO in it, so maybe it's not needed right away?

**Comment by PierreRambaud** [comment]
The welcome module is broken since there is no MBO module http://forge.prestashop.com/browse/BOOM-5645

**Comment by eternoendless** [comment]
Unfortunately we can't merge it until it's approved by the QA

**Pull request merged**
