### PR TITLE
Added form theme to the address required fields

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Now address required fields uses form theme.
| Type?         | refacto
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Part of #16482
| How to test?  | Address required fields must look and work exactly the same

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21243)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

I have this issue: 
The white space:
image

Without PR => ok
image


Thanks!

**Comment by JevgenijVisockij** [comment]
> Hi @JevgenijVisockij,
> 
> I have this issue:
> The white space:
> image
> 
> Without PR => ok
> image
> 
> Thanks!

Fixed the problem, thanks for Q&A!

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

It is ok :heavy_check_mark: 
When all options are required => ok
image
When Options are not required => ok
image

From the BO, as it is an employee => ok  as described here: https://github.com/PrestaShop/PrestaShop/issues/17549

Thank you!

**Comment by Progi1984** [comment]
Thanks @JevgenijVisockij & @khouloudbelguith

**Pull request merged**
