### PR TITLE
Updating the PrestaShop images for installer last step

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop.
| Description?  | Updating the images of BO and FO in installer last step to reflect PrestaShop current design.
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a.
| How to test?  | Check you have the new images at the end of the installation process.

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]
Code looks good :stuck_out_tongue:

**Comment by AlexEven** [comment]
:grimacing:

**Comment by maximebiloe** [comment]
tenor

**Comment by aleeks** [comment]
THank you @AlexEven for your 200th PR!

**Pull request merged**
