### PR TITLE
Disable override button in performance page

### LINKED ISSUE #14596: Disable override button in performance page is not working
**Describe the bug**
The button to disable overrides is not working properly.

**To Reproduce**
1. Install a fresh PrestaShop
2. Add an override, for example for classes/CMS.php, override the __construct() function and add an echo 'hello'; followed by a die();
3. Delete the class_index in /var/cache/prod/class_index.php
4. Put yes on the disable overrides in the parameters in the back office
5. Go to any CMS page and modify it, the override is executed.
6. Even if i delete all the cache afterward it is still executed

I hope this is enough to reproduce the bug.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6

---

In the new version of the upgrade module, we should check if overrides are well disabled (see #14781)
We should fix this issue before working on the upgrade module

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Since PrestaShop 1.7.3.0 Disable override button don't generate new index classes
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/14596
| How to test?      | Create Override and check if is ok when you enable or disable override
| Possible impacts? | This may impact the people who decorate this adapter

**:notebook: BC Breaks**
* The class `DebugModeConfiguration ` has one new parameter : 
  * `PrestaShop\PrestaShop\Adapter\Cache\Clearer\ClassIndexCacheClearer`  $classIndexCacheClearer

It's a regression i can backport on 1.7.8 too  but no't has service; only with use PrestaShopAutoload for no BC break

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26070)

### CODE REVIEW

**Comment by kpodemski** [comment]
If this is a regression since 1.7.3 then `develop` is the right branch 👍

**Review by matthieu-rolland — DISMISSED** [review]
LGTM, never used the `ClassIndexCacheClearer` adapter before, but from what I see in the code your PR looks good to me 👍

**Comment by ghost** [comment]
_never used the ClassIndexCacheClearer_
 
At the first time i use : `use PrestaShopAutoloader;` after i see the adapater :+1:

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Can you please check the Conflicting files?

Thanks!

**Comment by ghost** [comment]
Close by : https://github.com/PrestaShop/PrestaShop/pull/26210

**Pull request closed without merging**
