### PR TITLE
Update module's information cache and add clear cache for doctrine

### LINKED ISSUE #33091: Module's information in backoffice are in different language after changing employee's lang
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you change language in your backoffice, your module list in Module Manager remains in the original language. The issue is caused by module manager caching the list in the wrong language.

Chaging the caching key by adding a language fixes the issue.
```
protected function getCacheKey(string $moduleName, ?int $shopId = null): string
    {
        $shop = $shopId ? [$shopId] : Shop::getContextListShopID();

        return $moduleName . implode('-', $shop) . Context::getContext()->language->id;
    }
```

The second issue is that the cache does not get cleared when using Performance > Clear cache button.

### Expected behavior

It should be in the correct language.

### Steps to reproduce

1. Install Prestashop in Czech.
2. Go to International > Localization and import United Kingdom localization, select to import only "Languages".
3. Go to right-top > Your profile and change your Language to English.
4. Go to Modules > Module Manager and see that all module names and descriptions are in Czech, not in English.
5. Clearing cache, still nothing.
6. When you reset a single module, that module will fix itself and appear in English.

Snímek obrazovky 2023-07-04 090956

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.0.x
| Description?      | Update module's information cache and add clear cache for doctrine
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test are green, and see https://github.com/PrestaShop/PrestaShop/issues/33091
| Fixed ticket?     | Fixes #33091
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Comment by M0rgan01** [comment]
Tests -> https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5533929263

**Review by Hlavtox — APPROVED** [review]

**Review by boherm — APPROVED** [review]
LGTM, thanks @M0rgan01 for your PR :)

**Review by florine2623 — APPROVED** [review]
Hello @M0rgan01 ,

Tested the PR, it is working as expected.

It is QA ✅

**Comment by Hlavtox** [comment]
Thanks everybody!!!

**Pull request merged**
