### PR TITLE
Rename routing file catalog.yml to _catalog.yml to follow routing structure

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | It seems that `catalog.yml` should be marked with underscore like `_catalog_yml` as it includes other resources under `/catalog` directory. If i wanted to add another routing file under this directory, it would be without underscore, for example `brands.yml`.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Migrated catalog pages should work.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9293)

### CODE REVIEW

**Comment by sarjon** [comment]
@mickaelandrieu can you check it?

**Review by PierreRambaud — DISMISSED** [review]
Nice catch

**Comment by mickaelandrieu** [comment]
@PierreRambaud looks like @prestonBot still have issues to find the right type of contribution :/

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @sarjon  and @PierreRambaud for the review

**Pull request merged**
