### PR TITLE
Style issue on BO

### PR DESCRIPTION
**Pull request by CaptainYouz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | This PR fixes the styles issues describe in #10339 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #10339
| How to test?  | Check before and after (on all new-theme BO pages)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10436)

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]

**Comment by mbadrani** [comment]
Everything seems de to be ok except this one below
image
@CaptainYouz  any idea?

**Comment by CaptainYouz** [comment]
@mbadrani i think this should be the correct behavior (info-box overlapping the side menu).

**Comment by mbadrani** [comment]
@CaptainYouz because on the issue #10339 one of the bug concerns this glitch as you can see below

image

**Comment by CaptainYouz** [comment]
Yep, but in a UX point of view, it is better that the tooltip overlap the existing content. Also, tooltip generally disappear on other click events. So in this case, the scenario caught in the screenshot should normally never appear. @TristanLDD what do you think ?

**Comment by eternoendless** [comment]
FYI we are progressively replacing those tooltips with help text below fields.

**Comment by TristanLDD** [comment]
Glitches that make tooltips unaligned to the interrogation points should be fixed indeed, but as @CaptainYouz said right, tooltips should always overlap the content, when they're opened you expect to be able to read them no matter the content displayed below.

**Comment by CaptainYouz** [comment]
@TristanLDD yes, the others glitches were fixed. It concerned the overlapping.

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
@CaptainYouz prepare yourself for a rebase. :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @CaptainYouz

**Pull request merged**
