### PR TITLE
Fix duplicate HTML id

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | duplicated HTML ids are invalid
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | In Supplier section of Product Page in back office, you should see only one "custom_fields" when doing something like $('#custom_fields') in your developer web toolbar

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12465)

### CODE REVIEW

**Review by PrestaEdit — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by ntiepresta** [comment]
@mickaelandrieu , we need more explanations to reproducing this behavior,  can you provide us the screenshot of the issue?.  I have the same behavior  without this Pr. 
sans pr meme chose
Thanks,

**Comment by mickaelandrieu** [comment]
ping @PrestaEdit for the explanations as this is him who has reported an issue 👍

**Comment by PrestaEdit** [comment]
Hi @ntiepresta !

While you have manufacturers and custom fields (customization) inside PrestaShop 1.7, the sames IDs are set.

Check this: https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_supplier_choice.html.twig#L26

And this:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Panels/options.html.twig#L145

**Comment by PierreRambaud** [comment]
look like there is a missing quote here:https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/views/Admin/Product/ProductPage/Forms/form_supplier_choice.html.twig#L55
Are you able to fix this in this PR or should I create a new one @mickaelandrieu ?

**Comment by mickaelandrieu** [comment]
> Are you able to fix this in this PR or should I create a new one @mickaelandrieu ?

hmm I'm not really fan of multi purpose pull requests, but I'll do it here: nice spotted @PierreRambaud :+1:

**Comment by mickaelandrieu** [comment]
hmm, something wrong happens with payment methods... 

https://travis-ci.org/PrestaShop/PrestaShop/jobs/489601915#L1232

I don't think it's related to the update (bug in FO, but an update of BO template), any idea someone?

/c @PrestaShop/prestashop-core-developers

**Comment by PierreRambaud** [comment]
@mickaelandrieu it's a problem related to Selenium, rerun and it should be ok.

**Review by PierreRambaud — APPROVED** [review]

**Comment by ntiepresta** [comment]
Hi,
After testing this Pr, I have the same behavior with or without this Pr. I have already reported  this behavior above. I atttached a video recorde for details. Could you please provide me steps to reproduce the issue or a video recorde for more details .
https://drive.google.com/file/d/12gRd5JWMX3f6zQQSHD8-xCrIu--3nPNK/view?usp=sharing
Thanks

**Comment by khouloudbelguith** [comment]
This PR fixes this issue: #12161

**Comment by ntiepresta** [comment]
Thanks @khouloudbelguith  for reply,
I manage to reproduce the issue.

**Comment by PierreRambaud** [comment]
Thanks @mickaelandrieu and @PrestaEdit

**Pull request merged**
