### PR TITLE
Fix missing reference symbol into Product::getProductProperties

### PR DESCRIPTION
**Pull request by hadjedjvincent**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow Product::getProductProperties to be used correctly
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Just try to edit something from "product" hook parameter, it will only work if you use this fix

### CODE REVIEW

**Comment by xBorderie** [comment]
I like how your whole team is cheering for you :)

**Comment by aleeks** [comment]
Make sense to me

**Review by aleeks — APPROVED** [review]

**Comment by aleeks** [comment]
Thank you @hadjedjvincent

**Comment by prestamodule** [comment]
@aleeks any chance to get this merged for 1.7.0.6 ? Thx

**Review by PrestaEdit — APPROVED** [review]

**Comment by prestamodule** [comment]
Hey @aleeks, any news about this fix please ? cc @xBorderie

**Comment by Quetzacoalt91** [comment]
Hello guys,

If you want to make this fix available on PS versions 1.7.1.x (this is too late for 1.7.0.6), you have to change the base branch. The branch develop contains changes for 1.7.2.x.

**Comment by hadjedjvincent** [comment]
@Quetzacoalt91 Updated now. BTW, too bad that @aleeks did not merged this 11 days ago as this was ready already.
Anyway, now, we have to make our PR using 1.7.1.x branch instead of develop ?

**Comment by Quetzacoalt91** [comment]
If we deal with a bug fix, yes. `develop` is also possible but this would make the fix only available from 1.7.2.x.

**Comment by Quetzacoalt91** [comment]
@hadjedjvincent and all your team, thank you.

**Pull request merged**
