### PR TITLE
put legacy context on cache during a request

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Build context is a very extensive task, we shouldnt construct it multiple times during 1 single request |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Launch a Blackfire analysis and monitor the call to `getContext()` before/after. On product page, the function was called 7 times, now it's only one. |

Related Blackfire graph => https://blackfire.io/profiles/compare/042b18e8-304d-415b-b05d-a71a7f0db04f/graph

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Interesting :+1: 

Do you already have some diff on Blackfire to show ?

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 sadly, I'm on windows at home, would you mind to add it ? :cat:

**Comment by Quetzacoalt91** [comment]
Here it is: https://blackfire.io/profiles/compare/042b18e8-304d-415b-b05d-a71a7f0db04f/graph

@mickaelandrieu: http://www.ubuntu.com/download/desktop

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 Thank you !

**Pull request merged**
