### PR TITLE
Fixed minor issues on Logs Grid page

### LINKED ISSUE #10280: Minors regressions on logs page
**Describe the bug**
I just found 2 minors regressions on the migrated log page

**To Reproduce**
1. Go to Advanced parameters > Logs
2. You will see checkboxes before each lines, on the legacy page there wasn't checkboxes because there isn't any bulk actions available

capture d ecran_251

capture d ecran_253

Then, you can erase everything, but when you click on it doesn't do anything

capture d ecran_252

Little display issue, the string "Logs by email" shouldn't be displayed above the field

capture d ecran_254

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed some minor issues of Logs page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixed #10280
| How to test?  | Ask @marionf 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10281)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
@mickaelandrieu, your PR already needs a rebase. :)

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 I've already rebased it 3 times in 1h lol

**Comment by PierreRambaud** [comment]
@mickaelandrieu But you need to run cs-fixer:
```bash
Loaded config default from "/home/travis/build/PrestaShop/PrestaShop/.php_cs.dist".
   1) /home/travis/build/PrestaShop/PrestaShop/src/Core/Grid/Definition/Factory/LogGridDefinitionFactory.php
```

**Comment by mickaelandrieu** [comment]
> @mickaelandrieu But you need to run cs-fixer:

something is wrong with our composer command that installs the pre-commit hook

**Review by PierreRambaud — DISMISSED** [review]

**Comment by marionf** [comment]
@mickaelandrieu 

When I click on erase all and ok, nothing is deleted
And there is a little display issue, the string "Logs by email" shouldn't be displayed above the field

capture d ecran_256

**Comment by mickaelandrieu** [comment]
> When I click on erase all and ok, nothing is deleted

Ok it's now fixed /c @sarjon use DELETE is not compatible with the javascript extension

For the design, I don't know I need help and docs since @eternoendless have changed the form theme from vertical to horizontal view.

Maybe can you hint me on what needs to be done Pablo?

**Comment by PierreRambaud** [comment]
> use DELETE is not compatible with the javascript extension

Since when? Which javascript extension?

**Comment by sarjon** [comment]
> Since when? Which javascript extension?

he means grid javascript extension, which is responsible for submiting action. :)

**Comment by PierreRambaud** [comment]
We maybe need to update javascript extension instead of remove DELETE method :/

**Comment by sarjon** [comment]
hi @marionf "Erase all" action and options layout is fixed. :+1:

**Comment by mickaelandrieu** [comment]
> We maybe need to update javascript extension instead of remove DELETE method :/

New features on the Grid component are not allowed until the release of 1.7.5, this will probably be done when we will check and update all routes.

**Comment by mickaelandrieu** [comment]
> and options layout is fixed.

I did nothing about it: are you sure? :angel: 

Can I expect an approval then? :rose:

**Comment by sarjon** [comment]
> I did nothing about it: are you sure?

i've updated it. :+1:

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @mickaelandrieu & @sarjon

**Pull request merged**
