### PR TITLE
Remove code linked to `gapi` Module

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove code linked to GApi Module
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | N/A
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26650)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Legit change, but no issue for this one?

**Comment by jolelievre** [comment]
No issue and no need to test this?

**Comment by Progi1984** [comment]
@jolelievre No need QA as the module is archives, it's removal of dead code. It was detected after a discussion with @MatShir and @PrestaShopCorp Extensions Team.

**Comment by MatShir** [comment]
I don't know about the no QA but for the issue since it is to remove dead code I think we can bypass it for this one ;)

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @Progi1984

**Pull request merged**
