### PR TITLE
FR translation for top menu items

### PR DESCRIPTION
**Pull request by xBorderie**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Translate SELL into VENDRE, IMPROVE into PERSONNALISER, CONFIGURE into CONFIGURER, and DEFAULT into AUTRES. |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | n/a |
| How to test? | Download Duolingo. Learn French. Check spelling. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
ping @AlexEven for when she comes back from holidays :)

**Comment by xBorderie** [comment]
And a question: why is uppercase not handled through CSS rather than in the text? Screenreaders will read it as an acronym: S-E-L-L. Tiring. #a11y

**Comment by AlexEven** [comment]
+1 for the CSS.

Good to go!

**Comment by maximebiloe** [comment]
I just changed the CSS to transform the text automatically in this commit: https://github.com/PrestaShop/PrestaShop/pull/6236/commits/fbc425552fbb72a97dee1f900f1cbe36b98c7e06.

**Comment by xBorderie** [comment]
Merci @maximebiloe !

**Pull request merged**
