### PR TITLE
[-] BO : Fixed show categories tree in the admin panel

### PR DESCRIPTION
**Pull request by wellic**
Tree of categories is displayed incorrectly when adding, editing and viewing category.

### CODE REVIEW

**Comment by wellic** [comment]
STR:

1) Go to admin mode
2) Select in menu Catalog->Categories
3) Click  button in the toolbar "Add New Categories" or "View"/"Edit" button of exists Category
4) Check "Parent category"

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR,  @jocel1 is already on it.

Best regards.

**Comment by wellic** [comment]
The pull-request #2768 duplicates this pull-request?

**Comment by jeromenadaud** [comment]
Hi Wellic,

Thank you for your dedication and your great help, @jocel1 has integrated your changes and something more. So I close this PR. Keep contributing, we need your help.

Kindly regards.

**Pull request closed without merging**
