### PR TITLE
Added management of the 'addedByModule' field in the "CustomizationField" object

### PR DESCRIPTION
**Pull request by Codencode**
In the ProductFormDataProvider::extractCustomizationsData() method, I added the 'addedByModule' key to the $fields array. In the CustomizationFieldsCommandsBuilder::buildCustomizationFields() method, I added the 'added_by_module' key to the $customizationFields array.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | If a module uses product customization and sets in the table 'PREFIX_customization_field' is_module=1 , every time the product is saved (after changing name,price etc ) using Prestashops Save and Publish, the product is saved with is_module=0
| Type?             | bug fix
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | 1) Create a product with a customization field. 2) In the `customization_field` table, set `is_module` to 1 for the record corresponding to the field of the created product. This simulates that the field was created by a module. 3) Go to BO and update the product and verify that the `is_module` field in `customization_field` table remains set to 1.
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/discussions/36897
| UI Tests | https://github.com/florine2623/testing_pr/actions/runs/10903696477
| Sponsor company   | @Codencode

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@Codencode Seems we need to fix unit tests. ;-)

In `tests\Unit\Core\Form\IdentifiableObject\DataProvider\ProductFormDataProviderTest.php` find `getDatasetsForCustomizations`

And add `'addedByModule' => false` after `'required' => false,` in all arrrays.

**Comment by Codencode** [comment]
> @Codencode Seems we need to fix unit tests. ;-)
> 
> In `tests\Unit\Core\Form\IdentifiableObject\DataProvider\ProductFormDataProviderTest.php` find `getDatasetsForCustomizations`
> 
> And add `'addedByModule' => false` after `'required' => false,` in all arrrays.

@Hlavtox,
I did it.

Thanks

**Comment by Hlavtox** [comment]
@Codencode Good! :-) Now just a CS fixer - add comma after `'addedByModule' => $customizationField->isAddedByModule()`

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
UI test - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/10864164803

**Review by tleon — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Codencode ,

Without PR :

https://github.com/user-attachments/assets/584825b0-ec27-4921-b00d-39c1f785ba11

With PR, it works as expected. In the customization_field, the column is_module keeps its value :

https://github.com/user-attachments/assets/7a1f370d-24dd-477b-85d8-de3d289ac389

Thanks!
It is QA ✅

**Comment by Hlavtox** [comment]
Again, good job @Codencode & @florine2623! :-))

**Pull request merged**
