### PR TITLE
This PR fixes #12509

### LINKED ISSUE #12509: ContextErrorException on order if Legal compliance module is installed
**Describe the bug**
When we do an order with Cash on delivery payment method then the **(1/1) ContextErrorException
Warning: Cannot use a scalar value as an array** exception will occur. The exception occurs when only the debug mode is on and the configuration in this module **"Proportionate tax for shipping and wrapping"** is set to **YES**

**To Reproduce**

1. configure the pretashop as mentioned in the description. 
1. Add any product in cart, a tax should be applied on the product.
1. Go to checkout, select the shoipping method, (it should not be free)
1. Chosse payment method
1. and click on "Order with an obligation to pay" 

**Screenshots**
Module Configuration page  - 
legalcompliance

Error - 
legalcomplianceerror

**Additionnal information**
PrestaShop version: 1.7.4.4, 1.7.5.0
PHP version: 7.0

### PR DESCRIPTION
**Pull request by PeeyushAgrawal**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |1.7.5.x
| Description?  | This PR fixes the ContextErrorException occurring  on order creation if Legal compliance module is installed
| Type?         | bug fix /  critical
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12509 
| How to test?  | Perform the same steps as described to reproduce the issue in #12509. This PR will fix the issue.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12683)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hmm, this changes look like invalid as you change the data structure returned by the method by adding the id_tax on each row.

I wonder how the caller still works with the data modified.

**Comment by ghost** [comment]
Hi @PeeyushAgrawalWebku, thanks for the PR 👍 

Can you have a look at @Quetzacoalt91 feedback, please?

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 

Please let me know if anything remaining from my end.

Thanks,

**Comment by PeeyushAgrawal** [comment]
Hello @samuel-pires 

Please check and let me know if anything is remaining from my end.

Thanks

**Comment by PeeyushAgrawal** [comment]
Hello @Quetzacoalt91 

Could you please let ma know that the changes done by me is invalid? Should i do something on this. Please check.

Thanks

**Comment by matks** [comment]
Sorry for the late answer @PeeyushAgrawalWebkul it seems your PR was lost in the queue. I just spend 2 hours trying to understand what AverageTaxOfProductsTaxCalculator is supposed to do 😄 and my conclusion is that it was broken from the start for usage with `getTaxesAmount()` with `$price_after_tax` used.

I see in your PR you're trying to fix it by injecting the data using `id_tax` as a gateway for `Tools::spreadAmount()` to be able to work properly, but this would be a "quick and dirty fix" 😉 we better fix it for good.

**Pull request closed without merging**
