### PR TITLE
Fixed missing attributes (employee) to call removeProduct

### PR DESCRIPTION
**Pull request by madef**
| Questions | Answers |
| --- | --- |
| Branch? | Use the "develop" branch if you target PrestaShop 1.7; use the "1.6.1.x" branch if you target PrestaShop 1.6 (bugfixes only). |
| Description? | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc. |
| Type? | bug fix / improvement / new feature |
| Category? | See [the Category list](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message#Howtowriteacommitmessage-Category), i.e.: BO |
| BC breaks? | Does it break backward compatibility? yes/no |
| Deprecations? | Does it deprecate an existing feature? yes/no |
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL. |
| How to test? | Please indicate how to best verify that this PR is correct. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by txmodxoops** [comment]
Issues v 1.6.1.6:

PHP Warning:  Missing argument 1 for ShoppingFluxExport::getIp(), called in /modules/shoppingfluxexport/shoppingfluxexport.php on line 1501 and defined in /modules/shoppingfluxexport/shoppingfluxexport.php on line 2000

**Comment by mickaelandrieu** [comment]
@madef please take time to update your contribution regarding @prestonBot comments please :)

**Comment by madef** [comment]
Hi,

If you look the  signature of the method removeProduct you will see that the is a $employee as parameter (so it's defined to null in the worst case).
This method call itself in ordrer to remove pack quantities. But the employee is not set in the parameters.

If you call removeProduct from a script and you specify an employee (#2) different from the employee (#1) in the context, the stock will not be changed by the same employee for the product and the pack.
And if you don't have any employee from the context, PrestaShop will crash because removeProduct will use the employee from the context is the parameter $employee is missing.

That why, it's really important to use the same signature for the two calls.


Best regards,

**Comment by aleeks** [comment]
Hello,
Thank you for your explanation, why did you not apply the same fix on the second call line 266 ?
Moreover, can you update your PR description (branch, type, category, etc.) ?

Regards

**Comment by aleeks** [comment]
I cherry-pick your commit here https://github.com/PrestaShop/PrestaShop/pull/7503 rebased from develop.
Thank you @madef

**Pull request closed without merging**
