### PR TITLE
Fix module modal layout

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Fix module modal layout
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3629
| How to test?  |

**Before**
capture d ecran 2017-08-10 a 14 32 37

**After**
capture d ecran 2017-08-10 a 16 05 39

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
We have 2 different style between discover and the action buttons:

capture du 2017-08-10 14-50-03

capture du 2017-08-10 14-49-28

**Comment by maximebiloe** [comment]
Nice catch @Quetzacoalt91. I just made fixes.

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]
Code looks good!

**Comment by Quetzacoalt91** [comment]
Thank you @maximebiloe

**Comment by marionf** [comment]
@maximebiloe 
For some modules the stars-ranking are truncated, maybe according to the size of the description ?

capture du 2017-08-10 18-18-11

**Pull request merged**
