### PR TITLE
Display product reference when product has no combination

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Display product reference when product has no combination
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2657
| How to test?  |

### CODE REVIEW

**Review by aleeks — APPROVED** [review]

**Comment by vincentbz** [comment]
Hi,

If my product doesn't have any reference, then it displays the label Reference. It shouldn't display anything.
I can find a version where it worked, a few weeks ago, if needed.
Thanks !

image

**Comment by maximebiloe** [comment]
Thanks @vincentbz. It should be okay now.

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by aleeks** [comment]
Thank you @maximebiloe

**Pull request merged**
