### PR TITLE
Fix product pagination in order with customization

### LINKED ISSUE #18959: BO - View order pagination does not display right number of products
#### Describe the bug

At the first access to an order (with minimum 9 products), the pagination is OK, with 8 products. If you change page (to page 2 for example), the last product on page 1 is present at the top of page 2.
If you return to page 1, only 7 products are displayed instead of 8.

#### Expected behavior

Pagination should always display 8 products per page.

#### Steps to Reproduce

1. Create an order with at least 9 different products
2. View the order : First page displays 8 products.
3. Go to page 2 : Last item of page 1 is displayed at top of page 2, it should not
4. Go back to page 1 : Only 7 products are displayed.

**Screenshots**

On my example : "Coussin renard" is displayed at top of page 2, it should not. When back on page 1, it is not displayed, it should.
https://drive.google.com/file/d/17-T7sofE5_ifkv5GDHXRnFqIjTRiOVlM/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | The pagination of products in an order details wasn't working when a customized product was in the list. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18959 
| How to test?  | 1. Create an order with at least 9 different products and with at least 1 customized product among the first 7th.<br>2. View the order : the pagination should work as intended (See #18959 for more details)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19039)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
I feel more at ease with this kind of code 😅

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
OK for QA, thanks @atomiix

**Comment by Progi1984** [comment]
@atomiix Need rebase ;)

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @atomiix

**Pull request merged**
