### PR TITLE
[*] BO : Allow to access module configuration in demo mode

### PR DESCRIPTION
**Pull request by Shagshag**

### CODE REVIEW

**Comment by kpodemski** [comment]
I think that demo mode shouldn't allow access to configuration... what is the point of this?

**Comment by Shagshag** [comment]
For a module demonstration, an access to the module configuration page is needed.

**Comment by jeromenadaud** [comment]
Hi,

Like @kpodemski I think if you want to configure module for testing purpose you will need to show other things not accessible in demo mode. In my opinion you can easily configure you shop with correct employee ACL administration.

Best regards.

**Comment by Shagshag** [comment]
> In my opinion you can easily configure you shop with correct employee ACL administration.

No :disappointed: There is no way to prevent the user to modify his password (from the login form or the 'My preference' page) except in demo mode.

So everybody can block the demo access easily. This is not usable.

**Comment by jeromenadaud** [comment]
Hi, 

The best way to achieve this is to prevent a user to modify his password from a special ACL.
I have reported this to our Product Managers, and I close this PR

I you want you can make a PR and help us to do it in this way.

Best regards.

**Comment by Shagshag** [comment]
@jeromenadaud 
say him to allow to block the "forgot your password" feature from the login page also.

**Comment by jeromenadaud** [comment]
Ok , sended.

Best regards.

**Pull request closed without merging**
