### PR TITLE
Add BOOM campaign

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR gathers all the scenarios of the BOOM tickets in a separate campaign named "boom"
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | npm run boom -- --URL=FrontOfficeURL --DIR=DownloadDirectory --URLLASTSTABLEVERSION=LaststableversionURL --DB_SERVER=DataBaseServer --DB_USER=DataBaseUser --DB_PASSWD=DataBasePassword --RCLINK=RCDownloadlink --RCTARGET=LastStableVersionLocation --FILENAME=RCFileName --LANGUAGE=language --COUNTRY=country

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9303)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @fatmaBouchekoua, thanks for writing these non-regression tests :+1:

**Comment by PierreRambaud** [comment]
Should I close this one, or change target branch?

**Comment by fatmaBouchekoua** [comment]
Hello @PierreRambaud , 
I will change the target branch.

**Comment by fatmaBouchekoua** [comment]
@mbadrani ready to be merged !

**Review by mbadrani — APPROVED** [review]
Review and QA validation done by Fatma

**Pull request merged**
