### PR TITLE
Fix: Original product image converted to WebP if set Image format: Use WebP for all images #34705

### LINKED ISSUE #34705: Original product image converted to WebP if set Image format: Use WebP for all images.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you upload a product image with the following settings:

- Advanced Parameters > New & Experimental Features > Multiple image formats: DISABLED
- Design Image Settings > Image Settings > Image format: Use WebP for all images.

Screenshot - New   Experimental Features - 1
Screenshot - Image Settings - 1

the system also compresses the original image in WebP, ERROR

When you upload a product image with the following settings:

- Advanced Parameters > New & Experimental Features > Multiple image formats: ENABLED
- Design Image Settings > Image Settings > Image formats to generate: WebP, AVIF
- Design Image Settings > Image Settings > Base format: Use JPEG
Screenshot - New   Experimental Features - 2
Screenshot - Image Settings - 2

the system does not convert the original image to WebP, CORRECT

Video:
https://github.com/PrestaShop/PrestaShop/assets/2463965/5efb77b4-c28b-40f7-8a68-e1aede3f32e5

### Expected behavior

_No response_

### Steps to reproduce

1. Go to Advanced **Parameters > New & Experimental Features** and set **Multiple image formats** to **Disabled**
2. Go to **Design Image Settings > Image Settings** and set **Image format** to **Use WebP for all images**
3. ​Upload an image of a product
4. The original file is of type WebP

### PrestaShop version(s) where the bug happened

8

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.2.x 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed issue or discussion?     | Fixes #34705

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
I think PNG images will loose transparency, because with `$forceType` you convert everything to JPG. 🤔

**Comment by Hlavtox** [comment]
I thought of removing this portion of code...

```php
if (Configuration::get('PS_IMAGE_QUALITY') == 'webp_all'
                || (Configuration::get('PS_IMAGE_QUALITY') == 'webp' && $sourceFileType == IMAGETYPE_WEBP)) {
                $destinationFileType = 'webp';
            }
```

Then it should work, but one usecase is broken.
- If `$destinationFileType` is `jpg` and `$forceType` is `false`, it will auto decide ONLY between JPG and PNG. This is good for original images, but bad for thumbnails, if `Configuration::get('PS_IMAGE_QUALITY') == 'webp_all'` or `Configuration::get('PS_IMAGE_QUALITY') == 'webp'`. 🔴 
- If `$destinationFileType` is `jpg` and `$forceType` is `true`, it will use JPG. 🟢 
- If `$destinationFileType` is `png` and `$forceType` is `true`, it will use PNG. 🟢
- If `$destinationFileType` is `webp` and `$forceType` is `true`, it will use WEBP. 🟢

We need to tell that method, that in case `$destinationFileType` is `jpg` + `$forceType` is `false`, if it should decide between JPG/PNG or JPG/PNG/WEBP.

**Comment by Codencode** [comment]
> Then it should work, but one usecase is broken.
> 
> * If `$destinationFileType` is `jpg` and `$forceType` is `false`, it will auto decide ONLY between JPG and PNG. This is good for original images, but bad for thumbnails, if `Configuration::get('PS_IMAGE_QUALITY') == 'webp_all'` or `Configuration::get('PS_IMAGE_QUALITY') == 'webp'`. 🔴
> * If `$destinationFileType` is `jpg` and `$forceType` is `true`, it will use JPG. 🟢
> * If `$destinationFileType` is `png` and `$forceType` is `true`, it will use PNG. 🟢
> * If `$destinationFileType` is `webp` and `$forceType` is `true`, it will use WEBP. 🟢
> 
> We need to tell that method, that in case `$destinationFileType` is `jpg` + `$forceType` is `false`, if it should decide between JPG/PNG or JPG/PNG/WEBP.

It is true!

I could check if 'PS_IMAGE_QUALITY' is 'webp_all' set 
$forceType = true
otherwise
$forceType = false

```                
                $forceType = Configuration::get('PS_IMAGE_QUALITY') == 'webp_all';
                if (!ImageManager::resize($file['save_path'], $new_path . '.' . $image->image_format, null, null, 'jpg', $forceType, $error)) {
```
I did a test, and if I set 'Image format': "Use PNG only if the base image is in PNG format." transparency remains.
Could it go?

**Comment by Hlavtox** [comment]
@Codencode It will be fixed properly by https://github.com/PrestaShop/PrestaShop/pull/34172.

**Comment by Codencode** [comment]
> @Codencode It will be fixed properly by #34172.

Ok, thanks

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `description` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#description))
* The `BC breaks` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#bc-breaks))
* The `deprecations` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#deprecations))
* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by matks** [comment]
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

**Pull request closed without merging**
