### PR TITLE
Reduce the number of ajax calls if the fixtures are not too larges and if there's enough memory available

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Fix install speed regression due to too many ajax calls
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Install and check the number of ajax calls (should be only 1 for each steps, no subtasks)

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9302)

### CODE REVIEW

**Comment by rGaillard** [comment]
@jocel1 you can maybe store in the session data the size of the XML files in order to avoid to calculate it at each step?
Also it should be interresting to check the memory used by the installer with the standard fixtures to potentially adapt the current value of 42M.

**Comment by rGaillard** [comment]
Also, glob is sometime denied by the server configuration but normally that throw only a PHP warning?

**Comment by jocel1** [comment]
@rGaillard actually display is only called once, it's the function which compute which steps should be executed. 
I don't know if it's worth increasing the complexity for the 42M if it was working properly for small shop before (the real memory usage depends on the php version, and in most of the case should be >= 128M with modern php version).
I'll remove glob and use readdir instead

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9302)* status: all files reviewed, 2 unresolved discussions (waiting on @jocel1 and @rGaillard)

___
*[install-dev/controllers/http/process.php, line 375 at r2](https://reviewable.io/reviews/prestashop/prestashop/9302#-LH97Qlt5HyjpBqgvqvT:-LH97Qlt5HyjpBqgvqvU:b-tl0cj8) ([raw file](https://github.com/prestashop/prestashop/blob/3db269fd4d4c5cb9d8a329f7b0386fc420a811a7/install-dev/controllers/http/process.php#L375)):*
> ```PHP
>     {
>         $size = 0;
>         $fixtureDir = __DIR__.'/../../fixtures/fashion/data/';
> ```

Not a fan of this being hardcoded here. The same info is here: https://github.com/PrestaShop/PrestaShop/blob/4a3b9894c083315768cebe912aaad355c49657ba/src/PrestaShopBundle/Install/Install.php#L1051
___
*[install-dev/controllers/http/process.php, line 376 at r2](https://reviewable.io/reviews/prestashop/prestashop/9302#-LH97ZuL1LgVZQwT9S1-:-LH97ZuL1LgVZQwT9S10:bas7zpe) ([raw file](https://github.com/prestashop/prestashop/blob/3db269fd4d4c5cb9d8a329f7b0386fc420a811a7/install-dev/controllers/http/process.php#L376)):*
> ```PHP
>         $size = 0;
>         $fixtureDir = __DIR__.'/../../fixtures/fashion/data/';
>         $dh = @opendir($fixtureDir);
> ```

Why the `@`? If you can't open the directory, there's a problem and it must bubble up.

**Review by jocel1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9302)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @eternoendless and @rGaillard)

___
*[install-dev/controllers/http/process.php, line 375 at r2](https://reviewable.io/reviews/prestashop/prestashop/9302#-LH97Qlt5HyjpBqgvqvT:-LHAE1R57QjNn2xcBnCr:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/3db269fd4d4c5cb9d8a329f7b0386fc420a811a7/install-dev/controllers/http/process.php#L375)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Not a fan of this being hardcoded here. The same info is here: https://github.com/PrestaShop/PrestaShop/blob/4a3b9894c083315768cebe912aaad355c49657ba/src/PrestaShopBundle/Install/Install.php#L1051
</blockquote></details>

Done.
___
*[install-dev/controllers/http/process.php, line 376 at r2](https://reviewable.io/reviews/prestashop/prestashop/9302#-LH97ZuL1LgVZQwT9S1-:-LHAE2FU6tHcCcFuDctx:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/3db269fd4d4c5cb9d8a329f7b0386fc420a811a7/install-dev/controllers/http/process.php#L376)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why the `@`? If you can't open the directory, there's a problem and it must bubble up.
</blockquote></details>

Done.

**Comment by Quetzacoalt91** [comment]
Tested on my shop, no more subtasks. :+1:

**Review by eternoendless — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9302#-:-LHCuRswAR3kDWR38_9d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rGaillard)

**Comment by eternoendless** [comment]
Thank you @jocel1

**Pull request merged**
