### PR TITLE
Remove unexpected binary condition

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There is an overcomplicated condition with int conversion and binary operators that could be handled with simple boolean operators.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green / Prestashop tests
| UI Tests          | -
| Fixed issue or discussion?     | -
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by PululuK — APPROVED** [review]

**Review by matks — APPROVED** [review]
For me the big added value of this PR is removing the bitwise operator. The && operator is easier to read.

**Comment by matks** [comment]
@davidglezz Could you please run the UI Tests to make sure this PR works as expected?

**Comment by davidglezz** [comment]
Sorry, I have not been able to run these tests.
Any suggestions on how to run them on Mac?
a simple docker command would be great

**Comment by kpodemski** [comment]
@davidglezz you don't need to run them locally but using provided Github action: https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/#using-ui-tests-to-verify-a-prs-pull-requests

**Comment by kpodemski** [comment]
I ran them for you: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/9774245853

**Review by kpodemski — APPROVED** [review]
All tests are green.

Thank you @davidglezz !

**Pull request merged**
