### PR TITLE
Fix: Setting DNI mandatory after address creation launches an exception during checkout

### LINKED ISSUE #31668: Setting DNI mandatory after address creation launches an exception during checkout
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If for a country there is the mandatory CF field and try to make an order (in the front-office) with an address that has the DNI empty field, the system shows an error that I attach.
Screenshot 2023-03-07 at 10-22-40 Screenshot

### Expected behavior

Error/Alert message inviting the customer to complete all the mandatory fields in the address

### Steps to reproduce

1. Add a product to the cart (no account)
2. Go in the checkout and create an account
3. Add an address, select Italy as a country
4. Save the address (don't complete the checkout, very important)
5. As an administrator (BO), go to back office, International > Country, edit Italy and enable the DNI field as mandatory
6. As the new customer (FO) try to complete the checkout

The problem occurs due to the modification to the **restorePersistedData** method of the Controller **controllers/front/Ordercontroller.php**
Until version 1.7.8.7 of PS the education $ This-> Cartchecksum-> GenerateChecksum ($ cart) Venifa performed only if there were no non-valid addresses, while in 1.7.8.8 this is always performed and therefore one is launched "non -managed" exception

**PS 1.7.8.7**
```

    protected function restorePersistedData(CheckoutProcess $process)
    {
        $cart = $this->context->cart;
        $customer = $this->context->customer;
        $rawData = Db::getInstance()->getValue(
            'SELECT checkout_session_data FROM ' . _DB_PREFIX_ . 'cart WHERE id_cart = ' . (int) $cart->id
        );
        $data = json_decode($rawData, true);
        if (!is_array($data)) {
            $data = [];
        }

        $addressValidator = new AddressValidator();
        $invalidAddressIds = $addressValidator->validateCartAddresses($cart);

        // Build the currently selected address' warning message (if relevant)
        if (!$customer->isGuest() && !empty($invalidAddressIds)) {
            $this->checkoutWarning['address'] = [
                'id_address' => (int) reset($invalidAddressIds),
                'exception' => $this->trans(
                    'Your address is incomplete, please update it.',
                    [],
                    'Shop.Notifications.Error'
                ),
            ];

            $checksum = null;
        } else {
            $checksum = $this->cartChecksum->generateChecksum($cart);
        }

        // Prevent check for guests
        if ($customer->id) {
            // Prepare all other addresses' warning messages (if relevant).
            // These messages are displayed when changing the selected address.
            $allInvalidAddressIds = $addressValidator->validateCustomerAddresses($customer, $this->context->language);
            $this->checkoutWarning['invalid_addresses'] = $allInvalidAddressIds;
        }

        if (isset($data['checksum']) && $data['checksum'] === $checksum) {
            $process->restorePersistedData($data);
        }
    }

```

**PS 1.7.8.8**

```

    protected function restorePersistedData(CheckoutProcess $process)
    {
        $cart = $this->context->cart;
        $customer = $this->context->customer;
        $rawData = Db::getInstance()->getValue(
            'SELECT checkout_session_data FROM ' . _DB_PREFIX_ . 'cart WHERE id_cart = ' . (int) $cart->id
        );
        $data = json_decode($rawData, true);
        if (!is_array($data)) {
            $data = [];
        }

        $addressValidator = new AddressValidator();
        $invalidAddressIds = $addressValidator->validateCartAddresses($cart);

        // Build the currently selected address' warning message (if relevant)
        if (!$customer->isGuest() && !empty($invalidAddressIds)) {
            $this->checkoutWarning['address'] = [
                'id_address' => (int) reset($invalidAddressIds),
                'exception' => $this->trans(
                    'Your address is incomplete, please update it.',
                    [],
                    'Shop.Notifications.Error'
                ),
            ];
        }

        // Prevent check for guests
        if ($customer->id) {
            // Prepare all other addresses' warning messages (if relevant).
            // These messages are displayed when changing the selected address.
            $allInvalidAddressIds = $addressValidator->validateCustomerAddresses($customer, $this->context->language);
            $this->checkoutWarning['invalid_addresses'] = $allInvalidAddressIds;
        }

        if (isset($data['checksum']) && $data['checksum'] === $this->cartChecksum->generateChecksum($cart)) {
            $process->restorePersistedData($data);
        }
    }

```

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.0.x, 8.1.0

### PHP version(s) where the bug happened

7.4, 8.0, 8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | If for a country there is the mandatory CF field and try to make an order (in the front-office) with an address that has the DNI empty field, the system shows an error that I attach.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #31668

### CODE REVIEW

**Comment by marsaldev** [comment]
Hi @Codencode, thanks for your contribution! 
I've fixed some specs in your description 😉

**Review by boherm — COMMENTED** [review]
LGTM, thanks for you contribution @Codencode.
(I don't approve now, because maybe it can be cool too have this fix first of all for 8.1.x, that can be merged into develop later. cc @PrestaShop/prestashop-core-developers)

**Comment by Codencode** [comment]
> (I don't approve now, because maybe it can be cool too have this fix first of all for 8.1.x, that can be merged into develop later. cc

Hi @boherm,
so should i create a branch with the changes starting from the 8.1.x branch [https://github.com/PrestaShop/PrestaShop/tree/8.1.x](https://github.com/PrestaShop/PrestaShop/tree/8.1.x)?

**Review by Hlavtox — CHANGES_REQUESTED** [review]
I think you should implement this check in `AddressChecksumCore::generateChecksum` and `return sha1('No address set');` like it does `if (!$address->id)`.

The solution you propose changes the behavior quite drastically and returns empty cart checksum.

**Comment by Codencode** [comment]
> I think you should implement this check in `AddressChecksumCore::generateChecksum` and `return sha1('No address set');` like it does `if (!$address->id)`.
> 
> The solution you propose changes the behavior quite drastically and returns empty cart checksum.

Hi @Hlavtox 
thank you for your suggestion.
I closed this pull and created a new one starting from PS 8.1.x in which I recreated the change by inserting your suggestion.

The new pull is: [https://github.com/PrestaShop/PrestaShop/pull/32290](https://github.com/PrestaShop/PrestaShop/pull/32290)
Thank you!

**Pull request closed without merging**
