### PR TITLE
Add a new hook on AdminCutomers view > Addresses actions

### PR DESCRIPTION
**Pull request by comxd**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR adds a new hook called displayAdminCustomersAddressesItemAction on the AdminCutomers view page at the addresses section. This hook located into the dropdown menu actions at the end of list just before the closing list tag </ul>.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8401)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @comxd, good idea.

What do you think @PrestaShop/prestashop-core-dev ?

For me, it's :+1:

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8401#-:-Kxw8aHowPlFhsrOlOYD:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by kpodemski** [comment]
@LittleBigDev wrong :)

not need to use |intval + sql update file is depreciated, sql should be in 1.7.3.0 in my opinion

**Review by kpodemski — CHANGES_REQUESTED** [review]
not need to use intval + sql should be in file of the new version

**Comment by LittleBigDev** [comment]
Oh I missed the filename ! Thanks !
About the intval : I think it's no harm making sure we are handling an integer. Better safe than sorry :)

**Comment by LittleBigDev** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[install-dev/upgrade/sql/1.7.2.3.sql, line 1 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8401#-KyFvZmAXFX0kZE5TmK_:-KyFvZmAXFX0kZE5TmKa:b-ru0w89) ([raw file](https://github.com/prestashop/prestashop/blob/3d38df0b21406bb6245392ff82406ddf097985c5/install-dev/upgrade/sql/1.7.2.3.sql#L1)):*
> ```SQLPL
> SET SESSION sql_mode = '';
> ```

This should be done in 1.7.3.0.sql

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8401)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
See my review comment above

**Comment by vincentbz** [comment]
Hi guys,

Are some changes requested to merge that PR in 1.7.3.0 ?

Thanks !

**Comment by Quetzacoalt91** [comment]
Yes, see @LittleBigDev comments.

**Comment by vincentbz** [comment]
Ok, thanks, so it'll will be in one of the next versions, not in 1.7.3.0 :)

**Comment by comxd** [comment]
Hi,

Please review @vincentbz @LittleBigDev

**Comment by LittleBigDev** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8401)*

**Review by LittleBigDev — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Pull request merged**
