### PR TITLE
Actually use arguments passed to CountryDataProvider->getCountries()

### PR DESCRIPTION
**Pull request by TysonAndre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no?
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | call CountryDataProvider with parameters different from defaults

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12399)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
HI @TysonAndre 

Thanks for this PR, I would accept it if it was targeting the `develop` branch. The branch `1.7.5.x` is opened to fix the regressions found in PS 1.7.5.0.

Would you mind switching this PR for `develop`? Thanks

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@PierreRambaud I dont think we need a QA validation here ?

**Comment by PierreRambaud** [comment]
Yes, no need QA :) We can merge when travis will be ok.

**Comment by matks** [comment]
Looks like Travis never started the test build 🤔 maybe because of the branch switch

**Comment by matks** [comment]
@TysonAndre since Travis has "lost" the build ID (I found the build, it's valid, but it seems github did not receive Travis feedback) I've added a useless commit to your branch (sorry for that) in order to re-trigger Travis check

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @TysonAndre

**Pull request merged**
