### PR TITLE
Fix license comment CS

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | PHP license comment/header must never be parsed as phpdoc. Regexes used to make this PR are below.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | CI must pass, changes can be verified by applying the regexes localy.
| Possible impacts? | no

Regexes used to make this PR:

```
(<\?php\s+/\*)\*(\s+\*[^\n]+PrestaShop)
$1$2

(<\?php\s+/\*\s+\*[^\n]+PrestaShop((?!/\*)(.|\n))+?\*/(?!\n\n))
$1\n
```

Changes checked. Please review and merge quickly to prevent conflicts on removed/added/moved files.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24673)

### CODE REVIEW

**Comment by eternoendless** [comment]
Sorry @mvorisek but this PR is impossible to review. Can you please just fix it here https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Command/UpdateLicensesCommand.php? We will execute the update ourselves later.

**Comment by mvorisek** [comment]
then keep open to allow that changes :D

**Comment by mvorisek** [comment]
@eternoendless this needs to be reopened as changes in at least Tools class are needed

**Comment by eternoendless** [comment]
You are welcome to create a new PR for the change in UpdateLicensesCommand

**Comment by PierreRambaud** [comment]
I don't understand why we should do this kind of change as parts of our licenses headers contain phpdoc elements:
https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.license.pkg.html
https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.author.pkg.html

**Comment by mvorisek** [comment]
When another phpdoc is not above the expression following the license header, the license header is wrongly attached (by apps using it) to that element.

See how Symfony or other major php apps format license headers. Can we agree on this @PierreRambaud ?

**Comment by PierreRambaud** [comment]
They use this 
```php
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

```

Because they don't include phpdoc elements, but we do.

**Comment by mvorisek** [comment]
I have written above why generated phpdoc above unknown code in not optimal.

We can drop the phpdoc elements from the license easily. It will be also shorten then.

Can we agree that this is fine, dear @PierreRambaud , with you? I will then change https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Command/UpdateLicensesCommand.php .

Also, please reopen this PR, so I can adjust it. I prefer that over a new PR, as it is better to keep PR count to minimal on both sides for the same thing. Thanks.

**Pull request closed without merging**
