### PR TITLE
Translate missing menu strings into Italian

### PR DESCRIPTION
**Pull request by ginodev**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Translate missing menu strings into Italian. <br/> configuration, install-dev/langs/it/data/. |
| Type? | improvement |
| Category? | IN |
| BC breaks? | no |
| Deprecations? | no |

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @ginodev 
Can you update your description and commit name according PrestaShop's sandards please ? 

* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

**Comment by ginodev** [comment]
Sorry! Yes

**Comment by maximebiloe** [comment]
Hello @ginodev,

I see you updated the PR description, but you need to amend your commit name to something like: `BO: Translate missing menu strings into Italian` and also fille the table.

Regards

**Comment by AlexEven** [comment]
Thank you @ginodev!

**Comment by ginodev** [comment]
Hello @maximebiloe

I hope is now correct 

Thanks!

**Comment by maximebiloe** [comment]
It okay for the table but you didn't change your commit message.

Here is how to do it: open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by txmodxoops** [comment]
okay, I've used git shell, and the next step?

thanks

**Comment by ginodev** [comment]
okay, I've used git shell, and the next step?

thanks

**Comment by maximebiloe** [comment]
It's still not ok and even your new commit messages are not following the guidelines.

Please, take a look at our [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message) for your next contributions. Otherwise, we'll have to reject your PR.

Regards.

**Pull request merged**
