### PR TITLE
Fix Cannot use object of type ParameterBag as array

### LINKED ISSUE #15815: Cannot use object of type ParameterBag as array
I get exception when saving a product: Cannot use object of type ParameterBag as array.
```
[Tue Oct 01 14:45:05.873957 2019] [php7:error] [pid 15296] [client 172.19.0.2:47756] script '/var/www/html/admin/themes/new-theme/public/index.php' not found or unable to stat, referer: https://myshop.com/admin/index.php/sell/catalog/products/9018?_token=Tl8ItvVRfaL46AdjUjhk5F52XFRuJjsQPfPQPS7X9FY
[Tue Oct 01 14:45:15.704399 2019] [php7:error] [pid 19] [client 172.19.0.2:47768] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Cannot use object of type Symfony\\Component\\HttpFoundation\\ParameterBag as array in /var/www/html/src/Adapter/Security/Admin.php:91
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\\PrestaShop\\Adapter\\Security\\Admin->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#3 /var/www/h in /var/www/html/src/Adapter/Security/Admin.php on line 91, referer: https://myshop.com/admin/index.php/sell/catalog/products/9018?_token=Tl8ItvVRfaL46AdjUjhk5F52XFRuJjsQPfPQPS7X9FY
```

This was caused by a module trying to call a function that did not exist by mistake in the name. It was quite difficult for me to find the problem since the error log did not show anything about this.

**We can see that [$attributes prop of class Request](https://github.com/symfony/http-foundation/blob/1b189258972362a0c711e819e46c2a2b72153cc9/Request.php#L74) is of type ParameterBag, and [ParameterBag (latest and previous versions)](https://github.com/symfony/http-foundation/blob/master/ParameterBag.php) does not implement [arrayaccess](https://www.php.net/manual/es/class.arrayaccess.php)**

PR: https://github.com/PrestaShop/PrestaShop/pull/15805

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.1.32

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | I got an exception when saving a product: Cannot use object of type ParameterBag as array and I have fixed it using ParameterBag "has" method.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15815
| How to test?  | if it exists, Run this file unit test.

```
[Tue Oct 01 14:45:05.873957 2019] [php7:error] [pid 15296] [client 172.19.0.2:47756] script '/var/www/html/admin/themes/new-theme/public/index.php' not found or unable to stat, referer: https://myshop.com/admin/index.php/sell/catalog/products/9018?_token=Tl8ItvVRfaL46AdjUjhk5F52XFRuJjsQPfPQPS7X9FY
[Tue Oct 01 14:45:15.704399 2019] [php7:error] [pid 19] [client 172.19.0.2:47768] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Cannot use object of type Symfony\\Component\\HttpFoundation\\ParameterBag as array in /var/www/html/src/Adapter/Security/Admin.php:91
Stack trace:
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): PrestaShop\\PrestaShop\\Adapter\\Security\\Admin->onKernelRequest(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent), 'kernel.request', Object(Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(44): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('kernel.request', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent))
#3 /var/www/h in /var/www/html/src/Adapter/Security/Admin.php on line 91, referer: https://myshop.com/admin/index.php/sell/catalog/products/9018?_token=Tl8ItvVRfaL46AdjUjhk5F52XFRuJjsQPfPQPS7X9FY
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15805)

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
Hi @davidglezz, thank you for your contribution !

Could you please create an issue explaining what you are fixing, and reference the issue in this PR?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
The fix is logic. We just need to understand how it can happened :sweat_smile:

**Comment by sarahdib** [comment]
Hello @davidglezz 

Can you provide us the steps to reproduce the issue and check that the PR is ok. 

Thank you for your contribution

**Comment by davidglezz** [comment]
I think it is difficult to reproduce. And I'm sorry, I'm not going to try.
I simply saw an exception with a logical and well-documented error. I think this problem does not require reproduction, the code itself proves it.

I will tell you what I did and my conclusions:

I modified a module that called a function that did not exist because the name was misspelled.

This function was called from the "updateProduct" or similar hook of the module.

The exception occurred when I save a product, this process is done through ajax. The server returned error 500 and a blank page (regardless of the status of the debug option)

It took me a long time to find the problem because  I didn't saw anything in the php error log about calling a function that didn't exist. Only the trace shown at the beginning of the issue/pr.

Being totally inexperienced, I think the exception handler produced an exception that was the only one it showed.

After applying this fix, the exception no longer was throw.

Finally, this would be another issue in my opinion, I never understood why this error appeared `... var/www/html/admin/themes/new-theme/public/index.php' not found or unable to stat.` . Are you trying to open index.php somewhere in prestashop? I solved it by creating index.php.

**Comment by marionf** [comment]
@PierreRambaud @davidglezz 
Do you see any non-regressions tests to be done by the QA ?
What could it break ?
Otherwise if there is nothing functional to test, we can go without QA

**Comment by PierreRambaud** [comment]
I don't see any scenario to test this PR.
ping @matks If you have an idea, please! Otherwise, let's merge it as technical PR

**Comment by matks** [comment]
> ping @matks If you have an idea, please! Otherwise, let's merge it as technical PR

Let's do that

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @davidglezz

**Pull request merged**
