### PR TITLE
Fix RTL glitches

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | This PR fixes two glitches in RTL languages. See below for more.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Install an RTL language or set an existing one to RTL. If you already have one, make sure to delete this file beforehand: `admin-dev/themes/new-theme/public/theme_rtl.css`. Go to a migrated page, eg. Product Catalog.

Fixed issues:

1. The PrestaShop logo is badly aligned.

	Before:
	
	screenshot 2019-01-17 at 16 14 17
	
	After:
	
	screenshot 2019-01-17 at 16 17 06
	
2. Material checkboxes appear rotated when checked

	Before:
	
	screenshot 2019-01-17 at 16 14 24
	
	After:
	
	screenshot 2019-01-17 at 16 17 24

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12196)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by mbadrani** [comment]
@eternoendless if you make installation in RTL (Persian for my case) on the first step of shop installation: the "/theme_rtl.css" file exists and you still have some glitches

**Comment by mbadrani** [comment]
@eternoendless does your PR includes the very first installation on RTL also?

**Comment by ntiepresta** [comment]
Hello, 
After tested this Pr with installation language RTL (Persian for example). The pop-up user profile should displayed correctly. 
persan
Best regards,

**Comment by mbadrani** [comment]
Hi @khouloudbelguith have you seen an issue like this raised before?

**Comment by khouloudbelguith** [comment]
HI @mbadrani,

Yes, it is reported in this ticket: https://github.com/PrestaShop/PrestaShop/issues/12138
Thanks!

**Comment by mbadrani** [comment]
Great! thanks @khouloudbelguith

**Comment by mbadrani** [comment]
All good @eternoendless next PR will resolve: #12138

**Comment by eternoendless** [comment]
Thanks guys

**Pull request merged**
