### PR TITLE
[-] FO : Hide H1 if page has no title

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | no |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | check if front page has empty H1 |

### CODE REVIEW

**Comment by inetbiz** [comment]
I'm curious why the index page would not have an H1 element?

**Comment by fojtcz** [comment]
Front page already have six H1 elements (i know this is not good from SEO point of view). This PR is mainly about hiding a title when is not present.

**Comment by kpodemski** [comment]
This is ok for SEO as long as h1 are in separated sections

**Comment by inetbiz** [comment]
I am against this PR. Do 90 days case study in SEMrush and prove your case. But, a header container MUST have an H1 element and that should not be 'hidden'.

**Comment by fojtcz** [comment]
@inetbiz  can you share link to the study?

headings should not be empty, there is the screenshot from https://validator.w3.org/
screenshot-validator-h1

**Comment by julienbourdeau** [comment]
@fojtcz Thank you ! Great idea, I'm sure we can find many other piece of code where this can be used.

**Comment by Shudrum** [comment]
I like it!

And, removing an empty h1 is clearly the better solution.

Thank you!

**Comment by fojtcz** [comment]
I'm happy to help :smile:

**Comment by inetbiz** [comment]
@fojtcz https://www.w3.org/TR/html5/sections.html#the-header-element

**Pull request merged**
