### PR TITLE
Clean productcontroller initcontent

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | See below. This is another part of https://github.com/PrestaShop/PrestaShop/pull/36684 extracted out. It completely cleans `ProductController::initContent` out of any price calculations, towards cleaner future.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | yes - but only one unused variable.
| Deprecations?     | no
| How to test?      | Auto test, see if packs work normally.
| UI Tests          | 🟢 https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11990807342
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### Changes
- `$this->transformDescriptionWithImg` moved to `getTemplateVarProduct`, so it's now called also for ajax calls. It belongs there better and maybe could fix an issue nobody noticed.
- `Pack::isPack($this->product->id) ? Pack::getItemTable($this->product->id, $this->context->language->id, true) : [];` is now not needed, we can fetch the pack products from our presented product, no need to call it again. That's why I moved the product code part few blocks to the top.
- `'noPackPrice' => $product_for_template['nopackprice_to_display'],` is now assigned in the lazy array.
- `'displayPackPrice' => !empty($product_for_template['pack']) && $product_for_template['price_amount'] < $product_for_template['nopackprice'],` is now using data we already have from lazy array, no need to call anything again.
- `$product_full['rounded_display_price']` moved to lazy array.

### Performance
- It can bring some performance benefit, because I saved
  - One `getPrice` call,
  - One `getPriceWithoutReduct` call
  - One `Pack::isPack` call
  - One `Pack::getItemTable` call
  - One `Pack::noPackPrice` call.
- It doesn't bring any performance regression for `nopackprice`, even if somebody dumps the whole lazy array, because we assigned it in `Product::getProductProperties` all the time anyway.

### BC breaks
- Removed unused template variable `productPriceWithoutReduction`

### CODE REVIEW

**Review by ShaiMagal — APPROVED** [review]

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `BC breaks` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#bc-breaks))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Hlavtox** [comment]
https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11990807342

**Comment by Hlavtox** [comment]
@florine2623 @kpodemski Tests green!

**Comment by marsaldev** [comment]
Don't forget to document the BC break please

**Review by marsaldev — APPROVED** [review]

**Comment by Hlavtox** [comment]
Hello @PrestaShop/qa-automation, what do you think about this PR, can I merge it? :-)

**Comment by Progi1984** [comment]
> Hello @PrestaShop/qa-automation, what do you think about this PR, can I merge it? :-)

Not about UI Tests, I let @PrestaShop/tech-council decide

**Comment by Hlavtox** [comment]
@Progi1984 There is nothing to decide, it has been accepted. I want for QA only. :-)

**Comment by Progi1984** [comment]
So ping @PrestaShop/qa-functional team ;)

**Comment by Hlavtox** [comment]
@Progi1984 Yes! Good catch, sorry for ping :D

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Checked the following for pack type of product :

- CRUD Pack
- Change type of product
- Checked Stock levels after orders
- Created a pack without any product, I have this error : https://github.com/PrestaShop/PrestaShop/issues/36907

LGTM ✅ 
Thanks!

**Pull request merged**
