### PR TITLE
Added new hook 'actionClearCache'

### PR DESCRIPTION
**Pull request by jherry**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Add a hook to be called when cache is cleared (in Performances page) |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | no |
| How to test? | create a module hooked to this new hook :-/ |

### CODE REVIEW

**Comment by xBorderie** [comment]
It seems your branch was not synchronized with 'develop', could you rebase it? Thank you!

**Comment by julienbourdeau** [comment]
It would be nice to have a hook here indeed, although it need a more specific name. So far this folder was only used for assets with CCC. Maybe something like `actionClearThemeAssetsCacheAfter` or `actionClearCccCacheAfter`.

**Comment by jherry** [comment]
Is the build stable? Why is it always failing with this PR?

**Comment by julienbourdeau** [comment]
This method isn't used anymore (CCC has been reworked) but I agree we should have this kind of hooks. It should be added to:

* Tools::clearCache()
* Tools::clearCompile()
* Tools::clearSf2Cache()

**Comment by antoin-m** [comment]
Hey @jherry, thank you for your contribution.

I cherry-picked your commit here : https://github.com/PrestaShop/PrestaShop/pull/7442

**Pull request closed without merging**
