### PR TITLE
Fix inactive request in HookEvent

### PR DESCRIPTION
**Pull request by mwienk**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Fix inactive scope for request in HookEvent
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | <p>http://forge.prestashop.com/browse/BOOM-1992<br/>http://forge.prestashop.com/browse/BOOM-2579</p>
| How to test?  | Create BO order with code.

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @mwienk for your contribution

**Comment by vincentbz** [comment]
Many thanks for that PR @mwienk  ! :)

**Comment by raul-lucian** [comment]
Hello,

Can you please tell me how can i see the files/customisations made in order ti fix this bug:
- #7665: Fix inactive request in HookEvent
Thank you!

**Comment by Quetzacoalt91** [comment]
If you wznt to see the changes applied, please go on the "Files changes" tab: https://github.com/PrestaShop/PrestaShop/pull/7665/files

**Comment by raul-lucian** [comment]
Thank you so much Quetzacoalt91.
You answer helped me fix the bug on my 1.7.0.5 shop!

**Pull request merged**
