### PR TITLE
Fix issue where multishop context ALL and Group only displayed products from one shop context.

### LINKED ISSUE #9613: [BOOM-5806] "All shops" view not showing 2nd store products in Multistore - Product Page
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5806).

- _**Reporter:**_ natural
- _**Created at:**_ Thu, 21 Jun 2018 10:46:42 +0200

### Describe the bug

I have a multistore with two stores, with products in two shops.
When i select "All shops" view, i can only see products of "B2C" (Default store), products of "B2B" are hidden.
The same to specific prices, in "B2C" products the specific prices are visible, but in "B2B" products i can't see specific prices, however there are because if i go to "All shops" view i can see "B2B" products specific prices.

I think this problems are related.
I have a clean installation of Prestashop 1.7.3
        
### Steps to reproduce
1. BO>Catalog>Products
2. Create products in the default shop
3. Configure multistore
4. Create new shop
3. Create products in the new shop
4. Select The default shop and see the products that are displayed in the list ==> OK (The products of the default shop are correctly created)
5. Select The new shop and see the products that are displayed in the list ==> OK (The products of the new shop are correctly created)
6. Select All shops and see the products that are displayed in the list ==> NOK (Only the products of the default shop are displayed)

**Screenshots**
 https://www.awesomescreenshot.com/video/5975855?key=209fcfb4479ff833291727dbd93b0af3

### Additional infos:

- PS version: 1.7.3.3 & 1.7.4.0 & 1.7.6.0
- PHP version: 7.1

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix issue where multishop context ALL and group still only displays product from one shop context.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9613.
| Related PRs       | 
| How to test?      | Follow instructions in PR.
| Possible impacts? |

### CODE REVIEW

**Comment by kpodemski** [comment]
Thanks for your work Daniel @Prestaworks 

@PrestaShop/prestashop-maintainers 

As we are still not sure if we will enable a new product page, I think we should consider accepting fixes for the legacy page.

**Comment by Prestaworks** [comment]
> Thanks for your work Daniel @Prestaworks
> 
> @PrestaShop/prestashop-maintainers
> 
> As we are still not sure if we will enable a new product page, I think we should consider accepting fixes for the legacy page.

well, if everything is ok with the PR, I can look at adding the same fixes for the new product page also.

**Comment by kpodemski** [comment]
@Prestaworks new product page might work a bit different, actually will work a bit different with multistore

you might want to test the beta and enable experimental page for multistore to see how it works

**Comment by Prestaworks** [comment]
> @Prestaworks new product page might work a bit different, actually will work a bit different with multistore
> 
> you might want to test the beta and enable experimental page for multistore to see how it works

same issue exist on the experimental page in the PS8.0.0 version I have set up, I think it's a little bit outdated however, so I will test with the beta later on.

**Comment by matks** [comment]
> Thanks for your work Daniel @Prestaworks
> 
> @PrestaShop/prestashop-maintainers
> 
> As we are still not sure if we will enable a new product page, I think we should consider accepting fixes for the legacy page.

@kpodemski Yes for me but we need QA approval too as it's more work for them

ping @PrestaShop/qa-functional

**Comment by Robin-Fischer-PS** [comment]
Hi @Prestaworks @kpodemski @matks !

Sorry for the late answer : We should indeed accept fixes like this for the legacy page, especially if it happens too on the experimental page :)

**Review by kpodemski — APPROVED** [review]

**Comment by Prestaworks** [comment]
I close the pull request, this was fixed in PS8

**Pull request closed without merging**
