### PR TITLE
Make grid.js more extendable

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR aims to make grid.js extendable using extensions.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Not yet.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9342)

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9342)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by eternoendless** [comment]
Codacy is complaining about some linting issues though

**Comment by sarjon** [comment]
@eternoendless fixed

**Review by eternoendless — APPROVED** [review]
> Reviewed 16 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9342)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by sarjon** [comment]
@PierreRambaud double review and merge? ^^

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@sarjon I let @eternoendless merge, because he's the master here \o/

**Pull request merged**
