### PR TITLE
BO: Harmonization of wording configuration.xml

### PR DESCRIPTION
**Pull request by Nobodaddy**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Harmonization of wording with current translation
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @Nobodaddy,
Why do you remove the `#` ?!

**Comment by Nobodaddy** [comment]
lol, because this is Franglais!
Even in the USA the hash is only used in methematical contexts. In business it's *no.* or *No*, never #. And in German nobody would understand it.

**Comment by AlexEven** [comment]
Hello Rainer, 
Why "RET" for returns? - I see it's either "Warenrücksendungen" or "Rücksendung" in Crowdin.
Thank you!

**Comment by Nobodaddy** [comment]
Hello Alex,
RET is the abbreviation for *Retoure*.

**Comment by xBorderie** [comment]
As far as I know, [# _is_ mostly used in the US](https://en.wikipedia.org/wiki/Number_sign#Usage_in_North_America) ("#1 country in the world!"), whereas [French & UK English use n° (or, as you write, No.)](https://en.wikipedia.org/wiki/Numero_sign#English).

We'd have to check if indeed No. should be used in business context, but I personally have received a good number of US-originated invoices and orders with #'s, so I'm skeptical.

**Comment by aleeks** [comment]
hello @Nobodaddy,
I let you with @AlexEven & @xBorderie for the wording detail :stuck_out_tongue_winking_eye:
When you are all ok, can you rebase your branch please? (and rename the commit with BO: ...)
We had a problem with tests when you make this PR.

**Comment by mickaelandrieu** [comment]
Hi @Nobodaddy,

you also need to reword your commit label. I don't understand why you still continue to add an extra space between the category and the colon when @prestonBot have notified you at least 10 times: is the message from @prestonBot useless ? Can you help us to help you ?

Mickaël

**Comment by xBorderie** [comment]
Indeed, didn't know "Retoure": https://de.wikipedia.org/wiki/Retoure
Does it mean "Warenrücksendungen" or "Rücksendung" should be replaces, @Nobodaddy ?

**Comment by Nobodaddy** [comment]
@xBorderie 
Depends on the context. In general you should always prefer *"Warenrücksendung"*. But the slip is called **Rücksendeschein** or **Retourenschein**. Therefor the abbreviation *RET*. :)

**Comment by mickaelandrieu** [comment]
@Nobodaddy oh, I guess you have a misunderstanding of what we ask you to do, regarding our commit conventions.

capture

From "BO : Harmonization of wording configuration.xml" to "BO: Harmonization of wording configuration.xml"

basically, this is the commands you need to do:

```bash
git checkout patch-75
git commit --amend # a window will open with the commit label on top
# edit the label save
git push -f origin patch-75
```

**Comment by Nobodaddy** [comment]
Basically ... I'm familiar with unix commands, but practically they might be not very helpful in my MS windows environment. :rolleyes:

**Comment by mickaelandrieu** [comment]
@Nobodaddy I can assure you that theses ``git`` commands are available in Windows. The easy way is to install the [GitHub desktop client](https://desktop.github.com/) that provide the git utility command line.

I use Windows every mondays, it's a very reliable environment for git.

Second option, install ms-git :)

**Comment by Nobodaddy** [comment]
Thank you, I'll give it a try.

**Comment by maximebiloe** [comment]
Hello @Nobodaddy,

The XML files will be removed in this PR https://github.com/PrestaShop/PrestaShop/pull/7363 and translations will be editable on Crowdin.
So, I close this PR.

Regards

**Pull request closed without merging**
