### PR TITLE
Add docker-compose.override.yml to ignored files

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | This allows docker-compose override on local development without having to ignore this file on every commit.
| Type?             | improvement
| Category?         | TE 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | None
| Possible impacts? | None

### CODE REVIEW

**Review by matks — APPROVED** [review]
Good idea 👍

**Review by matthieu-rolland — APPROVED** [review]
thanks 👍

**Review by PululuK — APPROVED** [review]
Yeah !

**Comment by matks** [comment]
Thank you @FabienPapet

**Pull request merged**
