### PR TITLE
Product Page - Shipping: delivery times

### PR DESCRIPTION
**Pull request by kompilorb**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Product Page - Shipping: delivery times
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/FF-96
| How to test?  | Use new feature for administrate shipping by product. See result on Front Office, on the product.

- [x] Port on StarterTheme: https://github.com/PrestaShop/StarterTheme/pull/207

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8419)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[admin-dev/themes/new-theme/scss/pages/_product_page.scss, line 1000 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd38PtT7aBLjavdER2:-Kwd38PuciVmoZ9vOFnI:b-fd72wm) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/admin-dev/themes/new-theme/scss/pages/_product_page.scss#L1000)):*
> ```SCSS
>     }
>   }
> }
> ```

Missing a single blank line at the end of file

---

*[classes/Product.php, line 259 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd3pAWYzwTr48kvUZb:-Kwd3pAWYzwTr48kvUZc:b-fhk143) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/classes/Product.php#L259)):*
> ```PHP
>     public $additional_delivery_times = 1;
> 
>     /** @var string delivery in-stock information */
> ```

Please be more verbose about this property.
You can use the multiline docblock for this :
```php
/**
  * Delivery in-stock information (short definition)
  * 
  * Regular delivery time (for in stock products) (longer description to explain better)
  * 
  * @var string
  * /
```

---

*[classes/Product.php, line 263 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd4a9d6IJ56kfN0h2J:-Kwd4a9d6IJ56kfN0h2K:b-nld5p4) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/classes/Product.php#L263)):*
> ```PHP
> 
>     /** @var string delivery out-stock information */
>     public $delivery_out_stock;
> ```

Please be more verbose about this property.
You can use the multiline docblock for this :
```php
/**
  * Delivery out-stock information (short definition)
  * 
  * Delivery time for out of stock products (because more delays to replenish stock etc etc.)
  * Only for allowed orders. (longer description to explain better, multiple lines are possible)
  * 
  * @var string
  * /
```

---

*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 136 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd68OOSJOYiR22Zg7k:-Kwd68OOSJOYiR22Zg7l:b-2u38ph) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L136)):*
> ```PHP
>         ->add('delivery_out_stock', 'Symfony\Component\Form\Extension\Core\Type\TextType', array(
>             'required' => false,
>             'label' => $this->translator->trans('Delivery time of out-of-stock products with allowed orders:', [], 'Admin.Catalog.Feature'),
> ```

Try stay within the PSR-2 line length soft limit (120 characters).
There is no hard limit though, and you can keep it as-is if you consider it will be easier to read and understand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by LittleBigDev** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Some changes are requested. See the Reviewable comments above.

**Comment by kompilorb** [comment]
*[classes/Product.php, line 263 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd4a9d6IJ56kfN0h2J:-KweF-UcsBrPJgOqSJBQ:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/classes/Product.php#L263)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please be more verbose about this property.
You can use the multiline docblock for this :
```php
/**
  * Delivery out-stock information (short definition)
  * 
  * Delivery time for out of stock products (because more delays to replenish stock etc etc.)
  * Only for allowed orders. (longer description to explain better, multiple lines are possible)
  * 
  * @var string
  * /
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[classes/Product.php, line 259 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd3pAWYzwTr48kvUZb:-KweEz9YdMCet8vMoNZ3:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/classes/Product.php#L259)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Please be more verbose about this property.
You can use the multiline docblock for this :
```php
/**
  * Delivery in-stock information (short definition)
  * 
  * Regular delivery time (for in stock products) (longer description to explain better)
  * 
  * @var string
  * /
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[admin-dev/themes/new-theme/scss/pages/_product_page.scss, line 1000 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd38PtT7aBLjavdER2:-KweExgrbXDcakleWXH7:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/admin-dev/themes/new-theme/scss/pages/_product_page.scss#L1000)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Missing a single blank line at the end of file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by eternoendless** [comment]
Reviewed 4 of 9 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[classes/Product.php, line 259 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweAC-zrAGapTGsp2SX:-KweAC-zrAGapTGsp2SY:b2tbvu6) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/classes/Product.php#L259)):*
> ```PHP
>      * Type of delivery time
>      *
>      * Choose witch parameters use for give information delivery.
> ```

Small typo here: "witch" --> "which" (otherwise we'd be talking about a mean old lady who performs magic and travels on a broomstick :wink: )

---

*[classes/Product.php, line 262 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweAdWf3vrPY8F47tfi:-KweAdWf3vrPY8F47tfj:br0l3s2) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/classes/Product.php#L262)):*
> ```PHP
>      * 0 - none
>      * 1 - use default information
>      * 2 - use product information
> ```

Can we use constants for these values?

---

*[install-dev/upgrade/sql/1.7.3.0.sql, line 14 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KwdtN4faKCGIzrPpwxI:-KwdtN4faKCGIzrPpwxJ:b-60rbkl) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/install-dev/upgrade/sql/1.7.3.0.sql#L14)):*
> AFTER `delivery_times`

There's s a typo here, should be `additional_delivery_times` instead

---

*[install-dev/upgrade/sql/1.7.3.0.sql, line 15 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweDa-gzF3tRVffdaCP:-KweDa-gzF3tRVffdaCQ:b5c2b2k) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/install-dev/upgrade/sql/1.7.3.0.sql#L15)):*
> ```SQLPL
> ALTER TABLE `PREFIX_product` ADD `additional_delivery_times` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `out_of_stock`;
> ALTER TABLE `PREFIX_product` ADD `delivery_in_stock` varchar(255) DEFAULT NULL AFTER `delivery_times`;
> ALTER TABLE `PREFIX_product` ADD `delivery_out_stock` varchar(255) DEFAULT NULL AFTER `delivery_in_stock`;
> ```

FYI, you could merge your `ALTER`s:

```sql
ALTER TABLE `PREFIX_product`
    ADD `additional_delivery_times` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `out_of_stock`,
    ADD `delivery_in_stock` varchar(255) DEFAULT NULL AFTER `additional_delivery_times`
    ADD `delivery_out_stock` varchar(255) DEFAULT NULL AFTER `delivery_in_stock`
```

*Note that the first column to add must last 

---

*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 123 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KwdtcuFPVaGFYmd0S68:-KwdtcuFPVaGFYmd0S69:bk16zwb) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L123)):*
> ```PHP
>         ->add('additional_delivery_times', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', array(
>             'choices' =>  array(
>                 '0' => $this->translator->trans('None', [], 'Admin.Catalog.Feature'),
> ```

We need to use the long array syntax until 1.7.4, please change it everywhere :slightly_smiling_face: 

---

*[src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe7TSpmIcYItVmijac:-Kwe7TSqiL5oMR8_xkCa:blsghtf) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig#L87)):*
> ```Twig
>                 {{ form_widget(child) }}
>                 <span class="small font-secondary">
>                   {{ "[1][2]edit[/1]"|trans({}, 'Admin.Catalog.Help')|replace({'[1]': '<a href="' ~ getAdminLink("AdminPPreferences") ~'" onclick="" class="btn sensitive px-0">', '[/1]': '</a>', '[2]': '<i class="material-icons">open_in_new</i>'})|raw }}
> ```

No need for `onclick=""`

---

*[src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe8sJSDkzhUgAcaXY_:-Kwe8sJSDkzhUgAcaXYa:bjmioyv) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig#L87)):*
> ```Twig
>                 {{ form_widget(child) }}
>                 <span class="small font-secondary">
>                   {{ "[1][2]edit[/1]"|trans({}, 'Admin.Catalog.Help')|replace({'[1]': '<a href="' ~ getAdminLink("AdminPPreferences") ~'" onclick="" class="btn sensitive px-0">', '[/1]': '</a>', '[2]': '<i class="material-icons">open_in_new</i>'})|raw }}
> ```

What does the `sensitive` class do? :thinking: 

---

*[src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe9R5ascDRKHF7y1jF:-Kwe9R5ascDRKHF7y1jG:b8ih0ez) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig#L87)):*
> ```Twig
>                 {{ form_widget(child) }}
>                 <span class="small font-secondary">
>                   {{ "[1][2]edit[/1]"|trans({}, 'Admin.Catalog.Help')|replace({'[1]': '<a href="' ~ getAdminLink("AdminPPreferences") ~'" onclick="" class="btn sensitive px-0">', '[/1]': '</a>', '[2]': '<i class="material-icons">open_in_new</i>'})|raw }}
> ```

Wouldn't it be simpler to extract the `<a>` and the `<i>` from the translation? I don't see any need to keep it as part of the translation itself.

```twig
<a href="{{ getAdminLink("AdminPPreferences") }}" class="btn sensitive px-0"><i class="material-icons">open_in_new</i>
{{ "edit"|trans({}, 'Admin.Catalog.Help') }}</a>
```

---

*[themes/classic/templates/catalog/_partials/product-prices.tpl, line 103 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweCd5A4HAaZtY8Ck_r:-KweCd5A4HAaZtY8Ck_s:b-x0r60r) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/themes/classic/templates/catalog/_partials/product-prices.tpl#L103)):*
> ```Smarty
>         {/if}
>       {/if}
>       {if $product.additional_delivery_times == 2}
> ```

Shouldn't this be `{elseif ...}`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[install-dev/upgrade/sql/1.7.3.0.sql, line 15 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweDa-gzF3tRVffdaCP:-KweHIVuSTzB5WdnnnGH:b-2j2wiw) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/install-dev/upgrade/sql/1.7.3.0.sql#L15)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

FYI, you could merge your `ALTER`s:

```sql
ALTER TABLE `PREFIX_product`
    ADD `additional_delivery_times` tinyint(1) unsigned NOT NULL DEFAULT '1' AFTER `out_of_stock`,
    ADD `delivery_in_stock` varchar(255) DEFAULT NULL AFTER `additional_delivery_times`
    ADD `delivery_out_stock` varchar(255) DEFAULT NULL AFTER `delivery_in_stock`
```

*Note that the first column to add must last 
</blockquote></details>

I know but i have take the old structure view in sql file (not merge the alter)  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 136 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwd68OOSJOYiR22Zg7k:-KweF19A83HLfA991pOp:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/00340a04a002381d0805e88278081608b8ea44b8/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L136)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Try stay within the PSR-2 line length soft limit (120 characters).
There is no hard limit though, and you can keep it as-is if you consider it will be easier to read and understand.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe8sJSDkzhUgAcaXY_:-KweIYa-RbtWDJQh32WD:b-usq2sg) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig#L87)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

What does the `sensitive` class do? :thinking: 
</blockquote></details>

I take the same class css from the same button. I'm not sure what he does ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[classes/Product.php, line 262 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweAdWf3vrPY8F47tfi:-KweJZpCMBnFm_6rnKU6:bxo8ht3) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/classes/Product.php#L262)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Can we use constants for these values?
</blockquote></details>

Not at this moment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[themes/classic/templates/catalog/_partials/product-prices.tpl, line 103 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweCd5A4HAaZtY8Ck_r:-KwePWqSw3sbk7H9ryxD:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/themes/classic/templates/catalog/_partials/product-prices.tpl#L103)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Shouldn't this be `{elseif ...}`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[classes/Product.php, line 259 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweAC-zrAGapTGsp2SX:-KweVPE9QXVT5EI2V_kE:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/classes/Product.php#L259)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Small typo here: "witch" --> "which" (otherwise we'd be talking about a mean old lady who performs magic and travels on a broomstick :wink: )
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[install-dev/upgrade/sql/1.7.3.0.sql, line 14 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KwdtN4faKCGIzrPpwxI:-KweJeoIT2G5KPyQ4hia:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/install-dev/upgrade/sql/1.7.3.0.sql#L14)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

> AFTER `delivery_times`

There's s a typo here, should be `additional_delivery_times` instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 123 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KwdtcuFPVaGFYmd0S68:-KweI6H2Jc8nO5rhMyEt:b-c8pt5w) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L123)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

We need to use the long array syntax until 1.7.4, please change it everywhere :slightly_smiling_face: 
</blockquote></details>

Change in this file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe7TSpmIcYItVmijac:-KweIX0oTiIRVXhOvAYx:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig#L87)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

No need for `onclick=""`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig, line 87 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe9R5ascDRKHF7y1jF:-KweP6NT9n1P4VwUJCJv:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_shipping.html.twig#L87)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Wouldn't it be simpler to extract the `<a>` and the `<i>` from the translation? I don't see any need to keep it as part of the translation itself.

```twig
<a href="{{ getAdminLink("AdminPPreferences") }}" class="btn sensitive px-0"><i class="material-icons">open_in_new</i>
{{ "edit"|trans({}, 'Admin.Catalog.Help') }}</a>
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by LittleBigDev** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[classes/Product.php, line 262 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweAdWf3vrPY8F47tfi:-KweYwMc8k1PlSZKmodw:b8ckbvd) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/classes/Product.php#L262)):*
<details><summary><i>Previously, kompilorb wrote…</i></summary><blockquote>

Not at this moment
</blockquote></details>

Isn't it possible to create class constants ?

---

*[classes/Product.php, line 271 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweZDulL93VJAmxNM92:-KweZDulL93VJAmxNM93:b-k4wxyu) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/classes/Product.php#L271)):*
> ```PHP
>      * Delivery in-stock information
>      *
>      * Long description for delivery in-stock product information.
> ```

Are we really talking about a description ? It looks more like a time range for delivery. 

---

*[classes/Product.php, line 280 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweZWbcoRuCE0XblMnj:-KweZWbdEgfAOxMo1Bc6:b-k4wxyu) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/classes/Product.php#L280)):*
> ```PHP
>      * Delivery out-stock information
>      *
>      * Long description for delivery out-stock product information.
> ```

Are we really talking about a description ? It looks more like a time range for delivery. 

---

*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 137 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe_EdT38vzCKZWP6a0:-Kwe_EdT38vzCKZWP6a1:b9bt7wk) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L137)):*
> ```php
>             'label' =>
>                $this->translator->trans(
>```

Should be on the same line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-:-KweiRQ-BImqBI2Acgef:bnfp4nl)*

**Review by eternoendless — DISMISSED** [review]
Looks good to me!

**Comment by kompilorb** [comment]
*[classes/Product.php, line 271 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweZDulL93VJAmxNM92:-Kwej4YRomwXJokYLIQs:b-4qdx8m) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/classes/Product.php#L271)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Are we really talking about a description ? It looks more like a time range for delivery. 
</blockquote></details>

Yes it's a description, example is a time range yes, but customer can write any description about delivery information and not only a time range. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[classes/Product.php, line 280 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweZWbcoRuCE0XblMnj:-KwejNIOhB8-95AQKD6S:b-4qdx98) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/classes/Product.php#L280)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Are we really talking about a description ? It looks more like a time range for delivery. 
</blockquote></details>

Yes it's a description, example is a time range yes, but customer can write any description about delivery information and not only a time range.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 137 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe_EdT38vzCKZWP6a0:-KwejZvPcLdjjgZ_b4qQ:bqz8ds4) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L137)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

> ```php
>             'label' =>
>                $this->translator->trans(
>```

Should be on the same line
</blockquote></details>

Why on the same line ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php, line 137 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-Kwe_EdT38vzCKZWP6a0:-KweliVHT6NcgN1403Tu:b-7rl0jr) ([raw file](https://github.com/prestashop/prestashop/blob/ff3072bfa5b62a0ab92a9e5bdee04fba85a659ac/src/PrestaShopBundle/Form/Admin/Product/ProductShipping.php#L137)):*
<details><summary><i>Previously, kompilorb wrote…</i></summary><blockquote>

Why on the same line ? 
</blockquote></details>

done 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by kompilorb** [comment]
*[classes/Product.php, line 262 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-KweAdWf3vrPY8F47tfi:-KwemgCqXf0yXanaK03F:bqka9nj) ([raw file](https://github.com/prestashop/prestashop/blob/984d7f05889e31ded9a5d2e01056f00c5a38dc59/classes/Product.php#L262)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Isn't it possible to create class constants ?
</blockquote></details>

I don't say that's not possible. I say only "not at this moment" this value must be use in legacy, smarty, symfony and twig. And i must ask for know if we do or not. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Comment by LittleBigDev** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-:-Kwes3TdPAj3qxmJoGdk:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]

**Comment by kompilorb** [comment]
PR Starter Theme : 
https://github.com/PrestaShop/StarterTheme/pull/207

**Comment by eternoendless** [comment]
Reviewed 1 of 6 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-:-Kx82Ji4P5MUyLIUdg0S:bnfp4nl)*

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419)*

**Review by eternoendless — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @kompilorb 
Some little things to change:
capture du 2017-10-24 16-41-26

The translation of these fields doesn't work:
capture du 2017-10-24 16-44-41

**Comment by mickaelandrieu** [comment]
tests are broken for now, this need an extra work to make this mergeable :)

Good job

**Comment by mickaelandrieu** [comment]
@kompilorb ping me when tests are OK, I'll approve the pull request :+1:

**Comment by kompilorb** [comment]
@mickaelandrieu ping ! :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8419#-:-Kxi1k_UCd7tOrYwwG6m:bnfp4nl)*

**Comment by eternoendless** [comment]
Thank you @kompilorb

**Pull request merged**
