### PR TITLE
Add nofilter to displayed hook

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Content of the hook is escaped as now.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Hook a module to the hook and check what happend.

### CODE REVIEW

**Comment by antoin-m** [comment]
Hey @prestamodule 

This change has already been made here https://github.com/PrestaShop/PrestaShop/pull/6972 :)

**Comment by PrestaEdit** [comment]
:+1: 

Hope it will be merged soon, like in the 1.7.0.2 ... ;-)

**Comment by antoin-m** [comment]
@PrestaEdit I guess it's a bit late! 😛 

http://build.prestashop.com/news/prestashop-1702-maintenance-release/

**Comment by PrestaEdit** [comment]
My bad, wanna say the 1.7.0.3 as it's already too late for the 1.7.0.2 (and really don't know why this one and the another PR was not merged before :-/)

**Pull request closed without merging**
