### PR TITLE
[-] FO : Remove backslash from BR tag in formatted address

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions | Answers |
| --- | --- |
| Branch? | "develop" |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
It's not realy a bugfix... what is the gain of removing the slash ?

**Comment by kpodemski** [comment]
I guess none and this PR is because @julienbourdeau done it for the rest of the HTML in StarterTheme/Classic

**Comment by mickaelandrieu** [comment]
@kpodemski consistency is an argument I can understand :+1:

**Comment by maximebiloe** [comment]
Thank you all for contributing and reviewing

**Comment by Shudrum** [comment]
And it is more HTML5 compliant.

👍

**Pull request merged**
