### PR TITLE
Delete product

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Add delete product and delete product with bulk actions tests (Full tests)
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | See below

1. Run the script path=full/02_product/10_delete_product.js npm run specific-test -- --URL=BackOfficeURL

2. Run the script path=full/06_catalogbulkaction/catalogbulkaction.js npm run specific-test -- --URL=FrontOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8812)

### CODE REVIEW

**Review by fatmaBouchekoua — DISMISSED** [review]

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
It looks like we need a rebase here, and some `;` are missing.

**Comment by fouratachour** [comment]
Hello @Quetzacoalt91  
I have made the rebase and I have added the missing semicolon.
Thanks for your review.

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by marionf** [comment]
Hello @fouratachour 
The scenario "bulk action in catalog page" on testlink has been updated since this PR, so we need to update this test

**Comment by fouratachour** [comment]
@marionf OK

**Pull request merged**
