### PR TITLE
Move classes/ autoloader to composer

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Move classes/ autoloader to composer and make it independent on config constants.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | CI must 🟢 
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24864)

### CODE REVIEW

**Comment by matks** [comment]
Hello, this PR has been in draft state for a long time now. Following the guidelines I wrote [here](https://github.com/PrestaShop/PrestaShop/pull/23979#issuecomment-906376989) I close this PR. Thank you for submitting the contribution though.

**Comment by mvorisek** [comment]
@matks why? this PR was in draft state as it needs https://github.com/PrestaShop/PrestaShop/pull/28121

**Comment by FabienPapet** [comment]
Actually, we can't move all classes/* into composer, it is not doable right now (mainly because of the overriding system as you can override abstract core classes)

The Autoload will be moved into composer as a separated package and then loaded with composer, and there is also a PR to integrate that package into Prestashop.

I don't know why it was closed before, perhaps @matks will explain this, but I think we should keep it closed and continue the work into #29923 .

Thank you for understanding

**Comment by mvorisek** [comment]
> Actually, we can't move all classes/* into composer, it is not doable right now (mainly because of the overriding system as you can override abstract core classes)

I mean implicit register into composer autoloader, eg. `vendor/autoload.php` include should be enough to use legacy classes

**Pull request closed without merging**
