### PR TITLE
[-] FO : the session remains active in cache

### PR DESCRIPTION
**Pull request by dertin**
Reloading login the session remains active in cache. Problem with mylogout().

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR, this was introduced in Back office but personnaly I am not very keen on that for php files in front office. Did you set ExpiresDefault in your server mod_expire config ? We should maybe rather handle ExpiresDefault in the htacess ?

Regards

**Comment by dertin** [comment]
...
<ifModule mod_expires.c>
ExpiresActive On
ExpiresDefault "now plus 1 days"
</ifModule>
...
is located below the main directory prestashop.

this causes conflict with the mylogout ?

**Comment by gRoussac** [comment]
Hi,

I believe yes, PrestaShop actually does not set it when server optiosn are activated in BO Performances tab , and maybe we should ?

Regards

**Comment by dertin** [comment]
Yes, I am testing ...

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
Hey there!

This PR is fairly old and there hasn't been much activity on it. Closing, but please re-open it on the `develop` branch if the change is still relevant.

Thank you for your contribution!

**Pull request closed without merging**
