### PR TITLE
Fix: method accept now both types array|bool, avoiding fatal error

### PR DESCRIPTION
**Pull request by nlsnmr**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x / 8.0.x
| Description?      | Title: Allow boolean type in addProductCustomizationData parameter<br>This pull request aims to address a compatibility issue with certain scenarios or third-party modules where the addProductCustomizationData() function in the ProductControllerCore class might receive a boolean value instead of an array.<br>Changes:<br>Updated the addProductCustomizationData() method in ProductControllerCore to accept both array and boolean types as its parameter.<br>This change ensures that the function can handle both expected and unexpected data types gracefully, improving overall compatibility and reducing the likelihood of encountering fatal errors. Future improvements could include additional error handling or logging to better handle unexpected data types and help developers identify the root cause of the issue.<br>Please review the changes and let me know if you have any feedback or concerns.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Test a variety of product pages in the front office, especially those with customization options, to ensure that the product data is displayed correctly and that customizations can be added and modified as expected.<br>2. Test the changes with third-party modules that might interact with the ProductControllerCore class or the product data on the front office product pages. Check for any conflicts or issues that arise due to the updated function signature.<br>3. If possible, test scenarios where the addProductCustomizationData function might receive a boolean value instead of an array, and verify that no fatal errors are encountered in these cases.<br>4. Check for any errors, warnings, or notices in the PHP error log and the PrestaShop logs to ensure that the changes do not introduce new issues or unexpected side effects.<br><br>By thoroughly testing the changes in various scenarios and configurations, we should ensure that the updated function signature provides the expected benefits without introducing new issues or negatively affecting existing functionality.
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | N/A

### CODE REVIEW

**Comment by Hlavtox** [comment]
I don't think it makes any sense to call this function with false. The theoretical errors should be handled before calling this I think. 🤔

**Comment by nlsnmr** [comment]
> I don't think it makes any sense to call this function with false. The theoretical errors should be handled before calling this I think. 🤔

fine for me, just take in consideration that the method getProductProperties, can return a boolean:

image

**Comment by Hlavtox** [comment]
@nlsnmr Yes, it can, but that's not our problem to deal with.
What sense does it make to `addProductCustomizationData` on `false`?

ProductController should never get into this situation because the existence of the product is checked during initialization of the controller by `if (!Validate::isLoadedObject($this->product)) {` and it immediately halts the controller and throws 404.

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Blocking for reasons above

**Comment by zuk3975** [comment]
I agree with @Hlavtox.
Furthermore the native union types that you used are not supported for php < 8.0

**Comment by kpodemski** [comment]
Thanks for contributing @nlsnmr but I agree with other guys :)

**Pull request closed without merging**
