### PR TITLE
Fix missing image on invoices

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.1
| Description?  | Logo on invoice was missing if SSL was activated in BO. Use URI instead of URL fix the issue.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/15088
| How to test?  | Enable SSL in BO. Then generate an invoice. Without this PR the logo is missing. With this PR the logo is showed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15089)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
LGTM

**Comment by matthieu-rolland** [comment]
Thank you for your contribution @MathiasReker !

**Comment by MathiasReker** [comment]
This is a regression. Should it have 1.7.6.1 milestone?

**Comment by marionf** [comment]
@MathiasReker 
Yes, could you rebase on 1.7.6.x branch ?

**Comment by MathiasReker** [comment]
I am fixing the rebase

**Comment by MathiasReker** [comment]
@matthieu-rolland I will look into that that issue.

**Comment by MathiasReker** [comment]
I messed something up with the rebase. I made a new PR: https://github.com/PrestaShop/PrestaShop/pull/15109/files

**Pull request closed without merging**
