### PR TITLE
[-] BO : fixed bug Unable to translate header

### PR DESCRIPTION
**Pull request by Eolia**

### CODE REVIEW

**Comment by Eolia** [comment]
+ a bonus :) https://www.prestashop.com/forums/topic/468694-transporteur-manquant-dans-facture-v161/

**Comment by tchauviere** [comment]
Hi @Eolia,

Thanks for your PR, it's seems there's a duplicate with this one 4051 (which I've closed).

Regards,

**Comment by gRoussac** [comment]
@tchauviere, please reopen, it is another file HTMLTemplateOrderSlip.php

Regards

**Comment by tchauviere** [comment]
@gRoussac,

Indeed, my bad ! PR reopened !

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution.

Best regards.

**Pull request merged**
