### PR TITLE
[*] Theme - Bootstrap update (3.3.4)

### PR DESCRIPTION
**Pull request by axometeam**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, Thank you for your PR,

But it change all button and input design, it's not compatible with uniform.

Best regards

**Comment by axometeam** [comment]
OK, so I will update uniform.

**Comment by kpodemski** [comment]
What about layer_cart? What is the point of adding border-radius here if design is square in entire default-bootstrap?

**Comment by jeromenadaud** [comment]
Hi, @kpodemski 

You have some panel and boxes with rounded border, but no buttons and input fields.

Best regards.

**Comment by redpik** [comment]
Hi Jérôme, have you planned to check this PR?

**Comment by jeromenadaud** [comment]
Hi,

rounded buttons are still present, il also break ui slider, please check.

Best regards

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
I am closing this PR because the `1.6` branch is no longer used, and PrestaShop 1.6 will now only receive bugfixes, not improvement such as this one.
If you want to recreate this PR for PrestaShop 1.7, please do it on the `develop` branch.
Thank you for your contribution!

**Pull request closed without merging**
