### PR TITLE
Added reference parameter to OrderDetailController

### PR DESCRIPTION
**Pull request by mcdado**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This enables to load the order detail page directly with an order `reference` rather then an order id. If both parameters are passed, `id_order` has precedence, which is good for backwards compatibility. |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | example.com/order-detail?id_order={id_order}<br>example.com/order-detail?reference={order_reference} |

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @mcdado, thank you, it's a good idea.
Just, can you put your "reference" logic in a condition ? Traditionally, we use id_order so, it's not necessarily to get and treat "reference"

```
$id_order = (int)Tools::getValue('id_order');
$id_order = $id_order && Validate::isUnsignedId($id_order) ? $id_order : false;

if (!$id_order) {
    $reference = Tools::getValue('reference');
    $reference = $reference && Validate::isReference($reference) ? $reference : false;
    
    if ($reference) {
        $order = Order::getByReference($reference)->getFirst();
        $id_order = $order ? $order->id : false;
    }
}

if (!$id_order) {
    $this->redirect_after = '404';
    $this->redirect();
} else {
    ...

```
or something like this ?

**Comment by mcdado** [comment]
I see what you mean… even though `$reference` is ignored unless `$id_order` is unset. Anyway, I see your argument and will make the correction.

**Comment by aleeks** [comment]
Thank you ! I think is the same on your other PR : https://github.com/PrestaShop/PrestaShop/pull/6379

**Comment by aleeks** [comment]
Hello @mcdado, I'm sorry again.., I was going to merge your PR, but commit's name does not comply the standard .. can you rename easily?

**Comment by mcdado** [comment]
Hi, I hope I used the right prefix… i'm not sure if a FrontController is under FrontOffice or Core… in case I got it wrong I can change it. Also, while I was at it I fixed up the syntax error. Same with #6379 .

**Comment by aleeks** [comment]
Hello, yes you have right, it's **CO**.
FO is when you make change in tpl file, or directly in the front office. One more change and it's all ok !

**Comment by mcdado** [comment]
Renamed commits. Ready to go! 😃

**Comment by aleeks** [comment]
Thank you ! :simple_smile:

**Pull request merged**
