### PR TITLE
Cancel previous build when it's possible

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Boost CI with a Cancel [Workflow Action](https://github.com/marketplace/actions/cancel-workflow-action) 
| Type?             | bug fix
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is green
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24997)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hello @PierreRambaud a nice feature!

According to doc https://github.com/styfle/cancel-workflow-action
maybe we need to use `workflow_run`

See `Advanced: Pull Requests from Forks`

**Comment by PierreRambaud** [comment]
> Hello @PierreRambaud a nice feature!
> 
> According to doc https://github.com/styfle/cancel-workflow-action
> maybe we need to use `workflow_run`
> 
> See `Advanced: Pull Requests from Forks`

My bad, I read that but forget to include it :sweat_smile:  Nice catch

**Review by matks — DISMISSED** [review]
Looks legit

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PierreRambaud

**Pull request merged**
