### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by staabm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Fix Typo
| Type?             | bug fix
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | n/a
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

Detected via phpstan https://github.com/phpstan/phpstan-src/pull/2041

```
Error: Call to sprintf contains 2 placeholders, 1 value given.
 ```

### CODE REVIEW

**Comment by kpodemski** [comment]
Thank you @staabm 

Fully agree with the Pull Request. The only thing remaining: even tho it's a simple fix, please fill in the provided table from the Pull Request table. You don't need to create an issue for this one, but the rest of the information is required.

**Comment by staabm** [comment]
sorry about that. hopefully this works now.

**Review by kpodemski — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @staabm ,

It is QA ✅ !

Thanks!

**Comment by nicosomb** [comment]
Thank you @staabm !

**Pull request merged**
