### PR TITLE
[-] BO : Fix admin add order page

### PR DESCRIPTION
**Pull request by Prestaspirit**
## Description
- The trigger "change" does not bind after the ajax loading the select field #payment_module_name
- Error display during the call to the method of the controller ajaxProcessDuplicateOrder AdminCarts
- Changing the ajaxProcessDuplicateOrder method returns errors

## Steps to Test this Fix

1. Go in the backoffice
2. Click on to add a order
3. Select a customer
4. Fill the cart with an existing order
5. No error message is returned if the filling is not possible
6. When payment method change the status id is not updated because the select field is filled in ajax when customer is selected
## Forge Ticket (optional)

none

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @Prestaspirit,

thanks for contribution, need to be checked by QA, then will be merged.

Mickaël

**Comment by vincentbz** [comment]
Hi,

It doesn't seem to work, the orders are not displayed anymore, see image below.

Thanks for your contribution :)

add order to customer

**Comment by Prestaspirit** [comment]
Bonjour,

Désolé je continue en Français parce que moi et la langue de Sheakespeer ça deux !

Le code fonctionne bien, soit vous avez une erreur javascript propre à votre environnement, soit la requêtes ajax n'est pas terminé, elle peut être extrémement longue selon le nombre de paniers et de commandes de votre client de test mais je vous confirme que mon code est bien fonctionnel et n'ajoute aucun bug ;-)

Merci

**Comment by mickaelandrieu** [comment]
I understand your point of view but we can't merge without QA agreement. 

Did you test your contribution against different web browsers for instance?

**Comment by Prestaspirit** [comment]
Hi,
Yes of course tested on Firefox, Chrome and IE11

If the tester does not say more about the mistake that he met little unfortunately I do not help :(

The party that orders load is not impacted by my changes, I know what to tell you more about this problem.

**Comment by vincentbz** [comment]
Hi @Prestaspirit ,

Have you tried to reproduce the bug you wanted to fix with this PR, on the latest version please ? 
I wanted to try again your PR but before I wanted to reproduce the bug, what I cannot do.

**Comment by aleeks** [comment]
Hello @Prestaspirit,
I'm closing this PR, QA said this PR doesn't fix the problem & we don't have more information.
It can be re-open if necessary.

Regards

**Pull request closed without merging**
