### PR TITLE
Fix Monitoring grids data for multishop

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When multiple shops exists, but context is single shop - most of migrated Monitoring lists where not considering the shop context id when getting data.
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | part of #10552
| How to test?  | Use `/admin-dev/index.php/sell/catalog/monitoring` to see migrated monitoring page. When multiple shops are available, select one of them and make sure that all monitoring grids are showing data just for that shop. When All shops are enabled, grids should contain data for default shop. :warning: Actions like edit/delete are not migrated within this PR, because it is highly coupled with product page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14991)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by sarahdib** [comment]
Hello @zuk3975 

- In migrated page the product appear  in the second shop but I created this one only for the first shop

image

image

---------------------------------------------------------------------------------------------------

- When I search by id there is no result if the id isn't the same. For example if I search 3, 23 need to be in the list 

image

image

---------------------------------------------------------------------------------------------------

- Delete and edit button not working but I think it's normal. Those action aren't migrated yet ?

**Comment by zuk3975** [comment]
Thanks @sarahdib,

- I've fixed the first issue with product shown in wrong shop.

- `When I search by id there is no result if the id isn't the same. For example if I search 3, 23 need to be in the list` - it is expected behavior, migrated lists filters id by exact value.

- `Delete and edit button not working but I think it's normal. Those action aren't migrated yet` - yes, not migrated, so it is normal :)

**Comment by sarahdib** [comment]
Thanks @zuk3975 I'm waiting for a review and I will test it :)

**Comment by zuk3975** [comment]
> Thanks @zuk3975 I'm waiting for a review and I will test it :)

@matks, could you check and also restart travis, please? :)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Here we go ! 😄

**Comment by matks** [comment]
PrettyCI is lost 🙄

**Comment by matks** [comment]
PrettyCI is now happy 😊thank you @mnapoli

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
