### PR TITLE
Translate aria-label in modal close button

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | aria-label="Close" to aria-label="{l s='Close' d='Shop.Theme.Global'}" 
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14437)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Nice catch!

**Comment by davidglezz** [comment]
I think the tests have failed because an error that is not related to the modifications:

`(#blockcart-modal) still not visible after 2500ms `

maybe it was an ajax timeout when adding a product to the cart

**Comment by matks** [comment]
Yes, it's a random CI issue (https://github.com/PrestaShop/PrestaShop/issues/14384)

**Comment by sarahdib** [comment]
Hello @davidglezz 

Thank you for this PR.

Can you provide me the tests steps ?

Thank you :)

**Comment by davidglezz** [comment]
I simply translate some labels.
Before the patch: the labels always "close" in English
After the patch: label in the correct language.

To test it use a screenreader or check the source code corresponding to the close button of involved modal-dialogs, for example, in "quick view" or "product added to cart popup".

**Comment by matks** [comment]
Thank you @davidglezz

**Pull request merged**
