### PR TITLE
Fixed :: Access to undeclared static property: Validate::$data for PHP7

### PR DESCRIPTION
**Pull request by pranid**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Fatal error: Uncaught Error: Access to undeclared static property: Validate::$data <br> fixed for PHP7 incompatibility |
| Type? | bug fix |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Try registering a costumer from the Front office |

Refer : http://stackoverflow.com/questions/35406163/presta-shop-errors-on-registration/39512556#39512556

Fixed :: Fatal error: Uncaught Error: Access to undeclared static property: Validate::$data

### CODE REVIEW

**Comment by pranid** [comment]
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Fatal error: Uncaught Error: Access to undeclared static property: Validate::$data <br> fixed for PHP7 incompatibility
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Try registering a costumer from the Front office



Refer : http://stackoverflow.com/questions/35406163/presta-shop-errors-on-registration/39512556#39512556

Fixed :: Fatal error: Uncaught Error: Access to undeclared static property: Validate::$data

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by mickaelandrieu** [comment]
@pranid this pull request is for `develop`, not for `1.6.1.x` branch. I flag it as "to be cherry picked".

Thank you

**Comment by pranid** [comment]
Hi @mickaelandrieu , I am new to this, Please let me know if I am doing it correct. 

Thank You

**Pull request merged**
