### PR TITLE
Error when adding product in cart or editing quantity

### LINKED ISSUE #9552: [BOOM-6127] Critical bug quantity issue
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-6127).

- _**Reporter:**_ Mreker
- _**Created at:**_ Mon, 30 Jul 2018 13:16:57 +0200

<p>watch the video.</p>

<p>You have to add a value > 1 to reproduce the error.</p>
        
* How to reproduce the issue ?

watch the video.
<br/>

<br/>
You have to add a value &gt; 1 to reproduce the error.

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |         - Do not update cart when cart product quantity is under 0<br/> - Prevent double event trigger on front (keyup and focusout) while pressing ret key<br/> - Fix webpack problem in dev / prod<br/> - Allow code coverage with phpunit
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixed https://github.com/PrestaShop/PrestaShop/issues/9552
| How to test?  | Follow ticket instruction. And in cart set 0 in input and press enter. Watch out with this PR, it change Cart.php, so we need many manual tests (front & back)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)

### CODE REVIEW

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: all files reviewed, 9 unresolved discussions (waiting on @PierreRambaud)

___
*[admin-dev/themes/default/webpack.config.js, line 77 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-033BrGNvC-Lblwf:-LJT-033BrGNvC-Lblwg:b-4bcv8i) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/admin-dev/themes/default/webpack.config.js#L77)):*
> ```JavaScript
>   },
>   plugins: [
>     new webpack.HotModuleReplacementPlugin(),
> ```

This should only be done in development (check webpack config for the new theme)
___
*[admin-dev/themes/default/webpack.config.js, line 83 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-3F70bM0mH2IL6_w:-LJT-3F70bM0mH2IL6_x:bo31epa) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/admin-dev/themes/default/webpack.config.js#L83)):*
> ```JavaScript
> 
> if (process.env.NODE_ENV === 'production') {
>   config.plugins.push(
> ```

Not sure if this will work if config is a `const`
___
*[admin-dev/themes/new-theme/webpack.config.js, line 31 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-5cM1GH7MO8dm0Sa:-LJT-5cM1GH7MO8dm0Sb:bn76j10) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/admin-dev/themes/new-theme/webpack.config.js#L31)):*
> ```JavaScript
> const keepLicense = require('uglify-save-license');
> 
> const config = {
> ```

Same comment about `const`
___
*[classes/Cart.php, line 1284 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-Dho3FwdLiVxshb-:-LJT-Dho3FwdLiVxshb0:b-4yqywo) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/classes/Cart.php#L1284)):*
> ```PHP
> 
>         if (Context::getContext()->customer->id) {
>             // The $id_address_delivery is null, use the cart delivery address
> ```

Maybe move this comment _inside_ the if?
___
*[classes/Cart.php, line 1347 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-KYa--vGom4AVSnb:-LJT-KYa--vGom4AVSnc:b-8kkx5b) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/classes/Cart.php#L1347)):*
> ```PHP
>         }
> 
>         if (!$product->available_for_order ||
> ```

Please add boolean operators at the start of the line. Also, one statement per line if you break them into more than one line.
___
*[classes/Cart.php, line 1382 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-U7v2AUFyk7rbM_J:-LJT-U7v2AUFyk7rbM_K:b-fwriz1) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/classes/Cart.php#L1382)):*
> ```PHP
>                 $newProductQuantity = $productQuantity + $quantity;
> 
>                 if ($cartFirstLevelProductQuantity['quantity'] <= 1 ||
> ```

Again, please put boolean operators at the start of the line
___
*[tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php, line 83 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-ofv-19R5ZDLgMIM:-LJT-ofw838AH3n2_f_u:b-1wdw8l) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php#L83)):*
> ```PHP
>     }
> 
>     /**
> ```

I think it's good practice to either:
- Describe your test using human language like "When the number of products in the cart is increased or decreased, a call to getProductQuantity should report the correct number of items of that type in the cart".
- Name your test in an assertive way like "testNumberOfProductsInCartIsReportedCorrectlyWhenUpdatingTheirQuantity"

Otherwise it makes it very hard to figure out what was the original intent of the test. 
___
*[tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php, line 107 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-jJTCiIDf0WTcRyQ:-LJT-jJTCiIDf0WTcRyR:blnvdvk) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php#L107)):*
> ```PHP
>     }
> 
>     public function updateQuantities()
> ```

Please add a `Provider` suffix to dataProviders
___
*[themes/classic/_dev/js/cart.js, line 35 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT1Qns9IAtJpkemltA:-LJT1Qns9IAtJpkemltB:bb3u06a) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/themes/classic/_dev/js/cart.js#L35)):*
> ```JavaScript
> 
> $(document).ready(() => {
>   const productLineInCartSelector = '.js-cart-line-product-quantity';
> ```

Watch out, I don't think that the es2015 profile has been set up for babel in this project.

**Review by PierreRambaud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: all files reviewed, 9 unresolved discussions (waiting on @eternoendless and @PierreRambaud)

___
*[admin-dev/themes/default/webpack.config.js, line 77 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-033BrGNvC-Lblwf:-LJTdWt-32ZD11IM7FBK:bb6un1j) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/admin-dev/themes/default/webpack.config.js#L77)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

This should only be done in development (check webpack config for the new theme)
</blockquote></details>

Done
___
*[admin-dev/themes/default/webpack.config.js, line 83 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-3F70bM0mH2IL6_w:-LJTb-wq7OCz-TTbHbOx:b-vuhpt0) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/admin-dev/themes/default/webpack.config.js#L83)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Not sure if this will work if config is a `const`
</blockquote></details>

Yes it works, we don't change the config value, we still play with and hash.
If crashed when we have something like `const i = 1; i =2;`

**Review by PierreRambaud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @eternoendless and @PierreRambaud)

___
*[classes/Cart.php, line 1284 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-Dho3FwdLiVxshb-:-LJTdylC0hom7KcmbLGf:bq8177d) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/classes/Cart.php#L1284)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Maybe move this comment _inside_ the if?
</blockquote></details>

I just remove the useless else statement here, but I can change if you want =)
___
*[classes/Cart.php, line 1347 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-KYa--vGom4AVSnb:-LJTe1vD9MAaRFjwOisF:bq8177d) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/classes/Cart.php#L1347)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please add boolean operators at the start of the line. Also, one statement per line if you break them into more than one line.
</blockquote></details>

I just remove the useless else statement here, but I can change if you want =)
___
*[classes/Cart.php, line 1382 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-U7v2AUFyk7rbM_J:-LJTe2ziERJU_ZNiOHw_:bq8177d) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/classes/Cart.php#L1382)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Again, please put boolean operators at the start of the line
</blockquote></details>

I just remove the useless else statement here, but I can change if you want =)

**Review by PierreRambaud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @eternoendless and @PierreRambaud)

___
*[themes/classic/_dev/js/cart.js, line 35 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT1Qns9IAtJpkemltA:-LJTp5qv-nLO1k2biGV1:b4o40aa) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/themes/classic/_dev/js/cart.js#L35)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Watch out, I don't think that the es2015 profile has been set up for babel in this project.
</blockquote></details>

let was used, so we can use const =)

**Review by PierreRambaud — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @eternoendless and @PierreRambaud)

___
*[tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php, line 83 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-ofv-19R5ZDLgMIM:-LJTpybrB0Fa0Z3TlEPB:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php#L83)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I think it's good practice to either:
- Describe your test using human language like "When the number of products in the cart is increased or decreased, a call to getProductQuantity should report the correct number of items of that type in the cart".
- Name your test in an assertive way like "testNumberOfProductsInCartIsReportedCorrectlyWhenUpdatingTheirQuantity"

Otherwise it makes it very hard to figure out what was the original intent of the test. 
</blockquote></details>

Done.
___
*[tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php, line 107 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-jJTCiIDf0WTcRyQ:-LJTq0JMDmhKazmKtQKG:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/tests/Unit/Core/Cart/Adding/Product/AddStandardProductTest.php#L107)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please add a `Provider` suffix to dataProviders
</blockquote></details>

Done.

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: all files reviewed, 1 unresolved discussion (waiting on @eternoendless)

___
*[admin-dev/themes/default/webpack.config.js, line 77 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT-033BrGNvC-Lblwf:-LJmj9hQEQUMEQHwJAgh:b-8d3s6i) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/admin-dev/themes/default/webpack.config.js#L77)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Still true!
___
*[themes/classic/_dev/js/cart.js, line 35 at r1](https://reviewable.io/reviews/prestashop/prestashop/9405#-LJT1Qns9IAtJpkemltA:-LJmk0qG66Dhb0i-r-QO:b-jd2esb) ([raw file](https://github.com/prestashop/prestashop/blob/4feaa35522c56605516b1284d7e5baf2ef421353/themes/classic/_dev/js/cart.js#L35)):*
<details><summary><i>Previously, PierreRambaud (GoT) wrote…</i></summary><blockquote>

let was used, so we can use const =)
</blockquote></details>

But it will still fail on older browsers. We can add babel later though.

**Review by eternoendless — COMMENTED** [review]
Looks good :thumbsup: 
Don't forget to commit the assets!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405#-:-LJnFjqSApVR3t0hgCwY:bwaz2k)* status: all files reviewed, 1 unresolved discussion (waiting on @PierreRambaud)

**Review by eternoendless — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9405)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by marionf** [comment]
@PierreRambaud Does it solve also this issue #9841 ?

**Comment by PierreRambaud** [comment]
@marionf Yes!

**Comment by marionf** [comment]
@PierreRambaud 

If I put 2 products in cart, enter 0 in qty field and click out the field, I can see quickly a 1 in the qty field before the deletion of the product

pr9405

**Comment by PierreRambaud** [comment]
@marionf Is it really important? Do you want me to investigate?

**Comment by marionf** [comment]
It doesn't seem to cause any other problems, so it's not necessary :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @PierreRambaud and everyone for the review.

PS: I've linked the related GitHub issue, but I don't know what I should do with this issue :/

**Pull request merged**
