### PR TITLE
Add default group to customer listing

### LINKED ISSUE #23936: Merchant is unable to determine which customer is registered
#### Is your feature request related to a problem?

When searching for a customer account, the merchant is unable to see which customer from the list is registered, and which are guest accounts.

#### Describe the solution you'd like

Display "Registered" YES/NO in the list. Maybe along with a customer group - related to: https://github.com/PrestaShop/PrestaShop/issues/23116

**Screenshots**

Výstřižek

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR adds customer's default group to customer listing page, so you can clearly distinguish between a registered customer and all guests. If group feature is disabled, this column is not visible.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23936
| Related PRs       | -
| How to test?      | See below
| Possible impacts? | -

**Use cases to test**
- Filtering works
- Exporting works
- Sorting works
- It gets disabled if group feature is disabled

**How it looks**

groups

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28183)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
nice ! this PR looks good to me, there's just CS fixer who's not happy:

**Review by Julievrz — APPROVED** [review]
Wording ✔️ Thanks!

**Review by Progi1984 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Thanks for the PR !

Filtering works
Exporting works
Sorting works
If group is deleted, it won't show in the list of customers
Tested with customer created from BO and FO
Tested with import of customer
Export to SQL Manager works

This is QA ✅

**Comment by Progi1984** [comment]
Thanks @Hlavtox & @florine2623

**Pull request merged**
