### PR TITLE
[*] Project : Improve PHP 7 compatibility

### PR DESCRIPTION
**Pull request by firstred**
Make variable handling compatible with PHP 7.
Background info: http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi,

While this PR increases the compatibility with PHP 7, it will throw a syntax error on PHP 5.3 with every line you changed.
In consequence, it cannot be merged for PrestaShop 1.6.1.X

However, I guess this code 
```php
if (!Validate::{$field['validation']}($value)) {
```

replaced by 
```php
$field_validation = $field['validation'];
if (!Validate::$field_validation($value)) {
```
would work on every PHP version.

**Comment by firstred** [comment]
PHP 5.3 still supported?:stuck_out_tongue_winking_eye:

Alright. Let's see if that works. Also explains why #4175 has never been merged into the 1.6.1.x branch.

**Comment by Quetzacoalt91** [comment]
Yeah, the minimum compatible PHP version will change with PrestaShop 1.7 :wink: 

BTW, #4175 has been merged, but reverted because of this bug (as explained in your other PR).

**Comment by firstred** [comment]
Let's close this one. #4503 has got everything PrestaShop needs in order to gain PHP 7 compatibility, I think.

**Pull request closed without merging**
