### PR TITLE
Solved problem with non-unserialized filters data

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | copy from `1.6` branch, https://github.com/PrestaShop/PrestaShop/pull/5571 |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1309 |
| How to test? | Do a search on orders tab with date |
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by aleeks** [comment]
@kpavlovsky thank you!
So, you can know how many PR hasn't into `develop` ? they are only yours ?

**Comment by kpodemski** [comment]
@aleeks from what i see there is a lot of changes on `1.6` which are not available on `develop`, i'm going to check latest releases and see how many, i'll try to cherry pick all of PRs which are also needed for `develop`

**Comment by aleeks** [comment]
@kpodemski ok, it's possible that one of them are actually fixed but.. let we see.
Thank you

**Comment by xBorderie** [comment]
Well, this is a first list to check :)
https://github.com/PrestaShop/PrestaShop/pulls?utf8=%E2%9C%93&q=label%3A%22To%20be%20cherry-picked%22%20base%3A1.6%20
Are you up for it, Krystian?

**Comment by kpodemski** [comment]
Wow, nice, so... i'm on it @xBorderie - i'll handle all of these :)

**Comment by xBorderie** [comment]
@kpodemski Wow, that would be awesome! I think many of these are just PR which the developer has forgotten to change label (from "to be cherry-picked" to "cherry-picked" :) ), so it shouldn't be take too lon to parse. Thanks!

**Comment by xBorderie** [comment]
Actually, only those were merged in 1.6: https://github.com/PrestaShop/PrestaShop/pulls?utf8=%E2%9C%93&q=label%3A%22To%20be%20cherry-picked%22%20base%3A1.6%20is%3Amerged
The others were proposed for merge, but not merged. Doesn't they can't be useful :p

**Comment by aleeks** [comment]
Thank you!

**Pull request merged**
