### PR TITLE
Remove minify HTML feature

### PR DESCRIPTION
**Pull request by julienbourdeau**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This feature usually introduces bugs and it's really a tiny tiny optimisation. |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

### CODE REVIEW

**Comment by firstred** [comment]
Couldn't agree more :)

**Comment by aleeks** [comment]
@julienbourdeau Cool !
Need to remove tests, `function assertHtmlEquals` and calls in : 
- `testDisplayError_shouldReturnSimpleError()`
- `testDisplayError_shouldReturnMultipleErrors()`

on file Tests\Unit\Classes\Module\ModuleCoreTest.php !

**Comment by aleeks** [comment]
Hello @julienbourdeau,
Can you rebase from develop for checks and sql file ?! :

**Comment by aleeks** [comment]
thank you!

**Pull request merged**
