### PR TITLE
Fix & optimize search::find queries

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Fix & optimize search::find queries
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8701
| How to test?  | add thai language, create a product & search it on the FO

### CODE REVIEW

**Comment by maximebiloe** [comment]
Thanks @aleeks

**Comment by jocel1** [comment]
To be merged in 1.7.x

**Comment by xBorderie** [comment]
@jocel1 Are you taking care of the 1.7 PR?

**Comment by jocel1** [comment]
@aleeks already did in https://github.com/PrestaShop/PrestaShop/pull/7994 ;)

**Pull request merged**
