### PR TITLE
Indian Localization improved 

### PR DESCRIPTION
**Pull request by adhavalboy**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Indian localization Improved 
| Type?         | improvement 
| Category?     |  IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | here is the list https://en.wikipedia.org/wiki/States_and_union_territories_of_India

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9411)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi,

Can you complete the description, branch, and how we can test? What it fix exactly? 

Regards

**Comment by mickaelandrieu** [comment]
Hello, I'm not sure this is a fix... imo you have utf8 encoding issues on your own shop and you're changing correct translations to fix it: don't you?

Looking at the very first translation you have changed: http://www.citypopulation.de/India-ArunachalPradesh.html is the right syntax.

So, I'm against this changes in the core :-1:

**Comment by adhavalboy** [comment]
In India, people are generally writing as I proposed many  see this pic of e-commerce site of India
screenshot_20180807_152613

**Comment by adhavalboy** [comment]
You are Following German-English script convention but localization for India-English script is different and localization purpose is to understand locally. I am from India, We are never writing as previously written.

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Hello @adhavalboy fair enough, thanks for completion of the description and the explanation.

**Comment by PierreRambaud** [comment]
Thansk a lot @adhavalboy

**Pull request merged**
