### PR TITLE
Fixed misuse of magic routing

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Template annotation may be unable to find the right path, probably because at some point it "lowercase" the path. It can work fine in MacOS, but not in Windows or GNU/Linux servers.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Access Stock overview page in `develop` branch and on this one. If you're using MacOS, you may (and should) configure it to be case sensitive.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8863)

### CODE REVIEW

**Comment by alegout** [comment]
Maybe you could add the fix also for src/PrestaShopBundle/Controller/Admin/TranslationsController.php? If i remember well, @prasanthSelvar find the same issue on it.

**Comment by Quetzacoalt91** [comment]
@alegout done :)

**Review by mickaelandrieu — COMMENTED** [review]
Thanks @Quetzacoalt91 !

**Review by alegout — APPROVED** [review]
Thank you @mickaelandrieu  and @Quetzacoalt91 !

**Pull request merged**
