### PR TITLE
[-] FO : Invalid combination price in case of ecotax

### PR DESCRIPTION
**Pull request by erouvier29**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, thank you for your contribution, can you please add some steps in a comment in order to reproduce this issue ?

Best regards.

**Comment by eric-rouvier** [comment]
1. Create a simple product, e.g. retail price with tax: 120€, tax rule: 20%, ecotax (tax incl.): 10€
2. Open FO product detail -> price = 120€ tax incl., including 10€ for ecotax: OK
3. Create combinations for above product without any price impact
4. Re-open FO product detail -> price = 121.67€ tax incl., including 10€ for ecotax: KO

**Comment by jeromenadaud** [comment]
Hi, I can't reproduce please see attached images:

screenshot 2015-07-27 12 06 28
screenshot 2015-07-27 12 06 50
screenshot 2015-07-27 12 07 08
screenshot 2015-07-27 12 07 19

**Comment by eric-rouvier** [comment]
Sorry, I forgot to specify that the issue occurs when there is a tax on ecotax (it is the case in France).
I guess you didn't set it...

**Comment by jeromenadaud** [comment]
Yes, you are right, thank you for you contribution.

Best regards.

**Pull request merged**
