### PR TITLE
Add Hindi, Mexican & Bosnian languages

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Include @LouiseBonnard Pull requests about Hindi, Mexican and Bosnian languages and add @eternoendless pull requests that add languages support.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | You must be able to install PrestaShop in Bosnian & Hindi.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11058)

### CODE REVIEW

**Review by eternoendless — APPROVED** [review]
LGTM

**Comment by eternoendless** [comment]
FYI: This PR also changes Filipino to Tagalog (because there's no 2-letter ISO code for Filipino) and adds Uzbek and Gujarati too

**Comment by marionf** [comment]
If I select Hindi, it's not translated I still see English

capture d ecran_500

I don't see Mexican, Uzbek, Gujarati, Filipino or Tagalog in the list

If I install in bosnian language and Bosnia & Herzegovina country, the english is also installed with USD currency

capture d ecran_502

capture d ecran_501

**Comment by marionf** [comment]
Don't know if it's related to this PR but if I switch to 1.7.5.x branch and try to re-install I have this error:

capture d ecran_503

**Comment by PierreRambaud** [comment]
@marionf For the first one, there is few translations in Hindi.
For the second, it's weird, I just installed PrestaShop with Hindi language :/

**Comment by PierreRambaud** [comment]
@marionf I tried and I'm able to reproduce what you encounter. You switch source code, and in 1.7.5.x Hindi language is not yet available, so you have an index error :)
it's not related to this branch.

**Comment by Quetzacoalt91** [comment]
Thank you @PierreRambaud

**Pull request merged**
