### PR TITLE
Set Phone as mandatory (as required in address format)

### LINKED ISSUE #28848: BO > Customers > Addresses - Required fields are not used in back office
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When applying required fields for addresses they are not used in the BO

### Expected behavior

Use the required fields like : 

https://user-images.githubusercontent.com/5064590/175557925-ebfe5aa9-09ac-4232-affd-0765cf7f4a7e.mp4

### Steps to reproduce

1 ) Set required fields in back office for address
2 ) Edit an address from back office and see you can add or adit an adresse without required field

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Nickinthebox**
Current address format for my country (France) is:
_firstname lastname
company
vat_number
address1
address2
postcode city
Country:name
phone_

If we don't fill the phone, we have a weird error in this create/edit address form : "Les champs d'adresse contiennent des caractères invalides." (meaning address fields contain illegal characters)

I fixed it by making the phone field mandatory (this commit), so that our end users are aware this is actually mandatory.

This is just a quick fix (maybe you should not merge this commit as it might not be the case in all address format for all countries, I have not checked, but if someone else has the same issue, he will find this solution googling it as I wrote the error above in French...).

The real fix would be: in the address form, when country is changed in the drop down menu the mandatory fields should also adapt (the * before the form fields + the help box asking to fill an empty mandatory field) depending on the address format of this selected country.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | See above
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28848.
| Related PRs       | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Comment by ghost** [comment]
Hello @Nickinthebox 

Have you check this part of PrestaShop.

Screenshot (47)


You must also create [an issue](https://github.com/PrestaShop/PrestaShop/issues/new/choose) this [tutorial](https://devdocs.prestashop.com/8/contribute/) can help you.

**Comment by Nickinthebox** [comment]
> Have you check this part of PrestaShop.

Yes, the "phone" was checked in this menu but the field was not indicated as mandatory in the form (no asterisk / no helper asking to fill it).

> You must also create [an issue](https://github.com/PrestaShop/PrestaShop/issues/new/choose) this [tutorial](https://devdocs.prestashop.com/8/contribute/) can help you.

Ok will check later

**Comment by ghost** [comment]
For me it's good Which theme do you use?

Screenshot (48)

**Comment by Nickinthebox** [comment]
> For me it's good Which theme do you use?

It's not on the front but on the admin page ( Clients > Address > New which has a path like */sell/addresses/new )

**Comment by ghost** [comment]
Ok, I understand the best way would be to get the required fields.

So we could also have * for adress2 for example.

Plz create an issue with the steps to reproduce.

**Comment by ghost** [comment]
Like this

https://user-images.githubusercontent.com/5064590/175553306-ec86e0d0-ac13-44d9-9453-38335001e498.mp4

**Review by matks — COMMENTED** [review]
> This is just a quick fix (maybe you should not merge this commit as it might not be the case in all address format for all countries, I have not checked, but if someone else has the same issue, he will find this solution googling it as I wrote the error above in French...).

I confirm this is probably not the right way to fix this 😅 it will work only if you need phone number mandatory

**Comment by ghost** [comment]
You can do something like this 

https://github.com/PrestaShop/PrestaShop/compare/develop...okom3pom:PrestaShop:change-required-field

i made an [issue](https://github.com/PrestaShop/PrestaShop/issues/28848) to remember

**Comment by kpodemski** [comment]
Hello @Nickinthebox 

Thanks to @okom3pom, there's a Pull Request implementing this feature properly and fixing a bug.

https://github.com/PrestaShop/PrestaShop/pull/29114

I'm closing this PR but thank you for taking the time to contribute.

**Pull request closed without merging**
