### PR TITLE
Update account.html

### PR DESCRIPTION
**Pull request by erseco**
Is a security hole giving the password by e-mail!

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Have you tried it ? I'm not sure this email is no longer used in PrestaShop 1.7.

**Comment by PrestaEdit** [comment]
This email is still used and is related to the "PS_CUSTOMER_CREATION_EMAIL" configuration that you can see in the Customer preferences ("Send an email after registration").

**Comment by erseco** [comment]
Yes, it is used, and IMHO is dangerous send the password by email, is better to avoid this

**Comment by gskema** [comment]
Does it send automatically generated passwords? Then you can't delete this.

**Comment by julienbourdeau** [comment]
HI,

So I checked, the email is still used but the password isn't sent. I guess it's related to the change we made about the _reset password_ process.

mailcatcher

I asked the product team, we'll see, the email probably need a bigger update.

Also, lets keep in mind that there is no security issue, it's mostly a matter of reassurance.

**Comment by Quetzacoalt91** [comment]
Hello,

It seems the password recovery is broken, we should have a link to the login page with a token.
By looking at the content, we have no way to go to this page.

**Comment by Quetzacoalt91** [comment]
Hi,

Thanks for your contribution. However, the changes have been already applied by another PR (#5889).
In consequence, I have to close this one.

Best regards

**Pull request closed without merging**
