### PR TITLE
Use Chrome instead of Firefox

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Use Chrome instead of Firefox
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
One day it rains, one day it's sunny! :running:

**Comment by Quetzacoalt91** [comment]
But did you try to turn it off and on again ?

**Comment by aleeks** [comment]
Push the button @maximebiloe !

**Comment by maximebiloe** [comment]
leaving

**Pull request closed without merging**
