### PR TITLE
Fix shipping price in orders demo

### LINKED ISSUE #17755: Wrong shipping in BO order view page
**Describe the bug**
Shipping price in Back Office order view page differs from Front Office for same order. Occurs in both legacy and migrated pages.
** NOTE ** Its associated with demo data. (the fixtures). With new order it works as expected

**To Reproduce**
1. Go to Orders->select order to view-> find products block
2. Check Shipping price
3. Go to Front office->find the same product->add to cart->check shipping price
4. In FO and BO the shipping prices are different. FO has the correct one.

**Screenshots**
1. migrated page BO Screenshot from 2020-02-20 11-20-03
2. legacy page BO Screenshot from 2020-02-20 11-20-16
3. FO Screenshot from 2020-02-20 11-23-33

**Additional information**
PrestaShop version: 1.7.7, 1.7.6
PHP version: N/A

### PR DESCRIPTION
**Pull request by marionf**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix shipping price in orders demo
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17755
| How to test?  | Verify orders created by demo data after a fresh install.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17765)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @marionf,

In the BO => Orders => Order details page
The shipping is always displayed with Tax excluded, but it is incorrect
1. For this customer group, prices are displayed as Tax included => `Shipping = €7.00` => NOK
image
In the FO => `Shipping= €8.40 `
2. For this customer group, prices are displayed as Tax excluded => `Shipping = €7.00` => OK
image

Thanks!

**Comment by marionf** [comment]
@khouloudbelguith it should be ok right now

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @marionf,

It is OK.
1. Tax excluded => OK
image
2. Tax included => Ok
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @marionf

**Pull request merged**
