### PR TITLE
Harmonization of  wording for 'cannot' spelling

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Wording harmonization: changed "can not" to "cannot". |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | n/a |
| How to test? | ^^; |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
yes

**Comment by xBorderie** [comment]
bd9a46f81e1613f8bb0c8cd1fc3d1360

**Comment by AlexEven** [comment]
:grimacing:

**Comment by Shudrum** [comment]
:stuck_out_tongue:

**Comment by xBorderie** [comment]
Next step for you Alex: correct the relevant "can not" to "cannot" :)
https://github.com/PrestaShop/PrestaShop/search?l=php&q=%22can+not%22&utf8=%E2%9C%93

**Pull request merged**
