### PR TITLE
Wrong validation while uploading product image more than defined size limit.

### LINKED ISSUE #20613: Wrong validation while uploading product image more than defined size limit.
#### Describe the bug
Wrong validation while uploading product images more than the defined size limit.

#### Expected behavior

It must produce proper validation along with its unit.

#### Steps to Reproduce

1. Go to Advanced parameters and check product image upload size limit https://prnt.sc/u14x0j (currently 2 MB).
2. Now go to the Admin Product page and upload an image size more than 2 MB.
3. Now you will get this message: https://prnt.sc/u14ugs
4. The above message is not correct here size unit is not defined (i.e, it is KB or MB nothing defined).

**Screenshots**
https://prnt.sc/u14ugs

#### Additional information

* PrestaShop version: 1.7.6.7
* PHP version: 7.0

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Wrong validation while uploading product image more than the defined size limit.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20613 .
| How to test?  | Go to Advanced parameters and check product image upload size limit https://prnt.sc/u14x0j (currently 2 MB).Now go to the Admin Product page and upload an image size more than 2 MB.Now you will get this message:https://prnt.sc/u14ugsThe above message is not correct here size unit is not defined (i.e, it is KB or MB nothing defined).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20614)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
thank you @Amit-Kumar-Tiwari-Webkul , LGTM, still, waiting for wording review before sending this PR to QA 👍

**Review by NeOMakinG — APPROVED** [review]

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
Hi, Any update from QA team.

**Comment by PierreRambaud** [comment]
> Hi, Any update from QA team.

Unfortunately, you need to wait, they have many issues to test :)

**Comment by khouloudbelguith** [comment]
Hi @Amit-Kumar-Tiwari-Webkul,

It is ok :heavy_check_mark: 
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @Amit-Kumar-Tiwari-Webkul & @khouloudbelguith

**Pull request merged**
