### PR TITLE
Removes unneeded parentheses around return statement

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Removes unneeded parentheses around return statement
| Type?         | improvement
| Category?     | TE
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14236)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
We'll plan to remove this directoryu because of legacy context. Not sure it's needed to improve this part.
wdyt @matks ?

**Comment by matks** [comment]
> We'll plan to remove this directoryu because of legacy context. Not sure it's needed to improve this part.
> wdyt @matks ?

Can't hurt 😅the removal is going to happen very slowly, so I think it's alright to put some ❤️in this directory

**Comment by Quetzacoalt91** [comment]
On my side, I think modifying this modules which is only here as fixtures is unecessary. This change should be applied on the source repository in https://github.com/PrestaShop/ps_banner, or it will be lost.

By the way, I wonder if these modules should not be included in this repository as submodules, because we duplicated code and we don't really know anymore if this part should be maintained. I'm closing this PR, but this question will remain as long as we keep this code.

**Comment by matks** [comment]
> By the way, I wonder if these modules should not be included in this repository as submodules, because we duplicated code and we don't really know anymore if this part should be maintained. I'm closing this PR, but this question will remain as long as we keep this code.

Maybe we should not rely on real modules in our tests 🤔only fake dummy modules ?

**Comment by PierreRambaud** [comment]
I'm for in favor of dummy modules, with only the necessary, which means, if your test need two hooks, create a little module with two hooks, etc.

**Pull request closed without merging**
