### PR TITLE
Update jQuery to 3.4.1 in Core theme and Classic theme

### LINKED ISSUE #14929: Upgrade to jQuery latest, use jQuery migrate for retro compatibility 1/4 - CORE THEME & CLASSIC THEME
EPIC : #13829

**Please update the EPIC after completion**

We are currently using old or very old versions of jQuery. These versions have never been upgraded because of breaking changes introduced in later versions. Using jQuery Migrate we could upgrade them to the latest version without breaking backward compatibility.

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Migrate jquery to jquery 3 and add jquery migrate, in front office (core and classic theme)
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14929
| How to test?  | Check that everything works in frontend (anything involving javascript)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15327)

### CODE REVIEW

**Comment by eternoendless** [comment]
Please commit the compiled assets in a commit of their own (as per the [contribution guidelines](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#compiled-assets)) :)

Otherwise it looks good!

**Review by jolelievre — COMMENTED** [review]
No need for a config or anything with `jquery-migrate`?
Like which version should be managed or anything?

**Comment by PierreRambaud** [comment]
@jolelievre The version is automatically manage by the jquery.migrate version :)

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Compile assets in separated commits please

**Comment by matthieu-rolland** [comment]
@PierreRambaud So I compiled the assets in a separated commit. It seems there is a small diff on the css compiled file too.

**Review by jolelievre — DISMISSED** [review]
Seems fine to me Maybe the css file was not up to date

**Comment by jolelievre** [comment]
Unless you need to rebase your branch @matthieu-rolland ?

**Review by PierreRambaud — DISMISSED** [review]

**Comment by ghost** [comment]
Hi,

Checked with Sarah L. Who worked on the classic theme (team ADDONS), it is important for the QA to test in depth as the cart and checkout uses js a lot.

**Pull request closed without merging**
