### PR TITLE
Simplify dependency injection

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Simplify dependency injection to ease maintainance + adds some autowiring when needed
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | CI 🟢 + automated tests

### CODE REVIEW

**Review by boherm — DISMISSED** [review]
LGTM, thanks @FabienPapet for your PR!

**Comment by FabienPapet** [comment]
Tests : https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/5411635223

**Review by boherm — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
@FabienPapet ga.tests are red. Is that related to your PR?

**Comment by FabienPapet** [comment]
I don't know, ping @PrestaShop/qa-automation

**Comment by Progi1984** [comment]
I have this error : 
fail_test_1

**Pull request closed without merging**
