### PR TITLE
Explicit error messages

### PR DESCRIPTION
**Pull request by Zudjo**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Adding an explicit error message, to avoid losing an hour around a misterious "Fatal Error" like I did :)
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Run the method with a non valid $isoCode parameter
| UI Tests          | Not needed
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/discussions/33981
| Related PRs       | Not needed
| Sponsor company   | ecommerce-manager.it

---

This is my first pull request ever, if something is wrong please let me know.
I'm not sure if the category 'TE' is the right one.

### CODE REVIEW

**Comment by mflasquin** [comment]
Hi @Zudjo, thanks for you PR but I think you have made a mistake, there is too many changes, maybe you have target the wrong branch (8.1.x, instead of develop ?)

**Comment by boherm** [comment]
Yes, as @mflasquin said, I think that you targeted the wrong branch or maybe your git history of your fork is a wayyy too old!

Also, the TE of your description is wrong.
To improve your table description, you can check this link: https://devdocs.prestashop-project.org/1.7/contribute/contribution-guidelines/pull-requests/#type--category 

Anyway, thanks a lot for your first contribution, and welcome! 😄

**Comment by Zudjo** [comment]
> Hi @Zudjo, thanks for you PR but I think you have made a mistake, there is too many changes, maybe you have target the wrong branch (8.1.x, instead of develop ?)

Oh yes, I see the problem.
I pointed to the 8.1.x as suggested by someone in the referenced discussion, but I forked the develop branch.

What should I do?
Point to develop, or fork 8.1.x and point to 8.1.x?

**Comment by Zudjo** [comment]
> Yes, as @mflasquin said, I think that you targeted the wrong branch or maybe your git history of your fork is a wayyy too old!
> 
> Also, the TE of your description is wrong. To improve your table description, you can check this link: https://devdocs.prestashop-project.org/1.7/contribute/contribution-guidelines/pull-requests/#type--category
> 
> Anyway, thanks a lot for your first contribution, and welcome! 😄

Yes I read that contribution page, but I'm still not sure what category this little improvement is under haha
What should it be?

**Comment by boherm** [comment]
@Zudjo, hum good question 🤔

Maybe it's easier to recreate a new branch based on the up-to-date 8.1.x branch, and cherry pick your commit `4c15ee063785bcdd73ffbdc49bc4c824741534d7`.

Then, you can create a new PR with your new branch and target the 8.1.x branch.
What do you think?

About the TE category, as I can see you edit the `classes/Country.php` so I think that CO (for core) could be better!

**Comment by Zudjo** [comment]
Ok, created new PR. Hope it's all good now.
Thanks for the support and patience.
I'm closing this PR.

**Comment by boherm** [comment]
Just to keep some history, this is a link to your new PR: https://github.com/PrestaShop/PrestaShop/pull/34158

**Pull request closed without merging**
