### PR TITLE
FO : Removed shop name from meta title

### PR DESCRIPTION
**Pull request by Dh42**
| Questions | Answers |
| --- | --- |
| Branch? | Develop. |
| Description? | This removes the shop name from the title. There has never been a translation of the shop name, so this will help with geo specific SEO and also give greater control over the meta title. |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Load page |

### CODE REVIEW

**Comment by inetbiz** [comment]
Increase character count to entities in the title. Best SEO advantage I can think of doing.

**Comment by julienbourdeau** [comment]
I agree! Thank you

**Comment by inetbiz** [comment]
@julienbourdeau Why did https://github.com/PrestaShop/PrestaShop/pull/5798 add it back. Who has the final word?

**Comment by maximebiloe** [comment]
It's not adding the shop name back, it's just removing a useless concat.

**Comment by inetbiz** [comment]
My mistake. =)

**Pull request merged**
