### PR TITLE
[-] FO : Fix line breaks for address field in module block contact info

### PR DESCRIPTION
**Pull request by spem**
Fix line breaks for address field in module block contact info, to
insert a line break between the company name and the address.

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, can you please sync your repository and include sass file to your PR ?

Best regards.

**Comment by AlexEven** [comment]
Hello, 

Two requests for you regarding the wording "Click on number to call now".
1: is it possible to simplify with "Click to call us now"? (shorter)
2: it wouldn't be relevant to desktop users anymore. Is it possible to amend the code so that you have 2 versions, a desktop one where you keep the original wording (Call us now), and a mobile one with your wording?

Thanks again, and best regards,

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by AlexEven** [comment]
I said what I had to say regarding wording, but I also made suggestion to improve the whole thing - I think a PM should review it. Or close the PR altogether, for we haven't had any feedback from @spem.
Thanks!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
