### PR TITLE
Make Twig accessible for modules inside hooks

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | It is not possible to access Twig inside back office display hooks using `$this->get('twig')`, this change aims to make Twig accessible explicitly without making it a public service - please note that it is a BC Break anyway, and I'm not sure if this is a better approach than making it global in general. I also added the missing `multishop_context_group` property, when missing, it breaks modules configuration page in multi-store context.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | To be tested by a dev, try to `$this->context->controller->getTwig()` in any back office display hook. I also added a fallback when using $this->get('twig') You can use the example module from this PR https://github.com/PrestaShop/example-modules/pull/194 (or from the main branch if it has been merged already), when the module is installed some additional blocks should be visible on the Order view page without exception triggered
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/12175474744
| Fixed issue or discussion?     | n/a
| Related PRs       | n/a
| Sponsor company   | PrestaShop SA

### Breaking Change

`ModuleCore::get` is now strictly typed `object|null` it doesn't return `false` anymore

### CODE REVIEW

**Comment by kpodemski** [comment]
cc @jolelievre 

imho it's a must have for the beta

**Review by jolelievre — DISMISSED** [review]
Thanks @kpodemski

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/committers 

this can be tested by devs, for example with the usage of `demovieworderhooks`

**Review by florine2623 — COMMENTED** [review]
Hello @kpodemski ,

As discussed with some devs, I tested these issues on multistore as this PR might fix them :
https://github.com/PrestaShop/PrestaShop/issues/37442 :x:
https://github.com/PrestaShop/PrestaShop/issues/37222 ✅ 
https://github.com/PrestaShop/PrestaShop/issues/37572 :x:

Issue https://github.com/PrestaShop/PrestaShop/issues/37222 ✅ is fixed and has been closed.

@kpodemski , I have tried following your instructions to test your PR with the example-module.
But I cannot install the module properly.

I have tried by dragging and dropping the module in my files.
Screenshot 2024-12-11 at 16 39 45

I have tried to upload the zip through Module Manager in BO
Screenshot 2024-12-11 at 16 40 25

Am I missing something ?
Waiting for your feedback :)

**Comment by kpodemski** [comment]
Hello @florine2623 

37442 and 37572 are completely unrelated to this PR. Did you run `composer install --no-dev` before uploading the .zip? It's technical PR that's why I suggested a developer to test it, it would just be easier for them :)

**Comment by Hlavtox** [comment]
@kpodemski Krystian, do other services work like they did? `router`, `session` etc.?

**Comment by kpodemski** [comment]
@Hlavtox I haven't tested it, but after discussing with @jolelievre we agreed that we treat Twig as an exception, by default developers should call the code outside of the main module class that has services correctly injected using DI

**Comment by Hlavtox** [comment]
@kpodemski Well, it's used in the example modules, and widely in 3rd party modules. Having to create separate class, YML files, composer just to fetch one twig, is just making it unnecessarily complicated.

**Comment by jolelievre** [comment]
Hi @florine2623 here is the module for test:
[demovieworderhooks.zip](https://github.com/user-attachments/files/18177896/demovieworderhooks.zip)

**Comment by florine2623** [comment]
Needs to test this issue : https://github.com/PrestaShop/PrestaShop/issues/37690

**Comment by kpodemski** [comment]
@florine2623 unrelated to this PR

**Comment by jolelievre** [comment]
@florine2623 indeed the initial purpose of this PR is for twig only, there is an opportunity to fix https://github.com/PrestaShop/PrestaShop/issues/37222 since the missing property was added but that's all In any case the multishop bugs shouldn't block this PR

**Review by florine2623 — APPROVED** [review]
Hello all,

Noted for the issues unrelated to this PR ^^

I followed the How to test of this PR.
It works as expected ✅ 
Screenshot 2024-12-18 at 11 14 24

Screenshot 2024-12-18 at 11 14 37

Screenshot 2024-12-18 at 11 14 43

Tested https://github.com/PrestaShop/PrestaShop/issues/37222, it is fixed as expected ✅ 

https://github.com/user-attachments/assets/b7ae5d24-a900-4cf2-a8d4-0543a842fda5

I tested the configuration of the module, before and after the upgrade, the configuration of categorytree works as expected.

Thanks!

**Comment by kpodemski** [comment]
thank you @florine2623 ❤️

**Pull request merged**
