### PR TITLE
Shop link change

### PR DESCRIPTION
**Pull request by ShepherdV8**
## Description

In the current configuration when you click on the shop link it opens in the same window as the BO so you loose the BO page.
Changing "link" to "_blank" will open FO in a new tab as it always has.

### CODE REVIEW

**Comment by firstred** [comment]
You would probably want to set the `target` attribute instead of changing the `class` in order to achieve the desired behavior.

**Comment by ShepherdV8** [comment]
This change sets the class as it has always been _blank is the proper target for a link to open in a new window instead of current.

**Comment by firstred** [comment]
I've just tested your PR, but the shop still opens in the same window.
Shouldn't it be `<a class="link" href="{if isset($base_url_tc)}{$base_url_tc|escape:'html':'UTF-8'}{else}{$base_url|escape:'html':'UTF-8'}{/if}" target="_blank">{$shop_name}</a>` instead?

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by ShepherdV8** [comment]
I also tested this and for some reason the link has changed or the file the link points to.
Now the file is the header.tpl (admin/themes/default/template) but basically the same change.
However someone else already created a pull request for this.
After a little thought on the subjest I see that  firstred comment on target would be better target="_blank".

**Comment by ShepherdV8** [comment]
I did not use Git for the commit so it does not show in the CMD window, I am new at using Git so still learning how to use it properly.

Also I installed a new test version (develop branch) and the Shop link once again points to the shop_list.tpl file instead of the header.tpl file, this seems to only be true on fresh install as I checked this morning and now points to header.tpl, strange but true.
I have never used Multi-Shop so I wonder if this would apply to that.

**Comment by firstred** [comment]
I've tested it again and
``` smarty
<a class="link" target="_blank" href="{if isset($base_url_tc)}{$base_url_tc|escape:'html':'UTF-8'}{else}{$base_url|escape:'html':'UTF-8'}{/if}">{$shop_name}</a>
```
is the solution.

I recommend you to close this pull request, since you have deleted your fork and simply create a new pull request with GitHub's file editor. Make sure you follow the guidelines.

**Comment by ShepherdV8** [comment]
Yes this is the correct way I installed a new test and used target for both files mentioned and works like a charm.

Yes I did I started fresh as I am learning Git and TortoiseGit and following the instructions I just could not seem to get it to work with the current way my repos were configured.
Now everything seems OK as I did manage a commit last night using Git, but still have a ways to go to feel comfortable using it.
I can now do this with Git which seems to be the way of choice.

**Comment by ShepherdV8** [comment]
Closed I will re-submit using Git.

**Pull request closed without merging**
