### PR TITLE
checkout if a field exists

### PR DESCRIPTION
**Pull request by jonathanparentlevesque**
Hello,

I searched quite a lot, but didn't found any function allowing to checkout if a field already exists in a table.

By example, in the install function of my module, I want to add a field in a prestashop table (which will causes an error if it already exists):

```
if(!$this->isFieldExists(_DB_PREFIX_ . "category", "allow_appointment")
    and !$success = Db::getInstance()->execute(
        "ALTER TABLE `" . _DB_PREFIX_ . "category`
        ADD `allow_appointment` TINYINT(1) NOT NULL DEFAULT 0"
    )
) {
    $this->_errors[] = $this->l(
        'An error occured while altering the category table.'
    );
}
```

You could add a function similar to this one in the `dbCore` class:

```
 /**
 * Determine if a field exist in a table (of the active database) or not.
 *
 * @param $tableName String
 * @param $fieldName String
 *
 * @return Boolean
 */
 private function isFieldExists($tableName, $fieldName)
 {
      $exists = false;

      if ($result = Db::getInstance()->executeS(
                "(SELECT DATABASE() as db_name)"
           ) and !empty(Db::getInstance()->executeS(
                "SELECT NULL
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE table_name = '" . pSQL($tableName) . "'
                AND table_schema = '" . pSQL($result[0]['db_name']) . "'
                AND column_name = '" . pSQL($fieldName) . "'"
           ))
      ) {
           $exists = true;     
      }

      return $exists;
 }
```

**Note**: I would had done it in a single SQL query, but `executeS()` Do not allow query like theses

```
SET @name = (SELECT DATABASE());

SELECT NULL
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'ps_category'
AND table_schema = @name
AND column_name = 'allow_appointment'
```

and that query do not work (as it considers `INFORMATION_SCHEMA` as the active database):

```
SELECT NULL
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'ps_category'
AND table_schema = (SELECT DATABASE())
AND column_name = 'allow_appointment
```

One of my main issue being that I didn't found anyway to know what is the name of active table during runtime unless I read the configuration file.

Thank you,
Jonathan Parent-Lévesque from Montreal

### CODE REVIEW

**Comment by xBorderie** [comment]
Hi @jonathanparentlevesque! It seems your pull-request does not contain any code commit. Is that right? Are you actually raising an issue here?

Additionally, as you can see, your PR was done on an outdated codebase, and thus takes all commits made in the meantime into account. Could you update your PR according to the latest codebase?

Thank you!

**Comment by jonathanparentlevesque** [comment]
@xBorderie 

It is not as much as an issues as a suggestion for an upgrade. The coding I'm suggesting is in my comment:

     /**
     * Determine if a field exist in a table (of the active database) or not.
     *
     * @param $tableName String
     * @param $fieldName String
     *
     * @return Boolean
     */
     private function isFieldExists($tableName, $fieldName)
     {
          $exists = false;
    
          if ($result = Db::getInstance()->executeS(
                    "(SELECT DATABASE() as db_name)"
               ) and !empty(Db::getInstance()->executeS(
                    "SELECT NULL
                    FROM INFORMATION_SCHEMA.COLUMNS
                    WHERE table_name = '" . pSQL($tableName) . "'
                    AND table_schema = '" . pSQL($result[0]['db_name']) . "'
                    AND column_name = '" . pSQL($fieldName) . "'"
               ))
          ) {
               $exists = true;     
          }
    
          return $exists;
     }

Of course, you don't need the first query to get the active database name if you use the function directly in your database class (but it doesn't possible to get the database name from a module).

I don't want to force you to integrate that coding, but I think it's the kind of function that can be useful want comes times to manage update a module table since MySQL do not support  the "if not exists" statement for "alter table".

I must also admit I struggled quite a lot wondering where you guys, the Prestashop team, are expecting outside developers to suggest upgrades for the api. Some instructions on your main web site could be beneficial for you since it is currently not intuitive at all...

Bien agréablement,
de votre confrère Canadien

**Comment by xBorderie** [comment]
Thank you for this contribution, @jonathanparentlevesque !
Pull-requests are only for code commit that are suggested. Suggestions should be discussed on [the Forge](http://forge.prestashop.com/), our bugtracker. Please create a new ticket with your idea and code there. And you can still created a PR with your code, which points to the discussion on the Forge :)

In any case, this PR is faulty. I suggest you close it once you have created a Forge ticket.

Best regards,

-xb.

**Comment by jonathanparentlevesque** [comment]
@xBorderie that's quite a lot a job you ask me there pal, I'm quite stress out on my own deadline, but I will show you my good will for this once.

**Comment by xBorderie** [comment]
I can copy/paste your content in a Forge ticket for you if you wish, but will need your Forge username in order to keep you in the conversation :)

**Comment by xBorderie** [comment]
Found [your ticket](http://forge.prestashop.com/browse/PSCSX-7461), thanks!

**Pull request closed without merging**
