### PR TITLE
Fix deprecated

### LINKED ISSUE #30147: PHP Deprecated
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Some php code used triggers deprecated warnings in the php logs.
```
1.
[28-Oct-2022 10:04:41 Europe/Stockholm] PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in D:\wamp64\www\prestashop800\vendor\twig\twig\src\Loader\FilesystemLoader.php on line 134

2.
[28-Oct-2022 10:04:41 Europe/Stockholm] PHP Deprecated:  strncmp(): Passing null to parameter #1 ($string1) of type string is deprecated in D:\wamp64\www\prestashop800\vendor\twig\twig\src\Loader\FilesystemLoader.php on line 135

3.
[28-Oct-2022 13:35:34 Europe/Stockholm] PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in D:\wamp64\www\prestashop800\classes\controller\AdminController.php on line 983

4.
[28-Oct-2022 09:56:16 Europe/Stockholm] PHP Deprecated:  uasort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in D:\wamp64\www\prestashop800\controllers\admin\AdminModulesController.php on line 110

```

### Expected behavior

No entries in the log when using the software.

### Steps to reproduce

0. Make sure debug mode is turned off in performance settings.
1. Go to orders controller in admin
2. log entries marked 1 and 2 should be in the php logs.
3. Go to modules tab, click on configure on a module like ps_brandslist
4. log entry marked 3 will be in the logs.
5. The last entry marked 4 is a bit harder as it requires a module with an admincontroller where the action parameter is not set.

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.12

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ebuildy**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | fix deprecation notice https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated#:~:text=Deprecated%3A%20Using%20%24%7Bvar%7D%20in,not%20cause%20the%20deprecation%20notice. Since PHP 8.2, PHP emits a deprecation notice on the following pattern that the dollar sign ($) is placed at the outside of the curly braces:
| Type?             |  improvement 
| Category?         |  BO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #30147
| Related PRs       | 
| Sponsor company   | SubitoLabs

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by ShaiMagal** [comment]
@ebuildy 
Totally same, two deprecations, are in file:
_./src/Adapter/Product/AdminProductDataProvider.php_

**Review by TheoAlloin — APPROVED** [review]

**Comment by kratekk** [comment]
@ebuildy does this fix works for you? I still have the same error  
`PHP Fatal error:  Uncaught ErrorException: Warning: Undefined property: Symfony\\Component\\VarDumper\\Caster\\CutStub::$cache_locking in /home/admin/domains/kadimex.8877.pl/public_html/radek/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:`

**Comment by kpodemski** [comment]
@kratekk 

there's a different fix for this issue:
https://github.com/PrestaShop/PrestaShop/pull/35466

**Comment by kratekk** [comment]
Yes @kpodemski looks like I wrote comment below wrong topic. I checked this one and does also not work

**Comment by paulnoelcholot** [comment]
Because the issue on Waiting for dev, the PR must be on Waiting for dev

**Pull request closed without merging**
