### PR TITLE
Fix display when a module uses $this->bootstrap = false;

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | There are missing styles for modules that does not use bootstrap
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5933
| How to test?  | Install a module that has bootstrap=false attribute and see the content div isn't correctly displayed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9297)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @prestamodule, thanks for thje fix.

> Install a module that has bootstrap=false attribute and see the content div isn't correctly displayed

For our dedicated QA team, would you mind to provide a module zip?

Mickaël

**Review by mickaelandrieu — APPROVED** [review]

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by prestamodule** [comment]
@mickaelandrieu i've sent to QA a simple module example using bootstrap=false

**Review by eternoendless — CHANGES_REQUESTED** [review]
This PR is missing the compiled assets and needs rebase, let me do that for you.

**Review by eternoendless — APPROVED** [review]

**Comment by marionf** [comment]
I have the same result with or without this PR, the title is hidden under the menu

capture d ecran_39

**Comment by prestamodule** [comment]
@marionf Maybe your browser cache ? Looks OK here.
capture d ecran 2018-07-10 a 18 22 31

**Comment by marionf** [comment]
Yes, it's ok :+1:

**Comment by mickaelandrieu** [comment]
And... merged, thanks everyone!

**Pull request merged**
