### PR TITLE
[*] CORE : Redis cache manager

### PR DESCRIPTION
**Pull request by mdrbx**
Introducing redis php cache manager in Prestashop.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

It seems really interesting! Unfortunately it seems like you fork 1.6 branch. Can you rebase your pull request on top of the `develop` branch ?
You can remove the merge commits at the same time :)

Also, if you want to write more details about what you're doing, why you're doing it and how to use it, it will really help the review.

Thanks for your contribution.

**Comment by Mooty13** [comment]
Hum, dunno how to do this to be honnest. Not so familiar with git.

I'll try, you can close this one.

**Comment by Mooty13** [comment]
New PR here : https://github.com/PrestaShop/PrestaShop/pull/4510

**Comment by xBorderie** [comment]
Thank you for remaking your commit on the `develop` branch! I am therefore closing this PR.

**Pull request closed without merging**
