### PR TITLE
Add arabic language in installer

### PR DESCRIPTION
**Pull request by LouiseBonnard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add Arabic language in installer
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Install PrestaShop in AR

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9414)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @LouiseBonnard

**Comment by marionf** [comment]
I can't complete the installation in Arabic #10250

**Comment by LouiseBonnard** [comment]
Oh no, why? what can we do to solve the problem?

**Comment by marionf** [comment]
I don't know, I added the issue in the to do list for 1.7.5.0

**Comment by LouiseBonnard** [comment]
@marionf, thank you.

**Pull request merged**
