### PR TITLE
Add old product ID on actionProductAdd hook when duplicating a product

### PR DESCRIPTION
**Pull request by duGuillaume**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | during product duplication it was impossible to retrieve old product id and use it on actionProductAdd hook
| Type? | improvement
| Category?     | CO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10533)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
In the case we do not duplicate a product, it would be great to at least have a entry about the original product.
This should be done in the third occurrence I found in AdminProductController:

https://github.com/PrestaShop/PrestaShop/blob/37eb0023b02716e78f3f688af70c4ea229573d18/controllers/admin/AdminProductsController.php#L1749

In this case, as we don't duplicate a product, the value could be `null`.

Also, could we have the key as `old_id_product`? It would follow the parameters of `actionShopDataDuplication`, with the parameter starting with `old_`.

**Comment by duGuillaume** [comment]
I wanted to respect the naming chart set by the existant variable named `$id_product_old = $product->id;` created at line 521 

is set like this in all duplicates functions like 
`public static function duplicateAttributes($id_product_old, $id_product_new)` or `public static function duplicateSuppliers($id_product_old, $id_product_new)` for exemple

How i need to change this PR ? By naming `$id_product_old` to `$old_id_product` everywhere or i put `'old_id_product' => $id_product_old` as third param ?

**Comment by Quetzacoalt91** [comment]
Your point seems valid, let's keep it as you did.

However, would you mind updating the third call to the hook? There is one call without the parameter.
Adding `'id_product_old' => null` would be fine.

**Comment by duGuillaume** [comment]
should i change in 
`tests/resources/module/pscsx32412/override/controllers/admin/AdminProductsController.php` l.673 and l.1797
and 
`tests/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php` l.421 and l.1549 ?

**Comment by Quetzacoalt91** [comment]
No, these files are used for tests regarding overrides only

**Comment by duGuillaume** [comment]
ok, done

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Hello @Quetzacoalt91,

I think we can merge it: do you agree?

Mickaël

**Comment by Quetzacoalt91** [comment]
Just asking for a QA review

**Comment by Quetzacoalt91** [comment]
Thank you @duGuillaume

**Pull request merged**
