### PR TITLE
Add failure scenario to cover PR 12878

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add a Behat test that follows bug scenario https://github.com/PrestaShop/PrestaShop/issues/11172 in order to validate potential fix https://github.com/PrestaShop/PrestaShop/pull/12878/
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Travis should be green

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15452)

### CODE REVIEW

**Comment by djbuch** [comment]
Tell me if I’m wrong but in this scenario you test the bug not the absence of bug ?
Be cause if the bug was not there we would have some delivery option.

Or else I didn’t understand the way we should write scenarios.

**Comment by matks** [comment]
> Tell me if I’m wrong but in this scenario you test the bug not the absence of bug ?
> Be cause if the bug was not there we would have some delivery option.

I confirm ! 😄Indeed this scenario checks the behavior we know about, the one we want to fix. So we wont merge this PR like this, we'll merge it together with your PR, once updated 😉

**Comment by PierreRambaud** [comment]
Could you please add the valid scenario instead based on https://github.com/PrestaShop/PrestaShop/pull/14381/files ?

**Comment by matks** [comment]
Found why the test of @tomlev and my test have different outputs: function `getDeliveryOptionList()` has static cache built-in. It needs to be disabled using `getDeliveryOptionList(null, true);`

**Pull request closed without merging**
