### PR TITLE
Update PageNotFoundController.php type hinting

### PR DESCRIPTION
**Pull request by ColonelMoutarde**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Add typehinting in class.
| Type?             |  improvement  refacto
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | call 404 page.

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `type` should be one of these: `new feature`, `improvement`, `bug fix` or `refacto`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hello @ColonelMoutarde!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello @ColonelMoutarde 

You typehint properties for the class that extends `FrontController` which broke the test suite.

Also, I'm not sure if we want to do this now since it provides very little value.

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@ColonelMoutarde Hi, did you even test the code?

It's throwing fatal errors in that page…

Fatal error: Type of PageNotFoundControllerCore::$ssl must not be defined (as in class FrontControllerCore) in /home/runner/work/PrestaShop/PrestaShop/controllers/front/PageNotFoundController.php on line 26
PHP Fatal error:  Type of PageNotFoundControllerCore::$ssl must not be defined (as in class FrontControllerCore) in /home/runner/work/PrestaShop/PrestaShop/controllers/front/PageNotFoundController.php on line 26

**Comment by kpodemski** [comment]
I am closing this PR, we cannot accept it as is, it would require more work to add type hints to front controllers, and I think it is not relevant for PrestaShop 9.

**Pull request closed without merging**
