### PR TITLE
Rounding problem

### PR DESCRIPTION
**Pull request by minkanbuch**
Hello! Please fix rounding problem or other price problem, when cauculate always has wrong, I checked all settings, there I think all is ok
erasmus
!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8654)

### CODE REVIEW

**Comment by minkanbuch** [comment]
Please complate my table i don't now how to do it

**Comment by Quetzacoalt91** [comment]
Hello @minkanbuch,

Bug report can be done on our bug-tracker on https://forge.prestashop.com.
As you don't suggest any change to the project, I close your pull-request.

Best regards

**Comment by minkanbuch** [comment]
Where exactly  I can find that bug report, I try to find it, but I don't now where

**Comment by minkanbuch** [comment]
?????????

**Pull request closed without merging**
