### PR TITLE
Update AdminController.php

### PR DESCRIPTION
**Pull request by martinfojtik**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, can you explain you PR please.

Best regards.

**Comment by fojt-cz** [comment]
Hi, 

of course, because of isset($values['validation']) was impossible to validate HTML field.

Best regards.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by fojtCz** [comment]
This fix is still relevant.

**Comment by xBorderie** [comment]
Alright, thank you @fojtCz !
Since it is not made on the correct branch, could you [rebase it](https://help.github.com/articles/about-git-rebase/) for the `1.6.1.x` branch?
Thank you!

**Comment by fojtCz** [comment]
Yes, this is in `unknown repository`, i created new PR #4995

**Pull request closed without merging**
