### PR TITLE
Allow more than 36 products per page

### PR DESCRIPTION
**Pull request by iqit-commerce**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Before fix controler maxium product per page was 36
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9285)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
For the record @djfm, do you remember why you set up this limit? I can't find the related pull request or any information about it.

**Comment by Quetzacoalt91** [comment]
I guess we wanted to force a limit to the customer, to avoid an unexpected charge on the server by loading all the products in a row.

We should probably avoid `Tools::getValue('resultsPerPage')` to be higher than `Configuration::get('PS_PRODUCTS_PER_PAGE')`?

**Comment by iqit-commerce** [comment]
We should probably avoid Tools::getValue('resultsPerPage') to be higher than Configuration::get('PS_PRODUCTS_PER_PAGE')

? i do not think it is good, PS_PRODUCTS_PER_PAGE set default value of products per row, let say 36.

There is often need to show much more. Limit to 36 is not flexible at all.

I think limit shpuld be remove or there shpuld be another field like PS_MAX_PRODUCTS_PER_PAGE which will also allow value like 0(no limit)

**Comment by iqit-commerce** [comment]
@Quetzacoalt91 any thoughts? Thanks !

**Comment by Quetzacoalt91** [comment]
I can agree to remove this hardcoded check. However, this should be done on the develop branch as it wasn't introduced with PS 1.7.4.0.

**Comment by iqit-commerce** [comment]
@Quetzacoalt91 ok, is there any guide which clarify when put PR in develop and when in latest branch?

**Comment by Quetzacoalt91** [comment]
This should be on the pull-request template, displayed when you open a new PR. This could be rewritten if needed.

Basically, `1.7.4.x` should have fixes of bugs brought by 1.7.4.0.

**Comment by iqit-commerce** [comment]
@Quetzacoalt91 ok i changed branch, however i think it would be better to onclude in 1.7.4.x since it do not break any backward compability

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @iqit-commerce

**Pull request merged**
