### PR TITLE
Missing legacy links fix for employess controller

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | adds legacy links to employee controller
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/13745
| How to test?  | no need

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13857)

### CODE REVIEW

**Comment by matks** [comment]
@tomas862 This PR does a lot more than just adding legacy links 😄

Why did you choose to split the "bulk toggle" route into 1 "bulk enable" and 1 "bulk disable" ? I'm not against it, I just want to understand the whole context

**Comment by tomas862** [comment]
> @tomas862 This PR does a lot more than just adding legacy links 
> 
> Why did you choose to split the "bulk toggle" route into 1 "bulk enable" and 1 "bulk disable" ? I'm not against it, I just want to understand the whole context

I was unable to add legacy links dynamically for single route:


AdminEmployees:submitBulk**disable**Selectionemployee


AdminEmployees:submitBulk**enable**Selectionemployee

**Comment by matks** [comment]
> > @tomas862 This PR does a lot more than just adding legacy links
> > Why did you choose to split the "bulk toggle" route into 1 "bulk enable" and 1 "bulk disable" ? I'm not against it, I just want to understand the whole context
> 
> I was unable to add legacy links dynamically for single route:
> 
> AdminEmployees:submitBulk**disable**Selectionemployee
> 
> AdminEmployees:submitBulk**enable**Selectionemployee

Oh, that's interesting. If we find more usecases like this, we might want to improve the _legacy_link feature to be able to provide an array of routes, not a single one.

ping @jolelievre FYI 😉

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @tomas862

**Pull request merged**
