### PR TITLE
Fixed filters date for orders tab

### PR DESCRIPTION
**Pull request by aleeks**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Fix filters (date) on the orders page |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1309 |
| How to test? | Do a search on orders tab with date |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by kpodemski** [comment]
https://github.com/PrestaShop/PrestaShop/commit/f19ae86bca6132b563564090bce1cf9308b71d98 

:D

**Comment by aleeks** [comment]
Hello !!
@kpodemski why your fix isn't in `develop` :(((
You can make it again and I close this PR ?

**Comment by kpodemski** [comment]
@aleeks good question, i think we have "few" bugfixes which are not on `develop` :-/

i'll make a PR in a second

**Comment by kpodemski** [comment]
#6425

**Comment by aleeks** [comment]
Thank you! i'm closing this PR :+1:

**Pull request closed without merging**
