### PR TITLE
Use media query inside responsive.js

### PR DESCRIPTION
**Pull request by Korri**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix some browsers (here chrome on Ubuntu gnome) which include the scrollbar width inside `$(window).width()` causing elements to be toggled at a different moment then the media query.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | Resize window in chrome ubuntu, theme isn't broken between `767px` and `782px` width

 I left the old variable (responsive.min_width and responsive.current_width) here in case some themes/plugin used them.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7728)

### CODE REVIEW

**Comment by ealvarez1990** [comment]
Good, I'm modifying the subject. I need 768px to apply mobile view. For that reason, I need to modify the responsive.js file but when I make changes these have no effect. In the Chrome inspector, this file is located in top / webpack: // and not in themes / classic / _dev / js

How can I change this file and make it work?

**Comment by Korri** [comment]
@nihco2 @eternoendless Any change to see this merged soon?

**Comment by eternoendless** [comment]
@marionf do you reproduce this on ubuntu?

**Comment by marionf** [comment]
@eternoendless no, I can't reproduce it

**Comment by eternoendless** [comment]
Looks like we can't reproduce the issue @Korri, sorry.

**Pull request closed without merging**
