### PR TITLE
Sort products in descending order

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | Sort products in descending order
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/STAB-79
| How to test?  | See products catalog

### CODE REVIEW

**Comment by aleeks** [comment]
Thank you @thierrymarianne

**Comment by vincentbz** [comment]
Thanks !

**Comment by AntoineMille** [comment]
Thanks, It's good for me

**Comment by aleeks** [comment]
Thank you @thierrymarianne

**Pull request merged**
