### PR TITLE
FO: If I type 0 as desired quantity, now the behavior is correct.

### PR DESCRIPTION
**Pull request by manfield**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Classic theme issue. The cart.js method: updateProductQuantityInCart does not take in consideration the case when user type 0 as desired quantity and behave in a wrong way. 
| Type?         | bug fix
| Category?     | FO 
| BC breaks?    | No
| Deprecations? | No
| How to test?  | Just open the cart after adding some products, then type 0 in the product_quantity_spin input

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10215)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
I dont understand what is the problem. If someone type `0`, it just delete the product from the cart.
@marionf any idea?

**Comment by manfield** [comment]
I noticed this issue happened under some circumstances.
I'm investigating.

**Comment by PierreRambaud** [comment]
I just noticed, are you using the latest 1.7.4.2?
Did you tried with #9405 ?

**Comment by manfield** [comment]
Yes, using 1.7.4.2.
Let me try #9405

**Comment by manfield** [comment]
I found the issue. 
It happens when you change the value twice:

- Try to add 20 products to the cart
- digit 18 in the input text
- then digit 0

**Comment by manfield** [comment]
By the way this pull request is wrong.

**Comment by manfield** [comment]
Ok it seems an issue with the controller. I will dig more and open an issue or ask for a merge request.

**Comment by manfield** [comment]
Yes, #9405 resolve this issue too. 
Thank you @PierreRambaud

**Comment by PierreRambaud** [comment]
Thanks to you for your feedback ;)

**Pull request closed without merging**
