### PR TITLE
[-] BO : Fix backoffice order with deleted address

### PR DESCRIPTION
**Pull request by Shoprunners**
If you want to add an order via backoffice and you have chosen an existing customer, his carts and orders are loaded. But if the address of the cart is not existing anymore (marked as deleted), there is no chance to edit it. This code change makes sure, that an existing backup address is loaded properly.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it mentions what the code change does? Using the PR's title would be great!

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by maximebiloe** [comment]
Hello @Shopmonauten,

Can you update your PR to respect PSR-2 standards, please?

Regards

**Comment by aleeks** [comment]
ping @vincentbz

**Comment by aleeks** [comment]
I cherry-pick your commit here https://github.com/PrestaShop/PrestaShop/pull/7504 rebase from develop.
Regards

**Pull request closed without merging**
