### PR TITLE
[+] FO : Add New hook display after opening body tag (usefull for mktg tag)

### PR DESCRIPTION
**Pull request by prestarocket**
Add new hook displayAfterBody after body tag: usefull for add tag like google tag manager

### CODE REVIEW

**Comment by xBorderie** [comment]
Well, remaking the PR also works ;) Thank you!

AND, you still won the prize for [4900th PR](https://github.com/PrestaShop/PrestaShop/pull/4900) ! :)

**Comment by prestarocket** [comment]
it was my goal !! ;) see you for the 9800th PR

**Comment by xBorderie** [comment]
Hahaha, see you soon then ;)

**Comment by djfm** [comment]
Why not use an already existing hook like `displayFooter`?

**Comment by prestarocket** [comment]
Some tags have to appears immediately after the opening <body> tag. Like google tag manager : 
https://developers.google.com/tag-manager/quickstart.

in addition, you should also add this feature (for allowing some js script not to be moved in footer) : https://gist.github.com/hereswhatidid/8c8edef106ee95138b03

**Comment by kpodemski** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
Hi,

> in addition, you should also add this feature (for allowing some js script not to be moved in footer) :

this is aready done, right ? => https://github.com/PrestaShop/PrestaShop/pull/3875/files

:+1: for this too, as we have nothing more to maintain from our side :)

**Comment by prestarocket** [comment]
@mickaelandrieu ok perfect it s already done for media.php
thx !!!

**Comment by xBorderie** [comment]
So, if I understand correctly, this PR can be closed, right?

**Comment by prestarocket** [comment]
yes you can merge it !! thx

**Comment by djfm** [comment]
Ok, but I'd like to find a less ambiguous name for the hook because when I read "displayAfterBody" I'm expecting it to be after the closing body tag (I know, it wouldn't make sense in practice).

I'd suggest:
- displayBeforeBodyContent
- displayAfterBodyOpeningTag
- displayImmediatelyAfterBodyOpeningTag (if that's the real purpose of the hook, let's be explicit)

What do you think?

**Comment by prestarocket** [comment]
yes, as you like; i prefer : displayAfterBodyOpeningTag

**Comment by Shudrum** [comment]
Let's go with `displayAfterBodyOpeningTag`!

I'll merge as soon as edited!

**Comment by xBorderie** [comment]
It's up to you, then, @prestarocket :)

**Comment by xBorderie** [comment]
Great, thanks!

**Comment by weikokzyl** [comment]
Need a hook for partial refund, after it, or wanted the date_upd to update after partial refund. 
Otherwise we have no idea when did the partial refund being conducted.

**Pull request merged**
