### PR TITLE
FO: Update jquery.scrollTo for Chrome 61

### PR DESCRIPTION
**Pull request by alexandre-stimpfling**
Since Chrome has changed to version 61 Jquery ScrollTo no longer works. For example, on the Command History page, the "Details" button no longer scrolls to the command. All ScrollTo use no longer works. After update to ScrollTo 2.1.2 it work again.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  "1.6.1.x" branch
| Description?  | PS 1.6.1.17, Chrome 61
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | No
| How to test?  | on the Command History page, the "Details" button no longer scrolls to the command

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8373)

### CODE REVIEW

**Comment by xBorderie** [comment]
Hello @alexandre-stimpfling !
I am curious as to where you found this v2.1.3?
As far as I can tell, the latest release is v2.1.2: https://github.com/flesler/jquery.scrollTo/releases

**Comment by alexandre-stimpfling** [comment]
Hello @xBorderie !

I have taken the version indicated in the header of the file jquery.scrollTo.min.js but in the meantime the developer has just corrected the version indicated in this file by going back to 2.1.2...
See the following commit:
https://github.com/flesler/jquery.scrollTo/commit/9785f37301f7b770d977898b976c7b61006e81e9#diff-215a7eeb533376626558f487408d8659

You are right, the current version is 2.1.2. :wink:
I will correct my first post.

**Comment by xBorderie** [comment]
Thanks for the pointer!
For clarity's sake, maybe also update the code to the corrected version?

**Comment by alexandre-stimpfling** [comment]
Yes you are right. It is done. 😉

**Comment by xBorderie** [comment]
Thanks a lot! The Core team will have a look at your PR soon.

**Comment by alexandre-stimpfling** [comment]
Perfect, thank you for your return. Have a good day.

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
