### PR TITLE
Combine two equal adjacent selectors

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | avoid CSS overcomplication.
| Type?         | refacto
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | generated CSS after and before the changes are the same

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15277)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
One more review and merge. No need QA here

**Comment by matks** [comment]
@NeOMakinG please review 😉

**Comment by davidglezz** [comment]
Should I compile the assets?

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
I compile these almost everyday, it should be fine ;)

Thanks

**Comment by PierreRambaud** [comment]
Closed and reopened for travis  :) waiting for CI and merge

**Comment by NeOMakinG** [comment]
Thanks @davidglezz :)

**Pull request merged**
