### PR TITLE
Fixed typo in wording in modal.tpl

### PR DESCRIPTION
**Pull request by Magicalname**
Fix Display Error if only 1  Product in Cart

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Just a Typo.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | No need QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21407)

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hi @Magicalname I dont understand this Pull Request. There is a dedicated block line 61 for the case "products_count equal to 1", with your PR it becomes useless. Can you explain the PR goal ?

**Comment by matks** [comment]
@Magicalname Also please fill in the template https://github.com/PrestaShop/PrestaShop/blob/develop/.github/PULL_REQUEST_TEMPLATE.md it does provide important informations for us to review the PR

Thanks 😉

**Comment by Magicalname** [comment]
> Hi @Magicalname I dont understand this Pull Request. There is a dedicated block line 61 for the case "products_count equal to 1", with your PR it becomes useless. Can you explain the PR goal ?

Because it fix this issue for me if you only have 1 Product in Cart

2020-10-12_21h01_25

Thank you....You are right it makes the function useless...The dedicated block line 61 is the Problem....i updated my changes the Error is caused by a typo in line 61

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thanks for the changes @Magicalname PR has now moved to QA validation step

**Review by matks — DISMISSED** [review]
On 2nd thought... @Progi1984 @atomiix this PR does not modify the behavior. It renames a placeholder being used inside a translation string.

So it does not fix a bug, it does not modify/improve the behavior ... but it will modify the translation string being used (IF placeholders are part of the string key - need to be sure) which will require the translators for all PS languages (up to 60 ? 100 ? 150 ?) to introduce a new string.

Is it really a good move ? 🤔

**Comment by PierreRambaud** [comment]
> On 2nd thought... @Progi1984 @atomiix this PR does not modify the behavior. It renames a placeholder being used inside a translation string.
> 
> So it does not fix a bug, it does not modify/improve the behavior ... but it will modify the translation string being used (IF placeholders are part of the string key - need to be sure) which will require the translators for all PS languages (up to 60 ? 100 ? 150 ?) to introduce a new string.
> 
> Is it really a good move ?

Yes, we must be consistent in our code and translations. Even if it costs time to repair some translations.

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
Thank you @Magicalname

**Pull request merged**
