### PR TITLE
Fix a typo in README.md file

### PR DESCRIPTION
**Pull request by SimonGrn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fix a typo in README
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20822)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]
You should save this kind of PR for Hacktoberfest 😛 easy win !

**Comment by Progi1984** [comment]
But PHPCSFixer is :red_circle:

**Comment by matks** [comment]
> But PHPCSFixer is 🔴

Unless @SimonGrn has super powers, he cannot have his PR refused by PHP CS Fixer by modiying MD files 😄

**Comment by SimonGrn** [comment]
> 
> You should save this kind of PR for Hacktoberfest 😛 easy win !

Oh no that's a terrific idea, I should have done that :(

> 
> > But PHPCSFixer is 🔴
> 
> Unless @SimonGrn has super powers, he cannot have his PR refused by PHP CS Fixer by modiying MD files 😄

If only... what can I do to fix this ? Or maybe we ask @eternoendless to bypass the PHP CS Fixer tests ?

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
