### PR TITLE
Deleting files marked as "to be deleted in 1.8"

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove three files marked as "to be removed in 1.8" aka, 8.0
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | no
| How to test?      | 
| Possible impacts? | If specific modules or developments of certain shops use these classes directly

### BC Breaks

Removed class `src/Adapter/ClassLang.php`
Removed class `src/PrestaShopBundle/Form/Admin/Type/TextEmptyType.php`
Removed class `src/PrestaShopBundle/Form/Admin/Type/TextareaEmptyType.php`

### CODE REVIEW

**Review by matks — APPROVED** [review]
Woups these files went off the radar during the clean for 8.0 😅 

At least they'll be gone for PS 8.1 👍

**Comment by matks** [comment]
@Sinepel Even if this is _expected_ we need to inform people "we removed these files" 😄 can you please add the BC break description?

**Comment by Progi1984** [comment]
@Sinepel Why not target the 8.0.x branch ? I believe that we can't remove classes in minor version. It's not compatible with semver.

**Comment by Sinepel** [comment]
@matks It's OK !

**Comment by Sinepel** [comment]
@Progi1984 Considering it was a BC Breaks, I thought it was too late to include it at this stage in 8.0.0 :)

Should it be changed?

**Comment by Progi1984** [comment]
Only @PrestaShop/prestashop-maintainers have the control on this decision.

**Comment by matks** [comment]
Apologies @Sinepel I did not look closely at the branch

> Considering it was a BC Breaks, I thought it was too late to include it at this stage in 8.0.0 :)

You're right.

I think it's too late for this one. Maybe we mark these files to be deleted in prestashop 9.0.0 instead?

**Comment by Sinepel** [comment]
@matks  
> I think it's too late for this one. Maybe we mark these files to be deleted in prestashop 9.0.0 instead?

As you prefer, if it's better to do it that way, let's go.

I am waiting for your confirmation

**Review by Amoifr — COMMENTED** [review]
Thx, good catch

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/4066725799

**Comment by nicosomb** [comment]
@kpodemski : do you think that the failing tests are related to this PR? I don't think so. In my opinion, we can merge.

**Comment by lartist** [comment]
It seems like a rebase is needed: https://github.com/lartist/ga.tests.ui.pr/actions/runs/4788537360

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Sinepel ,

Even after the rebase, it seems like your PR breaks the automated tests. I have relaunched them multiple times.
https://github.com/florine2623/testing_pr/actions/runs/5001093966

Could you check what is wrong ?
Thanks!

**Comment by kpodemski** [comment]
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
