### PR TITLE
[+] Add cacheMemcached (derived from #3086)

### PR DESCRIPTION
**Pull request by jocel1**

### CODE REVIEW

**Comment by drzraf** [comment]
I'm generally fine with the pull-request dev mode, but I noticed that:

- I originally submitted, as far as I can tell, a well-formed and well-suited pull-request
- you didn't explained why a "derived" pull-request was necessary (especially since AFAICT it was finally the very same diff as the original PR submission)
- it kept me from adding (possible) later commits to the initial pull-request (unless I overlooked how to do this)
- I forgot to fix the @author and copyright years comment/fields in the original ```CacheMemcached.php``` header (copy/pasted). Since the licence is OSL 3.0 there's no reason for not having correct authorship and copyright year (neither was updated CONTRIBUTORS.md)
- pull-request "derivation", in this case,, does not make the workflow more robust, eg: the "_missing_ changes in controllers" added in the 2nd commit of the pull request, in 97d4bd4, were already a part of the initial pull-request.

May I ask you, at least, a workflow / "pull-flow" clarification?

**Comment by drzraf** [comment]
...and this is especially disturbing since you're dedicated and makes money from php/mysql optimization (softizy.com/blog/prestashop-1-6-1-0-performances/) while this work has been done partly on my free time and partly on the time dedicated by and for an NGO.
@jeromenadaud in my opinion PrestaShop mergers should take care about such things

**Comment by drzraf** [comment]
Should I really provide a (provocative) pull-request fixing authorship and copyright attribution of the file I wrote in order to get attention on this issue?

**Comment by jeromenadaud** [comment]
Hi @drzraf, @jocel1 PR was preferred and merged because it was more complete than your.
As @jocel1 told you it was important to remove key system and implement delete method.

But keep contributing, we will merge your Pull Request.

Best regards

**Comment by drzraf** [comment]
@jocel1, after saying in a comment that:
 > _writeKeys() is not doing anything as well
... introduced it.
* This is, if not wrong, at least misleading since the return value of _writeKeys() is never used by the callers and it was exactly the reason why I kept it defined while keeping it a no-op in my PR.
* I postponed the implementation of delete() waiting for opinion about wildcards handling and didn't received any suggestion on this matter (obviously it would have been simpler to just copy/paste CacheMemcache.php code)
* Moreover the initial retrieval of the keys ```$this->keys = array_flip($this->memcached->getAllKeys());``` leading to ```isset($this->keys[$key]);``` in exist() was removed from @jocel1 PR without any explanation.

```diff https://patch-diff.githubusercontent.com/raw/PrestaShop/PrestaShop/pull/3086.diff https://patch-diff.githubusercontent.com/raw/PrestaShop/PrestaShop/pull/3243.diff```

The use of OSL is one thing, but authorship is another:
> @author PrestaShop SA <contact@prestashop.com> 
> @copyright  2007-2015 PrestaShop SA
are plain wrong. A look at any file in any other free software project give an idea of how it's wrong. My insistence here is; I think, proportional to the business aims I suspect in these changes.

Issues I raised in my previous post were not addressed, eg: ability to add to another existing PR [what, if possible, could have done @jocel1]

Anyway I hope not to encounter this again.

**Comment by jocel1** [comment]
@drzraf : I've removed the $this->keys from the memcached & APC implementation, because : 

- getting all the keys from memcached could be slow
- the cost of maintaining this array is too high (it's big, and with each update it has to be updated, and stored back into memcached)

**Comment by drzraf** [comment]
On Tue, Jul 28, 2015 at 07:21:31AM -0700, Jocelyn Fournier wrote:
> @drzraf : I've removed the $this->keys from the memcached & APC implementation, because : 
> - getting all the keys from memcached could be slow
> - the cost of maintaining this array is too high (it's big, and with
>   each update it has to be updated, and stored back into memcached)

ok. This makes sense.

**Pull request merged**
