### PR TITLE
Fixed wrong discount table

### PR DESCRIPTION
**Pull request by SnaKKo**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Product discounts based on quantity showed incorrect prices
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14199)

### CODE REVIEW

**Comment by matks** [comment]
Hi @SnaKKo thanks for the contribution ! Do you have an example of a scenario where the price displayed was wrong (and this PR fixes it) ? It would help us to valide the code modification 😉

**Comment by SnaKKo** [comment]
Hi @matks, tomorrow I will give you all the details.

**Comment by SnaKKo** [comment]
Hi @matks, this is the scenario to replicate the bug:

1) Go to "Shop parameters" -> "Product Settings" -> set "Display discounted price" to "Yes" (to display the new price with the applied discount instead of showing the discount (ie. "-5%"))

2) Set "Catalog Price Rules" as follows:

1_catalog_price_rules

3) Go to the product page and you'll see the table with wrong prices:

2_wrong_table

*) After the patch the prices are right:

3_fixed_table

**Comment by PierreRambaud** [comment]
Hi @SnaKKo  and sorry for the delay.
Are you able to continue this PR? If yes, could you please create an issue in order to help the QA and product teams to understand what is your problem and how we can improve the code?

Kind regards

**Comment by PierreRambaud** [comment]
Hi @SnaKKo ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
