### PR TITLE
Use default state for tax purposes

### PR DESCRIPTION
**Pull request by aleeks**
In countries with two level of taxes, it is interesting to give an estimate of taxes based on the shop location and applying also the state tax.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In countries with two level of taxes, it is interesting to give an estimate of taxes based on the shop location and applying also the state tax.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  |  -

See: https://github.com/PrestaShop/PrestaShop/pull/4415

### CODE REVIEW

**Comment by cedricfontaine** [comment]
Problem is that Address:Initialize is not used everywhere and some classes initialize adress by their own and don't use the default state.

**Comment by aleeks** [comment]
Hello @cedricfontaine, do you mean this fix isn't working ?

**Comment by cedricfontaine** [comment]
Well it's working but it's not enough in the latest code.

**Comment by aleeks** [comment]
Rebased to be like Shop.php

**Comment by antoin-m** [comment]
Thank you @aleeks @cedricfontaine :muscle:

**Pull request merged**
