### PR TITLE
Fixed display of Vouchers id in Customer View

### LINKED ISSUE #27924: [BO] Bad display of Vouchers id in Customer View
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I notice that the Id column is too tight, to a point where an id (composed of two digits like 10) will be split.

image

### Expected behavior

It should be displayed in same line

### Steps to reproduce

1. BO>SELL>Catalog>Discounts
2. Create more than 10 discounts
3. BO>SELL>Customers>Customers
4. Click on View Customer
5. Check the Vouchers block
6. See error > the IDs composed of two digits like 10 are splitted

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed display of Vouchers id in Customer View
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27924
| How to test?      | Cf. #27924

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28019)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Blocked by https://github.com/PrestaShop/PrestaShop/issues/27119

**Comment by Progi1984** [comment]
@florine2623 It's unlocked :)

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Thanks for the PR, it is looking good :)
It is QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
