### PR TITLE
Add context mocker for front controller tests

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Context mock helper class for testing
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
The new class is defined but not used. It this PR still a work in progress?

**Comment by eternoendless** [comment]
Actually it should be rebased into 1.7.2.x. I had @tomlev push it as a separate PR so that he could use elsewhere.

**Comment by Quetzacoalt91** [comment]
We are lucky, no need to rebase here.

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @tomlev

**Pull request merged**
