### PR TITLE
Fix typo in LayoutExtension

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix typo in LayoutExtension
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23615)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — DISMISSED** [review]
Please fill the table

**Comment by matks** [comment]
> Please fill the table

OMG bro

**Review by matthieu-rolland — APPROVED** [review]
LGTM code-wise !

**Comment by Progi1984** [comment]
> > Please fill the table
> 
> OMG bro

In this case, please do not ask other contributors ;)

**Pull request merged**
