### PR TITLE
Add a display hook in the address step just like other checkout step

### LINKED ISSUE #30666: Add a display hook in the address step just like other checkout step
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There is no possibility to add something (message) on address step of checkout.
So we suggest please add a display hook in the address step also just like other checkout steps.

### Describe the solution you'd like

We must provide a hook in address step of checkout page

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | There is no possibility to add something (message) on address step of checkout.So we suggest please add a display hook in the address step also just like other checkout steps.
| Type?             | new feature
| Category?         | FO 
| BC breaks?        |no
| Deprecations?     |no
| Fixed ticket?     | Fixes #30666 
| Related PRs       | Theme PR: https://github.com/PrestaShop/classic-theme/pull/92 Autoupgrade module PR:https://github.com/PrestaShop/autoupgrade/pull/543
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by FabienPapet — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello everybody,

This current PR should be tested with both other PRs [#classic-theme/pull/92](https://github.com/PrestaShop/classic-theme/pull/92) and [#autoupgrade/pull/543](https://github.com/PrestaShop/autoupgrade/pull/543)  Or they should be tested separately?


I think that this current PR should be tested at the same time with the [#classic-theme/pull/92](https://github.com/PrestaShop/classic-theme/pull/92) PR. Cause, for now, the behavior with PR is the same as without PR.

Waiting for your feedback!

**Comment by kpodemski** [comment]
@HanaRebaiQA 

You need to test it with the theme's PR, otherwise, you won't see anything in the front office.

**Comment by HanaRebaiQA** [comment]
Thank you @kpodemski 
Exactly yes! Could you please add the `Waiting for QA` label for the theme's PR?

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @Amit-Kumar-Tiwari-Webkul 

I have checked this PR in parallel with the classic theme's [PR](https://github.com/PrestaShop/classic-theme/pull/92)
But, it seems that the new feature in the `Addresses` step is not added. I did not see any changes. 


https://user-images.githubusercontent.com/92912932/209645406-a552c1f7-8fa4-403d-9297-0a8ba778503f.mp4


Could you please check and feedback?

Thank You!

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@HanaRebaiQA , To display data, It must be called by module

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@hibatallahAouadni , I'd suggest please provide a hook definition from any module (like blockreassurance module) like below
```php
public function hookDisplayAddressSelectorBottom()
{
   return 'test hook';
}
```

**Comment by kpodemski** [comment]
@HanaRebaiQA you could use quality assurance module to test it :)

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @kpodemski 

I have checked again using the quality assurance module [ps_qualityassurance.zip](https://github.com/PrestaShop/PrestaShop/files/10307712/ps_qualityassurance.zip), and i used these codes to can display the data : 

-The provided code by @Amit-Kumar-Tiwari-Webkul 
```

public function hookDisplayAddressSelectorBottom()
{
   return 'test hook';
}
```

-This code  : 

```
dump($params);
die;
```
https://user-images.githubusercontent.com/92912932/209658181-94889a3d-349d-4076-8f77-a1e6064ba3fc.mp4

Could you please provide us with the exact steps to test? and what is the exact expected behavior of the feature?



Thank You!

**Comment by kpodemski** [comment]
Hello @HanaRebaiQA 

I think it'd be better if you could discuss with someone else from @PrestaShop/qa-team to send you information how to test new hooks. I'm sure QA have this documented somewhere.

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
@HanaRebaiQA 
Please check the attached video, I show you step to test with QA module

[url](https://user-images.githubusercontent.com/42021740/209766499-888eb8e9-6b4a-4972-a9ff-db700f9d9566.webm)

**Comment by HanaRebaiQA** [comment]
Hello @Amit-Kumar-Tiwari-Webkul 

Thank you for your feedback!
We are waiting for the PM approval on the issue as mentioned [here](https://github.com/PrestaShop/PrestaShop/issues/30666#issuecomment-1365902193) before testing it again.

**Comment by MatShir** [comment]
LGTM ✅, you can test it @HanaRebaiQA.
Don't hesitate to ping at @PrestaShop/product-team and on slack #project-member so we can quickly reply ;)

**Review by HanaRebaiQA — APPROVED** [review]
Hello @Amit-Kumar-Tiwari-Webkul 

I have checked your PR again. The feature is well added when using the `DisplayAddressSelectorBottom` for the Addresses step of the checkout process.
My previous fault is that the hook name that I used is preceded by the word `hook` like this: `hookDisplayAddressSelectorBottom`

-Check the automated tests: OK
-Check with different codes: using the dump and the return methods: OK
-Check with multistore (new shop and new group of shop): OK 
-Check with different PHP versions (php7.2 and php8.1) : OK
-Check with different languages (RTL and no RTL) : OK
-Check with different browsers:  OK

image

image

https://user-images.githubusercontent.com/92912932/209790023-147f2bd0-9d84-4100-a8db-ba12eb5948a4.mp4

So, it's QA :heavy_check_mark: 

Thank You!

**Comment by kpodemski** [comment]
Thanks @Amit-Kumar-Tiwari-Webkul 

Thanks @HanaRebaiQA for the tests :)

**Comment by thomasnares** [comment]
You can remove "needs documentation" label

**Comment by Hlavtox** [comment]
@kpodemski Please don't remove `Needs autoupgrade PR` label before that PR is merged. 👍

**Comment by kpodemski** [comment]
@Hlavtox, IMHO we should have a way to mark this `autoupgrade` PR as required in `autoupgrade` repo, but we we can also see merged PRs with a milestone and this label there, in the core repo, so ok.

**Pull request merged**
