### PR TITLE
In BackOffice, fixed mismatch between legacy and new theme for RTL languages

### LINKED ISSUE #26017: [BO] Mismatch between default-theme and new-theme for RTL languages
Hello,

#### Describe the bug

There is two themes for back-office, default and new-theme:
public_html/admin/themes/default
public_html/admin/themes/new-theme

Some pages works with default-theme and some pages works with new-theme.
I checked RTL version of default-theme and new-theme source codes (theme.rtlfix) and i found some problems:
1. Mismatch: Some CSS rules not exported from default-theme to new-theme (Rules that fixes RTL direction and Persian Fonts definition)
2. Outdated: Persian fonts defined in default-theme are outdated and need to update (Used: V18, Current: [V30](https://github.com/rastikerdar/vazir-font))

#### Expected behavior

Themes should to be synchronized to looks same everywhere in back-office.

#### Steps to Reproduce

(1) Steps to reproduce the behavior (**Arabic/Persian**):

1. Go to BO > Products
2. Edit a product
3. See categories list

(2) Steps to reproduce the behavior (**Persian**):
_(Persian language needs to be selected as default language for BO)_

1. Go to BO > Employees
2. Edit Admin account
3. Select Persian for language
4. See the main menu font (new-theme)
5. Go to BO > Dashboard
6. See the main menu font (default-theme)

Different font faces for different pages:

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixes RTL problems in BO (Arrow directions, TinyMCE menu, Categories list, Attributes list and Page navigation). Upgrade Persian language font-face and matching between legacy and new theme.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26017
| How to test?      | The Admin language for the font-face testing must be set to Persian. Other fixes also are visible in Arabic languages.
| Possible impacts? | -

#### Modifications made:

1. All BO pages has matched font-face for Persian language.
2. BO > Catalog > Categories > Select a category
2.1. The "more" icon in category-list section has correct direction.
3. BO > Catalog > Products > Select a product
3.1. Checkbox in attributes-list section placed in right direction.
3.2. Dropdown menu in TinyMCE editor placed in correct position.
4. BO > Catalog > Products
4.1. Page navigation items (next and previous icons) has correct direction.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26147)

### CODE REVIEW

**Comment by mparvazi** [comment]
A redo for PR #26038

**Review by matks — DISMISSED** [review]
Thank you @mparvazi this PR structure is good 😉  

I'm not a great frontend developer so I will request the skilled eyes of @NeOMakinG to validate the content

**Review by NeOMakinG — DISMISSED** [review]
Already approved before

**Comment by mparvazi** [comment]
> 
> 
> Thank you @mparvazi this PR structure is good 😉
> 
> I'm not a great frontend developer so I will request the skilled eyes of @NeOMakinG to validate the content

Thank you @matks 
I look forward to confirming my first contribution on PS 😄

**Comment by NeOMakinG** [comment]
> > Thank you @mparvazi this PR structure is good 😉
> > I'm not a great frontend developer so I will request the skilled eyes of @NeOMakinG to validate the content
> 
> Thank you @matks I look forward to confirming my first contribution on PS 😄

The QA should test your PR now, after it, if they confirm that everything works fine, your PR will get merged :)

Don't forget, it's hacktoberfest!! This means that if you submit 3 more PRs and if they are validated, you can get a t-shirt or maybe plant a tree! https://hacktoberfest.digitalocean.com/

**Comment by mparvazi** [comment]
Fix dropdown menu text overflow.

BO > Products > Category filter

dropdown

```
/* Fix dropdown menu text overflow */
.dropdown-menu.show {
  right: 0px;
  left: auto !important;
}
```

**Review by NeOMakinG — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @mparvazi,

1. I re-installed this PR with English language & France country (after rebuilding assets: `make install`)
image
2. I used an incognito browser
3. I added the Arabic language from the BO > International > Translations page
4. I changed the employee language to Arabic
5. On the BO > Catalog > Products page, I have the same issue 
image

Thanks to check and feedback.

**Comment by mparvazi** [comment]
Hello @khouloudbelguith 

drop

**Comment by mparvazi** [comment]
Second test:
1. I build a PS by this PR changes
2. I Installed PS with English language
3. I added Arabic language (theme_rtl.css created **automatically** with expected changes from theme.rtlfix)
4. I changed the employee language to Arabic
5. BO > Catalog > Products

Same result in Firefox and Chrome:

**Firefox**
firefox

**Chrome**
chrome

**Comment by NeOMakinG** [comment]
@khouloudbelguith building assets isn't enough, you need to generate the RTL stylesheet (I think there is an option in the BO)

**Comment by khouloudbelguith** [comment]
Hi @mparvazi,

Thanks for your feedback.
I rechecked the issue with @NeOMakinG.
I regenerated the RTL files and it is ok.
I will retest this PR :slightly_smiling_face: 

Thanks!

**Comment by khouloudbelguith** [comment]
@mparvazi, I found an issue with this PR in all migrated pages with a list.
If we click on the ` dropdown-toggle` => NOK the display

image

Without PR => ok
image

Thanks!

**Comment by mparvazi** [comment]
@khouloudbelguith You're very accurate in finding mistakes 😄

Fixed!

`.dropdown-menu.show` => `.dropdown-menu[x-placement="bottom-start"].show`

Just effects on the menu at the right side.

https://watch.screencastify.com/v/p37SX2peLsbb3HadorDA

Please check again.

**Comment by NeOMakinG** [comment]
> @khouloudbelguith You're very accurate in finding mistakes 😄
> 
> Fixed!
> 
> `.dropdown-menu.show` => `.dropdown-menu[x-placement="bottom-start"].show`
> 
> Just effects on the menu at the right side.
> 
> https://watch.screencastify.com/v/p37SX2peLsbb3HadorDA
> 
> Please check again.

Yeah, Khouloud does a great job!

**Review by NeOMakinG — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
@mparvazi, sorry I found some other issue related to the RTL,

1. Employee language is RTL (Arabic)
2. Go to BO > Catalog > Products > Edit a product with combinations
3. Edit a combination
4. The icon of **next** and **previous** are NOK 
image

Also, when we click on the icon of the Marchandise Expertise => no dropdown is displayed
image

If the employee language = English => we have this 
image

PS: I checked the font-family with Persian => ok

- I checked those pages with RTL:
- Categories page
- Add a new page
- Add a new category page
- Translate page
- Category page

Thanks!

**Comment by mparvazi** [comment]
@khouloudbelguith Thanks for feedback. 

You mentioned two problems that need to be solved separately:

**1. First problem** (The icons of next and previous in the product combination section)
`<i class="material-icons">keyboard_arrow_right</i>`
The problem known as Bidirectionality in Material Icons:
https://material.io/design/usability/bidirectionality.html#mirroring-elements

Mirroring with CSS is a solution and below code will fix the problem:
⚠ BUT some icons shouldn't be mirrored (e.g. refresh icon and history icon). This code will mirror all icons and it is not good!
```
.material-icons {
    transform: scaleX(-1);
}
```
**My suggestion**
I think just fixing specific and major bugs, is not a bad idea!
The elements that I found:
```
.next .material-icons,
.prev .material-icons,
.btn-back .material-icons,
.order-navigation-right .material-icons,
.order-navigation-left .material-icons,
.menu-collapse .material-icons,
.order-preview-content .btn .material-icons,
.configure-link .material-icons {
    transform: scaleX(-1);
}
```

Screenshot 2021-10-21 003653


**2. Second problem** (The Merchant Expertise menu)
That's related to the gamification module. Using `!important` for some CSS rules in this module, prevents overriding for RTL in public theme (theme_rtl.css).

**My suggestion**
Adding below code in `gamification.css` will fixes the problem:
PrestaShop/tests-legacy/resources/modules/gamification/views/css/gamification.css 
```
/* RTL Fix */
.gamification-component #gamification_notif .dropdown-menu,
.bootstrap #header_infos #gamification_notif .dropdown-menu {
  transform: translate3d(324px, 20px, 0px) !important;
}
#gamification_notif .dropdown-menu:before,
#gamification_notif .dropdown-menu:after {
  left: 9px;
  right: auto !important;
}
```
https://watch.screencastify.com/v/eYsZltFtcXgQ7if1cAMK

I don't know if I should make this change as a commit in this PR or not?
🤔

**Comment by NeOMakinG** [comment]
@mparvazi You can if you want, it's the subject, but if you don't want, you already fixed what you seen and it can be inside another PR as it's not really related

**Comment by mparvazi** [comment]
@NeOMakinG Is this path correct for modification?
PrestaShop/tests-legacy/resources/modules/gamification/views/css/gamification.css

**Comment by NeOMakinG** [comment]
> @NeOMakinG Is this path correct for modification? PrestaShop/tests-legacy/resources/modules/gamification/views/css/gamification.css

Oh, I think it's better to fix it inside the gamification module directly. This path is totally wrong and the style is directly linked to this module, don't worry, this PR looks fine already to me!

**Comment by mparvazi** [comment]
@NeOMakinG OK, I'll just commits changes that needed due to the first issue has found by @khouloudbelguith https://github.com/PrestaShop/PrestaShop/pull/26147#issuecomment-947845569

**Review by NeOMakinG — APPROVED** [review]

**Comment by mparvazi** [comment]
@Progi1984 Can you please add this code in the gamification module
`gamification/views/css/gamification.css `
It will fixes the second problem (Merchant Expertise) that mentioned here: https://github.com/PrestaShop/PrestaShop/pull/26147#issuecomment-947845569
I don't know how to contribute on PS modules!

```
/* RTL Fix */
.gamification-component #gamification_notif .dropdown-menu,
.bootstrap #header_infos #gamification_notif .dropdown-menu {
  transform: translate3d(324px, 20px, 0px) !important;
}
#gamification_notif .dropdown-menu:before,
#gamification_notif .dropdown-menu:after {
  left: 9px;
  right: auto !important;
}
```

**Comment by NeOMakinG** [comment]
@mparvazi thanks a lot for every contribution you're doing the past few days :)

https://github.com/PrestaShopCorp/gamification

Here is the repository of the gamification module, it's the same process as PrestaShop except that you need to clone the fork of your module inside the `modules` folder

If you don't want to do it, don't hesitate to create an issue so it won't be lost in that discussion ;)

**Comment by mparvazi** [comment]
Hello @NeOMakinG 

I found the main problem about RTL theme in BackOffice:
prestashop\admin\themes\new-theme\public
Screenshot 2021-10-26 004701
For each CSS file, a RTL version of CSS created automatically after PS build.

BUT the RTL version doesn't call in BackOffice when employee's default language is RTL (Just theme_rtl.css used).

For example for Orders page:
prestashop\src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\index.html.twig
```
{% block stylesheets %}
  <link rel="stylesheet" href="{{ asset('themes/new-theme/public/orders.css') }}" type="text/css" media="all">
{% endblock %}
```

Problem will be solved by changing some files:

Adding RTL variable:
prestashop\src\PrestaShopBundle\Twig\LayoutExtension.php
```
return [
     'is_lang_rtl' => $this->context->getContext()->language->is_rtl,
];
```

Then using this var in twig files:
prestashop\src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\index.html.twig
```
{% if not is_lang_rtl %}
   <link rel="stylesheet" href="{{ asset('themes/new-theme/public/orders.css') }}" type="text/css" media="all">
{% else %}
   <link rel="stylesheet" href="{{ asset('themes/new-theme/public/orders_rtl.css') }}" type="text/css" media="all">
{% endif %}
```

These changes will fixes main RTL problems and reduces CSS modification.

**Comment by NeOMakinG** [comment]
@mparvazi ohhh! Good catch, this is something we changed in 1.7.8 or something like this, we split some bundles in order to avoid unused CSS on different pages

Could you create an issue about what you found? I may take it, or another contributor!

**Comment by mparvazi** [comment]
@NeOMakinG  OK, I will create an issue about that.

But I think this PR must be paused until new issue get reviewed and confirmed. Because some of changes in rtlfix files that I've made will become duplicated and must be removed.

**Comment by NeOMakinG** [comment]
> @NeOMakinG OK, I will create an issue about that.
> 
> But I think this PR must be paused until new issue get reviewed and confirmed. Because some of changes in rtlfix files that I've made will become duplicated and must be removed.

Looks ok :)

**Comment by mparvazi** [comment]
@NeOMakinG I need to know your opinion:

**Problem**
Sample => Invalid arrow direction, it must be left for RTL

Screenshot 2021-10-29 125132

**Easy and fast solution**
Using special rule: 
```
.configure-link .material-icons {
  transform: scaleX(-1);
}
```
But in the future with possible changes in BO, more of this may happen (Using arrow_right_alt in another class). In this case, a new CSS rule must be added for each class.

**Clean solution**
For material icons that needed to be mirrored for RTL, adding icon's content to the class:
`<i class="material-icons">arrow_right_alt</i>` => `<i class="material-icons arrow_right_alt">arrow_right_alt</i>`
```
.material-icons .arrow_right_alt {
  transform: scaleX(-1);
}
```
In this case we have one CSS rule that can be used for all cases in templates.


**Google suggestion:**
Full list of icons that should be mirrored, but i think focusing on direction icons is enough.
http://google.github.io/material-design-icons/#which-icons-should-be-mirrored-for-rtl-


**Which one is better?**

1. Adding CSS rules for each special cases without template modification (Current solution)
2. Modifying templates by adding the icon's content to the icon's class and using one CSS rule for all occurrences (More work but more clean).

**Comment by NeOMakinG** [comment]
> @NeOMakinG I need to know your opinion:
> 
> **Problem** Sample => Invalid arrow direction, it must be left for RTL
> 
> Screenshot 2021-10-29 125132
> 
> **Easy and fast solution** Using special rule:
> 
> ```
> .configure-link .material-icons {
>   transform: scaleX(-1);
> }
> ```
> 
> But in the future with possible changes in BO, more of this may happen (Using arrow_right_alt in another class). In this case, a new CSS rule must be added for each class.
> 
> **Clean solution** For material icons that needed to be mirrored for RTL, adding icon's content to the class: `<i class="material-icons">arrow_right_alt</i>` => `<i class="material-icons arrow_right_alt">arrow_right_alt</i>`
> 
> ```
> .material-icons .arrow_right_alt {
>   transform: scaleX(-1);
> }
> ```
> 
> In this case we have one CSS rule that can be used for all cases in templates.
> 
> **Google suggestion:** Full list of icons that should be mirrored, but i think focusing on direction icons is enough. http://google.github.io/material-design-icons/#which-icons-should-be-mirrored-for-rtl-
> 
> **Which one is better?**
> 
> 1. Adding CSS rules for each special cases without template modification (Current solution)
> 2. Modifying templates by adding the icon's content to the icon's class and using one CSS rule for all occurrences (More work but more clean).

I wouldn't even play with CSS on this... We've an rtl variable, this means that we can change the markup based on the templating generation, we can add some conditions to it

The right way would be => creating a twig component which would be called MaterialIcon, which takes 2 parameters => rtlIcon, ltsIcon, and the condition into it

**Comment by mparvazi** [comment]
@NeOMakinG 

LayoutExtension.php
```
public function icon($material_icon) 
{
	if (!$this->context->getContext()->language->is_rtl)
		return $material_icon;
	switch ($material_icon) {
		case 'arrow_right_alt':
			$material_icon = 'arrow_left_alt';
			break;
		case 'arrow_left_alt':
			$material_icon = 'arrow_right_alt';
			break;
		case 'chevron_right':
			$material_icon = 'chevron_left';
			break;
		case 'chevron_left':
			$material_icon = 'chevron_right';
			break;
	}
	return $material_icon;
}
```

Template file (twig files)
```
<i class="material-icons">{{ icon('arrow_right_alt') }}</i>
```

**Problem:**
But some icons used in .vue files and there is no access to $context for language.
themes\new-theme\js\vue\components\Pagination.vue
_Product V2 combinition edit modal_

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> LayoutExtension.php
> 
> ```
> public function icon($material_icon) 
> {
> 	if (!$this->context->getContext()->language->is_rtl)
> 		return $material_icon;
> 	switch ($material_icon) {
> 		case 'arrow_right_alt':
> 			$material_icon = 'arrow_left_alt';
> 			break;
> 		case 'arrow_left_alt':
> 			$material_icon = 'arrow_right_alt';
> 			break;
> 		case 'chevron_right':
> 			$material_icon = 'chevron_left';
> 			break;
> 		case 'chevron_left':
> 			$material_icon = 'chevron_right';
> 			break;
> 	}
> 	return $material_icon;
> }
> ```
> 
> Template file (twig files)
> 
> ```
> <i class="material-icons">{{ icon('arrow_right_alt') }}</i>
> ```
> 
> **Problem:** But some icons used in .vue files and there is no access to $context for language. themes\new-theme\js\vue\components\Pagination.vue _Product V2 combinition edit modal_

Don't we have an rtl var on `window`? Overwise we could check for the body class/attr and do a vue component

**Comment by mparvazi** [comment]
@NeOMakinG 

I found another issue:

For some icons, we don't have any reverse version:
`arrow_right_alt`
outline_arrow_right_alt_black_24dp
`arrow_left_alt` doesn't exist!

Choosing similiar icon is fine? (Leads to different views between RTL and LTR)
`keyboard_backspace`
outline_keyboard_backspace_black_24dp

What about icons that doesn't have any similar pair? 

By the way using of CSS will works fine for `vue` and `twig` templates.

**Comment by mparvazi** [comment]
**The list of icons that must be mirrored for RTL**

chevron_left
```
admin-dev\themes\default\template\nav.tpl(3)
admin-dev\themes\default\template\nav.tpl(4)
admin-dev\themes\new-theme\js\vue\components\Pagination.vue(33)
admin-dev\themes\new-theme\template\components\layout\nav_bar.tpl(27)
admin-dev\themes\new-theme\template\components\layout\nav_bar.tpl(28)

```
chevron_right
```
admin-dev\themes\new-theme\js\vue\components\Pagination.vue(50)
```

arrow_right_alt
```
src\PrestaShopBundle\Resources\views\Admin\Exception\error.html.twig(75)
src\PrestaShopBundle\Resources\views\Admin\Exception\not_found.html.twig(83)
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\preview.html.twig(174)
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\Blocks\View\messages.html.twig(85)
```

arrow_back
```
admin-dev\themes\new-theme\js\pages\product\components\dropzone\DropzonePhotoSwipe.vue(97)
admin-dev\themes\new-theme\template\components\layout\non-responsive.tpl(37)
src\PrestaShopBundle\Resources\views\Admin\Configure\AdvancedParameters\Email\Blocks\email_logs_grid.html.twig(32)
src\PrestaShopBundle\Resources\views\Admin\Configure\AdvancedParameters\ImportDataConfiguration\Blocks\import_data_configuration.html.twig(143)
src\PrestaShopBundle\Resources\views\Admin\Improve\Design\Cms\Blocks\listing_panel_footer.html.twig(28)
src\PrestaShopBundle\Resources\views\Admin\Improve\Design\MailTheme\Blocks\list_mail_theme_layouts.html.twig(113)
src\PrestaShopBundle\Resources\views\Admin\Product\ProductPage\Forms\form_combination.html.twig(72)
src\PrestaShopBundle\Resources\views\Admin\Sell\Catalog\Attribute\index.html.twig(45)
src\PrestaShopBundle\Resources\views\Admin\Sell\Catalog\Categories\Blocks\listing_panel_footer.html.twig(33)
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\Blocks\View\order_navigation.html.twig(33)
```

arrow_forward
```
admin-dev\themes\new-theme\js\pages\product\components\dropzone\DropzonePhotoSwipe.vue(105)
src\PrestaShopBundle\Resources\views\Admin\Configure\AdvancedParameters\ImportDataConfiguration\Blocks\import_data_configuration.html.twig(151)
src\PrestaShopBundle\Resources\views\Admin\Sell\Order\Order\Blocks\View\order_navigation.html.twig(43)
```

keyboard_arrow_right
```
admin-dev\themes\new-theme\js\pages\product\components\combination-modal\CombinationModal.vue(82)
src\PrestaShopBundle\Resources\views\Admin\Product\ProductPage\Forms\form_combination.html.twig(68)
```

keyboard_arrow_left
```
admin-dev\themes\new-theme\js\pages\product\components\combination-modal\CombinationModal.vue(71)
src\PrestaShopBundle\Resources\views\Admin\Product\ProductPage\Forms\form_combination.html.twig(67)
```

navigate_next
```
src\PrestaShopBundle\Resources\views\Admin\Configure\AdvancedParameters\Blocks\import_panel.html.twig(129)
```

**The changes that needed for each templates**

Adding icon's content to the class:
`<i class="material-icons">chevron_left</i>` => `<i class="material-icons chevron_left">chevron_left</i>`


**Definition of new CSS rules for mirror icon**

admin-dev\themes\default\public\theme.rtlfix
```
.material-icons .chevron_left {
  transform: scaleX(-1);
}
```
admin-dev\themes\new-theme\public\theme.rtlfix
```
.material-icons .chevron_left,
.material-icons .chevron_right,
.material-icons .arrow_right_alt,
.material-icons .arrow_back,
.material-icons .arrow_forward,
.material-icons .keyboard_arrow_left,
.material-icons .keyboard_arrow_right,
.material-icons .navigate_next {
  transform: scaleX(-1);
}
```

**Comment by NeOMakinG** [comment]
What about having both available ?

Add some helpers in order to flip (`.rlt-reverse-left, .rtl-reverse-right, .rtl-reverse-top, .rtl-reverse-bottom` for example)

And when we've the reverse icon, use the template, and comment if we use the helper to explain why we used that instead of another icon

**Comment by mparvazi** [comment]
@NeOMakinG 

Template:

`<i class="material-icons">chevron_left</i>` => `<i class="material-icons rtl-flip">chevron_left</i>`


CSS:
```
.material-icons .rtl-flip {
  transform: scaleX(-1);
}
```

Right?


I reviewed different articles for this problem:
[https://google.github.io/material-design-icons/#icons-in-rtl](https://google.github.io/material-design-icons/#icons-in-rtl)
[https://www.npmjs.com/package/@material/rtl](https://www.npmjs.com/package/@material/rtl)


Using CSS is recommended by Google as the best method.

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> Template:
> 
> `<i class="material-icons">chevron_left</i>` => `<i class="material-icons rtl-flip">chevron_left</i>`
> 
> CSS:
> 
> ```
> .material-icons .rtl-flip {
>   transform: scaleX(-1);
> }
> ```
> 
> Right?
> 
> I reviewed different articles for this problem: https://google.github.io/material-design-icons/#icons-in-rtl https://www.npmjs.com/package/@material/rtl
> 
> Using CSS is recommended by Google as the best method.

Be careful, there is a typo in your CSS!

Well, I agree, that could do the job ;)

**Comment by marionf** [comment]
@mparvazi @NeOMakinG It seems the issue isn't a regression of the V8, could you rebase on develop ?

**Comment by mparvazi** [comment]
@marionf @NeOMakinG 

Since PR #26560 has been approved, many problems related to RTL languages will be solved automatically. Therefore, this PR must be adapted to the new changes.

New PR will fixes:
1. Upgrading font-face for Persian language
2. Fix mismatch between BO themes for RTL languages
3. Find and delete duplicated CSS rules (e.g. #25035)
4. Fix bidirectionality in material icons for RTL languages
5. Fix minor bugs (e.g. Header search box)

I'll make a PR based on `develop` branch after more analysis.

**Pull request closed without merging**
