### PR TITLE
Updated contributor list

### PR DESCRIPTION
**Pull request by michaelKaefer**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add myself to contributors list
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9155)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
So, I guess we're good and we don't need to add `@author` anymore, am I right?

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks!

**Comment by Quetzacoalt91** [comment]
For your information, this list is also updated on each release. :)

**Comment by eternoendless** [comment]
Guys, please don't merge this kinds of PRs again. He would have been added to the contributors list as part of our usual release process. 

Our tool makes a diff out of the current contributors list and the generated one to pull out the list of first time contributors. Now I will have to remember to add him to the list manually...

**Pull request merged**
