### PR TITLE
Speed up test_dir with a lot of files present in a directory

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | see title
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4894
| How to test?  | do an install with a img dir full of files

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8788)

### CODE REVIEW

**Comment by jocel1** [comment]
Improvement in my case with a full img directory:
https://blackfire.io/profiles/compare/903cec84-026c-4f2a-92ed-bebb7a8a7769/graph

**Comment by Quetzacoalt91** [comment]
Interesting PR! The installer is really slow because of that filesystem check (particularly on our good old HDDs).

**Comment by rGaillard** [comment]
glob() is disabled on several hosting providers this is why the function is not used on PrestaShop.

**Comment by jocel1** [comment]
Thanks @rGaillard for the feedback, I'll then add a Tools::glob() function which will either use opendir or glob() if available

**Comment by Quetzacoalt91** [comment]
I'm fine with it, I haven't checked the performance improvement on my side but I checked the resultats are the same.

Would you mind to add that check as well on the tests? This will require to separate your function.

### ToolsTest

```php
    public static function testGetDirectories($path)
    {
        $res1 = self::getDirectoriesWithGlob($path);
        $res2 = self::getDirectoriesWithReaddir($path);
        sort($res1);
        sort($res2);
        if ($res1 !== $res2) {
            dump($res1, $res2);
            // Report error !
        }
        return $res1;
    }
```

### Tools
```php
    public static function getDirectories($path)
    {
        if (function_exists('glob')) {
            return self::getDirectoriesWithGlob($path);
        }

        return self::getDirectoriesWithReaddir($path);
    }

    public static function getDirectoriesWithGlob($path)
    {
        $directoryList = glob($path.'/*', GLOB_ONLYDIR | GLOB_NOSORT);
            array_walk($directoryList,
            function (&$absolutePath, $key) {
                $absolutePath = substr($absolutePath, strrpos($absolutePath, '/') + 1);
            }
        );

        return $directoryList;
    }

    public static function getDirectoriesWithReaddir($path)
    {
        $directoryList = [];
        $dh = @opendir($path);
        while (($file = @readdir($dh)) !== false) {
            if (is_dir($path.DIRECTORY_SEPARATOR.$file) && $file[0] != '.') {
                $directoryList[] = $file;
            }
        }
        @closedir($dh);

        return $directoryList;
    }
```

**Comment by alegout** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[classes/Tools.php, line 2658 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8788#-L6GTzijMOKte-3f5w5k:-L6GTzijMOKte-3f5w5l:b-hhjj8) ([raw file](https://github.com/prestashop/prestashop/blob/434be25a6795ff79b1e773d3afe2dd2d901133dd/classes/Tools.php#L2658)):*
> ```PHP
> 
>         $directoryList = [];
>         $dh = @opendir($path);
> ```

Hello, why did you use @ ahead opendir and closedir, maybe we should know if an error occured?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8788)*

**Comment by jocel1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[classes/Tools.php, line 2658 at r2](https://beta.reviewable.io/reviews/prestashop/prestashop/8788#-L6GTzijMOKte-3f5w5k:-L8WndgT46jdrubuRa2Q:brs4si6) ([raw file](https://github.com/prestashop/prestashop/blob/434be25a6795ff79b1e773d3afe2dd2d901133dd/classes/Tools.php#L2658)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Hello, why did you use @ ahead opendir and closedir, maybe we should know if an error occured?
</blockquote></details>

the idea is to have the same behaviour between glob and opendir. glob doesn't throw a warning in case of non existing path.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8788)*

**Comment by alegout** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[classes/Tools.php, line 2658 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8788#-L6GTzijMOKte-3f5w5k:-L8XAIlgN2ajM7JIDwz2:bm1o7ac) ([raw file](https://github.com/prestashop/prestashop/blob/434be25a6795ff79b1e773d3afe2dd2d901133dd/classes/Tools.php#L2658)):*
<details><summary><i>Previously, jocel1 (Jocelyn Fournier) wrote…</i></summary><blockquote>

the idea is to have the same behaviour between glob and opendir. glob doesn't throw a warning in case of non existing path.
</blockquote></details>

ok, it was because errors were shown before and not anymore now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8788)*

**Review by alegout — APPROVED** [review]
Thank you @jocel1

**Pull request merged**
