### PR TITLE
Test Buttons (Preview, Duplicate, Online, Go to catalog, Add a new product, Delete) in add product page

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Test Buttons (Preview, Duplicate, Online, Go to catalog, Add a new product, Delete) in add product page
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | path=full/02_product/10_check_product_page_buttons.js npm run specific-test -- --URL=prestashop_URL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8879)

### CODE REVIEW

**Review by fatmaBouchekoua — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @fouratachour

**Comment by marionf** [comment]
Hello @fouratachour 
After clicking on the delete button in the bottom of the product page and on "Yes" in the modal, we need to check on the catalog page if the product isn't here anymore (in addition to the presence of the message "Product successfully deleted.")
We need also to click on "No" in the modal after clicking on the delete button & check if we are still on the product page with the name of the product

**Comment by fatmaBouchekoua** [comment]
Hello @marionf ,
Thank you for your review, we will add them to this scenario in this PR https://github.com/PrestaShop/PrestaShop/pull/9127
You have to mention these actions in the recorded video, or in Teslink to ensure that we will not have missing scenarios in our scripts.

Thanks

**Comment by marionf** [comment]
Hello @fatmaBouchekoua 
I have updated the scenario on testlink

**Pull request merged**
