### PR TITLE
Fix RTL visual glitches

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3x
| Description?  | Fixes many bugs with RTL transformation, mainly due to the fact that CSS embedded in .vue files wasn't transformed to RTL.<br>This PR Also fixes other small visual glitches, like the collapse/expand buttons being different in tree components across the translation page and the stock page.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4319
| How to test?  | The stock pages as well as the translation page should look OK now

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8702)

### CODE REVIEW

**Comment by marionf** [comment]
@eternoendless 
I updated the [forge ticket](http://forge.prestashop.com/browse/BOOM-4319) with what remains to solve

**Comment by eternoendless** [comment]
Button background fixed!
screen shot 2018-01-25 at 18 06 23

**Comment by alegout** [comment]
Reviewed 30 of 31 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[admin-dev/themes/new-theme/scss/components/_ps_tree.scss, line 31 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8702#-L3m2c53sA-22jRb9SQH:-L3m2c53sA-22jRb9SQI:b504v64) ([raw file](https://github.com/prestashop/prestashop/blob/13f1a70eb6cbf2f087ce47f83d8d200242da93a2/admin-dev/themes/new-theme/scss/components/_ps_tree.scss#L31)):*
> ```SCSS
>       }
>       &.open:before {
>         content: "keyboard_arrow_down";
> ```

Personally i don't like the use of CSS language to modify html contents., but not a blocking point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8702)*

**Comment by alegout** [comment]
:lgtm: thank you :+1: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8702#-:-L3m4NFtEeitx88nbCMD:bm5te68)*

**Review by alegout — APPROVED** [review]
Thank you!

**Comment by eternoendless** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[admin-dev/themes/new-theme/scss/components/_ps_tree.scss, line 31 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8702#-L3m2c53sA-22jRb9SQH:-L3m510B9ygElSeOfwjM:bnlcykw) ([raw file](https://github.com/prestashop/prestashop/blob/13f1a70eb6cbf2f087ce47f83d8d200242da93a2/admin-dev/themes/new-theme/scss/components/_ps_tree.scss#L31)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Personally i don't like the use of CSS language to modify html contents., but not a blocking point.
</blockquote></details>

It's for the icon actually :)

In any case it's very much needed in order to be able to flip left or right-pointing icons when switching to RTL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8702)*

**Pull request merged**
