### PR TITLE
BO: fix wrong display in form.tpl

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | There is a HTML element in the `form.tpl` file that causes it to break the design. The error mainly affects when using the `tabs` in the array of the `HelperForm()`.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | In a module configurator, create a form using the `HelperForm` class, use tabs, and a couple of `textarea` inputs, then create a extra panel in the bottom and you will see this error with the overlapping elements, like this: https://i.postimg.cc/5fzSPc2t/Screen-Shot-2018-10-23-at-5-05-44-PM.png

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11132)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by ntiepresta** [comment]
@Rolige,
Please, can you provide us  the module  for  to reproduce the issue , to better meet your needs.
Best regards,

**Comment by Rolige** [comment]
@ntiepresta 
You can reproduce the error with this module from Addons: https://addons.prestashop.com/en/promotions-gifts/41771-smart-popup-newsletter-popup.html

Regards!

**Comment by ntiepresta** [comment]
@Rolige 
I did not manage to reproduce the issue with the popup-newsletter-popup  module. To better meet you needs, please can you provide us your module used and a video record of your issue.
Regards!
non probleme

**Comment by Rolige** [comment]
@ntiepresta 
I see, I tested again and the error disappeared. This PR was sent 2 months ago, maybe the problem was fixed in some other commit in that time lapse.

regards!

**Comment by PierreRambaud** [comment]
@Rolige Hey, if everything is ok for you, can we close this PR? :)

**Comment by Rolige** [comment]
Sure!

**Comment by PierreRambaud** [comment]
Thanks for your PR even if it was not merged, we really appreciate contributions from everyone :)

**Pull request closed without merging**
