### PR TITLE
Fix PHP CS Fixer configuration: disable single_line_throw and backport #17328

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Disable rule single_line_throw for PHP CS Fixer and backport #17328
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No QA needed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17532)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]

**Comment by matks** [comment]
😱 
```
HP-CS-Fixer configuration file found, running PHP-CS-Fixer with version
PHP CS Fixer 2.14.0 Sunrise by Fabien Potencier and Dariusz Ruminski

Loaded config default from "/tmp/code/.php_cs.dist".

In ConfigurationResolver.php line 756:
                                                          
  The rules contain unknown fixers: "single_line_throw".  
                                                          

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]

Errors were found, run 'pretty fix' to fix them.
```

**Comment by matks** [comment]
`single_line_throw ` was released with PHP CS Fixer 2.16.0 (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4452) which is why pretty-ci fails

**Comment by matks** [comment]
OK, I backport https://github.com/PrestaShop/PrestaShop/pull/17328/ to 1.7.7.x to fix the issue

**Review by rokaszygmantas — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @matks

**Pull request merged**
