### PR TITLE
Merge 8.0.x to 8.1.x

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Merge 8.0 to 8.1
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and [tests](https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5508824425) are green
| Fixed ticket?     | -
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by boherm — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Some tests are red, we need help from @PrestaShop/qa-automation

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
> tests

One failure is a dependency download failure probably due to network

The 2 others are related to Product Page V2 combinations feature (modal and bulk generate)

**Review by jolelievre — APPROVED** [review]

**Comment by M0rgan01** [comment]
Tests: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/5508824425

**Comment by matks** [comment]
Thank you @M0rgan01

**Pull request merged**
