### PR TITLE
Add High DPI support to ImageRetriever

### LINKED ISSUE #19798: No High DPI support in ImageRetriever
#### Describe the bug

Image retriever only generates low res images.

#### Expected behavior

All images should be generated correctly.

#### Steps to Reproduce

1. Turn on "Generate high resolution images" option
2. Regenerate all images, make sure the high res images are there
3. Delete thumbnails for one selected image of a product
4. Go to product page
5. Check the thumbnails folder - only low res images are regenerated

* PrestaShop version: 1.7.6.5

### PR DESCRIPTION
**Pull request by daresh**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add High DPI support to ImageRetriever
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19798
| How to test?  | 1. have a shop with no High DPI support<br>2. turn on High DPI support<br>3. go to product page<br>4. check out image folder on your server - img/p - it should have HIGH DPI images generated

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19965)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hi @daresh, Could you fix PHP-CS-Fixer ?

**Comment by daresh** [comment]
Hi @Progi1984 I tried but I don't know how to fix it and what is the bug there.

**Comment by matthieu-rolland** [comment]
> Hi @Progi1984 I tried but I don't know how to fix it and what is the bug there.

it's ok I did it 👍

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @daresh !!

**Comment by Progi1984** [comment]
Thanks @daresh & @SD1982

**Pull request merged**
