### PR TITLE
Use binary mode to write files

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11729)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Wdyt?

**Comment by mickaelandrieu** [comment]
I don't know at all: what does it change?

/c @matks

**Comment by MathiasReker** [comment]
@mickaelandrieu Windows offers a text-mode translation flag ('t') which will transparently translate \n to \r\n when working with the file. In contrast, you can also use 'b' to force binary mode, which will not translate your data. To use these flags, specify either 'b' or 't' as the last character of the mode parameter. 

 Doc: http://php.net/manual/kr/function.fopen.php

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
ping @Quetzacoalt91 wdyt?

**Comment by Quetzacoalt91** [comment]
Yep I read people advising to use the binary mode.

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by MathiasReker** [comment]
Should be ready to get merged :)

**Comment by Quetzacoalt91** [comment]
Thank you @MathiasReker

**Pull request merged**
