### PR TITLE
Allow Front controller called in cli if ssl is on or maintenance mode is on

### LINKED ISSUE #34670: Front controller called in cli is blocked by ssl redirection and maintenance mode
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Look at this https://devdocs.prestashop-project.org/8/modules/concepts/controllers/front-controllers/#using-a-front-controller-as-a-cron-task
A cron task in cli can be blocked by ssl redirection and maintenance mode

### Expected behavior

cli not blocked.
This PR allow front controller like crons tu be launched indifferently by http or by cli.

### Steps to reproduce

1. Call a front controller in CLI directly with php like explained in the doc : php patch/myscript.php
2. Activate SSL and Maintenance mode
3. The command doesn't works

### PrestaShop version(s) where the bug happened

1.7, 8, develop

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Creabilis

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allow Front controller called in cli if ssl is on or maintenance mode is on
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See issue
| Fixed issue or discussion?     | Fixes #34670
| Sponsor company   | Creabilis

### CODE REVIEW

**Comment by jf-viguier** [comment]
@prestonBot, There is an issue [there](https://github.com/PrestaShop/PrestaShop/issues/34670)

**Review by nicosomb — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Comment by jf-viguier** [comment]
Thanks @nicosomb @mflasquin

**Comment by Hlavtox** [comment]
This could theoretically go to 8.1.3

**Comment by jf-viguier** [comment]
@Hlavtox done here https://github.com/PrestaShop/PrestaShop/pull/34698

**Review by boherm — APPROVED** [review]

**Review by matks — APPROVED** [review]
I am still not a fan bof the solution but 🤷 I guess it can't hurt

**Review by matks — COMMENTED** [review]
Woups, I just saw there was a PR for 8.1.x branch so when we performed a branch merge, the changes were ported from 8.1.x to develop

I have verified: file is correct in https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/FrontController.php

This PR is not needed anymore, the code has already been changed on `develop`

**Comment by matks** [comment]
Thank you @jf-viguier

**Pull request closed without merging**
