### PR TITLE
BO > Shopping Carts : Force Bulk Column

### LINKED ISSUE #29894: Incorrect number of columns when filtering in Shopping Carts page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In Shopping Carts page, if I filter on Numeric in Order ID, there are 8 columns rather than 9.

### Expected behavior

If I filter on Numeric in Order ID, there are 9 columns.

### Steps to reproduce

1. In BO, go to Shopping Carts page
2. There are 9 columns : 
image
3. If I filter on Abandoned carts, there are 9 columns
image
4. If I filter on Numeric in Order ID, there are 8 columns
image

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #29984: BO - Fields are not correctly aligned in "Theme & logo"'s page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

On theme & logo page, fields are not aligned correctly (the middle one is a slight below other ones) + in French, the "email" word has got a bad translation (missing the "e" letter")
Tested on 8.0.x / 1.7.8.x / 1.7.7.8 version. No regression

8.0.x ❌ 

- EN
field-theme-logo-en-800

- FR
field-theme-logo-fr-800

1.7.8.x ❌ 

- EN
field-theme-logo-en-178x

- FR
field-theme-logo-fr-178x

1.7.7.8 ❌ 

- EN
field-theme-logo-en-1778

- FR

field-theme-logo-fr-1778

### Expected behavior

All fields should be aligned and text correctly written

### Steps to reproduce

1. Go to your BO

2. click on Design > Theme & Logo > Theme & logo tab

3. See error

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | BO > Shopping Carts : Force Bulk Column
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29894
| Related PRs       | N/A
| How to test?      | Cf. #29894 (The fix is tested by UI tests)<br> The CI is :green_circle:  : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/3525105754
| Possible impacts? | N/A

### CODE REVIEW

**Review by lartist — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by Progi1984** [comment]
@lartist & @mflasquin It's valided for UI Tests.

**Review by matthieu-rolland — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @Progi1984 

Thanks for your PR ! it's LGTM QA :heavy_check_mark: also the test-auto **OK** 
there is always 9 columns  by default even when you filter with `order ID` or with `Abandoned carts `
image
 , you can see the attached screenshots 

image


image

Thank you ! :rocket:

**Review by sallemiines — COMMENTED** [review]
Hello @Progi1984 

Thanks for your PR ! it's LGTM QA :heavy_check_mark: also the test-auto **OK** 
there is always 9 columns  by default even when you filter with `order ID` or with `Abandoned carts `
image
 , you can see the attached screenshots 

image


image

Thank you ! :rocket:

**Comment by eternoendless** [comment]
Thanks @Progi1984

**Pull request merged**
