### PR TITLE
Moving tests High to full or to broken tests

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Moving test high to full 
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | testing all fill suite

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13726)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Just to be sure, it is only about moving tests from `high` folder to `full` folder?
did you just copy the content in the proper folder or did you modify some things as well?

**Comment by boubkerbribri** [comment]
yes @jolelievre, it's only about moving files from high to full or from high to broken_tests.

**Comment by jolelievre** [comment]
Alright, ready to merge then?

**Comment by boubkerbribri** [comment]
yes, please

**Pull request merged**
