### PR TITLE
Add manufacturer url to {url} helper

### LINKED ISSUE #30313: {url} helper generate the manufacturer url without rewrite rules
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Hello, 

The `{url}` helper in smarty generate the URL of manufacturer without rewriting url:
ex:
`{url entity='manufacturer' id=1}`
will ouput: 
`//prestashop:8888/brands?id_manufacturer=1`

If we use the `$link` class it works fine: 
`{$link->getManufacturerLink(1)}`
will output: 
`http://prestashop:8888/brand/1-studio-design`

### Expected behavior

`{url entity='manufacturer' id=1}` should be return the same result of `{$link->getManufacturerLink(1)}` (without the http(s))

### Steps to reproduce

For testing: 
Edit file: themes/classic/templates/index.tpl
put this code:

```
{**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License 3.0 (AFL-3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
 * versions in the future. If you wish to customize PrestaShop for your
 * needs please refer to https://devdocs.prestashop.com/ for more information.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License 3.0 (AFL-3.0)
 *}
{extends file='page.tpl'}

    {block name='page_content_container'}
      <section id="content" class="page-home">
        {block name='page_content_top'}{/block}

        {block name='page_content'}
          {block name='hook_home'}
            {* Wrong url *}
            {url entity='manufacturer' id=1}
            <br>
            {* Good url *}
            {$link->getManufacturerLink(1)}
            {$HOOK_HOME nofilter}
          {/block}
        {/block}
      </section>
    {/block}

```

Then empty the smarty cache

Go to the home page of your shop, you will see the url displayed: 
Capture d’écran 2022-11-17 à 09 25 51

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by PrestaSafe**
Fix of issue: https://github.com/PrestaShop/PrestaShop/issues/30313

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Please the description on the issue #30313
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30313. 
| Related PRs       | none
| How to test?      | Follow instructions in the issue 
| Possible impacts? | none

### CODE REVIEW

**Review by micka-fdz — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
Nice work @PrestaSafe! :-)

**Review by kpodemski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thanx for your contribution @PrestaSafe !

@PrestaShop/qa-team  I will test this PR (I think it's to be tested by a developer, what do you think ?)

**Review by ghost — APPROVED** [review]
Nice !

**Comment by matthieu-rolland** [comment]
I tested the PR and it works as intended :+1:

**Review by jolelievre — APPROVED** [review]
Thanks @PrestaSafe

**Review by hibatallahAouadni — APPROVED** [review]
Hello @PrestaSafe 

Thanks for your PR :rocket: 
LGTM, QA :heavy_check_mark: 
image

Thanks!

**Comment by kpodemski** [comment]
Thanks @PrestaSafe! :))

**Pull request merged**
