### PR TITLE
Remove remains of AdminCartsController view

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes remains of old migrated cart view page.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Check that you can see detail in cart in BO. Check that backoffice order creation works normally. Check that cart list in BO works normally.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Comment by kpodemski** [comment]
You need to remove `use PrestaShop\PrestaShop\Core\Localization\Exception\LocalizationException;`

**Comment by Hlavtox** [comment]
Done @kpodemski

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by sallemiines — APPROVED** [review]
Hello @Hlavtox 

Thnx for the PR LGTM QA :heavy_check_mark: 

[AUTO-tests ](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5739505970) OK

**Comment by Hlavtox** [comment]
Thanks @sallemiines!

**Pull request merged**
