### PR TITLE
No PHP closing tag and no EOL

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11738)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
@PrestaShop/prestashop-core-developers No need QA.

**Comment by jolelievre** [comment]
@MathiasReker just a little conflict which appeared and we're good to go

**Comment by MathiasReker** [comment]
@jolelievre  fixed.

**Review by PierreRambaud — APPROVED** [review]

**Comment by jolelievre** [comment]
Thank you @PierreRambaud @MathiasReker

**Pull request merged**
