### PR TITLE
[-] CORE : Correct fatal error with php7

### PR DESCRIPTION
**Pull request by sfroment**

### CODE REVIEW

**Comment by sfroment42** [comment]
close @xGouley already do a PR on those errors

**Comment by jd440** [comment]
Are you planning to correct it on PS1.6.x?

**Comment by sfroment** [comment]
I'm not part of the prestashop team anymore I was believing that it was already correct.
I've made a new PR #5480. If you want to see it merged comment under this new one =).

**Comment by julienbourdeau** [comment]
Thanks @sfroment !

@jd440 I depends if it breaks PHP 5.2 support. But you can find all patches under this label: https://github.com/PrestaShop/PrestaShop/pulls?q=label%3APHP7

**Comment by jd440** [comment]
@julienbourdeau but we can do something compatible PHP 5.2 & PHP7

**Pull request closed without merging**
