### PR TITLE
Fix saving decimals in AdminProduct combination form

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If you save any value to every price impact form, the decimals aren't saved. The problem is that the system does'n accept comma in floats. 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2126
| How to test?  | Go to edit combination in BO and edit the cost price or the impact on price and save and finally refresh.

### CODE REVIEW

**Comment by thierrymarianne** [comment]
Thank you @fatmaBouchekoua

**Comment by davidddp** [comment]
I just added the lines of code to my PS 1.7.0.1 and it still does not work.

**Comment by psyray** [comment]
Hi,
This patch doesn't work properly.
It applies only on the current edited price due to the blur js function. If you have multiple combinations, all the others doesn't save the decimals. (see capture above which is the result after saving - all prices with 8 was 8,33333 before saving)
I think the price normalization should be set in the PHP part not the JS part.
image
I think

**Comment by psyray** [comment]
To temporary fix the problem, check my workaround here
http://forge.prestashop.com/browse/BOOM-2126

**Pull request merged**
