### PR TITLE
Revert "[*] TR : Better spelling of Dutch tab names"

### PR DESCRIPTION
**Pull request by Shudrum**
Reverts PrestaShop/PrestaShop#5002

### CODE REVIEW

**Comment by firstred** [comment]
Something wrong?

**Comment by Shudrum** [comment]
Yeah, but we will not revert your PR :)

You have a merge on your pull request, and this merge break the history and conflict with many other pull requests. This revert was created to see if it cancel the merge history but no … So I currently manually merge the conflicts ^^

**Comment by firstred** [comment]
Oops! 
Yeah, maybe I should stop calling my remotes `origin` and `origin2`. I saw that the wrong repo was merged.
Sorry for the inconvenience.

**Comment by Shudrum** [comment]
We should not have merged the PR in this state, but it's ok, we will fix everything :)

**Pull request closed without merging**
