### PR TITLE
Fix Incorrect SpecificPrice Currency Conversion (Issue 36844)

### LINKED ISSUE #36629: Cannot set specific price with currency filter
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello everyone,
We have discovered a bug with the specific pricing feature that prevents us from setting different prices in non-default currencies for products. We want to set fixed prices for one of our manufacturers, but we can't due to the rate multiplier.

Even after setting a stiff specific price in a different currency, the price is still multiplied by the exchange rate.

For example, the normal price in EUR:
image

Here, it should be 10 USD, but it is multiplied by the exchange rate:
image

Currencies:
image

Product specific price:
image

### Expected behavior

A fixed specific price should be as we set it, for example, 5 USD, not "5 USD * exchange rate". It works okay when you add a specific price in the default currency as it is supposed to be multiplied by the exchange rate.

### Steps to reproduce

Back Office:

1. Go to International > Localization > Currencies.
2. Set up an additional currency with an exchange rate, in my case x2.
3. Go to Products > Catalog > Add new product.
4. In the product "Pricing" tab, add a price (in my case it will be 5 EUR).
5. Scroll to the bottom > Specific prices > Add a Specific Price.
6. In "Apply to," choose the additional currency and then scroll to the bottom.
7. Turn on "Set specific price" and enter a value, in my case 10 USD

Front Office:

1. Go to the added product and check the price.
2. Verify the price.
3. Change the currency to the second one.
4. Check the price again.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

ps_currencyselector

### Your company or customer's name goes here (if applicable).

_No response_

### LINKED ISSUE #36844: Currency conversion is run even if there is set a specific price for a currency
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a merchant has 2 or more currencies, one can set a currency conversion. Lets say NOK and EUR. 
NOK is default price and EUR is set to conversion 0,1, meaning a product priced to 100 NOK, should be converted to 10 EUR. This works fine. 

But when a merchant wants to set the price for EUR specifically, lets say he/she sets it to 8 EUR with a specific price, the automatic currency conversion **should not apply**, however it does. 

In this case the price 8 EUR would be converted to 0,8 EUR.

### Expected behavior

When specific price is set for a currency, automatic currency conversion should not apply.

### Steps to reproduce

1. Create a product.
2. Activate two or more currencies, set up  currency conversion numbers.
3. Observe in front office that the price change as expected with automatic currency conversion.
4. Now go to the product and set a specific price for a currency.
5. Observe in front office that BOTH your "manual" specific price currency conversion AND the automatic currency conversion is applied.

Now, here is the sollution:
```
classes/Product.php:3896
$id_currency == $specific_price['id_currency'] // instead of strict check $id_currency === $specific_price['id_currency']
```

6. Now observe it works as it should.

The reason is that `$id_currency` is a string and `$specific_price['id_currency']`  is an int (or the other way, I cant remember), so the typesafe condition fails.

The bug should possibly be solved by making sure both those variables are int`s, but a quick fix is to disable the typecheck.

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mrkalchemy**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Specific Prices have a currency conversion applied to them even if the currency has been set and no conversion is necessary. See issue for full details. 
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |  For a product set a "Specific Price" that does not use the default shop currency and view the item in the store in the same currency. If an exchange rate is set then the price should still match the one set in the back office and the exchange rate will not be applied.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #36844 , Fixes #36629
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `BC breaks` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#bc-breaks))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by FabienPapet** [comment]
Can't approve this unless there is a unit test that proves that this works. 

Also, removing strict type checking is not a good idea IMHO, better convert it before making a comparaison. For an example

```php
$a = 1;
$b  = '1'

$a == $b // true
$a ===b $b // false

// change to this.
(int) $a === (int) $b // true
```

**Review by FabienPapet — CHANGES_REQUESTED** [review]
Can't approve this unless there is a unit test that proves that this works. 

Also, removing strict type checking is not a good idea IMHO, better convert it before making a comparaison. For an example

```php
$a = 1;
$b  = '1'

$a == $b // true
$a === $b // false

// change to this.
(int) $a === (int) $b // true
```

**Comment by mrkalchemy** [comment]
@FabienPapet  I've updated the PR to use a strict operator and explicit casting. This still fixes the mismatched type issue and, hopefully, should address your concerns.

**Review by FabienPapet — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I'm merging following @florine2623 recommendation. I think this change is completely safe.

**Pull request merged**
