### PR TITLE
Fix modules translation form

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Modules translation form can only be submitted using the first two save buttons due to malformed output
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Open a module configuration page, click "Translate" on top and submit the form

### CODE REVIEW

**Comment by maximebiloe** [comment]
Thank you @unlocomqx

**Comment by bellini13** [comment]
Can someone help explain to me why this did not make the 1.7.0.3 release?  This appears to have been merged on December 8th, and 1.7.0.3 was released on December 21st.  

Did something go wrong with the merging of this?

**Comment by maximebiloe** [comment]
@bellini13 it has been done on `develop`. I've reported it on `1.7.0.x` (https://github.com/PrestaShop/PrestaShop/pull/7193) 26 days ago and it was milestoned for 1.7.0.4. It will be available soon.

**Comment by bellini13** [comment]
Thanks maximebiloe.  i assumed since it was so long ago that it would automatically make the next (1.7.0.3) release, it hadn't occurred to me that they would skip a release.

Are you aware of a prioritization system that determines when fixes will be released?  Perhaps we can message offline about this?  I would be curious about Prestashop process for code promotion.

**Pull request merged**
