### PR TITLE
Fix EOL to LF in multiline strings

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix EOL to LF
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22965)

### CODE REVIEW

**Comment by Progi1984** [comment]
@mvorisek I don't understand the goal of this PR. Can you target me on this one ?

**Comment by mvorisek** [comment]
@Progi1984 yes, one file contained `\r\n` (Windows EOL) which this PR changes to pure linux EOL (`\n`)

**Comment by PierreRambaud** [comment]
> @Progi1984 yes, one file contained `\r\n` (Windows EOL) which this PR changes to pure linux EOL (`\n`)

It's inside strings, so it's not a problem. I see no reason to do it right now :thinking:

**Comment by mvorisek** [comment]
But no need to keep CRLF :) Thus we should normalize, right?

**Comment by PierreRambaud** [comment]
Since the pull request gives no value, we have no reason to merge it.
Currently, it's doesn't break anything, it's doesn't improve anything because these are strings :thinking:

**Comment by mvorisek** [comment]
@PierreRambaud This is CS fix. CS Fixer does not fix it as the CRLF endings are inside a heredoc string, but "dummy" text tools like IDE and git fix CRLF to LF. And keeping wrong EOL is thus then an issue as these files are changed by these applications itself and every time someone wants to contribute, these fixes are within the unstaged files.

I belive, the source of this issue is that someone staged these files incorrectly (on Windows with git configured without EOL conversion).

**Comment by mvorisek** [comment]
@matks @Progi1984 can you please help?

**Comment by mvorisek** [comment]
@matks @Progi1984 @eternoendless 1984 can someone of you please approve?

**Comment by PierreRambaud** [comment]
> @PierreRambaud This is CS fix. CS Fixer does not fix it as the CRLF endings are inside a heredoc string, but "dummy" text tools like IDE and git fix CRLF to LF. And keeping wrong EOL is thus then an issue as these files are changed by these applications itself and every time someone wants to contribute, these fixes are within the unstaged files.
> 
> I belive, the source of this issue is that someone staged these files incorrectly (on Windows with git configured without EOL conversion).

If you look closely in strings you change, you can also see there are a lot of tabs inside.
This is why a change like that is not really well. If you redo strings to concatenate strings, it would be better and we will approve it.

**Comment by mvorisek** [comment]
> If you look closely in strings you change, you can also see there are a lot of tabs inside.
> This is why a change like that is not really well. If you redo strings to concatenate strings, it would be better and we will approve it.

@PierreRambaud I see, but tabs were already there. The only change I propose with this PR is to norm the EOL to LF.

**Comment by PierreRambaud** [comment]
> > If you look closely in strings you change, you can also see there are a lot of tabs inside.
> > This is why a change like that is not really well. If you redo strings to concatenate strings, it would be better and we will approve it.
> 
> @PierreRambaud I see, but tabs were already there. The only change I propose with this PR is to norm the EOL to LF.

CRLF were already there too :sweat_smile:

**Comment by mvorisek** [comment]
yes, step by step, this PR is for one step only :)

**Comment by crts314** [comment]
CRLF issue is more annoying than the tabs. It took me time to just figure out why a single comment created so many modified lines. Many IDEs will save LF or CRLF but will refuse to save a file with a mix of both. Even when changing the 1 line I wanted through github editor I couldn't avoid the big diff as you can see on this screenshot

https://i.imgur.com/blly8wI.png 

So I believe the suggested PR is in itself an improvement, which is independant from the tab issue.

**Comment by mvorisek** [comment]
@PierreRambaud Is the reasoning above enough? From my POV the change is complete. If multiline strings should be refactored, it should be done really in another PR at least because that change should be done probably in much more files.

**Comment by Progi1984** [comment]
@mvorisek You should use PHPCSFixer and add `->setLineEnding("\n")` in https://github.com/PrestaShop/PrestaShop/blob/develop/.php_cs.dist#L48

Référence : https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3955#issuecomment-409673885

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek You should use PHPCSFixer and add `->setLineEnding("\n")` in https://github.com/PrestaShop/PrestaShop/blob/develop/.php_cs.dist#L48
> 
> Référence : [FriendsOfPHP/PHP-CS-Fixer#3955 (comment)](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3955#issuecomment-409673885)

@Progi1984 I belive `\n` is default and right EOL is enforced by `line_ending` CS fixer rule (enabled with `@Symfony` ruleset)

The issue is unfixed CRLF EOL in PHP string.

**Comment by PierreRambaud** [comment]
> The issue is unfixed CRLF EOL in PHP string.

Because you may want to add CRLF in strings, a cs fixer rule shouldn't block that.

**Comment by mvorisek** [comment]
> 
> 
> > The issue is unfixed CRLF EOL in PHP string.
> 
> Because you may want to add CRLF in strings, a cs fixer rule shouldn't block that.

Yes and that works as expected. But CRLF in strings here are not intended thus chnaging EOL to LF. @PierreRambaud @Progi1984 @matks please approve and merge.

**Comment by PierreRambaud** [comment]
As I said above, I will not approve this pull request since it brings no value.

**Comment by mvorisek** [comment]
@PierreRambaud why do you think another developer already opened a PR for the same? Why do we normalize EOL in files at all? Please, understand the improvement or please ping your peers to submit their opinion on it. Thanks.

**Comment by PierreRambaud** [comment]
> @PierreRambaud why do you think another developer already opened a PR for the same? Why do we normalize EOL in files at all? Please, understand the improvement or please ping your peers to submit their opinion on it. Thanks.

We already improve EOL in files, it's already checked by PHP CS Fixer, but doing it for string it's completely useless.

**Comment by mvorisek** [comment]
@PierreRambaud But why do we do that at all? I belive with the same reason we should fix the EOL in multiline strings as well, I and at least one reporter have a real issue that some non-code aware editors change these EOL which is unneeded obstackle to contribute to this project. In short, this is a real improvement without any downside, so let's merge it and keep everyone happy :)

**Comment by matks** [comment]
Hi everyone

Like I just wrote in PR https://github.com/PrestaShop/PrestaShop/pull/22823#issuecomment-870394578, I'm afraid here we are in a situation where we don't want to merge this PR. It has not been moved in March and I think if nobody from maintainer team joins in the discussion it means nobody from maintainer team is willing to join.
There is a lot of things to do for the PrestaShop project and our time is limited. Maintainers have to pick carefully what topics they allow to go forward by reviewing and approving Pull Requests, so they choose what PRs and/or topics they invest their time in. If this PR has not moved for a long time I think it's because maintainers do not see a very valid reason to continue.

By opening this PR but it seems we don't want the project to go through this path in this direction, at least today. Maybe in the future.

Thank you for your contribution, I close this Pull Request because I don't think it will be merged.

If 2 other maintainers of the project disagree with me they are free to re-open the Pull Request and continue this journey. For me, it's better to halt it here.

**Comment by mvorisek** [comment]
@matks this PR is legit and is required to fix EOL issue, almost every text editor normalizes EOL and any change in this file will introduce this changes again. And when it will, you will request a separate PR. And here it is :) @eternoendless please reopen, check, merge and speak with your guys :)

**Pull request closed without merging**
