### PR TITLE
removing code file 252 - 254

### PR DESCRIPTION
**Pull request by petsgoglamping**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Use the "develop" branch if you target PrestaShop 1.7; use the "1.6.1.x" branch if you target PrestaShop 1.6 (bugfixes only).
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature
| Category?     | See [the Category list](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message#Howtowriteacommitmessage-Category), i.e.: BO
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by petsgoglamping** [comment]
Hi there,

Sorry about this I think I have done the wrong thing. I am wanting to take out lines 252-254 in the code. So I can save products to my store but don't really know what I am doing. So if I have done the wrong thing is there a way you can delete/remove it?

Regards

Glyn

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by xBorderie** [comment]
Hi @petsgoglamping ! Are you saying that these lines of code are preventing to save products on your store?
Could you rather make a detailed bug report on the Forge? See here: http://forge.prestashop.com/secure/CreateIssue%21default.jspa?selectedProjectId=10110&issuetype=1 This way our team can properly assert the issue and see about a fix.
Thank you!
In the mean time, I am closing this PR.

**Comment by petsgoglamping** [comment]
I think a report has been made and this is the solution that has been put on the forum, but I don't know what or how to sort the problem out. I have switched from chrome to Firefox now, which is the other solution.

Regards

Glyn

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by xBorderie** [comment]
Ah, so could it be that you are using an old version of PS 1.6?
The Chrome issue was fixed in v1.6.1.9, [released November 8th](http://build.prestashop.com/news/prestashop-1619-maintenance-release/) (bug explanation in the article). Which version do you use?

**Comment by petsgoglamping** [comment]
I am using 1.6.1.7

Regards

Glyn

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by xBorderie** [comment]
Well, there you go: the issue was fixed two versions later.
I would advise you to upgrade to the latest 1.6 version, [1.6.1.11](https://download.prestashop.com/download/old/prestashop_1.6.1.11.zip), which includes the fix.

**Pull request closed without merging**
