### PR TITLE
Remove deprecated enable_mobile|disable_mobile

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove the enable_mobile and disable_mobile action from ModuleManager, deprecated since 1.7.3.0
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket | Relative to #26293
| How to test?      | Use the action on module (enable for mobile|disable for mobile) to see that it's work as before
| Possible impacts? | n/d

📓 BC break

- Remove method `enable_mobile()` in src/Core/Addon/Module/ModuleManager.php
- Remove method `disable_mobile()` in src/Core/Addon/Module/ModuleManager.php

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27527)

### CODE REVIEW

**Comment by Hlavtox** [comment]
@NeOMakinG Cannot we just completely remove this? Its 2010 stuff.

- Mobile users should have the same experience as desktop.
- We have responsivity.
- What even defines mobile and desktop? We have an infinite range of screen sizes.

**Comment by NeOMakinG** [comment]
> @NeOMakinG Cannot we just completely remove this? Its 2010 stuff.
> 
> * Mobile users should have the same experience as desktop.
> * We have responsivity.
> * What even defines mobile and desktop? We have an infinite range of screen sizes.

I agree, responsive should be enough, this is not the backend responsibility

**Comment by kpodemski** [comment]
@NeOMakinG @Hlavtox 

But this prevents the module from running on mobile devices, which means that if you have a heavy module connecting to the external service, and you want to use it on desktop, and not on mobile - you can. It's completely different than hiding/showing something on mobile.

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
No module should be that heavy that it should not be loaded on mobile. Usually over 60% of all customers access the web from mobile devices, they need to have the same experience as on desktop. ;-)

**Comment by kpodemski** [comment]
Let's leave that decision on what customers should, or shouldn't have to the developers 👍  I can imagine some scenarios, especially related to the B2B stores where this feature can be helpful :-)

**Review by Progi1984 — APPROVED** [review]

**Review by AureRita — CHANGES_REQUESTED** [review]
I tested it and the variable seems to be correctly changed, 

as we can see on this picture 

the module manager have 75 utilisation of disableMobile (on Mozilla)
image



It seems to be the same on google 
image



there is no use of _mobile 
image

**Review by AureRita — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Thanks @PrestaEdit 

I really think that this PR will create a lot of wrong behaviors on different modules, be prepared to get some issues about it!

**Comment by PrestaEdit** [comment]
Doesn't see why, as you are still able to enable/disable mobile devices for somes modules. It's just the old methods (not used by module itself) that are removed, not the feature.

**Comment by NeOMakinG** [comment]
> Doesn't see why, as you are still able to enable/disable mobile devices for somes modules. It's just the old methods (not used by module itself) that are removed, not the feature.

Oh ok, thanks for the precision!

**Comment by matks** [comment]
I think we also need to document BC break inside https://devdocs.prestashop.com/8/modules/core-updates/8.0/ so I keep the label "Needs documentation"

**Pull request merged**
