### PR TITLE
Add upload progress bar in virtual product panel

### LINKED ISSUE #26344: [BO] Improve virual product by adding upload progress for large files
#### Is your feature request related to a problem?

Uploading large files in product page may take too long. Without showing the upload progress user may think that the process has encountered a problem.

#### Describe the solution you'd like

Simply adding a progress bar before the submit button will be useful.

#### Screenshot

https://watch.screencastify.com/v/IR6vJed1Cu0tgVMElCyD

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Improves virtual product panel by adding progress bar in upload form. It'll be useful for large file uploads.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26344
| How to test?      | Create a new product. Select "Virtual product" from product type menu. In virtual product panel, progress bar is displayed before the submit button. Try upload a large file.
| Possible impacts? | -

#### Screenshots

- Before upload:

- Uploading:

- Upload completed:

https://watch.screencastify.com/v/IR6vJed1Cu0tgVMElCyD

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26370)

### CODE REVIEW

**Comment by Progi1984** [comment]
@mparvazi Thank you for your contribution.

I have added a label "Wainting for PM" as the Product Page is currently in migration. If you have time and if the issue is validated by PM, the good contribution could be to add this improvement to the new page. (Ping @NeOMakinG & @jolelievre for discussions).

**Comment by NeOMakinG** [comment]
damn @mparvazi I'm so sorry about this, but this PR may be canceled, the old product page will probably be kicked out in the next version :(

Let's wait @PrestaShop/product-team advice

**Comment by mparvazi** [comment]
@NeOMakinG No problem!
It’s worth to wait for new version.
In PS I Trust 🙏

**Comment by MatShir** [comment]
The idea is very good and cool 👍. The product page will be redesigned, but the feature is very well welcome. The issue is approved, when the new design is merged into develop you can then add your feature again. Sorry for the inconvenience. 
Keep the great work :)

**Pull request closed without merging**
