### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by hiousi**
Do we really need this test ?
Since almost 4 years this test is wrongly always true, and nobody noticed.
On some file systems (I thing of AWS S3) it is very time consuming and cost a lot to check for the presence of a file.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for you rPR but something went wrong, two commits in it concerning two differents things.

For the frist part https://github.com/PrestaShop/PrestaShop/pull/3999/files

Regards

**Comment by hiousi** [comment]
Hi,

yes you right, I will dot an other PR for the second point.
for this one, What about removing the file_exists test ?

**Comment by gRoussac** [comment]
(Why our answer was not mailed to me ?)

Hi again,

Could you try filtemtime() ? or is_file ?

Regards

**Comment by hiousi** [comment]
(don't know why you did not get the email ;)

file_exists(), filtemtime() or is_file()  end up to the same API method of the Amazon S3 PHP SDK. This operation are very long and cost 10 times a simple GET on a file. It is also a problem when the file is hosted on a CDN.
My logs are full of that kind of calls coming from carriers images and products attributes colors.
There are some other file_exists() here and there...

If you think it could be an improvement to implement a cache for that information, tell me.

regards,

**Comment by gRoussac** [comment]
Hey,

Well Tools::file_exists_cache ?

Regards

**Comment by gRoussac** [comment]
Due tio teh typo this was every time assigned so yes we can consider removing it.

Regards

**Comment by hiousi** [comment]
(just had a review of my github profile settings and double checked my email)

Tools::file_exists_cache yes bof. I will prefer something persistent across requests.
For now I will do a new PR to remove the test.

See you

**Comment by gRoussac** [comment]
ok thanks

**Pull request closed without merging**
