### PR TITLE
Split BO css into multiple bundles

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Today, we load the whole style of the whole BO on every page, splitting the style into some bundles for every pages is avoiding to load unused styles on every pages
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | This PR modifies JS/CSS but there should be no functional change. Consequently every migrated pages should look the same as before :/ . No need to test how the page reacts on input, only how it is displayed (CSS and JS) has been changed.<br/>Especially, look at "translate" pages, I deleted a stylesheet called "_translation_page" that looks not used anymore, couldn't find any style about it inside the BO <br/>⚠️ Also, take some time to review product/orders pages, they are mainly aimed there 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20584)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]
@NeOMakinG Is @eternoendless OK with this change ? I know there is a debate in the frontend world about "load the full CSS once so that navigation is very smooth then" versus "only load the CSS needed for this page and consequently split bundles"

**Comment by NeOMakinG** [comment]
@matks it's @eternoendless himself who asked me to work on this :)

**Review by ksaandev — DISMISSED** [review]
Nice 😁  split bundles look better

**Comment by Robin-Fischer-PS** [comment]
Hi @NeOMakinG ! Could you resolve the conflict ? Thanks :)

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello,

Tested display:

Translations page:
- Modify translation >switch french/english
- Add language > check display on FO
- Export language, select theme "classic" > OK
- Copy

Orders page:
- Add new order from BO
- Update status
- Check order detail
- Deleted order
product page:
- Add new product
- Edit new product
- check preview
- Delete product

Check migrated pages.

**TEST OK**

Thank you @NeOMakinG

**Comment by Progi1984** [comment]
Travis was broken :red_circle:

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @ngodefroy

**Pull request merged**
