### PR TITLE
Fix update of stock counter of selected product in "create new order" page

### LINKED ISSUE #18289: BO - New order page - The stock counter is not updated until a page refresh when a product is added to order
**Describe the bug**

In BO => Orders => Orders => Add an Order when a product is added the quantity is not updated until we refresh the page

#### Expected behavior

The quantity should be updated

#### Steps to Reproduce

1. Go to BO => Orders => Add an Orders
2. Select a customer
3. Select a product and click on "add to cart"
4. See error the quantity is not updated

**Screenshots**

capture d'écran_8

#### Additional information

* PrestaShop version: 1.7.7.x, 1.7.6.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by arouiadib**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | See details below
| Type?             | bug fix
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #18289
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/7297969395
| How to test?      | See details below
| Possible impacts? | See details below

**Overview:**

First of all, one should not forget that there are 2 classes of stock counter "in create new order" page ( with different class names and different behavior).

2 cases

Class 1:  the first counter is updated in 3 cases:
         * When switching between products in "Search results" list (when selecting a product).
         * When adding a selected product to cart.
	 * If a product is removed or quantity updated in "Cart products" list **AND** concerned product is the one selected in "Search results".

Class 2:  is for counter in  "Cart products"  list, this counter has different behavior, it is updated:
         * For a product when its quantity is changed.
	 * For product already added when this product is again added to cart.

Note the existence of two lists: "search results" and "cart products".

**Problems:**

I am the author of the behavior for class 1.  I used  "search results" list in the function I created. Today the same function is used to update class2 counters, while the list that should be used is the  "cart products" list. But I am hugely part of the cause. Let's deep dive in it !  :smiley: 

Back in time, I created `updateStock()` to update just class1. This method uses the EXISTING method `renderStock()`, which was written specifically for class 1. So, I created `updateStock()` with only class1 in mind.
`renderStock()` has evolved and today it takes in charge also updating class 2 counters. This is not a problem since it is just a rendering function. The problem is: `updateStock()` was also updated to take in charge class 2 (since renderStock() is able to do it now) and this is impossible due to:

**1.  asynchronous management:**
To understand it more, let's look at the diagram below:
stock counter diagram

So, `UpdateStock()` tries to update class2 counter while it it is not yet in DOM, because it needs the second event to be emitted.

error chrome

**2.  The two lists are different and have different purposes.**

`this.products` of Product Manager holds the list of results of product search. So this list may contain a product that is not in cart. 

***Conclusion:***

1 `updateStock()` shouldn't update class2 counters as it loops over`this.products` which holds "search results" and not "cart products"

2 As you can see for class2, the first rendering in time is always "overridden" by second rendering, so all the `updateStock()` is useless. 

In my old PR, I only created a front-side solution for class1 only. The sole purpose was user experience, and that by updating class1 stock counter without reloading the whole cart and by updating only `this.products`.Part of the mistake is the naming `updateStock` which misleads further devs making them think class2 counters are also concerned. However, class2 counters should be updated based on AJAX response, in other words during the `renderList()`.

**Solutions:**
- Keep `updateStock()` but rename it. Keep it  just for managing class1, pure front-side and based on `this.products`. It is useful on switching between search results. It also updates on add, change qty and remove but it only updates class1 front-side. Once a new search is performed, the object `this.products` is refreshed by values from server. **For class1, we can use only front-side update since this concerns only selected product from search results.**
- Never rely on `this.products` for updating class2 counters as this object is different from cart products and because it also changes after another search. The update of class2 should be based on AJAX response (the `cartInfo.products`). **For class2, we should not update counter front-side, but server-side.The AJAX response contains `availableStock` parameter that we can use to render stock after cart reloaded.** 

(Note this solution will be available in another PR, this PR fixes only the regression for class1, linked ticket)

**How to test?**

(In Orders/ Create new order page ) This PR updates the stock counter of a selected product/combination when an action is performed on cart for that product/combination. An action can be: Adding to cart, updating quantity in cart, or deleting from cart. Try to perform an action on a product/combination among the above mentioned actions, you will see that the stock counter is updated.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25367)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @arouiadib,

I have an issue following these steps:
1. Go to BO > Orders > Add new Order page
2. Choose a customer
3. Search a product "demo_12" for example  => in stock = 300 
image

4. Add to cart => In stock is updated 
image

5. Search again the same product
6. See error => The Instock is NOK 
image

Is it the same problem as the `Class 2` in your description; in stock is not updated in the product list?

Thanks!

**Comment by Progi1984** [comment]
@arouiadib Thank you for your contribution. I ping you with @khouloudbelguith feedback :)

**Comment by arouiadib** [comment]
Hi @khouloudbelguith and @Progi1984, and sorry for delay.

@khouloudbelguith, thank you for your time. I am aware of what you mentioned. But it is not related to this PR.  If we decide to only fix the regression then we can stick for the moment to this PR. To fix the problem globally (including what you observed), then we should modify the whole approach and create additional AJAX. We just need first to discuss some points product-wise and technical-wise.

I will create a PR to suggest a solution to the problem globally, once I know about the destiny of this one.

**Comment by matks** [comment]
Hi everyone so what do we do? Do we start the discussion with Product team?

> We just need first to discuss some points product-wise and technical-wise.

**Comment by kpodemski** [comment]
@PrestaShop/product-team 

This waits for almost a year guys :-)

**Comment by kpodemski** [comment]
ping again, @PrestaShop/product-team @MatShir

**Comment by kpodemski** [comment]
This PR isn't going anywhere, sorry but I closed it since there is no consensus on what to do.

**Pull request closed without merging**
