### PR TITLE
Fix displayHeader is not available when transplanting modules/hooks

### LINKED ISSUE #10405: displayHeader is not available when transplanting modules/hooks
**Describe the bug**
Whether or not you want to add hook exceptions or transplant a hook into `displayHeader` you can not since it's not in that list.

In my case I had a module which added CSS/JS in the `displayHeader` hook, just like any other module. Since there was a couple of pages (`cart` and `order` in my case) where I didn't want it to be active I added exceptions to it. It worked just fine for the other hooks but `displayHeader` is not available.

**To Reproduce**
1. Try to transplant a module to the `displayHeader` hook
2. When you try to select it in the "Transplant to" select, it's not available. It's not in the list.

**Additionnal information**
PrestaShop version: 1.7.4.2

### PR DESCRIPTION
**Pull request by Prestaworks**
Merge displayhooks with other hooks from module.
Possible to hooks to non display hooks with widget modules if hook function exists.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fixes the issue descripbed in ticket 10405 where widget modules could only be hooked to display hooks.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #10405.
| How to test?      | Please follow instructions in ticket.
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28094)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Logic seems OK for me. Nice find!

**Review by matthieu-rolland — DISMISSED** [review]

**Review by prestaforum — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Prestaworks ,

I have tested the following :
- Transplant a module to hook displayHeader
- Unhook module from displayHeader
- Install my own module created via https://validator.prestashop.com/generator, check displayHeader hook, edit it, unhook it, rehook it to displayHeader

When I unhook a native module from displayHeader and I want to hook it again, I see the displayHeader hook at the end of the list of Transplantation hooks.
Would it be possible to add it alphabetically like it is for the other hooks ?

Screenshot 2022-04-12 at 16 50 38

https://user-images.githubusercontent.com/16019289/162990455-8e839505-4719-4e90-9009-26340d0b14ed.mov

Other than that it looks good to me :)

Thanks!

**Comment by Prestaworks** [comment]
Hi @florine2623 

Nice touch! I have added a sorting of the merged list.

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Prestaworks ,

Looking good ! Thanks for the update. 
It is QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623 & @Prestaworks

**Comment by momo1240** [comment]
Hello guys I have the same issue on Prestashop 1.7.8.10 with prestashop default menu module (ps_mainmenu)
I want to hook the module on displayHeader but it doesn't show on the list
so I made the changes on "classes/module/Module.php" (cleared the cache etc..) reinstalled the module but the issue is still present 
thanks for your help

**Pull request merged**
