### PR TITLE
Validate cart rule actions on load

### LINKED ISSUE #19393: CART RULE - cart rule is applied even when you disabled
#### Describe the bug

If a Cart rule for cheapest product is created but not enabled and if a second cart rule is created and enabled the first one is displayed and enabled in the FO

#### Expected behavior

The cart rule must not be applied and displayed if not enabled

#### Steps to Reproduce

- [ ] Test1
1. Go to the BO => Catalog => Discounts => Create a new cart rule with the following parameters (see the attached screenshots below)
2. Enable the previously created cart rules
3. Go to the FO => Add to the cart demo_11 & demo_6
4. Go to the cart page => The cart rule is correctly applied to the cheapest product ( demo_11 )
5. Go Back to the BO => Catalog => Discounts => and disable the cart rule 
6. Go to the FO again and check the cart => the cart rule is applied and displayed => NOK

> ~7. Go Back to the BO => Catalog => Discounts => Create a new cart rule the parameters of this cart rule don't really matter just create a cart rule with a generated code and a amount of 10 % it's enough~
> ~8.Enable this cart rule~
> ~9. Go to the FO again and check the cart => the newly created cart rule is available~
> ~10. See error => the first created cart rule is applied and displayed even if not enabled in BO~

- [ ] Test2
>Edit by @hibatallahAouadni 

1. FO, add products to cart and apply a voucher
2. BO, edit the voucher date (valid to) to be expired
3. FO, refresh the page the voucher still applied => NOK
4. Delete the voucher, then you will see you can't apply it again => OK

- [ ] Test3
> Edited by Khouloud

Other steps to reproduce the same issue as described here https://github.com/PrestaShop/PrestaShop/issues/27650

**Preparation**
1. Create customer group ID 4.
2. Create a new customer, put him to group 4, set default group 4.
3. Create a cart rule that will apply automatically, cart rule will give a free gift, set group restriction only to 1, 2, 3.

**Actual bug**
1. Log in as the customer you created.
2. Add something to cart and go to cart.
3. Now, go edit that customer in BO, tick that he belongs to group 1.
4. Go back to cart, hit F5. Cart rule will be applied and gift added to cart.
5. Go back to edit customer, un-tick group 1, save.
6. Go back to cart, hit F5. Gift is not removed from cart.
_(7. It's removed when you +- the quantity on your product.)_
**Screen record**
https://drive.google.com/file/d/1SgVUMepMz-XsaUKgafB7aVv9LGnlAYLO/view

**Screenshots**

**Cart rule's parameters**
capture d'écran_35
capture d'écran_36
capture d'écran_37

**The cart rule is disabled in BO**
capture d'écran_43

**But applied and displayed in FO**
capture d'écran_44

#### Additional information

* PrestaShop version:1.7.7.x and 1.7.6.x
* PHP version: 7.2

### LINKED ISSUE #23933: Cart rule is  not removed from the cart when it expires
#### Describe the bug

When a cart rule is applied in the cart and it expires, it is not removed from the cart. The customer can finish the order with the cart rule applied.

#### Steps to Reproduce

1. Create a cart rule that expires in 5 minutes (for example)
image

2. Add a product to the cart and check that cart rule has been added automatically
image

3. Wait for 5 minutes, until the cart rule expires

4. Finish the order. The cart rule is expired but it has been applied:
image

#### Additional information

* PrestaShop version: 1.7.7.3

### LINKED ISSUE #32303: Order creation from cart with expired voucher
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If a coupon with an expiry date is inserted in a cart, but the order is concluded after this expiry, the coupon remains in the cart anyway and the system concludes the order with the expired coupon.
For convenience, I attach a video in which I add a voucher with an expiry date after the date of addition, then I change the expiry date of the voucher to an earlier date, and the system lets me complete the order.

https://user-images.githubusercontent.com/2463965/233968537-3e2d7b3e-cef6-4426-84e2-b9d05808c2c5.mp4

https://user-images.githubusercontent.com/2463965/233968551-fe8f1b0f-b2dd-4d1f-abdc-65aead10c1b9.mp4

### Expected behavior

The system should behave as if the voucher has been deactivated and therefore remove it from the cart.

### Steps to reproduce

1. Create a coupon dated after the current day
2. In the front-office, add the coupon to the cart
3. Change the coupon expiration date to a date before the current day
4. In the front office complete the order
5. The system has created the order including the expired coupon

### PrestaShop version(s) where the bug happened

8.0.x, 8.1.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | This PR slightly improves the validation of cart rules in the shopping cart. It doesn't fix all the issues, but it's a first step in always making the validation reliable. There have been a lot of issues reported regarding this and PR fixes some of them partially, this is why I'm not marking any Issues as "Fixes". Partial backport of https://github.com/PrestaShop/PrestaShop/pull/34875 after discussing it with @kpodemski. **It does not fix ACTIVE, TOTAL QUANTITY AND DATE VALIDITY OF THE VOUCHER.** Test it on some other properties of the cart rule.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Detailed steps are listed below.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7654840172 🟢 
| Fixed issue or discussion?     | This PR is related to #19393, #32303, #23933 but fixes only part of the issues.
| Related PRs       | 
| Sponsor company   | 

### Test scenario 1

1. Make a cart rule with a minimal order value of 100 EUR.
2. Meet the conditions. Add it to the cart.
3. Change the minimal quantity to 200 EUR.
4. Go to the cart, hit F5...
5. WITHOUT PR - Cart rule is not removed from cart. It’s removed when you +- the quantity on any product.
5. WITH PR - Cart rule is removed immediately.

### Test scenario 2

1. Create customer group ID 4.
2. Create a new customer, put him to group 4, set default group 4.
3. Create a cart rule that will apply automatically, cart rule will give a free gift, set group restriction only to 1, 2, 3.
4. Log in as the customer you created.
5. Add something to cart and go to cart.
5. Now, go edit that customer in BO, tick that he belongs to group 1.
7. Go back to cart, hit F5. Cart rule will be applied and gift added to cart.
8. Go back to edit customer, un-tick group 1, save.
9. Go back to cart, hit F5...
10. WITHOUT PR - Gift is not removed from cart. It’s removed when you +- the quantity on any product.
8. WITH PR - Gift is removed immediately.

### CODE REVIEW

**Comment by kpodemski** [comment]
@Hlavtox 

> It does not fix ACTIVE, TOTAL QUANTITY AND DATE VALIDITY OF THE VOUCHER. 

Well... 🤔 It looks like I didn't fully understand what you were trying to do. The reason why I insisted on having it backported is exactly because of the fact that people complain about inactive or outdated rules being accepted in cart :D

If that PR doesn't fix this issue, there is no reason to implement it on the patch version 👍🏻

**Comment by Hlavtox** [comment]
@kpodemski It does fix the issue of many other things. Quantity per customer, minimal amount, country, carrier, group, product restrictions of the voucher. All of this is now validated.

This change must be done anyway, even if I fix the other things in other PR, so I don't understand why you close it.

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
With @Hlavtox we improved the pull request table, so it is now more clear what PR does and fixes and it's worth having those fixes as soon as possible.

**Review by ShaiMagal — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by Hlavtox** [comment]
Bump @PrestaShop/qa-functional

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I tested your PR and it seems good for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by Hlavtox** [comment]
Thank you @paulnoelcholot!!!

**Pull request merged**
