### PR TITLE
Remove unused table ps_order_slip_detail_tax from install

### LINKED ISSUE #22914: No entries in database table ps_order_slip_detail_tax  PS 1.7.x.x
Hello, 

I am now using Prestashop 1.7.x.x since 2017 and I have generated a lot of orderslips during the years but I have no entries in the database table ps_order_slip_detail_tax. Is this just me or do you know about that? 

image

Thank you very much in advance for your answer.

PS 1.7.x.x
current PHP version 7.2.34

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This table is not used anywhere in the core
| Type?             | improvement
| Category?         | IN
| BC breaks?        | yes - The table is no longer created on install
| Deprecations?     | no
| Fixed ticket?     | Fixes #22914
| How to test?      | Validated by automatic tests
| Possible impacts? | Unknown

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24118)

### CODE REVIEW

**Review by PululuK — CHANGES_REQUESTED** [review]
@eternoendless  are you sure that no module uses this table?
Some sql may also fail https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/upgrade/sql/1.7.7.0.sql#L200

**Comment by eternoendless** [comment]
@PululuK yep, there's no reference in the Core to that table. Also, it refers to an id that doesn't exist.

There shouldn't be any problem in 1.7.7.0 because this will only affect the schema of new shops created in 1.7.8 or 1.7.9 (depending on when this PR is merged)

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Comment by boubkerbribri** [comment]
Tested with UI tests : 
- Sanity on Github actions
- Install + Orders + Taxes + Tax rules

=> All tests have passed.
Thanks, @eternoendless!

**Comment by PululuK** [comment]
Thanks @eternoendless

**Comment by sarahdib** [comment]
Thanks @boubkerbribri :)

**Pull request merged**
