### PR TITLE
Fix update order status settings with readonly user

### LINKED ISSUE #29152: BO - Read-only employee can edit an Order Status
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Employee with only View permission can modify an Order Status. 

https://user-images.githubusercontent.com/16019289/180744307-178812bb-534b-4cf9-91b2-bf023c5f12dd.mov

It is not a regression as it is reproduced on 1.7.7.8, 1.7.8.x, 8.0.x, develop

### Expected behavior

The Employee shouldn't be able to edit this and should have a warning saying:
Screenshot 2022-07-25 at 11 18 16

It should be the same behavior as it is in page Design > Image Settings

### Steps to reproduce

1. Go to BO > Team > Profile
2. Create a new profile "stagiaire"
3. Go to Permissions > Choose "stagiaire" > click on "View" for everything
4. Go to Employees > Create new employee with profile "stagiaire"
5. Log out from your current account and Log Into your "stagiaire" account
6. Go to Shop Parameters > Order Settings > Statuses
7. Click on ❌ or ✅ on the statuses
8. See that your modification is Saved

### PrestaShop version(s) where the bug happened

1.7.7.8, 1.7.8.x, 8.0.x, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  develop
| Description?      | Add permission checks
| Type?             | bug fix
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29152 .

### CODE REVIEW

**Comment by ghost** [comment]
1.7.7.X branch ? I think you need to target develop because it's not a regression.

**Comment by FabienPapet** [comment]
I didn't knew which one to target, so I put the oldest one, so it'll be merged back into develop. If you can confirm the target should be `develop` i'll rebase

**Comment by ghost** [comment]
@florine2623  say : _It is not a regression as it is reproduced on 1.7.7.8, 1.7.8.x, 8.0.x, develop_

Normaly it's develop, but she can confirm us

The 1.7.7.x is not supported anymore

**Comment by FabienPapet** [comment]
rebased onto develop as requested

**Comment by PrestaEdit** [comment]
Just as a reminder to doest not forgot later, we need to add an ADR about this kind of return.

Somes, we found a PrestaShopExceptio, somes it's a die() with a <return> and somes it's the errors array that is populated.

**Review by kpodemski — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Comment by kpodemski** [comment]
@Julievrz could you put "Waiting for QA" after you validate the wording? :)

**Comment by ghost** [comment]
Preston add BC Break ? 

Edit : oups i don't looked the history of the description i remove it

**Review by Julievrz — APPROVED** [review]
Wording ✔️

**Comment by AureRita** [comment]
Hi @FabienPapet 

Thank you for your PR, I tested it and it works except that the red notice is writted in white, as we can see here :

https://user-images.githubusercontent.com/100699445/183431441-e42eb2eb-5027-4566-8139-f024787d6ffa.mp4

can you change it in black ? 

Thanks

**Comment by FabienPapet** [comment]
@AureRita This modification is not easy and might be out of the scope of this PR. Plus it can have many impacts on other pages.

**Review by AureRita — APPROVED** [review]

**Pull request merged**
