### PR TITLE
Update Symfony components after 6.4.9 release

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update Symfony components after 6.4.9 release
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| UI Tests          | https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/9718315989 & https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/9718317586
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — APPROVED** [review]

**Comment by nicosomb** [comment]
UI tests are green.

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Waiting for QA team to tell us if we can merge this ;)

**Review by boherm — APPROVED** [review]

**Comment by florine2623** [comment]
UI tests are enough, no need QA functional !

**Pull request merged**
