### PR TITLE
Fix bug where the custom value is not saved if its value is a string equal to "0"

### PR DESCRIPTION
**Pull request by Piervers**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.0.x / 1.7.8.x
| Description?      | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?             | bug fix / improvement / new feature / refacto
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #{issue number here}.
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Comment by ghost** [comment]
Hello,

Thank you for your contribution, can you [open an issue](https://github.com/PrestaShop/PrestaShop/issues/new/choose) so that the QA team can follow and test your changes.

You should also fill the table in the description of your PR.

Thank you again for your contribution.

**Comment by ghost** [comment]
I also saw that you were using the develop branch of your fork, which could cause problems in case of rebase

https://github.com/PrestaShop/PrestaShop/blob/develop/CONTRIBUTING.md

**Review by matks — CHANGES_REQUESTED** [review]
As mentioned by @okom3pom 

@Piervers you need to rework the PR

**Comment by matks** [comment]
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
