### PR TITLE
Enable ChoiceTree javascript in manufacturers form 

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | In manufacturers form enables choice-tree javascript extension for shop-association field. Without enabling, the field is not expanding/collapsing and does not auto-check child checkboxes. Additional minor changes were made: fixed importing javascript asset, it was placed in wrong partial and didn't include parent and enabled help sidebar in view brands page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Go to Sell > Catalog > Brands & Suppliers > Brands. Open create or edit brand form when in multishop context. Shop association field should collapse and expand on arrows (`^`, `>`) click. When checking parent checkbox, the child checkboxes should automatically be checked as well. Also I enabled help sidebar in view brands page.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13508)

### CODE REVIEW

**Comment by zuk3975** [comment]
@matks this little guy is ready :smile:

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@zuk3975 we need a rebase 😉but we got QA validation

**Comment by zuk3975** [comment]
> @zuk3975 we need a rebase but we got QA validation

@matks rebased

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
