### PR TITLE
Update pack stock when order status changes with some conditions ?

### PR DESCRIPTION
**Pull request by maxime-aknin**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.x
| Description?  | E.g when an order is cancelled and this order contains a Pack and this Pack has config value "decrement both" or "decrement only pack", it should update pack stock instead of doing nothing
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Create an order with one Pack, check the stock then cancel the order, the stock is unchanged

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11190)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Please run cs-fixer, you have some coding style issues :)

**Comment by Quetzacoalt91** [comment]
I made a quick investigation in the code ran after the test you modified. If `StockAvailable::updateQuantity(...)` also checks that you product is in a pack, the first test (`!Pack::isPack($product['product_id'])`) could be redundant. If so, it would be better to remove it instead of adding more checks.

To be double checked.

**Comment by Quetzacoalt91** [comment]
(Related PR on `1.6.1.x`: https://github.com/PrestaShop/PrestaShop/pull/8263)

**Comment by Quetzacoalt91** [comment]
Hi,

I cannot reproduce the issue on the branch `1.7.5.x`, Canceling an order with a pack (decrement only pack) works properly. On what version are you running your shop?

**Comment by Quetzacoalt91** [comment]
Hi @maxime-aknin,

Following my last message, I'm closing as "Cannot reproduce". Please ping me if you need to post an update on this PR.

Regards

**Pull request closed without merging**
