### PR TITLE
Navigate between pages in catalog page

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This script is testing whether the pagination and the item per page option is working well on the catalog page
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run this command:  path=full/02_product/15_navigate_between_catalog_pages npm run specific-test -- --URL=URLFrontOffice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9147)

### CODE REVIEW

**Comment by marionf** [comment]
Hello @fatmaBouchekoua 
Is it the test for the feature in Shop parameters > product > pagination ?
I think I don't have written yet the scenario corresponding to this feature
And I will verify it after the code review

**Comment by fatmaBouchekoua** [comment]
Hello @marionf ,
this script is testing the scenario "PS032: Navigate between page in catalog page". There are a video and a description in testlink for this scenario.

**Comment by marionf** [comment]
@fatmaBouchekoua 
Oh yes, I missed it in testlink :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks everyone

**Pull request merged**
