### PR TITLE
[-] CORE: Minor fix on module actions in module page

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
This PR is not related to the current sprint, but fixes an issue with the "upgrade" button which should not appear.

### CODE REVIEW

**Comment by tchauviere** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
@tchauviere so, the "update" action for modules don't realy exists ? Should we have to update route arguments for `ModuleController::moduleAction` ?

**Comment by tchauviere** [comment]
@mickaelandrieu : already done https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/admin/routing_module.yml#L34-L40

**Comment by mickaelandrieu** [comment]
<3 thanks !

**Pull request merged**
