### PR TITLE
Module translations aren't working when using Smarty Extend into TPL

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Currently the selected source is the extend module. Always use $smarty->resource->name to retrieve the template name
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5983
| How to test?  | Follow instruction on Jira..

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9326)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @PierreRambaud

**Comment by tlhuillier** [comment]
Hello.
Seems to me that the error is fixed on Front Office, but still occurs inside Back Office.

Lets say I have a module with some configuration page, and we use smarty extends within it, then we can change translations for those templates but it won't appear when visiting the configuration page.

(using ps 1.7.4.2)

@PierreRambaud @eternoendless

**Comment by eternoendless** [comment]
Hi @tlhuillier would you mind crating a forge ticket for that? Thanks!

**Comment by kpodemski** [comment]
BOOM-5139

You can't translate strings below included file aaaand extended ones are not visible in BO, I think that these are somehow related

**Comment by tlhuillier** [comment]
@eternoendless Done http://forge.prestashop.com/browse/BOOM-6200

**Pull request merged**
