### PR TITLE
Fix availability display logic

### LINKED ISSUE #32437: Setting minimum quantity for sale to 0 breaks availability display logic
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I sell only one unique product in my PrestaShop store (upgraded to 8.03), and I want to maintain its SEO value even when it's sold out. To do so, I'm displaying a "sold" label on the main catalog page, but when I open the sold product the label is changed to "Last item". And this is incorrect.

The problem is that the {$product.availability|print_r} value currently shows "last_remaining_items1,"
It's misleading for customers who think the product is still available, while it's sold out.
image

I've created a [dedicated forum thread](https://www.prestashop.com/forums/topic/1076094-displaying-last-item-instead-of-sold-out-on-a-product-page/) for this

### Expected behavior

_No response_

### Steps to reproduce

1. Create a new product.
2. Set quantity to zero.
3. Set minimum quantity for sale to zero.
4. Deny orders when not in stock.
5. See FO product page in classic - availability is "Last items available".
6. When you set minimum quantity for sale to 1, it works correctly and shows "Sold out".

### PrestaShop version(s) where the bug happened

8.0, 8.1.x

### PHP version(s) where the bug happened

7.4, 8.0

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | Fix availability display logic
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #32437 
| Fixed ticket?     | Fixes #32437 
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Comment by Hlavtox** [comment]
I think I tried this and it doesn't fix the issue properly.

In stock 1 - Quantity wanted 0 = available quantity 0. So it will not pass through your new condition and display out of stock, while there is actually 1 piece in stock.

**Comment by kpodemski** [comment]
@Hlavtox is it a scenario when you have something in cart?

1 product in stock
you add this 1 unit to cart
?

**Comment by mflasquin** [comment]
> I think I tried this and it doesn't fix the issue properly.
> 
> In stock 1 - Quantity wanted 0 = available quantity 0. So it will not pass through your new condition and display out of stock, while there is actually 1 piece in stock.

Maybe we can let the QA check scenarios ?

**Comment by Hlavtox** [comment]
Without PR:
Quantity 0, minimal order 1 = Out of stock ✅ 
Quantity 0, minimal order 0 = Last items in stock 🔴 
Quantity 1, minimal order 0 = Last items in stock ✅ 
Quantity 1, minimal order 1 = Last items in stock ✅

With PR:
Quantity 0, minimal order 1 = Out of stock ✅ 
Quantity 0, minimal order 0 = Out of stock ✅ 
Quantity 1, minimal order 0 = Last items in stock ✅ 
Quantity 1, minimal order 1 = Not enough items in stock 🔴

**Comment by mflasquin** [comment]
> Without PR: Quantity 0, minimal order 1 = Out of stock white_check_mark Quantity 0, minimal order 0 = Last items in stock red_circle Quantity 1, minimal order 0 = Last items in stock white_check_mark Quantity 1, minimal order 1 = Last items in stock white_check_mark
> 
> With PR: Quantity 0, minimal order 1 = Out of stock white_check_mark Quantity 0, minimal order 0 = Out of stock white_check_mark Quantity 1, minimal order 0 = Last items in stock white_check_mark Quantity 1, minimal order 1 = Not enough items in stock red_circle

Thanks @Hlavtox I will check to fix it

**Comment by 0x346e3730** [comment]
Hey @mflasquin gentle reminder that this PR waits further work from your side ;)

**Comment by mflasquin** [comment]
Tests ui : https://github.com/mflasquin/ga.tests.ui.pr/actions/runs/5152584366

**Review by nicosomb — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]
Hi @mflasquin 

Could you add this scenario to `tests/Integration/Adapter/Presenter/Product/ProductLazyArrayTest.php`? There are some other scenarios already, we should make sure to have this as well.

**Review by FabienPapet — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by sallemiines — APPROVED** [review]
Hello @mflasquin 

Thanx for the PR !

- [Tests auto](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5323884357) ok 
- Checked the PR with those scenarios : 

Quantity 0, minimal order 1 = **Out of stock** 
Quantity 0, minimal order 0 = **Out of stock** 
Quantity 1, minimal order 0 = **Last items in stock** 
Quantity 1, minimal order 1 = **Last items in stock**  but when we increment the  quantity, the displayed status will be **Not enough items in stock** 

You can check the attached screen recorder 

https://github.com/PrestaShop/PrestaShop/assets/31663369/226351c8-ff38-4b8d-a948-a69f6a4eed3b



QA :heavy_check_mark: 
Thank you :rocket:

**Comment by mflasquin** [comment]
Thanks @sallemiines

**Pull request merged**
