### PR TITLE
Allow searching brands in choices list of product v2

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The option of minimal results for search to appear was missing, so this PR adds it (Used minimum results of 7, because this way it was done in legacy product page and this is the way we are using in most other similar choice lists)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/30770
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Product v2 description tab. When you have at least 7 brands available, then the brands choice list should contain a search input, where you can search in brands.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
Screenshot 2023-01-09 at 18 12 47

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@zuk3975 I think it's something that we could have documented, it's far from being obvious :D

edit: if it's `select2` specific then, no, no need for a documentation IMHO

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975

**Review by sallemiines — COMMENTED** [review]
Hello @zuk3975 
Thanks for the PR ! LGTM QA :heavy_check_mark: 

Products-•-devprs


Products-•-devprs (1)


Capture-d’écran-du-2023-01-10-10-39-23-png-1273×902-


Thank you :rocket:

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
