### PR TITLE
CO: Fixed old record deletion in addDeliveryPrice

### LINKED ISSUE #9592: [BOOM-5955] Strange behavior after editing a carrier
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5955).

- _**Reporter:**_ khouloud.belguith
- _**Created at:**_ Wed, 11 Jul 2018 18:04:33 +0200

<p>Hi,</p>

<p>After a fresh install PS1.7.4.0, navigate to the BO => IMPROVE => Shipping => Carriers, by default, we have two addresses, for the first one which id=2.<br/>
Try to edit this carrier, then click on save without changing any files, the id of this carrier will be changed.<br/>
In fact, after editing any carrier, a new carrier is created in the Database.</p>

<p>Best regards, Khouloud</p>
        
* How to reproduce the issue ?

1-Fresh Install 1.7.4.0
<br/>
2-Navigate to BO =&gt;  IMPROVE =&gt; Shipping =&gt; Carriers
<br/>
3-Edit a carrier

### PR DESCRIPTION
**Pull request by gfilippakis**
Fixed id_shop_group condition in DELETE statement
Added code for old record removal

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Records from deleted carrier IDs remain in ps_delivery table
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9592
| How to test?  | Create a carrier or edit an existing one and check the records of ps_delivery table.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8816)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Thanks for the report @gfilippakis,

we need a QA validation before considering the acceptance of your patch :)

Anyway, thanks for your contribution :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by matks** [comment]
@marionf if this bug is still happening in 1.7, we should be able to fix it thanks to this PR

**Comment by marionf** [comment]
@khouloudbelguith Could you try to reproduce it with 1.7.6.1 ?

**Comment by khouloudbelguith** [comment]
Hi @matks, @marionf,

Similar issue reported in this ticket

https://github.com/PrestaShop/PrestaShop/issues/9592

Thanks!

**Comment by matks** [comment]
So this PR does 2 things:
- it fixes a bad SQL condition where it's obvious `id_shop` should be `id_shop_group`
- it deletes old `delivery` SQL table records when new `delivery` records are added for the new carrier

What do I mean by "new carrier" ? Actually when carrier is edited, it is, a new carrier is created with new informations and an old record, unmodified, stays hidden in database.

**Comment by matks** [comment]
PR ported to https://github.com/PrestaShop/PrestaShop/pull/15615. Original author is mentioned and credited 😉

**Pull request closed without merging**
