### PR TITLE
Blank lines

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Handle blank lines. Add and remove to meet Symfony standards.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | Nothing to test.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11965)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
We are sorry but we can not review this pull request due to the amount of files changes :/

**Comment by MathiasReker** [comment]
@PierreRambaud The problem is that most of the files has blank lines after PHP doc. I can revert this commit for now, then it will be easy to review :)

**Comment by MathiasReker** [comment]
Better now? :)

**Comment by PierreRambaud** [comment]
Still really hard to review when we have more than 50 files and more than 500 lines change :(

**Comment by matks** [comment]
Dear @MathiasReker, as discussed together and following our [Contributing rules](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#pull-requests-requirements) I must unfortunately close this PR as it is too large to be thoroughly reviewed. Thank you for the contribution.

**Pull request closed without merging**
