### PR TITLE
Install.txt file & documentation link update

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | Install.txt file & documentation link update
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1830 
| How to test?  | -

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
Please wait until I have content to add to that  INSTALL.txt.
Monday at best, tomorrow otherwise.
Thanks!

**Comment by xBorderie** [comment]
Still have to edit Install_PrestaShop.html in order to have redirect to 
`http://doc.prestashop.com/display/PS17/Installing+PrestaShop?utm_source=html_installer`
instead of 
`http://doc.prestashop.com/display/PS16/Installing+PrestaShop?utm_source=html_installer`

**Comment by xBorderie** [comment]
Done.

@AlexEven Can you have a look at the https://github.com/PrestaShop/PrestaShop/pull/7040/commits/a80bb219a0362546ff847c431f073b88f4c3cd78?diff=unified file?

**Comment by xBorderie** [comment]
@aleeks Good to go!

**Comment by aleeks** [comment]
See: https://github.com/PrestaShop/PrestaShop/pull/7064

**Pull request merged**
