### PR TITLE
module ajax position capability

### PR DESCRIPTION
**Pull request by DevNet**
Fix to module ajax position capability

Currently, it's not possible to dispatch the ajaxProcess linked to change list positions since HelperList and from the Module class.

This patch allows you to easily make it possible to access ajaxProcessUpdatePositions since our modules.

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, have you check if adding this will not create some conflict with some others native module like blockcms, using the same DND capability ?

And maybe you have not noticed in : http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Best regards.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by gRoussac** [comment]
@DevNet :+1:

**Comment by xBorderie** [comment]
Hey @DevNet, thank you for this PR!

Sadly, this PR was made on the '1.6' branch, which is not used anymore. 
Could you make it again on the '1.6.1.x' branch so that you get full credit once we merge it? Even better if you do it on the 'develop' branch, so that it lands in PS 1.7 :)

Also, could you answer @jnadaud's question about possible conflicts in other native modules? This would really help us.

Thank you very much!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
