### PR TITLE
Fix Address form not work properly in customer account area

### LINKED ISSUE #34080: Address form not work properly in customer account area
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Tested on demo.prestashop.com
If you go to "account" and click update address (France) you need to enter states.
For some this bug exist only on Firefox or only on Chrome. On one my server with fresh PS install, bug seen in both browsers.
Reopen #33991.
On click Update on address in my-account area, form requesting enter state, even if country without states, Self-fixing only after manipulation with country change.

public function fillWith(array $params = []) called twice. Second call destroys country->id

### Expected behavior

No need enter states by default for France or other country with no states.

### Steps to reproduce
Clean browser cache before.
Go to demo.prestashop.com with 8.1.x version.
PS browser detection must be enabled.
PS must have enabled US country with states.
PS need to default US country (optional).
Ensure that your browser have default eu_US locale.
login as new customer and create address not US, all other without states.
Save address.
Click Update address.
Click Save.
 
https://github.com/PrestaShop/PrestaShop/assets/543458/a57f199d-05ec-4a6e-a859-14b1d1a78a2d

### PrestaShop version(s) where the bug happened

8.1.1 8.1.2

### PHP version(s) where the bug happened

8.2.10

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed issue or discussion?     | Fixes #34080, #35013
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by Hlavtox** [comment]
This looks like a legit fix!!!

@maofree @metacreo Guys could you test it?

**Comment by Maofree** [comment]
Hi @Hlavtox 
yes with this fix the problem is solved

**Comment by metacreo** [comment]
@Hlavtox 
> @maofree @metacreo Guys could you test it?

Tested. Its works. But we have one extra call of fillWith function.
```
public $cnt = 1;
    public function fillWith(array $params = [])
    {
 $this->cnt++;
 @dump($this->cnt);
```
Nothing will be better than my first PR https://github.com/PrestaShop/PrestaShop/pull/34152 #34152
Simple, effective, ps performance+ (no extra call)

**Comment by metacreo** [comment]
>  yes with this fix the problem is solved

@maofree  @Hlavtox not solved still extra (duplicate) call of function

**Review by tleon — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by metacreo** [comment]
It sounds offensive, but this is extra code.
@kpodemski @tleon Look at the code carefully.
`// 1) Update the format if a new id_country was set.` and `// 2) Detect country from address if set` essentially perform the same function.
The problem with the form is not at all in this section of the code.
The problem is that the form is filled one extra time. this happens because we have extra POST from controller. In last function call needed params is missing.
```
    public function fillWith(array $params = [])
    {
@dump($params);
```
Screenshot 2024-01-13 at 05-02-08 Address

All what we need it a move fillWith function call after form submit in controller #34152 .

@kpodemski @tleon As you ca see in screenshot... This is a single form request. But double call of function fillWith. On first call address already present. Second call just destroyed form country.
```
    public function fillWith(array $params = [])
    {
        // This form is tricky: fields may change depending on which country is being selected!
        // Country preselection priority order :
        // 1) Update the format if a new id_country was set.
        // 2) Detect country from browser language settings and matches BO enabled countries
        // 3) Default country set in BO
@dump(array_column(debug_backtrace(), 'function', 'class'));
```
Screenshot 2024-01-13 at 06-24-36 Address

**Comment by metacreo** [comment]
@kpodemski @tleon As you ca see in screenshot... This is a single form request. But double call of function fillWith. On first call address already present. Second call just destroyed form country.

**Comment by Hlavtox** [comment]
@metacreo I understand, but if you move the code, you are not running these steps when creating a new address.

```
3) Detect country from browser language settings and matches BO enabled countries
4) Default country set in BO
```

You can move the line in address controller, but what abou all other usages, modules?

**Comment by metacreo** [comment]
> You can move the line in address controller, but what abou all other usages, modules?

@Hlavtox Detection steel work fine. Tested. it's not related at all in this case.
What do modules have to do with this? if I suggest a change in the controller. It’s not me who is meddling in classes and it’s unclear why.

**Comment by metacreo** [comment]
@Hlavtox 
about modules.... modules developers say you big thanks, because PS is torn by duplicate functions and unnecessary requests. Say you as many modules dev. We need always write additional cache constructions like
```
class SomeClass {
    private $is_executed = true;

  private function someFunc {
     if (!$this->is_executed)
        ...
```
you understand that it’s easier for module developers to do this and not have to prove to you for years that your code is nonsense... and what does this ultimately lead to....

**Comment by metacreo** [comment]
> @metacreo I understand, but if you move the code, you are not running these steps when creating a new address.

@Hlavtox No!, you're wrong. We no need function fillWith on new address! why it needed? You apparently did not carefully look at the tracing result. The function fillWith is called independently of the controller class on editing only. From Core class.
Screenshot 2024-01-13 at 14-29-46 Address
3) Detect country from browser language settings and matches BO enabled countries
4) Default country set in BO
those steps work fine. if no address at all its getting from browser otherwise default. If some address present, no need auto detection, country come from first address. that's how it should be and that's how it works

**Review by AureRita — APPROVED** [review]
Hi @Codencode 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(56).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/187f863a-7e22-42a3-adb3-2feab6a62063)

As you seen it, it seems to work also with Italy.

Link to the auto test : https://github.com/AureRita/testing_pr/actions/runs/7531365923

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Review by metacreo — CHANGES_REQUESTED** [review]
What's wrong with you people? Are there any PHP programmers here at all?
This PR does NOT solve the problem completely, steel duplicate call of this function.
This PR creates additional unnecessary code. 1) and 2) same condition.
Changing this function is not related to this issue at all, because fillWith woks properly.
With this PR, the problem is only masked and not solved.

@Codencode be an honest programmer, you understand that I’m right and this  solution is hardcode. Close or change it.
I agree to close my PR, change yours to change the controller, no need to touch the class

**Comment by Hlavtox** [comment]
@metacreo Please, you tell everyone how we are not programmers, but in your PR you have at least 12th version of the code and with every change you say “THIS IS THE PROPER FIX”, come on.

Your “duplicate call” is there for years and has not been an issue.

**Comment by metacreo** [comment]
> @metacreo Please, you tell everyone how we are not programmers, but in your PR you have at least 12th version of the code and with every change you say “THIS IS THE PROPER FIX”, come on.
> 
> Your “duplicate call” is there for years and has not been an issue.

@Hlavtox Well, that’s essentially what happens. I see that you do not understand or will not fully understand how this works. I understand that this is not a problem for you and it is very bad. I have 12 changes, because I am not used to working on Github and I made them in my repository. You haven't provided a single fact why changing a controller is worse than changing a class.

And avoiding duplication of functions and conditions is a programming priority. You didn't know?

**Comment by matks** [comment]
@metacreo I think it is the 2nd time I must remind you that this GitHub area is under our [Code of Conduct](https://github.com/PrestaShop/PrestaShop/blob/712ba74be8d1dc9f08d32fe42b88c9d706706e0a/CODE_OF_CONDUCT.md)

> Examples of behavior that contributes to creating a positive environment include:

> Using welcoming and inclusive language
Being respectful of differing viewpoints and experiences
Gracefully accepting constructive criticism
Focusing on what is best for the community
Showing empathy towards other community members

Saying "Are there any PHP programmers here at all?" is NOT welcoming and inclusive language. It only frustrates the person in front of you who is very unlikely to listen to your opinion because you just attacked him verbally.

There will be no 3rd warning (= next time it's a ban) ; please remember that nobody here owes you anything, we all have our lives, our backgrounds, and everybody here is trying to contribute to make that project good. There is no place for criticizing other people skills. Being frustrated by code you disagree with is no valid reason to blame people.

**Comment by metacreo** [comment]
@matks Hello,
First of all, I did not attack anyone, I am trying to prevent a mistake that is being made, but I am not being heard.
The expression "Are there any PHP programmers here at all?" not directed specifically to any one participant in the discussion.
If anyone was offended, forgive me.

I provide arguments and arguments, as well as examples with facts. In response I read the ridiculous “what if”, “maybe”. As for the code, there is not a single reason to challenge my assertion. And there are many reasons to support my opinion. But for reasons I don’t understand as a programmer, I make logical and short conclusions. Someone or everyone may not like this, but the truth is on my side.

As for the ban, well, so be it. I won't be too upset. And even this will be useful. I no longer have to waste time helping the project, there are many others.

**Comment by Codencode** [comment]
Hi @metacreo,
my first solution was similar to yours and you know it because you rightly said that you had already proposed that type of solution.
Only then it was pointed out to me that I needed to intervene in the **CustomerAddressForm::fillWith()** method and I did.

I also think like you, but if someone who is part of the **Prestashop project** (I'm referring to @Hlavtox - https://www.prestashop-project.org/project-organization/people-and-roles/) gives me advice, I follow it, also because the important thing is to solve the problem, even if maybe the first solution avoids a call duplicated to the **fillWith** method.

**Comment by metacreo** [comment]
> Hi @metacreo, my first solution was similar to yours and you know it because you rightly said that you had already proposed that type of solution. Only then it was pointed out to me that I needed to intervene in the **CustomerAddressForm::fillWith()** method and I did.
> 
> I also think like you, but if someone who is part of the **Prestashop project** (I'm referring to @Hlavtox - https://www.prestashop-project.org/project-organization/people-and-roles/) gives me advice, I follow it, also because the important thing is to solve the problem, even if maybe the first solution avoids a call duplicated to the **fillWith** method.

@Codencode absolutely right, you see and understand the problem yourself. But unfortunately, this cannot be called a “solution of the problem.” It's called a little differently. Sorry, for example "a** lic***g".  😂

**Comment by kpodemski** [comment]
I don't see any huge performance flaws with a duplicate call of "fillWith", but I agree that we could eventually get rid of this duplication as well. That being said, if this fix resolves the original issue and doesn't bring any regressions, we could accept it as is and improve the controller later.

**Comment by metacreo** [comment]
> I don't see any huge performance flaws with a duplicate call of "fillWith", but I agree that we could eventually get rid of this duplication as well. That being said, if this fix resolves the original issue and doesn't bring any regressions, we could accept it as is and improve the controller later.

@kpodemski The fact is that changing the controller solves the problem, and changing the core class creates even more additional code. In this case, extra (no needed) code appears in the class. fillWith function woks as well at this moment and no need to be changed. fillWith NOT calling on new addr creation. Also changing controller is no depend on any (modules... etc..)

@kpodemski  huge or not it still Double call. Сollect such little things from all over the engine and get brakes.

**Comment by metacreo** [comment]
@kpodemski  In your opinion, if it’s only a little bad, then you can pour it into the engine? why not just change the controller? this will not affect at all and the problem will be solved correctly.

**Comment by Hlavtox** [comment]
It was broken inside fillWith method, it will be fixed inside fillWith method. End of story.

Further optimizations and cleaning can be done in another PRs for develp branch.

@kpodemski Can you please once more test if it works properly now, all 4 scenarios in the form?

**Pull request merged**
