### PR TITLE
Add installed modules to quick access

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add installed modules to quick access
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/STAB-62
| How to test?  | install a new shop & check your quick access

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by basma-yangui-prestashop** [comment]
@aleeks I find the installed modules correctly added to the quick access but it leads to the DashBoard and not to the installed modules page

**Comment by maximebiloe** [comment]
We just tested on another computer with a clean install and it's working.

capture d ecran 2017-01-05 a 11 47 54

When I click, I'm redirected to the installed modules page.

**Comment by vincentbz** [comment]
Hi,

It seems that when we use a vhost, it doesn't work. Is it easy to fix ? Is it something common ?

**Comment by maximebiloe** [comment]
I can confirm that even the "New Product" link doesn't work when using a virtual host

**Comment by mickaelandrieu** [comment]
So, this need an extra work :) thank you @basma-yangui-prestashop

**Comment by aleeks** [comment]
@basma-yangui-prestashop it's updated! Can you check please! all system :p

**Comment by basma-yangui-prestashop** [comment]
It's OK @aleeks! Thank you ;)

**Pull request merged**
