### PR TITLE
Merge 8.0.x into develop 

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.0.x into develop 
| Type?             | improvement
| Category?         | ME
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? |  ~

### CODE REVIEW

**Comment by nicosomb** [comment]
Tests launched here: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/3739015378

**Review by atomiix — DISMISSED** [review]

**Comment by nicosomb** [comment]
Tests are here https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/3741379773

**Review by matks — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @nicosomb ,

Thanks for the launch of the automated tests.

The following was tested during the quick session of exploratory test:
- BO PPV1 & PPV2 and Order page
- FO Customer account and Order

It is looking good.
It is QA ✅

**Comment by jolelievre** [comment]
Thanks @florine2623 and @nicosomb

**Pull request merged**
