### PR TITLE
Update Symfony components after 6.4.8 release

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update Symfony components after 6.4.8 release
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/9388649924
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by nicosomb** [comment]
UI tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/9396208321

**Comment by jolelievre** [comment]
> UI tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/9396208321

It's ok the PR was already validated by https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/9388649924

**Pull request merged**
