### PR TITLE
[*] MO : Blocklanguages add hreflang and rel alternate to the links for a better SEO and avoid duplicate content

### PR DESCRIPTION
**Pull request by cgordenne**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi again

Thank you for your PR and contribution.

Best regards

**Comment by Soullivaneuh** [comment]
I think this should be more on the `head` section according to
[Google Webmaster tools documentation](https://support.google.com/webmasters/answer/189077?hl=en).

@gRoussac Should I contribute on prestashop core or blocklanguage?

**Comment by firstred** [comment]
Ah, wow! Didn't notice this PR until now. So simple, yet so powerful.

Thanks for this PR!

@Soullivaneuh I'd say, go for this file: https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/_partials/head.tpl

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh I'd say, go for this file: 
> https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/_partials/head.tpl

Any chance to be accepted on 1.6 version?

**Pull request merged**
