### PR TITLE
Fixed mass action fields positioning in admin catalog page

### PR DESCRIPTION
**Pull request by LittleBigDev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | New products catalog's content flex rows are aligning (vertically) their items. We needed an exception for the "actions" row (mass action + filter by category)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [BOOM-4395](http://forge.prestashop.com/browse/BOOM-4395)
| How to test?  | Go to admin catalog page, expand / collapse the categories tree. Mass action filters vertical position should not change.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8565)

### CODE REVIEW

**Comment by eternoendless** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[admin-dev/themes/new-theme/scss/pages/_products_catalog.scss, line 14 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8565#-L-BIYe5SzgwNFyNKdqu:-L-BIYe5SzgwNFyNKdqv:b-y18nx6) ([raw file](https://github.com/prestashop/prestashop/blob/37155dba972541960734f7cee98ba9cc212f0877/admin-dev/themes/new-theme/scss/pages/_products_catalog.scss#L14)):*
> ```SCSS
>       align-items: center;
> 
>       &#catalog-actions {
> ```

Being that this is an id, and that ids are supposed to be unique, there's no need to over specify this selector as `.products-catalog > .content . row#catalog-actions`.

I think it would be simpler just to make it `.products-catalog #catalog-actions` (keeping `.products-catalog` for "namespacing" purposes)

---

*[src/PrestaShopBundle/Resources/views/Admin/Product/catalog.html.twig, line 77 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8565#-L-BJJg-4E2KHso_jY93:-L-BJJg-4E2KHso_jY94:b-547hdd) ([raw file](https://github.com/prestashop/prestashop/blob/37155dba972541960734f7cee98ba9cc212f0877/src/PrestaShopBundle/Resources/views/Admin/Product/catalog.html.twig#L77)):*
> ```Twig
>       </div>
> 
>       <div id="catalog-actions" class="row">
> ```

Can we rename this to `catalog-mass-actions` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8565)*

**Review by eternoendless — CHANGES_REQUESTED** [review]
Just some small changes needed

**Comment by LittleBigDev** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[admin-dev/themes/new-theme/scss/pages/_products_catalog.scss, line 14 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8565#-L-BIYe5SzgwNFyNKdqu:-L-BJxAinBeSS1XofLT-:bebrt1w) ([raw file](https://github.com/prestashop/prestashop/blob/37155dba972541960734f7cee98ba9cc212f0877/admin-dev/themes/new-theme/scss/pages/_products_catalog.scss#L14)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Being that this is an id, and that ids are supposed to be unique, there's no need to over specify this selector as `.products-catalog > .content . row#catalog-actions`.

I think it would be simpler just to make it `.products-catalog #catalog-actions` (keeping `.products-catalog` for "namespacing" purposes)
</blockquote></details>

Will do

---

*[src/PrestaShopBundle/Resources/views/Admin/Product/catalog.html.twig, line 77 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8565#-L-BJJg-4E2KHso_jY93:-L-BJnGkg0RPpYw62CVn:b1sh3yo) ([raw file](https://github.com/prestashop/prestashop/blob/37155dba972541960734f7cee98ba9cc212f0877/src/PrestaShopBundle/Resources/views/Admin/Product/catalog.html.twig#L77)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Can we rename this to `catalog-mass-actions` ?
</blockquote></details>

This row contains also the category filter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8565)*

**Comment by eternoendless** [comment]
Assets need to be rebuilt

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8565#-:-L-CTz6TH30R5ySkPTMy:bryqddt)*

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8565#-:-L-CXsQEcV_rOWVlaTU_:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @LittleBigDev

**Pull request merged**
