### PR TITLE
Bring back vat number to address on order view

### LINKED ISSUE #22830: Missing VAT number in Order view
#### Describe the bug

In new version - 1.7.7.1 VAT number in OrderPreview is not dispalyed.

#### Expected behavior

There should be a VAT number in Invoicing Address

#### Steps to Reproduce

1. Go to 'Orders'
2. Click on 'Order detail (loupe with + sign)'
3. See  VAT number is missing

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/22830
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22830 .
| How to test?      | Order something with vat number filled in address or just edit address from order and add it
| Possible impacts? | n/a
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22841)

### CODE REVIEW

**Comment by matks** [comment]
Hi @kpodemski what is the BC break ? Is it the fact the parameter is added in the middle of other parameters?

If yes, we can quite simply avoid the BC break by adding it as the last parameter instead, with a default value or nullable? 🤔

**Comment by kpodemski** [comment]
@matks if we can allow it to be nullable then ok, I can change it

**Comment by mateusz-szafraniec** [comment]
Works as it should.

**Review by mateusz-szafraniec — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by Arman-Hosseini — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @kpodemski :stuck_out_tongue: 

Thanks for your PR, it's QA :heavy_check_mark: !

I tested : 

- Test display VAT Number on Order Page
- Test display VAT Number on Invoice generated (via Generate invoice and via Payment accepted)
- Test display VAT Number on Delivery Form
- Test display in FO
- Test display Invoice by Mail
- Test display Invoice on Order in FO

pr 22841 proof

**Comment by PierreRambaud** [comment]
Thank you @kpodemski

**Pull request merged**
