### PR TITLE
Remove duplicates from smarty.config.inc.php

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Removes duplicates and fixes order
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No need, just a refacto.
| Fixed ticket?     | -
| Related PRs       | #33136
| Sponsor company   | -

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Nice catch, thanks @SharakPL

**Review by Hlavtox — APPROVED** [review]
Checked the methods one by one, no method removed, no method is duplicate.

Ping @Robin-Fischer-PS - can be merged without QA, if all test suites are green. 👍

**Comment by SharakPL** [comment]
https://github.com/SharakPL/ga.tests.ui.pr/actions/runs/5782889212 tests fail on modules - don't know why, can't be related to this PR.

**Comment by Hlavtox** [comment]
@SharakPL Not related, something is wrong with the module. 🤷

**Review by LouisAUTHIE — APPROVED** [review]

**Comment by SharakPL** [comment]
> @SharakPL Not related, something is wrong with the module. 🤷

Then otherwise it's green

**Review by aniszr — APPROVED** [review]
Hello @SharakPL 

I tested your PR, and it's LGTM:heavy_check_mark: 

Auto Test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5786252887 :heavy_check_mark: 

QA:heavy_check_mark: 

Thanks!

**Pull request merged**
