### PR TITLE
Set order update date on address change

### PR DESCRIPTION
**Pull request by hiousi**
Set order update date when delivery or billing address is changed

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Set order update date when delivery or billing address is changed
| Type?         | bug fix 
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | edit address from order in BO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10847)

https://github.com/PrestaShop/PrestaShop/pull/10847#event-2154468884

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12963)

### CODE REVIEW

**Comment by matks** [comment]
Thank you for your contribution ! As this changes the project behavior, I ask @colinegin to have a look.

@colinegin this PR modifies the project so that __when an address is modified, if there is an order linked to this address, the "last updated at" of the order is updated__. Wdyt ?

**Comment by hiousi** [comment]
A very small PR for a minor issue, but lots of our Rest call do not see updated orders. This issue is open since 1.6, I hope my PR will be merged soon. @marionf

**Comment by marionf** [comment]
Hello @hiousi 

I tried on develop branch to change the delivery address and invoice address for an order without your PR and the date_upd field in orders table is already updated

**Comment by hiousi** [comment]
@marionf 
This PR applies to AdminAddressesController not AdminOrdersController.
From where in admin did you change the address?

**Comment by marionf** [comment]
@hiousi 

Here, when you click on edit it's AdminAddressesController

capture d'écran_1430

**Comment by hiousi** [comment]
Same controller, but different parameters in URL that fire different part of code.

So, yes, it will work from order page. But won't update date if you change the address from /customer/address.

Please got to  /customer/address (client/adresse) on left menu, and try to change the address.

**Comment by marionf** [comment]
I tried with your PR:

I have an order ID 2 where id_address_delivery and id_address_invoice is 4
I go in Customers > Address and edit address 4
date_upd is well updated in address table but not in orders table

capture d'écran_1435

capture d'écran_1436

capture d'écran_1437

capture d'écran_1438

**Comment by hiousi** [comment]
yes you are right: my  PR is not that usefull since I found that doing an update in an address changes it in all orders using it, even the ones that are already shipped or invoiced.
Worse, it will update invoices! Rewriting invoices is a violation of laws in my country.

I've decided to completely disallow AdminAddressesController, and will wait for something more compliant with my local regulations.

thanks for your time.

**Comment by marionf** [comment]
@hiousi 

If you want to update an address for only one order, you can do it in the order page directly
This way, it will not update the address if it used for other orders
Can you close your PR if it's not usefull ?

**Comment by hiousi** [comment]
I close this PR, but because it does not solve the issue, I open a new bug report :  
https://github.com/PrestaShop/PrestaShop/issues/13537
and it reveals an other issue:
https://github.com/PrestaShop/PrestaShop/issues/13539

**Comment by matks** [comment]
> I close this PR, but because it does not solve the issue, I open a new bug report :
> #13537
> and it reveals an other issue:
> #13539

Not fair, one PR down, 2 issues up 😄 we should try to do the opposite

Joking aside, thank you for the contributions 😉

**Comment by hiousi** [comment]
@matks I understand your view/joke. You get how I'm slow on seeing the big picture. 
I'm a little cold in doing the opposite (you mean pushing PRs?) since those issues are coming from the very old times, and all the work discussing about them is taken from writing code. 

I was thinking of copying addresses when an order or invoice is created (cutting down references to address table in orders). that's a big change in code and SQL. I would not go in writing such a PR without consentment of your team.

Do you have another plan or idea to solve those issues?

**Comment by matks** [comment]
> I was thinking of copying addresses when an order or invoice is created (cutting down references to address table in orders). that's a big change in code and SQL. I would not go in writing such a PR without consentment of your team.
> 
> Do you have another plan or idea to solve those issues?

Your way of doing it, `copying addresses when an order or invoice` is the right one as far as I know.

The issue you have raised will be inserted into the roadmap and compared to other issues in order to define its priority. Indeed that is a both a huge work and a huge behavior change for prestashop.

**Pull request closed without merging**
