### PR TITLE
Fix CCC error for path with version

### PR DESCRIPTION
**Pull request by ComonSoft**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | Fix error in CCC style sheet and javascript when there is a version number added to uri.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Activate in back office CCC for stylesheet and javascript, if you have js or css added with version number with modules, header nor bottom concatenated files are no more corrupted.
| Fixed issue or discussion?     | Fixes ##35341
| Related PRs       | no
| Sponsor company   | @ComonSoft

### CODE REVIEW

**Comment by kpodemski** [comment]
Hi @ComonSoft 

It's quite an important fix. Could you rebase onto `8.1.x` branch?

**Comment by ComonSoft** [comment]
> Hi @ComonSoft
> 
> It's quite an important fix. Could you rebase onto `8.1.x` branch?

When I try to rebase, git wants to commit 4225 files instead of my changed files only!?

**Comment by kpodemski** [comment]
Maybe this tutorial will give you a better understanding of how to do that:
https://build.prestashop-project.org/howtos/misc/rebasing-your-git-branch/

Another option is to close this PR and open a new one on the `8.1.x` branch 👍🏻

**Comment by ComonSoft** [comment]
> Maybe this tutorial will give you a better understanding of how to do that: https://build.prestashop-project.org/howtos/misc/rebasing-your-git-branch/
> 
> Another option is to close this PR and open a new one on the `8.1.x` branch 👍🏻

I cannot push into 8.1.x branch, error not authorized :-(

**Comment by Hlavtox** [comment]
@ComonSoft I could rebase it for you, but you based the PR on develop branch. I think it will be better to open a new PR. 👍

**Comment by ComonSoft** [comment]
> @ComonSoft I could rebase it for you, but you based the PR on develop branch. I think it will be better to open a new PR. 👍

When I try to commit to branch 8.1.x with Github windows desktop, I got an error while I'm connected
image

**Comment by Hlavtox** [comment]
@ComonSoft First off - you are editing 8.1.x branch directly, that's not good, create separate branch for this PR based on 8.1.x.

Also, I see `push upstream` on the top, not sure how did you call your remotes, but upstream is usually this repository, you must push to `https://github.com/ComonSoft/PrestaShop`.

**Comment by ComonSoft** [comment]
> @ComonSoft First off - you are editing 8.1.x branch directly, that's not good, create separate branch for this PR based on 8.1.x.
> 
I'm sorry but I don't know how to make a commit to 8.1.x. 
What I did:
- clone Prestahsop with Github desktop
- select branch 8.1.x
- modified sources
- commit to 8.1.x
- and try Push upstream

What's wrong?

**Comment by kpodemski** [comment]
@ComonSoft 

You should fork the PrestaShop repository to your Github account, clone your repo, create a new branch based on 8.1.x, modify the files, push the branch back to your repository. Then, you create a pull request. You cannot modify PrestaShop's repository directly :)

**Comment by Hlavtox** [comment]
@ComonSoft You need to do this.

- clone Prestashop with Github desktop
- select branch 8.1.x
- checkout/switch to a new branch based on 8.1.x, called something like `fix-ccc`
- modified sources
- commit to `fix-ccc`
- push to origin

**Comment by boherm** [comment]
Hi @ComonSoft! Thanks for your first contribution ;)

> What's wrong?

You can't do this way, because you aren't the owner of this repository, and also for security!

But to contribute, you can fork this repository, clone your own fork into your local machine, create a branch on it and commit the diffs of the files you want. After you need to push this branch directly on your fork, and then you can create a new Pull Request to ask us to merge your branch in your fork with your modifications into the 8.1.x branch in the PrestaShop official repository.

I hope this small explanation can help you! :)

EDIT: Oh, you have some help already ahah! Thanks guys!

**Comment by SharakPL** [comment]
Closing in favor of #35565

**Pull request closed without merging**
