### PR TITLE
Use official Smarty lib

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR brings back smarty/smarty into the composer.json, allowing PrestaShop to get the latest changes. This PR goes with the PHP 7.2 compatibility and https://github.com/PrestaShop/TranslationToolsBundle/pull/39
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | I see 3 main things to check:

* Theme export, via cli or back-office
* Testing the basic features (already covered by the tests?)
* Testing the child/parent themes feature.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8566)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
I don't have rights on TranslationToolsBundle, can someone review and merge the related pr?

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 how the QA team should test it? I'm not really sure :/

**Comment by Quetzacoalt91** [comment]
I see 3 main things to check:

* Theme export, via cli or back-office
* Testing the basic features (already covered by the tests?)
* Testing the child/parent themes feature.

**Comment by marionf** [comment]
@Quetzacoalt91 
I have an exception when I try to clear the cache in BO
capture du 2017-12-04 18-07-38

**Comment by Quetzacoalt91** [comment]
ping @mickaelandrieu

@marionf, this issue is actually unrelated to the PR.

```

**Comment by Quetzacoalt91** [comment]
ping @mickaelandrieu

@marionf, this issue is actually unrelated to the PR. I came back to the branch `develop`, and requested the translation bundle before the merge of its dependency:

```diff
diff --git i/composer.json w/composer.json
index a33a7ba26a..9ce7627458 100644
--- i/composer.json
+++ w/composer.json
@@ -25,7 +25,7 @@
         "symfony/monolog-bundle": "^3.1.0",
         "sensio/distribution-bundle": "^5.0.19",
         "sensio/framework-extra-bundle": "^3.0.2",
-        "prestashop/translationtools-bundle": "dev-master",
+        "prestashop/translationtools-bundle": "dev-master#736c93cfd815015083e54010090bc33fd1585734",
         "tecnickcom/tcpdf": "6.2.12",
         "composer/installers": "1.0.21",
         "icanboogie/cldr": "1.3.9",
```

but the issue still occurs.

It seems the kernel is not aware yet of the new service container during the script exection. Making it fail when we try to update the translation catalog with the old container.

Please go on the review. I'll try to fix it at the same time.

**Comment by Quetzacoalt91** [comment]
I also have the issue encountered on #8515, regarding 
```
Call to undefined method Doctrine\Bundle\DoctrineCacheBundle\Command\ContainsCommand::getDefaultName()
```
Could be related to the dropped cache as well.

**Comment by Quetzacoalt91** [comment]
@marionf, that issue was actually linked to that PR. Cannot explain in details, but I had to get rid of Symfony 3.4 on this branch.
If Travis check switches to green, you may go on. :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thank you @Quetzacoalt91

**Pull request merged**
