### PR TITLE
Notification after theme reset, warning about images regeneration

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | refs https://github.com/PrestaShop/PrestaShop/pull/7553
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | reset theme to defaults
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by xBorderie** [comment]
Wording looks good to me!

Well, on second thought, maybe it could be improved upon.
How about:
"Your theme has been correctly reset to its default settings. You may want to regenerate your images. See the Improve > Design > Images Settings screen for the 'Regenerate thumbnails' button."

What do you think, @AlexEven ?

**Comment by AlexEven** [comment]
@xBorderie sounds good to me!

@kpodemski could you please change the domains to Admin.Design.Notification? Admin.Notifications is used for general notifications that can be found on any page. This one is specific to the Design section.

Thank you!

**Comment by aleeks** [comment]
Hello @kpodemski 
Can you rebase & change the domain like @AlexEven said please ?!!

Regards

**Comment by aleeks** [comment]
Tested, ok & thank you @kpodemski !

**Pull request merged**
