### PR TITLE
Fix throw InstallControllerHttpSystem::trans during installation process

### LINKED ISSUE #21134: Fatal Error during installation process
#### Describe the bug

Fatal Error during installation process 

#### Expected behavior

The trans() function should in translator not InstallControllerHttpSystem.

#### Steps to Reproduce

1. Download [develop branch](https://github.com/PrestaShop/PrestaShop) 
2. To get this message you must have at least one of the required extension disabled (Ex.: Disable **Intl** or **CURL**) 
3. Try to install

**Screenshots**

image

#### Additional information

* PrestaShop version: develop, 1.7.7.x
* PHP version: N/A
* By : @mushroot 
* PR : https://github.com/PrestaShop/PrestaShop/pull/20201

### PR DESCRIPTION
**Pull request by mushroot**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x 
| Description?  | The trans() function should in translator not InstallControllerHttpSystem.
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21134 
| How to test?  | tigger errorBlock error in install.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20201)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @mushroot  it seems there is some errors with travis can you check this please ?

**Comment by Progi1984** [comment]
@SD1982 It's OK now ;)

**Comment by SD1982** [comment]
hi @mushroot Can you provide us a test scenario please ?

**Review by PululuK — DISMISSED** [review]

**Comment by PululuK** [comment]
> hi @mushroot Can you provide us a test scenario please ?

image

**Review by kpodemski — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PululuK Sorry it's not a scenario. It's a screenshot :rofl:.

**Comment by PululuK** [comment]
> @PululuK Sorry it's not a scenario. It's a screenshot rofl.

😅 See https://github.com/PrestaShop/PrestaShop/issues/21134

Thank you @Progi1984

**Comment by SimonGrn** [comment]
Hello,

we need (as usual, you know the drill) to validate the issue before accepting a PR. We sadly are not able to reproduce the scenario linked in #21134 .
Please help us find the root cause of the problem in the issue comments thread.

Thank you !

**Comment by PululuK** [comment]
> Hello,
> 
> we need (as usual, you know the drill) to validate the issue before accepting a PR. We sadly are not able to reproduce the scenario linked in #21134 .
> Please help us find the root cause of the problem in the issue comments thread.
> 
> Thank you !

Hi @SimonGrn 
I just updated the PR. Could you follow step 2 please ?

**Comment by marionf** [comment]
Hello @mushroot  

As the issue is a minor regression of the 1.7.7 it should be fixed in 1.7.7.x
Could you please rebase your PR on 1.7.7.x branch ?

**Comment by PierreRambaud** [comment]
PR rebased

**Review by PierreRambaud — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SimonGrn** [comment]
Without the PR: 
image

With the PR : 
image

LGTM :heavy_check_mark:

**Comment by Progi1984** [comment]
Thanks @mushroot & @SimonGrn

**Pull request merged**
