### PR TITLE
[-] CORE : wrong language link on mail when change order status on BO

### PR DESCRIPTION
**Pull request by themella**
When you change order status from BO you will send link to email template whit BO context language and not with customer language.

### CODE REVIEW

**Comment by jnadaud** [comment]
Hi,

Thank you for your contribution.
What's happen if you send an email when you are not in a cart context ?

Best regards.

**Comment by themella** [comment]
Is a good reply is better put a condition like :

if (Context::getContext()->cart->id_lang)
{
  $template_lang_id=Context::getContext()->cart->id_lang;
}
else
{
  $template_lang_id=Context::getContext()->language->id;
}
$template_vars['{shop_url}'] = Context::getContext()->link->getPageLink('index', true, $template_lang_id, null, false, $id_shop);
$template_vars['{my_account_url}'] = Context::getContext()->link->getPageLink('my-account', true, $template_lang_id, null, false, $id_shop);
$template_vars['{guest_tracking_url}'] = Context::getContext()->link->getPageLink('guest-tracking', true, $template_lang_id, null, false, $id_shop);
$template_vars['{history_url}'] = Context::getContext()->link->getPageLink('history', true, $template_lang_id, null, false, $id_shop);

But need to modify cause you send link in wrong language when you change order status from BO

Cordiali Saluti

[roberto]
[codeispoetry]
[firma_ambiente]
[avviso_di_riservatezza]


Da: Jérôme Nadaud [mailto:notifications@github.com]
Inviato: mercoledì 4 novembre 2015 16:38
A: PrestaShop/PrestaShop
Cc: Roberto Bottazzi
Oggetto: Re: [PrestaShop] Bug fix wrong language link (#4393)


Hi,

Thank you for your contribution.
What's happen if you send an email when you are not in a cart context ?

Best regards.

-
Reply to this email directly or view it on GitHub<https://github.com/PrestaShop/PrestaShop/pull/4393#issuecomment-153765680>.

________________________________
Total Control Panel

Login<https://asp.reflexion.net/login?domain=pronesis.it>


A: roberto.bottazzi@pronesis.it<https://asp.reflexion.net/address-properties?aID=49045388&domain=pronesis.it>

From: bounces+848413-b161-roberto.bottazzi=pronesis.it@sgmail.github.com<mailto:bounces+848413-b161-roberto.bottazzi=pronesis.it@sgmail.github.com>


Score del messaggio: 1

Alto (60): Pass

Livello di Blocco dello Spam: Medium

Medio (75): Pass


Basso (90): Pass

Aggiungi<https://asp.reflexion.net/FooterAction?ver=3&bl-sender-address=1&hID=12936711811&domain=pronesis.it>(Enterprise<https://asp.reflexion.net/FooterAction?ver=3&ent=1&bl-sender-address=1&hID=12936711811&domain=pronesis.it>) questo mittente alla block list

Aggiungi<https://asp.reflexion.net/FooterAction?ver=3&bl-sender-domain=1&hID=12936711811&domain=pronesis.it>(Enterprise<https://asp.reflexion.net/FooterAction?ver=3&ent=1&bl-sender-domain=1&hID=12936711811&domain=pronesis.it>) sgmail.github.com alla block list



Hai ricevuto questo messaggio perchè lo Score ad esso attribuito non eccede il tuo Livello di Blocco dello Spam.

**Comment by xBorderie** [comment]
Hey Themella,

When contributing to PrestaShop, could you follow these best-practices for commit/PR titles?
http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Thank you very much!

**Comment by themella** [comment]
Done i think.

Is correct now?

**Comment by xBorderie** [comment]
A developer will soon review your PR, thank you!

**Comment by 7starsone** [comment]
Hello, may I know why this edit...
https://github.com/PrestaShop/PrestaShop/pull/4393/files

is still not on master 1.6 ?
 
even if ps updated... again issues with lang links on the email when change order status...

thanks

**Comment by xBorderie** [comment]
@7starsone This PR was made on the `develop` branch, from which we build PS 1.7. It has not yet been merged because it has not been fully reviewed by the team.
If you say that the issue is also on 1.6, then we might decide to port it to the `1.6.1.x` branch.

**Comment by 7starsone** [comment]
@xBorderie yes, indeed...the issue was initially on 1.6...
thanks

**Comment by xBorderie** [comment]
The thing is, there's been changes on the classes/Mail.php file since then, and the fix cannot be merged right now.
@themella, could you rebase your PR? Thanks:

**Comment by antoin-m** [comment]
Thank you @themella !

I cherry-picked your PR here https://github.com/PrestaShop/PrestaShop/pull/7483

**Comment by 7starsone** [comment]
Hello, despite this change...
unfortunately, I noticed that when one of my customers replied to the "Shipped" status mail...

still there were the default lang links instead of the customer lang...
so, how's that possible?
thanks

**Comment by 7starsone** [comment]
what's the difference between

I used
`if (Context::getContext()->cart->id_lang)...`

Do I need this, instead ?
`if (!is_null(Context::getContext()->cart) && !is_null(Context::getContext()->cart->id_lang))`

or the issue is somewhere else?

**Comment by 7starsone** [comment]
So, I also did it with a text installation **1.6.1.13**
where this fix seems not applied?

anyway,
```
1) place the order with customer eg. from Germany
2) pay by bankwire
3) the 1st email (Awaiting payment by bank transfer) is sent with the correct links...
4) If you accept the payment by BO links are wrong, instead
5) Change the status to Shipped, links are wrong again
```

**Comment by 7starsone** [comment]
another:

```
1) customer from Germany and bought with german language
2) after the payment accepted status, it gets the PDF attachment in the default shop lang instead of german... despite PDF rows are already translated
```
this should be absolutely avoided, under these conditions is impossible to offer a good service to customers from other countries....

**Comment by 7starsone** [comment]
please, let me explain this concept:
sometimes I don't understand why you makes it difficult when it's easy, I can't understand your code logic.

```
1) you're on the BO order page
2) the order page should be also related to the **customer**, not only to cart...
in reality, what "cart" has to do here if not for some order numbers?
3) you query the database for customer country/lang, cart is not really needed
4) you send the correct email and PDF, for sure
```
this is my logic, why not yours?
anyway, replaced
`if (Context::getContext()->cart->id_lang)...`
with
`if (!is_null(Context::getContext()->cart) && !is_null(Context::getContext()->cart->id_lang))`

it **seems** working, but I'm not sure... because in my opinion this routine is wrong by concept
thanks

**Comment by xBorderie** [comment]
Hello @7starsone,

As I wrote earlier, the fix has not yet landed on the 1.6 branch, only on the 1.7 branch.
That might be why applying the fix yourself does not fully work

Instead of commenting on a closed ticket, I suggest that you report all your steps and comments on [a new Forge ticket](forge.prestashop.com/).

Thank you!

**Pull request closed without merging**
