### PR TITLE
Show value for free delivery voucher instead of empty percents

### LINKED ISSUE #9702: [BOOM-5101] Voucher free shipping show 0.00% instead of free sipping
## SPECS

Cart rule with free shipping only: Display free shipping instead of 0,00%
Cart rule with free shipping + discount (amount or %): Display price of the carrier + Discount amount added
Cart rule with % discount: Display the discount amount            

image

You should always see the same value between the "discount(s)" line and the "cart rule" line if there is only one cart rule in the cart

----------------------
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5101).

- _**Reporter:**_ PN
- _**Created at:**_ Thu, 15 Mar 2018 09:27:45 +0100

<p>Hello,</p>

<p> </p>

<p><b>Type of view discounts in cart when is discount action set as free shipping. Why is showed: -0.00%? Better will be show free shipping instead of -0.00%.</b></p>

<p>Thank you</p>

<p>Best regards</p>

<p>PN</p>
        
* How to reproduce the issue ?

Catalog, Discounts, Cart Rules
<br/>

<br/>
for:
<br/>
1) Set Highlight: YES
<br/>
2) Leave field code blank
<br/>
3) Set actions: Free shipping: YES, none

### PR DESCRIPTION
**Pull request by LedCloud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When voucher with free delivery option is beeing applied to the cart it is shown as percent '0.0%' 
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9702
| How to test?  | Create voucher with free delievery option. Create an order, proccess it, in the cart you will see the line: -0.00% Instead of shipping value.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15459)

### CODE REVIEW

**Comment by Progi1984** [comment]
Hello @LedCloud, thanks for your contribution, would you mind to rebase your pull request and fix some PrettyCI errors ? Thanks

**Comment by LedCloud** [comment]
I changed the file, fixed it with php-cs-fixer-v2.phar... There are three lines of code changed. I don't see what is the problem with prettyci.

**Comment by PierreRambaud** [comment]
You need to rebase your branch first.
Maybe your branch on your fork is too old, this is why PrettyCi is crying.

**Comment by LedCloud** [comment]
Thank you for explanation. I will take care about that as soon as I get some free time.

**Comment by LedCloud** [comment]
I realized that I made the changes to the wrong file. I'm going to make another PR and this one might be closed.
Sorry (

I created another PR https://github.com/PrestaShop/PrestaShop/pull/15542

**Comment by matks** [comment]
> Sorry (

No problem 😉thanks for the time you dedicate to this project ❤️

**Pull request closed without merging**
