### PR TITLE
Wording: "Manufacturer" becomes "Brand"

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | What we used to call "Manufacturer" is now "Brand" from 1.7.<br>Change applies to content only, not to the code. |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |

*\* New wording **

Please check carefully before merging, it's supposed to update content only, not the variables or anything code-related.

Thanks!

### CODE REVIEW

**Comment by PrestaEdit** [comment]
:ok: ;-)

**Comment by inetbiz** [comment]
I disagree in this change, @AlexEven Levi Strauss has dozens of brands. Nike has many brands. Nike is *still* the manufacturer and Jordan's is one of their brands.

**Comment by AlexEven** [comment]
Hello @inetbiz,
Thanks for your feedback!
I understand you'd like to have BOTH manufacturer and brand. Today we only have one entity, and we're only changing its name. It's purely aesthetical if I may say.
Our opinion is that merchants would rather advertize brands on their shops, instead of manufacturers - so this is why we switch to "brand". To final users I believe they'll still identify Nike as a brand, and Jordan as a kind of sub-brand if you want, but it's still a brand in the end. And if you really want to say "Manufacturer" on your shop, this is still something you can change using the internal translation tool.
Best,

**Comment by ket4z** [comment]
Inetbiz, FYI Nike is definitely more a 'brand' than a 'manufacturer' (yet true, it can own other brands/sub-brands). The manufacturer of your Nike shoes will be probably some Chinese or Pakistani generic vendor with whom Nike contracts the production. Just to set the record straight. Today the consumers are about brands, not really manufacturers because production-wise pretty much everything becomes commodity and brand marketing is what makes the difference. I'm sure 80% of deployments today translate "manufacturer" to "brand" in their deployments hence this is really a step in right direction. Just my 5 cents.

**Comment by inetbiz** [comment]
@AlexEven and @ket4z it's all about semantics. When schema has manufacturer name, logo, mfg part number, it can extract information from online EDI systems indexed by major search. Now I understand more what you're going for in this iteration, @AlexEven. http://forge.prestashop.com/browse/PSCSX-5736 should take care of planning new entities for semantic seo purposes.

Bear in mind @AlexEven that some product brands sell better when the manufacturer logo is present. Whirlpool is the manufacturer of Maytag, KitchenAid, etc. Samsung has several brands including Galaxy S. It does matter in the future of 1.x

So that's why I thought it would be best not to have store owners get used to calling a manufacturer a brand. Let them learn the distinction between the two and explain it further in documentation.

**Comment by radusi** [comment]
I cannot agree more with @inetbiz . It's a no-go path.
The fact that some consumers, by mistake,  associate brands with manufacturers should not be a valid argument in favor of this. Ex. Ariel is a brand of Procter & Gamble, even Reebook is a brand of Adidas ( since 2006 ).

However, why should we give up on Manufacturer entity when is possible to introduce Brand, in between Manufacturer and Product.
I see this is a opportunity, not only a SEO one.

**Comment by vincentbz** [comment]
Hi,

As @AlexEven said, this decision is taken because in very most cases "manufacturer" is used for "brand" and this is why there is a native module that displays it. It has more sens to display the brands than the manufacturers.
Also, the word can be changed in the shop if it doesn't fit with the needs, but with this change we wanted to fit to most of the merchant needs.

**Comment by xBorderie** [comment]
In any case, this PR needs to be updated based on the latest codebase, since it cannot be merged without conflicts. Sorry @AlexEven, can you do it again?

**Comment by inetbiz** [comment]
Ignorance is bliss I suppose.

**Comment by radusi** [comment]
@xBorderie From DB architecture point of view, can I ( custom ) rename it back and use a Brand module in between Manufacturer and Product ?
I mean, is it possible ?
Thnx
Radu

**Comment by julienbourdeau** [comment]
I think you can introduce an entity inbetween. About translation, you can simply use the prestashop translation system to rename brand into manufacturer.
We won't do it because it introduces more complexity for not so much outcome.

**Comment by radusi** [comment]
@julienbourdeau Thanks a lot Julien. It's exactly what I was thinking, but I needed a confirmation that is permissible from DB structure.

**Pull request merged**
