### PR TITLE
Fix decoding of single quote/double quote in the rss feed (and others char I guess)

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Wrong displaying single quote and double quote in the "PrestaShop News" RSS feed. Helpful for the Italian news that could have the 'single quote' in the title.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | No ticket found
| How to test?  | Add Italian language to PrestaShop, in your employee profile switch to Italian language, go to dashboard. At the moment, the single quote is displayed like this => `\&#039;`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16755)

### CODE REVIEW

**Comment by matks** [comment]
@marsaldev Thanks for the contribution 😄and congrats for the 1st PR !

**Comment by marsaldev** [comment]
> @marsaldev Thanks for the contribution 😄and congrats for the 1st PR !

I want to be more active on the project 💪🏻

**Comment by PierreRambaud** [comment]
Hi @marsaldev ,
We are sorry for the delay :sweat_smile: 
Unfortunately I'm not able to reproduce your error when going on the Rss feed
image
Could you tell us more about how to reproduce :thinking:

**Comment by marsaldev** [comment]
Hi Pierre, no worries 😉
this is the last Italian xml:
[blog-it.xml.zip](https://github.com/PrestaShop/PrestaShop/files/4072021/blog-it.xml.zip)

The latest news has the single quote, not exactly the right character but it's fine, try to remove the first 2 news, so you'll display the "third" (that's is the first now) in the dashboard, it has the single quote that renders exactly like in the xml:
Schermata 2020-01-16 alle 16 28 49

Obviously if the problem could be solved at top, directly in the xml, this PR is useless 😊

**Comment by PierreRambaud** [comment]
@marsaldev Can you tell me from where this xml came? :sweat_smile: 
And which url do you use to reproduce?

**Comment by marsaldev** [comment]
@PierreRambaud As I see, the xml comes from here:
`$apiUrl = $this->configuration->get('_PS_API_URL_');`
`$blogXMLResponse = $this->circuitBreaker->call($apiUrl . '/rss/blog/blog-' . $isoCode . '.xml');`

And is located here:
`/config/xml/blog-it.xml`

**Comment by PierreRambaud** [comment]
I think the problem came from the PrestaShop API because we don't have any problems with other languages
http://api.prestashop.com/rss/blog/blog-fr.xml
http://api.prestashop.com/rss/blog/blog-en.xml

**Comment by marsaldev** [comment]
What a lucky 😊
And how we can solve?

**Comment by marsaldev** [comment]
Right now in the backoffice Italian dashboard:
Schermata 2020-02-06 alle 10 51 52

**Comment by PierreRambaud** [comment]
@marsaldev I don't know how to fix it right now :disappointed:

**Comment by marsaldev** [comment]
@PierreRambaud no worries, only a friendly reminder 😊
Who is in charge of PrestaShop API? I can talk to him/her and try to found a solution 😊

**Comment by PierreRambaud** [comment]
@marsaldev Should be the @PrestaShop/prestashop-core-developers :sweat_smile:

**Comment by matks** [comment]
Hi @marsaldev did the problem got solved at the source? Is this PR still needed?

**Comment by marionf** [comment]
Hi guys,

I don't see any question for PM here :thinking: 
I remove the "waiting for PM" label
Don't hesitate to ping us and add it if there is a functional question :)

@marsaldev If you still have this problem could you please [create an issue](https://github.com/PrestaShop/PrestaShop/issues/new?assignees=&labels=&template=1_bug_report.md) and link it to the PR ?

We need to first reproduce the issue before reviewing your PR :)

**Comment by PierreRambaud** [comment]
Hi @marsaldev ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
