### PR TITLE
Fix stock update error on Canceled orders

### PR DESCRIPTION
**Pull request by MounirBoukhris**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Update product's available quantity  when switching a canceled order to another status. These products must have available stock
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7679
| How to test?  | Use an order with status "Waiting for payment" in BO , when switching its status to "Canceled", the products containing in this order are restocked. However when we want that order to be paid again and we change its status to "Waiting for wire transfer", the stock of products is not updated (the available quantity is not decreased).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8263)

### CODE REVIEW

**Comment by hakeryk2** [comment]
Hey @Quetzacoalt91 and @LittleBigDev  maybe code-review and milestone for 1.6.1.18 - there is few forge for this and some topics on forums.

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[classes/order/OrderHistory.php, line 231 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8263#-L4C0FXd0I-vrF2-xIaR:-L4C0FXe0zv4iBHQejkA:bglqv3x) ([raw file](https://github.com/prestashop/prestashop/blob/28782124a7a56e3002fbff9fc53af802804ced28/classes/order/OrderHistory.php#L231)):*
> ```PHP
>                                 Tools::redirect($_SERVER['HTTP_REFERER']);
>                             } else {
>                                 StockAvailable::updateQuantity($product['product_id'], $product['product_attribute_id'], -(int)$product['product_quantity'], $order->id_shop);
> ```

If you feel adventurous enough, I would be extra glad if you could extract stock management stuff in a separate method. This method would check `Pack`, state change, and update quantity when relevant).

But this part is not required. Just highly appreciated.

---

*[classes/order/OrderHistory.php, line 242 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8263#-L4BwYHICL919P4ewRvp:-L4BwYHICL919P4ewRvq:b22nugz) ([raw file](https://github.com/prestashop/prestashop/blob/28782124a7a56e3002fbff9fc53af802804ced28/classes/order/OrderHistory.php#L242)):*
> ```PHP
>                                 && in_array($old_os->id, $error_or_canceled_statuses)
>                                 && ($quantityAvailableProduct <= 0 && !$isAvailableWhenOutOfStock)
>                             ) {
> ```

No `else` here. You should regroup all the `if` statements together.

Also, for people mental health, please consider simplifying some `if` recurring sequences by saving them in variables : `$newStateIsCanceled`, `$orderGettingCanceled`, `$orderNoMoreCanceled`, `$productIsAPack`, etc... Please. Really.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8263)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thank you @MounirBoukhris for dusting this very old piece of code !
Please see my comments above.

Also, this part is still live on develop branch. Maybe you could make an equivalent PR for it (after we wrap this one) ?

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
Correction is done ;)

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[classes/order/OrderHistory.php, line 190 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8263#-L6S4eEObvaESQpyohyd:-L6S4eEPxv9UOu_U4EgB:bur25x3) ([raw file](https://github.com/prestashop/prestashop/blob/a25b8fc626e331d882e5d54e5f57d78b91571d67/classes/order/OrderHistory.php#L190)):*
> ```PHP
>                     $quantityAvailableProduct = StockAvailable::getQuantityAvailableByProduct($product['product_id'], $product['product_attribute_id'], $order->id_shop);
>                     $isAvailableWhenOutOfStock = Product::isAvailableWhenOutOfStock(StockAvailable::outOfStock($product['product_id'], $order->id_shop));
>                     $productQuantityIsAvailabel = $quantityAvailableProduct <= 0 && !$isAvailableWhenOutOfStock;
> ```

typo in the var name

---

*[classes/order/OrderHistory.php, line 534 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8263#-L6S5HsSLZbPizK3bbs7:-L6S5HsSLZbPizK3bbs8:b653f5j) ([raw file](https://github.com/prestashop/prestashop/blob/a25b8fc626e331d882e5d54e5f57d78b91571d67/classes/order/OrderHistory.php#L534)):*
> ```PHP
>      * @param int $shopId
>      */
>     private function updateStockAvailableQuantity($productQuantityIsAvailabel, $product, $shopId)
> ```

Same typo here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8263)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Unofficial LGTM. Please fix typos and it's ok :)

**Comment by hakeryk2** [comment]
This is still not fixed :( @LittleBigDev could You please post it at 1.6.1.21 milestone?

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
