### PR TITLE
[*] method for getting Admin Media Path

### PR DESCRIPTION
**Pull request by kpodemski**

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi @kpodemski!

A big rework for the theme is currently on the pipe, I'll merge your pull request as soon as we finalize this work.

Thank you!

**Comment by xBorderie** [comment]
In the meantime, could you [update your commit's name](https://help.github.com/articles/changing-a-commit-message/) so that it follows [the guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)?

Thank you!

**Comment by kpodemski** [comment]
Hey @xBorderie 

it's ok now?

**Comment by xBorderie** [comment]
Seems good to me :)

**Comment by xBorderie** [comment]
Well @kpodemski, as you can see the target code has changed since then, and your PR cannot be applied anymore.
If you feel the new code could still your suggestion, could you please rebase your PR on an updated branch?
Thank you very much!

**Pull request closed without merging**
