### PR TITLE
Fix reset all default parameters on currency

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix reset all default parameters on currency
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/31812
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/31812
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by boherm — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Comment by djoelleuch** [comment]
Hello @mflasquin ,
I can't reproduce the [linked issue ](https://github.com/PrestaShop/PrestaShop/issues/31812)  without PR .
As you can see below : 

[Untitled_ Apr 14, 2023 4_47 PM.webm](https://user-images.githubusercontent.com/115152460/232078404-9113eafc-59d1-43c6-bbd8-f8163a1efa67.webm)

I think your PR  is related to this[ PR ](https://github.com/PrestaShop/PrestaShop/pull/32116) .
What do you think ? 
waiting for your feedback .
thanks .

**Comment by mflasquin** [comment]
Hi @djoelleuch, the button fixed on this PR is not the same, It's this button :

image

**Review by djoelleuch — APPROVED** [review]
Hello @mflasquin  ,
Automated tests --> OK
The issue is  well fixed 

[Untitled_ Apr 20, 2023 2_07 PM.webm](https://user-images.githubusercontent.com/115152460/233363988-968631ee-5409-47ab-9bc9-47f9c567d3a9.webm)


 It's QA approved :heavy_check_mark: 

Thank you for your PR !

**Comment by kpodemski** [comment]
thanks @mflasquin

**Pull request merged**
