### PR TITLE
CLDR Locale Cache data layer

### PR DESCRIPTION
**Pull request by LittleBigDev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As a Number repository, I need data layers to read my number information
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [FF-145](http://forge.prestashop.com/browse/FF-145)
| How to test?  | See committed phpunit tests

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8722)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
TODO : dedicated test file for layers read/write propagation

**Comment by eternoendless** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php, line 88 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8722#-L4MDGTbhsRgPMnBL7ys:-L4MDGTbhsRgPMnBL7yt:bogqt8b) ([raw file](https://github.com/prestashop/prestashop/blob/f9393db18f1822722ba3dea6866a0e931f6dd2f4/tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php#L88)):*
> ```PHP
>             "Known key"   => [
>                 'key'   => 'knownKey',
>                 'value' => 'known key result',
> ```

Maybe we should try with an object instance too, instead of a scalar, because that's what we are actually going to want to store.

---

*[tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php, line 100 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8722#-L4MEd2u74Otu9DHVWdL:-L4MEd2u74Otu9DHVWdM:b-xq5ho7) ([raw file](https://github.com/prestashop/prestashop/blob/f9393db18f1822722ba3dea6866a0e931f6dd2f4/tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php#L100)):*
> ```PHP
>     {
>         $data      = new LocaleData();
>         $data->foo = ['bar', 'baz'];
> ```

Oh I see that you did it here. Why not use put it on your dataProvider above? Maybe the read test is redundant with this one

---

*[tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php, line 122 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8722#-L4MEPehQAtO0Jf3x-TA:-L4MEPehQAtO0Jf3x-TB:bfwaoo7) ([raw file](https://github.com/prestashop/prestashop/blob/f9393db18f1822722ba3dea6866a0e931f6dd2f4/tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php#L122)):*
> ```PHP
>     }
> 
>     protected function mockCacheItem($key, $isHit, $value = null)
> ```

Looks unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8722)*

**Comment by LittleBigDev** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php, line 88 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8722#-L4MDGTbhsRgPMnBL7ys:-L4MJuB_o4hWfwzMAc2J:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/f9393db18f1822722ba3dea6866a0e931f6dd2f4/tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php#L88)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Maybe we should try with an object instance too, instead of a scalar, because that's what we are actually going to want to store.
</blockquote></details>

Done.

---

*[tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php, line 100 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8722#-L4MEd2u74Otu9DHVWdL:-L4MJv7wuzQsI-DG70wY:bqog80t) ([raw file](https://github.com/prestashop/prestashop/blob/f9393db18f1822722ba3dea6866a0e931f6dd2f4/tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php#L100)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Oh I see that you did it here. Why not use put it on your dataProvider above? Maybe the read test is redundant with this one
</blockquote></details>

Agreed

---

*[tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php, line 122 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8722#-L4MEPehQAtO0Jf3x-TA:-L4MJyVSWdTIdrQ3wnm4:buketii) ([raw file](https://github.com/prestashop/prestashop/blob/f9393db18f1822722ba3dea6866a0e931f6dd2f4/tests/Unit/Core/Localization/LocaleCacheDataLayerTest.php#L122)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Looks unused
</blockquote></details>

Indeed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8722)*

**Comment by alegout** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8722)*

**Review by alegout — APPROVED** [review]
Thank you :)

**Pull request merged**
