### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes part of deprecated code scheduled for deletion in v9.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | See below
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

### What to test
- Try registering, login and password reset in both BO and FO.
- Try to edit some product combinations and see if colors in FO product list still work.
Bez názvu

### Removed methods
- Product::getColorsListCacheId
- Tools::clearColorListCache
- Validate::isPlaintextPassword
- Validate::isPasswdAdmin
- FrontController::addColorsToProductList
- FrontController::getColorsListCacheId

### CODE REVIEW

**Comment by kpodemski** [comment]
@Hlavtox CS Fixer 👍🏻 otherwise LGTM

**Review by boherm — APPROVED** [review]
LGTM, thanks @Hlavtox!

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto tests should be enough:
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5067953667

**Review by FabienPapet — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-automation could you check what's wrong with the auto-tests?

**Comment by Progi1984** [comment]
> @PrestaShop/qa-automation could you check what's wrong with the auto-tests?

@kpodemski Which problem ?

image

**Comment by kpodemski** [comment]
@Progi1984 well, for the moment it was 36/37 but maybe it was because of the previous run 😵 

thanks

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional anything else you'd like to check there, or auto-tests are enough? could you confirm?

**Review by MhiriFaten — APPROVED** [review]
@kpodemski I did a quick check with product combinations and the colors in FO product works like usual ! LGTM
It is QA approved.

**Comment by kpodemski** [comment]
thanks Daniel @Hlavtox !

**Pull request merged**
