### PR TITLE
Add line in PR template to not forget UI tests

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | To not forget https://github.com/PrestaShop/ga.tests.ui.pr/
| Type?             | improvement
| Category?         | PM
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | CI is green 🟢 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]
Don't forget to launch UI tests for this PR too! 😄
Seriously, it's a good idea to avoid to forget UI tests 😉

**Review by mflasquin — DISMISSED** [review]

**Comment by kpodemski** [comment]
I'm not sure about that. For project members it could be something interesting, but for community contributions... Yet another thing to learn, and I'm afraid that even if somebody share the link to those tests QA will run their own anyway. What issue does it solve really?

**Comment by Progi1984** [comment]
> I'm not sure about that. For project members it could be something interesting, but for community contributions... Yet another thing to learn, and I'm afraid that even if somebody share the link to those tests QA will run their own anyway. What issue does it solve really?

Nightly is regulary broken by contributions. Because Contributor doesn't check all parts of PS.

**Comment by kpodemski** [comment]
@Progi1984 isn't this part of QA to run them? 🤔

**Comment by Progi1984** [comment]
> @Progi1984 isn't this part of QA to run them? 🤔

Quality is everyone's concern.

**Comment by kpodemski** [comment]
@Progi1984

It's not my point to discuss whether it is or not.

Let's assume we agree on this change, what if one didn't run the tests? Would you like for us to ask the contributor to do that? I don't see many advantages in **forcing it** if it's part of the QA process, and I do see a risk of adding yet another thing to the contribution process 🤔 Not to say that very often we struggle with things we don't have control over, and tests fail because of unknown reasons, we need to ask your team to check them anyway.

**Comment by nicosomb** [comment]
> what if one didn't run the tests?

Then, the @PrestaShop/committers members can launch them.

**Comment by kpodemski** [comment]
If we agree not to force them and only inform contributors about such a practice, then ok :)

**Comment by boubkerbribri** [comment]
> @Progi1984
> 
> It's not my point to discuss whether it is or not.
> 
> Let's assume we agree on this change, what if one didn't run the tests? Would you like for us to ask the contributor to do that? I don't see many advantages in **forcing it** if it's part of the QA process, and I do see a risk of adding yet another thing to the contribution process 🤔 Not to say that very often we struggle with things we don't have control over, and tests fail because of unknown reasons, we need to ask your team to check them anyway.

I think that we will not force it but it can be a must have. If we consider running all tests on a PR as part of the CI, it will be mandatory.
The only thing that stopping that is "we have a free open-source plan, we have limited resources, we use forks to run tests". If we have more resources, it will not be a question.

**Comment by kpodemski** [comment]
@boubkerbribri Having it in our CI would be great, I wonder how costly it would be to run tests using Google instance and only communicate through GH Action 🤔 + we would need some safe measures not to allow run them over and over again

**Review by LouisAUTHIE — DISMISSED** [review]

**Comment by matks** [comment]
Hello guys, I see the worries of @kpodemski and the answers provided.

The PR simply adds a section `| UI Tests |` . It does not explain that sometimes the UI tests can fail for good reasons (there is a test that was broken a few days ago and bug is being fixed, so it's expected it fail) or bad reasons (like timeouts). It does not explain UI tests are useful to verify if a PR has broken something in the software, in a place unrelated to the initial change. It does not explain how to reach out to QA team if there's questions about the result of these tests. Also if I am not wrong, people must regularly update their fork of https://github.com/PrestaShop/ga.tests.ui.pr/ : if they fork it once and then use it on PRs months later, they are running an outdated version of the tests on the latest version of the software which will produce unwanted results.

I have a suggestion: more than this simple PR, write a page on https://www.prestashop-project.org/ (in Maintainer Guide or in Quality Council) that explain all of the above 😄 and link it in the Description table.

So the PR content would go from
```
| UI Tests          | Please run these tests (see https://github.com/PrestaShop/ga.tests.ui.pr/) and paste here the link to the run.
```
to
```
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know how to use this tool](link)
```

**Review by jolelievre — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by matks — APPROVED** [review]
Thank you @nicosomb for accepting my requests and waiting for the docs page to be online 😊

**Review by boherm — APPROVED** [review]

**Pull request merged**
