### PR TITLE
[*] CORE: Removed hardcoded API urls

### PR DESCRIPTION
**Pull request by guestisp**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Regards

**Comment by guestisp** [comment]
Keep in mind that i've created safeDefine to allow users customize api urls from settings.inc. php

By removing that you are blocking the customization (is not possibile to redefine a constant)

For example we need to change the currency api URL in our environment.

**Comment by gRoussac** [comment]
Hi,

Indeed, are you maintining a server with a currencies xml ?

Regards

**Comment by guestisp** [comment]
Yes. We host hundres of PS shop in our network and we would like to cache/optimize external connections by removing, as much as possible, external requests.

We are downloading `http://api.prestashop.com/xml/currencies.xml` once a day, thus we would like to change the feed location to our address. There is no need to download the same file, hundred times from your server, we make a local copy here.

This also optimize bandwidth on your side.

More over, there are some network environments (like ours) where external requests are not allowed (or allowed with restriction) for security reasons. By using a custom server, this wouldn't affect any PS customers and is much faster to download a file from a LAN than from Internet.

**Comment by gRoussac** [comment]
Hi,

I guessed that but this is not my decision. I will discuss it again in tech meeting.

Regards

**Comment by guestisp** [comment]
Well, this PR dosn't change default behaviour, it add a capability, thus there are no issue with this.
If defined, a different url is used, if not defined (as default), the standard PS url is used.

**Comment by gRoussac** [comment]
Thank you for your feedback.

Regards

**Comment by guestisp** [comment]
Thank yor the new merge.

**Pull request merged**
