### PR TITLE
Allow to sort bestsellers by sales

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | http://forge.prestashop.com/browse/BOOM-4256
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4256
| How to test?  | http://forge.prestashop.com/browse/BOOM-4256
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8471)

### CODE REVIEW

**Comment by kpodemski** [comment]
ok, thanks @prestonBot ;D

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8471#-:-KyKZofJyEgyu56leMBZ:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Thank you @kpodemski

**Comment by Quetzacoalt91** [comment]
You are probably not aware of that @kpodemski, we started the process release of the 1.7.3.0 yesterday.

Your PR seems to be an improvement, not a bug fix, and we currently accept only bug fixes on the 1.7.3.0 tag. And from now, `develop` is for 1.7.4.0, `1.7.3.x` is for ... well, 1.7.3.x versions. :)
As we have a string change, I guess this is for 1.7.4.0.

**Comment by kpodemski** [comment]
Hey @Quetzacoalt91 

sorry but it's bugfix, there's literally nothing good for customer and shop with visiting best sellers sorted by name, in 1.6 (and 1.5, and 1.2... and 1.1...) sorting by sales was default one and this is expected behavior in PrestaShop for people who use it

> As we have a string change, I guess this is for 1.7.4.0.

ok, however we need to fix it in every single store we're creating on 1.7 ;D

**Comment by Quetzacoalt91** [comment]
We discussed internally about this PR, because of the string update the only choices we had were 1.7.3.0 or 1.7.4.0.
As your PR is already validated in a code and functional way, we take the responsibility for 1.7.3.0 :wink: 

Thank you @kpodemski

**Comment by kpodemski** [comment]
Great, thanks @Quetzacoalt91

**Comment by rdy4ever** [comment]
This PR should be commited ASAP. Sorting best sellers by name? Are you guys serious? Also, the same problem also happens eith the price drop page. There is no option to sort them by discount. kpodemski, could you take a look? Thanks!

**Pull request merged**
