### PR TITLE
Update wording cart-detailed-actions.tpl

### PR DESCRIPTION
**Pull request by Nobodaddy**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Cart had used the wrong translation item
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @Nobodaddy 
Can you follow Preston comments ?

Thank you!

**Comment by Nobodaddy** [comment]
@aleeks 
I'm sorry, but I have no idea what this comment means.

**Comment by maximebiloe** [comment]
Hello @Nobodaddy,

The comments mean that your commit message is `Update wording cart-detailed-actions.tpl` instead of `FO: Update wording in checkout` for example.

@AlexEven what do you think of these changes?

Regards

**Comment by Nobodaddy** [comment]
Hmm ... from my point of view this is not a question of approval or disapproval by @AlexEven, it's a question of programmer's logic.

**Comment by aleeks** [comment]
Rebased from develop.
Thank you @Nobodaddy

**Pull request merged**
