### PR TITLE
refactor: losslessy compress images

### PR DESCRIPTION
**Pull request by j9t**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | n/a (local branch was “refactor/images” as per PR details)
| Description?      | Used ImageOptim to defensively (losslessly) but aggressively compress all images, to reduce payload and improve performance.<br><br>Result as per ImageOptim: “Saved 1,6 MB out of 8,7 MB. 18,5% overall (up to 94,9% per file)”.
| Type?             | refacto
| Category?         | n/a
| BC breaks?        | n/a
| Deprecations?     | n/a
| How to test?      | compare images (changes should be imperceptible)
| UI Tests          | [skipped]
| Fixed issue or discussion?     | n/a
| Related PRs       | n/a
| Sponsor company   | n/a (individual contribution)

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
This is not lossless, compressing jpg to jpg. I can see your point, but I see the artifacts even on my phone. :-)

**Comment by j9t** [comment]
> This is not lossless, compressing jpg to jpg. I can see your point, but I see the artifacts even on my phone. :-)

The compression was lossless, @Hlavtox, @ps-jarvis, in a sense that it shouldn’t have degraded image quality. (If it was poor, it didn’t get better, however, if that’s what you expected.)

The formats were unchanged, too, so where you or others chose a lossy format (like JPG), that’s still using a lossy format.

I couldn’t spot any new artifacts, but that’s based on scanning and taking samples. Please let me know which images to revert and I’ll either proceed or drop the PR.

**Comment by leemyongpakvn** [comment]
I think we need to automate this kind of task as a github action for security reason. We are having a problem with contributors' packed js, so we don't need one more :)

**Comment by nicosomb** [comment]
@leemyongpakvn https://github.com/calibreapp/image-actions (thank you @Progi1984)

**Comment by leemyongpakvn** [comment]
@nicosomb Great. But it is for _new-open Pull Request with added or changed imagery_. How about existing images?

**Comment by Progi1984** [comment]
It can be done on demand or on schedule : https://github.com/calibreapp/image-actions#compress-on-demand-or-on-schedule

**Comment by leemyongpakvn** [comment]
@Progi1984 OK. I'd prefer On demand than On schedule for existing images. The problem now is who will add this image-action to our repos :wink:

**Pull request closed without merging**
