### PR TITLE
Remove live exchange rate toggle in Currencies

### LINKED ISSUE #23412: Remove live exchange rate toggle in International > Localization > Currencies
#### Is your feature request related to a problem?

The [cronjob module](https://github.com/PrestaShopCorp/cronjobs) isn't compatible with 1.7 versions and since it is a service provided by PrestaShop Corp, the core should not have any dependency with it.

#### Describe the solution you'd like

- [ ]  Remove all dependencies in the core with the cronjob module.
- [ ] Remove the live exchange rate toggle in International > Localization > Currencies
- [ ]  Add explanations in the documentation to indicate how to automatically update the exchange rates ->  "Check the [developer documentation](https://devdocs.prestashop.com/1.7/faq/pricing/#refresh-exchange-rates) for setup instructions." in Admin.International.Help

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove live exchange rate toggle in International > Localization > Currencies. Remove code related to no longer existing module `cronjobs`.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Implements #23412.
| Related PRs       | None
| How to test?      | International > Localization > Currencies, the toggle is replaced by an improved hint that points to the developer documentation.
| Possible impacts? | This should not have any other impact than removing the toggle.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28177)

### CODE REVIEW

**Comment by lmeyer1** [comment]
I tried to implement #23412 as a first issue that uses symfony core.

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Review by matks — APPROVED** [review]
Bravo @lmeyer1

**Review by kpodemski — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @lmeyer1 

I checked this PR. The improvement is well updated.
Here is my tested cases : 

- Check with multi-store : OK
- Check with different languages (RTL and no RTL) : OK
- Check with responsive : OK 
- Check when install/uninstall modules : OK
image

So, it's QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @lmeyer1 & @HanaRebaiQA

**Pull request merged**
