### PR TITLE
Remove Tools::jsonEncode and Tools::jsonDecode

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove Tools::jsonEncode and Tools::jsonDecode
| Type?             |improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Related to #26293
| How to test?      | No need QA, CI is green.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

## BC breaks

- `Tools::jsonEncode`  is no longer available
- `Tools::jsonDecode`  is no longer available

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26681)

### CODE REVIEW

**Review by tegbessou — COMMENTED** [review]
Do you forget to remove this function in smarty.config.inc.php lines 87 and 88? Are it's not necessary?

**Review by Progi1984 — APPROVED** [review]

**Comment by kpodemski** [comment]
Ouch, this one hurts, as it was required by addons validator to use these methods for a long, long time 😬

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@tegbessou it's needed because in Smarty you can use `{$var|@json_encode}` but `{$var|json_encode}` won't work without a custom modifier

**Comment by tegbessou** [comment]
Okay, but why this modifier has this params: array('Tools', 'jsonDecode') or array('Tools', 'jsonEncode') ?
It is a little strange because we remove these two functions

**Comment by kpodemski** [comment]
@tegbessou maybe you looked at the outdated diff? Pierre changed these two lines to replace these methods with the native ones from PHP

**Comment by tegbessou** [comment]
I don't see where? Can you show me, please?

**Comment by PierreRambaud** [comment]
@tegbessou It was an array because of the `call_user_func` function.
Example:
```php
class A {
    public function __construct()
    {
        call_user_func([$this, 'foo']);
    }

    public static function foo() {
        echo "bar" . PHP_EOL;
    }
}

new A(); // bar
call_user_func([A::class, 'foo']); // bar
```

**Comment by Progi1984** [comment]
Thanks @PierreRambaud

**Pull request merged**
