### PR TITLE
Fix some composer versions

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | dev-master version of pagesnotfound & contactform have min version requirement on PS 1.7.1.0
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Try to install a fresh clone of 1.7.0.x

### CODE REVIEW

**Comment by aleeks** [comment]
@antoin-m can you add contact form & ps_cachondelivery please ?

**Comment by antoin-m** [comment]
@aleeks I changed contactform but ps_cashondelivery is not present in the composer.json. Do you want me to add it?

**Comment by aleeks** [comment]
So nope!

**Comment by maximebiloe** [comment]
Thank you @antoin-m

**Pull request merged**
