### PR TITLE
Change domain to fix translation issue

### LINKED ISSUE #30916: Translation string for "new" in BO not working
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are two separate strings for the string ‘New’:

1. Front office: ‘New’ (=Nouveau) in `Shop.Theme.Global`
2. Back office: ‘New’ (=Neuf) in `Admin.Global`

image

image

 
Both strings are translated differently in 8+, but they both appear as “nouveau”, no matter the context. The translations are correct on Crowdin, but the translated strings on the software are not working correctly.

This is not the case in 1.7. I have not tested the bug in other languages.

I'm editing the string to place it under the right translation domain `Admin.Global`, instead of `Shop.Theme.Global`

### Expected behavior

Strings are supposed to be translated like this:

1. Front office: "Nouveau"
2. Back office: "Neuf" 

### Steps to reproduce

1. Create a new product, and make it visible on your store
2. Check if the label "new"is translated properly ("nouveau" in FO, "neuf" in BO)

### PrestaShop version(s) where the bug happened

8.0.0, 8.0.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by l-delin**
Solve issue #30916 

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | check the issue description
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | check the issue description
| Fixed ticket?     | Fixes #30916
| Related PRs       | check the issue description
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Review by zuk3975 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Comment by MatShir** [comment]
The issue is only on develop ? If not you can target the 8.0.x :)

**Comment by paulnoelcholot** [comment]
Hello @l-delin,

I can't reproduce this issue on develop, so could you please change it for 8.0.x?

Thanks!

**Comment by paulnoelcholot** [comment]
Hello @l-delin,

I have tested your PR on develop and if I understood correctly, the expected behavior is not the right one.

OK
image

OK
image

NOK
image
This label should be "Nouveau"

**Comment by l-delin** [comment]
@paulnoelcholot Yes, that's right :-)

**Review by boubkerbribri — DISMISSED** [review]
Something went wrong after changing the target branch to 8.0.x, there is a lot files updated on the PR. It's like you're backporting all modification made on develop to 8.0.x

**Comment by l-delin** [comment]
What should I do @boubkerbribri?

**Comment by boubkerbribri** [comment]
> What should I do @boubkerbribri?

I just fix it, could you take a look on modification please

**Comment by l-delin** [comment]
Looks good, thank you @boubkerbribri!

**Comment by atomiix** [comment]
Closing this one as I think the issue comes from the fact that this PR has not been made on a fork

**Pull request closed without merging**
