### PR TITLE
Do not show if email exists @ password reset

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | `develop` |
| Description? | An attacker can find out if an email address has been registered by entering it at the password forgotten prompt. This PR will make sure it that the password forgotten prompt will always show "An email has been sent, blabla" when the email address is valid. |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

Before:
noregisteredaccount

After:
hideemail

### CODE REVIEW

**Comment by kpodemski** [comment]
Maybe it would be better to show: if your email have been registered in our shop  you'll receive a link to password reset?

**Comment by firstred** [comment]
Yeah, nice one!
:+1:

**Comment by maximebiloe** [comment]
Good catch!
@AlexEven can you check the wording, please?

**Comment by AlexEven** [comment]
Thank you @firstred!

One remark, we're losing the reminder of the entered address, which can be useful for people to check if they made a typo or something. Would you mind adding it back?

Something like :

> If this email address has been registered in our shop, you will receive a link to reset your password at %.

Thank you!

**Review by kpodemski — APPROVED** [review]
Testing testing! Awesome PR!

**Comment by firstred** [comment]
Force-push! Your review is invalid ;)

**Comment by maximebiloe** [comment]
Thank you!

**Pull request merged**
