### PR TITLE
Module widget display fix

### LINKED ISSUE #20138: Module added as widget in smarty is displayed no matter if is disabled
#### Describe the bug

When you add widget in your .tpl like this {widget name="module_name"} and module is disabled, widget is still displayed.

#### Expected behavior

Widget shouldn't be displayed when module is disabled.

#### Steps to Reproduce

1. Go to file (open it with editor) index.tpl in theme/classic/templates/index.tpl, add {widget name="ps_imageslider"} after {block name='hook_home'}.
2. Go to homepage of your shop. Two widgets should be displayed.
3. Go to BO of your shop. Disabled  ps_imageslider module.
4. Go back to homepage of your shop. One widget will be displayed even if module is disabled.

#### Additional information

* PrestaShop version: 1.7.7

### PR DESCRIPTION
**Pull request by Oksydan**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | I think issue describe it enough. 
| Type?         | bug fix
| Category?     | FO 
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | Fixes #20138.
| How to test?  | Follow the instruction I mentioned in issue.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20139)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Oksydan,

The option "Disable Mobile" doesn't work.
I attached a screen record
https://drive.google.com/file/d/1vRdXs1IMRXH7OCgRkOntXDHXeTWvJVAX/view?usp=sharing
Thanks to check and feedback.

**Comment by Oksydan** [comment]
@PierreRambaud @atomiix 

waiting for conflicts resolve and review.

**Comment by matks** [comment]
> waiting for conflicts resolve

Nice try ! 😄 
But the conflicts resolution must come from your side

**Comment by Oksydan** [comment]
@matks 

Ok, I am dumb :D. Is there a way to run these php tests on my local machine ? If so, could you provide me some reference to the topic.

**Comment by PierreRambaud** [comment]
@Oksydan I restart the failing test. it was because of 
```
1) LegacyTests\Integration\Core\Localization\LocaleUsageTest::testItShouldFormatNumbers with data set "United States" ('en-US', 1234568.12345, '1,234,568.123')
Exception: file_get_contents_curl failed to download https://i18n.prestashop.com/translations/1.7.8.0/en-GB/en-GB.zip : (error code 28) Operation timed out after 0 milliseconds with 0 out of 0 bytes received
```

But yes, all tests can be run in local, we maybe need to document that to make it easier:sweat_smile:

**Review by PierreRambaud — APPROVED** [review]

**Comment by Oksydan** [comment]
@PierreRambaud 

would be nice 😃

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Oksydan,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1WxIFb-73lA8LpPOknrbc4o4ZOfagFj9I/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @Oksydan & @khouloudbelguith

**Pull request merged**
