### PR TITLE
Update rel="noopener noreferrer"

### PR DESCRIPTION
**Pull request by rudSarkar**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Little fix rel="noopener noreferrer" and `http://enable-javascript.com/` to `https://enable-javascript.com/`
| Type?         | improvement
| Category?     | IN
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9340)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by rudSarkar** [comment]
What I have to do now?

**Comment by Quetzacoalt91** [comment]
Nothing, this PR is currently under review.

**Comment by rudSarkar** [comment]
Thanks for the information.

**Comment by PierreRambaud** [comment]
Thanks @rudSarkar

**Comment by rudSarkar** [comment]
Welcome ❤

**Pull request merged**
