### PR TITLE
Match the right carrier in the select with the price shown when creating a new order from BO

### LINKED ISSUE #12682: BO manual order shows wrong shipping price (one product without changes)
Bug in Back Office manual order. Shipping price will show the wrong amount and the summary will be wrong. When creating the order everything recalculates and shipping cost will be correct according to the chosen carrier.

Can be reproduced in version 1.6.1.23 and 1.7.4.2.

How to reproduce: 
1) Create two delivery options with different amounts, none with free shipping (use different amount to see the bug). Take notice of the Position ID (1 and 2 in my case).
2) Go to Shipping -> Preferences and set the default carrier to the the carrier with highest ID (4 in my case)
3) Create a new manual order in the back office (Orders -> Add new order)
4) Choose customer and add one product
5) Scroll down to "Shipping"-part. "Delivery option" has the carrier with the highest position but the "Shipping price" shows the price of the default carrier.
6) If you add one more product to the cart, shipping price will be corrected. If you create the order, shipping price will be recalculated to the price of the carrier in the "Delivery option" box.
wrong shipping price
wrong shipping price2

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix the ticket #12682
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #12682
| Related PRs       | ~
| How to test?      | Follow the issue.
| Possible impacts? | ~

### CODE REVIEW

**Comment by kpodemski** [comment]
Why not use a Configuration service like you did at first?

**Comment by marsaldev** [comment]
> Why not use a Configuration service like you did at first?

Don't know, because the Adapter is a mess? :D 

What do you suggest?

**Comment by kpodemski** [comment]
Use a Configuration service like other modern parts of the software do. Configuration component is implementing a proper interface, if needed, we can replace it with a new version in the future.

**Comment by matks** [comment]
Re-running CI as multiple issues seem random

**Comment by matks** [comment]
@marsaldev can we have a PR title a little bit more informative 😉 ? Something like "pick the right carrier if..."

**Comment by marsaldev** [comment]
> @marsaldev can we have a PR title a little bit more informative 😉 ? Something like "pick the right carrier if..."

Sorry, you're right, my bad 😊 
Done! 😉

**Review by Amoifr — COMMENTED** [review]
Thks for this PR
Can I suggest to inject the configuration value by the yml instead of the Configuration ?
something like that : 
- "@=service('prestashop.adapter.legacy.configuration').get('_PS_MODULE_DIR_')"

**Comment by marsaldev** [comment]
> Thks for this PR Can I suggest to inject the configuration value by the yml instead of the Configuration ? something like that :
> 
> * "@=service('prestashop.adapter.legacy.configuration').get('_PS_MODULE_DIR_')"

Hi @Amoifr! Thanks for your feedback!
No problem to change it 😉, but I want to understand the "difference", I mean, why injecting the single value instead of the service? 
In future if the handler needs another Configuration value, we should edit the yml, inject a new value, and edit the constructor. 
In this case we have already the Configuration service, no need to edit the yml and the constructor, and you can use it wherever in the handler 🤔

**Comment by Amoifr** [comment]
Hi @marsaldev ,
We are agree that the legacy service of configuration is called in the both implementation. 
I would like, for my part, that the migration to symfony is accompanied by the fact of cutting ties with the legacy. And injecting adherence to a legacy service creates technical debt. While injecting a value pushes the use of legacy out of the migration code. The day we have an alternative to the configuration service of the legacy code will already be rid of its adhesions and we will only have to modify yaml.
On the other hand the code in question in fact only needs an input value, it seems pointless to pass the entire service to it.
What do you think ?

**Comment by kpodemski** [comment]
Hi @Amoifr 

The moment a new value will be required there is a need to add a new parameter, document it, etc. + it might create a BC Break.

Having a service available behind an interface and given that the values are stored in the cache anyway, I don't see any reason to use only a value.

**Comment by Amoifr** [comment]
Hi @kpodemski 

It was simply a matter of applying best practices for a class to receive the minimum memory footprint parameters. A string instead of a service. The service is destructed from the memory when the class is called in my case.
And about the BC Break .... adding a Service in the construct signature or a string.... The BC break is already present.

My my comment was just a suggestion. Ignore it. Let's continue as usual.

**Comment by kpodemski** [comment]
Thanks, @Amoifr - It's not the first time I have seen this suggestion, so you might be right, and we should stick to getting a single value instead of injecting a service. I remember @Progi1984 had the same suggestions. Franck, what do you think? Shall we keep the service or change it to the value?

**Comment by marsaldev** [comment]
Hi guys, thanks for your involving in the discussion, @Amoifr, my question wasn't an objection, but really wish to better understand which is the better approach 😊 
As @kpodemski noticed, I forgot it ^^", we have already go through this situation 😊 
Let's wait Franck (@Progi1984) pov 😉

**Comment by kpodemski** [comment]
@Progi1984, could you share your opinion about the topic?

**Comment by Progi1984** [comment]
My opinion is that we should only load in constructor only specific value instead of injecting a service. I prefer inject the service when we need to set configuration values. 

But you should ask to maintainers, they are there to provide the technical vision for the whole project.

**Comment by marsaldev** [comment]
Ping @PrestaShop/prestashop-maintainers 😊

**Review by kpodemski — APPROVED** [review]

**Comment by marsaldev** [comment]
gently ping @PrestaShop/committers  😊

**Review by atomiix — APPROVED** [review]

**Comment by sallemiines** [comment]
I will check this PR !

**Comment by zuk3975** [comment]
> My opinion is that we should only load in constructor only specific value instead of injecting a service. I prefer inject the service when we need to set configuration values.
> 
> But you should ask to maintainers, they are there to provide the technical vision for the whole project.

Yes, we have discussed it couple times already with @eternoendless in various topics and the rule of thumb generally is - inject only what you need. So if its possible only inject the value you use, instead of whole service.

**Comment by sallemiines** [comment]
Hello @marsaldev,

The issue is solved
- I run the automated tests **OK**

I checked those steps:
**Check1**
in BO :
- Create a new carrier which is not free without tax
- Create another carrier which is not free with tax
- In Shipping > Preferences > set one of the carriers created as the default one
- Go to orders > add a new customer > choose the  created customer to create a new order > add a new address > select a product and add it to the cart
- Check in the shipping section that the delivery option is the chosen carrier
- Check that the shipping price is correct
**Check2**
Repeat the same steps with the other carrier created (with tax) and check that the delivery price indicated is correct
- in shipping > performances > set the handling charge = 0
- add a new order and check that the shipping price is correct
- create a new discount (for example 10%)
- create an order with a not free carrier and add the created voucher
- in the summary block check that the value of the total voucher is displayed and the total is correct
- I check it also with the multiStore option
**Check3**
In FO :
Create an order > select the created shipping carried and check that the correct price is well displayed



https://user-images.githubusercontent.com/31663369/191514133-6cf27418-b9e9-43a1-bbbd-7958a53af6e3.mp4

Thank you !

**Comment by kpodemski** [comment]
Thank you @marsaldev @sallemiines

**Pull request merged**
