### PR TITLE
Rename new-api into command-api

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Read below
| Type?             | improvement
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No test needed
| Fixed ticket?     | 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

## Description

The new API built in 8.1.0 has still no better name than “New API” and
the endpoints are prefixed with `/new-api/`. The name “New API” is written in a few files in the software.

I think we all agree it’s not the best name ever 😆 

I suggest we rename the API as “Command API”  (as the API is supposed to plug on existing Commands from CQRS). URL prefix would become `/command-api`.

I considered the idea of using `/api/v2` for the URL prefix but PS webservices already use the `/api` prefix so it could create routing issues and confusion.

I also modify the version number from 1.0.0 to 0.1.0 to highlight the fact this is experimental and might change a lot in the next version.

Note: the new API is experimental so if the name we pick now is bad, no worries, we can change in 9.0, but at least we’ll have a proper name in 8.1.0 and not the silly "new api" name.

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]
Whatever how we name it, the name of the API should not be inside the url, so the url should be `/api/v2` would be better, regardless of the old one.

Also, I don't see the point of renaming it, and then renaming it the future. That does not make sense, why can't we just agree on the name and the pattern once for all ? It is a too big problem to organize a meet with 3 or  people inside, or even better, make an ADR for this ?

**Review by tleon — DISMISSED** [review]
I also thought we had agreed the other day to only name the api " command"  for intern uses and still use some regular path for the base endpoint url like "/api/v2/..." . 

I'm also ok with using "/command-api/..." .

**Comment by matks** [comment]
> It is a too big problem to organize a meet with 3 or people inside, or even better, make an ADR for this ?

Yes, decisions in the project are very long so I think the release date of 8.1.0 might come too soon for an ADR for this. There is a problem with slow decision making in the project, and we cannot ignore it.

**Comment by kpodemski** [comment]
@matks This is a tech decision which tech council should make. I think the decision making in the project is now clear. We can listen to @FabienPapet or @tleon's feedback, but eventually, it is not them who decides, we only have a few people to ask, so it should not be a super time-consuming process.

My POV:
If the new API aims to replace the old one, and it is possible to introduce `/api/v2/` without breaking old API, the `v2` makes sense, if not, because, for example, the purpose is different (I remember the split between BO API and FO API by @fabienvallon ) then we should think about a different name :-)

**Comment by matks** [comment]
Guys it's even worse than I thought: the routing has been defined in the back-office configuration.

So URLs are not `myshop.com/new-api/(...)` but `myshop.com/admin727272/new-api/(...)`

I think asking people around might take a long time. If we are not quick enough, then the current name will remain and might be shipped inside PrestaShop 8.1.0 😉 .

My suggestion would be:
1. Pick a "good enough" name and URL and merge it, at least we have something correct in PS 8.1.0
2. Decide together on a better name and URL
3. If 8.1.0 is not released yet, we can use another PR to change again the name and URL and have it in 8.1.0
4. If 8.1.0 has already been released, then we change the name in PS 9.0.0

If you skip step 1 and try to go directly to step 2 you might end up at step 4 and PrestaShop 8.1.0 will be released with a "New API" forever 😉

**Comment by kpodemski** [comment]
@matks 

Isn't a reason for this because Command API is "Back office API"? There was some differentiation of this which was surprising to me, but that was the case. It doesn't make sense for the front API to know the admin URL, this is a security issue, we want to share the API access and we share the admin URL? Nah

**Comment by matks** [comment]
I can go with "Back-office API" but it sounds bad to me -> a back-office is a place where users go to manage things. A Back-office and an API sound two very different things to me.

"Backend API" ?

**Comment by Progi1984** [comment]
If It's Backoffice API, why not only `/admin123456789/api/`?

**Comment by kpodemski** [comment]
I'm in favor of just /admin-dir/api, let's go with that one 👍🏻

**Comment by matks** [comment]
@kpodemski I would rather not keep the `/admin-dir` prefix in order to NOT disclose the admin prefix to unwanted users 😅 

I also think `/api` is too simple. What if tomorrow back-office needs another API, a GraphQL API? A data visualization API? Then you'll have `/api` and `/graphql-api` or `/api` and `/visualization-api`

Simply `/api` is very generic: as soon as a 2nd API, whatever it is, is created it'll create confusion.

If we keep the "Backoffice API" thing then at we could have `/backoffice-api` or `/backend-api` : this will never be confused with an API we would create in the future 👍

**Comment by kpodemski** [comment]
@matks 

I do believe it's "the API", that will be used in the back office context. For the front office, there will be a different layer, and we can keep: admin-dev/api/ because solution creators will use this API inside the back office context anyway.

**Comment by matks** [comment]
I think the future will prove you wrong 😄 but as long as we remove that "New API" and put something better instead I'm happy

**Comment by matks** [comment]
Name changed to backoffice API and URL changed to `/api`

For the record I think it's not a good idea 😆 but I favor a quick decent solution instead of a best solution we agree on 6 months later. Because we're a team.

**Review by Progi1984 — APPROVED** [review]
Approved for UI Tests

**Review by FabienPapet — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Comment by matks** [comment]
@kpodemski @FabienPapet Told you guys: the integration tests are failing because of routing mistmatch between previous API and new API, as they both use `/api` main routing entry 😆 https://github.com/PrestaShop/PrestaShop/actions/runs/4936678666/jobs/8824504634?pr=32484

(the problem is probably in the test because it lacks the admin prefix, but it highlights what I was trying to explain)

**Comment by FabienPapet** [comment]
If the tests are failing, better fix the tests than doing weird things and add weird names. That's also why I suggested to add v2 prefix ;)

**Comment by kpodemski** [comment]
@FabienPapet but this API have nothing to do with webservice API nor is the second version of it 🤔

@matks I thought the path is admin-dev/api, why would the tests fail if old one is /api from the root path?

**Comment by matks** [comment]
> @FabienPapet but this API have nothing to do with webservice API nor is the second version of it 🤔

Agreed: the first API a.k.a "Webservice" is a data-centric SOAP-style API. It has no versioning. The new API a.k.a "Backoffice API" is a command-oriented API. In my PR I set version number to 0.1.0 as it is experimental today.

We could imagine a future where we have "Backoffice API" v1, then it evolves and the version number becomes v2, and so on.

Saying that the Backoffice API is the v2 of the webservice is not 100% accurate 😉 although it can be seen like this.
 
> @matks I thought the path is admin-dev/api, why would the tests fail if old one is /api from the root path?

I think the problem comes from the test

**Comment by matks** [comment]
8.1.0 Release Candidate 1 is published so the API name will not change anymore, at least for 8.1.x . I close this PR.

**Pull request closed without merging**
