### PR TITLE
Improve doctrine and phpdoc

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11770)

### CODE REVIEW

**Comment by MathiasReker** [comment]
@jolelievre wdyt? :)

**Comment by MathiasReker** [comment]
I remake this. It is not review able

**Comment by jolelievre** [comment]
Whaaat?! only 1579 files to review.. Easy peasy!

**Comment by MathiasReker** [comment]
This one should be more easy to review: https://github.com/PrestaShop/PrestaShop/pull/11772 =)

**Pull request closed without merging**
