### PR TITLE
Fix missing product limit/offset when ordering by price on Sale page

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Performances & bugfix : product list is not limited on sales page when ordering by price
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket | http://forge.prestashop.com/browse/BOOM-3698
| How to test?  | Display the sale page & order by price

### CODE REVIEW

**Comment by jocel1** [comment]
https://blackfire.io/profiles/compare/54d61fb5-c013-47ca-80a6-96764aec24c4/graph

**Review by Quetzacoalt91 — APPROVED** [review]
Fabulous

wind face

**Comment by eternoendless** [comment]
Thank you @jocel1

**Comment by vincentbz** [comment]
Hi guys !

Does that PR fix also this ticket ? 
http://forge.prestashop.com/browse/BOOM-2409

Thanks !

**Comment by jocel1** [comment]
Hi @vincentbz!

I think it a different bug, this one only applies to the sale page

**Comment by eternoendless** [comment]
Thank you @jocel1

**Pull request merged**
