### PR TITLE
Migrate "Internation > Locations > States" page

### LINKED ISSUE #10606: Migrate "International > Locations > States" page
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/15032
- [x] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [x] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [x] States page - Add new states button is not displayed after incorrect Save #21183
- [x] #29345

#### Controller / routing
- [x] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [x] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [x] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [x] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [x] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [x] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [x] The new controller actions comply with our naming convention
- [x] The new SF routes names and paths comply with our naming convention
- [x] The new Twig template names comply actions with our naming convention
- [x] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [x] CSS being added must follow theme conventions

#### Core layer
- [x] Commands and Queries only use native types but internally use VOs
- [x] All Handlers must have an Interface
##### Conventions
- [x] The created SF service names comply with our naming convention
- [x] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [x] The legacy controller and templates files are gone
- [x] If PR includes a new concept/mechanism, documentation must be written
- [x] JS and CSS assets must be compiled and up-to-date
- [x] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [x] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [x] Commands and Queries are tested with Behat tests
- [x] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [x] (soon) Controller is covered with E2E tests using puppeeter
- [x] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### LINKED ISSUE #10607: Migrate "International > Locations > States > Add new / edit state" page
Part of Symfony migration project
Type: page

## Status

Todo:
- [ ] Migrate form https://github.com/PrestaShop/PrestaShop/pull/15071
- [ ] Multistore - Add information message https://github.com/PrestaShop/PrestaShop/issues/19413

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Bye Bye Legacy & Hello Symfony
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Resolves #10606, resolves #10607
| How to test?      | This PR enables the Symfony pages for "States" pages <br > <br> Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4055576581

**:notebook: BC Breaks**
* Removed class `AdminStatesController`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27590)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Comment by Progi1984** [comment]
@atomiix Rebased

**Comment by Progi1984** [comment]
@atomiix Sorry, I rebased & fixed UI Tests for running with new page (Like that, the nightly will be :green_circle: )

@PrestaShop/qa-automation @boubkerbribri Need review

**Review by nesrineabdmouleh — DISMISSED** [review]

**Comment by nicosomb** [comment]
@Progi1984 there is a conflict, could you please fix it?

**Comment by Progi1984** [comment]
@nicosomb @nesrineabdmouleh Rebased. Sorry :)

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
LGTM for UI tests

**Review by nicosomb — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Tested Add/Edit States.
Errors are well displayed when needed :
Screenshot 2023-02-10 at 10 31 51
Screenshot 2023-02-10 at 10 37 17
Screenshot 2023-02-10 at 10 37 30

LGTM ! It is QA ✅

**Comment by atomiix** [comment]
Thanks @Progi1984 and everyone involved!

**Pull request merged**
