### PR TITLE
Merge branch "1.7.7.x" into "develop"

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Merge branch "1.7.7.x" into "develop".
| Type?         | improvement
| Category?     | ME
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Tests must be green. No need QA.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18918)

### CODE REVIEW

**Comment by matks** [comment]
You need to delete public assets

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@PierreRambaud Shall we put `admin-dev/themes/new-theme/js/fos_js_routes.json` in `.gitignore` and compute it with `make assets` ?

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
> @PierreRambaud Shall we put `admin-dev/themes/new-theme/js/fos_js_routes.json` in `.gitignore` and compute it with `make assets` ?

I thought it was already the case in 178? Or we just discussed it?

**Comment by matks** [comment]
> > @PierreRambaud Shall we put `admin-dev/themes/new-theme/js/fos_js_routes.json` in `.gitignore` and compute it with `make assets` ?
> 
> I thought it was already the case in 178? Or we just discussed it?

Not done yet:
https://github.com/PrestaShop/PrestaShop/blob/develop/.gitignore
https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/js/fos_js_routes.json

**Comment by matks** [comment]
Thank you @Progi1984

**Pull request merged**
