### PR TITLE
Update classic webpack and fix watch issue by adding webpack-cli locally

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | If you have a wrong webpack version installed globally on your computer, you can't watch the classic theme
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go on the classic theme folder, npm i && npm run watch, classic theme should look as usual (It's testable by a dev)
| Possible impacts? | Assets builds

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24323)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG CI is completly :red_circle:

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG CI is broken & Need rebase

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
I've an undefined offset getImages error on this one which cause the CI to fail but : I can't reproduce it exactly (did one time...)

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG OK for QA ? (Label WIP)

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

A discussed with @Robin-Fischer-PS, he is OK for QA by dev but with an autos test pass on it.

Thank you!

**Comment by atomiix** [comment]
I've browsed the front office after running `npm i && npm run watch` and I didn't see anything wrong.
I guess we can pass the functional campaign @boubkerbribri 

Capture d’écran 2021-06-16 à 16 06 58

**Review by boubkerbribri — APPROVED** [review]
UI tests OK ! 
Thanks @NeOMakinG

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @boubkerbribri

**Pull request merged**
