### PR TITLE
Upgrade prestashop modules

### LINKED ISSUE #27077: Display issue for the polish language and the search bar
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The search bar cannot show an entire phrase translated in Polish because of the unnecessary padding

image

### Expected behavior

Search bar displayed properly :-)

### Steps to reproduce

1. Install polish language
2. See front office and the display issue

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

ps_searchbar

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Upgrade prestashop modules to latest relevant version.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | 
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28259)

### CODE REVIEW

**Comment by matks** [comment]
This Pull Request updates
- module blockreassurance from 5.1.0 to 5.1.1
- module searchbar from 2.1.2 to 2.1.3
- module statssales from 2.0.0 to 2.1.0

**Review by jolelievre — APPROVED** [review]
Thanks @matks

**Review by Progi1984 — DISMISSED** [review]
Please indicate updated modules and versions.

**Comment by matks** [comment]
> Please indicate updated modules and versions.

I must gift you glasses 😄 
Capture d’écran 2022-04-14 à 09 33 51

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @matks

**Pull request merged**
