### PR TITLE
Fix accented chars replacement for ä ö Ä Ö

### LINKED ISSUE #26157: Incorrect accented chars replacement for ö and ä
#### Describe the bug

When importing a product with the above letters in name, the friendly URL is not perfectly correct, ö is changed to o, and ä is changed to a

#### Expected behavior

ö should be changed to oe and ä should be changed to ae

#### Steps to Reproduce

1. Prepare a simple CSV file with only one cell - a name of a product containing "ö ä" letters
2. Import the file
3. Check the friendly URL created
4. Compare that friendly URL to the one generated by the "regenerate" button in back office 

#### Additional information

* PrestaShop version: all 1.6 and 1.7
* PHP version: all versions

### PR DESCRIPTION
**Pull request by daresh**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix accented chars replacement for ä ö Ä Ö
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26157
| How to test?      | Import a product with ä ö Ä Ö characters in it's name and check it's friendly URL
| Possible impacts? | CSV Import

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26160)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
Thank you very much for your PR @daresh 👍 

It cannot be approved before we reach for a decision (see discussion in the issue), but code wise I think it's ok

**Comment by daresh** [comment]
> It cannot be approved before we reach for a decision (see discussion in the issue), but code wise I think it's ok

Of course, so waiting for a conslusion there :)

**Review by Progi1984 — COMMENTED** [review]
@daresh Hi, thank you for your contribution.

Do you think you will be able to add a small unit tests for your cases ?

**Comment by daresh** [comment]
Would be great, by I've never done it, so I would need some tutorial :)

**Comment by Progi1984** [comment]
@daresh Check the file `tests/Unit/Classes/ToolsTest.php`. You will have some samples in this one.

**Comment by matks** [comment]
@daresh friendly reminder 😄

**Comment by davidglezz** [comment]
I disagree with this PR because, for example, the conversion from `ö` to `oe` is only applicable for locales: German (`de_DE`), German formal (`de_DE_formal`), German (Switzerland) formal (`de_CH`), German (Switzerland) informal (`de_CH_informal`), and German (Austria) (`de_AT`) locales.

https://en.wikipedia.org/wiki/%C3%96
https://github.com/WordPress/WordPress/blob/master/wp-includes/formatting.php#L1552

**Comment by daresh** [comment]
Thanks for your input. If we leave it as it is, there still will be an incosistency between how it's done in JS, nad how it's done in PHP. Probably both need fixing to take locale into account.

**Comment by matks** [comment]
Hi and thank you for the additionnal infos

I just pinged @Julievrz to get an answer for https://github.com/PrestaShop/PrestaShop/issues/26157#issuecomment-1030004689

**Comment by davidglezz** [comment]
I think this solution is better, less code to maintain
https://github.com/PrestaShop/PrestaShop/pull/27176

**Comment by Julievrz** [comment]
> Hi and thank you for the additionnal infos
> 
> I just pinged @Julievrz to get an answer for [#26157 (comment)](https://github.com/PrestaShop/PrestaShop/issues/26157#issuecomment-1030004689)

I asked German translators on Crowdin + on the #translation channel on the OS Slack.

**Comment by kpodemski** [comment]
Hello @Julievrz 

Do you have any news about this one?

**Comment by Julievrz** [comment]
> Hello @Julievrz
> 
> Do you have any news about this one?

Hi Kristian,

The question was answered in the issue. ☺️ https://github.com/PrestaShop/PrestaShop/issues/26157#issuecomment-1032441908

**Comment by marsaldev** [comment]
Hi @daresh ,

it looks like this PR is now stale. I close it as our rules state it 
"Pull Requests may be closed after 30 days of inactivity following a request for modifications."
(https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

Don't worry we can reopen the PR when you have some time and motivation 😉 just ping me

Thank you 😊

**Pull request closed without merging**
