### PR TITLE
Fix status dropdown of order listing page not being well displayed using rtl language

### LINKED ISSUE #21322: BO - Order page - RTL language - Status are not well displayed
#### Describe the bug

In the BO > Order page > when RTL is enabled, Statuses are not well displayed
image

#### Steps to Reproduce

1. Go to BO > International > Upload Arabic language
2. Change the BO language to Arabic
3. Go to BO  > Order list page > change status
4. See an error

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | Fix status dropdown of order listing page not being well displayed using rtl language by adding a right: inherit on .dropdown-menu using rtl file
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21322 .
| How to test?  | Activate Arabic language, go on order page, open a dropdown, you should see it normally

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21343)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
@NeOMakinG I believe `admin-dev/themes/new-theme/public/theme_rtl.css` should not be commited into git 🤔 ?

**Comment by NeOMakinG** [comment]
> @NeOMakinG I believe `admin-dev/themes/new-theme/public/theme_rtl.css` should not be commited into git 🤔 ?

Damn, only rtlfix should be, my bad, sorry!

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 
image

Thanks!

**Comment by jolelievre** [comment]
Thanks @NeOMakinG and @khouloudbelguith

**Pull request merged**
