### PR TITLE
Fix images quickview also updating product page by changing product i…

### LINKED ISSUE #20587: [FO] can't change color of a product: only the url changes
# Describe the bug

On a product page, when I change the color of an article, it doesn't change the color on the front, only the url changes

#### Expected behavior

On a product page, when I change the color of an article, I expect to see the color of that article to change to what I set.

#### Steps to Reproduce

1. Go to product page and choose a product (a tshirt would do it) 
2. change the color from black to white or reverse
==>See the URL changing but not the picture of the tshirt according to the color

_Note: The right product go into the basket_ 

**Screenshots**

https://drive.google.com/file/d/1YVlnsvMKtiL9Wcqq2xv996ZzHJ6yocQe/view

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
…mages selectors

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | See https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-672781474
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15531 and #20587 .
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-672781474

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20556)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by ngodefroy** [comment]
I managed to reproduce the issue: the product image isnt changing when I choose color. 
https://drive.google.com/file/d/1aOaY9aNdZgXN_YcR_oHHmG8zxlcfXZua/view

**Comment by NeOMakinG** [comment]
Did you build assets @ngodefroy ? I can't manage to reproduce it on this branche :/

**Comment by matthieu-rolland** [comment]
> I managed to reproduce the issue: the product image isnt changing when I choose color.
> https://drive.google.com/file/d/1aOaY9aNdZgXN_YcR_oHHmG8zxlcfXZua/view



> Did you build assets @ngodefroy ? I can't manage to reproduce it on this branche :/

He probably made a `make install` otherwise he wouldn't even be able to properly display the page (or am I missing something?). So he should have your modifications... except if he just switched branch without doing a fresh install, can you tell us more @ngodefroy ?

**Comment by NeOMakinG** [comment]
@matthieu-rolland I think the only way is by switching branch, but it's possible !

I just tested it and I can't manage to reproduce the same thing with this PR

**Comment by ngodefroy** [comment]
> @matthieu-rolland @NeOMakinG  I think the only way is by switching branch, but it's possible !
> 
> I just tested it and I can't manage to reproduce the same thing with this PR

what I did; 
```bash
git prcm origin 20556 develop
git st
make install
```

**Comment by matthieu-rolland** [comment]
The bug seems to be fixed on my side too 🤔 

https://drive.google.com/file/d/1nZkZc9PKBC2E3G4ZRFdwwgR0yeZMP5wc/view


We must be missing something.

**Comment by matks** [comment]
Tested, same for me it seems to fix the issue.

@ngodefroy when you do the `git prcm` there is no error message then ? The `git st` shows nothing wrong ?

**Comment by ngodefroy** [comment]
> Tested, same for me it seems to fix the issue.
> 
> @ngodefroy when you do the `git prcm` there is no error message then ? The `git st` shows nothing wrong ?

I have this message, I clicked "exit" button. Let me redo the test ! 
Capture d’écran 2020-08-18 à 15 45 49

**Comment by SimonGrn** [comment]
Fixed 
See video : https://drive.google.com/file/d/1Zt8UAMGbvl3tQvtsmNdcGWuzX_J7SFr7/view

**Comment by matks** [comment]
Thank you @NeOMakinG

**Pull request merged**
