### PR TITLE
Remove controller deprecations

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated code
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI 🟢  and automated tests
| Fixed ticket?     | n/a

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]
OK for me but **DO NOT MERGE** now. (target is 9.x)

**Review by lartist — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by FabienPapet** [comment]
tests: https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4084722966

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @FabienPapet 

I have launched the automatic tests. They failed in some tests (**Orders, Catalog and FO**) . This is the test run
https://github.com/HanaRebaiQA/testing_pr/actions/runs/4085957533

**PS**: I have launched many times failed jobs.
ping @PrestaShop/qa-automation Could you please check it?

**Comment by FabienPapet** [comment]
Failure are unrelated imo

**Review by HanaRebaiQA — APPROVED** [review]
Hello @FabienPapet 

I have launched again the automated tests. 
It fails now only on **BO:Catalog:01-04** and **FO**. https://github.com/HanaRebaiQA/testing_pr/actions/runs/4101502231
These fails exist on develop and not fixed yet as confirmed by @PrestaShop/qa-automation 

So, it's QA :heavy_check_mark: for this PR!
Thank You!

**Comment by nicosomb** [comment]
Thank you @FabienPapet and @HanaRebaiQA !

**Pull request merged**
