### PR TITLE
Fix Smarty.class.php class not found

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Prevent error while changing cache mode to MySQL.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Change cache mode to MySQL and reload page.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9040)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]
:ok_hand:

**Comment by Quetzacoalt91** [comment]
You could make it available for 1.7.4.0 by update the base branch to `1.7.4.x`. :)

**Comment by PierreRambaud** [comment]
Thanks @eternoendless for the update :)

**Review by eternoendless — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @PierreRambaud

**Pull request merged**
