### PR TITLE
Add 2 new hooks actionDispatcherBefore and actionDispatcherAfter

### PR DESCRIPTION
**Pull request by jherry**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | add 2 hooks in dispatch() method of Dispatcher class. One is called at the beginning (actionDispatcherBefore) and the other at the end (actionDispatcherAfter). |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | no |
| How to test? |  |

### CODE REVIEW

**Comment by kpodemski** [comment]
Use case?

**Comment by jherry** [comment]
This is used by HTML cache modules: 

- actionDispatcherBefore: if cache exists then display it and exit
- actionDispatcherAfter: used to display some stats

I'm trying to reduce the number of overrides in my module. These hooks could also be used for other HTML cache modules.
Do you think it's too specific?

**Comment by kpodemski** [comment]
Nah, it's ok, i was just curious, it would be good to run profiler and see if this would not be bad for performance if cache module is not used and Hook::exec is fired anyway

**Comment by xBorderie** [comment]
It seems your branch was not synchronized with 'develop', could you rebase it? Thank you!

**Comment by jherry** [comment]
How do I do that? Do I have to cancel this pull request and create a new one? (sorry I'm not used to this)

**Comment by julienbourdeau** [comment]
Let's debate it before you rebase. I doubt you can cache a whole page so early in the process. Have you started working on the module?

**Comment by jherry** [comment]
Yes, the module is on addons for about 2 years :-)

**Comment by kpodemski** [comment]
@julienbourdeau i assume that Cache is created `after` and `before` module only checks if cached version is available, simple as that. 

Still, it'd like to see profiler results ;D

**Comment by jherry** [comment]
Ok, I rebased the branch (I guess). The build failed but it does not seem to be related to my commit, does it?
For my info, a build is run on each pull request code?

**Comment by firstred** [comment]
Yep, a build is run on each pull request.

PR looks good to me. I'm not sure what the impact on performance would be, but the code looks okay.

**Review by firstred — APPROVED** [review]

**Comment by aleeks** [comment]
Missing sql update into 1.7.0.0.sql nop ?

`INSERT INTO `PREFIX_hook` (`name`, `title`, `description`, `position`) VALUES ('actionDispatcherAfter', 'real title', 'This hook is called at the end of the dispatch method of the Dispatcher.', '1');`

`INSERT INTO `PREFIX_hook` (`name`, `title`, `description`, `position`) VALUES ('actionDispatcherBefore', 'real title', 'This hook is called at the beginning of the dispatch method of the Dispatcher.', '1');`


And it can be a bit specific like(example of another hook)
- **title** : Display extra content on the product page
- **description** : This hook expects ProductExtraContent instances, which will be properly displayed by the template on the product page.

**Comment by jherry** [comment]
I added hook in upgrade script.
I modified hook title. I don't know how to be more specific, I did like other 'action' hooks.

**Comment by jherry** [comment]
No news? :-( @aleeks Are you still waiting for something from me? Can you remove the label "waiting for author feedback"?

**Comment by antoin-m** [comment]
Hey @jherry, thank you for your contribution!

I cherry-picked you commit in this PR https://github.com/PrestaShop/PrestaShop/pull/7438

**Pull request closed without merging**
