### PR TITLE
Restore cart if the customer logs off

### PR DESCRIPTION
**Pull request by kijamve**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Restore cart if the customer logs off
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Log out with a cart, it should look the same later.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17238)

### CODE REVIEW

**Comment by Progi1984** [comment]
Hello @PrestaShop/prestashop-product-team, is it a wanted behavior ? Thanks

**Comment by marionf** [comment]
Hello @kijamve 

Thank you for your PR
Please before opening a PR, [create an issue](https://github.com/PrestaShop/PrestaShop/issues/new/choose) to describe the problem or what you want to do
There is already an option to do that in shop parameters > Customers > "Re-display cart at login"

**Comment by kijamve** [comment]
@marionf It does not do that, the PR does the opposite, it keeps the cart if you close the session. And It is not an issue, it is an improvement (maybe new feature).

**Comment by kijamve** [comment]
It is not an issue, it is an improvement (maybe new feature).

**Comment by marionf** [comment]
@kijamve 
Could you please open a feature request issue and describe what you want to do and why ?

**Comment by kpodemski** [comment]
This should be an option, you can't just keep someone's cart if that person decide to log off...

**Comment by PierreRambaud** [comment]
Hi @kijamve,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
