### PR TITLE
// wording/translation

### PR DESCRIPTION
**Pull request by kelu95**

### CODE REVIEW

**Comment by xBorderie** [comment]
Has @AlexEven had a chance to see all these?
I wonder about
 - "BAN-13" replacing "EAN-13" -- I never heard of BAN-13, what is it?
 - "Cost price" replacing "Pre-tax wholesale price" in ProductCombination.php (Alex is digging into this currently, I think)
 - "Price - Tax excluded" replacing "Pre-tax wholesale price" in ProductPrice.php
 - "Retail price" replacing "Selling price" in Product/form.html.twig
 - Adding ":" (I think we chose to never end labels with ":")
 
Also, could you give us more details about the whole "placeholder" thing. If that's what I think it is, OH YEAH! :)

**Comment by AlexEven** [comment]
@xBorderie It comes from the mock-ups, but I'll check the whole thing now that it's live on the software. Thanks for the feedback!

**Comment by xBorderie** [comment]
Let me just say that I'm pretty sure it should still be [EAN-13](https://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29) :)

> The numbers encoded in EAN-13 bar codes are product identification numbers, which are also called Japanese Article Numbers (JAN) in Japan.

**Comment by ket4z** [comment]
EAN-13 is just one of many barcode formats, incidentally used in Europe, surprise. Together with UPC code they are globally recognized and unique, however to make the platform more universal, the field should be either called "Barcode" OR leave it at EAN and additional "UPC" code should be introduced.

That is if you want to get it right. In any case BAN-13 is BS...

**Comment by xBorderie** [comment]
Yup, thanks @ket4z, that's pretty my thinking too.
My guess is that BAN-13 is just a mistake that came from the mock-ups. I just made PR #4934 to fix it :)
And [we already have a "UPC barcode" barcode](https://github.com/kelu95/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Product/ProductCombination.php#L87) :)

**Comment by Jonadabe** [comment]
https://github.com/tecnickcom/TCPDF

1. 1D and 2D barcodes: CODE 39, ANSI MH10.8M-1983, USD-3, 3 of 9, CODE 93, USS-93, Standard 2 of 5, Interleaved 2 of 5, CODE 128 A/B/C, 2 and 5 Digits UPC-Based Extension, EAN 8, EAN 13, UPC-A, UPC-E, MSI, POSTNET, PLANET, RMS4CC (Royal Mail 4-state Customer Code), CBC (Customer Bar Code), KIX (Klant index - Customer index), Intelligent Mail Barcode, Onecode, USPS-B-3200, CODABAR, CODE 11, PHARMACODE, PHARMACODE TWO-TRACKS, Datamatrix, QR-Code, PDF417;

;-)

**Comment by xBorderie** [comment]
Oh my ;)

**Pull request merged**
