### PR TITLE
Fix blank lines: Add and remove

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11781)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Please merge this ASAP.

**Comment by MathiasReker** [comment]
@PierreRambaud I would like to make some PR's that can conflict with this one. Can I have this one merged into develop? :)

**Comment by mickaelandrieu** [comment]
Hello @MathiasReker,

congrats for your 5th position in contributors rank list => http://contributors.prestashop.com/

Mickaël

**Comment by MathiasReker** [comment]
@mickaelandrieu Thank you! :) Can you have a look on this PR. It should be fast to review. :)

**Review by mickaelandrieu — APPROVED** [review]

**Pull request merged**
