### PR TITLE
CO: Update AdminImportController.php

### PR DESCRIPTION
**Pull request by Nobodaddy**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Eliminated waste translation item, because a) it makes no sense, b) translation into other languages would cause problems.
| Type?         |  improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by Nobodaddy** [comment]
These 'PrestonBot' comments are really deterent. Is this the subtext? ;)

**Comment by aleeks** [comment]
You edited the PR description.
Your commit name is: "CO : Update AdminImportController.php"

Regards

**Comment by xBorderie** [comment]
It's because if the space before colon. You should use "`CO: etc.`", not "`CO : etc.`" :)

**Comment by Nobodaddy** [comment]
Lol, thank you. I already got it, too, meanwhile.

**Pull request closed without merging**
