### PR TITLE
BO: add isset employee for img

### PR DESCRIPTION
**Pull request by studiokiwik**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description | Bug with img if no employee exist |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | If no employee exist |

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by mickaelandrieu** [comment]
@xBorderie lulz

**Comment by aleeks** [comment]
Hello, can you : 
- Rename your commit ?
- Be careful with your indentation please ?

Without this change, this PR will be closed tomorrow.

**Comment by maximebiloe** [comment]
Hello @studiokiwik,

I'm not sure to really understand why you add this test.
How the employee couldn't be defined? If I display the BO, the employee must be defined.

Regards

**Comment by antoin-m** [comment]
Hi @studiokiwik , thank you for your contribution.

If we are loading the BO's header then the `employee` has to be loaded so it doesn't really make sense to add `isset`s before using it.

Closed in favor of https://github.com/PrestaShop/PrestaShop/pull/7421

**Pull request closed without merging**
