### PR TITLE
In Stock Movement page, localize date & time

### LINKED ISSUE #26454: [BO] Stock movements page don't show time
## Describe the bug

Stock movements page show only date and not time
Capture d’écran 2021-10-27 à 18 24 06

## Expected behavior

Display date & **time** of movements
Capture d’écran 2021-10-27 à 18 19 51

## Steps to Reproduce

1. Go to 'Stock Movements pages'
2. See date without time

## Additional information

* PrestaShop version: 8.x
* PHP version: N/A

### LINKED ISSUE #27932: BO - The movements page is not working with a specific language
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When we change the employee language with a specific language created manually, the movements page is nok.
In the BO > Catalog > Product V2 > Stock tab, when we click on the link "View all stock movements", we are redirected to the movements page> an error displayed in the console & no movement is displayed
image

It should be OK
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > International > Localization > Lanaguages page & create a new lanaguage 
image
2. Change the employee language with this one
3. Go to BO > Catalog > Stocks > Movements page
5. Go to BO > Catalog > Products V2 > Edit a product
6. In the Stock tab > Click on "View all stock movements",
7. See error: redirection to the stocks page, no movement is displayed & an error is displayed in the console

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4
### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In Stock Movement page, localize date & time
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26454 (and Relative to #9591)
| How to test?      | In Stock Movement, the time is now displayed and the datetime is now localized. The date take the full date time format from the language.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28001)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello, 

I tested the PR and the time is well displayed. But I noticed the following issue:

1. Go to international> languages > Edit the language
2. Add string of characters in the date format > save
3. an invalid time is displayed in the movement page  

https://user-images.githubusercontent.com/89604350/159950806-07b88772-dc4b-4f0e-922b-efabe760f9ee.mp4

Could you please check?

Thanks,

**Comment by Progi1984** [comment]
@marwachelly No. It's the expected behavior as we used the [`date`](https://www.php.net/manual/fr/function.date.php) PHP function for display with the [format](https://www.php.net/manual/fr/datetime.format.php) defined in the Language page .

**Review by marwachelly — APPROVED** [review]
Hello @Progi1984 ,

So PR is tested and the issue is well fixed. 

Many thanks,

**Comment by Progi1984** [comment]
Thanks @marwachelly

**Pull request merged**
