### PR TITLE
Fix crashing for bulk actions

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | See issue.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/10836
| How to test?  | Should fix issue.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11394)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by matks** [comment]
Tests should be updated 😄 but that is a very good thing

**Comment by ntiepresta** [comment]
OK  :+1:

**Comment by Quetzacoalt91** [comment]
Unfortunately, the tests don't pass. :(

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @sarjon

**Pull request merged**
