### PR TITLE
Fix translations escaping for BO header

### LINKED ISSUE #24686: Maintenance information translation at BO header is not escaped properly
#### Describe the bug

If you set translation of
```
Your visitors and customers cannot access your shop while in maintenance mode.%s To manage the maintenance settings, go to Shop Parameters > Maintenance tab.
```

to like
```
Your visitors and customers cannot access your shop while in maintenance mode.%s To manage the maintenance settings, go to "Shop Parameters" > "Maintenance" tab.
```
then header breaks:
Screenshot 2021-05-28 at 11 00 49

#### Expected behavior

The header should remain normal and show only icon + maintenance text.

#### Steps to Reproduce

1. Shop must be in English
2. Translate the string that is shown in Describe the bug section and **add quotes** to the string.
3. Activate maintenance mode.
4. Go to any non-dashboard page.
5. See broken header.

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | title says it all
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24686.
| How to test?      | Issue has all the details
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24897)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thanks for the PR.
The issue is indeed fixed on all migrated pages, but on the legacy pages, I still have the bug @hibatallahAouadni mentioned here : https://github.com/PrestaShop/PrestaShop/issues/24686#issuecomment-850697066

Migrated pages : OK
Screenshot 2021-06-10 at 14 52 50

Legacy pages : NOK
Screenshot 2021-06-10 at 14 52 44

Could you please check and feedback ?
Thanks !

**Comment by kpodemski** [comment]
@florine2623 

you're right, fixed on legacy too

QA = checking header behavior on both themes :)

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Thanks @kpodemski !
It's all good to me !
Screenshot 2021-06-14 at 18 25 24
Screenshot 2021-06-14 at 18 24 50

**Comment by matks** [comment]
Thank you @kpodemski and @florine2623

**Pull request merged**
