### PR TITLE
[-] FO : split CCC CSS file for IE 9 

### PR DESCRIPTION
**Pull request by AgenceNetDesign**
(accept only 4095 css rules by file css file)

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.

@jeromenadaud is working on that too, but we want to restrict this splitting for this browser only. Other browsers are handling one file, there is no reason to split for all browsers css files.

Regards

**Comment by jeromenadaud** [comment]
Hi, 

@gRoussac  is right, there is no reason to split for all browsers css files.
Can you make change for this ?

Best regards.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by maximebiloe** [comment]
Hi,

This has been done here: https://github.com/PrestaShop/PrestaShop/pull/4444
It should be integrated in a future relase of PrestaShop 1.6.

Regards

**Pull request closed without merging**
