### PR TITLE
Make Advanced Parameters > Logs configuration form multistore compatible

### LINKED ISSUE #19358: Multistore - Advanced Parameters > Logs - Add checkboxes
As a merchant, I want to be able to select one or many fields / toggles when I am in a specific shop context or in a group context, so I can apply a different configuration for the selected store or group and see which parameters have different value(s) for the selected store or group.

[Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

### PR DESCRIPTION
**Pull request by ecomiz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR add checkboxes and specifics settings drop-downs list to  BO > Advanced Parameters > Logs page to make it multistore compatible
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19358 and #19311 
| Original PR?      | https://github.com/PrestaShop/PrestaShop/pull/25645
| How to test?      | See issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25645)

### CODE REVIEW

**Comment by ghost** [comment]
Hello @ecomiz,

The process changes a bit you can follow [this PR](https://github.com/PrestaShop/PrestaShop/pull/25914)

What you name on slack we have created a dedicated chanel.

**Comment by ecomiz** [comment]
> Hello @ecomiz,
> 
> The process changes a bit you can follow [this PR](https://github.com/PrestaShop/PrestaShop/pull/25914)
> 
> What you name on slack we have created a dedicated chanel.

My name on slack is : Alberto ECOMIZ

**Review by matks — CHANGES_REQUESTED** [review]
Hello @ecomiz and thank you for this PR. Apologies for late review 😭 

The PR provided as an example by @okom3pom https://github.com/PrestaShop/PrestaShop/pull/25914 features some nice unit tests that would be really helpful on this contribution too. Do you think you can add unit tests?

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@ecomiz Some news about this PR ?

**Comment by matks** [comment]
Hi @ecomiz,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. If you find some time and want to continue please ping me and I will reopen the contribution.

Thanks!

**Pull request closed without merging**
