### PR TITLE
Module name in order details data

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | i just had a situation where i needed it directly in order-confirmation.tpl :)
| Type?         |  improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | obvious
| Sponsor company  | impSolutions

#### Important guidelines

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8483)

### CODE REVIEW

**Comment by kpodemski** [comment]
btw. maybe you could guys add it to 1.7.3? very little change

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Sadly, it's too late for 1.7.3 :(

**Comment by kpodemski** [comment]
Ok, no problem :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Here you go! Thank you @kpodemski

**Pull request merged**
