### PR TITLE
Remove search fields when listing are empty

### LINKED ISSUE #17597: Remove search fields when listing are empty
**Describe the bug**
Remove search fields, search button, labels and bulk checkbox when listing are empty

Already migrated pages:
- [x] Catalog > categories
- [x] Catalog > monitoring
- [x] Catalog > brands
- [x] Catalog > suppliers
- [x] Catalog > files
- [x] Customers > customers
- [x] Customers > addresses
- [x] Customer service > order messages
- [x] Design > pages (categories & pages)
- [x] International > localization > Languages
- [x] International > localization > Currencies
- [x] International > taxes > taxes
- [x] Shop parameters > order settings > statuses
- [x] Shop parameters > customer settings > groups
- [x] Shop parameters > contact > contacts
- [x] Shop parameters > traffic & SEO > SEO & URLs
- [x] Advanced parameters > E-mail 
- [x] Advanced parameters > Team > Employees 
- [x] Advanced parameters > Team > Profiles 
- [x] Advanced parameters > Database > SQL manager 
- [x] Advanced parameters > Database > DB backup
- [x] Advanced parameters > Logs
- [x] Advanced parameters > Webservice

Not yet migrated pages:
- [ ] Catalog > products
- [ ] Catalog > attributes
- [ ] Catalog > features
- [ ] Catalog > cart rules
- [ ] Catalog > catalog price rules
- [ ] Customer service > customer service
- [ ] Customer service > merchandise returns
- [ ] Design > image settings
- [ ] Shipping > carriers
- [ ] International > locations > Zones
- [ ] International > locations > Countries
- [ ] International > locations > States
- [ ] International > taxes > taxes rules
- [ ] Shop parameters > customer settings > titles
- [ ] Shop parameters > contact > stores
- [ ] Shop parameters > traffic & SEO > Search engines
- [ ] Shop parameters > traffic & SEO > Referrers
- [ ] Shop parameters > Search > Search
- [ ] Shop parameters > Search > Tags
- [ ] Advanced parameters > Multistore > Admin shop group
- [ ] Advanced parameters > Multistore > Admin shop
- [ ] Advanced parameters > Multistore > Admin shop url

**Screenshots**
Pages without empty state
capture d'écran_2306

Pages with empty state
capture d'écran_2305

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove search fields when listing are empty
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17597
| How to test?  | Already migrated pages:<br>- Catalog > categories<br>- Catalog > monitoring<br>- Catalog > brands<br>- Catalog > suppliers<br>- Catalog > files<br>- Customers > customers<br>- Customers > addresses<br>- Customer service > order messages<br>- Design > pages (categories & pages)<br>- International > localization > Languages<br>- International > localization > Currencies<br>- International > taxes > taxes<br>- Shop parameters > order settings > statuses<br>- Shop parameters > customer settings > groups<br>- Shop parameters > customer settings > titles<br>- Shop parameters > contact > contacts<br>- Shop parameters > traffic & SEO > SEO & URLs<br>- Advanced parameters > E-mail <br>- Advanced parameters > Team > Employees <br>- Advanced parameters > Team > Profiles <br>- Advanced parameters > Database > SQL manager <br>- Advanced parameters > Database > DB backup<br>- Advanced parameters > Logs<br>- Advanced parameters > Webservice<br><br>Not yet migrated pages:<br>- Catalog > products<br>- Catalog > attributes<br>- Catalog > features<br>- Catalog > cart rules<br>- Catalog > catalog price rules<br>- Customer service > customer service<br>- Customer service > merchandise returns<br>- Design > image settings<br>- Shipping > carriers<br>- International > locations > Zones<br>- International > locations > Countries<br>- International > locations > States<br>- International > taxes > taxes rules<br>- Shop parameters > contact > stores<br>- Shop parameters > traffic & SEO > Search engines<br>- Shop parameters > traffic & SEO > Referrers<br>- Shop parameters > Search > Search<br>- Shop parameters > Search > Tags<br>- Advanced parameters > Multistore > Admin shop group<br>- Advanced parameters > Multistore > Admin shop<br>- Advanced parameters > Multistore > Admin shop url

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19606)

### CODE REVIEW

**Comment by matks** [comment]
@Progi1984 Be careful, this bugfix did introduced a big issue last time it was attempted 😅 

Did you handle this [complex usecase](https://github.com/PrestaShop/PrestaShop/issues/17597#issuecomment-584641810) ?

**Review by PierreRambaud — APPROVED** [review]
YOLO

**Comment by Progi1984** [comment]
@matks Sample with Order Messages :

Without messages :
image

With a message : 
image

With list filtered and no results :
image

With list filtered and with results :
image

**Comment by matks** [comment]
@Progi1984 beautiful 👏

**Review by matks — APPROVED** [review]

**Comment by atomiix** [comment]
Hey @Progi1984, I think this PR fixes it too : https://github.com/PrestaShop/PrestaShop/pull/19597/files#diff-d3df3c524df921323ec17cedfe38888bL26
I didn't know there was an issue opened for that when I did it 😅

**Comment by Progi1984** [comment]
@atomiix I close it and I assign you the issue.

**Pull request closed without merging**
