### PR TITLE
CSS&HTML cleaning in "modern" email templates

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | CSS&HTML cleaning in "Modern" email templates
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Upload to mails/themes/modern and launch email preview in BO. Tested on 1.7.6.3 installation. All good.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17462)

### CODE REVIEW

**Comment by Hlavtox** [comment]
@PrestaShark I would be very careful deleting anything from the email templates. In all html email frameworks, there are millions of resets and hack, to make it looking SOMEHOW acceptable in all clients.

Outlook cannot do this, Gmail does that, Apple mail has another thing set this way etc. etc.

**Comment by ghost** [comment]
I see the point https://github.com/mjmlio/mjml/issues/577
Sorry for my ignorance.

**Comment by Hlavtox** [comment]
@PrestaShark Like, all of this for a fucking button? :D :D

 ```
<table role="presentation" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td style="background: #FFFFFF; text-align: center;">
            <a href="url" style="background: #FFFFFF; padding: 15px; border: 1px solid #37C84D; font-family:Arial, Open-sans, Helvetica, sans-serif; font-size: 16px; line-height: 1.1; text-align: center; text-decoration: none; display: block; font-weight: bold;">
                <span style="color:#37C84D;">Do that</span>
            </a>
        </td>
    </tr>
</table>
```

When this would be enough...
```
<a href="url" style="button button-yellow">Do that</a>
```

**Comment by ghost** [comment]
"It Wasn't Just a Puppy..."

**Pull request closed without merging**
