### PR TITLE
Bump classic-theme to 2.1.2

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Bump classic-theme to 2.1.2
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 & UI tests 🟢
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/7170451245
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @boherm,

CI are full red :/ https://github.com/paulnoelcholot/testing_pr/actions/runs/7180137228

Can you check that please? :pray: 

Thanks!

**Comment by matks** [comment]
I re-run the CI because the issue is very weird 😮 it's not a sanity test fail, it's a git merge fail 🤔 

```
Run git fetch origin pull/34812/head:pr34812
From https://github.com/PrestaShop/PrestaShop
 * [new ref]               refs/pull/34812/head -> pr34812
Switched to branch 'pr34812'
Run git fetch origin develop:develop
From https://github.com/PrestaShop/PrestaShop
   f5c6389b3a..549cb4eba6  develop    -> develop
   f5c6389b3a..549cb4eba6  develop    -> origin/develop
Auto-merging src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php
CONFLICT (content): Merge conflict in src/PrestaShopBundle/Form/Admin/Type/CustomMoneyType.php
Auto-merging src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
CONFLICT (content): Merge conflict in src/PrestaShopBundle/Resources/config/services/bundle/form/form_extension.yml
Auto-merging src/PrestaShopBundle/Resources/config/services/core/localization.yml
CONFLICT (content): Merge conflict in src/PrestaShopBundle/Resources/config/services/core/localization.yml
Rebasing (1/5)
error: could not apply 812625b61e... Fix CustomMoneyType for some locales
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 812625b61e... Fix CustomMoneyType for some locales
Error: Process completed with exit code 1.
```

**Review by tleon — APPROVED** [review]

**Review by matks — APPROVED** [review]
This time it's good 👍

**Comment by matks** [comment]
@paulnoelcholot Oh I was confused, I did not see you were running UI Tests.

I think this is because on your fork ; the branch `8.1.x` is outdated.

@boherm ran the tests https://github.com/boherm/ga.tests.ui.pr/actions/runs/7170451245

**Review by M0rgan01 — APPROVED** [review]

**Comment by matks** [comment]
New run of UI Tests by @boherm is all green 🟢 https://github.com/boherm/ga.tests.ui.pr/actions/runs/7170451245

**Pull request merged**
