### PR TITLE
Fix blocking add to cart button

### LINKED ISSUE #25221: The product-list on the checkout does not work with custom themes
#### Describe the bug

This fix https://github.com/PrestaShop/PrestaShop/issues/9634 breaks the "Add to cart" buttons in the product-list in all custom themes.

Short movie:
https://www.loom.com/share/1ed22057f0964fee84eaaf9bcc73a3c9

Fix https://github.com/PrestaShop/PrestaShop/issues/9634 adds to core.js this code to disable the "Add to cart" button:
$('[data-button-action="add-to-cart"]').prop('disabled', true);

The problem is that all custom themes use this code:
data-button-action="add-to-cart"
to add the "Add to cart" button in the product-list, which means that after an update to 1.7.8.x all shops with custom themes will have this problem and it is difficult to fix it directly in the theme.

You can go here:
https://addons.prestashop.com/en/3-templates-prestashop
open any theme and check the source code of the "Add to cart" button in the product-list to see that all themes use in the product-list that code:
data-button-action="add-to-cart"

#### Expected behavior

The "Add to cart" button should be disabled only on the product page in the form:
form#add-to-cart-or-refresh

In means that this code in the core.js:
$('[data-button-action="add-to-cart"]').prop('disabled', true);

should be replaced with something as this:
$('form#add-to-cart-or-refresh [data-button-action="add-to-cart"]').prop('disabled', true);

or this code should be removed from core.js and added to /themes/classic/assets/js/theme.js

#### Steps to Reproduce

1.Install a custom theme with the "Add to cart" button in the product-list.

2.Click the "Add to cart" button in the product-list.

3.After the popup is closed, all other buttons will be disabled.

**Screenshots**
Before clicking the "Add to cart" button:
https://prnt.sc/18a24cm

after closing the popup, all buttons are disabled:
https://prnt.sc/18a1zux

Short movie:
https://www.loom.com/share/1ed22057f0964fee84eaaf9bcc73a3c9

#### Additional information

* PrestaShop version: 1.7.8.0

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR fixes a regression introduced in PR described in the related issue
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25221 
| How to test?      | Instruction below
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

1. Edit `themes/classic/templates/catalog/_partials/miniatures/product.tpl`
2. Add code available below, right before `</article>`:

```
{if $product.add_to_cart_url}
     <form action="{$urls.pages.cart}" method="post">
      <input type="hidden" name="token" value="{Tools::getToken(false)}">
      <input type="hidden" name="id_product" value="{$product.id}">
      <input type="number" name="qty" value="{$product.minimal_quantity}">
      <button class="btn btn-primary add-to-cart" data-button-action="add-to-cart" type="submit" >
        Add to cart
      </button>
    </form>
{/if}
```
3. Try to add the product to cart, before and after PR

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25316)

### CODE REVIEW

**Review by PierreRambaud — COMMENTED** [review]
I'm afraid, the CI is broken :(

**Comment by kpodemski** [comment]
@PierreRambaud addons modules 🙄

**Comment by PierreRambaud** [comment]
> @PierreRambaud addons modules

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team this is critical for any third party theme

**Comment by Robin-Fischer-PS** [comment]
Hi @kpodemski ,

Thanks for the ping, we have readjusted the severity of the issue from Minor to Major, and will include your PR in the RC1 build !

**Comment by florine2623** [comment]
Hello @kpodemski ,

Thank you for the PR, after testing it, it is validated !

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623

**Comment by Prestacrea** [comment]
Hello @PierreRambaud @NeOMakinG 

This doesn't work if button content is only HTML without text (like an icon) :'(

`const $form = $(event.target.form);` should be replaced by `const $form = $(event.currentTarget.form);`

It is really hard to fix it from the theme, so for now, any theme that uses only an icon for this kind of button has this feature broken with Prestashop 1.7.8.0.

**Comment by kpodemski** [comment]
@Prestacrea can you make a PR targeting 1.7.8.x branch?

**Pull request merged**
