### PR TITLE
[*] FO: Removing never-used code in default-template

### PR DESCRIPTION
**Pull request by ghost**
$errors_discount is placed in these two template files but is never set,
neither in controllers, views or any other files (including modules).
This should be removed from the main branch.

It is probably code from an old code base (or a previously bundled module), but this variable is set nowhere, thus this code block should be removed as it might fool developers :)

### CODE REVIEW

**Comment by SirDev** [comment]
(this is my first pull request, evar). Please let me know if I did all according to your standards,

Erik

**Comment by kpodemski** [comment]
I am not sure but I think I used one block of this code in one of my projects, where I need to change behaviour and restrictions of the discounts ;)

**Comment by SirDev** [comment]
If you search the whole code base for errors_discount you will find zero matches outside of the files that have been changed. There's no setters for these smarty template vars, hence the code block will never be hit, hence it is obsolete. Am I wrong?

**Comment by PrestaEdit** [comment]
Just for fact... Do you know that this portion of code is in template since the... 0.9.7 ! And, already at this moment, it's seems to be not assigned.

Seems to be strange =)

**Comment by sfroment42** [comment]
:+1:

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.

Reported here https://github.com/PrestaShop/PrestaShop/pull/3881/files

Regards

**Pull request closed without merging**
