### PR TITLE
Fix wording

### LINKED ISSUE #22565: BO - Webservice - Webservice key is empty
#### Describe the bug

In the BO > Advanced Parameters > Webservice page, when we try to add a web service key with special characters, it will be empty

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1. Go to BO > Advanced Parameters > Webservice page 
2. Create a webservice key with this `<LDEXRUXFJHJI69FZWBXHNRKQ3W6VFU>` Key
3. Save
4. See the error
5. Select All => Try to disable with bulk action
6. See exception

image

#### Additional information

* PrestaShop version: 1769, 1770, develop (1780)
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Quick PR for fixing the wording as suggested by @Julievrz 
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22565
| Related PRs       | #28266 
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Comment by marsaldev** [comment]
@Julievrz Here you are the PR for fix the wording 😊

**Review by Progi1984 — APPROVED** [review]

**Comment by Julievrz** [comment]
> @Julievrz Here you are the PR for fix the wording 😊

Thank you!

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@PrestaShop/qa-team I guess we don't need to test this

**Review by florine2623 — APPROVED** [review]
Thanks @marsaldev and @Julievrz !

It is QA ✅

**Comment by matks** [comment]
Thank you @marsaldev

**Pull request merged**
