### PR TITLE
Remove default meta description

### LINKED ISSUE #28941: Remove default meta description "Shop powered by PrestaShop"
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Ton of stores have  "Shop powered by PrestaShop" in meta description : it's bad for seo.

### Describe the solution you'd like

And empty description is best for beginner seo: Google will compute a description based on the home page content. IT's more relevant.

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove default meta description "Shop powered by PrestaShop", and improve prestashop beginner seo
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28941
| How to test?      | Install prestashop, see that the meta description is not here anymore
| Possible impacts? | none

### CODE REVIEW

**Comment by micka-fdz** [comment]
Hi @jf-viguier, nice PR!

I think you can also remove this wording here:
https://github.com/PrestaShop/PrestaShop/blob/6f8365ebba40b37e611525597ea0d3f2c907dc76/classes/lang/KeysReference/MetaLang.php#L57

**Review by NeOMakinG — DISMISSED** [review]
👍

**Review by micka-fdz — DISMISSED** [review]

**Review by matks — DISMISSED** [review]
PR valid for code, I can't tell if this is expected behavior though :D

**Review by kpodemski — DISMISSED** [review]
I agree that it is probably better to have no description than a description saying that it's a store powered by PrestaShop. One of the common mistakes merchant's do is not changing this later :)

**Review by florine2623 — COMMENTED** [review]
Hello @jf-viguier ,

In Traffic & SEO, the description as been removed:
Screenshot 2022-07-15 at 12 28 11


But in Translation, I still see "Shop powered by PrestaShop", as you can see here:
Screenshot 2022-07-15 at 12 28 20

What do you think ?

**Comment by kpodemski** [comment]
@florine2623 

I don't think it's related. We need to export .xlf files for a new release, and then it should be all good.

**Comment by kpodemski** [comment]
@jf-viguier could you rebase your PR? :)

**Comment by jf-viguier** [comment]
@kpodemski rebase done

**Review by kpodemski — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by micka-fdz — DISMISSED** [review]

**Review by matks — DISMISSED** [review]
I'm sorry :( there is one more rebase to do as file `classes/lang/KeysReference/MetaLang.php` is in conflict

**Comment by jf-viguier** [comment]
@matks rebase done

**Review by kpodemski — DISMISSED** [review]

**Comment by atomiix** [comment]
Closed/reopened to trigger the CI

**Comment by atomiix** [comment]
I think @micka-fdz's comment is not here anymore?
> Hi @jf-viguier, nice PR!
> 
> I think you can also remove this wording here:
> 
> 
https://github.com/PrestaShop/PrestaShop/blob/6f8365ebba40b37e611525597ea0d3f2c907dc76/classes/lang/KeysReference/MetaLang.php#L57

**Comment by jf-viguier** [comment]
@atomiix it's done

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @jf-viguier ,

No message 'Shop powered by PrestaShop' written in Traffic & SEO. Possible to add a custom meta description.

It is QA ✅ 
Thanks!

**Comment by atomiix** [comment]
Thanks @jf-viguier

**Pull request merged**
