### PR TITLE
[*] Security : Use a better password hashing method

### PR DESCRIPTION
**Pull request by tiennou**
This changes the password hashing method to use [phpass-0.3](http://www.openwall.com/phpass/) instead of md5 + a install-wide hash. I hope using phpass is fine for you (it's public domain, and is used in Wordpress and Drupal last time I checked).

It handles password upgrades the first the user logs in again though, because we obviously don't have access to the plaintext.

Notes :
- [x] I didn't do anything w.r.t the database structure update (I did those manually), but I'm expecting there's an automated script somewhere that must be updated because the column size changed.
- [x] The configuration options of PasswordHash are hardcoded (the first parameter is the estimated "strength" of the hash, the seconds indicates whether hashes are machine-dependent or not). I've  setup adequate default, but if someone sees a need for them.
- [x] I didn't run tests, because I haven't been able to understand how they work. Pointers accepted ;-).

### CODE REVIEW

**Comment by tiennou** [comment]
Rebased, because I (plan to) work on Prestashop for a little internal project of mine, and this is one of my moving parts — also, someone asked me the status of it.

Note that I dropped the submodules changes from that, because they're a pain to maintain, and seeing the overwhelming interest in getting this merged I'd prefer going with a mean-and-lean PR that with a 10-different-repos hydra monster.

Also note that I haven't really tested the rebase yet.

**Comment by tiennou** [comment]
Just merged in 1.6 branch. This is ready for review BTW.

**Comment by sigma001** [comment]
Is there a chance to get it in 1.6.1.x mainline?

**Comment by julienbourdeau** [comment]
Hi,

We won't change the password hashing in a patch version. This will appear in the next major version. I dunno which method will be implemented tho (this one or maybe another one).

**Comment by tiennou** [comment]
Rebased. Also #3183.

**Comment by julienbourdeau** [comment]
Hi,

Thank you very much for your involvement. We will use Sacha's method for PrestaShop 1.7 #3183 . When your other PR #3888 I assume you agree :)

**Pull request closed without merging**
