### PR TITLE
Enable auto_reload for .twig templates in dev env

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When you change the .twig template you don't see any changes unless you clear the cache. This option will reload such templates automatically.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | QA by a dev. Details below.
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop SA

How to test? Before and after PR:

1. Enable dev mode.
2. Edit `src/PrestaShopBundle/Resources/views/Admin/Common/Grid/grid.html.twig`
3. Check if you see your changes on, for instance, the category list in BO.

Before this PR, you won't see any changes, you have to clear the cache. After this change, you'll see changes every time you modify .twig files.

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by Hlavtox** [comment]
Note for QA - for some magical reason, it works on Windows even without this switch. :-)

**Review by nicosomb — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

it doesn't impact anything for regular users, I added "Waiting for dev" to have QA by a developer.

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

It's OK for us.
Thanks!

**Review by matks — APPROVED** [review]

**Comment by jolelievre** [comment]
That's weird, I never needed this option nor to remove the cache for this to work 🤔 Otherwise I would have gone mad 😅

**Comment by kpodemski** [comment]
@jolelievre hmm 🤔 Daniel told me the same thing but he use Windows. For me it's always cached and it was also reported by extension team from Corp, and once on project's Slack 🤔

**Comment by nicosomb** [comment]
By default, this setting is set to `%kernel.debug%`. Strange that it doesn't work for you @kpodemski

**Comment by kpodemski** [comment]
I can't find a way to reproduce it again. Closing this for now 🙄

**Pull request closed without merging**
