### PR TITLE
MO Add Hook for ps_sharebutton

### PR DESCRIPTION
**Pull request by ghost**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Add Hook displayShareButton |
| Type? | improvement |
| Category? | FO |

#### Important guidelines

I think is a better way for custom modules using button ( Send to a friend, print, wishlist ... )

### CODE REVIEW

**Comment by okom3pom** [comment]
Preston dont like space

**Comment by mickaelandrieu** [comment]
@okom3pom he's a kind of psychopath :(

**Comment by firstred** [comment]
Why is `$product` not passed to the new hook?

**Comment by aleeks** [comment]
Hello @okom3pom ,
We already noted this problem, it will be fixed for 1.7.1 because it introduces a new hook + a new template. In addition, there is a need to adapt the starterTheme and add sql.
See: 
https://github.com/PrestaShop/PrestaShop/pull/6880
https://github.com/PrestaShop/PrestaShop/pull/6712
https://github.com/PrestaShop/StarterTheme/pull/138
Thank for your contribution.
Regards

**Pull request closed without merging**
