### PR TITLE
Change links block style in carrier process

### LINKED ISSUE #9618: [BOOM-5785] FO - a link block is bad displayed in the hook after carrier
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5785).

- _**Reporter:**_ khouloud.belguith
- _**Created at:**_ Tue, 19 Jun 2018 18:18:26 +0200

<p>Hi,<br/>
Create a link block with the hook displayAfterCarrier<br/>
Navigate to FO<br/>
Create an order => In the process checkout => Step Shipping Method => the block is bad displayed.<br/>
 <span class="image-wrap" style=""><a id="68776_thumb" href="http://forge.prestashop.com/secure/attachment/68776/68776_image-2018-06-19-18-17-39-272.png" title="image-2018-06-19-18-17-39-272.png" file-preview-type="image" file-preview-id="68776" file-preview-title="image-2018-06-19-18-17-39-272.png"></a></span> </p>

<p>Best regards, Khouloud</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Link module markup is creating problems on carrier step of the checkout process
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9618
| How to test?  | Create a link block with the link ps_linklist module and attach it to the displayAfterCarrier hook, don't forget to add links to the block, then go to the checkout process like you'd buy something, the links should display properly

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16528)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
looks good to me 👍

**Comment by matthieu-rolland** [comment]
@NeOMakinG is this meant to go on develop ?

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @NeOMakinG :)

Could you resolve the conflict on the theme.css file ? Thanks !

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

**Pull request merged**
