### PR TITLE
Update npm lock files to fix assets build in the latest Alpine

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Current npm lock files are quite out of date and the `npm install` command does not finish on the latest Alpine.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | GH CI must pass
| Possible impacts? | It should not break anything if deps and their use is correct.

How this PR was created:
1. all 4 npm lock files were deleted
2. `npm i --package-lock-only` command was run in the directories with the lock files

```
./tools/assets/build.sh
>>> Building admin default theme...
/builds/mvorisek/prestashop_eshop/admin-dev/themes/default /builds/mvorisek/prestashop_eshop
> node-sass@4.13.1 install /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-sass
> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/linux_musl-x64-83_binding.node": 
HTTP error 404 Not Found
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 
      export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
      npm config set proxy http://example.com:8080
> node-sass@4.13.1 postinstall /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-sass
> node scripts/build.js
Building: /usr/bin/node /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:89:16
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:80:29)
gyp ERR! stack     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/which/which.js:89:16
gyp ERR! stack     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Linux 4.19.0-16-amd64
gyp ERR! command "/usr/bin/node" "/builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /builds/mvorisek/prestashop_eshop/admin-dev/themes/default/node_modules/node-sass
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN default@1.7.5 No description
npm WARN default@1.7.5 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-12T12_49_56_351Z-debug.log
make: *** [Makefile:7: assets] Error 1
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23984)

### CODE REVIEW

**Comment by mvorisek** [comment]
Please help with updating the CI issue:

```
   Create, read, update and delete Standard product in BO
    ✓ should login in BO
    ✓ should go to Products page
    ✓ should reset all filters
    ✓ should create Product
    1) should preview and check product in FO


  32 passing (4m)
  1 failing

  1) Create, read, update and delete Standard product in BO
       should preview and check product in FO:

      AssertionError: expected 0 to equal 19
      + expected - actual

      -0
      +19
      
      at Context.<anonymous> (campaigns/sanity/02_productsBO/02_CRUDStandardProductInBO.js:91:31)
```

**Comment by NeOMakinG** [comment]
Hey @mvorisek, don't you have any js errors or 500 requests? Looks strange that updating package-lock break CI

**Comment by mvorisek** [comment]
> 
> 
> Hey @mvorisek, don't you have any js errors or 500 requests? Looks strange that updating package-lock break CI

The deps were very outdated, thus I will say I expected this. `Sanity` tests are browser tests that uses js libs and when updated libs are different. Anyone with js knowledge, please help/advise what to fix. Thanks!

**Comment by PierreRambaud** [comment]
> > Hey @mvorisek, don't you have any js errors or 500 requests? Looks strange that updating package-lock break CI
> 
> The deps were very outdated, thus I will say I expected this. `Sanity` tests are browser tests that uses js libs and when updated libs are different. Anyone with js knowledge, please help/advise what to fix. Thanks!

If you don't have ks knowledge, please don't try to update these files.

**Comment by mvorisek** [comment]
> If you don't have ks knowledge, please don't try to update these files.

I admit I am not a js expert, but currently the locked versions can not be installed on Alpine because the deps are locked too low. I have enough knowledge, when when js, to know, the latest deps matching the deps rules are supposed to be compatible. Thus I updated the locks and fixed the js deps install. Now, probably one two small things, are incompatible, and I ask kindly for a help. @PierreRambaud , please be so kind and appreciate my contributions.

**Comment by PierreRambaud** [comment]
> > If you don't have ks knowledge, please don't try to update these files.
> 
> I admit I am not a js expert, but currently the locked versions can not be installed on Alpine because the deps are locked too low. I have enough knowledge, when when js, to know, the latest deps matching the deps rules are supposed to be compatible. Thus I updated the locks and fixed the js deps install. Now, probably one two small things, are incompatible, and I ask kindly for a help. @PierreRambaud , please be so kind and appreciate my contributions.

I'm able to install node deps on alpine, it's maybe because of nodejs requirements. You have to chose the correct version.
Updating all deps without checking it and giving more information about which dependencies are updated is not a good idea, it can break everything as you can see in UI tests.

**Comment by mvorisek** [comment]
> Updating all deps without checking it and giving more information about which dependencies are updated is not a good idea, it can break everything as you can see in UI tests.

It can, but it shoud not, as the deps should be declared the way only patch updates are allowed. Please check the changes.

> You have to chose the correct version.

I use the latest Alpine (which I can not change) and for this version (and locked deps), compiled packages (like saas compiler) are not available.

**Comment by PierreRambaud** [comment]
> I use the latest Alpine (which I can not change) and for this version (and locked deps), compiled packages (like saas compiler) are not available.

If you can't, again you will have a bad day, we can't update all our dependencies like that. I'm sorry we will not merge this pull request.

**Comment by mvorisek** [comment]
I can :), reopen, I will fix the dep at least for Alpine install.

**Comment by PierreRambaud** [comment]
> I can :), reopen, I will fix the dep at least for Alpine install.

If you want to update dependencies, please create a pull request with all updated versions:
* This package, from 1.0 to 1.10
The way you did is really bad, it breaks everything.


>I can :), reopen, I will fix the dep at least for Alpine install.

You just said, you can't change your alpine version. But the problem is maybe related to your npm & nodejs version not alpine.

**Comment by mvorisek** [comment]
PR for deps - ok

> You just said, you can't change your alpine version. But the problem is maybe related to your npm & nodejs version not alpine.

no, some deps requires precompiled binaries and old versions have no precompiled binaries for the latest Alpine

**Pull request closed without merging**
