### PR TITLE
CORE : Fix #PSCSX-6452 - Customer getLastCart return condition

### PR DESCRIPTION
**Pull request by fkwakkenbos**

### CODE REVIEW

**Comment by fkwakkenbos** [comment]
https://github.com/PrestaShop/PrestaShop/pull/3599#issuecomment-127664389

**Comment by sfroment42** [comment]
Hello,

Sorry but it's not possible to pass such change into a minor release cause module that use this function won't work anymore.
Please read this article: http://build.prestashop.com/news/a-more-semantic-versioning-scheme/ .

Best regards.

**Comment by fkwakkenbos** [comment]
Hi Sacha, 
Please help me.

There are two steps to take:
1) Leave the Customer getLastCart in place with a Depricated notice and reference to the new function.
2) Create a Pull Request into which branch? Please advice me on this step.

Thanks.

**Comment by jeromenadaud** [comment]
Hi, thank you for your contribution, please rename the function with getLastEmptyCart and create a new function with the old name call this new one. You must add Tools::displayAsDeprecated(), before calling the new one. And all this code on develop branch.

Best regards.

**Comment by jeromenadaud** [comment]
Clear ?

**Comment by fkwakkenbos** [comment]
Yes, very clear :+1: Thank you.

**Pull request closed without merging**
