### PR TITLE
[-] Core : fix "sh: 1: -t: not found"

### PR DESCRIPTION
**Pull request by ghost**
See http://axiac.ro/blog/2013/06/sh-1-t-not-found/

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

Please do not use 1.6 branches anymore. We only keep it until we sorted all the PR based on it.
I'll recommend you to read this amazing article we published:

Also about this bug, I have another fix I'd like to see.
The emails shouldn't be sent at all. Actually it hasn't been sent in years since we don't ask smtp config during the installation process.

- [ ] Remove this method https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/controllers/console/process.php#L305 and all occurrences
- [ ] Remove all email templates `install-dev/langs/*/mail_identifiers.txt`

If you want to do it, you are welcome to make a pull request on the `develop` branch !

**Comment by julienbourdeau** [comment]
Hi,
Let me know if you intend to do it, otherwise I'll add it to my todolist ^^
Thank you

**Comment by ZiZuu-store** [comment]
Hi,
sorry but I have no time right now
Il 14/ott/2015 18:38, "Julien Bourdeau" <notifications@github.com> ha
scritto:

**Comment by julienbourdeau** [comment]
No problem, thank you :)

**Pull request closed without merging**
