### PR TITLE
Fix(ci): template update package fix table

### LINKED ISSUE #32585: The templated used for "Updated PrestaShop Packages" PR is broken
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When Github Actions opens a new pull request to update PrestaShop packages, the template used to generate the description is broken. See https://github.com/PrestaShop/PrestaShop/pull/32580 for example. 

The file used by Github Actions to generate this content is here: https://github.com/PrestaShop/PrestaShop/blob/develop/.github/workflows/cron_update_modules/script.php

### Expected behavior

_No response_

### Steps to reproduce

Open https://github.com/PrestaShop/PrestaShop/pull/32580

### PrestaShop version(s) where the bug happened

NA

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

PrestaShop

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | This PR is fixing the table generated by the github action Cron Update PHP Modules.
| Type?             |  improvement 
| Category?         |  PM
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Open #32580 and check the new comment made by the bot
| Fixed ticket?     | Fixes #32585
| Related PRs       | N/A
| Sponsor company   | Prestashop

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @tleon

**Comment by nicosomb** [comment]
@tleon How to test: "Open https://github.com/PrestaShop/PrestaShop/pull/32580 and check the new comment made by the bot" but I don't see the new comment.

**Comment by tleon** [comment]
@nicosomb this PR has to be merged then you can test the workflow

**Comment by matks** [comment]
Worst case scenario if there is a problem in this PR: next PR opened by the bot will be useless. So I think we can merge & see what happens 😁

**Comment by kpodemski** [comment]
As I mentioned on the Issue, you probably have to [fix it on the `8.0.x` branch](https://github.com/PrestaShop/PrestaShop/blob/8.0.x/.github/workflows/cron_update_modules/script.php). Also, you can test it by re-running GH action.

**Pull request merged**
