### PR TITLE
1.7.5.x

### PR DESCRIPTION
**Pull request by SharmPRO**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.5.x
| Description?  | Logs email message body into database new field and add a modal popup from BO email log to view what was really sent out . Needs a new field in PREFIX_mail database table  ('message' text NOT NULL ) There is a piece of javascript into src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Email/index.html.twig I cannot figure out where it is better to place.
[Archive.zip](https://github.com/PrestaShop/PrestaShop/files/3158089/Archive.zip)
screenshot-localhost-2019 05 08-17-31-39
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13717)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Sorry @SharmPRO , this PR does not include any contribution from your account. A merge from 1.7.5.x to develop should be done manually in order to fix the existing conflicts.
I'm closing it as it can't be accepted as-is.

Kind regards

**Comment by SharmPRO** [comment]
Hi How can i submit an New Feature ( code included ) ?

**Comment by SharmPRO** [comment]
@PierreRambaud 
I did read https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#pull-requests-requirements and I did not find anything different from what i submitted already.
If you think the code I submitted is a possible valid contribution, please use it for any further development.

**Comment by PierreRambaud** [comment]
Hi,
You must create a pull request by using git.
https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#commits

Today you only select the `1.7.5.x` branch and try to merge it in `develop` branch without having a commit from you and without using a fork.

Kind Regards

**Pull request closed without merging**
