### PR TITLE
Add hook "actionUpdateQuantity" in product v2

### LINKED ISSUE #34358: New product page style - doesn't pass  $params['id_product_attribute'] to its hook when the product has combinations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I've found a big problem on the module Mail alerts v2.4.2
after many tests I can say that for products with combinations the module doesn't sent email to alert customers when they return available

instead for standard product without combinations the module sends email to registered and non-registered customers

only emaiils associated to standard products are sent

After some tests this problem is present only if the new product page style is active

bye

### Expected behavior

_No response_

### Steps to reproduce

1. go to a product with combinations
2. choose a combination and set it to 0
3. go to its product page, select the combination with quantity to zero
4. set your email e submit to get a reminder
5. return to the product configuration
6. set 10 to that combination
7. look if you get the email

you can repeat the same steps for a standard product and you will see that you get it, instead on the previous test not

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Add hook "actionUpdateQuantity" in product v2
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests are green, see #34358
| UI Tests          | https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6931769967
| Fixed issue or discussion?     | Fixes  #34358
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by Hlavtox — COMMENTED** [review]
Isn't this already handled in src\Core\Stock\StockManager.php and src\Adapter\Product\Stock\Update\ProductStockUpdater.php? 🤔🤔🤔

**Comment by M0rgan01** [comment]
> Isn't this already handled in src\Core\Stock\StockManager.php and src\Adapter\Product\Stock\Update\ProductStockUpdater.php? 

For a 'classic' update of a quantity, without combination, yes. for updating a quantity of a particular combination, no. 

In this case it is the CombinationStockUpdater which is called

@Hlavtox

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @M0rgan01

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @M0rgan01 ,

It is QA ✅ 

The Product available email is well sent for combination product.

**Pull request merged**
