### PR TITLE
[BO] : Unable to get correct class name on render list, due to this CSS is not applied

### LINKED ISSUE #28889: [BO]: Unable to get correct class name on render list, due to this CSS is not applied
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the render list, when we select any value from the list header correct class is not applied https://prnt.sc/42-UBY4mt8Fw

### Expected behavior

there's should be space between filter and center

### Steps to reproduce

In the render list, when we select any value from the list header correct class is not applied 

image

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In the render list, when we select any value from the list header correct class is not applied https://prnt.sc/42-UBY4mt8Fw
| Type?             | improvement Fixes
| Fixed ticket? 	| Fixes https://github.com/PrestaShop/PrestaShop/issues/28889
| Category?         | BO
| BC breaks?        | no
| How to test?      | Test it from Prestashop catalog price rule controller

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by ghost** [comment]
Can you create a issue about it and link it to this problem

**Comment by Amit-Kumar-Tiwari-Webkul** [comment]
> Can you create a issue about it and link it to this problem

@okom3pom , https://github.com/PrestaShop/PrestaShop/issues/28889 added

**Comment by ghost** [comment]
I think you fix it here https://github.com/PrestaShop/PrestaShop/pull/28872/files

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@Amit-Kumar-Tiwari-Webkul sorry for the delay, it seems that we missed this PR 🙏

**Comment by Progi1984** [comment]
@Amit-Kumar-Tiwari-Webkul Before sending it to QA, please fix conflicting files.

**Comment by NeOMakinG** [comment]
It has been fixed in the mean time, thanks for the contribution, and sorry for the miss!

**Pull request closed without merging**
