### PR TITLE
Ignore VSCode folder

### PR DESCRIPTION
**Pull request by tom-combet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Ignore VSCode folder which stores debug configuration, plugin settings and so on.
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | Tweak workspace-specific settings in VSCode
| Possible impacts? | N/A

### CODE REVIEW

**Comment by kpodemski** [comment]
Hey 👋 

Take a look:
https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

**Review by kpodemski — CHANGES_REQUESTED** [review]
It's better to use global gitignore for this 👍🏻

**Comment by tom-combet** [comment]
Ah okay sorry, but project gitignore should be reviewed entirely then. It has several entries about IDEs configuration, like Sublime Text or Eclipse.

**Comment by kpodemski** [comment]
Good point 👍🏻

**Comment by NeOMakinG** [comment]
> Ah okay sorry, but project gitignore should be reviewed entirely then. It has several entries about IDEs configuration, like Sublime Text or Eclipse.

Would you be interested in cleaning it?

**Comment by tom-combet** [comment]
> > Ah okay sorry, but project gitignore should be reviewed entirely then. It has several entries about IDEs configuration, like Sublime Text or Eclipse.
> 
> Would you be interested in cleaning it?

Yup, I'll try right now, in an other pull request. I close this one when it's done.

**Comment by NeOMakinG** [comment]
> > > Ah okay sorry, but project gitignore should be reviewed entirely then. It has several entries about IDEs configuration, like Sublime Text or Eclipse.
> > 
> > 
> > Would you be interested in cleaning it?
> 
> Yup, I'll try right now, in an other pull request. I close this one when it's done.

Feel free to ping me when it's ready :)

**Comment by tom-combet** [comment]
@NeOMakinG @kpodemski Done in https://github.com/PrestaShop/PrestaShop/pull/28623!

**Pull request closed without merging**
