### PR TITLE
Added reference parameter to OrderDetailController (1.6.1.x)

### PR DESCRIPTION
**Pull request by mcdado**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | This enables to load the order detail page directly with an order `reference` rather then an order id. If both parameters are passed, `id_order` has precedence, which is good for backwards compatibility. |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | example.com/order-detail?id_order={id_order}<br>example.com/order-detail?reference={order_reference} |

Cherry-picked 279dee43c59384ce3c479b9456c1c8c65d97f137 (develop)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!
I doubt it will make it into 1.6.1.x, though: this branch should not receive backward-incompatible features.

**Comment by kpodemski** [comment]
@xBorderie from what @mcdado describe in "Description" this change **is** backward compatible

**Comment by mcdado** [comment]
Indeed, it doesn't break compatibility. It behaves the same in the following behaviors:
- parameter `id_order` is present and valid
- parameter `id_order` is not present or is invalid

**Additionally**, what this enables is when:
- parameter `reference` is present and valid **and** no `id_order` is present, use `reference` to obtain the order id.
- parameter `reference` is not present **and** no `id_order` is present, fail like before.

**Comment by mcdado** [comment]
Renamed commits. Ready to go! 😃

**Comment by mcdado** [comment]
Bummer, but fair enough...

**Pull request closed without merging**
