### PR TITLE
BO - WS  Fix Array to string Conversion on OrderCarrier

### PR DESCRIPTION
**Pull request by Fransuisse**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | add idlang loading product because Link expect a string not a array
| Type?         | bug fix 
| Category?     | WS
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no ticket
| How to test?  | Php notice creating new OrderCarrier Object using Webservice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8310)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for your contribution!

Sadly, you now have malformed commits instead of just one commit:
* one merge commit -- which if merged can break the repository's history!
* the initial commit, which does not follow the [PS naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message). It should be "BO: Fix array to string conversion on OrderCarrier ".

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Review by mickaelandrieu — COMMENTED** [review]
I approve but this PR needs to be cleaned from the merge commit.

**Review by matthieu-rolland — COMMENTED** [review]
Thank you @Fransuisse , could you please rebase your PR?

**Comment by PierreRambaud** [comment]
Hi @Fransuisse ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
