### PR TITLE
Update composer.json requirements

### PR DESCRIPTION
**Pull request by gavinkalika**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Updating composer.json
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | composer install

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16714)

### CODE REVIEW

**Comment by gavinkalika** [comment]
example of file being used `TinyMceMaxLengthValidator`

**Comment by gavinkalika** [comment]
I am not sure if I chose the correct category

**Comment by PierreRambaud** [comment]
I did it for you

**Review by PierreRambaud — APPROVED** [review]

**Comment by gavinkalika** [comment]
thanks! I do not understand the categories. Could you link a description please?

Finally, thanks for the review, but when does it get merged?

**Comment by PierreRambaud** [comment]
https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#category
@gavinkalika When another developer will review and merge it ;)

**Comment by jolelievre** [comment]
Could you detail a bit in the description why you needed to add this dependency?
Also, should we update the composer.lock? @PierreRambaud wdyt?

**Comment by gavinkalika** [comment]
@jolelievre 

No you do not need to update the composer.lock.

It is a very small change that provides consistency to the dependency list.
This is not a novel idea previous presta shop developers have done it before.

**Comment by PierreRambaud** [comment]
My bad @jolelievre is right, the composer.lock file needs to be updated.

**Review by PierreRambaud — DISMISSED** [review]
composer.lock needs to be updated

**Comment by jolelievre** [comment]
Could you add `ext-json` since we're at it? I get tons of warning in PHPStorm because of this

**Comment by jolelievre** [comment]
And to be really consistent we should have the same as in the doc page I guess: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#extensions
(I can see that JSON extension is not present in the doc page by the way)

And I guess `ext-gd` and `ext-dom` (at least) are missing in the composer file

**Comment by jolelievre** [comment]
According to https://github.com/PrestaShop/php-ps-info/ we need these ones (the doc is SO outdated 😅):

Capture d’écran 2019-12-09 à 18 48 25

**Comment by PierreRambaud** [comment]
@jolelievre We should update php-ps-info, the composer files, and ConfigurationTest (but in a new PR)

**Comment by jolelievre** [comment]
Well php-ps-info needs to me modified in another PR of course But about composer and ConfigurationTest since they are related to the same issue why not updating them in the same PR?

**Comment by PierreRambaud** [comment]
@jolelievre You're right, I was talking about the php-ps-info :sweat_smile:

**Comment by gavinkalika** [comment]
To update lock I ran 

`composer update --lock --ignore-platform-reqs`

https://devhints.io/composer

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
No need QA. Thanks @gavinkalika

**Pull request merged**
