### PR TITLE
Fix: Clear cache module multishop

### LINKED ISSUE #35296: The button to install a module disappears or doesen´t update.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you install or uninstall a module in the context of all stores the install button disappears and you have to refresh the page to make it reappear, just like when you install and want to configure the module. When the context is in a single store this doesn't happen.

https://github.com/PrestaShop/PrestaShop/assets/153643894/ec757efd-47db-47c4-ae23-69952ae58ce3

### Expected behavior

-  When uninstalling a module, the install button appears without refreshing the page.
-  When installing a module, the button to configure or disable the module appears without refreshing the page.

### Steps to reproduce

1. Go to BackOffice
2. Go to Shop parameters -> general -> Enable Multistore
3. Go to Advanced Parameters -> Multistore -> add a new store to the default store.
4. Go to modules -> Module Manager
5. Ensure "All stores" is set as a context
6. Deactivate Best suppliers
7. The button disappears
8. Refresh the page
9. The disable/configure button reappears

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by pvujic**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fixes render update on module state change in a multistore
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Enable / Disable / Install / Uninstall Module with Multishop
| UI Tests          | https://github.com/pvujic/ga.tests.ui.pr/actions/runs/8249682778
| Fixed issue or discussion?     | Fixes #35296
| Related PRs       | None
| Sponsor company   | Habitium

### CODE REVIEW

**Comment by pvujic** [comment]
It affects BO but it's a change in the core.
It Fixes #35296 

Are UI tests needed?

Edit: Added UI run

**Comment by pvujic** [comment]
Simplified PR to not break existing logic.
UI tests are 🟢

Ready for review please

**Review by matthieu-rolland — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @pvujic ,

Thanks for the PR !

Tested with multistore, single store, native module, module with configuration option.

The Action button is always displayed.

https://github.com/PrestaShop/PrestaShop/assets/16019289/b0541cc1-eb3c-4c23-918a-a16fb23a188f

LGTM ✅

**Comment by FabienPapet** [comment]
Thank you @pvujic

**Pull request merged**
