### PR TITLE
Add help field when integer type is used to a form

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The help field is not displayed when integer is used to a form
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27761
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/27761
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27762)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @okom3pom,

I have an exception following these steps:
1. Enable B2B
2. Create a new customer & create an order
3. Go to BO > Orders > Orders > change the order status to accepted
4. Delete the customer created
5. Go to BO > Customers > Outstanding page
6. See error 

image

Thanks!

**Comment by ghost** [comment]
Hello [khouloudbelguith](https://github.com/khouloudbelguith)

You tried without my PR I don't think it's related.

Nice catch

Regard Thomas

**Comment by khouloudbelguith** [comment]
Hello @okom3pom,

Yes, I manage to reproduce the same exception with PS1780 & PS1783
I created an issue https://github.com/PrestaShop/PrestaShop/issues/27785

Thank you for your feedback!

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

It is ok :heavy_check_mark: 

I checked:
1. Add/Edit a customer from BO
image
2. Add a customer from BO > Add new order page
image
3. Add a customer via API
4. Create a customer & Guest from FO
5. I tried with multishop enabled
6. I tried to create a customer when B2B was disabled

Thanks!

**Review by khouloudbelguith — APPROVED** [review]
Hi @okom3pom,

It is ok :heavy_check_mark: 

I checked:
1. Add/Edit a customer from BO
image
2. Add a customer from BO > Add new order page
image
3. Add a customer via API
4. Create a customer & Guest from FO
5. I tried with multishop enabled
6. I tried to create a customer when B2B was disabled

Thanks!

**Review by tegbessou — APPROVED** [review]

**Comment by atomiix** [comment]
Thanks @okom3pom

**Pull request merged**
