### PR TITLE
[-] Class: Category / Add category as hook params when toggle status

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

thank you for your contribution, but this change is a minor improvement, please move this PR to develop branch.

Best regards

**Comment by gRoussac** [comment]
Hi,

Is it needed here too ?

https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Category.php#L1384 and https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCategoriesController.php#L841 ?

I find it very strange that this hook is either called in AdminCategoriesController::ajaxProcessUpdatePositions() and Category::updatePosition(). as ajaxProcessUpdatePositions is calling updatePosition. This implies the hook to be executed twice ?

Regards

**Comment by gRoussac** [comment]
:up: ?

**Comment by gRoussac** [comment]
Please ?

**Comment by gRoussac** [comment]
https://github.com/PrestaShop/PrestaShop/pull/4111

**Pull request closed without merging**
