### PR TITLE
Revert tcpdf to version 6.3.2

### LINKED ISSUE #27265: The Logo of PDFs are NOK with RTL lanaguage
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When downloading PDFs with RTL language => NOK
This issue occurs with an invoice & Delivery slip & the credit slip

**Credit slip**
image
**Delivery slip**
image
**invoice**
image

In the PS1778 => ok
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > Your profile & select the Arabic language
2. Go to BO > Order > Generate an invoice & download it
3. See an error
4. Generate a delivery slip & download it
5. See an error
6. Generate a credit slip & download it
7. See an error

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.2, 1.7.8.3build1

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Since #20716 the version of tcpdf used contains a [known bug in rtl](https://github.com/tecnickcom/TCPDF/issues/303). This PR fixes it by using the latest version available before the bug was introduced.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27265
| How to test?      | Please see #27265
| Possible impacts? | Maybe other PDF can be impacted

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27405)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by kpodemski** [comment]
There's one more big issue before 6.3.5 too:

https://github.com/PrestaShop/PrestaShop/issues/25801

**Comment by kpodemski** [comment]
also, if we update to the specific version, shouldn't we have a proper update of composer.json too? 🤔

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Could you please update the composer.json version to lock the version, I'm afraid it will be updated in a few weeks because of that.

**Comment by mvorisek** [comment]
the latest tcpdf `6.4.4` should have this issue fixed, so preferably upgrade, as the downgrade version has other issues unfixed

**Comment by atomiix** [comment]
@mvorisek unfortunately no, the issue is not solved in 6.4.4

**Comment by mvorisek** [comment]
> Could you please update the composer.json version to lock the version, I'm afraid it will be updated in a few weeks because of that.

test for it should be added to prevent such upgrades until fixed

**Comment by jolelievre** [comment]
The status of this downgrade is still unclear:
- seems like downgrading to 6.3.2 will fix issue #27265
- but upgrade to 6.3.5 was necessary to fix issue #25801

Does it mean we are blocked until tcpdf provides a more recent version that fixes everything? S until this bug is fixed? https://github.com/tecnickcom/TCPDF/issues/303

**Comment by jolelievre** [comment]
We need a decision on this topic by @PrestaShop/product-team 
What strategy do we use since both bugs can't be fixed for now, which one should be prioritized? Do we simply wait for a new release of the library?

**Review by matthieu-rolland — COMMENTED** [review]
LGTM for the downgrade, but a decision must still be taken...  I invoke the mighty @MatShir

**Comment by yanmakouf** [comment]
Original issue is closed. Can we close this PR @atomiix ^^ ?

**Comment by atomiix** [comment]
@yanmakouf yep, you're right!

**Pull request closed without merging**
