### PR TITLE
Fix gift display in cart

### LINKED ISSUE #9757: [BOOM-4701] Free GIFT is not displayed correctly on cart
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4701).

- _**Reporter:**_ tantan199
- _**Created at:**_ Fri, 26 Jan 2018 10:50:03 +0100

I added a gift to all products on my store, the problem is that the price of the gift is displayed on the shopping cart page, another problem is that the quantity of the gift is adjustable. See attached pictures.

Because the cart variable from the `controller/front/CartController.php` filed gets override by another cart variable from the assignGeneralPurposeVariables function in the `/classes/controller/ProductListingFrontController.php`

**Temporary solution is change this code**
`'cart' => $this->cart_presenter->present($this->context->cart),`

in the assignGeneralPurposeVariables function to 

`cart' => $this->cart_presenter->present($this->context->cart, $shouldSeparateGifts = true),`

The same problem also exist in the Shopping cart module.

---
When I apply a cart rule that offers an item, it should behave the same as in 1.6

- when adding a product that meets the conditions of a cart rule in the cart, do not take into account the gift price calculations. Currently, we add the product with its price and then apply a reduction of this amount.
- **The recycle bin to delete a gift does not work** (see #24831)
- display the product as a gift, remove the possibility of modifying the quantity and no longer display the price either in the basket and at the time of payment.

Capture du 2018-02-20 11-25-39

- If my cart rule offers an item & a reduction (in amount or %), a "Discount" field appears in the cart.
- This field must not include the amount of the product offered but only the reduction -> OK.
- Same for the orange line with the promo, it must not include the amount of the product offered but only the reduction -> NOK

Capture du 2018-04-17 15-48-03

Capture du 2018-04-17 15-47-50

- In the case that I buy a product that is offered, 2 lines must appear in the cart.
- The discount field should not include the amount of the product offered but only the discount -> NOK.
- Same for the orange line with the promo, it must not include the amount of the product offered but only the reduction -> NOK

Capture du 2018-04-17 16-12-58

Capture du 2018-04-17 15-55-47

We should also replace "Discount" by "Total vouchers" as in 1.6, it was clearer like this

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Enables proper displaying of gifts in shopping cart.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create a a cart rule that adds gift, go to FO and check it displays correctly in checkout. See this comment https://github.com/PrestaShop/PrestaShop/pull/34464#issuecomment-1805974045 for screenshots.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6746614646 https://github.com/nesrineabdmouleh/testing_pr/actions/runs/6849705106 ✅ 
| Fixed issue or discussion?     | Fixes #9757
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Comment by M0rgan01** [comment]
@Hlavtox A problem with UI tests. A retry on the failures to be sure?

**Comment by Hlavtox** [comment]
@PrestaShop/qa-automation Hi, could you check the tests? The fail doesn't seem related, but just to be sure.

**Review by LouisAUTHIE — DISMISSED** [review]

**Review by kpodemski — COMMENTED** [review]
I'm pretty sure it's not that simple and there was something that forced us to remove this parameter.

**Comment by Hlavtox** [comment]
@kpodemski I have enabled gifts with home-made-fixed calculation on 1.7.6 for years now, works perfectly. And it works out of the box on 8.1.2. :-)

**Review by matthieu-rolland — COMMENTED** [review]
@Hlavtox thank you for the PR 👍 

Could you please explain why it is necessary to set the gift as "separate gift" to fix this bug ? I'm not sure I understand

**Comment by Hlavtox** [comment]
@matthieu-rolland

Imagine you order `Product A`, `Product B` and you get another `Product B` as a gift.

**Right now, it's displayed like a normal product. And if you remove the `Product B` you added, you will still see it as normal product. Removing doesn't work, no "gift" message.**

mug

**But if you present the cart with gifts, everything works fine. This option was disabled due to bad calculations, but they are now fixed.**

ok

**Review by matthieu-rolland — DISMISSED** [review]
I'm sold 👍

**Comment by Hlavtox** [comment]
@PrestaShop/ui-tests-maintainers One test fails, but everything works normally and the gifts work in the backoffice perfectly, not sure what is happening there. :-)

**Comment by nesrineabdmouleh** [comment]
Hello @Hlavtox,
UI tests are :heavy_check_mark: https://github.com/nesrineabdmouleh/testing_pr/actions/runs/6849705106

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

It does not work as expected :/

I have created 2 Cart rules.
1. Gift - gives a free Customizable Mug from 120 euros in cart
2. Cadeau - gives a free Hummingbird notebook from 30 euros in cart (with discount code)

I have added any product to my cart (less than 30 euros in cart), I had a free custom mug + a free Hummingbird notebook when I added my discount code. :x:

I added a few Custom Mug in my cart. They were considered as free gift :x:

I have deleted all the products that were not a gift from my cart. My cart is now full of gifts. :x:

The cart summary is wrong. The amount of Discount is superior to the Discount total. :x:

Screenshot 2023-11-14 at 14 27 03

Also, I can't delete some of my product from my cart :x:

https://github.com/PrestaShop/PrestaShop/assets/16019289/6a133d6b-eda4-47b8-9096-8ca06554699e

Could you check ? ^^
Thanks!

**Comment by Hlavtox** [comment]
Nothing better than digging through a code where there there are both cart, customizations and gift combined. :D But, fixed everything. Added a some comments so the next person have to think less. :-)

And it's somehow possible to add a product with required customizations to cart. 🤷Blocked here - https://github.com/PrestaShop/PrestaShop/pull/34562.

I tried multiple customizations.
I tried multiple cart rules adding the same product.
I tried multiple gift products.
I tried adding and removing when there are gift, noncustomized and customized.
Should work!!!

Snímek obrazovky 2023-11-14 153546

**Review by M0rgan01 — DISMISSED** [review]
thanks for the comments

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Thanks for the update !!

I have tested all the previous things I checked, as well as all the things you said here https://github.com/PrestaShop/PrestaShop/pull/34464#issuecomment-1810431894.

- tested multiple cart rules with and without code ✅ 
- multiple gifts in cart ✅ 
- remove all products from cart -> gifts were deleted as well ✅ 
- cart summary is correct ✅ 
- tested multiple cart rules with and without minimum purchase amount :x:

I have found just one thing that seems related to your PR. I could not reproduce it without your PR.
Minimum amount in cart to have a free gift is not correct. With 120 euros of products in my cart I should benefit the gift. But here I need to have at least 130 euros in my cart.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e6b173da-1bf6-4346-8395-7aaa8e2b0d76

Config of the cart rule :
Screenshot 2023-11-20 at 11 55 17

Without the PR :

https://github.com/PrestaShop/PrestaShop/assets/16019289/876d1d27-88c4-431f-87a9-51b770d83282

Could you check ? ^^

**Review by boherm — DISMISSED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by LouisAUTHIE — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
@Hlavtox ,

The bug mentioned previously has been fixed !

Retested the whole PR, no issue found !

It is QA ✅ 
Thanks !

**Comment by Hlavtox** [comment]
Thanks @florine2623 🥇

**Comment by mrabsinthe** [comment]
@Hlavtox would it be possible to delete the gift even if I'm in title to receive it? And if the gift has attributes (colors or size for example), can I change it from the cart?

**Comment by Hlavtox** [comment]
@mrabsinthe If the cart rule is deletable, you can delete the gift. If it's automatic, you can't, like any other cart rule.

If the gift has attributes, they are defined in the cart rule.

Nothing changed in the logic, it just shows "Gift" instead of a trash icon that doesn't work. That's all. :-)

**Comment by mrabsinthe** [comment]
pity, it would be awesome if all that work

**Pull request merged**
