### PR TITLE
Duplicated join in query.

### LINKED ISSUE #29339: Duplicated join in Hook.php leads to inefficient query
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Quite a slow query is in `classes/Hook.php:1202` 

Immagine 2022-08-15 154249

In the following query, `ps_module_shop` is joined twice, but only one join is needed.
``` 
SELECT SQL_NO_CACHE h.`name` as hook, m.`id_module`, h.`id_hook`, m.`name` as module
FROM `ps_module` m
INNER JOIN ps_module_shop module_shop
ON (module_shop.id_module = m.id_module AND module_shop.id_shop = 2 AND module_shop.enable_device & 1)
INNER JOIN `ps_module_shop` `ms` ON ms.`id_module` = m.`id_module`
INNER JOIN `ps_hook_module` `hm` ON hm.`id_module` = m.`id_module`
INNER JOIN `ps_hook` `h` ON hm.`id_hook` = h.`id_hook`
LEFT JOIN `ps_module_group` `mg` ON mg.`id_module` = m.`id_module`
WHERE (h.`name` != "paymentOptions") AND (hm.`id_shop` = 2) AND (mg.id_shop = 2 AND  mg.`id_group` IN (3))
GROUP BY hm.id_hook, hm.id_module
ORDER BY hm.`position`
```

### Expected behavior

I expect queries to be optimized. 

Removing the extraneous join, the query is faster (half the time, only 2 ms, that is not much, but it is a tiny improvement).
Immagine 2022-08-15 155107

### Steps to reproduce

1. Enable Debug profiler
2. Look for the query above on any page of the FO
3. Notice, that the table `ps_module_shop` is joined twice, and
    a. the extraneous (second) join is less restrictive than the first, but rows joined by the second query are a strict superset of those joined by the first query
    b. the alias `ms` is never used, neither in selected field, nor in conditions, nor elsewhere

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes a duplicated inner join in a query
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29339.
| Related PRs       | 
| How to test?      | Follow the instructions given in #29339
| Possible impacts? | The query result is guaranteed to stay the same

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@lmeyer1 Apologies for late review. Summer happened and a lot of people took some time off.

@PrestaShop/qa-team can this PR be tested by a developer?

**Comment by sLorenzini** [comment]
> @lmeyer1 Apologies for late review. Summer happened and a lot of people took some time off.
> 
> @PrestaShop/qa-team can this PR be tested by a developer?

hello,

@lmeyer1 thank you  for this PR 🚀 .

@matks, this PR is not testable bay a dev or QA because the [issue](https://github.com/PrestaShop/PrestaShop/issues/29339#issuecomment-1216236652) was not reproduced. 

Someone of the @PrestaShop/prestashop-maintainers could check this issue please 🙏?

I put the PR as blocked until the issue is validated

Thank you

**Comment by lmeyer1** [comment]
@sLorenzini 
I don't quite understand what `not reproduced` means here. I'm sure that the query will show up in debug profiler as explained. That fact that the query has a duplicate join may not be trivial, but someone who is fluent in SQL will be able to confirm.

**Comment by matks** [comment]
> @matks, this PR is not testable bay a dev or QA because the [issue](https://github.com/PrestaShop/PrestaShop/issues/29339#issuecomment-1216236652) was not reproduced.

@sLorenzini The problem is hidden deep inside the SQL query. I think maybe we could assign the QA validation to a developer to test this PR as he/she would be able to verify the SQL query before/after (which is out of the scope of QA analysts I think). The issue is not reproduced because it's "waiting for dev", I think we could do both issue verification by dev + PR verification by dev at the same time.

**Comment by Robin-Fischer-PS** [comment]
Hi there @lmeyer1 @matks @sLorenzini :)

To clarify a bit what we mean by "not reproduced" in QA, it's not that your issue does not exist, it's just that, while QA Analysts usually have some technical background, we are not experienced developers on PrestaShop, so we just need someone from the Maintainers to reproduce the issue (to check if it's really an issue, and to verify if the issue is not more serious than we think).

Once it's done, the Maintainer will test your PR (because the how to test is also technical), maybe launch automated tests and it will be OK :)

**Comment by jf-viguier** [comment]
Nice PR thanks

**Comment by jf-viguier** [comment]
IMO, the how to test should check if the returned rows are the same with or without the PR in a mono and multi shop context.
Thanks for the PR @lmeyer1

**Comment by eternoendless** [comment]
This PR is outdated vs the changes from #29469

From the looks of the change, it would make more sense to add the shop association once and only add the `enable_device` constraint as needed:

```php
        // SQL Request
        $sql = new DbQuery();
        $sql->select('h.`name` as hook, m.`id_module`, h.`id_hook`, m.`name` as module');
        $sql->from('module', 'm');
        $sql->innerJoin('hook_module', 'hm', 'hm.`id_module` = m.`id_module`');
        $sql->innerJoin('hook', 'h', 'hm.`id_hook` = h.`id_hook`');
        
        $isDeviceSensitive = !in_array($hookName, ['displayBackOfficeHeader', 'displayAdminLogin']);
        
        $sql->join(
            Shop::addSqlAssociation(
                'module',
                'm',
                true,
                $isDeviceSensitive ? ('module_shop.enable_device & ' . (int) Context::getContext()->getDevice()) : ''
            )
        );
```

**Comment by lmeyer1** [comment]
@eternoendless This PR is now ready on my side, following your comment. Thanks.

**Review by kpodemski — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by kpodemski** [comment]
Tested, and it's all good:

Before: https://capture.dropbox.com/pcteQKfH3t2U1en9
After: https://capture.dropbox.com/UOfKzaUmeGguwKKX

All modules are still loaded correctly.

**Comment by kpodemski** [comment]
Thank you, @lmeyer1

**Pull request merged**
