### PR TITLE
[+] CORE: Add TLS support

### PR DESCRIPTION
**Pull request by WassimAttar**
When using smtp.gmail.com and SSL/465 connexion parameters, mails are sent through gmail.
But, when TLS/587 connexion parameters are used this error is raised :
The SMTP connection failed to start [tls://smtp.gmail.com:587]: fsockopen returned Error Number 0 and Error String ''
To fix this TLS issue, an upgrade to swiftmailer 5.x is necessary.
This Mail.php file change upgrades the code from swiftmailer 3.3.2 to 5.x
It has been tested on smtp.gmail.com SSL/465 and TLS/587 and mails are sent.

### CODE REVIEW

**Comment by WassimAttar** [comment]
To test Mail.php swiftmailer must be upgrated to 5.x
Delete the /tools/swift/* files and put theses files
https://github.com/swiftmailer/swiftmailer/tree/5.x/lib/

**Comment by inetbiz** [comment]
Actually, @WassimAttar port 465 has been deprecated since 1997. https://en.wikipedia.org/wiki/SMTPS Use 25 or 587 and wow thanks for that PR. I :+1:  because I've seen the same issue using the correct port assignments.

**Comment by WassimAttar** [comment]
SSL/465 is may be deprecated but we don't decide which protocol/port the mail provider offers.
For the tests, what i know is that smtp.gmail.com works with both SSL/465 and TLS/587.
I have other providers who only works with TLS/587. That's why i wrote this patch and made a pull request to share it.
I hope that my contribution will be merged.

**Comment by inetbiz** [comment]
I thank you for that! 465 port assignment will also be going away for Google as they will not support SSL V2/3 any longer after June 2016

**Comment by WassimAttar** [comment]
Yes.
That's why TLS must work out of the box.

**Comment by xBorderie** [comment]
Hey @WassimAttar , thank you for your contribution!
Could amend your commit message in order to follow those guidelines: http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message?
You can use `git --amend` to change the commit, then update your PR. See here: http://schacon.github.io/history.html
Thank you!

**Comment by WassimAttar** [comment]
Done.
Please confirm that the commit message is fine.

**Comment by xBorderie** [comment]
Great! That being said, only now do I notice that your PR was made on the `1.6.1.x` -- which does not accept new features, only bugfix. This PR might therefore be closed.
Luckily, I see that you remade your change on the `develop` branch (for PrestaShop 1.7). The PR is faulty (old codebase), but it has a good chance to land into 1.7. Can you update that PR? Thank you very much!

**Comment by WassimAttar** [comment]
Done on the develop 1.7 branch.

**Comment by WassimAttar** [comment]
I can create a new clean PR on the develop branch with the correct commit message and the latest swiftmailer code.
You'll only have to merge.
Tell me if it's easier for you.

**Comment by xBorderie** [comment]
Yes, I see that you have closed #4557 for that reason. Don't hesitate to create a new PR with a commit made from an up-to-date `develop` branch!

Once you have done it, I suggest that you close this PR (#4546).

Thank you!

**Comment by WassimAttar** [comment]
Ok, i'll create a new clean PR and close this one.
But before, do you want me to add the latest swiftmailer code or you'll handle it ?

**Comment by xBorderie** [comment]
Maybe wait that the first PR is merged, then suggest an update with the latest SwiftMailer? Don't start big projects right now :)

**Comment by WassimAttar** [comment]
New PR done.
I close this one.

**Comment by xBorderie** [comment]
I see, with #4559. Great, thanks!
I'll let the developers review your code and handle the rest.
Cheers!

**Comment by xBorderie** [comment]
Please, could you copy/paste all your indications from this PR to the new PR's description textarea, so that developers do not have to look for them? Thank you!

**Comment by xBorderie** [comment]
:+1:

**Comment by therampagerado** [comment]
This PR is VITAL for 1.6.1.5 please can you merge it!

We can't use SMTP function in 1.6.1.4 if this is not applied.

Thank you WassimAttar, for your contribution!

**Pull request closed without merging**
