### PR TITLE
Remove hook XML files from install data

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove files that do not seem to bring value and are manually updated
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no (I hope)
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/11033
| How to test?  | Nothing should change

I could not find a reason why to keep these 2 files so I suggest we delete them.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11187)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
> I could not find a reason why to keep these 2 files so I suggest we delete them.

Are you sure? I have explained the reasons like 3 times already :unamused: ... you need to ensure that all hooks - even the ones *never* called by modules - will still be displayed in the debug toolbar.

hooks_debugger

It's one of the major features for the Module developers because without it they have no information on which hooks are dispatched in each page (and good luck to find them without var_dumping HookCore class).

Removing the xml file will make the "not Called Hooks" tab empty, so people will think there is no other available hooks: so removing the xml file introduces a regression and made the development of modules painful.

The only solution to not depends on Hooks table is to change the implementation of
`Hook::getHookModuleExecList` (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Hook.php#L771) what we can't do before the next major (Front Office also relies on it).

In fact, we need to keep it and complete it, it's quite the opposite :rofl:

**Comment by matks** [comment]
Could we rather delete it and **generate it** ? I do not trust us humans to update this file carefully without errors.
Some trick like the TranslationTools: parse the code, find the hooks exec and dispatch and register them.

**Comment by mickaelandrieu** [comment]
> Could we rather delete it and generate it?

I have no idea how, but yes if we could do it before each release it would be awesome! Of course, I don't say that maintaining this file by hand is right, sorry if I was a little bit harsh on it :)

**Comment by Quetzacoalt91** [comment]
@matks, I'm closing this PR until we find another solution. Only deleting these files will only bring compatibility issues with the modules using hook aliases.

Regards

**Pull request closed without merging**
