### PR TITLE
Fix inactive request in HookEvent

### PR DESCRIPTION
**Pull request by mwienk**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix inactive scope for request in HookEvent
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | <p>http://forge.prestashop.com/browse/BOOM-1992<br/>http://forge.prestashop.com/browse/BOOM-2579</p>
| How to test?  | Create BO order with code.

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Hello @mwienk,

We would like to include your fix in the next version 1.7.1.0. Would you mind updating your PR to use the branch `1.7.1.x` as base instead of develop?

**Comment by mwienk** [comment]
Hi @Quetzacoalt91,

It seems you already changed the base branch, do I need to do anything else?

**Comment by Quetzacoalt91** [comment]
Yes, I want you to make your branch starting from 1.7.1.X, on which you apply your commit.

**Comment by mwienk** [comment]
Opened in https://github.com/PrestaShop/PrestaShop/pull/7665

**Pull request closed without merging**
