### PR TITLE
Update Link.php to fix an issue with invalid URLs

### LINKED ISSUE #33258: Issue with invalid URLs inside products and categories
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

 Inside the method `getLanguageLink` the check for the `$params` is always done wrong as the key is present when a page is not found but the actual value is `false` on the key corresponding to the ID.
That makes the application raise a fatal later on when it search for the link:
`Invalid product vars at line 174 in file classes/Link.php`
`category vars at line 405 in file classes/Link.php

### Expected behavior

The page shouldn't raise a 500 error and return a 404.

### Steps to reproduce

1. The easiest way I found to test this is to install [`SEO Friendly URL Module`](https://github.com/softwaremistri/smseourl) which gonna remove the behavior on top of that method to redirect the user and makes it less complex to reproduce the issue.
2. Then update the URLs patterns to remove the ID (that remove the layer on top of the bug. However the bug is not linked directly to it)
3. Then you can enter any wrong URL in category or product and the problem gonna show up.

### PrestaShop version(s) where the bug happened

1.7.8.9

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

MBS Design

### PR DESCRIPTION
**Pull request by CrochetFeve0251**
| Questions         | Answers|
| ----------------- | -------------------------------------------------------|
| Branch?           | develop
| Description?      | Inside the method `getLanguageLink` the check for the `$params` is always done wrong as the key is present when a page is not found but the actual value is `false` on the key corresponding to the ID.<br>That makes the application raise a fatal later on when it search for the link:<br> `Invalid product vars at line 174 in file classes/Link.php`<br> `category vars at line 405 in file classes/Link.php`|
| Type?             | bug fix|
| Category?         | FO|
| BC breaks?        | no|
| Deprecations?     | no|
| How to test?      | The easiest way I found to test this is to install [`SEO Friendly URL Module](https://github.com/softwaremistri/smseourl)` which gonna remove the behavior on top of that method to redirect the user and makes it complex to reproduce the issue.<br>Then you can enter any wrong URL in category or product and problem gonna show up.|
| Fixed ticket?     | Fixes #33258, #33306|
| Sponsor company   | MBS Design|

### CODE REVIEW

**Comment by kpodemski** [comment]
Hi @CrochetFeve0251 

You will have to help us reproduce the issue first.

**Comment by CrochetFeve0251** [comment]
> Hi @CrochetFeve0251
> 
> You will have to help us reproduce the issue first.

@kpodemski I added a link to a issue with the same problem which they succeed to reproduce it without the module: #33306

**Comment by M0rgan01** [comment]
You have to change the destination branch to 1.7.8.x

**Comment by kpodemski** [comment]
@M0rgan01 why?😁 we only support  bugfixes for 8.1 and 9.0

**Review by Hlavtox — CHANGES_REQUESTED** [review]
This is not a correct change.

This method should return a language link for an existing object for hreflang purposes.

If you add this check, you may be fix an error, but get a nonsense link. What is a URL to product controller without a product? It doesn't exist, doesn't have any logic attached.

**Comment by M0rgan01** [comment]
Ah yes sorry! It should be for 8.1 :)

**Comment by CrochetFeve0251** [comment]
> This is not a correct change.
> 
> This method should return a language link for an existing object for hreflang purposes.
> 
> If you add this check, you may be fix an error, but get a nonsense link. What is a URL to product controller without a product? It doesn't exist, doesn't have any logic attached.

Do we have a controller we could set when we face that error or should we empty the controller on that case?

Currently with that fix we are redirect to the 404 page.

**Comment by CrochetFeve0251** [comment]
> Ah yes sorry! It should be for 8.1 :)

I changed the PR to  another base. However looks like it added some content maybe I should open a new one based on the right branch?

**Review by matks — COMMENTED** [review]
I think indeed the easiest way will be
- create a new branch from your fork, using target branch as base
- cherry-pick your commit 😉

**Comment by kpodemski** [comment]
I agree with @Hlavtox that this doesn't seem like a valid fix. This validation should be done earlier.

**Comment by kpodemski** [comment]
@Hlavtox although I recall some modules which have problem with this, for example they have a menu, links to categories, category gets deleted and ID is false at some point, this could prevent from these issues to happen **and** the change is quite safe since it redirects to 404

**Comment by CrochetFeve0251** [comment]
> I think indeed the easiest way will be
> 
>     * create a new branch from your fork, using target branch as base
> 
>     * cherry-pick your commit wink

I created a new [PR](https://github.com/PrestaShop/PrestaShop/pull/33342) based on the 8.1.

**Pull request closed without merging**
