### PR TITLE
Remove expired and disabled cart rules

### LINKED ISSUE #19393: CART RULE - cart rule is applied even when you disabled
#### Describe the bug

If a Cart rule for cheapest product is created but not enabled and if a second cart rule is created and enabled the first one is displayed and enabled in the FO

#### Expected behavior

The cart rule must not be applied and displayed if not enabled

#### Steps to Reproduce

- [ ] Test1
1. Go to the BO => Catalog => Discounts => Create a new cart rule with the following parameters (see the attached screenshots below)
2. Enable the previously created cart rules
3. Go to the FO => Add to the cart demo_11 & demo_6
4. Go to the cart page => The cart rule is correctly applied to the cheapest product ( demo_11 )
5. Go Back to the BO => Catalog => Discounts => and disable the cart rule 
6. Go to the FO again and check the cart => the cart rule is applied and displayed => NOK

> ~7. Go Back to the BO => Catalog => Discounts => Create a new cart rule the parameters of this cart rule don't really matter just create a cart rule with a generated code and a amount of 10 % it's enough~
> ~8.Enable this cart rule~
> ~9. Go to the FO again and check the cart => the newly created cart rule is available~
> ~10. See error => the first created cart rule is applied and displayed even if not enabled in BO~

- [ ] Test2
>Edit by @hibatallahAouadni 

1. FO, add products to cart and apply a voucher
2. BO, edit the voucher date (valid to) to be expired
3. FO, refresh the page the voucher still applied => NOK
4. Delete the voucher, then you will see you can't apply it again => OK

- [ ] Test3
> Edited by Khouloud

Other steps to reproduce the same issue as described here https://github.com/PrestaShop/PrestaShop/issues/27650

**Preparation**
1. Create customer group ID 4.
2. Create a new customer, put him to group 4, set default group 4.
3. Create a cart rule that will apply automatically, cart rule will give a free gift, set group restriction only to 1, 2, 3.

**Actual bug**
1. Log in as the customer you created.
2. Add something to cart and go to cart.
3. Now, go edit that customer in BO, tick that he belongs to group 1.
4. Go back to cart, hit F5. Cart rule will be applied and gift added to cart.
5. Go back to edit customer, un-tick group 1, save.
6. Go back to cart, hit F5. Gift is not removed from cart.
_(7. It's removed when you +- the quantity on your product.)_
**Screen record**
https://drive.google.com/file/d/1SgVUMepMz-XsaUKgafB7aVv9LGnlAYLO/view

**Screenshots**

**Cart rule's parameters**
capture d'écran_35
capture d'écran_36
capture d'écran_37

**The cart rule is disabled in BO**
capture d'écran_43

**But applied and displayed in FO**
capture d'écran_44

#### Additional information

* PrestaShop version:1.7.7.x and 1.7.6.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by idnovate**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Upgrade cart rules which are deleted, expired or disabled when presenting the cart
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19393
| How to test?      | Check ticket #19393

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Hi @idnovate, this is not the right place for such call.👍

**Comment by idnovate** [comment]
> Hi @idnovate, this is not the right place for such call.👍

Which would be the correct place?

**Comment by idnovate** [comment]
Ping @Hlavtox

**Comment by Hlavtox** [comment]
@idnovate I am not sure, but CartPresenter responsibility should be only to "make cart human readable". If we are doing any changes in the cart, it should be done somewhere in `Cart` or `CartController` class I think. Ping @kpodemski

**Comment by idnovate** [comment]
This is the trace:

```
#0 ...\src\Adapter\Presenter\Cart\CartPresenter.php(444): PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter->getTemplateVarVouchers(Object(Cart))
#1 ...\classes\controller\FrontController.php(487): PrestaShop\PrestaShop\Adapter\Presenter\Cart\CartPresenter->present(Object(Cart))
#2 ...\classes\controller\FrontController.php(554): FrontControllerCore->assignGeneralPurposeVariables()
#3 ...\controllers\front\IndexController.php(38): FrontControllerCore->initContent()
#4 ...\classes\controller\Controller.php(319): IndexControllerCore->initContent()
#5 ...\classes\Dispatcher.php(503): ControllerCore->run()
#6 ...\index.php(28): DispatcherCore->dispatch()
#7 {main}
```

Maybe it's better to add it here https://github.com/PrestaShop/PrestaShop/blob/bdc046426ccef35d52e706cb5856541926fefb70/classes/controller/FrontController.php#L485?

**Comment by FabienPapet** [comment]
Removing expired and disabled cart rules is not the responsibility of any of the cart controller, front controller, presenters, etc.

If you want to implement such a feature, you can either: 

- Create a dedicated action in the admin with a button for example, which will remove old data.
- If you want this to be automated, like a cron, create a Symfony command that you'll execute.
.

**Comment by idnovate** [comment]
> Removing expired and disabled cart rules is not the responsibility of any of the cart controller, front controller, presenters, etc.
> 
> If you want to implement such a feature, you can either:
> 
> * Create a dedicated action in the admin with a button for example, which will remove old data.
> * If you want this to be automated, like a cron, create a Symfony command that you'll execute.
>   .

I think that you didn't get the point 😕 The problem is that an expired cart rule is applied in the cart after the date limit. This must be checked by a controller.

**Comment by kpodemski** [comment]
I'll get back to you next week to solve this issue once and for all. I agree with @Hlavtox that it's not a presenter's responsibility to handle such a thing. I'll try to think of a better solution to this.

**Comment by FabienPapet** [comment]
@kpodemski i'm alos interested about how you'd handle this. There's a big chance I'll work on cart rules in a few months.

**Comment by kpodemski** [comment]
Hi @idnovate 

Could you test the solution I suggested? https://github.com/PrestaShop/PrestaShop/pull/30905

The one you proposed didn't remove vouchers when I tested it.

**Comment by idnovate** [comment]
> Hi @idnovate
> 
> Could you test the solution I suggested? #30905
> 
> The one you proposed didn't remove vouchers when I tested it.

Tested and worked correctly.

There is a BC issue because of the new parameter in the function `autoRemoveFromCart` if it's overridden 👌

**Comment by kpodemski** [comment]
@idnovate, if it's overridden than indeed, there will be a warning about the wrong declaration of the method, I don't think it should be something blocking for having it in 8.1 tho :)

**Comment by idnovate** [comment]
> @idnovate, if it's overridden than indeed, there will be a warning about the wrong declaration of the method

Sure, it does.

> I don't think it should be something blocking for having it in 8.1 tho :)

But it will require to developers to release a new module version and uninstall/install the override (and fixing the merging problems) :grimacing:

**Comment by kpodemski** [comment]
@idnovate 

> But it will require to developers to release a new module version and uninstall/install the override (and fixing the merging problems) 😬

it will, but it solves quite a major issue and it doesn't break BC Break promise :)

**Comment by kpodemski** [comment]
Closing in favor of https://github.com/PrestaShop/PrestaShop/pull/30905

**Pull request closed without merging**
