### PR TITLE
Catalog rules: don't display the shop column if there is only one shop

### LINKED ISSUE #9862: [BOOM-4014] Don't display the shop column if there is only one shop
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4014).

- _**Reporter:**_ salma.moakhar
- _**Created at:**_ Thu, 12 Oct 2017 17:47:10 +0200

<p>I will try to describe the problem clearly. Situation, i install the shop with name: "TestSHOP", later i rename it to "AnySHOP". This work fine until i have created "Price rule for catalog" it shows "TestSHOP" in the SHOP column.<br/>
I think this is the "internal name" for multistore purpose but when multistore is off the value cannot be changed in administration.<br/>
Steps to reproduce the issue :<br/>
1- In the installation shop name : "Shop_name_first"<br/>
2- Multistore is disabled <br/>
3- Rename the Sop name to "Shop_name_second" (Shop Parameters => Contact => Tab "Stores")<br/>
3- Add new catalog price rule<br/>
4- Save<br/>
5- The "CATALOG PRICE RULES" in the Shop column shows the first name of the shop "Shop_name_first" </p>

## SPECS
The column shop shouldn't be displayed if there is only one shop

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The fix is easy, but I decided to introduce a new helper, it might be useful for other developers
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9862.
| Related PRs       | n/a
| How to test?      | See if you still have a Shop name column without multi-store in use
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @kpodemski ,

Multistore ON, I do have the column ✔️ 
Multistore OFF, the column is not displayed ✔️ 

But as it is said in the issue, the name of the shop is not correct when it has been edited.

> 5- The "CATALOG PRICE RULES" in the Shop column shows the first name of the shop "Shop_name_first"

In BO > Catalog > Discount > Catalog Price Rules :

Screenshot 2022-05-02 at 12 00 03

In BO > Shop Parameters > Contacts > Stores :

Screenshot 2022-05-02 at 12 02 56

Could you check ?
Thanks!

**Comment by kpodemski** [comment]
Hello @florine2623 

Name from the `BO > Shop Parameters > Contacts > Stores` refers to something else than a "Shop name" from the multi-store context. It's about the mapping between a cart rule and the shop instance. We don't use the name from the configuration page for this :)

**Review by florine2623 — APPROVED** [review]
@kpodemski ,

Ok, I have modified the shop name in the multistore section.

So to recap : 
- With Multistore ON, 1 shop : column is not displayed
- With multistore ON, more than 1 shop : column is displayed
- With Multistore OFF : column is not displayed

For me it is QA ✅ 
Thanks !

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623

**Pull request merged**
