### PR TITLE
Update products.js to allow accessories having `|` in the name

### PR DESCRIPTION
**Pull request by makoso**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Hi, this may be available in the default Presciano ? It is available as a general array of strings are exploding? Because now I wasted some time to find a solution to this problem that should not exist :/ |
| Type? | bug fix |
| Category? | BO |
| BC breaks | no |
| Deprecations | no |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

I re-added the table and tried to fill it it correctly.

Also, could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by vincentbz** [comment]
Hi,

thanks for your contribution.
Could you explain what the problem was before your PR and what it fixes please ?
And what is a presciano please? :)

Thanks

**Comment by makoso** [comment]
Hello in response to a question .

Before editing the code could not be added to the product links(accessories) that contained in its name "|" (&#124;) , I think that the references could not be found.

Theoretically, it may seem that everything was ok, the box was displayed good suggestions but did not have an ID attribute , that attribute was replaced by the first part of its name, which resulted in the insertion into the database bad ids equal to 0
11 - > 0 ,
11 - > 0 ...
e.t.c

Now, the code allows to use the "|" in the name as well assigns a name and ID.

Sorry for the incorrect form and commit any questions, but I worked on the project had to finish quickly and so came out, but it was my first implementation of such actions on github so please bear with us, I will try to make up a little table.

And of course sorry for my english.

Regards Krzysztof.

**Comment by dSkrbic** [comment]
Hello,
It works finely without your PR, here is what I get on GIT/Dev:
screenshot_dsk_2016 08 02_17h50m00s_011_

May I have missed something?

Regards

**Comment by makoso** [comment]
Hi dSkrbic,
Yes there I don't have any problems, but edit other product and try add this one as "accesory", relation.
I think u will see my problem ;)

**Comment by mickaelandrieu** [comment]
@makoso merged.

Thank you for this contribution :)

**Pull request merged**
