### PR TITLE
[+] BO: Show SQL Manager & SQL Export only if sql manager is enabled in profile

### PR DESCRIPTION
**Pull request by guestisp**
This PR enable "Show SQL" and "Export to SQL Manager" only if logged employee has access to SQL Module.
Without this, clicking on "Export to SQL Manager" will result in `Access denied.` error.

### CODE REVIEW

**Comment by guestisp** [comment]
Any change to get this merged? If employee has no access to SQL module, both buttons will trigger an access denied error. This PR solve this and removes buttons by properly using ACL.

I think that standard PS behavious is a bug.

**Comment by guestisp** [comment]
News for this? Standard PS behavious is buggy and makes a broken link

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, I think we can discuss this with our @PrestaShop/prestashop-product-managers 

Best regards.

**Comment by guestisp** [comment]
This is a bug. If employee has not SQL access, the hardcoded buttons always liks to an accedd denied page.
It's clearly a bug.

**Comment by jeromenadaud** [comment]
Hi, 

Thank you for your contribution.

Best regards.

**Pull request merged**
