### PR TITLE
Carriers error with the keys going couriers fray function array_merge

### PR DESCRIPTION
**Pull request by fest73**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Carriers error with the keys going couriers fray function array_merge
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Across var_dump

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8943)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
That's a weird issue, by any chance do you have more details about how to reproduce your error?

Thanks a lot

**Comment by fest73** [comment]
@Quetzacoalt91 For example, some courier has an error, the error falls into the array of Errors with the courier id key. After array_merge wipes the keys

**Comment by Quetzacoalt91** [comment]
Sorry for the late reply, have you tried the `+` operator? I have seen in http://php.net/manual/en/function.array-merge.php it preserves the numeric keys of the arrays.

```php
$error += $carrier_error;
```

**Comment by fest73** [comment]
@Quetzacoalt91  no..

**Comment by PierreRambaud** [comment]
hi @dariusakafest, is this issue still needed? :)

**Comment by Progi1984** [comment]
Hello @dariusakafest  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?
Would you mind to rebase your pull request?

Thanks :+1:

**Comment by PierreRambaud** [comment]
Hi @dariusakafest ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
