### PR TITLE
Product settings: availabilty label and delivery time configuration

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Move delivery information from https://github.com/PrestaShop/ps_legalcompliance to the Core and add default value for stock information
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/FF-95
| How to test?  |

### CODE REVIEW

**Comment by maximebiloe** [comment]
Linked with: https://github.com/PrestaShop/ps_legalcompliance/pull/39 & https://github.com/PrestaShop/StarterTheme/pull/198

**Review by aleeks — DISMISSED** [review]
Looks like ok

**Review by LittleBigDev — COMMENTED** [review]
Seems ok (I reviewed only the code style)

**Review by Quetzacoalt91 — COMMENTED** [review]
Tested on my side, it works.

However, by looking at your PR I do not see where you apply the default value on a brand new shop. Did I miss something?

**Comment by maximebiloe** [comment]
Nice catch @Quetzacoalt91.
I just added a commit with the default values: https://github.com/PrestaShop/PrestaShop/pull/8220/commits/c3fc8d1a06af7148ff11d0da025d4a24b6c4c7f7

**Comment by aleeks** [comment]
Last commit looks ok

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @maximebiloe

**Pull request merged**
