### PR TITLE
[-] FO : fix disappearing radio button when hovering.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, can you also add scss file modifications ?
themes/default-bootstrap/sass/autoload/uniform.default.scss

Best regards

**Comment by Dvir-Julius** [comment]
I hope that this is what you wanted... if no, I am lost ;)
If it is wrong, I will open a ticket at your forge.

**Comment by jeromenadaud** [comment]
Hi,

Great ! Thank you

Best regards.

**Comment by gRoussac** [comment]
Hey,

uniform.default.css.map ?

Regards

**Comment by jeromenadaud** [comment]
oh, yes you are right.

Here it is : https://github.com/PrestaShop/PrestaShop/pull/2738

Thanks

**Pull request merged**
