### PR TITLE
Add select all and unselect all

### PR DESCRIPTION
**Pull request by djbuch**

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by djbuch** [comment]
Hi,

ok I'll try to have a look at my PR and reply to it according your article.

Regards,
David

2015-11-05 17:44 GMT+01:00 Vincent Terenti <notifications@github.com>:

**Comment by vTerenti** [comment]
Ok thank you @djbuch !

Best regards

**Comment by maximebiloe** [comment]
Hello,

Thanks for your contribution.
We've made those modifications in PrestaShop 1.7 (https://github.com/PrestaShop/PrestaShop/pull/4781)

Best regards

**Pull request closed without merging**
