### PR TITLE
Change default tax rate for Finland, fixes #36712

### LINKED ISSUE #36712: Finland default VAT changes from 24% -> 25.5% on 1.9.2024
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Finnish government has decided to up VAT from 24% to 25.5% on 1.9.2024. The default values in PrestaShop should reflect this change.

### Expected behavior

On new installation fetching the Finnish localization pack installs the correct VAT percent (25.5%) for general goods.

### Steps to reproduce

1. Install prestashop
2. Load Finnish localization pack
3. Check that finland general goods tax rate is 25.5%

### PrestaShop version(s) where the bug happened

-

### PHP version(s) where the bug happened

-

### If your bug is related to a module, specify its name and its version

-

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Update Finnish default tax rate from 24% to 25.5%
| Type?             | improvement
| Category?         | LO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install Finnish localization, check the Finnish tax rate. It should 25.5%
| UI Tests          | -
| Fixed issue or discussion?     | Fixes #36712 
| Related PRs       | -
| Sponsor company   |

### CODE REVIEW

**Comment by Hlavtox** [comment]
@tswfi 8.1.x?

**Comment by matks** [comment]
The files you modified are frozen-in-time copy of https://github.com/PrestaShop/LocalizationFiles/

https://github.com/PrestaShop/LocalizationFiles/pulls is the source of data that is being updated live and fetched by live shops

**Comment by tswfi** [comment]
Ok, closing this and opening a new PR in https://github.com/PrestaShop/LocalizationFiles/

**Comment by tswfi** [comment]
https://github.com/PrestaShop/LocalizationFiles/pull/49

**Comment by Hlavtox** [comment]
@matks But the default install data must also be modified no?

**Comment by matks** [comment]
> # Submitting changes
> Once a Pull Request has been accepted in this repository, changes should be synchronized to the [main project's "localization" directory](https://github.com/PrestaShop/PrestaShop/tree/develop/localization) via Pull Request.
>
> Embedding the localization files in the project allows users to benefit from localization files without having to download them.

**Comment by Hlavtox** [comment]
Yeah, so he must also do a PR for this repository, for 8.1.x branch.

**Comment by tswfi** [comment]
@matks I checked the current localization repo and diffed it against core 8.1.x localization directory and there are quite a few changes that are not in the core repo. New states in for some countries, some name changes etc. 

Would it make sense to do a full sync of the localization repo files into core localization directory or do I need to cherry pick my changes into the core?

(and maybe this should even be made automatically.. an action in localization repo could create a pull request against core whenever localization repo master branch is updated?)

**Comment by matks** [comment]
> (and maybe this should even be made automatically.. an action in localization repo could create a pull request against core whenever localization repo master branch is updated?)

Would be awesome 😄 

> Would it make sense to do a full sync of the localization repo files into core localization directory or do I need to cherry pick my changes into the core?

I think a full sync would be OK 🤔 although I'm not 100% sure. But we can try, open the PR and see if the changes make sense

**Pull request closed without merging**
