### PR TITLE
remove configuration of AEUC_LABEL_TAX_INC_EXC from module ps_legalco…

### LINKED ISSUE #37569: AEUC_LABEL_TAX_INC_EXC configuration in core
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In some places there is still access to the configuration AEUC_LABEL_TAX_INC_EXC of the ps_legalcompliance module. This module is archived and this configuration can be deleted from the code.
The configuration should be replaced by a hook later.
Example:
Image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to the code and search for 'AEUC_'

### PrestaShop version(s) where the bug happened

dev

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Markus-Gurkcity**
…mpliance

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In some places there is still access to the configuration AEUC_LABEL_TAX_INC_EXC of the ps_legalcompliance module. This module is archived and this configuration can be deleted from the code.
The configuration should be replaced by a hook later.
| Type?             | improvement
| Category?         | FO / BO / CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | Fixes #37569
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `category` should be one of these: `FO`, `BO`, `CO`, `IN`, `WS`, `TE`, `LO`, `ME` or `PM`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hello @Markus-Gurkcity!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by kpodemski** [comment]
Hello @Markus-Gurkcity 

Could you target `9.0.x` branch? It would be better to have this change inside `9.0` version, `develop` is for the `9.1` version already.

**Comment by kpodemski** [comment]
Hello @Markus-Gurkcity 
changing the base branch on GitHub, unfortunately, won't be enough :( you will have to rebase your pull request, or close this one, and create a new one. Could you do that?

**Comment by Markus-Gurkcity** [comment]
I made a new PR: https://github.com/PrestaShop/PrestaShop/pull/37611

**Pull request closed without merging**
