### PR TITLE
Use combination image instead of the cover image in cart

### LINKED ISSUE #21775: FO - Product with combinations - Incorrect image displayed
#### Describe the bug

In the FO, when we add a product with combinations to the cart, the cover image is displayed instead of the Product's image selected.
image
This issue occurs in 

- ~~Product successfully added to your shopping cart Pop up~~ => Fixed
- ~~Shopping cart page~~ => Fixed https://github.com/PrestaShop/PrestaShop/pull/24248
- Checkout page ( cart summary details)
- Order final summary
- Order confirmation page

#### Steps to Reproduce

1. Go to FO
2. Select first product "Hummingbird Printed T-Shirt"
3. Add the Combination  Size-S, Color-Wite
4. Go to cart (or cart summary in checkout page, order final summary or order confirmation page)
5. See an error

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Use combination image instead of the cover image in cart
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21775
| How to test?      | Follow ticket instruction
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24248)

### CODE REVIEW

**Review by PululuK — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by matks — APPROVED** [review]
Change is relevant with other similar reworks, see https://github.com/PrestaShop/PrestaShop/pull/21782

**Comment by hibatallahAouadni** [comment]
Hello @PierreRambaud 

As mentioned in the issue, this bug occurs in 

- ~~Product successfully added to your shopping cart Pop up~~ => already Fixed
- Shopping cart page => Fixed by your PR :heavy_check_mark: 
- Checkout page ( cart summary details) => not fixed :x: 
- Order final summary => not fixed :x: 
- Order confirmation page => not fixed :x: 

See the attached screen record and screenshot below:

https://drive.google.com/file/d/1RAgqT7bPQpXUWkM9ZZJ8_sdMY_iqW4hK/view

image

> Use combination image instead of the cover image in cart

As you mentioned, it seems your PR suppose to fix only Shopping cart page, is that so?
If so, LGTM :heavy_check_mark: 
**But the issue needs to stay open** :wink: 

Thanks!

**Comment by matks** [comment]
Thank you @PierreRambaud and thank you @hibatallahAouadni

**Comment by PierreRambaud** [comment]
> Hello @PierreRambaud
> 
> As mentioned in the issue, this bug occurs in
> 
> * ~Product successfully added to your shopping cart Pop up~ => already Fixed
> * Shopping cart page => Fixed by your PR heavy_check_mark
> * Checkout page ( cart summary details) => not fixed x
> * Order final summary => not fixed x
> * Order confirmation page => not fixed x
> 
> See the attached screen record and screenshot below:
> 
> https://drive.google.com/file/d/1RAgqT7bPQpXUWkM9ZZJ8_sdMY_iqW4hK/view
> 
> image
> 
> > Use combination image instead of the cover image in cart
> 
> As you mentioned, it seems your PR suppose to fix only Shopping cart page, is that so?
> If so, LGTM 
> **But the issue needs to stay open** 
> 
> Thanks!

It is, but I will fix it everywhere, it will be easier and better.

**Comment by PierreRambaud** [comment]
ah, too late @matks merged it

**Pull request merged**
