### PR TITLE
[*] BO : Allow basic HTML attributes in editor

### PR DESCRIPTION
**Pull request by mcdado**
Role, data and aria attributes are used by Bootstrap, and serve several purposes.
See these:
- http://www.w3.org/TR/wai-aria/states_and_properties#state_prop_def
- http://www.w3.org/TR/role-attribute/
- http://www.w3.org/TR/html5/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes

### CODE REVIEW

**Comment by inetbiz** [comment]
:+1:  for this PR

**Comment by xBorderie** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

-xb.

**Comment by mcdado** [comment]
So, I checked the PR again, tested against 1.6.1.2, I found out that it doesn't affect at all the system. I see that the editor side is okay, the POST request sent to the server when editing fields passes the data-* and aria-* attributes. They get stripped by the HTML sanitizer, which should be configurable. Can anyone who will close this PR create an issue or create a bug in the Forge about this behavior? Thanks!

**Comment by mickaelandrieu** [comment]
:+1: sounds fair to me.

**Comment by xBorderie** [comment]
Hey @mcdado, thank you for your feedback!

Indeed, this sound fair and square, and I doubt our devs will have an issue with it :)

Sadly, this PR was made on the `1.6` branch, which is not used anymore. Could you make it again on the `develop` branch so that when it lands in PS 1.7, you get full credit for it?

Thank you very much!

**Comment by xBorderie** [comment]
Thank you for #4446! :)

**Pull request closed without merging**
