### PR TITLE
Fixed the position of the selection card

### LINKED ISSUE #28241: BO > Positions - Selection card is not well positioned
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There's a regression in develop branch.
When I check any module to unhook it, the card is hidden when I scroll.

In PS 1.7.8.x :
Screenshot 2022-04-12 at 16 27 08

In develop branch :

https://user-images.githubusercontent.com/16019289/162986222-a1f16f60-45d2-4f77-a7a0-42d9192b0399.mov

### Expected behavior

The card should be placed like in PS 1.7.8.x

### Steps to reproduce

1. Go to BO > Design Positions
2. Check any module
3. See bug - Selection card is not well placed

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixed the position of the selection card
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28241
| How to test?      | Cf. #28241

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by marwachelly — COMMENTED** [review]
Hello,

I tested the PR and I observed the following problems:

1. The Selection card doesn't exist in responsive (size 425x 888)

**With PR:**

https://user-images.githubusercontent.com/89604350/165086349-552f4c82-6924-43d5-ada5-1e39f734d2ea.mp4



**Without PR (PS1.7.8.5):**


https://user-images.githubusercontent.com/89604350/165085371-4263c248-fcdc-4da5-a760-0135f95da91e.mp4

2. The position of the selection card is not fix when scrolling down


https://user-images.githubusercontent.com/89604350/165085961-f3d7b726-39fe-44f0-9313-d945992b8092.mp4

Could you please check?

Thanks,

**Review by NeOMakinG — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by marwachelly — COMMENTED** [review]
Hello @Progi1984,

I retested the PR but both issues are still not fixed:

**First issues:**
The selection card in responsive case has a wrong position:


https://user-images.githubusercontent.com/89604350/165753333-3c7f85d6-91f9-47c7-8b52-8f8f281df4db.mp4

**Second issue:**

The position of the selection card is not fix when scrolling down

https://user-images.githubusercontent.com/89604350/165753585-96adeed1-e879-406c-bcd3-a6d01a0ed15a.mp4

Could you please check?

Thanks,

**Comment by Progi1984** [comment]
@marwachelly For the first point, it's a new issue which asks some UX. We validated that with @MatShir yesterday.

For the second point, have you built assets ? I try on Firefox & Chrome. No problem.

**Comment by marwachelly** [comment]
> 

Hello @Progi1984,

I still see the second issue even after make install. Could you please check? 
image


https://user-images.githubusercontent.com/89604350/166666866-f4fe63c9-90fa-43be-9b27-7a37027f2ee1.mp4


Thanks,

**Comment by NeOMakinG** [comment]
@marwachelly could we create another issue about this? It will require investigations and maybe a refactor of that thing, I'll work on it

In the meantime, as it's really nitpick, we can merge this one

**Review by marwachelly — APPROVED** [review]
Hello @Progi1984 and @NeOMakinG,

A new [issue](https://github.com/PrestaShop/PrestaShop/issues/28428) is created to fixe the position of the selection card. This PR is QA :heavy_check_mark: 

Thanks,

**Comment by Progi1984** [comment]
Thanks @marwachelly & @NeOMakinG

**Pull request merged**
