### PR TITLE
Merge 8.1.x into develop

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop.
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI Green ✅  & [auto tests](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5087100751) green ✅.
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by 0x346e3730** [comment]
Waiting for a review from automated tests sheriff regarding the failures on the auto tests.

**Review by M0rgan01 — DISMISSED** [review]

**Comment by boherm** [comment]
(cc @PrestaShop/qa-automation 😄)

**Comment by Progi1984** [comment]
@0x346e3730 Needs UI tests launched on `ga.tests.ui.pr`.

**Comment by boherm** [comment]
@Progi1984 https://github.com/boherm/ga.tests.ui.pr/actions/runs/5000867463 🔴 😔

**Comment by Progi1984** [comment]
@boherm Could you restart failed jobs like #32583 has been merged in develop ?

FYI @nesrineabdmouleh :star:

**Comment by boherm** [comment]
@Progi1984, @nesrineabdmouleh Just 1 job failed left on rerun. (https://github.com/boherm/ga.tests.ui.pr/actions/runs/5000867463/jobs/8961222701)

**Comment by nesrineabdmouleh** [comment]
Hello @boherm,

The first error is related to the wording of the success alert message when enabling mobile in module manager page => 
-Enable **Mobile** action on module statsstock succeeded.
+Enable **mobile** action on module statsstock succeeded.
We should verify if the wording in 8.1.x should be applied in 9.0.0 

The second error also in Module manager page, we cannot enable/disable/install/... with bulk action =>
https://watch.screencastify.com/v/i2pKILH97R9nwTVsfrli

**Comment by boherm** [comment]
Hello @l-delin!
What do you think about this?
> The first error is related to the wording of the success alert message when enabling mobile in module manager page =>
-Enable Mobile action on module statsstock succeeded.
+Enable mobile action on module statsstock succeeded.
We should verify if the wording in 8.1.x should be applied in 9.0.0

**Comment by l-delin** [comment]
Hello @boherm, `Enable mobile action on module statsstock succeeded.` is good. 👍

**Review by boherm — DISMISSED** [review]

**Comment by Progi1984** [comment]
Ok for UI Tests : https://github.com/boherm/ga.tests.ui.pr/actions/runs/5000867463/jobs/9071764430

The only :red_circle: is due to this PR : #32663

**Review by boherm — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Comment by jolelievre** [comment]
Last run (hopefully) after catalog update https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5056799954

**Review by matks — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Pull request merged**
