### PR TITLE
Disable regeneration of fos js routing for 1.7.8.x

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | No need to regenerate fos js routing for 1.7
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| Related PRs       | n/a
| How to test?      | n/a
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by jolelievre — COMMENTED** [review]
Hi @kpodemski 

why should we disable this for the 178x branch, we should keep it until the supports is over but it seems a bit early to disable this no?

**Comment by kpodemski** [comment]
Hi @jolelievre 

As the support for this version is now limited, chances for this script being useful are very, very low.

**Review by 0x346e3730 — APPROVED** [review]

**Comment by zuk3975** [comment]
I still find this whole cron useless, because everytime we expose a new route, we must manually regenerate the json to see it work and test the related PR, so I just don't see a point in this automatic regeneration.
In other words - the routes only changes when we change the code (with the PR's), so those PR's should be responsible to regenerate the routes, isn't that right? 🤷‍♂️ 

Lets say someone changed a route in his PR and forgot to regenerate it, but left some mistake which ended up that his feature worked with old routing and passed QA, but wouldn't work with the correct regenerated routing, so the PR gets merged to develop. After some time the bot regenerates the route and the feature suddenly doesn't work anymore. Wouldn't this happen?
Is there a scenario where this bot is really beneficial? Am I missing something else?

**Comment by kpodemski** [comment]
@PrestaShop/committers what do you think? I agree with @zuk3975 - unless there were some other reasons for enabling the cron

**Pull request closed without merging**
