### PR TITLE
Improve StockManager queries performances

### LINKED ISSUE #14703: Poor performances in order status update due very slow StockManager.php queries
After troubleshooting slowdowns in order status change from a customer with a large catalogue I noticed that there are two queries that takes a very lot of time to run.

**ValidateOrder** method and status change are taking up to 15~20 seconds due to those queries.

First query in /src/Adapter/StockManager.php:171 (updateReservedProductQuantity method)
takes ~ 7 seconds to run   on high-spec dedicated MySQL server
Second query in /src/Adapter/StockManager.php:118 (updatePhysicalProductQuantity method)
takes ~ 10 seconds to run  on high-spec dedicated  MySQL server

First query is : 

```
UPDATE ps_stock_available sa
SET sa.reserved_quantity = (
SELECT SUM(od.product_quantity - od.product_quantity_refunded)
FROM ps_orders o
INNER JOIN ps_order_detail od ON od.id_order = o.id_order
INNER JOIN ps_order_state os ON os.id_order_state = o.current_state
WHERE o.id_shop = 1 AND
os.shipped != 1 AND (
o.valid = 1 OR (
os.id_order_state != 8 AND
os.id_order_state != 6
)
) AND sa.id_product = od.product_id AND
sa.id_product_attribute = od.product_attribute_id
GROUP BY od.product_id, od.product_attribute_id
)
WHERE sa.id_shop = 1
AND sa.id_product IN (SELECT product_id FROM ps_order_detail WHERE id_order = 15244)
```

Second query is :

```
UPDATE ps_stock_available sa
SET sa.physical_quantity = sa.quantity + sa.reserved_quantity
WHERE sa.id_shop = 1
```

This query seems to update the **whole** ps_stock_available table even if I am changing the status of a single order (?).

**In my case the ps_stock_available table have 903.000 distinct rows (website have 150k products with 740k combinations) so you'll need a large shop to reproduce this.**

Note that the problem was already represented in [BOOM-6265](http://forge.prestashop.com/browse/BOOM-6265) , but issue was closed and mis-referenced to other closed issues that had nothing to do with this problem, so it is still present in 1.7.6.0

### PR DESCRIPTION
**Pull request by tom-combet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Queries were using variable argument (select statement) in IN keyword so database was rebuilding each time an execution plan (better explained there: https://stackoverflow.com/a/1013959/17471786).<br>The order status change command was therefore very slow in big shops.
| Type?             | improvement
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #14703.
| Related PRs       | N/A
| How to test?      | Change order status on a shop with a lot of orders, you can use [this](https://github.com/PrestaShop/prestashop-shop-creator) to make a shop with a lot of order and check the time to update. You need to test this PR with mysql 8 and mysql 5 
| Possible impacts? | N/A

### CODE REVIEW

**Comment by kpodemski** [comment]
Interesting! Nice job @tom-combet 

Two questions:
1. I remember some issues using `WITH` with MySQL 5.x. Have you tested it on this version?
2. Could you provide some before and after benchmarks?

**Comment by tom-combet** [comment]
> Interesting! Nice job @tom-combet
> 
> Two questions:
> 
>     1. I remember some issues using `WITH` with MySQL 5.x. Have you tested it on this version?
> 
>     2. Could you provide some before and after benchmarks?

Thanks :)

I work on a simple LAMP stack. I plan to learn Docker, but a bit busy atm.
Can I test on MySQL 5 and provide a benchmark without it? I don't know how...

For info, I tested on a shop with 200000+ orders and it took 2 seconds to change status of 50 orders. It was taking ~30-40 seconds before the fix.

**Review by PrestaEdit — CHANGES_REQUESTED** [review]
Regarding my own test, I've an issue with this while trying to validate an order on the Front Office: 

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'od2 AS ( SELECT product_id FROM ps_order' at line 1

The query made is this one :

> WITH od2 AS ( SELECT product_id FROM ps_order_detail WHERE id_order = 9 ) UPDATE ps_stock_available sa INNER JOIN od2 ON sa.id_product = od2.product_id SET sa.reserved_quantity = ( SELECT SUM(od.product_quantity - od.product_quantity_refunded) FROM ps_orders o INNER JOIN ps_order_detail od ON od.id_order = o.id_order INNER JOIN ps_order_state os ON os.id_order_state = o.current_state WHERE o.id_shop = 1 AND os.shipped != 1 AND ( o.valid = 1 OR ( os.id_order_state != 8 AND os.id_order_state != 6 ) ) AND sa.id_product = od.product_id AND sa.id_product_attribute = od.product_attribute_id GROUP BY od.product_id, od.product_attribute_id ) WHERE sa.id_shop = 1

Tested with MySQL 5.7.38. As I see, the common table expressions (WITH) is part of MySQL 8, not before.

**Comment by tom-combet** [comment]
@PrestaEdit Thanks a lot for testing it!

I replaced WITH by a select subquery, can you test again please?
By the way, you can also test to change an order status, it would fail too and it's faster than checking out an order.

**Review by Progi1984 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
I can't test with mysql 5 but code seem to be good i just update the how to test.

**Comment by PrestaEdit** [comment]
Tested with MySQL 5.7.38, no issues visibles.

**Comment by khouloudbelguith** [comment]
Hi @tom-combet,

I have some trouble testing this PR

1. I tried to generate a lot of data using https://github.com/PrestaShop/prestashop-shop-creator (100 orders + 1000 carts + 100 customers) => when I tried to install the shop, it was blocked in the 87% 
image

image

2. Also, I tried to reproduce the issue with develop branch, it was ok, no problem occurred in my case.
image

- I have 1000 orders, and in each order: I have 10 products
- I have 100 customers
- I have 100 products

I attached a screen record

https://user-images.githubusercontent.com/16067358/202136262-0fea35ea-cd58-45f5-a64a-241bbb88bb41.mp4

Ping @PrestaShop/prestashop-maintainers @PrestaShop/prestashop-core-developers could you please check and test this PR?

Thanks!

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I tested it on the store with 135.000 orders. The difference is astonishing. 

@PrestaShop/qa-team I would like to approve and merge this PR. I tested it, I compared the table before and after changing the query, and it is all good.

**Review by Hlavtox — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @kpodemski :)

OK for a test by you, you can approve and merge it.
And thanks @tom-combet for the PR !

**Comment by ghost** [comment]
@PrestaEdit 

Nice job Tom

**Comment by alisamie97** [comment]
> I tested it on the store with 135.000 orders. The difference is astonishing.

Hi @kpodemski . would you please describe your test? I want to test this PR and my PR at #31065 
Actually the testing has two stages:
1. validating the ps_stock_available with and without the optimizations
2. analyzing the query time

**Review by matthieu-rolland — COMMENTED** [review]
So this PR is aproved and tested, or am I missing something ? @kpodemski ?

**Comment by Hlavtox** [comment]
@kpodemski Can we merge this?

**Comment by kpodemski** [comment]
thank you, @tom-combet :)

**Comment by ebuildy** [comment]
any chance to backport this fix for old versions please ?

**Comment by tom-combet** [comment]
> any chance to backport this fix for old versions please ?

@ebuildy I don't think so, but you can still add the changes manually: there is only 1 file changed.

**Comment by PululuK** [comment]
Nice @tom-combet

**Pull request merged**
