### PR TITLE
Remove deprecated files

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated features on v9.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | I only removed code deprecated in previous version and that was not used, so not behavior should be modified. I believe automated tests should tell us if something was broken although in theory it should not happen.
| Possible impacts? | None, only deprecated and not used code has been removed

### CODE REVIEW

**Comment by FabienPapet** [comment]
~Automated tests: https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4818675817~

**Review by lartist — APPROVED** [review]

**Review by lartist — CHANGES_REQUESTED** [review]
Auto tests failed

**Comment by nesrineabdmouleh** [comment]
Hello @FabienPapet 

The errors are not related to the PR.
Please rebase your branch from https://github.com/PrestaShop/ga.tests.ui.pr and create a new run of UI tests.

Thank you!

**Comment by FabienPapet** [comment]
https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4820610171

**Review by lartist — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
Finally UI tests are :green_circle: 
The failures are the same in the nightly

**Review by boherm — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Comment by mflasquin** [comment]
Thanks @FabienPapet

**Pull request merged**
