### PR TITLE
Add missing, remove useless and update existing index.php

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added full path to `index.php` files to prevent useless redirections. Removed useless `index.php` files and added missing `index.php` files.
| Type?         | Improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Check every directory.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11411)

### CODE REVIEW

**Comment by MathiasReker** [comment]
WIP

**Comment by MathiasReker** [comment]
Wdyt?

**Comment by PierreRambaud** [comment]
Hi,
Sadly, we are unable to review this PR due to the amount of files changed.
Can you separate this in many commits:
- one with code sniffer
- one with missing files
- ...

We found that you change the OSL license to AFL this is not possible I think and you also change the date 2018 to 2017 for some files.
https://github.com/PrestaShop/PrestaShop/pull/11411/files/ac0839b2f7e16d8453e548a94f8e253b5be57003..5c95e71bc53092860e8906080ef11a3f864368cf#diff-b6eedd7eb97eb5edfbdf55778709a5f1R3

Regards

**Comment by MathiasReker** [comment]
@PierreRambaud I undestand. I will try to do so. Do you prefer the long patch to prevent redirections?

Eg. `header('Location: ../../../');` instead of `header('Location: ../');`

**Comment by PierreRambaud** [comment]
Let's keep the `header('Location: ../');`, otherwise it must be in other commit to be sure we can review all paths :/

**Comment by MathiasReker** [comment]
I can make it in an other commit. I already made the script to write the full path. What do you prefer? :)

**Comment by MathiasReker** [comment]
Some files already use a patch different from `../`

**Comment by PierreRambaud** [comment]
I clearly prefer the full path to prevent useless redirection :)

**Comment by MathiasReker** [comment]
No problem :) How do I know if I should replace empty dir with OSL of AFL?

**Comment by MathiasReker** [comment]
@PierreRambaud I reverted everything and made a commit per path per license. :) There are still some dirs with missing index.php, but I don't know how to check if they should be OSL or AFL? I can easily add the rest once I know if either OSL or AFL.

**Comment by MathiasReker** [comment]
Those dirs does not have index.php:
[NOK.txt](https://github.com/PrestaShop/PrestaShop/files/2589294/NOK.txt)
(I did not exclude .git etc. This is just raw output)

Those dirs have index.php:
[OK.txt](https://github.com/PrestaShop/PrestaShop/files/2589295/OK.txt)

**Comment by MathiasReker** [comment]
I could use a list like this (eg.):

OSL:
`\classes\*`
`\src\*`

AFL:
`\admin-dev\themes\default\css\vendor\*`

This list could be made from NOK.txt =)

**Comment by PierreRambaud** [comment]
Some directories don't need index.php, such as `classes`, `admin-dev/backups`, ...
They already have a `.htaccess` to prevent directory listing and don't allow access to resources.
Only `public` resources need this file :)

**Comment by MathiasReker** [comment]
These both have .htaccess and index.php. Can I remove the index.php?

```

\admin-dev
\bin
\cache
\classes
\config
\controllers
\docs
\download
\img
\js
\localization
\mails
\modules
\override
\pdf
\themes
\tools
\upload
\var
\vendor
\admin-dev\backups
\admin-dev\export
\admin-dev\import
\config\xml
\docs\csv_import
\install-dev\sandbox
\tools\parser_sql
\tools\profiling
\translations\cldr


```

**Comment by ttoine** [comment]
OSL: core
AFL: themes and modules.

It means that the "classic" theme is in AFL, even if it is in the core repository. Thats is why bot OSL and AFL are included in this repository :-)

**Comment by PierreRambaud** [comment]
@MathiasReker It depends on what .htaccess authorize: granted or denied. If granted, children need index.php, otherwise don't care =)

**Comment by MathiasReker** [comment]
Everything is clear now. Thanks!

**Comment by MathiasReker** [comment]
WIP

**Comment by MathiasReker** [comment]
@PierreRambaud Everything should be good now 🙏 I hope my commits make sense to you! :-)

**Comment by MathiasReker** [comment]
I don't understand why Travis CI fails?

**Comment by Quetzacoalt91** [comment]
We can find in the output: `Warning: scandir(/home/travis/build/PrestaShop/PrestaShop/override/classes/): failed to open dir: [...]`.

If you removed these folders, you should bring back them. :)

**Comment by MathiasReker** [comment]
folders

Weird, I did not remove any folders. I attracted a screenshot of `/override/classes/`

**Comment by MathiasReker** [comment]
folders-2

**Comment by PierreRambaud** [comment]
Git take only files and not directories. If a directory is empty it will ignore it. This is why there were index.php.

**Comment by MathiasReker** [comment]
Oh, I see. So for every empty dir we now need an index.php :)

**Comment by mickaelandrieu** [comment]
I can't explain why this update breaks our test suites... /c @PierreRambaud WDYT?

**Comment by PierreRambaud** [comment]
@mickaelandrieu => @Quetzacoalt91 already found and tell us what is missing.

**Comment by MathiasReker** [comment]
I tried to replace empty folders in my last commit, but it did not solve the issue.

**Comment by PierreRambaud** [comment]
@MathiasReker it's about `override/classes` your latest commit doesn't include a index.php in this directory.

**Comment by MathiasReker** [comment]
Thanks @PierreRambaud

**Comment by MathiasReker** [comment]
Hm.. for some reason I can't commit changes in `/override/*`

**Comment by MathiasReker** [comment]
All files has been updated with correct path and missing files has been created. Some files can be deleted again, because they are not needed, but I am unsure witch can be deleted. Maybe this can be improved in an other PR?

**Comment by MathiasReker** [comment]
Travis CI should pass now :)

**Comment by MathiasReker** [comment]
Can this get merged, then we can remove the not needed index.php files in an other PR?

**Comment by MathiasReker** [comment]
Conflicts solved.

**Pull request closed without merging**
