### PR TITLE
Merge 8.0.x into 8.1.x

### PR DESCRIPTION
**Pull request by 0x346e3730**
Questions | Answers
-- | --
Branch? | 8.1.x
Description? | Merge 8.0.x into 8.1.x
Type? | improvement
Category? | ME
BC breaks? | no
Deprecations? | no
How to test? |  
Fixed ticket? |  
Related PRs |  
Sponsor company | PrestaShop SA

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Comment by nicosomb** [comment]
Tests here : https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4192044541

@0x346e3730: why isn't there a description in your post? 🙂

**Comment by 0x346e3730** [comment]
> Tests here : https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4192044541
> 
> @0x346e3730: why isn't there a description in your post? 🙂

I thought that it wasnt needed, my bad fixed it

**Comment by nicosomb** [comment]
The PR description is used to auto-tagged PR's. Then tags are used by contributors, changelog tool, etc. This description is very useful 😉 thank you for editing.

**Review by FabienPapet — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]
CI and ga.tests are green so it's ok for me.

**Comment by AureRita** [comment]
Hi @0x346e3730 

Thank you for your PR, I tested it by testing if this PR are correctly integrated in this PR : 
#31148
#31023
#31137
#31152

And as you indicated it with @nesrineabdmouleh , The test Auto is validated, 

So it QA approved :heavy_check_mark: 

Thank you !

**Comment by nicosomb** [comment]
Thank you @0x346e3730 and @AureRita

**Pull request merged**
