### PR TITLE
FO: Layered navigation select does not work with friendly URLs turned OFF

### PR DESCRIPTION
**Pull request by marrouchi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | When selecting filter display style "select" and having friendly URLs off changing option does not filter anything. It only works with friendly URLs enabled.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/NM-856
| How to test?  | Disable the URL rewrite and set category filter display as a select box in facet search module's filter template configuration.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by antoin-m** [comment]
Hey @marrouchi, thank you for your contribution!

I can't reproduce the bug. I disabled friendly URLs and used a select facet for the colors but when I use it it works. Did you do something else?

**Comment by marrouchi** [comment]
Hey, try to use a select facet for categories filter. 

FYI: This issue has been reported by someone else, i retested myself and i got the same anomaly

**Comment by antoin-m** [comment]
@marrouchi Are you sure you PrestaShop develop branch is up to date? I've reworked the whole dropdown facet to make it bootstrap compliant on classic. From what I see in the diff your version is still using the old HTML <select>

**Comment by marrouchi** [comment]
@antoin-m Yes you're right, i've just updated my branch and the problem is gone (html has been updated).

**Comment by antoin-m** [comment]
I'm happy to hear it! Thank you for the contribution anyway 😃

**Pull request closed without merging**
