### PR TITLE
Add AdminStatesController which is not exist in develope

### PR DESCRIPTION
**Pull request by tesshsu**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix ajax call select country and state not show in BO add store or edit store page
| Type?             | bug fix
| Category?         |  BO
| How to test?      | Go to BO -> add or edit store -> select Country like united State -> check states lists if show up
| Fixed ticket?     | Fixes ##32316

Fix result:

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hello thank you for the PR but we cannot reinsert this file that was deleted just to fix a country list 😅 . This PHP file contains a lot more logic than needed.

In order to fix bug https://github.com/PrestaShop/PrestaShop/issues/32316 properly what is needed is to implement the feature in the new Symfony page, not put back the old page ;) . We want this code deleted and replaced by modern code.

**Comment by tesshsu** [comment]
Hi @matks 
Thanks for the helpful feedback, could you provide more specs cause I'm not sure 'We want this code deleted and replaced by modern code'? 
tks

**Comment by zuk3975** [comment]
Stores controller is being migrated to symfony, but it will be only shipped for v9.0 or later.
Until thats done, we could probably add some "quickfix" to stores "states" selector by using the "modern" endpoint which returns json response with the states `PrestaShopBundle\Controller\Admin\Improve\International\StatesController::getStatesAction`? It shoudn't be that hard should it? :thinking:

**Comment by zuk3975** [comment]
I think this https://github.com/PrestaShop/PrestaShop/blob/develop/js/admin.js#LL1081C1-L1081C1 could be adapted to use the new endpoint (just not sure if we should try generate the url by sf router and pass it to data attribute or just hardcode the url in js :smile: ) wdyt @matks ?

**Comment by zuk3975** [comment]
https://github.com/PrestaShop/PrestaShop/pull/32554
here is the fix, it seems to work, maybe its enough? :man_shrugging:

**Comment by kpodemski** [comment]
thanks @tesshsu - I'm closing this PR in favor of #32554

**Pull request closed without merging**
