### PR TITLE
Added a new hook to custom SwiftMessage before sending mail

### PR DESCRIPTION
**Pull request by tonyyb**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  Adding hook to `Mail::send()` method to be able to custom SwiftMessage before sending mail.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Follow example bellow.

**Example of usage in a module :** 

```php
public function hookActionMailAlterMessageBeforeSend($params)
{
     /**
     * @var Swift_Message $message
     */
     $message = $params['message'];
     $headers = $message->getHeaders();
     $headers->addTextHeader('MY-CUSTOM-HEADER-KEY', 'MY-VALUE']);
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9428)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]
Sound legit!

**Comment by PierreRambaud** [comment]
@Quetzacoalt91 Should it needs a Waiting for QA?

**Comment by mickaelandrieu** [comment]
@PierreRambaud hmm without a module with the hook, the QA team won't test it.

**Comment by mickaelandrieu** [comment]
Hello @tonyyb,

looking at our hooks, we already have many hooks to manipulate emails;

* ``actionEmailAddBeforeContent``: Add extra content before mail content

This hook is called just before fetching mail template

* ``actionEmailAddAfterContent``: Add extra content after mail content

This hook is called just after fetching mail template

* ``actionEmailSendBefore``: Before sending an email

This hook is used to filter the content or the metadata of an email before sending it or even prevent its sending

* ``sendMailAlterTemplateVars``: Alter template vars on the fly

This hook is called when Mail::send() is called

For consistency, don't you think we should name this one ``actionMailAlterMessageBeforeSend`` as it will be used before ``actionEmailSendBefore`` in the mailing workflow?

Ping @Quetzacoalt91, I'm wondering if we should add a line in the database to document the behavior: I know it's not required to make the hook available but it's really useful to figure out what the hook do: wdyt?

**Comment by PierreRambaud** [comment]
Can you rename the hook in `actionEmailSendBefore` as @mickaelandrieu said? It's a great idea =)

**Review by PierreRambaud — APPROVED** [review]

**Comment by tonyyb** [comment]
Thanks @mickaelandrieu @PierreRambaud (and sorry for the delay).

**Comment by Quetzacoalt91** [comment]
Thank you @tonyyb

**Pull request merged**
