### PR TITLE
Add gsitemap

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Includes gsitemap as a native module
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | The module is installed with PS and works with 1.7

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9404)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @eternoendless

**Comment by MathiasReker** [comment]
@eternoendless I just made a lot of changes to the sitemap module. I solved every reported bug. I made it compatible with bootstrap and fixed a lot of issues. If I make a pull request on the module page, will you check it out?
screenshot_2018-08-08 modules services demo

**Comment by PierreRambaud** [comment]
@Mreker Of course we will check it! We are always glad to view and comment a pull request to improve everything that can be improved!

**Comment by MathiasReker** [comment]
Please check this: https://github.com/PrestaShop/gsitemap/pull/53

I did put a lot of work into the module in order to fix all the bugs I could find.

**Comment by Mreker** [comment]
[gsitemap.zip](https://github.com/PrestaShop/PrestaShop/files/2270124/gsitemap.zip)

or you can try it here

**Pull request merged**
