### PR TITLE
Fix product page v1 footer responsive

### LINKED ISSUE #29795: BO - Responsive - Product page V1 -  bad display of offline/online button in footer page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Offline/online button is not displayed correctly on small screen (between 1200px & 1473px precisely)
The button goes to a new line instead of staying beside the "Offline/Online" text.
Tested on:

8.0.0 ❌ 
- Offline

footer-pp1-offline-btn-800

- Online

footer-pp1-online-btn-800

1.7.8.6 ✅ 
- Offline

footer-pp1-offline-btn-1786

- Online

footer-pp1-online-btn-1786

1.7.7.8 ✅
- Offline

footer-pp1-offline-btn-1778

- Online 

footer-pp1-online-btn-1778

It's a regression bug

### Expected behavior

The button should be beside the "Offline/Online" text.

### Steps to reproduce

1. Go to BO on a small screen (between 1200px & 1473px)
2. Go to Catalog > Products
3. Edit an online product, see error on the footer page of "Online" button
4. Go back to Products list page > Click on "New product" button
5. See error on the footer page of "Offline" button

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Bootstrap cols are wrong on the product v1 footer layout 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29795
| How to test?      | See issue
| Possible impacts? | Product page v1 footer responsive

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by nicosomb** [comment]
@NeOMakinG I will approve your PR but I have a global question about about design PR. 
Do you publish some screenshots to make a "before / after"? With them, we can improve our review. Or this test is done by the QA team, so no need for us to review this part.

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
> @NeOMakinG I will approve your PR but I have a global question about about design PR. Do you publish some screenshots to make a "before / after"? With them, we can improve our review. Or this test is done by the QA team, so no need for us to review this part.

it's the QA that will test this :+1: 

Sometimes, in some specific cases, it's useful to add a screen capture in the pull request, but here it would be overkill imho, we already have screen captures before/after in the issue.

**Review by MhiriFaten — APPROVED** [review]
Hello @NeOMakinG ,

Thanks for your PR. The issue is well fixed. :tada:

Here is my checked list :

-Check with different languages: OK
-Check with different browsers: OK
-Check the automated tests: OK

[Untitled_ Oct 6, 2022 3_49 PM.webm](https://user-images.githubusercontent.com/111756615/194344429-f0155dc5-afef-4bc4-877c-4eba61c8bd59.webm)

**Comment by NeOMakinG** [comment]
Thanks for testing @MhiriFaten

**Pull request merged**
