### PR TITLE
Fix webservice id_shop_group parameter

### LINKED ISSUE #19566: id_group_shop instead of id_shop_group in webservice parameter
#### Describe the bug

There is a typo in the name of id_shop_group parameter for webservice, see official doc: https://devdocs.prestashop.com/1.7/development/webservice/tutorials/advanced-use/manage-multishop/#define-shop-specific-override)

#### Expected behavior

Activate multishop, with 2 groups (eg: "Default" and "Stores"), with at least 1 shop in each group. Activate webservices and create a key with full access (all resources and all shops). Create a product for the second groups's shop. Get products from /api/products?id_shop_group=2 you won't see the product you previously create.

#### Steps to Reproduce

Activate multishop, with 2 groups (eg: "Default" and "Stores"), with at least 1 shop in each group. Activate webservices and create a key with full access (all resources and all shops). Create a product for the second groups's shop. Get products from /api/products?id_shop_group=2 you won't see the product you previously create.

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

### PR DESCRIPTION
**Pull request by loicsapone**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Fix typo in the name of id_shop_group parameter for webservice, see official doc: https://devdocs.prestashop.com/1.7/development/webservice/tutorials/advanced-use/manage-multishop/#define-shop-specific-override)
| Type?         | bug fix
| Category?     | WS
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes #19566
| How to test?  | Activate multishop, with 2 groups (eg: "Default" and "Stores"), with at least 1 shop in each group. Activate webservices and create a key with full access (all resources and all shops). Create a product for the second groups's shop. Get products from /api/products?id_shop_group=2. Without this fix, you won't see the product you previously create.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19565)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Hello @loicsapone, thanks for your contribution !

I created an issue in order to populate the changelog with your work, if you can create it before opening the PR next time :)

Thanks, have a good day !

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I'm sorry but the problem is in the doc not in the code :sweat_smile:

**Comment by loicsapone** [comment]
@NeOMakinG Sorry, I'll do it next time!

@PierreRambaud In the whole project it's called shop_group (database & code), excepte in the webservice... So I think it's rather a naming problem in the code than in the documentation :smile:

**Comment by PierreRambaud** [comment]
> @NeOMakinG Sorry, I'll do it next time!
> 
> @PierreRambaud In the whole project it's called shop_group (database & code), excepte in the webservice... So I think it's rather a naming problem in the code than in the documentation

If we change this in the code, it's a BC break :/ Except if we manage both cases, we need to keep the original behavior :/

**Comment by loicsapone** [comment]
Correct, I hesitated when I opened the PR to flag it as BC break, but can a bug be considered as normal behavior and therefore cause a BC break if it's fixed?

If we leave aside the philosophical aspect, maybe we should correct the doc now and fix the bug later, maybe in the batch of modifications that you will make on the multistore (#19304)?

**Comment by PierreRambaud** [comment]
> Correct, I hesitated when I opened the PR to flag it as BC break, but can a bug be considered as normal behavior and therefore cause a BC break if it's fixed?
> 
> If we leave aside the philosophical aspect, maybe we should correct the doc now and fix the bug later, maybe in the batch of modifications that you will make on the multistore (#19304)?

Yes, I think it's better to fix the doc and try to fix it in the next release (if it's possible :sweat: )

**Comment by jolelievre** [comment]
I checked at the doc and how the parameter is used, `id_shop_group` makes more sense because it matches the entity fields (and database values as well). But we can't remove the previous behaviour indeed, so I think we should manage **both** parameters and document `id_group_shop` as deprecated in the doc.

This can be done with something like this:
```php
$idShoupGroup = null;
if (isset($params['id_shop_group']) && is_numeric($params['id_shop_group'])) {
    $idShoupGroup = $params['id_shop_group'];
} else if (isset($params['id_group_shop']) && is_numeric($params['id_group_shop'])) {
    $idShoupGroup = $params['id_group_shop'];
}
if (null !== $idShoupGroup) {
    ...
}
```

**Comment by loicsapone** [comment]
I'll try to find time to update my PR this weekend!

**Comment by jolelievre** [comment]
Hi @loicsapone,

I made a PR to update the doc with the appropriate parameter name https://github.com/PrestaShop/docs/pull/572

This is not the expected one (because it doesn't match the model field) but at least the doc is consistent now. Once your PR fixes this issue, allowing to use both parameters we will update the doc and mark `id_group_shop` as deprecated

If you can't find the time to update the PR no worries, if you want I can do it for you Let me know

**Comment by loicsapone** [comment]
Hi @jolelievre,
I update the PR this morning :blush:

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thank you @loicsapone

**Comment by SD1982** [comment]
HI @loicsapone I still don' t see the product created in the **_"stores group shop"_**

### I have the following parameters :
**Webservice** 
capture d'écran_75


**Multistore**
**_2 shops groups :_**
=> default group ( id_shop_group = 1 )  
=> stores group ( id_shop_group = 2 )
 
**_2 shops_** 
=>  the default group shop ( id_shop = 1 ) 
=> the stores group shop ( id_shop = 2 )

**_2 new products_** 
=> the default group shop product ( id = 20 )
=> the stores group shop product ( id = 21 )

### And I have the following results :

1 - ] **with the url "api/products"** => i see the product created in the _**"default group shop"**_ (id = 20 ) but not the product created in the **_"stores group shop"_** (id = 21 )
capture d'écran_70



2 - ] **with the url "api/products?id_shop=1"** (it's the ID of the "default" group shop)=> i see the product created in the _**"default group shop"**_ (id = 20 ) but not the product created in the **_"stores group shop"_** (id = 21 )
capture d'écran_71



3 - ] **with the url "api/products?id_shop=2"** (it's the ID of the "stores" group shop)=>  i see the product created in the **_"stores group shop"_** (id = 21 ) but not not the one created in the _**"default group shop"**_ (id = 20 )
capture d'écran_72


4 - ] **with the url "api/products?id_shop_group=1"** (it's the ID of the "default" group)=> i see the product created in the _**"default group shop"**_ (id = 20 ) but not the product created in the **_"stores group shop"_** (id = 21 )
capture d'écran_73


5 - ] **with the url "api/products?id_shop_group=2"** (it's the ID of the "default" group)=> i see the product created in the _**"default group shop"**_ (id = 20 ) but not the product created in the **_"stores group shop"_** (id = 21 )
capture d'écran_74

For the points 2 and 3 it's correct but for the others points the product created in the **_"stores group shop"_** is still not displayed in my request 

Did I miss something while reproducing the "how to test" ?

**Comment by loicsapone** [comment]
Hi @SD1982,

The purpose of this PR is to correct the parameter bug. The problem you are reporting is related to a context bug when using the webservice.

When you send the `id_shop_group` (or `id_group_shop`) parameter, the method `Shop::initialize()` set the ID of the default shop (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/shop/Shop.php#L452) and the id of the shop group you specified.
But, when Prestashop try to find the objects you requested, it doesn't use the `id_shop_group` from context and only uses the default `id_shop` it set previously (https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ObjectModel.php#L1395).

I quickly patched the problem in my project by replacing this line with the following code:
```php
$sql_filter = 'AND `multi_shop_' . bqSQL($this->def['table']) . '`.id_shop IN (' . implode(', ', Shop::getContextListShopID()) . ') ' . $sql_filter;
```

There are ways to make it cleaner and more optimized. I would try to find a better solution and do a PR if there is not one already open but I don't know when I will be able to do it.

**Comment by jolelievre** [comment]
Hi @loicsapone 

So you mean the bug related to shop context should be fixed in another PR? If yes then @SD1982 we just need to confirm that both parameters `id_shop_group` and `id_group_shop` have the same behaviour (including the bugs)

This way we at least validate both parameters are consistent and usable, and the bug can indeed be fixed in another PR

**Comment by SD1982** [comment]
Hi @jolelievre yes i will check that :+1

**Comment by SD1982** [comment]
Hi @loicsapone thank you for your return indeed I had misunderstood the purpose of your pull request my bad ! 

@jolelievre I have tested with the two paramaters (new and deprecated) and the behaviour is the same with "id_shop_group" or "id_group_shop" .
So it's good for the PR ! :+1:

**Comment by Progi1984** [comment]
Thanks @loicsapone

**Comment by jolelievre** [comment]
Thanks @loicsapone and @SD1982 

@loicsapone could you please open an issue that describes the bug you mentioned, and that @SD1982 reproduced? I think you're the one who understands it better and won't forget any details 😉
Thank you

**Comment by 8191** [comment]
@loicsapone @jolelievre Did the described bug in interworking of the `Shop::initialize()` shop selection and the webservice shop selection ever make it into a bugreport or PR?

**Pull request merged**
