### PR TITLE
Add PHP 7.1 as optional on Travis

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | PHP 7.1 is now available from a few months. It's time to include it in the tests matrix. Eventually, it can replace PHP 7.0.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
Good thing @Quetzacoalt91 Do you want to fix 7.1 tests ? or we can merge it ?

**Comment by Quetzacoalt91** [comment]
I will have a look on them first

**Comment by Quetzacoalt91** [comment]
Test related to deprecated features is marked as skipped.

For the errors related to CSS minify, a PR has been opened on the repository: https://github.com/mrclay/minify/pull/600

**Comment by aleeks** [comment]
@Quetzacoalt91 can we merge it and we are waiting for minify ?

**Comment by Quetzacoalt91** [comment]
Let's go for it!

**Comment by aleeks** [comment]
Thank you @Quetzacoalt91

**Pull request merged**
