### PR TITLE
Add concat space

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11646)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Not sure we can accept this PR without updating the cs fixer configuration.
@mickaelandrieu @matks wdyt?

**Comment by mickaelandrieu** [comment]
Hi @MathiasReker,

adding PHP Cs Fixer configuration is really recent and we have already a lot of our contributors' contributions "stuck" because of this. I think it's too soon in the process to make the validation more "strict", maybe in the next minor version?

ping @eternoendless

**Comment by eternoendless** [comment]
While I'm personally in favor of using spaces around the concat operator, we have [chosen](https://devdocs.prestashop.com/1.7/development/coding-standards/#php-code-conventions) to follow the [Symfony standards](https://symfony.com/doc/current/contributing/code/standards.html#structure), which state:

> Add a single space around binary operators (==, &&, ...), **with the exception of the concatenation (.) operator**;

Due to this, we can't enforce a space around it. But we can leave it up to the developer to choose by not enforcing it through cs-fixer rules.

**Comment by MathiasReker** [comment]
I understand :)

**Pull request closed without merging**
