### PR TITLE
Sets the current date on the duplicate product

### LINKED ISSUE #34079: date_add field not updated when duplicating a product
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you duplicate a product, its date_add field is not updated and remains the same as the original product. It causes missing "New" labels and the product is not listed on the New Products page.

### Expected behavior

When duplicating a product, the new product's date_add should be duplication datetime.

### Steps to reproduce

1. Go to the product listing.
2. Duplicate a product using the bulk action.
OR
1. Go to the product view/edit page of any product.
2. Duplicate the product.

3. Check date_add of newly created product(s) directly from database - they have the original product's date_add values.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by webeshop**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Sets the current date on the duplicate product.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Duplicate product in backoffice.
| UI Tests | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/8833916879
| Fixed issue or discussion?     | Fixes  #34079

### CODE REVIEW

**Comment by nicosomb** [comment]
⚠️  there is an other pull request to fix this bug: https://github.com/PrestaShop/PrestaShop/pull/34826

**Review by Codencode — APPROVED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Comment by nicosomb** [comment]
UI tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/7208891924

**Review by M0rgan01 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by jolelievre** [comment]
Thanks @webeshop 
The fix is legit but to validate this new business rule and avoid regression it should also be tested by behat tests, improving our behat test as we discover bugs is the best way to keep our code base sane Do you think you would be able to add those?

**Comment by florine2623** [comment]
Friendly reminder @webeshop ^^
Could you answer @jolelievre ?

**Comment by Hlavtox** [comment]
@jolelievre @MatShir I don't think it's worth it to block this PR because of the tests, please.

I have complains from my clients about this after upgrade, it's quite important, products are not showing as new...

**Comment by Hlavtox** [comment]
@webeshop Can you please rebase the PR to 8.1.x branch?

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@florine2623 Ready to test. ;-)

I am running this exact fix on production since 8.1.5 and it works perfectly.

**Comment by Hlavtox** [comment]
UI tests - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/8833916879

**Review by ShaiMagal — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @webeshop ,

Tested duplicating the product from option in product listing, from bulk action, from option on product page.

Works as expected ! It is QA ✅ 
Thanks!

**Review by jolelievre — APPROVED** [review]
Thanks @webeshop

**Pull request merged**
