### PR TITLE
Fix maximum compatible PHP version and error wordings

### LINKED ISSUE #20842: Maximum PHP compatible version is confusing
#### Describe the bug

When you try to install PrestaShop using PHP 8, you will get an error message saying that your version is not supported, like this:

Screencap

The message has been updated since to account for compatibility with PHP 7.4 and it now reads: 

> PrestaShop requires at most PHP 7.5.0 or fewer versions. To install PrestaShop 1.7.8.0 you need to downgrade your version of PHP.

There are a couple problems with this wording:

1. There is no, and probably never will be, a PHP version 7.5
2. It misleads the reader into thinking that PrestaShop will work with PHP 7.5
3. There is a mistake in the wording: "or fewer versions". The right word is "lower".

#### Expected behavior

1. The message should be replaced by this one: 
    > "Your server is running PHP {CURRENT_VERSION}, but PrestaShop requires PHP 7.4 or lower. To install PrestaShop 1.7.8.0 you need to downgrade your PHP version." 
    
    _Note how the maximum version does not include patch releases._
2. I should be able to install PrestaShop with any patch version of PHP 7.4.x

I suggest configuring it as follows:

```php
define('_PS_INSTALL_MAXIMUM_PHP_VERSION_ID_', 70499);
define('_PS_INSTALL_MAXIMUM_PHP_VERSION_', '7.4');
```

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The maximum version was wrong in the installer and it wouldn't work with PHP 7.4.1 and subsequent releases
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20842.
| How to test?  | Try to install with PHP 8 and with PHP < 7.1

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20843)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by PululuK** [comment]
In this case it is necessary to update PHP compatibility chart or not  ?

image
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

**Comment by eternoendless** [comment]
@PululuK for 1.7.8 yes!

Done here https://github.com/PrestaShop/docs/pull/702

**Comment by PululuK** [comment]
> @PululuK for 1.7.8 yes!
> 
> Done here [PrestaShop/docs#702](https://github.com/PrestaShop/docs/pull/702)

Thank you !

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

PHP = 5.6.40 When we try to install PrestaShop with CLI, The message is not updated
5 6_cli

When installing via Web => ok


PHP8.0.0 When we try to install PrestaShop with CLI, The message is not updated
8 0_cli
When installing via Web => ok
8 0_web

Thanks!

**Review by PierreRambaud — DISMISSED** [review]

**Comment by MatShir** [comment]
@eternoendless check @khouloudbelguith comment pls :)

**Comment by PierreRambaud** [comment]
Should be better right now: 
image

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
We have a problem with behat tests (on every PRs)

Edit: you can rebase the PR now

**Comment by PierreRambaud** [comment]
PR has been rebased

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @eternoendless,

It is ok :heavy_check_mark: 
**PHP5.6**
1. Via Web 
php5 6web
2. Via CLI 
php5 6cli

**PHP8**
1. Via Web 
ph8web
2. Via CLI 
php8cli


**PHP 7.4**
1. Via Web => ok 
image
2. Via CLI => ok 
php7 4cli

**PHP7.2** via web => ok
image

Thank you!

**Comment by PierreRambaud** [comment]
Thank you @eternoendless

**Pull request merged**
