### PR TITLE
Remove deprecated code in CmsCategory

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in CmsCategory
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `CmsCategory::searchByNameAndParentCMSCategoryId()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26305)

### CODE REVIEW

**Review by tegbessou — APPROVED** [review]
Thank you for this PR!
IMO it's good

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaEdit Could you document the BC Break, please ?

**Comment by PrestaEdit** [comment]
Hi,

Not able to document it, it's a BC break as we remove code. Likely other PR having deprecated removed code, it will BC break existing modules using them, isn't it ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @PrestaEdit

**Pull request merged**
