### PR TITLE
Demo products

### PR DESCRIPTION
**Pull request by toutantic**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Our demonstration "products" have been here for a long time it's time to replace them.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/FF-163
| How to test?  | install prestashop, open the front office you should see t-shirts, frame and mugs

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8739)

### CODE REVIEW

**Comment by alegout** [comment]
Reviewed 681 of 683 files at r1, 1 of 2 files at r2, 16 of 255 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8739)*

**Review by alegout — DISMISSED** [review]
Thank you!

**Comment by alegout** [comment]
Reviewed 11 of 12 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8739)*

**Review by alegout — DISMISSED** [review]

**Comment by alegout** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8739)*

**Review by alegout — APPROVED** [review]
:+1:

**Comment by eternoendless** [comment]
Thank you @toutantic

**Pull request merged**
