### PR TITLE
fix test feature

### PR DESCRIPTION
**Pull request by ntiepresta**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x 
| Description?  | Fix selector and add click on feature subtab
| Type?         | refacto 
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | TEST_PATH=full/05_feature/* npm run specific-test -- --URL=shopURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13565)

### CODE REVIEW

**Review by mbadrani — APPROVED** [review]
This PR well fixes the Test, thank you Reddy

**Comment by Quetzacoalt91** [comment]
Looks like PrettyCI does not pass because of files you did not modify. Rebasing your branch on 1.7.6.x may solve the issue.

**Comment by ntiepresta** [comment]
Yes, @Quetzacoalt91, I saw it. 
Thanks

**Comment by ntiepresta** [comment]
This link or Pr https://github.com/PrestaShop/PrestaShop/pull/13581, solves the PrettyCI problem of this Pr
Thanks

**Comment by PierreRambaud** [comment]
Why you're not fixing it in this PR? 🤔

**Comment by ntiepresta** [comment]
Hello, @PierreRambaud , I have chosen fixed with a new Pr, because, I had important conflict on my branch
Thanks

**Comment by PierreRambaud** [comment]
So you can close this one maybe?

**Comment by ntiepresta** [comment]
@PierreRambaud , OK

**Pull request closed without merging**
