### PR TITLE
Add migrated customers page helper card

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add Helper Card for Customers page
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes one of the items of https://github.com/PrestaShop/PrestaShop/issues/10434. This ticket is one item of the todo-list for https://github.com/PrestaShop/PrestaShop/issues/10559
| How to test?  | See fixed ticket. **Please rebuild assets before testing**. SF page is hidden but available at `/admin-dev/index.php/sell/customers/`

**For reviewers:** please especially check my CSS (https://github.com/PrestaShop/PrestaShop/pull/12128/files#diff-0ab3df9c1621650559b62fba8338eaa4R14) as I am not confident in it

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12128)

### CODE REVIEW

**Comment by matks** [comment]
This is what it looks like:
capture d ecran 2019-01-11 a 22 05 00

**Comment by matks** [comment]
@TristanLDD Please have a look at this helper card 😉

**Comment by TristanLDD** [comment]
Hello @matks !

The helper card looks good, expect one detail, it seems like the shape behind the illustration is cut: 

capture d ecran 2019-01-14 a 10 16 16

Expected:
capture d ecran 2019-01-14 a 10 16 34

Could you integrate the little animation on display like the SEO helper card ? 
Thank you :)

**Comment by matks** [comment]
@TristanLDD animation is on ✅ and background shape is now fit:
capture d ecran 2019-01-14 a 11 22 45

**Comment by TristanLDD** [comment]
@matks Thanks, that's perfect now ! 👍 
One last thing I'm thinking about: we agreed that the helper card will disappear definitely when the user closes it instead of re-appearing every time the page is charged. 

In a second time we would like to add the possibility to re-view the cards when closed, and to ensure that when a card is close by a certain profile of user it's still open for the other profiles.

**Comment by matks** [comment]
@TristanLDD This behavior is being implemented in https://github.com/PrestaShop/PrestaShop/pull/12111 😉

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by marionf** [comment]
Not sure if the display is correct in RTL, @TristanLDD wdyt ?

capture d ecran_915

Otherwise, it's all good

**Comment by marionf** [comment]
Same thing for the Team page:

capture d ecran_916

It's ok on SEO & Urls:

capture d ecran_917

**Comment by TristanLDD** [comment]
Indeed the display seems broken in RTL for Customers and Team pages, it should be like SEO & Urls page. 

But for optimal display, the grey shape behind the illustration should be mirrored as well: 
capture d ecran 2019-01-15 a 11 55 18

Would it be possible to mirror this shape in RTL or is this behavior too specific ?

**Comment by matks** [comment]
@TristanLDD I enabled image flip for all helper card, background and images:
capture d ecran 2019-01-24 a 16 19 51
capture d ecran 2019-01-24 a 16 19 55
capture d ecran 2019-01-24 a 16 22 10

**Comment by TristanLDD** [comment]
@matks Great, thank you ! :)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by ntiepresta** [comment]
Hello,
In "Manage your customers" block, the social title "Mrs" is not correctly displayed in French.

Before 
francais ok

After, with this Pr

**Comment by marionf** [comment]
@ntiepresta it's also the case on develop branch and not due to this PR
If @TristanLDD wants, we could enlarge the gender field in another PR ?

**Comment by ntiepresta** [comment]
@marionf 
Thanks for your precision. I manage to reproduce the issue without this PR on develop branch
title confirm

**Comment by TristanLDD** [comment]
@marionf Cécile told me recently that she would like to delete this field from the customers table (along with 1 or 2 other low-value fields) so maybe we should wait ;)

**Comment by matks** [comment]
Rebased and rebuilt assets (this applies the 2019 license header)

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thank you for the reviews

**Pull request merged**
