### PR TITLE
[-] BO: Correct chosen-sprite.png link

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, thank you for your contribution but please include sass file with the change.
Kindly regards

**Comment by jeromenadaud** [comment]
you may also use ```compass compile --force --sourcemap``` in commande line and rebase your PR with las change on 1.6.1.x branch

**Comment by PrestaEdit** [comment]
Hi @jeromenadaud, the branch just changed with a 1.6.1.x rebase and Sass files.

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution.

Best regards

**Pull request merged**
