### PR TITLE
Happy new Year PrestaShop!

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Happy new Year PrestaShop!
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Happy new Year PrestaShop!

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
prestonbg

😎

**Comment by antoin-m** [comment]
image

**Comment by aleeks** [comment]
Rebased

**Comment by maximebiloe** [comment]
Happy new year too @aleeks 🎉

**Pull request merged**
