### PR TITLE
feat(DbCore): Add getColumn function

### PR DESCRIPTION
**Pull request by Kaikina**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Add a new helper function to the DbCore class that fetches a column from a sql result set. We currently have getValue, getRow, getColumn is a good helper as well.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Execute a SQL query in a script calling getColumn and expects an array of the values of mentioned column.
| UI Tests          | NA
| Fixed issue or discussion?     | NA
| Related PRs       | NA
| Sponsor company   | Evolutive

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
Since using `SELECT *` is considered a bad practice, and the only abstraction inside the function is to use `array_column` with the query result, I don't see much value in this change.

Let's see what other committers think.

**Comment by Kaikina** [comment]
> Since using `SELECT *` is considered a bad practice, and the only abstraction inside the function is to use `array_column` with the query result, I don't see much value in this change.
> 
> Let's see what other committers think.

Select * is just an example. It could be "select id_product". I get that it doesn't provide much value. 
It just seemed "logical" to me, to have getRow, getValue, and getColumn as well, since I had done this operation many times in the past.

**Comment by kpodemski** [comment]
@Kaikina 

still, do you think having a wrapper around `array_column` is worth it? :)

**Comment by Kaikina** [comment]
I do, and I do understand not everyone think the same.

**Review by Hlavtox — COMMENTED** [review]
I will pass on this one. I don't think it has much value. Basically, it only saves one line of array_column.

And having this available from v9, nobody will use it anyway.

**Comment by kpodemski** [comment]
@Kaikina 

You know what, I don't mind seeing it in the core, to be honest, but in order to benefit from it more, could you rebase on `9.0.x`? at least it would be available starting v9, not v9.1 👌🏻

**Pull request closed without merging**
