### PR TITLE
[-] CORE : Adding missing method to make method HookExtension::render…

### PR DESCRIPTION
**Pull request by FabienSerny**
Please take the time to edit the "Answers" rows with the necessary information:

| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | The method "renderHooksArray" in class "HookExtension" is making this call "$this->moduleDataProvider->getModuleName($module)" but there was no such function in the class ModuleDataProvider |
| Type? | bug fix |
| Category? | CORE |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | / |
| How to test? | The function "renderHooksArray" is only used for one hook "displayAdminProductsExtra". Currently, if you attach a module to this hook, the admin product form does not display anymore. This PR fix the bug |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [the PSR-2 Coding Style](http://doc.prestashop.com/display/PS16/Coding+Standards)!
- Your commit MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)

…HooksArray works

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hi @FabienSerny,

Good to see you back!
@Quetzacoalt91 and @tchauviere can you look at this?

Regards

**Comment by Quetzacoalt91** [comment]
Hi,

Okay, we need this function in the ModuleDataProvider. However, we have from PrestaShop 1.7 a new class Module inserted in the `Adapter` namespace.

We should check which object we have here, and if this is the new Module Class, we need to get inside it the link to the legacy instance.

Regards

**Comment by FabienSerny** [comment]
Hi,

I saw that there is a new Module class name.
However, you're already Using "\Module" everywhere in the class "ModuleDataProvider", that's why I choose to use it.

Best regards,
Fabien

**Comment by Quetzacoalt91** [comment]
Actually I'm using the class `\Module` by calling its methods, but in general I'm just sending a string as a parameter in order to work with both classes.

Of course, we won't have a string here because we are asking for it, but if someone send the wrong object (i.e an instance of `PrestaShop\PrestaShop\Adapter\Module\Module`), this won't work. The objective is to use the new class, that's why I would add a check.

If we have the other class, we could adapt the function like this:

```php
    public function getModuleName($module)
    {
        if ($module instanceof PrestaShop\PrestaShop\Adapter\Module\Module) {
            return \Module::getModuleName($module->getInstance());
        }
        return \Module::getModuleName($module);
    }
```

**Comment by FabienSerny** [comment]
Okay, I see what you meant.

However, I might be wrong but $module->getInstance() won't return the module name.
It should be $module->getInstance()->name, right ?

The problem you're talking about exists in other methods of this class : 
- method "can"
- method "isEnabled"
- method "isInstalled"
- method "findByName" (okay maybe not this one)
...

We should do the same check on all these methods, right ?

**Comment by Quetzacoalt91** [comment]
You're right, it does not return the module name. However, it return the legacy class `\Module` to send `\Module::getModuleName(...)`.

And about the problem you're describing ... I do not see what's wrong. I never instanciate a `\Module` object, I just use the static functions. The parameter of these functions is a string, as described in the PHP doc, that's why we do not require the check for them.

**Comment by FabienSerny** [comment]
> You're right, it does not return the module name. However, it return the legacy class \Module to send \Module::getModuleName(...).

Maybe we're not talking of the same thing, you wrote : 
`return \Module::getModuleName($module->getInstance());`
\Module::getModuleName() is waiting for a string as parameter
$module->getInstance() return a class \Module
So correct me if I'm wrong, but there will be an issue there, right ?
(I had only a few hours of sleep, so maybe I'm missing something there :p )

> And about the problem you're describing ... I do not see what's wrong. I never instanciate a \Module object, I just use the static functions. The parameter of these functions is a string, as described in the PHP doc, that's why we do not require the check for them.

There are no PHP Doc for methods IsEnabled, isInstalled, ... in class ModuleDataProvider.
So as for getModuleName, it could be an instance of \Module. What do you think ?

**Comment by Quetzacoalt91** [comment]
AAAAAAAH ok ! I got it !

So you're right, we do not require additional test here. The parameter name is not explicit at all and will require a small explanation.

Thanks

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 go for merge then ? :)

**Comment by Quetzacoalt91** [comment]
Yep, and I will add the PHP doc for this function.

Thanks for your contribution @FabienSerny

**Comment by FabienSerny** [comment]
Thanks :)
And you're right, the parameter name is not explicit at all.
I just used the same parameter name used in \Module::getModuleName()
Next time, I'll try to be more accurate  :)

**Pull request merged**
