### PR TITLE
Merge 8.0.x to develop

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Merge 8.0.x to develop 
| Type?             | improvement
| Category?         | ME 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by lartist** [comment]
Automatic test link https://github.com/lartist/ga.tests.ui.pr/actions/runs/3542151827

**Review by matthieu-rolland — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Comment by lartist** [comment]
New automatic test run https://github.com/lartist/ga.tests.ui.pr/actions/runs/3542716551

**Review by jolelievre — DISMISSED** [review]
Thanks @lartist

**Review by matks — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]
🔥 👍

**Comment by lartist** [comment]
A new commit which consist to merge 8.0.x into this PR branch to add @Progi1984 fix regarding the nightly.
This is the new run https://github.com/lartist/ga.tests.ui.pr/actions/runs/3546409099

**Review by jolelievre — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by zuk3975** [comment]
> A new commit which consist to merge 8.0.x into this PR branch to add @Progi1984 fix regarding the nightly. This is the new run https://github.com/lartist/ga.tests.ui.pr/actions/runs/3546409099

everything finally green :tada:

**Comment by lartist** [comment]
> > A new commit which consist to merge 8.0.x into this PR branch to add @Progi1984 fix regarding the nightly. This is the new run https://github.com/lartist/ga.tests.ui.pr/actions/runs/3546409099
> 
> everything finally green 🎉

Yes @matks plz force merge :)

**Comment by Progi1984** [comment]
@lartist Please wait : the Nightly currently run on this PR.

**Comment by Progi1984** [comment]
The CI is now :green_circle:

**Comment by lartist** [comment]
> @lartist Please wait : the Nightly currently run on this PR.

Everything was already green :)

**Comment by matks** [comment]
> @lartist Please wait : the Nightly currently run on this PR.

Sorry I think you wrote the message at the moment I clicked ^^

**Pull request merged**
