### PR TITLE
Adding constants for configurations

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | First implementation for ADR https://github.com/PrestaShop/ADR/pull/16
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes / no
| Deprecations?     | yes / no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22672)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
I personally fu**ng love it, but I think putting it in Adapter\Configuration or in a new Configuration class could be better.
Wdyt @matks?

**Comment by PierreRambaud** [comment]
HI @JevgenijVisockij 
What's the state of the ADR? Are you planning to working on it?

**Comment by matks** [comment]
> HI @JevgenijVisockij What's the state of the ADR? Are you planning to working on it?

I'm afraid that we were not able to get maintainers team attraction on https://github.com/PrestaShop/ADR/pull/16 :/ and without ADR we cant merge this PR.

**Comment by PrestaEdit** [comment]
As this was closed 28 days ago, related to the ADR, maybe this PR need to be closed too, isn"t it ?

**Comment by matks** [comment]
> As this was closed 28 days ago, related to the ADR, maybe this PR need to be closed too, isn"t it ?

Indeed.

Sad ending :( but this PR could be reopened in the future if we can get the ADR discussion back on track.

**Pull request closed without merging**
