### PR TITLE
Merge `8.0.x` into `8.1.x`

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Merge `8.0.x` into `8.1.x`
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI ✅ & [auto tests](https://github.com/boherm/ga.tests.ui.pr/actions/runs/5197424830) ✅.
| Fixed ticket?     | n/a
| Related PRs       | n/a
| Sponsor company   | PrestaShop

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Comment by nicosomb** [comment]
@boherm some tests are red. Is that related to this PR?

**Review by matks — DISMISSED** [review]
All checks green now ✅

**Review by Progi1984 — CHANGES_REQUESTED** [review]
UI Tests are broken.

Please update your repository `ga.tests.ui.pr` and restart UI tests.

**Comment by boherm** [comment]
@Progi1984 Let's go: https://github.com/boherm/ga.tests.ui.pr/actions/runs/5197424830 🚀

**Review by kpodemski — DISMISSED** [review]

**Comment by Progi1984** [comment]
@boherm You reverted changes from 8.0.x branch : https://github.com/PrestaShop/PrestaShop/pull/32829

=> That create an error : https://github.com/boherm/ga.tests.ui.pr/actions/runs/5197424830/jobs/9375286582

**Comment by boherm** [comment]
@Progi1984 Oops! I didn't stage all changes... 😅 
It's done, I restart tests.

**Comment by boherm** [comment]
All green! 🚀

**Review by Progi1984 — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by boherm** [comment]
@PrestaShop/qa-automation @PrestaShop/qa-functional Are you ok to merge this PR? 😊

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
I approve for the @PrestaShop/qa-automation team. Need @boubkerbribri approval.

**Review by boubkerbribri — APPROVED** [review]
LGTM for UI tests but as discussed with @PrestaShop/qa-functional , this PR will need further checks to unsure that nothing was broken with these smarty updated (So I will let `waiting For QA`)

**Review by florine2623 — APPROVED** [review]
Hello @boherm ,

I did some exploratory tests on :

- Upload a theme
- Upload a module
- Creation of a product
- Checkout process
- Products list in BO

And tested these PR in particular https://github.com/PrestaShop/PrestaShop/pull/32790 and https://github.com/PrestaShop/PrestaShop/pull/32715.

It is looking good to me and QA ✅ 
Thanks!

**Pull request merged**
