### PR TITLE
Files from translations folder can not be accessed

### PR DESCRIPTION
**Pull request by idnovate**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Files from this folder are accessed when edit a product and error 403 appear
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Edit a product. 403 will appear in console.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9474)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
ping @PierreRambaud, wdyt?

**Comment by idnovate** [comment]
Error

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Agreed, don't find any files that need to be protected!

**Comment by Quetzacoalt91** [comment]
Thank you @idnovate

**Pull request merged**
