### PR TITLE
Fixed installation screen when some config keys were missing

### LINKED ISSUE #28649: Fallback when some details are missing for a theme during install
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I just tried reinstalling my shop on which I have another theme I quickly made a long time ago. It was only to explain how the child feature works, and I didn't take the time to add a preview image or the version in the `theme.yml`.

Because these details are missing, the theme takes a lot of space for nothing: Image link broken & no version displayed.

image

### Expected behavior

- For the preview: Either displaying a fallback image 
image

- For the version: displays `N/A` (Admin.Global)

### Tech investigation 

- [ ] Check how do we test with proper child theme

### Steps to reproduce

I think you can quickly reproduce this issue by duplicating the `classic` theme, then remove the file preview.png and the version in the yml file

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | If some configuration keys are missing in the `theme.yaml`, the display was buggy. 
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28649
| Related PRs       | 
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/28649
| Possible impacts? | 

Before 

171445162-6430c57d-362b-4be7-93d7-6b47cbfd10db

After

Capture d’écran 2022-09-12 à 10 59 19

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
Looks like your PR breaks unit tests in `tests/Unit/Core/Theme/ConfigReaderTest.php`

**Review by kpodemski — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by hibatallahAouadni — DISMISSED** [review]
Hello @nicosomb 

Thanks for you PR :rocket: 
LGTM, QA :heavy_check_mark: 

https://user-images.githubusercontent.com/23308427/191568610-610d9730-26c6-4c07-9107-dd2c8ba04447.mp4

Thanks!

**Comment by matks** [comment]
Thank you @nicosomb

**Comment by nicosomb** [comment]
FYI, I changed the destination branch to target `8.0.x`. 

@matks Could you relaunch the QA process please?

**Review by ghost — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @nicosomb 

Thanks for you PR :rocket: 
LGTM, QA :heavy_check_mark: 

https://user-images.githubusercontent.com/23308427/191568610-610d9730-26c6-4c07-9107-dd2c8ba04447.mp4

Thanks!

**Comment by matks** [comment]
Thank you @nicosomb

**Pull request merged**
