### PR TITLE
Set the statistics controller as ajax

### LINKED ISSUE #27449: [Improvement] The Statistics controller is generation noise at the server logs
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The Statistics controller should be mark as ajax to prevent the unnecessary code execution and unnecessary logging as the core tries to process smarty templates for the requests.

### Expected behavior

Navigating the frontend should collect the users information but shouldn't log errors nor warnings of invalid or unassigned templates on the server related to the statistics requests.

### Steps to reproduce

(with the php and server logs enabled)
1.- Navigate the front end
2.- Confirm that the user was tracked by PS
At the server logs you will notice errors about $template being missing. This is because the controller tries to parse a template that is not defined because is actually an ajax controller.

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

7.4.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Guisardo**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The Statistics controller should be mark as ajax to prevent the unnecessary code execution and unnecessary logging as the core tries to process smarty templates for the requests.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27449.
| How to test?      | Navigating the frontend should collect the users information but shouldn't log errors nor warnings of invalid or unassigned templates on the server related to the statistics requests.
| Possible impacts? | No secondary impacts.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27448)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi !

Please see the discussion in https://github.com/PrestaShop/PrestaShop/issues/20921 -> @rsoulard-prolaser wanted to fix the bug with PR https://github.com/PrestaShop/statsdata/pull/20

**Comment by Guisardo** [comment]
Hi @matks ! thanks for the support.
The PR that you mention only fixes part of the problem. If the request is successfully made to the controller, the controller (at the frontcontroller core class) still tries to parse template for through "display" if it is not marked as an ajax controller.

**Comment by rsoulard-prolaser** [comment]
Hi @Guisardo,

The PR add a variable "ajax" send to the controller and so the function "display" is not called.

**Comment by Guisardo** [comment]
You are right @rsoulard-prolaser Thanks for the clarification! Lets push that PR then.
Best,

**Pull request closed without merging**
