### PR TITLE
Remove default theme schemes (no longer used)

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Removed default theme schemes, which are no longer used
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Editing an employee profile should work as before

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8927)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Careful, code deletion should be for the minor version, just in case. `Improvement` is also a reason to not put that in a patch version :)

**Comment by eternoendless** [comment]
When you are right, you are right, I'll rebase onto develop

**Comment by LittleBigDev** [comment]
Some conflicts need to be resolved

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8927#-:-LAIou70DUPB_NJ-wght:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]
Thanks @eternoendless 
Some conflicts need to be resolved though

**Comment by eternoendless** [comment]
Rebased

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @eternoendless

**Pull request merged**
