### PR TITLE
[-] BO: Add custom.js in backend and backend login

### PR DESCRIPTION
**Pull request by guestisp**
Add a custom `custom.js` file to allow customization of backend

### CODE REVIEW

**Comment by guestisp** [comment]
Any issue with this ? Adding a custom JS can be useful, like with `overrides.css`

**Comment by guestisp** [comment]
Is possible to merge this ? We would like to make some changes in admin theme without copying the whole directory for upgrade purposes.

**Comment by jeromenadaud** [comment]
Hi,

thank you for your PR, I have just created a new hook in AdminLoginController for your needs,

Please see : https://github.com/PrestaShop/PrestaShop/pull/2765

Now you can directly hook a module on ```actionAdminLoginControllerSetMedia``` and ```actionAdminControllerSetMedia``` in order to add a custom js.

Best regards.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
Closing this PR since Jérôme's #2765 seems to be solving your issue.

**Pull request closed without merging**
