### PR TITLE
Fix deprecated function usage

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This function is deprecated
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | CI 🟢 & automated tests

### CODE REVIEW

**Comment by FabienPapet** [comment]
Automated tests : https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4015705354

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@FabienPapet I think you need to rebase your `ga.tests.ui.pr` repo because tests failed

**Review by matthieu-rolland — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

**Comment by jolelievre** [comment]
Just launched another campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4017591856

**Pull request merged**
