### PR TITLE
Improved readability

### PR DESCRIPTION
**Pull request by michaelKaefer**
According to https://stackoverflow.com/questions/23758916/psr-2-standard-for-long-if-conditions?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa PSR-2 does suggest anything but anyway this hopefully improves readability

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Reformatted an if condition to improve readability
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | No additional tests needed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8970)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
@michaelKaefer filling a complete pull request description is required: thanks for your understanding.

**Comment by michaelKaefer** [comment]
@mickaelandrieu I edited the table, is it ok? It's my first pull request for PrestaShop. - Can you also tell me why the Travis build failed and if that is a problem? I'd like to know about this for further pull requests. Thank you

**Comment by mickaelandrieu** [comment]
@michaelKaefer great, thanks 👍 

we have some timeout issues these days on Travis, I relaunch the build this should be good now.

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks for this first contribution @michaelKaefer!

**Pull request merged**
