### PR TITLE
Fix Incorrect count of the quantity of a customized product in the cart.

### LINKED ISSUE #32233: Incorrect count of the quantity of a customized product in the cart.
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If an product has 3 available quantities and has a text field for customization (not mandatory), by adding the customized product to the cart, it is also possible to add 3 non-customized ones.
This occurs because the system for calculating the quantity of the item in the cart does not count the customization.
I attach a video

https://user-images.githubusercontent.com/2463965/233431462-45f4394d-ca31-4241-ba3f-2a00e6ff6207.mp4

https://user-images.githubusercontent.com/2463965/233431471-9646ac18-0fea-4a40-8979-f18afcb3687b.mp4

https://user-images.githubusercontent.com/2463965/233431476-9fc0336a-541a-4db2-97ec-9483547c86a3.mp4

### Expected behavior

The system should add a maximum of 3 quantities of the article, thus also verifying the personalized article

### Steps to reproduce

In a fresh installation of Prestashop:
1. Modify article ID 19 by setting quantity 3 and setting the non-mandatory customization field (Options > Customization tab).
2. Go to the product in fronoffice.
3. Fill the personalization field.
4. Save customization.
5. Add the newly customized product to cart.
6. Add 3 quantities of the product (non-customized) to the cart.
7. At this point we have 4 units of item ID 19 in the cart when there are only 4 available.

### PrestaShop version(s) where the bug happened

1.7.x 8.0.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x 
| Description?      | If an product has 3 available quantities and has a text field for customization (not mandatory), by adding the customized product to the cart, it is also possible to add 3 non-customized ones.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #32233

### CODE REVIEW

**Comment by kpodemski** [comment]
I'll ping @unlocomqx who has a lot of knowledge around customizations in PrestaShop :)

**Comment by unlocomqx** [comment]
Hi @Codencode, thank you for your contribution

I think it's better to make the default value of the `id_customization` as false, then when it's false, avoid the checks. 

Then in the Cart::updateQty, you need to read both the product quantity and the customization quantity because 

If you're not very familiar with the logic, I can take over and create another PR if you'd like

Cheers

**Comment by Codencode** [comment]
> Hi @Codencode, thank you for your contribution
> 
> I think it's better to make the default value of the `id_customization` as false, then when it's false, avoid the checks.
> 
> Then in the Cart::updateQty, you need to read both the product quantity and the customization quantity because
> 
> If you're not very familiar with the logic, I can take over and create another PR if you'd like
> 
> Cheers

Hi @unlocomqx,

Your solution is not very clear to me.
you can try to give me some additional information or you can create a new PR as you surely know this part more than me

Thank you

**Comment by unlocomqx** [comment]
@Codencode I will submit a PR as soon as possible

Cheers

**Comment by unlocomqx** [comment]
@Codencode @kpodemski I created this PR to fix the issue

https://github.com/PrestaShop/PrestaShop/pull/32312

It's still wip as other checks and refactorings need to be made

I used the [$id_customization = false](https://github.com/PrestaShop/PrestaShop/pull/32312/files#diff-a1349548e1b4f0f9e9bda744305bba472b6cb9d887572fa1bcb9498f401e5fb7R1393) "convention" to signify that we want to get the quantity with and without customizations.

**Comment by Codencode** [comment]
> @Codencode @kpodemski I created this PR to fix the issue
> 
> #32312
> 
> It's still wip as other checks and refactorings need to be made
> 
> I used the [$id_customization = false](https://github.com/PrestaShop/PrestaShop/pull/32312/files#diff-a1349548e1b4f0f9e9bda744305bba472b6cb9d887572fa1bcb9498f401e5fb7R1393) "convention" to signify that we want to get the quantity with and without customizations.

Thanks @unlocomqx for the PR!
Now your solution is clear to me, in fact it was enough to check the `id_customization `parameter with `!== false.`

However in the `Cart::getProductQuantity()` method I delete the first statement:
`$productIsPack = Pack::isPack($idProduct);`

because the variable `$productIsPack` is not used in the method.

**Comment by Codencode** [comment]
@unlocomqx I tested the changes you proposed in the PR [#32312](https://github.com/PrestaShop/PrestaShop/pull/32312) and it seems that it works correctly.

**Comment by unlocomqx** [comment]
@Codencode Thanks for checking

I removed the unused variable

**Comment by kpodemski** [comment]
I'm closing in favor of #32312 

thank you for cooperating, guys!

**Comment by unlocomqx** [comment]
Thank you @Codencode, the PR was merged https://github.com/PrestaShop/PrestaShop/pull/32312

**Pull request closed without merging**
