### PR TITLE
CO: Bad Siret Validation BOOM-3955

### PR DESCRIPTION
**Pull request by Max84**
Branch: develop
Description: Bug fix for BOOM-3955 report. isSiret validation method is buggy with empty value.
Type: bug fix
Category: CO
BC breaks: no
Deprecations: no
Fixed ticket: http://forge.prestashop.com/browse/BOOM-3955
How to test: Try to update a customer throw webservice. With patch you can update it, even Siret field is empty, like all other fields.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8516)

### CODE REVIEW

**Comment by tomlev** [comment]
Thx @Max84 
It would be better to check empty siret before method call. Its name is "isSiret", so an empty siret is not valid.

**Review by tomlev — CHANGES_REQUESTED** [review]
Thx @Max84
It would be better to check empty siret before method call. Its name is "isSiret", so an empty siret is not valid.

**Comment by Max84** [comment]
Hi @tomlev

I'm not agree with you. Check other Validate methods. These other methods accept empty value ( isAddress, isGenericName, etc ...).
Not all methods, but a lot of them.

These other methods can have wrong.
So check too Customer object. Siret is not a required field, so it can be empty.
You can't define into customer object siret field as not required and don't allow empty value.

into Customer class, i found this:
'siret' => array('type' => self::TYPE_STRING, 'validate' => 'isSiret'),

Datatype is defined by class definition.

What do you think about this ?

Best regards,
Maxime

**Comment by Quetzacoalt91** [comment]
Actually, we removed the siret check for the Customer class from 1.7.2.0, because it was a specific check for French companies.
See https://github.com/PrestaShop/PrestaShop/commit/2ec89e7b26b198a3831ed36e1b399f7204757a36

This function is still used by the modules, that's why we kept it. But it requires to be filled, indeed.

**Comment by Max84** [comment]
Hi @Quetzacoalt91

Ok, i understand. If you'll merge https://github.com/PrestaShop/PrestaShop/commit/2ec89e7b26b198a3831ed36e1b399f7204757a36
you shouldn't merge mine. Or don't use first one and merge mine.
As you want !

Best regards,

**Comment by Quetzacoalt91** [comment]
The first one has been already merged, and is available from PS 1.7.2.0 :)

**Comment by Max84** [comment]
All right, i close this !

**Pull request closed without merging**
