### PR TITLE
Correcting Birthday validation

### PR DESCRIPTION
**Pull request by marwein**
i have got True using your isBirthDate with 2020-11-11 , and it's complicated and long using and / OR, so i tryed to simplify this and to correct this bug, the only case when it will be valid is : day <= day('d') AND Month >= date('m') AND Year <= date('Y'), so we accept birthday until (today)

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR, can you please close it and make it again on 1.6.1.x branch.

Can you please convert your code to PSR2 norm ? an please a quick look to http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Thank you.

Best regards

**Comment by marwein** [comment]
yes, will do every thing well and pull request on the 1.6.1. branch
thx

**Comment by gRoussac** [comment]
Hi,

"develop" branch would be ok for this. Just try amending your commit message.

Regards

Regards

**Comment by PrestaEdit** [comment]
This will no work.

Imagine that we are on the:

18 october 2015 and that I want to valide a date like this one: 23 march 2014.

2014 is <= of 2015, it's ok.  3 <= 10, it's ok.

But 23 > 18. Last test will return false.
(It's the same if you are on march and want to validate a birth date of october).

**Comment by marwein** [comment]
Hi, yes using those many if is so complicated. I changed my mind on my proejct and used your method, but i have added one line to correct this.
Imagine we are the 18 october 2015, and we choose a birthday 17 october 2016 
the year is > to date('Y') so we don't access the first second and third cases, OK
But if we choose the date 2016-09-01 as birthday your method return true

exemple to test :

```php
<?php
function isBirthDate_ps($date)
{
	if (empty($date) || $date == '0000-00-00')
        return false;
    if (preg_match('/^([0-9]{4})-((?:0?[1-9])|(?:1[0-2]))-((?:0?[1-9])|(?:[1-2][0-9])|(?:3[01]))([0-9]{2}:[0-9]{2}:[0-9]{2})?$/', $date, $birth_date))
    {
        if ($birth_date[1] > date('Y') && $birth_date[2] > date('m') && $birth_date[3] > date('d')
            || $birth_date[1] == date('Y') && $birth_date[2] == date('m') && $birth_date[3] > date('d')
            || $birth_date[1] == date('Y') && $birth_date[2] > date('m'))
            return false;
        return true;
    }
    return false;
}

function isBirthDate_me($date)
{
	if (empty($date) || $date == '0000-00-00')
        return false;
    if (preg_match('/^([0-9]{4})-((?:0?[1-9])|(?:1[0-2]))-((?:0?[1-9])|(?:[1-2][0-9])|(?:3[01]))([0-9]{2}:[0-9]{2}:[0-9]{2})?$/', $date, $birth_date))
    {
        if ($birth_date[1] > date('Y') && $birth_date[2] > date('m') && $birth_date[3] > date('d')
            || $birth_date[1] == date('Y') && $birth_date[2] == date('m') && $birth_date[3] > date('d')
            || $birth_date[1] == date('Y') && $birth_date[2] > date('m')
            || $birth_date[1] > date('Y'))
            return false;
        return true;
    }
    return false;
}

echo "2016-09-01 : " . ((isBirthDate_ps('2016-09-01'))?"Valid":"Invalid") . "<br/>" ;

echo "2016-09-01 : " . ((isBirthDate_me('2016-09-01'))?"Valid":"Invalid") . "<br/>" ;
?>
```
Result : 
```
2016-09-01 : Valid
2016-09-01 : Invalid
```

We need just to add a verification only for the year:
the first one return True, second False

**Comment by julienbourdeau** [comment]
Hi,

I'm just thinking out loud here, how about comparing timestamps with `strtotime()` ?

**Comment by marwein** [comment]
Hi,

It's a solution too, personaly i prefere using DateTime Tools and we can
convert a string to datetime too using
DateTime::createFromFormat(Y-m-d', '2015-10-19')

I used the DateTime format now

public static function isBirthDate($date)
{
    if (empty($date) || $date == '0000-00-00')
        return false;
    if
(preg_match('/^([0-9]{4})-((?:0?[1-9])|(?:1[0-2]))-((?:0?[1-9])|(?:[1-2][0-9])|(?:3[01]))([0-9]{2}:[0-9]{2}:[0-9]{2})?$/',
$date, $birth_date))
    {
        $now = new DateTime('NOW');
        $birthday = new DateTime($date);
        return (($now >= $birthday)?true:false);
    }
    return false;
}

it accepts birthdays until the same day.


Le lundi 19 octobre 2015, Julien Bourdeau <notifications@github.com> a
écrit :

**Comment by firstred** [comment]
Hi, 

Thank you for your pull request. It still looks like a good one to me.

Would you mind rebasing it? Thanks in advance!

**Comment by kpodemski** [comment]
@firstred i'm pretty sure that this was done in 1.7 already

**Comment by firstred** [comment]
Yep, indeed. This PR is no longer needed.

Thanks!

**Pull request closed without merging**
