### PR TITLE
bug fix - using the wrong func for checking exist

### PR DESCRIPTION
**Pull request by humpfreybogart**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

thank you for your PR. Which PHP version are you running please ? 

I get a Warning: property_exists() expects parameter 2 to be string, object given in classes/Customer.php on line 331

Reagrds

**Comment by jocel1** [comment]
Hi,

A proper fix would be to use the Tools::property_exists() function, for backward compatibility.

Best regards,

**Comment by gRoussac** [comment]
Hi,

Thank you. This function seems to be deprecated however.

Regards

**Comment by jocel1** [comment]
oh sorry, indeed :)

**Comment by michaelhjulskov** [comment]
it seems to be working for me... But how should I fix it then? I need getByEmail() to work

**Comment by michaelhjulskov** [comment]
Hello? Please

**Comment by michaelhjulskov** [comment]
By the way, I just realized that i made a typo in the PR.
should be
if (property_exists($this, $key))

**Pull request closed without merging**
