### PR TITLE
Update Mail::send documentation

### PR DESCRIPTION
**Pull request by mcdado**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update the documentation comment of method Mail::send().
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @mcdado,

Thank you for redoing your PR, but can you fill the mandatory table, please?
Even if it's a report, it's still required.

Regards

**Comment by aleeks** [comment]
Thank you @mcdado

**Comment by maximebiloe** [comment]
Luckily, @aleeks fill the table 😉

**Comment by asmadr** [comment]
Hello,
the function mail with $extraParams = '-f%s' not funcional in my sites if i change $extraParams = '%s' it work can you explain please. I can't change all my websites files. It's a server configuration?

Thank you

**Comment by mcdado** [comment]
@asmadr I think it's better if you ask in the forums for help: https://www.prestashop.com/forums/
Here the discussions are specific to the changes being made to the code, in this case the documentation comment before the `Mail::send()` method.

**Comment by asmadr** [comment]
@mcdado ok, think you

**Pull request merged**
