### PR TITLE
Fixes issue with cms category ordering in sitemap

### LINKED ISSUE #23168: CMS pages are not orders properly in sitemap
#### Describe the bug

CMS categories are not ordered correctly in sitemap page.

#### Expected behavior

They should be ordered correctly.

#### Steps to Reproduce

image

As found by @khouloudbelguith in https://github.com/PrestaShop/PrestaShop/pull/22476#issuecomment-773217278
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.8(develop)
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes issue with cms ordering
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23168 
| How to test?      | Create couple of cms categories, change their position and test that in sitemap their positions reflect the positions in BO.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23169)

### CODE REVIEW

**Comment by alfonsolr09** [comment]
i can't reproduce it on 1.7.6.4 
image
image

**Review by Progi1984 — DISMISSED** [review]
Please squash your last commits ;)

**Comment by Julievrz** [comment]
Hi! I can't see any wording in this PR. Am I missing something?🤔

**Comment by JevgenijVisockij** [comment]
> Please squash your last commits ;)

Done

**Comment by JevgenijVisockij** [comment]
> Hi! I can't see any wording in this PR. Am I missing something?thinking

There were some wording changes in accidentally added code, but that code was removed since then. Currently there is no wording in this PR.

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
Need rebase to fix behat tests

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

I found a trivial issue:

1. Go to BO > Design > Pages page 
2. Create a new page category `category1`
3. Create 3 subcategories in `category1`: `cat1`, `cat2` & `cat3`
4. In the `category1` > change the position of those subcategories 
image
5. Go to FO > Sitemap page => ok
6. Click on the link of the category1 
image
7. See error: the sort is NOK 
image

Thank you!

**Comment by JevgenijVisockij** [comment]
> Hi @JevgenijVisockij,
> 
> I found a trivial issue:
> 
>     1. Go to BO > Design > Pages page
> 
>     2. Create a new page category `category1`
> 
>     3. Create 3 subcategories in `category1`: `cat1`, `cat2` & `cat3`
> 
>     4. In the `category1` > change the position of those subcategories
>        image
> 
>     5. Go to FO > Sitemap page => ok
> 
>     6. Click on the link of the category1
>        image
> 
>     7. See error: the sort is NOK
>        image
> 
> 
> Thank you!

Thanks for Q&A! Fixed the issue.

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1Dnn9f0ruc_q1SM4gBapGcCRuu2xsu77S/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @JevgenijVisockij & @khouloudbelguith

**Pull request merged**
