### PR TITLE
PHPStan (Level 5) on js/

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | PHPStan (Level 5) on js/
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to #16471
| How to test?      | Github Actions are :green_circle: 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26744)

### CODE REVIEW

**Review by sowbiba — APPROVED** [review]

**Review by matks — COMMENTED** [review]
I'm a bit curious 😅  why do we run PHPStan on a folder that contains JavaScript ?

**Comment by Progi1984** [comment]
@matks May be because it contains PHP files

**Comment by matks** [comment]
> @matks May be because it contains PHP files

🤯

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thanks @Progi1984 !

**Pull request merged**
