### PR TITLE
Increase the number of results in the product search

### PR DESCRIPTION
**Pull request by Touxten**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |Increase the number of results in the product search
| Type?             | improvement
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | Create an order and check how many products are show during the search
| UI Tests          | 
| Fixed issue or discussion?     |
| Related PRs       | 
| Sponsor company   | Friend of Presta

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by LouisAUTHIE — DISMISSED** [review]

**Comment by nicosomb** [comment]
@ibahloul-ps I think we should have your opinion about this change.

**Comment by Touxten** [comment]
Let me give you my opinion:

The limit of 10 is really low for a large catalogue, you have the name of the product in your head but not the exact name, so you quickly find yourself copying and pasting exactly what you want, which I don't think is the point of a search.

Have a nice day!

**Comment by ibahloul-ps** [comment]
Hello @Touxten,
Thanks for your contribution!

Could you please add more details?
A screenshot or a video would be perfect :)

Have a great day!

**Review by PrestaEdit — APPROVED** [review]

**Review by jf-viguier — APPROVED** [review]

**Review by PululuK — APPROVED** [review]
Hi @Touxten , thanks for the contribution :) 
Can we make this configurable ?

**Comment by Touxten** [comment]
Yes i can make it configurable in the near future. 
You have e-traders for whom this could be a problem ?

For me 30 is the best for all merchants but we can have more also.

**Comment by Touxten** [comment]
Before :

Capture d'écran 2024-09-21 081918

After :

Capture d'écran 2024-09-21 082006

**Comment by PululuK** [comment]
I understand your idea better, in this case the best solution would be to use something like [Infinite scroll](https://select2.org/data-sources/ajax)

**Comment by FabienPapet** [comment]
maybe an autocmplete instead ?

**Comment by ibahloul-ps** [comment]
Hello @Touxten 

I agree with @FabienPapet , I think autocomplete would be a more appropriate solution, wdyt?

**Comment by Touxten** [comment]
Yes, and we can also add a fuzzy search.
However I am an e-merchant not a dev I think these few lines will help e-merchants.
Personally I do not use PrestaShop version 8 and even less version 9, I made this PR after a discussion on the Slack Friend of Presta

**Pull request closed without merging**
