### PR TITLE
Remove deprecated method `setPriorities` in class `SpecificPrice`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated method `setPriorities` in class `SpecificPrice`
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5089595740
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks
* Remove deprecated method `setPriorities` in class `SpecificPrice`

### CODE REVIEW

**Comment by Progi1984** [comment]
@PrestaShop/committers Open to Review

(Ping @jolelievre : The expert of Product)

**Comment by Progi1984** [comment]
@PrestaShop/committers Open to Review

(Ping @jolelievre : The expert of Product)

**Review by nicosomb — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Progi1984 

LGTM, QA ✅ 
https://github.com/hibatallahAouadni/testing_pr/actions/runs/5311687090

Thanks!

**Comment by nicosomb** [comment]
Thank you @Progi1984

**Pull request merged**
