### PR TITLE
Fix product flags display

### PR DESCRIPTION
**Pull request by nihco2**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Fix product flags display for classic theme |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-674 |
| How to test? | Check the 4 flags display |

### CODE REVIEW

**Comment by maximebiloe** [comment]
I have some little issues here:
capture d ecran 2016-08-31 a 17 59 33

**Comment by dSkrbic** [comment]
Q&A test: not OK, see screenshot
z3-screenshot_dsk_2016 09 01_11h51m23s_027_
z2-screenshot_dsk_2016 09 01_11h55m34s_029_
z1-screenshot_dsk_2016 09 01_11h57m35s_030_

**Comment by kpodemski** [comment]
These problems with saving the product are not related to this PR

**Comment by nihco2** [comment]
Fixes are done

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Pull request merged**
