### PR TITLE
Load only theme.(js|css) and custom.(js|css) & remove all other assets

### PR DESCRIPTION
**Pull request by julienbourdeau**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Maybe you should consider this

http://forge.prestashop.com/browse/PSCSX-2598?focusedCommentId=91912&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-91912

Regards

**Comment by julienbourdeau** [comment]
Thank you for your feedback. We'd rather people to not load many difference js files and not serve them from CDN.

As of today the best practice is to serve one single concatenated and minified javascript file. Once cached by the browser it won't be downloaded again. We provide all the tools to get there (with webpack) and the documentation is coming.

About CCC I don't know yet will look into it later. Especially because each module can add JS and CSS files, this feature is very important.

**Comment by kpodemski** [comment]
I'm not sure if this is a good idea, adding assets via addJS, addCSS was pretty simple and useful, we had possibility to easily add specific js code for category etc. I'm not sure if this all will be that simple as before, please remember about theme authors where we very often need to modify some core .js files, maybe in 1.7 javascript will be better, blockcart without markup inside etc. but still - this should be theme authors friendly.

Also, it was excellent to have /autoload/, people without knowledge had possibility to simply create 99-custom.css and modify theme without any issues after update... 

I think this move will be very important as soon as you will start with work on final PrestaShop default theme for v1.7.

**Comment by julienbourdeau** [comment]
`addJS` and `addCSS` are still available and they work exactly the same way as before. We just dont want the core to include so many external files. Today we load the jQuery easing plugin on every page and every template, not matter if it's needed by the theme. I understand that it can be quick and easy to load a page-specific javascript file but today it's a bad practice, we don't want to help people doing things the wrong way. Back in the days it was a good practice tho, that's why PrestaShop was doing it this way.

You can still load a specific file in your theme with the following method if you have to. If you want to add a file on the _my-account_ page:
In your `customer/my-account.tpl` file:
```smarty
{extends "page.tpl"}

{block name="head"}
  {$smarty.block.parent}
  <link rel="stylesheet" href="YOUR _FILE" type="text/css" media="screen" />
{/block}

{block name="page_title"}
  {l s='My account'}
{/block}

{block name="page_content_container"}
  <section id="content" class="page-content page-my-account">

    ...

  </section>
{/block}

```

**Comment by kpodemski** [comment]
And now it's clear for me and I agree with this :+1: 

Of course I think instead of having `<link rel=[...]` we should have functions like`{addJs}` or `{addCSS}` which should add proper file, maybe argument like "in_header" or "in_footer" will be nice too.

**Comment by gRoussac** [comment]
Hi,

What is the difference bewtween loading a concatenated and minified javascript easing plugin on every pages and loading one file on every pages, does all the page require all the plugins ? What about versionning of assets CCC implements to havoid cache issues ?

Regadrs

**Comment by kpodemski** [comment]
Hi @gRoussac 

I think now we can have one theme.js and we can load separate bigger files (which should be minifed, I don't know if by dev or by addJs with proper params) for specific pages, for example slider on the homepage, layered navigation on category page etc. I think load time of the homepage will be faster but subpages a little bit slower, what is better option? I don't know. Having different compiled js files for each of the page is something what is not exactly CCC.

btw. I think we should have possibility to load assets with params like file.js?v=2, on some servers cache is very hard and it will be simplier to change param in addJs to server newer file.

**Comment by julienbourdeau** [comment]
To make sure small theme customization are easy for merchants, we added `custom.css` and `custom.js`.

Unfortunately `addCSS` method load custom.css before theme.css. `addCSS` probably need a bit of work when arrays are passed.
I added a card on trello: https://trello.com/c/vc2dOwvQ/226-addcss-method-load-arrays-in-reverse-order-check-addjs

**Comment by kpodemski** [comment]
:+1: 

finally, good choice!

**Pull request merged**
