### PR TITLE
States : Added add button only on listing pages

### LINKED ISSUE #21183: BO - States page - Add new states button is not displayed after incorrect Save
#### Describe the bug

In the BO > International > Locations > States page, when we try to save incorrect data => redirection to the states page but the "Add new states button" is not displayed
image

#### Expected behavior

It should be displayed
image

#### Steps to Reproduce

1. Go to BO > International > Locations > States page
2. Click on Add new state
3. Try to create invalid states

#### Additional information

* PrestaShop version: 1.7.6.8, develop(1780)
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | States : Added add button only on listing pages
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #21183
| How to test?      | Cf. #21183

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25305)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

1. Go to BO > International > Locations > States page
2. Add a new state or Edit a state
3. The "Add button" is displayed

Is this the wanted behavior?

**With PR**
image

**Without Pr**
image

What do you think?

Thanks!

**Comment by Progi1984** [comment]
@khouloudbelguith Affirmative. Check issue.

**Comment by khouloudbelguith** [comment]
@Progi1984, in fact, in the issue the `Add new state` button is not displayed in the `states list` page 
**Without PR**
image
**With PR** => issue fixed, the button `Add new state` is displayed in the `States list` page
image

But the button "Add new state" is displayed also in the `Add new state` page and `Edit state` page, while it shouldn't or this is the wanted behavior?

Thanks!

**Comment by Progi1984** [comment]
@PrestaShop/product-team What is the expected behavior ?

**Comment by marionf** [comment]
@khouloudbelguith The button "add new state" should be displayed only in the listing
It should not be displayed in the add/edit state page

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by sarahdib** [comment]
@Progi1984 

1. Go to BO > International > Locations > States page
2. Add a new state or Edit with a iso code already used 
3. The "Add button" is not displayed in listing

Capture d’écran 2021-07-26 à 14 41 58

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sarahdib

**Pull request merged**
