### PR TITLE
Indexation not complete (PSCSX-5028)

### PR DESCRIPTION
**Pull request by erouvier29**
Some [product_attribute - language] were skipped because of LIMIT in Search::getProductsToIndex()
Additionally, try to make last change compliant with 1.6.0.13 database structure

### CODE REVIEW

**Comment by eric-rouvier** [comment]
I'm quite sure performances can be improved, but I don't know how. Need help from a MySQL specialist.

**Comment by jocel1** [comment]
I will take a look at it, I try to see if I can integrate the fix in https://github.com/PrestaShop/PrestaShop/pull/2649 ( I can reproduce the issue with my local datas )

**Comment by jocel1** [comment]
I've just pushed a fix in #2649 which should integrate your changes.

**Comment by 7starsone** [comment]
Hello, can you confirm that search class doesn't index products without images? This is my feeling...

and if so, why?
thanks

**Comment by 7starsone** [comment]
I did:

`SELECT * FROM ps_product WHERE active = 1 and indexed = 0; `

Total 2895

`SELECT * FROM ps_product WHERE active = 1 AND id_product not in (SELECT id_product FROM ps_image)`

Total 2221

There is a discrepancy, anyway...

**Comment by 7starsone** [comment]
in my opinion this is a bad code conception...

the user could be able to index products without images by option (at least), so not forced to index products with images only...

please write a solution about this and/or propose a code change about the search feature
thanks

**Comment by 7starsone** [comment]
mmm no, it seems doesn't index even many products with images...and at the moment I don't know why

I'm watching products fields to understand but I don't see any anomaly on database
so, there's some issues on the search class about indexation for sure
eg. on my db there are more than 1500 products with images and normal data which aren't indexed

**Pull request closed without merging**
