### PR TITLE
Fix Bad display of categories list in Product V2 [RTL]

### LINKED ISSUE #25991: [BO] [RTL] Bad display of categories list on Product (V2) edit page
Hello,

#### Describe the bug

In Product (V2) edit page (RTL language), categories list has invalid padding direction, checkbox overflow and bad radio button placement.

This is what we get:
Screenshot 2021-09-24 171433

#### Expected behavior

This is what we expect:
Screenshot 2021-09-24 171622

#### Steps to Reproduce

1. Go to BO > Products
2. Select a product to edit
3. Switch to experimental product page
4. Go to categories section

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In Product V2 page (RTL language), categories list has invalid padding direction, checkbox overflow and bad radio button placement.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25991
| How to test?      | BO > Products V2 > Categories
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25999)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Cool! Thanks for the contribution :)

**Comment by NeOMakinG** [comment]
@mparvazi I changed branch tag into develop, because it's an experimental feature and you're working branch is develop!

**Review by matthieu-rolland — APPROVED** [review]

**Comment by mparvazi** [comment]
I'll fix this problem with another PR

**Comment by NeOMakinG** [comment]
@mparvazi you closed this one because of some merge commits? If so, don't hesitate to ask us what to do, it would be a pleasure!

**Comment by mparvazi** [comment]
@NeOMakinG I've merged it in this commit: #26038
PR #26038 fixes all RTL problems the I've seen until now.

**Pull request closed without merging**
