### PR TITLE
Avoid cached data on dashboard refresh (PSCSX-5092)

### PR DESCRIPTION
**Pull request by erouvier29**
Just in case... Seems not to be systematic.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

You may also need this for Ipads and some browsers which do not respect the default cache for POST queries.

https://github.com/PrestaShop/PrestaShop/blob/1.6/themes/default-bootstrap/js/order-address.js#L111

Regards

**Comment by eric-rouvier** [comment]
Added headers. Thanks Gregory.

**Comment by gRoussac** [comment]
Thanks to you !

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, you may be interested in this for next time : http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Best regards.

**Pull request merged**
