### PR TITLE
Merge 8.0 to 8.1

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Merge 8.0 to 8.1
| Type?             | bug fix 
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto tests:
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/4363336748

**Review by 0x346e3730 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4363919008

**Review by djoelleuch — APPROVED** [review]
Hello @FabienPapet  , 
Automated tests => OK
LGTM , QA approved :heavy_check_mark: 

Thank you :rocket:

**Pull request merged**
