### PR TITLE
Remove unused toolbar.tpl

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Read below
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes - the toolbar.tpl file has been removed ([originally restored in 1.6.0.1](https://github.com/PrestaShop/PrestaShop/commit/e1ff774fcd9832e643a502be2528d11cd022ecaa) for backward compatibility)
| Deprecations?     | no
| How to test?      | Nothing to test
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop SA

## About this change

The `admin-dev/themes/default/template/controllers/access/helpers/form/form.tpl` file governs the style of the form in AdminAccess (aka Adv Parameters > Teams > Permissions). In AdminAccesControllers, we can verify that [show_toolbar is set to false](https://github.com/PrestaShop/PrestaShop/blob/c9ffe81097ac378d1b474262352419816eb6c81c/controllers/admin/AdminAccessController.php#L38). This means that the lines in the tpl around `if $show_toolbar` can be removed because it will always be false.

After removing those lines, we can see that there are no remaining references to `toolbar.tpl` left in the code, so we can remove it as well.

After removing `toolbar.tpl`, there are no more references to "toolbarHead", so we can remove the corresponding block from `admin.js`, which incidentally, also allows us to get rid of a deprecation message from jquery migrate:

Screenshot 2023-04-17 at 16 52 46

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @eternoendless ,

All automated tests are broken. I've relaunched them a few times already.
Could you check : https://github.com/florine2623/testing_pr/actions/runs/4763897406

@PrestaShop/qa-automation , do you have any idea on that topic ?

Thanks!

**Comment by Progi1984** [comment]
@florine2623 @eternoendless needs to rebase its PR before launching UI tests because he has some conflicting files.

**Comment by eternoendless** [comment]
Rebased!

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @eternoendless 

I have launched the automatic tests. 
The failed tests are already present on Nightly but not on the same fails.
**Tests** : https://github.com/HanaRebaiQA/testing_pr/actions/runs/4784810008
**Nightly** : https://github.com/PrestaShop/PrestaShop/actions/runs/4781547937

For example : 
image

image

ping @PrestaShop/qa-automation Do you confirm that these failures are no related to this PR ?

Thank You!

**Comment by nesrineabdmouleh** [comment]
Hello @HanaRebaiQA,

Thank you for testing, the errors are not related to the PR.
:red_circle: => issues https://github.com/PrestaShop/PrestaShop/issues/32178  https://github.com/PrestaShop/PrestaShop/issues/32180

**Review by HanaRebaiQA — APPROVED** [review]
Thank You @nesrineabdmouleh :) 

So, it's QA :heavy_check_mark:

**Comment by kpodemski** [comment]
thanks @eternoendless

**Pull request merged**
