### PR TITLE
Increase max. length of catalog price rule name (#BOOM-924)

### PR DESCRIPTION
**Pull request by antho-girard**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Maximum length of catalog price rule name was set to 32, which is not enough. It is now 255. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-924 |
| How to test? | Try to set a name with a length greater than 32 |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by julienbourdeau** [comment]
I checked, the database column is 255 characters long and the _ObjectModel_ has no other limit. Why not go all the way to 255?

**Comment by antho-girard** [comment]
Yes, you're right!
I'll raise the length limit while i'm at it :)

**Comment by julienbourdeau** [comment]
Hi,

Please update your PR and I can merge it right away :D

**Comment by julienbourdeau** [comment]
Sorry I used an old tab in my browser, it wasn't up to date !

**Comment by julienbourdeau** [comment]
Thank you!

**Pull request merged**
