### PR TITLE
[-] FO : Fix #PSCSX-4326, Incorrect prices on product page using reducti...on amount and more currencies, first part

### PR DESCRIPTION
**Pull request by gRoussac**
Need functionnal tests + review  + debug with group reduction

http://forge.prestashop.com/browse/PSCSX-4326

### CODE REVIEW

**Comment by eric-rouvier** [comment]
Product.php, lines 2859 + 2880: Aren't taxes added twice in some cases? (cf. #2548, still pending...)

**Comment by gRoussac** [comment]
Hi,

Thanks for your interest. On 2880, I had to replace price. It is not += statement.

I invite you to install https://github.com/gRoussac/PrestaShop/archive/PSCSX-4326.zip directly so that you can test 4/5 specific rules.

I know there is still a bug while adding group reduction on it, told the reporter.

Regards

**Comment by eric-rouvier** [comment]
Gregory, I was unable to test your archive. FO remains empty. I don't know what is going wrong...
And if I replace the previous 1.6.0.14 Product.php by the new one, there are some datamodel errors because of recent database changes I assume.

**Comment by gRoussac** [comment]
Hi,

I wanted to say thank you Eric for your feedback and help. Really appreciated.

Your two points are right. If everyone could be so subjective, I would be more than happy. I know your PRs are precise but even if I read it before or the one from @snamor , I simply forget them when trying to debug this.

To explain, I wanted to impact as few as possible the first if and ended in a non kiss way.

I know I had to affect $prices in the second if statement again for one case on cart page but can not reproduce anymore now so I merged your PR manually and we will run tests against it.

Best regards

PS : you could not use it because of submodules, modules are empty. I forgot to told you.

**Comment by eric-rouvier** [comment]
You're welcome, I know you have a lot to do.
Never easy to choose between patching and refactoring.
Let's all continue to do our best for user satisfaction... and glory ;-)

**Pull request merged**
