### PR TITLE
Fix error while compiling theme assets

### LINKED ISSUE #26248: PS 1.7.8.0 Error compiling classic theme assets with Windows 10
#### Describe the bug
When I try to compile the assets of the "classic" theme, the system gives an error.

If I run the command: 
**npm run build**

I get the following error:
**"NODE_ENV" non è riconosciuto come comando interno o esterno**
I solved it by replacing in the package.json file
`"build": "NODE_ENV=production webpack --progress --colors --debug --display-chunks",`
with
`"build": "webpack --progress --colors --debug --display-chunks --mode=production",`

But I still have problems, in fact executing the command:
**npm run build**
I get the following error:
**Can't resolve '. \ Tether.js' ...**

I attach the screenshot with the complete error

P.S.
I tried with ubuntu and it works

**Screenshots**
Screenshot

#### Additional information
* PrestaShop version: 1.7.8.0
* PHP: all
* SO: Windows 10

### PR DESCRIPTION
**Pull request by templatin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Error compiling theme assets in PS 1.7.8.0.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26248
| How to test?      | Please check above ticket.
| Possible impacts? | Theme assets compiling.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26477)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@Robin-Fischer-PS I think a dev can do the QA as it's i technical.

**Comment by Robin-Fischer-PS** [comment]
@Progi1984 OK for QA by dev, thanks !

**Comment by atomiix** [comment]
@PrestaShop/prestashop-core-developers do someone have a Windows 10 machine/VM to test this PR? 😅

**Comment by PierreRambaud** [comment]
Tests are green, not sure someone from the Core team has a Windows machine.
It still works on Linux/OSx, we can merge it as the change has been done by a Windows user.

Otherwise, it will never be tested and merged

**Pull request merged**
