### PR TITLE
Fix group when converting customer through front office form

### LINKED ISSUE #27753: Customer groups are not assigned properly when converting customer through front office
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Customer groups stay assigned to Guest after converting customer through front office.

Discovered while working on https://github.com/PrestaShop/PrestaShop/pull/25353, will be fixed by this.

### Expected behavior

Customer should have proper groups set.

### Steps to reproduce

1. Clear cookies. Add anything to cart. Go to checkout.
2. Enter name, surname, email and continue. (no password)
3. Go check your new guest customer to backoffice. See that his group is **"Guest"**.
4. Now, two options:
  - Go back to checkout first step and fill password.
  - OR go to Sign in > create new account. Enter the same email and a password.
5. Now your guest is converted to regular customer.
6. However, if you check your customer in backoffice, he will still have the **"Guest"** group assigned. He should have **"Customer"** group.

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR ensures proper group assignment when converting customer through front office. Reviewers, please read below.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27753
| Related PRs       | none
| How to test?      | See scenario in the related issue.
| Possible impacts? | none

### Description
- This PR fixes proper group assignment when converting customer through front office. When you go to checkout, don't fill out password, then decide to go back or register through normal register form.
- This PR has no BC breaks.
- The only three logic changes are these. They are intentionally separate because we don't want to mess up customer's group if the saving fails for any reason.
```
$customer->cleanGroups();
$customer->addGroups([Configuration::get('PS_CUSTOMER_GROUP')]);
$customer->id_default_group = (int) Configuration::get('PS_CUSTOMER_GROUP');
```
- Other changes are only renamed variables and some comments that I started in (https://github.com/PrestaShop/PrestaShop/pull/25353)
- I want to improve this further and unify the place where all these conversions and email sending occurs, but that will require bigger refactoring, this is the way to fix it to 8.1, easy to review, easy to QA.

### CODE REVIEW

**Review by matks — APPROVED** [review]
@Hlavtox thank you so much
- your very clear explanations make it very easy to review, and are precious for both reviewers and developers who will read the code in the future
- PR is scoped (it does only 1 thing) and code is more readable thanks to you

This is a great PR and I am so happy to see such contribution from you @Hlavtox 👍 great job

**Comment by Hlavtox** [comment]
@matks ❤️

**Review by FabienPapet — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @Hlavtox ,

It is ok :tada: 

Here is my checked list :

- multilanguage: English + French + Arabic: OK :heavy_check_mark: 
- multisore: OK :heavy_check_mark: 
- different browsers: OK :heavy_check_mark: 
- automated tests: OK :heavy_check_mark: 

[Untitled_ Oct 11, 2022 10_08 AM.webm](https://user-images.githubusercontent.com/111756615/195092926-73983b01-b1bd-4277-901d-764750de23f6.webm)

Thank you :pray:

**Comment by Hlavtox** [comment]
Thank youuuu @MhiriFaten! :-)))

**Comment by atomiix** [comment]
Thanks @Hlavtox !

**Pull request merged**
