### PR TITLE
Made cache parent directories recursively

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Make cache directory recursively |
| Type? | bug fix |
| Category? | IN |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1107 |
| How to test? | Install Prestashop and create cache parent directories when required |

### CODE REVIEW

**Comment by ginodev** [comment]
Hi!

Can you integrate this? https://github.com/txmodxoops/PrestaShop/pull/1

**Comment by xBorderie** [comment]
@ginodev You should create your own PR on the `develop` branch :)

**Comment by aleeks** [comment]
Thank you!

**Comment by ginodev** [comment]
@xBorderie I noticed that the develop version there are no modules, I'm forced to send the module ps_socialfollow?

**Comment by aleeks** [comment]
Hello @ginodev. Yes, you need to fork this repo : https://github.com/PrestaShop/ps_socialfollow and make your PR :+1:

**Comment by txmodxoops** [comment]
Done! :)

**Comment by ginodev** [comment]
Yes Done 👍

**Pull request merged**
