### PR TITLE
[*] Project : ReDesign Order View

### PR DESCRIPTION
**Pull request by PhpMadman**
This pull, is just to check what people think of this approch.

It's tabed version of the order view.
I only moved around the code in the tpl's. I thinks the page loads a little faster.
If this is to be added, it will most likely need to have a lot of css changes, especailly for the responsive design.

**Known Issues**
Product tab is blank at load, switching tab loads it.
Products kpi linkd does not work. ?JS to switch tab?
Status select and Mail select does not get proper width
Hooks are baddly placed.
~~Linked orders tab is always shown~~

**Ideas**
Move payment to it's own tab
Move Print order / View Invoice / Delivery etc buttons to above the tabs, sho they always show.

Feel free to push any changes to my branch.

### CODE REVIEW

**Comment by PhpMadman** [comment]
taborderview

**Comment by syswarren** [comment]
Hi there!

We really like your proposition and we'd like to move forward with it. You're right about the "Payment" tab. It'd be useful.
We're thinking about having a small modification by putting the "status" bloc between the KPI and the tabs. 

statusorder

Also, we're currently working on a whole new interface and if you want to participate, we'd be more than happy to share mockups with you to get your feedbacks. 

Let me know if you're interested. 
Thanks!

**Comment by kpodemski** [comment]
I think that it will be nice to see this on build.prestashop.com or some other place for developers...

in my opinion having 100% width block with statuses is not a solution, it is better to have one "motive-color" in back-office and style more important blocks with this background.

**Comment by syswarren** [comment]
@kpodemski Let's say this is a "quick fix". 
We're working on something really big for the next UI.

**Comment by PhpMadman** [comment]
Hi.

I like the status placement.
I'll make a commit later, and change to that look.

And yes, I'm always intrested in helping out with PrestaShop. 
Feel free to contact me about new design mockups.

**Comment by PhpMadman** [comment]
By the way, should I make new PR on dev branch or should I keep working on this?

**Comment by PhpMadman** [comment]
Nevermind. I'll do it on develop. I already uploaded it to my server.

**Comment by jeromenadaud** [comment]
Hi, yes, on develop branch please.
Thank you.

Kindly regards.

**Comment by PhpMadman** [comment]
new PR is #3462

**Pull request closed without merging**
