### PR TITLE
Fix wrong output message from ImageManager::validateUpload

### LINKED ISSUE #18391: ImageManager::validateUpload returns wrong message about extensions
#### Describe the bug

When developer specifies wanted extensions like [png, svg], if user upload an other one, the error message displayed don't care about extensions specified by the developer and mentions to the user that he must upload GIF, JPG or PNG file.

#### Expected behavior

The error's message should display extensions specified by the developer to inform correctly the user

1. Disable Debug mode
2. Replace this [line](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ImageManager.php#L476)
by
`if (!ImageManager::isRealImage($file['tmp_name'], 0, ['png']) || !ImageManager::isCorrectImageFileExt($file['name'], $types) || preg_match('/\%00/', $file['name'])) {`
3. Clear cache
4. Go to BO => Product details page
5. Upload Image `.jpg`
6. See error `Image format not recognized, allowed formats are: .gif, .jpg, .png`
=>It should be `Image format not recognized, allowed formats are: .png`
image
-------------------------------------------------

1. Create a form with `input:type="file":name="fieldName"`
2. On validation of form, display the output of `\ImageManager::validateUpload($_FILES['fieldName'], 0, ['png'])`
3. On your page upload a **jpg** file
4. You will see *Image format not recognized, allowed formats are: GIF, JPG, PNG* despite you have upload a jpg.
5. The good message should be `Image format not recognized, allowed formats are: .PNG`

#### Additional information

* PrestaShop version: 1.7.6.4
* PHP version: 7.2
* Pull Request: we have a patch to suggest for that issue

### PR DESCRIPTION
**Pull request by WebXYAgency**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch | develop
| Description | Fix the output of ImageManager::validateUpload which returns allways the same message specifying that only **gif, jpg, png** file are allowed although the form allow something else.
| Type | bug fix
| Category  | BO 
| BC breaks  | no
| Deprecations  | no 
| Fixed ticket  | Fixes #18391
| How to test  | see issue #18391

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18410)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Hello @WebXYAgency , thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by LouiseBonnard** [comment]
Hi @WebXYAgency, thanks for your contribution here! Can you indicate where in PrestaShop can a user upload other formats than .gif, .jpg, and .png?

**Comment by WebXYAgency** [comment]
> Hi @WebXYAgency, thanks for your contribution here! Can you indicate where in PrestaShop can a user upload other formats than .gif, .jpg, and .png?

Hi @LouiseBonnard, for example  this could be useful in the context of a custom integration we could only allow png format, other example, a module could require that we upload only svg.
But since it is a public method taking as parameter the expected extensions, any developer could use it with extensions other than .gif, .jpg, and .png.
Do you think it isn't?

**Comment by Progi1984** [comment]
Hello @WebXYAgency, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by LouiseBonnard** [comment]
Hi there @WebXYAgency, you have conflicting files that prevent the merge. Could you please rebase your PR to resolve the conflict? Many thanks!

**Comment by PierreRambaud** [comment]
Hi @WebXYAgency  ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
