### PR TITLE
[-] Class: Product / Check access for accessories

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by xBorderie** [comment]
The Product page has been heavily reworked since you made that PR, @prestamodule .
@xGouley, do you think it is still applicable?

**Comment by vincentbz** [comment]
Hi @prestamodule,

Can you tell me what's the aim of this PR please ? i'm not good in understanding code :)

Thanks !
(and sorry for the "small" delay :smile: )

**Comment by kpodemski** [comment]
@vincentbz I guess accessories are not checked for group access for products

**Comment by PrestaEdit** [comment]
Hi @vincentbz,

The deal was to check if the customer can see a product set in the accessories of a product. It's the block you set into the product sheet and that you can see on the product sheet (front).

With this, the goal is to show products that the customer can effectively see. (else, the customer will have an error if he can't see the product when he reach the product page).

You see ? :)

**Comment by vincentbz** [comment]
Thanks ! really more clear now :)
So it could be good to integrate it in the 1.7.
The product page has quite a lot changed, do you think this PR is still up to date ?

**Comment by xBorderie** [comment]
It can still be merged, but [the tests do not pass anymore](https://travis-ci.org/PrestaShop/PrestaShop/builds/88466768). A dev should see about that.
About the relevancy of the PR itself, I'd like @xGouley to give his opinion.

**Comment by Shudrum** [comment]
The tests are failing, please rebase your branch on the top of the develop branch to make them works.

Thank you !

**Comment by PrestaEdit** [comment]
Hi @Shudrum ,

The rebase of the branch was done by @hadjedjvincent ; tests are now ok. :)

**Comment by firstred** [comment]
All seems correct, indeed!

**Review by firstred — APPROVED** [review]

**Comment by aleeks** [comment]
Hello @prestamodule 
I cherry-pick your commit here https://github.com/PrestaShop/PrestaShop/pull/7501 rebase from develop

Regards

**Pull request closed without merging**
