### PR TITLE
[*] TEST : upgrade travis to trusty to fix google chrome version issue

### PR DESCRIPTION
**Pull request by jocel1**

### CODE REVIEW

**Comment by firstred** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
:+1: let me fix the two remaining tests.

**Comment by maximebiloe** [comment]
Thanks for the fix.
We're hoping that @mickaelandrieu's PR will fix the two failed tests :pray:

**Comment by mickaelandrieu** [comment]
:sunglasses:

**Pull request merged**
