### PR TITLE
[+] CORE : Add new hooks in image resize and cut

### PR DESCRIPTION
**Pull request by guestisp**

### CODE REVIEW

**Comment by guestisp** [comment]
News on this? Having noise on resized images is no good.

**Comment by guestisp** [comment]
bump

resized image have noise on high quality LCD display. Please fix.

**Comment by kpodemski** [comment]
@guestisp have you some examples? before and after change? I have 25" DELL 2560x1440 so maybe I'll see the difference :)

**Comment by guestisp** [comment]
Yes, please wait

**Comment by guestisp** [comment]
to-ol-shameless-santa-75cl

On many LCD screen, some blur is visible on white background, probably on LCD with high contrast ratio

In my own LCD i can't see the blur. On our graphical workstations (or some macbook pro) i'm able to see.

My fix, solve this issue. If I remember properly it's a bug in GD library or in PHP.

**Comment by guestisp** [comment]
Keep in mind the any (if any) github resize could remove the noise. If you need, I can send image by email.

**Comment by guestisp** [comment]
dsc_0087

One photo is better than 1000 words. Obviously ignore the circles made by phone when shooting on an LCD. Look at the square noise on white background

**Comment by kpodemski** [comment]
Hm, I don't see any blur on first image but - yes - on a second I see this.

**Comment by guestisp** [comment]
Probably, github resize the image for posting removing the blur.
The second one is a photo taken directly from my mobile phone. All images resized by PS has this blur. Even by choosing png or increasing to max the jpg quality.

**Comment by xBorderie** [comment]
Thank you for this PR!

**Pull request merged**
