### PR TITLE
Change color of view website and add icon color on hover

### LINKED ISSUE #22525: [BO] View my shop button is blue while it shouldn't
#### Describe the bug

Icon of View my shop on header is blue, it's looking like it's active while it shouldn't

#### Expected behavior

Should be gray, and blue on hover

image
image
image

#### Steps to Reproduce

1. Go to BO
2. Hover view my shop button

#### Additional information

* PrestaShop version: develop

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Icon of View my shop on header is blue, it's looking like it's active while it shouldn't
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22525.
| How to test?      | Go on BO, and see view my shop icons colors

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22526)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok when we have only one shop enabled but if you enable multistore context => NOK
image

Thank you!

**Review by Progi1984 — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
should be fine now @khouloudbelguith , couldn't do better than what you'll see on default them, as the markup is pretty weird

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

When multistore is enabled.
In the Migrated page => ok
image

In the legacy page => NOK
image


Thank you!

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG,
> 
> When multistore is enabled.
> In the Migrated page => ok
> image
> 
> In the legacy page => NOK
> image
> 
> Thank you!

I really can't do more than this without modifying the markup :/

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Thank you!

As discussed with @PrestaShop/qa-functional, it is ok :heavy_check_mark: 

With PR:
Mobile
image
Web
image


Thank's

**Comment by matthieu-rolland** [comment]
thank you @NeOMakinG

**Pull request merged**
