### PR TITLE
[-] BO: fix column icon width

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi @prestamodule,

Thanks for the branch switch, but it seems a conflict resolve is required here :)

Best regards,

**Comment by PrestaEdit** [comment]
Hi @tchauviere ,

Conflict ? You know wich ? :)

**Comment by tchauviere** [comment]
Hi @PrestaEdit,

git pull origin 1.6.1.x, should show you where there are.

I saw there's is conflicts only because GitHub told me so :) (see screen below)
https://www.dropbox.com/s/xrnjgbz0hqshhp6/Capture%20d%27%C3%A9cran%202015-09-21%2009.31.43.png?dl=0

Have a good day ;)

Best regards,

**Comment by jeromenadaud** [comment]
Hi, 

thank you for your contribution.

Best regards.

**Pull request merged**
