### PR TITLE
Fix help card in popup instead of full page on create webservice

### LINKED ISSUE #31943: WebService - Help card is in full screen when you modify a Webservice
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I clic on the help button during a modification of a webservice, the help information is on full screen insteed of put it in a modal (like all other help card) as you can see : 

[Untitled_ Mar 28, 2023 11_21 AM.webm](https://user-images.githubusercontent.com/100699445/228191114-521185cc-e851-49ef-84ab-8df0adad1bbe.webm)

### Expected behavior

This help card should be on a modal 

### Steps to reproduce

1. Go to BO > Advanced Parameters > WebService
2. Clic on "Add new webservice key"
3. Clic on Help button 
4. Look at this big help 

If you check another back-office page you'll see on other BO pages the "help" opens inside a modal, not in full screen.

### PrestaShop version(s) where the bug happened

8.0.3 - 8.0.1 - 1.7.7.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tleon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The Help button on the create webservice page of the BO was redirecting to a different page. This PR makes this button open a modal with the help page content as it is done on the rest of the BO.
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go to BO > Advanced Parameters > WebService,  Clic on "Add new webservice key", Clic on Help button
| Fixed ticket?     | Fixes #31943
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

## DETAILS : 
~~The content of the popup is a bit unusual because a screenshot is present in this help card. The doc from which the help card is filled is not part of the codebase. I'll inform on the side the person managing the doc to see if it's possible to make this part responsive.~~

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Comment by AureRita** [comment]
HI @tleon 

Thank you for your first PR ! I tested your PR and currently we have the modal but in this modal, there is an unlimited loading, as you can see : 

[Untitled_ Apr 5, 2023 11_57 AM.webm](https://user-images.githubusercontent.com/100699445/230048829-e839ebc7-d92f-4baf-be90-ea1043205cd3.webm)

Thank you

**Comment by matks** [comment]
Hi @AureRita, @tleon has seen that on this page, _the help content indeed does not load because of a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) issue_ .

It's not in the scope of this ticket but we think this is going to impact the end user, so your feedback is right 👍 .

@tleon is going to also solve this 🎯

**Review by matks — CHANGES_REQUESTED** [review]
Need to also solve the CORS issue

**Comment by tleon** [comment]
CORS issue is fixed. It also fixed the responsiveness of the template.

**Review by matks — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @tleon 

Thank you for your PR, I tested it and it works, as we can see here :

image

Thank you !

**Review by AureRita — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @tleon :))

**Pull request merged**
