### PR TITLE
[Standby] Disable selenium and startertheme tests

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | These tests will be moved to the E2E directory.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | This can be tested on Travis

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9031)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,

> These tests will be moved to the E2E directory.

I disagree with the way we solve the issue: I prefer to see them moved in E2E folder **before** disable the current ones.

These tests still help us revealing issues so I don't see the urgency to disable them.

Only my opinion here, we should discuss it ^^  ping @PrestaShop/prestashop-core-dev

**Comment by PierreRambaud** [comment]
Totally agree with @mickaelandrieu, we still need these tests even if some of them are failing.

**Comment by fatmaBouchekoua** [comment]
Hello @mickaelandrieu ,
This was requested by @mbadrani

**Comment by PierreRambaud** [comment]
Don't know if @eternoendless and @mickaelandrieu are agree to remove tests but your pull request need more modifications:

Remove in `run-functional-tests`:

```bash
if [[ $EXTRA_TESTS != *"functional"* ]]; then
  exit 0
fi
```

Same for `.travis.yml`:
```yaml
matrix:
  include:
    - php: 7.1
      env: EXTRA_TESTS=functional PRESTASHOP_TEST_TYPE=e2e
```

Moreover, to stay consistent, it's better to leave the file `check_e2e` and only remove bash execution in this one. :smile:

**Comment by fatmaBouchekoua** [comment]
Hello @PierreRambaud ,
Thank you for your review, I'm still working on it (I forgot to add the WIP label)

**Comment by mickaelandrieu** [comment]
I've talked with @mbadrani, this pull request will be accepted once the starter theme will be also used on the E2E suite :)

So you can remove all selenium and starter theme specific tests, but you also need a new build that install the starter theme and run e2e tests one more time :)

**Comment by Quetzacoalt91** [comment]
@mickaelandrieu, we agreed the tests wouldn't be merged before the E2E test suite is ready, do not worry. :)

**Comment by Quetzacoalt91** [comment]
Hi,

What's the status of this PR?

**Comment by mbadrani** [comment]
Hi @Quetzacoalt91 ,
For the moment this PR is still on hold, we will treat it once our new E2E tests framework (puppeteer) will be integrated in the E2E repo.

**Comment by PierreRambaud** [comment]
Selenium will be removed.

**Pull request closed without merging**
