### PR TITLE
Fix yml config parse typo

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix yml config parse typo
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | All tests must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16893)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
One more review and merge.
https://symfony.com/doc/current/components/yaml.html#reading-yaml-files

**Review by matthieu-rolland — APPROVED** [review]
lgtm for me too @PierreRambaud , thank you for your contribution @mvorisek 👍

**Comment by mvorisek** [comment]
When will this PR be merged into `develop`? Is there any general rule like when a release from the target branch is made?

**Comment by matks** [comment]
> When will this PR be merged into `develop`? Is there any general rule like when a release from the target branch is made?

We regularly perform merges of branch `1.7.6.x` into `develop`, but the frequency is not asserted. We do it every 2 or 3 days when enough commits are waiting for it. Example of such PR https://github.com/PrestaShop/PrestaShop/pull/16596

EDIT: as it's holidays season, the frequency dropped a lot 😁

**Comment by matks** [comment]
Just created a PR to perform the merge: https://github.com/PrestaShop/PrestaShop/pull/17000/

**Comment by mvorisek** [comment]
@matks Thanks!

**Pull request merged**
