### PR TITLE
Update autoload library to v1.0.1

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Update autoload library 
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See https://github.com/PrestaShop/autoload/pull/5 for description
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by djoelleuch** [comment]
Hello @jolelievre  , Some checks were not successful could you pease check it ! 
Thank you

**Comment by kpodemski** [comment]
It's related to my PR. Why didn't PHPStan block it inside my PR? 🤯 

Edit: and now tests are all green, not sure what happened :)

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional I'm marking this to be validated by a dev as it's a technical issue

**Review by FabienPapet — APPROVED** [review]

**Comment by jolelievre** [comment]
I already performed a QA by dev on the lib change PR here https://github.com/PrestaShop/autoload/pull/5
I'm not sure it's worth doing it again 🤔

**Comment by jolelievre** [comment]
Running campaign of UI tests https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5512478109

**Comment by jolelievre** [comment]
The initial PR was already tested so it's ok to merge this one

**Pull request merged**
