### PR TITLE
[WIP] FO: Bootstrap v4-beta upgrade for Classic theme

### PR DESCRIPTION
**Pull request by soullivaneuh**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Bootstrap v4-beta upgrade with theme fixes
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Install and see. :wink: 

This is a **WIP** for now. Please test my PR and send me any remark or founded bug under comment. :+1: 

See also: https://github.com/PrestaShop/PrestaShop/pull/8017#issuecomment-308964227

Notes:

* ps_banner default image should be redone to fit 1140px width.

TODOs:

- [x] Fix navbar desktop view
- [ ] Fix navbar mobile view (with menu dropdown)
- [x] Fix carrousel desktop view
- [x] Fix Wrapper/Footer blank separation on desktop view
- [x] Fix newsletter form on footer desktop view
- [x] Resize product miniatures image size for desktop view
- [x] Fix broken category page desktop view
- [ ] Fix broken category page mobile view
- [ ] Fix broken footer menus (disappears after de-collasping)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8022)

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I found a "white zone issue" here:

image

I put flashy background colors to easily catch the difference. `#wrapper` is green, `#footer` is red.

If I remove the `#wrapper` section, the white zone disappears. But it's still here if I let `#wrapper` without any content on it.

So it's linked to this section, but I don't know how. Any idea?

**Comment by Soullivaneuh** [comment]
I found why: It works better with a `.row` inside the `.container`...

**Comment by Soullivaneuh** [comment]
I have to fix this part:

image

But I didn't find the menu content inside `header.tpl`. Where can I find it?

**Comment by xBorderie** [comment]
I think you misunderstood @maximebiloe 's comment in #8017.
Updating to Alpha 6 means that FlexBox is used instead of the previous floating behavior, which breaks the display of the default theme... and that of all the community themes that have been built based on Classic.

This means that, sadly, PrestaShop 1.7 cannot upgraded to anything above Alpha 5 of Bootstrap 4, unless break ALL existing 1.7 themes. (Maxime, please confirm my understanding of this)

Thank you for your hard work on this ticket. I'm afraid it cannot be merged until the next major version...

**Comment by Soullivaneuh** [comment]
In this case we have a problem.

Twitter bootstrap is under alpha version. Alpha means unstable.

If some needed fixes comes on later versions of the bootstrap framework, how could we get them unless by upgrading it?

I'm not sure what was the reason to choose an unstable version for your next 1.7 default theme, but in this case, we have to take the risks with it IMHO.

Maybe this should be upgraded with a warning notice/blog post? Dunno, but we should take benefit of the upcoming stable bootstrap release...

Regards.

**Comment by xBorderie** [comment]
If I'm not wrong, one of the conversation about this was that we might make the switch once Bootstrap is indeed stable. Currently, [they are approaching beta](https://github.com/twbs/bootstrap/milestone/41)...

In early 2016, when working out the Classic theme, the Core team decided to use Bootstrap 4 because, even if it was at the time at Alpha 4 stage, it seemed stable enough, and we were hopeful that a proper release would appear within the year. 18 months later, it turns out that we were indeed optimistic! But we have to live with this choice and try not to break the ecosystem that is creating around 1.7.

**Comment by Soullivaneuh** [comment]
Indeed, very optimistic! :trollface: :wink: 

I still support that getting blocked on an old alpha release is potentially dangerous. We can't have any bugfixes anymore.

Maybe we can try a smoother solution? For example, creating a new theme and abandon the current classic one?

Current child themes will not be directly destroyed when upgrade but we may tell the developer to do the upgrade to the new one?

**Comment by soullivaneuh** [comment]
What do you think about my proposal? Bootstrap v4 is now on beta: http://getbootstrap.com/

**Comment by maximebiloe** [comment]
Hello @Soullivaneuh,

Yes, we saw that Bootstrap 4 is now in Beta.
I still need to look at your PR in details, but in parallel, I'm migrated our UI Kit to Alpha 6 and now I will update it to the Beta. It will be used in the BO.

Regards

**Comment by soullivaneuh** [comment]
Hello @maximebiloe,

I understand, but maybe can you give me a feedback for my proposition about separating the themes (https://github.com/PrestaShop/PrestaShop/pull/8022#issuecomment-309474421)?

With this, I'll know what to do to continue this not finished PR.

ATM, I just made a rebase to fix git conflict, skipping the compilation part.

BTW, I see you just have a `package-lock.json` file now. How can I update it properly?

**Comment by eternoendless** [comment]
Hello @Soullivaneuh 

Sorry for the long delay!

> Maybe we can try a smoother solution? For example, creating a new theme and abandon the current classic one?

Yeah, I think that would be the better solution in order to avoid breaking current child themes.

> BTW, I see you just have a package-lock.json file now. How can I update it properly?

I believe running `npm update` will update your dependencies based on `package.json`.

**Comment by soullivaneuh** [comment]
@eternoendless Thanks for the answer.

I'll try to get some time next month to finish this PR.

**Comment by soullivaneuh** [comment]
I did a rebase. I will still work on the main theme for now to give you a proper git diff.

When it will be done and approved, I'll move the files to a new theme folder before merge.

**Comment by soullivaneuh** [comment]
For what `bootstrap-touchspin` is used for exactly? It is compatible bootstrap 3 only according to the documentation but is still required.

**Comment by eternoendless** [comment]
I believe it's used for touch-enabled spinners like this one:

screen shot 2017-12-29 at 10 52 05

**Comment by johanlantz** [comment]
I also got hit by this today. Some features I wanted from bootstrap 4 was not available in the Alpha. 

If I am not mistaken existing themes can still ship their own bootstrap version. At some point you have to take the leap and it seems as with increased installations and modules for 1.7 it will only get worse by waiting. 

If existing themes continue or update this would only affect modules expecting a certain behavior, maybe these modules are not as common as we think. I assume a lot of functionality in bootstrap will be unaffected by the post alpha 5 changes.

**Comment by psdevx** [comment]
@eternoendless any new thought on this? 
I wanted to start working on a PS 1.7 theme and made some experiments but the first thing that happened was that I lost half a day trying to figure out why elements were not hidden when the documentation for Bootstrap 4 was very clear on how to do it.

Finally I realized that the Alpha 5 version of the theme does not have all the features listed in the docs or in this case was using an older api to hide things. This makes it very hard to develop and change things since the Bootstrap doc is not on pair with the features available in the classic theme.

**Comment by johanlantz** [comment]
I played with this a little bit during the weekend. I applied the changes in this PR manually and it worked more or less. There were a couple of issues but someone with more experience than me should be able to iron them out quite quickly. 

@eternoendless I think having a new theme based on classic would be a great idea. I am happy to help where I can. With all the efforts you are doing on modernizing for 1.7, having the up to date bootstrap version has to be the only way going forward.

@Soullivaneuh I saw yesterday that there is now v4 support for the touchspin. To be honest, I had some weird issues with the existing version in the Alpha5 on desktop so maybe its worth the update anyway. However if you had some issues with that one, updating it to the latest version should help.

I think the classic theme is awesome, finding my way around it is so much easier than older themes and I would like to use it when migrating to 1.7 but I do not want to invest all that time tuning it when the Bootstrap is deprecated so any efforts on this are highly appreciated. 

One thought @eternoendless, could it make sense to run this theme project in its own repo? It would make it easier to not have to clone the whole Prestashop repo and also easier to track PR's and issues only related to the theme?

**Comment by johanlantz** [comment]
@eternoendless Congratulations on completing the 4.0 integration in the BO. Any thoughts on if Bootstrap 4.x will finally be a priority for 1.7.5.0? If its a new theme project it will not break anything. I think everyone likes Classic so having a clone that can be used as a new baseline with the latest frameworks will allow things to move forward smoothly in the FO part as well and hopefully the old classic can be deprecated at some point :-)

**Comment by eternoendless** [comment]
Hi there!

I'm happy to announce that @prestarocket took matters into his own hands and released a port of Classic to Bootstrap 4.1, which you can find here: https://github.com/PrestaShop/classic-rocket

As the project now has its own repo, I'm closing this PR. Thanks a lot to everyone involved!

**Comment by Bonobomagno** [comment]
what happened to the merge milestone?

**Pull request closed without merging**
