### PR TITLE
Fix combination generation

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | fix error 500 while generating product combinations
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-6290
| How to test?  | Create a product with combinations. Save. Select combinations and click on generate. You should not hav 500 error in console anymore

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9466)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by marionf** [comment]
@tomlev 

No more 500 :+1: 

The modal with bulk actions is still disabled after clicking on generate, I think it was because of the 500 but it's not

capture d ecran_187

**Comment by jolelievre** [comment]
seems good to me!

**Review by jolelievre — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
this needs a rebase from develop branch for coding styles :-)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thanks @tomlev

**Pull request merged**
