### PR TITLE
Removed deprecated file `admin-dev/get-file-admin.php`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed deprecated file `admin-dev/get-file-admin.php`
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4407101835
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks 
* Removed file `admin-dev/get-file-admin.php`
* Remove parameter 1 `$admin` for the method `getTextLink` in class `ProductDownload`
* Remove parameter 2 `$admin` for the method `getHtmlLink` in class `ProductDownload`

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]
This probably needs a special mention in changelog, as it can have some weird side effects

**Comment by kpodemski** [comment]
Thanks @FabienPapet, noted 👍🏻

We'll go through everything at some point and have it documented.

**Review by matthieu-rolland — COMMENTED** [review]
Seems like there's an autom test that failed 3 times, what do you think @Progi1984 ?

**Comment by Progi1984** [comment]
@matthieu-rolland It's now all :green_circle:

**Comment by matthieu-rolland** [comment]
thank you !

**Pull request merged**
