### PR TITLE
Don't convert already converted currency

### PR DESCRIPTION
**Pull request by Tomkinss**
Fix convert price when in use multiple currency.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix convert price when in use multiple currency.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi @Tomkinss 

The conversion of prices from a currency to another is not good for products on FO  ?

**Comment by Tomkinss** [comment]
Hi @vincentbz 

I'm using in shop two currencies EUR and CZK. EUR is primary and all delivery options have price in EUR. Problem was in checkout process, when price was incorrectly converted from EUR to CZK. This commit fixed issue.
screen shot 2017-02-07 at 12 52 54

**Comment by vincentbz** [comment]
woh ! right the conversion is really broken for carriers. It converts twice.
Thanks to you i've also noticed it's broken for gift wrapping.

**Comment by aleeks** [comment]
@Tomkinss do you have time to do this  & re-open an other PR ?
I will merge this one.

**Comment by Tomkinss** [comment]
@aleeks yes ofcourse. I can do it.

**Pull request merged**
