### PR TITLE
Allow to translate placeholder

### LINKED ISSUE #28742: Allow to translate placeholder in create account section ( DD/MM/YYYY )
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Allow DD/MM/YY placeholder translation 

### Describe the solution you'd like

Allow DD/MM/YY placeholder translation for customer creation

### Alternatives you've considered

_No response_

### Additional context

image

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Allow to translate the date format placeholder in the customer account creation.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28742
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | See beelow
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

Test if you can translate the date format in the customer account creation, and check if the date format is correct in different languages. All date formats are stored [here](https://github.com/PrestaShop/PrestaShop/blob/develop/app/Resources/all_languages.json)

https://user-images.githubusercontent.com/5064590/174427407-0abf7cd0-4eab-4ae7-94bd-1054ff45231a.mp4

This PR close : https://github.com/PrestaShop/PrestaShop/pull/28746 beacause merge commit

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by MeKeyCool — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

Thanks for the PR!
I see no difference between the 1786 and your PR, see the attached screen record below:

https://user-images.githubusercontent.com/23308427/178304423-03ad41cc-a423-4e09-a20f-8ce31c6969ca.mp4

Please check and feedback.
Thanks!

**Comment by NeOMakinG** [comment]
> Hello @okom3pom
> 
> Thanks for the PR! I see no difference between the 1786 and your PR, see the attached screen record below:
> 
>  pr_28784.mp4 
> Please check and feedback. Thanks!

@hibatallahAouadni did you add some translations?

**Comment by ghost** [comment]
Hello @hibatallahAouadni 

You need to add something like this in  `translations/default/ShopFormsHelp.xlf`

Sorry i don't explain in the how to test

```
  <file original="classes/Tools.php" source-language="en-US" target-language="en" datatype="plaintext">
    <body>
      <trans-unit id="8df34bb962577b90d574a51ed2ca757f">
        <source>YYYY</source>
        <target>YYYY</target>
      </trans-unit>
    </body>
  </file>
  <file original="classes/Tools.php" source-language="en-US" target-language="en" datatype="plaintext">
    <body>
      <trans-unit id="350bfcb1e3cfb28ddff48ce525d4f139">
        <source>DD</source>
        <target>DD</target>
      </trans-unit>
    </body>
  </file>
  <file original="classes/Tools.php" source-language="en-US" target-language="en" datatype="plaintext">
    <body>
      <trans-unit id="ad05f78187c942f9dd521605fa81f1ba">
        <source>MM</source>
        <target>MM</target>
      </trans-unit>
    </body>
  </file>
```

After go to Translation and a translation for languages.

**Comment by hibatallahAouadni** [comment]
Hello @okom3pom 

LGTM, QA :heavy_check_mark: 

image

Thanks!

**Comment by matthieu-rolland** [comment]
thank you @okom3pom and @hibatallahAouadni !

**Pull request merged**
