### PR TITLE
Allow import combination with a quantity of 0

### PR DESCRIPTION
**Pull request by maidmaid**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This change allow to import qty change for a combination product to set qty to 0 |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | no |
| How to test? |  |

Currently, it's not possible to import a combination with a quantity of 0 because stock updating depends of the next condition `if (isset($info['quantity']) && (int)$info['quantity'])` and this condition converts 0 to false.

### CODE REVIEW

**Comment by xBorderie** [comment]
Hello @maidmaid! Thank you for this PR!

Could you [update your commit's name](https://help.github.com/articles/changing-a-commit-message/) so that it follows [the guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)?

Thank you!

**Comment by maidmaid** [comment]
Hello @xBorderie! I done, it's ok as is?

**Comment by xBorderie** [comment]
Great, thank you!
Now it's up to the Core developers to find time to review it.
Cheers!

**Comment by aleeks** [comment]
Hello @maidmaid 
Thank you!!! and sorry for the late answer! :smile:

**Pull request merged**
