### PR TITLE
Remove deprecated into GroupReduction

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in GroupReduction
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `GroupReduction::getGroupByCategoryId()`
* Removed method : `GroupReduction::getGroupReductionByCategoryId()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26307)

### CODE REVIEW

**Review by tegbessou — APPROVED** [review]
Thanks for the PR! LGTM

**Review by Progi1984 — COMMENTED** [review]
@PrestaEdit Could you document the BC Break, please ?

**Comment by PrestaEdit** [comment]
Hi,

Not able to document it, it's a BC break as we remove code. Likely other PR having deprecated removed code, it will BC break existing modules using them, isn't it ?

**Comment by Progi1984** [comment]
@PrestaEdit In the PR, check the block `BC Break`. We need to know which methods have been removed for documenting it.

**Review by Progi1984 — APPROVED** [review]

**Comment by PrestaEdit** [comment]
> @PrestaEdit In the PR, check the block `BC Break`. We need to know which methods have been removed for documenting it.

Thanks, I will do it for others ones, so. ;)

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @PrestaEdit

**Pull request merged**
