### PR TITLE
Add a new hook on dashboard

### PR DESCRIPTION
**Pull request by AntoineMille**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR adds a new hook called dashboardTop on dashboard
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2242
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by aleeks** [comment]
Add the insertion into 1.7.1.0.sql please @AntoineMille

**Comment by aleeks** [comment]
have you try a module to this hook ?

**Comment by maximebiloe** [comment]
Yes, I did with him

**Comment by aleeks** [comment]
Thank you @AntoineMille

**Comment by vincentbz** [comment]
ola

**Pull request merged**
