### PR TITLE
Update toCamelCase

### PR DESCRIPTION
**Pull request by neoteknic**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         |  improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | http://sandbox.onlinephpfunctions.com/code/a4e0f966c5bb23c935cafb08fc74be53587ed429

Fix php 7.2 warning (create_function deprecated), hudge performances improvement too :
Benchmark (php 7.1) :
Old function : 0.836s (100k iterations)
New function : 0.066s (100k iterations)

Quick test : http://sandbox.onlinephpfunctions.com/code/a4e0f966c5bb23c935cafb08fc74be53587ed429

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8584)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Interesting, it needs to be confirmed with some tests, but this one is cleaner than #8246

**Comment by jocel1** [comment]
Why not using Doctrine Inflector instead (already included in 1.7) ?
```
if ($catapitalise_first_char) {
   return Inflector::classify($str);
} else {
   return Inflector::camelize($str);
}
```
(which is internally using an even better regexp:
```
str_replace(' ', '', ucwords(strtr($word, '_-', '  ')));
```
)

BTW it could be great to change $catapitalise_first_char to $capitalise_first_char!

**Comment by Quetzacoalt91** [comment]
And we could write it ... in CamelCase :o

**Comment by Quetzacoalt91** [comment]
Hi @neoteknic,

In order to validate the changes, would you mind adding the following code in the test class for Tools?
These examples have been taken from the installation wizard, which uses this function.

### tests/Unit/Classes/ToolsCoreTest.php
```php
    public function testCamelCaseExample()
    {
        return array(
            array('address_format', 'addressFormat', false),
            array('attachment_lang', 'attachmentLang', false),
            array('attribute_group', 'attributeGroup', false),
            array('attribute_group_lang', 'attributeGroupLang', false),
            array('attribute_lang', 'attributeLang', false),
            array('carrier', 'carrier', false),
            array('carrier_group', 'carrierGroup', false),
            array('carrier_lang', 'carrierLang', false),
            array('carrier_tax_rules_group_shop', 'carrierTaxRulesGroupShop', false),
            array('carrier_zone', 'carrierZone', false),
            array('cart_product', 'cartProduct', false),
            array('cart_rule_lang', 'cartRuleLang', false),
            array('category_group', 'categoryGroup', false),
            array('category_lang', 'categoryLang', false),
            array('category_product', 'categoryProduct', false),
            array('cms_category', 'cmsCategory', false),
            array('cms_category_lang', 'cmsCategoryLang', false),
            array('cms_lang', 'cmsLang', false),
            array('cms_role', 'cmsRole', false),
            array('cms_role_lang', 'cmsRoleLang', false),
            array('configuration_kpi_lang', 'configurationKpiLang', false),
            array('configuration_lang', 'configurationLang', false),
            array('contact', 'contact', false),
            array('contact_lang', 'contactLang', false),
            array('country', 'country', false),
            array('country_lang', 'countryLang', false),
            array('customization_field_lang', 'customizationFieldLang', false),
            array('feature_lang', 'featureLang', false),
            array('feature_product', 'featureProduct', false),
            array('feature_value', 'featureValue', false),
            array('feature_value_lang', 'featureValueLang', false),
            array('gamificationtasks', 'gamificationtasks', false),
            array('gender_lang', 'genderLang', false),
            array('group_lang', 'groupLang', false),
            array('image_lang', 'imageLang', false),
            array('manufacturer_lang', 'manufacturerLang', false),
            array('meta_lang', 'metaLang', false),
            array('operating_system', 'operatingSystem', false),
            array('order_carrier', 'orderCarrier', false),
            array('order_detail', 'orderDetail', false),
            array('order_history', 'orderHistory', false),
            array('order_message', 'orderMessage', false),
            array('order_message_lang', 'orderMessageLang', false),
            array('order_return_state', 'orderReturnState', false),
            array('order_return_state_lang', 'orderReturnStateLang', false),
            array('order_state', 'orderState', false),
            array('order_state_lang', 'orderStateLang', false),
            array('product_attribute', 'productAttribute', false),
            array('product_attribute_combination', 'productAttributeCombination', false),
            array('product_attribute_image', 'productAttributeImage', false),
            array('product_lang', 'productLang', false),
            array('product_supplier', 'productSupplier', false),
            array('profile_lang', 'profileLang', false),
            array('quick_access', 'quickAccess', false),
            array('quick_access_lang', 'quickAccessLang', false),
            array('range_price', 'rangePrice', false),
            array('range_weight', 'rangeWeight', false),
            array('risk_lang', 'riskLang', false),
            array('search_engine', 'searchEngine', false),
            array('specific_price', 'specificPrice', false),
            array('stock_available', 'stockAvailable', false),
            array('stock_mvt_reason', 'stockMvtReason', false),
            array('stock_mvt_reason_lang', 'stockMvtReasonLang', false),
            array('store_lang', 'storeLang', false),
            array('supplier_lang', 'supplierLang', false),
            array('supply_order_state', 'supplyOrderState', false),
            array('supply_order_state_lang', 'supplyOrderStateLang', false),
            array('tab', 'tab', false),
            array('tax_lang', 'taxLang', false),
            array('warehouse', 'warehouse', false),
            array('web_browser', 'webBrowser', false),
            array('zone', 'zone', false),
            // True
            array('supplier_lang', 'SupplierLang', true),
            array('supply_order_state', 'SupplyOrderState', true),
            array('supply_order_state_lang', 'SupplyOrderStateLang', true),
            array('tab', 'Tab', true),
        );
    }

    /**
     * @dataProvider testCamelCaseExample
     */
    public function testToCamelCase($source, $expected, $firstCharUpperCase)
    {
        $actual = Tools::toCamelCase($source, $firstCharUpperCase);
        $this->assertEquals($expected, $actual, "Expected $source to be $expected in camel case, got $actual instead.");
    }

```

**Comment by Quetzacoalt91** [comment]
Added tests on the concerned function

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by jocel1** [comment]
No Inflector::classify / camelize usage finally ?

**Comment by Quetzacoalt91** [comment]
Not in this PR. I'd rather keep the changes suggested by the original author, and if somebody wants another solution, it is better to open a new PR.

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @neoteknic and @Quetzacoalt91

**Pull request merged**
