### PR TITLE
Add an exit button in tablet and phone menu

### LINKED ISSUE #30382: Add an exit button in tablet and phone menu
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Today, you can only leave the menu by clicking outside. Even though this is a common behavior today, there is no indication. This can lose the less technology-savvy users.

### Describe the solution you'd like

It would be better to have the same behavior as dotcom (clicking outside and exit button).

### Alternatives you've considered

_No response_

### Additional context

image

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by JBLach**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Adding a button to close the menu on mobile devices, close-up of the menu on the subpages and on the main page
| Type?             | improvement
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | Screenshots below
| Fixed ticket?     | Fixes #30382

# Main page 
image

# Subpages
image

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by djoelleuch — COMMENTED** [review]
Hello @JBLach  ,
I have checked your PR.

- The automated tests are NOK (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4574007307)
-   The position of the button is not in the right place and it's not working ! 

**Main page :**
image

**Subpages**
for the sub page , the button does not exist 
image



Could you please check it please ?

Thank You!

**Comment by kpodemski** [comment]
@djoelleuch 

You didn't compile the assets, or you didn't clear the cache after compiling the assets. You also haven't checked the changes on the mobile viewport.

@PrestaShop/qa-automation I don't think auto-tests are related, please confirm.

**Comment by Progi1984** [comment]
@kpodemski Before continuing, it seems the issue is not validated by PM.

@djoelleuch Could you restart failed UI Tests ?

**Comment by MatShir** [comment]
LGTM !!!

**Review by djoelleuch — APPROVED** [review]
Hello @JBLach , 
LGTM , it's QA :heavy_check_mark: 

image
image
Thank you !

**Comment by nicosomb** [comment]
Thank you @JBLach !

**Pull request merged**
