### PR TITLE
Merge 177x to develop 2021/02/02 [merge]

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 177x to develop 2021/02/02
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

Conflicts solved on the following files
```
install-dev/data/xml/hook.xml
src/PrestaShopBundle/Resources/views/Admin/Common/Grid/Blocks/table.html.twig
tests/UI/pages/BO/international/languages/add.js
tests/UI/pages/BO/shipping/preferences/index.js
themes/classic/templates/_partials/breadcrumb.tpl
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23108)

### CODE REVIEW

**Comment by PululuK** [comment]
@matks I just update the PR title to fix https://github.com/PrestaShop/PrestaShop/pull/22842

**Comment by matks** [comment]
> @matks I just update the PR title to fix #22842

Thank you 👍

**Review by PululuK — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Oh about the title the `[merge]` blocking feature, it's a nice idea but we need to put it a the end because the Changelog generating tool refuses PR titles which starts with `[` or any exotic symbol

**Comment by matks** [comment]
> Oh about the title the `[merge]` blocking feature, it's a nice idea but we need to put it a the end because the Changelog generating tool refuses PR titles which starts with `[` or any exotic symbol

Could we create a GitHub Action that refuses PRs that have an invalid title?

**Comment by PululuK** [comment]
We can improve https://github.com/PrestaShop/PrestaShop/pull/22842 to use  [endswith](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#endswith) instead of [contains](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contains)

**Comment by PierreRambaud** [comment]
Thank you @matks

**Pull request merged**
