### PR TITLE
Fix images quickview also updating product page by changing product i…

### LINKED ISSUE #9919: [BOOM-3664] Quickview - Related products with combinations change product page after changing a combination
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3664).

- _**Reporter:**_ stkado
- _**Created at:**_ Thu, 17 Aug 2017 14:46:51 +0200

<p>Hello, i ve the same issue of this ticket <br/>
<a href="http://forge.prestashop.com/browse/BOOM-1878" class="external-link" rel="nofollow">http://forge.prestashop.com/browse/BOOM-1878</a></p>

<p>but here the product page also changes.</p>

<p>When i change quickview attribute i ve 2 POST (cf post.png)</p>
        
* How to reproduce the issue ?

- Set product with attributes and related product
<br/>
- go to product page in FO
<br/>
- quickview on the related product
<br/>
- change attribute (S to M for exemple)

### PR DESCRIPTION
**Pull request by NeOMakinG**
…mages selectors

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | See https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-672781474
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9919
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/9919#issuecomment-672781474

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20555)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
But :vomiting_face: about the selector :sweat_smile:

**Comment by NeOMakinG** [comment]
> But 🤮 about the selector 😅

We can't do more, otherwise we'll introduce breaking changes on 3 part of codes, and we already paid it on 1.7.6 :/

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
> > But 🤮 about the selector 😅
> 
> We can't do more, otherwise we'll introduce breaking changes on 3 part of codes, and we already paid it on 1.7.6 :/

I approve the PR 👍 

Maybe we should start building a system to manage selectors backward compatibility ? Else we will keep adding these vey heavy selectors everywhere.

A JS file with "official selectors and their aliases" ?
A deprecation tag for selectors ?
A document where we explain what selectors are "protected against BC break" and what selectors are not ?

**Comment by NeOMakinG** [comment]
I think we're a bit stuck with this until next major, we could refacto a lot of selectors

**Comment by ngodefroy** [comment]
I reproduced the bug introduced by @khouloudbelguith on develop with the scenario described in the video.

Capture d’écran 2020-08-13 à 16 35 20

**Comment by NeOMakinG** [comment]
hey @ngodefroy , 

This PR doesn't aim this bug, but the bug with the picture when you change color combination on a quickview of a related product

The other bug is not related at all and should be inside another issue I think (it's backend issue if I'm right)

**Comment by ngodefroy** [comment]
@NeOMakinG I did not change the color but I added a product from a quickview related product. Isn't it related? If not, I will open another issue.

**Comment by NeOMakinG** [comment]
What should be tested is the fact that if you change color inside a quickview of related product (a tshirt from white to black for example), the photo of the main product page shouldn't be changed (but photo inside quickview should change)

**Comment by ngodefroy** [comment]
> What should be tested is the fact that if you change color inside a quickview of related product (a tshirt from white to black for example), the photo of the main product page shouldn't be changed (but photo inside quickview should change)

Test ok

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Pull request merged**
