### PR TITLE
Split grid service definitions in separate files

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | `grid.yml` is getting bigger and bigger with each migrated page, so it would be nice to split grid services into different files.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | All new list (grid) pages should be working.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10486)

### CODE REVIEW

**Comment by matks** [comment]
@sarjon Idea is great 👍 however I think since this PR was done 29 days ago, now `src/PrestaShopBundle/Resources/config/services/core/grid.yml` has probably grown again. Shall we redo the PR for the update grid.yml ?

I promise I will merge it quick 🙏

**Comment by mickaelandrieu** [comment]
ping @sarjon :angel:

**Comment by sarjon** [comment]
@matks i've rebased it, would be nice to merge it. :)

**Comment by matks** [comment]
No need for QA as I tested using Symfony container dumps ✅

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thanks @sarjon

**Pull request merged**
