### PR TITLE
Inherit `AbstractType` instead of `ChoiceType`

### PR DESCRIPTION
**Pull request by FabienPapet**
Signed-off-by: Fabien Papet <fabien.papet@gmail.com>

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Extending form types should be done with `getParent` and not with PHP extend
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Currency selection, should still work as intended

### CODE REVIEW

**Comment by lartist** [comment]
Regarding the function getBlockPrefix, It seems to me a default value is automatically set. Why sometimes are you adding this function and at other times you're not ?

**Comment by FabienPapet** [comment]
Because some of them are not just select types, but have their own display

**Review by mflasquin — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Comment by lartist** [comment]
> Because some of them are not just select types, but have their own display

I've just understood you just moved the block_prefix from the setDefaults method to getBlockPrefix method 👍

**Review by florine2623 — APPROVED** [review]
Hello @FabienPapet ,

Checked Currency selector in FO :
Screenshot 2023-05-02 at 14 37 23

In BO > Orders
Screenshot 2023-05-02 at 14 34 49

In BO > Localization 
Screenshot 2023-05-02 at 14 35 29

In PPV2 > Pricing tab
Screenshot 2023-05-02 at 14 36 45

In BO > Cart rules
Screenshot 2023-05-02 at 14 39 15

In BO >  Catalog price rules
Screenshot 2023-05-02 at 14 39 51

All is OK
It is QA ✅

**Comment by nicosomb** [comment]
Thank you @FabienPapet !

**Pull request merged**
