### PR TITLE
Make sure shop list in header is scrollable with lot of items

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
This PR is the same as #8426 by @soee, closed because the changes could be applied to a temporary environment for tests.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | This small PR ads 2 new styles to shop list in the backend (in both default and new theme) `overflow-y: auto;` and `max-height: 500px`. This change won't affect any user that have less than 15 shops (14 or less shops list shouldn't render outside our container with `max-height` set to `500px`) on one instance (multistore enabled). So when the list will be much longer (we have atm. ~ 500 shops) thanks to this change shop list will render scrollbar on the rightside that will allow admins to scroll the list. Before this chnage with long list shop users were unable to reach items rendered outside of visible website area. Please check posted link to ticket on Forge where you can see on 2 screenshots how the list behaves without and with proposed chnages.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3016
| How to test?  | Create 15 or more shops in multistore mode, apply styles added in the commits to admin themes, toggle shop list in backend header when there is less than 15 shops and when there is 15 shops or more.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8500)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8500#-:-Kz-Hyb8RRQmR1f-W1-q:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]

**Comment by soee** [comment]
@Quetzacoalt91 thank you for taking care of it :)

**Comment by eternoendless** [comment]
Looks like the compiled assets are missing 🤔

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 can you commit the compiled assets? Also, are you sure this is for 1.7.3.1 and not 1.7.3.0?

**Comment by Quetzacoalt91** [comment]
We can wait the next release. And I don't compile the assets to avoid rebasing later. :p

**Review by eternoendless — DISMISSED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @Quetzacoalt91

**Pull request merged**
