### PR TITLE
Merge 81x develop 160323

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop 160323
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI tests green and https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4435427840 green
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by zuk3975 — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]
Approved for UI tests

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I just launched Automated Tests : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4436273255

**Comment by hibatallahAouadni** [comment]
Hello @jolelievre 

Thanks @Progi1984 :pray: 
@jolelievre I see that **`BO - Catalog - Cart rules : Case 11 - Carrier Restriction`** has been failed, could you please check :pray: 

image

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni I restarted automated tests. The CI is now :green_circle:.

**Comment by boubkerbribri** [comment]
We have the green light, go merge

**Pull request merged**
