### PR TITLE
Limit the size of changelog for module updates

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Some modules add very long changelog on Modules > Module manager : Update tab. This fix limits its size to make whole page more compact.
| Type?             | improvement
| Category?         |  BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Needs update available for modules with long changelog eg. ps_metrics, ps_facebook, ps_mbo
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   |  ~

### Before
obraz

### After
psupdates

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]
nice improvement

**Review by kpodemski — DISMISSED** [review]

**Comment by SharakPL** [comment]
Fixes #27752

**Review by djoelleuch — COMMENTED** [review]
Hello @SharakPL  , 
 I have checked your PR. I think that the improvement is good for the modules of  very long changelog but i think it has no added value for the modules with a short description .
see the attached screenshot below :
**Without PR** 
image

**With PR** 

image
 
Please check and feedback.
Thanks!

**Comment by SharakPL** [comment]
Thanks @djoelleuch. Turns out `.pre-scrollable` isn't the best for this as it always adds scrollbar. I'll fix it with custom class.

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Gruttersshop** [comment]
> Thanks @djoelleuch. Turns out `.pre-scrollable` isn't the best for this as it always adds scrollbar. I'll fix it with custom class.

[SharakPL](https://github.com/SharakPL) Some 1 stop the merge? What we where doing? Is this a person that is  top of of you like your boss?

**Review by djoelleuch — COMMENTED** [review]
Hello @SharakPL  , 
I think that the custom class doesn't work .
 See screen-record  below : 

[Untitled_ Mar 6, 2023 3_25 PM.webm](https://user-images.githubusercontent.com/115152460/223138462-54b21f97-bcf0-4268-b62f-1a15c88de26f.webm)

Can you check please .
thanks !

**Comment by SharakPL** [comment]
@djoelleuch you need to rebuild assets of admin's new-theme after applying the PR.
```sh
cd admin-dev/themes/new-theme
npm run build
```

**Review by djoelleuch — APPROVED** [review]
Hello @SharakPL ,
LGTM , it's QA  :heavy_check_mark: 
image

Thank you ! :rocket:

**Comment by SharakPL** [comment]
Thanks @djoelleuch

**Pull request merged**
