### PR TITLE
Added npm to the docker image needed to build assets

### PR DESCRIPTION
**Pull request by amery**
prestashop-git_1  | * Build assets ...
prestashop-git_1  | ./tools/assets/build.sh
prestashop-git_1  | >>> Building admin default theme...
prestashop-git_1  | ~/html/admin-dev/themes/default ~/html

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The init script on .docker expects to find npm to build the assets
| Type?             | bug fix
| Category?         | NA
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | `docker-compose up`
| Possible impacts? | slower start times

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26562)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@amery Not sure about this one, isnt npm shipped with NodeJS?

**Comment by amery** [comment]
> @amery Not sure about this one, isnt npm shipped with NodeJS?

@NeOMakinG it's a separate package. If you start the container and watch the logs you'll see it complaining npm isn't found

**Review by NeOMakinG — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
> > @amery Not sure about this one, isnt npm shipped with NodeJS?
> 
> @NeOMakinG it's a separate package. If you start the container and watch the logs you'll see it complaining npm isn't found

Oh btw, maybe it's time to update the dockerfile in order to use npm 14 with node 7? Don't know if it use the right version atm @PierreRambaud

**Comment by amery** [comment]
@NeOMakinG I'm using node 16 (latest lts) and npm 8.1.3 without problems. should I extend this PR or make a new one?

**Comment by NeOMakinG** [comment]
Wut? I thought builds were crashing using node 16, did try to build some weeks ago with this version and it wasn't possible

Feel free to do it in this PR

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-maintainers Shouldn't we have a Github Action for checking that `docker-compose up` runs well ? What do you think about this ?

**Comment by PierreRambaud** [comment]
> @PrestaShop/prestashop-maintainers Shouldn't we have a Github Action for checking that `docker-compose up` runs well ? What do you think about this ?

Really, I don't think so, it depends on many things, how packages dependencies evolve.
Also, we can't accept it for the 1.7.8.x, as it concerns only the development mode, so the develop branch is enough.
I also use latest images from docker and I didn't get any errors:
image

When you use docker-compose, be aware of images, use `docker-compose up --force-recreate --build`

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I don't manage to reproduce the issue and the fix shouldn't be merged on the 1.7.8.x branch

**Comment by amery** [comment]
> I don't manage to reproduce the issue and the fix shouldn't be merged on the 1.7.8.x branch

this is the current output of the build where you can see `npm` is not being installed. suggested but not installed. @PierreRambaud 

```
Step 7/9 : RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
 ---> Running in 9ac7e4d39faf

================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 10.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" (recommended)
   * https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================

Continuing in 20 seconds ...


## Installing the NodeSource Node.js 10.x repo...


## Populating apt-get cache...

+ apt-get update
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [92.5 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8180 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
Fetched 8474 kB in 2s (4523 kB/s)
Reading package lists...

## Installing packages required for setup: lsb-release gnupg...

+ apt-get install -y lsb-release gnupg > /dev/null 2>&1

## Confirming "bullseye" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_10.x/dists/bullseye/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 10.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_10.x bullseye main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_10.x bullseye main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Get:4 https://deb.nodesource.com/node_10.x bullseye InRelease [4586 B]
Get:5 https://deb.nodesource.com/node_10.x bullseye/main amd64 Packages [769 B]
Fetched 5355 B in 1s (7400 B/s)
Reading package lists...

## Run `sudo apt-get install -y nodejs` to install Node.js 10.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Removing intermediate container 9ac7e4d39faf
 ---> 82ff23af5c55
Step 8/9 : RUN apt install -y nodejs
 ---> Running in 7f4a5d2b163b

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  javascript-common libc-ares2 libjs-highlight.js libnode72 libuv1 nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  javascript-common libc-ares2 libjs-highlight.js libnode72 libuv1 nodejs
  nodejs-doc
0 upgraded, 7 newly installed, 0 to remove and 28 not upgraded.
Need to get 11.7 MB of archives.
After this operation, 50.9 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 javascript-common all 11+nmu1 [6260 B]
Get:2 http://deb.debian.org/debian bullseye/main amd64 libc-ares2 amd64 1.17.1-1+deb11u1 [102 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 libjs-highlight.js all 9.18.5+dfsg1-1 [397 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 libuv1 amd64 1.40.0-2 [132 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 libnode72 amd64 12.22.5~dfsg-2~11u1 [8333 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 nodejs amd64 12.22.5~dfsg-2~11u1 [147 kB]
Get:7 http://deb.debian.org/debian bullseye/main amd64 nodejs-doc all 12.22.5~dfsg-2~11u1 [2545 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 11.7 MB in 0s (70.4 MB/s)
Selecting previously unselected package javascript-common.
(Reading database ... 17744 files and directories currently installed.)
Preparing to unpack .../0-javascript-common_11+nmu1_all.deb ...
Unpacking javascript-common (11+nmu1) ...
Selecting previously unselected package libc-ares2:amd64.
Preparing to unpack .../1-libc-ares2_1.17.1-1+deb11u1_amd64.deb ...
Unpacking libc-ares2:amd64 (1.17.1-1+deb11u1) ...
Selecting previously unselected package libjs-highlight.js.
Preparing to unpack .../2-libjs-highlight.js_9.18.5+dfsg1-1_all.deb ...
Unpacking libjs-highlight.js (9.18.5+dfsg1-1) ...
Selecting previously unselected package libuv1:amd64.
Preparing to unpack .../3-libuv1_1.40.0-2_amd64.deb ...
Unpacking libuv1:amd64 (1.40.0-2) ...
Selecting previously unselected package libnode72:amd64.
Preparing to unpack .../4-libnode72_12.22.5~dfsg-2~11u1_amd64.deb ...
Unpacking libnode72:amd64 (12.22.5~dfsg-2~11u1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../5-nodejs_12.22.5~dfsg-2~11u1_amd64.deb ...
Unpacking nodejs (12.22.5~dfsg-2~11u1) ...
Selecting previously unselected package nodejs-doc.
Preparing to unpack .../6-nodejs-doc_12.22.5~dfsg-2~11u1_all.deb ...
Unpacking nodejs-doc (12.22.5~dfsg-2~11u1) ...
Setting up javascript-common (11+nmu1) ...
apache2_invoke: Enable configuration javascript-common
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of reload.
Setting up libc-ares2:amd64 (1.17.1-1+deb11u1) ...
Setting up libuv1:amd64 (1.40.0-2) ...
Setting up libjs-highlight.js (9.18.5+dfsg1-1) ...
Setting up libnode72:amd64 (12.22.5~dfsg-2~11u1) ...
Setting up nodejs-doc (12.22.5~dfsg-2~11u1) ...
Setting up nodejs (12.22.5~dfsg-2~11u1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/js.1.gz because associated file /usr/share/man/man1/nodejs.1.gz (of link group js) doesn't exist
Processing triggers for libc-bin (2.31-13) ...
Removing intermediate container 7f4a5d2b163b
 ---> 984da71850a1
Step 9/9 : CMD ["/tmp/docker_run_git.sh"]
 ---> Running in 5f5bd23777dc
Removing intermediate container 5f5bd23777dc
 ---> 23036d906339
Successfully built 23036d906339
```

**Comment by amery** [comment]
> Wut? I thought builds were crashing using node 16, did try to build some weeks ago with this version and it wasn't possible
> 
> Feel free to do it in this PR

@NeOMakinG I have to admit I'm currently using my [own alpine-based image](https://github.com/amery/docker-services/blob/master/alpine/php7/latest/Dockerfile), and THERE node16 works fine. I'll see what I can do on this debian-based one now.

**Comment by amery** [comment]
so, after some testing npm 8.1.0 **IS** bundled in nodejs 16.x as @PierreRambaud suggested but not on 10.x

sticking to 10.x:

```
diff --git a/.docker/Dockerfile b/.docker/Dockerfile
index 7d87becaaf..48346c8369 100644
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -11,6 +11,7 @@ RUN mkdir -p /var/www/.npm
 RUN chown -R www-data:www-data /var/www/.npm
 
 RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
-RUN apt install -y nodejs
+RUN apt install -y nodejs \
+       && npm --version
 
 CMD ["/tmp/docker_run_git.sh"]
```
 fails, no `npm`

```
/bin/sh: 1: npm: not found
The command '/bin/sh -c apt install -y nodejs 	&& npm --version' returned a non-zero code: 127
```

but when switching to 16.x npm is there, at 8.1.0 and bundled in the nodejs package

```
diff --git a/.docker/Dockerfile b/.docker/Dockerfile
index 7d87becaaf..2dc0951b10 100644
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -10,7 +10,10 @@ COPY /docker_run_git.sh /tmp/
 RUN mkdir -p /var/www/.npm
 RUN chown -R www-data:www-data /var/www/.npm
 
-RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
-RUN apt install -y nodejs
+RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
+RUN apt install -y nodejs \
+       && dpkg -S `which npm` \
+       && npm i -g npm@8.1.3 \
+       && npm --version
 
 CMD ["/tmp/docker_run_git.sh"]
```

```
Step 8/9 : RUN apt install -y nodejs 	&& dpkg -S `which npm` 	&& npm i -g npm@8.1.3 	&& npm --version
 ---> Running in 92bac145a308

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 28 not upgraded.
Need to get 25.8 MB of archives.
After this operation, 120 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_16.x bullseye/main amd64 nodejs amd64 16.13.0-deb-1nodesource1 [25.8 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 25.8 MB in 0s (81.7 MB/s)
Selecting previously unselected package nodejs.
(Reading database ... 17744 files and directories currently installed.)
Preparing to unpack .../nodejs_16.13.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (16.13.0-deb-1nodesource1) ...
Setting up nodejs (16.13.0-deb-1nodesource1) ...
nodejs: /usr/bin/npm

removed 2 packages, changed 15 packages, and audited 219 packages in 3s

10 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New patch version of npm available! 8.1.0 -> 8.1.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.3>
npm notice Run `npm install -g npm@8.1.3` to update!
npm notice 
8.1.3
Removing intermediate container 92bac145a308
 ---> e872f7275f5b
Step 9/9 : CMD ["/tmp/docker_run_git.sh"]
 ---> Running in a392b4b12e06
Removing intermediate container a392b4b12e06
 ---> ad11a73d3f52
Successfully built ad11a73d3f52
```

**Comment by amery** [comment]
@Progi1984 @NeOMakinG apologies for the mess, I hadn't realised my 1.7.8.x branch was directly bound to the PR.

changes:
* rebased on top of the latest 1.7.8.x
* still adds npm to 10.x
* then upgrades to node 16.x and latest npm.

reasoning explained in the previous comment.

**Comment by amery** [comment]
> Also, we can't accept it for the 1.7.8.x, as it concerns only the development mode, so the develop branch is enough.

@PierreRambaud More than having or having not `npm`, and so being able to build assets, I suppose the key issue in stable vs develop in this case is 1.7.8.x carries package-lock files that require format updating when switching to a non-deprecated version of node... 

should I close this and try to get node 16 on  _develop_? I still see not having `npm` on the recommended docker-compose system as a bug for `1.7.8.x` though.

**Comment by NeOMakinG** [comment]
@amery https://devdocs.prestashop.com/1.7/development/compile-assets/

I think we can upgrade to node 14 for 1.7.8.x, and maybe we could try to improve the current NodeJS version of develop and change the table on this page: https://devdocs.prestashop.com/8/development/compile-assets/

**Comment by amery** [comment]
> @amery https://devdocs.prestashop.com/1.7/development/compile-assets/
> 
> I think we can upgrade to node 14 for 1.7.8.x, and maybe we could try to improve the current NodeJS version of develop and change the table on this page: https://devdocs.prestashop.com/8/development/compile-assets/

sounds good, I'll close this PR and work on that :)

**Comment by NeOMakinG** [comment]
> > @amery https://devdocs.prestashop.com/1.7/development/compile-assets/
> > I think we can upgrade to node 14 for 1.7.8.x, and maybe we could try to improve the current NodeJS version of develop and change the table on this page: https://devdocs.prestashop.com/8/development/compile-assets/
> 
> sounds good, I'll close this PR and work on that :)

Feel free to ask me if you need some help

**Pull request closed without merging**
