### PR TITLE
Fix css for search dropdown in combination generator

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/32360. The dropdown background fix was easy, but there was another issue (which probably existed for a while already) - whenever you click on dropdown to select the attribute it would close whole modal. I couldn't find any better solution, but to disable the ability to close the modal when you click outside of it.
| Type?             | bug fix
| Category?         |  BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/32360 (also the modal will not close when clicked outside now. Thats a side effect of main fix, but couldn't find a better solution for now :sweat: )
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/32360
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by zuk3975** [comment]
css is fixed but there is also some other problem that persists. When you click on dropdown item the whole modal closes. It may be related to click-outside.js directive, but i couldn't yet find out why/how.

**Comment by zuk3975** [comment]
for a quick fix I turned off the ability to close the modal when clicking outside of it (you can still close it by "X" icon or "Cancel"). Couldn't find better fix.

**Review by FabienPapet — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by djoelleuch — DISMISSED** [review]
Hello @zuk3975  ,
I have checked your PR the issue is well fixed ,
Automated tests --> OK (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4935228747/jobs/8821273952 )

[Untitled_ May 10, 2023 12_03 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/269dbe23-1793-437b-908d-25bd2f632285)


It's QA approved :heavy_check_mark:
Thank you for your PR :rocket:

**Comment by zuk3975** [comment]
Apparently I fixed it on wrong branch, it must target 8.1.x. Created a new PR for that, sorry for confusion.
https://github.com/PrestaShop/PrestaShop/pull/32509

**Pull request closed without merging**
