### PR TITLE
Merge 8.1.x into develop 13/03/23

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop branch
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI tests green and auto campaign green https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4408722648
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4408722648

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Comment by boubkerbribri** [comment]
OK for UI tests : 
API: Normal, it does fail does not work on 8.1.x
Design - Linkwidget : Error not linked to the PR
International : all good for me
If does not need test, we can QA :white_check_mark:

**Review by matthieu-rolland — COMMENTED** [review]
Can this be merged @jolelievre  ?

**Comment by nicosomb** [comment]
Thank you @jolelievre

**Pull request merged**
