### PR TITLE
jQuery it's loaded yet

### PR DESCRIPTION
**Pull request by arturu**
jQuery it's loaded yet from core.js

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.5.x / 1.6.1.x / 1.7.4.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix / improvement / new feature / refacto / critical
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes an [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct: Yes

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11024)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @arturu,

would you mind to complete the pull request description (i.e the table on the top)
so we can manage to review?

Mickaël

**Comment by eternoendless** [comment]
Looks like jQuery is already included in the core theme, so maybe we don't need to include it again in Classic?

**Comment by PierreRambaud** [comment]
Even if we don't include it in the core.js, this can be require in package.json in order to add use an other dependency.
If not, the package-lock file must be updated.

**Comment by PierreRambaud** [comment]
Hi @arturu 

Since we had no news from you for more than 30 days, I'll close this pull request

Thanks!

**Pull request closed without merging**
