### PR TITLE
Merge 1.7.8.7 into 1.7.8.x [merge]

### PR DESCRIPTION
**Pull request by atomiix**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Merge release branch 1.7.8.7-release into 1.7.8.x
| Type?             | bug fix
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Comment by doekia** [comment]
This release is buggy. Please urgently contact me so we can fix-it (1.7.8.8) before we ruin everything

**Comment by kpodemski** [comment]
@doekia what do you mean? are you referring to the blockwishlist module or the fix in this release?

**Review by matthieu-rolland — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @atomiix

**Comment by matks** [comment]
@doekia If there is a security issue please send an email to security@prestashop.com . If there is no security matter and it's simple bugs please share your findings in this pull request it will be more transparent and everyone will be able to work on the topic.

**Comment by doekia** [comment]
mail sent

**Pull request merged**
