### PR TITLE
[*] Modules : Enable updatePosition() at the  module's installation

### PR DESCRIPTION
**Pull request by Eolia**
Allows you to use $this->updatePosition($ id_hook, $ way, $ position) after the attachment of a new module to a hook.
Currently impossible, because : if (! Isset ($ res [$ k + 1])).
The new module is inevitably in last place, so, $ res [$ k + 1] does not exist and the function always returns false.
Tested in normal mode, ajax and on module install.

### CODE REVIEW

**Comment by Eolia** [comment]
Allo ?

**Comment by mickaelandrieu** [comment]
Yeah, sorry.

Ping me if I forgot this pull request more than 10 days.

Mickaël

**Comment by Shudrum** [comment]
Hi!

Please use spaces instead of tabulations please.

Thank you!

**Comment by Eolia** [comment]
@mickaelandrieu Ping!... (One month)

**Comment by mickaelandrieu** [comment]
@Eolia can you squash your commits ? looks good to me :)

**Comment by Eolia** [comment]
Sorry, but i don't understand the "squash" ?

**Comment by kpodemski** [comment]
Google for `git squash`

**Comment by Shudrum** [comment]
And there is still tabs.

**Comment by Eolia** [comment]
I do not understand.
Merge or not, the code is written, we will not discuss 2 years.
Bye

**Comment by xBorderie** [comment]
Well, to sum it up:

* You have several commits when only one is needed: through the command line, please try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request). [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).
* Your code uses tabulations instead of spaces for its indentation, which clashes with our [PHP coding standards](http://doc.prestashop.com/display/PS16/Coding+Standards). Please update your code to use tabulations.

That's it! Thank you!

**Pull request closed without merging**
