### PR TITLE
Cms page category listing position update

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This Pr brings some position update functionality for cms category page located in **admin-dev/index.php/improve/design/cms-pages/**
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #10567
| How to test?  | Try dragging functionality - this should work as in legacy page.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12974)

### CODE REVIEW

**Comment by tomas862** [comment]
Hi @jolelievre - I faced some limitations while using `PositionColumn`:
1. I can't use it with an ajax request - after each drag page is being refresed. Is this how it should be? :thinking: 
2. Got a weird filter position

Screenshot(1)

I think about the first problem we need to add anohter position-extension which would be called something like : `asynch-position-extension`
about the second problem I think its a bug so again, we should fix it :slightly_smiling_face:

**Comment by tomas862** [comment]
Hi @matks - faced some problems in cms category page:

Screenshot(2)

when you are in multishop and have shared cms categories for both shops then the positions are also shared because they are localed in `ps_cms_category` table. So when you drag in single shop you are actually dragging for all shops where the cms category page is assigned.

The same problem exists in non migrated page as well

its not possible to make this work well if we don't restructure the table and assign position in `
ps_cms_category_shop` instead - although this will require to update all the legacy sqls where the position is used and also in all shop context position stuff will not work.

**Comment by jolelievre** [comment]
Hi @tomas862,

indeed the position extension doesn't manage ajax updates for now. This would be great to have this
feature but I think it will be for the next version now.

About the filter position field, I met the same problem when I tried to refactor the `CategoryPositionColumn` (unfortunately I realized that the positions are managed via a nested tree and the `PositionUpdater` does not manage this kind of algorithm yet, again this should be added in the next version so we can use `PositionColumn` only and deprecate `CategoryPositionColumn`).

I found a way to fix the field issue however, we need to modify the grid presenter:
https://github.com/PrestaShop/PrestaShop/blob/a80f3edd36a4d18fbf82ead0f35178b2abe1f57b/src/Core/Grid/Presenter/GridPresenter.php#L118

and replace the column id:

```php
if (null !== $positionColumn) {
            array_unshift($columns, [
                'id' => $positionColumn->getId().'_handle',
                'name' => $positionColumn->getName(),
                'type' => 'position_handle',
                'options' => $positionColumn->getOptions(),
            ]);
        }
```

I think this should work, you can try it.

**Comment by jolelievre** [comment]
> The same problem exists in non migrated page as well
> 
> its not possible to make this work well if we don't restructure the table and assign position in ` ps_cms_category_shop` instead - although this will require to update all the legacy sqls where the position is used and also in all shop context position stuff will not work.

Indeed it would be the best scenario, but I'm afraid we are gonna be short on time to manage all this? Wdyt?
Another solution could be to hide the position in multi shop mode, so you can only order them in the general shop context. At least for now and we can manage the proper way in the next version.

**Comment by tomas862** [comment]
> > The same problem exists in non migrated page as well
> > its not possible to make this work well if we don't restructure the table and assign position in ` ps_cms_category_shop` instead - although this will require to update all the legacy sqls where the position is used and also in all shop context position stuff will not work.
> 
> Indeed it would be the best scenario, but I'm afraid we are gonna be short on time to manage all this? Wdyt?
> Another solution could be to hide the position in multi shop mode, so you can only order them in the general shop context. At least for now and we can manage the proper way in the next version.

@jolelievre 
Yes we are short on time to do this - and its seems like a breaking change because it might interrupt existing structure of the clients which are configured positions.

Another solution.
Well yes, sounds like a plan - so I'll **disable the position column when there is at least two shops and multishop feature is enabled** - is that right?

**Comment by jolelievre** [comment]
> Another solution.
> Well yes, sounds like a plan - so I'll **disable the position column when there is at least two shops and multishop feature is enabled** - is that right?

You should be able to order them when no shop is selected in the top menu. I don't know if it's possible? I lack knowledge on multi shop architecture/behavior..

**Comment by tomas862** [comment]
> You should be able to order them when no shop is selected in the top menu. I don't know if it's possible? I lack knowledge on multi shop architecture/behavior..

Right, so the true case of how it should be on cms page:

So it should work in **all shop context** but not in the **single shop context**. Also it should work if multistore feature is disabled.

But again, thats a temporary thing due to in general it should work as it is right now in migrated category page since it has correct position database structure:

In category page the positions column works only in **single shop context**.

It soo confusing right now :rofl:

**Comment by jolelievre** [comment]
> It soo confusing right now 🤣

Agreed 😅

> So it should work in **all shop context** but not in the **single shop context**. Also it should work if multistore feature is disabled.

Yes exactly, at least I think it's the easier and cleaner way to deal with this problem for now. But one thing I'm not sure: can you detect that you are in **all shop context** ?

> But again, thats a temporary thing due to in general it should work as it is right now in migrated category page since it has correct position database structure

True ideally it should work with each shop having its own order, but as you said we need to update `cms_category_shop` to add a new position field, although it's not complicated I'm afraid we will lack time to manage this properly (especially since we need to update legacy class...)

So I wonder if we can validate this behavior for 176 version.
@colinegin @PrestaShop/prestashop-core-developers wdyt?

**Comment by jolelievre** [comment]
> It soo confusing right now 🤣
Agreed 😅

> So it should work in **all shop context** but not in the **single shop context**. Also it should work if multistore feature is disabled.

Yes exactly, at least I think it's the easier and cleaner way to deal with this problem for now. But one thing I'm not sure: can you detect that you are in **all shop context** ?

> But again, thats a temporary thing due to in general it should work as it is right now in migrated category page since it has correct position database structure

True ideally it should work with each shop having its own order, but as you said we need to update `cms_category_shop` to add a new position field, although it's not complicated I'm afraid we will lack time to manage this properly (especially since we need to update legacy class...)

So I wonder if we can validate this behavior for 176 version.
@colinegin @PrestaShop/prestashop-core-developers wdyt?

**Comment by tomas862** [comment]
@jolelievre - done all the changes. Are you sure this line https://github.com/PrestaShop/PrestaShop/pull/12974/files#diff-bf209d4ccf4cb181302188588a6bdaf0R118 won't cause any issues?

**Comment by jolelievre** [comment]
> @jolelievre - done all the changes. Are you sure this line https://github.com/PrestaShop/PrestaShop/pull/12974/files#diff-bf209d4ccf4cb181302188588a6bdaf0R118 won't cause any issues?

I don't think unless some javascript depends on it but since it's only base on classes to manage the handle I think we're good. Did you try ordering via drag and drop? And the filter?
If it works on this page I think we're good to go.

**Comment by colinegin** [comment]
Hello @tomas862 and @jolelievre, I'm probably replying a bit late. 
No rush on multistore, we are aware there are problems on both legacy and symfony pages. 
For now, I prefer that we keep the feature iso even though it's clearly not perfect, for the next version we are going to precisely examine all the multishop behaviour and architecture and then decide what we want to improve.

**Review by jolelievre — DISMISSED** [review]

**Comment by sarahdib** [comment]
@TristanLDD 
When I drag and drop the message is like this 
Capture d’écran 2019-03-29 à 16 14 10

But in categories pages the message is not the same 
capture d'écran_1266

**Comment by TristanLDD** [comment]
@sarahdib The first message is the one from the UI Kit so it should be applied on both pages

**Comment by jolelievre** [comment]
> @sarahdib The first message is the one from the UI Kit so it should be applied on both pages

@tomas862 Correct me if I'm wrong but the first notification is a flash notif from Symfony, and the second one a javascript notification right? That's why they don't look the same.
Although it would be nice to have same notifications in javascript this is not related to this issue.

**Comment by tomas862** [comment]
@jolelievre  correct :)

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @tomas862

**Pull request merged**
