### PR TITLE
Performance is better when fetching all rows at once instead of itera…

### PR DESCRIPTION
**Pull request by mickaelandrieu**
…ting over the result

Cherry picked from https://github.com/PrestaShop/PrestaShop/pull/4539

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@xBorderie don't pass the tests. Closed.

**Comment by xBorderie** [comment]
Any idea why it wouldn't pass the test? We were all convinced the PR was good, so it's sad that tests are preventing us from having better performances.

**Comment by mickaelandrieu** [comment]
I think the issue is not in this PR (I agree) but in PrestaShop and on the way we retrieve elements from database.

As I'm not sure this contribution won't break a lot of stuff, I can't accept it "as it": too much risks for a little gain.

**Comment by jocel1** [comment]
It could be interesting indeed to see why it doesn't pass the tests. I suspect an issue with cache invalidation at some point (because fetching all rows at once enable the use of the cache).
I could try to take a look at it.

**Comment by mickaelandrieu** [comment]
@jocel1 this will be realy appreciated :+1:

**Comment by xBorderie** [comment]
Thank you for you insights on this, Jocelyn!

**Comment by jocel1** [comment]
FYI, I've just pushed a new PR with a more efficient cache + fetch all rows at once in the configuration class :

https://github.com/PrestaShop/PrestaShop/pull/5106/files

On my local install, all tests are ok with this one.

**Comment by jocel1** [comment]
@mickaelandrieu : on the fetch all rows part, compared to your PR the main difference is the extra if ($result) { test before iterating on the result in the foreach. Indeed, in some tests, the configuration query is using non existing table / db name, and hence the returned $result is null, and not an array().

**Comment by mickaelandrieu** [comment]
@jocel1 I'll review it ASAP,  thanks

**Pull request closed without merging**
