### PR TITLE
Fix reference in Shopping carts view

### LINKED ISSUE #22854: Reference number of product is incorrect in Shopping Carts
When I check Shopping Carts (NOT orders) the reference of products in all shopping carts are wrong (there is product name instead reference). This problem is also in official demo of prestashop 1.7.7.1. 
In orders this problem don`t exists. Only shopping carts are affected.

To check this go to https://demo.prestashop.com/#/en/back, then Orders > Shopping Carts. Check cart and list off products in it. All reference are wrong.

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | When you visit single cart in "Sell -> Shopping Carts", product reference is wrong
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22854 
| How to test?      | Check product reference before and after this change
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22863)

### CODE REVIEW

**Review by Arman-Hosseini — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @kpodemski 

Sorry, the issue is a regression of the 1.7.7, could you rebase your PR on 1.7.7.x branch ?

**Comment by kpodemski** [comment]
Hello @marionf 

done

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM !!
Thanks @kpodemski !!

**Comment by Progi1984** [comment]
Thanks @kpodemski & @SD1982

**Pull request merged**
