### PR TITLE
[*] CORE: Allow rel="nofollow" in anchors

### PR DESCRIPTION
**Pull request by gskema**
People who are doing SEO optimization need to have this.

### CODE REVIEW

**Comment by inetbiz** [comment]
@gskema quick question: Are other html attributes for microdata allowed?

**Comment by gskema** [comment]
Probably not, but I think you should be building microdata objects in RTE editors anyway.

**Comment by inetbiz** [comment]
Hard not to consider with 1.7 I think? If you build an about page in CMS, you may need/want to include certain vocabs such as organization and person along with professionalservices.

**Comment by gskema** [comment]
@inetbiz Sure, people may want to show their info on a separate page or or page block (Like footer contacts). Although I think if an objects is entered though BO form, it should have it's own output template for FO. For example, it would be great to have a page a page with all idividual store contacts listed and marked up.

Btw this is the config page I've used http://htmlpurifier.org/live/configdoc/plain.html#Filter.Custom
Doesn't seem to be any options for `itemprop` and such, this would probably require a custom filter.

**Comment by firstred** [comment]
Looks like a good PR to me. Something we could use in 1.7.

Could you please rebase this pull request so that we can merge it? Thank you!

**Review by firstred — APPROVED** [review]

**Comment by antoin-m** [comment]
Thank you for you contribution @gskema !

I cherry-picked your commits here https://github.com/PrestaShop/PrestaShop/pull/7468

**Pull request closed without merging**
