### PR TITLE
CartRule.php - performance bottleneck - duplicating query

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | There is bug in CartRule.php, where loading time of bigger eshops is totally bottlenecked by XXXXX duplicate queries. There are multiple issues - it's getting checked against no customer ID in some cases, it's using extra queries that it doesn't need and it does so in a loop, which is just against best practices.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Nothing to test
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

# For reviewers
This part of the code only concerns the cart rules logic in "highlighted vouchers" section in cart AND in customer my account zone. It doesn't affect any calculations, validations or something.

# Before - load time 1s, 13602 queries
before

# After - load time 0.2s, 144 queries
after

# How to test
There is no change in behavior, just much simplier code and much better performance on big shops with lot of clients and addresses.

## Create following cart rule.
 - Enter some name.
 - Enter some code.
 - Set highlight to yes.
 - Set country restriction to only France.
 - Set action to Free shipping.

Snímek obrazovky 2024-04-26 164144

## Scenario A (no change here)
1. Go to FO, register yourself, add something to cart, go to cart.
2. With no address created, you can't see any voucher in the "highlighted vouchers" section. ✅
3. When you create an address with country other then France in my account zone, you can't see any voucher in the "highlighted vouchers" section. ✅
4. When you change the country in the address to France in my account zone, you can see the voucher visible in the "highlighted vouchers" section. ✅

## Scenario B (this was broken before)
1. Go to FO, clear cookies, add something to cart, go to cart. See that you can't see any voucher in the "highlighted vouchers" section. ✅
2. Go to BO, go to Catalog > Brands and create a manufacturer address with France as a country (but with id_customer 0).
2. Go to FO, go to cart.
3. See that you can't see any voucher in the "highlighted vouchers" section. ✅ (but you could before this fix, because it was using id_customer 0 to get them)

### CODE REVIEW

**Review by Hlavtox — COMMENTED** [review]
What if we do it like this? Only one query and no need to loop through the countries? :-)

```php
$meetsCountryRestriction = (bool) Db::getInstance()->getValue('
SELECT crc.id_cart_rule
FROM ' . _DB_PREFIX_ . 'cart_rule_country crc
INNER JOIN ' . _DB_PREFIX_ . 'address a ON a.id_customer =  ' . (int) $id_customer . ' AND a.id_country = crc.id_country AND a.deleted = 0
WHERE crc.id_cart_rule = ' . (int) $cart_rule['id_cart_rule']
);

if ($meetsCountryRestriction) {
   $result[] = $result_bak[$key];
 }
```

**Comment by ShaiMagal** [comment]
@Hlavtox not sure, I made easy fix for this performance problem. I am not trying to refacto, but fix only :))
Maybe you make another PR for this later :-D

**Comment by Hlavtox** [comment]
@ShaiMagal Pushed to your branch bro, ONLY ONE QUERY NOW. ;-)

**Review by Hlavtox — DISMISSED** [review]

**Comment by ShaiMagal** [comment]
@Hlavtox ok, well

**Review by Hlavtox — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by ShaiMagal** [comment]
Can merge this?

**Comment by paulnoelcholot** [comment]
@ShaiMagal  Auto test are broken https://github.com/paulnoelcholot/testing_pr/actions/runs/9176203860/job/25230948486

Can you check that please?

**Review by boherm — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello  @ShaiMagal,

I tested your PR and it's good for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Pull request merged**
