### PR TITLE
Formatting of text incorrect if long feature description used

### LINKED ISSUE #9978: [BOOM-3055] Formatting of text incorrect if long feature description used
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3055).

- _**Reporter:**_ gray
- _**Created at:**_ Tue, 16 May 2017 19:58:17 +0200

<p>Formatting of text incorrect if long feature description used. Check attached image of 'filter by'</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by rdy4ever**
This PR fixes #9978

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes #9978
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9978
| How to test?  | See fixed ticket for the bug description.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10225)

### CODE REVIEW

**Comment by matks** [comment]
What do you think @BilalDr ? This is a possible solution to fix https://github.com/PrestaShop/PrestaShop/issues/9978

**Comment by BilalDr** [comment]
Yes it can be a great solution @matks . 
But first we need to check behaviour on small device (tablets, mobile)

**Comment by PierreRambaud** [comment]
Up, are you able to rebase @rdy4ever ?

**Comment by rdy4ever** [comment]
Sorry, I’ve deleted this repo.

**Comment by PierreRambaud** [comment]
No problem, I apply your changes directly into the facetedsearch module.
I close this pull request because of you deleted your repository.

**Pull request closed without merging**
