### PR TITLE
Removed execute bit set on PHP files

### LINKED ISSUE #27017: php files from the repository have execute bit set
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Some of php files have execute bit set 

From the repository : 
find `. -executable  -type f   -name "*.php"`

### Expected behavior

Most of this files should not be executable

### Steps to reproduce

1. clone the repository 
2. find `. -executable  -type f   -name "*.php"`

```
./controllers/admin/AdminProductsController.php
./controllers/admin/AdminTranslationsController.php
./admin-dev/themes/default/img/index.php
./admin-dev/themes/default/css/vendor/index.php
./admin-dev/themes/default/css/index.php
./admin-dev/themes/default/scss/modules/index.php
./admin-dev/themes/default/scss/partials/index.php
./admin-dev/themes/default/scss/vendor/index.php
./admin-dev/themes/default/scss/index.php
./override/modules/index.php
./img/st/index.php
./config/defines.inc.php
./config/xml/index.php
./js/tiny_mce/langs/index.php
./js/tiny_mce/plugins/paste/index.php
./js/tiny_mce/plugins/tabfocus/index.php
./js/tiny_mce/plugins/directionality/index.php
./js/tiny_mce/plugins/nonbreaking/index.php
./js/tiny_mce/plugins/align/index.php
./js/tiny_mce/plugins/insertdatetime/index.php
./js/tiny_mce/plugins/autoresize/index.php
./js/tiny_mce/plugins/legacyoutput/index.php
./js/tiny_mce/plugins/save/index.php
./js/tiny_mce/plugins/table/index.php
./js/tiny_mce/plugins/noneditable/index.php
./js/tiny_mce/plugins/advlist/index.php
./js/tiny_mce/plugins/layer/index.php
./js/tiny_mce/plugins/wordcount/index.php
./js/tiny_mce/plugins/preview/index.php
./js/tiny_mce/plugins/media/index.php
./js/tiny_mce/plugins/print/index.php
./js/tiny_mce/plugins/anchor/index.php
./js/tiny_mce/plugins/hr/index.php
./js/tiny_mce/plugins/example/index.php
./js/tiny_mce/plugins/visualblocks/css/index.php
./js/tiny_mce/plugins/visualblocks/index.php
./js/tiny_mce/plugins/visualchars/index.php
./js/tiny_mce/plugins/image/index.php
./js/tiny_mce/plugins/example_dependency/index.php
./js/tiny_mce/plugins/fullscreen/index.php
./js/tiny_mce/plugins/searchreplace/index.php
./js/tiny_mce/plugins/bbcode/index.php
./js/tiny_mce/plugins/lists/index.php
./js/tiny_mce/plugins/placeholder/index.php
./js/tiny_mce/plugins/pagebreak/index.php
./js/tiny_mce/plugins/link/index.php
./js/tiny_mce/plugins/colorpicker/index.php
./js/tiny_mce/plugins/fullpage/index.php
./js/tiny_mce/plugins/importcss/index.php
./js/tiny_mce/plugins/textcolor/index.php
./js/tiny_mce/plugins/charmap/index.php
./js/tiny_mce/plugins/contextmenu/index.php
./js/tiny_mce/plugins/index.php
./js/tiny_mce/plugins/code/index.php
./js/tiny_mce/plugins/autolink/index.php
./js/tiny_mce/plugins/autosave/index.php
./js/tiny_mce/plugins/template/index.php
./js/tiny_mce/plugins/emoticons/img/index.php
./js/tiny_mce/plugins/emoticons/index.php
./js/tiny_mce/index.php
./js/jquery/jquery.noConflict.php
./js/jquery/plugins/imgareaselect/index.php
./js/retro-compat.js.php
./install-dev/controllers/http/process.php
./classes/webservice/WebserviceException.php
./classes/webservice/SQLUtils.php
./classes/webservice/WebserviceOutputInterface.php
./classes/webservice/WebserviceOutputXML.php
./classes/webservice/WebserviceSpecificManagementSearch.php
./classes/webservice/WebserviceSpecificManagementImages.php
./classes/webservice/WebserviceSpecificManagementInterface.php
./classes/webservice/WebserviceOutputBuilder.php
./classes/webservice/WebserviceKey.php
./classes/db/Db.php
./classes/stock/SupplyOrderReceiptHistory.php
./classes/stock/SupplyOrderDetail.php
./classes/stock/SupplyOrder.php
./classes/stock/SupplyOrderHistory.php
./classes/stock/SupplyOrderState.php
./classes/Cart.php
./classes/CartRule.php
./classes/pdf/HTMLTemplateDeliverySlip.php
./classes/pdf/PDFGenerator.php
./classes/pdf/HTMLTemplateInvoice.php
./classes/pdf/HTMLTemplateOrderReturn.php
./classes/pdf/HTMLTemplate.php
./classes/pdf/PDF.php
./classes/cache/CacheXcache.php
./classes/cache/CacheApc.php
./classes/cache/Cache.php
./classes/cache/CacheMemcache.php
./classes/cache/CacheMemcached.php
./classes/helper/Helper.php
./pdf/index.php
./cache/tcpdf/index.php
./src/Adapter/Attachment/QueryHandler/GetAttachmentHandler.php
./src/Adapter/Product/AdminProductDataUpdater.php
./src/Core/Domain/Attachment/QueryHandler/GetAttachmentHandlerInterface.php
./src/Core/Domain/Attachment/QueryResult/Attachment.php
./src/PrestaShopBundle/Controller/Admin/Improve/ModuleController.php
```

### PrestaShop version(s) where the bug happened

1.7.8.2

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed execute bit set on PHP files
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27017
| How to test?      | Execute ` find . -executable -type f -name "*.php" -not -path "./vendor/*" -not -path "./modules/*"` and you should not find any files

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27811)

### CODE REVIEW

**Review by saulaski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by atomiix** [comment]
I have [`js/jquery/plugins/imgareaselect/index.php`](https://github.com/PrestaShop/PrestaShop/blob/develop/js/jquery/plugins/imgareaselect/index.php) that seems to be executable too

**Review by kpodemski — DISMISSED** [review]

**Comment by Progi1984** [comment]
@atomiix @kpodemski @matthieu-rolland Fixed the feedback from @atomiix. Thanks

**Review by PierreRambaud — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by atomiix — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hello @Progi1984, 

I tested it and the issue it's corrected as we can see : 
image

**Comment by Progi1984** [comment]
Thanks @AureRita

**Pull request merged**
