### PR TITLE
Fix customer search in new order form

### PR DESCRIPTION
**Pull request by Uebix**
In the back office new order form, javascript translations are malformed if contains quotes or double quotes.
Example: In Italian "View this order" is translated in "Vedi quest'ordine" and this character in javascript make an exception.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In the back office new order form, javascript translations are malformed if contains quotes or double quotes. Example: In Italian "View this order" is translated in "Vedi quest'ordine" and this character in javascript make an exception
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [#BOOM-3679](http://forge.prestashop.com/browse/BOOM-3679) [#BOOM-3015](http://forge.prestashop.com/browse/BOOM-3015) [#BOOM-3859](http://forge.prestashop.com/browse/BOOM-3859) [#BOOM-2882](http://forge.prestashop.com/browse/BOOM-2882) [#BOOM-2932](http://forge.prestashop.com/browse/BOOM-2932)
| How to test?  | Set Italian as BO language and try to search a customer in new order form.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8476)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hello @Uebix,

Is your issue occurring on PrestaShop 1.6 or 1.7?

**Comment by Uebix** [comment]
Hello @quetzacoalt91, this issue is on 1.7

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @Uebix.
For your information, I moved your PR on the branch 1.7.3.x to make it available from PrestaShop 1.7.3.1.

Best regards

**Comment by Uebix** [comment]
Conflicts for 1.7.3.x fixed

**Review by Quetzacoalt91 — DISMISSED** [review]
Still OK

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @Uebix

**Pull request merged**
