### PR TITLE
Create attribute

### PR DESCRIPTION
**Pull request by hadrich-hatem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows to do a script refactoring of the create, edit, delete and check an attribute. Create and check all type of attribute(radio, select, color and texture).
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run the script TEST_PATH=full/04_attribute/* npm run specific-test -- --URL=FrontOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9119)

### CODE REVIEW

**Comment by hadrich-hatem** [comment]
@mbadrani this PR is ready to be merged

**Review by mbadrani — DISMISSED** [review]
alredy approved

**Review by mbadrani — APPROVED** [review]
Ready to be merged

**Comment by PierreRambaud** [comment]
Thanks everyone

**Pull request merged**
