### PR TITLE
Update dependency classic theme

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Since versioning of classic theme has started this is a dependency update of classic theme to fit with core version
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/lartist/ga.tests.ui.pr/actions/runs/4114665816
| Fixed ticket?     | 
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi,
QA will do a small exploratory test on this one (in addition of automated tests) ;)

**Comment by lartist** [comment]
@nesrineabdmouleh I rebase this one ans still one error in auto test

**Review by matthieu-rolland — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
> @nesrineabdmouleh I rebase this one ans still one error in auto test

Hello @lartist 

Tests are OK for this PR => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/4122486224
The fail in orders is random and not related to this PR.

**Review by matks — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi ! @paulnoelcholot did an exploratory test session, it's all good for QA !

**Pull request merged**
