### PR TITLE
[-] BO: Fix saving full HTML email document

### PR DESCRIPTION
**Pull request by gskema**
`Tools::purifyHTML` destroys `html`, `head` tags, returning only the body. You can check the default email files that come with the installation and check them again after saving. Only content HTML is saved.

Also, the responsive email `style` block is destroyed too, but that is another issue.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Woud you mind making git --amend to rewrite the commit message as it will go in logs with the same commit title as your second PR ?

Thank you. Regards

**Comment by gskema** [comment]
Sorry, I messed up the commit messages yesterday :(

**Comment by sfroment42** [comment]
Hi @gskema ,

I think you should take a look at js/admin/tinymce.inc.js cause tinymce will also delete the head tag.

Best regards.

**Comment by gskema** [comment]
I'm aware of that, it works the same way as before (around 1.6.0.9, before `purifyHTML` everything worked correcly).

When you open emails translations, only the content body is left in RTE, the content is embded into HTML pattern on every save (`AdminTranslationsControllerCore::getMailPattern()`) in PHP.

**Comment by xBorderie** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

-xb.

**Comment by xBorderie** [comment]
Sorry that you had to close this PR, Gytis. PRs done on the `1.6` branch cannot be merged into `1.6.1.x`, so the best thing that can be done is to port them to a more current branch, such as `1.6.1.x` or `develop`.

**Comment by gskema** [comment]
@xBorderie I have a new patch https://gist.github.com/gskema/d3f62431965dbb5c8cdb04da97c9dc77, maybe I'll make a new PR

**Comment by xBorderie** [comment]
Nice, thanks!

**Pull request closed without merging**
