### PR TITLE
Fixes BO Dashdoard Button wrong display

### LINKED ISSUE #28974: BO - Dashboard - Bad display of the demo mode button
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Dashboard page, when we try to enable/disable the Demo mode, the icon-toggle-off/on is not well displayed

Employee language =  English
image
Employee language = Arabic
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > Dashboard page
2. Click on Demo mode to enable it or disable it
3. See error: the  icon-toggle-off/on is not well displayed when using LTR or RTL language

PS1786 => ok

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by LouisAUTHIE**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Prepend the class of the button Demo Mode while switching on/off in English and other languages
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28974 
| Related PRs       | N/A.
| How to test?      | Go to dashboard and toggle Demo button as described in the PR.
| Possible impacts? | No crucial impact.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by LouisAUTHIE** [comment]
Thx @okom3pom

**Review by NeOMakinG — DISMISSED** [review]

**Review by marwachelly — COMMENTED** [review]
Hello @LouisAUTHIE ,

I tested the PR but I noticed that when hover on the button the toggel hasn't the same color as the demo button (which is not the case on PS1.7.8.5)

https://user-images.githubusercontent.com/89604350/178968509-bd2f1f08-27ee-4e5e-b9e7-01087226576e.mp4


Could you please check?

Thanks,

**Comment by MatShir** [comment]
@LouisAUTHIE It almost fixed, could you check the feedback of the QA? We really would like to have your fix for the next release ;)

**Comment by LouisAUTHIE** [comment]
Hi, I will try to fix this tonight back from holidays

**Comment by LouisAUTHIE** [comment]
I have a problem with the rebase on the 8.0.x, I just would like to send this commit... but no success... https://github.com/PrestaShop/PrestaShop/pull/29024/commits/52f07398d8496e2818988f5c8def8796938d7b4b

--> Fixed with the sympathic help from @FabienPapet, thx mate for your help !

**Comment by LouisAUTHIE** [comment]
> Hello @LouisAUTHIE ,
> 
> I tested the PR but I noticed that when hover on the button the toggel hasn't the same color as the demo button (which is not the case on PS1.7.8.5)
> Untitled_.Jul.14.2022.11_55.AM.mp4
> 
> Could you please check?
> 
> Thanks,

Should be ok now

**Review by NeOMakinG — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello @LouisAUTHIE,

PR is tested again and the Issue is well fixed => PR is QA approved.

https://user-images.githubusercontent.com/89604350/182346483-bd67e018-73f7-4359-99c2-a79c1a4f470a.mp4

Thanks ,

**Review by marwachelly — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thanks @LouisAUTHIE and @marwachelly 👍

**Pull request merged**
