### PR TITLE
[*] BO : Change the Carrier on existing order

### PR DESCRIPTION
**Pull request by kelu95**
See : #PSCSX-1972 and #PSCSX-1041

### CODE REVIEW

**Comment by xBorderie** [comment]
Rework of #3360. Thanks @kelu95 !

**Comment by kpodemski** [comment]
Nice, finally this feature! :+1:

**Comment by firstred** [comment]
:+1:

**Comment by xBorderie** [comment]
Well @kelu95, looks you have fans waiting for a rebasing of this PR! :)

**Comment by kpodemski** [comment]
@xBorderie is it going to be merged into 1.7? @kelu95 are you going to rebase your PR or i should cherry pick it? This is really needed feature, many people have requested this.

**Comment by mickaelandrieu** [comment]
@kpodemski  kelu95 is no longer part of core team, if you can handle this, go for it :+1:

**Comment by kpodemski** [comment]
@mickaelandrieu ok thanks, i will :)

**Comment by xBorderie** [comment]
:+1:

**Comment by xBorderie** [comment]
Closing this PR since @kpodemski 's #5955 handled this all the way through :)
Thanks!

**Pull request closed without merging**
