### PR TITLE
Update jquery-ui to 1.13.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We didn't update jquery UI for years
| Type?             | improvement
| Category?         | FO / BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | I don't really know how to test this as most of the core doesn't use it anymore but it's kept as a dependency for every modules, on FO you should verify that classic/hummingbird is working fine, specially on facetedsearch pages as it's the only known native module using it
| Possible impacts? | Every parts using jquery-ui

# BC Break
https://jqueryui.com/upgrade-guide/1.13/
https://jqueryui.com/upgrade-guide/1.12/
https://jqueryui.com/upgrade-guide/1.11/

and other migrations guides are containing every changes

### CODE REVIEW

**Comment by ghost** [comment]
Add to test : ps_searchbar

**Comment by NeOMakinG** [comment]
> Add to test : ps_searchbar

And I tested it, it breaks 😢 

Because we need to update every parts which is kinda impossible as `jQuery UI` doesn't support this, it was a part of the development bundle in the past, which should have never been added to the project at all I guess

**Review by matks — COMMENTED** [review]
@NeOMakinG PR content seems valid but... can we do this now in `develop` branch? Like this? I dont know if we can embed this impact inside PrestaShop 8.1.0 :/

**Comment by NeOMakinG** [comment]
> @NeOMakinG PR content seems valid but... can we do this now in `develop` branch? Like this? I dont know if we can embed this impact inside PrestaShop 8.1.0 :/

If we target 9.x, then I'll remove every jQuery plugins and use the full bundle everywhere as it's not supported anymore

**Comment by FabienPapet** [comment]
@NeOMakinG is this PR still valid ?

**Comment by NeOMakinG** [comment]
> @NeOMakinG is this PR still valid ?

I would say yes, but I won't have the time to push it further as I won't be full time anymore if someone want to take over it later, feel free

**Pull request closed without merging**
