### PR TITLE
Adding Danish translation to installer

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions | Answers |
| --- | --- |
| Branch? | develop. |
| Description? | Adding Danish translation for installer + providing a basis for translation of menu and fixtures. |
| Type? | new feature |
| Category? | IN |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | na |
| How to test? | Choose Danish as install language + Denmark as shop country. You should have most of the content in your shop in Danish. Tadaaaa! |

There are still some XML files who need translations. I tried to extract as much as possible from Crowdin, but not everything is available. Counting on the community to help with the missing translations! :)

And it can be cherry-picked to 1.6, except for the tab.xml part I think. To be checked!

Thanks!

### CODE REVIEW

**Comment by vTerenti** [comment]
OK for me, seems to work fine!

**Comment by maximebiloe** [comment]
I don't speak Danish but everything looks good to me 😉

**Comment by Casper-O** [comment]
Don't know its fine, since it have non-latin characters in the URL? Like Æ Ø Å

Also, there seems to be a few typo around in it

**Comment by AlexEven** [comment]
Thank you @Casper-O.
I'll check the non-latin characters, I hadn't paid attention to it :(

**Comment by Casper-O** [comment]
I dont know If its an issue - i know its Possible to show them but its need to be activated in BO

**Pull request merged**
