### PR TITLE
Fixed wishlist button disappear when products are filtered

### LINKED ISSUE #26327: Wishlist button disappears while using Faceted Search
#### Describe the bug

Wishlist button disappears on category page while using any filter in faceted search.

#### Expected behavior

Wishlist button should not disappear.

#### Steps to Reproduce

1. Go to category page having faceted search module.
2. Click on any filter in faceted search module.
3. See that Wishlist button has disappeared.

**Screenshots**

Untitled-3

#### Additional information

* PrestaShop version: 1.7.8.0
* Wishlist module: v2.0.1
* Faceted Search module: v3.7.1

### PR DESCRIPTION
**Pull request by alexandrebru83**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix wishlist button disappears while using Faceted Search.<br/><br/> Instead of changing selector of MutationObserver blockwishlist `document.querySelectorAll('#products, .featured-products')` that detect changes on these direct childs.<br/><br/>I prefer to remove this useless div and be consistent to the product list page when products are not displayed. In this case, the element `#products` has childs `#js-product-list-top, #js-product-list, #js-product-list-bottom` directly in it, without `<div>`.<br/><br/>Open to discuss about these divs.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26327.
| How to test?      | See how to test section of issue
| Possible impacts? | 

# Breaking changes
We mark this PR as a BC because we removed some divs that might be used by any modules/theme developers but which looks useless

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26486)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
Nice catch 👍 

I think we should mark this as a BC, it may influence some modules works don't you think?

**Comment by alexandrebru83** [comment]
> Nice catch 👍
> 
> I think we should mark this as a BC, it may influence some modules works don't you think?

Yes we can :)

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @alexandrebrubeyonds,

The issue is a regression in PS1.7.8.0.
This PR should be created in branch 1.7.8.x and not develop.
Can you please change the base of your PR to 1.7.8.x?

Thanks!

**Comment by NeOMakinG** [comment]
> Hi @alexandrebrubeyonds,
> 
> The issue is a regression in PS1.7.8.0. This PR should be created in branch 1.7.8.x and not develop. Can you please change the base of your PR to 1.7.8.x?
> 
> Thanks!

Oh damn :( Nice catch

**Comment by alexandrebru83** [comment]
> Hi @alexandrebrubeyonds,
> 
> The issue is a regression in PS1.7.8.0. This PR should be created in branch 1.7.8.x and not develop. Can you please change the base of your PR to 1.7.8.x?
> 
> Thanks!

IDK how to do it, so I created new PR : #26526

**Comment by khouloudbelguith** [comment]
Hi @alexandrebrubeyonds,

Thanks, I will close this PR.

**Pull request closed without merging**
