### PR TITLE
[-]BO : Fix Module configure permission

### PR DESCRIPTION
**Pull request by dheerajwebkul**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | There is a separate "Configure" permission for every module in the back office, but configure permission need to module edit permission, after giving module edit permission user can disable and uninstall the module also, that should not happen. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-5940 |
| How to test? | Just try to give a module to only Configure permission not to disable and uninstall the module permission. You can see the issue. |

### CODE REVIEW

**Comment by Shudrum** [comment]
HI @dheerajwebkul, thank you for your PR.

I will not merge it right now as we are reworking the permission system and I wan't to avoid any conflict.

If this is safe for conflict, I'll merge it.

Thank you!

**Comment by dheerajwebkul** [comment]
Sure @Shudrum , Thanks for your reply

**Comment by dheerajwebkul** [comment]
Hello @Shudrum ,

I just fixed my commit. Last commit have some issue while module installation. But the travis-ci checks have been failed. Is there any issue?

Thanks,

**Comment by Shudrum** [comment]
Hi @dheerajwebkul,

The tests have failed because we have accidentally merged a bad pull request. The fix is now live but your tests stay red because you should have to rebase your PR.

But do not panic, the tests for your PR are now OK, I have launch them locally and all is good :)

👍

**Comment by dheerajwebkul** [comment]
Thanks @Shudrum ,

**Comment by vincentbz** [comment]
Hi,

I agree with you. "Edit" permission should not prevent using the "configure" permission.

**Comment by maximebiloe** [comment]
Hello,

Now that we've reworked the right managements, can you rebase your PR, please? It currently have conflicts.

Thank you in advance!

**Comment by Shudrum** [comment]
Hello @wkdks!

We would like to merge your pull request but we need you! Can you please rebase your pull request to allow us to merge? Do not hesitate to squash your commits in the same time.

Thank you!

**Comment by dSkrbic** [comment]
Hello,

Tested on 1.7.0.x -> **OK**
z1-scr_2016 11 23_15h38m29s_017_

**Comment by aleeks** [comment]
Is AdminModulesController.php already used ?

**Comment by dSkrbic** [comment]
EDIT

Seems this PR generate a collateral bug: impossible to edit modules:
z2-scr_2016 11 23_17h04m14s_018_

So removing the QA approval

**Comment by mickaelandrieu** [comment]
@wkdks would you mind to take a look ?

**Comment by wkdks** [comment]
@dSkrbic , I was not able to get this type of issues, Also I am not pretty familiar with GIT rebase,
I was tried but not able to rebase this commit. Please let me know how can I rebase this commit.

**Comment by aleeks** [comment]
Hello, i'm closing your PR, i just do this one https://github.com/PrestaShop/PrestaShop/pull/7455 amanding your commit :)
Thank you.

**Pull request closed without merging**
