### PR TITLE
Remove deprecated include "images.inc.php"

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed include file deprecated way back in 1.5 and used nowhere
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes - the file `images.inc.php` has been removed
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | Nothing to test
| Possible impacts? | No impact that I can see

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27914)

### CODE REVIEW

**Review by Progi1984 — COMMENTED** [review]
Please document the BC Break

**Comment by eternoendless** [comment]
Screenshot 2022-03-15 at 13 59 11

Good enough @Progi1984 ?

**Review by PierreRambaud — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Comment by Progi1984** [comment]
> Screenshot 2022-03-15 at 13 59 11
> 
> Good enough @Progi1984 ?

@eternoendless No, the BC Break must be defined outside the table like in #27802 else prestonbot can't analyse the table and add the "BC Break" label.

**Comment by eternoendless** [comment]
@Progi1984 that's a bug in prestonbot that I just fixed: https://github.com/PrestaShop/prestonbot/pull/127

**Comment by eternoendless** [comment]
Rebased

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
I add label "Needs documentation". BC break needs to be documented https://devdocs.prestashop.com/8/modules/core-updates/8.0/

**Pull request merged**
