### PR TITLE
Buttons in product page

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows to check all buttons in create product page
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run the script path=full/02_product/10_check_product_page_buttons.js npm run specific-test -- --URL=BackOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9127)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @fouratachour
After clicking on the delete button in the bottom of the product page and on "Yes" in the modal, we need to check on the catalog page if the product isn't here anymore (in addition to the presence of the message "Product successfully deleted.")
We need also to click on "No" in the modal after clicking on the delete button & check if we are still on the product page with the name of the product

I have updated the scenario "Buttons in footer product page" on test link

**Comment by fouratachour** [comment]
Hello @marionf
Done, Script updated !

**Comment by marionf** [comment]
Thank you @fouratachour :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks everyone!

**Pull request merged**
