### PR TITLE
Send customer thread reply message link in correct user language

### PR DESCRIPTION
**Pull request by 23b**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Reply emails to customer threads contain a answer link. This link has to be language specific to user.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Worst scenario: Shop setup with 2 languages, one being active. Backoffice employee uses the deactivated language. Employee replies to customer thread. Reply {link} send to the user in the "reply_msg" email will lead to 404.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20171)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @23b,

This PR cannot be tested because it is blocked by this issue: https://github.com/PrestaShop/PrestaShop/issues/20041
While testing this PR, I have the same exception reported when I click on the `Reply {link}`
image

Thanks!

**Comment by estebangarviso** [comment]
Hi @khouloudbelguith please change these two files and the exception disappears.
Rute file#1: /modules/contactform/views/templates/widget/contactform.tpl

`{block name="page_title"}
  {l s='Customer service - Contact us' d='Modules.Contactform.Shop'}
{/block}

<section class="login-form">
  <form action="{$urls.pages.contact}" method="post" {if $contact.allow_file_upload}enctype="multipart/form-data"{/if}>

    <header>
      <h1 class="h3">{l s='Send a message' d='Modules.Contactform.Shop'}</h1>
      <p>{l s='If you would like to add a comment about your order, please write it in the field below.' d='Modules.Contactform.Shop'}</p>
    </header>

    {if $notifications}
      <div class="notification {if $notifications.nw_error}notification-error{else}notification-success{/if}">
        <ul>
          {foreach $notifications.messages as $notif}
            <li>{$notif}</li>
          {/foreach}
        </ul>
      </div>
    {/if}

    {if !$notifications || $notifications.nw_error}
      <section class="form-fields">

        <label>
          <span>{l s='Subject Heading' d='Modules.Contactform.Shop'}</span>
          <select name="id_contact">
            {foreach from=$contact.contacts item=contact_elt}
              <option value="{$contact_elt.id_contact}">{$contact_elt.name}</option>
            {/foreach}
          </select>
        </label>

        <label>
          <span>{l s='Email address' d='Modules.Contactform.Shop'}</span>
          <input type="email" name="from" value="{$contact.email}" />
        </label>

        {if $contact.orders && isset($contact.orders[0]['id_order'])}
          <label>
            <span>{l s='Order reference' d='Modules.Contactform.Shop'}</span>
            <select name="id_order">
              <option value="">{l s='Select reference' d='Modules.Contactform.Shop'}</option>
              {foreach from=$contact.orders item=order}
                <option value="{$order.id_order}">{$order.reference}</option>
              {/foreach}
            </select>
          </label>
        {/if}

        {if $contact.allow_file_upload}
          <label>
            <span>{l s='Attach File' d='Modules.Contactform.Shop'}</span>
            <input type="file" name="fileUpload" />
          </label>
        {/if}

        <label>
          <span>{l s='Message' d='Modules.Contactform.Shop'}</span>
          <textarea cols="67" rows="3" name="message">{if $contact.message}{$contact.message}{/if}</textarea>
        </label>
        
        {hook h='displayGDPRConsent' id_module=$id_module}

      </section>

      <footer class="form-footer">
        <style>
          input[name=url] {
            display: none !important;
          }
        </style>
        <input type="text" name="url" value=""/>
        <input type="hidden" name="token" value="{$token}" />
        <button type="submit" name="submitMessage">
          {l s='Send' d='Modules.Contactform.Shop'}
        </button>
      </footer>
    {/if}
  </form>
</section>
`
Rute file#2: themes/classic/modules/contactform/views/templates/widget/contactform.tpl

`<section class="contact-form">
  <form action="{$urls.pages.contact}" method="post" {if $contact.allow_file_upload}enctype="multipart/form-data"{/if}>

    {if $notifications}
      <div class="col-xs-12 alert {if $notifications.nw_error}alert-danger{else}alert-success{/if}">
        <ul>
          {foreach $notifications.messages as $notif}
            <li>{$notif}</li>
          {/foreach}
        </ul>
      </div>
    {/if}

    {if !$notifications || $notifications.nw_error}
      <section class="form-fields">

        <div class="form-group row">
          <div class="col-md-9 col-md-offset-3">
            <h3>{l s='Contact us' d='Shop.Theme.Global'}</h3>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-md-3 form-control-label">{l s='Subject' d='Shop.Forms.Labels'}</label>
          <div class="col-md-6">
            <select name="id_contact" class="form-control form-control-select">
              {foreach from=$contact.contacts item=contact_elt}
                <option value="{$contact_elt.id_contact}">{$contact_elt.name}</option>
              {/foreach}
            </select>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-md-3 form-control-label">{l s='Email address' d='Shop.Forms.Labels'}</label>
          <div class="col-md-6">
            <input
              class="form-control"
              name="from"
              type="email"
              value="{$contact.email}"
              placeholder="{l s='your@email.com' d='Shop.Forms.Help'}"
            >
          </div>
        </div>

        {if $contact.orders && isset($contact.orders[0]['id_order'])}
          <div class="form-group row">
            <label class="col-md-3 form-control-label">{l s='Order reference' d='Shop.Forms.Labels'}</label>
            <div class="col-md-6">
              <select name="id_order" class="form-control form-control-select">
                <option value="">{l s='Select reference' d='Shop.Forms.Help'}</option>
                {foreach from=$contact.orders item=order}
                  <option value="{$order.id_order}">{$order.reference}</option>
                {/foreach}
              </select>
            </div>
            <span class="col-md-3 form-control-comment">
              {l s='optional' d='Shop.Forms.Help'}
            </span>
          </div>
        {/if}

        {if $contact.allow_file_upload}
          <div class="form-group row">
            <label class="col-md-3 form-control-label">{l s='Attachment' d='Shop.Forms.Labels'}</label>
            <div class="col-md-6">
              <input type="file" name="fileUpload" class="filestyle" data-buttonText="{l s='Choose file' d='Shop.Theme.Actions'}">
            </div>
            <span class="col-md-3 form-control-comment">
              {l s='optional' d='Shop.Forms.Help'}
            </span>
          </div>
        {/if}

        <div class="form-group row">
          <label class="col-md-3 form-control-label">{l s='Message' d='Shop.Forms.Labels'}</label>
          <div class="col-md-9">
            <textarea
              class="form-control"
              name="message"
              placeholder="{l s='How can we help?' d='Shop.Forms.Help'}"
              rows="3"
            >{if $contact.message}{$contact.message}{/if}</textarea>
          </div>
        </div>

        {if isset($id_module)}
          <div class="form-group row">
            <div class="offset-md-3">
              {hook h='displayGDPRConsent' id_module=$id_module}
            </div>
          </div>
        {/if}

      </section>

      <footer class="form-footer text-sm-right">
        <style>
          input[name=url] {
            display: none !important;
          }
        </style>
        <input type="text" name="url" value=""/>
        <input type="hidden" name="token" value="{$token}" />
        <input class="btn btn-primary" type="submit" name="submitMessage" value="{l s='Send' d='Shop.Theme.Actions'}">
      </footer>
    {/if}

  </form>
</section>
`

**Comment by khouloudbelguith** [comment]
Hi @estebangarviso,

Thanks for your feedback.
If you have already fixed it on your end or if you think you can do it, please do send us a pull request!
https://github.com/PrestaShop/contactform
Thanks!

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hello @23b , thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by 23b** [comment]
Well i tried

**Comment by PierreRambaud** [comment]
> Well i tried

Could you also run PHP cs fixer in order to fix the ci :)

**Comment by Progi1984** [comment]
@23b Please rebase your branch : we can't accept Merge commits in PR.

Look at [Contributions Guidelines](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#commits).

**Comment by matks** [comment]
Hi @23b,

It looks like this PR is not moving anymore. As mentioned in our [Maintainer Guide](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests), "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

I close this pull request as it seems stale. If however you want to continue, we can re-open it 😉 . Just tell us! 😄 

Thank you!

**Pull request closed without merging**
