### PR TITLE
Fix for rendering of disabled modules

### PR DESCRIPTION
**Pull request by iqit-commerce**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | widget included in tpl should check for their status
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | /no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2796
| How to test?  | Described in ticket http://forge.prestashop.com/browse/BOOM-2796

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @iqit-commerce, 

Can we keep the message if we are on `dev mode` ? WDYT @iqit-commerce @maximebiloe 

Regards

**Comment by iqit-commerce** [comment]
In my opinion making page blank even in dev mode becosue of this is not good idea. I saw many of my custoemer with enabled dev mode and they did not know much about it. 

Maybe instead throwing exception for entire page, there should be just message showed in place where widget was inserted in tpl. Somthing like " Could not initialize widget", and it should happen only in dev mode(my opinion)

**Comment by maximebiloe** [comment]
Hello @iqit-commerce,

Yes, I agree with @aleeks. It would be better, to throw the exception in dev mode and log it in prod mode like we did in this PR: https://github.com/PrestaShop/PrestaShop/pull/7734
In dev mode, you shouldn't have a blank page but the error displayed.

Also, this PR raise another issue. We forgot to enable the `ps_contactform` module in `Classic`. Could you do it in the `theme.yml` file, please?

Regards

**Comment by xBorderie** [comment]
Without giving any opinion on the whole dev-mode thing, I think we should take into account that strings cannot change between patch versions (1.7.1.x), only between minor versions (1.7.1.0, 1.7.2.0). 
Unsure if _removing_ a string fits that bill, though. Idea, @AlexEven ?

**Comment by iqit-commerce** [comment]
Hello,

I just made few more test and my commit solve issue only with including widget with {widget} but to not solve problem with {widget_block}

**Comment by iqit-commerce** [comment]
@maximebiloe it should throw exception in dev mode like 
`  throw new Exception(sprintf(
            'Module `%1$s` is not a WidgetInterface.',
            $moduleName
        ));`

or same way as in PR #7734 
`$this->warning[] = $e->getMessage();
                $scope->assign(array('notifications' => $this->prepareNotifications()));
                $tpl = $this->context->smarty->createTemplate(
                    $this->getTemplateFile('_partials/notifications'),
                    $scope
                );
                $templateContent = $tpl->fetch();`

so it create notification in tpl ?

**Comment by Shudrum** [comment]
Hello @iqit-commerce,

As this is a warning, like the PR #7734 please.

Thank you!

**Comment by maximebiloe** [comment]
Hello @iqit-commerce,

As you didn't take into account our suggestions, I close this PR.

Regards

**Comment by iqit-commerce** [comment]
Hello,

I was pretty busy recently, I will send updated PR soon.

**Comment by maximebiloe** [comment]
Nice! Thank you!

**Pull request closed without merging**
