### PR TITLE
Clean up service yml files

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR aims to add some structure to service yml files. See image below.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Backoffice should not break and work exactly the same.

Updated structure:
services

All uncategorized services (that dont have clear meaning) live under adapters/services.yml and bundle/services.yml.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9096)

### CODE REVIEW

**Comment by sarjon** [comment]
ping @mickaelandrieu what do you think? if you approve this update, ill also split remaining services.yml file into appropriate locations.

**Comment by PierreRambaud** [comment]
I like it! @mickaelandrieu wdyt? :smile:

**Comment by mickaelandrieu** [comment]
@sarjon Agree, this is the right thing to do!

You can split the remaining services :+1:

**Comment by sarjon** [comment]
@mickaelandrieu done

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@mickaelandrieu Look like everything ok :+1:

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @sarjon !

**Pull request merged**
