### PR TITLE
Update state.xml

### PR DESCRIPTION
**Pull request by rickygzz**
Changed:
- name tag Distrito Federal to Ciudad de México
- and its state tag properties id= and iso_code= to "CMX" according to its iso3166-2 code.

On 29 January 2016, Mexico City ceased to be the Federal District (Spanish: Distrito Federal or D.F.), and was officially renamed "Ciudad de México" (or "CDMX") 

Source:
https://www.iso.org/obp/ui/#iso:code:3166:MX
https://en.wikipedia.org/wiki/Mexico_City#20th_century_to_present

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Changed: name tag Distrito Federal to Ciudad de México and its state tag properties id= and iso_code= to "CMX" according to its iso3166-2 code.
| Type?             | improvement
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | It just updates a city name in Mexico.
| Possible impacts? | Since everything is linked to the state_id and not to the state_name, I dont think it will impact anything.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23813)

### CODE REVIEW

**Comment by Progi1984** [comment]
@rickygzz  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you target the `develop` branch and not the `1.7.7.x` branch ?

Thanks :+1:

**Comment by rickygzz** [comment]
> @rickygzz Thank you for your contribution. 🤗
> 
> Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
> Could you target the `develop` branch and not the `1.7.7.x` branch ?
> 
> Thanks 👍

I changed the target to `develop`.

There is a file named `install-dev/data/xml/state.xml` which is used when you first install the prestashop on the server. It is used to create the the database table`ps_states` with the states values for all the countries (when available).

I am just suggesting an update to this file, since it has been several years since Distrito Federal changed its name to Ciudad de México.

Changed:

```javascript
-    <state id="DIF" id_country="MX" id_zone="North_America" iso_code="DIF" tax_behavior="0" active="1">
-      <name>Distrito Federal</name> 
+    <state id="CMX" id_country="MX" id_zone="North_America" iso_code="CMX" tax_behavior="0" active="1">
+      <name>Ciudad de México</name>
```

name tag Distrito Federal to Ciudad de México
and its state tag properties id= and iso_code= to "CMX" according to its iso3166-2 code.


On 29 January 2016, Mexico City ceased to be the Federal District (Spanish: Distrito Federal or D.F.), and was officially renamed "Ciudad de México" (or "CDMX")

Source:
https://www.iso.org/obp/ui/#iso:code:3166:MX
https://en.wikipedia.org/wiki/Mexico_City#20th_century_to_present


I don´t see how a link may help you visualize this fix. Please let me know if it is still not clear, so I can find another way to explain this fix,

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Coiuld you please rebase your branch, it currently includes a lot of commits that you don't create :sweat_smile:

**Comment by rickygzz** [comment]
I was struggling to rebase this patch-3. So I am going to close this pull request.

I created a new pull request: Update state.xml - Distrito Federal changed to Ciudad de México #23828 

Thanks!

**Comment by rickygzz** [comment]
Closed.

**Pull request closed without merging**
