### PR TITLE
Speed up search queries (17)

### PR DESCRIPTION
**Pull request by jocel1**
(cherry picked from commit 8537e7f)

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | speed up search queries
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Search with a lot of products

### CODE REVIEW

**Comment by aleeks** [comment]
hello @jocel1 
Maybe, here, you need to put 1.7.2.2.sql. if someone upgrade 1.7.2.0 to 1.7.2.2, this patch will be not applied!

**Comment by jocel1** [comment]
oh you're right, thx!

**Comment by aleeks** [comment]
Hello @jocel1 
It's not really a bug fix so i move this PR on `develop`branch, you need to rebase from develop!
Thank you!

**Comment by jocel1** [comment]
For this one I think the change is safe enough to land in the 1.7.2.x branch? (I mean no regression is possible by just adding one index in the DB :))

**Comment by aleeks** [comment]
I know it's safe :/

ping @eternoendless @maximebiloe

**Comment by maximebiloe** [comment]
Seems good to me for `1.7.2.x`

**Review by maximebiloe — APPROVED** [review]

**Comment by aleeks** [comment]
Ok, so go.
sql done in my shop, no error :)
Thank you @jocel1

**Pull request merged**
