### PR TITLE
Fix display for invalid characters in tax name

### LINKED ISSUE #26515: BO - The tax Name field accept some invalid characters
#### Describe the bug

When adding a new Tax in the Name field, it is possible to accept `;` and `#` whereas these characters are mentioned as invalid characters according to the message displayed at the bottom of the field

#### Expected behavior

The field should accept every character.

#### Steps to Reproduce

1. BO>IMPROVE>International>Taxes
2. Click On Add new tax button
3. Enter Name of Tax with `; `and `#` 
4. Enter a Rate
4. Click On Save
5. See error > the tax is saved

**Screenshots**

Tax

#### Additional information

* PrestaShop version: 1.7.8.0 & develop
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | See below
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26515
| How to test?      | Check if the invalid characters are good
| Possible impacts? | No

**Description** 

Currently the tax name validation uses `generic_name`
See this [line](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxType.php#L80).

The sprintf uses another rule see [this line](https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Form/Admin/Improve/International/Tax/TaxType.php#L53) and [these lines](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/ConstraintValidator/TypedRegexValidator.php#L49-L52) to see the all restrictions 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26546)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]
Thank you for your PR! IMO all is good

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello,
The issue is not fixed.

See screen record : 
https://www.awesomescreenshot.com/video/5993998?key=d3eb130321ac7c462d474321c5a6842a

Could you check it please ! 

Thanks,

**Comment by ghost** [comment]
Hello @HanaRebaiQA 

We should be able to add # and ; in the name of the taxes.
My PR corrects the display of allowed characters.
I can edit to disallow # and ; but I don't understand why these characters are not allowed.

**Comment by HanaRebaiQA** [comment]
Hello @PrestaShop/product-team 
I created the issue #26515 in order to fix the mismatch between the tax Name field and the message displayed bellow. But the PR fixes the message displayed bellow and not the tax Name field . 
So with this PR the special characters `;` and `#` will be allowed. What do you think?
image



Thanks in advance,

**Comment by ghost** [comment]
Hello @HanaRebaiQA can you change the label to `Waiting for PM` 

Regards

**Comment by MatShir** [comment]
@PierreRambaud another one 🤔, IMO this field needs should accept every character. 
LGTM but I have to put waiting for wording because the behavior is changing ;)
cc @Julievrz could you have a look specifically for the help text ;)

**Comment by Julievrz** [comment]
> @PierreRambaud another one 🤔, IMO this field needs should accept every character. LGTM but I have to put waiting for wording because the behavior is changing ;) cc @Julievrz could you have a look specifically for the help text ;)

Yes, Hana had already told me about this issue. I don't see any reason why we shouldn't accept these characters. 👍

**Comment by ghost** [comment]
@Progi1984 or @PierreRambaud If you can add the label Waiting for QA

Sincerely

**Comment by HanaRebaiQA** [comment]
Hello @okom3pom 

Thanks for your PR. 
I have tested this PR and the issue is fixed. The actual behavior now is to allow all caracters expect these ones `<>={}` as mentioned in the displayed message. So, now the message and the restcition are both compatible. See screen-record below: 
https://watch.screencastify.com/v/bcCUniaSgIquxqtHdKh9

So, QA :heavy_check_mark: 

I verified the result also with mulilang, multistore
image

Thanks,

**Comment by matks** [comment]
Thank you @okom3pom

**Pull request merged**
