### PR TITLE
Make checkbox label clickable

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | description
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | i guess
| How to test?  | click on the label of any checkbox added in CustomerFormatter, before and after this PR

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9130)

### CODE REVIEW

**Comment by kpodemski** [comment]
btw. i really don't know which branch we need to use these days, i don't know if something what we send to `develop` will be used on 1.7.4 or we need to do PR on 1.7.4... confusing

**Comment by kpodemski** [comment]
oh, i just noticed that my PR is almost identical as #9110

**Comment by PierreRambaud** [comment]
Yes i'm agree, it's confusing, we will work on a proper documentation about how to contribute, just after the 1.7.4 release :)
I close your PR because of duplicate #9110 
Thanks for your contribution @kpodemski

**Comment by eternoendless** [comment]
Hi @kpodemski 

Here's a simple rule of thumb:
- If it's a **feature** or **improvement**, it should be done on the `develop` branch
- If it's a **bug fix** and it **_doesn't break retrocompatibility_**, then on the latest maintenance branch (currently `1.7.4.x`)

**Pull request closed without merging**
