### PR TITLE
Fix fields width when view is disabled on product page

### LINKED ISSUE #18173: Tabs of product page have different widths in back end with view only permission.
#### Describe the bug

When changing the permission of a profile for products to View only (Add, Edit and Delete are all unchecked) the tabs of the product page have different widths and are shown differently compared to an employee that does have a profile that allows for editing of a product.

#### Expected behavior

The layout/styling should be the same; just with buttons disabled.

#### Steps to Reproduce

1. Via Create an employee with profile salesman.
2. Alter the permissions for salesman for Products so that only the View is checked.
3. Logout / Login as newly created employee.
4. Select a product from the Products list

First tab:
Prestashop View Only 1

Options tab:
Prestashop View Only 2

#### Cause

This is probably caused because `product.html.twig` surrounds the form with a `<fieldset disabled id="field-disabled">` when the product is not editable.

#### Additional information

* PrestaShop version: 1.7.4
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Product fields tabs had different sizes depending of your rights on the backoffice
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #18173.
| How to test?      | See issue, basically : create an employee with view only rights on product page, and see on different tabs if size is fine
| Possible impacts? | Product page with limited rights

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23092)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I have a display issue in two cases.

1. Create a new profile only with `View product` permission
image
2. Create a new employee with Profile1
3. Sign in with this employee
4. Edit a product
5. See the error
image


1. Create a new profile only with `View product` & `add product` permissions
image
2. Create a new employee with Profile2
3. Sign in with this employee
4. Edit a product or Add a new product
5. See the error 
image

They should be displayed
image

- I used all other cases (superAdmin profile, Product with all permissions) => ok
- I tried in different size (full size, resized window, mobile) => ok
- I added a new tab in the product detail page => ok

Thank you!

**Comment by NeOMakinG** [comment]
@khouloudbelguith It's ok now, I centered the content as it's done with full rights

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

After the last fix, a new issue is displayed:

1. Fresh install
2. Sign in
3. Go to BO > Catalog > Products
4. Add new Product > add an image
5. See the error 

image

I disabled the cache, I cleared it, I used an incognito browser.

Thank you!

**Comment by NeOMakinG** [comment]
@khouloudbelguith 

image

I'm unable to reproduce the behavior :(

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,



> @khouloudbelguith
> 
> image
> 
> I'm unable to reproduce the behavior :(

Sorry, yes, the issue is not reproduced after a new fresh install.
https://drive.google.com/file/d/1YK5Z5t7cy1pEaBT8VQacE7u1ZVEmOmjR/view?usp=sharing

Thankyou!

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Pull request merged**
