### PR TITLE
[-] BO : Incorrect shipping taxes in order slips (PSCSX-4881)

### PR DESCRIPTION
**Pull request by erouvier29**
Reported for 1.6.0, still present in 1.6.1

### CODE REVIEW

**Comment by xBorderie** [comment]
Apparently it didn't pass the test done by a user: http://build.prestashop.com/news/prestashop-1-6-1-2-rc1/#comment-2379434269
"Order slip Tax detail computation still not working. I tried [this PR] and orders in BO crashed. Thanks!"

**Comment by eric-rouvier** [comment]
Sorry for the bad reporting...
Is it better now?

**Comment by xBorderie** [comment]
Thanks @eric-rouvier ! I'll let our developers check this out in due time.

**Comment by Shudrum** [comment]
Hi @eric-rouvier, thank you for your PR, we are trying to merge it as soon as we can.

The next time, please see [How to write a commit message](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message).

Thank you again!

**Comment by firstred** [comment]
:+1:
Works great here. Thanks!
PrestaShop really needs this fix merged ASAP!

You might want to squash your commits, to make merging easier for the dev team.

**Comment by erouvier29** [comment]
Thanks @firstred for the advice.
Commits squashed, we will see...

**Comment by vTerenti** [comment]
QA OK

**Comment by Shudrum** [comment]
:+1:

**Comment by xBorderie** [comment]
Yeah!

**Comment by firstred** [comment]
Good!

**Pull request merged**
