### PR TITLE
Better inform about faulty hooks

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | If not in chaining mode, module must not return an array, otherwise you will get an error `PHP Warning:  Array to string conversion in /var/www/vhosts/eshop-blanco.cz/httpdocs/classes/Hook.php on line 988` which is very hard to trace. This will prevent the error by disregarding the response and in developer mode, throwing a notice.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests green + you can test by steps below.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/8632360018 ✅ 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### How to test
Create two modules with this code and visit sitemap page in FO in debug mode, you will get errors in logs.

```
public function hookActionModifyFrontendSitemap($params)
    {
        return $params;
    }
```

### CODE REVIEW

**Review by M0rgan01 — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by florine2623** [comment]
@Hlavtox would you mind sharing the module for the tests ? :)

**Comment by Hlavtox** [comment]
@florine2623 Hi, of course, here :-) Actually, it can be reproduced just by one faulty module.

1. Install the test module - [tox_chaintestone.zip](https://github.com/PrestaShop/PrestaShop/files/14932828/tox_chaintestone.zip).
2. Go to sitemap page in front office.

### Without my PR:
- In debug mode, you will see `Warning: Array to string conversion in C:\xampp\htdocs\81x\classes\Hook.php on line 988`.
- In production mode, you won't see anything.

### With my PR:
- In debug mode, you will see `Notice: Module tox_chaintestone returned an array on hook actionModifyFrontendSitemap. This is not allowed, the response must be joinable to a string. in C:\xampp\htdocs\81x\classes\Hook.php on line 1001` - much better error. :-)
- In production mode, you won't see anything.

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Works as explained in your PR ^^

**Without PR :**
Screenshot 2024-04-10 at 16 25 26


**With your PR : ✅** 
Screenshot 2024-04-10 at 16 24 23

When I disable debug mode, nothing is displayed.

LGTM ✅ 
Thanks!

**Comment by Hlavtox** [comment]
@florine2623 Cool, thank you! :-)

**Pull request merged**
