### PR TITLE
Fix display edit country

### LINKED ISSUE #26342: BO - Address format in Countries page is badly displayed
#### Describe the bug

Address format is off centered

#### Expected behavior

Address format should be centered like the other elements.
Tabs and buttons should be on one line.

#### Steps to Reproduce

1. Go to BO > International > Locations > Edit Country of your choice
2. Scroll down to Address format

**Screenshots**

PS 1.7.8.X and develop :
Screenshot 2021-10-20 at 18 08 47

PS 1.7.7.7 :
Screenshot 2021-10-20 at 18 08 07

#### Additional information

* PrestaShop version: 1.7.8.x, develop
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Address format should be centered like the other elements. Tabs and buttons should be on one line.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yno
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26342
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/26342
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26353)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]
Thank you for your PR! IMO is good

**Comment by florine2623** [comment]
Hello @okom3pom ,

I hope you are doing OK !

On bigger screen, PR is good :
Screenshot 2021-10-22 at 11 59 42

On smaller screen, on info is not on one line :
Screenshot 2021-10-22 at 12 33 08

I would like to get confirmation from @PrestaShop/ux-team before approving the PR. Is it the wanted behavior ? What do you think ?

**Comment by prestascott** [comment]
Nice work!

LGTM! ✅

**Comment by florine2623** [comment]
Hello all,

It is QA approved !
Thanks everyone !

**Comment by Progi1984** [comment]
Thanks @okom3pom & @florine2623 @prestascott

**Pull request merged**
