### PR TITLE
Add support for blacklisting modules.

### PR DESCRIPTION
**Pull request by guestisp**
In some environments some modules must be blacklisted for security reasons.
This PR add the modules blacklist feature.

Not directly using an array because constants only support scalar values, thus, a CSV constant is required, for example: `define('_PS_MODULES_BLACKLIST_', 'module1, module2, module3');` in `settings.inc.php`

I'm open to suggestions or make improvements.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.

Let's say this constant is not defined, a module could then exclude another module if it defines it don't you think ?

Regards

**Comment by guestisp** [comment]
Good catch. I'll use a `Tool::safeDefine` (as per my previous PR) to force a blank constant if not overridden by `settings.inc.php`. What do you think ? In this way, constant is always defined.

**Comment by guestisp** [comment]
@gRoussac what do you think about my latest comment ?

**Comment by guestisp** [comment]
Any update on this ?

**Comment by kpodemski** [comment]
@gRoussac @jeromenadaud guys... at least leave some reply here, here is a lot of completely forgotten PR with nice features... maybe it is time to check/close/merge them? if something is not acceptable maybe just close this PR, it is better to close it than leave forgotten imo

**Comment by jeromenadaud** [comment]
Hi @kpodemski @guestisp,

we are refactoring modules page, and your feature will be taken in consideration by @PrestaShop/prestashop-product-managers .

Best regards

**Comment by kpodemski** [comment]
Ok :) Now we have what's next :)

thx, and btw. @jeromenadaud  remember about these .git folders... ;)

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Pull request closed without merging**
