### PR TITLE
Mitigate multiple function call CartPresenter::present

### LINKED ISSUE #31299: Duplicate and triple call to CartPresenter::present()
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When on cart page, `CartPresenter::present()` is called the first time here: https://github.com/PrestaShop/PrestaShop/blob/c130e2d2e0a2bd72d0dd1800114e05c0dff9e22d/classes/controller/FrontController.php#L491
then a second time: https://github.com/PrestaShop/PrestaShop/blob/c130e2d2e0a2bd72d0dd1800114e05c0dff9e22d/classes/controller/FrontController.php#L496 calls `this->getTemplateVarPage()` which is https://github.com/PrestaShop/PrestaShop/blob/c130e2d2e0a2bd72d0dd1800114e05c0dff9e22d/controllers/front/CartController.php#L551-L562
And a third time here:
https://github.com/PrestaShop/ps_shoppingcart/blob/58eb1f7a0fd481976cff427e57ebc6c0b2d8e06e/ps_shoppingcart.php#L96

### Expected behavior

We should call this function only once. There is no reason to call it multiple times.

### Steps to reproduce

1. Add after this line https://github.com/PrestaShop/PrestaShop/blob/674d6128c852a61ff3803206051d2bc29288871f/src/Adapter/Presenter/Cart/CartPresenter.php#L317 : `debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);`
2. Navigate to the cart page of the shop
3. Note the three backtraces displaying

### PrestaShop version(s) where the bug happened

8.0.1, dev

### PHP version(s) where the bug happened

any

### If your bug is related to a module, specify its name and its version

ps_shoppingcart dev

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Mitigate multiple redundant function calls using cache
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Put debug_print_backtrace in the function CAtrPresenter::present and observe.
| Fixed ticket?     | Fixes #31299
| Related PRs       | none
| Sponsor company   | Société Biblique de Genève

### CODE REVIEW

**Comment by Hlavtox** [comment]
Not sure if it's a real scenario, but watch out for this. Not sure if it can happen.
-> present
-> some changes in the cart
-> present

**Comment by lmeyer1** [comment]
@Hlavtox
Between the first and second call a change to the cart is impossible to happen. The call happens less that 10 executed lines from each other.

If the cart would change between the first and the third call, it would be a bug, and the symptoms would be obvious. Remember, the first call assigns the smarty `cart` variable to the page, the third call counts the number of products to display it in the cart widget at the to of the page.

Change in between means: The cart displayed on the page is different from the cart displayed in the widget. For instance, the cart page would display 2 articles, and the cart widget would display 3 articles. If this could happen, it would be noticed as a bug in the display of the order page.
Therefore, we can safely assume that the cart does not change in between.

**Comment by Hlavtox** [comment]
### Performance test
before
⬇️ 
after

**Review by 0x346e3730 — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by davidcylke** [comment]
Can this make big carts load faster? 🤔

**Comment by lmeyer1** [comment]
@davidcylke The way carts are calculated is a mess. This is just the tip of the iceberg.

**Comment by davidcylke** [comment]
> 
I know... Im checking github on weekly basis with hope someone will take care of it. Its a disaster for B2B sellers on prestashow.

**Comment by AureRita** [comment]
Hi @lmeyer1 

Thank you for your PR ! I tested your PR and I still have the three present, as you can see it on this screenshot : 

image

Did I miss something to do in the PR ? 

Waiting for your feedback

**Comment by Hlavtox** [comment]
@AureRita If you look on the code, you see that the work has been done inside the present `function`. If you did not find anything wrong, the PR works fine.

**Comment by Hlavtox** [comment]
@PrestaShop/qa-team This needs to be tested by a developer.

**Comment by Hlavtox** [comment]
Tested on localhost

**Before - present called and processed 3 times.**

before

**After - present called 3 times, but processed only 1 time.**

after1
after2

**Pull request merged**
