### PR TITLE
Delete old module manager JS files

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There are old unused JS files in old admin theme. These files were already migrated to TS.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test that BO assets build OK. Briefly check that module manager works normally - try uploading a module and doing some bulk actions.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
There's a **very little chance** that some people use those files, it's hard to believe, so I'm in favor of merging it :D

**Review by SharakPL — APPROVED** [review]
obraz

**ps_mbo** v.2 used one of these files, but it's not used anymore in current v.4

**Review by djoelleuch — APPROVED** [review]
Hi @Hlavtox 
It's QA approved :heavy_check_mark:
Automated tests --> OK

thank you ! :rocket:

**Comment by Hlavtox** [comment]
Thank yoooouu

**Pull request merged**
