### PR TITLE
[*] BO : Module page enhance list view display mode

### PR DESCRIPTION
**Pull request by ShepherdV8**
Please take the time to edit the "Answers" rows with the necessary information:

| Questions | Answers |
| --- | --- |
| Branch? | Develop |
| Description? | When viewing BO modules page in list mode, the modules are jumbled, needing more space and some padding. This change cleans it up nicely and makes it much easier to read. First try with git. |
| Type? | Improvement |
| Category? | BO |
| BC breaks? | No |
| Deprecations? | No |
| Fixed ticket? | None |
| How to test? | Just look at the modules page in list view before this change. |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi, please edit the "Answers"  column.

**Comment by superGB** [comment]
Ok for me, this is a small improvement until we implement a responsive view.

**Comment by tchauviere** [comment]
Hi @ShepherdV8,

Thanks for your PR, I merge it it now, but keep in mind that we are still working on this UI, so be aware that your changes can be overidden shortly by us :)

Thanks again for your contribution !

**Comment by ShepherdV8** [comment]
This was my first commit using Git I see the title has changed, Will the  first line in the message area will end up as title???

Also first time with the questions and answers is it correctly filled.

Thanks.

**Comment by xBorderie** [comment]
Thank you for filling the table, @ShepherdV8 ! I updated it a bit, taking the content from your commit's name. Next time, could you please follow [PrestaShop naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), for both the commit's name and the PR's title? Thank you!

**Pull request merged**
