### PR TITLE
Add VAT for Monaco

### LINKED ISSUE #22790: Missing localization pack for Monaco
#### Describe the bug

Orders placed to Monaco do not contain any tax.

#### Expected behavior

Orders placed to Monaco must respect the French VAT.

#### Steps to Reproduce

1. Place an order with delivery in Monaco
2. Prices are exclusive of VAT

I'll make a PR soon.

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR adds VAT to Monaco. Monaco must follow France VAT rules.
| Type?             | improvement
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22790
| How to test?      | -
| Possible impacts? | -
| Sponsor company | @Creabilis

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22811)

### CODE REVIEW

**Comment by micka-fdz** [comment]
Hi. I just added MC localization pack and regenerated EU tax rules groups with `prestashop:taxes:update-eu-tax-rule-groups` command. Can you have a look?

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@micka-fdz Thank you for your contribution. Sorry, I validated your PR but I didn't see there is a conflicting file. Could you rebase your PR and ping me for a new validation ?

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @micka-fdz ,

Thanks for your PR !
It is all good to me !

**Comment by Progi1984** [comment]
Thanks @micka-fdz & @florine2623

**Pull request merged**
