### PR TITLE
Fix autoload for composer 2.0 to be compliant with PSR-4

### LINKED ISSUE #20986: Composer dump returns deprecation dialog
#### Describe the bug

Something wrong with code,

#### Expected behavior

No deprecation's and similar. 

#### Steps to Reproduce

```bash-script
$ composer dump-autoload -o
```
retuens
```bash-script
Deprecation Notice: Class Tests\Core\Checkout\TermsAndConditionsTest located in ./tests/Unit/Core/Checkout/TermsAndConditionsTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\Unit\PrestaShopBundle\Utils\BoolParserTest located in ./tests/Unit/Core/Util/BoolParserTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\Unit\Core\Util\Country\ZipCodePatternResolverTest located in ./tests/Unit/Core/Domain/Country/ZipCodePatternResolverTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\PrestaShopBundle\Routing\Converter\RoutingCacheKeyGeneratorTest located in ./tests/Unit/PrestaShopBundle/Routing/Converter/RoutingCacheKeyGeneratorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\PrestaShopBundle\Routing\Converter\LegacyUrlConverterTest located in ./tests/Unit/PrestaShopBundle/Routing/Converter/LegacyUrlConverterTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\PrestaShopBundle\Routing\Converter\RouterProviderTest located in ./tests/Unit/PrestaShopBundle/Routing/Converter/RouterProviderTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\PrestaShopBundle\Routing\Converter\CacheProviderTest located in ./tests/Unit/PrestaShopBundle/Routing/Converter/CacheProviderTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Tests\PrestaShopBundle\Routing\Converter\LegacyRouteTest located in ./tests/Unit/PrestaShopBundle/Routing/Converter/LegacyRouteTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\Request\ParamConverter\ArgumentNameConverterTest located in ./vendor/sensio/framework-extra-bundle/Tests/Request/ArgumentNameConverterTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\DependencyInjection\AddExpressionLanguageProvidersPassTest located in ./vendor/sensio/framework-extra-bundle/Tests/DependencyInjection/Compiler/AddExpressionLanguageProvidersPassTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\DependencyInjection\AddParamConverterPassTest located in ./vendor/sensio/framework-extra-bundle/Tests/DependencyInjection/Compiler/AddParamConverterPassTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShop\TranslationToolsBundle\Tests\Translation\Dumper\MultilanguageCatalogTest located in ./vendor/prestashop/translationtools-bundle/Tests/Translation/MultilanguageCatalogTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShop\TranslationToolsBundle\Tests\Translation\Dumper\TraitExtractorTest located in ./vendor/prestashop/translationtools-bundle/Tests/Translation/Extractor/TraitExtractorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShop\TranslationToolsBundle\Tests\Translation\Extractor\FlattenizerTest located in ./vendor/prestashop/translationtools-bundle/Tests/Translation/Extractor/Util/FlattenizerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShopBundle\Install\SimplexmlElement located in ./src/PrestaShopBundle/Install/Simplexml.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Classes\SearchCoreTest located in ./tests-legacy/Integration/classes/SearchCoreTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Integration\Classes\Db\DbTest located in ./tests-legacy/Integration/classes/db/DbTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Classes\MediaCoreTest located in ./tests-legacy/Integration/classes/MediaCoreTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Integration\ModuleGetPossibleHooksListTest located in ./tests-legacy/Integration/classes/module/ModuleGetPossibleHooksListTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Integration\ModulesGetOverrideTest located in ./tests-legacy/Integration/classes/module/ModuleGetOverrideTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Integration\ModuleOverrideInstallUninstallTest located in ./tests-legacy/Integration/classes/module/ModuleOverrideInstallUninstallTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Classes\ShopCoreTest located in ./tests-legacy/Integration/classes/ShopCoreTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Classes\CacheCoreTest located in ./tests-legacy/Unit/classes/CacheCoreTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Core\Addon\ThemeRepositoryTest located in ./tests-legacy/Unit/Core/Addon/Theme/ThemeRepositoryTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Core\Addon\ThemeValidatorTest located in ./tests-legacy/Unit/Core/Addon/Theme/ThemeValidatorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Core\Addon\Module\ModuleManagerTest located in ./tests-legacy/Unit/Core/Addon/Module/ModuleManagerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Core\Addon\Module\ModuleRepositoryTest located in ./tests-legacy/Unit/Core/Addon/Module/ModuleRepositoryTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Stock\FakeStockAvailable4759 located in ./tests-legacy/Unit/Core/Stock/Core_Stock_StockManagerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Stock\FakeProduct4759 located in ./tests-legacy/Unit/Core/Stock/Core_Stock_StockManagerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Stock\FakePackItemsManager4759 located in ./tests-legacy/Unit/Core/Stock/Core_Stock_StockManagerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Stock\StockAvailableTest located in ./tests-legacy/Unit/Core/Stock/Core_Stock_StockManagerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Product\PriceFormatter located in ./tests-legacy/Unit/Core/Business/Product/ProductPresenterTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Product\ProductPresenterTest located in ./tests-legacy/Unit/Core/Business/Product/ProductPresenterTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Product\Search\SearchTest located in ./tests-legacy/Unit/Core/Business/Product/Search/SearchTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Product\Search\URLFragmentSerializerTest located in ./tests-legacy/Unit/Core/Business/Product/Search/URLFragmentSerializerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Product\Search\PaginationTest located in ./tests-legacy/Unit/Core/Business/Product/Search/PaginationTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Product\Search\SortOrderTest located in ./tests-legacy/Unit/Core/Business/Product/Search/SortOrderTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Payment\PaymentOptionFormDecoratorTest located in ./tests-legacy/Unit/Core/Business/Payment/PaymentOptionFormDecoratorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Core\Localization\DataLayer\LocaleCacheDataLayerTest located in ./tests-legacy/Unit/Core/Localization/LocaleCacheDataLayerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\Classes\Product\SpecificPrice\SpecificPriceFormatterTest located in ./tests-legacy/Unit/Classes/Product/SpecificPriceFormatterTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class LegacyTests\Unit\classes\Smarty\TemplateFinderTest located in ./tests-legacy/Unit/Classes/Smarty/TemplateFinderTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Csa\Bundle\GuzzleBundle\Tests\GuzzleHttp\Subscriber\DoctrineAdapterTest located in ./vendor/csa/guzzle-bundle/src/Tests/GuzzleHttp/Subscriber/CacheSubscriberTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201
```
**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.3.22-FPM

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Use the correct paths and class names. Some classes are now stored in other files.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Fixes #20986
| How to test?  | Test must be green and no more Core deprecations (Not Sensio, TranslationTools and GuzzleBundle) with the `composer dump-autoload -o` command. 

After:
```
[3.6.8] got@got:~/projects/prestashop/source/develop[fix/autoload]$ composer dump-autoload -o
Generating optimized autoload files
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\DependencyInjection\AddParamConverterPassTest located in ./vendor/sensio/framework-extra-bundle/Tests/DependencyInjection/Compiler/AddParamConverterPassTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\DependencyInjection\AddExpressionLanguageProvidersPassTest located in ./vendor/sensio/framework-extra-bundle/Tests/DependencyInjection/Compiler/AddExpressionLanguageProvidersPassTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Sensio\Bundle\FrameworkExtraBundle\Tests\Request\ParamConverter\ArgumentNameConverterTest located in ./vendor/sensio/framework-extra-bundle/Tests/Request/ArgumentNameConverterTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShop\TranslationToolsBundle\Tests\Translation\Extractor\FlattenizerTest located in ./vendor/prestashop/translationtools-bundle/Tests/Translation/Extractor/Util/FlattenizerTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShop\TranslationToolsBundle\Tests\Translation\Dumper\TraitExtractorTest located in ./vendor/prestashop/translationtools-bundle/Tests/Translation/Extractor/TraitExtractorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class PrestaShop\TranslationToolsBundle\Tests\Translation\Dumper\MultilanguageCatalogTest located in ./vendor/prestashop/translationtools-bundle/Tests/Translation/MultilanguageCatalogTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Csa\Bundle\GuzzleBundle\Tests\GuzzleHttp\Subscriber\DoctrineAdapterTest located in ./vendor/csa/guzzle-bundle/src/Tests/GuzzleHttp/Subscriber/CacheSubscriberTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Generated optimized autoload files containing 11061 classes
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20990)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@PierreRambaud Developer validation instead of QA validation ?

**Comment by Progi1984** [comment]
Ping @PrestaShop/qa-functional Ok for a Dev Validation ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud Developer validation instead of QA validation ?

Yes, tests are passing, only a dev validation is needed.
But I will do a new pull request to update our dependencies

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
@PierreRambaud So PrestaShop is now Composer 2 compliant ? That is some great news worthy of being acknowledged in Release Note I believe 😄

**Comment by PierreRambaud** [comment]
> @PierreRambaud So PrestaShop is now Composer 2 compliant ? That is some great news worthy of being acknowledged in Release Note I believe

Not yet, we must update our dependencies :)

**Pull request merged**
