### PR TITLE
Remove empty category blocks in module manager

### LINKED ISSUE #30260: Remove empty category blocks in module manager
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

There's an empty block in the module manager where there are no modules in a category.

### Describe the solution you'd like

Whenever there is no module in a category, the block is no longer shown.

Before
image

After
image

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Whenever there is no module in a category, the block is no longer shown.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30260
| Related PRs       | #30810 (To merge together)
| How to test?      | Load module manager. See the empty blocks are no longer there
| Possible impacts? | None?

Before:
Before

After:
After

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
`src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid_manage_empty.html.twig`
This file has been [modified recently](https://github.com/PrestaShop/PrestaShop/pull/28318) with this hook:
```
{{ renderhook('displayEmptyModuleCategoryExtraMessage', {'category_name': category.name}) }}
```
To meet requirements from the SMB edition. @MatShir approved it 

I think it looks better without this information, but it would be good to align on this topic.

**Comment by ghost** [comment]
@kpodemski I don't know? there was ps_mbo for ads before? not here? 

Screenshot - 2022-08-23T195418 231

**Comment by kpodemski** [comment]
@okom3pom I don't know. I just want to avoid going back and forth with changes that were previously (not that long ago) approved :D

**Review by Hlavtox — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by MatShir** [comment]
The issue was approved, I make sense to add content for marketplace module in the module manager https://github.com/PrestaShop/PrestaShop/issues/28317. UX could be enhanced ofc. It looks a good option to hide the block when nobody is hooked to it, only if we don't remove the hooks. Could you confirm @eternoendless?

**Comment by matks** [comment]
Waiting for @eternoendless feedback: this PR currently disables the use of the hook mentioned by @kpodemski . So it seems we don't want to merge it like this.

**Comment by Hlavtox** [comment]
@eternoendless @matks 

```twig
{% block catalog_category_empty %}
  {% set hookData = renderhook('displayEmptyModuleCategoryExtraMessage', {'category_name': category.name}) %}
  {% if hookData is not empty %}
    <div class="modules-list module-list-empty" data-name="{{ category.refMenu }}">
      <p>{{ 'You do not have module in « %categoryName% ».' | trans({'%categoryName%': category.name}, 'Admin.Modules.Feature') }}</p>
      {{ hookData }}
    </div>
  {% endif %}
{% endblock %}
```

**Comment by eternoendless** [comment]
Fixed using @Hlavtox's suggestion 👍 

I had to move the category name inside the block though. I also removed the wording, which not only had spelling and punctuation errors, but I also found it useless if you're adding content...

**Review by kpodemski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]
🍬

**Comment by sLorenzini** [comment]
hello @eternoendless,

Thank you for the PR.
To make a review in QA, we need to have an issue linked to the PR 😃 please 🙏 

Thanks in advance

**Comment by kpodemski** [comment]
@sLorenzini 

I've just created an issue to unblock this PR:
https://github.com/PrestaShop/PrestaShop/issues/30260

Could you add proper labels to it? because it has already been accepted,

**Review by MhiriFaten — COMMENTED** [review]
Hello @eternoendless ,

I checked this PR and I the issue is well fixed :heavy_check_mark: 
But the automated tests are failed in `BO:modules` test.

image

https://github.com/MhiriFaten/testing_pr/actions/runs/3443969574/jobs/5748649304

ping @PrestaShop/qa-automation Could you please check it ?

Thank you !

**Comment by boubkerbribri** [comment]
It's seems that the test should be updated, we will take a look.

**Comment by nesrineabdmouleh** [comment]
Hello @eternoendless @MhiriFaten @boubkerbribri 

Thank you for the PR and the tests !
I create this [PR](https://github.com/PrestaShop/PrestaShop/pull/30810) to fix the failed automated tests :100: 

The 2 PRs should be merged together :)
QA :heavy_check_mark: 

Thank you!

**Comment by matks** [comment]
@FabienPapet don't forget to add the milestone ;)

**Comment by boubkerbribri** [comment]
And please don't forget if there is a PR that's related (here was to fix UI tests)

**Pull request merged**
