### PR TITLE
[Performances] modules folder doens't need to be installed between parallel builds

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | 
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12600)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Build total time;  Total time 1 hr 11 min 33 sec => https://travis-ci.org/PrestaShop/PrestaShop/builds/494087020

PR that revert the Composer extension:  Total time 1 hr 17 min 14 sec  =>https://travis-ci.org/PrestaShop/PrestaShop/builds/493849354?utm_source=github_status&utm_medium=notification

Conclusion: no need to revert this change.

WDYT @PierreRambaud?

**Comment by PierreRambaud** [comment]
We don't care about total time because you can have a total time of 2h with only 5 builds of 3 minutes.
And more because we don't execute `composer install` only on travis.
We care about time with a `composer install` command.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Cache modules for travis will not improve performance.
We must improve performance for merchants not for travis.

**Comment by mickaelandrieu** [comment]
Merchants don't use Composer, they use the releases: we revert an interesting feature for everyone because we can't fix performance issues of our nightlies.

We could apply the same strategy on GCP, but we prefer to remove features in native modules than improve our nightly workflow :/

**Comment by PierreRambaud** [comment]
This is not because of GCP. 
With this kind of bad performance we can't automate, we can't work with a little computer, it eat memory and cpu, it's very very slow and it's only interesting for build :/

**Comment by mickaelandrieu** [comment]
Ok, but this also needs to be documented outside of ADR (ie in the docs),
because a lot of people update their native modules directly on the `modules` folder so we need to list the impacted modules and the related restrictions in the documentation: no dependencies managed by Composer for them.

**Pull request closed without merging**
