### PR TITLE
Allow the special character & to be indexed for search results

### LINKED ISSUE #26020: Allow the '&' character in product names to be indexed for search
#### Is your feature request related to a problem?

"Search indexes only alphanumeric characters but a few times I had to modify this behaviour to allow products containing the & in name to be indexed as merchants having such products in catalog complain about these products missing from search. The most recent example is a beverages wholesaler having products like J&B and similar which didn't appear for customers searching them."

#### Describe the solution you'd like

Modify the Search class static function extractKeyWords to allow the `&`.

#### Alternatives you've considered

Changing J&B with JandB which is ridiculous.

#### Additional context

None

### PR DESCRIPTION
**Pull request by Rho-bur**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There are many products in all industries having the name containing this sign and currently such products are skipped from the search results. Example: a beverages retailer will not find in the search results whisky brands named like J&B.
| Type?             | improvement
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26020.
| How to test?      | Add an & sign to a product name, re index the products in Sop Parameters -> Search then search for this product in FO.
| Possible impacts? | No impact.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26865)

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hi @Rho-bur your PR deletes 2 files that I dont think are related to the PR

**Comment by Rho-bur** [comment]
> Hi @Rho-bur your PR deletes 2 files that I dont think are related to the PR

@matks I am sorry, I am about to give up on this :-(
I have removed the second commit which altered the other two files and now 27 appears as changed.
I probably have all this process wrong and only messing up your work.
Should I close this and forget about it?
I can apply my fix manually to all my clients I just wanted to let others do this if need be.

**Comment by atomiix** [comment]
Hi @Rho-bur, please don't give up on this! We can give you a hand to fix the issue with your branch. I don't really know what happened here but it seems that your fix is not in this PR anymore. You can try to reset your branch to make it up-to-date with develop and then re-apply your fix. Or, you can try to start from a new branch and create a new PR if it looks simpler to you.

**Comment by Rho-bur** [comment]
@atomiix OK, I'll close this and do a new PR.
Somehow I feel stupid, I use Git for years, submitted PR's for other projects (Node/Vue) even submitted PR for PrestaShop documentation but this kills me; the worst is that I do not understand what I do wrong which proves that I do not understand the full process of creating a successful PR for PrestaShop core :-(

**Comment by Rho-bur** [comment]
Closing this as being useless.

**Pull request closed without merging**
