### PR TITLE
[-] CORE : Missing variable in CartPresenter

### PR DESCRIPTION
**Pull request by martinfojtik**
Variable `$product['price_tax_exc']` is required in ProductPresenter

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hi @fojtCz,

Do you need this variable for solve a particular bug ?
We wanted to avoid the template to care if the price should be displayed with or without taxes. The `price` variable contains the correct value, formatted and ready to be displayed.

Regards

**Comment by fojtCz** [comment]
Hi @maximebiloe,

variable is used in `private function addPriceInformation` in statement

```php
if ($settings->include_taxes) {
      $price = $regular_price = $product['price'];
} else {
      $price = $regular_price = $product['price_tax_exc'];
}
```

**Comment by maximebiloe** [comment]
I think you misunderstood something. You're referring to something used in `ProductPresenter`. This is used inside the the `CartPresenter` but not in the other way.
So, I don't see why we should add this ? Maybe it's me that miss something.

**Comment by fojtCz** [comment]
The `ProductPresenter` is called a feew lines later in `return $presenter->presentForListing ...` and `addPriceInformation` is called in `ProductPresenter` and is expecting to have the `$product['price_tax_exc']` variable. Does it make sense?

Sorry, for my English and my bad explanation.

**Comment by maximebiloe** [comment]
Thanks for your explanations, I understand now :smile: 

Could you rebase your PR to make the tests pass, please ?

Thank you

**Comment by fojtCz** [comment]
Off course. It's done.

**Pull request merged**
