### PR TITLE
Provide modules information about old order status

### LINKED ISSUE #24474: actionOrderStatusPostUpdate hook should have the old order status in params
#### Is your feature request related to a problem?

The actionOrderStatusPostUpdate hook have only newOrderStatus parameter but the order state has already been changed in the order.
#### Describe the solution you'd like

Add the old order state in params of the hook.

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR provide modules with information about old order status that is being changed.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24474
| How to test?      | Hook to actionOrderStatusPostUpdate and dump result, you should also get the old status.
| Possible impacts? | None, only adding data.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26743)

ping @jf-viguier

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
the issue says it should be validated by @PrestaShop/product-team , but I think it's more of a developer issue 🤔  

I send it in QA

**Comment by HanaRebaiQA** [comment]
Hello @Hlavtox 

I have tested this PR. The expected behavior is well added. See screen-record & screenshot below : 
https://watch.screencastify.com/v/RU52IWEW0tPkUqBNiL62 

The result of the informations of Order Status (Old and New one) in the DB are OK : 
image

Except this one : In the OldOrderStatus the fields of `name` and `template` are an array and not a string like in the NewOrderStatus
image

Do you accept it ?

Thanks,

**Comment by Hlavtox** [comment]
@matthieu-rolland @jolelievre Guys, should this hook return OrderState objects with **specified id_lang** (name is a string) or **not specified** (name is an array for each language)?

There is an inconsistency now. Lines concerned 99-100 here: https://github.com/PrestaShop/PrestaShop/blob/a5477a0c3a0131e820b759b049a4a314e46b74d1/classes/order/OrderHistory.php#L100

**Comment by matks** [comment]
> @matthieu-rolland @jolelievre Guys, should this hook return OrderState objects with **specified id_lang** (name is a string) or **not specified** (name is an array for each language)?
> 
> There is an inconsistency now. Lines concerned 99-100 here:
> 
> https://github.com/PrestaShop/PrestaShop/blob/a5477a0c3a0131e820b759b049a4a314e46b74d1/classes/order/OrderHistory.php#L100

## Simple answer

I think we should copy the `$newOrderStatus` behavior -> specified id_lang just to make it coherent.

If a module wants to display the order state name in another language he can do it with an extra query.

## Long term answer

The best would be not to provide such data, simply pass the OrderState ID and let the module fetch whatever it needs. But that would be a BC break so I suggest we stay with simple answer.

**Comment by Hlavtox** [comment]
@matks Hi, I unified both states.
```
$new_os = new OrderState((int) $new_order_state, $order->id_lang);
$old_os = new OrderState((int) $order->current_state, $order->id_lang);
```

> The best would be not to provide such data, simply pass the OrderState ID and let the module fetch whatever it needs. But that would be a BC break so I suggest we stay with simple answer.

I don't think so, why would the module need to re-create the OrderState object and loose performance? If it is already created and loaded, I would pass it as it is.
__________________________________

@HanaRebaiQA Hello Hana, it's ready for recheck, when you got time ;-)

**Comment by atomiix** [comment]
@Hlavtox phpstan is not happy ;)

**Review by matthieu-rolland — COMMENTED** [review]
I'm not sure I understand what phpstan is not happy about here 🤔

**Comment by Hlavtox** [comment]
I will have a look on it today, I see no reason why it should not work 🧐

**Comment by matthieu-rolland** [comment]
so I asked for our phpstan specialist's opinion (aka @Progi1984 ), and it seems like the issue is that $old_os is an object 🤔  

if that's the actual issue, phpstan's message is quite cryptic indeed: `Negated boolean expression is always false`

**Comment by matks** [comment]
@Hlavtox @matthieu-rolland this PR is rejected by phpstan for a reason we dont fully understand is that right?

**Comment by atomiix** [comment]
I agree with @matthieu-rolland, I think replacing
```php
if ($virtual_products && (!$old_os || !$old_os->logable) && $new_os && $new_os->logable) {
```
with
```php
if ($virtual_products && !$old_os->logable && $new_os->logable) {
```

would do the trick

**Comment by Hlavtox** [comment]
Done, let's try to see what it does. :-) I will rebase afterwards.

**Review by Progi1984 — DISMISSED** [review]
Hello @Hlavtox, thanks for your contribution, would you mind to rebase your pull request? Thanks

Reference : https://anavarre.net/how-to-rebase-a-github-pull-request/

**Comment by Hlavtox** [comment]
@Progi1984 rebased

**Review by atomiix — APPROVED** [review]

**Comment by Hlavtox** [comment]
@Progi1984 Rebased... Can you ping for reapproval so its merged?

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @Hlavtox 

I checked again this PR. The issue is fixed.

Here my tested cases : 
-Check with update an existing Order : OK
-Check with create an order from BO : OK
-Check with create an order from FO : OK
-Check with create an order from FO and updated with BO : OK
-Check with update an existing order with API : OK
-Check in database : OK
-Check with multistore : OK
-Check with different languages (RTL and no RTL) : OK

image

image

With First Create : 
image

https://user-images.githubusercontent.com/92912932/161100155-89ffdf85-996b-43c9-9f46-764ef2cfc66c.mp4


https://user-images.githubusercontent.com/92912932/161100217-e6eddbfa-255b-4619-afa4-22f7391c8772.mp4


https://user-images.githubusercontent.com/92912932/161100282-f55e8ad0-ce63-42ce-93a2-f9bc3be3cb80.mp4


Thanks!

**Comment by PululuK** [comment]
Thanks @Hlavtox 

@PrestaShop/prestashop-maintainers  see doc here https://github.com/PrestaShop/docs/pull/1339

**Comment by matks** [comment]
I think we also need to document BC break inside https://devdocs.prestashop.com/8/modules/core-updates/8.0/

**Comment by Hlavtox** [comment]
@matks I think its not a BC since it only adds a new property no? Or am I missing something?

**Comment by matks** [comment]
@Hlavtox Yes you're right. I was wrong it's not a BC but it's a hook parameter change. Does it need documentation?

**Comment by Hlavtox** [comment]
@matks Yes, it does. I will do it. ;-)

EDIT: @PululuK already did :-)

**Comment by awitkutarahil** [comment]
Thank you

**Pull request merged**
