### PR TITLE
Add hook delete carrier

### PR DESCRIPTION
**Pull request by janblahajmedia**
Add new hook when carrier is deleted.

### CODE REVIEW

**Comment by kpodemski** [comment]
you can use:
`actionObjectCarrierDeleteBefore` or `actionObjectCarrierDeleteAfter`

**Comment by janblahajmedia** [comment]
Ok, thanks ;-)
I could not find this hook.

**Comment by kpodemski** [comment]
These are "dynamic" hooks, you can check ObjectModel.php and search for `Hook::exec` :)

**Comment by janblahajmedia** [comment]
I trying register hooks what you wrote, but doesn't work.
So I walked code and I found that deleting carriers does not actually call method delete but calling the update method (which sets the status of deleted to 1). So the correct hook name for remove carrier is "actionObjectCarrierUpdateAfter" or "actionObjectCarrierUpdateBefore".

**Comment by kpodemski** [comment]
Yep, I forgot that it is not a good practice to delete carrier and yes, instead of deleting it's just marked as inactive, good point

**Comment by xBorderie** [comment]
Thank you for this PR, but you made it on an old version, and it includes several non-related commits. It cannot be merged.
Please update your PR to only use your commit (a67b998442c84837c5aff5982445f69aaf667152), or close this PR then create a new one :)

Thank you!

**Comment by kpodemski** [comment]
@xBorderie there is no point to create new PR in this case

**Comment by xBorderie** [comment]
Alright, then :)
Closing the PR!
Thanks to the both of you for your contribution!

**Pull request closed without merging**
