### PR TITLE
FO: Allow to define module front controllers layout

### PR DESCRIPTION
**Pull request by tonyyb**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?    |    1.7
| Description?  | Currently it is not possible to define the layout of a module front controller.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Try to define the layout of a module from AdminThemes back office controller.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you @tonyyb for this PR!
You changed the PR's title, but what Preston is asking you is to change the name of your commit, 548b307559a3b1f35b4857892715321e927ee529.

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by xBorderie** [comment]
Thank you for your update!

Sadly, you now have malformed commits instead of just one commit:
* the initial commit, which now follows the naming convention (thanks!),
* one "Merge" commit -- which if merged can break the repository's history!

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by tonyyb** [comment]
Hi @xBorderie !
Is it ok now ?

**Comment by xBorderie** [comment]
Alas, no :/ 
Look at [the commits in your PR](https://github.com/PrestaShop/PrestaShop/pull/7771/commits): it now embarks several commits recently merged into the project.
This seems to indicate that you should first [rebase your local repo](https://git-scm.com/book/en/v2/Git-Branching-Rebasing), then check that your commit is the only one.
Thank you for the effort!

**Pull request closed without merging**
