### PR TITLE
[-] FO : PSCSX-7449, fix parse error in AuthController.php

### PR DESCRIPTION
**Pull request by kpodemski**

### CODE REVIEW

**Comment by kpodemski** [comment]
Of course there's should be some getter in blocknewsletter module but it is almost impossible to force people to update native modules

**Comment by xBorderie** [comment]
Thank you for this PR, Krystian!
I renamed the PR. Core guys, the Forge ticket is here: http://forge.prestashop.com/browse/PSCSX-7449

@kpodemski, could you amend your PR to us the naming guidelines? Most notably the first one, but the second one could also use a bit of a touch-up. Use `git commit --amend` for that. Thanks!

**Comment by mickaelandrieu** [comment]
ping @kpodemski can "squash" your commits ?

**Comment by kpodemski** [comment]
@mickaelandrieu #5221

**Pull request closed without merging**
