### PR TITLE
New design for homepage slider on mobile

### LINKED ISSUE #13589: Classic theme - Mobile improvements
Apply design improvements for mobile view from Ready theme to Classic theme.

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | New design for mobile home slider 
| Type?         | new feature
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13589 
| How to test?  | Mobile version: carousel for home page<br>Before:<br>image<br>After:<br>image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13650)

### CODE REVIEW

**Comment by colinegin** [comment]
I'm not quite fan of arrows' design and position but i'm not really sure of what was supposed to be done here. What do you think @TristanLDD @prestascott ?

**Comment by prestascott** [comment]
@Progi1984 Hello, thank you for your work. :)

Text needs to be placed on the image otherwise users may think it's 2 different components so arrows can't be placed like.

What do you think @TristanLDD ?

**Comment by TristanLDD** [comment]
@coline This is from Nadia's mockup [(here)](https://invis.io/PFOEI0IT3YV#/323412029_Homepage) as long as I remember the point was to separate the text and the image on mobile so it doesn't break the slider, and display the image in full width. 

@Progi1984 I have 2 remarks regarding the design: 
- Can you vertically center the arrows on the image? 
- Can you add navigation dots like on the mockup above? Navigation dots will make it more clear that the text belongs to the slider.

Thanks a lot

**Comment by TristanLDD** [comment]
Hi @Progi1984, here's my feedback after testing the slider on mobile : 

1. Arrows stays in hover blue after click but should return to white
2. The 3 dots should not display above the text, always keep a 20px spacing above and below the dots.
3. Change dots size: 8x8px, 8px spacings
4. Enable swipe gesture
5. Keep the original arrows on desktop and use the grey background arrows on mobile only

Thanks a lot ! 

Slider mobile

**Comment by Progi1984** [comment]
@TristanLDD : Need UX Review
Mobile :
image

Desktop :
image

**Comment by TristanLDD** [comment]
After testing on Chrome Version 78.0.3904.97 (Build officiel) (64 bits), 

I still have wrong display of dots overlaping text:
Capture d’écran 2019-11-18 à 17 13 46

Also, the dots should display only on mobile: 
Capture d’écran 2019-11-18 à 17 31 16

Thanks a lot.

**Comment by Progi1984** [comment]
@TristanLDD Fixed thanks to @NeOMakinG ! Do you want to check a last time ?

**Comment by TristanLDD** [comment]
@Progi1984 I just checked it, approved !

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @Progi1984

**Pull request merged**
