### PR TITLE
Display product name and its attributes translated in order slips and invoices

### PR DESCRIPTION
**Pull request by hibatallahAouadni**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Attributes are not showing on delivery slips and invoices.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9019
| How to test?  | Pass an order then upload the invoice from BO.

### CODE REVIEW

**Comment by Nobodaddy** [comment]
A real milestone! :D
What happens is just that only the last ordered product is displayed with each and every attribute no matter if ordered or not.
I strongly recommend to test those "improvements" before you merge them!

**Comment by hibatallahAouadni** [comment]
Thanks @Nobodaddy for your feedback, it won't be merged till will be fixed.
We will notify you when we get it right.

**Comment by hibatallahAouadni** [comment]
Hello @Nobodaddy it was just a typing mistake, it needs to be group it by order_detail.product_id not by attribute_group.id_lang sorry :/ my bad and thanks again for checking it :)

**Comment by Nobodaddy** [comment]
Desolé, mais il n'était pas tout simplement une erreur de frappe!
As your _CONCAT_/_GROUP_CONCAT_ clause leads to unexpected errors I repeat my call for tests before you make it even worse. My solution works, yours does _not!_
Ever heard of Occam's razor? In simple terms for programming activities one could say: *The simplest working solution is usually the correct one.* :)

**Comment by hibatallahAouadni** [comment]
@Nobodaddy where is your solution ? and I just want make myself clear, this PR is still open and not merged yet, before it gets merged it has to be tested ;)

**Comment by hibatallahAouadni** [comment]
@Nobodaddy we make these change to resolve this problem http://forge.prestashop.com/browse/PSCSX-2323

**Comment by xBorderie** [comment]
I'm guessing he refers to [his answer on the German forum](https://www.prestashop.com/forums/topic/607758-rechnung-und-lieferschein-mit-artikelvarianten/#entry2553141).

Hey @Nobodaddy, could repost here an english translation of your post? Thank you!

**Comment by PascalNetenvie** [comment]
I tried all solutions said here and nothing solved this bug !
I also tried to revert file to one from 1.6.1.12 or 1.6.1.9 and it still the same.

**Comment by hibatallahAouadni** [comment]
Hello @PascalNetenvie this issue has not been in previous releases, so if you encounter another problem similar to this one make a ticket in the forge and we will fix as soon as possible :)

**Comment by PascalNetenvie** [comment]
Thanks but my problem is exactly this one (attributes not showing on invoices).
And this commit don't fix it ...

**Comment by Nobodaddy** [comment]
Like mentioned above:
https://www.prestashop.com/forums/topic/607758-rechnung-und-lieferschein-mit-artikelvarianten/#entry2553141

**Comment by hibatallahAouadni** [comment]
@Nobodaddy does your solution fix this problem  http://forge.prestashop.com/browse/PSCSX-2323 ?

**Comment by Nobodaddy** [comment]
No, I didn't just revert, if you'd look closer. 
However, I don't know if it fixes the forge solution. It just doesn't cause new bugs like your solution does by adding random accessoires' names to products without combinations.

**Comment by PascalNetenvie** [comment]
FOr me Nobodaddy / Eleazar Solution fixed the bug :
SQL as foollow :
```
		SELECT *
		FROM `'._DB_PREFIX_.'order_detail` od
		LEFT JOIN `'._DB_PREFIX_.'product` p
		ON p.id_product = od.product_id
		LEFT JOIN `'._DB_PREFIX_.'product_shop` ps ON (ps.id_product = p.id_product AND ps.id_shop = od.id_shop)
		LEFT JOIN `'._DB_PREFIX_.'product_lang` pl ON (pl.id_product = p.id_product AND pl.id_lang = '.$id_lang.' AND pl.id_shop = od.id_shop)
		WHERE od.`id_order` = '.(int)$this->id_order.'
		'.($this->id && $this->number ? ' AND od.`id_order_invoice` = '.(int)$this->id : '').' ORDER BY od.`product_name`');
```

**Comment by hibatallahAouadni** [comment]
@Nobodaddy you misunderstood me, what I mean is that you delete the modifications made by the PR, here's a screenshot to prove that your solution is nothing but what was in the previous releases (1.6.1.12)
generate pdf invoices in user language

if there's some changes that I can't see please mention it (one by one) thx :)

**Comment by Nobodaddy** [comment]
@hibatallahAouadni 
Yes, there are changes, because I kept this:
**LEFT JOIN `'._DB_PREFIX_.'product_lang` pl ON (pl.id_product = p.id_product AND pl.id_lang = '.$id_lang.' AND pl.id_shop = od.id_shop)**
Short and sweet: https://github.com/PrestaShop/PrestaShop/pull/7893

**Comment by aleeks** [comment]
Hello @hibatallahAouadni 
I'm closing this PR according with legal team!

Thank you!

**Pull request closed without merging**
