### PR TITLE
Error function trans()

### PR DESCRIPTION
**Pull request by AlfonsoSogara**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix error: FatalThrowableError in AdminController.php line 2735: Call to a member function trans() on null
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | In visual composer add a "Images Types"

### CODE REVIEW

**Comment by alfonsoalcantara** [comment]
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Please be specific when describing the PR. <br/> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | In visual composer add a "Images Types"

**Comment by Quetzacoalt91** [comment]
Hello @alfonsoalcantara,

Can you please give us more details on how to reproduce this error?
If we really have something to fix, I think there is another solution (in general, this is an issue related to a translation asked too early, before the parent constructor).

If you can provided the full stack when you get this issue, this would be even better.

Thanks!

**Comment by aleeks** [comment]
Hello @alfonsoalcantara Can you explain a little more please ?
Regards

**Comment by Quetzacoalt91** [comment]
Without more details, we cannot accept your changes.

The `$translator` property is already defined by the parent class when instantiated (https://github.com/alfonsoalcantara/PrestaShop/blob/2e9a57ba251de5e38b7bbd72cfded28364ff740b/classes/controller/Controller.php#L161).

Please check you do not have overrides for this specific method, and contact the module developer if so.

Best regards

**Pull request closed without merging**
