### PR TITLE
Fix setWsPositionInCategory and setWsCategories, the product position in the categories changes

### PR DESCRIPTION
**Pull request by BlackKerio**
After the product has been modified by a webservice, while we also use associations, position in the categories changes

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | After the product has been modified by a webservice,  If you use associations, when you add, remove, or just leave categories, another setWsCategories function will delete and then reinsert the product in all of the listed categories and position in the categories changes
| Type?         | bug fix 
| Category?     |  WS 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | you have to make a modification a product with the webservice with associations and categories 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16697)

### CODE REVIEW

**Comment by matks** [comment]
> Hello @BlackKerio!
> 
> This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

I think this is wrong 😄 thanks for another PR @BlackKerio ❤️

**Comment by matks** [comment]
@BlackKerio so if I understand correctly, category position, for this product, is incremented ? 🤔it seems weird ...

**Comment by BlackKerio** [comment]
yes, the function retrieves positions, deletes the product records in all categories from the table and re-writes them. Unfortunately, you increase +1. In addition, the product is not in any of the categories, set to 0. Which is also wrong, the position starts at 1. Testing performed by [@khouloudbelguith] (https://github.com/PrestaShop/PrestaShop/pull/15286)

**Comment by BlackKerio** [comment]
@khouloudbelguith  I can ask you to test it all at once. And confirm that everything is ok. I recommend two tests, one for product only and the other for product with accessories. thanks

**Comment by khouloudbelguith** [comment]
@BlackKerio, thanks!

This PR should be reviewed by our developers first, so I can test it.

Thanks!

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @BlackKerio,

It is OK
https://drive.google.com/file/d/1eYIJ6ysURUBC4nBsHO4ayLCSYFYrK-g0/view

Thanks!

**Comment by Progi1984** [comment]
Hello @BlackKerio, thanks for your contribution, would you mind to rebase your pull request before merging ? Thanks

**Review by Progi1984 — APPROVED** [review]

**Pull request merged**
