### PR TITLE
Remove extra checks

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes some basic calls to validate booleans and arrays. Adds types instead.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | Yes - there is a BC break. Validate::isBool returns true even if you passed null or 0/1. This won't be allowed now.
| Deprecations?     | no
| How to test?      | Tests green should be sufficient.
| UI Tests          | 🟢  https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7016764315
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### Additional information
Some issues in tests are due to bad calls to displayDate.
- statsproducts - https://github.com/PrestaShop/statsproduct/pull/37 + https://github.com/PrestaShop/statsproduct/pull/38 ✅ 
- ps_facetedsearch - https://github.com/PrestaShop/ps_facetedsearch/pull/945 + https://github.com/PrestaShop/ps_facetedsearch/pull/946 + https://github.com/PrestaShop/ps_facetedsearch/pull/947 ✅

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@PrestaShop/qa-automation Minor issues due to bad module calls, I fix them in separate PR. Can we merge this? :-)

**Review by M0rgan01 — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Review by ShaiMagal — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@PrestaShop/qa-automation Guys, I am fighting a bit with the `modules` campaign. A single run in debug mode is here - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7004428965.

Before, there was an issue when `ps_facetedsearch` was calling `Tools::displayDate` with a bad argument count. This was fixed in [3.14.1](https://github.com/PrestaShop/ps_facetedsearch/releases/tag/v3.14.1). I rebased this PR, everything. The correct code is being used - check [shop-artifacts](https://github.com/Hlavtox/ga.tests.ui.pr/suites/18521629123/artifacts/1075027013).

However, the test still throws this error in a file `modules\ps_facetedsearch\views\templates\admin\manage.tpl`, but why? There is nothing with dates anymore in that file. And the module works correctly when I try it manually.

Snímek obrazovky 2023-11-27 134249

**Comment by Progi1984** [comment]
@Hlavtox Could you update this line : https://github.com/PrestaShop/PrestaShop/blob/develop/tests/UI/data/demo/modules.ts#L32 ?

(I will fix the source of the bug in the future)

**Comment by Hlavtox** [comment]
@Progi1984 OK, updated, let's try - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7016764315

But how come that there was `$this->version = '3.14.1';` in the artifact? 🤔

**Comment by Hlavtox** [comment]
@Progi1984 All green!!! :-) https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/7016764315

**Review by ShaiMagal — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Pull request merged**
