### PR TITLE
Fix DNI mandatory for Italy

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Please read ticket https://github.com/PrestaShop/PrestaShop/issues/9891
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/9891
| How to test?  | Please read ticket https://github.com/PrestaShop/PrestaShop/issues/9891

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11009)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]
Thank you @MathiasReker 

I updated the base branch as `develop` as we deal with an improvement here.

**Comment by marionf** [comment]
Hello @MathiasReker 

This is my configuration:

DNI added for Italy

capture d ecran_652

No DNI for France

capture d ecran_653

DNI checked in Customers > Address

capture d ecran_629

I try to make an order with an address in France without DNI and I can't

capture d ecran_630

I should be able to make an order without DNI in France because in the country DNI is not added.

**Comment by MathiasReker** [comment]
This PR introduce some other issues as @marionf point out, and I do not have time to look into this issue sorry. I close this PR for now.

**Comment by LanmanGroup** [comment]
@marionf if you check "DNI in Customers > Address" this option is for all countries, so your situation is ok, the error are correct.

This PR is a fix if set "Locations - Countries - Italy (example) > Do you need a tax identification number?" to YES

**Pull request closed without merging**
