### PR TITLE
Fix button alignment inside input-group

### LINKED ISSUE #26644: [FO] Form elements are misaligned in 1.7.x.x and inconsistent on different browsers
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

This bug was there even in 1.7.7, but wasn't so visible.

Login form:

obraz

Looks even worse when focused:

obraz

It's the same on account creation page and checkout page:

obraz

### Expected behavior

Form buttons should be aligned with inputs

### Steps to reproduce

1. Go to Sign in page
2. Go to Create account page
3. Go to Order page, 1st tab: Personal Information
4. Focus password input on each page

### PrestaShop version(s) where the bug happened

1.7.7x, 1.7.8.x

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Now input-group buttons are properly aligned and follow input height changes on all browsers
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26644 .
| How to test?      | Go to login/create account page.
| Possible impacts? | Every `class="input-group"`, but already checked all from Classic theme v.1.7.8.x

psform

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26673)

### CODE REVIEW

**Comment by SharakPL** [comment]
I think someone broke Github actions. Not me! 🤐

**Comment by NeOMakinG** [comment]
@PrestaShop/product-team is it a regression? I don't think so

If it's not a regression, it should be fixed on develop!

Overwise I don't have anything against the fix

**Comment by SharakPL** [comment]
So should I make another PR for develop branch?

**Comment by NeOMakinG** [comment]
> So should I make another PR for develop branch?

First, we need to find if it's a regression

Is this behavior present on 1.7.7 ? If yes, it's not a regression, then we need to rebase this one to develop (or make a new one if it's too hard)

**Comment by SharakPL** [comment]
I believe it's been misaligned like that through whole 1.7. So when PR fixes something like that it should be merged with develop only?

**Comment by NeOMakinG** [comment]
> I believe it's been misaligned like that through whole 1.7. So when PR fixes something like that it should be merged with develop only?

Since it's a behavior which is not a regression of the previous version, then it can be fixed inside the `develop` workflow

Patch versions are for critical bugs and regressions only

**Comment by SharakPL** [comment]
Doesn't it mean it would be fixed in 1.7.9, which afaik will never be made since P8 is getting ready? This kind of information really should be explained in contribution docs, because developing 2-3 versions at the same time is quite confusing.

**Comment by NeOMakinG** [comment]
> Doesn't it mean it would be fixed in 1.7.9, which afaik will never be made since P8 is getting ready? This kind of information really should be explained in contribution docs, because developing 2-3 versions at the same time is quite confusing.

It would be fixed inside the 8.0 release, 1.7.9 will never exist

Mmmh, I did try to find something in the doc but it looks like you're right, we may need to document it somewhere :)

**Comment by SharakPL** [comment]
> It would be fixed inside the 8.0 release, 1.7.9 will never exist
> 

Exactly the problem I had with one of my previous fixes couple years back. It's an issue with whole range so why it can't be fixed right away in 1.7.8.2? 8.0 probably won't have that problem being made with flex from the start. Should I send this PR to 1.7.7.x branch to have it fixed in 1.7.8.2? I honestly think this kind of policy is one of the reasons many devs still would rather use 1.6 than 1.7 that is filled with all kinds of issues so simple to fix and yet never fixed 😠

I won't even bother fixing other issues I reported recently since it's pointless anyway.

**Comment by eternoendless** [comment]
> his kind of information really should be explained in contribution docs

Here it is: https://devdocs.prestashop.com/8/contribute/contribution-guidelines/supported-branches/

It's a fairly recent article though, hasn't been ported to 1.7 yet but will soon.

**Review by matthieu-rolland — COMMENTED** [review]
@SharakPL, thank you for your contribution

 I just put develop as the base branch of your PR, seems like it doesn't cause any conflict

**Review by NeOMakinG — APPROVED** [review]

**Comment by marionf** [comment]
Hello @SharakPL @NeOMakinG 

The issue isn't a regression, could you rebase on develop @SharakPL ?

**Comment by SharakPL** [comment]
@marionf it's [been moved](https://github.com/PrestaShop/PrestaShop/pull/26673#pullrequestreview-811248503) already to develop and it's just couple lines of css. What's the point of rebase instead of merge here?

**Review by Progi1984 — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @SharakPL ,

Thanks for the PR ! It is QA approved ✅ !

**Comment by SharakPL** [comment]
What's up with the failed checks?

**Comment by Progi1984** [comment]
Thanks @SharakPL & @florine2623

**Pull request merged**
