### PR TITLE
Add `new-products` page in global urls smarty

### PR DESCRIPTION
**Pull request by hendaghanmi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?   | Add `new-products` page in global urls smarty   
| Type?             | improvement 
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | N/ A
| Related PRs       |  N/ A
| How to test?      | See  description Bellow 
| Possible impacts? |  N /A 

## How to test 
In tpl try this code:
```smarty 
{$urls['pages']['new_products']} 
```
and make sure that will return the  new Products page url

### CODE REVIEW

**Review by PululuK — APPROVED** [review]
Thanks @hendaghanmi !

**Review by Hlavtox — APPROVED** [review]

**Comment by hendaghanmi** [comment]
thanks @PululuK

**Review by FabienPapet — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @hendaghanmi 

Thanks for your PR. 
Could you please specify which `tpl` file we need to use? Or, if you can create a dedicate issue for this PR to can have the PM approval.

ping @PrestaShop/product-team What do you think ?

Thank You!

**Comment by PululuK** [comment]
> Hello @hendaghanmi
> 
> Thanks for your PR. Could you please specify which `tpl` file we need to use? Or, if you can create a dedicate issue for this PR to can have the PM approval.
> 
> ping @PrestaShop/product-team What do you think ?
> 
> Thank You!

Hi @HanaRebaiQA 

You can use any tpl, and no need PM validation because it is a page that has been forgotten

**Comment by Hlavtox** [comment]
Works like a charm @hendaghanmi!

**Comment by PululuK** [comment]
Thanks @Hlavtox @hendaghanmi

**Pull request merged**
