### PR TITLE
Discount display & group restriction

### PR DESCRIPTION
**Pull request by axometeam**
Display only a discount for all customers of a group, if the discount is highlighted.

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by MrManchot** [comment]
Just for information : still have the problem on Pretsashop 1.6.1.2

**Comment by xBorderie** [comment]
Thank you for your feedback @MrManchot ! 

It seems to be more of a feature request than a bug, isn't it? Or have I misunderstood your explanation?

Since this PR was made on the '1.6' branch, could you make it again on the '1.6.1.x' branch so that you get full credit once we merge it? Even better if you do it on the 'develop' branch, so that it lands in PS 1.7 :)

Finally, could you follow [these rules](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message) for your commits titles?

Thank you very much!

**Comment by xBorderie** [comment]
Thank you for closing this PR. Could you tell us why? No time to create a PR on `develop`, issue not relevant anymore, anything else? Thank you for your feedback.

**Pull request closed without merging**
