### PR TITLE
[-] FO : remove unwanted string

### PR DESCRIPTION
**Pull request by MJ-Aristote**
Remove unwanted label that appear here : SHA: 022464c578ef5158ab401a6b416d118d2900ab57
We cannot translate all this email subject to remove this unwanted word [no_sync].

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, @MJ-Aristote !

@rGaillard, that's your commit initally. Do you have an opinion on this?

**Comment by rGaillard** [comment]
@MJ-Aristote if you delete this part of the string, you will import twice the customer messages.
See https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/admin/AdminCustomerThreadsController.php#L1034

**Comment by xBorderie** [comment]
@MJ-Aristote, the only string that is being translated is this: `l('Message from contact form')`. Are you seeing "[no_sync]" anywhere in the translation?

**Comment by MJ-Aristote** [comment]
@xBorderie  No, but there is no way to delete this string from message subject. So there is no solutions to remove this string. I advice you to keep this PR (and refuse it) if someone else want to delete this string later.

**Comment by xBorderie** [comment]
I am closing this PR now.
If you want to start a conversation about this, please open a new ticket on the Forge.
Cheers!

**Pull request closed without merging**
