### PR TITLE
Add webservice order returns - issue #17753

### PR DESCRIPTION
**Pull request by Max84**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | add orders returns support to webservice
| Type?             | new feature
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Enable the webservice, you'll see a new method, called order_returns. You can use this method to see and update all returns.
| Fixed ticket?     | #17753
| Related PRs       | N/A
| Sponsor company   | Vaisonet

### CODE REVIEW

**Review by matks — DISMISSED** [review]
So as expected 😄 this did not need a lot of code.

Looks like you used tabs instead of spaces and PHP-CS-Fixer is complaining. You can use the PHP-CS-Fixer binary to automatically fix it 😉

**Comment by Max84** [comment]
Right, easy, but i forgot cs fixer, my IDE hasn't the right rules. 
I'll fix it ASAP.

**Review by boherm — APPROVED** [review]
LGTM, thanks for your contribution @Max84! 😉

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Max84** [comment]
Thanks for approval, it was a dummy PR, but it's a useful PR 😁

**Comment by paulnoelcholot** [comment]
Hello @Max84,

I tested your PR and it's OK for me :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by boherm** [comment]
Thanks for your contribution @Max84 ;)

**Pull request merged**
