### PR TITLE
Add actionLoggerLogMessage hook

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new hook `actionLoggerLogMessage`
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Related PRs       | autoupgrade: https://github.com/PrestaShop/autoupgrade/pull/552.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hello the change is valid but I'm a little afraid of performance. If I am not wrong, a call to Hook::exec will trigger one (maybe more) SQL queries.

I always heard that "logging must be a not expensive operation in software" because a single user action can trigger log writing hundred times. So I'm afraid this could slow down PrestaShop a lot :/ wdyt @kpodemski ?

**Comment by kpodemski** [comment]
@matks 

Yeah, I wouldn't say I like the fact that we need to query for modules there to see if there's a chance that they might implement something for this part of the core. On the other hand, we don't have mechanisms to listen to such events without them.

It's something that would be much easier with Symfony mechanisms :D

**Comment by matks** [comment]
> @matks
> 
> Yeah, I wouldn't say I like the fact that we need to query for modules there to see if there's a chance that they might implement something for this part of the core. On the other hand, we don't have mechanisms to listen to such events without them.
> 
> It's something that would be much easier with Symfony mechanisms :D

We could use a configuration value like PS_ALLOW_LOG_HOOK to make sure we don't do a Hook::exec for nothing... but it would a SQL query too 🤯

**Review by kpodemski — CHANGES_REQUESTED** [review]
In the end, I think we shouldn't give this responsibility to abstract class (`AbstractLoggerCore`).

I do belive that we need an improvement logger. I'd be happy to hear other @PrestaShop/prestashop-maintainers opinion.

**Comment by kpodemski** [comment]
Ping @PrestaShop/prestashop-maintainers

**Comment by FabienPapet** [comment]
I we make the Symfony container available also for the frontend, it will be easy to integrate it with Symfony :)

**Review by kpodemski — COMMENTED** [review]
Hi @PrestaEdit 

`Hook::exec` won't break the performance. I've checked this. Do you want to continue with this hook? It would require a rebase and an autoupgrade PR. Let me know.

**Comment by PrestaEdit** [comment]
Hi @kpodemski,

I Check this very soon.

**Comment by PrestaEdit** [comment]
Done.

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @PrestaEdit

**Comment by kpodemski** [comment]
Thanks @PrestaEdit 

It works, even tho I have doubled logs on the 8.1.0, but it's not your fault.

**Comment by sneko** [comment]
@PrestaEdit on the initial PR https://github.com/PrestaShop/PrestaShop/pull/28563 you were mentioning Sentry. Do you have any sample/article to configure a shop with Sentry?

According to my research:
- Either I can go with an addon on the marketplace (but $)
- Or https://github.com/eXtalionLab/prestashop-sentry/ but it's not yet packaged

If you have something else, I'm interested 👍

**Comment by PrestaEdit** [comment]
Hi @sneko,

I've made somes tests but not more datas to share right now, sorry :)

**Pull request merged**
