### PR TITLE
IN : Put GB where they should be

### PR DESCRIPTION
**Pull request by Dh42**
| Questions | Answers |
| --- | --- |
| Branch? | Develop |
| Description? | Changed GB to out of EU |
| Type? | Improvement |
| Category? | IN |
| BC breaks? | No |
| Deprecations? | No |
| Fixed ticket? |  |
| How to test? | Self Explanatory |

See Brexit vote

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by kpodemski** [comment]
Hahaha 😭

**Comment by therampagerado** [comment]
I doubt you will be happy that this will be merged no sooner than 2.5 years... :D

**Comment by Shudrum** [comment]
Seriously @vincentbz? PM approved?

Thank you for the joke, will be reopened when needed … Not before 2 years I think.

**Comment by PierreRambaud** [comment]
Still waiting :roll_eyes:

**Comment by matks** [comment]
🇬🇧

**Pull request closed without merging**
