### PR TITLE
[*] BO: improved selection of the module in "Transplant module" page

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Can you please rebase your PR ?

Best regards

**Comment by kpodemski** [comment]
it's ok now?

**Comment by kpodemski** [comment]
@jeromenadaud it's ok now?

**Comment by jeromenadaud** [comment]
Hi, yes, try to fixup or squash your commits next time :-)

Best regards.

**Pull request merged**
