### PR TITLE
Fix unit price calculation in cart, product listings and order_conf email

### LINKED ISSUE #9603: [BOOM-5836] unit price in shopping cart page not displayed correctly
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5836).

- _**Reporter:**_ TeaJay
- _**Created at:**_ Tue, 26 Jun 2018 21:46:32 +0200

<p>unit price is calculated and displayed correctly in the product page.</p>

<p>but displayed wrong in the checkout. it seems to display the product price instead of the unit price.</p>
        
* How to reproduce the issue ?

1. use a product with weight-combinations that have an impact on unit price.
<br/>
2. put it into the cart and procedd to checkout
<br/>
3. in the checkout page the unit price is identical to the product price, no matter which combination is being chosen.

### PR DESCRIPTION
**Pull request by Shoprunners**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The unit price calculation used in Product#getProductProperties and called by the product listing system, is wrong. when taking the impact from combinations, it does not calculate the base unit price correctly using the base tax_exc price but instead the already influenced price with combination impact and adding the combination unit impact on top. Furthermore, no distinction of tax mode is in place for unit price calculation at this location.<br>In the cart there is no unit price impact for combination present at all, which we've added.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9603
| How to test?  | If you want to whip out excel and calculate unit prices for a complicated product with a few combinations and such, you can see this correction take place in the listing, provided you have ps_legalcompliance enabled with the show unit price in listing feature. For the cart change, this addition is rather intuitive.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15259)

### CODE REVIEW

**Comment by Shoprunners** [comment]
This is a follow-up to the now closed #14167

**Comment by matks** [comment]
Hi @Shoprunners thanks for the contribution 😄

As pricing computations is a critical issue, we have to handle very carefully the modifications we add. This is why although the PR looks fine, we have to do extensive checks to make sure this does not change another computation usecase, maybe an exotic one.

In order to see the impact on this PR, we must use ticket #9603 scenario, is that right ?

**Comment by Shoprunners** [comment]
The scenario given in #9603 demonstrates the issue solved in the CartPresenter fix. The other issue can be observed when using ps_legalcompliance with the feature of displaying unit prices in the listing (categories) enabled. One of our shops has products with base prices of nearly zero and combinations with big impacts on both price and unit price. The listing then shows the price for presumably the default combination but a totally wrong unit price. The fix for that is in the Product class.

**Comment by matks** [comment]
@Shoprunners We need at least those 2 items for this PR to be merged:
- comply with PrettyCI lint check (https://github.com/PrestaShop/PrestaShop/pull/15259/checks?check_run_id=203149174)
- a Behat test to make sure the computation is validated and we wont break it again in the future (see example https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Behaviour/Features/Scenario/Cart/Calculation/Product/only_products.feature)

Do you feel like giving it a try, or do you prefer I do it ?

**Comment by Shoprunners** [comment]
It would probably be easier if you were to make that test since we're not familiar with writing them.

The formatting of the PrettyCI output is not really intuitive to understand, so if you could just fix the one or two issues that would be marvelous. 

Thanks in advance

**Comment by Shoprunners** [comment]
i've just discovered that this is also an issue in the order_conf email sent by PaymentModule. If you look here, the 'unit_price' is not actually calculated and instead is just using the base price... https://github.com/PrestaShop/PrestaShop/blob/develop/classes/PaymentModule.php#L431

**Comment by Shoprunners** [comment]
I've added a commit fixing the issue in the order_conf email.

**Comment by NeOMakinG** [comment]
Hello @Shoprunners, sorry for the time we took regarding you'r PR !

Could we try to speed it a bit ? It needs a rebase and a Pretty run, and then we'll review it again !

**Comment by Shoprunners** [comment]
Hi, I changed the 2 mentioned in the PrettyCI report. As I am not a pro with git and rebase etc. any help from your side to get this commit through would be great.

**Comment by PierreRambaud** [comment]
> Hi, I changed the 2 mentioned in the PrettyCI report. As I am not a pro with git and rebase etc. any help from your side to get this commit through would be great.

I rebase the PR for you, but I think you should have a check and make sure everything is ok for you :)

**Comment by Shoprunners** [comment]
> > Hi, I changed the 2 mentioned in the PrettyCI report. As I am not a pro with git and rebase etc. any help from your side to get this commit through would be great.
> 
> I rebase the PR for you, but I think you should have a check and make sure everything is ok for you :)

Hi, thanks a lot. Looking good for me.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@matks That needs an unit test

**Comment by PierreRambaud** [comment]
Hey @Shoprunners are you able to provide unit tests or integration tests?

**Comment by PierreRambaud** [comment]
Hi @Shoprunners ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
