### PR TITLE
Add replyToName parameter to Hook actionEmailSendBefore

### LINKED ISSUE #37008: Add missing `replyToName` parameter to `actionEmailSendBefore` hook
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The `actionEmailSendBefore` hook is missing the `replyToName` parameter, which is present in the `Mail::send()` method. This parameter is necessary for modules that need to modify the reply-to name of outgoing emails.

### Expected behavior

The `actionEmailSendBefore` hook should include the `replyToName` parameter along with the other email-related parameters.

### Steps to reproduce

1. Create a module that hooks into `actionEmailSendBefore`.
2. Attempt to access the `replyToName` parameter within the hook.
3. Observe that the `replyToName` parameter is not available, while other parameters like `replyTo` are present.

### PrestaShop version(s) where the bug happened

This issue affects all versions of PrestaShop up to and including the latest development versions (1.7, 8.2).

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Damien - Lord of Web

### PR DESCRIPTION
**Pull request by tups**
# Add `replyToName` parameter to `actionEmailSendBefore` hook

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR adds the missing `replyToName` parameter to the `actionEmailSendBefore` hook. This parameter is already present in the `Mail::send()` method but was not being passed to the hook, limiting the ability of modules to modify the reply-to name of outgoing emails.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Check out this branch
|                   | 2. Create a module that hooks into `actionEmailSendBefore`
|                   | 3. Add code to access and potentially modify the `replyToName` parameter
|                   | 4. Trigger an email send (e.g., order confirmation)
|                   | 5. Verify that the `replyToName` parameter is available and can be modified within the hook
| UI Tests          | https://github.com/tleon/ga.tests.ui.pr/actions/runs/11073331304 https://github.com/florine2623/testing_pr/actions/runs/11363633342 ✅ 
| Fixed issue       | Fixes https://github.com/PrestaShop/PrestaShop/issues/37008
| Related PRs       | N/A
| Sponsor company   | [Your company name, if applicable]

## Description

This pull request adds the `replyToName` parameter to the `actionEmailSendBefore` hook in the `Mail` class. The change is minimal and straightforward:

```php
Hook::exec(
    'actionEmailSendBefore',
    [
        // ... existing parameters ...
        'replyTo' => &$replyTo,
        'replyToName' => &$replyToName, // Added this line
    ],
    null,
    true
);
```

This change allows modules to access and modify the `replyToName` parameter, bringing it in line with other email-related parameters already available in the hook.

## Benefits

- Modules can now access and modify the `replyToName` parameter within the `actionEmailSendBefore` hook.
- Consistency with other email-related parameters in the hook.
- Improved flexibility for customizing email behavior.

## Possible impacts

This change should not have any negative impacts as it only adds a new parameter to an existing hook. Existing modules using this hook will continue to function as before.

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by kpodemski — APPROVED** [review]

**Review by tleon — DISMISSED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello

We recently introduced the 9.0.x branch, which will be the base for PrestaShop 9.0. If you want to see your change in this version, please rebase your PR onto 9.0.x. The `develop` will be used for PrestaShop 9.1, so you need to decide what to do.

Please rebase onto `9.0.x` or let me know your decision if you don't need to have it there so I can unblock the pull request.

**Comment by tups** [comment]
Hello @kpodemski, I have just switched branches so that it can be integrated into version 9.0.x.
Is this okay for you?

**Review by kpodemski — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
QA by dev

**Comment by kpodemski** [comment]
thanks @tups !

**Pull request merged**
