### PR TITLE
Replace specific cache management with doctrine cache for module catalog

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The generated catalog cache was stored in a file created by ourselves. But we can also use the existing doctrine cache to handle that for us. The class AdminModuleDataProvider has been cleaned of the cache management. :)
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1950
| How to test?  | This PR has no visible impact.

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Tests updated to mock now doctrine cache.

**Comment by Quetzacoalt91** [comment]
I updated the PR to use also use the Doctrine cache in the class Module Repository.
I added the localization to this class and this PR now fixes http://forge.prestashop.com/browse/BOOM-1950

**Comment by maximebiloe** [comment]
A little rebase over here, please?

**Comment by Quetzacoalt91** [comment]
Here you go :)

**Comment by aleeks** [comment]
Okiiii dokiiiiiii 
mario

**Comment by maximebiloe** [comment]
Thank you @Quetzacoalt91 🐕

**Pull request merged**
