### PR TITLE
// Classic: Remove slashed for self-closing tags

### PR DESCRIPTION
**Pull request by julienbourdeau**
We shouldn't use them with HTML5 :)

### CODE REVIEW

**Comment by kpodemski** [comment]
Source for this? Why we shouldn't?

**Comment by julienbourdeau** [comment]
I would say _"pretty much everywhere on the internet"_ ^^

They are required in xHTML but they are optional in HTML5
https://www.w3.org/TR/html-markup/syntax.html#syntax-elements

I'm not sure it makes any sense to use them, except for backward compatibility with xHTML code. Why do you want to use them ?

**Comment by kpodemski** [comment]
I'm not against this change, I only asked about this because there is also almost no problem with using them, that's it ^^ it's ok for me to not have them if they're optional

**Comment by julienbourdeau** [comment]
So nobody's against it, here we go ! 👯

**Pull request merged**
