### PR TITLE
[-] PDF : (re) added shipping box in invoice

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@kpodemski would you mind to rebase ``1.6.1.x`` branch please ? 

Otherwise :+1:

**Comment by kpodemski** [comment]
@mickaelandrieu I'm not sure I understand why I should do rebase here? :D

**Comment by mickaelandrieu** [comment]
To make build green :)

**Comment by vincentbz** [comment]
Just tested and OK, the carrier appears. Thanks :)

[invoiceWithShipping.pdf](https://github.com/PrestaShop/PrestaShop/files/145166/invoiceWithShipping.pdf)

**Comment by Shudrum** [comment]
:+1:

**Comment by kpodemski** [comment]
:ok_hand:

**Pull request merged**
