### PR TITLE
Memcached

### PR DESCRIPTION
**Pull request by drzraf**
This adds a memcached cache backend based on the newer PHP::Memcached API (not the PHP::Memcache one).
It's better:
- quicker
- not more _writeKeys hack
- more robust (the _writeKeys hack could easily timeout)
  The memcached servers add/del things are reused **but** note that data cached with memcache _may_ not function with memcached (serialization differences). If that happens, after changing settings.inc.php, run:

``` php
php -r '$m = new Memcached(); $m->addServer("127.0.0.1", 11211, true); $m->flush();'
```

Some defaults about install/upgrade may need some minors additional tweaks.

### CODE REVIEW

**Comment by jocel1** [comment]
Hi,

Could you take a look at the CacheMemcache.php version from trunk ? The need for the $this->keys init has been removed, _exists is now doing a get() and _writeKeys() is not doing anything as well.

Thanks !

**Comment by drzraf** [comment]
That's nice and a probable improvement (it should get rid of the timeout issue).
It's not a concern for the introduction of the new backend. This implementation keep the (old) idea of fetching all keys (actually only there names) into memory at connect-time to speed-up existence-test. Its easy with the PHP::memcached API and the idea is that it will avoid a couple of memcached socket I/O at the price a (light) memory usage increase (a +/- 5k keys PHP array)

What _may_ be a *concern* though is that new ```delete``` method which supports wildcard-globbing. If it a hard-requirements for backends, then the new backend could not be merged without implementing this too. 
There is no such glob-built-in in the memcached protocol. But the new API has a (deletemulti)[https://php.net/manual/en/memcached.deletemulti.php] method.
(hint that would be easier to implement for other cache backends too (eg: mysql IN () vs mysql REGEXP))

Let me know if there is anything wrong with the current code but please note that I don't intend/can't afford the time to do major rework on this for master (I main,ly work against the 1.6.0.14). Sorry for this

**Comment by drzraf** [comment]
Adding the two commit above to the branch I think that it does the work. Any plan to push this (modified or not) for the next release?

**Comment by jocel1** [comment]
Hi,

I've just created https://github.com/PrestaShop/PrestaShop/pull/3243 derived from your work.

**Comment by xBorderie** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

-xb.

**Comment by xBorderie** [comment]
Closing this PR since it was remade in #3243.
Thank you for your contribution!

**Pull request closed without merging**
