### PR TITLE
Use Header element to group content, use nav structures and styling

### PR DESCRIPTION
**Pull request by inetbiz**
I've reworked the category-miniature.tpl as well. Preparing it for nav structure. Not knowing if the project will adopt JSON+LD or stay with microdata structure. In that case, the sub-cats comprise a schema/Listitem and still maintain html outline and machine readers for the disabled.

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hi @inetbiz,

Why do you use `<ul><li>` in `category-miniature.tpl`? It's not a list, just an element.

In `category.tpl`, you have removed `<section id="main">` to replace it by `<header>`, could you leave it in place, please ? This is to keep some consistence with others templates. You should put `<header>` inside the `<section>`.

Thanks.

**Comment by inetbiz** [comment]
@maximebiloe my codeschool.com course for front-end foundations explains that the `<header>` element is used to group a presentation block. The beginning of the category page is a presentation block. In an html5 outline, it would be the parent content.

`<section>` are sub-items of the outline. I've also introduced the sub-cats as a main navigation aid. See http://html5doctor.com/the-header-element/ which confirms why I coded it the way I did. Other theme pages should follow the same pattern such as suppliers.

I have discussed product category schema with the project lead @ schema.org and a contributor from goodrelations.org A category page with nested categories and spanned products should use an itemlist. See https://github.com/schemaorg/schemaorg/issues/605

**Comment by inetbiz** [comment]
@maximebiloe sub-cats with `<ul><li>` is a item list much like breadcrumbs in schema vocabulary. And, used in nav element. The nav more describes what is on the page than a section element. IMHO

**Comment by inetbiz** [comment]
I just ran my code through https://gsnedders.html5.org/outliner/ and came out with a perfect outline.

**Comment by maximebiloe** [comment]
We agree on the fact that `<header>` is needed for the beginning of the category page, but we prefer to keep the `<section id="main">` around. Can you add it, please ?

Regarding the `<ul><li>` there is already a list surrounding the `category-miniature.tpl` include so, inside this file, it is a list item, so no need to put again a `<ul><li>`. Moreover, an url, a name and a description are not the same so it comforts us to say it's not a list.

About the `<b class="h2">` you may use a `<span class="...">` instead.

There is no style for `.products h1` because StarterTheme is not meant to stylize elements. We don't know yet if we'll provide some css with it.

**Comment by inetbiz** [comment]
@maximebiloe category.tpl is the main list item. Is there a better way to present the loop of each product such as a div container, perhaps?

Concerning the absence of a header element at the top of the page: Run https://gist.github.com/inetbiz/17bdbe9b7ac50e41f31f through https://gsnedders.html5.org/outliner/ The sample, I think , represents your desire to use nested sections with no header. It breaks.

Now add:
````
<header>
<h1>Category Content here</h1>
<p>test content</p>
</header>
````
before any section like I had done and you will have outline titles that are correct.

**Comment by maximebiloe** [comment]
Hello,

I've cherry-picked your commits and melt them into one.
Please, rebase your branch more often and don't hesitate to squash your commits.

Here is the new PR #4319

Regards.

**Pull request closed without merging**
