### PR TITLE
Update version to 1.7.5.0

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This updates the branch version to 1.7.5.0
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Install PrestaShop

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9396)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Hello @eternoendless, I'm waiting for @PierreRambaud pull request for docker e2e tests to be merged to investigate on it.

Looking at current stack trace on Travis, I guess this has nothing to do with the code you have changed but with the unavailability of translation pack in 1.7.5.

We often have this cryptic error, so I guess we should throw a meaningful exception OR (/c @rGaillard) log an error and display it and ignore the download: wdyt?

**Comment by eternoendless** [comment]
> Looking at current stack trace on Travis, I guess this has nothing to do with the code you have changed but with the unavailability of translation pack in 1.7.5.

1.7.5 translation packs should be available, I tested it twice last week.

> We often have this cryptic error (...)

If you are talking about this error:

> Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed'

It's actually caused by a failing PhpUnit test when it's running in a "separate process". Debugging that is hellish, even though it's really interesting to find out how it works internally. I think they fixed that in a later version which we can't upgrade to since it's php 7.1+ only.

**Comment by matks** [comment]
👍 for this PR as this will solve strange behaviors at install steps

**Comment by mickaelandrieu** [comment]
@matks sadly we need to figure out why tests are broken first :/

**Comment by PierreRambaud** [comment]
@mickaelandrieu Found, problem with translations, currently trying to fix it :)

**Review by PierreRambaud — APPROVED** [review]

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @eternoendless  and thanks @PierreRambaud for the sneaky fix ;)

**Comment by eternoendless** [comment]
We should have waited for QA 😱 @mickaelandrieu

**Pull request merged**
