### PR TITLE
Make Symfony form management more robust

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added new interfaces, making our own implementations more robusts.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | yes (you can't extend Performance Data provider/form handler anymore)
| Deprecations? | yes
| How to test?  | Nothing to test

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8561)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Just one question, why are these classes store in the `Core` folder (and not in PrestaShopBundle)?

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 we should keep in bundle only classes related to the integration of PrestaShop in Symfony:

* sf forms
* sf controllers
* sf commands
* sf compiler pass
* sf service declarations
* sf framework configuration
* Twig templates

If someday we want to re-use theses "Core classes" into a specific package it will be easier to do it.

If I could do it, I'd move the `Translation` folder into `Core`, but it's too late... (and it's my fault ;) )

**Comment by Quetzacoalt91** [comment]
I heard the `Core` was supposed to disappear. :thinking:

**Comment by mickaelandrieu** [comment]
> I heard the Core was supposed to disappear. :thinking:

Nope, it's `Adapter` namespace that will be removed when the migration will be done, for now we keep the class that depends both on legacy and modern sides in Adapter namespace :+1:.

We should write the migration strategy somewhere, and I now exactly where ^o^ 

=> Can you merge it please ? :)

**Comment by kpodemski** [comment]
I think that we all can agree that Core/Adapter/PrestaShopBundle is messy right now, some stuff in Adapter shouldn't be there, for example stuff related to products listing is in both places at the same time which is not good

**Comment by mickaelandrieu** [comment]
ping? could be nice to merge it, we are talking about adding only 1 interface "FormDataProviderInterface".

**Review by Quetzacoalt91 — APPROVED** [review]

**Pull request merged**
