### PR TITLE
Tools::urlBelongsToShop should work with HTTP host header

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | see title
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | partly #24624
| How to test?      | CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24626)

### CODE REVIEW

**Comment by mvorisek** [comment]
@PierreRambaud please review

**Review by matks — COMMENTED** [review]
Hello @mvorisek the code seems OK for me 👍  however to fully validate it I would need some usecase I can work with.

Do you have an example of usecase, something I can reproduce, where
```
return empty($urlHost) || $urlHost === Tools::getServerName()
```
is failing while
```
return empty($urlHost) || $urlHost === Tools::getServerName() || $urlHost === Tools::getHttpHost();
```
provides the expected behavior?

I need something a little bit more accurate than `$_SERVER['SERVER_NAME'] should be not used` 😅  something with a clear server configuration I can setup

**Comment by mvorisek** [comment]
@matks set `SERVER_NAME` to `localhost` and see, that this function returns wrongly `false` then, if you can not get this, close as you know at least how this is can be done :D

**Comment by mvorisek** [comment]
@matks please see related PR which confirms the functionality

**Comment by matks** [comment]
This PR has high ROI in my opinion so I will bring it to merge stage myself following [the guidelines written here](https://github.com/PrestaShop/PrestaShop/pull/23979#issuecomment-906376989).

EDIT: I cannot find an accurate scenario and setup that is solved by this PR, see [my analysis](https://github.com/PrestaShop/PrestaShop/issues/24624#issuecomment-907449534)

**Comment by matks** [comment]
As I cannot find an accurate scenario and setup that is solved by this PR, I close it.

I am willing to reopen if someone can provide the relevant informations I need to create a situation where I can see the current state of the code fail, and the state suggested in PR would be successfull.

Thank you for your contribution.

**Pull request closed without merging**
