### PR TITLE
Fix translations theme export on Windows

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Fix translations theme export on Windows
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Just try to export theme translations on Windows

### CODE REVIEW

**Comment by kpodemski** [comment]
@maximebiloe hey Maxime, does anyone of you tried to upload theme or translations exported on Windows? For me it's still not working

**Comment by maximebiloe** [comment]
@kpodemski I didn't test it personally. Is there an error? Or it just simply doesn't work?

**Comment by kpodemski** [comment]
@maximebiloe theme package is invalid, flat structure exported to cache directory

**Comment by vincentbz** [comment]
Hi guys,

When I export a language on Windows, I have this. Is it the wanted result ?

image

**Comment by maximebiloe** [comment]
Yes that's what we want 😉

**Comment by vincentbz** [comment]
Thanks ! Krystian is it good for you too ?

**Comment by maximebiloe** [comment]
It also needs the following PR to export the right domains on Windows: https://github.com/PrestaShop/TranslationToolsBundle/pull/31

**Comment by aleeks** [comment]
Thank you @maximebiloe

**Pull request merged**
