### PR TITLE
Fix accessing disabled product, further refacto of controller

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below
| Type?             | refacto
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | -
| How to test?      | See below
| Possible impacts? | -

### I messed up a tiny bit in my previous PR
- When doing https://github.com/PrestaShop/PrestaShop/pull/29435 I made a mistake and there is a issue when you access a disabled products, I didn't realize moving the template assignment to the end made it permanent. :-)

### So this is half improvement/half bugfix. What I changed:
1. `$this->setTemplate('catalog/product', [` must be above check functions, so they can override the basic template if error is to be shown. So, I fixed that and moved it back above the 'check' functions.
2. Unified `setPreviewMode` to automatically account for admin token. There is no need to have this separate. If admin is previewing, he needs token anyway. There is no preview without token, token is useless without preview.
3. I further refactored checkPermissionsToViewProduct to make it more readable and prepare it for https://github.com/PrestaShop/PrestaShop/pull/29720.

### How to test
- Create product, keep redirection settings to default 404. Keep admin open.
- Visit this product in FO. Keep the tab open.
- Go to admin tab, disable it.
- Go back to the product on shop, hit F5, see weird page I caused. With this PR you will see 404 page again properly.

### CODE REVIEW

**Comment by Hlavtox** [comment]
@kpodemski @matks Made an oopsie in the last PR, check this please 😄

**Comment by kpodemski** [comment]
Hi @Hlavtox 

I think it would be great to discuss with @PrestaShop/qa-team to create a functional test checking behavior you described.

**Comment by Hlavtox** [comment]
@kpodemski I want to add a possibility to display this page in my other PR, so we can discuss it after maybe? Because the behavior will change. I would like this to be merged to fix it for now.

**Review by zuk3975 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
QA: I know there's no issue, but Daniel explained the situation 👍

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

Thanks for your PR. The "issue" is well fixed and I found no regression. 

https://watch.screencastify.com/v/4saZtqN402fqsum1wO6n

**Review by paulnoelcholot — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @Hlavtox and @paulnoelcholot

**Pull request merged**
