### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Remove deprecated & unused code
| Type?             | improvement
| Category?         | TE 
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Hi,

If I'm not wrong, the branch need to be develop and there are BC breaks there.

**Review by mflasquin — COMMENTED** [review]
Can we consider this PR as a BC break because of deletion of ModuleRepository.php even if this class is deprecated since PS 1.7.8 ?

**Comment by FabienPapet** [comment]
I think this a not a BC break as targeted branch is 8.0 and we allow bc breaks here. Also, it was alraedy deprecated.

**Comment by kpodemski** [comment]
There's code freeze for 8.0 already. This change can be accepted for 9.0 when the time comes.

**Comment by FabienPapet** [comment]
That's sad but I understand, putting it to 9.0

**Review by nicosomb — DISMISSED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
As mentioned by others, today our rules state that once code freeze has happened on a branch, only bugfixes are merged inside this branch until release.

Code freeze for 8.0.0 happened on 2022-06-09.

This rule was created to prevent any PR that does not aim to bring stability to be merged because each PR added inside a version brings a little risk of adding a major blocking bug.

**Pull request closed without merging**
