### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by neoteknic**
Stop use of obsolete apache version, use 2.4 directive

### CODE REVIEW

**Comment by aleeks** [comment]
ping @rGaillard

**Comment by rGaillard** [comment]
@neoteknic Thank you for your PR, maybe we can support the both version at once. Several hostings are still on Apache 2.2

**Comment by xBorderie** [comment]
If anything, 2.2 even seems to be more popular than 2.4: https://w3techs.com/technologies/details/ws-apache/2/all

**Comment by aleeks** [comment]
Hello all of you.
Thank you for your comment @xBorderie, so i'm closing this PR.
I think, we need to support many people as possible
Regards

**Pull request closed without merging**
