### PR TITLE
Fix: PHP 8.3 deprecation warnings

### LINKED ISSUE #36837: PHP 8.3 deprecation warnings
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are some deprecations in PrestaShop 9 on PHP 8.3.

### Expected behavior

No deprecations.

### Steps to reproduce

Place an order, during the process with profiler and debug mode enabled you will see this error:

```

Deprecated: Creation of dynamic property Address::$back is deprecated in /Users/kpodemski/code/prestashop9/classes/form/CustomerAddressForm.php on line 159

Deprecated: Creation of dynamic property Address::$token is deprecated in /Users/kpodemski/code/prestashop9/classes/form/CustomerAddressForm.php on line 159
```

### PrestaShop version(s) where the bug happened

9.0

### PHP version(s) where the bug happened

8.3

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There are some deprecations in PrestaShop 9 on PHP 8.3.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed issue or discussion?     | Fixes #36837
How to test? | Create a cart with one or more items without being logged in. During checkout, enter the details to create a new account. Then, enter the address information. At this point, you should no longer see the error. 
| UI Tests | https://github.com/florine2623/testing_pr/actions/runs/10832810747
| Sponsor company   | @Codencode

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by tleon — APPROVED** [review]

**Comment by tleon** [comment]
Could you run the UI tests on this PR and add an how to test in the PR description ?

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Codencode ,

Thanks for the PR.

The error mentioned is not displayed anymore with PHP 8.3.

Tested the standard case :

https://github.com/user-attachments/assets/47f6b023-82d8-4505-968f-41597b8f0a53

Tested the case where the address is edited, deleted, a new one is created, used another address for invoice.

Works as expected. It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
thank you @Codencode @florine2623

**Comment by Codencode** [comment]
Thank you @kpodemski!
Happy to contribute!

**Pull request merged**
