### PR TITLE
Add missing translation domains in AdminController

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Apply codereview from #28145 to AdminController. I added translation domains for each string that is already in a domain. I did not touch texts that are exclusively in `messages.xlf`.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | None
| Related PRs       | #28145
| How to test?      | There is no change in behavior
| Possible impacts? | None.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28171)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I believe this change doesn't require any QA as it's only about adding domains to translations, refacto.

**Comment by Progi1984** [comment]
@kpodemski Please ask to @PrestaShop/qa-functional before merging without QA. They are our guardians of the quality of PrestaShop.

**Comment by kpodemski** [comment]
@Progi1984 

If I'm not mistaken, not everything requires QA attention. This PR seems to match the criteria.

Can we clarify this once and for all @matks ? :>

**Comment by boubkerbribri** [comment]
> @Progi1984
> 
> If I'm not mistaken, not everything requires QA attention. This PR seems to match the criteria.
> 
> Can we clarify this once and for all @matks ? :>

Yeah, but i think when the changes are on `AdminController`, we should pass it to QA (to check if there is side effects). And I think some things are missing on the BO (to be verified).

**Comment by Progi1984** [comment]
It seems that this untested and merged PR has broken automated tests : https://nightly.prestashop.com/report/3789

**Comment by Robin-Fischer-PS** [comment]
@kpodemski Even if not everything requires QA, the good practice is to ping and ask to QA if it can be merged without tests. We will answer quickly, don't worry :D

And as @Progi1984 and @boubkerbribri said, it seems there is some bugs introduced by this PR.

But indeed you're right, we need to clarify this, and we will : We should have a meeting on this subject very soon :)

**Comment by kpodemski** [comment]
Ok then, in that case, it's safe to say that everything should be consulted, without exceptions, as this change seems to be completely secure, apart from the `===` that probably might do some bad 🤔 

Thanks for your input, and I'm very sorry for the problem. Thankfully we do have those automated tests ❤️

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional 

Fix: https://github.com/PrestaShop/PrestaShop/pull/28185

Sorry again 😞

**Comment by matks** [comment]
Mistakes happen. What's important about a mistake is to focus on what we learn from it, and become better, not on the mistake itself.

Because I'm sure we're going to do a lot more mistakes in the next years 😄 all of us

**Comment by Robin-Fischer-PS** [comment]
Hey @kpodemski , don't worry, as @matks said, mistakes happen ! The QA still loves you :stuck_out_tongue:

**Comment by lmeyer1** [comment]
@kpodemski Thank you for your fix!

**Comment by anjohnb** [comment]
Thank you

**Pull request merged**
