### PR TITLE
FO: off-canvas mobile menu

### PR DESCRIPTION
**Pull request by rdy4ever**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR converts the mobile main menu into an off-canvas menu. Redesigned for usability, Language/Currency selectors are now on the top of the menu left/right. Adds a "big" X button for closing the menu, hides hamburger icon when menu is open. Prevents body from accidental scrolling by fixed positioning it and hiding overflow while the menu is open, but keeps the menu scrollable. Minimal javascript code just adds and removes a css class from related elements, while removing the previous chunk of code that operated the mobile menu. The menu uses CSS animations for best performance. Moved the menu template code into a separate partial .tpl file in order to be able to keep it off-canvas (separate it from the `main`). Small fixes to the navbar: the logo now displayed as inline-flex in order for correct vertical alignment; cart icon has the same color as the rest of the nav links when inactive; adjusted the searchbar magnifying glass icon position in order to be properly aligned vertically.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Related to #9909 - requesting an off-canvas menu
| How to test?  | 
image
See it in action: https://imgur.com/a/yNEIUl7

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10574)

### CODE REVIEW

**Comment by colinegin** [comment]
@TristanLDD what do you think of this improvement suggestion ?

**Comment by rdy4ever** [comment]
If you guys don't like it in this dark theme, I could redesign it in a light flavour. Just let me know :)

**Comment by BilalDr** [comment]
Hi @rdy4ever ,
thanks a lot for your contribution !
If you have time you can also check this module of menu which needs some improvement on mobile : 
[Smart menu ](https://github.com/PrestaShop/seoprestamenu )

**Comment by TristanLDD** [comment]
Hi @rdy4ever

Thank you a lot for your suggestion, we already did the work on that mobile menu so I don't believe we will implement your PR as it is, however we will consider improving our menu with some of your features like the CSS animation and overflow hiding. Thank you again for your work.

**Comment by rdy4ever** [comment]
Ok, no problem.

**Pull request closed without merging**
