### PR TITLE
Fix: PPV2 - Specific prices can't be created for a particular combination

### LINKED ISSUE #34229: PPV2 - Specific prices can't be created for a particular combination
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PS 8.1.2, I want to create a specific price for a combination in particular. But all the combinations are not displayed; also I can't search for the said combination, there's no search field.

https://github.com/PrestaShop/PrestaShop/assets/16019289/ff58766f-d6dc-4717-9187-d4ec29886ccf

Might be related to https://github.com/PrestaShop/PrestaShop/issues/34203

### Expected behavior

All my combination should be displayed. Or I should have a search input field.

### Steps to reproduce

1. Go to BO > Create a combination product
2. Generate more than 20 combinations
3. Go to Pricing > Specific price block > Add a specific price
4. See in "All combinations" : only 10 combinations are displayed :x:
5. There's no search field to find another combination that is not already displayed in the dropdown :x:

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | In PS 8.1.2, I want to create a specific price for a combination in particular. But all the combinations are not displayed; also I can't search for the said combination, there's no search field.
| Type?             | bug fix
| Category?         | BO
| Fixed issue or discussion?     | Fixes #34229

### CODE REVIEW

**Comment by ChillCode** [comment]
Hi

That method is a bit strange to me, but surely have sense to others, but I guess you found a second bug and the solution.

When you add the DISTINCT and remove `pac.id_attribute` you can also remove the constraint and will work as expected without the array_slice thing:

```
->andWhere($qb->expr()->in('pac.id_attribute', ':attributes'))
->setParameter('attributes', $attributeIds, Connection::PARAM_INT_ARRAY)
```

Didn't realize we were getting duplicates using this method and that's why I only have 10 instead of 20 combinations listed, never counted them till now.

Nice catch.

[EDITED]

That function has to be reviewed, I also removed the attributeids thing and will see how it goes.

**Comment by Codencode** [comment]
> Hi
> 
> That method is a bit strange to me, but surely have sense to others, but I guess you found a second bug and the solution.
> 
> When you add the DISTINCT and remove `pac.id_attribute` you can also remove the constraint and will work as expected without the array_slice thing:
> 
> ```
> ->andWhere($qb->expr()->in('pac.id_attribute', ':attributes'))
> ->setParameter('attributes', $attributeIds, Connection::PARAM_INT_ARRAY)
> ```
> 
> Didn't realize we were getting duplicates using this method and that's why I only have 10 instead of 20 combinations listed, never counted them till now.
> 
> Nice catch.
> 
> [EDITED]
> 
> That function has to be reviewed, I also removed the attributeids thing and will see how it goes.

Hi,

yes, the problem is due to duplicates of the "id_product_attribute" field.

Removing 

`$qb->setMaxResults($limit); `

I get all the results, so array_slice I have to predict it to be able to return only the first N results.

**Comment by ChillCode** [comment]
Yes, the duplicates are because in my case products have two attributes (Color & Size) and will get twice the combination_id since both attributes belong to it.

Also when the next function applies the array_unique the result will always be 10 and that's why the search field doesn't appear.

Removing the attributesids I know we lose the search thing so your solution is the best one. without refactoring or creating a new method

**Comment by Codencode** [comment]
> andWhere($qb->expr()->in('pac.id_attribute', ':attributes')

So would you do this?

```        
        if ($shopConstraint->getShopGroupId()) {
            throw new InvalidShopConstraintException('Group shop constraint is not supported');
        }

        $qb = $this->connection->createQueryBuilder()
            ->select('DISTINCT pac.id_product_attribute')
            ->from($this->dbPrefix . 'product_attribute_combination', 'pac')
        ;

        if ($shopConstraint->forAllShops()) {
            $qb->innerJoin(
                'pac',
                $this->dbPrefix . 'product_attribute',
                'pa',
                'pac.id_product_attribute = pa.id_product_attribute'
            );
        } else {
            $qb->innerJoin(
                'pac',
                $this->dbPrefix . 'product_attribute_shop',
                'pa',
                'pac.id_product_attribute = pa.id_product_attribute AND pa.id_shop = :shopId'
            )->setParameter('shopId', $shopConstraint->getShopId()->getValue());
        }

        $qb
            ->where('pa.id_product = :productId')
            ->setParameter('productId', $productId->getValue())
        ;

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        $results = $qb->execute()->fetchAll();
        if (!$results) {
            return [];
        }

        return array_map(static function (array $result): CombinationId {
            return new CombinationId((int) $result['id_product_attribute']);
        }, $results);
```

would you also remove $languageId from the method parameters?

**Comment by ChillCode** [comment]
At first I did, but doing it we lose the search constraint, just was testing, wait till some PS contributor opinion, I'm not, 
but I left it like this and increased the limit to 40:

```

        if ($shopConstraint->getShopGroupId()) {
            throw new InvalidShopConstraintException('Group shop constraint is not supported');
        }

        $attributeIds = $this->searchAttributes($languageId, $shopConstraint, $searchPhrase);

        if (empty($attributeIds)) {
            return [];
        }

        $qb = $this->connection->createQueryBuilder()
            ->select('DISTINCT pac.id_product_attribute')
            ->from($this->dbPrefix . 'product_attribute_combination', 'pac')
        ;

        if ($shopConstraint->forAllShops()) {
            $qb->innerJoin(
                'pac',
                $this->dbPrefix . 'product_attribute',
                'pa',
                'pac.id_product_attribute = pa.id_product_attribute'
            );
        } else {
            $qb->innerJoin(
                'pac',
                $this->dbPrefix . 'product_attribute_shop',
                'pa',
                'pac.id_product_attribute = pa.id_product_attribute AND pa.id_shop = :shopId'
            )->setParameter('shopId', $shopConstraint->getShopId()->getValue());
        }

        $qb
            ->where('pa.id_product = :productId')
            ->andWhere($qb->expr()->in('pac.id_attribute', ':attributes'))
            ->setParameter('attributes', $attributeIds, Connection::PARAM_INT_ARRAY)
            ->setParameter('productId', $productId->getValue())
        ;

        if ($limit) {
            $qb->setMaxResults($limit);
        }

        $results = $qb->execute()->fetchAll();
        if (!$results) {
            return [];
        }

        return array_map(static function (array $result): CombinationId {
            return new CombinationId((int) $result['id_product_attribute']);
        }, $results);
```

I usually load 10 prices per combination (10, 25, 50, 75, 100, 150, 200, 250, 400, 500) so my customers don't really use that but  is a nightmare to search when you have 100 combinations using the word White and there are no mask on this search...

So the only real solution I think is to implement pagination using `'@PrestaShop/Admin/Common/javascript_pagination.html.twig'`? as mentioned before.

**Pull request closed without merging**
