### PR TITLE
Make FormattedTextAreaType works with TranslatableType

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Make FormattedTextAreaType works with TranslatableType. The reason being so we have only one type for translatbleTypes instead of multiple like we have now
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 1) Make sure that translatable fields didn't get affected in non-simplified-pages(Categories page). 2) Test that Translatable formatted text area type fully works in module Demo Symfony Form   in https://github.com/PrestaShop/example-modules repository. But only with this PR https://github.com/PrestaShop/example-modules/pull/29 PR is merged.  

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21115)

### CODE REVIEW

**Comment by matks** [comment]
⚠️ Our Twig linter is complaining
```
OR  in src/PrestaShopBundle/Resources/views/Admin/TwigTemplateForm/prestashop_ui_kit_base.html.twig (line 733)
      731          {% endif %}
      732        </div>
  >>  733      {% endif %}
  >> Unexpected "endif" tag (expecting closing tag for the "block" tag defined near line 700). 
      734      {{ block('form_help') }}
      735    {%- endblock translatable_widget %}
                                                                                
 [WARNING] 460 Twig files have valid syntax and 1 contain errors.                                                                                         
```

**Comment by JevgenijVisockij** [comment]
This can be reviewed but currently has 2 other PR that need to be merged before Q&A.

**Review by jolelievre — DISMISSED** [review]
Can't wait to see this one merged ^^

**Comment by Progi1984** [comment]
@JevgenijVisockij Always in WIP ?

**Review by NeOMakinG — DISMISSED** [review]
lgtm

**Review by PierreRambaud — DISMISSED** [review]

**Comment by JevgenijVisockij** [comment]
> @JevgenijVisockij Always in WIP ?

Hey, in my opinion this PR working correctly and not affecting anything it shouldn't means that
1) Other subtypes(text, text area) for TranslatableType still work as intended in non-simplified forms
2) Old way of adding formattable text area still works as intended
3) Other subtypes(text, text area) for TranslatableType still work as intended in simplified forms 
4) FormatableTextArea works with TranslatableType

Points 1 and 2 are testable, but in order for point 3 to be testable by Q&A we need at least one simplified form with TranslatableType (for example https://github.com/PrestaShop/PrestaShop/pull/19995). 4 point can be tested by example module in this case it would be great to merge this PR (https://github.com/PrestaShop/example-modules/pull/29) but it's not required. 

So I think it makes sense to remove WIP only once we have at least one simplified form with TranslatableType in develop.

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1JJSS2KCRxloGxOFxV3v3wu-Mz3ZexMwo/view?usp=sharing

Thanks!

**Comment by matks** [comment]
Thank you @JevgenijVisockij

**Pull request merged**
