### PR TITLE
Fix an unclear alert

### LINKED ISSUE #26833: FO -  Your account  - Add/Edit Addresses - unclear alert when we have invalid address
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the FO > Your account > Add/update address => when have an address with invalid data in the `address` field => unclear error
image

In the PS1778, we have
image

### Expected behavior

_No response_

### Steps to reproduce

1. Go to FO > Sign in and try to add a new address
2. In the address field, add invalid data for example `address_`
3. Click on Save

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1, 1.7.8.2build1

### PHP version(s) where the bug happened

7.2, 7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by rsoulard-prolaser**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Unclear alert when we have invalid address
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26833.
| How to test?      | Go to FO > Sign in and try to add a new address. In the address field, add invalid data for example `address_`. Click on Save. See error
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27376)

### CODE REVIEW

**Comment by saulaski** [comment]
The bug fix does the job: validations should be skipped if no value is provided in the field.
Thank you @rsoulard-prolaser 

The code around is overly complex and redundant. No surprise it fosters such bugs.

**Review by saulaski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello,

PR is tested and the error is fixed 

https://watch.screencastify.com/v/0tvr3e2SMP1GhuGs9LKJ

Thank you @rsoulard-prolaser  !

**Review by Progi1984 — CHANGES_REQUESTED** [review]
WAIT FOR 1783 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @rsoulard-prolaser & @marwachelly

**Pull request merged**
