### PR TITLE
Improve query performance in order status update due very slow StockManager.php queries

### PR DESCRIPTION
**Pull request by gennaris**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | query optimization to fix poor performance as described in issue #14703
| Type?         |  improvement 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes part of #14703 
| How to test?  | [In this comment](#issuecomment-535493365)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15707)

### CODE REVIEW

**Comment by Progi1984** [comment]
@gennaris Thank you for your contribution. It's a very interesting PR. Could you give us a test case ?  Thanks

**Comment by gennaris** [comment]
@Progi1984 you'll need a shop with a very large **ps_stock_available** table to reproduce (my customer shop where problem occured have 900k+ rows). 

Test case is pretty simple :
- Run an huge shop (100k+ products with variations // 900k rows in ps_stock_available table)
- Make a frontend order and check SQL queries with profiler during ValidateOrder call.

Also you can refer to my explanation in #14703 :
**updatePhysicalProductQuantity** method is called from **ValidateOrder** and performs an update on ALL **ps_stock_available** table rows when it should only need to update physical quantities of the order involved products ((unless I am missing some logic in the core (?) )). 

This PR was helpful to reduce order validation time of about 12 seconds in my customer shop.

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello,

The QA need the shop creator for testing this PR. Since the shop creator isn't working, the PR shouldn't be in waiting for QA until it fixed.

Thank you

**Comment by matks** [comment]
> Hello,
> 
> The QA need the shop creator for testing this PR. Since the shop creator isn't working, the PR shouldn't be in waiting for QA until it fixed.
> 
> Thank you

Can you tell us what is wrong on https://github.com/PrestaShop/prestashop-shop-creator ? 😃

**Comment by sarahdib** [comment]
@matks when we use the data generated by the shop creator the installation is blocked at 91%

**Comment by PierreRambaud** [comment]
@sarahdib @matks Since this PR has no problem, we must keep the `Waiting for QA` label.

**Comment by Progi1984** [comment]
Thanks @gennaris

**Comment by ComonSoft** [comment]
Hi, I tested with PS 1.7.6.5 the proposed fixed is already in, but we still have this issue.
We have 38 500 products / variations (most of them are variations). The updateReservedProductQuantity() method takes about 15 seconds per article ! No chance we have many articles in common cart, you can image the time it takes. 
Is any fix availaible, we loose customers, lot of orders are in timeout and in error, or several payements...

**Comment by serracol** [comment]
Dear community, any updates on this issue? This is really affecting our business and its forcing us to explore other eCommerce alternatives.
We have over 20.000 products and the checkout process takes about 35 seconds, and this is really not an option.

Please any ideas? Im worried that this has be arround since 2019...

**Comment by kpodemski** [comment]
Hello @serracol 

This PR has been merged and is available from PrestaShop 1.7.7

**Comment by stickyrst** [comment]
Prestashop 1.7.7.8, this issue still persists. updateReservedProductQuantity and updatePhysicalProductQuantity is very slow.

**Pull request merged**
