### PR TITLE
Remove smarty caching_type

### LINKED ISSUE #29160: Delete the feature cache smarty MySQL
**Description of the pb**
We need to remove the feature 'Caching type' - MySQL because it is unsafe and provides lower performance compared to file system cache.

**Solution**
 Delete the feature 'Caching type' -> MySQL in Advanced parameter > Performance.
 
 **Acceptance test**
 The feature is not displayed anymore in the selector and the code related is removed

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | Removes caching type from configuration
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes 
| Deprecations?     |  no
| Fixed ticket?     | Fixes #29160.
| How to test?      | Check configuration is gone on advanced setting > performance page.

### CODE REVIEW

**Comment by ghost** [comment]
Good news, why not add a SQL query to remove the configuration line in autoupgrade module when this PR is merged.
Let's take advantage of the BC break allowed with the 8.0.0

**Review by ghost — DISMISSED** [review]

**Comment by atomiix** [comment]
@okom3pom we're adding an extra layer of security in the next patch (1.7.8.8) that will move the `PS_SMARTY_CACHING_TYPE ` configuration from DB to the `config/defines.inc.php` file (as it's done with `_PS_MODE_DEV_`), and we'll make the SQL script to delete the configuration entry for that version at the same time ;)

**Review by atomiix — DISMISSED** [review]

**Review by PrestaEdit — CHANGES_REQUESTED** [review]
There is a `$configuration['caching_type'],`line into `validateConfiguration()` method.

**Comment by PrestaEdit** [comment]
> There is a `$configuration['caching_type'],`line into `validateConfiguration()` method.

Due to this, you can't enable the cache as the validation fail.
Does not hesitate to make some tests before proposing Pull Request as this.

Not working as now.

**Comment by ghost** [comment]
Nice catch @PrestaEdit

**Review by PrestaEdit — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by marsaldev — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @FabienPapet 

Thank you for your PR, I tested it and it works, as we can see here :
image

As expected we haven't the possibility to pass in MySql but we have what we do, register in `smarty_lazy_cache` as we can see in this video : 

https://user-images.githubusercontent.com/100699445/181050301-12257c56-20c2-486b-a1b5-3f6413e34a45.mp4

I don't know if it's an intended behaviour or not. If it is, I'll approved this PR, 

Waiting for your feedback

**Comment by kpodemski** [comment]
@FabienPapet make sure to open a new PR on `autoupgrade` module to delete the configuration from the database, and the database table for this cache

**Comment by ghost** [comment]
@kpodemski  already done https://github.com/PrestaShop/autoupgrade/pull/495 and for the table it's here : https://github.com/PrestaShop/autoupgrade/commit/a52214e4afc10e0263828467af88293f1b8b6e23

**Comment by ghost** [comment]
@AureRita yes it's the behaviour, but you have to check if the `ps_smarty_cache` table is empty but normaly it is.

**Review by AureRita — APPROVED** [review]
Hi @okom3pom 

Thank for this answer. Yes the `smarty cache` still be empty

**Pull request merged**
