### PR TITLE
Fixed call for Windows PrestaShop Components

### LINKED ISSUE #20931: BO - Category page - Friendly URL not automatically updated
#### Describe the bug

In the BO => Categories page => when we try to add a new category, the friendly URL is not automatically updated when we set the category's name.

#### Expected behavior

When we set the category's name, friendly URL must be automatically updated as before

#### Steps to Reproduce

1. Go to BO > Catalog > Categories page
2. Add a new category
3. Set a name
4. Save
4. See error "Friendly URL" is empty
image

#### Additional information

* PrestaShop version: develop(178)
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed call for Windows PrestaShop Components
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20931
| How to test?  | Cf. #20931 

Ping @boubkerbribri 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21277)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
I'm surprised we didn't see it earlier ^^

**Comment by Progi1984** [comment]
(@jolelievre The issue has been created 22 days ago).

**Comment by jolelievre** [comment]
@Progi1984 yes but I meant the missing uppercase during the review

**Comment by Progi1984** [comment]
And I think it's not logical but @NeOMakinG Will check in v2

**Comment by boubkerbribri** [comment]
It's good for me, Thanks @Progi1984

**Pull request merged**
