### PR TITLE
Removed deprecated support of translation for ObjectModel field using fields.php

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed deprecated support of translation for ObjectModel field using fields.php
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4407116734
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks
* Removed method `displayFieldName` in class `ObjectModel`

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by PrestaEdit — COMMENTED** [review]
The global and the method is still needed ? I'm not able to check, just as a remember ask.

**Comment by Progi1984** [comment]
@eternoendless You, who have a big experience with translations, do you think we can remove all usages of `$_FIELDS` ?

**Comment by eternoendless** [comment]
I'm actually discovering this part. From what it seems, this method is used to translate the name of an object model field when showing error messages like "The field %s is required". 

From the looks of it, it currently relies on a `$_FIELDS` array containing translations. However, this array is never initialized, it belonged to [1.6 translation files](https://github.com/PrestaShop/TranslationFiles/blob/master/1.6/fr/translations/fr/fields.php) that no longer exist since 1.7.0. So basically it doesn't work anymore, and it has been broken for years.

We could easily argue that it's not the role of ObjectModel to know how to translate field names, it's the controller's job to do it. So to me, this whole method should be completely removed, and its uses refactored.

**Review by kpodemski — CHANGES_REQUESTED** [review]
After @eternoendless comment, I realized that it's probably too risky to merge this without/before this part:

> We could easily argue that it's not the role of ObjectModel to know how to translate field names, it's the controller's job to do it. So to me, this whole method should be completely removed, **and its uses refactored**.

**Review by kpodemski — DISMISSED** [review]

**Comment by Progi1984** [comment]
@kpodemski I can do it the same PR ;)

**Review by matthieu-rolland — COMMENTED** [review]
Should this PR remain a draft ?

**Comment by Progi1984** [comment]
@kpodemski @matthieu-rolland @eternoendless @PrestaEdit @FabienPapet The PR is now ready to review. (All CI & Nightly are :green_circle:).

**Review by PrestaEdit — APPROVED** [review]

**Comment by eternoendless** [comment]
How will this affect validation errors in forms made with HelperForm?

**Comment by Progi1984** [comment]
@eternoendless That doesn't change anything : 

Rendering on `develop` or with this branch.
image

That used this change : 
image

Rendering on `develop` or with this branch.
image

That used this change in `ObjectModel`: 
image

**Comment by eternoendless** [comment]
So basically the whole thing is messed up. IMO if the error message system is kept, we should keep a way to match the field to a field name, at least the very least in one language! (eg. "public_name" -> "Public name"). 

Otherwise it's just broken.

**Comment by Progi1984** [comment]
@eternoendless I clean a deprecated and non used usage.

I check in 1.7.8.8. It was the same behavior.

image

In check in 1.6.1.24. It was the same behavior.
image

You ask an improvement : could you create an issue ?

**Comment by eternoendless** [comment]
This is not an improvement but a bug

**Comment by Progi1984** [comment]
Ok, sorry for the bad word.

In this case, this PR is a partial fix for this bug.

**Comment by eternoendless** [comment]
No this is partially removing a feature that doesn't work properly and that was deprecated without looking to fix it ;)

**Comment by Progi1984** [comment]
@eternoendless Have you an existing issue ? I don't find any issues.

**Comment by eternoendless** [comment]
ping @MatShir I think we should find a way to fix the error messages

**Review by MatShir — CHANGES_REQUESTED** [review]
With no alternative to make error messages work properly in legacy pages and modules that use this system. I don't think that removing this deprecated code brings more inconvenience than benefit.
The PR is blocked, waiting for the alternative that we could prioritize in parallel to this PR

**Comment by PrestaEdit** [comment]
Just to know, why it's one man that decide to keep this weird code (aka GLOBALS) and there is no issue or specs writed somewhere ?

**Comment by MatShir** [comment]
Anyone on the orga can veto a PR, tech or pms maintainers or commiters. I'm raising an issue, from the feedback from my collaborators and from what I'm reading. Blocking the PR temporally allows us to discuss the topic and not rushing the review & qa. If the concerns are addressed, specify or acknowledged somewhere, perfect then. If not, we have to do it.

**Comment by PrestaEdit** [comment]
Never read that, on the code of conduct of role organizations, but... okay.

**Comment by Progi1984** [comment]
@MatShir I don't understand. I remove unused code since version 1.5 (at least).

We discover an issue... which is not a regression, which is not linked to this.

Why not create an issue, merge this PR and fix the issue in an another PR ?

**Comment by eternoendless** [comment]
> We discover an issue... which is not a regression, which is not linked to this.

It is a regression from 1.7.0 from what I can tell (although it might be broken from before). Yes it is linked to this because the code you're removing governs the translation of field names in error messages. The code isn't working, most likely because the translations are missing, not because the code is useless!

> Why not create an issue, merge this PR and fix the issue in an another PR ?

Because without this PR it should be possible to work around the issue, but after this PR it won't be anymore.

Again, we should focus on fixing the error messages and THEN remove any remaining part of the code that remains useless after. The non-existance of a Github issue doesn't mean that the bug is not there, as you have shown in your screenshots.

Alternatively, we could remove all uses of validation error messages in ObjectModel and move them to controllers (as we should), which would make the whole future useless. Only THEN it would make sense to remove it.

**Comment by Progi1984** [comment]
Ok. I will try to fix it.

But I don't find in Object Model a correspondence between the field name in database and the field name.

Can I suggest using the field name and transforming it by replacing the underscores with spaces and applying the `ucwords` function (https://www.php.net/manual/fr/function.ucwords.php)?

Example: `public_name` becomes `Public Name`.
Example: `state` becomes `State`
Example: `id_address` becomes `Id Address`

I see this as an acceptable workaround until the validation of objects moves to the Symfony side.

@eternoendless / @MatShir : What do you think about it?

**Comment by eternoendless** [comment]
> But I don't find in Object Model a correspondence between the field name in database and the field name.

As I said before, the matching used to be made by `displayFieldName()` using the `$_FIELDS` variable as declared in the [old dictionaries](https://github.com/PrestaShop/TranslationFiles/blob/master/1.6/fr/translations/fr/fields.php?rgh-link-date=2023-03-20T15%3A24%3A24Z). As you can see, the key is made of the name of the object model class + md5 of the field name: https://github.com/PrestaShop/PrestaShop/blob/ca9d81aae0bb17f3e767bb5d835348ed144a3ab5/classes/ObjectModel.php#L1281

A possible solution would be to keep `displayFieldName()` and have it call the translator using the field name as message, and a translation domain as set in a property within the object model itself.

Like this:

```php
public static function displayFieldName($field, $class = __CLASS__, $htmlentities = true, Context $context = null)
{
  // ...
  return $translator->trans($field, [], static::$translationDomain);
  // ...
}
```

Having done that, we have two options to:

**Option 1: Complete the feature by making the existing fields translatable**

The fields themselves would have to be declared somewhere in order to allow the translations extractor to pick them up and make them appear in the translation interface. For that, we could declare them in [KeysReference Lang files](https://github.com/PrestaShop/PrestaShop/tree/8.0.0/classes/lang/KeysReference) that serve this exact purpose.

In this scenario, it would only remain to decide a translation domain for each ObjectModel. I suggest `Shop.Fields.<Classname>`

That said, there are _lots_ of fields, and to properly implement this we'd have to add a new option in the BO translation called "Field translations" (like Back office translations, Front office translations, etc). This might represent a lot of trouble for error messages that are meant go away sooner or later, as they are handled by controllers when the page has been migrated to symfony.

**Option 2: Only make this available for developers**

As an alternative, we could just leave this implemented without declaring all the fields. This would allow developers or integrators to handle this on their own if they choose to continue using HelperForm + Objectmodel.

* If a module includes an ObjectModel, they could use the module's domain for translations (eg `Modules.Mymodule.<Classname>`). Declaring the wordings anywhere in the module will make them show up in the translation interface when choosing that module.
* Alternatively, translations can be inserted directly in database.
* Keeping this method would also allow integrators to override it and reimplement it as they see fit.

**Comment by Progi1984** [comment]
Sorry. I will contribute only on UI tests now.

**Pull request closed without merging**
