### PR TITLE
Fix desktop menu regressions

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix integrations issues
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional)
| How to test?  | Compare menu with machine shuffle 1.7

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7535)

### CODE REVIEW

**Review by aleeks — APPROVED** [review]
Looks like ok

**Review by maximebiloe — APPROVED** [review]

**Comment by Shudrum** [comment]
Can you remove the compiled assets please?

Thank you!

**Comment by nihco2** [comment]
@Shudrum Done

**Comment by maximebiloe** [comment]
Thank you @nihco2

**Pull request merged**
