### PR TITLE
Fix license headers

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix license headers
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | No need for QA
| Possible impacts? |

### CODE REVIEW

**Comment by nicosomb** [comment]
Why don't commit on this PR? https://github.com/PrestaShop/PrestaShop/pull/32078

**Comment by matks** [comment]
@nicosomb I did not see it 😄

**Review by tleon — APPROVED** [review]

**Comment by matks** [comment]
@nicosomb PR https://github.com/PrestaShop/PrestaShop/pull/32078 seems stuck :/ so I would like my PR to move forward (at least it's going to fix a few outdated / missing license headers). The added value of my PR should not be blocked because another PR is stuck IMO.

**Review by nicosomb — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @matks

**Pull request merged**
