### PR TITLE
Merge 177x to develop 2020/12/21

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 177x to develop 2020/12/21
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22529)

### CODE REVIEW

**Comment by jolelievre** [comment]
@boubkerbribri There was conflicts on one UI test file but I can't remember which one Even for the others can you please check if everything seems alright?

@atomiix I had to ignore the changes you made in LocalizationPack.php from this PR https://github.com/PrestaShop/PrestaShop/pull/21912 Because now the class uses the `AddOfficialCurrency` which also manages the fallback to use existing currency and re-enables it if necessary So I think this mainly covers what you changed in this class but maybe it's worth having you check if it's alright, and maybe test it quickly

Thanks to both of you :)

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@jolelievre Behat tests fail 😞 

```
--- Failed steps:
001 Scenario: I order a product which price is changed after I order Then I update carrier, the product price must not change # Features/Scenario/Order/order_fixed_product_prices.feature:29
      Given product "Test Changing Product" price is 15.00                                                                    # Features/Scenario/Order/order_fixed_product_prices.feature:63
        Fatal error: Class 'Tests\Integration\Behaviour\Features\Context\Cart' not found (Behat\Testwork\Call\Exception\FatalThrowableError)
002 Scenario: Add a customized product without its customization                                        # Features/Scenario/Order/order_to_cart.feature:26
      Then I should get an error that the product is customizable and the customization is not provided # Features/Scenario/Order/order_to_cart.feature:32
        Last error should be "PrestaShop\PrestaShop\Core\Domain\Product\Exception\ProductCustomizationNotFoundException", but got "null" (RuntimeException)
```

**Comment by atomiix** [comment]
@jolelievre I've an issue when I follow those steps:
1. Add a non-existing language in *International > Localization > Languages* (iso code: aa, language: en-TS)
2. Try to add a new Currency, DZD for instance. You'll get an error that says `Can not find CLDR data for currency DZD`

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Wait for @atomiix approved

**Comment by atomiix** [comment]
@jolelievre the issue was in fact already there in develop. I created the issue #22545 but it means we can merge 1.7.7.x in develop as the original issue fixed by #21912  is still fixed.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @jolelievre

**Pull request merged**
