### PR TITLE
array_key_exists is deprecated on objects. use property_exists instead

### LINKED ISSUE #23710: category api returns name null
`/prestashop/api/categories?language=1&output_format=JSON&display=full` gives below
```json
active: "1"
associations: {products: Array(1)}
date_add: "2021-03-17 10:21:48"
date_upd: "2021-03-17 10:21:48"
description: null
id: 4
id_parent: "3"
id_shop_default: "1"
is_root_category: "0"
level_depth: "3"
link_rewrite: null
meta_description: null
meta_keywords: null
meta_title: null
name: null
nb_products_recursive: "1"
position: "0"
```
here name is null. how to fix it?

### PR DESCRIPTION
**Pull request by tahsin352**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | array_key_exists is deprecated on objects. use property_exists instead. It's give error on api call.
| Type?             |  improvement 
| Category?         |  WS 
| BC breaks?        | yes 
| Deprecations?     | yes 
| Fixed ticket?     | Fixes #23710
| How to test?      | Test using webservices.
| Possible impacts? | Please webservices.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23731)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
array_key_exists is executed on an array, not an object.

**Comment by tahsin352** [comment]
@PierreRambaud while running on php 7.4, i got below error
```
array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead (\/Library\/WebServer\/Documents\/prestashop\/src\/Adapter\/EntityMapper.php
```
I fixed those by `property_exists`.

**Comment by PierreRambaud** [comment]
> @PierreRambaud while running on php 7.4, i got below error
> 
> ```
> array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead (\/Library\/WebServer\/Documents\/prestashop\/src\/Adapter\/EntityMapper.php
> ```
> 
> I fixed those by `property_exists`.

Are you using the latest develop branch to get this error, or are you using the 1.7.7 release?

**Comment by tahsin352** [comment]
@PierreRambaud Yes, latest develop branch.

**Comment by PierreRambaud** [comment]
> @PierreRambaud Yes, latest develop branch.

I'm running the develop branch on PHP7.4 and I'm not able to reproduce, your change is not legit, get_object_vars returns an array not an object.

**Comment by matthieu-rolland** [comment]
> > @PierreRambaud Yes, latest develop branch.
> 
> I'm running the develop branch on PHP7.4 and I'm not able to reproduce, your change is not legit, get_object_vars returns an array not an object.

that's probably why the QA team couldn't reproduce the issue.

@tahsin352 did you reproduce this issue on the develop branch ?

**Comment by henri9813** [comment]
Hello,

Same problem here, prestashop 1.7.7.5. Use debug mode to see it.

**Comment by PierreRambaud** [comment]
> Hello,
> 
> Same problem here, prestashop 1.7.7.5. Use debug mode to see it.

It's normal, 1.7.7.5 is not yet compatible with PHP 7.4 as mentioned here: https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#php-compatibility-chart

I'm closing this issue as it's not reproducible

**Pull request closed without merging**
