### PR TITLE
Drop leftover code, /tools/http_build_url/ was removed

### LINKED ISSUE #24722: http_build_url can not be no longer required from tools/
#### Describe the bug

Requires must be removed, see https://github.com/PrestaShop/PrestaShop/search?q=http_build_url

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | see title
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/24722
| How to test?      | CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24760)

### CODE REVIEW

**Review by matks — APPROVED** [review]
Nice finding @mvorisek thank you.

I can find http_build_url tool in PrestaShop 1.6 https://github.com/PrestaShop/PrestaShop/tree/1.6.1.21/tools but not in PrestaShop 1.7.0.0 https://github.com/PrestaShop/PrestaShop/tree/1.7.0.0/tools

**Review by Progi1984 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
I think QA from developer is good enough. I'll let someone from @PrestaShop/prestashop-core-developers merge it.

Thank you @mvorisek 👍

**Comment by matks** [comment]
Tested import process without failures ✅

**Comment by matks** [comment]
Thank you @mvorisek

**Pull request merged**
