### PR TITLE
[-] BO: updated validation of price rule name to be consistent with database

### PR DESCRIPTION
**Pull request by webdif**
## Description

Maxlength should be 255 instead of 32.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @webdif, not realy.
What is the gain versus the increase of space in database ? Do you have so much price rules that you need more than 32 characters to describe them ?

**Comment by webdif** [comment]
Hi @mickaelandrieu,
In database, the field is `VARCHAR(255)`. The restriction to 32 is just the maxlength of the input.

**Comment by mickaelandrieu** [comment]
> In database, the field is VARCHAR(255)

Ok, merged. Thank you @webdif

**Comment by webdif** [comment]
@mickaelandrieu Not sure how to do that, I edited the file directly on Github. I just renamed the PR but can't find how to rename commit.

**Comment by mickaelandrieu** [comment]
@webdif well you need to edit the commit label: do you have git on your computer ?

You can use this tutorial, it's easy :) https://help.github.com/articles/changing-a-commit-message/

Thank you for your help !

**Comment by webdif** [comment]
Yes, I'm familiar with Git, but not with Github's UI (I edited the file in github directly). But that's OK now, the commit message has been modified.

**Comment by aleeks** [comment]
Hello @webdif 
It's already done here: https://github.com/PrestaShop/PrestaShop/pull/5803

Regards

**Pull request closed without merging**
