### PR TITLE
Backport Fix Simple anchors do not work #26380

### LINKED ISSUE #26326: Simple anchors do not work
#### Describe the bug

When I try to link to an anchor on a page, the page refreshes and doesn't stay.

Not easy to explain I hope the video will be clearer :)

#### Steps to Reproduce

1. Created a lot of text on a CMS page
2. Make a link to reach the bottom of the page
`<a href="#id777">Test ancre</a>`
`<p>Text.....</p>`
`<p id="id777">`
4. click on the link and see the error, the page is refreshed and straightened out.

**Screenshots**

https://user-images.githubusercontent.com/46202635/137910770-307466ef-21a3-424c-b654-89977606fbcd.mp4

#### Additional information
* No cache
* Test locally and in production (similar error)
* PrestaShop version: 1.7.8
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by alexandrebru83**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | When I try to link to an anchor on a page, the page refreshes and doesn't stay. Not easy to explain I hope the video will be clearer
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26326 
| How to test?      | See #26326 How to test section
| Possible impacts? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26410)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @alexandrebrubeyonds,

It is ok :heavy_check_mark: 
I checked with the new page => ok no-refresh 
**With PR**
https://watch.screencastify.com/v/XsASje4K3xxn54dHZNXw
I check also with Product comment module => Read reviews => OK 
https://watch.screencastify.com/v/VrWpMmcSnuQJoZB8ptyq

**Without PR** => NOK
https://watch.screencastify.com/v/xFDs1Eb8JyEkM9k3gF0e

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith & @alexandrebrubeyonds

**Comment by Prestapepe** [comment]
I see the file under the _dev folder but this folder is not in production yet, so... how can we make this work in the current prestashop version??

I didnt find a equivalent file.... 

Thanks

**Comment by Prestapepe** [comment]
@Progi1984

> Thanks @khouloudbelguith & @alexandrebrubeyonds

I see the greeetings, but the solution is aaplyed to a _dev folder that doesnt exist in production. The bug is still open!!

Please how those files apply to production if doenst exists there???

**Comment by ErwanZou** [comment]
> @Progi1984
> 
> > Thanks @khouloudbelguith & @alexandrebrubeyonds
> 
> I see the greeetings, but the solution is aaplyed to a _dev folder that doesnt exist in production. The bug is still open!!
> 
> Please how those files apply to production if doenst exists there???

Hello,
I found a solution that works on my side. You just have to comment out the "popstate" passage in the theme.js
`/*if ($(prestashop.themeSelectors.listing.list).length) {window.addEventListener('popstate', (e) => {const {state} = e;window.location.href = state && state.current_url ? state.current_url : history;});}*/*`

**Pull request merged**
