### PR TITLE
Fix not visible category display

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | fix template error when trying to display not visible category
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5678
| How to test?  | restrict category access to authenticated users only, visit the page with a not-authenticated account

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9315)

### CODE REVIEW

**Review by eternoendless — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @tomlev

**Comment by jf-viguier** [comment]
Can someone paste the issue here ?

**Comment by matks** [comment]
@jf-viguier Bug report BOOM-5678 content:

> Trying to access a category for which I don't have the rights (Category is configured to be only available to one specific group which I do not belong to) I get this error message (debug is "on") => See capture
> I use PS 1.7 default theme...
a

**Comment by jf-viguier** [comment]
@matks thanks.
This PR added the forced tpl : it's not relevant anymore I guess : no error without this tpl call.

**Pull request merged**
