### PR TITLE
Fix product footer direction using RTL language

### LINKED ISSUE #24925: [BO] Invalid direction of checkbox marker in RTL
Hello,

#### Describe the bug

Checkbox marker has invalid direction in BO with **RTL** Layout

#### Expected behavior

.../adminxxx/themes/new-theme/public/theme_rtl.css (Line: 521)
Need to change (border-left-style: none) to (border-right-style: none)

#### Steps to Reproduce

BO: Improve > international > localization

Screenshot 2021-06-11 at 18-40-33 بومی سازی • NEO

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

### LINKED ISSUE #24926: [BO] Invalid product footer position in RTL
Hello,

#### Describe the bug

Position of product footer is not fixed correctly for **RTL** layout in BO.

#### Expected behavior

.../adminxxx/themes/new-theme/public/product.css (Line: 664)
Need to change (right: 0; left: 13.13rem) to  (left: 0; right: 13.13rem)

#### Steps to Reproduce

1. Go to Catalog
2. Add new product

Screenshot 2021-06-11 184752

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Product footer direction was wrong using RTL language
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24926.
| How to test?      | Go on one product page and see footer
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

# How does it looks?
image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25034)

### CODE REVIEW

**Review by sowbiba — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by sarahdib** [comment]
@NeOMakinG the bug is not fixed 
Capture d’écran 2021-06-19 à 17 02 36

**Comment by NeOMakinG** [comment]
> @NeOMakinG the bug is not fixed
> Capture d’écran 2021-06-19 à 17 02 36

@sarahdib how dd you test? You probably need to remove the theme_rtl.css file inside the new-theme public folder, then active an RTL language, so it will generate the RTL stylesheet accordingly with the fix

**Comment by NeOMakinG** [comment]
Oh wait, are you on the experimental page?

**Comment by NeOMakinG** [comment]
@sarahdib 
image

Event on the experimental page, it looks fixed

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

it's Ok at first : 

image

V2 => OK

image

Then try to reduce the menu, see error:

image

On medium screen (ex: 1320px), these two buttons are separted => NOK

image

On mobile => NOK

image

Please check and feedback.
Thanks!

**Comment by NeOMakinG** [comment]
should be fine now @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

The issue of reduced menu is still there (it's partially fixed :wink: )

image

On medium screen, the button is fixed but it's misplaced:

image

I think it should be like this:

image

On mobile, if you could place the word "Online" besides the switch, it will be perfect:

image

Thanks for your hard working :pray:

**Comment by NeOMakinG** [comment]
Should be good now @hibatallahAouadni

**Comment by hibatallahAouadni** [comment]
LGTM, QA :heavy_check_mark: 
Thanks!

**Comment by PierreRambaud** [comment]
> LGTM, QA 
> Thanks!

Could you please put the label?

**Comment by hibatallahAouadni** [comment]
> QA OK without required approvals !? :trollface:

@PierreRambaud did you see? jokes on me :sweat_smile:

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @hibatallahAouadni

**Pull request merged**
