### PR TITLE
Remove unused legacy Customer Adresses files

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Remove legacy unused Customer Adresses files
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Linked to https://github.com/PrestaShop/PrestaShop/issues/10557
| How to test?  | No QA needed I think.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17077)

### CODE REVIEW

**Comment by matks** [comment]
Links to be fixed:
- some links in "view an order" page but since the page is migrated, it's OK
- in js/admins.js the function `dni_required()` needs to be updated
- in admin-dev/themes/default/template/helpers/form/form.tpl the address_token (used in dni_required() needs to be updated)

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matks ! Could you resolve the conflict ? Thanks :heart:

**Comment by matks** [comment]
> Hi @matks ! Could you resolve the conflict ? Thanks ❤️

There was no conflicts when I opened the PR :trollface:

**Comment by matks** [comment]
Rebased. Please approve this PR before it needs another rebase.

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thanks for review !

**Comment by PierreRambaud** [comment]
Thanks @matks

**Pull request merged**
