### PR TITLE
Save selected payment option with Ajax

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Save selected payment option to database.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Change payment option and refresh page.

This contribution requires https://github.com/PrestaShop/ps_checkpayment/pull/8 and https://github.com/PrestaShop/ps_wirepayment/pull/16

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi @martinfojtik  !

What is the aim of saving the payment option in Ajax please ? In what case is it useful ?

Thanks

**Comment by martinfojtik** [comment]
Hi @vincentbz,

if a customer selects a payment option and leaves the checkout page (for example, he wants to add something else to the cart). After returning to checkout there is no selected payment method. Customer must again choose the payment method. This PR will fix that.

**Comment by vincentbz** [comment]
Ok thanks for that explanation :)
There is a problem as for legal reasons we must not force a pre selected payment method if the basket is changed. 
With your PR, if I add a new product in the basket or if I change a thing (like shipping, gift wrapping...), the payment method is still selected whereas it shouldn't be. And in many countries, it will not be legal (as Germany or Austria, even France I think)

**Comment by martinfojtik** [comment]
ok, I didn't know that :) we don't have anything like that in the Czech Republic. Can we add an option to admin to enable/disable this functionality?

**Comment by vincentbz** [comment]
I see it with the team :)
Otherwise, do you think it's possible to cancel the ajax save if there is an event in the previous steps ?

**Comment by vincentbz** [comment]
Hi @martinfojtik 

It has been a long time but I think we can't merge a feature like this. It would be too specific, legaly too "borderline" and also some functional tricky cases.
I have to close it, thanks for your understanding :)

**Pull request closed without merging**
