### PR TITLE
Enable new Orders page

### LINKED ISSUE #17970: [ORDER PAGE] Check all legacy links are correctly redirected to new page
We need to go through all PrestaShop code looking for `AdminOrders` links and make sure they are correctly redirected to new migrate Orders pages.

This can be done by 3 ways:
- using redirection mechanism such as `getAdminLink()` abilities
- modifying the link (especially for hardcoded appended links in Javascript)
- adding `_legacy_link` tags on new routes

List of bad links fixed:
- link to order on timeline in Customer Service
- link to order from "Customers > Outstanding" page (only visible in B2B mode)
- link to order from "Customers > Merchandise returns" page
- search results page (example `/admin-dev/index.php?controller=AdminSearch&token=XXX`)

Links that are correctly redirected from legacy page to symfony page:
- dashboard and tab links
- search redirects (not search page)
- notification about new order
- customer page

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Enable new Orders page by adding active legacy_links
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/17970
| How to test?  |

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17959)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
@matks seems like sanity tests are failing on the order filter: `should reset all filters and get number of orders`

**Comment by matks** [comment]
Tests skipped in https://github.com/PrestaShop/PrestaShop/pull/17959/commits/b8dbcc1f0436a788c928f8400b72703b900b8c5f following @boubkerbribri guidelines

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi ! There is a missing link in Customer Service > Customer Service > Customer Service (lol), in "Orders and messages timeline", the "See more" button should redirect to the order, it does not (it redirect to orders list).

new order link

**Comment by matks** [comment]
@Robin-Fischer-PS Fixed your link and many others (see list in https://github.com/PrestaShop/PrestaShop/issues/17970). Code looks fine now 🤔so I'll dare saying "I think there is no link targeting Order pages anymore in this PR !"

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
All seems fine to me now, thanks @matks !

**Comment by Progi1984** [comment]
Thanks @matks

**Pull request merged**
