### PR TITLE
Missing extends in the new ValueObject\Email class

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Missing extends in the new ValueObject\Email class
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | No need QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17931)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by PululuK** [comment]
Hi @PierreRambaud 
Travis is tired 😫... I have the same problem here https://github.com/PrestaShop/PrestaShop/pull/17920

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud
> Travis is tired ... I have the same problem here #17920

I'm stuck, I'll ask to the Core team what's happening :/

**Comment by PululuK** [comment]
> > Hi @PierreRambaud
> > Travis is tired ... I have the same problem here #17920
> 
> I'm stuck, I'll ask to the Core team what's happening :/

Thank you ! keep me posted please @PierreRambaud

**Comment by PierreRambaud** [comment]
> > > Hi @PierreRambaud
> > > Travis is tired ... I have the same problem here #17920
> > 
> > 
> > I'm stuck, I'll ask to the Core team what's happening :/
> 
> Thank you ! keep me posted please @PierreRambaud

We found the problem, we are working on it :wink:

**Pull request merged**
