### PR TITLE
Remove deprecated ProductImageFolderProvider

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated ProductImageFolderProvider
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no, removed deprecated class
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | N/A
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26168)

### CODE REVIEW

**Comment by matks** [comment]
Hoho there was a unit test for the deprecated class. I'm surprised, and I'm happy.

**Comment by tegbessou** [comment]
PR is valid IMO

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
This class is deprecated since the 8.0. Can't be removed right now :roll_eyes:

**Comment by matks** [comment]
Closing I think I will never have the time to continue this topic and it is not a must-have.

**Pull request closed without merging**
