### PR TITLE
[*] New Hook to override object property

### PR DESCRIPTION
**Pull request by MJ-Aristote**
An example is better :
**Old way to add property to customer** , put this in override folder :

```
    public static $definition = array(
        'table' => 'customer',
        'primary' => 'id_customer',
        'fields' => array(
            'secure_key' =>                array('type' => self::TYPE_STRING, 'validate' => 'isMd5', 'copy_post' => false),
            'lastname' =>                    array('type' => self::TYPE_STRING, 'validate' => 'isName', 'required' => true, 'size' => 32),
            'firstname' =>                    array('type' => self::TYPE_STRING, 'validate' => 'isName', 'required' => true, 'size' => 32),
            'email' =>                        array('type' => self::TYPE_STRING, 'validate' => 'isEmail', 'required' => true, 'size' => 128),
            'passwd' =>                    array('type' => self::TYPE_STRING, 'validate' => 'isPasswd', 'required' => true, 'size' => 32),
            'last_passwd_gen' =>            array('type' => self::TYPE_STRING, 'copy_post' => false),
            'id_gender' =>                    array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId'),
            'birthday' =>                    array('type' => self::TYPE_DATE, 'validate' => 'isBirthDate'),
            'newsletter' =>                array('type' => self::TYPE_BOOL, 'validate' => 'isBool'),
            'newsletter_date_add' =>        array('type' => self::TYPE_DATE,'copy_post' => false),
            'ip_registration_newsletter' =>    array('type' => self::TYPE_STRING, 'copy_post' => false),
            'optin' =>                        array('type' => self::TYPE_BOOL, 'validate' => 'isBool'),
            'website' =>                    array('type' => self::TYPE_STRING, 'validate' => 'isUrl'),
            'company' =>                    array('type' => self::TYPE_STRING, 'validate' => 'isGenericName'),
            'siret' =>                        array('type' => self::TYPE_STRING, 'validate' => 'isSiret'),
            'ape' =>                        array('type' => self::TYPE_STRING, 'validate' => 'isApe'),
            'outstanding_allow_amount' =>    array('type' => self::TYPE_FLOAT, 'validate' => 'isFloat', 'copy_post' => false),
            'show_public_prices' =>            array('type' => self::TYPE_BOOL, 'validate' => 'isBool', 'copy_post' => false),
            'id_risk' =>                    array('type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'copy_post' => false),
            'max_payment_days' =>            array('type' => self::TYPE_INT, 'validate' => 'isUnsignedInt', 'copy_post' => false),
            'active' =>                    array('type' => self::TYPE_BOOL, 'validate' => 'isBool', 'copy_post' => false),
            'deleted' =>                    array('type' => self::TYPE_BOOL, 'validate' => 'isBool', 'copy_post' => false),
            'note' =>                        array('type' => self::TYPE_HTML, 'validate' => 'isCleanHtml', 'size' => 65000, 'copy_post' => false),
            'is_guest' =>                    array('type' => self::TYPE_BOOL, 'validate' => 'isBool', 'copy_post' => false),
            'id_shop' =>                    array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'copy_post' => false),
            'id_shop_group' =>                array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'copy_post' => false),
            'id_default_group' =>            array('type' => self::TYPE_INT, 'copy_post' => false),
            'id_lang' =>                    array('type' => self::TYPE_INT, 'validate' => 'isUnsignedId', 'copy_post' => false),
            'date_add' =>                    array('type' => self::TYPE_DATE, 'validate' => 'isDate', 'copy_post' => false),
            'date_upd' =>                    array('type' => self::TYPE_DATE, 'validate' => 'isDate', 'copy_post' => false),
            'new_field' =>                    array('type' => self::TYPE_DATE, 'validate' => 'isDate', 'copy_post' => false),
        ),
    );
```

**New way to add property to customer** , use hook in you module :

```
    public function hookActionCustomerDefinitionModifier($params) {
        $params['definition']['fields']['new_field'] = array('type' => self::TYPE_DATE, 'validate' => 'isDate', 'copy_post' => false);
    }
```

It's simple and permit multiple overrides by different modules...

### CODE REVIEW

**Comment by gskema** [comment]
I know this looks tempting but Admin controllers grab the static `$definition` before instantiating an object, which means the added field doesn't get included.

**Comment by MJ-Aristote** [comment]
AdminController seems to use
```
$definition = ObjectModel::getDefinition($class_name);
```
to get properly definition... so for me it's working.

**Comment by PrestaEdit** [comment]
I think this is an another way to handle it: https://www.facebook.com/permalink.php?story_fbid=760116190783841&id=100003564015734

**Comment by PrestaEdit** [comment]
I think this is an another way to handle it: https://github.com/PrestaShop/PrestaShop/pull/4064

**Comment by MJ-Aristote** [comment]
It doesn't care the way to do it, the aim is to have this possibility in core to allow proper properties extensions. Your solution is perhaps better than mine. It must be choose by Prestashop team.

**Comment by gskema** [comment]
@MJ-Aristote `ObjectModel::getDefinition($class_name)` is the exact problem, did you look it up? It takes the class static definition, which hasn't been altered yet. If alter the definition by `__construct` or `hookAlter*` an object must be instatiated. Some controllers don't instatiate any object before taking the definition, others do, but only by accident.

I was altering class definition using `__construct` until I noticed this bug in some admin controllers. This is why I use "the old way" (from your example)

**Comment by MJ-Aristote** [comment]
> If alter the definition by __construct or hookAlter* an object must be **instatiated**.
This hook is execute when objectmodel read __static__ property and return it to controllers.
The object is not instantiate yet.
That's why it's better than but it in __construct
Try this code, you will see if it works or not.
I'm using PS 1.6.1.1

**Comment by gskema** [comment]
@MJ-Aristote ok now I see what's going on. We should examine how this hook would impact the app.

**Comment by antoin-m** [comment]
Hey @MJ-Aristote, thank you for your contribution.

Unfortunately this PR would add lots of calls to Hook::exec() and modules developers are not even allowed to change the columns of the core models.

**Pull request closed without merging**
