### PR TITLE
Add breadcrumb to the contact page

### PR DESCRIPTION
**Pull request by SebBareyre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | add the missing breadcrumb function
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Just visit the contact page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9362)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Okay, this seems legit and this PR is fine technically.
However, I see there is a breadcrumb only on 2-levels pages, and on the category page. I guess there was a reason to not display it everywhere. We need a product review on this one.

ping @colinegin

**Comment by kpodemski** [comment]
@Quetzacoalt91 @colinegin 

it was reported by some people in Poland as a bug, after first look at it I was also in that group of people who thought that breadcrumb should be everywhere :)

**Comment by SebBareyre** [comment]
@kpodemski : I think that breadcrumb should be everywhere too... :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @SebBareyre

**Pull request merged**
