### PR TITLE
Optimize StockManager SQL queries for updating Physical and Reserved quantities

### LINKED ISSUE #14703: Poor performances in order status update due very slow StockManager.php queries
After troubleshooting slowdowns in order status change from a customer with a large catalogue I noticed that there are two queries that takes a very lot of time to run.

**ValidateOrder** method and status change are taking up to 15~20 seconds due to those queries.

First query in /src/Adapter/StockManager.php:171 (updateReservedProductQuantity method)
takes ~ 7 seconds to run   on high-spec dedicated MySQL server
Second query in /src/Adapter/StockManager.php:118 (updatePhysicalProductQuantity method)
takes ~ 10 seconds to run  on high-spec dedicated  MySQL server

First query is : 

```
UPDATE ps_stock_available sa
SET sa.reserved_quantity = (
SELECT SUM(od.product_quantity - od.product_quantity_refunded)
FROM ps_orders o
INNER JOIN ps_order_detail od ON od.id_order = o.id_order
INNER JOIN ps_order_state os ON os.id_order_state = o.current_state
WHERE o.id_shop = 1 AND
os.shipped != 1 AND (
o.valid = 1 OR (
os.id_order_state != 8 AND
os.id_order_state != 6
)
) AND sa.id_product = od.product_id AND
sa.id_product_attribute = od.product_attribute_id
GROUP BY od.product_id, od.product_attribute_id
)
WHERE sa.id_shop = 1
AND sa.id_product IN (SELECT product_id FROM ps_order_detail WHERE id_order = 15244)
```

Second query is :

```
UPDATE ps_stock_available sa
SET sa.physical_quantity = sa.quantity + sa.reserved_quantity
WHERE sa.id_shop = 1
```

This query seems to update the **whole** ps_stock_available table even if I am changing the status of a single order (?).

**In my case the ps_stock_available table have 903.000 distinct rows (website have 150k products with 740k combinations) so you'll need a large shop to reproduce this.**

Note that the problem was already represented in [BOOM-6265](http://forge.prestashop.com/browse/BOOM-6265) , but issue was closed and mis-referenced to other closed issues that had nothing to do with this problem, so it is still present in 1.7.6.0

### PR DESCRIPTION
**Pull request by alisamie97**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I have been facing a bad performance on PaymentModule::validateOrder and after some research I found out that the issue is with bad queries.
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Described after this table
| Fixed ticket?     | Fixes #14703 
| Related PRs       | Not found
| Sponsor company   | Your company or customer's name goes here (if applicable).

### How to test?

1. Make a huge shop (+ 120k products and many combinations)
2. Log the time before and after calling `$StockManager->updatePhysicalProductQuantity()` in these files:
3. `classes/PaymentModule.php`
4. `classes/order/OrderHistory.php`
5. Log the time before and after calling `$StockManager->updateReservedProductQuantity()` in this file:
6. `src/Adapter/StockManager.php`

I will post my results here soon

### CODE REVIEW

**Comment by alisamie97** [comment]
I tested this in a live server with these important numbers:
1. `ps_product` ~150k rows
2. `ps_product_attribute` ~160k rows
3. `ps_product_attribute_combination` ~160k rows
4. `ps_stock_available` ~320k rows
5. `ps_orders` ~23k rows
6. `ps_order_detail` ~134k rows

Testing rules:
- 10 products in cart for each test
- In each test the items in carts must be identical
- All modules that are hooked to the `PaymentModule::validateOrder()` MUST be unhooked

### Stage 1: Default code and no optimization
#### Time: ~8.47s
Stage 1

### Stage 2: Only optimize `updateReservedProductQuantity()`
#### Time: ~3.45s
Stage 2

### Stage 3: Only optimize `updatePhysicalProductQuantity()`
#### Time: ~3.14s
Stage 3

### Stage 4: Optimize both methods
#### Time: ~0.64s
Stage 4

**Comment by kpodemski** [comment]
well done @stifler97 👏🏻 

I see that you have a merge commit inside your PR, you will have to remove this commit to keep the git history clean.

PR looks very promising, I'll make sure to have a detailed look at your PR soon!

**Comment by alisamie97** [comment]
@kpodemski
Sorry for that, so I must push my commits directly into develop branch?

**Comment by alisamie97** [comment]
@kpodemski I added two commits directly on `develop` branch

**Comment by alisamie97** [comment]
Hi everyone.
I am willing to give you more details about what I have done if anyone is interested. Nearly two month ago I posted this edit and no body asked anything. I am not sure if this has any mistake or it is a rare case and few people are facing it.
Anyways I want to remind the team for this one because I think its has a huge impact, and I am ready to add more of this kind to the project. @kpodemski

**Comment by kpodemski** [comment]
Hello @stifler97 

Im going through some old PRs and I have your on the list as well. I validated another PR improving performance inside this methods, this one:

https://github.com/PrestaShop/PrestaShop/pull/28854

It's a bit cleaner, and it also solved the problem with slowness after placing an order. Could you check if it works for you? After merging it, I'd like to continue optimization in this part of the core, because placing an order is quicker, but "Stocks" in back office is still slow.

Let me know, I'd appreciate your feedback there.

**Comment by kpodemski** [comment]
Hi @stifler97 

I merged this other PR that improved the performance drastically, but with a little cleaner code.

I noticed there's still slowness with the method in the reserved quantity recalculation. I'm investigating it.

**Comment by alisamie97** [comment]
> Could you check if it works for you?

Hi @kpodemski 
I checked this PR #28854 in our shop and it has a good performance. However as expected we still have the slow query in reserved calculation as you mentioned.

I am ready to help more in queries because I think there are more to optimize. For example the add to cart action is very slow in our current version which is 1.7.7.8, we are about to upgrade to 1.7.8.8 and I did not test yet if it is fixed. But I would like to find the root cause of that and try to optimize it too as many many requests will come to the server for the add to cart action when a shop is on sale or in a season

**Pull request closed without merging**
