### PR TITLE
Remove legacy images

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes old functionality regarding legacy images. This was an old structure of images where all product images were in single folder, like categories or manufacturers. Prestashop is using the new system by default since 1.5.1.0.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes - It won't offer the migration in admin image controller. Also, requesting an image in old format idProduct-idImage will throw a deprecation notice in developer mode. `Deprecated: Passing image identifier in the old format is deprecated, use only image ID. This fallback will be removed in next major.`
| How to test?      | See that nothing changes and images still work fine. Maybe a dev could do the QA.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by AureRita** [comment]
Hi @Hlavtox 

Thank you for your PR ! I tested it and I find an issue, when you do an order with a product without images, You didn't have the default picture selected when you have no images, as you can see on this video : 

[Untitled_ Feb 16, 2023 2_56 PM.webm](https://user-images.githubusercontent.com/100699445/219386860-0a7cdd36-043b-4799-95f8-2543566f5909.webm)

In this video, you've one part without the PR and another one, with the PR. 

Waiting for your feedback

**Review by nicosomb — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by AureRita** [comment]
Hi @Hlavtox 

Thank you for your correction, I tried this and I find that the issue is now on the product with images, as you can see : 

[Untitled_ Feb 16, 2023 5_51 PM.webm](https://user-images.githubusercontent.com/100699445/219433550-35e35940-f534-47d4-a941-6d3a305e3ec3.webm)

Waiting for your feedback

**Comment by Hlavtox** [comment]
Hi @AureRita, found the issue and fixed it. There were still some places in the code, where it was trying to get the product image in the old format (id_product-id_image). I removed this, should be fine now. 👍

noimage

Ping @nicosomb and @kpodemski for reapproval. 🙏

**Comment by kpodemski** [comment]
@Hlavtox 

PHPStan complains:  Parameter #2 $idImage of method LinkCore::getImageLink() expects string, int given.

**Comment by Hlavtox** [comment]
I will convert it to allow the underscored ids. Will support the old format for some majors now.

```
if (strpos("_", $idImage) {
 throw notice
remove the product id
}
```

**Comment by Hlavtox** [comment]
@kpodemski Ready to go

**Review by zuk3975 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @Hlavtox 

I have checked your PR. Here is my checked list : 

- Check the automated tests: OK
- Check the images work fine on the product page with different product types (Standard, Combinations, Virtual, Pack) : OK
- Check when adding images for the product: OK
- Check when no images are set for every product type: OK
- Check the products images (With images and without) on the order page (BO & FO) : OK 
- Check the images when inserting them from the file manager on different pages: OK
- Check the images on the categories page : OK
- Check the images on the brands page : OK
- Check the images on the stocks page : OK
- Check with different PHP versions (7.3, 8.1) : OK
- Check with different browsers : OK

But, i found an issue on Stocks page but it's not related to this PR 
image

So, it's QA :heavy_check_mark: 

Thank You!

**Comment by Hlavtox** [comment]
Thank you @HanaRebaiQA! :-)

**Pull request merged**
