### PR TITLE
Fix smarty deprecation stripslashes and md5

### LINKED ISSUE #32703: smarty user deprecation notices about php function modifiers
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the logs, I get errors like:
     
    User Deprecated: Using php-function "stripslashes" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

    User Deprecated: Using php-function "strtoupper" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier.

### Expected behavior

Prestashop should not use smarty functionality that is deprecated in the currently used smarty version.

### Steps to reproduce

1. Enable logging of `E_USER_DEPRECATED` (In PHP 8.1, logging of `E_USER_DEPRECATED` is enabled by default)
2. Navigate to a page that uses a deprecated smarty modifier, e.g.
    - `/recuperation-mot-de-passe`
    - `/manufacturers`
    - Follow indications here https://github.com/PrestaShop/PrestaShop/issues/31731#issuecomment-1543413116
4. Find the error in the server logs

### PrestaShop version(s) where the bug happened

8.0.4, Smarty as required in composer.json: 4.3.1

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Société Biblique de Genève

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Passing `stripslashes` as a modifier in smarty is deprecated since Prestashop 8.0.4
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | With PS 8.0.4 and PHP 8.1 (or 8.0) we no longer get user depreation notices in the error log.
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/32703
| Related PRs       | none
| Sponsor company   | Société Biblique de Genève

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by lmeyer1** [comment]
Sorry, there ws another file containing the deprecated feature

**Review by SharakPL — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your PR :rocket: 
As the related issue is Waiting for Dev to be validated, so this PR can be tested by a Dev.
Ping @PrestaShop/prestashop-core-developers please validated the related issue and test this PR :pray: 

Thanks!

**Comment by matks** [comment]
Hi @lmeyer1 I tested your PR with the scenario

1. Make sure PHP logs errors of level E_USER_DEPRECATED
2. Navigate to /recuperation-mot-de-passe
3. Check latest PHP error log lines, see

But I continue to have the deprecated errors. In your PR content I see the only modified file for front-office is debug.tpl : so maybe this PR is not complete? Then it does not fully fix https://github.com/PrestaShop/PrestaShop/issues/32703 ?

**Comment by kpodemski** [comment]
Maybe this PR will solve the problem globally:
https://github.com/PrestaShop/PrestaShop/pull/33136

I noticed all these deprecations in one of the production stores.

**Comment by jolelievre** [comment]
I agree @kpodemski we should close this PR in favor of yours

**Comment by lmeyer1** [comment]
This problem is fixed in #33136

**Pull request closed without merging**
