### PR TITLE
Fix pack stock issues

### PR DESCRIPTION
**Pull request by alegout**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x.
| Description?  | Fix issue with pack quantity.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [BOOM-4361](http://forge.prestashop.com/browse/BOOM-4361), [BOOM-3487](http://forge.prestashop.com/browse/BOOM-3487)
| How to test?  | 1) in preferences > products > choose decrease both for packs <br>2) Don't allow to order out of stock product <br>3) create a product A with a stock of 50 <br>4) create a product B with a stock of 5, this product is a pack of 10 products A <br>5) You cannot order 50 products A and 5 products B.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8607)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/PrestaShopBundle/Install/DatabaseDump.php, line 60 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L0AcBuc0XD9g9JtMPN0:-L0AcBuc0XD9g9JtMPN1:b-n3fzji) ([raw file](https://github.com/prestashop/prestashop/blob/f749f4ed600f27ccde74f9349635f7732c890643/src/PrestaShopBundle/Install/DatabaseDump.php#L60)):*
> ```PHP
> 
>         if ($dumpFile === null) {
>             $tmpDirPath = sys_get_temp_dir() . '/prestashop';
> ```

I think you didn't want to add this file in the commit ! Please make a separate PR for the DB dump fix.

---

*[src/PrestaShopBundle/Tests/Utils/Database.php, line 38 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L0AcGwKV1_KzVf38gnw:-L0AcGwKV1_KzVf38gnx:b-n3fzji) ([raw file](https://github.com/prestashop/prestashop/blob/f749f4ed600f27ccde74f9349635f7732c890643/src/PrestaShopBundle/Tests/Utils/Database.php#L38)):*
> ```PHP
>      * Create the initialize database used for test
>      */
>     public static function createTestDB($overrideIfExists = true)
> ```

I think you didn't want to add this file in the commit ! Please make a separate PR for the DB dump fix.

---

*[tests/TestCase/IntegrationTestCase.php, line 56 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L0AcPVJR5OTwuw3nXS7:-L0AcPVJR5OTwuw3nXS8:b-n3fzji) ([raw file](https://github.com/prestashop/prestashop/blob/f749f4ed600f27ccde74f9349635f7732c890643/tests/TestCase/IntegrationTestCase.php#L56)):*
> ```PHP
>     {
>         require_once(__DIR__ . '/../../config/config.inc.php');
>         Database::restoreTestDB();
> ```

I think you didn't want to add this file in the commit ! Please make a separate PR for the DB dump fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thank you @alegout 
Please see my comments above

**Comment by alegout** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/PrestaShopBundle/Install/DatabaseDump.php, line 60 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L0AcBuc0XD9g9JtMPN0:-L0AgxL6NHrfiz7Hk9Or:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/f749f4ed600f27ccde74f9349635f7732c890643/src/PrestaShopBundle/Install/DatabaseDump.php#L60)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I think you didn't want to add this file in the commit ! Please make a separate PR for the DB dump fix.
</blockquote></details>

Done.

---

*[src/PrestaShopBundle/Tests/Utils/Database.php, line 38 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L0AcGwKV1_KzVf38gnw:-L0Ags_q0M1mnxWk0gdt:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/f749f4ed600f27ccde74f9349635f7732c890643/src/PrestaShopBundle/Tests/Utils/Database.php#L38)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I think you didn't want to add this file in the commit ! Please make a separate PR for the DB dump fix.
</blockquote></details>

Done.

---

*[tests/TestCase/IntegrationTestCase.php, line 56 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L0AcPVJR5OTwuw3nXS7:-L0AgvoUcZ1t33_9d89w:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/f749f4ed600f27ccde74f9349635f7732c890643/tests/TestCase/IntegrationTestCase.php#L56)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I think you didn't want to add this file in the commit ! Please make a separate PR for the DB dump fix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by LittleBigDev** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-:-L0E10j8gshHLB64CNWS:bnfp4nl)*

**Comment by LittleBigDev** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Review by LittleBigDev — DISMISSED** [review]
Thank you @alegout :+1:

**Comment by marionf** [comment]
Hello @alegout 
If I add first 50 products A and try to add 5 packs B, I can't -> It's ok 
But if I add first 5 packs B and try to add 50 products A, it works while it shouldn't

**Comment by jocel1** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[classes/Cart.php, line 1175 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L2QrdjJFhqFgj_zj_Ev:-L2QrdjJFhqFgj_zj_Ew:bnfmjpm) ([raw file](https://github.com/prestashop/prestashop/blob/843303d3b5058e3217bfa067a76a8dbb965af10e/classes/Cart.php#L1175)):*
> ```PHP
>         if (Configuration::get('PS_ALLOW_MULTISHIPPING') && $this->isMultiAddressDelivery()) {
>             $firstUnionSql .= ' AND cp.`id_address_delivery` = '.(int)$id_address_delivery;
>             $secondUnionSql .= ' AND cp.`id_address_delivery` = '.(int)$id_address_delivery;
> ```

why not putting those in the commonWhere, and add the commonWhere later ?

---

*[classes/Cart.php, line 1180 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L2QroOxn7sDYplP2H4r:-L2QroOxn7sDYplP2H4s:b-rjzxkj) ([raw file](https://github.com/prestashop/prestashop/blob/843303d3b5058e3217bfa067a76a8dbb965af10e/classes/Cart.php#L1180)):*
> ```PHP
>         if ($id_customization) {
>             $firstUnionSql .= ' AND c.`id_customization` = '.(int)$id_customization;
>             $secondUnionSql .= ' AND c.`id_customization` = '.(int)$id_customization;
> ```

Same comment here, move it into the commonWhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by jocel1** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by alegout** [comment]
Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[classes/Cart.php, line 1175 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L2QrdjJFhqFgj_zj_Ev:-L4osXKGJyAaTvBQ9Bs8:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/843303d3b5058e3217bfa067a76a8dbb965af10e/classes/Cart.php#L1175)):*
<details><summary><i>Previously, jocel1 (Jocelyn Fournier) wrote…</i></summary><blockquote>

why not putting those in the commonWhere, and add the commonWhere later ?
</blockquote></details>

Done.

---

*[classes/Cart.php, line 1180 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L2QroOxn7sDYplP2H4r:-L4osY50g0ivb0rzcqhN:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/843303d3b5058e3217bfa067a76a8dbb965af10e/classes/Cart.php#L1180)):*
<details><summary><i>Previously, jocel1 (Jocelyn Fournier) wrote…</i></summary><blockquote>

Same comment here, move it into the commonWhere
</blockquote></details>

Done.

---

*[classes/Cart.php, line 1186 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L4osaJH-Gppr1TzMiC5:-L4osaJIEFVdkGN9sXm4:bb7kaxo) ([raw file](https://github.com/prestashop/prestashop/blob/843303d3b5058e3217bfa067a76a8dbb965af10e/classes/Cart.php#L1186)):*
> ```PHP
>             COALESCE(SUM(first_level_quantity), 0) as quantity 
>           FROM (' . $firstUnionSql . ' UNION ' . $secondUnionSql . ') as q';
>         $result = Db::getInstance()->getRow($parentSql);
> ```

lulz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by eternoendless** [comment]
Reviewed 2 of 8 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[classes/Pack.php, line 177 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5O3mvduB3zsiP-sPKa:-L5O3mvduB3zsiP-sPKb:b-7pn2mj) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Pack.php#L177)):*
> ```PHP
>             || ((int) $wantedQuantity <= 0)
>         ) {
>             $wantedQuantity = Tools::getValue('quantity_wanted', 1);
> ```

This should be given, not inferred from global values

---

*[classes/Pack.php, line 206 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5O4C2pqE43QcYwlmGa:-L5O4C2pqE43QcYwlmGb:bfwaoo7) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Pack.php#L206)):*
> ```PHP
>         $id_product = (int) $id_product;
>         $id_product_attribute = (int) $id_product_attribute;
>         $cache_is_pack = (bool) $cache_is_pack;
> ```

Looks unused

---

*[classes/Pack.php, line 212 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5O2tlv85GwE4m1kX1H:-L5O2tlv85GwE4m1kX1I:b-3yd6kz) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Pack.php#L212)):*
> ```PHP
>         }
>         $packQuantity = StockAvailable::getQuantityAvailableByProduct($id_product, $id_product_attribute);
>         $cart = Context::getContext()->cart;
> ```

Why not pass the cart as a parameter? There's no cart in the BO, and it would be easier to test

---

*[classes/Product.php, line 3592 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5OLkIRmcCTCBDdTGa6:-L5OLkIRmcCTCBDdTGa7:bfw9g6j) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Product.php#L3592)):*
> ```PHP
>     * @param int $id_product Product id
>     * @param int $id_product_attribute Product attribute id (optional)
>     * @param bool|null $cache_is_pack
> ```

Looks unsued

---

*[classes/Product.php, line 3602 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5OLrKWKr5A9-AVoPLB:-L5OLrKWKr5A9-AVoPLC:b-3yd6kz) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Product.php#L3602)):*
> ```PHP
>         $availableQuantity = StockAvailable::getQuantityAvailableByProduct($id_product, $id_product_attribute);
>         $nbProductInCart = 0;
>         $cart = Context::getContext()->cart;
> ```

Why not pass the cart as a parameter? There's no cart in the BO, and it would be easier to test

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 44 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5ONBwyk5JaQDYf0W7Y:-L5ONBwyk5JaQDYf0W7Z:b-6xkizr) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L44)):*
> ```PHP
>         $nbProduct = \Product::getQuantity($idProductInPack);
>         $this->assertEquals(5, $nbPack);
>         $this->assertEquals(50, $nbProduct);
> ```

You should try to avoid having more than one assertion per test.
This will push you to write more descriptive tests, like "testNumberOfAvailablePacksIsCorrect", "testNumberOfAvailableProductsIsCorrect".

If you launch phpunit with the parameter `--testdox` you'll have a nice checked list like this:

```
$ phpunit --testdox BankAccountTest
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

AddPack
 [x] Number of available packs is correct
 [x] Number of available products is correct
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by alegout** [comment]
Review status: 6 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[classes/Pack.php, line 206 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5O4C2pqE43QcYwlmGa:-L5iunfWiLwHDz_6e0QW:b-x8g9j1) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Pack.php#L206)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Looks unused
</blockquote></details>

Herited from Product::getQuantity()

---

*[classes/Product.php, line 3592 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5OLkIRmcCTCBDdTGa6:-L5iuu3dFTJ49DHWSmem:b-x8g9j1) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Product.php#L3592)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Looks unsued
</blockquote></details>

Herited from Product::getQuantity()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by alegout** [comment]
Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by alegout** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[classes/Pack.php, line 177 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5O3mvduB3zsiP-sPKa:-L5j5DDJ90p8lbjtH7U4:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Pack.php#L177)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

This should be given, not inferred from global values
</blockquote></details>

Done.

---

*[classes/Pack.php, line 212 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5O2tlv85GwE4m1kX1H:-L5jAyJDXDiV3uH4sDqB:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Pack.php#L212)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why not pass the cart as a parameter? There's no cart in the BO, and it would be easier to test
</blockquote></details>

Done.

---

*[classes/Product.php, line 3602 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5OLrKWKr5A9-AVoPLB:-L5jAzxmnwpNNJthfGNq:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/classes/Product.php#L3602)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Why not pass the cart as a parameter? There's no cart in the BO, and it would be easier to test
</blockquote></details>

Done.

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 44 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L5ONBwyk5JaQDYf0W7Y:-L5tIspLrN9L2WMUsPVX:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/d2e47bce4863412ec934690e908213bbdbd99b8b/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L44)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should try to avoid having more than one assertion per test.
This will push you to write more descriptive tests, like "testNumberOfAvailablePacksIsCorrect", "testNumberOfAvailableProductsIsCorrect".

If you launch phpunit with the parameter `--testdox` you'll have a nice checked list like this:

```
$ phpunit --testdox BankAccountTest
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

AddPack
 [x] Number of available packs is correct
 [x] Number of available products is correct
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by alegout** [comment]
Currently implementing pack stock type for Pack::getQuantity and Pack::isInStock functions.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-:-L5uDR76PVcX6aDXOIig:b-221zau)*

**Comment by alegout** [comment]
done, waiting for review

**Comment by eternoendless** [comment]
Reviewed 1 of 8 files at r3, 1 of 1 files at r6, 14 of 14 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 84 at r7](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L6bhIitFYJO7hepzUvI:-L6bhIitFYJO7hepzUvJ:bxxzk5m) ([raw file](https://github.com/prestashop/prestashop/blob/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L84)):*
> ```PHP
>         $nbProduct = \Product::getQuantity($this->productInPack->id);
>         $this->assertEquals(5, $nbPack);
>         $this->assertEquals(50, $nbProduct);
> ```

You can use PHPUnit data providers to avoid repeating code on your tests

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 209 at r7](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L6bhjlkeP926EOHYy9s:-L6bhjllOrj_kRkd-izi:b-eviirn) ([raw file](https://github.com/prestashop/prestashop/blob/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L209)):*
> ```PHP
>         $this->assertFalse(\Pack::isInStock($this->pack->id, 2, $this->cart));
>         $this->assertTrue(\Pack::isInStock($this->pack->id, 1, $this->cart));
>         $this->resetCart();
> ```

Maybe `$this->resetCart();` should be done in a `tearDown()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by eternoendless** [comment]
Almost there!!

**Comment by alegout** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[classes/Pack.php, line 34 at r8](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L6bm_6uIcV8u5Y8ZgFj:-L6bm_6uIcV8u5Y8ZgFk:bhhfz8j) ([raw file](https://github.com/prestashop/prestashop/blob/8d4f9141c72eefa32973da8ba147d0687bf8c614/classes/Pack.php#L34)):*
> ```PHP
>      * @var string
>      */
>     const STOCK_TYPE_PACK_ONLY = 0;
> ```

my mistake sorry :)

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 84 at r7](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L6bhIitFYJO7hepzUvI:-L6blNCXR0uQsTKTpZZK:bsf3ab) ([raw file](https://github.com/prestashop/prestashop/blob/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L84)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You can use PHPUnit data providers to avoid repeating code on your tests
</blockquote></details>

Not useful in this case i though

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 209 at r7](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L6bhjlkeP926EOHYy9s:-L6bmGJ-V66IRfmij01C:bfaxmcq) ([raw file](https://github.com/prestashop/prestashop/blob/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L209)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Maybe `$this->resetCart();` should be done in a `tearDown()`?
</blockquote></details>

already done, but i need to reset cart before each pack type test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by alegout** [comment]
Yes almost! :)

**Comment by eternoendless** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[tests/Unit/Core/Cart/Adding/Product/AddPackTest.php, line 84 at r7](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-L6bhIitFYJO7hepzUvI:-L6bnZzXVZfU3jj0oz8B:b9tghpt) ([raw file](https://github.com/prestashop/prestashop/blob/64e6f9e1d4068bd1ebab78c089e08d16c928fcd9/tests/Unit/Core/Cart/Adding/Product/AddPackTest.php#L84)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Not useful in this case i though
</blockquote></details>

I see the same 5 lines repeated 3 times, that's what data providers are for :)
Not blocking though

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Comment by eternoendless** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607#-:-L6bnwKb55mLoQyZ3m4C:bg7igkv)*

**Review by eternoendless — DISMISSED** [review]

**Comment by marionf** [comment]
I have the same issue as before:
If I add first 50 products A and try to add 5 packs B, I can't -> It's ok
But if I add first 5 packs B and try to add 50 products A, it works while it shouldn't

**Comment by eternoendless** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8607)*

**Review by eternoendless — APPROVED** [review]

**Comment by marionf** [comment]
@alegout 
I choose to decrement pack only.
I add 5 products B & I try to add 50 products A -> I can, it's ok
I add 50 products A & I try to add 5 products B -> I can't, it's not ok It should be possible

**Comment by marionf** [comment]
It's ok for me, thanks you @alegout

**Comment by eternoendless** [comment]
Thank you @alegout 🎉

**Pull request merged**
