### PR TITLE
[-] CORE : Correct fatal error with php7

### PR DESCRIPTION
**Pull request by sfroment**
follow up of #3588

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @sfroment, please describe how you can display this fatal error.

**Comment by jd440** [comment]
are you planning to merge it on PS1.6.x?

**Comment by mickaelandrieu** [comment]
@jd440 for now, we are focused on 1.7 branch. I add the tag "cherry-picked"

**Comment by jd440** [comment]
but 1.6.1.9 are claim as "PHP 7 is now fully supported" ?

**Comment by Eolia** [comment]
@jd440 Welcome to the world of Care Bears :)

**Comment by julienbourdeau** [comment]
@jd440 Can you point me where you read that ?

**Comment by Eolia** [comment]
@julienbourdeau Here: http://build.prestashop.com/news/prestashop-1614-maintenance-release/

**Comment by jd440** [comment]
@julienbourdeau http://build.prestashop.com/news/prestashop-1614-maintenance-release/

```

> Here are the changes that 1.6.1.4 brings:
> 
>     PHP 7 is now fully supported

```

**Comment by jd440** [comment]
are you planning to launch 1.6.1.6?
Would you integrate something as 
`if (PHP_MAJOR_VERSION < 7){
 	if (!Validate::$function($value)) {
        	$this->_errors[] = sprintf(Tools::displayError('The field %1$s (%2$s) is invalid.'), call_user_func(array($className, 'displayFieldName'), $field, $className));
	}           
else {
	if (!Validate::{$function}($value)) {
        	$this->_errors[] = sprintf(Tools::displayError('The field %1$s (%2$s) is invalid.'), call_user_func(array($className, 'displayFieldName'), $field, $className));
        }
}`

Which must be compatible PHP 5.2 -> PHP7

**Comment by xBorderie** [comment]
@jd440: Pull requests for v1.6.1.6 are being gathered here: https://github.com/PrestaShop/PrestaShop/milestones/1.6.1.6
If you feel like implementing this code, please submit your PR for consideration!
Thank you!

**Comment by Eolia** [comment]
@sfroment Please re-submit another time your PR (3th)...

**Comment by sfroment** [comment]
will be done tomorrow

**Comment by sfroment** [comment]
@Eolia Updated !

**Comment by sfroment** [comment]
@xBorderie @Eolia @jd440 @mickaelandrieu Could we get some news cause you can merge the PR it won't break compat with php 5.x !

**Comment by mickaelandrieu** [comment]
@sfroment I need a reproducible test case ping @Shudrum

**Comment by Eolia** [comment]
@mickaelandrieu :https://www.prestashop.com/forums/topic/494424-prestashop-16-with-php-70-experience-problems-solutions/
https://www.prestashop.com/forums/topic/523487-ps-et-php7-pas-compatible/
https://www.prestashop.com/forums/topic/512327-importar-csv-no-funciona-con-php-7-en-versiones-1611-1613-1614/
https://www.prestashop.com/forums/topic/496726-prestashopexception-property-customer-lastname-is-empty-php-7/
https://www.prestashop.com/forums/topic/516124-fatal-error-with-minicsliderphp/

**Comment by Shudrum** [comment]
Hi!

Thank you @sfroment! But we avoid to test the php version. There is a simple solution just by assigning another var just before.

This will be fixed, but not this way.

Thank you again.

**Comment by firstred** [comment]
I have touched the code (before this changeset) with PHP 7.0.6, but couldn't reproduce the fatal error.

However, with PHP <= 7.0.4 I did notice the following problems:
- Random memory leaks after roughly a week when using Apache + `mod_php`
- or the opposite, a garbage collector which removes the variables way too soon (dafuque)
Those caused fatal errors or missing classes errors

**Comment by sfroment** [comment]
Sorry I can't help you on this one I just update my PR that was done when the php7 rc1 was released http://php.net/archive/2015.php#id2015-08-21-1 ...

**Comment by Shudrum** [comment]
No problem @sfroment, thank you :)

**Comment by antoin-m** [comment]
Hi @sfroment, thank you for your contribution!

It seems to me that both syntaxes are working on all PHP versions : 
https://3v4l.org/tPqgG

Furthermore the tests run on travis with PHP 5.4, 5.6 and 7 so I think we would have seen the issue since then.
I'll close this PR but do not hesitate to open it again if you think it's still relevant.
Michel.

**Comment by sfroment** [comment]
Back in my time at prestashop we were supposed to support more than php 5.4 we were supporting 5.3 and 5.2 if I remember well and on those versions the change is needed this PR as almost a year...

**Comment by antoin-m** [comment]
You're right PHP 5.3 and 5.2 won't work without this PR but as of PrestaShop 1.7 we only support PHP >= 5.4

**Comment by Dh42** [comment]
What does it say about how serious PrestaShop takes security when they insist on supporting insecure software?

**Comment by firstred** [comment]
@sfroment Have a look at this comment: https://medium.com/@JonSnow2/i-worked-sometimes-ago-as-core-developer-at-prestashop-in-the-french-team-e8e1a84a140#.norak62re

It will give you an idea as to why nothing gets done anymore.

I have no idea why the Pull Request section just hasn't been closed, yet.

**Pull request closed without merging**
