### PR TITLE
Made the Symfony error/exception handler availables in front office

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | We should enjoy the Symfony error/exception handlers in Front office too |
| Type? | new feature |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Easy, look for a bug in front office: WOW what a nice error page |

### CODE REVIEW

**Comment by kpodemski** [comment]
maybe it should based on `_PS_DEBUG_PROFILING_`?

**Comment by mickaelandrieu** [comment]
@kpodemski it's not the profiler from Symfony, only the error handler.

For the web profiler, I need a delay (and a complete migration to Symfony :p)

**Comment by kpodemski** [comment]
oh, ok

**Comment by Quetzacoalt91** [comment]
Woooo, how I feel with this pull-request: 

code refactoring

**Comment by mickaelandrieu** [comment]
How I feel now:

yoda

**Comment by mickaelandrieu** [comment]
Thanks @maximebiloe

**Comment by Quetzacoalt91** [comment]
maxresdefault

**Pull request merged**
