### PR TITLE
Fixed payment methods of carriers

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | enable paiement methos for every new added carrier
| Type?         | bug fix
| Category?     | BO

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by maximebiloe** [comment]
🙈

**Comment by rGaillard** [comment]
In case of multishop, it will doing the insertion only for the default shop in case of  all shops or shop group context. Shop::getContextListShopID() must be use.

**Comment by mickaelandrieu** [comment]
@rGaillard can you do the update please ? I'm not sure to understand what you want me to do.

**Comment by aleeks** [comment]
ping @rGaillard  https://github.com/PrestaShop/PrestaShop/pull/6909/commits/c79b2dbe84992e0f72ae47c22eb45f1fd7bbd461?w=1

**Comment by mickaelandrieu** [comment]
Thank you @aleeks :)

**Comment by maximebiloe** [comment]
Thank you!

**Pull request merged**
