### PR TITLE
Add availability component to FO

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We need to have an availability component to the FO
| Type?             | new feature
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #{issue number here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

# How does it looks?
image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25062)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Hi @NeOMakinG as you're working on a new theme, is this still needed?

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG as you're working on a new theme, is this still needed?

Yes because we maintain classic + This system will be in the new theme also

**Comment by kpodemski** [comment]
Hello @NeOMakinG 

In one of the other PRs, you said that adding new features to the Classic theme doesn't make sense. Is this PR still relevant? I mean the front-end part.

**Comment by NeOMakinG** [comment]
> Hello @NeOMakinG
> 
> In one of the other PRs, you said that adding new features to the Classic theme doesn't make sense. Is this PR still relevant? I mean the front-end part.

Kinda agree with this, but this PR has been created almost 1 year ago :p

Should we call the product team in order to decide?

**Comment by Hlavtox** [comment]
- We need to integrate this - https://github.com/PrestaShop/PrestaShop/issues/23534
- Extract theme code to classic repository
- Make the same in hummingbird repository

and merge it 👍 

____

And only thing left in the TODO will be the quantity, which will still be in the product details. But integrating that will require some BC and much more thought because the specs are no precise. But the front will be prepared at least. 👍

**Review by kpodemski — COMMENTED** [review]
@Hlavtox @NeOMakinG 

Hi guys, what about this PR? Is it still relevant for Hummingbird v1? Shall we prioritize it somehow?

**Comment by Hlavtox** [comment]
I will do a slimmed down version of it for hummingbird, further to evolve in v9. It will be a bit slimmer after rebase, I already implemented some things in other PRs. :-)

**Comment by kpodemski** [comment]
Thanks @Hlavtox - in that case, I'm closing this PR, I'm sure we'll use some of @NeOMakinG work from this one in the future 👍🏻

**Pull request closed without merging**
