### PR TITLE
[*] CORE : Remove migrate jquery plugin

### PR DESCRIPTION
**Pull request by gRoussac**

### CODE REVIEW

**Comment by kpodemski** [comment]
@gRoussac back in game? :P

**Comment by gRoussac** [comment]
Hey,

No non just migrating an 1.3.0.4 =)

**Comment by julienbourdeau** [comment]
Hi Greg,

Why it should be removed ?

I don't really understand the comment:
> added query migrate for compatibility with new version of jquery will be removed in ps 1.6

Was it supposed to be removed in 1.6 ?

**Comment by aleeks** [comment]
Hello @gRoussac ,
I'm closing this PR because, we are still with jquery 1.11 so we need this. (for BO at least)

Regards

**Pull request closed without merging**
