### PR TITLE
Remove deprecated admin endpoints

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed old deprecated endpoints, which allows to remove the tests-legacy suite
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | AFAIK there is nothing to test, the code wasn't used anymore
| Possible impacts? | Ancient code could be impacted by the BC break

## Removed admin endpoints:

- backup.php
- ajax_products_list.php -> redirected calls to the appropriate AdminProducts, but the updated code is probably not used anymore anyway
- displayImage.php
- drawer.php
- grider.php
- pdf.php
- searchcron.php

Removing these endpoints allowed me to remove their associated tests, which were the last in the tests-legacy directory.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27917)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
It looks OK but I would like @Quetzacoalt91 and @kpodemski to tell us if they think `backup` endpoint might still be used

**Comment by Quetzacoalt91** [comment]
At the time we deprecated it, we should have redirected calls from the core to new routes via Symfony.

If they are still used, this should be by external tools.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Hi @eternoendless, Thank you for your contribution.

Could you create a PR on devdocs for these BC and explain how migrate to old endpoints to new endpoints ?

**Comment by kpodemski** [comment]
@matks 

Some modules probably use those, but module developers have much more to update, so it's ok to have them removed.

**Comment by eternoendless** [comment]
@Progi1984 Maybe I can, but not before [this PR](https://github.com/PrestaShop/docs/pull/1315) has been merged...

**Review by Progi1984 — DISMISSED** [review]
@eternoendless The PR is now merged on devdocs. Could you add a linked PR on the devdocs : https://devdocs.prestashop.com/8/modules/core-updates/8.0/#removals ?

**Comment by eternoendless** [comment]
Here it is @Progi1984: https://github.com/PrestaShop/docs/pull/1334

But I think it's better to document them after the PR has been merged, otherwise I might find myself having to change the documentation again if for some reason my PR is not approved.

**Review by matks — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by atomiix** [comment]
Should we merge it?

**Comment by matks** [comment]
@atomiix I think either we merge it or request QA team to run automated campaign on it

**Review by Progi1984 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @eternoendless 

Thank you for your PR, I launch a run automated campaign on it, and it's ok

**Comment by Progi1984** [comment]
Thanks @eternoendless & @AureRita

**Pull request merged**
