### PR TITLE
Fixed deletion of attribute

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Deleting an attribute in the back-office should not raise an exception. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1386 |
| How to test? | Delete an attribute in the back-office |

### CODE REVIEW

**Comment by kpodemski** [comment]
I think it should be done via `ObjectModel`? Overall i'm confused by this PR, it should be done automatically, if you delete something from `ps_something` and you have relation with `ps_something_lang` everything from `ps_something_lang` should be deleted instantly, right?

**Comment by thierrymarianne** [comment]
It should but it is not happening that way here, hence this PR.

**Comment by kpodemski** [comment]
Nah, i'm not sure, we can agree that this is more like workaround than real solution.

@julienbourdeau @Shudrum ?

**Comment by kpodemski** [comment]
@thierrymarianne we should be looking for a relation between 
https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Entity/Attribute.php

and

https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Entity/AttributeLang.php

`cascade`? @mickaelandrieu ?

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by thierrymarianne** [comment]
@kpodemski Thank you for the hint, I've figured records in language table was deleted too late.

**Comment by kpodemski** [comment]
Weird :P something wrong with multi-store for Attributes then?

**Comment by thierrymarianne** [comment]
Foreign keys between `attribute` and `attribute_lang` enforces deletion of records in language table first.

**Comment by kpodemski** [comment]
Oh, cool, i hope that this change would not affect any other parts of the system!

**Comment by iTiaNex** [comment]
there is a problem when enable multi-store option,if the default shop of a product is not the global default shop (most conditions is shop 1 ),when generate attributes or move image positions,it can't initial a right  ObjectModel object,so it usually caused an error,

**Comment by maximebiloe** [comment]
Thank you!

**Pull request merged**
