### PR TITLE
Properly handle controller names without dash

### LINKED ISSUE #12518: Modules positions not works for pages with dash in url
It seems like module position stopped work for me in Prestahop 1.7.5, but only for pages with 2 or more words in url, like "new-products".

**To Reproduce**
Install clean Prestashop 1.7.5
Go to Design - Positions - take for example Newsletter subscription module in FooterBefore hook - click Edit - in list we can select "newproducts" - save.
Now go to new products page - module still there: https://gyazo.com/8bf46714cda5fa09b0c65f8928c982a6

Back to list of exceptions for this module, and type "new-products" (with dash):
https://gyazo.com/b1637c5c9065ceeeae9783be0fd3af76

Save, go to page - now module is hidden, as it should be.
https://gyazo.com/17ba7e660155e2215c34d6ff7e0d972f

By the way, it works for pages with one word urls, like "index" or "contact".

Also I have another 1.7.4.3, and it works normal with all pages.

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Fixes #12518
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12518
| How to test?  | follow instructions from ticket #12518

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12547)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @eternoendless, this fixes a regression of 1.7.5.0, is it too late to onboard it into 1.7.5.1?

**Review by mickaelandrieu — CHANGES_REQUESTED** [review]
Would you mind to add a comment with the link of the issue?

```php
/**
 * @see https://link-to-the-issue
 */
if(in_array(...
```

**Comment by kpodemski** [comment]
@mickaelandrieu done

**Comment by eternoendless** [comment]
Since this is a regression, do we know which change introduced the issue?

**Comment by kpodemski** [comment]
@eternoendless i didn't check it but on Design -> Positions -> Transplant module controllers are no longer using original names, like, 'new-products', by looking into:
https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/langs/en/data/meta.xml

i see that there are pages with dashes in names but i'm not sure if meta.xml is used in 1.7 installer tbh :D

**Comment by kpodemski** [comment]
by going futher, `PREFIX_meta` has controllers with proper names

**Comment by colinegin** [comment]
Hello @kpodemski, I think @mickaelandrieu had had some comments about your PR, are you able to make those changes and make your PR on the develop branch ?

Thanks a lot !

**Comment by kpodemski** [comment]
@eternoendless @colinegin 

shall i redo this PR on different branch? this is still an issue

**Comment by colinegin** [comment]
Hello @kpodemski , thanks for writing back !
Yes indeed could you redo your PR on develop branch ?

Thanks a lot !

**Pull request closed without merging**
