### PR TITLE
Fix fatal on array_merge if query in addMissingProductFields returns no result

### PR DESCRIPTION
**Pull request by jocel1**
Change the query to make a LEFT JOIN on product_lang instead of an INNER JOIN

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fatal error when a product has no associated translation in the current language
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a product without any corresponding entry in product_lang and try to display it

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8600)

### CODE REVIEW

**Comment by jocel1** [comment]
TODO : add tests!

**Review by eternoendless — APPROVED** [review]
LGTM

**Comment by prestamodule** [comment]
@mickaelandrieu @eternoendless @jocel1 Replacing `INNER JOIN` by `LEFT JOIN` is causing a **big issue** here.
Every product of the catalog is returned by the query.
This is causing missing translations (for example) if the first row of the result isn't the current id_product we are looking for.

Guess `$sql` should be edited like this:

```php
$sql = "SELECT
                    p.*,
                    pl.*,
                    sa.out_of_stock,
                    IFNULL(sa.quantity, 0) as quantity,
                    (DATEDIFF(
				p.`date_add`,
				DATE_SUB(
					'$now',
					INTERVAL $nbDaysNewProduct DAY
				)
			) > 0) as new
                FROM {$prefix}product p
                LEFT JOIN {$prefix}product_lang pl
                    ON (pl.id_product = p.id_product
                    AND pl.id_shop = $idShop
                    AND pl.id_lang = $idLang)
                LEFT JOIN {$prefix}stock_available sa
                    ON (sa.id_product = p.id_product
                    AND sa.id_shop = $idShop)
                WHERE p.id_product = $idProduct";
```

You can notice the issue by using this sample (try with id_product > 1) :

```php
$assembler = new ProductAssembler(Context::getContext());
$product = $assembler->assembleProduct(array('id_product' => 2));
```

Just look at `$product` array and especially lang columns that are null.

**Comment by jocel1** [comment]
Hi @prestamodule,

You're 100% right, the p.id_product = $idProduct should have been in the WHERE from the beginning, sorry about it!

**Comment by mickaelandrieu** [comment]
hello @jocel1, any chance to provide a patch next week?

**Comment by jocel1** [comment]
@mickaelandrieu Unfortunately next week will not be possible, I've already provided a patch this week :trollface: 
https://github.com/PrestaShop/PrestaShop/pull/9188

**Pull request merged**
