### PR TITLE
Refactoring of the upgrade, to be easily usable in the auto upgrade module

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Refactoring of the upgrade, to be easily usable in the auto upgrade module
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | Try to upgrade from an older version

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
I think the commit name issue is just the space before ":" :)

**Comment by jocel1** [comment]
Hi Xavier!
Yes, I'll rebase it anyway once Alex/Maxime start the review

**Comment by kpodemski** [comment]
Hello guys, i'm worried about one thing, is upgrader no longer ajaxed? it is import due to fact that very often we need to upgrade huge databases with a lot of data, or this PR is focused on "manual upgrade" method, not `autoupgrade` module at all?

**Comment by jocel1** [comment]
Actually it's the opposite :) The work here is made to be used by both the manual upgrade and the autoupgrade module (so all the upgrade stuff is centralized in one place).

You can check the related autoupgrade PR which uses this work : https://github.com/PrestaShop/autoupgrade/pull/49/files

**Comment by kpodemski** [comment]
@jocel1 i'm so happy to see it, great job

**Comment by maximebiloe** [comment]
Thank you @jocel1

**Pull request merged**
