### PR TITLE
Fixed bug on increase/decrease quantity. Remain invalid vouchers discounts.

### PR DESCRIPTION
**Pull request by sete391**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Bug Fix on increase/decrease qty. Remain invalid vouchers.
| Type?         | Bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Create a voucher (with voucher code empty) with 10% discount and priority 2. Create another voucher (with voucher code empty) with 15% discount and priority 1, with 2 units as minimal quantity. Create a manual order and add 1 product. 10% discount is applied (OK). Increase quantity. Voucher changes, 15% discount is applied (OK). Decrease quantity. Voucher remains, 15% discount is applied. It's wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8528)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hello @sete391, in order to make the approval of your PR faster & easier, please take some to fill the table in the description input.

That's really important for us, it allows us to reproduce the issue and validate your fix.
Thank you

**Comment by sete391** [comment]
Sorry. Done!

**Comment by Quetzacoalt91** [comment]
Perfect :ok_hand:

**Review by mickaelandrieu — APPROVED** [review]

**Comment by marionf** [comment]
Hello @sete391 

I can't reproduce your issue
screenrecord41

Can you give me more details to reproduce it ?

Thanks !

**Comment by sete391** [comment]
Sorry, it happens in a BackOffice order. I said manual order but I mean a BackOffice order

**Comment by marionf** [comment]
Hello @sete391 

Following the PR #9036, can you rebase please ?

**Comment by MathiasReker** [comment]
What is status in this?

**Comment by sete391** [comment]
> What is status in this?

Too old and rebase errors... Please, go to https://github.com/PrestaShop/PrestaShop/pull/10465

**Pull request closed without merging**
