### PR TITLE
fix(duplicate-product-customization): duplicate product in cart with …

### LINKED ISSUE #35478: BO - Order Creation - Customizable product with same customization can be added to an order individually
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I add a product with customization to an order, when the same customization is added, it should not add another product, but it should increase the quantity of the existing product.

https://github.com/PrestaShop/PrestaShop/assets/16019289/e7eb0a1a-5177-44d9-8fbe-d958d37b162c

### Expected behavior

Exact same customization should be detected and stacked.

### Steps to reproduce

1. Go to BO > Orders > Add an order > Choose Customer
2. Choose "Customizable mug" > Add a Customization "hello" > Add to cart
3. Click again on Add to cart
4. 2 entities of the same products with the same custom are added :x: 

### PrestaShop version(s) where the bug happened

8.1.3, develop

### PHP version(s) where the bug happened

8.1.27

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Symcon GmbH

### PR DESCRIPTION
**Pull request by TheoAlloin**
…the same customization text

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | When I add a product with customization to an order, when the same customization is added, it should not add another product, but it should increase the quantity of the existing product.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See related issue
| Fixed issue or discussion?     | Fixes #35478 
| Sponsor company   | Softizy

### CODE REVIEW

**Review by Hlavtox — COMMENTED** [review]
It doesn't seem right to me, there can be the same product with multiple customizations in the cart.

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Blocking because it's an expected behavior.

**Review by matthieu-rolland — COMMENTED** [review]
I'll also block this PR until we have confirmation this is an actual bug 

(nonetheless thank you @TheoAlloin for contributing !)

**Review by matthieu-rolland — COMMENTED** [review]
@MatShir & @kpodemski do you guys agree that this is not a bug ?

**Review by kpodemski — CHANGES_REQUESTED** [review]
As much as I appreciate your contribution, @TheoAlloin , I think this can lead to unexpected behavior for a bit of gain.

**Comment by TheoAlloin** [comment]
Hi, should i close the PR?

**Comment by MatShir** [comment]
I trust @kpodemski and @Hlavtox about the impact and side effects that such a minor change can bring. I think for now we can live with this bug around, I'm closing the PR and the issue. 
Thanks anyway @TheoAlloin 🤗

**Pull request closed without merging**
