### PR TITLE
Fixed store selection on product creation

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Fix store selection in back-office |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Log in to the back-office, activate multistore, create a new store and go to Catalogue > Product in order to create product belonging to the newly created store |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
This need a rebase :)

**Comment by Shudrum** [comment]
Hi! Perfect for me but … Can you remove the compiled assets from your pull request please?

```
admin-dev/themes/new-theme/public/bundle.js
admin-dev/themes/new-theme/public/theme.css
```

Thank you!

**Comment by thierrymarianne** [comment]
@Shudrum Both CSS and JS compiled files have been removed from this PR.

**Comment by Shudrum** [comment]
Thank you!

**Pull request merged**
