### PR TITLE
Create robots.txt

### PR DESCRIPTION
**Pull request by txmodxoops**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Creates robots.txt file for search engine indexing. |
| Type? | new feature |
| Category? | CO |
| BC breaks? | yes |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Use Google Webmaster to validate the file using indexing request section. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by txmodxoops** [comment]
Issues v 1.6.1.6:

PHP Warning: Missing argument 1 for ShoppingFluxExport::getIp(), called in /modules/shoppingfluxexport/shoppingfluxexport.php on line 1501 and defined in /modules/shoppingfluxexport/shoppingfluxexport.php on line 2000

**Comment by julienbourdeau** [comment]
I'm a bit lost, why are you talking about shopping flux?

**Comment by txmodxoops** [comment]
If indexing shopping on google webmaster, requires a robots.txt file, I 
thought it was important


Il 19/07/2016 09.32, Julien Bourdeau ha scritto:

**Comment by mickaelandrieu** [comment]
Still, you need to complete the pull request table.

**Comment by txmodxoops** [comment]
I think they can not do anything else, you could copy the contents of the file and re-create it?

**Comment by mickaelandrieu** [comment]
You only need to edit your pull request description and update the answers according to @prestonbot comments.

**Comment by txmodxoops** [comment]
OK... now it is correct?

**Comment by mickaelandrieu** [comment]
@txmodxoops thanks for update, I've completed your description.

Mickaël

**Comment by mickaelandrieu** [comment]
Bonjour

**Comment by txmodxoops** [comment]
Thanks

**Comment by mickaelandrieu** [comment]
Reviewed ;) thank you @txmodxoops

**Pull request merged**
