### PR TITLE
Fix: [BO] : Error notification displayed in Multistore page

### LINKED ISSUE #32654: Warning on the Cart Rules creation/editing page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When accessing the cart rule creation/modification page, the following warning appears:
```
Warning on line 81 in file XXX\classes\Smarty\SmartyLazyRegister.php
[2] end(): Argument #1 ($array) must be passed by reference, value given
```

I attach a video.

https://github.com/PrestaShop/PrestaShop/assets/2463965/cbabeec0-3161-44de-a580-59e845831d77

### Expected behavior

_No response_

### Steps to reproduce

1. In admin go to Catalog > Discounts
2. Click on **Add new cart rule**
3. The warning is displayed

### PrestaShop version(s) where the bug happened

8.0.4, 8.1.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### LINKED ISSUE #32680: [BO] : Error notification displayed in Multistore page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After installing the PS 810 RC version and activating the multistore option, go to the multistore page, an error notification is displayed

### Expected behavior

No error or exception should be visble 

### Steps to reproduce

1. Enable MultiStore 
2. Go to MultiStore Page 
3. See the Error 

The result With PS PS 810-rc , PS 81x  
image

The result with Develop 

image

### PrestaShop version(s) where the bug happened

PS 810-rc , PS 81x 

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      |After installing the PS 810 RC version and activating the multistore option, go to the multistore page, an error notification is displayed
| Type?             | bug fix
| Category?         | BO
| Fixed ticket?     | Fixes #32680 and #32654
| Sponsor company   | Codencode snc

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Isn't it a duplicate of https://github.com/PrestaShop/PrestaShop/pull/32715/ ?

**Comment by Codencode** [comment]
> Isn't it a duplicate of #32715 ?

This is #32715

**Comment by matks** [comment]
Argh I meant https://github.com/PrestaShop/PrestaShop/pull/32699 XD I see you closed the other one

**Comment by Codencode** [comment]
> Argh I meant #32699 XD I see you closed the other one

Allright,
yes I had some problems so I closed the PR and recreated this new one.

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
looks good

**Review by jolelievre — APPROVED** [review]

**Review by AchrafKchaou1991 — APPROVED** [review]
Hello @Codencode 
I tested this PR with PS 8.0.x using PHP 8.1/7.4:

[Pr32715.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/6ad8c56e-c850-4e06-ab13-a909b2f38712)

The issue is well fixed :heavy_check_mark: 
The automated tests are OK :heavy_check_mark: 
https://github.com/AchrafKchaou1991/ga.tests.ui.pr/actions/runs/5112751531
PR :heavy_check_mark: 
Thank you

**Review by matks — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @Codencode !

**Pull request merged**
