### PR TITLE
Allows to set id_customization for cart row via webservices

### LINKED ISSUE #23570: [WS] [POST/PUT] Carts - id_customization is not propaged to DB
#### Describe the bug

id_customization is not propagated into DB via webservice/API POST or PUT /carts request

#### Expected behavior

Once I put correct id (not 0) into id_customizaiton, into POST or PUT request to endpoint /carts, this id should be stored into DB.

## 1. Create a cart: 
- **method: POST**
- **body:**

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
    <id_address_delivery>14</id_address_delivery>
    <id_address_invoice>14</id_address_invoice>
    <id_currency>1</id_currency>
    <id_customer>2</id_customer>
    <id_guest>42</id_guest>
    <id_lang>1</id_lang>
    <id_shop_group>1</id_shop_group>
    <id_shop>1</id_shop>
    <id_carrier></id_carrier>
    <recyclable></recyclable>
    <gift></gift>
    <gift_message></gift_message>
    <mobile_theme></mobile_theme>
    <delivery_option></delivery_option>
    <secure_key>5aa7510184d3eb0a9f550af2456ee182</secure_key>
    <allow_seperated_package></allow_seperated_package>
    <date_add></date_add>
    <date_upd></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product>19</id_product>
          <id_product_attribute>0</id_product_attribute>
          <id_address_delivery>14</id_address_delivery>
          <id_customization></id_customization>
          <quantity>1</quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```
## 2. Create a customization
- **method: POST**
- **body:**
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <customization>
    <id_address_delivery>14</id_address_delivery>
    <id_cart>59</id_cart>
    <id_product>19</id_product>
    <id_product_attribute>0</id_product_attribute>
    <quantity>1</quantity>
    <quantity_refunded>0</quantity_refunded>
    <quantity_returned>0</quantity_returned>
    <in_cart>1</in_cart>
    <associations>
      <customized_data_text_fields>
        <customized_data_text_field>
          <id_customization_field>2</id_customization_field>
          <value>[WS] - test customization</value>
        </customized_data_text_field>
      </customized_data_text_fields>
      <customized_data_images></customized_data_images>
    </associations>
  </customization>
</prestashop>
```
## 3. Add the created customization to the cart
- **method: PUT**
- **body:**
```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
  <cart>
	<id>59</id>
    <id_address_delivery>14</id_address_delivery>
    <id_address_invoice>14</id_address_invoice>
    <id_currency>1</id_currency>
    <id_customer>2</id_customer>
    <id_guest>42</id_guest>
    <id_lang>1</id_lang>
    <id_shop_group>1</id_shop_group>
    <id_shop>1</id_shop>
    <id_carrier></id_carrier>
    <recyclable></recyclable>
    <gift></gift>
    <gift_message></gift_message>
    <mobile_theme></mobile_theme>
    <delivery_option></delivery_option>
    <secure_key>5aa7510184d3eb0a9f550af2456ee182</secure_key>
    <allow_seperated_package></allow_seperated_package>
    <date_add>2021-03-16 15:56:18</date_add>
    <date_upd></date_upd>
    <associations>
      <cart_rows>
        <cart_row>
          <id_product>19</id_product>
          <id_product_attribute>0</id_product_attribute>
          <id_address_delivery>14</id_address_delivery>
          <id_customization>10</id_customization>
          <quantity>1</quantity>
        </cart_row>
      </cart_rows>
    </associations>
  </cart>
</prestashop>
```
### The customization id is not saved => NOK
ERROR: Directly in response I receive 0 in id_customization, instead of 14. 
And also in DB is stored 0 in table ps_cart_product in columnt id_customization

#### Additional information

* PrestaShop version: 1.7.7.2 and also 1.7.6.5
* PHP version: 7.3.27

### PR DESCRIPTION
**Pull request by webeshop**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allows to set id_customization for cart row via webservices
| Type?             | improvement
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23570
| How to test?      | See #23570
| Possible impacts? | Cart webservices

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Hello @webeshop thank you for tou PR

Can you edit the description of the PR with the good branch `develop` for the label

**Review by MeKeyCool — APPROVED** [review]

**Comment by NeOMakinG** [comment]
> Hello @webeshop thank you for tou PR
> 
> Can you edit the description of the PR with the good branch `develop` for the label

I would also say, please write the way to test this PR, in the current state, you can only guess it by reading the code, while the QA shouldn't need to read the code to test the PR.

**Comment by webeshop** [comment]
> > Hello @webeshop thank you for tou PR
> > Can you edit the description of the PR with the good branch `develop` for the label
> 
> I would also say, please write the way to test this PR, in the current state, you can only guess it by reading the code, while the QA shouldn't need to read the code to test the PR.

Hello @NeOMakinG, 

there is full info and way to test this PR. 
https://github.com/PrestaShop/PrestaShop/issues/23570

**Comment by NeOMakinG** [comment]
> > > Hello @webeshop thank you for tou PR
> > > Can you edit the description of the PR with the good branch `develop` for the label
> > 
> > 
> > I would also say, please write the way to test this PR, in the current state, you can only guess it by reading the code, while the QA shouldn't need to read the code to test the PR.
> 
> Hello @NeOMakinG,
> 
> there is full info and way to test this PR. #23570

Updated the description

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team QA by a dev?

**Review by FabienPapet — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @webeshop 

Thanks for your PR :rocket: 
LGTM, QA :heavy_check_mark: 
The customization with its value has been well saved :heavy_check_mark: 

image

The cart has been well updated :heavy_check_mark: 
image

And thanks to this PR I found a major regression on develop #30180 :pray: 

Thanks!

**Review by hibatallahAouadni — APPROVED** [review]
Hello @webeshop 

Thanks for your PR :rocket: 
LGTM, QA :heavy_check_mark: 
The customization with its value has been well saved :heavy_check_mark: 

image

The cart has been well updated :heavy_check_mark: 
image

And thanks to this PR I found a major regression on develop #30180 :pray: 

Thanks!

**Pull request merged**
