### PR TITLE
Remove system-specific entries from gitignore

### PR DESCRIPTION
**Pull request by tom-combet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | System-specific files, like IDE configuration and generated ones by OS, shouldn't be ignored in the repository but on the developer side (in a [global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) for example).
| Type?             | refacto
| Category?         | PM
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | Related to #28614.
| How to test?      | N/A
| Possible impacts? | N/A

### Breaking changes

- System-specific files will no longer be ignored, developers will have to ignore them themselves.

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by atomiix** [comment]
@PrestaShop/qa-team I guess there is no need to test something here, we can merge it?

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @atomiix 

We @PrestaShop/qa-team think that we should run the automated tests on this PR before being merged.

Thank you!

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @atomiix 

Go for merge the PR, our best @PrestaShop/qa-automation confirmed that no QA is needed.

Thank you!

**Comment by atomiix** [comment]
Thanks @tom-combet!

**Comment by zuk3975** [comment]
btw if someone needs - to ignore git files globally after this PR (not sure if its the best practice, but it works for me):
- create your own .gitignore somewhere lets say `whateverpath/global-ignores/prestashop/.gitignore`
- write down your system specific files (the ones you want to ignore) into that .gitignore like usually - e.g. `.idea/`
- run following command: `git config --global core.excludesfile whateverpath/global-ignores/prestashop/.gitignore`

should be good to go :heavy_check_mark:

**Comment by tom-combet** [comment]
Yes, it is actually the best practice, as pointed out by @kpodemski : https://github.com/PrestaShop/PrestaShop/pull/28614#issuecomment-1140269427. I'll link the gist in the description PR.

**Pull request merged**
