### PR TITLE
Travis cache is now used

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Use the cache of travis to cache the composer dependancies |
| Type? | Improvement |
| Category? | Tests |
| BC breaks? | Nope |
| Deprecations? | Nope |
| How to test? | A cache should appear in the Travis dashboard |

capture du 2016-05-12 11-44-30

### CODE REVIEW

**Comment by jocel1** [comment]
Does it change anything ? I thought the cache was used by travis only if sudo was disabled

**Comment by Quetzacoalt91** [comment]
Hi @jocel1,

This is what I thought too, but it seems Travis changed the cache availability on its differents environments: https://docs.travis-ci.com/user/ci-environment/

I was sure "private" was only written before, and now I see "public & private".  In consequence, I add the composer folder to the cache to verify if a speed-up occurs.

**Comment by jocel1** [comment]
That would be really great!

**Comment by jocel1** [comment]
Indeed : https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Comment by Shudrum** [comment]
Let's try it!

**Pull request merged**
