### PR TITLE
Use proper variable for checking category active

### LINKED ISSUE #26406: Category breadcrumb error
#### Describe the bug

When the breadcrumbs are loaded on a category page you get the following error:
```
Notice: Undefined variable: category
```

It has something to do with:
https://github.com/PrestaShop/PrestaShop/blob/develop/controllers/front/listing/CategoryController.php#L253

`$category` is called instead of `$this->category`.

#### Expected behavior

Load the category page without an error

#### Steps to Reproduce

1. Create a category who hasn't a parent and isn't a root category
2. Make the category active
3. Access the category page

image

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/26406
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26406
| How to test?      | Can't really reproduce but the code is wrong. 😄
| Possible impacts? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26414)

### CODE REVIEW

**Review by alexandrebru83 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
It works only because of luck :sweat_smile: When reaching all parents, the latest element is the current category, or is active.
But yes the code is wrong, we can merge without QA

**Comment by Hlavtox** [comment]
@PierreRambaud Rethorical question - is the variable in the loop created, if the array that its looping is empty? :D

**Comment by PierreRambaud** [comment]
> @PierreRambaud Rethorical question - is the variable in the loop created, if the array that its looping is empty? :D

Nope, the variable is not created, but without parent, this condition is never true `$this->category->id_parent != 0 && !$this->category->is_root_category` so it never checks the latest element ^^

**Review by tegbessou — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @Hlavtox

**Pull request merged**
