### PR TITLE
[*] Add DashboardModule class

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR, sorry for late reply.

I believe modules/dashgoals/dashgoals.php should not be among your commit https://github.com/PrestaEdit/PrestaShop/commit/e24352230c9b42f3674e57468fbdb847294e37a5 right ?

Thank you. Regards.

**Comment by PrestaEdit** [comment]
Hi Gregory,

I take some change to be up to date. The dashgoals module have to be update in another place.

I have set up to date this pull request to take care of consideration only what I wan't to do in int.

Best regards.

**Comment by PrestaEdit** [comment]
I dit the change here: https://github.com/PrestaShop/dashgoals/pull/11

**Comment by gRoussac** [comment]
Hi,

Thank you. There are still modules in your commit and they need to be changed in their own repo for dashgoal, not in the core because they are submoudles. BUT this would lead to modules here having minimum version 1.6.0.1, because DashboardModule would not exist in old cores. So i' m a bit embarassed here, this should have been done in 1.6.0.4 when you did your PR....

Regards

**Comment by PrestaEdit** [comment]
Not false, ... And so true for the last part. It's was in nov 2013, and it's sure that's not the same now.

I think, for the moment, we can close this PR and see what we can do for the the future, cause we will have a lot of problems with this one, it's true :)

**Pull request closed without merging**
