### PR TITLE
Fixed mixed up display in some cases at partial refunds

### PR DESCRIPTION
**Pull request by paeddl**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes a bug in display at the orders-view when creating a partial refund
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9195)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @paeddl, can you describe how a member from QA team can validate this contribution please?

**Comment by paeddl** [comment]
@mickaelandrieu 
- Create an order with for example a bundled product.
- Click on "partial refund" for this order
- Then you'll see a misaligned view like attached in the screenshot
bildschirmfoto 2018-06-21 um 11 46 19

**Review by mickaelandrieu — APPROVED** [review]

**Comment by marionf** [comment]
Hello @paeddl 

I can't reproduce your issue
From 1200 to 1855px I have this:

1855 a 1200px

Under 1200px I have this: 
moins 1200px

Can you tell me with which browser and which size of screen you have this issue ?

Thanks :)

**Comment by paeddl** [comment]
Hello @marionf 
I just tried locally and on a customers installation, it starts at a width of 1200px, and then it's always there, even if the window gets bigger. Browsers: Firefox and Chrome in latest versions.

**Comment by marionf** [comment]
All right, thank you @paeddl

**Comment by mickaelandrieu** [comment]
and merged! Thanks @paeddl

**Pull request merged**
