### PR TITLE
Replace Open Sans with Noto Sans

### PR DESCRIPTION
**Pull request by firstred**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | `develop`
| Description?  | Replace Open Sans with Noto Sans.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

This pull requests embeds a font in PrestaShop which can be compared to Open Sans, but contains a lot more glyphs in order to support many more languages out-of-the-box.

There are only a few small differences between the two: http://www.identifont.com/differences?first=Open+Sans&second=Noto+Sans

But the benefit is huge for international software such as PrestaShop: https://www.google.com/get/noto/ 
583 languages are supported!

Unsupported glyphs cause the browser to fall back on `sans-serif` and apply faux bold (or sometimes does not apply the style at all):
**Open Sans**
opensans

**Noto Sans**
notosans

(This is some weird combination of Dutch, English and Chinese, but you'll get the idea)

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @firstred,

Thanks for the font upgrade, it's a nice feature.
But the tests are failing, can you look at that, please?
Also, you're downgrading to Bootstrap 4 Alpha 2, can you make a `npm update` before compiling?

Regards.

**Comment by firstred** [comment]
Upgrade to alpha 5 ok as well? ^^

**Comment by maximebiloe** [comment]
We still need some work to do to be compatible with Alpha 5, so Alpha 4 is okay 😉

**Comment by firstred** [comment]
Okay, I'm seeing `No mixin named pull-right` with alpha 4 atm in `/css/components/cart.scss`. Do you know where I can get the mixin?

**Comment by firstred** [comment]
Oh, it should be replaced with `float-{size}-right`.

`float-xs-right` seems to cover all sizes (not sure?) and seems to be a good replacement for `pull-right`.

**Comment by firstred** [comment]
Nvm. It's just `float: right`

**Comment by maximebiloe** [comment]
Just lock on Alpha 4. We will migrate later to Alpha 5 or newer

**Comment by firstred** [comment]
Yep, I did, but the build was basically broken. Someone included `@pull-right`, even though that has been removed with Bootstrap 4.

Fixed now. Maybe the tests will pass this time, too.

**Comment by firstred** [comment]
Alright, it passes :smile:

**Comment by mickaelandrieu** [comment]
Thank you @firstred !

**Comment by firstred** [comment]
Nice, thanks y'all! :smile:

**Comment by xBorderie** [comment]
Cool!

**Comment by maximebiloe** [comment]
Hello @firstred,

You still have uses the Bootstrap 4 Alpha 5 (https://github.com/firstred/PrestaShop/blob/f9dbc200fd3f0e6bcfaf069281f7ef50cbc827e8/themes/classic/assets/css/theme.css#L2)
And we saw the first issue on the product page:
capture d ecran 2016-11-02 a 17 50 49

Can you make a new PR to rollback on Alpha 4, please? We will stay on this version until we will process all the removal and depreciations.

Thanks

**Comment by firstred** [comment]
Just use `npm i` and `webpack -p` ?

**Comment by firstred** [comment]
D'ohhh, it's that stupid `^`. Remove it from the version number in `package.json` if you want to lock the version!

**Comment by firstred** [comment]
@maximebiloe https://github.com/PrestaShop/PrestaShop/pull/6892

**Comment by maximebiloe** [comment]
Thanks @firstred, I just merged it.

**Comment by ProBackup-nl** [comment]
The [noto sans font has issues and needs a~~n upstream~~ fix](https://github.com/googlei18n/noto-fonts/issues/736). Backtick character + letter results in horizontal spacing that is way off. Instead of being displayed before the letter, the backtick ends up in or after the letter. Event at https://fonts.google.com/specimen/Noto+Sans

**Comment by ProBackup-nl** [comment]
@firstred Please update the Noto Sans web font files according to #11398 or mention the tool(s) you used to create the woff(2), eot, svg files from the source .ttf

**Pull request merged**
