### PR TITLE
Add the default language in AlternativeLangsUrl array

### PR DESCRIPTION
**Pull request by Gitwebpush**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add the default language in AlternativeLangsUrl array.
| Type?         |  improvement
| Category?     | FO 
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | None
| How to test?  | In the Front Office you have to inspect the source code and search for hreflang="x-default".

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20076)

### CODE REVIEW

**Comment by Progi1984** [comment]
@Gitwebpush  Thank you for your contribution. :hugs: 

Could you fill the table in your PR ?
Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Comment by Gitwebpush** [comment]
Done

**Comment by Progi1984** [comment]
@Gitwebpush I don't understand why you need the attribute `hreflang="x-default"` ? (It's why I asked you a new issue).

**Comment by Gitwebpush** [comment]
> @Gitwebpush I don't understand why you need the attribute `hreflang="x-default"` ? (It's why I asked you a new issue).

The hreflang="x-default" is used when no other language/region matches the user's browser setting. Google recommends to use hreflang x‑default.

**Comment by Progi1984** [comment]
Reference : https://webmasters.googleblog.com/2013/04/x-default-hreflang-for-international-pages.html

**Comment by matks** [comment]
Hi everyone,

It looks like this PR is not moving anymore. As mentioned in our [Maintainer Guide](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests), "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

I close this pull request as it seems stale and you might dont want to continue on it. If however you want to continue it, you can re-open 😉 .

Thank you!

**Pull request closed without merging**
