### PR TITLE
Fix: Useless redirection in the Customer Service page

### LINKED ISSUE #32423: Useless redirection in the Customer Service page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When you click in the "Pending Discussion Threads", your page reload.  

image

### Expected behavior

We can delete this comportement because it's useless 

### Steps to reproduce

Customer service > Customer service > Pending discussion threads

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | When you click in the "Pending Discussion Threads", your page reload.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #32423
| Sponsor company   | Codencode snc

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by kpodemski** [comment]
@FabienPapet remember about labels 👍🏻

**Review by djoelleuch — COMMENTED** [review]
Hello @Codencode ,

I have checked your PR , the issue is well fixed.
But automated tests are failed on [test (functional:BO:design, 8.1.x)](https://github.com/MhiriFaten/testing_pr/actions/runs/4915584404/jobs/8780168171#logs)

Ping @PrestaShop/qa-automation is it related to the PR ? 

Thank you.

**Comment by Codencode** [comment]
> Hello @Codencode ,
> 
> I have checked your PR , the issue is well fixed. But automated tests are failed on [test (functional:BO:design, 8.1.x)](https://github.com/MhiriFaten/testing_pr/actions/runs/4915584404/jobs/8780168171#logs)
> 
> Ping @PrestaShop/qa-automation is it related to the PR ?
> 
> Thank you.

Hi @djoelleuch,
thanks for the feedback.

Consider that my PR changes only one line of code, so it's probably a coincidence that the autotests fail.

**Review by djoelleuch — APPROVED** [review]
Hello @Codencode  , 

LGTM , Automated tests --> OK  (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4926001653/jobs/8800916260)

It's QA approved :heavy_check_mark: 

Thank you !

**Comment by kpodemski** [comment]
thank you @Codencode 👏🏻 

great to see so many contributions from you!

**Comment by Codencode** [comment]
> thank you @Codencode 👏🏻
> 
> great to see so many contributions from you!

It's a pleasure to help out when possible!

**Comment by Codencode** [comment]
@kpodemski,
will this change be added to future releases and therefore to the "develop" branch?

**Pull request merged**
