### PR TITLE
[*] CORE : Add $_GET & $_POST getter via getAllGetValues & getAllPost…

### PR DESCRIPTION
**Pull request by prestamodule**
…Values

Tools::getAllValues() may overwrite $_POST values because of $_GET merge.
- Direct usage of $_POST / $_GET is not allowed by the module validator.

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello,

Can you tell me in which cases do you have the same names for `$_POST` and `$_GET` values ?
This should not happen, I guess.

Regards.

**Comment by prestamodule** [comment]
Hi Maxime,

About same names, it could happen in some modules, my comment wasn't concerning the PS Core.

Direct usage of $_POST / $_GET is not allowed by the module validator, this is the main reason of our PR.
With theses methods, we could access both of them, separated, and know when the var is coming from a POST or a GET.
The current method does not allow us to make the difference and handle the data differently.


Regards,

**Comment by kpodemski** [comment]
:+1:

**Comment by maximebiloe** [comment]
I did understand that but why do you have the same parameters in the modules ?
Can't you avoid this ?

**Comment by prestamodule** [comment]
Another reason, i want to be able to generate some cache id depending on $_GET parameters in my module or application, but i want to ignore some keys (like UTM_* for example).
Actually, i must directly use $_GET because we don't have any alternative. We do not want to use $_POST values, it would pollute our cache id, we don't need it.

I've synchronized branch so tests can pass again.

BTW, if it could be applied to PS 1.6.1.5 it would be very nice for everyone.

**Comment by maximebiloe** [comment]
Hello,

We can't accept those getters, because you'll have the possibilities to access those variables easily with Symfony.
You just have to add those following lines : 
`use Symfony\Component\HttpFoundation\Request;`
`$request = Request::createFromGlobals();``
Then, just use the object `$request` to access to what you want (More info [here](http://symfony.com/doc/2.8/components/http_foundation/introduction.html))

Also, be careful for your future pull requests, you have a merge commit in it :wink:

Regards

**Pull request closed without merging**
