### PR TITLE
Fix order message not visible in admin

### LINKED ISSUE #9676: [BOOM-5292] Order in bo no longer display which employee created it
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5292).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Wed, 11 Apr 2018 14:22:19 +0200

### Describe the bug
Before in 1.6 version, in the message section we had the employee who created the order.
 It's not the case anymore in 1.7 version

If there is a problem with the order or payment you do not know who created the order, if you have a telephone pool to take orders you can not distribute the sales commissions according to the employees who created the telephone orders.

### Proposed solution

image

### Expected behavior
BO>Order should display which employee has created the Order in the Message block

**PS 1.6.1.20**
image

### Steps to reproduce

1. BO>SELL>Orders>Orders
2. Create an Order
3. Back to Order List
4. View the latest created order
5. Scroll donw to the Message block
6. See error > No info about the employee who created the order displayed in the message block

image

### Additional infos

- PS version: 1.7.8.5
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Order message that is passed as `$message` attribute (example - message about manual order) into `PaymentModule::validateOrder` method is not saved into a customer thread, thus not visible in order detail in backoffice. Standard order note was migrated from the legacy `Message` object into `CustomerThread`/`CustomerMessage`, but this one is not. While I was at it, I removed some unused code in PaymentModule.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Create order from backoffice and check that you can see both messages on order detail.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/9659035153 ✅ 
| Fixed issue or discussion?     | Fixes #9676
| Related PRs       | 
| Sponsor company   | 

### Known issues
Although the message is marked as private, it looks like any other message, because of styling issues. The styling of message that has `id_employee = 0` AND `private = true` will be resolved in another PR.

### How does it look
Snímek obrazovky 2024-05-31 185245

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @Hlavtox

**Review by FabienPapet — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Thanks for the PR !

I noticed an issue, when I create a manual order, i always have 2 messages displayed.

Screenshot 2024-06-25 at 11 54 24

https://github.com/PrestaShop/PrestaShop/assets/16019289/d1a37ea6-862a-4abe-99d9-04bbf23a2c2c

Could you check ? :)
Thanks!

**Review by tleon — APPROVED** [review]

**Comment by Hlavtox** [comment]
Don't do anything with this PR for now, I will need to consult this with someone, I don't think keeping two tables is good idea, it should be done properly...

**Comment by matks** [comment]
> Don't do anything with this PR for now, I will need to consult this with someone, I don't think keeping two tables is good idea, it should be done properly...

You can make it a draft then

**Pull request closed without merging**
