### PR TITLE
Added module productcomments (now compatible with PS 8.0)

### LINKED ISSUE #27040: productcomments is not compatible with PS 8.0
There is a dependency conflict when installing productcomments in PS 8:

Screenshot

Do not forget to check to reproduce the [bug #27007](https://github.com/PrestaShop/PrestaShop/issues/27129) after the compatibility update

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Added module productcomments (now compatible with PHP 8.0)
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27040
| How to test?      | The module `productcomments` is now available in Core.

Ping @boubkerbribri for tests.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27646)

### CODE REVIEW

**Review by PrestaEdit — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
@boubkerbribri this PR is aproved 👍

**Review by NeOMakinG — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Progi1984 ,

Thanks for the PR !

Tested on 8.0.0, module is well installed. Bug #27129 is tested and not reproduced.

I have encountered 2 issues.
- The rating is not displayed in the product page :
Screenshot 2022-02-17 at 11 17 11

It should be :
Screenshot 2022-02-17 at 11 12 33

- And it is not displayed in the Quick View either :
- 
https://user-images.githubusercontent.com/16019289/154455032-4cec000a-82ea-4f5d-8e15-ee1b3e9cb2ec.mov

Could you check please ?
Thanks !

**Comment by Progi1984** [comment]
@NeOMakinG & @PierreRambaud Fixed the bug on theme of @florine2623 :) If you have a small bunch of time for review

**Review by PierreRambaud — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Progi1984 ^^
Thanks for the update !

This is fixed indeed ✅ 



Sorry but I noticed something else : the rating is not displayed in the thumbnail of product ⛔ 

| What I should have | What I have |
| --- | --- |
| Screenshot 2022-03-04 at 14 47 53 | Screenshot 2022-03-04 at 14 48 35 |

Could you check ?
Thanks!

**Review by saulaski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 ,

Thanks for the update.

LGTM, QA ✅

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
