### PR TITLE
Remove hardcoded status filter in products list

### LINKED ISSUE #29204: BO - Product V2 - New product created with quick access is not displayed in the list
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

After enabling the "New product page" in the BO > Advanced Parameters > New & Experimental Features page.
When we create a product from quick access => The product is not displayed in the list of products

https://user-images.githubusercontent.com/16067358/181798247-b00aa0de-965e-4ee7-9c16-b353c338dd4a.mp4

With Product V1 => OK

### Expected behavior

_No response_

### Steps to reproduce

- [x] Case1

2. Go to BO > Advanced Parameters > New & Experimental Features page
3. Enable New product page - Single store and save
4. In the Quick access > click on New product 
5. Make some changes and save
6. Go to the Product list page
7. See error > the product is not displayed

- [x] Case2

1. Enable the multistore feature
2. Go to BO > Advanced Parameters > New & Experimental Features page
3. Enable New product page - Multi-store and save
4. In the Quick access > click on New product 
5. Make some changes and save
6. Go to the Product list page
7. See error > the product is not displayed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Product list did only show enabled products up until now. Fixed.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Closes #29204
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | refer to #29204
| Possible impacts? |

### CODE REVIEW

**Comment by FabienPapet** [comment]
Maybe duplicate of https://github.com/PrestaShop/PrestaShop/pull/29195 ?

**Comment by zuk3975** [comment]
> Maybe duplicate of #29195 ?

Might be related, but different. (my PR solves the issue that disabled products were not shown in list at all)

**Comment by FabienPapet** [comment]
I agree, but I found out that there are empty products with `state=0` created when you want to create a product without saving. (and then when you click on save, `state` is update from `0`to `1`

Removing that filter may cause some unwanted empty products to be shown.

**Review by matthieu-rolland — COMMENTED** [review]
Thanx @zuk3975 , two feedbacks:

1/ Are you sure that the problem is not that the product created from quick access has not its state set to 1 ?  Because if I'm not wrong, we don't want products with `state` set to `0` in the product list. It would display a product that has never been saved yet. (I think that's what @FabienPapet is talking about)

> Might be related, but different. (my PR solves the issue that disabled products were not shown in list at all)

I'm not sure the field `state` is for disabled product (there are also the `active` and `visibility` fields, so I could be wrong, this is all confusing...)


2/ Some behat tests would be nice so that we don't have this bug coming back 👍

**Comment by zuk3975** [comment]
> Thanx @zuk3975 , two feedbacks:
> 
> 1/ Are you sure that the problem is not that the product created from quick access has not its state set to 1 ? Because if I'm not wrong, we don't want products with `state` set to `0` in the product list. It would display a product that has never been saved yet. (I think that's what @FabienPapet is talking about)
> 
> > Might be related, but different. (my PR solves the issue that disabled products were not shown in list at all)
> 
> I'm not sure the field `state` is for disabled product (there are also the `active` and `visibility` fields, so I could be wrong, this is all confusing...)
> 
> 2/ Some behat tests would be nice so that we don't have this bug coming back +1

ahh i might confused state and "active" fields :thinking: good point, gonna double check it.

**Comment by zuk3975** [comment]
hey indeed i confused those 2. It was intentional to have p.state = 1 hardcoded as state is not the same as "active". So im closing this PR because it will probably be solved by https://github.com/PrestaShop/PrestaShop/pull/29195

**Pull request closed without merging**
