### PR TITLE
Fixed keywords disappear from search index

### PR DESCRIPTION
**Pull request by marionf**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Delete a product, and you delete words that is shared in search_word tabel, make other product disapear from search until next full reindex.
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8239
| How to test?  | See ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10859)

### CODE REVIEW

**Comment by marionf** [comment]
As #8587 is closed

**Review by jocel1 — DISMISSED** [review]
LGTM (thanks @Casper-O !)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by eternoendless** [comment]
Repushed for attribution... thanks @Casper-O

**Review by eternoendless — APPROVED** [review]

**Comment by niccoX** [comment]
These tickets which many are from 2016/17, are still waiting to be merged. Why are they not added into 1.6, but keep being stalled? Even the author of this ticked seems quite angry and even closed the ticket. Way to go!

**Comment by ttoine** [comment]
Hello @niccoX if you look at the recent releases of the 1.6.1.x, they were focused on security fixes.
When the team will have time again to release a 1.6 version for another reason that security, they will be able to work on this kind of pull request.

**Comment by niccoX** [comment]
> Hello @niccoX if you look at the recent releases of the 1.6.1.x, they were focused on security fixes.
> When the team will have time again to release a 1.6 version for another reason that security, they will be able to work on this kind of pull request.

Last update was 1 security fix.

**Comment by ttoine** [comment]
but this was a lot of work and tests with the reporter of the issue.
also, you don't count that 3 security versions of the 1.6 have been released recently.

**Comment by eternoendless** [comment]
Thanks @marionf

**Pull request merged**
