### PR TITLE
Add unit test for profile ID test

### PR DESCRIPTION
**Pull request by gavinkalika**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | NO
| Deprecations? | NO
| Fixed ticket? | [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16028)

### CODE REVIEW

**Comment by gavinkalika** [comment]
from https://github.com/PrestaShop/PrestaShop/pull/16028

@PierreRambaud here is the new branch

**Review by PierreRambaud — APPROVED** [review]

**Comment by gavinkalika** [comment]
cc @jolelievre

**Comment by matks** [comment]
Thank you @gavinkalika for increasing prestashop unit test coverage 👏

**Comment by gavinkalika** [comment]
@matks thanks. where can i go to make bigger contributions on this project?

**Comment by eternoendless** [comment]
Hi @gavinkalika, thanks for your contribution!
If you'd like to continue contributing, feel free to take on an bug, [there are plenty to choose from](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3ABug+label%3A%22To+Do%22) 🙂

**Pull request merged**
