### PR TITLE
CO: Using hyphen instead of underscores in suppliers and manufacturers urls

### PR DESCRIPTION
**Pull request by marrouchi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Using by default hyphen instead of underscores in suppliers and manufacturers urls
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8869
| How to test?  | Check Backend SEO config and Frontend suppliers and manufacturers pages are working correctly.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by aleeks** [comment]
If we do that on minor release, we can break all SEO of marchant isn't ? WDYT ?
@maximebiloe  @julienbourdeau @Shudrum @Quetzacoalt91 @xBorderie

**Comment by marrouchi** [comment]
@aleeks Yes, that's why i made this PR in this branch and not in 1.6, new installations can start with these new urls. We can add some rewrite rules to add 301 HTTP permanent redirection in htaccess (temporarily).

This is somehow crucial for SEO since search engines treats a hyphen as a word separator, but underscore is treated as a word joiner :
http://www.ecreativeim.com/blog/2011/03/seo-basics-hyphen-or-underscore-for-seo-urls/

**Comment by xBorderie** [comment]
Well, [Google does indeed recommend to use hyphens instead of underscores](https://support.google.com/webmasters/answer/76329?hl=en), but more [recent sources tend to show](https://moz.com/blog/15-seo-best-practices-for-structuring-urls) that [it doesn't matter anymore](https://www.seroundtable.com/google-doesnt-care-about-underscores-vs-dashes-in-urls-22180.html). [It seems to be more a readability issue](https://www.seomechanic.com/seo-101-hyphens-underscores-_-urls/) -- which I am all for, by the way, but using underscore hasn't prevented Wikipedia from ranking first for maaaaany search queries.

**Comment by marrouchi** [comment]
@xBorderie In my opinion, we cannot compare Wikipedia (who has a hundred other criterias that would lead to a better ranking) with a small e-commerce that would like to start doing business that relies heavily on SEO. In the other hand, why not follow the content or product pattern which already uses a prefix + dashes :) ?

**Comment by xBorderie** [comment]
Well, sure, your opinion is valid, but [so is the opinion of a Google Webmaster Trends Analyst](https://www.youtube.com/watch?v=YL4sdTcUJzo#t=1301) ;)

**Comment by maximebiloe** [comment]
We renamed `Manufacturers` into `Brands` in PrestaShop 1.7. @AlexEven what do you think about this URL rewriting?

**Comment by aleeks** [comment]
Hello @marrouchi  @maximebiloe  @marrouchi 
I'm closing this PR because of the reasons that were mentioned.
- SEO break
- Not translatable url
- Maybe it can be done in the shop's settings.

Regards

**Pull request closed without merging**
