### PR TITLE
[*] Project: Better license headers

### PR DESCRIPTION
**Pull request by gskema**
Although not a part of PSR-2, it is recommended to open file comments with `/**`. They look much nicer, collapse and work better with IDEs. File comment opening tag `/**` inspection is a part of PHPCS inspection list. Every else I've seen they use `/**` for file comments.

Other changes:
- Indentations fixes for tags based on PHPCS
- Replaced old and incomplete license header
- Fixed some typos
- Updated generator method in Tools.php

Did not swap any OSL/AFL types!

So sorry for this PR, I think I may have [OCD](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder) :smiley:

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, 

thank you for your contribution, big work ! 
An thanks to github for w=1 parameter

Best regards

**Comment by kpodemski** [comment]
Without w=1 my browser said "I am not going to show you what's changed"

:+1: @gskema

**Comment by gskema** [comment]
Obviously this header type should be changed in modules too (in the future). Don't forget!

**Comment by Shudrum** [comment]
Ahah, love your OCD :smile:

Thanks !

**Pull request merged**
