### PR TITLE
Make committers code owners

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR is a change of the project organization. When this PR is merged, it will replace maintainers with committers in the code owners file. Maintainers will become a subteam from committers.<br/>For code review, this means that two committers can now fully approve a Core Pull Request. As committer might have less knowledge of PrestaShop inner structure, they must be aware of what PR they fill confident enough to approve and what PR they might request maintainer's review.
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by ghost** [comment]
@PrestaShop/qa-team test or not

**Comment by matks** [comment]
> @PrestaShop/qa-team test or not

Hello @okom3pom I believe there is nothing to test ^^

**Comment by ghost** [comment]
Thank you @matks

**Comment by ghost** [comment]
Sorry for the bad milestones ...

**Comment by matks** [comment]
> Sorry for the bad milestones ...

If it's good at the end, then everything's OK 👍

**Pull request merged**
