### PR TITLE
Permit submit form button to be outside of a form with a form attribute

### LINKED ISSUE #17194: Change JQuery targeting of add-to-cart form by native targeting
**Is your feature request related to a problem? Please describe.**

I would like to put the button "add-to-cart" outside of the form. The form's submitting still work's if you add "form" attribute in the button element... but the JS function "add-to-cart" prevents me from doing it

**Describe the solution you'd like**

The solution is to change this line 
```let $form = $(event.target).closest('form');```
By this line
```let $form = $(event.target.form);```

The form's submitting still work's whithout the "form" attribute in the button element if you keep the button inside the form element.

https://github.com/PrestaShop/PrestaShop/blob/675626f689becd95c9bf3161e368f74dcfbf11c0/themes/_core/js/cart.js#L85

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | We couldnt put add-to-cart button outside of a form because of that
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fix #17194 
| How to test?  | Every add-to-cart button should work as expected, please don't forget to build asset before testing

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17243)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
Can you please resolve the conflict ?

**Comment by Progi1984** [comment]
Poke @NeOMakinG

**Comment by SD1982** [comment]
Thanks for the improvement @NeOMakinG

**Comment by matks** [comment]
Thanks for QA @SD1982 and for thanks for the code @NeOMakinG !

**Pull request merged**
