### PR TITLE
BO: Button to add an address from the customer profile

### PR DESCRIPTION
**Pull request by AlBlanc**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This contribution add a button in the customer profile page. This button allows to add an address to the customer. |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you!

**Comment by vincentbz** [comment]
Hi,

Thanks for this PR :)
Could you rebase your PR please ? So that I can validate the test, but it seems to be good, and that's a useful function.

**Comment by AlBlanc** [comment]
Done :)

**Comment by vincentbz** [comment]
Ok, works perfectly, thanks :)

**Comment by mickaelandrieu** [comment]
Thanks @AlBlanc

**Pull request merged**
