### PR TITLE
Replace EN (US) by EN (UK) in UK localization pack

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | We were adding US English to the UK localization pack while we have a UK English language.
| Type?         | improvement
| Category?     | LO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a.
| How to test?  | Install UK localization pack, should add the EN (UK) language.

### CODE REVIEW

**Comment by AlexEven** [comment]
giphy 17

**Comment by vincentbz** [comment]
Hi,

Could anyone try this PR please ? It fails with me but I can't find why. Installation with UK loc or import of UK pack doesn't put the EN/UK language. Weird.

**Comment by aleeks** [comment]
ping @AlexEven o_O

**Comment by AlexEven** [comment]
Import of localization pack works, you need to select "No" for "Download data pack".
Doesn't seem to be working for install in UK - maybe it uses a different system, I don't know.

**Comment by AlexEven** [comment]
NB: GB flag missing

**Comment by aleeks** [comment]
Working if **Import of localization pack works, you need to select "No" for "Download data pack".**

Thank you @AlexEven

**Pull request merged**
