### PR TITLE
Allow adding multilanguage routes, add comments

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | This PR allows to extend front end routing with multilanguage routes.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | @kpodemski can test if my hook works. :-)
| Fixed issue or discussion?     | 
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/628
| Sponsor company   | 

### Description
- Imagine you are making a blog module and you use hookModuleRoutes to add your new route. You will run into limitation that you can't create a route for multiple languages, for example:
  - EN: /blog/post/1-test
  - FR: /magazine/article/1-test
- This is important when you want to use built in methods to retrieve links. You can't, because for other languages, you would get bad urls.
- So, this:
  - Adds comments to Dispatcher to better explain what is happening.
  - Moves "getting languages" to the beginning of the method. Removed the exact same copy of the code that doesn't do anything. :-)
  - Added some methods to be able to get routes and delete them (the class attribute is private).
  - Added a hook to allow adding or modyfing the routes in any way, allowing unlimited flexibility.

### Test module
[tox_hooktest.zip](https://github.com/PrestaShop/PrestaShop/files/12527024/tox_hooktest.zip)
Put `dump($this->routes);` after `Hook::exec('actionAfterLoadRoutes', ['dispatcher' => $this]);`

### CODE REVIEW

**Review by M0rgan01 — APPROVED** [review]

**Review by LouisAUTHIE — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
@Hlavtox , I have checked the PR and LGTM.
Also Automated tests are OK.

**Comment by nicosomb** [comment]
⚠️ 

UI tests: https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/6122337697
Please wait before merge this PR

**Comment by Hlavtox** [comment]
@kpodemski Can you please add "needs documentation" and remove "BC break"?

**Comment by kpodemski** [comment]
@Hlavtox PR for autoupgrade needed 👍🏻

**Comment by Hlavtox** [comment]
@kpodemski Yeah I would add the labels if I wasn't banned 🤣🤣

**Pull request merged**
