### PR TITLE
Fix when adding combination to an already existant product in multistore context

### LINKED ISSUE #9686: [BOOM-5237] BO: Multistore | List of the attributes, with the association only to the second shop, doesn't appear in the product page
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5237).

- _**Reporter:**_ khouloud.belguith
- _**Created at:**_ Tue, 3 Apr 2018 13:23:35 +0200

<p>Hi,</p>

<p>In a multistore configuration, when you create a new attribute only available in the second shop, in the product page, this attribute created doesn't appear.</p>

<p>Best regards, Khouloud</p>
        
* How to reproduce the issue ?

Create a multistore configuration.
<br/>
Create a new attribute only available in the second shop
<br/>
Try to create a product with combinations =&gt; this attribute doesn&#39;t exist.

### PR DESCRIPTION
**Pull request by vcopleutre**
This fix need to be tested

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When adding a cobmination to an already existant product in a multistore context, the combination is added only in the context shop, not in all shops of the group. This commit fix this. Works on 1.6.17
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9686 
| How to test?  | Add combinations to an existing product and check if the combination has been added for all the shop relative to the group shop containing the contextual shop.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13217)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
The fix seems legit, otherwise there is is shop affected.
Ping @matthieu-rolland I know you're working on the multishop

I know there is a conflict, but maybe you can fix it?

**Review by matthieu-rolland — COMMENTED** [review]
thank you for your PR @vcopleutre , looks good to me 👍

**Review by matthieu-rolland — COMMENTED** [review]
I resolved the conflict, let's see how the CI (especially behat tests) react to this modification

**Comment by Progi1984** [comment]
@matthieu-rolland We can't accept merge commits in PR :(

**Comment by PierreRambaud** [comment]
Hi @vcopleutre ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
