### PR TITLE
[-] Class: Product / Get the cover image if no id_image given

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by thierrymarianne** [comment]
Closing as breaking the build.

**Comment by PrestaEdit** [comment]
Breaking the build as open since more than one year now, :)

**Comment by kpodemski** [comment]
lol

**Comment by kpodemski** [comment]
if i were in PrestaShop team i'd rather apologize every time while answering on 6+ months old ticket, sorry guys but this is ridiculous :)

**Pull request closed without merging**
