### PR TITLE
Remove unnecessary cart present and improve performance

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Boosts performance a lot on cart page by avoiding useless presenting of cart just to add one body class.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See below. Live shop with this change - https://eshop-franke.cz/
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### How to test
- Open https://www.domain.com/cart?action=show
- With products in cart, verify that there is no `cart-empty` class 
`<body id="cart" class="lang-cs country-cz currency-czk layout-full-width page-cart tax-display-enabled">`
- With empty cart, verify that there is `cart-empty` class 
`<body id="cart" class="lang-cs country-cz currency-czk layout-full-width page-cart tax-display-enabled cart-empty">`

### Performance gain with empty cart on 8.1.7
62 ms -> 54 ms
136 queries -> 121 queries

### Performance gain with 5 items in cart on 8.1.7
240 ms -> 216 ms
645 queries -> 569 queries

### CODE REVIEW

**Review by ShaiMagal — APPROVED** [review]

**Comment by Hlavtox** [comment]
https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11891566226

**Comment by Hlavtox** [comment]
@florine2623 @kpodemski Auto tests somehow don't work at all on this branch and 43/43 end up with timeout.

I think it's a safe change easy to test manually. Maybe @kpodemski you could test it quick? It's just that one HTML class.

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
Test - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11916752605

**Comment by Hlavtox** [comment]
@kpodemski @florine2623 The tests on 8.2.x just don't work. Or I am doing something wrong.

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Tests are green : https://github.com/florine2623/testing_pr/actions/runs/11934459237

Thanks :)

**Pull request merged**
