### PR TITLE
Remove ModuleZipManager service as class is missing

### LINKED ISSUE #28133: Remove ModuleZipManager service as class have been removed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

image (2)

### Expected behavior

_No response_

### Steps to reproduce

1 - Have a fresh install of PrestaShop (develop)

2 - Download MBO zip file : https://github.com/PrestaShopCorp/ps_mbo/suites/5935287095/artifacts/203186518 
[ps_mbo.zip](https://github.com/PrestaShop/PrestaShop/files/8416817/ps_mbo.zip)

3 - Go to Modules > Modules manager

4 - Install MBO

5 - Go to Dashboard, See the error

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

MBO - 3.x branch

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The service `prestashop.module.zip.manager` points `PrestaShop\PrestaShop\Adapter\Module\ModuleZipManager` which does not exist anymore
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #28133
| Related PRs       | https://github.com/PrestaShopCorp/ps_mbo/pull/155

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28132)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by intraordinaire — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @sowbiba ,

Thank for your PR, I tested your pr and currently we have an exception everywhere, as you can see : 

https://user-images.githubusercontent.com/100699445/161940204-8e1ca2fc-fd18-47b8-a999-7f11765478a3.mp4

I use the ps_mbo zip that you linked in your issue ( [ps_mbo.zip](https://github.com/PrestaShop/PrestaShop/files/8425411/ps_mbo.zip) )

**Comment by sowbiba** [comment]
> Hi @sowbiba ,
> 
> Thank for your PR, I tested your pr and currently we have an exception everywhere, as you can see : 
> 
> https://user-images.githubusercontent.com/100699445/161940204-8e1ca2fc-fd18-47b8-a999-7f11765478a3.mp4
> 
> I use the ps_mbo zip that you linked in your issue ( [ps_mbo.zip](https://github.com/PrestaShop/PrestaShop/files/8425411/ps_mbo.zip) )
> 
> 

I think you didn't install the module well. Install a fresh instance of PS, use the module manager page to upload the zip

Just extracting the module to the folder will not make the services loaded. I'm maybe wrong but it looks like that

**Comment by AureRita** [comment]
Ok, I do it again entirely with you : 

https://user-images.githubusercontent.com/100699445/161944602-c27bfff3-d0d6-4d57-ad5c-eaa4b2d9bf14.mp4

Tell me if I did it wrong

**Comment by sowbiba** [comment]
[ps_mbo.zip](https://github.com/PrestaShop/PrestaShop/files/8459941/ps_mbo.zip)

Hello @AureRita 
Please try with this one

**Review by AureRita — APPROVED** [review]
Hi @sowbiba , 

I tested it with your new modules and it seems to works well, 

Thank you

**Comment by Progi1984** [comment]
Thanks @sowbiba & @AureRita

**Pull request merged**
