### PR TITLE
Fix design on cart page

### LINKED ISSUE #13229: Promo code during checkout and order button
**Describe the bug**
1) Try to add a promo code during checkout, try to open and close it
The effect is jerky

2) The "order" button is stuck to the frame

capture d'écran_1323

3) When you have promo code highlighted and you arrive on the checkout you have 2 links: "Have a promo code ?" and "Close" to do the same thing
"Have a promo code?" shouldn't be displayed in this case

capture d'écran_1331

4) When you click on close the promo code higlighted is closed, it should be only the promo field

**Additionnal information**
PrestaShop version: develop
PHP version: N/A

### PR DESCRIPTION
**Pull request by YeLnatSs**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Some 
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #13229 
| How to test?  | Add a product to your cart and click on "proceed to checkout" to go on cart page.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13480)

### CODE REVIEW

**Comment by marionf** [comment]
@YeLnatSs as you fix a regression, this PR should be on 1.7.6.x branch instead of develop

**Comment by YeLnatSs** [comment]
@marionf Okay, I change it to 1.7.6.x. 
Thank you

**Comment by matks** [comment]
@YeLnatSs you need to rebase your branch on develop in order to fix PrettyCI build status

**Comment by YeLnatSs** [comment]
@matks Okay I will rebase it

**Pull request closed without merging**
