### PR TITLE
Remove isPasswd() method

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Validate
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `Validate::isPasswd()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26315)

### CODE REVIEW

**Review by tegbessou — COMMENTED** [review]
Thanks for the PR!

But you miss three occurrences:
- themes/classic/templates/customer/password-new.tpl
- themes/classic/templates/customer/_partials/account-transformation-form.tpl

If you don't delete them, there are some bugs.
To test, I have made an order and at the end of the order process, it's will ask you to specify a password. When I delete the function and don't change the method, I have an error 500

**Comment by PrestaEdit** [comment]
Hi @tegbessou,

Inside theses tpl, it's the data-validate attribute.
With it, it's the JavaScript that use the validate.js and it's specific isPasswd method, not related to the PHP method.

Could you say me the error detail of your error 500, maybe ? It could be something else, here.

**Comment by PrestaEdit** [comment]
Something to say: the size is now limited to 72 and the max is like 255 (as before) in the new validation method.
Note sure what to do, here.

Cause if we change the value of 72, it could break a lot of things, imho.

**Comment by tegbessou** [comment]
> Hi @tegbessou,
> 
> Inside theses tpl, it's the data-validate attribute. With it, it's the JavaScript that use the validate.js and it's specific isPasswd method, not related to the PHP method.
> 
> Could you say me the error detail of your error 500, maybe ? It could be something else, here.

You are totally right, this is not an issue with this! I forgot to delete `isPasswd` call in the Customer!

**Review by tegbessou — APPROVED** [review]
PR is valid IMO

**Review by Progi1984 — COMMENTED** [review]
@PrestaEdit Could you document the BC Break, please ?

**Comment by PrestaEdit** [comment]
Hi,

Not able to document it, it's a BC break as we remove code. Likely other PR having deprecated removed code, it will BC break existing modules using them, isn't it ?

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @PrestaEdit 

@PrestaShop/qa-functional Checked and no more uses found

**Pull request merged**
