### PR TITLE
Add debounce to quantity change of order create product

### LINKED ISSUE #21734: Input lag in BO > Create order > Cart
#### Describe the bug

On BO > Create order, in the cart, when updating the quantity of a product using the "up/down arrow" with consecutive hits on the same input, it's not acknowledged correctly.

For example, I'm at 6. I hit 3 times the "up" arrow, the counter goes up to 9 and then goes back to 7.

It's OK when adding the product

#### Expected behavior

All inputs should be taken into account

#### Steps to Reproduce

1. Go to BO > Create Order
2. Select and customer and add a product
3. Increase the quantity by clicking multiple times on the "up" arrow, fast enough
4. The quantity is not well updated

**Screenshots**

https://drive.google.com/file/d/1e0fqUhsqojurQ_xbQdUwAY1m54wzT0Tu/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.0 RC1 Build 4
* PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | There was strange lags when you were changing quantity of a product really fast on create order page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21734.
| How to test?  | Check issue, it's just about spamming the quantity input of a product inside create order

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21977)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @NeOMakinG I still have the behaviour described in #21734
https://drive.google.com/file/d/1C9gyMdupaloKq78yAkDEBS1YR8Lb72C-/view?usp=sharing

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Please check the Conflicting files.

Thanks!

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Following these steps:

1. Go to BO > Create Order
2. Select and customer and add a product
3. Change the quantity of the product to 100
4. Decrease the quantity by clicking multiple times on the "down" arrow, fast enough
5. See an error in the console

https://drive.google.com/file/d/1USnOihpNEVRjQP17yHDh9H16lKORlEwT/view?usp=sharing

Also, clicking multiple times on the "down"/"up" arrow => the block is refreshed => we are stopped, because the  block quantity's position is changed

I attached  a screen record

https://drive.google.com/file/d/1cce41PaaxV8B8fIZ7Oh8Gez1K1XYL9u4/view?usp=sharing

Thanks!

**Comment by NeOMakinG** [comment]
> Also, clicking multiple times on the "down"/"up" arrow => the block is refreshed => we are stopped, because the block quantity's position is changed

Let's treat this on another issue (which is already created by @SD1982 : https://github.com/PrestaShop/PrestaShop/issues/22026 (It will be hard to fix it, I've no idea)

I changed the behavior, I disable every inputs buttons when the request is currently running, this prevent clicks between the debounce as it has delay

I also pushed some lint to these files (it doesn't hurt), let me know if this is fixed

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I have a new issue 
I try to change the quantity of the product, when I stopped, the field quantity is disabled, I cannot change the quantity anymore.
image

I attached a screen record
https://drive.google.com/file/d/1n4wuO4ddeO_FGDoLleQUU28qufIFHvtV/view?usp=sharing

Thanks!

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I confirmed with @MatShir with the new behavior. 
It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1F4UudR_SkenWqMqnmU7tRdx5Y3l3Nzyy/view?usp=sharing

Thanks!

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG,
> 
> I confirmed with @MatShir with the new behavior.
> It is ok ✔️
> https://drive.google.com/file/d/1F4UudR_SkenWqMqnmU7tRdx5Y3l3Nzyy/view?usp=sharing
> 
> Thanks!

Sorry khouloud, I should have write it before, can you also test with multiple products ? As every products are disabled when the request is launched

Edit: Didn't see the full video, my bad that's fine :)

**Comment by Progi1984** [comment]
Thanks @NeOMakinG @SD1982 & @khouloudbelguith

**Pull request merged**
