### PR TITLE
Better validate availability date

### LINKED ISSUE #34692: FO - Product with 0 quantity show us a date with : 0000-00-00
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I create a new product with 0 quantity, If I go to the FO and check this one, we'll have a Available date : 0000-00-00 as you can see : 

image

### Expected behavior

We expected that if we don't put a date, the available date shouldn't be show, and if there is no product detail, this tab shouldn't be show.

### Steps to reproduce

1. Go to BO 
2. Go to Catalog > Products
3. Clic on New Product 
4. Clic on Standard Product 
5. Clic on Add new Product 
6. Set a title 
7. Put it Online 
8. Save it 
9. Go to FO 
10. Check you product 
11. :negative_squared_cross_mark: You'll have the available date with many 0

### PrestaShop version(s) where the bug happened

8.1.x - develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

None 

### Your company or customer's name goes here (if applicable).

PS

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Improves date validation to avoid zeroes to be passed into front office. (I broke it here - https://github.com/PrestaShop/PrestaShop/pull/34462/files, before it actually tried to format the '0000-00-00' to a date and then set it to null.)
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See related issue.
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #34692
| Related PRs       | 
| Sponsor company   | 

Ping @AureRita

### CODE REVIEW

**Comment by RosaBenouamer** [comment]
@Hlavtox thank you for your PR. To be sure with it you return null so no data and no Product details tab or you will have an empty tab ?

**Comment by Hlavtox** [comment]
@RosaBenouamer I didn't change anything in that department, just fixing an issue I introduced before.

And yes, there will be an empty details tab, but it has been like this for years in clasic.

**Review by boherm — APPROVED** [review]

**Comment by RosaBenouamer** [comment]
> @RosaBenouamer I didn't change anything in that department, just fixing an issue I introduced before.
> 
> And yes, there will be an empty details tab, but it has been like this for years in clasic.

I just ask because on the issue you have write as fixed it's written "We expected that if we don't put a date, the available date shouldn't be show, and if there is no product detail, this tab shouldn't be show."

Of course we could fix at least the first part of the issue :-) it's a good thing

**Comment by Hlavtox** [comment]
@RosaBenouamer Yeah, but there will almost always be something in that tab, so I think nobody noticed in all those years. :-) Reference, manufacturer, features, EAN etc.

**Review by ShaiMagal — APPROVED** [review]

**Review by matks — APPROVED** [review]
Code looks OK to me but I'll be happy having explanations for

> before it actually tried to format the '0000-00-00' to a date and then set it to null

I don't see where the error is

**Comment by Hlavtox** [comment]
@matks 

Before my previous PR there was only `if (isset($product['available_date'])) {`.
So if the date was `0000-00-00`, it was actually set. Then it made some nonsense date like 1970-01-01 and decided that its already long past, so it set it to null.

When I added the empty and zeroes check in my previous PR, there was nothing resetting the date into null, so now there are zeroes displayed in FO. :-)

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox 

Thank you for your PR, I tested it and it seems to works as you can see : 

[Untitled_ Nov 29, 2023 5_10 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/0ecbe819-1eb7-48bc-889c-e73281ee20a6)


Link to the auto test : https://github.com/AureRita/testing_pr/actions/runs/7035247264

As you can see on the video, you've the product details that are showed without anything in there, but you discuss it with Rosa so it's seems to be good. 

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by Hlavtox** [comment]
Thank you @AureRita! Merging :-)

**Pull request merged**
