### PR TITLE
Allow modules to modify product list after query

### PR DESCRIPTION
**Pull request by 123monsite-regis**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allowing modules to modify product list after query, using actionProductSearchAfter (more details bellow)
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | create a module as described below, and please especially test all front office pages having a list of products.

Just one more & for this proposition, but as many possibilities as you want after :)

- Description
According to me , the hook actionProductSearchAfter located at classes/controller/ProductListingFrontController.php may have allow modules to add , remove or modify some products of the product list.
So, passing the param with a reference can be a solution.
( It was a possibility with ps 1.6 on hook actionProductListModifier )

- Sample code
To test this, you can create a module as bellow : 

```php
<?php
use PrestaShop\PrestaShop\Adapter\Image\ImageRetriever;
use PrestaShop\PrestaShop\Core\Product\ProductListingPresenter;
use PrestaShop\PrestaShop\Adapter\Product\PriceFormatter;
use PrestaShop\PrestaShop\Adapter\Product\ProductColorsRetriever;

class MyModuleWhoAddTheSameProductAtTheStartOfEachListing extends Module
{
    [... Classic code of a module ...]
    
    //Always displaying the " T-shirt délavé à manches courtes " at first listing product
    public function hookactionProductSearchAfter($params)
    {  
        $id_product_to_add = 1; //this is just a sample, not a real case
        
        $presenterFactory = new ProductPresenterFactory($this->context);
        $presentationSettings = $presenterFactory->getPresentationSettings();
        $presenter = new ProductListingPresenter(
            new ImageRetriever(
                $this->context->link
            ),
            $this->context->link,
            new PriceFormatter(),
            new ProductColorsRetriever(),
            $this->context->getTranslator()
        );
        
        $product_for_template = $presenter->present(
            $presentationSettings,
            array('id_product' => $id_product_to_add),
            $this->context->language
        );
        
        array_unshift($params['products'], $product_for_template);

        return true;
    }
}

```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8687)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Make sense to me, wdyt @Quetzacoalt91?

**Comment by Quetzacoalt91** [comment]
I see a few lines further that we already send the whole parameters array as reference

```php
Hook::exec('filterProductSearch', array('searchVariables' => &$searchVariables));
```

Have a tried your code with `filterProductSearch` @123monsite-regis?

**Comment by 123monsite-regis** [comment]
Sory,
i does not know why i did'nt see the line 
```Hook::exec('filterProductSearch', array('searchVariables' => &$searchVariables));```
@Quetzacoalt91 , my pull request seels in consequence not pertinent , can i close it ?

**Comment by Quetzacoalt91** [comment]
If you confirm the hook already fits your needs, yes you may close the PR. :)

**Comment by 123monsite-regis** [comment]
I close this  pull.
as mentioned previously this is irrelevant, as the hook exist ( and work , i tested) one line before.
My sample can be adapted with  the usage of filterProductSearch hook.

**Pull request closed without merging**
