### PR TITLE
[WIP] Rework/front controller

### PR DESCRIPTION
**Pull request by julienbourdeau**
I introduce new smarty vars for template:
- currencies
- languages
- countries

They are all formatted as follow so you can use `$currencies.current.iso_code`, `$currencies.all.default`, `foreach ($currencies.all as $cur)` and so on.

```
Array
(
    [all] => Array
        (
            [0] => Array
                (
                    [id_currency] => 2
                    [name] => Euro
                    [iso_code] => EUR
                    [conversion_rate] => 1.360729
                    [deleted] => 0
                    [active] => 1
                    [id_shop] => 1
                    [iso_code_num] => 978
                    [sign] => €
                )

            [default] => Array
                (
                    [id_currency] => 1
                    [name] => British Pound Sterling
                    [iso_code] => GBP
                    [conversion_rate] => 1.000000
                    [deleted] => 0
                    [active] => 1
                    [id_shop] => 1
                    [iso_code_num] => 826
                    [sign] => £
                )

        )

    [current] => Array
        (
            [id_currency] => 1
            [name] => British Pound Sterling
            [iso_code] => GBP
            [conversion_rate] => 1.000000
            [deleted] => 0
            [active] => 1
            [id_shop] => 1
            [iso_code_num] => 826
            [sign] => £
        )

)
```

About the URLs array, so far it's based on what was already existing. It's mostly base link for image folders. 
We intend to introduce a smarty function like `{get_url type="product" entity=$product}` or something similar.

### CODE REVIEW

**Comment by djfm** [comment]
I think the collections are not needed and `$currency`, `$language` and `$country` are enough.

I understand that `$language` is needed for the `<html lang="en-us">` thingy, but maybe we could go without `$currency` and `$country` altogether.

Any example use of `$country` and `$currency` in the theme?

**Comment by kpodemski** [comment]
Is there any chance to make $context available in tpl files? For sure some modules or themes can use `$country` or `$currency` for some {if} statements.

**Comment by djfm** [comment]
If it is used by a module it should rely on the hook parameters, not the template variables.

In smarty variables are global so it might work but I think a module should not rely on variables assigned by the controller!

**Comment by kpodemski** [comment]
I saw a lot of modules using $page_name, $cookie, $lang_iso etc. On product lists you may see for example: `<meta itemprop="priceCurrency" content="{$currency->iso_code}" />`

**Comment by djfm** [comment]
Ok good point, they're indeed needed at least for itemprop's so let's keep them. I hadn't noticed this, thanks!

**Comment by julienbourdeau** [comment]
So I moved back to simple arrays for `currency`, `country` and `language`.

I also made sure OobjectSerializer remove some attributes https://github.com/PrestaShop/PrestaShop/commit/993dabdf5a2d6be4194b867387afd71f2d0b1483

```
    [currency] => Array
        (
            [name] => British Pound Sterling
            [iso_code] => GBP
            [iso_code_num] => 
            [sign] => £
        )
```

```
    [customer] => Array
        (
            [lastname] => DOE
            [firstname] => John
            [email] => pub@prestashop.com
            [last_passwd_gen] => 2015-09-01 11:17:51
            [birthday] => 1970-01-15
            [newsletter] => 1
            [newsletter_date_add] => 2013-12-13 08:19:15
            [ip_registration_newsletter] => 
            [optin] => 1
            [website] => 
            [company] => 
            [siret] => 
            [ape] => 
            [outstanding_allow_amount] => 0.000000
            [max_payment_days] => 0
            [note] => 
            [is_guest] => 0
            [id_shop] => 1
            [id_shop_group] => 1
            [id_default_group] => 3
            [date_add] => 2015-09-01 17:17:51
            [date_upd] => 2015-09-01 17:17:51
            [id] => 1
            [is_logged] => 
            [gender] => Array
                (
                    [type] => 0
                    [name] => Array
                        (
                            [1] => Mr.
                        )

                    [id] => 1
                )

            [risk] => Array
                (
                    [name] => 
                    [color] => 
                    [percent] => 
                    [id] => 
                )

        )
```

```
    [language] => Array
        (
            [name] => English (English)
            [iso_code] => en
            [language_code] => en-us
            [is_rtl] => 0
            [date_format_lite] => m/d/Y
            [date_format_full] => m/d/Y H:i:s
            [id] => 1
        )
```


Also I still have doubts, `urls` might be useless 
```
    [urls] => Array
        (
            [base_url] => http://prestashop.ps/
            [img_ps_url] => http://prestashop.ps/img/
            [img_cat_url] => http://prestashop.ps/img/c/
            [img_lang_url] => http://prestashop.ps/img/l/
            [img_prod_url] => http://prestashop.ps/img/p/
            [img_manu_url] => http://prestashop.ps/img/m/
            [img_sup_url] => http://prestashop.ps/img/su/
            [img_ship_url] => http://prestashop.ps/img/s/
            [img_store_url] => http://prestashop.ps/img/st/
            [img_col_url] => http://prestashop.ps/img/co/
            [img_url] => http://prestashop.ps/themes/StarterTheme/img/
            [css_url] => http://prestashop.ps/themes/StarterTheme/assets/css/
            [js_url] => http://prestashop.ps/themes/StarterTheme/js/
            [pic_url] => http://prestashop.ps/upload/
        )

```

**Comment by kpodemski** [comment]
Having array with urls is must have, how you will load for example flag or shipping logo in theme? It is better to have {$img_lang_url} instead of doing {$img_ps_url}l/ 

also, make sure to include directory urls so we can easily check for example:

{if file_exists($ps_img_dir`etcetc)}

**Pull request merged**
