### PR TITLE
Remove id from entity search input templates

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The templates for the entity search input component included an ID based on `form.vars.name` which is the collection index, this could lead to elements with duplicated ID which is invalid in HTML. Besides the id was never used so it's been decided to remove it.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | CI tests green, check that the elements using this component still work like before (related products, attached files, SEO redirect target, specific price customer)
| Possible impacts? | ~

### Preview here is a video showing the places where the component is used

https://watch.screencastify.com/v/jLvUvAUxpeDaUBo8IwNk

Also, I forgot about the specific price customer:

https://watch.screencastify.com/v/me8QIW2Dwm2fbPXSZCCq

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matks** [comment]
Re-running CI

**Review by matks — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]
Ahhh I like it

**Review by sLorenzini — APPROVED** [review]
hello @jolelievre,

Thank you for this PR.
Tested on develop branch with PHP 7.2 version.

Tested with a product already installed with the shop and a new product, product page V2:

BO
----------
- Description tab: search and add related products and save ✅ 
- Specifications tab: ✅ 

> 1. create file on this page (pdf / jpg / png)
> 2. remove it
> 3. search it in the field and add it
> 4. save

OR

> 1. create file on manage files page (pdf / jpg / png)
> 2. go back to product page > specifications tab
> 3. search it in the field and add it
> 4. save

- SEO tab: add a target category in redirection page block, put to offline the product and save ✅ 
- Pricing tab: add specific price on a customer and other parameters and save ✅ 

FO
-------

- Related products (linked to description tab on the BO), is well displayed ✅ 
- All attachment files (linked to specifications tab on the BO), are well displayed and can be downloaded ✅ 
- Good redirection to the category choosen when product is offline (linked to the SEO tab on the BO) ✅ 
- Specific price is well displayed with parameters choosen (linked to princing tab on the BO) ✅ 

QA approved ✅ 

Thanks

**Comment by Progi1984** [comment]
Thanks @jolelievre & @sLorenzini

**Pull request merged**
