### PR TITLE
Improve error message on login page

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | When you put a wrong email or password, it shows `There is one error: 1. Some error message` on login page. Now it will just show `Some error message` if there is just one. 
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests green.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/6785688583, 2nd attempt - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6791367917
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

dasd
⏬⏬⏬ 
Snímek obrazovky 2023-11-06 233409

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]
Nice! Thanks mate 😉

**Comment by nicosomb** [comment]
@Hlavtox I think we can QA this PR, right?

**Comment by Hlavtox** [comment]
@nicosomb Yeah, we can, although I don't know how to reproduce 2 error messages at once. :-)

- For one error - put some nonsense into email and try to log in.
- For multiple errors - open `controllers/admin/AdminLoginController.php` and put `$this->errors[] = 'blabla';$this->errors[] = 'blabla';` to the beginning of `processLogin` method.

**Review by matthieu-rolland — DISMISSED** [review]

**Review by LouisAUTHIE — DISMISSED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by Hlavtox** [comment]
@florine2623 all green ✅

**Review by boubkerbribri — APPROVED** [review]
LGTM for UI tests Code

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

It works as expected :

Screenshot 2023-11-07 at 15 26 40

It is QA ✅

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @Hlavtox and @florine2623 !

**Pull request merged**
