### PR TITLE
Fixed filemanager new folder

### LINKED ISSUE #26519: BO - The field text of a new folder is not consider as a placeholder
#### Describe the bug

While insert a new text of new folder in the File manager, the field text is not considered as a placeholder. The text do not disappear.

#### Expected behavior

The text `New folder `must be a placeholder

#### Steps to Reproduce

1. BO>Catalog>Products
2. Click on New product
3. Go to Summary/Description
4. Click On Insert/edit link
5. Click On the button to insert an url 
6. In Actions, Click On New Folder
7. Insert folder name
8. See error > `New Folder` don't disappear and possible to insert a new text with New Folder

**Screenshots**

Before Save :
folder1

After Save it :

folder2

#### Additional information

* PrestaShop version: 1.7.8.0 & develop
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by alexandrebru83**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | While insert a new text of new folder in the File manager, the field text is not considered as a placeholder. The text do not disappear.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26519.
| How to test?      | How to test section of issue
| Possible impacts? | Other use of prompt function when rename or duplicate

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26538)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@NeOMakinG Isn't it possible to move these minified to dependencies ?

**Review by matthieu-rolland — APPROVED** [review]

**Comment by NeOMakinG** [comment]
> @NeOMakinG Isn't it possible to move these minified to dependencies ?

Unfortunately not without a lot of pain

- Filemanager is a complete project by itself, which has been tweaked for our use
- It contains PHP

I really think that this little project is a pain for us, we should probably redo a file manager in the core or rely on a new library with npm

But this is not related to the PR :/

**Review by Progi1984 — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @alexandrebrubeyonds ,

Thanks for the PR, text is a placeholder now ! It is QA approved !

**Comment by Progi1984** [comment]
Thanks @alexandrebrubeyonds & @florine2623

**Pull request merged**
