### PR TITLE
Remove deprecated methods inside Product class

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Product model
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed define : `_CUSTOMIZE_FILE_`
* Removed define : `_CUSTOMIZE_TEXTFIELD_`
* Removed method : `Product::addProductAttributeMultiple()`
* Removed method : `Product::addAttributeCombinaison()`
* Removed method : `Product::addAttributeCombinationMultiple()`
* Removed method : `Product::updateQuantity()`
* Removed method : `Product::reinjectQuantities()`
* Removed method : `Product::getIdProductAttributesByIdAttributes()`
* Removed method : `Product::getAttributeCombinaisons()`
* Removed method : `Product::deleteAttributeCombinaison()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28192)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @PrestaEdit

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I think executing the full automated suite could be a good idea.

**Review by AureRita — APPROVED** [review]
hi @PrestaEdit ,

I used the automated test and it pass 

Thank you

**Comment by Progi1984** [comment]
Thanks @PrestaEdit & @AureRita

**Pull request merged**
