### PR TITLE
Refactor phpstan exclusion lists with ::class

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | More refactorable
| Type?             | refacto
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | n/a
| Possible impacts? | no functional change

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24035)

### CODE REVIEW

**Comment by matks** [comment]
Hi @mvorisek  we have entered the month of April which is the month where PrestaShop 1.7.8 should be feature frozen. The very last Pull Requests are being submitted and validated so we can complete the 1.7.8 milestone. So review might come late as maintainers are very busy at this moment! 😅

**Comment by mvorisek** [comment]
Hi @matks this just needs a 20 seconds look, all changed files produce binary same result :)

**Comment by matks** [comment]
Hi @mvorisek it'll take me more than 20 seconds because to validate this PR I'll have to make sure it works well with https://github.com/PrestaShop/phpstan-prestashop and I will have to verify what changes you introduced in the +14,673 lines.

I dont plan to do it line by line, but I'll have to setup a diff script to verify only `::class` have been added and nothing else.

Our role of maintainer requires us to verify everything 😊 we are gatekeepers of the codebase. We are in charge of making sure nothing harmful goes there. What if you added a backdoor in these 14,673 lines? I have to ensure nothing risky is in there.

So unless I personally validate that these 14,673 lines changed contain nothing suspicious I cannot approve this PR.

**Comment by mvorisek** [comment]
I understand, it's made with regex replace, thus I advise to do the same on your side on the sources and compare.

Also, please get onto https://github.com/PrestaShop/PrestaShop/pull/23918 , which can be checked be reverting all changes excl. the changed CS config, reruning the CS fixer and comparing the result.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I see no reason to merge this PR, it brings no value, it's unreviewable.
Please stop wasting your time on useless things like that.

**Comment by matks** [comment]
Hi @mvorisek 

When @PierreRambaud says `it brings no value` I think he makes a point.

Why add these `::class` ? What are the benefits? What is better in the codebase after the PR has been merged in comparison to before?

Sometimes we developers do something not because it brings benefits, but "because the code looks better like this". Unfortunately every change we introduce in a codebase can have side-effects, sometimes very unexpected.

So if we consider the time you took to implement the change (using the regexp), the time I need to take to validate the PR (and because we need 2 approvals to merge a PR it will require someone else to take the same time as I do), _is the change you want to introduce really worth it?_

So can you tell us _why_ you added these `::class`? What is so much better in this?

It's actually important 😉  in a PR both author and maintainer invest time into a change. @PierreRambaud is right to mention that this PR might not be a good ROI.

**Comment by PierreRambaud** [comment]
I'm closing it, since we will not review or merge this pull request.

**Comment by mvorisek** [comment]
It has a benefit. When `::class` is used, the use can be find by an IDE and refactoring is possible.

Also, as I have written, this PR was made with regex replace and can be verified easily.

@PierreRambaud please stop saying things that are no true!, citing:

> I see no reason to merge this PR, it brings no value, it's unreviewable.

**Comment by mvorisek** [comment]
Here is one reference why Lavarel uses it: https://laravel-news.com/using-class-keyword-laravel

basically all major projects use it ;-)

**Comment by PierreRambaud** [comment]
> Here is one reference why Lavarel uses it: https://laravel-news.com/using-class-keyword-laravel
> 
> basically all major projects use it ;-)

You edited files without understanding the aim of these files.

**Comment by matks** [comment]
@mvorisek the content of these files is never expected to be changed ;) see the origin https://github.com/PrestaShop/PrestaShop/pull/23522

So we will never refactor this file. Actually we will never modify it again and we will remove it when we build PrestaShop 8.0.0 as phpstan will be applied to the full project

**Comment by mvorisek** [comment]
I know the aim and also a contributor to phpstan or CS Fixer packages :D :D

**Comment by mvorisek** [comment]
> @mvorisek the content of these files is never expected to be changed ;) see the origin #23522
> 
> So we will never refactor this file. Actually we will never modify it again and we will remove it when we build PrestaShop 8.0.0 as phpstan will be applied to the full project

This is not true. If class is renamed, removed, IDE should be aware of it. Even if you will not change these files, my proposal is good :)

**Comment by matks** [comment]
> > @mvorisek the content of these files is never expected to be changed ;) see the origin #23522
> > So we will never refactor this file. Actually we will never modify it again and we will remove it when we build PrestaShop 8.0.0 as phpstan will be applied to the full project
> 
> This is not true. If class is renamed, removed, IDE should be aware of it. Even if you will not change these files, my proposal is good :)

This file contains "class that we cannot apply `declare(strict_types=1);` (and other PHP7 features)" because of backward compatibility.

If one of the class if this file is renamed or removed, it's a BC break 😄  .

If however one day we decide to rename or remove such a class (for example for PrestaShop 8.0.0 next major version) and it's a BC break, we'll add the `declare(strict_types=1);` and the file will no longer be useful :)

So this file content will never change. It will just be deleted one day.

**Comment by mvorisek** [comment]
I have proven this change is helful and an industry standard practise. It can be also checked under 5 minutes with regex replace.

I understand your assumptions, but given the fact this change can be checked quickly, the beneficts are greater than "at this time" assumptioms which can change and are much harder to reason (like there can be an internal class without BC guarantee).

I hope you understand my point as well and accepts contributions to better CS in general.

**Comment by matks** [comment]
I am sorry but no, we do not understand your point.

> "at this time" assumptions" which can change

When the need comes, we'll consider this change :) . Until then, better not do something "for maybe a future need". [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

> industry standard practice

There is no silver bullet. Industry standard practices are useful when applied to the right context. The context of this file makes the use of `::class` useless IMO.

**Comment by mvorisek** [comment]
If nothing, this change, requiring 5 minute review (= 10, 15 EUR), can help developer be aware (by allowing easy IDE usage discovery) there is no strict types required.

https://github.com/PrestaShop/PrestaShop/pull/22965 is by @PierreRambaud also an UNuseful change. But as you can see, it was opened on Jan 24. One extra user also supported me in the discussion. What is your POV on this (small) improvement?

**Comment by matks** [comment]
> an help developer be aware (by allowing easy IDE usage discovery) there is no strict types required.

We dont need IDE to be aware of this file content 😄 

Files in `.github/workflows/phpstan/` are not expected to be visited. As I said these files have been created and will not be modified anymore. One day they will be deleted. No need to help IDE navigate them :)

> If nothing, this change, requiring 5 minute review

As I said before, no, it will take more time than 5 minute review because I need to validate that there is nothing harmful in these changes. 😉 

If I approve this PR as a maintainer I put my own responsibility saying "nothing risky in this PR". I will take a lot more than 5 minutes to assert this.

You cannot know how long I will review ;) you are not in my seat. And software estimates have always been a very vague field.

**Comment by mvorisek** [comment]
How to review:

- checkout commit before this PR
- do the same changes with regex replace
- verify the changes vs. the proposed ones
- done :)

I do like 500 PRs and 500 code reviews for public projects a year, so I know what you are talking about.

**Comment by mvorisek** [comment]
The same review for any generated changes :) I will be happy if you can practice this workflow on my PRs 8-)

**Comment by matks** [comment]
> How to review:
> 
> * checkout commit before this PR
> * do the same changes with regex replace
> * verify the changes vs. the proposed ones
> * done :)
> 
> I do like 500 PRs and 500 code reviews for public projects a year, so I know what you are talking about.

I am sorry but this is only partially what I would review in this PR.

Without being exhaustive, I would also
- verify this works well with https://github.com/PrestaShop/phpstan-prestashop
- verify the regexp to be used, explore it to make sure it is not faulty
- verify it works for a 1 line file or the 14,673 lines file
- try to find possible side-effects that might harm the codebase
- try to think if this can be improved

Different people do different reviews. This is how I would do it, other maintainers might do it differently.

However even if it was about 5 minutes, 20 minutes, 45 minutes ; I am still not convinced about the outcome of this PR. I am sorry but I fail to see a usecase where this change is useful, no matter how long it would take to review. Moreover each PR on this repository needs 2 successfull reviews, so you can x2 the review time.

I am sorry @mvorisek but I'm going to take a break in this discussion 😅  because I'm a bit exhausted from it. I'm also exhausted from the feature freeze happening on 1.7.8 that requires a lot of efforts and other maintainers and contributors also need me. So I will stop answering for now.

You've done great contributions [to this project](https://github.com/PrestaShop/PrestaShop/pulls/mvorisek) and the PrestaShop project thanks you 😉  but it does not mean all of your contributions will go through. For this PR we really, really, fail to see the ROI and the benefits of merging it, why insist so much? 😄 

If I find some strength later I'll come back to resume the discussion. In the meantime I suggest you read https://medium.com/@alcaeus/dealing-with-large-changes-in-open-source-projects-26a4aad87803 it's a great tale about how maintainers and contributors can work together. And it's about thousand lines reviews. 😉

**Pull request closed without merging**
