### PR TITLE
Ordering product in BO doesn't work

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Ordering product is currently only working with url rewrite: `/catalog/product/{limit}/{offset}/{orderBy}/{sortOrder}` But sortable-column use query params instead to prevent errors allow. More I fixed many CS issues.
both usage.| Type?         | bug fix
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5533
| How to test?  | Go to catalog product page in BO and tri to sort by name.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9074)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
@PierreRambaud can you please separate your changes in several commits? One for the CS fixer and the other for the actual fix?
This will make the review easier.

**Comment by PierreRambaud** [comment]
@Quetzacoalt91 Done, and sorry!

**Comment by PierreRambaud** [comment]
For Codacy, not sure it's a good idea to fix NPath complexity in this PR :D

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9074#-:-LChHGINCa2K8-6S-erE:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @PierreRambaud

**Pull request merged**
