### PR TITLE
Bump modules (ps_linklist in v6 & blockwishlist in v3)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Bump modules (ps_linklist in v6 : PrestaShop/ps_linklist#166 & blockwishlist in v3 : PrestaShop/blockwishlist#209)
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | @PrestaShop/qa-functional : FYI @florine2623 & @MhiriFaten have tested two modules releases on develop branch
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   |@PrestaShopCorp

### CODE REVIEW

**Review by nicosomb — COMMENTED** [review]
This kind of PR is not handled by Github Actions?

**Comment by Progi1984** [comment]
@nicosomb Nope, because we need to change the `composer.json`.

**Comment by nicosomb** [comment]
@Progi1984 oh you're right, it's major upgrade 😴 sorry.

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
No need QA, thanks @Progi1984 !

**Pull request merged**
