### PR TITLE
BO :  Wording modal_confirm.html.twig

### PR DESCRIPTION
**Pull request by Nobodaddy**
Bad English

### CODE REVIEW

**Comment by xBorderie** [comment]
I disagree: the labels are here to warn the user about the lasting implications of an action for which they have already clicked. 'You would like...' has no place here, "You are about to..." _is_ the correct English.

However, nicely spotted for the "disable" typo! :)

**Comment by llandrysg** [comment]
Hi there,

Yes, the aim of this wording being to warn users, I think as well it's less efficient to replace it with "would like'. "You are about to..." is much more appropriate to the situation described and to the context.

**Comment by maximebiloe** [comment]
Regarding what has been said, I close this PR.

Thanks @Nobodaddy

**Comment by Nobodaddy** [comment]
I understand what you mean and agree. Thank you.
However, you should drop abbrevations like _"You`re"_ in help texts. It should be _"You are ..."_.

**Comment by xBorderie** [comment]
Alexandra is away in vacation, but I think should would agree.

**Pull request closed without merging**
