### PR TITLE
Add manufacturers and suppliers list to sitemap

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Extend sitamap list and fix BOOM-1310 |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1310 |
| How to test? | Open frontend sitemap |

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by martinfojtik** [comment]
yes, i updated the commit name

**Comment by xBorderie** [comment]
Thank you! Tests are failing for PHP 5.4, any idea why @mickaelandrieu ?

**Comment by mickaelandrieu** [comment]
No... @martinfojtik  you may need to rebase against develop, and pray.

**Comment by Shudrum** [comment]
Thank you @martinfojtik! We have an issue about this, so when someone merge this pull request, please close this issue: http://forge.prestashop.com/browse/BOOM-1310

**Comment by martinfojtik** [comment]
@xBorderie the error in test is somehow related to `blocktopmenu`

@mickaelandrieu i just rebased it and starting to :pray:

**Comment by mickaelandrieu** [comment]
@martinfojtik  good to me :) Merged!

Thank you!

**Comment by AlexEven** [comment]
Hello hello. 
Again, please add the label "Waiting for wording" when new or updated content is introduced.
We no longer use "manufacturer", but "brand" instead.
I'll update the content but please pay attention when you see "manufacturer"!
Thank you!

**Pull request merged**
