### PR TITLE
Removal of the terms "whitelist" and "blacklist" from Prestashop part. 1

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Details below ⬇️ 
| Type?         | improvement / refacto
| Category?     | PM
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | Fixes #
| How to test?  | Complicated to announce how to test so many changes are multiple, but overall, test if the search with blocked words still works, if the cache still works and the proper functioning of admin access with cookie.

I think my PR will make people react:D

Following the Black Lives Matter movement that has taken place, and is still taking place, several open-source ecosystems have chosen to make changes in their lexicon to ban the use of exclusionary terms.

### Some precisions
There are many occurrences that cannot be modified, mainly for compatibility reasons. Some function and/or class names can't be modified but there are many comments, variables, array indexes that can be modified.

My PR is not complete, it's a first part! For the term "blacklist" in PHP there is not much left, except the necessary ones in my opinion. But for "whitelist" the work is much more important. I haven't started the JS/CSS/TPL files yet either but it will come!

I replaced by `allow`, `allowed` and `blocklist`, `blocked` but if you want to change, no problem!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20401)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I'm totally against this kind of change since the word Blacklist as nothing to do with Black people. Same for Black Hat and many others words... 

**Edit:** I didn't mean to start a polemic. I'm just very picky about definitions, my bad.

**Comment by Vladdov** [comment]
Forbid more words - dark chocolate, black cars and black asphalt.
And if in essence you are looking for a problem where there is no a priori, since the code does not apply to any person.

**Comment by matthieu-rolland** [comment]
@Sinepel no offense but I also disagree with this PR, at least for this terminology that is completely unrelated to racial bias:

`The black hat/white hat terminology originates in the Western genre of popular American culture, in which black and white hats denote villainous and heroic cowboys respectively.`

https://en.wikipedia.org/wiki/Black_hat_(computer_security)

We can't just remove the words "black" and "white" from the common language, it makes no sense. 🤔

**Comment by Sinepel** [comment]
No worries, I don't take it personally. I wanted to follow a more global movement, Apple or WordPress took this decision recently as well. But no worries, I also understand your point of view 😉

**Comment by eternoendless** [comment]
I understand you mean good @Sinepel but as others stated, deleting arbitrary words does nothing to help oppressed minorities.

**Comment by PululuK** [comment]
> I understand you mean good @Sinepel but as others stated, deleting arbitrary words does nothing to help oppressed minorities.

@eternoendless  @PierreRambaud 

Could we change suddenly, put the bad things in whitelist and the good ones in blacklist ? If you do not mind ?

**Comment by PululuK** [comment]
You ignore the psychological effects of these appointments! Good luck, keep teaching your kids that good things are associated with white and bad things with black!

**Comment by PululuK** [comment]
Sorry, but I can no longer contribute to a project like this!

**Comment by matthieu-rolland** [comment]
> Sorry, but I can no longer contribute to a project like this!

I'm really sorry to hear that @PululuK , I'd just like to say that in many cultures (if not all cultures?), before there was electricity,  darkness was related to fear and danger, and light was related to safety and trust. 

This is where this whole "white/black" opposition comes from, it was never about skin color.

**Comment by eternoendless** [comment]
**Update:** I shouldn't have gone political, sorry.

I'd be OK with choosing "allowlist" and "blocklist", which are as easy or even easier to understand than the former ones. Given the choice between a semantically charged word and one that means exactly what we intend, the choice is simple. 

However, renaming public code is a breaking change, which we try to avoid. Renaming private items only makes no sense because the offending wordings will still be present in public code. Moreover, having two ways to refer to the same thing introduces inconsistencies which result in increased complexity, so I'd prefer avoiding it.

_Some_ code units and comments could be renamed, like in `AdminController` and `FrontController`... but is it worth it? We generally don't accept cosmetic changes unless they make the code clearer to understand.

> Sorry, but I can no longer contribute to a project like this!

I'd be very sorry to see you go away for this @PululuK

**Comment by ttoine** [comment]
that's the purpose. to make a change about this social contract.

**Comment by PululuK** [comment]
Je vous écris en Français, comme ça on se comprends mieux peut-être et vous arretez de me prendre pour un CON !
Le PR  proposé par @Sinepel me semble avoir des bonnes intentions (même si je suis pas tout à fait d'accord, et je precise que je ne soutiens pas **BlackLivesMatter**). Cepandant j'ai été choqué par la manque de pédagogie, la violence et l'ironie de vos commentaires.

Vous perdez votre temps à m'écrire de longs commentaires, qui n'ont rien à voir  ! 

Comprennez l'intention de ce PR, ré-lisez vos commentaires !

Bye

**Comment by sowbiba** [comment]
@PululuK je suis aussi noir que toi et je te met ici le meme message que celui que j'ai mis à mes collègues. Ma mentalité est complètement assumée et je n'ai pas peur de la rendre publique

"Bon je suis en congé mais je suis tombé sur ce débat. J'avais donné ma position, je la redonne. Blacklist/Whitelist sont des termes qu'on utilise en informatique depuis des décennies. Et ils n'ont rien à voir avec la couleur de peau et je ne me sens aucunement offensé en les lisant. Changer ces termes ne changera rien à la cause des minorités. Si c'est pour clamer "on soutient la cause", vaut mieux le faire clairement et **officiellement**. Et de mon avis, prendre certaines positions c'est admettre la différence. C'est un problème de fond, de comportement. Dans un monde idéal, que ton interlocuteur soit black,white,yellow, aucune différence de traitement, de discours ... ne devrait être faite. Voilà l'objectif"

Qu'on n'utilise plus blacklist/whitelist mais qu'on continue avec cette mentalité qui pense qu'en Afrique les gens ont 10ans de retard, ou d'autres préjugés encore plus offensants, pour moi c'est un coup d'épée dans la mer

Tu continueras à entendre "je suis d'humeur noire" dans les conversations, ou d'autres expressions de ce genre.
Pour moi l'essentiel est d'être respecté et qu'on arrive à ne pas voir différemment 2 personnes pour des histoires de genre, de couleur, d'handicap ou whatever

De même que je suis contre le genre de réponse qui dit "oui, tu fais cette PR mais c'est le point de vue d'un white guy". Encore une fois on met en avant la couleur de peau

**On nous a clairement dit de ne plus prendre de position politique dans le cadre de notre travail. Ce message est strictement personnel et n'engage en rien la société PrestaShop**

**Comment by sowbiba** [comment]
Concernant la PR, si ça fait que certains se sentent plus à l'aise, pourquoi pas, ça ne changera pas ma vie, loin de là

Par contre, ça fera jurisprudence pour pleins de changements parce que tel ou tel terme peut etre interprété autrement dans un autre contexte. Et je défendrai bec et ongles ces autres changements si celui-ci passe ... égalité de traitement pour tous les cas oblige

**Pull request closed without merging**
