### PR TITLE
[*] BO Shop Link Change

### PR DESCRIPTION
**Pull request by ShepherdV8**
Please take the time to edit the "Answers" rows with the necessary information:

| Questions | Answers |
| --- | --- |
| Branch? | Develop |
| Description? | Shop Link Change. |
| Type? | [*] |
| Category? | BO |
| BC breaks? | No |
| Deprecations? | No |
| Fixed ticket? | None |
| How to test? | After fresh install of 1.7 Alpha 3 click the shop link at top of BO page. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [the PSR-2 Coding Style](http://doc.prestashop.com/display/PS16/Coding+Standards)!
- Your commit MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)

The BO shop link will open in the current window when clicked this change will open shop link in a new tab.

### CODE REVIEW

**Comment by ShepherdV8** [comment]
Why is this failing I followed the Instuctions for Git to the letter.

**Comment by firstred** [comment]
Hi,

It doesn't seem to be related to your Pull Request. Travis is unable to download Google Chrome in order to start the tests.
To me the PR looks good!

**Comment by ShepherdV8** [comment]
OK Thanks, I thought I did something wrong again, so I assume this is on Githubs side and nothing I can do or change.

**Comment by firstred** [comment]
Not sure what's causing it.
It could be a wrong command in the Travis script or some connectivity problems with Travis.

You can always force a rebuild by amending your commit and force pushing it again:
```shell
git commit --amend
git push -f
```

**Comment by ShepherdV8** [comment]
If the pull is OK I will just leave it as is as I see a lot of pull request with the red x.

**Comment by firstred** [comment]
Yes, the cause has been found: Chrome was no longer working on Ubuntu 12.04, so the Travis instance has been upgraded to 14.04

**Comment by ShepherdV8** [comment]
Good to hear, see how it goes on my next request.

**Comment by ShepherdV8** [comment]
Is this [*] FO Shopping Cart Change merged with the [*] BO Shop link change I am lost here.
How do I make the Commits separate and make a new Pull request for each commit.
Or is this just how Github works I thought I would have to create a new pull request.
I am using Tortoisegit to submit the commit.

**Comment by ShepherdV8** [comment]
I am closing this and starting over I am sorry for what seems to be a screw up I am going to recreate my local clone and then do each request again without updating the local from the prestashop repo.
I suppose that did something to cause the merge.

**Pull request closed without merging**
