### PR TITLE
[-] BO : Set stock option the same for all context shops when creating a new product

### PR DESCRIPTION
**Pull request by erouvier29**

### CODE REVIEW

**Comment by eric-rouvier** [comment]
@jeromenadaud: Following your remark about sharing stock, I think it is already managed by StockAvailable::setProductDependsOnStock through StockAvailable::addSqlShopParams: updated/inserted ps_stock_available entry contains id_shop or is_shop_group depending on group share stock option.

**Comment by jeromenadaud** [comment]
Hi, can you please use PSR-2 norms and rebase your PR ?

{ missing after foreach($id_shops as $id_shop) and indentation is 4 spaces.

Best regards.

**Comment by eric-rouvier** [comment]
PSR-2 should be ok now.
How to rebase?
Regards

**Comment by jeromenadaud** [comment]
git rebase -i sha-1, is very use full when you have a lot of commits.

**Pull request merged**
