### PR TITLE
Fix spacing, padding and bugs on responsive

### LINKED ISSUE #22911: [RESPONSIVE - BO] Fix spacing, padding and bugs
Epic: https://github.com/PrestaShop/PrestaShop/issues/22358 

#### Describe the bug

Theses pages have spacing and padding issues and need to be fixed.

#### Expected behavior

Fix spacing and padding in order to keep consistency between BO pages. 

SELL - Catalog > Products: 
- [x] Add a 12px spacing between _"Filter by category button"_ and _"Bulk actions"_ 
product
- [x] Enlarge placeholder in the table because it can't be read sometimes
_Add screenshots_

SELL - Catalog > Categories:
- [x] Fix bug on KPIs pan size
- [x] Enlarge placeholder in the table

IMPROVE - Module Catalog:
- [x] Add a 12px spacing between the search bar and the _"Category"_ select
- [x] Fix tooltips display and place it right next to the subtitle
- [x] Make the _"Categories" select" on full width
- [x] Add a 8px spacing between the module rating and the _"Install"_ block button
- [x] Add padding of 16px on _"Install"_ block button
module catalog

IMPROVE - Design > Theme & Logo
- [x] Fix tabs display

IMPROVE - Payment > Payment Methods
- [ ] Use UI Kit because the info alert design at the bottom of this page _"More modules on addons.prestashop.com"_ is wrong => Module issue, not core

IMPROVE - International > Localization
- [ ] Use UI Kit because the checkbox design in _"Content to import"_ section is wrong => Backend issue

CONFIGURE - Shop Parameters > Traffic & SEO: 
- [x] Add a 12px spacing between _"Learn more"_ and _"Configure index page"_ button

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There was some bugs on responsive that we wants to fix in order to provide the best UX
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22911.
| How to test?      | See issue, these bugs are on different pages

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22919)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @NeOMakinG 
I noticed some few difference between the PR and the screenshots in the epic:

**In the epic i have this**
image
**With or without the PR i don't**
image

**In the epic the subtitle is in bold and the "tooltip" button look like this**
image
**With your PR the result is different**
image

And can you be more specific for this part
image

Except the reported points the other fix seems OK

**Comment by NeOMakinG** [comment]
Hey @SD1982, Thanks for testing, I pushed the font-weight on the title

The info icon is linked to the UIKit, we couldn't use the outline one for a reason I forgot

The header is not linked to this PR at all, and there is a bug fixed in another PR on this

For placeholders, sometimes you've a placholder with like 20px of weight, and now you've a min-width : 

image

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @NeOMakinG 
Just one last point 
With a larger mobile device size ( ipad mini  for exemple ) the placeholders looks like before
image

**Comment by NeOMakinG** [comment]
@SD1982 I did use the 1024px breakpoint there

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM now !!
Thanks @NeOMakinG !!

**Comment by Progi1984** [comment]
Thanks @SD1982 & @NeOMakinG

**Pull request merged**
