### PR TITLE
Load theme css on maintenance page

### LINKED ISSUE #13505: errors/maintenance.tpl does not include custom.css in head
**Describe the bug**
The errors/maintenance.tpl does not include  themes/child_classic/assets/css/custom.css when it is present on the file system, making it impossible to easily use custom CSS on the maintenance page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Admin -> Configure -> Shop Parameters -> Maintenance
2. Enable Maintenence Mode
3. Check the HEAD content that is rendered.
4. It does not include custom.css

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: N/A

I'm a newbie to PrestaShop - I checked maintenance.tpl - that uses _partials/stylesheets.tlp - and a PHP $stylesheets variable that is passed in. I'm not sure that I want to dicker with the stylesheet logic in the PHP application.

Please fix so that custom.css is included when present on the file system.
Thank you

### PR DESCRIPTION
**Pull request by Prestaworks**
loads the theme css including custom.css on maintenance page.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix for issue 13505
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Follow instructions in issue report.
| UI Tests | https://github.com/florine2623/testing_pr/actions/runs/7102350393
| Fixed issue or discussion?     | Fixes #13505 
| Sponsor company   | Prestaworks AB

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
After this change, the maintenance page loads all theme.css and custom.css and everything that modules have registered.

The idea could be to create a maintenance.css with some basic styling for this page + of course, loading custom.css.

What do you think @Prestaworks ?

**Comment by Prestaworks** [comment]
> After this change, the maintenance page loads all theme.css and custom.css and everything that modules have registered.
> 
> The idea could be to create a maintenance.css with some basic styling for this page + of course, loading custom.css.
> 
> What do you think @Prestaworks ?

I was thinking that also, but then, many themes has "theme configurator" modules that attach specific css rules depending on settings, so maybe the shop owner has loaded a specific background color or font. Then it would be nice if the maintenance page follow the same basic rules without specific css files, right?

If this is not wanted, then I can change to only include custom.css, that is a quick change. maintenance.css can also be added, but there is already error.css specificly loaded on the maintenance page.

**Comment by kpodemski** [comment]
@Prestaworks ok, so maybe let's load custom.css without adding everything else

regarding maintenance.css, I think you are right, we can target:

`.page-content.page-maintenance`, the only thing missing is that `<body>` has no specific class, so maybe the ultimate solution could be to:

- load custom.css
- add:
```
'body_classes' => [
    'maintenance-mode' => true
]
```

modify `layout-error.tpl` with:

`<body class="{$body_classes|default:[]|classnames}">`

What do you think?

I'll also ping @Hlavtox  - maybe it's an overkill and there's no need to do that :)

**Comment by matks** [comment]
> After this change, the maintenance page loads all theme.css and custom.css and everything that modules have registered.

Is it a big problem? It's a maintenance page, it's not supposed to be used often. So I feel OK to make it a bit bloated.

At least if we load all the CSS we're sure the developers have everything they could need 😄 ?

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Prestaworks ,

With your PR, the changes are well taken into account in the maintenance page.

Following the steps from the issue, here's what I have now :
Screenshot 2023-12-05 at 15 44 53

It's QA ✅ (waiting for the auto tests to finish before merging please)

**Review by boherm — APPROVED** [review]

**Comment by mflasquin** [comment]
thanks @Prestaworks 😉

**Pull request merged**
