### PR TITLE
Fix product pages tabs

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix product page tabs behavior after bootstrap update
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3812
| How to test?  | Click on product page tabs

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Does it require a npm update somewhere?

**Comment by nihco2** [comment]
@Quetzacoalt91 nope

**Comment by Quetzacoalt91** [comment]
I still have an issue when switching to another tab then going back to the first one, as you can see:
capture du 2017-09-21 14-42-23

The textarea disapperead under "description"

**Review by LittleBigDev — DISMISSED** [review]
Seems ok.

**Comment by nihco2** [comment]
@Quetzacoalt91 fixed !

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @nihco2

**Pull request merged**
