### PR TITLE
Increase size of the hours column in PREFIX_store db table

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | see https://github.com/PrestaShop/PrestaShop/pull/7555
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | see https://github.com/PrestaShop/PrestaShop/pull/7555
| Sponsor company | impSolutions

PS: I don't know what's next, 1.7.0.6 or 1.7..1? :| i hope that 1.7.0.6 as we have very important bugfix related to `{widget_block}` feature

### CODE REVIEW

**Comment by xBorderie** [comment]
I guess such a change could only happen in a minor version anyway, so 1.7.1.0.

**Comment by kpodemski** [comment]
I'm not that sure because it's bugfix

**Comment by maximebiloe** [comment]
It's a bugfix, but it needs a database structure change, so it will be in a minor version.
Could you change the modification you made in `1.7.0.6.sql` to make it in `1.7.1.0.sql` and change the destination branch of your PR to `1.7.1.x`, please? It may require a rebase, but we'll try to embed it into 1.7.1.

Regards

**Comment by maximebiloe** [comment]
Hello @kpodemski,

Would you mind changing the `1.7.0.6.sql` file to `1.7.2.0.sql`, please?

Regards

**Comment by aleeks** [comment]
Rebased from develop, thank you @kpodemski

**Pull request merged**
