### PR TITLE
Fix FormSubmitButton method

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | 1. Fix form method: Before, always 'POST' (I think it was lost in some Merge)<br>2. Fix _method value to btnMethod. Previously only GET or POST even if the button had another
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | https://github.com/PrestaShop/PrestaShop/pull/20508#issuecomment-686628912

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20508)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
@davidglezz  Thank you for your contribution. :hugs: 

Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Comment by davidglezz** [comment]
It is an improvement, which could prevent current and future bugs. I made this improvement theoretically because when I saw the code I did not see it coherent.

It would be necessary to verify that the pages that use it continue to work well.

It is currently used in 4 pages to delete items.

- Delete product from brands
image
- Delete address Dropdown
- Delete Category thumbnail
- Delete Category cover


Find `js-form-submit-btn`
https://github.com/PrestaShop/PrestaShop/search?q=js-form-submit-btn&unscoped_q=js-form-submit-btn

**Comment by Progi1984** [comment]
@davidglezz Ok for me. I send it to QA (I updated your PR).

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1m68NyHuEQB3BJFqhtcBYim4dNzzgkFTe/view?usp=sharing
Thanks!

**Comment by Progi1984** [comment]
Thanks @davidglezz & @khouloudbelguith

**Pull request merged**
