### PR TITLE
Fix Symfony Kernel in WebService dispatcher in 1.7.8.x

### LINKED ISSUE #27411: Webservice API error Undefined offset when enabling multilanguage
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Try to run this API Call

API CALL TO:

`/api/cart_rules
`
METOD POST

BODY

```
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<cart_rule>
<date_from><![CDATA[{{formatDate(now; "YYYY-MM-DD HH:MM:SS")}}]]></date_from>
<date_to><![CDATA[{{formatDate(addDays(now; 1); "YYYY-MM-DD")}} 23:59:59]]></date_to>
<name><language id="1" xlink:href="https://www.vinove.it/api/languages/1"><![CDATA[SCONTO CARRELLO {{3.firstname}} {{3.lastname}}]]></language></name>
<code><![CDATA[{{upper(base64((3.id) + "*" + formatDate(now; "SS")))}}]]></code>
<reduction_percent><![CDATA[5.00]]></reduction_percent>
<active><![CDATA[1]]></active>
<id_customer><![CDATA[{{3.id}}]]></id_customer>
<quantity><![CDATA[1]]></quantity>
<description><![CDATA[ Sconto valido 24h sul tuo carrello ]]></description>
<quantity_per_user><![CDATA[1]]></quantity_per_user>
</cart_rule>
</prestashop>
```

Retunr this error
```
[500] [PHP Notice #8] Undefined offset: 2 (/var/www/html/vinove/classes/webservice/WebserviceOutputJSON.php, line 98)
[PHP Notice #8] Undefined offset: 3 (/var/www/html/vinove/classes/webservice/WebserviceOutputJSON.php, line 98)
[PHP Notice #8] Undefined offset: 4 (/var/www/html/vinove/classes/webservice/WebserviceOutputJSON.php, line 98)
```

### Expected behavior

Cart rule applied with only language 1 (default) and other language empty

### Steps to reproduce

1. Instal PS without data
2. Make an API CALL
3. Pass the language "1" field name
4. Check output JSON

### PrestaShop version(s) where the bug happened

1.7.6.9

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | backport of https://github.com/PrestaShop/PrestaShop/pull/24403
| Type?             | bug fix
| Category?         | WS
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27411
| How to test?      | See issue
| Possible impacts? | no
| Sponsor company   | Creabilis.com

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27622)

### CODE REVIEW

**Comment by jf-viguier** [comment]
Hey maintainers, PR already validated and QA tested here https://github.com/PrestaShop/PrestaShop/pull/24403 (web service stuff)

**Review by PululuK — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by khouloudbelguith — COMMENTED** [review]
Hi @jf-viguier,

I did not manage to reproduce the issue with the 178x branch.
I tried to create a cart rule via API => ok
I used this script

```php
<prestashop xmlns:xlink="http://www.w3.org/1999/xlink">
<cart_rule>
<date_from>2022-01-20 23:00:00</date_from>
<date_to>2022-06-20 23:59:59</date_to>
<name><language id="1">Cart Rule with -10% promotion</language></name>
<code>khouloud</code>
<reduction_percent>5</reduction_percent>
<active>1</active>
<id_customer></id_customer>
<quantity>3</quantity>
<description>description</description>
<quantity_per_user>2</quantity_per_user>
</cart_rule>
</prestashop>
```
https://user-images.githubusercontent.com/16067358/153424960-88c3aba6-a9ca-4cb1-b677-53d9a390773d.mp4

I tried to add a new category via API => ok
I used this script
```php
<prestashop>
	<category>
		<id>47</id>
		<id_parent format="isUnsignedInt">2</id_parent>
		<active required="true" format="isBool">1</active>
		<id_shop_default>1</id_shop_default>
		<id_root_category>0</id_root_category>
		<name required="true">
			<language id="1" xlink:href="http://prestashop.tn/PrestaShop/api/languages/1">upup</language>
		</name>
		
		<link_rewrite>
			<language id="1" xlink:href="http://prestashop.tn/PrestaShop/api/languages/1">rewrite</language>
		</link_rewrite>
		<associations>
			<categories nodeType="category" api="categories">
				<category xlink:href="http://prestashop.tn/PrestaShop/api/categories/4">4</category>
			</categories>
			<products nodeType="product" api="products">
				<product xlink:href="http://prestashop.tn/PrestaShop/api/products/1">
					<id>1</id>
				</product>
				</products>
		</associations>
	</category>
</prestashop>
```

https://user-images.githubusercontent.com/16067358/153425262-f669884e-4ace-4028-8242-1a8524034b0b.mp4

Did I miss something?

Thanks!

**Review by Amoifr — COMMENTED** [review]
Thks also for the clean-up ;-)

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I reproduced the issue with PS1783 only when we install a shop **without data**.
https://github.com/PrestaShop/PrestaShop/issues/27629#issuecomment-1036093781

Thanks!

**Review by khouloudbelguith — APPROVED** [review]
Hi @jf-viguier,

It is ok :heavy_check_mark: 
Install shop with no data:
1. add a category via API
2. add a cart rule via API
3. add a product via API
4. update category via API
5. delete a category via API
6. Add catalog price rule via API
7. add a customer via API
8. add order status via API

Install a shop with data:
1. add a category via API
2. add a cart rule via API
3. 8. add order status via API

https://user-images.githubusercontent.com/16067358/153859659-236a9e97-2068-459f-aead-3d86e2d52a1d.mp4

**Without PR**
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @jf-viguier & @khouloudbelguith

**Comment by matks** [comment]
Hello everyone I'm sorry for coming back to this PR but initially I was against merging https://github.com/PrestaShop/PrestaShop/pull/26205. See my comments https://github.com/PrestaShop/PrestaShop/pull/26205#pullrequestreview-830170348

I still believe https://github.com/PrestaShop/PrestaShop/pull/26205 is not the proper way to fix this issue. Booting the kernel on every request to the webservice is overkill. I think we should not have added this to the project.

@PululuK  @PierreRambaud  wdyt?

EDIT: to provide a little bit of context

It means that if someone has a shop that does not use multilang, the loading of the kernel is useless for him, just waste of CPU.
It means that if someone handles 1,000 HTTP requests for the webservice and only 1 needs multilang loaded, then 999 webservice requests did load the kernel for nothing. Waste of CPU again

**Comment by matks** [comment]
@jolelievre provided a cool compromise https://github.com/PrestaShop/PrestaShop/pull/27766

**Comment by jf-viguier** [comment]
@jolelievre thanks

**Comment by jolelievre** [comment]
And similar modification on develop https://github.com/PrestaShop/PrestaShop/pull/27770

I know using legacy code like this is far from ideal, but in a legacy environment do as the legacies did

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/27766 was merged 🎉 thank you everyone

**Pull request merged**
