### PR TITLE
New hook for performing actions when address change on cart

### PR DESCRIPTION
**Pull request by Prestaworks**
New hook for performing actions when address change on cart

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR adds a new hooks actionUpdateCartAddress that triggers when address is changed on cart. This is usefull for recalculating shipping or checking if customer changes from private to buisness address for instance.
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Sponsor company   |  Prestaworks AB
| Related PRs | https://github.com/PrestaShop/autoupgrade/pull/563

## Summary by CodeRabbit

- **New Features**
  - Introduced a new event trigger that activates after the delivery address on the cart is updated, allowing integrations to respond to address changes in the cart.

### CODE REVIEW

**Comment by kpodemski** [comment]
Thanks @Prestaworks !

Two things are missing:
- you have to add new hooks to hook.xml
- there has to be an autoupgrade PR created for 9.0.0.sql :)

**Comment by Prestaworks** [comment]
> Thanks @Prestaworks !
> 
> Two things are missing:
> 
>     * you have to add new hooks to hook.xml
> 
>     * there has to be an autoupgrade PR created for 9.0.0.sql :)

9.0.0.sql, that's on the autoupgrade module?

**Review by kpodemski — APPROVED** [review]
Thanks @Prestaworks 

Yes, related pr should be about `autoupgrade` module :)

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
@Prestaworks thank you for your contribution 👍 

I saw that you made the autoupgrade pull request, as I said I think it's better to wait until this PR is merged before the autoupgrade pull request can be merged

**Comment by 0x346e3730** [comment]
Hello @Prestaworks, thank you for your contibution !
I have one question however : how can you consume the hook and know if it's the billing or the delivery address that has been changed ? "cart" seems a bit too much generic for me as it can be either one.

**Comment by Prestaworks** [comment]
> Hello @Prestaworks, thank you for your contibution ! I have one question however : how can you consume the hook and know if it's the billing or the delivery address that has been changed ? "cart" seems a bit too much generic for me as it can be either one.

One of the functions is a bit generic also, 
function updateAddressId this will update both adresses if needed.

function updateDeliveryAddressId is a bit more specific-

I guess we could add params to the hook for invoiceAddressWasChanged and deliveryAddressWasChanged if you think that's a good idea? 
But a module using the hook can also check to old and new address id and compare it to the adress on the cart to see if the new address is set on the field thats used by the module.

**Comment by 0x346e3730** [comment]
> > Hello @Prestaworks, thank you for your contibution ! I have one question however : how can you consume the hook and know if it's the billing or the delivery address that has been changed ? "cart" seems a bit too much generic for me as it can be either one.
> 
> One of the functions is a bit generic also, function updateAddressId this will update both adresses if needed.
> 
> function updateDeliveryAddressId is a bit more specific-
> 
> I guess we could add params to the hook for invoiceAddressWasChanged and deliveryAddressWasChanged if you think that's a good idea? But a module using the hook can also check to old and new address id and compare it to the adress on the cart to see if the new address is set on the field thats used by the module.

I won't block the PR as it's already been approved I just wanted to raise the point because of the use case you gave in the PR description. The parameter to specify which address could be a solution but I don't see it as blocking if it's achievable elsehow.

**Review by MhiriFaten — APPROVED** [review]
Hello @Prestaworks,

LGTM, it's QA approved :heavy_check_mark: 

Thank you!

**Comment by kpodemski** [comment]
Thank you @Prestaworks 🎉

**Pull request merged**
