### PR TITLE
Fix bag with Cart::getPackageSthippingCost cache id

### PR DESCRIPTION
**Pull request by webmak**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | The cart cache key should take the id_zone into account
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @webmak 
Can you respect our norms ? Preston helps you! Without response of you, this PR will be closed.

Regards

**Comment by antoin-m** [comment]
Thank you @webbax, I updated your PR so that it follows our guidelines.

**Comment by webmak** [comment]
Thanks @antoin-m. Where can I read about requirements to pass your PR validation?

**Comment by antoin-m** [comment]
You can find our guidelines here : http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Don't worry about this PR, it will be merged just before the 1.6.1.12 is released 😃

**Comment by maximebiloe** [comment]
Thanks @webmak

**Pull request merged**
