### PR TITLE
[-] CORE : Fix #PSCSX-3480 htaccess generation with media server

### PR DESCRIPTION
**Pull request by sfroment**
- follow up https://github.com/PrestaShop/PrestaShop/commit/2bdd9f1f910cc148c86a43fb08879404f0acf480 to handle friendly url with different media server per shop

(cherry picked from commit f8b3693f5a796fa8037efb953c81270f897daa96)

### CODE REVIEW

**Comment by sfroment42** [comment]
#3416

**Comment by momo1240** [comment]
hello, thank you for these modifications 
I'm trying to implement it on ps 1.5.6
I have this error Call to undefined method Configuration::getMultiShopValues()
is "Configuration::getMultiShopValues" working on ps 1.5
thank you

**Comment by Quetzacoalt91** [comment]
Hello,

There a PS guide o the PrestaShop validator which allows you to know the compatibility range of a specific function / method /class from the core. https://validator.prestashop.com/guide/search

`Configuration::getMultiShopValues()` exists from PS 1.6.0.3

**Comment by momo1240** [comment]
Hello,
thank you for your reply sir 
Now I understand why I can't use it on ps 1.5.6
I was wondering is there is an equivalent of "Configuration::getMultiShopValues()" for ps 1.5.6

thank you

**Comment by momo1240** [comment]
Hello,
thank you for your reply sir
I made an override for this function on class/configuration.php
I made all changes but something wrong with the htaccess generation
I should have this :
^cdn1.domaine.fr
^cdn2.domaine.fr
^cdn3.domaine.fr
^www.domaine.fr

and then the same thing for domaine.com

instead I have
^cdn1.domaine.fr
^cdn1.domaine.com
^cdn2.domaine.fr
^cdn2.domaine.com
^cdn3.domaine.fr
^cdn3.domaine.com
^www.domaine.fr

I just changed on ps 1.5.6 : class/tools.php:
if (!$medias)
$medias = array(MEDIA_SERVER_1, MEDIA_SERVER_2, MEDIA_SERVER_3);

$media_domains = '';
if ($medias[0] != '')
	$media_domains = 'RewriteCond %{HTTP_HOST} ^'.$medias[0].'$ [OR]'."\n";
if ($medias[1] != '')
	$media_domains .= 'RewriteCond %{HTTP_HOST} ^'.$medias[1].'$ [OR]'."\n";
if ($medias[2] != '')
	$media_domains .= 'RewriteCond %{HTTP_HOST} ^'.$medias[2].'$ [OR]'."\n";
TO

if (!$medias && Configuration::getMultiShopValues('PS_MEDIA_SERVER_1')
&& Configuration::getMultiShopValues('PS_MEDIA_SERVER_2')
&& Configuration::getMultiShopValues('PS_MEDIA_SERVER_3')
) {
$medias = array(
Configuration::getMultiShopValues('PS_MEDIA_SERVER_1'),
Configuration::getMultiShopValues('PS_MEDIA_SERVER_2'),
Configuration::getMultiShopValues('PS_MEDIA_SERVER_3')
);

$media_domains = '';
foreach ($medias as $media) {
foreach ($media as $media_url) {
if ($media_url) {
$media_domains .= 'RewriteCond %{HTTP_HOST} ^'.$media_url.'$ [OR]'."\n";
}
}
}

or maybe the override I did for ps 1.5 in class/configuration.php

public static function getMultiShopValues($key, $id_lang = null)
	{
		$shops = Shop::getShops(false, null, true);
		$resultsArray = array();
		foreach ($shops as $id_shop)
			$resultsArray[$id_shop] = Configuration::get($key, $id_lang, null, $id_shop);
		return $resultsArray;
	}
	
}

Thanks for your help

**Pull request closed without merging**
