### PR TITLE
Improve compatibility between PHP 7.1 and PrestaShop

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | When gettig the homepage with a server running PHP 7.1 (which seems to be more strict), a fatal error was thrown because a string variable used as an array. |
| Type? | bug fix |
| Category? | CO |
| BC breaks? | Nope |
| Deprecations? | Nope |
| Fixed ticket? | / |
| How to test? | Switch on PHP 7.1 and go to the homepage. You should not have the following issue. |

**Fatal error:** Uncaught Error: [] operator not supported for strings in /Users/tNabord/Documents/github/PrestaShop/classes/db/DbQuery.php:96 Stack trace: #0 /Users/tNabord/Documents/github/PrestaShop/src/Adapter/EntityMapper.php(46): DbQueryCore->from('shop', 'a') #1 /Users/tNabord/Documents/github/PrestaShop/classes/ObjectModel.php(233): PrestaShop\PrestaShop\Adapter\EntityMapper->load('1', NULL, Object(Shop), Array, NULL, true) #2 /Users/tNabord/Documents/github/PrestaShop/classes/shop/Shop.php(135): ObjectModelCore->__construct('1', NULL, NULL) #3 /Users/tNabord/Documents/github/PrestaShop/classes/shop/Shop.php(414): ShopCore->__construct('1') #4 /Users/tNabord/Documents/github/PrestaShop/config/config.inc.php(112): ShopCore::initialize() #5 /Users/tNabord/Documents/github/PrestaShop/index.php(27): require('/Users/tNabord/...') #6 {main} thrown in /Users/tNabord/Documents/github/PrestaShop/classes/db/DbQuery.php on line 96

### CODE REVIEW

**Comment by firstred** [comment]
Nice one. Thanks!

**Comment by mickaelandrieu** [comment]
Maybe can we add PHP 7.1 to the build?

**Comment by Quetzacoalt91** [comment]
Not yet, there are still more issues to fix before PrestaShop can run successfully on PHP 7.1.

I saw another one in the Hook class, but couldn't find how to fix it yet.

**Comment by maximebiloe** [comment]
Thanks!

**Pull request merged**
