### PR TITLE
PDF documents unformatted

### LINKED ISSUE #9527: [BOOM-6197] PDF documents unformatted
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-6197).

- _**Reporter:**_ exeicomltd
- _**Created at:**_ Mon, 6 Aug 2018 16:12:41 +0200

<p>Hello!<br/>
I've installed prestashop 1.7.4.2 and, when I try to print (for example) an order, I see an unformatted document (see attachement).<br/>
This not happened in version 1.7.3.0....<br/>
Can anyone help me?<br/>
Many thanks,</p>

<p>Daniele</p>
        
* How to reproduce the issue ?

Ask me the admin access to BO and simply open order and print....
image

### PR DESCRIPTION
**Pull request by rdy4ever**
Fix for #9527

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix for #9527
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9527
| How to test?  | In the Admin back office, try to print an order.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10135)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by ntiepresta** [comment]
Hi, @rdy4ever 
we manage to reproduce the issue with PS 1.7.4.0 . But this modification doesn’t resolved the issue. We have the same behavior after correcting
Best regards, Reddy Ntie

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
I confirm it does work.

capture du 2018-09-07 14-55-36


@rdy4ever, I updated your PR by rebasing an regenerating the assets, I hope you don't mind.
@ntiepresta can you please try again?

**Comment by ntiepresta** [comment]
@Quetzacoalt91 ,
Ok, No problem.

**Comment by rdy4ever** [comment]
@Quetzacoalt91 no problem, thanks!

**Comment by PierreRambaud** [comment]
Thanks @rdy4ever

**Pull request merged**
