### PR TITLE
Merge 8.1.x to develop

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge `8.1.x` into `develop`
| Type?             | improvement 
| Category?         | ME 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by cdesiles — APPROVED** [review]

**Comment by matks** [comment]
Tests running https://github.com/matks/ga.tests.ui.pr/actions/runs/5854105872

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
cc @PrestaShop/qa-automation, some tests are red even tho merge commits seem to be unrelated, can we merge?

**Review by LouisAUTHIE — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
```
1) BO - Orders - Credit slips : Sort (by ID, Date and OrderID) and Pagination of Credit Slips
       Create Credit slip n°11
         should check the existence of the Credit slip document:

      AssertionError: expected 'Delivery slip' to equal 'Credit slip'
      + expected - actual

      -Delivery slip
      +Credit slip
```
This problem seems indeed not related to the PR body. I ran the tests twice.

**Review by boherm — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
Hello @matks 
UI tests are OK :green_circle: => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/5857911560
The only error exist in the nightly!

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @matks

**Pull request merged**
