### PR TITLE
A lot of code improvements

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR normalize a lot of uses and improve CS. The code becomes more simple, more easy to read and in some cases even faster.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Everything should work the same as before and Travis CI must pass.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11664)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Travis CI passed and there are no conflicts :)

**Comment by MathiasReker** [comment]
Both short and long array syntax are used. How about normalize it in this PR? If you think so, what do you prefer?

Same for list syntax?

**Comment by MathiasReker** [comment]
Ping @mickaelandrieu @matks @eternoendless @PierreRambaud

I spent a lot of hours on this PR and I read the changes more than once. This PR can get the CS up to date. Wdyt?

**Comment by MathiasReker** [comment]
The lint issue in Travis CI is caused, because I did not use one concat space in latest commit (Run PHP CS fixer)
Default PrestaShop rule says one concat space: https://github.com/PrestaShop/PrestaShop/blob/develop/.php_cs.dist#L14
But from this PR: https://github.com/PrestaShop/PrestaShop/pull/11646 I understand, that it is better to stick to default Symfony rule that says no concat space.

**Comment by mickaelandrieu** [comment]
Hi, let me review this with a cup of coffee. 

1920 files my friend, I need time!

Maybe next time it's easier to split all the improvement in multiples pull requests as you did on the ones I've merged.

Mickaël

**Comment by MathiasReker** [comment]
@mickaelandrieu I agree with you, that this PR is huge, maybe too big. But how about the conflicts if I spitted it into different PR's? :trollface:

**Comment by PierreRambaud** [comment]
Not sure we can approve this PR because of some rules are not in our cs fixer configuration. Wait for @eternoendless

**Comment by MathiasReker** [comment]
With the PR I aim to normalize everything one time for all. Then there could be some code in future PR's that does not have the same way structure, but for now it could be nice to have it normalized. It makes the code more easy to read and some of the improvement in this PR even makes the code faster.

There are bunch of old code in PrestaShop that would be nice to have updated. This PR solves a lot of it.

I know it is hard to review, but I really hope you will consider to merge this PR. I did read it all several times to catch any mistakes.

**Comment by MathiasReker** [comment]
@PierreRambaud I ran php-cs-fixer with PrestaShop rules to override any changes done in this PR :)

**Comment by MathiasReker** [comment]
If something in this PR should be changed please let me know and I will have look on it :)

**Comment by eternoendless** [comment]
Thank you @MathiasReker for your contribution. However, I think this PR is just too big and it will be way too time-consuming to review. The longer we take to review it, the more conflicts and even more time we'll have to spend reviewing it.

I suggest splitting it into smaller PRs. That way we will be able to review and merge them faster. If your changes are made using php-cs-fixer, consider discussing an update of our settings with the team first, then opening a PR containing those changes, and **only those**. Another PR can follow.

Also, try to avoid merging changes from upstream into your branch. It's better to rebase instead as it provides a cleaner log. If you don't know how, [here's a quick guide](http://build.prestashop.com/howtos/misc/rebasing-your-git-branch/).

I'm closing this one as it doesn't make sense as-is. You can also cherry-pick commits from this PR in your other PRs if it makes your work easier, but remember: one PR per change. 

Small PRs -> more chance of getting them merged 👍 

Looking forward to your follow-ups.

**Comment by MathiasReker** [comment]
@eternoendless Thanks, it makes sense. 👍

**Comment by MathiasReker** [comment]
@eternoendless as requested: https://github.com/PrestaShop/PrestaShop/pull/11718

**Pull request closed without merging**
