### PR TITLE
[BO][PRODUCTS] Add product count filtered

### LINKED ISSUE #20221: [BO][PRODUCTS] Add product count filtered
#### Is your feature request related to a problem?

Add product count filtered. Display number of products filtereds look Categorie page for example.

Capture du 2020-07-18 15-48-37

#### Describe the solution you'd like

Capture du 2020-07-18 15-47-29

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Add product count filtered. Display number of products filtereds look Categorie page for example.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20221.
| How to test?  | See  #20221.

## Before 
Capture du 2020-07-18 15-48-37

## After 

Capture du 2020-07-18 15-47-29

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20222)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi, the idea of adding `{{ product_count_filtered }}` is good but why change the markup of the page ?

Without a good reason to do this, we cannot do it because it changes the page selectors structure and consequently might break a module plugged on this page, using these selectors

**Comment by PululuK** [comment]
> Hi, the idea of adding `{{ product_count_filtered }}` is good but why change the markup of the page ?
> 
> Without a good reason to do this, we cannot do it because it changes the page selectors structure and consequently might break a module plugged on this page, using these selectors

Hey @matks, bon week-end !
Can you indicate the line concerned please?

**Comment by davidglezz** [comment]
This will add the title again. Maybe we should find a better place for the number


# Products
## Products (n)

It would be cool to be able to mix the above toolbar with the grid toolbar

**Comment by PululuK** [comment]
> This will add the title again. Maybe we should find a better place for the number
> 
> # Products
> ## Products (n)
> It would be cool to be able to mix the above toolbar with the grid toolbar

Hi @davidglezz 
This is the current behavior on all controllers. See BO Categories for example

**Comment by PululuK** [comment]
@matks @davidglezz the news ?

**Comment by PierreRambaud** [comment]
> @matks @davidglezz the news ?

Little reminder guys :)

**Comment by matks** [comment]
Apologies for late answer. Year is now 2021, we are working on a new Product page. Can you check the new Product page (see https://build.prestashop.com/news/prestashop-1-7-8-0-beta-release/) and see if changes would fit better in the new Product page ?

**Comment by PierreRambaud** [comment]
Hi @PululuK,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
