### PR TITLE
Merge build PR into 8.1.x

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Merge build PR into 8.1.x
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and UI tests green https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/5423319103/jobs/9861090485
| Fixed ticket?     | none
| Related PRs       | none
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @matthieu-rolland

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @matthieu-rolland ,

Could you relaunch the automated tests ?
There's an issue with **test (functional:BO:design, 8.1.x)**

Thanks!

**Review by aniszr — APPROVED** [review]
Hello @matthieu-rolland 

Thanks for your PR, blockwishlist and linklist modules versions are well updated :heavy_check_mark: 
See attached screenshots :
image
image

I tested #31379 and it LGTM :heavy_check_mark: 
Auto Test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5421210718

Thanks!

**Comment by matthieu-rolland** [comment]
Wait ! UI test is still broken

I'm on it

**Review by Progi1984 — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
test ui green: https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/5423319103/jobs/9861090485

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Pull request merged**
