### PR TITLE
Fixed update of combinations

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Fixed update of combinations
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Try to save Product with combinations using PHP 5.6

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8948)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
ping @eternoendless this is really important to ship 1.7.4.0 with this commit, or combinations save won't work with PHP 5.

**Comment by mickaelandrieu** [comment]
Thanks everyone for review!

**Comment by jf-viguier** [comment]
Thank you for the fix, we had this frustrating bug too.

**Comment by mickaelandrieu** [comment]
@jf-viguier sorry sorry^^ You should have updated your shops to PHP 7 already, why keep a slow version of PHP?

**Comment by jf-viguier** [comment]
Production is running php7 but preproduction not, we still have old websites to maintain

**Comment by mickaelandrieu** [comment]
@jf-viguier "je compatis" ^^, the update will be available in 1.7.3.2

**Comment by andrekat** [comment]
Somhow, this problem isnt fix at my shop 1.7.3.1. I've followed the commit but didnt worked :(
Please give advice

**Comment by ibnuzahari** [comment]
Hi @mickaelandrieu ....this update also not working on my website.
can you please advice. TQ

**Comment by unreviewed** [comment]
Not working on 1.7.5.1

**Pull request merged**
