### PR TITLE
Solution for PSCSX-5480

### PR DESCRIPTION
**Pull request by Amazzing**
http://forge.prestashop.com/browse/PSCSX-5480

### CODE REVIEW

**Comment by ZiZuu-store** [comment]
Please try to save DOM elements instead of reparse ..

Use a variable to store it

**Comment by Amazzing** [comment]
Do you mean something like that?:

```
if (typeof reviewsContent != 'undefined')
    var reviewsContent = $(element).find('.list-reviews')[0].outerHTML;
html += reviewsContent;
```
Well, it might be better, but all other elements are reparsed in the original function. For example:
`html += '<h5 itemprop="name">'+ $(element).find('h5').html() + '</h5>';`
So, probably it is better to keep the existing logic.

**Comment by ZiZuu-store** [comment]
I'm simply telling not to invoke the find() multiple times .. store the result and use it

var found = $(element).find('.list-reviews');

if found.length ..  found[0] .. and so on

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Comment by ZiZuu-store** [comment]
Again, *if* this PR is good someone in the core PS dev team should take the task of cherry picking it ... IMHO of course

**Comment by xBorderie** [comment]
It seems this one has been fixed with #4079 :)

**Comment by drAlberT** [comment]
LOL :)

**Pull request closed without merging**
