### PR TITLE
Avoid possibility to create product with combinations when combinations feature is disabled

### LINKED ISSUE #28967: Combinations feature disabled - Product V2 - We can create a product with combinations
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the BO > Advanced Parameters > Performance page > when we disable the combinations feature, we can still add a product with combinations or change the type product to a product with combinations

This issue is reproduced with PS1786 / 8.0.x

### Expected behavior

The feature can't be disabled if the there is at least on combination in the product catalog. If the feature is disabled, the combination option on the creation form modal and the product changement modal is not displayed and can't be selected.

### Steps to reproduce

1. Delete all products with combinations
2. Go to BO > Advanced Parameters > Performance page
3. Disable combinations
4. Go to BO > Advanced Parameters > New & experimental features page
5. Enable a New product page
6. Go to BO > Catalog > Product V2
7. Add a product with combinations => NOK, the type combinations should be hidden: ping @MatShir what do you think?
8. Edit any product > Change the type of product with combinations => NOK: The type combinations should be hidden ping @MatShir, what do you think?

### PrestaShop version(s) where the bug happened

1.7.8.6, 8.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Avoid possibility to create product with combinations when combinations feature is disabled
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28967
| Related PRs       | 
| How to test?      | See #28967
| Possible impacts? |

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
I think it changes the UX aspect of the modal as you moved the "Product with combinations" at the end of the list.

I think you should go for an `unset`. Let me know if I'm wrong 👍

**Comment by mflasquin** [comment]
> I think it changes the UX aspect of the modal as you moved the "Product with combinations" at the end of the list.
> 
> I think you should go for an `unset`. Let me know if I'm wrong +1

You're right :smile: I changed it

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
ping @PrestaShop/committers major issue fix to review

**Review by FabienPapet — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @mflasquin 

I have checked your RP, the bug is well fixed : 

- The issue of combinations feature is fixed and it can be disabled.
- Avoid possibility to create product with combinations.
- Automated tests are OK. 


[Untitled_ Jan 13, 2023 3_45 PM.webm](https://user-images.githubusercontent.com/111756615/212347576-08b4dd85-b1c1-47c0-9316-c48756ed4c62.webm)

So it's QA approved :heavy_check_mark: 
Many thanks !

**Comment by kpodemski** [comment]
Thank you, @mflasquin !

@PrestaShop/qa-team is on fire today! 🔥 💪🏻

**Pull request merged**
