### PR TITLE
[*] Project: Small fixes for use with PHP7

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

Can you detail this line  ? (https://github.com/PrestaShop/PrestaShop/pull/4175/files#diff-d373723286a172a4ca3d76c4858f565bR1384)
```php
(PHP_MAJOR_VERSION < 7 && !Validate::$values['validation'](Tools::getValue($field))) || !Validate::{$values['validation']}(Tools::getValue($field))
```

What problem are you trying to solve ?

**Comment by PrestaEdit** [comment]
Hi @julienbourdeau,

It's a fix that some days ago... Don't remember the way I do for have the error but it was a things like: "Can't access to an undeclared variable". Will try to see to have the error again...

**Comment by PrestaEdit** [comment]
Hi @julienbourdeau,

This error: "Fatal error: Uncaught Error: Access to undeclared static property: Validate::$values" when you wan't to update an option attach to an AdminController, is this ;-)

**Comment by Quetzacoalt91** [comment]
:+1: 

This closes #4298

**Comment by PrestaEdit** [comment]
I take your commit, cause it's really easier like this, for handle the _destruct ; to complete this one, :)

**Comment by therampagerado** [comment]
Will support for php7 be added into 1.6.1.2? Currently I have white screen when switching to 7

**Comment by Quetzacoalt91** [comment]
Hi @therampagerado,

Before asking for support, you always have to enable the Dev mode in order to have more details on the issue. :wink:

**Comment by ram-you** [comment]
Webservice is not 100% compatible with php7.
"SITENAME/api/products/?ws_key=xxxxxxxxxxxxxxxxxxxxxxx&output_format=xml" works.
"SITENAME/api/products/?ws_key=xxxxxxxxxxxxxxxxxxxxxxx&output_format=JSON" doesn't work.

Thank you.

**Pull request merged**
