### PR TITLE
Remove useMobileTheme()

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove useMobileTheme()
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no

## BC Break

Removed `FrontController:: useMobileTheme()`

### CODE REVIEW

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers 

Is it **really** a BC break that we shouldn't accept? That method has no actual behavior and was changed to this state seven years ago.

**Review by kpodemski — APPROVED** [review]
I'm leaving my approval. IMHO we can follow common sense there ;-)

**Comment by matks** [comment]
> I'm leaving my approval. IMHO we can follow common sense there ;-)

I agree :)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
We could even say it's not a BC break, it's a bugfix or it's "removing dead code" 😄

**Comment by matks** [comment]
@Robin-Fischer-PS this PR removes a completely useless piece of code forgotten since ages. Can we merge it without QA ? I ... don't even know what should be tested 😄

**Comment by NeOMakinG** [comment]
> @Robin-Fischer-PS this PR removes a completely useless piece of code forgotten since ages. Can we merge it without QA ? I ... don't even know what should be tested 😄

Nothing could be tested probably

**Pull request closed without merging**
