### PR TITLE
Update module versions in composer.lock (PS 8.1.x)

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | those are all patch module upgrades, except for `prestashop/productcomments` (5.0.3 => 6.0.2)
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and UI tests green
| UI Tests          | https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/6638369397
| Fixed issue or discussion?     | https://github.com/orgs/PrestaShop/projects/7/views/79?pane=issue&itemId=35204277
| Related PRs       | none
| Sponsor company   | Your company or customer's name goes here (if applicable).

## Updated modules:

- prestashop/blockreassurance :        v5.1.2 => v5.1.3
- prestashop/pagesnotfound :            v2.0.2 => v2.0.3            
- prestashop/productcomments :       v5.0.3 => v6.0.2            
- prestashop/ps_emailalerts :              v2.4.1 => v2.4.2            
- prestashop/ps_facetedsearch :        v3.13.1 => v3.13.2           
- prestashop/ps_featuredproducts :   v2.1.4 => v2.1.5            
- prestashop/ps_linklist :                      v6.0.3 => v6.0.4

### CODE REVIEW

**Review by M0rgan01 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@matthieu-rolland the PR description is not accurate 😉

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland the PR description is not accurate 😉

updated 👍

**Review by boherm — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @matthieu-rolland 

Thank you for your PR, I tested it and it seems to works as you can see : 

image

image

image

image

image

image

image

Because the auto test is :green_circle: and the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by matthieu-rolland** [comment]
I restarted the failed integration test, it was because of a timeout on a download... should be fine

**Comment by mflasquin** [comment]
thanks @matthieu-rolland !

**Pull request merged**
