### PR TITLE
Order page: fix stock value update when editing a product

### LINKED ISSUE #17971: The stock is not correctly recalculated after editing product quantity in the order
#### Describe the bug

The stock is not correctly recalculated after editing product quantity in the order

#### Expected behavior

Display the correct quantity in stock after editing the product quantity

#### Steps to Reproduce

1. Go to BO > orders > orders > view
2. Click on edit to change a product quantity
3. Increase or decrease the product quantity for +1 or -1
4. See the quantity in stock is increased of +2 or decreased of -2
5. If you save, the quantity in stock is correct

**Screenshots**
https://drive.google.com/file/d/18Vqi8NzBhrFfFjgnKvQ_mK0JFWtKaKiu/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | When editing a product in order page, the stock value for this product was badly recalculated (only frontend, before saving)
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17971
| How to test?  | 1. Go to BO > orders > orders > view<br>2. Click on edit to change a product quantity<br>3. Increase or decrease the product quantity<br>4. See the quantity in stock: it should be correct (the bug happened before saving, when the stock value is updated live)<br><br>See #17971 for more details

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18061)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
look fine

Edit: damn, it's wip

**Review by jolelievre — DISMISSED** [review]
Much clearer with `previousQuantity` !
Maybe it would be worth renaming `stock` in `availableQuantity` as well?

**Comment by matthieu-rolland** [comment]
> Much clearer with `previousQuantity` !
> Maybe it would be worth renaming `stock` in `availableQuantity` as well?

that's a good idea 👍 I'll do that

@jolelievre done

**Review by matks — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by boubkerbribri** [comment]
@matthieu-rolland can you please resolve conflicts

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland can you please resolve conflicts

done 👍

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by SD1982** [comment]
This PR correctly fix #17971 thanks @matthieu-rolland

**Comment by Progi1984** [comment]
Hello @matthieu-rolland , thanks for your contribution, would you mind to rebase your pull request? Thanks

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Pull request merged**
