### PR TITLE
[-] CORE : PHP 5.4 compatible

### PR DESCRIPTION
**Pull request by maximebiloe**
## Description

This PR meant to make PretaShop 1.7 running on PHP 5.4.
## Steps to Test this Fix

Install PrestaShop 1.7 with PHP 5.4 and browse :wink:

### CODE REVIEW

**Comment by kpodemski** [comment]
What is the point of having compatibility with dead 5.4? :) Even WP move compatibility up to 5.6...

**Comment by mickaelandrieu** [comment]
I disagree that we have to use a lower version of doctrine because of php requirements. 

We need to add a Polyfill, or create one but keep 5.4 *can't be a limitation* of PrestaShop in 2016.

**Comment by mickaelandrieu** [comment]
Except if I'm wrong doctrine orm and dbal requirements are 5.4 and 5.3, can you tell me the errors encountered @maximebiloe?

**Comment by kpodemski** [comment]
First of all why 5.4 not 5.6? I really didn't saw a hosting with 5.4 but without 5.6 for a long, long time!

**Comment by kpodemski** [comment]
Oldschool in da house
http://php.net/supported-versions.php

**Comment by maximebiloe** [comment]
Hi,

@mickaelandrieu, [this call](https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L62] is not compatible with PHP 5.4. The class name resolution has been introduced in PHP 5.5.
We could see to improve it later.

@kpodemski, we choose to be compatible with PHP 5.4 because is the last months, 30% of the new PrestaShop installs have been done with PHP 5.4. Also, composer has measured that 15% of users are still on PHP 5.4.

Regards

**Comment by kpodemski** [comment]
Hi @maximebiloe 

I'm not sure if that is good point, maybe people should be noticed that hosting provider can easily changed this version? On most of the servers 5.4 is by default but with option to change to 5.6 or even 7, if WP can ask users in the future to change their version why PrestaShop can't? If people wouldn't be forced to change things they'll still stuck on IE7 and XP

**Comment by mickaelandrieu** [comment]
@maximebiloe can you try to lock doctrine common to 2.5.3 in our composer?  The master branch requirements are 5.5.  This should solve this issue.  Thank you for your feedback.

**Comment by maximebiloe** [comment]
Thanks @mickaelandrieu, I've locked doctrine on 2.5.

**Comment by maximebiloe** [comment]
@kpodemski, WordPress recommends PHP 5.6 but they still supports PHP 5.2 as you can see [here](https://wordpress.org/about/requirements/)

**Comment by Shudrum** [comment]
Thank you @maximebiloe and @mickaelandrieu!

Let's merge!

**Pull request merged**
