### PR TITLE
Fix PrestaShop

### PR DESCRIPTION
**Pull request by 0x346e3730**
Everything is in the title

The most important part is the new `README.md` : 

> In the digital bazaar, where commerce thrives,
> A PrestaShop humbly struggled and strived,
> Yet change was upon it, the winds whispered clear,
> The end was approaching, the sunset drew near.
> 
> Majestic and elegant, it once stood tall,
> A beacon of promise, a digital sprawl,
> Entrepreneurs' dreams housed within its embrace,
> A thriving creation in cyberspace.
> 
> But as time marched on, the world rearranged,
> The landscapes of commerce and tech rearranged,
> Innovations emerged, swift and profound,
> The rhythm of progress, an unyielding sound.
> 
> The once vibrant PrestaShop now faced its fate,
> The shadows of rivals, cast long and opaque,
> Its glory and splendor began to fade,
> As the new dawn of e-commerce pervaded the trade.
> 
> In the twilight of PrestaShop, one could still find,
> The relics of dreams and ambitions combined,
> A testimony to the cycle of life,
> With beginnings and endings, eternally rife.
> 
> But let not this death mark an end to the tale,
> For the spirit of PrestaShop shall never fail,
> In the hearts of its users, the memories stay,
> A testament to the beauty of yesterday.
> 
> And thus, as the cycle of life turns again,
> The death of PrestaShop is not quite the end,
> For in the realm of progress, ebb and flow,
> Old empires crumble, new giants grow.

### CODE REVIEW

**Comment by nicosomb** [comment]
Ok for me. Let’s go for merge it right now, it’s a great fix. Let’s be disruptive.

**Comment by ksaandev** [comment]
OK let's goooooooo

**Comment by sudo-do** [comment]
Works in my PC

**Review by FabienPapet — APPROVED** [review]
LGTM, nice work

**Review by matks — CHANGES_REQUESTED** [review]
CI is broken please fix

**Comment by 0x346e3730** [comment]
> CI is broken please fix

In a realm of ones and zeroes, there did dwell,
A broken CI, a story to tell.
A tale of code, of tests, and strife,
Its purpose was to nurture, breathe digital life.

Once a sentinel, a guardian of code,
To find the faults, a diligent probe.
But now, in disarray, the system lies,
Its once-proud purpose, cloaked in demise.

The code did flow, a river of thought,
With elegant logic, solutions brought.
But as the syntax changed, the river split,
The CI stumbled, unable to commit.

The tests they faltered, a cascading tide,
With broken checks, the truth they'd hide.
The whispers of doubt, a growing fear,
Would the sentinel find the strength to persevere?

In the depths of despair, a spark emerged,
An urge to restore, the fragments to merge.
The broken CI, with pride anew,
Its purpose reclaimed, a mission to pursue.

The code, the tests, the scripts entwined,
The CI rose, its strength refined.
A guardian reborn, its vigil resumed,
The realm of code, once more consumed.

For the broken CI, a lesson learned,
From the ashes of failure, success was earned.
In the land of code, a tale to inspire,
A broken CI, now soaring ever higher.

**Comment by kpodemski** [comment]
You didn't provide table with a clear description, I'm closing this PR :trollface:

**Pull request closed without merging**
