### PR TITLE
Rename non-namespaced Attribute class used internally by PHP 8

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Starting with PHP 8.0 non-namespaced `Attribute` class is used internally, see https://3v4l.org/9KiqJ
| Type?         | refacto
| Category?     | CO
| BC breaks?    | BC class is provided, but there is a break - overrided Attribute will not override the AttributePs
| Deprecations? | no
| Fixed ticket? | related with https://github.com/PrestaShop/PrestaShop/issues/18547
| How to test?  | CI tests must pass

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20710)

### CODE REVIEW

**Comment by mvorisek** [comment]
Please advise better name.

Table name etc. can stay.

For PHP lower than 8.0 we can provide a BC class, thus there wll be no BC break for current versions.

**Comment by mvorisek** [comment]
can someone what else needs to be renamed, error from install:
```
Class '\Attribute' not foundInstalled failed, displaying errors from logs:
```
probably some fixtures data... BC class will stay for users, but this PR itself should fix all related issues in PrestaShop and work without that BC class

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Thanks for your contribution, but it's too early to consider using PHP8, we are working to make it available with PHP7.4 on the develop branch, and we already know there is too many BC breaks in PHP8 :disappointed:

**Comment by mvorisek** [comment]
> 
> 
> Thanks for your contribution, but it's too early to consider using PHP8, we are working to make it available with PHP7.4 on the develop branch, and we already know there is too many BC breaks in PHP8 😞

I already have install fully working for PHP 8: https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/377695757

please merge this change asap, yesterday, I checked all new coliding classes in PHP 8 and this is the only one - we should merge to `develop` now, I was able to provide full BC

**Comment by PierreRambaud** [comment]
> > Thanks for your contribution, but it's too early to consider using PHP8, we are working to make it available with PHP7.4 on the develop branch, and we already know there is too many BC breaks in PHP8 disappointed
> 
> I already have install fully working for PHP 8: https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/377695757
> 
> please merge this change asap, yesterday, I checked all new coliding classes in PHP 8 and this is the only one - we should merge to `develop` now, I was able to provide full BC

It's a huge BC breaks since the `Attribute` class is no longer working as expected. People that are doing override (because it's still allowed), will not call the right class.

**Comment by matks** [comment]
> > Thanks for your contribution, but it's too early to consider using PHP8, we are working to make it available with PHP7.4 on the develop branch, and we already know there is too many BC breaks in PHP8 😞
> 
> I already have install fully working for PHP 8: https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/377695757
> 
> please merge this change asap, yesterday, I checked all new coliding classes in PHP 8 and this is the only one - we should merge to `develop` now, I was able to provide full BC

Hi, I think there is a misunderstanding.

BC break stands for backward compatible break. To make it short, this means "a change introduced in a codebase that provides previously compatible usages to work anymore following upgrade". I started an article about it here https://github.com/PrestaShop/prestashop.github.io/pull/730 (still draft).

I think you mention "BC" as in "Breaking Change" because "`develop` is not php8 compatible yet".

That being said, back to current topic.

We can see that you are working on "compatibility between `develop` branch and php8.0" and that is amazing 😄  thanks for the hard work !

However this is a complex work. Because, as you have found out, in order to allow this compatibility to happen, multiple changes into PrestaShop `develop` will be needed.

Some of these changes might be BC breaks. In theory, since we follow SemVer, **we should aim for as few as possible BC breaks** however we expect there will be some necessary breaks. Necessary = there is no backward compatible way to do it (or the backward compatible way is very expensive).

**But** we dont aim for `develop` to be php8 compliant **yet**. `develop` will give birth to `1.7.8.x` branch which will bring php7.4 compability thanks to @PierreRambaud work. Later, there will probably be a `1.7.9.x` branch and I guess at this moment we will introduce php8 compatibility. One step at a time.

So **if we merge your PR now** it will introduce a big BC break (renaming the class) although it is not needed yet, because we do not target php8 compatibility for `develop` now.

However, if we target php8 compatibility for `1.7.9.x` branch, then __as soon as 1.7.8.x branch is out develop will become the "future 1.7.9" and we will accept this PR__.

So my answer, to make it short, is "your work is nice however it is too early to be merged because what we merge now will be shipped in 1.7.9".

Obviously we are not against PRs that help php8 compatibility without introducing BC breaks. The issue here "users will pay the cost of a BC break without the benefits"

**Comment by mvorisek** [comment]
> So if we merge your PR now it will introduce a big BC break (renaming the class)

@matks I do not think so - please describe what will be broken

**Comment by matks** [comment]
> > So if we merge your PR now it will introduce a big BC break (renaming the class)
> 
> @matks I do not think so - please describe what will be broken

```
$attributes = Attribute::getAttributes(Context::getContext()->language->id, true);
```
⬇️ 
```
$attributes = AttributePs::getAttributes(Context::getContext()->language->id, true);
```

If a PrestaShop user has built a module for its shop by using [raw override](https://devdocs.prestashop.com/1.7/modules/concepts/overrides/), upon upgrade, the changes brought by your PR will disable his override. Since the class **being used** changes, the override file will modify the behavior of `AttributeCore`, not `AttributePsCore` and then the shop will ignore what used to work.

For example, quite a lot of people use ObjectModel override in order to alter the SQL schema. If you wish to have a new SQL column into Attribute object, it is easy to use an override and ObjectModel will out-of-the-box acknowledge the updated data structure, including inside PrestaShop Webservice. This is especially useful when building a synchronization data module between your shop and an ERP.

So there is a BC break. And we will probably have to merge it indeed, but let's do it at the right moment in the right place 😉  when the code we deliver is aiming for a php8 compatibility.

**Comment by mvorisek** [comment]
@matks https://github.com/PrestaShop/PrestaShop/pull/20710/files#diff-f13cec78081c7bf8b66d98d53d2ea63dR32 really?

**Comment by matks** [comment]
> @matks https://github.com/PrestaShop/PrestaShop/pull/20710/files#diff-f13cec78081c7bf8b66d98d53d2ea63dR32 really?

Yes, really 😄 .

I might be wrong - and I will check that because you make me doubt 😛  - but

## Currently in the code, let's say it's PS 1.7.7.0

I have `AttributeCore` class.

I can modify the behavior of `AttributeCore` using an override.

When I use an override, **everywhere** in the PrestaShop software, __the code from my override is being used, instead of the original file__.

## With your PR, let's say it's PS 1.7.8.0

I have `AttributeCore` class AND `AttributePsCore` classes.

The original software uses `AttributePsCore` now. But `AttributeCore` class is still here, and it extends `AttributePsCore` (and that is good !).

## If I upgrade from 1.7.7.0 to 1.7.8.0

If I modify nothing, my override keeps modifying `AttributeCore` NOT `AttributePsCore`. But modifying `AttributeCore` is not useful anymore because it's not used anymore.

**Comment by mvorisek** [comment]
I updated the description to reflect this, yes, override of Attribute will not affect the new AttributePs

as the nonCore classes are generated, we should update the generator to apply overrides of AttributeCore to AttributePsCore instead, right? This way, we can merge immediatelly, right?

**Comment by matks** [comment]
> as the nonCore classes are generated, we should update the generator to apply overrides of AttributeCore to AttributePsCore instead, right? This way, we can merge immediatelly, right?

Haha 😄  nice idea ! Indeed this seems to work as a plan

What do you think @PierreRambaud ? Would it be possible to trick the generator to avoid the BC break ? 😛

**Comment by PierreRambaud** [comment]
> > as the nonCore classes are generated, we should update the generator to apply overrides of AttributeCore to AttributePsCore instead, right? This way, we can merge immediatelly, right?
> 
> Haha  nice idea ! Indeed this seems to work as a plan
> 
> What do you think @PierreRambaud ? Would it be possible to trick the generator to avoid the BC break ?

It will be still a BC break since the class name change.
Also, the `AttributePsCore` is not a good class name, the Ps have nothing to do in the class name. It should be something like `ProductAttribute` and will be also a BC break.

The PHP8.0 is still in beta, so everything can still change, the Attribute protected class will maybe be changed, we don't know and we should not waste our time debate on something which is not released yet for something which is not started (the 1.7.9.0).
I will reconsider it when the PHP8.0 will be officially released.

**Comment by mvorisek** [comment]
Attribute class will stay because of PHP 8.0 feature freeze, RC expected in September.

I renamed the class from `Attribute` to `AttributePs` as there are other classes like `AttributeGroup` which will be named inconsistently then.

Let's wait until PHP 8.0 RC1 is out and then find a solution which we can merge immediatelly.

**Comment by PierreRambaud** [comment]
> Attribute class will stay because of PHP 8.0 feature freeze, RC expected in September.
> 
> I renamed the class from `Attribute` to `AttributePs` as there are other classes like `AttributeGroup` which will be named inconsistently then.
> 
> Let's wait until PHP 8.0 RC1 is out and then find a solution which we can merge immediatelly.

Exactly, if we rename the Attribute class, we will have to do it for AttributeGroup to be consistent. Let's wait for a 8.0 release and also for the 1.7.9.0 to start. We can close this pull request.

**Comment by mvorisek** [comment]
no, we will keep it, this can be solved for 1.7.8.0 too, as the change will need to be done anyway

**Comment by PierreRambaud** [comment]
> no, we will keep it, this can be solved for 1.7.8.0 too, as the change will need to be done anyway

I'm sorry but I'm against adding breaking changes not needed for the 1.7.8.0. Let's wait for @PrestaShop/prestashop-core-developers feedbacks too

**Comment by kpodemski** [comment]
Hello y'all, is it even possible to have such a change in 1.7.x? Tbh i thought that php 8 is plan for v8 :) I'm not sure if it would be possible to make PrestaShop compatible with php 8 without having more BC breaks. Lets remember about all dependencies, right now people are instantly moving to => () and I'm sure with `match` will be no different 😂

Maybe solution would be to have 1.7 as LTS and 1.8 before v...9? ;) 

PHP 8 is coming this year, it would be good to know what's the plan for this y'all have :)

#notifyme

**Comment by PierreRambaud** [comment]
> Hello y'all, is it even possible to have such a change in 1.7.x? Tbh i thought that php 8 is plan for v8 :) I'm not sure if it would be possible to make PrestaShop compatible with php 8 without having more BC breaks. Lets remember about all dependencies, right now people are instantly moving to => () and I'm sure with `match` will be no different 
> 
> Maybe solution would be to have 1.7 as LTS and 1.8 before v...9? ;)
> 
> PHP 8 is coming this year, it would be good to know what's the plan for this y'all have :)
> 
> #notifyme


AFAIK, if PHP8.0 is released this year, we will support it on the next release. This means, currently the 1.7.8.0 will support PHP 7.4, but, if the 1.7.6.8 is not released yet when the PHP8.0 will be available, we will do our best to support it. 
But (again :sweat_smile:), it's still in beta and many dependencies are (maybe) not compliant with PHP8, we should take in consideration all our dependencies before doing the job and add many unneeded BC breaks.

**Comment by kpodemski** [comment]
@PierreRambaud maybe having PrestaShop compatible wouldn't be so hard, but i'm afraid of minimum PHP version needed ;)

**Comment by PierreRambaud** [comment]
> @PierreRambaud maybe having PrestaShop compatible wouldn't be so hard, but i'm afraid of minimum PHP version needed ;)

This is also a possible problem :sweat_smile:

**Comment by jderusse** [comment]
For the record, this issue prevents users running php 7 to require dependencies (or their own code) using polyfill (list of packages impacted: https://packagist.org/packages/symfony/polyfill-php80/dependents?order_by=downloads)

I sugesst to add "conflict" rule in your `composer.json`

**Comment by PierreRambaud** [comment]
Closed in favor of #24609

**Comment by mvorisek** [comment]
I wonder why a separate PR with original authorship is not preferred.

**Pull request closed without merging**
