### PR TITLE
Add zipcode formats for Afghanistan and Egypt

### PR DESCRIPTION
**Pull request by enumag**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Add zipcode formats for Afghanistan and Egypt |
| Type? | bug fix |
| Category? | IN |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? |  |

Source: https://en.wikipedia.org/wiki/List_of_postal_codes

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by enumag** [comment]
@xBorderie Done.

**Comment by xBorderie** [comment]
Thank you!

**Comment by julienbourdeau** [comment]
I have reported your patch on `develop` branch, this should be merged for the next 1.6 version.
thank you for your contribution!

**Review by firstred — APPROVED** [review]

**Comment by maximebiloe** [comment]
Thank you @enumag!

**Pull request merged**
