### PR TITLE
BO: add isset employee for img

### PR DESCRIPTION
**Pull request by studiokiwik**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Bug with img if no employee exist |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | If no employee exist |

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @studiokiwik,

What do you try to fix here ?
In the same file, there are a other calls to the $employee object. Because this file is supposed to be loaded when the employee is logged, this variable should always exists. And if the other employee attributes do not throw an error, I do not see why this one would.

Best regards

**Comment by tslominski** [comment]
1. File can be loaded when employee is not defined, so your supposition is wrong
2. At the line 221 there is already one check if employe is set
3. Because if it is not set, when getImage() is called there will be fatal error:  Call to undefined method .
4. But there is also second call to getImage() , in line 229, this time - without check, so this commit tries to address that

**Comment by Quetzacoalt91** [comment]
> File can be loaded when employee is not defined, so your supposition is wrong

Thanks, but I need more details. Where ?

> Because if it is not set, when getImage() is called there will be fatal error: Call to undefined method .

And once this line will be fixed, so the execution would send notices or warnings a few lines later with `$employee->firstname` on null object. 😉

**Comment by antoin-m** [comment]
Hi @studiokiwik , thank you for your contribution.

If we are loading the BO's header then the `employee` has to be loaded so it doesn't really make sense to add `isset`s before using it.

Closed in favor of https://github.com/PrestaShop/PrestaShop/pull/7421

**Pull request closed without merging**
