### PR TITLE
[Merge] Merge 8.0.x to develop 

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Merge 8.0.x to develop 
| Type?             | improvement
| Category?         | ME 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | 
| Possible impacts? | 

I hope all will be fine 🤞

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]
Hope this PR will be merged quickly :wink:

**Review by jolelievre — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Comment by lartist** [comment]
Fiouuuu long code review !

**Review by jolelievre — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by mflasquin — DISMISSED** [review]

**Review by lartist — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]
default, new theme and theme build perfectly, lgtm 🍬

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by atomiix** [comment]
Thanks @nicosomb!

**Pull request merged**
