### PR TITLE
Update iframe-modal.ts DOM Text Interpreted As HTML 

### PR DESCRIPTION
**Pull request by Shivam7-1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML.
| Type?             |  improvement 
| Category?         |  CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI
| UI Tests          |  https://github.com/PrestaShop/PrestaShop/actions/runs/12180776044
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by tleon — APPROVED** [review]

**Comment by Shivam7-1** [comment]
Hii @tleon Thanks For Reviewing is there Anything else is Required From My Side to get PR Merge?
Thanks

**Review by boherm — APPROVED** [review]
LGTM, thanks @Shivam7-1.

**Comment by boherm** [comment]
> Hii @tleon Thanks For Reviewing is there Anything else is Required From My Side to get PR Merge? Thanks

To get your PR Merge, don't forget to run UI tests. You can follow this readme: https://github.com/prestashop/ga.tests.ui.pr
Please add UI Tests url in the PR description :)

**Comment by Shivam7-1** [comment]
Hii  @florine2623 this PR is waiting for QA could you please check QA over here 
Thanks

**Comment by paulnoelcholot** [comment]
Hello @Shivam7-1,

I will check this :+1:

**Comment by Shivam7-1** [comment]
Hii @paulnoelcholot is there Anything else is required from my side to get this PR merge?
Thanks

**Comment by paulnoelcholot** [comment]
Hello @Shivam7-1,

Sorry for the late, I tested your PR and it's good for me! :tada: 

Thanks!

Auto test here : https://github.com/paulnoelcholot/testing_pr/actions/runs/12315635827

**Review by paulnoelcholot — APPROVED** [review]

**Pull request merged**
