### PR TITLE
Add missing trans method instead of hard-coded wording

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Add missing trans method call on hard-coded wording
| Type?             | bug fix
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Review by PrestaEdit — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by atomiix — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by jolelievre** [comment]
Runnin automatic tests:
- PHP 7.3 Node 14 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3323528584
- PHP 7.4 Node 14 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3323534916
- PHP 8.0 Node 16 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3323540395

**Review by yanmakouf — APPROVED** [review]

**Comment by boubkerbribri** [comment]
> Runnin automatic tests:
> 
>     * PHP 7.3 Node 14 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3323528584
> 
>     * PHP 7.4 Node 14 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3323534916
> 
>     * PHP 8.0 Node 16 https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3323540395

Something bad happened, I'm checking this and will re-run tests.

**Review by boubkerbribri — APPROVED** [review]
The errors on php7.3 are a worflow problem.
So after analyzing, it's all good for me.

**Comment by matthieu-rolland** [comment]
thanks @jolelievre and @boubkerbribri !

**Pull request merged**
