### PR TITLE
Disable php in the "img" directory

### PR DESCRIPTION
**Pull request by yannicka**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | PHP scripts can be injected in the "img" folder and then executed. This pull request prevent this.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | yes, probably
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

### CODE REVIEW

**Comment by aleeks** [comment]
ping @rGaillard !

**Comment by rGaillard** [comment]
Hi Yannick,

There is already a .htaccess file in the /img/cms/ directory which is more restrictive than yours. Maybe you can update your PR moving this file to the parent (/img/) directory?

**Comment by yannicka** [comment]
It is done.

**Comment by xBorderie** [comment]
Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by Quetzacoalt91** [comment]
Commits squashed

**Comment by aleeks** [comment]
Thank you @yannicka & @rGaillard  & @Quetzacoalt91

**Comment by metacreo** [comment]
I couldn't think of anything dumber. kill SEO with one commit)))

**Comment by ShaiMagal** [comment]
@metacreo I couldn't think of anything dumber. kill SECURITY with one commit))) - PR #34825

**Comment by Hlavtox** [comment]
@metacreo I don't know how this PR affects SEO? :-)))

**Comment by metacreo** [comment]
@Hlavtox But I know))) how Google will react to a bunch of 403 instead of 404

**Comment by metacreo** [comment]
Besides... if you turned off PHP, why is there an index file with a PHP extension? Do you like accumulating garbage in directories? And what about redirecting through an index when accessing directories?

**Comment by metacreo** [comment]
Honest hosting admins, who write error logs instead of merging them into /dev/zero, have long been cursing the PS for worn-out SSDs.  And all from this commit ))) You probably just didn’t see the error log in a medium-loaded production

**Comment by metacreo** [comment]
> @metacreo I couldn't think of anything dumber. kill SECURITY with one commit))) - PR #34825

About what security... 

Can you tell me more about the security in the folder with images... for example, where does the malicious code come from? how can he get there? while loading? or when checking downloaded files? observe the cause-and-effect relationship and there will be no such commits... and everything will be fine with the head too.

I think that because of someone’s paranoia, you shouldn’t throw the htaccess file anywhere

**Comment by matks** [comment]
Hello! Please see my message [here](https://github.com/PrestaShop/PrestaShop/pull/34825#issuecomment-1859263786) to keep this discussion healthy and constructive 😉

**Comment by metacreo** [comment]
I apologize if my statements seemed rude or impudent. I promise not to flood here anymore.

@matks  Please give me a little explanation. Where are the tests? Where is the problem reproduction? Where is the clear description of the problem? On what basis was this commit accepted? Was it accepted according to the rules and sense or based on someone else’s emotions?

**Pull request merged**
