### PR TITLE
Improve prestashop.core.query_bus service to use parent

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  |  I found while working on another bug. Avoid service dependencies duplicate in ```src/PrestaShopBundle/Resources/config/services/core/command_bus.yml``` See : https://symfony.com/index.php/doc/3.3/service_container/parent_services.html.
| Type?         | improvement 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A.
| How to test?  | I do not really know 🤔

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18992)

### CODE REVIEW

**Comment by Progi1984** [comment]
@PululuK Travis is :red_circle: with this error :
> Attribute "public" on service "prestashop.core.query_bus" cannot be inherited from "_defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in /home/travis/build/PrestaShop/PrestaShop/src/PrestaShopBundle/Resources/config/services/core/command_bus.yml (which is being imported from "/home/travis/build/PrestaShop/PrestaShop/src/PrestaShopBundle/Resources/config/services.yml").Installed failed, displaying errors from logs:

**Comment by PululuK** [comment]
> @PululuK Travis is red_circle with this error :
> 
> > Attribute "public" on service "prestashop.core.query_bus" cannot be inherited from "_defaults" when a "parent" is set. Move your child definitions to a separate file or define this attribute explicitly in /home/travis/build/PrestaShop/PrestaShop/src/PrestaShopBundle/Resources/config/services/core/command_bus.yml (which is being imported from "/home/travis/build/PrestaShop/PrestaShop/src/PrestaShopBundle/Resources/config/services.yml").Installed failed, displaying errors from logs:

Hi @Progi1984 
Thank you  man  ...  But, how did you get this information ?

**Comment by Progi1984** [comment]
@PululuK You can access to travis logs.

Example : https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/328553323

**Comment by PululuK** [comment]
> @PululuK You can access to travis logs.
> 
> Example : https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/328553323

Why didn't you use my PR in the example? 🤔

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Not sure about this one 🤔it might not hurt, but is it really interesting to have inheritance here for one usecase ?

I think `foo_service` should be a child of `bar_service` when there really is a parent/child relationship between them, like Repositories and AbstractRepositories.

Here the 2 buses are not parent/child. They are siblings, doing the same purpose in 2 different cases

**Comment by PierreRambaud** [comment]
> Not sure about this one it might not hurt, but is it really interesting to have inheritance here for one usecase ?
> 
> I think `foo_service` should be a child of `bar_service` when there really is a parent/child relationship between them, like Repositories and AbstractRepositories.
> 
> Here the 2 buses are not parent/child. They are siblings, doing the same purpose in 2 different cases

Consider this as config inheritance only. I'm pretty sure if you update one, you'll have to do it for the other :thinking:

**Comment by PululuK** [comment]
> Not sure about this one 🤔 might not hurt, but is it really interesting to have inheritance here for one usecase ?
> 
> I think `foo_service` should be a child of `bar_service` when there really is a parent/child relationship between them, like Repositories and AbstractRepositories.
> 
> Here the 2 buses are not parent/child. They are siblings, doing the same purpose in 2 different cases

Hi @matks, thanks for feedback man !
I understand you perfectly! indeed, there is an ambiguity on the concept of parent in symfony services. As the documentation indicates, you can also use it in case you want to manage common dependaces between the different services (effectively with consistency and logic).
https://symfony.com/index.php/doc/3.3/service_container/parent_services.html.

In my case, it seems legitimate to use the notion of parent (which is false in truth) between these two services.

**Review by matks — APPROVED** [review]
I'm convinced 😄

**Comment by matks** [comment]
@PierreRambaud @Progi1984 Agreed to merge without QA ?

**Comment by Progi1984** [comment]
Ok for me. I don't know how to test. May be adding unit testing for checking inheritance ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
No QA needed, it's purely a technical pull request ;)

**Comment by PierreRambaud** [comment]
Thanks @PululuK

**Pull request merged**
