### PR TITLE
(WIP) [?] TEST : HHVM Travis test

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Would PrestaShop run on HHVM... |
| Type? | bug fix/improvement/new feature |
| Category? | TEST |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | N/A |
| How to test? | ...stay tuned for the answer on Travis. |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
To be honest we don't try to be hhvm compliant since PHP7 is alive,  stable and performant.  :)

**Comment by Dh42** [comment]
That is not the best decision. Being compatible with HHVM means that you write proper code without bottlenecks. If you coded to be compliant with HHVM you would produce faster php 7 code.

**Comment by mickaelandrieu** [comment]
@Dh42 it's "not so important platform support" versus  "Travis build duration".  hhvm is **not** PHP, I don't see why produce hhvm-compliant code will make this code faster on PHP7.  Don't forget that we also need to stay compliant with PHP5.4.. So we should already test with 5.4, 5.5, 5.6 and 7.0 ideally with MySQL 5.5, 5.6 and 5.7 and so on..  Of course it's only my opinion,  not the core team opinion ^^ we need to talk about it soon :)

**Comment by firstred** [comment]
Good! Let's get the discussion on HHVM started.

Closing this PR for now.

**Pull request closed without merging**
