### PR TITLE
Add modern and active Sortable library

### LINKED ISSUE #30210: Stop using jqueryuiSortable and jquerySortable in native modules
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

According to [an article in openjsf.org](https://openjsf.org/projects/#emeritus), jqueryUI is a Emeritus project which the maintainers feel _have reached or are nearing end-of-life_. [jqueryui in PrestaShop core js](https://github.com/PrestaShop/PrestaShop/blob/8.0.0/js/jquery/ui/jquery-ui.js) even stays at 1.10 version since 2013, all jqueryui plugins there are outdated the same.
We need to replace jqueryui plugins by other equivalent modern, active and popular libraries one by one ASAP. 
Starting with [jquery.ui.sortable.js](https://github.com/PrestaShop/PrestaShop/blob/8.0.0/js/jquery/ui/jquery.ui.sortable.min.js) in these 2 native modules is my first step (someone had done initial steps in hummingbird theme and ps_facetedsearch module:)
- [x] [blockreassurance](https://github.com/PrestaShop/blockreassurance/blob/v5.1.1/blockreassurance.php#L246)
- [x] [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/v3.1.1/ps_imageslider.php#L611)

Furthermore, the similar plugin [jquery/plugins/jquery.sortable.js](https://github.com/PrestaShop/PrestaShop/blob/8.0.0/js/jquery/plugins/jquery.sortable.js) (used by  ps_facetedsearch module) is outdated, so we need to replace it as well (my second step;)  
### Describe the solution you'd like

Stop using jquery/ui/jquery.ui.sortable.js in native modules, use  [SortableJS](https://github.com/SortableJS/Sortable) instead, like [Drupal had done with their core](https://www.drupal.org/node/3084730).

Stop using jquery/plugins/jquery.sortable.js, use SortableJS instead, like jquery.sortable's author suggested at [deprecation-notice](https://github.com/farhadi/html5sortable#deprecation-notice).

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by leemyongpakvn**
as an alternative for jqueryuiSortable in [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/v3.1.1/ps_imageslider.php#L611) module, and jquerySortable in [ps_facetedsearch](https://github.com/PrestaShop/ps_facetedsearch/blob/v3.8.0/ps_facetedsearch.php#L757) module

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Check the fixed ticket below.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #30210 (partialy)
| Related PRs       | **Optional** for [ps_facetedsearch/pull/733](https://github.com/PrestaShop/ps_facetedsearch/pull/733)
| How to test?      | Check the related PR above. <br>For security reason, check diff between this added file here and its original at [github/SortableJS](https://github.com/SortableJS/Sortable/blob/master/Sortable.min.js).
| Possible impacts? | only on module that chose to switch from the old sortable library to this new one.

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
thank you for your PR @leemyongpakvn 

I invoke @NeOMakinG, this seems like a good call, what do you think?

**Review by NeOMakinG — APPROVED** [review]
🍬

**Review by kpodemski — APPROVED** [review]
Good idea. The next step could be to replace this:

`$this->addJS(_PS_JS_DIR_ . 'vendor/ladda.js');`

with some helper, similar to what we have for jquery plugins 😎

**Review by HanaRebaiQA — APPROVED** [review]
Hello @leemyongpakvn 

I have launched the automated tests on your PR. 

It's QA :heavy_check_mark: 

Thank You!

**Comment by kpodemski** [comment]
Thank you, @leemyongpakvn !

**Pull request merged**
