### PR TITLE
Allowed e2e tests to restart 3 times

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Well, it's triggered by the Core team manually but I'm lazy
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Yup! I've probably increased Dev Core team productivity: how awesome I am xD
| How to test?  | Wait for travis.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15126)

### CODE REVIEW

**Comment by matks** [comment]
I guess we can try 😐 but this does not solve the root cause
I 👍 this PR but I need a +2 approval I'd like another opinion

**Comment by mickaelandrieu** [comment]
Hello,

> I guess we can try neutral_face but this does not solve the root cause
I +1 this PR but I need a +2 approval I'd like another opinion

It is because what I want to fix here is the "manual" operations the QA + Core team have to do.

Fixing our test suite is another piece of cake, a lot bigger and not easy to eat :warning:

Thanks to the patch of @eternoendless, once I'll rebase the build should be green :pray:

**Comment by matks** [comment]
Travis failed for a random reason although it tried 3 times 😬 

I think Travis demonstrated this will not be enough 😆

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Travis spoke! 🙏

**Comment by mickaelandrieu** [comment]
Closed: I guess its too late to postpone this problem 👼   :/

**Pull request closed without merging**
