### PR TITLE
Update Smarty to v3.1.39

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update Smarty to v3.1.39 . Version [3.1.39](https://github.com/smarty-php/smarty/releases/tag/v3.1.39) fixes 2 sandbox security issues.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | CI is green
| Possible impacts? | Only smarty version is updated, and it's a a jump of 3 patch versions.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23295)

### CODE REVIEW

**Comment by matks** [comment]
Re-running Sanity tests for php7.4 for the 4th time, I'm starting to wonder if the PR introduces a bug with php7.4 😛

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by matks** [comment]
@NeOMakinG @Progi1984 Hi, I dont think this PR needs QA 🤔 
- the version bumps are supposed to be only bugfixes and vulnerability patches (3.1.36 to 3.1.39)
- what can QA test 🤷‍♂️ "the all app ?" I think our automated tests are enough, just like for dependabot PRs

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional  What do you think about that ?

**Comment by Robin-Fischer-PS** [comment]
@matks @Progi1984 We will perform a small manual test, it should be done today !

**Comment by Progi1984** [comment]
Thanks @matks & @sarahdib

**Pull request merged**
