### PR TITLE
Remove 'Constraint' suffix from TypedRegex constraint and validator

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Rename `TypedRegexConstraint to TypedRegex` and `TypedRegexConstraintValidator to TypedRegexValidator`
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No issue with validation on "Add/edit CMS page", "Add/edit brand" and "Add/edit brand address"

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13159)

### CODE REVIEW

**Comment by zuk3975** [comment]
@matks

**Review by PierreRambaud — DISMISSED** [review]

**Comment by matks** [comment]
@zuk3975 Travis is not happy that you broke its build 😉 
```
> @php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit-admin.xml
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
...............................................................  63 / 133 ( 47%)
.........
Fatal error: Class 'PrestaShop\PrestaShop\Core\ConstraintValidator\Constraints\TypedRegexConstraint' not found in /home/travis/build/PrestaShop/PrestaShop/src/PrestaShopBundle/Form/Admin/Improve/International/Language/LanguageType.php on line 73
```

**Comment by zuk3975** [comment]
> @zuk3975 Travis is not happy that you broke its build 
> 
> ```
> > @php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit-admin.xml
> PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
> ...............................................................  63 / 133 ( 47%)
> .........
> Fatal error: Class 'PrestaShop\PrestaShop\Core\ConstraintValidator\Constraints\TypedRegexConstraint' not found in /home/travis/build/PrestaShop/PrestaShop/src/PrestaShopBundle/Form/Admin/Improve/International/Language/LanguageType.php on line 73
> ```
@matks :thinking: not sure how i missed this, but now fixed

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
