### PR TITLE
Fix stock page responsive

### LINKED ISSUE #22681: [RESPONSIVE - BO] Stock page is not responsive
#### Describe the bug

The stock page has a lot of bugs which make it unusable on mobile

#### Expected behavior

At least be able to use the stock page on mobile, even if it hasn't been thought for the best UX

#### Steps to Reproduce

1. Go to Stock page

**Screenshots**

image

#### Additional information

* PrestaShop version: develop

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Stock page wasn't responsive
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22681.
| How to test?      | Go on stock page on mobile and see if the page is pretty fine

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22691)

### CODE REVIEW

**Comment by Progi1984** [comment]
@NeOMakinG Lint CSS is :red_circle:

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
there's a conflict on `admin-dev/themes/new-theme/scss/components/layout/_main_header.scss`

**Review by Progi1984 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @NeOMakinG :)

It looks almost fine to me, just two remarks/questions : 

- When in tablet display, the "Edit quantity" column is too short for the screen, I have this display : 
pr22691 tablet column

- In "Mobile" display, the export buttons are not displayed : Is this a wanted behavior ?
On mobile : No buttons
pr22691 export mobile


On desktop : Buttons
pr22691 export normal

Thanks ;)

**Comment by NeOMakinG** [comment]
Hey @Robin-Fischer-PS 

I didn't work on the tablet at all, aim to work on mobile views!

Hide export buttons is a wanted behavior, see figma's mockup :

image

**Comment by Robin-Fischer-PS** [comment]
Alright, thanks @NeOMakinG ;)

Then it's all OK for me, QA :heavy_check_mark:

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @Robin-Fischer-PS

**Pull request merged**
