### PR TITLE
[+] Project : Cart::getPackageDimensions()

### PR DESCRIPTION
**Pull request by prestalab**
This function calculate weight, width, height, depth of package for carrier modules. In future it can replace getTotalWeight function.

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, Thank you for your contributions.

Can we discuss this new enhancement with ours @PrestaShop/prestashop-product-managers ?

Best regards.

**Comment by prestalab** [comment]
Yes, but team members are private and I cant write to @PrestaShop/prestashop-product-managers

**Comment by SebSept** [comment]
If accepted, can you explain how you are computing dimensions ? The logic.

**Comment by prestalab** [comment]
This simple algorithm puts products on each other. Height is sumed, depth and width is max of products.
If you know package size you can use this code https://github.com/dvdoug/BoxPacker

**Comment by SebSept** [comment]
Nice, thanks for the feedback. I think you can add that information in the docblock (function should not be read to know what it is doing, saves time!)

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
