### PR TITLE
Errors when saving memcached configuration

### LINKED ISSUE #9542: [BOOM-6166] memcached server do not work with v.1.7
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-6166).

- _**Reporter:**_ venty
- _**Created at:**_ Wed, 1 Aug 2018 19:16:42 +0200

<p>Hello,</p>

<p>on one server I have installed memcached and also prestashop with versions 1.6.20 and 1.7.4.2 ...</p>

<p>When attempting to run and add a memcached server in versions 1.6, it gets, and at 1.7 not everything turns red ...</p>

<p>What to do?</p>

<p>Thanks in advance!</p>

<p>BR</p>

<p>Venty</p>

<p> </p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | - Refactor variables names<br>- Check if getVersion is an array<br>- Wrong condition in js<br>- Use const for http codes
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9542 
| How to test?  | Follow ticket instruction.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10201)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by matks — APPROVED** [review]

**Comment by ghost** [comment]
I have applied the changes approved by @matks, but the problem is not solved.

**Comment by qadeeralvi** [comment]
Hi,
I installed the latest PrestaShop version 1.7.5 and still have faced this problem. I could not add the server. see the attached file. Thanks in advance!

prestashop 1 7 5_chache_error

**Comment by ghost** [comment]
Me too, confirm that with the 1.7.5 version the problem is not solved!

**Comment by havkacik** [comment]
The problem still persists in PS1.7 - specifically in 1.7.6.4. Any timelines for resolving this has been established? Many thanks for info. 

3fd3ln6ht1z8l0z84rz9xn7u3oa7qs7b_anonymized

**Pull request merged**
