### PR TITLE
Fixed hint tooltip on template

### PR DESCRIPTION
**Pull request by aleeks**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Fix tooltip when have some special caracters |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | See picture. |

hint_fix
#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]
Make sense :+1:

**Comment by mickaelandrieu** [comment]
Don't you have to commit on `test` branch too ?

**Comment by aleeks** [comment]
I'm working on this !

**Comment by thierrymarianne** [comment]
Thanks @aleeks

**Pull request merged**
