### PR TITLE
Fix Address form not work properly in customer account area

### LINKED ISSUE #34080: Address form not work properly in customer account area
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Tested on demo.prestashop.com
If you go to "account" and click update address (France) you need to enter states.
For some this bug exist only on Firefox or only on Chrome. On one my server with fresh PS install, bug seen in both browsers.
Reopen #33991.
On click Update on address in my-account area, form requesting enter state, even if country without states, Self-fixing only after manipulation with country change.

public function fillWith(array $params = []) called twice. Second call destroys country->id

### Expected behavior

No need enter states by default for France or other country with no states.

### Steps to reproduce
Clean browser cache before.
Go to demo.prestashop.com with 8.1.x version.
PS browser detection must be enabled.
PS must have enabled US country with states.
PS need to default US country (optional).
Ensure that your browser have default eu_US locale.
login as new customer and create address not US, all other without states.
Save address.
Click Update address.
Click Save.
 
https://github.com/PrestaShop/PrestaShop/assets/543458/a57f199d-05ec-4a6e-a859-14b1d1a78a2d

### PrestaShop version(s) where the bug happened

8.1.1 8.1.2

### PHP version(s) where the bug happened

8.2.10

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed issue or discussion?     | Fixes #34080, #35013

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
I think you can put the fill in the same condition below. ;-)

**Comment by Hlavtox** [comment]
- There is a simmilar PR like this here https://github.com/PrestaShop/PrestaShop/pull/34152
- We should investigate what is the root of this problem. Apparently it didn't happen on 1.7.8.

**Comment by Codencode** [comment]
> * There is a simmilar PR like this here [Fix AddressController.php #34152](https://github.com/PrestaShop/PrestaShop/pull/34152)
> * We should investigate what is the root of this problem. Apparently it didn't happen on 1.7.8.

The problem depends on the fact that the Customer Address Form:fill With() method has been changed compared to version 1.7.8.x

PS 1.7.8.x
```
   public function fillWith(array $params = [])
    {
        // This form is very tricky: fields may change depending on which
        // country is being submitted!
        // So we first update the format if a new id_country was set.
        if (isset($params['id_country'])
            && $params['id_country'] != $this->formatter->getCountry()->id
        ) {
            $this->formatter->setCountry(new Country(
                $params['id_country'],
                $this->language->id
            ));
        }

        return parent::fillWith($params);
    }
```

PS 1.8.x
```
    public function fillWith(array $params = [])
    {
        // This form is tricky: fields may change depending on which country is being selected!
        // Country preselection priority order :
        // 1) Update the format if a new id_country was set.
        // 2) Detect country from browser language settings and matches BO enabled countries
        // 3) Default country set in BO

        if (isset($params['id_country'])) {
            $country = (int) $params['id_country'] !== (int) $this->formatter->getCountry()->id
                ? new Country($params['id_country'], $this->language->id)
                : $this->formatter->getCountry()
            ;
        } elseif (
            Tools::isCountryFromBrowserAvailable() &&
            Country::getByIso($countryIsoCode = Tools::getCountryIsoCodeFromHeader(), true)
        ) {
            $country = new Country((int) Country::getByIso($countryIsoCode, true), Language::getIdByIso($countryIsoCode));
        } else {
            $country = new Country((int) Configuration::get('PS_COUNTRY_DEFAULT'), $this->language->id);
        }

        $this->formatter->setCountry($country);

        return parent::fillWith($params);
    }
```

So now in 1.8.x if $params['id_country'] is not set (and this is the case in which you access the modification of an address) the system tries to load the country from the language, if it fails it loads the default one.

**Comment by Hlavtox** [comment]
OK, that makes sense, but I think that if you move the form filling into `if (Tools::isSubmit('submitAddress')) {`, it will break the default country in the form no?

Shouldn't the real fix be inside `fillWith` method?

So, the expected behavior on initial form load:
- If editing existing address, $this->formatter->setCountry must be the country from the address.
- If editing new address, $this->formatter->setCountry must be the default country resolved inside the method.
- If submitting the form, $this->formatter->setCountry must be the country from submitted params.

**Comment by metacreo** [comment]
@Codencode this is duplicate of PR #34152
but you have double `Tools::isSubmit('submitAddress')` check 

For what you suggest duplicate code?
```
        if (Tools::isSubmit('submitAddress')) {
            ///
        }
        if (Tools::isSubmit('submitAddress')) {
            ///
        }
```
The unfortunate PS already suffers from duplicate functions and requests. 😢

**Comment by Codencode** [comment]
> OK, that makes sense, but I think that if you move the form filling into `if (Tools::isSubmit('submitAddress')) {`, it will break the default country in the form no?
> 
> Shouldn't the real fix be inside `fillWith` method?
> 
> So, the expected behavior on initial form load:
> 
> * If editing existing address, $this->formatter->setCountry must be the country from the address.
> * If editing new address, $this->formatter->setCountry must be the default country resolved inside the method.
> * If submitting the form, $this->formatter->setCountry must be the country from submitted params.

Ok, 
I could modify the fillWith method to be like this:
```
        if (isset($params['id_country'])) {
            $country = (int) $params['id_country'] !== (int) $this->formatter->getCountry()->id
                ? new Country($params['id_country'], $this->language->id)
                : $this->formatter->getCountry()
            ;
        } elseif (
            Tools::isCountryFromBrowserAvailable() &&
            Country::getByIso($countryIsoCode = Tools::getCountryIsoCodeFromHeader(), true)
        ) {
            $country = new Country((int) Country::getByIso($countryIsoCode, true), Language::getIdByIso($countryIsoCode));
        } else {
            $country = new Country((int) Configuration::get('PS_COUNTRY_DEFAULT'), $this->language->id);
        }
```
to like this
```
        if (isset($params['id_country'])) {
            $country = (int) $params['id_country'] !== (int) $this->formatter->getCountry()->id
                ? new Country($params['id_country'], $this->language->id)
                : $this->formatter->getCountry()
            ;
        } elseif ($this->address) {
            $country = $this->formatter->getCountry();
        } elseif (
            Tools::isCountryFromBrowserAvailable() &&
            Country::getByIso($countryIsoCode = Tools::getCountryIsoCodeFromHeader(), true)
        ) {
            $country = new Country((int) Country::getByIso($countryIsoCode, true), Language::getIdByIso($countryIsoCode));
        } else {
            $country = new Country((int) Configuration::get('PS_COUNTRY_DEFAULT'), $this->language->id);
        }
```

Do you think it's better?

**Comment by Codencode** [comment]
> @Codencode this is duplicate of PR #34152 but you have double `Tools::isSubmit('submitAddress')` check
> 
> For what you suggest duplicate code?
> 
> ```
>         if (Tools::isSubmit('submitAddress')) {
>             ///
>         }
>         if (Tools::isSubmit('submitAddress')) {
>             ///
>         }
> ```
> 
> The unfortunate PS already suffers from duplicate functions and requests. 😢

@metacreo,
you're right, but I think that, as @Hlavtox suggests, I will modify the **CustomerAddressForm::fillWith()** method

**Comment by metacreo** [comment]
@Hlavtox 
> Shouldn't the real fix be inside `fillWith` method?

I think NO. 
The present code design is quite acceptable. Don't forget about the browser verification factor. (isCountryFromBrowserAvailable)
The best solution at the moment is to change AddressController.php and leave the fillWith function alone. Otherwise, it is necessary to rewrite the entire design that affects these controllers, and I already foresee new, more serious errors.
Just trace the sources of the fillWith call.

**Comment by metacreo** [comment]
> you're right, but I think that, as @Hlavtox suggests, I will modify the **CustomerAddressForm::fillWith()** method

@Codencode 
It’s not worth it, but if you really want to, determine all the factors.
because those that Hlavtox described are only a small part.

from the beginning I also took up fillWith and came to the conclusion that there would be trouble.
besides ! this way you will leave a **duplicate** function fillWith call.

😂 no matter how much they want it, the very first decision is the best

**Comment by Codencode** [comment]
I created a new pull request (#35021) with the CustomerAddressFormCore::fillWith() method modification.

Furthermore, I created a second one identical to this one (#35020) which however takes into account @metacreo's consideration.

**Pull request closed without merging**
