### PR TITLE
Explain differences between this repo and the corporate project

### LINKED ISSUE #36055: Zipball on GitHub does not match website
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The Zipball in this GitHub repo 

https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.5

does not match the same offered product when downloaded from the website at 

https://prestashop.com/prestashop-offers/classic/ (not a permalink)

Please note that the website also requires you to type in some b-s email address before the download proceeds. This is similar to how Docker works, right before everyone started boycotting Docker.

### Expected behavior

_No response_

### Steps to reproduce

Download both
Compare

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by fulldecent**
To reduce confusion, improve transparency, and fairly introduce the other project

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Explain difference between this repository and the company product, which both have the same name and version numbers but are different products
| Type?             | improvement
| Category?         | FO / BO / CO / IN / WS / TE / LO / ME / PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Read markdown file index.md
| UI Tests          | not applicable
| Fixed issue or discussion?     | Fixes #36055
| Related PRs       | none
| Sponsor company   | William Entriken, Pacific Medical Training

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
I am sorry but
- the content listed here is not accurate
- I am against putting this in the README

This README is the README of prestashop/prestashop which is a software project. For the OSS project stuff we have https://www.prestashop-project.org/ which was created for this purpose.

I prefer to keep things in the right place 😉 and not mix them

**Comment by fulldecent** [comment]
Thank you for your review, @matks. Can you please justify 

> the content listed here is not accurate

?

---

Surely there will be some confusion between the PrestaShop 8.1.5 product released in this repository and the PrestaShop 8.1.5 product released on PrestaShop.com.

If there is a more correct way to explain what I have tried in this PR, please give me a another chance to correct the errors and propose how we can transparently and constructively explain this in our README here.

**Comment by matks** [comment]
@fulldecent Long story short, PrestaShop project and PrestaShop company have been the entity for around ten years, a differenciation was initiated in 2022 but there are plenty things who are still merged.

For example the brand PrestaShop is solely owned by PrestaShop SA.

I'm sorry the only accurate answer 😅 is "it's complicated". If I had to go through each item (the brand, the software, the website, the policy...) I would need to write a hundred line statement.

Another example: every tool or service being used to carry out the project (GitHub, DockerHub, Crowding) are being paid by PrestaShop SA but their usage is made available to all project members.

Also some services like https://api.prestashop-project.org/ are being deployed by PrestaShop SA team although the code is open https://github.com/PrestaShop/distribution-api

I checked your website 😉 and I see you come from the blockchain world where I think things are 100% clear and un-ambiguous. I'm sorry I'm afraid for PrestaShop things are not as clear as they are for ETH for example.

(I anticipate more questions, I'm going on holidays this evening and I won't answer for around 10 days 😄 so if you don't get another answer from me in the next days it's not I'm ignoring you, just enjoying my vacations)

**Comment by matks** [comment]
That being said I really prefer we keep the README for the software project and bring that kind of content in https://www.prestashop-project.org/ 😉

**Comment by fulldecent** [comment]
Thank you, have a great vacation!

Yes you are right, before that I was at Google and worked on Linux 👋.

Updated PR to greatly simplify things. Hopefully it now says only the necessary things that people will need to know.

**Comment by Hlavtox** [comment]
@matks I think the current version is alright. :-)

There are endless issues regarding this, if this clears it up for some of the poeple, it's at least something.

**Comment by kpodemski** [comment]
Hello @fulldecent, thank you for your time and submitting this PR.

Following "one official zip distribution" strategy, this change is no longer relevant (The project won't release its distributions.) and its place is not in the Readme.md on GitHub.

**Pull request closed without merging**
