### PR TITLE
[-] Class: Customer / Show display as deprecated for customerIdExists()

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Adding the deprecated function call is ok to me haowever you are chnging its behavior by retruning a boolean. customerIdExistsStatic is returning th customer id and so does customerIdExists currently, maybe modules are relying on that and this breaks backward compat despite the obvoius name of the function.

Best regards

**Comment by PrestaEdit** [comment]
Hi,

Actually, it's not really true. The method is just to know if a Customer is in base, not to get it's ID. It's a "bonus" for this method, to do only one query/method but comments on methods and name let me know that you have to get a true/false return.

But, of course and because the static method one return an integer, I do the same now on the deprecated method ;-)

**Comment by PrestaEdit** [comment]
And, of course... You want to know if $id_customer exist and passed it into params. Get it in return is just not necessary ;-)

**Comment by gRoussac** [comment]
Hi,

I guess you seem to however agree this is changing behavior when i see your commit =)

Regards

**Comment by PrestaEdit** [comment]
Not really ;-). But I think we can't break the use of the method and that an another PR will be more right to change it, if we need to ;)

**Comment by seigieu** [comment]
It can break things. Even if it's not suppoused to, it returns customer ID and some may relay on it in way:

    if($id = customerIdExists($id)){
        $id; // we gout our ID
    }

as a sanitization of ID (even tho it should not be like this). So it could break some modules for some.

**Comment by PrestaEdit** [comment]
No more with the recent commit I did... ;-)

**Comment by seigieu** [comment]
True. Point is if we try to break some modules or keep backward compatibility.

**Comment by PrestaEdit** [comment]
Yes. Is what I do the another commit, evin If I think is not the good way to use these methods. But, we can't break them so ;-)

Like this, it's do the same way that before :)

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution please use develop branch for deprecated functions.

Best regards.

**Pull request closed without merging**
