### PR TITLE
Invalid characters are being saved as Social titles

### LINKED ISSUE #28320: Invalid characters are being saved as titles
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When creating or editing an existing social title, the tool tip shows the invalid characters as: "0-9!<>,;?=+()@#"{}_$%:".
However when entering any of these characters, they are still getting saved, only the max length limit works in this field. 

https://user-images.githubusercontent.com/23308427/165263440-c6f1ef76-d635-4387-9c33-d5f729f7f3d0.mp4

### Expected behavior

Invalid characters should not be allowed to save.

### Steps to reproduce

1. Go to Shop parameters -> Customer settings -> Titles.
2. Press "Add new social title".
3. Check the "Social title" tool tip.
4. Enter the invalid characters in to the same field.
5. Press "Save".

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by AlexTechDev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  9.0.x
| Description?      | When creating or editing an existing social title, the tool tip shows the invalid characters as: "0-9!<>,;?=+()@#"{}_$%:". <br/> However when entering any of these characters, they are still getting saved, only the max length limit works in this field. <br/> So to fix it I use the class Validate "isCatalogName" to validate the social title, if it's ok to be Catalog Name and show in front office it will be ok to be Social Title.  Also I update the hint to "Invalid characters: <>;=#{}:"
| Type?             | bug fix
| Category?         |  BO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #28320
| How to test?      | Go to Shop parameters -> Customer settings -> Titles.<br/>Press "Add new social title".<br/>Check the "Social title" tool tip.<br/>Enter the invalid characters in to the same field.<br/>Press "Save"

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
I'm afraid it's a breaking change, and probably should be planned for v9.

**Comment by kpodemski** [comment]
I marked PR with a milestone to not forget about it.

**Review by kpodemski — DISMISSED** [review]

**Comment by AureRita** [comment]
Hi @AlexTechDev 

Thank you for your PR ! I tested it and I see that the character     :      "    can be used, as you can see here : 

image

You can maybe change the hint to "Invalid characters: <>;=#{}"

Thank you

**Review by kpodemski — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello @AlexTechDev ,

There are some checks haven’t completed yet, could you check it please before testing the PR?

**Review by AchrafKchaou1991 — APPROVED** [review]
Hello @AlexTechDev 
I have checked your PR ;

[Pr 29760**.webm](https://github.com/PrestaShop/PrestaShop/assets/131356155/2f7bd187-11d4-425a-ac4e-49e2d7619c68)

PR OK :heavy_check_mark: 
The automated tests are OK :heavy_check_mark: 
https://github.com/AchrafKchaou1991/ga.tests.ui.pr/actions/runs/5108997872
Thank you :smile:

**Comment by nicosomb** [comment]
Thank you @AlexTechDev !

**Pull request merged**
