### PR TITLE
Add barcode in invoice

### PR DESCRIPTION
**Pull request by waternice**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Develop
| Description?  | Used TCPDF for generating BARCODE. <br/> First we created TCPDF parameters in HTMLTemplateInvoice.php and then used it in invoice.addresses-tab.tpl to print barcode.
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Generate a invoice.

### CODE REVIEW

**Comment by thenote** [comment]
why it failed?

**Comment by thenote** [comment]
Changed Commit Names 👍

**Comment by mickaelandrieu** [comment]
@thenote it's useless to "downvote" @prestonBot's comment, he'll still loves you :lollipop:

**Comment by thenote** [comment]
I downvoted because it was showing also after changing commit name.

Sorry for my Downvote, I also Loves it.🍭 @prestonBot @mickaelandrieu

**Comment by mickaelandrieu** [comment]
@thenote yeah sorry we are aware that @prestonBot don't remove the message after your update, I tried to fix the behavior this should be better now.

If you are interested, you can take a look to the code in the repository: this is open source !
For every star @prestonBot got, we save a kitten around the world :laughing: !

https://github.com/PrestaShop/prestonbot

**Comment by thenote** [comment]
i am in and also like to save kitten.🍭 @mickaelandrieu @prestonBot

**Comment by aleeks** [comment]
ping @vincentbz

**Comment by aleeks** [comment]
Hello @thenote 
Have you tested this PR ? Can you show the result because for me, it's not working.

**Comment by vincentbz** [comment]
hi @thenote 
I agree, it would be great if you could give us an example, thanks !

Could you also give us an example of that use case for customers ? in what case it would be useful ?

**Comment by aleeks** [comment]
Hello @thenote, 
After reviewing & trying to fix this PR, i'm closing it because it can't work.
Feel free to re-open if you can fix it. You need to rebase against develop too.

Regards

**Pull request closed without merging**
