### PR TITLE
[*] BO : Allow to exclude tax and shipping in affiliation sales total

### PR DESCRIPTION
**Pull request by cedricfontaine**

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by cedricfontaine** [comment]
still needed.

**Comment by cedricfontaine** [comment]
This PR needs to be added. Tax should not be included in affiliate.

**Comment by xBorderie** [comment]
Hey @cedricfontaine , thank you for your feedback!

Since this is a new feature, could you make this PR again on the `develop` branch, so that it lands in PS 1.7 you get full credit for it :)

And before you do any more rewrite (and spend time on this), I want to make sure that what you are implementing is accepted. Could you give us a lot more details about your intentions with this PR? This way, our Product team will be able to make a decision about that idea.

This is a long work that you have put into this, I want to make sure we are on the same point.

Thank you very much!

**Comment by cedricfontaine** [comment]
In fact currently the affiliate amount are calculated on total including taxes and shipping. In the majority of affiliate program, commission are tax and shipping excluded. This PR adds a way to define if tax and shipping is included in the amount due.

**Comment by xBorderie** [comment]
So, you mean that's actually a bug, and thus should be in the next 1.6 patch version? Could you rebase your PR on the `1.6.1.x` branch, then?

**Comment by cedricfontaine** [comment]
For my experience in Canada, and US, where all prices are withot tax, yes it's a bug.

**Comment by xBorderie** [comment]
Thank you for your feedback. Can you rebase this PR for the `1.6.1.x` branch? We can't use this one because it was made on the `1.6` branch... Thank you!

**Comment by xBorderie** [comment]
Great, thank you Cédric!

**Pull request closed without merging**
