### PR TITLE
Replace nav bar (left menu) smarty template by twig component

### LINKED ISSUE #32990: Twig Component : Navigation bar (left menu)
## Description

See #33101 for description

This is the Navigation bar ( left menu)  part.

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Replace nav bar (left menu) smarty template by twig component
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto test 🟢 
| Fixed ticket?     | Fixes #32990
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @lartist

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello @lartist ,

There are some checks that were not successful, could you check it please?

**Comment by lartist** [comment]
@nesrineabdmouleh told me it's not due to the PR @MhiriFaten

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/5487396137

**Review by M0rgan01 — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
@lartist while it is not related to the PR so it is approved you can merge it :heavy_check_mark: 

Thanks @MhiriFaten, we're waiting for this PR first https://github.com/PrestaShop/PrestaShop/pull/33208

**Review by tleon — APPROVED** [review]

**Comment by lartist** [comment]
Thanks @lartist

**Pull request merged**
