### PR TITLE
Add `id_feature_value` in `Product::getFrontFeaturesStatic`

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add `id_feature_value` in `Product::getFrontFeaturesStatic`.
| Type?             | improvement
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      |  Try this code in product.tpl `{var_dump($product.features)}` and make make you have `id_feature_value` for each feature value.
| Possible impacts? | N/A

### CODE REVIEW

**Review by nicosomb — COMMENTED** [review]
Just to understand: you want to have access to this variable in template?

**Comment by PululuK** [comment]
> 

Hello @nicosomb, yep.

**Review by nicosomb — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @PululuK ,

I check your PR and it's QA :heavy_check_mark: 

Thank you !

**Comment by marsaldev** [comment]
Thanks @PululuK 💪!

**Pull request merged**
