### PR TITLE
Simplified logs form

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Simplify logs settings form
| Type?         | improvement
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Part of #16482
| How to test?  | Simplifying Advanced Parameters -> Logs. Everything must look the same with one exception: blue help box replaced with help text under input.

:notebook: **BC Break**
Backwards compatibility break introduced due to extension of TranslationAwareType instead of using TranslatorAwareTrait. This means if any module extends LogsByEmailType file they will get an exception.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21234)

### CODE REVIEW

**Comment by JevgenijVisockij** [comment]
I have 2 concerns with this PR:

1. Before the "Minimum severity level" field was required but in the interface it didn't have the red * next to it. Now with the new form theme it does, so I wonder if that's the problem from the interface side. It needs to be required because then interface doesn't allow an empty field. 
2. Currently "Minimum severity level" allows you to save absolutely any string, even though it seems it's meant specifically for threat level (which is an int number). I wonder if I should add a check to make sure it doesn't happen?

**Comment by PululuK** [comment]
Hi @JevgenijVisockij 

I can do it here https://github.com/PrestaShop/PrestaShop/pull/21075  if it doesn't bother you.

**Comment by JevgenijVisockij** [comment]
> Hi @JevgenijVisockij
> 
> I can do it here #21075 if it doesn't bother you.

Oh, of course, go ahead! I am closing the PR then.

**Comment by JevgenijVisockij** [comment]
Closed in favor of https://github.com/PrestaShop/PrestaShop/pull/21075

**Comment by PululuK** [comment]
> Oh, of course, go ahead! I am closing the PR then.

If you have any suggestions do not hesitate to comment on [my PR](https://github.com/PrestaShop/PrestaShop/pull/21075) please !

**Pull request closed without merging**
