### PR TITLE
Merge 8.1 to develop

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1 to develop
| Type?             | bug fix 
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by 0x346e3730 — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
@FabienPapet 

I think you should wait for the merge PR 8.0->8.1 to be merged first, to make sure develop is fully up to date after the two PRs

(Edit: I meant this PR https://github.com/PrestaShop/PrestaShop/pull/31680)

**Comment by nicosomb** [comment]
Tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4376412309

**Review by jolelievre — DISMISSED** [review]
Thanks @FabienPapet

**Comment by nicosomb** [comment]
@FabienPapet should I run the tests again?

**Review by mflasquin — DISMISSED** [review]

**Comment by FabienPapet** [comment]
yes @nicosomb

**Comment by nicosomb** [comment]
https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4383048266

**Comment by nicosomb** [comment]
@FabienPapet there is a conflict with your PR. 
About the tests, 5 are failing. Don't know if they are related to your PR.

**Comment by nicosomb** [comment]
Tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/4383498155

**Review by 0x346e3730 — DISMISSED** [review]
https://www.youtube.com/watch?v=AWM5ZNdWlqw

**Review by jolelievre — DISMISSED** [review]
Thanks @FabienPapet

**Review by nicosomb — APPROVED** [review]
ok for me. 

@PrestaShop/qa-automation can you tell us if failing tests are related to this PR or not please?

**Comment by nesrineabdmouleh** [comment]
Hello @nicosomb
The errors are not the same in the nightly, I will check the failures but please restart the failed jobs
New run => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/4384991664

**Review by mflasquin — APPROVED** [review]

**Comment by jolelievre** [comment]
I just ran another run, because I wasn't sure if yours included the latest fix Fabien added @nesrineabdmouleh (the PR was modified not long before your message so it could be missing some commits)
Just to be sure https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4385205654

**Comment by nesrineabdmouleh** [comment]
@jolelievre UI tests are :heavy_check_mark: in my run => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/4384991664 I think it includes the latest fix of Fabian

But in your run you have two failed jobs => 'BO-international' & 'BO-shopParameters' (You can restart failed job)

**Comment by paulnoelcholot** [comment]
Hello @FabienPapet @jolelievre 

I'm testing the PR but for the moment the auto tests have returned bugs : https://github.com/paulnoelcholot/testing_pr/actions/runs/4405637284/jobs/7717987638

**Comment by jolelievre** [comment]
Closed in favor of https://github.com/PrestaShop/PrestaShop/pull/31773

**Pull request closed without merging**
