### PR TITLE
Check if intl is installed in installer

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Check if intl extension is loaded before running installer
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Try to install with and without intl extension.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11937)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
I thought it wasn't a mandatory extension, as I never installed on my environment. Did something change recently?

**Comment by PierreRambaud** [comment]
It's a mandatory extension for composer.json, Symfony and also to send Mail.

**Comment by PierreRambaud** [comment]
Ping @eternoendless Should we merge this in 1.7.5.1 (There are issues about missing intl) or develop ?

**Review by matks — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Target 1.7.5 is validated by @eternoendless, we can merge!

**Comment by eternoendless** [comment]
For the record, [it has always been required](https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/#extensions)... but visibly it wasn't being enforced.

Thank you @PierreRambaud

**Pull request merged**
