### PR TITLE
Align "Sign in" button to center in mobile phones

### PR DESCRIPTION
**Pull request by templatin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The "Sign in" button should be aligned to center in mobile phones to make it look good and perfect.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | No
| Deprecations?     | No
| How to test?      | Check the "Sign in" button on customer login form in mobile phone.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22638)

### CODE REVIEW

**Review by Arman-Hosseini — DISMISSED** [review]

**Comment by Arman-Hosseini** [comment]
Please amend your commits and use force push.

**Comment by templatin** [comment]
> Please amend your commits and use force push.

I didn't understand what you mean.

I don't use Github regularly so you can consider me a newbie to it and sorry about the last commit.
Actually I wanted to create a new PR for changes in pagination.tpl file but don't know how it got pushed to this PR. If you can, please delete that last commit and consider only the login-form.tpl file.

**Comment by Arman-Hosseini** [comment]
> > Please amend your commits and use force push.
> 
> I didn't understand what you mean.
> 
> I don't use Github regularly so you can consider me a newbie to it and sorry about the last commit.
> Actually I wanted to create a new PR for changes in pagination.tpl file but don't know how it got pushed to this PR. If you can, please delete that last commit and consider only the login-form.tpl file.

Hey @templatin, take it easy :)

You can modify your last commit with using: `git commit --amend`

You can also back to earlier commit with: `git reset <commit_key>`
And after all, use this: `git push -f <remote> <current_branch>`

**Comment by Arman-Hosseini** [comment]
There is one more thing.
You must target the `develop` branch instead of `1.7.7.x` branch.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Please target th  develop branch :)

**Review by matks — CHANGES_REQUESTED** [review]
Hello @templatin and thank you for the contribution. Apologies for the very late answer.

Code seems good but as mentioned by my peers, the target branch must be `develop` not `1.7.7.x`. I see you changed it once, then reverted it. Is there a problem?

**Comment by templatin** [comment]
Done :)

**Review by matks — DISMISSED** [review]
perfect, thank you ! I approve the PR

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/ux-team Hi, are you ok with this bug fix/improvement ?

**Review by NeOMakinG — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by atomiix** [comment]
Closed and re-opened to trigger the CI

**Comment by prestascott** [comment]
Hi everyone,

Sorry for the late reply ✌️ 
Thank you @templatin for you PR. Centering is a nice improvement for the login page.

I suggest fitting the button with the screen like this:
Login page - Mobile

It will be easier for customers to tap on the button since they use their mobile.

Wdyt?

**Comment by florine2623** [comment]
Hello @templatin ,

Thanks for the PR !

Do you think you could do as suggested by @prestascott in previous message ?

Now I have :
Screenshot 2021-09-07 at 15 01 24

Thanks !

**Comment by templatin** [comment]
Hey, I can do the changes as suggested by @prestascott but don't know how to do it cleanly. I tried merging few minutes ago and now its showing some unwanted files. Sorry for the mess.

**Comment by NeOMakinG** [comment]
@templatin 

All you need to do is a rebase, I could do it for you but it's something interesting to learn honestly.
By the way, as 1.7.7.x as a lot of differences between 1.7.8.x and then develop, I would completely git reset --hard on the develop head then redo the work on develop, as the PR is not too big, feel free to contact me on slack or there if you need help

**Comment by templatin** [comment]
> @templatin
> 
> All you need to do is a rebase, I could do it for you but it's something interesting to learn honestly.
> By the way, as 1.7.7.x as a lot of differences between 1.7.8.x and then develop, I would completely git reset --hard on the develop head then redo the work on develop, as the PR is not too big, feel free to contact me on slack or there if you need help

Sorry but I don't understand what you mean about resetting. I don't use Github too often and find it confusing. Can I close this pull request?
The changes I submitted is very small, even you or anyone can submit it.

For making the changes suggested by @prestascott , it just need to add a single line of CSS (width: 100%) to button class and also the changes requested in this pull should be reverted back.

**Comment by NeOMakinG** [comment]
@templatin close it if you want, don't hesitate to create a new PR to fix @prestascott feedback, overwise I may think about it later

**Comment by Julievrz** [comment]
There are no strings in this PR, I'm removing the label but feel free to ping me if needed.

**Pull request closed without merging**
