### PR TITLE
Fix bug when creating order from BO in Italian language

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Can't create order from back office with Italian language. The problem is related to some translations with one quotes that make some problems in the JS.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2882
| How to test?  | Try to add an order from the BO.

### CODE REVIEW

**Comment by AlexEven** [comment]
@vincentbz - not sure how I can help here ^^

**Comment by Quetzacoalt91** [comment]
The domain are missing, you may want to add them at the same time?

**Comment by aleeks** [comment]
Hello @fatmaBouchekoua 
I've the bug in 1.7.1.x branch but not in develop so i'm closing this.
Regards

**Comment by Uebix** [comment]
Fix at https://github.com/PrestaShop/PrestaShop/pull/8476

**Pull request closed without merging**
