### PR TITLE
Check if product is active and orderable during checkout

### LINKED ISSUE #33071: Customer can order disabled product from front office
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Please follow exactly as my video.

[github3.webm](https://github.com/PrestaShop/PrestaShop/assets/136475297/efb497b0-fa50-4d0a-a3b8-c7f92726f546)

### Expected behavior

While clicking on "Proceed to checkout" button on the next page or on the same page it should display error that "Product is not available"

### Steps to reproduce

Go to FO and add a product in cart
Now come to backoffice and disable the same product
Now go to the front office and without reloading just press on "Proceed to checkout"
You can see, you can order the product successfully, which must not be.

### PrestaShop version(s) where the bug happened

 8.1.0

### PHP version(s) where the bug happened

7.4 and 8.0

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Webkul

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Checks if the product is active and orderable in all steps of the checkout. Should be probably unified with `Cart::checkQuantities` for v9, but this is a safe fix. This PR also backports https://github.com/PrestaShop/PrestaShop/pull/32946 by @Tofandel to make this fix work properly.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See if related issue is fixed.
| Fixed ticket?     | Fixes #33071
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@kpodemski @FabienPapet CS fix, reapprove pls 🙏

**Review by kpodemski — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Thanks for the PR !

Unfortunately, it is not completely fixed.

I should have a message indicating why I can't proceed to checkout + the process to checkout button should be gray like in previous versions.
Screenshot 2023-07-10 at 15 31 44

Here's what I have :
Can't go further to checkout.

https://github.com/PrestaShop/PrestaShop/assets/16019289/cb858e78-9cab-419c-9610-10d52e58963c

Could you check ?

**Review by jolelievre — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@florine2623 Oh, I see the issue, but I have no idea who broke that functionality. Can we agree to merge my fix at least and then work on the cart issue?

Ping @PrestaShop/committers

**Comment by kpodemski** [comment]
@Hlavtox the 8.1.1 is in 6 days, I think we should try to fix it

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@florine2623 Hi, can you please retest it? We managed to fix this issue, should work properly! :-)

**Review by mflasquin — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by sallemiines — APPROVED** [review]
Hello @Hlavtox 

Thanx for the PR ! LGTM QA :heavy_check_mark: 
[Tests auto](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5520334925/jobs/10066810350) : ok

https://github.com/PrestaShop/PrestaShop/assets/31663369/b33e2bca-9e82-4deb-abd1-075ad77b80ca

Thank you :rocket:

**Comment by Hlavtox** [comment]
Thank you @sallemiines! :-))))

**Pull request merged**
