### PR TITLE
Introduce NumberMinMaxFilterType and IntegerMinMaxFilterType

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As for products list page I need two inputs besides each - one type is  for filtering ids while another type is for numbers such as price.
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | partialy required for https://github.com/PrestaShop/PrestaShop/pull/14267
| How to test?  | Within this PR this component will not appear anywhere. It will be used by others once it is merged so no manual testing is required

To do after release of this:

- [ ] Document it!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14320)

### CODE REVIEW

**Comment by rokaszygmantas** [comment]
```php
$minMaxForm = $this->createForm(MinMaxType::class, [], [
            'required' => true,
            'min_field' => IntegerType::class,
            'min_field_options' => [
                'help' => 'inner help message',
            ],
            'max_field' => NumberType::class,
        ]);
```

maybe we should introduce two min max types, one for integer and one for float values (if it's needed)? I think it's better compared to having one generic min max type and having to define types when building the form.

**Comment by tomas862** [comment]
> ```
> $minMaxForm = $this->createForm(MinMaxType::class, [], [
>             'required' => true,
>             'min_field' => IntegerType::class,
>             'min_field_options' => [
>                 'help' => 'inner help message',
>             ],
>             'max_field' => NumberType::class,
>         ]);
> ```
> 
> maybe we should introduce two min max types, one for integer and one for float values (if it's needed)? I think it's better compared to having one generic min max type and having to define types when building the form.

@rokaszygmantas  we have more then just two types:

`MoneyType`
`PercentType`
`RangeType`

but Im thinking right now that you might be right here - I thought about this as well. 

Maybe we could have :

`IntegerMinMaxType`
`NumberMinMaxType`
`PercentMinMaxType`
`MoneyMinMaxType`

and we also have native type `RangeType` which is `<input type="range">` so it would be `RangeMinMaxType` which basically adds two sliders 

anyway this is closely related to my second problem which is:
how to control layout in grid since same html does not fit anymore so well.

two options:

1. Either we will have `GridIntegerMinMaxType`, `GridNumberMinMaxType` etc...
2. Either I try to apply some css magic to fit these types in Grid so the same type can be rendered in form and in grid.

**Comment by tomas862** [comment]
gonna apply it for grid use case only - when someone will need it they can extend the functionality.

**Comment by tomas862** [comment]
@matks this one is required for continue of product page listing development - review when you can :)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Review is ✅ and I restart Travis

**Comment by tomas862** [comment]
need restart Travis again - too random error to be related with this PR :D

**Comment by matks** [comment]
LGTM

**Pull request merged**
