### PR TITLE
Cart rule is applied even is disabled in specific conditions

### LINKED ISSUE #19393: CART RULE - cart rule is applied even when you disabled
#### Describe the bug

If a Cart rule for cheapest product is created but not enabled and if a second cart rule is created and enabled the first one is displayed and enabled in the FO

#### Expected behavior

The cart rule must not be applied and displayed if not enabled

#### Steps to Reproduce

- [ ] Test1
1. Go to the BO => Catalog => Discounts => Create a new cart rule with the following parameters (see the attached screenshots below)
2. Enable the previously created cart rules
3. Go to the FO => Add to the cart demo_11 & demo_6
4. Go to the cart page => The cart rule is correctly applied to the cheapest product ( demo_11 )
5. Go Back to the BO => Catalog => Discounts => and disable the cart rule 
6. Go to the FO again and check the cart => the cart rule is applied and displayed => NOK

> ~7. Go Back to the BO => Catalog => Discounts => Create a new cart rule the parameters of this cart rule don't really matter just create a cart rule with a generated code and a amount of 10 % it's enough~
> ~8.Enable this cart rule~
> ~9. Go to the FO again and check the cart => the newly created cart rule is available~
> ~10. See error => the first created cart rule is applied and displayed even if not enabled in BO~

- [ ] Test2
>Edit by @hibatallahAouadni 

1. FO, add products to cart and apply a voucher
2. BO, edit the voucher date (valid to) to be expired
3. FO, refresh the page the voucher still applied => NOK
4. Delete the voucher, then you will see you can't apply it again => OK

- [ ] Test3
> Edited by Khouloud

Other steps to reproduce the same issue as described here https://github.com/PrestaShop/PrestaShop/issues/27650

**Preparation**
1. Create customer group ID 4.
2. Create a new customer, put him to group 4, set default group 4.
3. Create a cart rule that will apply automatically, cart rule will give a free gift, set group restriction only to 1, 2, 3.

**Actual bug**
1. Log in as the customer you created.
2. Add something to cart and go to cart.
3. Now, go edit that customer in BO, tick that he belongs to group 1.
4. Go back to cart, hit F5. Cart rule will be applied and gift added to cart.
5. Go back to edit customer, un-tick group 1, save.
6. Go back to cart, hit F5. Gift is not removed from cart.
_(7. It's removed when you +- the quantity on your product.)_
**Screen record**
https://drive.google.com/file/d/1SgVUMepMz-XsaUKgafB7aVv9LGnlAYLO/view

**Screenshots**

**Cart rule's parameters**
capture d'écran_35
capture d'écran_36
capture d'écran_37

**The cart rule is disabled in BO**
capture d'écran_43

**But applied and displayed in FO**
capture d'écran_44

#### Additional information

* PrestaShop version:1.7.7.x and 1.7.6.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | If a Cart rule for cheapest product is created but not enabled and if a second cart rule is created and enabled the first one is displayed and enabled in the FO.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19393.
| How to test?  | See #19393 By @SD1982 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19399)

### CODE REVIEW

**Comment by matks** [comment]
@PululuK Good evening 😄

**Review by matks — DISMISSED** [review]
Looks logic 👍

**Comment by matks** [comment]
However this breaks one of our unit tests.
See Travis output https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/340236747

To run the tests locally `php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit.xml`

The question is: is the test good (so it has found an issue with your PR) or is the test wrong (it did not handle this usecase) ? If test is wrong it needs to be updated

**Comment by PululuK** [comment]
> @PululuK Good evening smile

Don't be afraid, you can go to bed 😅

**Comment by PululuK** [comment]
> However this breaks one of our unit tests.
> See Travis output https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/340236747
> 
> To run the tests locally `php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit.xml`
> 
> The question is: is the test good (so it has found an issue with your PR) or is the test wrong (it did not handle this usecase) ? If test is wrong it needs to be updated

Thank you  @matks ! I will check that out later.

**Review by Progi1984 — APPROVED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Need Travis to be fixed ;)

**Comment by PululuK** [comment]
> However this breaks one of our unit tests.
> See Travis output https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/340236747
> 
> To run the tests locally `php -d date.timezone=UTC ./vendor/bin/phpunit -c tests-legacy/phpunit.xml`
> 
> The question is: is the test good (so it has found an issue with your PR) or is the test wrong (it did not handle this usecase) ? If test is wrong it needs to be updated

Unit tests is ok! Now the Behavior tests looks broken

**Comment by PierreRambaud** [comment]
Hey @PululuK are you still working on it?

**Comment by PierreRambaud** [comment]
Hi @PululuK ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
