### PR TITLE
Fix PHP CS FIXER - again

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Because an old pull request has been merge without taking in consideration the new php-cs-fixer configuration.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Travis and tests must be green. No need QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17446)

### CODE REVIEW

**Comment by matks** [comment]
Creating copy of https://github.com/PrestaShop/PrestaShop/pull/17435 because Travis is drunk

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Need another approval to fix develop @PrestaShop/prestashop-core-developers

**Review by Matt75 — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Pull request merged**
