### PR TITLE
Update function getCustomerOrders to avoid error

### LINKED ISSUE #27967: Customer Account / Order History ContextErrorException when it crashed during order creation
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When an order is missing in table ps_order_history due to a crash during order creation, and when customer wants to see his/her order history, today, it gives a "ContextErrorException : Trying to access array offset on value of type null", because $orderState becomes null and so $orderState['name'], $orderState['invoice'], $orderState['color'] can't exist. By using Null Coalescing Operator instead of Ternary Operator, we avoid the error.

### Expected behavior

It should show the list of Orders

I proposed a new code here : [https://github.com/PrestaShop/PrestaShop/pull/27179](https://github.com/PrestaShop/PrestaShop/pull/27179)

### Steps to reproduce

1. Make an order in FO using customer ZJA
2. Remove its SQL lines from table ps_order_history table
3. Then browse customer account ZJA, click on order history.

### PrestaShop version(s) where the bug happened

1.7.8.4

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NicolasCador**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When an order is missing in table ps_order_history due to a crash during order creation, and when customer wants to see his/her order history,  today, it gives a "ContextErrorException : Trying to access array offset on value of type null", because $orderState becomes null and so $orderState['name'], $orderState['invoice'], $orderState['color'] can't exist. By using Null Coalescing Operator instead of Ternary Operator, we avoid the error.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27967
| How to test?      | See below
| Possible impacts? | Only order history in customer account.

### Description

Today, it gives a "ContextErrorException : Trying to access array offset on value of type null", if there was a crash during order creation, because $orderState becomes null and so $orderState['name'], $orderState['invoice'], $orderState['color'] can't exist.
By using Null Coalescing Operator instead of Ternary Operator, we avoid the error.

### How to test

1. Make an order in FO using customer ZJA
2. Remove its SQL lines from table ps_order_history table
3. Then browse customer account ZJA, click on order history.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27179)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hello, I understand the logic.

In order to make it very clear what is happening, can I suggest this code:
```
            $orderState = !empty($val['id_order_state']) ? $indexedOrderStates[$val['id_order_state']] : null;

            if ($orderState) {
                $res[$key]['order_state'] = $orderState['name'] ?: null;
                $res[$key]['invoice'] = $orderState['invoice'] ?: null;
                $res[$key]['order_state_color'] = $orderState['color'] ?: null;
            }
```

I added a `if ($orderState) {...}`
 
 this way
 - we dont enter the `if()` statement is `$orderState` is null -> 3 useless statements avoided
 - the code is quite clear about what it does: "in case $orderState is not null, fetch that data, else just skip that"

**Comment by NicolasCador** [comment]
> Hello, I understand the logic.
> 
> In order to make it very clear what is happening, can I suggest this code:
> 
> ```
>             $orderState = !empty($val['id_order_state']) ? $indexedOrderStates[$val['id_order_state']] : null;
> 
>             if ($orderState) {
>                 $res[$key]['order_state'] = $orderState['name'] ?: null;
>                 $res[$key]['invoice'] = $orderState['invoice'] ?: null;
>                 $res[$key]['order_state_color'] = $orderState['color'] ?: null;
>             }
> ```
> 
> I added a `if ($orderState) {...}`
> 
> this way
> 
> * we dont enter the `if()` statement is `$orderState` is null -> 3 useless statements avoided
> * the code is quite clear about what it does: "in case $orderState is not null, fetch that data, else just skip that"

Hello matks,

in fact, in line 968, there a comment "// In case order creation crashed midway some data might be absent" to explain these 3 lines are there to put null in $res[$key]['order_state'], $res[$key]['invoice'], $res[$key]['order_state_color'] when there was a crash during order creation.
With your suggestion, $res[$key]['xxx'] will never be null or anything else. May it be a problem?

**Review by matthieu-rolland — APPROVED** [review]
> Hello, I understand the logic.
> 
> In order to make it very clear what is happening, can I suggest this code:
> 
> ```
>             $orderState = !empty($val['id_order_state']) ? $indexedOrderStates[$val['id_order_state']] : null;
> 
>             if ($orderState) {
>                 $res[$key]['order_state'] = $orderState['name'] ?: null;
>                 $res[$key]['invoice'] = $orderState['invoice'] ?: null;
>                 $res[$key]['order_state_color'] = $orderState['color'] ?: null;
>             }
> ```
> 
> I added a `if ($orderState) {...}`
> 
> this way
> 
> * we dont enter the `if()` statement is `$orderState` is null -> 3 useless statements avoided
> * the code is quite clear about what it does: "in case $orderState is not null, fetch that data, else just skip that"

I think @NicolasCador is right, with this condition, in the case of a crash happening (which the code tried to deal with), the keys for `$res[$key]['order_state'` etc... will just not exist anymore, so we're removing properties from the array being returned in this very specific situation

lgtm

**Review by sowbiba — APPROVED** [review]

**Review by sowbiba — DISMISSED** [review]
Finally take the approval back. Can you please create an issue and fill correctly the PR description table ? It'll be helpful for the QA to test it and for our changelog

**Comment by NicolasCador** [comment]
>

**Comment by NicolasCador** [comment]
Hello @sowbiba ,

sorry, I don't understand your request.

Could you please help me?

**Comment by matks** [comment]
@sowbiba is referring to this
Capture d’écran 2022-01-13 à 22 49 08

**Comment by NicolasCador** [comment]
ah ok
and what is the request exactly?

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]
Apologies for late answer. I updated the description for you as I was late.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@NicolasCador Could you create an issue for validation the bug by the @PrestaShop/qa-functional team ? Thanks

**Comment by matks** [comment]
@Progi1984 I don't think a scenario can be performed by QA team as this is a complex usecase happening only in an exotic scenario. This is why I think QA by dev is more relevant.

**Comment by NicolasCador** [comment]
Thank you @matks, because I didn't understand the question from @Progi1984

**Comment by Robin-Fischer-PS** [comment]
Hi there,

It can be tested by a dev for the fixed issue, but it would be better to have a regression test by the QA afterwards.

And if would indeed be nice to have an issue linked to the PR, since it's obviously a bug fix.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@NicolasCador Hi, could you open an issue for your bug : https://github.com/PrestaShop/PrestaShop/issues/new/choose ?

**Comment by NicolasCador** [comment]
> @NicolasCador Hi, could you open an issue for your bug : https://github.com/PrestaShop/PrestaShop/issues/new/choose ?

Ok done

**Comment by HanaRebaiQA** [comment]
Hello everyone,

Could you please change the base branch to **1.7.8.x**  instead of develop since the verified issue is a regression (see the comment [here](https://github.com/PrestaShop/PrestaShop/issues/27967#issuecomment-1076446963)) ?

Thank you!

**Comment by NicolasCador** [comment]
Hello @Progi1984 & @matks 

how a can we change the base branch to 1.7.8.x instead of develop since the verified issue is a regression?

Thanks

**Comment by matks** [comment]
@NicolasCador Do you mean you don't know how to switch the PR branch?

**Comment by NicolasCador** [comment]
@matks yes I don't know, sorry

**Comment by matks** [comment]
😄  it's OK all of us learnt it one day.

To change the PR base branch you can follow https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

It is however likely that your branch is based on develop and not on 1.7.8.x . So if you change the branch you will have a lot commits unneeded.

To avoid this, you might need to create a new branch, that starts from 1.7.8.x and then cherry-pick your commit on it
-> follow https://dev.to/grepliz/how-to-cherry-pick-commits-into-a-new-branch-284n
-> https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/cherry-picking-a-commit

**Comment by NicolasCador** [comment]
@matks I'm sorry, I don't find how to do exactly... what "GitHub Desktop"?

**Comment by kpodemski** [comment]
@NicolasCador 

If you don't feel comfortable with Git and don't have time to play with it, feel free to create a new PR targeting 1.7.8.x branch. Thank you for your efforts ❤️

**Comment by NicolasCador** [comment]
Hello all, ok, thank you, I created a new Pull Request in the right branch 1.7.8.x : https://github.com/PrestaShop/PrestaShop/pull/28117

**Comment by kpodemski** [comment]
Thank you @NicolasCador

**Pull request closed without merging**
