### PR TITLE
FIX bug #34199

### LINKED ISSUE #34199: Trying to access array offset on value of type null Product.php
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the Product.php file an error occurs on the following lines:
        array_unshift($result, null);
        foreach ($result as &$value) {
            $value = $value['id_product'];
        }

This code adds null to the beginning of $result and in the first interaction it gives an error when querying the id_product variable because the first value of $result is null

This causes a php error:
Got error 'PHP message: [PHP Warning #2] Trying to access array offset on value of type null .../Product.php..., line 7245 

### Expected behavior

We hope it doesn't cause that any error or warning 

### Steps to reproduce

 Execute this php snippet:

// Enter your code here, enjoy!
        $result=array(array('id_product'=>10));
        array_unshift($result, null);
        foreach ($result as &$value) {
            $value = $value['id_product'];
	    print($value);
        }

You will get this: 
Warning: Trying to access array offset on value of type null in ...

Solution proposal:
       // Move array_unshift to the end
        foreach ($result as &$value) {
            $value = $value['id_product'];
	    print($value);
        }
       **array_unshift($result, null);**

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1.24

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by KinG-InFeT**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | resolve core bug just resolved into develop branch
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | update product via API
| Fixed issue or discussion?     | Fixes #34199

### CODE REVIEW

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@KinG-InFeT Hi, please fill out description of the PR. :-)

**Comment by KinG-InFeT** [comment]
> @KinG-InFeT Hi, please fill out description of the PR. :-)

filled :)

**Comment by matks** [comment]
Hello we cannot verify the bug is fixed without a valid bug report ; please help providing a valid bug report here https://github.com/PrestaShop/PrestaShop/issues/34199

Something like "Do A then B then C", not "look at the code" 😉

**Comment by matks** [comment]
Hi,

Since we had no news from you since July, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Comment by jakubvondrak** [comment]
> Hi,
> 
> Since we had no news from you since July, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.
> 
> Thanks!

@matks: I've provided reproduction steps in https://github.com/PrestaShop/PrestaShop/issues/34199 three weeks ago. Please reopen and merge this PR.

**Comment by eveneme** [comment]
+1

**Comment by matks** [comment]
> > @KinG-InFeT Hi, please fill out description of the PR. :-)
> 
> filled :)

"resolve core bug just resolved into develop branch" this is not a valid description of this pull request. A valid descriptions is described here https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/

> Describing your change and the reasoning behind it is extremely important for it to be reviewed and approved. Explain, in as much detail as you can, what did you change and why.

> If you need space, just write a short summary about your change in the table, then describe in more detail below it. You are also encouraged to add links, files, screenshots… anything that can help reviewers understand why the change is needed, and why it’s valid.

"update product via API" is also far from satisfying

> In addition to being code reviewed, each individual contribution is manually verified by PrestaShop’s QA team. In order to effectively confirm that your change doesn’t introduce new errors, please describe how to best verify that your change does what you expect it to do. Feel free to write as much details as you can outside the table if needed.

If you're not willing to follow our processes, please don't submit a Pull Request. These process are here to help us guide the changes being merged into the codebase, and are very valuable for prestashop users. You cannot simply skip them.

**Comment by matks** [comment]
I think the most efficient option to help this topic is to move it forward myself so I submitted a Pull Request https://github.com/PrestaShop/PrestaShop/pull/36807 to fix it. The code changes are almost identical to this Pull Request, however I added the missing items to comply with our process.

**Pull request closed without merging**
