### PR TITLE
Add Malagasy language

### PR DESCRIPTION
**Pull request by OneDotIT**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add the support for Malagasy language.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | #14074 #15435
| How to test?  | Through the localization option, create a new language with costume ISO code.

~~Branch of 1.7.6.x as the request #15063.~~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15482)

### CODE REVIEW

**Comment by Progi1984** [comment]
@OneDotIT You have used base branch as 1.7.6. Could you use develop as base branch and re-push ?

**Comment by OneDotIT** [comment]
This the main commit with the base as develop #15063, but you asked for it to be re-based to current release ?

> Hello @OneDotIT, thanks for your contribution, would you mind to rebase your pull request? Thanks

**Comment by Progi1984** [comment]
@OneDotIT Sorry, but I misspoke. I wanted you rebased your pull request (git rebase) to the latest version of the develop branch (because your PR was based on develop branch but not its latest branch). Could you create a PR based to the develop branch (and its latest version) ?

Reference : http://build.prestashop.com/howtos/misc/rebasing-your-git-branch/

**Comment by OneDotIT** [comment]
As this: #15484

**Comment by Progi1984** [comment]
@OneDotIT Perfect ;)

**Pull request closed without merging**
