### PR TITLE
// Fix NPM install on Windows

### PR DESCRIPTION
**Pull request by martinfojtik**

### CODE REVIEW

**Comment by kpodemski** [comment]
Oho, i'm going to test it right away! :D

**Comment by kpodemski** [comment]
For me problem still occurs, this is part of my npm-debug:
http://pastebin.com/WW7QEcRQ

any clues?

**Comment by fojtCz** [comment]
i dont know why this is happening, but you can open folder `js/vendor` and run`npm install` from there

**Comment by Shudrum** [comment]
Hi everyone!

`package.json` is already updated: https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/default/package.json, and Webpack is used to compress & import the needed modules.

So the `cp` is already removed :)

**Comment by Shudrum** [comment]
@kpodemski: It is the `npm -C` command making your install fail… I just don't know why… You have a latest version of npm & node…

But, running the npm install on the test folder during the install is… not a good idea. I'll remove it.

I hope this will now work for you after this fix.

Stay tuned!

**Comment by kpodemski** [comment]
@Shudrum thank you!

**Pull request closed without merging**
