### PR TITLE
Remove the discount (if any) from the total amount of credit split

### LINKED ISSUE #35614: BO > Order details page - Amount displayed on Document tab for Credit slip is incorrect when made on an order with discount
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

For example :
- Total order price : 100€
- Total discount : 30€

The credit slip should be 70€ but it's actually 100€.

### Expected behavior

In my Document Block, the Amount should be 70€, instead of 100€

### Steps to reproduce

1. Go to BO > Orders > Discounts > Create a discount 30€
2. Create a product 100€
3. In FO > Add the product to your cart > Proceed checkout, make sure the discount is taken into account
4. Go to BO > Change status to Paiement accepted
5. Click Partial Refund 
6. Select > `Generate a credit slip` & `Product(s) price, excluding amount of initial voucher: €70.00` > Click Partial Refund
7. See in Document Block > the Amount column is incorrect. It displayed €30.00, it should be €70.00

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This fix should solve the wrong credit slip total amount calculation, despite the pdf generated is correct, the data stored in database is not. Now the value is correct and displayed correctly in the document tab in the order page. When the merchant choose
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Follow the issue
| UI Tests          | Please run UI tests and paste here the link to the run. As we support MySQL and MariaDB in our tests, you have to launch 2 campaigns (by choosing both). [Visit the UI Tests repo and follow instructions](https://github.com/PrestaShop/ga.tests.ui.pr/).
| Fixed issue or discussion?     | Fixes #35614 
| Sponsor company   | Myself

### CODE REVIEW

**Comment by kpodemski** [comment]
Hello @marsaldev 

Could you target `9.0.x` branch? `develop` is currently for `9.1.x` version, it would be better to have your bugfix inside 9.0

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hi @marsaldev 

Please target `9.0.x` branch, so we have this fix inside `9.0` 🙏🏻

**Comment by marsaldev** [comment]
Sorry Krystian, just saw your message, no problem 👍🏼

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Notifications.Error`
    - [ ] `Link to database cannot be established: %s`
    - [ ] `PrestaShop Fatal error: no utf-8 support. Please check your server configuration.`
    - [ ] `Graph module could not be loaded.`
    - [ ] `Grid module could not be loaded.`
- `Admin.Orderscustomers.Feature`
    - [ ] `ID:`
    - [ ] `Customer private note`
    - [ ] `Order private note`
    - [ ] `MPN:`
- `Admin.Global`
    - [ ] `Basic information`

(Note: this is an automated message, but answering it will reach a real human)

**Comment by marsaldev** [comment]
@kpodemski sorry Krystian, I made a mess, I closed this PR and opened a new one https://github.com/PrestaShop/PrestaShop/pull/37621

**Pull request closed without merging**
