### PR TITLE
Update Grid definition Ids

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Removes `_` from grid ids and updates to camel case. Also registers new hooks during installation.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Behavior does not change in this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10569)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Once tests pass, I'll merge => 0 risks, only gains :)

@PrestaShop/prestashop-core-developers this pull request allow the hook debugger to display the Grid hooks even if no module register it, and rename it to make the hook name more consistent with others hooks :+1:

**Review by PierreRambaud — DISMISSED** [review]

**Comment by jolelievre** [comment]
wouldn't it be easier to have a special getter that Camelize the getId() value, `getHookGridId()` for example
this way even if developper forget about the correct syntax it will work fine, and we can keep get getId in (potentially) snake case elsewhere (eg javascript) since it is less important

**Comment by eternoendless** [comment]
Unit tests are failing 🙁

**Comment by PierreRambaud** [comment]
Travis crashed, I rerun tests :)

**Comment by sarjon** [comment]
anybody has any ideas why its failing? :/ i cant understand how these changes may affect tests. :disappointed:

**Comment by PierreRambaud** [comment]
@sarjon I know. these tests are using hook and module ids, you add new hook, so ids change =)

**Comment by sarjon** [comment]
>  these tests are using hook and module ids

right.. now i understand, ill need to find a way to fix it.

**Comment by PierreRambaud** [comment]
@sarjon I can have a check this afternoon if you want?

**Comment by sarjon** [comment]
@PierreRambaud i've tried to fix it, lets see if it works out. :crossed_fingers:

**Comment by sarjon** [comment]
all is good. :+1:

**Review by PierreRambaud — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @sarjon and everyone for the reviews :+1:

**Pull request merged**
