### PR TITLE
Fixed tax manager class constructor parameters

### PR DESCRIPTION
**Pull request by gfilippakis**
The tax manager class should receive at least the same parameters as TaxRulesTaxManager class in TaxManagerFactory

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The tax manager class should receive at least the same parameters as TaxRulesTaxManager class in TaxManagerFactory
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create a tax manager module that extends TaxManagerModule class and use the constructor from TaxRulesTaxManager class for your tax manager class.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9088)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @gfilippakis,

at this moment we don't accept any more new features on `1.6.1.x`, but we can make the improvement available in the next `1.7.x` release by using develop instead.

Thanks for understanding

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Hi @gfilippakis,

By any chance do you have a module for the QA team to make the test faster?

**Comment by ntiepresta** [comment]
Hi @gfilippakis, 
Could you please provide us the module for the QA  test?
Best regards, Reddy Ntie

**Comment by gfilippakis** [comment]
[sleedtaxmanager.zip](https://github.com/PrestaShop/PrestaShop/files/2323597/sleedtaxmanager.zip)

**Comment by mickaelandrieu** [comment]
Thanks @gfilippakis!

**Comment by gfilippakis** [comment]
Since TaxRulesTaxManager receives both address and type as arguments when a new instance is created inside TaxManagerFactory::getManager, I consider it more consistent to provide the same arguments for any tax manager class.

**Comment by PierreRambaud** [comment]
@ntiepresta Why do you add the waiting for author without comment? Can you give us more information about what's missing?

**Comment by ntiepresta** [comment]
Hello, @PierreRambaud 
I have added the waiting for author after my comment  and my request of the module, for more information and more details on how to reproduce the issue , to better meet his needs.
Thanks

**Comment by PierreRambaud** [comment]
@ntiepresta This is why I don't understand. You asked for information, he gave you the module, @mickaelandrieu ask for QA, and you directly ask for author without any explanation.
Can you give us information about why it's waiting for author?

**Comment by ntiepresta** [comment]
@PierreRambaud,
It was for  understand how to reproduced the problem, I saw good  its module, but  I needed understand exactly how to reproduce its problem, because with its description, it was not very clear how to reproduce the problem . that all ok now, thank you.

**Comment by ntiepresta** [comment]
Hello, 
these errors are displayed after testing the module(sleedtaxmanager). 
Steps to reproduce these errors:
1. download and install  the module
2. B.O :  SELL , Catalog, product page. see error 
3. F.O :  click on a product. See error 
avec module dans b o
avec module

**Comment by gfilippakis** [comment]
Override Customer class:

```php
class Customer extends CustomerCore
{
    const CVAT_NORMAL = 0;
    const CVAT_REDUCED = 1;
    const CVAT_INEU = 2;
    const CVAT_NONEU = 3;
    const CVAT_EXCLUDED = 4;
}
```

**Comment by gfilippakis** [comment]
After the above override you will reach

> PHP Catchable fatal error:  Argument 1 passed to NGTaxManager::__construct() must be an instance of Address, none given

and this is the point where you need my commit changes in order to proceed.

**Comment by marionf** [comment]
Hello @gfilippakis 

I have another issue after overriding Customer class

capture d ecran_673

**Comment by gfilippakis** [comment]
Please keep in mind that my original fix was targeting 1.6.1.x branch and @mickaelandrieu switched it to develop on May 21st 2018. Therefore it is natural that some dependencies are missing.

I was actually hoping that this would be considered a bug fix for 1.6.1.x instead of a new feature.

**Comment by marionf** [comment]
I would like to validate your PR but I can't test it correctly with these errors

**Comment by gfilippakis** [comment]
My original fix was for 1.6.1.x, so please test it in 1.6.1.x.

It's 23 bytes of code added in one single file. We have spent too much time already debating on the complexity of testing such a small fix.

If you consider this fix valuable, please become more familiar with 1.6.1.x's codebase and evaluate the patch in 1.6.1.x.

**Comment by marionf** [comment]
In need to test it also on 1.7 because we will merge it on develop branch and I need to be sure it doesn't break anything

**Comment by gfilippakis** [comment]
My patch was originally addressing the 1.6.1.x branch.

The module that was supplied for testing works only on the 1.6.1.x branch.

If you need to test it on 1.7 you should write your own tests. 
In the meantime, you could have merged it into 1.6.1.x.

**Comment by marionf** [comment]
Hello @gfilippakis 

Since we have had no news for more than 30 days and this PR doesn't work, I close it
Feel free to open a new one if needed

**Pull request closed without merging**
