### PR TITLE
Add package weight in carrier

### LINKED ISSUE #20057: Package weight parameter missing (crucial to calculate shipping cost!)
#### Is your feature request related to a problem?

The request is pretty basic and simple. We need to be able to add a package weight somewhere in configuration.
Currently, if I would sell and send some products at a total of 9.8 KG, but the box I use to send it is 0.3 KG, the total weight would be 10.1 KG. My shipping cost for packages < 10 KG and > 10 KG is not the same. Because PS doesn't add my box weight to total, it calculates the wrong shipping price.

#### Describe the solution you'd like

Add a parameter somewhere so an additional weight can be added to the total weight before calculation of shipping cost.
There are handling charges in **shipping -> preferences**,  there ~~could~~ should also be **handling weight**.

#### Alternatives you've considered

I found an addon that has this purpose (among other things) but it seams illogical to pay €50 euro for such basic function, risking to have to pay the license again and again for each PS update in the future.

#### Additional context

There is lots of chatter about this topic on PS forums, dating back to PS 1.3.
It's hard to understand why it's not yet supported. 
As a PS newbie, this raises some red flags to continue using PS.

Thanks for your consideration

### PR DESCRIPTION
**Pull request by cdigruttola**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add new setting card in Shipping Preferences to manage package weight in shipping cost calculation by weight.
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Set a weight range in carrier, set a package weight and check if range chosen is correct according to sum of weight products and package weight.
| Fixed issue or discussion?     | Fixes #20057

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @cdigruttola!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Shipping.Feature`
    - [ ] `Price (VAT excl.)`
    - [ ] `Package weight`

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Blocking to prevent accidental merge. There have been some discussions in the issue about this, I personally don't think it's needed.

This packing weight doesn't resolve anything for two reasons:
- You can set additional weight including package for each product and it will be even better because it will scale properly.
- It's scope is very limited. The packing weight is not the same for 1 or 10 products, or for 1kg and 10kg package.

Ping @kpodemski @ibahloul-ps

**Comment by gericfo** [comment]
Hello @cdigruttola 
Please note that the **“Needs autoupgrade PR”** label has been automatically added to your Pull Request. This means that the changes made in your PR must also be reported in the **Autoupgrade module**, responsible for running the update process of PrestaShop stores. 
When there's a modification to the `db-structure.sql` file or if a Doctrine entity has been modified, added, or deleted, it impacts the database structure. Modifying the list of hooks and feature flags has consequences on the update process as well. These changes can affect how the application interacts with the database and how update procedures are handled. It's important to consider these aspects when contributing to ensure a smooth update experience for users. 
That's why this contribution should be backported, with another corresponding PR, on the **Autoupgrade module's GitHub repository** which is available here: [link](https://github.com/PrestaShop/autoupgrade). 
Don't forget to add a comment in this current thread with the link to this PR once it has been created. 
Thank you.

**Comment by MateoChateau** [comment]
> Blocking to prevent accidental merge. There have been some discussions in the issue about this, I personally don't think it's needed.
> 
> This packing weight doesn't resolve anything for two reasons:
> 
> * You can set additional weight including package for each product and it will be even better because it will scale properly.
> * It's scope is very limited. The packing weight is not the same for 1 or 10 products, or for 1kg and 10kg package.
> 
> Ping @kpodemski @ibahloul-ps


Hi 👋  From what I see after doing some research on the topic as well as on previous discussions: 
- This pain has easy alternative solutions (like for example take it into account while editing the ranges, and for products that have their own box include it in the product weight)
- I see that [a module](https://github.com/cdigruttola/packageweight) was created by @cdigruttola to solve this very same issue ? (haven't tested it yet ) Would be interesting to have some feedback from it.
- Adding a generic package weight seems not to answer completely to the pain, as the weight is not always the same for all packages within an order, so it seems like a sort of "half-way" solution

From what I understand of the provided solution in this PR I have to say that I agree with @Hlavtox, I would not advise to add this feature to the core as it is, I think the solution needs to be thought furthermore. 

I notice there's an [open discussion on the topic](https://github.com/PrestaShop/PrestaShop/discussions/35063), we can take it from there if you all agree. 

Thx !

**Comment by cdigruttola** [comment]
Hi @MateoCastilloPS,
I created the module based on the old version of the carrier page. I planned to update it for the new version of the carrier page.
Carmine

**Comment by kpodemski** [comment]
Hello @cdigruttola 

Thank you for taking the time to contribute.

Given the comments above, I'm closing this pull request since there is no agreement to have such changes inside the core.

**Pull request closed without merging**
