### PR TITLE
Add related PRs to pull request template

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I think we should add a standardized field for providing related PRs for classic, hummingbird, autoupgrade and others.
| Type?             |  improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | -
| Possible impacts? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28043)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Agree with this, it will be useful

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
What is this PR waiting for?

**Review by davidglezz — APPROVED** [review]

**Comment by matks** [comment]
> What is this PR waiting for?

I see this new field would be useful for some PRs. But majority of PRs will not use it. I'm not sure it's a good idea to insert a field that only applies to a minority of PRs.

Also if this PR is merged it needs to be followed up by an update of https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/pull-requests/#description

**Comment by kpodemski** [comment]
@matks 

I'm not sure I agree with you. We will see more PRs that need this field because:
- classic and hummingbird are separated repositories now
- we moved SQL upgrade files to the autopgrade not that long ago

**Comment by matks** [comment]
> @matks
> 
> I'm not sure I agree with you. We will see more PRs that need this field because:
> 
> * classic and hummingbird are separated repositories now
> * we moved SQL upgrade files to the autopgrade not that long ago

How many PRs will require a SQL upgrade, how many PRs will require an update of both theme repository and Core? And how many PRs will not be in these 2 usecases?

Note: it's possible to provide the "If theme, autoupgrade or other module change is needed, provide a link to related PRs here" inside the PR description outside of the template 😉 . I am not against requesting people to provide this link when necessary, we could add a message below.

It's just if we start adding fields "that apply to some Pull Requests but not all of them" to this table 😅 I'm worried it would become a very big table over time and create contribution friction.

So this is my worry 😊 . I'm not 100% sure I'm against this PR, but I state that I'm afraid of seeing this table becoming bigger and bigger if we start walking this path

Note: I just checked Magento PR template and they also have a "Related PRs" field (so this is actually an argument AGAINST me 😆 ) https://github.com/magento/magento2/blob/2.4-develop/.github/PULL_REQUEST_TEMPLATE.md

**Review by atomiix — APPROVED** [review]

**Comment by matks** [comment]
Seeing so many people approving this PR I guess I might be paranoid 😛

**Comment by NeOMakinG** [comment]
> Seeing so many people approving this PR I guess I might be paranoid 😛

Like a lot of PRs, just remove the line if you don't need it while contributing

**Comment by matks** [comment]
Let's get that merged then ❤️  thank you @Hlavtox 

@Hlavtox Will you update the documentation or I do it?

**Comment by Hlavtox** [comment]
@matks Done bro https://github.com/PrestaShop/docs/pull/1343

**Pull request merged**
