### PR TITLE
Js responsive value is not changed on resize

### PR DESCRIPTION
**Pull request by iqit-commerce**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | To corectly calculate prestashop.responsive.mobile value it is needed to base on actual window width. Previosly it was base on _cw value which stored window with value calculated before window resize.
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | /no
| Fixed ticket? | 
| How to test?  | Resize window and print prestashop.responsive.mobile

### CODE REVIEW

**Comment by iqit-commerce** [comment]
I'm sorry but i do not see why commit name is wrong

**Comment by Korri** [comment]
You should probably just replace _cw by _w in the first check, that would be much shorter, but nice fix!

**Comment by vincentbz** [comment]
Seen with Nico, thanks for your PR @iqit-commerce !

**Comment by maximebiloe** [comment]
Thank you @iqit-commerce

**Pull request merged**
