### PR TITLE
Fix ps_viewedproduct in classic theme

### PR DESCRIPTION
**Pull request by SharakPL**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | https://github.com/PrestaShop/ps_viewedproduct/pull/7 changed module's template file location from `/views/template` to `/views/templates`, but in classic theme it's still `/views/template` so theme's file had no effect since ps_viewedproduct v1.1.0
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Change content of `/themes/classic/modules/ps_viewedproduct/views/template/hook/ps_viewedproduct.tpl` to see no effect, because `/modules/ps_viewedproduct/views/templates/hook/ps_viewedproduct.tpl` is used instead.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12227)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Nice catch @SharakPL

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @SharakPL

**Comment by SharakPL** [comment]
@PierreRambaud @Quetzacoalt91 How come this is still not fixed in 1.7.5.1?

**Comment by kpodemski** [comment]
@PierreRambaud @Quetzacoalt91 ping, this is ready to merge, approved etc...

**Comment by PierreRambaud** [comment]
@SharakPL It's not a regression from the 1.7.4 (as I know), this is why we consider this as a bug and will be included in the 1.7.6.

@kpodemski This PR has already been merged :thinking:

**Pull request merged**
