### PR TITLE
Remove already migrated code in AdminModulesPositionsController

### LINKED ISSUE #28074: BO>Positions: you can not transplant a module neither edit a hook
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Testing the `develop` branch and the new hummingbird theme, in the BO I went to Design -> Positions and clicked on "Transplant a module" button. 
image

And this bug appeared :
image

And when you try to edit a hook
https://user-images.githubusercontent.com/100699445/161978454-98c585c3-1e72-4c8c-93f2-ceeb3346c134.mp4

I searched for related issues to form.tpl missing and I found this one #27543. I think they are related.

### Expected behavior

I should be able to transplant a module

### Steps to reproduce

1. Go to Design -> Positions
2. Click on "Transplant a module" button
3. See the bug appears

Another scenario
1. Go to BO
2. Go to Design > Position
3. Click on the Edit button near a module
4. The Exception appear 

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR restores a template that was incorrectly judged as no longer necessary in #27925. While analyzing the problem, I realized that although the Module Positions page has been migrated to Symfony, the "Transplant a module" feature is still handled by the legacy controller, which requires this template. On another note, since the listing part in the legacy controller is unreachable code (as it's handled by the Symfony controller), I took the liberty of removing it in order to avoid having to reintroduce the other template I had deleted in my previous PR, which to the best of my knowledge remains useless. I also removed the invalid deprecation notices in the controller and the restored template.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #28074
| How to test?      | The "transplant a module" feature works again. No other feature within the Module Positions should be broken.
| Possible impacts? | ~

## Breaking Changes

Removed methods:
- AdminModulePositionsController::initMain()

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28086)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@eternoendless I sent your PR in QA. Good job & Good fix. 

Could you create an issue for not forgetting the Symfony migration of this endpoint ? Thanks for advance

**Comment by sLorenzini** [comment]
Hello, 
The issue fixed by this PR is blocking https://github.com/PrestaShop/ps_emailalerts/pull/110, could you please remove the "blocked" label when this PR is merged? Thanks!

**Comment by matks** [comment]
> Hello, The issue fixed by this PR is blocking [PrestaShop/ps_emailalerts#110](https://github.com/PrestaShop/ps_emailalerts/pull/110), could you please remove the "blocked" label when this PR is merged? Thanks!

Got it 😉

**Review by florine2623 — APPROVED** [review]
Hello @eternoendless ,

Thanks for the PR !

Tested initial case. The page works as before.
Successfully transplanted modules to hooks, message after successful transplant is displayed.
Transplanted multiple modules, native modules, external modules to different hooks (positionable & non-positionable).
No exception is displayed, no error is console.
BO > Design > Positions page works as before too. No error displayed or in console.

It is QA ✅ !

**Comment by Progi1984** [comment]
Thanks @eternoendless & @florine2623

**Pull request merged**
