### PR TITLE
1.7.7.2

### LINKED ISSUE #23199: schema.org error in products out of stock when stock management is disabled
#### Describe the bug

schema.org error in products out of stock when stock management is disabled.

When you deactivate the stock management and a product is in negative stock, instead of showing this
```
itemprop="offers" itemscope itemtype="https://schema.org/Offer">
<link itemprop="availability" href="https://schema.org/InStock" />
```

this other wrong code is shown
```
itemprop="offers" itemscope itemtype="https://schema.org/Offer">
<link itemprop="availability" href="https://schema.org/PreOrder" />
```

#### Expected behavior

I think the product should be shown in stock

#### Steps to Reproduce

1. Go to disable stock management
2. Increase stock on a product
3. See good on source code

4. Reduce the stock of the same product to 0
5. See error on source code

**Screenshots**

https://youtu.be/ogvmNO3m7SY

#### Additional information

* PrestaShop version: 1.7.6.4, 1.7.7.1, develop (1.7.8.0)
* PHP version: 7.2, 7.3

### PR DESCRIPTION
**Pull request by alfonsolr09**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  1.7.7.2
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/23199
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes ~#23199~ 
| How to test?      | Go to disable stock management, Reduce the stock of a product to 0, See good
| Possible impacts? | I think no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23247)

### CODE REVIEW

**Comment by alfonsolr09** [comment]
I think I didn't create the pr well, I don't know how to do it ...

**Comment by alfonsolr09** [comment]
https://github.com/alfonsolr09/PrestaShop/pull/1/commits/dd58474ad092d42c49549c54e193e1adb4180802 
THIS IS THE PR

**Comment by matks** [comment]
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request 😉

**Comment by alfonsolr09** [comment]
> https://github.com/alfonsolr09/PrestaShop/pull/1/commits/dd58474ad092d42c49549c54e193e1adb4180802 
> THIS IS THE PR

That is good?

**Comment by matks** [comment]
@alfonsolr09 I'm sorry but no 😅 it's a commit, not a PR. If we click the "merge" button below what will be added to `develop` branch is the full content of your branch, not just this commit.

It's a great opportunity for you to learn it the right way 😉 . Most open source projects use Pull Requests for the contribution, so it's not a waste of time to learn how to make a Pull Request with the right content.

If you google "tutorial make pull request github" you'll find plenty of tutorials, read them, practice a bit (maybe on your own repository) then reopen a Pull Request with _just the changes you want to commit_ (just these 3 lines, right ? https://github.com/alfonsolr09/PrestaShop/commit/dd58474ad092d42c49549c54e193e1adb4180802). It's not easy, but it's not hard either as a lot of people have successfully learnt to do it. And you will acquire a great skill 🎉 .

**Comment by alfonsolr09** [comment]
> https://github.com/alfonsolr09/PrestaShop/pull/1/commits/dd58474ad092d42c49549c54e193e1adb4180802 
> THIS IS THE PR

Click here

**Comment by matks** [comment]
@alfonsolr09 Please, follow my advice 😉 and read some tutorials https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request then practice.

https://github.com/alfonsolr09/PrestaShop/commit/dd58474ad092d42c49549c54e193e1adb4180802 is not a Pull Request. It's a view of a commit content, shown by GitHub. You cannot send snippets of code like this in the project. You must follow the contribution workflow that everybody follows.

EDIT: oh, did you mean https://github.com/PrestaShop/PrestaShop/issues/23199 instead of https://github.com/alfonsolr09/PrestaShop/commit/dd58474ad092d42c49549c54e193e1adb4180802 ?

**Comment by alfonsolr09** [comment]
I mean #23248 @matks

**Pull request closed without merging**
