### PR TITLE
Do not interfere with PDF files

### LINKED ISSUE #31602: Can't view a file directly in the browser, it is always downloaded
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
today a customer warned me on the fact that the pdf files that he had placed in a server folder, in the webroot of the site, he could not view them from the browser but made them download. Instead in the other site made with wordpress it was possible.
I checked the chrome settings and they are set to view pdf files in the browser.
I also put the pdf file on other sites with other wordpress and grav cms and joomla and from all I can view the pdfs in the browser.
then I put the pdf file on other sites made with prestashop and they all make me download the pdf when I go to type the url to the file in the browser

could be some information in the htaccess files used by prestashop

wordpress
https://www.progetto-group.it/qr/smaltimento/EAD_lampade.pdf

prestashop
https://www.bathman.it/QRCODE/EAD_lampade.pdf

with firefox I can see it on the browser, before it download the file then shows the file to the browser
with chrome it download the file, but just when is used prestashop

bye

### Expected behavior

_No response_

### Steps to reproduce

1. upload a pdf file in the webroot of a site with prestashop
2. set the file's url to chrome's browser

### PrestaShop version(s) where the bug happened

1.7.8.8, 8.01

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | There was a security "thing" that forced PDF file downloads instead of opening it in browser. This could be good for securing public - uploaded PDFs, but not the ones from merchant. I removed adding this rule to the global root `.htaccess` and added it only to `uploads/.htaccess`, where all these uploads go.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See below
| Fixed ticket?     | Fixes #31602
| Related PRs       | 
| Sponsor company   | 

### Research - user untrusted file uploads
- Message attachments (orderd detail and contact page) - PS_UPLOAD_DIR
- Product customizations - PS_UPLOAD_DIR

### How to test
- _Should be probably tested by a developer, @Robin-Fischer-PS what do you think?
- Clone this.
- Regenerate htaccess file by saving any page meta configuration or delete this bit of rules from htaccess.
- Copy any pdf file to root directory of prestashop and try to open it in browser, it will respect settings of your browser and probably display it, instead of forcing download of the file.
- Copy any pdf file to /uploads directory and try to open it in browser. Should be forced downloaded.

### Disclaimer
It behaves in a weird way sometimes. I am using XAMPP on Windows and either Apache or Chrome is caching it.
- I have a `aaa.pdf` in my prestashop root. When I access it in browser, it downloads. 
- Then I delete the rule from `.htaccess`.
- When I access `aaa.pdf` again, it's still downloading instead of displaying.
- When I rename `aaa.pdf` to `bbb.pdf` and access it, it opens in browser.
- BUT, when I access `aaa.pdf` I still get it and it gets downloaded, even though it doesnt exist anymore. :-) 🤷‍♂️

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by MatShir** [comment]
@Hlavtox milestone 8.1 but targeting develop ? 🤔

**Comment by Hlavtox** [comment]
@matthieu-rolland @nicosomb Reapproval pls, I owe you a beer

@MatShir fixed :D

Snímek obrazovky 2023-03-03 153800

**Review by nicosomb — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi ! It can be tested by a dev indeed. Thanks @Hlavtox !

**Review by jolelievre — DISMISSED** [review]
Warning!

This was introduced ON PURPOSE in a security fix https://github.com/PrestaShop/PrestaShop/security/advisories/GHSA-rc8c-v7rq-q392

So until we're sure this doesn't reopen a fixed security breach I prefer to block this. Besides I don't see why it's such a big issue not to be able to open the PDF in the browser, I can understand its "a bit" annoying but in face of security it's completely negligeable

**Comment by Hlavtox** [comment]
@jolelievre OK, then this should be only put to [upload directory .htaccess](https://github.com/Hlavtox/PrestaShop/blob/fix-pdf-htaccess/upload/.htaccess), so we block user uploaded PDFs, but not the ones in other folders. 👍

**Comment by 0x346e3730** [comment]
I don't understand how a server config is related to security, what if someone decides to use nginx or caddy to host PrestaShop ? Does it mean the "security fix" does not work ?

**Comment by matthieu-rolland** [comment]
So if understand well:

1.  The security measure is to set all PDF files as attached files so that they are never opened in the browser, thus avoiding any risk of XSS vulnerability.

2. This is a problem for merchants who want to have their own PDF files opened in the browser directly, not as attachments.

### About PDFs uploaded in the BO:

> today a customer warned me on the fact that the pdf files that he had placed in a server folder, in the webroot of the site, he could not view them from the browser but made them download

If we don't trust a PDF uploaded by a merchant or an employee,  why would we trust a PDF directly put into the server ?
If we consider that an uploaded PDF is not trustworthy because the BO could have been hacked, then the same could be said about the server.

- I think we should trust all PDFs not uploaded by a customer. It's the merchant's responsibility to not use corrupted PDF files.

### About PDFs uploaded by a customer in the FO:

- In all cases, customer-uploaded PDFs shouldn't be opened in the browser, for security reasons.

### Solution proposal:

- find all use cases where a PDF can be uploaded by a customer
- see where those PDFs are stored in those cases, and add the apache rule in the htaccess file at this place.
- the apache rule can be removed in Tools.php

**Comment by Hlavtox** [comment]
### User untrusted file uploads
- Message attachments (orderd detail and contact page) - _PS_UPLOAD_DIR_
- Product customizations - _PS_UPLOAD_DIR_

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by davidglezz** [comment]
> What if someone decides to use nginx or caddy to host PrestaShop ? Does it mean the "security fix" does not work ?

I was wondering the same thing. Does anyone know the answer?

**Comment by matthieu-rolland** [comment]
> > What if someone decides to use nginx or caddy to host PrestaShop ? Does it mean the "security fix" does not work ?
> 
> I was wondering the same thing. Does anyone know the answer?

Oh I missed this question:

Well by default PrestaShop provides htaccess configurations, for Apache. If one chooses not to use Apache but instead Nginx or Caddy, then he has to replicate those configurations himself.

Our documentation provides a configuration example for Nginx: https://devdocs.prestashop-project.org/8/basics/installation/nginx/

you can see in the example that the `upload` folder is dealt with in this file, when this PR is merged we should update this documentation

**Comment by Hlavtox** [comment]
@hibatallahAouadni There is nothing to consult here, you can test it

**Comment by florine2623** [comment]
I add the label Waiting for dev to follow this message https://github.com/PrestaShop/PrestaShop/pull/31637#issuecomment-1455814787

**Comment by tleon** [comment]
Hello I tested this as of today. It's all good for me. I indeed encountered the same behavior in chrome as described but changing the name of the file did the tick. 

It's a go for me.

**Comment by Hlavtox** [comment]
Thank you Thomas!!! :-)

@kpodemski We can merge

**Pull request merged**
