### PR TITLE
Move namespace from Core/Domain/Product/AttributeGroup to Core/Domain/AttributeGroup

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Move most of the classes from Core/Domain/Product/AttributeGroup to Core/Domain/AttributeGroup as they make more sense there
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test attribute group related things (Product page - combination generatioon, attribute list). This PR doesn't affect how something works but theoreticly it could have broken something. (But chances are slim since all tests are green https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4545274908)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]

**Comment by lartist** [comment]
1) Are the namespaces you moved under experimental status? Otherwise it's a BC break
2) Did you leave 4 types in the description on purpose ?

**Comment by JevgenijVisockij** [comment]
> 1. Are the namespaces you moved under experimental status? Otherwise it's a BC break
> 
>     2. Did you leave 4 types in the description on purpose ?

They are part of product page, I think it still count's as experimental.

Yeah 4 types was a typo, fixed.

**Review by zuk3975 — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Comment by jolelievre** [comment]
Running auto campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4545274908 if all is green this should be mergeable

**Review by zuk3975 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @JevgenijVisockij

**Review by florine2623 — APPROVED** [review]
Hello @JevgenijVisockij ,

Checked the following :

- Combination generation
- Generation of new combinations with new attributes
- Deletion of existing combinations while product already in cart
- Deletion of attributes in attributes pages and checked impact in PPV2 and FO 
- Edited product type from Standard to Combination
- Checked filter in combination page
- Bulk action/deletion

It is QA ✅ 
Thanks!

**Pull request merged**
