### PR TITLE
Update guzzle and smarty dependencies

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Update guzzle and smarty dependencies
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Comment by kpodemski** [comment]
@jolelievre 

Hi Jo! Make sure to add a `Needs documentation` if there is an update of the minor version 👍 

Second thing. We're going back and forth with this:

`"plugin-api-version": "2.2.0"`

What's the version we should have, exactly?

**Review by zuk3975 — APPROVED** [review]

**Review by matks — APPROVED** [review]
I approve but I agree with @kpodemski : we need to decide what to do with `plugin-api-version`

**Comment by matks** [comment]
@jolelievre 🆙

**Comment by jolelievre** [comment]
HI @kpodemski @matks 

regarding the `plugin-api-version` I think it's just about the composer version used to update dependencies, locally I have 2.2. Of course, I can update my version and update this, but should it be a requirement for all contributors to have the same minor version of composer? Since I don't think it has any influence on the software I'm not sure it's really worth it.

But if we want to force this then we should have a CI to detect and prevent this or we will always have those back and forth if we don't pay attention, and that's not a check that should be handled by humans 🤖

**Review by kpodemski — APPROVED** [review]
Maybe let's not overthink stuff 👍 I have nothing to add if there's no visible impact, no matter which plugin-api-version we use.

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

Hello QA team, I think it might be worth testing this PR with the automated campaign. What do you think?

**Comment by Robin-Fischer-PS** [comment]
Hi @kpodemski @jolelievre :)

It can indeed be tested with the automated campaign only !

**Review by HanaRebaiQA — APPROVED** [review]
Hello @jolelievre 

I just launched the automated tests.
They are OK :heavy_check_mark: 

Thank You!

**Comment by kpodemski** [comment]
Thanks @jolelievre @HanaRebaiQA

**Comment by thomasnares** [comment]
You can remove tag "need documentation" @kpodemski

**Comment by thomasnares** [comment]
🆙 Tag : needs-documentation is ready to remove, documented in https://github.com/PrestaShop/docs/pull/1554

**Pull request merged**
