### PR TITLE
[*] BO : fix execution time in cart rule controller when shop has too many cart rules

### PR DESCRIPTION
**Pull request by baiiko**
If two manu cart rules on BO, we have a max execution time.

Thanks

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for reporting, 

Is this solving your problem : https://github.com/PrestaShop/PrestaShop/pull/2598

Best regards.

**Comment by jeromenadaud** [comment]
Hi @GuigZ- any feedback ?

Best regards.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
I'm closing this ticket because it has not received the needed feedback, and because the issue seems solved by another PR.
If the issue is still there, please open a new ticket on the `1.6.1.x` branch, NOT on the `1.6` branch. Thank you!

**Pull request closed without merging**
