### PR TITLE
Merge 8.1.x into develop

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto tests 🟢 https://github.com/lartist/ga.tests.ui.pr/actions/runs/4809355093
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
Autom tests are red at several places, the PR can't be merged right now

**Comment by lartist** [comment]
> Autom tests are red at several places, the PR can't be merged right now

Yes we're just waiting for this fix merged https://github.com/PrestaShop/PrestaShop/pull/32339
The PR can anyway be review and eventually approved :)

**Review by zuk3975 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by nesrineabdmouleh** [comment]
Hello @lartist,

UI tests are :green_circle: 
The 2 errors in BO_header & BO_design are related to these 2 issues https://github.com/PrestaShop/PrestaShop/issues/32178 https://github.com/PrestaShop/PrestaShop/issues/32180 

Thank you all :)

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @lartist

**Pull request merged**
