### PR TITLE
Add the spam protection option in the preference page

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | We add the spam protection option in the preference page, if the option is activated then the spam protection solution proposed in this PR (https://github.com/PrestaShop/PrestaShop/pull/8168) will be applied
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9466
| How to test?  | 

general prestashop 1 6

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8420)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8420#-:-KyLj1w0U-25AVc6J9X1:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by matks** [comment]
@marionf if this issue is still happening in 1.7, we should be able to fix it thanks to this PR

Issue is: spam protection is mandatory, this PR allows merchant to choose to disable it

**Comment by marionf** [comment]
I think this PR is not necessary with what has already been done about spamming problems:
http://build.prestashop.com/news/fighting-against-spamming/
http://build.prestashop.com/news/fighting-against-spamming-again/

**Comment by matks** [comment]
Then we can close it.

**Pull request closed without merging**
