### PR TITLE
Add missing deprecation on previous PerformanceFormHandler

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add missing deprecation on previous PerformanceFormHandler.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No need for QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12968)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by mickaelandrieu — DISMISSED** [review]
```diff
- to be removed in 1.8
+ to be removed in the next major
```
According to @eternoendless previous reviews :)

Sorry :/

**Comment by matks** [comment]
> ```diff
> - to be removed in 1.8
> + to be removed in the next major
> ```
> 
> According to @eternoendless previous reviews :)
> 
> Sorry :/

You could have used github sugggestions system so I could just click on "approve suggestion" and go ... 😢 
I thought you were a friend 💔

**Comment by sarjon** [comment]
@matks are you sure this class should be deprecated and  not removed?
It extends `AbstractFormHandler` which does not exist and it uses hook dispatcher that is not even injected. This class is more dead than alive.

**Comment by matks** [comment]
> @matks are you sure this class should be deprecated and not removed?
> It extends `AbstractFormHandler` which does not exist and it uses hook dispatcher that is not even injected. This class is more dead than alive.

That's a valid point 🤔 should we follow SemVer for broken code ?
I think not, but I prefer to ask for advice @mickaelandrieu @eternoendless

**Comment by PierreRambaud** [comment]
@matks still needed?

**Comment by matks** [comment]
@PierreRambaud I'm hesitating. This is a class not used anymore, replace by another. So we are in a "deprecation" usecase. However, as sarjon indicated, the class actually is broken 😅 so is it useful to keep a broken class ? Maybe I can delete it, although it's against SemVer ...

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Closing and re-opening to reset Travis

**Comment by matks** [comment]
Travis is trolling me so I close this PR and re-create one https://github.com/PrestaShop/PrestaShop/pull/17204

**Pull request closed without merging**
