### PR TITLE
[-] BO: AdminImportController / Use $vars

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by gRoussac** [comment]
:+1:

**Comment by sfroment42** [comment]
:+1:

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, why do not also take out from for loop in attributeImport function, Tools::getValue('convert') and Shop::getContextListShopID(), etc... The same can be done in others functions.

What do you think about this ?

Best regards.

**Comment by PrestaEdit** [comment]
Hi @jeromenadaud ,

:+1:  ; it's done ! ;-)

**Comment by jeromenadaud** [comment]
Hi, 

Thank you for your contribution.

Best regards.

**Pull request merged**
