### PR TITLE
[*] Better rendering of data

### PR DESCRIPTION
**Pull request by Eolia**
Avoid unformated text and slashes on customized data on orders

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/5051)

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

I'm not sure this is a best place to do that. Shouldn't it be inside the template ? (at least `nl2br`, I'm surprised data are saved with backslashes)

**Comment by kpodemski** [comment]
For sure this code is for theme not for model

**Comment by Eolia** [comment]
OK...
This is the third customer that has the problem.
The object model adds backslashes
This function is only used for display but, if you prefer to edit tpls, must edit those admin (order), those in the front (customer account) and those invoices, cool ...

Now do what you want ^^

**Comment by kpodemski** [comment]
Are you sure that this is not because of for example magic_quotes enabled? I've never face this problem

**Comment by kpodemski** [comment]
I just test it and didn't have any issues:
image

**Comment by Eolia** [comment]
Hum... do you have simpel quotes in your language ? In french, a lot !

**Comment by kpodemski** [comment]
@Eolia see screenshots

**Comment by Eolia** [comment]
` $query = 'INSERT INTO `'._DB_PREFIX_.'customized_data` (`id_customization`, `type`, `index`, `value`)
			VALUES ('.(int)$id_customization.', '.(int)$type.', '.(int)$index.', \''.pSQL($field).'\')';`

`function pSQL($string, $htmlOK = false)
{
    return Db::getInstance()->escape($string, $htmlOK);
}`
`    public function escape($string, $html_ok = false, $bq_sql = false)
    {
        if (_PS_MAGIC_QUOTES_GPC_) {
            $string = stripslashes($string);
        }

        if (!is_numeric($string)) {
            $string = $this->_escape($string);

            if (!$html_ok) {
                $string = strip_tags(Tools::nl2br($string));
            }

            if ($bq_sql === true) {
                $string = str_replace('`', '\`', $string);
            }
        }

        return $string;
    }`

So, if $htmlOK == 1 $string = $string QED

**Comment by mickaelandrieu** [comment]
Hello,

I agree with the previous comments, this shouldn't be done here.

As you're not willing to change your contribution, I'm gonna close it.

Thanks for your understanding.

**Comment by Eolia** [comment]
Pas prêt ???
Depuis 2 ans que ce bug existe, vous vous réveillez que maintenant ? Qui est-ce qui n'est pas prêt ?

C'est exactement à cause de ce genre de traitement que j'ai cessé mes contributions ici.

**Comment by kpodemski** [comment]
@Eolia your fix is just bad, that's it, you were not willing to continue to work on that, even 2 years ago, don't be an ass now

**Comment by mickaelandrieu** [comment]
> Now do what you want ^^

We already asked you a change 2 years ago, I think 2 years is enough to figure out *you* don't want to do it.

Pull requests in `waiting for author feedback` state are closed after a period of inactivity. Still, if you're willing to make a new contribution with this change, I'll be fast to review it: your choice.

**Pull request closed without merging**
