### PR TITLE
Fix duplicate product list

### PR DESCRIPTION
**Pull request by Thorfy**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | duplicate product in product list.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | go in BO product list, add pack or product with combination, save, and duplicate product appear

fix for:
 - 1.6.1.5
 - 1.6.1.6
 - 1.6.1.7
 - 1.6.1.9
 - 1.6.1.10

### CODE REVIEW

**Comment by Thorfy** [comment]
https://github.com/PrestaShop/PrestaShop/commit/1b5bf2d54c53bd0aa9f894a94802cc7f9bdfc827

**Comment by xBorderie** [comment]
@Thorfy Are you saying that #6643 already solves the issue? If so, could close your PR so as to not have a duplicate? Thank you!

**Comment by Thorfy** [comment]
the ticket #6643 does solve the error in part, This solve it more complete

**Comment by vincentbz** [comment]
Hi @Thorfy 

I can't reproduce your bug. I don't have any duplicate product that appear when I save it, even with combinations, pack or downloadable.

**Comment by aleeks** [comment]
Hi,
I'm closing this issue, but no problem to re-open if we found a solution.

**Pull request closed without merging**
