### PR TITLE
Display active zones first in Carrier wizard and flag inactive ones

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Display active zones first in Carrier wizard and flag inactive ones |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | disable a zone and check if is not visible in Carrier wizard |

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks for this PR! I wonder why it was `false` in the first place...

**Comment by maximebiloe** [comment]
Hello,

I think the `false` was wanted. You may want to configure your carrier before activate the zone. Otherwise, you'll have a zone active in front office without any carrier available.

What do you think?

**Comment by martinfojtik** [comment]
Hi,

@maximebiloe its true, but i think in majority of time users just changing price to zones which are permanently activated and displaying full list of zones can be confusing. I thing there are two solutions :
- permanently hide deactivated zones (like i did in this PR)
- or add expand/collapse button under the list to show disabled zones

What do you think?

Sorry for my English.

**Comment by maximebiloe** [comment]
Hi,

No problem for your english, I understand 😉 

I see your point but we have two use cases here: the one you describe and and the one I describe. We need to take both into account.

So, I saw with our UX designer and she offers to add a little mention "active" or "inactive" next to the zone name. Something like "Europe _(active)_".
Would it be okay for you? Is yes, would mind edit your PR to do that?

Thank you

**Comment by martinfojtik** [comment]
yes, of course.. now it look like:
prestahop-zone-range

is that better?

**Comment by maximebiloe** [comment]
Nice! Look great to me 😉 

Unfortunately, yesterday we've merged a little glitch which broke the tests. Would mind rebasing your PR against develop to get the fix and push again, please? It will relaunch the tests and I'm pretty sure it will be green. So I'll merge this.

Thank you @martinfojtik!

**Comment by martinfojtik** [comment]
@maximebiloe now it's green

**Comment by maximebiloe** [comment]
Thank you @martinfojtik!

**Pull request merged**
