### PR TITLE
Replace parameters.yml with parameters.php

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Replace parameters.yml with parameters.php |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Run web installation or CLI installation after installing vendors with composer. The content of the `parameters.yml` file should be moved to `parameters.php` after converting it into a PHP array. |

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Care about extra space after "improvement", @prestonBot is evil :dancer:

**Comment by matks** [comment]
Hi @thierrymarianne I know it's a been a very long time but by any chance do you remember if you did not _delete_ the parameters.yml file on purpose, and rather _emptied_ it ? 😄

**Comment by thierrymarianne** [comment]
Hi @matks, I really could not tell what this was all about. 
I'm sorry for the lack of context :sweat: 

The only reason I can think of (which is a bit far-fetched) would be not to leave sensitive information in a yml format hanging around in case of a failure affecting the replacement of a `parameters.yml` file with a `parameters.php` config file :shrug: 

If a `public` directory were to be exposed by a web server, this would not be a problem but the contents of `app/config` might be exposed depending on a server (mis-)configuration and how all the files in the root directory are served.

**Comment by matks** [comment]
@thierrymarianne thank you so much for answering even though the PR is so old 👍

**Pull request merged**
