### PR TITLE
Fix shipping method change on checkout page

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The event parameter wasn't defined on the event listener
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1857
| How to test?  | Go on the checkout page (with firefox) and try to change the shipping method. The price should update.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
I feel like a "Deja vu" :/

**Review by mickaelandrieu — APPROVED** [review]

**Comment by antoin-m** [comment]
Yeah that's what I was thinking right now... :disappointed:

**Comment by Quetzacoalt91** [comment]
Yep, that's right. See #6980

**Comment by antoin-m** [comment]
Ah! Thank you @Quetzacoalt91 :)
I'll close this one.

**Pull request closed without merging**
