### PR TITLE
BO / Cart rule / Improve product selection

### LINKED ISSUE #23526: BO / Cart rule / Improve product selection
#### Is your feature request related to a problem?

On a large catalog, product and category selection is messy on cart rule condition tab :
- Fancy box is too small
- If an item is too long to fit in the select, there is no way to see the end : no horizontal scrollbar

Capture d’écran 2021-03-04 à 16 59 40

#### Describe the solution you'd like

Use overflow:auto on select[multiple]

image

image

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | On a large catalog, improve product and category selection cart rule condition tab : Larger fancy box and horizontal scrollbar
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/23526
| How to test?      | Add a product and category selection on a cart rule.
| Possible impacts? | overflow:auto on select[multiple] should be ok but it has to be tested on other controllers

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23527)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
LGTM, do we've some others select[multiple] in the BO ? Did you check the behavior ?

**Review by kpodemski — DISMISSED** [review]

**Comment by jf-viguier** [comment]
@NeOMakinG in tag management I guess

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I have an issue if the category name has more than 77 characters for example

1. Create a category with this name: `this is a test example for the pr in the branch develop to fix cart rule issue tested by me`
2. Go to BO > Catalog > Discounts > Create a cart rule
3. In the Conditions Tab > Select Product selection > Choose a category
4. If the modal is opened => OK 
image
5. If you click to scroll to see all the text => NOK 
image
6. If you click outside => OK

Thank you!

**Comment by jf-viguier** [comment]
@khouloudbelguith I don't have this, it's a browser issue I guess.
What browser/os have you ?

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

I used Google Chrome version 87.0.4280.141 (Build officiel) (64 bits).

Thank you!

**Comment by jf-viguier** [comment]
@khouloudbelguith I've the bug when the line is selected, is it the same for you ?

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier,

>@khouloudbelguith I've the bug when the line is selected, is it the same for you?

Yes, I have the issue when the category is displayed in the `Unselected` & `Selected` list and it is selected.
As described in my previous screenshot.

Thank you!

**Comment by jf-viguier** [comment]
@khouloudbelguith the issue is also there without my PR. It's a browser issue I guess so please remove  Waiting for author and Waiting for dev. 
@NeOMakinG any idea on how to fix this ?

**Comment by khouloudbelguith** [comment]
@jf-viguier, thanks for your feedback.
I manage to reproduce the issue without PR also.
https://drive.google.com/file/d/1hLbAB3A1pz4j-rrCXJGNpo9JHPiHEcla/view?usp=sharing

Thank you!

**Comment by NeOMakinG** [comment]
@jf-viguier it was because option width was the initial width of the select (without the scroll width), using width: max-content is fixing this as the width is now the natural width of the option!

**Comment by khouloudbelguith** [comment]
Hi @jf-viguier, @NeOMakinG,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1wDWJuBt2ne23px9c1NfYxJpFiD-mebyS/view?usp=sharing

Thank you!

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by jf-viguier** [comment]
Thanks @NeOMakinG

**Comment by Progi1984** [comment]
Restarted all Github Actions :) And Thanks @jf-viguier & @NeOMakinG & @khouloudbelguith

**Pull request merged**
