### PR TITLE
Functional Tests : WS - Orders : CRUD

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Functional Tests : WS - Orders : CRUD
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle:
| UI Tests          | https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/6879461828
| Fixed issue or discussion?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## Linked Issues
* https://github.com/PrestaShop/PrestaShop/issues/34564
* https://github.com/PrestaShop/PrestaShop/issues/34576

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
I reran failed jobs, I'm not sure it's related to your PR...

**Review by boubkerbribri — DISMISSED** [review]

**Comment by boubkerbribri** [comment]
@Progi1984 please resolve conflict

**Comment by Progi1984** [comment]
@boubkerbribri @nesrineabdmouleh  Rebase done

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by boubkerbribri** [comment]
THanks @Progi1984

**Pull request merged**
