### PR TITLE
Added "ean13_product" query param to dispatcher

### PR DESCRIPTION
**Pull request by tomloprod**
In this way, we could access the URL of a product of which we only know the code `EAN-13`.

**Example:**

    /index.php?controller=product&ean13_product=0000000000000

### CODE REVIEW

**Comment by xBorderie** [comment]
Hey @tomloprod , need help making your PR happen?

**Comment by tomloprod** [comment]
Hi @xBorderie I'm not sure this PR can be useful :-)

What do you think?

**Comment by xBorderie** [comment]
Indeed, this could be interesting for professionals!

Could you make another PR with a single commit, following our [naming guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

Thank you!

**Comment by tomloprod** [comment]
Of course :-) I will make a PR.

Regards!

**Pull request closed without merging**
