### PR TITLE
Create, edit and delete Linkwidget

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Create, edit and delete a different LinkWidget HOOK
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | TEST_PATH=full/15_design/3_link_widget npm run specific-test -- --URL=FrontOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9275)

### CODE REVIEW

**Comment by kpodemski** [comment]
I wonder if we should have e2e tests for native modules inside core repo, shouldn't be this available directly from module repo? cc @mickaelandrieu @Quetzacoalt91 @eternoendless

**Comment by PierreRambaud** [comment]
@kpodemski Totally agreed, we are trying to find a way to add functional, unit and e2e tests directly in modules.

**Comment by eternoendless** [comment]
> shouldn't be this available directly from module repo?

@kpodemski It makes absolute sense to me! But I don't think it will be easy.
cc @mbadrani

**Comment by PierreRambaud** [comment]
As @toutantic said, we need to focus and show to everyone how they can implement and execute E2E tests. Maybe use a generic npm dependencies (created by us) to install, configure and run a prestashop instance as we do in `test/E2E` and use `path` env vars to select module. (THis one will be changed to `TEST_PATH` in the future due to errors why zsh)

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by fatmaBouchekoua** [comment]
@mbadrani this PR is ready to be merged

**Comment by mbadrani** [comment]
@fatmaBouchekoua some conflicts here

**Comment by mbadrani** [comment]
@fatmaBouchekoua there are some conflicts here

**Comment by fouratachour** [comment]
@mbadrani @fatmaBouchekoua : conflicts resolved !

**Review by fatmaBouchekoua — APPROVED** [review]

**Pull request merged**
