### PR TITLE
[-] Class: DbQuery / Add rightJoin() method

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by jocel1** [comment]
Why not just adding rightJoin since rightOuterJoin is the same operation ?

**Comment by PrestaEdit** [comment]
:+1:

**Comment by Shudrum** [comment]
Hi !

Thank you for your contribution.

Best regards.

**Comment by Shudrum** [comment]
Hi again !

I've merged your PR but this is an enhancement, all enhancement should be pulled on the 1.6 branch from now. An article is coming soon about that !

Thank you again.

**Pull request merged**
