### PR TITLE
Use default catalog as a fallback

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | Do not set a fallbackCatalog, use the original strings
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1750

### CODE REVIEW

**Comment by maximebiloe** [comment]
See https://github.com/PrestaShop/PrestaShop/pull/6912

**Comment by aleeks** [comment]
Could you rebase please @maximebiloe

**Comment by maximebiloe** [comment]
@aleeks done 😉

**Comment by aleeks** [comment]
Thank you @maximebiloe

**Pull request merged**
