### PR TITLE
[+] FO : Add display after carrier list hook

### PR DESCRIPTION
**Pull request by firstred**
## Description

Add a hook to display information after the carrier list
## Steps to Test this Fix

Step 1. Create a new module
Step 2. Hook some HTML to `displayAfterCarrier`
Step 3. Check if output is shown

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Hi,

I think you forgot to commit somes changes (like pass the var to smarty) or maybe you want to use the {hook h='displayAfterCarrier'} method inside the template. No ?!

**Comment by firstred** [comment]
Yep! It's just there to be displayed, just like the `displayBeforeCarrier` hook.

**Comment by PrestaEdit** [comment]
Right, but $hookDisplayAfterCarrier is never declared/assigned. I really think you wanna write something like: {hook h='displayAfterCarrier' nofilter}

**Comment by firstred** [comment]
Indeed! Thank you for the information.

I have now added it to `$extraParams` and pass the `Cart` object, just like `hookDisplayBeforeCarrier`.

**Comment by PrestaEdit** [comment]
Right ! It's now more better, ;-)

**Comment by maximebiloe** [comment]
Thanks.

Could you report this change into the [StarterTheme](https://github.com/PrestaShop/StarterTheme), please?

**Pull request merged**
