### PR TITLE
[WIP] Prepare the svg integration with Imagick

### PR DESCRIPTION
**Pull request by wdammak**
Prepare the svg integration with Imagick 
- isImagick:  Get if the imagick library is installed
- resizeWithImagick: Resize, cut and optimize image with Imagick.

Issue: [https://github.com/PrestaShop/PrestaShop/issues/10600](https://github.com/PrestaShop/PrestaShop/issues/10600)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15631)

### CODE REVIEW

**Comment by matks** [comment]
Hi @wdammak this looks like an in-progress work ? Or is something you need to be merged in the core to enable a module / an extension on your shop ?

**Comment by wdammak** [comment]
Hi @matks my reflection that I had is since all the images of ps are managed in this class is that we can integrate imagick and manage in each function the existence of lib. if it exists, deal with imagick otherwise use GD to keep the compatibility ...
For now we could duplicate the .svg file in the usual folders even if I think we can do better...
It's a PR to get in the bath :)

**Comment by matks** [comment]
Hello @wdammak it looks like you could not finish this PR, you probably had other topics you had to focus on. Should I close it?

**Comment by matks** [comment]
This PR is stale since 2019.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen.

Thank you for your contribution.

**Pull request closed without merging**
