### PR TITLE
CO: New methods for handling token for guest users to prevent CSRF

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Currently getToken doesn't allow to prevent CSRF for actions related to guest users |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | n/a |
| How to test? | n/a |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/5863)

### CODE REVIEW

**Comment by julienbourdeau** [comment]
It looks like you're introducing 2 new methods but you don't use them. Did I miss something?

**Comment by kpodemski** [comment]
This is extended API for module developers, that's it, currently there's no way to use getToken in modules for guest users and if we for example wants to create module which is for guest users.

**Comment by kpodemski** [comment]
@xBorderie @Shudrum 1.6.1.7 milestone? Please :santa:

**Comment by mickaelandrieu** [comment]
Hello @kpodemski,

it's a new feature, and we will only merge bug fixes into `1.6.1.x` branch until end of maintenance period.
I have the feeling you've done the same pull request for `1.7.x` branch, let's discuss what can be added in 1.7.x then :+1: 

Thanks for your understanding.

**Pull request closed without merging**
