### PR TITLE
Improve buttons in customer detail

### LINKED ISSUE #25092: Provide new voucher buttons to customer page
#### What can we do
We can provide additional links for merchants to create voucher from customer detail page, and speed up their work a bit.
The plus icon is already used on address section on the page.

We can link to the page normally for the beginning, and possibly improve it in the future by preselecting the customer on voucher screen.

#### If the customer does not have any vouchers
vouchers

#### If customer already has some vouchers
vouchers_some

### LINKED ISSUE #25093: Provide new order buttons to customer page
#### What can we do
We can provide additional links for merchants to create manual order from customer detail page, and speed up their work a bit.
The plus icon is already used on address section on the page.

We can link to the page normally for the beginning, and possibly improve it in the future by preselecting the customer on order screen.

#### If the customer does not have any orders
orders_empty

#### If customer already has some orders
orders_some

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I added buttons to corners of order and discount block, so you can easily add them faster. I added buttons to the content of blocks, if there are no data yet.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check detail of customer and see that you can do things faster. :-)
| Fixed ticket?     | Fixes #25093, Fixes #25092
| Related PRs       | 
| Sponsor company   | 

### Screenshot
customerzone

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by kpodemski** [comment]
@nicosomb two approvals -> waiting for QA label :)

**Comment by nicosomb** [comment]
@kpodemski sorry fo forgetting it 🙂

**Review by djoelleuch — COMMENTED** [review]
Hello @Hlavtox ,
I have checked this PR , it LGTM .
The issue is well fixed .
image

But the automated tests are Failed :x: 
https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4053059184
Ping @PrestaShop/qa-automation could you check it please ?
Thanks.

**Comment by Hlavtox** [comment]
@djoelleuch Failed test is not related, it could not be the cause. It's the same fail as in https://github.com/PrestaShop/PrestaShop/pull/31104. 👍 Can we merge? 🙏

**Comment by nesrineabdmouleh** [comment]
Hello @djoelleuch,

Thank you for your ping ! 
The failed test is not related to the PR, you can approve :heavy_check_mark:

**Comment by Hlavtox** [comment]
Thank you!

**Pull request merged**
