### PR TITLE
Add missing license headers

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Added missing license headers
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | Nothing to test
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23722)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by Progi1984** [comment]
@eternoendless You have a PHPCSFixer error.

**Comment by matks** [comment]
PHP CS Fixer fails because of one empty line

UI tests because of random network issue
```
* Installing PrestaShop, this may take a while ...
file_get_contents_curl failed to download https://i18n.prestashop.com/translations/1.7.7.3/en-US/en-US.zip : (error code 28) Connection timed out after 5001 millisecondsInstalled failed, displaying errors from logs:
```

Also these are not necessary for 1.7.7.3 as `tests/` folder is removed in the ZIP so no need to be fast

**Comment by eternoendless** [comment]
Should be ok now

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @eternoendless

**Pull request merged**
