### PR TITLE
Removes unnecessary return on update everywhere

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Continue on the PR https://github.com/PrestaShop/PrestaShop/pull/12941 this PR will remove the usage of ids everywhere
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | I'll list down all the controller actions which were affected after this change :arrow_double_down: . Please check that all EDIT forms for these pages (like "edit a customer", "edit an employee") are not broken.

- [x] Update docs in https://github.com/PrestaShop/docs/pull/184/files#diff-31267c83d02ffc33f0f5b8d297c58604R346 . Remove id checking and also check if form handler does not return id

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13251)

**List of affected controller edit actions**

admin-dev/index.php/sell/catalog/brands/ both address and manufacturer edit

admin-dev/index.php/sell/catalog/categories both root and regular edit actions

admin-dev/index.php/improve/design/cms-pages/ both category and cms page edit actions

admin-dev/index.php/configure/shop/contacts/

admin-dev/index.php/improve/international/currencies/

admin-dev/index.php/sell/customers/

admin-dev/index.php/improve/international/languages

admin-dev/index.php/configure/shop/seo-urls

admin-dev/index.php/configure/advanced/profiles

admin-dev/index.php/configure/advanced/sql-requests

admin-dev/index.php/improve/international/taxes

admin-dev/index.php/configure/advanced/webservice-keys

### CODE REVIEW

**Comment by tomas862** [comment]
@matks done :)

**Comment by matks** [comment]
> I'll list down all the controller actions which were affected after this change

I guess the commit messages can used as a list 😉 ?

**Comment by tomas862** [comment]
@matks just added the list in the description :)

**Review by matks — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @tomas862

**Comment by matks** [comment]
Thank you @marionf for the huge QA work

**Pull request merged**
