### PR TITLE
Removed useless aliases which cause issue with MariaDB

### LINKED ISSUE #33157: MariaDB Incompatibility
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I am using MariaDB and tried to run the behavioural test suite and get several errors. Around 12 errors are related to a problem with the database and all of the same kind:

````
001 Scenario: one product in cart, quantity 1, can apply only the cart rule which is restricted to selected carrier # Features/Scenario/Cart/CartRule/FrontOffice/carrier.feature:160
      And I save all the restrictions for cart rule cartrule7                                                       # Features/Scenario/Cart/CartRule/FrontOffice/carrier.feature:173
        An exception occurred while executing 'DELETE FROM ps_cart_rule_carrier crc WHERE crc.id_cart_rule = ?' with params [3]:
        
        SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'crc WHERE crc.id_cart_rule = '3'' at line 1 (Doctrine\DBAL\Exception\SyntaxErrorException)
````

The cause is, that MariaDB is not supporting an alias for the `DELETE` statement. Minimal test:

````
MariaDB [test_prestashop]> DELETE FROM ps_prodcut xy WHERE id_product=123123;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'xy WHERE id_product=123123' at line 1
```` 

I can find a few places where the alias feature is used, but these seem not covered by the automated tests.

When I search MariaDB in the issues, 19 issues are shown. From this, I conclude, that MariaDB is used with PrestaShop and thought to be working. Looking through the issues briefly, I haven't found an indication that MariaDB is not to be used.

The CI tests run only with MySQL.

### Expected behavior

I suggest to do the following, instantly:
- update the documentation stating that: "Only MySQL is fully supported and tested. MariaDB users could run into issues and should report a bug"
- Add a field in the bug report with the database type and version

If MariaDB should be supported, it needs to be added to the CI tests in the long run I think.

Since the problem seems minor and I know what to do now, I will stay with MariaDB in our environment and send some patches.

### Steps to reproduce

Run the behavioural tests with MariaDB

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Aliases on table in DELETE queries aren't compatible with MariaDB
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | green tests 
| UI Tests          | https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/8891200020
| Fixed issue or discussion?     | Fixes #33157 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by cdesiles — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Hlavtox** [comment]
@nicosomb Given how simple the PR is, what about 8.1.x?

**Comment by nicosomb** [comment]
@Hlavtox because `src/Adapter/CartRule/Repository/CartRuleRepository.php` doesn't exist in `8.1.x` ? 😉

**Comment by Hlavtox** [comment]
@nicosomb Ahaaaa, that makes sense! :D

**Comment by nicosomb** [comment]
UI tests are green https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/8891200020

**Pull request merged**
