### PR TITLE
CO: Payment method title extended to 255 characters

### PR DESCRIPTION
**Pull request by mauglee**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | master
| Description?  | 32-char length is too short. DB schema describes this attribute as 255 char length. After fix now this is equal - DB and PHP code. It is not acceptable to trim to 32 chars, because this is used in email notifications and invoices. The buyer can't see whole title if it's more than 32 char length. E.g. if payment module name is „Credit card payment on products reception“ the buyer will see only „Credit card payment on products “.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Use payment method with title longer than 32 chars and see buyers email or PDF invoice.

### CODE REVIEW

**Review by stickyrst — APPROVED** [review]
Looks just right

**Comment by maximebiloe** [comment]
Hello @mauglee,

Thanks for your contribution.
The PRs are meant to be done on `develop` branch, so I changed the destination branch. Unfortunately `master` and `develop` have diverged so your PR needs a rebase.
Can you do that, please?

Regards

**Comment by mauglee** [comment]
Could you provide some instructions for that?

**Comment by aleeks** [comment]
Hello @mauglee 
I cherry-picked your commit here: https://github.com/PrestaShop/PrestaShop/pull/7531

Thank you :)

**Pull request closed without merging**
