### PR TITLE
Improve search performance for large shops

### PR DESCRIPTION
**Pull request by Darhazer**
The existing search implementation basically loads all indexed products that are active & visible into memory and then intersects with the ones that match the keyword search. For a large catalog, this means loading thousands of products just to match them with the ones returned by the words index.

This PR adds a filter on the query, based on the products returned from the search_index table, so no products that do not match the search query are loaded in order to build the `$product_pool`.

Basically, the PR attempts the same as #7786 but keeps the changes minimal

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Performance optimization
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | perform a seach in the front-end. Make sure the results are the same as in the original version. Try different combinations of terms, including ones that do not result in an available product. Try searching for inactive products.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16828)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]
Waiting for one more developer before going to QA.

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Darhazer** [comment]
PR rebased to account for #14428

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
Ping @Darhazer can you please resolve the conflicting file ?

**Comment by Darhazer** [comment]
@SD1982 rebased

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @Darhazer

**Pull request merged**
