### PR TITLE
Fix wrong schema of "InStock" for Out of stock products

### PR DESCRIPTION
**Pull request by rdy4ever**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In Classic, there is a wrong schema of "InStock" for all products, regardless if the product is actually out of stock.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5447
| How to test?  | Go to the Google structured data testing tool and try it with both in stock and out of stock products.
--

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9027)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Hi!

Good job! We're waiting for QA review :-)

Mickaël

**Comment by rdy4ever** [comment]
Hi. I did another commit (to comply with Codacy) and somehow dismissed your review. Could you please take another look? Sorry:)

**Comment by mickaelandrieu** [comment]
@rdy4ever thanks!

EDIT: don't worry too much about the commits, I'll squash an clean the history when I'll merge ;)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thank you @rdy4ever!

Edit: ported on StarterTheme => https://github.com/PrestaShop/StarterTheme/pull/228

**Pull request merged**
