### PR TITLE
Remove ecotax field when the product is virtual

### LINKED ISSUE #15038: Ecotax field shouldn't be displayed in BO if the product is virtual
The ecotax is a contribution to finance the collect, the recycling and the depollution of a piece of furniture or used electrical and electronic equipment.
So, the ecotax field shouldn't be displayed in pricing tab of the product page for a virtual product (even if it's enabled in International > Taxes)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove ecotax field when the product is virtual
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #15038
| How to test?      | Cf #15038

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27673)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @Progi1984

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Progi1984 ,

Thanks for the PR !

The ecotax is not displayed on Product (Experimental Page) but not on the original Product Page, as shown on the screen record :

https://user-images.githubusercontent.com/16019289/156581168-526db75b-0631-433d-b34a-7649e79fd0df.mov

In the FO, the ecotax is displayed too :
Screenshot 2022-03-03 at 15 29 33

Can you confirm this is the wanted behavior ?
Thanks!

**Comment by Progi1984** [comment]
@florine2623 I just see in backoffice. I will fix frontoffice. But I won't fix it on the original Product Page as it would be removed for v8 (ping @jolelievre & @MatShir).

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-maintainers Fixed for frontoffice :)

**Review by matthieu-rolland — COMMENTED** [review]
LGTM, but UI tests broken, restarted it

**Review by tegbessou — APPROVED** [review]

**Comment by Progi1984** [comment]
@matthieu-rolland It should be fixed.

**Review by atomiix — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984 

To answer your question no need to fix V1 indeed, but good call on the FO

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Progi1984 and all,

Thanks for the details !

Fixed in Experimental Product page ✅  and not displayed in FO ✅ 

Noted that it won't be fixed in Product Page V1.
But there's an issue with the product final price in BO if I add an ecotax in V1.

In my case :
I add an ecotax in V1, in FO, final price is OK
I check my product sheet on V2 : no ecotax, the prices don't match the FO 🚫 

https://user-images.githubusercontent.com/16019289/157023857-e17c2870-c958-4269-b7c4-b87b8696b406.mov


Could you confirm what should be the specs for this case ?
Thanks!

**Comment by Progi1984** [comment]
@jolelievre Have you got an idea on the problem of @florine2623 ? I have not changed anything on price calculation.

**Comment by jolelievre** [comment]
Hi @florine2623 and @Progi1984 

I think this use case should be ignored for the scope of this PR because:
- first there is a HUGE inconsistency between legacy page which still allows to use ecotax on virtual product and new page which ignores it
- second, the ecotax has been handled in the V2, when the price inputs are modified there is a complex computation to perform between price tax excluded, ecotax and price tax included So it doesn't handle nor adapt to the value specified in DB

Second point will be handled in another PR to fully handle the ecotax in page v2

First point however is more worrying, because even if we use the V2 form the inconsistency remains so I suggest to do this: when product type is switched to virtual product the ecotax value should be forced to 0 to avoid this inconsistency So it must be handled in the CQRS command and behat tested, and this part could be done in this PR

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 @jolelievre ,

As discussed together yesterday, what @jolelievre mentioned will be fixed in another PR.

This PR has been tested on Product Page V2.
Display in BO and FO is removed correctly. Tested on virtual product edition/creation. Modified type of product.
For now, this PR for ecotax is QA ✅ 

Thanks!

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
