### PR TITLE
[-] CORE : Fix Smarty SQL Cache

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Unable to find `SmartyCacheResourceMysql.php` because the file was moved. |
| Type? | bug fix |
| Category? | CORE |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | Dunno |
| How to test? | Enable MYSQL Caching on the page "Advanced Parameters > Performance" |

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Have you actually got an error? Have you tried to remove the whole line ? I mean, how come this wouldn't be autoloaded ?

**Comment by firstred** [comment]
Yes, I have actually got an error. I can aldo see that the database doesn't get filled.

**Comment by julienbourdeau** [comment]
Alright, thank you :)

**Comment by firstred** [comment]
But erm.. it should just be autoloading instead?

**Comment by firstred** [comment]
In that case I'll investigate some more and see if we can get rid of the line.

**Comment by julienbourdeau** [comment]
Thank you very much

**Pull request merged**
