### PR TITLE
Protect templates directory

### LINKED ISSUE #33722: Missing directory protection (from htaccess) for templates directory
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The `/templates` directory is not protected with an `htaccess`

### Expected behavior

The `/templates` directory should be protected with an `htaccess` as all other code directories (eg: `/src`)

### Steps to reproduce

1. Enable listing directories on the server
2. Access to `/templates`

Modules PrestaScan Security is for exemple listing this directory as unprotected:
https://ibb.co/JRSFZKB

### PrestaShop version(s) where the bug happened

Seen in 8.0.5

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Profileo

### PR DESCRIPTION
**Pull request by maxime-morel**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes #33722 by adding an htaccess to protect the `templates` directory
| Type?             | bug fix
| Category?         | FO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | See #33722
| Fixed issue or discussion?     | Fixes #33722
| Related PRs       | 
| Sponsor company   | Profileo

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]
LGTM, thanks @maxime-profileo ;)

**Comment by boherm** [comment]
Maybe a QA by dev for this one?

**Comment by MatShir** [comment]
Same comment [here](https://github.com/PrestaShop/PrestaShop/pull/33700#issuecomment-1693505248) ;)

**Comment by nicosomb** [comment]
@MatShir I will do a backport on 8.1.x

**Comment by nicosomb** [comment]
@MatShir done here https://github.com/PrestaShop/PrestaShop/pull/33788

**Comment by MatShir** [comment]
Thanks 🤗

**Pull request merged**
