### PR TITLE
Display Ecotax select when ecotax is enabled, without saving

### LINKED ISSUE #20600: [BO] [TAXES] Ecotax list doesnt appear after clicking on the buttons ecotax NO/YES
#### Describe the bug

When I go into international>taxes>tax options, I see "Use ecotax" with a "NO" and "YES" button.
If I click on yes while it was on no, the list doesnt popup: I need to click on save button a first time to make it appear.
Moreover, I don't understand why the list give us different rates which doesnt reflect the amount of the ecotax but the VAT?

#### Expected behavior

The ecotax list should appear as soon as I click on the "YES" button without the need to click "save" first. 

#### Steps to Reproduce

1. Go to  international > taxes>tax options
2. Click on "use ecotax" "YES"
3. See the list doesnt come up, you need to click save first.

**Screenshots**

https://drive.google.com/file/d/186w5-AadzJNlraqgfBAgs2EXNVyYsafE/view

#### Additional information

* PrestaShop version: 178
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Display Ecotax select when ecotax is enabled, without saving
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #20600
| How to test?      | Cf. #20600

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27815)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by florine2623 — COMMENTED** [review]
Hello @Progi1984 ,

Thanks for the PR.
LGTM, it is QA ✅ 

https://user-images.githubusercontent.com/16019289/156608948-c63286d1-2eff-4d64-8bad-5bbf7ccbd3cd.mov

Before I put the QA ✅ label, what about this comment : 
>Moreover, I don't understand why the list give us different rates which doesnt reflect the amount of the ecotax but the VAT?

Should the Wording be modified to make it more understandable ? @Julievrz what do you think ?

Thanks!

**Comment by Progi1984** [comment]
@florine2623 @Julievrz I know this tax list must move in the future (#22827)

**Comment by Julievrz** [comment]
> @florine2623 @Julievrz I know this tax list must move in the future (#22827)

Thanks. I suggest we discuss the wording in this issue. :-)

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
@Julievrz @florine2623 If it's just wording, we can create a new issue (not in the scope of the initial PR).

**Comment by Julievrz** [comment]
> #22827

Yes, I commented https://github.com/PrestaShop/PrestaShop/issues/22827

**Review by florine2623 — APPROVED** [review]
Thanks @Julievrz !

@Progi1984 looking good to me ^^ QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623 & @Julievrz

**Pull request merged**
