### PR TITLE
[-] CORE: Add default value for id_order var in contact email

### PR DESCRIPTION
**Pull request by gskema**

### CODE REVIEW

**Comment by xBorderie** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

-xb.

**Comment by xBorderie** [comment]
Hey Gytis! Sorry for the late feedback.
Seems like we already have this information. Is this PR still needed? Are we missing something?
image
Thank you!

**Comment by gskema** [comment]
@xBorderie Hello :D Your screenshot is completely unrelated, did you check the code changes?

**Comment by xBorderie** [comment]
Screenshot was provided to me, I'm merely the messenger :)
Could you give us more details about this?
And in any case, if it's still relevant, could you remake it on 'develop'?

**Comment by gskema** [comment]
I think it still relevant, yes. If you look at Line 180, you can see that `{id_order}` gets added if there is an associated order. The problem is that when there is no associated order, `{id_order}` is not replaced in the email template. This fix passes "empty" value of dash `-` to template.

**Comment by xBorderie** [comment]
Alright, then. Would you feel like remaking it on 'develop'?

**Comment by gskema** [comment]
I'll see what I can do :D

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
