### PR TITLE
bugfix: id_order is not passed to the URL in the order history, cf link in /historique-des-commandes

### PR DESCRIPTION
**Pull request by drzraf**
cf PR #3528

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello,

Does it throw an error ? Because, the order detail is working well on my side.
The id_order is send by Ajax, through JavaScript. So, apparently, there is no need to set it into the URL.

Regards.

**Comment by drzraf** [comment]
I remember that I needed this patch to get the URL parameter.
Either there was a javascript error at that time, or javascript was
disabled, or was coming from a page/hook/translation which didn't
triggered/load the javascript.

I don't know the reason why it didn't work in the first place, but
patching the template worked in my case (I bet it'd also be safer).

**Comment by maximebiloe** [comment]
Yes, if you have a JavaScript error, having the parameter in the URL will still open the page.

Could you, please, modify your commit message to respect [our norm] (http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message) ?

**Comment by drzraf** [comment]
sorry but no, really, I'm sorry, it's too much bureaucracy this time.
I'm volunteering and have already a lot of other things to do and can't
just respect every single normative bit for every project I contribute
freely to / or need to patch.
Feel free to rename/cherry-pick/... it to as you prefer, you're probably
more aware of this than I could be myself.

thank you

**Comment by maximebiloe** [comment]
Ok.
I've just made it in #4414

Regards

**Pull request closed without merging**
