### PR TITLE
Access denied when acess localhost/myshop/admin123/index.php?controller=AdminTabs&toke=xxx with SuperAdmin And AdminTabs Tab don't exists

### LINKED ISSUE #15048: AdminTabs controller can not be accessed - Menu BO Page
**Describe the bug**
`AdminTabs` admin controller doesn't appear in any menu. If you try to access directly by URL it returns an `Acces denied` error.

This functionality is not in any other controller.

**To Reproduce**
1. Open any AdminController
2. Change URL to `controller=AdminTabs`
3. Bypass token warning

**Additional information**
PrestaShop version: 1.7.6.0

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Access denied when acess localhost/myshop/admin123/index.php?controller=AdminTabs&toke=xxx with SuperAdmin And AdminTabs Tab don't exists
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket ?    | Fixes #15048
| How to test ? | 1. Open any AdminController<br>2. Change URL to `controller=AdminTabs`<br>3. Bypass token warning

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17501)

### CODE REVIEW

**Comment by PululuK** [comment]
Hi @HamzaElghanoui 

Thank for you contribution, and welcome ! 
Could you please create an issue for this PR ? 
Also, I think it is missing SQL for the update process @see : https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/upgrade/sql
What do you think @PierreRambaud  ?

**Comment by HamzaElghanoui** [comment]
Hi @PululuK the issue already created https://github.com/PrestaShop/PrestaShop/issues/15048

**Comment by PululuK** [comment]
> Hi @PululuK the issue already created #15048

Thank you !

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — CHANGES_REQUESTED** [review]
Hi @HamzaElghanoui, thanks for your contribution ! However, @PululuK is right, the upgrading process should be took into account too.

**Comment by HamzaElghanoui** [comment]
> Hi @HamzaElghanoui, thanks for your contribution ! However, @PululuK is right, the upgrading process should be took into account too.

Hi @atomiix  @PululuK @Progi1984 
Because my old branch was become unknown repository I will create a new PR
https://github.com/PrestaShop/PrestaShop/pull/19660
Thank you all.

**Comment by Progi1984** [comment]
PR Closed. Moved to #19660

**Comment by PululuK** [comment]
> PR Closed. Moved to #19660

NOPE ! it's not the same PR
 #19660 is complementary to it

**Comment by Progi1984** [comment]
@HamzaElghanoui Could you move your modifications to the another PR ? Sorry, I can't reopen this PR because the repository has been removed.

**Comment by HamzaElghanoui** [comment]
> @HamzaElghanoui Could you move your modifications to the another PR ? Sorry, I can't reopen this PR because the repository has been removed.

it's done @Progi1984 
This is new PR https://github.com/PrestaShop/PrestaShop/pull/19692

**Comment by Progi1984** [comment]
Thanks @HamzaElghanoui

**Pull request closed without merging**
