### PR TITLE
[+] Installer : actionFrontControllerSetMedia in DB

### PR DESCRIPTION
**Pull request by connemb**
Hook was executed in FrontController setMedia method, but was not
available in the hook table.
This is a useful alternative for modules to use when adding CSS and JS
files instead of relying on hookTop and hookHeader

### CODE REVIEW

**Comment by PrestaEdit** [comment]
If the hook exist, you don't need to have it into the DB, do you know. It's usefull if it's a display one, to change the hook and position into the module positions list, but not for an action one.

As I think.

**Comment by connemb** [comment]
Other hookActions are in the hook database. You might be right about the hook still being able to run, however this gives the user the ability to transplant a module and rearrange the order of the modules. I came across this because they have actionAdminControllerSetMedia set in the DB, but not the front office actionFrontControllerSetMedia and we were not able to transplant our module into it without it being present in the database

**Comment by PrestaEdit** [comment]
You are right about transplant and positions. It's maybe a good thing to have it in DB. And it's not really a big things to do ! ;)

Let PrestaShop team decide about it ;-)

**Comment by xBorderie** [comment]
Thank you for your contribution! We are reworking this area for the Starter Theme, therefore I am closing this PR. Cheers!

**Pull request closed without merging**
