### PR TITLE
Allow product default supplier reference to be updated, if the product supplier is already attached to the product

### PR DESCRIPTION
**Pull request by simondaigre**
This PR allows product default supplier reference to be updated, if the product supplier is already attached to the product.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update product supplier reference whatever product supplier is new or not.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Create a product, add a product supplier with reference, edit supplier reference

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11175)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by simondaigre** [comment]
Hi @mickaelandrieu,

Could you merge this PR ?

Thanks

**Comment by PierreRambaud** [comment]
Hi @simondaigre , can you apply a cs fixer please?
To run the command:
`./vendor/bin/php-cs-fixer fix`

**Review by Quetzacoalt91 — APPROVED** [review]
Rebased, ammended the commit title & applied cs fixer.

**Comment by Quetzacoalt91** [comment]
Thank you @simondaigre

**Comment by simondaigre** [comment]
@PierreRambaud Hi, seems my fix is broken by your commit https://github.com/PrestaShop/PrestaShop/commit/29bda43a552316fb4a29c60f44ff287230bce62f#diff-7d7493bae4eba5d548b7f7f88d16d7ea

Default supplier reference is not set for base product. Could you revert this ?

Thanks

**Pull request merged**
