### PR TITLE
[-] CORE : #PSCSX-6589 - Backup database views

### PR DESCRIPTION
**Pull request by erouvier29**

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

Can you give me more details ? I created a simple view but it wasn't backed up :(

**Comment by eric-rouvier** [comment]
Strange...
At the end of the backup file, you should find the optionnal DROP VIEW instruction and the CREATE (...) VIEW one for each defined view which name starts with DB_PREFIX. No content, of course, as it is dynamic.

Could it depend on MySQL version?
Does your view appear in the results of "SHOW TABLES"?
And what is the result of "SHOW CREATE TABLE ps_your_view" ?

**Comment by julienbourdeau** [comment]
Hi,

I'll try again. We'll merge this into develop, do you mind rebasing your branch and make a new PR on the develop branch ?
I wouldn't normally ask this we need to delete the `1.6.2.x` branch.

Thank you!

**Comment by julienbourdeau** [comment]
Hi,

I ported your Pr overthere #4346 since PrestaShop 1.6.2 has been cancelled to deliver PrestaShop 1.7 faster ;)

Thanks for your commitment.

**Comment by eric-rouvier** [comment]
Hi Julien,
Sorry but I didn't have time to do it earlier.
Thank you for the transfer.

**Pull request closed without merging**
