### PR TITLE
Fixed DB backup page

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | DB backup page was not updated using new interfaces
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Access Configure > Advanced Parameters > Database then Backup tab

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10223)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Hi @LouiseBonnard, this translation key was not found: 

"Check the maximum filesize allowed (e.g. Max: 16MB)" in "AdminAdvparametersHelp" domain, even in fallback catalog.

What do we do?

**Comment by LouiseBonnard** [comment]
@mickaelandrieu, the translation key is currently localized in the _messages.xlf_ file. Since it is better to assign domains to it, let's just keep it under Admin.Advparameters.Help if you're alright with that. :-)

**Comment by mickaelandrieu** [comment]
@LouiseBonnard I do but because the current fallback catalog is not synced with our code, we are unable to retrieve the key and this makes the e2e test break: do you think we can update the translation pack? /c @eternoendless

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@mickaelandrieu Is there something missing now?

**Comment by mickaelandrieu** [comment]
I don't think so :+1:

**Comment by PierreRambaud** [comment]
Thanks @mickaelandrieu

**Pull request merged**
