### PR TITLE
Replace mobile quick access smarty template by twig component

### LINKED ISSUE #33168: Twig Component : Mobile quick access

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Replace mobile quick access smarty template by twig component
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto tests 🟢 
| Fixed ticket?     | Fixes #33168 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by boherm — DISMISSED** [review]

**Comment by boherm** [comment]
Please fix the CI :)

**Review by boherm — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Comment by FabienPapet** [comment]
Conflict comes from quality tools files, this may not need qa validation after rebase.

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/5540572986

**Review by boherm — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @lartist

**Review by tleon — APPROVED** [review]

**Pull request merged**
