### PR TITLE
[+] FO : Use default state for tax purposes

### PR DESCRIPTION
**Pull request by cedricfontaine**
In countries with two level of taxes, it is interesting to give an estimate of taxes based on the shop location and applying also the state tax.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks a lot for this new PR! A developer will soon review it. Cheers!

**Comment by maxlandry** [comment]
I've modified my Address.php file, but it doesn't work... It only shows the Country tax by default, without the provincial/state tax.

**Comment by xBorderie** [comment]
@maxlandry Thank you for reviewing! Only the Address.php file is changed in this PR, so it seems you did things correctly.
@cedricfontaine, any feedback on this?

**Comment by fojtcz** [comment]
I think the default state should be different for every country.

**Comment by cedricfontaine** [comment]
Yes it's only Address.php to make it works. It should work,

**Comment by xBorderie** [comment]
@maxlandry Could you give us a screenshot explaining why it fails, or at least more details?

@cedricfontaine Could you describe how best to test your PR?

Thank you both!

**Comment by maxlandry** [comment]
Absolutely!

So I modified the address.php file with the correction suggested.
capture d ecran 2016-05-10 a 10 38 14

But when I add an item in my cart, it only shows the country tax, not the state one.

capture d ecran 2016-05-10 a 10 39 10

When I connect with my user account (that has the same country and same state as the store), everything works perfectly.

capture d ecran 2016-05-10 a 10 39 31

Any idea of what's going on? I'm using Prestashop 1.6.1.5

**Comment by cedricfontaine** [comment]
To test it, juste create tax with a default rate for the country, and a new rate for a specific state. With my modification, the default rate will use the same as the default state of the shop.

**Comment by maxlandry** [comment]
I've created a new tax rule with 2 new taxes, and it still does the same thing...

capture d ecran 2016-05-10 a 13 41 18

**Comment by aleeks** [comment]
Hello @cedricfontaine 
I'm closing this PR, i cherry-pick your commit here: https://github.com/PrestaShop/PrestaShop/pull/7482 (rebased from develop)
Thank you :+1:

**Pull request closed without merging**
