### PR TITLE
Improve adresses block in customer BO page

### LINKED ISSUE #18980: [BO][CUSTOMER][ADDRESSES BLOCK] Add addresses ID and N° of items
#### Is your feature request related to a problem?

Add addresses ID and N° of items (BO > Customers > Customer > Adresses block)

#### Describe the solution you'd like
Keep consistency with the other blocks (Group, Orders ... etc)

adress_block (1)

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Add addresses ID and N° of items (BO > Customers > Customer > Adresses block).
| Type?         |  improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18980.
| How to test?  | See #18980.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18981)

### CODE REVIEW

**Comment by matks** [comment]
Nice idea, it looks good 😄 
Capture d’écran 2020-05-05 à 15 47 10

**Review by matks — APPROVED** [review]

**Comment by PululuK** [comment]
> Nice idea, it looks good smile

Thank you John DOE 😅

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@TristanLDD Is it ok for you on the UX side ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PululuK** [comment]
News ?

**Comment by Progi1984** [comment]
Ping @TristanLDD ;)

**Comment by PululuK** [comment]
Ping @TristanLDD @Progi1984

**Comment by NeOMakinG** [comment]
@prestascott wdyt too ? :)

**Comment by prestascott** [comment]
Hi everyone, 

It seems that the 'edit button' is separated from the 'more button' -> they should be displayed in the same column which is 'Actions'. 

Apart from that, 'address id' and 'number of items' sound good to me! :)

**Comment by PululuK** [comment]
Hi @prestascott  
> It seems that the 'edit button' is separated from the 'more button' -> they should be displayed in the same column which is 'Actions'.

It's not in the scope of the issue. See #18980 please !

> Apart from that, 'address id' and 'number of items' sound good to me! :)

Yes !

Thanks

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @PululuK !!

**Comment by NeOMakinG** [comment]
Thanks @PululuK

**Pull request merged**
