### PR TITLE
Build Back Office default theme using Webpack 4

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This upgrades webpack in the back office default theme to v4
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Legacy pages in the BO should continue to work as before

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9471)

### CODE REVIEW

**Review by CaptainYouz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9471)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @eternoendless)

___
*[admin-dev/themes/default/package.json, line 16 at r1](https://reviewable.io/reviews/prestashop/prestashop/9471#-LKw6Fmj9o-TfSrwbdVi:-LKw6Fmj9o-TfSrwbdVj:b38wp6t) ([raw file](https://github.com/prestashop/prestashop/blob/1024192ff9baa9a028274c1c361867a31aa9f629/admin-dev/themes/default/package.json#L16)):*
> ```JSON
>         "@babel/core": "^7.0.0-rc.1",
>         "@babel/preset-env": "^7.0.0-rc.1",
>         "babel-loader": "^8.0.0-beta.4",
> ```

warning: beta version
___
*[admin-dev/themes/default/webpack.config.js, line 82 at r1](https://reviewable.io/reviews/prestashop/prestashop/9471#-LKw6YKr4jt1CFh7hsMm:-LKw6YKr4jt1CFh7hsMn:b-8a919e) ([raw file](https://github.com/prestashop/prestashop/blob/1024192ff9baa9a028274c1c361867a31aa9f629/admin-dev/themes/default/webpack.config.js#L82)):*
> ```JavaScript
>       }]
>     },
>     optimization: {
> ```

empty object, is it needed ?

**Review by CaptainYouz — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
We need a rebase here @eternoendless  :)

**Comment by Quetzacoalt91** [comment]
:wave: @eternoendless there are also some comments from @CaptainYouz waiting to be solved.

Sending to QA anyway.

**Review by eternoendless — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9471)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @CaptainYouz)

___
*[admin-dev/themes/default/package.json, line 16 at r1](https://reviewable.io/reviews/prestashop/prestashop/9471#-LKw6Fmj9o-TfSrwbdVi:-LLZMNB5-yKiGXcu0uJa:byu1r8y) ([raw file](https://github.com/prestashop/prestashop/blob/1024192ff9baa9a028274c1c361867a31aa9f629/admin-dev/themes/default/package.json#L16)):*
<details><summary><i>Previously, CaptainYouz (Anas Mammeri) wrote…</i></summary><blockquote>

warning: beta version
</blockquote></details>

We need babel-loader v8 with webpack 4. They have now released the stable version so i'll upgrade it. Recompiling produces no side effects.
___
*[admin-dev/themes/default/webpack.config.js, line 82 at r1](https://reviewable.io/reviews/prestashop/prestashop/9471#-LKw6YKr4jt1CFh7hsMm:-LLZMi3x-G1wSQjzabMc:b-8o8cs0) ([raw file](https://github.com/prestashop/prestashop/blob/1024192ff9baa9a028274c1c361867a31aa9f629/admin-dev/themes/default/webpack.config.js#L82)):*
<details><summary><i>Previously, CaptainYouz (Anas Mammeri) wrote…</i></summary><blockquote>

empty object, is it needed ?
</blockquote></details>

As discussed, added for simplification. Used below (config.optimization.minimizer).

**Review by CaptainYouz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9471)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @CaptainYouz)

**Comment by Quetzacoalt91** [comment]
I merged although there are issues with some cs fixer. I'll make a specific PR about this.

Thank you @eternoendless

**Pull request merged**
