### PR TITLE
Change PrestaShop URL in footer of emails

### LINKED ISSUE #22311: [EPIC] Improve legal compliance of the open source project
#### Is your feature request related to a problem?

I am studying the legal compliance of the PrestaShop open source project's Core and its dependencies. In order to be legal compliant, a few improvements are needed.

#### Describe the solution you'd like

- [x] replace jsonify (NPM) because it is in public domain, and it is not acceptable regarding the project license. An alternative exists: https://github.com/substack/jsonify/pull/7#issuecomment-612860241
- [x] update soundasleep/html2text in last version. Current used version is in EPL, and the new version is in MIT. https://github.com/soundasleep/html2text
- [ ] TinyMCE, Cropper, File uploader and PHP SQL parser must have their own repository (if we forked them) or must be managed via a dependencies manager. Currently, they are directly included directly in the Core of PrestaShop. #16475
- [ ] In modules, some librairies are included in the repository instead of being in the list of dependencies in package managers configuration #16015 #16012 #16011 
- [ ] In general, try to remove dependencies distributed under Unlicense and LGPL would be a nice to have. So, no more should be added, if it is possible replace them, it would be awesome. While it is possible to have them in the project regarding OSL, some users that are very straight about open source definition and legal compliance might consider them as a possible problem regarding legal compliance.
   - Unlicense: postcss-apply@0.3.0, postcss-apply@0.8.0, spdx-license-ids@1.2.2, tweetnacl@0.14.5
   - LGPL: ezyang/htmlpurifier, smarty/smarty, tecnickcom/tcpdf, TinyMCE
- [ ] Code origin and authors knowledge #27557

#### Additional context

Enforcing the legal compliance of the PrestaShop open source project will lead to more adoption by companies that care about it; e.g North America and Germany, and big companies in general take a lot of care about legal compliance, in order to avoid copyright issues and patent trolls.

Update note: adding a new issue to the list

## Fixed

- [x] #27172
- [x] Remove useless dependencies like "prestashop-release-script"
- [x] GDPR issue with CNDs used for fonts, #27541

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | According to Company/OS Project clarification, links in footer of emails should point to https://www.prestashop-project.org/ instead of https://www.prestashop.com/.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22311.
| Related PRs       | -
| How to test?      | -
| Possible impacts? | -
| Sponsor company | @Creabilis

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Comment by ghost** [comment]
Hi @micka-fdz I agree but I think the change should be brought here :

https://github.com/PrestaShop/mjml-theme-converter/blob/master/mails/themes/modern_mjml/components/footer.mjml.twig

**Comment by micka-fdz** [comment]
Hi @okom3pom,
Done here: https://github.com/PrestaShop/mjml-theme-converter/pull/25 ✅

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by micka-fdz** [comment]
Hi @atomiix, do we really need QA validation here?

Same PR already merged without QA here: https://github.com/PrestaShop/mjml-theme-converter/pull/25

**Review by florine2623 — APPROVED** [review]
Hello @micka-fdz ,

Without PR :
Screenshot 2022-07-07 at 10 49 17


With PR :


Screenshot 2022-07-07 at 10 55 32

It is QA ✅ 
Thanks!

**Comment by matks** [comment]
Thank you @micka-fdz

**Pull request merged**
