### PR TITLE
Remove  PS_SHOP_ACTIVITY and shop_activity 

### LINKED ISSUE #28851: Remove PS_SHOP_ACTIVITY and shop_activity only used by a removed controller
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Remove SHOP_ACTIVITY only used by removed controllers

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php#L85

### Describe the solution you'd like

Remove SHOP_ACTIVITY only used by removed controllers

https://github.com/PrestaShop/PrestaShop/blob/1.7.8.x/src/PrestaShopBundle/Controller/Admin/Improve/Modules/AddonsStoreController.php#L85

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      |Remove SHOP_ACTIVITY only used by removed controllers
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28851.
| Related PRs       | 
| How to test?      | Check if install work without activity  
| Possible impacts? |

### CODE REVIEW

**Comment by kpodemski** [comment]
Hello @okom3pom 

We discussed this element here on Github, and the product team decided to keep it.

CC @PrestaShop/product-team - we need your opinion there or in the issue

**Comment by ghost** [comment]
Hello @kpodemski 

I can't find a discussion on this if you have the link.

I don't see the point of keeping these lines that are not being used.

But if the PM wants to, no worries

**Comment by kpodemski** [comment]
@okom3pom I agree with you, I wanted to have this code deleted, but this configuration might be in use by some external companies/developers who use them for something... :) Let's wait for a PM decision.

**Comment by PrestaEdit** [comment]
The discuss is here : https://github.com/PrestaShop/PrestaShop/pull/26850

**Comment by ghost** [comment]
Thank you,
I was looking for in the issues.

**Review by Progi1984 — APPROVED** [review]

**Pull request closed without merging**
