### PR TITLE
Merge `8.1.x` into `develop`

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge `8.1.x` into `develop`
| Type?             | improvement 
| Category?         | ME 
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by matks** [comment]
Automated tests https://github.com/matks/ga.tests.ui.pr/actions/runs/5900485321

**Review by boubkerbribri — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional can we merge? :) auto tests ok

**Comment by boubkerbribri** [comment]
> @PrestaShop/qa-functional can we merge? :) auto tests ok

Saw with @aniszr , you can merge

**Comment by jolelievre** [comment]
Thanks @matks

**Pull request merged**
