### PR TITLE
change of logos

### PR DESCRIPTION
**Pull request by emmanuelf75009**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | This pull request regards the change of the demo logo in the front office, the invoice and the emails. It is displayed both in front office and in BO as an example
| Type?         | Improvement
| Category?     | FO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | Reinstall and check the front office / Generate an invoice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8733)

### CODE REVIEW

**Comment by emmanuelf75009** [comment]
Hi, 
This pull request regards the change of the demo logo in the front office, the invoice and the emails. 
Il is displayed both in front office and in BO as an example

**Review by Quetzacoalt91 — APPROVED** [review]
As the size is different for each logo, the rendering must be checked.

**Comment by toutantic** [comment]
I checked the rendering, size of the logo on the invoice is fine.
Size of the logo on the front page is ok but when you put the mouse over the menu the logo is partially hidden by the menu that pop-up. It does not look nice. 
Height of the logo should be reduce as much as possible

**Comment by toutantic** [comment]
Replaced by #8739

**Pull request closed without merging**
