### PR TITLE
[*] BO : Replaced logical operators

### PR DESCRIPTION
**Pull request by jremes-foss**
Good morning.

I replaced the logical operators in the source code. The reason for this is simple: for example, the and operator does not have the same precedence as &&. Same goes with or and ||. This could lead to unexpected behavior and carries a bug risk so it is best to replace them.

Thank you.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
:+1:

**Comment by xBorderie** [comment]
Hello @Newman101 ! Thank you for this PR!

Could you [update your commit's name](https://help.github.com/articles/changing-a-commit-message/) so that it follows [the guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)?

Thank you!

**Comment by Newman101** [comment]
Sure, I can do that. Thank you for notifying me about the code guidelines, I will follow them from now on.

**Comment by Newman101** [comment]
Done.

**Comment by xBorderie** [comment]
Ah, I saw your action live on that page :)

Sorry, but I didn't mean the PR's title, but the commit's name itself, because this is what is being parsed by our changelog-building tool. 
This cannot be changed through the GitHub interface, you have to update the commit itself using Git. [More information on this page](https://help.github.com/articles/changing-a-commit-message/) (in short: use `git commit --amend`).

**Comment by Newman101** [comment]
Ok, I'll do that then. Just let me amend that from my terminal. =)

**Comment by xBorderie** [comment]
Yup, that's the way to do it! Thanks!

**Comment by Newman101** [comment]
Done. :)

**Comment by xBorderie** [comment]
Well done, thanks!

**Comment by mickaelandrieu** [comment]
thank you @Newman101

**Comment by Newman101** [comment]
You're welcome :) Happy to help.

**Pull request merged**
