### PR TITLE
[+] MySQL 5.7 Compatibility

### PR DESCRIPTION
**Pull request by ianfunghk**
Fix error occurred during installation. SQL error on query

> All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

What MySQL version are you using ?
I fixed it here #4507 but I feel like your fix is better than mine :smile: 

Have you got any error with your cart? I believe the behavior won't even change, MySQL probably fixed this silently before 5.7.

**Comment by ianfunghk** [comment]
I am using MySQL version 5.7.9 and actually it is the first day to use PrestaShop. I did not realized it was related to the MySQL version and were shocked as this code seems existed for so long.

Originally, I did a search and come up with [this](https://www.prestashop.com/forums/topic/480947-error-presta-on-server-2012-r2-sql-error-on-query-all-parts-of-a-primary-key-must-be-not-null/?p=2182525). After looking into the code, I came up with my own (I think it is better, also thanks for your support) solution.

**Comment by julienbourdeau** [comment]
Hi,

I forgot yesterday but when you change the SQL structure, you need to make the same change in the sql file used for upgrade. You can have a look here #4553 

Also, for your next PR (I hope you'll make more), please follow this norm for PrestaShop commit message format:
http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

**Comment by zimmi1** [comment]
Just downloaded from PrestShop home page, the error is still here and blocks install... (!)

**Pull request merged**
