### PR TITLE
Enable controlling of default language URL prefix

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Allows to control if URLs of default language should be prefixed by language or not. This avoids breaking all URLs and loosing SEO when you add a second language.
| Type?             | new feature
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Test with friendly URLs ON, OFF. Test multiple language, test canonical redirection.
| UI Tests          |  https://github.com/florine2623/testing_pr/actions/runs/11707757642 ✅ 
| Fixed issue or discussion?     | https://www.prestashop.com/forums/topic/550132-how-to-remove-main-language-in-url/, https://www.prestashop.com/forums/topic/636971-removing-language-prefix-after-domain-url-in-prestashop-172x/, https://www.prestashop.com/forums/topic/112809-language-prefix-in-url/, https://www.prestashop.com/forums/topic/569679-how-to-remove-default-language-from-url-when-i-have-2-languages-set/, https://www.prestashop.com/forums/topic/178062-any-way-to-hide-en-language-prefix-in-url/, https://www.prestashop.com/forums/topic/711696-country-code-in-urls-language-packs/
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/1009
| Sponsor company   | 

### How it looks
setings

### What it resolves
You have French shop and your URLs look like this. Normal PrestaShop.
- http://localhost/3-clothes

You expand and add another language and suddenly, you loose all of your SEO because URLs get changed:
- http://localhost/fr/3-clothes
- http://localhost/en/3-clothes

### How it works
You have French, German and English on your shop. French is default.

If you have the prefix enabled
- http://localhost/fr/3-clothes
- http://localhost/de/3-clothes
- http://localhost/en/3-clothes

If you have the prefix disabled.
- http://localhost/3-clothes ⬅️ here is the change
- http://localhost/de/3-clothes
- http://localhost/en/3-clothes

### What I tested
- When prefix is enabled and I visit http://localhost/3-clothes, I get redirected to http://localhost/fr/3-clothes. ✅
- When prefix is disabled and I visit http://localhost/fr/3-clothes, I get redirected to http://localhost/3-clothes. ✅
- Changing languages work properly. ✅

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Global`
    - [ ] `Use prefix for default language`

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by ShaiMagal — APPROVED** [review]
This is a common problem usually resolved some htaccess hacks, much better.

**Comment by jf-viguier** [comment]
A must have, Thanks Daniel

**Review by jf-viguier — APPROVED** [review]

**Review by LouisAUTHIE — APPROVED** [review]

**Comment by LouisAUTHIE** [comment]
Nice thx

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Thanks for the PR and the detailed description ^^

I tested the following :
- enabling/disabling of the option
- with 1 language enabled/multiple languages enabled
- checked the URL with existing/existing ISO code

I have found a small error :

- I have English as default language & France as a country
- Disable the option `Use prefix for default language`
- Disable French language
- Go to FO
- Go to any product page ✅ 
- Go to any category from the menu :x: 404 error

https://github.com/user-attachments/assets/c016825d-3b15-47c2-aaf4-198ce90123c5




Could you check ? :)

Thanks!

**Comment by Hlavtox** [comment]
@florine2623 You need to clear cache, because the module has HTML cache of the items and it remembers URLs. The same issue happens if you change URL of a category or something.

**Comment by florine2623** [comment]
You are right, it works perfectly when I don't forget to clear to cache ^^

**Comment by Hlavtox** [comment]
@florine2623 Not really your fault, the module should be probably hooked to more places, but there are many things that may break it, probably not worth it. :-)

Thank you

**Pull request merged**
