### PR TITLE
Update modules (blockreassurance/dashtrends/ps_checkpayment/welcome)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Update modules:<br>- blockreassurance: v4.1.1 to v5.0.0<br>- dashtrends: v2.0.2 to v2.0.3<br>- ps_checkpayment: v2.0.4 to v2.0.5<br>- welcome: v6.0.0 to v6.0.3
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | Check if modules blockreassurance, dashtrends, welcome are well installed, are up-to-date and they have no errors at use.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21449)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matks** [comment]
Travis fails 🤔 
```
NFO: Module statssearch has no vendor folder [] []
[2020-10-14 16:45:43] app.INFO: Protect vendor folder in module statsstock [] []
[2020-10-14 16:45:43] app.INFO: Module statsstock has no vendor folder [] []
[2020-10-14 16:45:43] app.INFO: Protect vendor folder in module statsvisits [] []
[2020-10-14 16:45:43] app.INFO: Module statsvisits has no vendor folder [] []
[2020-10-14 16:45:43] php.CRITICAL: Fatal Compile Error: PrestaShop\PrestaShop\Adapter\Module\ModuleDataProvider::main(): Failed opening required '/home/travis/build/PrestaShop/PrestaShop/modules/welcome/vendor/autoload.php' (include_path='/home/travis/build/PrestaShop/PrestaShop/vendor/pear/pear_exception:/home/travis/build/PrestaShop/PrestaShop/vendor/pear/console_getopt:/home/travis/build/PrestaShop/PrestaShop/vendor/pear/pear-core-minimal/src:/home/travis/build/PrestaShop/PrestaShop/vendor/pear/archive_tar:.:/home/travis/.phpenv/versions/7.1.27/share/pear') {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: PrestaShop\\PrestaShop\\Adapter\\Module\\ModuleDataProvider::main(): Failed opening required '/home/travis/build/PrestaShop/PrestaShop/modules/welcome/vendor/autoload.php' (include_path='/home/travis/build/PrestaShop/PrestaShop/vendor/pear/pear_exception:/home/travis/build/PrestaShop/PrestaShop/vendor/pear/console_getopt:/home/travis/build/PrestaShop/PrestaShop/vendor/pear/pear-core-minimal/src:/home/travis/build/PrestaShop/PrestaShop/vendor/pear/archive_tar:.:/home/travis/.phpenv/versions/7.1.27/share/pear') at /home/travis/build/PrestaShop/PrestaShop/modules/welcome/welcome.php:24)"} []
The command "if [ "$PRESTASHOP_TEST_TYPE" != "sanity" ]; then bash travis-scripts/install-prestashop; fi" failed and exited with 1 during .
```

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I have an error during the Install
image
Also detected by Travis: https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/399633200#L560

Thanks to check it.

**Review by PierreRambaud — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by Progi1984** [comment]
@khouloudbelguith Fixed. Ready for testing ;)

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

After a fresh installation, the module welcome can't be started
There's an error in the console
image

Thanks!

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by matks** [comment]
Duplicate Travis check => PR can only be merged with Admin rights

**Review by PierreRambaud — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1CRQowpCmfaHMR73IG5HU3BSWh6L7QdIO/view?usp=sharing

Thanks!

**Pull request merged**
