### PR TITLE
Delete a category using the three options and script refactoring

### PR DESCRIPTION
**Pull request by hadrich-hatem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows to do a script refactoring of the create, edit, delete and check a category. Delete a category using the three options.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run the script path=full/3_category/* npm run specific-test -- --URL=BackOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9112)

### CODE REVIEW

**Comment by marionf** [comment]
Hello @fatmaBouchekoua 
I will review it after the the rebase & the code review :)

**Comment by hadrich-hatem** [comment]
Hello @marionf,
The rebase of this PR done.
Thank you to do the review on it.
Best regard,

**Comment by marionf** [comment]
Hello @hadrich-hatem 
I am waiting the technical code review before :)
The code reviewer can add the "Waiting for QA" status after the CR

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @hadrich-hatem 
This test should catch this issue: http://forge.prestashop.com/browse/BOOM-4293
Can you verify if it's well the case and let me know ?
Thanks :)

**Comment by hadrich-hatem** [comment]
Hello @marionf,
This test didn't catch that issue, but if you want I can add that case to verify the existence of the bug in the FO.

**Comment by marionf** [comment]
This means that we don't check if the products have been associated to the parent category if I choose to:
- "associate the products without other categories to the parent category, and keep them enabled. "
- "associate the products without other categories to the parent category, then disable these products for now. I re-enable them when they are moved in their new category. (Recommended) "
Can you please add this check ?
We need to check it for the 3 products after each option of deletion:
- the product associated only to the deleted category
- the product associated to the deleted category (principal) & to another category
- the product associated to the deleted category & to another category (principal)

**Comment by hadrich-hatem** [comment]
Hello @marionf,
I have added the check of this issue [BOOM-4293](http://forge.prestashop.com/browse/BOOM-4293).
Can you review the scenario again?
Thanks :)

**Comment by marionf** [comment]
@fatmaBouchekoua can you review it ?

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Need rebase again due to the merge of : #8887

**Comment by hadrich-hatem** [comment]
Hello,
The rebase of this PR done.
Thank you :)

**Comment by PierreRambaud** [comment]
@fatmaBouchekoua This one need a new review :)

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Need rebase again due to another merge :(

**Comment by hadrich-hatem** [comment]
Hello,
The rebase of this PR done.
Thank you :)

**Comment by PierreRambaud** [comment]
@fatmaBouchekoua for review and @marionf for QA please? :)

**Review by fatmaBouchekoua — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks  @hadrich-hatem

**Pull request merged**
