### PR TITLE
Make PrestaShop headless

### LINKED ISSUE #21144: How to go headless ?
Hi,

I'm upgrading my frontend to React and really need a complete REST API, with products and login endpoints, for instance.

When I search, I see mixed signals :
. at [PrestaShop-Day-Paris-2020](https://build.prestashop.com/news/CFP-PrestaShop-Day-Paris-2020/) , headless looks like a priority
. the marked is heading that way. Magento has a great REST API [(doc)](https://magento.redoc.ly/2.4.0-admin/)

But :
. I can't find any session about it at [PrestaShop-Day-Paris-2020](https://events.prestashop.com/prestashop-day-paris-2020/fr/sessions?searchtext=&page=1&group=Tech%20Talks)
. in the [roadmap page](https://github.com/PrestaShop/PrestaShop/projects/1), it doesn't look like it's planned, except 2 lines  "The PrestaShop webservice needs some refactoring and tests" in the backlog.

I need a long term strategy.

What's the plan ?

Thanks a lot,

Olivier Allouch

### PR DESCRIPTION
**Pull request by le-melon**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | It's 2023 time to go headless folks. To the moon!
| Type?             |  new feature
| Category?         | FO
| BC breaks?        | yes but nobody cares
| Deprecations?     | no
| How to test?      | After this PR PrestaShop got swag
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/21144
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by mflasquin — CHANGES_REQUESTED** [review]
Don't forget to delete admin-dev/themes to make the BO headless (or backless ?) too :smile:

**Review by Hlavtox — CHANGES_REQUESTED** [review]
😁

**Comment by sudo-do** [comment]
looking forward for Prestashop cli

**Comment by le-melon** [comment]
The CI is wrong, my code is right.

**Pull request closed without merging**
