### PR TITLE
Fix bug in ajax quantity refresh

### LINKED ISSUE #9754: [BOOM-4714] ajax quantity refresh
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4714).

- _**Reporter:**_ gianginone
- _**Created at:**_ Sat, 27 Jan 2018 17:44:10 +0100

<p>I have a combination with quantity and another attribute. </p>

<p>I have quantity 50 and color blue: minimal quantity to order 50</p>

<p>quantity 100 and color blue: minimal quantity to order 100</p>

<p> </p>

<p>after i choose 100 and blue combination is ok and the quantity to add to cart is 100 </p>

<p>but if i try to change this combination to the first the quantity not update to 50 but is 100</p>

<p> </p>

<p>why?</p>
        
* How to reproduce the issue ?

N/A

### LINKED ISSUE #10948: Products with combination
**Describe the bug**
The problem happen when there is a product with combinations and every combination has a minimun quantity order quantity.
When you are in the frontend product page, for instance if you choose a combination with minimun order quantity 200 the quantity input field is updated to 200 correctly (see image attached minimum_quantity_200.PNG), after this if you choose again a combination with minimum order quantity lower then the previous (for instance 100) the input field remains 200 (see attachment minimum_quantity_100.PNG).
This isn't the real problem indeed, if you try to change manually the input field setting for instance 100, it's impossible do add the product to the cart; clicking on the button "Add to cart" will get no action at all (see image attached minimum_quantity_100_B.PNG).
This is due to the fact that for the page the minimum order quantity is still set to 200.

**To Reproduce**
1. Go to a product page with combination that have different minimum order quantity
2. Click on a combination with minimum order quantity for instance 200, after choose a product with minimum order quantity setted to 100 and update manually the input field quantity to 100.
4. In this situation it's impossible to add the combination to the cart.

**Additionnal information**
PrestaShop version: different version affected 1.7.3.x to 1.7.4.2
minimum_quantity_100
minimum_quantity_100_b
minimum_quantity_200

### PR DESCRIPTION
**Pull request by damianobertuna**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Correction for Bug ajax quantity refresh #10948
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #10948
| How to test?  | - Go to a product page with combination that have different minimum order quantity<br />- Click on a combination with minimum order quantity for instance 200, after choose a product with minimum order quantity setted to 100 and update manually the input field quantity to 100.<br />- In this situation it's impossible to add the combination to the cart.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10964)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi and thanks for the contribution. Look like you add some commits that are mustn't be in this pull request. Can you change it and target the 1.7.5.x branch please?

**Comment by damianobertuna** [comment]
> Hi and thanks for the contribution. Look like you add some commits that are mustn't be in this pull request. Can you change it and target the 1.7.5.x branch please?

Sorry, I'm not so skilled on github, could you tell me some tips about how to do?

**Comment by PierreRambaud** [comment]
Hi @damianobertuna I fixed your branch and I commit to the real file which is `themes/_core/js/product.js` ;)

**Review by tomlev — DISMISSED** [review]

**Comment by ntiepresta** [comment]
Hi, 
This correction, resolves well problem described . But, displays this error, the field quantity have not been updated with minimum quantity. And impossible of decrease  the quantity.
marion pro

https://drive.google.com/file/d/1fd1wDq-T_Ag4YlYAYcDfR8qutgOXl153/view?usp=sharing

**Comment by PierreRambaud** [comment]
I logically fix errors :)

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @damianobertuna

**Pull request merged**
