### PR TITLE
Update gsitemap

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Update gsitemap: https://github.com/PrestaShop/gsitemap/pull/53
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11027)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Can you target the 1.7.5.x branch instead?

**Comment by MathiasReker** [comment]
@PierreRambaud I already am?

**Comment by PierreRambaud** [comment]
`PrestaShop:develop from Mreker:update-composer` :) You're targeting develop branch

**Comment by MathiasReker** [comment]
Sorry, my bad! Should be fixed now. :)

**Comment by eternoendless** [comment]
@Mreker did you edit the composer.lock file manually? Because v4 hasn't been released yet.

**Comment by MathiasReker** [comment]
@eternoendless yes, I edit the file manually

**Comment by eternoendless** [comment]
I see now. You should never (in any project) change the .lock file manually, because it's maintained by composer itself.

Don't worry though, I'll update it for you when we release the v4 version of the module.

**Comment by MathiasReker** [comment]
Okay, thank you @eternoendless

I wrote the changelog to the new version here: https://github.com/PrestaShop/gsitemap/pull/53

**Pull request closed without merging**
