### PR TITLE
Allow to see the vouchers that will be available

### LINKED ISSUE #21797: The vouchers available in the future assigned to a specific user are not visible in the FO
#### Is your feature request related to a problem?

The vouchers available in the future assigned to a specific user are not visible in the FO.

Capture d’écran de 2020-11-06 18-40-46

#### Step to reproduce

1. Create a voucher for 2021
2. Go to customer account check if the voucher is display

#### Describe the solution you'd like

The voucher to come are not visible
Capture d’écran de 2020-11-06 18-41-04
Capture d’écran de 2020-11-07 10-54-04

## Specs 

**User need (merchant):**
- As a merchant, I want to be able to display or not the vouchers that will be available on the customer account (FO).

**Specs:**
- It would be a checkbox with the wording “Display the voucher on the customer account” (wording still to be defined by @Julievrz). 
- If the date is a later date, the checkbox will be displayed. 
- If the date is an earlier date or the same day, the checkbox won’t be displayed.
- If the date that was a later date becomes an earlier date or the same day, the checkbox won’t be displayed.

**Design:**

Step 1: Enter the later dates
Cart Rules - conditions valid future

Step 2: See the "Display" option
Cart Rules - conditions valid future hidden

Step 3: Check the "Display" option
Cart Rules - conditions valid future display

#### Additional context

Version : 177RC
PHP 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Allow to see the vouchers that will be available
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21797
| How to test?  | Create a voucher that will be available in XX day, go to customer account check if voucher is display

Capture d’écran de 2020-11-07 15-10-21
Capture d’écran de 2020-11-07 15-10-04

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21803)

### CODE REVIEW

**Comment by Progi1984** [comment]
@PrestaShop/product-team We are waiting for your specs on #21797

**Comment by rdy4ever** [comment]
I think some merchants don't want this behaviour by default, so you should also add a configuration to turn this on or off. Maybe I'm having a sale and generate some vouchers, but I don't want my customers to know about the sale in advance and wait for it.

**Comment by ghost** [comment]
@rdy4ever if the PR do : 

**Display voucher to come only if attached with an id_customer** 

Whats do you think ?

**Comment by rdy4ever** [comment]
> @rdy4ever if the PR do :
> 
> **Display voucher to come only if attached with an id_customer**
> 
> Whats do you think ?

This could work.

**Comment by Julievrz** [comment]
Hi @okom3pom ! Is all the wording present in the PR yet? Because I can see some wording in your screenshot that I cannot see in the PR (e.g.: "To Come")

**Comment by ghost** [comment]
@Julievrz << To come >> is the name of the Voucher :) 

For the moment i wait @MatShir feedback because cart rules :p

**Comment by prestascott** [comment]
Hello everyone,

**User need (merchant):**
- As a merchant, I want to be able to display or not the vouchers that will be available on the customer account (FO).

**Specs:**
- It would be a checkbox with the wording “Display the voucher on the customer account” (wording still to be defined by @Julievrz). 
- If the date is a later date, the checkbox will be displayed. 
- If the date is an earlier date or the same day, the checkbox won’t be displayed.
- If the date that was a later date becomes an earlier date or the same day, the checkbox won’t be displayed.

**Design:**

Step 1: Enter the later dates
Cart Rules - conditions valid future

Step 2: See the "Display" option
Cart Rules - conditions valid future hidden

Step 3: Check the "Display" option
Cart Rules - conditions valid future display

**Comment by Julievrz** [comment]
Here is my wording suggestion: 
"Display the voucher now in the customer account" in Admin.Catalog.Feature
What do you think?

**Comment by MatShir** [comment]
@Julievrz good for me. What do you think @okom3pom?

**Comment by Julievrz** [comment]
> @Julievrz good for me. What do you think @okom3pom?

@MatShir @okom3pom I updated my comment to remove the tooltip as it might be weird to have a tooltip or a help text with a checkbox. I hope "now" is clear enough but let me know if you feel like the wording should be improved.

**Comment by ghost** [comment]
@MatShir @Julievrz && @prestascott

I took the time to read all, it's ok for me all is good.

But when i see the ux i think i have to close this PR

Stay opened the # https://github.com/PrestaShop/PrestaShop/issues/21797

And i try to open a new PR but i think i need help for made a good PR, i am a kidam with javascript and when i read

```
If the date is a later date, the checkbox will be displayed.
If the date is an earlier date or the same day, the checkbox won’t be displayed.
If the date that was a later date becomes an earlier date or the same day, the checkbox won’t be displayed. 
```

I dont know how to do

Regards

**Pull request closed without merging**
