### PR TITLE
Update composer deps and lock classic to beta-2.0.0

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Update prestashop 8.0.x composer dependencies: ps_banner, blockwishlist and classic-theme. Classic-theme is now locked to 2.0.0-beta
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | These are patch updates and they are not supposed to break anything
| Possible impacts? |

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Comment by matks** [comment]
PHP CS Fixer is not happy
```
- require.prestashop/classic : exact version constraints (2.0.0-beta) should be avoided if the package follows semantic versioning
```

**Comment by matks** [comment]
CI Composer validation fixed in https://github.com/PrestaShop/PrestaShop/pull/29239/commits/7449c6d6ecb0eb0933e0bc5fe9c67d8bab90841e

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by MeKeyCool — APPROVED** [review]

**Comment by matks** [comment]
@PrestaShop/qa-team This change is supposed to have no consequences on the software but I let you choose what QA to perform against it

**Comment by Robin-Fischer-PS** [comment]
I think just an automated tests launch would be enough :)

**Comment by matks** [comment]
> I think just an automated tests launch would be enough :)

Sounds good to me 👍 😄

**Review by HanaRebaiQA — APPROVED** [review]
Hello, 

I have checked this PR. The automated tests are OK.
So, it's QA :heavy_check_mark: 

Thank You!

**Pull request merged**
