### PR TITLE
New hook added for adding new resource in webservice

### PR DESCRIPTION
**Pull request by dks295**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | [+]WS : Added new hook for adding new resource in webservice #5529 |
| Type? | improvement |
| Category? | WS |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | add new resource in prestashop webservice |

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi @dks295!

Can you add the hook on the XML registering all the hooks?

Thank you!

**Comment by dks295** [comment]
Hello,

Sure,

Is this 

prestashop/install/data/xml/hook.xml

file which is used to register hook using xml ?

Thanks,

**Comment by Shudrum** [comment]
Perfect :)

Thank you! (And sorry for the long response time)

**Comment by darktowerhosting** [comment]
great thing !

**Comment by prakashyuvib** [comment]
Hi,

i am register'd hook. But i am getting error in api page

**Fatal error: Uncaught Error: Class 'D**

**Pull request merged**
