### PR TITLE
Fix/get existing ids from ids or refs

### PR DESCRIPTION
**Pull request by jonasburneika**
fix for https://github.com/PrestaShop/PrestaShop/issues/10824 issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21406)

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hi @jonasburneika thanks for the PR but there is an issue with it.

Even if the parameter `match_ref` is used in the Import page, we cannot fetch it like this from `Tools::getValue()` directly inside Product class. That would break the [MVC principle](https://devdocs.prestashop.com/1.7/modules/concepts/controllers/). This class belongs to the Model, the parameter `match_ref` seems to belong in the Controller.

IMO the right way to implement this behavior would be
- add a new optional argument to `getExistingIdsFromIdsOrRefs()` to modify this behavior
- make sure to pass the right value for this argument inside the Controller

See example below

**Comment by matks** [comment]
Example:
```
public static function getExistingIdsFromIdsOrRefs($ids_or_refs, $forceUsingReferences = false)
```

The idea is that getExistingIdsFromIdsOrRefs can be used in many usecases where `Tools::getValue()` does not work. In a CLI context for example. So this function must be passed the right arguments through the code layer instead of getting the value directly from the request

**Comment by matks** [comment]
Also please fill in the PR template https://github.com/PrestaShop/PrestaShop/blob/develop/.github/PULL_REQUEST_TEMPLATE.md 🙏 that would help us to review this PR

**Comment by Julievrz** [comment]
Hi 😃 I cannot see any wording in this PR, is it normal?

**Comment by atomiix** [comment]
> Hi 😃 I cannot see any wording in this PR, is it normal?

@Julievrz you're right, I don't know exactly what happened there but there's no wording in this PR. I deleted PrestonBot's comment and the *waiting for wording* label.

@jonasburneika you'll need to resolve the conflicting file. Also, if you could [squash you commits](https://www.internalpointers.com/post/squash-commits-into-one-git), it would be nice :)

**Comment by matks** [comment]
Hi, [following our review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

Since this PR did not get any activity since November 2020, I close it.

Please note this does not mean it's a final "won't merge" 😉  ; if you come back we can reopen it and update it

Thank you for the contribution

**Pull request closed without merging**
