### PR TITLE
Fix checkbox direction on RTL

### LINKED ISSUE #24925: [BO] Invalid direction of checkbox marker in RTL
Hello,

#### Describe the bug

Checkbox marker has invalid direction in BO with **RTL** Layout

#### Expected behavior

.../adminxxx/themes/new-theme/public/theme_rtl.css (Line: 521)
Need to change (border-left-style: none) to (border-right-style: none)

#### Steps to Reproduce

BO: Improve > international > localization

Screenshot 2021-06-11 at 18-40-33 بومی سازی • NEO

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Checkbox direction was wrong using RTL language
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24925.
| How to test?      | Go on `/improve/international/localization/` and see checkboxes
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

# How does it looks?
image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25034)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

The checkbox is fixed but the menu is placed to the left (not to the right) and ofc this happens only with the new migrated pages.
Desktop:

https://drive.google.com/file/d/10J2Dm6DbcGfR4g6lhGNiar5B_fNpaLra/view

Mobile:

https://drive.google.com/file/d/1HqzATqOvsTL7LNtWi1fNvj1gHvXGpe6z/view

Please check and feedback.
Thanks!

**Comment by NeOMakinG** [comment]
@hiba, please rm `admin-dev/themes/new-theme/public/theme_rtl.css` file and disable then enable the RTL language again, that should work :)

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
@NeOMakinG Could you rebase your PR for merging it ?

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
