### PR TITLE
Remove deprecated method `getClassName` in class `Tab`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated method `getClassName` in class `Tab`
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5287119517
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks
* Remove deprecated method `getClassName` in class `Tab`

### CODE REVIEW

**Review by FabienPapet — APPROVED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Review by boherm — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @Progi1984 

Thanks for your PR 🚀 
Unfortunately the auto tests failed on 3 tests BO>Orders & BO>Products:
https://github.com/hibatallahAouadni/testing_pr/actions/runs/5308886062/jobs/9614803547
Please check and feedback.

Thanks!

**Comment by Progi1984** [comment]
@hibatallahAouadni It's the Docker build (problem with CI). Could you restart your failed tests ?

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Progi1984 

Thanks for your feedback 🙏 
LGTM, QA ✅ 
https://github.com/hibatallahAouadni/testing_pr/actions/runs/5308886062

Thanks!

**Comment by nicosomb** [comment]
Thank you @Progi1984 !

**Pull request merged**
