### PR TITLE
Prevent customization modal open if qty changed in cart on classic

### LINKED ISSUE #26852: FO - shopping cart page is freezed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Shopping cart page is freezed while setting the quantity of a customized product and press directly on product customization .
https://watch.screencastify.com/v/0TmTvd3Qeb7NNOEQAjZP

### Expected behavior

_No response_

### Steps to reproduce

1. Go to FO > Choose customized product
2. Add and save a customization 
3. Click on Add to th cart > Proceed to checkout
4. change the quantity and press directly on Product customization 
5. The shopping cart page is freezed

### PrestaShop version(s) where the bug happened

1.7.8.1/ 1.7.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We need to avoid the modal of customization to be opened right after manually changing the qty of the product
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26852.
| How to test?      | See issue
| Possible impacts? | Cart FO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26854)

### CODE REVIEW

**Review by sowbiba — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I have a behavior following these steps:

1. Go to FO > Choose a customized product
2. Add and save a customization
3. Click on Add to the cart > Proceed to checkout
4. In the FO > Shopping cart page 
5. Set a quantity with the keyboard and press directly on Product customization
6. The customization is not opened, we should click on it the second time to display it

I attached a screen-record
https://watch.screencastify.com/v/ThOcRIVBA2hMXGbbISjL
Is it a normal behavior?

----------------------------------------------------------

I have the same issue following these steps:
1. Create a customized product with minimal quantity = 2
2. Go to FO > Choose this  product
3. Add and save a customization
4. Click on Add to the cart > Proceed to checkout
5. In the FO > Shopping cart page > decrease the quantity of the product to 1 with the mouse and click directly on the customization
6. See error: the page is freeze

I attached a screen record
https://watch.screencastify.com/v/5POy0dRhzpwu8YhuSVQB

--------------------------------------------------------------

I have the same issue following these steps:

1. Go to FO > Choose a customized product
2. Add and save a customization
3. Click on Add to the cart > Proceed to checkout
4. In the FO > Shopping cart page > decrease/increase the quantity of the product to 1 with the mouse and click directly on the customization
5. See error: the page is freeze

I attached a screen record
https://watch.screencastify.com/v/QMwlS0twXijaRqVOywxA

Thank you!

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG,
> 
> I have a behavior following these steps:
> 
> 1. Go to FO > Choose a customized product
> 2. Add and save a customization
> 3. Click on Add to the cart > Proceed to checkout
> 4. In the FO > Shopping cart page
> 5. Set a quantity with the keyboard and press directly on Product customization
> 6. The customization is not opened, we should click on it the second time to display it
> 
> I attached a screen-record https://watch.screencastify.com/v/ThOcRIVBA2hMXGbbISjL Is it a normal behavior?
> 
> I have the same issue following these steps:
> 
> 1. Create a customized product with minimal quantity = 2
> 2. Go to FO > Choose this  product
> 3. Add and save a customization
> 4. Click on Add to the cart > Proceed to checkout
> 5. In the FO > Shopping cart page > decrease the quantity of the product to 1 with the mouse and click directly on the customization
> 6. See error: the page is freeze
> 
> I attached a screen record https://watch.screencastify.com/v/5POy0dRhzpwu8YhuSVQB
> 
> I have the same issue following these steps:
> 
> 1. Go to FO > Choose a customized product
> 2. Add and save a customization
> 3. Click on Add to the cart > Proceed to checkout
> 4. In the FO > Shopping cart page > decrease/increase the quantity of the product to 1 with the mouse and click directly on the customization
> 5. See error: the page is freeze
> 
> I attached a screen record https://watch.screencastify.com/v/QMwlS0twXijaRqVOywxA
> 
> Thank you!

Khouloud, you're not human. 

Gonna take a look

**Comment by NeOMakinG** [comment]
@khouloudbelguith now on any actions, the modal should not open at all, I prevent the default event of clicking on it because there is another action blocking this one

Opening the modal AFTER the action would be hard to maintain honestly => It would require that the product hasn't been removed (so the modal exist) and it would require to stock the past clicked element in a variable in order to show the correct modal, it's way too complicate for such a think to me.

**Review by matks — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I have an issue following these steps:

1. Go to FO > Choose a customized product
2. Add and save a customization
3. Click on Add to the cart > Proceed to checkout
4. In the FO > Shopping cart page
5. Decrease the quantity to negative quantity with the keyboard and press outside
6. Click on the customization
7. See error => customization cannot be opened

I attached a screen record
https://watch.screencastify.com/v/z2AJIuCARBdjaNNOsqKU

Thanks!

**Comment by NeOMakinG** [comment]
@khouloudbelguith It should be fine now :)

**Review by matthieu-rolland — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @NeOMakinG, when I click quickly to increase & decrease the quantity than on the product customization.
Sometimes, I'm freezed
The first screen record

https://user-images.githubusercontent.com/16067358/150803645-9503bdb2-4a86-40dc-b545-ec9c80061f02.mp4

The second screen record, it is frozen at 00:58 & 01:42

https://user-images.githubusercontent.com/16067358/150805295-1431d181-bb98-4cb3-a5d5-b1d99a215288.mp4


I tested other cases => ok

https://user-images.githubusercontent.com/16067358/150805977-6cface66-b951-40d6-a110-fc47b733c553.mp4


Thanks!

**Comment by NeOMakinG** [comment]
@khouloudbelguith It may fix it but I'm not sure at all

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @NeOMakinG

**Review by khouloudbelguith — CHANGES_REQUESTED** [review]
Hi @NeOMakinG,

I have an issue following these steps:
1. Create a customized product with required customization &another not required 
image
2. Create a cart rule that provides this product as a gift 
image
3. Go to FO > Add another product to cart & Proceed to checkout
4. In the Shopping cart => apply the cart rule 
image
5. Go to FO > Product page of the last product created
6. Try to add customization of the required field & Save
7. See error 
image

I attached a screen record

https://user-images.githubusercontent.com/16067358/154459557-e28be67f-6d10-4c97-b5a0-3876d56ddfc4.mp4

**Without PR** => ok

https://user-images.githubusercontent.com/16067358/154460106-c96300c7-9f95-4a7a-86e6-1559c45cd9d8.mp4

Thanks!

**Comment by NeOMakinG** [comment]
@khouloudbelguith this error is a PHP error, completely impossible to be related to this PR, I'll rebase, maybe it has been fixed somewhere else

**Review by atomiix — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @NeOMakinG

**Review by khouloudbelguith — APPROVED** [review]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 

On the shopping cart page, I tried 
- a customized product with minimal quantity > 1

https://user-images.githubusercontent.com/16067358/157427402-673c4b1c-4169-481c-bd6c-42898d634397.mp4

- a customized product out of stock not allowed

https://user-images.githubusercontent.com/16067358/157428080-00676c9a-fd1b-419c-868b-88132f9366a5.mp4


- this issue https://github.com/PrestaShop/PrestaShop/pull/26854#pullrequestreview-885772430 is not reproduced  anymore


https://user-images.githubusercontent.com/16067358/157428617-011fb2fb-57a5-402b-9349-4fb4e6ac127d.mp4


- Some other checks

https://user-images.githubusercontent.com/16067358/157430652-0b33fa43-e2ba-45c7-bfee-b0fc97e215fb.mp4

- I tried to add/remove some cart rules

On the checkout page, I tried to add some vouchers / remove some vouchers / select different carriers / Offer gift wrapping
Thanks!

**Comment by NeOMakinG** [comment]
@khouloudbelguith thanks a lot for testing this

**Pull request merged**
