### PR TITLE
Theme manager layout config

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by djfm** [comment]
Something seems to be broken:

1. Set a page layout for "category", e.g. "Left column"
2. Save the settings
3. Notice the change is effective by visiting a category page in front-end, also, `config/settings_1.json` is correct, that's good
4. Now go back to the layout settings in back-end

I expect:
- to see the "Left column" layout on the "category" page

I see:
- the default layout on the "category" page

**Comment by djfm** [comment]
Getting closer, but, if I add this to my `theme.yml`:

```yml
theme_settings:
  default_layout: layout-full-width
  layouts:
    category: layout-left-column
```

And then I re-install PrestaShop, the layout is not applied to the category page.

**Comment by mickaelandrieu** [comment]
> And then I re-install PrestaShop, the layout is not applied to the category page.

Did you remove the json file before re-install ?

**Comment by djfm** [comment]
Yes, I have tried again having first deleted the .json, same thing.

**Comment by djfm** [comment]
Yes, twice!

I would expect `theme.yml` to be the source of truth when calling `enable("classic")` on the theme manager, and `settings_[id_shop].json` to be the source of truth in all other cases.

Whenever the settings are update through the UI, the `settings_[id_shop].json` file should be updated.

**Comment by mickaelandrieu** [comment]
I suspect the installer to not use ``ThemeManager::getInstanceByName()`` but ``Shop::setTheme()`` :/
I check it now.

**Pull request closed without merging**
