### PR TITLE
Fix line ending

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | /
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11714)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
@PrestaShop/prestashop-core-developers No need QA. It move CRLF to LF.

**Comment by jolelievre** [comment]
@MathiasReker I think some conflicts came from the previously merge PRs

**Comment by MathiasReker** [comment]
@jolelievre fixed =)

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
thanks @MathiasReker

**Pull request merged**
