### PR TITLE
Added id_shop param to actionAfterLoadRoutes Hook

### PR DESCRIPTION
**Pull request by hherreros-webimpacto**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      | Added id_shop param to the actionAfterLoadRoutes Hook
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | -
| UI Tests          | -
| Fixed issue or discussion?     | -
| Related PRs       | -
| Sponsor company   | Webimpacto Consulting, S.L

When you use the hook actionAfterLoadRoutes to add new routes for several stores and languages, it causes that the "routes" variable of the Dispatcher get filled with several stores. 

This causes the createUrl() function of Dispatcher to not work properly to create a url for another store, since the array $this->routes[$another_shop] is not empty, it doesnt load the routes for that store.

This can be avoided if (when we use the hook actionAfterLoadRoutes) we only add routes of the id_shop that is being loaded.

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Makes sense. @Hlavtox is that a hook that you added? Do you remember when was it added? Unfortunately, as for quite a lot of new hooks, there's no documentation. [I created an Issue.](https://github.com/PrestaShop/docs/issues/1775)

**Comment by Hlavtox** [comment]
@kpodemski Yes it's this one - https://github.com/PrestaShop/PrestaShop/pull/33873, has a proper label so @thomasnares can go through it when there is time.

This PR is legit, the method is sometimes called with different shop ID than the context, so it's good for the module to know which store is being requested. We can merge this when tests are green. 👍

**Review by kpodemski — CHANGES_REQUESTED** [review]
In that case, I suggest treating this as something that we should implement into 8.1.x branch :)

@hherreros-webimpacto could you rebase it onto 8.1.x branch?

**Comment by hherreros-webimpacto** [comment]
@kpodemski im not used to do pull requests, is this ok or should I do another fork from 8.1.x and do another PR?
Thank you and happy new year :)

**Comment by Hlavtox** [comment]
@hherreros-webimpacto Hi Hugo, please make a new PR, it will be better.

Please, make sure to first create a new branch called something like `routes-hook-shop` based on 8.1.x. It's not a good practice to make PRs from your develop branch. I could theoretically rebase your `develop` branch to `8.1.x`, but it would be a mess.

**Pull request closed without merging**
