### PR TITLE
Bump phpstan/phpstan from 1.9.6 to 1.9.14

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Bump phpstan/phpstan from 1.9.6 to 1.9.14
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | The CI tests the bump of version
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

### CODE REVIEW

**Review by zuk3975 — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Comment by nicosomb** [comment]
@Progi1984 there is no automatic jobs for that?

**Comment by Progi1984** [comment]
@nicosomb No.

**Comment by Progi1984** [comment]
@nicosomb & @zuk3975 I fixed the CI in 494d2fc.

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/3965982891

**Comment by Progi1984** [comment]
@kpodemski You can restart failed jobs, plz :)

**Comment by kpodemski** [comment]
@Progi1984 still problem, this test with PDF doesn't work for a few days, the one with orders is a new one, although it's for all PRs I'm trying to test :(

**Comment by kpodemski** [comment]
@Progi1984 all good with tests after restart, only known issue with PDF test

**Comment by kpodemski** [comment]
@hibatallahAouadni auto tests are ok, do we need anything else here?

**Comment by hibatallahAouadni** [comment]
@kpodemski LGTM it's a GO!

**Comment by kpodemski** [comment]
Thanks! :)

**Pull request merged**
