### PR TITLE
Fix statistics error

### LINKED ISSUE #20921: Prestashop incorrectly collects data about user activity (window unload event is unreliable)
#### Describe the bug

Prestashop module named statsdata uses an unload event to send a POST request with data about user activity. This does not work for me since I get a 99% of 499s because web browser cannot handle the request fully.

A shop is hosted on dedicated machine with good hardware and network, it depends more on a client network speed, but the unload event may not be reliable for this purpose simply because we have multiple web browsers.

#### Expected behavior

I expect to receive a HTTP 200 response code, not a 499

1. Go to BO > Module manager page > search for the `statsdata` module and configure it.
2. Enable `Save page views for each customer`,  `Save global page views options` and save
3. Go to FO > Inspect the element > in the Network tab > Select the "Preserve log" option and reload the page
4. see an error
image

1. Go to any shop page
2. Close tab / change url
3. At this stage the unload event should be triggered
4. The web browser (brave in my case which is chrome based) have no time to handle the post request to the server, therefore server logs 499 http code

#### Additional information

```
traefik2@myserver    | <customer_ip> - - [08/Sep/2020:22:55:14 +0000] "POST /index.php?controller=statistics HTTP/2.0" 499 21 "-" "-" 5350380 "project-secured@docker" "http://<proxy_ip>:80" 14ms
traefik2@myserver    | <customer_ip> - - [08/Sep/2020:22:57:48 +0000] "POST /index.php?controller=statistics HTTP/2.0" 499 21 "-" "-" 5350974 "project-secured@docker" "http://<proxy_ip>:80" 0ms
traefik2@myserver    | <customer_ip> - - [08/Sep/2020:22:57:50 +0000] "POST /index.php?controller=statistics HTTP/2.0" 499 21 "-" "-" 5350976 "project-secured@docker" "http://<proxy_ip>:80" 0ms
```

* repository: https://github.com/PrestaShop/statsdata/blob/4de78d4c0b096f2d6768f5c96856ea8eabd8358c/statsdata.php#L127
* PrestaShop version: 1.7.7.0
* PHP version: 7.2
* Stackoverflow similar issue: https://stackoverflow.com/questions/21228349/sending-a-post-request-with-javascript-on-unload-beforeunload-is-that-possible

### PR DESCRIPTION
**Pull request by rsoulard-prolaser**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See #20921
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #20921
| How to test?      | See #20921
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26963)

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Dear @rsoulard-prolaser thank you for your contribution but it's lacks a little context 😅  you just submit the code with no explanation.

Could you please explain a bit more why adding `display()` function solves the mentioned ticket?

Here's a suggestion of what can make it a very good merge request:
☞ Context: Help maintainers be on the same page.
☞ Problem: What's wrong.
☞ Solution: Sum up your solution.
☞ Changes: Sum up the changes made.
☞ Usage: Add examples for clarity and docs.
☞ Tests: Show you're not breaking things.

Source: https://twitter.com/lorismatic/status/1469308514170556416?t=iuaOwLJk6FXfkI-HSMDBfA&s=19

**Comment by rsoulard-prolaser** [comment]
Hello @matks,

The statsdata module calls StatisticsController to record statistics in `postProcess()`
https://github.com/PrestaShop/PrestaShop/blob/09969d329e797a2fdd6caa817079e8ebe3365231/controllers/front/StatisticsController.php#L33-L47
And then continue to execute `run()`
https://github.com/PrestaShop/PrestaShop/blob/09969d329e797a2fdd6caa817079e8ebe3365231/classes/controller/Controller.php#L298-L345
Up to `display()` of FrontController
https://github.com/PrestaShop/PrestaShop/blob/09969d329e797a2fdd6caa817079e8ebe3365231/classes/controller/FrontController.php#L702-L715
$this->template is not valued in StatisticsController and generate this error:
`PHP message: PHP Fatal error:  Uncaught  --> Smarty: 0():Missing '$template' parameter <-- \n  thrown in /......../vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php on line 177`

I might have changed `postProcess()` of StatisticsController to add a die at the end. :thinking:

**Review by matks — CHANGES_REQUESTED** [review]
Hello @rsoulard-prolaser 

Now I understand. You provide an empty `display()` method so that the HTTP POST request sent against `shop.com/index.php?controller=statistics` does not crash

But it seems a bit like a hack 🤔 may I suggest something else?

`shop.com/index.php?controller=statistics` is called from the homepage, using an ajax query, right? so if we make sure PrestaShop acknowledges this is an ajax query, it will not call `display()`

I just did a test; if I call `shop.com/index.php?controller=statistics&ajax=1` then the query is correctly acknowledged as an ajax query and `display()` is not called, which is the expected behavior I guess

**Comment by rsoulard-prolaser** [comment]
Hello @matks 

You are right, the best solution is to do as @Quetzacoalt91 suggests:
https://github.com/PrestaShop/statsdata/pull/7#issuecomment-368924243

You can close this PR, I can create a new one on the statsdata module if you want.

**Comment by matks** [comment]
@rsoulard-prolaser as we both agree the solution https://github.com/PrestaShop/statsdata/pull/7 is better :D then let's do this instead.

Can you create a new PR on the statsdata module ? Dont hesitate to ping me on it

**Pull request closed without merging**
