### PR TITLE
  [-] CORE : Only link orders with same cart

### PR DESCRIPTION
**Pull request by PhpMadman**
Update of #3295

### CODE REVIEW

**Comment by PhpMadman** [comment]
Finally rebased...

**Comment by aleeks** [comment]
Hello @PhpMadman 
Can you explain more your PR please ?

**Comment by aleeks** [comment]
See with @vincentbz  ok for the concept.
PR rebase here: https://github.com/PrestaShop/PrestaShop/pull/7477

Thank you :)

**Comment by PhpMadman** [comment]
This is mostly for those of use who use a custom module to change to a numeric reference, and use multishop.
Beacuse then you have the same reference on two different orders, from two shops. And without my little update, PS will consider those brothers.

Besides that, I think it is a good thing to have. Even though it's unlikely PS will generate an non-unique reference, this makes sure that orders are not linked, when they shouldn't.

**Comment by aleeks** [comment]
Hello @PhpMadman Ok, it will be merged, it's your commit in #7477 :)

**Pull request closed without merging**
