### PR TITLE
Add travis puppeteer

### PR DESCRIPTION
**Pull request by mbadrani**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This is the first travis file for puppeteer, not yet triggered by the main travis file.
| Type?         | refacto
| Category?     | TE
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | no
| How to test?  | set-up the trigger on the main travis.yml on the main prestashop/.travis.yml

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14726)

### CODE REVIEW

**Comment by matks** [comment]
Hi @mbadrani I think something went wrong with your PR.
I rebuilt it here: https://github.com/PrestaShop/PrestaShop/pull/14728 is that correct ?

**Comment by matks** [comment]
@mbadrani If I understand correctly, you want to add the `tests/puppeteer/.travis.yml` file
but this file is not read by Travis as it is in a sub-folder.
That's why you said `set-up the trigger on the main travis.yml on the main prestashop/.travis.yml`

How do you plan to do it ?

**Comment by mbadrani** [comment]
Yes I've seen that, I suggest adding the trigger in a second PR when you gave me some feedbacks about this first .travis.yml file

**Comment by mbadrani** [comment]
ok for me https://github.com/PrestaShop/PrestaShop/pull/14728

**Comment by matks** [comment]
I'm not sure

**Pull request closed without merging**
