### PR TITLE
Remove high DPI images functionality

### LINKED ISSUE #26886: Deprecate HighDPI images
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

I think that there is now a lot more to images - **srcsets**, than just a simple 2x resolution images. If 2x images are needed, they can be easily made by creating another image thumbnail size, but much better solution is to have several dimensions for usage on different resolutions.

### Describe the solution you'd like

Deprecate HighDPI images and all functionality joined together. We can make something much better in the new theme.

Ping @NeOMakinG

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes functionality of generating high DPI images. Sourcesets handle this.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | See that thumbnail generation works fine.
| Fixed ticket?     | Fixes #26886
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
CS Fixer is not happy, otherwise LGTM.

**Review by kpodemski — DISMISSED** [review]
It is a BC Break, but I'm ok with this as the feature is no longer used or needed.

**Review by kpodemski — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Automated tests are OK : https://github.com/florine2623/testing_pr/actions/runs/5209702414

Tested all generation of thumbnails with edited/non-edited Image settings.

Screenshot 2023-06-08 at 14 40 26

It works well. Checked on the FO, all images are still available.

Screenshot 2023-06-08 at 14 42 21

It is QA ✅ 
Thanks!

**Comment by nicosomb** [comment]
Thank you @Hlavtox !

**Pull request merged**
