### PR TITLE
[+] FO : Use default state for tax purposes

### PR DESCRIPTION
**Pull request by cedricfontaine**
In Canada and US, it's better to apply local state tax if needed.

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by cedricfontaine** [comment]
Still needed for country with Country / State taxes.

**Comment by xBorderie** [comment]
Hey @cedricfontaine , thank you for your feedback!

Sadly, since this PR was made on the `1.6` branch (which is not used anymore), could you make it again on the `1.6.1.x` branch so that you get full credit once we merge it? Even better if you do it on the `develop` branch, so that it lands in PS 1.7 :)

Thank you very much!

**Comment by cedricfontaine** [comment]
Ok done with #4415

**Comment by xBorderie** [comment]
Great, thanks a lot! I'm closing this PR for the 1.6 branch.

**Comment by tiger442** [comment]
It doesn't seam to work on 1.6.1.7

**Comment by xBorderie** [comment]
@tiger442 Could you give more details [in a Forge ticket](http://forge.prestashop.com/)? Thank you!

**Comment by cedricfontaine** [comment]
Problem is that in Product::getPriceStatic you initialize the adress in the function rather than using Address::initialize. So pastch should be applied to this function also. I do think that Address::initialize should be used in the function.

**Comment by xBorderie** [comment]
@cedricfontaine Would you be willing to make a further PR?

**Comment by cedricfontaine** [comment]
Ok #6931

**Pull request closed without merging**
