### PR TITLE
Add "quick_view" block to classic theme

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add the quick_view block to classic theme to let us modify the content easily with a extends of the source template.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Try to change the source content of this block.

### CODE REVIEW

**Review by PrestaEdit — APPROVED** [review]

**Comment by aleeks** [comment]
Hello @prestamodule 
could you report it on starterTheme please!
Thank you!

**Comment by PrestaEdit** [comment]
Hi @aleeks ,

Was done here: https://github.com/PrestaShop/StarterTheme/pull/160

**Comment by julienbourdeau** [comment]
Hi,

Please make sure your indent is correct. And if you want to modify the style of Classic, please add a screenshot. It helps a lot ;)

I'll merge it on StarterTheme and we'll see if this makes it into Classic.

**Comment by PrestaEdit** [comment]
Hi @julienbourdeau ,

Sorry about the indent.

There is no screenshot to have as you will see the same as before: is just a encapsuled block as you will add a <div>...</div> on a element.

It will allow the child template to change the content of the block, the goal is not to change it before :)

**Comment by julienbourdeau** [comment]
Oh yeah sorry! I didnt realize, let's say I was tired yesterday ^^

Thanks!

**Pull request merged**
