### PR TITLE
Bo rtl stylesheets

### PR DESCRIPTION
**Pull request by molka**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | rtl
| Description?  | When you change the Arabic language, you can see that almost all blocks are displayed on the wrong way. This PR fix the default and new theme style.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Go to BO and switch to Arabic language

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @molka,

Thanks for your contribution.
We've created a dedicated branch for the RTL. I changed the target branch of your pull request, so it needs a little rebase. Could you do it, please?

Thanks

**Comment by molka** [comment]
Hello @maximebiloe ,

When I rebase it to the rtl branch I get "Everything up-to-date"
Any idea how to fix it?

Thanks!

**Comment by maximebiloe** [comment]
Are you rebasing on top of your `rtl` local branch? It you do that, you need to update it from the remote.

**Comment by molka** [comment]
Hello @maximebiloe ,
Done, thanks!

**Comment by maximebiloe** [comment]
Hello @molka,

Thanks for your contribution.
As we choose another method (more details here: http://build.prestashop.com/news/PrestaShop-RTL-project-update), I close this PR.

Regards

**Pull request closed without merging**
