### PR TITLE
Improvement: displaying header toolbar on mobile

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In mobile version: The plus (+) button is not rendered if there is only the help button present in the toolbar as well as if there is no button. Moreover, if the help button is the only one present in the toolbar, it will remain displayed at the top but in material icon and will no longer make a line break.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | navigate in any page on BO with just help button on toolbar and resize to be on mobile ⇒ the help button persist, and the (+) button is not shown. If you navigate to other page with much button, you can see the toolbar disappears and the (+) button is rendered.
| Fixed ticket?     | Linked to the discussion #32151
| Sponsor company   | @PrestaShopCorp

image
image

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by 0x346e3730 — DISMISSED** [review]

**Comment by MhiriFaten** [comment]
Hello, @ga-devfront ,

Some checks were not successful, could you check it please ?
I will remove the `waiting for QA` label

**Comment by ga-devfront** [comment]
> Hello, @ga-devfront ,
> 
> Some checks were not successful, could you check it please ? I will remove the `waiting for QA` label

I would like to fix it but in local I haven't the error and don't understand the problem then I check the file ...

**Review by kpodemski — DISMISSED** [review]

**Comment by ga-devfront** [comment]
> Hello, @ga-devfront ,
> 
> Some checks were not successful, could you check it please ? I will remove the `waiting for QA` label

It's fixed

**Review by MatShir — CHANGES_REQUESTED** [review]
Small update on the UI https://github.com/PrestaShop/PrestaShop/discussions/32151#discussioncomment-5612919 :)
Could you take them into account? 🤗

**Comment by ga-devfront** [comment]
I just updated the help button to used material icon on mobile according to this discussion : https://github.com/PrestaShop/PrestaShop/discussions/32151
That's the new preview.
image

**Review by MatShir — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @ga-devfront ,

I have checked your PR and LGTM !
It is QA approved :heavy_check_mark: 

Thank you.

**Comment by kpodemski** [comment]
thank you @ga-devfront :)

**Pull request merged**
