### PR TITLE
Removed deprecated method `isAnything` in class `Validate`

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed deprecated method `isAnything` in class `Validate`
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4512067965
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

## BC Breaks
* Removed method `isAnything` in class `Validate`

### CODE REVIEW

**Comment by Progi1984** [comment]
@PrestaShop/committers /@PrestaShop/prestashop-maintainers Open to review

**Review by nicosomb — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Comment by kpodemski** [comment]
Hi @Progi1984 

I don't think there's a need for QA in such PRs if you run auto-tests and CI is green. We could think of having QA where you remove some more methods or widely used ones.

**Comment by Progi1984** [comment]
@kpodemski Let the @PrestaShop/qa-functional decide 😉. It's their scope.

**Comment by HanaRebaiQA** [comment]
Hello @kpodemski 

@florine2623 is on this PR. She will give her feedback following the check of the automated tests.

**Review by florine2623 — APPROVED** [review]
Hello @Progi1984 @kpodemski @HanaRebaiQA ,

Thanks for the automated tests @Progi1984 .

Tested the following :
- Upload a theme, check the FO
- Upload a module, check the configure page
- Test the purchase of a product with a fake payment method and a fake delivery method in the default theme
- Login in the BO then open the product list
- Creation of a product

It is QA ✅ 
Thanks!

**Pull request merged**
