### PR TITLE
Product reference is now available in blockbestsellers module

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Reference is now available in blockbestsellers.tpl etc. |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | maybe ;) |
| How to test? | Try to use `$product.reference` now and after commit |
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi,

Should it appear in FO when I display the blockbestsellers ?

**Comment by xBorderie** [comment]
@vincentbz I think it's more of a question of the product's reference being available as a PHP/Smarty value for blockbestsellers module. But it doesn't use it yet, right @kpodemski ?

**Comment by xBorderie** [comment]
Please note that 1.6.1.x is not supposed to accepted enhancements anymore, only bugfixes. But since this doesn't seem to break backward compatibility, maybe the the developers can accept it.

**Comment by kpodemski** [comment]
Hi guys,

{$product.reference} is not available if we want to use it and we need to make override for it, I've created override for this in many of my projects so I think it is a good addition, and as this is micro change and 100% working and backward compatible I hope it will be accepted.

**Comment by kpodemski** [comment]
Pink @xBorderie

**Comment by xBorderie** [comment]
Well, @maximebiloe does want us to cover one of her songs (once we revive the PrestaBand) :)

**Comment by maximebiloe** [comment]
🎤

**Comment by kpodemski** [comment]
Hahaha, autocorrection lol

**Comment by kpodemski** [comment]
@xBorderie @Shudrum what we're doing with this PR?

**Comment by aleeks** [comment]
Hello,
It will be on next 1.6. Thank you @kpodemski 
Do you want cherry-pick on 1.7 ?

**Comment by maximebiloe** [comment]
Thank you @kpodemski

**Pull request merged**
