### PR TITLE
Fix(merchandise-return): deprecation alert is displayed on the return form

### LINKED ISSUE #35362: Merchandise returns pdf file - a deprecation alert is displayed on the return form
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When a customer request a return, when I change the status of the return, the return form is available.
When I click on it, I have the return form with a warning on it.

Screenshot 2024-02-14 at 17 32 24

`Deprecated: Using php-function "sprintf" as a modifier is deprecated and will be removed in a future release. Use Smarty::registerPlugin to explicitly register a custom modifier. in /develop/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php on line 114`

It is only displayed one time. When I download this file another time, the warning is not displayed anymore.

### Expected behavior

Should not display the deprecation warning

### Steps to reproduce

1. Go to BO > Enable merchandise return
2. Log into your customer account > Make an order
3. Go back to BO > Change status of latest order made to Delivered
4. Go to your customer account > Order history and details > Details > Scroll down to Product section
5. Select the product you want to return > Request a return
6. Go to BO > Customer Service > Merchandise return > Click on the latest merchandise return
7. Change status to Waiting for package
8. Click on Print out button
9. See Deprecation displayed in PDF :x:

### PrestaShop version(s) where the bug happened

8.1.x, 9.0.x

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by TheoAlloin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | See [related issue](https://github.com/PrestaShop/PrestaShop/issues/35362) description
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| UI Tests     | https://github.com/florine2623/testing_pr/actions/runs/8283185085
| How to test?      | See [related issue](https://github.com/PrestaShop/PrestaShop/issues/35362) description
| Fixed issue or discussion?     | Fixes #35362
| Sponsor company   | Softizy

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
Good catch. :-)

However, there is one other way, maybe we should register it as an allowed smarty modifier? https://github.com/PrestaShop/PrestaShop/blob/8.1.x/config/smarty.config.inc.php

Ping @PrestaShop/tech-council

**Comment by TheoAlloin** [comment]
Thanks 😁 But it's more thanks to the issue reporter !

TBH I'm not a fan of template calculation (via smarty modifier or other ways). 

Maybe should I migrate the displayed return number directly in the related controller ? What do you think?

**Review by matthieu-rolland — APPROVED** [review]

**Comment by florine2623** [comment]
@PrestaShop/tech-council can this PR be tested like this ?
Or do we need to take in account the comments by @Hlavtox and @TheoAlloin ?

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @TheoAlloin ,

I see 2 approvals so it is testable !

Thanks for the fix, I don't have any deprecation message anymore.

The PDF file is downloadable and is clean.
Screenshot 2024-03-14 at 16 24 30

Thanks!

**Comment by Hlavtox** [comment]
We can merge this one, but after discussion with @jolelievre, we will also add it to the allowed modifiers list. :-)

**Pull request merged**
