### PR TITLE
[*] MO : Blocklanguages add hreflang and rel alternate to the links for a better SEO and avoid duplicate content

### PR DESCRIPTION
**Pull request by cgordenne**
This PR is linked with : https://github.com/PrestaShop/blocklanguages/pull/5

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

thank you for your PR. Can you please add $language.iso_code|escape:'html':'UTF-8', i rather see it escaped.

**Comment by gRoussac** [comment]
Hi,

Sorry about this, can you please this PR and open it again but on '1.6.1.x' branch please ?

Regards

**Comment by cgordenne** [comment]
Hi,

No problem, here is my new PR : #4012 

Regards

**Comment by gRoussac** [comment]
:muscle:

**Pull request closed without merging**
