### PR TITLE
Add params to actionValidateOrderBefore

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add some params to hook call and allow to change OrderState ID if needed
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello 

Can we have a How to test please :)

https://github.com/paulnoelcholot/testing_pr/actions/runs/7899132661/workflow CI = :green_circle:

**Comment by paulnoelcholot** [comment]
@PrestaShop/product-council

**Comment by kpodemski** [comment]
@paulnoelcholot as far as I remember QA has a module to test hooks, you could dump these extra params there

**Comment by paulnoelcholot** [comment]
Hello @PrestaEdit,

I tested your PR and it's good for me! :tada: 

Thanks!

image

**Review by paulnoelcholot — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PrestaEdit

**Pull request merged**
