### PR TITLE
[-] Split css for IE9, header : add css for IE9 < only

### PR DESCRIPTION
**Pull request by kelu95**

### CODE REVIEW

**Comment by xBorderie** [comment]
Rework of #3223. Thanks @kelu95 !

**Comment by kpodemski** [comment]
@xBorderie what about this? when it will be merged?

**Comment by xBorderie** [comment]
@kpodemski The team is currently 100% dedicated to releasing the first beta of PrestaShop 1.7 on the coming weeks, and sadly that means that pull-requests will have to wait a bit more. 

The whole situation is not easy, because we want to release a new 1.6.1.x version (plenty of material for that), but the only priority is 1.7 beta 1 right. PRs are not forgotten though, and be assured that we'll get back to them very soon! 

Thank you for your patience.

**Comment by vTerenti** [comment]
QA OK

**Comment by xBorderie** [comment]
Nice!

**Pull request merged**
