### PR TITLE
Upgraded symfony package

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Upgrades to symfony 4.4.50
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | PrestaShop

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @nicosomb

**Comment by jolelievre** [comment]
Tests should be green here https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4076225973
(minus some tests that have been identified as failing currently and need to be fixed, not blocking then)

**Comment by eternoendless** [comment]
There are three failing tests @jolelievre 

Screenshot 2023-02-06 at 15 07 52

**Comment by kpodemski** [comment]
I guess that it has to be rebased on 8.0.2.

@matks @atomiix could probably confirm.

**Review by mflasquin — COMMENTED** [review]
@lartist create new PR targetting 8.1 https://github.com/PrestaShop/PrestaShop/pull/31236 because since this version, the Symfony version is also fixed in the composer.json. I think we can close this in favor of lartist's PR.

**Pull request closed without merging**
