### PR TITLE
Fix product description lists color on FO

### LINKED ISSUE #23064: error color text in product description
#### Describe the bug

when I activate the bullet list the text color changes in the classic theme

#### Expected behavior

same colour

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Edit your product
3. Add a bullet list to your product's summary
4. **Save**
5. Click on **Preview**
6. FO, you can see the bullet list in product page with different color

**Screenshots**

image

#### Additional information

* PrestaShop version:1.7.7.0
* PHP version: 7.2.29

### LINKED ISSUE #23065: error showing description listed in product quick view
#### Describe the bug

When I put a bullet list in the description of an article, it is not shown if I open the quick view of the product
See the video

#### Expected behavior

if I open the quick view of the product, I can see the bullet list in the description of an article

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Edit your product
3. Add a bullet list to your product's summary
4. **Save**
5. Click on **Preview**
6. FO, you can see the bullet list in product page
7. Go to **Category** page and click on **quick view** link
8. See error => the bullit list is not displayed

**Screenshots**

https://youtu.be/nY7uM-RmAwQ

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.29

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Image descriptions lists are black instead of grey (like the whole product page)
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23064.
| How to test?      | Add a list in a product description, go to the product page and see if the color is grey instead of black (see issue for reference)
| Possible impacts? | Product page color of description

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23073)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by alfonsolr09** [comment]
why was this change not made in theme.css ??

**Comment by SD1982** [comment]
Hi @NeOMakinG 
With your PR if i have a bullet list and a numbered list , the numbered list appear as a bullet list (see screenrecord)
**Without PR**
one item by list
https://drive.google.com/file/d/1oCzQUJRD01fGJkoTIj2TAWZf55jgn00z/view?usp=sharing
two items by list
https://drive.google.com/file/d/1feetbh1ppU7y1Z71ncgJqw4W3mmlMKxQ/view?usp=sharing
**With PR applied**
one item by list
https://drive.google.com/file/d/1rqoOMlPW-0PJ2_38zFcn4rBjTR_TPCyN/view?usp=sharing
two items by list
https://drive.google.com/file/d/1TIiQyRvXu03M-VVbz24mB-UTgrC1UPjW/view?usp=sharing

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG
> With your PR if i have a bullet list and a numbered list , the numbered list appear as a bullet list (see screenrecord)
> **Without PR**
> one item by list
> https://drive.google.com/file/d/1oCzQUJRD01fGJkoTIj2TAWZf55jgn00z/view?usp=sharing
> two items by list
> https://drive.google.com/file/d/1feetbh1ppU7y1Z71ncgJqw4W3mmlMKxQ/view?usp=sharing
> **With PR applied**
> one item by list
> https://drive.google.com/file/d/1rqoOMlPW-0PJ2_38zFcn4rBjTR_TPCyN/view?usp=sharing
> two items by list
> https://drive.google.com/file/d/1TIiQyRvXu03M-VVbz24mB-UTgrC1UPjW/view?usp=sharing

Ok. thanks for testing, gonna check this, strange thing as I tested with every lists at the same time!

**Comment by NeOMakinG** [comment]
> why was this change not made in theme.css ??

https://github.com/PrestaShop/PrestaShop/pull/23074#issuecomment-771467018

See this for reference..

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
Seems Ok now
image
Thanks @NeOMakinG !!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @SD1982

**Pull request merged**
