### PR TITLE
Fix cover update by WebService

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | For some reasone bugfix from https://github.com/PrestaShop/PrestaShop/commit/2f165db08aeec2fa6899ee6cc380a9b027e44c77 was not available on 1.6.1.x |
| Type? | bug fix |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-6461 |
| How to test? | Try to update product within a cover via WS |
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by kpodemski** [comment]
Done

**Comment by kpodemski** [comment]
@xBorderie i suggest to move it to 1.6.1.7 as this fix is already on `develop` and somehow not available on 1.6 branch

**Comment by xBorderie** [comment]
Nicely spotted, thanks!

**Comment by firstred** [comment]
Status: Code reviewed

**Comment by maximebiloe** [comment]
Thanks @kpodemski!

**Pull request merged**
