### PR TITLE
Do not use raw in DataColumn

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Never use raw in DataColumn, create a new column if needed.
| Type?         | bug fix
| Category?     |  BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Can be done by a dev. Tests are Green.

image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22403)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]
@PierreRambaud Can you provide a little more insights about "how to test" ? 😅  I have no idea how to create an "unofficial" currency.

**Comment by boubkerbribri** [comment]
@matks to create unofficial currency, you need to check 'Create an alternative currency' checkbox and fill currency attributes yourself.
image

**Review by jolelievre — APPROVED** [review]
Nice job @PierreRambaud !

**Comment by NeOMakinG** [comment]
Hey

Custom currency : 
image

Edited currency : 
image

Thanks @PierreRambaud

**Pull request merged**
