### PR TITLE
[-] BO : Fix tree issue

### PR DESCRIPTION
**Pull request by jocel1**

### CODE REVIEW

**Comment by alexsegura** [comment]
:+1: 

I was going to open a pull request for more or less the same issue: the tree "auto-submits" when a radio input is used, and there is also this crazy `if (name != 'id_parent')` which I can't understand. 

However, IMHO we could have a better solution than another global variable. 
We should be able to manage this via an option passed when the tree is initialized. 

What do you think ?

**Comment by jocel1** [comment]
Hi!

It's a bit tricky because tree_categories.tpl is the default template, and it should feature the "auto-submits" on  radio input. We want to have existing modules still working properly, without having to modify the tree init.

**Comment by alexsegura** [comment]
And?

The value of the option would be true by default, as you did. 
I'm just saying that global variables should be avoided. 

BTW, do you know in which case the name of the inputs is `id_parent` ? I've searched the whole codebase but can't find anything initializing the Helper with this value.

**Comment by jocel1** [comment]
Sure, try to create a new category for example (in the code, it's in AdminCategoriesController.php line 476)

**Comment by jocel1** [comment]
As for the redir I'll do a few tests, I have an idea for a better implementation.

**Comment by jocel1** [comment]
I've push a new fix. Unfortunately I was not able to remove the global declaration, but at least I feel it's cleaner now. 
Initially I wanted to be able to get the attached function on the click handler (doing a 
var treeClickFunc = this.$element.parent().find('ul.tree input').first().click; 
in the init of tree.js), and then use it on 
this.$element.find(":input[type=radio]").click(treeClickFunc);
without having to declare it in the tpl, but it seems it doesn't work. (if you think it's possible, any help would be appreciated ;) )

**Comment by alexsegura** [comment]
Hum IMHO it's event more complicated to declare the callback in the template.

In my mind it would look like:

```javascript
$('#{$id|escape:'html':'UTF-8'}').tree('init', {
  autoSubmit: false
});
```

But from what I see this won't work: `init` call won't pass the options to the object. 
Actually the code does not respect the standard way of creating a jQuery plugin. 
It should be initialized like this:

```javascript
$('#{$id|escape:'html':'UTF-8'}').tree({
  autoSubmit: false
});
```

Then, `this.options` would contain the `autoSubmit` key. 
We would still need to manage the default options (`$.fn.tree.defaults`), and to change the way the plugin is initialized in templates. 

In the current implementation there is in fact no way to pass the options, even if it looks like it's implemented.

**Comment by jocel1** [comment]
I think declaring the callback in the template is the best place, since a module could want to be able to customize this behaviour as well.

**Comment by alexsegura** [comment]
Then it should be an option: 

```javascript
$('#{$id|escape:'html':'UTF-8'}').tree({
  onRadioClick: function(e) {
    // Do something when a radio input is clicked
  }
});
```

By default, the `onRadioClick` option would refresh the page as it is implemented right now. 

Also, if we expose a method to change options at runtime, modules could customize this behavior as you say:

```javascript
$('#{$id|escape:'html':'UTF-8'}').tree('option', 'onRadioClick', function(e) {});
```

I think I'll make another PR, I have it very clear.

**Comment by jocel1** [comment]
Actually it would be awesome if your implementation could be more generic, i.e. not restricted to onradioclick.
For example :

onclick: function(selector, e) {

},
onchange: function(selector, e) {

}
(an any kind of event supported by "on()")

**Comment by jeromenadaud** [comment]
reported on 1.6.1.x with : #3413

**Comment by alexsegura** [comment]
Hum, I don't understand what happened here...

Did you read my comments ? 
This is not really satisfying: to avoid auto submit when using radio inputs, one still needs to rewrite the whole 'tree_associated_categories.tpl' file, no ?

**Comment by jocel1** [comment]
yes, but it was working like that before the changes on the tree implementation done in the 1.6.1.0 release : 

https://github.com/PrestaShop/PrestaShop/blob/1.6.0.14/admin-dev/themes/default/template/controllers/products/helpers/tree/tree_associated_categories.tpl

(see the 

$('#{$id|escape:'html':'UTF-8'}').find(':input[type=radio]').click(function(){
			location.href = location.href.replace(/&id_category=[0-9]*/, '') + '&id_category=' + $(this).val();
		}); 

code).

So the purpose of this PR was to implement the same behaviour as before, but we a slightly improved implementation. Anyway, it's the TPL (which can be overloaded easily) which should control this behaviour.

**Comment by alexsegura** [comment]
Okay.

**Comment by jocel1** [comment]
but feel free to make another PR, as you were suggesting, if you want to improve the current behaviour :)

Thanks!

**Pull request closed without merging**
