### PR TITLE
Allow HTML in notifications

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | we may want to add links or formatting into the notifications
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3033
| How to test?  | delete all your addresses, go to "Addresses" page, you will see a notification with the link inside, unfortunately before this change link is not properly displayed because of sanitization
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by kpodemski** [comment]
I'll cherry pick to StarterTheme after merge here, i'm waiting for your feedback about this one :)

**Comment by xBorderie** [comment]
Isn't there some security implication? @rGaillard ?

**Comment by kpodemski** [comment]
Why? Errors are created via controllers

**Comment by Quetzacoalt91** [comment]
@rGaillard, I guess no answer means that everything is okay? :upside_down_face:

**Comment by kpodemski** [comment]
Three months, uhhh, back to normal i see

**Comment by Quetzacoalt91** [comment]
Yeah, sorry about that, we lost your PR when it went in the second page of the list. :stuck_out_tongue: 

Let's go with it.

**Pull request merged**
