### PR TITLE
Add revocation and privacy terms to checkout

### LINKED ISSUE #28556: FancyBox not showing up at checkout
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When clicking on terms during checkout at "I agree to the [terms of service] and [revocation terms] and will adhere to them unconditionally.", nothing happens.

Google Chrome shows me this warning, is it related to FancyBox not opening?
> A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

### Expected behavior

FancyBox opening

### Steps to reproduce

1. Put an item in basket
2. Go to checkout
3. Fill out address etc
4. In Step 4, click on terms of service

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by doeselschnecke**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | During checkout, customers do not have to agree to revocation terms or privacy policies. This is required by most local laws worldwide and used to be added by ps_legalcompliance module. However, this module is not maintained any longer. It lacked support for privacy policy implementation and breaks FancyBox functionality. This is a simple patch without modules or overrides and only requires two additional SQL entries. 
| Tested on | 1.7.8.6, Safari+Chrome
| Type?             | improvement
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28556 
| Related PRs       | none
| How to test?      | Go to checkout and click on terms, privacy policy, revocation terms to open FancyBox showing them
| Possible impacts? | Translations for other languages than english need to be done.

Result:
Screenshot 2022-05-21 at 15 51 35

### CODE REVIEW

**Comment by doeselschnecke** [comment]
I am not sure about the (int) in ConditionsToApproveFinder.php that was merged in February to develop branch ([#26913](https://github.com/PrestaShop/PrestaShop/pull/26913))

Apparently this additional (int) is only for testing with PHPStan.

However, with that (int) one test fails.
Screenshot 2022-05-21 at 16 10 06


In 1.7.8.6 the code is working without (int)

**Review by matthieu-rolland — COMMENTED** [review]
CS fixer is not happy, you can fix it by running this command from the root of your project:

`./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix classes/checkout/ConditionsToApproveFinder.php`

then commit the modification 

About your PR:

It looks good to me, I pinged the product team in your issue to get their opinion, I'm waiting for their approval before approving your PR 👍

**Comment by doeselschnecke** [comment]
> CS fixer is not happy, you can fix it by running this command from the root of your project:
> 
> `./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix classes/checkout/ConditionsToApproveFinder.php`
> 
> then commit the modification
> 
> About your PR:
> 
> It looks good to me, I pinged the product team in your issue to get their opinion, I'm waiting for their approval before approving your PR 👍

Thank you for the help. Running CS Fixer on Github seems to be unnecessarily complicated. In the ./vendor folder on the branch develop is no file despite an .htaccess? So I've run PHP CS Fixer locally and updated the file manually.

However, now YAML Test complains about the php-cs-fixer file I created on GitHub. Sheesh. Why is GitHub so weird? Using git in command-line is billion times more understandable and not every commit gets automatically pushed..

**Comment by Progi1984** [comment]
The issue #28556 waits for the @PrestaShop/product-team.

**Comment by Hlavtox** [comment]
Hi @doeselschnecke, these custom terms of service are very specific to your country and for example nothing like this is required in Czech republic.

We recentely added a new hook that will allow you to hook your custom conditions here - https://github.com/PrestaShop/PrestaShop/pull/27437

**Comment by kpodemski** [comment]
Hello @doeselschnecke 

Do you think the hook mentioned by @Hlavtox could solve your issue?

**Comment by doeselschnecke** [comment]
> Hello @doeselschnecke
> 
> Do you think the hook mentioned by @Hlavtox could solve your issue?

I think it definitely could! Do you know in which PS Version the commit was introduced? I only see that it got merged into develop, but not which PS Version has this feature. It’s probably in 8.0.0?

**Comment by matks** [comment]
> #27437

https://github.com/PrestaShop/PrestaShop/pull/27437 PR was merged in PrestaShop 8.0.0

I close the PR as it seems it is not needed 👍 . The hook will allow you to customize PrestaShop for your country laws

**Pull request closed without merging**
