### PR TITLE
Add missing licence 

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Add missing licence
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No code is modified, no QA needed
| Fixed ticket?     | 
| Related PRs       | none
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by PrestaEdit** [comment]
And... 
Capture d’écran 2023-03-02 à 09 50 51

No blocking rules about merging pull requests until CI is not green ? 🤔

**Comment by kpodemski** [comment]
@PrestaEdit, you know the answer, so why ask?

**Comment by PrestaEdit** [comment]
I'm not on the organization, so, as a lot of other things, no, I don't know.
You seems to know everyone, and everything of others peoples knows. Good to know, there.

I'm asking to know, to discuss about this possibility, to know what happend. I'm a contributor of this project, you know, so I'm interrested in the good but also bad things that could happend here and try to solve them, on my way.

I'm asking as like a the label bot, maybe sometimes it could be something else. But you know that, too, of course :)

It's surely something difficult to understand, maybe.

**Comment by matthieu-rolland** [comment]
Actually I'm not sure how @Hlavtox managed to bypass the CI... but I told him yesterday so now he knows

You're not wrong @PrestaEdit,

actually this PR being merged without CI caused me an unexplained cs-fixer issue in another PR :D

**Comment by Hlavtox** [comment]
@PrestaEdit I fucked it up, the button was available and I thought "What could go wrong with adding a license on top of a file".

**Comment by matthieu-rolland** [comment]
No big deal @Hlavtox, don't worry... 

I wonder how the merge button was available, probably a bug from GitHub ...

**Comment by PrestaEdit** [comment]
@Hlavtox I can understand, yes ! :-/

It's not against you - or even against someone, ... - more to know what could be done to avoid that further :)

**Comment by kpodemski** [comment]
GitHub acted strange that day. Normally the button is blocked. CI has to be green. It was always like that, and nothing has changed.

**Pull request merged**
