### PR TITLE
Replaced text input by select input for page name in Meta page 

### PR DESCRIPTION
**Pull request by antho-girard**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This PR replaces text input by select input for the page name field, same as PS 1.6 |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1074 |
| How to test? | In BO > Shop Parameters > Traffic, add a new page. The select list should contain available pages. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by AlexEven** [comment]
Hello @antho-girard,

Thanks for this!

I have two remarks.

1. Domains for translation should have 3 levels, not 2 like you proposed here (Admin.Parameters).
You should use "Admin.Parameters.Feature" here I believe.

If you add some help text (hint/ desc), domain should be Admin.Parameters.Help
If you add some errors or warnings, domain should be Admin.Parameters.Notification.

You'll find more info about this on this article, and don't hesitate to ask if you have a question!
http://build.prestashop.com/news/new-translation-system-prestashop-17/#domains-structure

2. Could you please use "Module pages" instead of "Modules pages"?

Thank you!

**Comment by antho-girard** [comment]
Hello @AlexEven,

Thanks for your feedback!
Wording & translation domains should be ok now.

**Comment by AlexEven** [comment]
Wonderful, thank you! :)

**Comment by xBorderie** [comment]
Great, thanks @antho-girard !

**Comment by vincentbz** [comment]
Great, thanks !

status : 'QA approved'

**Comment by xBorderie** [comment]
\o/

**Pull request merged**
