### PR TITLE
Hide default spin buttons for input number

### LINKED ISSUE #26796: [BO] Bad display of the Edit quantity field in Stock page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

There is a CSS rule for replacing native up and down arrows in Edit quantity field. But the native arrows doesn't hide and when user hover mouse pointer upon field, both of them will be shown.

**Blur mode:**

**Hover mode:**

### Expected behavior

**Blur mode:**

**Hover mode:**

### Steps to reproduce

Go to BO > Catalog > Stock

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mparvazi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Hide default spin buttons for input number.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26796
| How to test?      | Go to BO > Catalog > Stock
| Possible impacts? | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27257)

### CODE REVIEW

**Comment by mparvazi** [comment]
Ref: https://www.w3schools.com/howto/howto_css_hide_arrow_number.asp

**Review by NeOMakinG — DISMISSED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @mparvazi ,

Thanks for the PR, it is QA ✅ !

**Review by Progi1984 — CHANGES_REQUESTED** [review]
WAIT FOR 1783 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @mparvazi & @florine2623

**Pull request merged**
