### PR TITLE
Add hook to get a customized id zone for an id_address

### PR DESCRIPTION
**Pull request by guestisp**
This PR add a new hook called `actionGetZoneById` usefull to alter the default behaviours, for example to change the shipping zone based on zip code coming from id_address

### CODE REVIEW

**Comment by guestisp** [comment]
Please merge this PR or #2405 we absolutely need one of these, in Italy is impossible to set proper shipping cost for certain locations without these PR.

It's a simple hook.

**Comment by guestisp** [comment]
Here you can see a thread asking for ZIP support:
https://www.prestashop.com/forums/topic/254876-localita-disagiate-cap-non-provincia/

many other thread on PS forum asking for this, please merge this or (better) #2405

**Comment by guestisp** [comment]
@gRoussac can you please merge? We can't properly set shipping prices for Italy, without this PR or #2405.
The only way is to override `actionGetZoneById` and is not a good solution.

This PR is just a new hook call, very easy.

**Comment by guestisp** [comment]
News on this ?

**Comment by guestisp** [comment]
I know you are planning postcodes support for 2015 but in the meantime please add this hook.
We can't use Prestashop in Italy without loosing money on every shipment.
ALL carriers in italy has prices based on postcodes and this support is missing in Prestashop, thus we loose money every time a ship is made to every hard-to-reach location (like small town on mountains and so on)

**Comment by guestisp** [comment]
news?

**Comment by guestisp** [comment]
Up

**Comment by guestisp** [comment]
Please merge. We need this in Italy, we can't ship.

**Comment by guestisp** [comment]
Please merge. I really don't understand why don't you merge a very simple hook that would solve all major shipping issues for Italy. Really, I don't understand.........

**Comment by guestisp** [comment]
This is totally non-sense. A big issue for all italian customers, fixed by this single hook, is still unmerged without any reason.

**Comment by guestisp** [comment]
Please add this hook......

**Comment by guestisp** [comment]
bump...

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, please check this next time:

http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message
http://doc.prestashop.com/display/PS16/Coding+Standards

Best regards.

**Comment by guestisp** [comment]
Thank you very much!

**Comment by djfm** [comment]
I think there is an issue if there are 2 or modules hooked on this hook, because if I understand correctly the code in `Hook::exec`, the output of `Hook::exec` will in this case be a concatenation of `id_zone`s which is probably not what you expect :)

**Pull request merged**
