### PR TITLE
Refacto ThemeCatalogController to use annotations

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Refactor Controller to use latest conventions about annotations
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |  Page "Improve > Design > Themes Catalog" should behave like before, **especially access rules**. This Controller controls themes shown by Addons.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12077)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by mbadrani** [comment]
@matks Fatal error 500 on your PR in import page 
image

**Comment by mbadrani** [comment]
@matks need rebase to fix the import page (error 500)

**Comment by Quetzacoalt91** [comment]
FYI a rebase is only needed when we need to retrieve the latest changes before reapplying the new commits (in case of conflicts or when we need to use another base branch).

When new changes must be brought, this task is not needed.

**Comment by mbadrani** [comment]
Mathieu need to rebase @Quetzacoalt91 if you want more context please ask @matks

**Comment by Quetzacoalt91** [comment]
Actually YOU will need to rebase as soon as the other fix is merged, in order to get the latest changes.

**Comment by Quetzacoalt91** [comment]
Thank you @matks

**Pull request merged**
