### PR TITLE
Correcting max_weight comment in Carrier.php

### PR DESCRIPTION
**Pull request by crts314**
`@var int => @var float`

based on

```php
'max_weight' => ['type' => self::TYPE_FLOAT, 'validate' => 'isFloat'],
```

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Correcting max_weight comment in Carrier.php 
| Type?             | comment fix
| BC breaks?        | no
| Deprecations?     | no
| Possible impacts? | None (only a comment was fixed)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23449)

### CODE REVIEW

**Comment by crts314** [comment]
It's weird. I only changed one comment but the diff is large ...

**Comment by matthieu-rolland** [comment]
> It's weird. I only changed one comment but the diff is large ...

Hmm, weird, maybe try rebasing your PR

**Review by matthieu-rolland — COMMENTED** [review]
Hmm, weird, maybe try rebasing your PR, it might fix the big diff

**Comment by crts314** [comment]
I found the issue.. It is due to the end of lines. This file doesn't only have CRLF instead of LF but has actually mixed end of lines...

Saving it using LF makes a couple hundred lines modified.

Saving it using CRLF makes a thousand lines modified.

https://i.imgur.com/blly8wI.png

Maybe I should create a separate PR just for normalizing the file to LF ?

**Comment by Progi1984** [comment]
@crts314 As you want : a new PR or a new commit on this one ?

**Comment by Progi1984** [comment]
@crts314 :warning: A PR cannot contain merge commits. And you have always modifications on lines without changes.

**Comment by crts314** [comment]
The modified lines other than the one with the comment are the endlines that were in CRLF and that I switched to LF (for normalization of end of lines). I have asked before if you would like that to be in a separate PR and you said that I can do it in this one with another commit. I will close this PR and create two one only modifying end of lines and one for correcting the wrong comment.

**Pull request closed without merging**
