### PR TITLE
Check if the directory name match the module file name

### LINKED ISSUE #27930: "Disabled" modules are still displayed during the installation process
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you change the name of the module directory, for example, from `autoupgrade` to `autoupgrade-off`, we shouldn't list it on the available modules to install.

### Expected behavior

We should only show the modules where the directory name matches the main module's file name.

### Steps to reproduce

1. before you install v8, change any module directory you want, from the original name to something else
2. go to the installer
3. see that the module is still displayed, but it shouldn't be

### PrestaShop version(s) where the bug happened

8.0.0

### PHP version(s) where the bug happened

n/a

### If your bug is related to a module, specify its name and its version

n/a

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We don't want to install modules that are not possible to install (e.g. because of the changed module's directory name)
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27930.
| How to test?      | Follow instructions from the issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27931)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by AureRita — CHANGES_REQUESTED** [review]
Hi @kpodemski,

I tested it and currently, the name will not be showed, but during the installation, the problem will not be on the module but in the theme, can you check if this issue doesn't come from your pr ? 

You can see it in this video : 

module hidden : 
https://user-images.githubusercontent.com/100699445/159259040-a0e5f648-5855-48a0-8fea-b0ae67044c28.mp4

**Comment by kpodemski** [comment]
Hi @AureRita 

If you disable modules required by the theme, the installation might fail. In my scenario, I had a local installation where I've changed some of my modules to `mymodule-off` because I didn't want to install them. I could select them during the installation, which was a bug because **it is required for a module directory to match the main module file**. If they do not match, module installation fails. This is a bug that I solved :-)

**Comment by kpodemski** [comment]
I suggest the following:

- change any module name that is not required by a bundled theme, for example, `autoupgrade` to `autoupgrade-off`
- check that you can select it during the installation without my PR and installation fails
- check the same thing with my PR and see that installation proceeds :-)

**Review by AureRita — APPROVED** [review]
Ok, I tested it with the module dashactivity and it works, none problem with the theme, 
The module is correctly hidden. 

Keep caution, if you check the previous video , when you've only one module display, the module will be check and not "all modules" you need to uncheck your module and cross it again to have the check on "all modules" 

thank you for your PR

**Comment by Progi1984** [comment]
Thanks @kpodemski & @AureRita

**Pull request merged**
