### PR TITLE
FO: improve mobile header and menu design

### PR DESCRIPTION
**Pull request by rdy4ever**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR aims to improve the mobile header and menu design: the menu toggle icon is switched with an "X" when the menu is open; fixed the logo position on home page (and it is no longer centered because the centering was not correct and it looked kind'a weird); the cart icon now has the same color as the other nav icons when inactive; the menu is now full screen (minus the site nav); improved design and usability for the expand/collapse arrows; 100% width for the searcbar on mobile; other minor fixes.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | Does it break backward compatibility?no
| Deprecations? | Does it deprecate an existing feature?no
| Fixed ticket? | Related to #9909
| How to test?  | ----- Before/After comparison -----
Menu closed:
image
Menu open:
image
Menu open with submenus:
image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10524)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
As a developer, I think it's really nice!

Wdyt @colinegin?

**Comment by colinegin** [comment]
Discussed with the UX team, we love it ! Thanks for your work @rdy4ever !

**Comment by rdy4ever** [comment]
Glad to help, @colinegin

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mbadrani** [comment]
@colinegin what do you think about this PR (duplicate or not?)

**Comment by Quetzacoalt91** [comment]
Hi @rdy4ever,

We didn't make the link between your PR and another one (https://github.com/PrestaShop/PrestaShop/pull/10229) created a few weeks ago.

It seems your PR may not be totally a duplicate, especially regarding the "X" icon. Can you please check the other PR and rebase yours to complete the potential missing improvements?

Thanks

**Comment by rdy4ever** [comment]
Hi @Quetzacoalt91 
Indeed, I was not aware of  #10229 when I made this PR. I see that #10229 is already merged so I might make another PR to improve in the future, but not right now because I will be a bit busy for a short while. I do see some issues with #10229 and I pointed out one there (it's not a good practice to use arbitrary top padding to center the logo, for example).

**Comment by Quetzacoalt91** [comment]
No worries @rdy4ever.

Your comments should be taken in account during the code freeze by @CaptainYouz on #10229.

In the meanwhile, I'm closing this PR. I guess it will be easier to start another PR than rebasing this one. But if you want to reuse it, feel free to reopen it.

Take care!

**Pull request closed without merging**
