### PR TITLE
[-] PDF : update constraints on Addresses display

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello,

Can you tell us more details about this please?

Regards

**Comment by mickaelandrieu** [comment]
Well ... I dont remember ^^ In my opinion, addresses are hidden from invoices by database configuration and this update is about allow the disply by default.

Ping @vincentbz

**Comment by Shudrum** [comment]
An update to the configuration.xml is needed before merging this PR :)

**Comment by mickaelandrieu** [comment]
@Shudrum what do I have to do ? I'm not sure to understand your point :)

**Comment by mickaelandrieu** [comment]
@Shudrum  done !

**Comment by Shudrum** [comment]
:+1:

**Pull request merged**
