### PR TITLE
Fix bug in translate module page

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Error when trying to translate a module |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1514 |
| How to test? | Just go to installed module -> configure -> translate module and there is no error any more ;) |

### CODE REVIEW

**Comment by thierrymarianne** [comment]
Thanks!

**Comment by mickaelandrieu** [comment]
@fatmaBouchekoua this introduce a bug on translator domain 
translations_modules

we cant select theme for translations anymore, can you remove the option from this select input please ?

**Comment by AlexEven** [comment]
Hello @fatmaBouchekoua 

I tried it but I have a request ^^
I went to Modules > Installed Modules > Image Slider > Configure > Translate > Select French

I arrive on this page, where I have to look for the technical name of the module (and I have no idea what it is since I'm a merchant ;) )

image

1. Can you please change the behavior so that when I select French, I arrive directly on the translation page for the selected module ?

(and right now I can't open this page but I think it's because of another PR ^^)

Thank you!
And let me know if unclear.

**Comment by AlexEven** [comment]
OK @maximebiloe tells me the translations are showing below this block.
However, I don't see any available translations for Image Slider, there must be some other issue... -_-

Thank you!

**Comment by fatmaBouchekoua** [comment]
Hello @AlexEven ,

you have selected a module which not have expressions to translate (see your first screenshot) . Try with another one ;)

**Comment by kpodemski** [comment]
I think that even if module is fully translated we should have possibility to edit those translations?

**Comment by fatmaBouchekoua** [comment]
@kpodemski Not fully translated but it doesn't have expressions to translate

**Comment by kpodemski** [comment]
@fatmaBouchekoua weird, is that even possible? We always have for example module name to translate?

**Comment by fatmaBouchekoua** [comment]
I've noticed this behaviour before editing this page

**Comment by AlexEven** [comment]
@kpodemski we've identified what's the issue and we'll fix this. We have two translations systems co-existing and we need to make sure all translations are available!

Thanks again @fatmaBouchekoua :)

**Comment by kpodemski** [comment]
@AlexEven cool, i know that this was reported on Gitter by me and @firstred that we translations with a format `$this->l` doesn't work at all at this moment for module templates

**Comment by AlexEven** [comment]
Isn't it what this PR is fixing?
The problem now lies with the 1.7 native modules which we've rewritten using the new trans method (like ps_imageslider).

**Comment by kpodemski** [comment]
Yes, from what i see this is a proper bugfix for this problem

@firstred could you confirm that?

**Comment by fatmaBouchekoua** [comment]
@mickaelandrieu Done PR: https://github.com/PrestaShop/PrestaShop/pull/6462

**Pull request merged**
