### PR TITLE
HelperList: remove notice if specificConfirmDelete is set to false

### LINKED ISSUE #27717: BO - HelperList: notice if specificConfirmDelete is set to false
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In an HelperList with specificConfirmDelete = false, a php notice is displayed in debug mode
image

### Expected behavior

No notice

### Steps to reproduce

1. Choose an HelperList
2. set $this->specificConfirmDelete = false;
3. Load the corresponding Admin Controller in debug mode
4. See the notice

### PrestaShop version(s) where the bug happened

1.7.x, 8.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | HelperList: notice if specificConfirmDelete is set to false
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | ~Fixes https://github.com/PrestaShop/PrestaShop/issues/27717~
| How to test?      |  see issue
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27718)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matthieu-rolland** [comment]
thank you !

PR is approved but we'll wait for the issue to be validated before sending it to QA 👍

**Comment by jf-viguier** [comment]
thanks

**Review by kpodemski — CHANGES_REQUESTED** [review]
This change prevents me from deleting shopping carts.

Steps to reproduce:
1. Open `AdminCartController`
2. set `specificConfirmDelete` to `false`.
3. apply your change

It's impossible to delete shopping carts. I think you should make a fix at the view level.

**Comment by jf-viguier** [comment]
Nice catch @kpodemski, i've changed default value to :
Tools::safeOutput(self::$cache_lang['DeleteItem'] . $name)

I don't know why specificConfirmDelete has a different treatment between null and false.

**Comment by atomiix** [comment]
I think you can simplify 
```php
if ($this->specificConfirmDelete !== false) {
  $data['confirm'] = null !== $this->specificConfirmDelete ? '\r' . $this->specificConfirmDelete : Tools::safeOutput(self::$cache_lang['DeleteItem'] . $name);
}
```

with:
```php
if (!empty($this->specificConfirmDelete)) {
    $data['confirm'] = '\r' . $this->specificConfirmDelete
}
```

[line 603-605](https://github.com/PrestaShop/PrestaShop/pull/27718/files#diff-e95bfb9f629400b25516527f6e7b19f361b184f1b2975110b9cda70bfed2a208R603-R605)

**Review by Progi1984 — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Comment by saulaski** [comment]
> I don't know why specificConfirmDelete has a different treatment between null and false

From what we can read in code, public property `specificConfirmDelete` is defined as null
- null => default behaviour ?
- false => disable the behavior ?
- any string => override default behaviour ?

**Comment by kpodemski** [comment]
Hello @jf-viguier 

What do you think about @atomiix feedback?

**Comment by matks** [comment]
Hi @jf-viguier ,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale.

If you find some time and want to continue please ping me and I will reopen the contribution 😉 you know how to contact me 😋 

Thanks!

**Comment by jf-viguier** [comment]
hi @matks, I've commited @atomiix suggestion, please reopen.
BTW, It was just a suggestion and not related to my pr.

**Comment by jf-viguier** [comment]
New PR here https://github.com/PrestaShop/PrestaShop/pull/28458

**Comment by matks** [comment]
I was about to reopen 👍  but this works too

**Pull request closed without merging**
