### PR TITLE
Add custom tinymce configuration on migrated pages

### LINKED ISSUE #19408: Hook for modifying TinyMce
It would be useful to alter the `tinySetup(config)` function.

Maybe add a (PHP)-hook somewhere to assign a JS-variable: `tinyMceOverrides` so one can do something like this:

    function hookTinyMceConfigDefault(&$config){
          $config['toolbar1' = "code,colorpicker,bold,italic,underline,strikethrough,blockquote,link,align,bullist,numlist,table,image,media,mysuperspecialtoolbarmagictrick";
    }

Then in `js/admin/tinymce.inc.php`  something like:

    
      $.each(tinyMceOverrides, function (index, el) {
           config[index] = el;
       });

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | TinyMCE config override was missing on migrated pages (Product page baited me probably)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19408.
| How to test?      | Add a defaultTinyMceConfig global var using QA module and see if the tinymce configuration changed and if it's working properly on pages, better be tested by a dev

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23232)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
strangely behat tests are breaking... I restart it just in case

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
Hi @PrestaShop/prestashop-core-developers we let you handle this one 
Thanks guys !!

**Comment by atomiix** [comment]
With this hook:
Capture d’écran 2021-03-31 à 17 06 15

Without the PR:
Capture d’écran 2021-03-31 à 17 06 28

With the PR:
Capture d’écran 2021-03-31 à 17 06 46

This PR is QA ✔️

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @atomiix

**Pull request merged**
