### PR TITLE
Fix a bug on safari where SEO preview on create page was not updated

### LINKED ISSUE #17525: SEO live previews don't work on Safari desktop
**Describe the bug**
SEO live previews don't work properly on Safari desktop.
Instead of displaying the meta-title, URL and meta-description,  it only displays the URL.

Capture d’écran 2020-02-06 à 08 50 28

**To Reproduce**
1. Go to Design > Pages > Create a new page
2. Fill in the fields
3. See the preview not working and the text editor nor being displayed

**Expected behavior**
Capture d’écran 2020-02-06 à 10 43 32 (2)

**Additional information**
PrestaShop version: 1.7.6.2
Safari version: 11.1.1
MacOS: 10.13.5

Couldn't reproduce with **Safari 13.0.5** on **MacOS 10.14.6** with **PS 1.7.6.2**

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | SEO Preview while creating a page was broken, it was not working
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17525
| How to test?  | Build assets, and then create a page and type in title, SEO should be updated

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17711)

### CODE REVIEW

**Review by matthieu-rolland — CHANGES_REQUESTED** [review]
LGTM, but for some reason you have pretty CI issues on files you didn't touch 🤔 

Maybe you need to rebase ?

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Need a rebase  @NeOMakinG

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Re running PrettyCI

**Comment by NeOMakinG** [comment]
To QA : It can be tested and @eternoendless will merge it without PrettyCI which is crying

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is OK `os => OS+X => os_version=High+Sierra => browser=>Safari & browser_version=>11.1`
https://drive.google.com/file/d/1Ea0hZfvAKt6PfJN1hREqA2FT16NnHlUp/view

PS: using iOS9 => issue reproduced
image
But, this is won't be fixed which is simlar to this case: https://github.com/PrestaShop/PrestaShop/issues/17403

Thanks!

**Comment by atomiix** [comment]
@eternoendless I think you can merge as it's QA approuved!

**Comment by eternoendless** [comment]
Thank you @NeOMakinG

**Pull request merged**
