### PR TITLE
Fix SQL table name in Category::getUrlRewriteInformation

### PR DESCRIPTION
**Pull request by nsorosac**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Table `category_link` does not exist
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
The fix is legit, although, from what I see, this method is not compatible with multi-store. I'm not sure if we should keep it in the core without ensuring that we'll return `id_shop`.

**Review by matthieu-rolland — COMMENTED** [review]
thank you for your pull request @nsorosac 

can you please create an issue and link it in your PR description table?

**Comment by matks** [comment]
> thank you for your pull request @nsorosac
> 
> can you please create an issue and link it in your PR description table?

Agreed with @matthieu-rolland 😄 

We can only validate your PR if we have a clear, reproducible understanding of the issue. In order to be able to explore your PR, to verify any side-effects, to make sure it is correct, we need a bug report confirmed. How did you find this problem?

**Comment by nsorosac** [comment]
@matks @matthieu-rolland désolé mais je ne passerai pas + de temps sur un fix aussi simple : une classe utilise une table qui n'existe pas, mon fix le corrige, fin de l'histoire :checkered_flag: 

Après si vous préférez tergiverser pendant 3 mois et fermer mon PR pour une raison obscure, libre à vous :kissing_heart:

**Comment by matks** [comment]
> @matks @matthieu-rolland désolé mais je ne passerai pas + de temps sur un fix aussi simple : une classe utilise une table qui n'existe pas, mon fix le corrige, fin de l'histoire 🏁
> 
> Après si vous préférez tergiverser pendant 3 mois et fermer mon PR pour une raison obscure, libre à vous 😘

Fixing a bug in the software is good, but if you simply push this PR and we merge it, nobody knows it's been fixed. Do you check every single PR that is merged into the software in order to know what has been fixed?

This is why also reporting a bug is important. This will be used _by other users of the software_ to understand what's been fixed. The bug report is not here to annoy you it is used to track the defect, track what version it impacts, in what version it is fixed, and also to make sure it will not come back in a future version.

So we are not requesting a bug report for an obscure reason. We request a bug report in order to allow people who will check PrestaShop changes to be able to understand what's going on. This is an open source project you can't just think "I have solved an issue, cool let's merge it and goodbye". It's also important to explain, track, register what happens for the people in two weeks, two months, two years that want to understand what was changed 😉 . Maybe one day you'll find a bug in prestashop and you'll be happy to find a complete and detailed bug report that describes it and give you all the information you need to find?

**Comment by matthieu-rolland** [comment]
> @matks @matthieu-rolland désolé mais je ne passerai pas + de temps sur un fix aussi simple 

English please.

It has nothing to do with the level of complexity of the PR, it's just that every PR must be linked to an issue so that our product and QA teams can track what is happening on the project, everyone follows this rule.

**Comment by nsorosac** [comment]
@matthieu-rolland nous avons déjà fait plein de PR reliés à aucune _issue_, vos équipes étaient ravies de les intégrer à la solution. Tant pis, c'est certainement le dernier PR que je ferai vu l'énergie à déployer pour corriger une simple ligne de PHP qui traîne depuis 3 dans le code source. Vous pouvez fermer le PR, merci.

**Pull request closed without merging**
