### PR TITLE
Add coding style based on PHPCS Fixer

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Everything we want to integrate with PHPCSFixer, We execute this on every files after the merge of the branch 1.7.4.x into develop :)
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Nothing to test.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9349)

### CODE REVIEW

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
To be merged after 1.7.4.2 is merged into develop

**Comment by mickaelandrieu** [comment]
@PierreRambaud update of .travis.yml file is missing, isn't it?

You can use my old pull request if you need to ;)

**Comment by PierreRambaud** [comment]
Nop, as @eternoendless said in previous conversation, we will do this after.
1 - Add rules to the project
2 - Use Cs Fixer on all files
3 - Add Travis check (and don't know if we need to fail fast or not + disable screenshots by default)

**Comment by mickaelandrieu** [comment]
> We execute this on every files after the merge of the branch 1.7.4.x into develop :)

So in this future PR, you will add the travis check if I have understood you clearly?

**Comment by PierreRambaud** [comment]
@mickaelandrieu Yes that's the aim! :+1: Cs Fixer is coming soon :100:

**Comment by eternoendless** [comment]
Needs rebase & merge !

**Pull request merged**
