### PR TITLE
Parse float for attributes wholesale price (Combinations)

### LINKED ISSUE #9972: [BOOM-3165] Price calculations ; product combination HT / TTC, I input 260 impact on price and 259.999999 is saved
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3165).

- _**Reporter:**_ antoine_pathie
- _**Created at:**_ Thu, 1 Jun 2017 12:17:08 +0200

<p>On my development site and a local fresh new install it's impossible to save a price impact with correct round.</p>

<p>For example, after entering 260 in "Impact on price (tax incl.) (step1.jpg) and clicking on "back to product" (backtoproduct.jpg) then click again on the combination the price change to "259.999999" (backtocombination.jpg). On the front-office the price is incorrect.</p>

<p>Moreover the final price is not calculated on the recap of all combinations.(backtoproduct.jpg)</p>
        
* How to reproduce the issue ?

> Edited by Khouloud

Reported here: https://github.com/PrestaShop/PrestaShop/pull/28482#pullrequestreview-974372319

1. Create a tax rule = 23%
2. Go to BO > Catalog > Product V2
3. Create a product with combinations > In the pricing tab: tax rule = 23% Retail price tax secluded = 10 / Retail price tax included = 12.3 / ecotax = 0 )
4. Generate a combination & edit it > impact on price tax included = 12 and click outside
5. See error: it will be converted to `12.000001`

https://user-images.githubusercontent.com/16067358/168652698-82d4d900-f087-440c-9541-97555031f4c1.mp4

### LINKED ISSUE #23922: The decimal of wholesale prices on attributes is lost when editing the product
#### Describe the bug

The decimal of the attributes wholesale prices is lost when the product is edited, and then the calculations of profits are wrong.

#### Expected behavior

The wholesale price should stay the same when the product is edited.

#### Steps to Reproduce

1. From the Back-Office: Catalog / Products, click to edit a Product with attributes
2. Go to the Attributes tab, and then edit an attribute
3. Enter a wholesale price for the attribute (e.g. 1,55)
4. Save and go back to the product listing
5. Click to edit the same product
6. Click on Save and go back to the product listing
7. Click to edit the same product (for the 3rd time), go to the Attributes tab and click on the attribute : the wholesale price has been rounded, the decimal is lost
PS : make sure the decimal used in price is a comma (,) not a point (.)

**Screenshots**

https://drive.google.com/file/d/1ftmGmgHwTNXUNSaZVNcdhtcXVnNE1N1a/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.x
* PHP version: N/A

### PR DESCRIPTION
**Pull request by andromaque**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add a float parser for the wholesale price of attributes
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23922. Might fix #9972 too
| How to test?      | From the Back-Office Catalog / Products, click to edit a Product with combinations<br/>Go to the Combinations tab, and then edit a combination<br/>Enter a wholesale price for the combination (e.g. 1.55)<br/>Save and go back to the product listing<br/>Click to edit the same product<br/>Click on Save and go back to the product listing<br/>Click to edit the same product (for the 3rd time), go to the Combinations tab and click on the combination: the wholesale price is not rounded anymore.
| Possible impacts? | N/A

This PR fixes issue #23922, but it could also fix #9972, we're not 100% sure if these two issues are duplicates or not.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23923)

### CODE REVIEW

**Review by PululuK — APPROVED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — COMMENTED** [review]
Could you update unit test `tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php` in method `testGetFormCombination` ?

**Comment by matthieu-rolland** [comment]
shouldn't we wait for the bug to be reproduced by the qa in the issue before sending this PR in QA ?

**Comment by Progi1984** [comment]
@matthieu-rolland Right, and we need to improve unit test.

**Comment by PululuK** [comment]
> shouldn't we wait for the bug to be reproduced by the qa in the issue before sending this PR in QA ?



> shouldn't we wait for the bug to be reproduced by the qa in the issue before sending this PR in QA ?

Yes u'are right !

@Progi1984 sorry, we did at the same time.

**Comment by andromaque** [comment]
It appears that the PR is a duplicate of PR #20144 mentioned in issue #9972

The thing is that the issue #9972 has been opened in 2018, and PR #20144 is stuck for a while, because it seems it does not correct the issue (it's right, the issue is about a problem of rounding, and the PR is about the loss of decimals).

The issue I raised has been closed as duplicate (but it's not), and the PR #20144 won't be updated in a while I guess.

So what should be done? This is a simple issue with a simple resolution 😅

**Comment by matthieu-rolland** [comment]
@andromaque your fix looks good to me, I'd like to approve it, but we have this process where the issue must be reproduced before the PR is tested by the QA...  I'll try to ping someone at the QA

edit: I see it has been reproduced ! we can send it to QA then

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Comment by Progi1984** [comment]
@andromaque 
Could you update unit test tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php in method testGetFormCombination ?

**Comment by andromaque** [comment]
> @andromaque
> Could you update unit test tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php in method testGetFormCombination ?

@Progi1984 I'm not sure what I'm supposed to do, sorry. How can I update this test, and with what? I have absolutely no idea on how to work with these unit tests 😅

**Comment by PululuK** [comment]
Hi @Progi1984 
Can you please give more details to help @andromaque ... he seems to be lost 😀

**Review by PierreRambaud — DISMISSED** [review]

**Comment by andromaque** [comment]
Hi @Progi1984, could you please tell me what I have to update ?
Indeed I don't understand why I should modify a test for this issue, as it is not relevant to have an automatic test checking for this kind of bug: it's happening only with a specific locale and requires to save information multiple times on the product. For me it's clearly out of the scope of an automatic test.

**Comment by Progi1984** [comment]
@andromaque Hi, at the line https://github.com/PrestaShop/PrestaShop/blob/develop/tests-legacy/PrestaShopBundle/Model/Product/AdminModelAdapterTest.php#L255, add a row for your new key and add it the expected value.

**Comment by andromaque** [comment]
@Progi1984 the thing is it's totally useless, there is no bug while entering just one data. There is a bug if we enter a specific data (a price with a decimal, and comma separated), save, quit, enter the product again and save without touching to the attributes part, then save and going back to the product attributes to see the results. And worse, it only happens with a French locale, because the bug is due to the French decimal (which is a comma) being badly interpreted because it expects a point. Well, no way to enter this stuff (at least for me) in the automated test 😅

**Comment by andromaque** [comment]
ping @Progi1984 @PierreRambaud , could we please move forward and merge this PR without changing the unit test which is not relevant for this PR? Thank you

**Comment by PierreRambaud** [comment]
> ping @Progi1984 @PierreRambaud , could we please move forward and merge this PR without changing the unit test which is not relevant for this PR? Thank you

Unfortunately, everything is relevant when talking about unit tests, here, some are already present, it costs a few time to update them and make them work regarding your change.

**Comment by matks** [comment]
Hi @andromaque I agree with you that not everything should be tested, but here I see no reason not to test the new behavior you introduced :)

- there is already a test file for this, so you don't have to build the setup of the test
- the usecase is well identified: input and outputs
- the test is not going to consume a lot of resources or time so no cost issue

If we were doing Test Driven Development, we would have written the test _before_ the bugfix 😄  .

> it's happening only with a specific locale and requires to save information multiple times on the product. For me it's clearly out of the scope of an automatic test.

This test would be actually very useful! Because using a specific locale, and a multiple-save usecase is something we could forget to test when writing the code. I think this bug is an opportunity to verify PrestaShop can work well in these conditions.

If there was a bug report, it means someone reported this bug so someone was annoyed by a bad behavior of the software. It means there is something we can test 😄  . The test will help verify the issue does not come back later, and might also help us detect more deficiencies in the software area around this code.

Some developers like to say "you have a bug report? cool, the first thing to do is to write a test that fails because of the issue, and I can only validate your changes if the test passes after you merged your changes"

**Comment by andromaque** [comment]
Hi @matks 
Sure, I understand the value of a test. But this is not a simple test, this is a multiple actions test, which is clearly out of my area of knowledge 😞I see a function entering data only time, not multiple time (fakeFormData). We need at least 3 steps of entering data then tested against expected result. So how can we proceed? I don't think I will be able to correct the test to reproduce the behavior (changing the locale - and if we wanted to be exhaustive, we should test it against every locale to be sure, saving multiple times etc). Thank you for your help, we already missed the 1.7.8 so this PR won't be merged and available in prod until the end of the year at best... Which is too bad for such a simple and useful fix, because right now every shop using French and attributes has wrong stats. Thank you

**Comment by matks** [comment]
> Thank you for your help, we already missed the 1.7.8 so this PR won't be merged and available in prod until the end of the year at best...

You do not need to wait for a Pull Request to be merged to use a bugfix in production 🤔  . The bugfix is right here, you can use it immediately on your shop(s). The Pull Request goal is to merge the bugfix inside the upstream project so that it gets distributed to every user of the project.

> Sure, I understand the value of a test. But this is not a simple test, this is a multiple actions test, which is clearly out of my area of knowledge 

Good news: by building this test you are going to increase your skills 💪  😄  .

@Progi1984 already provided some insights on how to build this test 😉  . Can you try to do it? We can provide some help to guide you on this journey. At least try, and tell us of the obstacles you encounter.

**Comment by andromaque** [comment]
> You do not need to wait for a Pull Request to be merged to use a bugfix in production 🤔 . The bugfix is right here, you can use it immediately on your shop(s). The Pull Request goal is to merge the bugfix inside the upstream project so that it gets distributed to every user of the project.

Nope, but then I have to remember to merge all the modifications manually every time PrestaShop is updated. And the longer it takes to be merged in a stable release, the longer I'll have to do this.

> Good news: by building this test you are going to increase your skills 💪 😄 .

Yes 😂 But more seriously, should not tests being written by a dedicated team? Because I can clearly see a huge quality issue if the developers are writing their own test cases: the test will comply to what's been programmed, but it should comply to what has been **specified**, which is not the same.

> @Progi1984 already provided some insights on how to build this test 😉 . Can you try to do it? We can provide some help to guide you on this journey. At least try, and tell us of the obstacles you encounter.

I'll try and tell you. Unfortunately the insight is not enough... I need at least an example of a test doing multiple steps (and a clean way to force a locale), the insight of @Progi1984 was to add a key and set a value, which is not correct in this case because the key is already there and the value is not the only problem.

**Review by Progi1984 — APPROVED** [review]

**Pull request closed without merging**
