### PR TITLE
[-] BO : Fix PSCSX-7467, combination can be duplicated during product editing

### PR DESCRIPTION
**Pull request by kpodemski**

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, Krystian!
I renamed the PR. Core guys, the Forge ticket is here: http://forge.prestashop.com/browse/PSCSX-7467

@kpodemski, could you amend your PR to us the naming guidelines? Most notably the first one, but the second one could also use a bit of a touch-up. Use `git commit --amend` for that. Thanks!

**Comment by kpodemski** [comment]
@xBorderie I squashed those two commits into one with proper name

**Comment by xBorderie** [comment]
Hey @kpodemski ! I see you went so far as to deleted your commits. Is the time it takes to answer the reason?

**Comment by kpodemski** [comment]
Hi, it had be some mistake from my side :(

**Comment by xBorderie** [comment]
Ouch! I guess it's because you made the PR on the `1.6.1.x` branch rather than a fix-dedicated branch; you probably updated the branch to the latest codebase, and thus lost your fix? :/

**Comment by kpodemski** [comment]
Yes, unfortunately I've spent over an hour to solve this problem so I need to search on my files and local repos to find this, I will create new PR if i'll find this

**Comment by xBorderie** [comment]
Damn. Good luck!

**Comment by kpodemski** [comment]
eh, I've lost it, I can do it again because I remember this case but I can do it in 2-3 days and I'm hoping that it will not wait another 6 months :(

**Pull request closed without merging**
