### PR TITLE
Fix: BO - cannot change the type of a product

### LINKED ISSUE #32675: BO - cannot change the type of a product
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when you add the product name you can't  change the type of product .

[iss1produitname810.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/8edb1175-7853-49db-b066-47e26391c631)

### Expected behavior

after adding all the informations , you can change the type of your product 
 PS 8.0.4 : OK  

[iss1produitname804.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/4826c461-8764-4688-9704-e51b1412959c)

### Steps to reproduce

1. Go to Catalog > Products >Add new product (ex : standard  product ) > see you can click to change the type of your product .
2. Add the name of the product > See NOW you can't change the type of your product   .

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

8.1 

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x 
| Description?      | when you add the product name you can't change the type of product
| Type?             | bug fix
| Category?         | BO
| Fixed ticket?     | Fixes #32675

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @Codencode 

Thanks for your PR.
Unfortunately the related issue is closed by the Product team (see their [comment](https://github.com/PrestaShop/PrestaShop/issues/32675#issuecomment-1566838240)).
So the PR should be closed.

Sorry and thanks for your hard working 🙏

**Comment by Codencode** [comment]
> Hello @Codencode
> 
> Thanks for your PR. Unfortunately the related issue is closed by the Product team (see their [comment](https://github.com/PrestaShop/PrestaShop/issues/32675#issuecomment-1566838240)). So the PR should be closed.
> 
> Sorry and thanks for your hard working 🙏

Hi @hibatallahAouadni,
no problem!

**Review by jolelievre — CHANGES_REQUESTED** [review]
Hi @Codencode 

I'm sorry but I must block this PR but for a good reason. The fact this button is disabled on any change in the page is not a bug but a feature (true story ^^)

By doing this we want to force the fact that changing a product type is the only thing performed in a type changing request. Because we encountered numerous bugs related to this.

For example you change some data related to virtual product but change its type to another one, then you get potential errors depending on which order the modification are performed, the product is transformed in to a regular product but you add a virtual file which is against some of our business rule and it triggers an error.

Other example, the virtual product doesn't have an ecotax, when we switch the type the ecotax is added to the original product price to balance it. But if both are modified at the same time the ecotax may be lost and the final price is not the same anymore.

That's one example but basically since the form content is dynamic and dependent on the product type some inconsistency can occur if the product type is switched during request that also contain other data, and some data may be lost.

All those changes are handled in this listener if you're curious https://github.com/PrestaShop/PrestaShop/blob/cb27b546e978926d732d5a510864d3b33f4c9060/src/PrestaShopBundle/Form/Admin/Sell/Product/EventListener/ProductTypeListener.php#L43

We tried to handle them as well as possible at first by checking the former type and the new current type, but in the end it only brings a LOT of complexity and it doesn't prevent some bugs that we couldn't anticipate yet. So the safest move we decided was to force the type switching to be the only action of a request, and any other modification prevents the type switching.

Quite a long answer, I hope it's clear 😅 I'm available to discuss it further.

**Comment by Codencode** [comment]
Hi @jolelievre,
no problem, everything is clear indeed thanks for explaining all the reasons!

Thanks!

**Comment by PululuK** [comment]
Thanks @jolelievre for the explanation

**Pull request closed without merging**
