### PR TITLE
View templatesRemove email "Preview" from BO section "Statutes" (because it's not working)

### LINKED ISSUE #36165: Remove email "Preview" from BO section "Statutes" (because it's not working)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Preview button is not working and customers are confused and consistently reporting problem to developers, very difficult to explain it's "security feature", because customers are asking "Why is there button Preview, if it's not working"...

Real issue from real production environment.

### Expected behavior

Preview will show email content only for logged BO users, but it can be a **lot of edits**, so for now **it's better to hide button "Preview" at least.** Maybe in future improve it.

### Steps to reproduce

1. Go to BO to section "Statutes"
2. Open any State with "Send email to customer" enabled
3. Scroll down and click on button "Preview"
4. Popup will appears, but we see only error 403 Forbidden (because of security protection of email contents from outside)

### PrestaShop version(s) where the bug happened

8.1.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

openservis.cz

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Check issue #36165 
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Go to any Order State with mail template and check, if there is button "Preview"
| UI Tests          |  https://github.com/florine2623/testing_pr/actions/runs/9658853714 ✅ 
| Fixed issue or discussion?     | Fixes #36165 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Review by kpodemski — CHANGES_REQUESTED** [review]
That's not how we should do things, removing something because it stopped working is not a solution.

**Comment by kpodemski** [comment]
Isn't a solution to simply allow browsing these files in the .htaccess?

**Comment by Hlavtox** [comment]
@kpodemski probably a security issue, everyone could browse your templates

**Comment by ShaiMagal** [comment]
@kpodemski But this is not working for **4 years** (https://github.com/PrestaShop/PrestaShop/issues/17759)... It's nothing new...

So better option is to leave this still not working and still explaining customers? seriously? :-D

Better option for me is hide this, if this is not working for 4 years already. Customers are complaining. Hiding is not ideal solution, but better than leave this feature still broken....... :/

Unfortunatelly, no :( because, it will allow "attacker" to see content of this mail templates. And this is purpose of .htaccess to hide this from public.

**Review by kpodemski — APPROVED** [review]
Ok. From the code perspective, it's good, from the product point of view, I'd like to see @MatShir opinion on this one, I think it's not the end of the world to temporarily disable this.

**Comment by MatShir** [comment]
LGTM 👌 
thanks @ShaiMagal !

**Review by Hlavtox — APPROVED** [review]

**Comment by ps-jarvis** [comment]
QA approved, well done! Message to the maintainers: do not forget to milestone it before the merge.

**Review by florine2623 — APPROVED** [review]
LGTM, it is QA ✅

**Pull request merged**
