### PR TITLE
Fix category description below the image

### LINKED ISSUE #9979: [BOOM-3049] Problème d'affichage catégorie en FO
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3049).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Tue, 16 May 2017 11:33:09 +0200

<p>Version 1.7.1.2 RC2<br/>
La description de la catégorie et l'image se superposent</p>
        
* How to reproduce the issue ?

N/A

### LINKED ISSUE #11494: Category description text shouldn't be below the image
**Describe the bug**
Category description texts should not be below the image in the classic theme design.

**To Reproduce**

1. Go to 'Category page on classic theme'

**Screenshots**
category-page

**Additionnal information**
PrestaShop version: 1.7.4.4

### PR DESCRIPTION
**Pull request by dineshbadrukhiya**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Category description texts should not be below the image in the classic theme design.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9979
| How to test?  | Check the category page description on classic theme.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11495)

### CODE REVIEW

**Comment by TristanLDD** [comment]
Hi @dineshbadrukhiya 
Thank you for your suggestion

We are currently working on a new way to display the category banner and text. The next update of this component of the classic theme will be the result of the reflexion we're having now, that's why we won't change the current behavior immediately.

**Comment by marionf** [comment]
@dineshbadrukhiya can you rebuild assets please ?

**Comment by dineshbadrukhiya** [comment]
@marionf I will.

**Comment by Quetzacoalt91** [comment]
Conflicts resolved and assets regenerated

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by dineshbadrukhiya** [comment]
@Quetzacoalt91 Thanks.

**Comment by marionf** [comment]
@TristanLDD is it ok for you ?

capture d ecran_684

**Comment by TristanLDD** [comment]
@marionf    Ok for me :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @dineshbadrukhiya

**Pull request merged**
