### PR TITLE
BO: Import stores csv

### PR DESCRIPTION
**Pull request by marrouchi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | This PR add the stores CSV import feature.
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-3457
| How to test?  | You can use the csv file "docs/csv_import/stores_import.csv" to test the stores import. Import process is similar to importing products, categories, ...

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
Sadly, we do not currently accept new features for 1.6 -- the 1.6.1.x branch only accepts bugfixes. Maybe one day we'll have a 1.6.2.x branch! :)
In the mean time, could you remake this PR on the 'develop' branch? It seems to be an interesting idea, and thus could land in PS 1.7! :)

**Comment by marrouchi** [comment]
@xBorderie Okay :)

**Comment by marrouchi** [comment]
@xBorderie i've checked and this feature exists already in the "develop" branch (1.7), so i guess everything is OK!

**Comment by xBorderie** [comment]
I thought it might be. 

raw

Thanks for taking the time to check!

I am closing this PR. Feel free to reopen it if one day there's a 1.6.2.x branch opening! :)

**Pull request closed without merging**
