### PR TITLE
Introduce Nightly status badge - thank you @SimonGrn

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Introduce Nightly status badge in README.md
| Type?         | new feature
| Category?     | PM
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No need for QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18733)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by matks** [comment]
Looks like shields.io API is quite slow. We're going to improve this with @SimonGrn we might not need shields.io API.

**Comment by matks** [comment]
Apparently we could return directly the SVG
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="190" height="20"><linearGradient id="b" x2="0" y2="100%"><stop offset="0" stop-color="#bbb" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><clipPath id="a"><rect width="190" height="20" rx="3" fill="#fff"/></clipPath><g clip-path="url(#a)"><path fill="#555" d="M0 0h105v20H0z"/><path fill="#97ca00" d="M105 0h85v20H105z"/><path fill="url(#b)" d="M0 0h190v20H0z"/></g><g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110"> <text x="535" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="950">Nightly - develop</text><text x="535" y="140" transform="scale(.1)" textLength="950">Nightly - develop</text><text x="1465" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="750">70% passed</text><text x="1465" y="140" transform="scale(.1)" textLength="750">70% passed</text></g> </svg>
```

**Comment by PierreRambaud** [comment]
It's not a good idea to display the svg directly because data are not static :thinking:

**Comment by SimonGrn** [comment]
> It's not a good idea to display the svg directly because data are not static

What is your suggestion ?

**Comment by Progi1984** [comment]
@SimonGrn May be an endpoint `http://api-nightly.prestashop.com/data/badge/svg` which returns the svg code.

**Comment by PierreRambaud** [comment]
> @SimonGrn May be an endpoint `http://api-nightly.prestashop.com/data/badge/svg` which returns the svg code.

Yes, it's maybe the best solution but you need to code the svg behaviour (with different color depending on the result of builds)

**Comment by Progi1984** [comment]
@PierreRambaud Which are ever available in `http://api-nightly.prestashop.com/data/badge`

**Comment by SimonGrn** [comment]
I'm already sending different data in the JSON endpoint, so that's not a big deal. What is a big deal (to me) is that I'm not sure using a REST API to display SVG is a good practice.

**Comment by Progi1984** [comment]
@SimonGrn A REST API can send different data according to the endpoint (Stripe has endpoints finishing with csv/xml/json

**Comment by SimonGrn** [comment]
I can do that, but won't it blow up the server with all the load ? I should then make a cache system, and that's becoming a bit complicated

**Comment by matks** [comment]
Keep It Simple and Stupid.
Endpoint returns raw SVG data with "search-and-replace" built-in for the values.

Let's not over-engineer something that is a nice-to-have and unlikely to be used by someone else 😉

**Comment by SimonGrn** [comment]
OK, so here it is:
- Raw JSON version : http://integration-api-nightly.prestashop.com/data/badge
- SVG version : http://integration-api-nightly.prestashop.com/data/badge/svg

Data is pulled from the last execution for the `branch` given through the `branch` GET parameter (default to `develop`). You can also give it a specific date with the `date` GET parameter.

Does it seems OK for you ?

**Comment by matks** [comment]
@SimonGrn It's beautiful 😄 
How can we use the date ? I tried http://integration-api-nightly.prestashop.com/data/badge/svg?date=18-05-2020

**Comment by SimonGrn** [comment]
You must use the YYYY-MM-DD format. Also it's the integration platform, we don't have that much data (insert it not automatic).
You can check http://integration-api-nightly.prestashop.com/data/badge/svg?date=2020-04-14&branch=1.7.7.x for example.
Go to http://integration-nightly.prestashop.com/ to see the data we have there.

**Comment by matks** [comment]
@SimonGrn Beautiful ! Do you want to do the PR ? 😊

**Comment by SimonGrn** [comment]
I'll let you do it ! Thanks :stuck_out_tongue_closed_eyes:

**Comment by matks** [comment]
This PR is now mergeable

Final badge is https://img.shields.io/endpoint?url=https%3A%2F%2Fapi-nightly.prestashop.com%2Fdata%2Fbadge&label=Nightly%20Status

**Comment by SimonGrn** [comment]
Nice ! Thanks for the PR

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]
Cool!

**Comment by matks** [comment]
Thank you for review !

**Pull request merged**
