### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This var is not used ; it's handled inside the src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Webservice/index.html.twig template
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Sponsor company   | @PrestaEdit.

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by nicosomb — APPROVED** [review]
good catch

**Review by Touxten — APPROVED** [review]

**Comment by FabienPapet** [comment]
If develop is the 9.1, this is a BC break, this should target 9.0 IMO

**Review by kpodemski — CHANGES_REQUESTED** [review]
Could you rebase onto 9.0.x?

**Pull request closed without merging**
