### PR TITLE
Allow template vars override in hook actionFrontControllerSetVariables

### PR DESCRIPTION
**Pull request by Matt75**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow template vars override in hook actionFrontControllerSetVariables
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Please see https://github.com/Matt75/displayshoplogobylang which requires this hook modification to work properly

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14049)

### CODE REVIEW

**Comment by Matt75** [comment]
Is possible to add it on 1.7.6 ?
It's for a demonstration 🤓

**Comment by matks** [comment]
Does it solve partially needs expressed in https://github.com/PrestaShop/PrestaShop/issues/13462 or https://github.com/PrestaShop/PrestaShop/issues/11125 ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by Matt75** [comment]
https://github.com/PrestaShop/PrestaShop/issues/13462 is related to Twig, this is for FO who still use Smarty so I don’t think.

https://github.com/PrestaShop/PrestaShop/issues/11125 is related to Presenters, here it’s about template vars in FrontController class. I think it’s better to add another hook for Presenters. Maybe I will need it for wishlist module ?

But seems to be similar needs.

**Comment by matks** [comment]
Note: after merge, needs to be added to hook list on devdocs

As it is a FO hook, it does not need to be added to hook.xml nor in the SQL upgrade, does it ? 🤔

**Comment by matks** [comment]
Thank you @Matt75

**Comment by matks** [comment]
> Note: after merge, needs to be added to hook list on devdocs
> 
> As it is a FO hook, it does not need to be added to hook.xml nor in the SQL upgrade, does it ? 🤔

ping @Quetzacoalt91 @PierreRambaud 
Do we need to update hook.xml and SQL upgrade for FO (= legacy) hooks, or is it only for Symfony hooks ?

**Comment by Quetzacoalt91** [comment]
You may want to add it into the file hook.xml if you want to provide details about this hook. That's not a mandatory step though.

**Comment by jf-viguier** [comment]
Yes, please add a hook for Presenters overriding.

**Pull request merged**
