### PR TITLE
Remove duplicate attributes 

### LINKED ISSUE #18626: BO - Orders & Invoices page - an exception is displayed
#### Describe the bug

In the BO => Orders & Invoices Page, an exception is displayed

In the install page, randomly, we have
image

#### Steps to Reproduce

1. Go to BO => Orders page & Invoices page
2. See error

**Screenshots**
image

#### Additional information

* PrestaShop version: develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | In the BO => Orders & Invoices Page, an exception is displayed. conflict between #18425 and #18220 during the merge
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/18626.
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/18626 by @khouloudbelguith .

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18628)

### CODE REVIEW

**Comment by PululuK** [comment]
Hi guys @khouloudbelguith  @PierreRambaud  @matks  @Progi1984 

There has been a conflict between these two PRs (#18425 and #18220) which has just been merged.

I think we can revert this #18425 because it is already included here #18220. In this case you can close my [current](https://github.com/PrestaShop/PrestaShop/pull/18628) PR please.

Sorry

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
I don't think this one requires QA :thinking:

**Comment by NeOMakinG** [comment]
@PierreRambaud 

https://github.com/PrestaShop/PrestaShop/pull/18425 has been merged without QA and it looks like it generated a regression regarding to a @khouloudbelguith issue : https://github.com/PrestaShop/PrestaShop/issues/18626

We should really take care on this.

Also there is a message from @PululuK that this PR is closable, wdyt?

**Comment by PululuK** [comment]
> @PierreRambaud
> 
> #18425 has been merged without QA and it looks like it generated a regression regarding to a @khouloudbelguith issue : #18626
> 
> We should really take care on this.
> 
> Also there is a message from @PululuK that this PR is closable, wdyt?

Indeed this PR does not require QA, and even QA can not detect this kind of conflict. It is a special case I think. We have two options, either we revert this one #18425, or we consider this PR (in reality it is a revert)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PululuK

**Pull request merged**
