### PR TITLE
Enabling category canonical redirection

### PR DESCRIPTION
**Pull request by 123monsite-regis**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | FO: enabling category canonical redirection
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Configure Redirect to the canonical URL to 301 or 302 and test all your FO , especially categories

This features exists on 1.6, but is not present on current 1.7 release
(https://github.com/PrestaShop/PrestaShop/blob/1.7.0.5/controllers/front/listing/CategoryController.php#L43 )

### CODE REVIEW

**Comment by aleeks** [comment]
Rebased from develop, is it ok for you @123monsite-regis  ?
Regards

**Comment by 123monsite-regis** [comment]
yes, it is still ok on todays develop' code

**Comment by aleeks** [comment]
@123monsite-regis you tested it after my rebase ?!

**Comment by 123monsite-regis** [comment]
I have test this pull  as a patch , on a fresh developp extract is it necessary to est my whole patch branch after a rebase ?

**Comment by aleeks** [comment]
Hello @123monsite-regis 
I don't think so, let's go to merge!
Thank you!

**Pull request merged**
