### PR TITLE
Update licence headers

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Update licence headers in all project before 1.7.8 release
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | No need
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25029)

### CODE REVIEW

**Review by PululuK — CHANGES_REQUESTED** [review]
See please https://github.com/PrestaShop/PrestaShop/pull/25021

**Comment by sowbiba** [comment]
> See please #25021

@matks When he asks for something and do it himself ...

**Comment by matks** [comment]
> > See please #25021
> 
> @matks When he asks for something and do it himself ...

I just wanted to help 😅

**Comment by sowbiba** [comment]
> > > See please #25021
> > 
> > 
> > @matks When he asks for something and do it himself ...
> 
> I just wanted to help

I know 😂 
Thanks dude ❤️

**Pull request closed without merging**
