### PR TITLE
Stylise list in product short description of quickview

### LINKED ISSUE #23065: error showing description listed in product quick view
#### Describe the bug

When I put a bullet list in the description of an article, it is not shown if I open the quick view of the product
See the video

#### Expected behavior

if I open the quick view of the product, I can see the bullet list in the description of an article

#### Steps to Reproduce

1. **BO**>**SELL**>**Catalog**>**Products**
2. Edit your product
3. Add a bullet list to your product's summary
4. **Save**
5. Click on **Preview**
6. FO, you can see the bullet list in product page
7. Go to **Category** page and click on **quick view** link
8. See error => the bullit list is not displayed

**Screenshots**

https://youtu.be/nY7uM-RmAwQ

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2.29

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | List inside quickview of product were unvisible
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23065
| How to test?      | Add list inside product short description and go on product list, click on quickview and see if color and font-size is the right one
| Possible impacts? | Quickview of product on product lists

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23074)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by alfonsolr09** [comment]
shouldn't this be done in theme.css ??

**Comment by NeOMakinG** [comment]
> shouldn't this be done in theme.css ??

No, it's processed by webpack and sass-loader, which will output theme.css from scss source files, this will be inside theme.css when assets will be built for release!

See 
https://sass-lang.com/
https://webpack.js.org/loaders/sass-loader/
https://webpack.js.org/

for references :)

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
hi @NeOMakinG i have the same bug that  i described in #23073 
see comment => https://github.com/PrestaShop/PrestaShop/pull/23073#issuecomment-771464668
image
The part in red should be a numbered list

**Comment by NeOMakinG** [comment]
> hi @NeOMakinG i have the same bug that i described in #23073
> see comment => [#23073 (comment)](https://github.com/PrestaShop/PrestaShop/pull/23073#issuecomment-771464668)
> image
> The part in red should be a numbered list

I think you tested the version before my commit, let's review it again :)

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SD1982** [comment]
LGTMN !!
image
Thanks @NeOMakinG !!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @SD1982

**Pull request merged**
