### PR TITLE
[WIP] FO: update classic theme to Bootstrap 4.1.1

### PR DESCRIPTION
**Pull request by duGuillaume**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  migrate classic theme from bootstrap alpha 5 et 4.1.1
| Type?         | improvement
| Category?     | FO

Hello,

I tried to migrate classic theme to bootstrap 4.1.1, but I'll need some help to test, I tried to test everything but i think i missed some elements or features.

container class now have 100% width under md breakpoint
her the old applied rule 

.container {
    max-width: 100%;
}
.container {
    width: 540px;
    ~~max-width: 100%;~~
}

here the new one

 .container {
    max-width: 100%;
}
.container {
    ~~max-width: 540px;~~
}

i didn't know if new rule style was wanted or the old one, so i let it at 100%

#### 3 things left to do: 
- Choose what to do with new design rules
- I need anothers eyes to check the theme 
- I tested it on FF, some tests are needed on Chrome / Edge / Opéra / Safari

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9294)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
That's really cool to see the interest in upgrading bootstrap.

To avoid potential compatibility issues, we created a new reprository on which the new classic theme should be stored in: https://github.com/PrestaShop/classic-rocket
@prestarocket and @GuillaumeKadolis, perhaps you should work together to avoid the work being duplicated?

**Comment by prestarocket** [comment]
@GuillaumeKadolis i will push this week my work on the refacto of classic theme. I have added some improvement : last version of BS, lazyloading, offcanvas for menu and filter on mobile, lightweight... 
You can drop me an email if you want to talk : prestarocket@gmail.com

**Comment by duGuillaume** [comment]
@prestarocket if you need help keep me in touch

**Comment by prestarocket** [comment]
@GuillaumeKadolis could you give me your email ? The demo site : https://demo-prestashop.prestarocket.com/ (There are still a couple of small points to fix)

**Comment by mickaelandrieu** [comment]
@GuillaumeGBzh I guess it's ok to say you can contribute to https://github.com/PrestaShop/classic-rocket ? /c  @prestarocket 

> The demo site : https://demo-prestashop.prestarocket.com/ (There are still a couple of small points to fix)

This is awesome already! 

Sorry for the flood :) (can I close?)

**Comment by duGuillaume** [comment]
Yeah it's ok, i send my contacts at @prestarocket by mail (prestarocket@gmail.com), i'll check  https://github.com/PrestaShop/classic-rocket repo. You can close

**Comment by Quetzacoalt91** [comment]
Closing as the work will be done on https://github.com/PrestaShop/classic-rocket

Good luck!

**Pull request closed without merging**
