### PR TITLE
Add message to show who is the employee who created a BO order

### LINKED ISSUE #9676: [BOOM-5292] Order in bo no longer display which employee created it
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-5292).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Wed, 11 Apr 2018 14:22:19 +0200

### Describe the bug
Before in 1.6 version, in the message section we had the employee who created the order.
 It's not the case anymore in 1.7 version

If there is a problem with the order or payment you do not know who created the order, if you have a telephone pool to take orders you can not distribute the sales commissions according to the employees who created the telephone orders.

### Proposed solution

image

### Expected behavior
BO>Order should display which employee has created the Order in the Message block

**PS 1.6.1.20**
image

### Steps to reproduce

1. BO>SELL>Orders>Orders
2. Create an Order
3. Back to Order List
4. View the latest created order
5. Scroll donw to the Message block
6. See error > No info about the employee who created the order displayed in the message block

image

### Additional infos

- PS version: 1.7.8.5
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by Prestaworks**
Fix for issue 9676

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In order to fix #9676 I add a message into the order to show who is the employee who created the order
| Type?             | bug fix
| Category?         |  BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #9676. and also #9783 
| Related PRs       | 
| How to test?      | Add new order from BO, employee information is added as message on order.
| Possible impacts? |

### CODE REVIEW

**Review by matks — COMMENTED** [review]
The solution works for me 👍 and the bug has been there since 2018 so even if we could build something more advanced for this usecase, I think this simple and nice solution is enough.

But I think we should not do this in the Controller. If another controller creates a BO from an order we need this logic to be run too.

Can I suggest to add this logic into https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php ?

**Comment by Prestaworks** [comment]
> The solution works for me 👍 and the bug has been there since 2018 so even if we could build something more advanced for this usecase, I think this simple and nice solution is enough.
> 
> But I think we should not do this in the Controller. If another controller creates a BO from an order we need this logic to be run too.
> 
> Can I suggest to add this logic into https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php ?

hmm is that code even used here? it seems to already have what we want with the order message, but the controller use the formhandler and not the command you linked to?

**Comment by matks** [comment]
> > The solution works for me 👍 and the bug has been there since 2018 so even if we could build something more advanced for this usecase, I think this simple and nice solution is enough.
> > But I think we should not do this in the Controller. If another controller creates a BO from an order we need this logic to be run too.
> > Can I suggest to add this logic into https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php ?
> 
> hmm is that code even used here? it seems to already have what we want with the order message, but the controller use the formhandler and not the command you linked to?

The FormHandler dispatches a Command then received by the CommandHandler who is responsible for the business logic. I might be mistaken about which CommandHandler to modify but the idea is that such business rules should go into CommandHandlers, not Controllers

Reference -> https://medium.com/marmolabs/skinny-models-skinny-controllers-fat-services-e04cfe2d6ae

**Comment by Prestaworks** [comment]
> > > The solution works for me 👍 and the bug has been there since 2018 so even if we could build something more advanced for this usecase, I think this simple and nice solution is enough.
> > > But I think we should not do this in the Controller. If another controller creates a BO from an order we need this logic to be run too.
> > > Can I suggest to add this logic into https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/CommandHandler/AddOrderFromBackOfficeHandler.php ?
> > 
> > 
> > hmm is that code even used here? it seems to already have what we want with the order message, but the controller use the formhandler and not the command you linked to?
> 
> The FormHandler dispatches a Command then received by the CommandHandler who is responsible for the business logic. I might be mistaken about which CommandHandler to modify but the idea is that such business rules should go into CommandHandlers, not Controllers
> 
> Reference -> https://medium.com/marmolabs/skinny-models-skinny-controllers-fat-services-e04cfe2d6ae

I agree, the code seems to be there also, working. It's just it ends up in the paymentModule class and the message there is saved to ps_message and not ps_customer_message. So it's not displayed in the BO since the BO only use ps_customer_message.

Maybe the best way to fix this is to move the message value on validateOrder to customer_message instead? I think the ps_message is some legacy table right?

**Comment by Prestaworks** [comment]
Seems Github closed this PR when I rolled back the changes. 
The new PR is located here
https://github.com/PrestaShop/PrestaShop/pull/28692
it now fixes two issues instead of one.

**Pull request closed without merging**
