### PR TITLE
Fix: date_add field not updated when duplicating a product #34079

### LINKED ISSUE #34079: date_add field not updated when duplicating a product
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you duplicate a product, its date_add field is not updated and remains the same as the original product. It causes missing "New" labels and the product is not listed on the New Products page.

### Expected behavior

When duplicating a product, the new product's date_add should be duplication datetime.

### Steps to reproduce

1. Go to the product listing.
2. Duplicate a product using the bulk action.
OR
1. Go to the product view/edit page of any product.
2. Duplicate the product.

3. Check date_add of newly created product(s) directly from database - they have the original product's date_add values.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description     | Reset product date_add on duplicate product
| Type?             | bug fix 
| Category?         | BO
| Fixed issue or discussion?     | Fixes #34079

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
From looking on the code, it also seems that this piece of code didnt work either. Hmm

$shopProduct->indexed = false;
$shopProduct->active = false;


@PrestaShop/qa-functional Guys can you please check if you duplicate product using new prosuct page, does the new product get disabled? Or the old one?

**Comment by Codencode** [comment]
> From looking on the code, it also seems that this piece of code didnt work either. Hmm
> 
> $shopProduct->indexed = false; $shopProduct->active = false;
> 
> @PrestaShop/qa-functional Guys can you please check if you duplicate product using new prosuct page, does the new product get disabled? Or the old one?

When duplicating, the new product is deactivated and not the original, I tried it.

**Comment by nicosomb** [comment]
⚠️  there is an other pull request to fix this bug: https://github.com/PrestaShop/PrestaShop/pull/34823

**Comment by Codencode** [comment]
> ⚠️ there is an other pull request to fix this bug: #34823

HI @nicosomb,
I know, but I believe that the problem depends on the fact that the system recovers the old product and not the one just duplicated.
I proposed my solution to get feedback from other developers and understand what the best solution is.
Anyway, thanks for pointing that out.

**Comment by kpodemski** [comment]
Hello @Codencode 

This other PR seems to do the job, I think yours changed something that somebody did on purpose. It was about getting the old product but for a given shop context.

**Comment by Codencode** [comment]
> Hello @Codencode
> 
> This other PR seems to do the job, I think yours changed something that somebody did on purpose. It was about getting the old product but for a given shop context.

Hi @kpodemski,
you're right, in fact I hadn't tried the modification with the multishop!
I'm closing the pull request!
Thank you!

**Pull request closed without merging**
