### PR TITLE
Bump version to 8.1.4

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Bump version to 8.1.4
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by M0rgan01 — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Comment by Hlavtox** [comment]
As it's the same PR as all of the before, we can merge it :-) https://github.com/PrestaShop/PrestaShop/pull/34548/files

**Review by nicosomb — APPROVED** [review]

**Comment by matks** [comment]
@Hlavtox @ShaiMagal @nicosomb @M0rgan01 This PR broke the UI tests because they do rely on the version number.

As https://github.com/PrestaShop/distribution-api does not acknowledge 8.1.4 (because it does not exist yet), it does not provide the data needed by UI Tests.

If you had run the UI tests you would have seen it.

So please run UI tests everytime 😄

**Comment by matks** [comment]
This is the PR that will fix the UI tests failure https://github.com/PrestaShop/distribution-api/pull/38/

You need to do this everytime you bump the patch version number

**Comment by Hlavtox** [comment]
@matks I had no idea about this. :-)

I added it here - https://github.com/PrestaShop/PrestaShop/issues/35216
But mainly, it should be added here - https://www.prestashop-project.org/maintainers-guide/processes/release/prestashop/preliminary-tasks/ Could you do it? 🙏

**Comment by matks** [comment]
Here it goes https://github.com/PrestaShop/open-source/pull/252

**Comment by Hlavtox** [comment]
@matks Thank you! :-)

**Pull request merged**
