### PR TITLE
Get non responsive twig component independent

### LINKED ISSUE #33187: Independent twig component: Non responsive
## Description

See #33101 for description in Step 2

This is the Non responsive part.

This component should be quite autonomous.

Blocked by https://github.com/PrestaShop/PrestaShop/issues/33175

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Get non responsive twig component independent
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto tests 🟢 
| Fixed ticket?     | Fixes #33187
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by tleon — DISMISSED** [review]
You have some code style you need to fix before merge. Otherwise good work

**Review by boherm — APPROVED** [review]
LGTM, thanks @lartist!

**Comment by Hlavtox** [comment]
@kpodemski Does it make sense to migrate it? This component is unused.

**Comment by Hlavtox** [comment]
Confirmed to be removed https://github.com/PrestaShop/PrestaShop/pull/33324#issuecomment-1647513407

**Pull request closed without merging**
