### PR TITLE
+[Core] Avoid error if an address was deleted but id still exists in …

### PR DESCRIPTION
**Pull request by Eolia**
…cart table

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi @Eolia,

I'm closing this PR since its on the wrong branch.
Thanks to make it again on 1.6.1.x if you want it to be merged ;)

Best regards,

**Comment by gRoussac** [comment]
Hi,

Can you please report your commit on 1.6.1.x branch ? Or would you mind letting me doing it if you do not ?

Regards

**Comment by Eolia** [comment]
Do what you want, you have the info, I have other things to do than to recreate PR every time.

**Comment by kpodemski** [comment]
Not having possibility to easily change PR branch is simply frustrating

**Comment by gRoussac** [comment]
Ok thanks

**Pull request closed without merging**
