### PR TITLE
Fixed error compile

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixed error compile
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | see image
js

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Review by antoin-m — APPROVED** [review]

**Comment by aleeks** [comment]
PR : https://github.com/PrestaShop/PrestaShop/pull/6861

**Review by PrestaEdit — CHANGES_REQUESTED** [review]
Better will be to use the {l s='' js=1} no ?

**Comment by aleeks** [comment]
Hello @PrestaEdit
Yes, I do not know what I was thinking when I made this PR 👎

Thank you!

**Comment by PrestaEdit** [comment]
Hé hé, no problem ! It's happen, sometimes.

Don't forgot the Pull Request #6861 made on the debug branch, ;-)

**Review by PrestaEdit — APPROVED** [review]

**Comment by aleeks** [comment]
Done here : https://github.com/PrestaShop/PrestaShop/pull/6874

**Comment by maximebiloe** [comment]
Thanks!

**Pull request merged**
