### PR TITLE
Merge 177x into develop 08/09/2020

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Merge 1.7.7.x into develop
| Type?         | improvement
| Category?     | ME
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | ~

Conflicts
```
	both modified:   admin-dev/themes/new-theme/js/pages/order/create/product-renderer.js
	both modified:   admin-dev/themes/new-theme/js/pages/order/view/order-product-add-autocomplete.js
	both modified:   admin-dev/themes/new-theme/js/pages/order/view/order-product-add.js
	both modified:   admin-dev/themes/new-theme/js/pages/order/view/order-product-edit.js
	both modified:   classes/Product.php
	both modified:   src/Core/Domain/Product/Command/RemoveAllProductsFromPackCommand.php
	both modified:   src/Core/Domain/Product/Supplier/Exception/ProductSupplierConstraintException.php
	both modified:   tests/Integration/Behaviour/Features/Context/Domain/OrderFeatureContext.php
	both modified:   tests/UI/pages/BO/shopParameters/productSettings/index.js
	both modified:   themes/_core/js/theme.js
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20898)

### CODE REVIEW

**Comment by matks** [comment]
> Hi, thanks for this contribution!
> 
> I found some issues with the Pull Request description:
> 
> * Your pull request does not seem to fix any issue, consider [creating one](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (see note below) and linking it by writing `Fixes #1234`.
> 
> Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
> 
> ### About linked issues
> Please consider opening an issue before submitting a Pull Request:
> 
> * If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
> * It can help trigger a discussion about the best implementation path before a single line of code is written.
> * It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.
> 
> (Note: this is an automated message, but answering it will reach a real human)

✋

**Comment by matks** [comment]
Behat tests failing

- Features/Scenario/Order/order_shipping.feature
- Features/Scenario/Product/update_shipping.feature

https://travis-ci.com/github/PrestaShop/PrestaShop/jobs/382410347
```
--- Failed steps:
001 Scenario: Use a carrier that depends on price, add product to change order total the shipping price should update as well # Features/Scenario/Order/order_shipping.feature:28
      Then I should get error that carrier is invalid                                                                         # Features/Scenario/Order/order_shipping.feature:30
        Last error should be "PrestaShop\PrestaShop\Core\Domain\Cart\Exception\CartConstraintException", but got "null" (RuntimeException)
002 Scenario: Use a carrier that depends on weight, add product to change order total the shipping price should update as well # Features/Scenario/Order/order_shipping.feature:119
      Then I should get error that carrier is invalid                                                                          # Features/Scenario/Order/order_shipping.feature:121
        Last error should be "PrestaShop\PrestaShop\Core\Domain\Cart\Exception\CartConstraintException", but got "null" (RuntimeException)
003 Scenario: Use default carrier, then update the order carrier      # Features/Scenario/Order/order_shipping.feature:210
      And order "bo_order1" should have "weight_carrier" as a carrier # Features/Scenario/Order/order_shipping.feature:220
        Order bo_order1 should have weight_carrier as a carrier, expected id_carrier to be 4 but is 2 instead (RuntimeException)
004 Scenario: When shipping recalculate is disabled the shipping is not updated # Features/Scenario/Order/order_shipping.feature:291
      And order "bo_order1" should have "weight_carrier" as a carrier           # Features/Scenario/Order/order_shipping.feature:302
        Order bo_order1 should have weight_carrier as a carrier, expected id_carrier to be 4 but is 2 instead (RuntimeException)
005 Scenario: I update product shipping                                 # Features/Scenario/Product/update_shipping.feature:8
      Then product product1 should have following shipping information: # Features/Scenario/Product/update_shipping.feature:34
        Unexpected carrier references in product shipping information
        Failed asserting that two arrays are equal.
        --- Expected
        +++ Actual
        @@ @@
         Array (
        -    0 => 0
        -    1 => 0
         )
006 Scenario: Only update product dimensions without changing other values # Features/Scenario/Product/update_shipping.feature:45
      Given product product1 should have following shipping information:   # Features/Scenario/Product/update_shipping.feature:46
        Unexpected carrier references in product shipping information
        Failed asserting that two arrays are equal.
        --- Expected
        +++ Actual
        @@ @@
         Array (
        -    0 => 0
        -    1 => 0
         )
007 Scenario: Provide negative product dimensions                        # Features/Scenario/Product/update_shipping.feature:72
      Given product product1 should have following shipping information: # Features/Scenario/Product/update_shipping.feature:73
        Product width expected to be "15", but is "10.5" (RuntimeException)
543 scenarios (536 passed, 7 failed)
7945 steps (7845 passed, 7 failed, 93 skipped)
```

**Review by jolelievre — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by matks** [comment]
Behat test failing for php7.2 only (!!!):
```
Failed steps:
001 Scenario: Add product with regular price, add it again with different specific price The first price is updated # Features/Scenario/Order/order_specific_prices.feature:26
      Given I update order "bo_order1" status to "Payment accepted"                                                 # Features/Scenario/Order/order_specific_prices.feature:60
        Notice: Undefined index: displayPrice in /home/travis/build/PrestaShop/PrestaShop/var/cache/test/smarty/compile/d8/0e/7d/d80e7d627dd7d65531893bc85bd570998d13d761_0.file.invoice.tax-tab.tpl.php line 96
```

Re-running...

**Comment by matks** [comment]
It's not a random CI failure 🤯 the test is failing for php7.2 only.

EDIT: let's double-check by re-running ALL php versions

**Comment by matks** [comment]
Closing in favor of https://github.com/PrestaShop/PrestaShop/pull/20939

**Pull request closed without merging**
