### PR TITLE
Add hook overrideCartSubtotals and hook overrideOrderSubtotals

### PR DESCRIPTION
**Pull request by webmak**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add hook overrideCartSubtotals to CartPresenter And hook overrideOrderSubtotals to OrderPresenter
| Type?         | new feature
| Category?     | CO
| BC breaks?    |no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  |-

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7757)

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @webmak 
If you want add new hooks, you have to add them on hook.xml & add a sql query in 1.7.1.2.sql (install-dev/upgrade/sql/) for example 

Regards

**Comment by webmak** [comment]
Hello @aleeks 
It is not required. You just need to puth this code and if module need hook then module will register it in db. It not need to be stored in db from default.

**Comment by aleeks** [comment]
I know but like this, we don't know how this hook is for. No name, no description..
Moreover, I think this name is not ok, maybe, must start with action/display/ or filter isn't @maximebiloe  ?

**Comment by webmak** [comment]
@aleeks
In my case it was neede to override free shipping text for different carries in my module. So I've add this name because you can override subtotals in module. Because vars are passe by link

**Comment by maximebiloe** [comment]
I agree with @aleeks, it would be better to add the hooks in `hook.xml` and into the sql upgrade file.
Also, the add of new hooks, can only be done into minor versions, not patches, so I change the destination branch of your PR.

**Comment by webmak** [comment]
@maximebiloe Do what you think correct) I was traing to help. But it take to much time to comunicate

**Comment by Progi1984** [comment]
Hello @webmak , thanks for your contribution, would you mind to rebase your pull request? Thanks

Reference : https://anavarre.net/how-to-rebase-a-github-pull-request/

**Comment by PierreRambaud** [comment]
Hi @webmak ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
