### PR TITLE
Fix a bug where you couldn't select an image in TinyMCE after saving it

### LINKED ISSUE #11011: JavaScript error in console when editing an image in TinyMCE - BO CMS Page
**Describe the bug**
issue JS when editing a CMS page with an image in the wysiwyg

**To Reproduce**

1. Go to Design > Pages
1. Edit a CMS page
1. Add an image in the wysiwyg editor & save
1. Edit the CMS page and click on the image in the wysiwyg editor
1. See error, you can't edit the image

**Screenshots**
capture d ecran!UNITO-UNDERSCORE!437

**Additionnal information**
PrestaShop version: 1.7.4.3
PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When you saved an image in a TinyMCE editor, you couldnt select it anymore
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #11011
| How to test?  | Go in Appearance -> Pages, edit a page, add an image then save the page, you should be able to select the image again and modify it

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16583)

### CODE REVIEW

**Comment by matks** [comment]
@NeOMakinG Would it be possible to provide us the snippet of modified code ? 😅 as it's minified here, it's un-reviewable.

**Comment by NeOMakinG** [comment]
It's nowhere in the core repository... Only the tinymce.min is present

**Comment by matks** [comment]
> It's nowhere in the core repository... Only the tinymce.min is present

But what did you do in this PR ? 😛 there's no way to understand it from the committed file.

**Comment by PierreRambaud** [comment]
Agree with @matks we can't accept this kind of pull request.

**Comment by NeOMakinG** [comment]
Changed `c.getSel().setBaseAndExtent(e,0,e,1)` to `c.select(e)` (From this thread : https://github.com/tinymce/tinymce/issues/3611#issuecomment-304384844) in order to wait for a migration to a new version

Then tested it

**Comment by NeOMakinG** [comment]
So, TinyMCE 4.x branch isnt buildable due to 40+ TS errors...

**Comment by PierreRambaud** [comment]
@PrestaShop/prestashop-core-developers what do you think, should we merge?
I'm still not in favor of merging this kind of change :/

**Comment by NeOMakinG** [comment]
Well, or we merge this, or we manage to migrate to the latest TinyMCE version which can be huge, I couldn't find a way to build this version of TinyMCE properly...

**Comment by PierreRambaud** [comment]
It can be huge, but it should be done instead of custom tweak :thinking:

**Comment by NeOMakinG** [comment]
#17651 fixes it

**Pull request closed without merging**
