### PR TITLE
BO: product page - wording updates, part 1

### PR DESCRIPTION
**Pull request by AlexEven**
@vincentbz  & @Leadesign >> Please check if it's alright with you!

| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Wording for product page, to match mock-ups and improve display. |
| Type? | Improvement |
| Category? | BO |
| BC breaks? | Of course no |
| Deprecations? | Nope |
| Fixed ticket? | Don't know |
| How to test? | N/A |

### CODE REVIEW

**Comment by xBorderie** [comment]
good job _ef4e56b1cd0fc955e62bdb74048c6444

**Comment by xBorderie** [comment]
Two things:

* Shouldn't the "Women" category be renamed "Womenswear"? 'cos we're not actually selling women, right?
* Since we plan on changing the demo catalog, is my question above still warranted?

**Comment by AlexEven** [comment]
Since we'll change the demo catalog, I wouldn't worry about this now!

**Comment by xBorderie** [comment]
I'll PR that for `1.6.1.x` then ;)

**Pull request merged**
