### PR TITLE
BO: Bad example value for "Default group ID" column

### PR DESCRIPTION
**Pull request by jordisan**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6 |
| Description? | Fix error in sample CSV file |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Check sample CSV file |

### CODE REVIEW

**Comment by jordisan** [comment]
Updated contribution table

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by aleeks** [comment]
Hello @jordisan 
Can you please rename your commit name ? Tell me if it's ok for you.
Thank you!

**Comment by jordisan** [comment]
@aleeks , 
I'm sorry, but I proposed this change from the web interface; I don't have a local repository for thisproject and I'm not going to lose a couple of hours just to add three characters.

**Comment by aleeks** [comment]
hello @jordisan 
Ok, no problem, I'm closing this PR and make one other from your idea.
Thanks

**Pull request closed without merging**
