### PR TITLE
Remove wholesale price suppliers synchronicity

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In the page V2 development we introduced a synchronicity between product/combination wholesale price and the default supplier's price. After discussion with @kpodemski @Hlavtox and @MatShir we realized that it's not such a good idea as it prevents using the wholesale price independently for custom purposes So the synchronicity is removed in this PR
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | CI green and auto campaigns green, not sure it needs some functional QA
| Possible impacts? | ~

### CODE REVIEW

**Review by zuk3975 — DISMISSED** [review]

**Comment by jolelievre** [comment]
I just ran the campaigns for this PR https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3846786165

**Review by FabienPapet — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Comment by kpodemski** [comment]
Automatic tests:
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/3857189432

**Comment by kpodemski** [comment]
@jolelievre automated tests are green, I guess there's no need for a manual QA on this one

btw. you deprecated `supplier_reference`, is that on purpose?

**Comment by jolelievre** [comment]
Hi @kpodemski 
I think it doesn't need manual QA since it mostly removes a behaviour and I tested it everything is fine, besides a QA session of the whole page is planned for next week, but to be confirmed with the QA team I guess.

About `supplier_reference` yes it's on purpose, it's redundant with the data already available in the supplier's table which can be fetched via a join, we already deprecated it on Product but we forgot to do it on Combination.

**Pull request merged**
