### PR TITLE
Multistore - Design > Position - Do not display content and update message in all shops or in a group context

### LINKED ISSUE #19424: Multistore - Design > Position - Do not display content and update message in all shops or in a group context
Currently, this page isn't working in all shops or in a group context
The current information message is "If you want to order/move the following data, please select a shop from the shop list." 

To avoid bad behaviors and for a better understanding, we should display ONLY the information message in these contexts and update the current message for the following one:
"Note that this page is available in a single shop context only. Switch context to work on it."

This is specified in the [multistore specials cases specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-5-the-page-is-displayed-only-when-a-specific-shop-is-selected)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Multistore - Design > Position - Do not display content and update message in all shops or in a group context
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #19424
| How to test?      | Cf. #19424

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27669)

### CODE REVIEW

**Review by Julievrz — DISMISSED** [review]
Wording ✔️

**Review by saulaski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thank @Progi1984 
This page will probably need some improvements in the future:
- remove the use of `@Template` annotation
- use a simplified form

But it's not the scope of the issue ^^

**Comment by Progi1984** [comment]
@jolelievre Could you create an issue and assign it to me ? I will do with pleasure.

**Comment by jolelievre** [comment]
@Progi1984 We'll need to discuss this with @PrestaShop/product-team I guess, I don't know if this was already planned at some point

I found two issues related to this page already, so maybe it's better to do everything at once? (one of them looks like an epic):

https://github.com/PrestaShop/PrestaShop/issues/21092
https://github.com/PrestaShop/PrestaShop/issues/10568

**Review by AureRita — CHANGES_REQUESTED** [review]
Hello @Progi1984,

I tested your pr and I noticed that the text is correctly changed but : 
with "All store" it's a warning message and not an information message, as you can see 

All groups with warning message
image

And, with the group shop, you've the same issue and this is not the "ONLY" message as you can see : 

Group shop with two messages 
image

**Review by jolelievre — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by AureRita — CHANGES_REQUESTED** [review]
I tested it and the message's type is correctly changed, 

as we can see here : 

On all group, We have only the correct info message 
image


On group shop, the information message is correct, but it's not the only one 
image

@MatShir or @marionf, must we have two messages or only one in the second case ? 

to get two messages :

When you create your second shop, DON'T change the color of the group 
(if you need more information, I can do it point by point )

**Comment by Progi1984** [comment]
Ping @PrestaShop/product-team for the question from @AureRita

**Comment by MatShir** [comment]
From the spec here https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/multistoregeneralspecs.md and https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/broader-topics/multistorespecialsspecs.md, it seems to be the normal behavior if the color of the header is not set for the group shop.

**Comment by MatShir** [comment]
If it is the only bug left, I guess the PR is QA validated @AureRita ?

**Review by AureRita — APPROVED** [review]
Hi @MatShir ,

Thank you for your answer, and yes indeed, the PR is QA approved

**Comment by Progi1984** [comment]
Thanks @AureRita @florine2623 & @MatShir

**Pull request merged**
