### PR TITLE
Wording for 8.1.0 release

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Wording updates for 8.1.0 release
| Type?             | improvement
| Category?         | LO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Translations are ok
| Fixed ticket?     | Fixes partially https://github.com/PrestaShop/PrestaShop/issues/32460
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/32147
| Sponsor company   | PrestaShop

### CODE REVIEW

**Comment by l-delin** [comment]
Hello, looks good to me. Wording ☑️ Thanks!

**Review by jolelievre — APPROVED** [review]
Thanks @0x346e3730

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4945324703

**Review by mflasquin — APPROVED** [review]

**Comment by 0x346e3730** [comment]
Everything is green, merging

**Pull request merged**
