### PR TITLE
Prevent checking nonsupported image formats

### LINKED ISSUE #33424: Image - Avif format doesn't works when I regenerate the thumbnail
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I want to regenerate the thumbnail with the new feature image, if I enable the Avif, I've a red screen as you can see : 

[Untitled_ Jul 26, 2023 3_40 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/cd9cef5f-2987-4a18-a96d-9a99729bcb76)

### Expected behavior

I expected that I have no red screen on it

### Steps to reproduce

1. Go to BO > Advanced Parameters > New & Experimental Features 
2. Enable Multiple Image Format 
3. Go to BO > Image Settings
4. Try to Enable Avif, even if your bowser doesn't enable it for you 
5. Save it 
6. Scroll down and Clic on Regenerate thumbnails, Regenerate :x: **Error** You'll have a red screen 
7. **Bonus** If you go on FO, you'll have a **Fatal Error**

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Prevents certain people from trying to break the software by altering the HTML.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Follow steps in related issue.
| Fixed ticket?     | Fixes #33424
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]
Please target 8.1.x branch.

**Comment by Hlavtox** [comment]
Fixed, you can re-review guys, thanks! @M0rgan01 @boherm @matthieu-rolland

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @Hlavtox , 

LGTM , 

[pr33428.webm](https://github.com/PrestaShop/PrestaShop/assets/115152460/977e9f62-2c8e-46a8-b869-dd55a13192fb)

Automated tests :   ( https://github.com/PrestaShop/PrestaShop/actions/runs/5709579345 ) 

It's QA approved :heavy_check_mark: 
thank  you  !

**Comment by Hlavtox** [comment]
@djoelleuch Thank youuuuu!

**Pull request merged**
