### PR TITLE
Show the category block in the list page on first page only

### LINKED ISSUE #9512: [BOOM-6248] [SEO OPTIMIZATION] Category page : remove category title block after page 1
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-6248).

- _**Reporter:**_ Bilal
- _**Created at:**_ Tue, 14 Aug 2018 18:16:43 +0200

<p>On category pages, bloc including title description and image of the category should only appear on page 1.</p>

<p>We should remove this bloc on all pages (except on the first page). In order to avoid duplicate content. </p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Show the category block in the list page on first page only for SEO purposes
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9512 
| How to test?  | Go to a category with several pages (if needed change the number of displayed product in Admin / Shop Parameters / Product Settings), go to seconde page using the url (a simple click updates the current page thanks to ajax calls), the category bloc is not present any more WARNING: be sure to clear your cache so that the Javascript is updated

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9459)

### CODE REVIEW

**Comment by jolelievre** [comment]
@eternoendless hello
I made the modification we talked about with the new id directly on the h2 tag
Is it ok for you?

**Comment by jolelievre** [comment]
@eternoendless hell PR rebase and assets rebuilt, can you validate it please?

**Review by PierreRambaud — APPROVED** [review]

**Comment by jolelievre** [comment]
thanks @PierreRambaud 
I wait for the build succeed before merging

**Review by eternoendless — APPROVED** [review]
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9459)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[controllers/front/listing/CategoryController.php, line 145 at r1](https://reviewable.io/reviews/prestashop/prestashop/9459#-LKv91uH6Jl568z83TTL:-LKv91uH6Jl568z83TTM:bwtof7o) ([raw file](https://github.com/prestashop/prestashop/blob/68beb5bcdc00806a6531b9996d0ca6e54e27d45e/controllers/front/listing/CategoryController.php#L145)):*
> ```PHP
>     {
>         $data = parent::getAjaxProductSearchVariables();
>         $rendered_products_header = $this->render('catalog/_partials/category-header', array('listing' => $data));
> ```

Keep in mind that 3rd party themes (not based in classic) won't have this partial initially. What happens in that case?

**Review by eternoendless — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9459)* status: all files reviewed, 1 unresolved discussion (waiting on @jolelievre)

**Comment by jolelievre** [comment]
@eternoendless in another theme the user won't have this feature available, the render in ajax will fail silently (returning an empty string), and the id allowing to replace the content won't exist
so no BC breaks, waiting for your review acceptance to merge ;)

**Review by eternoendless — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9459)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by eternoendless** [comment]
Thank you @jolelievre

**Comment by rdy4ever** [comment]
Ok. May I ask "why?". Google[ knows what a header is](https://moz.com/community/q/headers-footers-count-as-duplicate-content) and we're talking here about a listing page with pagination. Google also knows that a header element on each page of a listing is not duplicate content. Wouldn't it be much simple just to mark the category header block as `<header>`?
Also, category pages already have the `link rel="canonical"` set, so Google understands that the subsequent pages are part of the main category page.
Plus, with this PR all the other then first pages would miss the H1 tag.
To me this looks like unnecessary  added complexity.

**Pull request merged**
