### PR TITLE
Don't use 0 value for carrier name

### LINKED ISSUE #25800: [BO][Carriers] Can't not filter by the first demo carrier (with id=1)
#### Describe the bug
Cannot find default carriers when filtering by its name

#### Expected behavior
Carriers displayed

#### Steps to Reproduce

1. Fresh install shop
2. Go to BO > Carriers page
3. Filter By the name of the first carrier on the list (id=1) (the name should contain 0)
4. See error : Table is empty
5. Click on Edit of the first carrier
6. Just click on Save
7. Back to the list
8. Filter by name => the first carrier is well displayed

**Screenshots**
image
image

#### Additional information

* PrestaShop version: 1.7.6.7 & 1.7.7.7 & 1.7.8.0
* PHP version: 7.3

### LINKED ISSUE #27305: statscarrier - the name of the carrier ID 1 is not correct
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

At the installation, the name of the carrier with ID 1 is `0` instead of the name given in Shipping > Carriers.
Screenshot 2022-01-11 at 14 56 46

Once I modify the name of the carrier, I have the penultimate carrier name :
Screenshot 2022-01-11 at 15 03 11

### Expected behavior

It should be the same name as what we have in Shipping > Carriers

### Steps to reproduce

1. Go to BO > Stats > Carrier distribution
2. See that one carrier is named 0
3. Go to Shipping > Carriers
4. Change name of carrier ID 1 with "hello world"
5. Go back to BO > Stats > Carrier distribution
6. See that name is updated with initial name instead of "hello world"

### PrestaShop version(s) where the bug happened

1.7.8.x, develop

### PHP version(s) where the bug happened

7.3, 7.4

### If your bug is related to a module, specify its name and its version

statscarrier v2.0.1

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Cannot find default carriers when filtering by its name for the first  carrier created by the installation
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/25800 Fixes https://github.com/PrestaShop/PrestaShop/issues/27305
| How to test?      | See issue
| Possible impacts? | 

**:notebook: BC break** 

If a merchant never update the demo carrier, he will see 0
Remove : 

- `Carrier::getCarrierNameFromShopName`
- `Cart::replaceZeroByShopName`
- AdminCarrierController : `getList`

**:notebook: Informations** 

This PR replace : https://github.com/PrestaShop/PrestaShop/pull/26071

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26071)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by matks — COMMENTED** [review]
Ohlala ... what crazy code you have found @okom3pom !

So basically a carrier whose name is zero will be "magically" replaced, in the BO interface, by the shop name?

I ... don't understand the idea behind. Or maybe something related to multishop?

I ask because I think it would be safer for us to fully understand the idea - even though it seems crazy - so we _know_ what we are removing

**Comment by ghost** [comment]
Hello,

I don't think it has anything to do with the multishop.

This code has been causing a lot of problems for years.

There are also bugs in the carrier modules when you don't know this piece of code

**Comment by matks** [comment]
> I don't think it has anything to do with the multishop.

Then what is that code supposed to do 🤯 😅 ?

I think it was written with a purpose. If we cannot find this purpose and we approve & merge this PR we might break an eligible and valid behavior of the software 😭

**Comment by ghost** [comment]
I found when this code started.

https://github.com/PrestaShop/PrestaShop/commit/cc65b4e0cb7c1b3b7bf8ac07f09fd7669b96bf74#diff-9cc4f715b26cedae04644d9ad82357494906498542fbc615f2e1f21bc4b3556eR639-R642

At installation the carrier name is 0 since 1.5.0.0

**Review by Progi1984 — DISMISSED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello @okom3pom,

Could you please check the conflicting files?

Thanks,

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello, 

I tested the PR and I noticed the following issues :
1. The carrier name is now "click and collect" instead of the shope name.

image
image

2. When editing the carrier name from shipping> carriers , the name is not changed in the page stats> carrier distribution. 
https://watch.screencastify.com/v/MrAl5xcviYWkCCwWenAL

Could you please check? 

Thanks,

**Comment by ghost** [comment]
Hi @marwachelly this is normal behaviour. I  did a[ PR in SPEC for this](https://github.com/PrestaShop/prestashop-specs/pull/233)

Regards Thomas

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello,

I still miss the following information :

@PrestaShop/product-team Is the default name for a carrier should be "click and collect" instead of the shop name? 
Could you please check the first point in the [comment](https://github.com/PrestaShop/PrestaShop/pull/27439#pullrequestreview-898757293) ?
Ps: Without PR the default carrier name is the same as the shop name.

Thanks,

**Review by jolelievre — APPROVED** [review]
Hi @marwachelly

from what I understand from this PR this is the purpose that the carrier from fixtures now behave as the other and has its own name instead of an automatic fallback with the shop name. It also fixes the two issues referenced in the description this way.

This should be confirmed by @PrestaShop/product-team though I guess

**Comment by MatShir** [comment]
To double-check, the carrier after an edition creates a new carrier with a new ID with its new name. So if the product was distributed with the old carrier then on stats, we will see the old carrier name. We will be able to see the new carrier name only when the new carrier will be used in a new order.
So the bugs are fixed, but the carrier system is, to avoid being vulgar, let's say that it needs to be revamped.
Is the PR okay then @marwachelly ?

**Comment by kpodemski** [comment]
@MatShir 

> So the bugs are fixed, but the carrier system is, to avoid being vulgar, let's say that it needs to be revamped.

What do you mean exactly? new ID when editing a carrier? 🤔

**Comment by marwachelly** [comment]
> 

Thank you @MatShir for your response. Just I need your confirmation regarding the carrier name. With this PR the default carrier name is changed to "click and collect" instead of the shope name.

**Comment by marwachelly** [comment]
> To double-check, the carrier after an edition creates a new carrier with a new ID with its new name. So if the product was distributed with the old carrier then on stats, we will see the old carrier name. We will be able to see the new carrier name only when the new carrier will be used in a new order. So the bugs are fixed, but the carrier system is, to avoid being vulgar, let's say that it needs to be revamped. Is the PR okay then @marwachelly ?

Thank you @MatShir for your response. Just I need your confirmation regarding the carrier name. With this PR the default carrier name is changed to "click and collect" instead of the shope name.

**Comment by MatShir** [comment]
> @MatShir
> 
> > So the bugs are fixed, but the carrier system is, to avoid being vulgar, let's say that it needs to be revamped.
> 
> What do you mean exactly? new ID when editing a carrier? 🤔

If you edit the carrier, it soft-deletes the carrier and create a new one linked to the old one cf.https://github.com/PrestaShop/prestashop-specs/pull/233

@marwachelly If you make a new order with the same carrier, what it is displayed in the carrier distribution?

**Comment by kpodemski** [comment]
@MatShir 

I know, but it's good behavior to avoid losing of the historical data, I was wondering what you meant by:
>the carrier system is, to avoid being vulgar, let's say that it needs to be revamped

btw. @okom3pom 

maybe it would be good to update the Carrier name in the `autoupgrade` module if it's equal to 0?

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello @MatShir ,

Without PR the default name was the same as the shop name:

https://user-images.githubusercontent.com/89604350/160153418-f7eeca1d-b814-48db-a383-04ae6895705d.mp4

with PR the default name is Click and collect

https://user-images.githubusercontent.com/89604350/160153523-f48a7fc5-be92-4a4b-babc-ab1290464414.mp4

Is that the wanted behavior?

Regarding the edit of carrier I think the behavior is as mentioned in the spec

https://user-images.githubusercontent.com/89604350/160153772-7d5d8d54-be34-4582-b310-21e9026ebb24.mp4

Could you please check? 
Many thanks

**Comment by MatShir** [comment]
@kpodemski IMO the interface should be more explicit of how is it behaving. So merchant understand more why a new carrier is created and that some data will still be present. For me, It should update the carrier with the same ID, and it has to be the orders that should not be updated to keep the history, from what I could quickly understand.

@marwachelly I didn't know the carrier was taking the shop name. PR is changing this to fix bugs by putting in hard wording, so it doesn't rely on 0 value anymore. I find Click and Collect to be more generic and clear. Let’s go with that ! :)

**Comment by marwachelly** [comment]
> @marwachelly I didn't know the carrier was taking the shop name. PR is changing this to fix bugs by putting in hard wording, so it doesn't rely on 0 value anymore. I find Click and Collect to be more generic and clear. Let’s go with that ! :)


[MatShir](https://github.com/MatShir), 
Verry nice !
Thanks a lot,

**Comment by jolelievre** [comment]
Hi @marwachelly since @MatShir validated the new behaviour is the PR QA validated or there was still other bugs?

**Review by marwachelly — APPROVED** [review]
Hello, 

PR is tested and the bug is fixed. As agreed with @MatShir:

- The default carrier name is changed to "Click and collect
-  When you edit a carrier a new carrier is created and it keeps a link with the old one with the id_reference (the stats of the old carrier will displayed in the carrier distribution)

Thanks All,

**Comment by Progi1984** [comment]
Thanks @okom3pom & @marwachelly & @MatShir

**Pull request merged**
