### PR TITLE
Modify CustomerAddressFormatter.php

### PR DESCRIPTION
**Pull request by sirius82**
With PS 1.7.2.2, if DNI is enabled in Customers -> Address, and not enabled in Countries -> countries where DNI is not mandatory, a 500 error occurs for these countries after submitting of the address. It's necessary to unable DNI in Customers -> Address and enable it in Countries only for these where the DNI is mandatory (like Italy, ...). For these countries, "Optional" cannot be display near this field. So this code get this field Required for these countries.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | With PS 1.7.2.2, if DNI is enabled in Customers -> Address, and not enabled in Countries -> countries where DNI is not mandatory, a 500 error occurs for these countries after submitting of the address.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Disable DNI in Customers -> Address and enable it in Countries only for these where the DNI is mandatory (like Italy, ...). For these countries, "Optional" cannot be displayed near this field. So this code gets this field Required for these countries. If it's not filled, the message "This field is required" is displayed.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8917)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @sirius82,

would you mind completing the contribution table? We can't merge a pull request without the complete contribution table.

Regards

**Comment by sirius82** [comment]
Hi ! I'm sorry I don't find where I can complete my contribution !

**Comment by mickaelandrieu** [comment]
@sirius82 you can edit your pull request description 
capture

**Comment by sirius82** [comment]
Sorry ! I didn't see it before. It's done.

**Comment by mickaelandrieu** [comment]
Thank you @sirius82 !

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8917#-:-LATK4Yw3N1-EsH5Ig3G:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Thanks @sirius82

**Comment by ntiepresta** [comment]
Thank you @sirius82 for your contribution
This PR solves this bug: http://forge.prestashop.com/browse/BOOM-3848
Can you complete the "fixed ticket" section ?

**Comment by marionf** [comment]
Hello @sirius82 

I don't check DNI as required 

capture du 2018-04-23 11-10-55


But I add it in the Italy country

capture du 2018-04-23 11-12-00


The DNI field is optional, while it shouldn't

capture du 2018-04-23 11-12-37


Now, I check DNI as required

capture du 2018-04-23 11-16-38


I don't add it for France country

capture du 2018-04-23 11-17-00


When I try to order with an address in France I can't because I don't filled the DNI field

capture du 2018-04-23 11-17-14

This is the expected behavior: 
The DNI field is checked as required, it should be mandatory only for countries in which it has been added in address format.

Can you edit your PR to implement this behavior ?

**Comment by sirius82** [comment]
Hello Marion I suppose you're french ? Donc je continue en français. Quelle version de Prestashop ?
Pour 1.7.2.2 j'ai dû recourir à cette méthode sinon erreur 500 pour un français. Je viens de tester encore une fois, et je n'ai pas de souci pour remplir l'adresse.

In english : I had to do that for 1.7.2.2 because I had an error 500 for french customers without dni.
I just test again and I have not problem with this method.

**Comment by marionf** [comment]
@sirius82 
Yes I am French :)
I tested your PR and there isn't the error 500 anymore which is a great thing. But I think we can improve the behavior as I told you. If you can do it, it will be awesome :)

**Comment by sirius82** [comment]
@marionf do you have changed the file CustomerAddressFormatter.php  ?
1) DNI unabled in the address settings
2) DNI enabled only for countries where it's mandatory (not for France then)
3) Adding this code in CustomerAddressFormatter.php as you can see here : https://github.com/PrestaShop/PrestaShop/pull/8917/files
` if ($field === 'dni' && $this->country->need_identification_number) {
              $formField->setRequired(true);
                 }`

Following that :
1) the field DNI is not marked as optional in the form for Italian customer
2) the field DNI doesn't display in the form for french customer
3) no error when the french customer sends the form

En français car mon anglais n'est pas top : 
1) il faut désactiver les DNI dans les réglages des adresses
2) activer DNI seulement pour les pays où c'est requis
3) ajouter la modification dans le fichier CustomerAddressFormatter.php (voir le lien du fichier modifié) qui ajoute une condition : si DNI ajouté pour un pays et requis, alors la valeur "requis" est vraie. Quand c'est faux, le mot Optionnel est affiché. Quand c'est vrai, il n'y a rien (ce que je ne trouve d'ailleurs pas très évident ...)

En suivant cela : 
1) le champ DNI n'est plus marqué Optionnel pour les Italiens
2) le champ DNI n'apparaît pas sur le formulaire pour Français
3) si un Italien ne le remplit pas un message lui indique que le champ est obligatoire. 
4) Un Français peut envoyer son formulaire sans problème.

**Comment by marionf** [comment]
@sirius82 
1) J'applique les changements sur le fichier CustomerAddressFormatter.php

2) J'ai 2 comptes clients:
- 1 avec une adresse en France et le champ DNI non renseigné
- 1 avec une adresse en Italie et le champ DNI non renseigné

3) Le champs DNI n'est pas coché dans Clients > Adresses

capture du 2018-04-23 11-10-55

4) Le champs DNI est ajouté dans le format de l'adresse pour le pays Italie, mais pas France

capture du 2018-04-23 11-12-00

capture du 2018-04-23 11-17-00

5) J'essaye de passer une commande avec l'adresse en France -> le champ DNI n'est pas renseigné -> je peux valider la commande -> OK

6) J'essaye de passer une commande avec l'adresse en Italie -> le champ DNI n'est pas renseigné (optional) -> Je peux valider la commande -> NOT OK

capture du 2018-04-23 11-12-37

7) Je coche le champs DNI dans Clients > Adresses

8) J'essaye de passer une commande avec une adresse en France -> le champ DNI n'est pas renseigné -> je peux pas valider la commande -> NOT OK

capture du 2018-04-23 11-17-14

9) J'essaye de passer une commande avec une adresse en Italie -> le champ DNI n'est pas renseigné,  -> je peux pas valider la commande -> je le renseigne -> OK

Le comportement que nous souhaitons est le suivant:
Si le champs DNI est coché comme requis dans Clients > Adresses, il devrait être obligatoire seulement pour les pays dans lesquels il a été ajouté (adresse format dans International > Localisation > Pays)

**Comment by sirius82** [comment]
Justement, c'est le comportement que provoque la ligne ajoutée dans CustomerAddressFormatter.php : que si le champ DNI est requis dans le formulaire du pays, il ne soit pas mis comme optionnel.
Je vois sur vos copies d'écran que pour l'Italie, vous avez ajouté DNI dans les champs mais vous n'avez pas modifié le curseur en bas pour le rendre obligatoire.

Voici mes réglages
1) champs requis dans Adresses
champs-requis-adresses

2) réglages formulaire français
reglages-formulaire-france

3) réglages formulaire italien 
reglages-formulaire-italie

4) les lignes ajoutées sont les lignes 100 à 104 dans la boucle 
`if (count($fieldParts) === 1)`
Il y a d'abord le if concernant le postcode, puis le if pour le dni
ajout-100-customeraddressformatter

5) le formulaire vu par le client français
formulaire-client-france

6) le formulaire vu par le client italien. Notez que la mention Optionnel (ou Facultatif) n'apparaît pas à côté du champ DNI.
formulaire-client-italien

7) Le client français peut valider son formulaire, pas d'erreur.
adresse-valide-france

8) si le client italien ne remplit pas le champ dni, l'erreur lui est signalée
erreur-validation-formulaire-italien-sans-dni

**Comment by marionf** [comment]
Ok, je n'avais pas activé le need_identification_number dans le pays.
La condition est donc faite là dessus.

Le problème est que si j'ai une adresse en Italie sans DNI renseigné et que je passe  need_identification_number à Yes, alors mon client Italien peux commander:

capture du 2018-04-24 17-48-29

Mon client Italien ne devrait pas être mesure de commander et devrait être obligé à modifier son adresse comme ceci:

capture du 2018-04-24 17-50-04

-> Ceci fonctionne si je coche DNI dans Clients > Adresses

La seconde condition devrait donc se faire sur le DNI dans Client > Adresses et non sur le need_identification_number dans le pays.

**Comment by sirius82** [comment]
C'est là le bug, quand on met DNI obligatoire dans Clients -> Adresses. Chez moi, cela met une erreur 500 pour le client français.
Je n'ai pu le contourner que comme je l'ai expliqué. De cette façon, sur ma version de 1.7, le client italien ne peut commander, le formulaire réclame le DNI comme je l'ai montré sur la copie d'écran. Je viens de tester encore une fois, le formulaire n'est pas enregistré tant que le client italien ne rentre pas son DNI.
La seule chose que je constate, c'est que dans le fichier modifié (CustomerAddressFormatter.php) ici, j'ai repris la même structure que pour le postcode et elle est différente dans le fichier de mon site.

Sur mon site : 
 ` if ($field === 'postcode') {
      if ($this->country->need_zip_code) {
          $formField->setRequired(true);
                    }
                }
    if ($field === 'dni') {
      if ($this->country->need_identification_number) {
           $formField->setRequired(true);
                   }
                }`

Essayez comme cela. Si cela fonctionne, je ferai la correction. En tout cas, chez moi ça marche.

**Comment by marionf** [comment]
L'erreur 500 n'est plus présente :) 
Cependant il reste deux problèmes fonctionnels à corriger qui sont les suivants : 

Cas 1
Si je ne coche pas DNI dans Clients > Adresses, mon client Italien qui a une adresse sans DNI peut valider sa commande.
Il devrait être contraint à modifier son adresse si le DNI n'est pas renseigné car le DNI est présent dans le format de l'adresse et le need_identification_number est à on.

Cas 2
Si je coche DNI dans Clients > Adresses, mon client Français qui a une adresse sans DNI ne peut pas valider sa commande car il est contraint de modifier son adresse.
Il ne devrait pas y être obligé car le champs DNI n'est pas présent dans le format de l'adresse et le need_identification_number est à off.

Il y a 3 conditions à prendre en compte :
- La présence du DNI dans le format de l'adresse du pays
- Le need_identification_number du pays
- La checkbox DNI dans Client > Adresses

Actuellement, nous en avons que 2:
if ($field === 'dni' && $this->country->need_identification_number)

**Comment by sirius82** [comment]
Qu'avez-vous mis dans CustomerAdressFormatter.php ? Avez-vous essayé comme je l'ai écrit hier soir le code que j'ai dans mon fichier ?
Car je ne rencontre absolument pas le même problème que vous. Mon client italien NE PEUT PAS valider le formulaire si le DNI n'est pas entré. Vous pouvez le voir sur http://www.diamoro.com.

**Comment by marionf** [comment]
Oui, le résultat est le même.

Je ne suis pas sure que l'on parle du même formulaire ?

Je ne parle pas du formulaire de création d'adresse (c'est ok le champ DNI est obligatoire et je ne peux pas enregistrer l'adresse s'il n'est pas rempli)

capture du 2018-04-25 10-54-13

Je parle du formulaire adresse durant la commande:

capture du 2018-04-25 10-57-18

**Comment by sirius82** [comment]
Je n'arrive absolument pas à reproduire la même chose que vous. Mes copies d'écran concernent bien le formulaire dans le tunnel de commande, je ne parle que de celui-là depuis le début. Je ne peux absolument pas le valider tant que je n'ai pas mis le DNI. Celui-ci apparaît bien dans l'adresse (ligne juste sous le nom). Question déjà posée à laquelle il ne me semble pas avoir eu de réponse : quelle version de PS ? Et aussi quel thème ?
adresse-valide-france

Toujours dans le formulaire de commande, j'ai édité Adresse pour en ajouter une en France et c'est ok
ajout-adresse-form-commande

A tout hasard, pouvez-vous me donner l'url du site ?

**Comment by sirius82** [comment]
[CustomerAddressFormatter.zip](https://github.com/PrestaShop/PrestaShop/files/1946522/CustomerAddressFormatter.zip)
Voici mon fichier php. Essayez-le pour voir. PS 1.7.2.2.
Avez-vous testé le formulaire sur l'url que je vous ai communiquée hier ?

**Comment by marionf** [comment]
Il y a eu des changements depuis PrestaShop 1.7.2.2 sur le checkout (dont ces PR: #8435 et #7975 ), voilà pourquoi vous n'avez pas le bug que j'ai relevé.
Pour répondre à votre question, je test la PR sur la branch develop donc PrestaShop 1.7.4.0 avec le thème Classic par défaut. Si vous testez ainsi, vous aurez le même problème que moi :)

**Comment by sirius82** [comment]
okay ! il me semble vous avoir demandé quelle version vous aviez dès le début, il ne me semble pas que vous y ayez répondu, on aurait gagné du temps ;-) J'ai bien spécifié dans le changement proposé que c'était pour 1.7.2. Il semblerait donc que cette nouvelle version n'utilise pas le même formulaire dans le processus de commande et dans le compte client ?

**Comment by ttoine** [comment]
Hello guys,

Next time you contribute, could you please discuss in english? I know it can be more difficult sometimes, but the aim is just to ensure that all contributors can read this PR.

**Comment by sirius82** [comment]
Hello ttoine, yes indeed. But it's not easy for me to be sure that I correctly understood what meaned Marion. Even in the same language isn't easy ! We needed several message to understand finally that we have not the same version.
To resume : for PS 1.7.2.2, it's just necessary to change CustomerAddressFormatter.php as I said.
The problem of Marion seems to be different. Her version is 1.7.4

**Comment by eternoendless** [comment]
Hi @sirius82 

First of all, thank you for your contribution!

While I understand that your fix may be working on your 1.7.2.2 shop, the `develop` branch on which your contribution is based on corresponds to the latest development codebase for the next major version (1.7.4). Unfortunately, we cannot accept contributions for older 1.7 branches.

In order for us to be able to accept your PR, please make sure it works correctly on the branch you're submitting your PR to.

Thanks!

**Comment by ttoine** [comment]
@sirius82 

BTW, I would be very interested to chat with you (in french this time) on an other channel to see how we could help contributor like you to do it right the first time. I mean, to be sure that it's easy to work with the develop branch, and then do you pull request.

If possible for you, when would you be available? we can use phone or skype.

**Comment by sirius82** [comment]
It's a good idea. I prefer by phone Is it possible to send you a MP to give you my number or you give me your.

**Comment by ttoine** [comment]
you can find me on twitter: @ttoine, just ping me.
or, in general, you can find me by looking for "ttoine" in google.

**Comment by sirius82** [comment]
Found. I just sent you a mail.

**Comment by marionf** [comment]
@sirius82 
Do you want to adapt your PR for the last version & solve the issue that I told you ?
If not, I will close your PR because the bug isn't solved in the last version

**Pull request closed without merging**
