### PR TITLE
Merge back branch 1.7.5.x (changes for 1.7.5.1)

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Merge back branch 1.7.5.x (changes for 1.7.5.1)
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | ~
| How to test?  | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12444)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by matks** [comment]
Lint is bad 😆

**Comment by jolelievre** [comment]
Oh crap the lint rules changed! 🤪

**Comment by jolelievre** [comment]
@PrestaShop/prestashop-core-developers it's alright tests are green!

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @jolelievre

**Pull request merged**
