### PR TITLE
Fix legacy submenu laptop

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix hole in left menu on laptop 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2366
| How to test?  | check left menu on laptop

### CODE REVIEW

**Review by maximebiloe — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @nihco2 
The comportment isn't that expected, the menu should be like on the new pages

**Comment by marionf** [comment]
Hello @nihco2 
On the old pages the menu is truncated
capture du 2017-07-10 15-00-33

**Comment by aleeks** [comment]
ping @nihco2

**Review by eternoendless — DISMISSED** [review]
Code looks good!

**Comment by marionf** [comment]
Hello @nihco2 
I removed the QA approved because I didn't know this PR solve also another ticket: http://forge.prestashop.com/browse/BOOM-3305
On the new pages the icones have a size of 20x20 and on the old pages they have a size of 20x33
Maybe we can solve this ?

**Comment by nihco2** [comment]
@marionf container size is different but it's the same font-size for ico

**Comment by marionf** [comment]
It's Ok, thanks @nihco2 to specify !

**Comment by nihco2** [comment]
@eternoendless I have rebase, could you please add check review again ? Thks !

**Review by eternoendless — APPROVED** [review]
Looks good to me!

**Review by maximebiloe — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @nihco2

**Pull request merged**
