### PR TITLE
// Cache optimizations

### PR DESCRIPTION
**Pull request by jocel1**

### CODE REVIEW

**Comment by guestisp** [comment]
Did you see speedup when enabling cache? I always had big slowdown enabling it.

**Comment by jocel1** [comment]
@guestisp : it depends if you have MySQL query cache enabled or not. If query cache is enabled, I recommend not using the prestashop cache, I'll just slowdown the performances. However if query cache is disabled, the cache could help, but only if your site is not too big to fill the whole APC / Memcached cache.

**Comment by guestisp** [comment]
@jocel1 thank you. I never tried with mysql cache disabled.

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.

Would you mind adding line feed on if statements to suit PS norms ? http://doc.prestashop.com/display/PS15/Coding+Standards#CodingStandards-Block

Many thanks. Regards

**Comment by jocel1** [comment]
@gRoussac Done !

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR.

Best regards

**Pull request merged**
