### PR TITLE
Reorganize Search Aliases with a new tab

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | * Reorganize Search Aliases with a new tab.<br>* Remove legacy search aliases grid in favor of new aliases tab.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 1. Install shop after checkout this PR.<br>2. Navigate to Configure > Search.<br>3. Tests new behaviours describe in the description.
| UI Tests          | MySQL 🐬 : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/12085743483<br>MariaDB 🦭 : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/12085754472
| Fixed issue or discussion?     | Fixed https://github.com/PrestaShop/PrestaShop/issues/37551
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/37212
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @boherm

**Comment by Progi1984** [comment]
MySQL :dolphin: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/12085743483
MariaDB :seal: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/12085754472

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Admin.Advparameters.Help`
    - [ ] `Enable / Disable the store page.`
    - [ ] `Enable / Disable the merchandise return page.`
- `Admin.Shopparameters.Feature`
    - [ ] `New aliases`

(Note: this is an automated message, but answering it will reach a real human)

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @boherm,

I tested your PR and I found a bug or a strange comportment:

https://www.loom.com/share/50a15474cc3641eab0c815fee9108d9f?sid=923a59db-d8b1-4222-86bb-c289e3a1001f

If you add 2 aliases with the same name, it is the first one that is entered that is taken into account in choosing its status. Is this an intended behavior? Would it be desirable to put an error message to prevent the backup if there are two aliases with the same name?

@PrestaShop/product-council What did you think about that?

Thanks for your feedback!

**Comment by Hlavtox** [comment]
@paulnoelcholot Well, the aliases work in a weird way currently, so I think that it has to be reworked anyway to make any sense...

Let me explain.

Currently, you add an alias `car => automobile`.  And the way it works is, that instead of searching for `car`, it searches for `automobile`. So, all products that don't contain only `car` are not found. So, it's pretty much useless. **And in this case, yeah, two aliases with the same search string don't make sense.**

But, IMHO, the way it should work (and how elastic search, typesense work) is that if you make alias `car => automobile`, it will search for both variants of the word. **And in that case, it would make perfect sense to have multiple aliases.**

So you create:
`car => automobile`
`car => vehicle`

And when searching for `car`, it also finds products that contain `automobile` and `vehicle`.

**Comment by paulnoelcholot** [comment]
@boherm I found a second bug.... :/

https://www.loom.com/share/8325174ec4624cd9ada5e13e7c7019d3?sid=47aa2a60-5788-4d4a-a1f0-972976675253

**Comment by paulnoelcholot** [comment]
Seen with @boherm and @PrestaShop/product-council , the two bugs are not blocking for the PR.

So it's good for me! :tada: 
Thanks!

Auto test : https://github.com/paulnoelcholot/testing_pr/actions/runs/12316821168

**Comment by paulnoelcholot** [comment]
Issues created : 
https://github.com/PrestaShop/PrestaShop/issues/37675
https://github.com/PrestaShop/PrestaShop/issues/37676

**Review by paulnoelcholot — APPROVED** [review]

**Comment by boherm** [comment]
Thanks guys!

**Comment by gericfo** [comment]
Hello @boherm , 
Please note that the “Needs autoupgrade PR” label has been automatically added to your Pull Request. This means that the changes made in your PR must also be reported in the Autoupgrade module, responsible for running the update process of PrestaShop stores. 
When there's a modification to the `db-structure.sql` file or if a Doctrine entity has been modified, added, or deleted, it impacts the database structure. Modifying the list of hooks and feature flags has consequences on the update process as well. These changes can affect how the application interacts with the database and how update procedures are handled. It's important to consider these aspects when contributing to ensure a smooth update experience for users. 
That's why this contribution should be backported, with another corresponding PR, on the Autoupgrade module's GitHub repository which is available here: [link](https://github.com/PrestaShop/autoupgrade) Contribution to the Autoupgrade module documentation: [link](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/upgrade-module/ ). 
Don't forget to add a comment in this current thread with the link to this PR once it has been created. 
If you are sure that your Pull Request doesn’t require additional actions, ping commiters and it will be checked. 
Thank you.

**Pull request merged**
