### PR TITLE
Move entity repositories in existing subfolder

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
This PR should be merged for the version 1.7.1.0

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In our entity folder, we have the entities (as expected) and their repositories. However, why are they in the same place if a `Repository` subfolder exists ?
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Possibly yes
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
@thierrymarianne will be happy!!!

**Comment by maximebiloe** [comment]
Could you rebase, por favor? 🐣

**Comment by Quetzacoalt91** [comment]
Done

**Comment by maximebiloe** [comment]
¡Muchas gracias!

**Pull request merged**
