### PR TITLE
Add new variable in product.php, to sort features in front

### PR DESCRIPTION
**Pull request by Tanguy-SALMON**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This commit allows to be able to sort features in front. By a range system, it's possible to add, e.g. title for sorted features. It's useful for product with a lot of features, like computers for example. 
| Type?         | improvement
| Category?     | CO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | No
| How to test?  | Just add a small snippet in templates\catalog\_partials\product-details.tpl . An example of the snippet is in the archive attachment.

[product-details.zip](https://github.com/PrestaShop/PrestaShop/files/2212731/product-details.zip)
!
demo2

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9356)

### CODE REVIEW

**Comment by rdy4ever** [comment]
Hi there. This is nice, but seems complicated. 
I did something like this with no core modification, by playing a bit with custom features, a bit of js and css. I think it would be easier and reusable to create the group titles as features, with the value "@title" (or something else that you will never use as a regular value). Then, for each product add the title feature above its children. Then, use js to add a class to each feature that has the value "@title" and CSS to style it (hide the "@title" value and style the label). If you'd like to add icons for each title, then you can add the feature id as a class in the tpl.file for each feature (lke "feature-23") and use the :before pseudo in css to add an icon for each case.

**Comment by kpodemski** [comment]
LGTM

**Comment by Tanguy-SALMON** [comment]
Hi, 
@rdy4ever Create group titles as features could be confused for the shopper when add features for new product (which features are title, which ones are regular features).
For the CSS and JS, for my solution, no need to add CSS, cause, title CSS is same that one used in description tab. And no need to add JS.

I would also add that this commit allow the possibility to make a module to make this functionality more user friendly.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @Lathanao

**Pull request merged**
