### PR TITLE
Superfluous table alias

### PR DESCRIPTION
**Pull request by jocarat**

### CODE REVIEW

**Comment by jocarat** [comment]
it should be good now

**Comment by xBorderie** [comment]
Thank you Jérôme!
Sadly, you now have 4 commits instead of just one:
* the initial commit, still here
* two well-formatted commits (one taken from your #5099, which you closed)
* a merge commit.

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).
Thank you!

**Comment by xBorderie** [comment]
Hey @jocarat ! Any chance you could clean up the commits, as explained above? Thank you!

**Comment by jocarat** [comment]
Hi, sorry but I tried and totally messed up my repository, i'm not familiar with these kind of git manipulations...

that's just a few chrs to remove from both files, maybe somebody else can apply these patchs ?

regards

**Comment by xBorderie** [comment]
Then the easiest way for you would be to create a new PR which follows the correct conventions, and once it is created, close this one :)

**Comment by antoin-m** [comment]
Thank you for your contribution @jocarat ! :)

Since you had some issues with your git repository I cherry-picked your PR here : https://github.com/PrestaShop/PrestaShop/pull/7460

**Pull request closed without merging**
