### PR TITLE
Fixed birthday input from 'text' to 'date'

### PR DESCRIPTION
**Pull request by Sloth-Wizard**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | CO changed the input type from text to date as it isn't user friendly on a birthday field
| Type?         |  improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8991)

### CODE REVIEW

**Comment by Sloth-Wizard** [comment]
Hey !
Not sure why the Travis build isn't passing

```
1) should allow filling the personal info form without password:
element (#checkout-personal-information-step.-reachable.-complete) still not visible after 2500ms
```
I don't get why it requires this (makes no sense to me)

If anyone cares to explain what's happening here I would be very thankfull :)

**Comment by mickaelandrieu** [comment]
ping @fatmaBouchekoua can you help this contributor to update the selector involved in this change? This is probably why the e2e don't pass anymore :)

Thanks!

**Comment by fatmaBouchekoua** [comment]
Hello @Sloth-Wizard 
Thank you for your contribution. 
The tests are failing because you've made the birthday required and the tests don't fill the birthday input.
@mickaelandrieu is it necessary to make the birthday as required?

**Comment by mickaelandrieu** [comment]
@fatmaBouchekoua IMO yes because if we ask for birthdate, we assume we will retrieve a birthdate isn't it?

Maybe can we complete the testing scenario here, if you can give us some hints on what we need to do?

Thank you

**Comment by arafatx** [comment]
Why don't we use the old date picker like we had in prestashop 1.6.
OK, I notice that we have the type=birthday, when changing to birthday it will show what we previously had in prestashop 1.6 but it doesn't work when saving. I think it's deprecated type.

**Pull request closed without merging**
