### PR TITLE
Fix unclosed div in product-list.tpl

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | n/a
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #n/a
| How to test?      | dev qa test
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24680)

### CODE REVIEW

**Review by PululuK — APPROVED** [review]

**Review by matks — APPROVED** [review]
Nice catch!

Fortunately the mistake was introduced in 1.7.8
so this PR will avoid it reaching production https://github.com/PrestaShop/PrestaShop/pull/22908

**Review by NeOMakinG — APPROVED** [review]
Damnnnnnnnn, me => 🚪

**Comment by matks** [comment]
> Damnnnnnnnn, me => 🚪

Would it be possible to detect unclosed div tags on submitted PRs? In CI?

**Comment by NeOMakinG** [comment]
> > Damnnnnnnnn, me => 🚪
> 
> Would it be possible to detect unclosed div tags on submitted PRs? In CI?

Maybe, idk, worth checking if something like this exist for any files

**Comment by PierreRambaud** [comment]
> > > Damnnnnnnnn, me => door
> > 
> > 
> > Would it be possible to detect unclosed div tags on submitted PRs? In CI?
> 
> Maybe, idk, worth checking if something like this exist for any files

I know this is something we can test while building a Vue app, but since we have custom smarty/twig templates, I'm afraid it's not possible in state :(

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @kpodemski !

**Comment by Progi1984** [comment]
Thanks @kpodemski & @florine2623

**Pull request merged**
