### PR TITLE
Update legacy-to-standard-locales.json

### PR DESCRIPTION
**Pull request by OneDotIT**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | A new language can not be added unless the corresponding 2-Character ISO code exist inside the file legacy-to-standard-locales.json. This pull request add's a new ISO code for Malagasy.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #14074
| How to test?  | Through the localization option, create a new language with costume ISO code.

Add Malagasy ISO "mg": "mg-MG".

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14185)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by OneDotIT** [comment]
Hello,
Pardon me, I was caught in something.
Appreciate approving both of the pull's request, I will simplify it when I come back.

Regards,

---- On Fri, 12 Jul 2019 17:41:43 +0300 GoT <mailto:notifications@github.com> wrote ----


@PierreRambaud approved this pull request.

**Comment by sarahdib** [comment]
Hello @OneDotIT 

Thank you for your contribution.

I add the Malagasy iso code in language tab. Then in localization -> translation,I try to translate back office translation in Malagasy language but I found an error :

image

**Comment by OneDotIT** [comment]
Hello,
Yes this is the error pop-up I mentioned @ https://github.com/PrestaShop/PrestaShop/issues/14074#issuecomment-500508124
My initial suspicion was that the files has to come from crowdin translation project (Prestashop website is the intermediate).


I will debug, apply this patch and #14349 then test again, see what I get. But please expect me no before than 25July.

---- On Tue, 16 Jul 2019 16:03:22 +0300 Sarah Dib <mailto:notifications@github.com> wrote ----


Hello https://github.com/OneDotIT

Thank you for your contribution.

I add the Malagasy iso code in language tab. Then in localization -> translation,I try to translate back office translation in Malagasy language but I found an error :

https://user-images.githubusercontent.com/3034677/61296638-cd43ea00-a7da-11e9-9630-f21b3ee2367f.png

**Comment by sarahdib** [comment]
Hello @OneDotIT 

Like @PierreRambaud  said https://github.com/PrestaShop/PrestaShop/pull/14349#issuecomment-507648430
You need to combine the two PR.

We will wait

**Comment by PierreRambaud** [comment]
Closed in favor of #15063

**Pull request closed without merging**
