### PR TITLE
[*] Project : Separate products in cart, order and invoice by customization

### PR DESCRIPTION
**Pull request by unlocomqx**
## Description

Separate products by customizations as well as combinations so that each customization can have its own line and thus quantity and price
This allows modules to assign a cost to each customization easily using an override on getPriceStatic
## Steps to test this Improvement
1. Apply this SQL code to the database to add two fields to `cart_product` & `order_detail`
   https://gist.github.com/unlocomqx/9dc585eab82432853a87e8e2b4974f0e
2. Create a text customization field on a test product
3. Save a customization in the product page and add to cart
4. Save a second customization and add to cart

The customizations will be each on a separate line (screenshots in the Forge link below)

I've seen a number of modules trying to find a workaround but this is the best solution to add extra data to a product line and give it a cost
## Forge Ticket (optional)

Forge: http://forge.prestashop.com/browse/BOOM-535
Forum: https://www.prestashop.com/forums/topic/516960-cart-customizations-in-prestashop-17/

### CODE REVIEW

**Comment by xBorderie** [comment]
Hi! Thank you for this contribution! You keep closing and reopening it, is it a work in progress?

Seems to me that your last commit (a138ba13316d60ebb64bc5051f8ac1a1b29039b0) has way too many files for what it should do. Could you double-check that you're not touching files that are unrelated? Thanks!

**Comment by unlocomqx** [comment]
Hello,

Sorry, I'm restarting the pull request as I made a wrong commit with all
changed files!

I will post another pull request, can you delete the current one?

Thank you very much

**Comment by xBorderie** [comment]
Alright, cool.
Can't delete PR: let's keep it closed :)
Cheers!

**Comment by unlocomqx** [comment]
Okay, Thanks a lot

Cheers

**Pull request closed without merging**
