### PR TITLE
Add QS to some of the back office assets to force cache clearance

### LINKED ISSUE #30925: Back office css / js cache busting
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Most of the time after doing 1-click update and something changed in back office system CSS / JS files, they do not get re-loaded by browser, no matter how many times u try CTRL+F5. So after every update in any eshop, I end up with logging JS errors and TinyMCE not showing anywhere. There is missing cache busting version info within CSS / JS file links.

Happens through pretty much any version of 1.7, but depends on actual changes in CSS / JS files. If there is no change, u won´t get js errors nor bad styling.

Usually, I have to open browser dev tools, set them to use no cache at all, reload page to get browser to load updated files. Then turn it off and it start working normally. No problem with me, but it´s hard to describe to shop owners for who I´m building e-shops...

### Expected behavior

Something like:

<script type="text/javascript" src="[/admin17sue/themes/default/public/bundle.js](view-source:https://www.suestyle.cz/admin17sue/themes/default/public/bundle.js?v=1788)"></script>

### Steps to reproduce

1. Run 1-click update with browser set as normal, awerage user.

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Added query string with a PS version to reload assets cache (some of the general assets loaded in BO)
| Type?             |  improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See that rtl.js, theme.css, main.bundle.js and some other have now query string with PS version
| Fixed ticket?     | Fixes #30925
| Related PRs       | n/a
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by Progi1984** [comment]
Isn't a security hole to reveal the version of PrestaShop ? Ping security guy @atomiix .

**Comment by kpodemski** [comment]
@Progi1984 it is in BO

**Comment by Progi1984** [comment]
Isn't it displayed in login page ?

**Comment by Hlavtox** [comment]
@Progi1984 it already is :-)

9333A24E-8F14-4294-9571-E7BB7C0DF451

**Comment by Progi1984** [comment]
Oh ! Chut ! 👍

**Comment by atomiix** [comment]
What do you think about using https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Version.php instead of the constant?

**Review by 0x346e3730 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @kpodemski  

There are problems with the CI, can you check this so we can test it.

Thanks!

**Review by djoelleuch — COMMENTED** [review]
Hello @kpodemski , 

Automated tests => OK (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4373426524) 
For a better test, it should be tested by a dev .

Thank you

**Comment by Hlavtox** [comment]
Hi everyone, I tested the PR and everything works correctly.

Prestashop version parameter was appended to every asset where it was implemented. On old and new pages. No issues or load errors in console. ✅ 
Snímek obrazovky 2023-03-09 155543

**Pull request merged**
