### PR TITLE
Merge 1.7.8.x into 8.0.x

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Merge 1.7.8.x to 8.0.x 20220825
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @FabienPapet

**Review by zuk3975 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by yanmakouf — APPROVED** [review]
Ci broken sur des merge commits

**Comment by matks** [comment]
Close and re-open to reset the CI

**Comment by matks** [comment]
@PrestaShop/qa-team Automated tests should be enough?

**Comment by Robin-Fischer-PS** [comment]
Hi @FabienPapet @matks !
Yes, automated tests are enough on this one (normal merge PR, not like the previous one with 30.000 lines modified :P )

**Comment by jolelievre** [comment]
OK thanks @Robin-Fischer-PS 

Automated tests are good (left red ones are known by the nightly already), merging this one ^^

https://github.com/jolelievre/testing_pr/actions/runs/2955752043

**Pull request merged**
