### PR TITLE
CO: Remove confusion about cart rule code check

### PR DESCRIPTION
**Pull request by AAymeric**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove confusion about cart rule code check
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for your contribution!

Sadly, you now have malformed commits instead of just one commit:
* the initial commit, which does not follow the [PS naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message),
* One revert commit,
* One commit which does not follow the naming convention (additional space),
* one commit which does follow the naming convention,
* one merge commit -- which if merged can break the repository's history!

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by AAymeric** [comment]
Hi xBorderie,

I can also cancel this pull request and start all over a commit correctly foramted?

**Comment by xBorderie** [comment]
Yes indeed! It's the easiest way sometimes :)

**Comment by AAymeric** [comment]
Ok let's go !

**Pull request closed without merging**
