### PR TITLE
[-] BO : use relative proto in AdminThemesController

### PR DESCRIPTION
**Pull request by ghost**
remove hardcoded "http:" for external links

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR! Please use `Tools::usingSecureMode()` instead :)

**Comment by ZiZuu-store** [comment]
You mean `getCurrentUrlProtocolPrefix()` ..

**Comment by ZiZuu-store** [comment]
@Shudrum @xBorderie see #5609

**Comment by Shudrum** [comment]
Perfect!

**Pull request closed without merging**
