### PR TITLE
RTL

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Makes RTL available
| Type?         | new feature
| Category?     | CO
| BC breaks?    | 
| Deprecations? | 
| Fixed ticket? | 
| How to test?  | Already tested

Many thanks to @Danoosh, @maximebiloe, Molka Djemal and @ramtin2025

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8437)

### CODE REVIEW

**Comment by maximebiloe** [comment]
giphy 2

**Comment by LittleBigDev** [comment]
Reviewed 36 of 36 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[admin-dev/themes/new-theme/scss/components/_tinymce.sass, line 1203 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDwExLJZ93dMsfQike:-KxDwExLJZ93dMsfQikf:b-cpkkyd) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/admin-dev/themes/new-theme/scss/components/_tinymce.sass#L1203)):*
> ```Sass
> .mce-rtl
>     i.mce-i-checkbox
>         direction: rtl
> ```

Missing single blank line at the end of file

---

*[classes/Language.php, line 188 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDwUZM_LwxsmXE7HBF:-KxDwUZNKIias_PYoM9K:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L188)):*
> ```PHP
>             return false;
>         }
>         
> ```

trailing spaces to be deleted

---

*[classes/Language.php, line 202 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDwXZOXlZNA5I5aYof:-KxDwXZOXlZNA5I5aYog:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L202)):*
> ```PHP
>         return true;
>     }
>     
> ```

trailing spaces to be deleted

---

*[classes/Language.php, line 208 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDwYDh4ZCjuSMgUpWH:-KxDwYDh4ZCjuSMgUpWI:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L208)):*
> ```PHP
>             return false;
>         }
>         
> ```

trailing spaces to be deleted

---

*[classes/Language.php, line 1338 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDwZI09UrLAeT4yCrs:-KxDwZI09UrLAeT4yCrt:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L1338)):*
> ```PHP
>         }
>     }
>     
> ```

trailing spaces to be deleted

---

*[classes/Language.php, line 1348 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDxuHt5IS9kMHI1mTA:-KxDxuHt5IS9kMHI1mTB:bd1hzjj) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L1348)):*
> ```PHP
>      * @param null $path
>      */
>     public static function installRtlStylesheets($bo_theme = false, $fo_theme = false, $theme_name = null, $iso = null, $install = false, $path = null)
> ```

This method has too many parameters, tests and does too many things.
Refacto is needed (extract methods) for the sake of maintainability.

---

*[classes/Language.php, line 1358 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDw_93MwFWfebGhLgt:-KxDw_93MwFWfebGhLgu:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L1358)):*
> ```PHP
>             }
>         }
>         
> ```

trailing spaces to be deleted

---

*[classes/Language.php, line 1362 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDw_jrVOCSqIqdYSdF:-KxDw_jrVOCSqIqdYSdG:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L1362)):*
> ```PHP
>             \RTLGenerator::generate($admin_dir.'themes');
>         }
>         
> ```

trailing spaces to be deleted

---

*[classes/Language.php, line 1366 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDwaCl3FpdG9DFbs2Q:-KxDwaCl3FpdG9DFbs2R:b5h431) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/Language.php#L1366)):*
> ```PHP
>             \RTLGenerator::generate($front_dir.($theme_name?$theme_name:'classic'));
>         }
>         
> ```

trailing spaces to be deleted

---

*[classes/assets/StylesheetManager.php, line 69 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxDyoHxoQRyr9nCup2l:-KxDyoHxoQRyr9nCup2m:ba314bf) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/classes/assets/StylesheetManager.php#L69)):*
> ```PHP
>         } else if ($fullPath) {
>             $this->add($id, $fullPath, $media, $priority, $inline, $server);
>         }
> ```

1. `$this->add()` can be extracted from the if/elseif/else.
If possible, `else` should be avoided.

2. This method does too many things.
Tests should at least be delegated and maybe performed outside and *before* calling `register()`. Then, `register()` should have only `$id, $path, $priority, $inline` parameters.

---

*[controllers/admin/AdminThemesController.php, line 334 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxE-z3DCV0cWHBI4Q8w:-KxE-z3DCV0cWHBI4Q8x:blghdv5) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/controllers/admin/AdminThemesController.php#L334)):*
> ```PHP
>                 array(),
>                 'Admin.Design.Notification'
>             );
> ```

Not a real change request. But I'd like to draw attention on this `postProcess()` method that definitely needs a refacto.

---

*[controllers/admin/AdminThemesController.php, line 543 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxE0NhVAbEEDnIPeIT1:-KxE0NhVAbEEDnIPeIT2:bpvea4l) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/controllers/admin/AdminThemesController.php#L543)):*
> ```PHP
>             ),
>         );
> 		
> ```

Tabulations

---

*[install-dev/controllers/http/process.php, line 117 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxE0pLj1dDYAU6ivmAF:-KxE0pLkoDSvA35Kfy6l:b-qemldc) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/install-dev/controllers/http/process.php#L117)):*
> ```PHP
>                 Tools::redirect('index.php');
>             }
>         }
> ```

Same comment as for `postProcess()`. This method needs a refacto.

---

*[themes/classic/assets/css/theme.rtlfix, line 12 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8437#-KxE1NEvwsKlGHq3e-VM:-KxE1NEvwsKlGHq3e-VN:bcw3w83) ([raw file](https://github.com/prestashop/prestashop/blob/bf3face391f611b0402aa4c55fd0a8043706b0f7/themes/classic/assets/css/theme.rtlfix#L12)):*
> ```
> 	content: "?";
> 	opacity: 0;
> }
> ```

- Care about tabulations
- Missing single blank line at the end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8437)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Nice and huge work !
Though, some changes are requested IMHO.

**Comment by kompilorb** [comment]
New Pull Request : https://github.com/PrestaShop/PrestaShop/pull/8467

**Pull request merged**
