### PR TITLE
Harmonize migrated controllers

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Updates controllers that were migrated for 1.7.5 version with new naming conventions.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | Controllers listed below should work as they did before, no functionality as changed.

Updated controllers:

- EmailController (E-mail page)
- BackupController (Backups page)
- MetaController (Traffic & SEO page)
- LocalizationController (Localization page)
- GeolocationController (Geolocation page)
- LogsController (Logs page)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11030)

### CODE REVIEW

**Comment by sarjon** [comment]
@matks here's PR which is kinda related to https://github.com/PrestaShop/PrestaShop/issues/11021

**Review by matks — APPROVED** [review]
Perfect 😃 you even added some improvements that make the code simpler

**Comment by matks** [comment]
@eternoendless @PierreRambaud I'd like to merge this `1.7.5.x`. This is not a bugfix however if we do not merge this for `1.7.5.x` then this will require a lot of deprecations / aliases / workarounds to avoid introducing BC breaks.

**Comment by marionf** [comment]
@sarjon 

When I try to delete in bulk on the emails page, I have this exception:

capture d ecran_446

I have configured  Geolocation to see catalog only from Afghanistan and can see the shop from France, and also in private navigation

capture d ecran_448

capture d ecran_449

With same settings in 1.74.3 it's working:

capture d ecran_450

**Comment by sarjon** [comment]
hi @marionf 

1. regarding exception, it is totally not related to this PR
2. Geolocation rules should work if you try to access actual shop (on remote server). In addition, behavior has changed a little between 1.7.4 and 1.7.5 due to this PR https://github.com/PrestaShop/PrestaShop/pull/9441,  thats why you can access shop from your localhost.

**Comment by marionf** [comment]
You are right @sarjon, I have these issues also on 1.7.5.x branch
I will create a new issue

**Comment by sarjon** [comment]
> I will create a new issue

@marionf i dont think that Geolocation has an issue, it just ignores Geolocation rules for **localhost**, it should work well on remote server. :)

**Comment by matks** [comment]
@PierreRambaud approved so let's merge !

**Pull request merged**
