### PR TITLE
 Fix fatal when no product to set in CategorySearchProvider

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  Fix fatal when no product to set in CategorySearchProvider. The `CategorySearchProvider->getProductsOrCount()` function may return a boolean and we're waiting for an array in `ProductSearchResult->setProducts()`
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2382
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
Here: 
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Supplier/SupplierProductSearchProvider.php#L76
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Search/SearchProductSearchProvider.php#L121
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/PricesDrop/PricesDropProductSearchProvider.php#L76
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/NewProducts/NewProductsProductSearchProvider.php#L75
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Category/CategoryProductSearchProvider.php#L89
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Manufacturer/ManufacturerProductSearchProvider.php#L76
- https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/BestSales/BestSalesProductSearchProvider.php#L67

:relaxed::relaxed::relaxed::relaxed::relaxed::relaxed:

**Comment by prestamodule** [comment]
This is a good catch, and useful !

**Comment by maximebiloe** [comment]
@aleeks it was already done on some providers. So, I used the same check.
Thanks!

**Review by aleeks — APPROVED** [review]
Ok for me

**Comment by aleeks** [comment]
Thank you @maximebiloe

**Pull request merged**
