### PR TITLE
Migrate translations page to TypeScript

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | We're migrating to TS, Vue files needs too!
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Translation page should work as expected
| Possible impacts? | Translation page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25236)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

After installing this PR, I have an exception in the BO > International > Translations page
image
It is blocked by this issue: https://github.com/PrestaShop/PrestaShop/issues/26756
This PR should be tested after merging this PR: https://github.com/PrestaShop/PrestaShop/pull/26789

Thank you!

**Comment by Progi1984** [comment]
@khouloudbelguith #26789 has been closed in favor of #26934 (which is merged).

@NeOMakinG Could you rebase your PR, please ?

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 

- I checked all functions for each section
- I checked the translation page when multistore enabled
- I checked with a mobile

https://watch.screencastify.com/v/8HNPSqE6ai3L2vb1Qgv2

Automatic tests are ok
[Mochawesome Report_trans.pdf](https://github.com/PrestaShop/PrestaShop/files/7727042/Mochawesome.Report_trans.pdf)


Thanks!

**Comment by NeOMakinG** [comment]
Thanks @khouloudbelguith

**Pull request merged**
