### PR TITLE
Improve security by randomizing prefix

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Small improvement to security by generatin a random prefix for the database. This will avoid every shop using ps_.
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install the shop, the database step will show a prefilled box with random letters every time.
| UI Tests          | ~~does not work at the moment.~~ https://github.com/florine2623/testing_pr/actions/runs/11323168446
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | Prestaworks AB

### CODE REVIEW

**Review by boherm — COMMENTED** [review]
Thanks for your contribution @Prestaworks! 
This could be a cool feature to add, but maybe just 2 chars [a-z] isn't enough.
With [a-zA-Z0-9] instead of [a-z] only and with 4 or 5?
(https://dev.mysql.com/doc/refman/8.4/en/identifiers.html)

**Comment by Hlavtox** [comment]
Ping @PrestaShop/tech-council
Ping @ShaiMagal @kpodemski

**Comment by Prestaworks** [comment]
> Thanks for your contribution @Prestaworks! This could be a cool feature to add, but maybe just 2 chars [a-z] isn't enough. With [a-zA-Z0-9] instead of [a-z] only and with 4 or 5? (https://dev.mysql.com/doc/refman/8.4/en/identifiers.html)

I can change to that if that is what is wanted.

**Comment by kpodemski** [comment]
Let's do that @Prestaworks :)

**Comment by Prestaworks** [comment]
> Let's do that @Prestaworks :)

I made the change now.

**Review by jolelievre — APPROVED** [review]
Thanks @Prestaworks

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]
Thanks @Prestaworks!

**Review by florine2623 — COMMENTED** [review]
Hello @Prestaworks ,

When I try to install a PrestaShop, the prefix of the database is always "ps_". I have tried multiple installations.

Screenshot 2024-10-14 at 11 40 11

Am I missing something ?
Waiting for your feedback !

**Comment by Prestaworks** [comment]
> Hello @Prestaworks ,
> 
> When I try to install a PrestaShop, the prefix of the database is always "ps_". I have tried multiple installations.
> Screenshot 2024-10-14 at 11 40 11
> 
> Am I missing something ? Waiting for your feedback !

Works fine for me :)

Are you using some kind of automatic installer?
bild

**Review by florine2623 — APPROVED** [review]
Hello @Prestaworks ,

Auto tests are green !

I tried again after reinstalling my shop, it works as expected.
Screenshot 2024-10-15 at 10 07 57
Screenshot 2024-10-15 at 10 08 05

Thanks for the PR!
It is QA ✅

**Comment by kpodemski** [comment]
thank you @Prestaworks @florine2623

**Comment by Hlavtox** [comment]
@kpodemski @Prestaworks @PrestaShop/tech-council I think that it should not generate uppercase letters. It may provide some side effects because some systems may be case sensitive and some not.

**Comment by Prestaworks** [comment]
> @kpodemski @Prestaworks @PrestaShop/tech-council I think that it should not generate uppercase letters. It may provide some side effects because some systems may be case sensitive and some not.

If you want to change to only lower case, I can change that. Can we repoen the PR in that case or do I need to create a new one?

**Comment by Hlavtox** [comment]
@Prestaworks Just my opinion, but I think it would be better, for sake of consistency and readability. :-)

**Comment by Prestaworks** [comment]
> @Prestaworks Just my opinion, but I think it would be better, for sake of consistency and readability. :-)

I agree, I made a new PR to remove the capital letters
https://github.com/PrestaShop/PrestaShop/pull/37167

**Pull request merged**
