### PR TITLE
Removed order of languages in TranslatableType field for migrated pages

### LINKED ISSUE #20341: [1.7.6.7] Different order of languages
Hello,
I have just added a few new languages to my Prestashop and I noticed that order of languages displayed is different is a few places. In some places languages are displayed according to their ID, but in some places the order is totally random. Here's an example:

This is the order of the languages in New feature section. This is the ocrrect order according to the ID of the language presented on the International -> Localization -> Languages. 

feature

And this is the order of languages when I am adding a new category - it's ordered randomly.

category

I prefer the display according to the ID everywhere because it is easier to add new things or modify something because I know the position of all languages on the list with jsut a quick look. With random order I have stop for a moment to find the langauge I want to work with. Can you help?

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Removed order of languages in TranslatableType field for migrated pages
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20341
| How to test?  | * Install the Shop in English<br>* Add French from the BO<br>* Add Spanish from the BO<br>* Set default language for employee in French<br>**BEFORE** <br>* The order in Migrated pages must be by ID and the default language for employee in priority (French, English, Spanish)<br>* The order in non Migrated pages must be by ID (English, French, Spanish)<br>**AFTER** <br>* The order in Migrated pages must be by ID (English, French, Spanish)<br>* The order in non Migrated pages must be by ID (English, French, Spanish)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21346)

### CODE REVIEW

**Comment by Progi1984** [comment]
@PrestaShop/qa-automation No changes on your automated tests ?

**Comment by boubkerbribri** [comment]
> @PrestaShop/qa-automation No changes on your automated tests ?

I don't think so, we always set the English part (+ french sometimes)

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @Progi1984 !!

**Comment by Progi1984** [comment]
Thanks @SD1982

**Pull request merged**
