### PR TITLE
Display 3 products on the same line on home with 2 columns layout

### LINKED ISSUE #16352: Two columns small left column with Recommended Product are not displaying corectly.
Hello, I have a little problem with displaying products on main page.
I wanted to have menu with all categories and products on main page, so I have changed grid for index to "Two columns small left column - Two columns with a small left column".
But now in the main page only two products in one row are displayed (instead of 3) 
How to change this to look the same as in category view where 3 products are displayed in a row.

this issue is in the popular products section, when I click "display all products" it display 3 products in a row.

**To Reproduce**

**Screenshots**
If applicable, add screenshots or screenrecords to help explain your problem.

**Additional information**
PrestaShop 1.7.6.1
PHP version: 7.3

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If you selected the 2 columns layout on home, you would see 2 product on every single lines
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16352 
| How to test?  | Set layout of your homepage to two columns small left and see if there are 3 products on the same line

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16504)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by eternoendless** [comment]
@NeOMakinG You forgot to fill out the "description" part of the PR table 😉

**Comment by sarahdib** [comment]
@NeOMakinG 
Can you rebase your PR :) ?

Thank you

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

After applying your fix, the way of displaying the product (position) inside a category is changed when we have one or two products.
1. One product (Men category)
1.1 Before applying PR:
image
1.2. After applying PR:
image
2. Two products (Clothes category)
2.1 Before applying PR:
image
2.2. After applying PR:
image

PS: the index page is OK
image

Thanks!

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is OK.
https://drive.google.com/file/d/1vQhD6G-6LLXnlDZqvn07HAU4tqcx9e1p/view

Thanks!

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

**Pull request merged**
