### PR TITLE
Adding hook enabling us to skip email sending

### PR DESCRIPTION
**Pull request by xitromedia**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | For some cases this may be wanted, e.g. for order confirmation that cannot be disabled elsewhere.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Forge ticket  | 
| How to test?  |

### CODE REVIEW

**Comment by firstred** [comment]
This looks like a nice PR. Would you mind rebasing it and rename the hook to `'actionEmailSendBefore'` so that it is harmonized with the other hooks names. Thank you!

**Comment by julienbourdeau** [comment]
Good hook!
Michael is right about the name. Also, I would send all the method parameters as inputs to the hook.

**Comment by kpodemski** [comment]
@julienbourdeau it's good to see someone responding to old PR,s but i think it would be much better to cherry pick best of them instead of asking for changes after years :)

**Comment by antoin-m** [comment]
Hi @xitromedia, thank you for your contribution.

I cherry-picked your PR here https://github.com/PrestaShop/PrestaShop/pull/7443

**Pull request closed without merging**
