### PR TITLE
Create, edit, delete and delete with bulk actions address

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | create, edit, delete and delete with bulk actions address
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | path=full/09_customer/addresses/* npm run specific-test -- --URL=BackOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8827)

### CODE REVIEW

**Review by fatmaBouchekoua — DISMISSED** [review]

**Review by fatmaBouchekoua — DISMISSED** [review]

**Review by Quetzacoalt91 — DISMISSED** [review]
missing `;`

**Comment by fouratachour** [comment]
Hello @Quetzacoalt91
I have added the missing semicolon.
Thanks for your review.

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by fouratachour** [comment]
Hello @marionf 
This PR has been rebased
Best regard,

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
@fouratachour Can you rebase please?
@fatmaBouchekoua Can you revalidate after the rebase please?

**Comment by fouratachour** [comment]
Hello @PierreRambaud 
This PR has been rebased
Best regard,

**Review by fatmaBouchekoua — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @fouratachour and @fatmaBouchekoua

**Pull request merged**
