### PR TITLE
change buildGroupedFeatures of product lazy array to public

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0
| Description?      | allow buildGroupedFeatures to be called everywhere
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | NA
| Sponsor company   | Creabilis.com

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop`, `9.0.x` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Hlavtox** [comment]
Anything that blocks you from calling getGroupedFeatures? 🤔

**Comment by jf-viguier** [comment]
nice catch @Hlavtox 
etGroupedFeatures populate the grouped features, it should be named setGroupedFeatures, wdyt ?

**Comment by Hlavtox** [comment]
@jf-viguier Cool! :-) Well, it's just an internal method that constructs them, sooooo I think the name is good like this IMHO.

**Pull request closed without merging**
