### PR TITLE
CO: Fixed foreach warning on empty hook return in CustomerFormatter

### PR DESCRIPTION
**Pull request by MDWeb-Lille**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | missing is_array check, triggered warning on empty $additionnalFormFields, like d681768 and 4cfc02f
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Warning happened on create account page FO with module multiblocks

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hello @MDWeb-Lille,

I'm so sorry, I did not see your pull-request and I have merged a similar one yesterday (#8339)!
This fix will be available for the next minor version of PrestaShop 1.7.3.0.

Best regards

**Comment by MDWeb-Lille** [comment]
:(

**Comment by Quetzacoalt91** [comment]
I know, I should have merged yours because it was created before. Sorry about that. :/

**Comment by MDWeb-Lille** [comment]
That's ok, it's a minor fix, it was more about the thrill of the bug hunt :) Hope it won't happen again, thanks for letting us know

**Pull request closed without merging**
