### PR TITLE
Order feature by position then id_feature_value in productForm V2

### LINKED ISSUE #25053: Order feature by position then id_feature_value in productForm V2
#### Describe the bug

In Prestashop we can order feature for displaying. But when we set those features on the product form, we don't get this order.

#### Expected behavior

Display and edit feature in the order define for the feature. When a feature is set several times, order in the same order they were created (ie. in the id_feature_value order).

#### Steps to Reproduce

1. Go to a product with features form
2. Take a screenshot
3. Go to the feature form
4. Change the order of your features
5. Go back to your product form
6. Check if feature order has changed

#### Additional information

* PrestaShop version: 1.7.8.0-beta.1
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by e-gaulue**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In Prestashop we can order feature for displaying. But when we set those features on the product form V2, we don't get this order. We should be able to display and edit feature in the order define for the feature. When a feature is set several times, use the same order they were created (ie. in the id_feature_value order).
| Type?             |  improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25053.
| How to test?      | See #25053.
| Possible impacts? | None.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25054)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
just a comment to remind other maintainers that this PR should not be sent to QA before the issue has been reproduced and validated

**Review by matthieu-rolland — APPROVED** [review]
code wise LGTM

**Review by PierreRambaud — APPROVED** [review]

**Comment by marionf** [comment]
@MatShir It's about product page V2, could you have a look ?

**Comment by MatShir** [comment]
Nice catch ! Thanks for the contribution

**Review by jolelievre — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hello @e-gaulue ,

I checked your PR, the features are now ordered in the same order as in the Features configuration, so it's QA :heavy_check_mark: !

Thanks :)

pr 25054 Product V2 OK

**Comment by Progi1984** [comment]
Thanks @e-gaulue & @Robin-Fischer-PS

**Comment by matks** [comment]
Good contribution @e-gaulue 😉 thank you

**Pull request merged**
