### PR TITLE
Harden OrderShippingAddressForViewing and OrderInvoiceAddressForViewing against old/messy data ; Fix issue #23336 

### LINKED ISSUE #23336: TypeError in constructor of class OrderShippingAddressForViewing on null data in table ps_address
####  Observed
BackOffice fails with 500 and order can not be processed.

####  Expected
process order without error

####  How to reproduce

1. Go to the BackOffice > Orders > Orders 
2. click on an order where one of the following columns is NULL in the ps_address: phone, company, address2, phone_mobile
3. See error

**Cause**
NULL is not a string, therefor arguments passed to the OrderShippingAddressForViewing constructor raise TypeError

**Possible solutions**
1. when setting up prestashop force NOT NULL on optional address fields, will only work for new installations
2. make the constructor of OrderShippingAddressForViewing more robust against other datatypes
3. propper database migrations

**hot-fix**
I ran this on the mysql server, for the moment it's working again
```
UPDATE `ps_address` SET `phone`="" WHERE `phone` IS NULL; 
UPDATE `ps_address` SET `company`="" WHERE `company` IS NULL;
UPDATE `ps_address` SET `address2`="" WHERE `address2` IS NULL;
UPDATE `ps_address` SET `phone_mobile`="" WHERE `phone_mobile` IS NULL;

ALTER TABLE `ps_address` MODIFY `phone` VARCHAR(32) NOT NULL;
ALTER TABLE `ps_address` MODIFY `company` VARCHAR(255) NOT NULL;
ALTER TABLE `ps_address` MODIFY `address2` VARCHAR(128) NOT NULL;
ALTER TABLE `ps_address` MODIFY `phone_mobile` VARCHAR(32) NOT NULL;
```

**Full error**
`Type error: Argument 4 passed to PrestaShop\PrestaShop\Core\Domain\Order\QueryResult\OrderShippingAddressForViewing::__construct() must be of the type string, null given, called in /var/www/vhosts/<hostname redacted>/httpdocs/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php on line 270`

#### Additional infos
PrestaShop version: 1.7.7.1
PHP version: 7.2

### PR DESCRIPTION
**Pull request by FredBrockstedt**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  1.7.7.0 and 1.7.7.1
| Description?      | Harden OrderShippingAddressForViewing and OrderInvoiceAddressForViewing against old/messy data in ps_address, that contains null values, leading to a Server Error 500 in the backend, because of type conversion.
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23336
| How to test?      | Create a new object OrderShippingAddressForViewing(1, 'John', 'Doe', null, 'Street 123', null, 'City', 'Country', '12345', null, null) this should not raise TypeError null is not a string.
| Possible impacts? | For the user, null values will be displayed as empty string in the address field or on the invoice.

PS: Fixes #23336 and probably #22386 and #22215 as well 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23354)

### CODE REVIEW

**Comment by Progi1984** [comment]
@FredBrockstedt Could you target the `develop` branch ? The issue is not defined as regression, so the PR will not be included in patch version for 177x.

**Review by matks — CHANGES_REQUESTED** [review]
Hi @FredBrockstedt 

> old/messy data in ps_address, that contains null values, leading to a Server Error 500 in the backend, because of type conversion.

Actually I believe that these Server Error 500 are somehow a good thing. Because you said it yourself: the main reason why this Server Error is because the data below, hidden in MySQL is old, messy, irregular, inconsistent. This is an advantage of strongly typed applications: they just refuse messing up with types, and that leads to a huge decrease in bugs.

So I would like to keep this strictness, and rather work on fixing the database ; rather than making the code fault-tolerant and lose the advantages of a strongly typed application.

What do you think?

**Comment by FredBrockstedt** [comment]
> @FredBrockstedt Could you target the `develop` branch ? The issue is not defined as regression, so the PR will not be included in patch version for 177x.

hi @Progi1984,
How do we make it a regression patch? I think neither 1.7.7.0 or 1.7.7.1 should have been released without it.

**Comment by FredBrockstedt** [comment]
> Actually I believe that these Server Error 500 are somehow a good thing. Because you said it yourself: the main reason why this Server Error is because the data below, hidden in MySQL is old, messy, irregular, inconsistent. This is an advantage of strongly typed applications: they just refuse messing up with types, and that leads to a huge decrease in bugs.
> 
> So I would like to keep this strictness, and rather work on fixing the database ; rather than making the code fault-tolerant and lose the advantages of a strongly typed application.
> 
> What do you think?

Hi @matks,
I kinda go along with your reasoning, but it highly depends on the time and place.
It's great if you catch a 500 in development, it's another thing if a client calls you and says, no fresh orders can be processed, which is what happened to me and judging from the issues to other people too.
In the broader sense of PHPs strictly typed, this is still strictly typed, as you couldn't pass an int as postal code.
Getting the migrations straight would be a good thing, but let's not foul ourselves, the day there is no messy data in any production system, is the day our lord and saviour comes down from the heavens.

Maybe view this as a temporary thing. Patching it will buy some time, to get the database situation fixed and in a future release the "?" can be safely removed without great effort.

**Comment by matks** [comment]
> Maybe view this as a temporary thing. Patching it will buy some time, to get the database situation fixed and in a future release the "?" can be safely removed without great effort.

PrestaShop is not meant to have temporary things in it 😅  . Release software lives forever.

You're free to customize and extend the PrestaShop Core to adapt it ; but we cant put temporary things in the Core (else @PierreRambaud will eat me 🍖 ).

> It's great if you catch a 500 in development, it's another thing if a client calls you and says, no fresh orders can be processed, which is what happened to me and judging from the issues to other people too.

The 500 actually indicates an issue: the messy/old database stuff. If we just make the code fault-tolerant, the database content will stay corrupted, likely to create issues later in the future.

I see 2 possible ways (there might be more) to solve this situation without "softening" the code and removing the strictly typed behavior:

1. Catch TypeError (is that possible with php ?) at controller level to display an informative message, making it easier for customer to understand the situation. Example of such message "The order data could not be displayed because part of it is corrupted. Please fix the irregular data."
2. Look for such discrepancies in database earlier in the process, either during upgrade process (and maybe, if detected at this moment, attempt to fix it?) or when opening the dashboard, some red warnings that pops up to indicate this issue?

**Comment by LordTama** [comment]
Hello.
I understand your point of view to not modify the code to solve the issue. But why the database was corrupted in the first place ? We are many users with the exact same issue. For me it’s a regression. It’s happening only with new clients since my upgrade to the 1.7.7 branch. My database is very old, something like 5 years or more, and it’s the first time we see this.

**Comment by matks** [comment]
> But why the database was corrupted in the first place ?

Each shop has its unique history. The possible ways I can think of, for data reaching an inconsistent state, are:
- SQL structure modified by modules, overrides, sysadmins (for optimization purposes sometimes)
- incorrect SQL structure in old versions of PrestaShop: I dont think previous versions of PrestaShop were bug-free (nothing in the software world is bug-free 😄 ) and we could be facing an issue stayed undetected for years
- issues during upgrade process: upgrading a SQL database in production will always be a tough challenge, especially when the SQL structure might vary because of customizations introduced by modules or overrides

> It’s happening only with new clients since my upgrade to the 1.7.7 branch.

The previous implementation of the Order View Back office page was a lot more fault-tolerant. So it gave the wrong impression "it works !" but actually there was issues inside the database content.

I dont think it was even fault-tolerant on purpose, it was rather relying on PHP [Type Juggling](https://www.php.net/manual/en/language.types.type-juggling.php).

Type juggling may look like a nice thing at first, because "it works!" . But under the hood, the issues arise, undetected, and are likely to create deeper consequences. For example maybe a webpage rendered by PHP will "display just right" but when the data is exported into an ERP, the discrepancies become visible.

> For me it’s a regression

I can see why you think that:
- on PrestaShop 1.7.6, the data loads fine
- on PrestaShop 1.7.7, the page fails to load

But once again, it's a false impression 😄  . The culprit seems to be the code, but it's rather the data being loaded that was "tolerated" by PrestaShop 1.7.6 and is not anymore by 1.7.7 .

Making the code more fault-tolerant might look appealing, but what this will do is that it will allow you to continue running your shop with invalid data. This data being invalid must, at some point, be fixed 😄  you cant avoid that.

That being said, that is what we aim to do in the PrestaShop Core, but this is an open source project: if you disagree with this view, you are free to operate the changes you want (like the ones in this Pull Request) to make your shop more fault-tolerant. That is the strength of open source: take what you like, and modify the things you dislike 😄 . We dont want to make the Core more fault-tolerant, but you, and only you, decide what the code on your shop does.

**Comment by FredBrockstedt** [comment]
Hey @LordTama and @matks,

about the question, some parts of Prestashop handling addresses like to put null in an optional field and some like to put "". Performance should be the same, but null is not a string although in a VARCHAR column, causing the issue. Sadly there is no Gentlemans agreement, that only "" should be used. And even if there was, I'd feel rather uncomfortable, knowing there is a ticking null bomb. How many modules like to write null values to ps_address, I cannot say.

@matks: Thank you for making a clear decision. I like that.
If we can't compromise on the easy thing, let's compromise on the hard thing.
If we can't change the constructor, then let's protect it against null values, by altering all VARCHAR columns in ps_address to NOT NULL.
How many modules will throw exceptions, because they can't write null to ps_address, I cannot say.
@matks made the decision, so I think it's fair to make it his responsibility, to see this through.

My patch is certainly two months late. Waiting longer will cause more people to hotfix the database by hand, which will cause more problems down the line. It might appear optional to patch, but it's not optional to see the shipping address and invoice in production.

One final thing, before I close this PR.
What kind of bug are you trying to catch by not allowing null in the constructor?

**Comment by bastienuh** [comment]
Hi, this PR will not fix the issue, because there is at least one more file to update, for same reason :

**src/Core/Domain/Order/QueryResult/OrderMessageForViewing.php :**
```php
public function __construct(
        int $messageId,
        ?string $message,
        OrderMessageDateForViewing $messageDate,
        ?int $employeeId,
        ?bool $isCurrentEmployeesMessage,
        ?string $employeeFirstName,
        ?string $employeeLastName,
        ?string $customerFirstName,
        ?string $customerLastName,
        ?bool $isPrivate
    ) {
        $this->messageId = $messageId;
        $this->message = strval($message);
        $this->messageDate = $messageDate;
        $this->employeeFirstName = strval($employeeFirstName);
        $this->employeeLastName = strval($employeeLastName);
        $this->customerFirstName = strval($customerFirstName);
        $this->customerLastName = strval($customerLastName);
        $this->employeeId = strval($employeeId);
        $this->isPrivate = strval($isPrivate);
        $this->isCurrentEmployeesMessage = strval($isCurrentEmployeesMessage);
    }
```

By adding the above code and the code of this PR, everything was solved.

**Comment by matks** [comment]
Hi everyone, as nothing moves anymore on this PR I close it. As said before, we dont want to make the Core more fault-tolerant as we think it only brings more issues than it solves.

But you, and only you, decide what the code on your shop does: if you disagree with this view, you are free to operate the changes you want (like the ones in this Pull Request) to make your shop more fault-tolerant. That is the strength of open source: take what you like, and modify the things you dislike 😄 .

Thank you for your contribution @FredBrockstedt

**Comment by Davidorul** [comment]
Really ? No one will ever fix this ? And all PS users that had 1.6 and upgraded to 1.7 will have to fix their DB by hand ?

I already ran several kB of SQL "hotfixes" and still have issues here and there (because of product combinations and variants). :-/

**Comment by matks** [comment]
> Really ? No one will ever fix this ? And all PS users that had 1.6 and upgraded to 1.7 will have to fix their DB by hand ?
> 
> I already ran several kB of SQL "hotfixes" and still have issues here and there (because of product combinations and variants). :-/

Open source is not free support. If you find that any issue is critical for you, and it's important to have it fixed ASAP, then you can _invest_ into having it done. You can hire a developer to fix it, or if you are a developer yourself, you can try doing it on your own. The most important thing is to share that fix with everyone -- that's what the open source spirit is all about. It will become helpful for other people.

I also seize the opportunity to remind you of our Code of Conduct (regarding other comments you posted) https://github.com/PrestaShop/PrestaShop/blob/25337bb5a97fe95caabd8ac92cef9fb9813abc18/CODE_OF_CONDUCT.md

> Examples of behavior that contributes to creating a positive environment include:
>
> Using welcoming and inclusive language
> Being respectful of differing viewpoints and experiences
> Gracefully accepting constructive criticism
> Focusing on what is best for the community
> Showing empathy towards other community members

Please be careful about how you speak, so that we can keep a collaborative and positive environment here.

**Comment by Davidorul** [comment]
I am very sorry for my wording and commenting on an old thread like this. I guess I was just really frustraded trying to fix an upgraded PS installation...

I ran into this issue (like many others) and was hoping to find a quick solution - which I thought was actually provided here. And so I really didn't understand why this wasn't resolved in a different way back in Feb/May/Aug...

Sorry, I really didn't want to disrespect your work on PS.

**Pull request closed without merging**
