### PR TITLE
Add external libraries

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add font-awesome library
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | - 
| How to test?  | call function & test your icon

In controller : 
```php
$this->requireAssets(array('font-awesome'));
```

In module : 
```php
$this->context->controller->requireAssets(array('font-awesome'));
```

Register your module to display header : 
```php
public function hookDisplayHeader()
{
    $this->context->controller->requireAssets(array('font-awesome'));
}
```

To be optimised!

**NOTE:** so far this only works with font-awesome, more libraries should be added.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Great idea! Although I'd rather a more generic method, so we can extend it.

```php
$this->context->controller->requireAssets(['font-awesome']);
```

**Comment by firstred** [comment]
:open_mouth: That would be even better. Great initiative!

**Comment by kpodemski** [comment]
Full agree with @julienbourdeau

Good idea though!

**Comment by aleeks** [comment]
Hello @firstred @kpodemski 
If this solution is ok for you, we will update this PR :+1:

**Comment by kpodemski** [comment]
@aleeks it's great

**Comment by firstred** [comment]
Yes, it's great! This is how I like it. Keep going! :D

**Comment by xBorderie** [comment]
Super nice!
Now, to write the doc about it. Any candidate? ;)

**Comment by aleeks** [comment]
@julienbourdeau for asset priority
@PrestaShop/prestashop-core-dev @kpodemski @firstred  for comments

It can be better, we can discuss about this, it's just to test for moment

**Comment by xBorderie** [comment]
Sure, I know it's still a WIP, but I'm pretty sure devs will want to have doc about this quickly :)

**Comment by firstred** [comment]
It's on the develop branch. How long will it take before this lands in an actual release?

It's basically a behavioral change, so shouldn't this be postponed until 1.7.1? We're still SemVer-ing right?

**Comment by xBorderie** [comment]
Indeed, I doubt it'll be merged for a patch update.

**Comment by kpodemski** [comment]
@firstred let's be honest, i don't think that it's something that important, we should respect semver but from the other side we should treat semver reasonable

**Comment by julienbourdeau** [comment]
This will be merged into develop, which is the branch for 1.7.1. I strongly believe that the whole 1.7 eco system will upgrade to 1.7.1 and that not many stores will run 1.7.0.x in production for a long time.

**Pull request merged**
