### PR TITLE
Merge 8.1.x into develop

### PR DESCRIPTION
**Pull request by 0x346e3730**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.1.x into develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Run tests 
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | PrestaShop

### CODE REVIEW

**Comment by 0x346e3730** [comment]
Tests : https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4202002625

**Review by lartist — APPROVED** [review]

**Comment by zuk3975** [comment]
Some of integration tests seems to be failing. The ones in BO might be restarted and work in second try, but the one in FO is probably failing legitimately

**Comment by nesrineabdmouleh** [comment]
> Tests : https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4202002625

Hello @zuk3975,

UI tests are :heavy_check_mark: 
The errors of **[test (functional:FO, develop)](https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4202002625/jobs/7331800279#logs)** and **[test (functional:BO:orders:01, develop)](https://github.com/0x346e3730/ga.tests.ui.pr/actions/runs/4202002625/jobs/7331797720#logs)** exit on [nightly](https://github.com/PrestaShop/PrestaShop/actions/runs/4219188557)

**Review by matthieu-rolland — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
LGTM for UI tests

**Comment by nicosomb** [comment]
Thank you @0x346e3730 and @boubkerbribri !

**Pull request merged**
