### PR TITLE
Add psgdpr module as native

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add psgdpr module as native
| Type?             | new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | See #24643
| How to test?      | The module is installed with PrestaShop
| Possible impacts? | None that I can see, the module was being pushed by API before

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27036)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@eternoendless PR title is 'add psgdpr and blockreassurance' but you add psgdpr and ps_googleanalytics

**Comment by eternoendless** [comment]
I don't know what you're talking about 😗 🎶

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
CI will be fixed with https://github.com/PrestaShop/ps_googleanalytics/pull/106

**Review by sowbiba — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
The selected version of `prestashop/ps_googleanalytics` is buggy and will not work if we integrate it like that

**Review by matthieu-rolland — COMMENTED** [review]
so what's the next step for this PR?

I guess we should wait for the selected version of the ps_googleanalytics module to be fixed unless we choose another version for now?


(That is, if the bug comes from the module itself and is not related to a malfunction in prestashop)

@eternoendless what do you think ?

**Comment by eternoendless** [comment]
I'd say this is blocked until the module has been fixed.

**Comment by matks** [comment]
@eternoendless Modules GDPR and Google Analytics have new released versions

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
Integration tests are failing. Maybe since `psgdpr` creates an anonymous user address? 🤔

**Comment by PrestaEdit** [comment]
Hi,

Already done there: https://github.com/PrestaShop/PrestaShop/pull/27962

**Comment by Progi1984** [comment]
Thanks @PrestaEdit

**Pull request closed without merging**
