### PR TITLE
Fix for image change in zoom modal window

### PR DESCRIPTION
**Pull request by iqit-commerce**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | When combination for product change, then DOM is refresh so with previouse code click function was not triggered.
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | /no
| Fixed ticket? | 
| How to test?  | Go to product with combination, change attribute, open modal with images and change image by clicking on thumbail

### CODE REVIEW

**Review by maximebiloe — APPROVED** [review]

**Comment by iqit-commerce** [comment]
there is another PR which fix this isssue https://github.com/PrestaShop/PrestaShop/pull/7725

**Comment by vincentbz** [comment]
Oh thanks !
We should have seen that you already fixed it, sorry for that :-/

**Comment by aleeks** [comment]
Hello @iqit-commerce 
Can you amend your commit ?

**Comment by vincentbz** [comment]
Hi,

It doesn't work for me :-/ Still the same problem, if I click on another image, it doesn't change.
i've emptied cache, tried on a private navigation, nothing different

**Comment by maximebiloe** [comment]
I've cherry-picked your commit here: https://github.com/PrestaShop/PrestaShop/pull/7742 and add the compiled assets

**Comment by root-it** [comment]
Upgraded to 1.7.1.1 and this issue still exist.

**Pull request closed without merging**
