### PR TITLE
Updated Lithuanian language stop words blacklist

### PR DESCRIPTION
**Pull request by jusurb**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added Lithuanian language stop word blacklist
| Type?         | improvement
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? |  #16575 
| How to test?  | Open BO index.php?controller=AdminSearchConf switch to **lt** make sure you see the newly added stop words

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16576)

### CODE REVIEW

**Comment by LouiseBonnard** [comment]
Dear @Gamesh, thanks a lot for this PR! I've just asked the Lithuanian proofreaders on [Crowdin](https://crowdin.com/project/prestashop-official) to check it and confirm that all is fine for them. I will approve the wording as soon as I have their feedback. ;-)

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @Gamesh 

It's ok if I install the store in Lithuanian language but if I add the localisation Pack the stop words is still in english

**Comment by jusurb** [comment]
@PierreRambaud any tips on what @sarahdib said, what is missing?

**Comment by PierreRambaud** [comment]
@Gamesh I'm sorry, I don't have any idea why words are still in english :thinking:

**Comment by jusurb** [comment]
@sarahdib @PierreRambaud i will not investigate this further as i've done with my prestashop project, so this PR is now take it or leave it :) 
basically either we merge it as is and improve for people installing LT language or we don't do anything and i close this PR

**Comment by jusurb** [comment]
> Dear @Gamesh, thanks a lot for this PR! I've just asked the Lithuanian proofreaders on [Crowdin](https://crowdin.com/project/prestashop-official) to check it and confirm that all is fine for them. I will approve the wording as soon as I have their feedback. ;-)

@LouiseBonnard i don't blame you for not trusting a Lithuanian to write Lithuanian translations 😄 but any updates on this?

**Comment by LouiseBonnard** [comment]
Hi Gamesh, the wording has been approved after my comment, hence the _wording approved_ label last December. So everything is fine on this part! Please don't blame me, aha, it is not a question of trust rather than a question of double-checking the content - like the code is reviewed, the wording also needs to be reviewed. :-)

I read again the issue and it looks like this translation does not fix the problem, cf. [Sarah's comment](https://github.com/PrestaShop/PrestaShop/pull/16576#issuecomment-575378733). So I did some research and it turns out the string has not been properly translated in Lithuanian in [Crowdin](https://crowdin.com/translate/prestashop-official/all/en-lt#q=a%7Cabout), see my screenshot below. It explains your issue. I've asked the proofreaders to approve your suggestion, I will test it as soon as they validate it and close this issue if fixed.

Capture d’écran 2020-05-14 à 16 11 26

I keep you posted!

**Comment by jusurb** [comment]
@LouiseBonnard sure, thanks :)

**Comment by LouiseBonnard** [comment]
Many thanks for this pull request, @Gamesh, the translation issue has been solved directly on Crowdin. As a consequence, I close this PR.

**Pull request closed without merging**
