### PR TITLE
Update deleteFeatures() for Multi-shop

### PR DESCRIPTION
**Pull request by ghost**
If in a shop context, it deletes all values in all shops.
This fix this bug.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commit's name to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog?
To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this must be done via the command line: just changing the title of the pull-request from the GitHub interface is not the same!_ :)

Thank you!

**Comment by creaweb06** [comment]
Hi,
I've just changed the title of the commit. Please let me know if something's wrong.
Ty

**Comment by xBorderie** [comment]
Thank you Thomas, but you changed the title of the pull-request via the GitHub interface, which is not the same :)
Changing the commit's name (or commit message) requires you to use the command line interface on your `patch-3` branch. See this guide for help: https://help.github.com/articles/changing-a-commit-message/
Thank you for the update!

**Comment by creaweb06** [comment]
Hi,
We made some changes within the commit with all the branch (patch-3 to patch-5).
Hope it's good ;-)
Thank for your help

**Comment by aleeks** [comment]
Hello @creaweb06 
I cherry-pick your commit here: https://github.com/PrestaShop/PrestaShop/pull/7489/files rebased from develop.
Thank you

**Pull request closed without merging**
