### PR TITLE
Optimised attribute get all call

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Make this call more fast by removing all useless calls |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Access Product page and take a look to xhr requests: one of them is `<your-website>/attribute/get-all`, after optimisations this call is faster. |

**Before:**
before

**After:**
final_opti

Blackfire analysis required please :)

### CODE REVIEW

**Comment by maximebiloe** [comment]
capture d ecran 2016-06-20 a 16 52 18

Not sure it's really beneficial in this case

**Comment by mickaelandrieu** [comment]
@maximebiloe so weird :/ can you put a link to the graph analysis please?  :)

**Comment by maximebiloe** [comment]
Sure!
Here is on `develop`: https://blackfire.io/profiles/b867697e-8806-4063-8d58-54305ac7d012/graph
and then on your branch: https://blackfire.io/profiles/1f95368d-1ba0-4428-ab25-09562f917094/graph

**Comment by mickaelandrieu** [comment]
Not wort, closed.

**Pull request closed without merging**
