### PR TITLE
Put multiple image feature toggle into the "new feature" block

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Image feature toggle should appear in the `new feature` block.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |no
| How to test?      | Image feature toggle should appear in the `new feature` block instead of `experimental`
| Fixed ticket?     | #31663
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello,

I have launched the automatic tests on this PR and i have thse failures : https://github.com/HanaRebaiQA/testing_pr/actions/runs/4353164069 

Compared to the Nightly of 8.1.x. There is only the Product V2 wich is failed

**Review by HanaRebaiQA — COMMENTED** [review]
Hello,

I have launched the automatic tests on this PR and I have these failures: https://github.com/HanaRebaiQA/testing_pr/actions/runs/4353164069 

image


Compared to the Nightly of 8.1.x. There is only Product V2 which is failed

image

ping @PrestaShop/qa-automation Could you please check if these failures are related to this PR ?

My functional tests are in progress.

Thank you!

**Comment by nesrineabdmouleh** [comment]
> Hello,
> 
> I have launched the automatic tests on this PR and I have these failures: https://github.com/HanaRebaiQA/testing_pr/actions/runs/4353164069
> 
> image
> 
> Compared to the Nightly of 8.1.x. There is only Product V2 which is failed
> 
> image
> 
> ping @PrestaShop/qa-automation Could you please check if these failures are related to this PR ?
> 
> My functional tests are in progress.
> 
> Thank you!

Hello @HanaRebaiQA,
Please rebase your fork
Thank you!

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @matthieu-rolland 

I have checked your PR. The feature is OK. But, I have always had failures in automatic tests even after updating my fork.
As you can see here: https://github.com/HanaRebaiQA/testing_pr/actions/runs/4363348360 


Single shop : 
image

Multistore :
image

https://user-images.githubusercontent.com/92912932/223730668-db4f6805-3188-43a6-a3fa-6a819c26d12d.mp4



Could you please check if it's related to your PR ? ping @PrestaShop/qa-automation Could you please check it ?

@nesrineabdmouleh Thank You for your answer. 
Thank You!

**Comment by nesrineabdmouleh** [comment]
> Hello @matthieu-rolland
> 
> I have checked your PR. The feature is OK. But, I have always had failures in automatic tests even after updating my fork. As you can see here: https://github.com/HanaRebaiQA/testing_pr/actions/runs/4363348360
> 
> Single shop : image
> 
> Multistore : image
> 
> Could you please check if it's related to your PR ? ping @PrestaShop/qa-automation Could you please check it ?
> 
> @nesrineabdmouleh Thank You for your answer. Thank You!

Hello @HanaRebaiQA 
You're welcome :)
The errors are related to setup mailutils and not to UI tests, please relaunch the failed jobs!
Thank you!

**Review by HanaRebaiQA — APPROVED** [review]
Hello @nesrineabdmouleh 

Thank you again for your feedback :) 
I have launched again the automatic tests. The number of failures jobs is reduced https://github.com/HanaRebaiQA/testing_pr/actions/runs/4363348360/jobs/7633030454 

The error are related to the setup mailutils as you have mentioned.

So, It's QA :heavy_check_mark: 

Thank You!

**Comment by FabienPapet** [comment]
Thank you @matthieu-rolland

**Comment by matthieu-rolland** [comment]
thank you for the tests @HanaRebaiQA and @nesrineabdmouleh :+1:

**Pull request merged**
