### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | This var is not used ; it's handled inside the src/PrestaShopBundle/Resources/views/Admin/Configure/AdvancedParameters/Webservice/index.html.twig template
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
No need for QA, to be merged after CI 🟢

**Comment by paulnoelcholot** [comment]
Hello @PrestaEdit,

I tested your PR and ti's good for me! :tada: 

Thanks!

Auto test : https://github.com/paulnoelcholot/testing_pr/actions/runs/12356955879

**Review by paulnoelcholot — APPROVED** [review]

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by FabienPapet** [comment]
Thank you @PrestaEdit

**Pull request merged**
