### PR TITLE
Remove initForm* from old product controller

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As suggested by @mickaelandrieu [here](https://github.com/PrestaShop/PrestaShop/pull/7367#issuecomment-275785950) those methods shouldn't be called anymore so let's remove them!
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

### CODE REVIEW

**Comment by aleeks** [comment]
Make sense beucause Product page is generated by Symfony ..

**Comment by antoin-m** [comment]
Yeah but some of the old methods are still being called from the new controller if I remember correctly

**Comment by aleeks** [comment]
Yes, but not the functions you're removing here?

**Comment by maximebiloe** [comment]
So much love in the branch name 😍

**Comment by antoin-m** [comment]
@aleeks I hope not :crossed_fingers:

**Comment by aleeks** [comment]
I don't need you hope, i need ou test!

**Comment by antoin-m** [comment]
Well I mean all the features I tried were working so I didn't notice any difference.

Merge it and if someone complains someday about a missing initForm* you know which PR to revert ;)

**Comment by basma-yangui-prestashop** [comment]
@antoin-m After applying your PR, the product quantity can no longer be saved.

Try to create a new product and set a value (>0) in the quantity field, then save and go to the catalog. You will find that the quantity of this product is null.

**Comment by xBorderie** [comment]
"Oups" :)

**Comment by antoin-m** [comment]
Weird, I tried it on my work computer and just now on my mac and it works :/

**Comment by aleeks** [comment]
Hello @basma-yangui-prestashop 
It's working for me too. Can you reproduce your situation ?

**Comment by maximebiloe** [comment]
capture d ecran 2017-02-07 a 11 02 51

Okay for the perfs, but I can't set my combination quantities either 😢

**Comment by aleeks** [comment]
Thank you @antoin-m

**Comment by aleeks** [comment]
Thank you @antoin-m

**Pull request merged**
