### PR TITLE
Remove migrated shopping carts pages feature flag

### LINKED ISSUE #10584: Migrate "Orders > Shopping Carts" page
Type: page
Part of Symfony migration project

## Status

Todo :
- [ ] Migrate listing
- [ ] Migrate KPIs
- [ ] Remove "Delete" actions from carts that have placed orders (see https://github.com/PrestaShop/PrestaShop/issues/10584#issuecomment-723147564)
- [ ] [Add a modal to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)

Previous PRs for step 1: https://github.com/PrestaShop/PrestaShop/pull/17883 and https://github.com/PrestaShop/PrestaShop/pull/17326

### Controller / template
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove `carts` feature flag for the new migrated shopping carts pages in BO.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | After installation of this PR, migrated shopping carts pages in bo must be displayed by default instead of the legacy ones.
| UI Tests          | We need to update tests ui before. https://github.com/boherm/ga.tests.ui.pr/actions/runs/7928192249 ✅ 
| Fixed issue or discussion?     | Fixes #10584 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @boherm

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Make sure to migrate the links also. ;-)

Snímek obrazovky 2024-02-12 152435

**Review by jolelievre — DISMISSED** [review]

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by nesrineabdmouleh — DISMISSED** [review]

**Comment by paulnoelcholot** [comment]
Hello @boherm,

I tested your PR and it's good for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @boherm and @paulnoelcholot

**Comment by boherm** [comment]
We don't really need a autoupgrade PR, the FF is introduced in 9.0.0.

**Pull request merged**
