### PR TITLE
Can't transformToCustomer while password max length is shorter than default 16 length

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | There is known bug, because already there is text "_TODO - This should be revised in the future because 16 chars can be outside of bounds of * isAcceptablePasswordLength. It should not be checked._". I found it accidentally, when eshop owner reported me transform Host to Customer isn't working. I found it. Problem is when we set up maximum password length lower than default 16 characters. In this PR I already took into account opposite story (min pass length) - but this is only theoretical, from land of dreams... :)
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Set maximal password length to 15 (for example), before this PR you are not able to transfer Host to Customer. After apply this PR, it will works.
| UI Tests          |  https://github.com/florine2623/testing_pr/actions/runs/10920473355
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `description` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#description))
* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by SharakPL** [comment]
> ...not able to transfer Host to Customer

Do you mean transforming a Guest account into a Customer account?

**Comment by Hlavtox** [comment]
Two points here:
- Maybe you could just do average between the two values.
- There seems to be a scenario where it falls back to default values, should we account for it? https://github.com/PrestaShop/PrestaShop/blob/628978d9d42a9d44794f0b47dbc21b74588d68af/classes/Validate.php#L568

**Comment by Hlavtox** [comment]
Oh, its already fixed on develop, it checks the length only of the password was provided.

See - https://github.com/PrestaShop/PrestaShop/blob/628978d9d42a9d44794f0b47dbc21b74588d68af/classes/Customer.php#L1226

**Review by FabienPapet — DISMISSED** [review]

**Comment by ShaiMagal** [comment]
@Hlavtox Ah, OK, so I used solution from develop, we need to backport it to 8.x branch.

BTW - Why this fix is in develop and not 8.x branch? ://// This should be in 8.x as well.. It's not obsolete version, we must support it...

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by matks** [comment]
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

**Comment by matks** [comment]
> BTW - Why this fix is in develop and not 8.x branch? ://// This should be in 8.x as well.. It's not obsolete version, we must support it...

Because the changes were introduced by https://github.com/PrestaShop/PrestaShop/pull/31076 with other chanes

**Review by matks — APPROVED** [review]
OK for me but I think QA team will need a little more details 😉

**Review by matks — DISMISSED** [review]
@ShaiMagal As PHPStan indicates, `$crypto` variable does not exist. I think you got the code from `develop` but need to acknowledge the code between 8.1.x and develop is different

**Comment by ShaiMagal** [comment]
@matks Thank you, you are right.
I edited PR, tests are green.

**Review by Hlavtox — APPROVED** [review]

**Comment by ShaiMagal** [comment]
@matks ? :)

**Comment by matks** [comment]
Sorry guys I am lost in the limbo

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @ShaiMagal ,

Here are the steps I used to QA this PR :
- Got to FO > Add product to cart > Proceed to checkout
- Step 1 of checkout process > Order as guest
- Proceed to checkout until Your order is confirmed
- Go to BO > Customers > Edit your latest customer
- Edit `Group access` and `Default customer group` to Customer **only**
- Add a password less than 10 characters
- Save OK
- Go to FO > Log into as customer with email and password less that 10 characters
- Login NOK :x:

If I understand well, I should be able to do the last step without error with this PR, but it is not the case.

https://github.com/user-attachments/assets/f73cbe2c-2954-4f98-ad41-05ddaa9ef6c7

I don't know how to `Set maximal password length to 15 (for example)`, could you specify where I can do that ?

Thanks!
Waiting for your feedback :)

**Comment by Hlavtox** [comment]
@florine2623 I will help you, here are the steps to reproduce:
- Go to advanced parameters > Security and set Maximum password length to 15 characters.
- Now, make an order in FO as a guest.
- On the confirmation screen (or if you go to guest order tracking page), you have an option to convert yourself into a customer.
- If you try it without this PR, it will fail.
- If you try it with this PR, it will work.

**Review by florine2623 — COMMENTED** [review]
Oh thanks @Hlavtox ^^

I have checked with your steps.

Screenshot 2024-09-18 at 17 26 04

I tried to create the customer account from :
- guest tracking page
- order confirmation page
- from BO as a merchant

In all those cases, I can't log into my _customer_ account 😅 

Am I missing something ? (The PR is well installed)

**Comment by Hlavtox** [comment]
@florine2623 Ah, sorry :D

Please, new steps:
- Go to advanced parameters > Security and set Maximum password length to 15 characters.
- Create order as a guest.
- Go to BO > Customers, find the customer.
- Click on the button to transform the guest into a customer.
- Not working without PR, working with PR.

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

It works as expected ^^

Sorry I couldn't test properly before because I set _Minimum_ password length to 15 characters instead of _Maximum_. My bad, sorry.

I tested multiple cases to transform a guest account to a customer account.
- from FO > order confirmation ✅ 

https://github.com/user-attachments/assets/452b7841-76b3-4aed-9e8a-e497c25a8e57

- from FO > tracking url ✅ 

https://github.com/user-attachments/assets/f93e0b1f-adb4-43a3-9ff4-e6718a05b126


- from BO : with **only** _Customer_ as Group access and Default customer group, with multiple Group access and Default customer group _Customer_ 
This case doesn't work because the minimum password is 15 in the BO and the merchant should know that ✅ 

https://github.com/user-attachments/assets/49e9f211-0997-4afd-befb-28755d12b54b

Thanks!
It is QA ✅

**Pull request merged**
