### PR TITLE
Remove deprecated hooks from 1.5

### PR DESCRIPTION
**Pull request by julienbourdeau**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Remove deprecated hooks from 1.5 |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | I don't think anyone used them anymore |

### CODE REVIEW

**Comment by thierrymarianne** [comment]
To be tested with https://github.com/PrestaShop/ps_linklist/pull/18

**Comment by maximebiloe** [comment]
It's easier to merge this one and close yours @thierrymarianne, @julienbourdeau was faster. Sorry 😉

**Comment by vincentbz** [comment]
One case is missing here, if the block name is empty, there is still an error

image

**Comment by thierrymarianne** [comment]
@vincentbz It has been taken care of with https://github.com/PrestaShop/ps_linklist/pull/18

**Comment by vincentbz** [comment]
Ahhhh ok thanks :)

**Pull request merged**
