### PR TITLE
Retry downloading language packs

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Tries to avoid temporary failures by attempting to download a language pack several times.
| Type?             |  improvement
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | Check that you can update language pack correctly from back office
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33514
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — APPROVED** [review]
this is a nice quality of live improvement :+1:

**Review by boherm — APPROVED** [review]
Nice improvement! Thanks @Hlavtox 🙂

**Review by sallemiines — APPROVED** [review]
Hello @Hlavtox 

Thnx for the PR LGTM QA  :heavy_check_mark: 

Thank you

**Review by sallemiines — APPROVED** [review]
Hello @Hlavtox 

Thnx for the PR LGTM QA  :heavy_check_mark: 

Thank you

**Comment by Hlavtox** [comment]
Thank youuuuu @sallemiines!

**Pull request merged**
