### PR TITLE
Remove FrameworkExtraBundle `@Template` annotation.

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The @template annotation is deprecated and will be removed in future versions. We should not add any usages of it. 
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Indicate how to verify that this change works as expected.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
I think it'll be considered BC Break if one decorated those controllers. Right? :)

**Review by matthieu-rolland — APPROVED** [review]

**Comment by FabienPapet** [comment]
> I think it'll be considered BC Break if one decorated those controllers. Right? :)

I don't know

**Review by florine2623 — APPROVED** [review]
Hello @FabienPapet ,

Link to automated tests : https://github.com/florine2623/testing_pr/actions/runs/4260586103/jobs/7415240787

Tested those pages in BO :
Screenshot 2023-02-24 at 14 18 53

No regression or exception were found.

It is QA ✅ !

**Comment by FabienPapet** [comment]
Thank you @florine2623

**Pull request merged**
