### PR TITLE
[-] CORE : Correct fatal error with php7

### PR DESCRIPTION
**Pull request by sfroment**
Fatal error: Uncaught EngineException: Access to undeclared static property: Validate::$values

### CODE REVIEW

**Comment by tchauviere** [comment]
Wait for PHP 5.4 before this can be merged. It will fail < PHP 5.4

**Comment by panploenes** [comment]
Can we have a label for these fixes? So its easier to find and apply them manuelly.
Just an idea...

**Comment by tchauviere** [comment]
Hi @panploenes,

We were just talking about that idea atm. I think we will do that :)

Best regards,

**Comment by sfroment42** [comment]
#3574

**Comment by ghost** [comment]
Hello, 

I am getting below error after updating my website php version from 5.6 to 7.

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/foreceen/php_scripts/forecee/db_connect.php:13 Stack trace: #0 /home/foreceen/public_html/private/meeting/facetoface/index.php(2): include_once() #1 {main} thrown in /home/foreceen/php_scripts/forecee/db_connect.php on line 13

Could you please help to solve this issue.

Thank you 
smita

**Pull request closed without merging**
