### PR TITLE
Fix product sorting on Orders page

### LINKED ISSUE #22853: Products in orders are shown in reverse order (from last to first product)
When I update my shop to 1.7.7.1 products in orders are shown in reverse order. This is problem becouse when I download them to an external inventory management, the order is different.

How to check this:
As client add to cart product 1, then product 2. Make order. Go to this order in BO. Product 2 is on first place, and product 1 on second place. In order confirmation email order of products is OK - product 1, then product 2.

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Products are in reverse order in compare to front-office and other places
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #22853.
| How to test?      | Follow #22853 and CI green
| Possible impacts? | n/a

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24822)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
I have no idea if products should be ordered from A to Z or from Z to A in the Order View Back-Office page 😄 but I see @sowbiba did the exact opposite from this PR in https://github.com/PrestaShop/PrestaShop/pull/21692 and introduced the QuerySorting object on purpose.

Can we verify together why A to Z or Z to A would be better? If we don't, maybe in 4 months someone will think that products list is not in right order on this BO page and will revert it again 😛 

ping @MatShir

**Review by matks — COMMENTED** [review]
Woups I wanted to comment no approve ^^

**Comment by kpodemski** [comment]
I think we should have identical sorting in both FO and BO, FO is A-Z for years 🤔

**Review by Progi1984 — APPROVED** [review]

**Review by Progi1984 — COMMENTED** [review]
Hi When a question has no answer, it's time to ask to @PrestaShop/product-team

**Comment by MatShir** [comment]
This was specified to be in reverse because when a product is added the list is refreshed, we thought that the merchant would see the product added if it appeared in the first page. So in the reversed order, the last products added to the order are displayed first and are not hidden in the pagination.
We didn't see any inconvenience to have a different order between the FO and BO.

**Comment by kpodemski** [comment]
@MatShir 

Yeah that was a good idea **but**

- products from an order are going to ERP right after order creation
- they're A-Z
- based on that you have a list of products to be packed, the employee is doing it and later he needs to mark products in BO

and why I understand this linked Issue? I'm working on a module that allows you to print orders and we're using A-Z, we also have an addon called "Order completing" where we also use A-Z, you open a popup, scan the product, and you see it marked as "Packed"

This A-Z, Z-A might be confusing and problematic at some point in the chain of order logistics

**Comment by MatShir** [comment]
Okay I see. Thanks for the clarification

**Comment by MatShir** [comment]
I was wondering if the one of the best solution would be to put the sort as a parameter on the Back-Office. The module could use the parameter, so every parts linked to the order will have the same order. And the developer could add new sorting depending on the business.

**Comment by kpodemski** [comment]
@MatShir 

I remember one time where merchant wanted to sort products by quantity, one where sorting should be by availability date so maybe that's a good idea **but** I'm not sure about implementation yet, maybe we should have some kind of `OrderProductsSortingProvider` where people can inject their own methods...  maybe let's create an Issue and we'll think about possible solutions there...

**Comment by matks** [comment]
@MatShir @kpodemski What about we add a simple "arrow" button inside the View Order page which controls a GET parameter and merchant can click on it to choose the sort? Just like in listings where you can decide if you want columns ordered by highest to lowest or the opposite.

That would mean the code on the server must be able to output products using both directions but it's not complex IMO.

**Comment by kpodemski** [comment]
@matks yeah that sounds like a good idea, if @MatShir is ok with it then we need to decide whether I should do it now in this PR, or add it later

**Comment by matks** [comment]
🆙 @MatShir or @marionf 😉

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-core-developers 

I guess this one should be rebased to 1.7.8.x, as there are no plans for 1.7.7.7 at this moment?

**Comment by Progi1984** [comment]
@kpodemski Affirmative.

**Comment by marionf** [comment]
> @MatShir @kpodemski What about we add a simple "arrow" button inside the View Order page which controls a GET parameter and merchant can click on it to choose the sort? Just like in listings where you can decide if you want columns ordered by highest to lowest or the opposite.

@matks yes it seems a good idea, @kpodemski could you integrate this behavior and rebase your PR on 1.7.8.x branch ?

**Pull request closed without merging**
