### PR TITLE
Convert customization price to current currency

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The customization price should be converted to give a correct total
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Create a customization then change its price in the database (usually it's done by a module which adds options to a product). Then change the currency, the total should be correct

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11282)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @unlocomqx,

you can fix your pull request executing this command in the root folder of your shop:

```
./vendor/bin/php-cs-fixer fix
```

Regards

**Comment by unlocomqx** [comment]
I rebased and reformatted my code, now the linter is green

Thank you

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by marionf** [comment]
Hello @unlocomqx 
I can't reproduce the issue, can you please send a screeshot showing the problem ?
When I edit the price in product table, the price isn't updated in the product page in BO & FO it still show the old price
Than you !

**Comment by unlocomqx** [comment]
Hi @marionf , here's the list of steps to reproduce, I will send you more info if anything isn't clear
1. Create a text customization field in the Options tab of the product edit page
https://scr.prestalife.net/sc6a8c4
2. Fill the field in the product page then save it and add it to cart
https://scr.prestalife.net/sc0d8r8
3. Change the customization price in the table "customized_data" (this step is supposed to be performed by a module)
https://scr.prestalife.net/sc0m8i4
4. The total should reflect the product price + customization price
https://scr.prestalife.net/sc6h8p5
5. Change the currency in the cart page (I use a conv rate of 10 to simplify)
https://scr.prestalife.net/sc4b2v9
6. The product price is converted but the customization price isn't converted which makes the total wrong
https://scr.prestalife.net/sc9r2z1

Best regards

**Comment by marionf** [comment]
Thank you for these details @unlocomqx 
I can reproduce the issue and your PR solve it :+1:

**Comment by PierreRambaud** [comment]
Thanks @unlocomqx

**Pull request merged**
