### PR TITLE
BO: increase specific price limit

### PR DESCRIPTION
**Pull request by vincentbz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | There is a limit of 1000 specific prices in the code. As it's frequently reported by community, i increase it to 3000
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2434
| How to test?  | Import more than 1000 specific price, see if they still work. I've just made a PR of something already tested by a contributor so it should be ok

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8428)

### CODE REVIEW

**Comment by vincentbz** [comment]
@maximebiloe coucou !

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by jocel1** [comment]
Hi @vincentbz !

It's frequently reported by the community because there were a bug earlier in the code which is now fixed both in develop and 1.6 branch. The limit of 1000 is an optimization to avoid constructing too big php array (which not really efficient with more than 1000 products), but it should not change anything to the final result :)

**Comment by kpodemski** [comment]
From what i understand it's only in situation where you have 1k specific price for one product, right? edgy case

**Comment by jocel1** [comment]
yes, but initially it was because of a bug in the method, when the threshold is reached. The bug doesn't exist anymore, so there's no need to change this parameter. However a better code would be to remove the parameter and use a constant instead, because there's no point have this variable as a parameter.

**Comment by eternoendless** [comment]
Closing this as already fixed according to @jocel1

**Pull request closed without merging**
