### PR TITLE
Upgrade jquery to latest version, drop polyfills

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Upgrades jQuery to 3.7.1 everywhere, drops live polyfills, update jquery.validate to latest version, hotffixed deprecations in some dead plugins.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | Tests green.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6651799920
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

➡️ Keeping migrate scripts for now, as we would need to upgrade jQueryUI. I will do it in a separate PR.

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]
🎉

**Comment by Hlavtox** [comment]
Updated jquery validate plugin, now the tests should be good, hopefully

**Comment by Hlavtox** [comment]
@nicosomb @mflasquin @kpodemski All good, tests green. :-) https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6651799920

Last step will be to remove jquery migrate, but for that, we need to upgrade jQuery UI, which is a bit of a problem. They don't provide built packages with separated files we need, so it will need some more thought.

**Review by matthieu-rolland — COMMENTED** [review]
nice !

what are the removed image files about ?

**Comment by Hlavtox** [comment]
@matthieu-rolland Unused jquery ui theme, it's using the base one. :)

**Review by matthieu-rolland — APPROVED** [review]
LGTM, and ui tests are fine too, nice work 👍

**Review by M0rgan01 — APPROVED** [review]
Nice work !

**Comment by florine2623** [comment]
As discussed with the team, this doesn't need to be tested by QA as auto tests is doing the job

**Comment by nicosomb** [comment]
Thank you @Hlavtox !

**Pull request merged**
