### PR TITLE
Added new link in installation footer

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x 
| Description?      | Added new link in installation footer
| Type?             |  improvement 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check if the link is present
| UI Tests          | N/A
| Fixed issue or discussion?     | #37245
| Related PRs       | N/A
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Install`
    - [ ] `Any questions? We’re here to help. Visit the <a href="https://help-center.prestashop.com/" target="_blank" rel="noopener noreferrer">Help Center</a> or <a href="https://help-center.prestashop.com/en/contact" target="_blank" rel="noopener noreferrer">contact us</a>.`

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Hi @nicosomb, this links not only doesn't work 💡, but it leads to prestashop.com.

**Comment by nicosomb** [comment]
@ibahloul-ps The 2nd link (`https://help-center.prestashop.com/en/contact`) is KO, what should be the correct URL?

**Pull request closed without merging**
