### PR TITLE
Add module infos in config page

### LINKED ISSUE #23504: Add module infos in config page
## Is your feature request related to a problem?

Currently the only way to get the version and author of the module is on the modules listing.
If you are in the module configuration page and you want to know the version and the author, you have to come back to the listing.

## Describe the solution you'd like

Display the version and author of the module in the configuration page.

Capture d’écran du 2021-03-03 17-12-54(1)

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Currently the only way to get the version and author of the module is on the modules listing.Display the version and author of the module in the configuration page.
| Type?         | improvement 
| Category?         | BO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/23504
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/23504
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23505)

### CODE REVIEW

**Review by matks — APPROVED** [review]
Seems good 🎉

**Comment by PululuK** [comment]
I would like to be able to display the status too (indicate if the module is activated or deactivated), but I have no idea about the UX.
@prestascott @TristanLDD  @NeOMakinG can you help me please ? Where can I display this information in module config page?

**Comment by NeOMakinG** [comment]
Let's wait for @prestascott feedback on this :)

**Review by PierreRambaud — APPROVED** [review]
LGTM

**Comment by prestascott** [comment]
Thanks @PululuK, I shared my feedbacks in your issue #23504!

Do you just want to make the infos available on the config page? Or do you also want merchants to be able to activate/disable the module on this page?

**Comment by marionf** [comment]
Hello @PululuK 

Do you think it's possible to integrate the [feedback](https://github.com/PrestaShop/PrestaShop/issues/23504#issuecomment-794163438) of @prestascott ?

**Comment by PierreRambaud** [comment]
Hi @PululuK ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
