### PR TITLE
Fix access for read only permissions

### LINKED ISSUE #30788: Unable to access the module for an employee without setting all permissions
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

then in personalize I have
image

but the profile can't access (invalid token, compromised) it unless I add add and delete permissions, which I don't want.
it worked without problems on 1.7.8

### Expected behavior

_No response_

### Steps to reproduce

1. go to permissions
2. choose a profile
3. set show/edit permissions for modules
4. attempt to access a module from an account with this profile

### PrestaShop version(s) where the bug happened

8.0 and 8.0.1

### PHP version(s) where the bug happened

8.1.13

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by dingedi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix https://github.com/PrestaShop/PrestaShop/issues/30788
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30788
| Related PRs       | related to https://github.com/PrestaShop/PrestaShop/pull/29067
| How to test?      | [Reproduce](https://github.com/PrestaShop/PrestaShop/pull/29067) 
| Possible impacts? | -

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Comment by FabienPapet** [comment]
Nice catch

**Review by zuk3975 — DISMISSED** [review]

**Comment by atomiix** [comment]
I think this issue is more global and we should check every controller!

**Comment by FabienPapet** [comment]
I already did a check on some controllers long time ago to fix them @atomiix, I missed that one. Maybe it's worth checking again, but it's not worth to wait that check to merge this IMO.

**Comment by FabienPapet** [comment]
@dingedi can you rebase your PR onto the 8.0.X branch please ?

**Comment by dingedi** [comment]
I couldn't do it I don't know how to do it, can you do it?
otherwise I can recreate the PR by putting the right branch

**Comment by kpodemski** [comment]
Hi @dingedi 

Sure, if you want, you can close this PR and create a new one that targets 8.0.x.

If you want to learn more about rebase, you can [read this article](https://build.prestashop-project.org/howtos/misc/rebasing-your-git-branch/).

**Comment by dingedi** [comment]
New PR here: https://github.com/PrestaShop/PrestaShop/pull/30818

**Pull request closed without merging**
