### PR TITLE
Merge 1.7.3 into develop

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Synchronize develop with updates done in 1.7.3.x branch
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | I don't know

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8530)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Maofree** [comment]
Hi
Can I know if this bug will be solved in a short time? because I think it is a big bug and I report it from many months. Nobody answer to the topic so I write here to get some info about that.

http://forge.prestashop.com/browse/BOOM-3195
after each 1.7 upgrades many modules lost their hooks in the front-office and it is necessary to reset them each time.

thanks
bye

**Comment by kpodemski** [comment]
@maofree i'm afraid that this is not going to be solved in 1.7.3... however...

@Quetzacoalt91 @mickaelandrieu 

guys, if that's a case and people have this issue... i think that this is issue which needs to be fixed before releasing a new version, imagine all these people lost their module settings after an update... this would be a disaster

thoughts @eternoendless ?

**Comment by Maofree** [comment]
ok thanks
at this moment I cannot upgrade to 1.7.x from 1.6 or start a new project with 1.7 to avoid this problem

**Comment by Quetzacoalt91** [comment]
We haven't confirmed yet, but this might be related to https://github.com/PrestaShop/PrestaShop/pull/8543. Fingers crossed!

**Pull request merged**
