### PR TITLE
Add deprecated hooks list in class

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Some hooks are now deprecated from PS 1.7. This PR adds a variable in the Hook class in order to notify the developer if one of them will be removed. The hook displayBackOfficeFooter is the first one to be flagged as deprecated. |
| Type? | new feature |
| Category? | CO |
| BC breaks? | Nope |
| Deprecations? | Yes |
| Fixed ticket? | / |
| How to test? | Install a module registered in the hook backOfficeFooter, visit several pages on the backoffice and finally look at the PrestaShop log. You should have a line about the deprecated notice. |

capture d ecran 2016-09-06 a 11 46 02

### CODE REVIEW

**Comment by prestamodule** [comment]
@Quetzacoalt91 Is there an alternative to displayBackOfficeFooter ? This hook was used to do some actions at the end of the page (not for display, but it was one of the last hook run on a page, may be useful in some cases)

**Comment by Quetzacoalt91** [comment]
As far I know there is no alternative, because there is no footer anymore on the new pages (product & modules).
This hook will survive as long as there as Legacy pages on the back office, but it is already not called anymore on the Symfony ones.

**Comment by maximebiloe** [comment]
@prestamodule you said you were using it not for display purpose. Why do you use it? We may add a new hook with a better name it it's an action hook.

**Comment by prestamodule** [comment]
> @prestamodule you said you were using it not for display purpose. Why do you use it? We may add a new hook with a better name it it's an action hook.

Because there was no alternative :)
Maybe there are new hooks into 1.7 that we can use, we did not checked for now.

We used it as a "trick" in order to do some tasks after a CSV import (and just before page reload).

It would be cool to introduce a new action hook on this controller (Import) when the import is finished (at least). What do you think ? We can make PR of course.

**Comment by Quetzacoalt91** [comment]
We are currently working on the subject about missing hooks (to add or to bring back), this is the best moment to add one if you want to. 👍

**Comment by kpodemski** [comment]
@prestamodule have you tried to use hooks available in `AdminController`? i mean dynamic hooks like `hookAdminImportControlleraction_nameAfter`?

**Comment by maximebiloe** [comment]
Thanks

**Pull request merged**
