### PR TITLE
[-] Project : Fix redirects on HTTPS

### PR DESCRIPTION
**Pull request by ghost**
- Removed hardcoded protocol
- Removed multiple QS append on some redirects

### CODE REVIEW

**Comment by doekia** [comment]
Just a quick question, why creating the function Tools::getProto() when Tools::getProtocol() seems to do the exact same thing?
See also https://github.com/PrestaShop/PrestaShop/pull/2746

**Comment by ZiZuu-store** [comment]
Maybe I'm wrong .. but to the function you reference you have to pass the $ssl parameter .. how I choose its value?

**Comment by doekia** [comment]
Calling Tools::getProtocol() without parameter or null choose de proper (once this PR applied) protocol. Hence Tools::getProtocol() seems to me doing exactly what your Shop::getProto() does

**Comment by ZiZuu-store** [comment]
If a PR will do Tools able to do the work it will be used. Of course. At
the moment it doesn't and the our patch was made against the code in dev
now

If tools has the method it has to be used, of course.... Possibly in the
plethora of other places in the gore and in the modules that are nowadays
reinventing their own wheels too

Il mercoledì 1 aprile 2015, doekia <notifications@github.com> ha scritto:

> Calling Tools::getProtocol() without parameter or null choose de proper
> (once this PR applied) protocol. Hence Tools::getProtocol() seems to me
> doing exactly what your Shop::getProto() does
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrestaShop/PrestaShop/pull/2779#issuecomment-88634070>
> .
>


-- 
Cordialmente,
Massimo -- *the ZiZuu staff*

**Comment by ZiZuu-store** [comment]
This is a patch that applies cleanly on PS 1.6.1.1
@jeromenadaud please consider it as without this change we have spurious **https -> http -> https** redirects!

```
--- classes/shop/Shop.php.orig  2015-08-27 19:56:38.000000000 +0200
+++ classes/shop/Shop.php       2015-09-04 10:06:49.144754385 +0200
@@ -190,6 +190,11 @@
         Shop::$initialized = true;
     }

+    protected static function getProto()
+    {
+        return (Configuration::get('PS_SSL_ENABLED') && Configuration::get('PS_SSL_ENABLED_EVERYWHERE')) ? 'https://' : 'http://';
+    }
+
     public function setUrl()
     {
         $cache_id = 'Shop::setUrl_'.(int)$this->id;
@@ -358,7 +363,7 @@
                         $redirect_header = ($redirect_type == 1 ? 'Found' : 'Moved Permanently');
                         header('HTTP/1.0 '.$redirect_code.' '.$redirect_header);
                         header('Cache-Control: no-cache');
-                        header('Location: http://'.$url);
+                        header('Location: '.self::getProto().$url);
                         exit;
                     }
                 }
@@ -426,7 +431,7 @@
                 $redirect_code = ($redirect_type == 1 ? '302' : '301');
                 $redirect_header = ($redirect_type == 1 ? 'Found' : 'Moved Permanently');
                 header('HTTP/1.0 '.$redirect_code.' '.$redirect_header);
-                header('Location: http://'.$url);
+                header('Location: '.self::getProto().$url);
                 exit;
             } elseif (defined('_PS_ADMIN_DIR_') && empty($shop->physical_uri)) {
                 $shop_default = new Shop((int)Configuration::get('PS_SHOP_DEFAULT'));
```

**Comment by ZiZuu-store** [comment]
See this report with or without this patch applied https://varvy.com/tools/redirects/

**Comment by ZiZuu-store** [comment]
@jnadaud still pending? :)

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by Eolia** [comment]
Yes it's always an important request, please commit it

**Comment by ZiZuu-store** [comment]
@vTerenti Sorry but no time at the moment for review the patch .. if anybody in the PS team can do the job I'll be grate

**Comment by therampagerado** [comment]
Will this fix be added to 1.6.1.5?!

**Comment by xBorderie** [comment]
Hello @therampagerado, and thank you for your concern.
As it is, the PR cannot be merged because it is on the `1.6` branch, and all the work is now happening on the `1.6.1.x` branch.
I just recreated the PR on the correct branch `1.6.1.x` as best as I could in #4705. Now it's up to the developers to merge it or not.
Best regards.

**Comment by xBorderie** [comment]
I am therefore closing this PR now. Please comment on #4705. And thank you again @ZiZuu-store for your initial PR!

**Comment by therampagerado** [comment]
@xBorderie - great, thanks! Looking forward for feedback on your pull request and I'll manually do it in my distribution because as I see 1.5 will be another 2-3 months in future and it's not sure if they will put it it this release.

Thanks once again!

**Comment by ZiZuu-store** [comment]
So we can close this PR .. Hope to see the new PR merged in short ;)

**Comment by xBorderie** [comment]
The team is deep into making sure the first beta of 1.7 contains everything they want it to be, but I'll make sure the PRs are not forgotten, trust me! :)

**Pull request closed without merging**
