### PR TITLE
[-] BO : Fix product friendly-URL not updated with name

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Bug fix of the friendly URL not updated with the product name. |
| Type? | Bug fix |
| Category? | BO - Product page |
| BC breaks? | Nope |
| Deprecations? | Nope |
| Fixed ticket? | [BOOM-676](http://forge.prestashop.com/browse/BOOM-676) |
| How to test? | Modify the product title, the friendly URL will be automatically updated at the same time. Wow ! |

### CODE REVIEW

**Comment by vTerenti** [comment]
QA NOK

**Comment by kpodemski** [comment]
Remember that if you're going to change the name of the already existing product URL shouldn't be updated, did you check it?

**Comment by Shudrum** [comment]
You're right @kpodemski

**Comment by Shudrum** [comment]
@vincentbz ?

**Comment by vincentbz** [comment]
Hi,

Yeah, it's not mandatory. It only happens when you validate the option "force update of friendly URL":

force friendly url

**Pull request closed without merging**
