### PR TITLE
Added message delivery information on checkout process

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added message delivery information on checkout process
| Type?         | new feature
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2802
| How to test?  | make an order & play with message delivery, update, create & delete it.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by folkertsmit** [comment]
I applied the changes, it does work for me but only with a registered user. When i dont create account (guest) then there is no message in backend added to order

**Comment by aleeks** [comment]
Hello @folkertsmit 
Thank you for your feedback. I will test it asap.
It's possible this doesn't work because customer aren't same as guest..
I see if i can fix it.

Regards

**Comment by aleeks** [comment]
Indeed, it doesn't work with guest.
I put it on WIP and fix it later.

Regards

**Comment by folkertsmit** [comment]
Great thank you!

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by maximebiloe** [comment]
Thank you @folkertsmit for the initial work and @aleeks for the final commits

**Comment by jordiFive** [comment]
Hi @aleeks, ty this post.
I just need just this solution in my shop but i need on the finish step.
How can apply with this method?

Regards.

**Comment by xBorderie** [comment]
@jordiFive If you need this change, you'll have to adapt these changes to your 1.7 install: https://github.com/PrestaShop/PrestaShop/pull/7833/files
...or you could wait for version 1.7.2.0, which should be released in July :)

**Pull request merged**
