### PR TITLE
[*] TR: Swedish, translate country.xml

### PR DESCRIPTION
**Pull request by MacRoy**
Translated to Swedish

### CODE REVIEW

**Comment by AlexEven** [comment]
Hello MacRoy, 

Thanks for this PR!

Do you think you could help us and translate the other countries' names as well? It would make sense if you wish to have all the back end in Swedish. Here you'll only have 'Sweden' in Swedish.

If you do it, please do so on your branch patch-27, it will be added in this pull-request. 

Thanks again,

**Comment by MacRoy** [comment]
Hi Alex!

I have now completed the translation of country.xml. Can you check that my pull request was correct, I had missed the spelling of a country and had to correct this, so I did not get the key for the pull request ago. You can check whether it was so or not?

Best regards
MacRoy


17 nov 2015 kl. 17:15 skrev Alex Even <notifications@github.com>:

**Comment by AlexEven** [comment]
Hello MacRoy, 

Thanks for updating the PR!
Can you tell me which country was misspelled that I should check?

You can see what would finally be merged here: https://github.com/PrestaShop/PrestaShop/pull/4256/files

If you have questions about how to update / manage your pull-request or how to use GitHub, you can join this [chat](https://gitter.im/PrestaShop/GitHub-Git-PullRequest) where we can help you :)

Best regards,

**Comment by MacRoy** [comment]
Hi Alex!

I have now made adjustments in the Swedish translation, and is now complete.

Best regards
MacRoy

**Pull request merged**
