### PR TITLE
Simplified customer preferences

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Simplify customer preferences form
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Part of #16482
| How to test?  | Simplifying Shop Parameters -> Customer settings form. Everything must look the and work the same with following exceptions: 1. blue help box replaced with help text under input. 2. Password reset delay is now required(it was always required but now is shown as such 3. Error message for password reset delay appears next to the input instead of at the top of the page. 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21234)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
lgtm

**Review by atomiix — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

I found only one issue:
In all fields, you have a required option
image
Before, it was ok
image

Thanks to check and feedback.

**Comment by JevgenijVisockij** [comment]
@khouloudbelguith  fixed the issues, but some fields still have the red * next to them as they are actually required.

This is ready for code reviews.

**Comment by JevgenijVisockij** [comment]
Blocked https://github.com/PrestaShop/PrestaShop/pull/21245 as that PR would remove uneeded red * from Yes/No types.

**Comment by JevgenijVisockij** [comment]
> This pull request seems to contain new translation strings. I have summarized them below to ease up review:
> 
>     * `Admin.Notifications.Error`
>       
>       * [ ]  [`The field is invalid.`](https://github.com/PrestaShop/PrestaShop/pull/21234/files#diff-cc92abd6661aff278f401928bb4395b8R81)
> 
> 
> (Note: this is an automated message, but answering it will reach a real human)

Previous message was "The %s field is invalid" with %s being "Password reset delay" I think that message no longer makes sense since now error message is shown next to the field. Should I change message back to how it was or maybe anybody has ideas for a better error message here. 

Input is considerd invalid when it's not numeric or is lower then 0.

**Comment by Julievrz** [comment]
> > This pull request seems to contain new translation strings. I have summarized them below to ease up review:
> > ```
> > * `Admin.Notifications.Error`
> >   
> >   * [ ]  [`The field is invalid.`](https://github.com/PrestaShop/PrestaShop/pull/21234/files#diff-cc92abd6661aff278f401928bb4395b8R81)
> > ```
> > 
> > 
> > (Note: this is an automated message, but answering it will reach a real human)
> 
> Previous message was "The %s field is invalid" with %s being "Password reset delay" I think that message no longer makes sense since now error message is shown next to the field. Should I change message back to how it was or maybe anybody has ideas for a better error message here.
> 
> Input is considerd invalid when it's not numeric or is lower then 0.

Hi @JevgenijVisockij, sorry for the late answer! 
If I understand well, it is the same error than in this PR (https://github.com/PrestaShop/PrestaShop/pull/21243). If yes, why not using the same wording? "The field is invalid. Please enter a positive integer number." in Admin.Notifications.Error

Also, I agree that if the error message is just next to the field, it may not be necessary to specify the name of the field again. Could you show me with a screenshot how it would appear, please?

**Comment by JevgenijVisockij** [comment]
> > > This pull request seems to contain new translation strings. I have summarized them below to ease up review:
> > > ```
> > > * `Admin.Notifications.Error`
> > >   
> > >   * [ ]  [`The field is invalid.`](https://github.com/PrestaShop/PrestaShop/pull/21234/files#diff-cc92abd6661aff278f401928bb4395b8R81)
> > > ```
> > > 
> > > 
> > > (Note: this is an automated message, but answering it will reach a real human)
> > 
> > 
> > Previous message was "The %s field is invalid" with %s being "Password reset delay" I think that message no longer makes sense since now error message is shown next to the field. Should I change message back to how it was or maybe anybody has ideas for a better error message here.
> > Input is considerd invalid when it's not numeric or is lower then 0.
> 
> Hi @JevgenijVisockij, sorry for the late answer!
> If I understand well, it is the same error than in this PR (#21243). If yes, why not using the same wording? "The field is invalid. Please enter a positive integer number." in Admin.Notifications.Error
> 
> Also, I agree that if the error message is just next to the field, it may not be necessary to specify the name of the field again. Could you show me with a screenshot how it would appear, please?

Hey

I think using same wording makes sense.

And here is the screenshot
image

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @JevgenijVisockij,

It is ok :heavy_check_mark: 

THanks!

**Pull request merged**
