### PR TITLE
Fix webservice accessory xlink href

### PR DESCRIPTION
**Pull request by Dakror**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix the wrong accessory xlink href on webservice product responses
| Type?         | bug fix
| Category?     | WS
| BC breaks?    | no
| Deprecations? |o
| How to test?  | Old xlink is 404, new one is correct

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21613)

### CODE REVIEW

**Comment by Progi1984** [comment]
Closed & Reopened for executing a new time all checks.

@Dakror Could you give us a scenario test for checking before/after ?

**Comment by Dakror** [comment]
just look at the webservice output of a product by id. if you go down to the accessories and try to use the given url, you will see that its wrong

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Tested by dev team, QA ok :)

**Comment by Progi1984** [comment]
Thanks @Dakror & @PierreRambaud for the test and @Robin-Fischer-PS for the "QA :heavy_check_mark:"

**Pull request merged**
