### PR TITLE
Fix bug extra space: htaccess directive order

### PR DESCRIPTION
**Pull request by prestarocket**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | errors 500 for img, css and js because of the wrong directive (FO & BO): extra space in directive Order deny,allow
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Install PS with Apache 2.2

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9339)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @PierreRambaud wdyt ?

**Comment by PierreRambaud** [comment]
Yes it's true, `Order` take one argument without spaces.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
No need QA for this one, Can be merge and will be release very soon with the 1.7.4.2

**Comment by prestarocket** [comment]
You should deliver this very soon because it could break a lot of shops
capture d ecran 2018-07-18 a 08 50 28

**Comment by PierreRambaud** [comment]
It will, maybe today or tomorrow. We are planning a new release really fast. 
But for your information APache 2.2 isn't maintained since last year, and have many vulnerabilities, I encourage everyone to move to a recent installation of this software.

**Comment by prestarocket** [comment]
ok thx !

**Comment by MDWeb-Lille** [comment]
Even though Apache 2.2 is no longer maintained, many servers are still running on it. Some of our clients don't want to change their hosting despite a new version of their shop in 1.7.

1.7.4.2 must therefore be released as soon as possible.
Thx @prestarocket !

**Review by prestamodule — APPROVED** [review]

**Comment by Rjain31** [comment]
I changed the directive and removed the space in the files indicated. but the site FO is still showing HTTP 500 error.Any solutions are welcome . Thanks

**Comment by mickaelandrieu** [comment]
@Rjain31 put your shop in development mode and you should see an error trace.

If you get a 500 it's not related to Apache configuration.

**Pull request merged**
