### PR TITLE
[-] BO : Fixed a bug in export URL of toolbar ( stock movements )

### PR DESCRIPTION
**Pull request by tonyyb**
The &amp; in URL of toolbar button prevents the export of .csv

### CODE REVIEW

**Comment by tonyyb** [comment]
What about this bug fix ?

**Comment by xBorderie** [comment]
Hey @tonyyb, thank you for this PR!

Our developers will soon have a look at your proposal. Thank you for your patience!

**Comment by tonyyb** [comment]
Thank you, idem for #4517 !

**Comment by xBorderie** [comment]
Please make sure your code is [PSR-2](http://www.php-fig.org/psr/psr-2/)... and if you find a file that does not respect PSR-2 yet, feel free to make a PR for that :)

**Comment by tonyyb** [comment]
Hey @xBorderie ! My code is PSR-2 in these PR ...

**Pull request closed without merging**
