### PR TITLE
Cherry pick not merged non conflicting changes from 1.6 to 1.7

### PR DESCRIPTION
**Pull request by jocel1**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Cherry pick not merged non conflicting changes from 1.6 to 1.7
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | a lot
| How to test?  | 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Okay, on this one we got an issue when launching the tests on the StarterTheme:

> error: Your local changes to the following files would be overwritten by checkout:

We will have to work on it.
I also restart the tests for PHP 7, which have failed.

**Comment by Quetzacoalt91** [comment]
Actually, this made me discover that the travis script was incorrect.

Once #7896 is merged, it would be great that you rebase your PR on develop. :wink:

**Comment by Quetzacoalt91** [comment]
Now that #7896 is merged, can you please rebase @jocel1 ?

Thanks

**Comment by jocel1** [comment]
Well actually I don't think merging this one directly is the right approach. You'd rather check from which 1.6 PR each changes are coming from, and merge them individually in 1.7 / develop to properly keep track of the merge. (like #7960 which has just been merged from the 1.6 branch, and which is included in this PR has well)

**Comment by aleeks** [comment]
I'm closing this, but we need to keep in mind that there will be a little work to do on these commits.
Thank you @jocel1

**Pull request closed without merging**
