### PR TITLE
Update default catalog 8.1.x

### PR DESCRIPTION
**Pull request by ps-jarvis**
| Questions         | Answers
| ----------------- | ------------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Automatic update of default catalog for 8.1.x
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @ps-jarvis!

This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

**Review by Hlavtox — DISMISSED** [review]
**Blocking, explanation:**

The same situation as with the previous PR happened again - https://github.com/PrestaShop/PrestaShop/pull/35534.

Most of the changes in this PR are just strings that were randomly detected in another file than where they were detected last time. 

If this will be merged, the strings will pop up as untranslated in Crowdin.

Last time, on Slack, the discussion ended with "let's merge this now and let's see if it happens again".

What to do now? Ping @PrestaShop/tech-council @Julievrz

**Comment by jolelievre** [comment]
It's weird that they are considered as new wordings, the initial source wording is the same, the namespace is the same, and even the trans unit ID remains the same (ex: `1063e38cb53d94d386f21227fcd84717`)

The file source should not impact the Crwdin know wordings 🤔

**Comment by jolelievre** [comment]
@Hlavtox are you sure about what you claim? Modifications on the PR side and new string on Crowdin side are two different things, so far every single extraction we didi had this issue to show some wordings as new (green) in the PR, but they are always going with the same deletion (red) in the PR as well The important thing is that the source is the same and the trans unit ID remains the same

AFAIK Crowdin should understand this kind of changes and not consider these as new wordings, I discussed with @Julievrz and she doesn't remember about such issue on crowdin 🤔

**Comment by Hlavtox** [comment]
@jolelievre 

I could be very well wrong, but this is what I think. 🤔

Last time, dozens/hundreds of strings that did not change popped up as untranslated in Crowdin.

I don't know if the reason was translation ID or the source file.

What I don't want to happen is we merge it and the strings will be untranslated again.

Maybe, do you think you could make one manual PR with just one string from this PR? Then do a crowdin push and we will see if it messes up crowdin or not.

**Comment by jolelievre** [comment]
@Hlavtox nope, handling translation workflow is already complicated enough as it is, we worked to automate this as much as possible So no I won't perform a manual extraction of something that is fully automated sorry

I discussed this with Julie, she has no memory of this kind of problem and she prefers to review the changes in Crowdin directly, so we'll merge the PR as is and push to crowdin to see the changes Maybe there won't be any new wordings for that matter

If as you say some wordings have disappeared after this push, then it will truly indicate that the process is flawed, in this case @matks @amine-O I suggest we prioritize a refacto of our wording extraction tool so that we get stable exports (the source file is useless, the wordings should be ordered alphabetically so that they are always returned in the same order)

**Comment by Hlavtox** [comment]
@jolelievre

Well, I remember it quite clearly, there was a long discussion about it on Slack.

But hey, whatever, just push it then. 🤷‍♂️

**Comment by Julievrz** [comment]
Hey, if something is wrong we can roll back on Crowdin. This way we can verify if there is indeed an issue. :)

**Review by matthieu-rolland — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Pull request merged**
