### PR TITLE
Add view shopping carts scenario

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check the cart details in the view shopping cart page.
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | path=full/01_orders/5_shopping_carts_view.js npm run specific-test -- --URL=FrontOfficeUrl

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9093)

### CODE REVIEW

**Review by marionf — DISMISSED** [review]

**Review by mbadrani — DISMISSED** [review]

**Comment by fatmaBouchekoua** [comment]
@mbadrani rebase done

**Comment by PierreRambaud** [comment]
Hi, this PR needs to be rebased.

**Comment by fatmaBouchekoua** [comment]
Done

**Comment by PierreRambaud** [comment]
@fatmaBouchekoua You need to review again :D

**Comment by fatmaBouchekoua** [comment]
@mbadrani review please?

**Review by mbadrani — APPROVED** [review]
approved changes

**Comment by fatmaBouchekoua** [comment]
@PierreRambaud It's ready for merge !

**Comment by PierreRambaud** [comment]
Thanks @fatmaBouchekoua

**Pull request merged**
