### PR TITLE
Scroll top to product list when paginate

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | After clicking the last page with few products in the FO, user have to scroll up to find the products
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3288
| How to test?  | Go to product list in FO scroll down and paginate to the next page, ou will be scrolled top to the list

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi,

Could you move it to 1.7.2.x branch please ? 
And there is still a problem on Firefox, see ticket 

Thanks !

**Comment by marionf** [comment]
Hello @fatmaBouchekoua 

It's not working for me

**Comment by vincentbz** [comment]
Hi,

Thanks for that PR.
The behaviour is not good.

It should be : 
1. I click on the pagination
2. It changes directly to the top of the next page

We don't need animation to go to the top of the page.
It should be to the top of the page, not to the top of the products, like this : 
image

A good example is Amazon. If I change page, i'm on the top of the next/previous page
https://www.amazon.fr/s/ref=sr_pg_3?fst=as%3Aon&rh=n%3A13921051%2Cn%3A13910741%2Cn%3A323625011%2Ck%3Acarte+SD&page=3&keywords=carte+SD&ie=UTF8&qid=1502108563&spIA=B01EDX4C9Y,B01EDX5RFW,B01EDX6562,B0019R31J0,B01BGLKX9E,B01EDX5DTM

Thanks

**Comment by fatmaBouchekoua** [comment]
Hello @vincentbz ,
Since there was no described behavior on the ticket, I chosen to animate scrolling to the top of the product list.
I've changed the behavior as described on this PR. Could you recheck please?

Thanks!

**Review by LittleBigDev — APPROVED** [review]

**Pull request merged**
