### PR TITLE
Replace comma with dot in special price

### PR DESCRIPTION
**Pull request by Casper-O**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | This auto replace comma with dot in special price. In some countries its normal that you use comma as a seperator for decimals and this is currently giving some wrong results.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | No
| Deprecations? | NO
| Fixed ticket? | 
| How to test?  | use comma instead of dot when typing price reduction. Before 2,45 would be saved as 2.00 - after this PR it should save it as 2.45

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hello @Casper-O,

While reviewing your pull-request, I found a function already doing the job: `noComma(<dest>)`

I added it on one of the concerned field, and I think it would suit you as well:
```smarty
<input type="text" disabled="disabled" name="sp_price" id="sp_price" value="{$product->price|string_format:$priceDisplayPrecisionFormat}" onchange="noComma('sp_price');" />
```

**Review by Quetzacoalt91 — CHANGES_REQUESTED** [review]
Review done, comment to be discussed

**Comment by Casper-O** [comment]
The change you suggest seems more clean, i have to say that i just copied how the other price fields works in BO - But for some reason i can not accept your changes? Guess its because i don't have the right permissions

**Comment by Quetzacoalt91** [comment]
Oh, this was actually just an example, nothing to be accepted / rejected.

Your commit must be amended in order to replace the change. :wink:

**Comment by Casper-O** [comment]
Okay, i must have been confused by the e-mail from github regarding this... i Will figure it out in a few hours

**Comment by Casper-O** [comment]
Hi @Quetzacoalt91 

I have made the changes you suggested, and amended my commit. Had to Force it, hope it don't break anything.

**Comment by Casper-O** [comment]
I must have been sleepy when I did the changes, good you found it that missing / - beside of that, Eveything else should be fine. Correct ?

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Hello,

Indeed, I added a commit by myself to add a missing slash at the end of the DOM.
About your message of yesterday, this is totally normal to force push when you amend a commit. When you rewrite the git history, you cannot push without `--force`.

On my side, everything is now ready to be merged. This should be done just before a new 1.6 release.

Best regards

**Comment by maximebiloe** [comment]
Thank you @Casper-O & @Quetzacoalt91

**Pull request merged**
