### PR TITLE
Property Address->id_country is empty

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When trying to delete old address called from CustomerAddressPersister.php:73 "return $address->save() && $old_address->delete();" Fatal error is thrown about id_country being empty. This is because old address does not exists and at the same time prestashop tries to validate it and update it and then throws error. At this case if ID is empty means records is not present on database and shouldnt be updated nor deleted. And there is a another bug that isUsed() returns true on non persisted address record. But in any way if ID is empty no further actions should be performed.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Maybe #9812
| How to test?  | N/A

Repost of https://github.com/PrestaShop/PrestaShop/pull/9266

Credit to @vytsci

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10373)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Why do travis fail?

**Comment by PierreRambaud** [comment]
@Mreker failed due to lint problem:
https://travis-ci.org/PrestaShop/PrestaShop/jobs/427126416#L932

**Comment by MathiasReker** [comment]
How do I fix that?

**Comment by PierreRambaud** [comment]
@Mreker You can run php-cs-fixer `./vendor/bin/php-cs-fixer fix`, or if you want, you can install the git pre-commit hook with the following command: `composer run git-hook-install`

**Comment by MathiasReker** [comment]
Thanks

**Comment by khouloudbelguith** [comment]
Hi,

Fixes #9812

**Comment by mickaelandrieu** [comment]
Hello @Mreker,

while I appreciate a lot your efforts to fix this bug, I don't think this is the right fix to do.

As you said, the issue is with `$address->isUsed()` which does not behave as expected: looking at the original thread on [stackoverflow](https://stackoverflow.com/a/46894596/1986681) I'm more in favor of his changes: wdyt?

Also, I can't reproduce the issue: can you help me to reproduce it?

Mickaël

**Comment by MathiasReker** [comment]
Yes, this makes sense. I updated this PR.

**Comment by MathiasReker** [comment]
I can't reproduce it. @vytsci can. This PR was a repost of #9266 because some information was missing.

**Comment by MathiasReker** [comment]
Should I close this, or is it relevant? This was original a repost of #9266.

**Comment by MathiasReker** [comment]
@mickaelandrieu please update status :-)


> 
> 
> Hi,
> 
> Fixes #9812

@khouloudbelguith wdyt?

I can't reproduce the issue on 1.7.5.x

**Comment by khouloudbelguith** [comment]
Hi @MathiasReker,

I manage to reproduce the issue with 1.7.5.0beta1 / the branch 1.7.5.x.
In the checkout process, after creating a new customer, in the address step, if you click "continue" button => an exception displayed.
Thanks!

**Comment by MathiasReker** [comment]
@khouloudbelguith  do the PR solve the issue?

**Comment by khouloudbelguith** [comment]
@MathiasReker, our QA team should verify your PR.
Thanks!

**Comment by MathiasReker** [comment]
I am not able to say if this PR solves the issue, if you think it does, can you change status to waiting for QA?

**Comment by MathiasReker** [comment]
@khouloudbelguith did you manage to solve the issue with this PR?

**Comment by khouloudbelguith** [comment]
@MathiasReker, sorry for the delay.
Your PR need to be reviewed by our dev first then tested by our QA team.
Thanks for your understanding!

**Comment by MathiasReker** [comment]
Should I close this PR?

**Comment by PierreRambaud** [comment]
ping @mickaelandrieu

**Pull request closed without merging**
