### PR TITLE
Product with customizations error import

### LINKED ISSUE #21682: BO - Import page - Product with customizations are not well imported - The customization is not displayed in the product's option Tab
#### Describe the bug

When you try import products with customizations deleting current products first a duplicate error type is throw and import doesn't work well.

#### Expected behavior

Import products with customizations work well.

>Edited by Khouloud

_The import is done successfully, but in the BO > Catalog > Products > Product details page > Options Tab > There is no customization added._

**Steps to reproduce the issue:**
1. You have previously some products
2. Go to BO > Advanced Parameters > Import page
3. Select Products
4. Choose a file
[products_import.csv.zip](https://github.com/PrestaShop/PrestaShop/files/5523554/products_import.csv.zip)
5. Enable "Delete all products before import" 
6. Click the Next Step button
7. The import is done successfully
8. Go to BO > Catalog > Products > Product details page > Options Tab > There is no customization added => **nok**.

PS1768: https://drive.google.com/file/d/1EMQCOrFyKCN9ojfrZPizvVEfPPHdJpPq/view?usp=sharing
PS1770rc1build4: https://drive.google.com/file/d/1pLWDUknUwUU1xqu0U1vi-TxG-rTiSNI_/view?usp=sharing
9. If I check the Database => ok
image

----------------------------------------------------------------------------------

#### Steps to Reproduce

1. Go to BackOffice > Advanced Parameters > Import.
2. Select entity product.
3. Upload a valid .csv with your products and customizations.
4. Select delete current products before import.
5. Import.

#### Additional information

* PrestaShop version: 1.7.6.7

### PR DESCRIPTION
**Pull request by dawalberto**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When you try import products with customizations deleting current products first a duplicate error type is throw and import doesn't work well.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #21682
| How to test?  | Try import products with customizations deleting current products first.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21681)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Hello @dawalberto,

Please take care of the PR's template, it should be full filled.

Also, you need to create an issue, so we can try to reproduce the bug before validating any changes.

**Comment by SimonGrn** [comment]
Hello all,

as usual we need to validate the [linked issue](https://github.com/PrestaShop/PrestaShop/issues/21682) before this PR can be merged.

Thank you !

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SimonGrn** [comment]
Hello,

we have a problem with this PR: it fixes a non-existent problem. The linked issue was created because the author didn't use the proper way to import products with combinations as you can see [here](https://github.com/PrestaShop/PrestaShop/issues/21682#issuecomment-719545667).
We shouldn't accept this PR.

**Comment by PululuK** [comment]
> Hello,
> 
> we have a problem with this PR: it fixes a non-existent problem. The linked issue was created because the author didn't use the proper way to import products with combinations as you can see [here](https://github.com/PrestaShop/PrestaShop/issues/21682#issuecomment-719545667).
> We shouldn't accept this PR.

Hi @SimonGrn 
No, it is correct! You talk about combinations while he talks about customizations.

ping @hibatallahAouadni can you re-open the issue please?

**Comment by SimonGrn** [comment]
Oh my bad, we reopen it.

**Comment by SD1982** [comment]
Hi @dawalberto I have reproduced all the steps described in #21682 and It seems that the issue is not fixed by your PR ( confirmed also by @khouloudbelguith )
Can you check this please ?

**Comment by matks** [comment]
Hi @dawalberto as we got no answer in 30 days we close the PR [following our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) but if you come back we'll be happy to reopen it 😉  have a nice day

**Comment by dawalberto** [comment]
> Hi @dawalberto as we got no answer in 30 days we close the PR [following our rules](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) but if you come back we'll be happy to reopen it 😉 have a nice day

Sorry for not taking care of this! I hope I can later. I do not have time now

**Comment by matks** [comment]
No worries 😄  we'll be waiting

**Pull request closed without merging**
