### PR TITLE
Installation test

### PR DESCRIPTION
**Pull request by ansar21mallouli**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Installation when language is equal or different to the country.
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | TEST_PATH=broken_tests/installation/installation.js npm run specific-test -- --URL=FrontOfficeURL --LANGUAGE=Language --COUNTRY=Country --CURRENCY=Currency --DB_SERVER=DbServer --DB_PASSWD=DbPassword --DB_USER=DbUser

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12206)

### CODE REVIEW

**Review by mbadrani — APPROVED** [review]
Fine for me

**Comment by mbadrani** [comment]
Related Bug https://github.com/PrestaShop/PrestaShop/issues/10744, we should integrate this test once the related issue is fixed

**Comment by mbadrani** [comment]
thanks @ansar21mallouli

**Comment by mbadrani** [comment]
related issue: https://github.com/PrestaShop/PrestaShop/issues/10744

**Comment by marionf** [comment]
Existing issue found by this test: #12168

**Pull request merged**
