### PR TITLE
Added PS_MAINTENANCE_TEXT key in database

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions | Answers |
| --- | --- |
| Branch? | debug (develop) |
| Description? | A configuration key was missing in installation, causing maintenance text to not be translatable |
| Type? | bug fix |
| Category? | IN |
| BC breaks? | Does it break backward compatibility? yes/no |
| How to test? | ShopParameters > General > Maintenance => play with differents languages. <br> **You MUST install again your shop** |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
@mickaelandrieu Do you plan to add this commit to the develop branch as well ?

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 as soon as this pull request will be merged ;)

**Comment by maximebiloe** [comment]
You can now 😉

**Comment by mickaelandrieu** [comment]
https://github.com/PrestaShop/PrestaShop/pull/6769 yes sir !

**Pull request merged**
