### PR TITLE
Fixed html tags that appear in carrier wizard

### PR DESCRIPTION
**Pull request by antho-girard**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This PR fixes html tags that appear in "summary" carrier wizard |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1620 |
| How to test? | Edit an existing carrier and go to last step "Summary" |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by antho-girard** [comment]
Hi,

I think this concerns 1.6.1.x too.

**Comment by kpodemski** [comment]
This was already rejected by Remi because of xss

**Comment by Quetzacoalt91** [comment]
Yep, see #5704 for more details.

**Comment by antho-girard** [comment]
Ok, thanks

**Comment by aleeks** [comment]
Yes, we are waiting for this change..
See : 
https://github.com/PrestaShop/PrestaShop/pull/6625
https://github.com/PrestaShop/PrestaShop/pull/5704

**Pull request closed without merging**
