### PR TITLE
Fix notification refresh on migrated pages

### LINKED ISSUE #23573: New message/order/customer notification bubble not updated live
### Describe the bug
New message/order/customer notification bubble is not updated live, without refreshing the browser.

### Expected behavior
I expected a notification bubble number on either a new message/customer/order without refreshing the browser like in 1.7.6 and previous years versions.

### Steps to Reproduce
Open frontpage of BO, and notice the notification bubbles does not update the numbers as you get new orders/messages.

-------

On a brand new test install it seemed to work fine. I sent 4-5 messages, and the bubble updated fine every time, but after I installed new language (danish) the bubble stopped to work.
notify

### Additional information

- PrestaShop version: 1.7.7.1
- PHP version: 7.3

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Notifications refresh was not working on migrated page
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23573.
| How to test?      | Go on migrated page (order for example), create an order on FO, wait for the notification badge to show (it take up to 2 mins)
| Possible impacts? | Auto notification displaying in the BO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23691)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Well, to summarise all my tests, I will put all the results in the table below:

| Action         | without PR - Legacy         | without PR - Symfony         | with PR - Legacy         | with PR - Symfony         
| ----------------- | ----------------- | ----------------- | ----------------- | -----------------
| Create an account | :heavy_check_mark:          | :negative_squared_cross_mark:          | :negative_squared_cross_mark:          | :heavy_check_mark:         
| Create an Order | :heavy_check_mark:          | :negative_squared_cross_mark:          | :negative_squared_cross_mark:          | :heavy_check_mark:         
| Send a message | :heavy_check_mark:          | :negative_squared_cross_mark:          | :negative_squared_cross_mark:          | :heavy_check_mark:         

Thanks!

**Comment by NeOMakinG** [comment]
Hey @hibatallahAouadni 

I just tested the PR :

Migrated : 

image

Legacy :

image

Both got the request inside the network tab, and both get new notifications in the header, I still pushed assets so you don't have to build these

**Review by Progi1984 — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

Thanks! It works :tada: 
Check the attached screen record below:

https://drive.google.com/file/d/1AuwO4v0tA7PXa_RJv5FD9P566saSZzOg/view

| Action         | without PR - Legacy         | without PR - Migrated         | with PR - Legacy         | with PR - Migrated         
| ----------------- | ----------------- | ----------------- | ----------------- | -----------------
| Create an account | :heavy_check_mark:          | :negative_squared_cross_mark:          | :heavy_check_mark:          | :heavy_check_mark:         
| Create an Order | :heavy_check_mark:          | :negative_squared_cross_mark:          | :heavy_check_mark:          | :heavy_check_mark:         
| Send a message | :heavy_check_mark:          | :negative_squared_cross_mark:          | :heavy_check_mark:          | :heavy_check_mark:      

Thanks!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
## Need RELEASE 1773

**Review by PierreRambaud — DISMISSED** [review]
Do not merge until 1.7.7.3 release

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Pull request merged**
