### PR TITLE
Allow administrators to add the keyword "categories" in SEO & URLS (product link)

### PR DESCRIPTION
**Pull request by andrewice77**
| Questions | Answers
| ------------ | -------------
| Branch | 1.7.5.x
| Description | Change function for display correctly all categories and subcategories in URL. This allow the administrator to add the keyword 'categories' in the SEO & URLs and then display all categories and subcategories in URL.
| Type | improvement
| Category | BO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12356)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello,

thanks for your contribution @andrewice77!

What do you think @colinegin?

Also, this pull request should be done in develop branch, but before asking you any effort I'd like to have an approval from Product team :)

Mickaël

**Comment by andrewice77** [comment]
Hello @mickaelandrieu,
thanks for the reply :)
I hope this change is good, I just want to help and contribute! 

Andrew

**Comment by marionf** [comment]
Hello @andrewice77 

What do you want to do exactly ? 
We can already edit the route to the product to have all categories in URL, like this:

capture d ecran_978

Can you give us more details ?

Thank you :)

**Comment by andrewice77** [comment]
Hi @marionf!
Yes, with this function: "getParentCategories" we get only to the second subcategory on URL. 
Instead with this other function (getProductCategoriesFull), we get all category of product on URL. 
Try also inserting a third subcategory to a product and in the route of product will not be visible.
prestashop



Thank You! ;)

**Comment by marionf** [comment]
@andrewice77 

The problem with your PR is the following:
If I have a product in several categories, they will all be displayed in the URL

capture d ecran_1071

capture d ecran_1072

If you want all parents categories displayed in the URL, you should select the last categories as main:

capture d ecran_1075

capture d ecran_1077

**Comment by andrewice77** [comment]
Thank you and sorry @marionf!

**Pull request closed without merging**
