### PR TITLE
Build core theme using Webpack 4 and jQuery 2.2.4

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This upgrades webpack in the core theme to v4 (up from v1!) and jQuery from v2.1.4 to v2.2.4
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | The FO should continue to work as before

This PR also compresses the built file `core.js`, reducing the file size by over 50%: 269K before --> 113K now.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9467)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by MathiasReker** [comment]
@eternoendless can you update htmlpurifier too? :-) Link: http://htmlpurifier.org/

**Comment by MathiasReker** [comment]
HTML Purifier 4.10.0 is a maintenance release, collecting a year of accumulated bug fixes. The most critical fixes relate to supporting PHP 7.2 properly, and there are a few other minor fixes. One thing on the feature front: relative CSS length specifiers are now supported. Additionally, we have officially dropped support for PHP 5.3; while we have not purposely broken HTML Purifier for this version, we are no longer testing for it.

**Comment by mickaelandrieu** [comment]
@Mreker would you mind to contribution a pull request for it?

I'm in favor of this update too, just looking for you to help us a little bit :+1:

**Comment by mickaelandrieu** [comment]
Well played @eternoendless and thanks for QA review

**Comment by mortenhartvig** [comment]
Thanks for finally compressing the core.js file. Now Google Pagespeed insights may finally stop nagging about it (UX designers/theme developers should really focus on this, as it directly affects how successful Prestashop is considered vs. other software) 👍

**Comment by MathiasReker** [comment]
@mickaelandrieu here you go https://github.com/PrestaShop/PrestaShop/pull/10376 😃

**Pull request merged**
