### PR TITLE
BO: Fix some of the functions on the product page (JS)

### PR DESCRIPTION
**Pull request by M03G**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If Prestashop is installed in a subdirectory whose name starts with a number, the JS will incorrectly modify the links that occur requests for data processing. Thus, you can not delete the file in the virtual product can not attach a file to the product, can not see the list of product combinations, can not change the type of product (with the removal of all combinations), can not add a feature to the product (at is possible to obtain a list of values).
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1788
| How to test?  | The problem is the regular expression used. If prestashop installed on www.site.com/17prestashop/ address (for example), www.site.com/17prestashop/feature/get-feature-values/1 requests for the product with the number 8, will be converted to www.site.com/8prestashop/feature/get-feature-values/1, instead of www.site.com/17prestashop/feature/get-feature-values/8 . Therefore it is necessary to change the regular expression (I added a question mark in it, as a token to be necessarily). <br> with old regex - https://regex101.com/r/5Nxxyx/1 <br> with new regex https://regex101.com/r/5Nxxyx/2

### CODE REVIEW

**Comment by M03G** [comment]
This is particularly interesting against the background of this research - https://domains-index.com/nine-millions-domain-names-just-numbers/ :)

**Comment by M03G** [comment]
The problem also exists in the domain, starting with a digit. And for subdomains.

**Review by PrestaEdit — APPROVED** [review]
Tested there and it"s now working :)

**Comment by PrestaEdit** [comment]
Please, @aleeks ... Don't forgot this one (or the other), 1.7.0.2 not working (without this !) :)

**Comment by aleeks** [comment]
Hello @PrestaEdit, it will be in 1.7.0.3.. :pensive:

**Comment by maximebiloe** [comment]
Thank you @M03G.

We close this one but it has been cherry-picked on `1.7.0.x` here: #7091 and will be integrated in `develop` when we'll merge `1.7.0.x` into `develop`.

Regards

**Pull request closed without merging**
