### PR TITLE
[*] BO : add two image generation methods, crop and adjust #PSCSX-4894

### PR DESCRIPTION
**Pull request by violy**
Add two image generation methods, **crop** and **adjust**.
See Issue I've create [#PSCSX-4894](http://forge.prestashop.com/browse/PSCSX-4894)

I add two new values the configuration option `PS_IMAGE_GENERATION_METHOD` : 
- Crop (id 3)
- Adjust (id 4)

Both methods will adapt your source ratio to your destination ratio, the **Crop** method may crop your source, the **Adjust** method may show some stripes.

Maybe the BO `PS_IMAGE_GENERATION_METHOD` field title should be more exhaustive. _I've not edit this part._

This is my first PR. Thanks.

### CODE REVIEW

**Comment by violy** [comment]
I don't understand why there is 168 commits…

**Comment by jeromenadaud** [comment]
Hi, you can try to first set your upstream like : https://help.github.com/articles/configuring-a-remote-for-a-fork/ and after sync your fork like : https://help.github.com/articles/syncing-a-fork/

Best regards.

**Comment by violy** [comment]
Thank you, 
I've make a new commit, with those new instructions,
and publish my new Pull Request.

**Comment by jeromenadaud** [comment]
Ok, Thank you

**Pull request closed without merging**
