### PR TITLE
Delete migrated AdminRequestSqlController again

### PR DESCRIPTION
**Pull request by matks**
Return of PR https://github.com/PrestaShop/PrestaShop/pull/13852

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove AdminRequestSqlController again
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Last step of https://github.com/PrestaShop/PrestaShop/issues/10495 (we forgot to do it)
| How to test?  |Please check nothing related to Database Manager a.k.a SQL Manager page is broken

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14870)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Waiting for a ticket, and CI tests :)

**Comment by matks** [comment]
Closing and reopening for Travis

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
image

:thinking:

**Comment by Progi1984** [comment]
> image
> 
> thinking

The same here !

**Comment by matks** [comment]
This PR seems corrupted, so I'll re-create a new one https://github.com/PrestaShop/PrestaShop/pull/17187

**Pull request closed without merging**
