### PR TITLE
Fix carrier depth, height and width limits

### LINKED ISSUE #22877: Carrier limit do not work
#### Describe the bug

When using the depth, height and width limits on the carriers they do not work as expected.
If any value is "ok" the carrier will show up.

#### Expected behavior

If one of the values is exceeding the carrier limit, the carrier should not show up in the checkout.

#### Steps to Reproduce

1. Go to product, set values height, depth and width to 1, 1 and 5 and save
2. Go to carriers, activate the light carrier.
3. In front office, add product to the cart and go to checkout all the way to the carrier step.
4. Light carrier should show up.
5. Go back to editing the light carrier in BO, set height, depth and width max values to 20, 20 and 2 and save.
6. Reload the checkout, light carrier still shows up, even if the product in the cart is exceeding the maximum width of the carrier.

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixing issue 22877 and making the code a bit more easy to read.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #22877
| How to test?      | See ticket for details
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22884)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
Thank you @Prestaworks for your contribution 👍 

Your PR seems fine, but cs fixer is not happy, you can fix this easily with this command, from the root of your project:

`./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix classes/Carrier.php`

**Comment by Prestaworks** [comment]
Let see if this last commit works, all the line endings got screwed up due to no gitattributes file, so I lets se if it corrects itself now.

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Prestaworks,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1TtRx7IlENiybgbooZBEzv7XHGRwvkppb/view?usp=sharing

Thank you!

**Comment by atomiix** [comment]
Thanks @Prestaworks & @khouloudbelguith

**Pull request merged**
