### PR TITLE
Add actionPresentPaymentOptions hook

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add the actionPresentPaymentOptions like other presenter (Cart, Product, Order, ...).
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | You can have a module hooked on actionPresentPaymentOptions and see that params having the $paymentOptions array in it.
| Possible impacts? | Nothing, it will just add possibility to unset some payments methods by a module.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26259)

### CODE REVIEW

**Comment by PrestaEdit** [comment]
And with the autoupgrade PR too: https://github.com/PrestaShop/autoupgrade/pull/426

**Comment by tegbessou** [comment]
Thanks for the PR! LGTM

**Review by matks — COMMENTED** [review]
I have a question.

`PaymentOptionsFinder::find()` already gathers payment options by exploring 3 hooks.

So what is the exact usecase this hook `actionPresentPaymentOptions` aims to solve? I think it has one clear advantage: it allows to modify the format of payment options (add some extra data), but maybe I did not see the whole picture.

As hook `actionPresentPaymentOptions` is called after the payment options have been found and formatted, should we modify the name to make it clear? Like `actionAfterPresentPaymentOptions` ?

**Review by kpodemski — APPROVED** [review]

**Comment by PrestaEdit** [comment]
Hi @matks ,

The hook name is based on the others Presenter, as Cart/Product/Order/OrderReturn.

About the need of this, it's to let a third party module remove a payment option related to some inner code.
Theses three hooks will just allow you to get the modules that are hooked on. But you don't let others modules filter them.

Maybe we need to add a "filterPaymentOptions" hook inside the finder itself.

**Comment by PrestaEdit** [comment]
And/or keep it and add the filter, in the find() method. Wdyt ?

**Comment by kpodemski** [comment]
@PrestaEdit 

We could have the same discussion with different presenters, I'm afraid, hook at the end is more flexible and I can think of more use cases for it.

**Review by matks — APPROVED** [review]
IMO the hook `actionPresentPaymentOptions` here seems to do the job. It can filter, reformat, and even be used as an 'event' triggered whenever payment options are fetched to call something else.

I would like to see a name a little more accurate, so people understand what it does, but if the name has been chosen because other presenters follow a naming convention, then current name is better.

So it's an approval from me 👍

**Comment by matks** [comment]
@PrestaShop/qa-team should this be tested by a developer?

**Comment by khouloudbelguith** [comment]
Hi @PrestaEdit,

It is ok :heavy_check_mark: 
1. I checked the table `PREFIX_hook` 
image
2. I added a module ps_qualityassurance to check this hook
**BO** 
image
**FO** 
image
3. I checked the page BO > Design > Position 
image
4. I added some payment modules and create some orders from FO & BO
image
5. I installed the ps_emailalert module => mail well received after creating a new order

Thanks!

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PrestaEdit

**Pull request merged**
