### PR TITLE
Fix the phone number validator

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When creating a new address, we can save it into the DB even the phone number is just a whitespace.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8348
| How to test?  | BO > Customers > Addresses > Set required fields for this section > make the phone required, FO > Sign in > My addresses > Add a new address > fill the phone number with whitespace and "Save", check if the error message is displayed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8446)

### CODE REVIEW

**Comment by cdoublev** [comment]
I can still save a whitespace as a phone number with this fix. I propose this:

```php
1 === preg_match('/^[+0-9. ()-]*$/', trim(' ') // true
0 === preg_match('/^[+0-9. ()-]+$/', trim(' ') // true
```

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[classes/Validate.php, line 537 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8446#-KyL9-4Qt47gncsETl00:-KyL9-4R8AuMipWO-6l-:b6f8pqn) ([raw file](https://github.com/prestashop/prestashop/blob/1d4bf5da81dab55bfe07e5a2241e7ead56b14025/classes/Validate.php#L537)):*
> ```PHP
>     public static function isPhoneNumber($number)
>     {
>         return preg_match('/^[+0-9. ()-]*$/', trim($number));
> ```

I suggest removing all the (allowed) non-numeric characters, and then validating that resulting string is non empty, and has only digits left.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8446)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Please see comment above

**Comment by cdoublev** [comment]
@LittleBigDev, are you suggesting to remove non-numeric characters in the final version to be saved in database? `I'm not a phone number 123-456-789` is not a phone number, but it contains a phone number. I don't want a string containing a phone number to be validated as being a phone number. 

Aside: the regexp may be improved with a min/max digits number, as it's explained in this [O'Reilly book excerpt](https://www.safaribooksonline.com/library/view/regular-expressions-cookbook/9781449327453/ch04s03.html) mentioning ITU E164 recommandation.

**Comment by LittleBigDev** [comment]
I'm talking about validation. Not filtering. So no, I'm not suggesting to remove non-numeric characters in the final version. I'm suggesting to remove *allowed* non-numeric characters from the string (using a temp string) and check if result has only digits. Obviously, your example would not be valid, because the result would be something like `I'mnotaphonenumber123456789`

Thanks for mentioning ITU E164 ! I agree with you, regexp should be improved with the 7-15 min/max.

**Comment by Azouz-Jribi** [comment]
Hi @LittleBigDev 
Can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[classes/Validate.php, line 537 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8446#-Kyog9Gwn7fhIpWnniPB:-Kyog9Gwn7fhIpWnniPC:bobz32v) ([raw file](https://github.com/prestashop/prestashop/blob/7f231f01552bf144bc834fd53482143049d91fa7/classes/Validate.php#L537)):*
> ```PHP
>     public static function isPhoneNumber($number)
>     {
>         if (!preg_match('/^[+0-9. ()-]*$/', $number)) {
> ```

This test is useless. The final preg_match does the job.

---

*[classes/Validate.php, line 541 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8446#-KyogKGPMp16pc8ylBfc:-KyogKGQ8yD6PUzZcU1c:bnz2qi0) ([raw file](https://github.com/prestashop/prestashop/blob/7f231f01552bf144bc834fd53482143049d91fa7/classes/Validate.php#L541)):*
> ```PHP
>         }
> 
>         $phoneNumber = preg_replace("/[^!0-9]/", "", $number);
> ```

This mask should match the list of allowed characters only (" ", "+", "(", ")", etc.). After the replacement, only digits should be left. If non digits characters remain, it means the original phone number was invalid.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8446)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
See my comments above

**Comment by Azouz-Jribi** [comment]
Hi @LittleBigDev
Correction is done.

Thanks ;)

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8446#-:-KyvFE9Bsbr5MG3d2ix0:bnfp4nl)*

**Comment by LittleBigDev** [comment]
LGTM, but waiting for Travis approval.
Good job @Azouz-Jribi :)

**Review by LittleBigDev — DISMISSED** [review]

**Review by Quetzacoalt91 — CHANGES_REQUESTED** [review]
With this kind of change and seeing the discussion you got here, adding tests is mandatory.

Please add some examples properly tested in [tests/Unit/classes/ValidateCoreTest.php](https://github.com/PrestaShop/PrestaShop/blob/b3893d83333925429e3e8c3a9ee92dcb03d49588/tests/Unit/classes/ValidateCoreTest.php).

**Comment by LittleBigDev** [comment]
Reviewed 1 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/Unit/classes/ValidateCoreTest.php, line 255 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8446#-L2V3u-UjLczTFMEz9IY:-L2V3u-VVSXdOZ0Jajup:bcjmccq) ([raw file](https://github.com/prestashop/prestashop/blob/ddcc62c4c055c5212a20ea3ecfd7e8b2e21db69a/tests/Unit/classes/ValidateCoreTest.php#L255)):*
> ```PHP
>             array(false, null),
>         );
>     }
> ```

Please use indexes in the data array, to name the data sets. If a test fails in Travis, we will know exactly which one failed. This index is directly displayed in the phpunit report when it fails :
```php
return array(
    'Country Foo, version 1' => array(true, '+1 900 253 0000'),
    'Country Foo, version 2' => array(true, '+1-900-253-0000'),
    'Country Bar, version 1' => array(true, '+49 291 12345678'),
    'Country Bar, version 2' => array(true, '(+49) 291-12345678'),
    // [...]
);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8446)*

**Comment by LittleBigDev** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8446)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
See my comment above

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
Correction is done, can you check it ?

Thanks ;)

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
