### PR TITLE
Fix the display of placeholder in combinations tab

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | When choosing combinations the placeholder moves in the following line. - Fix typeahead width & fix font for maxlength hint on product page - Issue with placeholder display on product page
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3334 http://forge.prestashop.com/browse/BOOM-3335 http://forge.prestashop.com/browse/BOOM-2105
| How to test?  | Go to BO > Catalog > Products > create or edit a product, select the Combinations tab, choose some combinations and check if the placeholder has an enough space and remains in the same row.

Added this PR https://github.com/PrestaShop/PrestaShop/pull/8112

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @Azouz-Jribi 
Thanks, I just add an outline none and compile asset separately.

**Comment by aleeks** [comment]
Juste added some commit related. @maximebiloe

**Comment by aleeks** [comment]
Thank you @Azouz-Jribi @maximebiloe

**Comment by Azouz-Jribi** [comment]
@aleeks 
you are welcome

**Pull request merged**
