### PR TITLE
Brakes when you add a lot of zones

### PR DESCRIPTION
**Pull request by fest73**
You add a lot of zones, you try to add a range in the carrier and write a value there

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Brakes when you add a lot of zones
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | You add a lot of zones, you try to add a range in the carrier and write a value there

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8988)

### CODE REVIEW

**Comment by fest73** [comment]
@Quetzacoalt91  please check my pull request

**Comment by PierreRambaud** [comment]
@Quetzacoalt91 little up ? Don't know this part of code :/

**Comment by Quetzacoalt91** [comment]
Yeah, I haven't finished the check on that PR, but I want to confirm there is no misunderstanding between ranges & zones.

**Comment by Quetzacoalt91** [comment]
Hi there, a quick update on my review.

So far I don't see any performance improvement with 1500 zones, however there are some regressions, like the first line which can't be modified anymore when the checkbox in unchecked.

`develop`:
capture du 2018-05-29 16-35-07

This PR:
capture du 2018-05-29 16-35-16


There is another fix to look for, but I cannot accept yours unfortunately.

**Comment by PierreRambaud** [comment]
@dariusakafest any news? :smile_cat:

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Waiting for author

**Comment by matks** [comment]
Hi, [following our review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

Since we did not get answer from author I close this PR.

Please note this does not mean it's a final "won't merge" 😉 if you come back we can reopen it

Thank you for the contribution

**Pull request closed without merging**
