### PR TITLE
[-] BO : Fix use of custom class with textarea (even if autoload_rte …

### PR DESCRIPTION
**Pull request by PrestaEdit**
…not set)

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, thank you for your contribution,  can you please rebase your PR ?

Best regards,

**Comment by PrestaEdit** [comment]
Hi,

Wich branch ? :)

**Comment by jeromenadaud** [comment]
1.6.1.x

**Comment by PrestaEdit** [comment]
PrestaEdit  wants to merge 1 commit into PrestaShop:1.6.1.x from PrestaEdit:patch-139

:confused:

**Comment by jeromenadaud** [comment]
Very hard to rebase on a 1.6.1.x updated from our side, may be more simple from your side.

**Comment by PrestaEdit** [comment]
https://github.com/PrestaShop/PrestaShop/pull/3520

**Pull request closed without merging**
