### PR TITLE
Notifications bell icon read fix

### LINKED ISSUE #20169: The new order and/or new customer alert under the bell sign wont close
#### Describe the bug

When a customer has made an order or there is a new customer registration, the notifications on top right of the screen keeps displaying even when you already clicked it.

#### Expected behavior

When opening the notifications bell, then when you close it, the notifications normally goes away.

#### Steps to Reproduce

Make an fictive order, then you see the new order notification als normal.

#### Additional information

* PrestaShop version: 1.7.7.0beta
* PHP version: 7.2.31

### PR DESCRIPTION
**Pull request by rajat315315**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The notification icon showed unread notifications even when admin read them.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? | Fixes #20169 .
| How to test?  | See fixed ticket

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20188)

### CODE REVIEW

**Review by matks — APPROVED** [review]
Code looks good 👍  I approve

Thanks !

**Comment by matks** [comment]
To be backported to 1.7.7.x after merge

**Review by qualityangel — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20188)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by qualityangel — COMMENTED** [review]
Works like a charm, approved

> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20188#-:-MCLz5UFDwjJdQorckFX:bm888xp)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by qualityangel — APPROVED** [review]
Works fine in 1.7.7.0

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @rajat315315,

When the bell shows 3 messages. 
If I just click on the Messages link and reload the page all messages are removed **despite they are not read**.
image

**With PR**
https://drive.google.com/file/d/12QVe6LBpNUGj6GZ-BLAOA2DpDD66Isbq/view?usp=sharing

Ping @PrestaShop/prestashop-product-team what do you think of this fix?

Thanks!

**Comment by rajat315315** [comment]
Hi @khouloudbelguith ,
Is this not the expected behaviour?
Does it not used to behave like this in all past versions?

**Comment by qualityangel** [comment]
> Hi @khouloudbelguith ,
> Is this not the expected behaviour?
> Does it not used to behave like this in all past versions?

Yes it does. This is so far i know from version 1.6, This is normal behaviour.

**Comment by khouloudbelguith** [comment]
Hi @rajat315315,

>Is this not the expected behaviour?
Does it not used to behave like this in all past versions?

Yes, this is the behavior used in the last PrestaShop versions.
But this is an incorrect as reported here: https://github.com/PrestaShop/PrestaShop/issues/9550
I need confirmation from the Product team to accept the last behavior.

Thanks!

**Comment by rajat315315** [comment]
Updates??

**Comment by khouloudbelguith** [comment]
Hi! 

@PrestaShop/prestashop-product-team friendly reminder :slightly_smiling_face: 

Thanks!

**Comment by LouiseBonnard** [comment]
Hi @khouloudbelguith, thank you very much for the reminder. :-)

If https://github.com/PrestaShop/PrestaShop/issues/9550 can be fixed in the meantime, let's optimize both behaviors! If it is too risky, then let's focus on this part so that it can be backported to 1.7.7.x once merged.

**Comment by khouloudbelguith** [comment]
Hi @rajat315315,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1ep8oGmuZMPtVg1AWhfm8RYPCoXSjSRoK/view?usp=sharing


PS: https://github.com/PrestaShop/PrestaShop/issues/9550 not fixed yet.

Thanks!

**Comment by PierreRambaud** [comment]
Thanks @rajat315315

**Comment by ghost** [comment]
Hi,

I think you forgot to backport this PR.

I can open a new one in 1.7.7.x ? Or it's with a GIT command

**Comment by Progi1984** [comment]
@okom3pom Go for a new one in 177x. Thanks :)

**Comment by rajat315315** [comment]
Hello everyone,
I request you to please nominate me, if you think I have done some meaningful contribution to the community...
https://stars.github.com/nominate/

**Pull request merged**
