### PR TITLE
Do not check for formats that are enabled when deleting images

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | There is no need to instantiate anything when deleting images, we can just delete all existing supported  formats. Also, a merchant could have disabled one format and it would not be deleted. Extrated from https://github.com/PrestaShop/PrestaShop/pull/33407 so we can merge it more easily.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | Test that images are deleted correctly.
| Fixed ticket?     | Fixes #33226
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
nice 👍 

there's a conflict (before I can aprove)

**Comment by Hlavtox** [comment]
@matthieu-rolland Bad branch, fixed ;-)

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]
LGTM, thanks @Hlavtox!

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

Some checks haven't completed yet, can you check that?

Thanks!

**Review by kpodemski — DISMISSED** [review]
To be verified what we do with it.

**Review by kpodemski — CHANGES_REQUESTED** [review]
It's a change of the behavior.

Before this change:
if you have a third-party solution for .webp images, they won't be deleted automatically if the product image is deleted

After the change:
They will be deleted.

You have to respect the feature flag, otherwise, there's no point in adding them.

I think we need to fix the root of the problem, which is the container not being available for webservices.

Just to be clear: it is not necessarily a _bad behavior_ introduced, but we would be messing up with images that were not generated by core, and I think we should not do it.

**Comment by Hlavtox** [comment]
@kpodemski

I don't think there is a scenario where you would want the images to be kept. If someone went through the work to put something into folder with product image, it belongs to that image.

Also, if you disable one image format in image settings, it won't be deleted and we would be keeping some files behind.

> You have to respect the feature flag, otherwise, there's no point in adding them.

There is no feature flag to respect, `ImageFormatConfiguration` is not part of a feature flag, but a normal class.

**Pull request closed without merging**
