### PR TITLE
Migration 1.7.7.x Register all new hooks

### PR DESCRIPTION
**Pull request by tdavidsonas88**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Register new hooks in _install-dev/data/xml/hook.xml_ and also 1.7.7.0.sql files. Used terminal commands to generate them.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Feature Freeze 1.7.7 TODO-List for Migration
| How to test?  | Check if after reinstalling the Prestashop the new hooks are inserted to the database correctly

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17583)

### CODE REVIEW

**Comment by tdavidsonas88** [comment]
Modified our hook list generation commands to log the failures to the database and used the commands add the missing hooks. Commands used:
```
  prestashop:update:configuration-file-hooks-listing  Appends configuration file hooks list
  prestashop:update:sql-upgrade-file-hooks-listing    Adds sql to sql upgrade file which contains hook insert opeartion
```
Would say a big thanks if you help me to verify the hooks were generated correctly and if not to improve the commands.
Also I think there are some more hooks added by the developers - not sure about the efficient way to find them all

**Comment by matks** [comment]
> Modified our hook list generation commands to log the failures to the database and used the commands add the missing hooks. Commands used:
> 
> ```
>   prestashop:update:configuration-file-hooks-listing  Appends configuration file hooks list
>   prestashop:update:sql-upgrade-file-hooks-listing    Adds sql to sql upgrade file which contains hook insert opeartion
> ```
> 
> Would say a big thanks if you help me to verify the hooks were generated correctly and if not to improve the commands.

The hooks look good ✅ . A small test could be good:
- open a migrated page and check that `$hookDispatcher->dispatchWithParameters(...)` calls the right hook name
- or even better (but longer): create a smalll test module that is hooked on one migrated SF page to check that indeed the hooks are called (see example below)

Example:
```
<?php

class TestModule extends \Module
{
    public function hookActionBeforeCreateCatalogPriceRuleFormHandler(...)
    {
        die("it works !");
    }
}
```

> Also I think there some more hooks added by the developers - not sure about the efficient way to find them all

We expect developers to register these hooks manually, see example https://github.com/PrestaShop/PrestaShop/pull/17477

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by tdavidsonas88** [comment]
@matks Tested the generated hook: actionAttachmentFormBuilderModifier by installing it to the module and it was triggered successfully :tada:

**Comment by matks** [comment]
@PierreRambaud What do you expect QA to test ? 😅 

I suggest we merge this PR without QA (@Robin-Fischer-PS dont hit me please) as this is purely technical and there is no php code in this PR

**Comment by Robin-Fischer-PS** [comment]
If QA test is needed, I would like some more details on the "how to test", if possible (step by step scenario, because as you know we are really bad in "technical" tests :P ) !

**Comment by PierreRambaud** [comment]
@matks There are change in the PHP code, plus sql requests in the upgrade process, it must be tester :thinking:

**Comment by matks** [comment]
> @matks There are change in the PHP code, plus sql requests in the upgrade process, it must be tester 🤔

I hear you but I find it hard for QA team to test this 🤔 . What can check ? What can they monitor ?

It's like cart rules 😛 any PR modifying the cart rule system needs QA to check "nothing is broken", but this is too vague.

**Comment by PierreRambaud** [comment]
@matks The upgrade process should have been test by anyway, I'll trust you :heart:

**Comment by PierreRambaud** [comment]
Thanks @tdavidsonas88

**Comment by tdavidsonas88** [comment]
Thank you all both PrestaShop Core reviews and @tomas862 for helping understand the hook commands :slightly_smiling_face:

**Pull request merged**
