### PR TITLE
IN: New feature, Nginx default configuration

### PR DESCRIPTION
**Pull request by mdrbx**
This is the first version of Nginx default configuration for Prestashop 1.7.1.
Some features need to be debugged : Front office product quick view and declination management for instance.
Need help on this !

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @MattLoyeD !

Thank you for your initiative! It can be really cool!
Maybe @rGaillard can help you ?!

**Comment by MattLoyeD** [comment]
Any news about this ?

**Comment by vincentbz** [comment]
Not yet but it would be great :)
We try to find a way to test it, by having a nginx server.

**Comment by eternoendless** [comment]
Hi @MattLoyeD 

Thanks a lot for this contribution! I took the liberty of creating a new PR with a working Nginx config file that I made which is partially based on this one.

You can find it here: https://github.com/PrestaShop/PrestaShop/pull/8128

Of course, I have given you credit as a contributor :)

**Comment by maximebiloe** [comment]
Hello @MattLoyeD,

As @eternoendless has made a new PR base on this one, I close it.

Regards

**Pull request closed without merging**
