### PR TITLE
Unify reporting of query types

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I added controller names to every product listing controller queries. It will be easier for filtering modules (faceted search) to determine where the query is coming from. PricesDrop, BestSales, NewProducts already had it filled in.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | You can test in faceted search module for example. See below.
| Possible impacts? | - 

### How to test
- You can test it in faceted search.
- `Open up \modules\ps_facetedsearch\src\Hook\ProductSearch.php` and add `dump($query);` to the beginning of `productSearchProvider` function.
- Then open all pages there are in PS - category, manufacturer, supplier, search, prices drop, best sales, new products and see that there is a query type everywhere. 
- Before, there was only a category id or search term. Much better if we can use just one property to see where are we at. :-)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26285)

### CODE REVIEW

**Review by matks — APPROVED** [review]
Is there somewhere we can see the before/after for this PR? A listing in back-office?

**Comment by Hlavtox** [comment]
@matks You can test it in faceted search.
Open up `\modules\ps_facetedsearch\src\Hook\ProductSearch.php` and `dump($query);`

Then open all pages there are in PS - category, manufacturer, supplier, search, prices drop, best sales, new products and see that there is a query type everywhere. Before, there was only a category id or search term. Much better if we can use just one property to see where are we at. :-)

**Review by tegbessou — APPROVED** [review]
Thank you for your PR!! It's good IMO

**Comment by Progi1984** [comment]
@Hlavtox Could you improve the `How to test` (with the return of @matks) and we can send the PR to QA ?

**Review by Progi1984 — APPROVED** [review]

**Comment by Hlavtox** [comment]
@Progi1984 Added to the description. :-)

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Thanks for your PR.
I found the difference between with or without PR.
I tried with branch 1.7.8.x.

- Category page 
image
- Search page
image
- new-products page
image
- best-sales page 
image
- Brands page 
image
- Supplier page 
image

I have the same result with PR
- Category page 
image
- Search page 
image
- new-products page 
image
- best-sales page  
image
- prices-drop page 
image
- Brands page 
image
- Supplier page 
image

PS: this improvement can be added to the wishlist module also :slightly_smiling_face: 
image

Thanks!

**Comment by kpodemski** [comment]
Thank you @Hlavtox and @khouloudbelguith

**Pull request merged**
