### PR TITLE
Update AbstractAssetManager.php

### PR DESCRIPTION
**Pull request by raidnew**
*fix add version in css and js files.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | 
| Type?         | bug fix 
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9382)

### CODE REVIEW

**Comment by matks** [comment]
Hi @raidnew thank you for this PR !

Can you provide some informations about it ? From what I can understand you want to handle filenames such as `form.css?v=2` ? Did you face a usecase where you needed this ?

Also as stated in the, your code must respect our Coding Standards which includes [PSR-2](https://www.php-fig.org/psr/psr-2/). Can you update your PR to match these standards ?

**Comment by Quetzacoalt91** [comment]
Hi @raidnew,

As requested by @matks, without any explanation we won't be able to go further in the review process and will have to close the pull-request.

Would you mind providing a description of the issue you try to fix here?
Thanks

**Comment by MathiasReker** [comment]
@raidnew what is status on this? :-)

**Comment by PierreRambaud** [comment]
@Mreker Still waiting for explanation. We don't know why this patch need to be merged :/

**Comment by MathiasReker** [comment]
@PierreRambaud indeed

**Pull request closed without merging**
