### PR TITLE
Add actionCartGetPackageShippingCost hook

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Allow to edit the package shipping cost value.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Related PRs.     | https://github.com/PrestaShop/autoupgrade/pull/553
| Deprecations?     | no
| How to test?      | Add a module with actionCartGetPackageShippingCost  hook and update shippingCost value.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Looks OK to me but I'm afraid a given Cart, when we need to compute total, subtotals and shipping costs / ranges / available carriers could call multiple times `getPackageShippingCost()`

So if a slow module hooks on this hook, it could slow down a lot the Checkout FO page.

Wdyt @Matt75 ? Apologies for the ping I ask you because I think you know this topic very well 👍

**Comment by kpodemski** [comment]
I've seen a lot of modules overriding this method. It might be helpful for developers. I'm still unsure if this is the best thing we can come up with for the price modification, tho.

It is the same for this hook and the one that somebody wanted to add for the `Product::priceCalculation`

**Comment by Matt75** [comment]
I'm agree with @kpodemski 

It's legit but we should add a warning on documentation to warn developers about possible performances impact.

Since years, there issues with some carrier modules that's perform an external call to third parties inside `CarrierModule::getOrderShippingCostExternal()` without usage of cache.

I think a warning to explain that hook can be called several time in same request can be a good thing.

Generally we use a cache in memory with a checksum to check if we need to update cache when change to avoid external call that's can slow down load time.

**Review by kpodemski — CHANGES_REQUESTED** [review]
Hello @PrestaEdit 

A few things are needed:
- rebase
- PR for the autoupgrade module

**Comment by kpodemski** [comment]
Ping @PrestaEdit 

Do you plan to work on this?

**Comment by PrestaEdit** [comment]
Hi @kpodemski,

I Check this very soon.

**Comment by PrestaEdit** [comment]
Done.

**Comment by Hlavtox** [comment]
@kpodemski @PrestaEdit Is it really needed to extract the logic to a new function? You could put the hook to the end of the current function no?

**Comment by PrestaEdit** [comment]
It's allow to by-pass the return made in the base of the function like if it's a virtual cart. You maybe want, with this hook, to handle a shipping cost even on a virtual cart (as an example).

**Comment by Hlavtox** [comment]
Aaaah, so it would never get to the hook. OK, understand :-)

**Review by Hlavtox — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @PrestaEdit ,

Tested with the module quality assurance.

It works well, the shipping cost is well updated with these elements :
Screenshot 2023-02-20 at 16 51 07

It is QA ✅ 
Thanks!

**Comment by nicosomb** [comment]
Thank you @PrestaEdit and @florine2623 !

**Pull request merged**
