### PR TITLE
Better validate cookie length

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | See below
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See below
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/6927521249 ✅ 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | 

### Description
- This PR makes sure that the cookie is valid before sending it to the browser. Otherwise, the browser will silently refuse to save the cookie and the user will be wondering why the page won't work. If there is an overflowing cookie, the merchant will now know and it will be logged.
- There was a case like this before with ps_viewedproducts, where it saved an infinite list of products into a cookie, resulting in the cookie overflowing after some time.
- So, according to RFC 2965 I check for combined BYTE LENGTH of both the name and content.

### The original logic was broken
  - It just failed with no explanation.
  - It was using wrong count to check it.
  - It was using mb_strlen with some overloading (removed in PHP 8 btw). It must use strlen, because strlen will give you byte length.
  - It was checking the length before the encryption.
  - It was checking only the content length, you must check the combined length.

### How to test
Open `classes/controller/FrontController.php`, find `public function init()` and put this to the end of the method.

```php
$this->context->cookie->test .= 'blablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablablabl';
```
Go to homepage and keep hitting F5. You will see that you get an exception after few hits.

### CODE REVIEW

**Review by boherm — DISMISSED** [review]

**Review by boherm — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
nice 👍  did you notice this problem IRL ?

**Comment by Hlavtox** [comment]
@matthieu-rolland Yes, few years ago. Every few weeks, adding to cart stopped working on our employee's PCs. After flushing cookies it started to work again.

It was caused by ps_viewedproducts adding a list of viewed products to cookie infinitely, until it was too large that it was not saved by the browser. It was fixed only recently - https://github.com/PrestaShop/PrestaShop/issues/26996.

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

I followed your steps. I have the expected behavior :
Screenshot 2023-11-20 at 11 02 21

It is QA ✅

**Comment by Hlavtox** [comment]
Perfect, thank you @florine2623!!! :-)

**Pull request merged**
