### PR TITLE
[-] LO : Update Lithuanian currency to Euro

### PR DESCRIPTION
**Pull request by gskema**
I believe this commit got lost with the merge of 'release' branch. It would be great if you could include this with the hotfixes.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

https://github.com/PrestaShop/PrestaShop/commit/7fc692806027701721ef5922907d7bb16e1ecafc

Regards

**Comment by gskema** [comment]
Hello,

why aren't the changes of 7fc6928 reflected in the current state of lt.xml in 1.6 branch? Were the change overwritten by c0a4fe2 ?

Thanks

**Comment by gRoussac** [comment]
Hi,

Yes your are right I beleieve. I will see with @jeromenadaud.

Thank you. Regards

**Comment by gRoussac** [comment]
Hi,

https://github.com/PrestaShop/PrestaShop/commit/b8e19123235e7c1969516154bee30a21eb50af90

Thank you for your dedication.

Regards

**Pull request closed without merging**
