### PR TITLE
[-] MO : productcomments -> 4 stars by default

### PR DESCRIPTION
**Pull request by indesign47**
Changed default grade from 3 to 5
https://github.com/PrestaShop/productcomments/commit/809e699846f4d4cc2fa1624cd892bbe1cf87da03

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, why 5 by default ?

Best regards.

**Comment by indesign47** [comment]
Hi Jérome,

Ask, in the past, to Fabio and Emilien... and then Damien do it.

https://github.com/PrestaShop/productcomments/commit/809e699846f4d4cc2fa1624cd892bbe1cf87da03
Best regards

**Comment by jeromenadaud** [comment]
Hi, 5 stars seems to be very higher and not very credible, why not 4 ?

Best regards.

**Comment by indesign47** [comment]
Hi Jérome,

• If a customer leave a very good comment and forget to change stars you get a 3 stars.
• If a customer leave a very bad comment and forget to change stars you get also 3 stars.
Maybe the best solution is, like for title or comment, that stars must be set by defaut at "0" and throw an error if the customer leave "0" stars.

Best regards.

**Comment by jeromenadaud** [comment]
Hi, What do you think the merchant will expect to see in his product page ? I think 4 it's ok.

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR.

Best regards.

**Pull request merged**
