### PR TITLE
Fix shopping cart when allow checkout with unavailable pack items

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | The shopping cart allows checkout with unavailable pack items.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7170
| How to test?  | BO > preferences > products > choose decrease both for packs, create a product A with a stock of 50, create a product B with a stock of 5 (this product is a pack of 10 products A), order 50 products A and 5 products B, FO > shopping cart and check if an error message appears.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8457)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[classes/Cart.php, line 4090 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyKzHff8xMjR2UmsKYF:-KyKzHfgrySfqejn5-OH:b-ffksda) ([raw file](https://github.com/prestashop/prestashop/blob/289d8ef50313bba0451dd06949fb248a04310bcc/classes/Cart.php#L4090)):*
> ```PHP
>     public function checkPackitemQuantities()
>     {
>         if (Configuration::get('PS_PACK_STOCK_TYPE') > 0) {
> ```

To reduce complexity, please use the following form (early return) :
```php
if (!Configuration::get('PS_PACK_STOCK_TYPE') > 0) {
    return true;
}
// Then, the rest of the code
```

---

*[classes/Cart.php, line 4110 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyL-EU3jQgbXiB0eCL0:-KyL-EU4w64_jZVt-eEQ:bde34l) ([raw file](https://github.com/prestashop/prestashop/blob/289d8ef50313bba0451dd06949fb248a04310bcc/classes/Cart.php#L4110)):*
> ```PHP
> 
>         return true;
>     }
> ```

This method is too complex and not easily readable.
Please extract smaller methods :
```php
$result = true;
foreach ($products as $cartProduct) {
    $product = new Product((int)$cartProduct['id_product']);
    if ($product->getType() === Product::PTYPE_PACK) {
        $result $= $this->validateProductPackQuantities($product);
    }
}

return (bool)$result;
```
```php
private function validateProductPackQuantities(Product $product) {
    $result = true;
    foreach (Pack::getItems($product->id, $this->id_lang) as $item) {
        $return $= $this->validatePackItemQuantity(/* parameters here */);
    }

    return (bool)$return;
}
```
```php
private function validatePackItemQuantity(/* parameters */) {
    // you get the point
}
```
Please be consistent in return type, it will be easier for the calling code to use the result.
Don't forget phpDoc !

---

*[controllers/front/CartController.php, line 353 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyL2CNBP5vDeOzJaGhS:-KyL2CNCw8YDiV6hqz2s:b-bayhgj) ([raw file](https://github.com/prestashop/prestashop/blob/289d8ef50313bba0451dd06949fb248a04310bcc/controllers/front/CartController.php#L353)):*
> ```PHP
>         $packProduct = $this->context->cart->checkPackitemQuantities();
>         if ($packProduct !== true) {
>             $this->errors[] = sprintf(Tools::displayError('An item (%1s) in your cart is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted.'), $packProduct['name']);
> ```

Please break the sprintf call in multiple lines

---

*[controllers/front/OrderController.php, line 61 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyL2U_A2dFQuVQK8GqU:-KyL2U_A2dFQuVQK8GqV:bkb0gci) ([raw file](https://github.com/prestashop/prestashop/blob/289d8ef50313bba0451dd06949fb248a04310bcc/controllers/front/OrderController.php#L61)):*
> ```PHP
>         if ($packProduct !== true) {
>             $this->step = 0;
>             $this->errors[] = sprintf(Tools::displayError('An item (%1s) in your cart is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted.'), $packProduct['name']);
> ```

Same here, multiple lines please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thanks Azouz.
Some changes are required for a better maintainability.

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
Can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[classes/Cart.php, line 4092 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyokHJDxv4veMhM2svI:-KyokHJE3nx6nuBbqw71:byh9c5b) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4092)):*
> ```PHP
>         if (Configuration::get('PS_PACK_STOCK_TYPE') <= 0) {
>             return true;
>         } else {
> ```

The else is useless.
The aim of all this is reducing indentation and NPath.

---

*[classes/Cart.php, line 4112 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyolZY6YU9tUlnSgErz:-KyolZY7CtNILeb4HlxO:b5bqko0) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4112)):*
> ```PHP
>      * Validate product pack quantities
>      *
>      * @param array $cartProduct - Array of cart product
> ```

I would discribe it as "single cart product data"

---

*[classes/Cart.php, line 4116 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KytfDo4O-o-ZSJG1qpQ:-KytfDo4O-o-ZSJG1qpR:b5hr1yv) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4116)):*
> ```PHP
>      * @return bool|Product
>      */
>     private function validateProductPackQuantities($cartProduct, &$products)
> ```

Why would you pass `$products` as reference ? We want to validate, not to modify.

---

*[classes/Cart.php, line 4124 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KytcmWeFxOg5F2gAFyu:-KytcmWeFxOg5F2gAFyv:bl3se2x) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4124)):*
> ```PHP
>                 return $result;
>             }
>         }
> ```

I suggest doing something like this :
```php
foreach(/* whatever */) {
    if (!$this->validatePackItemQuantity(/* params */)) { // Fuzzy statement because this methods returns boolean only
        return false;
    }
}

return true;
```
And then, obviously, refactor `validatePackItemQuantity()` so it returns boolean only (see below).

---

*[classes/Cart.php, line 4131 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyteTu5u8ovHGyENlXL:-KyteTu5u8ovHGyENlXM:b-81ms2w) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4131)):*
> ```PHP
>     /**
>      * Validate product pack item quantity
>      *
> ```

Please add a description to explain how it is validated (if you don't, we have to go through the code and try to understand).
At list describe the validation conditions. 

---

*[classes/Cart.php, line 4133 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyonE7DxxbcCVjTsQRz:-KyonE7Eykl7UMo0QKev:b3mp3ia) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4133)):*
> ```PHP
>      *
>      * @param Product $item
>      * @param array $cartProduct - Array of cart product
> ```

"single cart product data"

---

*[classes/Cart.php, line 4135 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kytfa7hoh3LngcQZg4M:-Kytfa7hoh3LngcQZg4N:b-si8tp1) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4135)):*
> ```PHP
>      * @param array $cartProduct - Array of cart product
>      * @param array $products - Array of cart products
>      * @return bool|Product
> ```

Please return bool only.

---

*[classes/Cart.php, line 4140 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KyteNd2Fqv8eqw1gaHz:-KyteNd3t4kdwU_4ODUp:bvnd60r) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4140)):*
> ```PHP
>     {
>         $productsIds = array_column($products, 'id_product');
>         $key = array_search($item->id, $productsIds);
> ```

Please rename `$key` with a more explicit name

---

*[classes/Cart.php, line 4148 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kyte-YFE0jpJBm7FGpV:-Kyte-YFE0jpJBm7FGpW:bfv6vok) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4148)):*
> ```PHP
>                 'cart_quantity' => $totalQuantity,
>             );
>             $products[$key]['cart_quantity'] += $totalQuantity;
> ```

Why would you modify a product list used as a reference for our tests ? How can we trust a reference list if the code itself is altering it ?
If a modif is needed, it should be performed outside this method.
Something like "if not valid, then modify this thing" (2 method calls : validate and modify).

---

*[classes/Cart.php, line 4154 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kytdgspv77CGkHoQ0V1:-Kytdgsq_kg-y1sVGmi9:b-590d7z) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4154)):*
> ```PHP
> 
>         if ($item->quantity < $totalQuantity) {
>             return $item;
> ```

I disagree with this. Validation method should only check if "things" are ok. It shouldn't return anything else than "yeah it's ok" or "no it's not ok".
If return type is not predictable, it makes this method hard to use.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Ok things are getting better, but still need to be sorted out.
See my comments above.

**Comment by Azouz-Jribi** [comment]
*[classes/Cart.php, line 4154 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kytdgspv77CGkHoQ0V1:-Kyz4pzSnhzTjv0XAWmW:bcuyqgi) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4154)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

I disagree with this. Validation method should only check if "things" are ok. It shouldn't return anything else than "yeah it's ok" or "no it's not ok".
If return type is not predictable, it makes this method hard to use.
</blockquote></details>

I think in our case, we must return the item with the quantity not available, to notify the customer, which product he must adjust

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Comment by LittleBigDev** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[classes/Cart.php, line 4154 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kytdgspv77CGkHoQ0V1:-Kyz8T3mX-Q4UxfO5q3i:bgdyyp6) ([raw file](https://github.com/prestashop/prestashop/blob/8f3132d05918dc3323dd8772edbb9ae605c4613f/classes/Cart.php#L4154)):*
<details><summary><i>Previously, Azouz-Jribi wrote…</i></summary><blockquote>

I think in our case, we must return the item with the quantity not available, to notify the customer, which product he must adjust
</blockquote></details>

Caller of `validatePackItemQuantity()` method already knows which item is being validated (passed as parameter of the method).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
Correction is done, can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[classes/Cart.php, line 4088 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kz8beWPtMQr1CF19uE2:-Kz8beWPtMQr1CF19uE3:bssii7s) ([raw file](https://github.com/prestashop/prestashop/blob/bf861559fe73c29027737ae26819411898f0f0e8/classes/Cart.php#L4088)):*
> ```PHP
>      * @return bool|Product - Return the product in case it's quantity is unavailable
>      */
>     public function checkPacksitemsQuantities()
> ```

Add a capital "I" (for Items) in the method name

---

*[classes/Cart.php, line 4103 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kz8cqJ6Af88gUEvQ3C7:-Kz8cqJ7HEG9e3t2RJjZ:begwbqz) ([raw file](https://github.com/prestashop/prestashop/blob/bf861559fe73c29027737ae26819411898f0f0e8/classes/Cart.php#L4103)):*
> ```PHP
>                 $allCartProducts = $this->extractPackItems($cartProduct['id_product'], $cartProduct['cart_quantity'], $allCartProducts);
>             }
>         }
> ```

This whole `foreach` should be another private method, like `getCartProductsFlatList($cartProducts)` (or something equivalent). "Flat" because pack items would be replaced by multiple simple products in the returned array.

---

*[classes/Cart.php, line 4116 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kz8anthMfmvUHGx-K_1:-Kz8anthMfmvUHGx-K_2:b-k7rbix) ([raw file](https://github.com/prestashop/prestashop/blob/bf861559fe73c29027737ae26819411898f0f0e8/classes/Cart.php#L4116)):*
> ```PHP
>      * @return array - Array of cart products
>      */
>     private function extractPackItems($productId, $packQuantity, $allCartProducts)
> ```

SRP ! Please don't extract + inject. 
`$allCartProducts` should no be a parameter of this method.
The *caller* should use the result of `extractPackItems()` to add new entries or increment quantities in `$allCartProducts` (more detailed comment below). 

---

*[classes/Cart.php, line 4138 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-Kz8b6ghdqG3wXL6iHrq:-Kz8b6ghdqG3wXL6iHrr:bsscwjp) ([raw file](https://github.com/prestashop/prestashop/blob/bf861559fe73c29027737ae26819411898f0f0e8/classes/Cart.php#L4138)):*
> ```PHP
>             } else {
>                 $allCartProducts[$productIndex]['cart_quantity'] += $totalQuantity;
>             }
> ```

This method should only return a list of extracted pack items (+ relevant data).
The `$allCartProducts` modifications should be performed outside.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thank you, this is getting better !
Well done with "displayError" factorization.

Still some changes needed though (single responsibility principle is important for maintainability).

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev
Correction is done, can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[classes/Cart.php, line 4142 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KzOgshWQjH1nZpIxZ5h:-KzOgshWQjH1nZpIxZ5i:bfvjcye) ([raw file](https://github.com/prestashop/prestashop/blob/7a87ce50ba9ab84d8a62e4755790c5af4750cddc/classes/Cart.php#L4142)):*
> ```PHP
>         }
> 
>         return $cartProductsTmp;
> ```

I can see you added the extracted pack items in `$cartProductsTmp`, but you didn't remove the original pack. Is it normal ?

---

*[controllers/front/CartController.php, line 439 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KzOhuT68UGliWaBv2B5:-KzOhuT7CVrCgQqw-nv_:b-lp1i8) ([raw file](https://github.com/prestashop/prestashop/blob/7a87ce50ba9ab84d8a62e4755790c5af4750cddc/controllers/front/CartController.php#L439)):*
> ```PHP
>      * Check if the packs items in the cart are available
>      */
>     private function shouldPacksItemsAvailable(){
> ```

Bad naming.
Better use `validatePackItemsAvailability()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thank you @Azouz-Jribi.
2 more details to address, and we are good.

**Comment by Azouz-Jribi** [comment]
Hi @LittleBigDev 
Correction is done, you're right about removing the original pack.
Can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
:lgtm:

Nice :)

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-:-KzTGnL1Ru2Q9RJkP1qa:b-77x45b)*

**Review by LittleBigDev — DISMISSED** [review]

**Comment by marionf** [comment]
Hello @Azouz-Jribi 
I tested and didn't see error message in shopping cart, I can complete the order.

**Comment by Azouz-Jribi** [comment]
Hi @marionf 
it works well for me :/

This is how to test it :
1- BO > Products > set **Default pack stock management** value as **Decrement both**.
2- BO > Catalog > Products > create a new product A with quantity = 50.
2- BO > Catalog > Products > create a new pack B with quantity = 5 (this pack consists of 10 products A).
3- FO > order 5 **packs B** and 50 **products A**.

- when I visite the cart page :
pscsx-7170-1
- when i try to modify the quantity :
pscsx-7170-2
If we use **Order process type** as **Five steps** the error message appears, but if we use **One-page checkout** the error won't be displayed (I'm working to fix it).

**Comment by marionf** [comment]
Thank you @Azouz-Jribi for these details, it's because I was in one page checkout.
If I have in my cart more products than in my stock, the error message is displayed twice

capture du 2017-11-24 16-26-29

**Comment by Azouz-Jribi** [comment]
Hi @marionf 
The correction is done to fix the problem for the one page checkout.
You can retest it after the code review.
@LittleBigDev can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
:lgtm_cancel: 
Need to review again.

---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-:-Kzw_f3UXBN1b8XC7zP5:b-lr16jd)*

**Comment by LittleBigDev** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[themes/default-bootstrap/js/order-opc.js, line 327 at r6](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KzwiqwrHV9lTYMmcv2J:-KzwiqwsVCnms4Y6ZGts:bzi82is) ([raw file](https://github.com/prestashop/prestashop/blob/415f425ea45c9553c783dfd62e54b144f22fe02e/themes/default-bootstrap/js/order-opc.js#L327)):*
> ```JavaScript
> function updatePaymentMethodsDisplay()
> {
> 	var checked = '';
> ```

Please replace all tabs indentations by spaces indentations

---

*[themes/default-bootstrap/js/order-opc.js, line 353 at r6](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-KzwgNAgoO9ovTA8DMV3:-KzwgNAgoO9ovTA8DMV4:bxp6afy) ([raw file](https://github.com/prestashop/prestashop/blob/415f425ea45c9553c783dfd62e54b144f22fe02e/themes/default-bootstrap/js/order-opc.js#L353)):*
> ```JavaScript
> 							}
> 						}
> 						if (!!$.prototype.fancybox) {
> ```

Double negation is hard to read.
Please use `Boolean($.prototype.fancybox)` or any other readable way to check if fancybox exists (creators of this plugin probably provided a recommended way of doing this)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thank you @Azouz-Jribi.
Minor changes requested.

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
Correction is done, can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8457#-:-L-62uzRDsFzKIUlxcJ3:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by marionf** [comment]
I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

Furthermore, I can't reproduce the issue with PrestaShop 1.7.6.1:
After adding 50 products A to the cart, if I go to the product page of product B (pack), I can't add it to the cart (Out of stock message + add to cart button disabled)

**Pull request closed without merging**
