### PR TITLE
Fix wrong product alignment in product lists for smaller devices

### LINKED ISSUE #16249: Product alignment is wrong in product lists for smaller devices
**Describe the bug**
In product lists and featured products on homepage, products look broken on smaller screens due to` justify-content: flex-start;`. We need to fix this as it looks terrible on mobile devices (see screen).
**To Reproduce**
Try if on mobile or via developer tools

**Screenshots**
before

**Additional information**
PrestaShop version: 1.7.7
PHP version: N/A

### PR DESCRIPTION
**Pull request by rdy4ever**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In product lists and featured products on homepage, products look broken on smaller screens due to justify-content: flex-start;. We need to fix this as it looks terrible on mobile devices (see screen).
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16249
| How to test?  | Untitled-1

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16250)

### CODE REVIEW

**Comment by rdy4ever** [comment]
OK, I have a problem with 2 earlier commits I have made by mistake on develop that are now commited at each PR. I couldn't find a way to fix it for this repository on GH Desktop/Windows

**Comment by PierreRambaud** [comment]
You can reset your branch to a commit

`git reset --hard COMMIT_HASH` if you want to remove some recent commits

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
@rdy4ever Pull request squashed and rebased ;)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Progi1984** [comment]
@rdy4ever Could you rebase and rebuild your assets, please ?

**Comment by PierreRambaud** [comment]
@Progi1984 Pr rebased

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@PierreRambaud Thanks. I wait for Travis and I merge it if it's Green

**Comment by PierreRambaud** [comment]
Thanks @rdy4ever

**Comment by PierreRambaud** [comment]
Thanks @rdy4ever

**Pull request merged**
