### PR TITLE
Remove Persian install fixtures

### LINKED ISSUE #22657: Installation Error in Persian (Farsi) Language.
#### Describe the bug

On the installation process (PrestaShop v1.7.7.0) in Persian (Farsi) language, one error happened about carrier->delay is empty and installation with demo data can't be succeeded

I created a PR for this #22564

#### Expected behavior

Nobody can install PrestaShop in version 1.7.7.0.  
unless disabling demo data -OR- install in English and after that add the Persian Language from admin.
#### Steps to Reproduce

1. Go to the installation
2. change the language to Persian (Farsi)
3. Go to the installation steps.
4. See an error

**Screenshots**

image_2020-12-24_13-47-09

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: I don't remember but I believe 7.1

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | **I dont know why but Persian is the only language that has hardcoded fixtures in its install fixtures folder** (see https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/fixtures/fashion/langs/fa/data).<br/><br/>In this PR I remove these hardcoded fixtures in order to make sure Persian language is processed similarly to other languages available at install step. It seems to fix https://github.com/PrestaShop/PrestaShop/issues/22657.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/22657
| How to test?      | Please follow ticket steps and confirm shop is installed correctly.
| Possible impacts? | ~

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22674)

### CODE REVIEW

**Comment by matks** [comment]
Data was put there by https://github.com/PrestaShop/PrestaShop/pull/8834 . Why ? 🤔

**Comment by atomiix** [comment]
@matks I'm not sure to understand but to me Persian is **not** the only language with harcoded fixtures. Take a look at the french folder for instance: https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/fixtures/fashion/langs/fr/data

**Comment by matks** [comment]
@atomiix Indeed 2 other folders have hardcoded fixtures: `fr` and `en`.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
I'm not sure it's the right way to do it.
There are a lot of translated fixtures (as an example https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/fixtures/fashion/langs/bn/data https://github.com/PrestaShop/PrestaShop/tree/develop/install-dev/fixtures/fashion/langs/de/data)

We should fix the problem, and removing fixtures :thinking:

**Comment by matks** [comment]
@PierreRambaud After a more thorough analysis, what I have is:
- `fashion/langs/fr/data` folder has full fixtures translated
- `fashion/langs/en/data` folder has full fixtures translated
- `fashion/langs/fa/data` folder has full fixtures translated
- all other folders have only `product.xml` translated

In this PR I remove all `FA` files excluding `product.xml` file, to make sure FA language is processed similarly to other languages (with the exception of FR and EN).

EDIT: Note that removing the fixtures _does not prevent them from being translated_. After an install without these fixtures I have a category translated.

There is something strange about the fact that FA has hardcoded translated fixtures, and not DE or ZH 🤔 .

**Comment by PierreRambaud** [comment]
> @PierreRambaud After a more thorough analysis, what I have is:
> 
> * `fashion/langs/fr/data` folder has full fixtures translated
> * `fashion/langs/en/data` folder has full fixtures translated
> * `fashion/langs/fa/data` folder has full fixtures translated
> * all other folders have only `product.xml` translated
> 
> In this PR I remove all `FA` files excluding `product.xml` file, to make sure FA language is processed similarly to other languages (with the exception of FR and EN).

But is it what we really need? :sweat_smile: 
Are values correctly translated with your change? is everything ok? 
I'm not sure everything should come from crowdin, we have to be sure it's the desired behaviour and not assumption :)

**Comment by jolelievre** [comment]
Just because only three languages have install data translated doesn't mean it's a bad thing.. It just means french and english were (naturally) handled by the core team And someone (probably from community) put some extra effort to add farsi data in the fixtures

It seems to me that removing these data is simply hiding the problem not fixing anything, it means if someone adds data fixtures in another language it will then bug again?

**Comment by jolelievre** [comment]
(By the way if the purpose is to fix a 177 bug this PR should target 177 branch and version)

**Comment by matks** [comment]
My reasoning is as follows:

1. From what I see, only FA language has translated demo fixtures, with the exclusion of FR and EN for the reasons stated by @jolelievre .
2. It seems these data are out-of-sync with db structure which is why the install cannot happen. It's highly probable that at some point FR and EN demo data needed to be updated but FA fixtures were not updated accordingly.
3. We can fix the translated demo fixtures but the bigger issues, highlighted by this bug, will stay:
a) everytime demo fixtures must be updated for FR and EN, we'll need to do the same for FA fixtures although we do not have someone fluent in Persian in the team
b) this data is hardcoded which means it cannot be managed on Crowdin to be improved and updated
c) the other languages (german, danish, chinese...) are still not translated so the feature "have demo fixtures translated" is very far from completion

If I check our resources, the time we have to work on different topics, I don't think we'll fix  a) b) or c) soon in the future 🤔  so I'd rather suppress the topic than keep the current situation and come back to a situation I think we can manage which is "only FR and EN (languages we can handle by ourselves) have demo fixtures".

The [initiative of translating demo data](https://github.com/PrestaShop/PrestaShop/pull/8834) for Persian was a nice one 👍  but it was 2 years ago and nothing changed since then. This is why I think it could be a good choice to drop the "have demo fixtures translated" issue rather than fixing it just for Persian.

Your call 😄

**Comment by Arman-Hosseini** [comment]
@matks I can manage the translations of FA fixtures.

**Comment by AliShareei** [comment]
Dear @matks,
PrestaShop is taught at some educational levels in Iran.
We worked closely with teachers and authors of educational books for Prestashop in Iran.

I believe that problems like the previous PrestaShop demo that was not suitable for schools and educational levels have changed for this reason.
Since there is no internet connection in many schools, this fixtures data is probably in the source for this reason.

So I think to remove this data is not a good idea for that reason. (I'm not exactly sure but I think it's related)
Since we check all versions of PrestaShop for use in Iran, it will probably not be a problem if has a problem like this we will send a PR like #22564.

Do not worry about the Persian language and its demo data.

**Comment by AliShareei** [comment]
Dears @matks, @jolelievre, @PierreRambaud, @Arman-Hosseini,

As I told in my PR & issue topic. (in issue targeted for 1.7.8.0) It's better to fix this in the next patch release.
I have some calls from teachers all over Iran, schools that I do not even know where they are about this problem.
And I have to explain to them on the phone what to do.

Edit: I checked again it's seems changed from 1.7.8.0 to 1.7.7.x. It's good Thanks.
As I found the next patch I mean 1.7.7.1 is in process and cant be fixed on that version.
But I want to know if you can make changes to the final zip and hardcoded to fix this?

**Comment by AliShareei** [comment]
> If I check our resources, the time we have to work on different topics, I don't think we'll fix a) b) or c) soon in the future 🤔 so I'd rather suppress the topic than keep the current situation and come back to a situation I think we can manage which is "only FR and EN (languages we can handle by ourselves) have demo fixtures".
> 
> The [initiative of translating demo data](https://github.com/PrestaShop/PrestaShop/pull/8834) for Persian was a nice one 👍 but it was 2 years ago and nothing changed since then. This is why I think it could be a good choice to drop the "have demo fixtures translated" issue rather than fixing it just for Persian.
> 

Dear @matks,

I don't know about how data insert from fixtures to DB. but I think if the installer first loads data from `EN `or `FR `and then merged with other existing language data chooses by the user.
There will be no more possible errors even if the data is incomplete and outdated.

**Comment by matks** [comment]
I close this PR as it sounds like it was a bad idea 😉 thanks for the feedback !

**Pull request closed without merging**
