### PR TITLE
[-] WS : fix wrong check of available field getter

### PR DESCRIPTION
**Pull request by kelu95**

### CODE REVIEW

**Comment by PrestaEdit** [comment]
I'm not sure about that... The test is to know if  field in $webserviceParameters have a setter/getter.

As the field is dynamic (getter), you can take it directly. Like the test and the error say to us.

No ? :)

**Comment by totti240282** [comment]
RETURN HTTP BODY

Fatal error: Call to undefined method Language::getIDs() in /var/www/vhosts/supplementmuscle.com/httpdocs/classes/webservice/WebserviceRequest.php on line 479

**Comment by totti240282** [comment]
RETURN HTTP BODY

Fatal error: Call to undefined method Language::getIDs() in /var/www/vhosts/supplementmuscle.com/httpdocs/classes/webservice/WebserviceRequest.php on line 479

**Comment by PrestaEdit** [comment]
@totti240282 if you try this file, you need to apply this commit too: https://github.com/kelu95/PrestaShop/commit/836105f5d1d878ffbff5578e89e2414bd5dc055a

**Comment by totti240282** [comment]
Ok now is ok ?

Thanks !

**Comment by totti240282** [comment]
<message><![CDATA[The field "ean13" is dynamic. It is not possible to filter GET query with this field.]]></message>

**Comment by kelu95** [comment]
Hi, i need to check that deeply.
I coming back to you quickly.

**Comment by totti240282** [comment]
Thanks.

**Comment by kelu95** [comment]
Hi,

this PR cant be work, and bug associated identified as non bug

Regards

**Comment by totti240282** [comment]
with this change I can not filter by code ean13 and wholesalesprice.

**Comment by Ecno92** [comment]
@kelu95 Any updates about this issue?

**Comment by totti240282** [comment]
I attend !

**Comment by studiokiwik** [comment]
Hello
any news on that?

**Pull request closed without merging**
