### PR TITLE
Make color and texture consistent when both are set

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Product variants may be color or texture but not both.<br>This refacto changes 2 if by if-elseif
| Type?         | refacto
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Check that the product variants are shown correctly in:<br>Product with color and texture variants in Product miniature, product page and quick view.

Product variants may be color or texture but not both.
As seen in
https://github.com/PrestaShop/PrestaShop/pull/12523/files#diff-284fd264950a297a1db191d6d0946ef9R47
and
https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/facets.tpl#L85

I used if-elseif instead to improve readability and not see that both could be simultaneously.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15284)

### CODE REVIEW

**Comment by marionf** [comment]
@kpodemski What do you think of this change ?

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Seems legit. By definition we can't have both.

**Comment by marionf** [comment]
@kpodemski would like to have both: https://github.com/PrestaShop/PrestaShop/issues/10596#issuecomment-461774283

**Comment by PierreRambaud** [comment]
This is what this commit is doing :D 
If texture => use texture
Else if color => use color

But you're still able to save both data in the BO. But you can't render both in FO.

**Comment by kpodemski** [comment]
👍

**Comment by marionf** [comment]
@davidglezz 

This PR doesn't change the current behavior which is:

If I add a texture AND a color:

capture d'écran_1940

- Attribute listing BO = texture

capture d'écran_1941

- Attribute listing product page BO = color

capture d'écran_1942

- Product page FO = texture

capture d'écran_1943

- Product listing FO = color

capture d'écran_1944

- Quickview FO = texture

capture d'écran_1945

**Comment by PierreRambaud** [comment]
Hi @davidglezz Your pull request needs to be rebased to continue :)

**Comment by davidglezz** [comment]
The original intention of this PR was to improve and simplify the "if" condition of the template "product-variants.tpl", but in the end I modified the rest of the templates to be consistent:
```
If texture => use texture
Else if color => use color
```
On the other hand, I have not been able to perform my own tests (problems with the current dockerfile) but the screenshots provided by @marionf in "Product listing FO = color" do not fit with the code.

I will investigate a bit more and try to provide screenshots, apologies for the delay, I have little time.

**Comment by davidglezz** [comment]
This PR makes color and texture consistent in all places.

Previously, if both color and texture were selected, then in some places color was shown and in others texture was shown.

If the 2 are set, texture is shown. If the user wants to show the color it will be easy to delete the texture.


If I add a texture AND a color:
image

- Attribute listing BO = texture
image

- Attribute listing product page BO = texture
image

- Product page FO and Quickview FO = texture
image

- Product listing FO = texture
image

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @davidglezz

**Pull request merged**
