### PR TITLE
[-] BO : Fixed php notice for forms with field value not assigned.

### PR DESCRIPTION
**Pull request by Exadra37**
The php error:

```
Notice on line 290 in file /home/www/example.com/public_html/cache/smarty/compile/e5/ed/62/e5ed620e752d74f90e7efcbbe311b3ca216cb43f.file.form.tpl.php [8] Undefined index: 8
```

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, can you describe some steps in order to reproduce this error ?

Best regards.

**Comment by Exadra37** [comment]
After an upgrade from 1.3 to 1.6 where in 1.3 just the language id 3 was present, all the other ones where deleted, and in the new 1.6 we have languages id 1, 2 and 3 present but no values in database for id languages 1 and 2, therefore when building the form you will get this php notice, because you are trying to assign a value from an array key that do not exists.

**Comment by jeromenadaud** [comment]
Hi,

If language 2 and 3 is not present, it's because you have an other problem.
I think, keeping the notice to be present, it help you to see that you have a real problem.

Best regards.

**Comment by Exadra37** [comment]
The values are not present because in this case the carrier have never been saved with this language, therefore if you ignore the notice and save the carrier and came back again the notice will not appear any more.... so no other problem here, as explained before in this situation the 2 languages have been added to the new store in 1.6 version, but they where not present in the previous version 1.3.

But this form Helper is used in the core code and any Module you develop for Prestashop can use it also... So i do not agree in have the code trying to access elements in an array that don't exists.

I am developer, not a curious, and i always prefer to have code that checks if a key of an array is isset or not empty, depending on the case. 

I always develop with debug set to true and i never ship code to my clients that are giving any type of php error, warning, notice, etc.... but i solve lot of bugs in third part  Modules and Themes, that clear do not develop with debug active or just ignore all the warnings and errors.

This my preference and i think is a best practice that every developer should care about in order to avoid potential bugs in their applications later on in production.

But this is my opinion and i do not want to enforce it to any body... 

Thanks for your time and attention in my PR ;)

**Comment by Exadra37** [comment]
Closing, once new version released, this seems to be out of interest for merging into the core code.

**Pull request closed without merging**
