### PR TITLE
Update PrestaShop module version

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Update PrestaShop module version
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Only CI and auto tests green https://github.com/lartist/ga.tests.ui.pr/actions/runs/4125261061
| Fixed ticket?     |
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Comment by Robin-Fischer-PS** [comment]
Hi,
Only auto tests green on this one indeed for QA. Thanks !

**Review by zuk3975 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional some errors are red, false-positives?

**Review by MhiriFaten — COMMENTED** [review]
Hello @lartist ,
I'll remove the 'waiting for QA' label, and you can put it back on when it's ready for testing again!
Thank you.

**Review by mflasquin — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
> Hi, Only auto tests green on this one indeed for QA. Thanks !

Tested with UI tests All good

**Comment by nicosomb** [comment]
Thank you @lartist and @boubkerbribri !

**Pull request merged**
