### PR TITLE
Make the slider appears on Mobile view

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | The image slider (in home page) is not displayed in the mobile view.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3134
| How to test?  | Enable the modules ps_imageslider and enable it for mobile view, go to FO and check if the image slider appears on Mobile view.

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]
Code looks good

**Comment by marionf** [comment]
Hello @Azouz-Jribi 
There is a proportion issue with the slider on mobile.

pr8152

We must keep the same proportions for the images.
As for the banner:

pr8152-2

**Comment by Azouz-Jribi** [comment]
Hi @marionf 
I try to fix as soon as possible.

Thanks ;)

**Comment by Azouz-Jribi** [comment]
Hello @marionf 
Correction is done.
Can you retest it ?

Thanks

**Comment by marionf** [comment]
Hello @Azouz-Jribi 
It's working thank you very much !

**Comment by aleeks** [comment]
hello @Azouz-Jribi 
Need a rebase here!

**Comment by Azouz-Jribi** [comment]
Hi @aleeks 
Rebase is done ;)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @Azouz-Jribi

**Pull request merged**
