### PR TITLE
Improve email validation

### PR DESCRIPTION
**Pull request by ghost**
Prevents logs and exceptions returned by the Swift

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Avoid saving incorrect email addresses.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Simply try to use an email address like this `mail..fine@mail.com` in any form that you subsequently have to send an email to that email address, what's the problem?, PrestaShop will save perfectly the email without any error message for the user, but once an attempt is made to send the email, Swift will throw an exception and obviously the email will never be sent. With this modification we take advantage of Swift's own validation and avoid storing incorrect emails.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12377)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
As I do agree we should use Swiftmailer to validate mails, you can see in our test suite that some tests are broken.

The email "john.doe@prestashop" is valid for Swiftmailer and not valid for PrestaShop: I'm not an expert, so I don't know who is right here :unsure:

What do you think?

**Comment by PierreRambaud** [comment]
john.doe@prestashop is logically valid, but since we are using a very very very old version of Swiftmailer, we also have a very old RFC checker which is for example disalowing utf8 characters,

**Comment by Rolige** [comment]
@mickaelandrieu @PierreRambaud maybe we can take the best of both worlds with...
```php
return !empty($email) &&
    preg_match(Tools::cleanNonUnicodeSupport('/^[a-z\p{L}0-9!#$%&\'*+\/=?^`{}|~_-]+[.a-z\p{L}0-9!#$%&\'*+\/=?^`{}|~_-]*@[a-z\p{L}0-9]+(?:[.]?[_a-z\p{L}0-9-])*\.[a-z\p{L}0-9]+$/ui'), $email) &&
    Swift_Validate::email($email);
```

But in any case I think that Swift validation should exist because it's the class responsible for sending mail.


Regards!

**Comment by PierreRambaud** [comment]
If we use the Swift_Validate class, the preg_match is useless. 
At least but not last, if they don't want to patch the compatible 5.6 version we maybe need to fork the Swift mail sender to be sure it is compatible with a real RFC, like something wasn't created in 2000...
We can't continue to use deprecated and outdated libraries.

**Comment by Rolige** [comment]
@PierreRambaud I agree with you that it is quite obsolete, it should have been updated quite some time ago, at least in the begin of PS 1.7, there is an alternative right now which will be compatible even when the Swiftmailer its updated, the new system use a dependency called [EmailValidator](https://github.com/egulias/EmailValidator), just include this in the composer and then the email validation could be...

```php
public static function isEmail($email)
{
    $validator = new Egulias\EmailValidator\EmailValidator();

    return !empty($email) &&
        $validator->isValid($email, new Egulias\EmailValidator\Validation\RFCValidation());
}
```

This will be completely modern, updated and will not cause any conflict on the moment the Swift class is upgraded.

Regards!

**Comment by PierreRambaud** [comment]
Otherwise we should plan to remove the PHP5.6 support and be focused on new technologies. If we drop this one, we will be able to use the latest version of SwiftMailer. (and many other libraries :P)

**Comment by Rolige** [comment]
@PierreRambaud 
New versions of Magento are compatible only with php 7.1.3+, I think that PrestaShop had to removed its compatibility with php 5.x since its version 1.7+, in fact PrestaShop 1.7.x with php 5.6 in a shared hosting its too slow, but it significantly improves its performance with php 7.1+

**Comment by PierreRambaud** [comment]
@Rolige We create an issue to list all dependencies that are not compatible with PHP7.3, We're thinking about removing php5.x compatibility and support.

**Comment by PierreRambaud** [comment]
Since we are planning to remove php 5.6 support, we will be able to update to the latest version of swift mailer :)

**Comment by matks** [comment]
We upgrade Swiftmailer to v6.2.3.

So now I guess we can modify the code to
```
return !empty($email) && Swift_Validate::email($email);
```

Wdyt ?

**Comment by PierreRambaud** [comment]
@matks We should use the dedicated package which is recommended by SwiftMailer:
https://github.com/swiftmailer/swiftmailer/blob/6484964bfa7ce98cb3683726963e4dee0ac62aac/CHANGES#L89

**Comment by Rolige** [comment]
@PierreRambaud Also the most common library for email validation can be integrated:
https://github.com/egulias/EmailValidator
Even this library is recommended by Symfony.

**Pull request closed without merging**
