### PR TITLE
Remove inline style from default datas

### LINKED ISSUE #21441: Remove inline style on default datas descriptions
#### Is your feature request related to a problem?

On clean install of PS, default datas descriptions contains inline style.
For example: `<span style="font-size:10pt;font-style:normal;">...</span>`

#### Describe the solution you'd like

Please remove inline style on default datas :

- short description of products
- long description of products
- description of categories / manufacturers / suppliers

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove inline style from default datas : product/category/manufacturer descriptions
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21441
| How to test?  | Check if inline style has been correctly removed
| Sponsor company | @Creabilis

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21822)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
How does it look now ?

**Review by Progi1984 — APPROVED** [review]

**Comment by micka-fdz** [comment]
@NeOMakinG 

1. Go to https://demo.prestashop.com/
2. Go to product / category / manufacturer page
2. Remove inline style from descriptions

The only difference is about font size and it doesn't shock me.

**Comment by khouloudbelguith** [comment]
Hi @micka-fdz,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1Uwio25StWKcgcxesXm3HcqVl8uqnYKEf/view?usp=sharing

Thanks!

**Comment by PululuK** [comment]
Thanks @micka-fdz

**Pull request merged**
