### PR TITLE
Fix error when change product qty in cart

### LINKED ISSUE #31833: Cart product with quantity greater than stock available doesn't allow to reduce it
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In the cart page, if you have a product with quantity greater than the established in stock available a error shows up stating:
'product x' is no longer available in this quantity. You cannot proceed with your order until the quantity is adjusted.

If you proceed to reduce the quantity in the quantity input, the cart will not allow it showing :
The available purchase order quantity for this product is 'x'.
And reverts back the previous quantity value

This always happens with products without attribute, if the product is with attribute, it will allow the reduction of quantity only if the change is less or equal than the stock available.

### Expected behavior

When the quantity of a product in the cart is less than the available quantity and the user presses the "Order" button in the cart, a message is displayed: "The available quantity for the order of this product is X" and the product quantity is set to the quantity available X.

If the user presses the up key or types a quantity greater than the available quantity, the quantity is reset to the available quantity.
if the user presses the down key or types a quantity equal to or less than the available quantity, the quantity value is not updated.

### Steps to reproduce

With the demo store:

1. Go to the product 7 page ('Mug The adventure begins') and add 5 items to your cart
2. In the admin modify the stock of this product in such a way that only 3 are left available
3. Back in the front go to the cart page and you will see the error message, and the product with the quantity of 5 that you requested
4. Try to reduce the quantity, is not possible

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix error when change product qty in cart
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31833 
| Fixed ticket?     | Fixes #31833 
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/29016
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by lartist — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @mflasquin 

I have checked your PR. I found this issue which is not fixed and is not present on PS8.0.3

**Issue** : The Proceed to checkout button is enabled and the error message is not displayed when decreasing the quantity and then clicking on the button

1. On BO > Check that the product has a quantity 
2. Go to FO > Add the product to the cart and add 5 (for example) items to it
3. Come back to BO > Edit the product > Change the quantity to 3 (for example) 
4. Come back to FO and refresh the page 
5. See that there is a message error : OK
6. Decrease the quantity with a message error similar to `The available purchase order quantity for this product is 3`. 
7. See error > The Proceed to checkout button is enabled : **NOK**
8. Put the quantity equal to 3 with no message error : OK
9. Increase again the quantity > The Proceed to checkout button is enabled again : **NOK**
10. Click on the button > There is no message error and it's possible to click always on the button : **NOK**

**With PR : NOK** :x: 

image

https://user-images.githubusercontent.com/92912932/230343086-74476058-68d6-4fd4-a7df-119c166a35ba.mp4


**Without PR PS8.0.3 : OK** :heavy_check_mark: 

image

https://user-images.githubusercontent.com/92912932/230343858-bb6af057-6f29-45ee-8632-7f3f1dbc1053.mp4


I launched the automatic tests and it's failed on FO with this error `Run npm run test:functional:FO:01-03` 
https://github.com/HanaRebaiQA/testing_pr/actions/runs/4627005701/jobs/8184407162

ping @PrestaShop/qa-automation I think it's not related to this PR. What do you think ?

@mflasquin Could you please check it ?

Thank You!

**Comment by nesrineabdmouleh** [comment]
Hello @HanaRebaiQA 

Yes the errors are not related to UI tests, you should rebase your branch and relaunch all jobs :)

**Review by lartist — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello, 

Thanks @nesrineabdmouleh for your feedback :) 
I have checked again this PR. The issue is well fixed. Thanks @mflasquin for the fix :) 

- Check with multistore : OK
- Check the original issue : OK
- Check the mentioned issue : OK
- Check with different product types (Standard, Combinations, Pack) : OK
- Check with different PHP versions (PHP7.3, PHP 8.1) : OK 

image

https://user-images.githubusercontent.com/92912932/230412696-e76424d3-a06f-4655-a73f-a97741a400e6.mp4

So, it's QA :heavy_check_mark: 

Thank You!

**Comment by mflasquin** [comment]
Thanks @HanaRebaiQA

**Pull request merged**
