### PR TITLE
Fix prestashop:linter:security-annotation find-missing failed because of non existant methods

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix prestashop:linter:security-annotation find-missing failed because of non existant methods / class
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/nesrineabdmouleh/testing_pr/actions/runs/4107533089
| Fixed ticket?     | -
| Related PRs       | -
| Sponsor company   | [@PrestashopCorp](https://github.com/PrestaShopCorp)

### CODE REVIEW

**Review by lartist — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/4101868300

No need QA. There is nothing to test.

**Review by matthieu-rolland — DISMISSED** [review]

**Review by eternoendless — APPROVED** [review]
Weird but OK

**Review by lartist — APPROVED** [review]

**Comment by boubkerbribri** [comment]
@nesrineabdmouleh can you check please why tests are failing for this one https://github.com/boubkerbribri/ga.tests.ui.pr/actions/runs/4105987881/jobs/7083623766

**Comment by boubkerbribri** [comment]
Tests are OK for this PR https://github.com/nesrineabdmouleh/testing_pr/actions/runs/4107533089

@PrestaShop/qa-functional 
Do we need to perform more tests or we could add QA heavy_check_mark ?

**Comment by Robin-Fischer-PS** [comment]
Hi,

No need for more QA, thanks for the ping :)

**Pull request merged**
