### PR TITLE
Add js-doc on some data classes

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x 
| Description?      | Add js-doc on data classes : Cart rule, Catalog price rule, Category, cms page, contact, customer, delivery options and employee
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25178)

### CODE REVIEW

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
It's maybe time to use TypeScript instead, it will help you a lot ;)

**Comment by boubkerbribri** [comment]
> It's maybe time to use TypeScript instead, it will help you a lot ;)

Yes, we need to find time for that, it's on our `TODO` list.
But I think even with typescript, we need to add js-doc to generate markdown files that describe each function and how to use it on tests (it will help to have more contributions in the future).

**Review by NeOMakinG — DISMISSED** [review]

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by Progi1984** [comment]
## WAIT FOR 1780 RELEASE

**Comment by Progi1984** [comment]
@boubkerbribri Could you rebase your PR, please ?

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @boubkerbribri

**Pull request merged**
