### PR TITLE
Update configuration.xml

### PR DESCRIPTION
**Pull request by MacRoy**
Translated to Swedish

### CODE REVIEW

**Comment by AlexEven** [comment]
Hello MacRoy, 

Returns are translated as "retur" in Swedish, and examples show RE as a prefix, why using RS?

Sames goes for delivery slips, I see it translated as "leverans-slip" (or "Följesedel" for that matter, it would need to be harmonized it seems).
Why using LS and not LE or FO? 

Customer service is translated "Kundtjänst" in the software, please kindly harmonize.

Again, we thank you for suggesting translations here, it helps us a lot, but it would help even more if the translations are matching what we have in Crowdin. It's important it should be harmonized.

Thank you!

**Comment by MacRoy** [comment]
Hi Alex!

I agree with you completely! Those who are doing translations should have both knowledge and experience in this area, especially when it comes to terms like these.

The reason I have not committed myself all of these responsibilities because I long ago made a request to this effect to a certain person at PrestaShop, but never received a reply! Additionally, it takes a terribly long time to get those translations as was done approved. I have worked many years with translation into various companies within the right technology and specialist areas, so I have some experience and have a good understanding of E-trade translations, too.

Returns = Returer
Delivery slip = Följesedel
Customer service = kundservice

Just as an example!

Best regards
MacRoy


17 nov 2015 kl. 17:29 skrev Alex Even <notifications@github.com>:

**Comment by firstred** [comment]
Looks like it is still worth it to merge this pull request!

**Review by firstred — APPROVED** [review]

**Comment by aleeks** [comment]
Hello, end about develop ?

**Comment by xBorderie** [comment]
@aleeks If it's good enough for 1.6.1.x, I think it is too for develop! :)

**Comment by aleeks** [comment]
Hello, this PR will be closed.
Your PR has been duplicated with @AlexEven 's remark. It's now into `develop` & `1.6.1.x`
Thank for your contribution.

**Pull request closed without merging**
