### PR TITLE
FO : Remove useless validation

### LINKED ISSUE #28648: Order not validated when notification request is sent
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Payment gateways with redirection usually use a background request from the server to notify the payment result.

When geolocation is enabled, if this request is located in a country which is not enabled, the order is not validated because of this validation:

https://github.com/PrestaShop/PrestaShop/blob/dd2aa84c0a8588beaa7df509604f88d5b25a043d/classes/PaymentModule.php#L367-L371

### Expected behavior

The order should not throw an error because of this.

Possible solutions:

- Remove this validation
- Get the country from the order address, not from the context

### Steps to reproduce

This issue is only reproducible under some circumstances, which can not be replicated. So this is a "conceptual" test.

1. Disable "UK" country from the countries.
image
2. Enable geolocation (download database, etc.).
3. Make an order from another country like ES or FR.
4. Use a payment gateway with redirection like Redsys, for example.
5. When you pay, you will get a request to _/module/redsys/controller/payment_. 
6. This request is sent by a server located in UK. 

The request doesn't have context, so geolocation sets the country in the context according to the IP. 
It's located in the UK, so the order is not validated because this country is not enabled.

---
1. Install this module [dummypayment.zip](https://github.com/PrestaShop/PrestaShop/files/8927022/dummypayment.zip)
2. Enable Geolocation
3. Disable a country
4. Make an order paying with "Dummy payment"
5. You will get an URL to confirm the payment. Open this URL in an incognito tab with a VPN from the country disabled in the step 3
6. Error

### PrestaShop version(s) where the bug happened

1.7.8.6

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by idnovate**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Check ticket
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check ticket
| Fixed ticket?     | Fixes #28648
| Sponsor company   | idnovate.com

### CODE REVIEW

**Comment by kpodemski** [comment]
@idnovate I think we were close to accepting such a solution, but then we thought about context switching in the middle. Don't you think that that was the purpose of the original code? To make sure that the context country stays the same?

**Comment by idnovate** [comment]
> @idnovate I think we were close to accepting such a solution, but then we thought about context switching in the middle. Don't you think that that was the purpose of the original code? To make sure that the context country stays the same?

The problem is that you are validating the country from the IPN request. Which is the point of this?

**Comment by kpodemski** [comment]
I'll allow myself to ping the payment module expert to consult this one 🎉 

cc @Matt75

**Comment by idnovate** [comment]
The point is that if a customer located in a valid country makes a payment and the IPN request is located in a blocked country, the order is not validated.

I understand that the validation should be done only to the customer location.

**Comment by Matt75** [comment]
In fact the context initialization is hard topic and not very documented.

The Core use internally the Context in several places and it should be properly initialized to avoid issue.

When the IPN request is received, my recommendation to avoid issue with context is to load the Cart from database then initialize the context using cart data.

Something like that:

https://github.com/PrestaShop/PrestaShop/blob/8.1.0/src/Adapter/ContextStateManager.php

Note: for retrocompatibility, I created my own ContextStateManager based on the Core one for previous PrestaShop versions.

```
    /**
     * @param \PrestaShop\PrestaShop\Adapter\ContextStateManager $contextStateManager
     * @param \Cart $cart
     *
     * @throws \PrestaShopDatabaseException
     * @throws \PrestaShopException
     */
    protected function setCartContext(ContextStateManager $contextStateManager, Cart $cart)
    {
        $contextStateManager
            ->saveCurrentContext()
            ->setCart($cart)
            ->setCustomer(new \Customer($cart->id_customer))
            ->setCurrency(new \Currency($cart->id_currency))
            ->setLanguage($this->getAssociatedLanguage($cart))
            ->setCountry($this->getCartTaxCountry($cart))
            ->setShop(new \Shop($cart->id_shop))
        ;
    }

    /**
     * @param \Cart $cart
     *
     * @return \Country
     *
     * @throws \PrestaShopDatabaseException
     * @throws \PrestaShopException
     */
    protected function getCartTaxCountry(Cart $cart)
    {
        $taxAddressType = \Configuration::get('PS_TAX_ADDRESS_TYPE');
        $taxAddressId = property_exists($cart, $taxAddressType) ? $cart->{$taxAddressType} : $cart->id_address_delivery;
        $taxAddress = new \Address($taxAddressId);

        return new \Country($taxAddress->id_country);
    }

    /**
     * Returns the language related to the cart or the default one if it doesn't exist
     *
     * @param \Cart $cart
     *
     * @return \Language
     *
     * @throws \PrestaShopDatabaseException
     * @throws \PrestaShopException
     */
    protected function getAssociatedLanguage(Cart $cart)
    {
        if (null !== $this->associatedLanguage) {
            return $this->associatedLanguage;
        }

        $this->associatedLanguage = new \Language($cart->id_lang);

        if (!\Validate::isLoadedObject($this->associatedLanguage)) {
            $this->associatedLanguage = new \Language((int) \Configuration::get('PS_LANG_DEFAULT'));
        }

        return $this->associatedLanguage;
    }
```

**Comment by idnovate** [comment]
In fact, I just removed this validation `if (!$this->context->country->active) {`. The other lines removed are not used any more once this validation is removed.

The context is working correctly.

**Comment by Matt75** [comment]
The context is also used to load language to generate invoice PDF, sending email etc...
And others stuffs deeply linked and executed synchronously during the same request...
So the Context initialization could have side affect for different features

**Comment by idnovate** [comment]
But the commit doesn't affect this.

**Pull request closed without merging**
