### PR TITLE
Fix [BO- Stores page] Sort by post code not working

### LINKED ISSUE #21038: [BO- Stores page] Sort by post code not working
#### Describe the bug

When sorting by post code, the result is incorrect

#### Expected behavior

Should be well sorted

#### Steps to Reproduce

1. Go to BO -> shop parameters -> Contact -> Stores
2. Click on column post code to sort by
3.Check that the sort is incorrect

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
image

#### Additional information

* PrestaShop version: branch 1.7.7.x
* PHP version: php 7.2

### PR DESCRIPTION
**Pull request by PululuK**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | In BO > Stroe page sort by post code not working, when sorting by post code, the result is incorrect.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/21038
| How to test?  | See https://github.com/PrestaShop/PrestaShop/issues/21038

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21048)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PululuK @kpodemski You unlocked the badge "Identical PR" :rofl:.

**Comment by kpodemski** [comment]
@Progi1984 @PululuK yeah 🤦 I noted some PRs to work with yesterday and I believe I did that before @PululuK PR so yeah, it happens 🙈

**Comment by Progi1984** [comment]
> @Progi1984 @PululuK yeah facepalm I noted some PRs to work with yesterday and I believe I did that before @PululuK PR so yeah, it happens see_no_evil

Don't hesitate to discuss on Slack for synchronizing your WIP ;)

**Review by PierreRambaud — APPROVED** [review]

**Comment by ngodefroy** [comment]
TEST OK
https://drive.google.com/file/d/1BiCzg9lt_TAgn8d20n-JNl9Ql2OesT3Z/view

Thank you @PululuK & @boubkerbribri

**Comment by matks** [comment]
Thank you @PululuK

**Pull request merged**
