### PR TITLE
[+] BO : Added a list of unpaid and partially paid invoices

### PR DESCRIPTION
**Pull request by PhpMadman**
[_] BO : Added Firstname, Lastname and Unpaid amount to Unpaid invoices …
[-] BO : Design fixes to Unpaid invoices
[-] BO : Added support for multiple payments on one invoice to Unpaid invoices
[_] BO : Filter update for unpaid invoices …
[+] BO : Export unpaid invoices list as csv
[*] BO : More userfriendly unpaid invoices list
[-] BO : Friendly text fix for unpaid invoices VIEW button

### CODE REVIEW

**Comment by jeromenadaud** [comment]
HI, Thank you for reporting,

I think we can discuss this feature with our @PrestaShop/prestashop-product-managers 
Best regards.

**Comment by jeromenadaud** [comment]
Hi,

It 's a nice have future, but I have some questions, How did you get unpaid invoice ? After a refund from a credit cart payment ? Or something like this ?

Best regards.

**Comment by PhpMadman** [comment]
Hi.

I work for a B2B company so, all of our invoices are unpaid when we send the orders.
I have the Universal Payment Module from https://github.com/prestalab/universalpay installed.
It does not any payment to the orders.
So we have to manually add payment when we get paid aprox 30days later...

**Comment by jeromenadaud** [comment]
Hi,

Well, in this case, it will be great to add this feature into PrestaShop by a B2B Module, but not natively.

Best regards.

**Comment by PhpMadman** [comment]
Okey. Thanks for at lest taking a decision on this pull request.
I'll write a module for this when ever I get the time...

**Comment by jeromenadaud** [comment]
yes, it will be great, you can also sell it on PrestaShop Marketplace .

**Pull request closed without merging**
