### PR TITLE
Complete RTL styles for new-theme and new localization structure based on iso code

### PR DESCRIPTION
**Pull request by hafkhami**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | RTL
| Description?  | With this new PR, Prestashop new-theme was completely matched with RTL languages. Also, a new proposal structure was created based on the Iso Code to resolve languages differences. [for example font]. It should be noted that this method was created by override the styles, which is better than the PrestaShop 1.6 method. [old method was separate style file for RTL]
| Type?         | new feature
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3436
| How to test?  | Just choose the language that is RTL like Persian or Arabic and open page with PrestaShop new-theme like Catalog or Stock Managements. [Make sure RTL is activated]

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks @hafkhami !
ping @AlexEven :)

**Comment by AliShareei** [comment]
hi @xBorderie @AlexEven 

we (Prestafa Team) create a forge Ticket for description about this. (edit first post here)
http://forge.prestashop.com/browse/BOOM-3436

**Comment by Danoosh** [comment]
@hafkhami @AliShareei @AlexEven

The RTL support by overriding css files is not new. we did it before in installer , FO and also BO by adding rtl.css file:
installer: https://github.com/PrestaShop/PrestaShop/pull/1521
FO and BO: https://github.com/PrestaShop/PrestaShop/pull/1551/files

Overriding fonts by adding an iso-code.css file is not new too. You can see admin controller initFooter method in pull 1551 (linked above).

Your code is very similar to my pull requests in 2014.

we suggested these methods for RTL Prestashop many times but there are many hidden problems that must be worked on it.

**Comment by AlexEven** [comment]
Thank you @hafkhami  for this pull-request!

@Danoosh - we are not looking for anything new, but merely for something that can work with PrestaShop 1.7. If you have some other method, please share it with everyone.
If there are hidden problems that you know of from your work on 1.6, maybe you can tell @hafkhami and @AliShareei so that we can improve this pull-request together. This is a starting point, and we need to build on top of this.

Thank you! :simple_smile:

**Comment by AliShareei** [comment]
hi @Danoosh , Thank you for your response And thanks for the previous PRs made by you.

There are a few points on this PR: 
- First, all of the new PrestaShop are compatible with RTL. We checked in Persian, Arabic, Hebrew and Urdu languages, there was no problem. There may be minor issues that can be solved in future PRs.

- Second, unfortunately, the method used in BO & FO is a separate file.This means more duplicate files and codes. I think the best way to styles is to override that. The separate file is suitable for twig and smarty files. I think the override solution is good, I do not see any problem. if have there problems we can fix together & future PRs.

- Third, Your proposed solution is suited by Iso Code. We also offer this structure like you. We tried to give it a structure and clean it up and use it. In this structure we have used it for Arabic and Persian languages. ( iso-ar dir and iso-fa dir) I did not write code for other languages because I was not familiar, but its structure is ready for other languages. for example Hebrew , Urdu , Malay , Kurdish, Pashto and others

- Finally, We are ready to adapt PrestaShop 1.7.x as soon as possible. But first we need to know what we are and what structure is supposed to be implemented. I think that if this structure is considered appropriate, we can continue to develop it.

This PR will technically tell us what it will be like.

Thank You.

**Comment by Danoosh** [comment]
@AlexEven There are different methods for make Prestashop fully RTL support. we are trying to list all of them and share it with you and others.
I just noticed that some of changes in this PR exist in Prestashop now and can't be added again (can be editted of course).
We are very glad that @hafkhami and @AliShareei joined us in RTL project but as you know these methods are old and this PR can't be merged based on the following.

@AliShareei 
1. Yes. Different versions have been RTL compatible by suggestions I gave to Kevin Granger ( @Shipow ) in past. There are some bugs that we are not allowed to fix by adding css file and this is a technical issue.

2. As I said earlier if you see the PR links I sent, this ability was provided earlier and it available to apply localizations using two seprate files or as a single file. Some codes need to be modified.

3. If we extend coordination between us, I will explain more. I just mentioned that these codes must be modified or removed or use previous codes but actually you rewrote them.

4. Of course we followed this from a long time ago. Otherwise current RTL localizations wouldn't be in PrestaShop.

Finally, we need share of knowledges and cooperation to optimize the localizations. We need to take steps forward and we should not turn back. I expect more cooperation from my friends Mr. Afkhami and Mr. Sharei since I'm familiar to current localizations well and it prevents doing the same thing again.

**Comment by AlexEven** [comment]
Thank you all for your comments! How can we proceed from there? Do we need to chat about it over a Skype or something?

Why not having only one CSS file, and add a class in the body to switch everything in RTL?
or have the language code in the body as well? and thus use such or such font for the language while still having one and only one stylesheet for RTL.

I leave it with @maximebiloe to continue the discussion, as it's out of my understanding :)

Thank you!

**Comment by AliShareei** [comment]
Thank you again @danoosh for your comment.

hi @AlexEven , @maximebiloe ,

The structure we offered to you on BO new-theme is exactly the same as the one you used in **Default** for FO.

 FO RTL for Default: https://github.com/PrestaShop/PrestaShop/blob/rtl/classes/controller/FrontController.php#L884

our Commit for BO new-theme: https://github.com/PrestaShop/PrestaShop/pull/8110/files#diff-d373723286a172a4ca3d76c4858f565bR2681

So there should not be a problem with this part, So we wrote just the same way as PrestaShop.
 to make it similar, name theme-rtl.css can be changed to rtl.css like FO. 
_[PLEASE change name if approved this PR]_

About your questions @AlexEven : 

> **Why not having only one CSS file, and add a class in the body to switch everything in RTL?
or have the language code in the body as well? and thus use such or such font for the language while still having one and only one stylesheet for RTL.**

_This means that **RTL** and **LTR** are just one file with specified class?_ 
It is possible but not the right thing. 

_This means that **RTL** and **iso_code** are just one file?_

Using by iso_code is not necessary. But this is for all languages include LTR, not just for the RTL.  Since the appearance of the management section is important, and shop managers spend their time there. We suggested that the iso_code file be placed in the admin area so that local codes can be written for greater attractiveness and better user experience.

According to this, it's not just RTL, we offer it for all languages. Of course, it is not required, and if there is no file, then it will not be called. 
Meanwhile, the separation of files makes it easier to manage and maintain the code and prevent future complexity in the future.

**Finally, to summarize:**
This PR contains ~3300 lines of code, which is almost all CSS for BO new-theme for localized & RTL.
A few lines of PHP code  are similar to those of the PrestaShop structure in FO. The iso_code structure is also suggested and the decision is with you. we only prepared for Persian and Arabic languages.

If there was another question or need more discussion, I'm here.

Thanks All

**Comment by Danoosh** [comment]
@AlexEven 

> Thank you all for your comments! How can we proceed from there? Do we need to chat about it over a Skype or something?
> Why not having only one CSS file, and add a class in the body to switch everything in RTL?
> or have the language code in the body as well? and thus use such or such font for the language while still having one and only one stylesheet for RTL.

The problem is not about number of css files in RTL languages. It's not even about suggested method. The reason is that these files are static where default theme and CSS files are dynamic and they might be updated frequently. This is not a permanent method.

Actually, if we were allowed to make PrestaShop RTLed by adding some CSS files, we would have done this on 2014 for PrestaShop 1.6 and we had RTLed PrestaShop 1.7 some monthes ago...

**Comment by AlexEven** [comment]
Hi there!
Thanks again @hafkhami for the PR and @AliShareei for the involvement! 
As explained on the [RTL Trello board](https://trello.com/b/szTruf2c/prestashop-rtl), we've chosen another method to implement RTL in PrestaShop.
It's now all merged on this same RTL branch, so that you can test it and let us know if you have some feedback regarding what has been done. I'll share a package on the Trello board too, so that everyone can test it.
Thank you, and please tell us if you have any question!
Cheers,

**Pull request closed without merging**
