### PR TITLE
[-] BO: Imap emails import connector bugs, remake of #PSCSX-5847

### PR DESCRIPTION
**Pull request by xGouley**
Report of https://github.com/PrestaShop/PrestaShop/pull/3323 on develop branch.

### CODE REVIEW

**Comment by xGouley** [comment]
Report of 1.6.1.x PR, To be tested on develop before to merge

**Comment by inetbiz** [comment]
@xGouley any thoughts about language definitions? I see you have english in the error message responses.

**Comment by xGouley** [comment]
Right, good point! I will add Tools::displayError, and we need to add these messages into the errors catalog.

**Comment by xBorderie** [comment]
@vincentbz Could please give your opinion about this. Forge ticket is http://forge.prestashop.com/browse/PSCSX-5847 Thanks!

**Comment by vincentbz** [comment]
If tests are ok, we can merge it on the 1.6.1.5.

Thanks :)

**Pull request merged**
