### PR TITLE
Remove useless variable from FromController::init()

### PR DESCRIPTION
**Pull request by ksaandev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove useless variable from FromController::init()
| Type?         | refacto
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

My IDE tells me this variable is unused

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19391)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
You're IDE says the truth :sweat_smile:

**Comment by ksaandev** [comment]
> You're IDE says the truth 😅

\o/

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
Thank you @ksaandev

**Comment by matks** [comment]
No need for QA I think

**Pull request merged**
