### PR TITLE
Update 2 old links to PrestaShop site and github on BO login page

### PR DESCRIPTION
**Pull request by Uthanien**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update 2 old links  <br> I run in local machine and use the new links.
| Type?             |  refacto
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?     |  no
| How to test?      | Run in local machine
| UI Tests          | https://github.com/Uthanien/ga.tests.ui.pr/actions/runs/6832322399
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matks — COMMENTED** [review]
This PR looks good 👍 but it is a draft so we can't validate it yet

**Comment by Uthanien** [comment]
> This PR looks good 👍 but it is a draft so we can't validate it yet

I update the PR.

grettings

**Review by nicosomb — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by boherm** [comment]
LGTM, thanks @Uthanien for your PR!

**Review by matks — APPROVED** [review]
I might be bold but I think we don't need to disturb the QA team to verify that 😄

**Comment by matks** [comment]
Thank you @Uthanien

**Pull request merged**
