### PR TITLE
When the thread refers to a product, the generated link are wrong

### LINKED ISSUE #19192: Product link on customer thread don't link properlly
#### Describe the bug

When i click on product link on customer thread, the link gos to product list instead of the product details.

#### Expected behavior

Open product detail backoffice page

#### Steps to Reproduce

1- Add a customer question from order history page, for a purchased product.
2- In backoffice, open customer service and open the recent thread.
3- Click on product link

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.6.5
* PHP version: N/A

### PR DESCRIPTION
**Pull request by runningz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In customer service, when the thread refers to a product, the genereted link are wrong. I fix this for PrestaShop 1.7.6.5
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19192
| How to test?  | If you add a question from Order History about a purchased product, the product link added to customer service message are wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19191)

### CODE REVIEW

**Comment by Progi1984** [comment]
@runningz Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Comment by runningz** [comment]
Done, how i relate with the PR?

Un saludo,

Raúl Rubio

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @runningz !

**Comment by Progi1984** [comment]
Thanks @runningz

**Pull request merged**
