### PR TITLE
Fix module install if there is only 1 position available

### LINKED ISSUE #25113: Module install fail if there is only 1 position available
#### Describe the bug

Module install fail if there is only 1 position available

#### Expected behavior

Module install work even if there is only 1 position available

#### Steps to Reproduce

1. Make a clean install
2. Remove all modules
3. Install a new one 
4. Module doesn't install

#### Additional information

* PrestaShop version: 1.7.7.4
* PHP version: 7.3

PR : https://github.com/PrestaShop/PrestaShop/pull/25110

### PR DESCRIPTION
**Pull request by Jeremy-FT**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | fix module install if there is only 1 position available
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/25113
| How to test?      | Make a clean install, remove all modules, install a new one => Module doesn't install
| Possible impacts? | Modules positions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25110)

### CODE REVIEW

**Comment by Progi1984** [comment]
@Jeremy-FT Could you open an issue ? That permits to our QA team to check it. Thanks

**Comment by Jeremy-FT** [comment]
> @Jeremy-FT Could you open an issue ? That permits to our QA team to check it. Thanks

Done https://github.com/PrestaShop/PrestaShop/issues/25113

**Comment by atomiix** [comment]
@Jeremy-FT I'm wondering if the same should also be applied later: https://github.com/PrestaShop/PrestaShop/pull/25110/files#diff-db4a6f0d64d78260ad0a05d45662963e591dd46009ae2eedde824930f0f368a2R2036-R2047 ? WDYT?

**Comment by Jeremy-FT** [comment]
> @Jeremy-FT I'm wondering if the same should also be applied later: https://github.com/PrestaShop/PrestaShop/pull/25110/files#diff-db4a6f0d64d78260ad0a05d45662963e591dd46009ae2eedde824930f0f368a2R2036-R2047 ? WDYT?

Yeah, it seems that all `return false` should be replaced by `continue`

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
As far as I know, the QA team is not able to reproduce the issue.
More, I'm not sure it's the right way to fix your problem.
Wanted to change all `return false` (as you said in comment) will result that this method will only be able to `return true`, I'm afraid we can't accept your change because I don't understand what you are trying to do and why.
We need more information and an easy way to reproduce it in order to accept it.

**Comment by Jeremy-FT** [comment]
> As far as I know, the QA team is not able to reproduce the issue.
> More, I'm not sure it's the right way to fix your problem.
> Wanted to change all `return false` (as you said in comment) will result that this method will only be able to `return true`, I'm afraid we can't accept your change because I don't understand what you are trying to do and why.
> We need more information and an easy way to reproduce it in order to accept it.

The function updatePosition() should not break module install and therefore should always return true IMHO. It maybe not the best way to fix this issue but it's better than breaking module install don't you think ?

The issue can be reproduced https://github.com/PrestaShop/PrestaShop/issues/25113#issuecomment-870441932

**Comment by PierreRambaud** [comment]
I'm sorry @Jeremy-FT I have to close your pull request, the issue hasn't been reproduced, we will not able to test your pull request properly.
Kind regards

**Pull request closed without merging**
