### PR TITLE
Add new method to generate RTL stylesheets

### PR DESCRIPTION
**Pull request by ramtin2025**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | "rtl"
| Description?  | Add new method to generate RTL stylesheets
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Select RTL language (e.g persian, arabic) in PrestaShop installer.

This PR contains:
- Add "installRtlStylesheets" method in Language class

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @ramtin2025,

Can you use PSR-2 standards and resolve conflicts, please?

Thanks

**Comment by AlexEven** [comment]
Hello @ramtin2025, 

Thanks for adapting your code to the PSR-2 standards!
However, we still need the commit names (Update Language.php etc) to follow our commit standards.
You should squash your commits and then we'll be able to merge it (and the #8245 at the same time).

Thank you!

**Comment by Danoosh** [comment]
@AlexEven You can merge these PRs now.

**Review by maximebiloe — APPROVED** [review]

**Comment by maximebiloe** [comment]
Thank you @ramtin2025

**Pull request merged**
