### PR TITLE
Fix access when adding attribute value

### PR DESCRIPTION
**Pull request by antho-girard**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Fixes access when adding a new Attribute value in BO. Comparison was not correct. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1012 |
| How to test? | In BO, Catalog > Attributes & Features > Attributes tab > "Add a new value". Enter a value for one of the existing features and Save. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you Anthony!

**Comment by vincentbz** [comment]
status : 'QA approved'
Tested and it works, thanks !

**Comment by mickaelandrieu** [comment]
status: 'PM approved'

**Comment by maximebiloe** [comment]
Thanks!

**Pull request merged**
