### PR TITLE
[-] FO: Fix #PSCSX-6504 / Productcomments and new global.js stars are…

### PR DESCRIPTION
**Pull request by prestamodule**
… not display correctly

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR.

"#criterions_list .star" is very specific, don't you want to add a new class like for instance and add it in https://github.com/PrestaShop/PrestaShop/blob/develop/themes/default-bootstrap/modules/productcomments/productcomments_reviews.tpl

Regards

**Comment by PrestaEdit** [comment]
Hi @gRoussac ,

Just added a class .not_uniform to the star and do a uniform.not() on this class. As this, we can use the class in an another place too ;-)

**Comment by gRoussac** [comment]
:rocket:

**Comment by tchauviere** [comment]
:+1:

**Comment by tchauviere** [comment]
Hi @prestamodule,

Thanks for your contribution, your PR is now merged.

Best regards,

**Pull request merged**
