### PR TITLE
Check the created customer in the front office and delete customer with both mode

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows to check the created customer in the front office and delete customer with both mode
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | TEST_PATH=full/09_customer/customer_settings/* npm run specific-test -- --URL=FrontOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9124)

### CODE REVIEW

**Comment by fouratachour** [comment]
Hello @marionf 
This PR has been rebased
Best regard,

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
@fouratachour Can you rebase please?
@fatmaBouchekoua Can you revalidate after the rebase please?

**Comment by fouratachour** [comment]
Hello @PierreRambaud 
This PR has been rebased
Best regard,

**Comment by PierreRambaud** [comment]
Hi, This PR needs to be rebased again due to #8827  :)

**Comment by fouratachour** [comment]
Hello @PierreRambaud 
Done .

**Comment by PierreRambaud** [comment]
Need rebase again cos of dependencies between your PR :(

**Comment by fouratachour** [comment]
Hello @PierreRambaud 
This PR has been rebased
Best regard,

**Comment by PierreRambaud** [comment]
@fatmaBouchekoua for review and @marionf for QA please? :)

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Need rebase due to a recent merge. Thinking you must do something about this, like cut `common_client.js`.

**Review by mbadrani — APPROVED** [review]
The Functional scenario has been reviewed by Fourat

**Comment by fatmaBouchekoua** [comment]
@mbadrani this PR is ready to be merged

**Pull request merged**
