### PR TITLE
nginx.conf bugfix frontend showing 404 and stuff

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Try to build Prestashop container with and without that patch.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13051)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hey thanks for your contribution.
Can you tell us more please ? Which container are you building? 
I'm not able to reproduce any 404 without your patch.

**Comment by ghost** [comment]
Hello. I built Alpine container with nginx 1.14.2 .

Admin worked all ok. frontend reachable but all pages except index were returning page not found (through prestashop). Including but not only : product category, product detail, etc..

I added that `location` stuff and it fixed it. Now most of page works.

**Comment by PierreRambaud** [comment]
Could you provide me your Dockerfile which I'll be able to reproduce? :)

**Comment by ghost** [comment]
```
FROM alpine

RUN mkdir -p /usr/src/app 
RUN adduser app -D -h /usr/src/app

RUN apk update
RUN apk add nginx supervisor sudo mysql-client bash
RUN apk search -qe 'php7-*' | grep -vE 'apache|ssh|snmp|magick' | xargs apk add

RUN mkdir -p /run/nginx /var/log/supervisor /etc/supervisor.d

RUN mkdir /run/app && chown app:app /run/app && chmod 750 /run/app

RUN chown app:app /usr/src/app

RUN adduser nginx app

VOLUME /usr/src/app
WORKDIR /usr/src/app

RUN rm -f /etc/php7/php-fpm.d/www.conf
COPY etc/php-fpm.conf /etc/php7/php-fpm.d/www.conf

RUN rm -f /etc/nginx/conf.d/default.conf
COPY etc/nginx.conf /etc/nginx/conf.d

COPY etc/supervisor.ini /etc/supervisor.d/app.ini

COPY bootstrap /
RUN chmod a=,u=rx /bootstrap

ENTRYPOINT /bootstrap && /usr/bin/supervisord
```

**Comment by PierreRambaud** [comment]
I'm still not able to reproduce, can you show me what kind of request are going in 404 after a fresh install?
(Screenshot from chrome/firefox with developper mode on network tab could be cool :smiley: )

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@volp1s : @PierreRambaud don't reproduce the bug. Have you a scenario test ?

**Comment by matks** [comment]
It seems this PR got stale, so I close it.

If you come back feel free to open it again 😉  thanks for the contribution

**Pull request closed without merging**
