### PR TITLE
Remove _isPresent() in PrestaShopLogger

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in PrestaShopLogger
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `PrestaShopLogger::_isPresent()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26312)

### CODE REVIEW

**Review by tegbessou — DISMISSED** [review]
Thanks for the PR! LGTM

**Comment by PierreRambaud** [comment]
Look like you mixed it with #26322 :sweat_smile:

**Comment by PrestaEdit** [comment]
Argh. I've seen it but note sure, ... Could you say me if I need to revert the commit or try something as clear/clean it ?

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Could you remove the change in `classes/shop/Shop.php` as it is not relative to the PR ?

**Comment by PrestaEdit** [comment]
As my previous ask, maybe you can answer to it in order to : "Could you say me if I need to revert the commit or try something as clear/clean it ?"

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaEdit Thanks

@PrestaShop/qa-functional Checked and no more any uses in BackOffice. The removed method has already a replacement.

**Review by atomiix — APPROVED** [review]

**Comment by atomiix** [comment]
Thanks @prestamodule!

**Pull request merged**
