### PR TITLE
Removal of unnecessary comparison

### PR DESCRIPTION
**Pull request by dingedi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removal of unnecessary comparison. It is useless to check if value is not null it is done automatically in the other comparison with string
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | .
| Related PRs       | .
| How to test?      | .
| Possible impacts? | no impact.

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]
OK for me

**Comment by nicosomb** [comment]
@dingedi About the "how to test" section, maybe we can list the places where this function is used to check if it's still the same behavior.

**Comment by dingedi** [comment]
it is most used in objectmodel definitions for validation
I found it in 3 places:
- [classes/Employee.php](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Employee.php#L137) line 137
- [classes/Customer.php](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Customer.php#L210) line 210
- [classes/ProductDownload.php](https://github.com/PrestaShop/PrestaShop/blob/develop/classes/ProductDownload.php#L74) line 74

**Comment by dingedi** [comment]
I only found one place where it is used
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/module/ModuleGrid.php#L150

**Comment by florine2623** [comment]
@nicosomb , it seems like there's no big impact. Are the automated tests sufficient for this PR ?

**Comment by nicosomb** [comment]
I launched these tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/3683452642

**Review by florine2623 — APPROVED** [review]
Hello @nicosomb & @dingedi ,

On my end, I launched these : https://github.com/florine2623/testing_pr/actions/runs/3677531891/jobs/6219615056
They're all green.

It is QA ✅ then.
Thanks!

**Comment by nicosomb** [comment]
Thank you @dingedi !

**Pull request merged**
