### PR TITLE
Replace EN (US) by EN (UK) in UK localization pack

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x.
| Description?  | We were adding US English to the UK localization pack while we have a UK English language.
| Type?         | improvement
| Category?     | LO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a.
| How to test?  | Install UK pack, should add the EN (UK) language.

### CODE REVIEW

**Comment by aleeks** [comment]
@AlexEven need this in 1.7 ?

**Comment by aleeks** [comment]
Ok, done here: https://github.com/PrestaShop/PrestaShop/pull/7818

**Comment by Nobodaddy** [comment]
This is no milestone - this is nonsense! The translation for UK has never been finished and it doesn't look like it ever will be.

**Comment by maximebiloe** [comment]
Thank you @AlexEven

**Comment by AlexEven** [comment]
@Nobodaddy It doesn't hurt to try and make use of the EN-UK language we have on Crowdin. Let's hope it will motivate people to contribute to adapt the translation to the UK standards :)

**Comment by Nobodaddy** [comment]
@AlexEven No offense, Alex, but ... that's just a pipe dream, like this  __DE Austria__ and __DE Switzerland__! We didn't find translators for this project since more than 6 years -  which means, not even during PrestaShop best years as rising star in e-commerce. How can you expect this will happen now?

**Pull request merged**
