### PR TITLE
Assign ID prop to null instead of unset

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Assign ID prop to null instead of unset
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | CI must pass
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24581)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Hello @mvorisek can you explain why you submit this change?

I tried to look at the difference between `unsert($myvar);` and `$myvar = null;` and I found no clear advantage. `unset()` even seems to be slightly better as it might be faster and clear more memory.

https://stackoverflow.com/questions/13667137/the-difference-between-unset-and-null

Also I'll be honest: the `ObjectModel` class is a critical piece of PrestaShop in-house ORM and any change to it can have unexpected consequences. So without a clear way to validate the change is good, such as a big test net, I don't know if we can merge this.

**Comment by mvorisek** [comment]
Of course I can. I have build several ORM tools and as you can see, I almost never fix non-critical code :)

Please provide proof to your statement that it is faster.

Class properties are more or less hash tables. When class has a property defined on compile time, this named hashtable is allocated once per class. Any manipulation of these entries instead of (keeping it) and setting simply to null should be faster and safer (as otherwise isset is needed which supresses a typoes like `isset($m->idd)`).

**Comment by mvorisek** [comment]
And here numbers for you: https://3v4l.org/PjKCD

memory is the same as long as the original property name is used, otherwise: https://3v4l.org/oi8ID

**Comment by mvorisek** [comment]
@matks any other objections?

**Comment by mvorisek** [comment]
@PierreRambaud please review

**Comment by matks** [comment]
> @matks any other objections?

Hi @mvorisek the review will come, but pull request review is not 100% of the tasks we are focused on, and there's a huge quantity of Pull Requests to review. The 2 previous days have been heavy work to get PrestaShop 1.7.8.0 beta1 out, so delays like days or weeks are not unusual in PrestaShop open source project :) . No need to ping.

**Review by eternoendless — APPROVED** [review]
LGTM

**Comment by eternoendless** [comment]
The `unset` was clearly added to remove the value, not to free memory (https://github.com/PrestaShop/PrestaShop/commit/3cf12b934085968ad076024aff64eae41cf75173). The property is supposed to be there since it's declared in the class and not set dynamically. The null assignment seems to be appropriate.

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by eternoendless** [comment]
Closing and reopening to retrigger stuck tests

**Comment by Progi1984** [comment]
Thanks @mvorisek

**Pull request merged**
