### PR TITLE
[Need UI Kit update] Fixes switch input in Currency form to use toggle type

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR introduces new toggle type which is being used in Currency form.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/10190#issuecomment-462843632
| How to test?  | With this PR input Currency "Status" input should look like this https://prnt.sc/nd71ne

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13458)

### CODE REVIEW

**Comment by sarjon** [comment]
@matks as requested, although I think that spacing can be improved.

**Review by matks — APPROVED** [review]

**Comment by marionf** [comment]
It seems not related to this PR because I have the issue also on develop branch, but FYI when I edit or add a currency, the drop down is empty

capture d'écran_1441

I talked with @TristanLDD who will make a mockup :)

**Comment by TristanLDD** [comment]
The toogle button should have an indication of the current state on the right: 
Capture d’écran 2019-04-18 à 18 20 51

Also, make sure it's well aligned with the text. We will change the yellow color to light red, but this change will be done directly through the UI Kit so it will apply to every toggle in the BO.

**Comment by sarjon** [comment]
> The toogle button should have an indication of the current state on the right:

Does that mean when you toggle switch then text on the right has to toggle as well? Like "Yes/No"? If so, why this toggle is better than exiting switch input? :thinking:

**Comment by matks** [comment]
> > The toogle button should have an indication of the current state on the right:
> 
> Does that mean when you toggle switch then text on the right has to toggle as well? Like "Yes/No"? If so, why this toggle is better than exiting switch input? 🤔

I agree 😅 I usually see this kind of switch without text in mobile and web apps

**Comment by TristanLDD** [comment]
I still think it's not obvious enough for some user to have only the toggle with no information of what kind of action there is behind. Most of us are very used to this behavior, but remember that some of our users are complete beginners in using such an interface. 

Capture d’écran 2019-04-24 à 10 30 58

When you see it on mobile apps, there's always an indication of what the toogle is doing, like "enable data", here the indication is just "state". I hope you get my point.

**Comment by sarjon** [comment]
> I hope you get my point.

I don't, but let it be. Either way, to make text next to toggle input change, I think it must be done in UI Kit first, @matks am I right?

**Comment by matks** [comment]
Yes indeed

**Comment by sarjon** [comment]
> Yes indeed

Is there anyone who would like to do it? :smile:

**Comment by matks** [comment]
> > Yes indeed
> 
> Is there anyone who would like to do it? 😄

I created an issue for it https://github.com/PrestaShop/prestashop-ui-kit/issues/65 as this is going a bit too far for a 1.7.6 bugfix 😉
We'll do it for 1.7.7

**Comment by sarjon** [comment]
> We'll do it for 1.7.7

Will we? :trollface:

**Comment by matks** [comment]
> > We'll do it for 1.7.7
> 
> Will we? :trollface:

Once Orders pages are out 😄

**Comment by matks** [comment]
Hi @NeOMakinG, this PR is blocked because we need a UI Kit update. We never found enough time to do it 😢 do you think you can help us ?

**Comment by matks** [comment]
Might be related to https://github.com/PrestaShop/prestashop-ui-kit/pull/79

**Comment by matks** [comment]
This PR can be finished after https://github.com/PrestaShop/prestashop-ui-kit/pull/79 is merged and new UI Kit version is released

**Comment by NeOMakinG** [comment]
> This PR can be finished after [PrestaShop/prestashop-ui-kit#79](https://github.com/PrestaShop/prestashop-ui-kit/pull/79) is merged and new UI Kit version is released

Not related to this PR, this pr is aiming the yes/no toggle blue and red that you can found on every form, so it's not the same design at all

But if the new toggle looks better (it has labels and more) we can use it

**Comment by NeOMakinG** [comment]
@PrestaShop/prestashop-product-team will we use new toggles introduced in 1.7.8 ? If yes, then we can close this PR

**Comment by LouiseBonnard** [comment]
@NeOMakinG, exactly, we can close this PR since the toggle component has changed in the meantime, thanks!

**Pull request closed without merging**
