### PR TITLE
[+] Project: Add support for postcodes in zones

### PR DESCRIPTION
**Pull request by guestisp**
A must have feature for all Italian customers, where many postcodes are subject to specific prices by carriers.
This add support to postcodes grouped by zones. In this way will be possible to create a carrier bound to a specific zone with "special" postcodes with surchange (island, special destination, and so on...)

Missing translations, i don't know how to add default translation in this PR. Let me know and I'll fix ASAP.
Install/upgrade should be tested.

Let me know If this could be improved in any way.

### CODE REVIEW

**Comment by guestisp** [comment]
Any chance to get this merged in the near future ? Is a 'must-have' feature for all italian customers. In Italy, all carriers has shipping costs based on destination ZIP codes. 
Actually is impossibile to properly manage this shipping cost in prestashop, without this PR.

**Comment by jeromenadaud** [comment]
Hi,

thank you for your PR, this feature is planned in our 2015 road-map.
I will report it to our Product Managers and come back to you with more info.

Best regards.

**Comment by guestisp** [comment]
Great news, but can you add, at least, the hook ? In 2015 you could add native support for postcodes (like my PR) but in the mean time, an hook would be great so that I can develop a module without overriding classes.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
This is a great idea, and will require some good thinking around the Product.
We added this as a ticket to our Product team.
Since this PR cannot be merged anymore, I am closing it.
Thank you for your contribution!

**Pull request closed without merging**
