### PR TITLE
Add actionAdminControllerSetMedia to hooks that could be executed even if the module is disabled

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add actionAdminControllerSetMedia to hooks that could be executed even if the module is disabled. This hook is used to add somes assets on the Back Office, like module configuration.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Use a module with actionAdminControllerSetMedia and see that it will not be executed if it's disabled.
| Possible impacts? | n/d

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26993)

### CODE REVIEW

**Comment by kpodemski** [comment]
But... why?

**Comment by PrestaEdit** [comment]
Because ? :) It's like the displayBackOfficeHeader, if you need to manage assets, you could use this specific hook (that is better to use) and as it's not fire when the module is disable, it will not inject your assets, simply.

**Comment by kpodemski** [comment]
Ok, I'm not sure I understand. 

1. I have a ModuleX
2. I'm loading 1MB of assets through it
3. I'm disabling this module

You want to still load these assets even if the module has been disabled?

**Comment by PrestaEdit** [comment]
Of course. And as you are able to do it inside the displayBackOfficeHeader hook, too.

A disable module is still configurable and usable with it's own AdminTabs, for example.

**Comment by kpodemski** [comment]
Sorry, it doesn't make sense. There was some edge scenario for the `displayBackOfficeHeader` when we had to do it. Disabled modules are not configurable through AdminTabs anymore, it was a bug that has been fixed.

**Comment by kpodemski** [comment]
Most of the time, developers don't care if the module loads assets globally or only on the pages related to the module; thus, this change might introduce a lot of confusion and performance regression.

**Comment by PrestaEdit** [comment]
What ? A module NEED to be configurable when it's disabled. Why ? Cause if you need to do more and more configurations, you need to be able to do it without having it in production (and yes, if developpers does not do best practices, merchants are not with the pre-production environment, for sure).

**Comment by PrestaEdit** [comment]
I will not close this Pull Request as my own, to be honest. Just to know.

**Comment by kpodemski** [comment]
> What ? A module NEED to be configurable when it's disabled. Why ? Cause if you need to do more and more configurations, you need to be able to do it without having it in production

I understand. Controllers are still there and you can redirect the merchant to them, but the tab is no longer displayed in the menu.

Maybe we need to think about a better solution because `displayBackOfficeHeader` hook is also problematic. I often see modules that check for updates from external servers, and even if you disable the module, external calls are still slowing down the back office.

**Comment by matks** [comment]
> But... why?

I have the same very question 😆  .

I think there is here 2 different approaches. It's about "what is a disabled module"?

Depending on the answer, this PR is a good idea or a bad idea.

If we consider "when I disable a module, I want my shop to behave exactly as if it was not there" this PR is not relevant.
If we consider "when I disable a module, I just want it not to be loaded on my shop but I want to be able to access it" this PR can be relevant... but I'm afraid of side-effects. Because @PrestaEdit in your case it works, but maybe some other module developer would find it surprising that his module, even when disabled, still loads assets.

I'm afraid if he ask many different people, we'll have both "yes" and "no" answers 🤷‍♀️  it depends on people way of work, people needs, people vision of how a module should work...

Honestly I am not a module developer so I dont feel relevant to choose. I can however request @Matt75 and @Quetzacoalt91 opinion: they have a high experience. Their opinions will help us a lot I am certain.

**Comment by PrestaEdit** [comment]
It's just a sense-thing. You can disabling and uninstalling a module. This difference could answer by itself to your ask, I'm pretty sure. ;-)

Or we will still use the displayBackOfficeHeader (until you will remove it, 👀 ) because a disabled module is still available to have a getContent() action usable. :)
But the header hook is not make to add assets, I'm afraid (it coud, but it's not make for this).

**Comment by Quetzacoalt91** [comment]
I understand the meaning of this PR. As already said previously, merchants are still able to configure their modules even if they are disabled, and the hook `actionAdminControllerSetMedia` is recommended (instead of displayBackOfficeHeader) to load the assets we could need on the configuration page.

**Comment by kpodemski** [comment]
I would love to see statistics of how many modules from Addons Marketplace that uses `actionAdminControllerSetMedia` have a proper `if` inside to check if their code is executing on the configuration page of the module only.

Unfortunately, I'm sure that this change would break some popular modules like Visual Composer or other page builders. If you want to disable a module, you disable it. You don't uninstall it to lose your data.

Simple scenario:
_User X is using Module Y, but he wants to test a Module Z. Module Y is fully configured with a lot of data inside. Module Y modifies the Order page hiding some elements to implement a feature differently. You disable Module Y to test Module Z. You're going to the Order page now, and you see that Module Y still affects your store even tho you disabled it. You have only one choice. You can uninstall Module Y and lose all data to test module Z._

IMHO it's more a question for a PM now how to tackle this.

**Comment by matks** [comment]
me right now: 🤷‍♂️ 😅

**Comment by matks** [comment]
So what do we do :/ ? this PR actually challenges "what are the consequences of disabling a module"

**Comment by matks** [comment]
Hi everyone I'm sorry but I'm going to close this PR
- it has no activity since December
- unfortunately we have half people who support merging the PR and half who seem against

I'm afraid I can't approve the PR in this situation. We can dive into the topic more closely if you wish to (on the slack channel?) but I don't want to approve a PR with such risk

**Comment by PrestaEdit** [comment]
:(

**Comment by PrestaEdit** [comment]
So sad. Cause somes do shit, we need to continue to make shit too. Not cool.

**Pull request closed without merging**
