### PR TITLE
Restore composer file

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Because the new system take too much time to install all dependencies in a little system we need to rollback to previous behavior and add a new commit to do this kind of installation only for build.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Waiting for CI.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12598)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
> and add a new commit to do this kind of installation only for build.

I'd like to see this commit a part of this pull request then 👍!

Also, I don't understand why a Green build from CI proves anything was fixed [as another PR created at the same time as yours is green too](https://github.com/PrestaShop/PrestaShop/pull/12597): are you really sure this revert is required and can you explain what you are trying to fix?

**Comment by PierreRambaud** [comment]
It does not take the same time 
Without my change:
image

With:
image

And we must check for more than one comparaison :)

**Comment by mickaelandrieu** [comment]
Hello !

Did you take a look at #12600? 😇

**Comment by PierreRambaud** [comment]
Yes and as I said, we don't care about total time in travis.

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
