### PR TITLE
[*] Project : Enhance Readme with external link

### PR DESCRIPTION
**Pull request by inetbiz**
External link to prestashop preferred hosting partners link. https://www.prestashop.com/en/ecommerce-hosting

### CODE REVIEW

**Comment by AlexEven** [comment]
Hello @inetbiz,

Thanks for your contribution! 
I see what you wanted to do here, but I think we need to keep the list (while updating it). 
We're informing people before anything, we're not trying to push any partner here.

So I would have instead:

If your host does not offer PHP 5 by default, [here are a few explanations][3] about PHP 5 or the `.htaccess` file for certain hosting services (1&amp;1, Free.fr, OVH, GoDaddy, etc.).

Would you mind updating your PR?

Best regards,

**Comment by inetbiz** [comment]
@AlexEven your suggestion still gives preferential treatment to certain hosting providers. Namely the list you have above with 1&1, free.fr, OVH, Godaddy. As an employee of a hosting provider, that harms our ability to compete fairly in the marketplace.

Would you agree to drop the naming of those competitors?

**Comment by AlexEven** [comment]
Hello, 

In that case yes, we can drop the naming list and that should solve it.

How about rewriting the sentence like this?

"If your host does not offer PHP 5 by default, you will find a few explanations about PHP 5 or the .htaccess file in [our documentation][3], with details for certain hosting services."

Hopefully this will suit you. 

Best regards,

**Comment by inetbiz** [comment]
http://doc.prestashop.com/display/PS16/Misc.+information#Misc.information-ActivatingPHP5 is still doing the same thing. @AlexEven do I need to open a documentation issue? I think you could do better just by giving three examples by environment. Plesk, cPanel, Raw apache/php, IIS+, etc.

**Comment by inetbiz** [comment]
@AlexEven I flagged you over 60 days ago.

**Comment by AlexEven** [comment]
Hello @inetbiz 

Indeed, apologies for the delay. Thanks for the updated commit.

Yes, you can open a documentation ticket on the Forge, simply make sure you select the "Documentation" project.
We'll keep the hosting providers as it is on the company's .com, and we have some partnership agreements with them. If you want to add some content for your service, please kindly provide it in the ticket.

Best regards,

**Comment by inetbiz** [comment]
@AlexEven please clarify the hosting providers list in the documentation? Are you stating in public that you have special, commercial, contracts to insert their names into the documentation found at http://doc.prestashop.com/display/PS16/Misc.+information#Misc.information-ActivatingPHP5 ??

**Comment by guestisp** [comment]
@inetbiz totally agree with you.

**Comment by inetbiz** [comment]
@guestisp I'm waiting to see.

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
Hello! I made changes to the README.md file in #4387, and forgot to take your PR into account -- introducing conflicts. Sorry! 
It's now done in #4508. I'm therefore closing this PR. Thank you for your contribution!

**Comment by xBorderie** [comment]
Oh, and just so you know, partnerships contracts don't include a clause about having a name in the documentation, as far as I know. If you know information for enabling PHP5 in more hosts, please submit a ticket on the Forge! Cheers.

**Comment by inetbiz** [comment]
@xBorderie I cannot think of a single commercial hosting provider still using PHP4. It is a major failure in The Payment Card Industry's Data Security Standards 3.0

I think your warnings in advanced configuration settings is sufficient in that in warns against OS using less than PHP 5.4. The documentation should point to a [requirements page](http://doc.prestashop.com/display/PS16/System+Administrator+Guide#SystemAdministratorGuide-Requiredsettings). That page, perhaps, should state the minimum required PHP version.

There are simply too many equations to list possible outcomes when you have CloudLinux&trade;, cPanel&trade;. nginx, et al.

**Pull request closed without merging**
