### PR TITLE
Update grid design regarding grid gear icon position and dropdown toggle icon modification

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | As mentioned in https://github.com/PrestaShop/PrestaShop/pull/10774#issuecomment-431363447 some design changes are needed on all lists
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #11080 #11077 
| How to test?  | Check the design updates according to https://github.com/PrestaShop/PrestaShop/pull/10774#issuecomment-431363447 and also test if the list actions which are now located in list header works

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11095)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @tomas862, how about some screenshots? :smile:

**Comment by matks** [comment]
Here is the wheel :) 
capture d ecran 2018-10-23 a 16 37 48

Here is the drop-down
capture d ecran 2018-10-23 a 16 38 12

**Review by matks — DISMISSED** [review]

**Comment by TristanLDD** [comment]
Hello @matks, can you just adjust the position of the wheel in the header so it's vertically well aligned?  

capture d ecran 2018-10-30 a 15 50 15 . 

Except this little detail I'm ok with those components :)

**Comment by TristanLDD** [comment]
Hello @matks, can you just adjust the position of the wheel in the header so it's vertically well centered?

wheel

Except this little detail I'm ok with these components :)

**Comment by PierreRambaud** [comment]
@tomas862 Can you please fix conflicts and we will merge :)

**Comment by sarjon** [comment]
@PierreRambaud rebased. :wink:

**Comment by matks** [comment]
@PierreRambaud @sarjon Did Tristan's UX feedback got implemented ? I tried to do it but I'm really bad at CSS 😞

**Comment by PierreRambaud** [comment]
@matks Tristran removed the waiting for UX label 8 days ago :) so should be ok now!

**Comment by matks** [comment]
Travis is not happy because of lint

**Comment by sarjon** [comment]
lint was fixed by this PR https://github.com/PrestaShop/PrestaShop/pull/11306 so it is not because of this PR, but i can rebase if you want. :)

**Comment by matks** [comment]
@sarjon thanks but this is not required: if `develop` branch is fine now, I can restart travis build and it should be green

**Comment by sarjon** [comment]
> it should be green

and it is. :)

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @sarjon

**Pull request merged**
