### PR TITLE
Fix linkchecker script for UI tests

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fix linkchecker script for Ui tests
| Type?             | bug fix
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| Related PRs       | 
| How to test?      | Run `npm run check:links`, test will run and you will see some errors
| Possible impacts? | N/A

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]
@boubkerbribri Question :question: : Why not in the CI, now ?

**Comment by boubkerbribri** [comment]
It will be difficult to have it green always, some errors that displays are from external services dependencies. The deal is to check it every now and then (before releases).

**Review by matks — APPROVED** [review]
@boubkerbribri how do you want to validate this PR?

**Comment by boubkerbribri** [comment]
> @boubkerbribri how do you want to validate this PR?

The pull request is already tested, if is that what you mean and issue was found using this version of Autoupgrade #30051.

You can merge it unless you have something else in mind.

**Comment by matks** [comment]
Thank you for answer @boubkerbribri

**Pull request merged**
