### PR TITLE
Show/hide attach file form with button

### PR DESCRIPTION
**Pull request by nihco2**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | show/hide attach a new file form with a button |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-994 |
| How to test? | Check if the form is displayed correctly |

### CODE REVIEW

**Comment by vTerenti** [comment]
Hi!

Thanks for your contribution!

Best regards

**Comment by vTerenti** [comment]
Question : how can we delete attached files?

**Comment by vincentbz** [comment]
Not in the product page, if you want to fully manage your attachments, it's in the "files" page.
We kept the same behaviour as previously but just added the possibility to add a file to the "file center" from the product page.

**Comment by vincentbz** [comment]
Hi,

Some bugs reported in the tickets
http://forge.prestashop.com/browse/BOOM-994

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by antoin-m** [comment]
Thank you :)

**Pull request merged**
