### PR TITLE
[*] FO : Fix #PSCSX-4382:  Add hook to customize cart summary

### PR DESCRIPTION
**Pull request by guestisp**
Actually, is not possible to customize cart summary without overriding Cart::getSummaryDetails()
An hook should be added to allow customization without the need to override the whole method.

Fix #PSCSX-4382

### CODE REVIEW

**Comment by kpodemski** [comment]
:+1:

**Comment by gRoussac** [comment]
Hi,

thank you for your PR. I would say it would belong to unvisible hooks, so it can not be called displaySomething like displayTop. Don't you think ?

Regards

**Comment by kpodemski** [comment]
actionCartSummary or cartSummaryMidifier (like productListModifier)?

**Comment by guestisp** [comment]
Yes, is an invisible hook.

Probably `actionAfterCartSummary` is better, because it's called after the original cart summary

**Comment by guestisp** [comment]
Let me know what do you prefere

**Comment by gRoussac** [comment]
I would say actionCartSummary too. Can you aslo withdraw additionnal spaces after parenthesis please ?

Regards

**Comment by guestisp** [comment]
Which parenthesis ? array_merge ?

**Comment by gRoussac** [comment]
( is_array($hook) ) 

(is_array($hook))

thank you !

**Comment by guestisp** [comment]
extra spaced removed

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and contribution.

Best regards

**Pull request merged**
