### PR TITLE
[*] Project: move product comparator into module

### PR DESCRIPTION
**Pull request by PrestaEdit**

### CODE REVIEW

**Comment by gRoussac** [comment]
:muscle:

**Comment by jeromenadaud** [comment]
:clap:

**Comment by kpodemski** [comment]
Nice one... however... it doesn't seems retro compatible, right?

**Comment by gRoussac** [comment]
Yeah withdrawing getFeaturesForComparison from the class is clearly not respecting backward compat. But i was just commenting the exhaustive work this PR has required. We need to fully review and test it indeed and probably changing the function getFeaturesForComparison to test if the module is installed and then call the module method. So that users using the current function will still have an answer getFeaturesForComparison, + a deprecate warning maybe.

Regards

**Comment by kpodemski** [comment]
Most of custom themes from Addons Marketplace will not work after these changes, most of them links to product-comparison using getPageLink, AJAX now is also hanled by different page, this is a great move to use comparison as module however for now it needs few more tests on backward compat.

**Comment by gRoussac** [comment]
Indeed

**Comment by jeromenadaud** [comment]
Hi @PrestaEdit 

great PR, but we need to keep backward compatibility at this moment, please let me call you tomorrow in order to show you how to do it with new architecture.

Best regards.

**Comment by PrestaEdit** [comment]
Hi @jeromenadaud , no problem! ;-)

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
Thank you for the huge work done in this PR!
Sadly, I must close this PR because the `1.6` branch is no longer used, and PrestaShop 1.6 will now only receive bugfixes, not improvement such as this one.
If you want to recreate this PR for PrestaShop 1.7, please do it on the `develop` branch.
Thank you for your contribution!

**Pull request closed without merging**
