### PR TITLE
CO: UNIX_TIMESTAMP converts to UTC time

### PR DESCRIPTION
**Pull request by stickyrst**
UNIX_TIMESTAMP convert MySQL dates to UTC (https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_unix-timestamp). You should not use that while comparing it to a system date, if the system timezone is different from UTC. I had problems with cache because of that, and the cache was deleted at every refresh. Took me a while to find the problem.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | UNIX_TIMESTAMP convert MySQL dates to UTC (https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html#function_unix-timestamp). You should not use that while comparing it to a system date, if the system timezone is different from UTC. I had problems with cache because of that, and the cache was deleted at every refresh. Took me a while to find the problem. My server timezone is GMT +2.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Configure your system timezone to GMT + 2, then clear cache. Browse the website and then check the Smarty cache folder (With cache on). It will be empty or there will be only 1 folder, because cache files will be deleted every single time someone browses the website, due to comparing UTC to GMT + 2 dates. 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7958)

### CODE REVIEW

**Comment by eternoendless** [comment]
I'm having a bit of a hard time to see the problem here. The current logic, as I understand it, is as follows:

1) Dates are stored as DATETIME in the current timezone, by the means of` FROM_UNIXTIME('.time().')`.

`time()` returns a Unix timestamp, which by definition is UTC. `FROM_UNIXTIME` should convert it to the local timezone.

I verified that by running `SELECT FROM_UNIXTIME(0)`, which as expected, gave me `1970-01-01 01:00:00` (I'm in UTC+1)

2) When retrieved, dates are reconverted to Unix timestamps (again, by definition in UTC) using `UNIX_TIMESTAMP(...)`.

So, when I execute `SELECT UNIX_TIMESTAMP('1970-01-01 01:00:00')`, as expected, I get `0`.

3) We use that timestamp for comparison with the results of `filemtime()`.

... which returns a timestamp (once more, UTC).

Maybe I'm missing something, but I'm unable to see the timezone issue here.

**Comment by stickyrst** [comment]
@eternoendless 
Hello Pablo!

If your database has a timezone and your web server has another timezone,
then the code will compare 2 times with different timezones, that's the
problem.

Back with example:

SELECT UNIX_TIMESTAMP('2017-07-31 16:00:00') returns 1501506000
strtotime('2017-07-31 16:00:00') returns 1501509600
date('Y-m-d H:i:s', 1501506000) returns 2017-07-31 15:00:00

So there is an 1 hour delay between those 2 timestamps, even if they look the same - 2017-07-31 16:00:00 (one from mysql, one from php), which results in wrong comparsion result.

George

**Comment by eternoendless** [comment]
> If your database has a timezone and your web server has another timezone, then the code will compare 2 times with different timezones

How would that be?
The web server sends timestamps which are in UTC regardless of which timezone the server is configured in.
The database server receives [UTC] timestamps, stores them in the local timezone, and sends [UTC] timestamps.

All data communication and processing is done using [UTC] timestamps.

The only scenario in which I can imagine that not working is if either one's time is off. For example, if your server is configured in UTC but the clock is configured to be 2 hours late to match UTC+2, the timestamps used and sent from the web server would be 2 hours late.

**Comment by stickyrst** [comment]
Check the example, same result on both a dev server and a live server (except the live server has a delay of 2 hours instead of 1 hour), with no connection to each other (separate hosting). Let me know your thoughts on that.

**Comment by eternoendless** [comment]
If my calculations are correct, your SQL server is un UTC+2 and your web server in UTC+1

> strtotime('2017-07-31 16:00:00') returns 1501509600
> date('Y-m-d H:i:s', 1501506000) returns 2017-07-31 15:00:00
> 
This is normal if your web server is in UTC+1.

In this example:
`strtotime()` takes a date in the *web server's timezone* and transforms it into a UTC timestamp.
`date` takes a UTC timestamp and transforms it into a date in the *web server's timezone*.

So your server's timezone has an impact on the result.

However, this is not what the current code does 🙂 

The current code uses `time()` and `filemtime()` which both return UTC timestamps regardless of your server's timezone.

MySQL uses `FROM_UNIXTIME` to convert from UTC to the local timezone and `UNIX_TIMESTAMP` for the reverse operation.

There are no mixed timezones that I can see 🤔 

The server side works with UTC timestamps, and the database server only transforms it into the local timezone for storage (it's transformed back to UTC when data is sent).

My suggestion would be to ensure that the clocks on both your servers match their configured timezone. If you have ssh access, a quick way is simply typing `date`.

**Comment by matks** [comment]
Closing as we got no answer from author in 2 years

**Pull request closed without merging**
