### PR TITLE
[-] BO : Fix #PSCSX-4929 display problem of media server

### PR DESCRIPTION
**Pull request by sfroment**

### CODE REVIEW

**Comment by doekia** [comment]
What's about legacy server migrating?
I wonder what the underlying reason btw to move those params to the Db ?
Cloud? But cloud will address such by SetEnv !

We enter the bloated registry scenario that Microsoft followed earlier by injecting every piece of settings within the db. An Microsoft was using hierarchy and underlying C + persistent cache ...

**Comment by gRoussac** [comment]
Hi,

Media servers need to be multishop. Lagacy should be maintained by https://github.com/PrestaShop/PrestaShop/blob/1.6/install-dev/upgrade/php/p16011_media_server.php

Regards

**Comment by doekia** [comment]
Ok but still remain the question about legacy migration.
Those constants never get flaged deprecated.
Add to the upgrade to clean those values from the settings.inc.php and probably a note in the change log.

**Comment by gRoussac** [comment]
Hi,

Thank you for your advice but I believe this is done here https://github.com/PrestaShop/PrestaShop/blob/1.6/install-dev/upgrade/php/p16011_media_server.php#L38

Regards

**Pull request merged**
