### PR TITLE
Delete unused old images

### PR DESCRIPTION
**Pull request by martinfojtik**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | I Grep through the root folder and find which images are no longer used anywhere in admin or modules.I deleted the 110 \* `GIFs` and 102 \* `PNGs` :cry: |
| Type? | refacto |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |

### CODE REVIEW

**Comment by xBorderie** [comment]
For our review, could you give us the grep command you used? :)
Thank you!

**Comment by fojtcz** [comment]
Actually i created small Symphony script which loop through all folders.

You can put file name into search bar on this page and find if file is somewhere in a code.

**Comment by xBorderie** [comment]
Well, we'd be interested in seeing how your script works, 'cos it would be easier than to check that each one of these 200+ files must be deleted :)

**Comment by fojtcz** [comment]
ok, there it is https://gist.github.com/fojtcz/28ccedcfe89199a111f9

**Comment by julienbourdeau** [comment]
Hi,

I like the approach (using a script) but I would even recommend to delete the whole `/img/admin` folder :dart:

**Comment by fojtcz** [comment]
@julienbourdeau me too, but some of these images are still used in code

there is the list of scripts which are using at least one of these images:
```
admin-dev\filemanager\css\jquery.contextMenu.min.css
admin-dev\filemanager\jPlayer\skin\blue.monday\jplayer.blue.monday.css
admin-dev\functions.php
admin-dev\themes\default\css\bundle\default.css
admin-dev\themes\default\template\controllers\carrier_wizard\logo.tpl
admin-dev\themes\default\template\controllers\carts\helpers\view\view.tpl
admin-dev\themes\default\template\controllers\customer_threads\helpers\options\options.tpl
admin-dev\themes\default\template\controllers\customer_threads\message.tpl
admin-dev\themes\default\template\controllers\languages\helpers\form\form.tpl
admin-dev\themes\default\template\controllers\orders\form.tpl
admin-dev\themes\default\template\controllers\orders\helpers\view\view.tpl
admin-dev\themes\default\template\controllers\outstanding\_print_pdf_icon.tpl
admin-dev\themes\default\template\controllers\tax_rules\helpers\list\list_content.tpl
admin-dev\themes\default\template\helpers\form\assoshop.tpl
admin-dev\themes\default\template\toolbar.tpl
admin-dev\themes\new-theme\scss\components\_category_tree.scss
classes\AdminTab.php
controllers\admin\AdminCarriersController.php
controllers\admin\AdminCarrierWizardController.php
controllers\admin\AdminCountriesController.php
controllers\admin\AdminGroupsController.php
controllers\admin\AdminLanguagesController.php
controllers\admin\AdminProductsController.php
controllers\admin\AdminQuickAccessesController.php
controllers\admin\AdminSearchController.php
controllers\admin\AdminStatesController.php
controllers\admin\AdminStockConfigurationController.php
controllers\admin\AdminStockMvtController.php
install-dev\theme\rtl.css
install-dev\theme\view.css
install-dev\theme\views\header.phtml
install-dev\theme\views\process.phtml
install-dev\theme\views\welcome.phtml
js\admin.js
js\jquery\plugins\fancybox\jquery.fancybox.css
js\jquery\plugins\jquery.colorpicker.js
js\jquery\plugins\treeview-categories\jquery.treeview-categories.css
js\tiny_mce\plugins\colorpicker\plugin.min.js
modules\_blocktopmenu\css\superfish-modified.css
modules\blocklayered\views\templates\admin\add.tpl
modules\blockpermanentlinks\blockpermanentlinks-footer.tpl
modules\blockreassurance\blockreassurance.php
modules\gamification\data\data_EN_CZK_CZ.json
modules\gamification\views\css\gamification.css
modules\gamification\views\templates\hook\notification.tpl
modules\statsbestmanufacturers\statsbestmanufacturers.php
modules\statsforecast\statsforecast.php
modules\statsproduct\statsproduct.php
modules\vatnumber\views\templates\admin\_configure\helpers\form\form.tpl
themes\classic\templates\customer\order-detail.tpl
```

pretty long list :fearful:

**Comment by fojtcz** [comment]
if somebody wants to hunt them, there is JSON list :smile: 

https://gist.github.com/fojtcz/8679c267407c94b188dae073445c2b46

**Comment by mickaelandrieu** [comment]
ping @julienbourdeau what do we do?

**Comment by julienbourdeau** [comment]
Great! 🔦 
Thank you

**Pull request merged**
