### PR TITLE
[-] CORE : Fix #PSCSX-5301 correct return value

### PR DESCRIPTION
**Pull request by sfroment**
- 1st commit
  - when display error is true need to return false on success 
  - when display error is false need to return true on success

### CODE REVIEW

**Comment by oleacorner** [comment]
Hi Sacha

I think this part of the function should also have been reviewed :+1: 
if ($this->product_restriction)
		{
			$r = $this->checkProductRestrictions($context, false, $display_error, $alreadyInCart);
			if ($r !== false && $display_error)
				return $r;
			elseif (!$r && !$display_error)
				return false;
		}

Something like following code would have been better :
if ($this->product_restriction)
		{
               if ($r !== false)
                      return (!$display_error) ?false :$r;
                }

**Comment by sfroment42** [comment]
Hello @oleacorner,

Actually !$r in the elseif is less restrictive than $r !== false that why I haven't rework this part.
But I think taking your solution won't impact the comportment of the function I'll chech this ASAP.

Best regards.

**Comment by oleacorner** [comment]
I agree with you.
I think the purpose of this code is to decide to return FALSE or the string of the checkProductRestriction. That's why I propose this rewritting which seems more lisible for me

**Comment by oleacorner** [comment]
The checkProductRestriction may return TRUE/FALSE/a string/a product list.
My code, as the original one, may be wrong

**Comment by oleacorner** [comment]
Hi Sacha,

I think the first check in the method must also be modified, to take care about the $display_error
		if (!CartRule::isFeatureActive())
			return false;

**Comment by sfroment42** [comment]
Hello @oleacorner,

I close this PR for the moment.
Take a watch https://github.com/sfroment42/PrestaShop/commits/check_validity .
I've rework the method to unitary test it.
I'll do another PR when I will get a better series of test.
I'll try to do the same on checkProductRestriction to test it too.
If you got idea of test tell me!

Best regards.

**Pull request closed without merging**
