### PR TITLE
Private Note Orders

### PR DESCRIPTION
**Pull request by JavierEB**
Prestashop always, in the private note of customer orders, is not associated with the order itself ... it is associated with the customer. With which it would be a good option to associate only that private note within the orders only to them. For example: a customer has multiple orders, but only one needs xx $ and that note may be only for that order, not for the customer itself ... I don't know if you understand me ... Attached photos of the orders, to all those of the same client are associated with the same "test note"
I think that is a problem. Thank you
Screenshot_2020-04-26 Orders Order FFATNOMMJ from John DOE • Prueba1764
Screenshot_2020-04-26 Orders Order KHWLILZLL from John DOE • Prueba1764
Screenshot_2020-04-26 Information about customer J DOE • Prueba1764

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc. Feel free to add more information below this table.
| Type?         | new feature
| Category?     | BO 
| BC breaks?    |  no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/14753
| How to test?  | any version of prestashop

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18825)

### CODE REVIEW

**Comment by Progi1984** [comment]
@JavierEB Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Comment by matthieu-rolland** [comment]
@JavierEB it seems like your PR is merging develop into 1.7.6.x, I'm pretty sure you don't want to do that :D

**Comment by JavierEB** [comment]
> 
> 
> @JavierEB Thank you for your contribution. hugs
> 
> Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
> Could you give us a scenario which permits to test the bug before and after this PR ?
> 
> Thanks +1

hi, the problem is with all versions of PS. This is a problem that comes from behind I think ...
Because the private note of the orders is actually saved in the table ps_costumers> Column "Note" with which it is associated with all the orders of that customer, not just one.

**Comment by JavierEB** [comment]
> 
> 
> @JavierEB Thank you for your contribution. hugs
> 
> Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
> Could you give us a scenario which permits to test the bug before and after this PR ?
> 
> Thanks +1

hi, the problem is with all versions of PS. This is a problem that comes from behind I think ...
Because the private note of the orders is actually saved in the table ps_costumers> Column "Note" with which it is associated with all the orders of that customer, not just one.

**Comment by Progi1984** [comment]
@JavierEB Please create an issue which be prioritized thanks our @PrestaShop/prestashop-product-team

**Comment by JavierEB** [comment]
>  Please create an issue which be prioritized thanks our @PrestaShop/prestashop-product-team

ok thanks

**Comment by MatShir** [comment]
Hi @JavierEB,
There are 2 needs here:
- One where we want to have a concise description of the customer (for big client, to save customer behavior/additional information). It is very useful for B2B cases for example.
- One where we want to have a concise description of the order status

The first one is implemented with a private note. 

But the second one is kind of done with the private message which can be only be seen by the merchant in this particular order. 
It is not ideal for the merchant to look to the private messages to process the order or to see quickly notable information.

Instead of editing the feature of customer note, I suggest adding new input for this. I will ask our designer to recommend the ideal implementation for this feature on this order page.
@PrestaShop/prestashop-designers

**Comment by PierreRambaud** [comment]
Sorry @JavierEB , this PR does not include any contribution from your account. This kind of merge should be done manually in order to fix the existing conflicts.
I'm closing it as it can't be accepted as-is.

If you have a feature request or a bug please create an issue https://github.com/PrestaShop/PrestaShop/issues/new/choose

Kind regards

**Pull request closed without merging**
