### PR TITLE
Fix customer search in specific price PPV2

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      |  the pr  https://github.com/PrestaShop/PrestaShop/pull/33458 conditioned the creation of the autocomplete on the multistore feature, i improved this
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see https://github.com/PrestaShop/PrestaShop/issues/34652
| UI Tests          | https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/7007893427
| Fixed issue or discussion?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/34652
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @M0rgan01

**Review by florine2623 — COMMENTED** [review]
Hello @M0rgan01 ,

The search field works.

But before I could delete the customer i chose, now I can't. I need to delete the whole specific price and recreate it.

Before :

https://github.com/PrestaShop/PrestaShop/assets/16019289/cf5ba2e8-ae9c-4a4e-8a43-b7854f831392


After : customer can't be deleted
Screenshot 2023-12-01 at 10 24 02

Could you check ?

**Comment by jolelievre** [comment]
@florine2623 you are testing the wrong page Your video is on the v1 the bug fix is for v2 You need to enable the product page V2 with the feature flag

**Comment by MatShir** [comment]
@florine2623 the deletion issue doesn't come from this PR. So we could create another issue for it. 
The test is good from @florine2623. I suggest to move on ! :)

**Comment by MatShir** [comment]
Re adding waiting for QA, to have @florine2623 feedback to be sure :p

**Comment by florine2623** [comment]
Ok for me !
I'll create an issue for that to be fixed later on ^^

**Comment by florine2623** [comment]
https://github.com/PrestaShop/PrestaShop/issues/34748

**Pull request merged**
