### PR TITLE
Fixes and improvements in the BO & Core

### PR DESCRIPTION
**Pull request by M03G**
Each commit has explanatory comment.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, @M03G !
Could you make one PR per commit? This way we can merge things precisely, and not accept everything on one swoop.
Thanks!

**Comment by M03G** [comment]
I can, @xBorderie . That's what I was doing before. But one of my PR has not been considered in May, 7 months. And while no one considered, it is impossible to make another - changes are added to the first.

**Comment by M03G** [comment]
@xBorderie , I close this PR? And what PR do first?

**Comment by xBorderie** [comment]
Indeed, you recently closed #3052 for lack of interest on our part -- but it was made on an abandoned branch, so by the time we had the time to look at it, we couldn't merge it.

You should close this PR, and create three new PRs on the `develop` branch. Try the BO one, but all three could be useful. Don't the forget to put the comments withing the PR! :)

**Pull request closed without merging**
