### PR TITLE
Fix web service when using PHP 7.2 or higher, checking if countable or scalar array before using count()

### PR DESCRIPTION
**Pull request by Ousret**
PHP 7.2 raise warning when using count() on a non-countable element and trigger HTTP/500 with PrestaShop web service. This patch does not affect compatibility with the previous version of PHP. See PHP RFC: is_countable for more.

In some cases, $shopIDs is not countable, like when you create a brand new installation from scratch using embedded setup script and demo fixtures.

```php
if ((is_array(self::$shopIDs) || self::$shopIDs instanceof Countable) && count(self::$shopIDs)) {
      return true;
}
```

To avoid breaking things in the near future, and long-term support I propose to check if $shopIDs is countable or checking primitive scalar type before running count() on it. 
I use both is_array and isinstance in case you choose to use an actual Array-like object instead of the scalar one.

This PR does not break compatibility with PHP 5.4 and higher, also I think they're probably more array or countable object that are manipulated without this verification in the code. This PR is about unblocking this critical issue.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.5.x 
| Description?  | Webservice does not work using PHP 7.2 or higher w/ prestashop 1.7.x just after initial untouched installation with demo fixtures.
| Type?         | bug fix / critical
| Category?     |  WS 
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | no
| How to test?  | Simply request webservice using PHP 7.2 or higher.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11087)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Chance branch to 1.7.5.x please

**Comment by Ousret** [comment]
Done + php lint check on webservicerequest.php fixed

**Comment by Quetzacoalt91** [comment]
PR updated to target the develop branch.

I wonder if we shouldn't use a polyfill of the method `is_countable` here.
It would make the code really easier to read, as we wouldn't need to cop/paste the same tests everywhere needed, and we would have the code ready to use for PHP 7.3.

This would need a new dependency to be added: https://symfony.com/blog/introducing-new-symfony-polyfills-for-php-7-3-and-ctype

**Comment by matks** [comment]
👍 for the polyfill

**Comment by Quetzacoalt91** [comment]
@Ousret, do you want to update your PR to add the polyfill or do you want us to handle this?

**Comment by Quetzacoalt91** [comment]
Without answer from you, I created another PR with the polyfill. See #11510

**Comment by Quetzacoalt91** [comment]
As #11510 as been merged, I'm closing this one. Thanks @Ousret

**Pull request closed without merging**
