### PR TITLE
Fix orders page dropdown going under header by removing the fixed property

### LINKED ISSUE #17717: Order status list is under the header not completely displayed
**Describe the bug**
Order status list is under the header not completely displayed

**To Reproduce**
1. Go to orders > orders
2. Make sure you have a lot of orders
3. Scroll down and click on an order status in the list 
3. You don't see all status  

https://drive.google.com/file/d/1-LYxdLLRAXxzXastAloSbxVEHqWxWFqP/view?usp=sharing

**Screenshots**
76763182-ea2e2400-6792-11ea-9a45-e6acf2a51edd

**Additional information**
PrestaShop version: 1.7.7.x
PHP version: N/A

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Some items of status dropdown were not clickable by being under the header
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #17717  .
| How to test?  | You should find a grid with dropdowns in list and see if you are able to click on every items by scrolling top or bottom when the dropdown is opened

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17849)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by arouiadib — DISMISSED** [review]

**Comment by boubkerbribri** [comment]
@NeOMakinG 
Tests KO
When opening dropdown 'status' : 

- We can't see the last element 
image

- A scrollbar is displayed in orders list, and we can have infinite scroll
image
image

**Comment by NeOMakinG** [comment]
Need review as I fixed a sideeffect from another work

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by SD1982** [comment]
This PR correctly fix #17717 . Thanks @NeOMakinG

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG

**Pull request merged**
