### PR TITLE
Fix visual issues new product page

### LINKED ISSUE #32214: Visual issues on the new product page (desktop version)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are some visual issues on the new product page.

 1. If you have a multi-lang site, language iso-codes should be uppercase (this is a feature request ;-))
https://capture.dropbox.com/Ipr6P4gHlCDQWdTt

**Apply uppercase for all ISO codes - both dropdown selectors for multi-language text inputs AND TinyMCE Text Editors (impacts the entire BO, not only product page)**  

 2. Element below indicates whether the field is required or not, but there's no label explaining that.
https://capture.dropbox.com/cjYTfYu4WZISB6Sc

Tab Details -> Attached files -> **Add a label « Required field » before yes/no toogle** 

3. What do you want me to type there? Missing placeholder.
https://capture.dropbox.com/qlvsa0rqqBvj43OE

Tab Stocks -> Stock alert input -> **Add placeholder "Enter threshold value / Enter low stock value" + Change text input into numeric input** 

 4. Link below is misaligned. It is not in the center, it is not to the left, etc.
https://capture.dropbox.com/jMWWFibWdYOzwAGP

Tab Pricing -> Retail price -> **Align internal link on bottom right, under Retail price input**

 5. There are a few issues there. The help text doesn't look like a help text, warning/info text doesn't look like one.
https://capture.dropbox.com/Mru43SJO6TP3oxxG

Tab Pricing -> Add new specific price modale -> **Turn text « For customer meeting the… » into blue info alert**

6. Worth considering making it more readable. (feature request)
https://capture.dropbox.com/dcMEAaJ4kHKd1vuI

Tab SEO -> Redirection page -> Long Info alert -> **Change paragraph text into bullet list inside info alert**

 7. When you click this button, it gets a weird border covering part of the text.
https://capture.dropbox.com/VJZHmF53l6JJft0i

Tab SEO -> Meta title / Meta description / Friendly URL ->
Quick win: **Fix behavior of Reset button (on click: filled - after click: back to outlined)** 
Nice to have: **Dynamic behavior - Reset button is disabled when input value = reset value, Reset button is enabled when input value ≠ reset value**

 8. I don't understand this part. What is this currency for? I have PLN but still the EUR symbol on the left. (edit, ok, it doesn't change dynamically).
https://capture.dropbox.com/esELxbafmUtZ8nnh

Tab Options -> Supplier reference(s)
Quick win: **Remove the currency symbol from cost price input**
Nice to have: **Make Cost price input's currency symbol dynamic: Cost price currency symbol adapts to the Currency selected in dropdown next to it** (should be possible as this behavior already exists) 

**Other improvements :** 

- Tab Pricing -> Retail price -> **Make Tax rules input disabled when taxes are disabled** 

- Mobile -> Tab description -> Add categories - > Category selection modale -> **Center modale + align Cancel/Save buttons on bottom right** 

- Mobile -> Tab Stock -> **Fix display for Add or subtract item input** 

- Virtual Product > Tab Virtual 
If the Add downloadable file is set to no, all the input are disabled

Capture d’écran 2023-08-06 à 23 04 16

 

### Expected behavior

Some of the elements could be fixed/improved.

### Steps to reproduce

Visit the new product page and the places you see on screenshots.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

n/a

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix some issues in new product page.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |  no
| How to test?      | See #32214
| Fixed ticket?     | Fixes #32214
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by Hlavtox — COMMENTED** [review]
Quick check/test

1 - If you have a multi-lang site, language iso-codes should be uppercase (this is a feature request ;-)) FIXED
2 - Element below indicates whether the field is required or not, but there's no label explaining that. FIXED, but I would switch the required and delete button, delete should be at the end.
3 - What do you want me to type there? Missing placeholder. - FIXED
4 - Link below is misaligned. It is not in the center, it is not to the left, etc. FIXED
5 - There are a few issues there. The help text doesn't look like a help text, warning/info text doesn't look like one. IMPROVED
6 - Worth considering making it more readable. (feature request) - FIXED, collapse added
7 - When you click this button, it gets a weird border covering part of the text. 🔴 PARTIALLY FIXED - @boherm add some margin under the helptext or something, or margin top on the button?
8 - I don't understand this part. What is this currency for? I have PLN but still the EUR symbol on the left. (edit, ok, it doesn't change dynamically). 🔴 NOT FIXED?

**Comment by boherm** [comment]
Hi @Hlavtox, thanks for your review ;)

> 7 - When you click this button, it gets a weird border covering part of the text. 🔴 PARTIALLY FIXED - @boherm add some margin under the helptext or something, or margin top on the button?

Yeah, why not to add a margin.
I just add the "disable" button behavior thing when we don't have a change on the friendly url.

> 8 - I don't understand this part. What is this currency for? I have PLN but still the EUR symbol on the left. (edit, ok, it doesn't change dynamically). 🔴 NOT FIXED?

Weird 🤔 Have you correctly rebuild the new theme?

**Comment by Hlavtox** [comment]
@MatShir @TristanLDD Guys one more improvement regarding the specific prices.

- Disable one checkbox, if you enable the other one?
- What about adding **A)** and **B)** or something before the two discount options?

(automatic translation in chrome)
Snímek obrazovky 2023-08-09 181954

**Comment by MatShir** [comment]
If I remember well both can be applied so, that's why it is not like a switch behavior.

**Comment by boherm** [comment]
Yo @Hlavtox, I've fix the 7th and 8th items.
For the 8th, I don't reproduce on my side but maybe it's a browser compatibility issue.
Anyway, with the fix I've done, this could be working on your side now.

If you have some time, can you recheck that? 🙏

**Review by matks — APPROVED** [review]

**Review by LouisAUTHIE — APPROVED** [review]

**Comment by Hlavtox** [comment]
@boherm I will test it during the weekend 👍

**Review by aniszr — COMMENTED** [review]
Hello @boherm 

I tested your PR, almost all of your improvements are well displayed.

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/3c4b320c-7164-4169-a63d-d5cee489c263

The only failed improvement is :

- Mobile -> Tab Stock -> Fix display for Add or subtract item input :x:
See attached screenshot:
image

Could you please check and feedback!

Thanks!

**Comment by Hlavtox** [comment]
@aniszr Anis, does this work? You must show it. :)

IMG_7307

**Comment by aniszr** [comment]
Hello @Hlavtox 

Thanks for your feedback.

I retested the currancy changing behavior and found that `Cost price (tax excl.)` don't change automatically the currency symbol when we assign a new Currency! Unless we click save and publish!!

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/0a6d2a2a-487a-4252-b603-580761840836

Thanks!

**Comment by boherm** [comment]
Hello @aniszr,
Have you really rebuild assets (and precisely admin-new-theme) before testing? 🤔
It's reaaaaaally weird...

**Review by aniszr — APPROVED** [review]
Hello @boherm 

I retested your PR and make sure that cache is cleared and admin-new-theme is well generated :heavy_check_mark: 

The previousely mentioned problems are solved :

- Mobile -> Tab Stock -> Fix display for Add or subtract item input  :heavy_check_mark: 
- The **Cost price(tax excl.)** currency symbol is responsively changed when changing **Currency** field :heavy_check_mark: 

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/0677afb3-fc90-4abf-8945-0cfb7e5ca85c

Auto Test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5832815208 :heavy_check_mark: 

QA :heavy_check_mark: 

Thank you!

**Comment by MatShir** [comment]
🎉 thanks everyone

**Pull request merged**
