### PR TITLE
[-] FO: Wrong number of displayed products in Search

### PR DESCRIPTION
**Pull request by kpodemski**
How to check error?
1. Default product per page = 12
2. Go to category page, change product per page to 60, number of product will be now assigned  to cookie
3. Search for products where results is more than 12
4. You'll have maximum of 12 products displayed (without pagination) even if you found 50 products+.

Before:
https://drive.google.com/file/d/0B9iMp5W-IBKpYjlDUW14OGVBTTg/view?usp=sharing

After:
https://drive.google.com/file/d/0B9iMp5W-IBKpR2ZWMUZYRFpjQnc/view?usp=sharing

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for youyr PR. Are you testing a git version ?

This sounds like your issue https://github.com/PrestaShop/PrestaShop/pull/2349

Regards

**Comment by kpodemski** [comment]
Hi,

This is not related because we don't even see pagination before this change, after change from #2349 everything is the same as here "before".

**Comment by gRoussac** [comment]
Hi,

Ok thanks I get it now.

Regards

**Comment by kpodemski** [comment]
Hi @gRoussac 

I just noticed that these links from description was not available, I just fixed this issue and I hope you'll fined a solution for this problem if my solutions is not good enough.

**Comment by jeromenadaud** [comment]
Hi @kpodemski 

Thank you for your contribution.

Best regards.

**Pull request merged**
