### PR TITLE
[-] FO : Fixed bug when clicking on "Read reviews" or any anchors (#PSCSX-7495)

### PR DESCRIPTION
**Pull request by antho-girard**
## Description

This PR solves wrong behaviour when clicking on "Read reviews" button or any classic anchors in the product page: the available quanitity and add to cart button disappear and the text "This combination does not exist for this product. Please select another combination" shows up.
If product has at least one combination, problem doesn't occur.
## Steps to Test this Fix

1. Install/Enable the productcomments module for example.
2. Leave a comment on a product that has **no combination**.
3. On the product page (FO) click on "Read reviews".
4. Go on top of the page, there's no warning message anymore and "add to cart" button is still visible.
## Forge Ticket (optional)

Fixes ticket http://forge.prestashop.com/browse/PSCSX-7495

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/5280)

### CODE REVIEW

**Comment by xBorderie** [comment]
Feedback on the Forge ticket seems to indicate that this PR only solves half of the issues: clicking the "Write a review" button is also problematic.

**Comment by antho-girard** [comment]
It's strange, on a fresh install of 1.6.1.4, the "Write a review" button seems to works fine with the change.

**Comment by Polarforscher** [comment]
Hi, thanks for your efforts - much appreciated! I uninstalled then re-installed the module, made changes to the 4 lines but still the same problem with "Write a review", e.g.: http://www.montessorisupplies.co.uk/sensorial/298-knobless-cylinders.html

**Comment by Polarforscher** [comment]
Hi, 
I re-installed the whole shop from the beginning. 
For a while the product comments worked but now they're broken again. 
Same problem as as last time, the "Write a review" button is not clickable but at least the Add to Cart" button does not disappear! 
E.g.: http://www.montessorisupplies.co.uk/bead-material/277-golden-beads.html#new_comment_form
Any ideas?
Thanks a lot!

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
