### PR TITLE
Get notifications center independent twig component

### LINKED ISSUE #33179: Independent twig component: Notifications center
## Description

See #33101 for description in Step 2

This is the Notifications center part.

This component should be quite autonomous.

Blocked by https://github.com/PrestaShop/PrestaShop/issues/32988

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Get notifications center independent twig component
| Type?             | improvement
| Category?         |  BO
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | CI 🟢 and auto tests 🟢 
| Fixed ticket?     | Fixes #33179 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
lgtm but UI tests complain about bulk product deletion

**Comment by matthieu-rolland** [comment]
I restarted the failing test, it's not related to your PR I think...

**Review by M0rgan01 — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/5656508074

**Review by sallemiines — APPROVED** [review]
Hello @lartist 

Thank you for the PR !
[Automate tests](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5680194121) OK 
LGTM QA :heavy_check_mark: 

Thank you :rocket:

**Comment by nicosomb** [comment]
Thank you @lartist

**Pull request merged**
