### PR TITLE
[*] CORE : improve global performances

### PR DESCRIPTION
**Pull request by jocel1**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | improve global performances |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | run unit test |

proof_perf

### CODE REVIEW

**Comment by xBorderie** [comment]
Note to code reviewer: Easier to read with https://github.com/PrestaShop/PrestaShop/pull/5580/files?w=1 :)

**Comment by mickaelandrieu** [comment]
On PHP7, i5, 8Go de RAM

| branch      | command | Time and memory used
| ------------- | ---------------|----------------------------------------
| develop | php bin/phpunit -c tests/ | Time: 12.58 seconds, Memory: 68.00Mb
| hotfix-17-perfs | php bin/phpunit -c tests/ | Time: 12.63 seconds, Memory: 66.00Mb

**Comment by xBorderie** [comment]
Well it's the little things that count:

capturelittleimprovement

**Comment by jocel1** [comment]
@mickaelandrieu On a real shop with a siege benchmark before / after, it does improve performances :
https://www.dropbox.com/s/qx913gy7xz75x5q/1.7-opti.png?dl=0

**Comment by mickaelandrieu** [comment]
Thank you @jocel1, good enough to me :-)

**Pull request merged**
