### PR TITLE
[*] TR : Better spelling of Dutch tab names

### PR DESCRIPTION
**Pull request by firstred**
This PR has some better spellings of tab names in Dutch.
Also in order to keep up to date with CrowdIn translations.

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, @firstred !

@AlexEven, what do you think? :)

**Comment by firstred** [comment]
PR updated

**Comment by AlexEven** [comment]
Thank you @firstred !

Just one thing, you added back "CSV" for "Imports", could you please remove it? 
In 1.7 we want to drop the "CSV", import should be possible with other formats too!

Best,

**Comment by firstred** [comment]
Nice!
OK, I have changed it.

**Comment by xBorderie** [comment]
Alright! Merging this, thanks Michael!

**Comment by AlexEven** [comment]
:+1:

**Comment by firstred** [comment]
Oops. I forgot a few tabs. New PR: #5254

**Pull request merged**
