### PR TITLE
Change india address form

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The India address form should have a `state` field
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1873
| How to test?  | As a customer try to add an address in India

https://en.wikipedia.org/wiki/Address_(geography)#India

### CODE REVIEW

**Comment by aleeks** [comment]
We have to change the sql file when version will be fixed.. WIP

**Comment by maximebiloe** [comment]
Could you rename your SQL file by `1.7.1.x`, please?

**Comment by antoin-m** [comment]
Done :nail_care:

**Comment by aleeks** [comment]
Any QA here ?

**Pull request merged**
