### PR TITLE
Update CONTRIBUTORS.md to fix mispelled contributor name

### PR DESCRIPTION
**Pull request by helgvor-stoll**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x / 1.7.6.x
| Description?  | Please be specific when describing the PR. <br> Every detail helps: versions, browser/server configuration, specific module/theme, etc.
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17472)

### CODE REVIEW

**Comment by matks** [comment]
Hi @helgvor-stoll, as CONTRIBUTORS.md is a generated file, I need to check with @eternoendless if a manual modification, just like you suggest, is valid. If the generator does not acknowledge your modification, it will be erased next time we update the CONTRIBUTORS.md

**Comment by PierreRambaud** [comment]
AFAIK The Contributors files is generated depending on what you setting up in your git configuration when you committed.

**Comment by helgvor-stoll** [comment]
Hello,
It's ok. I changed the data in my github account
Kind regards
Helgvor

⁣Envoyé par TypeApp ​

Le 3 févr. 2020 à 09:21, à 09:21, GoT <notifications@github.com> a écrit:

**Comment by PierreRambaud** [comment]
@helgvor-stoll This data came from git, not GitHub :sweat_smile: 
You can retrieve these information by using
```
git config -l
# or 
git config user.name
```

**Comment by Progi1984** [comment]
@helgvor-stoll Have you got an answer from the team ?

**Comment by matks** [comment]
Hi,

It looks we have no answer from author.

I close this pull request as the topic seems outdated. If however you want to continue it, please ping us.

Thank you!

**Pull request closed without merging**
