### PR TITLE
Fix the except_pages in theme.yml

### PR DESCRIPTION
**Pull request by FrancMunoz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix the except_pages in theme.yml
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3756, http://forge.prestashop.com/browse/BOOM-3577
| How to test?  | Install a theme with except_pages in theme.yml.

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi @FrancMunoz 

Thanks for that PR !
We'll review it very soon, stay tuned :)

**Comment by Quetzacoalt91** [comment]
Hello @FrancMunoz,

Nice catch.
However, I would prefer to make sure the list sent to ThemeManager::doEnableModule() is already safe. If we don't, we must apply this fix on the install / uninstall / enable / disable functions which are almost the same.

Do you mind moving your fix in Theme:getModulesToEnable()?

We would get something like this:
```php
    public function getModulesToEnable()
    {
        $modulesToEnable = $this->get('global_settings.modules.to_enable', array());
        $modulesToHook = $this->get('global_settings.hooks.modules_to_hook', array());

        foreach ($modulesToHook as $hookName => $modules) {
            if (is_array($modules)) {
                foreach (array_values($modules) as $module) {
                    if (is_array($module)) {
                        $module=key($module);
                    }
                    if (null !== $module && !in_array($module, $modulesToEnable)) {
                        $modulesToEnable[] = $module;
                    }
                }
            }
        }

        return $modulesToEnable;
    }
```

**Comment by FrancMunoz** [comment]
Hi!

Sure! this would be better and safer. I Committed your proposal. 

Thank you!

**Review by Quetzacoalt91 — APPROVED** [review]
Tested and code reviewed

**Comment by Quetzacoalt91** [comment]
Thank you @FrancMunoz

**Comment by FrancMunoz** [comment]
It's a pleasure. Thank you!

**Pull request merged**
