### PR TITLE
Add new hook to add order actions in Back Office, on an order view

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Add a hook to add order action (button) in the detail of an order. |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Fetch this commit, register a module to the hook and see the result. |

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commits' names to use the NEW [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog tool?

To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this **must** be done via the command line: you can't do this just by changing the title of the pull-request from the GitHub interface!_ :)

Thank you!

**Comment by PrestaEdit** [comment]
Hi @xBorderie ,

It seems that my editor do more than I want, with a merge/new commit.

Do you want I close this one and create it again with the commit name with prefix, to be easier ?

**Comment by xBorderie** [comment]
You can simply squash the commits into one :)

See [this tutorial](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by xBorderie** [comment]
Or, you can close this PR and create a new one with a single commit :)

**Comment by PrestaEdit** [comment]
Hi @xBorderie ; was done on the #5626 (more faster for me now).

**Comment by xBorderie** [comment]
Haha, I understand, no soucÿ ;)

**Pull request closed without merging**
