### PR TITLE
1.7.

### PR DESCRIPTION
**Pull request by jonathanparentlevesque**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.
| Description?  | The menu in the BO doesn't scroll, which is a problem if your custom modules create new menus/submenus entries (those) are inaccessible). Add an invisible scrollbar.
| Type?         |  improvement 
| Category?     | BO
| BC breaks?    | No
| Deprecations? | No
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2625
| How to test?  | Scroll the menu (the scroll bar is invisible).

In "*admin-theme.css*":

`#nav-mobile{-ms-overflow-style: none;overflow-y: auto;}#nav-mobile::-webkit-scrollbar{display: none;}#nav-sidebar{-ms-overflow-style: none;overflow-y: auto;}#nav-sidebar::-webkit-scrollbar{ display: none;}`

In "*admin-theme.css*":

`.nav-bar{-ms-overflow-style:none;overflow-y:auto;}.nav-bar::-webkit-scrollbar{display:none;}`

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @jonathanparentlevesque 
I'm closing this PR because your branches aren't ok.
Thank you to make another PR with only YOUR commit.

Regards

**Comment by jonathanparentlevesque** [comment]
Hello Alex Sampiao / @alex.sampaio1991@gmail.com. 

I have written a support ticket with the code, you guys  ask me to post on github. Now, you ask me to rewritten the ticket while you just have to copy/past the code.in the he right files.

Usually I am paid to do the job and I already gave you one hour out of my personal to fix the problem.

Il y a toujours bien des limites à prendre le monde pour acquis tabarnacle.

My best regards, 
Jonathan Parent-Levesque

**Comment by aleeks** [comment]
@jonathanparentlevesque,
Maybe you want to merge your `develop` branch into `1.7.1.x` so you can try to change the `from branch` below the title.
Preston can help you if you follow his message!

Regards

**Comment by xBorderie** [comment]
Wow, there's no need to resort to profanity here. Please keep the comments clean.

When we see someone who apparently knows how to fix an issue, we always ask them to contribution their solution through a pull-request. This way, you get credit for your fix, while this shows us that you know how to use Git -- and therefore you have coding skills (rather than guessing the solution), which implies we'll have less testing to do.

Since you did not include your fix as a Git commit in your PR, we'll have to take it from here and include your fix ourselves. Thank you for trying.

Best regards,

-xb.

**Pull request closed without merging**
