### PR TITLE
Removed realpath for assets

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Removed realpath for assets
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | go to your front

Need https://github.com/PrestaShop/PrestaShop/pull/6919/files merged
Wip for test

### CODE REVIEW

**Comment by aleeks** [comment]
ping @mickaelandrieu @julienbourdeau  @Atchworks @alltheworld :p

**Comment by aleeks** [comment]
Don't merge before https://github.com/PrestaShop/PrestaShop/pull/6919, needed!

**Comment by Quetzacoalt91** [comment]
@aleeks,

I will have to test again without your PR, but on a shared hosting running with IIS, the lists of CSS and JS files to load are empty.

**Comment by aleeks** [comment]
@Quetzacoalt91 without, or with or both :p ??

**Comment by Quetzacoalt91** [comment]
I made only one test, WITH your PR: All assets are missing. :)

**Comment by aleeks** [comment]
need to merge https://github.com/PrestaShop/PrestaShop/pull/6918 berfore

**Review by mickaelandrieu — APPROVED** [review]

**Comment by maximebiloe** [comment]
If @mickaelandrieu approves! 😬
Thank you!

**Pull request merged**
