### PR TITLE
Simplify module manager, remove see more/less

### LINKED ISSUE #28116: "See more" / "See less" links in the "Module manager" tab
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

**"See more" / "See less" links in the "Module manager" tab**

See-more-less

### Describe the solution you'd like

Please kill the annoying "See more" / "See less" links in the "Module manager" tab. The modules page is dedicated to list the modules and work with them. Why do you want to hiding the modules on this page and force merchants and developers to make a few more useless clicks in order to see all modules installed in his PrestaShop? What is the idea behind the feature showing only first 6 modules in each category? What is benefit of this feature?

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR refactors and simplifies the module manager. It removes some old templates, styles, unused JS code. It also removes `See more` and `See less` from module categories. (PM validated)
| Type?             | improvement
| Category?         | BO
| BC breaks?        | partial - some unused twig files removed
| Deprecations?     | no
| How to test?      | Play around in module manager and see that it works the same as before, except you now see all the modules and don't have to click "see more" every time.
| Fixed ticket?     | Fixes #28116
| Related PRs       | 
| Sponsor company   | 

### List of deleted files
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_grid.html.twig
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/card_list_addons.html.twig
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/categories_card.html.twig
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/categories_grid.html.twig
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/grid_loader.html.twig
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/see_more.html.twig
- src/PrestaShopBundle/Resources/views/Admin/Module/Includes/sorting.html.twig

### CODE REVIEW

**Review by 0x346e3730 — APPROVED** [review]
+69 -866 that's a really good PR :+1:

**Review by matks — APPROVED** [review]
Looks good but even though BC breaks are allowed in major versions ; shouldn't we acknowledge them? Write a list of breaking changes?

**Comment by Hlavtox** [comment]
@matks ✅

**Review by FabienPapet — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I have tested your PR and it's good for me :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by Hlavtox** [comment]
@paulnoelcholot Thank you bro!

**Pull request merged**
