### PR TITLE
Leave the id unchanged if force_id is set to true in ObjectModel class

### PR DESCRIPTION
**Pull request by m1k3lm**
As a developer I would like to be able to extend this class and have the id unchaged if I define forced_id to true.
The same way that the id is not deleted before the insert, it shouldn't be set to 0 once the insert has taken place.

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | In MySql, when the row id is not generated by the autoincrement mechanism and is set in the insert query the `Db::getInstance()->Insert_ID()` statement returns 0. That's why I think that it should not be assigned to `$this->id` when `$this->force_id` is set to true.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Possible impacts? | If any part is using this it will be losing the id, if it works like this it means that it is not using the id once the insert has been done so would not be impacted by this change.
| How to test ? |I faced the problem when I needed an extension where I needed an ObjectModel that had predefined Ids.<br/>I made something like https://gist.github.com/m1k3lm/ac2a817685860eb471095fbd090b2589 and use it like:<br/>> $dummy = new Dummy(6);<br>> $dummy->dummy = 'dummy value';<br>> $dummy->update();<br>> echo $dummy->id;<br><br>I would expect the echoed `$dummy->id` to be 6 but I got 0.<br>After the PR `$dummy->id` echoes 6|

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24636)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Progi1984** [comment]
@m1k3lm  Thank you for your contribution. :hugs: 

Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Comment by matks** [comment]
Hello @m1k3lm did you see @Progi1984 request ? 😉

**Comment by m1k3lm** [comment]
Sorry @Progi1984, I missed the comment.

I faced the problem when I needed an extension where I needed an ObjectModel that had predefined Ids.
I made something like https://gist.github.com/m1k3lm/ac2a817685860eb471095fbd090b2589 and use it like:
``` php
$dummy = new Dummy(6);
$dummy->dummy = 'dummy value';
$dummy->update();
echo $dummy->id;
```

I would expect the echoed `$dummy->id` to be 6 but I got 0.
After the PR `$dummy->id` echoes 6

**Comment by m1k3lm** [comment]
@Progi1984 was my comment useful enough or do you need anything else?

**Comment by Progi1984** [comment]
@m1k3lm Thank your for the ping. :wink: Could you rebase as you have a conflicting file ? After that, I send your PR to QA.

**Comment by m1k3lm** [comment]
@Progi1984 ok, the problem is solved then. No need to merge.

**Pull request closed without merging**
