### PR TITLE
Only use unit_price_ratio when defined in Product

### LINKED ISSUE #19038: PHP Notice Product Class
#### PHP Notice on Product class

Hi! I check in new PS versions since 1.7.5 that in line 4889 there is a sentence that allways report me a PHP Notice:
NOTICE: PHP message: PHP Notice:  Undefined index: unit_price_ratio in /shared/httpd/novaut/classes/Product.php on line 4889

$row['unit_price'] = ($row['unit_price_ratio'] != 0 ? $row['price'] / $row['unit_price_ratio'] : 0);

#### Expected behavior
Is not an error of parenthesis clousure ?
The correct sentence will be 
$row['unit_price'] = (isset($row['unit_price_ratio']) && $row['unit_price_ratio' ] != 0) ? $row['price'] / $row['unit_price_ratio'] : 0;

Sorry if not an error ;)

Thanks a lot

#### Additional information

* PrestaShop version: 1.7.5 - 1.7.6
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ksaandev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check unit_price_ratio is defined before using it in Product class
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/19038
| How to test?  |  https://github.com/PrestaShop/PrestaShop/issues/19038

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19601)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@ksaandev Thank you for your contribution. :hugs: 

Could you give us a scenario which permits to test the bug before and after this PR ?

Thanks :+1:

**Review by matthieu-rolland — APPROVED** [review]

**Comment by ksaandev** [comment]
> @ksaandev Thank you for your contribution. 🤗
> 
> Could you give us a scenario which permits to test the bug before and after this PR ?
> 
> Thanks 👍

Just like https://github.com/PrestaShop/PrestaShop/issues/19038 described in I found these PHP notices into my logs:
`PHP Notice: Undefined index: unit_price_ratio in /www/httpd/ps/classes/Product.php on line 4889`

I dont know which actions are need to do to see them again

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-core-developers Need QA ?

**Review by matks — APPROVED** [review]
I dont think we need QA and we do not really know what to tell them 🤔

**Comment by PierreRambaud** [comment]
@matks So I merge it :D 

Thanks @shakaran

**Comment by matks** [comment]
> @matks So I merge it :D
> 
> Thanks @shakaran

You're a generous person ❤️ 

Thanks @ksaandev and @shakaran and @Veiss

**Comment by ksaandev** [comment]
Thanks guys !

**Pull request merged**
