### PR TITLE
Fix table responsive of multistore page

### LINKED ISSUE #24914: [BO] - Multistore page is not responsive
#### Describe the bug

Multistore page is not responsive.

#### Expected behavior
 
Multistore page should be responsive

#### Steps to Reproduce

1. **BO** > **CONFIGURE** > **Advanced Parameters** > **Multistore**
2. Try to minumise th screen size
3. See error (see screenshot n°1)
4. On **mobile** device 
5. check the multistore table
6. See error > the **Main url of this shop** label and the **url** are overlapped (see screenshot n°2)

**Screenshots**

- screenshot n°1

image

- screenshot n°2

image

#### Additional information

* PrestaShop version: 1.7.8.x & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Array was overlaping the panel, and URLs were overlapping with the title
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24914.
| How to test?      | Go on multistore page and see if screens in the issues are fixed
| Possible impacts? | Multistore page layout

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24918)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by florine2623** [comment]
LGTM

Thanks @NeOMakinG !

Although, I found this bug in page Image Settings 

https://user-images.githubusercontent.com/16019289/121911611-34081000-cd30-11eb-9aef-b5cf0b522cda.mov

@PrestaShop/product-team @prestascott 
Should it be fixed in this PR too or another one ?

Thanks!

**Comment by NeOMakinG** [comment]
@florine2623 another one, and maybe we need to test every legacy pages before :)

**Comment by florine2623** [comment]
Thanks @NeOMakinG , 
It is QA approved then !

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @florine2623

**Pull request merged**
