### PR TITLE
enhance phone number display and handling

### LINKED ISSUE #18928: ps_contactinfo module improvements
**New description**

I'd like to extend the original issue, the original issue title is flexible enough to make this seem possible.

**Is your feature request related to a problem?**
- The phone number provided to front page by module ps_contactinfo is not clickable. Using smartphone it is comfortable that phone number is active, the same as email address.
- The eMail Address should be encoded to be protected against SPAM bots

**Describe the solution you'd like**
- enclose the phone number in <a> tags
- For eMail Address make use of Smarty mailto & encode function for better spam bot protection (see #9180)

**Alternatives you've considered**
none

**Additional context**
none

**Original description :**
The phone number provided to front page by module ps_contactinfo is not clickable. 
Using smartphone it is comfortable that phone numer is active, the same as email address.

### PR DESCRIPTION
**Pull request by ziegenberg**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.x
| Description?  | Make the display of phone number in footer and contact page's left column configurable and make phone number clickable.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#18928.
| How to test?  |  - back office open Shop parameters > Contact > Stores > Contact details and add phone number <br> - Open front office and click on the phone number in nav bar at top of the page <br> - Open front office and click on the phone number in the footer at the bottom of the page <br> - Open front office, navigate to contact us page and click on the phone number <br> - on mobile devices the dialer interface should open<br><br> - Open Modules > Module Manager > ps_contactinfo > Configure and set Display phone number to "no" <br> - Open front office and the phone number in the footer at the bottom of the page should be gone <br> - Open front office, navigate to contact us page and the phone number should be gone

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19843)

### CODE REVIEW

**Comment by matks** [comment]
Hi @ziegenberg !

The elements you suggest putting in the template have been removed purposefully 🤔 in order to prevent spam. See the PR https://github.com/PrestaShop/PrestaShop/pull/17562/

So if we merge your PR, are we not opening the doors to spam again ? 🤔

**Comment by ziegenberg** [comment]
hi @matks!

the mentioned #17562 is about the email address, this PR is about the phone number and does not touch the email address. If this change is not desirable then #18928 maybe should be closed as won't fix.


But maybe the templates in the ps_contactinfo should also be changed to include the javascript scrambling.

**Comment by matks** [comment]
Hi @ziegenberg this PR stayed in Draft state for 6 months now. Did you find yourself focused on another topic, so you could not continue this?

**Comment by ziegenberg** [comment]
Hi!
Thx for the reminder, I'll look into it today

**Comment by PierreRambaud** [comment]
Hi @ziegenberg ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
