### PR TITLE
Deletes AdminModulesPositions legacy controller

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Deleted legacy AdminModulesPositions controller as corresponding page is migrated.
| Type?         | refacto
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | No changes in user interface

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13847)

### CODE REVIEW

**Comment by matks** [comment]
Thank you @zuk3975

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@zuk3975 Did you check `AdminModulesPositions` was not used anymore ? We've got some regressions because of that.

**Comment by zuk3975** [comment]
> @zuk3975 Did you check `AdminModulesPositions` was not used anymore ? We've got some regressions because of that.

Maybe i missed something. Whats wrong?

**Comment by zuk3975** [comment]
@matks, I've found some usages in js, not sure if it can be the reason of regression. Can't find any in php though. :/
1. associated with drag n drop https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/js/admin/dnd.js#L90
2. Module position specific js https://github.com/PrestaShop/PrestaShop/blob/1.7.6.x/js/admin/modules-position.js#L29

**Comment by matks** [comment]
We got a 404 on "Module Positions" page when we click on "Transplant a module"

**Comment by zuk3975** [comment]
> We got a 404 on "Module Positions" page when we click on "Transplant a module"

@matks, Ok (not ok at all :cry: ) seems that positions page isn't fully migrated then :/
https://github.com/PrestaShop/PrestaShop/blob/4edececed3066f483a472d2ac9f611a7e800ad60/src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController.php#L113
here it generates link refering legacy page (`http://prestashop.local/admin-dev/index.php?controller=AdminModulesPositions&addToHook`).

**Comment by matks** [comment]
@zuk3975 Do I create an issue for that ?

**Comment by zuk3975** [comment]
> @zuk3975 Do I create an issue for that ?

@matks, yes, please.

**Comment by matks** [comment]
@marionf Created it for us 😄 
https://github.com/PrestaShop/PrestaShop/issues/13935

**Pull request merged**
