### PR TITLE
[-] FO: fix when clicking filters labels, not checkbox. Fixed an

### PR DESCRIPTION
**Pull request by xGouley**
override of blocklayered. From #PSCSX-5838

### CODE REVIEW

**Comment by xGouley** [comment]
Travis seems to reject PR only on old versions of PHP, but there is no PHP modification, only JS.

**Comment by kelu95** [comment]
:+1:

**Comment by gRoussac** [comment]
Hi,

Please report on '1.6.1.x'.

Regards

**Comment by xGouley** [comment]
Closed: new PR made to report this fix on 1.6.1.x

**Pull request closed without merging**
