### PR TITLE
Update Validate.php

### PR DESCRIPTION
**Pull request by filipedanielpires**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | use of php native function filter_var to validate email's
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | In FO as a customer I should be able to register and login with a valid email.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9129)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Watch out with this function, it's currently not working with not latin characters:
```
filter_var('test@из.com', FILTER_VALIDATE_EMAIL); // false
filter_var('bonjouréé@gmail.com', FILTER_VALIDATE_EMAIL); // false
```

**Comment by filipedanielpires** [comment]
The current function validates emails like:
`test..@mail.com`
`tést@mail.com`

and those are not valid emails

**Comment by PierreRambaud** [comment]
For the double dot I'm agree, we need to catch this exception (dot on first or last) but for the second one it's valid. It's part of RFC 6531 (https://tools.ietf.org/html/rfc6531), more you can send with gmail for example `my.email+&é"'(-è_@gmail.com` . We need to remove the regex, and use a proper class, maybe EmailValidator from Symfony?

**Comment by filipedanielpires** [comment]
I've got this message:

`PHP Fatal error:  Uncaught exception 'Swift_RfcComplianceException' with message 'Address in mailbox given [tést@mail.com] does not comply with RFC 2822, 3.6.2.' in /var/www/public_html/tools/swift/classes/Swift/Mime/Headers/MailboxHeader.php:348`

but when the customer register it doesn't complain.

**Comment by PierreRambaud** [comment]
Yes, it's a know issue, we are working on it. 
And it look like the latest version of Switfmailer fix the problem but we can't used it due to php requirements issue (>=7.0 for Swift 6+). I will try to have a discussion with the team to find the best way to fix the problem (remove `é` even if it must be accept, or try to override Swift validator).

**Comment by mickaelandrieu** [comment]
Hello,
would you mind to complete the contribution table?

> Please indicate how to best verify that this PR is correct.

Mickaël

**Comment by PierreRambaud** [comment]
Hi again,

You can change the regexp with:
```php
    public static function isEmail($email)
    {
        $re = '/^[a-z\p{L}0-9!#$%&\'*+\/=?^`{}|~_-]+\.*[a-z\p{L}0-9!#$%&\'*+\/=?^`{}|~_-]+@[a-z\p{L}0-9]+(?:[.]?[_a-z\p{L}0-9-])*\.[a-z\p{L}0-9]+$/ui';
        return !empty($email) && preg_match(
            Tools::cleanNonUnicodeSupport($re),
            $email
        );
    }
```

I try with 
```
test+é..@gmail.com => false
test+é.@gmail.com => false
test+é123@gmail.com => true
..test+é.@gmail.com => false
test@gmail.com => true
```

I'm working on a fix for Swift Mailer, I'm having an error with Html component on some browsers when I register with `testé@gmail.com` for exemple, depends on how they implements the field type `email`.

**Comment by PierreRambaud** [comment]
Look like we can't do anything about special chars for now..
https://github.com/swiftmailer/swiftmailer/issues/898 :/ It comes with SwiftMailer 6.  
We will plan a major php update this year. 
At least you can change the regex if it's ok for you?

**Comment by filipedanielpires** [comment]
Do you think we can have this aproach:

<pre>if (preg_match('/[^\p{Common}\p{Latin}]/u', $email)) {
    return !empty($email) && self::nonLatinEmail($email); // actual method
}
return !empty($email) && filter_var(Tools::replaceAccentedChars($email), FILTER_VALIDATE_EMAIL); // new method
</pre>

**Comment by PierreRambaud** [comment]
Yes, I think we can try this approach :) it's a good idea ;)

**Comment by filipedanielpires** [comment]
Hi,

I made another commit but didn't used the Tools::replaceAccentedChars method, because it was accepted those mail's, and in fact they were valid by as part of RFC 6531, like you said before, but the email's were never sent because SwiftMail doesn't suport RFC 6531, and if that happens the customer cannot receive any emails.

**Comment by PierreRambaud** [comment]
Can you please indicate how we can tests your PR? Some use cases for example. Thanks

**Comment by filipedanielpires** [comment]
<pre>
$emails = [
    "test@mail.com",        // is valid
    "tést@mail.com",        // is invalid
    "test+é..@mail.com",    // is invalid
    "test+é.@mail.com",     // is invalid
    "test+é123@mail.com",   // is invalid
    "..test+é.@mail.com",   // is invalid
    "test@из.com",          // is valid
];

foreach ($emails as $email) {
    if (Validation::isEmail($email)) {
        echo $email . " is valid\n";
    } else {
        echo $email . " is invalid\n";
    }
}
</pre>

**Review by PierreRambaud — APPROVED** [review]

**Comment by marionf** [comment]
Hello @filipedanielpires 

Could you please complete the "how to test" line ?

Thank you

**Comment by PierreRambaud** [comment]
You can test to register with this e-mails:
```
    "test@mail.com",        // is valid
    "tést@mail.com",        // is invalid
    "test+é..@mail.com",    // is invalid
    "test+é.@mail.com",     // is invalid
    "test+é123@mail.com",   // is invalid
    "..test+é.@mail.com",   // is invalid
    "test@из.com",          // is valid
```

**Comment by marionf** [comment]
in FO it's OK but in BO I can create a customer account with these mail addresses :

` "tést@mail.com",        // is invalid `
` "test+é..@mail.com",    // is invalid `
` "test+é.@mail.com",     // is invalid `
` test+é123@mail.com",   // is invalid `

capture d ecran_666

For `"..test+é.@mail.com"` it's working I can't create a customer account in BO

capture d ecran_665

**Comment by SebSept** [comment]
Because, SwiftMail sends email, it may be better to let swift handle mail addresses check.

```php
include_once(_PS_SWIFT_DIR_.'swift_required.php');

class Validate extends ValidateCore
{

    /**
     * Check for e-mail validity
     *
     * En utilisant swift directement on s'assure que les adresses validées par Prestashop sont ok pour swift.
     *
     * @param string $email e-mail address to validate
     * @return bool Validity is ok or not
     */
    public static function isEmail($email)
    {
        return Swift_Validate::email($email);
    }

}```

**Comment by PierreRambaud** [comment]
We need to apply a patch on SwiftMailer https://github.com/swiftmailer/swiftmailer/issues/898

**Comment by matks** [comment]
@PierreRambaud It looks like issue on Swiftmailer is still not solved, can you confirm ?

**Comment by PierreRambaud** [comment]
@matks It should be ok with the dedicated package https://github.com/swiftmailer/swiftmailer/blob/6484964bfa7ce98cb3683726963e4dee0ac62aac/CHANGES#L89

**Comment by matks** [comment]
@atomiix you recently worked on Swiftmailer use in PrestaShop, can you tell us if your work did solve this issue ?

**Comment by atomiix** [comment]
@matks yep, it should be solved now, the `isEmail` function uses the same validation method that `SwiftMailer`. https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Validate.php#L60

**Comment by PierreRambaud** [comment]
Regarding @atomiix comment. We can close this pull request.
Thanks for your contribution.

**Pull request closed without merging**
