### PR TITLE
Importer fixes

### PR DESCRIPTION
**Pull request by tiennou**
In the process of migrating our 250+ categories and 2600+ products to Prestashop, the importer gave me some work to do, so I fixed some stuff.

There is at least a functional change here (see the individual commit description for more info for what I considered "bugs"), but it won't overwrite categories anymore if they share the same ID in the DB and in the file unless you set "Force IDs".

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by tiennou** [comment]
For the record, the underlying issues I wanted to fix ought to be still present.

- The 1st can be side-stepped by tweaking your custom-built exporter so IDs 1 & 2 don't appear.
- The 2nd can be side-stepped by tweaking your custom-built exporter so categories are ordered correctly w.r.t their parent-child relationship.

I tried to rebase that on `develop` but failed. If there's interest I can give it a spin again, but it's not on my plate anymore because side-steps.

**Comment by xBorderie** [comment]
Hey @tiennou, thanks for trying a rebase on `develop`, that's cool!

Your changes are indeed quite long, so I completely understand that it would be too much work to rebase directly. Do you think you could rebase each commit rather the whole thing? In any case, we're not asking you to do it RIGHT NOW: if you can do it, do it in your own time, there's no rush :)

Thank you for your contribution!

**Comment by xBorderie** [comment]
Hello!
The Importer has been partially reworked in 1.7. Is there a way you could have a look at it and tell us whether your suggestions are still relevant or not?
If so, could you remake that with one commit per PR, in order to have focused PRs?
Thank you very much!

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
