### PR TITLE
Customized Debug toolbar with PrestaShop application information

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Make debug toolbar display information about PrestaShop version and documentation instead of Symfony
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | none
| How to test?  | See screenshots

prestashop-profiler

block_opened

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8472)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Hello @mickaelandrieu, a unit test is failing : https://travis-ci.org/PrestaShop/PrestaShop/jobs/298303693#L928

**Comment by Quetzacoalt91** [comment]
OH YES, the missing information!

**Comment by mickaelandrieu** [comment]
> Hello @mickaelandrieu, a unit test is failing : https://travis-ci.org/PrestaShop/PrestaShop/jobs/298303693#L928

yes... but don't know why... the debug toolbar is not display on `AdminCartsController`

edit: fixed relaunching test suite

**Comment by Quetzacoalt91** [comment]
Now we have the PrestaShop version 2 times, but can we still have the Symfony version installed as well?

**Comment by LittleBigDev** [comment]
It will depend on PS version anyway (1 SF version = 1 PS version)
Edit : or am I wrong ??? :O

**Comment by Quetzacoalt91** [comment]
This information could be useful for module developers, and for us. We won't need to reinstall a previous version of PresteShop just for having the related Symfony version.

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 you still have it

sf_version

but still, I've improved the block, wdyt?

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
All good for me, thanks!

**Pull request merged**
