### PR TITLE
Add rel="nofollow" to prestashop website link

### LINKED ISSUE #15953: Add attribute rel="nofollow" on prestashop.com link in PS stores
Hello,

To prevent Google from considering traffic to prestashop.com coming from "2019 - ecommerce software by PrestaShop" as fake, we need to add the attribute rel="nofollow". 
This mention is available by default in all footers from 1.7 stores.

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | all is in title
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15953

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15959)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
lgtm

Thank you @jf-viguier 👍

**Comment by matthieu-rolland** [comment]
@jf-viguier could you please fix your conflicts? Maybe you did your modification from the develop branch?

I think your fix is supposed to be based on 1.7.6.x

**Review by matthieu-rolland — CHANGES_REQUESTED** [review]
Conflicts must be solved

**Comment by jf-viguier** [comment]
Yes, i'm in the develop branch. How can I solve this ? Another PR on 1.7.6 branch ?

**Comment by matks** [comment]
> Yes, i'm in the develop branch. How can I solve this ? Another PR on 1.7.6 branch ?

The easiest way is to create a new branch, originating from 1.7.6.x branch, and to cherry-pick your commit in it.

I did it for you 😉 see https://github.com/PrestaShop/PrestaShop/pull/15963

**Comment by jf-viguier** [comment]
ok @matks

**Pull request closed without merging**
