### PR TITLE
Add actionPriceCalculation hook

### LINKED ISSUE #23246: New hook for product price
#### Is your feature request related to a problem?

As a module developer I have a need to set the product price to what I want.

Having a hook `actionGetProductPrice` that could return new price for the product could open quite a few possibilities for modules without using overrides.
* realtime pricing from erp
* totally new discount processes
* etc

#### Describe the solution you'd like

Something like this:

```php
    public function getPrice(
        $tax = true,
        $id_product_attribute = null,
        $decimals = 6,
	$divisor = null,
        $only_reduc = false,
        $usereduc = true,
	$quantity = 1
    ) {
        $origprice = Product::getPriceStatic((int) $this->id, $tax, $id_product_attribute, $decimals, $divisor, $only_reduc, $usereduc, $quantity);
       $hooked_price = Hook::exec('actionGetPrice', ['product'=>$this->id, 'tax'=>$tax, 'id_product_attribute'=>$id_product_attribute, 'decimals'=>$decimals, 'divisor'=>$divisor, 'only_reduc'=>$only_reduc, 'usereduc'=>$usereduc, 'quantity'=>$quantity, 'origprice'=>$origprice];
);
       if($hooked_price) {
          return $hooked_price;
       }

        return $origprice;
    }
```

Totally untested code, just the idea.

Ideally the hook should also have the possible customer and cart objects (if the price of the product depends on other stuff in the cart that can be calculated also).

#### Alternatives you've considered

At the moment override seems to be the only way to affect product pricing in anyway from a module.

#### Additional context

The cart should also take these calculations in to account for this to be usefull.

Another similar attribute is stock level...

### PR DESCRIPTION
**Pull request by carmas123**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.8.x
| Description?      | With this hook the developer can change the result of method priceCalculation.
| Type?             | improvement / new feature
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes #23246 
| How to test?      | his is simply a new hook
| Possible impacts? | Nothing

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27915)

### CODE REVIEW

**Review by carmas123 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27915#-:-MyCWXT29tCg58yzZ_W7:bb6un1j)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @carmas123)

**Comment by jolelievre** [comment]
You shouldn't target 178x branch but develop instead. This hook is a new feature so it won't be integrated into 178 version as a patch.

**Comment by jolelievre** [comment]
Especially here it creates lots of conflicts because you created a branch based on develop which you try to merge in 178x, so the diff is huge.

**Comment by carmas123** [comment]
Ok the best way is for me to remove my fork and recreate all from begin.

**Comment by carmas123** [comment]
@jolelievre what do you think?

**Pull request closed without merging**
