### PR TITLE
Update CompareProduct.php

### PR DESCRIPTION
**Pull request by Mehdib92**
The $period var was not taken into account in the SQL.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thnak you for your PR, nice catch. Can you please make it again on 1.6.1.x branch ? and please a quick look to http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

I beleive you wanted to wether write 

```
'.$interval.'
``` 

Thank you.

Regards

**Comment by Mehdib92** [comment]
Ok. 

I just did it, it should be ok now. 

Sorry for the errors, this is my first commit :)

**Comment by gRoussac** [comment]
No problem !

**Comment by maximebiloe** [comment]
Hello,

The compare products features has been dropped in PrestaShop 1.7, so let me close this PR.

Regards.

**Pull request closed without merging**
