### PR TITLE
Fix to show only attributes associated to the context shop in product combinations

### LINKED ISSUE #20022: In Multistore, product attributes aren't displayed when created for a specific shop
#### Describe the bug

In the product editor, within a multi-store with a shop context selected, it's not possible to use attributes that were created specifically for a specific store.

#### Expected behavior

Show the product attributes associated to the shop in context.

#### Steps to Reproduce

1. In a multi-store, create attributes and assign different shops for each one
2. try using them in the product editor

**Screenshots**

https://streamable.com/17qk9a

#### Additional information

* PrestaShop version: Develop / 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | In the product editor, within a multi-store with a shop context selected, it's not possible to use attributes that were created specifically for a specific store.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #20022
| How to test?  | In a multi-store, create attributes and assign different shops for each one. Then try using them in the product editor. Error video: https://streamable.com/17qk9a

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19969)

### CODE REVIEW

**Comment by Progi1984** [comment]
@Rolige  Thank you for your contribution. :hugs: 

Would you mind to rebase your pull request to remove Merge Commit ? 
Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

**Comment by Rolige** [comment]
> @Rolige Thank you for your contribution. 🤗
> 
> Would you mind to rebase your pull request to remove Merge Commit ?
> Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?
> 
> Thanks 👍

Issue created! About to rebase, do you have a tutorial of how to achieve this with a forked repo maintained with "upstream"?

**Comment by NeOMakinG** [comment]
- git checkout develop
- git pull upstream develop
- git checkout Rolige-fix-attributes-by-shop
- git rebase develop

then you'll have some conflict maybe (or not), every time you git conflict :

- git status
and fix every files that are not git added

then

- git rebase --continue

and when every changes applied

- git push origin Rolige-fix-attributes-by-shop -f

Try it :)

Thanks for you'r contrib!

**Comment by Rolige** [comment]
> * git checkout develop
> * git pull upstream develop
> * git checkout Rolige-fix-attributes-by-shop
> * git rebase develop
> 
> then you'll have some conflict maybe (or not), every time you git conflict :
> 
> * git status
>   and fix every files that are not git added
> 
> then
> 
> * git rebase --continue
> 
> and when every changes applied
> 
> * git push origin Rolige-fix-attributes-by-shop -f
> 
> Try it :)
> 
> Thanks for you'r contrib!

Thanks but it doesn't work :(

**Comment by matks** [comment]
Hi everyone,

It looks like this PR is not moving anymore. I close this pull request as it seems stale. Feel free to re-open it if you have time to work on it 😉  .

Thank you!

**Pull request closed without merging**
