### PR TITLE
Functional tests - Refacto categories tests

### PR DESCRIPTION
**Pull request by nesrineabdmouleh**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Refacto categories tests
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no need
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25233)

### CODE REVIEW

**Review by boubkerbribri — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by boubkerbribri — DISMISSED** [review]
WAIT FOR 1.7.8.0 RELEASE

**Comment by matks** [comment]
Re-running the CI

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
CI failing because of https://github.com/PrestaShop/PrestaShop/issues/25317 . PR not related to https://github.com/PrestaShop/PrestaShop/issues/25317

QA team has defined the scope of changes that need to be embedded inside 1.7.8.0 RC1 build 2. This PR is inside the list.

**Comment by matks** [comment]
Thank you @nesrineabdmouleh

**Pull request merged**
