### PR TITLE
InkExtension added to Twig

### LINKED ISSUE #25862: Allow to use inky_to_html in twig emails templates
#### Is your feature request related to a problem?

With prestashop v8 we are able to use https://twig.symfony.com/doc/3.x/filters/inky_to_html.html since we are using twig 3.x version. This might be huge for developers that are working on email templates. We will be able to simplify our twig files with ink templating language.

#### Describe the solution you'd like

I think we should add inky_to_html filter to twig. It might be really new cool feature in prestashop v8 with foundation emails allowing us to create themes with scss and simple ink template language. Adjusting emails to FO project might be just few lines of scss code with variables. Changes to email template will hurt less (right now eyes are bleeding when you are reading that output code in twig) and cost us less time.

### PR DESCRIPTION
**Pull request by Oksydan**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | This PR only adding inky support to twig email template. We will be able to use inky and foundation email framework to speed up our emails development. 
| Type?             | new feature
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25862
| How to test?      |  1. Download [inkytest.zip](https://github.com/PrestaShop/PrestaShop/files/9728521/inkytest.zip). Unzip file and place it to `rootDir/mails/modern` directory. Zip file contains `core/inky-example.html.twig` and two styles files that you should place inside `rootDir/mails/modern/assets` directory. <br> 2. Go to BO `Design->Email theme->Generate emails form`. Select `Select your email theme - modern`, `Select your language - select any language`, `Select the theme you want to overwrite - core`, `Overwrite templates - set to Yes`, CLICK - `Generate emails`.<br> 3. Right now got to directory `rootDir/mails/SELECTED_LANG/` and look for `inky-example.html`. Open that file in your browser, it should contains title and 3 columns with heading and buttons.<br> 4. Check other emails templates is there is any differences (shouldn't).
| Possible impacts? | It would be good to check other emails templates but that might be waste of time since filter is applied inside twig template via `apply inky_to_html`.

### CODE REVIEW

**Comment by FabienPapet** [comment]
Hello, 

Thank you for the PR. I think there will be no problem to add it in the core, but you need to create the service definition and tag it as a twig extension if you want to add this feature. Adding an extension in the  constructor is not the way to go here.

**Comment by Oksydan** [comment]
Hi @FabienPapet 
thanks for your CR, changes applied. 
Symfony and services are still new to me. I didn't know that is possible to register it this way, thank you for taking your time ❤️

**Review by atomiix — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by kpodemski** [comment]
It probably requires QA by the dev. To be confirmed by @PrestaShop/qa-team

**Comment by Robin-Fischer-PS** [comment]
Yep, a QA by dev would be nice in this one !

Thanks for the ping @kpodemski and for the PR @Oksydan :)

**Comment by Hlavtox** [comment]
Works perfectly @Oksydan!!!
- Email using foundation & inky generated perfectly
- Txt version generated properly
- There was no other change in the emails except the new template you added

One thing to note. It requires PHP `extension=xsl` enabled to work - a requirement of `pinky` package, installed along with `inky`.

**Video:**
https://user-images.githubusercontent.com/6097524/206590707-703e8bca-f2f5-4d74-877b-0f583d8a6338.mp4

**Comment by kpodemski** [comment]
Hi @Oksydan 

There's a need for a rebase because of the `composer.lock`

**Comment by Oksydan** [comment]
@Hlavtox @kpodemski branch rebased

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@Hlavtox do you have tests ready to just regenerate emails again?

**Comment by Hlavtox** [comment]
Thanks @Oksydan, confirmed, works perfectly!

email

**Comment by Hlavtox** [comment]
@Oksydan Bro, could you open a new PR with this feature? ;-) Now is the time! I will test it. ✌️

**Pull request merged**
