### PR TITLE
Form type `MaterialChoiceTableType` introduce `display_total_items` form `option`

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | `MaterialChoiceTableType` introduce `display_total_items` form `option`.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See https://github.com/PrestaShop/PrestaShop/discussions/35551
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/8173704811
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/discussions/35551
| Related PRs       | N/A
| Sponsor company   | Evolutive

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @PululuK ,

I checked on page Customers from BO, but I don't see the total displayed.

Screenshot 2024-03-06 at 15 45 29

Am I missing something ?
Thanks!

**Review by FabienPapet — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @PululuK,

I tested your PR and I found a bug as you can see : https://www.loom.com/share/4ed05e1152c44c889d131321c1815bf3?sid=3db95e05-3065-4633-a88c-75370220bdc7

1. Click to select all
2. Save
3. uncheck all groups except "select all"
4. Save
5. Error

**Comment by PululuK** [comment]
Hi @paulnoelcholot,
This is not a bug, the total indicated the number of elements in the list and not the number of elements selected :)

**Comment by paulnoelcholot** [comment]
@PululuK 

HTTP 400 BAD REQUEST 
Input value "customer" contains a non-scalar value.

This is not a bug?

Check my step to reproduce and watch the record until the end please :)

**Comment by PululuK** [comment]
@paulnoelcholot seem not related to my PR

**Comment by paulnoelcholot** [comment]
@PululuK 

Yes indeed, my sorry, it's a regression of develop...

So it's good for me, thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by PululuK** [comment]
Thanks @paulnoelcholot

**Pull request merged**
