### PR TITLE
Make the sub-categories disabled when you edit the category

### PR DESCRIPTION
**Pull request by hibatallahAouadni**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | the problem is that category will be deleted when you try to add main cat to sub-category
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8220 and http://forge.prestashop.com/browse/BOOM-3114
| How to test?  | try to edit a category, you will find all its sub-categories are disabled, so you can't add to one of its sub-cat.

### CODE REVIEW

**Comment by hibatallahAouadni** [comment]
the PHP part is Thierry PR: https://github.com/PrestaShop/PrestaShop/pull/6318 and for the JS part has to be "Cherry-picked". Ping @aleeks @marionf

**Comment by maximebiloe** [comment]
Hello @hibatallahAouadni,

Can you make the same PR on `1.7.1.x` branch, please?
Thank you.

**Comment by hibatallahAouadni** [comment]
@maximebiloe yep with pleasure :)

**Comment by maximebiloe** [comment]
Thank you @hibatallahAouadni

**Comment by aleeks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/7935

**Pull request merged**
