### PR TITLE
Migrate make into composer script

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Migrate make into composer script. Also solves https://github.com/PrestaShop/PrestaShop/pull/23964#discussion_r610664149
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | GH CI must pass
| Possible impacts? | Developers using `make assets` must use `composer build-assets` now

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23982)

### CODE REVIEW

**Review by Progi1984 — CHANGES_REQUESTED** [review]
I'm against this PR. It's a bad practice to put front end behavior in PHP package manager. And vice-versa. It's why we use make which it does for this.

**Comment by mvorisek** [comment]
> 
> 
> I'm against this PR. It's a bad practice to put front end behavior in PHP package manager. And vice-versa. It's why we use make which it does for this.

This project can not be installed without `composer` thus composer is required. Requiring `make` (not available on Windows) is on the other side absolutely not needed. It can also help reduce the files in the root directory.

**Comment by PierreRambaud** [comment]
> > I'm against this PR. It's a bad practice to put front end behavior in PHP package manager. And vice-versa. It's why we use make which it does for this.
> 
> This project can not be installed without `composer` thus composer is required. Requiring `make` (not available on Windows) is on the other side absolutely not needed. It can also help reduce the files in the root directory.



> > I'm against this PR. It's a bad practice to put front end behavior in PHP package manager. And vice-versa. It's why we use make which it does for this.
> 
> This project can not be installed without `composer` thus composer is required. Requiring `make` (not available on Windows) is on the other side absolutely not needed. It can also help reduce the files in the root directory.

I'm sorry, but make command is available on Windows, you have a ton of ways to use it via git bash, gnuwin32, etc.
As @Progi1984 , I'm against having nodejs commands inside composer commands.

**Comment by mvorisek** [comment]
I mean available by default :)

> I'm against having nodejs commands inside composer commands.

I am againt having composer commands inside make, see https://github.com/PrestaShop/PrestaShop/pull/23982/files#diff-04dff3f67f336c66337155d1fcf858d9f53a6e1181d05baf629dd804b6637363R65 , with make, no args can be passed by composer.

Having a makefile to call another command then not helpful. To make everyone happy, I propose to update this PR to drop the makefile completely, eg. call the one script to build assets directly (and revert the composer config change).

**Comment by matks** [comment]
Hi I dont understand why wanting to remove `makefile` ? Makefiles have been used for fifty years now, I dont see why it's a problem.

If we have php-only commands we need to reuse often we can make them composer commands
If we have node-only commands we need to reuse often we can make them npm commands
If we have cross-language commands we need to reuse often we can use a cross-language tool to store them, and makefile seems a valid choice to me.

Personally I would rather drop all npm and composer commands to have make commands only to have a single unified ways to store such commands 😄  but it looks like many people have different visions on what should be done.

**Comment by mvorisek** [comment]
Please merge https://github.com/PrestaShop/PrestaShop/pull/23886 first and I will update this PR.

**Pull request closed without merging**
