### PR TITLE
Enhance TemplateVarShop Function with Shop Group ID for Improved Multi-Shop Support

### PR DESCRIPTION
**Pull request by OrionCodeDev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Added the parameter 'id_shop_group' => $this->context->shop->id_shop_group to the function getTemplateVarShop(). This change allows better utilization and differentiation of multiple shop groups in templates. <br> This modification affects the template variables for shops by including the shop group ID, facilitating improved customization and handling in multi-shop environments.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Verify that the getTemplateVarShop() function now includes the 'id_shop_group' parameter in its output. Ensure templates utilizing this function correctly display and differentiate shop groups. Test with multiple shop groups to confirm the functionality. Now you can use in FO for example {if $shop.id_shop_group == 3}
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/9713992877
| Fixed issue or discussion?     | --
| Related PRs       | --
| Sponsor company   | Code Olympus Studio

**copy of #36450  Reason: Rebase to 8.1.x thanks: @kpodemski for help**
**this change should be included in every version, as it enhances the functionality by allowing better differentiation and utilization of multiple shop groups in templates.**

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Comment by florine2623** [comment]
@ChronoBrake ,

Could you explicit the How to test steps please ? :)

Thanks!

**Comment by OrionCodeDev** [comment]
> @ChronoBrake ,
> 
> Could you explicit the How to test steps please ? :)
> 
> Thanks!

To test the variables in a random Smarty template (your choice) file on the front office, follow these steps:

1. **Open the Smarty Template File**:
   - Open the desired `.tpl` file in your front office where you want to test the variables.

2. **Insert the Test Variables**:
   - To display all parameters provided by the `getTemplateVarShop()` function, insert the following line in the `.tpl` file:
     ```smarty
     {$shop|@var_dump}
     ```
   - To display the new group ID of the current shop, insert:
     ```smarty
     {$shop.group_id}
     ```

3. **Save the File**:
   - Save the modified `.tpl` file after adding the above lines.

3a. Refresh cache (sometime we need to clear cache to see new version of modified file)

4. **Load the Webpage**:
   - Load the webpage in your browser where this template file is used.

5. **Check the Output**:
   - For `{$shop|@var_dump}`: You should see all parameters and their values provided by `getTemplateVarShop()` displayed on the webpage.
   - For `{$shop.group_id}`: You should see the group ID of the current shop displayed on the webpage.

These steps will allow you to test and view the data available in the Smarty template context for your front office.

**Review by florine2623 — APPROVED** [review]
Hello @ChronoBrake ,

The auto tests are broken, I have relaunched them a few times : https://github.com/florine2623/testing_pr/actions/runs/9713992877
I need @PrestaShop/qa-automation to verify that it is QA OK before merging the PR. 

Other than that, I tested the PR, LGTM.

I have the right information depending on the shops/group shop I'm in.
Screenshot 2024-07-01 at 10 59 50
Screenshot 2024-07-01 at 11 00 02

**Comment by florine2623** [comment]
Waiting for @PrestaShop/qa-automation for their approval :)

**Comment by Progi1984** [comment]
@florine2623 It's a GO :green_circle:

**Comment by florine2623** [comment]
Thanks @Progi1984 !

**Review by boherm — APPROVED** [review]

**Comment by boherm** [comment]
Merged! Thanks @ChronoBrake ;)

**Pull request merged**
