### PR TITLE
Improve E2E tests

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add option to specify admin email & password, rename path in TEST_PATH to prevent the usage of PATH / path variable. Allow us to test https install
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Wait for CI

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9301)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Tests are failing due to the deactivation of mbo module.

**Comment by PierreRambaud** [comment]
Still waiting for the mbo module when installing prestashop.

**Comment by PierreRambaud** [comment]
@fatmaBouchekoua Any idea about why my tests are broken with module? everything is ok local, and I revert everything about MBO.

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
LGTM, good job @PierreRambaud

**Pull request merged**
