### PR TITLE
[-] CORE : wrong parameter name for controller in Dispatcher::createUrl

### PR DESCRIPTION
**Pull request by Shagshag**

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi @Shagshag!

Sorry for the long response time…

Can you explain what it does and how to test it?
The only tests done with `fc' are like `Tools::getValue('fc') == 'module'`…

Thank you!

**Comment by firstred** [comment]
This doesn't look correct to me.

**Comment by xBorderie** [comment]
@Shagshag Could you give more information about you're trying to achieve here? 
Thank you!

**Comment by Shagshag** [comment]
@xBorderie @Shudrum
Don't remember... guys this PR is more than one year old!

it was related to module controller URL if pretty URLs are not enabled and this https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Dispatcher.php#L775 but I don't remember more.

**Comment by thierrymarianne** [comment]
Thank you for your reply. Since it is not quite clear why we should consider this parameter is wrong, we have to close this.

**Pull request closed without merging**
