### PR TITLE
Make PrestaShop compatible with composer 2.0

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Now that composer 2.0 is released, we can't use it on PrestaShop because we're using an incompatible dependency ([composer/installers](https://packagist.org/packages/composer/installers)). This PR fixes it.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Try `composer install` with both composer 1.x & composer 2.0. You shouldn't get any error.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21609)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
Re-running as PHP CS Fixer GA failed for a weird reason 🤔

**Comment by matks** [comment]
No it fails again
```bash
Run ./vendor/bin/php-cs-fixer fix --dry-run --diff

In ToolInfo.php line 50:
                         
  Undefined index: name  
                         
Error: Process completed with exit code 1.
```

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by kpodemski** [comment]
Is everything ok here? Those out of scope changes are ok?

**Comment by jolelievre** [comment]
@kpodemski Unfortunately all our CI process were blocked because of this so we don't have much choice However the change is localized and we keep compatibility with composer 1 AND 2 so I guess we're fine

**Comment by eternoendless** [comment]
I think the code changes are out of scope and if the style linter forces them then those rules should be deactivated

**Comment by atomiix** [comment]
@eternoendless I think it's a bug that has been fixed for the rule `phpdoc_var_without_name` so it makes sense to fix the comments rather than disabling the rule.

**Review by matks — APPROVED** [review]

**Comment by eternoendless** [comment]
Validated by automated tests, thanks @atomiix

**Pull request merged**
