### PR TITLE
Remove deprecated TypeaheadRedirectionTargetTransformer

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated TypeaheadRedirectionTargetTransformer and its service
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no, removed deprecated class
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | N/A
| Possible impacts? | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26169)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]
Please remove the test `Tests\Unit\PrestaShopBundle\Form\DataTransformer\TypeaheadRedirectionTargetTransformerTest`, too.

**Review by matthieu-rolland — COMMENTED** [review]
unit tests broken (need to remove related tests too), otherwise LGTM 👍

**Comment by tegbessou** [comment]
PR is valid IMO

**Review by Progi1984 — COMMENTED** [review]
@matks Thank you for your contribution. Could you document the BC break, please ?

**Comment by matks** [comment]
> @matks Thank you for your contribution. Could you document the BC break, please ?

There is no BC break.

We do not promise backward compatibility on deprecated classes, because depreciation is exactly saying that no backward compatibility will be provided on this usecase.

Look at how Symfony does this: 
- PR https://github.com/symfony/symfony/pull/39579 introduces a BC break => `BC Break` label is applied to PR
- PR https://github.com/symfony/symfony/pull/43118 removes deprecated code => no `BC Break` label is applied

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
1.7.9.0 is the future version (never changed to 8.0 :p)

**Comment by Progi1984** [comment]
@PierreRambaud Thanks for the comment. We updated messages in #26382.

**Comment by PierreRambaud** [comment]
I talked to @matks 
He told me this class has been added only for the new Product Page V2, so it can be removed but has to be mentioned in the PR description.

**Comment by matks** [comment]
Closing I think I will never have the time to continue this topic and it is not a must-have.

**Pull request closed without merging**
