### PR TITLE
[-] BO : Meta title and description use textarea

### PR DESCRIPTION
**Pull request by petyuska**
Meta title and description use textarea instead of input.
Meta description usually a longer text.
Admin UI improvement.

### CODE REVIEW

**Comment by Nobodaddy** [comment]
No offense, but this change makes no sense. For SEO the meta title shouldn't exceed 70 chars, the meta descriptions 160. This limit was applied to the products section, why now a different solution for categories?

**Comment by inetbiz** [comment]
+1

**Comment by inetbiz** [comment]
@Nobodaddy Maybe use textarea with character limit? Yoast SEO for WordPress UX also uses a text area and warns you when you exceed 160

**Comment by Nobodaddy** [comment]
Nope, you cannot limit a textarea in PrestaShop!

**Comment by inetbiz** [comment]
@Nobodaddy 
```
<textarea maxlength="number">
```

**Comment by Nobodaddy** [comment]
lol, try it out! It's not this easy in this case!

**Pull request merged**
