### PR TITLE
Classic theme footer block design improvement

### LINKED ISSUE #11490: classic theme footer block design improvement
**Describe the bug**
Contact block has extra spaces in the left side and border compare to other footer columns of classic theme footer. We should remove that extra space for better UX.

**Screenshots**

footer

**Additionnal information**
PrestaShop version: 1.7.4.4

### PR DESCRIPTION
**Pull request by dineshbadrukhiya**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Contact block has extra spaces in the left side and border compare to other footer columns of classic theme footer. We should remove that extra space for better UX.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |  #11490 
| How to test?  | Check the footer Contact block.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11491)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Requesting UX validation

**Comment by marionf** [comment]
@dineshbadrukhiya can you rebuild assets please ?

**Comment by dineshbadrukhiya** [comment]
@marionf Okay Np. I will.

**Comment by dineshbadrukhiya** [comment]
@marionf Don’t merge this PR, as there are unwanted commits by mistake. I don’t know how to delete this commits. I will try to remove.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
This PR needs one more rebase to fix the conflicts.

**Comment by dineshbadrukhiya** [comment]
@Quetzacoalt91 I have no idea how to rebase. Can you do this for me?

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by dineshbadrukhiya** [comment]
@Quetzacoalt91 Thanks.

**Comment by marionf** [comment]
@TristanLDD Is it ok for you ?

capture d ecran_683

**Comment by TristanLDD** [comment]
@marionf  Ok for me !

**Comment by PierreRambaud** [comment]
Thanks @dineshbadrukhiya

**Pull request merged**
