### PR TITLE
Fix uses of #fff instead of $white in the classic and new-theme scss

### LINKED ISSUE #23759: The project uses #fff a lot of times instead of the $white var
#### Describe the bug

Legacy developers were using #fff variables everywhere instead of using the $white variable which is way more maintainable

#### Expected behavior

Using $white everytime you need the white color

####
No need to reproduce, it's mainly a dev thing

* PrestaShop version: develop

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Using #fff instead of $white variable is making things unmaintanable when you need to replace every white by another color
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23759.
| How to test?      | Need to be tested by a dev I think => `grep -r '#fff' ./` inside the `classic/_dev` and `new-theme` directory and only one occurance should appear (also check a bit the FO and BO to see if nothing changed but well, should be fine!
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23760)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by sowbiba — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
I think it can be tested by a dev easily

**Comment by Progi1984** [comment]
> I think it can be tested by a dev easily

@PrestaShop/qa-functional OK with that ?

**Comment by Robin-Fischer-PS** [comment]
OK for QA by dev :)

**Comment by Progi1984** [comment]
> OK for QA by dev :)

Will be done next year :trollface:

**Comment by atomiix** [comment]
@NeOMakinG I got only 1 occurence in `/themes/classic/_dev/` but I got more on `/admin/themes/new-theme/`:

Capture d’écran 2021-04-07 à 10 23 37

**Comment by NeOMakinG** [comment]
Damn, it's due to merged stuff after the PR

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by atomiix** [comment]
LGTM!
Capture d’écran 2021-04-07 à 17 37 54

It's QA ✔️

**Pull request merged**
