### PR TITLE
Release/manual verifications 1789

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixes after manual verifications to release 1.7.8.9
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | -
| Fixed ticket?     | -
| Related PRs       | -
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by djoelleuch** [comment]
Hello @mflasquin 
I have noticed that there are some checks on CI that haven’t been completed.

image

Could you please check it before starting testing it ?
thanks !

**Review by jolelievre — DISMISSED** [review]
Thanks @mflasquin

**Review by jolelievre — APPROVED** [review]

**Comment by jolelievre** [comment]
I launched the tests locally since the CI is broken:

- integration tests: OK
- behaviour tests: OK
- phpunit-legacy tests: OK
- phpunit-endpoints tests: OK
- unit-tests tests: OK
- phpunit-sf tests: OK
- phpunit-controllers: OK
- phpunit-admin: ALmost ok, one unit test is failing but it doesn't seem to be related to this PR or even this version, I tested with the version 1.7.8.0 and the same test is failing, in `DeliveryControllerTest:testPdfActionWithInvalidData` but this use case can't happen in the BO unless you forcefully modify the input types to be able to force an invalid value Then the SQL query fails nd returns an error, previously it redirected towards the page with session error message I don't think it should be blocking for the PR or even the release

**Comment by mflasquin** [comment]
Failing test on @jolelievre's environment are working on my environment :smile:

**Comment by jolelievre** [comment]
QA by dev validated!

**Pull request merged**
