### PR TITLE
Fix map translatable fields

### PR DESCRIPTION
**Pull request by fest73**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix map translatable fields
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes an [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | Add custom field in product for example description_2, during iteration description for lang id 2 replace element of array with name description_2

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15718)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi and thanks for your contribution.

Could you please create an issue?

**Comment by fest73** [comment]
@PierreRambaud This caused a problem for me, as a result of which I found such a solution

**Comment by PierreRambaud** [comment]
@dariusakafest I understand, but this require an issue in order to help us to reproduce and see if the fix is pertinent.

**Comment by fest73** [comment]
@PierreRambaud Add field "description_2" in product object.
Next, implement it through the Symphony builder forms, so that another tab description is displayed in the product editing

**Comment by PierreRambaud** [comment]
@dariusakafest We can't help you and merging your pull request without an issue :crying_cat_face:

**Comment by PierreRambaud** [comment]
@dariusakafest I'm not the one who decide if this PR is pertinent or not sweat_smile This is why an issue is required :)

**Comment by PierreRambaud** [comment]
HI @dariusakafest  
Since we had no news from you for more than 30 days, I'll close this pull request

Thanks!

**Pull request closed without merging**
