### PR TITLE
Fix on asset links for the symfony layout

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix on asset links for the symfony layout, see https://github.com/PrestaShop/PrestaShop/issues/34392
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and UI tests are green
| UI Tests          | legacy: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6665432947 / symfony: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6665433853
| Fixed issue or discussion?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/34392
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@M0rgan01 Something is still wrong my brother. It added query strings to the end of the assets, but the paths are still missing the folder prefix. 🤔 Could you check?

BEFORE
BEFORE

AFTER
AFTER

-------------------------------

Update - it's because of the absolute path. Changing `<script src="{{ asset('/js/admin.js') }}"></script>` to `<script src="{{ asset('js/admin.js') }}"></script>` fixes the issue.

**Comment by M0rgan01** [comment]
@Hlavtox Ok, you don't need an absolute path but rather a relative one. it should be better. 

`<script src="{{ asset('js/admin.js') }}"></script>` does not work, because the context is under admin-dev.

**Review by Hlavtox — DISMISSED** [review]
Works fine ;-)

**Review by boherm — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@M0rgan01 Do you think it would it be possible to improve the paths automatically?

I think it's a bit confusing to omit the `../js` in the beginning of the path, and also you need to add the `front_js`.

This solution requires to do some changes to template and won't solve module issues, because for example you would still get this in a module:

`<script src="/admin-dev/../modules/modulename/views/js/some.bundle.js?1.7.6.9"></script>`

**Comment by M0rgan01** [comment]
@Hlavtox 

For modules, or any other folder, it is possible to add a package

```
framework:
  assets:
    packages:
      front_js:
        base_path: '../js'
      modules:
        base_path: '../modules'
```

It is also possible to navigate directly in the asset path. 

For the automatic aspect of improving the paths, it is possible to create our own extension, or dynamically calculate the URL to have a complete link. But that would require more time and maintenance.

This is possible but do we want to invest time to improve paths or the impact is only visual for developers?

**Review by tleon — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by florine2623** [comment]
QA ✅ 
Seen with @M0rgan01, the red test has nothing to do with the PR

**Pull request merged**
