### PR TITLE
Fix translation issue during language install

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | Fix language installation: when XXXLang tables are populated, duplicated rows were not correctly translated
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4365
| How to test?  | install shop. Install another language (BO>international>translations). Set your BO account on this new language. Install new language. Set to this language: menu texts are now translated correctly

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8696)

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]
LGTM

**Comment by Quetzacoalt91** [comment]
Don't you think you should change the method description and the variable name?
We are not relying on the default current language anymore, but the current one.

For the QA team, can you please check for all shops in a multishop context, just in case?

**Comment by tomlev** [comment]
@Quetzacoalt91 done ;)

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by marionf** [comment]
@tomlev sorry I removed my QA approved thanks to @rGaillard 
In a multishop context, when I add a language, the product takes for this language added the language of the employee account instead of the default language of the shop

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8696#-:-L5OUBZe27k1_ZnWWUeG:bnfp4nl)*

**Review by eternoendless — DISMISSED** [review]

**Comment by tomlev** [comment]
hum this PR is related to the "accessories" menu issue. Need more work to fix both

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 24 of 24 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8696#-:-L5i7NNE-F3ITZkjLFls:bnfp4nl)*

**Review by eternoendless — DISMISSED** [review]

**Comment by marionf** [comment]
We have still the issue in multishop context

**Comment by eternoendless** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8696)*

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8696#-:-L5ntsirPcC7v7b_a7Fp:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @tomlev

**Pull request merged**
