### PR TITLE
Fix issue in Dispatcher after an upgrade from 1.6 to 1.7

### LINKED ISSUE #23712: Index controller not being matched in frontend after upgrading from 1.6.x to 1.7.7.2
#### Describe the bug

After an (traumatic) upgrade, all categories and custom friendly urls works fine. All except home page, which throws 404 exception.

After a deep research, I've found that Dispatcher isn't matching the url '/' for his regex ( "regexp" => "#^/$#u" ) within getController() method. In fact this is not that it doesn't match, but that '/' route also matches the route regex for "category_rule" ( regexp" => "#^/(?P<rewrite_category>[_a-zA-Z0-9-\pL]*)$#u" )  which is sorted before the index one in the routes array.

*** See screenshot for current sorted routes array ***

I've fixed it by moving the "custom routes" code within loadRoutes() method before the code for "default routes". This way, the index controller is checked before the categories one.
bg1

#### Expected behavior

It should check for a match in the index / homepage route before doing it in the category_rule route regex.

#### Steps to Reproduce

1. Install prestashop 1.6 (any minor version)
2. Upgrade it (if you can) to 1.7.7.2
3. Go to homepage
4. See error 404

#### Additional information

* PrestaShop version: 1.7.7.2
* PHP version: 7.1.3

### PR DESCRIPTION
**Pull request by logosur**
Fixes issue 23712

https://github.com/PrestaShop/PrestaShop/issues/23712

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 1.7.7.x
| Description?      | after prestashop upgrade from 1.6.x to 1.7.7.2 homepage throws 404 error. This is an issue related to the order where routes are stored in the routes array in Dispatcher.php
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        | no 
| Deprecations?     | no
| Fixed ticket?     | Fixes #23712
| How to test?      | Just install PS 1.6.x and upgrade to 1.7.2.2, then go to homepage and check that it is throwing 404 error.
| Possible impacts? | May check that all other routes are not affected after this fix.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23713)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi @logosur thanks for the PR ! I see you move the logic "set default routes" some line later. Can you help me understand why this change was needed, why does it fix the issue?

Without context it's not obvious 😅

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Hey thanks for your contribution but could you explain a little bit more why you did this change.
Also, could you take a minute to properly fill the description table and target the develop branch instead? :)

**Comment by logosur** [comment]
Hi Mathieu and Pierre!

Yes, if we let Dispatcher check before the regex for categories route than the homepage one `#^/(?P<rewrite_category>[_a-zA-Z0-9-\pL]*)$#u`, as it matches the homepage route too `/`, since homepage isn't a category, it throws an 404 error. So if we put the homepage regex before `#^/$#u`, homepage can be matched the first and then stop. This way we get working both homepage and categories routes without problems.

I even think that the "natural" order when checking routes should have the homepage before anything, anyways.

By moving the code order, we achieve this.

This is the current sorted routes within current code:
image

If we change the code this way, the homepage route will be the first in the routes array and can match the homepage route regex `#^/$#u` avoiding it to match the category route regex, and solving the issue.

You can also take a look into this issue 
https://github.com/PrestaShop/PrestaShop/issues/23712


Thanks!

**Comment by logosur** [comment]
Maybe would it be better if we close this MR and I create it again from the right branch ?

**Comment by PierreRambaud** [comment]
> Maybe would it be better if we close this MR and I create it again from the right branch ?

If you don't know how to rebase properly a pull request, it will be easier for you to do it ^^

**Comment by logosur** [comment]
I did this rebase, but honestly I don't feel confortable hehe
Let's begin again ;)

**Pull request closed without merging**
