### PR TITLE
Add test for mismatching groups, fix the check in handler

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See below.
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Tests green.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

**Changes**
- Added a test that checks if a group mismatch assertion works correctly when creating a customer.
- Added a test that checks if a group mismatch assertion works correctly when editing a customer.
- When doing this, I discovered that the check in `EditCustomerHandler` works only if both default group and the group list are provided in the command. Which is true when using BO, but not in tests or when editing customer programatically. So I improved the assertion to use customer's original data for this check, if not provided.

### CODE REVIEW

**Review by zuk3975 — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Comment by Hlavtox** [comment]
This could be tested by a dev or QA. This mainly fixes an issue in tests, which revealed it. It worked before when editing customer from BO, but by an accident. :-)

To confirm it didn't break backoffice, go edit some customer, check only `Visitor` group in the list and select a `Customer` default group. If you see an error `Customer default group with id X" must be in access groups`, it works fine.

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Link to automated tests : https://github.com/florine2623/testing_pr/actions/runs/4204894651

Tested what you said the previous comment. 

I have the same message as without PR : 
`A default customer group must be selected in group box.`
Yours is : `Customer default group with id X" must be in access groups`

Which one should be displayed ?

Thanks!

**Comment by Hlavtox** [comment]
@florine2623 It depends on a context. 

In behat tests, you should see the exception itself - `Customer default group with id "%s" must be in access groups`.
exception

In backoffice, you will see it as a nice error message - `A default customer group must be selected in group box.`
bo

If you got an error, it works fine and it's QA ✅. :-)

**Review by florine2623 — APPROVED** [review]
Thanks @Hlavtox for the quick answer.

Then it is QA ✅ 
Thanks 💪

**Comment by Hlavtox** [comment]
Thank youuuuuuuuu!!!

**Pull request merged**
