### PR TITLE
Remove useless controller permission suffix

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers |
| ----------------- | ------------------------------------------------------- |
| Branch?           | 8.0.x  |
| Description?      | This check is already done in PageVoter so we don't need to check in the annotation.  |
| Type?             | improvement  |
| Category?         | BO |
| BC breaks?        | no |
| Deprecations?     | no |
| How to test     |  Check pages used by Positions, Backup and profile controller with different roles. Check whatever the role you have, you can send a test mail. This validates the FrameworkBundleAdminController.php modifications |

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — COMMENTED** [review]
>  This check is already done in PageVoter so we don't need to check in the annotation.

Can you show me where ? 😄 I checked PageVoter and Access and did not see the tilde (I also dont know what is its purpose)

**Comment by FabienPapet** [comment]
Tilde is for concatenation only in expression language

**Comment by zuk3975** [comment]
> > This check is already done in PageVoter so we don't need to check in the annotation.
> 
> Can you show me where ? smile I checked PageVoter and Access and did not see the tilde (I also dont know what is its purpose)

@matks 
https://github.com/PrestaShop/PrestaShop/blob/8.0.x/src/PrestaShopBundle/Security/Voter/PageVoter.php#L113

**Comment by zuk3975** [comment]
LGTM (but needs a rebase)

**Comment by FabienPapet** [comment]
rebased

**Review by kpodemski — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @FabienPapet,

As discussed with @PrestaShop/qa-functional team, can you please update the "how to test" section? so we can decide if we need only to run automatic tests on this PR or not.

Thanks!

**Comment by FabienPapet** [comment]
Updated how to test section

**Review by florine2623 — APPROVED** [review]
Hello @FabienPapet ,

Automated tests have been launched and are OK.
Tested Positions, Backup et Profile pages (when they are available) with the 4 different profiles + 1 profile that I created and sent a test email from each of these account.

It is QA ✅ 
Thanks!

**Comment by atomiix** [comment]
Thanks @FabienPapet & @florine2623!

**Pull request merged**
