### PR TITLE
Merge 8.0.x to develop

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Merge 8.0.x to develop
| Type?             | improvement
| Category?         | ME
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | ~
| Possible impacts? | ~

## Fixed git conflicts

-      .github/workflows/ui_tests_code_checks.yml
-       admin-dev/themes/default/package.json
-       tests/UI/pages/BO/customerService/customerService/view.js
-       themes/package.json

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by yanmakouf — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]
Validated for @PrestaShop/qa-automation 

@PrestaShop/qa-functional Do you want to test this PR ?

**Comment by nesrineabdmouleh** [comment]
> Validated for @PrestaShop/qa-automation
> 
> @PrestaShop/qa-functional Do you want to test this PR ?

**Comment by Progi1984** [comment]
@matks Hi could you update your PR for merging this one : #29864 ?

**Review by Progi1984 — DISMISSED** [review]
Need update for @PrestaShop/qa-automation

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
