### PR TITLE
Fix exception when switching shop context after pushing a form on some configuration pages

### LINKED ISSUE #25674: BO - Multistore - SEO & URLs page & Webservice page & new marchandise return page - an exception is displayed when changing Shop links
#### Describe the bug

In the BO > Shop Parameters > Traffic & SEO page, an exception is displayed when changing the shop link in the header
The same issue is displayed in the Webservice page 

#### Steps to Reproduce

- [ ] Issue1

- Enable multistore
- Create a new shop group
- create a new shop in this group
- Go to SEO & URLs page
- make any change (enable URL accented / enable Display attributes in the product meta title/...) and save
- In the header, select any other link shop, shop group, all shops
- see error 
image

If you navigate to your BO and go back to the Traffic & SEO page => it is well displayed

- [ ]  Issue2
1. Go to BO > Advanced Parameters > Webservice page
2. Enable Webservice page 
3. In the header, select any other link: shop, shop group

- [ ] Issue3
1. Go to to /admin-dev/index.php/sell/customer-service/merchandise-return/
2. Enable returns
3. In the header, select any other link: shop, shop group

In the PS1777 => ok

#### Additional information

* PrestaShop version: 1780rc1build3
* PHP version: 7.1, 7.4

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | This PR fixes the issue we had on some forms, when switching shop context after pushing the form. The fix implemented is to redirect to the page (GET url) after processing the form.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #25674
| How to test?      | See issue #25674 
| Possible impacts? | I don't think so

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25833)

### CODE REVIEW

**Review by Progi1984 — COMMENTED** [review]
@matthieu-rolland Could you remove new return types ? It create BC Breaks

**Review by Progi1984 — DISMISSED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @matthieu-rolland

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @matthieu-rolland !

I checked : 
- The 3 pages in the issue in Multistore : OK
- All other config pages in Multistore : OK
- The 3 pages in the issue in Single Store : OK

So it's QA :heavy_check_mark: !

**Comment by Progi1984** [comment]
Thanks @matthieu-rolland & @Robin-Fischer-PS

**Comment by MatShir** [comment]
😱 this PR needs to be merged also into 1.7.8.0-build. @matthieu-rolland could you take a look please ? 🙏

**Pull request merged**
