### PR TITLE
Fix the voucher visibility

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | If a voucher is limited just for one customer but also for some groups it will be visible for all customers of those groups.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9712
| How to test?  | See the steps in the ticket description.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8701)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8701#-:-L417eU-eB3t5baYqOzo:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by matks** [comment]
@marionf I have checked, this fixes partially the bug https://github.com/PrestaShop/PrestaShop/issues/13002. What it does is: "if when we display to a customer all the cart rules that applies to him, we find a cart rule restricted to a customer, and it's a different customer, then we hide it"

However as you said in https://github.com/PrestaShop/PrestaShop/issues/13002#issuecomment-476562612:
"What happens when a cart rule is limited to a specific customer AND to a/some customer's group(s) ?
Who should see the voucher ? Only the specific customer ? Or also any customer in the group ?
Currently, the voucher is displayed only for the specific customer"
Here this PR answers "only the specific customer should see the voucher". I dont know if this is the right answer ...

**Comment by marionf** [comment]
@matks 

https://github.com/PrestaShop/PrestaShop/issues/13002#issuecomment-492568364
> If I select a specific customer, I can't add a restriction on customer group (the checkbox is disabled) and vice versa: if I select customer group restriction, I can't add a specific customer (the field is disabled)

**Comment by matks** [comment]
@marionf OK, your answer is about the behavior of the Cart Rules BO page (and it makes sense).

However there might still be bad cart rules (bad = configured in a bad way) stored in database. These cart rules might have a restriction on customer group AND restriction on customer.

If this happens, although unlikely, shall we apply this PR behavior, which is "if when we display to a customer all the cart rules that applies to him, we find a cart rule restricted to a customer, and it's a different customer, then we hide it" ? It's like a protection against badly configured cart rules. It does not replace the true solution, which is to fix the BO page behavior, but can be useful.

Wdyt ?

**Comment by marionf** [comment]
@matks 

> "if when we display to a customer all the cart rules that applies to him, we find a cart rule restricted to a customer, and it's a different customer, then we hide it"

Yes, it makes sense for existing cart rules

**Comment by matks** [comment]
Ported to https://github.com/PrestaShop/PrestaShop/pull/15903/

**Comment by matks** [comment]
@Azouz-Jribi I'm happy to announce your fix was ported to PS 1.7 through https://github.com/PrestaShop/PrestaShop/pull/15903 (and you are credited)

**Pull request closed without merging**
