### PR TITLE
Check product availability in order step

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | fix product availability check on cart step
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5154
| How to test?  | add product to cart. Set product not available anymore on BO. try to checkout : you should be redirected to cart with unavailability message

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8940)

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]

**Comment by marionf** [comment]
@tomlev 

Some changes has been done in theme.js file in this [PR](https://github.com/PrestaShop/PrestaShop/pull/8478/files) 
So, we have a retro-compatibility issue if I use a template with this js change & a previous version of PrestaShop

capture du 2018-04-12 17-11-03

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8940#-:-LADVxBDEdJZm2_UZ628:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @tomlev

**Comment by eternoendless** [comment]
ping @tomlev Could you please check that your fix exists in the Starter Theme?

**Comment by jefkeijers** [comment]
Does this fix also affect when an order is created through the API? Currently one of our clients sends their orders in csv-format, we prepare the orders and afterwards we import them in our Prestashop. It may occur that a product will get a negative stock but this is no problem as the order is already picked.

**Pull request merged**
