### PR TITLE
[+] CORE: Add TLS support

### PR DESCRIPTION
**Pull request by WassimAttar**

### CODE REVIEW

**Comment by xBorderie** [comment]
Report of #4546 for the `develop` branch.

**Comment by WassimAttar** [comment]
When using smtp.gmail.com and SSL/465 connexion parameters, mails are sent through gmail smtp.
But, when TLS/587 connexion parameters are used this error is raised :
The SMTP connection failed to start [tls://smtp.gmail.com:587]: fsockopen returned Error Number 0 and Error String ''
To add TLS support, an upgrade to swiftmailer 5.x is necessary.
This Mail.php handles swiftmailer 5.x version.
It has been tested on smtp.gmail.com SSL/465 and TLS/587 and mails are sent.

To test Mail.php swiftmailer must be upgrated to 5.x
Delete the /tools/swift/* files and put theses files
https://github.com/swiftmailer/swiftmailer/tree/5.x/lib/

**Comment by therampagerado** [comment]
I had to start using SMTP but I was unable because swift mailer is old and google brought me here.

This not seems to work as it should be on 1.6.1.4. The 'loading icon' keeps spining when sending test email.

Mail.php was updated and swift mailer was updated too according to instructions.

Can you give some directions?

**Comment by kpodemski** [comment]
I really hope that this problem will be solved because it can make PrestaShop unusable for many people from what I see

**Comment by WassimAttar** [comment]
This PR only works on the develop branch.
For 1.6.1.4 go and get the Mail.php file here :
https://www.prestashop.com/forums/topic/474063-the-smtp-connection-failed-to-start-tlssmtpgmailcom587/?p=2243097

**Comment by therampagerado** [comment]
Thank you WassimAttar,

With this file and the latest swiftmailer from github it seems to work now.

But I have the following issue - when I have imputed the password and the specifield TLS port from my SMTP and hosting provider it either gives 'failed 2 factor authentication' or "connection timeout"

When I input port 587 it sends emails without password.

Can you tell me where those password and account are stored so I can check if they are inputed but simply not displayed? I can't find them.

**Comment by WassimAttar** [comment]
Before testing with your own smtp provider, did you test with a gmail account ?
If it works with gmail TLS and not with your own provider it means that your TLS configuration is wrong.
Are you sure about the port ?
Are you sure about the smtp server ?
Are you sure about login/password ?
Are you sure that your smtp provider accepts login/password connexions ?

**Comment by therampagerado** [comment]
It's working with my host. In matter of fact it's working and sending emails withouth password visible in the field. That's why I'm asking if you know where this password is stored so I can check if it's there and simply not shown in BO or it's really working without supplied password.

Thank you!

**Comment by WassimAttar** [comment]
The smtp configuration is stored in the "configuration" table.
The name of the fields :
PS_MAIL_SERVER
PS_MAIL_USER
PS_MAIL_PASSWD
PS_MAIL_SMTP_ENCRYPTION
PS_MAIL_SMTP_PORT

**Comment by therampagerado** [comment]
It's saved so at least it's not security loophole but it's not displayed when saved in BO. The **************** are not displayed.

**Comment by WassimAttar** [comment]
Prestashop 1.6.5 and 1.7.x includes the latest version of Swiftmailer.
Therefore my PR is useless, i'm closing it.
Thanks for the Prestashop Team.

**Comment by xBorderie** [comment]
Thank you for this PR, @WassimAttar, and for taking the time to make sure that it wasn't needed anymore!

**Pull request closed without merging**
