### PR TITLE
Replace ProductInterface occurences by RedirectType

### PR DESCRIPTION
**Pull request by Sinepel**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Replace the various occurrences of ProductInterface with RedirectType. ProductInterface is deprecated since September 2020
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | Change the types of redirections on a product in the back office and test if they work
| Possible impacts? | A redirection error if there was an error during the various replacements

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23798)

### CODE REVIEW

**Comment by Sinepel** [comment]
Hi @matks / @NeOMakinG !
I don't understand why the "UI tests / Sanity (7.4) (pull_request)" test doesn't pass. Any ideas?

**Comment by PululuK** [comment]
> Hi @matks / @NeOMakinG !
> I don't understand why the "UI tests / Sanity (7.4) (pull_request)" test doesn't pass. Any ideas?

Hi @Sinepel , thanks for this contribution!
This is not related to you PR, I just re-run the tests.

**Comment by Sinepel** [comment]
Hi @PululuK ! Thanks ! 😃

**Comment by Sinepel** [comment]
I was wondering if I should delete the file as well. 
I'm waiting for your opinion :)!

**Comment by PululuK** [comment]
> I was wondering if I should delete the file as well.
> I'm waiting for your opinion :)!

I don't think that's a good idea! You risk breaking some modules and other parts of the Core.
I suggest you mark this class as deprecated. See this exemple https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Search/SearchParametersInterface.php#L20

**Comment by Sinepel** [comment]
> > I was wondering if I should delete the file as well.
> > I'm waiting for your opinion :)!
> 
> I don't think that's a good idea! You risk breaking some modules and other parts of the Core.
> I suggest you mark this class as deprecated. See this exemple https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Search/SearchParametersInterface.php#L20

OK, that's what I thought!
The class is already marked as deprecated so that sounds good to me :)

**Review by Progi1984 — APPROVED** [review]

**Comment by Sinepel** [comment]
@Progi1984 

I'm cursed with these tests! 😂

**Comment by PululuK** [comment]
> @Progi1984
> 
> I'm cursed with these tests! joy

Hi @Sinepel  
I re-run the tests ... Its Ok now !

**Review by PululuK — APPROVED** [review]
Thanks @Sinepel

**Comment by Sinepel** [comment]
Hi , do you know why there is the waiting for wording label?

Thanks !

**Comment by Progi1984** [comment]
> Hi , do you know why there is the waiting for wording label?
> 
> Thanks !

Fixed. Thanks

**Comment by khouloudbelguith** [comment]
Hi @PrestaShop/prestashop-core-developers,

This PR could be tested by Devs?

Thank you!

**Comment by kpodemski** [comment]
@khouloudbelguith 

you could just make sure that redirections are working as before when set from product page, from dev pov is ok

**Comment by Sinepel** [comment]
Hi @khouloudbelguith @kpodemski @Progi1984 
Do you know when this can be verified by QA and merged?

**Comment by khouloudbelguith** [comment]
Hi @Sinepel,

It is ok :heavy_check_mark: 
I checked all redirections:
1. Permanent redirection to a category (301)
image
2. Temporary redirection to a category (302)
image
3. Permanent redirection to a product (301)
image
4. Temporary redirection to a product (302)
image
5. No redirection (404)
image

I checked translations
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @Sinepel & @khouloudbelguith

**Pull request merged**
