### PR TITLE
Add missing hook actionSubmitAccountBefore

### LINKED ISSUE #34134: missing hook actionSubmitAccountBefore
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

missing hook at install in hook table

### Expected behavior

_No response_

### Steps to reproduce

1. Install prestashop
2. look at hook table

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Creabilis

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | add missing hook actionSubmitAccountBefore
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | missing hook at install in hook table
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/34134
| Sponsor company   | Creabilis

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Comment by ghost** [comment]
Nice catch You should also add it to autoupgrade

**Review by mflasquin — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @jf-viguier ,

The missing hook is now present :
Screenshot 2023-10-04 at 15 42 10

QA ✅ 
Thanks!

**Comment by boherm** [comment]
Thanks @jf-viguier!
@nicosomb, the `actionSubmitAccountBefore` hook seems to be already in the autoupgrade module, no?

**Comment by matks** [comment]
@boherm Don't forget the milestone 😉

**Pull request merged**
