### PR TITLE
Fix spelling from conversation to conversion rate.

### PR DESCRIPTION
**Pull request by hwdnoz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes a typo. The function was called a conversation rate, which I think was meant to be conversion rate.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | yes
| Fixed ticket? | none
| How to test?  | Test with any system that gets the currency conversion rate, from a currency object. Using the new function getConversionRate will test the improvement. Using the old function getConversationRate will test for backwards compatibility.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by howardnoz** [comment]
Hi, how do I indicate the type and category? Do I simply edit the comment, and place them in the respective columns?

**Comment by maximebiloe** [comment]
Hello @howardnoz,

Yes, you need to edit the PR comment.
Also, you can't just change the name of a public function. You need to keep the old function which will call the new one.

Regards

**Comment by Quetzacoalt91** [comment]
Hello @howardnoz,

Following @maximebiloe comment, please add the following code near the new function:
```php
    /**
     * Get conversion rate
     *
     * @return int|string
     * @deprecated 1.7.2.0, use Currency::getConversionRate() instead
     */
    public function getConversationRate()
    {
        Tools::displayAsDeprecated('Use Currency::getConversionRate() instead');
        return $this->getConversionRate();
    }
```

This is a mandatory step in order to merge merge your PR, because we cannot remove any public function in a new minor version of PrestaShop

**Comment by howardnoz** [comment]
Dear @maximebiloe,

I've made necessary changes, and hope that it's ready to be merged. Please let me know if anything else needs to change.

Thank you,
Howard

**Comment by Quetzacoalt91** [comment]
Hello @howardnoz,

The changes seem good. We can proceed with the merge.
Thanks for your contribution.

Best regards

**Pull request merged**
