### PR TITLE
[-] BO : Fixed voucher in cart not displaying in checkout when switch…

### PR DESCRIPTION
**Pull request by HeinCorbet**
…ing currency

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/4955)

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR, @HeinCorbet !
The team is currently 100% committed to the next major version, PrestaShop 1.7 (on the `develop` branch), so you might have to wait for at least the first beta version (in the coming weeks) for your PR to be merged.
Thank you for your patience!

**Comment by vincentbz** [comment]
Hi @HeinCorbet 

Thanks for this PR.
Could you explain the steps to reproduce the bug please ? 

Before applying your fix, i've created a voucher in euros, applied it in shopping cart summary in euros ant switched in dollars, and it worked.
http://i.imgur.com/Bf6OTc0.png
http://i.imgur.com/GmyoK33.png

Did I miss something ?

Thanks :)

**Comment by HeinCorbet** [comment]
Hello Vincent,

I was on a holiday last week, so here is my late response.

The problem occures when you have 2 currency which differ a lot in 
exchange rate. Like Euro to Kroatische kuna (1: 13). Create the voucher 
in Kroatische kuna and make sure the amount of the voucher (100 Kc) is 
higher than the total cart amount in euro's (must be under 100 euro's). 
The voucher<http://www.wisselkoersen.nl/forex/details.aspx?id=514325> 
will not show in the cart anymore.
But if you look in the code you should see that the is no currency 
recalculation as it is used in other classes.

I have prepared this fix for a customer and it is working correct in 
production.

regards,
Hein Corbet



Op 24-2-2016 om 18:44 schreef vincentbz:
>
> Hi @HeinCorbet <https://github.com/HeinCorbet>
>
> Thanks for this PR.
> Could you explain the steps to reproduce the bug please ?
>
> Before applying your fix, i've created a voucher in euros, applied it 
> in shopping cart summary in euros ant switched in dollars, and it worked.
> http://i.imgur.com/Bf6OTc0.png
> http://i.imgur.com/GmyoK33.png
>
> Did I miss something ?
>
> Thanks :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/PrestaShop/PrestaShop/pull/4955#issuecomment-188374580>.
>

-- 
met vriendelijke groeten,
Hein Corbet

**Comment by Shudrum** [comment]
Hi, we still need a QA feedback. Also, please be careful with the tabulations, only spaces :)

**Comment by dSkrbic** [comment]
Hello HeonCorbet,

I tryed to reproduce the bug as you described and (un)fortunately, the cart rule worked finely. Can you confirm that you still can reproduce it?

_Here are the used paramters:_
**Test 1:**
- Shop version 1.6.1.5 / MonoShop / without any configuring except:
- Two currency: 
 - €uro, default currency,
 - Zebulon: rate change: 1/100 €
- Cart rule:
 - Highlighted CartRule
 - apply, 500Zb discount
- Cart value 32€, 3200Zb

**Test2**:
- Shop version 1.6.1.5 / MonoShop / without any configuring except:
- Two currency: 
 - €uro, default currency,
 - Zebulon: rate change: 1/100 €
- Cart rule:
 - Highlighted CartRule
 - If Cart > 500 Zb
 - apply, 500Zb discount
- Cart value 32€, 3200Zb

For each test, for any currency, with or without changing currency in or before the cart, the cart rule has been proposed, and the change rate was correcely applied.

Can you confirm that this protocol test ties in with your configuration when you found the bug?

Regads,
dSkrbic

**Comment by HeinCorbet** [comment]
Hello,

yes i can still reproduce the problem with 1.6.1.5 too

the problem is with combination of vouchers. Is the cart in euro (200 euro). Create 2 voucher voor 1000 CZK (=88 euro)  (or zebulon).
Add the 2 vouchers to the cart. They will show in CZK, but the second will not show in EURO. 

kind regards,

Hein Corbet

**Comment by vincentbz** [comment]
Hello,

Without your PR, it's impossible in 1.6.1.5 to add more than one Voucher to the cart even if they are highlighted.
With your PR, I can add them one after the other, but the problem is that it works even if the "compatibility with other cart rules" option are not checked in the Vouchers.
See examples below : 

voucher1
voucher2
voucher3

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
