### PR TITLE
Improve stock sql performance

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Improve stock sql performance
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/FF-86
| How to test?  | test if stock page works ^^

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by xBorderie** [comment]
Just for bragging, could you add a Blackfire check? :)

**Comment by aleeks** [comment]
Boum

blackfire

**Comment by xBorderie** [comment]
That's what I'm talking about!
Now do it on all the other SQL queries ;)

**Review by LittleBigDev — APPROVED** [review]

**Comment by maximebiloe** [comment]
source

**Comment by Quetzacoalt91** [comment]
dog-catching-wind

**Pull request merged**
