### PR TITLE
CLDR reference data (files) reader

### PR DESCRIPTION
**Pull request by LittleBigDev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |develop
| Description?  | Reading from CLDR files was done in reverse, from the most specific file to the root. It should be done the other way around: read data in the root, then override with data in more specific files.
| Type?         | new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [FF-164](http://forge.prestashop.com/browse/FF-164)
| How to test?  | See unit tests suite

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8732)

### CODE REVIEW

**Comment by alegout** [comment]
Reviewed 3 of 5 files at r1, 757 of 758 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/Core/Localization/CLDR/LocaleData.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NiijveEdULJVW2TN1:-L5NiijveEdULJVW2TN2:bb0qh1c) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/LocaleData.php#L37)):*
> ```PHP
>      * @var string
>      */
>     public $localeCode;
> ```

Is it normal that all properties are public?

---

*[src/Core/Localization/CLDR/Reader.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NjT0zszLzh1yW_ON3:-L5NjT0zszLzh1yW_ON4:bnjso40) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L37)):*
> ```PHP
>     const CLDR_ROOT         = 'localization/CLDR/';
>     const CLDR_MAIN         = 'localization/CLDR/core/common/main/';
>     const CLDR_SUPPLEMENTAL = 'localization/CLDR/core/common/supplemental/';
> ```

can not mutualize somethings with translations/cldr?

---

*[src/Core/Localization/CLDR/Reader.php, line 230 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5Nlz7dD488Zi1R5NOb:-L5Nlz7dD488Zi1R5NOc:ber2ko1) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L230)):*
> ```PHP
>      * @return array The indexed locale parts (e.g.: ['langage' => 'en', 'region' => 'US'])
>      */
>     protected function getLocaleParts($localeTag)
> ```

Can't we use Locale::getPrimaryLanguage($localeTag) and Locale::getRegion($localeTag) here?

---

*[src/Core/Localization/CLDR/Reader.php, line 393 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NoiEHnQ3bDrAOBPJV:-L5NoiEHnQ3bDrAOBPJW:bytz4ki) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L393)):*
> ```PHP
>                 if (isset($symbolsNode->currencyGroup)) {
>                     $symbolsList->currencyGroup = (string)$symbolsNode->currencyGroup;
>                 }
> ```

Add an array $properties to check, foreach on it, and 

if (isset($symbolsNode->$property)) {
    $symbolsList->$property = (string)$symbolsNode->$property;
}

to reduce function lines?

---

*[src/Core/Localization/CLDR/Reader.php, line 417 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpGMmnYfbGQi7K0Rl:-L5NpGMmnYfbGQi7K0Rm:by8zhhr) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L417)):*
> ```PHP
>                 // If alias is set, we just copy data from another numbering system :
>                 if ($alias = $format->alias) {
>                     if (preg_match(
> ```

if ($alias... and preg_match...) remove sub if

---

*[src/Core/Localization/CLDR/Reader.php, line 446 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpP_3qA6OswhWRTT9:-L5NpP_3qA6OswhWRTTA:b-2guby3) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L446)):*
> ```PHP
>                 // If alias is set, we just copy data from another numbering system :
>                 if ($alias = $format->alias) {
>                     if (preg_match(
> ```

same here

---

*[src/Core/Localization/CLDR/Reader.php, line 476 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpREc8ECjUqn8nsey:-L5NpREc8ECjUqn8nsez:b-2guby3) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L476)):*
> ```PHP
>                 // If alias is set, we just copy data from another numbering system :
>                 if ($alias = $format->alias) {
>                     if (preg_match(
> ```

same here

---

*[src/Core/Localization/CLDR/Reader.php, line 633 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NkySzaCMA_GA4bXzC:-L5NkySzaCMA_GA4bXzD:bgcx174) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L633)):*
> ```PHP
>     protected function extractParentLocale(SimplexmlElement $parentLocaleXmlData, $localeTag)
>     {
>         if ('root' === $localeTag) {
> ```

Use multiple times, maybe we can use a constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Comment by LittleBigDev** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/Core/Localization/CLDR/LocaleData.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NiijveEdULJVW2TN1:-L5NtLc0PzkCOAmuyob9:b-yazilm) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/LocaleData.php#L37)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Is it normal that all properties are public?
</blockquote></details>

This is a "data bag". It allows us to use a data type instead of using arrays.
The only purpose of this class is carrying and exposing data. So, all public.

---

*[src/Core/Localization/CLDR/Reader.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NjT0zszLzh1yW_ON3:-L5Nvbu9mgSW0M3jMKfa:b-k2pku5) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L37)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

can not mutualize somethings with translations/cldr?
</blockquote></details>

`/translations/` directory is in `.gitignore` and is used dynamically by PrestaShop app when languages pack are installed. We can't mix them up

---

*[src/Core/Localization/CLDR/Reader.php, line 230 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5Nlz7dD488Zi1R5NOb:-L5O0piUKXUeYXP9fKz4:bk3zixi) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L230)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Can't we use Locale::getPrimaryLanguage($localeTag) and Locale::getRegion($localeTag) here?
</blockquote></details>

We can't require intl extension to be activated. So, we can't rely on this class.
Moreover, we need some customization (on currencies) which is not possible with the intl Locale class.

---

*[src/Core/Localization/CLDR/Reader.php, line 393 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NoiEHnQ3bDrAOBPJV:-L5O1JMvN98g7SIIQcSy:b5bzeic) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L393)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Add an array $properties to check, foreach on it, and 

if (isset($symbolsNode->$property)) {
    $symbolsList->$property = (string)$symbolsNode->$property;
}

to reduce function lines?
</blockquote></details>

This is properties obfuscation, which is not wanted here.
Also, dynamic properties / method calls are hard to read and maintain.

---

*[src/Core/Localization/CLDR/Reader.php, line 417 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpGMmnYfbGQi7K0Rl:-L5O2dB9RrMOldQnRAUu:b-nc1hul) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L417)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

if ($alias... and preg_match...) remove sub if
</blockquote></details>

would raise an undefined variable error

---

*[src/Core/Localization/CLDR/Reader.php, line 446 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpP_3qA6OswhWRTT9:-L5O2nYyPc1jq_--ZD00:b-nc1hul) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L446)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

same here
</blockquote></details>

would raise an undefined variable error

---

*[src/Core/Localization/CLDR/Reader.php, line 476 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpREc8ECjUqn8nsey:-L5O2or1hRhzrGhgrDu6:b-nc1hul) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L476)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

same here
</blockquote></details>

would raise an undefined variable error

---

*[src/Core/Localization/CLDR/Reader.php, line 633 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NkySzaCMA_GA4bXzC:-L5O3HaYloBlER04wBsc:b-t77xc3) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L633)):*
<details><summary><i>Previously, alegout (Alban) wrote…</i></summary><blockquote>

Use multiple times, maybe we can use a constant.
</blockquote></details>

agreed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Comment by alegout** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/Core/Localization/CLDR/LocaleData.php, line 37 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NiijveEdULJVW2TN1:-L5O4Eh7t3xMgstoNYje:b-4pr4sa) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/LocaleData.php#L37)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

This is a "data bag". It allows us to use a data type instead of using arrays.
The only purpose of this class is carrying and exposing data. So, all public.
</blockquote></details>

Ok thanks for the explanation!

---

*[src/Core/Localization/CLDR/Reader.php, line 417 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5NpGMmnYfbGQi7K0Rl:-L5O4Y1D1s7-TL_EcHYR:b-om7j5r) ([raw file](https://github.com/prestashop/prestashop/blob/e04f67770de25cb5457e9e14231f1abd441d556e/src/Core/Localization/CLDR/Reader.php#L417)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

would raise an undefined variable error
</blockquote></details>

with $alias defined before the if of course :) But if you prefer nested if, ok ^^

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Comment by alegout** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Comment by alegout** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-:-L5OA6Uu5pYNR-YKj6j_:bnfp4nl)*

**Review by alegout — DISMISSED** [review]
Thank you

**Comment by eternoendless** [comment]
Reviewed 3 of 5 files at r1, 757 of 758 files at r2, 3 of 4 files at r3, 1 of 1 files at r5, 1 of 18 files at r6.
Review status: 747 of 748 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/Core/Localization/CLDR/NumberSymbolsData.php, line 166 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OheWzO5K6ienttQml:-L5OheWzO5K6ienttQmm:b-gc9adw) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/CLDR/NumberSymbolsData.php#L166)):*
> ```PHP
>      *  Fluent interface
>      */
>     public function override(NumberSymbolsData $symbolsData)
> ```

This could be called `overrideWith` to keep in line with `LocaleData::overrideWith()`

---

*[src/Core/Localization/CLDR/Reader.php, line 527 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OkdOjItVU29rvfJFV:-L5OkdOkitHgfYihkyyU:by3lb9q) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/CLDR/Reader.php#L527)):*
> ```PHP
>             return [];
>         }
>         $supplementalXmlData = $this->readSupplementalData(self::SUPPL_DATA_CURRENCY);
> ```

Where's this method?

---

*[src/Core/Localization/DataLayer/LocaleReferenceDataLayer.php, line 90 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OmDhSOfMz52Hu4XoY:-L5OmDhSOfMz52Hu4XoZ:b-2xnmbz) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/DataLayer/LocaleReferenceDataLayer.php#L90)):*
> ```PHP
>     protected function doWrite($localeCode, $data)
>     {
>         // Nothing.
> ```

Shouldn't it throw an exception?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Comment by alegout** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8732)*

**Comment by alegout** [comment]
Reviewed 1 of 18 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8732)*

**Comment by LittleBigDev** [comment]
Review status: 745 of 748 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/Core/Localization/CLDR/NumberSymbolsData.php, line 166 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OheWzO5K6ienttQml:-L5OqeFeXYC3QRQbtm3S:b32wtd) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/CLDR/NumberSymbolsData.php#L166)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

This could be called `overrideWith` to keep in line with `LocaleData::overrideWith()`
</blockquote></details>

ok

---

*[src/Core/Localization/CLDR/Reader.php, line 527 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OkdOjItVU29rvfJFV:-L5OsU1SG6WYAh5kNbDN:b-8g4h24) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/CLDR/Reader.php#L527)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Where's this method?
</blockquote></details>

Dead code

---

*[src/Core/Localization/DataLayer/LocaleReferenceDataLayer.php, line 90 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OmDhSOfMz52Hu4XoY:-L5OsbtMdHpXt94kSC69:be8klh9) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/DataLayer/LocaleReferenceDataLayer.php#L90)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Shouldn't it throw an exception?
</blockquote></details>

Well, not really. `doWrite()` call comes from the abstract parent class. It will be called whatever layer type it is. In this case, reference data should not write because reference data is... reference data and should not be altered.
Though, execution should not be stopped by a write trial on this layer. It just does nothing, and then let the other layers do their stuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Comment by eternoendless** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/Core/Localization/DataLayer/LocaleReferenceDataLayer.php, line 90 at r5](https://reviewable.io:443/reviews/prestashop/prestashop/8732#-L5OmDhSOfMz52Hu4XoY:-L5P-JSOvGQlZn5P8eUo:bkit6d1) ([raw file](https://github.com/prestashop/prestashop/blob/90570fa29b2282ceffb3ce86a3680a260f704fba/src/Core/Localization/DataLayer/LocaleReferenceDataLayer.php#L90)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Well, not really. `doWrite()` call comes from the abstract parent class. It will be called whatever layer type it is. In this case, reference data should not write because reference data is... reference data and should not be altered.
Though, execution should not be stopped by a write trial on this layer. It just does nothing, and then let the other layers do their stuff.
</blockquote></details>

Sounds reasonable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8732)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @LittleBigDev

**Pull request merged**
