### PR TITLE
Fix checkout when one module and no cgv validation

### LINKED ISSUE #29371: The checkout is broken when only one payement without CGV validation
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The checkout is broken when only one payement without CGV validation

Screenshot - 2022-08-17T100835 771

### Expected behavior

Checkout working

### Steps to reproduce

1 ) Go to module active only one payment module
2 ) Go to order options disable CGV
3) Try to make an order on FO

### PrestaShop version(s) where the bug happened

1.7.8

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The checkout is broken when only one payement without CGV validation
| Type?             | bug fix 
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29371 
| Related PRs       | 
| How to test?      | See below 
| Possible impacts? | ?

**How to test**

`cd themes/`
`npm run build`

Test the checkout with : one payment module, two payment modules, CGV, without CGV , free oder.

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by kpodemski** [comment]
@okom3pom is it still a BC Break?

**Comment by ghost** [comment]
@kpodemski no oups, it's a mistake

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @okom3pom

**Comment by kpodemski** [comment]
Hi @okom3pom 

One question, does this change have to be ported to `classic-theme` too?

**Comment by ghost** [comment]
Hi @kpodemski no it's the core 

https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/checkout-payment.js

**Comment by kpodemski** [comment]
@okom3pom you're right, brain-fog on my side :)

**Review by florine2623 — APPROVED** [review]
Hello @okom3pom ,

Thanks for the PR.

I've tested different cases :
one payment module
multiple payment modules
with CGV
without CGV
free oder (product 0€ or with discount)
tested with multiple types of product in cart

The button is always clickable and the checkout process works fine.

It is QA ✅ !

**Comment by kpodemski** [comment]
Thanks @okom3pom @florine2623 ! :-)

**Pull request merged**
