### PR TITLE
Update license headers 2020

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Update license headers for year 2020
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Travis is green

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17565)

### CODE REVIEW

**Comment by matks** [comment]
To check suspicious content, use
```
$ git diff HEAD HEAD^  --numstat > log.txt
  // modifies '2  2  ' to 'aaa' in log.txt
$ sed '/^aaa/d' log.txt > log2.txt
```

**Comment by matks** [comment]
Suspicious files to check:
```
1	1	admin-dev/package.json
1	1	admin-dev/themes/default/package.json
3	3	admin-dev/themes/new-theme/js/components/form/autocomplete-with-email.js
23	23	admin-dev/themes/new-theme/js/pages/currency/form/components/CurrencyFormatter.vue
23	23	admin-dev/themes/new-theme/js/pages/currency/form/components/LanguageList.vue
0	25	install-dev/upgrade/php/copy_tab_rights.php
0	25	src/Adapter/ContextStateManager.php
3	3	src/Adapter/Language/LanguageImageManager.php
1	1	src/Core/Domain/Order/QueryResult/OrderProductCustomizationForViewing.php
1	1	src/Core/Domain/Order/QueryResult/OrderProductCustomizationsForViewing.php
1	1	src/Core/Domain/Profile/Command/AbstractProfileCommand.php
1	1	src/Core/Domain/Profile/ProfileSettings.php
0	25	src/Core/Util/BoolParser.php
3	3	src/PrestaShopBundle/Form/Admin/Extension/RowAttributesExtension.php
23	23	src/PrestaShopBundle/Resources/views/Admin/Product/CatalogPage/Forms/form_products.html.twig
0	24	src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_product_modal.html.twig
1	1	src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/view_product_pack_modal.html.twig
0	25	tests/Integration/Behaviour/Features/Context/Domain/AddressFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/ContactFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/DebugModeFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/EmployeeFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/OrderCartFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/OrderPaymentFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/OrderShippingFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/ShowcaseCardFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Domain/ThemeMailTemplatesFeatureContext.php
0	25	tests/Integration/Behaviour/Features/Context/Util/CategoryTreeIterator.php
0	25	tests/Unit/Core/Util/BoolParserTest.php
1	1	themes/package.json
```

**Comment by PierreRambaud** [comment]
Closed in favor of #17579 17579

**Comment by matks** [comment]
Suspicious files checked

Found 2 issues
- Double header in file install-dev/upgrade/php/copy_tab_rights.php
- Empty file src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/View/Modal/update_product_modal.html.twig (=> not related to this PR)

**Pull request closed without merging**
