### PR TITLE
Fix adding to cart with the click on the icon

### LINKED ISSUE #26433: [FO] Add to cart not working when clicking on icon cart
#### Describe the bug

When we click on the cart icon inside add to cart button, product don't work.

#### Expected behavior

When we click on the cart icon inside add to cart button, product should work

#### Steps to Reproduce

1. Go to product page
2. Click on icon cart inside add to cart button
3. See product not added to cart

**Screenshots**

Capture d’écran 2021-10-26 à 19 06 42

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: N/A

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | All the details in the Issue
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26433
| How to test?      | Try to add the product by clicking on the icon, instead of the rest of the button
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26434)

### CODE REVIEW

**Review by alexandrebru83 — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]
Thank you for your PR. IMO all are good

**Review by PululuK — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
is restarted php unit tests with DB, they were failing when downloading the translation file, it should be fine

**Comment by florine2623** [comment]
Thanks for the details @matthieu-rolland !

@kpodemski 
Thanks for the PR, tested and it works great :) it is QA approved !

**Comment by PululuK** [comment]
Thanks @kpodemski @alexandrebrubeyonds

**Pull request merged**
