### PR TITLE
Fixes wrong url in credit-slip e-mail

### LINKED ISSUE #21272: Wrong url in credit-slip e-mail
#### Is your feature request related to a problem?

When you create a credit slip the url is not correct on the mail

avoir

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When you create a credit slip the url is not correct on the mail
| Type?         | improvement 
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21272
| How to test?  | Please indicate how to best verify that this PR is correct.

I do not know if I have modified everything.

I also made a request on https://crowdin.com/project/prestashop-official

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21273)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi @okom3pom the PR seems to be OK 😄 but since this is a URL change and a wording change, I'll let @LouiseBonnard check it too as this is her scope.

I think you dont need to modify file `app/Resources/translations/default/EmailsBody.xlf` 🤔 this is a file we only modify when we build the next version

**Comment by ghost** [comment]
Thank for reviewing, i add this issue https://github.com/PrestaShop/PrestaShop/issues/21291

I wait ( https://crowdin.com/project/prestashop-official/fr# ) to see

**Comment by LouiseBonnard** [comment]
Hi @okom3pom and @matks, thanks! Wording is now part of @Julievrz's scope, she will review it as soon as possible and let you know if she requests any change. ;-)

**Review by jolelievre — DISMISSED** [review]
As @matks said the xlf catalog are updated by some scripts and should never be modified manually
Especially because we must never remove an old wording (which may be used by former versions) we only add new ones So can you please revert the changes on this file?

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by SD1982** [comment]
Hi @okom3pom i try to reproduce your issue but i don't have any url like you with or whitout your PR
Did i miss something ?
Can you provide us a complete  test scenario to reproduce your issue and correctly test your PR ?

**Without PR**
image

**With your PR applied**
image

**Comment by ghost** [comment]
Hi @SD1982 

You have to regenerate your emails template after the PR and  to put your mouse on the link

**Comment by SD1982** [comment]
hi @okom3pom Thanks for the precision i will try to retest the PR today :+1:

**Comment by SD1982** [comment]
Hi @okom3pom the url redirect to a non existing page

**Redirected to** 
image

**Instead of**
image


And the URL format is not the same

**Before PR**
before PR

**After PR**
after PR

**Comment by ghost** [comment]
You're right this PR only works with the rewritten url

I made a mistake _ -

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM the url and the redirection are good now !
image
Thanks @okom3pom !!

**Comment by ghost** [comment]
@ping @matks or @Progi1984 or other preston isn't happy

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
> @ping @matks or @Progi1984 or other preston isn't happy

Puffins are always happy !

**Comment by matks** [comment]
Thank you @okom3pom

**Pull request merged**
