### PR TITLE
No alert displayed when we click on "Save then add another value" button

### LINKED ISSUE #21252: BO - Features page - No alert displayed when we click on "Save then add another value" button
#### Describe the bug

In the BO > Catalog > Features page, there is no green alert when we click on "Save then add another value" button.
In the attribute page => ok

#### Expected behavior

image

#### Steps to Reproduce

1. Go to BO > Catalog > Features page
2. Click on 'Add new feature value'
3. Set date
4. click on "Save then add another value" button

#### Additional information

* PrestaShop version: 1770rc1, 1.7.6.8
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | No alert displayed when we click on "Save then add another value" button
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/21252
| How to test?      | Check if an alert is display
| Possible impacts? | no impact

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24327)

### CODE REVIEW

**Comment by ghost** [comment]
Same : PrestaShop#24327

**Comment by dariel97** [comment]
Si

2021-05-04 14:09 GMT-07:00, okom3pom ***@***.***>:

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Already approved by @boubkerbribri in #24327

**Review by PululuK — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @okom3pom & @boubkerbribri

**Pull request merged**
