### PR TITLE
Fix variable name in order_customer_comment.html.twig

### LINKED ISSUE #21296: Bad variable name in order_customer_comment.html.twig
#### Describe the bug

Bad variable name in order_customer_comment.html.twig

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

1) Make an Order
2) Go to Order Detail
3) Send a comment on the order
4) Check Mail from owner shop

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: 1.7.7.0 nightly
* PHP version: N/A

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Bad naming
| Type?         | bug fix
| Category?     | FO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21296
| How to test?  | Cf #21296

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21297)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by jolelievre** [comment]
Hi @okom3pom 

Thanks for the fix, however I have two warning about this one:
- it should target 1.7.7.x branch since it was identified as a regression of 177
- this is not the first one I see this fix, and the corrections on modern mail templates must be handled in the MJML sources which are in this repo https://github.com/PrestaShop/mjml-theme-converter

After a few search, I realized I already fixed this typo, and also reverted the fix later, probably because I didn't update the sources correctly. So if you can just rebase your PR to 1.7.7.x branch this will handle the problem for the core and I'll take care of the sources update 😉

**Comment by ghost** [comment]
Hi @jolelievre 

I am a GIT newbie

I'll open a new one in 1.7.7.x and close this one.
I would take the time to understand << rebase >> later

I can also remove Lastname and Fisrtname from this line : ?

https://github.com/PrestaShop/PrestaShop/blob/1.7.7.x/mails/themes/modern/core/order_customer_comment.html.twig#L43

It's an email for the shop not for the customer. 

I also see the {product_name} is missing

Before i made the new one.

**Comment by eternoendless** [comment]
Don't worry @okom3pom I've done the rebase for you

Also: https://github.com/PrestaShop/mjml-theme-converter/pull/6

**Review by eternoendless — DISMISSED** [review]

**Comment by jolelievre** [comment]
@eternoendless this PR fixes another template that had not been updated https://github.com/PrestaShop/mjml-theme-converter/pull/7

However it appears there is a problem with the rebase of this PR, there shouldn't be this many GA for 177

**Comment by jolelievre** [comment]
I just cherry-picked the commit on top of a 1.7.7.x branch and force pushed it, the CI seems in a better state now

**Review by jolelievre — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

It is ok :heavy_check_mark: 
image
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @okom3pom & @khouloudbelguith

**Pull request merged**
