### PR TITLE
Update HTMLTemplateInvoice.php

### PR DESCRIPTION
**Pull request by Nobodaddy**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Deleted waste variable %space%. Just to prevent that in future you create variables for dot, comma and colon. Seriously, who needs a variable for a blank?
| Type?         | improvement
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? yes/no
| Deprecations? | Does it deprecate an existing feature? yes/no
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL.
| How to test?  | Please indicate how to best verify that this PR is correct.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by xBorderie** [comment]
Because " " is not the same as "&nbsp;", and "&nbsp;" has more chance to be mistranslated/copied than "%space%", maybe? :)

**Comment by maximebiloe** [comment]
Hello @Nobodaddy,

Sorry but we can't merge this PR, the variable won't be replaced anymore.
I agree, the string shouldn't be in a `trans()`, only in a `sprintf()`, this way, it won't be visible on Crowdin.

Regards

**Comment by Nobodaddy** [comment]
👎 
It seems you still haven't understood what this is about! Nobody needs a special variable for a blank!

**Comment by xBorderie** [comment]
It's not just a blank, it's a non-breaking space: it prevents an automatic line break where there should be none :)

I do believe it is useful, [because different languages have different ways to space the % sign (or not)](https://en.wikipedia.org/wiki/Percent_sign#Spacing). Sure, it seems there is not check for this currently and that we are just following the [BIPM's recommendation](http://www.bipm.org/en/publications/si-brochure/section5-3-7.html), but someday, maybe...

**Comment by Nobodaddy** [comment]
I know that it's a nbsp. :)
But the problem is that Twig will automatically escape HTML entities, which makes the result a simple blank.

**Pull request closed without merging**
