### PR TITLE
[*] BO : Product stock updating is easier for merchants when you can …

### PR DESCRIPTION
**Pull request by 123monsite-regis**
…see the product reference or ean13

### CODE REVIEW

**Comment by gRoussac** [comment]
:+1:

**Comment by xBorderie** [comment]
Thank you for this PR, @123monsite-regis !

Much of the Product page architecture has changed with 1.7. @xGouley, could you tell us if you feel this PR is still relevant? Thanks!

**Comment by aleeks** [comment]
Hello @123monsite-regis 
Is it still valid ? I mean this function is already used with the new product page ?

**Comment by 123monsite-regis** [comment]
Hi,
this is not valid for 1.7 version (it's an old 1.6 pull).
It need to be done again, 
i think in src/PrestaShopBundle/Resources/views/Admin/Product/Include/form_combination.html.twig , but i do not know who datas come for this template

**Comment by aleeks** [comment]
Hello @123monsite-regis 
Thank you for your feedback, so i'm closing this PR. It have to be done on `1.6.1.x` branch

Regards

**Pull request closed without merging**
