### PR TITLE
fix error report when loading back office module list

### PR DESCRIPTION
**Pull request by gu78**
Remove error on
PHP Notice:  Undefined property: stdClass::$price in /cache/smarty/compile/02/3c/1d/023c1db63dd9ad75a7c39cf8027523d2cccaa059.file.list.tpl.php on line 136

### CODE REVIEW

**Comment by gu78** [comment]
This patch just initialize module price to 0

**Comment by gRoussac** [comment]
Hi,

Try this ? https://github.com/PrestaShop/PrestaShop/pull/3404/files

Regards

**Comment by gu78** [comment]
Thanks! 

I don't see that as a fix, as it first checks $module->price value and
later checks if the variable is set, so the problem persists. 

A right patch would check first if the price has been set. 

2015-08-18 12:15, Gregory Roussac wrote: 

> Hi, 
> 
> Try this ? https://github.com/PrestaShop/PrestaShop/pull/3404/files [1] 
> 
> Regards 
> 
> --
> Reply to this email directly or view it on GitHub [2].

 

Links:
------
[1] https://github.com/PrestaShop/PrestaShop/pull/3404/files
[2]
https://github.com/PrestaShop/PrestaShop/pull/3739#issuecomment-132157107

**Comment by gu78** [comment]
Hello!

 

New message, please read <http://semabicer.com/nearly.php?dmi>

 

Gustavo

**Pull request closed without merging**
