### PR TITLE
Fixed position action button in Order Page

### LINKED ISSUE #19918: Pagination should not impact the add product button in the order page
#### Describe the bug
The pagination and the buttons should be above the fold.

image

#### Expected behavior

image

#### Steps to Reproduce

1. Open an order

**Screenshots**

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixed position action button in Order Page
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19918
| How to test?  | **BEFORE :**<br>image<br>**AFTER :**image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19937)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]
Looks fine but did you test every cases ? Like changing the status of the PR, idk if more buttons are shown

**Review by PierreRambaud — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
HI @Progi1984 There is a problem when trying to add a new product :
Without the PR after adding a product we are correctly redirected to the order detail page and the product is added:
https://drive.google.com/file/d/1lIanRG4pon48P6y4-uqzsCD6q-S3iUB6/view?usp=sharing

But with the PR nothing is happening just the add button become enabled again we have to refresh the page to return to the order detail page
https://drive.google.com/file/d/1pl1S1FAdstvfXrvrPiW5gKVoZf-dEP6A/view?usp=sharing

Same behaviour if we want to delete or edit a product we also have to refresh the page 
https://drive.google.com/file/d/1FOZtoPi5YPYjM7TuK7bnsH4yDvhDzI1-/view?usp=sharing
https://drive.google.com/file/d/1FOZtoPi5YPYjM7TuK7bnsH4yDvhDzI1-/view?usp=sharing

And if we add a lot of product the rendering off the label and the select box is done on several lines
capture d'écran_87

**Comment by NeOMakinG** [comment]
Only your last point seems to be linked to the PR, strange thing

**Review by NeOMakinG — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by sowbiba — APPROVED** [review]

**Comment by SD1982** [comment]
Hi @Progi1984 The pagination is not at the same level than the button like in your screenshot

Screenshot at 16-59-32
Screenshot at 17-00-05

Is It the requiered behaviour ?

And also i still notice the behaviour i described i my last test ( a resfresh is needed for any action like delete , add and edit a product )

**Comment by Progi1984** [comment]
Ping @MatShir : Ok for you ?

**Comment by SD1982** [comment]
Hi @Progi1984 The problem that i mentionned [here](https://github.com/PrestaShop/PrestaShop/pull/19937#issuecomment-649612883) seems to not be related to your PR. I will investigate on my side to find the cause

**Comment by MatShir** [comment]
The refresh is ok for me! 👍 
But I need to check for space

**Comment by MatShir** [comment]
All clear and mission accomplished 👏

**Comment by Progi1984** [comment]
Thanks @MatShir & @SD1982

**Pull request merged**
