### PR TITLE
Compute price_without_reduction without group reduction

### PR DESCRIPTION
**Pull request by KminekMatej**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Upon product object, there is property called **price_without_reduction**. This price is, strangely, counted with reduction from customer group. From the logic of property, this should be the main price, without any reduction.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | Add product. Set its price to 3000. Create a user, belonging to user group with reduction of 40% of price. After login, this user should see price = 1800, price_without_reduction = 3000. (Before this PR, user would see price = 1800, price_without_reduction = 1800)
| Possible impacts? | Count of price_without_reduction has changed. Therefore any theme / logic, working with this property should get checked.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24026)

### CODE REVIEW

**Comment by matks** [comment]
Hi @KminekMatej   we have entered the month of April which is the month where PrestaShop 1.7.8 should be feature frozen. The very last Pull Requests are being submitted and validated so we can complete the 1.7.8 milestone. So review might come late as maintainers are very busy at this moment! 😅

**Comment by KminekMatej** [comment]
@matks Thats cool with me. I updated my instance manually, so no hurry from my side. I am actually impressed you have time to respond on more than 2k issues you guys have here :)

**Review by matks — CHANGES_REQUESTED** [review]
Hello @KminekMatej .

The changes you have submitted are very small but are scaring me 😄  . Because it's in the Product class (it's a key class in PrestaShop) inside functions that are used probably hundred of times in maybe a hundred different scenarii.

It's close to impossible to validate all of these possible usecases manually. We need items that prove to us that this change is valid.

We need, to validate this PR, automated tests. I know it can be quite complex to setup but without a safety test we cannot merge this change.

You can find examples of such tests in https://github.com/PrestaShop/PrestaShop/pull/23702/ and the documentation is https://devdocs.prestashop.com/1.7/testing/how-to-create-your-own-behat-tests/

**Comment by PierreRambaud** [comment]
Hi @KminekMatej ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
