### PR TITLE
FO: Fix cart rule detail amount

### LINKED ISSUE #31486: Incorrect cart rule detail if products with different VAT
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you create a cart rule and apply it only to a selected products, and you have products with different VAT in the cart, the amount displayed is not correct.

### Expected behavior

The cart rule detail and the "Discount" row must match.

### Steps to reproduce

1. Create a cart rule with 100% discount and apply it to the cheapest product
image

2. Configure different VAT for 2 products
image
image

3. Add both products to the cart and check the cart summary details
image

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by idnovate**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | image
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check #31486
| Fixed ticket?     | Fixes #31486
| Sponsor company   | idnovate.com

### CODE REVIEW

**Comment by idnovate** [comment]
After the fix:

image

**Comment by dudu0911** [comment]
works! thank you so much

**Review by 0x346e3730 — APPROVED** [review]
LGTM

**Review by SharakPL — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @idnovate  , 
I have tested your PR and it's well fixed !

https://user-images.githubusercontent.com/115152460/229091954-ca2a436f-6e37-45e2-9eb4-9d2aec0274fc.mp4



It's QA approved :rocket: 
thank you !

**Comment by nicosomb** [comment]
Thank you @idnovate !

**Pull request merged**
