### PR TITLE
Fix: PPV2 - Specific prices can't be created for a particular combination 

### LINKED ISSUE #34229: PPV2 - Specific prices can't be created for a particular combination
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In PS 8.1.2, I want to create a specific price for a combination in particular. But all the combinations are not displayed; also I can't search for the said combination, there's no search field.

https://github.com/PrestaShop/PrestaShop/assets/16019289/ff58766f-d6dc-4717-9187-d4ec29886ccf

Might be related to https://github.com/PrestaShop/PrestaShop/issues/34203

### Expected behavior

All my combination should be displayed. Or I should have a search input field.

### Steps to reproduce

1. Go to BO > Create a combination product
2. Generate more than 20 combinations
3. Go to Pricing > Specific price block > Add a specific price
4. See in "All combinations" : only 10 combinations are displayed :x:
5. There's no search field to find another combination that is not already displayed in the dropdown :x:

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | In PS 8.1.2, I want to create a specific price for a combination in particular. But all the combinations are not displayed; also I can't search for the said combination, there's no search field.
| Type?             | bug fix
| Category?         | BO
| Fixed issue or discussion?     | Fixes #34229

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
ah, unit tests need to be updated

**Comment by Codencode** [comment]
> ah, unit tests need to be updated



> ah, unit tests need to be updated

Hi @matthieu-rolland,
I do not know how to do it.

Thank you

**Comment by matks** [comment]
Similar to https://github.com/PrestaShop/PrestaShop/pull/34250

**Review by matks — CHANGES_REQUESTED** [review]
As answered in https://github.com/PrestaShop/PrestaShop/pull/34250 : removing the limit is dangerous because it will attempt to load all combinations for a product and in case of products with lot combinations, it could crash the page.

> also I can't search for the said combination, there's no search field.

Here you are right and you actually describe the right solution. You need to implement pagination + search/filter capabilities, that would be the correct way to solve this problem

**Comment by ChillCode** [comment]
Hi

Just tried on a site with thousands of products and combinations and changed the limit to 2000 and then opened a product with almost 700 combinations, ~the result is that the page loaded fast and the select didn't hang or freeze~ it freezes for a couple of seconds but also is not viable to select one between 700 options, but the 20 limit is to small for users who don't use modules/webservices to update/create products..

The difference between PPV1 that loaded all data and then the browser had to render it, is that we are only loading 700 options, not all the data so it's an easy task for the browser to render, don't think it will crash if that limit is higher.

The ajax endpoint that loads the combinations accepts the q parameter so it shouldn't be difficult to implement a search field:

https://example.com/admin/index.php/sell/catalog/products-v2/1/search-product-combinations?limit=2000&q=AA

**Comment by Codencode** [comment]
Hi,
by removing the limit (as I did in the modification), the search field already appears and it already works, but each search corresponds to an ajax call.
The best solution (as suggested by @matks) would be to implement pagination, but the select2 component does not provide this.

**Comment by Codencode** [comment]
> As answered in #34250 : removing the limit is dangerous because it will attempt to load all combinations for a product and in case of products with lot combinations, it could crash the page.
> 
> > also I can't search for the said combination, there's no search field.
> 
> Here you are right and you actually describe the right solution. You need to implement pagination + search/filter capabilities, that would be the correct way to solve this problem


I created a new pull request #34315 which fixes the problem by always showing the search input while preserving the limit.

Could you check if it's ok?

Thanks.

**Comment by ChillCode** [comment]
Hi,

You're right, I only set to 2000 and test it, but taking a closer look to phpdocs it clearly says it's always loaded by ajax and uses select2 and only fills selected options on page load so every keystroke will make a call.

Updated my previous comment, since the product I used had some combinations deleted and I didn't notice, now I tested wth real 700 and freezes for few seconds.

I revised the code, and I guess there is no type that fits this need so the alternative to your solution is a bit more of work.

**Comment by Codencode** [comment]
> Hi,
> 
> You're right, I only set to 2000 and test it, but taking a closer look to phpdocs it clearly says it's always loaded by ajax and uses select2 and only fills selected options on page load so every keystroke will make a call.
> 
> Updated my previous comment, since the product I used had some combinations deleted and I didn't notice, now I tested wth real 700 and freezes for few seconds.
> 
> I revised the code, and I guess there is no type that fits this need so the alternative to your solution is a bit more of work.

Hi @ChillCode,
I created a new pull request that solves the problem in a different way, the system always loads 20 combinations at a time, but the search input is always shown, in this way it is possible to refine the search using the name of the attributes.

If you want to try it here is the link: #34315.
 
Thank you.

**Pull request closed without merging**
