### PR TITLE
Fix typo in module controller messages

### PR DESCRIPTION
**Pull request by laurentrousseau918**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix typo in module controller messages
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     |  ??
| Related PRs       | ??
| How to test?      | Check message, see it is not good
| Possible impacts? |

### CODE REVIEW

**Review by PululuK — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]
@PrestaShop/qa-team 

Asking for a confirmation that this PR doesn't require any tests, it's just a wording change :)

**Comment by laurentrousseau918** [comment]
> @PrestaShop/qa-team
> 
> Asking for a confirmation that this PR doesn't require any tests, it's just a wording change :)

Yes 🐬

**Review by NeOMakinG — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
No need QA indeed @kpodemski , thanks @laurentrousseau918 !

**Comment by kpodemski** [comment]
Thank you @laurentrousseau918

**Pull request merged**
