### PR TITLE
Fixed CSS issues when using DisplayProductPriceBlock

### PR DESCRIPTION
**Pull request by idnovate**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix layout when using `displayProductPriceBlock`
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/ps_legalcompliance/pull/69#issuecomment-696795183
| How to test?  | Check https://github.com/PrestaShop/ps_legalcompliance/pull/69

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21114)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by ngodefroy** [comment]
QA Currently blocked by https://github.com/PrestaShop/PrestaShop/pull/20942

**Comment by ngodefroy** [comment]
Hello @PrestaShop/prestashop-core-developers 
None of the QA were able to test this PR, everyone had different results and no one was able to see the fix, could you check it ?
Thank you

**Review by matthieu-rolland — APPROVED** [review]

**Comment by atomiix** [comment]
I've just checked this PR.
Before:
Capture d’écran 2020-10-16 à 10 43 53

After:
Capture d’écran 2020-10-16 à 10 43 05

This PR fixes the issue!

**Comment by atomiix** [comment]
Thanks @idnovate !

**Pull request merged**
