### PR TITLE
Show installed modules by default instead of the modules selection

### PR DESCRIPTION
**Pull request by christianverardi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Show installed modules first
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | [BOOM-3390](http://forge.prestashop.com/browse/BOOM-3390)
| How to test?  | From the BO click on the Modules' page link from the menu.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8244)

### CODE REVIEW

**Comment by aleeks** [comment]
ping @vincentbz

**Comment by Quetzacoalt91** [comment]
The module section will be reworked. The entry point is going to change as written in this PR.

However, I won't merge this PR until the project has started.

**Comment by christianverardi** [comment]
@Quetzacoalt91 ok, thanks for the feedback.

**Comment by LittleBigDev** [comment]
Ping @Quetzacoalt91

**Comment by Quetzacoalt91** [comment]
As said, no merge until the project has started. :wink:

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @christianverardi

**Pull request merged**
