### PR TITLE
Comment search process

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | I want to implement something in Search class, so I first need to understand how the hell it works. So, this comments the process and makes it more readable. **NO LOGICAL CHANGES.**
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | No need to test, no changes.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by ShaiMagal — DISMISSED** [review]

**Review by kpodemski — CHANGES_REQUESTED** [review]
You changed something because tests are failing... :(

**Comment by Hlavtox** [comment]
@kpodemski Aah, yes I changed `array_merge` to `array[]` and it made the items be added in different order. The order doesn't matter.

**Review by ShaiMagal — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional 

FYI, this PR contains changes to variable names, comments added to the code, and simplified two places in the code that I checked as a dev. Following other PRs like this that we merged in the past, I will merge this one after having green automated tests.

Tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/10810118871

**Comment by florine2623** [comment]
Tests are green @kpodemski 😄

**Pull request merged**
