### PR TITLE
Update PULL_REQUEST_TEMPLATE.md to acknowledge 8.2.x

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update PULL_REQUEST_TEMPLATE.md to acknowledge 8.2.x
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by kpodemski — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by kpodemski** [comment]
@matks ahh, I think it should go to 8.2.x branch :D

**Comment by matks** [comment]
> @matks ahh, I think it should go to 8.2.x branch :D

It's not needed. GitHub uses the configuration files of the default branch which is develop.

**Pull request merged**
