### PR TITLE
Allow override of every modern template

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | self described
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | this will fixes futures tickets if we don"t merge it now
| How to test?  | Install the following [module](https://github.com/PrestaShop/PrestaShop/files/1859869/module_inheritance.zip), every modern page (except from Modules section) will be overriden: it is the intended behavior :)

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8895)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
ping @sarjon take a look at this, very important to use the @Template annotation if you want to make your template overridable by modules.

**Comment by sarjon** [comment]
thanks for information @mickaelandrieu !

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @mickaelandrieu

**Comment by kpodemski** [comment]
Annotations in Symfony are some next level magic, and i thought that Angular is more magical :O

**Pull request merged**
