### PR TITLE
Fix error due to wrong token when changing quantities in product quantity tab

### PR DESCRIPTION
**Pull request by misthero**
the token sent via ajax after first time someone edit manually the quantity fields is wrong, this new variable fix it.

this merge the PRs
https://github.com/PrestaShop/PrestaShop/pull/4313
https://github.com/PrestaShop/PrestaShop/pull/4312

### CODE REVIEW

**Comment by misthero** [comment]
@xBorderie

**Comment by xBorderie** [comment]
Thank you! I am closing the two other PR, since they are combined in this one.
The Core dev will soon have a look at this. Cheers!

**Comment by xBorderie** [comment]
Could you amend your commit's name to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog?
To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this must be done via the command line: just changing the title of the pull-request from the GitHub interface is not the same!_ :)

Thank you!

**Comment by aleeks** [comment]
Hello @misthero 
Is it still valid with 1.7 PrestaShop & new productController from Symfony ?

**Comment by misthero** [comment]
hello @aleeks 
not tested, but looking at the 1.7 javascript variables, my guess is yes, the ajax calls still needs the right token for every controller

1.7 -> admin-dev/themes/default/template/header.tpl line 71:
```
var token_admin_orders = '{getAdminToken tab='AdminOrders'}';
var token_admin_customers = '{getAdminToken tab='AdminCustomers'}';
var token_admin_customer_threads = '{getAdminToken tab='AdminCustomerThreads'}';
```

so yes, it is probably needed to send the correct token for the product Controller too

**Comment by aleeks** [comment]
Hello,
Yes, but is it always called ? The form product has totally changed in 1.7.
Where this call is done ?

**Comment by misthero** [comment]
https://github.com/PrestaShop/PrestaShop/blob/1.7.0.x/js/admin/products.js#L1418

the ajax call is here.. it is used? I don't know...
if you are unsure leave the commit out. It is a minor bugfix anyway...

I am sorry I have no time right now to check further.

**Comment by aleeks** [comment]
Hello,
The new product page is in the new theme and is therefore not normally impacted by this change.
Thank you!

**Pull request closed without merging**
