### PR TITLE
Wrong mimetype for svg file

### LINKED ISSUE #24597: Mimetype for svg is wrong in the filemanager configuration. It doesn't allow to upload svg files
#### Describe the bug

Mimetype for svg is wrong in the filemanager configuration. It doesn't allow to upload svg files

```
//**********************
//Allowed mime types
//**********************
$mime_img = array('image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/tiff', 'image/svg');
$mime_file = array('application/pdf');
$mime_video = array('video/mpeg', 'video/mp4', 'video/x-msvideo', 'audio/x-ms-wma', 'video/x-flv', 'video/webm');

$mime = array_merge($mime_img, $mime_file, $mime_video);
```

SVG mimtype is "image/svg+xml" https://www.w3.org/TR/SVG11/mimereg.html

#### Expected behavior

The file manager should allow to upload SVG files but it doesn't.

#### Steps to Reproduce

1. Go to a product in admin
2. Click on description
3. add an image in the editor
3. Upload a SVG file

#### Additional information

* PrestaShop version: 1.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by Shagshag**
There's only one registered mediatype for SVG, image/svg+xml, not image/svg

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Mimetype for svg is wrong in the filemanager configuration. It doesn't allow to upload svg files
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     |  Fixes #24597
| How to test?      | Try to upload a svg file with the filemanager
| Possible impacts? | Product description for example.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24595)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]
I confirm the mime type is not the right one: https://www.w3.org/TR/SVG11/intro.html

**Comment by Shagshag** [comment]
Added 'image/svg' because the two mime types seem to be used

**Review by PierreRambaud — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by florine2623** [comment]
LGMT

Thanks @Shagshag !

**Comment by Progi1984** [comment]
Thanks @Shagshag and @florine2623

**Pull request merged**
