### PR TITLE
Update PHP CS Fixer

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | /
| Type?         | improvement
| Category?     | CO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | /
| How to test?  | /

Rule | PR
-- | --
align_multiline_comment' =>   ['comment_type' => 'phpdocs_only'] | https://github.com/PrestaShop/PrestaShop/pull/11694
'array_indentation' => true | https://github.com/PrestaShop/PrestaShop/pull/11695
'combine_consecutive_issets' => true | https://github.com/PrestaShop/PrestaShop/pull/11696
'combine_consecutive_unsets' => true | https://github.com/PrestaShop/PrestaShop/pull/11697
'single_line_comment_style' => true | https://github.com/PrestaShop/PrestaShop/pull/11699
'logical_operators' => true | https://github.com/PrestaShop/PrestaShop/pull/11701
'no_short_echo_tag' => true | https://github.com/PrestaShop/PrestaShop/pull/11703
'no_alias_functions' => true | https://github.com/PrestaShop/PrestaShop/pull/11707
'modernize_types_casting' => true | https://github.com/PrestaShop/PrestaShop/pull/11708
'no_mixed_echo_print' => true | https://github.com/PrestaShop/PrestaShop/pull/11709
'no_closing_tag' => true | https://github.com/PrestaShop/PrestaShop/pull/11738
'single_blank_line_at_eof' => true | https://github.com/PrestaShop/PrestaShop/pull/11738

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11718)

### CODE REVIEW

**Comment by MathiasReker** [comment]
Why does travis not run?

**Comment by Quetzacoalt91** [comment]
Looks like Travis refused to handle your PR:
Capture d’écran du 2019-03-14 15-24-38

Last time I had to duplicate your branch to trigger the builds.

**Comment by MathiasReker** [comment]
@Quetzacoalt91 I just tried that. I will wait and see if it solves the issue :) New PR: https://github.com/PrestaShop/PrestaShop/pull/12927

**Comment by MathiasReker** [comment]
@Quetzacoalt91 I did not manage to solve the issue. Can you help me?

**Comment by Quetzacoalt91** [comment]
I had to create #12934 in order to trigger yours.

**Comment by MathiasReker** [comment]
Do Travis need to pass before the PR can be merged? I wrote a script to make the project up to date with the new rules, but I am not sure it will make the tests pass.

```
#!/bin/sh

php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules='{"align_multiline_comment": {"comment_type": "phpdocs_only"}}'
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Align multili ne comment"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="array_indentation"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Array indentation"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="combine_consecutive_issets"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Combine consecutive issets"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="combine_consecutive_unsets"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Combine consecutive unsets"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="single_line_comment_style"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Single line comment style"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="logical_operators" --allow-risky="yes"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Logical operators"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="no_short_echo_tag"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "No short echo tag"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="no_alias_functions" --allow-risky="yes"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "No alias functions"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="modernize_types_casting" --allow-risky="yes"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Modernize types casting"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="no_mixed_echo_print"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Use echo instead of print"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="no_closing_tag"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "No closing tag"
fi
php ../php-cs-fixer.phar fix ./ --using-cache="no" --rules="single_blank_line_at_eof"
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Single blank line at EOF"
fi
../vendor/bin/php-cs-fixer fix
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Run php-cs-fixer"
fi

```

**Comment by matks** [comment]
> Do Travis need to pass before the PR can be merged? I wrote a script to make the project up to date with the new rules, but I am not sure it will make the tests pass.

Yes, we cant take the risk because if we merge something that breaks the build into `develop`, this will block _all_ PRs from being merged

**Comment by Quetzacoalt91** [comment]
Hi @MathiasReker,

I'd like to try something which requires your PR to be closed.
I expect that creating a PR with my account from your branch would allow Travis to be run.

If this does not work, it will be reopened.

**Comment by MathiasReker** [comment]
Tests passed 🎉 😄

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Please execute cs fixer only on    
``` 
    __DIR__.'/src',
    __DIR__.'/classes',
    __DIR__.'/controllers',
    __DIR__.'/tests',
```

You change tools, var, and others directory which are something external resources.

**Comment by MathiasReker** [comment]
@PierreRambaud Here is what I just did. Everything OK? :)

```
#!/bin/sh

git reset --hard HEAD~7
git push -f
git pull --rebase upstream develop
git push -f

path=('src' 'classes' 'controllers' 'tests')

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules='{"align_multiline_comment": {"comment_type": "phpdocs_only"}}'
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Align multiline comment"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="array_indentation"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Array indentation"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="combine_consecutive_issets"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Combine consecutive issets"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="combine_consecutive_unsets"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Combine consecutive unsets"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="single_line_comment_style"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Single line comment style"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="logical_operators" --allow-risky="yes"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Logical operators"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="no_short_echo_tag"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "No short echo tag"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="no_alias_functions" --allow-risky="yes"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "No alias functions"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="modernize_types_casting" --allow-risky="yes"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Modernize types casting"
fi


for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="no_mixed_echo_print"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Use echo instead of print"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="no_closing_tag"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "No closing tag"
fi

for DIR in "${path[@]}"
do
  php ../php-cs-fixer.phar fix "./$DIR" --using-cache="no" --rules="single_blank_line_at_eof"
done
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Single blank line at EOF"
fi

../vendor/bin/php-cs-fixer fix
if ! git diff-index --quiet HEAD --; then
  git add -A
  git commit -m "Run php-cs-fixer"
fi

git push
```

**Review by PierreRambaud — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by MathiasReker** [comment]
@Quetzacoalt91 Can you restart the builds please? Isen't it weird that this issue happens often from my account?

**Comment by MathiasReker** [comment]
Please merge this PR, because a lot of conflicts will come :)

**Comment by MathiasReker** [comment]
@Quetzacoalt91 can you start the tests please? :)

**Comment by Quetzacoalt91** [comment]
I created #13034 to trigger your tests.

**Comment by MathiasReker** [comment]
Moved to here: https://github.com/PrestaShop/PrestaShop/pull/14245

I had some issues with my acc that affects this PR.

**Pull request closed without merging**
