### PR TITLE
Update PS version available in README.md

### PR DESCRIPTION
**Pull request by Klemart3D**
Update PS version

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update PS version available in README.md
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Indicate how to verify that this change works as expected.
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | Fixes #{issue number here}, Fixes #{another issue number here}, Fixes https://github.com/PrestaShop/PrestaShop/discussions/ {discussion number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]
Thank you @Klemart3D

**Comment by matks** [comment]
Thank you @Klemart3D

**Comment by Klemart3D** [comment]
@matks If milestone is 9.0.0, perhaps "8.1" must be replaced by "9.0" to display a readme ready for v9.0 release?

**Comment by matks** [comment]
> @matks If milestone is 9.0.0, perhaps "8.1" must be replaced by "9.0" to display a readme ready for v9.0 release?

The README displayed on the homepage https://github.com/PrestaShop/prestaShop/ is the `develop` branch. People will see the README of `develop`.

Today latest available release is PS 8.1, and we'll have to update it somewhere in 2024 when 9.0 is delivered ;)

**Pull request merged**
