### PR TITLE
Revert separated module buttons

### LINKED ISSUE #11331: Bad design on small screen for module action buttons in V1.7.5.0 beta 1
**Module List buttons are looking bad**
See my screenshot

**To Reproduce**
1. Go to 'Modules -> Module Manager'
2. Click on 'Module Manager Tab'
3. See error

**Screenshots**
ps-module manager beta test

**Additionnal information**
PrestaShop version: 1.7.5.0 beta 1
PHP version: 7

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Partially reverts #9287. Module action buttons are together again.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | Fixes #11331
| How to test?  | On module pages, buttons are together as on all PrestaShop 1.7 versions.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11466)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
R.I.P

**Comment by marionf** [comment]
@TristanLDD 

Is it ok for you ? 

capture d ecran_651

**Comment by TristanLDD** [comment]
@marionf Can the button and the dropdown be attached together ? Like what we have in the [UI Kit](https://cdn.rawgit.com/PrestaShop/prestashop-ui-kit/master/index.html) : 
button

**Comment by Quetzacoalt91** [comment]
@marionf this is obviously a wrong display. :)
Can you please refresh your cache browser?

**Comment by marionf** [comment]
Yes, it's ok :)

**Pull request merged**
