### PR TITLE
Use 2x images URLs

### LINKED ISSUE #26599: High resolution product images are not displayed
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

My Prestashop Installation: 1.7.8.0, classic theme.
My products images in large format are displayed in low res. But I enabled the high resolution image generation.
When I inspect the HTML I can see that Prestashop generates the URL of the low-res image:

Capture d’écran 2021-11-14 à 17 16 58

When I fix the URL in the inspector by adding `2x`:

Capture d’écran 2021-11-14 à 17 22 08

Then the image is displayed in high-res as expected.

### Expected behavior

@NeOMakinG 
We investigated with @Hlavtox and we think that the best solution would be to use the `picture` element with `srcset` so every pictures will adapt depending on the browser and the viewport

### Steps to reproduce

1. show a product image
2. click on the image to sse it large
3. observe that the image is in low-res

Tested on macOS Big Sur on:
- Firefox latest version
- Safari latest version
- Chrome latest version

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by jak78**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Here is my fix suggestion for this issue: https://github.com/PrestaShop/PrestaShop/issues/26599 
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26599
| How to test?      | On a retina-enabled device, display a product with a 2x image and when the high-DPI mode is enabled in the configuration. You should see it in high-res. Tested on macOS.
| Possible impacts? | Code that uses the `ImageRetriever` class

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26876)

### CODE REVIEW

**Comment by jak78** [comment]
Here is the minimal code I found to fix #26599 

I would like to implement automated tests on this code. I need to comply with your test policy. Should I implement:
- a unit-test of `ImageRetriever`class? I guess I will need a small refactor to mock `file_exists` then
- an integration test?
- a functional test?

**Comment by jak78** [comment]
Backport of: https://github.com/PrestaShop/PrestaShop/pull/26877

**Comment by PrestaEdit** [comment]
Hi,

Inside PrestaShop 1.6, the 2x image was changed with JavaScript, to replace the src of the image by the 2x as needed.

I'm not sure that we need to deliver the 2x image with the ImageRetriever but more inside the srcset of the image attribute on HTML generated.

It's just an opinion based on what I know of this, I'm not the best placed to say about the right decision here :)

**Review by Progi1984 — APPROVED** [review]

**Review by matks — COMMENTED** [review]
Before approving the change, an exploration is needed => https://github.com/PrestaShop/PrestaShop/issues/26599

**Review by matthieu-rolland — COMMENTED** [review]
the fix seems good to me, should we wait for @NeOMakinG 's approval ?  (he is off but will be back soon)

**Comment by NeOMakinG** [comment]
I don't see any problems with this as it's based on a configuration I think so, but it's definitely not the end of our work on images :p

**Comment by matks** [comment]
> I don't see any problems with this as it's based on a configuration I think so, but it's definitely not the end of our work on images :p

@eternoendless thinks we might solve this bug using `srcset` attribute rather, wdyt?

**Comment by NeOMakinG** [comment]
> > I don't see any problems with this as it's based on a configuration I think so, but it's definitely not the end of our work on images :p
> 
> @eternoendless thinks we might solve this bug using `srcset` attribute rather, wdyt?

srcset is obviously something we need to implement/think about yes

**Comment by Hlavtox** [comment]
@NeOMakinG @matks The same as the other PR, this is so wrong. Do not merge!

**Comment by jak78** [comment]
Thanks for the feedback. Closed the PR as the approach should be entirely different

**Pull request closed without merging**
