### PR TITLE
Performance improvement with +100000 products

### PR DESCRIPTION
**Pull request by dominservice**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Performance improvement with +100000 products.
| Type?             | improvement 
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no.
| Related PRs       |no.
| How to test?      | You should add at least 100,000 products with features and enter category subpagest.
| Possible impacts? | no.

### CODE REVIEW

**Comment by Hlavtox** [comment]
Hi @dominservice, can you please provide us with some timings, when you manually execute this query over your db?

Also, please can you test this code? It may be simplier.

```php
$sql = 'SELECT COUNT(cp.`id_product`) AS total
FROM `' . _DB_PREFIX_ . 'category_product` cp 
LEFT JOIN `' . _DB_PREFIX_ . 'product` p ON p.`id_product` = cp.`id_product`
' . Shop::addSqlAssociation('product', 'p') . '
WHERE cp.`id_category` = ' . (int) $this->id .
($front ? ' AND product_shop.`visibility` IN ("both", "catalog")' : '') .
($active ? ' AND product_shop.`active` = 1' : '') .
($idSupplier ? ' AND p.id_supplier = ' . (int) $idSupplier : '');
```

**Comment by dominservice** [comment]
Hello, unfortunately I no longer have access to the customer base where I performed it, but unfortunately with such a large number of products, this query was not optimal. The fact is simpler, because everything in one query, with a small store is efficient, but with a large store with over 130,000 products, the page was loading very slowly. Now, even with litespeed turned off, it works very quickly, because I used query split. Sometimes with big data it is better to make more smaller queries, because overall it is more efficient

**Comment by dominservice** [comment]
Hi @Hlavtox, certain complex database queries that are in @Prestashop are inefficient with such large stores. Today, more and more stores operate in dropshipping and, thanks to integration, they load several wholesalers into one store. The store that I mentioned will have to ultimately handle about a million products, and if there are many additional features for each product, and the customer uses a faceted search, the store will simply not be able to handle such a complex question, so it is better to make a few small queries based on the relationship what are in the Laravel framework.

**Comment by kellian84** [comment]
@dominservice how did you fix the problem please? because I have the same problem :/

**Comment by dominservice** [comment]
@kellian84 https://github.com/PrestaShop/PrestaShop/compare/develop...dominservice:PrestaShop:patch-1
You need to look for any optimizations in the main SQL queries. Test them in phpmyadmin, see which ones take the most time. Usually, it is about complex queries, as in this case. In such a situation, you should break down the query into components and execute them separately, passing the parameters obtained from one query to the other. With very large databases, this is the best optimization on ready-made engines such as prestashop or magento. It is best to create an override for the class to be modified. In this case, I wanted to propose an optimization that could be usefully applied to presta, but as you can see the project manager cannot understand that the optimization of SQL code is not always about executing queries composed of subquery, on the contrary, especially with large databases . @Hlavtox suggested that I use this query, which is provided by prestashop, without trying to understand that my solution could be very profitable for big stores. I don't think @Hlavtox has ever dealt with large stores. Or maybe @Hlavtox will check it and try it ?? what a problem on test servers to generate a few million products and check how long is the prestashop query executed and what time the proposed solution is carried out.

**Comment by Hlavtox** [comment]
> @Hlavtox suggested that I use this query, which is provided by prestashop, without trying to understand that my solution could be very profitable for big stores. 

What? Where did I suggest to use Prestashop query? In my previous comment I simplified the query that you provided and asked you to test it. https://github.com/PrestaShop/PrestaShop/pull/29117#issuecomment-1191278386

It's very difficult to approve a PR when you don't provide a proper PR description, a test case, a test store, any timings. 🤷

**Comment by kpodemski** [comment]
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find and motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
