### PR TITLE
Fix the sorting by price in the products filtering page

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | The sorting by price does not work correctly with pagination, when there are discounts on products.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-7452
| How to test?  | BO > apply a discount to product, disable the blocklayered module, FO > category page, try to sort the products by price and check if the products are displayed in order in all pages.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8699)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[classes/Category.php, line 704 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-L41CFuCOc9ISxxDTxB3:-L41CFuCOc9ISxxDTxB4:bgpp9w1) ([raw file](https://github.com/prestashop/prestashop/blob/5bcbea6243c0cbfb912cd312f72ca6bc87c9309a/classes/Category.php#L704)):*
> ```PHP
>         /** Return only the number of products */
>         if ($get_total) {
>             return sizeof($productsId);
> ```

For consistency, please use `count()`

---

*[classes/Category.php, line 729 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-L41D3lBuzx9XbG9C2An:-L41D3lBuzx9XbG9C2Ao:btb0cem) ([raw file](https://github.com/prestashop/prestashop/blob/5bcbea6243c0cbfb912cd312f72ca6bc87c9309a/classes/Category.php#L729)):*
> ```PHP
>         if ($order_by == 'price') {
>             $order_by = 'orderprice';
>             $this->createTomporayCategoryProducts($front, $active, $id_supplier);
> ```

Not okay. This will create a temporary table + data insertion every time `getProducts()` is called. Not a good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8699)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Please find another solution

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
can you check it ? 

Thanks

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[classes/Category.php, line 779 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-L4BQKrrFfsBhO7BtM6s:-L4BQKrrFfsBhO7BtM6t:b-vxcbbn) ([raw file](https://github.com/prestashop/prestashop/blob/317450e158ed3b839c125c949d68e8cfb738fa75/classes/Category.php#L779)):*
> ```PHP
>         $limitLenght = (int)$random_number_products;
>         if ($order_by === 'orderprice') {
>             if ($random === true) {
> ```

You should first address the `if($random)` and then look at the `$order_by` cases.

---

*[classes/Category.php, line 789 at r2](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-L4BQfCgVHi1RroD85jX:-L4BQfCgVHi1RroD85jY:b-tnpk2h) ([raw file](https://github.com/prestashop/prestashop/blob/317450e158ed3b839c125c949d68e8cfb738fa75/classes/Category.php#L789)):*
> ```PHP
>             $sql .= ($random === true)
>                 ? ' ORDER BY RAND() LIMIT ' . (int)$random_number_products
>                 : ' ORDER BY ' . (!empty($order_by_prefix) ? $order_by_prefix . '.' : '') . '`' . bqSQL($order_by) . '` ' . pSQL($order_way) . ' 
> ```

This ternary should be replaced by if / else. Doing so, you will avoid the code duplication (lines 782 and 789)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8699)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
This solution needs to be simplified. Multi-level if / elses are never a good solution. It also increases the N-path, and degrades maintainability (brain bandwidth is not unlimited)

**Comment by Azouz-Jribi** [comment]
@LittleBigDev 
Correction is done, can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[classes/Category.php, line 781 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-L4Fuij5m5h0pSP1NuQu:-L4Fuij5m5h0pSP1NuQv:b-hk53ob) ([raw file](https://github.com/prestashop/prestashop/blob/ba1d4e1a2cf5afcd2c093bd22a00a165a4412a5c/classes/Category.php#L781)):*
> ```PHP
> 
>         if ($random === true) {
>             $sql .= ' ORDER BY RAND()' . $isOrderByPrice ? '' : ' LIMIT ' . $limitLength;
> ```

Please take care of the future reader :
```php
$sql .= ' ORDER BY RAND()';
if (!$isOrderByPrice) {
    $sql .= '  LIMIT ' . $limitLength;
}
```

---

*[classes/Category.php, line 786 at r3](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-L4FuMWelmUeFkJ9LPij:-L4FuMWfKA6_0tf5wd2j:bemwt1c) ([raw file](https://github.com/prestashop/prestashop/blob/ba1d4e1a2cf5afcd2c093bd22a00a165a4412a5c/classes/Category.php#L786)):*
> ```PHP
>             $limitOffset = (((int)$p - 1) * $limitLength);
>             $sql .= ' ORDER BY ' . (!empty($order_by_prefix) ? $order_by_prefix . '.' : '') . '`' . bqSQL($order_by) . '` ' . pSQL($order_way);
>             $sql .= $isOrderByPrice ? '' : ' LIMIT ' . $limitOffset . ',' . $limitLength;
> ```

Please take care of the future reader :
```php
if (!$isOrderByPrice) {
    $sql .= ' LIMIT ' . $limitOffset . ',' . $limitLength;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8699)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Almost there !

**Comment by Azouz-Jribi** [comment]
Hello @LittleBigDev 
can you check it ?

Thanks ;)

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8699#-:-L4tl_4voolHPomHIqMW:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]
Thank you @Azouz-Jribi

**Comment by kpodemski** [comment]
👍

**Comment by marionf** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

Futhermore, I can't reproduce the issue with PrestaShop 1.7.6.1

**Pull request closed without merging**
