### PR TITLE
[-] BO: Removed hardcoded BO header image

### PR DESCRIPTION
**Pull request by guestisp**
Make properly use of CSS background class. Allow overriding header image through `overrides.css`

### CODE REVIEW

**Comment by guestisp** [comment]
Any issue with this ?

**Comment by guestisp** [comment]
Is possible to merge this? I don't like hardcoded page elements, images should be wrote in CSS (and thus overridable by `overrides.css`)

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your PR, there is a big diff on your CSS files, If you want you can resync your fork (Please see https://help.github.com/articles/syncing-a-fork/) or you can change your PR, removing css, or I can close this PR and push it manually to current branch.

Let me know.

Best regards.

**Comment by guestisp** [comment]
I had some issue with SASS files. If you can and if this is not an problem for you, you can close this and add `background: url('../img/prestashop-avatar-header_shopname.jpg') no-repeat top left` to `#header_shopname` class and remove `{$shop_name|escape:'html':'UTF-8'}` from template. 

Probably is the easiest way to fix this PR.

**Comment by guestisp** [comment]
The same could be done for login page.

**Comment by jeromenadaud** [comment]
OK, I will do it right now.
I close this PR.

Best regards.

**Comment by jeromenadaud** [comment]
Hi,

Done, but for login page it's a little more complicate, if you have time you can make a PR in order to change logo img to css. If not, we will do it when we have some resource free.

Best regards.

**Comment by guestisp** [comment]
I'll try but every time i create some changes to SASS files, my PR generate tons of changes.

**Comment by guestisp** [comment]
Why harder?
I can remove these:
```
<img id="logo" width="40px" src="{$img_dir}icon-prestashop.svg"/>
			PRESTASHOP
```

from login template, make a new image and a PR but I can't customize SASS files to reflect changes.

**Pull request closed without merging**
