### PR TITLE
Protect .git folder with htaccess

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Protect .git folder with htaccess
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | see issue
| Fixed issue or discussion?     | Fixes (https://github.com/PrestaShop/PrestaShop/issues/34052)
| Sponsor company   | Creabilis

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Comment by boherm** [comment]
Thanks for your contribution @jf-viguier!

I have relauch the failed jobs on the CI. (It could be a false positive 🤔)

Also, to have a cleaner history when we merge your PR, can you merge your commit [cs fixer](https://github.com/PrestaShop/PrestaShop/pull/34122/commits/678d03b6c63d1710c3473babd2c7041b88815d96) into your [Protect .git folder with htaccess](https://github.com/PrestaShop/PrestaShop/pull/34122/commits/d8c4f497eddd407945357fe5db0ecaaebec743e4), please?

**Review by kpodemski — CHANGES_REQUESTED** [review]
There are unrelated commits in your PR.

**Comment by jf-viguier** [comment]
@boherm rebase done.
@kpodemski no more, a rebase error

**Review by kpodemski — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]
I hesitated before aproving.... the PR seems overkill (you're not supposed to deploy prestashop with GIT), but then you talked about the case of the development server on the open internet...  

I guess it doesn't harm and secures private data on dev servers 👍

**Comment by jf-viguier** [comment]
Thanks @matthieu-rolland 
Have you all read this website ? https://www.repo-lookout.org/

"Including our most recent security scan on October 19, 2023, we have scanned 10,632,272,454 URLs on 1,136,564,612 domains. A total of 1,038,683 publicly exposed source code repositories have been found to date.

As a result, Repo Lookout sent 546,755 emails to the technical contact, of which 388,927 emails were successfully delivered."

**Comment by florine2623** [comment]
Can this be QAed by dev ?

**Comment by jf-viguier** [comment]
@florine2623 the how to test is in the issue.
Just git clone PrestaShop from source to have a .git folder

**Review by jolelievre — DISMISSED** [review]

**Comment by Progi1984** [comment]
Sorry @ps-jarvis : But the CI is :red_circle: :) 

I let @PrestaShop/committers decide.

(Sorry @jf-viguier ;) )

**Review by boherm — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by matks — APPROVED** [review]
As mentioned before, I think this PR is theoretically not useful.

A production environment should NEVER expose a .git (the .git should be removed before exposing the server if it is inside the exposed server directory).

... but I said "should" and we know the world does not follow "should" right 😅 (in French "avec des si on mettrait Paris en bouteille") ?

- adding this line does NOT introduce drawbacks
- it does introduce benefits for people who did not remove the .git for a production environment

So I approve 👍

**Comment by jf-viguier** [comment]
Thanks @matks @kpodemski @matthieu-rolland @boherm 
Improve security in any way is always good for your community, so many security holes in the PrestaShop eco-system.
We all know that "the world does not follow "should" right"

**Comment by Robin-Fischer-PS** [comment]
Hi,

Added the "Waiting for dev" label as this should be tested by a dev.

Thanks for the PR @jf-viguier !

**Comment by BarbUk** [comment]
FYI (after discussion today with @jf-viguier).

About the vulnerability fixed by this PR:
 - Exposing the .git directory is a vulnerability documented by [CWE 527](https://cwe.mitre.org/data/definitions/527.html)
 - All data in an exposed git directory can be scraped (mail, database config, external api keys).
 - If you have a hosting with a predictive database tool (`/adminer.php`, `/phpmyadmin`), your database is now compromised / dumped.

You already document blocking [every dotfile / dotdir in your own documentation for nginx](https://github.com/PrestaShop/docs/blob/ccce7fde7e012118379ab0527bb3408b10f0c708/basics/installation/advanced/nginx.md?plain=1#L88-L91).

[@772424](https://github.com/772424), we block every dotfiles / dotfolder by default (protecting `/.env` or `/app/config/.parameters.php.swp`), so I think this is the next step after this PR is merged.

**Comment by jf-viguier** [comment]
Thanks @BarbUk for new arguments, you rocks

**Review by matthieu-rolland — COMMENTED** [review]
QA dev OK 👍  (by me)

**Comment by matthieu-rolland** [comment]
thank you @jf-viguier 👍

**Pull request merged**
