### PR TITLE
Fix non scalar value in translation

### LINKED ISSUE #35175: Trying to translate front-office with PS 9.0.0 gets a fatal error page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Trying to translate front-office with PS 9.0.0 gets a fatal error page

Capture d’écran 2024-01-25 à 17 32 36

### Expected behavior

It should open the Translation Edit page without error

### Steps to reproduce

1. Install PrestaShop using `develop` branch, in French
2. Go to back-office, open Translation menu
3. Select the following options (see below the screenshot)
4. Click on "Modify"

Capture d’écran 2024-01-25 à 17 32 46

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix non scalar value in translation. I also fixed a token issue on a translations form
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI / UI tests are green
| UI Tests          | https://github.com/nesrineabdmouleh/testing_pr/actions/runs/7871213565
| Fixed issue or discussion?     | Fixes #35175
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by tleon — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @M0rgan01

**Comment by nesrineabdmouleh** [comment]
UI tests => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/7871213565 :green_circle:

**Review by Progi1984 — APPROVED** [review]
@nesrineabdmouleh Approved for UI tests

**Review by boherm — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @M0rgan01

I tested your PR and it's GOOD for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Pull request merged**
