### PR TITLE
Add return types for front controllers methods

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Adds return types to front controllers. Removes some unnecessary returns that were found.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | no - I intentionally left FrontController and AdminController alone, so module controllers do not fail on `method X not compatible with FrontController::Y`
| Deprecations?     | no
| How to test?      | Run auto tests.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/11570400336 ✅ 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by Hlavtox** [comment]
@FabienPapet This could warm your heart :D

**Review by kpodemski — APPROVED** [review]

**Review by ShaiMagal — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Comment by FabienPapet** [comment]
Thank you so much ❤️

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `BC breaks` should be `yes` or `no`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#bc-breaks))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

Auto tests are green ! This doesn't need functional testing.
It is QA ✅ 
Thanks!

**Comment by Hlavtox** [comment]
Thank you @florine2623 !!! :-)

**Pull request merged**
