### PR TITLE
Fix sorting by Relevance in search results (develop branch version)

### LINKED ISSUE #34174: Product Search Relevance Option is Reversed When Manually Selected
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When using the search products are displayed ordered by "Relevance" but the "Sort by:" drop-down shows "Choose". If "Relevance" is selected from options the products are listed in reverse order. i.e. the lease relevant first. 

### Expected behavior

The "Relevance" option should be selected by default and list products with the most relevant first.

### Steps to reproduce

Do a search in the front end.
Check the sort order displayed on the results page and make note of the product order.
Use the on page drop-down to select "Relevance" sort order.
Check the order of the displayed products.

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by mrkalchemy**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | suggested fix for issue #34174 (develop branch)
| Type?             | bug fix
| Category?         | FO 
| BC breaks?        |  no
| Deprecations?     | no
| How to test?      | Search option defaults to "Relevance" and selecting 'Relevance' displays in correct match order.
| UI Tests          | https://github.com/mrkalchemy/ga.tests.ui.pr/actions/runs/6905998626
| Fixed issue or discussion?     | Fixes #34174 
| Related PRs       | #34317 (8.1.x version)
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by nicosomb** [comment]
Hello @mrkalchemy 
Is this Provider used only once?

**Comment by mrkalchemy** [comment]
> Is this Provider used only once?

Hi @nicosomb,
Yes, as far as I know it's only used for the search page.

**Review by nicosomb — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @mrkalchemy ,

Thanks for your PR.

I see that it is fixed. The sorting drop-down is well displayed. And the search page displayed the product in the correct order.

Screenshot 2023-11-20 at 16 35 32

Screenshot 2023-11-20 at 16 35 37

It is QA ✅

**Comment by nicosomb** [comment]
Thank you @mrkalchemy !

**Pull request merged**
