### PR TITLE
Remove irrelevant die() and throw exception instead

### LINKED ISSUE #18521: Die() in Customer class
#### Describe the bug

Why oh why do you die()?
In classes/Customer.php, method getByEmail, line 445, you check if the email address is valid, and if not  you kill the script.

#### Expected behavior

Throw an exception, return false, log a fatal error, whatever. Just don't kill the script. The current way can cause some nasty and hard to find issues, and it simply doesn't look good to clients.

#### Steps to Reproduce

---

**Screenshots**

---

#### Additional information

* PrestaShop version: 1.7.6.3 to current
* PHP version: N/A

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove irrelevant die() and throw exception instead in `Customer::getByEmail()`
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/18521
| How to test?  | No need for QA

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18531)

### CODE REVIEW

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@matks Travis is all red ;) Please fix Travis before review ;)

**Comment by matks** [comment]
@Progi1984 @PierreRambaud Very funny 😄 

I added a trailing comma to a function
```
if (($plaintextPassword && !Validate::isPlaintextPassword($plaintextPassword))) {
            throw new \InvalidArgumentException(
                'Cannot get customer by email as given password is not a valid password',
            );
        }
```

So my code is php7.3 compliant but not php7.1 or php7.2 compliant 😆 
Capture d’écran 2020-04-24 à 10 59 16

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
@atomiix I think this PR needs no QA (I added it in PR description) as code change is relevant and ... also because I dont know what QA can test 😄 

If you agree please merge

**Comment by Progi1984** [comment]
@matks Too late
image

**Comment by matks** [comment]
> @matks Too late
> image

Nope, @SD1982 asked me to write this message because he does not know either what to do 🤣

**Comment by atomiix** [comment]
OK for me @matks, thanks!

**Pull request merged**
