### PR TITLE
[-] FO: Add hooks "actionProductListOverride" & "actionProductListModifier" on products list

### PR DESCRIPTION
**Pull request by prestamodule**

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

We are looking to rework this on the starter theme branch. Nothing is defined yet but this might be tightly related to @djfm's work on layered navigation.

I'll close this PR (I want to delete this branch as well). Feel free to talk about it on Gitter :)

Thanks

**Comment by kpodemski** [comment]
@julienbourdeau 1.6.1 tree is final before 1.7? There will be no 1.6.2?

**Comment by julienbourdeau** [comment]
Hi, what do you mean final ?

1.6.2.0 have been cancelled weeks ago, we kept the branch until we processed all open pull request. :) An article is coming on build as well (of course).

**Comment by kpodemski** [comment]
@julienbourdeau I didn't know that 1.6.2 was cancelled... I don't think it is a good idea but I'll wait for an article on build.prestashop... stable 1.7 with such a huge changes will be released in... 8-12 months? almost 1 year without new features in PrestaShop (respecting semver where 1.6.1 will not have any)? I don't like it.

**Comment by julienbourdeau** [comment]
We expect PrsetaShop 1.7 earlier :)
http://build.prestashop.com/news/version-1-7-0-0-is-underway/

Basically, we'd rather deliver 1.7 sooner than add little features to 1.6. :P

**Comment by PrestaEdit** [comment]
Hi @julienbourdeau ,

Do you think we can integrate this kind of PR into the 1.6.1.5 ? ;-)

**Pull request closed without merging**
