### PR TITLE
Remove meta keywords

### LINKED ISSUE #11144: Remove meta keywords from Prestashop - they are deprecated
In Traffic & SEO > SEO & URLs, we need to add an option in the SEO options block to allow the merchant to enable or disable metakeywords fields in every page where this field exists : 
- product page
- category page
- cms page
- brands page
- suppliers page

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Initial issue : META keywords are deprecated

So this line of code from /templates/_partials/head.tpl file is useless and potentialy risky.

`<meta name="keywords" content="{block name='head_seo_keywords'}{$page.meta.keywords}{/block}">

image

`
**Source**
https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html
https://datadrivenlabs.io/blog/meta-keyword-tag-google-2018/

**Reason?**
Not relevant keywords stuffing

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | Meta keywords have been deprecated by the PM team and in the code, they are dead for more than 20 years. This does not touch product tags - they are a different thing. :-)
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Concerns few BO pages, but they should all be covered by tests.
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/10788272365
| Fixed issue or discussion?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/11144
| Related PRs       | https://github.com/PrestaShop/hummingbird/pull/653, https://github.com/PrestaShop/classic-theme/pull/153, https://github.com/PrestaShop/blockwishlist/pull/281, https://github.com/PrestaShop/autoupgrade/pull/1009
| Sponsor company   | 

❗ Needs autoupgrade PR after it's merged!

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]
It's ok for me.

**Comment by Hlavtox** [comment]
@kpodemski There are two issues with test:
-  Undefined array key "keywords" in /var/www/html/var/cache/prod/smarty/compile/classiclayouts_layout_full_width_tpl
- Module test that throws 500 because blockwishlist selecting pl.meta_keywords.

Should I fix it and release it, or we can merge this PR and do it afterwards? It will need autoupgrade PR also.

**Comment by kpodemski** [comment]
@Hlavtox, you will have to adjust the `blockwishlist`, and we need to release it. There's another release in progress:
https://github.com/PrestaShop/blockwishlist/pull/276

Maybe you could add the check with `version_compare` not to make module compatible only with v9 because of this change and rather handle v9 and versions below in a module.

> Undefined array key "keywords" in /var/www/html/var/cache/prod/smarty/compile/classiclayouts_layout_full_width_tpl

This is also something to be fixed. For the time being `develop` here depends on classic dev branch, so it's just a matter of fixing it on the develop. See https://github.com/PrestaShop/PrestaShop/blob/develop/composer.json#L62

**Comment by Hlavtox** [comment]
@kpodemski 
- Fixed in both themes
- Waiting for https://github.com/PrestaShop/blockwishlist/pull/280 and https://github.com/PrestaShop/blockwishlist/pull/276

**Comment by gericfo** [comment]
Hello @Hlavtox 
Please note that the **“Needs autoupgrade PR”** label has been automatically added to your Pull Request. This means that the changes made in your PR must also be reported in the **Autoupgrade module**, responsible for running the update process of PrestaShop stores. 
When there's a modification to the `db-structure.sql` file or if a Doctrine entity has been modified, added, or deleted, it impacts the database structure. Modifying the list of hooks and feature flags has consequences on the update process as well. These changes can affect how the application interacts with the database and how update procedures are handled. It's important to consider these aspects when contributing to ensure a smooth update experience for users. 
That's why this contribution should be backported, with another corresponding PR, on the **Autoupgrade module's GitHub repository** which is available here: [link](https://github.com/PrestaShop/autoupgrade). 
Don't forget to add a comment in this current thread with the link to this PR once it has been created. 
Thank you.

**Comment by Hlavtox** [comment]
@gericfo I am the one who introduced this label, I know what to do, thanks

**Review by kpodemski — DISMISSED** [review]
Hello

We recently introduced the 9.0.x branch, which will be the base for PrestaShop 9.0. If you want to see your change in this version, please rebase your PR onto 9.0.x. The `develop` will be used for PrestaShop 9.1, so you need to decide what to do.

Please rebase onto `9.0.x` or let me know your decision if you don't need to have it there so I can unblock the pull request.

**Comment by Hlavtox** [comment]
@kpodemski Hi, rebased

Test run https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11448338345 will probably fail on blockwishlist, because it wasn't yet updated in composer, but a 3.0.2 is already out.

**Comment by Hlavtox** [comment]
Rebased, new run - https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/11520643076

**Comment by kpodemski** [comment]
@Hlavtox I think there are some false-positives, could you restart the tests?

**Comment by Hlavtox** [comment]
@kpodemski I re-ran them two times now. This is really annoying.

I have to re-run both CI and ui tests X times to get them to be green.

**Comment by Hlavtox** [comment]
@kpodemski Krystian, this PR is currently stuck due to tests failing that needs adapting. Can we merge it? I can't get hold of anyone that would be responsible for these tests, unfortunately.

**Comment by nesrineabdmouleh** [comment]
Hello @kpodemski @Hlavtox,

Sorry for the delay, this is a new run https://github.com/nesrineabdmouleh/testing_pr/actions/runs/11572814684
I will adapt tests if there are failures. :)

Thanks!

**Comment by Hlavtox** [comment]
Thank you @nesrineabdmouleh, it's now all green after your magic! :-)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.2.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by ShaiMagal — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@florine2623 Florine do you want to test something or green tests are sufficient? :-)

**Review by florine2623 — DISMISSED** [review]
Hello @Hlavtox ,

Auto tests are enough ✅ : https://github.com/florine2623/testing_pr/actions/runs/11589618667

It can be merged :)
Thanks!

**Comment by Hlavtox** [comment]
@nesrineabdmouleh @Progi1984 Ping for one ui team approval please. :-)

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]
Ok for UI Tests

**Review by ShaiMagal — APPROVED** [review]

**Comment by Hlavtox** [comment]
@nesrineabdmouleh @Progi1984 One more please

**Review by Progi1984 — APPROVED** [review]

**Pull request merged**
