### PR TITLE
Tax Rules Groups > Grid : Confirm Modal & Common Search

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Tax Rules Groups > Grid : Confirm Modal & Common Search
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Relative to #10610
| How to test?      | * Go to `/admin-dev/index.php/improve/international/tax_rules_groups/`<br>* Try to delete or bulk delete : the confirm modal now appears<br>image<br>* Filters on grid works<br>image

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
LGTM 👍

**Review by matks — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Progi1984 ,

I tested multiple cases for bulk delete :
- bulk delete existing tax rules/new tax rules
- bulk delete enabled/disabled tax rules
- bulk delete mix of tax rules
- bulk delete modal appear and deletion is OK ✅ 

I tested the filter :
- filter on character `%` doesn't work
Screenshot 2022-06-16 at 10 01 20

- filter on `ID = 1` should list all the tax rules with ID containing 1.
What I have :
Screenshot 2022-06-16 at 10 02 32

What I should have : 
Screenshot 2022-06-16 at 10 02 38

Could you check please ?
Thanks!

**Comment by Progi1984** [comment]
Thanks @florine2623 

@matks @matthieu-rolland I fixed @florine2623's feedbacks.

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello all,

Thanks for the update.
Everything mentioned above has been fixed !

Modal is displayed when deleting (bulk or one element), all buttons on modal work
Sorting works
Filtering works

It is QA ✅

**Comment by Progi1984** [comment]
Thanks @florine2623

**Pull request merged**
