### PR TITLE
Adjust birthday inputs on create customer page

### LINKED ISSUE #21839: [UI-KIT] - Improve field spacing in customer page
#### Describe the bug
Improve field spacing in customer page

#### Step to reproduce 
1- Go to BO -> Customer 
2- Add a customer
3- See the error

Capture d’écran 2020-11-06 à 17 23 59

#### Additional information

* PrestaShop version: Develop
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Birthday input were'nt taking the full width of columns
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #21839.
| How to test?  | See issue, it's juste width of birthday selects

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21856)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Roomsmaniia** [comment]
It seems there is a Travis error can you please check to fix it ?

Thanks

**Comment by NeOMakinG** [comment]
@RomainBocheux where do you see a Travis error ? Can't find it, it's all green ^^

**Comment by Roomsmaniia** [comment]
@NeOMakinG Travis's status changed a few minutes after my comment

I can test this pr now

**Comment by Roomsmaniia** [comment]
LGTM,

Thanks @NeOMakinG

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @RomainBocheux

**Pull request merged**
