### PR TITLE
Update BO architecture in product settings page

### LINKED ISSUE #24769: Reorganize fields in product settings page
#### Is your feature request related to a problem?

For a better architecture, reorganize fields in BO > shop parameters > product settings page in the following order:

product settings

### PR DESCRIPTION
**Pull request by kevin-xtn**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Reorganize fields n BO > shop parameters > product settings page for a better architecture
| Type?             | improvement 
| Category?         | BO
| BC breaks?        | yes / no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24769.
| How to test?      | BO > shop parameters > product settings verify if fields are saved correctly 
| Possible impacts? | Product pages in FO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26184)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hello @kevin-xtn and thank you for the contribution. I can you've moved some fields around, could you provide a brief explanation of what you moved and why you think the new location is better? 😉

**Comment by kevin-xtn** [comment]
@matks I made this PR as per this issue, https://github.com/PrestaShop/PrestaShop/issues/24769
The issuer described that it improves the BO architecture.

**Comment by Progi1984** [comment]
@kevin-xtn Thank you for your contribution. Could you rebase your PR for fixing conflicting files ?

**Comment by PrestaEdit** [comment]
Ping @kevin-xtn.

**Comment by PierreRambaud** [comment]
Hi @kevin-xtn ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Comment by PierreRambaud** [comment]
Unfortunatelly, I'm not able to rebase your PR and push on your branch, I redo the PR #27440

**Pull request closed without merging**
