### PR TITLE
Module page quicks

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes regressions brought by the switch on bootstrap 4
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3963
| How to test?  | Check upload modals and, in general, modal titles

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8421)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8421#-:-KwdGV8SmANr8BIzMCnA:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]

**Comment by LittleBigDev** [comment]
Travis doesn't approve though...

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8421#-:-Kx8XKnowJ6pv-YCH7me:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @Quetzacoalt91

**Pull request merged**
