### PR TITLE
Fix wrong update of shipping cost when order is updated in BO

### PR DESCRIPTION
**Pull request by LedCloud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | If the order is beeing changed from BO the shipping cost become free (zero) if the qty of the product is more than availble for order. It happens when editing qty, adding new product to the order, deleting one product from the order, changing the qty of the product, address is beeing changed. As I see that's because method refreshShippingCost (Order.php) use updateQty (Cart.php). This method works perfect (as I know) for front office, but it should be rewritten for the BO routins. It can return false but this value is not handled by refreshShippingCost. When refreshShippingCost gets false from updateQty - shipping costs becomes free. I made simple change to the code. Those changes work but I believe new method in Cart.php should be written. Now updateQty still can return false if one add qty more than availble.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5163
| How to test?  | I'm not sure I made all correct. Create order with one or more goods with qty 1 each. Change qty first of them in BO, so new qty would be more than qty availble. Shipping costs would be calculated correct. Without changes the shipping costs get free.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8905)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @LedCloud, thanks for reporting the issue.

I'm not really easy with the patch you have provided but it shows clearly the issue so thank you for that!

What do you think @eternoendless ?

**Comment by LittleBigDev** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[classes/Cart.php, line 1195 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8905#-LAHwAKjDhcJsCB4A3EA:-LAHwAKjDhcJsCB4A3EB:bft9dkq) ([raw file](https://github.com/prestashop/prestashop/blob/fd3255c8e32e8d4b2513e754d309f221e92db7e4/classes/Cart.php#L1195)):*
> ```PHP
>         $auto_add_cart_rule = true,
>         $skipAvailabilityCheckOutOfStock = false,
>         $bo_changes = null //if null - usual behavoir.
> ```

Adding a new parameter is not welcome. We already struggle with mammoth method signatures !

---

*[classes/Cart.php, line 1330 at r1](https://beta.reviewable.io/reviews/prestashop/prestashop/8905#-LAHwl_d4Kh6xneY3uWb:-LAHwl_d4Kh6xneY3uWc:b-hwye52) ([raw file](https://github.com/prestashop/prestashop/blob/fd3255c8e32e8d4b2513e754d309f221e92db7e4/classes/Cart.php#L1330)):*
> ```PHP
> 
>                 if (!Product::isAvailableWhenOutOfStock((int)$result2['out_of_stock'])) {
>                     if (isset($bo_changes)){//changes have been made in BO
> ```

This method should not be aware of any context. We need a more generic behavior.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/prestashop/prestashop/8905)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Hello @LedCloud 
Thx for this PR, highlighting the issue. Your investigations saved us time !
Though, I agree with @mickaelandrieu, another solution should be implemented. Adding a new parameter is not wanted. This is actually a code smell (https://sourcemaking.com/long-parameter-list)
`updateQty()` should not be THAT context-dependent. Maybe the `updateQty()` usage could be fixed in `Order` class instead ?

**Comment by LedCloud** [comment]
If you ask for my opinion, I can say that the quantity in the data base is already changed by the time _updateQty_ called. So the only thing it does is calculating the shipping cost.
Since it is called only from _refreshShippingCost_ (class Order.php) for that purpose, I believe that calculating could be done in _refreshShippingCost_.
But I perfectly understand I cann't do that because I'm not a coder. All I wanted was that you pay attention.

**Comment by eternoendless** [comment]
Hi @LedCloud 

Thank you for your contribution!

Unfortunately, due to the points mentioned before, we cannot accept this PR as-is. We'll keep track of the bug so that we can see it fixed. 

Thanks for understanding. Feel free to open a new Pull Request if you find a better solution.

**Pull request closed without merging**
