### PR TITLE
Add condition to avoid duplicate invoice line.

### LINKED ISSUE #15513: Update order state with Order::setCurrentState() add new line for invoice in order view
**Describe the bug**
When update the order with `Order::setCurrentState()` create a new line in payments for create the invoice. 

**To Reproduce**
Update state with webservice
>[Edited by Khouloud]

Steps to reproduce the issue:

1. Edit the status "Payment accepted" as described in the screenshot
image
3. Create a new order, the first status created is "Payment accepted" [you can create an order from the BO or you can use a Paypal module]
4. Install the module
[fgorderstate.zip](https://github.com/PrestaShop/PrestaShop/files/3651991/fgorderstate.zip)
6. Click on Configure => click on the link & edit the `order_id`
7. Go the BO => Orders => previous Order created => error => new payment line added => wrong
 image

### PR DESCRIPTION
**Pull request by FlorentinGarnier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The method `Order::setCurrentState()` add new line for invoice in order view
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15513 and maybe #11154
| How to test?  |Set an orderstate by webservice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15514)

### CODE REVIEW

**Comment by FlorentinGarnier** [comment]
#15513

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @FlorentinGarnier 

Thank you for this contribution. 
Can you provide us a demo module to test this PR?

Have a nice day

**Comment by FlorentinGarnier** [comment]
Hello @sarahdib,
 You can do this for testing this PR

Best regard


> 
> 
> **Describe the bug**
> When update the order with `Order::setCurrentState()` create a new line in payments for create the invoice. 
> 
> **To Reproduce**
> Update state with webservice
> >[Edited by Khouloud]
> 
> Steps to reproduce the issue:
> 
> 1. Edit the status "Payment accepted" as described in the screenshot
> image
> 3. Create a new order, the first status created is "Payment accepted" [you can create an order from the BO or you can use a Paypal module]
> 4. Install the module
> [fgorderstate.zip](https://github.com/PrestaShop/PrestaShop/files/3651991/fgorderstate.zip)
> 6. Click on Configure => click on the link & edit the `order_id`
> 7. Go the BO => Orders => previous Order created => error => new payment line added => wrong
>  image
>

**Comment by FlorentinGarnier** [comment]
Hello, do you have take into account my last comment ?

**Comment by matks** [comment]
Closing and re-opening to reset Travis

**Review by matks — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @FlorentinGarnier

**Pull request merged**
