### PR TITLE
Fix bug on contact when mail is too long

### LINKED ISSUE #12799: Contact Information - email too long is cut
**Is your feature request related to a problem? Please describe.**
When the email is too long, the email is cuted. The number of character possible is very limited for email address before it is cut.

image

**Describe the solution you'd like**
Use the space underneath the icon

### PR DESCRIPTION
**Pull request by YeLnatSs**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | New design for email in contact page due to mail too long
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #12799 
| How to test?  | Check sidebar in contact page.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12893)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
Hello @YeLnatSs,

this need a rebase but it's good to me so far :+1: 

Good job

**Review by jolelievre — APPROVED** [review]
Thanks @YeLnatSs

**Review by jolelievre — CHANGES_REQUESTED** [review]
Actually you need to rebase and rebuild the CSS

**Review by jolelievre — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @YeLnatSs

**Pull request merged**
