### PR TITLE
Object with multilang field update bug

### PR DESCRIPTION
**Pull request by gu78**
Fix a bug when updating multilingual field values in a form generated by form helper

### CODE REVIEW

**Comment by Shudrum** [comment]
function (e){var t,n,r,i=this[0];{if(arguments.length)return r=Q.isFunction(e),this.each(function(n){var i;1===this.nodeType&&(i=r?e.call(this,n,Q(this).val()):e,null==i?i="":"number"==typeof i?i+="":Q.isArray(i)&&(i=Q.map(i,function(e){return null==e?"":e+""})),t=Q.valHooks[this.type]||Q.valHooks[this.nodeName.toLowerCase()],t&&"set"in t&&void 0!==t.set(this,i,"value")||(this.value=i))});if(i)return t=Q.valHooks[i.type]||Q.valHooks[i.nodeName.toLowerCase()],t&&"get"in t&&void 0!==(n=t.get(i,"value"))?n:(n=i.value,"string"==typeof n?n.replace(ct,""):null==n?"":n)}}[How to write a commit message](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)

**Comment by Shudrum** [comment]
Hi gu78,

Thank you for your contribution.

Is there a way that **$this->id_lang** can be something else than a int, null ? You have find some cases where **$this->id_lang == 0** ?

BTW, can you follow the PrestaShop's commit norms ? 

Thank you again !

**Comment by gu78** [comment]
Hi Julien 

In the tests made $THIS.>ID_LANG values were int > 0, null or array. For
the last 2 cases the if condition is valid. 

 I'm sorry about the commit rules, I don't have so much time on a shitty
day. 

About the brackets, I left them as they were before. 

I reported the bug in the forum, but I think that no one will ever patch
that bug so I did by myself. 

https://www.prestashop.com/forums/topic/484131-fallo-al-actualizar-campo-multi-idioma-en-modulo/


-- 

Kind regards - Saludos cordiales - Med vänliga hälsningar - Freundliche
Grüsse 
-------------------------

GUSTAVO DURAN

gustavo@duranlinar.es
Tel: +34 605 205 273 Malaga - Spain 

El 2015-11-20 16:09, Julien Martin escribió: 

> Hi gu78, 
> 
> Thank you for your contribution. 
> 
> Is there a way that $THIS->ID_LANG can be something else than a int, null ? You have find some cases where $THIS->ID_LANG == 0 ? 
> 
> BTW, can you follow the PrestaShop's commit norms ? 
> 
> Thank you again ! 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1]
https://github.com/PrestaShop/PrestaShop/pull/4497#issuecomment-158426308

**Comment by antoin-m** [comment]
Hi @gu78, thank you for your contribution!

I cherry-picked your PR here https://github.com/PrestaShop/PrestaShop/pull/7473

**Pull request closed without merging**
