### PR TITLE
Don't register `module` on `hook` if already registered

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Don't register `module` on `hook` if already registered.
| Type?             | improvement 
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A.
| Related PRs       | N/A
| How to test?      | N/A
| Possible impacts? | Make sure that you can register you module to a hook `$this->registerHook('yourHookName')`.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hello @PululuK this looks like a nice idea, but it seems a similar check is already implemented below at line 595 (see `// Check if already registered`)

So I might be missing something but I expect that
- either the logic below at line 595 is faulty, then we need to fix it instead of adding a check
- or the logic at line 595 is correct, then what usecase do you handle?

**Comment by PululuK** [comment]
> Hello @PululuK this looks like a nice idea, but it seems a similar check is already implemented below at line 595 (see `// Check if already registered`)
> 
> So I might be missing something but I expect that
> 
>     * either the logic below at line 595 is faulty, then we need to fix it instead of adding a check
> 
>     * or the logic at line 595 is correct, then what usecase do you handle?

Thanks @matks, so I just remove the old check to avoid code duplicate

**Review by kpodemski — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello, 

A second review approval please to can test this PR? 
ping @matks 

Thanks!

**Review by atomiix — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @PululuK 

As validated by our QA-team, this PR needs only the automated tests.
I checked the automatic tests : OK :heavy_check_mark: 

So, it's QA :heavy_check_mark: 

Thank You!

**Comment by jolelievre** [comment]
Thanks @PululuK and @HanaRebaiQA

**Pull request merged**
