### PR TITLE
Partial fix for textarea field height issues in V1 product page

### LINKED ISSUE #35680: Textarea fields randomly broken on product page
### Describe the bug and add attachments

All tinymce fields on product page get randomly broken after some time of inactivity, or going to another tab and doing some actions.

Sometimes they break completely, sometimes they work, sometimes they shrink to some min size. You have to type inside to make them work again.

https://github.com/PrestaShop/PrestaShop/assets/6097524/65a6be73-6bd6-4552-9e77-12c984adbad5

### Expected behavior

It should work properly.

### Steps to reproduce

See video in issue description.

### PrestaShop version(s) where the bug happened

8.1.5

### PR DESCRIPTION
**Pull request by Roxayl**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | See #35692 (that I closed earlier). This fix is only applicable to the old product page, so merging in the 8.1.x branch makes more sense. This fix also addresses the issue of a superfluous focus on the textarea field introduced by the previous PR.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/35680#issuecomment-2009101266 
| UI Tests          | N/A
| Fixed issue or discussion?     | Partial fix/workaround for #35680
| Related PRs       | Follow-up for #35692
| Sponsor company   | [WAM](https://www.linkedin.com/company/wam-intl/)

NB: This PR does not address the issue in the new product page. In fact, there's probably a better way to fix completely the issue with TinyMCE fields in hidden tabs by using TinyMCE's event handling capabilities, but that requires some thorough UI testing so I'll think about it in a few weeks when I'll have more time. In the meantime, this should be a nice temporary workaround for the old product page.

### CODE REVIEW

**Comment by SharakPL** [comment]
Is PP.V1 still receiving fixes? I could have one or two 😉

**Review by kpodemski — DISMISSED** [review]

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by matks** [comment]
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

**Review by kpodemski — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Roxayl ,

Without PR with Product Page V2:

https://github.com/user-attachments/assets/3278b395-5542-42b5-aa20-83fd7df79184

With PR with Product Page V1:

https://github.com/user-attachments/assets/1bf8851d-f33d-42f7-86e1-459833f3793a

It is fixed for PPV1 and it is QA ✅ 
Thanks!

**Comment by florine2623** [comment]
Did you close the PR by mistake @Roxayl ?

**Comment by alexandrebru83** [comment]
With this commit in V1, now when admin clic on second tab and clic on first tab, it's auto scroll to description.

**Comment by alexandrebru83** [comment]
@florine2623 ? :)

**Pull request merged**
