### PR TITLE
Complete Php error handler

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | It's time to complete the current Php error handler when launching our test suites with a stack trace.
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Take a look at travis, before you only get a minimalist summary, now you get a list of every error spotted during the test suite execution: far better :+1: .

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12985)

### CODE REVIEW

**Comment by matks** [comment]
Capture d’écran 2019-03-20 à 17 55 34

😭

**Review by matks — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
> ;'(

I know ... it's time to manage this technical debt, too. Baby steps :+1:

**Comment by matks** [comment]
I'd like one more review from another dev as I'm worrying this will slow us rather than help us (what would be ideal would be to have all warnings *and* fix them but that would make the PR a lot bigger)

@Quetzacoalt91 @PierreRambaud @jolelievre ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
It's a good idea, but we must plan to remove all this warning / errors.
It'll help us to be sure we can remove deprecated functions =)

**Comment by mickaelandrieu** [comment]
For the deprecations, we'd better enable the deprecation helper of Symfony (but it will break the tests).

I don't think the output is really slow (maybe few more seconds for each test suite).

The big question is: does it help to make this technical debt managed?

If the answer is no, we'd better close this one (no hard feeling for me, don't worry!)

**Comment by PierreRambaud** [comment]
I think it can help and we don't care about one more minute for tests if it doesn't break anything for install & use.

**Comment by mickaelandrieu** [comment]
Don't worry, it's only enabled for PHPUnit :)

**Comment by Quetzacoalt91** [comment]
There a loooooooot of data in the Travis log with this PR, and I was unable to find the actual result of the unit tests. The idea is good, but it currently makes too much noise in my opinion for a daily use of Travis.

I would suggest to merge this when we are ready to handle these notices.

**Comment by matks** [comment]
Following Quetzacoalt91 feedback, I postpone this as we are not ready to merge it.

**Comment by mickaelandrieu** [comment]
ping @matks any chance to get this one merged in 1.7.7?

Or I close: let's not keep prs open when they are unlikely to be merged :)

**Pull request closed without merging**
