### PR TITLE
Update jQuery to 3.4.1 in installation pages

### LINKED ISSUE #15508: Update jquery to latest version in Installation process 4/4
EPIC: #13829

Update installation process's jquery version so that the old jquery (1.11) can be safely removed.

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Update jquery version in installation process
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15508
| How to test?  | Try to install prestashop, everything should be ISO.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15888)

### CODE REVIEW

**Comment by Progi1984** [comment]
@matthieu-rolland I just reset a Travis test ;)

**Comment by Progi1984** [comment]
@matthieu-rolland The PR fixes two problems. Could you divide it in two PR, please ?

**Comment by matthieu-rolland** [comment]
> @matthieu-rolland The PR fixes two problems. Could you divide it in two PR, please ?

It should be fine now, I just needed to rebase my branch already, develop is evolving so fast :D

**Review by Progi1984 — APPROVED** [review]
Perfect ;)

**Comment by matks** [comment]
Thank you @matthieu-rolland

**Pull request merged**
