### PR TITLE
Fixed product customization duplication

### PR DESCRIPTION
**Pull request by shaffe-fr**
| Questions | Answers |
| --- | --- |
| Branch? | develop, 1.6.1.x |
| Description? | Fix an SQL error when duplicating a product with customization fields. This error is caused by the id_shop column added in the customization_field_lang table with PrestaShop 1.6.0.12. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Create a product, add customization fields, duplicate de product |

Fix an SQL error when duplicating a product with customization fields.
This error is caused by the id_shop column added in the customization_field_lang table with PrestaShop 1.6.0.12.

### CODE REVIEW

**Comment by shaffe-fr** [comment]
I don't know why the travis build is failing and I don't think I can do anything to fix it. Can anyone help me? 
Thanks

**Comment by mickaelandrieu** [comment]
Hi @shaffe-fr,

is it a bug for 1.6.0.12? Do you reproduce the same issue on the latest 1.7.0 ?

Mickaël

**Comment by shaffe-fr** [comment]
Hi @mickaelandrieu, I did test with the latest 1.7.0 but it's a bug for 1.6.0.x and 1.6.1.x.

**Comment by aleeks** [comment]
Hello @shaffe-fr 
I cherry-picked your commit here https://github.com/PrestaShop/PrestaShop/pull/7514 rebased from develop.

Regards

**Pull request closed without merging**
