### PR TITLE
Update TranslationToolsBundle to version 6

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update TranslationToolsBundle to version 6 which has been upgraded to use Symfony 5.4
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green and tests UI green https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5123020780 And since it's related to translation maybe check the Transation edition page for the core and for modules (testing with a non native module would be a plus)
| Fixed ticket?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Review by boherm — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by lartist** [comment]
Auto tests https://github.com/lartist/ga.tests.ui.pr/actions/runs/5130770502

**Review by M0rgan01 — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @jolelievre 

Thanks for your PR 🚀 
All the translation works but the FO>hummingbird (btw, it works on 8.1.x), see the attached screen record below:

[pr_32720.webm](https://github.com/PrestaShop/PrestaShop/assets/23308427/bf7ede0b-9182-428b-a419-6cf8c85d6af8)

Please check and feedback.

Thanks!

**Comment by jolelievre** [comment]
Hi @hibatallahAouadni,

I fixed the bug you detected, although it as not related to this PR because there was the same bug on develop. There's a `404` wording used in hummingbird that was auto casted to an `int` by PHP, I forced casting to string to avoid this error

**Review by matthieu-rolland — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @jolelievre 

I checked the translation: BO, FO (Classic & HummingBird), modules (natives & non-natives), email (subject & body), all works 🚀 🙌 well done 👏 
The auto tests are 🟢 https://github.com/hibatallahAouadni/testing_pr/actions/runs/5840746316
LGTM, QA ✅ 

Thanks!

**Comment by kpodemski** [comment]
thanks @jolelievre

**Pull request merged**
