### PR TITLE
Fix: Notice: Trying to access array offset on value of type null 

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | See 1st commit desc for stacktrace. I do not know the reason (seems like some module is downloaded incomplete or so), but I can reproduce the issue repeatably on our Gitlab server. Also, I think Sanity tests fail for the same reason.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | GH CI must pass (several times at least :) )
| Possible impacts? | no

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23955)

### CODE REVIEW

**Comment by Progi1984** [comment]
@mvorisek As said in #23908, I contacted the internal PS Accounts team. They have fixed the problem in next major. So I close this PR.

**Comment by mvorisek** [comment]
@Progi1984 thanks for reply, where is the the PS Accounts Module located on Github?

**Comment by Progi1984** [comment]
Actually, the repository is not opened. I contact team about that.

**Comment by mvorisek** [comment]
@Progi1984 If that is 3rd party module, why we allow it to break PS install, shouldn't this PR be merged to prevent that?

**Comment by eternoendless** [comment]
> If that is 3rd party module, why we allow it to break PS install

That is a very good question indeed. In the future, there will be no 3rd party modules being pushed on install, we are working on it.

**Comment by mvorisek** [comment]
> there will be no 3rd party modules being pushed on install, we are working on it.

Is there any ticket and ETA for it?

**Pull request closed without merging**
