### PR TITLE
[-] FO: #PSCSX-6820 part 2/2

### PR DESCRIPTION
**Pull request by kpodemski**
Solved second problem

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Sponsor company | impSolutions

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, thank you for your contribution.

Best regards

**Comment by gRoussac** [comment]
Hello,

Désolé mais ce PR n'est pas correct, un module ne doit pas avoir son 
code dans global.js.

Avec jquery on peut tout binder comme on veut, le module doit gerer dans 
son script mais pas dans le core ni dans le thème.

Greg

**Comment by gRoussac** [comment]
Hi,

Sorry but could not this be rather included or tweked in blacklayered.js with an off/on jquery method for instance, I do not like to see this module interfering in the theme global file.

Regards

**Comment by kpodemski** [comment]
Hi @gRoussac and @jeromenadaud 

Yes, it could be fixed in blocklayered within this code:

`$(document).off('change', '.selectProductSort').on('change', '.selectProductSort', function(e) {
		$('.selectProductSort').val($(this).val());

		if($('#layered_form').length > 0)
			reloadContent(true);
	});

	$(document).off('change', 'select[name=n]').on('change', 'select[name=n]', function(e)
	{
		$('select[name=n]').val($(this).val());
		reloadContent(true);
	});`

instead of existing one which won't work and I didn't notice this :)

**Comment by gRoussac** [comment]
Hi,

thanks for getting back, can I revert your PR so ?

regards

**Comment by kpodemski** [comment]
Yep, see #4058 and let me know if it is ok :)

**Comment by kpodemski** [comment]
Sorry, wrong branch!

**Pull request merged**
