### PR TITLE
Move StockController into Admin/Sell/Catalog/

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Moved StockController into the appropriate namespace
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes - The file changed its namespace and location
| Deprecations?     | no
| Fixed ticket?     | N/A
| How to test?      | The stock page loads
| Possible impacts? | This only impacts the page load because the content is handled by another controller

## Breaking changes

Moved files:
- src/PrestaShopBundle/Resources/views/Admin/Stock/overview.html.twig 
  → src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Stock/overview.html.twig

Moved classes:
- PrestaShopBundle\Controller\Admin\StockController 
  → PrestaShopBundle\Controller\Admin\Sell\Catalog\StockController

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26836)

### CODE REVIEW

**Review by sowbiba — APPROVED** [review]
Looks good. Thanks @eternoendless

**Review by PierreRambaud — COMMENTED** [review]
I approve but we need more information about the BC breaks.
Otherwise, we will have to check the whole PR in the future to document the BC (whereas, a simple copy & paste will do the job :p )

**Comment by eternoendless** [comment]
> we need more information about the BC breaks.

What's missing in the description? The main thing that changes is the path of the controller and the template

**Review by jolelievre — APPROVED** [review]
Legitimate, but I agree with that we can add a bit more details in the description about the template that has been moved

**Comment by PierreRambaud** [comment]
> > we need more information about the BC breaks.
> 
> What's missing in the description? The main thing that changes is the path of the controller and the template

I'm not sure having only `The file changed its namespace and location` in the next changelog means something, you have to define which files, which namespaces are changing, etc.
See https://github.com/PrestaShop/PrestaShop/pull/26024

**Comment by eternoendless** [comment]
Description added

**Comment by PierreRambaud** [comment]
Thank you @eternoendless

**Pull request merged**
