### PR TITLE
Ease CustomerAddressForm customization

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Demonstrates how native classes may be open for extension but closed for modification.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | At some point, @azisyus may share his needs.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9440)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @azisyus,

can you confirm this update is enough to allow you to change the behavior of the submit action?

Regards,

**Comment by mickaelandrieu** [comment]
ping @azisyus,

would you mind to tell us if it helps you or not?

In all cases, I'll remove public access to the form properties.

Mickaël

**Comment by azisyus** [comment]
@mickaelandrieu sorry for delay, as you said it helps with hook and new get set methods, adding get set methods instead of changing access modifiers probably always better solution and i think this PR proves necessity of hooks because we cant override everything but also overrides fixes things fast and makes happy customer as you can understand we cant wait for new versions to fix our personal needs and also thats why you should remove override feature otherwise many php guy will use this feature hardly while writing module, i was using because i saw it in your [documents](https://devdocs.prestashop.com/1.7/modules/creation/module-file-structure/), first of all you need to remove from docs then it will slowly disappear and when the times comes you just remove the overrides and everything will be fine.

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
> i was using because i saw it in your documents, first of all you need to remove from docs then it will slowly disappear and when the times comes you just remove the overrides and everything will be fine.

:+1: you can count on me to remove every mention of overrides in the documentation ;) thanks!

**Comment by mickaelandrieu** [comment]
PR rebased (cs fixes)

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
LGTM @Quetzacoalt91 ?

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
You already had my blessing. :)

**Comment by PierreRambaud** [comment]
Thanks @mickaelandrieu

**Pull request merged**
