### PR TITLE
Remove lazy load for logo when Friendly URL active

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fixed at https://github.com/PrestaShop/PrestaShop/pull/26658 for P.S 1.7.8.1, but come back in P.S 1.7.8.5 in another template file.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/26666
| Related PRs       | If theme, autoupgrade or other module change is needed, provide a link to related PRs here.
| How to test?      | Follow ticket instructions
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Comment by leemyongpakvn** [comment]
It is a FO issue.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Please open an issue or ping @PrestaShop/qa-functional on your initial issue :)

**Comment by leemyongpakvn** [comment]
I sent @[PrestaShop/teams/qa-functional](https://github.com/orgs/PrestaShop/teams/qa-functional) at the bottom of https://github.com/PrestaShop/PrestaShop/pull/26658 but it looks like teams/qa-functional does not exist. What can I do now?

**Comment by matks** [comment]
@leemyongpakvn it looks like only maintainers can use ping on github 😅 

I did it https://github.com/PrestaShop/PrestaShop/issues/26666#issuecomment-1125811706

**Comment by leemyongpakvn** [comment]
@matks Thanks. By the way, the original issue was https://github.com/PrestaShop/PrestaShop/pull/26658.
It fixed https://github.com/PrestaShop/PrestaShop/issues/26666, and my commits as well as PR were added to the bottom of  #26658 automatically.

**Comment by leemyongpakvn** [comment]
For your information, it is a regression in template code in both PS 1.7.8.5 and PS 8.0.0 version, but with one more new problem: the product cover disappears in FireFox browser **and** PS 8.0.0 (there is no problem in Chrome browser **or** PS 1.7.8.5).
loading_lazy_make_image_disappear_in_Firefox

**Comment by leemyongpakvn** [comment]
@matks Sorry, it is not a regression: PR #26658 is for Shop logo, this PR is for Product covers. So I will close this wrong PR and open new issue for Product cover disappears in PS 8.0.0 and FireFox browser.

**Pull request closed without merging**
