### PR TITLE
Drop unused fields from ps_product_lang

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fields social_sharing_title and social_sharing_description are never been used. 
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3092
| How to test?  | Upgrade Prestashop and check if they still exist

### CODE REVIEW

**Review by aleeks — CHANGES_REQUESTED** [review]
Hello @fatmaBouchekoua 
Have you tested this ?
`Can't DROP 'social_sharing_title'; check that column/key exists`

Maybe you have to create a php script or use a if exists like `DROP TABLE IF EXISTS `PREFIX_help_access`;` but I can't find this for an alter table :-1:

**Comment by fatmaBouchekoua** [comment]
You are all right. We have to check if they exist before.

Thanks !

**Comment by aleeks** [comment]
I didn't found how we can do it with mysql only

```sql
IF(EXISTS (SELECT * FROM information_schema.COLUMNS WHERE TABLE_NAME = 'ps_product_lang' AND COLUMN_NAME = 'social_sharing_title')) 
BEGIN
     ALTER TABLE 'ps_product_lang' DROP COLUMN 'social_sharing_title'
END
```

but it doesn't work.. so need php script maybe

**Review by aleeks — APPROVED** [review]

**Comment by maximebiloe** [comment]
Thank you @fatmaBouchekoua & @aleeks

**Pull request merged**
