### PR TITLE
Sass fix

### PR DESCRIPTION
**Pull request by teototaro**
Fix for default position of homeslider navigation arrows

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Sorry can you please explain what this does fix ?

I believe this is cascading from https://github.com/PrestaShop/PrestaShop/blob/1.6/js/jquery/plugins/bxslider/jquery.bxslider.css#L88
https://github.com/PrestaShop/PrestaShop/blob/1.6/js/jquery/plugins/bxslider/jquery.bxslider.css#L71

Regards

**Comment by teototaro** [comment]
If you compile the original sass file the navigation arrows appears as showed in FIG.1.
The FIG.2 is the correct view instead.

FIG.1
schermata 2015-01-13 alle 13 01 51

FIG.2
schermata 2015-01-13 alle 13 02 01

**Comment by gRoussac** [comment]
Hi,

Sorry I could not reproduce that. css is ok on my test on a current git version.

Regards

**Comment by teototaro** [comment]
Yes, the compiled css is ok originally, but, if you re-compile the sass files online now in the release, you can see the bug.

**Comment by gRoussac** [comment]
Sorry I could not reproduce that. css is ok on my test on a current git version.

Regards

**Comment by teototaro** [comment]
Follow these steps:
1. download the sass folder online now (https://github.com/PrestaShop/PrestaShop/tree/1.6/themes/default-bootstrap/sass)
2. re-compile the files with Scout or similar

**Comment by gRoussac** [comment]
Follow these steps !

- clone the git repo
- delete the css and recompile it with compass


Regards

**Comment by jeromenadaud** [comment]
Hi @teototaro any news about the solution from @gRoussac ? It's working for you ?

**Pull request closed without merging**
