### PR TITLE
[-] CORE: Update wording tab.xml

### PR DESCRIPTION
**Pull request by Nobodaddy**
How come I thought that from time to time someone would synchronize the translations with Crowdin? I should have known better. :D
Have a look into the other file changes, too.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi,
thanks for contribution @Nobodaddy.

Let's take time to review it :)

Mickaël

**Comment by AlexEven** [comment]
Hello @Nobodaddy, and thanks for this!

We do it from time to time, when someone like you reminds us it should be done ^^
I've checked the file and if I compare with what we have on Crowdin, it gives me this:
https://github.com/PrestaShop/PrestaShop/pull/5133/files

Which has some more modifications from your version.
What do you think?

**Comment by Nobodaddy** [comment]
Hello Alex,

there seems to be another problem with this file - the English version contains more items than the German. Some items are still missing.
And please check the other files I changed, too.

**Comment by AlexEven** [comment]
Hello! 

Indeed, 1.7 (branch develop) has a new reorganized menu with updated tabs:

menu_17_de

The thing is, @Shudrum has been working on a way to make it easier to translate these new tabs. But it's not available yet. 
Let's say by the end of the week we should have an updated file in German with all the tabs we need in 1.7 (which would be quite an improvement from the situation right now). 
New tabs will be in English at first then you'll be able to translate it.

Now, what you first sent me and the file I provided are still valid for the 1.6 version, so if you tell me what I sent is correct, I'll merge to the 1.6 branch instead. What do you think?
Then we'll deal with 1.7 when we're ready.

What are the other files you are referring too? Is this regarding German translations or English suggestions?

Best,

**Comment by Nobodaddy** [comment]
Well, I'm a bit puzzled, Alex, because my other 5 file changes of xml files (without pullrequest) disappeared without a trace.

**Comment by AlexEven** [comment]
That would explain why I couldn't find any other xml files :)
Do you still have it locally? Can you try to make a new pull request?

**Comment by Nobodaddy** [comment]
Done!

**Comment by xBorderie** [comment]
So, we merged most of your more recent PRs, @Nobodaddy. Should we then merge this one too, or close it because the other ones fix it already?
Thank you!

**Comment by Nobodaddy** [comment]
Hope you will do, because this one's responsible that you always have to update the German translations after installing the PrestaShop upgrade, in order to harmonize the translations. I made this changes to prevent it in future.

**Comment by xBorderie** [comment]
Alright then.
Why the recent "commit merge"?

**Comment by AlexEven** [comment]
OK to merge, at least regarding the wording part. 
Not sure what you want to do about the commit merge!

**Comment by xBorderie** [comment]
Sadly, it cannot be merged right now, as the changes now conflict with the current codebase :/
@Nobodaddy, could you update your PR?

**Comment by maximebiloe** [comment]
Hello @Nobodaddy,

The XML files will be removed in this PR https://github.com/PrestaShop/PrestaShop/pull/7363 and translations will be editable on Crowdin.
So, I close this PR.

Regards

**Pull request closed without merging**
