### PR TITLE
Fix the error of product price must be set

### LINKED ISSUE #9830: [BOOM-4169] CLONE - "Error: Product price must be set"
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-4169).

- _**Reporter:**_ salma.moakhar
- _**Created at:**_ Fri, 27 Oct 2017 10:04:50 +0200

<p>If a product is priced to 0€ (this happens), when transforming an order from the backoffice in order to add/substract quantities, a warning arises:<br/>
"Error: Product price must be set" (txt_add_product_no_product_price)</p>

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When you create an order with the price of the product = 0 and you try to change the quantity, an error message appears "**Error: the price of the product must be set**".
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8761 and Fixes #9830
| How to test?  | BO > create a new product (**P**) with **price = 0**, FO > order product **P**, BO > the order details page, try to change the quantity of the product and check if the error message "**Error: The price of the product must be set**" is not displayed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8712)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[js/admin/orders.js, line 671 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8712#-L40zSbpJHqmiovngJpZ:-L40zSbpJHqmiovngJp_:brz26pr) ([raw file](https://github.com/prestashop/prestashop/blob/484803508f10b99d8cfe871ca4515d7968cc6bd6/js/admin/orders.js#L671)):*
> ```JavaScript
> 		e.preventDefault();
> 		var $productLineRow = $(this).closest('tr.product-line-row');
> ```

I suggest, as you started, creating all needed variables. Not only `$productLineRow` but also `$editProductQuantity`, `$editProductPrice`, `$totalProduct`, etc...
This way, you will separate selectors assignations and business logic. Logic will be easier to read and maintain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8712)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
See comment above

**Comment by Azouz-Jribi** [comment]
Hi @LittleBigDev 
Can you check it ?

Thanks :)

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8712#-:-L4BTRLSXf5dirdH6xs6:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by matks** [comment]
@marionf if this bug is still happening in 1.7, we should be able to fix it thanks to this PR

**Comment by khouloudbelguith** [comment]
@matks, @marionf => issue reported here: https://github.com/PrestaShop/PrestaShop/issues/9830

Thanks!

**Comment by Progi1984** [comment]
New PR on develop branch : #16392

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/16392 was merged 🎉 thanks @Azouz-Jribi

**Pull request closed without merging**
