### PR TITLE
Rename variable $producPropertiesCache (fix typo)

### PR DESCRIPTION
**Pull request by anegoda1995**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | just rename variable $producPropertiesCache => $productPropertiesCache (fix typo)
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2670
| How to test?  | no need for testing

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9098)

### CODE REVIEW

**Comment by anegoda1995** [comment]
Help me plz. Does it right that I create new branch commit there changes and merge it with develop?

**Comment by PierreRambaud** [comment]
Yep you created a branch with a commit, and it point on the `develop` branch :) And Nice catch 👍

**Review by PierreRambaud — APPROVED** [review]

**Comment by anegoda1995** [comment]
@PierreRambaud thank you :)

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
No need for a QA review, merging directly. :)

**Pull request merged**
