### PR TITLE
Correct usage of fixtures on behat tests for taxes

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | replace the usage of initial database fixtures by behat fixtures for tests on taxes
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | run behat ^^

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13772)

### CODE REVIEW

**Comment by matks** [comment]
I think it's 👍 
Have you considered using a [background](http://docs.behat.org/en/v2.5/guides/1.gherkin.html#backgrounds) ?

**Comment by tomlev** [comment]
indeed we should prepare background usage. but not in the current scope ;)
here I just wanted to properly use fixtures to avoid using magic IDs

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Behat tests run successfully by Travis => QA ✅

**Comment by matks** [comment]
Thank you @tomlev

**Pull request merged**
