### PR TITLE
Add low_stock_threshold to fixtures

### LINKED ISSUE #33490: Fixtures do not contain low_stock_threshold
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Default demo data doesn't contain low_stock_threshold, which results in this value being NULL in the database, while in fact, it should be 0, like it is for all new products.

### Expected behavior

Fixtures must be changed. PR created.

### Steps to reproduce

1. Install Prestashop, 
2. open phpmyadmin, 
3. find ps_product
4. check that values in low_stock_threshold are zeroes, instead NULL for demo products.

### PrestaShop version(s) where the bug happened

8.1.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Default demo data doesn't contain low_stock_threshold, which results in this value being NULL in the database, while in fact, it should be 0, like it is for all new products.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install Prestashop, open phpmyadmin, find ps_product and check that values in low_stock_threshold are zeroes, instead NULL for demo products.
| Fixed ticket?     | Fixes #33490
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]
Regarding the issue, I think you should target develop and not 8.1.x, WDYT ?

**Comment by Hlavtox** [comment]
@mflasquin I think if it's not a BC break, we can target 8.1 no?

**Comment by mflasquin** [comment]
8.1.x is a patch branch :

image

https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/supported-branches/

So regarding this page, you PR should target develop if I'm not mistaken

**Comment by kpodemski** [comment]
@mflasquin this is outdated, we are more flexible regarding patch branches, updates guidelines will be available on the project's website

**Comment by kpodemski** [comment]
@mflasquin more details: https://github.com/PrestaShop/docs/pull/1682

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
Without PR, the low_stock_threshold are NULL, see the attached screenshot below:

image

With your PR, the low_stock_threshold are zeroes :heavy_check_mark: 

image

LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by Hlavtox** [comment]
Thank you Hiba! :-)

**Pull request merged**
