### PR TITLE
Disable override button in performance page

### LINKED ISSUE #14596: Disable override button in performance page is not working
**Describe the bug**
The button to disable overrides is not working properly.

**To Reproduce**
1. Install a fresh PrestaShop
2. Add an override, for example for classes/CMS.php, override the __construct() function and add an echo 'hello'; followed by a die();
3. Delete the class_index in /var/cache/prod/class_index.php
4. Put yes on the disable overrides in the parameters in the back office
5. Go to any CMS page and modify it, the override is executed.
6. Even if i delete all the cache afterward it is still executed

I hope this is enough to reproduce the bug.

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 5.6

---

In the new version of the upgrade module, we should check if overrides are well disabled (see #14781)
We should fix this issue before working on the upgrade module

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Since PrestaShop 1.7.3.0 Disable override button don't generate new index classes
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/14596
| How to test?      | Create Override and check if is ok when you enable or disable override ( see below )
| Possible impacts? | This may impact the people who decorate this adapter

How to test : 
Create a new file Carrier.php 
inside : 

```
<?php
class Carrier extends CarrierCore
{


    /**
     * CarrierCore constructor.
     *
     * @param int|null $id Carrier ID
     * @param int|null $id_lang Language ID
     */
    public function __construct($id = null, $id_lang = null)
    {
        parent::__construct($id, $id_lang);

        die('Test if it\'s work');
    }
}
```

Put the file into override directory.

Remove the cache.

Go to admin carrier and try to edit a carrier see the error.

Go to performance and disable override 

Go to admin carrier  and try to edit a carrier no error

**:notebook: BC Breaks**
* The class `DebugModeConfiguration ` has one new parameter : 
  * `PrestaShop\PrestaShop\Adapter\Cache\Clearer\ClassIndexCacheClearer`  $classIndexCacheClearer

This PR, replace https://github.com/PrestaShop/PrestaShop/pull/26070 after a merge commit.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26070)

### CODE REVIEW

**Comment by ghost** [comment]
Sorry @matthieu-rolland && @PierreRambaud this PR replace : https://github.com/PrestaShop/PrestaShop/pull/26070 after a merge commit.

It's the same code.

**Review by matthieu-rolland — APPROVED** [review]
no problem @okom3pom , LGTM 👍

**Review by PierreRambaud — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @PrestaShop/prestashop-core-developers : Could you do the QA on this one ? It's a bit too technical for us :)

Thanks !

**Comment by ghost** [comment]
How to test : 
Create a new file Carrier.php 
inside : 

```
<?php
class Carrier extends CarrierCore
{


    /**
     * CarrierCore constructor.
     *
     * @param int|null $id Carrier ID
     * @param int|null $id_lang Language ID
     */
    public function __construct($id = null, $id_lang = null)
    {
        parent::__construct($id, $id_lang);

        die('Test if it\'s work');
    }
}
```

Put the file into override directory.

Remove the cache.

Go to admin carrier and try to edit a carrier see the error.

Go to performance and disable override 

Go to admin carrier  and try to edit a carrier no error

**Comment by PierreRambaud** [comment]
Thank you @okom3pom

**Pull request merged**
