### PR TITLE
Add translation domains to International menu's controllers

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Adding translation domains + renaming some variables. |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | na. |
| How to test? | See domains files. |

### CODE REVIEW

**Comment by maximebiloe** [comment]
domains

**Comment by aleeks** [comment]
@maximebiloe  Woooooooooooh you like happy  !

**Comment by aleeks** [comment]
Big thank you !!!!! :smiley:

**Comment by AlexEven** [comment]
:grimacing:

**Pull request merged**
