### PR TITLE
Add password reset url in mail for employee

### PR DESCRIPTION
**Pull request by antho-girard**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This PR adds password reset link in mail for employee |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1185 |
| How to test? | Try to reset your employee password. You'll receive the email with a link. Click the link and reset your password. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by antho-girard** [comment]
Hi,

I have some questions:
1/ Can you confirm the wording for html & txt mail please ?

2/ Once you reset your password, then you receive another mail with just your employee mail address. Is it the correct behaviour when employees reset their password?
Because the content of the mail includes links to Order History, Account and so on... (as if it was a customer).

Thanks !

**Comment by mickaelandrieu** [comment]
Hi Anthony,

I don't know. Let's wait for a PM :)

Mickaël

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by vincentbz** [comment]
I check for the wording right now

**Pull request merged**
