### PR TITLE
Access denied admin tabs

### LINKED ISSUE #15048: AdminTabs controller can not be accessed - Menu BO Page
**Describe the bug**
`AdminTabs` admin controller doesn't appear in any menu. If you try to access directly by URL it returns an `Acces denied` error.

This functionality is not in any other controller.

**To Reproduce**
1. Open any AdminController
2. Change URL to `controller=AdminTabs`
3. Bypass token warning

**Additional information**
PrestaShop version: 1.7.6.0

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Access denied when acess localhost/myshop/admin123/index.php?controller=AdminTabs&toke=xxx with SuperAdmin And AdminTabs Tab don't exists<br>This pull request is will continue to my old pull request because it's become unknown repository: #17501<br> Update process here: #19660
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket ?    | Fixes #15048
| How to test ? | 1. Open any AdminController<br>2. Change URL to `controller=AdminTabs`<br>3. Bypass token warning

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17501)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Because of the upgrade process, you need to update the 1.7.8.0.sql file to insert missing authorization data. Could you please update your pull request? :)

**Comment by HamzaElghanoui** [comment]
> Because of the upgrade process, you need to update the 1.7.8.0.sql file to insert missing authorization data. Could you please update your pull request? :)

Hi @PierreRambaud already update in another pull request that's approved https://github.com/PrestaShop/PrestaShop/pull/19660
what's do you think.

**Comment by PierreRambaud** [comment]
@HamzaElghanoui I sure they were connected but didn't remember the pull request :sweat_smile:

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @HamzaElghanoui !!

**Comment by Progi1984** [comment]
Thanks @HamzaElghanoui

**Pull request merged**
