### PR TITLE
[-] TR : typos fixed

### PR DESCRIPTION
**Pull request by grezlikowski**

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi @grezlikowski!

Thank you for your contribution, can you please follow the guidelines and rename you commits?

[How to write a commit message](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)

**Comment by grezlikowski** [comment]
It's done. Thank you.

czw., 4.02.2016 o 09:25 użytkownik Julien Martin <notifications@github.com>
napisał:

> Hi @grezlikowski <https://github.com/grezlikowski>!
>
> Thank you for your contribution, can you please follow the guidelines and
> rename you commits?
>
> How to write a commit message
> <http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PrestaShop/PrestaShop/pull/4873#issuecomment-179706300>
> .
>
-- 

Łukasz Gręźlikowski

**Comment by mickaelandrieu** [comment]
Hi,

@grezlikowski you have only changed the pull request name, not the commit name.

This is [how you can do](https://help.github.com/articles/changing-a-commit-message/), theses messages help us to release faster and make meaningful changelog between versions :)

Mickaël

**Comment by grezlikowski** [comment]
Sorry, I don't know how to do this. I will remember this with future requests.

**Comment by mickaelandrieu** [comment]
Hi,

@grezlikowski merged (https://github.com/PrestaShop/PrestaShop/commit/b4038496073d6738e9dca8298df8d705820946db) thanks for contribution.

Regards,

**Pull request closed without merging**
