### PR TITLE
Added the actionPresentProductListing hook

### LINKED ISSUE #19640: Overriding/extending ProductLazyArray
Hello,

I have a question regarding the ProductLazyArray class (namespace PrestaShop\PrestaShop\Adapter\Presenter\Product).

I would like to change the rounding for the $presAbsoluteReduction from 2 decimals to 0 in the 'addPriceInformation' method. This is a very small change but I do not want to add this adjustment in the core files. So I'm looking for a way to override or extend this functionality.

What is the best way to do this?
Thanks in advance.

### PR DESCRIPTION
**Pull request by stijnvergote**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added a new hook in the 'ProductListingPresenter' to be able to change the data in the ProductListingLazyArray that's created. There's already a hook present in the 'ProductPresenter' class and I believe this is a good addition as well.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19640.
| How to test?  | Create a module where this hook is registered. Here properties can be changed/added to the product. A custom module is attached in the description.<br>[vt_customoverrides.zip](https://github.com/PrestaShop/PrestaShop/files/4784887/vt_customoverrides.zip)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19647)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Well it makes sense 👏 😄

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by PululuK — DISMISSED** [review]

**Comment by sarahdib** [comment]
Hello @stijnvergote 

Thanks to provide us the module in order to test this pr.

**Comment by stijnvergote** [comment]
Hi @sarahdib,

How do you want me to provide the module?

**Comment by stijnvergote** [comment]
Do you want me to add the custom module in a new commit?

**Comment by SD1982** [comment]
Hi @stijnvergote you can provide us the module by adding the .zip file to the description of this PR .
Can you please also check if it's possible to resolve the conflicting files ?

**Comment by stijnvergote** [comment]
Hello @SD1982,

I fixed the conflicted files in a new commit, and added my custom module to the description of this pull request.

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by SD1982** [comment]
HI @stijnvergote thank you for resolving the conflicts and for providing the module!
Sorry to bother you again but i  have a little trouble visualizing what I am supposed to see / test with your PR could you provide us with a small test scenario?

**Comment by stijnvergote** [comment]
Hi, @SD1982,

For the website I'm working on, the discount percentages are by default shown with two decimals after the ','. So for example 17,39%. This is defined in the ProductLazyArray class: https://i.imgur.com/TVSmHkD.png.

In my application, I want the discount percentages to be presented with no decimals (17%): https://i.imgur.com/OaFj11x.png.

For this I make the following adjustment in my module: https://i.imgur.com/UstG7c5.png.

**Comment by stijnvergote** [comment]
@everyone can this be merged please?

**Comment by SimonGrn** [comment]
Hello @stijnvergote ,
sadly we're a small QA team and we have a lot of PRs to test. Currently our efforts are more focused on the 1.7.7.x branch since beta is ending soon.
Don't worry, your PR will be tested as soon as we can.

Thanks for your patience !

**Review by PierreRambaud — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM Thanks @stijnvergote !!

**Comment by PierreRambaud** [comment]
Thanks @stijnvergote

**Comment by stijnvergote** [comment]
Thanks for the merge guys! 👍

**Pull request merged**
