### PR TITLE
1.7.7.x

### PR DESCRIPTION
**Pull request by kalukramer**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.7.0
| Description?  | Add in fronte office product Start and end on specif price, in Europe is mandatory, is a Crime if dont have the start of promotion and ending. , , specific price/theme classic, etc. 
| Type?         |  improvement / new feature 
| Category?     | FO / BO
| BC breaks?    |  no
| Deprecations? |  no
| Fixed ticket? | Fixes #{issue number here}.
| How to test?  | Please indicate how to best verify that this PR is correct.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22384)

### CODE REVIEW

**Comment by Arman-Hosseini** [comment]
Hello @kalukramer .
Maybe you need to open a issue?

**Comment by kalukramer** [comment]
> Hello @kalukramer .
> Maybe you need to open a issue?

I have corrected

> Hello @kalukramer .
> Maybe you need to open a issue?

This isn't an issue.  From the version 1.4 don't have this Improvement, in Europe have a law for promotions, when you do a promotion, the product must have the start and ending date of promotion. In portugal the if you don't have this info, is a crime and culd cost 3000€

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Hello,

PR template is incomplete, also I don't see anything related to your description inside it.

What do you want to do there ? Merge 1.7.7.x into develop ?

**Comment by PierreRambaud** [comment]
Sorry @kalukramer this PR does not include any contribution from your account. A merge from 1.7.7.x to develop should be done manually in order to fix the existing conflicts.
I'm closing it as it can't be accepted as-is.

Kind regards

**Comment by kalukramer** [comment]
> Sorry @kalukramer this PR does not include any contribution from your account. A merge from 1.7.7.x to develop should be done manually in order to fix the existing conflicts.
> I'm closing it as it can't be accepted as-is.
> 
> Kind regards

Thank's for you help....

OK. I have resolved the problem by adding a code on "yoursite/themes/yourtheme/template/catalog/product.tpl"
after the line: " {include file='catalog/_partials/product-prices.tpl'}"

Insert this:

{if isset($product->specificPrice.to) && ($product->specificPrice.to|date_format:'%d-%m-%Y' > $smarty.now|date_format:'%d-%m-%Y')}
                {l s='start promo: '}<span class="specific_price_to">{$product->specificPrice.from|date_format:'%d-%m-%Y'}</span> </p>
                {l s='end promo: '}<span class="specific_price_to">{$product->specificPrice.to|date_format:'%d-%m-%Y'}</span>

 {/if}

NOW, after create the promotion will show on product page (front) the sart and ending of promotion, in EU is mandatory this rule.

"my two cent's"

**Pull request closed without merging**
