### PR TITLE
Improve error stack trace if an exception is thrown during the product save process

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | If an exception is thrown during the product save process, under certain circumstances, you will get no error codes or stack trace, very hard to debug.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | Follow this issue #30610 to see that you get nothing in browser console, very annoying 😊
| Possible impacts? | ~

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
CI is red...  I re-run failed jobs since I don't think it is linked to your PR

**Comment by PrestaEdit** [comment]
Related : https://github.com/PrestaShop/PrestaShop/pull/30338/

**Review by nicosomb — APPROVED** [review]

**Review by 0x346e3730 — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]

**Comment by sallemiines** [comment]
Hello @marsaldev 
Thanks for th PR! 
 Unfortunately, the issue is still exist  as you can see in my attached screen record below:
 

https://user-images.githubusercontent.com/31663369/212080693-eff80707-4dbd-4bf0-9431-4532375d351f.mp4

Please check and feedback ! 

Thank you !

**Comment by marsaldev** [comment]
Hi @sallemiines, thanks for your time.
The scope of the PR is not to remove the error but to improve the stack trace for debugging. You need to check it in the browser console 😊 


https://user-images.githubusercontent.com/48283112/216004272-bc0b6bf7-f3e0-462d-83e0-7a6463b1524a.mov

**Comment by sallemiines** [comment]
Hello @marsaldev 

Thanx for your feedback ! 

Well I rechecked the PR ! LGTM QA :heavy_check_mark: the stack trace for debugging is improved
the stack trace for debugging  result Without PR 

image

the stack trace for debugging  result  With PR :ok: 
image

Thank you ! :rocket:

**Review by nicosomb — CHANGES_REQUESTED** [review]
Just before merging, I see that the target branch is develop and milestone is 8.1. Do we need to update this PR (to change the branch) before merging?

**Review by jolelievre — DISMISSED** [review]

**Review by jolelievre — COMMENTED** [review]
Hi @marsaldev,

as @nicosomb mentioned did you plan on modifying this for 8.1 on 9.0?

If it's 8.1 you should change the target branch, and also I'd suggest adding a condition to this feature. It should only return more advanced error details in dev mode only. The stack trace can sometimes contain some critical information that could be bad for security (just in case).

If it's for 9.0 I'm not sure it's relevant, as you said the v1 will still be used for at least a year... in 8.1 and lower only. In v9.0 the v2 will definitely replace the v1 and all the related code is gonna be cleaned/removed.

**Comment by kpodemski** [comment]
Closing this PR as it won't be relevant for PS9. Thanks anyway Marco!

**Pull request closed without merging**
