### PR TITLE
Fixed multiples issues on Cart and product pages

### PR DESCRIPTION
**Pull request by ishcherbakov**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | \- Cart page: Possibility to set item qty manually (via input field)<br/>\- Cart page: fix some CSS styles, improve layout <br/>\- Product page: fix "Out of stock" icon<br/>\- Social networks widget: open link in new page<br/>\- Catalog pages: Add bottom margin for left menu |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | No |
| Deprecations? | No |
| Fixed ticket? | \- http://forge.prestashop.com/browse/BOOM-663<br/>\- http://forge.prestashop.com/browse/BOOM-667<br/>\- http://forge.prestashop.com/browse/BOOM-365 |
| How to test? | \- Qty feature: set desired qty and press &lt;Enter&gt; or click elsewhere<br>\- Bugs: see forge tickets for description |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by vincentbz** [comment]
status : 'QA approved'
Thanks !

**Comment by vincentbz** [comment]
Hi Ivan,

Could you rebase your PR so that we can merge it ? thanks :)

**Comment by ishcherbakov** [comment]
@vincentbz Yep

**Comment by ishcherbakov** [comment]
Any chance to merge this PR ? :)

**Comment by mickaelandrieu** [comment]
yes ! thank you @ishcherbakov

**Pull request merged**
