### PR TITLE
Fix SmartyLazyLoader for multiple smarty instances

### PR DESCRIPTION
**Pull request by antoin-m**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | SmartyLazyLoader shouldn't be a singleton since we could use multiple smarty instances while answering to one request.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1870
| How to test?  |

Ping @julienbourdeau what do you think about it?

### CODE REVIEW

**Review by julienbourdeau — APPROVED** [review]
Great job!

**Comment by firstred** [comment]
> SmartyLazyLoader shouldn't be a singleton since we could use multiple smarty instances while answering to one request.

Why do we want multiple Smarty instance? Why not one instance of a template engine?

**Comment by firstred** [comment]
We are already seeing write errors, because Smarty depends on a randomizer which can't really promise a truly random string (lack of entropy). See: http://www.smarty.net/forums/viewtopic.php?p=78130

I'm afraid this might get worse with multiple Smarty instances.

**Comment by firstred** [comment]
I have even made a Gist for that btw: https://gist.github.com/firstred/23e05023d67630c90d294761efcaee44

Waiting a microsecond before trying again seems to solve the randomness problem.

**Comment by antoin-m** [comment]
@firstred We have always used multiple instances of smarty. For instance when we generate PDFs :
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/pdf/PDF.php#L62
As we do not want to pollute the front's context we are only registering some methods on this instance.

**Pull request merged**
