### PR TITLE
Restore install sprintf JS lib integrity

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | When we merged https://github.com/PrestaShop/PrestaShop/pull/29273, the file `install-dev/theme/js/sprintf.min.js` was modified by the license header updator. The behavior of the file was not modified BUT as the file changed, the integrity check now fails, causing an error when attempting to load it inside the Installer "Informations" step (see screenshot below). This PR restores the file content to its initial content https://raw.githubusercontent.com/PrestaShop/PrestaShop/1eacfed357af9c67e373e432182e4322c2298863/install-dev/theme/js/sprintf.min.js which restores the correct behavior.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29667
| Related PRs       | 
| How to test?      | Please use the steps indicated in https://github.com/PrestaShop/PrestaShop/issues/29667
| Possible impacts? | 

## Screenshot of the JavaScript error
Capture d’écran 2022-09-16 à 20 48 51

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @matks 

Sorry for messing with this file, I integrated it in the ignore list of the license command but I guess I forgot to restore it correctly.

Just a question, where does this integrity test happen? Is it specific to the install process? or to the password policy feature for security reasons?

**Comment by matks** [comment]
> Just a question, where does this integrity test happen? Is it specific to the install process? or to the password policy feature for security reasons?

I dont know yet, but I'll have the answer soon 😄

**Comment by matks** [comment]
> Just a question, where does this integrity test happen? Is it specific to the install process? or to the password policy feature for security reasons?

@jolelievre here is the answer

https://github.com/PrestaShop/PrestaShop/blob/develop/install-dev/theme/views/layout.php#L22

introduced by https://github.com/PrestaShop/PrestaShop/pull/28127

**Review by florine2623 — COMMENTED** [review]
Hello @matks ,

The automatic tests have been launched and are OK.

- Tooltip and password requirements are displayed.
- Error text message for password is displayed too.
- There are no more error in the console.

Screenshot 2022-09-19 at 12 01 19

Although, my login to BO page is broken:
Screenshot 2022-09-19 at 12 10 58

And after logging in, my dashboard page has an exception:
Screenshot 2022-09-19 at 12 11 24

Could you check please ? 
Thanks!

**Comment by matks** [comment]
@florine2623 I am sorry but can you try again ? 😅 

I checked my PR and my login page is OK. My PR contains only one modified file it is in the installer code area. Nothing related to back office was modified.

See my login page
Capture d’écran 2022-09-19 à 14 54 05

**Comment by kpodemski** [comment]
@florine2623, did you run `make assets`? it seems like assets are not available

**Review by florine2623 — APPROVED** [review]
Hello guys,

Sorry, I don't know what happened during my tests this morning ^^'

I've retested again. It looks great.
I checked the password part in install-dev. Tooltip and password requirements are OK.
BO /FO are looking great.

It is QA ✅

**Comment by matks** [comment]
> Hello guys,
> 
> Sorry, I don't know what happened during my tests this morning ^^'

No worries, we all make little mistakes 👍 😄 thanks for testing

**Pull request merged**
