### PR TITLE
Remove some modules when building docker for tests

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Remove some modules when building docker for tests
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | Should be tested with docker, When trying to build and up docker-composer or UI tests, these folders should be deleted
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24305)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by SD1982 — APPROVED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
## WAIT FOR 1774 RELEASE

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @boubkerbribri

**Comment by matks** [comment]
Hi @boubkerbribri can you explain what you did this? Is it a temporary workaround?

**Comment by matks** [comment]
Hi we are a bit unconfortable with this PR so I suggested to revert it https://github.com/PrestaShop/PrestaShop/pull/24429 (and find another solution for the root problem)

**Pull request merged**
