### PR TITLE
[*] TR : (Dutch) Translate supplier order states

### PR DESCRIPTION
**Pull request by firstred**
## Description

Dutch translation of supplier order states

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@AlexEven does it sound good to you ? :)

**Comment by AlexEven** [comment]
Sounds perfectly good to my ears, so familiar with Dutch. :sweat_smile:
Thank you @firstred !

**Comment by firstred** [comment]
Hallo @AlexEven, hoe gaat het ermee? :D

**Comment by maximebiloe** [comment]
Thank you!

**Pull request merged**
