### PR TITLE
IN: Migration from earlier version, zero before product EAN13 where deleted

### LINKED ISSUE #16284: Migration from earlier version (ps earlier than 1.6.0.11), zero before product EAN13 where deleted
**Describe the bug**
During Migration from earlier version than 1.6.0.9
When apply, autoupgrade, zeros before Ean13 disappear.
note that official ean13 from Usa seems to begin from 000 to 060 ( for instance : 018200110306 )

**To Reproduce**
1. Install a old prestashop (1.6.0.9 is used on the screens bellow the reproduce steps )
2. Fill EAN13 for a product and for a product Attribute starting with a 0 (018200110306)
3. Install autoupgrade module
4. lauch it and upgrade to latest prestashop version
5. Go agin to see the product admin page after the migration , the 0 has disapper and the field is incorrect.

**Screenshots**
Before update : 
before_update

Autoupgrade module :  Update parameters
update_to

After update :
after_update

**Additional information**
PHP version: Migration from earlier version than 1.6.0.11

### PR DESCRIPTION
**Pull request by 123monsite-regis**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Migration from earlier version, zero before product EAN13 where deleted
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |  Fixes #16284
| How to test?  | ugrade from a version before 1.6.0.11 having ean13 looking like 000001234

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7017)

### CODE REVIEW

**Comment by Progi1984** [comment]
Closed & Reopened for launching Travis CI

**Comment by Progi1984** [comment]
Hi @123monsite-regis, could you open an issue for explaining your problem ? Thank you for your contribution.

**Comment by 123monsite-regis** [comment]
hi @Progi1984 
i opened an issue about this.

Sorry for the delay of my answer.
regards

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Hello @123monsite-regis, thanks for your contribution, would you mind to rebase your pull request? Thanks

Reference : https://anavarre.net/how-to-rebase-a-github-pull-request/

**Comment by PierreRambaud** [comment]
Hi @123monsite-regis ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
