### PR TITLE
Fix fixtures not generating thumbnails

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixtures need to be the last step of the installation. It needs images types which are data created by the installation theme.
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Try an installation and be sure all thumbnails are created.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12155)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by rGaillard** [comment]
@PierreRambaud some pre-installed modules doesn't need fixtures anymore for their installation?

**Comment by PierreRambaud** [comment]
@rGaillard If modules need fixtures to be installed, we have a problem since we have an option to disable demo products :smile:

**Comment by rGaillard** [comment]
@PierreRambaud if i remember correctly, some modules are using the default fixtures for their own fixtures installation this is why we had put fixtures installation before few years ago (but i don't remember which ones). But if there is no demo products, the modules doesn't have fixtures ;)

**Comment by PierreRambaud** [comment]
If we find a module with errors, we will change the order again :wink:  Thanks for info :+1:

**Pull request merged**
