### PR TITLE
CO: dump file fails with access denied message

### PR DESCRIPTION
**Pull request by psandmore**
If the file exists 'rename' fails with access denied message, remove the file first.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.0.x
| Description?  | access denied happened on creating class_index.php
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Happened to me many times in W10, PHP5.4.

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7262)

### CODE REVIEW

**Comment by aleeks** [comment]
Hello @psandmore,
Can you explain more what do you want to do ?

**Comment by psandmore** [comment]
It happened to me many times that class_index.php file was not recreated after module installation or cache clear. I investigated and figured out that this happens because the file handle (especially on Windows machine) is not released after the file is deleted. It takes usually around 0.1 - 0.3 ms in Windows to release the file handle.
The code I wrote resolves the problem and my tests shows that class_index.php is recreated properly every time.

**Comment by antoin-m** [comment]
Hey @psandmore, I'm not a big fan of your solution.

Do you think something like that could work http://php.net/manual/en/function.rename.php#56576 ?

**Comment by psandmore** [comment]
That exactly the problem that I try to solve. You can see that after the code I added there is a "rename" called. But "rename" fails to do its work. You can read in the comments on php.net that this problem exists with rename. I tried different other solutions, but this is the only one that worked for me.
I think it will be good to create Tools::rename with my enhancement and use it also in other parts of the code where rename is needed. If somebody will find better solution only Tools::rename can be changed.

**Comment by MathiasReker** [comment]
What is status on this?

**Comment by PierreRambaud** [comment]
We are not supporting PHP5.4 anymore, plus as @psandmore said, I'm not a bif fan of his solution.
I close this issue. Feel free to reopen it if you think the problem still occurred.

Thanks again @Mreker for feedback, I really appreciate what you're doing :)

**Pull request closed without merging**
