### PR TITLE
Update CLDR to latest version 36 (2019-10-04)

### PR DESCRIPTION
**Pull request by ziegenberg**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Updates the CLDR files from the latest v36 release and also the associated licenses files
| Type?         | refacto 
| Category?     | LO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | Install the most used languages (at least 5 languages, French, English, etc (We don't have the exact list))

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16347)

### CODE REVIEW

**Comment by matks** [comment]
@ziegenberg this is a big PR 😄thanks !

@eternoendless I think we need your review on this

**Review by Marcella700 — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
This PR should be rebased and squashed to avoid merge commits.

**Comment by ziegenberg** [comment]
> This PR should be rebased and squashed to avoid merge commits.

will do.

**Comment by ziegenberg** [comment]
rebased and squashed ✔

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
