### PR TITLE
Removed unneeded css properties in email template - 

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | font-size:0px; or dupplicated padding values. <br><br>Should be updated **globally** in all email templates.<br>Thanks!
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Check email have no changes in render

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/17432)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShark Thank you for your contribution. I updated the PR with the contribution table. Could you notify us when you have updated all email templates ? Thanks. I put in WIP waiting for your notification.

**Comment by ghost** [comment]
I will work today with this

**Comment by Progi1984** [comment]
<3

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/pull/17462

**Pull request closed without merging**
