### PR TITLE
[-] FO : fixed bug parse xml error

### PR DESCRIPTION
**Pull request by Eolia**
[-] FO : fixed bug  Avoid to see your shop in the Pacific Ocean...

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Would you mind telling me if this is the bug you are refering to? 

http://forge.prestashop.com/browse/PSCSX-6754

Thank you.

Regards

**Comment by Eolia** [comment]
Yes, it seems to be the same problem.
Bad data are sent, so Google Maps set geolocation to (0,0)

**Comment by gRoussac** [comment]
:+1:

**Comment by Eolia** [comment]
See this ticket so: http://forge.prestashop.com/browse/PSCFV-4093

**Comment by tchauviere** [comment]
Hi @Eolia,

Thanks for your contribution, could you please amend your commit to follow this guide:
http://doc.prestashop.com/display/PS15/How+to+write+a+commit+message

Ans can you also witch it to 1.6.1.x branch ?

Thanks a lot !

Best regards,

**Comment by tchauviere** [comment]
Hi @Eolia,

I'm closing this PR since its on the wrong branch.

Best regards,

**Pull request closed without merging**
