### PR TITLE
Add docker compose

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
- [x] Wait for https://github.com/PrestaShop/docker-ci/pull/9 to be merged
- [x] Update Readme.md

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Let's add a docker-composer file in order to make PrestaShop deployment easier for newcomers.
| Type?         | new feature
| Category?     | IN
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | You must have docker and docker-compose installed on your server / computer. Get the PR and launch the following command:

### How to run the LAMP stack with PrestaShop in it:

```bash
docker-compose up
```
Then got to http://localhost:8001, that's all :)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/7721)

### CODE REVIEW

**Comment by eternoendless** [comment]
Why the WIP label? What is still to be done?

**Comment by Quetzacoalt91** [comment]
I need to add  some parameters regarding the installation

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/7721#-:-L-2IH_ZsYaU0NKxslFy:bnfp4nl)*

**Review by LittleBigDev — DISMISSED** [review]

**Review by mickaelandrieu — APPROVED** [review]

**Review by alegout — APPROVED** [review]
Thanks @Quetzacoalt91 👍

**Pull request merged**
