### PR TITLE
Remove archived modules from email themes

### LINKED ISSUE #27084: [BO] The ps_reminder module archived but still exists in email theme folder
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The [ps_reminder](https://github.com/PrestaShop/ps_reminder) module has been archived but its twig layouts still exists in email theme folders:

```
PrestaShop/mails/themes/classic/modules/ps_reminder
PrestaShop/mails/themes/modern/modules/ps_reminder
```
After a fresh install of PS, the `ps_reminder` folder will be created in modules folder by email theme generator.

### Expected behavior

If this module is no longer available and cannot be used by other modules, then its items should be removed.

**Folders that should be deleted:** 
[PrestaShop/mails/themes/classic/modules/ps_reminder](https://github.com/PrestaShop/PrestaShop/tree/develop/mails/themes/classic/modules/ps_reminder)
[PrestaShop/mails/themes/modern/modules/ps_reminder](https://github.com/PrestaShop/PrestaShop/tree/develop/mails/themes/modern/modules/ps_reminder)

**Files that should be reviewed:**
[PrestaShop/.gitignore](https://github.com/PrestaShop/PrestaShop/blob/develop/.gitignore)
[PrestaShop/tests/Integration/Core/MailTemplate/MailTemplateGeneratorTest.php](https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Integration/Core/MailTemplate/MailTemplateGeneratorTest.php)
[PrestaShop/tests/Unit/Core/MailTemplate/LayoutVariablesBuilderTest.php](https://github.com/PrestaShop/PrestaShop/blob/develop/tests/Unit/Core/MailTemplate/LayoutVariablesBuilderTest.php)

**Translation file that should be reviewed:**
[PrestaShop/translations/default/EmailsBody.xlf ](https://github.com/PrestaShop/PrestaShop/blob/develop/translations/default/EmailsBody.xlf)

**Translation file that should be deleted:**
[PrestaShop/translations/default/ModulesReminderAdmin.xlf](https://github.com/PrestaShop/PrestaShop/blob/develop/translations/default/ModulesReminderAdmin.xlf)

### Steps to reproduce

1. Go to BO > Design > Email Theme
2. Select a theme for preview
3. The `ps_reminder` exists in grid table

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

ps_reminder

### PR DESCRIPTION
**Pull request by micka-fdz**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove archived modules from `classic` and `modern` email themes.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Emails from these modules should no longer be generated.
| UI Tests          | -
| Fixed issue or discussion?     | Fixes #27084
| Related PRs       | -
| Sponsor company   | @Creabilis

### CODE REVIEW

**Comment by micka-fdz** [comment]
Hi @boubkerbribri @Progi1984, this PR is about your comments here: https://github.com/PrestaShop/PrestaShop/pull/27544

**Review by Progi1984 — APPROVED** [review]
Approved for UI Tests

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Comment by micka-fdz** [comment]
This PR seems ready to merge 🎉

**Review by boherm — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
QA ✅ 

No more emails for ps_reminder and followup

**Comment by kpodemski** [comment]
thanks @micka-fdz

**Pull request merged**
