### PR TITLE
FO: Fix total products label

### PR DESCRIPTION
**Pull request by Amazzing**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Develop
| Description?  | Total products label should include all products, not only products on current page
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Check any product listing page

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @Amazzing,
I suggest you to use the [contribution table you have removed](https://raw.githubusercontent.com/PrestaShop/PrestaShop/develop/.github/PULL_REQUEST_TEMPLATE.md).

Thank you :)

**Comment by Amazzing** [comment]
OK, first message is updated. Should I create another pull request? Or this one is enough?

**Comment by xBorderie** [comment]
The devteam will take care of it if needed :)
Thanks!

**Comment by maximebiloe** [comment]
Hello @Amazzing,

Thank you for your contribution.
This branch is only meant to received prioritized bugs, meaning with a forge ticket.
I invite you to report your fix on `develop` branch but, please, respect our [commits standards](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message).

Regards

**Pull request closed without merging**
