### PR TITLE
Remove another faulty e2e test from Travis

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Disable another Selenium Guest scenario as it fails randomly
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/14384
| How to test?  | Travis is green

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15161)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
no more scenario \o/

**Comment by matks** [comment]
> no more scenario \o/

plz hit the "approve" button

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
But if we don't have any more scenario, should be remove travis jobs?

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Just a question

**Comment by matks** [comment]
> Just a question

Yes and no 😐 

Yes:
- these builds are useless now
- the code is dead and would be better removed

No:
- we should replace the broken tests ASAP so the builds should be useful again soon
- if we keep the builds around, it will "remind" us not to forget about updating them

**Comment by PierreRambaud** [comment]
It currently add useless jobs, that are consuming resources.
It's like keeping a commented code to be sure we will not forget to updates it.

We will be able to retrieve travis configuration in the git history :wink:

**Comment by matks** [comment]
Removed Travis build too.

Will be reinserted when https://github.com/PrestaShop/PrestaShop/issues/14497 is implemented

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
OK I think Travis lost my build now

Travis 🙄 srsly ? You dont want to be disabled so badly, so you hide the build result ?

**Comment by matks** [comment]
It's done

**Pull request merged**
