### PR TITLE
Fix html encoded urls in symfony layout

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix html encoded urls in symfony layout, see https://github.com/PrestaShop/PrestaShop/issues/34332
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI and UI tests are green
| UI Tests          | Legacy: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6655446502 / Symfony: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6655448301
| Fixed issue or discussion?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/34332
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by tleon — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
Tested, some things are fixed, some still encoded. ;-)

In these files, the escaping should be also removed:
- `src/PrestaShopBundle/Resources/views/Admin/Component/Layout/mobile_quick_access.html.twig`
- `src/PrestaShopBundle/Resources/views/Admin/Component/Layout/quick_access.html.twig`
- `src/PrestaShopBundle/Resources/views/Admin/Component/Layout/shop_list.html.twig`

**Review by jolelievre — DISMISSED** [review]

**Comment by M0rgan01** [comment]
@Hlavtox @tleon @nicosomb @jolelievre I removed the missing ones

**Review by nicosomb — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @M0rgan01 ,

Works as expected.

Before :
Screenshot 2023-10-30 at 12 10 07

After :
Screenshot 2023-10-30 at 12 10 22

It is QA ✅

**Comment by mflasquin** [comment]
thanks @M0rgan01 😉

**Pull request merged**
