### PR TITLE
[-] BO : Order state is protected or not from deletion now depends on `ps_order_state`.`unremovable` field value.

### PR DESCRIPTION
**Pull request by mauglee**

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!
Since your three commits are on the same file and with the same title, could you [squash them into one commit](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request), please?

**Comment by mauglee** [comment]
I will try :) This happened because when commited from command line, backticked table name was cut off from message. So I commited again with invoking text editor.

**Comment by mauglee** [comment]
After „git rebase -i upstream/master“ I get a file with a lot of other commits. Should I simply save and exit, or should I find my commits and leave only them deleting all others? Sorry about a lot of questions, but I am doing all this at first time.

**Comment by xBorderie** [comment]
These lines should be the way to go in order to rebase your branch on top of PS's 'develop' branch:
```
git checkout your-branch
git rebase onto develop E --interactive
```
[This is a good tutorial](https://www.atlassian.com/git/tutorials/rewriting-history) about rewriting Git history.
Yes, Git can be tricky the first times :) I would advise you to dive into it, it's really worth it.

**Comment by mauglee** [comment]
`git rebase onto develop E --interactive` does not work. Now I have tried regarding this http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request
Maybe it's all ok now?

**Comment by xBorderie** [comment]
As you can see, your PR now contains 4 commits, when ideally it would contain only one.
That, and your latest commit doesn't use the PS naming convention :/

**Comment by mauglee** [comment]
Are my commits squashed now?

**Comment by xBorderie** [comment]
Looks like so, yes! As you can see in the "Commits" tab of this PR, only one commit is listed, with the correct name. Congratulations!

Maybe you can help me help others who have the same issue, then: what were the missing instructions to help you reach that commit nirvāṇa? How did you proceed in the end?

As for the PR itself, I'll let the developers review your proposal and give you their feedback.

**Comment by mauglee** [comment]
I was guided by this http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request
And this „choose squash...“ was not clear for me. So I founded this explanation https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by xBorderie** [comment]
Great job!

**Comment by aleeks** [comment]
Hello @mauglee 
It has been done here: https://github.com/PrestaShop/PrestaShop/pull/6430/files

Regards

**Pull request closed without merging**
