### PR TITLE
Accordion missed in Legal Compliance module for PS 1.7. on mobile devices

### PR DESCRIPTION
**Pull request by Ranamiu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Legal Compliance module's informations in footer doesn't display properly on mobile. The behavior should be the same as other footer category links.
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2738
| How to test?  | As on mobile devices, once installed Legal Compliance module for PS 1.7., please look at footer on a mobile device. This module would need an accordion menu as for the rest of footer links.

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @ranamiu,

I think you made a mistake with the GitHub interface. You're trying to merge `develop` into `1.7.1.x` and not your own branch into `develop`.
I close this PR, but feel free to open a new one.

Regards

**Comment by ranamiu** [comment]
Hi Maxime,
Sorry !
You mean I should create my own branch and merge into develop?
Thank you
ranamiu 

    Il Martedì 13 Giugno 2017 10:50, Maxime Biloé <notifications@github.com> ha scritto:
 

 Hello @ranamiu,I think you made a mistake with the GitHub interface. You're trying to merge develop into 1.7.1.x and not your own branch into develop.
I close this PR, but feel free to open a new one.Regards—

**Comment by maximebiloe** [comment]
Hello @Ranamiu,

Yes, you should fork the project, create your branch, commit your changes and open a PR.

Regards

**Comment by Ranamiu** [comment]
Hi maximebiloe, 

First of all, thank you for following this up.

I am afraid I got wrong about GitHub PR .. I misunderstood what a PR on GitHub should do ...

I am afraid I am not currently able to suggest a fix for this, I am not a developer.

Apologizes!

Please, either you or anyone, take this PR as an example in order to suggest a fix and create a new PR: https://github.com/PrestaShop/PrestaShop/pull/7999

We really need a fix for this, it is so ugly looking on a mobile at a PS 1.7 footer having Legal Compliance enabled

Thank you

**Comment by maximebiloe** [comment]
Hello @Ranamiu,

No problem.
I see that you already made a bug report. We'll take it into consideration, and you'll be notified when it will be resolved.

Regards

**Pull request closed without merging**
