### PR TITLE
Fix image size in summary not limited

### LINKED ISSUE #9923: [BOOM-3634] Image in summary not limited
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-3634).

- _**Reporter:**_ marion_francois
- _**Created at:**_ Thu, 10 Aug 2017 09:57:28 +0200

<p>In my product page, I put an image in the summary tab.<br/>
I set a size which is too big.<br/>
It's displayed wrongly on the product page FO, see image.<br/>
I think it should be limited.</p>
        
* How to reproduce the issue ?

N/A

### PR DESCRIPTION
**Pull request by YeLnatSs**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Adding class to manage image in summary
| Type?         | bug fix 
| Category?     | FO 
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #9923
| How to test?  | Add a image in summary on product page. On FO, go to the product to check image.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13387)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by matks** [comment]
Thank you @YeLnatSs

**Comment by matks** [comment]
Looks like PrettyCI report got lost 🤔

**Review by Quetzacoalt91 — APPROVED** [review]
Rebasing did the work.

Now ready to merge.

**Comment by Quetzacoalt91** [comment]
Thank you @YeLnatSs

**Pull request merged**
