### PR TITLE
Update webpack dependencies of classic theme

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Webpack had some updates needed
| Type?             |  improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Can be tested by a dev, it's all about building the classic/_dev folder
| Possible impacts? | Classic theme

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25936)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Sorry but I understand nothing in this PR. Looks good to my beginner JavaScript self XD but cant approve.

**Comment by NeOMakinG** [comment]
> Sorry but I understand nothing in this PR. Looks good to my beginner JavaScript self XD but cant approve.

All about dependency update and breaking changes fixes

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
I tested your PR, but I have errors, here is what I did:

- Checkout your branch
- `cd themes/classic/_dev`
-  `npm install`
- `npm run build`

I get errors, like this one:

`ERROR in ./js/theme.js Module build failed: Error: Cannot find module 'babel-core'`

**Comment by NeOMakinG** [comment]
> I tested your PR, but I have errors, here is what I did:
> 
> * Checkout your branch
> * `cd themes/classic/_dev`
> * `npm install`
> * `npm run build`
> 
> I get errors, like this one:
> 
> `ERROR in ./js/theme.js Module build failed: Error: Cannot find module 'babel-core'`

Probably an error from your environment, looks fine at home + the CI is green

**Comment by hibatallahAouadni** [comment]
Hello @NeOMakinG 

LGTM, following @matthieu-rolland steps I didn't reproduce any issue, see the attached screenshot below:

image

I tried to fix this issue #25980 (change some css) while executing this command under `admin-dev/themes/new-theme/`:
` npm i && npm run watch`
=> No error :tada: check the attached screen reocrd below:
https://www.awesomescreenshot.com/video/5412939?key=66ae5017a37d58ccf1371b2b23202763

QA :heavy_check_mark: 

Thanks!

**Pull request merged**
