### PR TITLE
Merge 1765 to 177

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Merge 1.7.6.5 into 1.7.7
| Type?         | improvement
| Category?     | ME
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | -
| How to test?  | -

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18836)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
PR opened 3 hours ago and Travis is still running 😮

**Comment by matks** [comment]
Thank you @sowbiba

**Comment by jolelievre** [comment]
@matks no actually some builds had failed (I think for timeout reasons) and I relaunched them 20minutes ago
It's looking good, only one missing

**Comment by jolelievre** [comment]
oh it was actually already over and merged ^^

**Pull request merged**
