### PR TITLE
Fix Very strict selector div.delivery-option

### LINKED ISSUE #16050: Very strict selector div.delivery-option
The selector ["div.delivery-option"](https://github.com/PrestaShop/PrestaShop/blob/33684a3828f66e3a0e91ed53a8239813dcef41dd/themes/_core/js/checkout-delivery.js#L40) has 2 deficiencies:
1. Limit only div elements
2. The selector should start with "js-" to differentiate it from the style.

Point 1 is easy, change `div.delivery-option` to `.delivery-option`.
Point 2 is backwards incompatible. I think we can leave this for another issue. 

**Describe the bug**
I want to allow in my theme that `.delivery-option` is not `div`.

**Additional information**
PrestaShop version: N/A
PHP version: N/A

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allows themes to use other elements besides div as delivery-option
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #16050 
| How to test?  | The behavior when changing the carrier is as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16052)

### CODE REVIEW

**Review by matthieu-rolland — CHANGES_REQUESTED** [review]
Hello, thank you for your contribution @davidglezz ! 

Your modification looks fine to me, could you please build the related assets (in a separate commit) ?
https://devdocs.prestashop.com/1.7/development/compile-assets/

**Comment by davidglezz** [comment]
Done!

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@matthieu-rolland It's waiting for your seal.

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by sarahdib** [comment]
Hello @davidglezz 

Thank you for your contribution.

Could you resolve the conflict before the test ?

Thank you

**Comment by davidglezz** [comment]
Updated! @sarahdib

**Comment by PierreRambaud** [comment]
@davideapvd Look like you failed your rebase and add many other commits :thinking:

**Review by PierreRambaud — APPROVED** [review]

**Comment by davidglezz** [comment]
@PierreRambaud It's OK now?
I have made merge to be able to generate the assets with the latest commits to develop.
Because the assets that I generated when I made the PR became obsolete.

**Comment by Progi1984** [comment]
@davidglezz Yes. It's ok, now. Your PR needs to pass the QA for validation before to be merged.

**Comment by Progi1984** [comment]
Thanks @davidglezz

**Pull request merged**
