### PR TITLE
Fix: Warning on the Cart Rules creation/editing page

### LINKED ISSUE #32654: Warning on the Cart Rules creation/editing page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When accessing the cart rule creation/modification page, the following warning appears:
```
Warning on line 81 in file XXX\classes\Smarty\SmartyLazyRegister.php
[2] end(): Argument #1 ($array) must be passed by reference, value given
```

I attach a video.

https://github.com/PrestaShop/PrestaShop/assets/2463965/cbabeec0-3161-44de-a580-59e845831d77

### Expected behavior

_No response_

### Steps to reproduce

1. In admin go to Catalog > Discounts
2. Click on **Add new cart rule**
3. The warning is displayed

### PrestaShop version(s) where the bug happened

8.0.4, 8.1.x

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | When you enter the create/edit cart rules page, a warning is displayed.
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #32654
| Sponsor company   | Codencode snc

### CODE REVIEW

**Comment by kpodemski** [comment]
@Codencode it looks good, but I'm pretty sure something must be wrong higher, somewhere in the controller, there should not be array passed to the view 🤔

**Comment by Codencode** [comment]
Hi @kpodemski,
what you say is true, indeed in the "renderForm" method of the AdminCartRulesController controller the variable 'title' is assigned an array.

```
        $this->context->smarty->assign(
            [
                'show_toolbar' => true,
                'toolbar_btn' => $this->toolbar_btn,
                'toolbar_scroll' => $this->toolbar_scroll,
                'title' => [$this->trans('Payment:', [], 'Admin.Catalog.Feature'), $this->trans('Cart Rules', [], 'Admin.Catalog.Feature')],
                'defaultDateFrom' => date('Y-m-d H:00:00'),
                'defaultDateTo' => date('Y-m-d H:00:00', strtotime('+1 month')),
                'customerFilter' => $customer_filter,
                'giftProductFilter' => $gift_product_filter,
                'gift_product_select' => $gift_product_select,
                'gift_product_attribute_select' => $gift_product_attribute_select,
                'reductionProductFilter' => $reduction_product_filter,
                'defaultCurrency' => Configuration::get('PS_CURRENCY_DEFAULT'),
                'id_lang_default' => Configuration::get('PS_LANG_DEFAULT'),
                'languages' => $languages,
                'currencies' => $currencies,
                'countries' => $countries,
                'carriers' => $carriers,
                'groups' => $groups,
                'shops' => $shops,
                'all_shops' => Shop::getCompleteListOfShopsID(),
                'cart_rules' => $cart_rules,
                'product_rule_groups' => $product_rule_groups,
                'product_rule_groups_counter' => count($product_rule_groups),
                'attribute_groups' => $attribute_groups,
                'currentIndex' => self::$currentIndex,
                'currentToken' => $this->token,
                'currentObject' => $current_object,
                'currentTab' => $this,
                'hasAttribute' => $product->hasAttributes(),
            ]
        );
```

I can change the modification, but I don't know if the problem occurs in other controllers.
The change I made to the tpl would also solve the problem in any other pages.
What do you think is best to do?
Thank you!

**Comment by boherm** [comment]
Hi @Codencode! Thanks for your contribution.

I agree with you guys, and I don't really understand why we have an array with "Payment" and "Cart rules" titles on it... 
It seems also that is the only place that we have this situation.

Maybe we can edit this title to one value instead of an array and run auto tests?

**Comment by Codencode** [comment]
> Hi @Codencode! Thanks for your contribution.
> 
> I agree with you guys, and I don't really understand why we have an array with "Payment" and "Cart rules" titles on it... It seems also that is the only place that we have this situation.
> 
> Maybe we can edit this title to one value instead of an array and run auto tests?

Hi @boherm,
so I proceed with the modification of the controller?
Ovviamente lascerei "Cart rules".

Thank you!

**Comment by boherm** [comment]
Hi @Codencode,
Yes, I think you can purpose this modification on your PR too. 
I don't really know why we have "Payment" notion into Cart rule title... 😅

**Comment by Codencode** [comment]
> Hi @Codencode, Yes, I think you can purpose this modification on your PR too. I don't really know why we have "Payment" notion into Cart rule title... 😅

Hi @boherm,
I made the change by directly updating the controller.

**Review by boherm — APPROVED** [review]
LGTM, thanks @Codencode!

**Review by FabienPapet — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Codencode, 
Some checks haven't completed yet so I remove the WFQA label fo now.

**Comment by Codencode** [comment]
> Some checks haven't completed yet so I remove the WFQA label fo now.

Hello @paulnoelcholot,
the problem is that they haven't been started at all, there must have been a problem with the "actions" and I don't have the permissions to do it and I don't even know how to do it.

Thank you.

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional I restarted CI, you can test the PR, I'm sure CI will be ok unless something really weird is going on with them :)

**Review by MhiriFaten — APPROVED** [review]
Hello @Codencode ,

I have checked your PR and the warning is no more displayed !
Automated tests are OK.

LGTM, so it is QA approved :heavy_check_mark: 

Thank you.

**Comment by nicosomb** [comment]
thank you @Codencode !

**Pull request merged**
