### PR TITLE
Update dependency of classic theme to fit with core version

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Since versioning of classic theme has started this is a dependency update of classic theme to fit with core version
| Type?             |  improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/lartist/ga.tests.ui.pr/actions/runs/4103963461
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

Not sure about the above table completion !!!!!!!

### CODE REVIEW

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/4074226639

**Review by nicosomb — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Comment by jolelievre** [comment]
Runnin auto tests rebased on 8.1.x
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4076026581

**Review by jolelievre — DISMISSED** [review]

**Comment by nicosomb** [comment]
@PrestaShop/qa-team do you need to review this PR?

**Comment by Hlavtox** [comment]
@lartist Rebase it onto 8.1.x and it will work, if you just change the branch, it will do crap like this

**Pull request closed without merging**
