### PR TITLE
Optimize `Product::hasCombinations`

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Optimize `Product::hasCombinations` performances issue.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | See description bellow
| Possible impacts? | N/A

## How tests

- Add product with combination
- Add product without combination

```php
<?php

require(dirname(__FILE__).'/config/config.inc.php');

$product = new Product(ID_PRODUCT_HERE);

if ($product->hasCombinations()) {
    echo "is product with combination";
} else {
    echo "is product without combination";
}
```

### CODE REVIEW

**Review by FabienPapet — APPROVED** [review]
LGTM !

**Review by PrestaEdit — APPROVED** [review]

**Review by zuk3975 — APPROVED** [review]
could still be optimized by only selecting first combination id instead of all. Either add some optional "limit" param to existing "getPProductAttributesIds" method, or just use a custom sql query here.
Anyway it still a little optimization already so I approve.

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by djoelleuch — COMMENTED** [review]
hello @PululuK , 

I'm testing your pr and I want to know where I would like to put the script exactly

I tried to create a new PHP file and add your script but it gave me the following result

image

Waiting for your feedback !
Thank you.

**Comment by PululuK** [comment]
hi @djoelleuch 

please make sure that you have 
```php
require(dirname(__FILE__).'/config/config.inc.php');
```

I just update the script in PR description

**Comment by Hlavtox** [comment]
Works correctly @PululuK! :-)

```
<?php

require_once "config/settings.inc.php";
require_once "config/config.inc.php";
require_once "init.php";

// Combinations - 1
// No combinations - 6

$product = new Product(1);

if ($product->hasCombinations()) {
    echo $product->id . " is product with combination</br>";
} else {
    echo $product->id . " is product without combination</br>";
}

$product = new Product(6);

if ($product->hasCombinations()) {
    echo $product->id . " is product with combination</br>";
} else {
    echo $product->id . " is product without combination</br>";
}
```

Before:
before

After:
after

**Comment by PululuK** [comment]
Thanks @Hlavtox  @djoelleuch

**Pull request merged**
