### PR TITLE
Remove use of deprecated method in customizations

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 9.0.x
| Description?      | There were some remaining usage of deprecated methods related to customization. See below.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Automatic test + see how I tested it. :-)
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/12373607299 ✅ 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### Description
Customization system was improved some time ago and now all the customization price impacts, that can be added by module, are included in product price. However, there were two places, where it still called the deprecated method `Product::addProductCustomizationPrice`, that don't do anything. On backoffice cart view and in email preview in BO.

So, I removed these calls and tested everything.

_Note - the removed line for delivery address was added by me in https://github.com/PrestaShop/PrestaShop/pull/36653, it was just a quick fix to an issue inside that method, which is no longer called now._

### My test
I made a cart and I added a different customization prices for both items.

fo
database

First change - I checked if backoffice display works the same. ✅

bo

Second change - I checked if email preview works the same. It uses the last order created as a test data. ✅

email preview

### CODE REVIEW

**Review by ShaiMagal — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

Do you have the module to make customization price different ?
I remember testing a PR with that module, but I can't find it anymore 😓 

Now, in my case, I just have this in my database :
Screenshot 2024-12-17 at 16 47 54

Thanks!

**Comment by Hlavtox** [comment]
@florine2623 I tested it by manually changing the price in the database. :-)

Open `Customizable Mug`, add it to cart with two different customizations. Then go to `ps_customization` table in phpmyadmin and change the value in `price` column.

395527393-cf51b983-5882-40b5-b90a-7d87aeba3deb

**Comment by florine2623** [comment]
I don't have the same columns in ps_customization :

Screenshot 2024-12-17 at 17 26 03

🤔

**Comment by Hlavtox** [comment]
SOOOORRY! @florine2623 it's `ps_customized_data`

**Review by florine2623 — APPROVED** [review]
Oh thanks alright 😁 

Tested with your configuration and modified the customized price in database.

The Cart and Order confirmation on FO are OK
Screenshot 2024-12-17 at 18 07 15

The order in BO is OK
Screenshot 2024-12-17 at 18 07 35

It is QA ✅

**Pull request merged**
