### PR TITLE
Removed double escape for Tree Node template

### LINKED ISSUE #27348: BO - An error is displayed in some legacy pages
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

An error is displayed in multistore page :
image

An error in these pages also:

- Add/Edit new attribute
- Add/Edit new carrier
- Add/Edit new country
- Add/Edit new tax rule
- Add/Edit new group customer
- Stores page
- Referrers page

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO > Shop parameters > General 
2. Enable multistore
3. Go to Advanced parameters > Click on multistore
5. Add/Edit new attribute
1. Add/Edit new carrier
2. Add/Edit new country
3. Add/Edit new tax rule
4. Add/Edit new group customer
5. Stores page
6. Referrers page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.3/7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removed double escape for Tree Node template
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27348
| How to test?      | Cf #27348

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27381)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by saulaski — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by marwachelly** [comment]
Hello,

It seems the issue is not fixed in all pages. For exemple in page multistore the error still exist. Could you please check? 
https://watch.screencastify.com/v/ggYMRGrT3PnppV42ZWG4

Many thanks,

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello,

It seems the issue is not fixed in all pages. For exemple in page multistore the error still exist. Could you please check?
https://watch.screencastify.com/v/ggYMRGrT3PnppV42ZWG4

Many thanks,

**Review by saulaski — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello,

The problem is fixed in multistore page. But still nt fixed in the stores page. Could you please check?
https://watch.screencastify.com/v/zh31aIJEcGjYpgHU9LIq

Thanks,

**Review by jolelievre — APPROVED** [review]
Thanks @Progi1984

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello @Progi1984,

When installing the shop I faced the following error 
image
Could you please check?

Many thanks,

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello @Progi1984,

When installing the shop I faced the following error 
image
Could you please check?

Many thanks,

**Comment by atomiix** [comment]
@Progi1984 can you rebase your PR on the 1.7.8.x branch? Since smarty 3.4.43 [has been merged](https://github.com/PrestaShop/PrestaShop/pull/27350) on the 1.7.8.x branch, the issue appears in 1.7.8.x too!

**Comment by Progi1984** [comment]
@marwachelly Have you cleaned your cache before the install ?

**Comment by marwachelly** [comment]
Hello,

Issue is fixed in the following pages :

1. Advanced parameters > Click on multistore
2. See error
3. Add/Edit new attribute
4. Add/Edit new carrier
5. Add/Edit new country
6. Add/Edit new tax rule
7. Add/Edit new group customer
8. Stores page
9. Referrers page

Thank you @Progi1984

**Review by marwachelly — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @marwachelly

**Pull request merged**
