### PR TITLE
Responsive showcase cards fixed

### LINKED ISSUE #13175: Showcase cards are not responsive
**Describe the bug**
When on small screen Showcase cards are not responsive. Maybe image should be hidden when on small screens.

**To Reproduce**
1. Access new Employees page or SEO & URLs page.

**Screenshots**
showcase_cards

**Additionnal information**
PrestaShop version: develop

PHP version: N/A

### PR DESCRIPTION
**Pull request by YeLnatSs**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fix for responsive showcase cards 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| Fixed ticket? | Fixes #13175 
| How to test?  | Go on traffic & SEO to see the element.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13533)

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by marionf** [comment]
@YeLnatSs Your PR is for 1.7.6 so it should be on 1.7.6.x branch instead of develop

**Comment by YeLnatSs** [comment]
Hi @marionf I add it for 1.7.6.x

Branch? | 1.7.6.x

**Comment by matks** [comment]
@YeLnatSs What you need to do is to choose `1.7.6.x` as target branch:
Capture d’écran 2019-04-23 à 17 30 17

Sorry I reviewed too fast

**Comment by YeLnatSs** [comment]
@marionf I change it to 1.7.6.x

**Pull request closed without merging**
