### PR TITLE
PPV2 catch ProductNotFound exception and flash error

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | https://github.com/PrestaShop/PrestaShop/issues/29914
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | https://github.com/PrestaShop/PrestaShop/issues/29914. Note - the behavior differs depending if multishop is on. If multishop is on and product does not exist in context shop, then you will get a warning that product is not associated to the shop, and you should see a popup modal to select another shop. If, however, there is single shop context OR product doesn't exist in any shop, then you will be redirected to product listing with a flash error saying product doesn't exist.
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/29914
| Related PRs       | 
| Sponsor company   | 

image
image

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
lgtm :+1:

**Review by kpodemski — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Comment by zuk3975** [comment]
@jolelievre @kpodemski @matthieu-rolland could you approve again after final commit?
I added a normal translation message as in other pages (and updated the screenshot in description)

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @zuk3975 ,

Link to automated tests : https://github.com/florine2623/testing_pr/actions/runs/4122563905

Tested with all types of product and with and without debug mode.

I do not have the error. Now, the error message is more explicit and is displayed on the list of products :
Screenshot 2023-02-08 at 17 45 51



It is QA ✅ !
Thanks 💪

**Comment by nicosomb** [comment]
Thank you @florine2623 and @zuk3975 !

**Pull request merged**
