### PR TITLE
Display the notification count on the proper tab

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When you add more tabs on the module section, the notification badge always goes on the last tab. We expect it to be on the "Notifications" tab instead. It also fixes a "height" issue on the concerned tab. Assets are not generated to avoid conflicts.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | Ask Alexis or myself a module adding tabs to the module page.

## Before

capture du 2018-04-26 17-18-47

## After

capture du 2018-04-26 17-19-06

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8995)

### CODE REVIEW

**Review by eternoendless — DISMISSED** [review]
Looks good to me

**Comment by marionf** [comment]
@Quetzacoalt91 Do you have a module to test it please ?

**Comment by Quetzacoalt91** [comment]
Sent by PM

**Comment by Quetzacoalt91** [comment]
Passed code & QA review, merging with assets generated.

**Pull request merged**
