### PR TITLE
Fix Attributes with comma not displayed in Stock management

### LINKED ISSUE #26429: Attributes with comma not displayed in Stock management
#### Describe the bug

If a product attribute contain a comma (,) the product is not displayed in stock management.
For example a shoe size 37,5 is not displayed, a 37 1/2 shoe size work perfectly.

#### Expected behavior

I want to see all my product attributes...

#### Steps to Reproduce

1. Go to 'Stock management'
2. Search a product which contain product attribute with comma, it will be not displayed...

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.4

### PR DESCRIPTION
**Pull request by alexandrebru83**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | If a product attribute contain a comma (,) the product is not displayed in stock management. For example a shoe size 37,5 is not displayed, a 37 1/2 shoe size work perfectly.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26429.
| How to test?      | Go to 'Stock management' -> Search a product which contain product attribute with comma, it will be not displayed...
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26447)

### CODE REVIEW

**Review by PululuK — APPROVED** [review]
I just wanted to specify that this PR is for the display of the names of the combinations to be consistent in BO,
ping @PrestaShop/product-team

## Product page (v1)

Capture d’écran 2021-10-27 à 18 09 31

## Product page (v2)

Capture d’écran 2021-10-27 à 18 16 06


## Stock page

Capture d’écran 2021-10-27 à 18 13 23

Thanks @alexandrebrubeyonds !

**Comment by MatShir** [comment]
Looks good ! Hope it will be reviewed and merge before the release of the next patch :)

**Review by kpodemski — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @alexandrebrubeyonds ,
Some checks were not successful, could you check ?

ping @PrestaShop/prestashop-maintainers what do you think ?
Thanks!

**Comment by PululuK** [comment]
> Hello @alexandrebrubeyonds , Some checks were not successful, could you check ?
> 
> ping @PrestaShop/prestashop-maintainers what do you think ? Thanks!

Hi @florine2623 

I just re-run the test, is its a addons issue not related to this PR.

**Comment by florine2623** [comment]
Thanks @PululuK !

Tested on my end, it is all good :
Screenshot 2021-10-28 at 17 57 41

Thanks for the PR @alexandrebrubeyonds !

**Comment by Progi1984** [comment]
Thanks @alexandrebrubeyonds & @florine2623

**Pull request merged**
