### PR TITLE
Change domain to fix translation issue

### LINKED ISSUE #30916: Translation string for "new" in BO not working
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

There are two separate strings for the string ‘New’:

1. Front office: ‘New’ (=Nouveau) in `Shop.Theme.Global`
2. Back office: ‘New’ (=Neuf) in `Admin.Global`

image

image

 
Both strings are translated differently in 8+, but they both appear as “nouveau”, no matter the context. The translations are correct on Crowdin, but the translated strings on the software are not working correctly.

This is not the case in 1.7. I have not tested the bug in other languages.

I'm editing the string to place it under the right translation domain `Admin.Global`, instead of `Shop.Theme.Global`

### Expected behavior

Strings are supposed to be translated like this:

1. Front office: "Nouveau"
2. Back office: "Neuf" 

### Steps to reproduce

1. Create a new product, and make it visible on your store
2. Check if the label "new"is translated properly ("nouveau" in FO, "neuf" in BO)

### PrestaShop version(s) where the bug happened

8.0.0, 8.0.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by atomiix**
Solve issue #30916 

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | check the issue description
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | check the issue description
| Fixed ticket?     | Fixes #30916
| Related PRs       | check the issue description
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by atomiix** [comment]
Same PR as #30917 but rebased and made on a fork

**Review by lartist — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello @atomiix ,

I have checked your PR and I checked if the label "new" is translated properly ("nouveau" in FO, "neuf" in BO) as is expected in the issue.

But I noticed that in FO it displays "neuf".

[Untitled_ Feb 2, 2023 12_40 PM.webm](https://user-images.githubusercontent.com/111756615/216315356-be049d68-c93a-4aa8-8de2-1e3cc997e6d0.webm)


Can you check it please ?

**Review by FabienPapet — APPROVED** [review]

**Comment by atomiix** [comment]
@MhiriFaten I think it's normal, translations need to be updated now.
I think you can simulate it by changing `Neuf` to `Nouveau` in `translations/fr-FR/ShopThemeCatalog.fr-FR.xlf` ligne 175:
```diff
<trans-unit id="03c2e7e41ffc181a4e84080b4710e81e" approved="yes">
    <source>New</source>
-   <target state="final">Neuf</target>
+   <target state="final">Nouveau</target>
    <note>Line: 489</note>
</trans-unit>
```

After cleaning your cache `rm -rf var/cache/*`, I think you'll be able to have `Nouveau` in the FO and `Neuf` in the BO.

**Review by MhiriFaten — APPROVED** [review]
Thank you  @atomiix, and automated tests are OK.
So it's QA approved :heavy_check_mark:

**Comment by kpodemski** [comment]
thanks @atomiix :)

**Comment by dominiqueblanc** [comment]
Hi everyone,

Sorry but the issue #30916  is not fixed... I think there is a misunderstood.

According to the reviewed changes on the file src/PrestaShopBundle/Form/Admin/Product/ProductOptions.php
https://github.com/PrestaShop/PrestaShop/pull/31148/files/7f108b3befd7096ce647c5726ba520215d50a96b
https://github.com/PrestaShop/PrestaShop/pull/31148#pullrequestreview-1280877413

It appears that 'new' (=Neuf)  has been moved from `Shop.Theme.Catalog` to `Admin.Global`.
Consequently, the option appeared correctly translated in the dropdown in BO and that's fine.

Now, how to make it appears in FO ?

If I go in BO select a product and precise its condition as 'new - never worn before' (=Neuf), 'Neuf' won't appear in FO, because it doesn't exist anymore in `Shop.Theme.Catalog` (vs. 'Used and 'Refurbished').

Could you please check the details and comments I left in #30916 to express this situation ?
Thank you in advance, I hope it helps.

Best regards.

**Pull request merged**
