### PR TITLE
Fix call in getProducts, wrong 5th argument

### LINKED ISSUE #13705: Cart > getSpecificPrice called with shop group id rather than customer group id
**Describe the bug**
In the cart, reduction is shown in amount instead of percentage.

Debugging, I suspect the bug is due to the line 585 in classes/Cart.php :
`SpecificPrice::getSpecificPrice( ... (6 parameters), $this->id_shop_group, ...)`
But looking at the definition of this method :
`public static function getSpecificPrice(... (6 parameters), $id_group, ...)`

In other words : the method is asking for a (customer) group id, and a shop_group id is given instead.

(Consequence : 
- no specific price is found
- so reduction_type is set to 0
- so, in the template, the test '== amount' is valuated as true
- so, the reduction is shown in amount
)

**Steps to Reproduce**
I didn't try to reduce the case to a reproductible one, but following steps should be sufficient :

1. start from a default mono-shop installation of Prestashop 1.6.1.24, with only one shop group whose id is 1
2. create a customer group TEST (whose id is > 1)
3. create a customer FOO, and put him in this group
4. for a product BAR, create a specific price (-10%) for this group
5. log in as FOO, add BAR in your cart
6. go to cart
7. expected : the reduction is shown in percentage (as in Prestashop 1.6.0.x)
8. observed : the reduction is shown in amount

This line has been introduced by the following commit :
https://github.com/PrestaShop/PrestaShop/commit/20b7c28f188560f2ccc243d77aae3b6ce339bd05 − Optimize Cart::getProducts performances & factorize some queries by @jocel1

**Additional infos**

- PrestaShop version: 1.7.6.0
- PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.1
| Description?      | Fixes #13705 : SpecificPrice::getSpecificPrice() called with id_shop_group rather than customer's id_default_group in Classes/Cart.php<br><br>When calling `SpecificPrice::getSpecificPrice([..])` in the Classes/Cart.php `getProducts([...])` function, 5th argument has to be the customer default group and not the shop group
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #13705
| How to test?      | By coding: create a cart, add a product with a specific price 
| Possible impacts? | The bug doesn't have an impact on the cart because specific prices are reloaded later, but it breaks the `Cart::getProducts()` function if called by itself.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26448)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Comment by ghost** [comment]
@atomiix Hi, what's to be done now ? Why were some tests cancelled ?

**Comment by atomiix** [comment]
@jonathan-tesial I have no idea 😅 I'll trigger the CI again!

**Comment by ghost** [comment]
@atomiix Making progress !

**Review by matthieu-rolland — COMMENTED** [review]
php jobs were canceled for some reason 🤔  I launched them again

it would be nice to have a behat test that makes sure such a bug won't happen again in the future wdyt ?

**Comment by ghost** [comment]
@matthieu-rolland that would be indeed pretty good.
4 more tests have been cancelled, can someone launch them again ?

**Comment by matks** [comment]
Well, I'll reset the tests once more 🤔  but if more tests get cancelled, is that an indicator that something faulty is happening in GitHub?

**Comment by matks** [comment]
What is happening with this PR 😆

**Comment by matks** [comment]
Close and reopen to restart again the CI. If broken again there is something VERY WRONG

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @jonathan-tesial 

I checket with @khouloudbelguith  this PR.
We tried to use this script : 
```
?php
require dirname(__FILE__).'/config/config.inc.php';
$cart = new Cart();
$cart->id = 15;
$cart->id_shop_group = 1;
$cart->id_shop = 1;
$cart->id_carrier = 2;
$cart->id_lang = 2;
$cart->id_address_delivery=5;
$cart->id_address_invoice=5;
$cart->id_currency=1;
$cart->id_customer=2;
$force_ids = true;
//this will force ObjectModel to use your ID
$cart->force_id = (bool) $force_ids;

$cart->add();
$cart->updateQty(1, 23,0,false,'up',0,null,true,false,true,false);

echo "Done, cart well updated";
?>
```
But we have this exception : 
image

We checked the database, it is well added in the `ps_cart` & `ps_cart_product` tables.
Could you please provide us the exact script that you used to add a cart with a product that contains a specific price?

Thanks!

**Comment by PierreRambaud** [comment]
Hi @jonathan-tesial ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
