### PR TITLE
Add new selector for quickview modal using Bootstrap 5 (Hummingbird)

### PR DESCRIPTION
**Pull request by tblivet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR adds a selector on the quickview modal to accommodate Hummingbird, which uses Bootstrap v5 and introduces new selectors for modal display.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |  ⬇️
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/9679998967 ✅ 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   | @PrestaShopCorp

- Install Hummingbird on a shop.
- Open a quickview modal for a product that has combinations.
- Use the developer inspector to inspect "XHR" in network section.
- Change the combination; a new request should appear.
- When inspecting this request, you should find `quickview = 1` (previously, `0` was returned before the PR).
image

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `category` should be one of these: `FO`, `BO`, `CO`, `IN`, `WS`, `TE`, `LO`, `ME` or `PM`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hello @tblivet!

This is your first pull request on [PrestaShop](https://github.com/PrestaShop/PrestaShop/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by nicosomb — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @tblivet ,

Thanks for the PR !

The bug mentioned in https://github.com/PrestaShop/productcomments/pull/212#pullrequestreview-2141822510 is indeed fixed !

I have the right behavior ^^

https://github.com/PrestaShop/PrestaShop/assets/16019289/2ac24bd9-3e3a-4241-b5a9-b3e63b1c207a

Thanks! It is QA ✅ !

**Comment by ps-jarvis** [comment]
QA approved, well done! Message to the maintainers: do not forget to milestone it before the merge.

**Review by boherm — APPROVED** [review]

**Pull request merged**
