### PR TITLE
[*]BO: Webpack normalization and remove the tests install from the npm install

### PR DESCRIPTION
**Pull request by Shudrum**
Now the npm install is optionnal until the need of running the tests.

### CODE REVIEW

**Comment by kpodemski** [comment]
@Shudrum ready for tests?

**Comment by Shudrum** [comment]
@kpodemski ready for merge :)

**Comment by kpodemski** [comment]
@Shudrum great :+1: 
cc: @julienbourdeau

**Comment by Shudrum** [comment]
Ahah, you really want it ^^

So I merge.

**Comment by Shudrum** [comment]
Do not hesitate to say if there is still problems.

I cannot test with windows.

**Comment by kpodemski** [comment]
Hi @Shudrum 

It seems that it is working but in back-office I'm still seeing this error:
`Uncaught ReferenceError: Globalize is not defined`

Newest Opera on Chromium

**Comment by Shudrum** [comment]
This bug is known, only on the Dashboard, will be fixed soon.

**Comment by kpodemski** [comment]
Ok, but overall entire installation process went very well, thank you Shudrum :) 

Windows users likes it! :D

**Comment by Shudrum** [comment]
You're welcome!

**Pull request merged**
