### PR TITLE
[-] CORE : Fix #PSCSX-4594 escape { } if purify for mail template

### PR DESCRIPTION
**Pull request by sfroment**
allow you to add char that want be escape in a href if you do a
purifyHTML

### CODE REVIEW

**Comment by vidhujha** [comment]
NOt solved

**Comment by vidhujha** [comment]
I changed the code of all three files problem still not solved

**Comment by vidhujha** [comment]
Hello sfroment42 .
 "to get your mail like before I can suggest you to go into preference->Add / Update a language it will redownload the mail.
If some mail remain with the %7B/%7D you'll need to fix them manually with the method I detail you in my previous comment."

I tried but not sucsess

**Comment by sfroment42** [comment]
Hello @vidhujha,

Since we've done a better fix https://github.com/PrestaShop/PrestaShop/commit/be4e349cffd3eb0b376d4cbe2e3e15449da87a23.
But I believe there is no bug anymore, cause if you try to install a store with the dev version https://github.com/PrestaShop/PrestaShop/archive/1.6.zip.
You won't get any issue with the email translation.

Best regards.

**Pull request merged**
