### PR TITLE
Type protected and private methods of legacy admin controllers

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Adds types to all protected and private functions of legacy admin controllers. I did not type few exceptions, mainly when the method inherited from AdminController and there was a conflict of ObjectModel vs it's child.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | 
| UI Tests          | https://github.com/Hlavtox/ga.tests.ui.pr/actions/runs/6985011209
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
This is a BC break indeed :D 

nice 👍

**Review by ShaiMagal — APPROVED** [review]

**Comment by Hlavtox** [comment]
@florine2623 @PrestaShop/qa-automation 

The test is failing, but I think because the element is under the scrollbar. :D The feature is working normally. :-)

When I try it
Snímek obrazovky 2023-11-27 115638

Auto test artifact
fail_test_1

**Comment by nesrineabdmouleh** [comment]
Hello @Hlavtox,
Yes the feature is working normally, the error is related to the selector of the error message => [PR](https://github.com/PrestaShop/PrestaShop/pull/34690) to fix

**Comment by Hlavtox** [comment]
So @florine2623 I think it's QA ✅? :-)

**Review by tleon — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Pull request merged**
