### PR TITLE
Fix resetting sort and items per page on list filters reset action

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Modified filters reset action. Now its resetting list columns filters and offset, leaving `items per page` and `sorting` unchanged.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #13799
| How to test?  | Should work with all new migrated lists (except Products list, because it's not using same grid system, the Products list should not be affected by these changes). For example go to `Improve > International > Taxes` list and filter it by any column. Change sorting of any field and/or Items per page. After all these actions, press reset filters. **Filter fields should be resetted to defaults**. The **sort and items per page should not be resetted**. (sort and items per page should stay the same as previously selected).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13840)

### CODE REVIEW

**Comment by zuk3975** [comment]
@matks reviewable

**Comment by matks** [comment]
@colinegin As discussed in standup, this is not a bugfix but rather a behavior decision. Are you OK with what has been done ?

**Comment by colinegin** [comment]
Yes this is perfect @matks !
We should not forget to implement this change in the product listing when we'll be working on it ;)
ping @MatShir and @marionf

**Comment by matks** [comment]
@zuk3975 I'm sorry I dont understand the logic behind this PR. Can you explain it ?

**Comment by zuk3975** [comment]
> @zuk3975 I'm sorry I dont understand the logic behind this PR. Can you explain it ?

@matks, there is an issue #13799. In list when resetting the filters after search action - user expects only to reset columns filters, but the `item per page` and `sorting` is also resetted. So this PR fixes that. After these changes, when you reset the filters - only columns filters are resetted, but sorting and limit (a.k.a items per page) are left as it was. 
So for example after I filtered some list by name, selected to sort by id in DESC order and Items per page to show 10 (instead of default ASC and 50)  and i press reset` only the filter by name will be resetted`, but sort will be left by Id DESC and Items per page will stay 10.

In code it's very simple - unsets the `filters` array inside `PrestaShop\PrestaShop\Core\Search\Filters` and resets the offset to 0 (so the page will always be 1 after reset) instead of removing whole filter row from database.

**Comment by matks** [comment]
OK I was not understanding https://github.com/PrestaShop/PrestaShop/pull/13840/files#diff-c597104c09266cd043c65d2dbb167d46R288 but now I get it's a refacto not related to the issue 😄

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @zuk3975

**Pull request merged**
