### PR TITLE
Update prestashop 1.7.8.x composer dependencies

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Update prestashop 1.7.8.x composer dependencies: ps_banner, ps_wirepayment
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Related PRs       | 
| How to test?      | These are patch updates and they are not supposed to break anything
| Possible impacts? |

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Wishlist was done there : https://github.com/PrestaShop/PrestaShop/pull/29227/files

**Review by atomiix — DISMISSED** [review]

**Review by marsaldev — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matks,

The module "blockwishlist" was updated in this PR https://github.com/PrestaShop/PrestaShop/pull/29227
We need to update this PR?

Thanks!

**Comment by matks** [comment]
@khouloudbelguith I modified the PR and rebased it. Now only 2 modules are updated.

**Review by FabienPapet — APPROVED** [review]

**Review by yanmakouf — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team

what should be the strategy for such PRs? It's only patch version update for the modules

are sanity tests enough? can we merge it?

**Review by khouloudbelguith — APPROVED** [review]
Hi @matks,

It is ok :heavy_check_mark: 
I launched automatic tests on the:

- BO > Module manager page => ok
- Campaign FO => OK
- Create order from BO => OK

I checked the module ps_banner v2.1.2
image
I checked the module ps_wirepayment v2.1.3
image

Thanks!

**Pull request merged**
