### PR TITLE
Remove deprecated in Core namespace

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Core namespace
| Type?             | refacto
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Relative to #26293 
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4513230413

## **:notebook: BC Breaks**
* Removed class : `PrestaShop\PrestaShop\Core\Domain\Customer\ValueObject\Email`
* Removed class : `PrestaShop\PrestaShop\Core\Product\ProductListingPresenter`
* Removed class : `PrestaShop\PrestaShop\Core\Product\ProductPresenter`
* Removed class : `PrestaShop\PrestaShop\Core\Search\SortOrderFactory`
* Removed class : `PrestaShop\PrestaShop\Core\Search\URLFragmentSerializer`
* Removed trait : `PrestaShop\PrestaShop\Core\Hook\HookDispatcherAwareTrait`

## Linked PR
* PrestaShop/ps_specials#10
* PrestaShop/ps_specials#11
* PrestaShop/ps_newproducts#19
* PrestaShop/ps_bestsellers#30
* PrestaShop/ps_categoryproducts#36
* PrestaShop/ps_crossselling#44
* PrestaShop/ps_viewedproduct#29
* PrestaShop/ps_newproducts#22
* PrestaShop/ps_bestsellers#32
* PrestaShop/ps_categoryproducts#38
* PrestaShop/ps_crossselling#45
* PrestaShop/ps_viewedproduct#31

### CODE REVIEW

**Comment by Progi1984** [comment]
Blocked by `ps_specials` : PrestaShop/ps_specials#10

**Comment by Progi1984** [comment]
Blocked by `ps_newproducts` : PrestaShop/ps_newproducts#19
Blocked by `ps_bestsellers` : PrestaShop/ps_bestsellers#30
Blocked by `ps_categoryproducts` : PrestaShop/ps_categoryproducts#36
Blocked by `ps_crossselling` : PrestaShop/ps_crossselling#44
Blocked by `ps_viewedproduct` : PrestaShop/ps_viewedproduct#29

**Comment by Progi1984** [comment]
# Releases of modules
Blocked by `ps_newproducts` : PrestaShop/ps_newproducts#22
Blocked by `ps_bestsellers` : PrestaShop/ps_bestsellers#32
Blocked by `ps_categoryproducts` : PrestaShop/ps_categoryproducts#38
Blocked by `ps_crossselling` : PrestaShop/ps_crossselling#45
Blocked by `ps_viewedproduct` : PrestaShop/ps_viewedproduct#31

**Comment by Hlavtox** [comment]
@Progi1984 I will do the sort orders here - https://github.com/PrestaShop/PrestaShop/pull/31074

**Comment by Progi1984** [comment]
@PrestaShop/committers /@PrestaShop/prestashop-maintainers Open to review

**Review by SharakPL — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you @Progi1984

**Pull request merged**
