### PR TITLE
Improve cache

### PR DESCRIPTION
**Pull request by jocel1**
- Use multiDelete to invalidate the cache in memcached
- Implement a lazy LRU to remove from the cache the less used objects
- Implement in memcached a mecanism which automatically detect when an object is too big
- Split the big "table => queries" cache into several caches
- properly delete all the entries from the "table => queries" from multitables queries 

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | improve cache efficiency
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | run test. Use memcached

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8409)

### CODE REVIEW

**Comment by tomlev** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[classes/cache/Cache.php, line 136 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwATenxX18v3Qku9xMc:-KwATenxX18v3Qku9xMd:bxq5ilh) ([raw file](https://github.com/prestashop/prestashop/blob/7fbb94a209d614eb6c0aa28728bce15dc30f44be/classes/cache/Cache.php#L136)):*
> ```PHP
>      * @param $array
>      */
>     protected function _deleteMulti($array)
> ```

typehint ?

---

*[classes/cache/Cache.php, line 177 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwATp4GA3wsNm5cOy5k:-KwATp4GA3wsNm5cOy5l:bxq5ilh) ([raw file](https://github.com/prestashop/prestashop/blob/7fbb94a209d614eb6c0aa28728bce15dc30f44be/classes/cache/Cache.php#L177)):*
> ```PHP
> 
>     /**
>      * @param $value
> ```

typehint ?

---

*[classes/cache/Cache.php, line 287 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwATxCPbqE-wWmA9hRE:-KwATxCPbqE-wWmA9hRF:bxq5ilh) ([raw file](https://github.com/prestashop/prestashop/blob/7fbb94a209d614eb6c0aa28728bce15dc30f44be/classes/cache/Cache.php#L287)):*
> ```PHP
>      * Increment the query counter for the given query
>      *
>      * @param $query
> ```

typehint ?

---

*[classes/cache/Cache.php, line 319 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwAhT5RAUB5X6CYpJoh:-KwAhT5RAUB5X6CYpJoi:b-jggwav) ([raw file](https://github.com/prestashop/prestashop/blob/7fbb94a209d614eb6c0aa28728bce15dc30f44be/classes/cache/Cache.php#L319)):*
> ```PHP
>         // Get all table from the query and save them in cache
>         if ($tables = $this->getTables($query)) {
>             foreach ($tables as $table) {
> ```

the foreach content could be moved into a separate method to decrease complexity of this one
manipulating arrays is always hard to understand, and should be restricted in very short-scoped methods

---

*[classes/cache/Cache.php, line 363 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwAhliNfd1oZR3b_htW:-KwAhliNfd1oZR3b_htX:b-3xv4bp) ([raw file](https://github.com/prestashop/prestashop/blob/7fbb94a209d614eb6c0aa28728bce15dc30f44be/classes/cache/Cache.php#L363)):*
> ```PHP
> 
>             if ($tables = $this->getTables($query)) {
>                 foreach ($tables as $table) {
> ```

same as above, could you move this foreach content into a separate method ? code would be easier to read ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8409)*

**Comment by Quetzacoalt91** [comment]
# Comparisons:

## Cart content

capture du 2017-10-11 15-46-14

## Case 1
> From: #1. Cart - No cache (develop)
200 GET http://localhost/PrestaShop/fr/panier
8 minutes ago
To: #1. Cart - With memcache (develop)
200 GET http://localhost/PrestaShop/fr/panier
5 minutes ago
 
capture du 2017-10-11 15-41-32

https://blackfire.io/profiles/compare/09746dcc-aba8-449e-985e-a36d998fbe12...69dc0078-b40d-41c2-81a8-5e4db161e0f4/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()

## Case 2
> From: #1. Cart - No cache
200 GET http://localhost/PrestaShop/fr/panier
8 minutes ago
To: #1. Cart - With memcached (Jocelyn PR)
200 GET http://localhost/PrestaShop/fr/panier
4 minutes ago

capture du 2017-10-11 15-37-07

https://blackfire.io/profiles/compare/09746dcc-aba8-449e-985e-a36d998fbe12...7d1b0a28-f252-4ab8-93af-164e9d4832a7/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()

## Case 3
> From: #1. Cart - With memcache (develop)
200 GET http://localhost/PrestaShop/fr/panier
6 minutes ago
To: #1. Cart - With memcached (Jocelyn PR)
200 GET http://localhost/PrestaShop/fr/panier
4 minutes ago

capture du 2017-10-11 15-38-02
https://blackfire.io/profiles/compare/69dc0078-b40d-41c2-81a8-5e4db161e0f4...7d1b0a28-f252-4ab8-93af-164e9d4832a7/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main()

:top:

**Comment by tomlev** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[classes/cache/Cache.php, line 319 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwAhT5RAUB5X6CYpJoh:-KwErQYpXaQBu7h5D8Oi:b-esssuw) ([raw file](https://github.com/prestashop/prestashop/blob/7fbb94a209d614eb6c0aa28728bce15dc30f44be/classes/cache/Cache.php#L319)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

the foreach content could be moved into a separate method to decrease complexity of this one
manipulating arrays is always hard to understand, and should be restricted in very short-scoped methods
</blockquote></details>

great, thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8409)*

**Review by tomlev — DISMISSED** [review]

**Review by tomlev — DISMISSED** [review]

**Comment by jocel1** [comment]
I need to add new tests on this one first, the implement was broken, but the issue was not caught by the current tests !

**Comment by jocel1** [comment]
The latest code version is really for review, it fixes a bunch of existing issues!

**Comment by xBorderie** [comment]
"Really" or "ready"? :)

**Comment by jocel1** [comment]
Really ready :D

**Comment by eternoendless** [comment]
Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[classes/cache/Cache.php, line 52 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp7gB2R5uBXjh2Qfc6:-Kwp7gB2R5uBXjh2Qfc7:bmzz189) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L52)):*
> ```PHP
> 
>     /**
>      * Max number of queries cached in memcached, for each SQL table
> ```

Missing type (`int`)

---

*[classes/cache/Cache.php, line 137 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp7ZD9tIHNOjnimqc6:-Kwp7ZD9tIHNOjnimqc7:bghazn3) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L137)):*
> ```PHP
>      * @param array $keyArray
>      */
>     protected function _deleteMulti($keyArray)
> ```

You sign this parameter using `array`

---

*[classes/cache/Cache.php, line 157 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp7ih2e78JmeHnJjDA:-Kwp7ih2e78JmeHnJjDB:b5mfgm6) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L157)):*
> ```PHP
> 
>     /**
>      * @return mixed
> ```

Wrong type (should be `int`) and missing method description

---

*[classes/cache/Cache.php, line 165 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp7vb7CxxiHucJPUtZ:-Kwp7vb7CxxiHucJPUt_:b-tc03lf) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L165)):*
> ```PHP
> 
>     /**
>      * @param mixed $maxCachedObjectsByTable
> ```

Wrong type (should be `int`), missing method description

---

*[classes/cache/Cache.php, line 194 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp8-7nIIrMitABrsq2:-Kwp8-7nIIrMitABrsq3:bxcy4v0) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L194)):*
> ```PHP
> 
>     /**
>      * @param bool $value
> ```

Missing method description

---

*[classes/cache/Cache.php, line 267 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp86Vgd7PI083iXIp8:-Kwp86VhL1YSl0bu0BY6:bkrwt5r) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L267)):*
> ```PHP
>      * @param array $keyArray
>      */
>     public function deleteMulti($keyArray)
> ```

You can sign this parameter using `array`

---

*[classes/cache/Cache.php, line 331 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp8GLcfKHIKWYndaQl:-Kwp8GLcfKHIKWYndaQm:b-r5vt1f) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L331)):*
> ```PHP
>      * @param array  $result
>      *
>      * @return void
> ```

You can skip this for void functions

---

*[classes/cache/Cache.php, line 420 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp8bpn77Iw6FLFyMKG:-Kwp8bpn77Iw6FLFyMKH:bqyq3oz) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L420)):*
> ```PHP
>             $otherTables = $tables;
>             unset($otherTables[array_search($table, $tables)]);
>             $this->sql_tables_cached[$table][$key] = array('count' => 1, 'otherTables' => $otherTables);
> ```

Please prefer one item per line when declaring associative arrays

---

*[classes/cache/Cache.php, line 476 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-Kwp9gYiPhdBvUcOgCm5:-Kwp9gYiPhdBvUcOgCm6:b-q1swmo) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/classes/cache/Cache.php#L476)):*
> ```PHP
> 
>             // sort the array with the query with the lowest count first
>             uasort($this->sql_tables_cached[$table], array($this, 'sortByCount'));
> ```

You could use an anonymous function here

---

*[tests/Unit/UnitTestCase.php, line 32 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwpEcWw9qvAwYydDvlW:-KwpEcWw9qvAwYydDvlX:b-sz815w) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/tests/Unit/UnitTestCase.php#L32)):*
> ```PHP
>     }
> 
> }
> ```

It doesn't look like this class is used anywhere

---

*[tests/Unit/classes/CacheCoreTest.php, line 201 at r4](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-KwpDo7s4f9z3dJKm5BY:-KwpDo7s4f9z3dJKm5BZ:b-kzj4m4) ([raw file](https://github.com/prestashop/prestashop/blob/825248a67408565ea537efe5d8795651c7d52373/tests/Unit/classes/CacheCoreTest.php#L201)):*
> ```PHP
>     }
> 
>     public function testCacheInvalidation()
> ```

Please describe your tests :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8409)*

**Comment by eternoendless** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8409)*

**Comment by eternoendless** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8409#-:-KwuVzl0g5GZvdeohbm5:bnfp4nl)*

**Review by eternoendless — DISMISSED** [review]
Thanks for the changes, looks good to me!

**Comment by eternoendless** [comment]
@jocel1 could you please rebase?

**Comment by jocel1** [comment]
done!

**Comment by eternoendless** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8409)*

**Comment by eternoendless** [comment]
Thank you @jocel1

**Review by eternoendless — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
We have approvals, we have QA approvals => LGTM

**Pull request merged**
