### PR TITLE
BO - Order Preview : Added email

### LINKED ISSUE #24482: BO - Orders list - Preview order - Invoice details is missing the address mail of the customer
#### Describe the bug

In the BO > Orders > Order list page, when we try to preview an order, the invoice details is missing the address mail of the customer
BO_order_preview_invoic details

In PS1774 we have
1774_preview_BO_order

#### Steps to Reproduce

1. Go to BO > Orders > Orders list page
2. Click on 'arrow_down' to preview any order
4. See error: the address mail is missing the invoice details

#### Additional information

* PrestaShop version: 1.7.8.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | BO - Order Preview : Added email
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24482
| How to test?      | Cf. #24482 (Specs by @MatShir)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24773)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by arouiadib — APPROVED** [review]

**Review by Julievrz — APPROVED** [review]
Wording ✅ Thanks!

**Comment by SD1982** [comment]
LGTM Thanks @Progi1984 !!

**Comment by Progi1984** [comment]
## WAITING FOR 1775 RELEASE

**Comment by Progi1984** [comment]
Thanks @SD1982

**Pull request merged**
