### PR TITLE
Fix bad display alert when changing product combination quantity

### LINKED ISSUE #32716: BO - A bad display of alert success update
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

when you edit a combination  , the green alert is bad displayed .

### Expected behavior

image

### Steps to reproduce

1. Go to Catalog > Products> create a product with combination 
2. Edit the first one > ex : change the quantity of combination > click on save > **SEE THE ALERT MESSAGE IS BAD DISPLAYED**

image

### PrestaShop version(s) where the bug happened

PS 8.1.x / PS 810-rc / develop

### PHP version(s) where the bug happened

8.1 

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by fatm-dev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  8.1.x
| Description?      | Added relative position to form so image will be displayed in correct spot.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #32716
| Fixed ticket?     | Fixes #32716

### CODE REVIEW

**Comment by kpodemski** [comment]
Hi @fatm-dev 

Thanks for the fix! It seems that SCSS linter isn't happy, more details:

```
scss/pages/product/product_page.scss
 2000:5  ✖  Expected "position" to come before "padding-top"  order/properties-order
```

**Comment by fatm-dev** [comment]
@kpodemski  Hello, I'm sorry for the troubles. But I'm trying to squash commits but it keeps rebasing and putting two lines of same position. I'm using PhpStorm. I don't know if there are some tips?

**Comment by boherm** [comment]
Hi @fatm-dev! Thanks for your PR.

You can do a interactive rebase like so: 
1. Make sure that your local `8.1.x` branch is up to date with the PrestaShop/PrestaShop `8.1.x` branch.
2. On your terminal: `git rebase -i 8.1.x`
3. Replace `pick` by `fixup` for your last two commits (that needed to be squashed).
4. Verify that your changes is ok, with `position: relative;` before `padding-top: 1rem;`.
5. You can do a: `git log` to view if git history of your branch are in a right way.
6. Then, if ok: `git push --force`

**Review by kpodemski — APPROVED** [review]

**Review by boherm — APPROVED** [review]
LGTM @fatm-dev! :)

**Review by MhiriFaten — APPROVED** [review]
Hello @fatm-dev ,

I have checked your PR and the issue is well fixed :rocket: 

[Untitled_ Jul 6, 2023 4_15 PM.webm](https://github.com/PrestaShop/PrestaShop/assets/111756615/817c777a-dc05-4155-a1cb-ac7e75a02bd7)

Automated tests are OK.

So it is QA approved :heavy_check_mark: 

Thank you :smile:

**Comment by boherm** [comment]
Thanks @fatm-dev!

**Pull request merged**
