### PR TITLE
Introduce new hooks for main wrapper

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add some useful hooks for FO modules
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Nothing special to do

Related StarterTheme PR https://github.com/PrestaShop/StarterTheme/pull/182

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello @prestamodule,

Unfortunately, as we should release the `1.7.1.0` before the end of the month (and it's pretty close), the QA process has already been started and we can't add anything to the package. We are focusing on bugfix.
So, I changed the destination branch to embed your hooks into `1.7.2`.

Regards

**Comment by prestamodule** [comment]
Hi @maximebiloe, can't this be integrated into 1.7.1.1 ? Some hooks have already been added to 1.7.0.x without waiting for 1.7.1.x to be released.

**Comment by maximebiloe** [comment]
We have communicated on our [release planning](http://build.prestashop.com/news/announcing-our-2017-release-schedule/), so you can now anticipate your requests.
It won't be integrated in a patch version, because it would mean that a module won't be compatible for the complete minor version.

Regards

**Comment by prestamodule** [comment]
@maximebiloe http://build.prestashop.com/ says on 17/03

> Do you feel more hooks are needed for the next minor version? Suggest some through a PR!

We are making the PR 3 working days later.
So, suggest for nothing ? @xBorderie

**Comment by xBorderie** [comment]
Indeed: the 1.7.1.0 hooks are pretty much locked -- hence [the article you are referring to](http://build.prestashop.com/news/new-updated-hooks-1-7-1-0/), which lists them all.
In that context, "the next minor version" meant 1.7.2.0 (at best). Sorry, I should have been more precise!

We published the [PrestaShop release calendar](http://build.prestashop.com/news/announcing-our-2017-release-schedule/) almost two months; that should allow you to plan your PR in an efficient way.

**Comment by prestamodule** [comment]
Hi Xavier,

This is Stephan. We're really sad to read (understand) this last sentence is talking about 1.7.2.0. So... ok, we'll delay our new projects based on this new hook.

As Maxime said I know you are focus on bugfix until this release. 
So please, let me to remind you that the displayNav was not added into the Classic theme (see my comment on http://build.prestashop.com/news/new-updated-hooks-1-7-1-0/).
As the majority of theme designers prefers "Classic" as base of work, I think this is really important that "Classic" 1.7.1.0 use exactly the same hooks than the "Starter" theme.

Could you please ask to your dev team to fix this for 1.7.1.0 ?

Many thanks

**Comment by kpodemski** [comment]
Waiting at least 3 months for 3 new hooks is... well, not good, there is no need to check these hooks by QA team, it is a simple addition.

For the differences between Classic and StarterTheme, unfortunately StarterTheme seems to be forgotten.

**Comment by hadjedjvincent** [comment]
@kpodemski This is because new hooks are considered as a feature... They could be included into patch release, many contributors projects are delayed because of missing hooks.
Less projects = less addons = less money for PrestaShop and contributors = less services for the merchant

We can't ask all merchant to edit their template files and add some lines, or do it ourself..

@xBorderie Version 1.7 is still fresh, if you want users to move/migrate, you should consider new hooks as patch, like it was the case for 1.6 some time ago.
I know that we do not agree on that, but really, you should have a move on this.

**Comment by kpodemski** [comment]
@hadjedjvincent i'm not against adding hooks in 1.7.x versions, i'm against "code freeze" rule which is not great in a situation like this one, only 3 new hooks, 3 lines of code, do we really need QA etc. etc?

**Comment by hadjedjvincent** [comment]
@kpodemski I agree, i was just explaining why hooks aren't added into patch releases ;-)

**Comment by prestamodule** [comment]
@kpodemski We are all ok for saying there nothing no complex test for a new hook, as there is no backward compatibility or something like that. Just test if the hook is working.

**Comment by xBorderie** [comment]
I appreciate the fact that you feel I have a say in this decision :)
But that is not the case. As far as I know, adding hooks can have real performance impact, and therefore adding new hooks must be carefully weighed.
Generally speaking, the team is dedicated to fixing final issues before the 1.7.1.0 release, and cannot dedicate time to improvement.

As for Classic vs. Starter, I'll push the issue again; thanks for the reminder!

**Comment by kpodemski** [comment]
bs

**Comment by aleeks** [comment]
Fully rebased from develop, need to test it & go to merge.
Thank you @prestamodule

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Tests pass, we can finally merge for 1.7.2.0.

Thanks guys.

**Comment by xBorderie** [comment]
Cool!

**Pull request merged**
