### PR TITLE
Disable sorting on customer discount vouchers

### PR DESCRIPTION
**Pull request by tegbessou**
Disable sorting on customer discount vouchers, by adding in all fields `sortable` to false in `CustomerDiscountGridDefinitionFactory`

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Disable sorting on customer discount vouchers, by adding in all fields `sortable` to false in `CustomerDiscountGridDefinitionFactory`
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes a part of #26149
| How to test?      | To test this, you have to go on Customers > Customers > View a customer and see you can't sort the `Vouchers` table
| Possible impacts? | No

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26241)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @tegbessou,

With this PR, the pagination of the block voucher and addresses are NOK as reported here: https://github.com/PrestaShop/PrestaShop/issues/25588.
In fact, this fix: https://github.com/PrestaShop/PrestaShop/pull/25822 will be ignored in this PR.
Block addresses
image
Block voucher 
image


Thanks!

**Comment by tegbessou** [comment]
Hello @khouloudbelguith,

I have rebased with develop branch, so fix #25822 is now present.
Can you test again, please?

**Review by PululuK — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
@tegbessou, yes it is good now.
It is missing one review to change the label for `Waiting QA` and re-check the PR again.

Thanks!

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @tegbessou,

It is ok :heavy_check_mark: 
The sort doesn't exist
image

I checked the pagination the voucher and the addresses block => ok

Thanks!

**Comment by Progi1984** [comment]
Thanks @tegbessou & @khouloudbelguith

**Pull request merged**
