### PR TITLE
Remove deprecated in Configuration

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated in Configuration
| Type?             | improvement 
| Category?         | CO
| BC breaks?        | yes. Like ps_banner that use it's as now (https://github.com/PrestaShop/ps_banner/pull/39)
| Deprecations?     | no
| Fixed ticket?     | Fixes #26293.
| How to test?      | Nothing to test.
| Possible impacts? | BC Break.

**:notebook: BC Breaks**
* Removed method : `Configuration::getInt()`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26306)

### CODE REVIEW

**Review by tegbessou — COMMENTED** [review]
Thank you for your PR!

I don't know if you see but this method is used in modules ps_banner. I don't know if you have to fix this or it's accepted?

`modules/ps_banner/ps_banner.php`

**Review by Progi1984 — COMMENTED** [review]
@PrestaEdit Could you document the BC Break, please ?

**Comment by PrestaEdit** [comment]
Hi @tegbessou, @Progi1984,

I have added a Pull Request to the ps_banner module and add it into the BC Break.

**Review by PierreRambaud — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]
Thank you, LGTM

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @PrestaEdit 

@PrestaShop/qa-functional Check in Core. One use is found in `ps_banner` but a PR is there : PrestaShop/ps_banner#39

**Pull request merged**
