### PR TITLE
Allow image for categories when no description

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Allow image for categories when no description
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1744
| How to test?  | Add a new category, add a picture, and see if you have the image on your front office

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by vincentbz** [comment]
image

Heho, i'm not a pig

**Comment by aleeks** [comment]
My key "n" isn't working anymore :smiling_imp:

**Comment by xBorderie** [comment]
Nice try :D 
capturepig

**Comment by xBorderie** [comment]
Nice try :D 
capturenkey

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by xBorderie** [comment]
Seems like it really does work: http://victor-rodenas.com/2017/04/12/error-en-la-imagen-de-la-categoria-cuando-no-existe-descripcion-en-prestashop-1-7-1-0 :)

**Pull request merged**
