### PR TITLE
Fix payment layout broken on small screens

### LINKED ISSUE #13061: The lines inside table > tbody payments in orders tab go out of their coantiner
**Describe the bug**
The lines inside table > tbody payments in orders tab go out of their coantiner

**To Reproduce**
1-Create one order
2-Go to this order
3-Adjust resolution to 1423px of width

**Screenshots**
bug prestashop

**Additionnal information**
PrestaShop version: 1.7.5.1
PHP version: 7.2.15-0ubuntu0.18.04.1

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Payment window had an overflow on small screens 
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13061.
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22100)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Comment by atomiix** [comment]
@NeOMakinG Don't you think we should wait for #22100 to be merged and then 1.7.7.x to develop instead of redoing the fix?

**Comment by NeOMakinG** [comment]
> @NeOMakinG Don't you think we should wait for #22100 to be merged and then 1.7.7.x to develop instead of redoing the fix?

Since it's not in the same file anymore (because we did split bundles), I was like "Let's add it on the new file too, so rebase errors are not coming up"

**Review by Progi1984 — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I found an issue when using a mobile.
image

Thanks!

**Comment by NeOMakinG** [comment]
Mehh

@PrestaShop/ux-team help! Should I add an overflow scroll on mobile ?

**Comment by prestascott** [comment]
@NeOMakinG Yes, we must add an horizontal scrollbar

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 
https://www.awesomescreenshot.com/video/1909645?key=7f85a5b26e288288cd933b461300c4eb

Mobile => ok
https://drive.google.com/file/d/1UUV1O3hd5CCUaO9V7SzOoxkDA9nV1at6/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @khouloudbelguith

**Pull request merged**
