### PR TITLE
Slow combination update due to delay before request

### LINKED ISSUE #12207: Changing combinations on product page on PS 1.7.5 - very slow compared to previous versions
Compared to PS 1.6 and first versions of PS 1.7, the new PS 1.7.5 loads combinations really slow (after fresh install and only default modules) 
PS 1.7.5 works really fast on every page, except this thing which is not actually a bug but needs a fix. 

Another thing:
I have 2 combinations: 'product size' and 'product colors'.  I recently installed a module from mypresta which adds product pictures to color combinations and after install those combinations (product colors) load almost instantly compared to 'product size' combinations. 
So after module install the color combinations load very fast compared to the size combinations which leads me to think that something can be done to load thinks quicker. 

1. Create at least two combinations
2. Add values to combinations
3. Go to product and assign the combinations, make sure you add several photos to each combination value. 
4. Go to frontend, product page, and play around with selecting combinations
5. You should notice that each combination selection loads pretty slow

Also, playing around with performance settings and cache doesn't seem to make a difference. 
I run a pretty capable server. 

new project

PrestaShop version: 1.7.5
PHP version: 7.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | The combination update takes some time since 175, this is because the update product delay has been modified 
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12207
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12337)

### CODE REVIEW

**Comment by jolelievre** [comment]
The delay between each product update has been modified since the 174 version
It is really easy to revert to the former value (250ms) however I guess there were reasons to change this behavior

Maybe when modifying the quantity value, maybe with keyboard changes only
If this is the reason I propose to make this delay dynamic:
Example:
- default: 250ms
- quantity update: 100ms
- keyboard update: 1500ms

@PierreRambaud since you are the last one to have modified this behavior I'd like your opinion please

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Totally agreed, we need to change what kind of change we are doing. I just remembered with your examples :smiley:

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Need to be updated before. We must check what kind of action is currently executed.

**Review by joaoafpedro — DISMISSED** [review]

**Comment by pdkey** [comment]
yes - great! we also notice the selection of variation is very long. Terrible for modern system. - Make Presta great again :)

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Looks like we need a rebase here @jolelievre

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by hostisoft** [comment]
Could you indicate at the end how this was solved, I see three files, but they do not correspond to the js of a default theme template?

**Pull request merged**
