### PR TITLE
[*] FO Dynamically get excluded_key in FrontController->canonicalRedirection()

### PR DESCRIPTION
**Pull request by ghost**
May be example will be easier to undersand: if you go to example.com/fr/content/category/1-hoooome, you are redirected to example.com/fr/content/category/1-home?id_cms_category=1, because id_cms_category is not in the excluded_key array. Better is it to fill this excluded_key array dynamically, especially as now there is also the possibility for module to define custom routes through hookModuleRoutes, which may contain any kind of parameters, that shouldn't appear again in canonical url. I'm quite sure of the idea, but quite unsure of the way I've done it... especially I do not knwo how it will behave with multishop feature on. Hope it can help!

### CODE REVIEW

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by zimmi1** [comment]
Hi. Still actual !
The problem mentionned in the example is still present. I made a (short) review now and tested it on 1.6.1.2 : the code proposal is still valid. Some changes needed for coding style, though...

**Comment by xBorderie** [comment]
Thank you for your feedback @zimmi1 !
Since your PR was made on branch `1.6`, there is no way we can easily merge it on branch `1.6.1.x` (the new default for PS 1.6 development) and keep your credit.
Would it be possible for you to update your code and make a new PR on the `1.6.1.x` branch?
Thank you!

**Comment by maximebiloe** [comment]
Hi @zimmi1,

As we told you we can't merge your PR on `1.6` branch, so I have to close it.
If you want, you can open a new one on the `develop` branch.
Thanks for your contribution.

Regards.

**Comment by gRoussac** [comment]
Cherry-pick ?

**Comment by zimmi1** [comment]
What does this mean ?

If it is copy paste, sure you can.

**Pull request closed without merging**
