### PR TITLE
Integrate forgotten password alerts

### PR DESCRIPTION
**Pull request by thierrymarianne**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Render error and success alerts 
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/STAB-57
| How to test?  | Submit an email address which doesn't exist or an email address which does.

forgotten-password
forgotten-password-error
forgotten-password-success
renew-password

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@thierrymarianne is there any interest of "Report on StarterTheme" label? I have the feeling that the label is removed almost of the time, wdyt ?

**Review by mickaelandrieu — APPROVED** [review]

**Comment by aleeks** [comment]
@mickaelandrieu  I don't think so!

**Comment by mickaelandrieu** [comment]
Why did you request and add the feature to @prestonBot then ? :p

**Comment by aleeks** [comment]
I don't know how alert are displayed on starterTheme, or if starterTheme have alert, but this label is to prevent some changement!

**Comment by thierrymarianne** [comment]
@mickaelandrieu This PR is about integrated alerts. 
As the starter theme provides with HTML pages without CSS, I would say this was a false positive.

**Comment by maximebiloe** [comment]
Thank you @thierrymarianne

**Pull request merged**
