### PR TITLE
add puppeteer in progress migration from selenium to puppeteer, pleas…

### PR DESCRIPTION
**Pull request by mbadrani**
…e consider only regular suit, the rest is in progress

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | This is on progress migration E2E tests from Selenium Mocha to Puppeteer Mocha. <br> Note: Puppeteer requires at least Node v7.6.0 or greater. If you want to try it, please use Regular test suit. 
| Type?         | refacto
| Category?     | TE
| BC breaks?    | Does it break backward compatibility? no
| Deprecations? | Does it deprecate an existing feature? no
| How to test?  | Refer to the readme.md and try launching regular suit (headless by default).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13362)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Can you please remove the `migration_puppeteer` directory and edit `tests/E2E` files instead, we're loosing all the history and are not able to review. 
Otherwise please do cleanup in your PR, in integrate Docker, nightly, and many other things you didn't change.

And not sure the `1.7.6.x` should be targeted.

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
Clean directory or edit `tests/E2E` instead

**Comment by ttoine** [comment]
Hello, why is this pull request in the "done" column in the kanban? It is not merged.....

**Comment by tomlev** [comment]
"requires at least Node v6.4.0, but some tests use async/await which is only supported in Node v7.6.0 or greater." So it requires 7.6+

**Pull request closed without merging**
