### PR TITLE
[*] Project : Fix Order slip calculation for refund with shipping costs.

### PR DESCRIPTION
**Pull request by xGouley**
Orders screen & PDF displays, as PSCSX-5494

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Please report on 'devlop' or '1.6.1.x' as you want.

Regards

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xBorderie** [comment]
Hey guys!
Xavier G. tells me that this PR was very important, but @jnadaud had not merged at the time, and has since fixed the Tax system here and there, putting this PR in limbo. Now that the `1.6` branch is not used anymore, it would need to be remade on `1.6.1.x` or even `develop`.
This might warrant to [reopen the Forge ticket](http://forge.prestashop.com/browse/PSCSX-5494), don't you think? @vincentbz and @djfm, your opinion?

**Comment by vincentbz** [comment]
Totally agree. This is an important fix, that has already been verified, we can integrate it in the 1.6.1.5 if possible

**Comment by xBorderie** [comment]
Well it needs to be ported to the `1.6.1.x` branch first, and since it's tax-related, I think @djfm might find this a bit more touchy to merge directly :)

**Comment by vincentbz** [comment]
Of course :)

**Comment by xBorderie** [comment]
I reopened the Forge ticket.

**Comment by xBorderie** [comment]
Still not ported to the 1.6.1.x branch, and therefore not yet in 1.6.1.5, as we wanted.
The ticket is inactive: http://forge.prestashop.com/browse/PSCSX-5494, people are waiting for our feedback.
@xGouley, @vincentbz , @djfm : any idea on how to best handle this?

**Comment by vTerenti** [comment]
Hello!

This PR has been automatically closed because the branch 1.6 does not exist anymore.

Best regards

**Pull request closed without merging**
