### PR TITLE
Enable modules to know the current checkout process step

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Enable modules to know the current checkout process step
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  | No QA necessary I think 🤔

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15176)

### CODE REVIEW

**Comment by matks** [comment]
Ping @v4lux

**Comment by matks** [comment]
Travis is not happy 🎶 restarting the build 🎵

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Travis why u no lov me ? 😢

**Comment by PierreRambaud** [comment]
One more review and merge.

**Comment by matks** [comment]
@Quetzacoalt91 would you like to review, it, sir ? 😄

**Comment by matks** [comment]
@Quetzacoalt91 🆙this is related to Modules development, I think you'll be interested 😉

**Comment by matks** [comment]
Closing and re-opening for travis reset

**Review by PierreRambaud — APPROVED** [review]

**Comment by matks** [comment]
Thanks for review

**Pull request merged**
