### PR TITLE
Replaces the new product flag in the product flags by new

### LINKED ISSUE #26640: [FO] Product flags regression in 1.7.8.x
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Changing label `New` to `New product` was a mistake - it covers too much.

obraz

### Expected behavior

It's obvious we're looking at a product. Isn't it?

### Steps to reproduce

1. Open homepage or category with new products available

### PrestaShop version(s) where the bug happened

1.7.8.0, 1.7.8.1

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by WebHelpersPau**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | /1.7.8.x
| Description?      | Replaces the new product flag in the product flags by new.
| Type?             |  improvement
| Category?         | FO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26640
| How to test?      | Watch product list and product detail controllers
| Possible impacts? | Nothing critical

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26672)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
thank you @WebHelpersPau for your PR 👍

**Comment by Julievrz** [comment]
Thank you, wording ✔️

**Comment by WebHelpersPau** [comment]
Thanks for the wording feedback

**Review by Progi1984 — DISMISSED** [review]

**Comment by HanaRebaiQA** [comment]
Hello,

Thanks for this PR. The issue is fixed.
I tested the behavior with several types of products (standard, pack, customized,..) in different pages in FO. Also, i verified with responsive mode and with multistore.
See screen-record below : 
https://watch.screencastify.com/v/6iO2gmLy1N6bIERNM7U6

LGTM, QA :heavy_check_mark: 

Thanks,

**Comment by Progi1984** [comment]
@WebHelpersPau Could you update the integration test before merging : 

https://github.com/PrestaShop/PrestaShop/runs/4314268811?check_suite_focus=true#step:14:16 ?

**Comment by WebHelpersPau** [comment]
@Progi1984 sorry I've missed it, it's on the go

**Comment by WebHelpersPau** [comment]
Shoud be ok from now on

**Comment by Progi1984** [comment]
@WebHelpersPau Could you rebase and remove your merge commit ?

**Comment by WebHelpersPau** [comment]
@Progi1984 it shoud be ok right now.

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@WebHelpersPau the merge commit is there did you rebase?

**Comment by WebHelpersPau** [comment]
@NeOMakinG I have just merged some changes from another branch of mines. It's rebased on the good one normally

**Comment by Progi1984** [comment]
@WebHelpersPau No you have always two merge commits :

image
image

**Comment by WebHelpersPau** [comment]
Didn't know how to make it easily, not an expert in GIT, new PR with same content sent https://github.com/PrestaShop/PrestaShop/pull/26798/files

**Pull request closed without merging**
