### PR TITLE
Performance is better when fetching all rows at once instead of itera…

### PR DESCRIPTION
**Pull request by studiokiwik**
A little performance improvement (like 0.5 - 1ms+ / page)

### CODE REVIEW

**Comment by inetbiz** [comment]
I did see a .5ms drop in my test

**Comment by jocel1** [comment]
I assume it's with caching enabled ? When fetching all the rows, it can benefits from the cache.

**Comment by inetbiz** [comment]
Caching is on for me. So is memcached and Opcache for PHP 5

**Comment by gskema** [comment]
+1 I did profiling on a shop recently, and this was exactly was I concluded too. I remember that there was another query that fetches by row, I think it was `Hooks::getAll` which fetches by row too.

My results were something like
1) Using rows: 30ms, 5mb RAM (peak usage)
2) Fetching all at once: 3ms, 5.75MB RAM

The RAM usage in the PR would actually be higher (+1.5MB) because we rewrite the whole row, and we should unset rewritten rows immediatelly to save memory (by using refs).

**Comment by studiokiwik** [comment]
@gskema  There is about 20 places in last presta where Db::nextRow is used, half of them in upgrade code. There are places where nextRow should stay, due to (possible) memory problems, like in PrestaShopBackup or CartRule, so I would say it should be made case by case

**Comment by studiokiwik** [comment]
@jocel1 Cache (at least file cache) do not change much

https://blackfire.io/profiles/compare/25997790-431f-4789-ba0e-46dba57c3b79/graph - without cache
https://blackfire.io/profiles/compare/1fa8ba8e-6cad-4ba2-87f2-4a8a88de3c43/graph - without cache

https://blackfire.io/profiles/compare/90e7a6d0-395d-4353-a5ed-3db60a4e73f6/graph - with cache
https://blackfire.io/profiles/compare/e777fef6-efa3-45ac-9013-c0c27d2a0802/graph - with cache

**Comment by gskema** [comment]
@studiokiwik File cache is the slowest of all. Probably slower than no cache :)

I'm not saying that we should replace all `nextRow`, but should definitely consider  replacing them in Configuration and Hook classes, which call these queries on every request. I use Xdebug profilre to test the execution times, using `nextRow` it was `30ms`, which `executeS` was `3ms`. The RAM usage went up by 0.75mb ursing refs. `-27ms` is huge gain cosidering the whole excution time was `230ms` (on my local enviroment). So basically its the age old question: sacrifice speed or sacrifice memory?

**Comment by inetbiz** [comment]
@gskema I would say keep memory low. I limit my client's memory consumption to 256M in cloudlinux. Combinations eat up a lot of memory when there are more than say three options. One customer had 6 combos and the page was trying to consume almost 700mb on that process. Insane. =)

**Comment by studiokiwik** [comment]
@gskema For Configuration memory usage is a bit greater for ExecuteS (209 KB → 578 KB for vanilla Prestashop - about 1 - 2 % in total for clean installation, less with fully configured shop with module), i think it will be even less for hooks and modules

**Comment by maximebiloe** [comment]
Hello,

Thanks for contributing.
The `1.6.1.x` branch is only meant for bugfixes. Could you please make your PR on `develop` branch ?

Best regards.

**Pull request closed without merging**
