### PR TITLE
Product edit modal shop selection

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When trying to edit a product while in All shops context or group shop context the use is invited to select a shop first (list adapted to the product's shops). Also, handle this selection when trying to access the edition page in an inappropriate context
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | CI tests green (plus campaign auto) no manual tests for now this is only a partial feature PR
| Possible impacts? | ~

### CODE REVIEW

**Comment by jolelievre** [comment]
Running auto campaigns https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/3769072872

**Review by matthieu-rolland — APPROVED** [review]
LGTM

**Comment by matthieu-rolland** [comment]
FYI a functional test if failing but I don't think it's related to your PR

**Review by nicosomb — APPROVED** [review]
For the part that I can review (the php one), it's ok for me.

**Pull request merged**
