### PR TITLE
Fix header on default pages on mobile

### LINKED ISSUE #27385: [BO] Bad display of header itmes in medium screen
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

- **768px < width < 1039px**
The header items (quick access, search box, shop name, notification icon) in legacy theme pages are misaligned vertically at medium screen width. => **`Regression on 1.7.8.0`**

image

- **1024px < width < 1039px**
The header title and the shop version are misaligned => **`reproduced on 1.7.7.8`**
The Order page is not full width => **`reproduced on 1.7.7.8`**

image

### Expected behavior
Header items center align vertically and header height as like as new theme.

Screenshot 2022-01-18 at 12-14-03 Dashboard • sidebar

### Steps to reproduce

Go to BO > Dashboard

### PrestaShop version(s) where the bug happened

1.7.8.0

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | The header on responsive wasn't that good, some fixes are needed such as padding, margins
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27385.
| How to test?      | See issue
| Possible impacts? | Default page header in BO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27615)

### CODE REVIEW

**Review by matks — DISMISSED** [review]
Re-running failed CI

**Comment by mparvazi** [comment]
Great!

I thought it should be fixed with more changes :smile: 

Just a suggestion:
Make employee's icon size as same as other icons in header.

default:
Screenshot from 2022-02-08 14-17-37

new-theme:
Screenshot from 2022-02-08 14-16-58

**Review by matks — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by HanaRebaiQA — CHANGES_REQUESTED** [review]
Hello @NeOMakinG 

I detected this issue which is already exists without PR but it's not present in PS1778. 
The `Menu` is not aligned with the other buttons (eg : **width 768 * 861**)
**develop** : 
image
**1778** : 
 
image

Could you please check it?  as discussed it can be fixed in this PR.

Thanks!

**Review by jolelievre — APPROVED** [review]
Thank you @NeOMakinG

**Review by PierreRambaud — APPROVED** [review]

**Review by HanaRebaiQA — DISMISSED** [review]
Hello @NeOMakinG 

I checked again this PR, but the problem previously mentioned still exist.image

https://user-images.githubusercontent.com/92912932/156396927-838c8129-3427-470e-bd87-87ac84923d54.mp4

All caches are deleted (PS, var/cache, browser)

Could you please check again ?

Thanks!

**Comment by NeOMakinG** [comment]
@HanaRebaiQA  I just tested

# With the PR:
image

# Without the PR:
image

Seems like you have a cache issue, or something similar!

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @prestascott 

In `1778`, the buttons (Menu, Help, Demo) are aligned in the same line on responsive mode. 
image

https://user-images.githubusercontent.com/92912932/157070959-1be0b00f-0275-4236-8a1a-3129430ac168.mp4


With this PR, the behavior is changed. 
When we click on `Menu`, the buttons (Help and Demo) are displayed below like this : 

https://user-images.githubusercontent.com/92912932/157071202-61e6966f-65cc-4fb5-9735-e130df4b181c.mp4

What do you think ?

Thanks!

**Comment by prestascott** [comment]
The "Demo mode" button and the "Help" button must be aligned. 
The button "Menu" must be avoided on responsive and removed.

**Review by HanaRebaiQA — COMMENTED** [review]
Thank you @prestascott for your feedback!
@NeOMakinG What do you think according to scott's answer?

**Comment by NeOMakinG** [comment]
> The "Demo mode" button and the "Help" button must be aligned. The button "Menu" must be avoided on responsive and removed.

I strongly disagree with this, as every module can add a button inside a hook there, this means that some shops have like 6-7 buttons there, we should hide it behind a menu button...

**Comment by NeOMakinG** [comment]
> > The "Demo mode" button and the "Help" button must be aligned. The button "Menu" must be avoided on responsive and removed.
> 
> I strongly disagree with this, as every module can add a button inside a hook there, this means that some shops have like 6-7 buttons there, we should hide it behind a menu button...

I'm sure that these shops with a lot of buttons are buggy on responsive atm as these buttons are not hidden on mobile

**Comment by prestascott** [comment]
@NeOMakinG Don't we have a FAB before on responsive? 🤔

**Comment by NeOMakinG** [comment]
> @NeOMakinG Don't we have a FAB before on responsive? 🤔

Sorry? What do you mean? Didn't understand...

Edit: Floating Action Button, my bad.

@prestascott We don't have the FAB on legacy pages

**Comment by prestascott** [comment]
Ok I understand better now @NeOMakinG

Maybe we can only keep 2 buttons:
- The main primary action button
- A secondary action button group, for example "More actions"

Wdyt?

**Comment by NeOMakinG** [comment]
> Ok I understand better now @NeOMakinG
> 
> Maybe we can only keep 2 buttons:
> 
> * The main primary action button
> * A secondary action button group, for example "More actions"
> 
> Wdyt?

Can we merge this PR and create another issue in case you want this? I don't want to change this on 1.7.8 as it can introduce a breaking change, we're not improving on 1.7.8.x but fixing bugs

**Comment by atomiix** [comment]
I guess @TristanLDD is now the man in charge to answer 😄

**Comment by TristanLDD** [comment]
@NeOMakinG I agree with you on hiding all hooks actions behind the menu button, that is the best solution until we might separate them in a more specific secondary button

**Review by HanaRebaiQA — APPROVED** [review]
Hello @NeOMakinG 

I checked again this PR. Here my tested cases : 

-Check the related issue : OK
-Check with different Width configuration on responsive : OK
-Check with mobile : OK
-Check with different browsers (Chrome, Firefox, Safari and Edge) : OK
-Check on all BO pages with responsive and mobile : OK
-Check with different languages (RTL and No RTL) : OK
-Check with multistore : OK

image
image
image
image

So, it's QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @HanaRebaiQA

**Pull request merged**
