### PR TITLE
Block blank issues

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Block blank issues
| Type?         | improvement
| Category?     | PM
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21958)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by PululuK** [comment]
@matks LGTM, but it's always interesting to explain the WHY 😉

**Comment by matks** [comment]
> @matks LGTM, but it's always interesting to explain the WHY 😉

Well, basically we have people who abuse the blank issue to avoid filling in the "Bug report" template (see https://github.com/PrestaShop/PrestaShop/issues/21925). So we block this too 😛

**Comment by PululuK** [comment]
> > @matks LGTM, but it's always interesting to explain the WHY wink
> 
> Well, basically we have people who abuse the blank issue to avoid filling in the "Bug report" template (see #21925). So we block this too stuck_out_tongue


But they can still choose a template and then delete the default content, right?

**Comment by matks** [comment]
> > > @matks LGTM, but it's always interesting to explain the WHY wink
> > 
> > 
> > Well, basically we have people who abuse the blank issue to avoid filling in the "Bug report" template (see #21925). So we block this too stuck_out_tongue
> 
> But they can still choose a template and then delete the default content, right?

If they do it, we know 100% they purposefully refused to follow the template. Right now since blank issues are available it sends an ambiguous message.

**Comment by NeOMakinG** [comment]
> > > @matks LGTM, but it's always interesting to explain the WHY wink
> > 
> > 
> > Well, basically we have people who abuse the blank issue to avoid filling in the "Bug report" template (see #21925). So we block this too stuck_out_tongue
> 
> But they can still choose a template and then delete the default content, right?

But you could be less attempted

**Review by NeOMakinG — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by SimonGrn — APPROVED** [review]

**Comment by matks** [comment]
Thank you for review

**Pull request merged**
