### PR TITLE
Fix for tests 1 and 2 of the shop parameters test suite

### PR DESCRIPTION
**Pull request by SimonGrn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | New selectors for the automated tests for the shop-parameters test suite
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | TEST_PATH=full/12_shop_parameters/* npm run specific-test -- --URL=URL_PRESTASHOP

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13561)

### CODE REVIEW

**Comment by matks** [comment]
Congrats for your 1st PR @SimonGrn 😉
Can you use English commit messages instead of French ? We have not-French contributors that would be confused by this.

Apart from that, code is ✅

**Comment by SimonGrn** [comment]
Yes, my bad I'm sorry, I'm too used to French. I'll be more careful !
Thanks

**Review by matks — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Commit message is now in English.

**Review by mbadrani — APPROVED** [review]
Well done @SimonGrn thanks!

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @SimonGrn

**Pull request merged**
