### PR TITLE
PrestashopDatabaseException on cart confirmation with free delivery cart rules in debug mode #32748 

### LINKED ISSUE #32748: PrestashopDatabaseException on cart confirmation with free delivery cart rules in debug mode
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When creating a new customer group and creating a new cart rule with free delivery for this specific group when ordering i have an error in debug mode :

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND ccr.id_cart_rule = 1 AND o.id_order IS NULL LIMIT 1' at line 5<br /><br /><pre> SELECT count(*) FROM `ps_cart_cart_rule` ccr INNER JOIN `ps_cart` c ON c.id_cart = ccr.id_cart LEFT JOIN `ps_orders` o ON o.id_cart = c.id_cart WHERE c.id_customer = 3 AND **c.id_cart = AND** ccr.id_cart_rule = 1 AND o.id_order IS NULL LIMIT 1</pre>

It seems that the value for the c.id_cart parameter is not being properly assigned or retrieved.

image

I tried with a fresh install of prestashop i have the same error.

### Expected behavior

It seems that the value for the c.id_cart parameter is not being properly assigned or retrieved.
Normally the c.id_cart parameter should be retrieved

### Steps to reproduce

**BO**
1. Turn on debug mode
2. Create a new customer group
3. Create a new cart rules with a voucher code
4. Add a minimum amount, a minimum quantity & quantity per user (for example 100)
5. Make a restriction with the carrier
6. Check the free delivery and save
7. Create a new customer
8. Check the new group that you have created & uncheck the others
9. Select the new group as default group.
10. Save

**FO**
1. Login with the new customer account
2. Add products to your cart
3. Go the the order page
4. Add the free delivery voucher
5. Confirm by paying by check or transfer

You should get an 500 Error or the prestashop database exeption

Link to the video : https://drive.google.com/file/d/1OV8Q3E329ZMJbKyHPXUu4Ab3BwIA_zsP/view?usp=sharing

### PrestaShop version(s) where the bug happened

1.7.8.8

### PHP version(s) where the bug happened

7.1.33-52,7.4.21

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by clotairer**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop / 8.1.x
| Description?      |  PrestashopDatabaseException on cart confirmation with free delivery cart rules in debug mode #32748 
| Type?             | bug fix 
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | yes
| How to test?      | See also #32748 
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/11889887087 ✅ 
| Fixed issue or discussion?     | Fixes #32748
| Related PRs       | none
| Sponsor company   | @202ecommerce

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by thbl** [comment]
up

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @clotairer ,

Auto tests are green : https://github.com/florine2623/testing_pr/actions/runs/11889887087

Followed the scenarios on the issue, I can't reproduce it anymore.
No error on the BO nor the FO.

https://github.com/user-attachments/assets/0ba4f924-8e57-4772-86a6-a2e3e8006551

Thanks for the PR !
It is QA ✅

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Comment by clotairer** [comment]
Thank you for the merge !

**Pull request merged**
