### PR TITLE
Bump version to 1.7.8.4

### LINKED ISSUE #27219: Release 1.7.8.4
This issue tracks the status of the PrestaShop 1.7.8.4 release

### Information

Q                                    | A
-----------------------|---------------
**Type**          | Patch version
**Est. Build date**  |  Februray 23, 2022
**Milestone** | [1.7.8.4](https://github.com/PrestaShop/PrestaShop/milestone/80)
**Kanban** | [1.7.8.4](https://github.com/PrestaShop/PrestaShop/projects/23)
**Est. Delivery date**          |  March 9, 2022
**Release manager tech**        |  @NeOMakinG 
**Release manager product**     |  @fabienvallon 
### Current status

- [x] Development
- [x] Build
- [x] QA validation
- [x] Release
- [x] Available for upgrade
- [x] Docker image

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Bump version
| Type?             |  improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes #27219.
| How to test?      | No need
| Possible impacts? | PS Version

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27771)

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @NeOMakinG (and @Progi1984 :trollface: )

**Review by matks — APPROVED** [review]

**Review by matks — CHANGES_REQUESTED** [review]
You need to also modify Kernel.php line 39

**Comment by NeOMakinG** [comment]
> You need to also modify Kernel.php line 39

https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/ 

Should be added there then

**Review by sowbiba — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @NeOMakinG

**Pull request merged**
