### PR TITLE
[*] MO : Replace 1.6 modules by its 1.7 correspondance

### PR DESCRIPTION
**Pull request by maximebiloe**
## Description

Prestashop 1.7 introduced some new modules. This PR replaces the old ones by the new ones.
Also, when you enable a theme, this will install/enable the modules you want to hook if they are not.

### CODE REVIEW

**Comment by kpodemski** [comment]
I see that you guys just don't care about this completely irrelevant `_` in modules name which is not compilant with PSR?

**Comment by maximebiloe** [comment]
I tagged this PR `WIP`, so it's just a Work In Progress and we still thinking about the modules naming

**Comment by kpodemski** [comment]
Well, I can be sceptical if i can read on gitter that maybe it is better to change PrestaShop validator and drop support for PSR-x than change these names... there is completely no point of using `_` here. It is good enough to have `psblockcart` `pscategorytree` etc.

**Comment by julienbourdeau** [comment]
We won't drop PSR for PrestaShop at all! I meant having an exception for the module classe name.

The '_' in the can be seen as a prefix since we can't handle namespace in module class names. You know that the module must match the folder name.

Look at this commit: https://github.com/PrestaShop/PrestaShop/commit/90366cff2f3a3681162e42c5c533dd5b6b695744 At this time we were already PSR-2 but until we had namespaces we had to do that. The names are still using underscore in PS 1.6 and we follow PSR-2

This is a **temporary** exception, once we rework the way we load module classes, the `Ps_` will disappear.

There is also another option, simply removing the underscore, but I'm not sure this kind of prefix makes any sense in the class name.

**Comment by maximebiloe** [comment]
I'm closing this one, it will be included in https://github.com/PrestaShop/PrestaShop/pull/4817

**Pull request closed without merging**
