### PR TITLE
Fix UI kit problems

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | This PR includes the new UI kit beta 3, and fixes many UI problems
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4324<br>http://forge.prestashop.com/browse/BOOM-4334
| How to test?  | Check all symfony pages

In this PR:
- Updated UI Kit 1.0.0 beta 3 (includes Bootstrap 4 beta 2 and [many other things])(https://github.com/PrestaShop/prestashop-ui-kit/releases/tag/1.0.0-beta-3)
- Fixed wrong padding on table header on the product list (it was too big)
- Fixed icon alignment on card headers (titles on recently migrated pages)
- Fixed style of the user menu on the main header (it was misaligned)
- Fixed style of PS tagger and PS tags (search components on the modules page and translation page, as well as categories on the product page)
- Updated style of pagination with "jump to page", where the input didn't look like an input (bottom of the product list)

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8553)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[admin-dev/themes/new-theme/scss/pages/_product_page.scss, line 879 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8553#-KzyC7iRaGgpqbNZTGZw:-KzyC7iRaGgpqbNZTGZx:b-o0d9qs) ([raw file](https://github.com/prestashop/prestashop/blob/af18f50d9abb9813f7dac36b9aa0b30e7c450e5b/admin-dev/themes/new-theme/scss/pages/_product_page.scss#L879)):*
> ```SCSS
>     padding: {
>       top: 0.625rem;
>       bottom: 0.625rem;
> ```

Did you really mean removing the right and left values ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8553)*

**Review by LittleBigDev — CHANGES_REQUESTED** [review]
Thank you @eternoendless 
One clarification needed

**Comment by eternoendless** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[admin-dev/themes/new-theme/scss/pages/_product_page.scss, line 879 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8553#-KzyC7iRaGgpqbNZTGZw:-KzyFrlpjYcWHXFMWrJJ:b-n09kul) ([raw file](https://github.com/prestashop/prestashop/blob/af18f50d9abb9813f7dac36b9aa0b30e7c450e5b/admin-dev/themes/new-theme/scss/pages/_product_page.scss#L879)):*
<details><summary><i>Previously, LittleBigDev (Bastien Bieri) wrote…</i></summary><blockquote>

Did you really mean removing the right and left values ?
</blockquote></details>

Yep, they were wrong. I purposely left them out so that we use the defaults which are set up by the UI kit. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8553)*

**Comment by LittleBigDev** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[admin-dev/themes/new-theme/scss/pages/_product_page.scss, line 879 at r1](https://reviewable.io:443/reviews/prestashop/prestashop/8553#-KzyC7iRaGgpqbNZTGZw:-KzyI-aj5BJPGtCLIpjN:bruhiwt) ([raw file](https://github.com/prestashop/prestashop/blob/af18f50d9abb9813f7dac36b9aa0b30e7c450e5b/admin-dev/themes/new-theme/scss/pages/_product_page.scss#L879)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Yep, they were wrong. I purposely left them out so that we use the defaults which are set up by the UI kit. 
</blockquote></details>

all good then !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8553#-:-KzyI3CMgSt8DX1PdLXc:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Pull request merged**
