### PR TITLE
Fix display of address format in Countries page

### LINKED ISSUE #26342: BO - Address format in Countries page is badly displayed
#### Describe the bug

Address format is off centered

#### Expected behavior

Address format should be centered like the other elements.
Tabs and buttons should be on one line.

#### Steps to Reproduce

1. Go to BO > International > Locations > Edit Country of your choice
2. Scroll down to Address format

**Screenshots**

PS 1.7.8.X and develop :
Screenshot 2021-10-20 at 18 08 47

PS 1.7.7.7 :
Screenshot 2021-10-20 at 18 08 07

#### Additional information

* PrestaShop version: 1.7.8.x, develop
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by marwachelly**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x 
| Description?      | Address format should be centered like the other elements. Tabs and buttons should be on one line.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26342.
| How to test?      | Check that the display of "Address format" in Countries page is ok.
| Possible impacts? | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26253)

### CODE REVIEW

**Comment by marwachelly** [comment]
This PR should be fixed by https://github.com/PrestaShop/PrestaShop/pull/26353.

**Comment by ghost** [comment]
Nice @marwachelly you target the nice branch not me :)

**Review by ghost — COMMENTED** [review]
This PR target the good branch

**Comment by Progi1984** [comment]
@marwachelly I reopen your PR.

**Review by ghost — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @marwachelly,

It is ok :heavy_check_mark: 
image

I compared the behavior when we resize the window with PS1778 => same problem
Alos validated in this [comment](https://github.com/PrestaShop/PrestaShop/pull/26353#issuecomment-950978046).
This PR
image
1778
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @marwachelly & @khouloudbelguith

**Pull request merged**
