### PR TITLE
AdminStats Controller use the good column for total

### LINKED ISSUE #22671: AdminStats Controller KPI best category is bad
#### Describe the bug

KPI best category is bad when product with reduction.

#### Expected behavior

Explain what you expected to happen instead.

#### Steps to Reproduce

Make an order with one product ( **category vêtement** ) 35€ but with 50% reduction
Make an order with one product ( **category art** )  30€ no reduction 
Go to stats to update KPI 
Go to category page check the best category

**Screenshots**

With Change 

Capture d’écran de 2021-01-05 10-59-54

Without change

Capture d’écran de 2021-01-05 11-00-20

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: N/A

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The column product_price is the price without reduction so the stats as bad
| Type?             | bug fix 
| Category?         | BO 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/22671 
| How to test?      | Check the stats follow the issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22585)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

I still have the same issue.
I attached a screen record
[Untitled_ Jan 4, 2021 5_51 PM.zip](https://github.com/PrestaShop/PrestaShop/files/5765826/Untitled_.Jan.4.2021.5_51.PM.zip)

Thanks to check and feedback

**Comment by ghost** [comment]
oh it's right it's this one who fix https://github.com/PrestaShop/statsforecast/pull/19

I asked @ttoine for information on the future

**Comment by ghost** [comment]
This PR fix the KPI here

Capture d’écran de 2021-01-05 10-20-10

I must open a new issue

**Comment by ghost** [comment]
I open new issue https://github.com/PrestaShop/PrestaShop/issues/22671 for this PR

**Review by Progi1984 — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

Is it ready for QA?

Thank you!

**Comment by ghost** [comment]
Yes

**Comment by khouloudbelguith** [comment]
Hi @okom3pom,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1OitnBqsO5p1sso06xzrNZIjQsP5-W8t1/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @okom3pom & @khouloudbelguith

**Pull request merged**
