### PR TITLE
Fix facets.js pendingQuery was always false

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | 1. pendingQuery was always false. ~~I set it to true when there is a pending request.~~<br>2. [Return early pattern](https://forum.freecodecamp.org/t/the-return-early-pattern-explained-with-javascript-examples/19364)<br>3. Ignoring successive requests because one is in progress can confuse the user. Better to abort the previous request and continue only the last one
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Test that the facets in FO work as before

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20530)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]
LGTM

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by ngodefroy** [comment]
Hello @davidglezz and thank you for your contribution,

I'm not too sure if it's directly linked, but I found an issue when filtering a product on a color:
Capture d’écran 2020-09-03 à 11 41 25


@NeOMakinG any thoughts?

**Comment by PierreRambaud** [comment]
> Hello @davidglezz and thank you for your contribution,
> 
> I'm not too sure if it's directly linked, but I found an issue when filtering a product on a color:
> Capture d’écran 2020-09-03 à 11 41 25
> 
> @NeOMakinG any thoughts?

This problem has been fixed here #20773 make sure you use the latest changes in your develop branch when getting the PR's code :)

**Comment by ngodefroy** [comment]
> > Hello @davidglezz and thank you for your contribution,
> > I'm not too sure if it's directly linked, but I found an issue when filtering a product on a color:
> > Capture d’écran 2020-09-03 à 11 41 25
> > @NeOMakinG any thoughts?
> 
> This problem has been fixed here #20773 make sure you use the latest changes in your develop branch when getting the PR's code :)

Ok, after rebase working fine
Thank you @NeOMakinG

**Comment by Progi1984** [comment]
Thanks @davidglezz & @ngodefroy

**Pull request merged**
