### PR TITLE
Fixed duplication of hooks in pages migrated to Symfony

### PR DESCRIPTION
**Pull request by mickaelandrieu**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Hooks were duplicated on all Symfony pages, making the customization a complete nightmare.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4178
| How to test?  | Install a module which can be hooked to any page => https://github.com/mickaelandrieu/ps_test. Before the block is rendered twice, after only once 

### Before

develop

before

### After

fixed

after

> Note: you can use the provided `ps_test` module to test the hooks.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8442)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
I made a quick search for your hook admin footer, here are the two call stacks:

```
array:37 [▼
  0 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/config/smarty.config.inc.php"
    "line" => 168
    "function" => "exec"
    "class" => "HookCore"
    "type" => "::"
  ]
  1 => array:3 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/classes/Smarty/SmartyLazyRegister.php"
    "line" => 83
    "function" => "smartyHook"
  ]
  2 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/app/cache/dev/smarty/compile/1d/bc/e2/1dbce2e1fba649e3fdf2076010a911d6f27e96fc.file.footer.tpl.php"
    "line" => 24
    "function" => "__call"
    "class" => "SmartyLazyRegister"
    "type" => "->"
  ]
  3 => array:3 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php"
    "line" => 188
    "function" => "content_59f89193d32745_14694191"
  ]
  4 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/vendor/prestashop/smarty/sysplugins/smarty_internal_template.php"
    "line" => 303
    "function" => "fetch"
    "class" => "Smarty_Internal_TemplateBase"
    "type" => "->"
  ]
  5 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/app/cache/dev/smarty/compile/e4/0a/91/e40a9104fc289dd9ba1075100f77a77ac66ea774.file.layout.tpl.php"
    "line" => 169
    "function" => "getSubTemplate"
    "class" => "Smarty_Internal_Template"
    "type" => "->"
  ]
  6 => array:3 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php"
    "line" => 188
    "function" => "content_59f89193d96394_62386411"
  ]
  7 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/classes/controller/Controller.php"
    "line" => 552
    "function" => "fetch"
    "class" => "Smarty_Internal_TemplateBase"
    "type" => "->"
  ]
  8 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/classes/controller/AdminController.php"
    "line" => 1825
    "function" => "smartyOutputContent"
    "class" => "ControllerCore"
    "type" => "->"
  ]
  9 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/controllers/admin/AdminLegacyLayoutController.php"
    "line" => 117
    "function" => "display"
    "class" => "AdminControllerCore"
    "type" => "->"
  ]
```

```
array:33 [▼
  0 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/config/smarty.config.inc.php"
    "line" => 168
    "function" => "exec"
    "class" => "HookCore"
    "type" => "::"
  ]
  1 => array:3 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/classes/Smarty/SmartyLazyRegister.php"
    "line" => 83
    "function" => "smartyHook"
  ]
  2 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/app/cache/dev/smarty/compile/1d/bc/e2/1dbce2e1fba649e3fdf2076010a911d6f27e96fc.file.footer.tpl.php"
    "line" => 24
    "function" => "__call"
    "class" => "SmartyLazyRegister"
    "type" => "->"
  ]
  3 => array:3 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/vendor/prestashop/smarty/sysplugins/smarty_internal_templatebase.php"
    "line" => 188
    "function" => "content_59f89193d32745_14694191"
  ]
  4 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/classes/controller/AdminController.php"
    "line" => 1822
    "function" => "fetch"
    "class" => "Smarty_Internal_TemplateBase"
    "type" => "->"
  ]
  5 => array:5 [▼
    "file" => "/home/thomas/Documents/github/PrestaShop/controllers/admin/AdminLegacyLayoutController.php"
    "line" => 117
    "function" => "display"
    "class" => "AdminControllerCore"
    "type" => "->"
  ]
```

All the 'parent' steps are common. I just give the path to the last hook to debug. :)

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 interesting, this explain why a hook is called twice or more but doesn't explain why some are called only once :)

I'm in favor of pushing this improvement first and we need a minor new issue for this specific hook: regarding at code, this is a very very low level issue and I'm afraid about updating this code before testing and refactoring.

**Comment by mickaelandrieu** [comment]
@Quetzacoalt91 as it's more a bug fix than a feature, can we consider a merge of this PR into `1.7.3.x` ?

**Comment by Quetzacoalt91** [comment]
As far as I know this bug appeared with the first version 1.7, so the version on which we send this fix does not matter.

However, as the 1.7.3.0 is already in code freeze, I guess that's too late for this one.

EDIT: this is the last PR moved to the branch `1.7.3.x` for last-minute merge.

**Review by Quetzacoalt91 — APPROVED** [review]

**Pull request merged**
