### PR TITLE
Improve CMS section

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Several improvements in CMS section.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

### If we are in some deeper category, layout title now shows which category are we in, like the grid below.
subcategory title

### If no CMS category is created and we are in the root category, we hide the grid and show a help notification instead, so it's not wasting space for merchants that don't use it.
helpbar

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @MatShir @kpodemski for validation.

**Comment by MatShir** [comment]
You hide the category list when it is empty, that is right ?

**Comment by Hlavtox** [comment]
@MatShir Yes, and show `If needed, you can also organize pages into categories. To start, simply create a new category by clicking the button in the toolbar.`

**Comment by MatShir** [comment]
Sounds good !

**Review by kpodemski — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]
LGTM, thanks @Hlavtox! 🙂

**Review by AureRita — COMMENTED** [review]
Hi @Hlavtox 

Thank you for your PR, I tested it and it works, as we can see here :

[Untitled_ Aug 2, 2023 11_29 AM.webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/19de183f-721f-470a-9d2a-f0f8d021a3d9)

So, for me it's ok, but, because this one change the title of the page, @PrestaShop/qa-automation , there 'll be some modification on the test auto. I need your approval to put this in QA :heavy_check_mark:

**Comment by boubkerbribri** [comment]
I started the tests here https://github.com/boubkerbribri/ga.tests.ui.pr/actions/runs/5751965852
will see if its needed update from our side.

**Comment by AureRita** [comment]
I already send many time an autotest on this link : 
https://github.com/AureRita/testing_pr/actions/runs/5736934400/job/15589198179

**Comment by boubkerbribri** [comment]
> I already send many time an autotest on this link : https://github.com/AureRita/testing_pr/actions/runs/5736934400/job/15589198179

Ok so it needs some update from our side, we will have a look (and push on the same PR)
Thanks

**Comment by Progi1984** [comment]
@Hlavtox I have modified your PR (UI tests) and I push on it.

My UI Tests : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5759991543

**Comment by Hlavtox** [comment]
Thanks @Progi1984, can it be merged if CI is green?

**Comment by Progi1984** [comment]
@Hlavtox I let @AureRita decide. :smile:

**Comment by AureRita** [comment]
Hi @Hlavtox 

After more test on it, I find a new issue on your PR, If you filter by name your categories and delete the only one categories on this filter, the categories modal will disappear and you'll not have this one except if you create a new categories with the same name as you can see : 

[Untitled_ Aug 4, 2023 11_01 AM (1).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/fe56fff0-cf8b-46ca-830d-d8c26fd04022)

**Comment by MatShir** [comment]
Nice catch !
So after a filtering and a deletion, the parent categories is hidden. Maybe so the solution would be to display the parent category in anycase when there is a filter one. wdyt @Hlavtox ?

**Comment by Progi1984** [comment]
@Hlavtox You need to fix the error of @AureRita before I fix remaining UI tests. 

(FYI @PrestaShop/ui-tests-maintainers)

**Pull request closed without merging**
