### PR TITLE
 [*] PDF : Update invoice.product-tab.tpl

### PR DESCRIPTION
**Pull request by Nobodaddy**
Wording harmonization. 
You need a tax CODE for your annual tax declaration, this here seems to be a label for the tax RATE ;)

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,
thank you for your contribution, but it's the tax code (Tax id),  no tax rate.

Best regards.

**Comment by Nobodaddy** [comment]
Nope, until 1.6.0.14 the invoice always displays the tax rate in this place and not the tax id! I really hope you didn't change this.
Who would need a tax id here? Neither merchant nor customer! The tax id is just a serial number in the database.

**Comment by julienbourdeau** [comment]
Hi,

The invoice has been fully reworked for PrestaShop 1.6.1 and this column does not display the tax rate. We are writing a long article for http://build.prestashop.com to introduce and explain the new invoice.
This column is now a unique tax code (it happens to be the id_tax but it's not relevant here) and will be related to the tax rate.

Wait for the article to understand, I hope you're gonna like it. We can also email you a PDF example if you want to see.

Best regards,

**Comment by Nobodaddy** [comment]
A unique tax code! Perfect! 
Provides us another good opportunity in Germany to override this invoice. ;-)
Joking apart, I know the "Unique TaxPAYER Reference" number (UTR) but I never heard of a unique tax code. But you should know that in Europe tax rates in invoices are obligatory. 
Are you sure that the changes you made are still compliant to European law? 
Please have a look here: http://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32014L0055
Or in a nutshell here: http://www.expatax.nl/regulationsinvoice.php

**Comment by djfm** [comment]
Hi Nobodaddy,

Thanks for you comments and for the references.
I have read the shorter version http://www.expatax.nl/regulationsinvoice.php and I believe that we are actually *becoming* compliant!

Among the elements required on the invoice we find the "Tax Rate". And since the tax rate may be different between different products on the same invoice, there doesn't seem to be a better way to comply than writing the rate on each line.

The French interpretation of the requirements at least explicitly states that we need the tax rate on each line.

Since writing the actual rate on each line would have taken too much space, we write a code and a legend for the codes below the invoice :)

That's what French invoicing software do, and I'm pretty sure it is safe everywhere (would the government blame us for putting too much tax information?)

If you still believe this is a problem for Germany please advise and we'll consider options.

**Pull request closed without merging**
