### PR TITLE
Replace serialize with json_encode

### PR DESCRIPTION
**Pull request by tomlev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | Use json_encode() instead of serialize(). Many thanks to ROBIN PERAGLIE from RIPS TECHNOLOGIES
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4804
| How to test?  | test if there is no regression: change of delivery option on cart / filter (especialy date one) still works on AdminOrders

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8772)

### CODE REVIEW

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @tomlev

**Comment by kpodemski** [comment]
Hey @eternoendless 

what's the deal with this change? security? some issues with newest browsers? why is this part of 1.7.2.x?

**Comment by eternoendless** [comment]
It's a security issue, yeah: http://build.prestashop.com/news/prestashop-1-7-2-5-maintenance-release/

**Comment by ecomm360** [comment]
Hello @eternoendless, 
this change introduces directly the use of json_encode and json_decode PHP funcions. Will be better to use Tools::jsonDecode Tools::jsonEncode, right?

To respect the use of Tools class.

Thanks!

**Comment by Matt75** [comment]
@ecomm360 Tools::jsonDecode and Tools::jsonEncode are deprecated since 1.7.0 ;)

**Pull request merged**
