### PR TITLE
Add TinyMCE mobile theme in the BO

### LINKED ISSUE #23225: Add TinyMCE mobile mode
#### Describe the solution you'd like

Add TinyMCE mobile mode for a better UX

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | TinyMCE on mobile is not UX, it has an official mobile theme, let's use it !
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23225.
| How to test?      | Go on a migrated page or legacy page with tinymce, open in mobile mode on your browser and try to use it ! Some features are not disponible on mobile mode such as tables
| Possible impacts? | Mobile content editing

Here is how it looks like :

image

image

⚠️ Needs to be merged when TinyMCE get updated 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23298)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

I found two behaviors:

When I use mobile in BrowserStack, the new model is well displayed, but we cannot add a table as commented in the `How to test section`, also we cannot add a `video`, is this a wanted behavior?

Also, when we use the toggle device toolbar, the new design of TinyMCE is not displayed
image

Using BrowserStack => OK
image
image

What do you think, is this normal behavior?

Thank you!

**Comment by NeOMakinG** [comment]
You can only add tables on Desktop, and then you can edit content on mobile, because it's pretty hard to add tables and videos on mobile are you can't resize it or place it well, so it's a normal behavior

Also, tinymce is not detecting screen size change, you need to refresh the page when using the console to check for responsive, it's a normal behavior too :)

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Thank you!
I found only that when we add an image with mobile & then we save it.
This image is not saved.
I tried it with migrated page & legacy page.
Steps to reproduce the issue:
1. Open the shop in a mobile
2. Go to BO > Catalog > Categories page
3. Edit a category
4. In the description add an image
5. save
6. Edit the category and check if the image exists => Nok

I attached a screen record
https://drive.google.com/file/d/19xfPbsfoSlc2HdHm74g13mDbOb8WmXWV/view?usp=sharing

Thanks!

**Comment by NeOMakinG** [comment]
Could I get some help from a backend dev @PrestaShop/prestashop-maintainers ? It looks like the image is fine inside the field :/

**Review by matthieu-rolland — COMMENTED** [review]
We should probably compare the request being done in mobile and desktop mode ?
I'll try to have a look when I finish my current work

**Comment by NeOMakinG** [comment]
@PrestaShop/product-team I disabled image feature on mobile as I think it's useless to have this feature on mobile and our filemanager is not mobile compatible at all, wdyt?

**Comment by marionf** [comment]
@NeOMakinG Yes, if it's not compatible it's better to disable it

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

Comparing the last update, there are some feature are missing: for example, undo and test style
**Before**
image
**After**
image


Thank you!

**Review by Progi1984 — CHANGES_REQUESTED** [review]
ESLInt is :red_circle: https://github.com/PrestaShop/PrestaShop/pull/23298/checks?check_run_id=2226516172#step:4:71

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is Ok :heavy_check_mark: 
I checked with migrated page (category & product)
I checked the legacy page (GDPR)

https://drive.google.com/file/d/1zhzWp4bVkK02KZxx--In0yXNgEf5oigE/view?usp=sharing

Thank you!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith & @NeOMakinG

**Pull request merged**
