### PR TITLE
[*] BO : Display upload_max_filesize in Backoffice server informations

### PR DESCRIPTION
**Pull request by 123monsite-regis**
Useful debug information

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi and thank you for your contribution!

If you can just rename your two commits, this will be perfect: it is a backoffice modification, so the commit should start with `[*]BO:`, not FO.

Thank you again !

**Comment by 123monsite-regis** [comment]
ok
I have  renamed them,
( for those who wants to change a commit message, useful help can be found here : https://help.github.com/articles/changing-a-commit-message/ )

**Comment by xGouley** [comment]
:+1:

**Comment by mickaelandrieu** [comment]
For 1.6 ok, but since we have Symfony full stack framework this information can be accessed in dev mode => <your website>/admin-dev/_profiler/phpinfo, no ?

**Comment by Shudrum** [comment]
Thank you !

**Comment by 123monsite-regis** [comment]
@mickaelandrieu , I think that this  must be visible by non-developper and in production mode (the message on the top of the page is : "This information must be provided when you report an issue on our bug tracker or forum" )

**Comment by mickaelandrieu** [comment]
@123monsite-regis ok :+1:  thank you for your contribution :)

**Pull request merged**
