### PR TITLE
Multistore - Shipping > Preferences - Add checkboxes #19374

### LINKED ISSUE #19374: Multistore - Shipping > Preferences - Add checkboxes
As a merchant, I want to be able to select one or many fields / toggles when I am in a specific shop context or in a group context, so I can apply a different configuration for the selected store or group and see which parameters have different value(s) for the selected store or group.

[Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

### LINKED ISSUE #19381: Multistore - Orders > Invoices - Add checkboxes
As a merchant, I want to be able to select one or many fields / toggles when I am in a specific shop context or in a group context, so I can apply a different configuration for the selected store or group and see which parameters have different value(s) for the selected store or group.

[Specs checkboxes](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md#checkboxes)

Documentation: https://devdocs.prestashop.com/1.7/development/multistore/configuration-forms/

Implementation example: https://github.com/PrestaShop/PrestaShop/pull/24393

Example of [multistore form](https://github.com/prestashop/prestashop/blob/b852579779071e6af6c70b7c585ae99a4480f3d3/src/PrestaShopBundle/Form/Admin/Configure/ShopParameters/General/MaintenanceType.php)

Exemple of [data configuration class
](https://github.com/prestashop/prestashop/blob/cf717ae668ff649cb7baf58446e8989213536c40/src/Adapter/Shop/MaintenanceConfiguration.php)

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add multi store checkboxes for invoice 
| Type?             | new feature
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes #19374
| How to test?      | See issue
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25906)

### CODE REVIEW

**Comment by okom3pom** [comment]
I follow the steps here https://github.com/PrestaShop/PrestaShop/pull/24393 but : shop_preferences.bundle.js do not exist @matthieu-rolland

**Comment by atomiix** [comment]
@okom3pom Thanks for this PR :) I don't think `package-lock.json` & `package.json` should have changed though, can you revert them?

**Comment by ghost** [comment]
Oups sorry

**Comment by ghost** [comment]
New PR : https://github.com/PrestaShop/PrestaShop/pull/25912

**Pull request closed without merging**
