### PR TITLE
The most useful PR in the world

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove duplicate dot in PR template
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!

(Note: this is an automated message, but answering it will reach a real human)

**Review by kpodemski — APPROVED** [review]

**Comment by matks** [comment]
@kpodemski Did you review so fast because of my clickbait PR title?

**Comment by kpodemski** [comment]
@matks I thought you fixed cart rules and I just clicked "approve" as fast as i could 😂

**Comment by boherm** [comment]
Ah, we need to update kanbanbot to detect of UI Tests is empty with this new value :D

**Review by boherm — APPROVED** [review]

**Comment by nicosomb** [comment]
Ok …
No QA for your PR… why don’t you follow the same rules than the other commiters ? 🤪

**Comment by matks** [comment]
> Ok … No QA for your PR… why don’t you follow the same rules than the other commiters ? 🤪

😱

**Pull request merged**
