### PR TITLE
Allow full anonymous Symfony controller

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Handle anonymous controllers more generically, we still rely on an attribute set on the request but it is now more generic, this way it can be used direct in module's routing if they need to create an anonymous Symfony controller they just need to add `_anonymous_controller: true` in the route configuration
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green UI tests green (see below for test details)
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/10421903915
| Fixed issue or discussion?     | 
| Related PRs       | ~
| Sponsor company   | ~

### How to test

You can use this module for tests:
[public_route.zip](https://github.com/user-attachments/files/16612885/public_route.zip)

It is a very simple module that adds an anonymous route on the URL `/admin-dev/modules/public_anonymous_route` without this PR the URL cannot be accessed unless you are connected to the back office, with this PR the URL is accessible and the router doesn't add the CSRF token in its URL when it is generated.

**How to test**
1. Install the module
2. Go to module manager search for the module and click on Configure
3. In the module configuration you should see a link to the anonymous URL `/admin-dev/modules/public_anonymous_route`  The URL must NOT contain an `_token` parameter
4. Click on the link a simple string is returned `Anonymous content`
5. Logout from the BO and refresh the page with the anonymous content, it is still accessible

### Anonymous route

Here's an example of an anonymous route:
```yaml
public_anonymous_route:
  path: /public_anonymous_route
  defaults:
    _controller: PrestaShop\Module\PublicRoute\AnonymousController::anonymousAction
    _anonymous_controller: true
```

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by matthieu-rolland — DISMISSED** [review]
LGTM 👍   nice feature indeed

**Review by matks — COMMENTED** [review]
Code seems OLK but I am surprised we have no controllers where we use `_legacy_controller_anonymous`

Why did we do https://github.com/PrestaShop/PrestaShop/pull/35810 ?

**Comment by jolelievre** [comment]
> Code seems OLK but I am surprised we have no controllers where we use `_legacy_controller_anonymous`
> 
> Why did we do #35810 ?

The #35810, as its title suggests, was only for legacy controllers, but we had no use case of anonymous Symfony controllers so far
It was never possible to do it and we didn't even realize, but now we do have a use case with `ps_account`

**Review by matks — APPROVED** [review]
Thank you for the answer

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @jolelievre ,

Thanks for the PR ^^

I tested the standard case :

https://github.com/user-attachments/assets/a74875c5-d8a8-4e1d-ad2c-fa206436660a

Works as expected ✅ 
Thanks!

**Review by Progi1984 — APPROVED** [review]
ok for ui tests

**Pull request merged**
