### PR TITLE
Fix Simple anchors do not work

### LINKED ISSUE #14821: Moving in browser history does not work with product pagination
Going backward/forward in product overview (e.g. search results) should behave as expected (actually go back/forward to the respective page)

**To Reproduce**
1. Go to http://brave-relation.demo-ms.production.prestashop.com/en/2-home
2. Click on 'Next' or '2'
3. Go backwards in browser (arrow or swipe)
4. We stay on page 2 :(

PrestaShop version: Not sure, I guess 1.7.6
PHP version: Doesn't matter

### LINKED ISSUE #26326: Simple anchors do not work
#### Describe the bug

When I try to link to an anchor on a page, the page refreshes and doesn't stay.

Not easy to explain I hope the video will be clearer :)

#### Steps to Reproduce

1. Created a lot of text on a CMS page
2. Make a link to reach the bottom of the page
`<a href="#id777">Test ancre</a>`
`<p>Text.....</p>`
`<p id="id777">`
4. click on the link and see the error, the page is refreshed and straightened out.

**Screenshots**

https://user-images.githubusercontent.com/46202635/137910770-307466ef-21a3-424c-b654-89977606fbcd.mp4

#### Additional information
* No cache
* Test locally and in production (similar error)
* PrestaShop version: 1.7.8
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by alexandrebru83**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | When I try to link to an anchor on a page, the page refreshes and doesn't stay. Not easy to explain I hope the video will be clearer
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26326 
| How to test?      | See #26326 How to test section
| Possible impacts? | Make sure this issue is still fixed #14821

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26380)

### CODE REVIEW

**Review by NeOMakinG — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by tegbessou — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @alexandrebrubeyonds ,

Thanks for the PR, LGTM !

**Comment by MatShir** [comment]
Hi @alexandrebrubeyonds, 
Thanks for your contribution, but just to let you know that the fix will be applied to the next major version. If you want, you can share your fix to the new patch release 1.7.8.1 coming beginning of November. You just have to change of branch to the 1.7.8.x :)

**Comment by florine2623** [comment]
@MatShir @marionf 

Should I remove QA ✔️ label ? and test again once the rebase is done ?

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by florine2623** [comment]
Hello all,

Tested again, works like a charm.
Thanks everyone!

**Comment by alexandrebru83** [comment]
> Hello all,
> 
> Tested again, works like a charm. Thanks everyone!

I haven't done the rebase yet @florine2623

**Comment by Progi1984** [comment]
Thank you @alexandrebrubeyonds & @florine2623

**Comment by PululuK** [comment]
> > Hello all,
> > Tested again, works like a charm. Thanks everyone!
> 
> I haven't done the rebase yet @florine2623

@Progi1984  about https://github.com/PrestaShop/PrestaShop/pull/26380#issuecomment-950768291, in this case this PR Need to be backported to 1.7.8.x right ?

**Comment by Progi1984** [comment]
(@PululuK I discuss with @alexandrebrubeyonds on Slack ;) and the answer is yes)

**Pull request merged**
