### PR TITLE
Add missing SQL row for actionFrontControllerSetVariables hook

### PR DESCRIPTION
**Pull request by comxd**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Added missing hook registration into SQL table. Introduced by #7612
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | N/A
| How to test?  | N/A

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/21855)

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
If you target the develop branch, please use the 1.7.8.0.sql file instead :)

**Comment by comxd** [comment]
Ok but I think this fix can be applied on the 1.7.6.x branch?

**Comment by PierreRambaud** [comment]
@comxd This one has been added in 1.7.5.0, it's not a regression. It must be in the develop branch :)

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional QA Dev ?

**Comment by Robin-Fischer-PS** [comment]
Yes @Progi1984 , OK for QA by Dev :)

(Especially with a How to Test with "N/A"...)

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
Installed PrestaShop from your branch : I have well the hook :

image

Installed PrestaShop from the develop branch : Not found.

It's QA :heavy_check_mark:

**Pull request merged**
