### PR TITLE
[-] CORE : actually use passed Context in Link->getLanguageLink()

### PR DESCRIPTION
**Pull request by ghost**
please review and eventually apply ASAP .. makes impossible to pass context into templates and more

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution.

Best regards.

**Comment by ZiZuu-store** [comment]
As I rely on this patch in my module .. can you tell me on which PS version it would be fixed ? I'll have to make a version check .. Thank you

**Comment by jeromenadaud** [comment]
Hi @ZiZuu-store those changes will be available in next release: 1.6.1.0

Best regards.

**Comment by ZiZuu-store** [comment]
Thanks :)

**Pull request merged**
