### PR TITLE
Update license headers

### LINKED ISSUE #15116: Update the license headers and the command that do it
According to https://github.com/PrestaShop/PrestaShop/pull/15092#discussion_r313806075 our license headers are wrong, and the automatic command https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Command/UpdateLicensesCommand.php#L40 is wrong too.

We need to
- fix the Command
- fix all the headers 😭

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Fixed mistake in UpdateLicensesCommand and updated license header for all files
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixed #15116
| How to test?  | Nothing to test

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15125)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Tests are faling.

**Comment by matks** [comment]
> Tests are faling.

He promised me he updated only what needed to be updated.
He lied 😆

**Comment by PierreRambaud** [comment]
Nope, tests directory contains files without license headers :/

**Comment by matks** [comment]
> Nope, tests directory contains files without license headers :/

I know, I did several times this operation and everytime I blacklist them manually

I'm going to redo this PR and submit it bit by bit, targeting specific folders

**Comment by matks** [comment]
> > Nope, tests directory contains files without license headers :/
> 
> I know, I did several times this operation and everytime I blacklist them manually
> 
> I'm going to redo this PR and submit it bit by bit, targeting specific folders

Hard to do :/ so many files

Instead I computed the list of files whose diff is more than a 0/0 git modif:
```
0	24	admin-dev/themes/new-theme/.webpack/common.js
6	6	admin-dev/themes/new-theme/js/app/cldr/exception/localization.js
6	6	admin-dev/themes/new-theme/js/app/cldr/index.js
6	6	admin-dev/themes/new-theme/js/app/cldr/number-formatter.js
6	6	admin-dev/themes/new-theme/js/app/cldr/number-symbol.js
6	6	admin-dev/themes/new-theme/js/app/cldr/specifications/number.js
6	6	admin-dev/themes/new-theme/js/app/cldr/specifications/price.js
0	24	admin-dev/themes/new-theme/tests/cldr/number-formatter.spec.js
0	24	admin-dev/themes/new-theme/tests/cldr/number-symbol.spec.js
0	24	admin-dev/themes/new-theme/tests/cldr/specifications/number.spec.js
0	24	admin-dev/themes/new-theme/tests/cldr/specifications/price.spec.js
65	65	install-dev/upgrade/php/ps_update_tabs.php
0	24	mails/themes/classic/components/footer.html.twig
0	24	mails/themes/classic/components/header.html.twig
0	24	mails/themes/classic/components/layout.html.twig
0	24	mails/themes/classic/components/order_layout.html.twig
0	24	mails/themes/classic/core/account.html.twig
0	24	mails/themes/classic/core/backoffice_order.html.twig
0	24	mails/themes/classic/core/bankwire.html.twig
0	24	mails/themes/classic/core/cheque.html.twig
0	24	mails/themes/classic/core/contact.html.twig
0	24	mails/themes/classic/core/contact_form.html.twig
0	24	mails/themes/classic/core/credit_slip.html.twig
0	24	mails/themes/classic/core/download_product.html.twig
0	24	mails/themes/classic/core/employee_password.html.twig
0	24	mails/themes/classic/core/forward_msg.html.twig
0	24	mails/themes/classic/core/guest_to_customer.html.twig
0	24	mails/themes/classic/core/import.html.twig
0	24	mails/themes/classic/core/in_transit.html.twig
0	24	mails/themes/classic/core/log_alert.html.twig
0	24	mails/themes/classic/core/newsletter.html.twig
0	24	mails/themes/classic/core/order_canceled.html.twig
0	24	mails/themes/classic/core/order_changed.html.twig
0	24	mails/themes/classic/core/order_conf.html.twig
0	24	mails/themes/classic/core/order_customer_comment.html.twig
0	24	mails/themes/classic/core/order_merchant_comment.html.twig
0	24	mails/themes/classic/core/order_return_state.html.twig
0	24	mails/themes/classic/core/outofstock.html.twig
0	24	mails/themes/classic/core/password.html.twig
0	24	mails/themes/classic/core/password_query.html.twig
0	24	mails/themes/classic/core/payment.html.twig
0	24	mails/themes/classic/core/payment_error.html.twig
0	24	mails/themes/classic/core/preparation.html.twig
0	24	mails/themes/classic/core/productoutofstock.html.twig
0	24	mails/themes/classic/core/refund.html.twig
0	24	mails/themes/classic/core/reply_msg.html.twig
0	24	mails/themes/classic/core/shipped.html.twig
0	24	mails/themes/classic/core/test.html.twig
0	24	mails/themes/classic/core/voucher.html.twig
0	24	mails/themes/classic/core/voucher_new.html.twig
0	24	mails/themes/classic/modules/followup/followup_1.html.twig
0	24	mails/themes/classic/modules/followup/followup_2.html.twig
0	24	mails/themes/classic/modules/followup/followup_3.html.twig
0	24	mails/themes/classic/modules/followup/followup_4.html.twig
0	24	mails/themes/classic/modules/ps_emailalerts/customer_qty.html.twig
0	24	mails/themes/classic/modules/ps_emailalerts/new_order.html.twig
0	24	mails/themes/classic/modules/ps_emailalerts/order_changed.html.twig
0	24	mails/themes/classic/modules/ps_emailalerts/productcoverage.html.twig
0	24	mails/themes/classic/modules/ps_emailalerts/productoutofstock.html.twig
0	24	mails/themes/classic/modules/ps_emailalerts/return_slip.html.twig
0	24	mails/themes/classic/modules/ps_emailsubscription/newsletter_conf.html.twig
0	24	mails/themes/classic/modules/ps_emailsubscription/newsletter_verif.html.twig
0	24	mails/themes/classic/modules/ps_emailsubscription/newsletter_voucher.html.twig
0	24	mails/themes/classic/modules/referralprogram/referralprogram-congratulations.html.twig
0	24	mails/themes/classic/modules/referralprogram/referralprogram-invitation.html.twig
0	24	mails/themes/classic/modules/referralprogram/referralprogram-voucher.html.twig
0	24	mails/themes/modern/components/footer.html.twig
0	24	mails/themes/modern/components/header.html.twig
0	24	mails/themes/modern/components/layout.html.twig
0	24	mails/themes/modern/components/order_layout.html.twig
0	24	mails/themes/modern/core/account.html.twig
0	24	mails/themes/modern/core/backoffice_order.html.twig
0	24	mails/themes/modern/core/bankwire.html.twig
0	24	mails/themes/modern/core/cheque.html.twig
0	24	mails/themes/modern/core/contact.html.twig
0	24	mails/themes/modern/core/contact_form.html.twig
0	24	mails/themes/modern/core/credit_slip.html.twig
0	24	mails/themes/modern/core/download_product.html.twig
0	24	mails/themes/modern/core/employee_password.html.twig
0	24	mails/themes/modern/core/forward_msg.html.twig
0	24	mails/themes/modern/core/guest_to_customer.html.twig
0	24	mails/themes/modern/core/import.html.twig
0	24	mails/themes/modern/core/in_transit.html.twig
0	24	mails/themes/modern/core/log_alert.html.twig
0	24	mails/themes/modern/core/newsletter.html.twig
0	24	mails/themes/modern/core/order_canceled.html.twig
0	24	mails/themes/modern/core/order_changed.html.twig
0	24	mails/themes/modern/core/order_conf.html.twig
0	24	mails/themes/modern/core/order_customer_comment.html.twig
0	24	mails/themes/modern/core/order_merchant_comment.html.twig
0	24	mails/themes/modern/core/order_return_state.html.twig
0	24	mails/themes/modern/core/outofstock.html.twig
0	24	mails/themes/modern/core/password.html.twig
0	24	mails/themes/modern/core/password_query.html.twig
0	24	mails/themes/modern/core/payment.html.twig
0	24	mails/themes/modern/core/payment_error.html.twig
0	24	mails/themes/modern/core/preparation.html.twig
0	24	mails/themes/modern/core/productoutofstock.html.twig
0	24	mails/themes/modern/core/refund.html.twig
0	24	mails/themes/modern/core/reply_msg.html.twig
0	24	mails/themes/modern/core/shipped.html.twig
0	24	mails/themes/modern/core/test.html.twig
0	24	mails/themes/modern/core/voucher.html.twig
0	24	mails/themes/modern/core/voucher_new.html.twig
0	24	mails/themes/modern/modules/followup/followup_1.html.twig
0	24	mails/themes/modern/modules/followup/followup_2.html.twig
0	24	mails/themes/modern/modules/followup/followup_3.html.twig
0	24	mails/themes/modern/modules/followup/followup_4.html.twig
0	24	mails/themes/modern/modules/ps_emailalerts/customer_qty.html.twig
0	24	mails/themes/modern/modules/ps_emailalerts/new_order.html.twig
0	24	mails/themes/modern/modules/ps_emailalerts/order_changed.html.twig
0	24	mails/themes/modern/modules/ps_emailalerts/productcoverage.html.twig
0	24	mails/themes/modern/modules/ps_emailalerts/productoutofstock.html.twig
0	24	mails/themes/modern/modules/ps_emailalerts/return_slip.html.twig
0	24	mails/themes/modern/modules/ps_emailsubscription/newsletter_conf.html.twig
0	24	mails/themes/modern/modules/ps_emailsubscription/newsletter_verif.html.twig
0	24	mails/themes/modern/modules/ps_emailsubscription/newsletter_voucher.html.twig
0	24	mails/themes/modern/modules/referralprogram/referralprogram-congratulations.html.twig
0	24	mails/themes/modern/modules/referralprogram/referralprogram-invitation.html.twig
0	24	mails/themes/modern/modules/referralprogram/referralprogram-voucher.html.twig
0	25	src/Core/Domain/Theme/Exception/FailedToEnableThemeModuleException.php
23	23	src/PrestaShopBundle/Resources/views/Admin/Improve/Design/Cms/Blocks/form.html.twig
3	3	src/PrestaShopBundle/Resources/views/Admin/Sell/Customer/Blocks/showcase_card.html.twig
0	24	tests-legacy/PrestaShopBundle/Twig/Fixtures/module1/views/PrestaShop/Admin/Product/test.html.twig
0	24	tests-legacy/PrestaShopBundle/Twig/Fixtures/module2/views/PrestaShop/test.html.twig
0	24	tests-legacy/PrestaShopBundle/Twig/Fixtures/module3/views/PrestaShop/Admin/Product/ProductPage/Lists/list.html.twig
0	24	tests-legacy/PrestaShopBundle/Twig/Fixtures/module3/views/PrestaShop/Admin/Product/test.html.twig
0	296	tests-legacy/Unit/Classes/CacheCoreTest.php
2	2	tests-legacy/bootstrap.php
0	25	tests-legacy/resources/ModulesOverrideInstallUninstallTest/AdminProductsController.php
0	25	tests-legacy/resources/ModulesOverrideInstallUninstallTest/Cart.php
3	4	tests-legacy/resources/module/demo/composer.json
0	24	tests-legacy/resources/module/demo/templates/admin/demo.html.twig
8	8	tests-legacy/resources/modules/cronjobs/classes/CronJobsForms.php
8	8	tests-legacy/resources/modules/cronjobs/classes/index.php
18	19	tests-legacy/resources/modules/cronjobs/composer.json
8	8	tests-legacy/resources/modules/cronjobs/controllers/admin/AdminCronJobsController.php
8	8	tests-legacy/resources/modules/cronjobs/controllers/admin/index.php
8	8	tests-legacy/resources/modules/cronjobs/controllers/front/callback.php
8	8	tests-legacy/resources/modules/cronjobs/controllers/front/index.php
8	8	tests-legacy/resources/modules/cronjobs/controllers/index.php
8	8	tests-legacy/resources/modules/cronjobs/cronjobs.php
8	8	tests-legacy/resources/modules/cronjobs/index.php
0	25	tests-legacy/resources/modules/cronjobs/translations/de.php
0	25	tests-legacy/resources/modules/cronjobs/translations/en.php
0	25	tests-legacy/resources/modules/cronjobs/translations/es.php
0	25	tests-legacy/resources/modules/cronjobs/translations/fr.php
8	8	tests-legacy/resources/modules/cronjobs/translations/index.php
0	25	tests-legacy/resources/modules/cronjobs/translations/it.php
8	8	tests-legacy/resources/modules/cronjobs/upgrade/index.php
8	8	tests-legacy/resources/modules/cronjobs/upgrade/upgrade-1.0.6.php
0	24	tests-legacy/resources/modules/cronjobs/views/css/configure-ps-15.css
0	24	tests-legacy/resources/modules/cronjobs/views/css/configure-ps-16.css
8	8	tests-legacy/resources/modules/cronjobs/views/css/index.php
8	8	tests-legacy/resources/modules/cronjobs/views/index.php
8	8	tests-legacy/resources/modules/cronjobs/views/templates/admin/_configure/helpers/form/index.php
8	8	tests-legacy/resources/modules/cronjobs/views/templates/admin/_configure/helpers/index.php
8	8	tests-legacy/resources/modules/cronjobs/views/templates/admin/_configure/index.php
8	8	tests-legacy/resources/modules/cronjobs/views/templates/admin/index.php
8	8	tests-legacy/resources/modules/cronjobs/views/templates/index.php
24	24	tests-legacy/resources/modules/gamification/classes/Advice.php
24	24	tests-legacy/resources/modules/gamification/classes/Badge.php
24	24	tests-legacy/resources/modules/gamification/classes/Condition.php
24	24	tests-legacy/resources/modules/gamification/classes/GamificationTools.php
18	19	tests-legacy/resources/modules/gamification/composer.json
0	25	tests-legacy/resources/modules/gamification/controllers/admin/AdminGamificationController.php
24	24	tests-legacy/resources/modules/gamification/controllers/index.php
0	25	tests-legacy/resources/modules/gamification/de.php
0	25	tests-legacy/resources/modules/gamification/fr.php
24	24	tests-legacy/resources/modules/gamification/gamification.php
24	24	tests-legacy/resources/modules/gamification/index.php
24	24	tests-legacy/resources/modules/gamification/sql_install.php
0	25	tests-legacy/resources/modules/gamification/translations/cs.php
0	25	tests-legacy/resources/modules/gamification/translations/de.php
0	25	tests-legacy/resources/modules/gamification/translations/es.php
0	25	tests-legacy/resources/modules/gamification/translations/fr.php
24	24	tests-legacy/resources/modules/gamification/translations/index.php
0	25	tests-legacy/resources/modules/gamification/translations/it.php
0	25	tests-legacy/resources/modules/gamification/translations/pl.php
0	25	tests-legacy/resources/modules/gamification/translations/ru.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.4.9.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.6.6.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.7.3.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.7.6.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.7.7.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.8.0.php
24	24	tests-legacy/resources/modules/gamification/upgrade/install-1.8.9.php
0	24	tests-legacy/resources/modules/gamification/views/js/gamification.js
0	24	tests-legacy/resources/modules/gamification/views/js/gamification_bt.js
3	3	tests-legacy/resources/modules/ganalytics/ganalytics.php
24	24	tests-legacy/resources/modules/ps_banner/index.php
24	24	tests-legacy/resources/modules/ps_banner/ps_banner.php
3	3	tests-legacy/resources/modules/ps_emailsubscription/index.php
3	3	tests-legacy/resources/modules/ps_emailsubscription/ps_emailsubscription.php
3	3	tests-legacy/resources/modules/ps_featuredproducts/ps_featuredproducts.php
0	24	tests/Unit/PrestaShopBundle/Twig/Fixtures/modules/template.html.twig
0	24	tests/Unit/Resources/assets/css/override.css
0	24	tests/Unit/Resources/assets/css/sizes.css
0	24	tests/Unit/Resources/assets/css/titles.css
0	24	tests/Unit/Resources/mails/templates/account.html.twig
3	21	tools/build/Library/InstallUnpacker/content/js-runner.js
```

**Comment by matks** [comment]
Updated the PR, this should do the job 👍

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Unit tests fail in Travis only 🙄

**Comment by matks** [comment]
This is going to need an advanced exploration of Travis inner depths 😢

**Comment by matks** [comment]
Unit tests fail for both 5.6 and 7.1 => not a 5.6 Travis issue

**Comment by eternoendless** [comment]
This is not critical, removing it from the 1.7.6.1 milestone

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/15426

**Pull request closed without merging**
