### PR TITLE
Align checkboxes of multistore widget

### LINKED ISSUE #26904: BO - Multistore - migrated page with checkboxes
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Configurations pages with checkboxes are: https://github.com/PrestaShop/prestashop-specs/blob/master/content/1.7/back-office/multistoregeneralspecs.md#checkboxes

when a shop is selected, The checkboxes are not aligned
image

This is a new behavior in PS178
In the PS1778, we don't have checkboxes, so it is not a regression.

### Expected behavior

_No response_

### Steps to reproduce

1. Enable multistore
2. Create a new shop
3. Go to BO > General > Maintenance page
4. Select a shop
5. See error: The checkboxes are not aligned

### PrestaShop version(s) where the bug happened

1.7.8.0, develop

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Multistore checkbox wasn't aligned with the right content
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #26904.
| How to test?      | See issue
| Possible impacts? | Multistore checkbox

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27430)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by HanaRebaiQA — CHANGES_REQUESTED** [review]
Hello @NeOMakinG 

The issue is partially fixed. It fixes only for Enable Store label.
But it's not fixed for the other labels alignment.
image
image
https://watch.screencastify.com/v/mpEAqvCCOA7dbg8fWNcX

Please check and feedback!

Thanks!

**Review by atomiix — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @NeOMakinG

**Review by HanaRebaiQA — APPROVED** [review]
Hello @NeOMakinG 

I checked again this PR. The issue is fixed.

Here the verified cases : 
-Check with multistore : OK
-Check with different languages (as RTL) : OK 
-Check with different browsers (Chrome & firefox) : OK
-Check with responsive mode : OK 
image
image
image

image
image


https://user-images.githubusercontent.com/92912932/154507437-baa6c126-8c57-4dcc-aee7-ae4b719d7403.mp4


https://user-images.githubusercontent.com/92912932/154507512-620325e9-f585-4f98-bb6c-c1f787abe908.mp4



So, QA :heavy_check_mark: 

Thanks!

**Comment by NeOMakinG** [comment]
Thanks @HanaRebaiQA

**Pull request merged**
