### PR TITLE
Update wording AdminPerformanceController.php

### PR DESCRIPTION
**Pull request by Nobodaddy**
| Questions | Answers |
| --- | --- |
| Branch? | PrestaShop 1.7 dev |
| Description? | Corrected to capitalizing at the beginning of a sentence and made one notification more precise |
| Type? | improvement |
| Category? | CORE |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | (optional) If this PR fixes a [Forge](http://forge.prestashop.com/) ticket, please add its complete Forge URL. |
| How to test? | Please indicate how to best verify that this PR is correct. |

### CODE REVIEW

**Comment by AlexEven** [comment]
Hello Rainer, thanks for this!

I have to disagree with your suggestion for the message, as it would be changing its meaning. It's supposed to say that PS is unable to see whether the debug mode is activated or not (and thus incapable of giving a yes/no status to the "Debug mode" option). Your suggestion is assuming it is disabled, while it could be enabled in fact. We just don't know.

We could change it, but it should be something like "Impossible to know if debug mode is enabled or not".

Thank you!

**Comment by Nobodaddy** [comment]
Hello Alex,
How about *"Could not detect if debug mode is enabled. .."*?

**Comment by AlexEven** [comment]
Sounds good, thank you!

**Comment by antoin-m** [comment]
Hi @Nobodaddy, thank you for you contribution.

I'll close this one in favor of https://github.com/PrestaShop/PrestaShop/pull/7428 so that you won't have to rebase.

**Pull request closed without merging**
