### PR TITLE
Remove useless static cache and make sure CI exit in status 1 when installation failed

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Make sure `getIdFromClassName` is properly generated when using the CLI context. The problem is: because all requests are done one after the other, the method fill the value as empty array. If the array is empty, you can redo the SQL request. Than, remove `--quiet` mode when running composer. Also, in the future, instead of `die`, use `exit(1)`, it will make the CI failed, instead of telling you that everything is ok.
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is green.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24970)

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional Does it need some QA as it impacts installer ?

**Comment by PierreRambaud** [comment]
> @PrestaShop/qa-functional Does it need some QA as it impacts installer ?

Nope, it's only during the CI process

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
> > @PrestaShop/qa-functional Does it need some QA as it impacts installer ?
> 
> Nope, it's only during the CI process

I'm sorry but the code impacts the install in console mode.

**Comment by atomiix** [comment]
> > > @PrestaShop/qa-functional Does it need some QA as it impacts installer ?
> > 
> > Nope, it's only during the CI process
>
> I'm sorry but the code impacts the install in console mode.

@Progi1984  The CI uses the CLI installation so I guess if the installation works on the CI, it's ok?

**Comment by Robin-Fischer-PS** [comment]
After checking with @boubkerbribri , no need for more QA than the CI, so it's QA :heavy_check_mark: if CI is green :)

**Comment by atomiix** [comment]
Thanks @PierreRambaud!

**Pull request merged**
