### PR TITLE
Remove useless hook_delete file to permit upgrade from 1.6.x to 1.7.0.x (backport PR on 1.7.7.X)

### LINKED ISSUE #23433: Uprade Process : Prevent error on SQL existing row
#### Describe the bug

Updating from 1.6 in some case, process update broke during SQL insertion, because some date are yet present.

#### Expected behavior

As use case, some modules provide 1.6 and 1.7 compatibility. In this case could enable some hook only present in 1.7 version. If we update from 1.6, we could broke process on different step as at https://github.com/PrestaShop/PrestaShop/blob/6bf6509a2a5a823256c564f1625696d728edd2f3/install-dev/upgrade/sql/1.7.0.0.sql#L147-L155

#### Steps to Reproduce

1. Use a 1.6 versipon
2. Install any plugin with 1.6 and 1.7 comptabillity (and using some new hook as "displayAfterCarrier","displayProductExtraContent","displayNavFullWidth"
2. Use auto upgrade and update to 1.7 stable
3. Run upgrade 
4. Wait broke process

Get an error as : 
```
 SQL 1.7.0.0 1062 in INSERT INTO `ps_hook` (`name`, `title`, `description`, `position`) VALUES ('actionValidateCustomerAddressForm', 'Customer address form validation', 'This hook is called when a customer submit its address form', '1'), ('displayAfterCarrier', 'After carriers list', 'This hook is displayed after the carrier list in Front Office', '1'), ('displayCarrierExtraContent', 'Display additional content for a carrier (e.g pickup points)', 'This hook calls only the module related to the carrier, in order to add options when needed.', '1'), ('validateCustomerFormFields', 'Customer registration form validation', 'This hook is called to a module when it has sent additional fields with additionalCustomerFormFields', '1'), ('displayProductExtraContent', 'Display extra content on the product page', 'This hook expects ProductExtraContent instances, which will be properly displayed by the template on the product page.', '1'), ('displayNavFullWidth', 'Navigation', 'This hook displays full width navigation menu at the top of your pages', '1'), ('displayAfterBodyOpeningTag', 'Very top of pages', 'Use this hook for advertisement or modals you want to load first.', '1'), ('displayBeforeBodyClosingTag', 'Very bottom of pages', 'Use this hook for your modals or any content you want to load at the very end.', '1'): Duplicate entry 'displayAfterCarrier' for key 'hook_name'
```

#### Solution proposed

Use SQL IGNORE keyword on any SQL insertion

#### Additional information

* PrestaShop version: 1.6.1.x
* PHP version: 7.1

### PR DESCRIPTION
**Pull request by camlafit**
It's backport PR https://github.com/PrestaShop/PrestaShop/pull/23435 from develop to 1.7.7x branch as asked by @atomiix 
https://github.com/PrestaShop/PrestaShop/pull/23435#issuecomment-801984817

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | Fix #23433 and complete bdb65673dcafc0fcd8899d137431a62d165487bf<br>Prevent upgrade process from 1.6 version <br>Remove useless delete_hook file and prefere full SQL queries 
| Type?             | bug fix 
| Category?         | CO
| BC breaks?        | no
| Deprecations?     |no
| Fixed ticket?     | Fixes #23433 
| How to test?      | Do an upgrade from 1.6 with module using any "displayBeforeBodyClosingTag","displayAfterBodyOpeningTag","validateCustomerFormFields","displayCarrierExtraContent","actionValidateCustomerAddressForm","displayAfterCarrier","displayProductExtraContent","displayNavFullWidth" hook
| Possible impacts? | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23695)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by sarahdib** [comment]
Hello @camlafit 

Could you indicate us which modules use these hook ?

Thank you

**Comment by camlafit** [comment]
Hello @sarahdib

I wrote a list on #23433 issue  : https://github.com/PrestaShop/PrestaShop/issues/23433#issuecomment-786703091

Thanks

**Comment by sarahdib** [comment]
@camlafit as indicated here : [23433](https://github.com/PrestaShop/PrestaShop/issues/23433#issuecomment-804220920) This bug wasn't reproductible by our team.

@PrestaShop/prestashop-core-developers this pr shouldn't be in waiting for QA if we can't reproduce the issue.

**Comment by PierreRambaud** [comment]
Hi @camlafit ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Comment by kpodemski** [comment]
I think this report is valid @PierreRambaud 

I'll take on this issue and PR as QA seems to test wrong hooks, different than the reported in this PR.

**Comment by PierreRambaud** [comment]
> I think this report is valid @PierreRambaud
> 
> I'll take on this issue and PR as QA seems to test wrong hooks, different than the reported in this PR.

Watch out, you have to rebase on the develop branch ;)

**Comment by camlafit** [comment]
Hello

Sorry but I have nothing to said in more. I just can confirm problem occurred and have provided a patch to permit upgrade as asked. 
I'm open to complete but I need more element to know what to do.

thanks

**Comment by camlafit** [comment]
Hello

@PierreRambaud  as asked on initial PR , this PR should be hover 1.7.7.x I can rebase hover develop but looks as a non sense.

I wait your confirmation about how managed rebasing.

Thanks

**Comment by kpodemski** [comment]
Hello @camlafit 

First of all, thank you for your contribution and for getting back to us.

This PR should be re-done on the `develop` branch. I think you're right, and it's a valid bug report. The problem is that you didn't respond to our QA team in the related Issue, and from what I see, they were testing the wrong hooks.

I would suggest responding to our QA team first, and then create Pull Request on the `develop`.

**Comment by PierreRambaud** [comment]
Hi @camlafit ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Comment by camlafit** [comment]
Hello

No pb. You're welcome to backport this code if required. 

I'm not able to reply @kpodemski as it's yet a backport from develop branch as asked previously on https://github.com/PrestaShop/PrestaShop/pull/23435

Thanks

**Pull request closed without merging**
