### PR TITLE
changed hardcoded skiplist

### PR DESCRIPTION
**Pull request by mauglee**
Skiplist should depend on `ps_order_state`.`unremovable` value from DB

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for this PR!

Could you amend your commit's name to use the [guidelines](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message), so that it is taken into account by our changelog?
To do this, open a command line window and use `git commit --amend` for the commit's name. See [GitHub's help page](https://help.github.com/articles/changing-a-commit-message/) for more information.

_Note: this must be done via the command line: just changing the title of the pull-request from the GitHub interface is not the same!_ :)

Thank you!

**Comment by mauglee** [comment]
Commit amended. Should I do "pull request" again?

**Comment by xBorderie** [comment]
There's a merge commit in there, so you should try remove it, but other than that the PR is fine, thanks!

**Comment by mauglee** [comment]
Could you tell me exactly what to do? Because I am not so advanced git user.

**Comment by xBorderie** [comment]
Ah, I see you directly closed this one and created PR #5073, thanks!

**Comment by mauglee** [comment]
Yes, I was „fighting hard“ with this merged branch and decided simply to redo everything. If it's not taking a lot of your time, could you explain me how to pull-request again in the future? Because my push was rejected and I was proposed to pull from repo. That's how this "develop" branch was merged.

**Pull request closed without merging**
