### PR TITLE
CO: Attribute's EAN in the friendly URLS

### PR DESCRIPTION
**Pull request by alendit**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | "develop"
| Description?  | CO: Show product attribute's ean in the product's friendly url if there is one set
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3032
| How to test?  | Create a product with multiple attributes, each attribute with EAN. Go to product page and check if the EAN part of the URL changes when you select another product variant

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks a lot, Dimitri!

**Comment by vincentbz** [comment]
Hi @alendit 

Thanks for that PR !
I've just tried it and there is something weird. There is a number in the URL, but it's not the EAN13, see both here : 
EAN : 1234567890123
URL : 2147483647

image

**Comment by alendit** [comment]
Hi, could you show me the pretty URL product path setting?

**Comment by alendit** [comment]
Ok, try it now. 

Tell me, if you'd like to rebase it on the latest master and squash the commits

**Comment by aleeks** [comment]
Hello both,

I'm really not a big fan about this feature from scratch. 
@alendit can we image an automatic system based on more field than ean13 ? 
- some fields we define and accept
- search about these fields
- and next, do your process ?

but not like this.

**Comment by maximebiloe** [comment]
Hello @alendit,

I think we need to think more about this feature. We can't just add this field. Maybe we need to do something more generic.
Moreover, you choose to use the first EAN-13, why not the second one or the third one? We need to make something more complete, so I close this PR.

Regards.

**Pull request closed without merging**
