### PR TITLE
Multishop canvas fix

### LINKED ISSUE #34898: Product Images does not work in BO multishop with different domain names
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When we create a multi-shop PrestaShop with different domain names for the 2 stores, we end up with errors when generating the product images on the product sheets in the stores' back-office.

error-prestashop8

In the browser console, we can see the following error : 
`Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.`

⚠️  Please note that this case is possible if, when creating a new store, we enter an **existing domain name** in the store's URL fields!

The problem is also possible when we create a new product.
When we import an image, it is correctly added with its visual, then as soon as we save our changes and reload the page, we get the same error again.

For your information, when we run the same tests on a server with 2 existing but different domain names. We end up with the same errors. However, the domain names are correctly configured and point to the root of the PrestaShop folder on the server. (This is where we discovered the bug).

Multi-shop configuration (below) :

conf-shop1
conf-shop2

### Expected behavior

The aim of creating a multi-store PrestaShop would be to be able to view the product images of 2 stores configured with different domain names without having problems displaying product images, as we can do with PrestaShop v1.7.8.X.

### Steps to reproduce

1. Activate PrestaShop multi-shop mode
2. Create a new store
3. Once the new store has been created, you can click on "Click here to define a URL for this store".
4. In the "Shop URL" section of the domain fields, enter an existing domain name.
5. Empty or leave empty the Virtual URL and Final URL fields, then click on the "Save" button to save your changes.
6. Next, go to Catalog > Products, select your new store and click on a product with a correctly displayed image

https://github.com/PrestaShop/PrestaShop/assets/90344180/0959eb1d-6bda-44f1-9478-f70bcae81938

### PrestaShop version(s) where the bug happened

8.1.1

### PHP version(s) where the bug happened

8.1.26

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

ScaleDEV

### PR DESCRIPTION
**Pull request by unlocomqx**
Fixes https://github.com/PrestaShop/PrestaShop/issues/34898

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR fixes a CORS issue with the dropzone canvas
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Issue https://github.com/PrestaShop/PrestaShop/issues/34898
| UI Tests          | Please run UI tests and paste here the link to the run. [Read this page to know why and how to use this tool.](https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/ui-tests/).
| Fixed issue or discussion?     | Fixes #{issue number here}, Fixes #{another issue number here}, Fixes https://github.com/PrestaShop/PrestaShop/discussions/ {discussion number here}
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by unlocomqx** [comment]
This may or may not be a good solution. I just wanted to show a path for fixing it.

**Review by matthieu-rolland — COMMENTED** [review]
hello, and thank you for your contribution 👍 

Could you please explain your PR ? What did change i dropzone minified js  ?

**Comment by unlocomqx** [comment]
hi @matthieu-rolland 

I probably shouldn't have modified the min js, I will add it to the build if possible

I added img.crossOrigin = "anonymous" to allow loading the img from the other domain.
Otherwise, the allow cross origin header won't have an effect.

I will see how to modify the js properly

**Comment by OrionCodeDev** [comment]
> hi @matthieu-rolland
> 
> I probably shouldn't have modified the min js, I will add it to the build if possible
> 
> I added img.crossOrigin = "anonymous" to allow loading the img from the other domain. Otherwise, the allow cross origin header won't have an effect.
> 
> I will see how to modify the js properly

i tested it and for me still on product page, images can't load bcs cross origin error in console. 
Also same problem is in: #34886

**Comment by unlocomqx** [comment]
> > hi @matthieu-rolland
> > I probably shouldn't have modified the min js, I will add it to the build if possible
> > I added img.crossOrigin = "anonymous" to allow loading the img from the other domain. Otherwise, the allow cross origin header won't have an effect.
> > I will see how to modify the js properly
> 
> i tested it and for me still on product page, images can't load bcs cross origin error in console. Also same problem is in: #34886

Sorry I reproduced it on 8.1 then made my edits from the develop branch not the 8.1.x branch
I will replace this fix with another commit

**Pull request closed without merging**
