### PR TITLE
Add menu responsive (symfony part)

### PR DESCRIPTION
**Pull request by nihco2**
Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add left menu responsive
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/STAB-70
| How to test?  | Check if it's the same behavior as legacy responsive

### CODE REVIEW

**Comment by basma-yangui-prestashop** [comment]
Hi @nihco2,

After checking your fix, I noticed that :

- The header height of the Product and Modules page is smaller than that of the other pages (Legacy)
**Products header**
products_header
**Orders header**
orders_header

- When there is no notifications there is a chip indicating "0 notifications" in the product and modules page while there isn't any chip for the other pages
pastille

Could you please fix that?

**Comment by nihco2** [comment]
Thx @basma-yangui-prestashop, it's fixed

**Comment by basma-yangui-prestashop** [comment]
You welcome @ nihco2, but now, here is what I find:
- The hamburger button is bigger in the Orders page than in the Products/Modules page 
**Orders page**
capture d ecran de 2017-02-20 16 37 22
**Product page**
capture d ecran de 2017-02-20 16 37 59

- The chip indicating "0" notifications still exists even if there is notifications

- The message at the bottom of the notifications page indicating that there is no new order / customer does not appear in the Legacy pages. Is that normal?

**Comment by nihco2** [comment]
@basma-yangui-prestashop all is fixed, thx !

**Pull request closed without merging**
