### PR TITLE
Fix the search error with white spaces in stock page

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | When inserting a space before or after the keyword to search, no results are displayed. There is only the alert message.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3482
| How to test?  | BO > Catalog > Stock, insert a keyword with blank spaces and check If it returns the expected result.

### CODE REVIEW

**Comment by aleeks** [comment]
@nihco2, @maximebiloe  Did you think this can break other thing ?

Thank you @Azouz-Jribi
Maybe, you will have to rebase when yours others PR will be merged :smile:

**Review by maximebiloe — DISMISSED** [review]

**Review by eternoendless — CHANGES_REQUESTED** [review]
Needs rebase

**Comment by Azouz-Jribi** [comment]
Hello @eternoendless 
Rebase is done ;)

**Review by eternoendless — DISMISSED** [review]

**Comment by eternoendless** [comment]
Thanks @Azouz-Jribi !

**Review by aleeks — APPROVED** [review]

**Comment by aleeks** [comment]
Thank you @Azouz-Jribi

**Pull request merged**
