### PR TITLE
[-] FO : SQL query was errorneous and did not work for CMS pages

### PR DESCRIPTION
**Pull request by xitromedia**
...with a little bit better readability :o)
And again i recommend: PS programmers should test the code they write before releasing to the public :o)

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR and again as always your positive and encouraging comments.

Regards

**Comment by gRoussac** [comment]
@sfroment42  https://github.com/PrestaShop/PrestaShop/blob/1.6/classes/Meta.php#L403-L404 same thing

Thanks

**Comment by xitromedia** [comment]
Surely it is a dev branch and not yet released to the end user. But this code is not currently in work, rather from 17.12.2014 !? It is simply written but not tested like a lot of other code in PS as i often see. And brackets around (a?b:c) is nothing new in concatenated strings, i think.

My impression is that PS developers write often a lot of untested code causing a lot of time wasting and unnecessary error searches for other developers and users. Maybe there should be done more for quality management than for mass programming and i can only appeal to the PS team to advance the quality of the coding process if PS shall someday be a more stable, reliable and recommendable shop system.

Tell me please if my criticism is inappropriate or unwanted....but as i often see when searching the inet, the prestashop´s "bad code" problem is frequently discussed and not a problem just of me.

regards
andré

**Comment by sfroment42** [comment]
Hello,

Thanks for your PR sorry for my mistake.

Best regards.

**Pull request merged**
