### PR TITLE
Fix typo into phpDoc

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | IT's not traffix but traffic.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
You need to rebase :( because of https://github.com/PrestaShop/PrestaShop/issues/29641

**Review by yanmakouf — DISMISSED** [review]

**Comment by matks** [comment]
Trying to close and reopen to reset the CI

**Review by FabienPapet — DISMISSED** [review]

**Comment by FabienPapet** [comment]
I think there is no need to qa tests for this one. WDYT @PrestaShop/qa-team ?

**Review by FabienPapet — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
For sure, there's no need for QA there, but we need to wait for the CI fix.

**Comment by Robin-Fischer-PS** [comment]
Nop, we are going to test manually whole PrestaShop !!! :trollface: 

Yes, of course no QA on this one :P

**Comment by kpodemski** [comment]
Thx @PrestaEdit

**Pull request merged**
