### PR TITLE
Enable migrated Feature page and remove AdminFeaturesController

### LINKED ISSUE #10540: Migrate Catalog > Attributes & Features > Features page
Part of Symfony migration project
Type: page

Todo:
- [ ] Migrate listing and helper card 
PR: https://github.com/PrestaShop/PrestaShop/pull/15045

### Controller / template
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

### PR DESCRIPTION
**Pull request by zuk3975**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Enable migrated Feature page by default, remove feature flags and remove AdminFeaturesController and related legacy templates.<br> If you come to create feature value from the features index page (when we don't know the feature id), then after creation you are redirected back to the features index page. <br> If you come to create feature value from certain feature page (we know the featureId), then after creation you are redirected back to that feature view page (a.k.a feature values index page of that feature).
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Once the following PR https://github.com/PrestaShop/ps_facetedsearch/pull/862 is tested and ps_facetedsearch new version is released. Then we can update this PR composer.lock (include new version of the related module). Then this PR can be tested as following: Go to Sell > Catalog > Attributes & Features > Features and test all the behavior of grid, create, edit, delete, view actions (view action has its own create/edit/delete feature value which as well needs to be tested.<br>[UI tests https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5830924508](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6095486838)
| Fixed ticket?     | Closes https://github.com/PrestaShop/PrestaShop/issues/10540
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

**BC BREAKS**
controllers/admin/AdminFeaturesController.php has been removed;
admin-dev/themes/default/template/controllers/feature_value dir with all contents has been removed;
admin-dev/themes/default/template/controllers/features dir with all contents has been removedl

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]
Thanks @zuk3975 

First approval, but we need to check UI tests before validation of course

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5414877578

**Review by jolelievre — CHANGES_REQUESTED** [review]
As we discussed to really finalize this the faceted search module must be released and updated in this PR, that's the only reason why I temporarily block this on

**Comment by nesrineabdmouleh** [comment]
UI tests => https://github.com/nesrineabdmouleh/testing_pr/actions/runs/5442755354

**Comment by Progi1984** [comment]
UI Tests : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5456217511

**Comment by zuk3975** [comment]
UI tests running again:
https://github.com/zuk3975/testing_pr/actions/runs/5462542627

**Comment by zuk3975** [comment]
UI tests still needs adjustments. Ping @Progi1984 I don't understand whats wrong, so hopefully you can sort it out and finish this page :man_shrugging: :v:

**Review by lartist — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by nesrineabdmouleh** [comment]
Hello @zuk3975 

Please fix the conflicting files

**Review by boherm — DISMISSED** [review]

**Comment by djoelleuch** [comment]
Hello @zuk3975  , Some checks were not successful 
could you please check , thanks !

**Comment by lartist** [comment]
Yes @djoelleuch I'm still working on it 👍

**Review by lartist — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by aniszr** [comment]
Hello @zuk3975 @jolelievre 

This branch has many conflicts , could you please check and resolve it please !

 thanks !

**Review by jolelievre — DISMISSED** [review]
Thanks @zuk3975

**Review by lartist — DISMISSED** [review]

**Review by boubkerbribri — DISMISSED** [review]
LGTM UI tests

**Comment by sallemiines** [comment]
Hello @zuk3975 

[Tests autos](https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5864913868) are failed in **Orders** and **catalog** 
Please check 
Waiting for your feedback 

Thank you

**Comment by zuk3975** [comment]
> Hello @zuk3975
> 
> [Tests autos](https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5864913868) are failed in **Orders** and **catalog** Please check Waiting for your feedback
> 
> Thank you

ping @PrestaShop/qa-automation

**Comment by boubkerbribri** [comment]
> > Hello @zuk3975
> > [Tests autos](https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5864913868) are failed in **Orders** and **catalog** Please check Waiting for your feedback
> > Thank you
> 
> ping @PrestaShop/qa-automation

The last test is fixed, you can restart your tests
PS: BTW I did a rebase too

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by boubkerbribri** [comment]
Restarting tests here https://github.com/boubkerbribri/ga.tests.ui.pr/actions/runs/5890681984

**Review by jolelievre — APPROVED** [review]

**Comment by boubkerbribri** [comment]
@PrestaShop/qa-functional (@sallemiines) I fixed tests and restart them, is it a QA :white_check_mark: from your side ?

**Review by aniszr — COMMENTED** [review]
Hello @zuk3975 

I tested your PR, almost all of the Feature options are good!
I noticed two different behaviors when trying to export Features:

- Exporting from general Features list :heavy_check_mark: 
image

- Exporting from inside a Feature (the previous Feature should be deleted ):x:

See attached screenrecord:

https://github.com/PrestaShop/PrestaShop/assets/92626242/ec181244-f9d3-4aa0-961b-f371c0553419

Thanks!

**Comment by zuk3975** [comment]
Im sorry, but Im really busy these days and I dont know if i will ever find the time to fix it. Maybe someone else could take over, or maybe it could be resolved in separate issue so all the work of this pr is not lost?

**Comment by MatShir** [comment]
Let's merge it, and fix [the issue](https://github.com/PrestaShop/PrestaShop/issues/33862) into another PR ! Thanks everyone 🥳

**Comment by MatShir** [comment]
_The comment above was validated and sponsored by @Robin-Fischer-PS_

**Comment by jolelievre** [comment]
Thanks @zuk3975

**Pull request merged**
