### PR TITLE
Fixed Modal "View pack content"

### LINKED ISSUE #20444: BO - Orders page - Cannot view pack content
#### Describe the bug

In the BO => Orders => Order details page => we cannot view pack content

#### Expected behavior

Pack content should be displayed after clicking on the "View pack content" button

#### Steps to Reproduce

1. Create a Pack product which contains some other standard products
2. Go to FO, add this pack to the cart and complete checkout
3. Go to BO => Orders => last created order details page
4. Click on "View pack content" button
5. See error => Nothing happens 

**Screenshots**

image

#### Additional information

* PrestaShop version: 1.7.7.x
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Fixed Modal "View pack content"
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20444
| How to test?  | 1. Create a Pack product which contains some other standard products<br>2. Go to FO, add this pack to the cart and complete checkout<br>3. Go to BO => Orders => last created order details page<br>4. Click on "View pack content" button<br>5. **BEFORE** See error => Nothing happens<br>5. **AFTER** Modal opens

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20461)

### CODE REVIEW

**Comment by NeOMakinG** [comment]
theme.css isnt related to this at all

**Comment by Progi1984** [comment]
@NeOMakinG I build assets :p and the branch 177x has not assets up to date :(

**Comment by NeOMakinG** [comment]
It's ok for me

**Review by NeOMakinG — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

It is OK :heavy_check_mark: 
image

Thanks!

**Comment by Progi1984** [comment]
Thanks @khouloudbelguith

**Pull request merged**
