### PR TITLE
Fix exception 'Template ::base.html.twig is not defined'

### LINKED ISSUE #31510: Exception thrown when handling an exception
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I get this in my error log:
> Exception thrown when handling an exception (Twig\Error\LoaderError: Template "::base.html.twig" is not defined in "@PrestaShop/Admin/Exception/error.html.twig" at line 26. at /home/www-data/ps/production/releases/20230220144730/vendor/twig/twig/src/Loader/ChainLoader.php line 99)

### Expected behavior

No error

### Steps to reproduce

The error is caused in my case by an unexpected exception in my own module. Nevertheless the exception that I submit here is thrown in Prestashop core, during error handling.

I'm not exactly sure how to reproduce it. I think it is possible to reproduce it, when
- we have a module with an admin controller
- when we add `throw new Exception('Provoked exception');` somewhere in the code of the module's admin controller.

### PrestaShop version(s) where the bug happened

8.0.1

### PHP version(s) where the bug happened

8.0

### If your bug is related to a module, specify its name and its version

_No response_

### LINKED ISSUE #31675: If `_PS_MODE_DEV_` = false, the endpoint `/admin-dev/new-api/` returns a 500 HTTP Code
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If `_PS_MODE_DEV_` = `true`, the endpoint `/admin-dev/new-api/` returns a 404 HTTP Code.
If `_PS_MODE_DEV_` = `false`, the endpoint `/admin-dev/new-api/` returns a 500 HTTP Code.

### Expected behavior

If `_PS_MODE_DEV_` = `true`, the endpoint `/admin-dev/new-api/` returns a 404 HTTP Code.
If `_PS_MODE_DEV_` = `false`, the endpoint `/admin-dev/new-api/` returns a 404 HTTP Code.

### Steps to reproduce

1. Create a file `config/defines_custom.inc.php`

```php
<?php

define('_PS_MODE_DEV_', false);
```

2. Request https://domain.tld/admin-dev/new-api/
3. The HTTP Code is 500 (and should be 404)

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fixes an exception during error handling
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Provoke an unexpected Exception in BO module
| Fixed ticket?     | Fixes #31510 Fixes #31675
| Related PRs       | -
| Sponsor company   | Société Biblique de Genève

### CODE REVIEW

**Review by lartist — DISMISSED** [review]

**Review by FabienPapet — DISMISSED** [review]

**Comment by kpodemski** [comment]
@FabienPapet issue has not been validated by QA, if you think it's a valid report you can comment on the issue to help QA 👍🏻

**Comment by kpodemski** [comment]
@PrestaShop/qa-team autotests should be enough for this one :)

**Comment by kpodemski** [comment]
https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/4283818833

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by florine2623** [comment]
ping @nesrineabdmouleh 
This PR only needs automated tests, 3 tests are failed. I believed the failed tests are known bugs.
Could you confirm ?
Thanks!

**Comment by nesrineabdmouleh** [comment]
> ping @nesrineabdmouleh This PR only needs automated tests, 3 tests are failed. I believed the failed tests are known bugs. Could you confirm ? Thanks!

@florine2623 The errors of Orders and Design are known bugs, but in FO it fails in another test. 
@kpodemski can you relaunch FO tests ?
Thank you :)

**Review by matks — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @lmeyer1 

Thanks for your PR 🚀 
I close and reopen the PR cause there was some failed checks and now it's all green ✅ 
Here's the link of launched auto tests: https://github.com/hibatallahAouadni/testing_pr/actions/runs/4355570265

As the issue was validated by a Dev, the PR should be tested by a Dev 😉 

Thanks!

**Comment by kpodemski** [comment]
@lmeyer1 Hello Lorenz, it's all good, I wanted to finally merge it, but after merging some other PR, there's a rebase needed. Could you do that?

**Review by jolelievre — DISMISSED** [review]
Hi @lmeyer1 

thanks for the fix, it also fixes another issue related to API. This blocks the nightly for 8.1.x so could you please rebase your PR and change the target of your branch to 8.1.x?

**Comment by lmeyer1** [comment]
@jolelievre Hello, I changed the target branch to `8.1.x`

**Review by kpodemski — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @lmeyer1 ,

Automated tests --> OK :heavy_check_mark: 
(https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4406722896) 
LGTM , it is QA approved :heavy_check_mark: 
Thank you !

**Comment by nicosomb** [comment]
Thank you @lmeyer1 and @djoelleuch.

**Pull request merged**
