### PR TITLE
Fix the display of textarea in the category page

### PR DESCRIPTION
**Pull request by Azouz-Jribi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | When trying to edit category, the textarea of meta description is wrongly displayed.
| Type?         | bug fix 
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-9397
| How to test?  | Go to BO > Catalog > Categories > Edit categorie, and check if the textarea of meta description is correctly displayed.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8394)

### CODE REVIEW

**Comment by LittleBigDev** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/prestashop/prestashop/8394#-:-KyLjlV9okjdwWN6CBeM:bnfp4nl)*

**Review by LittleBigDev — APPROVED** [review]

**Comment by matks** [comment]
@marionf I think this bug was fixed at least by the migration of the page, but it's better to check.

**Comment by marionf** [comment]
I confirm, it's all good

capture d'écran_1982

**Comment by matks** [comment]
Hello,

I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.
Thank you for your contribution, we have checked and on 1.7 the bug is already fixed ✅ 

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

**Pull request closed without merging**
