### PR TITLE
Fix filtering by date in Movements page (stock section)

### LINKED ISSUE #28894: "Filter by date" doesn't work in the Movements page
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

In the Stock page => Movements tab => when we try to use the "advanced filters", the "Filter by date" doesn't work

https://user-images.githubusercontent.com/16067358/176204799-3a25da30-6a4a-4ce5-8490-803c339e473d.mp4

### Expected behavior

_No response_

### Steps to reproduce

1. Go to BO => Stocks Page => Movements page
2. Try to filter by an old date
3. Nothing happens => the page is refreshed

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

8.1, 7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Fix filtering by date in Movements page (stock section)
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28894 
| Related PRs       | ~
| How to test?      | Follow the issue
| Possible impacts? | ~

Ok, this was very tricky one! 

Despite the fact that the array was populated, when the ajax request was called, the params were not passed correctly 😶
Please take a look to this ss of the console
Screen shot 2022-07-15 at 12 48 19
One element in, but length value is 0 🤯

I spent a lot of time to understand how to populate `date_add` correctly and use the `event.dateType` variable as `index`, (I'm not a TS expert 😓), so I don't know if using a `Type` is the right approach, but is the only way that I found after hours 😊

Now, to make this PR better, I noticed a bug on timestamp, it should be without hours and minutes, I mean, for the "From" datepicker should be 00:01, and for the "To" datepicker should be 23:59, and I can't be able to understand how to do that on client side. I tried to add in the format the hours and minutes but the datepicker brokes 😕. I invoke the help of @NeOMakinG 😊

### CODE REVIEW

**Review by matks — DISMISSED** [review]
I'm a second-rate frontend developer but from my limited skills PR is valid 👍 providing the complexity of the bug

nice catch @marsaldev !

**Comment by NeOMakinG** [comment]
Getting a look today 👍

**Review by NeOMakinG — APPROVED** [review]
🍬

**Comment by marsaldev** [comment]
Thanks a lot @NeOMakinG!

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @marsaldev ,

Thanks for the PR!

I have a request for you ^^
For example, now I have this:
Screenshot 2022-07-19 at 17 58 38

"To" has a previous date than "From". Would it be possible to not allow that ?

Thanks!

**Comment by NeOMakinG** [comment]
> Hello @marsaldev ,
> 
> Thanks for the PR!
> 
> I have a request for you ^^ For example, now I have this: Screenshot 2022-07-19 at 17 58 38
> 
> "To" has a previous date than "From". Would it be possible to not allow that ?
> 
> Thanks!

@florine2623 It's possible but we should open an issue as an improvement and avoid blocking this PR which is a bugfix initially

Not because we have some process but as a way to track it better in case we introduce a new bug by adding this improvement! Don't hesitate to assign it to me if you want

**Review by florine2623 — APPROVED** [review]
Of course, I'll do that ^^
It is QA ✅ then !

Thanks all

**Comment by marsaldev** [comment]
@florine2623 @NeOMakinG 
thanks a lot! 😊

**Comment by NeOMakinG** [comment]
Thanks @marsaldev @florine2623

**Pull request merged**
