### PR TITLE
Cast OrderProductForViewing - location to string for Memcached

### LINKED ISSUE #36126: Problems OrderProductForViewing "must be of type string (or int), null given" and Memcached
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

I had a problem with retrieving the stock location for products that are no longer available when viewing an old order. Normally, this should return false when the stock location is not found. But when the Memcached cache is active, the null value is returned, causing a fatal error. This must be linked to the fact that Memcached doesn't distinguish between null and false. 

To correct my specific problem, I added the following processing at the end of the setProductCurrentStock() method in /classes/order/Order.php:
```
if ($product['location'] === null) {
    $product['location'] = false;
}
```

This ensures that false is returned and not null. 

The following issues seem to be affected by a similar bug: 
[#22215](https://github.com/PrestaShop/PrestaShop/pull/22215)
[#35753](https://github.com/PrestaShop/PrestaShop/pull/35753)
[#35979](https://github.com/PrestaShop/PrestaShop/pull/35979)

### Expected behavior

_No response_

### Steps to reproduce

1. Enable Memcached cache
2. Create an order
3. Delete an ordered product from the catalog
4. View order

### PrestaShop version(s) where the bug happened

8.1.2

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.2.x
| Description?      | Description is in issue #36126 , already validated by @matks in this issue.
| Type?             | bug fix
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | Fixes #36126 
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Review by Hlavtox — DISMISSED** [review]
Just cast it:

`$product['location'] = (string) StockAvailable::getLocation($product['product_id'], $product['product_attribute_id'], (int) $this->id_shop);`

**Comment by ShaiMagal** [comment]
@Hlavtox I made it same like in issue #36126 where @matks ask for this PR ("_Would you submit a Pull Request with your code changes?_"), but the guy who opened task didn't responded (I think, he don't know how to do PR).

So I made PR same like in this issue same way.

**Comment by Hlavtox** [comment]
@ShaiMagal Just providing a shorter solution.

**Comment by ShaiMagal** [comment]
@Hlavtox edited at your request bro.

**Comment by ps-jarvis** [comment]
Hi, thanks for this contribution!

I found some issues with the Pull Request description:

* The `branch` should be `develop` or `8.1.x`. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#branch))
* The `How to test` shouldn&#039;t be empty. ([Read explanation](https://devdocs.prestashop-project.org/9/contribute/contribution-guidelines/pull-requests/#how-to-test))

Would you mind having a look at it? This will help us understand how interesting your contribution is, thank you very much!
### About linked issues
Please consider opening an issue before submitting a Pull Request:
* If it's a bug fix, it helps maintainers verify that the bug is effectively due to a defect in the code, and that it hasn't been fixed already.
* It can help trigger a discussion about the best implementation path before a single line of code is written.
* It may lead the Core Product team to mark that issue as a priority, further attracting the maintainers' attention.

(Note: this is an automated message, but answering it will reach a real human)

**Comment by matks** [comment]
Hi, I have changed the target branch to 8.2.x because of https://github.com/PrestaShop/PrestaShop/issues/36758

**Review by matks — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by matks** [comment]
I reproduced the issue https://github.com/PrestaShop/PrestaShop/issues/36126 and verified the bugfix with Memcached

**Comment by matks** [comment]
Thank you @ShaiMagal

**Pull request merged**
