### PR TITLE
Changed message when PHP version is not correct

### LINKED ISSUE #29730: Installer is not very clear about required php version
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I tried to install Prestashop 1.7.8.7 with PHP 8.0.x version, but the installer tells me "PrestaShop requires PHP 7.4 or lower."

Capture d’écran 2022-09-23 à 14 23 55

OK. 
So I switched to PHP 5.6.x (which is lower than 7.4 😁)

But the installer tells me "but PrestaShop requires PHP 7.1.3 or newer." 

Capture d’écran 2022-09-23 à 14 35 03

### Expected behavior

PrestaShop installer should give the correct range of accepted PHP versions. 

### Steps to reproduce

1. Have a PHP 8.0 version
2. Try to install PrestaShop 
3. Switch to PHP 5.6
4. Try to install PrestaShop 

### PrestaShop version(s) where the bug happened

1.7.8.7

### PHP version(s) where the bug happened

PHP 5.6 or newer :D 

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           |  develop
| Description?      | The installer was not very clear about PHP version
| Type?             | new feature 
| Category?         | IN 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29730
| Related PRs       | 
| How to test?      | Try to install PHP with an unsupported PHP version. 
| Possible impacts? | 

Now the installer is more clear: 

Capture d’écran 2022-09-27 à 09 36 51
Capture d’écran 2022-09-27 à 09 37 42

### CODE REVIEW

**Review by FabienPapet — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
The first change - `or newer` => `between` is good, but you removed the `downgrade`/`upgrade `wording. 🤔

**Review by kpodemski — COMMENTED** [review]
The code is good, but I think it should go on the `develop` branch. It's an improvement.

**Comment by nicosomb** [comment]
@kpodemski as your prefer. Who can tell me if I need to target the `develop` branch?

**Comment by atomiix** [comment]
@nicosomb as it's not a regression nor a security fix, you should target `develop` ;)

**Comment by nicosomb** [comment]
@atomiix @kpodemski done.

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello 

I would like to validate if this PR should be fixed on `develop` or `1.7.8.x` branch

image


Also, Could you please check the CI before testing it ?

image

Thank You!

**Comment by matks** [comment]
@HanaRebaiQA The label `1.7.8.x` was wrongly added to the PR. I removed it. This PR should be merged inside `develop`.

**Comment by matks** [comment]
Closing and reopening to see if we can reset CI

**Review by kpodemski — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @nicosomb 

I have checked this PR. The feature is well added. 

Here the checked list : 


- Automated tests : OK

- Check with php versions below **7.2.5** with **Web** and **CLI** installations:

  - php 5.6 : OK
  - php 7.1 : OK
  - php 7.2.3 : OK

image

image

image

image

image

image

- Check with php versions between **7.2.5 and 8.1 included** with **Web** and **CLI** installations: 

  - php 7.2.5 : OK
  - php 7.4 : OK
  - php 8.0 : OK
  - php 8.1.9 : OK
  - php 8.1.11 : OK

image

image

  - php 8.2-rc : Could not be installed (not released yet!)

image

So, it's QA :heavy_check_mark: 

Thank You!

**Pull request merged**
