### PR TITLE
Functional tests - Fix random error in 'FO > Quick view product'

### PR DESCRIPTION
**Pull request by nesrineabdmouleh**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Fix random error in 'FO > Quick view product'
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | no need
| UI Tests          | 
| Fixed issue or discussion?     | no
| Related PRs       | no
| Sponsor company   |

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by boubkerbribri** [comment]
Should we merge it, even if there is no new 1.7.8.X version ?

**Comment by Progi1984** [comment]
@boubkerbribri I think @nesrineabdmouleh wait that the nightly for 1.7.8.x is fixed.

**Comment by boubkerbribri** [comment]
Thanks @nesrineabdmouleh

**Comment by matks** [comment]
Milestone is not 8.1.2 😛

**Comment by matks** [comment]
Milestone should be 1.7.8.11 if one day we publish such a version 😄

**Pull request merged**
