### PR TITLE
Move getBulkActions inside a dedicated trait

### PR DESCRIPTION
**Pull request by FabienPapet**
Signed-off-by: Fabien Papet <fabien.papet@gmail.com>

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Discussed with @zuk3975, I refactored some code to avoid putting it inside `FrameworkBundleAdminController`, not covered by BC promise as this method has been added last month in `develop`. This is to prefer composition over in inheritance, to reduce coupling and having unused methods inside `FrameworkBundleAdminController`
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI , automated tests and nightly 🟢

### CODE REVIEW

**Review by zuk3975 — APPROVED** [review]

**Review by lartist — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
@kpodemski & @FabienPapet I see that we should just check CI , automated tests and nightly 🟢 in the How to test of this PR, so there's no need doing QA?

**Comment by FabienPapet** [comment]
We just moved some code from one place to another. Tests should be sufficient IMO

**Review by nicosomb — APPROVED** [review]

**Comment by zuk3975** [comment]
As Fabien said there are no UI changes, if something is wrong then hopefully the tests will show (I don't think its worth QA time, as the risk is quite low). But if you really want to be sure, it could be tested briefly by going through all affected grids and seeing that bulk action works as expected. (The affected pages are the migrated product, stores, cart rules and features).

**Comment by FabienPapet** [comment]
Tests: https://github.com/FabienPapet/ga.tests.ui.pr/actions/runs/4891644952

**Comment by zuk3975** [comment]
many UI tests have failed (too many :smile: so I think its false alarm), restarting on recently updated tests branch.
https://github.com/zuk3975/testing_pr/actions/runs/4938137555

**Comment by zuk3975** [comment]
I've just manually tested all the related grids: Features, Stores, Product, Cart Rules. Bulk actions works as expected, so it is a QA :heavy_check_mark: 
Btw the UI tests seems to fail, but I highly doubt that those failures are related to this PR :zany_face:

**Comment by FabienPapet** [comment]
Thank you @zuk3975 for testing :)

**Pull request merged**
