### PR TITLE
Fixes to identifiable object form hooks

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | This PR removes reference from form data passed into hook and fixes hook naming.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | I think QA is not needed, see code changes.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13410)

### CODE REVIEW

**Comment by sarjon** [comment]
@matks wdyt?

**Comment by matks** [comment]
Is it a fix for https://github.com/PrestaShop/PrestaShop/issues/10412 ?

**Comment by sarjon** [comment]
> Is it a fix for #10412 ?

Nope, not even close. :smiley:

**Comment by matks** [comment]
I dont understand the goal 🤔 of this PR
- Why remove the data reference passing ? This is necessary for the hook system ?
- About the camelize: good idea, we should probably apply it everywhere, isn't it ?

**Comment by sarjon** [comment]
> Why remove the data reference passing ? This is necessary for the hook system ?

If you look closely, you'll see that `$data` is never used below hook, so passing it as a reference does not make sense, but adds confusion instead.

> About the camelize: good idea, we should probably apply it everywhere, isn't it ?

Definitely, we don't want to encourage function names like `public function hookMy_hook()`, right?

**Comment by matks** [comment]
> > Why remove the data reference passing ? This is necessary for the hook system ?
> 
> If you look closely, you'll see that `$data` is never used below hook, so passing it as a reference does not make sense, but adds confusion instead.

I think the bug you spotted ( 👏 ) is even worse actually 🤔 
This hook is useless as it is. We should either pass it `&$formBuilder` or call the hook before `buildForm(..., $data, ...)` in order to make sure modifying `$data` is useful

**Comment by sarjon** [comment]
> This hook is useless as it is

No, not at all, you can modify `$formBuilder` from modules as objects in PHP are passed "by reference" generally speaking. So `&` is not needed.

Refere to https://www.php.net/manual/en/language.oop5.references.php

**Comment by matks** [comment]
> > This hook is useless as it is
> 
> No, not at all, you can modify `$formBuilder` from modules as objects in PHP are passed "by reference" generally speaking. So `&` is not needed.
> 
> Refere to https://www.php.net/manual/en/language.oop5.references.php

You're right. And I actually know that 😐 my brain just got full retard. Sorry

**Comment by matks** [comment]
> If you look closely, you'll see that `$data` is never used below hook, so passing it as a reference does not make sense, but adds confusion instead.

I think we should put a comment explaining that in the code. It's not obvious, and I asked why, then more people will ask too

**Comment by sarjon** [comment]
Do we really have do document this? :thinking: 

I don't think it's worth documenting something that's obvious, you didn't see because git difference did not show whole code.

**Comment by matks** [comment]
> Do we really have do document this? 🤔
> 
> I don't think it's worth documenting something that's obvious, you didn't see because git difference did not show whole code.

No I asked why because every hook passes `&$data` so when I saw this one it really looked like a mistake. This hook does not comply with the implicit rule `pass data by reference to hooks` 😉 it deserves an explanation so that people do not mistake it with a bug.

**Comment by sarjon** [comment]
Now I think if we need it here at all. You can access form data via `$formBuilder->getData()`. :thinking:

**Comment by matks** [comment]
> Now I think if we need it here at all. You can access form data via `$formBuilder->getData()`. 🤔

If we do that we must write a comment for it. We cannot expect all people to guess that data can be extracted from the `$formBuilder`, and a small comment will help these people 😊

**Comment by sarjon** [comment]
> If we do that we must write a comment for it. We cannot expect all people to guess that data can be extracted from the $formBuilder, and a small comment will help these people

I agree with you, but it should be mentioned in Docs rather in code imo.

**Comment by PierreRambaud** [comment]
@sarjon I think @matks 's right! Adding this kind of comment in the doc is useless, don't rewrite something already exists in another documentation.
Better to add a simple 
```
/**
 * @see https://www.php.net/manual/en/language.oop5.references.php
 */
```

or something like in the code, not everyone know everything about OOP :)

**Comment by sarjon** [comment]
Closing, as it seems that it was fixed in https://github.com/PrestaShop/PrestaShop/pull/13643

**Pull request closed without merging**
