### PR TITLE
No image available in German: fix typo.

### LINKED ISSUE #23836: Product image "no image available" incorrect in German
#### Describe the bug

The texts on the German default images are incorrect.
/img/p/de.jpg has the text "No image available"
/img/p/de-*-default.jpg have the text "Kein bild verfügbar"

#### Expected behavior

The correct text would be: "Kein Bild verfügbar", 'B' in upper case.

#### Steps to reproduce

1. Install German language
2. Create a product
3. Do not put an image in the product
4. See the product in front

#### Additional information

* PrestaShop version: 1.7.7.2

I'm not sure if this is the correct place to submit this issue, since it is related to localisation.

### PR DESCRIPTION
**Pull request by lmeyer1**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This pull request fixes the typo in German images. see issue #23836
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23836.
| How to test?      | Look at images. No automation possible.
| Possible impacts? | None

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23903)

### CODE REVIEW

**Comment by lmeyer1** [comment]
If I understand well the log of the failed check, the reason was that the timeout of 6 minutes was reached for the installation of the shop. This is certainly not related to my changes.
Is it possible to rerun the checks?

**Review by Progi1984 — DISMISSED** [review]

**Comment by atomiix** [comment]
Hi @lmeyer1 nice catch! Can you try to optimize those images? Most of them are now 3x bigger that before 😄

**Comment by lmeyer1** [comment]
I have reduced the size by removing thumbnail, exif tags, no progressive jpg, and still 89% of quality.

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @lmeyer1 & @sarahdib

**Pull request merged**
