### PR TITLE
Change icon of module with missing logo

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | This PR changes the default icon of a module without a logo. I used material icon puzzle, the same one as in the left menu.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Upload [ps_success.zip](https://github.com/PrestaShop/PrestaShop/files/10413649/ps_success.zip), see that the icon is a puzzle instead of ugly question mark for ants.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

iconbefore
aftericon

### CODE REVIEW

**Comment by kpodemski** [comment]
What do you think @MatShir ?

**Comment by kpodemski** [comment]
@Hlavtox I think you should use a new file. There's a risk that somebody is using old file for other purposes.

**Comment by Hlavtox** [comment]
@kpodemski Fixed, I made a new file. 👍

**Comment by MatShir** [comment]
LGTM ! but have you discussed with design maybe they can do a cooler logo 🤷‍♂️

**Comment by Hlavtox** [comment]
@MatShir I would like to have it sooner than 2024 😄

**Comment by kpodemski** [comment]
@Hlavtox you forgot to upload a file :D

**Comment by Hlavtox** [comment]
@kpodemski Fixed ✅

**Review by kpodemski — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I have tested your PR and it's OK for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by Hlavtox** [comment]
Thanks @paulnoelcholot! 🚀🚀🚀

**Pull request merged**
