### PR TITLE
Fix notice on brands page

### PR DESCRIPTION
**Pull request by SebBareyre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix notice `Undefined index: nb_products` on brands page if there is no products linked to any manufacturer
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | BOOM-2663
| How to test?  |visit brands page with at least a brand but without any products linked to a brand

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9083)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Sorry I can't reproduce, do you use some modules? In which file `Undefined index: nb_products` is displayed?

**Comment by SebBareyre** [comment]
I don't use any modules here. The error appear here on ManufacturerController.php line 187

**Review by PierreRambaud — DISMISSED** [review]
Thanks I understand know :)

**Review by PrestaEdit — DISMISSED** [review]

**Comment by eternoendless** [comment]
Hi @SebBareyre 

We can make this available in 1.7.4.1 if you rebase into 1.7.4.x

**Comment by SebBareyre** [comment]
done.

**Comment by Quetzacoalt91** [comment]
You should make a interactive rebase (i.e `git rebase -i 1.7.4.x`) and remove all commits not related to this PR. :)

**Comment by SebBareyre** [comment]
I post a new pull request here : https://github.com/PrestaShop/PrestaShop/pull/9138

**Pull request closed without merging**
