### PR TITLE
Remove rebuild of SymfonyRequirements file after every composer run

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | We had to modify SymfonyRequirements.php to make it compatible with PHP 7.2 because Sensio won't. However, it was being overwritten by composer on each run. This PR stops it from being overwritten.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | No test needed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10837)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
wait!

you also need to remove the call in "post-install-cmd" block of composer

**Comment by PierreRambaud** [comment]
Done =)

**Review by PierreRambaud — APPROVED** [review]

**Review by mickaelandrieu — APPROVED** [review]

**Comment by eternoendless** [comment]
Nice catch @mickaelandrieu

**Comment by Quetzacoalt91** [comment]
Tests are failing. :)

**Comment by PierreRambaud** [comment]
Thanks @eternoendless

**Pull request merged**
