### PR TITLE
Fixed delete a shop (multistore)

### PR DESCRIPTION
**Pull request by aleeks**
| Questions | Answers |
| --- | --- |
| Branch? | Develop |
| Description? | Edit entities (Attribute, AttributeGroup, Lang) to adapt foreign keys |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1296 |
| How to test? | install a clean version of prestashop, activate multistore, add a new store & delete him |

### CODE REVIEW

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by mickaelandrieu** [comment]
Thank you @aleeks !

**Comment by beginner1000** [comment]
Hi Dear Developers,

I have the same issue, i have created multi shop by using Prestashop's MultiStore feature. The issues is: 1, my created multi shop is showing as main shop, 2: My all products are out of stock. 3: and my product category list is not showing all. I was kind of felt happy when i found your code here :) but i dont know where i need to make all those changes, i mean file location and the codes should be changed?
Please guide me.

Thank you very much

**Comment by xBorderie** [comment]
Hi @beginner1000,

GitHub is where development happens. It is not really the place to ask support question; that's [the PrestaShop community forum](http://www.prestashop.com/forums/)'s role :)

Are you saying that you want to delete one of your shop in order to solve your issues?

I would recommend upgrade to the latest version of PrestaShop, rather than modifying files manually. [The latest version is 1.7.0.4](https://www.prestashop.com/en/developers-versions).

Note that the code changes presented here are only for PrestaShop 1.7. If you use v1.6, these won't apply.

**Comment by beginner1000** [comment]
Hi xBorderie,

Thank you for reply, appreciated. And yes i have realized that but forums are not helping. Its nearly one month already, the multi shop issues still there. If there are any solution for deleting multi shop, would be appreciated.

Thank you again and hope you will reply

**Pull request merged**
