### PR TITLE
Improve exception checking in Behat tests

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Most of the time when an exception is raised in Behat tests it blocks the workflow and we know the test is failing But since we sometimes need to assert that exceptions are thrown some CQRS commands are wrapped in try/catch blocks so that we can store the exception thrown and assert its content in the next step<br>The problem is that with this some failing commands could be ignored if we don't check the exception in the next step so we added a manual step to check that no exception was thrown But it's not convenient to add this step everytime and we could forget some<br><br>This PR adds an automatic management of this exception checking, it stores any exception that might have been thrown after each step, and in the next step it ensure that this exception has been correctly asserted (and therefore clean) if not it means the exception was not expected so we consider the test as failed With this new method no exception can be ignored now even they were wrongly caught
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | CI tests green
| Possible impacts? | Stricter and more stable tests

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27002)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
The behavior is correct but the logic is inserted into the AbstractDomainFeatureContext which becomes bigger and bigger. Should we isolate the logic in a dedicated class or trait?

**Comment by jolelievre** [comment]
@matks  I thought about it, but it means we have to always associate this other Context when we use the lastException So if we forget to set it in the suite contexts then the whole feature is ignored and we go back to the previous state where exception were ignored sometimes

At least with this if you use `setLastException` you have the guaranty that everything is correctly checked

We could split the abstract into several classes or use traits, but I'm not sure it brings much value It can be refactored later if needed that's not the point of this PR

**Review by matks — APPROVED** [review]
Then OK for me ✅

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @jolelievre

**Pull request merged**
