### PR TITLE
Fix cookie collisions from PR # 14116 and improve overall security

### PR DESCRIPTION
**Pull request by mvorisek**
Fix cookie collisions introduced in https://github.com/PrestaShop/PrestaShop/pull/14116 and several security improvements.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | See commit descriptions.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | No new functionality, no need for extra tests. You should be able to login & continue to navigate in FO and BO

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14403)

### CODE REVIEW

**Comment by mvorisek** [comment]
How to get details about this test failure https://travis-ci.org/PrestaShop/PrestaShop/jobs/551683586 ?

**Comment by matks** [comment]
> How to get details about this test failure https://travis-ci.org/PrestaShop/PrestaShop/jobs/551683586 ?

Unfortunately that's a false positive, we've had a lot recently (see https://github.com/PrestaShop/PrestaShop/issues/14384). I restart the build

**Comment by mvorisek** [comment]
@matks Great, tests passed now. Please review and merge the security improvements, they are described in 4 different commits. Thanks.

**Comment by mvorisek** [comment]
Tests passed. Can someone review and merge?

**Comment by PierreRambaud** [comment]
Hi,
Can you please complete the description of your pull request with this template: https://github.com/PrestaShop/PrestaShop/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

I'm in favor of making this change but the only problem I see is if someone already have a `_COOKIE_IV_` defined in his configuration he can't connect anymore. Same with `_COOKIE_KEY_`.
WDYT @Quetzacoalt91 @matks ?

Kind Regards

**Comment by mvorisek** [comment]
@PierreRambaud I have added the PR template. Yes, all existing cookie will not be honored/discarded. But only once (only once when site owner updates the PS core).

**Comment by PierreRambaud** [comment]
You're right, don't know why my session won't get back when I tried :thinking:

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @mvorisek

**Pull request merged**
