### PR TITLE
Symfony 6 - Fix user deprecations

### PR DESCRIPTION
**Pull request by FabienPapet**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix some code deprecated in Symfony 5 to prepare for Sf6. Also fixes some PHPUnit warnings that prevent upgrading it.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | yes
| How to test?      | CI 🟢 + [automated tests](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5784617331)

### CODE REVIEW

**Review by M0rgan01 — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @FabienPapet and @lartist

**Comment by jolelievre** [comment]
Running auto tests https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5784617331

**Review by boherm — DISMISSED** [review]

**Comment by jolelievre** [comment]
Detected by automated tests, the [API tests are failing](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5784617331/job/15681332089) Here is the log content that seems to be related with the error:

```
[2023-08-07T16:44:52.468107+02:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getUserIdentifier" of class "PrestaShop\Module\KeycloakConnectorDemo\OAuth2\KeyCloakUser"." at /var/www/html/src/PrestaShopBundle/Service/DataProvider/UserProvider.php line 72 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"getUserIdentifier\" of class \"PrestaShop\\Module\\KeycloakConnectorDemo\\OAuth2\\KeyCloakUser\". at /var/www/html/src/PrestaShopBundle/Service/DataProvider/UserProvider.php:72)"} []
```

Not sure if the problem is from the keycloak module that needs to be adapted or if it's something missing in the core (maybe check the presence of the method and/or use a fallback). It seems weird the it fails here because of the module though, it seems like the module itself would be overriden the service injected via `UserProviderInterface` in our `src/PrestaShopBundle/Service/DataProvider/UserProvider` class?

Anyway this should be looked into.

**Comment by jolelievre** [comment]
New workflow after rebase and fix inside the keycloak module https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5798909772

**Review by jolelievre — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @FabienPapet @jolelievre

**Pull request merged**
