### PR TITLE
Add `id_reference` field in `Carriers` list

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add `id_reference` field in `Carriers` list.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See the screen
| UI Tests          | N/A
| Fixed issue or discussion?     | N/A
| Related PRs       | N/A
| Sponsor company   | Evolutive

Capture d’écran du 2023-11-21 10-52-16

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Comment by ShaiMagal** [comment]
@PululuK Why shop owners should see carrier id_reference? What is purpose of this?

**Review by kpodemski — CHANGES_REQUESTED** [review]
Do you have any valid scenario where it's merchant who needs to see id_reference?

**Review by ShaiMagal — CHANGES_REQUESTED** [review]
Why shop owners should see carrier id_reference? What is purpose of this?

EDIT:
Maybe it can be confusing for eshop owners to see "id_reference", they don't know what is it used for.

**Comment by kpodemski** [comment]
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
