### PR TITLE
Fix product information leak on the front office

### PR DESCRIPTION
**Pull request by kompilorb**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.2.x
| Description?  | leaks sensible cart product detail (wholesale price, supplier)
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3953
| How to test?  | View card product and product vars in template

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8433)

### CODE REVIEW

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @kompilorb

**Comment by doekia** [comment]
a part from wholesale_price, why pruning off id_supplier? how this leaks any information - critical ?

**Comment by DavidEschmeyer** [comment]
some people don't want to let people know the suppliers.  Supplier not to be confused with manufacturer/brand

**Comment by doekia** [comment]
an id discloses nothing about the supplier name unless you have activated the supplier url, in with case the supplier is disclosed in clear on this page. Pruning the id prevent extra processing to adopt a different view should this or that supplier is at stake? e.i: changing the shpiping delay for instance

**Comment by iqit-commerce** [comment]
Why cover is not added to allowed propertires?! it is breaking autocomplete search. I created pr #8447 which brings it back

**Comment by reho** [comment]
I've checked the pull and I think there is some problem: when cleaning the cart but after used the original again in the $templateVars (line 511). There should be $cleancart instead of  $this->cart_presenter->present($this->context->cart).

**Comment by eternoendless** [comment]
Fixed here: https://github.com/PrestaShop/PrestaShop/pull/8803

**Pull request merged**
