### PR TITLE
Disable e2e tests related to Addons for 1.7.4.x

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Remove install modules in e2e tests because addons doesn't have 1.7.4 version
| Type?         | bug fix
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Wait for travis build.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9070)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Can't do anything for Codacy, all globals variables are registered in the same way :/

**Comment by fatmaBouchekoua** [comment]
Hello @PierreRambaud ,
can you add a description for the new argument in the Readme file, please?
You have to rename your commits and add "TE:" at the beginning.

**Comment by eternoendless** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[tests/E2E/README.md, line 91 at r1](https://reviewable.io/reviews/prestashop/prestashop/9070#-LCYyAJ8B9Zt6tVfFnIy:-LCYyAJ91lsGzlG2vzHg:b70cy1) ([raw file](https://github.com/prestashop/prestashop/blob/c32b8a14df28252facbad4d293b69df3045c7cb8/tests/E2E/README.md#L91)):*
> ```Markdown
> * **MODULE**: **(Optional)** Module technical name to install (default to "gadwords")
> * **INSTALL**: **(Optional)** Boolean option : set it to **true** if you want to run the installation script (default to **false**)
> * **DISABLE_ADDONS**: **(Optional)** Boolean option : set it to **true** if you want disable check with Addons API (default to **false**)
> ```

Can we do it the other way around? `TEST_ADDONS = false` instead of `DISABLE_ADDONS = true`

---

*[tests/E2E/test/globals.webdriverio.js, line 19 at r1](https://reviewable.io/reviews/prestashop/prestashop/9070#-LCYySCOCIaXVRLifqj8:-LCYySCOCIaXVRLifqj9:b-l2erzq) ([raw file](https://github.com/prestashop/prestashop/blob/c32b8a14df28252facbad4d293b69df3045c7cb8/tests/E2E/test/globals.webdriverio.js#L19)):*
> ```JavaScript
> global.selenium_url = argv.SELENIUM;
> global.module_tech_name = argv.MODULE || "gadwords";
> global.disable_addons = !!argv.DISABLE_ADDONS; //Cast as boolean
> ```

If we inverse this value, make it default to true

---

*[tests/E2E/test/campaigns/high/10_module/2_cross_selling_module.js, line 13 at r1](https://reviewable.io/reviews/prestashop/prestashop/9070#-LCYya_0-XT4AgENfMjg:-LCYya_0-XT4AgENfMjh:b-9ww48r) ([raw file](https://github.com/prestashop/prestashop/blob/c32b8a14df28252facbad4d293b69df3045c7cb8/tests/E2E/test/campaigns/high/10_module/2_cross_selling_module.js#L13)):*
> ```JavaScript
>   }, 'common_client');
> 
>   if (disable_addons) {
> ```

Try using `global.disable_addons`

---


*Comments from [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9070)*

**Comment by eternoendless** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9070#-:-LCZV_73DXX40g3a8plo:bnfp4nl)*

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @PierreRambaud

**Pull request merged**
