### PR TITLE
Fix unclosed <p> html tag

### LINKED ISSUE #15477: Fixed a little html error in product.tpl
Hi
if you open the file
/classic/templates/catalog/product.tpl
at line 213
the final p tag is not closed in the right mode, it is missing ">"
it should be

`<p>{$attachment.description}</p>`

not like now

`<p>{$attachment.description}</p`

bye

**Screenshots**

**Additional information**
PrestaShop version: N/A1.7.6.1
PHP version: 7.0

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | @maofree found bad html tag
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15477 
| How to test?  | Nothing must be broken in product list.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15512)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
Thank you @davidglezz

**Comment by matks** [comment]
Closing and re-opening the PR to re-start Travis as we have migrated from travis-ci.org to travis-ci.com and this PR got lost in the migration (apparently)

**Comment by matks** [comment]
Travis is happy 🎶

**Comment by matks** [comment]
And thanks @maofree too 😄

**Pull request merged**
