### PR TITLE
[WIP] Add product pack items to checkout and cart page

### LINKED ISSUE #19587: Missing information for pack products
Hello,
I use PS 1.7.6.5 and there are missing information for product type = Pack:
- in shopping cart
- in final summary 
- in pdf - invoice, credit note, delivery slip...

There is always displayed only name of the product pack, but I'd like to display also the names of products which are contained in the pack. Then it would be much easier to check it if there are all information. 
It could be displayed similar how it is displayed in shopping cart for product with combinations. There are displayed combinations on the new lines.

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Cart, summary and invoice doesn't have product pack details
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19587.
| How to test?  | See issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/22093)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hey @NeOMakinG 
Still working on it?

**Comment by NeOMakinG** [comment]
It does require some backends

**Review by jolelievre — COMMENTED** [review]
@NeOMakinG I approve this for the form but you need to rebase it You're also saying that it needs some modif on the backend side? So you need a PHP developer to help you finish this?

**Comment by NeOMakinG** [comment]
> @NeOMakinG I approve this for the form but you need to rebase it You're also saying that it needs some modif on the backend side? So you need a PHP developer to help you finish this?

Yep, if you want we can take some time whenever you want to check together, I don't really remember why but I think the FO miss some datas in order to show related products everywhere we want to

**Comment by matks** [comment]
> Yep, if you want we can take some time whenever you want to check together, I don't really remember why but I think the FO miss some datas in order to show related products everywhere we want to

Hi @NeOMakinG I'm available to take some time together. We can first write a list of the places where backend data is missing. If list is short, let's do it quick together. If list is long, let's mark the related issue as blocked and wait for PM to prioritize this topic.

**Comment by NeOMakinG** [comment]
> > Yep, if you want we can take some time whenever you want to check together, I don't really remember why but I think the FO miss some datas in order to show related products everywhere we want to
> 
> Hi @NeOMakinG I'm available to take some time together. We can first write a list of the places where backend data is missing. If list is short, let's do it quick together. If list is long, let's mark the related issue as blocked and wait for PM to prioritize this topic.

Let's try to do this in the next weeks then!

**Comment by matks** [comment]
@NeOMakinG I'm here 👍

**Comment by matks** [comment]
@NeOMakinG do we give it another try ^^ ?

**Comment by Progi1984** [comment]
Hi @NeOMakinG,
Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.
Thanks!

**Pull request closed without merging**
