### PR TITLE
Use the same cookie filter prefix on module  admin controller override (legacy)

### LINKED ISSUE #29326: Filter not work properly on module admin controller override (legacy)
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Filter not work properly on module admin controller override (legacy).

### Expected behavior

When overloading the admin controller of a module, the filters must work correctly, and have the same behavior as on the original controller.

### Steps to reproduce

1 - Override an module with a legacy admin controller using a native listing system.

`/override/modules/mymodule/controllers/admin/AdminMyModule.php`

```php

<?php
class AdminMyModuleControllerOverride extends AdminMyModuleController{}
```

2 - Go to BO  and try to filter and see the following errors  :

- the current filter is not selected
- if you use the pagination the current filter is lost

### PrestaShop version(s) where the bug happened

N/A

### PHP version(s) where the bug happened

N/A

### If your bug is related to a module, specify its name and its version

N/A

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Filter not work properly on module admin controller override (legacy).
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/29326
| Related PRs       | N/A
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/29326
| Possible impacts? | N/A

### CODE REVIEW

**Comment by Hlavtox** [comment]
Nice! Just try to check if the page keeps working after uninstalling the module.

I think I played with legacy order page query once and got in a situation where I could not “unselect” filters in cookie. It just showed a permanent error and nothing else.

**Comment by PululuK** [comment]
> Nice! Just try to check if the page keeps working after uninstalling the module.

But... If the module is uninstalled, the controller will no longer exist 🤷🏿‍♂️

**Comment by Hlavtox** [comment]
I meant the module overriding the module 😄

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Hi @PululuK 

The related issue was closed. Do you plan to work on this feature and help QA reproduce the bug first? If not, let's close this PR.

**Comment by kpodemski** [comment]
Since we have had no news from you for more than 20 days, I'm closing this PR. Feel free to re-open it if you find the motivation to finish it. Don't hesitate to ping me if you have any questions or doubts.

**Pull request closed without merging**
