### PR TITLE
Fix OrderReturnState should not use soft delete

### LINKED ISSUE #20743: Bulk deletion on Return order statuses KO
#### Describe the bug

On BO > Parameters > Statuses, the deletion via Bulk Action of return statuses is not working. It was OK in 176.

Standard deletion is OK.

#### Steps to Reproduce

1. Go to BO > Shop Parameters > Order Settings > Statuses
2. Add a return status (if there is only the default one)
3. Select the status, bulk action, and click on "Delete selected"
4. Page is refreshed but the status is not deleted

**Screenshots**

https://drive.google.com/file/d/12CYlyZ9LH1Z36LGGvGVHvB-7dgS2gfc1/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7
* PHP version: N/A

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.7.x
| Description?  | Because `OrderReturnState` was handled the same way as `OrderState`, it was impossible to bulk delete order return states. This PR fixes it.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20743
| How to test?  | See #20743

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20796)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by ngodefroy** [comment]
TEST OK: 
Add a return status
Delete by bulk action 
The status is well deleted @sarahdib  confirmed. 
https://drive.google.com/file/d/1nq3AFUfWmVUX6XegmmJUWqZ1UaI2qCXQ/view

Note: I had the following issue on my case but it's apparently a problem on my side:
Capture d’écran 2020-09-01 à 11 32 46
&
https://drive.google.com/file/d/1UOOhWveX4QayPVHV5w1nqijNN-mftcfd/view

**Comment by PierreRambaud** [comment]
> TEST OK:
> Add a return status
> Delete by bulk action
> The status is well deleted @sarahdib confirmed.
> https://drive.google.com/file/d/1nq3AFUfWmVUX6XegmmJUWqZ1UaI2qCXQ/view
> 
> Note: I had the following issue on my case but it's apparently a problem on my side:
> Capture d’écran 2020-09-01 à 11 32 46
> &
> https://drive.google.com/file/d/1UOOhWveX4QayPVHV5w1nqijNN-mftcfd/view

I'm not sure it's a problem from your side since the table `order_return_state_lang` does not have any deleted field :sweat_smile:

**Comment by atomiix** [comment]
@PierreRambaud you're right, that's why I added a new commit to fix it 😄

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by ngodefroy** [comment]
This time its working just fine ! 
Thank you

**Comment by matks** [comment]
Thank you @atomiix for the PR and @ngodefroy for the QA 😉

**Pull request merged**
