### PR TITLE
Move position column template

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | The former macros for grid have been removed, we now use a twig extension which expects the column template to be in `@PrestaShop/Admin/Common/Grid/Columns/Content`
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Required for https://github.com/PrestaShop/PrestaShop/issues/9746
| How to test?  | 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10705)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by marionf** [comment]
@jolelievre Is there anything functional to test ? Or a specific page that I can check to see if there isn't regression ?

**Comment by jolelievre** [comment]
unfortunately no, this type of comun is only used in the ps_linklist module for now
and I don't know of any tests for the grid rendering, although there are a few Integration tests for some of the migrated controller but they don't test this specific type of column

**Comment by jolelievre** [comment]
sorry I misunderstood your question, I thought you were refering to automatic tests

so, you will need this PR modifications if you want to test the pending PR on the ps_linklist module https://github.com/PrestaShop/ps_linklist/pull/48

**Comment by PierreRambaud** [comment]
Thanks @jolelievre

**Pull request merged**
