### PR TITLE
ApplyProductCalculation and ProductlazyArray variable mismatch

### LINKED ISSUE #18225: ApplyProductCalculation and ProductlazyArray variable mismatch
If you want to display product availability in the cart, and show availability_message, it returns the wrong text. Like it always has the in-stock product, it doesn't show the message for available_later text. My client had products where the stock was 0. But in the cart, it displays an "in stock" label.

I tried it in PS 1.7.6.2 version. 
Long story short :D 
src/Adapter/Presenter/Product/ProductLazyArray.php:773 line always gets $product['quantity'] more than 0. In Cart class applyProductCalculations() method is clearly visible, that $product['quantity'] is overwriten by cart_quantity. 

`    protected function applyProductCalculations($row, $shopContext, $productQuantity = null)
    {
        if (null === $productQuantity) {
            $productQuantity = (int) $row['cart_quantity'];
        }

        if (isset($row['ecotax_attr']) && $row['ecotax_attr'] > 0) {
            $row['ecotax'] = (float) $row['ecotax_attr'];
        }

        $row['stock_quantity'] = (int) $row['quantity'];
        // for compatibility with 1.2 themes
        $row['quantity'] = $productQuantity;`
So in ProductLazyArray.php we need to take **stock_quantity instead** of **quantity**

#### Expected behavior
In cart show product availability when out of stock with the allowed order option. like _Delivery in 10-15days.

#### Steps to Reproduce

add product with 0 quantity, select Allow orders. 
Set Label when out of stock.
Add 
```
    {block name='product_availability'}
      <span id="product-availability">
        {if $product.show_availability && $product.availability_message}
          {if $product.availability == 'available'}
            <i class="material-icons rtl-no-flip product-available">&#xE5CA;</i>
          {elseif $product.availability == 'last_remaining_items'}
            <i class="material-icons product-last-items">&#xE002;</i>
          {else}
            <i class="material-icons product-unavailable">&#xE14B;</i>
          {/if}
          {$product.availability_message}
        {/if}
      </span>
    {/block}
``` 
in `templates/checkout/_partials/cart-detailed-product-line.tpl`

#### Additional information

* PrestaShop version: 1.7.6.2
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jonasburneika**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix for availability messages in cart
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #18225
| How to test?  | Check issue #18225

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/18226)

### CODE REVIEW

**Comment by Arman-Hosseini** [comment]
Please fill out the QA table and do not delete it.

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by jonasburneika** [comment]
> Please fill out the QA table and do not delete it.

Can someone point me to QA Table example? :/ I can't find it...

**Comment by Progi1984** [comment]
@jonasburneika Sorry, i just filled. Check the PR ;)

**Comment by khouloudbelguith** [comment]
Hi @jonasburneika,

It is OK
image
image
image

Thanks!

**Comment by PierreRambaud** [comment]
Thanks @jonasburneika

**Pull request merged**
