### PR TITLE
Do not use encodeURIComponent with POST data

### LINKED ISSUE #14604: When writing a private note strange characters are adding in the text
I just upgrade to the 1.7.6 version and now when I write a private note; for example before saving. After saving it adds strange characters to the text

Screenshot 2019-07-11 at 19 13 16

Screenshot 2019-07-11 at 19 13 34

_Originally posted by @01park in https://github.com/PrestaShop/PrestaShop/issues/13428#issuecomment-510596168_

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Do not use encodeURIComponent with POST data
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14604
| How to test?  | Follow ticket instruction.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14605)

### CODE REVIEW

**Comment by 01park** [comment]
Solution does not 100% worked. When I change the status of the order, in my case, to shipped. The strange % comes back.

**Comment by PierreRambaud** [comment]
I'm not able to reproduce even if I change the order status to `shipped`.
Do you clear your browser cache?

**Comment by 01park** [comment]
yes, I have clear browser.

Im no sure if I applied the fix correctly. I copied the code from here and paste this in the old one ( delete the wrong code). Was this correct?

**Comment by PierreRambaud** [comment]
I don't really know :/ Maybe you have module or anything else which alter data.

**Comment by 01park** [comment]
no, I just have the basic PS.

Would you be able to send me the file, that needs to be replaced / updated

**Comment by PierreRambaud** [comment]
Everything's on GitHub: https://github.com/PrestaShop/PrestaShop/blob/318d9f264f47a774c07cd3a378cf03e02a4b6630/js/admin.js

**Review by jolelievre — APPROVED** [review]
Nice job @PierreRambaud

**Comment by matks** [comment]
Thank you @PierreRambaud 

@01park if the issue remains on your side and you find what are the conditions required to reproduce the bug, please tell us 😉 we'll fix it in another PR

In the meantime, this PR solves the issue as far as we know so it's relevant to merge it

**Pull request merged**
