### PR TITLE
1.7.5.x

### LINKED ISSUE #13968: BO filemanager filter not working
Using filemanager in backoffice other https, the filter doesn't work. Due to mixed content a js include file is blocking.

1. Go to any rich text editor (page, product description...)
2. Click on insert picture Icon
3. Click on browse Icon
4. Enter text in filter box
5. Click on filter button, filter not working

If you go to browser inspector, you will see in console an error for a js request :
Mixed content error ... http://prestashop.domain.ext/adminXXXX/filemanager/dialog.php?type=1&descending=false&sort_by=&lang=fr&filter=keyword ... include.min.js

​PrestaShop version: 1.7.4.2 to 1.7.5.2
PHP version: 7.0 to 7.1

### PR DESCRIPTION
**Pull request by ComonSoft**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.5.x
| Description?  | Fix filter not working in filemanager in bakcoffice. Due to a mixed content blocking when using BO with https.
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #13968
| How to test?  | In any rich text editor in BO click on insert picture icon, and click on browse icon, enter text in filter input text and click on filter button

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13969)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Sorry @ComonSoft , this PR does not include any contribution from your account. A merge from 1.7.5.x to develop should be done manually in order to fix the existing conflicts.
I'm closing it as it can't be accepted as-is.

Kind regards

**Comment by ComonSoft** [comment]
ok how can I make a pull request to 1.7.5.x ?

**Comment by matks** [comment]
> ok how can I make a pull request to 1.7.5.x ?

Branch `1.7.5.x` is only used for critical issues as we are now about to release next 1.7.6 version.

I think it's better to either target the `1.7.6.x` (for bugfix) or target the `develop` version (feature) 😉

**Comment by ComonSoft** [comment]
Thanks a lot for your help, I saw this issue has been fixed in 1.7.6.x :-)

**Pull request closed without merging**
