### PR TITLE
Fix category access when group feature is disabled

### LINKED ISSUE #29820: Group access for categories is being checked even after disabling customer groups
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

PrestaShop keeps checking group access for categories, even after the "Customer groups" setting is set to NO.

### Expected behavior

Categories should be freely accessible after disabling "Customer groups"

### Steps to reproduce

1. Have some category assigned to only "customer" groups (visitor and guest unassigned).
2022-09-30 10_30_57-Edit_ Art • 1 7 8 Dev — Firefox Developer Edition
3. Have some product assigned only to this category and no other.
4. Try to visit both this category and this product while being a visitor - notice a "You do not have access..." error message.
5. Disable "Customer groups" in Performance settings.
6. Try to visit the category and product again, the product becomes visible, but the category page still gives a "You do not have access.." message.

### PrestaShop version(s) where the bug happened

1.7.8.x, 8.0.x

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix category access when group feature is disabled. See related issue for reproduce scenario.
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29820
| Related PRs       | 
| How to test?      | See issue
| Possible impacts? |

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]
You are fast @Hlavtox :D

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
> You are fast @Hlavtox :D

So are we

**Comment by matks** [comment]
Woups I went too fast. Let's wait for issue https://github.com/PrestaShop/PrestaShop/issues/29820 to be reproduced by QA (if we can't reproduce, we can't test) before sending the PR to QA 😅

**Review by matks — DISMISSED** [review]

**Comment by MhiriFaten** [comment]
Hello @Hlavtox ,

I tested the PR with **PHP 8.0** and **PHP 7.4** and I detected the following issues following the steps bellow:

1. Go to BO>Catalog> Categories.
2. Have a category assigned to only "customer" groups (visitor and guest unassigned).
3. Have some product assigned only to this category and no other.
4. Go to FO> try to visit this category while being a customer
5. try to visit a product of this category and sign out 
6. See error 
7. Go to BO>Performance settings.
8. Disable "Customer groups"
9. Go to FO> try to visit this category and product again and sign out
10. See error

**With PHP 7.4**  :x: 

[Untitled_ Oct 3, 2022 3_47 PM.webm](https://user-images.githubusercontent.com/111756615/193599926-06a1f5c8-c928-41d2-9b53-c62cba375500.webm)

**With PHP 8.0**  :x: 

[Untitled_ Oct 3, 2022 3_22 PM (1).webm](https://user-images.githubusercontent.com/111756615/193600336-17ec19b1-da34-4feb-8b8e-565d3bf5581b.webm)

Could you please check? :pray: 

Thank you

**Comment by Hlavtox** [comment]
@MhiriFaten That's a bug I made in my previous PR. I broke visiting disabled product. Not related to this PR. If it works on category pages, it works. 👍
This PR fixes that issue - https://github.com/PrestaShop/PrestaShop/pull/29822

**Comment by Hlavtox** [comment]
@PrestaShop/qa-team bump

**Comment by Hlavtox** [comment]
@MhiriFaten @hibatallahAouadni I rebased the PR onto the latest develop, the bug will no longer be there. You can now test the PR properly again. :)

**Comment by MhiriFaten** [comment]
Thank you, but before testing this PR it should be approved by @PrestaShop/prestashop-maintainers :+1:

**Review by matks — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by MhiriFaten — APPROVED** [review]
Hello @Hlavtox ,

It is ok 

Here is my checked list :

multilanguage: English + French + Arabic: OK :heavy_check_mark: 
different browsers: OK :heavy_check_mark: 
automated tests: OK :heavy_check_mark: 

[Untitled_ Oct 18, 2022 9_36 AM.webm](https://user-images.githubusercontent.com/111756615/196467276-f960fe64-c01f-4b44-8057-6f9373188c4f.webm)

Thank you :pray:

**Comment by kpodemski** [comment]
Thanks @Hlavtox

**Pull request merged**
