### PR TITLE
Ean13 and Ean8 check-sum validation

### PR DESCRIPTION
**Pull request by N-Wouda**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | The current Ean13 validation step simply checks if the Ean code is a numeric string of length 13. That's insufficient: it should also verify the bar-code checksum. This PR implements such a verification, and also adds tools for working with Ean8 bar-codes.
| Type?         | improvement / new feature
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Run tests

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11092)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Should it be easier to introduce a library that already include all barcode like this one https://github.com/tecnickcom/tc-lib-barcode ?

**Comment by N-Wouda** [comment]
Hello @PierreRambaud! You wrote,

>Should it be easier to introduce a library that already include all barcode like this one https://github.com/tecnickcom/tc-lib-barcode ?

I'm not opposed to the use of some third-party library to bring this functionality to PrestaShop, but the question is whether this pays out sufficiently. PrestaShop only needs one or two of those methods (as of yet, but probably also for the foreseeable future), and IMO introducing a dependency for something so minor does not pay. It's not so much easier any more: the code is here, and reworking it to use a third-party library is going to be a little extra work. 

I'm looking forward to your and others' responses.

**Comment by PierreRambaud** [comment]
Not sure PrestaShop needs only two or three. Depends on how you manage your products. @matks What do you think? Could be interesting to integrate EAN, QR Code, ITF, Code39, and maybe others.

**Comment by matks** [comment]
I don't know 😅 both opinions are relevant: adding this library can be very useful for shops which deal a lot with barcodes, however it's "one more dependency" in the bucket which makes PrestaShop project bigger (more files, bigger zip ...).

I would say I side with @N-Wouda as I like to aim for a as-lightweight-as-possible PrestaShop flexible and open for extensibility. In that usecase, we could add hooks to allow a module to easily plug itself in this process and provide the additionnal checks. It would be a "BarCode checker module".

However for this concern:
> It's not so much easier any more: the code is here, and reworking it to use a third-party library is going to be a little extra work.

Well, being able to use a 3rd party would make PrestaShop a bit more modular: we would have to create an Interface for those checks and make sure that the 3rd party provides expected features, but that a prestashop developer should be able to replace it by another provider if needed. So more work but better code structure.

**Comment by N-Wouda** [comment]
@mickaelandrieu @matks rebased!

@matks you wrote,

>Well, being able to use a 3rd party would make PrestaShop a bit more modular: we would have to create an Interface for those checks and make sure that the 3rd party provides expected features, but that a prestashop developer should be able to replace it by another provider if needed. So more work but better code structure.

No argument from me. That said, I do not have the time and interest to fully implement such a flexible design for many other types of validations/barcodes. I'd suggest we cross that bridge when we get to it.

**Comment by PierreRambaud** [comment]
ping @eternoendless @matks

**Comment by matks** [comment]
@PierreRambaud Sorry for late answer.

Fast forward 2 years, I think current PR is a mergeable milestone and we can keep the "add a checksum library verifier" for later. The current changes are not much, they are tested, and do not add one more dependency (more dependencies = harder to update for example when adding php8 compatibility).

So I would be in favor of accepting this PR, wdyt?

**Review by eternoendless — APPROVED** [review]
LGTM but needs rebase

**Comment by Progi1984** [comment]
Hello @N-Wouda, thanks for your contribution, would you mind to rebase your pull request? Thanks

Reference : https://anavarre.net/how-to-rebase-a-github-pull-request/

**Comment by PierreRambaud** [comment]
Hi @N-Wouda,

Unfortunately, the fork has been removed and we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Comment by N-Wouda** [comment]
@PierreRambaud no worries! I opened this PR (almost two weeks to the day) three years ago. My need, and interest, to get this into the codebase is now gone. You are very welcome to use the code and merge it in yourself, but I am not going to spend any further work on it.

**Pull request closed without merging**
