### PR TITLE
Enable usage of roles for Module Updates and Module Alerts pages and manage access

### LINKED ISSUE #11547: Can't enable or disable some modules permissions
**Describe the bug**
Can't enable or disable some modules permissions

**To Reproduce**
1. Go to Advanced parameters > Team > Permissions
2. Try to enable/disable checkboxes below

capture d ecran_680

3. See the error

capture d ecran_681

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Enable new Tabs roles ROLE_MOD_TAB_ADMINMODULESPOSITIONS_[XX] and TAB_ADMINMODULESNOTIFICATIONS_[XX] and use them to secure "Improve > Modules > Module Manager > Updates" and "Improve > Modules > Module Manager > Alerts" page
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Partially fixes https://github.com/PrestaShop/PrestaShop/issues/11547
| How to test?  | Previously, anybody logged in the BO could acces "Improve > Modules > Module Manager > Updates" page using link `/admin-dev/index.php/improve/modules/updates` . Now it requires the READ rights for this page that can be given through the Permissions page. Same for "Improve > Modules > Module Manager > Alerts" page.

@Quetzacoalt91 I added the new Tab roles in install data and gave access to the Superadmin. However should I add something for the auto-upgrade ?

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12713)

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
Hi @matks,

It looks like the same work will have to be done for AdminModulesNotifications.

**Comment by Quetzacoalt91** [comment]
> I added the new Tab roles in install data and gave access to the Superadmin. However should I add something for the auto-upgrade ?

I guess so. When we try to allow a profile to access this page, the check disappears as soon as we refresh the page.

**Comment by marionf** [comment]
> When we try to allow a profile to access this page, the check disappears as soon as we refresh the page.

Yes, there is an issue opened: #11547

**Comment by matks** [comment]
> > I added the new Tab roles in install data and gave access to the Superadmin. However should I add something for the auto-upgrade ?
> 
> I guess so. When we try to allow a profile to access this page, the check disappears as soon as we refresh the page.

Would something like `ps_1760_add_new_module_sf_tabs.php` do the job ? It would be a script that would add the new Tabs and give access to them to Superadmin.

However what about other profiles that used to have access to these pages (because it was wide opened before XD) and now will need to be given manually access ?

EDIT: will be solved in https://github.com/PrestaShop/PrestaShop/issues/12722

**Comment by matks** [comment]
> Hi @matks,
> 
> It looks like the same work will have to be done for AdminModulesNotifications.

Done, 2nd commit added

**Comment by matks** [comment]
> > When we try to allow a profile to access this page, the check disappears as soon as we refresh the page.
> 
> Yes, there is an issue opened: #11547

My PR fixes this issue for the pages "Module Alerts" and "Module Pages". For "Module Catalog" it will need to be done in another PR as this requires a technical change that I need to discuss with other team members.

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
