### PR TITLE
Remove step for install npm in tests

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | setup-node@v3 already installs npm, skip our own install step for it
| Type?             | improvement
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Check that CI is green
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   | 

Couldn't test this easily without really opening a PR so lets see what happens.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by tswfi** [comment]
Looks like the CI runs fine with this change. This is kind of a continuation for: https://github.com/PrestaShop/PrestaShop/pull/31988

**Comment by matks** [comment]
I love saving some CPU 😁

**Review by matks — COMMENTED** [review]
OK for me, requesting @boubkerbribri review on this as it impacts some of his scope of GA ;)

**Review by 0x346e3730 — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @tswfi ,
Automated tests -->OK (https://github.com/djoelleuch/ga.tests.ui.pr/actions/runs/4679067026) 
LGTM , it's QA :heavy_check_mark: 
thanks !

**Review by boubkerbribri — APPROVED** [review]

**Comment by nicosomb** [comment]
Thank you @tswfi

**Pull request merged**
