### PR TITLE
Fix generate path thumbnail image

### PR DESCRIPTION
**Pull request by fest73**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix function generator path to thumbnail
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional) If this PR fixes an [Issue](https://github.com/PrestaShop/PrestaShop/issues), please write "Fixes #[issue number]" here.
| How to test?  | For example generate thumbnail and output in edit product page thumbnail. Link for example: site.ru/admin_65466456/index.php/product/form/472, link for example ../img/tmp/thumb.jpg not work 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/14004)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]
Seems legit :+1:

**Review by matks — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thanks @dariusakafest

**Comment by sarahdib** [comment]
The PR create an issue in localization->language :
Capture d’écran 2019-06-06 à 18 51 07

The link is not the right one : 
Capture d’écran 2019-06-06 à 19 05 10

Can we revert it ?

**Comment by PierreRambaud** [comment]
@sarahdib Maybe better to fix this page.
Wdyt @matks ?

**Comment by matks** [comment]
> @sarahdib Maybe better to fix this page.
> Wdyt @matks ?

You mean "fix the legacy code that computes the path of the image and give it to the page" :trollface: ?

So, yeah. 😢

**Comment by tomas862** [comment]
related https://github.com/PrestaShop/PrestaShop/issues/14661

**Pull request merged**
