### PR TITLE
Add support for non-unity MySQL autoincrement

### LINKED ISSUE #15019: Prestashop requests auto_increment_increment and auto_increment_offset to be set to 1
**Describe the bug**
Installation of prestashop fails when installed on mysql in master-master or multimaster galera setup. Instalator checks for auto_increment options are set to 1, which is incompatible with galera or M-M setup.

**To Reproduce**
1. Setup mysql cluster Master-Master or Galera
2. Start instalation process of prestashop
3. Point configuration to M-M or Galera cluster

**Expected**
Galera or M-M cluster setup is quite common to achieve HA for database, prestashop should not check auto_increment options and should be installable on M-M or Galera cluster.

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add support for non-unity MySQL autoincrement
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/15019
| How to test?  | All tests neeed to pass.

Non-unity increment is well supported, only some tests and fixtures install from xml files expect fixed/unity autoincrement. This PR add global support for non-unity MySQL autoincrement and the code for creation of the initial data (which tests expect) was fixed.

Non-unity autoincrement support is important, as this is per DB server settings and can not be changed on per vhost basis.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16813)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]
Look legit. Good work. Waiting for one more developer before going to QA

**Review by Progi1984 — DISMISSED** [review]

**Comment by mvorisek** [comment]
No QA within 24 days, can this PR be merged?

**Comment by matks** [comment]
QA team might just be a bit busy 😉

**Comment by PierreRambaud** [comment]
@mvorisek Christmas holidays :sweat_smile:

**Comment by mvorisek** [comment]
Still holidays? Is it ok to merge this into the 1.7.7 branch?

**Comment by PierreRambaud** [comment]
@mvorisek Many things occurred during hollidays and after. Our quality team have many things to tests, and they want to be sure everything is ok :+1: 
Be patient, if your pull request is in QA, the hardest thing has been done :heart:

**Comment by mvorisek** [comment]
Can we merge it? Is it ok to merge this into the upcoming 1.7.8 branch / release?

**Comment by Progi1984** [comment]
@mvorisek Your PR is still on the QA side (@PrestaShop/prestashop-qa). That need more supplementary tests.

**Comment by Robin-Fischer-PS** [comment]
Hi @mvorisek @PierreRambaud @Progi1984  ! How can the QA test this PR ? Thanks !

And the conflict on this PR needs to be resolved before testing :)

**Comment by mvorisek** [comment]
@Robin-Fischer-PS All tests must pass. We are already using this patch for more than 2 years without any issue.

PR rebased on the latest `develop`.

**Comment by Robin-Fischer-PS** [comment]
Thanks @mvorisek for the rebase ! Since we cannot pass too much time on each PR (passing all our tests means the whole QA team working one week just on your PR), I saw with a fellow Core dev for a simple test scenario.
We are going to pass a simple end-to-end test case, with creation of a customer, doing an order FO and BO, editing the order, and paying it (after changing our autoincrement parameter in DB).

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@mvorisek Could you fix Travis, please ? Thanks

**Comment by mvorisek** [comment]
@tdavidsonas88 Can you please advise how to fix the tests? This PR seems to be broken by your last commits: https://github.com/PrestaShop/PrestaShop/commits/develop/tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php Thanks!

**Comment by tdavidsonas88** [comment]
> @tdavidsonas88 Can you please advise how to fix the tests? This PR seems to be broken by your last commits: https://github.com/PrestaShop/PrestaShop/commits/develop/tests/Integration/Behaviour/Features/Context/Domain/CategoryFeatureContext.php Thanks!

Checking out your branch and going to provide some feedback soon. Failures seems to be related with the whole behat suite running so will take some time to debug the error. My guess it can be related to: #    update category not available for multi shop context; Or category position 'tr_8_15_1,tr_8_13_0' undefined. Let me check it

**Comment by tdavidsonas88** [comment]
> @tdavidsonas88 Can you please advise how to fix the tests?

Unfortunately this test is passing for me locally on your branch both running only the failing suite and also whole behat suite.

**Comment by tdavidsonas88** [comment]
@mvorisek the error comes from here: https://github.com/mvorisek/PrestaShop/blob/7539961583b1f2139f7f415256d904b50fa684ff/src/Adapter/Category/CommandHandler/UpdateCategoryPositionHandler.php#L45-L62

Can you try to run/debug the suite locally with: ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml
?

**Comment by mvorisek** [comment]
> 
> 
> > @tdavidsonas88 Can you please advise how to fix the tests?
> 
> Unfortunately this test is passing for me locally both running only the failing suite and also whole behat suite.

You have probably MySQL AI step set to 1 and in the tests you expect some fixed IDs - see https://github.com/PrestaShop/PrestaShop/pull/16813/files#diff-354f30a63fb0907d4ad57269548329e3R80 can you temporary set you MySQL config with different AI step than 1 and recheck?

The failing test is https://travis-ci.com/PrestaShop/PrestaShop/jobs/289219843#L8234

**Comment by tdavidsonas88** [comment]
> > > @tdavidsonas88 Can you please advise how to fix the tests?
> > 
> > 
> > Unfortunately this test is passing for me locally both running only the failing suite and also whole behat suite.
> 
> You have probably MySQL AI step set to 1 and in the tests you expects some fixed IDs - see https://github.com/PrestaShop/PrestaShop/pull/16813/files#diff-354f30a63fb0907d4ad57269548329e3R80 can you temporary set you MySQL config with different AI step than 1 and recheck?
> 
> The failing test is https://travis-ci.com/PrestaShop/PrestaShop/jobs/289219843#L8234

Yes, I see, that I have hardcoded these values. I see solution: using generated values from db instead of hardcoded in the behat test

**Comment by tdavidsonas88** [comment]
@mvorisek  can I commit to your branch? or should I explain it to you?

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek can I commit to your branch? or should I explain it to you?

Feel free to commit directly :)

**Comment by tdavidsonas88** [comment]
> > @mvorisek can I commit to your branch? or should I explain it to you?
> 
> Feel free to commit directly :)

Can you add me as collaborator on Github repo/branch: tdavidsonas88? My push is rejected: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

**Comment by mvorisek** [comment]
> Can you add me as collaborator on Github repo/branch: tdavidsonas88?

done, added you as a collaborator for the whole fork

**Comment by mvorisek** [comment]
> 
> 
> @mvorisek Could you fix Travis, please ? Thanks

done, all CI tests passed

**Comment by mvorisek** [comment]
> @mvorisek Could you fix Travis, please ? Thanks

@Progi1984 done, all CI tests passed

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by mvorisek** [comment]
@PierreRambaud 
image
This PR have already passed the QA phase, the last change is only merge conflict fix.

**Comment by PierreRambaud** [comment]
@mvorisek You're right, adding this label by reflex :sweat_smile:

**Comment by PierreRambaud** [comment]
Thanks @mvorisek

**Comment by gennaris** [comment]
FYI : 
I tried to deploy a fresh v1.7.6.5 on a 4-nodes M-M Galera cluster by using this patch
but I got non visible backoffice categories afterwards.

I checked why and it looks like during installation home category is written to forcefully 
have ID 2 in **ps_shop** table (hardcoded?), 
This cannot work with a non-unity autoincrement as home category will get a different value
(id 1 = root / id 1 + AI offset = home).

**Comment by Progi1984** [comment]
@gennaris Could you open a new issue, please :) ?

**Comment by matks** [comment]
Hi @PierreRambaud and @Progi1984 sorry to come back almost 1 year later on this PR 😞 

Please tell if I miss something, but it looks like this PR brings in BC breaks 🤔  ?

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud and @Progi1984 sorry to come back almost 1 year later on this PR 
> 
> Please tell if I miss something, but it looks like this PR brings in BC breaks  ?

Yes you're right. the method `checkAutoIncrement` no longer exists.

**Comment by Progi1984** [comment]
I added the label ;)

**Pull request merged**
