### PR TITLE
[*] CORE : Add function to clean up the image after cut or resize

### PR DESCRIPTION
**Pull request by guestisp**
Actually, resized/cutted images make some noise due to PHP JPG liberary.

This function removes the noise cleaning up the resized image.

### CODE REVIEW

**Comment by guestisp** [comment]
News on this? Having noise on resized images is no good.

**Comment by guestisp** [comment]
bump

**Comment by gRoussac** [comment]
Hi,

Thank you for your P, you can not use $this in a static.

Regards

**Comment by janikjan** [comment]
Thank you for your solution! i replaced 2 lines of $this->clearImage($dst_file, $file_type); by self::clearImage($dst_file, $file_type); 

It is working now! The white background is the real white background without any grey lines   . 
You can download the latest version of fixed ImageManager.php here https://www.dropbox.com/s/am17tdflvyajac0/ImageManager.php?dl=0

But the negative side effect is the speed of regenerate of thumbnails. I did compare test and here are results: 
Fixed white background ImageManager.php: 3 min 40 s 
Original Prestashop ImageManager.php (with grey line issue): 1 min 5 s
As you can see difference is really really big. The fixed version is more then 3-times slower than original. Do you have any ideas how to make it same fast liek original version? Or at least only little slower then original version? Because right now it is really slow.

Thanks.

**Comment by guestisp** [comment]
Sorry for typo, code was refactored for publishing on GH.

**Comment by janikjan** [comment]
guestisp: thanks for your work anyway :). But do you have some solution the problem with speed? Asi you can see the difference is really huge (it is more then 3x slower then original solution). Thanks.

**Comment by janikjan** [comment]
Hello. Do you have any ideas how to fix the slowness of this solution?
Thank you.

**Comment by mickaelandrieu** [comment]
@janikjan yes,  use blackfire Profiler and try different strategies.

**Comment by janikjan** [comment]
@mickaelandrieu Thank you for your solution. But I am not a developer and also I do not have VPS or dedicated server. I am on regular hosting. From my point of view the best solution will be to use ImagMagick instead of GD. But there is nto any of solutions for this for latest version of Prestashop.

Or if you hava another solution I will be happy (or your own code).

**Comment by mickaelandrieu** [comment]
The point is that you need to know what operation is very slow in order to focus on improving that...

**Comment by mickaelandrieu** [comment]
Why not use imagefill()  instead of colouring pixel by pixel?

**Comment by mickaelandrieu** [comment]
What I suggest is to make a background white first, then include your thumbnail inside (I don't know well PrestaShop but I guess it's your need)

**Comment by janikjan** [comment]
I tried to change it from 
if(($r==253 && $g == 253 && $b ==253) || ($r==254 && $g == 254 && $b ==254)) {
imagesetpixel($src['ressource'], $x, $y, $white); }

to:
if(($r==253 && $g == 253 && $b ==253) || ($r==254 && $g == 254 && $b ==254)) {
imagefill($src['ressource'], $x, $y, $white); }


But it is still slow (same like before). 

I think the problem is here:
//Travel y axis
        for($y=0; $y<($processHeight); ++$y){
           // Travel x axis
            for($x=0; $x<($processWidth); ++$x){

From what I understand it scans every pixel in image.  But I am not sure how to make it without scan of every pixel. Because My jpg images have white background (ffffff) and because of bug in GD library it changes the white (ffffff) to fefefe and ffffff. So that is the reason why this patch will correct it to color of original jpg file. Because of this bug in GD library. I am not sure if there is some solution with using of GD library to fix this issue without performance impact.

That is the reason why I am think that the best solution will be maybe to use Imagemagick instead of GD. But there is not any simple solution how to change GD library to ImageMagick for latest Prestashop version.

**Comment by xBorderie** [comment]
Thank your your contribution! We're closing this PR as it seems to not the best solution in this case. Cheers!

**Pull request closed without merging**
