### PR TITLE
Remove unused symfony librairies

### LINKED ISSUE #32942: Remove symfony librairies not used in the CORE

### PR DESCRIPTION
**Pull request by lartist**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove unused symfony librairies
| Type?             | improvement
| Category?         | CO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | CI 🟢  and auto tests 🟢 
| Fixed ticket?     | Fixes #32942
| Related PRs       |
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Comment by lartist** [comment]
https://github.com/lartist/ga.tests.ui.pr/actions/runs/5313453230

**Review by FabienPapet — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by lartist** [comment]
CI and auto tests 🟢 

Thanks @lartist :)

**Comment by Hlavtox** [comment]
@lartist `polyfill-php73` also not needed anymore?

**Comment by matks** [comment]
Dont forget milestone ;) @lartist

**Comment by lartist** [comment]
> @lartist `polyfill-php73` also not needed anymore?

@Hlavtox yes you're right since we don't support it anymore. We can remove it in another PR.

**Pull request merged**
