### PR TITLE
Remove synchronous call to the CLDR

### PR DESCRIPTION
**Pull request by Shudrum**
| Questions | Answers |
| --- | --- |
| Branch? | debug |
| Description? | Some synchronous calls to the CLDR are done, they need to be asynchronous |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Check the currencies of the product page on the backoffice |

### CODE REVIEW

**Comment by kpodemski** [comment]
Hey Julien, what about this 'debug' branch? What is it?

**Comment by maximebiloe** [comment]
Here is the one on `debug` branch: https://github.com/PrestaShop/PrestaShop/pull/6804

**Comment by maximebiloe** [comment]
Let's merge it, tests were ok on `debug`

**Comment by kpodemski** [comment]
@maximebiloe do we need to make PR also on `debug` ?

**Comment by maximebiloe** [comment]
@kpodemski no need to make your PR on `debug`.
It will be the RC3 where we only fix the blocker issues. We made a new branch to avoid to block `develop` from merging.

**Pull request merged**
