### PR TITLE
$base_url smarty don't check if SSL is enabled

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  1.7.7.x
| Description?  | $base_url Smarty Variable don't check if SSL is enabled
| Type?         | bug fix 
| Category?     |  BO 
| BC breaks?    | no
| Deprecations? |  no
| Fixed ticket? | https://github.com/PrestaShop/gamification/pull/75 https://github.com/PrestaShop/PrestaShop/issues/20878
| How to test?  | Go to admin controller gamification open console

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20893)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by SD1982** [comment]
Hi @okom3pom as it's not a regression can you rebase this PR on the develop branch please ?

**Comment by ghost** [comment]
https://github.com/PrestaShop/PrestaShop/pull/20893 open https://github.com/PrestaShop/PrestaShop/pull/20940

**Comment by PierreRambaud** [comment]
This PR was correctly targeted the develop branch :thinking: 
It was just an error in the PR description's table :sweat_smile:

**Comment by ghost** [comment]
oups :D

**Pull request closed without merging**
