### PR TITLE
Fix `AdminProductsController` minor code issue

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix `AdminProductsController` minor code issue.
| Type?             | refacto
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | N/A
| Possible impacts? | N/A

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]
Haha 😄 that was a funny one

**Comment by matks** [comment]
I think we don't need QA for this one, am I too reckless 😝 ? @PrestaShop/prestashop-maintainers

**Comment by matks** [comment]
> I think we don't need QA for this one, am I too reckless 😝 ? @PrestaShop/prestashop-maintainers

Now asking @Robin-Fischer-PS

**Comment by kpodemski** [comment]
Thanks @PululuK

**Pull request merged**
