### PR TITLE
Add a CLI option for fixtures

### LINKED ISSUE #19696: Fixtures are always installed when using the CLI installer
## Describe the bug

When you use the CLI installer (`install-dev/index_cli.php`) to install a shop, there is no option to disable the fixtures installation.

#### Expected behavior

There should be a parameter to disable fixture installation when using the CLI install script.

#### Steps to Reproduce

1. launch the `install-dev/index_cli.php` with your relevant parameters to silently install a shop
2. fixtures are installed by default
3. there is no parameter to avoid that

This is my script installation parameters:
```sh
php index_cli.php \
--language='en' \
--country='fr' \
--domain='localhost' \
--base_uri='/prestashop/' \
--db_name=prestashop \
--db_user=root \
--db_password=melon \
--password=prestashop_demo \
--email=demo@prestashop.com
```

#### Additional information

* PrestaShop version: `develop` but seems to be like that since a few versions
* PHP version: doesn't really matter, but tested in 7.2

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add a CLI option for fixtures
| Type?         | improvement
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19696
| How to test?  | Check in dev & prod mode :<br>* Use no option<br>** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop`<br>* Use step option<br>** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop  --step=database,theme,modules,addons_modules`<br>** Installation with Fixtures: `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,fixtures,theme,modules,addons_modules`<br>* Use fixtures option<br>** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --fixtures`<br>** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --fixtures=0`<br>** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --fixtures=1`<br>* Use two options<br>** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,fixtures,theme,modules,addons_modules --fixtures=0`<br>** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,theme,modules,addons_modules --fixtures=1`<br>** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,fixtures,theme,modules,addons_modules --fixtures=1`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19757)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
@Progi1984 I think it's a developer who should do the QA here, wdyt ?

**Comment by Progi1984** [comment]
@matks I added a scenario which permits to QA to test without need of dev ;)

**Comment by matks** [comment]
> @matks I added a scenario which permits to QA to test without need of dev ;)

I see what are the commands they should run but what should they verify ? 🤔

**Comment by Progi1984** [comment]
> > @matks I added a scenario which permits to QA to test without need of dev ;)
> 
> I see what are the commands they should run but what should they verify ? thinking

It's just diplayed before the command : install w or w/o fixtures

**Comment by SimonGrn** [comment]
Check in dev & prod mode :
* Use no option
** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop`
=> OK

* Use step option
** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop  --step=database,theme,modules,addons_modules`
=> OK (no fixtures) except the `Anonymous` user with an `Anonymous` Address
** Installation with Fixtures: `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,fixtures,theme,modules,addons_modules`
=> OK (fixtures installed)

* Use fixtures option
** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --fixtures`
=> OK (fixtures installed)
** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --fixtures=0`
=> OK (no fixtures) except the `Anonymous` user with an `Anonymous` Address
** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --fixtures=1`
=> OK (fixtures installed)

* Use two options
** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,fixtures,theme,modules,addons_modules --fixtures=0`
=> OK (no fixtures) except the `Anonymous` user with an `Anonymous` Address
** Installation without Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,theme,modules,addons_modules --fixtures=1`
=> OK (no fixtures) except the `Anonymous` user with an `Anonymous` Address
** Installation with Fixtures : `php install-dev/index_cli.php --language=en --country=fr --domaine='127.0.0.1' --base_uri='/PrestaShop/' --db_server=127.0.0.1 --db_user=root --db_password=root --db_name=prestashop --step=database,fixtures,theme,modules,addons_modules --fixtures=1`
=> OK (fixtures installed)

Regarding the `Anonymous` user I guess it's normal since it's not a "real user" per se ?

**Comment by Progi1984** [comment]
@SimonGrn Normal for the `Anonymous` user : it comes from the `psgdpr` module (https://github.com/PrestaShopCorp/psgdpr/blob/master/psgdpr.php#L1021). Do you confirm that you have this module ?

**Comment by SimonGrn** [comment]
This is a vanilla installation, so indeed I have it !
image

This is :heavy_check_mark: for me

**Comment by Progi1984** [comment]
Thanks @SimonGrn

**Pull request merged**
