### PR TITLE
Edit demo product and check info

### PR DESCRIPTION
**Pull request by hadrich-hatem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows checking the basic information of demo products in the Back Office.
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | Run the script TEST_PATH=full/02_product/17_edit_check_demo_product_in_BO.js npm run specific-test -- --URL=FrontOfficeURL

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9107)

### CODE REVIEW

**Comment by marionf** [comment]
Hello @hadrich-hatem 

If the product is a pack, we need to check if it contains products & if the field to add product is displayed
capture du 2018-05-29 17-35-47

**Comment by hadrich-hatem** [comment]
Hello @marionf,
I have added the missing check if it contains products & if the field to add product is displayed.
Thank you.

**Comment by marionf** [comment]
Thank you @hadrich-hatem :)

**Comment by mickaelandrieu** [comment]
Hello @hadrich-hatem, this need to be rebased :+1:

**Comment by hadrich-hatem** [comment]
Hello @mickaelandrieu,
The rebase of this PR done.
Best regard,

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by fatmaBouchekoua** [comment]
@mbadrani This PR is ready to b merged

**Comment by mbadrani** [comment]
@fatmaBouchekoua some conflicts on product.js file, need rebase

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks @hadrich-hatem and everyone for reviews!

**Pull request merged**
