### PR TITLE
Performance is better when fetching all rows at once

### PR DESCRIPTION
**Pull request by studiokiwik**
Moved from https://github.com/PrestaShop/PrestaShop/pull/4368

### CODE REVIEW

**Comment by xBorderie** [comment]
Hey @studiokiwik, thank you for remaking this PR on the `develop` branch!
Sadly, it seems that your codebase wasn't up-to-date, and several unrelated commits where included.
Could you remake it with an updated codebase?
Thank you!

**Comment by julienbourdeau** [comment]
Hi,

Please update your PR and I'll merge it right away. Otherwise I'll have to cherry-pick your commit but the PR won't appear as _merged_. :(

**Comment by xBorderie** [comment]
@julienbourdeau, the commit itself is 2480e5dec71925ec09aaf27bfb34cdae60f74ab4, do you think it's mergeable easily? No risk of side-effect?

**Comment by julienbourdeau** [comment]
Yeah it seems good to me and many peolple here #4368 :)

**Comment by xBorderie** [comment]
Alright! Hey @studiokiwik, please update or remake your PR so you can get proper credit within the Git history :)

**Comment by xBorderie** [comment]
Hey @mickaelandrieu, can you cherry-pick this one? Thanks!

Keeping it open until you have created your own PR. 
Thank you for your contribution, @studiokiwik !

**Comment by maximebiloe** [comment]
Hello,

The codebase is not up-to-date anymore and there more commits than needed in your PR.
The commit has been cherry-picked and redone here  https://github.com/PrestaShop/PrestaShop/pull/5029 but the PR was closed.
Anyway, it has been backported in this one: https://github.com/PrestaShop/PrestaShop/pull/5106

Regards

**Pull request closed without merging**
