### PR TITLE
Fix steps height on carrier page on mobile

### LINKED ISSUE #24859: [BO - Responsive] - Bad Display of Carriers page
#### Describe the bug

The page is very long and the **stepDesc** are displayed incorrectly

#### Expected behavior

The **stepDesc** must be hidden and the page must be fit to the content.

#### Steps to Reproduce

1. On mobile
2. **BO** > **IMPROVE** > **Shipping** > **Carriers**
3. Edit a Carrier
4. See error (see the attached screenshot below)

**Screenshots**

image

#### Additional information

* PrestaShop version: 1.7.6.7 & 1.7.7.4 & 1.7.8.x & develop
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Steps height was pretty big on mobile and hard to use 
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #24859.
| How to test?      | Go on carrier page, set to small mobile (320) and refresh the page, the pan height should be fine!
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24909)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by Hlavtox** [comment]
@NeOMakinG Why not just `display: flex;` and `flex-wrap: wrap;` + 50% width of the step on mobile? No JS would be needed. 👍 These fixed heights are dangerous. 💣

**Comment by NeOMakinG** [comment]
> @NeOMakinG Why not just `display: flex;` and `flex-wrap: wrap;` + 50% width of the step on mobile? No JS would be needed. 👍 These fixed heights are dangerous. 💣

Hey, because every pans are in position: absolute; and the height is calculated on click on tabs links

Using display: flex; and another modern property, on a old plugin is like wanting to get around the complete lib workflow which is more dangerous to me that a minimum fixed height...

But I agree and both solution aren't fine enough to me, this page needs to get migrated with better concepts... This fix is acceptable for the moment to my knowledge

**Comment by NeOMakinG** [comment]
@florine2623 Why did you put the waiting for author label? Did you test it and found something? :)

**Comment by florine2623** [comment]
Hello @NeOMakinG !

Yes sorry, I don't know the message didn't send ^^'

All steps look good except for Step 2. The usual button are hidden :
Screenshot 2021-06-15 at 10 54 20

Here's what I have :
In 320px :
Screenshot 2021-06-15 at 10 45 31

In 1200px :
Screenshot 2021-06-15 at 10 49 13

Is there something I'm missing ?
Thanks!

**Comment by NeOMakinG** [comment]
Ok, only the first load had a problem, on the first step, it should be fine now (I think it's because the height is way higher on the first load because of some JS scripts)

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by florine2623** [comment]
Thanks for the update @NeOMakinG .
Looks perfect to me :
In 320 px :
Screenshot 2021-06-16 at 16 03 46

In 1200 px :
Screenshot 2021-06-16 at 16 04 16

Thanks!

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @florine2623

**Pull request merged**
