### PR TITLE
Add manual removal fallback in SymfonyCacheClearer

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add fallback in SymfonyCacheClearer to manually remove the cache folder when the command did not work
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI green and UI tests green, test enable/disable feature flags Test actions on modules (install, uninstall, enable, disable)
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/11161008811
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | ~

### CODE REVIEW

**Comment by Hlavtox** [comment]
This could finally fix the Windows issues. :-)

**Comment by jolelievre** [comment]
> This could finally fix the Windows issues. :-)

That's not the initial objective, but yeah it could If you have an environment to check if it works let us know 😉

**Review by florine2623 — APPROVED** [review]
Hello @jolelievre ,

Tested your PR.
It works as expected, when I enable/disable the feature flag for carrier, when I navigate to carrier page, I see the right page displayed !
No exception are displayed.

Waiting for 2 approvals and automated tests to be green before merging please !

Thanks!

**Comment by florine2623** [comment]
Automates tests launched :

Testing PrestaShop pull requests (with cache) : https://github.com/florine2623/testing_pr/actions/runs/11164768049
Testing PrestaShop pull requests (without cache) : https://github.com/florine2623/testing_pr/actions/runs/11164824032

**Review by boherm — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by florine2623** [comment]
Launched workflow `Testing PrestaShop pull requests (without cache)` : https://github.com/florine2623/testing_pr/actions/runs/11164824032

Result is green, so we can merge this PR ^^

Thanks!

**Pull request merged**
