### PR TITLE
Apply shop context in configuration

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Handle the shop context automatically when updating the configuration. This PR is set in the `develop` branch because it updates the behavior of every controller running under Symfony.
| Type?         | improvement
| Category?     | BO
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5946
| How to test?  | Try to enable the maintenance mode of a single shop, only the selected one must be impacted

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9311)

### CODE REVIEW

**Review by mickaelandrieu — DISMISSED** [review]

**Comment by mickaelandrieu** [comment]
This will fix the bug, but I'm not sure this is a good idea for the future to rely on a hidden context :/

**Comment by hadjedjvincent** [comment]
Isn't that should be targeted on 1.7.4.x ?
As you said @mickaelandrieu, it is a bug fix. It's more like a regression.

**Comment by Quetzacoalt91** [comment]
@hadjedjvincent do you mean this PR brings a regression?

@mickaelandrieu, what would you suggest? Does every form handler should specify on which context they want to write the configuration?

**Comment by hadjedjvincent** [comment]
@Quetzacoalt91 Not really, it looks like behaviour changed on 1.7.4 (if i refer to the forge ticket).
I was meaning it's a regression from previous releases.

**Comment by marionf** [comment]
Yes, @hadjedjvincent it's a regression of 1.7.4.0
Can you do it on 1.7.4.x @Quetzacoalt91 ?

**Comment by marionf** [comment]
@Quetzacoalt91 
We have another related issue.
If I choose in the drop down "All shop" context and change something, it's not applied to all shops.
Can we solve it btw or in another PR ?

@mickaelandrieu in multishop on legacy pages we have this button and checkboxes:
capture d ecran_47
Do you think it's possible to add it on symfony pages ?

**Comment by rGaillard** [comment]
@marionf i have opened an issue about it long time ago http://forge.prestashop.com/browse/BOOM-1678

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
Thank you @Quetzacoalt91

**Comment by mickaelandrieu** [comment]
> Do you think it's possible to add it on symfony pages ?

Yes, it's possible. This needs to be a forge issue and given to someone that add the field if we're in multishop context only.

@rGaillard not the same issue at all xD

**Pull request merged**
