### PR TITLE
Minor code refato `ModuleManager`

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | This change fixes minor code issues I found while working on another bug.
| Type?             | refacto
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Related PRs       | N/A
| How to test?      | Check that #28124 is still fixed
| Possible impacts? | N/A

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by atomiix** [comment]
Hey @PululuK can you give us more detail about the bug you faced to better understand your fix?

**Comment by PululuK** [comment]
> Hey @PululuK can you give us more detail about the bug you faced to better understand your fix?

Is not really a bug, just a code refato.

**Review by atomiix — APPROVED** [review]

**Comment by PululuK** [comment]
@atomiix waiting for dev label is more appropriate here I think ?

**Comment by atomiix** [comment]
@PululuK I updated your how to test section, I think this can be tested by the QA team

**Comment by PululuK** [comment]
Thanks @atomiix

**Review by matthieu-rolland — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @PululuK ,

Tested on develop branch.
Issue https://github.com/PrestaShop/PrestaShop/issues/28124 is still fixed. I haven't encountered any error why testing it.

I have also ran the automated tests for Modules page, everything is OK.

So this is QA ✅

**Comment by kpodemski** [comment]
Thank you @PululuK @florine2623

**Pull request merged**
