### PR TITLE
Remove non responsive component

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove this obsolete unused piece of code. :-)
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Check that BO looks the same.
| Fixed ticket?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hey there @Hlavtox I have never looked at this component. Can you tell us why you say it's not needed anymore? Is this because thanks to you and @NeOMakinG the BO is now fully responsive?

**Comment by matks** [comment]
FYI @MatShir @fabienvallon

**Comment by fabienvallon** [comment]
Yes 
To  remove ( and to not migrate in the LegacyLayout migration ) 

We will see if we have regression during the QA test / freeze

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @Hlavtox 

I tested your PR,there was no remarquable changes in BO!

Auto Test :https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5854731668 :heavy_check_mark: (1 fail reated to Nightly)

QA:heavy_check_mark: 

Thanks!

**Pull request merged**
