### PR TITLE
Add some fixes to the script

### PR DESCRIPTION
**Pull request by hadrich-hatem**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | This PR adds some fixes to script.
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10708)

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @hadrich-hatem,

What about 1.7.5.x branch?

**Comment by PierreRambaud** [comment]
Or develop?

**Comment by hadrich-hatem** [comment]
Hi @Quetzacoalt91,

Just there are some fixes that I will add on 1.7.5.x. So, i will close this PR and i will open another one.

Best regards,

**Comment by Quetzacoalt91** [comment]
Nice, having these tests on 1.7.5.x (or develop) would be better, as they are the current active branches.

I'm closing this one while you re-suggest the changes to the other branch.

Regards

**Comment by fatmaBouchekoua** [comment]
Hello @Quetzacoalt91 ,
I reopen this PR because there's a new pre-release 1.7.4.4.
Can you merge it please so we can run tests on this pre-release?

Thanks !

**Review by mbadrani — APPROVED** [review]
Needed for test campaign execution

**Pull request merged**
