### PR TITLE
Integrate new modern mail theme (compiled from MJML)

### LINKED ISSUE #12458: Integrate email template new design
This issue is related to the project which aims at reworking the whole email generation system, while replacing the current template with a new and modern one for an improved user experience.

The new template will be generic, for all stores, both for native transactional emails and module emails. 

The mock ups of the reworked template are available here : [https://invis.io/X7QDB1H69EZ](url)

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Integrate new modern theme for mails, also add a controller to allow preview the templates easily before they are generated. Fix a little bug in `CSSInlineTransformation`
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12458
| How to test?  |  You can use the new controller to display the templates you can specify a locale and the module if needed (ex: `/improve/international/mail-layout/preview/modern/account.html`, `/improve/international/mail-layout/preview/ps-emailalerts/modern/fr-FR/productoutofstock.html`)<br /><br /> Here is the url format: `/improve/international/mail-layout/preview/{theme}/{locale}/{layout}.{type}` and `/improve/international/mail-layout/preview/{module}/{theme}/{locale}/{layout}.{type}`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)

### CODE REVIEW

**Comment by kpodemski** [comment]
Hey @jolelievre 

without any checking from me (sorry) i have a question, what about custom modules? doesn this mechanism scan custom modules for having /mails/ directory?

**Comment by jolelievre** [comment]
Hi @kpodemski,

no this system does not scan automatically the modules mail folder to generate them.
However some hooks have been integrated in the system so that modules can add their own
mail layouts to the generation list.

Therefore if the modules' templates use twig templates with the proper `{{ 'test'|trans }}`
inside them they can benefit from the new mail generation each time a Language is installed.

Besides the new system only replaces the legacy download of mail templates, but it changes
nothing with the management of `Mail::send` Meaning if mail templates were integrated in the
module they will still work as they used to, they just can't be automatically generated in the new
installed language.

Does my answer seems clear to you? Some docs about the new hook along with a module example
are coming during the freeze period for more information.

**Comment by kpodemski** [comment]
Thank you @jolelievre - looking forward to see docs :)

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 120 of 120 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: all files reviewed, 9 unresolved discussions (waiting on @jolelievre)

___
*[mails/themes/modern/README.md, line 3 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Laz_Bs8ENJqd45qMVdJ:-Laz_Bs8ENJqd45qMVdK:b-jrqccb) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/mails/themes/modern/README.md#L3)):*
> ```
>  on the MJML
> ```

"on MJML"

> ```
> guaranty
> ```
"ensure"
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 57 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazbcc72Lda9O2LMCD7:-Lazbcc72Lda9O2LMCD8:bujgykr) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L57)):*
> ```PHP
>      * @return Response
>      */
>     public function previewAction($theme, $layout, $type, $locale = '', $module = '')
> ```

Shouldn't access to this controller be secured? https://devdocs.prestashop.com/1.7/development/architecture/migration-guide/controller-routing/#security
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 95 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazh-u24nwx3Nadv-ep:-Lazh-u34e-EQ__qjXuX:bnl52ig) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L95)):*
> ```PHP
>     {
>         /** @var ThemeCatalogInterface $themeCatalog */
>         $themeCatalog = $this->get(ThemeCatalogInterface::class);
> ```

I don't think it's a good idea to name services after classes right now.
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 100 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazdvF9DA8Na4s2Y_Yv:-LazdvF9DA8Na4s2Y_Yw:b-lwe5us) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L100)):*
> ```PHP
>             $theme = $themeCatalog->getByName($themeName);
>         } catch (InvalidArgumentException $e) {
>             throw new InvalidArgumentException($e->getMessage());
> ```

You should never, ever hide the original exception.

Either you catch it and rethrow it using a different type/message/code, or you let the original exception bubble up. If you decide to catch it and rethrow, you should _always_ make sure to link the new exception with the original one using the constructor's third argument:

```php
catch (Exception $e) {
   throw new SomeException("Error message", 123, $e);
}
```
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 107 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazefhD4zqq5Mr-RmdA:-LazefhD4zqq5Mr-RmdB:bohu3nk) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L107)):*
> ```PHP
>         /* @var LayoutInterface $layoutInterface */
>         foreach ($theme->getLayouts() as $layoutInterface) {
>             if ($layoutInterface->getName() == $layoutName &&
> ```

Please use leading boolean operators, not trailing

eg:
```php
if ($something
    && $somethingElse
) {
```
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 108 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazevDrErSciFbERmC_:-LazevDrErSciFbERmCa:bx199b1) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L108)):*
> ```PHP
>         foreach ($theme->getLayouts() as $layoutInterface) {
>             if ($layoutInterface->getName() == $layoutName &&
>                 (empty($module) || $layoutInterface->getModuleName() == $module)) {
> ```

When using multiline `if`, put the closing parenthesis and opening brace in a new line

eg:

```php
if ($something
    && $somethingElse) {
    $thisIsConfusing = true;
}

if ($something
    && $somethingElse
) {
    $thisIsMoreReadable = true;
}

```
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 124 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazhQUT11jZRwN7yQlx:-LazhQUT11jZRwN7yQly:b-izgatc) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L124)):*
> ```PHP
> 
>         /** @var LanguageRepositoryInterface $languageRepository */
>         $languageRepository = $this->get('prestashop.core.admin.lang.repository');
> ```

How about injecting all these services in the constructor?
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 135 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazhbhm7g1pLyLM0UJq:-Lazhbhm7g1pLyLM0UJr:b-tv6wb0) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L135)):*
> ```PHP
> 
>         /** @var MailTemplateRendererInterface $renderer */
>         $renderer = $this->get(MailTemplateRendererInterface::class);
> ```

Same comment about service names
___
*[src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml, line 27 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazicD0BBH0XpgNVUEp:-LazicD19kK9JJyGV11u:b98blg) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml#L27)):*
> ```YAML
> _mail_layout:
>   resource: "mail_layout.yml"
>   prefix: /mail_layout/
> ```

use a dash `-` instead of underscores `_` for routes

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 57 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazbcc72Lda9O2LMCD7:-LazkX215rys9zBNW0yH:b-r6ty7) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L57)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Shouldn't access to this controller be secured? https://devdocs.prestashop.com/1.7/development/architecture/migration-guide/controller-routing/#security
</blockquote></details>

Yes I didn't know how to add the roles correctly, I'm gonna add it.

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 57 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazbcc72Lda9O2LMCD7:-LazlR2k5Vh382Cb4P8c:b-sliemm) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L57)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

Yes I didn't know how to add the roles correctly, I'm gonna add it.
</blockquote></details>

Actually since all the roles and upgrade script have been dealt with in the other PR it would be easier to add the security annotation once this one has been merged. If it's ok with you?

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 95 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazh-u24nwx3Nadv-ep:-LazljEb1sAdtUiysOLV:bskov53) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L95)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

I don't think it's a good idea to name services after classes right now.
</blockquote></details>

This one is a bit special, I declared an alias for the interface in https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/core/mail_template.yml

```yaml
PrestaShop\PrestaShop\Core\MailTemplate\ThemeCatalogInterface: '@prestashop.core.mail_template.theme_folder_catalog'
```

Because I think the simple `ThemeFolderCatalog` will quickly be replaced by another one as the feature on mail themes will grow. So the idea was to simply update the alias and not all the classes that depend on it.

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 100 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazdvF9DA8Na4s2Y_Yv:-Lazmxmd9MFH9R53_eSs:b-828csz) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L100)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You should never, ever hide the original exception.

Either you catch it and rethrow it using a different type/message/code, or you let the original exception bubble up. If you decide to catch it and rethrow, you should _always_ make sure to link the new exception with the original one using the constructor's third argument:

```php
catch (Exception $e) {
   throw new SomeException("Error message", 123, $e);
}
```
</blockquote></details>

It's quite useless here additionally since I throw the same kind of exception, I used to throw an HttpException I think. I will remove this `try..catch..`

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 107 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazefhD4zqq5Mr-RmdA:-LaznPYL8GFFnL6I_Vce:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L107)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Please use leading boolean operators, not trailing

eg:
```php
if ($something
    && $somethingElse
) {
```
</blockquote></details>

Done.

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 108 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazevDrErSciFbERmC_:-LaznamHBL2BkJWgC1LU:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L108)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

When using multiline `if`, put the closing parenthesis and opening brace in a new line

eg:

```php
if ($something
    && $somethingElse) {
    $thisIsConfusing = true;
}

if ($something
    && $somethingElse
) {
    $thisIsMoreReadable = true;
}

```


</blockquote></details>

Done.

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml, line 27 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazicD0BBH0XpgNVUEp:-LazoUZf73_rVjFsTwf5:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Resources/config/routing/admin/improve/international/_international.yml#L27)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

use a dash `-` instead of underscores `_` for routes
</blockquote></details>

Done.

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 135 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazhbhm7g1pLyLM0UJq:-Lazno4S8utPpRWlG5L9:bpxxnv9) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L135)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Same comment about service names
</blockquote></details>

same alias reason, would you prefer I use a "string" alias? like
`prestashop.core.mail_template.theme_catalog: '@prestashop.core.mail_template.theme_folder_catalog'` ?

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 124 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazhQUT11jZRwN7yQlx:-Lazr9ft9ryJviKMYBnJ:bitq9nn) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L124)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

How about injecting all these services in the constructor?
</blockquote></details>

I would be ok with it! Except we hav absolutely no controller with constructors for now, nor do we have autowiring set on the controlles

**Comment by jolelievre** [comment]
___
*[mails/themes/modern/README.md, line 3 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Laz_Bs8ENJqd45qMVdJ:-LazrRQ62Ha4UDp0BvD2:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/mails/themes/modern/README.md#L3)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

> ```
>  on the MJML
> ```

"on MJML"

> ```
> guaranty
> ```
"ensure"
</blockquote></details>

Done.

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: all files reviewed, 2 unresolved discussions (waiting on @jolelievre)

___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 57 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazbcc72Lda9O2LMCD7:-Lb-5YkD4uv36QgRL4Y9:b-6bkhn1) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L57)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

Actually since all the roles and upgrade script have been dealt with in the other PR it would be easier to add the security annotation once this one has been merged. If it's ok with you?
</blockquote></details>

Ok but we'll need an issue for that
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 95 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazh-u24nwx3Nadv-ep:-Lb-5mQo4PZryjYuLk_O:bshp7oq) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L95)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

This one is a bit special, I declared an alias for the interface in https://github.com/PrestaShop/PrestaShop/blob/develop/src/PrestaShopBundle/Resources/config/services/core/mail_template.yml

```yaml
PrestaShop\PrestaShop\Core\MailTemplate\ThemeCatalogInterface: '@prestashop.core.mail_template.theme_folder_catalog'
```

Because I think the simple `ThemeFolderCatalog` will quickly be replaced by another one as the feature on mail themes will grow. So the idea was to simply update the alias and not all the classes that depend on it.
</blockquote></details>

why not name the alias the same way as the rest of the services?
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 124 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-LazhQUT11jZRwN7yQlx:-Lb-6CHb7mdZQB8Gnz6P:b2ooof1) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L124)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

I would be ok with it! Except we hav absolutely no controller with constructors for now, nor do we have autowiring set on the controlles
</blockquote></details>

Ok it was an idea
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 135 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazhbhm7g1pLyLM0UJq:-Lb-6H4WCod0rZj3-41G:b-gojyyb) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L135)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

same alias reason, would you prefer I use a "string" alias? like
`prestashop.core.mail_template.theme_catalog: '@prestashop.core.mail_template.theme_folder_catalog'` ?

</blockquote></details>

I think would be better that way, for consistency's sake

**Review by eternoendless — DISMISSED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by sarahdib** [comment]
@jolelievre 
The logo is missing 
Capture d’écran 2019-03-28 à 11 34 10

**Comment by jolelievre** [comment]
> @jolelievre
> The logo is missing

@sarahdib yes it's normal the generated mails are templates, which means the shop infos are injected when the mail is sent (shop logo, shop name, shop, url, ...)

There are placeholders in the html code, which is why the logo is not displayed. This could be injected during generation but then each time you change your logo mails would need to be generated again. So we keep the placeholders for now (and it avoids a BC break).

That said this could be added in the preview :/

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: all files reviewed, 4 unresolved discussions (waiting on @jolelievre and @sarahdib)

___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 38 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nkef4HEpySSRpbq2:-Lb3nkef4HEpySSRpbq3:b-9b10fu) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L38)):*
> ```PHP
>  * by the Mail class in real behavior.
>  */
> class MailVariablesTransformation extends AbstractTransformation
> ```

Maybe add `Preview` in the class name?
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 72 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nX5VDWEDk4UzNg6O:-Lb3nX5VDWEDk4UzNg6P:b-12qh69) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L72)):*
> ```PHP
> 
>         foreach ($templateVars as $placeholder => $value) {
>             $templateContent = preg_replace('/'.$placeholder.'/', $value, $templateContent);
> ```

This can be sped up significantly by using `strtr()` without the foreach.
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 89 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3o0Ec6mUP0z__0cg2:-Lb3o0Ec6mUP0z__0cg3:breu4a3) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L89)):*
> ```
> $this->configuration->get('PS_LOGO_MAIL')
> ```

Consider using temporary variables to avoid repeated function calls
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 102 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nrOHE3rWparlagHk:-Lb3nrOHE3rWparlagHl:b5wiuag) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L102)):*
> ```PHP
>         }
> 
>         $templateVars['{shop_name}'] = $this->legacyContext->getContext()->shop->name;
> ```

You can store `$this->legacyContext->getContext()` in a variable to avoid repeated function calls.

**Comment by jolelievre** [comment]
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 38 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nkef4HEpySSRpbq2:-Lb3sk_Y5Dm7sXj34DOG:b-u90cjd) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L38)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Maybe add `Preview` in the class name?
</blockquote></details>

I prefer not to, because maybe some this transformation will actually be used when we won't rely on Mail any more and generate the mails on the fly
Even though I know it's a near future, but anyway I think the class name should reflect its function only, not the context it is being used

**Comment by jolelievre** [comment]
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 72 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nX5VDWEDk4UzNg6O:-Lb3t8AfCfv0N74tc_x0:b-787vn7) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L72)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

This can be sped up significantly by using `strtr()` without the foreach.
</blockquote></details>

I think you meant `str_replace`? Done.

**Comment by jolelievre** [comment]
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 72 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nX5VDWEDk4UzNg6O:-Lb3tG4XAUq-2d7Gzb0V:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L72)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

I think you meant `str_replace`? Done.
</blockquote></details>

Done.

**Review by jolelievre — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: 122 of 123 files reviewed, 4 unresolved discussions (waiting on @eternoendless and @sarahdib)

___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 89 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3o0Ec6mUP0z__0cg2:-Lb3tI8526JjXz5aAyp1:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L89)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

> ```
> $this->configuration->get('PS_LOGO_MAIL')
> ```

Consider using temporary variables to avoid repeated function calls
</blockquote></details>

Done.
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 102 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nrOHE3rWparlagHk:-Lb3tJDJCIS6pXNjWxll:b-896fix) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L102)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

You can store `$this->legacyContext->getContext()` in a variable to avoid repeated function calls.
</blockquote></details>

Done.

**Comment by jolelievre** [comment]
___
*[src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php, line 57 at r1](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lazbcc72Lda9O2LMCD7:-Lb3tWiz-sy6e-V853Ek:b-o1vufn) ([raw file](https://github.com/prestashop/prestashop/blob/ca00a164d2d07008b5104b30d37e71023a50cc18/src/PrestaShopBundle/Controller/Admin/Improve/International/MailLayoutController.php#L57)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

Ok but we'll need an issue for that
</blockquote></details>

This will be done in this PR https://github.com/PrestaShop/PrestaShop/pull/13048

**Review by eternoendless — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: all files reviewed, 1 unresolved discussion (waiting on @jolelievre and @sarahdib)

___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 72 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nX5VDWEDk4UzNg6O:-Lb3ubqw0Y07IWFNwACq:bk50gx7) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L72)):*
<details><summary><i>Previously, jolelievre wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, please use `https://www.php.net/strtr` like this:

```php
$templateContent = strtr($templateContent, $templateVars);
```

**Comment by jolelievre** [comment]
___
*[src/Core/MailTemplate/Transformation/MailVariablesTransformation.php, line 72 at r4](https://reviewable.io/reviews/prestashop/prestashop/13004#-Lb3nX5VDWEDk4UzNg6O:-Lb408aX24eNMFCfc6WH:bb6un1j) ([raw file](https://github.com/prestashop/prestashop/blob/ace3ee58e8425f509f196db3042f169d548bcb7f/src/Core/MailTemplate/Transformation/MailVariablesTransformation.php#L72)):*
<details><summary><i>Previously, eternoendless (Pablo Borowicz) wrote…</i></summary><blockquote>

No, please use `https://www.php.net/strtr` like this:

```php
$templateContent = strtr($templateContent, $templateVars);
```
</blockquote></details>

Done

**Review by eternoendless — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13004)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sarahdib)

**Comment by jolelievre** [comment]
Thanks me!

**Comment by tlhuillier** [comment]
Nice feature you added 👏 

It only misses some doc, would be nice to have something about it on https://devdocs.prestashop.com.

Also, I was wondering how do you generate those emails from .mjml to .html.twig ? Aren't the source files (.mjml) supposed to exist in the Prestashop repo as well ?
Is there any update scheduled on https://github.com/PrestaShop/email-templates-sdk ?

**Comment by jolelievre** [comment]
Hi @tlhuillier 
Thank you. About the doc it is being finalized, sorry we focused on the RC release these past weeks, but I will try and publish the doc about email generation by the end of the week.

About the original templates we indeed used mjml sources which were then converted to twig templates (used in this new core feature). But the tool used for that was developed quickly (and ugly, my bad) and is not mature enough yet. I would like to improve it a lot: better code architecture, automatic tests, better management of the components, ...

As soon as this tool will have reached a high enough level of maturity we will add it to the documentation of course.

**Comment by tlhuillier** [comment]
Thanks for the answers.

Nice to see that emails start to get some love.
I'm waiting for this new tool :)

**Pull request merged**
