### PR TITLE
Features UX improvement

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Features UX improvement: the selectors are outside of the collection input, the provider must return a bit more data and the UX was modified in the form theme
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | ~
| UI Tests          | https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/7403423517
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | ~

## Condition of tests

I used this module to generate the data in which to improvements have been added:
https://github.com/PrestaShop/PsFixturesCreator

Then used the command from the module to generate a product with a lot of features:
```bash
./bin/console prestashop:product-creator --productsWithCombinations=1 --features=12 --featureValues=12
./bin/console prestashop:product-creator --productsWithCombinations=1 --features=65 --featureValues=25
./bin/console prestashop:product-creator --productsWithCombinations=1 --features=2 --featureValues=1000
```

Then the product page in BO was tested (only the new product page from 8.1, not the legacy one) and Blackfire was used to extract some metrics displayed in the following tables.

### Tests in prod mode
| Metric | Number of feature values | Without new UX | With new UX |
| ------ | -------------------------- | --------------------- | ----------------- |
| Time | 1 feature value | 5.54s |  4.84s |
| Memory peak usage |   | 31.5Mb | 32.2Mb |
| SQL Queries |   | 88.6 ms / 213 rq | 68.3 ms / 212 rq |
| Time | 144 feature values (12x12) | 9.88s | 7.94s |
| Memory peak usage |   | 69.7Mb | 67.3Mb |
| SQL Queries |   | 87.7 ms / 219 rq | 73.3 ms / 207 rq |
| Time | 1000 feature values (1 x 1000) | 4m36s | 37.3s |
| Memory peak usage |   | 492Mb | 260Mb |
| SQL Queries |   | 121 ms / 208 rq | 105 ms / 207 rq |
| Time | 1625 feature values (65x25) | 58.6s | 38.8s |
| Memory peak usage |   | 467Mb | 427Mb |
| SQL Queries |   | 103 ms / 272 rq | 83.2 ms / 207 rq |

### Specs

One line to add the feature. Once the feature associated to the product, it is added to the grid. 
Each feature can be deleted from the grid.

### CODE REVIEW

**Comment by jolelievre** [comment]
TODO: change target to develop, and try to improve memory usage a bit more

**Comment by Hlavtox** [comment]
@MatShir @ShaiMagal @kpodemski  Maybe this would be a good oportunity to get rid of those “custom” feature values, wdyt?

**Comment by kpodemski** [comment]
@Hlavtox I don't think so, it is not that important and perf optimization is a different subject

**Comment by MatShir** [comment]
@Hlavtox I prefer focusing on improving the UI to prevent systematic custom values and enhancing the creation of feature values from the form.

**Comment by Hlavtox** [comment]
@MatShir Yeah, I think if people could search in the features and create them on the go, it will greatly improve the workflow and remove the bambilions of duplicate values people have in the stores. :-))

**Review by matthieu-rolland — DISMISSED** [review]
ah this good old Jquery 👍  :D

**Review by M0rgan01 — COMMENTED** [review]
@jolelievre can you resolve conflict please ? :)

**Review by M0rgan01 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by Hlavtox** [comment]
Looks good! 

@MatShir We easily create a new value in all languages, why don't we take this opportunity to finally be able to create features on the fily? :-) It would be so much easier. Now if you want to PROPERLY create a feature without duplicate, you must go to the features page and create it there. It would be an easy thing for Jonathan to create a regular feature value instead of the "custom one". And we could get rid of them finally...

Snímek obrazovky 2024-01-08 171418

Also @jolelievre please check responsivity, it's unusable on mobile. :-)

**Comment by MatShir** [comment]
I recommend quickly checking the mobile. @Hlavtox, the new behavior, is a great idea but it should be done in a separate PR. Let's finish and merge it to move forward.

**Comment by jolelievre** [comment]
Ok I made a simple modification for mobile, I simply display the select in column instead of row, that will do the job for now If it's not enough then it should be designed and handled in a different PR

**Review by boubkerbribri — APPROVED** [review]
LGTM for UI tests

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @jolelievre,

I tested your PR and it's good for me! :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Pull request merged**
