### PR TITLE
Add responsive nav-bar

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | Add responsive menu
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional)
| How to test?  | Check responsive mockups

### CODE REVIEW

**Comment by vincentbz** [comment]
Some bugs in the navigation, see details here : http://forge.prestashop.com/browse/STAB-70

**Comment by vincentbz** [comment]
Another feedback, on the notifications : 
 - when there are some notifications, it's not correctly displayed (see image). When there are no notification, it's ok 
 - is it possible to close the notification tab by clicking on the notification icon please ? like to open it

Thanks !

With notifications (can't see the new message notif tab, the new customers is not entire)
image

Without notifications
image

**Comment by vincentbz** [comment]
Last one : when I want to modify translations of an installed languaged, I should have a "not available page" but I have a blank page with nothing to see/do

**Comment by nihco2** [comment]
@vincentbz it's fixed, could you please check again ?

**Comment by vincentbz** [comment]
Seen with Nico, it's now ok, thanks !

**Comment by thierrymarianne** [comment]
Thanks @nihco2 @vincentbz!

**Pull request merged**
