### PR TITLE
Fix forgotten tab

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | @nicosomb Found one more usage of tab. The method is not used and maybe doesn't work at all, but for sake of consistency.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | 
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@Hlavtox isn't it used in Email settings when you want to send the test email? if not, maybe we could remove it

**Comment by Hlavtox** [comment]
@kpodemski Yeah, there are many unused methods in that file, but I would clean it in separate PR?

**Comment by kpodemski** [comment]
@Hlavtox makes sense

btw. my understanding is that every JS code that called `tab` has to be changed to `controller`? if so, we need to mention it in the devdocs

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional FYI: this method hasn't been used for ages, probably since we migrated email settings page, I'm merging this PR and @Hlavtox will take care of cleaning admin.js in a separate PR :)

**Comment by Hlavtox** [comment]
@kpodemski Yes exactly. The fix is not difficult and it will concern only really old code. Because even 1.6 was already using `controller`. So, no need to put any conditions anywhere. 

The original PR has the label "needs documentation" so it should not be forgotten. https://github.com/PrestaShop/PrestaShop/pull/34525

**Comment by kpodemski** [comment]
@Hlavtox awesome, thanks

**Comment by Hlavtox** [comment]
PR cleaning up the files - https://github.com/PrestaShop/PrestaShop/pull/36110

**Pull request merged**
