### PR TITLE
[-] FO : Fix loyalty to work in 1.6.1.4 (and probably earlier 1.6.1.x…

### PR DESCRIPTION
**Pull request by DavidEschmeyer**
## Description

default bootstrap loyalty files needed updating to work. Noticed it was not working in 1.6.1.4. The module must have gotten ahead of the theme module files.
## Steps to Test this Fix

1) Install 1.6.1.4 with default-bootstrap.
2) Notice loyalty does not work in the product page (says no points)
3) Replace 2 files from the main module folder (/modules/loyalty) into default-bootstrap
4) Notice it works.
## Forge Ticket (optional)

none

### CODE REVIEW

**Comment by dave-lp** [comment]
one file was wrong, redoing

**Comment by inetbiz** [comment]
I think you're suppose to pull a PR from the develop branch of PS?

**Comment by dave-lp** [comment]
this is for 1.6.1.x.  I made new pull req.  develop maybe too?

**Comment by dave-lp** [comment]
nope this wont work in 1.7 which is dev branch... i will look into forward changes for that theme

**Pull request closed without merging**
