### PR TITLE
Fix TinyMCE not loading on safari in CMS page

### LINKED ISSUE #15272: TinyMCE doesn't show on Safarii, js bug
TinyMCE doesn't show on Safarii, js bug. On console we see error: 

[Error] Error: Syntax error, unrecognized expression: input[name^="cms_page[title](main.bundle.js:253:94328)

PrestaShop version: 1.7.6.0
PHP version: 7.2

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | CMS Page in BO was broken on safari because JS Selectors were not closed
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15272 
| How to test?  | Go in the BO in Appearance -> Pages, select a page and TinyMCE should work in the content of the page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16535)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
LGTM

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

It is OK.
image

Thanks!

**Comment by PierreRambaud** [comment]
Thanks @NeOMakinG

**Comment by matks** [comment]
@PierreRambaud @NeOMakinG this PR adds 17,123 lines to the codebase

I might be wrong, but I think something is strange 😄

**Comment by PierreRambaud** [comment]
@matks You're right, seems the dev assets has been committed. Another reason to stop commit these useless files.

**Pull request merged**
