### PR TITLE
CO: Fix the links sent in the mails (multilingualism)

### PR DESCRIPTION
**Pull request by GuillaumeGBzh**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.6.1.x
| Description?  | Fix the links sent in the mails (multilingualism). Currently, the links are built on the language of the Context.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Send an email to a client who does not have the default language of the site (and that of the context).

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8742)

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]
Sounds interesting!

**Comment by marionf** [comment]
Hello @GuillaumeGBzh 

I just tried without your PR the welcome and newsletter emails. Links to the website are well in the language of the customer (ES) and not in the default language (FR)

capture du 2018-03-12 18-00-13

capture du 2018-03-12 18-00-31

capture du 2018-03-12 18-04-47

Can you tell me in which email is the issue ?

Thanks :)

**Comment by GuillaumeGBzh** [comment]
Hello @marionf,

In fact, I forgot to specify one thing (and not least).
I was in a cli/cron context when I used the Mail::send() method. 

Guillaume

**Review by mickaelandrieu — APPROVED** [review]

**Comment by GuillaumeGBzh** [comment]
This fix has been merged for Prestashop 1.7.x.
Strangely, this is not the case for Prestashop 1.6.1.x.

**Pull request closed without merging**
