### PR TITLE
CORE : Fix #PSCSX-6452 - Customer getLastCart return condition

### PR DESCRIPTION
**Pull request by fkwakkenbos**
FIX for Core BUG: http://forge.prestashop.com/browse/PSCSX-6452

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi, thank you for your contribution,

Can you please report your PR on 1.6.1.x branch ?

Best regards.

**Comment by fkwakkenbos** [comment]
See: https://github.com/PrestaShop/PrestaShop/pull/3606

**Comment by fkwakkenbos** [comment]
Done so, please see: https://github.com/PrestaShop/PrestaShop/pull/3607

**Comment by gRoussac** [comment]
Hi,

There seems to be a missunderstanding here becasue of the name of the function.

The only use is /controllers/admin/AdminCartsController.php line 302 and this is inteded to receive false when the last cart of the customer has  no product. IE make a new cart if the last cart has products, otherwise make a new one.

getLastCart shoud be called getLastAvailableFreeCart or something like that.

Regards

**Comment by fkwakkenbos** [comment]
Hmm, I missed that one.
I suggest we rename the function into: "getLastEmptyCart" to solve this confusion.

Let me explain our situation.
When a customer starts his/her payment, we create a new Order from his Cart.
The new Order will get a custom order_state: "Waiting for payment".
When the customer decides to use his Back Button of the Browser, he/she will return in the old Cart on the OnePageCheckout.
This Cart is already turned into an Order and the Cookie does not contain any Cart at that moment.
So when the Customer decides to click on the Payment Button, the procedure wants to turn it's Cart again into an Order.
In this case we developed some code which checks this situation.
At this point we need to get the latest Cart which is turned into an Order and contains Products.
That's why we needed the function getLastCart....

Shall I rename the existing function into "getLastEmptyCart" and als change the AdminCartsController?

We decided to not use a function on Customer Core.
We instead create our own function inside the Module....
This is better because nothing else in the Core PrestaShop uses this functionality.

**Comment by fkwakkenbos** [comment]
I renamed the function, please see: https://github.com/PrestaShop/PrestaShop/pull/3607

**Comment by fkwakkenbos** [comment]
Please re-evaluate this pull request.

**Comment by gRoussac** [comment]
:+1:

**Comment by jeromenadaud** [comment]
Nice ! thank you.

**Pull request merged**
