### PR TITLE
Theme and logo page design fixes

### PR DESCRIPTION
**Pull request by tomas862**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | There are some design issues mentioned in the issue https://github.com/PrestaShop/PrestaShop/issues/13467
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/13467
| How to test?  | the issues mentioned in https://github.com/PrestaShop/PrestaShop/issues/13467 should no longer exist

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13690)

### CODE REVIEW

**Comment by tomas862** [comment]
@matks this one has still one issue remaining but its related with `Ps_Themeconfigurator` module.

**Review by matks — DISMISSED** [review]

**Comment by sarahdib** [comment]
@tomas862 the first issue seems still here 
Capture d’écran 2019-05-14 à 12 10 21

**Comment by tomas862** [comment]
@sarahdib - yes it still is but its related with certain module called `Ps_Themeconfigurator`. @matks confirmed me that this problem will be solved in another place but not withing this PR :)

**Comment by matks** [comment]
Looks like Travis feedback got lost :/ @tomas862 can you add anything (like a phpDoc fix) to re-trigger it ?

I have tried relaunching it from Travis but I think the connection between github and travis was severed so github is unable to identify the callback from Travis. A new commit will reset the whole feedback loop.

**Comment by tomas862** [comment]
done :)

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @tomas862

**Pull request merged**
