### PR TITLE
Enable migrated Title page and Remove AdminGendersController

### LINKED ISSUE #10628: Migrate "Shop parameters > Customer settings > Titles" page
Part of Symfony migration project
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Enable migrated Title page and Remove AdminGendersController
| Type?             | new feature
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI is :green_circle: & Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/5420688315
| Fixed ticket?     | Fixes #10628
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

### CODE REVIEW

**Review by boherm — DISMISSED** [review]
LGTM, thanks @Progi1984!

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by M0rgan01 — DISMISSED** [review]

**Comment by Progi1984** [comment]
Hi @PrestaShop/committers, I have one approval for @boherm. Can I have a second review when you will have some availability, plz ? Thanks

**Comment by Progi1984** [comment]
@boherm Need reapprove after rebase.

**Review by nesrineabdmouleh — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/committers @PrestaShop/prestashop-maintainers @PrestaShop/ui-tests-maintainers Rebased a new time

**Review by boherm — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
LGTM for UI tests

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by Progi1984** [comment]
@committers @prestashop-maintainers Need review when you have some availability

**Review by nicosomb — APPROVED** [review]
I know that you didn't change anything to this section, but maybe you can delete `currentUrl` (`'currentUrl' is assigned a value but never used`).

**Comment by Progi1984** [comment]
@nicosomb It's noted. @boubkerbribri and me have decided to remove it in another PR (we want to add a eslint plugin for warnings).

**Review by aniszr — APPROVED** [review]
Hello @Progi1984 

I tested your PR, all the changes added to Titles page are well displayed :heavy_check_mark: 

See attached screenshot : 

image

Auto test : https://github.com/aniszr/ga.tests.ui.pr/actions/runs/5782126698 :heavy_check_mark: 
QA :heavy_check_mark: 

Thanks!

**Comment by jolelievre** [comment]
Thanks @Progi1984 and @aniszr

**Pull request merged**
