### PR TITLE
[-] IN : Fix #PSCSX-6700, could not install in Czech, …

### PR DESCRIPTION
**Pull request by gRoussac**
:warning:  missing translation for fixtures data, still needs translation to be done :warning: 

@AlexEven please review it !

### CODE REVIEW

**Comment by gRoussac** [comment]
:collision: @jeromenadaud We can not install in Czech, are we waiting @AlexEven or do we merge in english for the moment ?

**Comment by AlexEven** [comment]
@gRoussac - we have some of these translations available in Czech (I think/hope), I have to see what we can retrieve from Crowdin.

**Comment by gRoussac** [comment]
:bride_with_veil:

**Comment by AlexEven** [comment]
https://github.com/PrestaShop/PrestaShop/pull/4130

**Pull request merged**
