### PR TITLE
Update welcome module version

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Onboarding redirect to page not found
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5354
| How to test?  | Create a virtualhost, run welcome module.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9077)

### CODE REVIEW

**Review by tomlev — APPROVED** [review]

**Comment by ntiepresta** [comment]
I executed this PR, the problem is not resolved in branch 1.7.4.x

**Comment by PierreRambaud** [comment]
@ntiepresta Did you make a `composer install` after switching branch?

**Comment by ntiepresta** [comment]
Thank you @PierreRambaud for your contribution.
This PR solves this bug : http://forge.prestashop.com/browse/BOOM-5354.

**Comment by eternoendless** [comment]
Thank you @PierreRambaud

**Pull request merged**
