### PR TITLE
Override admin and front controllers of modules

### PR DESCRIPTION
**Pull request by alexdee2007**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This feature allows to override ModuleAdminController and ModuleFrontController by adding it in /override/modules/controller/admin or /override/modules/controller/front
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  |

This feature allows to override ModuleAdminController and ModuleFrontController by adding it in /override/modules/controller/admin or /override/modules/controller/front

The new file should contain the ModuleAdminController or ModuleFrontController class extending the name with an "Override" suffix and extending the ModuleAdminController's or ModuleFrontControllerr's name to be its child.

Example:

```
override/modules/productscomment/controllers/front/default.php

class ProductCommentsDefaultModuleFrontControllerOverride extends ProductCommentsDefaultModuleFrontController {
    ..............
}
```

### CODE REVIEW

**Comment by xBorderie** [comment]
You're back, cool! I was afraid that, after three malformed PR, you had given up :)

Seems like you're on the right path here! You still have two commits when one would be enough (and a typo on "override" ;) ), but otherwise, the commit names are good to go. 

I'll let the developers review your code and give you a feedback on your proposal. In the meantime, I updated your PR description text with a more detailed one that you gave in a previous PR.

Thank you for your contribution!

**Review by rnabiullin — APPROVED** [review]
I tested this PR and it work excellent, but I would add strtolower to front controllers

**Review by Quetzacoalt91 — APPROVED** [review]
This PR is okay for me too. Code reviewed and tested.

**Comment by Quetzacoalt91** [comment]
Example used:

### override/modules/gamification/controllers/admin/AdminGamificationController.php
```php
<?php

class AdminGamificationControllerOverride extends AdminGamificationController
{
    public function __construct()
    {
        dump('Override gotcha!');
        parent::__construct();
    }
}
```

**Comment by Quetzacoalt91** [comment]
Thank you @alexdee2007, it took some time for us to include your changes, but it is now done.

The feature should be available on the next version 1.7.2.0 of PrestaShop.

Best regards

**Comment by kpodemski** [comment]
👍

**Comment by nabiyllin** [comment]
@Quetzacoalt91 can you merge this feature to 1.6 branch?
This feature really useful for our team and for old projects.

**Comment by maximebiloe** [comment]
Hello @nabiyllin,

We won't report this modification into `1.6.1.x` because we'll only do bugfixes, we won't add any new features.

Regards

**Pull request merged**
