### PR TITLE
add a checkbox, to check/uncheck all elements in the countries table

### PR DESCRIPTION
**Pull request by fgaroby**
| Questions | Answers |
| --- | --- |
| Branch? | `1.6.1.x` |
| Description? | Add a checkbox in the head of the "Countries" table, to check/uncheck all elements in this table |
| Type? | improvement |
| Category? | BO |
| BC breaks? | non |
| Deprecations? | non |
| How to test? | Go to "Localization" -> "Countries" |

### CODE REVIEW

**Comment by firstred** [comment]
Thanks for your pull request.

Did you know that you can select all by using the Bulk Actions?
bulkactions

I'm not sure if such a behavioral change on just the Countries table would be a good idea.

**Comment by kpodemski** [comment]
@firstred there's no bulk actions in Countries tab

**Comment by firstred** [comment]
Is that a 1.6 screenshot? It is available on the targeted branch `develop`

**Comment by kpodemski** [comment]
@firstred yeah, i guess @windu2b want's to have it on 1.6, i guess you can change branch from administrator ui

**Comment by firstred** [comment]
Mehh, that causes this kind of trouble. It is indeed obvious that @windu2b wanted to have it fixed on 1.6

@windu2b Would you mind rebasing it against the `1.6.1.x` branch? Thanks in advance!

**Comment by windu2b** [comment]
@firstred : Yes, I want to rebase it against the `1.6.1.x` branch, because we will soon use this version, in production.

**Comment by firstred** [comment]
Okay, I'll just wait for your rebase then :)

**Comment by windu2b** [comment]
Hummm... I think I didn't do the good thing. My bad !
I did a new PR (#6707), sorry.

**Pull request closed without merging**
