### PR TITLE
Improve sitemap-nested-list.tpl

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Don't add "nested" class when $is_nested is falsy and Simplify link.children checking in cms tpl because Empty already checks count
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | the sitemap should display as before.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20309)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Hello @davidglezz, can you provide the path to test ? QA testing is necessary unless you're only changing something that could not change anything by default (comments for example)

Changing some conditions inside a smarty template can provide side effects, I would say that we need to put QA there !

wdyt @PrestaShop/prestashop-core-developers ?

**Comment by SimonGrn** [comment]
Hello, 
I'm juste upping this PR since we didn't get any news from the author. Should it be closed ?

Thanks

**Comment by davidglezz** [comment]
path to test: the sitemap should display as before.

**Comment by davidglezz** [comment]
I can say a case where it does not perform as expected. (Note `is_nested=false` argument)
```
{include file='cms/_partials/sitemap-nested-list.tpl' links=$link.children is_nested=false}
```
In the old code `is_nested=false` === `is_nested=true`. The expected behabeour is that render diferent markup.

I fixed that. It is not currently used but it prevent a possible hard to find error in the future.

**Review by PierreRambaud — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
It's now ready for QA

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

It is ok :heavy_check_mark: 
image
https://drive.google.com/file/d/16uqeEK_flfEZGvcXGO04ZjiUiCDvSACB/view?usp=sharing

Thanks!

**Comment by Progi1984** [comment]
Thanks @davidglezz

**Pull request merged**
