### PR TITLE
Fix Carrier Wizard summary display (1.7)

### PR DESCRIPTION
**Pull request by firstred**
| Questions | Answers |
| --- | --- |
| Branch? | `develop` |
| Description? | Fixes the Carrier Wizard summary. See screenshots. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8395 |
| How to test? |  |

Before:
carrierwizardbefore

After:
carrierwizardafter

### CODE REVIEW

**Comment by PrestaEdit** [comment]
See this one: https://github.com/PrestaShop/PrestaShop/pull/5704

**Comment by firstred** [comment]
Ssshh, let's keep repeating the PR until it's actually solved :stuck_out_tongue_winking_eye:

**Comment by PrestaEdit** [comment]
:+1:  ; it's for the thread. You will see why it's not merged yet, :)

**Comment by basma-yangui-prestashop** [comment]
That works fine!

**Comment by firstred** [comment]
We should introduce the xss library to the back office or something like that...

**Pull request closed without merging**
