### PR TITLE
Fixed duplicate address in checkout

### LINKED ISSUE #23808: Duplicate address in checkout Address step on address edition
#### Describe the bug
In the FO, when we try to change the country of an address, a duplicate address is created instead of updating the selected address

#### Steps to Reproduce

Steps to reproduce the issue:

1. Enable France & United states countries in the BO > International > Location > Countries page
2. Go to FO > Sign in with John Doe
3. Add a product to the cart
4. Click on Proceed to checkout
5. In the Address step: Edit the country from France to "United States"
6. Click "Save"
7. Click on the "Address step" => Duplicated Address

**Screenshots**

https://drive.google.com/file/d/1YwU4rUQaNV3B6qel0Z43SWDS_5Z00uT9/view?usp=sharing

#### Additional information

* PrestaShop version: 1.7.7.2, 1773build1, 1769
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix duplicate address in checkout Address step on address edition
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23808
| How to test?      | see issue
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24920)

### CODE REVIEW

**Comment by jf-viguier** [comment]
Thanks to @DelecroixQuentin who let me pr his fix

**Comment by jf-viguier** [comment]
Thanks to @DelecroixQuentin who let me pr his fix

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Nice catch ;)

**Review by PululuK — APPROVED** [review]

**Comment by PululuK** [comment]
@Progi1984 @jf-viguier   `1.7.8.x` instead of `develop` ?

**Review by kpodemski — APPROVED** [review]

**Comment by Progi1984** [comment]
> @Progi1984 @jf-viguier   `1.7.8.x` instead of `develop` ?

No it was in `1.7.6.x` so it's not a regression.

**Comment by florine2623** [comment]
LGTM

Thanks @jf-viguier !

**Comment by Progi1984** [comment]
Thanks @jf-viguier & @florine2623

**Pull request merged**
