### PR TITLE
FO : Fix offset for "NEW" products listing

### LINKED ISSUE #27737: Product listed as "New" but without flag
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

New products in `/new-products` front controller appears without "NEW" flag:

image

### Expected behavior

All "new products" should appear with "NEW" flag

### Steps to reproduce

1. Open `https://domain/new-products`
2. Check that all products have "NEW" flag
3. Edit `date_add` from table `ps_product_shop` from some product, and set a date 20 days before today. For example, from 19/02 to 30/01.
4. Refresh `https://domain/new-products`
5. Check that the product edited in step 3 is listed but wihtout "NEW" flag

_* If the product edited in step 3 doesn't appear, set the following day. If the product is listed with "NEW" flag, set a previous day. There's only one day difference to reproduce the issue._

### PrestaShop version(s) where the bug happened

1.7.8.3

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by idnovate**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There is a 1-day offset for new products listed and "NEW" flag
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27737
| How to test?      | Check bug fixed

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27738)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]
LGTM !

I approve this PR but it should not be sent in QA before the issue is validated

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Review by tegbessou — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @idnovate 

I encounter these two issues with your PR:

**1. 1st issue:**

I created a product in `2022-03-06 00:35:12`, when I set the `Number of days for which the product is considered 'new'` as 3 (or 4 or 5): 

- the label `New` is well displayed on the product :heavy_check_mark: 
- but I can't find any product in the **New Products** page :x: 

https://user-images.githubusercontent.com/23308427/157218181-6a1e71f8-1e44-4ab4-90d0-5906d54b47fd.mp4

**2. 2nd issue:**

Changing the `Number of days for which the product is considered 'new'` as 6, while other products are created in `2022-03-02 00:35:12`: it should only display the products created after `2022-03-02 11:36:00`:

- the label New is not assigned to the created products in `2022-03-02 00:35:12` :heavy_check_mark: 
- all products are dispalyed in **New Products** page :x: 

https://user-images.githubusercontent.com/23308427/157220252-e6b9d166-763d-4e6f-8904-b334f1fcaae4.mp4

Please check and feedback.
Thanks!

**Review by hibatallahAouadni — CHANGES_REQUESTED** [review]
Hello @idnovate 

I encounter these two issues with your PR:

**1. 1st issue:**

I created a product in `2022-03-06 00:35:12`, when I set the `Number of days for which the product is considered 'new'` as 3 (or 4 or 5): 

- the label `New` is well displayed on the product :heavy_check_mark: 
- but I can't find any product in the **New Products** page :x: 

https://user-images.githubusercontent.com/23308427/157218181-6a1e71f8-1e44-4ab4-90d0-5906d54b47fd.mp4

**2. 2nd issue:**

Changing the `Number of days for which the product is considered 'new'` as 6, while other products are created in `2022-03-02 00:35:12`: it should only display the products created after `2022-03-02 11:36:00`:

- the label New is not assigned to the created products in `2022-03-02 00:35:12` :heavy_check_mark: 
- all products are dispalyed in **New Products** page :x: 

https://user-images.githubusercontent.com/23308427/157220252-e6b9d166-763d-4e6f-8904-b334f1fcaae4.mp4

Please check and feedback.
Thanks!

**Comment by idnovate** [comment]
I think that I miscount the days.

If you set, for example, `3 days` as new, if you upload a new product today 14th, it would be considered as new the 14th, 15th and 16th (3 days).

_Please note that only the days are considered, not the hour:_
https://github.com/idnovate/PrestaShop/blob/7b698009500ba6f90224bf7eea858b33c5642b2d/classes/Product.php#L2887

So, according to the new tests done today 14th March, it is displayed as `New` the 14th, 13th and 12th.

image

Product created 3 (or 4) days ago:
image
image
image

Product created 3 (or 2) days ago:
image
image
image

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Review by hibatallahAouadni — CHANGES_REQUESTED** [review]
Hello @idnovate 

Thanks for your PR :rocket: and your patience :pray: 
It looks good except the pagination, it looks like you haven't worked on it :sweat_smile: 
Check the attached screen record below:

https://user-images.githubusercontent.com/23308427/160596748-f41bc262-678c-4210-9f32-09180e292be9.mp4

As you can see, it should display 4 products and no pagination buttons.
Waiting for your feedback.

Thanks!

**Review by Progi1984 — DISMISSED** [review]

**Review by hibatallahAouadni — COMMENTED** [review]
@PrestaShop/prestashop-core-developers can someone please add a review, so I can test this PR :pray: 
Thanks in advance!

**Review by kpodemski — DISMISSED** [review]

**Review by hibatallahAouadni — DISMISSED** [review]
Hello @idnovate 

Thanks for your hard working :raised_hands: 
LGTM, QA :heavy_check_mark: 

https://user-images.githubusercontent.com/23308427/167701807-386a2155-ce31-447b-8d60-19f7f81a8383.mp4

Thanks!

**Comment by hibatallahAouadni** [comment]
@PrestaShop/prestashop-maintainers it seems the issue is a regression on 178x, should it be the base branch 178x not develop?

**Comment by matks** [comment]
@idnovate There is 2 issues in this Pull Request
- it contains Merge commits so the validator rejects it
- as said by @hibatallahAouadni it should target branch `1.7.8.x`

As you opened this PR in February, I dont want to be a burden ^^ so if you are OK I can do it. Do you agree I update your branch to make your PR valid?

**Comment by idnovate** [comment]
> @idnovate There is 2 issues in this Pull Request
> 
> * it contains Merge commits so the validator rejects it
> * as said by @hibatallahAouadni it should target branch `1.7.8.x`
> 
> As you opened this PR in February, I dont want to be a burden ^^ so if you are OK I can do it. Do you agree I update your branch to make your PR valid?

You make me a favour 🙌

**Comment by matks** [comment]
Rebase and branch switches done

**Comment by matks** [comment]
Thank you @idnovate

**Pull request merged**
