### PR TITLE
// recommended modules display on product page

### PR DESCRIPTION
**Pull request by xGouley**

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi!

Are you sure that throwing an error is the best solution?

**Comment by xGouley** [comment]
Not throwing, catching it.

**Comment by Shudrum** [comment]
As I understand, you use a `throw`and a `catch` for a standard behavior?

But if an error is really throwed during `getCatalogModules()`, this will be a silent error…

**Comment by xGouley** [comment]
Exact : silent error, for the moment, and then in the tpl, there is an alternative behavior. Waiting for functional feature specification for the next step.

**Comment by Shudrum** [comment]
Yep, but I'm pretty sure that a simple `break` will be a better solution.

**Comment by xGouley** [comment]
Well, just understood your objection, but the try catch is here for the $modulesProvider->getCatalogModules() call that throws another exception.

**Comment by xGouley** [comment]
New solution with smaller try catch, and proper continue statements.

**Comment by Shudrum** [comment]
But there is still a silent error …

**Pull request merged**
