### PR TITLE
Remove mcrypt encryption code

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Test already skipped, deprecated since PHP 7.1, removed in PHP 7.2.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | n/a
| How to test?      | GH CI must pass
| Possible impacts? | no, as mcrypt is not availabe in PHP, thus removed code that uses it can not be broken more

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23974)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
This is still available for PHP7.1, and this version is still compatible with PHP7.1

**Comment by mvorisek** [comment]
> 
> 
> This is still available for PHP7.1, and this version is still compatible with PHP7.1

This is correct, but for PHP 7.1 there is already a full replacement. Not indended to be used from user/module code directly, thus safe to remove.

**Comment by PierreRambaud** [comment]
> > This is still available for PHP7.1, and this version is still compatible with PHP7.1
> 
> This is correct, but for PHP 7.1 there is already a full replacement. Not indended to be used from user/module code directly, thus safe to remove.

There is a replacement, but it doesn't mean, people have configured it yet. It's a huge BC breaks.

**Comment by Progi1984** [comment]
I close as Mcrypt is always by default in PHP 7.1.

https://www.php.net/manual/fr/intro.mcrypt.php

**Comment by mvorisek** [comment]
@Progi1984 see https://github.com/PrestaShop/PrestaShop/issues/20739#issuecomment-822462017 , please reopen, develop/1.7.9 is meant to not support PHP 7.1, and in PHP 7.2 this code is useless :)

related with https://github.com/PrestaShop/PrestaShop/pull/24476

**Comment by Progi1984** [comment]
Actually, no decision has been decided about the drop out of PHP 7.1

**Comment by mvorisek** [comment]
@Progi1984 reopen, PHP 7.1 no longer supported

**Pull request closed without merging**
