### PR TITLE
[+] FO : Add manufacturer name in cart products

### PR DESCRIPTION
**Pull request by cedricfontaine**
Add the manufacturer name in cart product. It's needed in various area, like in the google analytics module.

### CODE REVIEW

**Comment by vincentbz** [comment]
Hi @cedricfontaine,

Would it be possible to update your PR so that we can validate and merge it please? :)

**Comment by cedricfontaine** [comment]
What should I update ?

**Comment by mickaelandrieu** [comment]
@cedricfontaine you only need to rebase against `develop`, cause `develop` was broken and fixed today. So your build will probably become green, and your PR merged ;)

Mickaël

**Comment by cedricfontaine** [comment]
Sorry, I've no idea how to rebase.

**Comment by aleeks** [comment]
Hello,
Closing this PR, just cherry-pick your commit here: https://github.com/PrestaShop/PrestaShop/pull/7461/commits

**Pull request closed without merging**
