### PR TITLE
Prevent injections in SQL in classes

### PR DESCRIPTION
**Pull request by aleeks**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Prevent injections in SQL (CMSCategory, COnfiguration, Category, Dispatcher, Search, Tag, stock/SupplyOrder) |
| Type? | bug fix |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1468, http://forge.prestashop.com/browse/BOOM-1469, http://forge.prestashop.com/browse/BOOM-1458, http://forge.prestashop.com/browse/BOOM-1456, http://forge.prestashop.com/browse/BOOM-1457, http://forge.prestashop.com/browse/BOOM-1452 |
| How to test? | Browse the site and see if something is broken.. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by maximebiloe** [comment]
Thank you!

**Comment by xBorderie** [comment]
Could this be interesting for 1.6.1.8?

**Comment by Id2iDev** [comment]
Hi, your modification doesn't works when webservice call to add/edit products in Search Class.

$queryArray3 can be an array of array
So we get this error : 
`[SQL Error] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0,0,0,0,0
				ON DUPLICATE KEY UPDATE weight = weight + VALUES(weight)' at line 2. From SearchCore->saveIndex() Query was : INSERT INTO ps_search_index (id_product, id_word, weight)
				VALUES 0,0,0,0,0
				ON DUPLICATE KEY UPDATE weight = weight + VALUES(weight)`

**Comment by aleeks** [comment]
@Id2iDev ok thank you, it's in https://github.com/PrestaShop/PrestaShop/pull/6391

**Pull request merged**
