### PR TITLE
[-] BO : Not updating OrderInvoice addresses

### PR DESCRIPTION
**Pull request by djbuch**
The address caches should be updated when the address of an order is edited

### CODE REVIEW

**Comment by firstred** [comment]
Hi @djbuch 

Thanks for your PR and sorry for the long wait (are you still around?)

This looks like a good PR to me. Could you please rebase it, so that we can test it? Thank you!

**Comment by firstred** [comment]
Basically what this PR does is update the registered Address in the OrderInvoice when the Address of an order has been changed.

**Comment by xBorderie** [comment]
@firstred If you find this PR good to take, and since @djbuch doesn't seem responsive (who can blame him?), do you think you could pick his commits into a new PR?

**Comment by antoin-m** [comment]
Thank you @djbuch, I cherry-picked your PR here https://github.com/PrestaShop/PrestaShop/pull/7498

**Comment by vincentbz** [comment]
Hi @djbuch 

I've tried to reproduce the bug before applying your fix and I can't. here is what i've done : 
 - two orders (1 and 2) with an address A, validated
 - In the order 2, I modify the delivery or invoice address 
 - the address is changed only for that order on the invoice and in the order display

Did I miss something ? :)
It seems to be the expected behaviour.

Thanks !

**Pull request closed without merging**
