### PR TITLE
[*] BO : Allow to exclude tax and shipping in affiliation sales total

### PR DESCRIPTION
**Pull request by cedricfontaine**

### CODE REVIEW

**Comment by maximebiloe** [comment]
Hello,

Thanks for contributing.
As all your commits have the same message, could squash them into one, please ?

Best regards

**Comment by cedricfontaine** [comment]
Sorry, but how do you do that ?

**Comment by maximebiloe** [comment]
By using `git rebase -i`.
You can take a look at [that] (https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

**Comment by cedricfontaine** [comment]
I'm sorry but I'm using the web version. Could you do without rebase ?

**Comment by aleeks** [comment]
Hello @cedricfontaine 
Rebased from develop here https://github.com/PrestaShop/PrestaShop/pull/7491 cherry-picking your commit.

For next time, please, consider our commit convention.

**Pull request closed without merging**
