### PR TITLE
Fix resetLanguage for Currencies

### LINKED ISSUE #31759: Currencies : The reset of currency format doesn't work
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

After editing a currency format with a custom symbol, the reset doesn't work

### Expected behavior

After editing a currency format with a custom symbol, the reset work (the example column is up-to-date).

### Steps to reproduce

Detected by #31761

1. Go to Currencies page
2. Edit the EUR currency
3. Edit the symbol for English (English) language
4. Define with a custom symbol (`@`, for example)
5. Save the modal
6. The currency format example is up-to-date with `@`
7. Save the currency
8. :tada: The currency use the custom symbol
9. Edit the EUR currency
10. Reset the currency format for English (English) language
11. :red_circle: The currency format example is not up-to-date with `€`
12. Save the currency
13. :red_circle: The currency don't use the symbol `€`

### PrestaShop version(s) where the bug happened

8.1.x

### PHP version(s) where the bug happened

7.3

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Fix `resetLanguage` function in `CurrencyFormatter.vue` to refresh properly currency data.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31759 
| Fixed ticket?     | Fixes #31759 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Review by 0x346e3730 — DISMISSED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@boherm Hi, Thank you for your contribution. Could you please update UI tests which allows us to detect the code : 

* https://github.com/PrestaShop/PrestaShop/blob/8.1.x/tests/UI/campaigns/cldr/08_resetSymbolFormatSettings.ts#L142-L175
* https://github.com/PrestaShop/PrestaShop/blob/8.1.x/tests/UI/campaigns/cldr/07_editSymbolFormatCurrency.ts#L124-L148

**Review by djoelleuch — DISMISSED** [review]
Hello @boherm 
The issue is well fixed , It's QA approved :heavy_check_mark: 

[Untitled_ Apr 12, 2023 5_04 PM.webm](https://user-images.githubusercontent.com/115152460/231500476-79875f07-895a-4309-a7bb-182798e99964.webm)

Automated tests --> OK

Thank you for you PR :rocket:

**Review by mflasquin — APPROVED** [review]

**Comment by boherm** [comment]
Thanks for your informations @Progi1984 and @djoelleuch!
FYI, I've add a new commit to unskip some tests like it said in comments related to this issue.

**Comment by Progi1984** [comment]
If the CI is :green_circle: 
If the Nightly is :green_circle: : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/4680122317

Ok for merge.

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Ping @boubkerbribri / @nesrineabdmouleh

**Review by nesrineabdmouleh — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
thank you @boherm and @nesrineabdmouleh

**Pull request merged**
