### PR TITLE
Remove Escape percentage in parameters

### LINKED ISSUE #12556: Installation Error : the % symbol is doubled on the parameters.php file generation
**Describe the bug**
When you put a database password with the symbol "%" at installation, this character is doubled in the parameters.php file
It caused me a lot of trouble

**To Reproduce**
1. Start a new install of prestashop
2. In the database configuration step, put a password with a % symbol
3. Finish the installation and look at the /app/config/parameters.php
4. See error on the database password

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.1

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Remove Escape percentage in parameters (#6649)
| Type?         | bug fix
| Category?     | IN
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #12556
| How to test?  | * Create a user mysql with a password with no percent<br>* Install PrestaShop with this user<br>* Explore BackOffice (migrated & legacy pages) & FrontOffice<br>* Create a user mysql with a password with one percent<br>* Install PrestaShop with this user<br>* Explore BackOffice (migrated & legacy pages) & FrontOffice<br>* Create a user mysql with a password with two percents<br>* Install PrestaShop with this user<br>* Explore BackOffice (migrated & legacy pages) & FrontOffice<br>* Create a user mysql with a password with no percent<br>* Install PrestaShop with this user<br>* Explore BackOffice (migrated & legacy pages) & FrontOffice<br>* Change the password of the user with a percent<br>* Modify password in `app/config/parameters.php`<br>* Explore BackOffice (migrated & legacy pages) & FrontOffice<br><br><br>SQL Request for creating a user:<br>`CREATE USER 'userpercent'@'localhost';`<br>`ALTER USER 'userpercent'@'localhost' IDENTIFIED BY 'abcdef%1234' ;`<br>`GRANT ALL PRIVILEGES ON *.* TO 'userpercent'@'localhost';`<br>`FLUSH PRIVILEGES;`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19850)

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I tried to install this PR with database password: `%admin%`, but I have an error during the last step.
image

I attached a screen record
https://drive.google.com/file/d/1JrKQzpDRntHuah6pBpE6K9uD52L-QmQl/view?usp=sharing

Also, I tried to install this PR with database password: `admin` => OK

Thanks!

**Review by PierreRambaud — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Progi1984,

I tried to install this PR with database password: `%admin%` again => Well installed,
Bo => well displayed
FO => well displayed
I checked the file `Prestashop_folder/app/config/parameters.php`, I found this line
`'database_password' => '%%admin%%',`

The database password is incorrect.

Thanks!

**Comment by PierreRambaud** [comment]
> Hi @Progi1984,
> 
> I tried to install this PR with database password: `%admin%` again => Well installed,
> Bo => well displayed
> FO => well displayed
> I checked the file `Prestashop_folder/app/config/parameters.php`, I found this line
> `'database_password' => '%%admin%%',`
> 
> The database password is incorrect.
> 
> Thanks!

The value in this file is normal, it's how `%` is defined with Symfony :otherwise it's a replacement :wink:
Examples:
`%%test%%` => string `%test%`
`%test%` => is trying to find a parameter named `test`

**Comment by SD1982** [comment]
Hi @Progi1984 I also test this PR with @khouloudbelguith and we noticed an exception: 
image (1)

The step to reproduce:

1. install shop with mysql password with no %
2. Go to BO and stay on the dashboad page
3. Edit the mysql password and add a %
4. Edit the password in app/config/parameters.php
5. Go back to presta BO and refresh the page

If we delete the content of the var/cache folder it's OK again

@khouloudbelguith and I think that can possibly be resolved with that improvement https://github.com/PrestaShop/PrestaShop/issues/16715

**Comment by PierreRambaud** [comment]
> Hi @Progi1984 I also test this PR with @khouloudbelguith and we noticed an exception:
> image (1)
> 
> The step to reproduce:
> 
> 1. install shop with mysql password with no %
> 2. Go to BO
> 3. Edit the mysql password and add a %
> 4. Edit the password in app/config/parameters.php
> 5. Go back to presta BO and refresh the page
> 
> If we delete the content of the var/cache folder it's OK again
> 
> @khouloudbelguith and I think that can possibly be resolved with that improvement #16715

@SD1982 @Progi1984 @khouloudbelguith 
Since it's a manual change, it's mandatory to clear the cache manually after changing a configuration file outside the BO context.
If everything is ok after it, the PR is good to be merged :)

**Comment by Progi1984** [comment]
Thanks @SD1982 & @PierreRambaud

**Comment by SD1982** [comment]
And @khouloudbelguith :+1:

**Pull request merged**
