### PR TITLE
Changing classic theme filters alignments and spaces

### LINKED ISSUE #14376: [Classic theme] Faceted search module design issue on mobile device
**Describe the bug**
Design improvement required on mobile device for category page filter options. 

**Screenshots**
IMG_0158

 To fix:
Go to: `/var/www/html/practice/testshop1/modules/ps_facetedsearch/views/dist/font.css`
Remove below style at line 124:
`width: calc(100% - 30px);`

**Additionnal information**
PrestaShop version: 1.7.6 RC1

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Filters were not aligned on mobile with icon
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14376 
| How to test?  | Go on mobile, specially on iOS and open filters on category page, everything should be right aligned as specified in the issue

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16956)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@sarahdib you put milestone 1.7.8.0 for this ticket, is it on purpose ?

**Comment by sarahdib** [comment]
@matks the issue was in the backlog 1.7.8

**Comment by matks** [comment]
> @matks the issue was in the backlog 1.7.8

Can we merge it in develop for 1.7.7 as it was done earlier than expected, or do you wish we keep it for 1.7.8 ?

**Comment by sarahdib** [comment]
@matks as you wish :) it's ok for me :)

**Review by Progi1984 — APPROVED** [review]
Approved after force-pushed ;)

**Comment by Progi1984** [comment]
@matks So we merge it now, finally ?

**Comment by Progi1984** [comment]
I have had my answer : We wait for feature freeze 1.7.7.

**Comment by marionf** [comment]
It was in 1.7.8 backlog because it's not a priority for 1.7.7
@Progi1984 but if the PR is ready to be merged, we can do it right now ? 
Or is there something blocking that requires to wait the 1.7.8 ?

**Comment by Progi1984** [comment]
@marionf After discussion with @eternoendless, we don't add any new things to 1.7.7.

**Comment by Progi1984** [comment]
Thanks @NeOMakinG

**Pull request merged**
