### PR TITLE
The special offers are disappearing suddenly

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.4.x
| Description?  | Prefer MySQL NOW() usage instead of PHP function to improve performance. Fix malformed query where we must be on the same day as cart rules.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-4544
| How to test?  | Everything is detailed on the forge ticket.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9055)

### CODE REVIEW

**Comment by sarjon** [comment]
wouldn't there be a problem when Mysql database is on a different machine with different time/timezone than the one where PrestaShop code runs?

**Comment by PierreRambaud** [comment]
@sarjon It's always a very very very bad idea to have different timezone in the same infrastructure :/ It's really better to let the lowest layer to handle date time data.
More `NOW()` is already used in many files (classes/Cart|Configuration|Connection|Customer|Employee,etc), and all upgrade scripts.

EDIT:
Also, you can change database timezone with Symfony configuration and same for php, so if you have a database cluster and a webservers cluster, you can ignore webservers timezone and set directly in configuration files :D

**Review by eternoendless — APPROVED** [review]

**Comment by 123monsite-regis** [comment]
sorry, 
i always though that mysql NOW() is less performant than date('Y-m-d 23:59:59') , as the second one can benefit from an eventual mysql cache( NOW() can never be cached on mysql side).
what do you think , i have no benchmark about this point?

**Comment by PierreRambaud** [comment]
In fact, not all countries have the same way to set a date, can be `Y-m-d` or `m-d-Y`. 
If you let the SQL to do that you can prevent some errors (Switching to PgSQL, Oracle or not using a real datetime field).

**Comment by mickaelandrieu** [comment]
Validated by the boss and QA approved by the other boss => should be LGTM *but* @eternoendless set the milestone for `1.7.4.1` release.

Sorry @PierreRambaud, I can't merge until we release `1.7.4.0`: the sooner, the better :)

**Comment by PierreRambaud** [comment]
Until the 1.7.4.0 is release, should we merge fix on develop at least?

**Comment by mickaelandrieu** [comment]
hmm, from my own experience we rarely backport commits in older releases...

**Pull request merged**
