### PR TITLE
Ignore `.htpasswd` file

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | Ignore `.htpasswd` file.
| Type?             | improvement
| Category?         | CO 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A.
| Related PRs       | N/A.
| How to test?      | N/A
| Possible impacts? | N/A

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
@PrestaShop/qa-team need QA ?

**Comment by boubkerbribri** [comment]
> @PrestaShop/qa-team need QA ?

No need for QA on this one.

**Comment by ghost** [comment]
@kpodemski i don't have the right :)

**Comment by kpodemski** [comment]
Thanks @PululuK

**Pull request merged**
