### PR TITLE
Fix display of color section on the add to cart modal on FO

### LINKED ISSUE #23660: FO - Shopping cart page & shopping cart-modal - A product with Color combination is not well displayed
#### Describe the bug

In the FO > when we add a product with a color combination to the cart, in the shopping cart page & in the shopping cart-modal, this product is not well displayed
image
image

#### Steps to Reproduce

1. Go to FO > Add a product with color combination to the cart
2. The shopping cart-modal is displayed
3. Change the cursor near the color
image
5. Click on proceed to checkout
6. Shopping cart page is displayed
7. Change the cursor near the color
8. See error 
image

#### Additional information

* PrestaShop version: 1.7.7.x ( 1773)
* PHP version: 7.1
* Shopping cart v2.0.4

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.7.x
| Description?      | There was a side effect on the selector of color inputs
| Type?             | bug fix
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23660.
| How to test?      | Go on FO using English language, on a product with some colors, select a color and add to cart, check on the right if the bug disappeared
| Possible impacts? | Product page

image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23688)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by khouloudbelguith** [comment]
Hi @NeOMakinG,

The issue is still reproduced by me and @Robin-Fischer-PS 

Rebuild assets:
```php
cd themes/
rm -rf node_modules/
npm i && npm run build
cd classic/_dev/
rm -rf node_modules/
npm i && npm run build
```

1. Fresh install with English language & France country 
2. In the FO > English is selected
3. Add a product with the color combination
4. See error in the modal 
image
5. Click on Proceed to checkout
6. See error in the Shopping cart page
image

Thank you!

**Comment by NeOMakinG** [comment]
I tested by checking out 1.7.7.x branch, build assets (and English lang is needed => bug reproduced), checkout this PR branch and rebuild assets => bug is fixed, looks like there is a problem somewhere when you test :/

**Comment by eternoendless** [comment]
@NeOMakinG Your PR is missing the compiled assets. [They are still required in the 1.7.7.x branch](https://devdocs.prestashop.com/1.7/contribute/contribution-guidelines/#compiled-assets)

**Review by jolelievre — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Comment by NeOMakinG** [comment]
I fixed another bug on variant links, QA already approved the fix, need review and we're fine!

**Review by eternoendless — APPROVED** [review]

**Comment by eternoendless** [comment]
@NeOMakinG I don't see the "QA ✓" label

**Comment by NeOMakinG** [comment]
@eternoendless @sarahdib is waiting for the review to approve

Relaunched travis as it was stuck

**Review by eternoendless — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG & @sarahdib

**Pull request merged**
