### PR TITLE
Updated modern email theme

### LINKED ISSUE #26177: [BO] Modern email theme isn't optimized for RTL languages
#### Describe the bug

Email templates that is generated base on Modern theme, isn't configured for RTL languages.

#### Expected behavior

Text align in email templates for RTL languages must be from right to left.

#### Steps to Reproduce

1. BO language must be RTL
2. Go to BO > Themes > Email theme
2. At "Generate emails" section, select Modern theme
3. Select a RTL language
4. Generate emails
4. At bottom of the current page ("Email themes" section) check email templates for Modern theme

**Screenshots**

Generated email template:

Expected email template:

#### Additional information

* PrestaShop version: 1.7.8.0
* PHP version: 7.3

### LINKED ISSUE #27570: Merge email twig file into the core
From the discussion https://github.com/PrestaShop/PrestaShop/issues/26177#issuecomment-1024055053
To allow developers and merchants to have the latest fixes from the modern theme, we need the twig files generated from https://github.com/PrestaShop/mjml-theme-converter into the core

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Updated modern email theme
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #27570
| How to test?      | Fixes #26177 in branch 1.7.8.x (asked by @MatShir)

Ping @mparvazi 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27614)

### CODE REVIEW

**Comment by mparvazi** [comment]
How to test:

**PS (email templates preview):**
1. Clear the PS cache
2. Change employee's language to RTL
3. Go to BO > Design > Email Theme
4. Choose modern for preview

**Generate emails (html files):**
_These files will be used for sending email._

Go to BO > Design > Email Theme > Generate emails
1. Select your email theme: **modern**
2. Select your language: **Arabic**
3. Select the theme you want to overwrite: **Core**
4. Overwrite templates: **Yes**

**Comment by atomiix** [comment]
Is this PR related to an existing PR on the https://github.com/PrestaShop/mjml-theme-converter repo?

**Comment by mparvazi** [comment]
> Is this PR related to an existing PR on the https://github.com/PrestaShop/mjml-theme-converter repo?

mjml: https://github.com/PrestaShop/mjml-theme-converter/pull/20
ps: https://github.com/PrestaShop/PrestaShop/pull/25992

**Review by Julievrz — APPROVED** [review]
Wording ✔️

**Review by matthieu-rolland — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by HanaRebaiQA — APPROVED** [review]
Hello @Progi1984 

I have tested this PR. The issue is well fixed on 178x.
I checked also all the related issues to this PR [#26177](https://github.com/PrestaShop/PrestaShop/issues/26177), [#27570](https://github.com/PrestaShop/PrestaShop/issues/27570), [#25990](https://github.com/PrestaShop/PrestaShop/issues/25990)
I checked also with different languages and with multisore.

Use : 
```
Go to BO > Design > Email Theme > Generate emails

Select your email theme: modern
Select your language: Arabic (for example)
Select the theme you want to overwrite: Core
Overwrite templates: Yes
```

**Gmail :** 
image

**Maildev :** 
image

**Outlook On Windwos 10 :** 
image

**Zimbra :** 
image


https://user-images.githubusercontent.com/92912932/153894530-937a27d8-e79a-4b6c-99be-dd14c032430c.mp4


So, QA :heavy_check_mark: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @HanaRebaiQA

**Pull request merged**
