### PR TITLE
Remove migrated image settings pages feature flag

### LINKED ISSUE #10563: Migrate "Design > Image Settings" page
Part of Symfony migration project

This page is a listing for Image Settings. When clicking on "edit" user is redirected to https://github.com/PrestaShop/PrestaShop/issues/10564

## Status

In order to finish the migration of this back-office page, we need to:

**Todo List**:
- [ ] Continue the PR [https://github.com/PrestaShop/PrestaShop/pull/22159 (see below)
- [ ] New feature to add to the Symfony page: [add a modal like on the backoffice page "Product listing" (in Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] New feature to add to the Symfony page: [add a modal to ask user to confirm or cancel when he wants to use the "delete action" for one Grid row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] The [Multistore header](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178) must also be added to the new Symfony page (if it is not already implemented). You can look at other migrated Symfony pages to see how it is built.
- [ ] New feature to add to the Symfony page: make the page multistore-compliant by introducing #19377
- [ ] New feature to add to the Symfony page: make the page multistore-compliant by introducing #19329
- [ ] Finally, we need a _last Pull Request_ to remove the legacy backoffice page and enable the Symfony page (see below)

Please submit one PR for each todo list item.

## About PR https://github.com/PrestaShop/PrestaShop/pull/22159

Please note that in PR https://github.com/PrestaShop/PrestaShop/pull/22159 the contributor wanted to migrate 2 pages together: this one AND https://github.com/PrestaShop/PrestaShop/issues/10564 . It might be wiser to split it into 2 PRs to make code review and testing easier... but we let you decide if this is interesting or a waste of time.

The PR https://github.com/PrestaShop/PrestaShop/pull/22159 aimed to create a new Symfony backoffice  page to replace the legacy page "Design > Image Settings". It was created by a motivated contributor. The new Symfony page should follow the [coding standards](https://devdocs.prestashop-project.org/8/development/architecture/migration-guide/) we have for all Symfony pages while providing the same behavior that the legacy page. It aims to create an equivalent page, but powered by Symfony and Twig :) .

Just like other Symfony pages, the application layer is Symfony + Twig, but it uses the Grid system to fetch and display data.

What you must do for PR https://github.com/PrestaShop/PrestaShop/pull/22159 is to fetch it
- Verify it is correct (for you), if not please fix wrong items you have found
- Have it reviewed (and approved) by committers
- The QA will not test it: they will test the last PR (see below)

## About the last PR

First Todo List items will be done by multiple PRs merged into `develop`. So the work of "create a new Symfony page that provides the same behavior/features as the legacy page" will be carried out BUT it is done on a Symfony page not accessible yet in the backoffice. You can browse it if you know the URL. It's like it's hidden.

In order to "finish" the job, a last PR is needed: this is the PR which _removes legacy files_ and enables the LegacyLinks that will redirect old URLs to the new page. So the new Symfony page replaces the legacy page in the back-office. When this is done, the migration is complete.

It is possible QA will find problems when testing the last PR: behaviors that used to work with the legacy page and are not working / implemented in the Symfony page. Then you must fix them.

Please ask @MatShir if you have questions about the behavior or @matks if you have questions about the code

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove `image_serttings` feature flag for the new migrated image settings pages in BO.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | After installation of this PR, migrated image settings pages in bo must be displayed by default instead of the legacy ones.
| UI Tests          | We need to update tests ui before.
| Fixed issue or discussion?     | Fixes #10563 
| Related PRs       | 
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]
Found two issues, one of them is quite big. ;-)

1. Product thumbnails are generated in all formats, not just the product ones. (not `category_cover`)

Snímek obrazovky 2024-02-15 154038

2. `Removed, I didn't build assets.`

**Comment by boherm** [comment]
Hi @Hlavtox,

> 1. Product thumbnails are generated in all formats, not just the product ones. (not `category_cover`)

Can you explain the way to reproduce this behaviour?

> 2. It offers all formats for regeneration of the given object, it should list just those for that object. (not `category_cover`)

Have your rebuild the new theme js scripts before testing? 🤔

**Comment by Hlavtox** [comment]
@boherm My settings is following. 

Rebuilding assets fixed the formats offered, I am sorry for confusion, but the issue with all thumbnails generated is still present.

I select "Products", correct list is loaded, I keep it to "All", click regenerate, and `category_cover` is generated, even if it's not a dimension for product.

settings1
settings2

**Comment by boherm** [comment]
> @boherm My settings is following.
> 
> Rebuilding assets fixed the formats offered, I am sorry for confusion, but the issue with all thumbnails generated is still present.
> 
> I select "Products", correct list is loaded, I keep it to "All", click regenerate, and `category_cover` is generated, even if it's not a dimension for product.
> 

I will check that ;)

EDIT: It's corrected.

**Comment by Progi1984** [comment]
@boherm It's good : https://github.com/Progi1984/ga.tests.ui.pr/actions/runs/7958172750/job/21766364264

**Review by jolelievre — DISMISSED** [review]
Thanks @boherm

**Comment by Progi1984** [comment]
@boherm Needs rebase

**Comment by boherm** [comment]
It's rebase!

**Review by Hlavtox — DISMISSED** [review]

**Comment by Progi1984** [comment]
@nesrineabdmouleh Could you review, please ?

**Review by jolelievre — DISMISSED** [review]

**Comment by AureRita** [comment]
Hi @boherm 

Thank you for your PR, I tested the PR and I see this issue : 

image

We still have the button image settings (it's "disabled" but it's still here)
FYI : if I enable it and disable it just after, we still have the new version of image settings 

Except that, I didn't see any other issue, 

Waiting for your correction, thank you

**Review by jolelievre — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @boherm 

auto tests link : https://github.com/AureRita/testing_pr/actions/runs/8002901895

I tested your PR with the last modification, all seems to works as expected, so it's a QA approved :heavy_check_mark: 

Thank you

**Pull request merged**
