### PR TITLE
Module alias in webpack configuration for the new-theme

### LINKED ISSUE #13943: How to add a JS extension for your modern module
# Summary

1. Enable modules to modify already-bundled JS files

```
import EmailSendingTest from './email-sending-test';
import SmtpConfigurationToggler from './smtp-configuration-toggler';
import Grid from '../../components/grid/grid';
import ReloadListActionExtension from '../../components/grid/extension/reload-list-extension';
import ...

const $ = window.$;

$(() => {
    const emailLogsGrid = new Grid('email_logs');
    emailLogsGrid.addExtension(new ReloadListActionExtension());
    emailLogsGrid.addExtension(new ExportToSqlManagerExtension());
    emailLogsGrid.addExtension(new FiltersResetExtension());
    emailLogsGrid.addExtension(...);
    const selector = '.my-selector';
    new EmailSendingTest(selector);
    new SmtpConfigurationToggler();
});
```

So we want to allow modules to customize this

2. Enable modules to inject JS and CSS files into a page (see https://github.com/PrestaShop/PrestaShop/pull/19277/)

# Context

https://github.com/friends-of-prestashop/demo-cqrs-hooks-usage-module

I have added `ToggleColumn` in Customers list using the module and it works like a charm. `ToggleColumn` required javascript extension  added to the grid `new ColumnTogglingExtension()`. To my luck, Customers list has this extension but developers might face the issues when they add column but the list does not have this extension in javascript compiled.

Possible solutions:
1) After creating sample doc about module creation we should create a sub-doc with advanced use cases such as **adding extension from module** - this will display webpack configuration, using hook to add your new javascript to existing list etc...

2) Provide a mechanism to be used from inside a module to add a specific JS/CSS file to the extended page, like legacy `addCss()`

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | We are a little bit bored about the `import '../../../../../../'` in javascript files. So we add a webpack aliases for `@js`, `@app`, `@pages`, `@components`, `@scss`, `@node_modules`.<br/>BC break: the initial `app` namespace is now called `@app`
| Type?         | improvement
| Category?     | BO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | partial fix #13943
| How to test?  | Nothing should change in the BO.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16432)

### CODE REVIEW

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
Waiting for a 2nd review

**Review by Progi1984 — DISMISSED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @PierreRambaud ! Could you resolve the conflict on this PR ?

And, if possible, could you give us a more detailed way to test ? (or explained what this PR change ?)

Thanks !

**Comment by PierreRambaud** [comment]
@Robin-Fischer-PS Since we change many things in the javascript, you need to open all pages and make sure there is no error in the javascript console. :)

**Comment by Robin-Fischer-PS** [comment]
Hi @PierreRambaud ! I tested majority of the BO page (but not all actions, of course...), did not see any new errors.

So it's QA :heavy_check_mark: !

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
🎉

**Pull request merged**
