### PR TITLE
Fixed Cart display when user have 2 customizations

### PR DESCRIPTION
**Pull request by vavrecan**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | When user is logged in and he has more than 2 customization in carts, then blockcart behaves strangely |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Create product with required text customization<ul><li>Then create a new customer and log in (this also affect existing customers)</li><li>Add to the cart three different customization for same product.</li><li> Then use Ajax-Cart to remove customization - it will work - but ajax will rebuild the customization without id_address_delivery - so if you try to remove all customization without doing page refresh it will not work and properly and item will stay in the cart without any customization.</li></ul> |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/5916)

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hi @vavrecan,

thank you for your contribution. For now we are focused on the release of our first stable 1.7.

We will merge as soon as possible.

Mickaël

**Comment by vavrecan** [comment]
thank you and looking forward - do not really worry about merging in - tbh default template in 1.6 is not so easy to customize because of many id references and jquery selectors are too absolute. I was wondering - ajax cart and OPC would be much easier with Angular or some MVVM - do you plan to do it like that in 1.7? 
Thanks! great job

**Comment by xBorderie** [comment]
Hi @vavrecan! The way themes work in 1.7 is pretty much set in stone, and does not use Angular (nor MVVM as far as I know), but Bootstrap 4.
You can have a look at the new default theme's code here: https://github.com/PrestaShop/PrestaShop/tree/develop/themes/classic
And read about its creation on the Build devblog: http://build.prestashop.com/news/new-theme-1-7-introduction/
As for the 1.6 default theme, you might be interested in the community-lead upgrade to it: https://github.com/PrestaShop/community-theme-16

**Comment by kpodemski** [comment]
The truth though, is that @vavrecan is right, it would be a way easier to bring Vue.js or other micro-framework to manage order-opc or ajax-cart in 1.7

**Comment by marionf** [comment]
I'm sorry but PrestaShop 1.6 support ended on June 30, 2019, consequently this PR will not be merged into the project.

Please note that if a critical issue is discovered, there is a dedicated GitHub repository: https://github.com/PrestaShop/PrestaShop-1.6 maintained by a team of volunteers.
From this repository, it will be possible to submit pull requests in order to fix critical issues.

You can read more about it on http://build.prestashop.com/news/1.6.1.x-what-s-next/

Furthermore, I can't reproduce the issue on PrestaShop 1.7.6.1 as we can't delete anymore customization from the cart

**Pull request closed without merging**
