### PR TITLE
Moving the call to the function renderwidget

### PR DESCRIPTION
**Pull request by frederic-benoist**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Simple move for futur override (necessary for profiling) |
| Type? | improvement |
| Category? | CO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | N/A |
| How to test? | not for now |

### CODE REVIEW

**Comment by Shudrum** [comment]
Hi!

What do you wan't to do with this?

I mean: statics are BAD, and we do not wan't to add some statics methods anymore.
If you have a REALLY good reason that cannot be resolved in a better way, why not.

**Comment by frederic-benoist** [comment]
Without this change, how to add profiling modules on PrestaShop 1.7?
Some examples :
- ps_banner use renderWidget on displayHome
- ps_contactinfo use renderWidget on displayNav1 and displayFooter
- ps_linklist use renderWidget on displayFooter

This solution allows the creation of an override function as with the hook::coreCallHook()

**Comment by Shudrum** [comment]
So the main problem is that we have removed some hooks?

**Comment by frederic-benoist** [comment]
No.
With the new renderWidget interface the old profiling tools can't works (hook::coreCallHook() is not used), 

With this change, it's possible to override the module call (the new function hook::coreRenderWidget) and add Profiling.

**Comment by Shudrum** [comment]
Ok, I understand the problem and you cannot do something better and you have just followed the other static method just bellow.

It is ok for me :)

But before merging : can you remove the merge commit ? Your pull request should only contain your commit.

Thank you!

**Comment by frederic-benoist** [comment]
remove merge commit done.

Thx

**Comment by Shudrum** [comment]
Thank you!

**Pull request merged**
