### PR TITLE
Re-enable functional tests

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | This PR fix and re-enable functional tests in Travis
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  |

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8815)

### CODE REVIEW

**Comment by fatmaBouchekoua** [comment]
This PR should be merged after this 2 PRs: https://github.com/PrestaShop/PrestaShop/pull/8618 & https://github.com/PrestaShop/PrestaShop/pull/8648

**Comment by eternoendless** [comment]
@fatmaBouchekoua The PRs have been merged, could you please rebase?

**Comment by fatmaBouchekoua** [comment]
Hello @eternoendless,

Done, and the tests turn green :tada:

**Review by Quetzacoalt91 — APPROVED** [review]
AWESOME

**Comment by eternoendless** [comment]
🎉 👏

**Pull request merged**
