### PR TITLE
Update pull-request template with additional PR types

### PR DESCRIPTION
**Pull request by sarjon**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | It adds additional "refacto" & "critical" so everyone could know that these exist.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a
| How to test?  | n/a

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9292)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
We need to update PrestonBot before =)

**Comment by mickaelandrieu** [comment]
> We need to update PrestonBot before =)

Preston was broken recently, but it was able to recognize `refacto` and `critical` types, with already a specific label for critical. For `refacto`, this needs to be discussed with @ttoine and @marionf afaik.

But before introduce new features, I'd like to see "him" working again for the basics :+1:

**Comment by PierreRambaud** [comment]
@mickaelandrieu Look like something is weird with preston when it was working yesterday -_-
Preston already has `critical` and `refacto` in its valid types and we can already add these types while creating a PR :/

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
No need of QA review of this one, I'm merging.

Thank you @sarjon

**Pull request merged**
