### PR TITLE
[*] CORE : Toggle birthdate field with one click

### PR DESCRIPTION
**Pull request by firstred**
## Description

Simply toggle the birthdate field on the customer registration form with one click.

customerfields
createaccountbirthdate

### CODE REVIEW

**Comment by vincentbz** [comment]
Totally agree with it, thanks !

**Comment by PrestaEdit** [comment]
:+1:

**Comment by maximebiloe** [comment]
Thank you for your contribution @firstred.

@AlexEven can you check everything is okay on the wording-side?

**Comment by AlexEven** [comment]
Looks good, thanks!

**Pull request merged**
