### PR TITLE
Add event on toggleOrderButton in order to provide state of checkbox to payment modules

### LINKED ISSUE #19189: Add a JavaScript event when Terms and conditions are approved
#### Is your feature request related to a problem?

In checkout process in payment step, add a [Javascript Event](https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/) when customer approve Terms and conditions to help payment modules to know if they can process to payment or not.

For modules [PrestaShop Checkout](https://github.com/PrestaShopCorp/ps_checkout), [Stripe](https://github.com/202-ecommerce/stripe_official) and [others](https://addons.prestashop.com/en/481-payment).

[PrestaShop Checkout](https://github.com/PrestaShopCorp/ps_checkout) use [PayPal Javascript SDK](https://developer.paypal.com/docs/checkout/) to manage Payment Button on checkout page and we use a callback to enable/disable it.
Currently we have to create your own event to check if Terms and conditions are approved.

[Stripe](https://github.com/202-ecommerce/stripe_official) use [Stripe Javascript SDK](https://stripe.com/docs/js) and [use their own event](https://github.com/PrestaShop/PrestaShop/issues/19161#issuecomment-629974094) to check if Terms and conditions are approved.

#### Describe the solution you'd like

Add a [Javascript Event](https://devdocs.prestashop.com/1.7/themes/reference/javascript-events/) in [Core Js](https://github.com/PrestaShop/PrestaShop/blob/03032d6adb19836240047b5658988f1e64c823ee/themes/_core/js/checkout-payment.js#L84)
https://github.com/PrestaShop/PrestaShop/blob/03032d6adb19836240047b5658988f1e64c823ee/themes/_core/js/checkout-payment.js#L68

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Payment modules needs an event in order to know if terms are checked or not
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19189 
| How to test?  | QA can't test this as you need to register to the event, only develop, so I think QA can only test if checkout process doesnt break when you choose a payment method

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19428)

### CODE REVIEW

**Review by Matt75 — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
Could we provide a test module for QA to validate the PR ?

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by Matt75** [comment]
> Could we provide a test module for QA to validate the PR ?

I will update Payment Example module

**Review by PierreRambaud — DISMISSED** [review]

**Comment by Matt75** [comment]
Added a test in [PaymentModule](https://github.com/PrestaShop/paymentexample) for QA Team : https://github.com/PrestaShop/paymentexample/pull/14/commits/6c9d5e69acea702dc2a41b269bc8db38cd1a80f2

**Comment by SD1982** [comment]
LGTM Thanks @NeOMakinG and Thanks @Matt75 !

**Review by matks — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matks** [comment]
Thank you @NeOMakinG for the PR and @SD1982 for the QA !

**Pull request merged**
