### PR TITLE
Add missing translation keys in home slider

### PR DESCRIPTION
**Pull request by shakaran**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add missing translation keys in home slider
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | /no
| Fixed ticket? | -
| How to test?  | Just load default theme with translations.

This allow to enable translations for the home slider in "classic" theme.

### CODE REVIEW

**Comment by xBorderie** [comment]
@shakaran You changed the PR's title, not the commit's name.
As written by PrestonBot, you can't change the commit's name from the GitHub interface. You need to use Git from the command line.

**Comment by xBorderie** [comment]
Moving this 1.7.1.0, since strings are frozen in 1.7.0.x.

**Comment by shakaran** [comment]
Just an opinion (trying to be constructive). There are a lot PR very simple and basic and they take days or weeks to be merged and released. It is VERY important release early and release often, specially if you want a quickly adoption of PS 1.7. Also [it encorauges to quick develop and new contributors interested](https://news.ycombinator.com/item?id=8712349).

If for a simple merge of a missing translation or other PR that are in queue takes weeks, the PS team is doing something wrong or indeed something that should be improved to reduce merge and release times.

More than 20 days after the official release, any minor 1.7.0.x or 1.7.x.x is released and considering that the bugs queue is almost growing exponentially, it should be taken with more urgency.

image

**Comment by xBorderie** [comment]
Thanks @shakaran. We have very much aware of the need to a better PR flow, and are working with the available resources. We actually do daily meetings to talk about the recent Forge tickets and see which are the most urgent issues that have surfaced since the release of 1.7.0.0. We do our best to move quickly.

Your own PR here is indeed a simple one, but as I wrote, we can only merge it in 1.7.1.0, because our SemVer-like version won't let us merge it in a patch (1.7.0.x) version.

Thank you for your patience!

**Comment by aleeks** [comment]
Thank you @shakaran !

**Comment by shakaran** [comment]
Nice, @xBorderie @aleeks which remains for release finally 1.7.0.3? I see in [github milestones](https://github.com/PrestaShop/PrestaShop/milestones) more than 33 issues closed, that seems enough to make a release for "minor". It would be a nice pattern that prestashop release a minor each 1-2 weeks at least, that allows to users get soon the updates with minor bugs fixed. It is a pity that I have to my client waiting more than 1 month for just add a translation key officially. Indeed, she is not taking a good impression about use the new PrestaShop version because it is all in English (she is Spanish) and her consumers are mostly woman buying clothes and speaking spanish. So please, I have patience, but clients and consumers are different, they want all fixed quickly.

**Pull request merged**
