### PR TITLE
Explain branching strategy

### PR DESCRIPTION
**Pull request by fulldecent**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update documentation about how we do branching here
| Type?             | improvement
| Category?         | PM
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | read markdown
| Fixed issue or discussion?     | discussed at https://github.com/PrestaShop/PrestaShop/issues/36090#issuecomment-2093695760

### CODE REVIEW

**Comment by Hlavtox** [comment]
I like the idea, but we should add information, that not all bug fixes go to the patch channel.

The general concensus is, that we allow simple, easy to test patches OR the ones where the fix is really major. If the fix works, but we smell potential dangers, we leave it to develop branch.

**Comment by fulldecent** [comment]
I'm happy to make changes on this PR. What you're describing may also need to be updated in that blog post.

Also, maybe we just merge this as is and wait until the pull requests come in and deal with them on a case by case basis

**Review by jolelievre — APPROVED** [review]
Thanks @fulldecent

**Review by matks — APPROVED** [review]
We could improve this further, but I don't want to nitpick 😉 it's quite good as it is. Other improvements can be done by other Pull Requests

**Comment by matks** [comment]
Thank you @fulldecent

**Pull request merged**
