### PR TITLE
Render a 404 template if no products found

### PR DESCRIPTION
**Pull request by ishcherbakov**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Render 404 page is no products found (7 pages concerned) |
| Type? | bug fix |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-1110 |
| How to test? | See forge ticket for description |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by kpodemski** [comment]
I think it will be better to move this code into some `FrontController` method

**Comment by maximebiloe** [comment]
This method works but I don't really like the `if`/`else`.
I think we could use the smarty extends feature to avoid this.
What do you think @julienbourdeau?

**Comment by ishcherbakov** [comment]
@maximebiloe I don't think you can avoid this as you have to set proper HTTP headers anyway.

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by vincentbz** [comment]
status : 'QA approved'

**Comment by vincentbz** [comment]
wouhou, it works^^

**Comment by mickaelandrieu** [comment]
Thank you Ivan :)

**Comment by rGaillard** [comment]
@ishcherbakov @mickaelandrieu @maximebiloe @vincentbz it should not sent a 404 header for SEO purposes.

**Comment by ishcherbakov** [comment]
@rGaillard sure ? Anyway HTTP 200 does not look like a good option neither. It leads to duplicate content issue as well.

**Comment by mickaelandrieu** [comment]
@rGaillard it's [not that bad](https://moz.com/blog/are-404-pages-always-bad-for-seo). It's up to merchant to configure a redirection to another product if a product is unavailable (302 or 301 according to the needs, of course).

**Comment by rGaillard** [comment]
@mickaelandrieu there is no option on the backoffice to create 302/301 rules when a product listing is empty. Also, currently the internal links stays on the shop. That is better to display a message on the initial page that there is currently no product in this page / category etc...

**Comment by vincentbz** [comment]
@mickaelandrieu in that case it's not for not found products but when a search, a category, a specific page, have no product, like "discounted products" when there are no product.  Impossible to make a 301/302 redirection

**Comment by mickaelandrieu** [comment]
@vincentbz got it. Still the contribution of @ishcherbakov is relevant. The main problem is using the same 404 template for this specific use case :)

**Comment by maximebiloe** [comment]
I agree with @rGaillard, it's not a 404 page, the page is found, it's just there is no product.
You can have page indicating clearly that there is no product in that category (or specific page like discounted products) with a canonical URL. That way, it won't cause SEO trouble.

**Pull request merged**
