### PR TITLE
AdminStatsController calculating bad values

### PR DESCRIPTION
**Pull request by PeNov**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.3.x
| Description?  | AdminStatsController calculating bad values, http://forge.prestashop.com/browse/BOOM-5670
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Create two orders with different currency. First in default shop currency. Second in different currency. Show dashboards statistics. 

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9164)

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Hi and Thanks for your contribution, but, look like you're trying to merge your develop branch into 1.7.3.x. Is it what you really want to do? If not can you switch to "develop" instead?

**Comment by PeNov** [comment]
Hi,
No, I would like merge commit into develop from PeNov-patch-getPurchases_calculating-bad-values. But I dont know how edit this pull request.

**Comment by PierreRambaud** [comment]
You can use edit button, otherwise create a new one by selecting your fork instead of current repository.
https://github.com/PrestaShop/PrestaShop/compare/develop...PeNov:PeNov-patch-getPurchases_calculating-bad-values?expand=1 Hope it will help you =)

**Comment by PeNov** [comment]
Thank you
I created new pull request.

**Pull request closed without merging**
