### PR TITLE
Fix cache class

### LINKED ISSUE #12509: ContextErrorException on order if Legal compliance module is installed
**Describe the bug**
When we do an order with Cash on delivery payment method then the **(1/1) ContextErrorException
Warning: Cannot use a scalar value as an array** exception will occur. The exception occurs when only the debug mode is on and the configuration in this module **"Proportionate tax for shipping and wrapping"** is set to **YES**

**To Reproduce**

1. configure the pretashop as mentioned in the description. 
1. Add any product in cart, a tax should be applied on the product.
1. Go to checkout, select the shoipping method, (it should not be free)
1. Chosse payment method
1. and click on "Order with an obligation to pay" 

**Screenshots**
Module Configuration page  - 
legalcompliance

Error - 
legalcomplianceerror

**Additionnal information**
PrestaShop version: 1.7.4.4, 1.7.5.0
PHP version: 7.0

### LINKED ISSUE #14119: AH01071: Got error 'PHP message: PHP Warning: Cannot use a scalar value as an array
**Description**

Enable APC cache in performance section and watch logs. If you dont see anything before this patch, maybe yo have a small shop. it is need to overpass the limit $maxCachedObjectsByTable = 10000

>Edited by Khouloud

Steps to reproduce the issue

1. Create more than 10000 products
2. Go to FO
3. See error

image

Prestashop 1.7.5.2 on php 7.2.19
today I've this warning:

`AH01071: Got error 'PHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 567\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\nPHP message: PHP Warning: Cannot use a scalar value as an array in /var/www/vhosts/100asa.it/httpdocs/classes/cache/Cache.php on line 463\n'`

I've also read this topic https://www.prestashop.com/forums/topic/582890-cannot-use-a-scalar-value-as-an-array/

### PR DESCRIPTION
**Pull request by davidglezz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix<br> PHP Warning:  Invalid argument supplied for foreach() in /classes/cache/Cache.php on line 567 <br>PHP Warning:  Cannot use a scalar value as an array in /classes/cache/Cache.php on line 463
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #14119
| How to test?  | Enable APC cache in performance section and watch logs. If you dont see anything before this patch, maybe yo have a small shop. it is need to overpass the limit `$maxCachedObjectsByTable = 10000`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20446)

### CODE REVIEW

**Comment by Progi1984** [comment]
@davidglezz Have you checked this scenario : https://github.com/PrestaShop/PrestaShop/issues/12509#issuecomment-463100960 ?

**Comment by davidglezz** [comment]
@Progi1984 I think it is not related

**Comment by davidglezz** [comment]
@khouloudbelguith incorrectly marked https://github.com/PrestaShop/PrestaShop/issues/14119 as a duplicate of https://github.com/PrestaShop/PrestaShop/issues/12509

**Comment by khouloudbelguith** [comment]
@davidglezz, the same warning is displayed
`Cannot use a scalar value as an array`

Isn't?

**Comment by davidglezz** [comment]
It is a PHP warning that can occur anywhere in the code where you try to use a number like an array. For example:
```php
$var = 1;
$var['name'] = 'John';
```

Not related with TaxCalculator...

**Comment by khouloudbelguith** [comment]
@davidglezz, thanks!
#14119 reopened

Thanks!

**Comment by davidglezz** [comment]
Still "waiting for author"

**Comment by davidglezz** [comment]
Please change the label "waiting for author"

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Dakror** [comment]
I'm still seeing the Warning after locally patching using this PR: 
image

**Comment by davidglezz** [comment]
@Dakror You need to restart the server or at least clear the cache.

**Comment by davidglezz** [comment]
QA team: Please do not forget this PR, its a bug fix!

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Sorry for the late response.
`it is need to overpass the limit $maxCachedObjectsByTable = 10000`
Could please provide me the exact steps to do to display this value `$maxCachedObjectsByTable`.

Thank you!

**Comment by davidglezz** [comment]
@khouloudbelguith 
Making queries that return more than 10 000 rows/items, for example, if you have more than 10 000 products...

$db->executeS with $use_cache = true


- Try call multiple times, do a lot of queries.
- Do queries over table or entity with more than 10 000 rows
- Not applicable for this tables: 
```php
    protected $blacklist = [
        'cart',
        'cart_cart_rule',
        'cart_product',
        'connections',
        'connections_source',
        'connections_page',
        'customer',
        'customer_group',
        'customized_data',
        'guest',
        'pagenotfound',
        'page_viewed',
        'employee',
        'log',
    ];
```

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

Thanks for your feedback.
I need to prepare this shop.
I will check and feedback.

Thank you!

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

I created more than 10000 products using API.
When I try to access to the FO => I have this exception
**With PR** 
image

**Without PR**
image

I deleted the cache manually and I used a private navigation. 
Thanks to check and feedback.

**Comment by davidglezz** [comment]
OMG! @khouloudbelguith  rocks!

**Comment by davidglezz** [comment]
@khouloudbelguith this happen if you fills the cache with the bug.
before use this Patch, clear the cache calling the ~~`opcache_reset()`~~ 
and try to fill the cache again.

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

I need to install Opcache on my server to use this function `opcache_reset()`
We try to use only APC cache, isn't it?

Thank you!

**Comment by davidglezz** [comment]
> APCu is the old APC without the opcode cache, which is now built provided officially by OPCache. It is a user cache, which means it must be explicitly used by your PHP code to take advantage of it, while OPCache does all the work just after being installed.

opchache is builtin with PHP


or restart server or use `apcu_clear_cache();`

I do not remember, what I did.

**Comment by davidglezz** [comment]
Sorry, I'm going to see if apcu needs to be activated,

**Comment by davidglezz** [comment]
Yes, apcu needs to be installed. 🤔

**Comment by khouloudbelguith** [comment]
Hi @davidglezz,

>Yes, apcu needs to be installed.

Yes, `apcu` is installed in my case.
I created this file 
```
<?php
apcu_clear_cache();
?>
```
It is well working!
**Without PR**, I have this exception
image
**With PR**
It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1TILEYm98lIh0UNBO79mhLI6u1u2WrM1Q/view?usp=sharing

Thank you!

**Comment by atomiix** [comment]
Thanks @davidglezz & @khouloudbelguith

**Pull request merged**
