### PR TITLE
// Fix CLDR data ganerator

### PR DESCRIPTION
**Pull request by martinfojtik**

### CODE REVIEW

**Comment by xBorderie** [comment]
Thanks for the PR, @fojtCz !

Our devs will review it soon :)

**Comment by kelu95** [comment]
Hi, thanks for your contribution, why remove main and supplemental data extraction ?

**Comment by fojtCz** [comment]
because `cldr.js` is loading data from `/translations/cldr/datas/main/en-US/numbers.json` not from `translations/cldr/main--en-US--numbers`

**Comment by fojtcz** [comment]
it has been already fixed

**Pull request closed without merging**
