### PR TITLE
travis: use it's own composer

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref: #2817

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi @TomasVotruba 

Thank you for contribution, but as you see Travis CI build failed, because when composer install is called is not in correct directory.

Please check your PR.

Best regards.

**Comment by jeromenadaud** [comment]
Hi, 

Maybe you have not noticed this : http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Best regards.

**Comment by TomasVotruba** [comment]
Oh, you are using composer only for tests? 
I'd recommend using standard `composer.json` position. Or is there any specific reason?

**Comment by jeromenadaud** [comment]
Hi,

Yes at this moment only for test, une future release we will implement it for all the solution.

Best regards.

**Comment by TomasVotruba** [comment]
This has no meaning then, though it's common composer usage.

Look forward to that release.

**Pull request closed without merging**
