### PR TITLE
Fix md5, charset and update the  Tread staus :  for sync messages imap

### LINKED ISSUE #25860: Problems on customer threads page
This issue was split from #23837

#### Describe the bug

**1. First bug:**

I had an error in Customer page
```
Notice on line 1053 of file /controllers/admin/AdminCustomerThreadsController.php 
[8] Undefined property: stdClass:$date
```

This line (this is PS 1.7.7.7) contains
`$md5 = md5($overview->date . $overview->from . $subject . $overview->msgno);`

The shop had received one spam email that didn't contain a date field in the header. Obviously the implicit assumption from Prestashop that this field is always set isn't true.

**2. Second bug:**

When the page load 9400 mail headers that were loaded from the IMAP mail server, the page tended to be very slow. Obviously the mails were not deleted on the server after they had been loaded. 

If I hadn't searched for a mail without a date I would never have guessed that this caused the slowness of the page.

#### Expected behavior

**1. First bug:**
Every sent email should contain a date field in the header

**2. Second bug:**

The mails should be deleted on the server after they had been loaded. 

#### Steps to Reproduce

1. Go to 'Customer Service' in the backend
2. Setup IMAP settings & Save
3. Revisit the 'Customer Service' page

**Screenshots**

```
Warning on line 1021 in file /prestashop/controllers/admin/AdminCustomerThreadsController.php [2] count(): Parameter must be an array or an object that implements Countable
```

#### Additional information

* PrestaShop version: 1.7.7.7
* PHP version: 7.3

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Currently there are several problems with the synchronization of messages.It is very complicated to test because it depends on the environment  
| Type?             | bug fix
| Category?         | BO 
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/25860
| How to test?      | Difficulty I can do a videoconference 
| Possible impacts? | No

# Explanation of changes 

**For the $subject :** 

Before :

` string(123) "=?UTF-8?Q?Re=3A_=5BVinkala=5D_Une_r=C3=A9ponse_=C3=A0_votre_message_est_disp?= =?UTF-8?Q?onible_=23ct47_=23tcqTUOShs9sZqE `

It's impossible to find CT and token

After : 

`string(107) "=?UTF-8?Q?Re=3A_=5BVinkala=5D_Une_r=C3=A9ponse_=C3=A0_votre_message_est_disp?= onible #ct47 #tcqTUOShs9sZqE"`

It's work 

**#For $overview->msgno** 

$overview->msgno change it's the number of position in mailbox.

**For remove date** 

Spammer can send email without date

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26818)

### CODE REVIEW

**Comment by ghost** [comment]
Sorry Preston :)

**Review by matks — CHANGES_REQUESTED** [review]
Hello @okom3pom I see 3 issues in this PR:
- the modifications you did probably work in your usecase, but I'm afraid they might not in any usecase or any config
- little BC break as you modify what we use to compute the md5 but data has already been stored in database -> after upgrade, all md5 already in database become obsolete
- as you said, very hard to reproduce and test so PR is very hard to validate 😅 

I'll be honest: as it's very hard to test and make sure we break nothing I prefer NOT to merge this PR instead of introducing a bug.

I'm open to ideas on how we could make this PR "less risky to merge".

**Comment by ghost** [comment]
This part of PrestaShop does not work in most cases.

We could keep the two MD5 fingerprints to test 

Even if the fingerprint is currently wrong because the msgno changes according to the order of the messages? 

You are right, I add the BC break

**Comment by Progi1984** [comment]
@okom3pom A solution could be to have a temporary md5 to check in first and a second one with the old method.

**Comment by ghost** [comment]
Hello, 

I will try to work on it next week.

Thanks for not closing

**Comment by Progi1984** [comment]
Ping @okom3pom Friendly reminder

**Comment by matks** [comment]
Hello,

It looks like this PR is now stale. I close it as our rules state it "Pull Requests may be closed after 30 days of inactivity following a request for modifications." (https://www.prestashop-project.org/maintainers-guide/reviewing-pull-requests/)

@okom3pom if you find some time we can reopen this PR 😉 

Thank you

**Pull request closed without merging**
