### PR TITLE
More data available for the productoutofstock email

### LINKED ISSUE #29111: Making more details about the product available for the out-of-stock email
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This feature request is related to this feature:
https://capture.dropbox.com/JAMdbCPnhWLDWfsq

One of the Polish merchants reported that a built-in feature about sending alerts about products with low stock has a limited amount of data about the product - for instance, there is no product reference available.

### Describe the solution you'd like

We should have `product_reference` available by default. Additionally, the product ID and its combination ID should be available for the sake of `hookActionGetExtraMailTemplateVars`.

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | All the details are available in the Issue
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29111 .
| Related PRs       | n/a
| How to test?      | You can test it using qualityassurance module, all the details available below
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.
| Sponsor company | impSolutions

1. Using `ps_qualityassurance` module, hook into the `actionGetExtraMailTemplateVars`
2. Content of the hook:

```
return print_r($params['template_vars'], true);
```

3. check the array of the parameters before, and after the fix. It should have additional data.
4. 
**Make sure to place an order, not edit the quantity**

### CODE REVIEW

**Comment by ghost** [comment]
Hello @kpodemski 

The code is good, but I can't test it.
Either via the hook or via email. Are you sure the email is not coming from ps_emailalert?
I must have missed something.

**Comment by kpodemski** [comment]
@okom3pom yeah, I'm sure :) if you setup the low stock alert, you need to place an order. Changing the quantity doesn't work - forgot to mention that

**Comment by ghost** [comment]
I had not made an order I test again

**Comment by ghost** [comment]
Now it's good :)  i try to relaunch CI thank you for details 

Capture d’écran de 2022-07-19 16-14-46

it's possible we have to change also ps_emailalert

**Review by ghost — APPROVED** [review]

**Review by FabienPapet — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @kpodemski ,

Thanks for the PR!

I have tested, I do have more info regarding product:
Screenshot 2022-08-08 at 14 52 44

It is QA ✅ 
Thanks!

**Comment by kpodemski** [comment]
Thanks @florine2623

**Pull request merged**
