### PR TITLE
Fix future mistakes

### PR DESCRIPTION
**Pull request by metacreo**
Fix future mistakes
objectNodeNames -- not used at all
objectNodeName -- need for object model
objectsNodeName -- need for object model

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hello @metacreo nice catch! can you tell us how you found this?

**Comment by metacreo** [comment]
> Hello @metacreo nice catch! can you tell us how you found this?

Hello, 
I'm just a module developer. I needed these features and just searched through the code.
I know PS very well from the technical side. Over 10 years of experience with this engine.
If you need details, exactly how I found it. I did a recursive search from the linux console (grep -rl, etc...).

**Comment by matks** [comment]
@metacreo I was wondering what situation would bring you to search through the code. Did you see something was wrong and searched for the reason?

**Comment by metacreo** [comment]
@matks I just needed to create new object like Product (but not Product) with features and webservice support. 
I compared the "product" and "attachment" objects (classes) with other classes in prestashop.
I just needed the "objectNodeName" and "objectsNodeName" parameters for my module object model webservice. Then I noticed that the "objectNodeNames" parameter is not used anywhere else and only the first 2 are used. This means that the extra parameter was introduced erroneously or forgotten for subsequent implementation.
Also... PS webservice classes implemented exactly with "objectNodeName" and "objectsNodeName" parameters and not with "objectNodeNames" in any way.

**Review by matthieu-rolland — APPROVED** [review]

**Review by MeKeyCool — APPROVED** [review]

**Pull request closed without merging**
