### PR TITLE
Fix on product-flags class' width for product cards

### LINKED ISSUE #15260: Fixed a little css bug around .product-flags
Hi
if you pass the mouse over a product block when there are some flags on the image, it is not possible to click over the image.
It is due from this code in theme.css

`.product-flags {
    width: 100%;
}`

to fix it it is necessary to use this code

`.product-flags {
    width: auto;
}`

bye

**Screenshots**

**Additional information**
PrestaShop version: 1.7.6.0
PHP version: 7.0

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Fix for a 1.7.6 regression. The product-flags on product miniatures (i.e. "NEW", "-20%") had the width set to 100%, it was thus overlapping the link to the product page on the area next to the flag. It has been fixed by replacing `.product-flags {width: 100%}` by `.product-flags {width: auto}`.
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #15260 
| How to test?  | Clicking on the right side of the flag should link to the product page. See pictures.

Bugged behavior:
Capture d’écran 2019-08-26 à 18 15 50

The behavior you should have thanks to this PR:
Capture d’écran 2019-08-26 à 18 16 01

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15265)

### CODE REVIEW

**Comment by ghost** [comment]
Not sure about the asset compiling tough, let me know guys if I did it properly 😉

**Review by PierreRambaud — APPROVED** [review]

**Comment by sam-pires** [comment]
Crap we have a problem on "Web only" labels, it uses the same `product-flags` class

with `witdh: 100%;`
Capture d’écran 2019-08-30 à 11 11 27

with `witdh: auto;`
Capture d’écran 2019-08-30 à 11 11 46

**Comment by dineshbadrukhiya** [comment]
> Crap we have a problem on "Web only" labels, it uses the same `product-flags` class

Can we remove absolute position for label "online-only"? wdyt?

**Comment by sarahdib** [comment]
@samuel-pires 

there is some conflicting files. Can you resolve it ?

Thank you

**Comment by ghost** [comment]
> > Crap we have a problem on "Web only" labels, it uses the same `product-flags` class
> 
> Can we remove absolute position for label "online-only"? wdyt?

Good idea, there is something to try there

**Comment by Progi1984** [comment]
Thanks @sam-pires for your help :)

**Pull request closed without merging**
