### PR TITLE
Travis: update config for dpl v2

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | No functionality change, only update travis config to remove warnings, i.e. update config based on the latest config grammar.
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | Travis jobs need to pass with same output as the previous build.

Before:
image
image
image

After:
image

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16807)

### CODE REVIEW

**Comment by mvorisek** [comment]
image
How to solve it? Please review and merge.

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
@mvorisek Sorry for late answer. As our CI relies on external 3rd party, payloads sometimes get lost 😅 so I closed and reopend the PR in order to re-send some payloads to both PrettyCI and Travis. I hope this one the payloads and their answers will reach destination.

**Review by matks — APPROVED** [review]

**Comment by mvorisek** [comment]
@matks
> @mvorisek Sorry for late answer. As our CI relies on external 3rd party, payloads sometimes get lost 😅 so I closed and reopend the PR in order to re-send some payloads to both PrettyCI and Travis. I hope this one the payloads and their answers will reach destination.

The PrettyCI seems to be still broken. TravisCI passed, no PHP code (which should be the only code PrettyCI checks) changed.

Can you merge and watch if the merge commit will pass all checks?

PS: reported, at the time of writing this message, to Pretty CI via contact form

**Comment by mvorisek** [comment]
@matks Here is a reply from Matthieu from the PrettyCI owner:

> Hello Michael,
> 
> Sorry about that. I had a look in several different places and it seems that the HTTP call to the GitHub API that triggers the build on the fork failed.
> I deployed a small change that hopefully will fix it. Are you able to restart the build manually in the GitHub UI?
> 
> Matthieu

**Comment by matks** [comment]
Reclosing and reopening again in order to see if issue with PrettyCI is fixed now

Thanks for the investigation @mvorisek 👍

**Comment by mnapoli** [comment]
@matks thank you for your patience, I finally managed to re-trigger the check suite manually (I'm not proud how I did, that involved some curl, ID hardcoding in the codebase and redelivering of webhooks 😅)

Hopefully everything is good now.

**Comment by matks** [comment]
Thank you @mvorisek for the travis config and @mnapoli for the debug in prod (dont worry, it happened (happens ?) to all of us !)

**Pull request merged**
