### PR TITLE
Fix not found feature value in FeatureValueCore::addFeatureValueImport

### LINKED ISSUE #19773: FeatureValue::addFeatureValueImport create new item instead of finding the good one.
#### Describe the bug

In a specific development (like handmade import) if you want find or create a feature value with FeatureValue::addFeatureValueImport a new feature value is always created.

#### Expected behavior

If the feature value (not custom and in current language) exists, it should be found and not created

#### Steps to Reproduce

Use :
    FeatureValue::addFeatureValueImport($id_feature, $value); 
or
    FeatureValue::addFeatureValueImport($id_feature, $value, $id_product);

in a loop of items with the same feature value. In admin panel you'll see multiple values with same name.

#### Additional information

* PrestaShop version: 1.7.6.3
* PHP version: 7.0.33

### PR DESCRIPTION
**Pull request by voxTeam**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | When FeatureValueCore::addFeatureValueImport is used in specific development, the $idLang can not be set. The search is done with idLang = 0 and so never found. So it will create multiple feature value with same name.
| Type?         | bug fix
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #19773.
| How to test?  | Use : FeatureValue::addFeatureValueImport($id_feature, $value); or FeatureValue::addFeatureValueImport($id_feature, $value, $id_product); in a loop of items with the same feature value. In admin panel you'll see multiple values with same name.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19774)

### CODE REVIEW

**Comment by Progi1984** [comment]
@voxTeam Thank you for your contribution. Have you a scenario test with actions on BackOffice & FrontOffice for our @PrestaShop/qa-functional team ?

**Comment by voxTeam** [comment]
Unfortunatly no, because all usage of FeatureValue::addFeatureValueImportin Prestashop Core specify the language.
I found this problem by coding a handmade importer.

**Review by matthieu-rolland — APPROVED** [review]

**Comment by SimonGrn** [comment]
The issue was not specified nor reproduced, we need to do that before taking this PR.

**Comment by matks** [comment]
Hi everyone

It looks like this PR is not moving anymore. As mentioned in our [Maintainer Guide](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests), "Pull Requests may be closed after 30 days of inactivity following a request for modifications".

I close this pull request as it seems stale and you might dont want to continue on it. If however you want to continue it, you can re-open 😉 . As said before, we need some scenario to observe the issue so our QA team can validate the PR.

Thank you!

**Pull request closed without merging**
