### PR TITLE
Remove commented code

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | There is a commented code present since more than 2014, version 1.6.0.4.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@PrestaShop/qa-team Can we merge it like it is? It's dumb code removed

**Review by AureRita — APPROVED** [review]
Hi @PrestaEdit and @NeOMakinG , 

Yes, I think we can merge it like it is. 

Have a nice day

**Comment by NeOMakinG** [comment]
Thanks @PrestaEdit, @okom3pom, @AureRita

**Comment by matks** [comment]
A little fragment of the past 😄

**Comment by PrestaEdit** [comment]
Call me Indiana Jones, 🤠

**Pull request merged**
