### PR TITLE
Improve performance of subselect query when fetching attributes of current group

### PR DESCRIPTION
**Pull request by NachE**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Improve performance of subselect query when fetching attributes of current group
| Type?         | improvement
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | With a high number of products and lots of combinations in every product

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8264)

### CODE REVIEW

**Comment by alexandernst** [comment]
I'm also hitting this issue, please merge asap if everything is ok.

**Comment by jocel1** [comment]
@NachE Could you post the EXPLAIN result of the query before and after the fix ?

**Comment by NachE** [comment]
@jocel1 

Before:

| id | select_type | table | type | possible_keys | key | key_len | ref | rows | filtered | Extra
| -- | ------------|------|------|---------------|-----|--------|----|------|--------|--------
|1|PRIMARY|pac2|range|PRIMARY|PRIMARY|4|NULL|257750|100.00|"Using where;Using index"
|2|"DEPENDENT SUBQUERY"|pa|ref|PRIMARY, product_default, product_attribute_product, id_product_id_product_attribute|product_default|4|const|512|100.00|"Using index; Using temporary; Using filesort"
|2|"DEPENDENT SUBQUERY"|pac|eq_ref|PRIMARY, id_product_attribute|PRIMARY|8|const, c28ps.pa.id_product_attribute|1|100.00|"Using index"

After:

| id | select_type | table | type | possible_keys | key | key_len | ref | rows | filtered | Extra
| -- | ------------|------|------|---------------|-----|--------|----|------|--------|--------
|1|PRIMARY|pac2|range|PRIMARY|PRIMARY|4|NULL|252018|100.00|"Using where; Using index"
|2|"DEPENDENT SUBQUERY"|<derived3>|ALL|NULL|NULL|NULL|NULL|27|100.00|"Using where"
|3|DERIVED|pa|ref|PRIMARY, product_default, product_attribute_product, id_product_id_product_attribute|product_default|4||512|100.00|"Using index; Using temporary; Using filesort"
|3|DERIVED|pac|eq_ref|PRIMARY, id_product_attribute|PRIMARY|8|c28ps.pa.id_product_attribute|1|100.00|"Using index"


In a real query, before:
Error Code: 2013. Lost connection to MySQL server during query, Duration / Fetch Time: 30.001 sec

In a real query, after:
54 row(s) returned, Duration / Fetch Time: 0.574 sec / 0.000011 sec

**Comment by jocel1** [comment]
@NachE I see, by adding the extra SELECT * FROM you are forcing the materialization of the result, which makes sense since the SELECT inside the IN (SELECT ) doesn't depend on the pac2 table.
Could you try the speed of fetching the current SUBQUERY results (which doesn't return a lot of rows) in a php variable, and injecting those values in the IN ( ) ?

**Comment by alexandernst** [comment]
@jocel1 What you're asking doesn't make any sense in terms of performance. Why would you fetch data through PHP's link with the database, just to send that same data back thought the same link, feeding a second query?

Keeping everything on the database's engine is much cheaper in terms of performance.

The `SELECT *` wrapping the `SUBSELECT` already acts like a fixed-value which the `IN` can use without any further modifications nor performance penalties.

**Comment by jocel1** [comment]
@alexandernst because depending on the version of MySQL you're using, it could be really inefficient at doing SUBQUERY. Basically it could creates internally a temp table, which takes some time as well.

If you execute the original query in MariaDB for example, it will choose automatically to do the materialization, and you'll not need the "ugly" wrapping SELECT * FROM (SELECT id).
But I agree generally we should better avoid any extra queries to save network roundtrip.

For this case I just want to compare the performance of two queries vs one query with a SUBSELECT

**Comment by alexandernst** [comment]
Oh, so your point is that in order to prevent this bug from happening on older *SQL engines, check what are the costs of 2 queries compared to 1 and see if the tradeoff pays? Fair enough.

**Comment by jocel1** [comment]
yup that's it. Old version of MySQL are crap with subqueries, it can even execute the same subquery *for each lines*, with the awful performances you can imagine!

**Comment by NachE** [comment]
@jocel1 Patch done. The speed of the two queries is still good. I hope this one is okay.

**Review by jocel1 — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @NachE

**Pull request merged**
