### PR TITLE
Upgraded classic theme and ps_contactinfo module

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x 
| Description?      | Updated classic theme 
| Type?             | improvement
| Category?         | CO
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | ~
| Related PRs       | ~
| How to test?      | ~
| Possible impacts? | ~

The diff of this file is huge. 
I ran https://github.com/davidrjonas/composer-lock-diff to show you the differences: 

| Production Changes | From  | To    | Compare                                                           |
|--------------------|-------|-------|-------------------------------------------------------------------
| prestashop/classic | 2.0.6 | 2.0.7 | https://github.com/PrestaShop/classic-theme/compare/2.0.6...2.0.7 |

### CODE REVIEW

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by kpodemski** [comment]
Something is off with your Composer updates that there's always a full diff 😁

btw. I'm worried about 2.0.7 and changes on the contact page. I think we need to have ps_contactinfo released as well.

**Review by jolelievre — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Review by eternoendless — DISMISSED** [review]

**Comment by kpodemski** [comment]
Hi @nicosomb 

I think you missed QA part for the module.

https://www.prestashop-project.org/maintainers-guide/release-a-native-ps-module/#merge-dev-into-master

**Comment by nicosomb** [comment]
@kpodemski You're right. I discovered this page after upgrading module. 

What should I do ?

**Comment by kpodemski** [comment]
@nicosomb 

Remove the release, do the merge PR, I'll approve it and then it needs QA. Then, after the validation, you can merge, this will create a release automatically.

**Review by mflasquin — DISMISSED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by eternoendless — APPROVED** [review]

**Comment by nicosomb** [comment]
Tests https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/3786905046

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
