### PR TITLE
// Sql optimizations

### PR DESCRIPTION
**Pull request by jnadaud**

### CODE REVIEW

**Comment by kpodemski** [comment]
Wow, huge. Any before/after benchmark will be available?

**Comment by AlexGidarakos** [comment]
Very nice to see the PS team working on speed optimizations! :D

Will these be included on .12?

**Comment by jeromenadaud** [comment]
Hi,

Unfortunately no. We will prepare a special release for all optimization with, of course, all benchmark, before and after.

Best regards.

**Comment by jeromenadaud** [comment]
Move to PR #2452

**Pull request closed without merging**
