### PR TITLE
Improve customization display in order confirmation email

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | This PR is based on #4389 with addition of quantity display improvement |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Make a new order with one or more customizations and check the order confirmation email |

Preview
screenshot_4

### CODE REVIEW

**Comment by stroborobo** [comment]
Hey @unlocomqx :) Thanks for taking the time to update this patch.

I think we shouldn't hide the quantity only because it's one. The purpose of this was to be uniform with the FO cart, so why should we move away from that again? It'll just be confusing if one product has multiple customizations and an shows the quantity, but the other with one doesn't.

**Comment by unlocomqx** [comment]
Hello @stroborobo,

Thank you for your reply, 
The customizations will be separated anyway as the PR #5644 was merged recently

Here's a preview of the cart
screenshot_1

So no cart line would have more than one customization

Best regards

**Comment by stroborobo** [comment]
Ah I see, sorry. So then shouldn't the mail layout represent this new cart view instead?

**Comment by unlocomqx** [comment]
I will see about that and maybe push another commit to further improve the
display

**Comment by unlocomqx** [comment]
Hello @stroborobo,

Here's the preview for the latest changes, 
screenshot_1

It's better and makes more sense, thank you

**Comment by xBorderie** [comment]
There have been changes in the codebase which conflict with your PR now. Could you rebase it? Thank you!

**Comment by unlocomqx** [comment]
Thank you for your message, I resolved the conflicts and did a rebase

**Comment by xBorderie** [comment]
Thanks! Now all we need is someone from the team to review this PR!

**Comment by vincentbz** [comment]
Hi,

Thanks for this PR. We just need to test the several cases (like when the customization is a file, if there are other products added...) :)

**Pull request merged**
