### PR TITLE
Update modules page design

### PR DESCRIPTION
**Pull request by nihco2**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | quick redesign of module page
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | (optional)
| How to test?  | Check with mockups

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
capture du 2017-07-27 17-00-36

Is it the expected position of the spinner?

**Comment by Quetzacoalt91** [comment]
It seems you have an issue when you have a dropdown button:

capture du 2017-07-27 17-14-53

**Comment by nihco2** [comment]
@Quetzacoalt91 Fixed with ui-kit (npm update)

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
capture du 2017-08-01 15-50-58

Dat detail :innocent:

**Comment by nihco2** [comment]
:smiling_imp: is in the detail

**Comment by nihco2** [comment]
@Quetzacoalt91 Done ! could you please add review  check ?

**Review by Quetzacoalt91 — DISMISSED** [review]
All good for me. On the UI kit side, it would be great to have another look for the marketplace card:
capture du 2017-08-03 11-46-10

**Comment by nihco2** [comment]
@Quetzacoalt91 Fixed with UI-Kit

**Comment by nihco2** [comment]
capture d ecran 2017-08-04 a 15 38 36

**Review by Quetzacoalt91 — APPROVED** [review]
Now I'm good, definitely.

**Pull request merged**
