### PR TITLE
Fix BO CSV import - broken functionality

### LINKED ISSUE #32416: Prestashop 8 CSV Import Load Saved configuration not working
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

While importing products using CSV Import, I am trying to load a saved configuration. On clicking on load button, the saved configuration is not loading. In the browser console, we receive an error :

Deprecated Feature Used:
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/ .

Affected Sources:

jquery-3.5.1.min.js:2
--

### Expected behavior

The saved configuration should load.

### Steps to reproduce

Goto Advanced Parameters>Import>CSV Import. Select products. On the next page, while matching field, try to load a saved configuration.

### PrestaShop version(s) where the bug happened

8.04

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

9gems.in

### LINKED ISSUE #32798: Bug using template for import function: Saved configuration is not working
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

If you create an tamplate for importing items in the store and you want to load it the columns of the template won't be set properly.

### Expected behavior

Import columns should be set.

### Steps to reproduce

1. Go to the import page in the Backoffice
2. Choose something to import
3. Go to the nex page to asign the collumns of your document.
4. Save your template.
5. Go back to te start page
6. Go to the next page to set the columns again.
7. Try to load your saved template.

### PrestaShop version(s) where the bug happened

1.7.8.7 , 8.2

### PHP version(s) where the bug happened

7.4.33

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

MARK-APP

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Without this changes, you aren't able to save / edit / delete CSV configuration and CSV import is totally broken and unusable. All important is already written in past -> issues #32416 + #32798.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | BO -> "CSV import" -> try to load any CSV file. Then try to load / save / delete configuration.
| UI Tests          | https://github.com/florine2623/testing_pr/actions/runs/6769770329
| Fixed issue or discussion?     | Fixes #32416, Fixes #32798
| Related PRs       | 
| Sponsor company   | https://www.openservis.cz/

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by matthieu-rolland — COMMENTED** [review]
Thank you for your contribution @ShaiMagal , can you please exaplain what `trigger("chosen:updated")` is doing here ?

**Comment by ShaiMagal** [comment]
@matthieu-rolland It update select/option dynamically while changing saved configuration.
Without this commit is't not working. (QA team can check CSV import without this commit, saving/loading configuration is NOT working... After this commit this is working again]

Here is it explained }:
https://harvesthq.github.io/chosen/
Section "Updating Chosen Dynamically"
"If you need to update the options in your select field and want Chosen to pick up the changes, you'll need to trigger the "chosen:updated" event on the field. Chosen will re-build itself based on the updated content."

I don't know better way how to fix problem with broken CSV import. (Tested on 2 production eshops + more people already tested this here - #32798 + #32416 - (@mark-app and @pavonic))

**Comment by marcos-ba** [comment]
Fixes 32416 and 32798 does not resolve my problem

config serveur

any other option ?

**Comment by Hlavtox** [comment]
@marcos-ba Can you elaborate? What problem? Whats wrong? What fixes? What does that screenshot mean?

**Comment by marcos-ba** [comment]
> @marcos-ba Can you elaborate? What problem? Whats wrong? What fixes? What does that screenshot mean?

- What problem? : save / edit / delete CSV configuration and CSV import is totally broken and unusable Prestahop 8.1.2
- What fixes? : Fixes #32416, Fixes #32798
- Whats wrong? Fixes does not resolve
- What does that screenshot mean? : this is My server configuration
PHP 8.1.10 / Mysql 5.7.44

**Comment by ShaiMagal** [comment]
Guys. Here is the video with DEMONSTRATION of this PR:
https://www.youtube.com/watch?v=aujmBXBhvOM

I will show you, how it is NOT working. And then, how is it working AFTER this PR.
This problem is very easy to reproduce and fix as well. Problem is, it's not possible to save configuration and it's not possible to delete configuration. This PR is solving both problems

My commits explanation:
 - AdminImportController.php - this fixing deleting configuration
 - import.js - this fixing saving configuration

test CSV file:
[products_import.csv](https://github.com/PrestaShop/PrestaShop/files/13260444/products_import.csv)

**Comment by ShaiMagal** [comment]
@marcos-ba I don't know, why for you it isn't working. I tested it on more client websites + clean PrestaShop. My two fixes are working (check my video with demonstration  for clean PrestaShop).

**Can any other test this PR, please? :)**

**Review by M0rgan01 — APPROVED** [review]

**Comment by Hlavtox** [comment]
@ShaiMagal No need to worry. Prestashop QA team will test it and their word is important. If it works fine, all good. :-)

**Comment by marcos-ba** [comment]
@ShaiMagal
Thanks for your answer.
I tried again.
- The Save function it's ok .(the data matching configuration is saved in the "pszr_import_match" table database.
- The Delete function it's ok.
- But the Load function still not working

In your video, you don't test this function.

======================================================

github 1

=========================================================

github 2

===========================================================

github3

**Comment by ShaiMagal** [comment]
@marcos-ba I tested "load" now and working well for me.

**Comment by ShaiMagal** [comment]
@marcos-ba Special video for you, testing LOAD function:
https://www.youtube.com/watch?v=lyJvEKxgD8k

**Comment by marcos-ba** [comment]
> @marcos-ba Special video for you, testing LOAD function: https://www.youtube.com/watch?v=lyJvEKxgD8k

Ok, thanks.
i used this Import csv tool in Prestashop 1.6 for 4 years all days....
I will be forced to use another means to mass update the prices of my products.

**Review by florine2623 — APPROVED** [review]
Hello @ShaiMagal ,

It works as expected. Tested Import, works as expected.


https://github.com/PrestaShop/PrestaShop/assets/16019289/fafaad26-2f9b-4102-9bba-64067760a104



QA ✅

**Comment by miggel84** [comment]
This isnt working for LOAD.

Im using PS 8.1.0 and PHP 7.3

I have changed import.js at line 78 as recommended, but isnt working. Anyone can help?

Thanks.

**Comment by marcos-ba** [comment]
with me still doesn't work.
Could be a clue for developers.
I renamed the import.js file to import_old.js
I emptied the \var\cache
The problem is still there but no **error is displayed**. It looks like the file import.js is not used when using the LOAD function. the Load button remains grayed out and does not return to its initial state

**Comment by miggel84** [comment]
> with me still doesn't work. Could be a clue for developers. I renamed the import.js file to import_old.js I emptied the \var\cache The problem is still there but no **error is displayed**. It looks like the file import.js is not used when using the LOAD function. the Load button remains grayed out and does not return to its initial state

In did. Thats exactly whats hapenning to me.
How are you doing, are you changing the options everytime you need to upload a new CSV file? Its a nightmare at least for me...

**Comment by marcos-ba** [comment]
It's very strange.
There are days it works...
(I have already seen this remark on a forum)

Today it's ok.
I therefore re-tested to rename the **import.js** file to importxxx.js and the load function obviously did not work. (still no error displayed)
**Back with the import.js file, it works.**
So I think there is a problem accessing the Import.js file

Why ? I don't know.
My skills do not allow me to find where the problem is.
**Please ! Prestashop developers, help.**

* funny: when it works, no need to apply the correction to line 78 of import.js ".trigger("chosen:updated")" .
With the native Prestashop 8.1.2 file it still works.

I will stay attentive to try to discover

**Comment by mark-app** [comment]
@marcos-ba @miggel84 I think it could be your browser cache. I had the same problem with Google chrome with javascript and css files. Try to clean your browser cache for your website or try an other browser like firefox for testing

**Comment by marcos-ba** [comment]
> @marcos-ba @miggel84 I think it could be your browser cache. I had the same problem with Google chrome with javascript and css files. Try to clean your browser cache for your website or try an other browser like firefox for testing

YES
Aplying - https://github.com/PrestaShop/PrestaShop/issues/32798 + https://github.com/PrestaShop/PrestaShop/issues/32416
and CLEAN THE BROWSER CACHE !!!
now it is working well.

Thanks [mark-app](https://github.com/mark-app)

**Comment by miggel84** [comment]
> > @marcos-ba @miggel84 I think it could be your browser cache. I had the same problem with Google chrome with javascript and css files. Try to clean your browser cache for your website or try an other browser like firefox for testing
> 
> YES Aplying - #32798 + #32416 and CLEAN THE BROWSER CACHE !!! now it is working well.
> 
> Thanks [mark-app](https://github.com/mark-app)

Oh ok. I will try that later and provide feedback. Thanks a lot for the help everyone!

**Pull request merged**
