### PR TITLE
Add behat tests for customer Commands and Queries (part 1)

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add behat tests to validate Commands and Queries for Customer domain
| Type?         | improvement
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | php ./vendor/bin/behat -c tests/Integration/Behaviour/behat.yml -s customer

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13495)

### CODE REVIEW

**Comment by sarjon** [comment]
> Add behat tests for customer Commands and Queries (part 1)

What a cliffhanger! When will Part 2 be released? :stuck_out_tongue:

**Review by tomlev — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13495)* status: all files reviewed, 5 unresolved discussions (waiting on @matks)

___
*[tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php, line 67 at r1](https://reviewable.io/reviews/prestashop/prestashop/13495#-LdJoA6fDzVkTKvTMEZA:-LdJoA6fDzVkTKvTMEZB:b-ndkffc) ([raw file](https://github.com/prestashop/prestashop/blob/eb1efc3629876192b55427ba1bb13a76ca5d2c96/tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php#L67)):*
> ```PHP
> 
>     /**
>      * @When I create a customer :customerReference with following properties:
> ```

since I'm not familiar with the behat ":" notation, shouldn't it be surrounded with quotes ? 
___
*[tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php, line 74 at r1](https://reviewable.io/reviews/prestashop/prestashop/13495#-LdJnW5Q2lQPyj1ZzuA5:-LdJnW5RCPmSDJsrlqBZ:bdtjcfa) ([raw file](https://github.com/prestashop/prestashop/blob/eb1efc3629876192b55427ba1bb13a76ca5d2c96/tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php#L74)):*
> ```PHP
>         $data = $this->formatCustomerDataIfNeeded($data);
> 
>         $commandBus = CommonFeatureContext::getContainer()->get('prestashop.core.command_bus');
> ```

maybe move this line into a method, IMO it will be more readable
___
*[tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php, line 136 at r1](https://reviewable.io/reviews/prestashop/prestashop/13495#-LdJnEoq4ETStKlC0CtE:-LdJnEou5DaovBAB4lB2:b-90d0hp) ([raw file](https://github.com/prestashop/prestashop/blob/eb1efc3629876192b55427ba1bb13a76ca5d2c96/tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php#L136)):*
> ```PHP
>     public function editCustomerUsingCommand($customerReference, TableNode $table)
>     {
>         if (!array_key_exists($customerReference, $this->customerRegistry)) {
> ```

this code is used multiple times: please move it into a method
___
*[tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php, line 246 at r1](https://reviewable.io/reviews/prestashop/prestashop/13495#-LdJo5mVB7d4lNvsnKw9:-LdJo5mVB7d4lNvsnKwA:bx6mlkp) ([raw file](https://github.com/prestashop/prestashop/blob/eb1efc3629876192b55427ba1bb13a76ca5d2c96/tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php#L246)):*
> ```PHP
> 
>     /**
>      * @Then I should be returned an error message ':message'
> ```

why using single quotes here ?
___
*[tests/Integration/Behaviour/Features/Context/Util/PrimitiveUtils.php, line 25 at r1](https://reviewable.io/reviews/prestashop/prestashop/13495#-LdJos250o36K1M1sOJH:-LdJos250o36K1M1sOJI:b-ye93th) ([raw file](https://github.com/prestashop/prestashop/blob/eb1efc3629876192b55427ba1bb13a76ca5d2c96/tests/Integration/Behaviour/Features/Context/Util/PrimitiveUtils.php#L25)):*
> ```PHP
>     {
>         switch ($type) {
>             case 'boolean':
> ```

please use constants here

**Comment by matks** [comment]
> > Add behat tests for customer Commands and Queries (part 1)
> 
> What a cliffhanger! When will Part 2 be released? 😛

Maybe it will be released by you 😄I said "part 1" because these tests do not cover all Commands for Customer, so part 2 should provide a 100% coverage on these Commands

**Comment by matks** [comment]
___
*[tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php, line 246 at r1](https://reviewable.io/reviews/prestashop/prestashop/13495#-LdJo5mVB7d4lNvsnKw9:-LdPJt9u49-XLezS5fMP:b-5d792m) ([raw file](https://github.com/prestashop/prestashop/blob/eb1efc3629876192b55427ba1bb13a76ca5d2c96/tests/Integration/Behaviour/Features/Context/CustomerManagerFeatureContext.php#L246)):*
<details><summary><i>Previously, tomlev (Thomas LEVIANDIER) wrote…</i></summary><blockquote>

why using single quotes here ?
</blockquote></details>

Because the message can contain double quotes like : Customer with id "5" was not found

**Comment by matks** [comment]
@tomlev Requested changes have been applied

**Review by tomlev — DISMISSED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13495)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by matks** [comment]
Last commit amended in order to make PrettyCI happy 😊

**Review by tomlev — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13495)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by matks** [comment]
Thanks @tomlev for the review

**Pull request merged**
