### PR TITLE
Add export shopping carts scenario

### PR DESCRIPTION
**Pull request by fatmaBouchekoua**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This script checks if the exported file contains exactly the same information in the shopping carts table
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | path=full/01_orders/6_export_shopping_carts.js npm run specific-test -- --URL=URLFrontOffice --DIR=DownloadDirectory

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9131)

### CODE REVIEW

**Comment by marionf** [comment]
Hello @fatmaBouchekoua
I will review it after the the rebase & the code review :)

**Review by mbadrani — APPROVED** [review]

**Comment by marionf** [comment]
@mbadrani merged without QA approved status :(

**Comment by fatmaBouchekoua** [comment]
@marionf Please check it, I will open another PR if there are missing scenarios.

**Comment by marionf** [comment]
Seems good for me

**Pull request merged**
