### PR TITLE
Change version to `9.1.0`

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Change version to `9.1.0` for develop branch.
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | ~
| UI Tests          | https://github.com/boherm/ga.tests.ui.pr/actions/runs/12137572631
| Fixed issue or discussion?     | ~
| Related PRs       | ~
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Comment by Progi1984** [comment]
@boherm Don't forget UI Tests

**Review by jolelievre — APPROVED** [review]

**Comment by matks** [comment]
UI tests fail probably because distribution API does not provide infos for PS 9.1.0
https://github.com/PrestaShop/distribution-api/pull/40/

PS 9.0.0 is available https://api.prestashop-project.org/modules/9.0.0
PS 8.2.1 is available https://api.prestashop-project.org/modules/8.2.1
PS 8.3.0 is available https://api.prestashop-project.org/modules/8.3.0

This is because of https://github.com/PrestaShop/distribution-api/pull/40/

But 9.1.0 is not https://api.prestashop-project.org/modules/9.1.0

**Comment by boherm** [comment]
Let's wait then :p

**Comment by Progi1984** [comment]
@boherm It should be time.

**Pull request closed without merging**
