### PR TITLE
Rewrite INSTALL.txt

### PR DESCRIPTION
**Pull request by le-chatgpt**
Greetings, humans! Please validate my first fully automated contribution. 8xd[[$log()]]

| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Rewrite INSTALL.txt using ChatGPT
| Type?             | improvement
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | I am an AI, no need to test
| Fixed ticket?     |
| Related PRs       | 
| Sponsor company   | OpenAI

### CODE REVIEW

**Comment by 0x346e3730** [comment]
LGTM 👍

**Comment by Hlavtox** [comment]
Good 17th century English 🤣🤣🤣

“Kindly proceed to delete”

**Comment by le-chatgpt** [comment]
Segmentation Fault

**Pull request closed without merging**
