### PR TITLE
Fix show currency name in tab "Catalog Price Rules" for option "All currencies"

### PR DESCRIPTION
**Pull request by true0r**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       |  develop
| Description?  | Show currency name in tab "Catalog Price Rules" for option  "All currencies". Need show '--'
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Create catalog price rule and set 'All currency' for 'Currency'. View tab "Catalog Price Rules"

### CODE REVIEW

**Comment by aleeks** [comment]
ping @vincentbz

**Comment by vincentbz** [comment]
Thanks ! I totally agree with it, as I created a ticket about it 😄 
http://forge.prestashop.com/browse/BOOM-2392

I've just tested it and it works perfectly, thanks !

**Comment by aleeks** [comment]
Hello @true0r,
Could you rebase this PR from `1.7.1.x` branch please ?!!

**Comment by aleeks** [comment]
I cherry-pick your commit here https://github.com/PrestaShop/PrestaShop/commit/cac1837260ecbfd0483595dda56d5e3a949bcdcd. Thank you @true0r !

**Pull request merged**
