### PR TITLE
Add disabled visual effect on disabled elements on the translation interface

### PR DESCRIPTION
**Pull request by francoispeyret**
see more on issue #12888

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  |  Fix a visual effect not visible in BackOffice (translations)
| Type?         | bug fix
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #12888 
| How to test?  | Search a word in translations and see if menu has disabled effect on some elements

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/12997)

### CODE REVIEW

**Comment by francoispeyret** [comment]
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop / 1.7.4 / 1.7.5
| Description?  |  Fix a visual effect not visible in BackOffice (transflations)
| Type?         | bug fix / improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | #12888 
| How to test?  | Search a word in translations and see if menu has disabled effect on some elements

**Comment by matks** [comment]
Hi and thanks for the contribution ! I dont think `admin-dev/themes/new-theme/scss/theme.scss` is the right file to put this fix 😉it would probably go rather in some page-specific scss (https://github.com/PrestaShop/PrestaShop/tree/40186ce0129375aaba15e1f143882fc9396ccf8f/admin-dev/themes/new-theme/scss/pages).

Wdyt @PierreRambaud ?

**Comment by PierreRambaud** [comment]
If it's specifc to translations, it must be in https://github.com/PrestaShop/PrestaShop/blob/develop/admin-dev/themes/new-theme/scss/pages/_translation_page.scss and with a better selector to be sure we won't change a behavior on others pages.

**Comment by ghost** [comment]
Ping @francoispeyret 
What do you think of these 2 feedback?

**Comment by francoispeyret** [comment]
@samuel-pires I think it's right.

need a new PL ?

**Comment by ghost** [comment]
Hi @francoispeyret,

Can you have a look at the required modification so we can merge the PR? 🙂 

Thanks,

**Comment by francoispeyret** [comment]
hi @samuel-pires 

all checks have passed :+1:

**Review by PierreRambaud — DISMISSED** [review]

**Comment by francoispeyret** [comment]
hi @samuel-pires 

Why does the PL always go back to merge conflict?

**Comment by PierreRambaud** [comment]
@francoispeyret It's because we merge another pull request containing css modifications. Each time a modification occured you need to rebase and regenerate assets.

**Review by PierreRambaud — DISMISSED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]
Rebased, fixed conflicts and move assets generation in a separate commit.

Ready for merge

**Review by PierreRambaud — APPROVED** [review]

**Pull request merged**
