### PR TITLE
[*] CORE & FO : Improve breadcrumb's rich snippets to match the Google recommrecommendations (https://developers.google.com/structured-data/breadcrumbs)

### PR DESCRIPTION
**Pull request by cgordenne**

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Please do not make it on 1.6 branch but rather on develop branch. Please also see discussion on https://github.com/PrestaShop/PrestaShop/pull/2152, adding the view in a controller is no offense, not MVC so this kind of annoyes me personaly.

Regards

**Comment by inetbiz** [comment]
@cgordenne do you know how to do the same with default bootstrap theme category.tpl and use itemlist for each product/offer including itemcount?

**Comment by cgordenne** [comment]
@gRoussac Sorry, I just followed the documentation who mentions the '1.6' branch. Should I create a new PR with the dev branch or should I continue on this one ?

@inetbiz If you want to put rich snippets on all products from your category page, it isn't a good practice following the Google documentation (https://developers.google.com/structured-data/rich-snippets/products) : use on "a product page that describes a single product" or "a shopping aggregator page that lists a single product, along with information about different sellers offering that product" but if you only want to mention that this is a list of things, try to use this : https://schema.org/ItemList

**Comment by gRoussac** [comment]
Hi @cgordenne,

Doc will be updtaed, 1.6 branch is now master branch. I believe you choose indeed make your PR again on develop branch.

Regards

**Comment by cgordenne** [comment]
@gRoussac Ok thanks, I'll do that and sorry again.

Regards

**Comment by gRoussac** [comment]
our bad !

**Comment by cgordenne** [comment]
@gRoussac If you want you can close this PR because I made a new one : #3539

**Comment by gRoussac** [comment]
Hi again,

Many thanks for this work.

Best regards

**Comment by inetbiz** [comment]
@cgordenne itemlist was the wrapper with product and offer schema is exactly how schema.org wants to see a category page. I've been talking to them in their github repo about this. I had pulled my PR on someproducts because that would have been invalid markup according them and goodrelations lead developer.

**Pull request closed without merging**
