### PR TITLE
Removes old images and their hight DPI

### LINKED ISSUE #28534: Impossible to regenerate images produced in high definition
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

I want to regenerate my thumbnails, but it doesn't do it on the images created in `2x` (`PS_HIGHT_DPI`). Looking at the code, I could see that the `_regenerateNewImages` function does not regenerate them if they still exist. So I went to the `_deleteOldImages` function and I could see that the `Regex` does not take into account `2x` files.

### Expected behavior

I would like that when I click on `Regenerate Thumbnails`, it also does it for high DPI images.

### Steps to reproduce

1. Go to `BackOffice > Design > Images`
2. Scroll down to `Image generation options`
2. Click on `Generate high definition images`
2. Scroll down to `Regenerate thumbnails`
3. Click on `Regenerate thumbnails`
4. Notice in the `/img/p/` folders that the images named `…2x.jpg` are not regenerated

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

7.2

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by w-jerome**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | I want to regenerate my thumbnails, but it doesn't do it on the images created in `2x` (`PS_HIGHT_DPI`). Looking at the code, I could see that the `_regenerateNewImages` function does not regenerate them if they still exist. So I went to the `_deleteOldImages` function and I could see that the `Regex` does not take into account `2x` files.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #28534
| How to test?      | Generate images, then activate the high definition images and generate images again. High definition images are not deleted.
| Possible impacts? | BackOffice > Design > Images > Regenerate thumbnails

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @w-jerome,

It is ok :heavy_check_mark: 
Automatic tests are ok :heavy_check_mark: 
I used this script to check all files with 2x.jpg as commented here: https://github.com/PrestaShop/PrestaShop/issues/28534#issuecomment-1139489941
```php
#!/bin/bash
set +x
searched_type=$1
Images_Files=($(find ./ -type f -name \*_default2x.jpg))
echo "test"
for IMAGE_FILE in "${Images_Files[@]}"; do
    output=$(file --mime-type $IMAGE_FILE)
      echo $output
done
```

if `Generate high-resolution images` is enabled and we Regenerate thumbnails, all images `_default2x.jpg` are **created**
If `Generate high-resolution images` is disabled and we Regenerate thumbnails with erasing images, all images `_default2x.jpg` are **removed**


I attached a screen record

https://user-images.githubusercontent.com/16067358/171031458-1f1e4f4b-2a72-4635-a319-19a785e6c035.mp4

Thanks!

**Comment by Progi1984** [comment]
Thanks @w-jerome & @khouloudbelguith

**Comment by w-jerome** [comment]
Great! Thanks a lot @Progi1984 @NeOMakinG & @khouloudbelguith , it will avoid problems of ghost files and too big files that are not used.

**Comment by Progi1984** [comment]
@w-jerome No thanks to you. There is no small contributions. There is just help for community :muscle:.

**Pull request merged**
