### PR TITLE
[-] BO : Last message from customer shown in Order details (#PSCSX-2169)

### PR DESCRIPTION
**Pull request by xGouley**

### CODE REVIEW

**Comment by kelu95** [comment]
:+1:

**Comment by gRoussac** [comment]
Hi,

Please report on 'devlop' or '1.6.1.x' as you want.

Regards

**Comment by gRoussac** [comment]
Hi,

:warning: I tested this PR and this is witdrawing payment message ( private no employee) from this page AdminOrdersController because it simply takes the first message.

Regards

**Comment by vTerenti** [comment]
(note: this is an automated message, but answering it will reach a real human )

Hi! Thank you for your pull request: your contribution to PrestaShop means a lot to us!

We are aware that this PR is still open after all this time, and we want to make sure that your hard work is not forgotten.

We are diving back into pull requests, and we want to work with you in order to get your PR to completion: we need your feedback!<br/>
Could you read [this article](http://build.prestashop.com/news/review-your-pull-requests/) from [the Build devblog](http://build.prestashop.com/), and take the time to review your pull requests, so that we can work with up-to-date information? You don't have to do it all right now, and every little step helps.

Again, thank you very much for this contribution, and for your renewed feedback on it!

**Comment by xGouley** [comment]
The functional need evolved since the answer of gRoussac: this PR is invalid.

**Pull request closed without merging**
