### PR TITLE
Fix display of available hooks for a module

### LINKED ISSUE #35612: BO > Design > Positions : Can't hook a module
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

The list of hooks was available in 8.1.x but not on develop.

`develop` : 
image

`8.1.4` : 
image

### Expected behavior

The list of hooks is available.

### Steps to reproduce

1. Go to BO
2. Design > Positions
3. Click on "Hook a module"
4. Choose a module like "Bank transfer"
5. List of hooks is not available

### PrestaShop version(s) where the bug happened

9.0.x

### PHP version(s) where the bug happened

8.2

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

@PrestaShopCorp

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | [In this PR](https://github.com/PrestaShop/PrestaShop/pull/34525), @Hlavtox removed deprecated code and made some changes. `modules-position.js` needed to updated. 
| Type?             | bug fix 
| Category?         | BO
| BC breaks?        | no
| Deprecations?     |  no
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/35612
| UI Tests          | https://github.com/nicosomb/ga.tests.ui.pr/actions/runs/8970299797
| Fixed issue or discussion?     | https://github.com/PrestaShop/PrestaShop/issues/35612 
| Related PRs       | https://github.com/PrestaShop/PrestaShop/pull/34525
| Sponsor company   | PrestaShop SA

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @nicosomb

**Review by Hlavtox — COMMENTED** [review]
Missed this one, thanks @nicosomb! :-)

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
No need to qa here, my previous pr was also about just changing tab to controller.

**Comment by nicosomb** [comment]
QA was needed here ... 🙄

**Comment by Hlavtox** [comment]
@nicosomb 

https://domain.cz/xxx/index.php?action=getPossibleHookingListForModule&tab=AdminModulesPositions&ajax=1&module_id=123&token=xxx

```
[{"id_hook":546,"name":"actionModifyFrontendSitemap","description":"This hook allows to modify links on sitemap page of your shop. Useful to improve indexation of your modules.","title":"Add or remove links on sitemap page","registered":true},{"id_hook":536,"name":"displayFooterCategory","description":"This hook adds new blocks under the products listing in a category\/search","title":"Category footer","registered":true},{"id_hook":27,"name":"displayFooterProduct","description":"This hook adds new blocks under the product's description","title":"Product footer","registered":true},{"id_hook":819,"name":"displayHeader","description":"This hook adds additional elements in the head section of your pages (head section of html)","title":"Pages html head section","registered":true},{"id_hook":535,"name":"displayHeaderCategory","description":"This hook adds new blocks above the products listing in a category\/search","title":"Category header","registered":true},{"id_hook":13,"name":"displayHome","description":"This hook displays new elements on the homepage","title":"Homepage content","registered":true},{"id_hook":405,"name":"gSitemapAppendUrls","description":"This hook allows a module to add URLs to a generated sitemap","title":"GSitemap Append URLs","registered":true},{"id_hook":482,"name":"moduleRoutes","description":"","title":"moduleRoutes","registered":true}]
```

https://domain.cz/xxx/index.php?action=getPossibleHookingListForModule&controller=AdminModulesPositions&ajax=1&module_id=123&token=xxx

```
[{"id_hook":546,"name":"actionModifyFrontendSitemap","description":"This hook allows to modify links on sitemap page of your shop. Useful to improve indexation of your modules.","title":"Add or remove links on sitemap page","registered":true},{"id_hook":536,"name":"displayFooterCategory","description":"This hook adds new blocks under the products listing in a category\/search","title":"Category footer","registered":true},{"id_hook":27,"name":"displayFooterProduct","description":"This hook adds new blocks under the product's description","title":"Product footer","registered":true},{"id_hook":819,"name":"displayHeader","description":"This hook adds additional elements in the head section of your pages (head section of html)","title":"Pages html head section","registered":true},{"id_hook":535,"name":"displayHeaderCategory","description":"This hook adds new blocks above the products listing in a category\/search","title":"Category header","registered":true},{"id_hook":13,"name":"displayHome","description":"This hook displays new elements on the homepage","title":"Homepage content","registered":true},{"id_hook":405,"name":"gSitemapAppendUrls","description":"This hook allows a module to add URLs to a generated sitemap","title":"GSitemap Append URLs","registered":true},{"id_hook":482,"name":"moduleRoutes","description":"","title":"moduleRoutes","registered":true}]
```

**Comment by nicosomb** [comment]
@Hlavtox for this kind of bug, QA is needed to check if the interface is still broken or not. 
Please read the issue https://github.com/PrestaShop/PrestaShop/issues/35612 to see what the QA does to check it. 

I have the impression that you are discovering how we work.

**Comment by kpodemski** [comment]
@nicosomb @Hlavtox @PrestaShop/qa-functional 

This change is pretty straightforward, but I tested it to save time and trouble for QA
https://capture.dropbox.com/CFdKk0EH46CO5ka9

All good.

> I have the impression that you are discovering how we work.

I think Daniel is well aware and he also was aware of the fact that this change will be 100% working :)

**Comment by nicosomb** [comment]
So, let's merge without QA 🙂  🎉 , no problem.

**Comment by Hlavtox** [comment]
@nicosomb When we can merge big PRs like attribute page migrations with no QA on it, it's no problem to merge one word. :-)))

**Comment by MatShir** [comment]
@Hlavtox, the QA conducted tests on the attribute page 🤔 We have identified some known issues. 
You are aware that you are violating the rules.

**Comment by kpodemski** [comment]
@MatShir, what does the attributes page have to do with Module positions? 🤔 

In my video (https://capture.dropbox.com/CFdKk0EH46CO5ka9), you see that I followed what @AureRita did in his. Can we stop spending time discussing such nonsense? this fix is clearly good and solves the issue!

**Comment by MatShir** [comment]
ask @Hlavtox, he is comparing different situation

**Comment by Hlavtox** [comment]
> You are aware that you are violating the rules.

And still I brought so many cool improvements that work without issues and people praise them in communities. <3

**Comment by MatShir** [comment]
> And still I brought so many cool improvements that work without issues and people praise them in communities. <3

Could not agree more, but all of them has followed the process, so why changing it know ? 😫

**Pull request merged**
