### PR TITLE
Add Icelandic as supported language

### PR DESCRIPTION
**Pull request by AlexEven**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop.
| Description?  | Adding Icelandic as a supported language to retrieve Crowdin translation.
| Type?         | new feature
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | n/a.
| How to test?  | Icelandic should be available in Translation > Add/Update a language drop-down, and after adding it, you should get the translation as available in Crowdin (=not much for now).

### CODE REVIEW

**Review by eternoendless — COMMENTED** [review]
I don't see a localization pack for `is` (localization/is.xml). Did you perchance forget it?

**Comment by AlexEven** [comment]
I didn't forget it, it's two different things. Localization pack helps you set up a country with its language and taxes and other localization data.
Here it's simply adding the language so you can get the translations.
Localization will come later (if I have both the time and info needed).

I'm doing another commit since the Translations page does not work as is, a little modification is needed.

Thanks!

**Comment by AlexEven** [comment]
Note: I had to add Icelandic to app/Resources/legacy-to-standard-locales.json otherwise the translation page would display an error.

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Thank you @AlexEven

**Pull request merged**
