### PR TITLE
Bug fix remove_from_cart_url

### LINKED ISSUE #19278: Bug fix remove_from_cart_url
#### Describe the bug

Can not delete product from cart with customization

#### Expected behavior

Delete product from cart

#### Steps to Reproduce

1. Create product with customization
2. Add in cart
3. Delete from cart

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.

#### Additional information

* PrestaShop version: N/A
* PHP version: N/A

### PR DESCRIPTION
**Pull request by fest73**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fix remove_from_cart_url and other urls. What are displayed in the basket of products
| Type?         | bug fix
| Category?     | CO 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/19278.
| How to test?  | 1. Create product with customization<br>2. Add in cart<br>3. Delete from cart

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/19251)

### CODE REVIEW

**Comment by Progi1984** [comment]
@dariusakafest  Thank you for your contribution. :hugs: 

Could you explain in [an issue your initial bug for this PR](https://github.com/PrestaShop/PrestaShop/issues/new/choose) (or may be link to an issue) ?

Thanks :+1:

**Comment by fest73** [comment]
@Progi1984 
https://github.com/PrestaShop/PrestaShop/issues/19278

**Comment by Progi1984** [comment]
@dariusakafest Could you answer to @florine2623 on the issue ? Please :)

**Comment by fest73** [comment]
@Progi1984 answered)

**Comment by matks** [comment]
Unfortunately the issue related to this PR was closed due to inactivity, so I close the PR too.

Thank you for submitting the PR, if you come back feel free to open it again 😉

**Pull request closed without merging**
