### PR TITLE
Bump wishlist to 2.1.2

### LINKED ISSUE #29155: New release of the blockwishlist to fix regressions
- https://github.com/PrestaShop/PrestaShop/issues/28832
- https://github.com/PrestaShop/PrestaShop/issues/28844
- update the file https://github.com/PrestaShop/PrestaShop/blob/develop/composer.lock in order to use blockwishlist 2.1.2

Creates regression on the V8 made, fix in the dev branch of the module.
To fix them before the final release of the V8, we need to release a new version of blockwishlist

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x
| Description?      | Bump version to 2.1.2 for `blockwishlist`
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #29155 
| How to test?      | `blockwishlist` is updated to 2.1.2

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Comment by atomiix** [comment]
Maybe we can do this PR on 1.7.8.x and it will be merged in 8.0.x and develop then?

**Comment by NeOMakinG** [comment]
@atomiix done!

**Review by MeKeyCool — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by khouloudbelguith — APPROVED** [review]
Hi @NeOMakinG,

It is ok :heavy_check_mark: 
image

Automatic tests for all FO, BO/Modules/module manager, BO/Customers/Customers => OK

I checked this PR:
https://github.com/PrestaShop/blockwishlist/pull/180 => ok
https://github.com/PrestaShop/blockwishlist/pull/179 => ok
https://github.com/PrestaShop/blockwishlist/pull/181 => ok

Thanks!

**Comment by NeOMakinG** [comment]
Thanks @khouloudbelguith

**Pull request merged**
