### PR TITLE
Allow Hour in specific Price

### LINKED ISSUE #11329: [Idea] Change specific price date ranges to DateTime
**Describe the bug**
We had multiple shop which was running PS1.6 and PS1.7.4.4. I found that in PS1.6, we can click the from date / time and to date / time in product -> Add a specific price. However, In PS1.7, I found we only can select the from date and to date only, but we have some promotion want start at specific time (e.g: 20% discount start at 15:00 and end at 18:00.

Is it PS1.7 not allow to set specific price with time range? 

**To Reproduce**
1. Go to 'Products' -> 'Edit' -'Price'
2. Click on 'Add a specific price'
3. Scroll down to 'Available from and to date' -> Click the calendar 
4. Only allow select the date without time

**Screenshots**
(https://user-images.githubusercontent.com/38032785/48235897-e0581c00-e3fa-11e8-8360-327653eb30bd.png)

**Additionnal information**
PrestaShop version: 1.7.3.2 and 1.7.4.4
PHP version: 7.0.31

### PR DESCRIPTION
**Pull request by ghost**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Allow hour in specific price ( product )
| Type?         | bug fix 
| Category?     | BO
| Ticket? | Fixes #11329
| How to test?  | Go to product -> Price -> Add specific price -> select date

It's the best way i found, i don't find the way for icon works ...  

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/8571)

### CODE REVIEW

**Comment by ghost** [comment]
`icons: {down: "dropdown-toggle"}`

Works but I do not have the competence to do the opposite

**Comment by vincentbz** [comment]
Hi @okom3pom ,

Thanks for that PR. And it works :)
It looks like this, 

image

We'll see with the devs' for the icons

**Comment by colinegin** [comment]
@TristanLDD We cannot test this PR as it is too old.

**Comment by matks** [comment]
@colinegin With a few update, I can get it work. However
- it needs some work as we added the "edit a specific price" in the meantime and this one still uses date, not date and time (should take me 1 hour)
- here is how it displays:

**Select hour**
capture d ecran 2018-12-14 a 15 04 11

**Select hour value**
capture d ecran 2018-12-14 a 15 04 15

So this behavior requires that if you want a specific hour, minute and second you must
- click on "hour"
- select value
- click on "minute"
- select value
- click on "second"
- select second

**Comment by colinegin** [comment]
In my opinion it's not the easiest, but we can imagine that merchants will probably never update seconds (should be set to zero by default in my opinion), and they will usually take a "full" hour (meaning X:00:00), so in the end it would mean 2 ou 4 clicks which is acceptable. Furthermore, they will also be able to edit the field itself.

So if it's the easiest way for you, it's ok for me. What do you think @TristanLDD ?

**Comment by jaribu** [comment]
Does not work on prestashop 1.7.4.2

**Comment by PierreRambaud** [comment]
@jaribu Thanks but we know :) This one has not been merged yet ;)

**Comment by ghost** [comment]
[Private joke] nobody loves me ( @mickaelandrieu ) [/Private Joke]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
@okom3pom Are you able to rebase? :)

**Review by matks — CHANGES_REQUESTED** [review]
This PR needs to be updated to work 😄 give me a few hours

The datepicker is defined in 2 places and some JS around needs to be updated to work with hour & time

See below

**Comment by matks** [comment]
@okom3pom We ❤️you

**Comment by colinegin** [comment]
@TristanLDD still needs to review the expected design !

**Comment by TristanLDD** [comment]
My recommandation for the date-time picker would be to use this bootstrap component behavior [https://eonasdan.github.io/bootstrap-datetimepicker/](url)

capture d ecran 2018-12-19 a 11 56 14

capture d ecran 2018-12-19 a 11 56 21

It allows to edit the date/time directly from the input fields as well, but the use of arrow button makes it easier to use. 

Would it be possible to use this behavior ?

**Comment by matks** [comment]
In order to allow hour & time in the Datepicker for specific prices page, you must:
- modify it in `admin-dev/themes/new-theme/js/app/utils/datepicker.js`
- modify it in `admin-dev/themes/new-theme/js/pages/catalog/product/specific-price-form-handler.js`
- rebuild the Javascript files required in the New Theme for Backoffice (see [devdoc](https://devdocs.prestashop.com/1.7/development/compile-assets/) if you have not done it before)

However this requires more time as:
- `admin-dev/themes/new-theme/js/app/utils/datepicker.js` might be used in several places so this might enable hour & time for **more** pages, we need to check that to ensure the modification only targets specific prices
- there is backend validation to update I think (for example the check for duplicates might ignore hour so if you create 2 specific prices, one for 12:12am and one for 12:15am the backend might say "you cannot create the 2nd price, it is a duplicate")
- default time used is "current time" so when you create a new specific price at 2:15pm the datetimepicker is initialized to 2:12pm 😛 
- handle UX feedback

@okom3pom Do you feel like giving it a go or can I start working on it ? Because you started it, so if I do the PR I would "steal the credit" for it 😉 

And I cannot use your commit because you branch cant be found anymore 😢

**Comment by Rioo** [comment]
Does someone have a solution for PS 1.7.4.2 this fix doesn't work?Thanks

**Comment by Rioo** [comment]
Does someone have a solution for PS 1.7.4.2 this fix doesn't work?Thanks

**Comment by eternoendless** [comment]
Closed due to inactivity. Since the branch is gone and the PR won't be merged as-is, there's no point in keeping it. Follow #11329 for future reimplementations.

**Comment by zuk3975** [comment]
https://github.com/PrestaShop/PrestaShop/pull/13716
This PR enables hours along with page migration.

**Comment by colinegin** [comment]
@zuk3975 thanks ! Do you think it could be added to other pages with start & end date such as product page, cart rule page ?

**Comment by zuk3975** [comment]
It can be added where hours are required. However i faced some issues while enabling hours (The plugin we are using offers more modifications, but it's simply not working as documented, might be because of different bootstrap versions... so I implemented the currently only working solution). The problem is - `lack of appearance modifications`. For example if hours are added to the date picker, `there is little to no way of modifying where should it appear`. It will simply show up side by side with calendar, without ability for user to show/hide/switch calendar and hour picker using buttons.

**Comment by colinegin** [comment]
@MatShir & @marionf , do you think it would be possible to add this feature (hours for specific price) in the new product page?
This is a demanded feature, available in 1.6 which has been lost in 1.7.

**Comment by matks** [comment]
> @MatShir & @marionf , do you think it would be possible to add this feature (hours for specific price) in the new product page?
> This is a demanded feature, available in 1.6 which has been lost in 1.7.

Yes ! 🎉

**Pull request closed without merging**
