### PR TITLE
Fix preview email themes test

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Fix preview email themes test
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27544)

### CODE REVIEW

**Review by nesrineabdmouleh — APPROVED** [review]

**Review by Progi1984 — COMMENTED** [review]
Why  adding 4 new layouts ?

**Comment by boubkerbribri** [comment]
> Why adding 4 new layouts ?

A contributor PR just added 4 emails theme to modern theme, so i'm fixing the UI tests

**Comment by Progi1984** [comment]
@boubkerbribri Have you got the link of the PR ?

**Comment by boubkerbribri** [comment]
> @boubkerbribri Have you got the link of the PR ?

Of course: https://github.com/PrestaShop/PrestaShop/pull/25992

**Review by Progi1984 — CHANGES_REQUESTED** [review]
An issue should be created. These emails should be removed. Modules are not anymore supported.

**Comment by boubkerbribri** [comment]
> An issue should be created. These emails should be removed. Modules are not anymore supported.

Since there is already an issue, i just added a [comment](https://github.com/PrestaShop/PrestaShop/issues/27084#issuecomment-1026948462) there.

**Review by Progi1984 — APPROVED** [review]
I approved. And when #27084 will be done, we will change it.

**Comment by Progi1984** [comment]
Thanks @boubkerbribri

**Pull request merged**
