### PR TITLE
Fix use of protocol

### PR DESCRIPTION
**Pull request by MathiasReker**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Protocol should not be hardcoded.
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | /

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/11678)

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Hi @MathiasReker,

how can we test this? I'm pretty sure it fixes a bug on shops powered by HTTPS but I'd like a reproducible test case so the QA team can validate it.

Mickaël

**Comment by MathiasReker** [comment]
@mickaelandrieu I agree with you. Sorry, this was done from a theocratic point of view. I can not add a reproduce case for this. I am not sure exactly where to check this. It should be image path of some PDF stuff and some cronjobs. I am not 100% sure.

**Comment by mickaelandrieu** [comment]
I'll ask another approval from @PrestaShop/prestashop-core-developers then :+1:

**Review by PierreRambaud — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks everyone

**Pull request merged**
