### PR TITLE
Fixes wrong images on order confirmation page with simple products

### PR DESCRIPTION
**Pull request by ckubitza**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Fixes wrong images on order confirmation page with simple products. Only the last image was used for all products
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-3695
| How to test?  | Order multiple simple products

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for your contribution!

Sadly, you now have malformed commits instead of just one commit:
* the initial commit, which does not follow the [PS naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message),
* one commit which does follow the naming convention,
* one merge commit -- which if merged can break the repository's history!

Could you try and [squash those commits into just one](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)? [Another explanation of squashing](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/).

Thank you!

**Comment by ckubitza** [comment]
Hm, I am not sure if its correct now, could you have a look again?

**Comment by Nakahiru** [comment]
Just tested, it works for me!

**Review by maximebiloe — APPROVED** [review]

**Comment by maximebiloe** [comment]
Thank you @ckubitza

**Comment by kpodemski** [comment]
Wow, i just came across this bug, nasty one!

**Comment by MisterMike** [comment]
Thank you @ckubitza, works like a charm and saved me some time!

**Pull request merged**
