### PR TITLE
Pass $query with reference into actionProductSearchProviderRunQueryBefore hook

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The actionProductSearchProviderRunQueryBefore hook is call before the query run. It could be usefull to be able to update the query itself (sort orders, for examples) if needed.
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Implement a module with this hook and check to modify the vars on the hook return.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by PululuK — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @PrestaEdit 

Thanks for your PR. Could you please provide us a module to can test the PR.
We @PrestaShop/qa-team think, that we should have an issue (Feature) for this improvement to know how to test it.

Thank You!

**Comment by PrestaEdit** [comment]
Hi @HanaRebaiQA ,

There is a module :
[issue.zip](https://github.com/PrestaShop/PrestaShop/files/9310832/issue.zip)

This will modify the search result (search a product like Hummingbird inside the shop).
 
To be honest, I've try this one without the Pull Request and it's seems working as it.
I let you confirm it maybe.

Edit: It's like PHP 7.4 / 8 handle variable already as reference (so you can edit them without this modification).
Or it's because $query is an object. If a PHP developer could confirm this, maybe :)

**Comment by PrestaEdit** [comment]
Why it's still in "Waiting for author", there ?

**Review by FabienPapet — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-team 

QA by a dev?

**Comment by AureRita** [comment]
Hi @PrestaEdit 

Thank for your module, I try it and I didn't see the difference when I've got your PR and without your PR, as you can see (the first one is without your PR and the second shop is with it) 

[Untitled_ Oct 31, 2022 4_38 PM.webm](https://user-images.githubusercontent.com/100699445/199048688-753de00d-2074-4a1a-ae12-2e964b32eee6.webm)


What should be the difference ?

**Pull request closed without merging**
