### PR TITLE
Choose previous date for cart rule test

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 1.7.8.x 
| Description?      | Choose previous date for cart rule test
| Type?             | refacto
| Category?         | TE
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | no tests needed
| Possible impacts? | none

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/25384)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Wait for the next release before merging it :+1:

**Comment by Progi1984** [comment]
## WAIT FOR 1780 RELEASE

**Comment by Progi1984** [comment]
@boubkerbribri Why do you close it ?

**Comment by boubkerbribri** [comment]
> @boubkerbribri Why do you close it ?

The fix is already done by @SD1982 on another PR

**Comment by Progi1984** [comment]
What a man, this @SD1982 ;)

**Pull request closed without merging**
