### PR TITLE
Add help field when integer type is used to a form

### LINKED ISSUE #27761: The help field is not displayed when integer type is used to a form
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

The help field is not displayed when integer type is used to a form.

Screenshot (3)

### Expected behavior

Help field need to be display

Screenshot (2)

### Steps to reproduce

1) Enable B2B

2) Edit a customer

3) See Maximum number of payment days field.

### PrestaShop version(s) where the bug happened

8.0

### PHP version(s) where the bug happened

7.4

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | The help field is not displayed when integer is used to a form
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27761
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/27761
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/27762)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by atomiix — DISMISSED** [review]

**Comment by marwachelly** [comment]
Hello, 

PR needs to be reviewed again.

Many thanks,

**Review by marwachelly — CHANGES_REQUESTED** [review]
Hello,

PR needs to be reviewed again.

Many thanks,

**Review by saulaski — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by tegbessou — APPROVED** [review]

**Review by marwachelly — APPROVED** [review]
Hello,

PR is tested. The help test is well added.
image
PR is QA approved.

Thanks,

**Comment by Progi1984** [comment]
Thanks @okom3pom & @marwachelly

**Pull request merged**
