### PR TITLE
Fix static vars not using scss vars on new-theme and classic

### LINKED ISSUE #23759: The project uses #fff a lot of times instead of the $white var
#### Describe the bug

Legacy developers were using #fff variables everywhere instead of using the $white variable which is way more maintainable

#### Expected behavior

Using $white everytime you need the white color

####
No need to reproduce, it's mainly a dev thing

* PrestaShop version: develop

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Using static css vars instead of scss variable is making things unmaintanable when you need to replace every white by another color
| Type?             | improvement
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #23759.
| How to test?      | It's not really testable tbh : search for #363a41, #25b9d7, #fafbfc, #bbcdd2... Maybe I missed some, but I don't think so!
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

⚠️ wait for https://github.com/PrestaShop/PrestaShop/pull/23760 to be merged before this one ⚠️ 

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/23760)

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@NeOMakinG CI is :red_circle: : https://github.com/PrestaShop/PrestaShop/pull/23803/checks?check_run_id=2227710380#step:12:2771

**Comment by NeOMakinG** [comment]
@Progi1984 should be fine now :)

**Review by Progi1984 — DISMISSED** [review]

**Comment by matks** [comment]
@NeOMakinG sorry for late review :( can you rebase then I'll review?

**Comment by NeOMakinG** [comment]
@matks done

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-maintainers I think if we find a last approve, we can merge without QA.

@PrestaShop/qa-functional Are you ok with that ?

**Review by matthieu-rolland — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Pull request merged**
