### PR TITLE
Add missing hooks actionCustomerLogout & displayCheckoutSummaryTop

### LINKED ISSUE #19894: No db entry for actionCustomerLogoutBefore or actionCustomerLogoutAfter
#### Describe the bug

There are no entries in the ps_hook table for actionCustomerLogoutBefore or actionCustomerLogoutAfter, so you can't hook modules to them.

I'm testing on 1.7.6, but I don't see them in the database for 1.7.7 either.

Adding the entries to the db, resolves the issue

#### Expected behavior

You should be able to hook to these positions.

#### Steps to Reproduce

1. With a module that provides hook code to these hook, try to transplant the module to them.

**Screenshots**

#### Additional information

* PrestaShop version: 1.7.6
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Add missing hooks actionCustomerLogout After Before and displayCheckoutSummaryTop
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/19894 AND https://github.com/PrestaShop/PrestaShop/issues/15594
| How to test?      | Install a new shop and check ps_hook table
| Possible impacts? | No

This Pr replaces https://github.com/PrestaShop/PrestaShop/pull/26084

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26072)

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
looks good to me 👍 

Shouldn't we add it in the autoupgrade module as well ?

**Comment by ghost** [comment]
https://github.com/PrestaShop/autoupgrade/pull/422

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-maintainers 

What about adding some mechanism or question in the template: "Does your PR introduce new hooks?"? so we could have an automatic label to inform the contributor and a maintainer that it has to be added to the `autoupgrade` too? 🤔 Maybe I'm overthinking 🤔

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by marwachelly** [comment]
Hello, 
To test the PR, after a fresh install, I installed a new module. The added hooks actionCustomerLogout After Before and displayCheckoutSummaryTop are now present and works fine as shown in the attached picture
image

But when I go to Advanced Parameters >database>SQL Managr => Those hooks are not present in PREFIX_hook table. 
https://www.awesomescreenshot.com/video/5599141?key=e8ba524a9dd6ae480dec9581c95656af

Could you please check?
Many thanks!

**Comment by ghost** [comment]
Hello,

I tried again and the hooks are present on the table.

https://www.okom3pom.com/videos/newHook.webm

Did you run the installation with the PR?

**Comment by marwachelly** [comment]
> Hello,
> 
> I tried again and the hooks are present on the table.
> 
> https://www.okom3pom.com/newHook.webm
> 
> Did you run the installation with the PR?

Hello @okom3pom ,
Yes I tried with the PR.Could you please check your screen record (it is not available).
Thanks

**Comment by ghost** [comment]
oups sorry

https://www.okom3pom.com/videos/newHook.webm

**Comment by marwachelly** [comment]
Hello, 
To test this PR I installed a new module 

> oups sorry
> 
> https://www.okom3pom.com/videos/newHook.webm

Hello,
Could you please install new shop with prefix different from ps and retest. In my case I used ms. The added hooks are not present in ms_hook table.

Thanks,

**Comment by ghost** [comment]
I hope this video will show you the way

https://www.okom3pom.com/videos/newHook2.webm

**Comment by ghost** [comment]
Don't hesitate to contact me on the open source slack

**Comment by marwachelly** [comment]
Hello @okom3pom ,
Thank you for your feedback. The issue is fixed and the hooks added are present in the data base and works fine. Just I need to test the PR PrestaShop/autoupgrade#422 to check the upgrade module.=> PR can be merged.

**Comment by Progi1984** [comment]
Thanks @okom3pom & @marwachelly

**Pull request merged**
