### PR TITLE
Update MobileDetect to 3.74.0

### LINKED ISSUE #32644: mobiledetectlib
As a developer I want to have framework up2date so : 
- I have a secure plateform
- New features 
- more performant prlateform in some case

## Description 

Upgrade [mobiledetectlib](https://packagist.org/packages/mobiledetect/mobiledetectlib) to,  at least, 3.74.0 version.

See also : 
[frameworks - PHP dependancies](https://www.notion.so/prestashopcorp/Les-cons-quence-en-fonction-des-versions-de-PHP-support-es-5fa9b7e6654a495cbcbbf86cb82fee91)
and 
[dependencies](https://miro.com/app/board/uXjVMMFa4_Y=/?share_link_id=447161604159)

## AT

PS should work (ISO) with the 3.74.0 version of mobiledetectlib

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Update MobileDetect to 3.74.0 - add type return and var type in Context
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | CI are green
| Fixed ticket?     | Fixes #32644
| Related PRs       | -
| Sponsor company   | -

### CODE REVIEW

**Review by tleon — DISMISSED** [review]

**Review by nicosomb — COMMENTED** [review]
When we update a class like that, is that possible to replace "snake case" by "camel case"? 

@jolelievre wdyt?

**Review by boherm — DISMISSED** [review]

**Comment by M0rgan01** [comment]
@nicosomb I had done it at the beginning, but it causes bc breaks

If the property was private it would have been easier :smiling_face_with_tear:

**Review by nicosomb — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Comment by paulnoelcholot** [comment]
Need review please :) ( @kpodemski  ? )

**Comment by kpodemski** [comment]
@paulnoelcholot conflicts

**Review by nicosomb — APPROVED** [review]

**Comment by M0rgan01** [comment]
@kpodemski Done

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Auto tests: https://github.com/kpodemski/ga.tests.ui.pr/actions/runs/5170729074

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional CI and auto-tests are green (except for the one known issue on the develop), can we merge?

**Comment by Robin-Fischer-PS** [comment]
OK for merge, thanks for the PR @M0rgan01 !

**Pull request merged**
