### PR TITLE
Check that all product are diplayed in the front Office

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Check that all the products activate in the back office exists in the front office
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | /
| How to test?  | TEST_PATH=high/02_product/10_display_all_product  npm run specific-test -- --URL=UrlFrontOffice

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9418)

### CODE REVIEW

**Review by fatmaBouchekoua — DISMISSED** [review]

**Comment by fatmaBouchekoua** [comment]
@mbadrani this PR is ready to be merged

**Comment by mbadrani** [comment]
@fouratachour need rebase

**Comment by fouratachour** [comment]
@mbadrani Done!

**Review by mbadrani — APPROVED** [review]
Rebase well done by Fourat

**Pull request merged**
