### PR TITLE
BO: Unable to generate invoice with button

### PR DESCRIPTION
**Pull request by tanzo**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Unable to generate the invoice with button in 'Documents' tab if before is generated the delivery document |
| Type? | bug fix / improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | Generate a delivery document without generate the invoice first. So the unique method to generate the invoice is with a status change. |

BO: Unable to generate the invoice with button in 'Documents' tab if before is generated the delivery document

### CODE REVIEW

**Comment by xBorderie** [comment]
Thank you for taking the time to redo it!

**Comment by tanzo** [comment]
Thank you too for time that you've spent for me

**Comment by tanzo** [comment]
Xavier, sorry, but Git is making me crazy. I created some trouble?

**Comment by xBorderie** [comment]
Ah, it seems you made your PR on a outdated codebase: you have several commits that are not supposed to be here (they
I would advise to update your 1.6.1.x branch to the latest codebase, re-introduce the changes from 2cb50c7fbaef5e5302575846559396119f333c1b in that updated codebase, then create a new commit (and PR) from there.
Good luck, and thank you!

**Comment by tanzo** [comment]
Xavier, I'm really sure my codebase was updated to last changes. I don't understand where they come out...

Please, can you help me in these steps?

**Comment by xBorderie** [comment]
It is not, my friend. See here: https://github.com/tanzo/PrestaShop/tree/1.6.1.x 
GitHub clearly says "This branch is 11 commits ahead of PrestaShop:1.6.1.x.".

And see the comparison between your 1.6.1.x and the master 1.6.1.x: https://github.com/PrestaShop/PrestaShop/compare/1.6.1.x...tanzo:1.6.1.x

Here's how to sync your fork: https://help.github.com/articles/syncing-a-fork/

**Comment by tanzo** [comment]
Xavier, please correct me if I do some wrong steps.
1. From github.com I click on Fork. (now I don't have the last updated codebase?)
2. From terminal on my pc, 'git clone https://github.com/tanzo/PrestaShop'
3. Add a remote fork https://help.github.com/articles/configuring-a-remote-for-a-fork/.
4. Sync the fork https://help.github.com/articles/syncing-a-fork/
5. From terminal 'git checkout 1.6.1.x' (to switch on 1.6.1.x branch)
6. Edit the file with my update
7. From terminal 'git commit' . (Here i insert the message for the commit)
8. From terminal 'git push' . (To upload my edit to server)
9. From github.com I create a pull request.

This steps are correct?

**Comment by xBorderie** [comment]
Seems good to me! 

At this point, you might be more at ease by closing this PR and opening a new one :)

**Pull request closed without merging**
