### PR TITLE
Remove deprecated function testGetFormCombination

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove deprecated function testGetFormCombination. Use testGetFormCombinations instead.
| Type?             | refacto
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | yes
| Fixed ticket?     | -
| Related PRs       | -
| How to test?      | Check if products combinations (create / update) works as expected
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by 0x346e3730 — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Comment by matks** [comment]
@mflasquin We can go forward on 01/02/2023 as `develop` will be the branch for 9.0.0 😉

**Review by matks — DISMISSED** [review]
OK to go forward on 01/02/2023

@mflasquin can you ping us on 1st of February? 😄

**Comment by mflasquin** [comment]
ping @matks :smile:

**Review by FabienPapet — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]
Please document BC Breaks like in this PR:
https://github.com/PrestaShop/PrestaShop/pull/28988

**Comment by mflasquin** [comment]
Already made in https://github.com/PrestaShop/PrestaShop/pull/28564

**Pull request closed without merging**
