### PR TITLE
Performance improvements on last visit

### PR DESCRIPTION
**Pull request by MAX-IT-Tech**
| Questions | Answers |
| --- | --- |
| Branch? | all |
| Description? | significant performance improvements of LAST_VISIT sql query |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | on my configuration time of execution of old sql query is ~17 s, new query is 0.096s, ps_guest rows 5084327, ps_connections rows 2616657. |

#### Important guidelines
- Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
- Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
- Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

significant performance improvements of LAST_VISIT sql query

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
@jocel1 would you mind to review it please ? :)

**Review by jocel1 — CHANGES_REQUESTED** [review]
If you replace the LEFT JOIN by a JOIN in the original query, it should be fast as well. Could you test it on your side, I modify the PR if it's the case ?

**Comment by zuzul** [comment]
i'm replaced LEFT JOIN by a JOIN and test in. Results are same.

**Comment by jocel1** [comment]
You mean it's still slow on you side ? If it's still the case, I'm ok with your PR as is.

**Comment by zuzul** [comment]
replace 'LEFT JOIN' by 'JOIN' make no difference on original and my modified query.

=== my modified query === Query time: 0.096 sec.
SELECT c.`date_add` AS last_visit
 		FROM `ps_connections` c 
       	LEFT JOIN `ps_guest` g USING (id_guest) // <- replace by JOIN, got same results
 		WHERE g.`id_customer` = 0 ORDER BY c.`date_add` DESC LIMIT 1

=== original query === Query time: ~18-19 sec.
SELECT MAX(c.`date_add`) AS last_visit
         FROM `ps_guest` g
         LEFT JOIN `ps_connections` c ON c.id_guest = g.id_guest // <- replace by JOIN, got same results
         WHERE g.`id_customer` = 0 LIMIT 1

**Comment by jocel1** [comment]
ok, I would have expected the second query to be much faster with a JOIN instead of a LEFT JOIN (on my DB, it's the case, but I have only 65 lines in ps_connections, and 374950 lines in ps_guest).

So your original PR is ok for me

**Review by jocel1 — APPROVED** [review]

**Comment by thierrymarianne** [comment]
Thank you!

**Pull request merged**
