### PR TITLE
Add attribute ID to product update response

### PR DESCRIPTION
**Pull request by unlocomqx**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Add the attribute ID so that modules can read it directly without making another ajax call |
| Type? | improvement |
| Category? | FO |
| BC breaks? | no |
| Deprecations? | no |
| How to test? | Sample code |

```
prestashop.on('updateProduct', function(resp){
    var id_product_attribute = resp.id_product_attribute;
    //...
});
```

### CODE REVIEW

**Review by antoin-m — APPROVED** [review]

**Comment by unlocomqx** [comment]
I did a rebase and "moved" my JS edits to the core as the block was moved
8485c73fcd841a32ff2c6290642239cc90f9722c

**Review by antoin-m — APPROVED** [review]

**Review by firstred — APPROVED** [review]

**Comment by unlocomqx** [comment]
Hello guys, sorry to push :D but this is necessary for my modules and others to get the product attribute ID directly when the user changes a product option

**Comment by maximebiloe** [comment]
Hello,

We did something more generic with this: https://github.com/PrestaShop/PrestaShop/blob/develop/themes/classic/templates/catalog/_partials/product-details.tpl#L1
You now have the entire product json encoded, so you can access to the id_product_attribute.

This PR is no longer needed.

Regards

**Comment by xBorderie** [comment]
Hey @unlocomqx ! Does Maxime's comment answer your concern/need?

**Comment by unlocomqx** [comment]
Yes, Thank you, that's exactly what I'm looking for 
Best regards

**Comment by xBorderie** [comment]
Great!

**Pull request closed without merging**
