### PR TITLE
Small ux optimizations

### LINKED ISSUE #9488: [BOOM-6294] [Product page] Small UX optimizations
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOOM-6294).

- _**Reporter:**_ coline.ginestet
- _**Created at:**_ Mon, 20 Aug 2018 18:51:03 +0200

<p>A few quickwin optimizations are needed to improve UX on the product page :</p>
<h1><a name="1.Layout"></a>1. Layout</h1>
<ul>
	<li>Remove margins and put the page content in full width for a better display on small screens.</li>
</ul>

<ul>
	<li>Reduce drag & drop area dimensiosn for image upload</li>
</ul>

<ul>
	<li>Increase dimensions of the text editor.</li>
</ul>

<h1><a name="2.Navigation"></a>2. Navigation</h1>
<ul>
	<li>Put the save button on the left of other buttons in the footer bar</li>
</ul>

<ul>
	<li>Redefine the links organization in the permanent footer</li>
</ul>

<h1><a name="3.UIcomponents"></a>3. UI components</h1>
<ul>
	<li>In “Basic Settings”, in the right column, in "categories" section, expand the category tree by default</li>
</ul>

<ul>
	<li>In “Basic Settings”, in the right column, in "categories" section, merge the 2 links “Expand” and “Collapse”.</li>
</ul>

### PR DESCRIPTION
**Pull request by CaptainYouz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop 
| Description?  | Implementation of small UI changes in BO> Product Page> New Product. Issue #9488
| Type?         | improvement
| Category?     | BO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #9488 
| How to test?  | See UI changes before/after in BO Product Page

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/10170)

### CODE REVIEW

**Comment by LouiseBonnard** [comment]
Can somebody tell me if there are a lot of strings to check in the PR? Diff files are quite heavy to load (even with the Reviewable tool) and make the search for wording pretty difficult. :-(

**Comment by CaptainYouz** [comment]
@LouiseBonnard no strings were changed/modified for this issue.

**Comment by LouiseBonnard** [comment]
@CaptainYouz, great, thanks Anas!

**Comment by mickaelandrieu** [comment]
Hello @CaptainYouz, would you mind to rebase your contribution and build (again) the assets?

Then I can put the 'Waiting for QA' label

**Comment by CaptainYouz** [comment]
@mickaelandrieu done :)

**Review by mickaelandrieu — APPROVED** [review]

**Comment by mickaelandrieu** [comment]
Thanks  @CaptainYouz & everyone for review

**Pull request merged**
