### PR TITLE
Fix addslashes not working

### LINKED ISSUE #31593: smarty js=1 modifier don't escape string anymore in smarty backoffice tpl in PrestaShop 8
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

In prestashop 8.1 beta 1, the js=1 flag in smarty translation doesn't escace the string.
This could cause a lots's of XSS security issues.

It's a regression from PrestaShop 8.0

### Expected behavior

escape the string

### Steps to reproduce

1. Install Prestashop 8.1 beta in french
2. Try to add a new carrier : the page is broken du to an non escaped js string.

image

Javascript error occurs in nearly every bo page, in information page, module page.

the smarty code is correct here :
`var need_to_validate = '{l s='Please validate the last range before creating a new one.' js=1 d='Admin.Shipping.Notification'}';`

The js=1 parameter doesn't do his job.

### PrestaShop version(s) where the bug happened

8.1 beta 1

### PHP version(s) where the bug happened

all

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Addslashes was not applied
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31593 
| Fixed ticket?     | Fixes #31593 
| Related PRs       | #30415
| Sponsor company   | Prestashop SA

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by lartist — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by 0x346e3730 — DISMISSED** [review]

**Review by nicosomb — DISMISSED** [review]

**Review by jolelievre — DISMISSED** [review]
Thanks @mflasquin

**Review by jolelievre — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Comment by PrestaEdit** [comment]
Ping @prestamodule to make a quick test about this, maybe.

**Review by hibatallahAouadni — APPROVED** [review]
Hello @mflasquin 

I checked almost pages in BO, and it seems fixed :heavy_check_mark: 
### Edit Carrier:
image

### Cart Rules:
image

Thanks to your PR, I found new regression #31660 on Product Combinations page :grin: 
Otherwise, LGTM QA :heavy_check_mark: 

Thanks!

**Comment by mflasquin** [comment]
Thanks @hibatallahAouadni

**Comment by loremipsum99** [comment]
Hi

Did the QA for this change also entail the generation of PDFs?  I've found that due to this commit the translation of generated PDFs  is broken! 

When I try go generate an invoice in the BO for an order in another language than English, all values that should be language specific are in English and not translated.

Puzzled by this bug after having upgraded to version 8.0.2 I did a debug session and found the following:

Due to this change strings in PDF templates are translated with the method 'Translate::getPdfTranslation()'. This was not the case before. This method depends on the global variable '$_LANGPDF'. If that one is not set or it's not an array, no translation will be done! That is, the method will simply return the string that should have been translated (after escaping quotes). And this is exactly what happens in my case! The global variable $_LANGPDF is not set. And having analyzed the entire code-base I also couldn't find any place where this variable would be set. I suspect the method 'Translate::getPdfTranslation()' is some legacy method that is broken since a while but as it was not used anymore nobody noticed it. With this change the method is used again and now causes issues.

**Pull request merged**
