### PR TITLE
1.7.6.x Discount voucher problem with non-promotional item

### PR DESCRIPTION
**Pull request by ALTITUDEV**
Hello,

Please excuse me in advance for my language, I have a bug with your version.

If an item on sale is added to a basket then it does not accept discount coupons (no worries at this level)

If an item is not on sale then the discount voucher applies (no worries too)

On the other hand, if the customer adds a promotional item + a non-commercial item to his basket, the discount voucher applies to the entire basket and not just the non-commercial item.

https://imgur.com/09d9be4a-5940-4b2e-9c33-3fbcc46206af

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/13727)

### CODE REVIEW

**Comment by matks** [comment]
Hi @CryoDevFR is it an issue or a PR ? I cannot see your contribution in the commit list.

**Comment by ALTITUDEV** [comment]
Hello, 

I don't know how Ghitub works, but it's a problem with the discount coupons, they take the whole basket into account even the items on special offer that I don't want to have cumulated as a promotion

**Comment by matks** [comment]
Then what you want to do is open an issue 😉 https://github.com/PrestaShop/PrestaShop/issues/new/choose

**Comment by ALTITUDEV** [comment]
Thanks :)

**Pull request closed without merging**
