### PR TITLE
Buyer verification before downloading the virtual product

### PR DESCRIPTION
**Pull request by thibault78580**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Currently when you buy a virtual product, you can share the download link and download the product without credentials of the customer account.
| Type?         | new feature
| Category?     | FO
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-5864
| How to test?  | Make an order with a virtual product, place the order in accepted payment, disconnect from the customer area, click on the download link of the product in the download email, enter your login details to download the virtual product.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/9262)

### CODE REVIEW

**Comment by matks** [comment]
Sorry for very late answer. I think this is a choice to see with Product team (whether or not to limit download capabilities to logged customers). It seems to make sense but some merchants might want to keep the download open.

**Comment by NeOMakinG** [comment]
> Sorry for very late answer. I think this is a choice to see with Product team (whether or not to limit download capabilities to logged customers). It seems to make sense but some merchants might want to keep the download open.

Maybe make it configurable so merchant who wants to keep it open can activate it again ? wdyt @PrestaShop/prestashop-product-team ?

**Comment by colinegin** [comment]
Hello @thibault78580 , thanks for your Pull Request. I have a few remarks :
- your solution prevents guest customers from buying downloadable products which in my opinion is a problem for all merchants who accept guest purchases. 
- it's quite common to be able to access the downloadable file from a link without having to relog. Why do you think this is a problem ? Do you face any other problem with this current behaviour ?

**Comment by PierreRambaud** [comment]
Hi @thibault78580 ,

Since we had no news from you for more than 30 days, I'll close this pull request. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
