### PR TITLE
Introduce store presenter

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Introduces presenter and lazy array for stores in front office, following https://github.com/PrestaShop/PrestaShop/pull/31309. It allows to lazy load data and use multiple image formats.
| Type?             | new feature
| Category?         | FO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Install this PR, see that the "stores" page in frontoffice works the same. I just rewrite the code but the behavior is not modified.
| Fixed ticket?     | 
| Related PRs       | https://github.com/PrestaShop/autoupgrade/pull/614
| Sponsor company   | 

### New hooks
- actionPresentStore

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by tleon — COMMENTED** [review]
Same comment as in #32653 

Since this is targeted to develop and planned for 9.0.x I guess you can type hint the class properties and even use some promoted properties in some cases.

**Review by matks — APPROVED** [review]
Good for me. Feel free to apply @tleon suggestion ;) it's interesting too

**Review by boherm — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
LGTM, QA :white_check_mark:
Run tests are green except the header regression on develop: https://github.com/hibatallahAouadni/testing_pr/actions/runs/5129635018
And thanks to this PR I found an old issue :grin: after saving the form store, the button Add new store disappear #32766

Thanks!

**Comment by kpodemski** [comment]
thanks @Hlavtox :)

**Comment by Hlavtox** [comment]
@tleon I will keep your suggestions in mind and apply them when I get to it. 👍

**Pull request merged**
