### PR TITLE
Removed _includeContainer ; never more used

### PR DESCRIPTION
**Pull request by prestamodule**
| Questions | Answers |
| --- | --- |
| Branch? | develop |
| Description? | Removed _includeContainer ; never more used |
| Type? | improvement |
| Category? | BO |
| BC breaks? | no |
| Deprecations? | no |
| Fixed ticket? |  |
| How to test? | .. |

### CODE REVIEW

**Comment by tchauviere** [comment]
Hi @prestamodule,

Thanks for your contribution. It seems there's conflict on your commit ATM. Can you update it ?

Thanks a lot !

Best regards,

**Review by Quetzacoalt91 — APPROVED** [review]
OK to merge this PR. However, may I ask you a last rebase @prestamodule ?

Thanks

**Comment by aleeks** [comment]
Hello @prestamodule ,
Can you rebase this PR please ?
Regards.

**Comment by prestamodule** [comment]
@aleeks Rebase done.

**Comment by aleeks** [comment]
Thank you @prestamodule !

**Pull request merged**
