### PR TITLE
Adding attribute as part of attribute group feature flag

### PR DESCRIPTION
**Pull request by JevgenijVisockij**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Attribute groups were added as part of feature flag, but attribute actions were not added(however they are not yet implemented.) So adding them here to this PR.
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      |  Attribute actions must work as part of of attribute groups feature flag here. https://github.com/PrestaShop/PrestaShop/pull/30035 |

### CODE REVIEW

**Review by jolelievre — DISMISSED** [review]
Thanks @JevgenijVisockij 

I see you created a PR only dedicated to attribute pages, and you're right the same feature flag should be used for both Attribute and AttributeGroup

Do you plan on creating small PRs for all the other commented legacy links? or a big one for all of them?

**Comment by JevgenijVisockij** [comment]
> Thanks @JevgenijVisockij
> 
> I see you created a PR only dedicated to attribute pages, and you're right the same feature flag should be used for both Attribute and AttributeGroup
> 
> Do you plan on creating small PRs for all the other commented legacy links? or a big one for all of them?

Yeah I created this separately as wanted to make sure this is how it should be. I won't have a separate PR for each feature flag but will probably add remaining ones in one or two PR's.

**Review by jolelievre — DISMISSED** [review]

**Review by zuk3975 — DISMISSED** [review]

**Comment by sallemiines** [comment]
Hello @JevgenijVisockij 

Thanx for the PR ! 

I have checked this PR, when enabling  the feature flag for Attribute Groups page in the New & Experimental Features page 

the `Add new attribute button`  in catalog>attributes does not allow access to New Attribute page even the  `Edit`  button also is not functional ' , you can see the attached screen record 


https://user-images.githubusercontent.com/31663369/217844217-181d53c4-015c-45ed-9483-abeef4f78257.mp4




Could you please check  ? 

Waiting for your feedback ! 
Thank you !

**Review by jolelievre — COMMENTED** [review]
Woups @JevgenijVisockij 

seems like this PR is a bit off, I don't know if it needs to be rebased or if it targets the wrong branch but there are too many commits and modifications IMHO 😅

**Review by jolelievre — APPROVED** [review]
Thanks @JevgenijVisockij

**Comment by jolelievre** [comment]
Running campaign https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/4678815023

**Comment by zuk3975** [comment]
isn't some parts missing in FeatureFlagLang and FeatureFlagSettings?

**Review by jolelievre — CHANGES_REQUESTED** [review]
Hi @JevgenijVisockij 

@zuk3975 noticed there are inconsistencies between the values in https://github.com/PrestaShop/PrestaShop/blob/8ccee4b42d95b1ec3f38c11fdec1be92d593ae0e/install-dev/data/xml/feature_flag.xml#L14 that are in DB and the values handles in catalog in https://github.com/PrestaShop/PrestaShop/blob/011575da5417931edd6d116f309f3b8aa94c3a8c/classes/lang/KeysReference/FeatureFlagLang.php#L45-L46

Since it's related to the feature flag you use in this PR, could you please fix the XML file to match the wordings?

**Comment by zuk3975** [comment]
the wording has related comment here https://github.com/PrestaShop/PrestaShop/pull/31502#pullrequestreview-1381435660
probably we should consider renaming "attribute groups" to "attributes" and if we need to enable the values page it would be "attribute values". (in code it stays as AttributeGroup and Attribute, but just because it would probably be too much now to rename them all, though it would have made sense to name them Attribute and AttributeValue from beginning, to follow same principle as feature and feature value)

**Comment by JevgenijVisockij** [comment]
Since change here is minimal I moved it to attribute migration PR where it is also needed
https://github.com/PrestaShop/PrestaShop/pull/32150

**Pull request closed without merging**
