### PR TITLE
Catch PrestaShopException to validate sql-requests properly in PHP 8.X

### LINKED ISSUE #31551: BO - An exception is thrown when adding a bad query with an alias in a wrong position only with php8
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

An exception is thrown when adding a bad query only with php8

**PS8.1.0 with php 8.1 : NOK** :x: 

image

**PS8.0.1 with php 8.1 : NOK** :x: 

image

**PS8.1.0 with php 7.3 : OK** :heavy_check_mark: 

image

**PS8.0.1 with php 7.4 : OK** :heavy_check_mark: 

image

https://user-images.githubusercontent.com/92912932/221572216-3c520703-d01d-451d-9daa-459c8fe01bda.mp4

https://user-images.githubusercontent.com/92912932/221572665-9396f6c7-1384-443b-a31d-fb122680d182.mp4

So, **it's a regression with php8!**

### Expected behavior

An alert message "Bad query" is displayed!

### Steps to reproduce

1. Use PHP 8.1
2. Go to CONFIGURE > Advanced parameters > Database
3. Add new SQL query > add a bad query (for example An alias is set near SELECT *)

```
SELECT * CUST
FROM hana_customer 
WHERE  id_customer = 2
```
4. Add a name for the SQL query
5. Click on Save
6. See error > An exception is displayed!

### PrestaShop version(s) where the bug happened

8.0.1, 8.1.0

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

_No response_

### PR DESCRIPTION
**Pull request by boherm**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.0.x
| Description?      | Catch PrestaShopException to validate sql-requests properly in PHP 8.X
| Type?             | bug fix
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | See #31551
| Fixed ticket?     | Fixes #31551
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by matks — APPROVED** [review]
Nothing to add ;) great job!

**Review by 0x346e3730 — APPROVED** [review]
Nice work 👍

**Review by mflasquin — APPROVED** [review]
Thanks @boherm

**Review by MhiriFaten — APPROVED** [review]
Hello @boherm ,

I have checked your PR with **`PHP 8.0`** and **`PHP 8.1`**, the issue is well fixed.

QA :heavy_check_mark: 
Thank you !

**Comment by nicosomb** [comment]
Congrats @boherm ! The first PR of a long list.

**Pull request merged**
