### PR TITLE
CustomerPersister.php

### PR DESCRIPTION
**Pull request by Boxieeee**
in
`private function create(Customer $customer, $clearTextPassword)
    {
Hook::exec('actionCustomerAccountUpdate', array(
                'customer' => $customer
            ));
}

private function update(Customer $customer, $clearTextPassword, $newPassword)
    {
Hook::exec('actionCustomerAccountAdd', [
                'newCustomer' => $customer
            ]);
`

are not  the names reversed in the hooks, I mean the update has account add and  the create has Update

in create we have 
`$this->sendConfirmationMail($customer);
            Hook::exec('actionCustomerAccountUpdate', array(
                'customer' => $customer
            ));
`
shouldn't we have this
`
            Hook::exec('actionCustomerAccountUpdate', array(
                'customer' => $customer
            ));
$this->sendConfirmationMail($customer);
`
the email send should be later after the hook

and cant we have a new hook 
`
 private function create(Customer $customer, $clearTextPassword)
    {
//start new hook here
bla bla 
end
}

### CODE REVIEW

**Comment by xBorderie** [comment]
Please use the Forge to report issues: http://forge.prestashop.com/browse/BOOM/

Thank you! I think you can safely close this PR :)

**Comment by cvikenzi** [comment]
Hello,
in prestashop 1.7 RC0 version I found this mistakes:

1. In class CustomerPersisterCore is action hook "actionCustomerAccountUpdate" in create() method and action hook "actionCustomerAccountAdd" in update() method. Its need to be just switched.

2. In customers groups is not working hiding prices. If I set "show price" in some customer group to off, prices are still visible in catalog and also in product detail.

Hope I help you with it :)

**Comment by julienbourdeau** [comment]
You're merging `master` into `develop` 😱

**Comment by julienbourdeau** [comment]
Please redo your commit from `develop` branch and submit a new pull request.

**Pull request closed without merging**
