### PR TITLE
Allow custom redirect after login

### PR DESCRIPTION
**Pull request by cvng**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Hooks : Allow customizing the redirect URL after login
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | You can test it using `ps_qualityassurance` module, all the details available below
| Fixed ticket?     | N/A
| Related PRs       | N/A
| Sponsor company   | @PrestaShopCorp

1. Register the `actionAdminLoginControllerLoginAfter` hook and assign the `redirect` param:

```php
public function hookActionAdminLoginControllerLoginAfter(array &$params): void 
{
    $params['redirect'] = 'https://www.prestashop-project.org';
}
```

2. After login, you should be redirected to https://www.prestashop-project.org

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Makes sense! Thanks for contributing :)

**Comment by cvng** [comment]
Hi @kpodemski, thanks for reviewing :) I have updated the `How to test` section of the PR as requested. cc @Progi1984

**Review by zuk3975 — APPROVED** [review]

**Review by nicosomb — APPROVED** [review]

**Review by djoelleuch — APPROVED** [review]
Hello @cvng  , 
It's QA approved :heavy_check_mark:
Automated tests --> OK

[Untitled_ Feb 9, 2023 3_07 PM.webm](https://user-images.githubusercontent.com/115152460/217851532-75eadff8-b3a0-4b21-a14a-d3283b5a055f.webm)

Thank you for you PR :rocket:

**Comment by nicosomb** [comment]
Congratulations @cvng 🎉 

Thank you @cvng and @djoelleuch !

**Pull request merged**
