### PR TITLE
Fix for image change in zoom modal window

### PR DESCRIPTION
**Pull request by maximebiloe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.1.x
| Description?  | When combination for product change, then DOM is refresh so with previous code click function was not triggered.
| Type?         | bug fix 
| Category?     | FO
| BC breaks?    | no
| Deprecations? | /no
| Fixed ticket? | 
| How to test?  | Go to product with combination, change attribute, open modal with images and change image by clicking on thumbnail

### CODE REVIEW

**Comment by vincentbz** [comment]
Tested and ok, thanks !

**Comment by aleeks** [comment]
Thank you @maximebiloe & @iqit-commerce

**Comment by root-it** [comment]
This issue still exists on 1.7.1.1. (after upgrade)

**Comment by aleeks** [comment]
Hello @root-it ,
Did you upgrade with theme upgrade or without ? because it depends of classic theme

Regards

**Pull request merged**
