### PR TITLE
Removed multiple same and non-standard conform tag IDs

### PR DESCRIPTION
**Pull request by xitromedia**

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi,

Is there a problem you are trying to solve or you just dont like it ? :D

**Comment by xitromedia** [comment]
hi,

i tried to solve a bug and pulled a request, but there was an error.
i am not so familiar with github and i have no time for now also searching what i have done wrong with git beside solving amateurish bugs in ps.

maybe you or other ps developers have enough time to work on the ghosts they called.... :o)

regards
andré


-----------------------------------------------------
Firma xitroMEDIA - WebDesign | eCommerce | Werbung

Brockwitzer Str. 8
01640 Coswig

email: info@xitromedia.de
WWW: www.xitromedia.de

Telefon: 03523 - 77 400 40 ( +49 3523 77 400 40 )
Fax: 03523 - 533 321 ( +49 3523 533 321 )

Inhabender Geschäftsführer (CEO): Mag. iur. André Ahner (TU Dresden)

USt-Id-Nr.: DE270654862

-----------------------------------------
Diese eMail enthält vertrauliche Korrespondenz.
Sollten Sie nicht der richtige Empfänger sein,
dann löschen Sie diese eMail bitte umgehend.
Vielen Dank für Ihre Mühe.

This email may be confidential.
If you are not the right recipient,
we appeal to you to delete this email.
Thank you for your effort.


---------------------------------------------------
obige Antwort auf Ihre Nachricht 
vom Donnerstag, 22. Oktober 2015 um 10:27:
---------------------------------------------------
> Hi,
> Is there a problem you are trying to solve or you just dont like it ? :D
> —
> Reply to this email directly or view it on GitHub.
>   
>      

---------------------------------------------------

**Comment by julienbourdeau** [comment]
If you find a bug you are welcome to open a issue on forge.prestashop.com
PrestaShop 1.7 won't be using this code by the way.

**Comment by xitromedia** [comment]
I have posted a lot of bugs to forge.prestashop.com, but even important bugs are fixed there either not at all or much too late. Even new versions of PS contain bugs that were posted to a current version and then they will not be fixed anymore because they belong to an old version!?

So i thought to pull requests here will be more effective, especially because some developers adviced me to do so. But it seems that PS git is not much better than PS forge.

More and more i regret to post bugs at all and to waste my time here ..... 

Especially if i am asked by developers if the code they create work, when fixing the bug i posted!?  Are they the PS developers that should test extensively the code they write or am i an PS developer?!
Or if somebody like you says: we do not need to fix a bug in current version that is easily to fix, because it will not occur anymore in the new version of PS, while a lot of people will use the current version still a long time!?

Sorry....but i don´t, cannot  and probably will never understand the philosophy of PS development ... if there is any!

By the way: The bug i fixed here shows again evidently the professionality level of some developers here. Keeping tag-IDs unique on a html doc is basic knowledge of first hours of first semester! How can somebody produce such an amateurish code ?! There are so many amateurish bugs in PS that i nearly every day think about to say good by to PS. But the time i already invested in PS nobody gives back to me.

I think there should be a quality control for developers here. Not everybody who calls oneself programmer should be allowed to program here.

**Comment by julienbourdeau** [comment]
Hey, sorry I think we got off the wrong foot.

Of course it's wrong to have multiple ID's but I was wondering if you made this PR if you encountered an actual issue with it (like JavaScript not updating the correct row or something). And that's why I told you to open a issue on the forge.
For this kind of problem (purely related to code) it's much better to open a pull request indeed. The person who advised you was right.

What I meant by "_PrestaShop 1.7 won't be using this code by the way._" is that the whole theme will be removed. To often we introduced bugs because we tried to fix something not so important, so im trying to be careful now that PrestaShop 1.7 is on the way. This code have been here since the very first stable version of PrestaShop 1.6 (https://github.com/PrestaShop/PrestaShop/commit/ba534ae2fcd4f4304580a5ed5b4533a3820b63ed) so changing it might have side effects now. I know there is **very** small chance :)

> Especially if i am asked by developers if the code they create work, when fixing the bug i posted!?
It's a good idea tho ! It's better to test different environments.

I've been reviewing a lot of pull request for the past 2 days, so I might have been a bit rough with you. Again, please accept my apologies.

**Comment by gRoussac** [comment]
Hi,

Sorry but I belive this bad id was not introduced in https://github.com/PrestaShop/PrestaShop/commit/ba534ae2fcd4f4304580a5ed5b4533a3820b63ed but https://github.com/PrestaShop/PrestaShop/commit/dd86f782fc833e54c7d4629fced090fa96b845ee

Regards

**Comment by gRoussac** [comment]
Hi,

Sorry this was introduced in https://github.com/PrestaShop/PrestaShop-1.5/commit/8b3aa236043b394f1def581be09300584dc13fbb and after that was kept for back ward compatiblity I guess.

Regards

**Comment by xitromedia** [comment]
hello julien,

you are not rough with me. I think i was rough with you because i am annoyed about the PS at all. I apologize for that however i must say that.

The case for that is that i spend since over 3 years day for day a lot of hours for fixing bugs or doing workarounds with PS to get someday a stable system that i can offer to my customers without headache. Every day i find a new bug or nonsense/bad code, where i say to myself: How amateurish is that?

You surely know that the law is very strict in germany and there are a lot of lawyers that only wait for even little mistakes for being allowed to admonish and sue shop owners. 

So it is is very annoying that PS has always and in every stable version again so many bugs that are partly even essential, like e.g. when prices are calculated wrongly. Many such bugs were fixed in past but then the same or similar bugs are newly created in a following version. It seems some or many PS developers do not learn from mistakes, else i cannot explain for myself why same bugs come back to code.
I think a shop system with wrongly calculated prices or taxes should be absolutely a NO GO. And always again i see forge posts concerning wrong calculations here and there!?

Often one bug is fixed and two new are created by the way. I think - and this is not only my opinion - it is a basic problem of the PS development: Too many things are done simultaneously. Too many things are done with 50% of energy instead of 100%. They are done too fast without sufficient and comprehensive testing, by too many people, that do not really adequately  know the PS-code and thar are not carefully enough or do not have enough programming experience to code within such a big flagship. 

The result is: PS users must spent a lot of time for bug-fixing, updating and bug-searching that should rather the developers do from start up. The quality of the whole code is neglected and PS is and will never be really "stable".

I appeal to you to invest more in quality controlling in relation to code and permitting programmers/developers to do things they should better not do.

And as long as i have the impression that amateurs work on and regularly downgrade the code, i will propably never really and extensively contribute to the PS development.

regards
André

**Comment by maximebiloe** [comment]
Hello,

Thanks for your contribution.
Unfortunately, `default-bootstrap` was replaced by a new theme in `develop`. If your fix is needed, could you remake you PR on `1.6.1.x`, please ?

Regards.

**Comment by gRoussac** [comment]
lol

**Pull request closed without merging**
