### PR TITLE
Upgrade cssjanus to 2.1.1

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Upgrade cssjanus to 2.1.1 . Diff between 2.1.1 and 2.1.0 is only internal https://github.com/wikimedia/php-cssjanus/compare/v2.1.0...v2.1.1
| Type?             | improvement
| Category?         | CO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | Automated tests should be enough
| Fixed ticket?     | 
| Related PRs       | If theme, autoupgrade or other module change is needed to make this change work, provide a link to related PRs here.
| Sponsor company   | Your company or customer's name goes here (if applicable).

### CODE REVIEW

**Comment by matks** [comment]
Tests https://github.com/matks/ga.tests.ui.pr/actions/runs/5223381272

**Review by matthieu-rolland — COMMENTED** [review]
several auto tests are failing... some tests can't even start because of a certificate issue it seems...

There's one that fails during tests, but I'm not sure if it's linked to this PR or not

**Comment by matks** [comment]
Re-running 😄 https://github.com/matks/ga.tests.ui.pr/actions/runs/5223381272

**Review by M0rgan01 — APPROVED** [review]

**Comment by matks** [comment]
Close and reopen to reset the CI

**Review by mflasquin — APPROVED** [review]

**Review by tleon — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @matks 

Thanks for your PR :rocket: 
Auto tests are :green_circle: https://github.com/hibatallahAouadni/testing_pr/actions/runs/5736270752/job/15550636935
(There's only API down, even on nightly) so it's a GO :heavy_check_mark: 

Thanks!

**Comment by nicosomb** [comment]
Thank you @matks!

**Comment by matks** [comment]
Thank you @nicosomb and @hibatallahAouadni 😄

**Pull request merged**
