### PR TITLE
Re-introduce server media

### PR DESCRIPTION
**Pull request by aleeks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Re-introduce server media
| Type?         | improvement
| Category?     | CO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | http://forge.prestashop.com/browse/BOOM-2181
| How to test?  | -

#### Important guidelines

* Make sure [your local branch is up to date](https://help.github.com/articles/syncing-a-fork/) before commiting your changes!
* Your code MUST respect [our Coding Standards](http://doc.prestashop.com/display/PS16/Coding+Standards) (for code written in PHP, JavaScript, HTML/CSS/Smarty/Twig, SQL)!
* Your commit name MUST respect our [naming convention](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message)!

### CODE REVIEW

**Comment by maximebiloe** [comment]
Thank you @aleeks

**Comment by maofree** [comment]
Hi
Can I know from which prestashop's version will be present again the 3 server media ?

thanks
bye

**Comment by xBorderie** [comment]
@maofree Since it's a "new" feature, it was merged for the next minor version at the times, which means 1.7.1.0.

**Comment by Quetzacoalt91** [comment]
@xBorderie, I'm not sure about this. I see we merged this PR on develop, not on 1.7.1.x branch

**Comment by xBorderie** [comment]
@Quetzacoalt91 It's [in the Beta 1](https://www.prestashop.com/en/developers-versions/changelog/1.7.1.0-beta1), in any case :)

**Pull request merged**
