### PR TITLE
No alert displayed when we click on "Save then add another value" button

### LINKED ISSUE #21252: BO - Features page - No alert displayed when we click on "Save then add another value" button
#### Describe the bug

In the BO > Catalog > Features page, there is no green alert when we click on "Save then add another value" button.
In the attribute page => ok

#### Expected behavior

image

#### Steps to Reproduce

1. Go to BO > Catalog > Features page
2. Click on 'Add new feature value'
3. Set date
4. click on "Save then add another value" button

#### Additional information

* PrestaShop version: 1770rc1, 1.7.6.8
* PHP version: 7.2

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | No alert displayed when we click on "Save then add another value" button
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/21252
| How to test?      | Check if an alert is display
| Possible impacts? | no impact

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/24327)

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by boubkerbribri — APPROVED** [review]
New alert displays when adding value and click on both buttons: :heavy_check_mark: 
Automatic regression tests: :heavy_check_mark: 

It's QA :heavy_check_mark: 
Thank you @okom3pom

**Comment by Progi1984** [comment]
@okom3pom No way. I wanted to restart Github Actions (one was crashed)  with closing and reopening. But your branch is removed. Could you push it, please ?

**Comment by ghost** [comment]
Oh my bad i deleted my fork after mistake i don't know the way

I made a new one ?

**Comment by Progi1984** [comment]
Yes, and if the code is identical, we approve directly.

**Comment by PululuK** [comment]
@okom3pom you can restore your branch.
Ex:. 
image

**Comment by ghost** [comment]
Thank you @PululuK i check

**Pull request closed without merging**
