### PR TITLE
Replace deprecated "create_function"

### PR DESCRIPTION
**Pull request by mvorisek**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Replace deprecated "create_function"
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | No new feature

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16632)

### CODE REVIEW

**Comment by mvorisek** [comment]
Any feedback? `create_function` usage is deprecated since PHP 7.2.

**Comment by PierreRambaud** [comment]
@mvorisek Thanks.  In fact, we already know, but this part of code are used only for tests, and are never executed :sweat_smile: We should refactor our test modules to only use what we want (one hook, install, uninstall, reset) and not all the useless code around.

**Comment by mvorisek** [comment]
Yes, I know, but I was getting warnings from out internal tests so I fixed it. Is this PR welcomed even or should I delete the PR?

**Comment by mvorisek** [comment]
@PierreRambaud Yes, I know, but I was getting warnings from out internal tests so I fixed it. Is this PR welcomed or should I delete the PR?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Let's approve this. One more review and merge without QA ;)

**Comment by mvorisek** [comment]
Can someone approve and merge?

**Comment by matks** [comment]
Sorry, it was a good idea to ping 😉

**Comment by matks** [comment]
Thank you @mvorisek

**Pull request merged**
