### PR TITLE
Remove the smoke tests campaign - Puppeteer 

### PR DESCRIPTION
**Pull request by nesrineabdmouleh**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Move the `01_install_shop` to the sanity campaign then remove the smoke tests. 
| Type?         | refacto
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | no
| How to test?  | npm run sanity-tests

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/15509)

### CODE REVIEW

**Review by SimonGrn — DISMISSED** [review]
Thanks @nesrineabdmouleh

**Review by boubkerbribri — COMMENTED** [review]
Thanks @nesrineabdmouleh 
Can you please update DOCKER.md file too

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]
Docker file needs to be updated.

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Comment by SimonGrn** [comment]
Thanks guys

**Pull request merged**
