### PR TITLE
Add select2 in large select options

### LINKED ISSUE #28065: Introduce select2 in long select options
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Add the select2 in the selectors with many options

image

### Describe the solution you'd like

Use select2 in follow pages : 
image

# Catalog

### Product 

- [x] Default Category (old and new page) 

### Supplier 

- [x] Country and state selector

### Manufacturer address

- [x] Country and state selector

# Customer

### Customer

- [x]  Default customer group 

### Address

- [x] Country and state selector

# Shipping

### Preferences

- [x] Default carrier 

# Shop parameters

###  General

- [x] Main Shop Activity selector

###  Order settings 

- [x]  Page for terms and conditions 

# Order

### Order

- [x] update status
- [x] Add form : payment and status selector

### Alternatives you've considered

_No response_

### Additional context

_No response_

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

### PR DESCRIPTION
**Pull request by PululuK**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop 
| Description?      | add select2 in large select options.
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/28065.
| How to test?      | See https://github.com/PrestaShop/PrestaShop/issues/28065.
| Possible impacts? | All pages BO described here https://github.com/PrestaShop/PrestaShop/issues/28065.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/28066)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
waiting for PM validation of the issue 👍

**Review by Progi1984 — CHANGES_REQUESTED** [review]
The issue #28065 waits for a @PrestaShop/product-team validation

**Review by matthieu-rolland — COMMENTED** [review]
meanwhile you can rebase your PR if you want (there's a conflict it seems)

**Comment by PululuK** [comment]
> meanwhile you can rebase your PR if you want (there's a conflict it seems)

Yep after @PrestaShop/product-team validation :)

**Comment by MatShir** [comment]
Nice job @PululuK thanks for your contribution !

**Review by Progi1984 — CHANGES_REQUESTED** [review]
@PululuK It's better. Could you remove in your Git history the merge commit, please ?

**Comment by MatShir** [comment]
Capture d’écran 2022-04-20 à 12 05 08
The layout seems broken in the order page :/

**Comment by PululuK** [comment]
> Capture d’écran 2022-04-20 à 12 05 08
> The layout seems broken in the order page :/

Nice catch @MatShir !
@NeOMakinG  can you please help me here ? Thanks

**Comment by PululuK** [comment]
Thank you @NeOMakinG  !!!

**Review by Progi1984 — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by SD1982** [comment]
LGTM thanks @PululuK !!

**Comment by NeOMakinG** [comment]
Thanks @PululuK , @SD1982 , @MatShir

**Pull request merged**
