### PR TITLE
Remove hard coded ads

### PR DESCRIPTION
**Pull request by ghost**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Remove hardcoded ads
| Type?             | improvement
| Category?         | BO
| BC breaks?        | yes
| Deprecations?     | no
| Fixed ticket?     | No issue
| How to test?      | No tests
| Possible impacts? | no impact
| Sponsor company   | @Touxten 

**:notebook: BC break** 
* Remove template `admin-dev/themes/default/template/controllers/modules/ad_bar.tpl`
* Remove property `$_modules_ad` in `AdminModulesController`

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26910)

### CODE REVIEW

**Review by matks — APPROVED** [review]
My eyes hurt when I read this code. Thank you for removing it.

**Review by PrestaEdit — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by matks — DISMISSED** [review]

**Comment by matks** [comment]
@PrestaShop/prestashop-maintainers I think we do not need QA for this PR, do we?

Also in theory it's a BC break as child classes might use this parameter, but this is unlikely.

**Comment by Progi1984** [comment]
@okom3pom Could you document the BC break ? After that, we can merge.

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Could you remove the template : `admin-dev/themes/default/template/controllers/modules/ad_bar.tpl` and its calls ?

**Comment by ghost** [comment]
Done, i don't find an other call for this file

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @okom3pom

**Pull request merged**
