### PR TITLE
Config

### PR DESCRIPTION
**Pull request by deneb-air**

### CODE REVIEW

**Comment by PrestaEdit** [comment]
Why ??! It's not logic... The purpose of have it in first time is to have some custom/override define like the mode dev, if you get it after, it's a no-sense.

**Comment by julienbourdeau** [comment]
Hi,

Thank you for your contribution.

I'd rather not let people override `defines_uri` unless there is a good reason. It's very much related to the way PrestaShop works. Do you use case to explain why you'd like to override it ?

Also you need to declare the custom ones before the core ones, otherwise you won't be able to override the define. PrestaEdit is right.

Thank you for watching your commit message tho :)

**Comment by deneb-air** [comment]
Hi.
This is useful when you need to create a new definition based on existing(not override it).
Ex.
```php
define('_MY_DOCS_CACHE_DIR_', _PS_CACHE_DIR_.'docs/');
Tools::safeDefine('_MY_API_LIST_', _PS_API_DOMAIN_.'/xml/my_list.xml');
```
But this commit breaks the existing order of initialization. It is bad.
I agree with you. It's not the best idea.
This can be solved by other way.
Sorry.

Thank you for feedback.

**Comment by xBorderie** [comment]
Thank you for this commit anyway, @deneb-air!

For your next commit, could you make sure to write a [correct commit message](http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message) and to put a lot more information on why you are doing this? 
Or, even better, submit an Improvement ticket [on the Forge](http://forge.prestashop.com/secure/Dashboard.jspa) so that we can discuss this beforehand :)

Thank you!

**Pull request closed without merging**
