### PR TITLE
Admin search - Transmit the search query param

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | 8.1.x
| Description?      | Dispatch the query parameter to the targetted pages
| Type?             | improvement
| Category?         | BO
| BC breaks?        | no
| Deprecations?     | no
| How to test?      | -
| Fixed ticket?     | #32895

### CODE REVIEW

**Comment by sowbiba** [comment]
Linked to https://github.com/PrestaShop/PrestaShop/discussions/32895

**Review by mflasquin — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]
Tiny addition, but if it is useful to you, I don't see the point of blocking it :)

**Review by MhiriFaten — COMMENTED** [review]
Hello @sowbiba,

Thank you for your RP but we need an issue related to it so that we can treat it and check the RP according to that.

**Review by FabienPapet — APPROVED** [review]
Not worth blocking this PR because it does not have any issue IMO. 🤔

**Review by boherm — APPROVED** [review]

**Comment by florine2623** [comment]
@FabienPapet @sowbiba @kpodemski 
How can this be tested ?
Should it be tested by a dev as we do not have steps to reproduce ?

**Comment by kpodemski** [comment]
@florine2623 yes, it can be tested by a dev, I didn't notice that @ps-jarvis is now adding Waiting for QA automatically

**Comment by kpodemski** [comment]
thanks @sowbiba 👍🏻

**Pull request merged**
