### PR TITLE
Allow everyone to track their order from guest tracking

### LINKED ISSUE #15605: Order as a guest > register with same email > order lost and cannot be tracked
**How to reproduce**
1. Order something as a guest with a single email address.
2. Register yourself in the store as a customer with this email adress.
3. Log out.
4. Go to guest tracking and try to track the order you made with the guest customer.
5. Does not work and says "Log in to your customer account to track your order".
6. You log in. Order is not there.
7. The order cannot be tracked.

**My personal thoughts on solution**
- If I order something two or more times as a guest, with the same email adress, the order should be assigned to the same original guest customer id.
- If I register my account, it should scan customer database for guest with the same email address and if found, it should convert that guest customer instead of creating a customer with duplicate address.

If solutions above are not possible, at least it should allow the guest to track the order, even if customer account is made.

**Additional information**
PrestaShop version: 1.7.6.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | This PR allows everyone to track their order from guest tracking screen. It fixes a problem, when if you ordered as a guest, than registered as a customer, you couldn't track our order in any way.
| Type?         | new feature
| Category?     | FO
| BC breaks?    | template update is needed
| Deprecations? | no
| Fixed ticket? | Fixes #15605 (Marked as duplicate, but there referenced issues are different, nevermind.)
| How to test?  | Go to guest tracking and track order of a guest and a customer.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/16872)

### CODE REVIEW

**Review by matthieu-rolland — COMMENTED** [review]
Thanks for your PR @Hlavtox 

Codewise, your contribution seems good to me 👍 , but I would like to be sure that the PM team approves of this feature...

@marionf @MatShir, what do you think?

**Comment by Hlavtox** [comment]
@matthieu-rolland @marionf @MatShir 

In Prestashop's current form:

- You make order as a guest.
- If you convert your guest to customer, everything is fine.
- BUT, if you register a customer manually, with the same email address, THEN:
- You go to guest tracking, enter reference and email and you cannot track it, because it finds a customer with that email.

With this change, I allow everyone to track their order. There is nothing wrong with a registered customer to track an order from guest tracking. We only don't want to show him the guest-conversion form, that's all.

Then, #10122 would not be a problem, let there be hundreds of guests with this email, who cares.

**Comment by matthieu-rolland** [comment]
> Then, #10122 would not be a problem, let there be hundreds of guests with this email, who cares.

I agree with you @Hlavtox ;)  that's why I took the time to review it, and even to test it on my machine, and it seems to work fine 👍  

But I can't send it to QA without the aproval of someone from the product team, since it changes the behavior of the guest tracking, and this precise solution was not mentioned or asked by them in prior issues.

**Comment by marionf** [comment]
@matthieu-rolland @Hlavtox 

It seems legit :+1:

**Comment by matks** [comment]
Great ! Thanks everybody, now let's have QA check everything's good and then we can merge this nice improvement 😄

**Review by matks — DISMISSED** [review]

**Comment by SD1982** [comment]
Waiting for a second review

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@Hlavtox Could you rebase your PR before going in QA ? Thanks

**Comment by Hlavtox** [comment]
@Progi1984 Up-to-date with develop

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Hlavtox** [comment]
@matks Can you also backport this to 1.7.7, if you merge it to develop, pleaseee? Would be nice to have customer zone working for 1.7.7! 🤜🤛

**Comment by matks** [comment]
> @matks Can you also backport this to 1.7.7, if you merge it to develop, pleaseee? Would be nice to have customer zone working for 1.7.7! 🤜🤛

I'd like to but the decision is not mine alone
ping @eternoendless @colinegin this PR fixes, on develop (target: 1.7.8), an old [bug](https://github.com/PrestaShop/PrestaShop/issues/9650#issuecomment-415055890)

Can I backport it to 1.7.7 ?

**Comment by colinegin** [comment]
Is it a risky PR ? Can it have an impact on other pages ?

**Comment by matks** [comment]
> Is it a risky PR ? Can it have an impact on other pages ?

It makes the "guest tracking" page more open on FO. Only front-office files are modified.

The only risk I see is with other guest tracking related behaviors, maybe implemented by modules.

**Comment by Hlavtox** [comment]
@colinegin

It only affects one and only page - guest tracking.

**Scenario**
You make an order and it's assigned to a guest customer.
There can be infinite numbers of guests with the same email and it does not produce any errors.
Then, you register a customer account manually, or make an order and check “register account”.
Now you have following user accounts:
- Account 1, guest, with order A
- Account 2, customer, with order B

**Current logic**
You go to track the order A.
Prestashop checks if there exists customer with this email. It finds, that there is a customer with the same email, and redirects you to login page.
This is wrong, because the order A is assigned to Account 1, not Account 2.
So, you cannot track it.

**What I did**
I removed this condition, so it lets you track it always.
I added a simple condition to template, to show “convert to customer” box only to guests.

**Comment by colinegin** [comment]
I'm all for it but i don't think @eternoendless will agree with me :p 
We should not add new bug fixes after code freeze. Wdyt @eternoendless ?

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

It is ok :heavy_check_mark: 
https://drive.google.com/file/d/1GL7Wo1_ugxXqZKfskFDwsjNLsAAimEcq/view?usp=sharing
Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Good!!! 🚀 

@eternoendless 1.7.7 PLZZZZZ 🙏

**Comment by Progi1984** [comment]
Thanks @Hlavtox

**Comment by alex4102** [comment]
Thanks @Hlavtox

**Comment by thepixelabs** [comment]
I have a new 1.7.6.5 installation, i also noticed this issue with new guest accounts. However no account was created for these guest accounts, i always get forwarded back to the homepage. Is this handled as well by this PR?

Is there any workaround if i manually edit any file? Thanks in advance

**Comment by Hlavtox** [comment]
@pixelicous Tell me the exact scenario what you do and what you think is wrong.

This just resolves following problem:
- You make XXX order as guest. So you have XXX guest accounts, you can track the order just fine.
- Now you make a normal user account and suddenly you could not track the orders you made as a guest.

**Comment by MatShir** [comment]
> I have a new 1.7.6.5 installation, i also noticed this issue with new guest accounts. However no account was created for these guest accounts, i always get forwarded back to the homepage. Is this handled as well by this PR?
> 
> Is there any workaround if i manually edit any file? Thanks in advance

@pixelicous 
Could you please provide us with more info (steps, video record... ) and create an issue ? We need more details to understand how we can reproduce your problem into a new issue.
Here, documentation if needed: http://build.prestashop.com/howtos/misc/how-to-create-bug-report/
Thank you!

**Comment by thepixelabs** [comment]
@hlavtox @MatShir hey guys, thank you for the quick response. of course, i'd be happy to.
@Hlavtox - Following what you say, i do have an issue then, this is a new order, new guest account.
I created a few test orders/users today, thus before i send details let me just reconfirm i am actually right at my claim.
also just upgraded to 1.7.6.6 so i need to test first and reply back with all information necessary in case i do stumble upon.

**Comment by thepixelabs** [comment]
@Hlavtox @MatShir 
Ok, i just checked, i do have an issue then.

1. I go to backoffice, created bogus product, a few basic details such as price etc
2. Browsing to my website, I pick that product, buy it, checkout using site (not paypal checkout or anything), i have my own domain so i just created a new email address
3. At checkout i choose paypal option (using developer sandbox paypal personal account), purchase the item
4. Received the order email to my inbox
5. Clicked on the link in the email or browsed manually to https://MY_DOMAIN_HERE/index.php?controller=guest-tracking (tried this also in incognito mode)
6. I write the email and order id in the form, click SEND and get forwarded to my regular homepage (no text related to the order)

It doesnt actually matter what i write in the order reference or email fields in the guest order tracking form, there is no form validation, i always get forwarded to my homepage.

The url i am forwarded to:
https://MY_DOMAIN_HERE/index.php?order_reference=ORDER_CODE_HERE&email=EMAIL_ADDRESS_HERE

It doesn't add the controller attribute to the URL apparently

If i use the correct code/email combination and write the address by myself then it works
https://MY_DOMAIN_HERE/index.php?controller=guest-tracking&order_reference=ORDER_CODE_HERE&email=EMAIL_ADDRESS_HERE

I am using a theme called "Apparel", it's a free theme, don't wish to disclose the company not sure if it's allowed.
I also use nginx, i have connected my shop successfully to external dropshipping and email services

**Comment by Hlavtox** [comment]
@pixelicous If you go to SEO & URL page in prestashop settings, do you have a rewrite filled for **guest-tracking** for that language?

**Comment by thepixelabs** [comment]
> @pixelicous If you go to SEO & URL page in prestashop settings, do you have a rewrite filled for **guest-tracking** for that language?

@Hlavtox 
Yes i do, screenshot below

image


I got here from #15536, maybe its the same issue ?

**Comment by thepixelabs** [comment]
@Hlavtox @MatShir 

Ok fixed it, i enabled "URL rewriting" under seo&urls. didnt quite get how it made it work and why it didnt without the friendly urls

**Pull request merged**
