### PR TITLE
Remove unused things in Media class

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Branch?           | develop
| Description?      | Removes things in Media class that are unused for whole 1.7 lifetime.
| Type?             | refacto
| Category?         | FO
| BC breaks?        | yes
| Deprecations?     | no
| How to test?      | Open front office and check that everything works normally.
| UI Tests          | 
| Fixed issue or discussion?     | 
| Related PRs       | 
| Sponsor company   |

### CODE REVIEW

**Review by tleon — APPROVED** [review]

**Review by matks — COMMENTED** [review]
So crazy, indeed I can't find any usage of this code and it was never deprecated

What is this sorcellery? 😄

**Comment by Hlavtox** [comment]
@matks I was searching for unused constants and came accross this `define('_PS_JQUERY_VERSION_', '3.4.1');`, which is outdated BTW. That lead me into the Media class after some time, looked around and saw that this is some history forgotten. :D

**Review by matthieu-rolland — APPROVED** [review]
👍

**Comment by matthieu-rolland** [comment]
launching some ui tests just in case: https://github.com/matthieu-rolland/ga.tests.ui.pr/actions/runs/6880944504

edit: re-ran failed test

**Review by M0rgan01 — APPROVED** [review]

**Comment by Hlavtox** [comment]
@PrestaShop/qa-automation Guys can you check the failed tests? I think it's not related and maybe it's the think you fix here https://github.com/PrestaShop/PrestaShop/pull/34590?

**Comment by nesrineabdmouleh** [comment]
Hello @Hlavtox 
Yes exactly ! It's a random error in the nightly => Not related to the PR

**Comment by Hlavtox** [comment]
OK, so merging, nothing else to test :-)

**Pull request merged**
